### ISSUE TITLE
[Feature] passwordless email sign in

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#1000]
Firebase announced set of new authentication features recently:
https://firebase.googleblog.com/2018/04/whats-new-in-firebase-authentication.html

I am wondering if support for these can be added easily to v4? Particularly passwordless sign in feature.

**Comment by Salakar** [comment]
![image](https://user-images.githubusercontent.com/5347038/38986563-aeb90eec-43c4-11e8-8162-4b7be2f6e8ef.png)

In short, on the TODO but PR's also welcome!
