### ISSUE TITLE
Cannot access firebase.database.ServerValue.TIMESTAMP

### ISSUE THREAD

**Issue by sequencer08** [invertase/react-native-firebase#1003]
### Issue

undefined is not an object (evaluating 'firebase.database.ServerValue.TIMESTAMP')

### Environment

```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.11.1  Yarn: Not Found
  npm: 3.10.10  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4697961
Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1  react-native: ^0.55.2 => 0.55.2
```

1. Application Target Platform: macOS Sierra
2. RNFirebase Version: Latest version

**Comment by Salakar** [comment]
@sequencer08 can you show us your code usage where you're trying to use timestamp + your import of RNFirebase?

**Comment by sequencer08** [comment]
Hi @Salakar . The issue has been resolve. I'm passing the the firebase config as:

`const firebase = RNFirebase.initializeApp({...});`

then call it on

`reactReduxFirebase(firebase, {...});`

which results TIMESTAMP became null. It should be:

```
RNFirebase.initializeApp({...});
reactReduxFirebase(RNFirebase, {...});
```

Cheers! 😃

**Comment by Salakar** [comment]
@sequencer08 and that's why I kept asking for you to show me that part 🙈 

![image](https://user-images.githubusercontent.com/5347038/39115734-86dd1198-46da-11e8-9e80-e599af16a2cb.png)

But you've sorted it, so all is well!

**Comment by staticreactor** [comment]
> Hi @Salakar . The issue has been resolve. I'm passing the the firebase config as:
> 
> `const firebase = RNFirebase.initializeApp({...});`
> 
> then call it on
> 
> `reactReduxFirebase(firebase, {...});`
> 
> which results TIMESTAMP became null. It should be:
> 
> ```
> RNFirebase.initializeApp({...});
> reactReduxFirebase(RNFirebase, {...});
> ```
> Cheers! 😃

Hi.
where do you write it?
@Salakar @sequencer08

**Comment by nwaughachukwuma** [comment]
@akinkoker the uploadFile method from getFirebase hooks into **fileMetadataFactory** callback in the reactReduxFirebase config object as defined [here](http://react-redux-firebase.com/docs/recipes/upload.html#change-file-metadata) . You can use this to modify how the file's meta data is written to the database. What I have done is to add a Server.TIMESTAMP somewhere there. See my implementation below.

```
import RNFirebase from 'react-native-firebase; // <-- somewhere up in the file
...

// same config that goes to reactReduxFirebase(firebase, reduxFirebaseConfig)
const reduxFirebaseConfig = { 
  userProfile: 'users',
  useFirestoreForProfile: true,
  presence: 'presence',
  fileMetadataFactory: (uploadRes, firebase, metadata, downloadURL) => {
    // upload response from Firebase's storage upload
    firebase.database.ServerValue = RNFirebase.database.ServerValue; // <-- this is where I hooked it
    const { metadata: { name, fullPath } } = uploadRes
    // default factory includes name, fullPath, downloadURL
    return {
      name,
      fullPath,
      downloadURL
    }
  }
};
```
