### ISSUE TITLE
Enabled proguard with only one optional package

### ISSUE THREAD

**Issue by patlux** [invertase/react-native-firebase#1004]
Hello,

does anyone have a working project setup with **enabled** proguard?

I only need the optional messaging package for my project, but receiving errors like:

```
Warning: io.invertase.firebase.Utils: can't find referenced class com.google.firebase.database.DataSnapshot
``` 

How can I fix this errors without to add all optional packages to my project?

**Comment by Salakar** [comment]
@patlux hmm this looks like it might be us - will get a fix up shortly and will be release as part of v4.0.5

**Comment by Salakar** [comment]
@patlux this has been pushed - will release to npm shortly. Thanks for the report!

**Comment by Salakar** [comment]
Published: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.5  - should fix your issue - let me know if you have any other proguard weirdness

**Comment by Salakar** [comment]
Can I see your `MainApplication.java` file source?

**Comment by patlux** [comment]
```diff
import android.app.Application;
import com.facebook.react.ReactApplication;
+ import io.invertase.firebase.RNFirebasePackage;
+ import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
+          new RNFirebasePackage(),
+          new RNFirebaseMessagingPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

**Comment by Salakar** [comment]
@patlux I see you still have the optional dependencies listed in your `app/build.gradle` though - can your try removing them now?

**Comment by patlux** [comment]
@Salakar I already did that to test the new v4.0.5 release.

E.g.: If I remove the `implementation "com.google.firebase:firebase-crash` line, the following warnings still exists:

```
Warning: io.invertase.firebase.crash.RNFirebaseCrash: can't find referenced class com.google.firebase.crash.FirebaseCrash
Warning: io.invertase.firebase.crash.RNFirebaseCrash: can't find referenced class com.google.firebase.crash.FirebaseCrash
Warning: io.invertase.firebase.crash.RNFirebaseCrash: can't find referenced class com.google.firebase.crash.FirebaseCrash
Warning: io.invertase.firebase.crash.RNFirebaseCrash: can't find referenced class com.google.firebase.crash.FirebaseCrash
Warning: io.invertase.firebase.crash.RNFirebaseCrash: can't find referenced class com.google.firebase.crash.FirebaseCrash
Warning: io.invertase.firebase.crash.RNFirebaseCrash: can't find referenced class com.google.firebase.crash.FirebaseCrash
```

**Comment by Salakar** [comment]
The below is what seems to work for me, though it's probably not the best solution. I'm not exactly a proguard wizard so some advice would be welcome :)

```pro
-keep public class com.google.firebase.* { public *; }
-dontwarn com.google.firebase.**

-keep public class com.google.android.gms.* { public *; }
-dontwarn com.google.android.gms.**

# if using notifications from RNFirebase
-keep public class me.leolin.shortcutbadger.* { public *; }
-dontwarn me.leolin.shortcutbadger.**
```

**Comment by testshallpasswork** [comment]
@Salakar @patlux I went a step further and added: 

```pro
-keep public class io.invertase.firebase.* { public *; }
-dontwarn io.invertase.firebase.**
```

 I do share the same concern if this is ideal.

**Comment by oakis** [comment]
@testshallpasswork I did the same as you, and it should be documented in react-native-firebase docs.

**Comment by chrisbianca** [comment]
Please feel free to submit a PR to the documentation.

**Comment by oakis** [comment]
@chrisbianca I have submitted a pull request. https://github.com/invertase/react-native-firebase-docs/pull/74

**Comment by chrisbianca** [comment]
Thanks @oakis, this is now merged, so I'm closing this issue.

**Comment by kkusanagi** [comment]
This issue still occur for React native 0.60.5.
    "react": "16.9.0",
    "react-native": "^0.60.5",
    "react-native-firebase": "^5.5.6"

Are we really need to add this proguard rules?

As for older version, don't required.
		"react": "^16.6.1",
		"react-native": "^0.59.10",
		"react-native-firebase": "^5.2.2",

**Comment by Salakar** [comment]
@kkusanagi please raise a new issue if possible - it's hard to track comments on old closed issues - thanks 👍
