### ISSUE TITLE
onSnapshot QueryListenOptions not working

### ISSUE THREAD

**Issue by seddonm1** [invertase/react-native-firebase#1009]
### Issue

Hi,
I am using "react-native-firebase": "^4.0.4" and am not seeing the effects of `includeQueryMetadataChanges` through a query snapshot listener.

Here is how I am calling the snapshot listener:
```javascript
        // subscribe to users collection
        this.unsubscribeUserCollection = firestore.collection(`users`).onSnapshot({
            includeDocumentMetadataChanges: true,
            includeQueryMetadataChanges: true
        }, this.onCollectionUpdate)
```

My snapshot holds:
`_metadata: { fromCache: false, hasPendingWrites: true }`
and i am expecting a second event shortly after the first with a successful write (which I can see via the Firebase web UI.
`_metadata: { fromCache: false, hasPendingWrites: false }`

Interestingly the _queryOptions key of the snapshotEvent object (`snapshotEvent._queryOptions`) is an empty object so it looks like the `onSnapshot.QueryListenOptions` are not being set corretly. This is on both iOS and Android. 

### Environment

Both iOS and Android

1. Application Target Platform:

macOS Sierra

2. Development Operating System:

Latest build for both

3. Build Tools:

^0.55.3

4. React Native version:

^0.55.3

5. RNFirebase Version:

^4.0.4

6. Firebase Module:

Firestore

**Comment by thevishnupradeep** [comment]
Any update on this?
