### ISSUE TITLE
Can't run on android  (Google Play Services is required)

### ISSUE THREAD

**Issue by konstantin-mohin** [invertase/react-native-firebase#101]
Hi, thanks for the awesome library,

I have exact the same problem [46](https://github.com/invertase/react-native-firebase/issues/46),
I run my app on a real device LG G5 with Android 6.1,
Google Play services 9.2.56

it's not clear what should I update ? 
I also tried with errorOnMissingPlayServices option, but got another error: "Application has not been registered....."

I also tried to run the app on Android 7 and it's working fine.

**Comment by HofmannZ** [comment]
See [this part of the docs](http://invertase.io/react-native-firebase/#/faqs?id=android-turning-off-google-play-services-availability-errors):
```js
import RNFirebase from 'react-native-firebase';

const configurationOptions = {
  debug: __DEV__ ? '*' : false,
  errorOnMissingPlayServices: false,
};

const firebase = RNFirebase.initializeApp(configurationOptions);

export default firebase;
```

**Comment by Salakar** [comment]
Your first issue is as @HofmannZ mentioned, the second issue about application not being registered means you haven't followed the `firebase add to sdk` wizard on the firebase console and setup the `google-services.json` file - either that or you incorrectly typed the package name of your app when you set it up. See http://invertase.io/react-native-firebase/#/firebase-setup

**Comment by konstantin-mohin** [comment]
@Salakar @HofmannZ 

thanks friends, 
I've fixed the issue,
