### ISSUE TITLE
Build error on starter kit

### ISSUE THREAD

**Issue by Rezania815** [invertase/react-native-firebase#1014]
### Issue

A problem occurred configuring root project 'RNFirebaseStarter'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find builder.jar (com.android.tools.build:builder:3.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.1.0/builder-3.1.0.jar

### Environment

1. Application Target Platform: Android

2. Development Operating System: Windows 10

**Comment by chrisbianca** [comment]
Sounds like you're on an old version of gradle... `google()` is only available in Gradle 3.x upwards
