### ISSUE TITLE
'FirebaseAnalytics/FirebaseAnalytics.h' file not found

### ISSUE THREAD

**Issue by andr3a88** [invertase/react-native-firebase#1016]
### Issue: Cannot build the project

After updating `RNFirebase´and `Firebase` iOS SDK cannot build the project:

+ `'Firebase.h' file not found with <angled> include; use "quotes" instead` in RNFirebaseUtil.h
+ `'FirebaseAnalytics/FirebaseAnalytics.h' file not found` in Firebase.h
+ `In file included from .../node_modules/react-native-firebase/ios/RNFirebase/admob/RNFirebaseAdMobRewardedVideo.m:2:`

### Environment

iOS 11.3
macOS High Sierra
Xcode 9.3 
ReactNative 0.55.1
RNFirebase Version: 4.0.5

Firebase version: 
Firebase 4.13.0
FirebaseAnalytics
FirebaseCore 4.0.20

**Comment by jeanregisser** [comment]
Do you use CocoaPods for the Firebase and RNFirebase?

**Comment by AndreiCalazans** [comment]
Environment
OS: macOS High Sierra 10.13.4
Node: 9.4.0
Yarn: 1.3.2
npm: 5.6.0
Watchman: 4.7.0
Xcode: Xcode 9.2 Build version 9C40b
Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
react: 16.3.1 => 16.3.1
react-native: 0.55.1 => 0.55.1



I'm having the same issue. I was able to get passed the Firebase.h by adding Firebase.h into `project_root/ios/Firebase/Firebase.h` .

but I'm still getting the second error. 

In `Firebase.h`
``` 
'FirebaseAnalytics/FirebaseAnalytics.h' file not found
```


I installed it manually, I'm not using CocoaPods.

### Steps to reproduce:

1. yarn add react-native-firebase
2. react-native link react-native-firebase
3. Add GoogleService-Info.plist to /ios/appName/
4. Drag Firebase framework files to project root inside xcode as the README of Firebase specified
5. Add the -ObjC flag to "Other Linker Settings":

**Comment by chrisbianca** [comment]
Please take a look at option 2 of https://rnfirebase.io/docs/v4.0.x/installation/ios#1.3.-Install-Firebase-Library

This explains that if you're not using cocoapods, you need to add the frameworks to an `ios/Firebase` folder for them to be picked up by RNFirebase.

**Comment by AndreiCalazans** [comment]
Thanks @chrisbianca I totally missed out on that.

For anyone else trying to get this to work manually. The following steps worked for me.

1. yarn add react-native-firebase
2. react-native link react-native-firebase
3. Add GoogleService-Info.plist to /ios/appName/
4. Download the Firebase sdk zip.

*Note: Here instead of following the readme inside the Firebase folder you downloaded follow the below steps.*

5. Create a Firebase folder in `root/ios/Firebase`.
6. Copy the folder `Analytics` and `all other module folders you pretend to use`, the `module.modulemap` file and `Firebase.h` inside to `root/ios/Firebase`.
7.  In xcode and in your build settings for your project (You need to have your project selected under targets and not just under Project). search for `Header Search Paths` and add this `$(SRCROOT)/Firebase`

8. Then Search for `Framework Search Paths` and add this `$(SRCROOT)/Firebase`.

9. Search for `Other Linker Settings` and add the -ObjC

10. in  `ios/[YOUR APP NAME]/AppDelegate.m` add `#import <Firebase.h>` at the top.

11.  still in `AppDelegate.m` add `[FIRApp configure];` in the beginning of the method  `didFinishLaunchingWithOptions:(NSDictionary *)launchOptions`.


Once you have done the above steps rebuild your app and it should be fine.

**Comment by wbattel4607** [comment]
@chrisbianca any idea why we're getting the same error even though we have always used Cocoapods? We started getting this error after the iOS SDK had their hiccup with 4.12.0. We now get this no matter what version we use.

<img width="846" alt="screen shot 2018-04-28 at 8 12 44 pm" src="https://user-images.githubusercontent.com/13490339/39402291-a4d85fa0-4b20-11e8-9a24-8cda0f92e942.png">

```
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios/RNFirebase.podspec'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Performance'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'
```

```

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 6.10.3
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3
  react-native-firebase: 4.0.6 => 4.0.6
```

**Comment by wbattel4607** [comment]
Actually, I can't get it to work even if I do include+link the SDK in the ios directory. I followed the instructions shared by AndreiCalazans but no bueno.

I don't have any idea what changed between it working and not working. I'm using version control and can't find any changes to the Podfile, Podfile.lock, etc...

**Comment by malangaveuday** [comment]
@AndreiCalazans, I am confused in this two files the module.modulemap file and Firebase.h, I am not able to see this in react-native-firebase sdk.

**Comment by kolohelios** [comment]
I wasn't able to do get what @loukandr suggests to work, but adding the Frameworks as individual files instead of the whole folder did work. Thanks to both @loukandr and @AndreiCalazans !

**Comment by Aung-Myint-Thein** [comment]
I have managed to followed @AndreiCalazans and @loukandr .. but after that i get a different error and it says "undefined symbols for architecture x86_64 react native" :( Anyone faced it and solved it before?

I am using the following:

"react-native": "^0.55.4",
"react-native-firebase": "^4.3.7",
 Firebase iOS SDK - 5.3.0

**Comment by Aung-Myint-Thein** [comment]
I set up using pod and it is working fine. So, maybe above comment is not valid anymore. Thanks guys! Followings are the steps I did in my project:

react-native unlink react-native-firebase
react-native install --save react-native-firebase
cd ios
pod init
pod update
pod install (will get some warnings but the above link shows how to solve them. open xcworkspace file in xcode and solve them.)
react-native link react-native-firebase
open xcworkspace file in xcode.
Build

**Comment by JulienMalige** [comment]
@AndreiCalazans your comment should be part of the doc ("without cocoapods" section)

**Comment by tenchoklang** [comment]
For anyone who is still having trouble, I had to modify @AndreiCalazans step 6. Instead of dragging the entire folder like the Analytics folder into the root/ios/firebase drag the contents within the folder, if your desired sdk file has a folder called RESOURCES drag the contents of that file too. As far as the executables if there is any they dont have to be added i think. And thank you @AndreiCalazans

**Comment by AndresCardonaDev** [comment]
HI Guys, i just ran into the same issue, and i read aggain the documentation from the Cocoapod, it says, that the pod for just Firebase needs to be added, then any sub module, so i leaved my configuration as follows and no more File not found exception or anything:

```
  pod 'Firebase', '~> 5.0.1'
  pod 'Firebase/Core', '~> 5.0.1'
  pod 'Firebase/Auth', '~> 5.0.1'
  pod 'Firebase/Database', '~> 5.0.1'
  pod 'Firebase/Firestore', '~> 5.0.1'
  pod 'Firebase/Messaging', '~> 5.0.1'
```

(Note, i don't know cocoapods, i come from maven world, but react-native happens and here i am :D, i think is better to set an specific version, and remember to run `pod update && pod install` on your project, as Firebase startup guide suggests

**Comment by MWSPL** [comment]
Removing pod 'Firebase/Messaging' and re-installing it solve the issue it seems for 

X-code - 10
swift - 4.2
Deployment target - 10.0

**Comment by bernhardt1** [comment]
@AndreiCalazans 

There is one crucial step you've missed that I had to work through to get my build to pass.

**@ step 4)** DO NOT DOWNLOAD THE IOS SDK THAT FIREBASE RECOMMENDS. You must check the supported versions table to make you iOS SDK version match with  the react-native version you are using + the react-native-firebase version you have installed: https://github.com/invertase/react-native-firebase/tree/v5.x.x#supported-versions---react-native--firebase

You can download the correct version from here: https://github.com/firebase/firebase-ios-sdk/releases/tag/5.20.2

**Comment by BartoszFicek** [comment]
If you use CocoaPods, just add these lines to your Podfile:
```
 post_install do |installer|
    rnfirebase = installer.pods_project.targets.find { |target| target.name == 'RNFirebase' }
    rnfirebase.build_configurations.each do |config|
      config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
    end
  end
```

**Comment by Air-Craft** [comment]
This worked for me. I'm guessing that firebase has nested folders  and the non-recursive default by CP doesn't find the modulemaps?

**Comment by anabeatrizzz** [comment]
@AndreiCalazans where can I find `Header Search Paths` in Xcode?

**Comment by KalvinWei** [comment]
> If you use CocoaPods, just add these lines to your Podfile:
> 
> ```
>  post_install do |installer|
>     rnfirebase = installer.pods_project.targets.find { |target| target.name == 'RNFirebase' }
>     rnfirebase.build_configurations.each do |config|
>       config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
>     end
>   end
> ```

Where to add? the end? inside `target 'wallet' do`?
