### ISSUE TITLE
How to downgrade this plugin, I'm using gradle 2.2.3, i don't want to upgrade gradle version

### ISSUE THREAD

**Issue by RameshkrishnanV** [invertase/react-native-firebase#1019]
### Environment

Android

1. Application Target Platform:

2. Development Operating System:

3. Build Tools:

gradle version 2.2.3

4. React Native version:
RN v 0.55

5. RNFirebase Version:

6. Firebase Module:

**Comment by RameshkrishnanV** [comment]
sorry myself i downgraded it.

**Comment by abhishiv** [comment]
Hey @RameshkrishnanV 

Which version did you ended up downgrading to?
