### ISSUE TITLE
Argument list too long: recursive header expansion failed at

### ISSUE THREAD

**Issue by enzomd** [invertase/react-native-firebase#1021]
**Versions**
macOS, iOS
react-native-firebase@3.3.1
react-native@0.55.3
Xcode 9.3
`pod --version` 1.5

I have `react-native-firebase` installed and working fine, with no mention of `pod 'React'` in my Podfile.

When I add a pod to my Podfile that depends on React 0.11, then run a `pod install`, then Xcode build, it fails with:

`RNFirebase:
Argument list too long: recursive header expansion failed at /Users/x/src/node_modules/react-native-firebase/ios/../../../ios/Pods/Headers/Private/gRPC-Core/grpc/src/core/lib/debug`

I created my project with `react-native init`, which by default had no `pod 'React'` in the Podfile.

How can I add pod packages that depend on `React 0.11` without RNFirebase failing at build time?

I can use `pod 'React', path: rn_path, subspecs` to use React 0.5* from `node_modules`, but it still gives the same error.

Im trying to install `react-native-maps`. [See the Podfile](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md#ios---cocoapods.).

`react-native-vector-icons` also causes the same error.

**Related**
https://github.com/invertase/react-native-firebase/issues/294
https://github.com/invertase/react-native-firebase/issues/808

**Comment by chrisbianca** [comment]
This has been fixed in v4.0.x
