### ISSUE TITLE
onMessage not working

### ISSUE THREAD

**Issue by JayricMok** [invertase/react-native-firebase#1023]
### Issue 1

Firebase onMessage not working.

    firebase.messaging().onMessage((message) =>{
      console.log("onMessage" + JSON.stringify(message));
    });

I tried to use Postman to send FCM https://fcm.googleapis.com/fcm/send , POST is successful with message_id return. However, `onMessage` listener not `console.log` my message. Permission everything go fine. Any idea for this ?

### Issue 2

Firebase onNotification and onNotificationDisplayed

    firebase.notifications().onNotification((notification) => {
      console.log("onNotification " + JSON.stringify(notification));
      //this._firebaseStreamInit(payload);
    });

    firebase.notifications().onNotificationDisplayed((notification) => {
      console.log("onNotificationDisplayed " + JSON.stringify(notification));
      // Process your notification as required
      // ANDROID: Remote notifications do not contain the channel ID. You will have to specify this manually if you'd like to re-display the notification.
    });

Also use Postman to send FCM https://fcm.googleapis.com/fcm/send , POST is successful with message_id return. Received notification, but in `console.log` get two error.

- Converting circular structure to JSON

- Unhandled JS Exception: Converting circular structure to JSON

### Environment

iOS

1. Application Target Platform:
macOS Sierra

2. Development Operating System:
Xcode 9.3

3. React Native version:
react-native-cli: 2.0.1
react-native: 0.53.0

4. RNFirebase Version:
"react-native-firebase": "^4.0.5"

**Comment by chrisbianca** [comment]
Issue 1: Can I see the message you're sending from Postman?

Issue 2: Not an error, it's because you're trying to console.log the notification which contains a reference to itself. See https://stackoverflow.com/a/42932117/5909648

**Comment by JayricMok** [comment]
@chrisbianca , this is the message I sent

	{
	  "to" : "/topics/specialtopic",
	  "priority" : "high",
	  "notification" : {
	    "body" : "This is a Firebase Cloud Messaging Topic Message!",
	    "title" : "FCM Message"
	  },
	  "data":{
	  	"name":"some name"
	  }
	}

**Comment by JayricMok** [comment]
@chrisbianca for issue 2 , how can i see what the given object of the `notification`

**Comment by chrisbianca** [comment]
That is a notification message which should go through `onNotification` not `onMessage`. To go through `onMessage` it needs to be just data:

```
{
  "to" : "/topics/specialtopic",
  "priority" : "high",
  "data":{
  	"name":"some name"
  }
}
```

For issue 2, you can either set a break point, or output the individual fields as defined here: https://rnfirebase.io/docs/v4.0.x/notifications/reference/Notification

**Comment by JayricMok** [comment]
@chrisbianca do you mean like this ?

    firebase.messaging(). onNotification((message) =>{
      console.log("onMessage" + JSON.stringify(message));
    });

**Comment by JayricMok** [comment]
@chrisbianca before update to 4.x , i was use 3.x and able to `onMessage` with notification message.

**Comment by chrisbianca** [comment]
Please check the release notes for 4.x - it details all the changes we made to messages and notifications and links to articles that detail why we've separated out notifications and messages: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0

For the stringify you'll need to do something like t his:

```
firebase.notification().onNotification((message) =>{
  console.log(`onMessage: title: ${message.title}; body: ${message.body}`);
});
```

Closing as this isn't an issue with the library.

**Comment by judemanutd** [comment]
@JayricMok in v4 this has changed and been separated.

**Comment by hrshs** [comment]
@chrisbianca I send this json but onMessage dosen't fire.
{
	"content_available":true,
  "data": {
  	"url":"channel://5",
  	     "text": "text updated",
      "post_id": "34",
      "img": "",
      "width": "0",
      "height": "0",
      "entity": [],
  "channel_id":13,
  "type":"I"
  },
  "to": 
    "fNLKufoD_FE:APA91bEdfYLAgCQKKuUv2fNFyVDnkfQ....[MyToken]"
 
}

**Comment by hrshs** [comment]
@chrisbianca I send this json as you say but onMessage dosen't fire

`{
	"content_available":true,
  "data": {
  	"url":"channel://5",
  	     "text": "text updated",
      "post_id": "34",
      "img": "",
      "width": "0",
      "height": "0",
      "entity": [],
  "channel_id":13,
  "type":"I"
  },
  "to": 
    "fNLKufoD_FE:APA91bEdfYLAgCQKKuUv2fNFyVDnkfQ....[MyToken]"
 
}`

**Comment by hrshs** [comment]
@chrisbianca  I send json as you say but onMessage doesn't fire.
``{
	"content_available":true,
  "data": {
  	"url":"channel://5",
  	     "text": "text updated",
      "post_id": "34",
      "img": "",
      "width": "0",
      "height": "0",
      "entity": [],
  "channel_id":13,
  "type":"I"
  },
  "to": 
    "fNLKufoD_FE:APA91bEdfYLAgCQKKuUv2fNFyVDnkfQqEM9pVllzmWHJ8OgtZx60fRGmUW7EdjwEZp4FnkE9lM7AYqz4h8hb6etHiB_roG6sLYCo80qSAcNv_-HKnuEzKUWcArZ5HfGnzx1ocVDEexg6kC-ghGthsa-veVvzY4xTRA"
  
}
