### ISSUE TITLE
Apps breaking due to change on Firebase Date object

### ISSUE THREAD

**Issue by FacuAcosta** [invertase/react-native-firebase#1024]
Our current project was breaking due to a change on Firebase Database. This is not being prompted anywhere unless you run the project with xCode and check the xCode logs. If you have a project and it's suddenly breaking, take a look at the following warning:

> The behavior for system Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
> To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
> 
> let db = Firestore.firestore()
> let settings = db.settings
> settings.areTimestampsInSnapshotsEnabled = true
> db.settings = settings
> 
> With this change, timestamps stored in Cloud Firestore will be read back as Firebase Timestamp objects instead of as system Date objects. So you will also need to update code expecting a Date to instead expect a Timestamp. For example:
> 
> // old:
> let date: Date = documentSnapshot.get("created_at") as! Date
> // new:
> let timestamp: Timestamp = documentSnapshot.get("created_at") as! Timestamp
> let date: Date = timestamp.dateValue()
> 
> Please audit all existing usages of Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.

**Comment by chrisbianca** [comment]
@FacuAcosta when you say your project was breaking, what do you mean?

We're aware of this change coming through, but as far as we're aware, the default behaviour at this point is to stick with the old Dates, and not automatically switch to Timestamps.

Unfortunately Timestamps are currently only supported on iOS and not Android.  Until it's available on both, we're unable to add this to react-native-firebase but will do as soon as it's available...

**Comment by FacuAcosta** [comment]
@chrisbianca Well, our project was suddenly crashing on production, now it's supposed to work. Probably It's not related to that warning but i wanted to post it just in case someone faces sudden crashes.

**Comment by chrisbianca** [comment]
Ok, I'm going to close this as it seems unrelated to the issue you were experiencing and we're aware of this change gradually filtering through.
