### ISSUE TITLE
Metrics for performance claim

### ISSUE THREAD

**Issue by brentvatne** [invertase/react-native-firebase#103]
Hi there! I noticed in the README that it says:

> All in all, RNFirebase provides much faster performance (~2x) over the web SDK.

I'm really curious to see the metrics you gathered for this! It seems like something that would be quite difficult to measure.

**Comment by Salakar** [comment]
@brentvatne good point, you're right this is something that is and has proven quite difficult to measure. 

We initially got these numbers when we first started building our [testing suite app](https://github.com/invertase/react-native-firebase/tree/master/tests). 

One of the features of the tests app is the ability to switch the tests between using the official web sdk or the RNFirebase implementation for comparative testing. Running the tests using the RNFirebase implementation vs using the Web SDK was almost 2-3x faster in terms of completion time (each test is timed and its run time is displayed upon completion). 

Admittedly though that this is more of a real world scenario vs a raw benchmark, the app makes use of redux and react navigation libraries both of which are JS based and compete with the web sdk on the JS thread.  

In terms of a raw benchmark - in an empty app that renders null the results are quite different:
![moo](https://cloud.githubusercontent.com/assets/5347038/25894958/d594b15a-3575-11e7-86f1-c56bb8d255eb.png)

As you can see they're pretty much on par with each other, the only exception being that the web sdk lazy connects on the first ref request hence the 1.6s on the first iteration. The query used is a `orderByChild` query with `startAt` and `endAt` query modifiers, see code below.

```javascript
  setInterval(() => {
    const now = performance.now();
    return firebase.database()
      .ref('matches')
      .orderByChild('date_unix')
      .startAt(1493942400)
      .endAt(1494028799)
      .once('value', (snapshot) => {
        console.log(performance.now() - now);
      });
  }, 2000);
```

I would like to expand on the documentation in terms of performance, do you have any recommended approaches for benchmarking in react native - especially JS vs Native? I'm a bit of a performance junkie myself so would be interested in a more effective approach.

**Comment by Salakar** [comment]
Closing as no response.

**Comment by brentvatne** [comment]
heya thanks for getting back to me! I was away on vacation. I don't have any suggestions for how to improve the benchmarks here, I was just curious in case to learn more about your methodology.

**Comment by Salakar** [comment]
@brentvatne no worries, welcome back :) 

But yep, it has been a bit of a grey area for me in terms of how to properly benchmark things in RN, guess it just has to be best effort benchmarking (for now, for me).
