### ISSUE TITLE
[Android] Collapsible Notification not collapsing

### ISSUE THREAD

**Issue by dgruseck** [invertase/react-native-firebase#1030]
### Issue

I'm trying to implement collapsible notifications, the second notification should replace the first if the collapsible key is the same. 
On iOS collapsible notifications are working perfectly, but on Android they are not getting collapsed.
I'm sending a notification with the Node Admin SDK, and in the [CloudMessaging docs](https://firebase.google.com/docs/cloud-messaging/admin/send-messages#android_specific_fields) you can find the section for the collapsibleKey on Android.

### Notification payload:
```javascript
{
  notification: {
    title: 'Title',
    body: 'Message',
  },
  android: {
    priority: 'high',
    collapseKey: key,
  },
  apns: {
    headers: {
      'apns-priority': '10',
      'apns-collapse-id': key,
    },
  },
}
```

### Displaying the notification in onReceive:
```
  notification.android.setChannelId('channel-key');
  firebase.notifications().displayNotification(notification);
```
Do you have any idea what is wrong here?

Thanks,
David

### Environment
```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.6.0
  Yarn: 1.6.0
  npm: 5.3.0
  Watchman: 4.7.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.2 AI-145.3537739

Packages:
  react: 16.3.1
  react-native: 0.55.3
  react-native-firebase: 4.0.6
```

**Comment by chrisbianca** [comment]
`collapseKey` is an option available for FCM Messages which gets the operating systems to collapse notifications when they are handled by the OS itself.

In this situation, you're choosing to control how to display the notification, so you'll need to set the `group` property if you want the notifications to group together:

https://rnfirebase.io/docs/v4.0.x/notifications/reference/AndroidNotification#setGroup

**Comment by dgruseck** [comment]
@chrisbianca 
Hey Chris,

but even if the app is killed the notifications don't collapse on android.
And if the app is open I want to replace one notification with another, the setGroup is just showing the notifications in a cluster. Is there any possibility to replace a notification.

Regards,
David

**Comment by chrisbianca** [comment]
Looks like the `collapseKey` parameter for Android should actually be `collapse_key` as per the docs: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidconfig

**Comment by dgruseck** [comment]
@chrisbianca

I tried all the different possibilities for the collapse_key with postman but none of these worked.
The only thing that worked was the tag, but it's not showing a preview of the newly received notification and seems not to be supported by react-native-firebase.

```
{
   "to" : "####",
   "notification" : {
     "body" : "Description",
     "title": "Collapsing 1",
     "collapse_key": "key",
     "tag": "tag1" <-- the only one that works

   },
   "android": {
     "collapse_key" : "key",
   },
   "collapse_key" : "key",
}
```

**Comment by atultiwaree** [comment]
> 

Thanks, using tag worked for me I'm able to see the title and body get replaced by new one, but what do you mean by preview ?
