### ISSUE TITLE
How do I loop through Firebase Storage? [react-native-firebase]

### ISSUE THREAD

**Issue by ukritTKK** [invertase/react-native-firebase#1032]
### Issue

I can get an image download URL of a single image via getDownloadURL() method but my storage have two images. I need to get and image download URL of multiple images file of the same folder in storage. How can I do that?

here's my code (single image)
`let userId = firebase.auth().currentUser.uid`
`let storageRef = firebase.storage().ref(userId)`
`storageRef.child('29-4-2018').child('ImageFile.jpg').getDownloadURL()`
`    .then((url) => {`
`
`        `    console.log('storageRef image downloadURL: ', url)`
`
`        `   this.props.setImageDownloadURLAction(url)        // redux action`
`})`
`.catch((error) => {
    console.log('Unable to get a download URL due to ' + error)
})`

### Environment

1. Application Target Platform:

        Android

2. Development Operating System:

        Windows 10

3. Build Tools:

        23.0.1

4. React Native version:

        0.54.4

5. RNFirebase Version:

        ^4.0.4

here's my storage files
![image](https://user-images.githubusercontent.com/29112628/39400245-f60cffc6-4b56-11e8-953b-168b48433d4d.png)

**Comment by chrisbianca** [comment]
@ukritTKK The Firebase Storage SDKs do not allow you to list the files within a directory - it expects you to know what the files are called and download them individually as you are doing above.
