### ISSUE TITLE
(ios)[v4.0.4 -> v4.0.6] Firebase.h not found in RNFirebaseAdMobRewardedVideo.m

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#1038]
### Issue

Upgrade from v4.0.4 to v4.0.6 caused iOS build to fail with following error
![screen shot 2018-05-01 at 11 44 27](https://user-images.githubusercontent.com/3154053/39467121-07a710ca-4d35-11e8-8a6c-7fc335005bf8.png)

Project is not using AdMob.

### Environment

1. Application Target Platform: iOS 10.3

2. Development Operating System: macOS High Sierra

3. Build Tools: XCode 9.3

4. React Native version: 0.55.3

5. RNFirebase Version: 4.0.6

6. Firebase Module: AdMob

**Comment by Salakar** [comment]
Are you able to try the change in this proposed PR: https://github.com/invertase/bridge/blob/master/lib/node/index.js#L22

**Comment by IljaDaderko** [comment]
@Salakar can do, could you point me to the file where this needs to be added in `node_modules/react-native-firebase` please? There is no bridge folder there.

**Comment by chrisbianca** [comment]
I think he meant this PR: https://github.com/invertase/react-native-firebase/pull/1017
Assuming you're using Cocoapods for RNFirebase?

**Comment by IljaDaderko** [comment]
@chrisbianca Just for firebase modules, not RNFirebase, that was linked normally.

**Comment by Salakar** [comment]
My bad, wrong link on clipboard! The PR @chrisbianca  suggested is what I was meant to link 🙈

**Comment by IljaDaderko** [comment]
@chrisbianca that solved my issue, something was wrong with one of the Google dependencies in the pod-file, had to run `pod update`, looks like they removed one version from cocoapods directory.

**Comment by chrisbianca** [comment]
Glad you're now sorted :D
