### ISSUE TITLE
Flow version too high?

### ISSUE THREAD

**Issue by danjersoft** [invertase/react-native-firebase#104]
I'm using React Native 0.40.0 and I'm unable to use any version newer than 1.0.0-alpha13 of react-native-firebase.

Seems that this is because you're using a newer version of Flow than what that version of React Native is using.

I don't use Flow currently so I'm sure I'm missing something. Any suggestions?

**Comment by Salakar** [comment]
Thanks for the issue @danjersoft - could you be a bit more specific in terms of the issue you're facing, are you getting packager errors relating to flow? Is your app redboxing?

**Comment by danjersoft** [comment]
Yes, I get a red box. Here's the output from the packager:
```
transformed 1175/1179 (100%)(node:23797) UnhandledPromiseRejectionWarning: 
Unhandled promise rejection (rejection id: 2072): SyntaxError: 
SyntaxError /.../node_modules/react-native-firebase/lib/modules/database/reference.js: 
Unexpected token, expected ) (188:73)
```

**Comment by Salakar** [comment]
@danjersoft can you go into your node modules and into react-native-firebase and revert [this commit](https://github.com/invertase/react-native-firebase/commit/912722d331e6a70015c36c49766fdbd0381693c7) and tell me if if you still get flow errors?

cc @Leeds-eBooks

**Comment by danjersoft** [comment]
I commented out that section in `react-native-firebase/.flowconfig`, but I still get the same error.

**Comment by chrisbianca** [comment]
I had this, and had to remove the flow annotations from the `transaction()` function at https://github.com/invertase/react-native-firebase/blob/master/lib/modules/database/reference.js#L378 in order to get it to run.

I haven't had a chance to figure out why those in particular were causing issues.  Any ideas @Leeds-eBooks ?

**Comment by Leeds-eBooks** [comment]
The only thing I can think is that `(?Error, boolean, ?Snapshot) => *` might be newish syntax – I think in the past you had to name all arguments in flow type definitions. @chrisbianca or @danjersoft can you try  changing that to `(e: ?Error, b: boolean, s: ?Snapshot) => *` and see if it fixes it?

**Comment by Leeds-eBooks** [comment]
@chrisbianca Why would @danjersoft's error message be referencing line `(188:73)`?

**Comment by chrisbianca** [comment]
I assume it's because the packager is stripping out all the comments, so the line numbers don't match.
I just updated the line to what you suggested and it worked for me...

**Comment by Leeds-eBooks** [comment]
Ok @danjersoft are you able to do the same to confirm that this fixes your issue? Then I will have a go at putting names back into all the code and submit a PR.

**Comment by danjersoft** [comment]
Yes, that fixed it for me as well. Thanks everyone for looking into this so quickly :)
