### ISSUE TITLE
Android: Displaying a notification fails when using <activity-alias /> as launcher

### ISSUE THREAD

**Issue by BrandonSmith** [invertase/react-native-firebase#1041]
### Issue

Displaying a notification fails when using <activity-alias /> as launcher

    <activity-alias
      android:name=".MainActivity"
      android:targetActivity=".SplashActivity"
      android:label="@string/app_name"
      android:launchMode="singleTop">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity-alias>

When I show a notification:

    try {
      firebase.notifications().displayNotification(notification)
    } catch (err) {
      console.log(err)
    } 

I get the error:

    Error: Could not find main activity class

This can be traced down to the [RNFirebaseNotificationManager#getMainActivityClass()](https://github.com/invertase/react-native-firebase/blob/19266d4bae83769b2977b7f709919d6b2f299a78/android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java#L548) method.

Thinking that getMainActivityClass makes too narrow of an assumption that the class the <activity-alias /> resolves to is, in fact, an actual class. Further, it seems that if the class is being used to construct a new Intent, can't you simply use the Intent itself and clone it using Intent's copy constructor?

### Environment

1. Application Target Platform:

Android

2. Development Operating System:

macOS

3. Build Tools:

3.1.1

4. React Native version:

0.54.4

5. RNFirebase Version:

4.0.6

6. Firebase Module:

notifications

**Comment by runia1** [comment]
@chrisbianca Is there anyway you guys could dedicate some time to making sure Notification callbacks work properly with apps that use Splash Screens?  

React Native seems to take some time to get going. During that time the default is to just display a white screen and because of that, almost every react native app has a splash screen so there is something to show the user besides a white screen during that boot up time.

Even if there is nothing to be done code wise in this library, it'd be worth it just to document some of the things developers may run into if say: *they use a splash screen*... and some workarounds or additional setup needed in those cases.

**Comment by BrandonSmith** [comment]
@chrisbianca My configuration that triggered this error is as follows. I have since fixed the issue by renaming classes to avoid `activity-alias`. It may be worth to note that `activity-alias` is often used, as it was in the case, to avoid breaking shortcuts that users have created. If the `android:name` changes, shortcuts break.

AndroidManifest.xml
```
<activity
  android:name=".SplashActivity"
  android:theme="@style/SplashTheme">
</activity>

<activity-alias
  android:name=".MainActivity"
  android:targetActivity=".SplashActivity"
  android:label="@string/app_name">
  android:label="@string/app_name"
  android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
  android:windowSoftInputMode="adjustResize"
  android:launchMode="singleTop">
  <intent-filter>
    <action android:name="android.intent.action.MAIN" />
    <category android:name="android.intent.category.LAUNCHER" />
  </intent-filter>
</activity-alias>

<activity
  android:name=".ReactNativeActivity"
  android:label="@string/app_name"
  android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
  android:windowSoftInputMode="adjustResize"
  android:exported="true" />
</activity>
```

SplashActivity.java
```
package ...;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

public class SplashActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Intent intent = new Intent(this, MainActivity.class);
        startActivity(intent);
        finish();
    }
}
```

**Comment by nicolasdanelon** [comment]
check this configuration. The intent-filter of MainActivity has android name: **android.intent.category.INFO**
```xml
    <activity
      android:name=".SplashActivity"
      android:label="@string/app_name"
      android:theme="@style/SplashTheme">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>

    <activity
      android:name=".MainActivity"
      android:label="@string/app_name"
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
      android:exported="true"
      android:windowSoftInputMode="adjustResize"
      android:screenOrientation="portrait"
      android:launchMode="singleTask">

      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.INFO" />
      </intent-filter>
```
