### ISSUE TITLE
RNFirebase/admob/RNFirebaseAdMobRewardedVideo Firebase.h file not found  

### ISSUE THREAD

**Issue by rickyansari** [invertase/react-native-firebase#1043]
### Issue

![firebase issue](https://user-images.githubusercontent.com/5939456/39525227-0843fbe2-4e39-11e8-966a-d26af428beb4.png)

1 error generated.

### Environment

1. Application Target Platform: iOS

2. Development Operating System:

3. Build Tools:

4. React Native version: 0.50.4

5. RNFirebase Version: 3.3.1

6. Firebase Module:

**Comment by Ehesp** [comment]
Can we see your Podfile please.

**Comment by rickyansari** [comment]
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'consumer_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for consumer_app
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKCoreKit'
    pod 'Bolts'
    pod 'GoogleSignIn'
    pod 'Fabric', '~> 1.7.2'
    pod 'Crashlytics', '~> 3.9.3'
    pod 'Firebase/Core'

end

**Comment by rickyansari** [comment]
Thank you very much for your time @Ehesp . The issue is resolved by changing the 
 pod **FirebaseCore**      To      pod **'Firebase/Core'**
