### ISSUE TITLE
rename 

### ISSUE THREAD

**Issue by javan10** [invertase/react-native-firebase#1045]
when I running the command "npm run rename", the package "node_modules/react-native-firebase/src/main/java/io/invertase/firebase is also renamed to the name of my_package. resulting in "node_modules/react-native-firebase/src/main/java/io/my_package/

the MainApplication.java does not matter the packages of the firebase.

**Comment by chrisbianca** [comment]
Moved to: https://github.com/invertase/react-native-firebase-starter/issues/27
