### ISSUE TITLE
admob not Banner show 

### ISSUE THREAD

**Issue by phuochoit** [invertase/react-native-firebase#1046]
ISSUE
When I show Banner 
 file name BannerAdComponet.js
`import React, { Component } from 'react';
import { View, TouchableWithoutFeedback } from 'react-native';
import firebase from 'react-native-firebase';
const Banner = firebase.admob.Banner;
const AdRequest = firebase.admob.AdRequest;
const request = new AdRequest();

class BannerAdComponet extends Component {
    constructor(props) {
        super(props);
        this.state = {};
    }
    render() {
        return (
            <View style={{ alignItems: 'center', marginTop: 5, justifyContent: 'center' , flex: 1}}>
                <Banner
                    size={"LARGE_BANNER"}
                    unitId={'ca-app-pub-1070789846238739/7160815396'}
                    request={request.build()}
                    onAdLoaded={() => {
                        console.log('Advert loaded');
                    }}
                    onAdFailedToLoad={(error) => {
                        console.log('====================================');
                        console.log('error-admob', error);
                        console.log('====================================');
                    }}
                />
            </View>
        );
    }
}

export default BannerAdComponet;`

And  show banner in new file 

`import React, { Component } from 'react';
import {View  } from 'react-native';

import BannerAdComponetfrom "./BannerAdComponet";
class HomeComponent extends Component {
    constructor(props) {
        super(props);
        this.state = { }
    }
    render() {
        return (
            <View style={{flex: 1}}>
                <BannerAdComponet />
            </View>
        );
    }
}

export default HomeComponent;
`

I get the error:
`The ad request was successful, but no ad was returned due to lack of ad inventory`

**Comment by Ehesp** [comment]
You don't have any ads which are able to show as a `LARGE_BANNER`. You need to add/buy inventory in the admob dashboard.
