### ISSUE TITLE
Loading dependency graph, done. App never loads.

### ISSUE THREAD

**Issue by adrice727** [invertase/react-native-firebase#1048]
### Issue
After updating `AppDelegate.m`, the bundler reaches `Loading dependency graph, done.` and then stops. I never get a loading `%` indicator and the app never loads.

Steps to reproduce:

1. Starting at clean `master` branch - OK
2. Copy `GoogleService-Info.plist` to `ios/[myapp]/` - OK
3. Run `pod init`, remove target  `appname-tvOSTests` from `Podfile`, run `pod update` - OK
4. Add `pod 'Firebase/Core’` to Podfile.  Uncomment `platform :ios,  ‘9.0’` line. - OK
5. Run `yarn add react-native-firebase` - OK
6. Update AppDelegate.m with `#import <Firebase.h>` and `[FIRApp configure] and run `react-native link react-native-firebase` successfully.  - LOADING DEPENDENCY GRAPH . . .

I've tried just about all of the usual tricks like `yarn --reset-cache`, uninstalling and reinstalling `watchman`, deleting `Pods` and reinstalling, etc., but no luck.  I've started a brand new project with `react-native init` and ended up at the same place. 

### Environment

iOS Simulator

1. Application Target Platform: `iOS` `macOS Sierra 10.12.6`
2. Development Operating System: `macOS Sierra 10.12.6`, `Xcode Version 9.2 (9C40b)` 
3. Build Tools: `yarn`
4. React Native version: `"react-native": "0.55.3"`
5. RNFirebase Version: `"react-native-firebase": "4.0.6"`
6. Firebase Module: `Core`

**Comment by adrice727** [comment]
Fixed.  `XCode` wasn't picking up my `GoogleService-Info.plist`.

**Comment by dillon** [comment]
@adrice727 I'm having this same issue. I'm not sure if `XCode` is picking up my `GoogleService-Info.plist` or not. How can you tell, and how did you end up fixing it?

**Comment by andrico1234** [comment]
@dillon hey, I had the same issue as well. To add the file to your Xcode project do the following

* open Xcode
* open folder and choose the ios directory of your project
* right-click 'app' in your finder bar on the left-hand side
* have it point to the `GoogleService-Info.plist` file

**Comment by dillon** [comment]
@andrico1234 thanks for the instructions. I couldn't find 'app' in the finder bar, but I clicked on `GoogleService-Info.plist` and say its Target Membership had `monitor` selected. I tried clicking monitorTests as well and saving but it didn't do the trick
<img width="971" alt="screen shot 2018-09-21 at 3 03 08 am" src="https://user-images.githubusercontent.com/8380979/45865289-06423800-bd4b-11e8-9d0e-2b05eab14424.png">
