### ISSUE TITLE
downloadFile(...).then is a Promise instead of a function returning a Promise

### ISSUE THREAD

**Issue by Damnum** [invertase/react-native-firebase#105]
This line seems to be wrong: https://github.com/invertase/react-native-firebase/blob/master/lib/modules/storage/task.js#L55

then should be a function not a promise right?

I changed it to

`this.then = promise.then.bind(promise);`

and it works

**Comment by davidtrogers** [comment]
@Damnum I noticed the same thing yesterday when trying to upload files. The [type def](https://github.com/invertase/react-native-firebase/blob/80b519158fa0132d9126366fe1b07d8da8ed83b5/lib/modules/storage/task.js#L45) will need to be changed too to match up with catch:
``` javascript
  then: Promise<*>
  catch: () => Promise<*>
```

**Comment by andfk** [comment]
+1

**Comment by Salakar** [comment]
@Damnum @davidtrogers the fix for this is landing in v2. In the meantime you can use the callbacks instead of promises as a workaround.

**Comment by andfk** [comment]
@Salakar FYI and for interested people, I ended resolving the promise that comes from: `firebase.storage().ref('/image/1').putFile(image.uri).then`. Notice the final **`.then`**. That one returns the promise we need with the upload info. Then as soon as this is fixed, we´ll have to remove all `.then`.

**Comment by bennygenel** [comment]
@Salakar Hi! Can you please give an example of how to use callbacks please.
I tried this but it didn't work.

```
firebase.storage()
    .ref('/images/' + id)
    .putFile(image.path, (uploadedFile)=>{
      console.log('uploadedFile',uploadedFile);
    });
```

**Comment by Salakar** [comment]
@bennygenel I believe this was fixed in v1.1.0, try updating the npm module

**Comment by andfk** [comment]
@bennygenel yeah, I can confirm the storage works perfectly on v1.1.0

**Comment by bennygenel** [comment]
@Salakar & @andfk Thanks for the heads up. I updated and it fixed the problem.
