### ISSUE TITLE
[CloudMessaging] Invalid argument type 'void' to unary expression in AppDelegate.m

### ISSUE THREAD

**Issue by steverob** [invertase/react-native-firebase#1053]
### Issue

I am following the iOS documentation for Firebase Cloud Messaging and after I copied the following code into my `AppDelegate.m`, I am seeing this error - `Invalid argument type 'void' to unary expression`

Additions to `AppDelegate.m`

```
  // Firebase Configurations
  [FIRApp configure];
  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
  
  -(void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
    [RNFirebaseMessaging didReceiveLocalNotification:notification];
  }
  
  - (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo {
    [RNFirebaseMessaging didReceiveRemoteNotification:userInfo];
  }
  
  - (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
  fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
    [RNFirebaseMessaging didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
  }
  
    - (void)userNotificationCenter:(UNUserNotificationCenter *)center
  willPresentNotification:(UNNotification *)notification
  withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {
    [RNFirebaseMessaging willPresentNotification:notification withCompletionHandler:completionHandler];
  }
  
    - (void)userNotificationCenter:(UNUserNotificationCenter *)center
  didReceiveNotificationResponse:(UNNotificationResponse *)response
  withCompletionHandler:(void (^)(void))completionHandler {
    [RNFirebaseMessaging didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
  }
```
Help would be appreciated. I followed docs from here - https://rnfirebase.io/docs/v3.2.x/messaging/ios#Update-%3Ccode%3EAppDelegate.m%3C/code%3E

### Environment

1. Application Target Platform: iOS
2. Development Operating System: macOS Sierra (10.12.6)
3. Build Tools: Xcode 9.2 (9C40b) 
4. React Native version: 0.52.2
5. RNFirebase Version: 3.2.4
6. Firebase Module: Cloud Messaging

**Comment by chrisbianca** [comment]
@steverob This is one of a number of issues that has been fixed as part of the v4 release - I would strongly recommend updating to the v4 branch if you're going to be using messaging and notifications.

This isn't something that we're going to be backporting to v3

**Comment by steverob** [comment]
@Chenjh1992  I am using `v4.0.7` and I get these new weird errors. Is Xcode not loading the headers or something?

![screen shot 2018-05-07 at 3 54 34 pm](https://user-images.githubusercontent.com/1220480/39697624-250dc83c-520f-11e8-8311-7810f4053a56.png)

**Comment by steverob** [comment]
Sorry please ignore @chrisbianca. I did not do `pod update`. Only `pod install.

Thanks!
