### ISSUE TITLE
How to test verification

### ISSUE THREAD

**Issue by Friis1978** [invertase/react-native-firebase#1055]
### Issue

Hello developers, 
I would really like to know how I should
test the phone verification. 

When the verification code i sent for the first time, the phone automatically goes into the 
state AUTO_VERIFIED, so the state should somehow be reset in the phone.

Is there any functions I could use in firebase to reset the state ?

### Environment

Android

1. Application Target Platform:

26

2. Development Operating System:

26

3. Build Tools:

26

4. React Native version:

0.53.3

5. RNFirebase Version:

4.0.6

**Comment by Salakar** [comment]
@Friis1978 unfortunately I don't think there is anything you can use to reset the state, bit of a hard thing to test even on our end due to the physical device requirements etc. 

Shot in the dark thing you could try: log out the user and also reset the the devices `iid` by calling [delete](https://rnfirebase.io/docs/v4.0.x/iid/reference/iid#delete) and see if that does anything to reset the state for you.

Otherwise I guess this is a question for Firebase Support potentially?

**Comment by Friis1978** [comment]
Hey @Salakar ,

Thanks for helping out with this, seems strange that I am the only one struggling with this issue. 
I have tried sending the question to the firebase team. 

How could I reset the devices iid, cant find any documentation for that anywhere ?

**Comment by Salakar** [comment]
There a link in my response, the `delete` link 😋

**Comment by Friis1978** [comment]
Hei @Salakar, 

Haha, did not notice the link, sorry. 

The delete function does not have any effect.
I dont understand how other developers could have tested this flow ?

Hopefully the firebase team have an answer for me soon. 

Here is my code

`import React, { Component } from 'react';
import { View, Text, AsyncStorage } from 'react-native';
import { connect } from 'react-redux';
import Svg, { G, Path } from 'react-native-svg';

import firebase from 'react-native-firebase';

import {
    phoneChanged,
    loginUserPhone,
    checkAsyncStorage,
    firebaseSignInWithPhoneNumber
} from '../../actions';

import {
    Card,
    CardSection,
    Input,
    BlueButton
} from '../common';

class LoginFormPhone extends Component {
    constructor(props) {
        super(props);
        this.unsubscribe = null;
        this.state = {
            user: null,
            message: '',
            codeInput: '',
            phoneNumber: phoneDefault,
            confirmResult: null,
        };
    }

    componentWillMount() {
        this.props.checkAsyncStorage('phone');
    }

    componentDidMount() {
        this.unsubscribe = firebase.auth().onAuthStateChanged((user) => {
            console.log('state changed');
            if (user) {
                console.log('User data found');
                this.setState({ user: user.toJSON() });
            } else {
                console.log('User was signed out');
                this.setState({
                    user: null,
                    message: '',
                    codeInput: '',
                    phoneNumber: phoneDefault,
                    confirmResult: null,
                });
            }
        });
    }

    componentWillUnmount() {
        if (this.unsubscribe) this.unsubscribe();
    }

    ShowCurrentDate = (txt, object) => {
        const dateobject = new Date(object);
        let second = dateobject.getSeconds();
        if (second < 10) {
            second = `0${second}`;
        }
        let minute = dateobject.getMinutes();
        if (minute < 10) {
            minute = `0${minute}`;
        }
        let hour = dateobject.getHours();
        if (hour < 10) {
            hour = `0${hour}`;
        }
        let date = dateobject.getDate();
        if (date < 10) {
            date = `0${date}`;
        }
        let month = dateobject.getMonth() + 1;
        if (month < 10) {
            month = `0${month}`;
        }
        const year = dateobject.getFullYear();

        return `${txt} ${hour}:${minute}:${second} ${date}/${month}-${year}`;
    }

    signIn = () => {
        const { phoneNumber } = this.state;
        //this.firebaseAuth(phoneNumber);
        this.firebaseSignIn(phoneNumber);
    };

    signOut = () => {
        firebase.auth().signOut();
    }

    checkPhoneState = () => {
        const { phoneNumber } = this.state;
        this.firebaseAuth(phoneNumber);
    }

    async deleteId() {    
        await firebase.iid().delete()
        .then(() => {
            console.log('iid deleted');
        });        
    }

    confirmCode = () => {
        const { codeInput, confirmResult } = this.state;

        if (confirmResult && codeInput.length) {
            console.log(`Code input: ${codeInput}`);
            confirmResult.confirm(codeInput)
                .then((user) => {
                    console.log('User has been found');
                    console.log(user);
                })
                .catch(error => this.setState({ message: `Code Confirm Error: ${error.message}` }));
        }
    };

    firebaseSignIn = (phoneNumber) => { 
        firebase.auth().signInWithPhoneNumber(phoneNumber).then((result) => {
            const token = result;
            console.log(token);
        }).catch(error => this.setState({ message: `Sign In With Phone Number Error: ${error.message}` }));
    }

    firebaseAuth = (phoneNumber) => {
        firebase.auth()
            .verifyPhoneNumber(phoneNumber)
            .on('state_changed', (phoneAuthSnapshot) => {
                console.log('State changes');
                console.log(phoneAuthSnapshot);
                // How you handle these state events is entirely up to your ui flow and whether
                // you need to support both ios and android. In short: not all of them need to
                // be handled - it's entirely up to you, your ui and supported platforms.

                // E.g you could handle android specific events only here, and let the rest fall back
                // to the optionalErrorCb or optionalCompleteCb functions
                switch (phoneAuthSnapshot.state) {
                    // ------------------------
                    //  IOS AND ANDROID EVENTS
                    // ------------------------
                    case firebase.auth.PhoneAuthState.CODE_SENT: // or 'sent'
                        console.log('code sent');
                        this.setState({ message: 'code sent' });
                        // on ios this is the final phone auth state event you'd receive
                        // so you'd then ask for user input of the code and build a credential from it
                        // as demonstrated in the `signInWithPhoneNumber` example above
                        break;
                    case firebase.auth.PhoneAuthState.ERROR: // or 'error'
                        console.log('verification error');
                        console.log(phoneAuthSnapshot.error);
                        this.setState({ message: phoneAuthSnapshot.error });
                        break;

                    // ---------------------
                    // ANDROID ONLY EVENTS
                    // ---------------------
                    case firebase.auth.PhoneAuthState.AUTO_VERIFY_TIMEOUT: // or 'timeout'
                        console.log('auto verify on android timed out');
                        this.setState({ message: 'auto verify on android timed out' });
                        // proceed with your manual code input flow, same as you would do in
                        // CODE_SENT if you were on IOS
                        break;
                    case firebase.auth.PhoneAuthState.AUTO_VERIFIED: // or 'verified'
                        // auto verified means the code has also been automatically confirmed as correct/received
                        // phoneAuthSnapshot.code will contain the auto verified sms code - no need to ask the user for input.
                        console.log('auto verified on android');
                        this.setState({ message: 'auto verified on android' });
                        // Example usage if handling here and not in optionalCompleteCb:
                        // const { verificationId, code } = phoneAuthSnapshot;
                        // const credential = firebase.auth.PhoneAuthProvider.credential(verificationId, code);

                        // Do something with your new credential, e.g.:
                        // firebase.auth().signInWithCredential(credential);
                        // firebase.auth().currentUser.linkWithCredential(credential);
                        // etc ...
                        break;
                    default:
                        console.log('No data');
                        this.setState({ message: 'No data' });
                }
            }, (error) => {
                // optionalErrorCb would be same logic as the ERROR case above,  if you've already handed
                // the ERROR case in the above observer then there's no need to handle it here
                console.log(error);
                // verificationId is attached to error if required
                console.log(error.verificationId);
            }, (phoneAuthSnapshot) => {
                // optionalCompleteCb would be same logic as the AUTO_VERIFIED/CODE_SENT switch cases above
                // depending on the platform. If you've already handled those cases in the observer then
                // there's absolutely no need to handle it here.

                // Platform specific logic:
                // - if this is on IOS then phoneAuthSnapshot.code will always be null
                // - if ANDROID auto verified the sms code then phoneAuthSnapshot.code will contain the verified sms code
                //   and there'd be no need to ask for user input of the code - proceed to credential creating logic
                // - if ANDROID auto verify timed out then phoneAuthSnapshot.code would be null, just like ios, you'd
                //   continue with user input logic.
                console.log(phoneAuthSnapshot);
            });
        // optionally also supports .then & .catch instead of optionalErrorCb &
        // optionalCompleteCb (with the same resulting args)
    }

    renderPhoneNumberInput() {
        return (
            <Input
                maxLength={8}
                label="Telefonnr."
                placeholder="telefonnummer her..."
                onChangeText={value => this.setState({ phoneNumber: value })}
                value={`${this.props.phonenumber}`}
            />
        );
    }

    renderLoginButton() {
        return (
            <BlueButton onPress={this.signIn}>
                Start
            </BlueButton>
        );
    }

    renderMessage() {
        const { message } = this.state;

        if (!message.length) return null;

        return (
            <Text style={{ padding: 5, backgroundColor: 'white', color: 'black' }}>{message}</Text>
        );
    }

    renderVerificationCodeInput() {
        const { codeInput } = this.state;

        return (
            <Input
                maxLength={12}
                label="Verification kode"
                placeholder="Verification kode her..."
                onChangeText={value => this.setState({ codeInput: value })}
                value={codeInput}
            />
        );
    }

    renderVerificationCodeButton() {
        return (
            <BlueButton onPress={this.confirmCode}>
                Konfirmer Kode
            </BlueButton>
        );
    }

    renderLoggedInUser() {
        console.log('renderLoggedInUser');
        const { user } = this.state;

        const userPhone = `Bruger telefonnummer: ${user.phoneNumber}`;
        const userUid = `Id: ${user.uid}`;

        console.log(user);
        const lastLogin = this.ShowCurrentDate('Sidst logget på:', user.metadata.lastSignInTime);
        const firstLogin = this.ShowCurrentDate('Første gang logget på:', user.metadata.creationTime);
        console.log(lastLogin);
        console.log(firstLogin);

        return (
            <View>
                <Text style={{ fontSize: 25, marginBottom: 20, alignSelf: 'center' }}>Du er logget ind!</Text>
                <Text style={{ fontSize: 14, alignSelf: 'center' }}>{userPhone}</Text>
                <Text style={{ fontSize: 14, alignSelf: 'center' }}>{userUid}</Text>
                <Text style={{ fontSize: 14, alignSelf: 'center' }}>{firstLogin}</Text>
                <Text style={{ fontSize: 14, marginBottom: 20, alignSelf: 'center' }}>{lastLogin}</Text>
            </View>
        );
    }

    renderLogOutButton() {
        return (
            <BlueButton onPress={this.signOut}>
                Log ud
            </BlueButton>
        );
    }

    renderDeleteUserButton() {
        return (
            <BlueButton onPress={this.deleteId}>
                Delete User Id
            </BlueButton>
        );
    }

    renderSvg() {
        return (
            <CardSection style={{ justifyContent: 'center', alignItems: 'center' }}>
                <Svg
                    style={styles.imageStyle}
                    height="150"
                    width="250"
                    viewBox="0 0 408 212.16"
                >
                    <G id="Lag_2" data-name="Lag 2">
                        <G id="Lag_1-2" data-name="Lag 1">
                            <Path fill="#00b8ff" d="M204,153" />
                            <Path
                                fill="#00b8ff"
                                d="M350.88,97.92a57.55,57.55,0,0,0-8.46.63A106.06,106.06,0,0,0,146.29,50.49,81.61,81.61,0,0,0,55.75,98a57.11,57.11,0,0,0,1.37,114.21l.91,0v0H350v0l.91,0a57.12,57.12,0,1,0,0-114.24Z"
                            />
                            <Path
                                fill="#fff"
                                d="M230.6,135.94,204,152.21l-26.6-16.27c-7.45-4.56-11.89-12-11.89-20V69.53c5.35,4.69,38.42-6.53,38.42-9.69,0,3.17,33.14,14.45,38.56,9.69v46.42C242.49,123.91,238,131.38,230.6,135.94Z"
                            />
                            <Path
                                fill="#00b8ff"
                                d="M294.23,186.29a25.27,25.27,0,0,0-29-25A46.91,46.91,0,0,0,178.48,140a36.1,36.1,0,0,0-40,21,25.26,25.26,0,0,0-24.66,25.25"
                            />
                            <Path
                                fill="#fff"
                                d="M294.23,186.29A25.41,25.41,0,0,0,285,167.67a24.65,24.65,0,0,0-14.44-5.5,32.93,32.93,0,0,0-5.17.29l-1.21.08-.12-1.16a46.18,46.18,0,0,0-11-25.94,46.78,46.78,0,0,0-10.8-9.19,46.14,46.14,0,0,0-27.16-6.53A47.73,47.73,0,0,0,201.33,123a46.76,46.76,0,0,0-12.08,7.33A48.73,48.73,0,0,0,180,141l-.66,1-1.15-.24a34.73,34.73,0,0,0-22.68,3.08,35.49,35.49,0,0,0-16,16.64l-.31.65h-.66a24.79,24.79,0,0,0-17.06,6.94,25.43,25.43,0,0,0-7.62,17.22,25.06,25.06,0,0,1,1.55-9.66A25.8,25.8,0,0,1,138.4,160l-1,.65A37.79,37.79,0,0,1,144.15,150a36.82,36.82,0,0,1,9.93-7.8,36.41,36.41,0,0,1,12-4.06,38,38,0,0,1,12.72.21l-1.81.79a49.34,49.34,0,0,1,9.88-11.64,50.46,50.46,0,0,1,13-8,48.14,48.14,0,0,1,66.49,41.73l-1.33-1.07a34.89,34.89,0,0,1,5.66-.1,25.81,25.81,0,0,1,5.53,1.06,25.27,25.27,0,0,1,9.63,5.55,26.1,26.1,0,0,1,6.37,9A24.77,24.77,0,0,1,294.23,186.29Z"
                            />
                            <Path fill="#00b8ff" d="M243.06,165.8" />
                        </G>
                    </G>
                </Svg>
            </CardSection>
        );
    }

    render() {
        const { user, confirmResult } = this.state;
        return (
            <Card>
                {this.renderSvg()}
                <CardSection>
                    {/* 
                        If it is the first time the user logs in  
                    */}
                    {!user && !confirmResult && this.renderPhoneNumberInput()}
                </CardSection>
                <CardSection>
                    {/* 
                        If it is the first time the user logs in  
                    */}
                    {!user && !confirmResult && this.renderLoginButton()}
                </CardSection>
                <CardSection>
                    {this.renderMessage()}
                </CardSection>
                <CardSection>
                    {/* 
                        If Phonenumber verificationcode has been sent, but has not been confirmed.
                        This user will be sent to the register user screen.    
                    */}
                    {!user && confirmResult && this.renderVerificationCodeInput()}
                </CardSection>
                <CardSection>
                    {/* 
                        If Phonenumber verificationcode has been sent, but has not been confirmed.
                        This user will be sent to the register user screen.    
                    */}
                    {!user && confirmResult && this.renderVerificationCodeButton()}
                </CardSection>
                {/* 
                        If Phonenumber verificationcode has been sent, and has been confirmed.
                        We can get the current user info, and log the user in.           
                    */}
                {user && this.renderLoggedInUser()}
                <CardSection>
                    {user && this.renderDeleteUserButton()}
                </CardSection>
                <CardSection>
                    {user && this.renderLogOutButton()}
                </CardSection>
            </Card>
        );
    }
}

const phoneDefault = '+4531152585';

const styles = {
    errorTextStyle: {
        fontSize: 20,
        alignSelf: 'center',
        color: 'red'
    },
    imageStyle: {
        flex: 1,
        marginTop: 10,
        marginBottom: 10,
        marginLeft: 10,
        marginRight: 10
    }
};

const mapStateToProps = ({ auth }) => {
    const {
        phonenumber,
        latitude,
        longitude,
        error,
        loading
    } = auth;

    console.log(auth);

    return {
        phonenumber,
        latitude,
        longitude,
        error,
        loading
    };
};

export default connect(mapStateToProps, {
    phoneChanged,
    loginUserPhone,
    checkAsyncStorage,
    firebaseSignInWithPhoneNumber
})(LoginFormPhone);`

**Comment by chrisbianca** [comment]
Use a phone number for a different phone, not the one you’re testing the app on

**Comment by Friis1978** [comment]
@chrisbianca so what you are saying is, that I should have sent the sms to a different phone number, so my app is not detecting this phone as 'already verified' ?.

**Comment by chrisbianca** [comment]
Yep, exactly

**Comment by Salakar** [comment]
All,

You can now test with fake/whitelisted phone numbers and custom codes by adding custom numbers and their corresponding authorisation codes on your Firebase Console. 

See the following: https://firebase.google.com/docs/auth/web/phone-auth#test-with-whitelisted-phone-numbers

This also means you can test directly from an iOS simulator or Android emulator without Google Play Services installed. 🎉 

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
