### ISSUE TITLE
After running "yarn add react-native-firebase", cannot link and project does not build

### ISSUE THREAD

**Issue by alexfoxy** [invertase/react-native-firebase#1059]
### Issue
I have followed the installation instructions and when I run "react-native link" it appears to link the files:

> rnpm-install info Linking react-native-firebase ios dependency
> rnpm-install info Platform 'ios' module react-native-firebase has been successfully linked

...but hangs at the end of the process. I then cannot build my project with the error:

`Cannot find Firebase.h`

from within the ReactNativeFirebase Library which would suggest it didn't manage to link them.

### Environment

1. Application Target Platform:
iOS 10.3+

2. Development Operating System:
XCode 9.3

3. Build Tools:

4. React Native version:
0.55.3

5. RNFirebase Version:
4.0.7

6. Firebase Module:
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics', '~> 3.10.1'

**Comment by Ehesp** [comment]
Could you post your `Podfile` please?

**Comment by alexfoxy** [comment]
sure:

```
project 'ios/freqapp.xcodeproj/'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'freqapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for freqapp
  pod 'Mixpanel'
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics', '~> 3.10.1'

  # Add new pods below this line

  target 'freqappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by Ehesp** [comment]
Okay so the link command has added the pod to the file successfully.. If you jump into your `ios` directory, run `pod install` as it seems like it didn't install Firebase, hence the error appearing in `AppDelegate.m` I assume!

**Comment by alexfoxy** [comment]
That's not it - FirebaseSDK is installed and working. The 'Firebase.h' file not found error is in RNFirebaseUtil.h: 

<img width="598" alt="screen shot 2018-05-09 at 08 07 53" src="https://user-images.githubusercontent.com/151772/39800585-351efc4e-5360-11e8-8aff-6194392f6278.png">

**Comment by chrisbianca** [comment]
Can I see your podfile.lock?

**Comment by alexfoxy** [comment]
I have resolved by changing the Header Search paths in the RNFirebase build settings. 

Changed from:
> ${SRCROOT}/../../../ios/Firebase
> ${SRCROOT}/../../../ios/Headers/Public

to:
> ${SRCROOT}/../../../Pods/Firebase
> ${SRCROOT}/../../../Pods/Headers/Public

I'm not sure if this is a problem our end?

**Comment by chrisbianca** [comment]
Very strange, the RNFirebase default header paths are set to:

```
"$(inherited)",
"$(SRCROOT)/../../react-native/React/**",
"${SRCROOT}/../../../ios/Firebase/**",
"${SRCROOT}/../../../ios/Pods/Headers/Public/**",
```

Which your version doesn't seem to be reflecting for some reason.

**Comment by alexfoxy** [comment]
My Folder structure is like:

```
myappname
    node_modules
    ios
    Pods
        Firebase
        Headers
        ....
    ...
```

So if react-native-firebase is in node_modules doesn't my search paths make sense?

**Comment by alexfoxy** [comment]
Is your project structure different?

**Comment by chrisbianca** [comment]
Ah! You have initialised your pods project at the root level - it should be within the `ios` folder :)
This is why your header paths need to be different.

You'll want to recreate the Podfile within `ios` and then run `pod install` from there
