### ISSUE TITLE
[proposal] firebase.ml() Machine Learning

### ISSUE THREAD

**Issue by chrisbianca** [invertase/react-native-firebase#1060]
This issue is to discuss the newly announced Machine Learning (ML) API, possible API implementation spec for RNFirebase and to track interest.

Announcement: https://developers.googleblog.com/2018/05/introducing-ml-kit.html

Video: https://youtu.be/ejrn_JHksws

Overview: https://firebase.google.com/products/ml-kit/

SDK Guide: https://firebase.google.com/docs/ml-kit/

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by JonathanLehner** [comment]
seems it is available from Google now

**Comment by kevinjpetersen** [comment]
I wonder if Firebase ML Kit will support native JavaScript in the future, either way, I'm definitely in favor having ML Kit implemented into React Native Firebase for Android and iOS as it makes Machine Learning possible for everyone, fast and easy.

+1

**Comment by Salakar** [comment]
@kevinjpetersen ML Kit in the JS SDK should be doable for them in the future with the likes of [Tensorflow JS](https://js.tensorflow.org/), though it is a hefty dependency to include as part of a website bundle though as well; 0.5mb uncompressed.

**Comment by Seroleashed** [comment]
Any plans yet when this kit will be implemented? (e.g."on xx.xx.20xx", "in the next x months", "some time soon", "not before x")

**Comment by JonathanLehner** [comment]
you go ahead and make a PR?

I don't know any of this. It seems you just have to add this native module
from google and integrate it into the Github project and then make a PR..

**Comment by Salakar** [comment]
@JonathanLehner it's not as simple as you make it sound 😛 for example the recent `functions()` support added which is only 1 method to support required [quite a few changes to implement support](https://github.com/invertase/react-native-firebase/pull/1056/files).

This one has a lot of methods and also requires thought around how the API will look in JS land. We'll get there, can't give you an exact date when unfortunately @Seroleashed

**Comment by sarathxm** [comment]
It will be cool with react native.

**Comment by radi-cho** [comment]
Hello guys! I've posted some questions in the Firebase Discussion Group related to ML Kit in React Native and the web. Take a look [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/firebase-talk/xiKTdB62ubo/WSB6wajBBgAJ).

Conversation:

> me:  Is there any way to use the current beta version of the Firebase ML Kit with React Native...The `firebase` npm module is pretty limited and the `react-native-firebase` community may wait Firebase to roll out ML Kit for the web to implement it more easily. Will Firebase roll out web version of the ML Kit, like Tensorflow rolled out Tensorflow.js? Are there another solutions for using the ML kit in React Native?

> Sachin (Product Manager on ML Kit): Thanks for the feedback, Radi. No immediate plans on this. We'd love to see the community take this up for now, as we love RN as well :)

**Comment by JonathanLehner** [comment]
It is better to work with the native files of ML kit since they are
optimised. Tensorflow.js has lower performance than the original Tensorflow
in C++. People use Tensorflow.js because you can easily load it into a
browser, if you have an app, however, this is not a big factor, since all
users have to download it and install it.

**Comment by Salakar** [comment]
Hi all, we'll look at adding support for this as part of the v5.x.x release cycle. 

The first release for it will most likely just have built-in model support only. We can look at custom model support at a later date.

**Comment by salmankhann** [comment]
Hi @Salakar any updates on this?

**Comment by Salakar** [comment]
Let's track this over at https://boards.invertase.io/react-native-firebase/p/ml-kit-for-firebase
