### ISSUE TITLE
Support Firebase SDK v5.0.0+

### ISSUE THREAD

**Issue by brunolemos** [invertase/react-native-firebase#1061]
### Issue

After upgrading the Firebase pods to v5+, ios build fails:

`error: incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
`

On code:

```obj-c
    [[FIRAuth authWithApp:firApp] signInAnonymouslyWithCompletion:^(FIRUser *user, NSError *error) {
        if (error) {
            [self promiseRejectAuthException:reject error:error];
        } else {
            [self promiseWithUser:resolve rejecter:reject user:user];
        }
    }];
```

![image](https://user-images.githubusercontent.com/619186/39789490-7c339d60-5306-11e8-9cca-1e6676e359a5.png)

From their [changelog](https://firebase.google.com/support/release-notes/ios):

![image](https://user-images.githubusercontent.com/619186/39789495-8688810e-5306-11e8-8ec0-dc0dacdbccda.png)

### Environment

1. Application Target Platform: iOS

2. Development Operating System: Xcode 9.3

3. Build Tools:

4. React Native version: ^0.55.5

5. RNFirebase Version: ^4.1.0

6. Firebase Module: Auth

**Comment by shafy** [comment]
+1

**Comment by fungilation** [comment]
Not quite the same, but I get a whole bunch of errors like this:
<img width="1512" alt="screenshot 2018-05-08 20 52 03" src="https://user-images.githubusercontent.com/3803466/39794928-b8fc0598-5301-11e8-9ba8-44ceea335ec2.png">

Is there a way to lock pod versions, or I simply have to not run pod update?

**Comment by schtulmann** [comment]
+1 

Same problem here, errors when adding Firebase/Auth or Firebase/Firestore.

**Comment by chrisbianca** [comment]
There are a number of breaking changed in v5 of the iOS pods: (https://firebase.google.com/support/release-notes/ios)

We're going to have to spend a bit of time looking into these and seeing how they affect RNFirebase and also how compatible they are with the equivalent Android functionality.

As alway's we'll do our best to get support added as soon as we can.

In the meantime you should be able to fix the version of firebase by adding the following to your Podfile:

```
pod 'Firebase/Core', '~> 4.13.0'
```

**Comment by jgfidelis** [comment]
For your problem, I think you can change your code to:
```
[[FIRAuth authWithApp:firApp] signInAnonymouslyWithCompletion:^(FIRAuthDataResult *dataResult, NSError *error) {
        if (error) {
            [self promiseRejectAuthException:reject error:error];
        } else {
            [self promiseWithUser:resolve rejecter:reject user:dataResult.user];
        }
    }];
```

**Comment by fungilation** [comment]
FYI, all the major version updates for Firebase dependencies, not just Core. Output from `pod update`:

```
Analyzing dependencies
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `SentryReactNative` from `../node_modules/react-native-sentry`
Fetching podspec for `react-native-orientation` from `../node_modules/react-native-orientation`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
Downloading dependencies
Using BoringSSL (10.0.2)
Installing Firebase 5.0.0 (was 4.13.0)
Installing FirebaseABTesting 2.0.0 (was 1.0.0)
Installing FirebaseAnalytics 5.0.0 (was 4.2.0)
Installing FirebaseAuth 5.0.0 (was 4.6.1)
Installing FirebaseCore 5.0.0 (was 4.0.20)
Installing FirebaseDatabase 5.0.0 (was 4.1.5)
Installing FirebaseFirestore 0.12.0 (was 0.11.0)
Installing FirebaseInstanceID 3.0.0 (was 2.0.10)
Installing FirebaseMessaging 3.0.0 (was 2.2.0)
Installing FirebasePerformance 2.0.0 (was 1.1.3)
Installing FirebaseRemoteConfig 3.0.0 (was 2.1.3)
Installing FirebaseStorage 3.0.0 (was 2.2.0)
Installing FirebaseSwizzlingUtilities 2.0.0 (was 1.0.1)
Using GTMSessionFetcher (1.1.15)
Installing GoogleToolboxForMac 2.1.4 (was 2.1.4)
```

**Comment by shafy** [comment]
@fungilation yes but if you do `pod 'Firebase/Core', '~> 4.13.0'` in your `Podfile`, all other dependencies will also remain <5

**Comment by thallamsai** [comment]
please share the mapping of the firebase pod and RNFirebase version that are compatible. A lot of people are struggling with this issue. I am using Cocoapods. Either FirebaseCore/FirebaseCore.h error or the FirebaseAnalytics error or FirebaseAuth error is coming up. It would be helpful if anyone who have solved the issue can drop in their podfile versions and compatible RNFirebase version.
Thanks in advance

**Comment by shafy** [comment]
@thallamsai see my comment right above. You might need to delete your Pods folder and again do `pod install` (maybe even a `pod cache clean --all`). My firebase version in my `package.json` is `"react-native-firebase": "^4.1.0",`.

Hope that helps.

**Comment by jaschaio** [comment]
Does somebody know where I can get the `4.13.0` Files from to Integrate manually without CocoaPods? [The download link within the official guide](https://firebase.google.com/docs/ios/setup#frameworks) automatically downloads the latest version. Related: firebase/firebase-ios-sdk#1270

**Comment by cmmartin** [comment]
@jaschaio I am looking for the same thing. Managed to get 5.0.0 manually linked without cocoapods only to find out this library only supports 4.13.0

**Comment by chrisbianca** [comment]
Just pushed up support for v5: https://github.com/invertase/react-native-firebase/commit/42e7fb2e5d8a7599330d995030257068e681fd94

We have a few other things which we'd ideally like to get included in our next release, so this might take a couple of days to land, but it will be part of v4.2.0.

**Comment by isnotahippy** [comment]
@chrisbianca Running that commit in a project with use_frameworks! enabled and allowing Firebase to install at the latest version, seeing the "RNFirebase core module was not found" error. If I downgrade to Firebase 4.13.0 and the previous RNfirebase I see the "incompatible block pointer type" errors from the first post here. 

Running fine with use_frameworks commented out, but I need it enabled for another dependency. I've installed RNFirebase via `react-native link` and not as a pod. 

Trying to work out where it's gone wrong but I figured I'd reply in case there is something obvious here.

**Comment by stereodenis** [comment]
@chrisbianca 
![image](https://user-images.githubusercontent.com/1406461/40268151-3a6047ee-5b71-11e8-8673-e252a5423e6f.png)

```
PODS:
  - Firebase (5.0.1):
    - Firebase/Core (= 5.0.1)
  - Firebase/Auth (5.0.1):
    - Firebase/CoreOnly
    - FirebaseAuth (= 5.0.0)
  - Firebase/Core (5.0.1):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.0.0)
  - Firebase/CoreOnly (5.0.1):
    - FirebaseCore (= 5.0.1)
  - Firebase/Messaging (5.0.1):
    - Firebase/CoreOnly
    - FirebaseMessaging (= 3.0.0)
  - FirebaseAnalytics (5.0.0):
    - FirebaseCore (~> 5.0)
    - FirebaseInstanceID (~> 3.0)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - nanopb (~> 0.3)
  - FirebaseAuth (5.0.0):
    - FirebaseCore (~> 5.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseCore (5.0.1):
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
  - FirebaseInstanceID (3.0.0):
    - FirebaseCore (~> 5.0)
  - FirebaseMessaging (3.0.0):
    - FirebaseCore (~> 5.0)
    - FirebaseInstanceID (~> 3.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - Protobuf (~> 3.1)
  - GoogleToolboxForMac/Defines (2.1.4)
  - GoogleToolboxForMac/Logger (2.1.4):
    - GoogleToolboxForMac/Defines (= 2.1.4)
  - "GoogleToolboxForMac/NSData+zlib (2.1.4)":
    - GoogleToolboxForMac/Defines (= 2.1.4)
  - GTMSessionFetcher/Core (1.1.15)
  - nanopb (0.3.8):
    - nanopb/decode (= 0.3.8)
    - nanopb/encode (= 0.3.8)
  - nanopb/decode (0.3.8)
  - nanopb/encode (0.3.8)
  - Protobuf (3.5.0)
```
"react-native": "0.54.0"
"react-native-firebase": "^4.2.0"

What's wrong?

**Comment by NirpE** [comment]
Anyone got v4.2.0 with Firebase 5.x working yet? I am unable to archive project.

**Comment by simonbengtsson** [comment]
Yes, we are rocking 4.2 and 5.0 before and 5.1 since yesterday.

**Comment by NirpE** [comment]
I just upgraded and ran fresh npm install + pod install. Still getting following error when trying to build in XCode:

`'FirebaseCore/FIRAnalyticsConfiguration.h' file not found`

**Comment by simonbengtsson** [comment]
Checked now and we do have that file in our repo.

**Comment by NirpE** [comment]
If I choose "Generic iOS Device" as target to build to or try to archive, I am getting that above error. Running on emulator seems to work.

**Comment by simonbengtsson** [comment]
I'll publish a new release today, I'll let you know if we run into the same issue.

**Comment by NirpE** [comment]
@simonbengtsson care to share your XCode Build Settings -> header Search Paths?

**Comment by simonbengtsson** [comment]
Here are our search paths: 

![screen shot 2018-06-01 at 09 36 23](https://user-images.githubusercontent.com/3586691/40827915-671cbd90-657f-11e8-9d7a-ea84ce205477.png)

Should also add that we are using cocoa pods and swift for our iOS project with these fixes applied to react native on pod install and npm install.

https://gist.github.com/simonbengtsson/45c9bbb2f7fabbca1707ebcfe78e08d7

**Comment by NirpE** [comment]
I have RNFirebase.xcodeproj located under Libraries, should I be having source code folder there instead? Any idea what is the root component of this issue?

**Comment by simonbengtsson** [comment]
Including the source works better for us. Have not explored why actually.

**Comment by NirpE** [comment]
@chrisbianca do you have any hints on how to get this working using Pods without manually adding RNFirebase sources to project?

**Comment by salmanbukhari1** [comment]
@cmmartin can you please list the steps taken to install manually. I am running into errors after installing manually. Thanks

**Comment by agrawalsurabhi89** [comment]
I'm also looking for manual steps for integration. Could you please share @cmmartin
