### ISSUE TITLE
'FirebaseAnalytics/FIRAnalyticsConfiguration.h' file not found

### ISSUE THREAD

**Issue by DLevai94** [invertase/react-native-firebase#1062]
### Issue

On my project after updating to 4.1.0 and RN 0.55.4 I can't build iOS.

`'FirebaseAnalytics/FIRAnalyticsConfiguration.h' file not found`

### Environment

MacOS High Sierra, iOS 11.3, XCode

**Comment by yangga** [comment]
Same here...What happen...

**Comment by chrisbianca** [comment]
My guess, is this is related to the new versions of Cocoapods that have been released.
See here: https://github.com/invertase/react-native-firebase/issues/1061

**Comment by dluksza** [comment]
I've had same issue after updating native pod dependency to 5.0.0. Downgrading changing Podfile entry to:
```
pod 'Firebase/Analytics', '4.2.0'
```
did solved this issue. It seams that `react-native-firebase` is not yet compatible with newest firebase release.

**Comment by Salakar** [comment]
@dluksza you're right, we're not yet compatible with the latest SDK, it only came out yesterday and there's been quite a few breaking changes in it that we're going to have to deal with unfortunately

**Comment by DLevai94** [comment]
@chrisbianca Yes! Confirmed, thanks! :)

**Comment by chrisbianca** [comment]
Thanks for confirming. For those that stumble across this issue, please see: https://github.com/invertase/react-native-firebase/issues/1061 for a suggested fix

**Comment by stereodenis** [comment]
@chrisbianca please help me https://github.com/invertase/react-native-firebase/issues/1106

**Comment by nunobasto** [comment]
Hi, I also have this problem but I'm not using pods so how can I get the firebase sdk version 5.18.2? The one that can be downloaded is the 6.1.0.

**Comment by mikehardy** [comment]
5.20.2 is the current version and if you search firebase-ios-sdk release you'll find it -> https://duckduckgo.com/?q=firebase-ios-sdk+releases&ia=web - they're on github

**Comment by nunobasto** [comment]
Thank you!! 
I've forgotten about the releases "tab" in github. I went to the branch but I missed that.

(As my app is still on RN 0.54 according to RNFirebase I guess I have to use the sdk 5.18 or previous)
