### ISSUE TITLE
firebase phone auth check if user already exist in firebase Authentication before send sms

### ISSUE THREAD

**Issue by adirzoari** [invertase/react-native-firebase#1064]
Hey,
I'm using this library and I'm try to make firebase phone auth.
I have situation when user enter phone number, then I user verify phone number then sent code and add this user to Authentication users in firebase console and he has unique uid. BUT when I removed the app and install again, then I press again the same phone number and I get again sms althought that this user already exist in Authentication table in firebase console. why is that? I understand that his uid has changed, but he already exist in firebase system.

I add the table with my phone number (let's called this table **AUTHTable**
![Authentication table - the red line is my number](https://user-images.githubusercontent.com/20258998/39839999-a4b956d6-53e6-11e8-9f2a-01e24ab8b77b.JPG)

I think about this way(but don't know how to implement it):

1. first time when new user sign with phone number, after successful confirmation to insert new data under /UsersApp node in firebase with phoneNumber and uid property
2. if user remove app and install again before make verifyPhoneNumber to  check under /UsersApp node in firebase if phoneNumber exist
 2.1. if exist so I want to make sign up(what way to sign up without get sms code, just write user in AUTHtable with the exist phone number) but without  send confirmation code/sms just replace his uid in **AUTHTable** to the new uid.
2.2 if user not exist to insert his uid and phone number in **AUTHTable** and insert new child under /UsersApp

```
class FirebaseService {
    user = ''
    uid = ''
    userStatusDatabaseRef = ''
    userStatusFirestoreRef = ''

    constructor() {
        firebase.auth().onAuthStateChanged((user) => {
            if (user) {
                const { uid, phoneNumber} = firebase.auth().currentUser._user
                UserStore.user.setUID(uid)
                UserStore.user.setPhoneNumber(phoneNumber)
                let ref = firebase.database().ref(`/Users/${UserStore.user.uid}`)
                ref.on('value', this.gotUserData)
            }
            this.setListenConnection()

        })
    }
    
    confirmPhone = async (phoneNumber) => {
        const phoneWithAreaCode = phoneNumber.replace(/^0+/,'+972'); 

        return new Promise((res, rej) => {
            firebase.auth().verifyPhoneNumber(phoneWithAreaCode)
                .on('state_changed', async (phoneAuthSnapshot) => {
                    switch (phoneAuthSnapshot.state) {
                    case firebase.auth.PhoneAuthState.AUTO_VERIFIED:
                        await this.confirmCode(phoneAuthSnapshot.verificationId, phoneAuthSnapshot.code, phoneAuthSnapshot)
                        res(phoneAuthSnapshot)

                        break

                    case firebase.auth.PhoneAuthState.CODE_SENT:
                        UserStore.setVerificationId(phoneAuthSnapshot.verificationId)
                        res(phoneAuthSnapshot)
                        break

                    case firebase.auth.PhoneAuthState.AUTO_VERIFY_TIMEOUT: 
                        UserStore.setVerificationId(phoneAuthSnapshot.verificationId)
                        UserStore.setErrorCodeAuthentication('SMS code has expired')
                        res(phoneAuthSnapshot)


                    case firebase.auth.PhoneAuthState.ERROR:
                        rej(phoneAuthSnapshot)
                        break

                    }
                })
        })
    }

    confirmCode = async (verificationId, code, phoneAuthSnapshot) => {
           try{
            const credential = await firebase.auth.PhoneAuthProvider.credential(UserStore.verificationId, code)
            UserStore.setCodeInput(code)
            UserStore.setUserCredentials(credential)
            AppStore.setAlreadyRegister(true)
            await this.authenticate(credential)
            return credential
           } catch(e){
               throw new Error(e)
        }
           
      
    }


    signOut() {
        firebase.auth().signOut()
    }

    gotUserData = (data) => {
        let user = data.val() // check user in /Users  in firebase
        const { uid, phoneNumber, displayName, image } = UserStore.user
        console.log(user)
        if (user) {
            UserStore.setUser(user)
        }else{
            console.log('user not exist in /users');
        }
        }


    }

```

**Comment by chrisbianca** [comment]
@adirzoari This is not how Firebase Auth works.  Every time you call signInWithPhoneNumber or verifyPhoneNumber, a new SMS will be sent by Firebase.  There's no way of getting around this situation.

**Comment by deveid** [comment]
What if I want to check if a  phone number exist in the authentication table. if the phone number exist I want it to move to the next activity. My problem now is checking if a user's phonen number is in the auth table

**Comment by paddy57** [comment]
firebase phone authentication works like that only each time you need to send otp sent by firebase to verify user, you can write extra code to check the specific phone number os already logged in or not by storing the a boolean in internal storage after the successful authentication by firebase and can check if user comes on that activity if that boolean is true send him to next activity

**Comment by anjananeema1102** [comment]
> What if I want to check if a phone number exist in the authentication table. if the phone number exist I want it to move to the next activity. My problem now is checking if a user's phonen number is in the auth table

@deveid DId you find any solution?

**Comment by Awais-mohammad** [comment]
This is not how firebase phone auth work however this can be achieved when signing in with email and password.When you are signing in with phone number it means you are signining in so technically the user is signed in you cannot create user with phone number you can just sign it in and every time user sign-in a new otp will be sent

**Comment by waseemsourcecode** [comment]
You can create a user directory in the firebase database with userphone number and next time if user logout or reinstall the app in the login button you will check first if phone number of textfield is already present in the firebase database or not if YES then loginin else show phone authentication OTP screen.

**Comment by jatinder3273** [comment]
When the user sign-in it returns the user detail object, and there is value in it `isNewUser: true`

**Comment by chauhan130** [comment]
I think only way to do this is through the firebase admin SDK (details shown [here](https://firebase.google.com/docs/auth/admin/manage-users#retrieve_user_data)).  The admin SDK has function `getUserByPhoneNumber(phoneNumber)`. 

So you have to create a simple firebase cloud function that can confirm if the number exists or not and call that cloud function from the client.
