### ISSUE TITLE
Notification doesn't disappear after clicking on it.

### ISSUE THREAD

**Issue by AbhiOnlyOne** [invertase/react-native-firebase#1066]
Using the below code I'm creating notifications.

```
this.notificationListener = firebase.notifications().onNotification(notification => {
        console.log("OnNotification", notification)
        notification.setTitle("MyApp")
        notification.android.setPriority(firebase.notifications.Android.Priority.High)
        notification.android.setChannelId("test-channel")
        firebase.notifications().displayNotification(notification);
})
```

> But the notification doesn't disappear even after clicking on it. The only way to clear notification is to swipe it.

**Comment by AbhiOnlyOne** [comment]
Found the solution. Added this line:

`notification.android.setAutoCancel(true);`

**Comment by gsteja2307** [comment]
thanks it worked

**Comment by musadiq-jinbade** [comment]
> `notification.android.setAutoCancel(true);`

can you I know where should I use this line.

**Comment by Ehesp** [comment]
@musadiq-jinbade when building the notification to display.

**Comment by musadiq-jinbade** [comment]
> @musadiq-jinbade when building the notification to display.


this is my code if app is in foreground after clicking on notification, doesn't clear in notification center?
 
/*

    * Triggered when a particular notification has been received in foreground

    * */


    this.notificationListener = firebase.notifications().onNotification((notification) => {

      const { title, body } = notification;


      console.log('onNotification:');






      const localNotification = new firebase.notifications.Notification({

        sound: 'sampleaudio',

        show_in_foreground: true,

      })

        

        .setSound('sampleaudio.wav')

        .setNotificationId(notification.notificationId)

        .setTitle(notification.title)

        .setBody(notification.body)

        .android.setChannelId('fcm_FirebaseNotifiction_default_channel') // e.g. the id you chose above

        .android.setLargeIcon('ic_launcher')


        .android.setPriority(firebase.notifications.Android.Priority.High);



      firebase.notifications()

        .displayNotification(localNotification)



        .catch(err => console.error(err));


    });

**Comment by hrishiakhade** [comment]
> > @musadiq-jinbade when building the notification to display.
> 
> this is my code if app is in foreground after clicking on notification, doesn't clear in notification center?
> 
> /*
> 
> ```
> * Triggered when a particular notification has been received in foreground
> 
> * */
> 
> 
> this.notificationListener = firebase.notifications().onNotification((notification) => {
> 
>   const { title, body } = notification;
> 
> 
>   console.log('onNotification:');
> 
> 
> 
> 
> 
> 
>   const localNotification = new firebase.notifications.Notification({
> 
>     sound: 'sampleaudio',
> 
>     show_in_foreground: true,
> 
>   })
> 
>     
> 
>     .setSound('sampleaudio.wav')
> 
>     .setNotificationId(notification.notificationId)
> 
>     .setTitle(notification.title)
> 
>     .setBody(notification.body)
> 
>     .android.setChannelId('fcm_FirebaseNotifiction_default_channel') // e.g. the id you chose above
> 
>     .android.setLargeIcon('ic_launcher')
> 
> 
>     .android.setPriority(firebase.notifications.Android.Priority.High);
> 
> 
> 
>   firebase.notifications()
> 
>     .displayNotification(localNotification)
> 
> 
> 
>     .catch(err => console.error(err));
> 
> 
> });
> ```

Add `.android.setAutoCancel(true)`  below `.android.setLargeIcon('ic_launcher')` or anywhere below const localNotification

**Comment by musadiq-jinbade** [comment]
Thanks! @hrishiakhade for the update. let me check I will update on same
