### ISSUE TITLE
Can not find module firebase.firestore()

### ISSUE THREAD

**Issue by sinevitch** [invertase/react-native-firebase#1067]
### Issue

Can not find module firebase.firestore()  although it finds a module firebase.database();
firebase.database () works fine
![image](https://user-images.githubusercontent.com/35930695/39874957-f27ec842-5477-11e8-95a6-a5107f139ac6.png)

error
![image](https://user-images.githubusercontent.com/35930695/39875023-1a16f47e-5478-11e8-8733-682df625c38c.png)

![image](https://user-images.githubusercontent.com/35930695/39875231-b9b4955e-5478-11e8-8211-ce4f79224346.png)

### Environment

 IOS

1. Application Target Platform:

 e.g. macOS Sierra 

2. Development Operating System:

 Xcode 9. 3

3. React Native version:

react-native-cli: 2.0.1
react-native: 0.55.4

5. RNFirebase Version:

"react-native-firebase": "^4.0.6" 

6. Firebase Module: firestore

**Comment by Salakar** [comment]
@sinevitch please see https://github.com/invertase/react-native-firebase/issues/1061 for now
