### ISSUE TITLE
[Auth] Losing Auth-State

### ISSUE THREAD

**Issue by DavidKuennen** [invertase/react-native-firebase#107]
Currently happening on my iOS and Android App. After some time my app is losing the auth state (onAuthStateChanged triggers with User=null).

If I reload the app (without logging in again), the auth state is correct again (still logged in). 

I recently updated react-native-firebase and I think it didn't happen before.

**Comment by Ehesp** [comment]
Hey is this on development mode? Could you also clarify how you're signing in along with a guesstimate of the time it takes. Not noticed the issue at all here.

**Comment by DavidKuennen** [comment]
Of course. 

It's happens on dev and release mode. Sign-In-Method is mail/pw. The time it takes is random. But mostly after a few minutes.

This is being called in my App.js:

```javascript
Firebase.auth().onAuthStateChanged((user) => {
    Storage.init().then(() => {
        if (user && lastState !== LoggedState.loggedIn) {
            alert('loggedIn')
            lastState = LoggedState.loggedIn;
            Firebase.messaging().subscribeToTopic(user.uid);
            Firebase.analytics().setUserId(user.uid);
            onLoggedIn(Map(user))
        } else if(lastState !== LoggedState.loggedOut) {
            lastState = LoggedState.loggedOut;
            setInterval(() => {
                alert('loggedOut')
            }, 5000);
            onLoggedOut();
        }
    })
})
```

Since I'm also using react-native-navigation and the alerts are disappearing along with the activity as soon as the auth state changes (changing from TabBased to SingleScreenApp), I used the interval to debug if there really is a logout happening.

Current version: 1.0.0-alpha11

**Comment by Ehesp** [comment]
First I'd suggest switch to the latest release, will help us to debug it easier.

Are you triggering an event which seems to be causing this? I'd be interesting to see whether it just times out with the activity left open. In terms of logging, just do a console log and check logcat/xcode to see it appearing.

**Comment by DavidKuennen** [comment]
Alright, I will update and keep you posted as soon as I have some news for you.

**Comment by DavidKuennen** [comment]
Wait, now that I see that function I posted again, didn't I make a mistake there? 

According to the firebase-docs the onAuthStateChanged-method will be called in these cases:
* Right after the listener has been registered
* When a user is signed in
* When the current user is signed out
* When the current user changes
* When there is a change in the current user's token

Especially the last one is interesting. If the function triggers with a new user token, I should still get a user. The problem with my implementation is, that I save the last logged state and include it into the condition. So even if I get a new user, the new state is still logged and and logged out is being triggered. 

I now rewrote it like this: 

````javascript
Firebase.auth().onAuthStateChanged((user) => {
    if (user) {
        if(lastState !== LoggedState.loggedIn) {
            lastState = LoggedState.loggedIn;
            Firebase.messaging().subscribeToTopic(user.uid);
            Firebase.analytics().setUserId(user.uid);
            onLoggedIn(Map(user))
        }
    } else {
        if(lastState !== LoggedState.loggedOut) {
            lastState = LoggedState.loggedOut;
            setInterval(() => {
                alert('loggedOut')
            }, 5000);
            onLoggedOut();
        }
    }
})
```

I will test whether the error still happens and comment here as soon as I have some more infos.

**Comment by Ehesp** [comment]
Okay cheers. We use this lib in a production app with auth, and haven't seen an issue like this one! :)

**Comment by chrisbianca** [comment]
Yeah, likewise, I've not seen any issues in production.
I'm pretty sure the reason for this error is in the incorrect logic that you highlighted.

**Comment by DavidKuennen** [comment]
As expected, now it's working. Closing this. :smile:
