### ISSUE TITLE
build error when ad crashlytic

### ISSUE THREAD

**Issue by xabree** [invertase/react-native-firebase#1071]
### Environment

1. Application Target Platform: android

2. Development Operating System: ios

3. Build Tools: build:gradle:2.2.3

4. React Native version:  55

5. RNFirebase Version: com.crashlytics.sdk.android:crashlytics:2.9.1

6. Firebase Module:
com.crashlytics.sdk.android:crashlytics:2.9.1

> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find io.fabric.tools:gradle:1.25.1.
     Searched in the following locations:
         https://jcenter.bintray.com/io/fabric/tools/gradle/1.25.1/gradle-1.25.1.pom
         https://jcenter.bintray.com/io/fabric/tools/gradle/1.25.1/gradle-1.25.1.jar

**Comment by chrisbianca** [comment]
Please check you have added:

```
        maven {
            url 'https://maven.fabric.io/public'
        }
```
as explained in the installation notes: https://rnfirebase.io/docs/v4.1.x/crashlytics/android

**Comment by xabree** [comment]
already added 

        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        } 
    
        maven {
            url 'https://maven.google.com'
        }

        maven { 
            url "https://jitpack.io" 
        }

        maven {
            url 'https://maven.fabric.io/public'
        }

**Comment by chrisbianca** [comment]
it needs to be in the `buildscript` section, not the `allprojects` section

**Comment by xabree** [comment]
Thank you @chrisbianca , It work.
