### ISSUE TITLE
default messaging.remoteMessage is not a constructor firebase react native firebase

### ISSUE THREAD

**Issue by vishnukalakota** [invertase/react-native-firebase#1076]
### Issue

  const message = new RNFirebase.messaging.RemoteMessage()
            .setMessageId(user.userId)
            .setTo('xxxxxxx@gcm.googleapis.com')
            .setData({
                key1: 'value1',
                key2: 'value2',
            });
        RNFirebase.messaging().sendMessage(message);

default messaging.remoteMessage is not a constructor firebase react native firebase

Android

messaging v 4.0.7

**Comment by chrisbianca** [comment]
How are you importing `RNFirebase`?
You need to make sure you are using the core `firebase` import from react-native-firebase, not an initialised instance as the RemoteMessage object is only available on the core import, i.e.

```
import firebase from 'react-native-firebase';

const message = new firebase.messaging.RemoteMessage()
.setMessageId(user.userId)
.setTo('xxxxxxx@gcm.googleapis.com')
.setData({
key1: 'value1',
key2: 'value2',
});
firebase.messaging().sendMessage(message);
```
