### ISSUE TITLE
No interstitial are shown on Android

### ISSUE THREAD

**Issue by giladno** [invertase/react-native-firebase#1077]
This works perfectly on iOS, but fails to work on Android.

After some debugging, I've traced it down to this line: https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/admob/RNFirebaseAdmobInterstitial.java#L67

```
  void loadAd(final AdRequest adRequest) {
    Activity activity = adMob.getActivity();
    if (activity != null) {
      activity.runOnUiThread(new Runnable() {
        @Override
        public void run() {
          interstitialAd.loadAd(adRequest);
        }
      });
    }
  }
```
It always returns a `null` activity, thus never shows any ads.

Ideas?

**Comment by Salakar** [comment]
@giladno are you using wix navigator by any chance?

**Comment by giladno** [comment]
@Salakar yes I am. Is there any special setup I need to take for it to work?

**Comment by Salakar** [comment]
Thanks for reporting this issue. We're aware that AdMob has fallen behind on React Native Firebase and would like to bring it up to speed again. I will close this issue for now and track it as well as other issues collectively over on the `AdMob overhaul proposal` to be addressed in a future release. See #1259
