### ISSUE TITLE
group message notification

### ISSUE THREAD

**Issue by fauzymk** [invertase/react-native-firebase#1078]
### Issue
How can i group my notification so it doesnt create a new panel everytime new notification comes in ? I've set the setGroup() function but got no effect. Below is my code

```
   this.messageListener = firebase.messaging().onMessage(message => {
          // Process your message as required
          firebase.notifications().android.createChannel(channel);

          let local = new firebase.notifications.Notification()
          .setNotificationId(message.messageId)
          .setTitle(message.data.title)
          .setBody(message.data.text)

          if (Platform.OS === 'android') {
              local
                  .android.setChannelId('test-channel')
                  .android.setAutoCancel(true)
                  .android.setGroup("message1")
                  // .android.setBadgeIconType(firebase.notifications.Android.BadgeIconType.Small)
                  .android.setCategory(firebase.notifications.Android.Category.Message)
                  .android.setPriority(firebase.notifications.Android.Priority.High);
          }

          firebase.notifications().displayNotification(local)
      });
```

### Environment

1. Application Target Platform: Android

2. Development Operating System: macOS High Sierra

3. Build Tools:

4. React Native version: 0.54.2

5. RNFirebase Version: 4.1.0

6. Firebase Module: messaging

**Comment by chrisbianca** [comment]
@fauzymk Take a read of https://developer.android.com/training/notify-user/group which explains how grouping works on Android.  All the methods it talks about are exposed by react-native-firebase.

**Comment by lutchobandeira** [comment]
Hey guys. I am having trouble to implement this. Could you help me?

I am trying to group notifications on android when the application is on background:

```
firebase.notifications().onNotificationDisplayed((notification) => {
  notification.android.setGroup(message.chatId);
});
```

I am clearly missing something. What do I do in order to set group on the notification?

**Comment by firofame** [comment]
@lutchobandeira did you find a solution?
