### ISSUE TITLE
Can't get this to work on Android

### ISSUE THREAD

**Issue by heroic** [invertase/react-native-firebase#1079]
### Issue

I have tried following all steps over and over again, but I am just unable to get this to work with Android.

I keep getting the error: `Process 'command '/Users/NidhiMittal/Library/Android/sdk/build-tools/27.0.3/aapt'' finished with non-zero exit value 1`

### Environment

Android

1. Application Target Platform:

macOS Sierra

2. Development Operating System:

Android Studio

3. Build Tools:

23.0.3

4. React Native version:

0.20.1

5. RNFirebase Version:

4.1.0

6. Firebase Module:

Tried both 11.6.0, and 15.0.0. However, 15.0.0 caused an error `For input string: “+”`, so reverted to 11.6.0

**Comment by RyanWarner** [comment]
@heroic How were you able to fix this issue?
