### ISSUE TITLE
Filters using floats not returning results

### ISSUE THREAD

**Issue by AndrewHenderson** [invertase/react-native-firebase#108]
RNF v1.0.2

If you have a location record with the value `latitude: 34.1013717`. It is not returned using this query:

```js
firebase.database()
      .ref('locations')
      .orderByChild('latitude')
      .startAt(34.00867000999119)
      .endAt(34.17462960866099);
```
However, it is returned when using whole numbers:

```js
firebase.database()
      .ref('locations')
      .orderByChild('latitude')
      .startAt(34)
      .endAt(35);
```

**Comment by Ehesp** [comment]
Hey is this android/iOS/both? Shouldn't be a hard one to fix, although a
test needs adding too.

**Comment by AndrewHenderson** [comment]
@Ehesp I'm only testing on iOS simulator at the moment.

**Comment by Ehesp** [comment]
Okay thanks I assume this is an issue on Android too then. We'll take a look tomorrow/Friday, should have it sorted pretty quickly tbh.

**Comment by Salakar** [comment]
@AndrewHenderson you're good to go in v1.0.9 - was just an ios issue, android tests passed without needing a change.
