### ISSUE TITLE
Didn't find class "com.google.firebase.firestore.MetadataChanges" 

### ISSUE THREAD

**Issue by steverob** [invertase/react-native-firebase#1081]
### Issue

When testing the release build in Android, while listening to `onSnapshot`, I'm seeing this exception - 

```
java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.firestore.MetadataChanges" on path: DexPathList[[zip file "/data/app/co.eventstream.GamePlatform-8j9QYyRUi_t25hi2AtV4kQ==/base.apk"
```

Works well in development mode though and in iOS.

Contents of `app/build.gradle`:

```
    implementation(project(':react-native-firebase')) {
        transitive = false
    }
    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation "com.google.firebase:firebase-auth:15.1.0"
    implementation "com.google.firebase:firebase-core:15.0.2"
    implementation "com.google.firebase:firebase-firestore:15.0.0"
    implementation "com.google.firebase:firebase-database:15.0.0"
    implementation "com.google.firebase:firebase-messaging:15.0.2"
    implementation "com.google.firebase:firebase-perf:15.1.0"
    implementation "com.google.firebase:firebase-invites:15.0.1"
```

### Environment

RNFirebase - ` "react-native-firebase": "^4.0.7"`
ReactNative - `0.52.2`
Platform - `Android`
Firebase Module - `Firestore`

![screen shot 2018-05-14 at 2 18 55 pm](https://user-images.githubusercontent.com/1220480/39987470-816ac134-5782-11e8-8f1d-0dddea34e381.png)

**Comment by UADACID** [comment]
same error with me

**Comment by steverob** [comment]
@UADACID delete `node_modules` and run `npm install` again or upgrade to `4.1.0`. Trythis.

**Comment by Salakar** [comment]
@steverob are using proguard minify in release mode on your android build? If you are can you try adding the rules I mentioned [over here](https://github.com/invertase/react-native-firebase/issues/1004#issuecomment-388595714) to your proguard rules (/android/app/proguard-rules.pro)

**Comment by Salakar** [comment]
Actually, it's probably not that, MetadataChanges was added in Firestore 16, which is supported in v4.1.0.  v4.0.7 should be fixed at v15 though so shouldn't be erroring... 

If you could upgrade to v4.1.0 this should stop happening, upgrade notes are on the release: https://github.com/invertase/react-native-firebase/releases/tag/v4.1.0 - nothing too major

**Comment by skymax406** [comment]
Hi same error for me but in 4.1.0

`
> Task :app:processDebugGoogleServices 
Parsing json file: /mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/react-native-app-autonome/android/app/google-services.json

> Task :react-native-firebase:compileDebugJavaWithJavac FAILED
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/react-native-app-autonome/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:20: error: cannot find symbol
import com.google.firebase.firestore.MetadataChanges;
                                    ^
  symbol:   class MetadataChanges
  location: package com.google.firebase.firestore
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/react-native-app-autonome/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:18: error: cannot find symbol
import com.google.firebase.firestore.MetadataChanges;
                                    ^
  symbol:   class MetadataChanges
  location: package com.google.firebase.firestore
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/react-native-app-autonome/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:94: error: cannot find symbol
      MetadataChanges metadataChanges;
      ^
  symbol:   class MetadataChanges
  location: class RNFirebaseFirestoreCollectionReference
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/react-native-app-autonome/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:99: error: cannot find symbol
        metadataChanges = MetadataChanges.INCLUDE;
                          ^
  symbol:   variable MetadataChanges
  location: class RNFirebaseFirestoreCollectionReference
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/react-native-app-autonome/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:101: error: cannot find symbol
        metadataChanges = MetadataChanges.EXCLUDE;
                          ^
  symbol:   variable MetadataChanges
  location: class RNFirebaseFirestoreCollectionReference
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/react-native-app-autonome/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:97: error: cannot find symbol
      MetadataChanges metadataChanges;
      ^
  symbol:   class MetadataChanges
  location: class RNFirebaseFirestoreDocumentReference
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/react-native-app-autonome/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:101: error: cannot find symbol
        metadataChanges = MetadataChanges.INCLUDE;
                          ^
  symbol:   variable MetadataChanges
  location: class RNFirebaseFirestoreDocumentReference
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/react-native-app-autonome/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:103: error: cannot find symbol
        metadataChanges = MetadataChanges.EXCLUDE;
                          ^
  symbol:   variable MetadataChanges
  location: class RNFirebaseFirestoreDocumentReference
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
8 errors


FAILURE: Build failed with an exception.
`
With that config : 
`
 implementation('com.crashlytics.sdk.android:crashlytics:2.9.1@aar') {
        transitive = true
    }
    // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:15.0.2"
    implementation "com.google.firebase:firebase-core:15.0.2"

    
    compile "com.google.android.gms:play-services-auth:15.0.2"
`

**Comment by Salakar** [comment]
@skymax406 you need v16 of the firestore dependency: `implementation "com.google.firebase:firebase-firestore:16.0.0"`

**Comment by skymax406** [comment]
@Salakar its not working :(

```
implementation('com.crashlytics.sdk.android:crashlytics:2.9.1@aar') {
        transitive = true
    }
    // Firebase dependencies
    implementation "com.google.firebase:firebase-firestore:16.0.0"
    implementation "com.google.android.gms:play-services-base:15.0.2"
    implementation "com.google.firebase:firebase-core:15.0.2"
```
Same error

**Comment by skymax406** [comment]
Downgrading `react-native-firebase` to `4.0.7` has worked for me ....

**Comment by UADACID** [comment]
i am solved by using 4.0.4,
- rm -rf node_modules
- open package.json and remove '^' on react-native-firebase
- npm install

**Comment by chrisbianca** [comment]
Is somebody able to run `./gradlew app:dependencies` from their `android` directory when using 4.1.0 and take a look at what version of the `firebase-firestore` lib is being pulled through?

**Comment by dbyilmaz** [comment]
@chrisbianca I have a same problem.

**./gradlew app:dependencies**
**This dependencies:**
[dependencies.txt](https://github.com/invertase/react-native-firebase/files/2007682/dependencies.txt)

**Comment by dbyilmaz** [comment]
@skymax406  it is work thanks 👍 
```
    "react": "^16.3.2",
    "react-native": "^0.55.4",
    "react-native-firebase": "4.0.7",
```

**Comment by chrisbianca** [comment]
@dbyilmaz can you update to v4.1.0 of `react-native-firebase` and set the `firebase-firestore` dependency in your `build.gradle` to v16.0.0 ?

**Comment by dbyilmaz** [comment]
I did @chrisbianca. But it throws an error.
 Gradle dependencies version have to same for work properly.
```
> Task :app:processDebugGoogleServices FAILED
Found com.google.firebase:firebase-firestore:16.0.0, but version 12.0.1 is needed for the google-services plugin.
```

**Comment by chrisbianca** [comment]
It's clear to me that this is a misconfiguration.  `MetadataChanges` was added into v4.1.0 of RNFirebase to support v16 of `firebase-firestore`.

In order for this to work, you **have to follow all of the instructions** set out in the release notes here: https://github.com/invertase/react-native-firebase/releases

This includes, updating the versions of the google-services plugin and android tools plugin, and updating the versions of the android libraries to the versions indicated in the release notes.

I'm closing this as it's not an issue with the library.

**Comment by dbyilmaz** [comment]
@skymax406  can you write  your error message?

**Comment by skymax406** [comment]
Sure

```
> Task :react-native-firebase:compileDebugJavaWithJavac FAILED
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/smarthome-react-native-application/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:20: error: cannot find symbol
import com.google.firebase.firestore.MetadataChanges;
                                    ^
  symbol:   class MetadataChanges
  location: package com.google.firebase.firestore
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/smarthome-react-native-application/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:18: error: cannot find symbol
import com.google.firebase.firestore.MetadataChanges;
                                    ^
  symbol:   class MetadataChanges
  location: package com.google.firebase.firestore
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/smarthome-react-native-application/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:94: error: cannot find symbol
      MetadataChanges metadataChanges;
      ^
  symbol:   class MetadataChanges
  location: class RNFirebaseFirestoreCollectionReference
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/smarthome-react-native-application/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:99: error: cannot find symbol
        metadataChanges = MetadataChanges.INCLUDE;
                          ^
  symbol:   variable MetadataChanges
  location: class RNFirebaseFirestoreCollectionReference
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/smarthome-react-native-application/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:101: error: cannot find symbol
        metadataChanges = MetadataChanges.EXCLUDE;
                          ^
  symbol:   variable MetadataChanges
  location: class RNFirebaseFirestoreCollectionReference
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/smarthome-react-native-application/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:97: error: cannot find symbol
      MetadataChanges metadataChanges;
      ^
  symbol:   class MetadataChanges
  location: class RNFirebaseFirestoreDocumentReference
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/smarthome-react-native-application/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:101: error: cannot find symbol
        metadataChanges = MetadataChanges.INCLUDE;
                          ^
  symbol:   variable MetadataChanges
  location: class RNFirebaseFirestoreDocumentReference
/mnt/3485f5c2-2fbe-4ab4-a5d4-c64c3a0c5673/Projets/smarthome-react-native-application/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:103: error: cannot find symbol
        metadataChanges = MetadataChanges.EXCLUDE;
                          ^
  symbol:   variable MetadataChanges
  location: class RNFirebaseFirestoreDocumentReference
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
8 errors

```

**Comment by skymax406** [comment]
You are right ! I must have been wrong in my tests, I tried without and it had not changed anything.
And now it works, the problem came from there aparemment!  :+1: 

Thx dude !

**Comment by Salakar** [comment]
Good spot @jeanregisser !
