### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by ravivaishnav123** [invertase/react-native-firebase#1082]
Help me this for this issue. I have implemented whole process according to process.
 when import this 
#import "RNFirebaseNotifications.h"
I got a isuue.
### Issue

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNFirebaseMessaging", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_RNFirebaseNotifications", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Environment

1. Application Target Platform: ios os

2. Development Operating System:ios

3. Build Tools:xcode 9.3/9.2

4. React Native version:53.3

5. RNFirebase Version:4.1.0

6. Firebase Module:

**Comment by chrisbianca** [comment]
@ravivaishnav123 did you follow the instructions for setting up Messaging as well as Notifications?

**Comment by jnrepo** [comment]
@chrisbianca I'm getting this same issue. I have followed the setup instructions for messaging and notifications in the links below.

https://rnfirebase.io/docs/v4.2.x/notifications/ios
https://rnfirebase.io/docs/v4.2.x/messaging/ios

**Comment by chrisbianca** [comment]
Generally this happens when your XCode workspace is out of sync with the pod files.

Please follow the steps here to attempt to resolve your issues: https://rnfirebase.io/docs/v4.2.x/troubleshooting/ios#Duplicate-Symbols-/-Undefined-Symbols-(build-time-error)

If this does not fix the problem, please feel free to re-open

**Comment by muhammadsr** [comment]
Having slightly similar issue. @chrisbianca suggested solution did not help unfortunately.

<img width="1011" alt="screen shot 2018-08-22 at 2 46 20 pm" src="https://user-images.githubusercontent.com/1937488/44492680-49a96980-a61a-11e8-9b57-2d3cda534d8d.png">
