### ISSUE TITLE
Firebase - big batch commit hugs (or timeouts?) with no error

### ISSUE THREAD

**Issue by rubengarciam** [invertase/react-native-firebase#1089]
### Issue

Writing a _WriteBatch.commit()_ when the batch contains a substantial amount of __writes_ (close to 1k) hungs (or timeouts, I can't really tell) without returning any error.

Not sure if there's a limit to the amount of writes a batch can perform?

**Udate:** After a while, this is displayed in dev tools console:

```
PhoneAuthListener.js:146 
Error: Firestore: Client specified an invalid argument. (firestore/invalid-argument).
    at createErrorFromErrorData (NativeModules.js:121)
    at NativeModules.js:78
    at MessageQueue.__invokeCallback (MessageQueue.js:398)
    at MessageQueue.js:137
    at MessageQueue.__guardSafe (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:136)
    at debuggerWorker.js:70
```

### Environment

1. Application Target Platform:

iOS

2. Development Operating System:

macOS High Sierra 10.13.4

3. Build Tools:

XCode 9.3.1 (9E501)

4. React Native version:

0.55.3

5. RNFirebase Version:

4.0.6

6. Firebase Module:

Firestore

**Comment by chrisbianca** [comment]
@rubengarciam I'd imagine you're running up against one of more limits on the Firestore database which are explained here: https://firebase.google.com/docs/firestore/quotas

What I am slightly concerned by, is why this doesn't get reported instantly, but takes some time before it's reported back to you. How long are we talking?

**Comment by chrisbianca** [comment]
I'm going to close this due to lack of further information. Please re-open if this is still an issue.
