### ISSUE TITLE
IOS background onMessage

### ISSUE THREAD

**Issue by niocncn** [invertase/react-native-firebase#1092]
Is it possible to awake IOS app from background to play sound? 
There are two types of messages: 'Data' and 'Notification' as it's written in documentation.
Can I implement `onMessage` method to wake up my app after receiving `data` message as said in documentation?
```
firebase.messaging().onMessage((message: RemoteMessage) => {
    this.setState({message});
});
```
I tried to do as said in documentation, but nothing happens.

**Comment by chrisbianca** [comment]
We're aware of this and hope to have the functionality added soon. Please follow: https://github.com/invertase/react-native-firebase/issues/971

**Comment by ramesh456** [comment]
Hi , have you found any solution ?

**Comment by ramesh456** [comment]
@chrisbianca  Is there any solution for new version ?
