### ISSUE TITLE
onAuthStateChanged does not(?) supply a Firebase.User object.

### ISSUE THREAD

**Issue by ChristianTucker** [invertase/react-native-firebase#110]
As per the documentation the `onAuthStateChanged` callback should pass in a `Firebase.User` object in which you would be allowed to call methods, such as `getToken()` See [docs](https://firebase.google.com/docs/reference/js/firebase.User).

Rather or not a Firebase.User object is actually supplied or not, I'm not completely sure, which is why there's a (?) in my issue title. Howwever, `getToken` is not a function on the user object passed back from the `onAuthStateChanged` listener, and the firebase documentation clearly states that it should be available

**Comment by Salakar** [comment]
@ChristianTucker can confirm this definitely returns an instance of the Firebase.User class with the methods, also the getToken method is there:
![image](https://cloud.githubusercontent.com/assets/5347038/25995393/f9fc6656-3709-11e7-99d8-8c0d989d516e.png)

What RNF version are you on? iOS or Android for this issue?

**Comment by ChristianTucker** [comment]
We haven't tested the application on iOS yet, so as far as we know this is an Android issue. 

We're running `react-native-firebase: 1.0.0-alpha12` and `react-native: 0.43.0-rc.4` 

The code this shows this problem is below:

```
firebase.auth().onAuthStateChanged((user) => {
  if(user) {
    console.log('user.getToken', user.getToken); // undefined
    console.log('current.getToken', firebase.auth().currentUser.getToken); // Function information
    
    // user.getToken is not a function    
    user.getToken().then(() => { ... });

  }
});

**Comment by ChristianTucker** [comment]
Here's prototype differences between the user object returned from `onAuthStateChanged` and `firebase.auth().currentUser`

https://gyazo.com/73bb5ebc954f9aaa7c25a4f91dcbf22d

**Comment by Salakar** [comment]
@ChristianTucker I can confirm this has already been fixed in a later version, upgrade to v1.0.2 and you should be good to go.

**Comment by ChristianTucker** [comment]
@Salakar  Alright, I'll let them know to update. Thanks.

**Comment by Salakar** [comment]
The commit: https://github.com/invertase/react-native-firebase/commit/d2a9bb7fa3d89343443411af42e88c734587d87e if it helps.
