### ISSUE TITLE
Any plan to support DFP as well? (DFPBannerView etc.)

### ISSUE THREAD

**Issue by giladno** [invertase/react-native-firebase#1100]

**Comment by Ehesp** [comment]
Hey, a rework of Admob is planned for 4.3.0 release. Whether or not we integrate DFP is to be decided, as it does fall outside of Firebase. That being said, once there's a solid, tested implementation for Admob we may release a standalone DFP package as we'd already have a good base to work from.

**Comment by ianwelsh** [comment]
Looks like Admob support was added in v6. Are there any new plans to add DFP support?

**Comment by Ehesp** [comment]
@ianwelsh we're only supporting what Firebase provides in this library. Honestly though, my knowledge of AdMob vs DPF isn't great. From what I see, supporting DFP would require additional SDKs and "non-Firebase" products.

**Comment by ianwelsh** [comment]
@Ehesp I'm not sure whether it's considered "non-Firebase", but it seems to use the same SDKs as AdMob. For instance, it's include in [com.google.android.gms.ads on Android](https://firebase.google.com/docs/reference/android/com/google/android/gms/ads/doubleclick/package-summary) and [GoogleMobileAds on iOS](https://firebase.google.com/docs/reference/ios/googlemobileads/api/reference/Classes/DFPBannerView), both of which are in the https://firebase.google.com docs.

**Comment by Almouro** [comment]
Hi @Ehesp, would a PR for DFP support be accepted on the repository?

There's not a lot of difference between a DFPBanner and GADBanner, since DFPBanner inherits from GADBanner, so I'd be happy to submit a PR here.

**Comment by mikehardy** [comment]
@Almouro I'm the person-currently-merging things and I'd consider a PR if it was small. If you look at the structure of the libraries, I challenge you to find the "Ads related firebase things" here:

https://firebase.google.com/docs/reference/android/packages (there are ads of course, but inside firebase scope?)
https://github.com/firebase/firebase-android-sdk/
https://github.com/firebase/firebase-ios-sdk/

My point being that AdMob does not really belong in a Firebase wrapper. This should all be in https://github.com/sbugert/react-native-admob and we *should* delete all AdMob-related items from here

So if at all possible I encourage you to focus effort on react-native-admob which should have a future, whereas development in AdMob here - from a philosophical position of where things should be - is a dead-end
