### ISSUE TITLE
RNFirebaseAdMobRewardedVideo is not abstract and does not override abstract method onRewardedVideoCompleted()

### ISSUE THREAD

**Issue by john1jan** [invertase/react-native-firebase#1102]
RNFirebaseAdMobRewardedVideo is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener
public class RNFirebaseAdMobRewardedVideo implements RewardedVideoAdListener {
       ^
Note: Some input files use or override a deprecated API.

```
ext.firebaseVersion = '15.0.0'
classpath 'com.google.gms:google-services:3.2.1'
compile "com.google.android.gms:play-services-base:15.0.0"
compile 'com.google.android.gms:play-services-auth:15.0.0'
compile "com.google.firebase:firebase-config:15.0.0"
compile ("com.google.firebase:firebase-analytics:15.0.0"){
        force = true
}
compile 'com.google.firebase:firebase-core:15.0.0' 
```

**Comment by chrisbianca** [comment]
What version of react-native-firebase are you using? You need to be on 4.1.x to support v15+ of the android libs.
