### ISSUE TITLE
Error: You attempted to use a firebase module that's not installed on your Android project by calling firebase.notifications()

### ISSUE THREAD

**Issue by geekymsk** [invertase/react-native-firebase#1108]
### Issue

i am getting the above error in android after adding notifications to the app.
Error: You attempted to use a firebase module that's not installed on your Android project by calling firebase.notifications()

 Ensure you have:

 1) Installed the required Firebase Android SDK dependency 'com.google.firebase:firebase-notifications' in your 'android/app/build.gradle' file.
    
 2) Imported the 'io.invertase.firebase.notifications.RNFirebaseNotificationsPackage' module in your 'MainApplication.java' file.
    
3) Added the 'new RNFirebaseNotificationsPackage()' line inside of the RN 'getPackages()' method list.

  even when i do above things (com.google.firebase:firebase-notifications:16.0.0) i am getting
 that the  firebase-notifications:16.0.0 is not found error while running.

### Environment

 Android

1. Application Target Platform:

 macOS Sierra

2. Development Operating System:

 Android Studio 
3. Build Tools:

4. React Native version: 0.54.4

5. RNFirebase Version: ^4.1.0

6. Firebase Module:  firebase.notifications()

**Comment by geekymsk** [comment]
com.google.firebase:firebase-notifications:16.0.0

**Comment by cristianonescu** [comment]
I also have this issue. any solution yet?

**Comment by chrisbianca** [comment]
As mentioned by @cristianonescu and in the documentation, notifications requires that messaging is also correctly setup.  Please take a look at the android installation documentation.

**Comment by tal987** [comment]
The solution for this is to add those to app/build.gradle :
     
`implementation 'com.google.firebase:firebase-core:16.0.1'`
  `  implementation 'com.google.firebase:firebase-messaging:17.0.0' `
 **make sure they are on the latest version**
you don't need to import the com.google.firebase:firebase-notifications

then 1. Imported the 'io.invertase.firebase.notifications.RNFirebaseNotificationsPackage' module in your 'MainApplication.java' file.

2. Added the 'new RNFirebaseNotificationsPackage()' line inside of the RN 'getPackages()' method list.

**Comment by msqar** [comment]
@tal987 I have done the same but ofc with different versions and keeps throwing that error.

```
    // Firebase dependencies
    implementation 'com.google.android.gms:play-services-base:16.1.0'
    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation 'com.google.firebase:firebase-messaging:19.0.0'
```

These are the ones i added into the app/build.gradle.

Also have in the MainApplication the `import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;` imported and added into the Package array.

**Comment by mikehardy** [comment]
@msqar this indicates a fundamental integration problem for the app. It looks like you are attempting to stay on the pre-AndroidX support libraries, I would not advise that. I would migrate to AndroidX then integrate react-native-firebase like this for react-native 0.59 and below https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh (I am assuming that you are not on RN0.60+ yet if you are not on AndroidX yet)

**Comment by msqar** [comment]
@mikehardy yes Mike, i'm using 0.60.6 with AndroidX i run `npx jetify` too. On iOS it works fine, on Android throws this error.

**Comment by mikehardy** [comment]
very strange, if you get the error in the title ('You attempted to use a firebase module...') anywhere, you should get it everywhere. For an example of a react-native 0.60+ project + RNFBv5 https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh might be interesting or might be repetitive, but the comments show things. `npx react-native-clean-project clean-project-auto && yarn` (or npm, I guess) followed by a rebuild might also be interesting. Most unexpected to get a module installation error only sometimes

**Comment by msqar** [comment]
@mikehardy indeed strange. This is what Sentry is showing:

```
Error: You attempted to use a firebase module that's not installed on your Android project by calling firebase.notifications().

Ensure you have:

1) Installed the required Firebase Android SDK dependency 'com.google.firebase:firebase-notifications' in ...
    at See (android for full setup instructions.:0)
    at initialiseNativeModule(9c6846f4-945c-4ca0-bd66-67b99480b461:178988)
    at Notifications.ModuleBase(9c6846f4-945c-4ca0-bd66-67b99480b461:179045)
    at new Notifications(9c6846f4-945c-4ca0-bd66-67b99480b461:177938)
    at (9c6846f4-945c-4ca0-bd66-67b99480b461:175640)
...
(6 additional frame(s) were not displayed)
```
I'll take a look at your .sh file and see what I can do that's different on mine.

**Comment by kosalram-dev** [comment]
@mikehardy 

I end up getting the same error as yours. Have you solved it?

**Comment by Biplovkumar** [comment]
Still getting error in latest version (react native) with react-native-firebase 5.
plz open It. @mikehardy

**Comment by mikehardy** [comment]
@Biplovkumar no, react-native-firebase 5 is out of support.

**Comment by Biplovkumar** [comment]
Sir but many methods which is not available in Version 6.
so  i am not able to use version 6.

```
1. firebase.notifications().setBadge(0)
2. firebase.notifications().getBadge()
3. firebase.notifications().onNotification((notification) => {}   (**Get Forground notifications**.)
4. firebase.notifications().removeAllDeliveredNotifications();
```

i am stuck from 4 days.
i have updated my app in latest version but cause of these methods i am not able to update fire base too.
Cause of firebase, i am not able to update my app.
plz help @mikehardy .
thanku for reply.

**Comment by mikehardy** [comment]
@Biplovkumar v6 has been out nearly a year now? It was widely discussed that it would remove local device notifications APIs, as they are not firebase-specific and are a monster to maintain  

The issues list has information, you can see the tracker issue in the query result here https://github.com/invertase/react-native-firebase/issues?q=is%3Aissue+v6+notifications+sort%3Acomments-desc

It has been answered a bunch but the docs were not explicit enough, I just updated them so they are crystal clear on what, why, and what to do: https://rnfirebase.io/migrating-to-v6#notifications

**Comment by Biplovkumar** [comment]
thanks @mikehardy  for the reply.
but not satisfactory answer.
cause of I need all replacement Method (Above given 4) in version 6.
So i can work same.

**Comment by mikehardy** [comment]
Unfortunately, it will not work the same for the reasons I stated. If you want support you will upgrade to current stable versions, and if you want notifications you will integrate a 3rd party notifications package
