### ISSUE TITLE
no visible @interface for 'FIRQuery' declares the selector 'addSnapshotListenerWithIncludeMetadataChanges:listener

### ISSUE THREAD

**Issue by geekymsk** [invertase/react-native-firebase#1110]
### Issue

i am geetting  No visible @interface for 'FIRQuery' declares the selector 'addSnapshotListenerWithIncludeMetadataChanges:listener:' in xcode.

      pod 'GooglePlaces'
      pod 'GooglePlacePicker'
      pod 'Firebase/Core', '~> 4.13.0'
      pod 'Firebase/Firestore'
      pod 'Firebase/Storage'
      pod 'Firebase/Auth'
      pod 'Fabric'
      pod 'Crashlytics'
      pod 'Firebase/Messaging'
    

### Environment

iOS

1. Application Target Platform:

 macOS Sierra

2. Development Operating System:

Xcode
3. Build Tools:

4. React Native version: 0.54.4

5. RNFirebase Version: ^4.1.0

6. Firebase Module:

**Comment by kryhtin** [comment]
I'm experiencing same issue even after upgrading to 4.2.0 
![screen shot 2018-05-22 at 10 06 18](https://user-images.githubusercontent.com/9670566/40341595-db4c85f4-5da7-11e8-8ae7-41cdd3028a1c.png)

**Comment by longfay** [comment]
Change the build location under the workspace settings, put the build location under your own project

**Comment by cristianPerez** [comment]
@geekymsk yes it was solved with @chrisbianca suggestions, thanks man really nice npm package, it's the best on this moment for my react native app.
