### ISSUE TITLE
How to make notifications always visible?

### ISSUE THREAD

**Issue by jkdrangel** [invertase/react-native-firebase#1114]
### Issue

I need to show notifications in my app with the app in foreground, exist a configuration to this?

### Environment

1. Application Target Platform: 
Both

4. React Native version:
0.51.0

5. RNFirebase Version:
3.2.4

6. Firebase Module:
Cloud Messaging

**Comment by chrisbianca** [comment]
@jkdrangel You'll want to update to v4+ of React Native Firebase.  There has been massive amounts of work done to improve messaging and notifications and add documentation specifically for this.
