### ISSUE TITLE
Authentication: signInAndRetrieveDataWithEmailAndPassword() can't catch error on Android

### ISSUE THREAD

**Issue by clundberg1** [invertase/react-native-firebase#1116]
### Issue

If I call signInAndRetrieveDataWithEmailAndPassword() and pass it an empty email/password, I expect it to throw an error and be able to catch it. On IOS that works correctly, but on Android the app crashes apparently bypassing the catch()

Edit: I just noticed that the same problem occurs with createUserAndRetrieveDataWithEmailAndPassword()

4. React Native version:

0.53.0

5. RNFirebase Version:

15.0.0

6. Firebase Module:
Authentication

**Comment by chrisbianca** [comment]
We have spoken to Firebase about this in the past as it should be consistent across the SDKs, but unfortunately they haven't fixed it their end yet.

I would strongly suggest that you don't allow people to submit empty strings as their email and password - that will resolve this issue.
