### ISSUE TITLE
sendSignInLinkToEmail requires actionCodeSettings

### ISSUE THREAD

**Issue by rikur** [invertase/react-native-firebase#1117]
### Issue

Current implementation is broken as it tries to call the SDK with `null` as actionCodeSettings.

### Environment

Android

1. Application Target Platform:

Android SDK 26

2. Development Operating System:

Android SDK 26

3. Build Tools:

JDK8

4. React Native version:

latest

5. RNFirebase Version:

4.2.0

6. Firebase Module:

Auth

**Comment by rikur** [comment]
By passing `actionCodeSettings` to `firebase.auth(). sendSignInLinkToEmail()` as the second parameter, things work smoothly. But I think developers should be oblivious to this whole `actionCodeSettings`

**Comment by chrisbianca** [comment]
This is correct behaviour as per the official Firebase JS SDK we follow: https://firebase.google.com/docs/reference/js/firebase.auth.Auth#sendSignInLinkToEmail

We are not able to generate `ActionCodeSettings` for you as there are fields which we have no way of being able to predict values for.
