### ISSUE TITLE
[ios] [pods] firebase.crashlytics() not found

### ISSUE THREAD

**Issue by AndrewJack** [invertase/react-native-firebase#1122]
### Issue

Crashlytics library is not found when using Cocoapods 1.5, in a project is using Cocoapods for all dependencies (no manual linking).

When calling `firebase.crashlytics()` the following error is shown:
```
Error: You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.crashlytics().
```

#### Example project:
https://github.com/AndrewJack/react-native-firebase-starter/tree/demo/cocoapods_1.5

```bash
yarn install
cd ios
pod install
```

Observe - Crashlytics not in the module list.
Comment out `firebase.crashlytics().log` in `componentDidMount` to see error

#### Solution
I have fixed this in my project by adding `s.dependency 'Crashlytics'` to the RNFirebase podspec.

I understand that this may not be wanted for users that don't want crashlytics in their ios project.

To solve this I'd like your feedback on the preferred solution.

**Either**:
1) Add `s.dependency 'Crashlytics'` to podspec and all users would download and link the crashlytics dependency (guessing this isn't the preferred option)
2) Add [subspecs](https://guides.cocoapods.org/syntax/podspec.html#subspec) to the podspec like [React Native](https://github.com/facebook/react-native/blob/master/React.podspec#L46)
3) Add header search paths to the podspec e.g. `ss.pod_target_xcconfig  = { "HEADER_SEARCH_PATHS" => "\"$(PODS_TARGET_SRCROOT)/Crashlytics/iOS\"" }`

Option 2 pod import would look something like this:
```ruby
pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios', :subspecs => [		
  "Core",
  "Analytics",
  "Crashlytics",		
  "Perf"
  # other dependencies
]
```

### Environment

1. Application Target Platform:

macOS Sierra - 10.13.4

2. Development Operating System:

iOS

3. Build Tools:

Xcode 9.2
Cocoapods 1.5.2

4. React Native version:

0.55.3

5. RNFirebase Version:

4.1.0 (Will occur on later versions too)

6. Firebase Module:

Crashlytics

**Comment by koloff** [comment]
```
Possible Unhandled Promise Rejection (id: 0):
Error: You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.auth().
```

I tried reinstalling everything tens of times, nothing works... How can I revert back to the older cocoapods version to try to fix the problem?

**Comment by AndrewJack** [comment]
@koloff https://stackoverflow.com/questions/20487849/how-to-downgrade-or-install-an-older-version-of-cocoapods 

Then run pod update I guess or revert your code.

**Comment by Eyesonly88** [comment]
I hit this issue as well. 
I solved it by updating to the latest version of this library `"4.3.3"` and `pod update`.

**Comment by AndrewJack** [comment]
There hasn't been any recent changes to the podspec. So I don't think this has been fixed, I'll re-test to check.

I'll try and submit a potential fix this week.

**Comment by AndrewJack** [comment]
I've tested in my [test project](https://github.com/AndrewJack/react-native-firebase-starter/tree/demo/cocoapods_1.5) and our main one. This commit fixes the issue: https://github.com/invertase/react-native-firebase/commit/1d2757dc308c6dc51ecd81a6f91df5298bfb5342

Subspecs for the ios implementation may be a useful addition. and would save linking extra code that is not used. I will submit a pr when I get a chance to play around with that.

I'll close this issue as the original problem has been fixed.

**Comment by Salakar** [comment]
@AndrewJack apologies I forgot to tag this as fixed in the release notes and reply back here. Drowning in commits 🙈 

Subspecs might be useful indeed, let me know how you get on and if you need anything, on here, discord or twitter.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by lfalkner** [comment]
Seeing the same issue with the following versions:
Podfile.lock
DEPENDENCIES:
  - Crashlytics (~> 3.10.7)
  - Fabric (~> 1.7.11)
  - Firebase/Core (~> 5.9.0)

package.json
    "react-native-firebase": "^5.0.0"

Per instructions here, https://rnfirebase.io/docs/v5.x.x/installation/ios, I've installed Firebase Core via CocoaPods, but installed react-native-firebase via linking. (The recommended installation steps).

**Comment by Baskerville42** [comment]
The same issue
```
platform :ios, '9.0'

target 'SayblakeApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # RN Pods
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'RCTImage',
    'RCTGeolocation'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Pods for SayblakeApp
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'
  pod 'Firebase/Firestore', '~> 5.3.0'
  pod 'Firebase/Storage', '~> 5.3.0'
  pod 'Fabric', '~> 1.7.11'
  pod 'Crashlytics', '~> 3.10.7'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'SayblakeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
 installer.pods_project.targets.each do |target|
   if target.name == 'React'
     target.remove_from_project
   end
 end
end
```

`"react-native": "0.56.0"`
`"react-native-firebase": "^4.3.8"`

<img width="421" alt="screen shot 2018-10-03 at 11 03 01 am" src="https://user-images.githubusercontent.com/5596941/46397829-f25be600-c6fb-11e8-9023-812c8978313c.png">

**Comment by recepkocur** [comment]
+1

**Comment by carrchr** [comment]
I am suffering the same issue trying to use RNFirebase and Crashlytics when calling in `firebase.crashlytics().recordError()` in Javascript. 

installed RNFirebase via `yarn run react-native link react-native-firebase`

```
package.json snippet
"react-native": "0.55.4",
"react-native-firebase": "4.3.8",
"react-native-schemes-manager": "^1.0.5",
```

```
Podfile snippet
use_frameworks!

pod 'Firebase/Core', '~> 5.3.0'
pod 'Google-Mobile-Ads-SDK', '7.27.0'
pod 'GoogleAppIndexing'
pod 'Fabric', '~> 1.7.5'
pod 'Crashlytics', '~> 3.10.4'
```
