### ISSUE TITLE
passwordless login link doesn't automatically open into the app

### ISSUE THREAD

**Issue by rikur** [invertase/react-native-firebase#1125]
### Issue

I've exhausted my options on how to get the links sent by firebase for passwordless login to open the app by default. I've set `actionCodeSettings.handleCodeInApp` to `true` to no effect. I tried adding ?efr=1 to the url as well to no effect.

The links open into the application properly on Android. On iOS I get the firebase "app preview page " and can click "open" to open it in app. But this is not idea for login links. My best guess is that `true` doesn't properly translate to BOOL `YES` to firebase SDK.

### Environment

iOS

4. React Native version:

latest

5. RNFirebase Version:

```
implementation project(':react-native-firebase')
    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation "com.google.firebase:firebase-core:15.0.2"
    implementation "com.google.firebase:firebase-auth:15.1.0"
    implementation "com.google.firebase:firebase-firestore:16.0.0"
    implementation "com.google.firebase:firebase-invites:15.0.1"
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.1@aar') {
      transitive = true
    }
```

**Comment by dannywitters** [comment]
@rikur have you figured out a solution to this?

**Comment by rikur** [comment]
@dannyshisler I don't think I found a solution, no. I have since moved away from firebase.
