### ISSUE TITLE
GoogleSigninError: Sign-in in progress

### ISSUE THREAD

**Issue by NathHorrigan** [invertase/react-native-firebase#1127]
### Issue

`GoogleSigninError: Sign-in in progress` error when logging in with `react-native-community/react-native-google-signin` package after logging out. First login works but second does not.

This isn't an issue with this package directly but is problematic since that is the official way of signing in with google as stated in the docs. The issue on the the repo hasn't been noticed really (https://github.com/react-native-community/react-native-google-signin/issues/378)

### Environment:
Android (AFAIK but haven't tested iOS)

### RNFirebase Version: 
4.0.2

### Firebase Module: 
Auth

**Comment by chrisbianca** [comment]
Closing as this is not a react-native-firebase issue.
