### ISSUE TITLE
RNFirebaseNotifications.h file not found

### ISSUE THREAD

**Issue by ahmetilhann** [invertase/react-native-firebase#1128]
I am using podfıle. I get an error RNFirebaseNotifications.h file not found

My podfile

```
platform :ios, '9.0'

target 'dfvTechnische' do
  pod 'Firebase/Messaging'
end
```

My Error
<img width="730" alt="ekran resmi 2018-05-24 00 43 00" src="https://user-images.githubusercontent.com/5680957/40452730-8b663ebe-5eeb-11e8-842b-2765ba91d5d0.png">

My versions: 
<img width="302" alt="ekran resmi 2018-05-24 00 45 54" src="https://user-images.githubusercontent.com/5680957/40452817-d959ab60-5eeb-11e8-8e1d-21415d580f6f.png">

**Comment by shresthaKiran** [comment]
You can find the answer here https://github.com/invertase/react-native-firebase/issues/979

**Comment by ahmetilhann** [comment]
My Solution

Step 1:  Run it `pod install`
```
platform :ios, '9.0'

target 'projectName' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', 
    'DevSupport', 
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', 
    'RCTAnimation', 
  ]
  
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

```

Step 2: run it `react-native link react-native-firebase`

Step 3: Check the Build Setting > Header Search paths
<img width="800" alt="ekran resmi 2018-05-26 12 40 11" src="https://user-images.githubusercontent.com/5680957/40574830-382ed992-60e2-11e8-8399-0d1a267457ee.png">
