### ISSUE TITLE
The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.

### ISSUE THREAD

**Issue by geekymsk** [invertase/react-native-firebase#1131]
### Issue

Getting this in android studio logcat and app freezes

05-24 15:46:57.780 11860-11930/com.geekyants.uberx W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.SizeReportingShadowNode
05-24 15:46:57.801 11860-11860/com.geekyants.uberx W/System: ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/0000001e/n/armeabi
05-24 15:46:58.468 11860-11860/com.geekyants.uberx W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
05-24 15:46:58.910 11860-11930/com.geekyants.uberx W/Firestore: (0.6.6-dev) [Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
    To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
    
    FirebaseFirestore firestore = FirebaseFirestore.getInstance();
    FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
        .setTimestampsInSnapshotsEnabled(true)
        .build();
    firestore.setFirestoreSettings(settings);
    
    With this change, timestamps stored in Cloud Firestore will be read back as com.google.firebase.Timestamp objects instead of as system java.util.Date objects. So you will also need to update code expecting a java.util.Date to instead expect a Timestamp. For example:
    
    // Old:
    java.util.Date date = snapshot.getDate("created_at");
    // New:
    Timestamp timestamp = snapshot.getTimestamp("created_at");
    java.util.Date date = timestamp.toDate();
    
    Please audit all existing usages of java.util.Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.

### Environment

 Android

1. Application Target Platform:

 macOS Sierra
2. Development Operating System:

Xcode or Android Studio version
3. Build Tools:

4. React Native version: 0.54.4

5. RNFirebase Version: ^4.1.0

6. Firebase Module:

**Comment by ashour** [comment]
The same warning is appearing in the XCode console for iOS:

<Warning>: 4.13.0 - [Firebase/Firestore][I-FST000001] The behavior for system Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
	To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
	
	let db = Firestore.firestore()
	let settings = db.settings
	settings.areTimestampsInSnapshotsEnabled = true
	db.settings = settings
	
	With this change, timestamps stored in Cloud Firestore will be read back as Firebase Timestamp objects instead of as system Date objects. So you will also need to update code expecting a Date to instead expect a Timestamp. For example:
	
	// old:
	let date: Date = documentSnapshot.get("created_at") as! Date
	// new:
	let timestamp: Timestamp = documentSnapshot.get("created_at") as! Timestamp
	let date: Date = timestamp.dateValue()
	
	Please audit all existing usages of Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.

### Environment



1. Application Target Platform: iOS



2. Development Operating System: macOS High Sierra 10.13.4



3. Build Tools: XCode 9.3



4. React Native version: 0.55.4



5. RNFirebase Version: 3.3.1



6. Firebase Module: Firestore

**Comment by sowdri** [comment]
Guys any update on this? This issue has to be reopened as the fix has not be released yet. Thank you
