### ISSUE TITLE
Implementing consent-library for Admob - GDPR 

### ISSUE THREAD

**Issue by CristiTr** [invertase/react-native-firebase#1133]
Hi guys,

Some of you may have noticed  that AdMob now requires to implement the consent-library to get in app consent from users.
(if you are based in the EU this is required for all users) 

Google eu-consent documentation:
[Android](https://developers.google.com/admob/android/eu-consent)
[IOS](https://developers.google.com/admob/ios/eu-consent)

On a first look these libraries look buggy, also we know that they were written under a  huge time pressure. 

Is there any plan to implement the eu-consent library in **RNFirebase**?

How do you tackle this issue? it has been only a few days since this requirement started showing in AdMob and eCPM dropped immediately to about 30% of the usual rate.

**Comment by Ehesp** [comment]
Thanks for brining this up, we'll discuss internally about the priority as an admob rework is in the pipeline and this is something which will need consideration. 

I've raised it on https://react-native-firebase.canny.io/feature-requests/p/implement-consent-library-admob so we can keep track. Thanks!

**Comment by lwansbrough** [comment]
+1. If this is a priority or more importantly, a _requirement_ made by AdMob, this library _needs_ to implement it.

**Comment by bladefist** [comment]
Not having the consent sdk likely means users of this repo are leaving a lot of CPM on the table.

**Comment by bearty** [comment]
Do you have any news about implementing GDPR? 
I did't find any information in documentation and in "request board" (search and load more not work)

**Comment by Salakar** [comment]
@bearty the board should be fixed now sorry 🙈

**Comment by czater** [comment]
any news?

**Comment by Salakar** [comment]
PR's would be welcome on this, right now we have our hands full.

**Comment by djpetenice** [comment]
Is there any new on this? I've just moved over from react-native-admob which also didn't have the GDPR constent library implemented.

**Comment by Salakar** [comment]
This will most likely land as part of v6.

You can track the progression of v6 here: https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by djpetenice** [comment]
@Salakar thanks for the update 👍

**Comment by Ehesp** [comment]
Hi All this is in progress and will be part of v6.
