### ISSUE TITLE
Refresh token error on Android

### ISSUE THREAD

**Issue by RocKhalil** [invertase/react-native-firebase#1134]
### Issue

`refresh_token` is being returned on iOS but getting `User.refreshToken is unsupported by the native Firebase SDKs.` on Android

### Environment

1. Application Target Platform: Android

2. Development Operating System: MacOS

3. Build Tools: Command Line

4. React Native version:  0.51.0

5. RNFirebase Version: 4.1.0

6. Firebase Module: Phone Auth

**Comment by Ehesp** [comment]
Please use https://rnfirebase.io/docs/v4.2.x/auth/reference/User#getIdToken, getting the `refreshToken` in RNFirebase is unsupported (https://rnfirebase.io/docs/v4.2.x/auth/reference/User#refreshToken).

**Comment by stevehs17** [comment]
@Ehesp 
getIdToken doesn't provide a refresh token, only an access token. That token expires after an hour, and the tokens getIdToken returns cease to be valid.

Using getIdToken is NOT a workaround for the problem. You seem to be saying the problem is insoluble.

**Comment by phuocantd** [comment]
same here, iOS has return refreshToken but Android is not
