### ISSUE TITLE
ARC Semantic issue

### ISSUE THREAD

**Issue by sinevitch** [invertase/react-native-firebase#1136]
Help me please

I faced the face with a problem:

![image](https://user-images.githubusercontent.com/35930695/40514617-7a9ae482-5fb2-11e8-85e1-945ad5d633fa.png)

### Environment

Ios
1. Application Target Platform:
macOS Sierra
2. Development Operating System:
Xcode Version 9.3 (9E145)
4. React Native version:
"react-native": "^0.55.3"
5. RNFirebase Version:
"react-native-firebase": "^4.0.6",
6. Firebase Module:
pod 'Firebase/Core', '~> 4.13.0'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'

**Comment by tanishqaggarwal** [comment]
Change to 'Firebase/Core', '~> 5.0.1' in your pod file.

See #1110
