### ISSUE TITLE
'FirebaseCore/FIRAnalyticsConfiguration.h' file not found  getting this error 

### ISSUE THREAD

**Issue by somsin** [invertase/react-native-firebase#1139]
i used pod install , but facing this error , whats fix for this

**Comment by Ehesp** [comment]
Please follow the issue template and we'll be able to help.

**Comment by somsin** [comment]
i have used template but getting same error

**Comment by somsin** [comment]
'FirebaseAnalytics/FIRAnalyticsConfiguration.h' file not found

**Comment by somsin** [comment]
[!] CocoaPods could not find compatible versions for pod "Firebase/Core":
  In Podfile:
    Firebase/Analytics (= 4.2.0) was resolved to 4.2.0, which depends on
      Firebase/Core (= 4.2.0)

    Firebase/Core

CocoaPods could not find compatible versions for pod "Firebase/Firestore":
  In Podfile:
    Firebase/Firestore

Specs satisfying the `Firebase/Firestore` dependency were found, but they required a higher minimum deployment target.
CocoaPods could not find compatible versions for pod "FirebaseCore":
  In Podfile:
    Firebase/Analytics (= 4.2.0) was resolved to 4.2.0, which depends on
      Firebase/Core (= 4.2.0) was resolved to 4.2.0, which depends on
        FirebaseAnalytics (= 4.0.3) was resolved to 4.0.3, which depends on
          FirebaseCore (~> 4.0)

    Firebase/Analytics (= 4.2.0) was resolved to 4.2.0, which depends on
      Firebase/Core (= 4.2.0) was resolved to 4.2.0, which depends on
        FirebaseCore (= 4.0.7)

**Comment by zerbinidamata** [comment]
Any updates on this?
