### ISSUE TITLE
google-services plugin could not detect any version for com.google.android.gms or com.google.firebase

### ISSUE THREAD

**Issue by davidohayon669** [invertase/react-native-firebase#114]
When I build on Android I get this warning:

```
google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.
please apply google-services plugin at the bottom of the build file.
```

Needless to say I did everything according to instructions, including that line in `app/build.gradle`

The build succeeds and everything seems to work fine... Should I care about it?

**Comment by Ehesp** [comment]
Could we see the dependancies section of your build.gradle please?

**Comment by davidohayon669** [comment]
@Ehesp Eventually what I did that stopped this message was adding:

`compile 'com.google.firebase:firebase-core:10.2.0'`

to those dependencies (same version of firebase as in this package) as suggested in [react-native-fcm](https://github.com/evollu/react-native-fcm) (Android Configuration):

`//this decides your firebase SDK version`

Seems like a good thing? Maybe it should be added to the instructions here
