### ISSUE TITLE
How to translate the permission request for Push Notification (Messaging) in iOS

### ISSUE THREAD

**Issue by gianpaj** [invertase/react-native-firebase#1141]
<img src="https://user-images.githubusercontent.com/899175/40542246-0f349960-6028-11e8-9248-6591f54d08e0.png" alt="drawing" width="375px"/>

For example: the app support both English and Ukrainian.
All the other strings are translated via a JS plugin or Xcode.

How do I display the Ukranian translation for this?

Thanks 🙂

### Environment

iOS

4. React Native version:

0.55.4

5. RNFirebase Version:

4.2.0

6. Firebase Module:

Messaging

**Comment by chrisbianca** [comment]
Closing in favour of the feature request on Canny: https://react-native-firebase.canny.io/admin/board/feature-requests/p/translate-the-permission-request-for-push-notification-messaging-in-ios
