### ISSUE TITLE
Production build on Android not responding until clear data

### ISSUE THREAD

**Issue by razvantodea14** [invertase/react-native-firebase#1142]
### Issue

The production build is stuck in splash screen after I've updated Firebase to 4.1.0. I've follow the instructions regarding the installation of the library and all worked well when I tested the debug and release build locally, only after I've install the play store build I discover this issue. The application remains stuck in splash screen, until I clear local data manually. I managed to reproduce this issue on Samsung S7, S8 (os Version 7.0) and Google Pixel XL ( os version 8.1.0 )devices.  Any tips about how could I debug this problem?

### Environment

Android

1. Application Target Platform:

macOs High Sierra

2. Development Operating System:

Android Studio 3.0.1

3. Build Tools:

Project Gradle
    classpath 'com.android.tools.build:gradle:3.1.2'
    classpath 'com.google.gms:google-services:3.2.1'

App Gradle

    implementation 'com.google.android.gms:play-services-base:15.0.0'
    implementation 'com.google.firebase:firebase-core:15.0.2'
    implementation 'com.google.firebase:firebase-ads:15.0.0'
    implementation 'com.google.firebase:firebase-auth:15.1.0'
    implementation 'com.google.firebase:firebase-config:15.0.2'
    implementation 'com.google.firebase:firebase-crash:15.0.2'
    implementation 'com.google.firebase:firebase-messaging:15.0.2'
    implementation 'com.google.firebase:firebase-perf:15.1.0'
    implementation 'com.google.firebase:firebase-database:15.0.0'
    implementation 'com.google.firebase:firebase-storage:15.0.2'
    implementation 'com.google.firebase:firebase-firestore:16.0.0'

I've also generate different APK based on CPU Architecture

4. React Native version:

   0.55.4

5. Firebase Version:

   4.1.0

**Comment by chrisbianca** [comment]
According to: https://stackoverflow.com/questions/50222500/firebase-auth-getidtoken-gets-stuck-after-update there may have been an issue with auth in 15.1.0. Can I suggest giving 16.0.1 a try?
