### ISSUE TITLE
Remove all notification.

### ISSUE THREAD

**Issue by GarryChang** [invertase/react-native-firebase#1145]
Hi guys,
I am using React Native notification with react-native-firebase plugin. How can I remove all notification on notification bar? Please help me.

**Comment by Ehesp** [comment]
Have you tried https://rnfirebase.io/docs/v4.2.x/notifications/reference/Notifications#removeAllDeliveredNotifications

Let us know if you require other functionality and we'll re-open, thanks!

**Comment by GarryChang** [comment]
Thanks.
