### ISSUE TITLE
XCode build error after upgrading to v0.4.2

### ISSUE THREAD

**Issue by MIREX** [invertase/react-native-firebase#1150]
### Issue
After Upgrading to react-native-firebase v4.2.0 and upgrading pods to v5.*, XCode build started to fail with error.

![2018-05-28 15 41 42](https://user-images.githubusercontent.com/1025141/40611054-3ee6986c-628e-11e8-815a-149aad663581.png)

Pods used:
`pod 'Firebase/Core` (**without locking version**)
`pod 'Firebase/Messaging'`

Already tried to add this dependency. Same result
`pod 'Firebase'`

### Environment
1. Application Target Platform: **iOS**
2. Development Operating System: **macOS High Sierra 10.13.4**
3. Build Tools: **XCode 9.3**
4. React Native version: **0.55.3**
5. RNFirebase Version: **4.2.0**
6. Firebase Module:  ***probably FirebaseCore***

**Comment by somsin** [comment]
i am also facing same issue

**Comment by andrewkslv** [comment]
Do you have an idea which version should we use to get rid of crashes? I can't build ios project either. I wanted to add push notifications to my project with `react-native-firebase` and stacked for the last 3 days.

**Comment by somsin** [comment]
me also

**Comment by andrewkslv** [comment]
hey @somsin @MIREX I finally managed to run `react-native-firebase` library with exact your configuration.

**Comment by somsin** [comment]
can you post your configuration

**Comment by ThomasAbbink** [comment]
I had the same issue with slightly different Pods: 

`  pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'`

What finally resolved it for me was 
- removing the firebase pods from my Podfile
- `pod install` to uninstall them
- adding the pods back in
- `pod install` a second time 

My project started building again after that.

**Comment by andrewkslv** [comment]
@somsin I mean environment.
