### ISSUE TITLE
Uploading files

### ISSUE THREAD

**Issue by sinevitch** [invertase/react-native-firebase#1152]
Help me please. I'm trying to upload a file
the file looks like this (this.state.foto1):
![image](https://user-images.githubusercontent.com/35930695/40625961-3e0aeb52-62be-11e8-9f00-3e15a78c4bce.png)

The file is located in state (this.state.foto1)
Firebase fully connected

When you run this code, you receive an error
![image](https://user-images.githubusercontent.com/35930695/40625390-d89fd1a4-62ba-11e8-8bc4-00e8ea153427.png)

![image](https://user-images.githubusercontent.com/35930695/40625198-987fec68-62b9-11e8-9a17-783c1e75fb79.png)

Please tell me I'm doing the right thing?

### Environment

IOS

1. Application Target Platform:

macOS Sierra

2. Development Operating System:

Xcode 

3. Build Tools:

4. React Native version:

Version 9.3

5. RNFirebase Version:

"react-native-firebase": "^4.2.0"

6. Firebase Module:

pod 'Firebase/Core', '~> 5.0.1'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

**Comment by chrisbianca** [comment]
@sinevitch As per the error, you need to define the `successCb` function that is passed into the `.then` part of your promise.
