### ISSUE TITLE
No visible @interface for 'FIRQuery' declares the selector 'addSnapshotListenerWithIncludeMetadataChanges:listener

### ISSUE THREAD

**Issue by somsin** [invertase/react-native-firebase#1157]
app was working randomly this error is started coming

No visible @interface for 'FIRQuery' declares the selector 'addSnapshotListenerWithIncludeMetadataChanges:listener:'
<img width="743" alt="screen shot 2018-05-29 at 11 36 23 pm" src="https://user-images.githubusercontent.com/4973590/40676799-6fdc01ee-6399-11e8-81c7-e68e2fc2c9ae.png">

pod 'Firebase/Core','4.9.0'
  pod 'Firebase/Firestore','4.9.0'
  pod 'Firebase/Messaging','4.9.0'
  pod 'FirebaseAnalytics', '4.0.9'

**Comment by chrisbianca** [comment]
You need to update your Pods to v5, as per: https://github.com/invertase/react-native-firebase/issues/1110
