### ISSUE TITLE
RNFirebaseBackgroundNotificationAction is not work

### ISSUE THREAD

**Issue by dbyilmaz** [invertase/react-native-firebase#1159]
### Issue
App receive notification when app on background/ is dead. But not trigger headless task. By the way notification is schedule notification. I see notification tap on the phone. But headless task not trigger.

### Environment

1. Application Target Platform: **Android**

2. Development Operating System: **macOS Sierra**

3. Build Tools:

4. React Native version: **0.53.0**

5. RNFirebase Version: **4.2.0**

6. Firebase Module: **notification**

**AndroidManifest.xml**
```
        <receiver android:name="io.invertase.firebase.notifications.RNFirebaseNotificationReceiver"/>
        <receiver android:enabled="true" android:exported="true"  android:name="io.invertase.firebase.notifications.RNFirebaseNotificationsRebootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </receiver>

        <receiver android:name="io.invertase.firebase.notifications.RNFirebaseBackgroundNotificationActionReceiver" android:exported="true">
            <intent-filter>
                <action android:name="io.invertase.firebase.notifications.BackgroundAction"/>
            </intent-filter>
        </receiver>
        <service android:name="io.invertase.firebase.notifications.RNFirebaseBackgroundNotificationActionsService"/>
```
**HeadlessTask**

```
const NotificationMessage = async (data) => {
    console.log(data);
};

AppRegistry.registerHeadlessTask('RNFirebaseBackgroundNotificationAction',
() => NotificationMessage);

```

**Comment by chrisbianca** [comment]
@dbyilmaz what code are you using to schedule the notification?

**Comment by dbyilmaz** [comment]
@chrisbianca 
```
           const notificationStart = new firebase.notifications.Notification()
            .setNotificationId('startid')
            .setTitle('Title')
            .setBody('Body')
            .setData({
                type: 'start',
            }).android.setChannelId('testChannel');

            const fireDate = moment(`2018-05-30 15:00`).valueOf();

            firebase.notifications().scheduleNotification(notificationStart, {
                fireDate,
            });
```

**Comment by chrisbianca** [comment]
You need to follow all of the steps here to be able to accept actions in the background: https://rnfirebase.io/docs/v4.2.x/notifications/android-actions#Performing-the-action-in-the-background

You have to explicitly set the action to be a background action if you don't want it to wake the UI.

**Comment by dbyilmaz** [comment]
It works. @chrisbianca but I want to trigger automatically when receiving notification. is it possible?

**Comment by chrisbianca** [comment]
The only way would be to send a data only notification as covered here: https://rnfirebase.io/docs/v4.2.x/messaging/receiving-messages#4)-(Optional)(Android-only)-Listen-for-FCM-messages-in-the-background

**Comment by dbyilmaz** [comment]
@chrisbianca So, local notification is not triggered headless task automatically. am I right? I am using firebase messaging. But ı have to use local notification. Local notification must trigger headless task automatically.
