### ISSUE TITLE
Firebase Analytics NSURLConnection HTTP load failed -9802

### ISSUE THREAD

**Issue by ishigamii** [invertase/react-native-firebase#1162]
### Issue

I am currently experimenting an issue with the deployment of the ios app on a real device. When I am connected to my mac and use xcode or run-ios I can launch the app but on the splashScreen I get a really long lag and some log : 
```
[Firebase/Analytics][I-] Firebase Analytics v.50001000 started
2018-05-30 16:35:48.291187+0200 5.1.0 - [Firebase/Analytics][I-] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2018-05-30 16:35:59.165835+0200[:] TIC TCP Conn Failed [1:0x1d017f800]: 3:-9802 Err(-9802)
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
```

Considering this I thought that I didn't declare the good `NSAppTransportSecurity` exceptions. So 
I tried adding an exception for `firebaseio.com` but didn't seem to be the right url.
So I tried using : 
```
<key>NSAppTransportSecurity</key>
<dict>
   <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

But even with this I still get the same lag so my question is what should be done cause when I unplug my phone and try to restart it on a real device it crashes whereas on the simulator it works perfectly (Cause he doesn't check the http/https) or plugged it works with the lag but the app doesn't crash. Should we add an exception manually ? is that a real issue ? 

### Environment

1. Application Target Platform:

Xcode Version 9.4 (9F1027a), IOS 

2. Development Operating System:

MacOS High Sierra Version 10.13.4

3. Build Tools: ? 

4. React Native version:

    "react-native": "0.53.0",

5. RNFirebase Version:

    "react-native-firebase": "^4.2.0",

6. Firebase Module:

```
 # Pods for tooGoal
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
```

```
Using Firebase (5.1.0)
Using FirebaseAnalytics (5.0.1)
Using FirebaseAuth (5.0.0)
Using FirebaseCore (5.0.2)
Using FirebaseDatabase (5.0.1)
Using FirebaseInstanceID (3.0.0)
Using FirebaseStorage (3.0.0)
Using GTMOAuth2 (1.1.6)
Using GTMSessionFetcher (1.1.15)
Using GoogleSignIn (4.1.2)
Using GoogleToolboxForMac (2.1.4)
Using QBImagePickerController (3.4.0)
Using RNImageCropPicker (0.20.3)
Using RSKImageCropper (2.0.1)
Using React (0.53.0)
Using leveldb-library (1.20)
Using nanopb (0.3.8)
Using yoga (0.53.0.React)
```

Thanks a lot in advance.

**Comment by ishigamii** [comment]
Nothing here, was a bad conf of release for ios

**Comment by vongohren** [comment]
@ishigamii what was your bad conf? Cause im experiencing this now and struggle to get past it?

**Comment by ishigamii** [comment]
@vongohren sadly I don't sorry :s
