### ISSUE TITLE
Delivered Notifications are getting dismissed on app update

### ISSUE THREAD

**Issue by pranjal-jain** [invertase/react-native-firebase#1163]
### Issue
Delivered Notifications are getting dismissed on app update.

### Reproduction Steps
1. Create and show a test notification.
2. Simulate App Update using `adb install -r myApplication.apk`

Test notification created will disappear

### Environment

1. Application Target Platform: Android

2. Development Operating System: macOS High Sierra

3. React Native version: 0.55.3

4. RNFirebase Version: 4.2.0

5. Firebase Module: notifications

**Comment by chrisbianca** [comment]
@pranjal-jain Unfortunately, this is something we have no control over as it seems to be operating system behaviour.  If you're aware of a way of fixing this, then please let us know.
