### ISSUE TITLE
Failed to find byte code for com/google/android/gms/ads/VideoController$VideoLifecycleCallbacks

### ISSUE THREAD

**Issue by courptwayne** [invertase/react-native-firebase#1165]
### Environment

1. Application Target Platform:

2. Development Operating System:

3. Build Tools:

4. React Native version:

5. RNFirebase Version:

6. Firebase Module:

**Comment by chrisbianca** [comment]
This is an issue with the gradle plugin. You'll need to disable Instant Run from within Android Studio.
