### ISSUE TITLE
There seem to be no TypeScript type definition for firebase.config()

### ISSUE THREAD

**Issue by Spetastian** [invertase/react-native-firebase#1170]
### Issue

There seem to be no type def for firebase.config().

The following gives me "[ts] Property 'config' does not exist on type 'Firebase'":

```
import firebase from 'react-native-firebase';

if (__DEV__) {
  firebase.config().enableDeveloperMode();
}

// Set default values
firebase.config().setDefaults({
  hasExperimentalFeature: false,
});
```

I looked in the source code and it seems that the definition exists but its commented out: https://github.com/invertase/react-native-firebase/blob/master/lib/index.d.ts#L28

Why is that?

### Environment

RNFirebase Version: 4.2.0

Firebase Module: Remote Config.

**Comment by chrisbianca** [comment]
The typings weren't accurate, so we opted to disable them rather than have incorrect typings as part of the library.  None of us use Typescript personally, so would be grateful to anybody who's willing to submit a PR for the typings.

**Comment by chrisbianca** [comment]
Closed by: https://github.com/invertase/react-native-firebase/pull/1226
Thanks @Ken-Lim !

**Comment by asadalibest1** [comment]
## Use TypeScript for Cloud Functions
For developers who prefer to write functions in TypeScript, Cloud Functions provides two types of support:

Create and configure TypeScript projects for automatic transpilation at initialization (firebase init functions).
Transpile existing TypeScript source to JavaScript at deploy time via a predeploy hook.

see more details:
https://firebase.google.com/docs/functions/typescript
