### ISSUE TITLE
Captcha on iOS phone auth signup

### ISSUE THREAD

**Issue by joecaraccio** [invertase/react-native-firebase#1171]
Hi Everyone,

I s there a solution to turning off the phone auth captcha that pops up when trying to sign on for iOS. I spent a long time looking, but can't find the way to turn off the captcha system

**Comment by chrisbianca** [comment]
Hi @joecaraccio, take a look at: https://firebase.google.com/docs/auth/ios/phone-auth#enable-app-verification

reCAPTCHA is used automatically if silent push notifications aren't enabled or aren't possible on a particular device, e.g. a simulator.

**Comment by kevboh** [comment]
For people who are still seeing the captcha after turning on Push Notifications, I also had to turn on the "Remote notifications" Background Mode—you can do so in the Capabilities pane in Xcode.

**Comment by samitha9125** [comment]
> For people who are still seeing the captcha after turning on Push Notifications, I also had to turn on the "Remote notifications" Background Mode—you can do so in the Capabilities pane in Xcode.

This should be added to the documentation as well. Most people get confused about why they are not receiving silent push notifications even after enabling APSs for their project. This is the second necessary step to receive Silent Push Notification.

**Comment by Shilpa26v** [comment]
@kevboh @joecaraccio 
i have enable push notification and background mode --remote notification
added apns certificate in play console too
still captcha not getting disable can anybody let me know what is missing

**Comment by heardthisdev** [comment]
@Shilpa26v Did you ever find a solution? I'm having the same issue
