### ISSUE TITLE
How to dismiss Notification when receiving Firebase Cloud Messages

### ISSUE THREAD

**Issue by hoanghapo** [invertase/react-native-firebase#1172]
How to dismiss Notification when receiving Firebase Cloud Messages?

This code not working 
```
// Optional: Flow type
import type { RemoteMessage } from 'react-native-firebase';

componentDidMount() {
    this.messageListener = firebase.messaging().onMessage((message: RemoteMessage) => {
        // Process your message as required
        return false;
    });
}

componentWillUnmount() {
    this.messageListener();
}
```

**Comment by Ehesp** [comment]
Please follow the issue template with your versions so we can help. I'll reopen once it's been edited.

You should also check out https://rnfirebase.io/docs/v4.2.x/messaging/introduction as you'll probably find what you're looking for there :)
