### ISSUE TITLE
missing function android.setVisibility

### ISSUE THREAD

**Issue by NicolasHanzel** [invertase/react-native-firebase#1175]
### Issue

android.setVisibility is not a function, the function didn't appear in AndroidNotification.js
Could you add these lines ? 

```

  setVisibility(visibility: string): Notification {
    this._visibility = visibility;
    return this._notification;
  }


```

Thanks,

### Environment

1. Application Target Platform: Android

2. Development Operating System: Windows 10

3. Build Tools: -

4. React Native version: -

5. RNFirebase Version: - 

6. Firebase Module: Notifications

**Comment by chrisbianca** [comment]
This has been fixed by @aMarCruz as part of #1219
