### ISSUE TITLE
DocumentChange.type should have a more specific type

### ISSUE THREAD

**Issue by sargunv** [invertase/react-native-firebase#1180]
### Issue

In the TypeScript definitions, `DocumentChange.type` is currently type `string`. It should be type `"added" | "modified" | "removed"`, according to Firebase docs: https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentChange.

### Environment

1. Application Target Platform: N/A

2. Development Operating System: N/A

3. Build Tools: N/A

4. React Native version: N/A

5. RNFirebase Version: 4.2.0

6. Firebase Module: Firestore

**Comment by chrisbianca** [comment]
Thanks for flagging, this will be resolved in the next release
