### ISSUE TITLE
Admob occasionally displays full-screen video on Banner ad units (with videos disabled)

### ISSUE THREAD

**Issue by wbattel4607** [invertase/react-native-firebase#1182]
### Issue

We use several banner ad units in our app, and every once in a while a full-screen video will appear and consume the entire screen for several seconds. We've disabled video content in the Admob dashboard but it still happens.

I don't know if this is an issue with Admob or this library, but I've also posted it on the Google forum [here](https://productforums.google.com/forum/#!topic/google-admob-help-forum/2mHihTAi0Tw;context-place=forum/google-admob-help-forum).

Any ideas?

### Environment

1. Application Target Platform: iOS (not tested on Android)

2. Development Operating System: macOS High Sierra

3. Build Tools: Xcode 9.3, iOS 11

4. React Native version: 0.55.4

5. RNFirebase Version: 4.2.0

6. Firebase Module: Admob (Firebase 5.1.0, Google-Mobile-Ads-SDK 7.31.0)

**Comment by wasedaigo** [comment]
I am having the same issue, I think. The admob banner container is scrollable too.

![image from ios 1](https://user-images.githubusercontent.com/182612/41813615-20e7bd72-76ee-11e8-960d-bae194865fd2.png)

@wbattel4607 Is it looking like this?

**Comment by wasedaigo** [comment]
I have a similar issue on iPhoneX

1. Clicking on the play button does not do anything
2. The admob banner container is scrollable
3. double tapping it shows Copy|SelectAll menu

<img width="367" alt="screen shot 2018-06-23 at 2 03 54 pm" src="https://user-images.githubusercontent.com/182612/41813627-690845cc-76ee-11e8-9740-fe387d92bc4b.png">

**Comment by Salakar** [comment]
Thanks for reporting this issue. We're aware that AdMob has fallen behind on React Native Firebase and would like to bring it up to speed again. I will close this issue for now and track it as well as other issues collectively over on the `AdMob overhaul proposal` to be addressed in a future release. See #1259
