### ISSUE TITLE
database ref set always fails with "No properties to serialize found on class com.facebook.react.bridge.ReadableNativeMap"

### ISSUE THREAD

**Issue by esprehn** [invertase/react-native-firebase#1184]
### Issue

All calls to database.ref('foo').set('bar') fail with "No properties to serialize found on class com.facebook.react.bridge.ReadableNativeMap".

.update() calls work fine, so this seems to be an issue with the .set() code path.

### Environment

1. Application Target Platform: Android.

2. Development Operating System: OS X 10.13.4

3. Build Tools: 27.0.3

4. React Native version: 0.54.3

5. RNFirebase Version: 4.2.0

6. Firebase Module: Database

**Comment by esprehn** [comment]
Looks like this is an issue with React Native 0.54.3, upgrading to 0.54.4 fixes it.

https://github.com/facebook/react-native/commit/15fa2250fdd0865ce1d0c6ac13b817e7b2c7757a#diff-db05809c8152c5b123b6c08cb00a4c17

**Comment by chrisbianca** [comment]
Thanks for identifying this - there were a couple of other issues that had flagged similar.
