### ISSUE TITLE
getToken does not return

### ISSUE THREAD

**Issue by haseebnaseem** [invertase/react-native-firebase#1192]
### Issue

`firebase.messaging().getToken` never returns. This is how i am calling it I added a setTimeout incase the token was not available right away

```
firebase.messaging().hasPermission().then(enabled=>{
        if(enabled){
            console.log('enabled');
            setTimeout(()=>{
                firebase.messaging().getToken(token=>{
                    if(token)
                        console.log('token',token);
                    else
                        console.log('no token yet');
                })
            },60000);
        }else{
            firebase.messaging().requestPermission().then(()=>{
                console.log('got permission');
            }).catch(err=>{
                console.log('did not get persmisis');
            });
        }
    });

```
However I see the token in android logs using `adb logcat`:
```
06-08 18:19:20.933  9073  9250 D RNFirebaseMessaging: Firebase token: eR-BHM7-SS0:APA91bESl4rYYglx5tTzDN8dkTWqZQozCSbJGWmXmGAxPla13KlJV9QM6fADaOGyt-NmoApjy0ToRwmo33P0S7RtNu_Z7R6QvHTMjPKgL6MBqmFmSZ6eZ8mjxhCjOQKTG4MNyu3teT3l
```
### Environment

1. Application Target Platform:android

2. Development Operating System:Ubuntu (16.04)

3. Build Tools:

4. React Native version:0.48

5. RNFirebase Version:4.2.3

6. Firebase Module:messaging

**Comment by flasd** [comment]
As the [docs](https://rnfirebase.io/docs/v4.2.x/messaging/reference/Messaging#getToken) say `getToken() returns Promise containing String;` Try:

```javascript
import firebase from 'react-native-firebase';

const messaging = firebase.messaging();

messaging.hasPermission()
    then((enabled) => {
        if (enabled) {
            messaging.getToken()
                .then(token => { /* do stuff */ })
                .catch(error => { /* handle error */ });
        } else {
            messaging.requestPermission()
                .then(() => { /* got permission */ })
                .catch(error => { /* handle error */ });
        }
    })
    .catch(error => { /* handle error */ });
```

Hope it solves it.

**Comment by chrisbianca** [comment]
@husscode is correct. You need to be awaiting a promise to be returned by `getToken`

**Comment by poziminski** [comment]
For me, the clue was to run client and api on HTTPS with self-generated localhost SSL certificate. Then, my `getToken()` started resolving.

**Comment by mgwedd** [comment]
I'm seeing a similar issue with `react-native-firebase/messaging:@6.3.4`. I am awaiting the Promise as the docs suggest, but it never resolves. In the code below, the second log never occurs: 

```
import FBMessaging from '@react-native-firebase/messaging'
// ...
console.log( 'pre getToken' )
const fcmToken = await FBMessaging.getToken()
console.log( 'post getToken', fcmToken ) 
```

**Comment by angelos3lex** [comment]
I face same issue. I do have permissions enabled, but getToken never resolves, in ios simulator. I use `react-native-firebase: 5.5.6`

**Comment by mikehardy** [comment]
I don't believe testing anything about FCM in a simulator is useful. Use a real device

**Comment by angelos3lex** [comment]
I found the solution to this: 
The problem was that i was using older version of the following pods:

  - 'Firebase/Core', I had 6.9.0 instead of 6.13.0
  - 'Firebase/Messaging', I had 6.9.0 instead of  6.13.0
  - 'GoogleAppMeasurement', I had 6.1.2 instead of  6.1.6

**Comment by mikehardy** [comment]
6.27.0 is out and works fine, react-native-firebase test project is already updated with them #3815 - I'd get current, 6.13.0 is pretty old at this point even.

**Comment by shoaib2527** [comment]
@mikehardy Facing it now in 2023. 
None of the Promises from `messaging()` are returning. App is stuck on latest messaging versions. Here is my package.json file
`

    "@react-native-firebase/analytics": "^17.2.0",
    "@react-native-firebase/app": "^17.2.0",
    "@react-native-firebase/crashlytics": "^17.2.0",
    "@react-native-firebase/dynamic-links": "^17.3.0",
    "@react-native-firebase/messaging": "^17.3.1",
    "@react-native-firebase/remote-config": "^17.3.0",`
    
Note: **JUST ANDROID** My app isn't build for IOS, so i'm not testing on IOS.

**Comment by shoaib2527** [comment]
Right, I think so too. I tried different versions but still same. 
So it doesn't looks an issue with library.

**Comment by mikehardy** [comment]
@shoaib2527 in addition, your version numbers are an unsupported mix, they should all be the same for react-native-firebase --> https://invertase.io/blog/react-native-firebase-versioning
