### ISSUE TITLE
firebase.database().ServerValue vs firebase.database.ServerValue

### ISSUE THREAD

**Issue by smkhalsa** [invertase/react-native-firebase#12]
Based on the firebase JS [implementation](https://firebase.google.com/docs/reference/js/firebase.database.ServerValue#.TIMESTAMP), we should be able to access ServerValue from firebase.database, not firebase.database().

**Comment by Ehesp** [comment]
Good spot, will be sorted tomorrow :)

**Comment by Salakar** [comment]
Note to self: `firebase.storage.TaskEvent.STATE_CHANGED` also needs doing
