### ISSUE TITLE
Inconsistent paths with/out trailing slashes in firebase.storage.Native

### ISSUE THREAD

**Issue by Haraldson** [invertase/react-native-firebase#1200]
### Issue

The paths in `firebase.storage.Native` are inconsistent – it would be nice if they were all either with or without trailing slashes, in order to simplify building file paths to local resources.

`firebase.storage.Native.TEMP_DIRECTORY_PATH` *has* a trailing slash.
`firebase.storage.Native.DOCUMENT_DIRECTORY_PATH` *does not have* a trailing slash.

---

In addition to these things, `TEMP_DIRECTORY_PATH` is listed as `TEMPORARY_DIRECTORY_PATH`, but isn’t available as a property in `firebase.storage.Native`.

### Environment

1. Application Target Platform: iOS
2. Development Operating System: macOS High Sierra
3. Build Tools: Xcode 9.3
4. React Native version: 0.55.3
5. RNFirebase Version: 4.2.0
6. Firebase Module: Storage

**Comment by Salakar** [comment]
Thanks for reporting this issue. 

We're aware that Storage has fallen behind slightly on React Native Firebase and would like to bring it up to speed again. I will close this issue for now and track it as well as other issues collectively over on the Storage improvements proposal to be addressed in a future release. See #1260

**Comment by Salakar** [comment]
@Haraldson thanks for reporting this.

Have just fixed this pending v4.3.0 release. For consistency all paths have been changed to be without a trailing slash as this was the least breaking change. Additionally `TEMP_DIRECTORY_PATH` was missing on android and has been added, was already there on iOS.

**Comment by Salakar** [comment]
@Haraldson thanks again for reporting this, fix is now live in the [v4.3.0 release](https://github.com/invertase/react-native-firebase/releases/tag/v4.3.0).

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
