### ISSUE TITLE
Class Not Found: io.invertase.firebase.messaging.RNFirebaseSystemBootEventReceiver

### ISSUE THREAD

**Issue by leifdroms** [invertase/react-native-firebase#1201]
### Environment : Android

1. Application Target Platform: Android Mobile Devices (Various Android Versions)

2. Development Operating System: Android Studio 3.1.2

3. Build Tools: (Android) 27.0.3

4. React Native version: 55.4

5. RNFirebase Version: 4.2.0

6. Firebase Module: firebase-messaging:15.0.2

I'm getting crash reports on Android from various versions that the app is crashing due to the class "io.invertase.firebase.messaging.RNFirebaseSystemBootEventReceiver" not being found on path "DexPathList[[zip file "/data/app/". The exception being thrown is, "Unable to instantiate receiver io.invertase.firebase.messaging.RNFirebaseSystemBootEventReceiver"

The issue seems to pop up when the device reboots. So far iOS is not affected.

**Comment by chrisbianca** [comment]
@leifdroms This class was changed as part of the upgrade from v3 to v4. It's now: `io.invertase.firebase.notifications.RNFirebaseNotificationsRebootReceiver` as per: https://rnfirebase.io/docs/v4.2.x/notifications/android#Scheduled-Notifications-(Optional)
