### ISSUE TITLE
Failed to resolve: firebase-messaging

### ISSUE THREAD

**Issue by sinevitch** [invertase/react-native-firebase#1204]
1) I've done react-native link react-native-firebase
2) I've done "place this file in the root of your project"(google-services.json)

3)
![image](https://user-images.githubusercontent.com/35930695/41291399-3afb03d4-6e58-11e8-83dc-ffeec825d880.png)

4)
![image](https://user-images.githubusercontent.com/35930695/41291424-54dca19a-6e58-11e8-9dd1-bf754140b7a0.png)

5)
![image](https://user-images.githubusercontent.com/35930695/41291491-8017a576-6e58-11e8-80a0-56702883625c.png)

6)Entire file  app/build.gradle
![image](https://user-images.githubusercontent.com/35930695/41291602-cad079ee-6e58-11e8-94bc-79aee621b547.png)

When I compile a project, I get 2 errors:
![image](https://user-images.githubusercontent.com/35930695/41302086-44349392-6e72-11e8-93ae-6f9fdc947041.png)

### Environment

Android

1. Application Target Platform:

macOS Sierra

2. Development Operating System:

Android Studio version
![image](https://user-images.githubusercontent.com/35930695/41292491-6a536b50-6e5b-11e8-8f62-94c93c58c78c.png)

3. Build Tools:
![image](https://user-images.githubusercontent.com/35930695/41292714-02a1c190-6e5c-11e8-887f-19d1bf713a38.png)

![image](https://user-images.githubusercontent.com/35930695/41293593-635f60c6-6e5e-11e8-8119-8c8ad4eae1ab.png)

4. React Native version:

"react-native": "0.55.4"

5. RNFirebase Version:

"react-native-firebase": "^4.2.0"

**Comment by ifanfaizal** [comment]
@sinevitch hey, did you manage to fix it? I got the same problems :'(

**Comment by ifanfaizal** [comment]
@sinevitch I found the solution! You just need to move up the google() in allprojects repositories to the top (above mavenLocal())..

**Comment by chrisbianca** [comment]
I have updated the documentation to reflect this: https://github.com/invertase/react-native-firebase-docs/commit/1ead30f51292165d864416935ae9b452803a621e
