### ISSUE TITLE
Multiple Flow errors resulting from possibility of null object IDs

### ISSUE THREAD

**Issue by benknight** [invertase/react-native-firebase#1205]
I just upgraded to a version of this library that has Flow types, and now Flow is reporting errors just about anywhere I reference the "id", for example of in [DocumentSnapshot](https://github.com/invertase/react-native-firebase/blob/c14e60017ede6d6689afea582263bcd3c9509775/lib/modules/firestore/DocumentSnapshot.js#L46), [Path](https://github.com/invertase/react-native-firebase/blob/d0b6972e395f5e7f9cd59e961689b4b3a22e3c7e/lib/modules/firestore/Path.js#L16), [CollectionReference](https://github.com/invertase/react-native-firebase/blob/25506479d3295a452db9a2be13d69af8be401a9d/lib/modules/firestore/CollectionReference.js#L34), and [DocumentReference](https://github.com/invertase/react-native-firebase/blob/25506479d3295a452db9a2be13d69af8be401a9d/lib/modules/firestore/DocumentReference.js#L46).

Solving these errors requires adding existence checks everywhere in my application that accesses an `id` property, which seems unnecessary and cumbersome.  Are there really common/valid cases where an objects `id` would be null?  Basically I'm not seeing a need for the `| null` part of the type definition.

**Comment by Ehesp** [comment]
Thanks for flagging - I'll look into this one, from a quick look I think you may be correct but will let you know for sure.

**Comment by Salakar** [comment]
@benknight thanks for the report, have swapped these to be string only as you're right. Will land in v5.2.0. Sorry for the delay.
