### ISSUE TITLE
Firestore get() Crash my Android app

### ISSUE THREAD

**Issue by KchTT** [invertase/react-native-firebase#1208]
Hi...
Im using firestore en my app and crash when invoque get() function.

com.google.firebase:firebase-firestore:16.0.0

java.lang.NoSuchMethodError
FirestoreSerialize.java
java.lang.NoSuchMethodError: No virtual method getDocument()Lcom/google/firebase/firestore/DocumentSnapshot; in class Lcom/google/firebase/firestore/DocumentChange; or its super classes (declaration of 'com.google.firebase.firestore.DocumentChange' appears in /data/app/com.airnizerappnative-2/base.apk:classes3.dex) at io.invertase.firebase.firestore.FirestoreSerialize.documentChangeToWritableMap(FirestoreSerialize.java:129)

**Comment by chrisbianca** [comment]
Without knowing what version of react-native-firebase you're using it's hard to help you.  Please fill out the issue template properly and re-open.
