### ISSUE TITLE
After setting up with iOS Getting RNFirebaseStarter has not been registered.

### ISSUE THREAD

**Issue by shubhanus** [invertase/react-native-firebase#1209]
### Issue

i did setup using cocoa pods and app is building successfully then i am getting red screen just after loading packager files RNFirebaseStarter has not been registered.

### Environment

IOS

1. Application Target Platform:

macOS Sierra

2. Development Operating System:

iOS

3. Build Tools:

""

4. React Native version:

"react-native": "0.55.3",

5. RNFirebase Version:

"react-native-firebase": "4.2.0",

6. Firebase Module:

'Firebase/Core'
'Firebase/Database'
'Firebase/Messaging'

AppDeligate.m file
#import <Firebase.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  NSURL *jsCodeLocation;
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"RNFirebaseStarter"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

before app was crashing with  [FIRApp configure]; then when i dropped GoogleService-Info.plist in Resources group then it stopped crashing but i am getting this now.

![simulator screen shot - iphone 6 - 2018-06-13 at 18 13 03](https://user-images.githubusercontent.com/17209817/41351913-78673412-6f35-11e8-8e7b-b1a6f9c364e6.png)

**Comment by chrisbianca** [comment]
As per the error, it looks like you're either running the packager from another project, or have renamed the project since starting the packager.
