### ISSUE TITLE
Android Release Variant - undefined is not an object (evaluating 's.crash')

### ISSUE THREAD

**Issue by wbattel4607** [invertase/react-native-firebase#1210]
### Issue
**This issue only appears when setting `variant` to `release`**, when the app launches I am getting these crashing errors:
```
E/ReactNativeJS: undefined is not an object (evaluating 's.crash')
E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
E/ReactNativeJS: Module JSTimers is not a registered callable module (calling callTimers)
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
```

I found the relevant line in my android bundle, which is tied to SMXCrashlytics. I looked it up and found [a similar issue](https://github.com/corymsmith/react-native-fabric/issues/87) on the `react-native-fabric` repository- except for them it was also happening on debug builds. We used to use that repository but have since replaced it with this repository. The "solution" on that issue was to go back and install the SDK correctly, as it had not been originally. I've confirmed that our installation accurately following your guide [here](https://rnfirebase.io/docs/v4.2.x/crashlytics/android). Now I'm fumbling in the dark with no real idea of how to fix this or where the problem is. If you have any insight and/or suggestions, I'd appreciate hearing them. Thanks.

### Environment

1. Application Target Platform: Android (variant=release)

2. Development Operating System: maxOS High Sierra

3. Build Tools: Android Studio 3.1.3, All Android API Levels

4. React Native version: 0.55.4

5. RNFirebase Version: 4.2.0

6. Firebase Module: Crashlytics

**Comment by Ehesp** [comment]
Hi @wbattel4607 this one will be tricky for us to debug without a replicated repo for us to work on. Are you able to create a barebones repository which triggers this issue and we can see if its directly related to this library or not?

Thanks

**Comment by wbattel4607** [comment]
@Ehesp I recreated my RN project from scratch and now the problem is gone. I still don't know what the problem was but I'm past it now.
