### ISSUE TITLE
does firestore offline feature allow customised handling when sychronizing? (doc)

### ISSUE THREAD

**Issue by callagga** [invertase/react-native-firebase#1211]
Does react-native-firebase's firestore offline feature support customising the sychronisation approach when a device connects back on line?   (e.g. if you did not want an offline change made 5 days ago and just came back offline, to overwrite a change that was made by another user 1 day ago)

Does this library only provide the same functionality in the Google Firestore web javascript SDK/API in which case I could follow up in more detail in this Google documentation?  

(If you happen to be able to give me a quick pointer if you know re meeting this requirement that would be greatly appreciated - e.g. to have control of how the sync process works currently do you really need to roll-your-own approach using redux-persist/redux-offline)

**Comment by chrisbianca** [comment]
I'm afraid we simply wrap the functionality of the native SDKs and as far as I'm aware there isn't any way of customising how the synchronisation will work.  I'd suggest having a read through the native iOS and Android SDK documentation - if you happen to find anything that suggests customisation is possible then please point us at the docs and we'll get this added.
