### ISSUE TITLE
Google sign in Cannot read proprety 'configure' of undefined

### ISSUE THREAD

**Issue by salution** [invertase/react-native-firebase#1212]
### Issue

I set up following the documentation in google sign-in but it have error Cannot read proprety 'configure' of undefined

### Environment

iOS
1. Application Target Platform:

MacOS High Sierra

2. Development Operating System:

iOS

3. Build Tools:

4. React Native version:

react-native 0.55.4

5. RNFirebase Version:

"react-native-firebase": "^4.2.0",

6. Firebase Module:
 'Firebase/Core'
 'Firebase/Auth'
 'GoogleSignIn'

in this code

await GoogleSignin.configure({
        iosClientId: 'my_client_id.apps.googleusercontent.com'
      })

**Comment by chrisbianca** [comment]
This implies that you haven't imported `GoogleSignIn` from `react-native-google-signin`

**Comment by Mogust** [comment]
i have a same problem here, i import the GoogleSignIn from react-native-google-signin and still got error "Cannot read configure property"
