### ISSUE TITLE
onUserChanged triggers multiple times on HighOrder Component

### ISSUE THREAD

**Issue by paolospag** [invertase/react-native-firebase#1217]
Hi,
for my application, I created a High-Order Component (called withAuthentication) through which the app observes changes to the user's sign-in/sign-out state.

Initially I used the "onAuthStateChanged" method to achieve this and it works fine: in console.log, the auth state changes trigger once.

However, for my purpose, I also needed to observe profile/user updates and I noticed the existence of this your own method "onUserChanged".

I changed the method in my High-Order component, but when the auth state changes, in console.log this triggers multiple times (twice or three times), e.g. when I sign-out app. Why is this happening?
I fear that this will initialize all the subordinate functions several times, as well as causes memory leaks.

This is part of my code:
```
...
    componentDidMount = () => {
      this.unsubscribe = firebase.auth().onUserChanged(this.onUserChanged);
    }
    componentWillUnmount = () => {
      if (this.unsubscribe) this.unsubscribe();
    }
    onUserChanged = (auth) => {
      if (auth) {
        console.log(auth)
        this._getAsyncCurrentUser(auth._user.uid);
      } else {
        console.log("sign out");
        this._removeAsyncCurrentUser();
      }
    }
...
```

Is there a way to solve this problem?

I'm using React Native 0.55.4 and React Native Firebase 3.3.1

### Environment

1. Application Target Platform:
Both Android and iOS

2. Development Operating System:
Windows 10

3. Build Tools:

4. React Native version:
0.55.4

5. RNFirebase Version:
3.3.1

6. Firebase Module:
auth()

**Comment by chrisbianca** [comment]
Unfortunately, due to the way this has been implemented it is occasionally possible that a single action can cause the `onUserChanged` method to trigger more than once.

This is because we are tying into a number of underlying actions which may be triggered.  However, be assured that this will always send the exact same `User` object, so there is no risk of memory leaks.
