### ISSUE TITLE
onAdLoaded event is not correctly fired when has multiple banners

### ISSUE THREAD

**Issue by ensecoz** [invertase/react-native-firebase#1218]
### Issue

Event onAdLoaded() is not correctly fired for multiple Banners.

```

class App extends React.Component<any, any> {
  render() {
    <BannerItem id={1} />
    <BannerItem id={2} />
    <BannerItem id={3} />
    <BannerItem id={4} />
  }
}

class BannerItem extends React.Component<any, any> {
  constructor(props) {
    super(props);
    this.state = {
      loaded: false
    };
  }

  handleAdLoaded = () => {
    console.log("loaded()" + this.props.id);
    this.setState({
      loaded: true
    });
  };

  render() {
    console.log("render()" + this.props.id);
    return (
        <Banner
          size="LARGE_BANNER"
          unitId="xxxx"
          onAdLoaded={this.handleAdLoaded}
        />
    );
  }
}
```

and the log look like this:

```
render()1
render()2
render()3
render()4
loaded()4
render()4
loaded()4 <-- duplicated
render()4
```

Also there is no loaded() log message for id 1, 2, 3

### Environment

1. Application Target Platform: Android

2. Development Operating System: Windows 10

3. Build Tools: Android SDK

4. React Native version: 0.55.4

5. RNFirebase Version:  4.2

6. Firebase Module: admob

**Comment by Salakar** [comment]
Thanks for reporting this issue. We're aware that AdMob has fallen behind on React Native Firebase and would like to bring it up to speed again. I will close this issue for now and track it as well as other issues collectively over on the `AdMob overhaul proposal` to be addressed in a future release. See #1259
