### ISSUE TITLE
Could not collect default user properties on iOS for Firebase Analytics

### ISSUE THREAD

**Issue by neko-neko** [invertase/react-native-firebase#1224]
### Issue

Could not collect default user properties on iOS for Firebase Analytics.
(e.g. Age/Gender) 
Default user properties: https://support.google.com/firebase/answer/6317486?hl=en

### Environment

iOS

1. Application Target Platform: iOS
2. Development Operating System: Xcode
3. Build Tools: 9.0
4. React Native version: 0.55.4
5. RNFirebase Version: 4.10
6. Firebase Module:

```
pod 'Firebase/Core', '~> 4.13.0'
pod 'Firebase/Auth', '~> 4.13.0'
pod 'Firebase/Firestore', '~> 4.13.0'
pod 'Firebase/RemoteConfig', '~> 4.13.0'
pod 'Firebase/Storage', '~> 4.13.0'
pod 'Firebase/Performance', '~> 4.13.0'
pod 'Firebase/Messaging', '~> 4.13.0'
pod 'Fabric'
pod 'Crashlytics'
```

**Comment by chrisbianca** [comment]
I'm afraid this is nothing to do with React Native Firebase as it's handled by the native SDK itself.

Do note that, as per the last section of the link you sent through, this sort of user property is unavailable until you have a sufficient level of traffic going through your app.
