### ISSUE TITLE
Problem compiling version 4.2.0 with fastlane

### ISSUE THREAD

**Issue by jadsonor** [invertase/react-native-firebase#1227]
I'm having problems when compiling a project with fastlane, getting the following: In file included from /Users/XXXX/XXXX/XXX/XXX/node_modules/react- 
native-firebase/ios/RNFirebase/RNFirebaseUtil.h:6:
../../../ios/Pods/Headers/Public/Firebase/Firebase.h:1:9: fatal error: 
'FirebaseCore/FirebaseCore.h' file not found
#import <FirebaseCore/FirebaseCore.h>
1 error generated.

**Comment by jadsonor** [comment]
Are you using CocoaPods ?

**Comment by rikur** [comment]
I pull in Firebase deps with cocoapods, but I've linked react-native-firebase manually -- similar to your case it seems.

I usually am able to fix build errors like this by nuking the Pods folder, running pod install again and getting rid of any RN caches.
