### ISSUE TITLE
FCM  Event instances are not clearing while removing the component from react-native-router-flux Actions route stack

### ISSUE THREAD

**Issue by prasanthyejje** [invertase/react-native-firebase#1229]
I am Using   **FCM.getInitialNotification().then((notif) => this.getInitialNotificationFunction(notif));
        this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => function(Notif)**
Both FCM Methods are executing multiple time.

**_Issue Explanation :_**  I Closed My App By Clicking Device Hardware Back Button and Again I opened  App By Clicking On The App Logo From Home Screen Of Device. here if I am Getting A FCM Notification Both Methods( FCM Method Mentioned Above) Are Executing Multiple TImes. If I close The App 3 Times Then FCM methods Are Executing 3 Times, If I Do This Process 4 times Then Methos Executes 4 Times. 

And I Am Using **react-native-router-flux** For Navigation. When User Clicks Hardware Back Button I am Removing The All App Components(Screens) From react-native-router-flux Actions Stack(It Means When User Open The App, App Starts From The Splash Screen Component.) 
@evollu @mlc  Help Me On This.

### Environment
1. Application Target Platform:
**Android OS**

2. Development Operating System:
**React-Native With Redux**

4. React Native version:
**react-native-cli: 2.0.1
react-native: 0.50.3**

5. RNFirebase Version:
**"react-native-fcm": "^11.2.0",**

**Comment by chrisbianca** [comment]
This question relates to `react-native-fcm` which we do not support.  It's suggested that you migrate to the react-native-firebase messaging and notification functionality going forwards.
