### ISSUE TITLE
fb.getToken().then((token) =>  returns null for token in android 4.4.4 or 4.4.2 ,

### ISSUE THREAD

**Issue by a11231g** [invertase/react-native-firebase#1231]
in android device version 4.4.4 or 4.4.2  i cant get token , and it returns null ,although i updated play service to the latest version for this device 
"react-native verison" : 55.3
"react-native-firebase": "3.2.0",
what should i do ?

**Comment by Ehesp** [comment]
Can we see your code usage please?

**Comment by Ehesp** [comment]
If you're still having issues please respond with some code usage and we'll pick this back up. Cheers.

**Comment by soloist624** [comment]
I have the same issue, even on later versions of android

I call this function in App.js
It works great on debug mode but after I install a release build of my app, returned value for token is null

```
firebase
			.messaging()
			.getToken()
			.then(async(fcmToken) => {
				if (fcmToken) {
					
					console.log('FCM---gettoken(App)',fcmToken)
						  }
				  } else {
					// user doesn't have a device token yet
					console.log('FCM -- user doesn not have a device token yet (App.js)')
```
