### ISSUE TITLE
Not receiving fcm data-only message when app is closed

### ISSUE THREAD

**Issue by Ketn** [invertase/react-native-firebase#1238]
### Issue
I followed the steps mentioned [here](https://rnfirebase.io/docs/v4.2.x/messaging/receiving-messages).

Now, I'm receiving messages when app is in foreground via `firebase.messaging().onMessage` and in the background via a headless task I defined according to the same guide, but I don't receive messages when the app is closed, however I get this warning in my `android logcat`:

`W GCM     : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000 pkg=com.mycustomapp (has extras) }`

This is my` bgMessaging.js`
```
import firebase from 'react-native-firebase';
import type { RemoteMessage } from 'react-native-firebase';

export default async (message: RemoteMessage) => {
    console.log("RemoteMessage", message);

    const newNotification = new firebase.notifications.Notification()
        .android.setSmallIcon(message.data.icon)
        .android.setChannelId(message.data.channel_id)
        .setNotificationId(message.messageId)
        .setTitle(message.data.title)
        .setBody(message.data.body)
        .setData({
            key1: 'value1',
            key2: 'value2',
        });
    firebase.notifications().displayNotification(newNotification);

    return Promise.resolve();
}
```

I've registered it as a headless task in my `index.js` as follows:

```
import { AppRegistry } from 'react-native';
import App from './app';
import bgMessaging from './bgMessaging';

const app = new App();

AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => bgMessaging);
```

These are the permissions I've enabled & the service:
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
<uses-permission android:name="android.permission.VIBRATE" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.GET_ACCOUNTS" />

<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

<uses-permission android:name="android.permission.WAKE_LOCK" />

<permission android:name="com.mycustomapp.permission.C2D_MESSAGE"
            android:protectionLevel="signature" />
<uses-permission android:name="com.mycustomapp.permission.C2D_MESSAGE" />
<meta-data
                android:name="com.google.firebase.messaging.default_notification_channel_id"
                android:value="@string/default_notification_channel_id"/>
<service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>
<service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
    <intent-filter>
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
    </intent-filter>
</service>

<service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />
```

I can't figure out why am I not receiving messages when app is closed?
Is there something wrong with the way I've registered my headless task?
Am I missing some permission that I need for it to work?

**P.S.** I'm using [react-native-navigation](https://github.com/wix/react-native-navigation), and I wasn't sure how to register the headless task in it (if not the usual way as shown above).

### Environment
Android

**Build Tools:** 27.0.3
**React Native version:** 0.53.3
**RNFirebase Version:** 4.2.0
**Firebase Module:** messaging
**compileSdkVersion:** 27
**minSdkVersion:** 16
**targetSdkVersion:** 26

**Comment by aMarCruz** [comment]
@Ketn , try replacing `const app = new App()` with `AppRegistry.registerComponent('<app-name>', () => App)`, where `<app-name>` is the name of the main component.

**Comment by Ketn** [comment]
@aMarCruz Tried that, but now when the app is launched, it just shows a white screen. I don't think that is the issue.

**Comment by aMarCruz** [comment]
@Ketn , I think Headless JS needs to be set in an earlier stage that your App class is instantiated.
What is it that your App exports?

**Comment by Ketn** [comment]
It's an app similar to this: https://github.com/wix/react-native-navigation/tree/master/old-example-redux

How do I set Headless JS in an earlier stage?

**Comment by Ketn** [comment]
I expect it's done the way I've done. Not sure about that. I want to figure out if this is happening due to headlessJS implementation done wrong or something else. Because it's working fine when app is in the background (but not closed).

**Comment by judemanutd** [comment]
@Ketn I don't see any code of a channel being created, neither is a default channel mentioned in your manifest file. You won't be able to create any notifications without a channel post nougat I think.

```
if (Platform.OS !== "ios") {
    notification.android
      .setSmallIcon("ic_notification_icon")
      .android.setChannelId("news");

    const channel = new firebase.notifications.Android.Channel(
      "news",
      "News",
      firebase.notifications.Android.Importance.Max
    )
      .setSound("notification_beep")
      .setDescription("News channel");

    await firebase.notifications().android.createChannel(channel);
  }
```

**Comment by Ketn** [comment]
@judemanutd Default channel exists in AndroidManifest.xml already. Must have missed putting it in while writing this post.

```
<meta-data
                android:name="com.google.firebase.messaging.default_notification_channel_id"
                android:value="@string/default_notification_channel_id"/>
```

And I've tested on **Android 5.1.1**. This problem exists in all versions of android. For some reason, the headlessTask kills itself when the app is closed. Idk why though. Any way to figure out the reason?

**Comment by judemanutd** [comment]
@Ketn can you try it on an older device kitkat or below, I suspect this might be an issue with doze mode or battery optimizations.

**Comment by Ketn** [comment]
Using stock android. Notifications from all other apps work just fine.

**Comment by Ketn** [comment]
@judemanutd I'm sorry, I just checked. It is due to battery optimization issue. I am using OnePlus 5T (android 8.1.0) and I went to the battery settings to set it in "Not Optimised" mode for my app and I'm receiving notifications just fine. However, all other apps are in Optimise mode by default too, yet I receive notifications from them properly. Is there any way to understand why is this happening, what can be done to fix this? Because I don't expect users to disable the default battery optimized state for my app by themselves.

**Comment by judemanutd** [comment]
@Ketn are you sending your notifications with priority high

**Comment by Ketn** [comment]
@judemanutd Yes, I think so. I've tried sending both data-only and notification-only messages. Both have identical results (i.e. not working when app is killed and is in battery optimisation mode but working when in "not optimised" mode). This is the fcm message I send to fcm server from my server, in case you thin anything might be wrong with that?:

Data-only message
```
{
  "data": {
      "title":"App Notification",
      "body":"This is to notify you",
      "color":"#607D8B",
      "channel_id":"test-channel",
      "icon":"ic_notif",
      "sound":"default",
      "show_in_foreground":true
  },
  "to":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "priority":"high"
}
```

Notification message (I believe the default priority is high for notification messages?)
```
{
  "to":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "time_to_live":660,
  "notification": {
    "title":"App Notification",
    "body":"This is to notify you",
    "android_channel_id":"test-channel"
  }
}
```

Lemme know if anything's wrong with the above messages.

P.S. I get a successful response from Firebase upon sending those message requests even if I don't receive the notification on my device.

**Comment by judemanutd** [comment]
@Ketn Yep, everything looks correct, I am actually surprised that you are having issues with notification on messages because that is directly handled by the system and doesn't even start your app up, data messages are the ones where the system notifies your app.

About firebase giving a success on response, that is pretty much correct, firebase confirms that it received the message not that it was sent out from firebase servers.

I know that android P has introduced buckets for apps that throttle what an app can do and how it uses the phones resources [https://developer.android.com/preview/features/power#buckets](url)

A specific line in that says

> More active apps are assigned to buckets that give the apps higher priority, making more system resources available to the app. In particular, the bucket determines how frequently the app's jobs run, how often the app can trigger alarms, and how often the app can receive high-priority Firebase Cloud Messaging (FCM) messages. These restrictions apply only while the device is on battery power; the system does not impose these restrictions on apps while the device is charging.

Again this is a P thing and not Oreo and considering a new app should be given high priority at the start I'm not entirely sure but maybe try it on a different device or plug your device in for charging and then test it.

**Comment by Ketn** [comment]
@judemanutd I tried testing with device plugged in for charging. Still the same issue.

**Comment by aMarCruz** [comment]
@Ketn , move the `<service>` tags in your AndroidManifest.xml to inside `<application>`

**Comment by Ketn** [comment]
@aMarCruz I'm sorry but I didn't mean to say that it's my Manifest file just the content of it that hold relevance. My service tags are obviously under application tag otherwise I wouldn't be receiving notifications etc. even when app is in foreground or background.

**Comment by appli-intramuros** [comment]
Hello,

Same problem here. Did you find any solution ?

Thanks.

**Comment by appli-intramuros** [comment]
Slack app seems to have similar issues.
It seems to be due to battery optimization on android 6 and above.

https://get.slack.help/hc/en-us/articles/360001562747-Known-issues-with-Android-notifications

I dont know if is it possible to force an app not to be battery optimized by android.

**Comment by Salakar** [comment]
@Ketn unfortunately on OnePlus phones I don't think there is anything you can do from your app to prevent the behaviour you're seeing - it will require your users to disable battery optimization for your app. [Notifications are highly reliable, except when device manufacturers interfere](https://onesignal.com/blog/manufacturers-interfere-with-reliable-notifications/) 🙈 

Here's a table for reference; taken from [here](https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown):

**Comment by Ketn** [comment]
@Salakar - I understand that and setting "Don't Optimise" option helps but I also see apps like WhatsApp, Facebook, Twitter, etc. working fine without the "Don't Optimise" helps. I want to know why is that so. Is that random selection, based on app's battery usage or based on what criteria? Please give your input on that.

**Comment by judemanutd** [comment]
@Ketn I think that's due to whitelisting of apps by the OEM directly.

**Comment by DavidDimon** [comment]
@Ketn change this:
{
  "data": { // **to notification, like this: "notitication" :{ ...**
      "title":"App Notification",
      "body":"This is to notify you",
      "color":"#607D8B",
      "channel_id":"test-channel",
      "icon":"ic_notif",
      "sound":"default",
      "show_in_foreground":true
  },
  "to":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "priority":"high"
}
and this on bgMessage.js
`export default async (notification: Notification) => {`

**Comment by aseemupadhyay** [comment]
@Ketn  I confirm that this is OS related. Opted for don't optimise and it worked. However, I am not sure if it is device dependent. I have a Oneplus 6 tho.

**Comment by sangupandi** [comment]
> @Ketn unfortunately on OnePlus phones I don't think there is anything you can do from your app to prevent the behaviour you're seeing - it will require your users to disable battery optimization for your app. [Notifications are highly reliable, except when device manufacturers interfere](https://onesignal.com/blog/manufacturers-interfere-with-reliable-notifications/) 🙈
> 
> Here's a table for reference; taken from [here](https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown):
> 
> ![table](https://camo.githubusercontent.com/f98102d1470339dcbaf4b399e2dfb6741ceaa9a2/68747470733a2f2f692e696d6775722e636f6d2f716d655178344c2e706e67)
> 
> Will close this issue as it's outside the realms of an issue with the library. Feel free to continue on the discussion here though if needed.
> 
> Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:
> 
> * 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
> * 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
> * 👉  Star this repo on GitHub ⭐️

Is this fixed in latest version?

**Comment by sjernigan** [comment]
I see an issue with Chrome (not firefox) but it doesn't have anything to do with the battery setting.  And any running Chrome app will enable it to receive messages so be sure to test with no other running apps.
