### ISSUE TITLE
Channel ID not being used from Notification Composer

### ISSUE THREAD

**Issue by raoneel** [invertase/react-native-firebase#1240]
### Issue
 
I've gone through the process of setting up notifications on Android, and my app is receiving notifications. However, the notification just appears in the tray, and IS NOT displayed heads up (example below)
![image](https://user-images.githubusercontent.com/1142156/41803397-2e0cb5e0-763d-11e8-8270-7bed0627837e.png)

I've seen that the default notification channel provided doesn't have high priority. So, I created a new channel with high priority (which should allow for heads up) like this

```javascript
const channel = new firebase.notifications.Android.Channel(
      "daily",
      "Reminders",
      firebase.notifications.Android.Importance.High
    ).setDescription("Reminds you....");

// Create the channel
firebase.notifications().android.createChannel(channel);
```

On my phone, I can see that the new channel is created with high priority. Now, I go to the Firebase console and create a notification. I set the channel ID as "daily"

![image](https://user-images.githubusercontent.com/1142156/41803418-7c7b79d2-763d-11e8-9cff-2bb431cc295f.png)

However, when my app receives the notification and I long press it, it says the channel is "Uncategorized", which I assume is the default channel. It's not using the "daily" channel I just created. Does anyone know what I'm doing wrong here? 

### Environment

1. Application Target Platform: Android Oreo (8.0)

2. Development Operating System: OSX High Sierra

3. Build Tools: Android Studio

4. React Native version:
react-native-cli: 2.0.1
react-native: 0.55.4

5. RNFirebase Version:
"react-native-firebase": "^4.2.0",

6. Firebase Module: Messaging/Notifications

**Comment by Rithie** [comment]
Where did you place this piece of code?

**Comment by raoneel** [comment]
```
class Splash extends Component {
  componentWillMount() {
    // Build a channel
    const channel = new firebase.notifications.Android.Channel(
      "daily",
      "Daily Reminders",
      firebase.notifications.Android.Importance.High
    ).setDescription("Reminds you...");

    // Create the channel
    firebase.notifications().android.createChannel(channel);
}
}
```

Still seeing this issue. I'm creating notification channels as described above, and I am receiving the notification. However, these are not heads up notifications as they should be.

**Comment by Salakar** [comment]
Please see yellow box at top of the docs here, it will explain how to trigger heads-up notifications: https://rnfirebase.io/docs/v4.3.x/notifications/android

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
