### ISSUE TITLE
Android/Firestore: offline mutations are not synced after coming back online

### ISSUE THREAD

**Issue by savvopoulos** [invertase/react-native-firebase#1241]
### Issue

On android, adding an object while offline is not synced to firestore until I restart the app. This works as expected on iPhone (the added item appears on firestore after coming back online).

Steps: 1. turn off wifi 2) call firebase.firestore().collection('samples').doc(id).set(data) 3) turn wifi back on 4) wait 1 min for obj with id to appear online (does not) 5) add another obj => wait for it to appear online (also not) 6) kill app 7) start again 8) objects appear after a few seconds(edited)

### Environment

1. Application Target Platform:
Using: Samsung S5 / 7.1.2 / LineageOS.

2. Development Operating System:

react-native run-android --variant=release
on mac osx high sierra

3. Build Tools:
"buildToolsVersion '26.0.1'

4. React Native version:
    "react-native": "^0.53.0",

5. RNFirebase Version:

    "react-native-firebase": "^4.2.0",
    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation "com.google.firebase:firebase-core:15.0.2"
    implementation "com.google.firebase:firebase-analytics:15.0.2"
    implementation "com.google.firebase:firebase-auth:15.1.0"
    implementation "com.google.firebase:firebase-config:15.0.2"
    implementation "com.google.firebase:firebase-firestore:16.0.0"
    implementation "com.google.firebase:firebase-perf:15.1.0"
    implementation "com.google.firebase:firebase-storage:15.0.2"

6. Firebase Module:
Firestore.

**Comment by Ehesp** [comment]
@savvopoulos Could you try adding a network listener in RN (https://facebook.github.io/react-native/docs/netinfo.html) to check whether your device/app actually comes back online from a React Native sense? May not be related as the native SDKs should handle this but there has been a few related issues in the past.

**Comment by Salakar** [comment]
Closing issue due to no response. Can re-open on request if this is still an issue.

Thanks

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
