### ISSUE TITLE
setUserId(null) not working

### ISSUE THREAD

**Issue by EatSafeClaudia** [invertase/react-native-firebase#1247]
### Issue

setUserId(null) doesn't seem to work.

Once a user logs in, I send their id. When they log out, I want to reset their userId. Currently I do a setUserId(null), but looking on firebase, events continue being tracked under the previous user id.

### Environment

Android

1. Application Target Platform:

Android

4. React Native version:

0.54.1

5. RNFirebase Version:

4.2.0

6. Firebase Module:
Analytics

**Comment by Salakar** [comment]
@EatSafeClaudia any chance you could provide a code example of your usage

**Comment by Salakar** [comment]
Closing due to no response and unable to reproduce locally. Will re-open on request if this is still an issue.

Thanks

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by lukasgjetting** [comment]
@Salakar I'm having this issue aswell. I'm currently running it in a Redux middleware.  
I am simply doing `firebaseTracker.setUserId(null);` where `firebaseTracker = firebase.analytics();`  
When looking in Firebase Debug Mode, I see the following (after running the above function).

![From Firebase, nothing changed](https://i.gyazo.com/ef3a55b606bda157a219a3d0ea95ecf6.png)

I have verified that the function is actually running with a `console.warn`.  
I have tried doing `firebaseTracker.setUserId('null');`, but that gives me the following:

![From Firebase, user_id is the string 'null'](https://i.gyazo.com/b473a0a7d87a53c92534ef5c8e508c83.png)

I mean, it could work.. but I would prefer actually setting it to null.

Thanks in advance for your help!

**Comment by EatSafeClaudia** [comment]
Still having this issue, your description of use, @lukasgjetting, is exactly mine. I am having the issue after upgrade to RN 0.56.0 and RNFB 4.3.8.

**Comment by tjjjwxzq** [comment]
I get the same issue - trying to call `setUserId(null)` or `setUserId(undefined)` both do not work. I still see the old user id showing up in the Firebase DebugVIew. Only when I call `setUserId` on another string does the previous one get replaced (eg. `setUserId(dummy`)

RN version: 0.57.7
RNFB version: tested on both 4.2.0 and 5.2.2

**Comment by Salakar** [comment]
@lukasgjetting @EatSafeClaudia @tjjjwxzq not sure what to suggest here, we call the native method directly with the value provided to it from JS, so if you send a null it calls `FirebaseAnalytics.getInstance(getContext()).setUserId(null);` on Android. This might be a bug with the Firebase Android SDK.

Analytics re-write for v6 is complete and it has some minor changes; all the methods return Promises now so this removes the chance that this could be a race condition (e.g. RN bridge batches method calls, so setting a user id may be being sent along with other method calls, e.g. logEvent at the same time, with a promise now you can ensure that it has set the user before the next analytics method is called).

See https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md for details on the v6 release and upgrading notes / caveats - if you wish to try it out early.

**Comment by patrickbdev** [comment]
This issue is happening on iOS on the following versions:
  pod 'Firebase/Core', '5.20.2'
  pod 'Fabric', '1.9.0'
  pod 'Crashlytics', '3.12.0'
We're able to set the userId, but setting it to nil still retains the old value.

**Comment by mikeborozdin** [comment]
Why has this been closed?

It's still an issue in `5.5.3`.

**Comment by mikehardy** [comment]
seems to be an underlying sdk issue. I believe the suggested workaround was to set to empty string

**Comment by mikehardy** [comment]
can't find the related issue now but it's in the tracker somewhere just not linked here, it was from a separate issue tho

**Comment by btilford** [comment]
Pretty sure this still exists in v7. 

Assuming there is no way to unset this wouldn't setting it to a new UUID each time be better than an empty string so that you don't merge a bunch of users under the "empty" id?

**Comment by mikehardy** [comment]
This is more than a year old, if you still have a problem please post a new issue with full details and an App.js that reproduces please

**Comment by anuragraina** [comment]
The issue still exists. Setting userId to null doesn't work, it keeps the same old id.
