### ISSUE TITLE
Missing options for get() queries, like "source"

### ISSUE THREAD

**Issue by scottmas** [invertase/react-native-firebase#1248]
I just inspected the source code and the library is missing the ability to add options to `get()` queries. Per [firestore documentation](https://firebase.google.com/docs/firestore/query-data/get-data#source_options), there is a `source` option which will enable us to switch between server fetches and the offline cache. But [the current RN Firebase code](https://github.com/invertase/react-native-firebase/blob/master/lib/modules/firestore/Query.js#L140) has no support for this option:

**Comment by Salakar** [comment]
@scottmas thanks for the report, can confirm we're missing this, we'll address this as part of v4.3.0, PRs also welcome in the meantime.

**Comment by chrisbianca** [comment]
I've just added this option to both the `DocumentReference` and `CollectionReference` `get()` methods.  It will filter through as part of the next release.

**Comment by scottmas** [comment]
You're a champion Chris!

**Comment by scottmas** [comment]
Am I reading the tests right though that the `cache` option is busted on Android? Do you think that's a google library issue?

**Comment by bobmulder** [comment]
@chrisbianca  do you have any indication when the next release will be?
