### ISSUE TITLE
Can’t remove listener on the few circumstance.

### ISSUE THREAD

**Issue by lazyhoneyant** [invertase/react-native-firebase#125]
In the manual or other articles, 
firebase real-time database listener should be removed when a component will unmount.
But This doesn’t work on the specific case.

( normal )
componentDidMount() {
	this.ref.on(‘child_added’, handleAdd);
}

componentWillUnmount() {
	this.ref.off()
}

Above example works well. But In the following example, This doesn’t work.

( abnormal) 

componentDidMount() {
	this.ref.limitToLast(20).on(‘child_added’, handleAdd);       
}

componentWillUnmount() {
	this.ref.off()
}

In this case, When i came back to this component, this cause call multiiple handleAdd. This means that past listener is alive.  this.ref.off() works when only simple listener ( like this.ref.on('value',callback) or this.ref.on('child_added,callback)).

Am I wrong or is the impossible?

and I think there is no solution to grasp the listener.

let listener = this.ref.limitToLast(20).on(‘child_added’, handleAdd);       

above variable listener is not the reference to the listener but just function.

**Comment by chrisbianca** [comment]
@lazyhoneyant This is because the `limitToLast()` modifier returns a brand new Reference instance as per the spec. So `this.ref.off()` is removing the listener on the initial reference, not the new reference.

If you show how you're setting `this.ref` I can suggest a better way to approach it.

**Comment by lazyhoneyant** [comment]
Thx for answering.

The following is my brief code.

`

componentDidMount() {
    firebase.auth().signInWithCustomToken(customToken)
    .then((user) => {

      let now = new Date().getTime();

      this.chatMessagesRef = firebase.database().ref('chatMessages/' + this.props.chatRoomId);

      this.childListener = this.chatMessagesRef.orderByChild("createdAt").startAt(now).on('child_added',this.handleChild)

      this.chatMessagesRef.orderByChild("createdAt").limitToLast(20).once('value', (snapshot)=>{

      })            

    })
    .catch((err) => {
      console.error('User signin error', err);
    });

}

componentWillUnmount(){
  this.chatMessagesRef.off();
  this.chatMessagesRef.off('child_added', this.handleChild);
  this.chatMessagesRef = null;
}`

**Comment by chrisbianca** [comment]
I think the key is that you have two different references that you're interested in, so you need to separate them.  Something like:

```
componentDidMount() {
  firebase.auth().signInWithCustomToken(customToken)
  .then((user) => {
    let now = new Date().getTime();
    const chatMessagesRef = firebase.database().ref('chatMessages/' + this.props.chatRoomId);
    this.listenerRef = chatMessagesRef.orderByChild("createdAt").startAt(now);
    this.listenerRef.on('child_added',this.handleChild);

    chatMessagesRef.orderByChild("createdAt").limitToLast(20).once('value', (snapshot)=>{

    })
  })
  .catch((err) => {
    console.error('User signin error', err);
  })
}

componentWillUnMount() {
  // Note that this.listenerRef may not exist, so needs a check
  if (this.listenerRef) this.listenerRef.off();
  // or
  if (this.listenerRef) this.listenerRef.off('child_added', this.handleChild);
}
```

**Comment by lazyhoneyant** [comment]
I have been struggling with this issue for a couple of hours. but your advice works well.
Thank you. :)

**Comment by rgoldiez** [comment]
@chrisbianca - This is helpful.  Different that the web SDK it seems that you have to do the `.off()` on the specific event and handler that you want to unsubscribe.  

From the [Firebase docs](https://firebase.google.com/docs/reference/js/firebase.database.Reference#off):
> If a callback is not specified, all callbacks for the specified eventType will be removed. Similarly, if no eventType or callback is specified, all callbacks for the Reference will be removed.

It seems that `react-native-firebase` requires you to be specific with the `.off()`.  Please confirm (or refute 😄 ) my understanding and testing.

**Comment by chrisbianca** [comment]
@rgoldiez this should not be the case - `react-native-firebase` should follow the docs and remove all callbacks for a specified eventType (if no ref is supplied) or all callbacks for a reference (if no ref or callback is supplied).

We do have tests for these cases in our test suite which are all passing so please let me know if you think this isn't the case.
