### ISSUE TITLE
Attempt to invoke virtual method "java.lang.String com.google.firebase.iid.FirebaseInstanceId.getToken()" on a null object reference

### ISSUE THREAD

**Issue by gabrieljo** [invertase/react-native-firebase#1251]
1. Application Target Platform: Android 
                                - classpath 'com.android.tools.build:gradle:3.1.3'        classpath 
                                - 'com.google.gms:google-services:3.2.1'
2. Development Operating System: High Sierra
3. Build Tools: Android SDK 
4. React Native version: 0.51.0
5. RNFirebase Version: 4.2.0
6. Firebase Module:
 - "com.google.firebase:firebase-firestore:15.0.0"
- "com.google.firebase:firebase-core:15.0.2"
- "com.google.firebase:firebase-messaging:15.0.2"

Hi there,

I would like to use firebase cloud message, so installed base firebase, firebase-messaging, firebase-notification modules. then when I tried to get token. the error "Attempt to invoke virtual method "java.lang.String com.google.firebase.iid.FirebaseInstanceId.getToken()" on a null object reference" has been occurred.

I call the token "const fcmToken = await firebase.messaging().getToken()" on "componentDidMount" as a async

can you please give me some advice. thanks in advance

cheers,

**Comment by iRahulGaur** [comment]
"Attempt to invoke virtual method", most of the time this means that you haven't defined a variable or something, you have declared it but not defined it. check if fcmToken is defined properly.
hope it will help!

**Comment by Salakar** [comment]
@gabrieljo you'll need to update to "com.google.firebase:firebase-messaging:17.1.0" and also v4.3.x of React Native Firebase.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by akhileshsinha** [comment]
There was problem in merged manifest, following service was missing from the merged manifest. Added same to AndroidManifest.xml it worked like a charm.

 <service android:name="com.google.firebase.components.ComponentDiscoveryService" >
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
 </service>

**Comment by akhileshsinha** [comment]
There was problem in merged manifest, following service was missing from the merged manifest. Added same to AndroidManifest.xml it worked like a charm.

 ```
<service android:name="com.google.firebase.components.ComponentDiscoveryService" >
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
 </service>
```
Everything is working fine now.
