### ISSUE TITLE
Firestore runTransaction not running

### ISSUE THREAD

**Issue by 0paIescent** [invertase/react-native-firebase#1252]
Sadly there really isn't much to this issue, but the first example of using transactions with RNFirebase doesn't run for me. I can put console.logs before and after calling it and they run just fine, but runTransaction never does. Everything else to do with firestore works perfectly, pretty confused as to why this wouldn't work.

**Comment by Salakar** [comment]
@0paIescent android? iOS? Versions? 😛 The [tests for transactions](https://github.com/invertase/react-native-firebase/blob/master/bridge/e2e/firestore/transactions.e2e.js) are all passing so not sure what the difference is here.

**Comment by 0paIescent** [comment]
Ah sorry, Android, RNFirebase: 4.2.0. It's super weird because I can stick a console.log in the transaction and that won't even run. I'm sure I'm just missing something, I'll take another look at it later tonight.

**Comment by Ehesp** [comment]
@0paIescent could you should show your code usage?

**Comment by 0paIescent** [comment]
Sure, I've reduced it all the way down to just the following to make sure I wan't missing anything:
`firestore.runTransaction(() => 'complete').then(result => console.log(result)`

but nothing ever gets printed to the console, when I copy and paste the example from the RNFirebase Docs even it doesn't run. I'm very confused, to the point that I want to just pull the existing data out, update it, and push it back up manually without the transaction since I can't get it to work.

**Comment by Ehesp** [comment]
@0paIescent if that is your actual code usage it would seem you are missing parenthesis, when calling `firestore`:

`firestore().runTransaction(() => 'complete').then(result => console.log(result)`

You can see an example of that in action here: https://rnfirebase.io/docs/v4.2.x/firestore/transactions

**Comment by 0paIescent** [comment]
Ah my bad, I've got a file with all my firebase constants so just exporting `auth() as auth`, `firestore() as firestore`. So it actually is running with `firestore().runTransaction...`.

**Comment by Ehesp** [comment]
Right ok no worries. Hmm, sorry if I'm covering the obvious but have you put a `.catch` statement on the end to see if any errors are throwing? A full code usage example would be really handy here!
