### ISSUE TITLE
io.invertase.firebase.auth.RNFirebaseAuth.signInAnonymouslyAndRetrieveData

### ISSUE THREAD

**Issue by OMP1024** [invertase/react-native-firebase#1255]
com.google.android.gms.internal.zzdvv.zzb (Unknown Source)
--
  | com.google.firebase.auth.FirebaseAuth.signInAnonymously (Unknown Source)
  | io.invertase.firebase.auth.RNFirebaseAuth.signInAnonymously (RNFirebaseAuth.java:211)
  | io.invertase.firebase.auth.RNFirebaseAuth.signInAnonymouslyAndRetrieveData (RNFirebaseAuth.java:203)
  | java.lang.reflect.Method.invokeNative (Method.java)
  | java.lang.reflect.Method.invoke (Method.java:525)
  | com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:374)
  | com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:162)
  | com.facebook.react.bridge.queue.NativeRunnable.run (NativeRunnable.java)
  | android.os.Handler.handleCallback (Handler.java:800)
  | android.os.Handler.dispatchMessage (Handler.java:100)
  | com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:31)
  | android.os.Looper.loop (Looper.java:194)
  | com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run (MessageQueueThreadImpl.java:194)
  | java.lang.Thread.run (Thread.java:838)

**Comment by Salakar** [comment]
@OMP1024 please provide the error message not just the stack. Also please provide your versions of RN, RNFB etc

**Comment by Ehesp** [comment]
Closing this one - please reply with the information needed and we'll be happy to reopen.
