### ISSUE TITLE
on killed app as we clicked on notification how to redirect on specific screen 

### ISSUE THREAD

**Issue by ronak1992** [invertase/react-native-firebase#1256]
The issue list of this repo is exclusively for bug reports.

1> When App is in killed state notification is coming but we are not able to redirect on specific page we want to redirect

### Issue

1> When App is in killed state notification is coming but we are not able to redirect on specific page we want to redirect

### Environment  iOS-Android Both

1. Application Target Platform:   macOS Sierra, Windows 10

2. Development Operating System:  MAC    (Xcode(11.2) or Android Studio(3.2) version
 
3. Build Tools:  

4. React Native version:  react-native 0..55.3

5. RNFirebase Version:  

6. Firebase Module . :   3.3.1

**Comment by chrisbianca** [comment]
@ronak1992 You're using v3.3.1 - if you look at v4 there is much better support and documentation.

@anubansal92 are you also on v3.3.1?

**Comment by anubansal92** [comment]
@chrisbianca I'm using v4, but I'm not getting a callback in onNotification() when I click on the notification.

**Comment by anubansal92** [comment]
@chrisbianca not getting a callback in onNotificationOpened. I'm running on iphone 8 11.3 simulator

**Comment by pragneshAliansoftware** [comment]
@chrisbianca i have used onNotificationOpened , its not getting called in ios but gets called successfully in android
