### ISSUE TITLE
[Android] Play Services isAvailable() doesn't update

### ISSUE THREAD

**Issue by ecexplorer** [invertase/react-native-firebase#1257]
### Issue

After prompting the user to update Google Play Services (Android only), when the user comes back into the context of the app, I check `utils.playServicesAvailability`, and none of the values change (even in the event of an update to Play Services). Looking into the source, the culprit seems to be that `getPlayServicesStatus()` (https://github.com/invertase/react-native-firebase/blob/a090bd3480e498ef8e90c1a092f134bd098a7053/android/src/main/java/io/invertase/firebase/RNFirebaseModule.java#L79) is only called once, creating each as constants and cannot be updated again until a user cleans the app state & re-initializes.

### Environment

Android

RNFirebase Version:

Utils, v4.2.0

**Comment by Salakar** [comment]
@ecexplorer good spot, I guess the best thing for us to do would be move this to a callable method on the `utils()` module, will mean it becomes asynchronous though rather than synchronous like it is on the statics.

**Comment by ecexplorer** [comment]
An asynchronous call would work just fine :) Thanks @Salakar
