### ISSUE TITLE
[Proposal][WIP] AdMob overhaul

### ISSUE THREAD

**Issue by Salakar** [invertase/react-native-firebase#1259]
Hi all 👋 

We're aware that AdMob support has fallen behind recently and we plan to address this by overhauling the module for a potential 4.x.x/5.x.x release which will include rewriting it to ensure that it provides the all the functionality in an easy to use and reliable manner.

This issue is a placeholder that will be updated as we have more details on what will be supported and how this will be structured. 

Secondly, it's also here to show that we're aware of existing issues and that we will be addressing them as part of this proposal. Any historic or new issues will be closed and redirected here to track them in one place.

---

To help support React Native Firebase development and sustain the library long term, please consider [backing it on Open Collective](https://opencollective.com/react-native-firebase).

**Comment by Salakar** [comment]
Quick poll; should Admob remain part of this library or should we break it out into it's own library?

Click one to vote:

[![](https://api.gh-polls.com/poll/01CHBCD3WJ4VT55B9BDR9X4ZJJ/Stay%20as%20part%20of%20React%20Native%20Firebase)](https://api.gh-polls.com/poll/01CHBCD3WJ4VT55B9BDR9X4ZJJ/Stay%20as%20part%20of%20React%20Native%20Firebase/vote)
[![](https://api.gh-polls.com/poll/01CHBCD3WJ4VT55B9BDR9X4ZJJ/Break%20out%20into%20own%20library)](https://api.gh-polls.com/poll/01CHBCD3WJ4VT55B9BDR9X4ZJJ/Break%20out%20into%20own%20library/vote)

**Comment by deadcoder0904** [comment]
Hey, @Salakar would this be a part of 6.0.0?

And will it be a standalone library because I want to use it but don't want to install the whole thing?

**Comment by Salakar** [comment]
@deadcoder0904 yes & yes. All Firebase services in v6 are separate NPM packages now: https://github.com/invertase/react-native-firebase/tree/master/packages

**Comment by deadcoder0904** [comment]
@Salakar I already checked it from the README link but it returns 404. The `packages/` folder also doesn't have AdMob. Can you point me where it is?

**Comment by Salakar** [comment]
@deadcoder0904 it's not ready yet, there will be a package there once work on it starts for v6; can follow along on v6 status here: https://github.com/invertase/react-native-firebase/issues/2025 or on the [Changelog on master](https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md)

If you'd like to contribute to `admob` package and start the process then I can create a branch and package for `admob` ready to go so the code can be migrated from v5. Let me know.

**Comment by deadcoder0904** [comment]
Oh okay cool. 

> If you'd like to contribute to admob package and start the process then I can create a branch and package for admob ready to go so the code can be migrated from v5. Let me know.

Idk much about that sorry :(

Any ETA? I'm writing a blog on Admob & this might the best solution so was wondering if it'll be ready soon or not :)

**Comment by Ehesp** [comment]
@deadcoder0904 It's a couple of months away yet - unless someone else helps kick it off 👍

**Comment by Salakar** [comment]
Closing as v6 is now out with AdMob changes.
