### ISSUE TITLE
[Proposal][WIP] Storage improvements

### ISSUE THREAD

**Issue by Salakar** [invertase/react-native-firebase#1260]
Hi all 👋 

`storage()` has fallen slightly behind recently and we plan on improving the module for a 5.x.x release which includes improving it to ensure that it provides the all the functionality in an easy to use and reliable manner with better documentation and bug fixes.

This issue is a placeholder that will be updated as we have more details on what will be supported and how this will be structured in the API. 

Secondly, it's also here to show that we're aware of the issues that have already been raised and will be addressing them as part of this proposal. Any historic or new issues will be closed and redirected here to track all the issues that need addressing in one place.

New features to add:

- [ ] Multi-bucket support
    - RNFB internals re-written to support this JS side in https://github.com/invertase/react-native-firebase/commit/7632da1809554cc5314361ec36c5ca88db6a8fa6 - just needs storage work done now.
- [ ] `StorageTask`; and support for resumable uploads/downloads
   - [ ] `cancel()`
   - [ ] `resume()`
   - [ ] `pause()`

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
The issues linked above all have live fixes now in the [v4.3.0 release](https://github.com/invertase/react-native-firebase/releases/tag/v4.3.0).

New features / adding support for missing features will be done in the v5.x.x release cycle.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
![image](https://user-images.githubusercontent.com/5347038/44057265-804d46b6-9f42-11e8-8af3-440b1adb159c.png)

**Comment by ziyafenn** [comment]
Guys, multiple storage support has not yet been released? 
Thanks.

**Comment by mtford90** [comment]
@ziyafenn doesn't appear so. I've had to add multiple app instances - one for each bucket.

**Comment by Salakar** [comment]
@mtford90 @ziyafenn these things take time sorry, but I can with 100% certainty say that this will be in v6.0.0 given that it's a full rework to bring 100% Firebase SDK surface coverage in 21 modules.

You can track it here; https://github.com/invertase/react-native-firebase/pull/1837

No small release as you can see. 🙈

**Comment by Salakar** [comment]
@mtford90 @ziyafenn https://github.com/invertase/react-native-firebase/pull/2043 PR is up and in progress now; check the changelog linked there; this has multi-bucket support already implemented.

Will ping when a v6.0.0 is out with Storage ready.

**Comment by Salakar** [comment]
Closing in favour of the above-mentioned PR.
