### ISSUE TITLE
react-native-firebase and react-native-sound

### ISSUE THREAD

**Issue by Brumor** [invertase/react-native-firebase#1261]
### Issue

Hey everyone !

I've been trying to use react-native-sound inside the Basic Starter Kit for react native firebase and I keep having errors, I'm pretty new to react native and have no clue what the problem is, here is what happen when I run react-native run-android:

> Starting JS server...
> Building and installing the app on the device (cd android && gradlew.bat installDebug)...
> 
>     Configure project :app
>     registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
>     Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnul
>     l, src/debug, src/nullnullDebug]
>     registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
>     registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
>     Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nul
>     lnull, src/release, src/nullnullRelease]
>     registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> 
>     Configure project :react-native-sound
>     WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
>     It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-depe
>     ndency-configurations.html
>     WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum su
>     pported version (27.0.3) for Android Gradle Plugin 3.1.2.
>     Android SDK Build Tools 27.0.3 will be used.
>     To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each versio
>     n of the Android Gradle Plugin now has a default version of the build tools.
> 
>     Task :app:processDebugGoogleServices
>     Parsing json file: C:\Users\paulb\Projets\Localears2\android\app\google-services.json
> 
>     Task :app:compileDebugJavaWithJavac
>     C:\Users\paulb\Projets\Localears2\android\app\src\main\java\com\localears\localears\MainApplication.java:
>     6: error: package com.zmxv.RNSound does not exist
>     import com.zmxv.RNSound.RNSoundPackage;
>     ^
>     C:\Users\paulb\Projets\Localears2\android\app\src\main\java\com\localears\localears\MainApplication.java:
>     7: error: package com.zmxv.RNSound does not exist
>     import com.zmxv.RNSound.RNSoundPackage;
>     ^
>     C:\Users\paulb\Projets\Localears2\android\app\src\main\java\com\localears\localears\MainApplication.java:
>     46: error: cannot find symbol
>     new RNSoundPackage(),
>     ^
>     symbol: class RNSoundPackage
>     C:\Users\paulb\Projets\Localears2\android\app\src\main\java\com\localears\localears\MainApplication.java:
>     47: error: cannot find symbol
>     new RNSoundPackage(),
>     ^
>     symbol: class RNSoundPackage
>     4 errors
> 
> FAILURE: Build failed with an exception.
> 
>     What went wrong:
>     Execution failed for task ':app:compileDebugJavaWithJavac'.
> 
>     Compilation failed; see the compiler error output for details.
> 
>     Try:
>     Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log ou
>     tput. Run with --scan to get full insights.
> 
>     Get more help at https://help.gradle.org
> 
> BUILD FAILED in 54s
> 36 actionable tasks: 5 executed, 31 up-to-date
> Could not install the app on the device, read the error above for details.
> Make sure you have an Android emulator running or a device connected and have
> set up your Android development environment:
> https://facebook.github.io/react-native/docs/getting-started.html `

thanks in advance for any help !

### Environment

1. Application Target Platform: Android
2. Development Operating System: Windows 10
3. Build Tools: Atom
4. React Native version:  0.55.3
5. RNFirebase Version:4.1.0
6. Firebase Module: N/A

**Comment by Salakar** [comment]
@Brumor this is most likely an issue with your setup of `react-native-sound` - did you run the link command as per their readme? Check it's added to your settings Gradle as per their [manual install guide for android](https://github.com/zmxv/react-native-sound/wiki/Installation#manual-installation-on-android) if not.
