### ISSUE TITLE
Cannot read property 'collection' of undefined

### ISSUE THREAD

**Issue by gagaJay** [invertase/react-native-firebase#1263]
### Issue

Im using the sample app "react-native-firebase-starter" to try out the feature of firestore. I follow the instruction on the page and everything works just like the page said: Cloud Firestore module is enabled.
![screen shot 2018-07-02 at 2 24 22 am](https://user-images.githubusercontent.com/3827781/42135440-25330884-7d9f-11e8-94d6-4b3b4667e1cd.png)

But things changed when i try to utilise the firestore module. What I did is simply as this:
![image](https://user-images.githubusercontent.com/3827781/42135496-d0d72292-7d9f-11e8-89e0-7cfef5a25999.png)

Then I get this error:
![image](https://user-images.githubusercontent.com/3827781/42135498-e11e63fe-7d9f-11e8-82b1-0ea22881c64f.png)

This is so confusing. I follow every steps stated by the react native firebase page and still lead to this error. It looks like the firestore is just undefined. Why is this happening?

### Environment

1. Application Target Platform: 
iOS

2. Development Operating System:
macOS High Sierra

3. Build Tools:
VS Code

4. `React Native` version:
"react-native": "^0.55.3"

5. `React Native Firebase` Version:
"react-native-firebase": "^4.1.0"

6. `Firebase` Module:

  pod 'Firebase/Core', '~> 4.13.0'

  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Performance'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  
  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics', '~> 3.10.1'

7. Are you using `typescript`? 
no

---
Loving `react-native-firebase`? Please consider supporting their open collective:
👉  https://opencollective.com/react-native-firebase/donate -->

**Comment by Ehesp** [comment]
As per the [docs](https://rnfirebase.io/docs/v4.2.x/firestore/reference/firestore#collection) and web SDK, you need to call firestore which provides access to the methods:

```js
import firebase from 'react-native-firebase';

...

firebase.firestore().collection("products")
```

**Comment by gagaJay** [comment]
That works now, so the doc sample is wrong. It would be good if someone can update it.

**Comment by chrisbianca** [comment]
@gagaJay Can you direct us to the documentation sample that you think is wrong?

**Comment by gagaJay** [comment]
sure. Please check the link below, all examples within are importing firestore directly from 'react-native-firebase'.

https://rnfirebase.io/docs/v4.2.x/firestore/transactions

**Comment by chrisbianca** [comment]
Thanks, I've just updated here: https://github.com/invertase/react-native-firebase-docs/commit/5d6a3d6b206fb0303bf30424209a4e7250fc4e75#diff-10be5f2aea8b3783771475163db77ab0

This will take 10-15 minutes to filter through onto the docs website.

**Comment by gagaJay** [comment]
nice, i can see it now. good job!
