### ISSUE TITLE
Unable to load data when app is backgrounded (triggered by notification)

### ISSUE THREAD

**Issue by tclarke-scottlogic** [invertase/react-native-firebase#1267]
If I get a push notification on iOS, I want to pull some related data from the Firebase database in the background, so my user can read their articles on the train.

I'm getting the appropriate onDisplayNotification event, and it's reliably triggering, but when I query the database, it doesn't load the relevant data until the app is foregrounded, by which time the user may be offline.

So how can I retrieve entries from firebase.database() when my app is backgrounded?

**Comment by chrisbianca** [comment]
@tclarke-scottlogic This is related to: https://github.com/invertase/react-native-firebase/issues/971

In trying to simplify the messaging and notification process as part of v4, we had hidden some of the control that iOS offers when handling background messages and notifications.  We need to reinstate this functionality in a simple to understand manner.  I'm going to close this issue to remove the duplicate, but please track #971 for progress.

**Comment by pragneshAliansoftware** [comment]
Any fix for this issue? I am also facing this problem in v4.0.0
