### ISSUE TITLE
Notification does not received when app is closed

### ISSUE THREAD

**Issue by 28harishkumar** [invertase/react-native-firebase#1268]
### Issue

On android (oppo device), I am receiving notification only when app is either in foreground or in background but not when app is closed.

When app is in background `notificationDisplayedListener` does not work. It only show notification in notification drawer. `onNotificationOpened` is receiving data only when user clicks on notification. In other words, data will be lost if user doesn't click on notification.

### Environment

1. Application Target Platform: 27

2. Development Operating System: Ubuntu 16.04

3. Build Tools:
Android Studio version: 3.1.3
API level: 27

4. `React Native` version: 0.55

5. `React Native Firebase` Version: 4.2.0

7. Are you using `typescript`? No

**Comment by chrisbianca** [comment]
@28harishkumar This is exactly how notifications work on both Android and iOS. Anything with a notification part will get intercepted by the Operating System and only passed to the application if it is already open, or the user taps on the notification.

If you want data to pass to the app without user intervention when the app is closed or in the background, then you need to look at sending a data-only message.
