### ISSUE TITLE
[Android] Firebase Analytics JAR not available

### ISSUE THREAD

**Issue by luskin** [invertase/react-native-firebase#1270]
### Issue

Many other of the plugins work but analytics cannot be found as per your installation instructions. Our app gradle for firebase is as follows:

```
    // Firebase
    implementation project(':react-native-firebase')
    implementation 'com.google.android.gms:play-services-base:15.0.0'
    implementation 'com.google.firebase:firebase-core:15.0.2'
    implementation 'com.google.firebase:firebase-auth:15.1.0'
    implementation 'com.google.firebase:firebase-messaging:15.0.2'
    implementation 'com.google.firebase:firebase-database:15.0.0'
    implementation "com.google.firebase:firebase-config:15.0.2"
    implementation "com.google.firebase:firebase-analytics:15.0.2"
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.1@aar') {
        transitive = true
    }
```

but we receive the following error:
`Could not find firebase-analytics.jar (com.google.firebase:firebase-analytics:15.0.2).
Searched in the following locations:
    https://jcenter.bintray.com/com/google/firebase/firebase-analytics/15.0.2/firebase-analytics-15.0.2.jar`

Downgrading to 15.0.1 seemed to fix the issue so if 15.0.2 is available you should make sure to upload it.

### Environment

1. Application Target Platform: Android

2. Development Operating System: macOS High Sierra

3. Build Tools: Android Studio 3.1.2

4. `React Native` version: 0.55

5. `React Native Firebase` Version: 4.1.0

6. `Firebase` Module: analytics

7. Are you using `typescript`? No

---
Loving `react-native-firebase`? Please consider supporting their open collective:

  👉  [https://opencollective.com/react-native-firebase/donate](https://opencollective.com/react-native-firebase/donate)

**Comment by Salakar** [comment]
@luskin looks like the docs for this on our end are wrong - for android you don't need to add the dependency, analytics is part of Firebase Core;

Remove the `implementation "com.google.firebase:firebase-analytics:15.0.2"` and you should be good to go! Will update the docs. Sorry about this.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
Docs updated; https://rnfirebase.io/docs/v4.3.x/analytics/android
