### ISSUE TITLE
onTokenRefresh being called every time the app loads

### ISSUE THREAD

**Issue by amanthegreatone** [invertase/react-native-firebase#1271]
### Issue
Every time the app loads onTokenRefresh is getting called. Seeing this on iOS simulator as of now. Will update if its the case with real devices also.

AppContainer.js
```
class AppContainer extends Component {
componentDidMount() {
    createAndroidNotificationChannel()
    this.attachFirebaseListeners()
}

componentWillUnmount() {
    this.fcmMessageListener()
    this.notificationListener()
    this.notificationDisplayedListener()
    this.notificationOpenedListener()
    this.onTokenRefreshListener()
}

attachFirebaseListeners = async () => {
    try {
	    this.onTokenRefreshListener = firebase.messaging().onTokenRefresh(fcmToken => {
                console.log('fcm onTokenRefresh: this seems to be a bug as this method is being called every time app loads')
	           // TODO: send the new token to server
	     })

            this.fcmMessageListener = firebase.messaging().onMessage(message => {
		    console.log('onMessage:', message)
	    })

	    const notificationOpen = await firebase.notifications().getInitialNotification()
	    if (notificationOpen) {
		    console.log('getInitialNotification:', notificationOpen)
	    }

	    this.notificationListener = firebase.notifications().onNotification(notification => {
		    console.log('onNotification:', notification)
	    })

	    this.notificationOpenedListener = firebase.notifications().onNotificationOpened(notificationOpen => {
		    console.log('onNotificationOpened:', notificationOpen)
	    })

	    this.notificationDisplayedListener = firebase.notifications().onNotificationDisplayed(notification => {
		    console.log('onNotificationDisplayed:', notification)
	    })
    } catch (error) {
	    console.log(error)
    }
}

render() {
	const signedIn = this.props.userSession && this.props.userSession.token && this.props.subdomainConfig.baseURL ? true : false
	const Layout = rootNavigator(signedIn)
         return <Layout />
	}
}

const mapDispatchToProps = dispatch => bindActionCreators(ActionCreators, dispatch)
const mapStateToProps = ({ userSession, subdomainConfig }) => ({ userSession, subdomainConfig})
export default connect(mapStateToProps,mapDispatchToProps)(AppContainer)
```

### Environment

Application Target Platform: iOS
Development Operating System: macOS High Seirra
Build Tools: XCode 9.4
React Native version: 0.54.2
React Native Firebase Version: 4.2.0
Firebase Module: Messaging and Notifications
Are you using typescript? No

**Comment by danialepaco** [comment]
I think it isn't a bug, you can store the first token you get and later when this listener is trigered you can compare... and if its diferent that's it NEW TOKEN!.. I do it this way in native ios code. Hope it helps

**Comment by amanthegreatone** [comment]
that is how i am restricting redundant calls to send the token to my server yes. but i dont think this is intended behaviour. or is it?

**Comment by erandagan** [comment]
I don't think that this is the expected behaviour - the method says onToken**Refresh**, and the token wasn't at all refreshed, it was simply retrieved. I'm seeing this issue on real devices, too.

Quoting the [firebase docs](https://firebase.google.com/docs/cloud-messaging/android/client):

> The onTokenRefresh callback fires whenever a new token is generated, so calling getToken in its context ensures that you are accessing a current, available registration token [...]

Most important part of the quote is "whenever a **new** token is generated"

I think the current implementation is confusing, perhaps renaming the method to indicate _a_ token was retrieved, not necessarily a new one? Of course, the best thing would probably be fixing the issue entirely.

**Comment by jskidd3** [comment]
I agree with @erandagan. If `onTokenRefresh` is invoked at the start by design then it should be renamed as its current name suggests that it will be include a new tkoen. As stated above, by storing the token and checking its value we're effectively doing what you'd expect the function to do anyway. The `onTokenRefresh` function is behaving more like "onTokenRetrieved".

**Comment by andrewkslv** [comment]
More interesting it fires every time on iOS but not on Android.

**Comment by Salakar** [comment]
I think the best way to determine the correct behaviour would be to try it on the official Firebase Web SDK and see how it behaves - if someone could do that and report back that would save me a lot of time 👌 

Thanks

**Comment by jja08111** [comment]
If your app clears keychains, the onTokenRefresh will be called at the app startup time. Because the FirebaseInstallationId is stored at keychain and the Firebase iOS SDK regenerates token if FirebaseInstallationId differences with token prefix.
