### ISSUE TITLE
On android after installing app getInitialLink() is NULL

### ISSUE THREAD

**Issue by vvusts** [invertase/react-native-firebase#1273]
### Issue

**This issue is when app is not installed on device.**

- On IOS press on dynamic link it opens store I install app, press open and `getInitialLink()` is called `url` parameter is ok.

- On Android press on dynamic link opens store I install app, press open and `getInitialLink()` is called but `url` parameter is `NULL`.

### Environment

1. Application Target Platform: 

Android (5,6,7,8)

4. `React Native` version:

0.52.1

5. `React Native Firebase` Version:

4.2.0

6. `Firebase` Module:

Dynamic Links

7. Are you using `typescript`? 

No

---
Loving `react-native-firebase`? Please consider supporting their open collective:

  👉  [https://opencollective.com/react-native-firebase/donate](https://opencollective.com/react-native-firebase/donate)

**Comment by vvusts** [comment]
I have just debugged native code.
And I am getting `null` for `mInitialLink` in:
`nodeModules....react-native-firebase/android/src/main/java/io/invertase/firebase/links/RNFirebaseLinks.java`
Code:
```
@ReactMethod
  public void getInitialLink(final Promise promise) {
    if (mInitialLinkInitialized) {
      promise.resolve(mInitialLink);
    } else {
      if (getCurrentActivity() != null) {
        FirebaseDynamicLinks.getInstance()
          .getDynamicLink(getCurrentActivity().getIntent())
          .addOnSuccessListener(new OnSuccessListener<PendingDynamicLinkData>() {
            @Override
            public void onSuccess(PendingDynamicLinkData pendingDynamicLinkData) {
              if (pendingDynamicLinkData != null
                && !isInvitation(pendingDynamicLinkData)) {

                mInitialLink = pendingDynamicLinkData.getLink().toString();
              }
              Log.d(TAG, "getInitialLink: link is: " + mInitialLink);
              mInitialLinkInitialized = true;
              promise.resolve(mInitialLink);
```
How I did it.
I clicked on link on emulator.
Then I run debug from android studio which installed app on emulator.
Then this code was executed.

**Comment by vvusts** [comment]
Please check images. This is behaviour when debug.
You can see that after app install I have link for `pendingDynamicLinkData.getLink()` but `mInitialLink` is without value somehow.
![screen shot 2018-07-06 at 13 40 09 2](https://user-images.githubusercontent.com/25580183/42377252-d5d334f8-8122-11e8-9b34-0390a78923b4.png)
![screen shot 2018-07-06 at 13 40 21 2](https://user-images.githubusercontent.com/25580183/42377254-d5f45f16-8122-11e8-9e9d-ed4b8c83b584.png)

**Comment by vvusts** [comment]
Even if I do this:
```
     //if (pendingDynamicLinkData != null
     // && !isInvitation(pendingDynamicLinkData)) {
     mInitialLink = pendingDynamicLinkData.getLink().toString();
     //}
```
in java code `mInitialLink` is always `null`.

**Comment by vvusts** [comment]
This is versions that I use:
```
implementation project(':react-native-firebase')
    implementation "com.google.firebase:firebase-messaging:15.0.2"
    implementation "com.google.firebase:firebase-invites:15.0.1"
    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation "com.google.firebase:firebase-core:15.0.2"
```
I don't know if there is something important that I can write.

**Comment by vvusts** [comment]
I created a new project with all latest libraries and again same problem.
I posted project to: https://github.com/vvusts/firebaseDynamicLinksDemo
Summary this is new project, only android configured.

**Comment by Salakar** [comment]
@vvusts let me know how you get on with your release build after tonights screenshare, should in theory be working now.

For others; we used the `App Link Assistant` (**always ignore step 2 on it**) in Android Studio to configure / verify the links are working; `Tools` -> `App Link Assistant` and then uploading the SHA256 from the generated DAL file to the firebase console app. Worth noting you can only have one of these working at a time, multiple SHA256's on the firebase console will default to the latest one only, bit annoying as you can't test debug and release together.

You can see which SHA256 is active by visiting `https://YOUR_DOMAIN.page.link/.well-known/assetlinks.json`

ALA:
![image](https://user-images.githubusercontent.com/5347038/42475273-0d622cac-83c2-11e8-9741-8afd6e16759b.png)


---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by vvusts** [comment]
Hi, thank you @Salakar for all help on this issue.
The only thing that is required to be changed in module code is:
```
private boolean isInvitation(PendingDynamicLinkData pendingDynamicLinkData) {
    return false;  //return FirebaseAppInvite.getInvitation(pendingDynamicLinkData) != null;
  }
```
I will leave it like this for now if I uncomment it initial link again doesn't work (_I returned all other changes_).
**SHA256** is also important to be mentioned when it's updated firebase console cache it so need to wait a few minutes.
@Salakar already wrote about other stuffs so I will not mention it.
Once again thank you for help and support. We can close this one.

**Comment by Salakar** [comment]
@vvusts good to hear you've got your app released and working, that long screenshare session last night was worth it in the end then 😄 

Might be worth us removing that `isInvitation` check, not entirely sure what it's achieving to be honest. Could leave the checking up to users in JS land as an invite is still a link technically... e.g. the following could be done in JS land:

```js
const invitation = await firebase.invites().getInitialInvitation();
const link = await firebase.links().getInitialLink();

if (link && !invitation) {
 // or something
}
```

Will close and add a note in our internal issue tracker to revisit the isInvitation issue.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by bilalsyed001** [comment]
@Salakar Any timeline for isInvitation fix on android? I can confirm the solution suggested by @vvusts fixes the issue. Adding an additional check for getInvitationId if its empty works for me:

`  private boolean isInvitation(PendingDynamicLinkData pendingDynamicLinkData) {
        FirebaseAppInvite invite = FirebaseAppInvite.getInvitation(pendingDynamicLinkData);
        if (invite != null && invite.getInvitationId() != null && !invite.getInvitationId().isEmpty()) {
           return true;
        }
        return false;
   }`

If this looks ok I can submit PR.

**Comment by Salakar** [comment]
@bilalsyed001 yes please, the above as a PR would be great, I can merge and then do a patch release later today

**Comment by bilalsyed001** [comment]
#1293

**Comment by Salakar** [comment]
@bilalsyed001 v4.3.5 published with your PR included, let me know if there's any further issues.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
