### ISSUE TITLE
Crashlytics not installed natively on iOS

### ISSUE THREAD

**Issue by anhtuank7c** [invertase/react-native-firebase#1275]
### Issue
Crashlytics not installed natively

![simulator screen shot - iphone 8 plus - 2018-07-05 at 08 31 48](https://user-images.githubusercontent.com/3163410/42298106-5af759ac-802e-11e8-94a0-51447db1814f.png)

Pod install result

<img width="404" alt="screen shot 2018-07-05 at 8 32 41 am" src="https://user-images.githubusercontent.com/3163410/42298144-8f1eba4a-802e-11e8-9ba1-9134b006affa.png">

Podfile

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'shop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTSettings',
    'DevSupport'
  ]

  # Pods for shop
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics', '~> 3.10.1'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
end

```

### Environment

1. Application Target Platform: 

iOS

2. Development Operating System:

macOS Sierra

3. Build Tools:

Xcode 9.4.1
iOS 10.0.0

4. `React Native` version:

"react-native": "0.56.0",

5. `React Native Firebase` Version:

"react-native-firebase": "^4.2.0"

6. `Firebase` Module:

Crashlytics

7. Are you using `typescript`? 

no

**Comment by anhtuank7c** [comment]
Sound i have to use `react-native link react-native-firebase` instead of integrate via `cocoapods`

**Comment by SamMatthewsIsACommonName** [comment]
I jsut got the same error trying to update, with auth. Will downgrade for now
<img width="328" alt="screen shot 2018-07-19 at 10 16 46 am" src="https://user-images.githubusercontent.com/21329063/42919595-e608cb34-8b3c-11e8-9315-42c3f1c66066.png">

**Comment by anhtuank7c** [comment]
https://rnfirebase.io/docs/v4.3.x/installation/ios#2.-React-Native-Firebase-Installation-Recommended-installation

**Comment by SamMatthewsIsACommonName** [comment]
in the release notes of 4.3.0 it talks about which pods to use... Not sure just saying to use link now instead is very constructive?
