### ISSUE TITLE
Feature Request: Disable Crashlytics in Debug Builds on Android/iOS

### ISSUE THREAD

**Issue by f0rr0** [invertase/react-native-firebase#1277]
https://docs.fabric.io/android/crashlytics/build-tools.html#disable-crashlytics-for-debug-builds
https://docs.fabric.io/apple/crashlytics/advanced-setup.html#conditional-dsym-upload

**Comment by Salakar** [comment]
Thanks for flagging, we're doing a custom init of Crashlytics in our internal re-write of it, so this should be supportable hopefully in a future release.

Will close and track in internal board and reply when it's being worked on / planned to be released.

**Comment by harisoyo** [comment]
Hi, Is this available yet?
