### ISSUE TITLE
All links to premium kits are broken

### ISSUE THREAD

**Issue by n-scope** [invertase/react-native-firebase#1279]
Hi,
I am not sure if it the right place to submit the issue, but it seems to me that all your links to your premium starter kits are redirected to https://rnfirebase.io/docs/v4.2.x/getting-started

So far I have tested:
https://rnfirebase.io/kits
http://invertase.link/get-started-premium
https://rnfirebase.io/kits/auth-starter

I hope you will be able to fix it soon ;) Inbetween could you tell what starter kits are available and how much do they cost ?
Thanks a lot !

**Comment by Salakar** [comment]
Sorry we're no longer offering premium starter kits for the time being. They may however be resurfacing in the near future.

Apologies for the inconvenience, we still need to remove a couple of links from the site still.

**Comment by n-scope** [comment]
Too bad, for solo developpers like me, it was a good way to provide support for your great work at this open source project, while speeding up my own projects !

Thanks for your answer anyway !

**Comment by sibijosephv** [comment]
I bought this one earlier and I no longer have the support or the links to download the premium kit. Too bad. :(
