### ISSUE TITLE
[iOS] Crashlytics null pointer crash

### ISSUE THREAD

**Issue by ochrstn** [invertase/react-native-firebase#1281]
### Issue

I followed the documentation to add Firebase and Crashlytics to my React Native project.

I used the following function to test the crash reporting:

`firebase.crashlytics().crash()`

On iOS this leads to a crash (**EXC_BREAKPOINT**) inside the library when accessing the Crashlytics singleton, which turned out to be a null pointer for me (RNFirebase.xcodeproj/fabric/crashlytics/RNFirebaseCrashlytics.m):

```
RCT_EXPORT_METHOD(crash) {
    [[Crashlytics sharedInstance] crash];
}
```

Some related log output:
```
[Crashlytics] Version 3.10.1 (129)
...
5.4.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.50001000 started
```
On Android everything is working fine.

### Environment

1. Application Target Platform: 

iOS 11.0.1

2. Development Operating System:

macOS High Sierra 10.13.2

3. Build Tools:

Xcode Version 9.3.1 (9E501)

4. `React Native` version:

0.55.2

5. `React Native Firebase` Version:

4.2.0

6. `Firebase` Module:

```
Firebase (5.4.0)
Crashlytics (3.10.1)
Fabric (1.7.5)
```

installed via Podfile

7. Are you using `typescript`? 

no

**Comment by Salakar** [comment]
Hello, this is correct behaviour, crash() is for testing purposes so will crash your app, on iOS, this is a hard crash and on Android, a soft crash - the differences are due to the native Firebase SDKS.
