### ISSUE TITLE
[RemoteConfig] "Empty String" value is treated differently in IOS/Android

### ISSUE THREAD

**Issue by jpgarcia** [invertase/react-native-firebase#1282]
### Issue
I'm using `firebase.config().getValues` to retrieve values from Remote Config. 

What I found is that If you set an item in Firebase's console as `Empty String` it will be returned as follows:

**IOS**: 
```js
{ 
  source: 'remote',
  'val()': 0 
}
```

**Android**: 
```js
{ 
  source: 'remote',
  'val()': '' 
}
```

just to clarify: `No Value` works as expected retuning the following both in IOS and Android:

```js
{ 
  source: 'static',
  'val()': 0
}
```

### Environment

1. Application Target Platform: **Both**

2. Development Operating System: **macOS High Sierra**

3. Build Tools: **N/A**

4. `React Native` version: **0.51.0**

5. `React Native Firebase` Version: **4.2.0**

6. `Firebase` Module: **remote config**

7. Are you using `typescript`? **no**

---
Loving `react-native-firebase`? Please consider supporting their open collective:

  👉  [https://opencollective.com/react-native-firebase/donate](https://opencollective.com/react-native-firebase/donate)

**Comment by Ehesp** [comment]
Just checked this, seems it's a native iOS SDK bug. I have filed a bug report with Firebase and will let you know the outcome.

There isn't really much we can do here, as zero is still a valid remote config value so we can't convert it our side.
