### ISSUE TITLE
getInitialNotification() returns null if app opens after notification banner is gone

### ISSUE THREAD

**Issue by MakeAndyBetter** [invertase/react-native-firebase#1289]
### Issue

Notifications are received in Foreground/Background/Closed State. 

If I receive a notification while the app is closed and I then open the app via the app icon, the initial notification is null even though there was a notification received.

### Environment

1. Application Target Platform: 

IOS

2. Development Operating System:

macOS High Sierra

3. Build Tools:

Xcode 9.4.1 (9f2000)

4. `React Native` version:

0.55.4

5. `React Native Firebase` Version:

4.2.0

6. `Firebase` Module:

Notifications

7. Are you using `typescript`? 

no

---
Loving `react-native-firebase`? Please consider supporting them with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by brzonsea** [comment]
This is happening for me in Android as well

**Comment by rheng001** [comment]
Same here, happening for me on Android

**Comment by Baskerville42** [comment]
Does anyone have any ideas how to fix it?

**Comment by RDardelet** [comment]
As the [documentation for getInitialNotification](https://rnfirebase.io/docs/v4.3.x/notifications/reference/Notifications#getInitialNotification) specifies, you need to open the app via pressing a notification in order to retrieve the notification data. If you open the app by pressing the "app icon" as you mentioned, it is normal that you'll get `null` returned.

**Comment by RDardelet** [comment]
But I am experiencing an issue where when I press a notification with app killed on android, the app launches but I still get `null` from getInitialNotification as if it was not opened by a notification.

**Comment by evaleirasclapps** [comment]
@RDardelet Check if you added the corresponding `<intent-filter />` in **AndroidManifest.xml**
```
<intent-filter>
    <action android:name="ACTION_1" />
    <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```
Nota that ACTION_1 is the action named in the notification payload as **click_action** .

**Comment by RasmusFredensborg** [comment]
This solved my issues with getInitialNotification returning null:

According to [https://github.com/invertase/react-native-firebase/issues/1331](url), you need to add:
```
@Override
public void onNewIntent(Intent intent) {
    setIntent(intent);
    super.onNewIntent(intent);
}
```
in MainActivity.java.

**Comment by phonganhhung9xtb** [comment]
what about on iOS when app killed, if i tap on notification getInitialNotification not fire, app crashed immediate. any solution for this issue? i'm using RN 0.57.8 and RNF 5.2.0. thank

**Comment by CTres** [comment]
I'm having this issue.

**Comment by naxel** [comment]
any news or solutions?

**Comment by Anujmoglix** [comment]
error: cannot find symbol
            public void onNewIntent(Intent intent)

**Comment by rafaelcavalcante** [comment]
> error: cannot find symbol
> public void onNewIntent(Intent intent)

There is more info inside the [issue](https://github.com/invertase/react-native-firebase/issues/1331) mentioned by @RasmusFredensborg, @Anujmoglix, this one:

> @MrEdinLaw Add this at the top of your MainActivity.java
> `import android.content.Intent;`

**Comment by Anujmoglix** [comment]
Thanks @rafaelcavalcante  . I have added this but it is not working for me.

**Comment by rafaelcavalcante** [comment]
> Thanks @rafaelcavalcante . I have added this but it is not working for me.

I made these changes too i could not get it to work. I believe the problem i'm having is because of the custom splashscreen library. There is an issue mentioning it...

**Comment by mikehardy** [comment]
Just saying if anyone is using any splash screen except the new-er [react-native-bootsplash](https://github.com/zoontek/react-native-bootsplash/), you should convert to react-native-bootsplash immediately. It works and is maintained

Conversion is very fast and there is even a CLI to generate the storyboard file you need now for iOS app accepatance, to replace the old .xib file

**Comment by rafaelcavalcante** [comment]
> Just saying if anyone is using any splash screen except the new-er [react-native-bootsplash](https://github.com/zoontek/react-native-bootsplash/), you should convert to react-native-bootsplash immediately. It works and is maintained
> 
> Conversion is very fast and there is even a CLI to generate the storyboard file you need now for iOS app accepatance, to replace the old .xib file

Thanks Mike! I'll go for it ;)

**Comment by tara-singh-danu** [comment]
Does anyone found a solution?

**Comment by acro5piano** [comment]
I used Notifee and it shows initialNotification successfully. On the other hand, react-native-firebase does not.

https://notifee.app/react-native/reference/getinitialnotification

**Comment by thisisashukla** [comment]
facing similar issue. i am getting null from messaging().getIntitialNotification()

**Comment by Keyur-Rao** [comment]
Issue: I was getting remoteData from messaging().getInitialNotification() and messaging().setBackgroundHandler() also not register.
solution: @react-native-firebase, @react-native-firebase/messaging is conflict with @notifee i simplly remove notifee module and it's works for me..

**Comment by Shasikhan** [comment]
> Issue: I was getting remoteData from messaging().getInitialNotification() and messaging().setBackgroundHandler() also not register. solution: @react-native-firebase, @react-native-firebase/messaging is conflict with @notifee i simplly remove notifee module and it's works for me..

But what about if we want to use notifee with react native firebase messaging. How to solve this problem. Any idea?

**Comment by mikehardy** [comment]
@Shasikhan you just use notifee and use the notifee handlers instead of the react-native-firebase handlers?

**Comment by Shasikhan** [comment]
> @Shasikhan you just use notifee and use the notifee handlers instead of the react-native-firebase handlers?

I am using the react-native-firebase handlers as mentioned in the notifee library FCM integration

// React Native
import notifee from '@notifee/react-native';
import messaging from '@react-native-firebase/messaging';

function onMessageReceived(message) {
  notifee.displayNotification(JSON.parse(message.data.notifee));
}

messaging().onMessage(onMessageReceived);
messaging().setBackgroundMessageHandler(onMessageReceived);

**Comment by autimio** [comment]
Using `react-native-notifications` worked for me.

```
import { Notifications } from 'react-native-notifications';
Notifications.getInitialNotification().then(async remoteMessage => {}).catch(err => { console.error(err, 'err') })
```

**Comment by LasithaOffice** [comment]
Ive faced the same issue.  I also got null from messaging() .getInitialNotification() . for me it was I'd had multiple .getInitialNotification() method callings in the app. and only the first method will be executed with the correct input.. after removing unwanted ones it worked for me even inside a promise object.
