### ISSUE TITLE
Can't find variable: ThenableReference // ThenableReference is not defined

### ISSUE THREAD

**Issue by smallex** [invertase/react-native-firebase#1292]
### Issue

I just upgraded to RNFirebase v4.3.3 and now get the following error(s) when executing
`firebase.database().ref(somePath).push()`:

![screen shot 2018-07-11 at 14 10 30](https://user-images.githubusercontent.com/16029467/42552397-0674d68c-8517-11e8-8c07-c3288465d544.png)
![screen shot 2018-07-11 at 14 30 30](https://user-images.githubusercontent.com/16029467/42552398-06b08e02-8517-11e8-8fd1-429171b23293.png)

The Reference.js file is located at node_modules/react-native-firebase/dist/modules/database/Reference.js. Interestingly, the code snippet 

```
declare class ThenableReference<+R> extends Reference {
  then<U>(
    onFulfill?: (value: R) => Promise<U> | U,
    onReject?: (error: any) => Promise<U> | U
  ): Promise<U>;
  catch<U>(onReject?: (error: any) => Promise<U> | U): Promise<R | U>;
}
```

as introduced by https://github.com/invertase/react-native-firebase/pull/869 exists at **lib**/modules/database/Reference.js but not at **dist**/modules/database/Reference.js. I am not sure how the dist folder is generated or why it is used instead of the lib folder, so any help would be appreciated.

### Environment

1. Application Target Platform: 
Both Android and iOS

2. Development Operating System:
macOS High Sierra 10.13.5

3. Build Tools:
-

4. `React Native` version:
0.55.4

5. `React Native Firebase` Version:
4.3.3

6. `Firebase` Module:
database

7. Are you using `typescript`? 
no

---
Loving `react-native-firebase`? Please consider supporting them with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
Have reverted this for now, needs tweaking given current build setup. Just published a patch version v4.3.4 with this in.
