### ISSUE TITLE
orderByChild().equalTo() only returns one result

### ISSUE THREAD

**Issue by smkhalsa** [invertase/react-native-firebase#13]
Here's my code

```
import Firebase from 'firebase'
// import Firebase from 'react-native-firebase'
import config from './firebaseConfig'

const firebase = Firebase.initializeApp(config)

const collectionsRef = firebase.database().ref('collections/v1-0')
collectionsRef.orderByChild('ownerId').equalTo(userId).once('value')
```

When I run the above, I get all 4 results stored in my firebase. However, when I comment out firebase and uncomment react-native-firebase, I only get 1 result.

**Comment by Salakar** [comment]
What type of value is userId, this will help debug, assuming a string? Could you give a sample of your data also if possible? Thanks

**Comment by smkhalsa** [comment]
@Salakar Yes, userId is a string - a firebase generated user uid. Here's a sample collection:

```
{
  "id" : "-KdbLN7GOnaO6e0kyjIq",
  "kriyaIds" : [ "pran-bandha-mantra-meditation", "long-chant", "disease-resistance-and-heart-helper", "meditation-for-strong-nerves", "pranayam-energizer-series", "kriya-for-elevation", "kriya-for-morning-sadhana", "indra-nittri-meditation" ],
  "name" : "Favorites",
  "ownerId" : "7hbEl05CXxX33ZrSMNsV9ONYWn22"
}
```

**Comment by Salakar** [comment]
@smkhalsa 
![image](https://cloud.githubusercontent.com/assets/5347038/24244974/f9b905dc-0fb8-11e7-84d1-26e36db03dd5.png)

Added a test with the same query you're doing which compares native vs web's snapshot.val() output and the deep equality check is passing - at least on ios, are you on Android? Going to test android next

**Comment by Salakar** [comment]
@smkhalsa seems to be working also on android:

![image](https://cloud.githubusercontent.com/assets/5347038/24245592/72507f3c-0fbb-11e7-9a24-ff065576df4b.png)

**Comment by Salakar** [comment]
The test data structure: 
![image](https://cloud.githubusercontent.com/assets/5347038/24245618/890e5744-0fbb-11e7-880c-3a8378184bf2.png)

Is anything wildly different here?

**Comment by smkhalsa** [comment]
@Salakar, it looks like this is an issue with Firebase. I tried using the iOS SDK directly to access the data, and it still came back with only one result. 

I'm closing this as the issue appears not to be related to react-native-firebase.

**Comment by smkhalsa** [comment]
I found the culprit, but I'm still not sure why this was happening. 

I had initialized my firebase in native iOS code since I was getting an error when initializing in JS. I had also set persistence in native iOS code.

```
  [FIRApp configure];
  [FIRDatabase database].persistenceEnabled = YES;
```

When I remove the second line and re-build, everything seems to work correctly and consistently.
