### ISSUE TITLE
Requesting Starter Kit with create-react-native-app

### ISSUE THREAD

**Issue by lkhgvsuren** [invertase/react-native-firebase#1303]
I create an app with create-react-native-app and run it with no problem. But I tried Basic Starter Kit on official site. And then it crashed. It would be very helpful if you provide a starter kit with create-react-native-app.

**Comment by Ehesp** [comment]
Hello - we recommend checking out https://github.com/ueno-llc/react-native-starter for a more complete starter kit.

We have discussed a CLI for the starter kit but it's not at the top of our priority list right now sorry.
