### ISSUE TITLE
checkActionCode - bug for iOS

### ISSUE THREAD

**Issue by chris-divvito** [invertase/react-native-firebase#1304]
### Issue
Hi - I have a bug using checkActionCode - as far as I can tell it will be a general bug for any use of checkActionCode with codes for the reset password action. I don't know much more about Obj-C than I have discovered while trying to track this one down, or I would normally try to submit along with a PR to fix it.

So my use case looks like this: 

```
// ...
  let codeInfo: firebase.auth.ActionCodeInfo | null = null;
  try {
    codeInfo = yield call([auth, auth.checkActionCode], verificationCode);
  } catch (e) {
    yield call(resetPasswordErrorHandling, e);
    return;
  }
//...
```

(the use of `yield call()` is from a lib called Redux Sagas, but you can consider it analogous in this case to `codeInfo = await auth.checkActionCode(verificationCode)` in case you aren't familiar with it.)

We experience a hard crash at this point on iOS. From a mornings chasing this down I believe the root cause is in `RNFirebaseAuth.m` in the `checkActionCode` method, on this line:

`NSDictionary *result = @{@"data": @{@"email": [info dataForKey:FIRActionCodeEmailKey], @"fromEmail": [info dataForKey:FIRActionCodeFromEmailKey],}, @"actionType": actionType,};`

The error logged at the crash is: 

```
Application threw exception NSInvalidArgumentException: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]

```

From my reading, the NSDictionary shorthand: `@{}` does not support nil values. From my debugging, it appears that at this point the "fromEmail" key of info is nil. Based on my reading of the general firebase docs, I think this is to be expected for codes for any action other than `RECOVER_EMAIL`.

As I said, I don't really grok Obj-C, but I would hazard a guess that the solution is to check for this case and either insert some other supported value in for the nil case (empty string? Boolean false? Something else?), or to not include the fromEmail key at all in the nil case.

### Environment

1. Application Target Platform: 
Both (but issue only arises in iOS)

2. Development Operating System:
MacOS High Sierra

3. Build Tools:
xCode 9.4

4. `React Native` version:
0.51.0

5. `React Native Firebase` Version:
3.2.0 (although the relevant code is unchanged in later versions and a test of updating to 3.3.1 finds the issue to persist)

6. `Firebase` Module:
auth

7. Are you using `typescript`? 
yes

**Comment by Salakar** [comment]
@chris-divvito thanks for the detailed report and the debugging as well - really helpful 👍 

Could you locally swap out that line with the below block, rebuild your app and let me know how you get on:

```objectivec
NSMutableDictionary *data = [NSMutableDictionary dictionary];

if ([info dataForKey:FIRActionCodeEmailKey] != nil) {
    [data setValue:[info dataForKey:FIRActionCodeEmailKey] forKey:@"email"];
} else {
    [data setValue:[NSNull null] forKey:@"email"];
}

if ([info dataForKey:FIRActionCodeFromEmailKey] != nil) {
    [data setValue:[info dataForKey:FIRActionCodeFromEmailKey] forKey:@"fromEmail"];
} else {
    [data setValue:[NSNull null] forKey:@"fromEmail"];
}

NSDictionary *result = @{ @"data": data, @"actionType": actionType };
```

If all works well after that I can look into doing a patch version for the v3.3.x release line for you.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by chris-divvito** [comment]
Thanks @Salakar - that does indeed fix the issue for me

**Comment by chris-divvito** [comment]
Just a note that this issue is prevalent in 4.3.8 as well

**Comment by chris-divvito** [comment]
oh except that instead of actionType the second prop name should be `@"operation"` to comply with the new ActionCodeInfo type

**Comment by Salakar** [comment]
@chris-divvito the fix for this is on the v4.3.x branch, it's just not been published to npm as we're working on v5 at the moment. v5.0.0-rc1 has this included though if you're interested in using the latest version - see the pre-releases channel on discord for more info.

Will try and get a v4.4.0 out at some point with this in. Thanks for reporting the typings issue as well 👌

**Comment by rtman** [comment]
@Salakar 

is this fix only available in v5.x.x? I see you mentioned a v4.4.0 possibly coming, I'm still on v4.3.7 and can't upgrade to v5 yet due to the react-native 0.56 min requirement. 

I might have to manually fix it for now i think.

**Comment by chris-divvito** [comment]
@rtman I've been doing the same in the meantime too - we similarly had issues trying to make the move to 0.56.

I can strongly recommend the `patch-package` npm module for this.
