### ISSUE TITLE
Performance Monitoring - Custom Attributes

### ISSUE THREAD

**Issue by lmarti17** [invertase/react-native-firebase#1305]
### Issue

Hello, I want to use on top of Performance Monitoring, the **Custom Attributes** feature as seen in Firebase documentation (https://firebase.google.com/docs/perf-mon/custom-attributes) but I can't seem to find any equivalent support for this in the package. 
Is it implemented in your package or do you plan to support this feature ? 
Thanks !

### Environment

1. Application Target Platform: 

Both

2. Development Operating System:

macOS Sierra

3. Build Tools:

4. `React Native` version:

55.4.0

5. `React Native Firebase` Version:

3.2.0

6. `Firebase` Module:

Performance Monitoring

7. Are you using `typescript`? 

No

**Comment by lmarti17** [comment]
Thanks for the quick answer !
Any idea of the date for the 5.0 release ?

**Comment by Ehesp** [comment]
@lmarti17 Not 100% sure on that yet sorry. 

I've just pushed up some more changes including iOS support, typescript and also theres a 5.0 branch on the docs repo. Feel free to pull the changes in from the branch if you'd like to use them now. It's also now an open PR: https://github.com/invertase/react-native-firebase/pull/1316

I'll go ahead and close this issue for now, can track progress on the PR.

**Comment by Aung-Myint-Thein** [comment]
hello, I am using react-native-firebase 4.3.7 and I saw `perf()` is commented out in firebase index.d.ts. Does it mean the performance monitoring is not available in 4.3.7 and I should update to 5+ version?

Thanks in advance.
