### ISSUE TITLE
'Failed to display notificaton' on iOS

### ISSUE THREAD

**Issue by im-aditya** [invertase/react-native-firebase#1307]
### Issue

I am not able to trigger local / scheduled notifications on iOS. 

My code:

```
const notification = new firebase.notifications.Notification()
        .setNotificationId('notificationId')
        .setTitle('My notification title')
        .setBody('My notification body')
        .setData({
            key1: 'value1',
            key2: 'value2',
        });

    if (Platform.OS === 'ios') {
        notification
            .ios.setBadge('1');
    } else {
        notification
            .android.setChannelId('test-channel')
            .android.setSmallIcon('ic_launcher');
    }

    try {
        firebase.notifications().displayNotification(notification);
    } catch (error) {
        console.warn('[FirebaseService] Failed to show local notification', error);
    }

    try {
        const date = new Date();
        date.setSeconds(date.getSeconds() + 10);
        firebase.notifications().scheduleNotification(notification, {
            fireDate: date.getTime(),
        });
    } catch (e) {
        console.warn('[FirebaseService] Failed to schedule notification', e);
    }
```

Getting this error: 

For local notification: 

```
Possible Unhandled Promise Rejection (id: 0):
Error: Failed to display notificaton
createErrorFromErrorData@http://172.20.10.7:8081/index.bundle?platform=ios&dev=true&minify=false:2056:26
http://172.20.10.7:8081/index.bundle?platform=ios&dev=true&minify=false:2008:51
__invokeCallback@http://172.20.10.7:8081/index.bundle?platform=ios&dev=true&minify=false:2450:23
http://172.20.10.7:8081/index.bundle?platform=ios&dev=true&minify=false:2195:34
__guardSafe@http://172.20.10.7:8081/index.bundle?platform=ios&dev=true&minify=false:2363:13
invokeCallbackAndReturnFlushedQueue@http://172.20.10.7:8081/index.bundle?platform=ios&dev=true&minify=false:2194:21
invokeCallbackAndReturnFlushedQueue@[native code]
```

For schedule notification:
```
Possible Unhandled Promise Rejection (id: 1):
Error: Failed to schedule notificaton
createErrorFromErrorData@http://172.20.10.7:8081/index.bundle?platform=ios&dev=true&minify=false:2056:26
http://172.20.10.7:8081/index.bundle?platform=ios&dev=true&minify=false:2008:51
__invokeCallback@http://172.20.10.7:8081/index.bundle?platform=ios&dev=true&minify=false:2450:23
http://172.20.10.7:8081/index.bundle?platform=ios&dev=true&minify=false:2195:34
__guardSafe@http://172.20.10.7:8081/index.bundle?platform=ios&dev=true&minify=false:2363:13
invokeCallbackAndReturnFlushedQueue@http://172.20.10.7:8081/index.bundle?platform=ios&dev=true&minify=false:2194:21
invokeCallbackAndReturnFlushedQueue@[native code]
```

I was using [react-native-push-notifications](https://github.com/zo0r/react-native-push-notification) but I had to switch to firebase for some reasons. With the previous library local notifications were working fine. But now its not.

Both of these promise rejections are coming from this file: https://github.com/invertase/react-native-firebase/blob/master/ios/RNFirebase/notifications/RNFirebaseNotifications.m

And it is not entering the try catch block of my code !!

I have requested the notification permissions and allowed it. Since notifications were working with the previous library, I am guessing my certificates and provisioning profile is setup correctly.

Also I have removed all the setup code for the previous library, just in case if it was causing some issue. 

### Environment

1. Application Target Platform: 

iOS 11.0.3

2. Development Operating System:

macOS Sierra

3. Build Tools:

Xcode 9.3.1

4. `React Native` version:

0.55.4

5. `React Native Firebase` Version:

^4.2.0

6. `Firebase` Module:

messaging, notifications

7. Are you using `typescript`? 

no

**Comment by im-aditya** [comment]
I added a breakpoint to the Obj-C code and the error it is displaying is this:

<img width="724" alt="screen shot 2018-07-17 at 9 58 14 am" src="https://user-images.githubusercontent.com/3098218/42796520-444cf274-89a8-11e8-910e-e8db634810f0.png">

NSCocoaErrorDomain - code 4097
connection to service named com.apple.usernotifications.usernotificationservice

I don't know Obj-C so I have no idea what this is about. Any help ?

**Comment by hwde** [comment]
I was able to trace this in XCode, Apple expects UNMutableNotificationContent.badge to be NSNumber, so ensure that setBadge() gets a a number:

```
if (Platform.OS === 'ios') {
        notification
            .ios.setBadge(1);
}
```

Then it works.

**Comment by Ehesp** [comment]
@Titozzz `displayNotification` is a promise - check the error that it returns as it's currently getting swallowed. The error could be more graceful than the raw one.

**Comment by Titozzz** [comment]
Sure let me try !

**Comment by ducpt2** [comment]
@Titozzz  same error to me. :)))

**Comment by tkow** [comment]
I found that notification instance from callback argument has null type data and they cause crush of app. I set undefined instead of null via set~ methods, then it is solved. So, it can be fixed by modifying initialize method of notification if null is passed to constructor.
