### ISSUE TITLE
Cloud Functions - httpsCallable error: Object cannot be encoded in JSON

### ISSUE THREAD

**Issue by KyleCprt** [invertase/react-native-firebase#1314]
### Issue

Hello,
I implemented RN Firebase Cloud Functions module on my project and I have an issue on Android. I followed the instructions on the documentation and when I call this code:

```javascript
const httpsCallable = this._firebase.functions().httpsCallable('checkIfUserExists');

    httpsCallable({ uid: 'xxx-xxx-xxx' })
        .then(({ data }) => {
            console.log(data);
        })
        .catch(httpsError => {
            console.log(httpsError.code); // invalid-argument
            console.log(httpsError.message); // Your error message goes here
            console.log(httpsError.details.foo); // bar
        })
```

I get the following error:
`Error: Object cannot be encoded in JSON: { NativeMap: {"uid":"xxx-xxx-xxx"} }`

When I put breakpoints in the native code 'RNFirebaseFunctions.java', it looks like the 'input' variable is not well formated. If I change the following code
```
httpsCallableReference
      .call(input)
      .addOnSuccessListener(new OnSuccessListener<HttpsCallableResult>() {
         ...
```

to 
```
httpsCallableReference
      .call()
      .addOnSuccessListener(new OnSuccessListener<HttpsCallableResult>() {
         ...
```
It well goes into the `onSuccess` method.

Here your can find a screenshot during the `onFailure` breakpoint:
![capture d ecran 2018-07-18 a 15 20 30](https://user-images.githubusercontent.com/32989884/42884310-4fb052fe-8a9e-11e8-80af-6686089999ee.png)

And here the content of the `input` variable:
![capture d ecran 2018-07-18 a 15 23 17](https://user-images.githubusercontent.com/32989884/42884419-9339764a-8a9e-11e8-87db-a9d39547eb2d.png)

Note: My project already use several React Native Firebase modules (Auth, Database...) and everything else works.

### Environment

1. Application Target Platform: 
- Android (working fine on iOS)

2. Development Operating System:
macOS 10.13.4

3. Build Tools:
Android Studio 3.1.3
Build #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.4

4. `React Native` version:
0.54.1

5. `React Native Firebase` Version:
4.2.0

6. `Firebase` Module:
Cloud Functions ("com.google.firebase:firebase-functions:16.0.1")

7. Are you using `typescript`? 
No

**Comment by Ehesp** [comment]
Hello, thanks for the report.

Just tested this locally with the exact same code and I, unfortunately, can't replicate it.

```java
Object input = wrapper.toHashMap().get(DATA_KEY);
```

Straight after this line (45), `input` is always returned correctly as a `HashMap` (see below), but in your screenshot, it shows it as a `NativeMap` - not sure how that can happen. Do you mind creating a quick test repository that reproduces the issue?

![image](https://user-images.githubusercontent.com/842078/42892538-f9145830-8aa9-11e8-983a-eddea485e6f9.png)

**Comment by KyleCprt** [comment]
Hello 👋

I created a repo: https://github.com/KyleCprt/rn-firebase-issue. You should be able to reproduce this issue

**Comment by Ehesp** [comment]
@KyleCprt sorry I've been away - I'll get this looked at ASAP!

**Comment by imspikey** [comment]
still having this issue on version 5.1.1!!!
have it bean resolved?

**Comment by Salakar** [comment]
We've been unable to repro this on the v6 release of functions support - if this is still an issue on v6 please let us know with a new issue and a reproduction example.

Will close this in the meantime sorry.
