### ISSUE TITLE
react native stucked at Loading from localhost:8081

### ISSUE THREAD

**Issue by guitar9** [invertase/react-native-firebase#1321]
### Issue

I want to use firebase cloud messaging. I want to send a notification from my backend to user of the app.
I did all steps which are described in the documentation.
When i want to run the app i get this error message:

```
/home/t/.gradle/caches/transforms-1/files-1.1/appcompat-v7-23.0.1.aar/42bc2fc4a31ff4a3c61485418522917b/res/values/values.xml:113:5-69: AAPT: error: resource android:attr/fontStyle not found.
    
/home/t/.gradle/caches/transforms-1/files-1.1/appcompat-v7-23.0.1.aar/42bc2fc4a31ff4a3c61485418522917b/res/values/values.xml:113:5-69: AAPT: error: resource android:attr/font not found.
    
/home/t/.gradle/caches/transforms-1/files-1.1/appcompat-v7-23.0.1.aar/42bc2fc4a31ff4a3c61485418522917b/res/values/values.xml:113:5-69: AAPT: error: resource android:attr/fontWeight not found.
```

### Environment

1. Application Target Platform: 

Android

2. Development Operating System:

Linux

3. Build Tools:

Android Studio: v.3.1.3
Android Sdk API 28 partially installed
Android Sdk API 27 installed
Android Sdk API 23 partially installed

4. `React Native` version:

0.55.4
5. `React Native Firebase` Version:

4.3.7
6. `Firebase` Module:

Messaging and Notification module, which was decriped in the docu. 

I only need to send Notifications

7. Are you using `typescript`? 

no

---
Loving `react-native-firebase`? Please consider supporting them with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by guitar9** [comment]
updated     compileSdkVersion to version 27. Now i get error cant find this things in meta in Android Manifest. So I commented out. 
Tried to run it again. Now it stucked at 0% in bundeling. 
Tried to run it with android studio get error Failed to find byte code for com/google/firebase/database/DatabaseReference$CompletionListener

Have uninstalled android studio and android sdk. Installed it again but nothing helps.

Is there a little exmaple for android? I am really frustfrustrated  :(
--

**Comment by guitar9** [comment]
yesterday i tried https://github.com/zo0r/react-native-push-notification and https://github.com/evollu/react-native-fcm but there i had issues, too and nobody answered to my issues. This is my last hope

**Comment by erandagan** [comment]
It's a bad idea to comment out (and really, make any changes) to files owned by libraries / generated by gradle.

Could you try upgrading appcompat to 27.x.x, along with setting both your compile and target versions to 27?
This should solve the missing resource error.

**Comment by Salakar** [comment]
Will close this issue as it's not specifically related to this library - feel free to continue the conversation though 👍
