### ISSUE TITLE
error.credential is null if credential-already-in-use

### ISSUE THREAD

**Issue by sowdri** [invertase/react-native-firebase#1329]
**Summary:** 

According to the docs, if the `linkWithCredential` fails, then the `error` should contain `error.credential` which should be used in the subsequent call to `signInWithCredential`, but it's null. 

**Quoted from the docs:** 

> auth/credential-already-in-use: Thrown if the account corresponding to the credential already exists among your users, or is already linked to a Firebase User. For example, this error could be thrown if you are upgrading an anonymous user to a Google user by linking a Google credential to it and the Google credential used is already associated with an existing Firebase Google user. The fields error.email, error.phoneNumber, and error.credential (AuthCredential) may be provided, depending on the type of credential. **You can recover from this error by signing in with error.credential directly via auth#signInWithCredential.**

I'm using phone auth with anonymous login. So all users are authenticated anonymously at first, and during login, are linked with the credentials created using phone number and sms code. This works fine for new mobile numbers, however when the mobile number already exists, the linking fails, and I've to `signInWithCredential` instead, which is not possible at the moment, because the `error.credential` is null. 

Any help is appreciated, 
Thanks,

**Comment by barbarosh** [comment]
@Salakar your code use exception like this https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/error_auth.js but we should get an exception like this https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/error_withcredential.js with email and credentials

**Comment by Salakar** [comment]
@barbarosh the problem at the moment is that PhoneAuthCredentials aren't serializable both ways across the bridge, at least not on Android - @sowdri and I discussed this at length on the #authentication discord channel. 

In short, we need to come up with a way of storing the token on the native side only and faking it on the JS side - with the real credential staying on native until it's consumed.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
Hey, closing this and tracking in the following PR: 

https://github.com/invertase/react-native-firebase/pull/2107

Thanks
