### ISSUE TITLE
How to check if app is connected ? 

### ISSUE THREAD

**Issue by Kris4an7** [invertase/react-native-firebase#133]
Hello,
I am trying to connect my app with the Firebase Analytics tool, but I have no idea if it's working. The library is installed good and I do get console statements, but nothing shows on my firebase account or the DebugView. 

Any tips ? I have never linked an app before with an analytics tool. 
Here is my code that should be relevant. 
In my MainContainer

```
import RNFirebase from 'react-native-firebase';

const configurationOptions = {
  errorOnMissingPlayServices: false,
};
const firebase = RNFirebase.initializeApp(configurationOptions);

console.log(firebase);

class MainContainer extends Component { 
	render() {
        firebase.analytics().setAnalyticsCollectionEnabled(true);
        firebase.analytics().setCurrentScreen('user_profile');
        firebase.analytics().setMinimumSessionDuration(0);
        firebase.analytics().setUserProperty('nickname', 'foobar');

		return (
```

**Comment by Ehesp** [comment]
Hey, if it's installed correct you should be fine. The console for analytics is far from realtime, it sometimes takes a few hours for things to show up.

**Comment by Ehesp** [comment]
@Kris4an7 I'll close this as it should be working fine. Check your console to see the events.

Let me know if they don't appear and we'll re-open.
