### ISSUE TITLE
Android actions example not working as expected

### ISSUE THREAD

**Issue by NirpE** [invertase/react-native-firebase#1330]
### Issue

Following the tutorial of Android Actions - Adding a custom button will not give proper results when action is clicked. NotificationOpen.action is not `test_action`, instead it has value `android.intent.action.VIEW`

Note: onNewIntent() in MainActivity does contain proper action for Intent.

### Environment

1. Application Target Platform:

Both

2. Development Operating System:

macOS Sierra

3. Build Tools:

Android Studio 3.1.3

4. `React Native` version:

0.54.0

5. `React Native Firebase` Version:

^4.3.0

6. `Firebase` Module:

Notifications

7. Are you using `typescript`?

No

**Comment by alnsantosh** [comment]
I am facing the same issue. 

const action=new Firebase.notifications.Android.Action('like','ic_launcher','like')
action.setShowUserInterface(true);
notification.android.addAction(action);

With the above code, I am able to add an action button to the android push notification but on clicking on a notification when the app is in the background, NotificationOpen.action is not 'like', instead it has value android.intent.action.VIEW

**Comment by alnsantosh** [comment]
@Ehesp , Please help me with this issue.

**Comment by alnsantosh** [comment]
@NirpE , Did you figure out the solution for the problem

**Comment by Salakar** [comment]
Could either of you give me a reproducible repo - it would help me debug this quicker.

**Comment by alnsantosh** [comment]
Unfortunately, I cannot provide any reproducible repo. However I followed the same instructions as per the documentation.

`// Set up your listener
firebase.notifications().onNotificationOpened((notificationOpen) => {
    // notificationOpen.action will equal 'test_action'
});

// Build your notification
const notification = new firebase.notifications.Notification()
  .setTitle('Android Notification Actions')
  .setBody('Action Body')
  .setNotificationId('notification-action')
  .setSound('default')
  .android.setChannelId('notification-action')
  .android.setPriority(firebase.notifications.Android.Priority.Max);
// Build an action
const action = new firebase.notifications.Android.Action('test_action', 'ic_launcher', 'My Test Action');
// Add the action to the notification
notification.android.addAction(action);

// Display the notification
firebase.notifications().displayNotification(notification);`

I literally followed the above snippet from the firebase documentation. However, when I click on the button, notificationOpen.action does not give me "test_action". Instead I get "android.intent.action.VIEW" as the action. This is not letting me to differentiate the button click with the notification click.
