### ISSUE TITLE
[DOC] different redirection for crashlytics setup doc

### ISSUE THREAD

**Issue by theohdv** [invertase/react-native-firebase#1333]
### Issue

On https://rnfirebase.io, if you try to access the setup documentation of crashlytics from the home page you'll access this page: https://rnfirebase.io/docs/v4.3.x/crash/ios.

**But** from the documentation page: https://rnfirebase.io/docs/v4.3.x/, if you try to access the same page, it will redirect you on: https://rnfirebase.io/docs/v4.3.x/crashlytics/ios.

The problem is that the instructions are not the same so I cannot say which is the good way to setup crashlytics.
### Environment

1. Application Target Platform: **Both**
2. Development Operating System: **macOS Sierra**
3. Build Tools: **NA**
4. `React Native` version: **0.55**
5. `React Native Firebase` **Version: 4.3.0**
6. `Firebase` Module: **Crashlytics (maybe not the only one)**
7. Are you using `typescript`? **No**

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
@theohdv Crash/Crash Reporting is the predecessor of Crashlytics - use Crashlytics, Crash is deprecated.

Thanks

**Comment by theohdv** [comment]
Ok thanks ! But you should fix the redirection from the home page.
