### ISSUE TITLE
firebase.messaging().deleteToken is not a function

### ISSUE THREAD

**Issue by weepy** [invertase/react-native-firebase#1335]
Hiya, 

firebase.messaging().deleteToken is unsupported, even though the documentation seems to mention using it. 

is there a work-around ?  This is on latest RN with up to date everything. Also on iOS. 

J

**Comment by Salakar** [comment]
@weepy you can delete token on the iid module, see the iid docs here: https://rnfirebase.io/docs/v4.3.x/iid/reference/iid#deleteToken

Will get messaging updated to point to the same method internally or have its own method as it is now clearly supported. 

Thanks for flagging :+1:

**Comment by weepy** [comment]
Thanks. Do you mean that I can delete the iid token and that will have the
same effect ?

**Comment by Salakar** [comment]
@weepy yes it should have the same effect.
