### ISSUE TITLE
Firestore onSnapshot event callback not firing

### ISSUE THREAD

**Issue by dbyilmaz** [invertase/react-native-firebase#1342]
### Environment

1. Application Target Platform: Android

2. Development Operating System:  macOS Sierra

3. Build Tools:

4. `React Native` version: 0.53.0

5. `React Native Firebase` Version: 4.3.7

6. `Firebase` Module: firestore

7. Are you using `typescript`? : no

---
This code block is not work.
```
firebase.firestore().doc(path).onSnapshot((doc) => {
// not fired here.
                console.log('some log'); // it is not seen on terminal.
});
```

`
[Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
Firestore: To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:`

Log:
```
07-25 11:49:29.819 18360 18424 W Firestore: (0.6.6-dev) [Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
07-25 11:49:29.819 18360 18424 W Firestore: To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
07-25 11:49:29.819 18360 18424 W Firestore:
07-25 11:49:29.819 18360 18424 W Firestore: FirebaseFirestore firestore = FirebaseFirestore.getInstance();
07-25 11:49:29.819 18360 18424 W Firestore: FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
07-25 11:49:29.819 18360 18424 W Firestore:     .setTimestampsInSnapshotsEnabled(true)
07-25 11:49:29.819 18360 18424 W Firestore:     .build();
07-25 11:49:29.819 18360 18424 W Firestore: firestore.setFirestoreSettings(settings);
07-25 11:49:29.819 18360 18424 W Firestore:
07-25 11:49:29.819 18360 18424 W Firestore: With this change, timestamps stored in Cloud Firestore will be read back as com.google.firebase.Timestamp objects instead of as system java.util.Date objects. So you will also need to update code expecting a java.util.Date to instead expect a Timestamp. For example:
07-25 11:49:29.819 18360 18424 W Firestore:
07-25 11:49:29.819 18360 18424 W Firestore: // Old:
07-25 11:49:29.819 18360 18424 W Firestore: java.util.Date date = snapshot.getDate("created_at");
07-25 11:49:29.819 18360 18424 W Firestore: // New:
07-25 11:49:29.819 18360 18424 W Firestore: Timestamp timestamp = snapshot.getTimestamp("created_at");
07-25 11:49:29.819 18360 18424 W Firestore: java.util.Date date = timestamp.toDate();
07-25 11:49:29.819 18360 18424 W Firestore:
07-25 11:49:29.819 18360 18424 W Firestore: Please audit all existing usages of java.util.Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.
07-25 11:49:29.887 18360 18438 W linker  : /data/app/com.google.android.gms-2/base.apk!/lib/x86/libconscrypt_gmscore_jni.so: unused DT entry: type 0xf arg 0x119
```

**Comment by Nima104** [comment]
Are you somehow changing the fields of the document specified by path? 

firebase.firestore().doc(path).onSnapshot(callback) creates an event listener that only fires when you change any fields on that doc. From the guides: 

> You can listen to a document with the onSnapshot() method. An initial call using the callback you provide creates a document snapshot immediately with the current contents of the single document. Then, each time the contents change, another call updates the document snapshot."

[https://firebase.google.com/docs/firestore/query-data/listen](url)

**Comment by Ehesp** [comment]
Hi @dbyilmaz could you show us any security rules around the `path` and also what data is at the `path` (please remove anything sensitive but keep the types, e.g. a date).

Our tests are passing for this so just want to see if we can replicate an edge case.

Cheers

**Comment by dbyilmaz** [comment]
@Ehesp Problem is security rules.  I edited security rules then work. Thanks @Ehesp 👍
