### ISSUE TITLE
Phone Verification

### ISSUE THREAD

**Issue by abburi03** [invertase/react-native-firebase#1347]
Hi, 

I am trying to just very phone using the library (Not provider linking) .  Do you support this feature?

**Comment by Salakar** [comment]
@abburi03 hi, yes we do, please see the following documentation: https://rnfirebase.io/docs/v4.3.x/auth/phone-auth#verifyPhoneNumber

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by krishnaraghavendra** [comment]
@Salakar I tried doing that but how to verify code. I was able to send code to user and i have access to verificationID. Now how to check if code is valid.  There is no clear documentation for that
