### ISSUE TITLE
possible to make app size smaller?

### ISSUE THREAD

**Issue by guitar9** [invertase/react-native-firebase#1349]
I only use Messaging, Admob and Notification. My Android app has a size of 27,21 MB only with this implementation with firebase. Is this normal? Can i make i smaller?

**Comment by Salakar** [comment]
Please don't post the same issue multiple times. You've also created this same issue on the starter repo.

Also please ask questions like this on Discord - the GitHub issues are generally for bug reports.

Thank you.
