### ISSUE TITLE
onshapshot() or get() both method not work....in firestore

### ISSUE THREAD

**Issue by ektasahu027** [invertase/react-native-firebase#1350]
apply plugin: "com.android.application"

import com.android.build.OutputFile

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.2"

    defaultConfig {
        applicationId "com.inquirr.inquirr"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
          multiDexEnabled true
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-localization')
compile project(':react-native-input-picker')
    compile project(':react-native-image-picker')
    compile project(':react-native-video')

  compile(project(':react-native-firebase')) {
         transitive = false
     }
       compile 'com.android.support:multidex:1.0.0'
        compile "com.google.android.gms:play-services-base:15.0.0"
     compile "com.google.firebase:firebase-core:15.0.0"
     compile "com.google.firebase:firebase-analytics:15.0.0"
        compile "com.google.firebase:firebase-auth:15.0.0"
        compile 'com.google.firebase:firebase-database:15.0.0'
          compile 'com.google.firebase:firebase-storage:15.0.0'
          compile 'com.google.firebase:firebase-firestore:15.0.0'
 

    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:27.0.2"
    compile 'com.facebook.react:react-native:+'

}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
 apply plugin: 'com.google.gms.google-services'

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
           classpath 'com.google.gms:google-services:3.1.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
      
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}

versions are

  "native-base": "^2.7.1",
    "react": "16.3.2",
    "react-native": "0.55.4",
    "react-native-firebase": "^4.1.0",

error
com.google.firebase.firestore.Metadata changes
didn't find class com.google.firebase.firestore.componentsGet
didn't find class com.google.firebase.firestore.componentsonSnapshpt

**Comment by Salakar** [comment]
Please correctly format your code snippets and also please provide an actual error stack using the android ADB logs as it's not clear what your issue is here? 

Will re-open once it's been updated and you reply here. 

Thanks
