### ISSUE TITLE
[ios][notifcation/messaging]FIRInstanceIDLogger formatMessageCode EXC_BAD_ACCESS KERN_PROTECTION_FAILURE 

### ISSUE THREAD

**Issue by dluksza** [invertase/react-native-firebase#1352]
### Issue

After migrating notifications in my app from `react-native-notification` to `react-native-firestore` I've started seeing strange issue on iOS. Don't have any clue why it is happening. Apart from changing this -middleware- library nothing else has changed. I'm still using the same texts in messages. But from time to time this error popup in crshlytics:

` +[FIRInstanceIDLogger formatMessageCode:] EXC_BAD_ACCESS KERN_PROTECTION_FAILURE`

See attached [crash_log.txt](https://github.com/invertase/react-native-firebase/files/2236859/crash_log.txt) for detailed information.

I've enabled `Push Notifications` in app `Capabilities`, also configured certificates and APNs but this is still occurring.

Right not I'm clue less, don't even know where to start looking for help. Therefore before contacting `firebase-ios-sdk` team I've figured that maybe you guys can help me. Maybe this is simple miss configuration or something easy to fix.

### Environment

1. Application Target Platform:

iOS

2. Development Operating System:

macOS

3. Build Tools:

not relevant

4. `React Native` version:

0.56.0

5. `React Native Firebase` Version:

4.3.8

6. `Firebase` Module:
```
  pod 'Firebase', '~> 5.4.0'
  pod 'Firebase/Core', '~> 5.4.0'
  pod 'Firebase/Auth', '~> 5.4.0'
  pod 'Firebase/Analytics', '~> 5.4.0'
  pod 'Firebase/Firestore', '~> 5.4.0'
  pod 'Firebase/Performance', '~> 5.4.0'
  pod 'Firebase/RemoteConfig', '~> 5.4.0'
  pod 'Firebase/Messaging', '~> 5.4.0'
```
7. Are you using `typescript`?

yes

**Comment by Salakar** [comment]
@dluksza I can only suggest based on the stack trace that it'd be best flagging this issue up on the `firebase-ios-sdk` repo - the stack trace points to only the iOS sdk internals. 

Sorry if that's not very helpful. 🙈 Do tag this issue if you post an issue over there so people can follow it through.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by dluksza** [comment]
This is helping a bit. Thank you for your time :)

**Comment by vikasatappinlay** [comment]
any reference for solution ?

**Comment by renan-5by5** [comment]
@VikasReactNative Did you find a solution?

I'm having a similar error and I can't find a solution, when I click on the push notification the app opens and crashes. Putting debug, I noticed that it pings several times in the userNotificationCenter method, in my test it must have pinged about 15 times, after that I removed the breakpoint and the app crashed
