### ISSUE TITLE
[Android RN 0.52 - v4.3.8] Promise never return on call firestore.set and firestore.update

### ISSUE THREAD

**Issue by joaom182** [invertase/react-native-firebase#1354]
### Issue

The follow code only fire `console.warn('Saving...')` in Android.
On iOS works fine, fire `console.warn('Saving...')` and `console.warn('Saved')`

```javascript
console.warn('Saving...')
firestore.doc('docpath').set(docPayload, { merge: true }).then(function(){
   console.warn('Saved')
}).catch(function(err){
   console.warn('error ' + err.toString())
})
```

### Environment

1. Application Target Platform:
Android

2. Development Operating System:
macOS HighSierra

3. Build Tools:
--

4. `React Native` version:
0.52.0

5. `React Native Firebase` Version:
4.3.8

6. `Firebase` Module:
Firestore

7. Are you using `typescript`?
No

**Comment by Ehesp** [comment]
Thanks for the report. Do you have any specific security rules which may be effecting it?

Our tests for this are passing, however I'll check it manually - if that works, a reproducible project may come in handy!

**Comment by joaom182** [comment]
What specifically do you mean by security rules?

**Comment by Ehesp** [comment]
On the Firebase console, you have anything specific in here:

![image](https://user-images.githubusercontent.com/842078/43463110-c16db2fc-94cf-11e8-9050-1f1a47c3a5b6.png)

**Comment by joaom182** [comment]
@Ehesp nop

**Comment by Ehesp** [comment]
@joaom182 thanks for checking. I'll check this out - there's currently some background work going on with Firestore for another issue which has required a few changes so I'll speak with Salakar on that.

**Comment by jedashford** [comment]
I had the same problem, no get() promise would ever resolve on Android. The starter project references com.google.gms:google-services:4.0.1 . Apparently this version has issues finding the google-services.json file. You'll need to update to com.google.gms:google-services:4.0.2 in your android/build.gradle . I highly suggest a maintainer make this simple change and push it to master ASAP.

https://stackoverflow.com/questions/47565761/gradle-warnings-could-not-find-google-services-json-while-looking-in
