### ISSUE TITLE
Notifications are not gone when I clicked them

### ISSUE THREAD

**Issue by Bang9** [invertase/react-native-firebase#1359]
### Issue
I'm using now only using onMessage to display custom notification.
Everything works fine(foreground/background/closed), but delivered(in status bar) notifications are not disappear when I clicked them(app is going to open)
How can I kill them when I clicked👿

Is there other notification option that I dont know?
or have I to use onNotificationOpened with removeDeliveredNotification in my app root?

Im waiting for reply thank you
p.s. I love rnfirebase😘

### Environment

1. Application Target Platform:
 android

2. Development Operating System:
Win10

3. Build Tools:
Latest version of Android Studio

4. React Native version:
0.55.4

5. RNFirebase Version:
4.2.x

6. Firebase Module:
Notifications

**Comment by 8BallBomBom** [comment]
Are you using the setAutoCancel android option?
If not have a look here.
https://rnfirebase.io/docs/v4.3.x/notifications/reference/AndroidNotification#setAutoCancel
`notification.android.setAutoCancel( true );`

**Comment by Bang9** [comment]
Oh crap I missed that options, thx so much!

**Comment by Salakar** [comment]
@Bang9 thanks for the love 👍 

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
