### ISSUE TITLE
Firebase Performance Monitoring

### ISSUE THREAD

**Issue by mikelambert** [invertase/react-native-firebase#136]
Looks like Firebase just added Performance Monitoring APIs: https://firebase.googleblog.com/2017/05/introducing-firebase-performance.html

This is a tracking bug for the eventual addition of such APIs to react-native-firebase.

Looks like they offer automatic tracking of various App behaviors (startup, background, foreground), as well as tracking of HTTP/S requests (unclear if it'll catch RN fetches).

The described APIs are basically as follows:
https://firebase.google.com/docs/reference/android/com/google/firebase/perf/FirebasePerformance
https://firebase.google.com/docs/reference/android/com/google/firebase/perf/metrics/Trace
...along with an `@AddTrace` decorator for easily tracking a function's performance (which could work in JS too).

**Comment by Salakar** [comment]
See #130.

**Comment by mikelambert** [comment]
Oh woops, thanks!
