### ISSUE TITLE
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by digrase008** [invertase/react-native-firebase#1360]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-firebase.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-firebase: None of the consumable configurations have attributes.

While creating built it's working fine but when it comes to run the built that is after performing react-native run-android I am getting built got failed with the above message 

Here is my built.gradle : 

buildscript {
    repositories {
         google()
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'com.google.gms:google-services:4.0.0'
        // classpath 'com.google.gms:google-services:3.2.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}

ext {
    buildToolsVersion = "27.0.3"
    minSdkVersion = 16
    compileSdkVersion = 27
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}

**Comment by Ehesp** [comment]
Have you run the link command? Seems as though it hasn't installed properly. E.g. check https://github.com/invertase/react-native-firebase-starter/blob/master/android/settings.gradle#L2 and other files for comparison.

**Comment by digrase008** [comment]
yup I have run the link command also still stuck at the same stage from
last 2 days please help me out

**Comment by jozan** [comment]
I solved this exact same problem by moving `google()` repository at the top of the list.

build.gradle
```
allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

**Comment by Usamashahid76** [comment]
Remove compile('react-native-fetch-blob') from build.gradle from android folder

**Comment by SilajitBukaiSil** [comment]
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-app-auth.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-app-auth: None of the consumable configurations have attributes.

**Comment by SilajitBukaiSil** [comment]
Can anyone please tell me how to solve this issue? I already tried with ./gradlew clean in android, also delete node module and then npm install and run in android. Nothing work. Please help if any body know any other way. Thanks in advance!

**Comment by pacozaa** [comment]
@SilajitBukaiSil Got the same problem. Do you know how to solve this?

**Comment by Fatima758** [comment]
@SilajitBukaiSil
i have same problem. did you solve that?

**Comment by Usamashahid76** [comment]
1st method,
Also remove the import of react-native-fetch-blob in any screen 

yarn remove (respective command ** for instance react-native-fetch-blob)
Then go to 
android/build.gradle  and remove the line of compile(react-native-fetch-blob) 
Then go to 
main/src/java/mainactivity.java
And remove the import and line containing react-native-fetch-blob
Then finally
Command line
cd android
gradlew clean
cd..
react-native run-android

2nd method
remove node modules
npm install
cd android 
gradlew clean
cd..
react-native run-android

3rd method 
remove build folder from android 
and then compile again

**Comment by mikehardy** [comment]
Everyone, first, try react-native-clean-project and after installing it run `react-native clean-project-auto` - second, if you still have an issue open a new issue and follow the template thoroughly please
