### ISSUE TITLE
With Phone Auth, reCaptcha page on the safari turns blank after checking

### ISSUE THREAD

**Issue by viniciusfont** [invertase/react-native-firebase#1363]
### Issue

Only on iOS, using the **Phone Auth**, the _reCaptcha_ page on the safari turns blank after checking and does not return to the application.

I have been developing this application for 1 month, successfully logging on several times, and only today when I arrived at the office did the problem begin.

I already configured another GoogleService-Info.plist and the URL in Xcode.

### Environment

1. Application Target Platform:

iOS

2. Development Operating System:

macOS High Sierra 10.13.6

3. Build Tools:

Xcode Version 9.4.1 (iPhone 6s)
react-native run-ios (simulator)

4. `React Native` version:

"react-native": "0.56.0"

5. `React Native Firebase` Version:

"react-native-firebase": "4.2.0"

6. `Firebase` Module:

Auth (Phone Auth)

7. Are you using `typescript`?

no

---

**Comment by handu** [comment]
@viniciusfont Having the same issue, but only running on device. It works for me in the simulator ("react-native-firebase": "4.2.0", "react-native": "0.50.3")

**Comment by viniciusfont** [comment]
@handu Did the problem start today?

**Comment by handu** [comment]
@viniciusfont Yes, but it works for me now, I guess it was a tmp glitch in firebase service?

**Comment by viniciusfont** [comment]
@handu It worked, apparently it was a temporary problem indeed. I was losing my mind already! =D

**Comment by hadare1** [comment]
I now have the same issue : 
podfile : 

    pod 'Firebase/Core', '~> 6.3.0'
    pod 'Firebase/Auth', '~> 6.3.0'

react versions: 
    "react-native": "^0.59.9",
    "react-native-firebase": "^5.3.1",

**Comment by mikehardy** [comment]
I don't think that's a supported version combination https://rnfirebase.io/docs/v5.x.x/getting-started#Supported-versions---React-Native-/-Firebase

**Comment by hadare1** [comment]
I downgraded my pod to this : 

    pod 'Firebase/Core', '~> 5.15.0'
    pod 'Firebase/Auth', '~> 5.15.0'

**Comment by yoavapi** [comment]
I have the same issue

**Comment by viniciusfont** [comment]
> I have the same issue

Apparently it is a temporary problem with Firebase services

**Comment by ianlenehan** [comment]
This has been a problem for me for about two weeks. I really don't think I've changed anything relevant but I actually can't log into my app anymore and it's super frustrating. 

FWIW it's probably not something wrong with this package but I have no idea what's going on. It just goes to "about: blank". I upgraded from `"react-native-firebase": "~5.5.6",` to "@react-native-firebase/app": "^7.2.1", "@react-native-firebase/auth": "^8.0.5",` without any luck.

**Comment by mikehardy** [comment]
Has something changed about the URLs for callback configured between firebase console / apple developer connection / plist? If I think through exactly which systems have control at that moment I think it's those systems, e.g. CFBundleURLSchemes in your plist. Just a hunch tho

**Comment by jonasmedeiros** [comment]
Hi Guys I had this error on my Emulator was really annoying but I got a colleague that fixed on ios side, just need to add to ios/{project}/AppDelegate.m  this code 

```
-(BOOL) application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return YES;
}
```

**Comment by rayhk6** [comment]
> -(BOOL) application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
>   return YES;
> }

It works. Really appreciate it!

**Comment by devpascoe** [comment]
Fresh install RN 0.75.3 and i needed to implement @jonasmedeiros method on AppDelegate for it to work on iOS. Weird.

**Comment by hashhirr** [comment]
> Hi Guys I had this error on my Emulator was really annoying but I got a colleague that fixed on ios side, just need to add to ios/{project}/AppDelegate.m this code
> 
> ```
> -(BOOL) application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
>   return YES;
> }
> ```
> 
> This will make the fix when get back from safari.

thanks man your a life saver

**Comment by Vimal1464** [comment]
> Hi Guys I had this error on my Emulator was really annoying but I got a colleague that fixed on ios side, just need to add to ios/{project}/AppDelegate.m this code
> 
> ```
> -(BOOL) application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
>   return YES;
> }
> ```
> 
> This will make the fix when get back from safari.

You and your colleague are greatest

**Comment by Bilal-Abdeen** [comment]
> Hi Guys I had this error on my Emulator was really annoying but I got a colleague that fixed on ios side, just need to add to ios/{project}/AppDelegate.m this code
> 
> ```
> -(BOOL) application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
>   return YES;
> }
> ```
> 
> This will make the fix when get back from safari.

Excellent solution. Thank you so much. If anyone is interested in a swift version of the fix:
```swift
@main
class AppDelegate: RCTAppDelegate {
  // ........

  // add the following:
  override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any]) -> Bool {
      return true
  }
}
```

**Comment by arjunchopra35** [comment]
> > Hi Guys I had this error on my Emulator was really annoying but I got a colleague that fixed on ios side, just need to add to ios/{project}/AppDelegate.m this code
> > ```
> > -(BOOL) application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
> >   return YES;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will make the fix when get back from safari.
> 
> Excellent solution. Thank you so much. If anyone is interested in a swift version of the fix:
> 
> @main
> class AppDelegate: RCTAppDelegate {
>   // ........
> 
>   // add the following:
>   override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any]) -> Bool {
>       return true
>   }
> }

You sir, Are a legend.

**Comment by syedumair043** [comment]
firebase phone auth give me blank screen after recaptcha

I am using these

    "@react-native-firebase/app": "^21.13.0",
    "@react-native-firebase/auth": "^21.13.0",

I have tested the latest version aswell but its giving me same behaviour
