### ISSUE TITLE
onNotificationOpened not working at iOS 11

### ISSUE THREAD

**Issue by dominicsavb** [invertase/react-native-firebase#1364]
### Environment

1. Application Target Platform:

iOS

2. Development Operating System:

macOS High Siera

3. Build Tools:

iOS 11

4. `React Native` version:

0.55.4

5. `React Native Firebase` Version:

4.2.0

6. `Firebase` Module:

notification

7. Are you using `typescript`?

no

---

When I'm using local notification, and I used onNotificationOpened to know when notification is tapped and app is at background (not closed, and not at foreground). But why when I tapped notification, cannot catch by onNotificationOpened... it is Ok at android, but not working at iOS. What's wrong with this?

Thank you

**Comment by dominicsavb** [comment]
Solved. The problem is found. I solved it with delete react-native-fcm configuration.

**Comment by dominicsavb** [comment]
Not triggered when app at foreground and background...

**Comment by alifarooq96** [comment]
Hello @dominicsavb ,

I am running into the same issue that you have described. Can you please provide more information on how you resolved the issue? I have already removed the FCM configuration from AppDelegate.m. Am I missing something?

I removed these lines however it doesn't seem to make any difference:
`
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
  [[RNFirebaseMessaging instance] didRegisterUserNotificationSettings:notificationSettings];
}

-(void) userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler {

  [[RNFirebaseMessaging instance] didReceiveRemoteNotification:response.notification.request.content.userInfo];
  completionHandler();
}
`
