### ISSUE TITLE
React native firebase and standart firebase library onAuthStateChanged outputs different info.

### ISSUE THREAD

**Issue by berpcor** [invertase/react-native-firebase#1365]
Hello.

```
import * as firebase from 'firebase';

const config = {
};

firebase.initializeApp(config);

firebase.auth().onAuthStateChanged((user) => {
            if(user){
                console.log('AUTH-YES', user);
            }else {
                console.log('AUTH-NO', user);
            }
 });

```
In case above i get AUTH-NO while

```
import firebase from 'react-native-firebase';

firebase.auth().onAuthStateChanged((user) => {
            if(user){
                console.log('AUTH-YES', user);
            }else {
                console.log('AUTH-NO', user);
            }
 });

```
outputs AUTH-YES after app loading.
Is it normal?

**Comment by Salakar** [comment]
@berpcor yes that is correct - the Native SDKs persist authentication - even after an uninstall and reinstall of the app in some cases. If you need there to be no auth then you'll need to log out the user.

Hope that helps.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
