### ISSUE TITLE
Android realtime database fetching forever

### ISSUE THREAD

**Issue by LucasBassetti** [invertase/react-native-firebase#1366]
Hi,

My realtime database stops working in Android suddenly. No every simple query that I do the promise never return a result (gets stuck forever). Example:

```
firebase.database().ref(SOME_PATH).once('value').then((snapshot) => {
  console.log(snapshot.val());
}).catch((error) => {
  console.log(error);
});
```

The strange part that I didn't do nothing. It just stop working (iOS works fine). I tried a lot of stuffs to fix it:
- Update react-native-firebase
- Update android package from `12.0.0` to `16.0.1`
- Downgrade to a branch on github that I'm absolutely sure it was working
- Clean cache
- Reinstall the app
- Install in different devices

Unfortunately nothing worked.

### Environment

1. Application Target Platform:

Android

2. Development Operating System:

macOS High Sierra 10.13.6

3. Build Tools:

Android SDK version

4. `React Native` version:

`0.55.2`

5. `React Native Firebase` Version:

Tried with `4.0.7` `4.1.0` and `4.3.8`

6. `Firebase` Module:

database

7. Are you using `typescript`?

no

I appreciate any feedback about this.

**Comment by LucasBassetti** [comment]
Believe or not the problem was fixed after I restarted my mac 😞

**Comment by Salakar** [comment]
Ah the old "Have you tried turning it off and on again" trick 😄
