### ISSUE TITLE
RNFIRMessaging.h not found 

### ISSUE THREAD

**Issue by VKGraphics** [invertase/react-native-firebase#1367]
I used
"react-native": "0.55.4",
"react-native-firebase": "^4.3.8",
 
I follow [medium](https://medium.com/the-modern-development-stack/react-native-push-notifications-with-firebase-cloud-functions-74b832d45386)

I add this line on my AppDelegate.m
`#import "RNFIRMessaging.h"`

after I found out header file change to `RNFirebaseMessaging.h`

but its still throw an error.

**Comment by Salakar** [comment]
@VKGraphics that medium article is for a very old version of this library. Please use the setup docs here: https://rnfirebase.io/docs/v4.3.x/notifications/ios

Thanks

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by AbhiShrek** [comment]
The latest RNFirebase official docs have a link to this "old" medium post.
And there is no other document to describe how to configure the Appdelegate.m file with RNFirbase.

If there is any, can you please mention it here ?

![Screenshot 2019-05-04 at 10 09 39 AM](https://user-images.githubusercontent.com/11253347/57173995-1f6ca480-6e55-11e9-8229-dd797a110d82.png)
