### ISSUE TITLE
GoogleService-Info.plist is not added to .xcworkspace automatically.

### ISSUE THREAD

**Issue by mikeywaites** [invertase/react-native-firebase#1370]
### Environment

1. Application Target Platform:

ios

2. Development Operating System:

macOs Sierra

3. Build Tools:

Version 9.2 (9C40b)

4. `React Native` version:
"react-native": "~0.55.2",

5. `React Native Firebase` Version:
"react-native-firebase": "^4.3.8"

6. `Firebase` Module:
database, auth, messaging

7. Are you using `typescript`?
no

---

After many agonising attempt I finally managed to port a slightly old react native app to more recent version.  During this process i had a total nightmare getting my project to work with react-native-firebase and I finally found the cause.

My project would compile without errors but as soon as the app loaded on the simulator it would immediately crash.  I trawled through logs and didn't find anything that showed why the app was crashing.  (at least i didn't see and perhaps i just missed something obvious)

I eventually found this comment from another project https://github.com/firebase/firebase-ios-sdk/issues/340#issuecomment-334825911 and Eureka! the app now loads correctly.

I wanted to report this because it's really not clear in from the setup guide here.  Once I found the issue I went back to the docs and only knowing what i was looking for did i spot the key parts.

"Make sure that the GoogleService-Info.plist file has **been added to your project within XCode**."

Even Firebase's docs aren't clear on this manual step https://firebase.google.com/docs/ios/setup#add_firebase_to_your_app

Sorry if i logged this as a bug and it should be a feature request.  Thanks for the awesome work on this project 🤘

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
@mikeywaites welcome 🎉 

You're right, the docs aren't overly specific, they could do with a mini guide I guess - will get something more specific/detailed added to the docs for the v5 release.

Will close this for now - am tracking internally 👌
