### ISSUE TITLE
Realtime Database Promise not resolving

### ISSUE THREAD

**Issue by toytonic** [invertase/react-native-firebase#1373]
### Issue

Promise never returns a value. The following statement never resolves with any value since my update to the latest libs:

```
const userRef = firebaseDb.ref(`user/${uid}/info`);
const userInfo = await userRef.once('value');
```

Same for remote config. Can't fetch or activate any values.

### Environment

1. Application Target Platform:

Android

2. Development Operating System:

macOS Sierra, 10.13.6

3. Build Tools:

SDK 26

4. `React Native` version:

0.56

5. `React Native Firebase` Version:

4.3.8

6. `Firebase` Module:

database, remote config

7. Are you using `typescript`?

yes

**Comment by Ehesp** [comment]
Make sure you give the emulator a restart first of all, sometimes it seems to disconnect and doesn't connect.

Second, are you checking to see if any error is thrown?

**Comment by toytonic** [comment]
Yes, I did both. Even restarted my mac after reading about this in a similar issue. Will update and check iOS today and see if it works there.

**Comment by Ehesp** [comment]
Hmm - Can you check any security rules you have? They could be blocking the request and the error isn't flagging

**Comment by toytonic** [comment]
I'm not aware of having changed any of them:

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
<uses-permission android:name="android.permission.VIBRATE" />
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

BTW: iOS works after upgrading.

**Comment by Ehesp** [comment]
Sorry, I meant on the Firebase console, does `user/${uid}/info` have anything which may be stopping the request going through?

**Comment by toytonic** [comment]
Really strange behavior which I haven't figured out completely. But I was able to fetch/set the data after resetting the user node in the firebase console. So it should not be related to react-native-firebase in general.

Still strange that iOS was working flawless. Will close the issue now and report back, once I find out more. Thanks a lot for trying to help anyways.

**Comment by Euklidian-Space** [comment]
> Really strange behavior which I haven't figured out completely. But I was able to fetch/set the data after resetting the user node in the firebase console. So it should not be related to react-native-firebase in general.
> 
> Still strange that iOS was working flawless. Will close the issue now and report back, once I find out more. Thanks a lot for trying to help anyways.

Hey @toytonic.  I am having this exact same issue.  Could explain your solution a bit more clearly?  Not entirely sure what you mean by "reset user node in firebase console"

Thanks

**Comment by Luiyit** [comment]
> > Really strange behavior which I haven't figured out completely. But I was able to fetch/set the data after resetting the user node in the firebase console. So it should not be related to react-native-firebase in general.
> > Still strange that iOS was working flawless. Will close the issue now and report back, once I find out more. Thanks a lot for trying to help anyways.
> 
> Hey @toytonic. I am having this exact same issue. Could explain your solution a bit more clearly? Not entirely sure what you mean by "reset user node in firebase console"
> 
> Thanks

I had the same issue, I was able to solve it in this way
https://gist.github.com/Luiyit/43ad2106ebf22dcf944a4f1a0407448a
