### ISSUE TITLE
How to use crashlytics??

### ISSUE THREAD

**Issue by sarathvad1811** [invertase/react-native-firebase#1375]
There's no proper documentation how to use crashlytics... Please provide a proper documentation on how to use that.... 
TIA

**Comment by Ehesp** [comment]
Crashlytics works out of the box once installed, and will automatically show any crashes a user experiences on console. 

If you'd like to force your own, you can use the methods here: https://rnfirebase.io/docs/v4.3.x/crashlytics/reference/crashlytics

E.g:

```
firebase.crashlytics().crash();
```

**Comment by Ehesp** [comment]
Anywhere in your app's lifecycle. For example right in the `componentDidMount` of your "root" component, or even outside of a component. As long as you set any values as soon as you're able to, they'll get sent with any subsequent crash reports.

**Comment by JMV2112** [comment]
Per the comment mentioned by @dantn93 is also happening on a physical device.

**Comment by ammoradi** [comment]
any news about this?

**Comment by pguatura** [comment]
If you are using the method mentioned above, it throws the reported crash. That method is used to test if the reports are getting to the dashboard. The documentation https://rnfirebase.io/docs/v5.x.x/crashlytics/reference/crashlytics shows some methods to track non-fatal errors.
