### ISSUE TITLE
Notifications launchMode

### ISSUE THREAD

**Issue by marcoschicote** [invertase/react-native-firebase#1377]
Hi
I'm just getting started with RN Native Firebase an RN and I'm having trouble installing the library. I'm trying to use Notifications. The installation guide for Notifications says that I need to set the `launchMode` to `singleTop`. However, for compatibility with other libraries I need to keep the `launchMode` for `MainActivity` in `singleTask`. Can I use another activity with Notifications?

Thanks for your help!

**Comment by appli-intramuros** [comment]
same problem. Did you find any solution ? @marcoschicote

**Comment by marcoschicote** [comment]
Not yet @appli-intramuros

**Comment by peteroid** [comment]
I got the same issue. The RN Linking document suggests to set launchMode="singleTask" but the RNF Notification document suggests launchMode="singleTop". I just chose "singleTask" as there is a weird behavior for the Linking when the launchMode="singleTop". Can anyone advice what's the best practice?

**Comment by malithjkmt** [comment]
Contradicting setup instructions

for react-native-firebase notifications it says to use `android:launchMode="singleTop"`
official doc: https://rnfirebase.io/docs/v5.x.x/notifications/android 

for react-native-firebase dynamicLinks it says to use `android:launchMode="singleTask"`
official doc: https://rnfirebase.io/docs/v5.x.x/links/android 

What should we do if we are to use both notifications and dynamic links?

**Comment by artshevtsov** [comment]
I changed `singleTop` to `singleTask` launch mode for my app because RN App's constructor calls multiple times if I receive a lot of intents on android. So all event listeners, for example AppState change event with async actions inside it runs as many times as how much tasks/intents started.

**Comment by thuongtv-vn** [comment]
@malithjkmt 
Have you got the answers?
