### ISSUE TITLE
App receives dynamic links when run in debug scheme but not when run in release scheme

### ISSUE THREAD

**Issue by haseebnaseem** [invertase/react-native-firebase#1379]
### Issue

I have integrated the dynamic links sdk using react-native firebase. I tested the deep links by opening the url by tapping on them in a text message which lead to a screen displaying my apps name and the information along with the open button. Tapping the open button took me to the app store's page for my application. I then installed the app using xcode in a debug scheme. The dynamic link was received correctly and everything worked fine. I then did the same process but changed the scheme to release. This time the url received was unfortunately null. I have debugged the native code as well and can see that `dynamicLinkFromCustomSchemeURL:url` contains the correct deep link in debug scheme but not in release scheme. 

Here is my pod file:
```
2 platform :ios, '9.0'
  3 
  4 target 'paitoo' do
  5   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  6   # use_frameworks!
  7 
  8   # Pods for paitoo
  9   rn_path = '../node_modules/react-native'
 10   pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
 11   pod 'React', path: rn_path, subspecs:[
 12     'Core',
 13     'RCTActionSheet',
 14     'RCTAnimation',
 15     'RCTGeolocation',
 16     'RCTImage',
 17     'RCTLinkingIOS',
 18     'RCTNetwork',
 19     'RCTSettings',
 20     'RCTText',
 21     'RCTVibration',
 22     'RCTWebSocket'
 23   ]
 24   pod 'AppCenter/Crashes', '~> 1.3.0'
 25   pod 'AppCenter/Analytics', '~> 1.3.0'
 26   pod 'AppCenterReactNativeShared', '~> 1.2.0'
 27   pod 'Google/SignIn'
 28   pod 'Firebase/Core', '~> 4.13.0'
 29   pod 'Firebase/Messaging'
 30   pod 'Firebase/DynamicLinks'
 31 end
 32 post_install do |installer|
 33   installer.pods_project.targets.each do |target|
 34     if target.name == "React"
 35       target.remove_from_project
 36     end
 37   end
 38 end

```
### Environment

1. Application Target Platform: ios

2. Development Operating System: macOS High Sierra v10.13.6 

3. Build Tools: Xcode v9.4.1 , iOS v11.4.1

4. `React Native` version: 0.49.5

5. `React Native Firebase` Version: 4.2.0

6. `Firebase` Module: links

7. Are you using `typescript`? no

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by IcebergRage** [comment]
Hey,

I have the same problem here, any solutions ?

**Comment by haseebnaseem** [comment]
@IcebergRage Unfortunately no. Do let me know if you find something, I have not been able to make it work.

**Comment by IcebergRage** [comment]
@haseebnaseem I found the problem:

I had two Codes Signing Entitlements.
so the `myCodeSigningRelease.entitlements` doesn't have the associated domains.
You can check it in Target > Build Settings > Code Signing Entitlements

Hope it helps.

**Comment by Harleymckee** [comment]
I am having this issue. The links are working great in Debug mode.
In release linking works when the app is 1. in the foreground 2. in the background
but 3. does not work when going through the download flow.

**Comment by karanwadhwa** [comment]
exact same issue as @Harleymckee were you able to find a solution for this?

**Comment by mikehardy** [comment]
That was 3.5 months ago, and 11 versions of firebase-ios-sdk ago. I'd open a new issue after making sure all your versions were up to date (including an override to iOS pod 6.32.0 - overriding is like this https://rnfirebase.io/#ios ) and providing an App.js that reproduces the problem
