### ISSUE TITLE
Multiple plist in IOS

### ISSUE THREAD

**Issue by lazyhoneyant** [invertase/react-native-firebase#138]
I have multiple GoogleService-Info.plist.
The one is for developing, and The other one is for production.
So I've changed the following codes in RNFirebase.xcodeProj/Modules/RNFirebase.m

**(before)**
NSString *plistPath = [[NSBundle mainBundle] pathForResource:@"GoogleService-Info" ofType:@"plist"];

**(after)**
       NSString *plistPath;

        
            #ifdef DEBUG
        
            plistPath = [[NSBundle mainBundle] pathForResource:@"GoogleService-Info-dev" ofType:@"plist"];
        
            #else
        
            plistPath = [[NSBundle mainBundle] pathForResource:@"GoogleService-Info" ofType:@"plist"];
        
            #endif
        

but, This code is not working. Simulator always " import GoogleService-Info.plist ".
Am I wrong? how Can I do that?

**Comment by lazyhoneyant** [comment]
I solved this problem by myself.
I was trying to edit the codes in /rootProject/ios/~~ NOT /node_modules/react-native-firebase/~~.

**Comment by ugiacoman** [comment]
@lazyhoneyant Does this get overwritten everytime you re-install your `node_modules`? I'm looking to do the same!

**Comment by ugiacoman** [comment]
I think I figured it out. In your `AppDelegate.m`, you can set the path to your plist and configure firebase based on that plist.

```
NSString *filePath = [[NSBundle mainBundle] pathForResource:@"GoogleService-Info" ofType:@"plist"];
FIROptions *options = [[FIROptions alloc] initWithContentsOfFile:filePath];
[FIRApp configureWithOptions:options];

```
Reference:
https://stackoverflow.com/a/39451163/4615629
