### ISSUE TITLE
child_added event fires when updating

### ISSUE THREAD

**Issue by phihungnv** [invertase/react-native-firebase#1380]
Hi all,

Anyone faces this problem and know how to fix ? 

`ref().once('value', snapshot => {
            this.afterGetFirebaseData(snapshot)
        })`
`ref().on('child_added', (childSnapshot) => {
//
        })`

Thanks

Environment
Application Target Platform: Both

Development Operating System: macOS Sierra

React Native version: 0.55.4

React Native Firebase version: 4.2.0

Firebase Module: Database

**Comment by Salakar** [comment]
@phihungnv you've not provided an actual error or issue here? Given how long ago this was I'm going to close this issue.

If you're still having a problem please make a detailed issue with an error or description of the issue you're facing.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
