### ISSUE TITLE
Error merging two existing accounts

### ISSUE THREAD

**Issue by ygomezfinale** [invertase/react-native-firebase#1385]
following this guide: https://firebase.google.com/docs/auth/web/account-linking In my web app I was able to merge two accounts into one with no problem, but when I try to do the same in my mobile app:

//action to recover from the auth/credential-already-in-use
// Get reference to the currently signed-in user
const { currentUser } = firebase.auth();
var prevUser = currentUser;
// Sign in user with another account
firebase.auth().signInAndRetrieveDataWithCredential(linkError.credential).then((userCredential) => {
  console.log("Sign In Success", userCredential.user);
  var newUser = userCredential.user;
  // Merge prevUser and newUser data stored in Firebase.
  // Note: How you handle this is specific to your application

    // After data is migrated delete the duplicate user
    return newUser.delete().then(() => {
      // Link the OAuth Credential to original account
      return prevUser.linkAndRetrieveDataWithCredential(linkError.credential);
    }).then(() => {
      // Sign in with the newly linked credential
      return firebase.auth().signInAndRetrieveDataWithCredential(linkError.credential).then(() => {
        return dispatch(mergeAccountsCompleted())
      })
    });
  })

The execution of prevUser.linkAndRetrieveDataWithCredential fails with the error code: 'auth/no-current-user' I couldn't find documentation for this error. So my question is, how can I recover from the auth/credential-already-in-use error when I want to merge the existing accounts in react-native-firebase ?

Thanks in advance !

**Comment by Salakar** [comment]
@ygomezfinale we don't yet support `error.credential`, please see this issue: https://github.com/invertase/react-native-firebase/issues/1329

In short; waiting on a PR to land in React Native - once/if this lands in a version we can start getting this supported.

PR: https://github.com/facebook/react-native/pull/20940

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by ygomezfinale** [comment]
Hello Salakar,
this issue is not about the support of error.credential, the problem here is the prevUser seems to be not logged in when executing prevUser.linkAndRetrieveDataWithCredential, it launch the 'auth/no-current-user' error code, my question is about how to handle this:
When linking two existing accounts, without logged out the current user, log in with the second user, delete it and linking this second account to the first one.
