### ISSUE TITLE
Client Callable Firebase Function fails with "Error: The data couldn’t be read because it isn’t in the correct format."

### ISSUE THREAD

**Issue by gkartalis** [invertase/react-native-firebase#1386]
Hello,
first of all thanks for the great work you're doing with RNfirebase!

### Issue
 
Client Callable Firebase Function fails with _"Error: The data couldn’t be read because it isn’t in the correct format."_ when deployed to regions other than us-central1 (tried Europe West and Asia).

**CF code:** 
```javascript 
exports.getName = functions.region('europe-west1').https.onCall((data, context) => {
     return { name: "Testopoulos" };
});
```

**RN App code:**

```javascript
const httpsCallableUserName = firebase.functions().httpsCallable('getName');

getUserName = () => {
    httpsCallableUserName()
    .then(({ data }) => {
        console.log(data.name);
    })
    .catch(httpsError => {
        console.log(httpsError); 
    })
  }
```

There is a note in the [docs](https://firebase.google.com/docs/functions/locations#http_and_client_callable_functions) saying that "[when] using HTTP functions to serve dynamic content for hosting, you must use us-central1" but I am just returning an object to our frontend React Native client and not using Firebase Hosting. I read other posts about the regions but I don't think it is the same case. Any ideas? 

### Environment

1. Application Target Platform:

Both.

2. Development Operating System:

MacOS High Sierra

3. Build Tools:

XCode

4. `React Native` version:

0.55.2

5. `React Native Firebase` Version:

4.3.8

6. `Firebase` Module:

Cloud Functions

7. Are you using `typescript`?

No.

-----

**Comment by Salakar** [comment]
Landing in v5/https://github.com/invertase/react-native-firebase/pull/1395

Thanks
