### ISSUE TITLE
No such file or directory: libRNFirebase.a

### ISSUE THREAD

**Issue by BlakeRxxk** [invertase/react-native-firebase#1387]
### Issue
Building my app in debug/release mode produce error 
`no such file or directory: '/Library/Developer/Xcode/DerivedData/App-aqmvuabcxrupkgfjyogwyxrtzbvk/Build/Products/Debug-iphonesimulator/libRNFirebase.a'`
but real location of `libRNFirebase.a` is `Debug-iphonesimulator/RNFirebase/libRNFirebase.a'`

clean build and cleaning Derrived Data didn't help;
pod deintegrate didn't help; 
upgrading RN version and RNF version it's not an option

is there any solutions?

### Environment

1. Application Target Platform: iOS
2. Development Operating System: macOS High Sierra
3. Build Tools:
 - Xcode 9.4
 - Xcode 9.2
 - Xcode 9.3
 - deployment target iOs 9.0
4. `React Native` version: 0.44.0
5. `React Native Firebase` Version: 2.2.3
6. `Firebase` Module: Core, Crash, Messaging ~> 4.2.0
7. Are you using `typescript`: no
---

**Comment by joshimbriani** [comment]
How are you linking RNFirebase? Are you just running `react-native link react-native-firebase`? If you are, it might be worth trying to manually link that .a like step 2 in [the linking guide](https://facebook.github.io/react-native/docs/linking-libraries-ios).

**Comment by BlakeRxxk** [comment]
@joshimbriani linking was manually

**Comment by BlakeRxxk** [comment]
I know it's been a while, but I'm still facing this issue from time to time, mostly on my CI machine.
as I mention before main problem - is with linker

`no such file or directory: '/Library/Developer/Xcode/DerivedData/App-aqmvuabcxrupkgfjyogwyxrtzbvk/Build/Products/Debug-iphonesimulator/libRNFirebase.a'`
but real location of `libRNFirebase.a` is
`/Library/Developer/Xcode/DerivedData/App-aqmvuabcxrupkgfjyogwyxrtzbvk/Build/Products/Debug-iphonesimulator/RNFirebase/libRNFirebase.a'`

I tried manual linking and automatic, changing package versions (between 2.1.0 and 2.2.3) - nothing.

**Comment by 007jedgar** [comment]
For me, I installed RNFirebase using cocoapods _after_ deserting the npm method. But I still had a RNFirebase.xcodeproj file under "Libraries." Try Deleting the RNFirebase Library.

**Comment by ishigamii** [comment]
I am having this issue every two weeks when I try to compile the new version of my app and after some build / clean / restart sometimes i get it to work but to be honest I don't understand what is causing this :s Any fix ?

**Comment by longnk-1447** [comment]
.

**Comment by prinse1545** [comment]
I am facing the same issue it's been about a month without any luck

**Comment by filmhomage** [comment]
Same here. Only on CI machine. 🤔
