### ISSUE TITLE
Cannot archive project when using react-native-firebase

### ISSUE THREAD

**Issue by vysotsky** [invertase/react-native-firebase#1388]
### Issue

Seems like there is a conflict between embedded React Native and my version connected via CocoaPods. 
When using `npm install`, it fails post install run phase and says that cannot resolve react native due to @providesModule duplication.
When using `yarn install`, I'm having lots of warnings like the following:
```
This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: verifyPropTypes
  Paths: /project/ios/Pods/React/Libraries/ReactIOS/verifyPropTypes.js collides with /project/node_modules/react-native/Libraries/ReactNative/verifyPropTypes.js
```
And these warnings prevent app from archiving (both iOS and android) because react native cli cannot generate a bundle.
```
Ambiguous module resolution from `/Users/vsts/agent/2.136.1/work/1/s/App/App.js`: The name `react-native` was looked up in the Haste module map. It cannot be resolved, because there exists several different files, or packages, that provide a module for that particular name and platform. The platform is generic (no extension). You must delete or blacklist files until there remains only one of these:

  * `/Users/vsts/agent/2.136.1/work/1/s/node_modules/react-native-firebase/node_modules/react-native/package.json` (package)
  * `/Users/vsts/agent/2.136.1/work/1/s/node_modules/react-native/package.json` (package)
```
Cleaning caches didn't work. Also we're facing with this issue on our CI environment. 

As far as I understand, the problem is that `react-native-firebase` folder contains another `node_modules` and it breaks dependencies map as now my project contains 2 react natives (react-native-firebase`s one is 0.11.1 🤔). I tried removing this folder but it also didn't work.

### Environment

1. Application Target Platform:

Both

2. Development Operating System:

MacOS

3. Build Tools:

Xcode 9.3, 9.4, Android Studio 3.1.1

4. `React Native` version:

0.55.4

5. `React Native Firebase` Version:

5.0.0

6. `Firebase` Module:

Core, Analytics

7. Are you using `typescript`?

No

**Comment by ms4ever7** [comment]
+, same issue

**Comment by Ehesp** [comment]
I think is more of a React Native issue with the module caching in place. [This](https://github.com/facebook/react-native/issues/15789#issuecomment-327115978) comment seems to have solved the issue for a number of people. Also another one sounds like restarting your Mac also helps.

If you Google `react native Ambiguous module resolution` you'll find loads of similar issues with modules and different resolutions.

**Comment by vysotsky** [comment]
Sorry, but as I've said before, cleaning caches doesn't work. Restarting Mac doesn't help as well. And as I've mentioned, we're also having this issue when using our CI environment which cleans itself and its caches after each run. So I have to ask you to reopen this issue.

**Comment by piasetskiy** [comment]
I have the same issue!!!

**Comment by Ehesp** [comment]
Are you guys installing with `npm` or `yarn`?

**Comment by vysotsky** [comment]
We tried both, nothing worked.

**Comment by vysotsky** [comment]
npm cannot run `postinstall` script so we've decided to use `yarn`

**Comment by vysotsky** [comment]
I just tried removing `react` from `Podfile`. When running `pod install`, it said me that it tries to install another version of the library - `Installing React (0.11.0)`. That's the version react-native-firebase contains. And it also breaks the project.
