### ISSUE TITLE
FieldValue.arrayUnion() and FieldValue.arrayRemove() APIs.

### ISSUE THREAD

**Issue by hasanaktas** [invertase/react-native-firebase#1389]
These two features are not working.

please update firestore...

**Comment by Salakar** [comment]
Firebase Android SDK support is still being worked on, we'll add support in v5 / when android SDK support lands.

**Comment by udarts** [comment]
Any idea when v5 will be released with these featured included?

**Comment by hugopretorius72** [comment]
Hey guys, has this landed? I look forward to it very much

**Comment by graig12** [comment]
Had this been fixed I am still unable to use arrayUnion

**Comment by Salakar** [comment]
It's `firebase.firestore.FieldValue.X`
