### ISSUE TITLE
'array-contains' support for firestore

### ISSUE THREAD

**Issue by abburi03** [invertase/react-native-firebase#1390]
Hi, 

Firstly thank you for wonderful library. I see that firestore has support for 'array-contains' in where clause, which is really helpful where clause when working with arrays. In RNFireBase docs I don't see that you are supporting it yet (Correct me If i am wrong) . If you are not supporting do you have any plans to support it in near future

For feature requests please visit our [Feature Request Board](https://boards.invertase.io/react-native-firebase).

**Comment by Salakar** [comment]
Firebase Android SDK support is still being worked on, we'll add support in v5 / when android SDK support lands.

**Comment by Salakar** [comment]
@abburi03 `v5.0.0-rc4` has just been published with firestore `array-contains` filtering support.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
