### ISSUE TITLE
react-native-firebase and react-native-navigation-v2 android

### ISSUE THREAD

**Issue by rendomnet** [invertase/react-native-firebase#1392]
Does anyone have working project with react-native-firebase and react-native-navigation(wix) on Android?
Both of this plugins are heavily changing config files. And after a while only Android expert can understand what is happening.

Right now my App are very unstable under android. I have a lot of mixed settings in config files like build.gradle.

Maybe someone with stable "react-native-firebase and react-native-navigation" app can share he's config files?

here is mine build.gradle

```
apply plugin: "com.android.application"

import com.android.build.OutputFile



project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"
def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        vectorDrawables.useSupportLibrary = true
        applicationId "com.myapp"
        multiDexEnabled true
        minSdkVersion 19
        targetSdkVersion 27
        missingDimensionStrategy "RNN.reactNativeVersion", "reactNative55" // <- See note below for further instruction regarding compatibility with other React Native versions
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
//    applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

// configurations.all {
//     resolutionStrategy.eachDependency { DependencyResolveDetails details ->
//         def requested = details.requested
//         if (requested.group == 'com.android.support') {
//             details.useVersion "27.1.0" // <- Change this to whatever version you're using
//         }
//     }
// }

dependencies {
    api "com.facebook.react:react-native:+"  // From node_modules
    implementation(project(':react-native-firebase')) {
        transitive = false
    }

    implementation 'com.android.support:multidex:1.0.3'
    implementation project(':react-native-image-crop-picker')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-localization')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'com.android.support:appcompat-v7:27.1.0'
    implementation 'com.android.support:design:27.1.0'

    implementation (project(':react-native-maps')) {
      exclude group: 'com.google.android.gms', module: 'play-services-base'
      exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }

    implementation project(':react-native-navigation')

    // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:15.0.1"
    implementation "com.google.android.gms:play-services-maps:15.0.1"


    implementation 'me.leolin:ShortcutBadger:1.1.21@aar' // <-- Add this line if you wish to use badge on Android

    implementation "com.google.firebase:firebase-core:16.0.1"
    implementation "com.google.firebase:firebase-auth:16.0.2"
    implementation "com.google.firebase:firebase-firestore:17.0.4"
    implementation "com.google.firebase:firebase-messaging:17.1.0"
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
```

**Comment by Ehesp** [comment]
Going to have to ask for community help on this one, we've not used that navigator properly yet so not sure on what kinks there are.

**Comment by Ehesp** [comment]
Could you also explain what issues you're having? Is it build, or is it something else>

**Comment by rendomnet** [comment]
@Ehesp right now my app crashing when I'm navigating in android. And problem that I'm trying to configure android files to fix this issue, but i'm not sure if changing something for one plugin will not break it for another.

**Comment by Ehesp** [comment]
What is the native error when it crashes?

**Comment by rendomnet** [comment]
When I'm running react-native run-android - my app crashes with "restart application" button.
I run gradlew clean, gradlew build and got this error.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-firebase:lint'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

  The first 3 errors (out of 4) were:
  /Users/user/myapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java:200: Error: Call requires API level 23 (current min is 16): android.app.NotificationManager#getActiveNotifications [NewApi]
      StatusBarNotification[] statusBarNotifications = notificationManager.getActiveNotifications();
                                                                           ~~~~~~~~~~~~~~~~~~~~~~
  /Users/user/myapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java:202: Error: Call requires API level 18 (current min is 16): android.service.notification.StatusBarNotification#getTag [NewApi]
          if (statusBarNotification.getTag() == tag) {
                                    ~~~~~~
  /Users/user/myapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java:203: Error: Call requires API level 18 (current min is 16): android.service.notification.StatusBarNotification#getId [NewApi]
              notificationManager.cancel(statusBarNotification.getTag(), statusBarNotification.getId());
                                                                                               ~~~~~
```

**Comment by Stone2517** [comment]
Run **gradlew cleanBuildCache**

**Comment by rendomnet** [comment]
@Stone2517 I have done gradlew cleanBuildCache then gradlew build.... and got the same error.

**Comment by hongsa** [comment]
i got same error. How can i solve this?

**Comment by hongsa** [comment]
i solved this problem.
please downgrade react-native-firebase verson to 3.3x

**Comment by rendomnet** [comment]
@erandagan 
The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..


The specified Android SDK Build Tools version (25.0.3) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.3.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Update Build Tools version and sync project
Open File


The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..


The specified Android SDK Build Tools version (25.0.0) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.3.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Update Build Tools version and sync project
Open File


Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html


The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..


Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html


The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..


The specified Android SDK Build Tools version (26.0.1) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.3.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Update Build Tools version and sync project
Open File


Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html


The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..


The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..


The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..


Module 'react-native-navigation' has variant 'reactNative51Debug' selected, but the module ''app'' depends on variant 'reactNative55Debug'
Select 'react-native-navigation' in "Build Variants" window
Fix problem

**Comment by rikochet** [comment]
I am facing the same NotificationManager.java errors in my own project, so I downloaded the starter project.

https://github.com/invertase/react-native-firebase-starter

The errors also exist in this project. I have tried deleting my ~/.gradle folder and run `./gradlew cleanBuildCache` and `./gradlew clean` but the issue remains.

Any ideas?

**Comment by rendomnet** [comment]
Guys what helped me is launching Android Studio and update everything it will ask you update.

**Comment by Northshoot** [comment]
I am having the same problem. 

`rm -rf ~/.ggradle/caches/`

`./gradlew cleanBuildCache`

`./gradlew build`

results in error:

`  The first 3 errors (out of 4) were:
  /Users/triioadmin/workspace/mobile-client/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java:200: Error: Call requires API level 23 (current min is 16): android.app.NotificationManager#getActiveNotifications [NewApi]
      StatusBarNotification[] statusBarNotifications = notificationManager.getActiveNotifications();
                                                                           ~~~~~~~~~~~~~~~~~~~~~~
  /Users/triioadmin/workspace/mobile-client/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java:202: Error: Call requires API level 18 (current min is 16): android.service.notification.StatusBarNotification#getTag [NewApi]
          if (statusBarNotification.getTag() == tag) {
                                    ~~~~~~
  /Users/triioadmin/workspace/mobile-client/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java:203: Error: Call requires API level 18 (current min is 16): android.service.notification.StatusBarNotification#getId [NewApi]
              notificationManager.cancel(statusBarNotification.getTag(), statusBarNotification.getId());`


Why running android studio should be a solution?  The project should run from command line when building with gradle.

The `build.gradle' of the project (react-native-firebase)  has min version set to 16 so why is this error?

`
  defaultConfig {
    minSdkVersion 16
    targetSdkVersion rootProject.hasProperty('targetSdkVersion') ? rootProject.targetSdkVersion : DEFAULT_TARGET_SDK_VERSION
    versionCode 1
    versionName "1.0"
    multiDexEnabled true
  }
`

changing it avoid the compilation error but I am sure this is not the right way to do it.

**Comment by danielidt** [comment]
Ok guys, I think i fixed it. I had to add `implementation 'com.android.support:appcompat-v7:26.0.2'` to my dependencies

I was using `compileSdkVersion = 27` and found that I could keep that as well. it also works with `compileSdkVersion = 26`

It also works with other versions of `implementation 'com.android.support:appcompat-v7:{version}'` included as long as 26.0.2 or 26.0.1 is in there. Not sure what the best configuration is since im not an android dev but wanted to share the solution i found.

**Comment by Salakar** [comment]
Hey all, I've just pushed up a commit that wraps all `StatusBarNotification` usage inside a version check statement - so this will no longer cause an issue on lower sdk version targets (16). 

This will land in the next release.

Thanks
---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by eran-or** [comment]
Adding the next line to build.gradle (Module app)  dependencies resolve it:
 implementation "com.android.support:design:${rootProject.ext.supportLibVersion}"
