### ISSUE TITLE
Different Approach When Receiving Notification

### ISSUE THREAD

**Issue by kriptonhaz** [invertase/react-native-firebase#1394]
### Issue
Testing with different physical device as listed as down here with different issue

The trouble device:
- Oppo R7(OS Version 5.1.1) =>notification goes in tray in both foreground and background, when apps is closed notification didn't show anything
- Vivo Y83(OS Version 8.1.0) => when apps is closed notification didn't show anything
- Xiaomi Redmi 4x (OS Version 7.1.2) => notification goes on tray in all apps state (foreground, background, close)

The working device: (all notification is work like I want; heads-up, foreground background, apps closed)
- Oppo F7 (OS Version 8.1.0)
- Samsung Galaxy J5 (OS Version 6.0.1)
- Lenovo A7000 (OS version 6.0)

this is my payload

> {
>  "to" : "device token",
>  "collapse_key" : "type_a",
>  "priority" : "high",
>  "content_available" : true,
>  "data" : {
>      "body" : "First Notification",
>      "title": "Notification Test",
>      "key_1" : "Data for key one",
>      "key_2" : "Hellowww"
>  }
> }

I've been using tips from [1238](https://github.com/invertase/react-native-firebase/issues/1238#issuecomment-410422872) but still not achieving the result as expected. Is there anyway to fix that? at least still receiving notification when apps is closed.
### Environment
1. Application Target Platform:
Android
2. Development Operating System:
Windows 10
4. `React Native` version:
0.55.4
5. `React Native Firebase` Version:
4.3.8
6. `Firebase` Module:
messaging
7. Are you using `typescript`?
No
---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by sangupandi** [comment]
any updates on this?

**Comment by venkat-waran** [comment]
Same issue any update on this?
