### ISSUE TITLE
Database transaction support is missing

### ISSUE THREAD

**Issue by jonasb** [invertase/react-native-firebase#14]
[database.Reference.transaction()](https://firebase.google.com/docs/reference/js/firebase.database.Reference#transaction) is a crucial part of interacting with the Firebase Database and is missing from react-native-firebase.

**Comment by Ehesp** [comment]
This is down to tricky implementation I believe. It's something @Salakar has been thinking about and started implementing but I'm not sure on progress.

To get around this on our current app, we implement an upstream message, which the server is able to handle and process for now.

**Comment by Salakar** [comment]
@jonasb just landed android support for this: https://github.com/invertase/react-native-firebase/commit/bb6b1aa7f268e2418ed622f5a409b0553bb2d402. 

Working on ios now.

**Comment by Salakar** [comment]
Landed for both platforms in alpha9 :)

Closing.

**Comment by jonasb** [comment]
Seems to work well for me! Thanks!
