### ISSUE TITLE
ios: crashlytics fails to initialize

### ISSUE THREAD

**Issue by jfaust** [invertase/react-native-firebase#1401]
### Issue

This commit:
https://github.com/invertase/react-native-firebase/commit/1d2757dc308c6dc51ecd81a6f91df5298bfb5342

broke crashlytics for us. We do not use either pods or `react-native link` - and the actual Crashlytics framework does not have the extra `Crashlytics` directory.

Changing the include checks/imports back locally fixes things.

### Environment

1. Application Target Platform:

iOS

2. Development Operating System:

macOS (various)

3. Build Tools:

Bazel

4. `React Native` version:

0.55.4

5. `React Native Firebase` Version:

4.3.8

6. `Firebase` Module:

Crashlytics

7. Are you using `typescript`?

yes but irrelevant

---

**Comment by jfaust** [comment]
This is still an issue, and is preventing us from upgrading.

**Comment by Salakar** [comment]
Just pushed something to allow both path variations - this will be out in v5 later today, thanks for the report 👍 	

https://github.com/invertase/react-native-firebase/commit/4ec5524645d9815f9e59344fd10acfebe97c5512

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by ziyafenn** [comment]
@Salakar does this mean that i won't be able to use this fix on 4.3.8? As i'm using RN 0.55 i can't upgrade to v5 :(
