### ISSUE TITLE
Native Ads Advanced support

### ISSUE THREAD

**Issue by perrosnk** [invertase/react-native-firebase#1403]
This [Issue](https://github.com/invertase/react-native-firebase/issues/1309) was closed by referencing an external [link](https://github.com/invertase/react-native-firebase/issues/1309#issuecomment-405877145) but it doesn't work anymore.

So, Are native ads advanced going to be supported?

**Comment by Ehesp** [comment]
Hello - we're currently not sure on the future of Admob within the library (and Firebase itself). I've looked into Native Ads and they'll be difficult to implement with React Native due to the amount of flexibility it allows for.

Currently they're not in progress and we may move them out to a standalone library at some point, however, it's to be discussed. I'm open to having a conversation about them and working through to seeing how the module could be properly implemented.

**Comment by perrosnk** [comment]
Hello @Ehesp .
As far as I understand the recommended way to use AdMob is with Firebase according to the [docs](https://firebase.google.com/docs/admob/admob-firebase) so it would make sense to be part of this library in my opinion.

**Comment by perrosnk** [comment]
It should be open

**Comment by perrosnk** [comment]
It should be open

**Comment by Ehesp** [comment]
Please see https://invertase.canny.io/admin/board/react-native-firebase/p/new-native-ad-format

**Comment by JamieCorkhill** [comment]
What is happening with this issue? Are AdMob Native Ads going to be supported by React-Native-Firebase?

Thanks.

**Comment by perrosnk** [comment]
Native ads are out of beta and are available to everybody!

Any updates whether Native ads will be supported by react-native-firebase any time soon?

**Comment by mikehardy** [comment]
AdMob just began the port from v5 react-native-firebase to v6, I'd guess they want to do that prior to increasing API surface area but I see you are listening on the feature board so you will probably see any updates as they arrive

**Comment by JamieCorkhill** [comment]
@mikehardy Feature board? Where can I find that?

Are any Native Ad formats available at all for React Native with react-native-firebase?

Thanks.

**Comment by mikehardy** [comment]
@JamieCorkhill it's linked above

**Comment by Salakar** [comment]
The short answer is yes. The long answer is this wont be until 6.1/6.2 most likely;

Other than bug fixes and API reworking and improvements, the only new features coming in v6 are the ad consent apis/forms

**Comment by manuhook** [comment]
Hi @Salakar,
Is there still a roadmap for Admob Native Ads ?
Thanks you !

**Comment by emil45** [comment]
Hey, I know it's closed issue, but in the docs there is no mention about native ads.

Is there any update ?

**Comment by mikehardy** [comment]
https://github.com/invertase/react-native-firebase/issues?q=is%3Aissue+%22admob+native+ads%22+sort%3Aupdated-desc

turned up:

https://github.com/invertase/react-native-firebase/issues/3270
