### ISSUE TITLE
No way to find/purchase "Premium Starter Kits"

### ISSUE THREAD

**Issue by bdombro** [invertase/react-native-firebase#1406]
All links in the main website and documentation get redirected to https://rnfirebase.io/docs/v4.3.x/getting-started. How does one actually view more info or purchase?

**Comment by Ehesp** [comment]
Hello - they're currently disabled due. We want to ensure we can offer full support and keep them fully up-to-date, and we have lots of commitments at the moment! Hopefully they'll be available at some point in the future.

**Comment by bdombro** [comment]
Would you please consider sharing it with me, despite being unsupported? I'd really like to see a bigger example of using react-native-firebase
