### ISSUE TITLE
firebase.auth().currentUser retrieves outdates data

### ISSUE THREAD

**Issue by rendomnet** [invertase/react-native-firebase#1409]
### Issue
I have user edit page, where I successfully change user displayName. In the callback I retrieve updated data. 
But if I run
`let user = await firebase.auth().currentUser;`
it will return pervious unchanged data.

Only if I logout and login then my 
`let user = await firebase.auth().currentUser;` 
will return correct updated info.

### Environment

1. Application Target Platform:

Tested on iOS

2. Development Operating System:

macOS Sierra

4. `React Native` version:

"react-native": "0.55.4",

5. `React Native Firebase` Version:

    "react-native-firebase": "^4.3.8",

**Comment by Ehesp** [comment]
You'll need to call [reload](https://rnfirebase.io/docs/v4.3.x/auth/reference/User#reload) after updating the user's data. 

Also, one to keep in mind, accessing [currentUser](https://rnfirebase.io/docs/v4.3.x/auth/reference/auth#currentUser) isn't a promise so no need for the `await`.
