### ISSUE TITLE
cancel on uploads

### ISSUE THREAD

**Issue by weepy** [invertase/react-native-firebase#1411]
Hiya - is there a workaround for cancelling storage tasks ? I see it's currently not supported ?

**Comment by Salakar** [comment]
Hey @weepy - no work around but support for `pause`, `cancel` and `resume` is coming in `v5.0.0`. I will tag you on this issue when there's a RC version out of v5 with support in it. v5.0.0 is in active development right now.

Additionally I'll close this and track on https://github.com/invertase/react-native-firebase/issues/1260.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by llaine** [comment]
Any workaround on that one?

**Comment by addu1** [comment]
When is v6.0.0 coming?
