### ISSUE TITLE
Model 'path' does not exist error using firebase-functions

### ISSUE THREAD

**Issue by NicWickman** [invertase/react-native-firebase#1412]
### Issue

error: bundling failed: Error: Unable to resolve module `path` from `D:\Apps\RallyApp\node_modules\firebase-functions\lib\providers\firestore.js`: Module `path` does not exist in the Haste module map
}
happens whenever I try to import firebase-functions with `const functions = require('firebase-functions')`
### Environment

1. Application Target Platform:

Both

2. Development Operating System:

Windows 10, but error also occurs in Ubuntu running WSL.

3. Build Tools:

Android 

4. `React Native` version:

Occurs on both 55.4 and 56.

5. `React Native Firebase` Version:

using the most recent starter kit.

6. `Firebase` Module:

functions

7. Are you using `typescript`?

no

---

**Comment by Ehesp** [comment]
The `firebase-functions` module isn't part of the library, make sure you're following the guides/docs here https://rnfirebase.io

**Comment by NicWickman** [comment]
I have been following the guides, and I am working from the starter kit.

https://rnfirebase.io/docs/v4.3.x/functions/reference/functions <- Is this not functionality meant to use firebase-functions? The Firebase Cloud Function Example gives `const functions = require('firebase-functions');` as an example.

So how do I use functions with RNFirebase?

**Comment by Ehesp** [comment]
That's what you'd deploy to Firebase Cloud Functions, then you'd use the module on this library to hook into that function.

**Comment by NicWickman** [comment]
Thanks Elliot, that's helpful. Obviously I'm new to this.

Nic
