### ISSUE TITLE
> Task :app:processDebugGoogleServices : Build Failed with an Exception

### ISSUE THREAD

**Issue by heisty** [invertase/react-native-firebase#1413]
-->

### Issue

I tried installing React Native Firebase and followed their tutorial on rnfirebase but when I 'react-native run-android' it , It always failed.

Scanning folders for symlinks in D:\JNLX\JNL\node_modules (2451ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...

> Configure project :app
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Configure project :react-native-facebook-login
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.3.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-firebase
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..

> Configure project :react-native-text-input-mask
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-vector-icons
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (26.0.3) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.3.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:processDebugGoogleServices
Parsing json file: D:\JNLX\JNL\android\app\google-services.json

ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontWeight

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 38s
66 actionable tasks: 65 executed, 1 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

### Environment

1. Application Target Platform:

ANDROID

2. Development Operating System:

WIN10

3. Build Tools:

Sublime, Im using the RN cli.

4. `React Native` version:

0.55.4

5. `React Native Firebase` Version:

"version": "4.3.8",

6. `Firebase` Module:

n/a

7. Are you using `typescript`?

no

---

**Comment by stackdumper** [comment]
I have the same issue, appeared after the installation of `Notifications` module.

**Comment by stackdumper** [comment]
[FIX]
For me, error was caused by following steps:
https://rnfirebase.io/docs/v4.3.x/notifications/android#Default-icon-and-color-(Optional)

Removing of following tags in `android/app/src/main/AndroidManifest.xml` fixed the problem
```xml
<meta-data
  android:name="com.google.firebase.messaging.default_notification_icon"
  android:resource="@drawable/ic_stat_ic_notification"
/>

<meta-data
  android:name="com.google.firebase.messaging.default_notification_color"
  android:resource="@color/colorAccent"
/>

<meta-data
  android:name="com.google.firebase.messaging.default_notification_channel_id"
  android:value="@string/reminders"
/>
```

**Comment by gitsad** [comment]
Does anyone know how to resolve it? I have the same problem 😞

**Comment by gitsad** [comment]
On iOS, everything works but on Android, I have this problem which @heisty documented. @heisty have you managed to resolve it?

**Comment by demarchisd** [comment]
Same thing here.. did anybody solve it?

**Comment by youssefatti** [comment]
sudo react-native run-android worked for me

**Comment by heisty** [comment]
I decided to clean everything up and works, deleted almost everything.

**Comment by heisty** [comment]
Going to close this issue.

**Comment by Rutheniceye92** [comment]
@heisty Can you please tell how you cleaned everything? What do you mean by everything?

**Comment by youssefatti** [comment]
i think he talk about that : 
 1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
and do this to : 
in Xcode Product->Clean Build Folder
in android Studio Build-> Clean Project

and restart your computer too

**Comment by LuckyShine001** [comment]
Just fellow these steps:
cd android
gradlew clean
cd..
react-native run-android

**Comment by JxDarkAngel** [comment]
In my case, it was that the name of my **packageName** that came from the file was not correct: **google-services.json**
