### ISSUE TITLE
 The [[DEFAULT]] firebase app has not been initialized!

### ISSUE THREAD

**Issue by SwapnilRathore** [invertase/react-native-firebase#1417]
### Issue

`Here is my build.gradle file` : 

     buildscript {
       repositories {
          google()
           jcenter()

    }
    dependencies {
        classpath 'com.google.gms:google-services:4.0.1'
        classpath 'com.android.tools.build:gradle:3.1.3'
    }
    }

    allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }

     }
     }

     apply plugin: 'com.google.gms.google-services'

`here is my app/build.gradle file`:

    apply plugin: "com.android.application"

    import com.android.build.OutputFile

    project.ext.react = [
    entryFile: "index.js"
    ]

    apply from: "../../node_modules/react-native/react.gradle"

    def enableSeparateBuildPerCPUArchitecture = false

    def enableProguardInReleaseBuilds = false

    android {
    compileSdkVersion 26
    buildToolsVersion '27.0.3'

    defaultConfig {
        applicationId "com.ifiwhereyou_frontend"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
		// Enabling multidex support.
        multiDexEnabled true
      }
      signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
         }
      }
	dexOptions {
        javaMaxHeapSize "4g"
      }
      splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
          }
       }
     buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
          }
      }
       // applicationVariants are e.g. debug, release
       applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
          }
       }
      }

       dependencies {
        // This should be here already
         implementation project(':react-native-firebase')

      // Firebase dependencies
       implementation "com.google.android.gms:play-services-base:15.0.1"
      implementation "com.google.firebase:firebase-core:16.0.1"
      implementation "com.google.firebase:firebase-ads:15.0.1"
      implementation project(':lottie-react-native')
      implementation project(':react-native-vector-icons')
      implementation fileTree(dir: "libs", include: ["*.jar"])
      implementation 'com.android.support:design:27.1.0'
      implementation "com.facebook.react:react-native:+"
      implementation project(':react-native-navigation')
	  implementation 'com.android.support:multidex:1.0.0'

    }

      // Run this once to be able to run the application with BUCK
     // puts all compile dependencies into folder libs for BUCK to use
      task copyDownloadableDepsToLibs(type: Copy) {
        from configurations.compile
        into 'libs'
     }

`Here is the code were i have used ad banner and banner id` : 

       import firebase from 'react-native-firebase';

       const Banner = firebase.admob.Banner;
      const AdRequest = firebase.admob.AdRequest;
      const request = new AdRequest();
      request.addKeyword('foobar');

     <Banner
      unitId = {"ca-app-pub-xxxxxxxxxxxxxxxx"}
      size={"LARGE_BANNER"}
      request={request.build()}
      onAdLoaded={() => {
        console.log('Advert loaded');
      }}
      />

<----  in main index file i have initialised Admob id ------>

`here is the index.js `:

       import { AppRegistry } from 'react-native';
       import App from './src';
       import firebase from 'react-native-firebase';
       firebase.admob().initialize('ca-app-pub-xxxxxxxxxxxxxxxxxxx');
       AppRegistry.registerComponent("ifiwhereyou_frontend", () => App);

### Environment

1. Application Target Platform: Android

2. Development Operating System: macOS Sierra

3. Build Tools:
`Android Studio` 3.1.3,
`Android SDK` 26  

4. `React Native` 0.56.0 
    `React-native-cli`: 2.0.1

5. `react-native-firebase`: ^4.2.0,

6. `Firebase` Module: Admob

7. Are you using `typescript`? yes

**Comment by moritzmorgenroth** [comment]
+1

**Comment by Ehesp** [comment]
Have you added the json file from the firebase console?

**Comment by SwapnilRathore** [comment]
Yes  i did

**Comment by Ehesp** [comment]
Could you show us the output of `firesbase.apps()` please? Console log will do!

**Comment by JanErikFoss** [comment]
Same error.

I'm getting empty array.

**Comment by JanErikFoss** [comment]
I'm getting the same error. 

firebase.apps is an empty array.

**Comment by SwapnilRathore** [comment]
The issue got resolved , it was just a bad config , i have specified the wrong package name while adding app in firebase console.

Thanks!

**Comment by Subway19** [comment]
I was getting this error and I resolved this after a lot of efforts. Now I am stuck in this error.

`app.utils(...).checkPlayServicesAvailability is not a function`

Anybody can help me out on this?

**Comment by MeisterTea** [comment]
Please check out this issue if you stumble on this error : https://github.com/invertase/react-native-firebase/issues/2187
