### ISSUE TITLE
signInAndRetrieveDataWithCredential throws wrong error code (auth/unknown)

### ISSUE THREAD

**Issue by rwichmann** [invertase/react-native-firebase#1418]
### What happens:
I tested `signInAndRetrieveDataWithCredential` with a wrong verification code. The error returns:
**code**: "auth/unknown"
**message**: "The SMS verification code used to create the phone auth credential is invalid. Please resend the verification code SMS and be sure to use the verification code provided by the user."

### What I expected:
The message seems ok, but the error code should be "auth/invalid-verification-code".

### Environment

1. Application Target Platform:
iOS
2. Development Operating System:
macOS
3. Build Tools:
XCode, VSCode
4. `React Native` version:
0.56.0
5. `React Native Firebase` Version:
4.3.8
6. `Firebase` Module:
database, auth
7. Are you using `typescript`?
yes

**Comment by Ehesp** [comment]
Hello thanks for flagging - we'll get this checked out.

**Comment by Salakar** [comment]
@rwichmann thanks again for this, I've just landed a commit to update all the error codes on iOS in #1663 - this will be in the v5.1.0 release this coming week.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
