### ISSUE TITLE
does react-native-firebase support both Google Search Ads and Google Search Ads

### ISSUE THREAD

**Issue by pengcao1** [invertase/react-native-firebase#1421]
Hi folks:
as *issue* title description,  
does react-native-firebase support both Google Search Ads and Google Search Ads？
and how can do that in my react-native project(both Android and IOS)?

**Comment by Ehesp** [comment]
Sorry not sure what you mean, Google Search Ads is not Firebase related?

**Comment by pengcao1** [comment]
I mean that. 
We are trying set up Google search and Apple search ads that will drive app downloads 
does *react-native-firebase* supported this feature? and How did i do step by step/

**Comment by Ehesp** [comment]
Can you link me to whatever documentation you're referring to please?

**Comment by Mighty683** [comment]
@Ehesp Does linking of iAd.framework add support for Apple Search Ads as described in firebase docs?
https://support.google.com/firebase/answer/6317518?hl=en

Can we track Apple Search Ads like Google Campaigns with react-native-firebase?
