### ISSUE TITLE
ActionCodeInfo typing issue on 4.3.8

### ISSUE THREAD

**Issue by chris-divvito** [invertase/react-native-firebase#1423]
### Environment

1. Application Target Platform:
Both

2. Development Operating System:

Ubuntu for android dev and Mac for iOS

3. Build Tools:

Android Studio & xCode

4. `React Native` version:

0.55.4

5. `React Native Firebase` Version:
4.3.8

6. `Firebase` Module:

auth

7. Are you using `typescript`?

yes

---

Hello,

Just found an issue that rears it's head at least in 4.3.8, pretty simple one really - in checkActionCode method in RNFirebase both Java and ObjC methods return the operation in the property: `actionType`, not `operation` as the typings in `index.d.ts` would suggest

**Comment by Ehesp** [comment]
@chris-divvito do you mind submitting a PR?

**Comment by chris-divvito** [comment]
Sure, would you prefer the methods changed to comply to the typings or vice versa?

**Comment by Salakar** [comment]
@chris-divvito hey - just pushed a fix for this, native properties have been renamed to `operation` - to match the Web SDK + docs.

This will be in the v5 release later today.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
