### ISSUE TITLE
Auth methods use currentUser instead of the user instance they are called from

### ISSUE THREAD

**Issue by respectTheCode** [invertase/react-native-firebase#1426]
### Issue

When deleting a user the wrong user is deleted. The ObjC code is ignoring the user object that delete was called on and instead using the currentUser

https://github.com/invertase/react-native-firebase/blob/81fee9f57a27d29d013e45c318e9360794c275fe/ios/RNFirebase/auth/RNFirebaseAuth.m#L309-L312

This can be tested with like this

```javascript
const auth = firebase.auth();
const anonUser = auth.currentUser;
const user = await auth.signInAndRetrieveDataWithCredential(cred);
console.log("Previous anonymous user", anonUser.uid);
console.log("New logged in user", user.user.uid);
await anonUser.delete();
console.log("deleted anonymous user", anonUser);
```

This same thing happens when calling other methods like `linkAndRetrieveDataWithCredential`. The method is called on the currentUser instead of the user instance that the method was called from.

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS High Sierra

3. Build Tools: Xcode

4. `React Native` version: 0.55.4

5. `React Native Firebase` Version: 4.3.8

6. `Firebase` Module: auth

7. Are you using `typescript`? yes

**Comment by Ehesp** [comment]
Hi @respectTheCode - what's happening is correct, Firebase will always work with whatever the `currentUser` is. You can't have multiple users within Firebase on the same instance. You need to create another Firebase app instance to have multiple users.

**Comment by respectTheCode** [comment]
The docs show this same type of flow. Grab a reference to the current user, log in a new user, delete that user, link the credentials to the old user and that user in. I haven't tried it on web as I don't currently have that need but I assume the code in the docs works.

Example code copied from https://firebase.google.com/docs/auth/web/account-linking?authuser=0

```javascript
// Get reference to the currently signed-in user
var prevUser = auth.currentUser;
// Sign in user with another account
auth.signInWithCredential(credential).then(function(user) {
  console.log("Sign In Success", user);
  var currentUser = user;
  // Merge prevUser and currentUser data stored in Firebase.
  // Note: How you handle this is specific to your application

  // After data is migrated delete the duplicate user
  return user.delete().then(function() {
    // Link the OAuth Credential to original account
    return prevUser.linkWithCredential(credential);
  }).then(function() {
    // Sign in with the newly linked credential
    return auth.signInWithCredential(credential);
  });
}).catch(function(error) {
  console.log("Sign In Error", error);
});
```

**Comment by brunoro** [comment]
@Ehesp I feel that mirroring the Web API here is quite misleading, as the native bits of `react-native-firebase` are completely ignoring the callee of the methods on signed out user objects (`linkWithCredentialAndRetrieveData` and `delete` are the ones I stumbled upon myself). Maybe it would be the case of narrowing User into SignedInUser and adding those methods to that subclass?

@respectTheCode the [example on the Android docs for linking](https://firebase.google.com/docs/auth/android/account-linking#link-federated-auth-provider-credentials-to-a-user-account) indeed doesn't use a reference to a previously signed in account.
