### ISSUE TITLE
Android compilation issue with 5.0.0-rc1 with FirebaseFunctions.getInstance()

### ISSUE THREAD

**Issue by aforty** [invertase/react-native-firebase#1427]
### Issue

Trying to compile the latest 5.0.0-rc1 for Android and I get this error during compilation. Seems that `FirebaseFunctions.getInstance()` no longer accepts the region parameter.

```
> Task :react-native-firebase:compileReleaseJavaWithJavac FAILED
/Users/aforty/Code/leverage-mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/functions/RNFirebaseFunctions.java:63: error: no suitable method found for getInstance(FirebaseApp,String)
    FirebaseFunctions functionsInstance = FirebaseFunctions.getInstance(firebaseApp, region);
                                                           ^
    method FirebaseFunctions.getInstance(FirebaseApp) is not applicable
      (actual and formal argument lists differ in length)
    method FirebaseFunctions.getInstance() is not applicable
      (actual and formal argument lists differ in length)
/Users/aforty/Code/leverage-mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/functions/RNFirebaseFunctions.java:64: error: cannot find symbol
    functionsInstance.useFunctionsEmulator(origin);
                     ^
  symbol:   method useFunctionsEmulator(String)
  location: variable functionsInstance of type FirebaseFunctions
/Users/aforty/Code/leverage-mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/functions/RNFirebaseFunctions.java:90: error: no suitable method found for getInstance(FirebaseApp,String)
    FirebaseFunctions functionsInstance = FirebaseFunctions.getInstance(firebaseApp, region);
                                                           ^
    method FirebaseFunctions.getInstance(FirebaseApp) is not applicable
      (actual and formal argument lists differ in length)
    method FirebaseFunctions.getInstance() is not applicable
      (actual and formal argument lists differ in length)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-firebase:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

app/build.gradle dependencies
```
dependencies {
    ...
    implementation "com.google.android.gms:play-services-base:15.0.1"
    implementation "com.google.firebase:firebase-core:16.0.1"
    implementation "com.google.firebase:firebase-analytics:16.0.1"
    implementation "com.google.firebase:firebase-messaging:17.1.0"
    implementation "com.facebook.react:react-native:+" // From node_modules
}
```
### Environment

1. Application Target Platform:
Android

2. Development Operating System:
macOS Sierra

3. Build Tools:
Android Studio 3.1.4

4. `React Native` version:
0.56.0

5. `React Native Firebase` Version:
5.0.0-rc1

6. `Firebase` Module:
N/A

7. Are you using `typescript`?
no

**Comment by aforty** [comment]
Turns out the npm release of 5.0.0-rc1 doesn't include 769b3e742a1fd09fcf815391564505d293da3bca. :/

**Comment by Salakar** [comment]
RC1 does include this change, RC1 was cut for release 2 days ago, this change is 8 days ago. It should be in there?

It's not in RC0 so you maybe still have left overs of that locally perhaps, ensure you've set a specific version for react native firesbase, `5.0.0-rc1`, on your package json.

**Comment by aforty** [comment]
I did very explicitly set it to `5.0.0-rc1`. I verified that `node_modules/react-native-firebase/package.json` said `5.0.0-rc1` but `android/build.gradle` had `com.google.firebase:firebase-functions:16.0.1` (instead of `16.1.0`).

Try yourself `yarn add react-native-firebase@5.0.0-rc1`.

**Comment by marcoacierno** [comment]
Same here,

package.json says "version": "5.0.0-rc1",
but in the gradle it still uses 16.0.1

can you reopen the issue?

**Comment by Salakar** [comment]
Installed `react-native-firebase@5.0.0-rc1` from npm in a fresh project and it's correct, it has the `16.1.0` functions sdk.

![image](https://user-images.githubusercontent.com/5347038/44539617-8a79af00-a6fc-11e8-9537-e7918a556221.png)

**Comment by JanErikFoss** [comment]
I'm getting this error even though I'm using 16.1.0

Both in my own build.gradle and in node_modules/react-native-firebase/android/build.gradle.

I've tried cleaning all kinds of caches and reinstalling. Am I missing something?

**Comment by Salakar** [comment]
Try invalidating caches on android studio and rebuilding:

![image](https://user-images.githubusercontent.com/5347038/44580170-dd04ab00-a790-11e8-82c8-a8f67fb04d3d.png)

**Comment by Salakar** [comment]
I can also confirm that `16.1.0` does support the region arg, screenshot of decompiled `FirebaseFunctions` `getInstance` code: 

![image](https://user-images.githubusercontent.com/5347038/44580214-0de4e000-a791-11e8-9239-652ed6c22076.png)

**Comment by JanErikFoss** [comment]
That worked!

**Comment by cf-bosung90** [comment]
@Salakar I have tried your method of invalidate caches and restart but I am still getting the same problem.

When I check the FirebaseFunctions I do not see the code in your Screenshot
![image](https://user-images.githubusercontent.com/40073735/45210137-a3797880-b243-11e8-842f-eac2c8f548ee.png)

I am using `    "react-native-firebase": "5.0.0-rc1",`
I checked node_modules/react-native-firebase/android/build.gradle and I see correct version of firebase-functions is added as dependencies
`  compileOnly "com.google.firebase:firebase-functions:16.1.0"`

Any help would be appreciated.

**Comment by cf-bosung90** [comment]
Looks like Invalidate caches doesn't properly remove the gradle cache. I fixed by running
    ./gradlew cleanBuildCache
