### ISSUE TITLE
Help wanted: firebase.messaging().getToken() returns null

### ISSUE THREAD

**Issue by chinalwb** [invertase/react-native-firebase#1429]
### Issue

By following the guide of [Cloud Messaging](https://rnfirebase.io/docs/v4.3.x/messaging/device-token), the following code:

```
firebase.messaging().getToken()
  .then(fcmToken => {
    if (fcmToken) {
      // user has a device token
    } else {
      // user doesn't have a device token yet -- **my problem is here**
    } 
  });
```
My problem is `getToken()` returns null. Want to know what to do to re-get the token.

```
const playService = firebase.utils().playServicesAvailability
console.log('play service', playService)
```
It prints:
```
play service {isAvailable: true, status: 0}
```

P.S.: I can get the token on my Android Studio emulator, but for the above case, I cannot get the token on my real device, it is a HuaWei Honor 8, runs Android 7.0. 

### Environment

1. Application Target Platform: Android

2. Development Operating System: macOS Sierra

3. Build Tools: Android Studio

4. `React Native` version: 0.55.4

5. `React Native Firebase` Version: 4.3.0

6. `Firebase` Module: messaging

7. Are you using `typescript`? no

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Ehesp** [comment]
Could you check the result of `hasPermission()`?

**Comment by cx5168** [comment]
my solution：
  
```
      const res = Firebase.messaging().requestPermission();
      await res.promise;
      setTimeout(() => {Firebase.messaging().getToken().then(()=>{...})}，3000）
```

**Comment by chinalwb** [comment]
@Ehesp 

```
firebase.messaging().hasPermission()
      .then(enabled => {
        if (enabled) {
          // user has permissions
          console.log('User has fcm permission')
          this.registerFcmMessageListener()
        } else {
          // user doesn't have permission
          console.log('User doesn\'t have fcm permission')
          firebase.messaging().requestPermission()
            .then(() => {
              // User has authorised
              console.log('User has authorised fcm')
              this.registerFcmMessageListener()
            })
            .catch(error => {
              // User has rejected permissions
              console.log('User has rejected fcm permissions, error = ', error)
            })
        }
      })
```
The above code prints 'User has fcm permission'

**Comment by chinalwb** [comment]
@cx5168 Thank you, but this still doesn't work for me.

Here is my code:
```
  getFcmToken() {
    firebase.messaging().getToken()
      .then(fcmToken => {
        if (fcmToken) {
          console.debug('fcm token ==', fcmToken)
          this.props.dispatch(fcmRegister(fcmToken))
        } else {
          // user doesn't have a device token yet
          console.debug('User doesn\'t have a device token yet, token = ', fcmToken)
          firebase.messaging().requestPermission()
          setTimeout(() => {
            this.getFcmToken()
          }, 3000)
        }
      })
  }
```

**Comment by cx5168** [comment]
@chinalwb
It takes time for the server to generate tokens, and getToken can't get tokens without waiting for the server to return the promise. 

In addition, the firebase version of the build.gradle file is recommended to upgrade to the latest. 
app/build.gradle:
```
implementation "com.google.firebase:firebase-messaging:17.3.0"
implementation "com.google.android.gms:play-services-base:15.0.1"
implementation "com.google.firebase:firebase-core:16.0.3"
```

End of the document  to add:
`com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true`

I hope you can succeed.

**Comment by Ehesp** [comment]
@chinalwb `requestPermission` is a promise which you need to wait for

**Comment by chinalwb** [comment]
@cx5168 Thanks very much! `It takes time for the server to generate tokens` would this means, the token finally needs to be generated at fcm server? If so that will make sense, my phone is not able to access to fcm server (but my emulator is able to do that and there is no problem to the emulator).

Thanks again.

**Comment by chinalwb** [comment]
I'll come back to close this thread after I am done with the network problem and double checked.

**Comment by gavin-gmlab** [comment]
I'm also seeing this problem the 1st time I install the app on the actual device. I will need to kill the app then relaunch to get the token successfully. Not great for user experience though. How can we make this more reliable?

**Comment by chinalwb** [comment]
@cx5168 Got it, thanks!

BTW, just FYI, my emulator does provide me the FCM token.

**Comment by jperezr13** [comment]
Hello, in Android 8.0 is not returning the token, there are some solution for this.

**Comment by chinalwb** [comment]
Sometimes I get token = null as well, maybe this issue should be reopen

**Comment by efstathiosntonas** [comment]
Any news in this? Still getting null, tried all methods above

**Comment by efstathiosntonas** [comment]
According to [docs](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId.html#getToken()), getToken() is deprecated. Other than that, docs state:

> Returns the automatically generated token for the default Firebase project.
 This generates an Instance ID if it does not exist yet, which starts periodically sending information  to the Firebase backend (see getId()).
 Returns
 the master token **or null if the token is not yet available**

**Comment by efstathiosntonas** [comment]
Ok folks, here's the deal:

In `RNFirebaseMessaging.java` replace `getToken` method with: 

```
  @ReactMethod
  public void getToken(Promise promise) {
    try {
      String token = FirebaseInstanceId
              .getInstance()
              .getToken("Put here your Sender Id", "FCM");
      Log.d(TAG, "Firebase token: " + token);
      promise.resolve(token);
    } catch(IOException e) {
      e.printStackTrace();
    }
  }

```

don't forget to import `import java.io.IOException;`

Tested on emulator, not on real device.

**Comment by HasanAlyazidi** [comment]
Mr. @efstathiosntonas please bump the package version, so we can update `RNFirebaseMessaging.java` from npm/yarn.

**Comment by efstathiosntonas** [comment]
@faisalpathan have you added google services json and plist from firebase in your project? It seems that  firebase  is not initiating thus you dont have sender id.

**Comment by faisalpathan** [comment]
@efstathiosntonas , google-services.json is already present in android/app folder of the application and also the notification permission is also granted

**Comment by cx5168** [comment]
@efstathiosntonas   I modify it according to your code, not through setTimeOut to get token, not token, and have a warning (Possible Unhandled Promise Rejection (id: 0) Error: SERVICE_NOT_AVAILABLE) 

My configuration is all right. 

Is there any other way?

**Comment by efstathiosntonas** [comment]
@faisalpathan @cx5168 this has nothing to do with this modification, there is something wrong with your setup/configuration. The change I've made is according to [docs](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId#getToken()) so there's nothing wrong.

**Comment by faisalpathan** [comment]
@efstathiosntonas , please can you share your configuration and which version of react-native-firebase you are using ?

**Comment by cx5168** [comment]
@efstathiosntonas  You're right. I've tried several times and I can get token normally. Thank you very much.

**Comment by faisalpathan** [comment]
@cx5168  can you share your configuration as well ?

**Comment by faisalpathan** [comment]
@cx5168 , thank you so much for the configuration , Really Appreciated. Still getting the same error as 

``` Error: INVALID_SENDER
    at createErrorFromErrorData (NativeModules.js:121)
    at NativeModules.js:78
    at MessageQueue.__invokeCallback (MessageQueue.js:398)
    at MessageQueue.js:137
    at MessageQueue.__guardSafe (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:136)
    at debuggerWorker.js:70 ```

**Comment by cx5168** [comment]
@faisalpathan
It looks like an error caused by an invalid registration. I think your google-services.json configuration is not working.

**Comment by caobo171** [comment]
I checked the native code , maybe your issue is like me, I resolved by follow this issue , turn on/off push notification capability 
[https://github.com/firebase/quickstart-ios/issues/111 ](https://github.com/firebase/quickstart-ios/issues/111)
