### ISSUE TITLE
Database Secrets Deprecated: Support for Admin SDK?

### ISSUE THREAD

**Issue by AndrewHenderson** [invertase/react-native-firebase#143]
I noticed the following deprecation notice on my Firebase console.

<img width="949" alt="screen shot 2017-06-02 at 6 21 35 am" src="https://cloud.githubusercontent.com/assets/1031565/26729763/87546530-4763-11e7-8b81-44b64c6c9321.png">

Does RNF support using the new Admin SDK?

**Comment by chrisbianca** [comment]
@AndrewHenderson the Admin SDK is only intended to be run on servers so I can't see a reason why RN-Firebase would need to support it?

Also, the Admin SDK only supports Node, Java and Python, so there'd be no way of supporting it even if we wanted to.

**Comment by AndrewHenderson** [comment]
@chrisbianca I suppose my concern is with the deprecation notice. Do you happen to know if database secrets no longer recommended for new projects?

**Comment by chrisbianca** [comment]
This error has no relation to rn-firebase as you'll be using the .plist or .json file that are supplied by the Firebase console.  Neither use database secrets as they are not meant for client usage.

**Comment by AndrewHenderson** [comment]
@chrisbianca I currently have my secret in the RNFirebase function under the APIKey. Should I not have that there?

const firebase = new RNFirebase({
  googleAppID: 'XXXXX',
  databaseURL: 'https://xxx.firebaseio.com',
  storageBucket: 'xxx.appspot.com',
  APIKey: 'XXXXXX,
  debug: true
});

**Comment by chrisbianca** [comment]
For iOS: http://invertase.io/react-native-firebase/#/installation-ios?id=_1-setup-google-servicesplist-and-dependencies
For Android: http://invertase.io/react-native-firebase/#/installation-android?id=_1-setup-google-servicesjson

That way you don't need any of the secrets in the setup.  You can see the configuration options here: http://invertase.io/react-native-firebase/#/usage
