### ISSUE TITLE
"createRepo called for Repo that already exists"

### ISSUE THREAD

**Issue by ollieh-m** [invertase/react-native-firebase#1430]
### Environment
1. Application Target Platform:
iOS

2. Development Operating System:
macOS High Sierra

3. Build Tools:
Xcode 9.4.1

4. `React Native` version:
0.56.0

5. `React Native Firebase` Version:
4.2.0

6. `Firebase` Module:
N/A

7. Are you using `typescript`?
no
---

Our app is crashing sometimes on iOS on the splash screen with the following error reported in crashlytics: 

```
Fatal Exception: RCTFatalException: Exception 'createRepo called for Repo that already exists.' was thrown while invoking on on target RNFirebaseDatabase with params (
    "[DEFAULT]",
    "https://<redacted>.firebaseio.com",
        {
        appName = "[DEFAULT]";
        eventType = value;
        hasCancellationCallback = 0;
        key = "$https://<redacted>.firebaseio.com$/.info/serverTimeOffset${}";
        modifiers =         (
        );
        path = ".info/serverTimeOffset";
        registration =         {
            eventRegistrationKey = "$https://<redacted>.firebaseio.com$/.info/serverTimeOffset${}$0$value";
            key = "$https://<redacted>.firebaseio.com$/.info/serverTimeOffset${}";
            registrationCancellationKey = "$https://<redacted>.firebaseio.com$/.info/serverTimeOffset${}$0$value$cancelled";
        };
    }
)
```

Here is the full stack trace (redacted): [stack_trace.txt](https://github.com/invertase/react-native-firebase/files/2318681/stack_trace.txt)

Googling suggests this may be related to calling database().ref() in a background thread (https://stackoverflow.com/questions/42336400/firebase-crashes-out-of-the-blue-with-repoexists-message) but I don't believe we are calling it from a background thread. Ultimately we start making .ref() calls from componentDidMount() in a regular component.

Any suggestions would be very welcome!

**Comment by ollieh-m** [comment]
For anyone else who encounters this, the problem stemmed from calling firebase.database() in the constructor of a class that was initialised and imported into various react-native sagas, so I think it boiled down to firebase.database() being called very early on in the app lifecycle. I removed it from the constructor and just called firebase.database() as and when it was needed, and haven't had crashes since.

**Comment by kevinvangelder** [comment]
In our use case, we were falling back to the instantiation step if the database wasn't already created, however we ended up with a race condition where there were two simultaneous attempts to access the database resulting in two simultaneous instantiations. Simply running the instantiation as soon as the parent class was instantiated solved this issue and the error.

**Comment by fabellonnoe** [comment]
do not use firebaseDatabase().ref inside componentDidMount

sample format

```
 componentDidMount() {
    this.handleVersionCheck();
  }

  handleVersionCheck = () => {
    //check version in realtime
    const that = this;
    setTimeout(function() {
      firebaseDatabase()
        .ref('/config/version')
        .on('value', snapshot => {
          that.setState({version: snapshot.val()});
        });
    }, 3000);
  };
```
