### ISSUE TITLE
Firebase In-App Messaging (Feature Request)

### ISSUE THREAD

**Issue by kumarpatel** [invertase/react-native-firebase#1431]
https://firebase.google.com/docs/in-app-messaging/

Posted this request at https://boards.invertase.io/react-native-firebase
but the post doesn't seem to show even after filtering via search. Load more button doesn't work either. Which is why I created this feature request issue instead.

**Comment by Salakar** [comment]
Thanks for reporting the issue with the feature board, I will speak with Canny about the issue.

Re in app messaging, you can use it now, see https://twitter.com/mikediarmid/status/1032673313418616833?s=19

We'll look at getting some docs added on the website to indicate how to add the SDKs etc.

**Comment by Salakar** [comment]
@kumarpatel hello, the board issues have been fixed! 👌 Thanks for reporting.

**Comment by brenwell** [comment]
I am curious, is this functionality in? If so from what version. Thanks for all the hard work!

**Comment by Ehesp** [comment]
@brenwell 	it's just an SDK which needs installing, nothing for us to do on the lib.

**Comment by brenwell** [comment]
Gotcha. Thanks

**Comment by GaneshSaiKumar** [comment]
@Salakar  is firebase in-app messaging added to react-native-firebase?

**Comment by brenwell** [comment]
Yes. I have used it, at least

**Comment by GaneshSaiKumar** [comment]
@brenwell can you share me the docs for integration

**Comment by brenwell** [comment]
If I remember correctly this has no React native specific code. Simple follow the standard iOS and Android Firebase installation guides and then start sending

**Comment by GaneshSaiKumar** [comment]
have tried all the possible! still i'm not receiving firebase inapp messages.

FCM are working fine

**Comment by mikehardy** [comment]
@GaneshSaiKumar "all the possible", but you don't list the things? Did you read the blog entry from the firebase team and debug each step one by one to make sure your app works with APNS and FCM works with APNS, so console->FCM->APNS->app works, vs just console->FCM->app? It's a different pathway so FCM->app doesn't indicate much. https://firebase.googleblog.com/2017/01/debugging-firebase-cloud-messaging-on.html

**Comment by GaneshSaiKumar** [comment]
@mikehardy updated my comment plz go through again

**Comment by mikehardy** [comment]
Very strange. Seems easy enough based on the docs. You killed and reopened the app? You are sure your instanceid is correct? Have you tried with the rnfirebase-starter example clean just as a test run? (I always use a new firebase API there first, personally, to keep tests simple and focused)

**Comment by GaneshSaiKumar** [comment]
yeah i've closed and reopend app still not able to get in app message modal in app.
Does firebse in-app messages need FCM integrated? or FIAM alone is an entity?

haven't tried with react-native-firebase-starter but created a new react-native project to test and added firebase to it. not able to figure out the issue

**Comment by brenwell** [comment]
I think i was using `pod 'Firebase/Messaging'` not `pod 'Firebase/InAppMessagingDisplay' not sure what the difference is now

**Comment by GaneshSaiKumar** [comment]
@mikehardy react-native-firebase-starter doesn't have fire base in app messages added by default

I've added following line alone to the downloaded project
    implementation 'com.google.firebase:firebase-inappmessaging-display:17.1.1'
as mentioned here https://firebase.google.com/docs/in-app-messaging/get-started

and tired sending an in-app message. Didn't work

**Comment by mikehardy** [comment]
Strange. I have no personal experience with in-app messaging yet. It seems like it should be easy but obviously not. Maybe some hook or listener isn't attached between react-native-firebase and the firebase android sdk. Or did a simple web sdk test. I'm just brainstorming at this point though - sorry no real answers.

**Comment by GaneshSaiKumar** [comment]
@Salakar  @Ehesp  Hey guys can you please take a look into this!!

**Comment by brenwell** [comment]
From the link above it says

>  In-App Messaging is an essential complement to notifications sent via Firebase Cloud Messaging.

Maybe you need both pods?

**Comment by GaneshSaiKumar** [comment]
might be! 
but react-native-firebase-starter kit comes with FCM by default. So, even then it should be working at least with starter kit

**Comment by Dnyaneshwar1926** [comment]
You have to enable API manually from google console to receive message successfully.

**Comment by Dnyaneshwar1926** [comment]
Question 1:-
In this popup the background color is not shown. It is always white (infact I changed the color on firebase console as per guidelines ). How can I change the background color?

Question 2:-
In this popup is always triggering in splash screen. I want it to trigger in main activity. How to do it?

**Comment by Anshuman71** [comment]
> You have to enable API manually from google console to receive message successfully.

where exactly?

**Comment by Dnyaneshwar1926** [comment]
https://console.developers.google.com

API & Services -> Enable API & Service -> search InAppMessaging -> Enable

![image](https://user-images.githubusercontent.com/49900019/65402351-6ac72580-ddeb-11e9-8e1d-650450e895e6.png)

![image](https://user-images.githubusercontent.com/49900019/65402363-79add800-ddeb-11e9-8a33-634d533ac865.png)
