### ISSUE TITLE
unable to send silent push notification

### ISSUE THREAD

**Issue by rbsl-rimjhim** [invertase/react-native-firebase#1433]
Is there any way to send silent notification i.e. it should not be popped up in notification tray but it should just update some data in background?

I tried removing notification key from post data but it doesn't work because it is required to set atleast the below key in notification (as I am using splash screen component)-
"notification" : {
		"click_action" : "open_event_action"
	}

**Comment by erandagan** [comment]
This has nothing to do with this library.
Check out https://stackoverflow.com/questions/37570200/firebase-silent-apns-notification

**Comment by Salakar** [comment]
@erandagan is correct 👍 Please see the link provided.

Thanks
