### ISSUE TITLE
Clean up firebaseopensource.com listing

### ISSUE THREAD

**Issue by samtstern** [invertase/react-native-firebase#1436]
First of all thanks for adding a `.opensource/project.json` file!  You can already see that this project is now correctly listed in the Android and iOS categories rather than under web (which we were guessing based on the `react` in the name).

You can see the updated page here:
https://firebaseopensource.com/projects/invertase/react-native-firebase/

That said, a few more improvements could be made:

  * Right now the `related` projects links to the starter template.  However that link breaks since the starter project is not listed on the opensource site.  So the two options to fix it are to either remove it from the `related` section or add it to the [additional_projects](https://github.com/firebase/firebaseopensource.com/blob/master/config/additional_projects.json) configuration.
  * We look for a `h1` (in HTML or markdown) to define the "header" section.  The README uses an `h2` at all levels though which results in a sort of empty body section just re-declaring the name.
  * The horizontal lines throughout the README don't render so well on the opensource site.  Happy to take suggestions on what we should do with them!

By the way, it's not required to use your root `README` as the source of the content on the opensource site.  You could make another page (like `docs/FOSDC.md`) and declare that in the `content` property of your `json` config.  Then you could customize how you appear on our site without compromising how you appear to your direct GitHub traffic.

These are all 100% optional suggestions and I am happy to help with PRs if appropriate.

**Comment by Salakar** [comment]
@samtstern thanks for the feedback 👍 and your work on the site 👌 

I've sent over a PR to add to the additional projects section if thats ok? I've also changed the first header to an H1 here: https://github.com/invertase/react-native-firebase/commit/dee357cb26b64ef99af8fd32ea2e2878b467a5d3

For the horizontal lines maybe something like:
![image](https://user-images.githubusercontent.com/5347038/44742796-ac0dd880-aaf8-11e8-959b-b38c24194f26.png)

Same colour as header bottom border, just slightly thicker height.
```css
hr {
    height: .25em;
    padding: 0;
    margin: 48px 0 24px 0;
    background-color: #ebebeb;
    border: 0;
}
```

Will look into maybe doing a separate more specific page to replace the readme usage as well.

**Comment by samtstern** [comment]
Confirmed some of these changes on a local build:

`h1` looking good:
![image](https://user-images.githubusercontent.com/8466666/44743580-bc519380-aab7-11e8-9e54-d8db8a3ef29e.png)

Starter project renders:
![image](https://user-images.githubusercontent.com/8466666/44743597-c70c2880-aab7-11e8-9ece-1042cf1ac95e.png)

The site deploys ever 30m or so, so you should see it reflected live pretty soon.  Thanks for the fast response time!

**Comment by samtstern** [comment]
@Salakar thanks!  I took your `<hr>` style suggestions, only tweaked it a little:
https://github.com/firebase/firebaseopensource.com/commit/bb40108e4d8c1ccf98872b4a9928fb711f20c9ef

Results:
![image](https://user-images.githubusercontent.com/8466666/44744176-582fcf00-aab9-11e8-853f-23f2cf6810ba.png)

![image](https://user-images.githubusercontent.com/8466666/44744193-667deb00-aab9-11e8-8d04-dbab0d8fefe9.png)

**Comment by Salakar** [comment]
@samtstern nice, looks good! 😍 

Going to close this issue and will ping you here or on the other repo if I have any issues or questions 👍 

Will ping you here also once I've done a custom root page.
