### ISSUE TITLE
Objects are not vaild as React child (found : object with keys {$$typeof,type,key, ref,props,_owner,_store})

### ISSUE THREAD

**Issue by sritharanrbt** [invertase/react-native-firebase#1438]
Objects are not vaild as React child (found : object with keys {$$typeof,type,key, ref,props,_owner,_store}). if you meant to render a collection of children, use an array instead

it worked fine on ios build , issue only with on android build 

Reference : 
https://stackoverflow.com/questions/50555275/react-native-objects-are-not-valid-as-a-react-child-found-object-with-keys

By using this reference i tried to use require instead of importing 'react-native-firebase'

but stuck with the same problem , i doest not fade away

### Environment

1. Application Target Platform:

Android

2. Development Operating System:

 macOS Sierra

3. Build Tools:

Xcode 9.3

4. `React Native` version:

 0.56.0

5. `React Native Firebase` Version:

     4.3.8

6. `Firebase` Module:

All 

kindly help with this issue

**Comment by sritharanrbt** [comment]
yeah you are right @Ehesp this is my code fault ,this is the one comes from Mobx  actually i used latest version of React-native that doest not opt for Mobx

**Comment by FibreFoX** [comment]
Hm, I'm still hitting this problem, but unsure if this really is related to this react-native-firebase project. @sritharanrbt did you found your problem? Anything that could help me by my problem?

I'm using latest RN `0.57.3` with React `16.6.0-alpha.8af6728` (as suggested by the RN-team) in combination with react-native-firebase `5.0.0`. In an older project-version the same code works with RN `0.55.4` and react-native-firebase `4.3.8`.

**Comment by FibreFoX** [comment]
Just for reference:

there seemed to be a problem with the used JSC, adding an import to `core-js` "fixed" my problem:
```js
/** @format */

import 'core-js';
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
```

**Comment by hellorachid** [comment]
@FibreFoX Thank you, you made my day
