### ISSUE TITLE
 The confirmation SMS on Android does not work

### ISSUE THREAD

**Issue by sinevitch** [invertase/react-native-firebase#1440]
SMS sends both to iOS and to android (app-release.apk)

I have the data code
![image](https://user-images.githubusercontent.com/35930695/44786638-7242dd80-ab9d-11e8-85a7-d527be4b3ef6.png)

This code works on iOS But throws an error on android (app-release.apk)

"react-native-firebase": "^4.2.0",
"react-native": "0.55.4",

build gradle of my project:

![image](https://user-images.githubusercontent.com/35930695/44787030-9a7f0c00-ab9e-11e8-8379-4ca415406d39.png)
![image](https://user-images.githubusercontent.com/35930695/44787040-a5d23780-ab9e-11e8-907e-28904e57f986.png)

**Comment by Ehesp** [comment]
Hello - what is the error thrown?

**Comment by sinevitch** [comment]
SMS sends only to release version

I can not determine the error

**Comment by Salakar** [comment]
@sinevitch that's not an SMS issue - that's something going on with RN / your rendering. Can you show your full code for UI with SMS auth flow.
