### ISSUE TITLE
Error: Firestore: The service is currently unavailable. (firestore/unavailable).

### ISSUE THREAD

**Issue by quandevelopment** [invertase/react-native-firebase#1441]
### Environment

1. Application Target Platform:
Android

2. Development Operating System:
macOs HighSierra

3. Build Tools:

4. `React Native` version:
0.56.0

5. `React Native Firebase` Version:
4.3.7

6. `Firebase` Module:
Firestore

7. Are you using `typescript`?
no
---

After a while a get the following error:
Error: Firestore: The service is currently unavailable. (firestore/unavailable).
    at createErrorFromErrorData (NativeModules.js:146)
    at NativeModules.js:95
    at MessageQueue.__invokeCallback (MessageQueue.js:392)
    at MessageQueue.js:128
    at MessageQueue.__guard (MessageQueue.js:291)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:127)
    at t (RNDebuggerWorker.js:1)

Then I have to deinstall and reinstall the app to get the connection again.
I tried the new function  
 firebase.firestore().enableNetwork()
but it doesn't work.

Any ideas?

Best Qung

**Comment by alican-k** [comment]
I encountered this error when I used a new fresh firebase project. Firestore database is also needs to be activated on the firebase console.

**Comment by quandevelopment** [comment]
> I encountered this error when I used a new fresh firebase project. Firestore database is also needs to be activated on the firebase console.

So I have to activate Firebase too?

**Comment by f-it-360** [comment]
Hi, I can't solved the issue so I changed to Parse as backend. It works like a charme. Now I just use the Push Server for my App.
Maybe I will try it later again.

Best Qung

**Comment by quandevelopment** [comment]
Hi, I can't solved the issue so I changed to Parse as backend. It works like a charme. Now I just use the Push Server for my App.
Maybe I will try it later again.

Best Qung

**Comment by zhigang1992** [comment]
If you are located in China, FireStore / Google is blocked there.

It'll error out with `firestore/unavailable`

**Comment by SasiKumar-Ramesh** [comment]
@Salakar We are having this issue in our production apps. Please check this  
![screenshot 2019-03-08 at 1 48 43 pm](https://user-images.githubusercontent.com/20661760/54016456-09ba6600-41a9-11e9-9301-f44029125d32.png)

**Comment by haitranhuy** [comment]
any update  for this issues

**Comment by pitchourou** [comment]
Same here , it is a problem

**Comment by hiroyaiizuka** [comment]
+1

**Comment by joeljerushan** [comment]
Someone Help this happens in some times suddenly (not every time)

![image](https://user-images.githubusercontent.com/10111309/69347131-f816e100-0c99-11ea-8bc0-8e71eb13f0d9.png)

**Comment by mgilosfullscaleio** [comment]
[https://medium.com/@chonnaronghanyawongse/coding-diary-why-my-firestore-doesnt-work-2db41fb82121] Helped me, by disabling and enabling the token service.

**Comment by mgilosfullscaleio** [comment]
Previously, this was an intermittent problem(happens 2-3x every night). But I'm getting this error since 3 days ago.

**Comment by tronin** [comment]
I've got the same problem in two different applications in production.

**Comment by zhigang1992** [comment]
One possibility is that it's an error message issue.

when I'm doing `.get({source: 'cachce'})` and the firebase SDK will throw

```
Error Domain=FIRFirestoreErrorDomain Code=14 "Failed to get document from cache. (However, this document may exist on the server. Run again without setting source to FirestoreSourceCache to attempt to retrieve the document " UserInfo={NSLocalizedDescription=Failed to get document from cache. (However, this document may exist on the server. Run again without setting source to FirestoreSourceCache to attempt to retrieve the document }
```

But code 14 will be translated into `FIRFirestoreErrorCodeUnavailable`

with error message of 

```
The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
```

which is incorrect in this case.

**Comment by zootopia106** [comment]
Any solution here?
It's really blocking production release.

**Comment by amitpatelcontract** [comment]
Did you guys figure this one out? Please update if anyone did. Thanks!

**Comment by quantux** [comment]
I'm also having the same problem :/

**Comment by brandtnewww** [comment]
I'm facing the same issue on my App in production now and then.

`Non-fatal Exception: UnhandledPromiseRejection
[firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
<unknown>
`

Would be great to find a workaround soon.

**Comment by tronin** [comment]
Have the same bug
```[firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying wit```

**Comment by kadirakkaya** [comment]
In my case I have array in document and there are 75 items in array. I reduced array items to 50 and error gone.

**Comment by jrgilbert74** [comment]
I get these errors randomly, if I restart the phone they tend to go away.

**Comment by jbromberg** [comment]
Also having this issue. Any updates?

**Comment by VladRDV** [comment]
Are there any updates on this issue?

**Comment by mikehardy** [comment]
Why would there be updates on a closed issue?

**Comment by RichardFevrier** [comment]
Maybe @mikehardy because it should have never been closed in the first place :)

Like @zhigang1992, I can reproduce this issue when I try to get the data from the cache.
On a new device or by deactivating the persistence:

```
await firestore().settings({
  persistence: false,
});
```

**Comment by mikehardy** [comment]
@RichardFevrier this issue is so old, I'd recommend opening a new issue with 100% up to date versions (that is firebase-ios-sdk 6.28.1 and firebase-android-sdk BoM 25.6.0 - it's documented on rnfirebase.io how to override) to make sure we're not chasing phantoms.

You can't imagine the number of "I have the exact same problems" we get that are actually the same problem about 1% of the time, so we work with the info we have available, doing our best, and close things when they seem like the *original* issue is closed. With the dates on these comments so old, definitely go for a new issue with up to date versions, necessary info provided, and a repro  App.js if at all possible

**Comment by guiima** [comment]
I had the same problem. In my case it was the settings on google-services.json that were wrong. Maybe it will help someone.

**Comment by emreakcadag** [comment]
It's. revelant with **_firestore.disableNetwork()**

When you disable network then enable again; it does not work. It keeps disabled. So that's why getting this error. 

And also I could not find any solution.

**Comment by mikehardy** [comment]
@emreakcadag there have been several upstream issues related to this, out of our control. If you instrument the code and verify we are calling the native disable/enable network APIs then the react-native-firebase module is doing what it can. You might verify with firebase-android-sdk 25.9.0 and firebase-ios-sdk pod 6.31.0 to make sure that with up to upstream SDKs this is still happening, and check their issues lists (they are on github as well under those repo names)

**Comment by melodysdreamj** [comment]
I had the same issue. It was a problem because the time of the test device was 1 month ago. After correcting the time, all the problems were solved.

**Comment by mikehardy** [comment]
Interesting @melodysdreamj that info may help some people. It's important to note that if you are a parent with children, it's currently a "thing to try" for children to get around various parental restrictions by setting the time on their borrowed parent's phones back in time, so having incorrect times/dates set on devices happens more than you would think.

**Comment by davenlin19** [comment]
Still have this problem. I tried to change the timezone, signout at the beginning of App.js but no luck :( @mikehardy do you have any idea how to fix it once for good? Thanks

**Comment by lpetkov-sw** [comment]
Hello, we have the same problem. Once the device network is loose and then back again the firestore keep returning old data. It keeps using the cache without synchronization until the app is not reinstalled (the local storage is deleted). Please share some workarounds if you have some. 

P.S. That's happening on iOS/Android simulator/emulator and devices as well.

**Comment by mikehardy** [comment]
The best thing to do is make sure you are using the most up to date firebase-android-sdk underling, which is I think 25.13.0 (26.0.0 won't be possible to use until #4471 lands and forward ports to the new major version of the upstream library). Information on how to override the underlying SDK version (in case you do not have the most current) is on the rnfirebase.io main page I believe

**Comment by aliasad106** [comment]
It is still happening on the latest verison.

**Comment by mikehardy** [comment]
@aliasad106 does not move the issue forward but does generate notifications for everyone. How did it go when you tried each of detailed items in the comments above?

**Comment by aliasad106** [comment]
@mikehardy I'm sorry 
This is my environment. 
1. React Native 0.63.3 
2. @react-native-firebase/app" 10.1.0
3.@react-native-firebase/firestore 10.1.1
4. Firebase region Europe London
5. Issue experienced in Pakistan
6. Happens when network is 2G or slower( everything else works )

**Comment by mikehardy** [comment]
So, you have outdated versions (likely not a cause, but still, why chase issues on old versions?) and on likely unreliable networks firestore is unavailable? That seems like expected behavior? There is all sorts of information you do not address about caching, network availability network state etc above.

**Comment by TrungJamin** [comment]
i got the s

**Comment by TrungJamin** [comment]
i got the same and here is the way i fixed it.
i just run yarn add @react-native-firebase/app and yarn add @react-native-firebase/firestore
I also close my simulator and wipe the data before turn it on again and it worked for me. Hopefully it works for you guys.

**Comment by mzyadatuba** [comment]
This is really strange issue, yesterday everything was working just fine, now this error keeps showing

[cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.

Its really a blocker and there is not valid explanation or solution!

Why everything related to Firebase always buggy and unstable!

**Comment by mikehardy** [comment]
Everything related to Firebase is pretty stable and works great for me.

Sorry you're having this experience, I can understand if you suffer frequent problems it is frustrating.

I imagine you either are attempting to use a VPN that has been flagged for abuse by google and blocked, or you don't have your project set up correctly to generate tokens (like, the device check API is not enabled or is failing for some reason) so firestore no longer believe it has sufficient privileges to authenticate to the cloud backend and fails you

**Comment by jonathanmv** [comment]
In my case I was getting the error from the android emulator running on mac. 
I didn't notice that the **android emulator didn't have internet connexion**. 
I fixed it by adding a DNS Server as suggested in this [StackOverflow answer](https://stackoverflow.com/questions/44535500/internet-stopped-working-on-android-emulator-mac-os).

That solved the emulator-not-having-internet issue, which then solved the `firestore/unavailable` issue.

**Comment by AbhiShrek** [comment]
I am having this issue on mac on Android Emulator only.
iOS emulator is running fine and is able to read the exact same data.
it's not the DNS or VPN issue, as it occurs randomly. Mostly it runs fine, but suddenly one rainy day, it gives the Error.

**Comment by haoyuant** [comment]
Having this issue on some Android devices, and it seems that this happens quite often on some of the users' phones. I believe it is related to the refresh token, but don't know how to fix it.

**Comment by mikehardy** [comment]
@haoyuant my first suspicion is always a VPN for firestore unavailable. If it's not that, then if your thunch about refresh tokens is right, check all the google cloud platform API access around auth tokens and device check APIs etc

**Comment by haoyuant** [comment]
Hi @mikehardy, I already checked the API settings, looks all good and Firebase works most of the time. All of the users reported this issue are in Australia and I believe they don't use any VPN, and their network works normally since they can use other apps without any problem. If the unavailable issue occurs, the Firebase services including Cloud Functions, Authentication(network request failed) and Firestore will fail in a row even I already implemented some sorts of retry, then the users need to restart the app to fix the problem. I don't think the app itself has some logical bugs that lead to this issue, since even the very simple Firestore query on the login page fails randomly. Only happens on Android.

**Comment by mikehardy** [comment]
This may need closer work with a friendly user, a native reproduction tester app from firebase-android-sdk and some careful testing / display of Auth token / refresh token status along with network availability testing / display that user could run / send results with. No idea how we could reproduce without being in situ on the affected network

**Comment by haoyuant** [comment]
Yea actually my client she's one of the affected user, she did run some tests for me on her phone, like I told her to switch the network and make sure the network was working well, and she tried wifi/4g/other guy's hotspot, but the same issue kept happening. According to her report, when this bug occurred, she restarted the app, but the app asked her to sign in again, so it seems that the refresh token expired somehow, which I believe is same as the issue discussed in this post https://medium.com/@chonnaronghanyawongse/coding-diary-why-my-firestore-doesnt-work-2db41fb82121

I added some code to catch the unavailable exception, and tried to get the refresh token from the cloud but in some cases (roughly 50% of the time) it still failed 3 times in a row with roughly 3 sec retry delay for each.

**Comment by mikehardy** [comment]
This sounds really frustrating, it's clear you've put some effort in to this. Your retry attempts sound reasonable, but doesn't it seem like the most likely path is still a network error of some sort?
I'd make 100% sure you are on the most up to date versions of everything (there are changes in this area periodically...firebase-android-sdk 28.3.1 is most recent, firebase-ios-sdk is 8.5.0 most recent) and if your client is affected that's a good opportunity to go for a native reproduction. This will *have* to be pursued upstream with the firebase team, we have no ability at the react-native level to affect these things, it's all in the underlying firebase-android-sdk and they'll need a native reproduction. They do provide quickstarts to make it almost painless to generate a little side-loadable debug app though: https://github.com/firebase/quickstart-android/tree/master

**Comment by haoyuant** [comment]
Yea I think this is more likely a network error or something wrong with the native implementation because the same issue is happening on Flutter. I'll try, thanks for your help: )

**Comment by usama-asfar** [comment]
Not resolved 

```
[Error: [firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.]
```

React Native And Firebase versions
```
react-native-cli: 2.0.1
react-native: 0.64.2
```
```json
"@react-native-firebase/app": "^13.0.1",
"@react-native-firebase/firestore": "^13.0.1",
```

React Native Info 
```
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-2377M CPU @ 1.50GHz
    Memory: 285.96 MB / 11.49 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.0 - /usr/bin/node
    Yarn: 1.22.11 - /usr/bin/yarn
    npm: 8.1.0 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.2 => 0.64.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mikehardy** [comment]
There are a variety of reasons this can happen. One typical reason is VPNs for instance.
This is definitely not a problem with the module, it's underying cloud service network expectations + the native SDKs, there is nothing actionable in this repo, sorry

**Comment by usama-asfar** [comment]
Please make sure you have enabled Firestore on the Firebase console.

**Comment by cedrickjames** [comment]
Can  anyone solve this error? My app is running very well and then it suddenly give error like this.

**Comment by mikehardy** [comment]
@cedrickjames all sorts of reasons it can happen. My (not-)favorite is apparently firebase won't service requests from many VPNs. Another is if an auth token failied, that chains into a firestore error, and auth tokens can fail for various reasons my (not-)favorite one there being if in google cloud platform console the correct APIs aren't enabled or are restricted or something. How you troubleshoot it depends on what your hunches are but it always boils down to slowly bisecting environment and code. Try a completely new throwaway project and hook to that if you're not sure your google cloud stuff is right. Check a different network path to end device if that's a thing. Keep brainstorming and testing.

**Comment by cedrickjames** [comment]
Thankyou for the tips @mikehardy. I hope this will works.

**Comment by cedrickjames** [comment]
I tried to update my firebase package by adding  yarn add @react-native-firebase/app, same with firestore and enable api in google cloud  platform console. It workssss. But i dont know it will not happen again. Thanks guys

**Comment by mikehardy** [comment]
It will stop working if you try certain VPNs or disable certain APIs in google cloud platform console :-). Don't do that :laughing: ? Glad it's working!

**Comment by funyin** [comment]
Solved the issue in Flutter, simply toggle airplane mode and try again

**Comment by eduardofinotti** [comment]
> Solved the issue in Flutter, simply toggle airplane mode and try again

Thanks, solved for me! ASHUHSUASUHSAS

**Comment by hnvcam** [comment]
Hi all, 
This is really a frustrated issue when using this tools, because the unknown error message won't help much. Fortunately, I found this post: https://medium.com/@chonnaronghanyawongse/coding-diary-why-my-firestore-doesnt-work-2db41fb82121, it showed that the refresh token was expired before it gets renew. So I put these code to workaround:
```
auth().useEmulator('http://localhost:9099');
    if (auth().currentUser) {
        const lastSignIn = moment(auth().currentUser.lastSignIn);
        if (lastSignIn.isBefore(moment().subtract(1, 'hour'))) {
            auth().signOut();
        }
    }
```
I'm not sure if everyone has known this yet, so I put the comment on this issue as it is the top searched for firestore/unavailable.

**Comment by eramudeep** [comment]
i am also facing the same issue. 
`
    "react": "17.0.2",
    "react-native": "0.68.2",

    "@react-native-firebase/app": "^14.11.1",
    "@react-native-firebase/auth": "^15.0.0",
    "@react-native-firebase/firestore": "^15.0.0",
`

not understanding what the problem

**Comment by parthya** [comment]
I tried using firestore.clearPersistence() and now getting this 'firestore/unavailable error'. 

I can login but if I check User object, I see "refreshToken: [Exception: Error: firebase.auth.User.refreshToken is unsupported by the native Firebase SDKs".

For same user web version is working fine. 

Tried deleting the app and installing again same issue.

**Comment by frg100** [comment]
> > Solved the issue in Flutter, simply toggle airplane mode and try again
> 
> Thanks, solved for me! ASHUHSUASUHSAS

Same here!!!!
