### ISSUE TITLE
OnNotificationOpened is not triggered in Android 

### ISSUE THREAD

**Issue by nezaidu** [invertase/react-native-firebase#1443]
### Environment
1. Application Target Platform:
Android

2. Development Operating System:
macOS Mojave

3. Build Tools:

4. `React Native` version:

     `0.56.0`
5. `React Native Firebase` Version:
         `4.3.8`

6. `Firebase` Module:
      `com.google.firebase:firebase-messaging:17.1.0`

Send notification from BE. App should be in background. Try opening it from tray. Error in logcat will be the same as:
https://github.com/flutter/flutter/issues/19004

After updating firebase message to `com.google.firebase:firebase-messaging:17.3.0`, i got rid of exception, app opens, but OnNotificationOpened still is not triggered, but initial notification is populated. I believe this has something to do with RNNv2, i got it working by:
![image](https://user-images.githubusercontent.com/3225817/44851617-9b30a480-ac69-11e8-9e48-37503514802a.png)

**Comment by cx5168** [comment]
same issue. any ideas?

**Comment by dakt** [comment]
Same thing here.

**Comment by aaalive** [comment]
Same issue

**Comment by Ehesp** [comment]
Tracking on https://github.com/invertase/react-native-firebase/issues/1331
