### ISSUE TITLE
Firebase Messaging iOS docs may require a wrong version '~> 5.3.0'

### ISSUE THREAD

**Issue by Chi-AnTai** [invertase/react-native-firebase#1444]
### Issue

Hi guys, I found that in docs v4.3.x Cloud Message iOS Installation chapter it says 
"pod 'Firebase/Messaging', ~> 5.3.0", however when I search Firebase in Cocoapods It says the latest version of FirebaseMessaging is 3.1.1.
It took me a few hours trying to install Firebase/Messaging until I found the require version is not even exist LOL, I think this "pod 'Firebase/Messaging', ~> 5.3.0" should be wrong.
And I also want to thank you guys for such great library, its amazing.
https://rnfirebase.io/docs/v4.3.x/messaging/ios
https://cocoapods.org/pods/FirebaseMessaging
### Environment

1. Application Target Platform:iOS

2. Development Operating System:macOS Sierra

3. Build Tools: Xcode 9

4. `React Native` version: 0.55.2

5. `React Native Firebase` Version: 4.3.5

6. `Firebase` Module: messaing

7. Are you using `typescript`? no

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by CarlosTolenk** [comment]
Something similar is happening to me too! If the application is closed I received the notification but I can not access the information that comes in, but instead if the application is active and the notification arrives, it will return the information

**Comment by Salakar** [comment]
@Chi-AnTai `"pod 'Firebase/Messaging', ~> 5.3.0",` does exist - you might need to remove your `Podfile.lock` file before updating to these. ` FirebaseMessaging` - without the `/` i a sub dependency of the Pod.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by ChiAnTai** [comment]
@Salakar I now realize the difference between Firebase/Messaging and FirebaseMessaging, Thanks you very much.
