### ISSUE TITLE
Require Cycle: DocumentReference <> DocumentSnapshot

### ISSUE THREAD

**Issue by TrekSoft** [invertase/react-native-firebase#1446]
### Issue

The newest version of react native (0.57.0-rc.3) has started giving yellow bar warnings about require cycles. 

I'm using v5.6.0 of react-native-firebase and am getting a warning about this require cycle:

Require cycle: node_modules\react-native-firebase\dist\modules\firestore\DocumentReference.js -> node_modules\react-native-firebase\dist\modules\firestore\DocumentSnapshot.js -> node_modules\react-native-firebase\dist\modules\firestore\DocumentReference.js

### Environment

1. Application Target Platform:

Android

2. Development Operating System:

Windows 10

3. Build Tools:

N/A

4. `React Native` version:

0.57.0-rc.3

5. `React Native Firebase` Version:

5.6.0

6. `Firebase` Module:

Firestore

7. Are you using `typescript`?

No

**Comment by TrekSoft** [comment]
Actually it turns out there's a bunch more of them which I could list here as well if interested

**Comment by Salakar** [comment]
@TrekSoft Yes please, could you list them and I'll restructure the code. Thanks

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by TrekSoft** [comment]
Thanks so much @Salakar ! Here's what I have:

- utils\apps.js <> modules\core\app.js 
- modules\admob\index.js <> modules\admob\Interstitial.js
- modules\admob\index.js <> admob\RewardedVideo.js
- database\Reference.js <> utils\SyncTree.js
- modules\core\firebase.js <> utils\apps.js
- modules\firestore\CollectionReference.js <> modules\firestore\DocumentReference.js
- \modules\firestore\DocumentReference.js <> \modules\firestore\DocumentSnapshot.js
- \modules\firestore\DocumentReference.js -> utils\serialize.js ->  \modules\firestore\DocumentSnapshot.js -> \modules\firestore\DocumentReference.js
- modules\storage\index.js -> modules\storage\reference.js -> modules\storage\task.js -> modules\storage\index.js

Thanks again!

**Comment by taschik** [comment]
We are running in to the similar error as well:
```
Require cycle: node_modules/react-native-firebase/dist/modules/firestore/DocumentReference.js -> node_modules/react-native-firebase/dist/modules/firestore/DocumentSnapshot.js -> node_modules/react-native-firebase/dist/modules/firestore/utils/serialize.js -> node_modules/react-native-firebase/dist/modules/firestore/DocumentReference.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

That's our setup here: 
``` React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 985.18 MB / 32.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 26.0.3, 27.0.3, 28.0.1
        API Levels: 23, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.5.2 => 16.5.2
      react-native: ^0.57.0 => 0.57.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```
Firebase: 
```
react-native-firebase@5.0.0-rc2

- Firebase/Core (5.8.1):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.1.4)
  - Firebase/CoreOnly (5.8.1):
    - FirebaseCore (= 5.1.3)
  - Firebase/Messaging (5.8.1):
    - Firebase/CoreOnly
    - FirebaseMessaging (= 3.1.2)
  - FirebaseAnalytics (5.1.4):
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.2)
    - GoogleAppMeasurement (~> 5.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - "GoogleUtilities/NSData+zlib (~> 5.2)"
    - nanopb (~> 0.3)
  - FirebaseCore (5.1.3):
    - GoogleUtilities/Logger (~> 5.2)
  - FirebaseInstanceID (3.2.1):
    - FirebaseCore (~> 5.1)
    - GoogleUtilities/Environment (~> 5.2)
  - FirebaseMessaging (3.1.2):
    - FirebaseCore (~> 5.0)
    - FirebaseInstanceID (~> 3.0)
    - GoogleUtilities/Reachability (~> 5.2)
    - Protobuf (~> 3.1)
```

**Comment by aidan2129** [comment]
Has this been fixed yet? i am also getting the same yellow warnings.

**Comment by aidan2129** [comment]
I have set yellow box to ignore these warnings for now until it is updated. I assume it should be ok if nothing is breaking. To set it to ignore the require cycle warnings do this.

```
import { YellowBox } from 'react-native';

YellowBox.ignoreWarnings(['Require cycle:']);
```

**Comment by ziyafenn** [comment]
Same problem here. RN 0.57.2

**Comment by burtek** [comment]
Can confirm, also getting those

**Comment by jstansbe** [comment]
I'm using core, messaging, and notifications for Android
```
    "react-native": "0.57.4",
    "react-native-firebase": "^5.0.0"
```
console output (the below occurs 10 times):
```
Require cycle: node_modules\react-native-firebase\dist\utils\apps.js -> node_modules\react-native-firebase\dist\modules\core\app.js -> node_modules\react-native-firebase\dist\utils\apps.js
```

**Comment by FadiAboMsalam** [comment]
same problem here

**Comment by Salakar** [comment]
See: https://github.com/facebook/metro/issues/287

**Comment by MrLoh** [comment]
I cannot get rid of them in my console. Would be great if this could be fixed, as it really isn't a very good coding practice

**Comment by llaine** [comment]
Same problem here: 
```
    "react-native": "0.57.8",
    "react": "16.6.3",
```

**Comment by radin-reth** [comment]
- [YellowBox](https://facebook.github.io/react-native/docs/debugging) are Warnings will be displayed on screen with a yellow background.
so in this case, I think `YellowBox.ignoreWarnings` wouldn't help you.

All you need to do to get rid of the warning from console is to patch it in [metro](https://github.com/facebook/metro)
```./node_modules/metro/src/lib/polyfills/require.js```
because the warning come from there, 

Luckily I found [Exilz](https://github.com/Exilz), does this job well.
[Feel free to check it out ->](https://github.com/facebook/metro/issues/287#issuecomment-444177106)

**Comment by ospfranco** [comment]
Require cycles on their own are not bad, while the warning is justified I think trying to get rid of require cycles completely is a bad idea for most projects, this included, adding it to the ignored list would be my way to go.

**Comment by vdlindenmark** [comment]
I'm also getting this on RN0.59... Would be great if this could be fixed.. :-)

**Comment by vgm8** [comment]
Same here, having the same error in RN0.59

**Comment by RWOverdijk** [comment]
Pretty annoying 😄 Anything we can do to help?

**Comment by Salakar** [comment]
This has been completely solved in v6 and a drastic internals rework was the only way to solve something like this, unfortunately. 

v6 is still WIP but if you're one of the lucky few to only need the Firebase modules listed on the [v6 changelog](https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md) then you can switch to v6 already (instructions on changelog). The modules listed there are ready for use despite their 'alpha' tag on npm as these are more like a 'RC' version - alpha tagged as some modules (the ones not listed there) still need to be migrated to v6 still before it can be released - and all the modules require the same version.

**Comment by RWOverdijk** [comment]
I can't wait to use that. I've been waiting for the stack traces... So sexy.

Unfortunately cloud messaging isn't in that list yet.

Thanks for being awesome. 😎

**Comment by TrekSoft** [comment]
Thanks so much Salakar! I'm now teaching a college night class on the side with my job at Amazon and have all of them using Firebase with your library since it is by far the easiest and best database integration I know of with mobile.

**Comment by asherccohen** [comment]
Hi, is this issue now resolved or should we wait for v6?

**Comment by i1990jain** [comment]
What kinda development cycle are you into ???
This is humiliating

**Comment by mikehardy** [comment]
@i1990jain  that is abusive.

**Comment by RWOverdijk** [comment]
@i1990jain wow.

**Comment by Salakar** [comment]
For the record; this was the comment: 

![image](https://user-images.githubusercontent.com/5347038/58387628-7ce5b280-8009-11e9-9282-67da85bebabb.png)

The maintainers and contributors work tirelessly on this project and in most cases during their own personal time. When users such as yourself make these kinds of comments but they themselves don't make an effort to contribute it's hurtful to those who do make the effort. 

We don't tolerate any kind of derogatory comment, so @i1990jain consider this your final warning, you've been blocked from our projects for 72 hours, I suggest you read up on the [code of conduct](https://github.com/invertase/meta/blob/master/CODE_OF_CONDUCT.md) once you come back and before you have any further interactions with this project.

**Comment by Ehesp** [comment]
FYI this will be fixed in v6 which is currently in progress.

**Comment by SaeedZhiany** [comment]
@Salakar 
Here is the list of cycles warning I'm getting, it may be helpful cause I didn't see more of them in the other comments.

```
Require cycle: node_modules\react-native-firebase\dist\utils\apps.js -> node_modules\react-native-firebase\dist\modules\core\app.js -> node_modules\react-native-firebase\dist\utils\apps.js

Require cycle: node_modules\react-native-firebase\dist\modules\admob\index.js -> node_modules\react-native-firebase\dist\modules\admob\Interstitial.js -> node_modules\react-native-firebase\dist\modules\admob\index.js

Require cycle: node_modules\react-native-firebase\dist\modules\admob\index.js -> node_modules\react-native-firebase\dist\modules\admob\RewardedVideo.js -> node_modules\react-native-firebase\dist\modules\admob\index.js

Require cycle: node_modules\react-native-firebase\dist\modules\database\Reference.js -> node_modules\react-native-firebase\dist\utils\SyncTree.js -> node_modules\react-native-firebase\dist\modules\database\Reference.js

Require cycle: node_modules\react-native-firebase\dist\modules\core\firebase.js -> node_modules\react-native-firebase\dist\utils\apps.js -> node_modules\react-native-firebase\dist\modules\core\app.js -> node_modules\react-native-firebase\dist\modules\database\index.js -> node_modules\react-native-firebase\dist\modules\core\firebase.js

Require cycle: node_modules\react-native-firebase\dist\modules\firestore\DocumentSnapshot.js -> node_modules\react-native-firebase\dist\modules\firestore\DocumentReference.js -> node_modules\react-native-firebase\dist\modules\firestore\DocumentSnapshot.js

Require cycle: node_modules\react-native-firebase\dist\modules\firestore\CollectionReference.js -> node_modules\react-native-firebase\dist\modules\firestore\Query.js -> node_modules\react-native-firebase\dist\modules\firestore\QuerySnapshot.js -> node_modules\react-native-firebase\dist\modules\firestore\DocumentChange.js -> node_modules\react-native-firebase\dist\modules\firestore\DocumentSnapshot.js -> node_modules\react-native-firebase\dist\modules\firestore\DocumentReference.js -> node_modules\react-native-firebase\dist\modules\firestore\CollectionReference.js

Require cycle: node_modules\react-native-firebase\dist\modules\firestore\DocumentReference.js -> node_modules\react-native-firebase\dist\modules\firestore\utils\serialize.js -> node_modules\react-native-firebase\dist\modules\firestore\DocumentReference.js

Require cycle: node_modules\react-native-firebase\dist\modules\firestore\utils\serialize.js -> node_modules\react-native-firebase\dist\modules\firestore\FieldValue.js -> node_modules\react-native-firebase\dist\modules\firestore\utils\serialize.js

Require cycle: node_modules\react-native-firebase\dist\modules\core\firebase.js -> node_modules\react-native-firebase\dist\utils\apps.js -> node_modules\react-native-firebase\dist\modules\core\app.js -> node_modules\react-native-firebase\dist\modules\functions\index.js -> node_modules\react-native-firebase\dist\modules\core\firebase.js

Require cycle: node_modules\react-native-firebase\dist\modules\storage\index.js -> node_modules\react-native-firebase\dist\modules\storage\reference.js -> node_modules\react-native-firebase\dist\modules\storage\task.js -> node_modules\react-native-firebase\dist\modules\storage\index.js
```

**Comment by Salakar** [comment]
Thanks @SaeedZhiany - these have all been sorted in the upcoming v6 release

**Comment by Ehesp** [comment]
Pushed up the v6 Firestore changes for this earlier today.

**Comment by ketan1062** [comment]
having the same error in RN0.61.2

**Comment by SaeedZhiany** [comment]
@ketan1062 
As @Ehesp said in [this comment](https://github.com/invertase/react-native-firebase/issues/1446#issuecomment-507725574) the problem has been solved in upcoming v6, So we should wait for it.

**Comment by Ehesp** [comment]
v6 has been released for a few months now with this fix.
