### ISSUE TITLE
Dynamic link of react-native-firebase version 4.1.0 does not work on android

### ISSUE THREAD

**Issue by tuan072090** [invertase/react-native-firebase#1449]
I followed exactly[ this tutorial](https://rnfirebase.io/docs/v4.1.x/notifications/android) to  install dynamic link on android then I handle dynamic link by 2 function
`firebase.links().getInitialLink()
        .then((url) => {
            console.log("url.....", url);
        });`
and 
`firebase.links().onLink((url) => {
        console.log("url.....", url);
    });`

I tested by copy and paste the dynamic link to chrome --> it auto open app but the url I logged is always null in both 2 situations (installed and not installed app).

Does anyone has the same issue like me?

**Comment by SnowDang** [comment]
I have the same problem!
