### ISSUE TITLE
previousChildName is completely ignored in `onChildAdded`,  `onChildChanged` and `onChildMoved`

### ISSUE THREAD

**Issue by sgong-gzy** [invertase/react-native-firebase#145]
In RNFirebaseDatabaseReference.java, `handleDatabaseEvent` does not take account into `previousChildName`.

As a result none of `onChildAdded`,  `onChildChanged` and `onChildMoved` are getting the `previousChildName` on Javascript side.

Is there any plan to support `previousChildName`?

Thanks.

**Comment by Ehesp** [comment]
Hey, thanks for the report. Absolutely if it's something we've missed! We'll take a look asap

**Comment by sgong-gzy** [comment]
Hi, that's great! Thanks for your fast response! Can't wait for an update!

**Comment by Ehesp** [comment]
So I added this in a few commits from https://github.com/invertase/react-native-firebase/commit/3809fa8f63c645ee4de7faddf692f31536c04abd onwards. Now the issue is actually that the response on the native side is always null... Will keep looking into it.

**Comment by Ehesp** [comment]
cc @Salakar - did you look into this one? Remember you were looking into it at one point.

**Comment by Salakar** [comment]
Support added in a v2 version - confirmed still working with v3 changes.
