### ISSUE TITLE
firebase.database().cleanup() is undefined

### ISSUE THREAD

**Issue by ShaMan123** [invertase/react-native-firebase#1450]
### Issue

Tried using the function `firebase.database().cleanup()` to remove all database listeners.
Got an error that `cleanup` is undefined.
When searching this repo couldn't find any reference about the function, however my code editor seems to autocomplete it.
**Hope it exists somewhere => extra useful!**

### Environment

1. Application Target Platform: Both

2. Development Operating System: Windows 10

3. Build Tools: Android Studio Oreo (27)

4. `React Native` version: 0.55.4

5. `React Native Firebase` Version: 4.2.0

6. `Firebase` Module: database

7. Are you using `typescript`? no

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
It got removed 🙈 looks like [the types](https://github.com/invertase/react-native-firebase/blob/master/src/index.d.ts#L422) weren't updated to reflect. 

We'll look at getting this added back, but, over at `firebase.utils().X` - to keep it out of the standard SDK API surface.

For now you should be able to do this by doing the following:

```js
import SyncTree from 'react-native-firebase/dist/utils/SyncTree';

SyncTree.removeListenersForRegistrations(Object.keys(SyncTree._reverseLookup));
```

Hope that helps in the meantime. 👍 

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
`firebase.utils().database.cleanup()` is up ready to land in v5.1.0. Will close this now.

Thanks
