### ISSUE TITLE
android duplicate notification

### ISSUE THREAD

**Issue by AZIMAT** [invertase/react-native-firebase#1453]
### Issue
Hi everthing looks ok with my push notification i face issue that my notifications shows duplicate

### Environment

1. Application Target Platform:

2. Development Operating System:

3. Build Tools:

4. `React Native` version:

5. `React Native Firebase` Version:

6. `Firebase` Module:

7. Are you using `typescript`?

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Ehesp** [comment]
Please follow the issue template, and also maybe show some code or more details so we can help.

**Comment by andrewtelkamp** [comment]
@AZIMAT did you ever figure anything out on this?
