### ISSUE TITLE
setWithPriority or setPriority on Reference?

### ISSUE THREAD

**Issue by escobar5** [invertase/react-native-firebase#146]
Can't seem to find a way to set the priority of a reference

**Comment by Salakar** [comment]
Hmm you're right, does seem to be missing this - we'll get them added for the next release. Thanks

**Comment by escobar5** [comment]
Thank you, I've found that for the time being you can set the priority by setting the field ".priority" in the object to update.

**Comment by chrisbianca** [comment]
@escobar5 I've just added these two methods - they'll be included in an upcoming release.  Thanks for reporting the fact they were missing!!
