### ISSUE TITLE
fireStore onSnapshot on collection runs twice for every update on Android (iOS works as expected)

### ISSUE THREAD

**Issue by therise3107** [invertase/react-native-firebase#1460]
This the query 
```
firebase
      .firestore()
      .collection('lists')
      .where(`sharedUids.${uid}`, '==', true)
      .onSnapshot(
        { includeDocumentMetadataChanges: true },
        snapshot => {
          const fromCache = snapshot.metadata.fromCache ? 'from cache' : 'from server'

          snapshot.docChanges.forEach(change => {
            const data = change.doc.data()

            if (change.type === 'added') {
              dispatch({ type: 'ADD_LIST_FINISH', payload: data })
            }
            if (change.type === 'modified') {
              dispatch({ type: 'UPDATE_LIST_FINISH', payload: data })
            }
            if (change.type === 'removed') {
              dispatch({ type: 'DELETE_LIST_FINISH', payload: data })
            }
          })
        },
        error => dispatch({ type: 'LIST_ERROR', payload: error })
      )

```
Every time I make a local change above query dispatches `UPDATE_LIST_FINISH` reducer twice on android which re-render my component twice.

| Platform 	| Status  	|
|----------	|---------	|
| iOS      	| Working 	|
| Android  	| Bugged  	|

| Module                	| Version 	|
|-----------------------	|---------	|
| node                  	| 8.9.4   	|
| npm                   	| 5.6.0   	|
| react-native          	| 0.55.4  	|
| react-native-firebase 	| ^3.0.5  	|

Development Operating System:
`macOS High Sierra 10.13.6`

Are you using `typescript`
`No`

Thanks in advance

**Comment by therise3107** [comment]
Found the solution removing `{ includeDocumentMetadataChanges: true }` solved it
Closing the PR

**Comment by 007Arkadeep** [comment]
Add this. I got perfect result. { includeMetadataChanges: false } solved it.
Code Snippet : 

this.db = firebase.firestore();
this.db.collection("YOUR_COLLECTION_NAME").onSnapshot({ includeMetadataChanges: false },(snapshot) => {
  snapshot.docChanges().forEach((change) => {
      if (change.type === "added") {
          console.log("Added: ", change.doc.data());
      }
      if (change.type === "modified") {
          console.log("Modified: ", change.doc.data());
      }
      if (change.type === "removed") {
          console.log("Removed: ", change.doc.data());
      }
  });
});
