### ISSUE TITLE
Last versions of of all necessary modules doesn't work.

### ISSUE THREAD

**Issue by berpcor** [invertase/react-native-firebase#1463]
Hello.
Installation of React Native Firebase is real pain. 
For the moment the latest versions of all necessary modules doesn't work. Only set of versions from starter kit works. Moreover, even in starter kit **multiDexEnabled true** is used. As I understand this is a temporary variant of solving the problem. Is it normal?

**Comment by Salakar** [comment]
The latest versions of the SDKs do work, use /tests app in in this repo as a reference for the versions, the starter will be updated once we're finished with v5.
