### ISSUE TITLE
When sending message from php the app is crashed.

### ISSUE THREAD

**Issue by tareq0065** [invertase/react-native-firebase#1465]
### Issue

When I am sending the message from php curl the app is crashing instead of showing notification. Is there any solution, please. But app is getting BG response if I use `AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => bgMessaging);`. Otherwise its crushing. I am using genymotion Google pixel 7.1.0 emulator to test. its getting message when I am using firebase console to send message.

![unknown](https://user-images.githubusercontent.com/25137925/45164846-46ff6480-b215-11e8-8a87-f1d216e703f7.png)

The response when using
`AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => bgMessaging);`

![screenshot_1](https://user-images.githubusercontent.com/25137925/45164919-6f875e80-b215-11e8-8277-b1ae381f9d15.png)

### Environment

1. Application Target Platform:

Both

2. Development Operating System:

macOS Sierra, Windows 10

3. Build Tools:

Xcode/ Android Studio

4. `React Native` version:
"react-native": "^0.55.3"

5. `React Native Firebase` Version:

"react-native-firebase": "^4.3.6"

6. `Firebase` Module:
Push notification.

7. Are you using `typescript`?
no

**Comment by Ehesp** [comment]
Please could you open Android studio and show us the native error when it crashes. Cheers.
