### ISSUE TITLE
App Crash When Open

### ISSUE THREAD

**Issue by abhishektaneja09** [invertase/react-native-firebase#1471]
com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets (CatalystInstanceImpl.java)
com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets (CatalystInstanceImpl.java:216)
com.facebook.react.bridge.JSBundleLoader$1.loadScript (JSBundleLoader.java:31)
com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle (CatalystInstanceImpl.java:234)
com.facebook.react.ReactInstanceManager.createReactContext (ReactInstanceManager.java:1114)
com.facebook.react.ReactInstanceManager.access$900 (ReactInstanceManager.java:113)
com.facebook.react.ReactInstanceManager$5.run (ReactInstanceManager.java:911)
java.lang.Thread.run (Thread.java:760)

**Comment by Ehesp** [comment]
Nothing here relates to this lib. Please provide more information.
