### ISSUE TITLE
firebase.messaging().onMessage isn't triggered

### ISSUE THREAD

**Issue by victormarcel** [invertase/react-native-firebase#1473]
i am trying to received data messages on my app react-native using firebase.messaging().onMessage, i am sending messages through firebase console, but the messages is not calling onMessage method.

i am trying like this

```
constructor(props){
        super(props);
        this.onMessageListener();
}

onMessageListener = firebase.messaging().onMessage(message => console.log("mensagem enviada"))

```

"react-native": "0.55.4",
"react-native-firebase": "^4.3.8",

**Comment by aaalive** [comment]
Have same issue

**Comment by victormarcel** [comment]
@aaalive, i could fix this issue.
So, my problem was that i was sending messages through firebase console, but the messages sent from there are notifications, calling the method:

```
firebase.notifications().onNotification((notification: Notification) => {
    // Process your notification as required
});
```

For sending messages, read this [documentation](https://firebase.google.com/docs/cloud-messaging/admin/send-messages). Using the FCM admin, you can send messages to devices using fcm token.

**Comment by victormarcel** [comment]
@kimberlyluna , i am using this versions:

```
implementation "com.google.firebase:firebase-core:16.0.1"
implementation "com.google.firebase:firebase-messaging:17.1.0"
```

**Comment by aaalive** [comment]
Thank you for your answer. None of the call back of this lib called
unfortunately. I'm trying to understand at the moment may be this
watchman.. or so

**Comment by Strate** [comment]
Solved issue by using react-native-firebase notifications module, instead of messaging

**Comment by ErAz7** [comment]
I've not tried your solution but if the FCM console messages are only caught by onNotification listener, then why firebase official example for JS catches FCM console messages with onMessage ?
