### ISSUE TITLE
Firebase storage putfile is full of problems 

### ISSUE THREAD

**Issue by amitbravo** [invertase/react-native-firebase#1475]
with react-native-firebase v4.3.5 when I uploading a file using firebase.storage().ref(filename).putFile(), as soon as the file uploading is done, device starts downloading heck of data even in MBs in speed and it never ends until I crash the app , otherwise device becomes very hot and all battery drains in few minutes, so I decide to  upgrade to 4.3.8 and also removed crashlytics and performance modules , it goes fail silently. it does not upload file at all . I thought in the beginning that its due to react-native-image-crop-picker library which I used to pick an image from image gallery or camera , but it happens ditto with react-native-document-picker too which I use to select and upload pdf and other doc files. 
however, things are doing well with ios. (I did not try 4.3.8 as 4.3.5 is already doing fine)
### Environment

1. Application Target Platform: Android
2. Development Operating System: macOS Sierra 10.13.6
3. Build Tools: Android studio 3.1.3 ( I do not use it to build though ) , Android SDK version : compileSdkVersion 27
buildToolsVersion "27.0.3"
targetSdkVersion 27
4. `React Native` version:  "react-native": "^0.55.4"
5. `React Native Firebase` Version: 4.3.5 and 4.3.8
6. `Firebase` Module: database, auth, messaging, storage ( just removed crashlytics and perf )
7. Are you using `typescript`? NO
android/app/build.gradle

  implementation project(':react-native-firebase')
    implementation "com.google.android.gms:play-services-base:15.0.1"
    implementation "com.google.firebase:firebase-core:16.0.1"
    implementation "com.google.firebase:firebase-auth:16.0.2"
    implementation "com.google.firebase:firebase-database:16.0.1"
    implementation "com.google.firebase:firebase-messaging:17.1.0"
    implementation "me.leolin:ShortcutBadger:1.1.21@aar"
    implementation "com.google.firebase:firebase-storage:16.0.1"

**Comment by Salakar** [comment]
Hey, Please can you show your code usage, this sounds like something may be calling itself in a loop in your code potentially?

**Comment by amitbravo** [comment]
I came to know that it was not an issue related to storage at all. I was triggering a cloud function to send push notifications to users right after uploading an image/file  this cloud function was something like 

 ````
 return admin.messaging().send(payload)
          .then( (response) => {
            console.log("Successfully sent message:", response);
            return;
          })
          .catch( (error) => {
            console.log("Error sending message:", error);
            return;
          });
````
and when I trigger the function , it takes lot of time to finish with that log e.g. 
Execution took 60006 ms, finished with status: 'timeout'
and when this above line appears in the function log , the moment app start to download heck of a data and stuck in some kind of infinite loop , but when I change the above code with this 
````
admin.messaging().send(payload)
        
res.send("success");
````
it execute with in 8ms with status '200' and WOLLA!! no stupid downloading , I really do not know how it works but I know that we really need to return some kind of status 200 message if we trigger a cloud function with in app. sorry for bad english.
