### ISSUE TITLE
Can't build error: cannot find symbol

### ISSUE THREAD

**Issue by damathryx** [invertase/react-native-firebase#1477]
### Issue
I am not able to build in android, and have been stuck on a loop. I am getting this error
> Task :react-native-firebase:compileDebugJavaWithJavac FAILED
```
/path-to-project/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/invites/RNFirebaseInvites.java:169: error: cannot find symbol
        mPromise.resolve(Arguments.fromList(Arrays.asList(ids)));
                                  ^
  symbol:   method fromList(List<String>)
  location: class Arguments
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-firebase:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

this is my [android/build.gradle](https://gist.github.com/damathryx/47181acb912d86fa26c602d2fe37d2c5)

this is my [app/build.gradle](https://gist.github.com/damathryx/3a9d4347887d374faf3207fa6462da6c)

### Environment

1. Application Target Platform:

Android

2. Development Operating System:

macOS High Sierra

3. Build Tools:

Java 8, 

4. `React Native` version:

0.47.1

5. `React Native Firebase` Version:

4.3.8

6. `Firebase` Module:

NA

7. Are you using `typescript`?

NO
---

**Comment by damathryx** [comment]
ok problem is that React Native version is not supported

**Comment by nafisholeh** [comment]
which version are you using now @damathryx ?
I had the same problem and my environment are the same with yours

**Comment by wmonecke** [comment]
I have the same problem @damathryx. Could you elaborate on what you did?
