### ISSUE TITLE
Link Multiple Auth Providers to an Account

### ISSUE THREAD

**Issue by wbattel4607** [invertase/react-native-firebase#148]
I've got a question, and if the answer is no then it's a feature request.

Does this library currently support multiple auth providers per user? Firebase has the ability to link multiple providers to individual user accounts, such as email and phone, or Facebook and phone, etc...

Below is their documentation for iOS & Android, as well as JavaScript web apps. It seems to me like it wouldn't be terribly hard to port to react-native given it's just a series of functions already available natively for all applicable platforms.

iOS: https://firebase.google.com/docs/auth/ios/account-linking
Android: https://firebase.google.com/docs/auth/android/account-linking
Web: https://firebase.google.com/docs/auth/web/account-linking

We'd **really** like to use this, so I hope it's something that will ship with V2 if it's not already capable.

Thanks!

**Comment by Salakar** [comment]
It does support multiple auth providers, you'd do it the same way you would if you were using the web sdk, using `currentUser.link()`. 

An example can be found in the test suites here: https://github.com/invertase/react-native-firebase/blob/master/tests/src/tests/auth/authTests.js#L34, this example upgrades a guest user to a registered user using `link`.

There's also an example of logging in with facebook on the authentication docs, bottom of the page.

Hope that helps :)

Side note: in v2 this becomes `linkWithCredential` to match the web sdk v4 changes.

**Comment by wbattel4607** [comment]
Thank you!
