### ISSUE TITLE
undefined is not an object (evaluating 'new _firebase2.default.notifications.Android.Channel')

### ISSUE THREAD

**Issue by mcampsall** [invertase/react-native-firebase#1480]
### Issue

I am trying to create a channel for android notifications using:

```
// Build a channel
    const channel = new firebase.notifications.Android.Channel(
      "channelID",
      "Notifications Channel",
      firebase.notifications.Android.Importance.Max
    ).setDescription("Notifications channel");

    // Create the channel
    firebase.notifications().android.createChannel(channel);
```

which gives me the error: `undefined is not an object (evaluating 'new _firebase2.default.notifications.Android.Channel')`

app/build.gradle dependencies:

```
dependencies {

    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:23.0.1"
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation(project(':react-native-firebase')) {
        transitive = false
    }

    // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation "com.google.firebase:firebase-core:15.0.2"
    implementation "com.google.firebase:firebase-analytics:15.0.2"
    implementation "com.google.firebase:firebase-messaging:15.0.2"
//    implementation 'me.leolin:ShortcutBadger:1.1.21@aar' // <-- Add this line if you wish to use badge

    implementation project(':react-native-navigation')
    implementation project(':react-native-localization')

}
```
### Environment

1. Application Target Platform:

Android

2. Development Operating System:

macOS High Sierra

3. Build Tools:

Android Studio 

4. `React Native` version:

    "react-native": "0.55.3",

5. `React Native Firebase` Version:

    "react-native-firebase": "^4.3.8",

6. `Firebase` Module:

Notifications

**Comment by mcampsall** [comment]
I updated to the latest version of RNFirebase (4.3.8) and it still occurs

**Comment by iamsoorena** [comment]
I have this exact problem.

**Comment by rockerkk** [comment]
Have you followed initial setup guide, messaging setup guide and notifications setup guide?

initial setup guide: https://rnfirebase.io/docs/v4.3.x/installation/initial-setup
messaging setup guide: https://rnfirebase.io/docs/v4.3.x/messaging/android
notifications setup guide: https://rnfirebase.io/docs/v4.3.x/notifications/android

**Comment by Patrick64** [comment]
I also have this problem on "react-native-firebase": "5.2.2" and have followed those initial setup guides, Any solutions??
