### ISSUE TITLE
Click notification but don't disappear

### ISSUE THREAD

**Issue by lizhuoyuan** [invertase/react-native-firebase#1482]
### Issue

```
this.notificationListener = firebase.notifications().onNotification((notification: Notification) => {
            //处理通知
            console.log('---notificationListener:', notification);
            const channel = new firebase.notifications.Android.Channel('test-channel', 'Test Channel', firebase.notifications.Android.Importance.Max)
                .setDescription('My apps test channel');
            // Create the channel
            firebase.notifications().android.createChannel(channel);
            const thisNotification = new firebase.notifications.Notification()
                .setNotificationId(notification._notificationId)
                .setTitle(notification._title)
                .setBody(notification._body)
                .setData(notification._data)
                .android.setChannelId('channelId')
                .android.setSmallIcon('ic_launcher');
            // Build a channel

            firebase.notifications().displayNotification(thisNotification);


        });
```
![image](https://user-images.githubusercontent.com/15923901/45342936-f2bc0200-b5d1-11e8-9692-d092980a3739.png)
I  clicked it ,  but it still here . I hope it will hide or disappear.
Please tell me what should to do , thank you!

### Environment

1. Application Target Platform:

android

2. Development Operating System:

  Windows 10 

3. Build Tools:

  Android Studio 3.2,   Android 8.1

4. `React Native` version:
  0.55.0)  

5. `React Native Firebase` Version:

 (e.g. 4.1.0)

6. `Firebase` Module:

 notifications

7. Are you using `typescript`?
no
---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by lizhuoyuan** [comment]
@agungjk-okadoc 
firebase.notifications().removeDeliveredNotification(notification._notificationId)

**Comment by LorandP** [comment]
`firebase.notifications().removeDeliveredNotification(notification._notificationId)` is not working react-native: 0.57.7 and firebase 4.3.8
