### ISSUE TITLE
support android.setChronometerCountDown parameter in notifications

### ISSUE THREAD

**Issue by nenti** [invertase/react-native-firebase#1483]
Missing android notification option for chronometer to recalibrate notification timers to count down rather than counting up. This is used for:
- timer alarms that occure in future and you want to inform the user about the exact time remaining to the event
- playback of media, displaying time remaining in the current asset playing

https://developer.android.com/reference/android/app/Notification.Builder.html#setChronometerCountDown(boolean)

**Comment by Salakar** [comment]
@nenti thanks for this - please can you raise this on our feature request board: https://boards.invertase.io/react-native-firebase

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
