### ISSUE TITLE
Send Cloud Message to IOS device in development failed.

### ISSUE THREAD

**Issue by lazyhoneyant** [invertase/react-native-firebase#149]
I followed all steps in firebase.google.com/docs/cloud-messaging/ and http://invertase.io/react-native-firebase/#/firebase-setup.

To test Cloud Message, I send a message via the firebase console.
But I couldn’t send messages. Firebase console status of sending was failed.

I've tested 3 circumstances.

1. IOS Simulator

It works. Background notification does not work. but onMessage by token works.

**2. Real Device(iPhone) in Development**

It doesn't work. 
onMessage doesn't work by the token. 
Background notification doesn't work too.

3. Real Device in Release.

It works well.

Can I only debug on Real Device in Release mode?
I want to test and debug the app on the Real Device on Development.
Is it impossible?

**Comment by Ehesp** [comment]
Hey, Notifications don't work on the emulator.

As for prod/dev, have you uploaded your development key to the firebase
console?

**Comment by chrisbianca** [comment]
@lazyhoneyant As @Ehesp mentions, notifications don't work on the simulator - a restriction by Apple for some reason.

It certainly sounds like a configuration problem if everything is working fine with your release build. I for one have notifications working fine in development mode on a real device.

This article is a great resource for debugging where the issues might lie: https://firebase.googleblog.com/2017/01/debugging-firebase-cloud-messaging-on.html

**Comment by lazyhoneyant** [comment]
@Ehesp @chrisbianca 
thanks for the advice.
I found it wasn't the problem of this library. I have two accounts for Firebase.  One is for development, the other one is for production. and I control the multiple ' GoogleService-Info.plist ' depending on environments. On simulator receive messages on GoogleService-Info-dev.plist but On Device switched to production GoogleService-info.plist. It was my problem. I don't know exact solution for controlling the both development and production. but It's ok. I'm digging.
Thanks for the reply.

**Comment by ollydixon** [comment]
The comments in this issue are wrong.
``Data notifications`` work on the simulator just not displayed ``push notifications``.
You can use FCM with simulator for things like ``onMessage``
