### ISSUE TITLE
Crashlytics log doesn't show in Firebase Dashboard

### ISSUE THREAD

**Issue by anhtuank7c** [invertase/react-native-firebase#1490]
### Issue

I tried to `recordError` in `Crashlytics` but doesn't see the result on Firebase Crashlytics Dashboard
I don't know exactly how many hours must be spent to see the result.

```
crashlytics.setStringValue('stack', `AAA`)
crashlytics.setStringValue('fileName', `App.js`)
crashlytics.setStringValue('lineNumber', `30`)
crashlytics.recordError(0, `RN Fatal: TEST CRASHLYTICS`)
```

### Environment
```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 43.20 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.2.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.1
        API Levels: 21, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.0 => 0.57.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-extended-cli: 1.0.202
      react-native-git-upgrade: 0.2.7
```
Are you using `typescript`: No

### Crasylytics Dashboard
<img width="1162" alt="screen shot 2018-09-14 at 11 19 41 am" src="https://user-images.githubusercontent.com/3163410/45529576-2f753c80-b810-11e8-9757-59e65fb60a37.png">

**Comment by Kamill90** [comment]
@anhtuank7c have you eventually seen logs in your console?

**Comment by anhtuank7c** [comment]
@Kamill90 Yes, I have. But the non-fatal log is not a high priority to scan and display in Crashlytics by Google. That's why we could not see it in realtime.

**Comment by sheydarezaee** [comment]
I have been waiting a day to see non-fatal logs and no luck, how can I debug/ resolve this?

**Comment by mikehardy** [comment]
I get crash logs in the crashlytics console more or less within an hour (sometimes just in a few minutes). If it isn't working I'm not sure why but there are lots of reasons - check dsyms status in the console (maybe they aren't uploading?), make sure the android and ios projects are set up correctly with the sha hash for android etc...

**Comment by ghasemikasra39** [comment]
same issue

**Comment by anhtuank7c** [comment]
> @anhtuank7c Have you known how to use log method and others yet?

What do you mean?

**Comment by anhtuank7c** [comment]
@dantn93 What do you mean?

**Comment by yauhenidrobau** [comment]
It's possible because of 64KB log limit
