### ISSUE TITLE
Android Core Firebase Installation issue

### ISSUE THREAD

**Issue by VamshiKyra** [invertase/react-native-firebase#1492]
### Issue
I am trying to use core features, followed the installation guide [https://rnfirebase.io/docs/v4.3.x/installation/android](url)

But after following all the instruction and trying to run the application. I am facing the bug.
![firebase bug](https://user-images.githubusercontent.com/40666762/45592450-d3a7d200-b93b-11e8-879f-59878a9c496b.PNG)

Error:
Metro Bundler ready.

Loading dependency graph, done.
(node:10384) UnhandledPromiseRejectionWarning: Error: Couldn't find preset "module:metro-react-native-babel-preset" relative to directory "C:\\Project\\Authorization"
    at C:\Project\Authorization\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\Project\Authorization\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Project\Authorization\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Project\Authorization\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Project\Authorization\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Project\Authorization\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Project\Authorization\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Project\Authorization\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
(node:10384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Environment

1. Application Target Platform:
Android

2. Development Operating System:
Windows 10

3. Build Tools:
Android Studio 3.1.3
Android SDK 27.0

4. `React Native` version:
0.55.4

5. `React Native Firebase` Version:
4.3.8

6. `Firebase` Module:
auth, messaging, database

7. Are you using `typescript`?
no

---
Package.json
{
  "name": "Authorization",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "babel-preset-react-native": "^4.0.1",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-firebase": "^4.3.8"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "^0.45.3",
    "react-test-renderer": "16.5.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

My git repo: https://github.com/VamshiKyra/Authorization

**Comment by mdmush** [comment]
- Update your package.json with below:
```
{
  "name": "Authorization",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.5.0",
    "react-native": "0.57.0",
    "react-native-firebase": "^4.3.8"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.45.5",
    "react-test-renderer": "16.5.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

- Delete your **[YOUR_PROJECT_FOLDER]/node_modules/**
- [Optional] `watchman watch-del-all && rm -rf node_modules/ && yarn cache clean && yarn install && yarn start -- --reset-cache` 
- Run `npm install` now
