### ISSUE TITLE
subscribeToTopic with multiple registration tokens  failing with invalid token format

### ISSUE THREAD

**Issue by amitbravo** [invertase/react-native-firebase#1496]
firebase.messaging().subscribeToTopic(devices, 'employeechat') where _devices_ is an array containing devices tokens of employees

function is failing with **invalid taken format** however, I am using only alphanumeric characters in topic name.

Environment
Application Target Platform: Android
Development Operating System: macOS Sierra 10.13.6
Build Tools: Android studio 3.1.3 ( I do not use it to build though ) , Android SDK version : compileSdkVersion 27
buildToolsVersion "27.0.3"
targetSdkVersion 27
React Native version: "react-native": "^0.55.4"
React Native Firebase Version: 4.3.5 and 4.3.8
Firebase Module: database, auth, messaging, storage ( just removed crashlytics and perf )
Are you using typescript? NO
android/app/build.gradle
implementation project(':react-native-firebase')
implementation "com.google.android.gms:play-services-base:15.0.1"
implementation "com.google.firebase:firebase-core:16.0.1"
implementation "com.google.firebase:firebase-auth:16.0.2"
implementation "com.google.firebase:firebase-database:16.0.1"
implementation "com.google.firebase:firebase-messaging:17.1.0"
implementation "me.leolin:ShortcutBadger:1.1.21@aar"
implementation "com.google.firebase:firebase-storage:16.0.1"

**Comment by Salakar** [comment]
This isn't the correct usage of the method, see https://rnfirebase.io/docs/v5.x.x/messaging/reference/Messaging#subscribeToTopic

Single argument, of the topic name only. The syntax you're trying to use is only for the Firebase NodeJS Admin SDK.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
