### ISSUE TITLE
Missing exportVal implementation

### ISSUE THREAD

**Issue by secobarbital** [invertase/react-native-firebase#1497]
### Issue

The `DataSnapshot` class does not define an `exportVal` method. This is despite the typing lists `exportVa()l: any` in the interface.

### Environment

1. Application Target Platform:

iOS

2. Development Operating System:

macOS High Sierra

3. Build Tools:

Xcode 9.4.1

4. `React Native` version:

0.39.1

5. `React Native Firebase` Version:

4.3.8

6. `Firebase` Module:

database

7. Are you using `typescript`?

no

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Ehesp** [comment]
Hello 

`exportVal` isn't actually available in native, which we have documented here: https://rnfirebase.io/docs/v4.3.x/database/reference/DataSnapshot#exportVal

You're correct though that it is in the types - I'll get this removed.

**Comment by secobarbital** [comment]
Looking at the source for the iOS library, it seems like it is there as
`valueInExportFormat`. At least that is what I am attempting to use in my
fork.

https://github.com/firebase/firebase-ios-sdk/blob/927a2cd567bde4d9cbbdd7772f151034b0552a82/Firebase/Database/Api/FIRDataSnapshot.m#L44

**Comment by Ehesp** [comment]
It does seem it's now possible. I think Android was the issue, but that does seem possible now with `getValue(true)`. 

Will get that change in.

**Comment by Salakar** [comment]
This is now supported on master, implemented in https://github.com/invertase/react-native-firebase/commit/cc3d8e74d8b1e28e4311bfad6a41f5cbb84cbcdb - this will land in v5.1.0 - or if you want to use it earlier it'll be in tomorrows RC release (rc3).

Implemented as per WebSDK format: https://github.com/firebase/firebase-js-sdk/blob/master/packages/database/src/core/snap/LeafNode.ts#L172

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by secobarbital** [comment]
> Implemented as per WebSDK format: https://github.com/firebase/firebase-js-sdk/blob/master/packages/database/src/core/snap/LeafNode.ts#L172

It looks like the `LeafNode` algorithm is being applied to the root `Node` of the `Snapshot`. We actually need to recurse down the tree, passing the `exportFormat` flag down, as is done by `ChildrenNode`: https://github.com/firebase/firebase-js-sdk/blob/master/packages/database/src/core/snap/ChildrenNode.ts#L200

Sorry I wasn't able to point this out earlier. Let me know if you want a new Issue opened for this.
