### ISSUE TITLE
Storage not working

### ISSUE THREAD

**Issue by neverlan** [invertase/react-native-firebase#15]
![image](https://cloud.githubusercontent.com/assets/5860671/24204840/f6bb618a-0f19-11e7-8c1d-4caef9cea715.png)

Trying to upload a file as shown in the doc.
Same code was working with firestack#v3 branch.

**Comment by Salakar** [comment]
Can you show me your code?

**Comment by Salakar** [comment]
@neverlan and where is `firebase` defined? Not sure where you're getting firebase.userId from?

**Comment by neverlan** [comment]
I'm adding custom props like userId in the firebase object for convenience.
Database is working.

**Comment by Salakar** [comment]
Well, `firebase` is undefined as the error says, you've not imported it correctly, can I see the import?

**Comment by neverlan** [comment]
firebase is well defined. According to the error log, the problem is there line 12:

![image](https://cloud.githubusercontent.com/assets/5860671/24206191/c8165ab6-0f1d-11e7-87a0-81a4159dd66b.png)

**Comment by Salakar** [comment]
Can you try something, comment out where you're adding custom props onto firebase instance and hard code in a user id there, does it work?

Storage/reference.js#114 the putFile function is losing it's context somewhere along the way, am running it here unmodified and it's got the correct 'this' context

**Comment by neverlan** [comment]
Tried with a clear firebase instance. Same problem. Added some breakpoints. The first call is ok (storageRef is defined) but when calling .then(() =>) storageRef is undefined.

**Comment by Salakar** [comment]
Eeek, ok, give me some time to debug it more, weird one 😕 

In the meantime something like:
![image](https://cloud.githubusercontent.com/assets/5347038/24209477/52cc7866-0f1e-11e7-9581-49da7882a8ff.png)
 might work? Give that a go in your node modules and restart the packager

**Comment by Salakar** [comment]
Have a feeling its the promisify util screwing it up somewhere, it is due to be removed, am still in the process of changing native side to use the native promise implementations, I'll do storage now and push a new alpha.

**Comment by neverlan** [comment]
putFile = ( ... ) => {} does not resolve the issue.
Yes pretty weird, I don't understand why the StorageTask constructor is called two time (one on init, another time calling .then()).

**Comment by Salakar** [comment]
@neverlan aye not quite sure why it's calling that twice either, didn't write the original code welp, re-writing/refactoring now, give me an hour or so and i'll have android & ios redone with native promise usage - it was on the todo anyway, just bumped it up.

**Comment by neverlan** [comment]
Ok cool :)

**Comment by Salakar** [comment]
@neverlan ios done: https://github.com/invertase/react-native-firebase/commit/e23302fb2497976c192669af1fd358aac6da6e92 . Finishing android and then i'll do a release.

**Comment by neverlan** [comment]
Thanks for quick feedback :)

I'm getting this error:

![image](https://cloud.githubusercontent.com/assets/5860671/24217674/f1474bd4-0f40-11e7-94f2-b914b15d9fa2.png)

**Comment by Salakar** [comment]
Try pull again, hadn't finished yet with the JS side ;p only just pushed the JS updates

**Comment by neverlan** [comment]
I now got:

![image](https://cloud.githubusercontent.com/assets/5860671/24218448/ae9e8f10-0f43-11e7-8699-ed76ad239c15.png)

**Comment by Salakar** [comment]
Ok leave it with me, writing tests atm for storage

**Comment by Salakar** [comment]
What type of file is it also? @neverlan

**Comment by neverlan** [comment]
A jpg. The file is uploaded, it's just that the .then func crash the app.

**Comment by Salakar** [comment]
If you comment out [this](https://github.com/invertase/react-native-firebase/blob/master/ios/RNFirebase/RNFirebaseStorage.m#L372) and rebuild ios app - does it work?

**Comment by neverlan** [comment]
Nop :)

(commented out, xcode clean, xcode build)

**Comment by Salakar** [comment]
What about the downloadUrl line (the one above last one), sorry!

**Comment by neverlan** [comment]
Okay, figured out that the RCTJSONStringify error was due to a write permission on the storage path issue. But the "cannot read property 'storage' of undefined" remain.

**Comment by Salakar** [comment]
Ah ok, so 2 errors then, first being it should of rejected into the catch if no storage permission, and the other scope/context one. Will carry on my side then

**Comment by neverlan** [comment]
Just to sum up:

![image](https://cloud.githubusercontent.com/assets/5860671/24220517/d16119f8-0f4a-11e7-83c5-091a01ed9adf.png)

I tested this code directly inside a component, not using redux (thought redux-thunk could be involved in the promise error).

**Comment by Salakar** [comment]
Probably not this but:

```javascript
const firebase = RNFirebase..initializeApp({
    // and whatever options
    debug: __DEV__ ? '*' : false,
    errorOnMissingPlayServices: false,
    persistence: true,
});
```

Another thing i'll add a check for is that, no direct constructor calls or something like that. But again most likely not that.

**Comment by Salakar** [comment]
Sorry to keep using you as a guinea pig 🙈  could you change as per the below diff, in task.js:

![image](https://cloud.githubusercontent.com/assets/5347038/24220822/c9f8f20a-0f43-11e7-958f-03e7cd0b8805.png)

**Comment by Salakar** [comment]
Wooooo \o/ ok one more thing - does it go into 'catch' when the user has no write permission on storage - like you had before

**Comment by neverlan** [comment]
Nop not catched :)

**Comment by neverlan** [comment]
Well it is catched in console but the app still crash.

upload(currentPicturePath)
  .catch(err => console.log(err));

**Comment by Salakar** [comment]
RCTJSONStringify error again?

**Comment by neverlan** [comment]
Yes:

![image](https://cloud.githubusercontent.com/assets/5860671/24221607/4433daf2-0f4f-11e7-87e4-7478c79848c5.png)

**Comment by Salakar** [comment]
![image](https://cloud.githubusercontent.com/assets/5347038/24225265/67a3bb94-0f57-11e7-9fab-09977133b2df.png)

Getting there ;p

**Comment by Salakar** [comment]
Hoorah, all fixed:
![image](https://cloud.githubusercontent.com/assets/5347038/24226745/2c958420-0f60-11e7-8321-4135b33ace70.png)

**Comment by neverlan** [comment]
Working perfectly :)

**Comment by manjeets12** [comment]
@Salakar and @neverlan  can you please guide how you fixed this issue, I am getting same  error i.e RNFirebaseStorage.putgile got 3 arguments, expected 4, my code is

export const startUpload= function(data){
  let {url,path} = data; // where url is 'Images/Avatar/'+uid   and path is local path generated by image-crop-picker
  return dispatch => {
    firebase.storage()
    .ref(url)
    .putFile(path,{contentType: 'image/jpeg'})
    .then(uploadedFile => {
        console.lgo(uploadedFile);
    })
    .catch(error => {
        console.log(error);
    });
  }
}

**Comment by Salakar** [comment]
@manjeets12 android will be fixed in tonights build - it's still in progress. The above was for ios. Will tag you in the commit/release.

**Comment by manjeets12** [comment]
great, I will be waiting for the updates.

I have a small doubt, hope you will not mind asking at the wrong place, react-native-image-crop-picker giving me file path something like that "file:///data/data/com.riduk/cache/react-native-image-crop-picker/bcab9320-cf4e-4eba-b040-0c63eb6c57d6.jpg",  will this work for storage or do I need to edit it in some other way (just asked because you are checking on "content" within path in your java files

**Comment by Salakar** [comment]
That path looks correct 👍

**Comment by Salakar** [comment]
@manjeets12 
![image](https://cloud.githubusercontent.com/assets/5347038/24466121/9c1ffb80-14a7-11e7-9f04-2d8a0787d511.png)

Android done, releasing new version now (alpha10). Let me know if you notice anything off/anything i've missed.

**Comment by manjeets12** [comment]
@Salakar great it is so fast, I will let you know as soon as I am done with  testing it

**Comment by manjeets12** [comment]
works perfectly for android

**Comment by manjeets12** [comment]
hi @Salakar  please change photoURL to photoUri in documentation for update profile function, because it is what you used in your java classes
```
firebase.auth().currentUser
        .updateProfile({
          photoUri: response.downloadUrl, // this is working and photoURL: string, this is not
          displayName:'Manjeet Singh'
        })
        .then(user =>{
          console.log(user);
        })
        .catch(error =>{
          console.log(error);
        });
```

**Comment by Salakar** [comment]
Will look into this, should match whatever the web sdk for firebase does

**Comment by chrisbianca** [comment]
I've just updated the Java code to look for photoURL rather than photoUri which brings it inline with the web SDK and what is already done in iOS
