### ISSUE TITLE
scheduleLocalNotification() not working

### ISSUE THREAD

**Issue by Kernael** [invertase/react-native-firebase#150]
Hey !

I'm trying to fire a scheduled local notification as so :
```

firebase.messaging().scheduleLocalNotification({
  title: 'Title',
  body: 'Body',
  icon: "ic_launcher",
  large_icon: "ic_launcher",
  color: "#234a75",
  fire_date: moment().valueOf() + 1000 * 5,
  id: Math.floor((Math.random() * 500) + 0).toString(),
  show_in_foreground: true,
})
```

But the notification is never triggered (tested on Android).

Is there something I am missing ? `createLocalNotification()` works perfectly well with the same parameters (without `id` and `fire_date` of course).

Thank you for your amazing work.

**Comment by chrisbianca** [comment]
@Kernael Have you tried setting the fire_date as slightly further in the future?
I seem to recall having a similar issue where it takes a little while for the notification to be registered.  Try a minute or two rather than a few seconds?

**Comment by Kernael** [comment]
No luck so far with `fire_date: moment().add('2', 'minutes').valueOf()`.

**Comment by Kernael** [comment]
Figured it out, it came from a missing configuration as documented here : http://invertase.io/react-native-firebase/#/installation-android?id=_3-cloud-messaging-optional

**Comment by chrisbianca** [comment]
Fantastic - glad you got there!

**Comment by sfratini** [comment]
@chrisbianca This thread helped me sorted this out, however I couldn't find this method in the docs. Is it possible to update and add this information? The scheduleLocalNotification and createLocalNotification are not in the messaging reference.

**Comment by Salakar** [comment]
@sfratini if you're looking at 4 then they're in the notifications reference docs
