### ISSUE TITLE
Question: setup 2 firebase projects for dev and prod based on env

### ISSUE THREAD

**Issue by Stas-Buzunko** [invertase/react-native-firebase#1501]
I need dynamically choose 1 of 2 firebase projects (not apps) depending on whether it's development and production env.

There is little info on the internet how to do it and I hoped maybe some of you have done it + it may be useful to add this to docs somewhere.

**Comment by Stas-Buzunko** [comment]
found https://firebase.google.com/docs/configure/

could you please help me convert swift code to obj-c?

```
// Load a named file.
let filePath = Bundle.main.path(forResource: "MyGoogleService", ofType: "plist")
guard let fileopts = FirebaseOptions(contentsOfFile: filePath!)
  else { assert(false, "Couldn't load config file") }
FirebaseApp.configure(options: fileopts)
```

**Comment by Stas-Buzunko** [comment]
found obj-c here
https://stackoverflow.com/a/44191335/5766054

but needed to add  NSString *filePath;
for people who may need this in the future, i have 2 plists in a target folder:
GoogleService-Info-Dev and  GoogleService-Info,
here is code to replace [FIRApp configure];  in AppDelegate.m
```
  NSString *filePath;

  #ifdef DEBUG
    filePath = [[NSBundle mainBundle] pathForResource:@"GoogleService-Info-Dev" ofType:@"plist"];
  #else
    filePath = [[NSBundle mainBundle] pathForResource:@"GoogleService-Info" ofType:@"plist"];
  #endif

  FIROptions *options = [[FIROptions alloc] initWithContentsOfFile:filePath];
  [FIRApp configureWithOptions:options];
```
don't forget to remove [FIRApp configure];

**Comment by Stas-Buzunko** [comment]
looks like for android all you need is to place files correctly as in firebase docs
```
app/
    google-services.json
    src/development/google-services.json
    src/release/google-services.json
```

still, it may be worth adding to docs obj-c code for AppDelegate.m

**Comment by Ehesp** [comment]
@Stas-Buzunko could you add this to the docs please?

**Comment by Stas-Buzunko** [comment]
@Ehesp yes, if you haven't done it yet, how could i do this?
