### ISSUE TITLE
TypeError: undefined is not a function(evaluating messaging.getInitialNotification())

### ISSUE THREAD

**Issue by esmatptr** [invertase/react-native-firebase#1502]
I updated both the react-native-firebase and react-native versions and just received this error when trying to run the app.
Note that this was working fine before.

import firebase from 'react-native-firebase'
var messaging= firebase.messaging()

componentDidMount() {
   messaging.onMessage((notif) => {
            this.onAndroidMessage(notif)
        })
        FCM.getInitialNotification()
            .then((payload) => {
                // do something
            })
   })
}

### Environment

1. Application Target Platform:

Android

2. Development Operating System:

Windows 10

3. Build Tools:

Android Studio

4. `React Native` version:

0.54.0

5. `React Native Firebase` Version:

4.3.8

6. `Firebase` Module:

messaging

7. Are you using `typescript`?

no

**Comment by andrewhartwig** [comment]
`FCM.getInitialNotification()` or `messaging.getInitialNotification()` cause I only see the former
