### ISSUE TITLE
Save a reference with transaction

### ISSUE THREAD

**Issue by francescovenica** [invertase/react-native-firebase#1504]
When I try to run a transaction like this:
```
        city.userId = `/users/${self.user.uid}`;
        if (!cityDoc.exists) {
          transaction.set(self.cityRef, city);
        } else {
          transaction.update(self.cityRef, city);
        }
```

the userId is saved as a string instead of a reference, not sure if I'm doing something wrong...this is my setup:

macOS Sierra

```
"react": "16.4.1",
"react-native": "0.56.1",
"react-native-firebase": "^4.3.8",
```

running on simulator (not tested on device)

many thanks

**Comment by Ehesp** [comment]
Could you please provide some more context? What is `book`? Is this RTB or Firestore?

**Comment by francescovenica** [comment]
I'm sorry, book was a copy error, it's all city...so what I'm doing is run a transaction (copied from the docs https://rnfirebase.io/docs/v4.3.x/firestore/transactions#Multiple-reads-and-writes ) the userId is a relational field but when I run the transaction is saved as string

**Comment by Ehesp** [comment]
Just to confirm, you're saying that it's saving as a `string` on the console, not an expected `reference`?

**Comment by francescovenica** [comment]
yes, exactely...when I'll go to check in the firestore console I see the right value but saved as string instead of reference

**Comment by Ehesp** [comment]
Right ok thanks - sounds like a bug on our end then. You should be able to work around it for the time being, but we'll get this sorted.

**Comment by francescovenica** [comment]
how can I work around?

**Comment by francescovenica** [comment]
I'm sorry, I found the problem....it was my mistake, I was saving the string /users/userId but saving the user reference save directly the vlaue as reference isntead of string...so my fault

```
city.userId = self.userRef;
```
