### ISSUE TITLE
 Firestore: The service is currently unavailable. (firestore/unavailable).

### ISSUE THREAD

**Issue by cattuan** [invertase/react-native-firebase#1505]
### Issue

After i upgraded Xcode to 10 and iOS 12.0, when I get the doc by id, I got the below error.

Error: Firestore: The service is currently unavailable. (firestore/unavailable).
ExceptionsManager.js:84
     code:"firestore/unavailable"
     domain:"FIRFirestoreErrorDomain"
     framesToPop:1
     message:"Firestore: The service is currently unavailable. (firestore/unavailable)."
userInfo:Object {NSLocalizedDescription: "Failed to get document because the client is offli…"}
     NSLocalizedDescription:"Failed to get document because the client is offline."

### Environment

1. Application Target Platform: 

iOS 12.0 

2. Development Operating System:

macOS Sierra

3. Build Tools:

Xcode 10

4. `React Native` version:

0.56.0

5. `React Native Firebase` Version:

4.3.8

6. `Firebase` Module:

firestore

7. Are you using `typescript`?

no

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Olovorr** [comment]
Hey @cattuan, would you mind sharing how did you solve this one? I am probably experiencing the same issue.

**Comment by gusoskar** [comment]
Same here

**Comment by Olovorr** [comment]
@gusoskar It started working on it's own after a while. Firestore was down apparently, but nothing was mentioned anywhere 🙂I don't think that it is the package issue.

**Comment by cattuan** [comment]
@Olovorr @gusoskar Are you using the custom token to sign to Firebase Auth?  
If is that, you try change `firebase.auth().signInWithCustomToken()` to `firebase.auth().signInAnonymously()`.
It worked for me!

**Comment by zootopia106** [comment]
@cattuan 
my app is using email/password authentication and i am still getting this error.
any idea?

**Comment by brandtnewww** [comment]
I'm facing the same issue on my App in production now and then.

`Non-fatal Exception: UnhandledPromiseRejection [firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff. <unknown>`

Would be great to find a workaround soon.
