### ISSUE TITLE
When key in "!=" and "array_contains" where operator turn out error!!! 

### ISSUE THREAD

**Issue by Luktm** [invertase/react-native-firebase#1506]
### Issue

Where operator turn out error when key in "!=" and "array_contains". I do not know which part i did wrong.

```
import React, {Component} from 'react';
import {
    ScrollView,
    TouchableOpacity,
    Text,
    View,
    TouchableWithoutFeedback
} from 'react-native';
import firebase from 'react-native-firebase';

class ChatTicketList extends Component {

    state = {
        tickets: {}
    };

    componentWillMount() {
        firebase.firestore().collection('tickets').where('fruit', 'array_contains', 'apple')
            .onSnapshot(collection => {
                const tickets = {};

                collection.forEach(doc => {
                    tickets[doc.id] = doc.data();
                });
                this.setState({tickets})
            });
    }
}
```

Firebase firestore database:
![firestore-array-data](https://user-images.githubusercontent.com/24861458/45754948-9e5af700-bc4f-11e8-9f2d-a22b5761736c.JPG)

Error Get From Emulator:
![operator-error](https://user-images.githubusercontent.com/24861458/45754814-415f4100-bc4f-11e8-88f2-a480e4711872.PNG)

Firebase cloud firestore documentation: 
![firebase-doc-array-contains](https://user-images.githubusercontent.com/24861458/45755648-93a16180-bc51-11e8-9505-093c8a73493e.JPG)

### Environment

1. Application Target Platform: Android

2. Development Operating System: Windows 10

3. Build Tools: Android SDK Version 27.0.3

4. `React Native` version: 0.55.4

5. `React Native Firebase` Version: 4.3.8

6. `Firebase` Module: database

7. Are you using `typescript`? no

---

**Comment by Ehesp** [comment]
`array_contains` isn't available yet. It'll be available in the next v5 rc release.

**Comment by felixchan** [comment]
@Ehesp when is the expected release date for v5 rc?  Is there any way to start testing `array_contains` now?

**Comment by Ehesp** [comment]
Within the next couple of weeks. PRs for the feature are very welcome.

**Comment by Luktm** [comment]
> @Ehesp when is the expected release date for v5 rc? Is there any way to start testing `array_contains` now?

Maybe it's only available for web version??

**Comment by Ehesp** [comment]
We need to do the native integration. It will probably be there on the Web,
although we've not tested it'll work with the react native environment.
Just be aware you may lose out on other modules you're using.

**Comment by Salakar** [comment]
@Luktm @felixchan `v5.0.0-rc4` has just been published with firestore `array-contains` filtering support.

Note that the correct usage is with a dash (`array-contains`), not an underscore (`array_contains`).

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
