### ISSUE TITLE
[Android FCM] Incomplete/missing notifications

### ISSUE THREAD

**Issue by skizzo** [invertase/react-native-firebase#151]
Hi,
I'm trying to implement Firebase Cloud Messaging for Android. Unfortunately, I'm not able to handle all the cases required for a functional app. Note: It doesn't matter whether I send the notification via Cloud Functions of the Notifications Panel in the Firebase Console.

# Working:

1. **App is not started at all**: When opening the app via double-tapping a notification, the notification is coming through via `firebase.messaging().getInitialNotification()`.
_Note: The notification's message text doesn't show up here, no clue why_.

2. **App is in foreground/active**: When the app is in the foreground and a notification is sent, it's coming through via `firebase.messaging().onMessage()`.
_Note: The notification's message text shows up here._

# Not working:

3. **App is started, but in background**: The notification is shown in the panel, but after double-tapping it to bring app into foreground, **neither `getInitialNotification()` (okay, makes sense) nor the `getMessage()` (shouldn't happen) are triggered**.

---

I followed the [Android setup guide for FCM](http://invertase.io/react-native-firebase/#/installation-android?id=_3-cloud-messaging-optional) step by step, and double-checked before posting this issue. Can anybody help please?

**Comment by chrisbianca** [comment]
@skizzo this is quite strange as I definitely have this working in my app, though admittedly I most recently tested and confirmed it was working using the v2 PR: https://github.com/invertase/react-native-firebase/pull/130

My suggestion would be to start introducing some break points in the native Java code to see whether the message is being received at all by the app. In particular: https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/messaging/MessagingService.java#L20

**Comment by skizzo** [comment]
Thanks for your reply @chrisbianca. 

I've set a breakpoint in the `onMessageReceived (..)` function in the `MessagingService` class, and it's exactly what I expected: The function is being triggered in case 2 (_app is not started at all_, can't debug case 1) but not in case 3 (_app is started, but in background_).

Another thing I thought is that maybe it has to do with using background processing? I should note that I use [react-native-audio-streaming](https://github.com/tlenclos/react-native-audio-streaming) in my project and want to be able to play music while the app is in the background.

**Comment by erezrokah** [comment]
Hi, we've recently go this working with v1.1.0.
Have you set `launchMode="singleTop"` as described here:
http://invertase.io/react-native-firebase/#/installation-android?id=_3-cloud-messaging-optional

In this case you should receive the notification when returning from background using:
firebase.messaging().onMessage() 

Since the code here:
https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/messaging/RNFirebaseMessaging.java

Calls sends the notification event in `onNewIntent`

**Comment by skizzo** [comment]
As mentioned, I followed the instructions and double-checked before creating this issue. So yes, the `launchMode` is set to `singleTop`. And thanks, but knowing that I **should** receive notifications now doesn't really get me any closer to solving this ;)

Is it normal for you guys that the `onNewIntent (..)` function is called every time I start the app or put it into the foreground, without actively sending any notifications? This also means that I receive this intent on every app start, even though it's not a notification directly:

![screen shot 2017-06-09 at 13 24 41](https://user-images.githubusercontent.com/2892572/26973469-114c3674-4d17-11e7-8171-991d873e1bd8.png)

Maybe it has sth. to do with it? Needless to say that I come from the iOS world and am an Android noob still.

**Comment by erezrokah** [comment]
Hi, I'm also an android noob, and just a user of this library. 
What we've done is ignore the events that are irrelevant (don't contain the notification data we need).
Inter process communication in Android works by launching activities with intents (intents contain the data passed to the activity).

Meaning when you press a notification it will launch your app (activity) with the notification data (intent).
In `singleTop` mode instead of creating a new activity with a new intent, the data is passed to the existing activity using the `onNewIntent` as described here:
https://inthecheesefactory.com/blog/understand-android-activity-launchmode/en

I would suggest putting some logs in this handler and see if you get the notification you're looking after.

**Comment by skizzo** [comment]
Thanks for the explanation! I already placed breakpoints & logs in all the Java functions handling notifications (see my last comment), so I'm really running out of ideas here.

**Comment by chrisbianca** [comment]
@skizzo do you want to give the v2 branch a try?

I've done a bit of clean up of Firebase Messaging and confirmed that your scenario is working in my app, so hopefully it will resolve your problem as well.

**Comment by fbacker** [comment]
also having this issue.

    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1",
    "react-native-firebase": "1.1.1",

Seems not to get all the data in RNFirebaseMessaging.java 

    private WritableMap parseIntent(Intent intent)


When **app is active** the registerMessageHandler is used and that works great.

when **app is in background** the registerMessageHandler is runned, but the app is inactive so it doesn't do anything. going back to the app parseIntent is runned and doesn't show the correct object to the app

when **app is closed** the parseIntent is runned and doesn't show the correct object to the app

**Comment by chrisbianca** [comment]
@fbacker when you say that it doesn't show the correct object to the app, what exactly do you mean by this? That `onMessage`has the incorrect notification object? Or that a notification isn't showing?

**Comment by fbacker** [comment]
When app is opened.
<img width="504" alt="screen shot 2017-06-20 at 18 34 28" src="https://user-images.githubusercontent.com/4478361/27344595-2b81b36a-55e7-11e7-90d6-4eaf25e6967c.png">

and when its closed
<img width="618" alt="screen shot 2017-06-20 at 18 34 35" src="https://user-images.githubusercontent.com/4478361/27344606-3461db54-55e7-11e7-8091-82ade255ac08.png">

**Comment by chrisbianca** [comment]
Thanks @fbacker.  Are you able to confirm this is still the case with v2.0.0 which has just been released?  I'll have some time tomorrow to investigate this properly.

**Comment by fbacker** [comment]
@chrisbianca Yes, will upgrade and try it out.

**Comment by fbacker** [comment]
Upgraded to v2, but still same issue.
I've inactivated the app, send a push notification and open the app. Even when I click on the notification to open the app I still doesn't get the fcm object.

<img width="998" alt="screen shot 2017-06-21 at 22 03 26" src="https://user-images.githubusercontent.com/4478361/27404483-84e891fc-56ce-11e7-85bf-1269c1a37603.png">

**Comment by lazyhoneyant** [comment]
+1 same issue.

**Comment by AugustKarlstedt** [comment]
Same issue here as well.

**Comment by chartrandf** [comment]
+1 sae issue.

**Comment by maxbbb** [comment]
I was experiencing the same issue, and when sending a notification through a firebase cloud function or otherwise, I had code that looked like this. 


```
const payload = {
   notification: {
    data: myData
   }
}

firebase.messaging().sendToTopic(userTopic, payload)
```

but it turns out that if you want to append extra data to the notification your syntax has to look like this 

```
const payload = {
   notification: {
    options: myNotificationOptions
   },
   data: {
    payloadData: myData
   }
}
firebase.messaging().sendToTopic(userTopic, payload)
```


not sure if the people experiencing this problem are already doing this but this fixed everything for me, hope it helps.

**Comment by patrickkempff** [comment]
Any solution? I have the same problem, I am trying to use the library in conjunction with react-native-navigation

**Comment by mdvx** [comment]
I tried this, 

const payload = {
   notification: {
    options: myNotificationOptions
   },
   data: {
    payloadData: myData
   }
}

only works if myData is a String

Error sending message (or deleting call): { Error: Messaging payload contains an invalid value for the "data.payloadData" property. Values must be strings.

So I am back to this...

const payload = {
   notification: {
    options: myNotificationOptions
   },
   data: myData  // myData is a Map<String,String<
}

which works fine if the app is open, however when closed, and the notification comes, all values are null

**Comment by krystiansliwa** [comment]
Hi, any progress on that? Or workaround/patch? I have the same problem

**Comment by engvik** [comment]
We ran into this issue as well (or something very similar), and it turned out that it was our Java-implementation of a splash screen that broke notifications for us. Implemented by following [this guide](https://medium.com/handlebar-labs/how-to-add-a-splash-screen-to-a-react-native-app-ios-and-android-30a3cec835ae).

**Comment by krystiansliwa** [comment]
We also had custom splash screen. Our solution for this issue was to send in notification payload this key `click_action: open_event_action`,
then modify AndroidManifest file by adding intent-filter for that click action.

```xml
        <activity
            android:name=".MainActivity"
            android:windowSoftInputMode="stateAlwaysHidden|adjustPan"
            android:screenOrientation="portrait"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:background="@color/background"
            android:launchMode="singleTop"
            >
            <intent-filter>
                <action android:name="open_event_action" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
```

**Comment by chrisbianca** [comment]
Thanks for reporting.  We're aware of lots of issues with notifications and will be addressing them all as part of the v3.2.0 release stream.  Please see https://github.com/invertase/react-native-firebase/issues/595 for updates.

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)

**Comment by pgqueme** [comment]
I had to remove my custom SplashScreen to get it to work on Android. Maybe I'll try the library `react-native-splash-screen` suggested on [this thread](https://github.com/evollu/react-native-fcm/issues/763).
