### ISSUE TITLE
Registering for notifications is coupled with the modal requestPermission

### ISSUE THREAD

**Issue by britianoates** [invertase/react-native-firebase#1511]
### Issue

Please expose a method other than RequestPermission to perform the wiring of APNS to FCMToken.  

The magic seems to be this call in RequestPermission:
registerForRemoteNotifications

The importance of this function was explained in the documentation when we started.  Right now the only way to perform this sync is to call requestPermission every time the fcmToken changes.  The code doesn't read clearly (I'm not really requestingPermission).  

It also created problems for us because we are trying to preserve our one chance on iOS to request permission, so our solutions to rewire existing users after token refresh also needs to skip requestPermission.

We'd like a second function called resyncForRemoteNotifications or something similar to perform only the sync operations.

### Environment
1. Application Target Platform:
Both

2. Development Operating System:
mac High Sierra

3. Build Tools:
xcode 9.4, Android Studio 28

4. React Native version:

"react-native": "0.55.4",

5. React Native Firebase Version:

"react-native-firebase": "^4.0.3",

6.  Firebase Module:

firebase-core:12.0.1
firebase-analytics:12.0.1
firebase-messaging:12.0.1

7. Are you using typescript?
no

**Comment by Salakar** [comment]
@britianoates this had now landed on master thanks to @timwangdev 🎉 it will be in the v5.1.0 release. 

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
