### ISSUE TITLE
setUserProperty results in high error probability

### ISSUE THREAD

**Issue by jsweird** [invertase/react-native-firebase#1512]
Using the react-native-firebase module version 4.3.x, I'm seeing that setting many user properties at once results in at least one error on the DebugView each time I run it, and as a result, missed user properties on all subsequent events. For instance I have a method after successful sign in that goes and sets all the user properties that I need right in a row:

```
_firebase.setUserProperty('prop1', 'value1');
_firebase.setUserProperty('prop2', 'value2');
_firebase.setUserProperty('prop3', 'value3');
_firebase.setUserProperty('prop4', 'value4');
_firebase.setUserProperty('prop5', 'value5');
```

Is there a way to do this that might have better reliability? Perhaps in the react module, could it be updated to receive an object or array of user property key-value pairs that might cut back on the noise?

Additionally, I have some events which I want to tag a value, or dollar amount. I do not see a way to capture this in the react-native-firebase docs. It doesn't seem like something that should be set as a user property, since it only pertains to certain events, such as a purchase. Anyone have any insight into how I might achieve this? Thank you in advance for any insights!

**Comment by Salakar** [comment]
Not entirely sure what you mean here but you can do the following:

```js
firebase.analytics().setUserProperties({
	prop1: 'value1',
	prop2: 'value2',
	prop3: 'value3',
	prop4: 'value4',
});
```

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by jsweird** [comment]
> Not entirely sure what you mean here but you can do the following:
> 
> ```js
> firebase.analytics().setUserProperties({
> 	prop1: 'value1',
> 	prop2: 'value2',
> 	prop3: 'value3',
> 	prop4: 'value4',
> });
> ```

It fails when trying to pass an object in. No user properties end up getting set, and it throws an exception. If the module is supposed to allow this, then there is a bug because it doesn't work. In either case, the documentation [here](https://rnfirebase.io/docs/v4.3.x/analytics/reference/analytics) fails to mention that it would accept an object.
