### ISSUE TITLE
[Storage] StorageTask not triggering listener on Android

### ISSUE THREAD

**Issue by FacuAcosta** [invertase/react-native-firebase#1514]
### Issue

I'm using `storageTask.on` listener on the `'state_changed'` event to get the status of the current upload. The listener is working fine on iOS, I'm getting the snapshot for showing the upload progress, handling errors and the response if it succeeded  but on Android, the listener is never triggered. The thing is, the files are getting uploaded properly but I need to show the user the progress since it might take a while to upload. Here is my current code:

```
const { videoSource } = this.state;
    const { uid } = firebase.auth().currentUser;
    const extension = videoSource.split('.').pop();
    const fileName = Date.now();
    const mime = `image/${extension}`;
    const imageRef = firebase
      .storage()
      .ref()
      .child(`/users/${uid}/files/${fileName}.${extension}`);

    try {
      const uploadTask = imageRef.put(videoSource, { contentType: mime });

      uploadTask.on(
        'state_changed',
        snapshot => {
          const progress = snapshot.bytesTransferred / snapshot.totalBytes;
          const roundedProgress = this.precisionRound(progress, 1);

          if (!_.isNaN(roundedProgress)) {
            this.setState({ uploadProgress: roundedProgress });
          }

          switch (snapshot.state) {
            case firebase.storage.TaskState.PAUSED:
              break;
            case firebase.storage.TaskState.RUNNING:
              break;
            default:
              break;
          }
        },
        error => {
          Toast.show('Error, try again.', Toast.SHORT);
          this.setState({ showUpload: false, disabledButton: false });
        },
        res => {
          uploadAthleteVideo('athlete', res).then(status => {
            if (status) {
              this.handleVerifSuccessFlow();
            } else {
              Toast.show(
                'An error occurred please check your connection and try again.',
                Toast.SHORT
              );
            }
          });
        }
      );
    } catch (error) {
      this.setState({ showUpload: false, disabledButton: false });
      console.log(error);
    }
```
**UPDATE**
Further tests show that not even the simple `putFile` is triggering the callback once finished yet the files are getting uploaded.

```
imageRef
        .putFile(videoSource, { contentType: mime })
        .then(res => {
          console.log(res);
        })
        .catch(error => console.log(error));
```
### Environment

1. Application Target Platform: Android

2. Development Operating System: macOs High Sierra 10.13.6

3. Build Tools: Android Studio 3.1.2, 

4. `React Native` version: 0.55.3

5. `React Native Firebase` Version: 4.3.8

6. `Firebase` Module: Storage: Android = 16.0.1 , iOS = 5.3.0

7. Are you using `typescript`? No

**Comment by viniciusoliveira01** [comment]
Same problem here!

**Comment by FacuAcosta** [comment]
**UPDATE**
After some digging we found the source of the issue. We had some Storage Rules that were working fine on iOS, `allow create` and `allow delete`. This rules allowed users to create and delete files but it seems that for Android you also need to add `allow read` because It looks like the listener relies on reading from the bucket. 

Closing issue.
