### ISSUE TITLE
snapshot.foreach is not a function

### ISSUE THREAD

**Issue by umair-ameen** [invertase/react-native-firebase#1515]
### Issue

```
getDates() {
    firebase.database().ref('dates').orderByKey().once('value').then(
      (snapshot) => {
        snapshot.forEach(date => {
          let dt = date.val();
          this.dates.push(dt);
        });
        console.log(this.dates);
       }
    )
  }
```

**TypeError: snapshot.forEach is not a function**

### Environment

1. Application Target Platform:

Android

2. Development Operating System:

Windows 10

3. Build Tools:

NativeScript + Angular + Visual Studio Code

6. `Firebase` Module:

database, auth, messaging,

7. Are you using `typescript`?

yes

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Ehesp** [comment]
Hey thanks for the report.

Could you try and debug and check what `snapshot` is and what properties it has?

Cheers
