### ISSUE TITLE
Scheduled notification not shows up

### ISSUE THREAD

**Issue by esipavicius** [invertase/react-native-firebase#1519]
### Issue

I tried to create schedule notification, but nothing shows up, but display notifications works. So I set sheduler for +5sec and it nothing do. No error, no message, nothing. Maybe I missed something?

P.S. with master branch chashing app. It stops

**build.gradle implementations**

    implementation project(':react-native-firebase')
    implementation "com.google.android.gms:play-services-base:15.0.1"
    implementation "com.google.firebase:firebase-core:16.0.1"
    implementation "com.google.firebase:firebase-messaging:17.1.0"

**AndroidManifest**

    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.mydehdeps"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <uses-sdk
            android:minSdkVersion="16"
            android:targetSdkVersion="26" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
    >
        <activity
        android:name=".MainActivity"
        android:launchMode="singleTop"
        android:label="@string/app_name"
        android:theme="@style/SplashTheme"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:screenOrientation="portrait"
        android:windowSoftInputMode="adjustResize"
        >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
                <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
            </intent-filter>
        </activity>

        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

        <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@mipmap/ic_launcher"
        />

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/background"
        />

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/default_notification_channel_id"
        />

        <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />

        
        <receiver android:name="io.invertase.firebase.notifications.RNFirebaseNotificationReceiver"/>

        <receiver android:enabled="true" android:exported="true"  android:name="io.invertase.firebase.notifications.RNFirebaseNotificationsRebootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </receiver>
    </application>
    </manifest>

**Code**

    import firebase from 'react-native-firebase';
    
    
    const channel = new firebase.notifications.Android.Channel(
        'dep_time_tracing',
        'Time tracking',
        firebase.notifications.Android.Importance.Max
    ).setDescription('Hint users how much left time o drive to next dep');
    firebase.notifications().android.createChannel(channel);
    
    const localNotification = new firebase.notifications.Notification({
        sound: 'default',
       // show_in_foreground: true,
       // show_in_background: true,
    })
        .setNotificationId('hh2')
        .setTitle('bb')
        .setSubtitle('cc')
        .setBody('dssd')
        .setData({
        type: 'start',
    })
        .android.setChannelId('dep_time_tracing') // e.g. the id you chose above
        .android.setSmallIcon('ic_launcher') // create this icon in Android Studio
        .android.setColor(COLORS.RED) // you can set a color here
        .android.setPriority(firebase.notifications.Android.Priority.High);
    
    // Schedule the notification for 1 minute in the future
    const date = new Date();
    date.setSeconds(date.getSeconds() + 5);
    
    firebase.notifications()
        .scheduleNotification(localNotification, {
            fireDate: date.getTime(),
        })
        .catch(err => console.error(err));

### Environment

1. Application Target Platform:

Android(8.0.0) from USB.

2. Development Operating System:

Ubuntu 18.04

3. Build Tools:

Android Studio 3.1.4
targetSdkVersion            = 26
buildToolsVersion           = "27.0.3"
googlePlayServicesVersion   = "15.0.1"
supportLibVersion           = "26.1.0"
minSdkVersion               = 19
compileSdkVersion           = 26

4. `React Native` version:

0.56.0

5. `React Native Firebase` Version:

^4.3.8

6. `Firebase` Module:

notification

7. Are you using `typescript`?

no

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by ducpt2** [comment]
+1 i have the same issue in iOS. Don't know what wrong. :)
I can push a local notification in the simple way, but scheduled not work at all.
Any help?

**Comment by esipavicius** [comment]
It should throw error?
[https://imgur.com/k5NLKlk](debug 1)
[https://imgur.com/k5NLKlk](debug 2)

**Comment by esipavicius** [comment]
It is not should have somehing like call show notifications like displayNotification ?
[debug](https://imgur.com/k5NLKlk)

**Comment by ducpt2** [comment]
@esipavicius pls check this link:
https://medium.com/@yangnana11/how-to-set-up-firebase-notification-in-react-native-app-android-only-4920eb875eae
Maybe this can help u.

**Comment by esipavicius** [comment]
> @esipavicius pls check this link:
> https://medium.com/@yangnana11/how-to-set-up-firebase-notification-in-react-native-app-android-only-4920eb875eae
> Maybe this can help u.

Hi, thanks!

First time I read, this. But I do not relised it is important to create event listener (firebase.notifications().onNotification) ;/ Maybe it should be updated documentation, because where is not mentioned about this in the https://rnfirebase.io/docs/v5.x.x/notifications/scheduling-notifications ...

**Comment by ramki1979** [comment]
I have the listener, but the listener is not triggered?

I have rechecked the configuration docs of 5.x.x and every this look good, yer I am not able to see ScheduleNotifications work.

**Comment by Iamivan1996** [comment]
Even i have create the event listener, it is still not working. Am i missing something?

Here is the function to schedule the notification
![screen shot 2018-12-19 at 7 12 45 pm](https://user-images.githubusercontent.com/30230906/50216906-15746880-03c2-11e9-9af9-c5e26de45848.png)

The listener to display the notification
![screen shot 2018-12-19 at 7 14 20 pm](https://user-images.githubusercontent.com/30230906/50217010-6a17e380-03c2-11e9-8b7f-75d9798088c2.png)

I can create a local notification for ios and android, but schedule notification is not work in android

**Comment by DNA-h** [comment]
Oh my god, wasted 2, 3 hours on this simple problem. Thank you @esipavicius

**Comment by mikehardy** [comment]
Interesting, the patch branch there looks correct but it the alteration does not seem to be integrated into the documentation. @esipavicius do you want to submit that as a PR? It's almost a year old at this point which was before I started helping with the project, maybe there was a reason you didn't propose it but it looks good to me
