### ISSUE TITLE
ARC Semantic Issue No visible @interface for FIRQuery on Firestore module

### ISSUE THREAD

**Issue by anjapadu** [invertase/react-native-firebase#1520]
1. Application Target Platform:

IOS

2. Development Operating System:

 macOS Sierra

3. Build Tools:

X-Code 10.0

4. `React Native` version:

0.57.º

5. `React Native Firebase` Version:

^5.0.0-rc4

6. `Firebase` Module:
 'Firebase/Firestore', '~> 5.3.0'

7. Are you using `typescript`?

No
---

Got this error when trying to start my app via xcode :(
plz help u.u

![image](https://user-images.githubusercontent.com/16998699/45933306-83d69580-bf4f-11e8-9ccc-5401f718b85b.png)
![image](https://user-images.githubusercontent.com/16998699/45933309-8f29c100-bf4f-11e8-8847-5b1403100b89.png)

**Comment by 4mitabh** [comment]
same issue with  react-native": "0.57.1

**Comment by anjapadu** [comment]
If i comment  both lines the application starts but i don't if will be able to use Firestore correctly when i need it or it will have break.

**Comment by Salakar** [comment]
You need to be on iOS Firestore SDK 5.6.0 and above for React Native Firebase v5.x.x.
