### ISSUE TITLE
Analytics not showing for Android

### ISSUE THREAD

**Issue by puja1234** [invertase/react-native-firebase#1521]
Android analytics not showing up neither on dashboard nor in debug view mode.
in build.gradle of app level
   applicationId 'com.xxxxx'
   
compile(project(':react-native-firebase')) {
        transitive = false
    }
compile "com.google.android.gms:play-services-base:11.4.2"
compile "com.google.firebase:firebase-core:11.4.2"
compile "com.google.firebase:firebase-analytics:11.4.2"

In AndroidManifest package name is host.xxx.xxxx;

1. Environment
Android only.(its working fine for IOS).

2. Development Operating System:
MacOs

3. Build Tools:
Android SDK version used 
    compileSdkVersion 26
    buildToolsVersion '26.0.1'

4. `React Native` version:
    0.51.0

5. `React Native Firebase` Version:
 3.0.0

6. `Firebase` Module:
Analytics

7. Are you using `typescript`?

no

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
@puja1234 hey, v3.0.0 is out of support unfortunately so there's not much I can do to help you here, my guess it's potentially due to the older versions of gms play services SDKs. 

I'd recommend updating to at least 4.3.8 if you can.
