### ISSUE TITLE
Notifications.setBadge() causes native crash on Android when ShortcutBadger is not installed

### ISSUE THREAD

**Issue by paour** [invertase/react-native-firebase#1524]
### Issue

On Android, when not using the [optional ShortcutBadger](https://rnfirebase.io/docs/v4.3.x/messaging/android) dependency, the app suffers a native crash when setting a badge (for iOS).

The crash log contains `Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lme/leolin/shortcutbadger/ShortcutBadger;`, which makes sense.

I would expect an optional dependency to be handled in a safer manner by RNFirebase, testing whether that class is available before trying to use it, and writing a warning to the log rather than crashing…

Another way to handle this would be to implement an `IOSNotifications` class, similar to `AndroidNotifications`, to expose iOS-specific features (since explicit badges on Android are not standard, and the OS/launchers handle displaying notification dots on top of app icons that have outstanding notifications).

### Environment

1. Application Target Platform:

Both, but the crash affects only Android.

2. Development Operating System:

macOS High Sierra

3. Build Tools:

Not dependant on build tool version.

4. `React Native` version:

0.55.4 (not specific to this version)

5. `React Native Firebase` Version:

4.3.8

6. `Firebase` Module:

Notifications

7. Are you using `typescript`?

No

**Comment by mikehardy** [comment]
This is a reasonable point, and if the general stance is that badging isn't great (per discussion here #2076) then I'd expect more people to opt out on Android and decrease their dependency size, but if it's marked optional then you wouldn't necessarily expect to have to platform-check your code while still badging on iOS. If someone posts a PR for this I'd include it in a release for v5 and forward port to v6 etc
