### ISSUE TITLE
OnNotificationOpened not called on Android when App is in background or close

### ISSUE THREAD

**Issue by mikenDev** [invertase/react-native-firebase#1525]
### Issue

I have an onNotificationOpened listener on my homepage that check if the app is opened by tapping on the notification and navigates the user to the inbox screen.

When selecting a notification from the tray, the onNotificationOpened function is called in all cases on IOS - foreground/background/close

On Android, the same function is called only when the app is in foreground. I noticed the getInitialNotification function is called when the app is in background or even closed. However after navigating to the inbox and removing all notification, when I come back to the homepage, the getIntialNotifcation function is called again

Any idea on how to handle this case?

Here is a snippet of my navigation service

class NavigationService {
  constructor (navigationProp) {
    this.navigation = navigationProp
  }

    _startPushNavigation = () => {
      this._listenForNotification()
    }

    _stop = () => {
      this._listenForNotification()
    }

    // onNotificationOpened is not being call on Android when app is in background or close
    _listenForNotification = () => {
      Firebase
        .notifications()
        .onNotificationOpened((notificationOpen) => {
          this._navigateToInboxScreen()
        })

      Firebase.notifications().getInitialNotification(() => {
        this._navigateToInboxScreen()
      })
    }

    _navigateToInboxScreen = () => {
     //remove all notifications
      Firebase.notifications().removeAllDeliveredNotifications()
      // navigate to inbox here
    }
}

### Environment

1. Application Target Platform:

Both

2. Development Operating System:

macOS Sierra

3. Build Tools:

4. `React Native` version:

0.53.0

5. `React Native Firebase` Version:

4.2.0

6. `Firebase` Module:

messaging

7. Are you using `typescript`?

no

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Ehesp** [comment]
https://github.com/invertase/react-native-firebase/issues/1331
