### ISSUE TITLE
split into separate modules 

### ISSUE THREAD

**Issue by tonmanayo** [invertase/react-native-firebase#1526]
For feature requests please visit our [Feature Request Board](https://boards.invertase.io/react-native-firebase).
So a found a lot of people using this library only use 1 or two features and it ships off with everything

Could you not split it into react-native-firebase-analytics, react-native-firebase-auth etc

**Comment by Ehesp** [comment]
Hey, yes this is something we're very much aware of but requires a lot of planning. There are chats going on internally about this, but if you could make a request on canny we can keep you updated there.
