### ISSUE TITLE
Native crash when receiving some kinds of FCM messages (wix v2 app)

### ISSUE THREAD

**Issue by hugows** [invertase/react-native-firebase#1527]
### Issue

Native crash when receiving some kinds of FCM messages. The issue:

- My app is using Wix navigation library (Wix v2 Application [main class seems to be this](https://github.com/wix/react-native-navigation/blob/v2/lib/android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java)  
- App is on the foreground
- Receiving a non-notification FCM message (e.g. with data key) and...

The app crashes/closes with the following error (seen on Android Studio):

 ```
--------- beginning of crash
09-25 07:20:55.555 6609-6979/com.XXX E/AndroidRuntime: FATAL EXCEPTION: Firebase-RNFirebaseMessagingService
    Process: com.XXX, PID: 6609
    java.lang.ClassCastException: com.XXX.MainApplication cannot be cast to com.facebook.react.bridge.ReactContext
        at io.invertase.firebase.Utils.isAppInForeground(Utils.java:155)
        at io.invertase.firebase.messaging.RNFirebaseMessagingService.onMessageReceived(RNFirebaseMessagingService.java:34)
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:60)
        at com.google.firebase.iid.zzg.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)
09-25 07:20:55.561 6609-6979/com.XXX I/Process: Sending signal. PID: 6609 SIG: 9
```

(I was trying this setup to create "custom notifications" from my own JS code like the docs explain - but will revert to notification messages which were properly working - thanks for the project!)

### Environment

1. Application Target Platform:

Android

2. Development Operating System:

Ubuntu 18.04

3. Build Tools:

Android Studio 3.1.4, Android SDK 26

4. `React Native` version:

"0.56.0",

5. `React Native Firebase` Version:

"react-native-firebase": "^5.0.0-rc4",

6. `Firebase` Module:

messaging

7. Are you using `typescript`?

no

---

**Comment by Salakar** [comment]
Thanks for the report - have just pushed a fix for this in https://github.com/invertase/react-native-firebase/commit/fb6153db94a9bf70fbfd347e41d8006042e56ae2

This will be available in the v5 release later today. 👍 	

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
