### ISSUE TITLE
[ios] Fails to build with default XCode 10 settings

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#1529]
### Issue

Below is set of errors that pops up during `Compiling RNFirebaseFunctions.m` step of the build. Most suggestions online ask to clear build / derived data folder, but it doesn't seem to help.

> ▸ Building RNFirebase/RNFirebase [Release]
> ▸ Check Dependencies
> ▸ Compiling RNFirebaseFunctions.m
> ~~~~~~~ ^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: could not build module 'Darwin'
> #include <sys/types.h>
>  ~~~~~~~ ^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/usr/include/dispatch/dispatch.h:25:10: could not build module 'Darwin'
> #include <Availability.h>
>  ~~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/usr/include/os/object.h:25:10: could not build module 'Darwin'
> #include <Availability.h>
>  ~~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: could not build module 'CoreFoundation'
> #include <CoreFoundation/CoreFoundation.h>
>  ~~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/usr/include/objc/objc.h:31:10: could not build module 'Darwin'
> #include <sys/types.h>      // for __DARWIN_NULL
>  ~~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:27:10: could not build module 'Darwin'
> #include <TargetConditionals.h>
>  ~~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/CoreServices.framework/Headers/UTCoreTypes.h:19:10: could not build module 'CoreFoundation'
> #include <CoreFoundation/CoreFoundation.h>
>  ~~~~~~~~^
> ❌  /Users/vagrant/git/packages/skimitar-app/node_modules/react-native-firebase/ios/RNFirebase/functions/RNFirebaseFunctions.h:3:9: could not build module 'Foundation'
> #import <Foundation/Foundation.h>
>  ~~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:9: could not build module 'Foundation'
> #import <Foundation/Foundation.h>
>  ~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBase.h:8:10: could not build module 'Darwin'
> #include <stdbool.h>
>  ~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CABase.h:11:10: could not build module 'Darwin'
> #include <stdbool.h>
>  ~~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/EAGL.h:8:10: could not build module 'Foundation'
> #include <Foundation/Foundation.h>
>  ~~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLDefines.h:8:9: could not build module 'Darwin'
> #import <os/availability.h>
>  ~~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/IOSurface.framework/Headers/IOSurfaceBase.h:12:10: could not build module 'Darwin'
> #include <sys/cdefs.h>
>  ~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CoreImageDefines.h:10:10: could not build module 'Darwin'
> #include <TargetConditionals.h>
>  ~~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CoreVideo.h:16:10: could not build module 'Darwin'
> #include <TargetConditionals.h>
>  ~~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/ImageIO.framework/Headers/ImageIOBase.h:11:10: could not build module 'Darwin'
> #include <stdbool.h>
>  ~~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTDefines.h:12:10: could not build module 'Darwin'
> #include <Availability.h>
>  ~~~~~~~~^
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/FileProvider.framework/Headers/NSFileProviderDomain.h:8:9: could not build module 'Foundation'
> #import <Foundation/Foundation.h>
>  ~~~~~~~~^
> ▸ Compiling RNFirebaseInstanceId.m
> ❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: could not build module 'Darwin'
> #include <sys/types.h>
>          ^~~~~~~~
> ** ARCHIVE FAILED **

<img width="560" alt="screenshot 2018-11-14 at 09 51 01" src="https://user-images.githubusercontent.com/3154053/48470929-0dd60880-e7f3-11e8-9496-d1f25a6db46f.png">

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS Mojave 10.14

3. Build Tools: XCode 10 (set to legacy build setting)

4. `React Native` version: 0.57.1

5. `React Native Firebase` Version: 5.0.0-rc5

6. `Firebase` Module: Functions?

7. Are you using `typescript`? yes

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by IljaDaderko** [comment]
Completely closing xcode, reinstalling node_modules and cleaning derrived data / build helped.

**Comment by Fouppy** [comment]
How did you fix this on your CI? I'm facing the same issue on Bitrise

**Comment by IljaDaderko** [comment]
@Fouppy My ci is still broken, but this is not an issue with react native firebase. I assume you updated to XCode 10 there? I'm on bitrise as well, using fastlane and got everything in place to clean build folder and clear derrived data, but for some reason it is not doing the trick :/ I assume it might be an issue with fastlane in my case

Here is an issue I opened there
https://github.com/fastlane/fastlane/issues/13436

Meanwhile I am waiting for feedback here, to see if I can set up a bash script to clean all of these areas before building
https://stackoverflow.com/questions/52517921/bash-script-to-clean-xcode-10-build-derived-data-folders

**Comment by Fouppy** [comment]
Actually I'm still on XCode 9.X, but managed to fix my builds by replacing `npm i` with the following script:

`watchman watch-del-all && rm -rf ios/build/* && rm -rf node_modules/ && npm cache verify && npm i`

Not sure which part of this script is really relevant, as it is more a local cleanup solution, nonetheless it succeeded.

Btw I'm not using Fastlane (yet!).

Hope this helps :)

**Comment by hugopretorius72** [comment]
Any fix for this yet? I am also using CI and get the exact same issue on two of my projects.  Two other projects with the same setup works just fine.  I can't seem to find whats different and causing this.

**Comment by gabsschneider** [comment]
I am having the same issue in XCode 10 using the new build system, the suggested solutions are not working. In my case, the app was running and compiling just fine on the simulator, but when I changed for the production build it started getting the error messages shown above, now it doesn't even build for the simulator

**Comment by codeflows** [comment]
This is probably related to https://github.com/firebase/firebase-ios-sdk/issues/1916 ?

**Comment by codeflows** [comment]
Also having mostly random build failures here, when building from scratch on CircleCI (with Xcode 9.4.1, Firebase 5.9.0, react-native-firebase 5.0.0)

The firebase-ios-sdk issue referenced above has a hint that this might be related to the header map setting? The error messages I'm getting are a bit undeterministic but along the lines of

```
❌  /Users/distiller/user/projects/xyz/node_modules/react-native-firebase/ios/RNFirebase/instanceid/RNFirebaseInstanceId.h:3:9: could not build module 'Foundation'

#import <Foundation/Foundation.h>
 ~~~~~~~~^


▸ Compiling RNFirebaseAdMobRewardedVideo.m
▸ Compiling RCTConvert+UIBackgroundFetchResult.m

** ARCHIVE FAILED **


The following build commands failed:
CompileC /Users/distiller/Library/Developer/Xcode/DerivedData/xyz-ankmumdxtthuucctmkmqtifwqzxf/Build/Intermediates.noindex/ArchiveIntermediates/Staging/IntermediateBuildFilesPath/RNFirebase.build/Release-iphoneos/RNFirebase.build/Objects-normal/armv7/RNFirebaseInstanceId.o RNFirebase/instanceid/RNFirebaseInstanceId.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
[08:07:00]: Exit status: 65
```

**Comment by julo15** [comment]
I just managed to wire up our iOS build to bitrise (we use Buddybuild for CI, but i'm more familiar with bitrise so I decided to give it a shot). i ran into the same issue with pulling in the incorrect `time.h` header.

what was interesting, though, is that bitrise seemed to compile successfully before i got all the signing cert stuff set up correctly on bitrise. it seemed to compile RNFIrebaseInstanceId.m and other RNFirebase files without complaining, until barfing because of a lack of signing certs (`error: exportArchive: No signing certificate "iOS Distribution" found`).

i'm not that familiar with the iOS build system (I'm primarily an android dev), so i'm not sure if what i saw was just a red herring.

**Comment by gabsschneider** [comment]
I am facing the same issue as the author of this thread. My app was running fine on the simulator but when I changed for the generic build it started throwing the errors outlined here. I have no knowledge of the ios build system so don't know what to do..

**Comment by IljaDaderko** [comment]
@hugopretorius72 @gabsschneider @julo15 @codeflows This issue is not related to `react-native-firebase` per se, after tinkering with it for a while I believe its something to do with XCode 10's legacy build system not being used on CI.

Me and my friend both set our XCode's to use legacy build system, it changed some entry in plist file, so we thought that it will persist everywhere, however when we pulled our repo on a new machine that used fresh version of XCode, it was not set to build system.

Easiest workaround atm is to deploy via non-ci i.e. straight from XCode or revert to earlier react version.

There is also this response I got from bitrise ci support
```
According to the Xcode documentation you can disable the modern buildsystem using the -UseModernBuildSystem=0
```

Thats a flag xcode cli tools use ^ I think you can specify it in fastlane or ci tool you are using to archive your apps.

Also, this will likely be resolved with react-native 0.58 as there are efforts being made to make it work with XCode's new build system.
https://github.com/facebook/react-native/pull/21458

Hope this helps :)

**Comment by Salakar** [comment]
You can persist the legacy build system by making sure to add the following file as part of git: https://github.com/invertase/react-native-firebase-starter/blob/master/ios/RNFirebaseStarter.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings - with the setting of course.

**Comment by dwmkerr** [comment]
I've been having the same issue intermittently (in fact, most of the time) even with XCode 9.

Here's an example of the failing output:

```
▸ Building library libReactNativeTestFairy.a
▸ Building library libReactNativeTestFairy.a
▸ Building RNFirebase/RNFirebase [Release]
▸ Check Dependencies
▸ Compiling RNFirebaseFunctions.m

❌  /Applications/Xcode-10.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: could not build module 'Darwin'

#include <sys/types.h>
         ^~~~~~~~
```

And here's a link to an example failing build:

https://circleci.com/gh/dwmkerr/gameboard/945

*Reproduction Steps*

Push any code to build on CircleCI, it will most likely fail with errors similar to the above. However, it will *not* fail when building locally. I'm using Fastlane. Here's a link to the repo:

https://github.com/dwmkerr/gameboard/

And the `Fastfile`:

https://github.com/dwmkerr/gameboard/blob/master/fastlane/Fastfile

*What I've Tried*

1. Cleaning Caches
2. Upgrading to XCode 10
3. Forcing 'use legacy build' with `xcargs: "-UseModernBuildSystem=0"`
4. Forcing 'use legacy build' with `xcargs: "-UseNewBuildSystem=NO"`
5. Making sure the `xcsettings` are committed, as per @Salakar's suggestion

I just can't get these builds to work now on CircleCI, any other suggestions for what could be going on?

**Comment by codeflows** [comment]
I'd like to have this re-opened as well, our situation is similar to @dwmkerr's. Xcode 9, Circle CI, Fastlane. Working locally 100% of the time but never on the CI.

**Comment by IljaDaderko** [comment]
@Salakar I think this is worth re-opening now, here is additional context:
react-native@0.57.5 was released that claims to fix XCode 10's build issues i.e. we can use default one instead of legacy now:
https://twitter.com/Kelset/status/1062390902616920065

However this error keeps happening, now on any build either dev / prod / local or ci if new build system is enabled.

**Comment by IljaDaderko** [comment]
If anyone feels brave, I got this working when I changed my project to use react and RNFirebase via CocoaPods (not recommended if you are not comfortable with XCode / iOS dev practices)
https://facebook.github.io/react-native/docs/integration-with-existing-apps

Judging by https://github.com/facebook/react-native/issues/20774#issuecomment-438609643
issue that `react-native-firebase` is having can still be on `react-native` side, although before I started using CocoaPods approach I applied all necessary patches and still got this error :/

**Comment by sowdri** [comment]
@Fouppy @IljaDaderko A simple fix for bitrise is to choose XCode 9.x as your build stack. I was facing the same issue using XCode 10, and later reverted to 9.x and was able to build successfully. Hope this helps.

**Comment by ukris** [comment]
Please do not close this. I am still having the issue

**Comment by mtnptrsn** [comment]
I'm also having the same issue.

**Comment by IljaDaderko** [comment]
@mtnptrsn @ukris Are you guys seeing same error as in https://github.com/invertase/react-native-firebase/issues/1529#issue-363711231 or something else?

Could you drop your environment info. Also is this happening locally or in CI environment? Debug or Release builds?

**Comment by vinnybad** [comment]
I’m seeing this issue on my CI only (bitrise). I’m using fastlane. Everything was fine until I added a cocoapod subspec for using the Firebase database. I build release builds on my CI, but I suspect it happens for debug builds as well. 

Locally, I saw the issue when I was using the modern build system. I’ve manually changed it in the workspace and am passing in the appropriate flags to force it to use the legacy build system. No luck.

**Comment by sauravexodus** [comment]
Any luck with this issue. Still a problem for me :(

**Comment by rangav** [comment]
Looks like the problem is in react-native-firebase library version.

in Podfile
`pod 'Firebase/Core'`

pod install 

and i have used     
"react-native-firebase": "5.1.1" ( 5.2.3 did not work for me)

This made the project build sucessfully.

**Comment by sauravexodus** [comment]
@vinnybad I am using Bitrise as well. Let me know if you find any solution to this misery.

**Comment by seblau** [comment]
Having the same issue. Happens more or less randomly with about every 5th build. Reproduced on multiple Macbooks and Mac Mini (CI). Using Xcode 10 legacy build.
I noticed that the error is caused by both react-native-flurry-analytics and react-native-firebase respectively.

Here is the error log, in this case cause by react-native-flurry-analytics:

```
[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: [31mcould not build module 'Darwin'[0m

#include <sys/types.h>
[36m                   ^~~~~~~~~[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/dispatch/dispatch.h:25:10: [31mcould not build module 'Darwin'[0m

#include <Availability.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/os/object.h:25:10: [31mcould not build module 'Darwin'[0m

#include <Availability.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: [31mcould not build module 'CoreFoundation'[0m

#include <CoreFoundation/CoreFoundation.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/objc/objc.h:31:10: [31mcould not build module 'Darwin'[0m

#include <sys/types.h>      // for __DARWIN_NULL
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:27:10: [31mcould not build module 'Darwin'[0m

#include <TargetConditionals.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreServices.framework/Headers/UTCoreTypes.h:19:10: [31mcould not build module 'CoreFoundation'[0m

#include <CoreFoundation/CoreFoundation.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Users/jenkins/Library/Developer/Xcode/DerivedData/MyShoes-cbjraxzqfnuulubitdnpuijtenie/Build/Intermediates.noindex/ArchiveIntermediates/MyShoes/BuildProductsPath/Release-iphoneos/include/React/RCTBridgeModule.h:8:9: [31mcould not build module 'Foundation'[0m

#import <Foundation/Foundation.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:9: [31mcould not build module 'Foundation'[0m

#import <Foundation/Foundation.h>
[36m ~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBase.h:8:10: [31mcould not build module 'Darwin'[0m

#include <stdbool.h>
[36m ~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CABase.h:11:10: [31mcould not build module 'Darwin'[0m

#include <stdbool.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/EAGL.h:8:10: [31mcould not build module 'Foundation'[0m

#include <Foundation/Foundation.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLDefines.h:8:9: [31mcould not build module 'Darwin'[0m

#import <os/availability.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/IOSurface.framework/Headers/IOSurfaceBase.h:12:10: [31mcould not build module 'Darwin'[0m

#include <sys/cdefs.h>
[36m ~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CoreImageDefines.h:10:10: [31mcould not build module 'Darwin'[0m

#include <TargetConditionals.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CoreVideo.h:16:10: [31mcould not build module 'Darwin'[0m

#include <TargetConditionals.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/ImageIO.framework/Headers/ImageIOBase.h:11:10: [31mcould not build module 'Darwin'[0m

#include <stdbool.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTDefines.h:12:10: [31mcould not build module 'Darwin'[0m

#include <Availability.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/FileProvider.framework/Headers/NSFileProviderDomain.h:8:9: [31mcould not build module 'Foundation'[0m

#import <Foundation/Foundation.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKAdNetwork.h:8:9: [31mcould not build module 'Foundation'[0m

#import <Foundation/Foundation.h>
[36m ~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: [31mcould not build module 'Darwin'[0m

#include <sys/types.h>
[36m                   ^~~~~~~~~[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/dispatch/dispatch.h:25:10: [31mcould not build module 'Darwin'[0m

#include <Availability.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/os/object.h:25:10: [31mcould not build module 'Darwin'[0m

#include <Availability.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: [31mcould not build module 'CoreFoundation'[0m

#include <CoreFoundation/CoreFoundation.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/objc/objc.h:31:10: [31mcould not build module 'Darwin'[0m

#include <sys/types.h>      // for __DARWIN_NULL
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:27:10: [31mcould not build module 'Darwin'[0m

#include <TargetConditionals.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreServices.framework/Headers/UTCoreTypes.h:19:10: [31mcould not build module 'CoreFoundation'[0m

#include <CoreFoundation/CoreFoundation.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Users/jenkins/Library/Developer/Xcode/DerivedData/MyShoes-cbjraxzqfnuulubitdnpuijtenie/Build/Intermediates.noindex/ArchiveIntermediates/MyShoes/BuildProductsPath/Release-iphoneos/include/React/RCTBridgeModule.h:8:9: [31mcould not build module 'Foundation'[0m

#import <Foundation/Foundation.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:9: [31mcould not build module 'Foundation'[0m

#import <Foundation/Foundation.h>
[36m ~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBase.h:8:10: [31mcould not build module 'Darwin'[0m

#include <stdbool.h>
[36m ~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CABase.h:11:10: [31mcould not build module 'Darwin'[0m

#include <stdbool.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/EAGL.h:8:10: [31mcould not build module 'Foundation'[0m

#include <Foundation/Foundation.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLDefines.h:8:9: [31mcould not build module 'Darwin'[0m

#import <os/availability.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/IOSurface.framework/Headers/IOSurfaceBase.h:12:10: [31mcould not build module 'Darwin'[0m

#include <sys/cdefs.h>
[36m ~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CoreImageDefines.h:10:10: [31mcould not build module 'Darwin'[0m

#include <TargetConditionals.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CoreVideo.h:16:10: [31mcould not build module 'Darwin'[0m

#include <TargetConditionals.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/ImageIO.framework/Headers/ImageIOBase.h:11:10: [31mcould not build module 'Darwin'[0m

#include <stdbool.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTDefines.h:12:10: [31mcould not build module 'Darwin'[0m

#include <Availability.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/FileProvider.framework/Headers/NSFileProviderDomain.h:8:9: [31mcould not build module 'Foundation'[0m

#import <Foundation/Foundation.h>
[36m ~~~~~~~~^[0m



[31m❌  [0m/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKAdNetwork.h:8:9: [31mcould not build module 'Foundation'[0m

#import <Foundation/Foundation.h>
[36m ~~~~~~~^[0m


** ARCHIVE FAILED **


The following build commands failed:
CompileC /Users/jenkins/Library/Developer/Xcode/DerivedData/MyShoes-cbjraxzqfnuulubitdnpuijtenie/Build/Intermediates.noindex/ArchiveIntermediates/MyShoes/IntermediateBuildFilesPath/RNFlurryAnalytics.build/Release-iphoneos/RNFlurryAnalytics.build/Objects-normal/armv7/RNFlurryAnalytics.o RNFlurryAnalytics.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
CompileC /Users/jenkins/Library/Developer/Xcode/DerivedData/MyShoes-cbjraxzqfnuulubitdnpuijtenie/Build/Intermediates.noindex/ArchiveIntermediates/MyShoes/IntermediateBuildFilesPath/RNFlurryAnalytics.build/Release-iphoneos/RNFlurryAnalytics.build/Objects-normal/arm64/RNFlurryAnalytics.o RNFlurryAnalytics.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
```

**Comment by ottoo** [comment]
Is there no solution to this? I am getting this as well when upgrading to 5.2.3. Have been using 4.3.8 so far and don't get these errors with that version.

**Comment by luco** [comment]
+1 on this. Can't build.

**Comment by duongkhoilinh** [comment]
+1. I'm having the exact same issue and I can't deploy my app to TestFlight :(

**Comment by ottoo** [comment]
I managed to figure out my issue, I think. In the end it was not related to react-native-firebase, kind of. Another library that I used had its *header search paths* set to `/ios/Pods/**` which meant that that library would look for headers everywhere in all the Pods. Limiting that library's header search path to `/ios/Pods/[libraryname]` fixed the issue.

**Comment by brenwell** [comment]
That’s interesting. Firebase‘s Firestore podspec has the Pods folder as a header search path. But not recursive

**Comment by sonlexqt** [comment]
For me, it's turn out after upgrading `react-native-firebase` to v5.3.1, I have to modify the versions of pod dependencies [like so](https://rnfirebase.io/docs/v5.x.x/releases/v5.3.x#iOS---Update-Firebase-SDKs). After this, the problem is gone!

**Comment by inkwaris** [comment]
+1 on this. I'm also having the same issue.

**Comment by makedirectory** [comment]
I think I'm still having this issue w/ 5.20.1. App only seems to compile after a few attempts... tried to reinstall pods, updated headers, etc.

No luck.

**Comment by mikehardy** [comment]
I’m fairly certain you still need to set legacy build system for react-native-firebase v5

**Comment by makedirectory** [comment]
I've been using the new build system w/ version 5 since I started working with it. The problem is with the search header paths in xCode.

More information can be found here: https://github.com/firebase/firebase-ios-sdk/issues/2260#issuecomment-461601816

**Comment by HugoKawamata** [comment]
Updating the firebase pod dependencies to 5.20.1 fixed this for me, on CircleCI.

**Comment by henrymoulton** [comment]
Getting this issue using App Center Build, has anyone solved it?

**Comment by noway** [comment]
For me it was the matter of settings $(SRCROOT) from recursive to non-recursive in Header Search Path:
![image](https://user-images.githubusercontent.com/2031472/193498999-eb732d44-68d3-4aa1-adfa-b1cc1c19926c.png)
