### ISSUE TITLE
Using RNFirebase for a React Web App

### ISSUE THREAD

**Issue by babara2** [invertase/react-native-firebase#1530]
Hi, 

I was wondering if it is at all possible to use RNFirebase for a ReactJS webapp. I really like how the notifications module is implemented and would like to use the functionality for my web app.

**Comment by Salakar** [comment]
@babara2 for the Web you'll have to use the official Firebase Web SDK, we use the native Android & iOS SDK's on this library. Notifications is very much specific to Android or iOS devices.

Web SDK: https://firebase.google.com/docs/web/setup

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by gsouf** [comment]
@Salakar what's about today with react-native-web ?

**Comment by Ehesp** [comment]
@gsouf no change. This library targets Android & iOS so using the Firebase official Web SDK is the way to go.

I'm going to lock this, as this library will never be usable on the web.

**Comment by gsouf** [comment]
To the question:

> what's the recommended way to work with invertase for an application that compiles to ios/android and web?

Invertase's team answered:

> Your best bet is to create a file which returns an instance of Firebase depending on the environment. Our SDK matches the Web SDK where it can, however there are differences, so the experience may be tricky.

**Comment by mikehardy** [comment]
Or have an interface that abstracts your firebase services, and in your bootstrap switch based on platform which firebase implementation is used to implement the interface, a classic example being something like pluggable database drivers in native apps
