### ISSUE TITLE
Firebase auth continues to automatically log the user back in after it has been disabled?

### ISSUE THREAD

**Issue by booboothefool** [invertase/react-native-firebase#1532]
Using `5.0.0-rc4` on iOS.

After the user is disabled in Firebase console gui, firebase.auth() continues to refresh the user.

I would expect the user is not automatically logged in again after they have been set to disabled.

Only after `firebase.auth().signOut()` is the user blocked from logging in again.

**Comment by Ehesp** [comment]
This is normal behaviour I'm afraid. If you want real time updates for disabling, I'd recommend syncing the user up with the RTDB.
