### ISSUE TITLE
Remove notification permission

### ISSUE THREAD

**Issue by damathryx** [invertase/react-native-firebase#1534]
I would like to implement a switch for notification inside the app. Is there an api to remove permission?

**Comment by erandagan** [comment]
If you want to allow the user to disable notifications, revoking the permission isn't the way to go. Once granted permission, your app (both iOS and Android) can't revoke it (really, why would it?), the user is the only one who can.

You should simply set some sort of persistent user preference and check it before displaying notifications.

**Comment by damathryx** [comment]
@erandagan how do I do that when the app is closed?

**Comment by erandagan** [comment]
It depends on how you implemented notifications in the first place. For example if you send them from the server, just keep a boolean in your database indicating if you should send notifications to a particular user.

Anyway this is really out of the scope of this package and I suggest you ask on stackoverflow.

**Comment by AkilLis** [comment]
@erandagan In this case if customer is logged out without internet connection we couldn't mark as logged out. So customer still receive push notification in app closed. What am i thinking is at least we need to revoke permission.

**Comment by AkilLis** [comment]
@Ehesp Any advice on this case?.

**Comment by yangnana11** [comment]
I looked for a way as you asked but I couldn't.
I tried another way. If you don't mind this one, you can take it as reference:
https://medium.com/@yangnana11/how-to-turn-on-and-off-firebase-notification-on-phones-56b436a3e38b

**Comment by AkilLis** [comment]
@yangnana11  Thanks for your response. It seems to me we redirect user to disable notification from settings when user want to log out. This method might be some bad consequences. But user refuses to disable notification. After that we still send them push notification when user connected to the internet even user has already logged out.

**Comment by yangnana11** [comment]
Ah, you have different approach to mine.
In that case, I think you should have something in your database like "is_notify" column, so when user log out, he doesn't get any notification from your server.

**Comment by AkilLis** [comment]
@yangnana11 Yes i did. We can toggle status in database only user connected to the internet. If user logged out without internet connection we could't handle it. Next time user connected to the internet we push notification to them. That is a some lack of internet connection issue.

**Comment by yangnana11** [comment]
@AkilLis I think your logout function should return value. They can only success logging out when we finish the job in server

**Comment by AkilLis** [comment]
@erandagan Exactly. We force them to connect internet first. But it is weird experience for customers.
