### ISSUE TITLE
Build is getting failed

### ISSUE THREAD

**Issue by jatinseth2007** [invertase/react-native-firebase#1536]
I have followed the documentation provided at https://rnfirebase.io/docs/v5.x.x/installation/ios to run firebase notification for my app, It's running fine on simulator but while I am trying to build (to run on my iphone), it's giving me error as shown in following image.

![screen shot 2018-09-27 at 4 32 28 pm](https://user-images.githubusercontent.com/8512903/46142090-6b2dee80-c273-11e8-99e1-2b67ecd3d6b5.png)

I am new using pods and tried lot of things but nothing is working for me.

My POD file is given below:
![screen shot 2018-09-27 at 5 18 17 pm](https://user-images.githubusercontent.com/8512903/46143984-5bb1a400-c279-11e8-8095-17f3576d6036.png)

**Comment by Ehesp** [comment]
This happens when iOS cannot find the Firebase pod. Try deleting the Podfile.lock, deleting the pods directory and running `pod install` again.

**Comment by jatinseth2007** [comment]
@Ehesp I have tried it and did not help, I have updated my issue by adding my pod file too. I have understood that it's happening cuz IOS is not able to find pod but how to solve it, not able to find solution.

**Comment by Salakar** [comment]
@jatinseth2007 

Try move your pods into the `target` scope. Also make sure you version your pods like the documentation states, otherwise you could run into issues later on, e.g.

```ruby
pod 'Firebase/Core', '~> 5.9.0'
pod 'Firebase/Messaging', '~> 5.9.0'
```

Also ensure you're opening the generated xcworkspace file in xcode and not the xcodeproj file.

I'd recommend checking out: [YouTube - Install React Native Firebase Core [iOS]](https://www.youtube.com/watch?v=qiOGMcX6Xtw)

**Comment by jatinseth2007** [comment]
@Salakar Oh!, my bad, I was using collective.xcodeproj instead of collective.xcworkspace and it was creating that problem( I did not find this instruction on official documentation or maybe I missed this one), It's working now, thanks for help mate (beer)
