### ISSUE TITLE
Help in understanding RNFirebaseBackgroundMessage because it does not work even with JobScheduler

### ISSUE THREAD

**Issue by aboutonlineblog** [invertase/react-native-firebase#1538]
I have been scratching my head for a while now thinking what is missing. I decided to create my own notification because I am aiming for a rich content push notification with custom large icons and big pictures (which I successfully created).

I create a function called **ShowNotification** that accepts parameters necessary to display that rich content notification such as image urls, titles, content and so on. The payload looks like this:

    {
      data: {
        notificationId: 1,
        iconURL: "http://....so on",
        bigPicURL: "http://...so on",
        title: "My Notification",
        content: "My Content",
      },
      to: token
    }

I got the above payload by listening to the **RNFirebaseBackgroundMessage**

    AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage' (message: RemoteMessage) => {
       console.log('PAYLOAD', message);
    });

The above listener work perfectly and my custom notification works when app is minimised; however, when I totally close the app, it does not work anymore. I tried to Log the `onMessageReceived(RemoteMessage message)` and closed the app then send another push notification. Nothing is being received.

Did a lot of search and decided to create a JobScheduler that runs in every 6 seconds when the app is in background or inactive (I used the React native AppState to trigger the scheduler if app is in background state).

Now as soon as the scheduler starts, the `onMessageReceived(RemoteMessage message)` started to receive the payload even if the app is killed or closed (which is a good news). Now the problem I have now is that the `AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage')` is still not being triggered hence my custom notification will not show.

I need some advice on what to do from here.

Is there a way to trigger this `AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage')` once the scheduler starts?

Is there another trick to make it work?

Please help thank you.

**Comment by Salakar** [comment]
@aboutonlineblog have you added the background service indicated here: https://rnfirebase.io/docs/v5.x.x/messaging/android#(Optional)-Background-Messages

**Comment by aboutonlineblog** [comment]
@Salakar - Thank you so much for the response . . yep I already added it in my Manifest . . which I believe why `AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage')` works when I minimise the app but when I totally close the app it will no longer trigger even with JobScheduler.

**Comment by aboutonlineblog** [comment]
Is there a way I can create a class and use the onMessageReceived method inside the class like:

import io.invertase.firebase.messaging.RNFirebaseMessagingService;
import android.util.Log;
import com.google.firebase.messaging.RemoteMessage;

```
public class CPNBroadcastReceiver extends RNFirebaseMessagingService {
  @Override
  public void onMessageReceived(RemoteMessage message) {
    super.onMessageReceived(message);

    RNFirebaseMessagingService instance = new RNFirebaseMessagingService();

    // DON'T KNOW HOW TO MAKE IT WORK
  }
}
```
I do not know what to do next

**Comment by aboutonlineblog** [comment]
Never mind I figured it out, It appears you can not have two FirebaseMessagingService in one project.

**Comment by shuzootani** [comment]
https://medium.com/@chornenkyy.v/do-you-want-to-use-two-or-more-firebasemessagingservices-at-once-67236d1bd9e0
