### ISSUE TITLE
[iOS] Sound not working. Android is perfect.

### ISSUE THREAD

**Issue by vendramini** [invertase/react-native-firebase#1539]
### Issue

iOS not playing sound.

```javascript
const notification = new firebase.notifications.Notification()
    .setTitle("message.title")
    .setBody("message.body")
    .setSound("default")
    .setNotificationId("message.action");
firebase.notifications().displayNotification(notification);
```
I'm also trying to play a custom sound "alarm.mp3", that doesn't work. I added it to my Xcode project.
I'm testing on iPhone 6 (11.4.1) and iPad (10.3.3). No one work.

### Environment

1. Application Target Platform:

iOS 11.4.1 and 10.3.3.

2. Development Operating System:

Developing on Linux Mint, but compiling on macOS High Sierra 10.13.6.

3. Build Tools:

Xcode 9.4.1

4. `React Native` version:

0.55.4

5. `React Native Firebase` Version:

ˆ5.0.0

7. Are you using `typescript`?

No.

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by vendramini** [comment]
Shame on me, sorry guys. I'm not familiar with apple toys, didn't know about a beautiful mute button hidden on device's side. :sweat:

**Comment by dominicsavb** [comment]
at iOS, where you put mp3 file at xcode? 

Thank you

**Comment by joeabill** [comment]
@dominicsavb I believe with iOS you have to load the audio file thru Xcode.

**Comment by thienbao92** [comment]
I had exactly similar issue with @vendramini. Beautiful mute button causes big trouble lol.
