### ISSUE TITLE
'RCTEventDispatcher.h' file not found

### ISSUE THREAD

**Issue by chawax** [invertase/react-native-firebase#154]
Hi,

When I build a React Native project with React Native Firebase I have the following error :

![image](https://user-images.githubusercontent.com/5655399/26985889-c2bc5fd2-4d45-11e7-9e30-80d5ba8c49f2.png)

My project uses React Native 0.42.3.

Any idea how I could solve this problem ?

**Comment by Ehesp** [comment]
Please follow issue 77 for this.

**Comment by paulftw** [comment]
Having exactly same issue. Tried recreating the project from scratch and following the install instructions multiple times.

I know maintainers are focused on the new better version but it's frustrating that we cannot prototype while waiting for it to go live.

**Comment by Salakar** [comment]
@paulftw I can assure you we've spent many hours of our time and still are trying to sort this one, so its not for lack of trying.

**Comment by chrisbianca** [comment]
@paulftw I have completely rewritten the iOS setup instructions to better support new projects.  It seems that the majority of the problems were being caused by `react-native link` so whilst the process if now a little more manual, it should be much more resilient.
