### ISSUE TITLE
Schedule background notification

### ISSUE THREAD

**Issue by esipavicius** [invertase/react-native-firebase#1542]
It is possible to set schedule notification with react-native-firebase and receive it in background when app was closed? If yes so how or it should be only possible with push notification?

I created schedule notification listener but only get notif when app is open.

I tried package https://github.com/zo0r/react-native-push-notification and here everything working ;/

**Comment by esipavicius** [comment]
I will check it again, but it was not fixed after last check.

**Comment by gglee89** [comment]
@esipavicius I am also experiencing the same thing.

Whenever I close my app on iOS I stop receiving notifications. 
But if my app is either in the Foreground or Background then is okay.
