### ISSUE TITLE
Firestore startAfter is inclusive instead of exclusive

### ISSUE THREAD

**Issue by anjapadu** [invertase/react-native-firebase#1544]
### Issue

StartAfter on IOS is not inclusive. On android i don't have any problem but on IOS it includes the startAfter element.
tell me if is not a react-native-firebase problem and is firebase problem plz 

### Environment

1. Application Target Platform:

IOS

2. Development Operating System:

MacOS Sierra

3. Build Tools:

Xcode

4. `React Native` version:

0.57.1

5. `React Native Firebase` Version:

^5.0.0-rc4
pod 'Firebase/Firestore', '~> 5.6.0'

6. `Firebase` Module:

Firestore
7. Are you using `typescript`?

No

**Comment by Salakar** [comment]
Duplicate of https://github.com/invertase/react-native-firebase/issues/735

**Comment by Salakar** [comment]
Hey,

Would someone be able to provide me with a reproducible query and sample data, please?

Thanks

**Comment by mikehardy** [comment]
@Salakar this went to sleep after you failed to reproduce, recommend unpin / resolve stale?

**Comment by mikehardy** [comment]
We can't reproduce this
