### ISSUE TITLE
RNFirebase Installation: Lexical or Preprocessor Issue  + Parse Issue

### ISSUE THREAD

**Issue by felixchan** [invertase/react-native-firebase#1545]
1. Application Target Platform:

**iOS**

2. Development Operating System:

**Mac OS High Sierra**

3. Build Tools:

**XCode Version 10.0 (10A255)**

4. `React Native` version:

**0.57.1**

5. `React Native Firebase` Version:

**5.0**

6. `Firebase` Module:

```
target 'client' do

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'Firebase'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'Firebase/Firestore'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Crash'
    pod 'Firebase/DynamicLinks'
    pod 'Firebase/Performance'


  target 'clientTests' do
    inherit! :search_paths
  end

end
```

7. Are you using `typescript`?

**No**

```
$react-native init client
$cd ./client/ios/
$pod init; pod repo update; pod install
$yarn add react-native-firebase
$yarn install
$react-native link react-native-firebase
$open client.xcworkspace
```
Put GoogleService-Info.plist
Added:
```
#import <Firebase.h>
[FIRApp configure];
```
Clean Build Folder 
Build
Error

<img width="513" alt="screen shot 2018-09-30 at 8 04 52 pm" src="https://user-images.githubusercontent.com/306524/46267865-1d6feb00-c4ec-11e8-9f50-5ee4fc0ec840.png">

**Comment by Salakar** [comment]
Can you show the Error from the screenshot? This is most likely an Xcode 10 issue as well, try the following: https://github.com/facebook/react-native/issues/21168#issuecomment-422793222

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by felixchan** [comment]
Thank you, that solved it!

**Comment by StarkAndy** [comment]
Hi just wanna know how you solved it ? Can you please elaborate

**Comment by Parameshvadivel** [comment]
> Hi just wanna know how you solved it ? Can you please elaborate

Hey did you found any solution for this

**Comment by mikehardy** [comment]
@Parameshvadivel clone and run https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh - there is no issue in the module, that script will create an example app for you demonstrating same. This issue is from 2018! I suspect it no longer applies to anything current
