### ISSUE TITLE
hasPermission returns a (Promise returning a) Number (instead of a Boolean)

### ISSUE THREAD

**Issue by WaldoJeffers** [invertase/react-native-firebase#1547]
### Environment

1. Application Target Platform:
iOS

2. Development Operating System:
macOS Sierra

3. Build Tools:
XCode

4. `React Native` version:
0.54.0

5. `React Native Firebase` Version:
4.0.4

6. `Firebase` Module:
messaging

7. Are you using `typescript`?
No

---

It might be related to https://github.com/invertase/react-native-firebase/issues/1442

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by lucianomlima** [comment]
If I have a fix how I can test in my machine? I did look in repo for some guidance, but I can't find one.

**Comment by Ehesp** [comment]
@lucianomlima 	see https://github.com/invertase/react-native-firebase/tree/master/tests
