### ISSUE TITLE
⚠ Critical: Firestore collection where query returns incorrect results for "date > x"

### ISSUE THREAD

**Issue by enzomd** [invertase/react-native-firebase#1552]
Firestore > "greater than" where query results will match on results where the target property is `null` or equal to the provided query argument.

```js
const jsDate = new Date();
const where = collection.where("updateTs", ">", jsDate);

const opts = {includeQueryMetadataChanges: true};
where.onSnapshot(opts, async (qSnap) => {
    // const data = qSnap.docChanges[x].doc.data()
    // This will return:
    // - data.updateTs === null
    // - data.updateTs.getTime() === jsDate.getTime()
    //      - data.updateTs.toISOString() === jsDate.toISOString()
});
```

These should not be part of the query results when the type is "added".

### Environment

1. Application Target Platform:
iOS

2. Development Operating System:
macOS

3. Build Tools:
Xcode

4. `React Native` version:
version "0.55.3"

5. `React Native Firebase` Version:
version "4.0.6"

6. `Firebase` Module:
Firestore

**Comment by Salakar** [comment]
This is a known issue with dates, it will be fixed soon, see the current duplicate issues relating to this:

https://github.com/invertase/react-native-firebase/issues/1437
https://github.com/invertase/react-native-firebase/issues/1439

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
