### ISSUE TITLE
Firestore error: "transactionGetDocument called for non-existant transactionId 0"

### ISSUE THREAD

**Issue by enzomd** [invertase/react-native-firebase#1556]
When I read a document after a transaction, this line is printed to my logs.

Does this indicate the transaction has failed/is not atomic?

```js
const ok = await fsDb.runTransaction(async (t) => {
    t.set(docRef, data);
    // t.update(docRef, data);
    return true;
});
const d = await docRef.get();
```

```
transactionGetDocument called for non-existant transactionId 0
```

https://github.com/invertase/react-native-firebase/blob/94852c890281ffec256c8357c3488a47cb53f30d/ios/RNFirebase/firestore/RNFirebaseFirestore.m#L50

### Environment

1. Application Target Platform:
iOS

2. Development Operating System:
macOS

3. Build Tools:
Xcode

4. `React Native` version:
version "0.55.3"

5. `React Native Firebase` Version:
version "4.0.6"

6. `Firebase` Module:
Firestore

**Comment by enzomd** [comment]
@Salakar Are transactions still safe to use, or does this log message indicate an error state?

**Comment by Salakar** [comment]
@enzomd they are still safe, that log is purely there as a safeguard / fyi i.e. between RN reloads of your app in dev native vs JS can become out of sync, therefore, the transaction could exist in native but not in JS and vice versa.

Am assuming this was local dev of course?

**Comment by Salakar** [comment]
@enzomd I've reworked the transaction logic for iOS in v5.1.0, could you try out the RC and report back in a new issue if you're still seeing this log, thank you.

`yarn add react-native-firebase@5.1.0-rc1` (use /tests app on master as a reference for SDK versions)

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
