### ISSUE TITLE
Type definition of firebase.notifications.Notification() is incorrect

### ISSUE THREAD

**Issue by jonleighton** [invertase/react-native-firebase#1558]
### Issue

I instantiated a notification per [the docs](https://rnfirebase.io/docs/v5.x.x/notifications/displaying-notifications). Here's the code sample from the docs:

``` js
const notification = new firebase.notifications.Notification()
  .setNotificationId('notificationId')
  .setTitle('My notification title')
  .setBody('My notification body')
  .setData({
    key1: 'value1',
    key2: 'value2',
  });
```

However, I get a Flow error because the function signature has a mandatory argument:

https://github.com/invertase/react-native-firebase/blob/94852c890281ffec256c8357c3488a47cb53f30d/src/modules/notifications/Notification.js#L41-L44

The code seems to work fine, so presumably this argument should be optional.

### Environment

1. Application Target Platform: N/A
2. Development Operating System: N/A
3. Build Tools: N/A
4. `React Native` version: 0.56
5. `React Native Firebase` Version: 5.0.0
6. `Firebase` Module: notifications
7. Are you using `typescript`? no

**Comment by thomasw** [comment]
This is still broken.

**Comment by Ehesp** [comment]
@thomasw Can you submit a PR?

**Comment by thomasw** [comment]
@Ehesp Just to clarify my terse comment, I posted after re-verifying the issue to ensure the stale tag was removed, not as a complaint. I'd be happy to submit a fix though. I'll aim for tomorrow.
