### ISSUE TITLE
Documentation for twitter authentication is missing

### ISSUE THREAD

**Issue by johhansantana** [invertase/react-native-firebase#1561]
Hello

It seems that there's some missing documentation on social media authentication.

The only ones that I could find was with facebook and google. Twitter, Github and others are missing:
https://rnfirebase.io/docs/v5.x.x/auth/social-auth#Twitter

**Comment by Salakar** [comment]
@johhansantana correct, it, unfortunately, hasn't been documented yet, but we'd welcome a PR if anyone can send one over (click the Edit button on any docs page to be taken to the markdown file). Would be super helpful 🎉

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
