### ISSUE TITLE
Release schema Build failed

### ISSUE THREAD

**Issue by pateljaykesh** [invertase/react-native-firebase#1563]
Hello

In debug mode react native firebase is working fine.

But in release schema getting following error.

ld: library not found for -lFirebaseCore
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have did react-native link command but not working.

I am having Xcode 10. Can you help me on this?

**Comment by pateljaykesh** [comment]
yes i did but not working.same error getting.
ld: library not found for -lFirebaseCore

**Comment by Salakar** [comment]
@pateljaykesh please use the issue template, we can't guess everything about your setup 🙃 

Quick guess though, change your Xcode build system to `legacy`, see: https://github.com/facebook/react-native/issues/21168#issuecomment-422793222

Will close this issue. If you're still having problems I'd suggest making a new issue and filling out the issue template, please 👍 	

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
