### ISSUE TITLE
Error on build: No visible @interface for 'FIRQuery' declares the selector 'queryWhereFieldPath:arrayContains:'

### ISSUE THREAD

**Issue by mtzfactory** [invertase/react-native-firebase#1566]
### Issue

Build fails on file `RNFirebaseFirestoreCollectionReference.m`, at `applyFilters` method says:

`No visible @interface for 'FIRQuery' declares the selector 'queryWhereFieldPath:arrayContains:'`

The only way to make it work is commenting out the part of code that uses it...

Podfile:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'my_test_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for my_test_app

  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'
  pod 'Firebase/Firestore', '~> 5.3.0'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

end
```

### Environment

1. Application Target Platform:
iOS

2. Development Operating System:
macOS Sierra

3. Build Tools:
Xcode 10

4. `React Native` version:
0.57.1

5. `React Native Firebase` Version:
5.0.0

6. `Firebase` Module:
5.3.0

7. Are you using `typescript`?
no

---

![screen shot 2018-10-05 at 08 09 51](https://user-images.githubusercontent.com/200234/46518813-7043fc80-c876-11e8-9b5c-711aa29386a9.png)

**Comment by mtzfactory** [comment]
Hi again,

I think the error comes from __firebase-ios-sdk__, more expecifically from the header file`FIRQuery.h`, that doen't export that methods, because they are defined in `FIRQuery.m`:

_FIRQuery.m_
```
- (FIRQuery *)queryWhereField:(NSString *)field arrayContains:(id)value {
  return
      [self queryWithFilterOperator:FSTRelationFilterOperatorArrayContains field:field value:value];
}

- (FIRQuery *)queryWhereFieldPath:(FIRFieldPath *)path arrayContains:(id)value {
  return [self queryWithFilterOperator:FSTRelationFilterOperatorArrayContains
                                  path:path.internalValue
                                 value:value];
}
```

So, what do i do now? I mean, the Firebase package is installed by Pod, right? Do I have to update the sdk version in the pod file? to which one?

Does the pod system install the [sdk from here](https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore) ¿? because the definition in 'FIRQuery.h' [there is correct](https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/Source/Public/FIRQuery.h)...

Does anybody have this error as well?

Thanks.

**Comment by Salakar** [comment]
You need to be on v5.9.0 of the ios sdk, as per the docs and the v4 - v5 migration guide:

https://rnfirebase.io/docs/v5.x.x/firestore/ios#Add-the-pod
https://rnfirebase.io/docs/v5.x.x/release-notes#iOS---Update-Firebase-SDKs

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by mycoberago** [comment]
I am running into the same exact error except I did a manual install (without Cocoapods).  The application has been successful prior to this upgrade.

**Environment**
Application Target Platform:
iOS

Development Operating System:
macOS Sierra

Build Tools:
Xcode 10.2.1

React Native version:
0.59.3

React Native Firebase Version:
^5.5.3

Firebase Module:
5.9.0

Are you using typescript?
no

<img width="757" alt="Screen Shot 2019-06-27 at 9 19 53 AM" src="https://user-images.githubusercontent.com/8285427/60273918-c2252a80-98bc-11e9-8746-e6cf21d15909.png">

Below is how I have added Firebase into the Xcode.proj and the Header Search Paths I have had prior to upgrade/error.

<img width="260" alt="Screen Shot 2019-06-27 at 9 21 41 AM" src="https://user-images.githubusercontent.com/8285427/60274223-51324280-98bd-11e9-863e-8bebef51c4d6.png">

<img width="223" alt="Screen Shot 2019-06-27 at 9 23 18 AM" src="https://user-images.githubusercontent.com/8285427/60274242-57c0ba00-98bd-11e9-9573-d464ceb6b821.png">

<img width="522" alt="Screen Shot 2019-06-27 at 9 22 45 AM" src="https://user-images.githubusercontent.com/8285427/60274260-5d1e0480-98bd-11e9-8a48-a6ed9e19cf63.png">

Does anyone see anything that I'm missing?  Any help would be greatly appreciated.

Thank you.

**Comment by mikehardy** [comment]
@mycoberago if the versions you indicate are accurate, then you are on an incompatible version of the stack at that pod version - https://rnfirebase.io/docs/v5.x.x/getting-started#Supported-versions---React-Native-/-Firebase

**Comment by mycoberago** [comment]
> @mycoberago if the versions you indicate are accurate, then you are on an incompatible version of the stack at that pod version - https://rnfirebase.io/docs/v5.x.x/getting-started#Supported-versions---React-Native-/-Firebase

@mikehardy  Thank you for your quick reply.  I apologize, I mistakenly put 5.9.0 for the Firebase iOS SDK.  I'm actually using 5.20.2.

Do you see additional issues with my setup and/or provide other debugging approaches?

I appreciate your time.  Thanks, again.

**Comment by mikehardy** [comment]
@mycoberago I dunno - I’ve never tried with static linking on the underlying SDKs, there are just so many and Pods seems to work for me for the SDK dependencies. Seeing that it finds some of the interfaces but not all, that feels like a local-state-mismatch thing vs a total-project-failure thing. Have you tried nuking all local state to see if that gets you moving?  What I mean specifically https://github.com/invertase/react-native-firebase/issues/2269#issuecomment-506135988
