### ISSUE TITLE
Realtime Database Offline writing unsuccessful

### ISSUE THREAD

**Issue by xyzzyxyzzy0077** [invertase/react-native-firebase#1567]
This is regarding platform iOS, React Native 0.57.1 and React Native Firebase 5.0.0.
Realtime Database offline persistence enabled (at least I think so, as reading and even deleting offline are not a problem).

This is what I tried as a testing:

```javascript
someTest = () => {
    // firebase.database().goOffline()
    firebase.database().ref('test').set({
      [Date.now()]: true
    }, result => {
      console.log(result)
    })
  }
```
When the device is offline, or the `goOffline()` method is uncommented, the result is never returned. 
Also tried out the Promise version, didn't work either.

Any help?

----

Additionally, I tried this out elsewhere and find that actually the writing is done locally, which means I can see the edited one after restarting the app. Just that the function (set/update) not returning anything prevent me from wrapping up the chained promise.

**Comment by minusoneman** [comment]
I'm pretty sure the callback will not resolve if the device is offline (per design?).

If you want to create a new document while offline, one approach is to first create a key and then update at that location. Ex.

```javascript
const ref = firebase.database().ref('test');
ref.push().key; // <-- The key is created locally
const updates = {};
updates[Date.now().valueOf()] = true;
ref.update(updates); // <-- Don't wait for the update call to resolve
```

**Comment by Ehesp** [comment]
Checked this one out, it indeed only fires once set on the servers (as per design and Firebase documentation). Thanks for the comment @minusoneman!
