### ISSUE TITLE
Logical AND Where conditions combined with onSnapshot real time listener does not pick up updates to collection or docs in collection.

### ISSUE THREAD

**Issue by markmoul10** [invertase/react-native-firebase#1573]
### Issue
        const appointmentListener = firebase.firestore().collection('appointments')
        .where('date', '==', date.dateString)
        .where('clientId', '==', id)
        .orderBy('startTime')
        .onSnapshot(snapshot => {
            console.log(snapshot);
            dispatch({ type: FETCH_APPOINTMENTS, payload: { date, appointments: snapshot.docs, appointmentListener } });
        });

The code above will fetch the data when initially called. But the real time listener will not pick up changes (deletes, add's, updates) to the "appointments" collection. If I remove the "where" conditions it will pick up the changes. The "where" conditions seem to disable the onSnapshot real time listener which defeats the purpose of both the filters and onSnapshot.

### Environment

1. Application Target Platform:
IOS

2. Development Operating System:
MAC OS Sierra

3. Build Tools:
XCode

4. `React Native` version:
0.56.0

5. `React Native Firebase` Version:
4.3.7

6. `Firebase` Module:
Firestore

7. Are you using `typescript`?
no

---

**Comment by Salakar** [comment]
This is a known issue with dates, will be fixed soon, see current issues relating to this:

https://github.com/invertase/react-native-firebase/issues/1437
https://github.com/invertase/react-native-firebase/issues/1439

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
