### ISSUE TITLE
[Android] Open notification from tray re-laucnh app

### ISSUE THREAD

**Issue by ReactDeveloperOneQSoft** [invertase/react-native-firebase#1574]
When I open a notification from tray, app always re-launchs even app is in foreground.

My manifest.xml:
 <activity
            android:name=".MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:exported="true"
            android:label="@string/app_name"
            android:launchMode="singleTop"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize">
        </activity>
        <activity
            android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" />
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
        <provider
          android:name="android.support.v4.content.FileProvider"
          android:authorities="${applicationId}.fileprovider"
          android:grantUriPermissions="true"
          android:exported="false">
            <meta-data
              android:name="android.support.FILE_PROVIDER_PATHS"
              android:resource="@xml/file_paths" />
        </provider>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />

### Environment

1. Application Target Platform:
Android
2. Development Operating System:
macOS Sierra

3. Build Tools and dependencies:
buildToolsVersion = "27.0.3"
minSdkVersion = 16
compileSdkVersion = 27
targetSdkVersion = 27
supportLibVersion = "27.1.1"
googlePlayServicesVersion = "15.0.1"
androidMapsUtilsVersion = "0.5+"

dependencies {
    implementation project(':react-native-file-opener')
    implementation project(':react-native-fs')
    implementation (project(':react-native-firebase')) {
          transitive = false
    }
    implementation (project(':react-native-device-info')){
        exclude group: 'com.google.android.gms'
    }
    implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation project(':react-native-i18n')
    implementation project(':react-native-android-location-services-dialog-box')
    implementation project(':react-native-splash-screen')
    implementation project(':react-native-fbsdk')
    implementation (project(':react-native-camera')){
        exclude group: 'com.google.android.gms'
    }
    implementation project(':react-native-fast-image')
    implementation fileTree(dir: "libs", include: ["*.jar"])

    // For animated GIF support
    // Firebase dependencies
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.5@aar') {
        transitive = true
    }
    implementation "com.google.firebase:firebase-messaging:17.3.2"
    implementation 'me.leolin:ShortcutBadger:1.1.21@aar'
    implementation "com.google.firebase:firebase-core:16.0.1"
    implementation "com.google.android.gms:play-services-base:${rootProject.ext.googlePlayServicesVersion}"
    implementation "com.google.android.gms:play-services-auth:${rootProject.ext.googlePlayServicesVersion}"
    implementation "com.google.android.gms:play-services-maps:${rootProject.ext.googlePlayServicesVersion}"
    implementation 'com.facebook.android:facebook-android-sdk:4.34.0'
    implementation 'com.facebook.fresco:animated-gif:1.9.0'
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
}
4. `React Native` version:
0.56
5. `React Native Firebase` Version:
5.0.0
6. `Firebase` Module:
messaging
notification
7. Are you using `typescript`?
no
---

Please help me. Thank you

**Comment by awdhootlele** [comment]
Try https://github.com/NativeScript/push-plugin/issues/177

**Comment by ReactDeveloperOneQSoft** [comment]
> Try [NativeScript/push-plugin#177](https://github.com/NativeScript/push-plugin/issues/177)

I have added singleTop to MainActivity, but issue still persists.

**Comment by awdhootlele** [comment]
> > Try [NativeScript/push-plugin#177](https://github.com/NativeScript/push-plugin/issues/177)
> 
> I have added singleTop to MainActivity, but issue still persists.

If you have Splash Screen into your app, you need to set  android:launchMode="singleTop" into your Main activity AND your splash activity.
You can also try setting  android:launchMode="singleTask" instead of singleTop.

**Comment by ReactDeveloperOneQSoft** [comment]
Thanks @awdhootlele . 
Its solved by adding singTop to SplashActivity also.

**Comment by prasad-dumbre-10** [comment]
@ReactDeveloperOneQSoft 
@awdhootlele 
hii guys will you please share your manifest file , i think i have messed with my manifest file 
whenever i use intent filter in main activity evryting works fine , but i wanted to use splash acitivity
and when i put intent filter from Main activity to Splash activity firebase.notifications().onNotificationOpened dosent invokes
i am a noob please help me out here
Thankyou
my manifest file


     <activity
        android:launchMode="singleTop"
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">

      </activity>

        <activity
            android:launchMode="singleTop"
            android:name=".SplashActivity"
            android:theme="@style/SplashTheme"
            android:label="@string/app_name"
            >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
