### ISSUE TITLE
Unable to receive notifications on iOS 12

### ISSUE THREAD

**Issue by mohdabbas** [invertase/react-native-firebase#1577]
FCM is working fine on iOS 11 and Android as well, but after upgrading to iOS 12, notification are not coming to iPhones with iOS 12. Any idea?

Versions:
React Native: 0.53.0
React Native Firebase: 4.2.0

**Comment by ducpt2** [comment]
i able to test push notification using firebase console, but when i am using API: https://fcm.googleapis.com/fcm/send
I am not able to send notification to device.
Do you have same issue?

**Comment by mohdabbas** [comment]
No I am not using the API... just the console!

**Comment by mohdabbas** [comment]
Strange, after upgrading to v4.3.8, I am able to receive on ios12, but not on older iOS and Android devices :-D!

**Comment by ducpt2** [comment]
@mohdabbas  it work fine for me now. 
Versions:
React Native: 0.55.4
React Native Firebase: 4.3.8

**Comment by ducpt2** [comment]
@mohdabbas right now i am not able to receive notification, don't know why it happend :))

**Comment by rheng001** [comment]
@ducpt2 I'm having the same problem. Did you manage to figure it out?

**Comment by wardhanster** [comment]
Hey everyone, 
I was able to solve this from moving away from the older deprecated Server side API call to the latest one.
https://firebase.google.com/docs/cloud-messaging/migrate-v1
& 
https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message
Basically my new API endpoint looks like this 
Project-name which appears in the console area (something like this projectname-12334)
>https://fcm.googleapis.com/v1/projects/{project-name}/messages:send

**Comment by Aung-Myint-Thein** [comment]
@ducpt2 have you solved the issue? What was the API response when you try to trigger from fcm api? I am using nodejs firebase-admin library and I get `{"code":"messaging/internal-error","message":"Internal error encountered."}`. Appreciate if you have solved the issue and share the solution or suggestion :) Thanks!

**Comment by vicky462** [comment]
+1

**Comment by vicky462** [comment]
Any update in this ??

**Comment by Aung-Myint-Thein** [comment]
I have managed to get this working. I tried to send notification from gcm API directly and I received a more meaningful error saying "ApnsInvalidCredentials". Then I tried to reset the APNS configurations and they are working now. :) Let me know if anyone needs helps.
