### ISSUE TITLE
Phone Auth wrong SMS template.

### ISSUE THREAD

**Issue by itanhduy** [invertase/react-native-firebase#1579]
### Issue

I'm trying to change SMS Template but it doesn't work. I got `Your Firebase App verification code is xxxxx` instead of `%LOGIN_CODE% is your verification code for %APP_NAME%.`. Any help would be greatly appreciated

When I'm getting verification code from Firebase:
![image](https://user-images.githubusercontent.com/10527554/46659275-cef2d880-cbde-11e8-9c33-7b8819adc0e0.png)

The expected template:
![image](https://user-images.githubusercontent.com/10527554/46659296-e336d580-cbde-11e8-828f-c818efda93a3.png)

```
import firebase from 'react-native-firebase'

const { auth, storage } = firebase

const AuthCore = auth()
const StorageCore = storage()

export { AuthCore, StorageCore }
```

```
  getCode = stopLoading => {
    const { openVerificationCodeDialog } = this.props
    AuthCore.signInWithPhoneNumber(this.phone.getPhoneValue())
      .then(
        confirmResult => {
          openVerificationCodeDialog(confirmResult)
        },
        error => {
          DefaultEmit.showErrorSnackBarWithCustomMessage(error.message)
        }
      )
      .then(() => stopLoading())
  }
```

### Environment

1. Application Target Platform:

iOS

2. Development Operating System:

macOS Sierra 10.13.6 (17G65)

3. Build Tools:

Xcode Version 10.0 (10A255)

4. `React Native` version:

react-native-cli: 2.0.1
react-native: 0.56.1

5. `React Native Firebase` Version:

^5.0.0-rc1

6. `Firebase` Module:

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'

7. Are you using `typescript`?

No

**Comment by samitha9125** [comment]
You better contact firebase support service and request their assistance. I faced a similar problem where I also received a SMS which contains unknown app name whenever I use an android phone to request the OTP. Finally found out that my package name is registered under someone else's app which has been published in Google Play Store and firebase pull that person's app name for auth message.

**Comment by itanhduy** [comment]
Hi @JalAsentista. I dunno who you are but thumb-down my post without any reason just makes you to be ridiculous.

Hi @samitha9125. Thanks for your information. I checked with firebase support service. They said the correct message will be appear when I publish my app to Apple Store/ Play Store

**Comment by tunvy** [comment]
> Hi @JalAsentista. I dunno who you are but thumb-down my post without any reason just makes you to be ridiculous.
> 
> Hi @samitha9125. Thanks for your information. I checked with firebase support service. They said the correct message will be appear when I publish my app to Apple Store/ Play Store

My application is a website so how can I get the correct notification?

**Comment by hnhai** [comment]
@tunvy Fix được chưa ông ?

**Comment by h3d-thanhlx** [comment]
@tunvy : did you fix this problem on your website?

**Comment by tunvy** [comment]
không fix được vì google giới hạn quốc gia Việt Nam sẽ mặc định là như vậy,
không tùy biến đc nhé


Vào Th 6, 6 thg 12, 2019 vào lúc 09:25 LeThanh <notifications@github.com>
đã viết:

**Comment by tunvy** [comment]
không fix được vì google giới hạn quốc gia Việt Nam sẽ mặc định là như vậy,
không tùy biến đc nhé

Vào Th 3, 29 thg 10, 2019 vào lúc 15:11 Hoàng Ngọc Hải <
notifications@github.com> đã viết:

**Comment by xuananpham93** [comment]
@andyngdz , Did you fix this problem?

**Comment by hnhai** [comment]
> @andyngdz , Did you fix this problem?

Việt Nam bị hạn chế nên k sửa được đâu bạn

**Comment by xuananpham93** [comment]
Cám ơn bạn nhé

**Comment by ckpvthuong** [comment]
làm em ngỗi nghĩ cả buổi ko biết mình làm sai chỗ nào.

**Comment by ckpvthuong** [comment]
> > @andyngdz , Did you fix this problem?
> 
> Việt Nam bị hạn chế nên k sửa được đâu bạn

làm em ngồi nghĩ cả buổi ko biết mình làm sai chỗ nào

**Comment by andyngdz** [comment]
Mình cảm ơn mọi người 🙇

**Comment by ckpvthuong** [comment]
> Mình cảm ơn mọi người

thớt ơi bạn test template tiếng việt cho app chưa nhỉ ?

**Comment by hungfhp** [comment]
Đến giờ đã chạy được chưa mọi người?

**Comment by mahmoud7796** [comment]
any updates

**Comment by bill-pairaktaridis** [comment]
We're getting the same issue but I think it's due to the app not being published. Make sure you've set your public facing name in the settings, also.

https://community.kodular.io/t/the-firebase-sms-otp-template-is-incorrect/63477/5
