### ISSUE TITLE
Connection status for initialized app from js part

### ISSUE THREAD

**Issue by barbarosh** [invertase/react-native-firebase#1582]
### Issue

Strange behavior, I have two initialized app in my project: one default, second from js part, and second app after 1 min activity second app lost connection, and I can`t restore connection by function goOnline() only when I go to screen with many listeners from second app it connection is restored,
have  any suggestion ?

### Environment

1. Application Target Platform: Android

2. Development Operating System:

3. Build Tools:

4. `React Native` version: 0.57.1

5. `React Native Firebase` Version: 4.3.8

6. `Firebase` Module: database

7. Are you using `typescript`? no

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by barbarosh** [comment]
It happens only if you do not have listeners for non-default app

**Comment by barbarosh** [comment]
@Salakar

**Comment by Salakar** [comment]
@barbarosh can you try update to the latest version of the firebase database android SDK, 16.0.3, iirc there was a connection/initialization bug mentioned as fixed on their release notes

**Comment by barbarosh** [comment]
@Salakar I will try, thanks !

**Comment by Salakar** [comment]
See the starter app if you get stuck with versions, it's up to date and on v5 also
