### ISSUE TITLE
OnNotification not being called on release mode [iOS] 

### ISSUE THREAD

**Issue by hisothreed** [invertase/react-native-firebase#1583]
### Issue

onNotification event is being called on debug mode, but when running on release it’s not being called, only getInitialNotification is working on release mode

### Environment
1. Application Target Platform: iOS

2. Development Operating System: macOS

3. Build Tools: xcode

4. React Native version: 0.55.4

5. RNFirebase Version: latest

6. Firebase Module: Notifications/ messaging

**Comment by RyszardRzepa** [comment]
Same issue. Notification listener `OnNotification`  works in development. When I build release app on IOS I will get only once notification in Foreground. If I set the app in the background and go back to the foreground, I will not get `foreground` notification any more. But background notification works.

**Comment by FadiAboMsalam** [comment]
I have the same issue in android 
onNotification being triggered on emulatore but once i do a build -relaese mode it never triggered on real device !

**Comment by alexey-chernikov** [comment]
Same situation on IOS - in development notifications works, in production doesn't

**Comment by alikianinejad** [comment]
same problem. any solution ?

**Comment by alikianinejad** [comment]
> Same issue. Notification listener `OnNotification` works in development. When I build release app on IOS I will get only once notification in Foreground. If I set the app in the background and go back to the foreground, I will not get `foreground` notification any more. But background notification works.
@RyszardRzepa 
I have same issue as you. did you find any solution?

**Comment by alikianinejad** [comment]
same issue 
@alexey-chernikov @FadiAboMsalam @RyszardRzepa did you find any solution ?
