### ISSUE TITLE
app:processReleaseGoogleServices failed

### ISSUE THREAD

**Issue by Balasnest** [invertase/react-native-firebase#1584]
Getting this error while doing release build. 
ENV:
react-native: 0.56
Android API Level: 27

**Task :app:processReleaseGoogleServices
Parsing json file: /.../android/app/src/dev/google-services.json**

FAILURE: Build failed with an exception.

```
* What went wrong:
Could not list contents of '/.../node_modules/metro/node_modules/.bin/babylon'. Couldn't follow symbolic link.
```

**Comment by Salakar** [comment]
Unfortunately this is not an issue with this library specifically. Please ask for help in the support chats if you're stuck, such us the Reactiflux discord server or our discord server.

Alternatively, I'd recommend using our starter project to get going:

- [invertase/react-native-firebase-starter](https://github.com/invertase/react-native-firebase-starter)

Or you can check out the following starter by Ueno:

- [ueno-llc/react-native-starter](https://github.com/ueno-llc/react-native-starter)
