### ISSUE TITLE
Crashlytics force crash error

### ISSUE THREAD

**Issue by ziyafenn** [invertase/react-native-firebase#1586]
### Issue

On Android, when forcing a crash with `firebase.crashlytics().crash();`, app throws an error as shown here:

![screenshot_20181010-204503](https://user-images.githubusercontent.com/314302/46759021-98948680-ccce-11e8-89e3-752298629fcf.png)

I use my own device connected via USB.

### Environment

1. Application Target Platform:

Android

2. Development Operating System:

macOS Mojave

3. Build Tools:

Android Studio 

4. `React Native` version:

0.55.6

5. `React Native Firebase` Version:

4.3.8

6. `Firebase` Module:

Crashlytics

7. Are you using `typescript`?

no

**Comment by Salakar** [comment]
This is as intended - crash() causes a crash.

**Comment by andrewhartwig** [comment]
I'm getting this as well, it doesn't seem to actually be crashing my app, where as on iOS the app actually crashes and reports an error to the firebase console. (None here for android).

**Comment by matthewng** [comment]
Same. I would expect calling this function would show a fatal crash on the firebase dashboard with a stacktrace.

**Comment by afilp** [comment]
How can we cause a crash due to "react native"? To see if this also works?

```
crashlytics {
  enableNdk true
}
```
