### ISSUE TITLE
Does Storage use user authentication?

### ISSUE THREAD

**Issue by booboothefool** [invertase/react-native-firebase#1587]
My app is currently using:
Firebase - for user authentication
AWS S3 - for storing images

I am building a way to upload photos to a user's photo album.

I was looking at the AWS Amplify library for fun: https://github.com/aws-amplify/amplify-js and noticed their storage S3 requires the user to be authenticated, then uploads images for that authenticated user.

Because of this, and with how my users are managed by Firebase, I was considering moving my image storage to Firebase as well if it can help authenticate the upload. Does Firebase make it easier to manage an authenticated user's photo album or should I just stick with S3?

**Comment by Ehesp** [comment]
The answer is yes, if you have it setup.

Take a look at this url: https://firebase.google.com/docs/storage/security/start

You can allow read/write from a path based on the user ID if you wish:

```
// Grants a user access to a node matching their user ID
service firebase.storage {
  match /b/{bucket}/o {
    // Files look like: "user/<UID>/path/to/file.txt"
    match /user/{userId}/{allPaths=**} {
      allow read, write: if request.auth.uid == userId;
    }
  }
}
```
