### ISSUE TITLE
[Android] receive message if app is killed

### ISSUE THREAD

**Issue by dgruseck** [invertase/react-native-firebase#159]
"react": "16.0.0-alpha.6",
"react-native": "^0.44.0",
"react-native-firebase": "^1.1.0",

I want to receive a message in getInitialNotification or onMessage when the app is killed.
If the app is in background or foreground it's working fine, but if the app is killed with the task manager my log says:
` MessagingService: Remote message received`
so the MessagingService is receiving the message but the react native listeners don't.

The message looks like:
```
data: {
  foo: 'bar',
}
```
Without any `notification` block, because I want to create my own local notification on some conditions.
Is it possible to receive messages if the app is killed?

Thanks,
David

**Comment by chrisbianca** [comment]
@dgruseck As you've found, `data` only messages are only received by the app if it's running either in the foreground or the background.  

If the app is killed, the only way to trigger the app to know about the message straight away is if there is a `notification` part to the message which prompts the Android OS to display a notification.  Only when the user clicks on the notification would the app be made aware of the message.

I don't think there's any other way of working around it, but take a look at the Firebase messaging documentation (https://stackoverflow.com/a/38295508/5909648).  If there is, then you'll be able to find it there - and please do let us know if you do!!

In the meantime, I'm going to close this issue as it's an FCM restriction, not anything we can work around with react-native-firebase.

**Comment by jsdario** [comment]
Hi there,

It is definitely possible on Android devices, and it's an OS level decision. iOS does not allow this kind of operation. Also important to remark that it works only with _silent push notifications_.

I used to have this with `react-native-push-notification` and I wonder if someone has achieved the same with this library.

Some references:
https://github.com/evollu/react-native-fcm/issues/507
https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md#3-silent-remote-push-notifications

**Comment by iadcg** [comment]
hey @jsdari. Were u able to make it work using this lib? Can you share your findings like you have handled it in the Android or iOS part?
