### ISSUE TITLE
putFile(filePath) hangs when upload to unreadable path on the bucket.

### ISSUE THREAD

**Issue by peat-psuwit** [invertase/react-native-firebase#1591]
### Issue

`storage().ref(path).putFile(filePath)`'s Promise will not be resolved if `path` points to a non-readable (but writable) path on the bucket.

#### Reproduction procedure
1. Deploy the following rule to Firebase storage:
```
match /test.txt {
  allow write: if true;
  allow read:  if false;
}
```
2. Clone https://github.com/peat-psuwit/react-native-firebase-putfile-hangs-demo, then provide your `google-services.json`. (The application ID is `xyz.peat_network.android.rnfirebaseputfileurldemo`). Build & run the app on Android.
3. In the app, press 'Create test file' first, then press 'Upload test file'.
  - __Expected bahavior__: both buttons eventually stops the activity indicator, indicating that the operation ends (either success or fail, see the code).
  - __Actual behavior__: after pressing 'Upload test file', the activity indicator hangs definitely. This indicates that `storage().ref(path).putFile(filePath)` hangs. (Again, see the code). However, if you check your bucket you'll see that the file uploads successfully (the file name is `test.txt`).

### Additional information

If you see at [this line](https://github.com/invertase/react-native-firebase/blob/af4b2f86812532646b50d39c6cf2105a91fbca43/android/src/main/java/io/invertase/firebase/storage/RNFirebaseStorage.java#L567), you'll notice that the code that `getDownloadUrl()` in `getUploadTaskAsMap(taskSnapshot, listener)` doesn't account for failure case. As the storage rule doesn't allow reading at this point, it fails at this point and no-one notice.

I'm not sure what the behavior should be in this case. It could be 1 of the following:
1. Still consider the invocation a success, providing `downloadURL` as `null`.
2. Consider the invocation a failure, and properly calling `listener`'s failure method.

I personally believe that 1st behavior is OK, since official JS SDK [stops providing `downloadURL` starting from 5.0.0](https://firebase.google.com/support/release-notes/js#5.0.0). However, you may want to consider stop providing `downloadURL` completely, to behave like official SDK.

### Environment

1. Application Target Platform: Android
2. Development Operating System: Ubuntu 18.04.1 LTS (Bionic Beaver)
3. Build Tools: Android Studio 3.2
4. `React Native` version: 0.57.2
5. `React Native Firebase` Version: 5.0.0
6. `Firebase` Module: Only storage.
7. Are you using `typescript`?: No (But I use flow).

```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
      Memory: 451.12 MB / 3.77 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/bin/node
      Yarn: 1.10.1 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
    SDKs:
      Android SDK:
        Build Tools: 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3
        API Levels: 23, 25, 26, 27, 28
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.2 => 0.57.2 
```

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
Thanks again. PR merged.
