### ISSUE TITLE
Conflicting parameter types warning

### ISSUE THREAD

**Issue by levani** [invertase/react-native-firebase#1592]
### Issue

I'm trying to add dynamic links support to ios app. In AppDelegate.m when I add

```
- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray *))restorationHandler {
  return [[RNFirebaseLinks instance] application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
}
```

I'm getting this warning:

> Conflicting parameter types in implementation of 'application:continueUserActivity:restorationHandler:': 'void (^ _Nonnull __strong)(NSArray<id<UIUserActivityRestoring>> * _Nullable __strong)' vs 'void (^__strong _Nonnull)(NSArray *__strong)'

Should I ignore this or is this a bug?

### Environment

1. Application Target Platform:

iOS

2. Development Operating System:

macOS 10.14

3. Build Tools:

xcode 10, iOS 12

4. `React Native` version:

0.57

5. `React Native Firebase` Version:

5.0.0

6. `Firebase` Module:

Dynamic Links (5.9.0)

7. Are you using `typescript`?

no

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by appli-intramuros** [comment]
@levani same problem. Did you find any solution ?

**Comment by levani** [comment]
Yes but can't really remember what was it. sorry.

**Comment by maxbeech** [comment]
@appli-intramuros did you find a solution to this please?

**Comment by sushilbansal** [comment]
@maxbeech https://github.com/facebook/react-native/issues/22716

**Comment by Base29** [comment]
Did anyone found a solution for this ?

**Comment by jkongie** [comment]
I got this to work by using

```
- (BOOL)application:(UIApplication *)application
            continueUserActivity:(nonnull NSUserActivity *)userActivity
            restorationHandler: (nonnull void (^)(NSArray<id<UIUserActivityRestoring>> *_Nullable))restorationHandler {
  return [[RNFirebaseLinks instance] application:application
                                     continueUserActivity:userActivity
                                     restorationHandler:restorationHandler];
}
```
