### ISSUE TITLE
firebase cloud messaging works on iOS simulator but doesn't works on real device

### ISSUE THREAD

**Issue by heeroduo** [invertase/react-native-firebase#1596]
### Issue

It's my code. As you can see that it's simple code for test cloud message. 
When the device receive any message, it will show a simple alert box.
And it worked well in iOS simulator. the simulator as iPhone 8 plus, iOS 11.4 ver.
When I send some message in Firebase console, it shows the alert box immediately.
And my real test device is also iPhone 8 plus and the iOS version is also 11.4 
But when I send same message, this real device doesn't show the alert box.
And also it doesn't trigger onMessage.

It has same codes and same setting. I checked about notification setting in the device.
But it's allowed notifications. And also checked about permission and token. The device
got permission and token correctly without any problems and I can read the token.

'FCM does not work on the iOS simulator, you must test them using a real device. 
This is a restriction enforced by Apple.' I read it in official document but actually it works... 
I don't know why it actually works in simulator but not a real device. If it didn't work on
simulator, I tried to find some other problems but it works on simulator. So maybe there
is some other kind of problem I think.

componentDidMount() {
    firebase.messaging().hasPermission()
    .then(enabled => {
      if (enabled) {
        this.setState({testState: 'enabled'});
      } else {
        firebase.messaging().requestPermission()
        .then(() => {
          this.setState({testState: 'requested'});
        })
        .catch(error => {
          this.setState({testState: 'error'});
        });
      }
    });
    this.messageListener = firebase.messaging().onMessage((message: RemoteMessage) => {
        Alert.alert('test', 'message');
    });
  }

  componentWillUnmount() {
    this.onTokenRefreshListener();
    this.messageListener();
  }

### Environment

1. Application Target Platform: 

iOS (11.4 version)

2. Development Operating System:

macOC

3. Build Tools:

Xcode

4. `React Native` version:

0.56.0

5. `React Native Firebase` Version:

5.0.0

6. `Firebase` Module:

messaging(5.9 ver)

7. Are you using `typescript`?

no

8. Test device

iPhone 8 plus

**Comment by tarr11** [comment]
Take a look at https://github.com/invertase/react-native-firebase/issues/1374
