### ISSUE TITLE
onMessage not called on iOS when app is killed by user

### ISSUE THREAD

**Issue by mattSydney** [invertase/react-native-firebase#1598]
### Issue

I am trying to send a data message to the device. When the app is in the foreground/background this works as expected. But if the user has killed the app, when the app is next started none of the previous messages have arrived. I expected that the app would just get the messages waiting when it restarted. Push notifications are working as expected but I need a away of notifying my app of any messages (for example the user may receive a push but not tap on it and open the app manually, so no data would be sent to app in that case)

### Environment

1. Application Target Platform:

iOS (12.0 version)

2. Development Operating System:

Mac os High Sierra
3. Build Tools:

Xcode 10

4. `React Native` version:
0.56

5. `React Native Firebase` Version:

iOS (12.0 version)

6. `Firebase` Module:

messaging

7. Are you using `typescript`?

yes

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by gglee89** [comment]
@mattSydney I am also experiencing the same thing.

There's also another similar thread that mentions the same issue: [#1542](https://github.com/invertase/react-native-firebase/issues/1542)

Whenever I close my app on iOS I stop receiving notifications. 
But if my app is either in the Foreground or Background then is okay.

**Comment by stonecold123** [comment]
I can't get the notification to display when the app is in the background.
I'm using IPhone XR to test.
