### ISSUE TITLE
background Messaging doesnt work

### ISSUE THREAD

**Issue by guitar9** [invertase/react-native-firebase#1599]
### Issue

I did the steps descriped here: https://rnfirebase.io/docs/v5.x.x/notifications/receiving-notifications

Background Messaging does not fire an event when i send a message from Firebase console.
I tried to show a toast but nothing happend.
### Environment

1. Application Target Platform:

Android

2. Development Operating System:

Linux

4. `React Native` version:

0.57.1

5. `React Native Firebase` Version:

5.0.0

6. `Firebase` Module:

messaging

7. Are you using `typescript`?

no
---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
You need to follow all the setup guides below:

- https://rnfirebase.io/docs/v5.x.x/messaging/android
  - (including the `(Optional) Background-Messages step`)
- https://rnfirebase.io/docs/v5.x.x/notifications/android
