### ISSUE TITLE
iOS notification with sound not showing while app is in foreground

### ISSUE THREAD

**Issue by SeriousChoice** [invertase/react-native-firebase#1600]
### Issue

I was confused by the error *"Failed to display notificaton"* followed by *"connection to service named com.apple.usernotifications.usernotificationservice"* when I received a notification sent from our web service so I tried with firebase console. 
I found out that with `"sound":"default"` the notification is not showing while the app is in foreground, only background or closed, with the previous error.
Any clues?

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS Mojave

3. Build Tools: Xcode 10, iOS 12

4. `React Native` version: 0.56.0

5. `React Native Firebase` Version: 4.3.8

6. `Firebase` Module: Messaging

7. Are you using `typescript`? No

**Comment by ajchili** [comment]
By default, iOS does not show a notification while the app is in the foreground afaik. This is also supported by [this](https://stackoverflow.com/questions/14872088/get-push-notification-while-app-in-foreground-ios#comment59799952_14872088).

To handle this, look [here](https://stackoverflow.com/a/40756206). They have an example in Swift but I think it would be easy to convert it to Obj-C. If you have any issues let me know and I'll try to get a test project running.

**Comment by sibigit** [comment]
i have the same issue in react native how to handle it i can get a console log while app is opened but not showing notification

**Comment by ajchili** [comment]
@sibigit You would have to handle notifications via the AppDelegate. I am not sure of the Obj-C method but here is the swift one.
```Swift
func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void)
```
It should be a similiar decleration for Obj-C.

**Comment by sibigit** [comment]
thanks @ajchili i was added those lines in my code,but i have fixed it by following the link https://rnfirebase.io/docs/v5.x.x/notifications/displaying-notifications. if still any one have issue i will share my code too

**Comment by StijnCoolen** [comment]
@sibigit how did you fix this? When I try to display the notification using `firebase.notitifcations().displayNotification(notification)` when the app is in the foreground on iOS I get the following error: `Error: Failed to display notification`

**Comment by veeramani-arthanari** [comment]
@StijnCoolen , I'm using **react-native-firebase** version 5.6.0. I've fixed this by adding the below condition. Open file `RNFirebaseNotifications.m` and go to the method 

`- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler NS_AVAILABLE_IOS(10_0)`


You'll see the below condition

`if (RCTSharedApplication().applicationState == UIApplicationStateBackground
            || RCTSharedApplication().applicationState == UIApplicationStateInactive)`

add one more condition to this

`if (RCTSharedApplication().applicationState == UIApplicationStateBackground
            || RCTSharedApplication().applicationState == UIApplicationStateInactive`
            **|| RCTSharedApplication().applicationState == UIApplicationStateActive) {**

Now I'm able to see the banner and get the sound.

**Comment by khaledBou** [comment]
I added this code but i can't show notifications in foreground,

what i should edit ? 

```
// Receive displayed notifications for iOS 10 devices.
// Handle incoming notification messages while app is in the foreground.
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {
  NSDictionary *userInfo = notification.request.content.userInfo;

  // With swizzling disabled you must let Messaging know about the message, for Analytics
  [[FIRMessaging messaging] appDidReceiveMessage:userInfo];

  // Print message ID.
  if (userInfo[kGCMMessageIDKey]) {
    NSLog(@"Message ID: %@", userInfo[kGCMMessageIDKey]);
  }

  // Print full message.
  NSLog(@"%@", userInfo);

  // Change this to your preferred presentation option
  completionHandler(UNNotificationPresentationOptionBadge | UNNotificationPresentationOptionAlert);
}
```

**Comment by KrishanMadushanka** [comment]
![Screenshot 2024-01-04 at 9 01 07 PM](https://github.com/invertase/react-native-firebase/assets/13725918/abbde2a1-9f1e-4238-b2ee-f60dc1ac9942)
