### ISSUE TITLE
App still able to receive notification after closed, but no sound playing and no vibration

### ISSUE THREAD

**Issue by fuj1w4r4** [invertase/react-native-firebase#1613]
Basically I am facing 2 issues here:

1. App still able to receive notification after closed, but no sound playing and no vibration.
2. App able to receive notification in foreground, sound played, but vibration apparently is not working at all.

      notification = new firebase.notifications.Notification()
      .android.setPriority(firebase.notifications.Android.Priority.High)
      .android.setVibrate(1000)

I have followed the documentation. Everything works fine except issues describe above. Any advice? Please help.

### Environment

1. Application Target Platform:

android

2. Development Operating System:

Windows 7

3. Build Tools:

Visual Code studio

4. `React Native` version:

0.55, 0.57

5. `React Native Firebase` Version:

5.0.0

6. `Firebase` Module:

notifications

7. Are you using `typescript`?

no

**Comment by LaVielle** [comment]
I have the same issue.
When the app is opened, I set the sound with `notification.setSound('default')`
But when the app is in the background or closed, no sound...

**Comment by LaVielle** [comment]
Ok, so I figured it out for my setup:

I am using a cloud function to the send the notifications. After adding the `sound` key to the notification payload, there was a sound and vibration when app was in background or closed:
`
            let payload = {
              notification: {
                title: newNotification.title,
                body: newNotification.body,
                sound: 'default'
              },
              data: newNotification.data ? newNotification.data : {}
            }

            // send away!
           return admin.messaging().sendToDevice(receiverToken, payload);
`

Then, I also had to specify the default sound in the `onNotification` listener (otherwise notifications would not display or vibrate when app was in foreground):
`notification.setSound('default')`

**Comment by vinaytechindustan** [comment]
Please Help! @Ehesp 
I am facing the same issue, I am able to receive the notification  if app is in Background, Foreground or Closed but no sound is playing neither phone vibrates

**Comment by lorenc-tomasz** [comment]
The same issue on Android - no sound or vibration.

**Comment by eggandmoney** [comment]
i am getting notifications on background but not on closed/swiped. Are there any other steps to do that ?
