### ISSUE TITLE
Unsuccessful debug_token response on signInWithCredential (with a valid access token)

### ISSUE THREAD

**Issue by bsr203** [invertase/react-native-firebase#1621]
Hi.
It is most likely a configuration issue, but any suggestion to how the API works will help me to solve it.

I get `Invalid OAuth access token` with this API
 
```
 const currentUser = await firebase
        .auth()
        .signInWithCredential(credential);
```

when I checked the access token at https://developers.facebook.com/tools/debug/accesstoken

```
Access Token Info
App ID	123...123 : xxx
Type	User
Metadata	{"auth_type":"rerequest"}
App-Scoped User ID
Learn More
123...123 : Abc Abc..
User last installed this app via API N/A
Issued	1539975915 (about an hour ago)
Expires	1545159915 (in about 2 months)
Data Access Expires	1547756393 (in about 3 months)
Valid	True
Origin	Mobile Web Faceweb
Scopes	email, public_profile
```
not sure why `Unsuccessful debug_token response` ? Does `react-native-firebase` makes the debug_token call or it is a configuration error with firebase console.

thank you.
bsr

```
message:"An internal error has occurred. [ Unsuccessful debug_token response from Facebook:{"error":{"message":"Invalid OAuth access token signature.","type":"OAuthException","code":190,"fbtrace_id":"DtuOu174tkf"}} ]"
stack:"Error: An internal error has occurred. [ Unsuccessful debug_token response from Facebook:{"error":{"message":"Invalid OAuth access token signature.","type":"OAuthException","code":190,"fbtrace_id":"DtuOu174tkf"}} ]\n
    at createErrorFromErrorData (/Users/bsr/myapp/.vscode/.react/index.bundle:2450:17)\n 
       at /Users/bsr/myapp/.vscode/.react/index.bundle:2402:27\n 
          at MessageQueue.__invokeCallback (/Users/bsr/myapp/.vscode/.react/index.bundle:2953:18)\n 
             at /Users/bsr/myapp/.vscode/.react/index.bundle:2700:18\n
                 at MessageQueue.__guard (/Users/bsr/myapp/.vscode/.react/index.bundle:2857:13)\n
                 at MessageQueue.invokeCallbackAndReturnFlushedQueue (/Users/bsr/myapp/.vscode/.react/index.bundle:2699:14)\n
                     at /Users/bsr/myapp/.vscode/.react/debuggerWorker.js:131:58\n
                         at process.<anonymous> (/Users/bsr/myapp/.vscode/.react/debuggerWorker.js:40:9)\n
                         at process.emit (events.js:182:13)\n...
__proto_

````
### Environment

1. Application Target Platform:

Android

2. Development Operating System:

macOS Sierra

3. Build Tools:

react-native

4. `React Native` version:

0.57.1

5. `React Native Firebase` Version:

^5.0.0

6. `Firebase` Module:

auth, messaging, notification

7. Are you using `typescript`?

yes
---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
Hey, check out the Facebook Auth example in the docs if you haven't already:

https://rnfirebase.io/docs/v5.x.x/auth/social-auth#Facebook

If you're still having issues come and chat on discord. 

Thanks

**Comment by bsr203** [comment]
I am not sure why, I joined the discord channel at https://discordapp.com/channels/295953187817521152/408595101363732501

it says, I don't have permission to send a message in this channel.

I also sent a DM to you, but no response yet :-)

I was following the example, and was getting the error at 

```
    const credential = firebase.auth.FacebookAuthProvider.credential(data.accessToken);
```

after getting a valid access token. I was mainly asking how can I troubleshoot further, as `debug_token` API call is used to check the token structure, which I saw is valid through FB tool. 

Please let me know how to get write access in the discord channel.
