### ISSUE TITLE
Can we add custom remote notification features with Firebase Cloud Messaging?

### ISSUE THREAD

**Issue by Tejas-narola** [invertase/react-native-firebase#1622]
@Salakar 
Can we add this features with Firebase Cloud Messaging?

For iOS
Custom Remote notification feature,  allow for advanced custom layouts and any specific notifications behavior
Like, Image with Remote notification

Application Target Platform:
macOS Sierra

Development Operating System:
iOS or Android SDK version

Build Tools:
0.55.x

RNFirebase Version:
messaging

Firebase Module:

**Comment by Salakar** [comment]
@Tejas-narola hey, please could you make a feature request here: https://boards.invertase.io/admin/board/react-native-firebase

Once created please paste the link to the request here so others can track it / upvote.

**Comment by onkarjanwa** [comment]
@Tejas-narola Were you able to achieve advanced custom layouts for push notification? I am looking forward to know how to do it.
