### ISSUE TITLE
When trigger click notification on Background Not working (Android)

### ISSUE THREAD

**Issue by auchaphon** [invertase/react-native-firebase#1623]
Please Help (Android)

When trigger click notification on Background Not working
show error message **W/FirebaseMessaging: Error while parsing timestamp in GCM event**

Platform ios it's working

**Comment by Salakar** [comment]
Firstly, please correctly fill out the issue template, without this, we can not help. 

Secondly, please don't duplicate issues, https://github.com/invertase/react-native-firebase/issues/1340.

Locking and closing this issue. 🙈
