### ISSUE TITLE
Error:Could not find aapt2-proto.jar  (com.android.tools.build:aapt2-proto:0.3.1).

### ISSUE THREAD

**Issue by JPsurj1a01** [invertase/react-native-firebase#1627]
`Error:Could not find aapt2-proto.jar (com.android.tools.build:aapt2-proto:0.3.1).
Searched in the following locations:
    https://jcenter.bintray.com/com/android/tools/build/aapt2-proto/0.3.1/aapt2-proto-0.3.1.jar`

" Getting  this error when build the application

**Comment by Salakar** [comment]
Please correctly fill out the issue template, without this, we can not help. 

Locking and closing this issue. Feel free to raise another issue that correctly follows the issue template.
