### ISSUE TITLE
Add Firebase Functions

### ISSUE THREAD

**Issue by Cretezy** [invertase/react-native-firebase#163]
My proposal of how to handle this would be as a wrapper for `fetch` (https://fetch.spec.whatwg.org/), as `firebase.functions()`. This adds the base URL to the `fetch` call, plus with an option such as `auth` which would add the authorization header. The call would need:

* Function: `string`
* Additional path (after the initial root path of the app): `string?`
* Headers: `object?`
* Body: `string?`/`object?` (stringified)
* Auth: `boolean?` (default: `false`)

Example:
Server side:

```javascript
exports.hello = functions.https.onRequest((req, res) => {
    res.send(`Hello ${req.body.name}!`);
});
```

```javascript
firebase.functions().run('hello', null, {name: "foo"})
    .then((response) => response.text())
    .then((response) => {
        console.log(response) // => Hello foo!
    });
```

If there's enough support for this, I could implement it.

**Comment by chrisbianca** [comment]
@Cretezy Interesting idea, and I could certainly see the benefit in being able to do this...  My only caveat is that as far as I'm aware, something similar doesn't exist in the Web SDK?

At the moment our focus is on matching the Web SDK where the equivalent functionality exists in the native iOS and Android, as well as covering the remaining iOS and Android API surface area.

It's something we could look to discuss with Firebase and see whether they have any appetite for offering something similar on the web SDK - assuming of course that I haven't missed something that's already been added there!

**Comment by Cretezy** [comment]
I couldn't find it at all in the Web SDK. If you could find it that'd be great. We could do a PR to the upstream Firebase JS code to add this feature if we implement it well here.

**Comment by Ehesp** [comment]
This is an interesting one. We could have this under a "3rd party modules" section. In v2 we do have the ability to only include the modules the user wants, but as this would be a JS implementation I guess it'd always be available.

Totally throwing this out there, it could be a total no as it starts to go away from the firebase web SDK, but we could do something like:

```
import functions from 'react-native-firebase-functions'; // 3rd party module

firebase.hook(functions, 'functions');
// firebase.functions() is now available
```

On an internal project we are working on, we kinda did something similar. When we got a push notification we sent a "ping" to the server as an upstream message to let the server know how much interaction it got. It was as follows:

```
let server = null;
firebase.server = () => {
  if (server) {
    return server;
  }
  server = new Server(<< server ID >>);
  return server;
};

```

**Comment by Ehesp** [comment]
For now lets close this one down. We can pick it up again in the future if needed, but if you want something custom in your own project then the last code snippet above should suffice. Right now we need to focus on Firebase features and replicating the web SDK.

**Comment by gvillenave** [comment]
I'd be interested in something like this too. Any idea if this could potentially make it to the roadmap soon?

**Comment by Ehesp** [comment]
We still have the same view as before really, we're focusing on Web SDK matching for the foreseeable future.

It'd be super simple to make your own modular code to do this anyway using fetch.

**Comment by gvillenave** [comment]
That's true, I think the only convenience to have that wrapper would be to avoid dealing with the Firebase server URL directly, but that's a minor concern. Thanks for the quick reply!

**Comment by Ehesp** [comment]
https://github.com/invertase/react-native-firebase/issues/935
