### ISSUE TITLE
java.lang.IllegalArgumentException:  attempt to remove OnFrameMetricsAvailableListener that was never added

### ISSUE THREAD

**Issue by sangupandi** [invertase/react-native-firebase#1632]
Problem in firebase performance monitoring package
I am using performance monitoring package version 

> com.google.firebase:firebase-perf 16.1.0

>  classpath 'com.google.gms:google-services:4.0.1'
> classpath 'com.android.tools.build:gradle:3.1.3'

> targetSdkVersion 28
>  buildToolsVersion "28.0.3"

I got the following issue

**java.lang.RuntimeException: Unable to stop activity ,attempt to remove OnFrameMetricsAvailableListener that was never added** .

also I tried downgrading the plugin to  com.google.firebase:firebase-perf  15.2.0 , its not working .
if I disable the performance plugin it working fine. 

#https://stackoverflow.com/questions/50281141/attempt-to-remove-onframemetricsavailablelistener-that-was-never-added

**Comment by Ehesp** [comment]
Please follow the issue template so we can help

**Comment by nomankhan18** [comment]
Hi @Ehesp , I am getting the same issue. If there any solution please post here.

**Comment by sangupandi** [comment]
> Hi @Ehesp , I am getting the same issue. If there any solution please post here.

If you are using the attribute, android:hardwareAccelerated="false" in the manifest. Remove the attribute.
