### ISSUE TITLE
Analytics events should be ignored when running in TestLab (Pre-launch report)

### ISSUE THREAD

**Issue by corradio** [invertase/react-native-firebase#1635]
When submitting to the Google Play Store, analytics events are being sent while the app is being tested in TestLab (as part of the pre-launch reports).
There's a simple way to exclude those events:
https://firebase.google.com/docs/test-lab/android/android-studio#modify_instrumented_test_behavior_for

**Comment by Salakar** [comment]
Hey @corradio this is planned to be added, please follow along over at: https://boards.invertase.io/react-native-firebase/p/detect-firebase-pre-launch-report-in-analytics

Thanks!

**Comment by wodka** [comment]
so just to get this right:

I need to manually add the code:

```js
import analytics, {firebase} from '@react-native-firebase/analytics';

if (firebase.utils().isRunningInTestLab()) {
  analytics().setAnalyticsCollectionEnabled(false)
}
```

**Comment by tobiaseisenschenk** [comment]
The link above is outdated since it points to the old `Utils` package. Now you actually have to do this instead:
```
import firebase from '@react-native-firebase/app';
import '@react-native-firebase/analytics';

if (firebase.app().utils().isRunningInTestLab) {
	firebase.analytics().setAnalyticsCollectionEnabled(false);
}
```
I hope this helps someone until the documentation is ready.

**Comment by mikehardy** [comment]
@tobiaseisenschenk "until the documentation is ready" -> there is an edit button at the top right of each page, and the workflow via github makes it possible to propose documentation edits almost automatically (they handle the fork/branch/PR creation work for you) :muscle:

**Comment by jorgemasta** [comment]
> The link above is outdated since it points to the old `Utils` package. Now you actually have to do this instead:
> 
> ```js
> import firebase from '@react-native-firebase/app';
> import '@react-native-firebase/analytics';
> 
> if (firebase.app().utils().isRunningInTestLab) {
> 	firebase.analytics().setAnalyticsCollectionEnabled(false);
> }
> ```
> 
> I hope this helps someone until the documentation is ready.

Hey men! Where do you place that code? 
I have put it inside a `useEffect` in my root component but doesn't work :(

**Comment by gponsu** [comment]
> > The link above is outdated since it points to the old `Utils` package. Now you actually have to do this instead:
> > ```js
> > import firebase from '@react-native-firebase/app';
> > import '@react-native-firebase/analytics';
> > 
> > if (firebase.app().utils().isRunningInTestLab) {
> > 	firebase.analytics().setAnalyticsCollectionEnabled(false);
> > }
> > ```
> > 
> > 
> > I hope this helps someone until the documentation is ready.
> 
> Hey men! Where do you place that code?
> I have put it inside a `useEffect` in my root component but doesn't work :(

It does not work for me either :(

**Comment by tobiaseisenschenk** [comment]
> > The link above is outdated since it points to the old `Utils` package. Now you actually have to do this instead:
> > ```js
> > import firebase from '@react-native-firebase/app';
> > import '@react-native-firebase/analytics';
> > 
> > if (firebase.app().utils().isRunningInTestLab) {
> > 	firebase.analytics().setAnalyticsCollectionEnabled(false);
> > }
> > ```
> > 
> > 
> > I hope this helps someone until the documentation is ready.
> 
> Hey men! Where do you place that code?
> I have put it inside a `useEffect` in my root component but doesn't work :(

We stopped using Google Analytics alltogether, but we had this setup code in our root component `App.tsx` along with other setup code, but not inside a React hook.

**Comment by rgomezp** [comment]
Hey men, I am facing this issue. I'm surprised there was no resolution or guidance

**Comment by mikehardy** [comment]
Women work on apps built with react-native-firebase as well 🤷‍♀️ 
We offer an ability to test whether you are in the test lab or not, but where use that is project-specific, it's not possible to offer general guidance as you could alter all sorts of behavior in the test lab, not just analytics. And you may want analytics events from the test lab as perhaps the test lab finds problems and the analytics info you custom log could help resolve it...

**Comment by rgomezp** [comment]
> There are women that work on apps built with react-native-firebase and have also contributed to the development of react-native-firebase as well 🤷‍♀️

My apologies, not sure why I said that
