### ISSUE TITLE
[Android] firebase.crashlytics().crash()

### ISSUE THREAD

**Issue by dantn93** [invertase/react-native-firebase#1636]
## Issue

I integrate the crashlytics and test (firebase.crashlytics().crash()) on android emulator, but it raises this bug
"length=2; index=10"
![screen shot 2018-10-25 at 6 55 41 pm](https://user-images.githubusercontent.com/20403819/47498487-9cf0a000-d887-11e8-94cd-0b07642cc539.png)

I found this post https://code.luasoftware.com/tutorials/android/setup-firebase-crashlytics-on-android-for-crash-reporting/#enable-crashlytics-in-firebase-console

It show that correctly, then I open console firebase but I don't see any crashes.
<img width="850" alt="screen shot 2018-10-25 at 10 03 01 pm" src="https://user-images.githubusercontent.com/20403819/47510219-dfbf7180-d8a1-11e8-9f33-4887bd4b0116.png">

This is my craslytics page
<img width="1168" alt="screen shot 2018-10-25 at 10 00 36 pm" src="https://user-images.githubusercontent.com/20403819/47510463-64aa8b00-d8a2-11e8-99db-7166793b4a37.png">

How can I fix it?

---

## Project Files

- Android: `android/build.gradle` contents.
```
buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath 'com.google.gms:google-services:4.0.1'
        classpath 'io.fabric.tools:gradle:1.25.4'
   }
```
 - Android: `android/app/build.gradle` contents.
```
implementation "com.google.firebase:firebase-core:16.0.4"
implementation('com.crashlytics.sdk.android:crashlytics:2.9.5@aar') {
        transitive = true
    }
```
## Environment
- **`React Native` version:**
 React Native 0.55.4
- **`React Native Firebase` library version:**
  "react-native-firebase": "5.0.0"
- **`Firebase` module(s) you're using that has the issue:**
  - [x] Crashlytics

**Comment by Titozzz** [comment]
Hello, the purpose of the function crash that you are calling is literally to ... crash() so that you get a real report on crashlytics.. 🚀

**Comment by dantn93** [comment]
@Titozzz  When I test on ios simulator. It appears immediately. Do you know how long it appear?

**Comment by dantn93** [comment]
@Titozzz Please reopen this topic. I think this service having problems. I have waited for more than 12 hours, but I don't receive any report in console firebase.
Can you give me a "crashlytics service" demo? Thanks

**Comment by navata** [comment]
I have this issues. I think we should update this library.

**Comment by jimmying** [comment]
I'm only testing on Android and it didn't work when running via dev on emulator or device. I waited over 12 hours and nothing.

It did work, however, when building a released version. That said, I've noticed that crashes don't show up consistently or instantly. I dunno, will continue testing but it looks like it works at least.

**Comment by GIRIRAJNAGAR768** [comment]
use following dependencies for android: 

 implementation('com.crashlytics.sdk.android:crashlytics:2.9.6@aar') {
        transitive = true
    }

it works for me. Thanks

**Comment by mikehardy** [comment]
No, don't use those. They are out of date. 2.10.1 is current
https://firebase.google.com/support/release-notes/android

**Comment by thanhluantl2304** [comment]
Dear mr @mikehardy I've tried test crash in debug mode. But it still not showing any issues in Firebase Console but only Crash-free statistics changed. Can you help me about that?

**Comment by mikehardy** [comment]
@thanhluantl2304 there are a lot of docs you need to read I think, especially the ones upstream on the google firebase site. Crashes won't report by default in debug mode. And you may not have uploaded de-obfuscation files. You have to relaunch the app to send the crash, etc etc.

**Comment by thanhluantl2304** [comment]
Thanks Mr @mikehardy i ran it as released app then it worked. But I want to ask you 1 more question. The report shown not clear issue's info. I want something like react native file name, error line number in react native file but report shown only info about native code (index.bundle). Can you explain about that? If could not, can you introduce me another library to get linenumber, filename when catch exception? Thank you very much!

**Comment by mikehardy** [comment]
@thanhluantl2304 so you need to maintain sourcemaps from your build process. Crashlytics has no map that goes back from the minimized/bundled javascript to the separate javascript files, back to maybe the typescript or whatever right? So if you need the original line numbers you must maintain sourcemaps and trace back. I'm unaware of off the shelf scripts that do that but they probably exist.

**Comment by thanhluantl2304** [comment]
Ok,  I'm going to try sentry for that purpose! Thanks you very much for the help!
