### ISSUE TITLE
How to test Crashlytics ?

### ISSUE THREAD

**Issue by ButuzGOL** [invertase/react-native-firebase#1638]
I have setup for both ios and android and in console Crashlytics dashboard appear
then i have button on which i have 
```
firebase.crashlytics().crash();
```
when i press it app crashes but no info on dashboard appear

**Comment by Ehesp** [comment]
You need to wait a while before it shows in the dashboard, it's not realtime I'm afraid. Usually 24-48 hours.

**Comment by FadiAboMsalam** [comment]
![Screenshot 2022-11-27 at 15 06 43](https://user-images.githubusercontent.com/12826829/204136840-58c56eb3-5115-466e-8e86-29d4829fc988.png)

this is what fixed it for me
