### ISSUE TITLE
React Native RNFirebaseStoragePackage Error: You attempted to use a firebase module that's not installed on your Android Project by calling firebase.firestore()

### ISSUE THREAD

**Issue by joris416** [invertase/react-native-firebase#1640]
In my React-Native application I use Firebase and FireStore. It runs fine on iOS, but when I run it on Android it tells me 'You attempted to use a firebase module that's not installed on your Android Project by calling firebase.firestore()'.

I followed all steps on https://rnfirebase.io/docs/v5.x.x/storage/android. My MainApplication.java is shown below:

```
import android.app.Application;

import com.facebook.react.ReactApplication;
import com.brentvatne.react.ReactVideoPackage;
import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.storage.RNFirebaseStoragePackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ReactVideoPackage(),
            new RNFirebasePackage(),
            new RNFirebaseStoragePackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  }; 
```

This gives the new RNFirebaseStoragePackage red underlining with the following message: 
![schermafbeelding 2018-10-26 om 11 13 27](https://user-images.githubusercontent.com/3315888/47557566-4af45c80-d911-11e8-8801-228c5a13bf67.png)

My app successfully compiles, but immediately gives the React Native red error screen: 
![screenshot_1540545772](https://user-images.githubusercontent.com/3315888/47557644-82630900-d911-11e8-94c8-5f2c27ca116a.png)

_Originally posted by @joris416 in https://github.com/invertase/react-native-firebase/issue_comments#issuecomment-433345546_

**Comment by Salakar** [comment]
Hey @joris416, you need to follow the Firestore guide on the docs, not the Storage one.
