### ISSUE TITLE
react-native link does not work after installing firebase

### ISSUE THREAD

**Issue by barjas** [invertase/react-native-firebase#1644]
## Issue

react-native link does not work well after installing firebase. builing ios fails after installing any other library after installing firebase. looks like pods and link does not play well togather 

im using the firebase starter kit. 

any advice ?

**Comment by Ehesp** [comment]
Hello - please could follow the issue template, or provide more details such as any errors etc you're experiencing. I'll reopen once we've got that and can help further.
