### ISSUE TITLE
🔥 Undefined symbols for architecture x86_64 & Use of undefined identifier

### ISSUE THREAD

**Issue by mycoberago** [invertase/react-native-firebase#1645]
## Issue

First, I really appreciate RNF's existence and I want to thank anyone and everyone who is willing to help...

I have successfully implemented RNF using RNFirebaseNotification, RNFirebaseMessaging and RNFirebaseAnalytics.  It has worked flawlessly.  This week, I was in the process of implementing authentication and storage.  I went through the same process of MANUALLY installing frameworks WITHOUT COCOAPODS using [this process](https://github.com/invertase/react-native-firebase/issues/1016#issuecomment-384027481) as I have in the past.  The implementation of RNFirebaseAuth went without any issues--binary compiled without a problem as well as debugging with both simulator and actual device...

MY PROBLEM is when I add the RNFirebaseStorage framework.  As soon as the framework is added (process done the same as all other frameworks that were successfully implemented), the binary will no longer compile with a slew of errors.  See images below:

THIS IS THE INITIAL ERRORS THAT I GET...
<img width="679" alt="screen shot 2018-10-28 at 9 21 50 am" src="https://user-images.githubusercontent.com/8285427/47621725-f3e5b780-dac9-11e8-8528-e344a044aee1.png">

FOLDER STRUCTURE WHERE ISSUE OCCURS
<img width="406" alt="screen shot 2018-10-28 at 4 36 23 pm" src="https://user-images.githubusercontent.com/8285427/47622213-66f22c80-dad0-11e8-86b0-ae65ab9cb418.png">

HEADER SEARCH PATHS (ALL HAVE BEEN WORKING BEFORE FRAMEWORK IS ADDED)
<img width="519" alt="screen shot 2018-10-28 at 4 43 17 pm" src="https://user-images.githubusercontent.com/8285427/47622236-b89ab700-dad0-11e8-942b-557fc46c572d.png">

THESE ERRORS OCCUR AFTER I UNLINK AND RELINK RNF
<img width="404" alt="screen shot 2018-10-28 at 8 09 09 am" src="https://user-images.githubusercontent.com/8285427/47621724-efb99a00-dac9-11e8-8532-85b3295873d1.png">

I have tried solutions proposed doing the following:
add libsqlite3.tbd, libz.tbd, libc++.tbd in Linked Frameworks as well as REMOVING DERIVED DATA found [here](https://stackoverflow.com/questions/42292090/firebase-undefined-symbols-for-architecture-x86-64).  I also tried different configurations described [here](https://github.com/facebook/react-native/issues/15838).

I have also unlinked and re-linked react-native-firebase.  

Again, I have successfully installed and implemented RNF until I add the RNFirebaseStorage framework.

I appreciate all the help.

Thank you in advance.

---

#### `ios/Podfile`:

- [x ] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:

#### `AppDelegate.m`:
```#import "AppDelegate.h"

#import "Firebase.h"
#import "RNFirebaseNotifications.h"
#import "RNFirebaseMessaging.h"
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTPushNotificationManager.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;
  // firebase config
  [FIRApp configure];
  // notifications config
  [RNFirebaseNotifications configure];
  
#if DEBUG
 jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
 jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
  

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"someApp"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundC

olor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

  - (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
    [[RNFirebaseNotifications instance] didReceiveLocalNotification:notification];
  }

  - (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
  fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
    [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
  }

  - (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
    [[RNFirebaseMessaging instance] didRegisterUserNotificationSettings:notificationSettings];
  }

@end
```

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `iOS 10` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [ x] MacOS, version: `High Sierra`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Xcode 10` e.g. Xcode 10, Android Studio 3.2
- **`React Native` version:**
  - `0.55.2`
- **`React Native Firebase` library version:**
  - `^4.3.7`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ x] Storage
- **Are you using `TypeScript`?**
  - [x ] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

**Comment by mycoberago** [comment]
Has anyone successfully implemented FirebaseStorage installing it manually as mentioned above?  It is the only component that is not working for me.

**Comment by salmanbukhari1** [comment]
any one able to solve this yet?
