### ISSUE TITLE
🔥 OnNotificationOpened not called when app is killed on ios

### ISSUE THREAD

**Issue by AishwaryaSurana** [invertase/react-native-firebase#1646]
## Issue

My notifications are getting displayed even when the app is killed but onNotificationOpened is not called when I click on notification and app crashes

` this.notificationOpenedListener =
 firebase.notifications().onNotificationOpened((notificationOpen: NotificationOpen) => {
const action = notificationOpen.action;
        const notification: Notification = notificationOpen.notification;
        var data = notification._data;
        if (data.action_target.toUpperCase() == "PROFILE".toUpperCase()) {
          Actions.profile();
        } else if (data.action_target.toUpperCase() == "Leaderboard".toUpperCase()) {
          Actions.skills({target:"leaderBoard"});
        } else if (data.action_target.toUpperCase() == "home".toUpperCase()) {
          Actions.homepage();
        } 
    });`

---

#### `ios/Podfile`:

- [x] I'm using Pods

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [x] iOS 10
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `iOS 10 `
- **Operating System:**
  - [x] MacOS
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Xcode 10`
- **`React Native` version:**
  - `55.4`
- **`React Native Firebase` library version:**
  - `^4.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [x] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

**Comment by Udbhav12** [comment]
I am facing issue in Android. Using RNF 5.5.4 and RN 0.59.9. When app is in killed state, notification is displayed but `onNotificationDisplayed` is not called

**Comment by mikehardy** [comment]
you should open a new issue not post on a closed one - but in general I believe when the app is in the background (and killed) on android even, notifications just go to the system tray and the app doesn't get control until the user taps on it, https://firebase.google.com/docs/cloud-messaging/android/receive but messaging/notifications is hard to think about correctly much less implement correctly so a new issue with full template is useful
