### ISSUE TITLE
How to make share extension authenticate when the user is already authenticated in the main app (without making the user to login again from the share extension)

### ISSUE THREAD

**Issue by i25878427** [invertase/react-native-firebase#1647]
Hey,

I am trying to achieve the following scenario:
1. User open the main app and login to the app (auth with firebase)
2. User open share extension and save the data to firebase database using the authentication he achieved in step 1.

In other words, I want to save the user the need to authenticate with firebase from the share extension when he already did it in the main app.

Is there a token or something I can share with the share extension from the main app using keychain or "App Group" in order the achieve this scenario?

I will appreciate the help,

**Comment by Ehesp** [comment]
Hello

How will your extension connect with Firebase? Can it make API calls, or use other Firebase SDKs?

You can get the users token (https://rnfirebase.io/docs/v5.x.x/auth/reference/User#getIdToken) here and use it to connect with Firebase services to save the data.

**Comment by i25878427** [comment]
Once I have the token. Which function should I use in order to connect to firebase?
