### ISSUE TITLE
Ios Build Errors

### ISSUE THREAD

**Issue by dileepbolisetti** [invertase/react-native-firebase#1649]
## Issue
react-native-firebase v5 build errors in IOS.

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:
platform :ios, '9.0'

target 'RNFirebaseStarter' do

  # use_frameworks!

   Pods for RNFirebaseStarter

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.9.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/AdMob', '~> 5.9.0'
  pod 'Firebase/Auth', '~> 5.9.0'
  pod 'Firebase/Database', '~> 5.9.0'
  pod 'Firebase/Functions', '~> 5.9.0'
  pod 'Firebase/DynamicLinks', '~> 5.9.0'
  pod 'Firebase/Firestore', '~> 5.9.0'
  # pod 'Firebase/Invites', '~> 5.9.0'
  pod 'Firebase/Messaging', '~> 5.9.0'
  pod 'Firebase/RemoteConfig', '~> 5.9.0'
  pod 'Firebase/Storage', '~> 5.9.0'
  pod 'Firebase/Performance', '~> 5.9.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.9'

end
```ruby
# N/A
```

#### `AppDelegate.m`:
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  NSURL *jsCodeLocation;
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"RNFirebaseStarter"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

@end

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS

- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [ ] MacOS, version: `High Sierra-10.13.6`
 
- **Build Tools:**
  - `ADD_SOMETHING_HERE` e.g. Xcode 10, Android Studio 3.2
- **`React Native` version:**
  - `0.57.1`
- **`React Native Firebase` library version:**
  - `^5.0.0`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [ ] No
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by Ehesp** [comment]
Hello - you've said you have iOS Build Errors but haven't shown them. Please provide some errors or information which will help us see what the problem is.

**Comment by dileepbolisetti** [comment]
@Ehesp 

When ever i update pods with pod install or pod update for using new pods the issue raising again...

with this pod lock file i am not getting above  errors..

PODS:
  - BoringSSL (10.0.6):
    - BoringSSL/Implementation (= 10.0.6)
    - BoringSSL/Interface (= 10.0.6)
  - BoringSSL/Implementation (10.0.6):
    - BoringSSL/Interface (= 10.0.6)
  - BoringSSL/Interface (10.0.6)
  - Crashlytics (3.10.9):
    - Fabric (~> 1.7.13)
  - Fabric (1.7.13)
  - Firebase/AdMob (5.9.0):
    - Firebase/Core
    - Google-Mobile-Ads-SDK (~> 7.33)
  - Firebase/Auth (5.9.0):
    - Firebase/CoreOnly
    - FirebaseAuth (= 5.0.4)
  - Firebase/Core (5.9.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.2.0)
  - Firebase/CoreOnly (5.9.0):
    - FirebaseCore (= 5.1.4)
  - Firebase/Database (5.9.0):
    - Firebase/CoreOnly
    - FirebaseDatabase (= 5.0.3)
  - Firebase/DynamicLinks (5.9.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (= 3.1.0)
  - Firebase/Firestore (5.9.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (= 0.13.4)
  - Firebase/Functions (5.9.0):
    - Firebase/CoreOnly
    - FirebaseFunctions (= 2.1.1)
  - Firebase/Messaging (5.9.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (= 3.1.2)
  - Firebase/Performance (5.9.0):
    - Firebase/Core
    - FirebasePerformance (= 2.1.2)
  - Firebase/RemoteConfig (5.9.0):
    - Firebase/Core
    - FirebaseRemoteConfig (= 3.0.1)
  - Firebase/Storage (5.9.0):
    - Firebase/CoreOnly
    - FirebaseStorage (= 3.0.2)
  - FirebaseABTesting (2.0.0):
    - FirebaseCore (~> 5.0)
    - Protobuf (~> 3.5)
  - FirebaseAnalytics (5.2.0):
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.2)
    - GoogleAppMeasurement (~> 5.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - GoogleUtilities/NSData+zlib (~> 5.2)
    - nanopb (~> 0.3)
  - FirebaseAnalyticsInterop (1.0.0)
  - FirebaseAuth (5.0.4):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.0)
    - GoogleUtilities/Environment (~> 5.2)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (5.1.4):
    - GoogleUtilities/Logger (~> 5.2)
  - FirebaseDatabase (5.0.3):
    - FirebaseCore (~> 5.0)
    - leveldb-library (~> 1.18)
  - FirebaseDynamicLinks (3.1.0):
    - FirebaseAnalytics (~> 5.1)
    - FirebaseAnalyticsInterop (~> 1.0)
    - FirebaseCore (~> 5.1)
  - FirebaseFirestore (0.13.4):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.0)
    - FirebaseFirestore/abseil-cpp (= 0.13.4)
    - gRPC-C++ (~> 0.0.3)
    - gRPC-ProtoRPC (~> 1.0)
    - leveldb-library (~> 1.20)
    - nanopb (~> 0.3.8)
    - Protobuf (~> 3.1)
  - FirebaseFirestore/abseil-cpp (0.13.4):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.0)
    - gRPC-C++ (~> 0.0.3)
    - gRPC-ProtoRPC (~> 1.0)
    - leveldb-library (~> 1.20)
    - nanopb (~> 0.3.8)
    - Protobuf (~> 3.1)
  - FirebaseFunctions (2.1.1):
    - FirebaseCore (~> 5.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseInstanceID (3.2.2):
    - FirebaseCore (~> 5.1)
    - GoogleUtilities/Environment (~> 5.3)
    - GoogleUtilities/UserDefaults (~> 5.3)
  - FirebaseMessaging (3.1.2):
    - FirebaseCore (~> 5.0)
    - FirebaseInstanceID (~> 3.0)
    - GoogleUtilities/Reachability (~> 5.2)
    - Protobuf (~> 3.1)
  - FirebasePerformance (2.1.2):
    - FirebaseAnalytics (~> 5.1)
    - FirebaseInstanceID (~> 3.2)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - GoogleUtilities/ISASwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.5)
  - FirebaseRemoteConfig (3.0.1):
    - FirebaseABTesting (~> 2.0)
    - FirebaseAnalytics (~> 5.1)
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.2)
    - GoogleUtilities/Environment (~> 5.2)
    - GoogleUtilities/NSData+zlib (~> 5.2)
    - Protobuf (~> 3.5)
  - FirebaseStorage (3.0.2):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - Google-Mobile-Ads-SDK (7.34.0)
  - GoogleAppMeasurement (5.2.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - GoogleUtilities/NSData+zlib (~> 5.2)
    - nanopb (~> 0.3)
  - GoogleToolboxForMac/Defines (2.1.4)
  - GoogleToolboxForMac/Logger (2.1.4):
    - GoogleToolboxForMac/Defines (= 2.1.4)
  - GoogleToolboxForMac/NSData+zlib (2.1.4):
    - GoogleToolboxForMac/Defines (= 2.1.4)
  - GoogleUtilities/AppDelegateSwizzler (5.3.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (5.3.0)
  - GoogleUtilities/ISASwizzler (5.3.0)
  - GoogleUtilities/Logger (5.3.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (5.3.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (5.3.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/NSData+zlib
    - GoogleUtilities/Reachability
  - GoogleUtilities/NSData+zlib (5.3.0)
  - GoogleUtilities/Reachability (5.3.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (5.3.0):
    - GoogleUtilities/Logger
  - gRPC (1.14.0):
    - gRPC-RxLibrary (= 1.14.0)
    - gRPC/Main (= 1.14.0)
  - gRPC-C++ (0.0.3):
    - gRPC-C++/Implementation (= 0.0.3)
    - gRPC-C++/Interface (= 0.0.3)
  - gRPC-C++/Implementation (0.0.3):
    - gRPC-C++/Interface (= 0.0.3)
    - gRPC-Core (= 1.14.0)
    - nanopb (~> 0.3)
  - gRPC-C++/Interface (0.0.3)
  - gRPC-Core (1.14.0):
    - gRPC-Core/Implementation (= 1.14.0)
    - gRPC-Core/Interface (= 1.14.0)
  - gRPC-Core/Implementation (1.14.0):
    - BoringSSL (~> 10.0)
    - gRPC-Core/Interface (= 1.14.0)
    - nanopb (~> 0.3)
  - gRPC-Core/Interface (1.14.0)
  - gRPC-ProtoRPC (1.14.0):
    - gRPC-ProtoRPC/Main (= 1.14.0)
  - gRPC-ProtoRPC/Main (1.14.0):
    - gRPC (= 1.14.0)
    - gRPC-RxLibrary (= 1.14.0)
    - Protobuf (~> 3.0)
  - gRPC-RxLibrary (1.14.0)
  - gRPC/Main (1.14.0):
    - gRPC-Core (= 1.14.0)
    - gRPC-RxLibrary (= 1.14.0)
  - GTMSessionFetcher/Core (1.2.0)
  - leveldb-library (1.20)
  - nanopb (0.3.8):
    - nanopb/decode (= 0.3.8)
    - nanopb/encode (= 0.3.8)
  - nanopb/decode (0.3.8)
  - nanopb/encode (0.3.8)
  - Protobuf (3.6.1)

DEPENDENCIES:
  - Crashlytics (~> 3.10.9)
  - Fabric (~> 1.7.13)
  - Firebase/AdMob (~> 5.9.0)
  - Firebase/Auth (~> 5.9.0)
  - Firebase/Core (~> 5.9.0)
  - Firebase/Database (~> 5.9.0)
  - Firebase/DynamicLinks (~> 5.9.0)
  - Firebase/Firestore (~> 5.9.0)
  - Firebase/Functions (~> 5.9.0)
  - Firebase/Messaging (~> 5.9.0)
  - Firebase/Performance (~> 5.9.0)
  - Firebase/RemoteConfig (~> 5.9.0)
  - Firebase/Storage (~> 5.9.0)

SPEC CHECKSUMS:
  BoringSSL: e10f92a27043805c01071fe815a5cd98ae8212e7
  Crashlytics: 55e24fc23989680285a21cb1146578d9d18e432c
  Fabric: 25d0963b691fc97be566392243ff0ecef5a68338
  Firebase: 383fa29aca93e371cab776b48a5c66544d3c2003
  FirebaseABTesting: 1f50b8d50f5e3469eea54e7463a7b7fe221d1f5e
  FirebaseAnalytics: 831f1f127f4a75698e9875a87bf7e2668730d953
  FirebaseAnalyticsInterop: 31b00d2a916918327308b2dff47251eb96f9e4ad
  FirebaseAuth: 504b198ceb3472dca5c65bb95544ea44cfc9439e
  FirebaseAuthInterop: 0ffa57668be100582bb7643d4fcb7615496c41fc
  FirebaseCore: 2a84b6b325792a4319ef71ee18819dcba08d2fd7
  FirebaseDatabase: e2bcbc106adc4b11a2da3ec2eb63c0c4a44f2f54
  FirebaseDynamicLinks: 33f349103fa71d463688b7671e6a60e00ac6a5af
  FirebaseFirestore: eaf0b6244e9463e2429fe216666b641e4dec606b
  FirebaseFunctions: 6c03d7c5d62520be4678dc3fb7957654aab82b4f
  FirebaseInstanceID: 78ba376fcd5b94c001f9999b2cbd3d1f1e56e78d
  FirebaseMessaging: d6feeb06218d2675b4149b0ada925a6b707a74cf
  FirebasePerformance: 65f7eb943ef3cc118899f945065ff9fa2d924e52
  FirebaseRemoteConfig: 7b6d675dfb11f0e0e638caee00908b06af150d56
  FirebaseStorage: fd82e5e5c474897e19972b34b22ac0f589dce04e
  Google-Mobile-Ads-SDK: a1cbce28c0c78ca1fb0b6c4f213485f55527c99f
  GoogleAppMeasurement: 2b3a023a61239c8d002e6e4fcf4abce8eddce0e0
  GoogleToolboxForMac: 91c824d21e85b31c2aae9bb011c5027c9b4e738f
  GoogleUtilities: 760ccb53b7c7f40f9c02d8c241f76f841a7a6162
  gRPC: 9d4c549f37c7cef22478634bac7a0405b6e3dbfb
  gRPC-C++: ee0b01db3122f0b6c2be28b5b11039f62fa15fe6
  gRPC-Core: f4836515817c0eb479aeeb9cc27c91c4ba62a9f6
  gRPC-ProtoRPC: 76f6053639a842e1fb45fa82aa598bf3f4d9f66f
  gRPC-RxLibrary: 3c305f32155024b116b780f389323c73a28197e6
  GTMSessionFetcher: 0c4baf0a73acd0041bf9f71ea018deedab5ea84e
  leveldb-library: 08cba283675b7ed2d99629a4bc5fd052cd2bb6a5
  nanopb: 5601e6bca2dbf1ed831b519092ec110f66982ca3
  Protobuf: 1eb9700044745f00181c136ef21b8ff3ad5a0fd5

PODFILE CHECKSUM: 724559b1eac0e0a9de158e66af8420939958674a

COCOAPODS: 1.4.0

**Comment by dileepbolisetti** [comment]
After Updating xcode  to latest one Errors Are gone
