### ISSUE TITLE
Breakout to Web SDK

### ISSUE THREAD

**Issue by Cretezy** [invertase/react-native-firebase#165]
I think we should provide a way to breakout to the [Web SDK](https://www.npmjs.com/package/firebase) when needed. Something like `firebase.web()` would use the `firebase.initializeApp` of the Web SDK with pre-filled data.

**Comment by Ehesp** [comment]
Hello, thanks for the suggestion. Do you have a good use-case for this?

We had a chat internally and we don't think this will be implemented. Generally swapping out the two libraries is easy anyway, as you just change a few things in a file which is exported to your app. The other reason being there is a lot of features which the native SDKs provide which the web SDK does not. For example Database provides offline support with this lib, and with the web SDK it would not. Having the ability to switch between the who libraries would cause issues and shouldn't really be done without good reason.

**Comment by Cretezy** [comment]
My very specific use case was for https://github.com/invertase/react-native-firebase/issues/164.

Maybe a way to get the current app 'settings' that could be fed to the Web SDK's `initializeApp` would be a perfect compromise.

**Comment by chrisbianca** [comment]
@Cretezy as mentioned by @Salakar on https://github.com/invertase/react-native-firebase/issues/164, there is work in progress on an app module to match the Javascript SDK.

I'm going to close this as breaking out to the web SDK is not something we plan on supporting.  Instead we will just continue to add to this library to cover the whole of the Javascript SDK, with the caveat that there has to be equivalent functionality available within the native iOS and Android SDKs.

**Comment by Cretezy** [comment]
That's great! However I think a simple function to get the "settings" that RNFirebase currently uses (read from fs) would be a great middle point between a full break out and a DIY break out.
