### ISSUE TITLE
RNFirebase core module was not found natively on android

### ISSUE THREAD

**Issue by archer87pl** [invertase/react-native-firebase#1659]
Hi, there are a lot of open requests regarding exception:
https://github.com/invertase/react-native-firebase/issues/682
https://stackoverflow.com/questions/50198791/rnfirebase-core-module-was-not-found-natively-on-android

Could you please help us how to resolve that issue? We have `   new RNFirebasePackage(),` in `MainApplication.java`

**Comment by Salakar** [comment]
Please correctly fill out the issue template, without this, we can not help, we're not mind readers. 🙃 

Locking and closing this issue. Feel free to raise another issue that correctly follows the issue template.
