### ISSUE TITLE
docs seem to be broken

### ISSUE THREAD

**Issue by Talor-A** [invertase/react-native-firebase#166]
Hi, not sure what happened but the docs site now has no sidebar and only the home page will display.

**Comment by chrisbianca** [comment]
@Talor-A we're looking into this - we're not sure what's happened either, seems to be something strange happening between GitHub pages and Docsify.

**Comment by nlmvy** [comment]
What happened with the docs site?

**Comment by Salakar** [comment]
Back to normal now it seems, must have been github. Can you both confirm?

**Comment by Salakar** [comment]
Have confirmed with a few others and seems to be good now. Closing
