### ISSUE TITLE
🔥5.0.0 crashes on iOS 12 at [FIRApp configure];

### ISSUE THREAD

**Issue by SirVeryBritish** [invertase/react-native-firebase#1662]
## Issue

Greetings, I tried to migrate from react-native-fcm to react-native-firebase@5.0.0. Set everything up according to the docs and tried to run my app on an iOS 12 - iPhone X Simulator. The app immediately crashes at startup. Android API 28 works really well. After spending more time than I would like to admit, searching StackOverflow and this GitHub repository, I tried version 4.3.8 and everything worked on first try with iOS 12.

Here is a stacktrace from Xcode and a screenshot of AppCode, when setting a breakpoint for the first exception 

stacktrace:
libc++abi.dylib: terminating with uncaught exception of type NSException

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/10279069/47954713-a962b000-df8d-11e8-8721-c810ad91cd4f.png">

Although, went I try with iOS version 10.1.3, I'm getting this stacktracen from Xcode:

*** First throw call stack:
(
	0   CoreFoundation                      0x000000011129cb0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010fd35141 objc_exception_throw + 48
	2   XXX                            0x000000010e74dd18 +[FIRAnalytics logEventWithName:parameters:] + 0
	3   libobjc.A.dylib                     0x000000010fd35e0a CALLING_SOME_+initialize_METHOD + 19
	4   libobjc.A.dylib                     0x000000010fd36032 _class_initialize + 550
	5   libobjc.A.dylib                     0x000000010fd3d187 lookUpImpOrForward + 225
	6   libobjc.A.dylib                     0x000000010fd4c554 _objc_msgSend_uncached + 68
	7   XXX                            0x000000010e72a6c1 -[FIRApp configureCore] + 705
	8   XXX                            0x000000010e729ef0 +[FIRApp addAppToAppDictionary:] + 144
	9   XXX                            0x000000010e728f3f +[FIRApp configureDefaultAppWithOptions:sendingNotifications:] + 367
	10  XXX                            0x000000010e728cf1 +[FIRApp configure] + 513
	11  XXX                            0x000000010e728170 -[AppDelegate application:didFinishLaunchingWithOptions:] + 96
	12  UIKit                               0x0000000113e6e9b7 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 299
	13  UIKit                               0x0000000113e7029c -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4119
	14  UIKit                               0x0000000113e765e4 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1709
	15  UIKit                               0x0000000113e737f3 -[UIApplication workspaceDidEndTransaction:] + 182
	16  FrontBoardServices                  0x00000001182b35f6 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	17  FrontBoardServices                  0x00000001182b346d -[FBSSerialQueue _performNext] + 186
	18  FrontBoardServices                  0x00000001182b37f6 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	19  CoreFoundation                      0x0000000111242c01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	20  CoreFoundation                      0x00000001112280cf __CFRunLoopDoSources0 + 527
	21  CoreFoundation                      0x00000001112275ff __CFRunLoopRun + 911
	22  CoreFoundation                      0x0000000111227016 CFRunLoopRunSpecific + 406
	23  UIKit                               0x0000000113e7208f -[UIApplication _run] + 468
	24  UIKit                               0x0000000113e78134 UIApplicationMain + 159
	25  XXX                            0x000000010e728510 main + 112
	26  libdyld.dylib                       0x000000011585165d start + 1
	27  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0' <- also breaks, when not commented

target 'XXX' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XXX
  pod 'Firebase/Core', '~> 5.9.0'

  target 'XXXTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

#### `AppDelegate.m`:

```objc
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"
#import <React/RCTBundleURLProvider.h>
#import <Firebase.h>
#import "RNFirebaseNotifications.h"
#import "RCCManager.h"
#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  
  NSURL *jsCodeLocation;
#ifdef DEBUG
  //  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
  
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  self.window.backgroundColor = [UIColor whiteColor];
  [[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation launchOptions:launchOptions];

  return YES;
}
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - iOS 12 - iPhone X Simulator 
  - iOS 12 - iPhone SE
- **Operating System:**
  - [x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - Xcode 10
  - AppCode 2018.2.4
Build #OC-182.4892.21, built on October 16, 2018
JRE: 1.8.0_152-release-1248-b19 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
- **`React Native` version:**
  - 0.55.3
- **`React Native Firebase` library version:**
  - 5.0.0
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by jarvisluong** [comment]
Reading from the project README, it says RNFirebase 5.0.0 only supports react-native 0.57 and above... That may be the reason it crashed.

**Comment by SirVeryBritish** [comment]
> Reading from the project README, it says RNFirebase 5.0.0 only supports react-native 0.57 and above... That may be the reason it crashed.

Oh dang, my bad. Thanks a lot @jarvisluong. I'm closing this issue now.
