### ISSUE TITLE
Email, Password & Phone - Create user ONLY IF BOTH authentication methods are valid

### ISSUE THREAD

**Issue by visagegod** [invertase/react-native-firebase#1664]
I'm trying to create an authentication flow where I am taking the user email & password then I am taking their phone and sending a SMS verification (they then input the code) and the account should get created ONLY IF BOTH authentication methods are valid
At the moment I am only finding a way to create a email&password account then add the phone authentication to it at a later time... any suggestions? Many thanks :smiley:
Currently looking like this:

```
const credential = await firebase.auth.PhoneAuthProvider.credential(this.state.verificationId, code);
await firebase.auth().createUserWithEmailAndPassword(email, pass)
await firebase.auth().currentUser.linkWithCredential(credential);
```

Problem being that the user could enter an incorrect phone verification code and the account would still get created with no phone linked...

**Comment by visagegod** [comment]
FROM @Salakar on Discord: 

your apps flow/logic can prevent continuing past the signup screens if https://rnfirebase.io/docs/v5.x.x/auth/reference/User#phoneNumber is not present (the number will be null until there's a verified phone number on the account

**Comment by Salakar** [comment]
@visagegod happy to help 👍 

You can throw the below into the mix with an auth state listener for ultimate winning 😉 

#### emailVerified

https://rnfirebase.io/docs/v5.x.x/auth/reference/User#emailVerified

#### sendEmailVerification

https://rnfirebase.io/docs/v5.x.x/auth/reference/User#sendEmailVerification

#### onAuthStateChanged

https://rnfirebase.io/docs/v5.x.x/auth/reference/auth#onAuthStateChanged


### Example

```js
firebase.auth().onAuthStateChanged(user => {
  if (user) {
    if (user.phoneNumber && user.emailVerified) {
      // ALL GOOD
    } else {
      // EMAIL/PHONE NOT VERIFIED
    }
  } else {
    // NOT SIGNED IN - dispatch / goto login screen?
  }
});
```

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
