### ISSUE TITLE
Documentation for supported / unsupported features

### ISSUE THREAD

**Issue by fdnhkj** [invertase/react-native-firebase#167]
Hi,

As discussed in [this Reddit post](https://www.reddit.com/r/reactnative/comments/6h0rtf/react_native_firebase_is_a_breeze_to_develop_with/), I think it would be nice to document in repo/docs the list of supported/not supported features (as a table?) for v1 and v2.

**Comment by Ehesp** [comment]
Something like the below? Makes sense...

| Firebase Features      | v1  | v2  |
| ---------------------- | --- | --- |
| Analytics              |     |     |
| Cloud Messaging        |     |     |
| Authentication         |     |     |
| Realtime Database      |     |     |
| Storage                |     |     |
| Performance Monitoring |     |     |
| Crash Reporting        |     |     |
| Remote Config          |     |     |
| App Indexing           |     |     |
| Dynamic Links          |     |     |
| Invites                |     |     |
| AdMob                  |     |     |

**Comment by fdnhkj** [comment]
Yes! That would be perfect :+1:

**Comment by Salakar** [comment]
@fdnhkj thanks for the issue and the upvote on reddit =] 

We'll get the supported feature table added to the front page of the docs.

**Comment by Salakar** [comment]
And done 👍

Thanks again. Closing
