### ISSUE TITLE
onMessage not receiving any message

### ISSUE THREAD

**Issue by Buwaneka1993** [invertase/react-native-firebase#1672]
##Version
"react-native-firebase": "^3.3.1"

## Issue
I used topics to send notification to mobile app. Its working only app is closed. but when app is on foreground messages are not receiving .

```
//call this when user login
function subscribeToTopic(){
  let topic='general';
  firebase.messaging().subscribeToTopic(topic);
}
//call this when user logout
function unsubscribeToTopic(){
  let topic='general';
  firebase.messaging().unsubscribeFromTopic(topic);
}

//call this on 'componentDidMount' on home screen
 this.messageListener = firebase.messaging().onMessage((message) => {
     console.log("message", message);
  });
```
I used above code lines. And OnMessage is not call when message send while app is on foreground. Right now I can`t use latest versions of react-native-firebase due to other nodemodules dependency issues. 

---

**Comment by sd1998** [comment]
@Ehesp I would like to work on this.

**Comment by MrIceman** [comment]
What platform?

**Comment by PrimeTimeTran** [comment]
@sd1998 have you had any luck? I'm on facing the same problem where `onMessage` is not called.
