### ISSUE TITLE
How to handle several storage bucket

### ISSUE THREAD

**Issue by AlexandreMaistret** [invertase/react-native-firebase#1674]
## Issue

I don't manage to use several storage buckets. Since there is no documentation for the Storage on the Docs I am using the official one provided by Google. It is written to use this : 

    var storage = firebase.app().storage("gs://my-custom-bucket");

However, I got an error saying that storage() cannot support an url. 

react-native: 0.55.4
react-native-firebase: 4.3.8

**Comment by AlexandreMaistret** [comment]
Hey hi Ehesp ! thanks for trying to help me.
I don't really understand why you are meaning by app instance (I don't know what to put in `appInstance`.) Is it possible that you to give me an example ?

**Comment by Ehesp** [comment]
You can create app instances by following this: https://rnfirebase.io/docs/v5.x.x/core/initialize-apps

Once you've created the app, you can access it via ``. With that app instance, you can then use that instance in your storage code:

```js
const app = firebase.core().app('foobar');
var storage = firebase.app().storage(app);
```

**Comment by AlexandreMaistret** [comment]
Thank you for the  explanation !
I will manage with that.

**Comment by VinodhPIT** [comment]
I'm also facing  the  same issue  now i'm working  on  old version of react native  here they  are using  firebase-version5 and i'm not able to use multiple buckets. Can any one please help me to fix the issue.?

**Comment by mikehardy** [comment]
@VinodhPIT - sadly, there is no support at all for v5, and it does not support recent enough SDK versions to work well on modern mobile operating systems, to the best of my knowledge

To create a new app instance you may find the legacy docs here https://v5.rnfirebase.io/docs/v5.x.x/core/initialize-apps

I can't stress enough though: do not use v5 of this library, upgrade to v14 at least (v15 if possible, though it require `use_frameworks!` in the Podfile, which may be problematic depending on your requirements.
