### ISSUE TITLE
Dependency failing: com.nimbusds:nimbus-jose-jwt:5.1 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2.3

### ISSUE THREAD

**Issue by afilp** [invertase/react-native-firebase#1676]
## Issue

I upgraded to the latest `react-native`, `gradle`, etc. I also upgraded to the latest `firebase`.

Now I get this error when trying to compile the Android project:

```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':app:checkCdialoguesDebugClasspath' property 'compileClasspath' during up-to-date check.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.3.1
  ,2.3]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
  
  Dependency failing: com.nimbusds:nimbus-jose-jwt:5.1 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2
  .3.
  
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends on project 'react' which depends onto com.nimbusds:nimbus-jose-jwt@5.1
  ```

I found that this is caused when I have this (required by firebase) code at the end:
`apply plugin: 'com.google.gms.google-services'`

If I remove this line, then it compiles.

Of course, due to this, then I get the following error (which is reasonable):
`Error : The [[DEFAULT]] firebase app has not been initialized`

So, what can we do in order to be able to both compile AND have `firebase` in our projects?

**IMPORTANT NOTE**: I noticed that the error is caused by the use of `json-smart` by `react-native-code-push`. I added the issue there too, in case you want to co-investigate: https://github.com/Microsoft/react-native-code-push/issues/1448

---

## Project Files

This is the dependencies code:

```
dependencies {
//    compile(project(':react-native-firebase')) { transitive = false }

    implementation project(':react-native-firebase')

    // RNFirebase required dependencies
    implementation 'com.google.firebase:firebase-core:16.0.4'
    implementation 'com.google.firebase:firebase-messaging:17.3.4'
    implementation 'com.google.android.gms:play-services-base:16.0.1'

    compile project(':react-native-sound')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-video')
    compile project(':react-native-vector-icons')
    compile project(':react-native-code-push')
    compile project(':react-native-device-info')
    compile project(':react-native-image-picker')

    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
```

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ x ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [ ] MacOS, version: `N/A`
  - [ x] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Android Studio 3.2` e.g. Xcode 10, Android Studio 3.2
- **`React Native` version:**
  - `0.57.4`
- **`React Native Firebase` library version:**
  - `^5.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [ x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by afilp** [comment]
@anitricks This is very interesting that we have the same problem while we both use `react-native-firebase` and `react-native-code-push`, with latest Android Studio/Gradle.

I believe this verifies the existence of the problem.

Since this is also related with `react-native-code-push` (the error I think is produced while compiling that package), can you please mention your problem also here so that we can all help in its resolution?
https://github.com/Microsoft/react-native-code-push/issues/1448

Thank you.

**Comment by OzzieOrca** [comment]
It appears that not adding `apply plugin: 'com.google.gms.google-services'` to the bottom of `app/build.gradle` like https://firebase.google.com/docs/android/setup#add_the_sdk says to do resolves the build issue. Maybe Codepush is already adding it or something.

**Comment by AlMel3000** [comment]
Hello!
@afilp 

try to add

`com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true`

at the bottom of android/app/build.gradle

**Comment by afilp** [comment]
@AlMel3000 This seems to be working! Thanks!

**Comment by afilp** [comment]
@AlMel3000 Do you think that this solution may cause any side effects?

**Comment by AlMel3000** [comment]
@afilp
Me and my team haven’t faced issues, related to this fix.
But we have not tried Firebase hardly - we are on the stage of its implementation.

**Comment by afilp** [comment]
Thanks!

**Comment by afilp** [comment]
@AlMel3000 I also see another possible solution:
https://github.com/invertase/react-native-firebase/issues/1155

Did you try that? (moving `jcenter()` after `google()`)

**Comment by AlMel3000** [comment]
@afilp
Didn’t worked for me

**Comment by OzzieOrca** [comment]
We got it working with this `android/build.gradle`:
```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.


buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'

        classpath 'org.ajoberstar:gradle-git:1.7.2'

        classpath 'com.google.gms:google-services:4.1.0' // <-- Was necessary to downgrade google-services from 4.2.0 to 4.1.0

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply plugin: 'org.ajoberstar.grgit'
ext.grgit = org.ajoberstar.grgit.Grgit.open()

allprojects {
    repositories {
        google()
        jcenter()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }

    configurations.all {
        resolutionStrategy.force(
            'com.google.firebase:firebase-invites:16.0.5', // <-- Was necessary to fix dependency resolution
        )
    }
}
```

The two important lines were
```gradle
classpath 'com.google.gms:google-services:4.1.0' // <-- Was necessary to downgrade google-services from 4.2.0 to 4.1.0
```
and
```gradle
configurations.all {
  resolutionStrategy.force(
    'com.google.firebase:firebase-invites:16.0.5', // <-- Was necessary to fix dependency resolution
  )
}
```

Idk how great of a solution that is but maybe that helps with debugging versions.

**Comment by afilp** [comment]
@OzzieOrca May I ask if this happens to you due to `react-native-code-push` too?

FYI, they investigate it there too: https://github.com/Microsoft/react-native-code-push/issues/1448

**Comment by OzzieOrca** [comment]
Yes we are using codepush also.

**Comment by Pandazaur** [comment]
Same problem when I installed `react-native-code-push`

As @OzzieOrca said, this line resolved my problem:

> ```groovy-gradle
> classpath 'com.google.gms:google-services:4.1.0' // <-- Was necessary to downgrade google-services from 4.2.0 to 4.1.0
> ```

**Comment by vinicarra** [comment]
This has not been fixed, downgrading the version should not be an accepted answer...

**Comment by mikehardy** [comment]
This is a dependency issue unrelated to react-native firebase. Additionally it is likely fixed if you upgrade all play services to current version. Finally there is a workaround available in the disable version check comment mentioned

**Comment by vivek-walecha-657** [comment]
@mikehardy Disable version check is not working. As @vinicarra mentioned downgrading the version is not the solution, we have to check why firebase is affecting code push and why intialize app issue is occurring.

**Comment by mikehardy** [comment]
or…check why code push is affecting react-native-firebase? I think it’s this https://github.com/Microsoft/react-native-code-push/blob/master/android/app/build.gradle#L30

**Comment by mikehardy** [comment]
./gradlew :app:dependencies usually has the answers, resolutionStrategy can help as well as excludes on dependencies

**Comment by cybernetic87** [comment]
If anybody still fights the issue:
`googleServices { disableVersionCheck = true
}`

Adding this resolved the issue for me.

**Comment by t2** [comment]
@cybernetic87 Adding it where?

**Comment by cybernetic87** [comment]
> @cybernetic87 Adding it where?

At the bottom of your build.gradle

**Comment by t2** [comment]
@cybernetic87 Thanks! That got past this initial error. Ran into another but don't expect it to be related.

**Comment by pedrosimao** [comment]
@cybernetic87 when I add it to the bottom of build.gradle I get the following error `Could not find method googleServices() for arguments`

**Comment by lerhhl** [comment]
> @cybernetic87 when I add it to the bottom of build.gradle I get the following error `Could not find method googleServices() for arguments`

Should be at the Bottom of the app build.gradle 
`apply plugin: 'com.google.gms.google-services'
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true`

**Comment by pedrosimao** [comment]
@lecramfriedrich I was using this line above the apply plugin. That's why it was bugging. Thanks a lot for your help!

**Comment by cielojrdev** [comment]
`com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true`
this helps, but still generated error about 'Unable to merge dex' so I needed to add this as well
in app/build.gradle
```
android {
    defaultConfig {
       multiDexEnabled true
    }
}
```
this is my setup
```
"react-native-code-push": "^5.6.1",
"react-native-firebase": "5.5.3",
"react": "16.8.3",
 "react-native": "0.59.9",
```

**Comment by rajesh-vdbapp** [comment]
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true  

not help me out in android

**Comment by snmishra** [comment]
> 
> 
> @cybernetic87 when I add it to the bottom of build.gradle I get the following error `Could not find method googleServices() for arguments`

I used to have
```
apply plugin: 'com.google.gms.google-services' com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
```

but, with version 4.3.1 of the plugin, I had to change to
```
apply plugin: 'com.google.gms.google-services' 
googleServices.disableVersionCheck = true
```

**Comment by Doko-Demo-Doa** [comment]
> > @cybernetic87 when I add it to the bottom of build.gradle I get the following error `Could not find method googleServices() for arguments`
> 
> I used to have
> 
> ```
> apply plugin: 'com.google.gms.google-services'
> com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
> ```
> 
> but, with version 4.3.1 of the plugin, I had to change to
> 
> ```
> apply plugin: 'com.google.gms.google-services' 
> googleServices.disableVersionCheck = true
> ```

@snmishra That works for me too, thanks a lot!

**Comment by Hesamedin** [comment]
`apply plugin: 'com.google.gms.google-services'
googleServices {
    disableVersionCheck = true
}`

This is **Pain Killer**, not a solution. 
We should blame Microsoft for such a bad support.

**Comment by mikehardy** [comment]
@Hesamedin it is a band-aid - there is a PR for the underlying issue here, https://github.com/google/play-services-plugins/pull/95 - subscribe there and you'll know when to pull the band-aid off :-)

**Comment by saggio89** [comment]
> ```
> apply plugin: 'com.google.gms.google-services'
> googleServices {
>     disableVersionCheck = true
> }
> ```
> 
> This is **Pain Killer**, not a solution.
> We should blame Microsoft for such a bad support.

When I try this, I get Plugin with id 'com.google.gms.google-services' not found

any idea anyone?

**Comment by snmishra** [comment]
> 
> 
> > ```
> > apply plugin: 'com.google.gms.google-services'
> > googleServices {
> >     disableVersionCheck = true
> > }
> > ```
...
> When I try this, I get Plugin with id 'com.google.gms.google-services' not found
> 
> any idea anyone?

I have the following:
```java
apply plugin: 'com.google.gms.google-services'
googleServices.disableVersionCheck = true
```

**Comment by bjacog** [comment]
A proper solution was found here: https://github.com/microsoft/react-native-code-push/issues/1448#issuecomment-561130291

Credit to @craigcolas:

> I was experiencing the same issue:
> 
> ```
> Dependency failing: com.nimbusds:nimbus-jose-jwt:5.1 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2
>   .3.
>   
>   The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
>   ifact with the issue.
>   -- Project 'app' depends on project 'react' which depends onto net.minidev:json-smart@{strictly 2.3}
>   -- Project 'app' depends on project 'react' which depends onto com.nimbusds:nimbus-jose-jwt@{strictly 5.1}
>   -- Project 'app' depends on project 'react' which depends onto com.nimbusds:nimbus-jose-jwt@5.1
> ```
> 
> I was seeing this after upgrading `com.google.gms:google-services` from version `4.1.0` to `4.2.0`. However, this issue is no longer happening after upgrading to the latest version `4.3.3`.

**Comment by mikehardy** [comment]
Yep, the underlying library PR merged. google services plugin 4.3.3+ no longer has this problem.

**Comment by madsams** [comment]
I had this problem with `com.google.gms:google-services:4.2.0`
downgrading to 4.1.0 or upgrading to 4.3.3 will fix this issue

**Comment by gomezmark** [comment]
> If anybody still fights the issue:
> `googleServices { disableVersionCheck = true }`
> 
> Adding this resolved the issue for me.

this worked on my end. thanks!
is there a possible side effect for this one?

**Comment by mikehardy** [comment]
Yes. You are now not checking for cross-compatibilities in google products. You should update to the most recent stable releases of everything and the problem goes away without disabling things

**Comment by ftcvlad** [comment]
Correct me if i'm wrong, but is [this](https://github.com/google/play-services-plugins/blob/master/strict-version-matcher-plugin/src/main/java/com/google/android/gms/dependencies/VersionEvaluation.kt#L17) the code in the most recent release?

So, if I aim to support Firebase version range, e.g. `com.google.firebase:firebase-messaging:[19.0.0, 22.99.99]`, it resolves to 22.0.0, [19.0.0, 22.99.99] !== 22.0.0 ---> it fails?

**Comment by mikehardy** [comment]
best to rely on the "bill of materials" and let them sort it: https://firebase.google.com/docs/android/learn-more#bom

**Comment by ftcvlad** [comment]
the reason i went with range instead of BoM is that i'm developing a module, so, i cannot pin consumers to a specific version of BoM. I could leave setting BoM version to them + use compileOnly, but a) slightly longer integration b) i only support range, not arbitrary versions. But yes, using BoM is a way.

**Comment by mikehardy** [comment]
You may want to pursue this directly with the play-services-plugin repo then - I understand at the module level things get stickier
