### ISSUE TITLE
Accessing Firebase database from Native(Android) side of react native application

### ISSUE THREAD

**Issue by gvetsa** [invertase/react-native-firebase#1679]
## Issue
I am using react native firebase in my react app to interact with database which is working very well but i want to access database from native side(Android) side of my react native app. How can i do that.
Any one please help me. I dont want to import google firebase and use it.

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - Android API 28
- **Operating System:**
  - [ ] MacOS, version: `N/A`
  - [x] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `ADD_SOMETHING_HERE`
- **`React Native` version:**
  - `0.57`
- **`React Native Firebase` library version:**
  - `5.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [x] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

**Comment by Ehesp** [comment]
Hey, whats your reasoning for wanting to do this?

In general, you'll need to create your own module and access the native SDK like we do on this lib, see https://github.com/invertase/react-native-firebase/tree/master/android/src/main/java/io/invertase/firebase/database

Closing as not an issue but happy to discuss.

**Comment by gvetsa** [comment]
> Hey, whats your reasoning for wanting to do this?
> 
> In general, you'll need to create your own module and access the native SDK like we do on this lib, see https://github.com/invertase/react-native-firebase/tree/master/android/src/main/java/io/invertase/firebase/database
> 
> Closing as not an issue but happy to discuss.

My Use case: 
1) I am starting HeadLessJs task from Broadcast Receiver from android but unfortunately the Headless Js task will execute only if the app is in background or foreground state. **It will not trigger the HeadlessJs task when the app is closed** but I need access to the firebase data from the android app. so i can do my business logic from android as there is no way for me to start the headlessJs task when the app closed. 
Solutions:
I have two solutions as i can think of
1) Use react native firebase API from java to access firebase database
2) Use Google firebase Android API to access firebase database

As i already have react native firebase API in my App. i am interested to use React native firebase API from java(Android).
Can you please guide me in this issue. or **please provide an example of how to use the React native firebase from java**.
