### ISSUE TITLE
displayNotification() not working on iOS

### ISSUE THREAD

**Issue by StijnCoolen** [invertase/react-native-firebase#1684]
## Issue

When receiving a notification on iOS while the app is in the foreground `onNotificationOpened` is called (and logs the notification). I then would like to use `firebase.notifications().displayNotification(notification);` to display the notification. This however gives me the following error: _Error: could not deliver notification_

**Comment by dominicsavb** [comment]
I face same problem...

**Comment by Salakar** [comment]
Sorry; please correctly fill out the issue template, without this, it's hard to help you.

Locking and closing this issue. Please raise another issue that correctly follows the issue template, thank you.
