### ISSUE TITLE
Error while task transformDexArchiveWithExternalLibsDexMergerForDebug is running

### ISSUE THREAD

**Issue by fernandomatheus** [invertase/react-native-firebase#1685]
Task **:app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED**
D8: Program type already present: com.google.firebase.analytics.connector.AnalyticsConnector$ConditionalUserProperty

What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/user/Desktop/project/project/android/app/build/intermediates/transforms/dexBuilder/debug/0.jar, /Users/username/Desktop/project/project/android/app/build/intermediates/transforms/dexBuilder/debug/1.jar
...

I'm getting this error when trying to run react-native run-android...

here is my android/build.gradle dependencies

```
dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.0.1'
    }
```

And my android/app/build.gradle dependencies

```
dependencies {
    compile project(':react-native-interactable')
    compile project(':react-native-firebase')
    compile project(':react-native-billing')
    compile project(':react-native-iap')
    compile project(':react-native-admob')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile "com.google.android.gms:play-services-base:15.0.1"
    
    compile "com.google.firebase:firebase-core:16.0.3"
    compile "com.google.firebase:firebase-config:16.1.0"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```

My app was working fine, and today for some reason I'm getting this errors. I already saw a lot of posts with similar problems but no success. I've tried to update the version `firebase-core` and `firebase-config` to the latest versions as mentioned here: https://firebase.google.com/support/release-notes/android

Does anybody know how to fix this ?

**Comment by alison-morgan** [comment]
Hey @fernandomatheus are you using npm or yarn?

**Comment by andreahaku** [comment]
I have the same problem and so far the only solution I've found is add that to the "gradle.properties" file:

`android.enableD8 = false`

**Comment by olbesp** [comment]
Try to add this line to your `android/app/build.gradle` file:
```
defaultConfig {
        ........
        multiDexEnabled true   // <--- this line
}
```

**Comment by andreahaku** [comment]
> Try to add this line to your `android/app/build.gradle` file:
> 
> ```
> defaultConfig {
>         ........
>         multiDexEnabled true   // <--- this line
> }
> ```

In my case, it was already there and the only solution has been to modify the ```gradle.properties```. If anyone has a better solution it's more than welcome as this give a bunch of deprecation warnings.

**Comment by fernandomatheus** [comment]
Thank you for everyone, I have been stuck in this problem for two days but none of solutions above worked for me. Just reading this article could open my mind to solve the problem, and it worked!: https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f 
I hope this article could help someone else.
