### ISSUE TITLE
how to change Notification icon?

### ISSUE THREAD

**Issue by lizhuoyuan** [invertase/react-native-firebase#1686]
## Issue

 
![image](https://user-images.githubusercontent.com/15923901/48543571-c9cf2a80-e8fc-11e8-9ccd-87d4e3bb7f4f.png)

 

android

  
![image](https://user-images.githubusercontent.com/15923901/48543662-f84d0580-e8fc-11e8-917f-2ac1b5f6e1de.png)
I want to change this , but I did not find a function

**Comment by Ehesp** [comment]
Can we see your resource directory? Will be in the android directory.

**Comment by lizhuoyuan** [comment]
![image](https://user-images.githubusercontent.com/15923901/48544750-46fb9f00-e8ff-11e8-956b-8f817cd7e9dd.png)

of course . 
I think may the problem with the picture

**Comment by Ehesp** [comment]
If you can, open Android Studio, then follow this guide: https://developer.android.com/studio/write/image-asset-studio#notification

It'll generate them for you in the correct locations / sizes.

**Comment by lizhuoyuan** [comment]
thanks

**Comment by developersahab** [comment]
I found solution by adding below code in AndroidManifest.xml:
`<application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" android:theme="@style/AppTheme">
. . . .
. . . .
. . . .
    <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
 </application>`

Before generate icon please keet it in mind logo should have `transparent background` 
Generate notification icons [link ](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=clipart&source.clipart=ac_unit&source.space.trim=1&source.space.pad=0&name=ic_stat_ac_unit)of all sizes and put the icon name `notification_icon `and extract all `drawable-density/` folders inside res folder

**Comment by conka991** [comment]
> I found solution by adding below code in AndroidManifest.xml:
> `<application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" android:theme="@style/AppTheme"> . . . . . . . . . . . . <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" /> </application>`
> 
> Before generate icon please keet it in mind logo should have `transparent background`
> Generate notification icons [link ](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=clipart&source.clipart=ac_unit&source.space.trim=1&source.space.pad=0&name=ic_stat_ac_unit)of all sizes and put the icon name `notification_icon `and extract all `drawable-density/` folders inside res folder

hi here, Im usign react native firebase too, and Im trying to attach an image to the notification with the method "setBigPicture()". I follow the docs but im not getting any results :/....It would be nice if you can give what things you have to do to achieve this, like: folder where I have to put the img, if the image needs a transparent background..etc
Thanks in advance!!!
