### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbgl;

### ISSUE THREAD

**Issue by sujitsagar** [invertase/react-native-firebase#1688]
Java exception in 'NativeModules'

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbgl;
java.lang.Class.forName
    Class.java:453
java.lang.Class.forName
    Class.java:378
<unknown>
    com.google.firebase.iid.FirebaseInstanceId.zzm@:3
<unknown>
    com.google.firebase.iid.FirebaseInstanceId.zzl@:71
<unknown>
    com.google.firebase.iid.FirebaseInstanceId.<init>@:80
<unknown>
    com.google.firebase.iid.FirebaseInstanceId.<init>@:9
<unknown>
    com.google.firebase.iid.zzai.create@:10
com.google.firebase.components.zzh.zza
    SourceFile:28
<unknown>
    com.google.firebase.components.zzi.get@:4
com.google.firebase.components.zzh.get
    SourceFile:39
<unknown>
    com.google.firebase.components.ComponentContainer$$CC.get@:15
com.google.firebase.components.zzd.zza
    SourceFile:68
com.google.firebase.FirebaseApp.zze
    SourceFile:703
com.google.firebase.FirebaseApp.initializeApp
    SourceFile:328
com.google.firebase.FirebaseApp.initializeApp
    SourceFile:294
com.google.firebase.FirebaseApp.initializeApp
    SourceFile:281
com.google.firebase.provider.FirebaseInitProvider.onCreate
    SourceFile:37
android.content.ContentProvider.attachInfo
    ContentProvider.java:1917
android.content.ContentProvider.attachInfo
    ContentProvider.java:1892
com.google.firebase.provider.FirebaseInitProvider.attachInfo
    SourceFile:31
android.app.ActivityThread.installProvider
    ActivityThread.java:6239
android.app.ActivityThread.installContentProviders
    ActivityThread.java:5805
android.app.ActivityThread.handleBindApplication
    ActivityThread.java:5722
android.app.ActivityThread$H.handleMessage
    ActivityThread.java:1656
android.os.Handler.dispatchMessage
    Handler.java:106
moduleAndStatics
    apps.js:190:42
Firebase
    firebase.js:45:47
<unknown>
    firebase.js:97:20
loadModuleImplementation
    require.js:191:12
guardedLoadModule
    require.js:138:36
_require
    require.js:118:20
<unknown>
    index.js:1
loadModuleImplementation
    require.js:191:12
guardedLoadModule
    require.js:138:36
_require
    require.js:118:20
<unknown>
    Splash.js:18
loadModuleImplementation
    require.js:191:12
guardedLoadModule
    require.js:138:36
_require
    require.js:118:20
<unknown>
    App.js:24
loadModuleImplementation
    require.js:191:12
guardedLoadModule
    require.js:138:36
_require
    require.js:118:20
<unknown>
    index.android.js:14
loadModuleImplementation
    require.js:191:12
guardedLoadModule
    require.js:131:45
_require
    require.js:118:20
global code
    
## Build.grade file
 implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:27.0.1"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation "com.google.android.gms:play-services-base:16.0.1"
    implementation 'com.google.firebase:firebase-core:16.0.4'
    implementation 'com.google.firebase:firebase-messaging:12.0.1'
    implementation "com.google.firebase:firebase-auth:16.0.5"

**Comment by Ehesp** [comment]
When you build? When you call a JS function? Please follow the issue template and we'll be able to help.

**Comment by sujitsagar** [comment]
This happens when I run the app after a successful build with "react-native run-android"

Here is my app level build.gradle
`buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
        classpath 'com.google.gms:google-services:4.0.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
           url 'https://maven.google.com'
        }
        maven {
            url "https://jitpack.io"
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        
        
    }
}
`
