### ISSUE TITLE
Blocking JS Thread When Loading

### ISSUE THREAD

**Issue by SteffeyDev** [invertase/react-native-firebase#169]
I have noticed that when I query the realtime database (using ref.on('value', ...)), it blocks the user interface from doing things like going back.  When I load a view and press the back button immediately, it doesn't respond until after the callback from the ref.on call is called.  I am not sure if this is usual behavior but as this is supposed to be running on its own thread, it seams odd for it to be blocking.  I only tested on iOS, but I imagine the same issue occurs on Android as well.

**Comment by Salakar** [comment]
Could you provide some sample code / a view of the type of data you're trying to query - might shed some light.

It's a weird one though, the JS side literally just forwards on/receives data to/from native over the RN bridge - so the only way I see this blocking is if something is hammering the bridge with events. 

cc @chrisbianca @Ehesp

**Comment by Ehesp** [comment]
How come you closed this?

**Comment by SteffeyDev** [comment]
Sorry, for some reason it started working, so I'm assuming it was an issue with RN or my configuration at the time, and not with this library.  I will re-open if the issue re-surfaces and I have time to investigate further.

**Comment by chrisbianca** [comment]
I assume that this is less visible because of the changes to fix: https://github.com/invertase/react-native-firebase/issues/171

However, we should keep an eye out in case there are any more fundamental issues around thread blocking.
