### ISSUE TITLE
Storing audio in storage

### ISSUE THREAD

**Issue by Linoa65** [invertase/react-native-firebase#1691]
## Issue

Hello !
I'm facing a problem, I want to use Firebase Storage with react-native to store files. It works perfectly to store an image, then, to get it back, everything's fine.
I tried to make the same to store an audio file (mp3) and it seems the file it stored. But when I try to read it with browser or with my app, it appears the audio is broken and unreadable.

After hours of research, I learn that firebase storage is not supported for some kind of files. I need help to understand why the audio is broken. I think it is possible to get data back, then decode them to get my audio readable. I saw some people store pure blob data into Cloud Firestore, it works, but I think is not a really good practice with Firestore.

Maybe is it possible to make it readable with some metadata, I'm just supposing.
Did you think you will implement this feature one day ? I'm just asking :)

Thanks to the team to make awesome job with this framework,
Florient

This is how I store my file :

```javascript
storeSound(file: string, user: string): Promise {
        return this.storage.child("sounds/" + user + "-" + Date.now() + ".mp3").putFile(file, {
            contentType: "audio/mpeg",
        });
    }
```

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by Salakar** [comment]
If you're able to, can you provide a sample MP3 file that works, to help the maintainers debug, thanks

**Comment by Linoa65** [comment]
Hello,

Thanks for your answer, it seems I sent an incorrect mp3 file, so, store works good, but file is broken. Then I verified and I sent a correct sound .mp3, but Task end with the classic "An unknown error as occurred". 
How can I store my file ? Even if I need to convert him before, then convert it back after it's not a problem, I just want to have advices on the best implementation possible of this case.
Store works with image, is it possible to make storage believe its a file type X then allow it to store ?

Thanks

**Comment by Ehesp** [comment]
@Linoa65 	are you setting a content-type in the meta data?

**Comment by Linoa65** [comment]
@Ehesp Yes ! Look at my storeSound method, I give the second parameter with contentType: "audio/mpeg" (I tried to set audio/mp3 but has no effect)

**Comment by Linoa65** [comment]
Hello,

I'm always facing this issue. Is there a way to convert my file and send a blob file for example, then decode it when I receive it ?
When I try to putFile my .mp3, I get this error : {framesToPop: 1, code: 'storage/unknown'}.

Thanks

**Comment by Salakar** [comment]
@Linoa65 could you also show your storage rules if possible, thanks

**Comment by tanayjain14** [comment]
@Linoa65 hey did you figure out how to upload files to firebase storage using react native firebase?

**Comment by Subiyel** [comment]
anyone successful for uploading audio?

**Comment by Rupenieks** [comment]
Also looking to upload / download audio. Not sure how to proceed. I can get the download URL from the file but how do I download the actual file afterwards? The google documentation only shows setting an img src to the download URL but this doesn't apply to any other media.

**Comment by mikehardy** [comment]
https://github.com/invertase/react-native-firebase/blob/3e980d4bb5fbaeefc045f2427a9e0cc0b153af6e/packages/storage/e2e/StorageTask.e2e.js#L43-L52

?

**Comment by fbotalla** [comment]
has anyone been able to solve this?

**Comment by mikehardy** [comment]
@fbotalla with apologies "this" is a 3.5 year old issue with a few different comments on it asking slightly different things, not an efficient way to get help as it's ambiguous and without detail. Our e2e tests (as linked / displayed above) exercise nearly every way to do anything with the APIs and you should check them in concert with the usage / reference docs on rnfirebase.io to see how to use the APIs. Failing that I would check stackoverflow, and if you discover an issue where the module is really just not working and you think there is an actionable bug - post a new issue here with details and an App.js that demonstrates the issue - https://stackoverflow.com/help/mcve
