### ISSUE TITLE
 🔥Can't find common super class when Build with proguard-android-opitmize

### ISSUE THREAD

**Issue by ducNgbk** [invertase/react-native-firebase#1700]
## Issue

Hi, I am trying to build Android app with Proguard
However, I am stuck with this problem:
- Build works fine when I use `proguard-android.txt`
- When I change to `proguard-android-opitmize.txt` to remove log and other things. Below error happened
Looking for your help
Thank you a lot in advance
```
Optimizing (pass 1/5)...
Unexpected error while evaluating instruction:
  Class       = [io/invertase/firebase/messaging/RNFirebaseMessagingService]
  Method      = [onMessageReceived(Lcom/google/firebase/messaging/RemoteMessage;)V]
  Instruction = [74] invokestatic #12
  Exception   = [java.lang.IllegalArgumentException] (Can't find common super class of [io/invertase/firebase/messaging/RNFirebaseMessagingService] (with 1 known super classes) and [android/content/ContextWrapper] (with 3 known super classes))
Unexpected error while performing partial evaluation:
  Class       = [io/invertase/firebase/messaging/RNFirebaseMessagingService]
  Method      = [onMessageReceived(Lcom/google/firebase/messaging/RemoteMessage;)V]
  Exception   = [java.lang.IllegalArgumentException] (Can't find common super class of [io/invertase/firebase/messaging/RNFirebaseMessagingService] (with 1 known super classes) and [android/content/ContextWrapper] (with 3 known super classes))
Warning: Exception while processing task java.io.IOException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Can't find common super class of [io/invertase/firebase/messaging/RNFirebaseMessagingService] (with 1 known super classes) and [android/content/ContextWrapper] (with 3 known super classes)
Thread(Tasks limiter_3): destruction
```
---

## Project Files

Android: `android/build.gradle`
```
buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 19
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
        classpath 'com.google.gms:google-services:4.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}


task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}
```
Android: `android/app/build.gradle`

```
....
def enableProguardInReleaseBuilds = true
...
buildTypes {
        release {
            debuggable false
            signingConfig signingConfigs.release
            shrinkResources enableProguardInReleaseBuilds
            minifyEnabled enableProguardInReleaseBuilds
            useProguard enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
...
```
Android `proguard-rules.pro`
```
# React Native

# Keep our interfaces so they can be used by other ProGuard rules.
# See http://sourceforge.net/p/proguard/bugs/466/
-keep,allowobfuscation @interface com.facebook.proguard.annotations.DoNotStrip
-keep,allowobfuscation @interface com.facebook.proguard.annotations.KeepGettersAndSetters
-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

# Do not strip any method/class that is annotated with @DoNotStrip
-keep @com.facebook.proguard.annotations.DoNotStrip class *
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.proguard.annotations.DoNotStrip *;
    @com.facebook.common.internal.DoNotStrip *;
}

-keepclassmembers @com.facebook.proguard.annotations.KeepGettersAndSetters class * {
  void set*(***);
  *** get*();
}

-keep class * extends com.facebook.react.bridge.JavaScriptModule { *; }
-keep class * extends com.facebook.react.bridge.NativeModule { *; }
-keepclassmembers class *  { @com.facebook.react.uimanager.UIProp <fields>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactProp <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactPropGroup <methods>; }

-dontwarn com.facebook.react.**

# TextLayoutBuilder uses a non-public Android constructor within StaticLayout.
# See libs/proxy/src/main/java/com/facebook/fbui/textlayoutbuilder/proxy for details.
-dontwarn android.text.StaticLayout

# okhttp

-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

# okio

-keep class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-dontwarn okio.**

# react-native-firebase

-keep public class me.leolin.shortcutbadger.* { public *; }
-dontwarn me.leolin.shortcutbadger.**

-keep class io.invertase.firebase.** { *; }
-dontwarn io.invertase.firebase.**

# remove debugging log

-assumenosideeffects
 class android.util.Log {
 public static *** d(...);
 public static *** i(...);
 public static *** v(...);
}
```
## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - ` Android API 27` 
- **Operating System:**
  - [x] MacOS, version: `10.14.1`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Android Studio 3.2`
- **`React Native` version:**
  - `0.57.2`
- **`React Native Firebase` library version:**
  - `5.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - [] **N/A**
  - [x] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

**Comment by ducNgbk** [comment]
Hi everyone,
Is there any solution or workaround for this problem yet?

**Comment by ducNgbk** [comment]
Hi everyone,
It's quite a long time since I posted this issue.
Is there any solution or workaround for this problem yet?
Thanks a lot for your awesome library

**Comment by logout0607** [comment]
After the Cordova-android 12.0.x update, the following problems occur when running proguard. Do you have a solution?

Unexpected error while evaluating instruction:
  Class       = [com/mxp/command/appcomm/bridge/BAppComm]
  Method      = [removeList(Lcom/mxp/api/MxpActivity;Ljava/lang/String;Ljava/util/ArrayList;)V]
  Instruction = [6] invokevirtual #218 = Methodref(com/mxp/command/appcomm/MAppComm.removeList(Landroid/content/Context;Ljava/lang/String;Ljava/util/ArrayList;)V)
  Exception   = [proguard.evaluation.IncompleteClassHierarchyException] (Can't find common super class of [com.mxp.api.MxpActivity] (with 2 known super classes: org.apache.cordova.CordovaActivity, com.mxp.api.MxpActivity) and [android.content.Context] (with 2 known super classes: android.content.Context, java.lang.Object))
