### ISSUE TITLE
Typescript: TaskEvent does not exist on '{ (): Storage; nativeModuleExists: boolean; }'

### ISSUE THREAD

**Issue by bmatcuk** [invertase/react-native-firebase#1706]
## Issue
I've pretty much duplicated the "Listener Example" for [Storage.Reference.putFile](https://rnfirebase.io/docs/v5.x.x/storage/reference/Reference#putFile) in my code. While the code works just fine, Typescript is complaining on the line `firebase.storage.TaskEvent.STATE_CHANGED` with the error:

```
Property 'TaskEvent' does not exist on type '{ (): Storage; nativeModuleExists: boolean; }'.
```

Seems the typescript definitions may be slightly out of sync?

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Typescript`
- **`React Native` version:**
  - `0.57.4`
- **`React Native Firebase` library version:**
  - `5.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [x] Storage
- **Are you using `TypeScript`?**
  - [ ] No
  - [x] Yes, version: `3.1.6`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by JanOwiesniak** [comment]
Just want to let you know that i'm running into a similar TypeScript issue.

**Code**

```
const persistPath = `${firebase.storage.Native.DOCUMENT_DIRECTORY_PATH}/${refPath}`;
```

**Error**

```
Property 'Native' does not exist on type '{ (): Storage; nativeModuleExists: boolean; }'.
```

**Comment by Salakar** [comment]
Hey both, thanks for reporting these, looks like the types need updating for storage. If anyone feels like helping out and submitting a PR to add these that'd be great, they can be found here: https://github.com/invertase/react-native-firebase/blob/master/src/index.d.ts

Otherwise, I'll get them looked at for v5.2.0.
