### ISSUE TITLE
You attempted to set the key `_user` with the value `{"metadata":{...}}` on an object that is meant to be immutable and has been frozen.

### ISSUE THREAD

**Issue by nanndoj** [invertase/react-native-firebase#1712]
I am facing this error when I try to call the confirm method from phone authentication. It was working fine some time ago (not sure how long)

````
You attempted to set the key `_user` with the value `{"metadata": ... }` on an object that is meant to be immutable and has been frozen.
````

The error is thrown from this line https://github.com/invertase/react-native-firebase/blob/512012179763042ef81aad68571838e85f7bf1f5/src/modules/auth/index.js#L119 and happens right after the confirmation result returns.

**Courious fact**
After some investigation I see that the error starts when the callback from phone confirmation is called:
 https://github.com/invertase/react-native-firebase/blob/85321b5246fc313b409116617d19636ab3029adf/src/modules/auth/phone/ConfirmationResult.js#L32

But the same code works fine when `_setUser` is called from this line
https://github.com/invertase/react-native-firebase/blob/512012179763042ef81aad68571838e85f7bf1f5/src/modules/auth/index.js#L75

**Environment**
React Native : `0.57.1`
React Native Firebase: `5.1.1`

**Comment by nanndoj** [comment]
This error only appears on the Debug version. I can confirm that the Release build works fine.

**Comment by tannera** [comment]
```
You attempted to set the key `id` with the value `"565355532"` on an object that is meant to be immutable and has been frozen.
``` 

 Lost a couple of hours trying to debug where this issue was originating for me. In my case, it turns out it's from firebase.analytics().logEvent("edge_event_1", {
info: error1Object,
}) where error1Object contains a property with a large array of objects (>100 objects). Each object has an id. 

Logging the object without that large array property fixed it.

**Comment by nanndoj** [comment]
The problem still happening. I am generating a production version to authenticate on the first time, as workaround. Then I generate a debug building and continue working

**Comment by altany** [comment]
This is happening for me when passing a small array of no more than 6 elements, sometimes even just 2. Removing the array fixes it.

This issue should not be closed.

**Comment by mikehardy** [comment]
@altany can you open a new issue following the issue template? I can't even contemplate the changes in the code since it was closed almost 2 years ago, so knowing the context containing your experience of the error will help triage
