### ISSUE TITLE
signInWithCustomToken error: auth/invalid-custom-token

### ISSUE THREAD

**Issue by chienvu123** [invertase/react-native-firebase#1713]
- i have used firebase.auth().signInWithCustomToken(token).
- token: when i login success => user => token = user.getIdToken()
=> error: auth/invalid-custom-token. The custom token format is incorrect. Please check the documentation...

- anybody help me, please!
-------
- **android/app/build.gradle**
implementation project(':react-native-firebase')
    implementation "com.google.firebase:firebase-core:16.0.1"
    implementation "com.google.firebase:firebase-storage:15.0.2"
    implementation "com.google.firebase:firebase-auth:16.0.2"
    implementation "com.google.firebase:firebase-database:16.0.1"
    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation 'com.google.android.gms:play-services-maps:15.0.0' 
...
 apply plugin: 'com.google.gms.google-services'
- **android/build.gradle**
classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'com.google.gms:google-services:3.2.1'
-------
- **version:**
"react": "16.3.1",
    "react-native": "0.55.4",
 "react-native-firebase": "^4.1.0",

** thanks all**

**Comment by Ehesp** [comment]
Please could you show us your code usage?

**Comment by telmen** [comment]
Hi @chienvu123, how did you resolve this?

**Comment by jerearaujo03** [comment]
Did you solved it?

**Comment by idkc-aios** [comment]
I had the same problem creating my custom token.

In the documentation it says that the expiration date and time (**exp**) must be a **maximum 3,600 seconds** later than the emission time (**iat**), where I put it to expire in 7 days, change to 1 hour and it worked without problems.

I hope this helps you

**Comment by SameeraMadushan** [comment]
Hi, Is this method still valid?
Seems it's deprecated with the new package @react-native-firebase/auth

**Comment by mikehardy** [comment]
Hmm it either exists (and should work, even if deprecated) or it is gone. 

Most of these problems are because Android auto-signs-you-in at the firebase-android-sdk level but the app attempts to use the token anyway instead of listening the user auth changed callback
