### ISSUE TITLE
Guide improve: onMessage() will not be called until implementing didReceiveRemoteNotification

### ISSUE THREAD

**Issue by jordenchang55** [invertase/react-native-firebase#1714]
## Issue
To add messaging feature, I followed each step in the guide of Cloud Messaging module.
But I found that if the `didReceiveRemoteNotification` function in AppDelegate is not implemented, then the data-only messages will not trigger `firebase.messaging().onMessage()` for both foreground and background.
After implementing the function, everything works as expected.
However, the implementation of `diddidReceiveRemoteNotification` function is only mentioned in the guide of Notification module and it should also be written into the guide of Cloud Messaging.  

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:
```ruby
# Required by RNFirebase
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
  pod 'Firebase/RemoteConfig', '~> 5.11.0'
```

#### `AppDelegate.swift`:

```swift
class AppDelegate : UIResponder,UIApplicationDelegate {
  // Create the base window
  var window : UIWindow? = UIWindow(frame: UIScreen.main.bounds)
  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    FirebaseApp.configure();
    RNFirebaseNotifications.configure();
    
    let jsCodeLocation = RCTBundleURLProvider.sharedSettings()?.jsBundleURL(forBundleRoot: "index", fallbackResource: nil);
    let rootView = RCTRootView(bundleURL:jsCodeLocation!, moduleName: "Croxera", initialProperties: nil, launchOptions:launchOptions);
    self.window = UIWindow(frame: UIScreen.main.bounds);
    let rootViewController = UIViewController()
    rootViewController.view = rootView;
    
    self.window!.rootViewController = rootViewController;
    self.window!.makeKeyAndVisible();
    return true;
  }
  
  func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
// Add this line make onMessage() work
    RNFirebaseNotifications.instance().didReceiveRemoteNotification(userInfo, fetchCompletionHandler: completionHandler);
  }
}
```

## Environment

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `iOS 12.1`
- **Operating System:**
  - [x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`

**Comment by PrimeTimeTran** [comment]
Yes on this! I'm not receiving onMessage as well.

**Comment by russelarms** [comment]
The guide for ios seems to be incomplete.
