### ISSUE TITLE
Could you add resolveShortLink feature?

### ISSUE THREAD

**Issue by sinhpn92** [invertase/react-native-firebase#1716]
I'm looking for `resolveShortLink` feature but i cannot find any document or code for to do it. 
Could you please add this feature into the lib?

Thanks!

**Comment by Salakar** [comment]
Hey @sinhpn92 please could you make a request on our feature request board; https://boards.invertase.io/react-native-firebase - could you also provide links to the native iOS & Android methods for this if possible, e.g. like [this](https://boards.invertase.io/react-native-firebase/p/firebase-analytics-expose-resetanalyticsdata) feature request does.

Thank you

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
