### ISSUE TITLE
🔥Anonymous Auth : currentUser metadata lastSignInTime never updated

### ISSUE THREAD

**Issue by mpalmerlee** [invertase/react-native-firebase#1717]
## Issue
I've upgraded an app from react-native-firebase 4.3.6 to 5.1.1 and I'm noticing in 5.1.1 using the anonymous login provider the user.metadata.lastSignInTime is never updated (it is always the same value as user.metadata.creationTime). I've been using those metadata properties to determine if we have a new or returning user.

My code is similar to this:
```
async componentDidMount() {
    this.unsubscribe = firebase.auth().onAuthStateChanged(async user => {
       await this.anonymousLogin(user);
       ...
    });
}

async anonymousLogin(currentUser) => {
  try {
    console.log("currentUser passed in:", currentUser, JSON.stringify(currentUser));
    if (!currentUser) {
      currentUser = await firebase.auth().signInAnonymously();
    }
    console.log("currentUser:", currentUser, JSON.stringify(currentUser));
  } catch (error) {
    console.log("anonymousLogin error:", error);
    throw error;
  }
};
```
This outputs my user data:
```
{"displayName":null,"phoneNumber":null,"photoURL":null,"refreshToken":"...","providerData":[],"providerId":"firebase","uid":"...","emailVerified":false,"email":null,"isAnonymous":true,"metadata":{"lastSignInTime":1543083075000,"creationTime":1543083075000}}
```
Always lastSignInTime === creationTime

As noted above, prior to RNFB version 5.x this was working fine

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/Firestore', '~> 5.11.0'
pod 'Firebase/Auth', '~> 5.11.0'
```

#### `AppDelegate.m`:

```objc
#import <Firebase.h>
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  NSURL *jsCodeLocation;
...
```

---

#### `android/build.gradle`:

```groovy
...
buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 21
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
        classpath 'com.google.gms:google-services:4.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
...
```

#### `android/app/build.gradle`:

```groovy
...
dependencies {
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-gesture-handler')
    implementation project(':react-native-firebase')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules


    // RNFirebase required dependencies
    implementation "com.google.firebase:firebase-core:16.0.4"
    implementation "com.google.android.gms:play-services-base:16.0.1"

    implementation "com.google.firebase:firebase-firestore:17.1.2"
    implementation "com.google.firebase:firebase-auth:16.0.5"
}
...
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [x] MacOS, version: `High Sierra 10.13.6`
  - [ ] Windows, version: `N/A`
  - [x] Other, please specify: `Ubuntu 18.04`
- **Build Tools:**
  - `Xcode 10.1`
- **`React Native` version:**
  - `0.57.4`
- **`React Native Firebase` library version:**
  - `5.1.1`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [x] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by Ehesp** [comment]
Had a quick look at this one, nothing glaringly obvious standing out so will be investigated.

**Comment by mpalmerlee** [comment]
I still have this issue, I can work around it by making a call out to firestore to see if a profile exists for that user to determine if the user is new or returning.

**Comment by pehagg** [comment]
@mpalmerlee , see https://github.com/firebase/firebase-js-sdk/issues/662.

**Comment by mpalmerlee** [comment]
Thanks for the pointer @pehagg, I'm not sure it's the same issue since I never see the field updated, even if the same user returns the next day. Does RNF use the firebase-js-sdk and therefore you are thinking it is the same issue? Or perhaps you are thinking I can use the `userCredential.additionalUserInfo.isNewUser` field like this linked issue suggests? Also note that this was working fine with RNF 4.x and seemed to start being an issue for me with RNF 5.x, not sure if that is also related to a new version of the firebase-js-sdk.

**Comment by erikvdplas** [comment]
@mpalmerlee ever found a proper solution?

**Comment by mpalmerlee** [comment]
Hey @erikvdplas, no I haven't looked at this since I worked around it or re-tested it with new versions of RNFB.

**Comment by haris-aqeel** [comment]
I am facing the same issue. I am authenticating user with custom email and password and it seems like lastSignInTime never changes. I logged out and login again after sometime, but it still shows me the same signInTime.
![image](https://user-images.githubusercontent.com/56465230/235960047-4f948584-ed2a-498a-8a85-57b26868b00f.png)
