### ISSUE TITLE
Support Crashlytics advanced user identifier features

### ISSUE THREAD

**Issue by rimzici** [invertase/react-native-firebase#1719]
Please add support for:

void Crashlytics.setUserName(String name);
void Crashlytics.setUserEmail(String email);

Request at boards [here](https://boards.invertase.io/react-native-firebase/p/support-crashlytics-advanced-user-identifier-features)

**Comment by Ehesp** [comment]
Tracking on https://boards.invertase.io/react-native-firebase/p/support-crashlytics-advanced-user-identifier-features
