### ISSUE TITLE
Pod install warnings: The `MyProject [Release]` target overrides the `FRAMEWORK_SEARCH_PATHS` 

### ISSUE THREAD

**Issue by lazyhoneyant** [invertase/react-native-firebase#172]
Pod install, I’ve encountered warnings related to ‘target overrides’
Some of this warnings disappeared by the solution on Manual. ( Add Other Linker Flags to all targets )

But Some warning still remains. 

> The `MyProject [Release]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-MyProject/Pods-MyProject.release.xcconfig'. This can lead to problems with the CocoaPods installation
> 
> The `MyProject [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-MyProject/Pods-MyProject.release.xcconfig'. This can lead to problems with the CocoaPods installation

How can I resolve this problem?

**Comment by chrisbianca** [comment]
@lazyhoneyant out of interest, what did you do to resolve this? If it's RN-Firebase related I can add it to the documentation...

**Comment by lazyhoneyant** [comment]
@chrisbianca I don't know what was the problem. But remove all the files and install again, It works. Thank you for the reply. :)

**Comment by lazyhoneyant** [comment]
@chrisbianca I've encountered this issue again. But I don't know why it happens. If I find out something from the issue, I will write it again here.

**Comment by lazyhoneyant** [comment]
@chrisbianca  I’ve solved this.

Open Xcode, Select my project, Search for ‘FRAMEWORK_SEARCH_PATHS’, and then add $(inherited).

**Comment by Ehesp** [comment]
@lazyhoneyant when you create a new RN project (`react-native init`) I believe this already comes as the default.

**Comment by lazyhoneyant** [comment]
@Ehesp I didn't know that. Maybe that is replaced by Installing FBSdk or something else. thx for pointing out.
