### ISSUE TITLE
🔥[Android >=8.0] Notifications: No Channel found (channelId) on newly created notification channel

### ISSUE THREAD

**Issue by ecexplorer** [invertase/react-native-firebase#1727]
## Issue

In the same app session, if I create a new notification channel (and corresponding ID) using the api firebase.notifications().android.createChannel(), and then try to use that channel ID to display a notification firebase.notifications().displayNotification(), I get:
E NotificationService: No Channel found for pkg=com.relaygo.spectre.companion, channelId=poke-3wWzrYhd6g3cQN6y, id=266221012, tag=null, opPkg=com.relaygo.spectre.companion, callingUid=10128, userId=0, incomingUserId=0, notificationUid=10128, notification=Notification(channel=poke-3wWzrYhd6g3cQN6y pri=1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x11 color=0xff66cccc category=msg groupKey=poke-$all$ number=0 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)

As soon as I remove the app from memory (swipe it away), and bring it back into focus, it works just fine. I've also confirmed that as soon as I call createChannel(), the new notification channel properly shows in android settings. Based on looking at the code, I actually think this may be an Android bug, but confirmation & knowledge of where to report that would be helpful :)

## Project Files

- Android: android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java
- Android: android/src/main/java/io/invertase/firebase/notifications/DisplayNotificationTask.java

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `Android 8.0 or higher`
- **`React Native` version:**
  - `0.57.5`
- **`React Native Firebase` library version:**
  - `5.1.1`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [x] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

**Comment by ecexplorer** [comment]
Sorry, this was a blunder on my part, channel id was not being set as expected

**Comment by adityajhordanbapr** [comment]
Hi, @ecexplorer How you solve it ? I face the same problem right now, no luck for me :(

**Comment by ecexplorer** [comment]
In android, for every notification that you have, you have to assign it to a notification channel. Channels  can be created using the Android-specific API. Look here: https://github.com/invertase/react-native-firebase-docs/blob/master/docs/notifications/android-channels.md
After ensuring your channel exists (you can check this in Android Settings), you should be able to show a notification that is associated with that channel.
