### ISSUE TITLE
Google login using signInWithCredential is wrong

### ISSUE THREAD

**Issue by skleest** [invertase/react-native-firebase#173]
For Google login, it looks like I have to use Google's `id_token` as `credentials.authToken` and `accessToken` as `credentials.secret`. Working with this workaround.

Using: `credential = firebase.auth.GoogleAuthProvider.credential(accessToken);` as instructed will also fail.

**Comment by Salakar** [comment]
Not sure on the issue here? Auth provides the ability to have both arguments, see: https://github.com/invertase/react-native-firebase/blob/master/lib/modules/auth/providers/Google.js#L2

**Comment by BuffMcBigHuge** [comment]
Try `auth()`. 

I had the same issue with Facebook, without the function notation, it worked on Android, but not iOS.

**Comment by skleest** [comment]
It's the naming convention that confuses--for Facebook, you have to use:
`credential = firebase.auth.FacebookAuthProvider.credential(accessToken);`
For Google, you have to use:
`credential = firebase.auth.GoogleAuthProvider.credential(idToken, accessToken);`
Whereas the more obvious way would be switch idToken and accessToken for Google login. Since this wasn't documented, took me a while to figure out.

Problem is here: https://github.com/invertase/react-native-firebase/blob/master/ios/RNFirebase/RNFirebaseAuth.m#L452
Google is accepting `authToken` as `idToken` and `authTokenSecret` as `accessToken`. This is inconsistent--maybe switching the two would work better/
Haven't checked on Android yet.

**Comment by chrisbianca** [comment]
@skleest this is by design as it matches the web SDK for `FacebookAuthProvider.credential` (https://firebase.google.com/docs/reference/js/firebase.auth.FacebookAuthProvider#.credential) and `GoogleAuthProvider.credential` (https://firebase.google.com/docs/reference/js/firebase.auth.GoogleAuthProvider#.credential).

I appreciate that this isn't documented explicitly with react-native-firebase, something that we'll be improving in the near future, but in the meantime just assume that it matches the web SDK.

**Comment by skleest** [comment]
@chrisbianca my fault not noticing that from web sdk--hope this helps others who may be confused!

**Comment by Jmiguel14** [comment]
> For Google login, it looks like I have to use Google's `id_token` as `credentials.authToken` and `accessToken` as `credentials.secret`. Working with this workaround.
> 
> Using: `credential = firebase.auth.GoogleAuthProvider.credential(accessToken);` as instructed will also fail.

The same problem, I had to pass the two credentials and it worked.
