### ISSUE TITLE
Cloud firestore session persistence

### ISSUE THREAD

**Issue by visagegod** [invertase/react-native-firebase#1730]
## Issue

I am trying to enable persistence for specific cloud firestore collections so that when the app is closed and then reopened I do not need to load the data directly from Firebase again. 

(Much like authentication in the app with no network connection)

---

## Use case

I have a collection called 'users-info' that holds details such as Firstname and Avatar. When the app is opened with no network connection the user is authenticated and can see their profile with the user-info doc for their account.

Is this possible using react-native-firebase? 

Many thanks :+1:

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

**Comment by james-berry** [comment]
+1, I would also like to know this!

**Comment by james-berry** [comment]
any info on this?

**Comment by Ehesp** [comment]
Unfortunately the only reference I can find to persistence is for the entire app, which is currently exposed ([link](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestoreSettings.Builder.html#setPersistenceEnabled(boolean))). Looks like it isn't possible for specific collections I'm afraid.

**Comment by pdSatyam** [comment]
@Ehesp . Is offline persistence enables on  cloud firestore   with react native?

**Comment by dsernst** [comment]
@Ehesp: Those linked docs (https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestoreSettings.Builder.html#setPersistenceEnabled(boolean)) say this is enabled by default, but that doesn't seem to be the case in `react-native-firebase@6`. 

Is it expected to be on?
