### ISSUE TITLE
analytics().logEvent does not seem to be working on Android

### ISSUE THREAD

**Issue by dannycochran** [invertase/react-native-firebase#174]
**Expected Behavior**

This code should log an event "myEvent":

```javascript
import RNFirebase from 'react-native-firebase';

const firebaseApp = RNFirebase.initializeApp({ debug: false });
firebaseApp.analytics().logEvent("myEvent");
```

**Actual Behavior**

I don't see "myEvent" anywhere in my Firebase dashboard analytics. Other, default Firebase events, such as "app_open", "session_start" are all being recorded, and I believe that's happening from react-native-firebase.

**Build:**

- RN: 0.45.0
- RN-Firebase: 1.1.0
- Emulator: Nexus 5X API 25

**Praise**

This library is so much nicer than using the WebSDK, thank you for all your work.

**Comment by chrisbianca** [comment]
Thanks @dannycochran, very kind of you to say!

Firebase analytics events can sometimes take a little while to come through on the dashboard.  You can however turn on debug view which should allow you to debug in realtime by following the instructions here: https://firebase.google.com/docs/analytics/debugview

Let me know if you're still having problems once you've tried debug mode and I can take another look.  Events are definitely working in my iOS and Android app at the moment...

**Comment by dannycochran** [comment]
Thanks @chrisbianca -- I see the events coming through in debug mode. It's now been about ~60 minutes and they're not showing up in the dashboard, that's normal?

**Comment by Ehesp** [comment]
Yeah that's normal. They can take hours annoyingly! Same with Performance Monitoring, takes yonks.

**Comment by dannycochran** [comment]
Gotcha, thanks for the quick responses & explanation.

**Comment by Ehesp** [comment]
I'll close this one, pretty sure it's working just firebase taking while. Let us know if there's any problems.

**Comment by Ehesp** [comment]
Beat me to it!

**Comment by chrisbianca** [comment]
@dannycochran for reference, what I've found is that when you first sending events it takes a while to come through then they generally come through a bit quicker after that.  Still nowhere near realtime though!!

**Comment by taeyzzz** [comment]
Hello

I use firebase analytic in both IOS and Android

in IOS i can see logevent after a fews hours but in android i can't see even default logevent 

so how to fix 

Thank you

**Comment by afadili** [comment]
Please where did you put your code to track your events ?

**Comment by taeyzzz** [comment]
i apologize for that. that's my fault. i use wrong credential that why it not work

thank you

**Comment by fardeenpanjwaniucmouli** [comment]
> Thanks @dannycochran, very kind of you to say!
> 
> Firebase analytics events can sometimes take a little while to come through on the dashboard. You can however turn on debug view which should allow you to debug in realtime by following the instructions here: https://firebase.google.com/docs/analytics/debugview
> 
> Let me know if you're still having problems once you've tried debug mode and I can take another look. Events are definitely working in my iOS and Android app at the moment...

I'm unable to see the log even with debug mode turned on. This is my code:
`Analytics.logEvent("Test_Log", {
                                                        email,
                                                        name
                                                    });`

where Analytics is being imported from this file:
`import firebase from "react-native-firebase";

let Analytics = firebase.analytics();

export default Analytics;
`

this is what the debug stream looks like for me:
![image](https://user-images.githubusercontent.com/52699227/63611562-c1c5b900-c5f9-11e9-90e3-ea49bc9e668c.png)

**Comment by mikehardy** [comment]
Maybe this is useful in the future. I use analytics like so (this is typescript)

I'm using current-as-of-now versions of everything (react-native 0.60.5, react-native-firebase v5.5.6, iOS Firebase SDK Pods 6.7.0, Android Firebase SDK BOM 2.20.0

contents of ./src/utilities/Analytics.ts
```typescript
import * as firebase from 'react-native-firebase';

/**
 * Easily log an analytics event. Guaranteed to succeed.
 * Will sanity check arguments for correctness vs underlying analytics provider,
 * and log errors (possibly via analytics if possible)
 *
 * @param name 40 character max alphanumeric and '_' only, starts with alpha
 * @param props keys 40 character max w/name content rules, values 100 character max
 */
function analyticsEvent(name: string, props?: Object | undefined): void {
  try {
    firebase.analytics().logEvent(name, props);
  } catch (e) {
    console.log('Unable to tag analytics event:', e);
  }
}

/**
 * Set user properties
 * @param props keys 24 char max alphanumeric and '_' only starts alpha, values 26 char max
 */
function setAnalyticsUserProperties(props: { [key: string]: string | null }): void {
  firebase.analytics().setUserProperties(props);
}

function setAnalyticsUser(id: string): void {
  firebase.analytics().setUserId(id);
}

function analyticsScreen(screenName: string): void {
  firebase.analytics().setCurrentScreen(screenName, screenName);
}

/**
 * Verify that we follow google rules for analytics string contents
 * If there is a problem it will have the side-effect of logging a reportable event
 * for followup to fix the problem
 * @param value string to verify
 * @param maxLength optional max length of the string, defaults to 40
 */
function checkAnalyticsString(value: string, maxLength: number = 40): boolean {
  let badEvent = 'errorInvalidAnalyticsEvent';
  if (value.length > maxLength) {
    firebase.analytics().logEvent(badEvent, { badKey: value.substr(0, maxLength - 1) });
    return false;
  }

  if (!/^[a-zA-Z][_a-zA-Z0-9]+$/.test(value)) {
    firebase.analytics().logEvent(badEvent, { badKey: value });
    return false;
  }

  return true;
}

export {
  analyticsEvent,
  setAnalyticsUserProperties,
  setAnalyticsUser,
  analyticsScreen,
  checkAnalyticsString,
};
```

Usage:
```typescript
import { analyticsEvent } from '../utilities/Analytics';

...
// inside some function somewhere
            analyticsEvent('updateDelayed');
// inside some other function
    analyticsEvent('onEnterPhoneNumber', { phoneNumber: phoneNumber });
```

It works for me ?

**Comment by fardeenpanjwaniucmouli** [comment]
Thanks for the quick reply! However, I'm not currently using TypeScript but is there anything wrong with the code that I have right now?

**Comment by mikehardy** [comment]
sorry I don't know - I've learned there are a million ways to do anything in javascript, and that coding and code review in the absence of testing it for real leads to long back and forths, so now I mostly just post one way to do that I've tested and know works, and if it's useful great, but otherwise I don't check posted code mostly in the interest of time - sorry

**Comment by mikehardy** [comment]
it's not fancy typescript though, the javascript analog should be just stripping the types I think and altering import style

**Comment by alisangi6456** [comment]
please tell how i create my own events
