### ISSUE TITLE
no errors are being logged to the firebase Crashlytics dashboard 

### ISSUE THREAD

**Issue by z3us94** [invertase/react-native-firebase#1746]
Hi everyone,

I know this issue has been out there for a while now.  But has anyone sorted this out? And I'm facing a strange kinda issue here my Crashlytics dashboard looks something like this.
![error-ss](https://user-images.githubusercontent.com/17064184/49736676-c7b87b80-fcb0-11e8-8980-7bbee11e2e22.png)

I followed the steps in the docs but still couldn't get this through. 
https://rnfirebase.io/docs/v4.0.x/installation/initial-setup this to install the core package and 
https://rnfirebase.io/docs/v5.x.x/crashlytics/reference/crashlytics to install the module.

my android/build.gradle looks like this,
![android_gradle](https://user-images.githubusercontent.com/17064184/49737207-406c0780-fcb2-11e8-9458-4149e43c1ead.png)

and my android/app/build.gradle looks like this,
![android_app_gradle](https://user-images.githubusercontent.com/17064184/49737256-62658a00-fcb2-11e8-8783-0308c6eb504c.png)

and these two lines are on top of the android/app/build.gradle file,
apply plugin: "com.android.application"
apply plugin: "io.fabric"

and used,
firebase.crashlytics().log('test crash'); to check the crash log.
But no luck so far. Is there something that im missing.
Thanks in advance.

**Comment by z3us94** [comment]
@Ehesp yeah figured that. I did test that with log() and recordError() methods. And yeah the records were appeared after like 24 hours but not all the errors that logged nor the crashes that I did use crash() method.

Also is there any way we could show react-native code in the stack trace on the dashboard error?

**Comment by kg-currenxie** [comment]
@z3us94 did you solve the issue with using `crash()` ?
