### ISSUE TITLE
AdMob Rewarded Video(Even Test Video) not loaded on iOS 

### ISSUE THREAD

**Issue by tusharmutreja** [invertase/react-native-firebase#1747]
Hey Everyone,

I am trying to Show rewarded video in IOS, But Every time I load the video I got the error Code: '"admob/error-code-no-fill"'.
Even not able to Load test Video.

`
import firebase from 'react-native-firebase';
import { EventRegister } from 'react-native-event-listeners';
import * as Constant from './../Common/Constant';

const advert = firebase.admob().rewarded(Constant.AddMob_UnitID);
const AdRequest = firebase.admob.AdRequest;
const request = new AdRequest();
export default class Admob {

    static inititalizeAdd(){
        firebase.admob().initialize(Constant.AddMob_AppID);
    }

    static loadAdd() {
        advert.loadAd(request.build());
    }

    static loadListeners() {
        advert.on('onRewarded', (event) => {
            EventRegister.emit(Constant.EventTypes.Rewarded, Constant.EventTypes.Rewarded);
            advert.loadAd(request.build());
        });
        advert.on('onAdClosed', () => {
            advert.loadAd(request.build());
        });
        advert.on('onAdLoaded', (event) => {
            // advert.show();
        });
        advert.on('onAdFailedToLoad', (error) => {
         console.log(error);
          });
    }

    static showAdd() {
        if(advert.isLoaded()){
         advert.show();
        }else{
            console.log('not loaded')
        } 
    }

}`

and AppDelegate File Looks Like:

`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  [RNFirebaseNotifications configure];
  [GADMobileAds configureWithApplicationID:@"ca-app-pub-9508394659859044~6040384343"];

  [[RCTI18nUtil sharedInstance] allowRTL:YES];
  NSURL *jsCodeLocation;
  [Fabric with:@[[Crashlytics class]]];

  

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"Playsive"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  //[RCTSplashScreen open:rootView];
  [RCTSplashScreen open:rootView withImageNamed:@"splash"]; // activate splashscreen, imagename from LaunchScreen.xib

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  
  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];
  
  return YES;
}`

Any suggestion Y i am not able to load Video...?

**Comment by hazeeb** [comment]
**error-code-no-fill** shows when the ad request was successful, but no ad was returned due to lack of ad inventory.
Check out this, https://rnfirebase.io/docs/v5.x.x/admob/error-handling

**Comment by tusharmutreja** [comment]
@hazeeb thanks, I already saw that, so It means my admob integration is fine ? 
there is issue with test ID?

**Comment by sonlexqt** [comment]
I tried using Interstitial instead of Rewarded and got the same error ... admob running out of ads doesn't seem convincing to me

**Comment by tusharmutreja** [comment]
@sonlexqt any update?

**Comment by sonlexqt** [comment]
@tusharmutreja no luck so far ...

**Comment by Chenjh1992** [comment]
Have you try `addTestDevice(<your device id>)`?

**Comment by tusharmutreja** [comment]
@Chenjh1992  yes I tried with test Id and for simulator it automatically takes it
