### ISSUE TITLE
Issue in building the android apk with react native firebase 5.1.1

### ISSUE THREAD

**Issue by vivek-walecha-657** [invertase/react-native-firebase#1748]
## Issue
I am trying to build the android project with react-native-firebase version 5.1.1
Getting the below issues:
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/vivek/Desktop/Goibibo/goibibo_mobile/afore/node_modules/react-native-firebase/android/build.gradle' line: 130

* What went wrong:
A problem occurred evaluating project ':react-native-firebase'.
> react-native-firebase: unable to locate React Native android sources or prebuilt binary. Ensure you have you installed React Native as a dependency in your project and try again.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 2s
react-native-firebase: unable to locate React Native android sources or prebuilt binary. Ensure you have you installed React Native as a dependency in your project and try again.
Open File
---

#### `android/settings.gradle`:

include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, './afore/node_modules/react-native-firebase/android')

---

## Environment

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.1
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 120.14 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.3.0 - ~/.nvm/versions/node/v11.3.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v11.3.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 14, 19, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-19 | ARM EABI v7a, android-19 | Intel x86 Atom, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.6 => 0.57.6

**Comment by vivek-walecha-657** [comment]
please refer this line:
https://github.com/invertase/react-native-firebase/compare/v5.1.0-rc3...master#diff-7ae5a9093507568eabbf35c3b0665732R129

**Comment by vivek-walecha-657** [comment]
@Salakar Can you please help here.
I'll be very thankful if I'll get any response.

**Comment by Chenjh1992** [comment]
By looking at RN-Firebase [build.gradle](https://github.com/invertase/react-native-firebase/blob/master/android/build.gradle#L104). Could you try to output/debug your `androidPrebuiltBinaryDir` to see if the path is correctly?
Also, could you post your directory structure?

**Comment by Mifayo** [comment]
any luck here ?

**Comment by Salakar** [comment]
Hey @Mifayo could you screenshot / show your project folder structure - this generally means you're using a non-standard project structure

**Comment by vivek-walecha-657** [comment]
> Hey @Mifayo, @vivek-walecha-657 could you screenshot / show your project folder structure - this generally means you're using a non-standard project structure

Sure @Salakar let me show you my project structure.

**Comment by vivek-walecha-657** [comment]
react-native-firebase build.gradle expects prebuild into this:
/Users/vivek/Desktop/abc/node_modules/react-native/android

but mine is in:
/Users/vivek/Desktop/abc/**def/ghi**/node_modules/react-native/android

**Comment by jhonex11** [comment]
I read   this article. I think You put a great deal of exertion to make this article.   I like your work.  <a   href="https://tutusapp.com/si-mont9k-versi-terbaru-2020/">Si   Mont9k Versi Terbaru 2020</a>
