### ISSUE TITLE
🔥Remote push notifications stop after some time

### ISSUE THREAD

**Issue by deorukhkarchaitanya** [invertase/react-native-firebase#1757]
## Issue
**[Android]**
I receive remote push notifications without any issues for a while after interacting with the app. When the app stays in the background for some time (about an hour, this time differs from device to device) the device stops receiving any push notifications. Once I open the app again, I start receiving push notifications as intended until I put the app in background and not interact with it for some time.

After reading a little on this issue, I figured that a lot of android devices kill off the app and it's services completely. Some Android devices have 'auto-start' turned off by default which prevents the background service to wake up after receiving a notification. 

I have also noticed that some apps have an FAQ section on how to troubleshoot device-specific issues to recieve push notifications which includes suggestions like turning off battery optimizations, turning on auto-start, whitelisting app from battery saver, etc.

To understand the problem better, I took 2 approaches to FCM

**1) notification + data messages from FCM**
Payload from server:
 ```
payload = {
                notification: {
                   title: "A title",
                   body: "Notification body"
                },
                data: {
                   dataExample1,
                   dataExample2
                }
            };
```

In this case I followed https://rnfirebase.io/docs/v5.x.x/notifications/receiving-notifications
Notification was generated by the OS and displayed appropriately

**2) data only from FCM**
```
payload = {
                data: {
                   dataExample1,
                   dataExample2,
                   title: "A title",
                   body: "Notification body"
                }
            };
```
In this case I followed https://rnfirebase.io/docs/v5.x.x/messaging/receiving-messages
Once bgMessaging.js was triggered, I would create a local notification using the data from the payload

----------------

_**Either way, the behaviour remained the same. Devices stopped receiving notifications/fcm messages after a while.**_

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath 'com.google.gms:google-services:4.0.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google() 
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27
                buildToolsVersion "27.0.2"
            }
        }
    }
}

ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}
```

#### `android/app/build.gradle`:
(I have removed a few irrelevant lines and comments)
```groovy
apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "xxxxxxxxx"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 999
        versionName "xxxxx"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    signingConfigs{
        release { 
            storeFile file(KEYSTORE_STORE_FILE)
            storePassword pass
            keyAlias KEY_ALIAS
            keyPassword pass
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation project(':react-native-document-picker')
    implementation project(':react-native-interactable')
    implementation project(':rn-fetch-blob')
    implementation project(':react-native-svg')
    implementation project(':react-native-firebase')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation "com.google.android.gms:play-services-base:16.0.1"
    implementation "com.google.firebase:firebase-core:16.0.4"
    implementation "com.google.firebase:firebase-auth:16.0.5"
    implementation "com.google.firebase:firebase-firestore:17.1.2"
    implementation "com.google.firebase:firebase-messaging:17.3.4"
    implementation "com.google.firebase:firebase-storage:16.0.4"
    implementation "me.leolin:ShortcutBadger:1.1.21@aar"

    apply plugin: 'com.google.gms.google-services'
}

task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```

#### `android/settings.gradle`:

```groovy
rootProject.name = 'xxxxx'
include ':react-native-document-picker'
project(':react-native-document-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-document-picker/android')
include ':react-native-interactable'
project(':react-native-interactable').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-interactable/android')
include ':rn-fetch-blob'
project(':rn-fetch-blob').projectDir = new File(rootProject.projectDir, '../node_modules/rn-fetch-blob/android')
include ':react-native-svg'
project(':react-native-svg').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-svg/android')
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')

include ':app'
```

#### `MainApplication.java`:

```java
package xxxx.xxx.xxxx;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.reactnativedocumentpicker.ReactNativeDocumentPicker;
import com.wix.interactable.Interactable;
import com.RNFetchBlob.RNFetchBlobPackage;
import com.horcrux.svg.SvgPackage;
import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.auth.RNFirebaseAuthPackage;
import io.invertase.firebase.firestore.RNFirebaseFirestorePackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;
import io.invertase.firebase.storage.RNFirebaseStoragePackage; 
import java.util.Arrays;
import java.util.List;
import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ReactNativeDocumentPicker(),
            new Interactable(),
            new RNFetchBlobPackage(),
            new SvgPackage(),
            new RNFirebasePackage(),
            new RNFirebaseAuthPackage(),
            new RNFirebaseFirestorePackage(),
            new RNFirebaseMessagingPackage() ,
            new RNFirebaseStoragePackage() ,
            new RNFirebaseNotificationsPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```

#### `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="xxxxxx">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> 
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove"/>
    <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
      >
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:launchMode="singleTop"        
        >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
     <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
    </service>
    <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
      <intent-filter>
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
      </intent-filter>
    </service>
    <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />
      <meta-data
        android:name="com.google.firebase.messaging.default_notification_icon"
        android:resource="@drawable/ic_notification" />
     <meta-data
        android:name="com.google.firebase.messaging.default_notification_channel_id"
        android:value="messages"/>
    </application>

</manifest>
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `Observed and tested on Android API 25, 27 , 28`
- **Operating System:**
  - [x] MacOS, version: `10.14.1`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Android Studio 3.2.1`
- **`React Native` version:**
  - `0.57.7`
- **`React Native Firebase` library version:**
  - `5.1.1`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] Authentication
  - [ ] Analytics
  - [x] Cloud **Firestore**
  - [x] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [x] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [x] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by Nits7029** [comment]
+1

**Comment by nickfla1** [comment]
I have a very similar issue, sometimes notifications just don't work. We are sending data-only notifications.
When this happens `firebase.notifications().displayNotification()` doesn't enter neither `then` nor `catch`

**Comment by Salakar** [comment]
@deorukhkarchaitanya are you listening for fcm registration token changes and updating your backend with the devices new token when it changes, I'd imagine if you're not then the issue probably is that you're pushing to an old registration token.

**Comment by deorukhkarchaitanya** [comment]
@Salakar yes, I am listening to the token changes. The token remains unchanged, once I re-open the app and it goes in the background after a while it stops receiving notifications. 

For Xiaomi devices turning on "auto-start" fixed this problem. Weird enough, apps like Facebook and Whatsapp have "auto-start" as on by default.

For an Android Go device, I tried whitelisting the app but still no luck. 

I suspect this is OEM specific issue but there needs to be some way to deliver these notifications.

**Comment by AugustoAleGon** [comment]
I have the same issue.

**Comment by Arun1295** [comment]
I am also having the same issue in android mobiles which having android version 7 and above.
Below version 7 it is working fine.
Any solution?

**Comment by foo4foo** [comment]
@Arun1295 I don't think this problem is related to react-native-firebase package at all. It may be a bug with firebase servers to drop notifications on high load (just a guess).

Also, I experienced this problem on all android versions (starting from 4.4).

**Comment by keech** [comment]
ref. https://github.com/firebase/firebase-ios-sdk/issues/2438

**Comment by keech** [comment]
Any updates?

**Comment by keech** [comment]
This issue should not close yet

**Comment by keech** [comment]
https://github.com/invertase/react-native-firebase/issues/1972

**Comment by keech** [comment]
#https://github.com/invertase/react-native-firebase/issues/1972

**Comment by fgagneten** [comment]
Same issue here!

**Comment by nilton-neto** [comment]
I`m also having the same issue, background messages works until it doesn`t.
Each time the app is opened, it starts working again for a while again

**Comment by chauhanPankaj007** [comment]
Still getting issue

**Comment by mikehardy** [comment]
Those vendors have corrupted the Android ecosystem by mis-implementing the power management APIs on purpose, complaints should go to them, and I hope with AOSP for Android 12 where the Android team promised to add compatibility checks for the power management APIs into the CTS these vendors are forced to behave. https://dontkillmyapp.com

**Comment by Andriiklymiuk** [comment]
Also having the same issue, when device stays in background for several days and then notifications stop coming at all. Problem only disappears, if device is terminated and opened again. Have someone figured out any way to overcome this issue?

**Comment by mikehardy** [comment]
https://dontkillmyapp.com probably...

**Comment by nasirdev74** [comment]
I'm having similar issue on realme device.

**Comment by mikehardy** [comment]
@nasirdev74 how did it go when you followed the link I posted above and made sure Realme device wasn't doing power saving? What evidence do you see in the logs as you test this, so we have concrete detailed information to move the issue forward other than a simple "me too" comment?

**Comment by AhsanRiyad** [comment]
same issue

**Comment by vramirezp** [comment]
same here

**Comment by hudsonthewolfman** [comment]
Same issue

**Comment by JabalnurIT** [comment]
same issue

**Comment by Kaddtechnologies** [comment]
this is still happening in 2024

**Comment by JatinjeetSingh12** [comment]
same issue

**Comment by obonyojimmy** [comment]
Found a solution , looks like some manifest declarations are not getting resolved from main RNFB package . Add under in application in AndroidManifest.xml

```
<application>
  ....   others...

    <service android:name="io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService" android:exported="false" />
    <service android:name="io.invertase.firebase.messaging.ReactNativeFirebaseMessagingService" android:exported="false">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
      </intent-filter>
    </service>
    <receiver
      android:name="io.invertase.firebase.messaging.ReactNativeFirebaseMessagingReceiver"
      android:exported="true"
      android:permission="com.google.android.c2dm.permission.SEND">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
      </intent-filter>
    </receiver>
    <meta-data android:name="firebase_messaging_auto_init_enabled" android:value="true" />
    <meta-data android:name="firebase_analytics_collection_enabled" android:value="true" />
</application>
```

Source:
- https://github.com/invertase/react-native-firebase/blob/main/packages/messaging/android/src/main/AndroidManifest.xml
- 
- https://github.com/invertase/react-native-firebase/blob/9c940857a3759f85fad2f8d995b83f7c08058d6b/docs/migrating-to-v6.md?plain=1#L92

**Comment by obonyojimmy** [comment]
On closer look , the [`onMessageReceived`](https://github.com/invertase/react-native-firebase/blob/main/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingService.java#L34) is not implemented , you might need to overide the method

**Comment by mikehardy** [comment]
@obonyojimmy this is an issue from 2018, and it's closed

The original poster's problem may still be valid for some, but so is the set of solutions and they mostly revolve around asking your users to alter settings for your app in a way that works for your device: https://dontkillmyapp.com/

In general users seem to prefer much improved battery life over whatever app feature us developers think is so important though, keep that in mind. Message delivery is unreliable in all cases and apps have to handle that gracefully.

**Comment by chaitanyadeorukhkar** [comment]
Commenting on a very old and stale issue for newcomers who land here. I highly doubt there is anything that can be done to "fix" this issue by the library. The issue remains with how companies use Android's power management to suppress applications in the background. My suggestion would be to ask your users to "whitelist" your all from the power management systems (refer https://dontkillmyapp.com). Having said that, users probably care more about their battery life than the notifications, try finding alternate ways to notify your users about critical things (like email). 

For people coming to this issue going forward, let's not engage more here since there's nothing that can be done on the library level.

**Comment by smasinde** [comment]
I get this problem when using react-native-background-fetch, after the background task runs all notification functionality stops
