### ISSUE TITLE
removeDeliveredNotification(id) not working

### ISSUE THREAD

**Issue by king804** [invertase/react-native-firebase#1762]
i want to remove the notification by id...In android, the notification can't remove

the code as below:
firebase.notifications().removeDeliveredNotification('0:1544884734101699%e81a54d1e81a54d1');

0:1544884734101699%e81a54d1e81a54d1   <------ curl send return it to me
response.data.results[0].message_id

**Comment by Salakar** [comment]
Please correctly fill out the issue template, without this, we can not help. 

Locking and closing this issue. Feel free to raise another issue that correctly follows the issue template.
