### ISSUE TITLE
Android removeDeliveredNotification(id) not working 

### ISSUE THREAD

**Issue by king804** [invertase/react-native-firebase#1763]
Hi , i have an issue about remove delivers notification, because i develop new feature "remove message". Therefore, i want to remove notification by unique id.

the notification id base on fcm curl send api return. (https://fcm.googleapis.com/fcm/send)

The android can't remove notification by id , but remove all is fine.

Backend curl post body
`let body = {
        to: push_token,
        notification:{
            title: user_name,
            body: content,
            sound: "default",
            icon: "notify",
            badge: 1,
        },
        data: {
            custom_notification: {
                show_in_foreground: false,
                badge: 1,
                priority: "high",
                content_available: true,
            }
        },
        content_available: true,
        priority: "high"
    }`

React Native Code
`async componentDidMount(){
       firebase.notifications().removeDeliveredNotification('0:1544884734101699%e81a54d1e81a54d1');
}`

"react-native": "0.57.0",
"react-native-firebase": "^5.1.0",

**Comment by LorandP** [comment]
I have the same problem.
Only this works:
`firebase.notifications().removeAllDeliveredNotifications()`

**Comment by LorandP** [comment]
From react-native-firebase 5.1.0+ you can apply this solution and it will work.
` if(Platform.OS === 'android' && typeof notification.android.tag === 'string'){
       let tag: string = notification.android.tag;
       Firebase.notifications().android.removeDeliveredNotificationsByTag(tag);
   } else {
       Firebase.notifications().removeDeliveredNotification(notification.notificationId);
   }`

**Comment by anastely** [comment]
@LorandP Hey, I have the same issue when i receive a notification "when app killed" and click to open it, it's opened very well and navigate me to "Notifications Screen" But in every time after I open the app without click to any notification it navigates me to "Notifications Screen", SO How can I remove the previous notification, 
I'm Tried this But didn't work


```
async componentDidMount() {
    BackHandler.addEventListener("hardwareBackPress", this.backPressed);

    this.notificationInitListener = await firebase
      .notifications()
      .getInitialNotification()
      .then(notificationOpen => {
        if (notificationOpen) {
          console.log(notificationOpen);
          setTimeout(() => {
            this.props.navigation.navigate("Notifications");
          }, 2000);
        }
        console.log("1---OPEND");
        firebase.notifications().removeAllDeliveredNotifications();
        console.log("1---OPEND-After");
      });
}
```

**Comment by yoopoong96** [comment]
> I have the same problem.
> Only this works:
> `firebase.notifications().removeAllDeliveredNotifications()`
> 
> Have you tried with
> `notification.android.setAutoCancel( true );` ?
> I have tried it with this also but it doesn't do anything

My app worked with SetAutoCancel(true) !!!!

**Comment by pankajtft** [comment]
**
if (Platform.OS === "android") {
        notification.android.setAutoCancel(true)
}
firebase.notifications().removeDeliveredNotification(notification.notificationId)
**

worked for me

**Comment by hanzoow** [comment]
any update ? 
im using "react-native-firebase": "^5.6.0", and "react-native": "0.61.5",
but removeDeliveredNotification isn't work for me ! 
i also set .android.setAutoCancel(true) but it didn't help !
plz help me

**Comment by fukemy** [comment]
i didnt see removeDeliveredNotification from the lib
