### ISSUE TITLE
RNFirebaseNotifications.h Not Found

### ISSUE THREAD

**Issue by thuyiya** [invertase/react-native-firebase#1767]
# Issue

This issue is keep popup, can not move forward,
Able to run application with 

```
pod 'Firebase/Core','4.2.0'
pod 'Firebase/Messaging','4.2.0'

```

this version of pod, but app is getting crash after i do that.

my env
```
Xcode 10.1
RN  0.53.3
React 16.2.0 
react-native-firebase 5.0.0
```

<img width="844" alt="screen shot 2018-12-15 at 8 17 12 pm" src="https://user-images.githubusercontent.com/42020227/50114063-a08e1b00-0269-11e9-96de-d846af0765f9.png">

**Comment by IljaDaderko** [comment]
Judging by documentation https://rnfirebase.io/docs/v5.x.x/installation/ios v5 of react-native-firebase relies on v5+ of firebase cocoapods. This might be an issue you are facing?

**Comment by thuyiya** [comment]
> Judging by documentation https://rnfirebase.io/docs/v5.x.x/installation/ios v5 of react-native-firebase relies on v5+ of firebase cocoapods. This might be an issue you are facing?
> 
> Everything runs fine on my end using pods versions from documentation. It looks like some `GoogleUtilities` bit is missing for you. Perhaps try running `pod update` just in case and clean your XCode project before rebuilding?

Working as accepted, Thanks for the support.
