### ISSUE TITLE
Firestore: No promise on get() or onSnapshot() when offline (if doc doesn't exist)

### ISSUE THREAD

**Issue by rom1k** [invertase/react-native-firebase#1769]
I'll keep it simple as the bug is easy to reproduce.

In firebase docs it says clearly:

> If you get a document while the device is offline, Cloud Firestore returns data from the cache. **If the cache does not contain data for that document, or the document does not exist, the get call returns an error.**
https://firebase.google.com/docs/firestore/manage-data/enable-offline#get_offline_data

```
// This is what happens when this code is run on a device that is completely offline
const test = async () => {
  try {
    console.log('Before doc')
   // Tried both with and without source option
    let doc = await this.db.collection('listTaskOrder').doc(listId).get({source: 'server'})
    console.log(doc.exists) // <--- NEVER REACHED 
  } catch (error) {
    console.log('catch') // <--- NEVER REACHED 
    console.log(error)
  }
}
test()
```
This causes an infinite loading screen in my app if the user has no internet connection, because there's no callback whatsoever so the app doesn't know when it's done loading. At least if I get an error I can stop the loading, now i have to figure out some weird workaround. Am I missing something or is this an actual bug?

EDIT:  I forgot to mention I got the same behavior with onSnapshot

Using
"react-native-firebase": "^5.1.1",
"react": "16.6.1",
"react-native": "0.57.7",

**Comment by rom1k** [comment]
This is strange. After I restart react native I now get the catch from .get(), it returns 'firestore/unavailable'. The problem I had seems to occur only if the app is connected to internet at first and then lose the connection (turn off wifi) and then do a simple reload. In that case I get no promise at all. It's only after I restart the app I again I get an error as expected.

**Comment by aureliopetrone** [comment]
There is an error with the request maybe. Try to do this:

```
    let doc = await this.db.collection('listTaskOrder').doc(listId).get({source: 'server'}, (error)=>console.log("ERROR", error))
```

**Comment by bennbollay** [comment]
https://github.com/firebase/firebase-js-sdk/issues/8862
