### ISSUE TITLE
push notification not working in some devices having android v8+

### ISSUE THREAD

**Issue by Nits7029** [invertase/react-native-firebase#1770]
## Issue

I have implemented push notification service and it works fine in most of android devices, but having issues in some device eg. realme android v8.1.

Issue is when app closed, not able to receive notifications and not able to handle notification data.

Let me know if any configuration files needed for review.

so anyone know, where i need to take a look? Thanks

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `ADD_SOMETHING_HERE` e.g. Xcode 10, Android Studio 3.2
- **`React Native` version:**
  - `ADD_SOMETHING_HERE`
- **`React Native Firebase` library version:**
  - `ADD_SOMETHING_HERE`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [x] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by deorukhkarchaitanya** [comment]
Please take a look at the issue #1757 I created and let me know if it is something similar that you are facing.

**Comment by Nits7029** [comment]
no its not some time, for me it never works when app closed. 

and and not able to handle notification data, when the app in background or in the foreground. I mean onNotificationOpened method not calling on tap of notification.

**Comment by Nits7029** [comment]
any updates here?

**Comment by Nits7029** [comment]
following up, i have debugged with Android studio. and i found that when app killed and on notification send i am getting log as attached screenshot

![screen shot 2018-12-21 at 6 09 57 pm](https://user-images.githubusercontent.com/9457796/50344152-c52b1100-054f-11e9-9060-9932a40b7c08.png)

**Comment by sangupandi** [comment]
@Nits7029 I am also getting the same problem mainly in oneplus and oppo devices. Did you got any fixes?

**Comment by Nits7029** [comment]
not yet, hopefully i moved to OneSingal

**Comment by sangupandi** [comment]
any updates here?

**Comment by abdullahbayram** [comment]
any progress?

**Comment by arvindebiztrait** [comment]
I am getting same issue, Can you please provide solution?

**Comment by ithustle** [comment]
+1
