### ISSUE TITLE
Crashlytics not work

### ISSUE THREAD

**Issue by nguyenhoanglam** [invertase/react-native-firebase#1771]
I've implemented crashlytics as the document. Then I tested it with a forced crash:
```java
firebase.crashlytics().crash() 
```
The crash was reported in Firebase console as expected. However, when the app crashs by an error in code, the crash is not reported to the console.

Does anyone has the same issue?

**Comment by Ehesp** [comment]
How long have you waited? They can take up to 24 hours to appear.

**Comment by nguyenhoanglam** [comment]
I've waited for 4 days and no reports shown. Do we need to use crash() function to report it or RNFirebase Crashlytics reports automatically?

**Comment by nguyenhoanglam** [comment]
It worked!

**Comment by oakis** [comment]
@nguyenhoanglam  Why do you close this issue without any resolution?
