### ISSUE TITLE
notifications().getInitialNotification never resolves on iOS in release mode

### ISSUE THREAD

**Issue by uuaqarahmed** [invertase/react-native-firebase#1775]
## Issue

In debug mode the following code runs fine and I can see notification information on iOS:

const notificationOpen: NotificationOpen = await firebase.notifications().getInitialNotification();
if (notificationOpen) {
 //works fine
}

However, when I change it to release mode, it never resolves and app goes on loading forever. This code is called when app is killed and is launched after tapping on a received notification. 

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  
- **`React Native` version:**
  - `0.57.0`
- **`React Native Firebase` library version:**
  - `5.1.1`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] Notifications

**Comment by bricker** [comment]
What was the issue here? I'm experiencing the same problem.
