### ISSUE TITLE
update doc with arrayUnion gives error

### ISSUE THREAD

**Issue by udarts** [invertase/react-native-firebase#1776]
## Issue

I am trying to update a document in firestore, to add users uid to a userhasread array, but using the following code, gives an error:

```javascript
setAnnounceToRead(userId) {
        let doc = firebase.firestore().collection('announcements').doc(this.state.id);
        doc.update({ "userhasread": firebase.firestore.FieldValue.arrayUnion(userId) });
}
```

It produces the following error:

    undefined is not an object (evaluating '_firebase.default.firestore.FieldValue.arrayUnion')

Both: this.state.id and userId exist (did a console.log on both).

---

#### `ios/Podfile`:

- [x ] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Xcode 10`
  - `Android studio (latest version)`
- **`React Native` version: **
  - `0.57.8`
- **`React Native Firebase` library version: **
  - `5.1.1`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [x] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by udarts** [comment]
Any idea on this issue?

**Comment by Salakar** [comment]
@udarts what does `firebase` var point to - your code, is this `import firebase from 'react-native-firebase';` exactly or are you passing it around through redux or something like that?

**Comment by udarts** [comment]
Imported from react-native-firebase

**Comment by udarts** [comment]
Oh, sorry missed a small thing, I am loading the react-native-firebase in a separate file and them loading that file in every component I use.

The file looks like the following:
```javascript
import RNfirebase from 'react-native-firebase';

const instance = RNfirebase.app();

export default instance;
```

**Comment by Salakar** [comment]
Ok thanks, that'll be your problem then - the statics are only accessible from the module export and not the `app()` instance; so you'll need to use that:

```js
import rnfirebase from 'react-native-firebase';

// correct
rnfirebase.firestore.FieldValue.arrayUnion(userId);

// incorrect (what you're doing currently)
rnfirebase.app().firestore.FieldValue.arrayUnion(userId);
```

Hope that helps, will close the issue now.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by udarts** [comment]
@Salakar Any idea on this?

**Comment by udarts** [comment]
@Salakar I've made a change and now use `import firebase from 'react-native-firebase';`.

When I now try to update a doc with the following code:
```
setAnnounceToRead(userId) {
        let doc = firebase.firestore().collection('announcements').doc(this.state.id);
        doc.update({ "userhasread": firebase.firestore.FieldValue.arrayUnion(userId) });
}
```

In Firestore it is shown as:
```
userhasread: [
    0: useruid
]
```
While I thought it should be:
```
userhasread: [
   useruid
]
```

**Comment by akhil-geekyants** [comment]
A similar case like this one https://github.com/invertase/react-native-firebase/issues/1776#issuecomment-452891618 for me too. But this doesn't happen always. 

Screenshot from firebase database

<img width="526" alt="Screenshot 2019-04-12 at 6 26 52 PM" src="https://user-images.githubusercontent.com/27768184/56039004-ec9d2800-5d50-11e9-82a5-e8b44511fa56.png">

Console Log of updating object.

<img width="327" alt="Screenshot 2019-04-12 at 6 23 32 PM" src="https://user-images.githubusercontent.com/27768184/56039143-3d148580-5d51-11e9-9f76-202cb18ae8a8.png">

Is this a Firebase issue?
