### ISSUE TITLE
Not shown any head up on Android 7.0, all goes to tray bar silently when the app in the background

### ISSUE THREAD

**Issue by eladglobalbit** [invertase/react-native-firebase#1781]
Not shown any head up on Android 7.0, all goes to tray bar silently when the app in the background. 
I have head up in the foreground in any Android version.
In the background, I can see head up just above Android 8.0.
I just flow over docs 10 time what can be the reason?
Here my code thanks for help :) 

```
import React, {Component} from 'react';
import { AsyncStorage ,View , Text } from 'react-native';
import firebase from 'react-native-firebase';
import {  Root , Drawer} from './src/config/router';

export default class App extends Component {

  async componentWillMount() {
    console.log(JSON.parse(await AsyncStorage.getItem("user")));
    const channel = new firebase.notifications.Android.Channel(
      "Hip-chanelId",
      "Channel Name",
      firebase.notifications.Android.Importance.Max
    ).setDescription("A natural description of the channel");
    firebase.notifications().android.createChannel(channel);


    this.notificationListener;

    firebase
      .messaging()
      .hasPermission()
      .then(enabled => {
        if (enabled) {
          firebase
            .messaging()
            .getToken()
            .then(token => {
              console.log(token);
            });
          // user has permissions
        } else {
          try {
            firebase.messaging().requestPermission();
            // firebase
            // .messaging()
            // .getToken()
            // .then(token => {
            //   console.log(token);
            // });
        } catch (error) {
            // User has rejected permissions
        }
        }
      });



      // firebase
      // .notifications()
      // .getInitialNotification()
      // .then(notification => {
      //   if (notification) {
      //     console.log("notification opened", notification);
      //   }
      // });

      firebase.notifications().getInitialNotification()
      .then((notificationOpen) => {
        if (notificationOpen) {
          // App was opened by a notification
          // Get the action triggered by the notification being opened
          const action = notificationOpen.action;
          // Get information about the notification that was opened
          const notification = notificationOpen.notification;  
        }
      });



      this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
        // Get the action triggered by the notification being opened
        const action = notificationOpen.action;
        // Get information about the notification that was opened
        const notification = notificationOpen.notification;

        console.log("notification opened", notification);
    });


      this.notificationDisplayedListener = firebase.notifications().onNotificationDisplayed((notification) => {

     });
    this.notificationListener = firebase.notifications().onNotification((notification) => {
        // Process your notification as required
           // Process your notification as required
      console.log("notification");
      const {
        body,
        data,
        notificationId,
        sound,
        subtitle,
        title
      } = notification;
      console.log("LOG: ", title, body, JSON.stringify(data));
      const localNotification = new firebase.notifications.Notification({
        sound: "default",
        show_in_foreground: true,
        priority: "high",
        local_notification: true
      })
        .setNotificationId(notification.notificationId)
        .setTitle('this coming from app')
        .setSubtitle(notification.subtitle)
        .setBody(notification.body)
        .setData(notification.data)
        .android.setChannelId("Hip-chanelId") // e.g. the id you chose above
        .android.setSmallIcon("ic_launcher") // create this icon in Android Studio
        .android.setColor("#000000") // you can set a color here
        .android.setPriority(firebase.notifications.Android.Priority.High)
  

        console.log('notifoocion ')
      firebase
        .notifications()
        .displayNotification(localNotification)
        .catch(err => console.error(err));
    });


  }

  componentWillUnmount() {
    this.notificationDisplayedListener();
    this.notificationListener();
    this.messageListener();
  }


constructor(props){
  super(props);
}




  render() {
    return (
       <Root />
    );
  }

}


```

bulid.gradle  app 

dependencies {
    compile project(':react-native-vector-icons')
     implementation(project(':react-native-maps'))
    compile project(':react-native-image-picker')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
  implementation 'com.android.support:appcompat-v7:27.1.1'
implementation 'com.android.support:design:27.1.1'
compile(project(':react-native-firebase')) {   
       transitive = false
}
implementation "com.google.android.gms:play-services-base:16.0.1"
implementation "com.google.firebase:firebase-core:16.0.4"
implementation "com.google.firebase:firebase-messaging:17.3.4"
implementation "com.google.firebase:firebase-auth:16.0.5"
implementation 'me.leolin:ShortcutBadger:1.1.21@aar'
}

bulid.gradle android 

` buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
        googlePlayServicesVersion = "15.0.1"`

AndroidManifest.xml

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.myapp">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
  <uses-permission android:name="android.permission.VIBRATE" />
  <uses-permission android:name="android.permission.GET_TASKS" />

  
  
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
      >

    <receiver android:name="io.invertase.firebase.notifications.RNFirebaseBackgroundNotificationActionReceiver" android:exported="true">
    <intent-filter>
      <action android:name="io.invertase.firebase.notifications.BackgroundAction"/>
    </intent-filter>
  </receiver>
  <service android:name="io.invertase.firebase.notifications.RNFirebaseBackgroundNotificationActionsService"/>

       <meta-data
    android:name="com.google.firebase.messaging.default_notification_channel_id"
    android:value="Hip-chanelId"/>

        <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
         <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:launchMode="singleTop">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
        <meta-data
     android:name="com.google.android.geo.API_KEY"
     android:value="api-key-fire-base"/>
    </application>

</manifest>
`

**Comment by eladglobalbit** [comment]
So the solution is like this : 
send this json:
{
 "to" : "token-phone",
 "data" : {
     "body" : "Body of Your Notification in Data",
     "title": "Title of Your Notification in Title"
 }
}
please **note** that you do not have a notification property when you send, you will get the message in on onMessage event in the background you will need to do the 4 steps of messaging like the doc.

**Comment by mcorner** [comment]
No matter what, I could not get pure "heads up" notifications (no data, just notification) to work on Android <8.0. I cold only get an icon and sound, but no floating notification.

On >=8.0 notifications work (heads up and everything) if I set up the channel with max priority.

I am switching to using pure data notifications and then showing the local notifications from the onMessage event.  See optional step 4 here: https://rnfirebase.io/docs/v5.x.x/messaging/receiving-messages

**Comment by eladglobalbit** [comment]
Try send what I say in postman  ,  now this work for me.
If this stil not works post here your code :)

**Comment by windydang26** [comment]
@eladglobalbit if you want to show headup noti with old android version (<=7) you always must be set sound for local notification before display.
