### ISSUE TITLE
react-native-firebase phone-auth refuses to send OTP sms

### ISSUE THREAD

**Issue by Yingi** [invertase/react-native-firebase#1785]
I am using react-native-firebase version 3.3x.

I have tried to implement the phone authentication, i have set up the SHA-1 hash in the firebase console. I have also set up a testing phone number. The code below works fine

`firebase.auth().signInWithPhoneNumber(phoneNumber)
      .then((confirmResult) => {
        console.log(confirmResult);
        this.setState({ confirmResult: confirmResult, authenticating: false })

      })`

But I am not recieving any OTP sms from firebase. If i use a different number that isnt registered in the firebase console, it gives an error as expected. But when i use the correct number, i am not recieving the OTP sms.

**Comment by 0x01Brain** [comment]
Same here, I even made sure to have my app certificate fingerprint added to the firebase console, and Google Play services installed in the emulator, the emulator is running Lolipop Google API.

**Comment by nonoyek** [comment]
Have u guys figure out? Working or still not working? please reply need to know urgently

**Comment by CrisHemswerthThor** [comment]
Hie, I have the same issue. Firstly, it was working fine for me but after adding firebase messaging, I stoped getting sms. Please help me if anyone has any solution.

**Comment by 345ml** [comment]
Any update?

**Comment by ckOfor** [comment]
Please make sure you are not using the same number you used as default in firebase console, It won't send notification to the same number in the console, try using a different number.
