### ISSUE TITLE
Getting multiple verification emails from firebase  ...hours and hour later

### ISSUE THREAD

**Issue by jasan-s** [invertase/react-native-firebase#179]
Has anyone faced this issue?  I am developing an app and yesterday tested sendEmailVerification(). Today I am still getting verification emails from firebase every after few hours.

**Comment by chrisbianca** [comment]
@jasan-s this sounds like a Firebase issue rather than anything to do with react-native-firebase?  Presumably you're still getting the email regardless of whether your app is open or not?  If so then I'd suggest reporting it to Firebase directly...
