### ISSUE TITLE
serverTimestamps is not working

### ISSUE THREAD

**Issue by alexandregiordanelli** [invertase/react-native-firebase#1797]
firestore has a feature that you can get a timestamp before exists on the server.. 

for example:
```
ref.onSnapshot(doc => {
   const data = doc.data({serverTimestamps: 'estimate'})
   console.log(data.createdAt) // createdAt is a field type timestamp
}
```
onSnapshot is fired always twice.. the first one it doesnt have the createdAt and the second one has it. using {serverTimestamps: 'estimate'} they put a timestamp for me for free in the first fired.

another issue is the correct on documentation is data.createdAt.toDate()

in react-native-firebase toDate is not necessary!

thanks a lot!

**Comment by Salakar** [comment]
@alexandregiordanelli thanks, could you link to the docs you mentioned, the feature above and also where the toDate() is. Thanks

**Comment by alexandregiordanelli** [comment]
https://firebase.google.com/docs/reference/js/firebase.firestore.SnapshotOptions
https://firebase.google.com/docs/reference/js/firebase.firestore.Timestamp

**Comment by bartkoedijk** [comment]
There is not a SnapshotOptions attribute in react native firebase. I am also confused if they haven't created this functionality or if this is left out for a reason. Can someone help me with this?

https://rnfirebase.io/reference/firestore/querydocumentsnapshot#data
https://firebase.google.com/docs/reference/node/firebase.firestore.QueryDocumentSnapshot#data

**Comment by mikehardy** [comment]
I see you linking to the node reference, we go from the client JS SDK, so you want this reference

https://firebase.google.com/docs/reference/js/firebase.firestore.QueryDocumentSnapshot

It does still appear to have the SnapshotOptions parameter

Sometimes our ability to implement the JS SDK APIs is tempered by underlying SDK differences in what we wrap - in this case it looks like firebase-android-sdk doesn't have SnapshotOptions https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/QueryDocumentSnapshot

...and neither does iOS https://firebase.google.com/docs/reference/ios/firebasefirestore/api/reference/Classes/FIRQueryDocumentSnapshot

So in this case there is no ability to implement SnapshotOptions it appears

**Comment by JanErikFoss** [comment]
Could I suggest adding a warning when you pass SnapshotOptions? I spent some unnecessary time debugging this.

**Comment by JanErikFoss** [comment]
Although both iOS and android have serverTimestampBehavior, it looks like it should be possible to handle this correctly.

**Comment by mikehardy** [comment]
I mean this sincerely - PRs happily accepted

**Comment by JanErikFoss** [comment]
https://github.com/invertase/react-native-firebase/pull/5514
