### ISSUE TITLE
Authentication examples throw 'is not a function' error in JS

### ISSUE THREAD

**Issue by dackers86** [invertase/react-native-firebase#18]
Steps to follow:

1. Install as per docs for Android.
2. Create a file in JS to implement....

```
import RNfirebase from 'react-native-firebase';

const instance = RNfirebase.initializeApp({
    debug: __DEV__ ? '*' : false,
    errorOnMissingPlayServices: false,
    persistence: true,
});

export default instance;
```

3. Attempt to cal any function in Auth, eg...

```
firebase.auth().onAuthStateChanged((user) => {
            if (user) {
                // User is signed in.
            }
        });
```

**Comment by Salakar** [comment]
What package version you running? It's working here on both ios and android:
![image](https://cloud.githubusercontent.com/assets/5347038/24256634/904ec50a-0fe0-11e7-84d0-5efdc44cb5eb.png)

**Comment by dackers86** [comment]
I'm attempting to update my emulator to the latest android version (may have something to do with google apis?)

**Comment by dackers86** [comment]
![screen shot 2017-03-23 at 16 05 35](https://cloud.githubusercontent.com/assets/2060661/24257477/ea7bef06-0fe2-11e7-9502-6e616b6f048b.png)
![screen shot 2017-03-23 at 16 05 55](https://cloud.githubusercontent.com/assets/2060661/24257478/ea84ebc4-0fe2-11e7-8edd-ec8ae8dd30ab.png)

**Comment by Ehesp** [comment]
Look in the Android logs, it'll probably be shouting about something.

```
react-native log-android
```

**Comment by dackers86** [comment]
Nothing seems log, trace with the error reads as....

```
--------- beginning of main
--------- beginning of system
```

**Comment by dackers86** [comment]
Version appears to be 1.0.0-alpha8

**Comment by Salakar** [comment]
I think you're missing the module import in MainApplication.java file in android folder, these two lines:

https://github.com/invertase/react-native-firebase-tests/blob/master/android/app/src/main/java/com/reactnativefirebasedemo/MainApplication.java#L6

https://github.com/invertase/react-native-firebase-tests/blob/master/android/app/src/main/java/com/reactnativefirebasedemo/MainApplication.java#L29

**Comment by Salakar** [comment]
Wait a minute, i see your problem, `require` doesn't automatically export default for you, change your import to:

`import firebase from '../firebase';

**Comment by dackers86** [comment]
Thanks Mike! 

That fixed it :)
