### ISSUE TITLE
onTokenRefresh unsubscribe

### ISSUE THREAD

**Issue by Cretezy** [invertase/react-native-firebase#180]
Hey, firebase.messaging().onTokenRefresh returns nothing. This is unlike the Web SDK, where it returns a function that once ran, can unsubscribe.

Current fix is this:

```javascript
let active = true;
const unsub = firebase.messaging().onTokenRefresh((token) => {
		if (active) {
			// Do things
		}
	});

// To unsubscribe currently:
active = false;
// Should be
unsub();
// or
unsub.off();
```

**Comment by Ehesp** [comment]
Thanks for reporting. We'll sort this out in the week.

**Comment by Cretezy** [comment]
Great, thank you.

**Comment by chrisbianca** [comment]
@Cretezy I've just been taking a look, this currently returns an object with a .remove() function.  I have updated to return a function as per the messaging spec for v2: https://github.com/invertase/react-native-firebase/commit/96d122f943fbafbb4d7076830a92f598a2f0159c

Thanks for reporting

**Comment by Cretezy** [comment]
Ah great!

https://github.com/invertase/react-native-firebase/blob/96d122f943fbafbb4d7076830a92f598a2f0159c/index.d.ts#L576 seems to be still outdating. That's where I was basing my original information on.

**Comment by chrisbianca** [comment]
Good spot! I've just updated the flow and TypeScript typings to match
