### ISSUE TITLE
it seems that logging custom events is not working.

### ISSUE THREAD

**Issue by flippy1989** [invertase/react-native-firebase#1804]
this is my code:
public class Filter extends AppCompatActivity {
    private FirebaseAnalytics mFirebaseAnalytics;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_filter);
        mFirebaseAnalytics = FirebaseAnalytics.getInstance(this);

    }

    public void onClickFilter(View v)
    {
        EditText minYear =findViewById(R.id.editText_minYear);
        EditText maxYear =findViewById(R.id.editText_MaxYear);
        EditText minPrice =findViewById(R.id.editText_minPrice);
        EditText maxPrice =findViewById(R.id.editText_MaxPrice);

        Bundle bundle = new Bundle();
        bundle.putString("min_price", minPrice.getText().toString());
        bundle.putString("min_price", minPrice.getText().toString());
        bundle.putString("min_price", minPrice.getText().toString());
        bundle.putString("min_price", minPrice.getText().toString());
        mFirebaseAnalytics.logEvent("search_parameters", bundle);

        DatabaseToApplication.minPrice = Integer.parseInt(minPrice.getText().toString());
        DatabaseToApplication.maxPrice = Integer.parseInt(maxPrice.getText().toString());
        DatabaseToApplication.minYear = Integer.parseInt(minYear.getText().toString());
        DatabaseToApplication.maxYear = Integer.parseInt(maxYear.getText().toString());
       // DatabaseToApplication.modelClicked = ((RadioButton)findViewById(R.id.radioButton_Model)).isChecked();
        Intent intent =new Intent(getApplicationContext(), MyStorageProduct.class);
        startActivity(intent);
    }
}

I don't know what the issue might be.
*please note that firebase is implemented and integrated correctly

**Comment by fukuball** [comment]
not working +1

**Comment by noahtallen** [comment]
@flippy1989, @fukuball Are you guys in react-native projects? That initial code looks like it's for a Native Android app. If so, then you might be in the wrong repo

**Comment by Ehesp** [comment]
Guys as @noahtallen mentioned this looks like native Android stuff, not React Native...
