### ISSUE TITLE
Vibrate on notification receive not working (iOS/Android)

### ISSUE THREAD

**Issue by ankitgroovy** [invertase/react-native-firebase#1808]
## Issue
i want phone to vibrate in some pattern for 30 seconds when i receive remote notification.
no matters application foreground / background / killed.
it should work in every case.
so how it is possible with this module.
i had seen code to vibrate in 
/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/DisplayNotificationTask.java

but it's not called. anyways. i tried to send vibration from push server. but nothing happens.
sometimes vibrates a slight but in some phones and for specific cases.

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
pod 'Firebase/Core'
 # 5.8.0 (version from Podfile.lock)
pod 'Firebase/Messaging'
 # 5.8.0 (version from Podfile.lock)
```

#### `AppDelegate.m`:

```objc
#import <Firebase.h>
#import "RNFirebaseNotifications.h"
#import "RNFirebaseMessaging.h"

// in didFinishLaunchingWithOptions
[FIRApp configure];
[RNFirebaseNotifications configure];

// other methods added
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [[RNFirebaseNotifications instance] didReceiveLocalNotification:notification];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
  [[RNFirebaseMessaging instance] didRegisterUserNotificationSettings:notificationSettings];
}

```

---

#### `android/build.gradle`:

```groovy
buildscript {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath 'com.google.gms:google-services:4.0.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven { url "https://jitpack.io" }
    }
}
```

#### `android/app/build.gradle`:

```groovy
android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
    }
}
dependencies {
...
implementation project(':react-native-firebase')
...
// Firebase dependencies
implementation "com.google.firebase:firebase-core:16.0.6"
implementation "com.google.firebase:firebase-messaging:17.3.4"
...
}
```

#### `android/settings.gradle`:

```groovy
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
```

#### `MainApplication.java`:

```java
import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;
import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;

// added this as documentation said
new RNFirebasePackage(),
new RNFirebaseMessagingPackage(),
new RNFirebaseNotificationsPackage(),
```

#### `AndroidManifest.xml`:

```xml
<service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
        <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
      </service>
      <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
        <intent-filter>
          <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
        </intent-filter>
      </service>
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
    ios from 9.0 to latest (12.1)
    android API 27
- **Operating System:**
  - [x] MacOS, version: `10.14.2`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - Xcode 10.1
  - Android Studio 3.2.1
- **`React Native` version:**
  - `0.55.4`
- **`React Native Firebase` library version:**
  - `4.3.8`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [x] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [x] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

**Comment by ziyoshams** [comment]
Hey @ankitgroovy, did you end up finding the solution?

**Comment by Nerogee** [comment]
vibration does not work in Android， but it's ok in IOS. Any solution?

**Comment by yasir-syed** [comment]
any update on this ?

**Comment by anuragipankaj** [comment]
any update guys???

**Comment by mikehardy** [comment]
@anuragipankaj it's an open source project, any updates will be here, if there are any.
I think you are going to want a full-featured "local notification" package (like notifee.app) as this module is focused on receiving remote notifications (firebase functionality) and does not attempt to cover all the local notification API surface area provided by mobile devices (not firebase functionality)
