### ISSUE TITLE
get double logEvent on one switch page please

### ISSUE THREAD

**Issue by AlohaIndy** [invertase/react-native-firebase#1809]
I use "wix/react-native-navigation" and "react-native-firebase".

code :

onNavigatorEvent(event) {
    if (event.id === 'didAppear') {
      firebaseApp
        .analytics()
        .logEvent('test_log_event'); 
    }
  }

result: 

![image](https://user-images.githubusercontent.com/32694764/50764468-451dde80-12a5-11e9-8df4-7404776964f2.png)

firebase get duo request on second 

how to fix?thx

**Comment by Salakar** [comment]
Please correctly fill out the issue template, without this, we can not help. 

Locking and closing this issue. Feel free to raise another issue that correctly follows the issue template.
