### ISSUE TITLE
how to show push notification with action buttons when app is in background

### ISSUE THREAD

**Issue by ramusesan** [invertase/react-native-firebase#1811]
push notifications are working fine with actions buttons when app is in foreground 
and not showing action button when app is background (only notification are showing without action button)

only message no action buttons are there can somebody help me

**Comment by zarvedan** [comment]
> @ramusesan
> Did you resolve this bug? Can you share me the solution?

Don't forget to remove "notification" from payload. Notification should be a "data message" if you don't want FCM to display the notification automatically.

"Data message | Client app is responsible for processing data messages. Data messages have only custom key-value pairs._"

[https://firebase.google.com/docs/cloud-messaging/concept-options](https://firebase.google.com/docs/cloud-messaging/concept-options)




https://firebase.google.com/docs/cloud-messaging/concept-options

**Comment by sourabhchotia** [comment]
i am still not able to do this. still my action buttons are not shown.
