### ISSUE TITLE
How to address device specific problems (Android,Notification,battery optimization)

### ISSUE THREAD

**Issue by sangupandi** [invertase/react-native-firebase#1812]
### Notification not displaying for some manufactures whenthe app is in killed state

(Oneplus devices, oppo ,vivo.. ) I can unterstand these are device specific issues but how to handle this issue. when the battery is opted for don't optimise mode it worked. 

##

**Comment by Ehesp** [comment]
Sorry I've no idea what you're asking - is this RNFirebase related?

**Comment by sangupandi** [comment]
Hi Eliot

I am using rn-firebase in my react native app for notification purpose. All
are working fine as expected. My Problem is Notification not received on
some devices mainly on "OnePlus,Vivo,Oppo" If I give don't optimize the
battery means it will receive the notification . Without changing this
settings , How I can acheive this? Please Give Some Suggestions/Solution.
Thank You. Waiting for your helpful reply.
