### ISSUE TITLE
🔥 RNFirebaseMessaging is intercepting FCM delegate call

### ISSUE THREAD

**Issue by littlehome-eugene** [invertase/react-native-firebase#1814]
We are using FCM and expect the following function to be called

`AppDelegate's 
 - (void)messaging:(FIRMessaging *)messaging didReceiveRegistrationToken:(NSString *)fcmToken {`

However `RNFirebaseMessaging.m` 's same function (signature) gets called instead

When we shake device and reload the js, RNFirebaseMessaging.m 's init method gets called and it is setting the delegate to itself. 

When we run the app by running it from xcode, this sometimes happens and sometimes doesn't..  
There's no explicit code to call RNFirebaseMessaging's init anywhere in our code. (We want our AppDelegate to be the delegate of the FCM messaging ..

## Issue

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:
 
```ruby
platform :ios, '9.0'
 use_frameworks!
 target "littlehome" do
   rn_maps_path = '../node_modules/react-native-maps'

   pod 'React', :path => '../node_modules/react-native', :subspecs => [
     'Core',
     'RCTText',
     'RCTImage',
     'RCTNetwork',
     'RCTSettings',
     'RCTLinkingIOS',
     'DevSupport',
     'RCTAnimation',
     'RCTWebSocket', # needed for localhost testing of your app
     'CxxBridge',
     #'BatchedBridge',
     'RCTGeolocation'
     # Add any other subspecs you want to use in your project
   ]
   pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
   pod 'Firebase', '4.11.0'
   pod 'Firebase/Core', '4.11.0'
   pod 'Firebase/Messaging', '4.11.0'
   pod 'Firebase/DynamicLinks', '4.11.0'
   pod 'Firebase/AdMob', '4.11.0'
   pod 'Firebase/RemoteConfig', '4.11.0'

   pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
   pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
   pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
   #---https://github.com/facebook/react-native/issues/20031 end//

   # react-native-maps dependencies
   pod 'react-native-maps', path: rn_maps_path
   # pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
   # https://github.com/react-community/react-native-maps/issues/1582
   pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
   # pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS
   # https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md

   pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
   pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'

   pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

 end


 post_install do |installer|
   installer.pods_project.targets.each do |target|
       if target.name == 'yoga'
           target.build_configurations.each do |config|
               config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
               config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
           end
       end

     target.build_configurations.each do |config|
       config.build_settings['SWIFT_VERSION'] = '3.0'
     end
   end
 end


 pre_install do |installer|
   # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
   Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
 end

 # [!] [Xcodeproj] Generated duplicate UUIDs:
 # https://github.com/CocoaPods/CocoaPods/issues/4370
 install! 'cocoapods',
          :deterministic_uuids => false

```

#### `AppDelegate.m`:

```objc
   [FIRApp configure];

   // fcm
   [FIRMessaging messaging].delegate = self;

   if ([UNUserNotificationCenter class] != nil) {
     // iOS 10 or later
     // For iOS 10 display notification (sent via APNS)
     [UNUserNotificationCenter currentNotificationCenter].delegate = self;
     UNAuthorizationOptions authOptions = UNAuthorizationOptionAlert |
       UNAuthorizationOptionSound | UNAuthorizationOptionBadge;
     [[UNUserNotificationCenter currentNotificationCenter]
       requestAuthorizationWithOptions:authOptions
                     completionHandler:^(BOOL granted, NSError * _Nullable error) {
         // ...
       }];
   } else {
     // iOS 10 notifications aren't available; fall back to iOS 8-9 notifications.
     UIUserNotificationType allNotificationTypes =
       (UIUserNotificationTypeSound | UIUserNotificationTypeAlert | UIUserNotificationTypeBadge);
     UIUserNotificationSettings *settings =
       [UIUserNotificationSettings settingsForTypes:allNotificationTypes categories:nil];
     [application registerUserNotificationSettings:settings];
   }

   [application registerForRemoteNotifications];
   // fcm
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - Xcode 10.1
- **`React Native` version:**
  - `0.57.4`
- **`React Native Firebase` library version:**
  - `5.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [x] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by manurana** [comment]
If I understand correctly, this is preventing the integration of any other service that sends its own messages to the app. For us, the particular service is CleverTap. The app is not able to show any CleverTap initiated messages. 
Would love to see this resolved sooner rather than later.
One implementation could be [how Segment has done it](https://github.com/intercom/intercom-ios/blob/fa65161e1d33c29aea96cb5feb128ed3e42957e7/Intercom.framework/Headers/Intercom.h#L276-L287).

**Comment by Salakar** [comment]
Hey, I've pushed up something for this in https://github.com/invertase/react-native-firebase/commit/0b052d684ca0e3ea1e9116aafcc4c3c60f6a1efc - simply implementing the `FIRMessagingDelegate` methods in your `AppDelegate` will now allow them to be called. This will land as part of PR #3339
