### ISSUE TITLE
RNFirebase.Auth onAuthStateChanged listener is calling multiple times with different users in result (android only)

### ISSUE THREAD

**Issue by rgaraev** [invertase/react-native-firebase#1815]
Hello, RNFirebase team and all users!

## Issue

I listen changing of the auth state: 

**componentDidMount() {
firebase.auth().onAuthStateChanged((user) => {
console.log('user: ', user);
}**

the app start to return anonymous user multiple times without stopping and every time anonymous user is new (different from previous).
The error occurs on only on android (8.1). on iOS 12 works perfect.  
**BUT!**
I investigated further around my problem. I've found that the error occurs when I add onAuthStateChanged listener in other react components. If i do it in 3 and more components the error start to occur.

### React native 
I use
 "react-native": "^0.57.8",
 "react-native-firebase": "^5.2.0",

### Android
 I set compileSdkVersion = 27
 'com.google.firebase:firebase-auth:16.1.0'

 Did somebody face the same problem? 
 Thank all in advance!

**Comment by Ehesp** [comment]
Hm, you say "a new user every time" - is this a new anonymous user? Could we see your code to understand the flow of how you're handling it within React?

**Comment by rgaraev** [comment]
@Ehesp, thank you for the response. I'm sorry about my English.
Yes, the app start to return anonymous user multiple times without stopping and every time anonymous user is new (different from previous). 
About my flow. It's simple. 

**componentDidMount() {
firebase.auth().onAuthStateChanged((user) => {
console.log('user: ', user);
}**

BUT!
I investigated further around my problem. I've found that the error occurs when I add **onAuthStateChanged** listener in other react components. If i do it in 3 and more components the error start to occur. 
 I also updated issue text.

**Comment by rgaraev** [comment]
@Ehesp, I've refactored my code to avoid parallel **onAuthStateChanged** listeners. 
I need to say I'm newbie in react native world. I only started my learning process. I think my problem from my low level o knowledge. If I will use Redux state container I can escape problems like this. 
I think we can close this issue. 
@Ehesp, thank you for your response!
