### ISSUE TITLE
🔥firebase.utills() not accessible in the app

### ISSUE THREAD

**Issue by zaka5192** [invertase/react-native-firebase#1816]
Hello there

## Issue

firebase.utils().errorOnMissingPlayServices = false;
throws error like 
"src/App.tsx(140,14): error TS2339: Property 'utils' does not exist on type 'Firebase'."

![screen shot 2019-01-09 at 7 03 00 pm](https://user-images.githubusercontent.com/42166955/50904096-3c620f80-1441-11e9-89dd-d384296a0f11.png)

![screen shot 2019-01-09 at 7 02 14 pm](https://user-images.githubusercontent.com/42166955/50904114-46840e00-1441-11e9-825f-7d1e88e1c086.png)

![screen shot 2019-01-09 at 7 02 29 pm](https://user-images.githubusercontent.com/42166955/50904121-4d128580-1441-11e9-82a5-30bb270e5d44.png)

the messaging part is working fine and app builds when I comment the utills() code. Also the app crashes in release.apk due to google-play-services dependency issue.

so how to bypass this. Any sort of help will be appreciated.

---

## Project Files

here is my app/build.gradle dependencies

![screen shot 2019-01-09 at 7 07 00 pm](https://user-images.githubusercontent.com/42166955/50904342-d924ad00-1441-11e9-9e8a-8fde0db5b872.png)

here is build.gradle

![screen shot 2019-01-09 at 7 08 41 pm](https://user-images.githubusercontent.com/42166955/50904433-125d1d00-1442-11e9-9c4d-c1f614b2792c.png)

and here is Manifest.xml
![screen shot 2019-01-09 at 7 09 55 pm](https://user-images.githubusercontent.com/42166955/50904504-446e7f00-1442-11e9-82d9-68d3e1947e7a.png)

![screen shot 2019-01-09 at 7 10 22 pm](https://user-images.githubusercontent.com/42166955/50904536-56e8b880-1442-11e9-981e-c16cd0701d23.png)

### iOS

iOS working fine with messaging.

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - Android API 27
- **Operating System:**
  - [ ] MacOS, version: iOS 10.13.6
- **Build Tools:**
  - 3.2.0
- **`React Native` version:**
  - react-native-cli: 2.0.1, react-native: 0.53.2
- **`React Native Firebase` library version:**
  - "react-native-firebase": "^5.1.1",
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [x] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [x] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] Yes, version: `2.7.2`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No

---

**Comment by Salakar** [comment]
@zaka5192 thanks for the detailed issue. Looks like the TS types for utils have not been done yet;

If anyone has the time to contribute then a PR would be most welcome;

Types:
https://github.com/invertase/react-native-firebase/blob/master/src/index.d.ts#L82
https://github.com/invertase/react-native-firebase/blob/master/src/index.d.ts#L60

Utils Module API:
https://github.com/invertase/react-native-firebase/tree/master/src/modules/utils

Otherwise; we'll get this looked at in due course.

**Comment by Salakar** [comment]
Hey 👋 

I'm going to go ahead and close this as it's fixed in the upcoming v6 release. PRs to fix the types on v5 are still welcome though.

Thanks
