### ISSUE TITLE
🔥PN's are not dismissed in foreground on android

### ISSUE THREAD

**Issue by LorandP** [invertase/react-native-firebase#1821]
## Issue

Hello, only on android, when a PN is displayed on foreground and is clicked, it is not dismissing from the status bar. It has to be dismissed manually, otherwise it is not getting dismissed.

In other case, if the PN is received while the app is in background or is closed, and the PN is clicked, then the notification it gets dismissed.

I have also tried adding `removeDeliveredNotifications` but this just does nothing.

---

#### `ios/Podfile`:

end
- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

}
```objc
// N/A
```

---

#### `android/build.gradle`:
`buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath 'com.google.gms:google-services:3.2.1'
        classpath "com.newrelic.agent.android:agent-gradle-plugin:5.17.2"
    }
}

allprojects {
    repositories {
        google()
        // Add jitpack repository (added by react-native-spinkit)
        maven { url "https://jitpack.io" }
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url 'https://mobile.useinsider.com'}
        mavenCentral()
        maven { url "https://dl.bintray.com/android/android-tools/" }
    }
}

subprojects {project ->
    if (
        project.name.contains('react-native-blur') ||
        project.name.contains('react-native-insider') ||
        project.name.contains('react-native-vector-icons')
    ) {
        buildscript {
            repositories {
                maven { url "https://dl.bintray.com/android/android-tools/" }
            }
        }
    }
    if (project.name.contains('react-native-fabric')) {
        buildscript {
            repositories {
                google()
                jcenter()
            }
        }
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}

subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}
`
```groovy
// N/A
```

#### `android/app/build.gradle`:
`android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.apparel.app"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 100
        versionName "2.4.3"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        renderscriptTargetApi 23
        renderscriptSupportModeEnabled true
        multiDexEnabled true
        manifestPlaceholders = [ partner : project.env.get("INSIDER_PARTNER_NAME")]
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            storeFile file(MYAPP_RELEASE_STORE_FILE)
            storePassword MYAPP_RELEASE_STORE_PASSWORD
            keyAlias MYAPP_RELEASE_KEY_ALIAS
            keyPassword MYAPP_RELEASE_KEY_PASSWORD
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        // These docs use an open ended version so that our plugin
        // can be updated quickly in response to Android tooling updates

        // We recommend changing it to the latest version from our changelog:
        // https://docs.fabric.io/android/changelog.html#fabric-gradle-plugin
        classpath 'io.fabric.tools:gradle:1.25.4'
    }
}

dependencies {
    compile project(':react-native-fabric')
    // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:16.0.1"
    implementation 'com.google.firebase:firebase-core:16.0.6'
    implementation "com.google.firebase:firebase-messaging:17.3.4"
    implementation "com.google.firebase:firebase-auth:16.1.0"
    implementation "com.google.firebase:firebase-firestore:17.1.4"
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.android.gms:play-services-tagmanager:16.0.6'
    implementation 'com.google.android.gms:play-services-location:16.0.0'

    // New Relic
    implementation "com.newrelic.agent.android:android-agent:5.17.2"

    // Insider
    compile (project(':react-native-insider')) {
        exclude group: 'com.google.firebase'
        exclude group: 'com.google.android.gms'
    }
}

subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'`

```groovy
// N/A
```

#### `android/settings.gradle`:
`rootProject.name = 'app'
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
include ':app'
`
```groovy
// N/A
```

#### `MainApplication.java`:
`
import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;
import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;
import io.invertase.firebase.auth.RNFirebaseAuthPackage;
import io.invertase.firebase.firestore.RNFirebaseFirestorePackage;
import io.invertase.firebase.analytics.RNFirebaseAnalyticsPackage;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new RNFirebasePackage(),
        new RNFirebaseMessagingPackage(),
        new RNFirebaseNotificationsPackage(),
        new RNFirebaseAuthPackage(),
        new RNFirebaseFirestorePackage(),
        new RNFirebaseAnalyticsPackage(),
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    Branch.getAutoInstance(this);
  }
}
`

```java
// N/A
```

#### `AndroidManifest.xml`:
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.apparel.app"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <application
      android:name=".MainApplication"
      xmlns:tools="http://schemas.android.com/tools"
      android:supportsRtl="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:theme="@style/AppTheme">

        <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>

        <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />

        <receiver android:name="io.invertase.firebase.notifications.RNFirebaseNotificationReceiver"/>
        <receiver android:enabled="true" android:exported="true"  android:name="io.invertase.firebase.notifications.RNFirebaseNotificationsRebootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </receiver>

        <activity
        android:name=".MainActivity"
        android:screenOrientation="portrait"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
            </intent-filter>

            <intent-filter android:label="filter_react_native">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="app" />
            </intent-filter>

      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="app-channel"/>

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@mipmap/ic_notification" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/gray_400" />

    </application>
</manifest>
`
```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - Android 6.0, 7.11, 8.0, 9.0 all the platforms that I have tested on
- **Operating System:**
  - [x ] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - Android Studio 3.2
- **`React Native` version:**
  - 0.57.7
- **`React Native Firebase` library version:**
  - 4.3.8
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [x ] Cloud **Firestore**
  - [x] Cloud **Messaging** (FCM)
  - [x] Crashlytics
  - [x] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by GabrielePrestifilippo** [comment]
Hi, @LorandP try using [removeDeliveredNotification](https://rnfirebase.io/docs/v5.x.x/notifications/reference/Notifications#removeDeliveredNotification)

**Comment by LorandP** [comment]
Hi @GabrielePrestifilippo , thanks for your help but unfortunately only `removeDeliveredNotifcation` is not working.
Sometimes I also get that this error:

> TypeError: _reactNativeFirebase.default.notifications(...).removeDeliveredNotifcation is not a function

My implementation is

`this.notificationOpenedListener = firebase.notifications().onNotificationOpened(async (notificationOpen) => {
        // Get information about the notification that was opened
        const notification = notificationOpen.notification;
        const notificationID = notification.notificationId;
        firebase.notifications().removeDeliveredNotifcation(notificationID)

        NotificationService.handleNotificationData(notification.data);
        Insider.handleNotification(notification.data);
      });`

**Comment by Zaporozhec7** [comment]
I have same issue. I found that removeDeliveredNotifcation() fail to remove that notifications which has tag set. So I made temporary workaround, which seems work for me:
 ```
   if(Platform.OS === 'android' && typeof notification.android.tag === 'string'){
        let tag: string = notification.android.tag;
        Firebase.notifications().android.removeDeliveredNotificationsByTag(tag);
    } else {
        Firebase.notifications().removeDeliveredNotification(notification.notificationId);
    }
```
@LorandP , try this, while issue not fixed

**Comment by LorandP** [comment]
@Zaporozhec7 Thank you for your help! Yes, I can confirm that this solution works but only from version 5.1.0 and above.
I have tried with 5.1.0 and 5.2.2 and it worked on both but on my current version (4.3.8) it did not work.

I have seen that in version v5.1.0-rc1 they have released a fix for `removeDeliveredNotificationsByTag ` and I think that fixed it.
