### ISSUE TITLE
Can't use setbadge when app is not in foreground

### ISSUE THREAD

**Issue by faustoct** [invertase/react-native-firebase#1824]
Piece of code 
````
    /*
    * Triggered when a particular notification has been received in foreground
    * */
    this.notificationListener = firebase.notifications().onNotification((notif) => {
        const { title, body, data } = notif;
        const notification = new firebase.notifications.Notification()
        .setNotificationId('notificationId')
        .setTitle(notif.title)
        .setBody(notif.body)
        .setData(notif.data);
        if(Platform.OS == 'ios'){
          notification.ios.setBadge(1)
        } else if(Platform.OS == 'android'){
          //notification.setShortBadger(1)
        }
        firebase.notifications().displayNotification(notification)
    });

    /*
    * If your app is in background, you can listen for when a notification is clicked / tapped / opened as follows:
    * */
    this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
        const { title, body, data } = notificationOpen.notification;
        alert(title)
        alert(body)
        alert(data)
    });

    /*
    * If your app is closed, you can check if it was opened by a notification being clicked / tapped / opened as follows:
    * */
    const notificationOpen = await firebase.notifications().getInitialNotification();
    if (notificationOpen) {
        const { title, body, data } = notificationOpen.notification;
        alert(title)
        alert(body)
        alert(data)
    }
````

can't use setbadge when app closed/kill or background

**Comment by MinaFSedrak** [comment]
any update ?

**Comment by ThienMD** [comment]
why closed?

**Comment by jegathispandi** [comment]
what is the fix for this issue? why are you closed this issue?

**Comment by mikehardy** [comment]
This is not a fantastic answer - let me say that first - but I have given up on setBadge as anything other than a curious "maybe" feature. It is not an Android platform feature and is hacked on with the badger dependency, via attempts to cover the specific launchers for various vendors. But the vendors move their APIs, some don't implement it (namely: the pixel launcher) so it seems a bit pointless to me. If it's a core feature you'll have to work with the badger project most likely

**Comment by jegathispandi** [comment]
I am unable to setBadge() when app is running in background. once we open the app I can able to setBadge using firebase. Is it possible to setBadge() when app is running in background

**Comment by mikehardy** [comment]
Maybe? You don't specify platform. on iOS I do it and it works, as part of a cloud message handler. on Android as mentioned above I "try" but expect failure and in general don't care, I reasoned changing requirements to not be hard in this spot was easier than fighting the platform :man_shrugging:

**Comment by jegathispandi** [comment]
My platform is android. could you please share your code for IOS? as you said its working fine for IOS

**Comment by mikehardy** [comment]
As mentioned I general consider this a bad requirement for an app, so I won't respond past this, but I literally just call `firebase.notifications().setBadge(1)` in code

**Comment by jegathispandi** [comment]
where did you call this? app.js or landingpage.js?. Is it working fine in backgroud? I mean without opening app It should update the notificationcount in app icon.

**Comment by jegathispandi** [comment]
could you please respond?

**Comment by mikehardy** [comment]
> As mentioned I general consider this a bad requirement for an app, so I won't respond past this, but I literally just call `firebase.notifications().setBadge(1)` in code

**Comment by dhevendhiran-adt** [comment]
Hey, still I can't get the badge count on ios when the app is in the background and closed. I am sharing a piece of code what I have used to get notifications
```
this.notificationListener = firebase
      .notifications()
      .onNotification(async (notification) => {

        const localNotification = new firebase.notifications.Notification({ show_in_foreground: false })
          .setNotificationId(notification.notificationId)
          .setTitle(notification.title)
          .setBody(notification.body)
          .setData(notification.data)
          .android.setChannelId("fcm_default_channel")
          .android.setSmallIcon("@drawable/wasfat")
          .android.setAutoCancel(true)
          .android.setColor("#b61b33")
          .android.setPriority(firebase.notifications.Android.Priority.High);

        let badgeCount = await firebase.notifications().getBadge();
        firebase.notifications().setBadge(badgeCount + 1);

        firebase.notifications().displayNotification(localNotification).catch(err => { });
      });
```

from the above code, I'm getting notification very fine in all cases. But I'm able to get badge count, only app is in the foreground.

Please suggest, If anything I have missed to get badge count when the app is in the background and closed. 

I am facing this only on ios. For android, it is working fine without the setBadge() method.

Thanks for any help.
