### ISSUE TITLE
🔥 Unable to build in Release. Error in CompileC RNFirebaseFunctions.m ...

### ISSUE THREAD

**Issue by agarant** [invertase/react-native-firebase#1825]
## Issue

I can build in dev, but I cannot create a release. Below is the compile step that is failing. What is strange is that I'm not using RNFirebaseFunctions.
```
The following build commands failed:
CompileC /Users/<user-name>/Library/Developer/Xcode/DerivedData/<project-name>-hcxhqlbhbudqgmcfgzxtkqhvdlpb/Build/Intermediates.noindex/ArchiveIntermediates/<project-name>/IntermediateBuildFilesPath/RNFirebase.build/Release-iphoneos/RNFirebase.build/Objects-normal/armv7/RNFirebaseFunctions.o RNFirebase/functions/RNFirebaseFunctions.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```
I tried adding  RNFirebaseFunctions but got these 2 compilation errors:
```
CompileC /Users/<user-name>/Library/Developer/Xcode/DerivedData/<project-name>-hcxhqlbhbudqgmcfgzxtkqhvdlpb/Build/Intermediates.noindex/ArchiveIntermediates/<project-name>/IntermediateBuildFilesPath/RNFirebase.build/Release-iphoneos/RNFirebase.build/Objects-normal/armv7/RNFirebaseFunctions.o RNFirebase/functions/RNFirebaseFunctions.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
CompileC /Users/<user-name>/Library/Developer/Xcode/DerivedData/<project-name>-hcxhqlbhbudqgmcfgzxtkqhvdlpb/Build/Intermediates.noindex/ArchiveIntermediates/<project-name>/IntermediateBuildFilesPath/RNFirebase.build/Release-iphoneos/RNFirebase.build/Objects-normal/armv7/RNFirebaseAdMobRewardedVideo.o RNFirebase/admob/RNFirebaseAdMobRewardedVideo.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

### Things that I tried without success:
- The clean xcode routine. (clean, exit, rm derived, pod install, clean, build)
- Removing use_framework and use module_headers instead
- Cleaning pods (deintegrate, rm -rf Pods, etc)
- Reverting to react-native-firebase 5.0.0
- Adding pod 'Firebase/Functions', '~> 5.15.0'
- Adding pod 'Firebase/AdMob', '~> 5.15.0'

### Other info
- I was using react-native-firebase 4.3.x and it worked. I upgraded to 5.2.0 after upgrading to RN 0.57.8. I did follow the migration steps for 5.0.0, 5.1.0 & 5.2.0 from the release notes.
- I'm building for release using [Faslane](https://docs.fastlane.tools/getting-started/ios/appstore-deployment/). ```build_app(scheme: "<project-name>", workspace: "<project-name>.xcworkspace")```

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '9.0'

target '<project-name>' do
  use_frameworks!

  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'

  target '<project-name>Tests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [x] MacOS, version: `10.13.6 `
  - [ ] Windows
  - [ ] Other
- **Build Tools:**
  - Xcode 10 -  Legacy build system
- **`React Native` version:**
  - 0.57.8
- **`React Native Firebase` library version:**
  - 5.2.0
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [x] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [x] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by Salakar** [comment]
Make sure you're building using the correct version on fastlane as this error sounds like you're using an older xcode version to build with;

https://docs.fastlane.tools/actions/xcversion/

**Comment by agarant** [comment]
That was it, thank you! 😀  Quick question, what in the error message tip you that I was using an older xcode version ?

**Comment by henrymoulton** [comment]
I've come across this error while using App Center Build, any reason this would happen?

**Comment by henrymoulton** [comment]
CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/Encounter-egxnnpwevwecdmffslmntmpovzrq/Build/Intermediates.noindex/ArchiveIntermediates/Encounter/IntermediateBuildFilesPath/RNFirebase.build/Release-iphoneos/RNFirebase.build/Objects-normal/armv7/RNFirebaseAdMob.o RNFirebase/admob/RNFirebaseAdMob.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/vsts/agent/2.155.1/work/1/s/Encounter/node_modules/react-native-firebase/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode_10.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode_10.3.app/Contents/Developer/usr/bin:/Library/Frameworks/Mono.framework/Versions/4/bin:/Users/vsts/.nvm/versions/node/v10.16.3/bin:/usr/local/lib/ruby/gems/2.6.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/vsts/bin:/Users/vsts/.yarn/bin:/usr/local/go/bin:/Users/vsts/Library/Android/sdk/tools:/Users/vsts/Library/Android/sdk/platform-tools:/Users/vsts/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/vsts/.azcopy"
    /Applications/Xcode_10.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditio...

** ARCHIVE FAILED **



The following build commands failed:
	CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/Encounter-egxnnpwevwecdmffslmntmpovzrq/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/RNFirebase.build/Release-iphoneos/RNFirebase.build/Objects-normal/armv7/RNFirebaseAdMobRewardedVideo.o RNFirebase/admob/RNFirebaseAdMobRewardedVideo.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by mikehardy** [comment]
@henrymoulton you posted incomplete information on a bug closed in January, that's not going to result in a good use of anyone's time. Please file a new bug with template fully filled out. Simply based on your error snippet though, I'd make 100% sure you had a fully up to date Google MobileAds SDK (failing to compile on that object smells like #2363) and you might `npm i -g react-native-clean-project && react-native clean-project-auto` to wipe out any stale Xcode derived data cache
