### ISSUE TITLE
Android Dex issue

### ISSUE THREAD

**Issue by isurugajasinghe** [invertase/react-native-firebase#1828]
I used react native 0.57 version and latest firebase version 
iOS working fine but android failed

I got the this issue from android studio 

**Error: Cannot fit requested classes in a single dex file (# methods: 67342 > 65536)**

**Comment by Salakar** [comment]
Please correctly fill out the issue template, without this, we can not help or guess your configuration. 

Locking and closing this issue. Feel free to raise another issue that correctly follows the issue template.
