### ISSUE TITLE
Get/Set badge number at background.

### ISSUE THREAD

**Issue by niros001** [invertase/react-native-firebase#183]
Hi i can use the get/set badge number while app is open, but sometimes i need to increment the bade number while app is closed/background. How can i do it?

**Comment by chrisbianca** [comment]
@niros001 you can set the badge as part of the notification message body.  The spec is here: https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support

By doing this, the OS should set the badge automatically - it definitely works on iOS and think it works on Android now too.

**Comment by niros001** [comment]
But that parameter require a number... i just need to increment by +1 but i don't know the badge number to increment.

**Comment by chrisbianca** [comment]
Unfortunately, the only way to do this in the background would be for your server to have some idea of what the number should be and set it that way.

**Comment by niros001** [comment]
That my last option that i want but thanks anyway.

**Comment by haseebnaseem** [comment]
@chrisbianca can you please confirm that it works on android. I want to update the badge when the app is in the background or when it is closed. However I am not able to get it to work on android emulator.

**Comment by aMarCruz** [comment]
@haseebnaseem , I think this works only in Android 8 and later, real devices. But depends on the launcher in use.

**Comment by kkusanagi** [comment]
As to update badge number in Android, you need to set code manually.
`firebase.notifications().setBadge(3);`

For IOS, set badge in payload can be done.

**Comment by giomv** [comment]
> As to update badge number in Android, you need to set code manually.
> `firebase.notifications().setBadge(3);`
> 
> For IOS, set badge in payload can be done.

If the app is closed or in background, is there a method which will be called when the notification arrives (not when tapped)? I ask this in order to place this function: 

`firebase.notifications().setBadge(3);`
