### ISSUE TITLE
:fire getScheduledNotificatons not working on iOS

### ISSUE THREAD

**Issue by theoryweary** [invertase/react-native-firebase#1830]
## Issue
  firebase.notifications().getScheduledNotifications does not return on iOS.  On Android this works perfectly.

This was working for me last month on react-native-firebase 5.1. It stopped working while I still had react-native-firebase 5.1 installed. I just tried upgrading to react-native-firebase 5.2 but I'm seeing the same issue. 

---

## Project Files
Here's how I'm trying to read the scheduled notifications
 ` console.log('local notification scheduled')
  firebase.notifications().getScheduledNotifications().then((notifications) => {
    console.log('logging notifications', notifications)
    notifications.forEach(n => console.log(
      'notificaiton log', n, 'fireTime', moment(n.schedule.fireDate).toDate()
    ))
  })`

However, this logging generates the following error, which makes me think that the notifications are never getting scheduled: 

YellowBox.js:67 Possible Unhandled Promise Rejection (id: 1):
TypeError: Cannot read property 'fireDate' of undefined
TypeError: Cannot read property 'fireDate' of undefined
    at blob:http://192.168.1.5:8081/fb97e98f-eb69-48f6-8e54-81e1907577c9:160507:95
    at Array.forEach (<anonymous>)
    at blob:http://192.168.1.5:8081/fb97e98f-eb69-48f6-8e54-81e1907577c9:160506:21
    at tryCallOne (blob:http://192.168.1.5:8081/fb97e98f-eb69-48f6-8e54-81e1907577c9:3291:14)
    at blob:http://192.168.1.5:8081/fb97e98f-eb69-48f6-8e54-81e1907577c9:3392:17
    at blob:http://192.168.1.5:8081/fb97e98f-eb69-48f6-8e54-81e1907577c9:22141:21
    at _callTimer (blob:http://192.168.1.5:8081/fb97e98f-eb69-48f6-8e54-81e1907577c9:22030:9)
    at _callImmediatesPass (blob:http://192.168.1.5:8081/fb97e98f-eb69-48f6-8e54-81e1907577c9:22066:9)
    at Object.callImmediates (blob:http://192.168.1.5:8081/fb97e98f-eb69-48f6-8e54-81e1907577c9:22285:14)
    at MessageQueue.__callImmediates (blob:http://192.168.1.5:8081/fb97e98f-eb69-48f6-8e54-81e1907577c9:2754:16)`

#And here is how I'm scheduling Notificaitons:

`const scheduleLocalNotification = ({
  Title,
  Body,
  targetScreen = 'Home'
}) => {
  let notification = new firebase.notifications.Notification();
  notification = notification.setNotificationId(new Date().valueOf().toString())
  .setTitle(Title)
  .setBody(Body)
  .setSound('default')
  .setData({
    targetScreen,
  });`

`// Schedule the notification for 1 minute in the future - for testing
  const date = new Date();
  date.setMinutes(date.getMinutes() + 1);`

`//schedule Notifcation
  firebase.notifications().scheduleNotification(notification, {
      fireDate: date.getTime(),
    }
  )
export default scheduleLocalNotification;`

I used the react-native-firebase starter package to configure this project in November 2018. 
#### `ios/Podfile`:
`platform :ios, '9.0'`

`target 'frenergy' do`

  `# Required by RNFirebase
  pod 'Firebase/Core', '~> 5.11.0'`

  `# [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/AdMob', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Database', '~> 5.11.0'
  pod 'Firebase/Functions', '~> 5.11.0'
  pod 'Firebase/DynamicLinks', '~> 5.11.0'
  pod 'Firebase/Firestore', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
  pod 'Firebase/RemoteConfig', '~> 5.11.0'
  pod 'Firebase/Storage', '~> 5.11.0'
  pod 'Firebase/Performance', '~> 5.11.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.9'`

 `pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'`

  `pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'`

  `pod 'RNIap', :path => '../node_modules/react-native-iap'
end`
`

```ruby
# N/A
```

#### `AppDelegate.m`:

#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>
#import "RNSplashScreen.h"  // here

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  NSURL *jsCodeLocation;
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"frenergy"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  [RNSplashScreen show];  // here
  return YES;
}

@end

```objc
// N/A
```

---

#### `android/build.gradle`:
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
  ext {
    buildToolsVersion = "28.0.2"
    minSdkVersion = 18
    compileSdkVersion = 27
    targetSdkVersion = 26
    supportLibVersion = "27.1.1"
  }
  repositories {
    google()
    jcenter()
    maven {
      url 'https://maven.fabric.io/public'
    }
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:3.2.1'
    classpath 'com.google.gms:google-services:4.0.1'
    classpath 'com.google.firebase:firebase-plugins:1.1.5'
    classpath 'io.fabric.tools:gradle:1.25.4'
    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
  }
}

allprojects {
  repositories {
    mavenLocal()
    google()
    jcenter()
    maven {
      // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
      url "$rootDir/../node_modules/react-native/android"
    }
  }
}

task wrapper(type: Wrapper) {
  gradleVersion = '4.6'
  distributionUrl = distributionUrl.replace("bin", "all")
}

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment
Testing on a real iPhone 6, iOS 12.1.2

- **Platform that you're experiencing the issue on**:
  - [x ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [ ] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `ADD_SOMETHING_HERE` e.g. Xcode 10, Android Studio 3.2
XCode 10
- **`React Native` version:**
  - `ADD_SOMETHING_HERE`
- **`React Native Firebase` library version:**
  - `ADD_SOMETHING_HERE`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [x ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [ X] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

**Comment by theoryweary** [comment]
Gah, I found that the schedule does not exist on each notification object, but that I can just put the fireDate in the data object on each notification.   I don't understand why this isn't consistent across iOS and Android though.

**Comment by harrydema** [comment]
Remember that on IOS you should ask for push notification permissions.
