### ISSUE TITLE
Tapping Notification not opening the app

### ISSUE THREAD

**Issue by aflahkp** [invertase/react-native-firebase#1838]
When a push notification is received, tapping on the notification from the notification tray not opening the app. Also the onNotificationOpened method is not getting Called.
At the same time When notification was pushed from firebase console it opens the app on tap. Also the onNotificationOpened is getting called. Is there some thing to code for getting the app opened from notification Tap..??

Using
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.4",
    "react-native-firebase": "^5.0.0",

**Comment by santoshdahal12** [comment]
Even I am facing the same problem. I also have same version of react native and react-native firebase

**Comment by aflahkp** [comment]
is there something to do with the server side code?

**Comment by IljaDaderko** [comment]
@aflahkp could you please fill out issue template. This will help a lot while debugging i.e. library versions, ios / android implementation, react version etc...

**Comment by aflahkp** [comment]
> @aflahkp could you please fill out issue template. This will help a lot while debugging i.e. library versions, ios / android implementation, react version etc...

Thanks for responding. Closing this issue as i raised a  new Issue following the template. #1854

**Comment by phonganhhung9xtb** [comment]
what about iOS? i face same issue.when app killed if i click on notification app crashed.
