### ISSUE TITLE
Invalid Key. Keys must not contain '/','.''#','$','[' or ']' 

### ISSUE THREAD

**Issue by addu1** [invertase/react-native-firebase#1839]
## Issue

I'm trying to write to realtime database. The code i use to push the data is here:

 var postData = {
      uid: uid,
      body: 'body',
      title: 'title',
      starCount: 0,
    };

    // Get a key for a new Post.
    var newPostKey = firebase.database().ref().child('posts').push().key;

    // Write the new post's data simultaneously in the posts list and the user's post list.
    var updates = {};
    updates[`/posts/${newPostKey}`] = postData;
    updates[`/user-posts/${uid}/${newPostKey}`] = postData;
    firebase.database().ref().update({updates},
      function (error) {
        if(error){
          console.log("POST CREATION ERROR ", error )
        }else{
          console.log("CREATED")
        }
      })

i Call this on a button click and get the error "invalid key".
I've attached a screenshot of the error.
![screenshot_20190117_130132_com addu getstarted](https://user-images.githubusercontent.com/17162834/51302506-92920c80-1a58-11e9-917d-b16d9df624e8.jpg)

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [ ] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `ADD_SOMETHING_HERE`
- **`React Native` version:**
  - `0.58.0-rc.2`
- **`React Native Firebase` library version:**
  - `^5.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [x] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

**Comment by Salakar** [comment]
What version of React Native Firebase is this? Please update the issue template. 👀

**Comment by addu1** [comment]
@Salakar I've updated the issue.

**Comment by IljaDaderko** [comment]
@addu1 I believe you need to change this line

```js
firebase.database().ref().update({updates},
  function (error) ...
```

to

```js
firebase.database().ref().update(updates,
  function (error) ...
```

as `updates` is already an object, you could spread it as well `{...updates}`, but in this context there is no use for spread operator.

**Comment by addu1** [comment]
@IljaDaderko thank you so much. That worked.

**Comment by Ehesp** [comment]
This is handled in v6 and throws a JS side error.
