### ISSUE TITLE
firebase.links().createShortDynamicLink(link) on iOS

### ISSUE THREAD

**Issue by dantn93** [invertase/react-native-firebase#1842]
## Issue

I want to create a short link with react native firebase, but it shows the bug

Possible Unhandled Promise Rejection (id: 0):
Error: Failed to create Short Dynamic Link
Error: Failed to create Short Dynamic Link
    at createErrorFromErrorData (blob:http://localhost:8081/a665695c-110f-44e8-beae-c6796939d649:2064:17)
    at blob:http://localhost:8081/a665695c-110f-44e8-beae-c6796939d649:2016:27
    at MessageQueue.__invokeCallback (blob:http://localhost:8081/a665695c-110f-44e8-beae-c6796939d649:2458:18)
    at blob:http://localhost:8081/a665695c-110f-44e8-beae-c6796939d649:2203:18
    at MessageQueue.__guardSafe (blob:http://localhost:8081/a665695c-110f-44e8-beae-c6796939d649:2371:11)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:http://localhost:8081/a665695c-110f-44e8-beae-c6796939d649:2202:14)
    at http://localhost:8081/debugger-ui/debuggerWorker.js:70:58

I use the package versions:
- react-native: 0.55.4
- react-native-firebase: 4.3.8
- platform: iOS
- Pod file: 
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/DynamicLinks', '~> 5.3.0'

When I install my pod file, why does it show:
Installing Firebase (5.3.0)
Installing FirebaseAnalytics (5.0.1)
Installing FirebaseCore (5.0.4) ???
Installing FirebaseDynamicLinks (3.0.1) ???

**Comment by IljaDaderko** [comment]
@dantn93 Could you please add your JS implementation to help with debugging this?

Can you confirm that your `Podfile` includes following and try running `pod update`

```ruby
pod 'Firebase/Core', '~> 5.3.0'
pod 'Firebase/DynamicLinks', '~> 5.3.0'
```

**Comment by dantn93** [comment]
@IljaDaderko 
my source:

const link = new firebase.links.DynamicLink(`https://${url}`, Config.FIREBASE_DEEPLINK_DOMAIN)
      .android.setPackageName(Config.BUNDLE_ID)
      .ios.setBundleId(Config.BUNDLE_ID);

      firebase.links()
      .createShortDynamicLink(link, 'UNGUESSABLE')
      .then((url) => {

When I use the "createDynamicLink" function, it creates the long link (OK)
But I need to create a short link and it has a failure

**Comment by Salakar** [comment]
@dantn93 could you add the promise catch as suggested above, so we can see what the actual error is please. Thanks

**Comment by dantn93** [comment]
> @dantn93 could you add the promise catch as suggested above, so we can see what the actual error is please. Thanks

@Salakar  I done
I configurated the whitelist URL pattern. Thanks!

**Comment by affanhashone** [comment]
@Salakar  How Did u fix it ?

**Comment by affanhashone** [comment]
@dantn93  How did you fixed it ?

**Comment by Surinderkaur329** [comment]
@dantn93  How did you fixed it ?

Its not working with ios latest.

**Comment by mikehardy** [comment]
@Surinderkaur329 can you be more precise?

>  Its not working with ios latest

Versions move quickly and these comments last forever, exactly what version is "latest"

**Comment by Surinderkaur329** [comment]
Hi Mike

Version:

platform :ios, '11.0'

pod 'Firebase/Analytics', '~> 7.0.0'
pod 'Firebase/DynamicLinks', '~> 7.0.0'

'createShortDynamicLink'  Its working well with android to create shortlink but in ios its not working.

Please suggest if any setting need to required. Its really important ..

**Comment by mikehardy** [comment]
@surendharreddy you are using old versions, and you are specifying them manually? You should not do that.

Use current stable here (react-native-firebase v12) and that will pull in firebase-ios-sdk v8.0.0.
I create short dynamic links in my project and they work? So you may have a code issue as well, but the module here should be working.

If you are able to reproduce a failure please make a minimum reproducible example https://stackoverflow.com/help/minimal-reproducible-example perhaps based on https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh in a new issue here where you fill out the relevant details in the issue and we may triage it to see what is going on

**Comment by Surinderkaur329** [comment]
Hi @mikehardy 

Any suggestion ? I really need your to get this done

**Comment by efstathiosntonas** [comment]
@Surinderkaur329 this is not stackoverflow, nor a support forum, did you at least tried what @mikehardy has suggested?
