### ISSUE TITLE
Send FCM data message using Firebase Console - Rich Notifications

### ISSUE THREAD

**Issue by shivsuthanm-odhub** [invertase/react-native-firebase#1843]
Firebase cloud messaging service working very well compare to other push notification services and also very useful dashboard to see all the collection of details.

My requirement need to send image using Firebase Console (**data payload/ rich notification**) but it's not settled well.

I can able to send the text notification (**notification payload**) in firebase console and also it's working properly.

I can able to send the data payload message from **Post man** like below and its working properly.

<img width="1125" alt="screenshot 2019-01-19 at 6 28 04 pm" src="https://user-images.githubusercontent.com/37928499/51427233-80140080-1c1b-11e9-993c-2ae6079ba982.png">

![img_1577](https://user-images.githubusercontent.com/37928499/51427240-9752ee00-1c1b-11e9-8909-2a46e54a886e.PNG)

![img_1578](https://user-images.githubusercontent.com/37928499/51427241-9752ee00-1c1b-11e9-8d2a-47b930979800.PNG)

But Whenever I was trying to send image **key/value pair in Additional options** using **Firebase console** like below its not working. Please suggest.

<img width="897" alt="screenshot 2019-01-19 at 6 24 51 pm" src="https://user-images.githubusercontent.com/37928499/51427248-acc81800-1c1b-11e9-9ed1-279423507b0b.png">

**Comment by AkilLis** [comment]
Need some documentation about rich notifications.

**Comment by AkilLis** [comment]
Still need this feature

**Comment by tgensol** [comment]
Any news or documentation available ? I would like to have an image in notification on Android and iOS, thanks !

**Comment by PantTushar** [comment]
This is very much required. Others too are looking out for it
[](https://github.com/invertase/react-native-firebase/issues/1996 )

**Comment by AkilLis** [comment]
@chrisbianca any news about this feature. thanks

**Comment by ranjithreynold75** [comment]
very much Required Feature, Looking forward for the support

**Comment by ccioloca** [comment]
Sending in a channel if the app is closed, displays the notification. But not when targeting id.

`{       
  "registration_ids":["my_id"],
  "data": {
  	"id": "3256",
  	"message": "123123"
  }
}`

Is it not possible? Or I am not sending it correct?

**Comment by fgarzonhz** [comment]
Enable Rich Notification will be a great feature and alot of projects will up level, more professional and more sofisticated. Thanks for your great contibution.

**Comment by Rajesh3R** [comment]
@AkilLis  i can' t  show rich notification in ios using react-native-firebase from firebase console, but working fine in android. please give me valid suggestion for show rich notification in ios

**Comment by ma96o** [comment]
This is very much required. I lost too much time

**Comment by lezpaul26** [comment]
how you show the notification with a picture?, can you show me your code?

**Comment by Ehesp** [comment]
We've not implemented image notifications for ios. The payload sent via FCM (above) is automatically handled by the **messaging** service.

**Comment by lezpaul26** [comment]
> We've not implemented image notifications for ios. The payload sent via FCM (above) is automatically handled by the **messaging** service.

thanks, can you help me with this?

 i only see the data or the payload when the app is in the foreground and show the payload in an alert, but i can't show it when I receive the notification + data in the background, foreground or closed with this payload.
 @rnfirebase library: 5.3

**Comment by ThanhQuang1410** [comment]
Any update? I’m getting the same isue on IOS. When app is open, the notification I push from firebase console didn’t show the image I set, but when app is close or in background the image showed up.

Anyone has any suggestions?

**Comment by tgensol** [comment]
@ThanhQuang1410  check this : https://github.com/invertase/react-native-firebase/issues/1996

**Comment by luatnd** [comment]
@shivsuthanm-odhub Hi, I use this format but my real device cannot show image attachment.
How can you do that?
This is my payload:
```json
{
  "to": "{{fcm_token_aquos}}",
  "priority": "high",
  "time_to_live": 259200,
  "data": {
    "title": "Hello world",
    "body": "Hello...",
    "image": "https://vortex.accuweather.com/adc2010/images/icons-numbered/01-l.png",
    
    "media_type": "image",
    "message": "message message message messagemessage message",
    "attachment": "https://vortex.accuweather.com/adc2010/images/icons-numbered/01-l.png"
  },
  "notification": {
  	"android_channel_id": "news",
    "sound": "default",
    "title": "Hello world",
    "body": "Hello...",
    "image": "https://vortex.accuweather.com/adc2010/images/icons-numbered/01-l.png"
  }
}
```

**Comment by luatnd** [comment]
Since I cannot find any document about the built-in feature like this, I need to implement myself:
https://docs.mobile.sailthru.com/docs/ios-rich-push

**Comment by LOG-TAG** [comment]
@luatnd can you share your workaround for this?

**Comment by luatnd** [comment]
@LOG-TAG  You need to create a notification extension, you just need to read the link in my above comment.

**Comment by Salakar** [comment]
PR #3339 has been merged which includes support for data messages, notification messages & data+notification messages - when the app is in the foreground, background or quit - for both iOS & Android.

With all these working now you could fairly easily send a data payload and create your own local notification from it.

I'm going to go ahead and close this issue also as #3339 should cover supporting it.
