### ISSUE TITLE
🔥React-Native Manual Setup - 'Firebase.h' file not found RNFirebaseUtil.h

### ISSUE THREAD

**Issue by telkandrew** [invertase/react-native-firebase#1847]
## Issue

Can't get iOS to build using manual setup instructions. Each time I get... 'Firebase.h' file not found RNFirebaseUtil.h. 

My steps: 

1) yarn add react-native-firebase
2) react-native link react-native-firebase

3) download GoogleService-Info.plist from firebase setup, add to XCode project here
<img width="268" alt="screen shot 2019-01-21 at 11 59 28 am" src="https://user-images.githubusercontent.com/20894667/51488640-12c7b300-1d74-11e9-8173-2a6fc62e1817.png">

4) create a Firebase Folder in the root of my XCode project and drag each of the files/resources into the folder like so 
<img width="732" alt="screen shot 2019-01-21 at 12 01 02 pm" src="https://user-images.githubusercontent.com/20894667/51488719-486c9c00-1d74-11e9-8bb8-a42c4d7ad222.png">

5) Added the import and configure to AppDelegate.m

<img width="824" alt="screen shot 2019-01-21 at 12 03 30 pm" src="https://user-images.githubusercontent.com/20894667/51488825-9ed9da80-1d74-11e9-9471-9de58c4e07f1.png">

6) Added '$(SRCROOT)/Firebase' to Framework Search Paths and Header Search Paths
<img width="906" alt="screen shot 2019-01-21 at 12 05 41 pm" src="https://user-images.githubusercontent.com/20894667/51489008-0d1e9d00-1d75-11e9-8d63-32e065cfe3fe.png">

7) Found -ObjC to "Other Linker Options" (didn't have to add as -ObjC was already added)
<img width="906" alt="screen shot 2019-01-21 at 12 05 41 pm" src="https://user-images.githubusercontent.com/20894667/51489703-17da3180-1d77-11e9-8271-5eb3d6d72cde.png">

Then when I try to build 'RNFirebaseUtil.h' throws the 'Firebase.h' not found error
<img width="1154" alt="screen shot 2019-01-21 at 12 22 34 pm" src="https://user-images.githubusercontent.com/20894667/51489774-46580c80-1d77-11e9-8427-c19ed8e8333b.png">

---

#### `ios/Podfile`:

- [x] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:
```objc
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <Firebase.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  NSURL *jsCodeLocation;

  #ifdef DEBUG
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  #else
    jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
  #endif

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"artsfolio"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

@end
```

---

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [x] MacOS, version: `High Sierra 10.13.3`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Xcode 9.2` 
- **`React Native` version:**
  - `0.57.8`
- **`React Native Firebase` library version:**
  - `5.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x ] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by Salakar** [comment]
Hey, could you manually change the firebase import in  'RNFirebaseUtil.h'  to: `#import <Firebase/Firebase.h>` and let me know if it builds? If so I'll clean these up for a v5.2.1 release

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
@telkandrew also; out of curiosity/research - whats the reasoning behind not using Pods in your case, if you don't mind me asking?

**Comment by telkandrew** [comment]
Even though I cleared watchman, cache, and rebooted XCode multiple times earlier, trying it again the issue seems to have resolved itself, and am now on to a new error.  

"FirebaseCore/FirebaseCore.h" file not found from "Firebase.h"
<img width="873" alt="screen shot 2019-01-21 at 8 26 10 pm" src="https://user-images.githubusercontent.com/20894667/51507354-88587100-1dbe-11e9-9b7b-c332b3788734.png">

On a side not I did try changing to <Firebase/Firebase.h> in 'RNFirebaseUtil.h' and it broke the build. <Firebase.h> I believe seems to be working.

I'm not using Pods because I have to integrate Firebase into a very large, pre-existing project soon, so I wanted to try it fresh project first. When we originally built the other project, Pods was breaking/not playing nicely with a few of our NPMs. I can't remember all of them off-hand, but I do believe one of them was 'react-native-camera'.

**Comment by telkandrew** [comment]
Finally got this to build, oh what fun. It looks like the issue most likely has to do with XCode not updating if you add files in a certain way. In case anyone else is having similar issues, here's what finally worked for me. Special thanks @andreicalazans's installation procedure in #1016 with a few alterations. For whatever reason, XCode isn't keeping in-sync with my local files, so I had to add the SDK files differently.

1) _yarn add react-native-firebase_
2) _react-native link react-native-firebase_
3) _Add GoogleService-Info.plist to /ios/appName/_
4) _Download the Firebase sdk zip._ 

_Note: Here instead of following the readme inside the Firebase folder you downloaded follow the below steps._

5) Create a Firebase folder in your local "{projectName}/ios/" folder, not in XCode.

6) Copy all of the folders and their resources (if they exist for said module) into your newly created Firebase folder (attaching a screenshot of my final folder's content's at the end of this post)

7) Open your project in XCode. Right click your ".xcodeproj" and click "Add Files to {yourProjectName}..."
<img width="319" alt="screen shot 2019-01-27 at 3 42 37 pm" src="https://user-images.githubusercontent.com/20894667/51806637-385c2d00-224a-11e9-8094-d3b76a4ef9a2.png">

8) Find the "Firebase" folder you just created and select it.

9) _Before clicking "Add", to the left you'll see an "Options" button. Click it, and make sure "Create Groups" and "Add to targets" for your project are both selected.
<img width="739" alt="screen shot 2019-01-27 at 3 46 21 pm" src="https://user-images.githubusercontent.com/20894667/51806680-bd474680-224a-11e9-9c7c-35e1410d1c69.png">

10) _In xcode and in your build settings for your project (You need to have your project selected under targets and not just under Project). Search for Header Search Paths and add this $(SRCROOT)/Firebase._ Set path to "recursive"

_Then Search for Framework Search Paths and add this $(SRCROOT)/Firebase._ Set path to "recursive"

_Search for Other Linker Settings and add the -ObjC_ (This didn't pertain to my situation as -ObjC was already under "Other Linker Settings"

_in ios/[YOUR APP NAME]/AppDelegate.m add #import <Firebase.h> at the top.

_still in AppDelegate.m add [FIRApp configure]; in the beginning of the method didFinishLaunchingWithOptions:(NSDictionary *)launchOptions.

Once you have done the above steps rebuild your app and it should be fine.__

**Comment by shuvo0074** [comment]
https://github.com/invertase/react-native-firebase/issues/1847#issuecomment-457952828 with this, don't forget to copy the Firebase.h file from FirebaseSDk and paste it in ios/Firebase folder

**Comment by bernhardt1** [comment]
@andrewtelkamp 

There is one crucial step you've missed that I had to work through to get my build to pass.

**@ step 4)** DO NOT DOWNLOAD THE IOS SDK THAT FIREBASE RECOMMENDS. You must check the supported versions table to make you iOS SDK version match with  the react-native version you are using + the react-native-firebase version you have installed: https://github.com/invertase/react-native-firebase/tree/v5.x.x#supported-versions---react-native--firebase

You can download the correct version from here: https://github.com/firebase/firebase-ios-sdk/releases/tag/5.20.2

Also, step 6 should possibly include advice to add the firebase.h file to the Firebase folder.

**Comment by mikehardy** [comment]
The sdk versions must match the react native firebase compatibility table yes, good point

**Comment by mikehardy** [comment]
Documentation PRs al ways welcome there is an edit link on each page and github allows easy Doc edits via the web...

**Comment by bernhardt1** [comment]
@mikehardy I submitted a PR here: https://github.com/invertase/react-native-firebase-docs/pull/189

**Comment by joeyyang** [comment]
Thank you @andrewtelkamp! Been stuck for days and your instructions are what finally got everything working.

Couple notes:
- Step 4: as @bernhardt1 mentioned, I had to ensure I downloaded the correct version of the Firebase iOS SDK. I'm using     `"react-native": "0.57.8"`, `"react-native-firebase": "5.2.3"`, and used the `5.17.0` release of the [Firebase iOS SDK](https://github.com/firebase/firebase-ios-sdk/releases?after=Firestore-1.0.2). I attempted to follow the instructions but later realized I downloaded the wrong package — I needed to click on the link under Assets that said "Firebase-5.17.0.zip", not "Source code (zip)"
![Screenshot 2019-07-02 12 43 34](https://user-images.githubusercontent.com/2928395/60546415-1a4f9880-9cd2-11e9-9890-0b46bbf0b17f.png)
- Step 6: I initially attempted to copy all Firebase modules over to `ios/Firebase`, but this led to a successful build that hung on app startup. Only importing the packages I needed fixed this.

**Comment by jimsproject** [comment]
finally solved, I find that react native firebase package was install globally. it causes RNFirebaseUtil.h can't find the pod header file. by remove the global one and make sure it is installed locally, now it is working.

**Comment by mikehardy** [comment]
Wow @Salakar if you do a rnfb doctor type script that last comment is interesting. Conflict with local vs global install. I never would have thought of that

**Comment by qwertzguy** [comment]
Another super important thing for those who get this error (I fought with this for an entire afternoon): **you must use the folder ios/Firebase exactly**, if you put the file in any other folder or name the folder differently (even different case), you will get the Firebase.h not found error because the RNFireBase.xcodeproj has the search path hard-coded to ios/Firebase.

**Comment by Ayushivam** [comment]
![menu](https://user-images.githubusercontent.com/36396957/64171944-7faa3c00-ce71-11e9-8096-dce2ab231da3.png)

**Comment by padlock98** [comment]
@andrewtelkamp may I reconfirm, step no. 6 "Copy all of the folders and their resources (if they exist for said module) into your newly created Firebase folder", do you mean the whole Firebase SDK folder or the whole RNFirebase folder?
