### ISSUE TITLE
Error-Code as number in "recordError(code, message)" make no sense

### ISSUE THREAD

**Issue by xstable** [invertase/react-native-firebase#1848]
First parameter in recordError should be an Number: 

![image](https://user-images.githubusercontent.com/1778068/51523088-2eda5b80-1e2b-11e9-80a6-b9eab0586ee2.png)

Let's set it to `123` and see where it appears: 
![image](https://user-images.githubusercontent.com/1778068/51523151-4fa2b100-1e2b-11e9-80fa-e38950181465.png)

For me it makes no sense at all to limit the "Error-Code" to an number. It would be better to allow a String to be able to put the Name of the Component (or other meta-info) in here.

In Fact, if you use Error-Codes, you also need some additional List with Error-Codes to know, what the numbers mean.

So please change this Filed to allow alphanumeric Characters.

**Comment by lfalkner** [comment]
It looks like this method signature was previously used in Crashlytics for Apple, and the error code was meant to point to an NSError code, which is specific to apple. I've been unable to confirm this completely, but it does point to the error code not having much meaning for a react-native product.
 https://docs.fabric.io/apple/crashlytics/logged-errors.html

**Comment by lfalkner** [comment]
In addition, it looks like there will be significant changes (for the better) with the API in version 6: https://github.com/invertase/react-native-firebase/issues/1783

**Comment by Salakar** [comment]
Crashlytics has recently had a major overhaul in https://github.com/invertase/react-native-firebase/pull/1958 - this will land as part of v6. 

As this issue no longer applies to it (can report actual JS Errors now) I will close and lock this issue.

Thanks for reporting.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
