### ISSUE TITLE
No sound in notifications when creating a channel

### ISSUE THREAD

**Issue by melenchenko** [invertase/react-native-firebase#1855]
When I create a channel, its notification sound is disabled in Android settings. Although I include it when creating the channel. How do I turn on the sound?

const channel = new firebase.notifications.Android.Channel('my_channel', 'My Channel', firebase.notifications.Android.Importance.High)
            .setDescription('My main channel')
            .setSound('default')
            firebase.notifications().android.createChannel(channel);

**Comment by lorenc-tomasz** [comment]
+1

**Comment by lorenc-tomasz** [comment]
I have resolved my issue here: https://github.com/invertase/react-native-firebase/issues/1930 Maybe it will help.

**Comment by Gp2mv3** [comment]
Same issue too...
