### ISSUE TITLE
🔥[Android] Null claim value in a claims object array causing java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by makirby** [invertase/react-native-firebase#1856]
## Issue
Null claim value within an object array causing the error below

```
java.lang.IllegalArgumentException: Could not convert class org.json.JSONObject$1
        at com.facebook.react.bridge.Arguments.addEntry(Arguments.java:117)
        at com.facebook.react.bridge.Arguments.makeNativeMap(Arguments.java:133)
        at com.facebook.react.bridge.Arguments.makeNativeObject(Arguments.java:34)
        at com.facebook.react.bridge.Arguments.makeNativeArray(Arguments.java:57)
        at io.invertase.firebase.Utils.mapPutValue(Utils.java:92)
        at io.invertase.firebase.Utils.mapPutValue(Utils.java:98)
        at io.invertase.firebase.auth.RNFirebaseAuth$33.onComplete(RNFirebaseAuth.java:1552)
        at com.google.android.gms.tasks.zzj.run(Unknown Source)
```

The claims object on the JWT which it is failing on, has the following structure.
```
"roles": [
    {
      "role": "validated",
      "scheme_id": null
    },
    {
      "role": "member",
      "scheme_id": 1
    },
    {
      "role": "member",
      "scheme_id": 2
    }
  ],
```

When debugging it seems the underlying object for the property scheme_id is of type "org.json.JSONObject$1" so when the method below calls getValue() it is failing.

```
 public static WritableNativeMap makeNativeMap(Map<String, Object> objects) {
    WritableNativeMap nativeMap = new WritableNativeMap();
    if (objects == null) {
      return nativeMap;
    }
    for (Map.Entry<String, Object> entry : objects.entrySet()) {
      addEntry(nativeMap, entry.getKey(), entry.getValue());
    }
    return nativeMap;
  }
```

This is happening when we set up the onIdTokenChange listener
`this.tokenChangeSubscription = firebase.auth().onIdTokenChanged(this.onIdTokenChange)`

---

#### `ios/Podfile`:

- [x] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - ` Android Studio 3.2` e.g. Xcode 10, Android Studio 3.2
- **`React Native` version:**
  - `57.8`
- **`React Native Firebase` library version:**
  - `5.2.1`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [x] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by Salakar** [comment]
Thanks for reporting this clearly, looks like the native firebase SDK is returning a raw JSON instance rather than a native Android type, not the first time this has happened 🙈

I'll sort a patch release to fix this tomorrow.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by makirby** [comment]
Hi were still seeing this randomly occur on our current production version.

**Comment by Salakar** [comment]
Apologies for the delay on getting a patch out for this, I'll try get one sorted for this in 5.2.3 this week.

**Comment by Salakar** [comment]
@makirby I've spent several hours today trying to reproduce this and I'm unable to 😞 here's the local test I was running to give you an idea of what I was trying:

```js
it.only('signs in with a admin sdk created custom auth token', async () => {
  const customUID = `zdwHCjbpzraRoNK7d64FYWv5AH02`;
  const tokenChangeSubscription = firebase
    .auth()
    .onIdTokenChanged(async user => {
      if (user) {
        const { claims } = await user.getIdTokenResult();
        console.warn(claims);
      }
    });
  const token = await firebaseAdmin.auth().createCustomToken(customUID, {
    test: null,
    roles: [
      {
        role: 'validated',
        scheme_id: null,
      },
      {
        role: 'member',
        scheme_id: 1,
      },
      {
        role: 'member',
        scheme_id: 2,
      },
    ],
  });
  const { user } = await firebase.auth().signInWithCustomToken(token);
  user.uid.should.equal(customUID);
  firebase.auth().currentUser.uid.should.equal(customUID);

  const { claims } = await firebase
    .auth()
    .currentUser.getIdTokenResult(true);

  console.warn(claims);
  await Utils.sleep(10000);
  await firebase.auth().signOut();
  tokenChangeSubscription();
});
```

And the logging output:

```json:
{ auth_time: 1551365106,
  email_verified: false,
  email: 'test@test.com',
  iss:
   'https://securetoken.google.com/react-native-firebase-testing',
  iat: 1551365107,
  exp: 1551368707,
  user_id: 'zdwHCjbpzraRoNK7d64FYWv5AH02',
  roles:
   [ { role: 'validated' },
     { role: 'member', scheme_id: 1 },
     { role: 'member', scheme_id: 2 } ],
  sub: 'zdwHCjbpzraRoNK7d64FYWv5AH02',
  aud: 'react-native-firebase-testing',
  firebase:
   { sign_in_provider: 'custom', identities: { email: [Array] } } }
```

As you can see there it's all working, there's no crashes or error on adb logs either.

What version of the Android Firebase SDKs are you on? You should be running the same versions as: https://github.com/invertase/react-native-firebase/blob/v5.x.x/tests/android/app/build.gradle#L94-L109

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by makirby** [comment]
Hi @Salakar thanks for taking a look at this, I really appreciate it. I believe our

**Comment by makirby** [comment]
Ive double checked the firebase version for the release im talking about
```
implementation project(':react-native-firebase')
    implementation "com.google.android.gms:play-services-base:16.0.1"
    implementation "com.google.firebase:firebase-auth:16.0.5"
    implementation "com.google.firebase:firebase-core:16.0.4"
    implementation "com.google.firebase:firebase-config:16.1.0"
    implementation "com.google.firebase:firebase-invites:16.0.4"
    implementation "com.google.firebase:firebase-messaging:17.3.4"
```
