### ISSUE TITLE
🔥 Release build fails after updating Firebase to v5.15.0

### ISSUE THREAD

**Issue by surendharreddy** [invertase/react-native-firebase#1857]
## Issue

Updated Firebase in my podfile to version 5.15.0 and also `react-native-firebase` to `"^4.3.8"` to integrate In-App Messaging for the app. Building work fines in debug mode, but when I make a release build it fails with `'React/RCTBridgeModule.h' file not found` error. Attached screenshot with full report below. 

<img width="764" alt="screenshot 2019-01-24 at 1 26 31 pm" src="https://user-images.githubusercontent.com/7141644/51656846-86b8c400-1fdd-11e9-8316-fa1e01d9861d.png">

I followed this tweet https://twitter.com/mikediarmid/status/1032673313418616833?s=20 and planned to integrate the In-App Messaging feature which requires no changes in the platform files. I'm running firebase already in production for more than 4 months, only now I'm facing these build issues issue. 

---

#### `ios/Podfile`:
- [x] I'm using Pods and my Podfile looks like:
```
target 'xxxxxxapp' do
  pod 'Stripe', '~> 11.2.0'
  pod 'Firebase/Core'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/InAppMessagingDisplay'
  pod "UXCam", "~> 2.5.12"
  use_frameworks!
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'UrbanAirship-iOS-SDK'
end
```

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `iOS 10`
- **Operating System:**
  - [x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Xcode 10` with legacy build system
- **`React Native` version:**
  - `"react-native": "0.55.4",`
- **`React Native Firebase` library version:**
  - `"react-native-firebase": "^4.3.8"`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [x] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [x] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

### Update 

Updated `react-native-firebase` to `"5.2.1"` and tried building the app, but it throws 
`'FirebaseCore/FirebaseCore.h' file not found`error.  Attached screenshot with full report below. 

<img width="1040" alt="screenshot 2019-01-25 at 11 11 14 am" src="https://user-images.githubusercontent.com/7141644/51722943-35b6d780-2092-11e9-847d-431081d17824.png">

**Comment by SchwarzerSchnee** [comment]
I've had the error from your update too, after hours of trial and error I fixed it by adding $(inherited) non-recursive to the top of Header/Framework Search Paths of the main project, if not already present. Good luck.

**Comment by surendharreddy** [comment]
Thanks, @SchwarzerSchnee! Will try this next week and see if I can make a release build.

**Comment by surendharreddy** [comment]
@SchwarzerSchnee I already have **$(inherited) non-recursive to the top of Header/Framework Search Paths of the main project** and I tried building the app in release schema multiple times, but I still get the same error.

**Comment by shakilproctur** [comment]
Facing FirebaseCore.h file not found. I am using version 16.0.0
