### ISSUE TITLE
[v2] FIRMessaging Compile Errors (iOS)

### ISSUE THREAD

**Issue by arminsal1** [invertase/react-native-firebase#186]
Just upgraded to v2 following the migration guide and xcode is giving me 3 compile errors related to FIRMessaging:
<img width="1182" alt="screen shot 2017-06-21 at 1 19 03 pm" src="https://user-images.githubusercontent.com/8769537/27397683-2539cd64-5685-11e7-8d78-c4aad4369125.png">
<img width="1179" alt="screen shot 2017-06-21 at 1 19 12 pm" src="https://user-images.githubusercontent.com/8769537/27397682-2539217a-5685-11e7-9357-fcce540b1b0a.png">
<img width="1181" alt="screen shot 2017-06-21 at 1 19 20 pm" src="https://user-images.githubusercontent.com/8769537/27397684-253f9546-5685-11e7-8758-3a0f410a80a6.png">

**Comment by Salakar** [comment]
Can you try remove your podlock file and re run your pod install and try again?

**Comment by arminsal1** [comment]
@Salakar I moved the old podlock file out of the folder (just in case I needed it later) and ran pod install again, which generated a new podlock file in the folder. But unfortunately the error persists even after cleaning the project and build folder

**Comment by fbacker** [comment]
@arminsal1 Try '''pod deintegrate''' and then delete the '''podlock file'''. Then '''pod install''. Maybe that will help.

**Comment by chrisbianca** [comment]
@arminsal1 can you confirm what version of firebase messaging is being installed according to your podlock file?

**Comment by arminsal1** [comment]
@fbacker I tried as you suggested and unfortunately there's no change. And @chrisbianca The terminal says "Installing FirebaseMessaging (1.2.3)" when I do pod install

**Comment by chrisbianca** [comment]
@arminsal1 it should be installing 2.0.0 - do you have any other modules installed which might make use of Firebase and specify an earlier version?  Here's a snapshot of my `pod install` output:

```
Using Firebase (4.0.0)
Using FirebaseAnalytics (4.0.0)
Using FirebaseAuth (4.0.0)
Using FirebaseCore (4.0.0)
Using FirebaseCrash (2.0.0)
Using FirebaseDatabase (4.0.0)
Using FirebaseDynamicLinks (2.0.0)
Using FirebaseInstanceID (2.0.0)
Using FirebaseMessaging (2.0.0)
Using FirebaseRemoteConfig (2.0.0)
Using FirebaseStorage (2.0.0)
```

**Comment by andrepcg** [comment]
This is my Podfile:

```
# Required by RNFirebase
pod 'Firebase/Core'
pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

# RNFirebase
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/AppIndexing'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Messaging'

pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'BatchedBridge', # Required For React Native 0.45.0+
  'Core',
  # Add any other subspecs you want to use in your project
]
```

and this is my `pod install` output:

```
Analyzing dependencies
Fetching podspec for `RNFirebase` from `../node_modules/react-native-firebase`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `Yoga` from `../node_modules/react-native/ReactCommon/yoga`
Downloading dependencies
Installing Firebase (3.17.0)
Installing FirebaseAnalytics (3.9.0)
Installing FirebaseAppIndexing (1.2.0)
Installing FirebaseAuth (3.1.1)
Installing FirebaseCore (3.6.0)
Installing FirebaseCrash (1.1.6)
Installing FirebaseDatabase (3.1.2)
Installing FirebaseDynamicLinks (1.4.0)
Installing FirebaseInstanceID (1.0.10)
Installing FirebaseMessaging (1.2.3)
Installing GTMSessionFetcher (1.1.10)
Installing GoogleToolboxForMac (2.1.1)
Installing Protobuf (3.3.0)
Installing RNFirebase (2.0.0)
Installing React (0.45.1)
Installing Yoga (0.45.1.React)
Generating Pods project
Integrating client project
Sending stats
```

And I'm having the same issues as @arminsal1 when compiling

**Comment by chrisbianca** [comment]
@andrepcg Is this a brand new project? Or one you've been using for a while?

What happens if you run `pod outdated`?

If you run `pod update` it should switch you to using the latest version of Firebase (4.0.0) and all the rest of the Firebase dependencies.

**Comment by arminsal1** [comment]
@chrisbianca Cocoapods wasn't letting me update to the newest version of Firebase, but I managed to do it after changing my iOS version from 0.8 to 0.9, deleting the podlock file and reinstalling the pods. Now the app runs perfectly without any compile errors

**Comment by chrisbianca** [comment]
Great! I wonder whether Firebase 4.0.0 now only supports iOS 9 and above - it wouldn't surprise me as anything less than 9 is barely used and not really supported by Apple anymore...

**Comment by zenyr** [comment]
`pod outdated` told me that there are v4 available but `pod update` never let me upgrade to v4 regardless of cache status. 

by inserting this line right before `Firebase/Core`, I managed to upgrade to Firebase v4
```
pod 'Firebase', '~> 4.0.0'
```

Ye.
