### ISSUE TITLE
Firebase only works on reload

### ISSUE THREAD

**Issue by adrielFab** [invertase/react-native-firebase#1863]
In my App.js, in my componentDidMount, I check to see if user has permission for receiving notifications. However, I noticed that this firebase functionality only works after I refresh the application. It never works on the first install. Any ideas could be useful

```
async function checkPermission() {
  const enabled = await firebase.messaging().hasPermission();
  if (enabled) {
    getToken();
  } else {
    requestPermission();
  }
}
```

```
function requestPermission() {
  firebase
    .messaging()
    .requestPermission()
    .then(() => {
      getToken();
    });
}
```

**Comment by Ehesp** [comment]
Are you sure there isn't an issue with your logic here? `getToken()` and `requestPermission()` here are promises which you're not waiting for the result of.

**Comment by prgMgava** [comment]
Hi, I am has the same problem. Hou did you resolved? @adrielFab

**Comment by Ehesp** [comment]
I'd suggest creating a new issue, this one is 5 years old. A lot has changed since then.
