### ISSUE TITLE
Getting could not invode RNFirebaseFirestore.documentSet null

### ISSUE THREAD

**Issue by thirappusuresh** [invertase/react-native-firebase#1866]
Please find the attached screenshot. I'm getting this error when I'm trying to set the data to firestore.

![6002168434851431314](https://user-images.githubusercontent.com/3216839/51804771-e8ea2100-228a-11e9-8675-0ccd35682f35.jpg)

**Comment by Ehesp** [comment]
Please fill out the issue template & provide some code so we can help.

**Comment by thirappusuresh** [comment]
Following is the code I'm using 

import firebase from 'react-native-firebase';

export function updateMemberDetails() {
    firebase
        .firestore()
        .collection('communities')
        .doc('communityname')
        .collection('members')
        .doc('memberid')
        .set({ field1: 'value1' })
        .then(function(docRef) {})
        .catch(function(error) {
            console.error('Error updating userChannel : ', error);
        });
}

I'm calling updateMemberDetails() method from different component. I was able to debug and see that the code is entering the method after that I'm getting could not invode RNFirebaseFirestore.documentSet null No virtual method Set error. It's not going to catch block also

**Comment by Josh-Uvi** [comment]
I have the same problem on android but it works fine on iOS. Any help would be greatly appreciated. Thanks in advance :)

**Comment by Josh-Uvi** [comment]
> Please fill out the issue template & provide some code so we can help.

I have the same problem on android but it works fine on iOS. Any help would be greatly appreciated. Thanks in advance
