### ISSUE TITLE
Getting could not invode RNFirebaseFirestore.documentSet null No virtual method Set

### ISSUE THREAD

**Issue by thirappusuresh** [invertase/react-native-firebase#1867]
## Issue

Please find the attached screenshot for exact error. I'm getting this error when I'm trying to set the data to firestore. Following is the code

import firebase from 'react-native-firebase';

export function updateMemberDetails() {
firebase
.firestore()
.collection('communities')
.doc('communityname')
.collection('members')
.doc('memberid')
.set({ field1: 'value1' })
.then(function(docRef) {})
.catch(function(error) {
console.error('Error updating userChannel : ', error);
});
}

I'm calling updateMemberDetails() method from different component. I was able to debug and see that the code is entering the method after that I'm getting could not invode RNFirebaseFirestore.documentSet null No virtual method Set error. It's not going to catch block also

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Android Studio 3.2.1` e.g. Xcode 10, Android Studio 3.2
- **`React Native` version:**
  - `0.57.7`
- **`React Native Firebase` library version:**
  - `React Native Firebase version 5.2.1`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [x] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [X] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by thirappusuresh** [comment]
Please find the attachment of error
![6002168434851431314](https://user-images.githubusercontent.com/3216839/51837747-6a44c080-232a-11e9-9f87-5b470f488e66.jpg)

**Comment by Josh-Uvi** [comment]
I have the same problem on android but it works fine on iOS. Any help would be greatly appreciated. Thanks in advance

**Comment by Josh-Uvi** [comment]
> I have the same problem on android but it works fine on iOS. Any help would be greatly appreciated. Thanks in advance

A solution I found: was to revert back to firestore version 17.1.5
dependencies {
  // ...
  implementation "com.google.firebase:firebase-firestore:17.1.5"
}
