### ISSUE TITLE
putFile() issue on Android

### ISSUE THREAD

**Issue by berkcoker** [invertase/react-native-firebase#1868]
The current (v5.2.1) implementation of putFile() seems to not work on Android devices. The error log I attached below indicates the library can't find the local file. I came up with an easy fix after a couple of hours of digging, which was to remove line 100 from modules/storage/reference.js:

`let _filePath = filePath.replace('file://', '');`

It looks like you need to keep the "file://" for the upload to succeed. I'm creating a PR on this, and hopefully it will be merged soon.

--------------------------------------------------------------------------------

01-28 16:30:43.638 25532 26027 W UploadTask: could not retrieve file size for upload /data/user/0/xxx/files/2019-01-29T00:30:21.007Z.aac
01-28 16:30:43.638 25532 26027 W UploadTask: java.io.FileNotFoundException: No content provider: /data/user/0/xxx/files/2019-01-29T00:30:21.007Z.aac
01-28 16:30:43.638 25532 26027 W UploadTask: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1396)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1247)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1100)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1054)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at com.google.firebase.storage.UploadTask.<init>(com.google.firebase:firebase-storage@@16.0.5:105)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at com.google.firebase.storage.StorageReference.putFile(com.google.firebase:firebase-storage@@16.0.5:281)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at io.invertase.firebase.storage.RNFirebaseStorage.putFile(RNFirebaseStorage.java:376)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at java.lang.reflect.Method.invoke(Native Method)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at android.os.Handler.handleCallback(Handler.java:790)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at android.os.Looper.loop(Looper.java:164)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
01-28 16:30:43.638 25532 26027 W UploadTask: 	at java.lang.Thread.run(Thread.java:764)
01-28 16:30:43.643 25532 26027 E UploadTask: could not locate file for uploading:/data/user/0/xxx/files/2019-01-29T00:30:21.007Z.aac
01-28 16:30:43.654 25532 26027 E StorageException: StorageException has occurred.
01-28 16:30:43.654 25532 26027 E StorageException: An unknown error occurred, please check the HTTP result code and inner exception for server response.
01-28 16:30:43.654 25532 26027 E StorageException:  Code: -13000 HttpResult: 0
01-28 16:30:43.668 25532 26027 E StorageException: No content provider: /data/user/0/xxx/files/2019-01-29T00:30:21.007Z.aac
01-28 16:30:43.668 25532 26027 E StorageException: java.io.FileNotFoundException: No content provider: /data/user/0/xxx/files/2019-01-29T00:30:21.007Z.aac
01-28 16:30:43.668 25532 26027 E StorageException: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1396)
01-28 16:30:43.668 25532 26027 E StorageException: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1247)
01-28 16:30:43.668 25532 26027 E StorageException: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:967)
01-28 16:30:43.668 25532 26027 E StorageException: 	at com.google.firebase.storage.UploadTask.<init>(com.google.firebase:firebase-storage@@16.0.5:118)
01-28 16:30:43.668 25532 26027 E StorageException: 	at com.google.firebase.storage.StorageReference.putFile(com.google.firebase:firebase-storage@@16.0.5:281)
01-28 16:30:43.668 25532 26027 E StorageException: 	at io.invertase.firebase.storage.RNFirebaseStorage.putFile(RNFirebaseStorage.java:376)
01-28 16:30:43.668 25532 26027 E StorageException: 	at java.lang.reflect.Method.invoke(Native Method)
01-28 16:30:43.668 25532 26027 E StorageException: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
01-28 16:30:43.668 25532 26027 E StorageException: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
01-28 16:30:43.668 25532 26027 E StorageException: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-28 16:30:43.668 25532 26027 E StorageException: 	at android.os.Handler.handleCallback(Handler.java:790)
01-28 16:30:43.668 25532 26027 E StorageException: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-28 16:30:43.668 25532 26027 E StorageException: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
01-28 16:30:43.668 25532 26027 E StorageException: 	at android.os.Looper.loop(Looper.java:164)
01-28 16:30:43.668 25532 26027 E StorageException: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)

**Comment by ParthNandaniya** [comment]
![phub error](https://user-images.githubusercontent.com/30195101/52894852-c175dc80-31d6-11e9-907a-83b40debde91.PNG)
i pass "uri"of image above in putfile it still error occure

`er Error: An unknown error has occurred.
    at createErrorFromErrorData (E:\new\pHub\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:146)
    at E:\new\pHub\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:95
    at MessageQueue.__invokeCallback (E:\new\pHub\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:397)
    at E:\new\pHub\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:127
    at MessageQueue.__guard (E:\new\pHub\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:297)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (E:\new\pHub\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:126)
    at debuggerWorker.js:72`

**Comment by berkcoker** [comment]
Just wanted to bump this because I have recently created a pull request that addresses this issue. putFile simply does not work on Android in its current form

**Comment by Salakar** [comment]
@berkcoker thanks for the PR, will get it merged today into v5.

**Comment by brahatksingh** [comment]
Why isn't google fixing  this? Is there any other way to get the Download Url ?
