### ISSUE TITLE
Incorrect RCT_ENUM_CONVERTER values 

### ISSUE THREAD

**Issue by whitetown** [invertase/react-native-firebase#1870]
Hello,

in react-native file:
node_modules/react-native/Libraries/PushNotificationIOS/RCTPushNotificationManager.m 

these values defined as:

```
RCT_ENUM_CONVERTER(UIBackgroundFetchResult, (@{
  @"UIBackgroundFetchResultNewData": @(UIBackgroundFetchResultNewData),
  @"UIBackgroundFetchResultNoData": @(UIBackgroundFetchResultNoData),
  @"UIBackgroundFetchResultFailed": @(UIBackgroundFetchResultFailed),
}), UIBackgroundFetchResultNoData, integerValue)

```
and in your project, these values defined differently (below) 
it causes a warning in the console or red screen 

node_modules/react-native-firebase/ios/RNFirebase/converters/RCTConvert+UIBackgroundFetchResult.m 

```
RCT_ENUM_CONVERTER(
    UIBackgroundFetchResult,
    (@{
        @"backgroundFetchResultNoData" : @(UIBackgroundFetchResultNoData),
        @"backgroundFetchResultNewData" : @(UIBackgroundFetchResultNewData),
        @"backgroundFetchResultFailed" : @(UIBackgroundFetchResultFailed)}
    ),
    UIBackgroundFetchResultNoData,
    integerValue
)
```

node_modules/react-native-firebase/ios/RNFirebase/notifications/RNFirebaseNotifications.m 

```
- (NSDictionary *) constantsToExport {
    return @{ @"backgroundFetchResultNoData" : @(UIBackgroundFetchResultNoData),
              @"backgroundFetchResultNewData" : @(UIBackgroundFetchResultNewData),
              @"backgroundFetchResultFailed" : @(UIBackgroundFetchResultFailed)};
}
```

Could you change these strings according to the original react-native, please

**Comment by Salakar** [comment]
@whitetown is this not still an issue?

**Comment by whitetown** [comment]
It was an issue because I used RCTPushNotificationManager together with FireBase.
Now I switched to FireBase notifications and removed the first library from my project.

**Comment by Salakar** [comment]
Ok thanks for clarifying, I'll make this change anyway for v6 as they shouldn't be conflicting.

**Comment by AdamLee321** [comment]
Has this fix been added to the alpha version of v6 yet?

**Comment by Salakar** [comment]
@AdamLee321 Notifications is not yet in the Alpha yet sorry, will be there in a few weeks.

**Comment by fant0mex** [comment]
Any chance this will be merged soon?
