### ISSUE TITLE
crashlytics crash not showing up on firebase dashboard

### ISSUE THREAD

**Issue by tenchoklang** [invertase/react-native-firebase#1871]
I am using firebase crashlytics. I am causing a crash by doing 
`firebase.crashlytics().crash()
`
and I am not seeing the crash report on the firebase dashboard. The crash is working because on android i get this screen
![screenshot_1548911092](https://user-images.githubusercontent.com/26011251/52031721-e1758280-24eb-11e9-9082-36185128a989.png)

and on ios the app freezes and i get brought to this page on xcode

<img width="1440" alt="screen shot 2019-01-31 at 12 07 31 am" src="https://user-images.githubusercontent.com/26011251/52031813-4b8e2780-24ec-11e9-8071-95400abf7582.png">

So I am assuming that firebase is correctly installed since it is causing the crash. But I am unable to see the crash on firebase crashlytics console. 

PS: I tried to crash the app natively via java in android it worked and i can see the crash report on crashlytics dashboard but for IOS I am unable to see the crash

EDIT: and yes I have waited 48+ hours

**Comment by raienko** [comment]
As for me, situation is almost the same.
Installed on both platforms, both applications work as expected on force crash.
But android collects information about crashes and shows it on dashboard and iOS - don't.
Waited for more than 48 hours. Tried even with disconnected xCode to make sure that it doesn't block Crashlytics reports for some reason.

**Comment by sujayjaju** [comment]
I have the opposite problem. It works on iOS but does not on Android.
Android does not have any logs stored. Logcat says "No reports found".

`firebase.crashlytics().recordError(...)` works though. Crashlytics is unable to catch fatal errors on Android for me.

**Comment by Salakar** [comment]
Closing in favour of https://github.com/invertase/react-native-firebase/issues/1921 as it provides more info; @sujayjaju in future please don't duplicate issues; our time is limited as it is 🙈 

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
