### ISSUE TITLE
:fire: Data-only messages are never received on iOS

### ISSUE THREAD

**Issue by SchwarzerSchnee** [invertase/react-native-firebase#1875]
HTTP v1 POST body:
```
{
	"message":{
		"token":"(...)",
		"notification":{
			"body":"hello world",
			"title":"hello world",
		},
		"data":{
			"hello":"1",
			"world":"234",
		}
	}
}
```

Code in my app:
```
//This works as expected:
this.notificationListener = firebase.notifications().onNotification((notification) => {
		  console.log("my data: "+JSON.stringify(notification.data));
	      const { title, body } = notification;
	      this.showAlert(title, body);
	  });

//If I take out the notification key of the above HTTP request, I expect that this listener here should be triggered. Instead, it is never triggered at all.
this.messageListener = firebase.messaging().onMessage((message) => {
	    console.log("my data: "+JSON.stringify(message));
	  });
```

The app is running in foreground. I am finding no sources online that claim this shouldn't work.

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - iOS 11, can test 12 later
- **`React Native` version:**
  - 0.58.1
- **`React Native Firebase` library version:**
  - 5.2.1
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [x] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

**Comment by kosintop** [comment]
I also experience similar issue.

I sent a cloud message from my own server
on android onMessage is trigger
on ios, onNotification is trigger instead,onMessage never trigger

**Comment by shubham1164** [comment]
I can receive data only message in IOS when app is in foreground but unable to receive data only message in IOS when the app is closed and there is no info regarding the same in the docs also.

**Comment by nyenye** [comment]
@shubham1164 about background on iOS there is a not which specifies only Android:

https://rnfirebase.io/docs/v5.x.x/messaging/receiving-messages

on the 4rth step. Maybe its this.

For me, it happened otherwise. @kosintop, it triggered onNotifications instead of onMessage. And right now (without any apparent change, not even onMessage will trigger).

**Comment by SchwarzerSchnee** [comment]
In case it wasn't clear from the starting post, the issue happens on the HTTP v1 API only. It's working fine with the legacy HTTP API. We would strongly prefer not to use legacy in our project though...

**Comment by shubham1164** [comment]
I am now using Voip notification for IOS and successfully able to trigger the notification on the IOS even in the closed IOS app

**Comment by antseburova** [comment]
onMessage is triggered on iOS on foreground only. iOS manages displaying notifications when your app is on background/closed by itself. After removing the notification object, add the following to your message object instead:
```
apns: {
        payload: {
          aps: {
            badge: unreadMessageCount,
            alert: {
              title,
              body
            }
          }
        }
}
```
