### ISSUE TITLE
[v2] build Error post migration to v2

### ISSUE THREAD

**Issue by jasan-s** [invertase/react-native-firebase#188]
Build Fails on iOS(only tested thus far): 
I'm getting an error:
`
The following commands produced analyzer issues:
	Analyze /Users/me/Desktop/React_Native/appA/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Users/me/Desktop/React_Native/appA/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
(2 commands with analyzer issues)
`

**Comment by Ehesp** [comment]
Can we see your Podfile?

**Comment by jasan-s** [comment]
@Ehesp  here it is : 

```
target 'appA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for 'appA'
end

# Required by RNFirebase
pod 'Firebase/Core'
pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

# [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
pod 'Firebase/AdMob'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'

pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'BatchedBridge', # Required For React Native 0.45.0+
  'Core',
  # Add any other subspecs you want to use in your project
]
```

**Comment by jasan-s** [comment]
any update on this error @Ehesp

**Comment by chrisbianca** [comment]
@jasan-s is there any more information in the error log?  The error you've posted doesn't really give much for us to go on, and doesn't necessarily imply that it's a problem with rn-firebase

**Comment by chrisbianca** [comment]
@jasan-s I'm going to assume that this issue is now resolved, please let me know if that's not the case
