### ISSUE TITLE
🔥 Dynamic Links: Doesn't redirect to App from Safari with latest Firebase Schema. 

### ISSUE THREAD

**Issue by Vanclief** [invertase/react-native-firebase#1891]
## Issue

Using Firebase Dynamic Links, when opening a Firebase Dynamic link in iOS with `Linking.openURL`, the link defaults to the fallback url instead of opening the Deeplink inside the App. This behavior only happens on iOS, with the exact same implementation for Android working as intended. 

This also happens when pasting the url in Safari, or trying to open the link in Slack or any app that defaults to Safari. However it works fine in WhatsApp.

[Related to this issue](https://github.com/invertase/react-native-firebase/issues/857)

However the solution does not apply since then the deep link schema has changed to: `applinks:your_subdomain.page.link` and the issue is marked as close. 

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [X] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `iOS 12`
- **Operating System:**
  - [X] MacOS, version: `10.14.2 `
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Xcode 10.1` 
- **`React Native` version:**
  - `0.57`
- **`React Native Firebase` library version:**
  - `5.2.1`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [X] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [X] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by uprootstudios** [comment]
We have the same issue and have tried almost every solution. @Vanclief have you been able to solve it?

**Comment by Vanclief** [comment]
Hi @uprootstudios,

Thank you, indeed I ended up with the same solution, unfortunately it does not work when scanning a link from a QR without requiring a prompt for there user, but that seems related to how iOS manages Universal Links.

**Comment by ajayzthakur7** [comment]
Getting same issue, using Stripe Ideal Payment in app, on providing firebase dynamic link as return URL , on completing payment safari is showing preview link to open the app instead of open the app directly.

I tried to make navigationInfoParameters?.isForcedRedirectEnabled = true but in this case safari is opening the App Store page,  even app is installed in device

**Comment by affanhashone** [comment]
@Vanclief  How Did you resolved this Isue

**Comment by ajayzthakur7** [comment]
Still this issue is not fixed however as deep I went to resolve this I found that this is safari behaviour now. Safari is unable to redirect back to app because iOS put default behaviour of safari such that if some one give app path in safari it would be Mandatory to ask user to open about that’s why preview page is coming. Hope this issue will get resolved by these guys in future.

**Comment by masterhaowu** [comment]
i am facing the same issue

**Comment by Vanclief** [comment]
@affanhashone The problem is how iOS manages Universal Links. It is not posible to just call`Linking.openURL` on iOS devices. The user needs to click on the link or click a Safari "Do you want to go to this website".  I though I could depend on the Universal Link behavior to navigate the user inside my app after he scanned a QR code, so after learning about this I had to implement this behavior by hand and only rely on Universal Links when the user was coming from an external application where he clicked on the link.
