### ISSUE TITLE
🔥Dynamic Links do not work from fresh start ( IOS )

### ISSUE THREAD

**Issue by Drews4life** [invertase/react-native-firebase#1901]
## Issue
I have application already pushed to App store and Google Play. On Android Dynamic Links are working as expecte. However, when I click on dynamic link from IOS Device, first I see preview page, then I get re-directed to app store, however after installing application dynamic link is not working at all. BUT! If I try open dynamic link again -> preview page -> "Want to Open *Application Name*" -> it opens app -> dynamic link fires up as expected. So The issue happens only on fresh start.
URL Types are correct (identifier and URL scheme is the same as my bundle ID). Associated Domain is applinks:*myproject*.page.link , so it is also fine. My Team ID is matching firebase.
![applinks](https://i.ibb.co/xmDTBtR/applink.png)
![url scheme](https://i.ibb.co/DgJR3sR/applink2.png)
![dynamic link](https://i.ibb.co/2YrfrB4/link.png)
![dynamic link config](https://i.ibb.co/0r5wYZR/bhv.png)

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```
platform :ios, '9.0'

target 'heavenrank' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for heavenrank

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.11.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/AdMob', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Database', '~> 5.11.0'
  pod 'Firebase/Functions', '~> 5.11.0'
  pod 'Firebase/DynamicLinks', '~> 5.11.0'
  pod 'Firebase/Firestore', '~> 5.11.0'
  # pod 'Firebase/Invites', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
  pod 'Firebase/RemoteConfig', '~> 5.11.0'
  pod 'Firebase/Storage', '~> 5.11.0'
  pod 'Firebase/Performance', '~> 5.11.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.9'

end

```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "RNSplashScreen.h"
#import <Firebase.h>
#import "RNFirebaseLinks.h"
#import "RNFirebaseNotifications.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<NSString *, id> *)options {
  
  return [[RNFirebaseLinks instance] application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray *))restorationHandler {
  return [[RNFirebaseLinks instance] application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  [FIROptions defaultOptions].deepLinkURLScheme = @"com.matcher.app";
  
  [Fabric.sharedSDK setDebug:YES];
  [RNFirebaseNotifications configure];
  NSURL *jsCodeLocation;
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"heavenrank"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
  [RNSplashScreen show];
  return YES;
}

@end

```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ios 11+`
- **Operating System:**
  - [x] MacOS, version: `Mojave`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Xcode 10.1`
- **`React Native` version:**
  - `0.57.1`
- **`React Native Firebase` library version:**
  - `^5.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - [] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [x] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by harrydema** [comment]
My link is executed but the attribution is not working. I created [this](https://github.com/invertase/react-native-firebase/issues/1899) ticket.

Are you executing this 2 functions on the javascript side?

```
firebase.links()
            .getInitialLink()
            .then((url) => {
                if (url) {
                    this._handleOpenURL(url);
                }
            });

        this.dynamicLinksListener = firebase.links()
            .onLink((url) => {
                if (url) {
                    this._handleOpenURL(url);
                }
            });
```

**Comment by Drews4life** [comment]
> My link is executed but the attribution is not working. I created [this](https://github.com/invertase/react-native-firebase/issues/1899) ticket.
> 
> Are you executing this 2 functions on the javascript side?
> 
> ```
> firebase.links()
>             .getInitialLink()
>             .then((url) => {
>                 if (url) {
>                     this._handleOpenURL(url);
>                 }
>             });
> 
>         this.dynamicLinksListener = firebase.links()
>             .onLink((url) => {
>                 if (url) {
>                     this._handleOpenURL(url);
>                 }
>             });
> ```

this is how I handle dynamic links on javascript side, I call this method in ComponentDidMount() function

```
callbackFirebaseDynamicLink = () => {
        firebase.links()
            .getInitialLink()
            .then((url) => {
                if (url) {
                    this.setState({ loading: false })
                    this.props.navigation.navigate(REGISTER_PHONE_SCREEN);
                }
            });

    }
```

so you basically suggest me to do it like so and it might solve the issue? 

```
 callbackFirebaseDynamicLink = () => {
        firebase.links()
            .getInitialLink()
            .then((url) => {
                if (url) {
                    this.setState({ loading: false })
                    this.props.navigation.navigate(REGISTER_PHONE_SCREEN);
                }
            });

        firebase.links()
            .onLink((url) => {
                if (url) {
                    this.setState({ loading: false })
                    this.props.navigation.navigate(REGISTER_PHONE_SCREEN);
                }
            });

    }
```

**Comment by Drews4life** [comment]
@harrydema 
this is how I handle dynamic links on javascript side, I call this method in ComponentDidMount() function

```
callbackFirebaseDynamicLink = () => {
        firebase.links()
            .getInitialLink()
            .then((url) => {
                if (url) {
                    this.setState({ loading: false })
                    this.props.navigation.navigate(REGISTER_PHONE_SCREEN);
                }
            });

    }
```

so you basically suggest me to do it like so and it might solve the issue? 

```
 callbackFirebaseDynamicLink = () => {
        firebase.links()
            .getInitialLink()
            .then((url) => {
                if (url) {
                    this.setState({ loading: false })
                    this.props.navigation.navigate(REGISTER_PHONE_SCREEN);
                }
            });

        firebase.links()
            .onLink((url) => {
                if (url) {
                    this.setState({ loading: false })
                    this.props.navigation.navigate(REGISTER_PHONE_SCREEN);
                }
            });

    }
```

**Comment by katwal-dipak** [comment]
@harrydema try to put 
`[FIROptions defaultOptions].deepLinkURLScheme = CUSTOM_URL_SCHEME;` before `[FIRApp Configure]:`
I am following this documentation & its works perfectly in my side.
[iOS Installation](https://rnfirebase.io/docs/v5.x.x/links/ios)

**Comment by Drews4life** [comment]
@katwal-dipak I tried everything before I put `[FIRApp Configure]:` first. It does not work either way

**Comment by ducanhmai205** [comment]
I'm also dealing with the same problem .  Any update guy?

**Comment by Drews4life** [comment]
@ducanhmai205 didn't manage to solve this issue. I used another deep linking provider

**Comment by romit07** [comment]
same issue  :(

**Comment by ducanhmai205** [comment]
> same issue :(

i switch over use branch sdk. is work

**Comment by romit07** [comment]
@ducanhmai205 I got this working just now. I did the following changes to my code:
1) I was calling FireApp configure initially, not interchanges these lines to be : 
  ```
[FIROptions defaultOptions].deepLinkURLScheme = @"in.xyz.xdev";
  [FIRApp configure];
```
2) Changes the deep link url sceme to bundle id of my app (in.xyz.dev), previously I was using my custom domain link : (links.customdomain.com)
3) In xcode under Url Types (in info settings) I changed the  url scheme to the bundle id of my app (in.xyz.dev) and identifier to my custom deeplink domain (links.customdomain.com), In your case it is macherapp.page.link

**Comment by tonmanayo** [comment]
Hi, we are still getting this issue

**Comment by kkusanagi** [comment]
I'm got it work.

Same as @Drews4life posted.
Do what he did.

only changes is 
```
[FIROptions defaultOptions].deepLinkURLScheme = @"com.matcher.app";
[FIRApp configure];

```

The only thing that is related to Firebase dynamic link "YourApp.page.link" is under Associated Domains.
In order to enable Associated Domain, you need to go to [Apple Account] (https://developer.apple.com/account/ios/identifier/bundle) to enable it, regenerate the provision profile and download and set into your Xcode project. Then set the "YourApp.page.link" as what @Drews4life did

Once done, remove the app and install again. (just for safety purpose).

Now the trick is here. If you generate the dynamic link through the firebase, it may not work. i'm also not sure why. 
But if you generate dynamic link through the app, copy and paste it into Safari, it worked.

**Comment by i6mi6** [comment]
This problem is still present with `pod 'Firebase/Core', '~> 5.3.0'`, any update on this?

**Comment by mikehardy** [comment]
@i6mi6 I believe we're at 5.4.3 now (or 5.4.2 - check `pod outdated`)? But I also don't believe that will alter code behavior, I don't recall changes there

**Comment by i6mi6** [comment]
@mikehardy Are you also experiencing this at `5.4.3`?

**Comment by mikehardy** [comment]
I'm not using dynamic links yet but intend to, so I'm watching this and in general just help triage react-native-firebase issue

**Comment by i6mi6** [comment]
I tried with `pod 'Firebase/Core', '~> 5.4.1'` and `"react-native-firebase": "^5.4.2",` but still not working.

**Comment by mikehardy** [comment]
Okay - at least you're up to date but as mentioned I was afraid that wasn't going to help. The only thing I don't understand is how it works for for at least 3 people and not for you, that's a puzzle. It doesn't seem like this is really a problem anymore, but something isn't working right. We'd need a lot more information about exact versions, how the AppDelegate.m is working, whether you configured it correctly in the Apple provisioning profile, how you created the link, what you expect to happen, what actually happens etc. No one else seems to be working on this, so the people here will have to help if possible

**Comment by i6mi6** [comment]
As a workaround I did this: 

```
import { Linking } from 'react-native'

const dynamicLink = await Linking.getInitialURL()
const url = await fetch(dynamicLink).then(res => res.url)
// parse url here
```

**Comment by Appkidd** [comment]
Think I've just found the root cause of this issue. If "Skip the app preview page (not recommended)" is checked in the dynamic link creation then when the app is launched from installation the link will be null.

**Comment by ram95krishh** [comment]
> @ducanhmai205 I got this working just now. I did the following changes to my code:
> 
> 1. I was calling FireApp configure initially, not interchanges these lines to be :
> 
> ```
> [FIROptions defaultOptions].deepLinkURLScheme = @"in.xyz.dev";
> [FIRApp configure];
> ```
> 
> 1. Changed the deep link url sceme to bundle id of my app (in.xyz.dev), previously I was using my custom domain link : (links.customdomain.com)
> 2. In xcode under Url Types (in info settings) I changed the  url scheme to the bundle id of my app (in.xyz.dev) and identifier to my custom deeplink domain (links.customdomain.com), In your case it is macherapp.page.link

Does this change work when you do a fresh install, is the link retained post installation?

**Comment by noway** [comment]
Still happening for me too on
```
    "@react-native-firebase/app": "^0.3.0",
    "@react-native-firebase/auth": "^0.3.0",
    "@react-native-firebase/dynamic-links": "^0.3.0",
```
```
  pod 'Firebase/Core', '~> 6.5.0 '
  pod 'Firebase/Analytics', '~> 6.5.0 '
  pod 'Firebase/Messaging', '~> 6.5.0 '
  pod 'Firebase/Auth', '~> 6.5.0'
```

I can reproduce it on iPhone XS with iOS 12.2. Works fine on iOS 13.0

Can this be prioritized?

**Comment by jamesawer3** [comment]
When my iOS app is in background and if I'm trying to open the deep link my app is not getting the link

**Comment by reactdevrocks** [comment]
@jamesawer3 same happening to me with both the platforms android as well as ios, but if app starts freshly it gets the link and when app is in background app does not get any link.
Any Help?

**Comment by NikitaNeganov** [comment]
@jamesawer3 if you want to read the link in the already started app, you need to use `firebase.links().onLink() method`. For this you'll also need to configure `continueUserActivity` method in `AppDelegate.m`.

Mine, for example, is: 
```
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *))restorationHandler {
    BOOL handled = [[RNFirebaseLinks instance] application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
    if (!handled) {
      handled = [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];

    }

    return handled;
    
}
```

**Comment by ammichael** [comment]
@NikitaNeganov can you provide details on what versions you are using? 
I gave up trying to use Dynamic Links and ended up using the default RN [Linking](https://facebook.github.io/react-native/docs/linking).

**Comment by NikitaNeganov** [comment]
@ammichael sure,
`react-native: 0.59.10`
`react-native-firebase: 5.5.6`

I've also had a problem with `onLink` not working initially, but after that, I followed [this guide](https://firebase.google.com/docs/dynamic-links/ios/receive) and set my ios app properly. I can't remember, though, what exactly was off

**Comment by jamesawer3** [comment]
> BOOL handled = [[RNFirebaseLinks instance] application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
>     if (!handled) {
>       handled = [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
> 
>     }

Have done it already

**Comment by MohammadAlieye** [comment]
same issue :)

**Comment by thespacemanatee** [comment]
This is still happening if I just follow the docs and haven't found a solution for this yet.

**Comment by ScreamZ** [comment]
+1, this is hell

**Comment by mikehardy** [comment]
I'm not trying to be snarky I promise, but I've been watching the news lately, and this issue is most certainly not hell. Yes it's irritating! I get it, but let's maintain perspective. I'd be happy to merge any docs or code PRs that help, I haven't had time to look into this again personally though and may not for a while, sorry

**Comment by ScreamZ** [comment]
@mikehardy I'm sure you're not 😄. I will end up with a full JavaScript implementation without RN firebase by parsing the link on my own if I can't achieve the behavior on the native side.

See my https://github.com/invertase/react-native-firebase/issues/5962#issuecomment-1119080987
