### ISSUE TITLE
Documentation for Admob is null

### ISSUE THREAD

**Issue by bitfabrikken** [invertase/react-native-firebase#191]
The docs at http://invertase.io/react-native-firebase/#/modules/admob just shows null.
I'd really like to use admob, but I can't figure it out without some documentation :)

**Comment by Salakar** [comment]
Ironically adblock blocks it ;p you need to turn it off for the site - there is no ads anyway :)

**Comment by bitfabrikken** [comment]
Haha. Thank you! Perhaps add that instruction as the text instead of null?

**Comment by bitfabrikken** [comment]
And thanks for a great module!

**Comment by Salakar** [comment]
It's an external module that generates the docs - we dont have control over what it shows if it fails to load unfortunately
