### ISSUE TITLE
android8, 9 : android.setLights(...) is not working

### ISSUE THREAD

**Issue by cx5168** [invertase/react-native-firebase#1911]
react-native-firebase@4.3.8
react-native@0.55.4

Received notification on Android 8, 9 mobile phone that led lighting cannot work . 
can you have a solution?

**Comment by cx5168** [comment]
Solved!

**Comment by notjulian** [comment]
> react-native-firebase@4.3.8
> react-native@0.55.4
> 
> Received notification on Android 8, 9 mobile phone that led lighting cannot work .
> can you have a solution?

hi,
how you solved this?

thanks

**Comment by sam9010** [comment]
@cx5168 ,@notjulian
i have this problem
can you help me?
thanks

**Comment by cx5168** [comment]
@sam9010 

const channel = new Firebase.notifications.Android.Channel(
          'default_notification_channel_id',
          'aaa',
          Firebase.notifications.Android.Importance.Max,
        );
        channel.setDescription('aaa');
        channel.enableLights(true);
        channel.enableVibration(true);
        Firebase.notifications().android.createChannel(channel);

**Comment by sam9010** [comment]
@cx5168 thanks a lot for your answer
i write this code
`     const channel = new firebase.notifications.Android.Channel(
                    'notification_channel_name', // To be Replaced as per use
                    'Notifications', // To be Replaced as per use
                    firebase.notifications.Android.Importance.Max
                ).setDescription('A Channel To manage the notifications related to Application');
                firebase.notifications().android.createChannel(channel);

console.log("hi");
 const localNotification = new firebase.notifications.Notification({
                        sound: 'default',
                        show_in_foreground: true,
                    })
                        .setNotificationId(message.messageId)
                        .setTitle(Data.title)
                        .setBody(Data.text)
                        .android.setChannelId('channel-id')
                        .android.setSmallIcon('ic_notification_icon') // create this icon in Android Studio
                        .android.setPriority(firebase.notifications.Android.Priority.High);
                    firebase.notifications().displayNotification(localNotification);
`
but i do not get notification in android 9

**Comment by barak109** [comment]
I"m trying to do what you suggested but still i didn't see led light notification changed
@cx5168 
this is my code 

```
const notification = new firebase.notifications.Notification();
  const channel = new firebase.notifications.Android.Channel(
    "test",
    "test",
    firebase.notifications.Android.Importance.Max
  );
  channel
    .enableVibration(true)
    .enableLights(true)
    .setLightColor("0xff0000ff");
  firebase.notifications().android.createChannel(channel);

  notification.android.setChannelId("test");
  // give the behavior of tag and override the old notification
  notification.android.setAutoCancel(true).setNotificationId("1");
  notification.android.setVibrate([1000, 1000, 1000, 1000, 1000]);
  notification.android.setLights(0xff0000ff, 10000, 10000);
  notification.setTitle(message.data.title);
  notification.setBody(message.data.body);
  notification.setSound(message.data.sound);

  firebase.notifications().displayNotification(notification);

```
