### ISSUE TITLE
React Native Firebase installation issue in ios with pods

### ISSUE THREAD

**Issue by tusharnetset** [invertase/react-native-firebase#1912]
Hello 
I am getting this error in react native firebase installation in ios.

Unhandled JS Exception: RNFirebase core module was not found natively on iOS, ensure you have correctly included the RNFirebase pod in your projects `Podfile` and have run `pod install`

<img width="219" alt="screen shot 2019-02-20 at 4 11 09 pm" src="https://user-images.githubusercontent.com/28781897/53086557-5b1cf100-352b-11e9-9499-0ddf6d12a696.png">

**Comment by Ehesp** [comment]
Please follow the issue template so we can help.
