### ISSUE TITLE
How to disable Crashlytics while working in debug mode?

### ISSUE THREAD

**Issue by archana-iron** [invertase/react-native-firebase#1913]
I have integrated firebase Crashlytics on a react native application. I want to disable crash logs while working on development mode. How can I disable crash logs in debug mode for both Android and Ios Application. To create crash logs I have followed react native firebase documentation check this official link :: https://rnfirebase.io/docs/v5.x.x/crashlytics/android

I am using react-native-firebase version 5.2.2

I want to disable logs on debug mode without changing the version. I want to add code to disable the crash log for both Android and Ios. Please suggest how this should be done.

**Comment by Salakar** [comment]
Hey @archana-iron; for now you can create a debug `AndroidManifest.xml` e.g. in `app/src/debug/AndroidManifest.xml` (clone of your current `AndroidManifest.xml`) and then add the following inside your `application` declaration:

```xml
// ...

<application>
  // ...

  <meta-data
    android:name="firebase_crashlytics_collection_enabled"
    android:value="false"/>
  // ...

</application>
// ...
```

We'll add something for v6.0.0 release to allow you to do this via JS. You can track this here: https://github.com/orgs/invertase/projects/2#card-17470855

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
