### ISSUE TITLE
support firebase events (ecommerce_purchase, travel, or games). 

### ISSUE THREAD

**Issue by MoeMamdouh** [invertase/react-native-firebase#1917]
## Documentation Feedback
did the library support the firebase predefined events and its required parameters like
 [ecommerce_purchase](https://support.google.com/firebase/answer/6317499?hl=en) 
[other events ](https://support.google.com/firebase/answer/6317498?hl=en&ref_topic=6317484)
and the required [parameters](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event#ECOMMERCE_PURCHASE) for ecommerce  

this is valid?
revenue metrics can be computed accurately?
```
const params = {
  TRANSACTION_ID: cartId,
  VALUE: grand_total,
  SHIPPING: shipping_amount,
  CURRENCY: quote_currency_code,
  COUPON: coupon_code
};
firebase.analytics().logEvent("ECOMMERCE_PURCHASE", params);
```

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by Salakar** [comment]
Hey @MoeMamdouh; yes these are supported via the standard [`logEvent(event, params)`](https://rnfirebase.io/docs/v5.x.x/analytics/reference/analytics#logEvent) method.

The event names and params are case sensitive; so you'll need to change your code above to be lowercase.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by MoeMamdouh** [comment]
thank you @Salakar 
so event name and  params should be in lowercase like this: 

```
const params = {
 transaction_id: cartId,
  value: grand_total,
  shipping: shipping_amount,
 currency: quote_currency_code,
  coupon: coupon_code
};
firebase.analytics().logEvent("ecommerce_purchase", params);
```
right?

**Comment by Salakar** [comment]
@MoeMamdouh correct 👍
