### ISSUE TITLE
[iOS] firebase.links().onLink

### ISSUE THREAD

**Issue by dantn93** [invertase/react-native-firebase#1919]
## Issue

Hi everyone,
I have an issue, below:
I use "getInitialLink" for URLs which cause the app to open from a previously closed / not running state. It DOES successfully.
But when I use "firebase.links().onLink()" for opening app which is running on background state. I can NOT get the link. How can I fix it?
I followed this guideline https://rnfirebase.io/docs/v5.x.x/links/reference/links

---

#### `ios/Podfile`:
- [x] I'm using Pods and my Podfile looks like:

## Environment

- **Platform that you're experiencing the issue on**:
  - [ x ] iOS
- **Operating System:**
  - MacOS, version: Mojave
- **Build Tools:**
  - Xcode 10
- **`React Native` version:**
  - 0.55.4
- **`React Native Firebase` library version:**
  - 4.3.8

**Comment by dantn93** [comment]
I resolved this issue. This is my mistake.
In AppDelegate.m I did not return this
"return [[RNFirebaseLinks instance] application:application continueUserActivity:userActivity restorationHandler:restorationHandler];"

**Comment by appli-intramuros** [comment]
@dantn93 I have exactly the same problem and my AppDelegate is correct... (according to the documentation). 
Can you share to me your xcode configuration (with URL types created) and your appdelegate ?
Thanks.

**Comment by romit07** [comment]
I am having the exact same issue, getInitialLink() is working but onLink() does not, I have the exact same code in my app delegate

**Comment by emekadev** [comment]
Does this work on your emulator?

**Comment by weberjc** [comment]
I had the same issue as well, getInitialLink() worked, but the onLink() listener never fired.
In my case, i was interfacing from AppDelegate.swift, and i needed to grab the instance instead of reconstructing it with RNFirebaseLinks().  Then the listener worked fine.  Searching for RNFirebaseLinks in the logs helped narrow it down.

`RNFirebaseLinks.instance().application(application, continue: userActivity, restorationHandler: restorationHandler)
`

**Comment by benevbright** [comment]
@weberjc So, did you get it work for you? Could you explain a bit more? Thanks.

**Comment by weberjc** [comment]
@benevbright i think it did work for me yes, when i remembered to grab the instance with .instance like in the code example above RNFirebaseLinks.instance().application(...) when integrating the listener on the native side in the AppDelegate.swift.
Although i ended up having an issue on android if memory serves right and then coming up with a custom lightweight solution instead.
