### ISSUE TITLE
TypeError: _reactNativeFirebase.default.crashlytics(...).enableCrashlyticsCollection is not a function.

### ISSUE THREAD

**Issue by archana-iron** [invertase/react-native-firebase#1920]
I have integrated react-native-firebase and using crashlytics module to generate crash logs. It works fine, but I want to generate crash logs only on development mode just for testing. After testing I will generate crash logs only only production. 
According to your manual guideline instruction, I have added code inside AndroidManifest.xml, and in info.plist file 

iOS::
Turn off automatic collection with a new key to your Info.plist file:

> Key: firebase_crashlytics_collection_enabled
> Value: false

Android
Turn off automatic collection with a meta-data tag in AndroidManifest.xml file:
```
<meta-data
    android:name="firebase_crashlytics_collection_enabled"
    android:value="false" />
```

Enable collection at runtime
I have initialised crashlytics inside my app.js file, like this
```
if (__DEV__) {
      firebase.crashlytics().enableCrashlyticsCollection();
}
```

It returns me an error::

> TypeError: _reactNativeFirebase.default.crashlytics(...).enableCrashlyticsCollection is not a function.

I am using React native version:: 0.58
React native firebase version :: 5.2.2

What should I do to resolve this issue, please suggest.

**Comment by Salakar** [comment]
Crashlytics has recently had a major overhaul in https://github.com/invertase/react-native-firebase/pull/1958 - this will land as part of v6. 

As this issue no longer applies (auto-init can be managed through firebase.json now and two new methods to control it; see the [changelog](https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md#crashlytics)) I will close and lock this issue.

If you have any feedback/queries relating to the PR above please ask in the `#crashlytics` discord channel or create an issue with `[v6]` in the title. 

Thanks for reporting 💛

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
