### ISSUE TITLE
PushNotification setSound is not working properly for android os 8.

### ISSUE THREAD

**Issue by RajPatel9490** [invertase/react-native-firebase#1922]
I am using react native firebase library for push notification and i am playing two different sound for two different notification so i am playing some .mp3 sound for one notification and default for other one so problem is app is playing only that sound which is coming in first notification for app and for rest notification playing the first played sound so I think the issue is notification information is not updating that's what it is playing the same sound for all the notification which app got for first notification.even we are getting right information in notification data but it is not updating the sound.
I used used that NotificationChannel.setSound() for API 26 so the problem is notification is playing only one sound even if we set different sounds.If your first notification for app has sound like "alert.mp3" so it will play that sound for the all other notification even if you set "default" for others.

### Environment
1. Application Target Platform:

Android API 21 and above.

1. Development Operating System:

Developing on macOS High Sierra 10.13.6.

1. Build Tools:

Android studio 3.3.1

1. `React Native` version:

0.56.1

1. `React Native Firebase` Version:

ˆ4.3.8

1. Are you using `typescript`?

yes.

I am getting data from firebase and below is my code to set Sound for notification.

this.notificationListener = firebase
  .notifications()
  .onNotification((notification: Notification) => {

    const channel = new firebase.notifications.Android.Channel(
      'test-channel',
      'Test Channel',
      firebase.notifications.Android.Importance.Max
    ).setDescription('My apps test channel');

    if (notification && notification.data) {
      const data = notification.data;
      if (data && data.messageKey) {
        //here I set the sound on basis of notification data to the channel

    ...
      } 
    }

    // Create the channel
    firebase.notifications().android.createChannel(channel);
    // Process your notification as required
    notification
    .android.setChannelId('test-channel')
    .android.setSmallIcon(Images.logoSmall);

firebase.notifications()
    .displayNotification(notification);
  });

**Comment by Dhrupal** [comment]
Can we have have duplicate ticket?

**Comment by cx5168** [comment]
// create channel
const channel = new Firebase.notifications.Android.Channel(
          'default_notification_channel_id',
          'aa',
          Firebase.notifications.Android.Importance.Max,
        );
        channel.setDescription('aa');
        channel.enableLights(true);
        channel.enableVibration(true);
        Firebase.notifications().android.createChannel(channel);

// display notification
const newNotification = new Firebase.notifications.Notification();
  newNotification.android.setChannelId('default_notification_channel_id');
  newNotification.android.setAutoCancel(true);
  newNotification.android.setLights(0xFF00FF00, 200, 200);
  newNotification.android.setVibrate([200, 200, 200, 200]);
  newNotification.android.setSmallIcon('notification');
  // android6
  if (Platform.Version <= 23) {
    newNotification.setTitle('aaaa');
  }
  newNotification.setSound('default');
  newNotification.setData({
    foreground: false,
    message: message.data.alert,
    url: message.data.url,
  });

  Firebase.notifications().displayNotification(newNotification);

**Comment by izaa** [comment]
@RajPatel9490 Hi do you have any tips, since my Android won't vibrate at all, and I hear only one single default notification sound but what i would need is longer vibration and sound like phone call. My code is like @cx5168 wrote. Thanks.

**Comment by RajPatel9490** [comment]
setSound before crating the channel like  **channel.enableVibration('alert');** and you need to put that alert.mp3 file in raw Directory in android.I think this will work to play your phone call sound thank you.

**Comment by izaa** [comment]
Hi @RajPatel9490 

thanks! Ok without .mp3 in setSound it works. Why I didn't try that before? :D anyway, now it only vibrates once, do the setVibrationPattern work in your app?

**Comment by RajPatel9490** [comment]
setSound work without .mp3 and I didn't try with setVibrationPattern.Thanks.

**Comment by ydv0121** [comment]
Hello @RajPatel9490 
i am getting HeadUp notification in andorid 8 and later
did you able to get **HeadUp** notification in android <= 25 (Lolipop,Marshmellow,Nougat) ???

**Comment by windydang26** [comment]
@ydv0121 if you want to get headup notification on android <= 7 you must set sound for noti.

**Comment by ydv0121** [comment]
@windydang26 where i need to set noti sound..in notification payload?? Or when i received the notification

**Comment by meliodev** [comment]
Hey guys, I struggled for hours to make a custom sound for notifications on android but it is still not working :'( . Please do anybody have a solution for this ? I put 'ringtone.mp3' on res/raw and . @RajPatel9490 I tried to use 'ringtone' without .mp3 but still not working :(

Here is my code :

`
        const channel = new firebase.notifications.Android.Channel(
          "channelId",
          "Channel Name",
          firebase.notifications.Android.Importance.Max
        )
          .setDescription("A natural description of the channel")
          .setSound('ringtone');

        firebase.notifications().android.createChannel(channel);

        const localNotification = new firebase.notifications.Notification()
          .setNotificationId(notification.notificationId)
          .setTitle(notification.title)
          .setSubtitle(notification.subtitle)
          .setBody(notification.body)
          .setData(notification.data)
          .setSound(channel.sound)
          .android.setChannelId("channelId")
          .android.setAutoCancel(true)
          .android.setVibrate(3000)
          .android.setColor("#93eafe") // you can set a color here
          .android.setGroup(notification.notificationId)
          .android.setPriority(firebase.notifications.Android.Priority.High);

        firebase.notifications().displayNotification(localNotification)
          
`
