### ISSUE TITLE
Documentation links not working

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [invertase/react-native-firebase#1924]
The two links for 
"Guides" and "Installation" are not implemented, but since they should probably just link to something like [https://rnfirebase.io/docs/v5.x.x](https://rnfirebase.io/docs/v5.x.x), I thought it must be a mistake.

**Comment by Salakar** [comment]
Hey, where are these links? Thanks

**Comment by Ehesp** [comment]
@Salakar readme ones - we can just remove until new docs are up.

**Comment by Salakar** [comment]
Ah ok, was confused 😅 will update readme for now or link to the old ones as suggested by @jenskuhrjorgensen (thanks for reporting)
