### ISSUE TITLE
🔥 Storage does not support App as parameter

### ISSUE THREAD

**Issue by AlexandreMaistret** [invertase/react-native-firebase#1926]
## Issue
Hi !

I am using several databases and buckets for my mobile application.
I am initializing my App with : 

    await firebase.initializeApp(
          {
            appId: 'XXXX',
            apiKey: 'XXXX',
            databaseURL: 'XXXX',
            storageBucket: 'XXXX',
            messagingSenderId: 'XXXX',
            projectId: 'XXXX',
          },
        'database1',
      );

 and then for using this particular database I am using :

     const database = firebase.app('database1').database();
     await database.ref('/users/')
    .set({
      username:  username,
      last_update: firebase.database.ServerValue.TIMESTAMP,
    });

which works like a charm, but when I want to use the bucket  also initialize with the same database I am using:

    const app = firebase.app('database1');
    const storage = firebase.app().storage(app);

And I have an error  `Error: storage does not support a URL or region as a param, please pass in an app.`, which I don't really understand why since I put a `console.log` for the constant `app`, and it is  a Firebase App.

I also tried 

    firebase.app('database1').storage();

but the application crashed and said `The storage uri cannot contain a path element.`

---

#### `android/app/build.gradle`:

    implementation project(':react-native-firebase')
    implementation "com.google.firebase:firebase-core:16.0.7"
    implementation 'com.google.android.gms:play-services-base:16.1.0'
    implementation "com.google.firebase:firebase-auth:16.1.0"
    implementation "com.google.firebase:firebase-messaging:17.3.4"
    implementation "com.google.firebase:firebase-database:16.0.6"
    implementation "com.google.firebase:firebase-storage:16.0.5"
    implementation "com.google.firebase:firebase-invites:16.1.0"

## Environment

- **Platform that you're experiencing the issue on**:
  - [X] **Android** but have not tested behavior on iOS
- **If known, the version of the platform are you experiencing the issue on:**
  - Android API 28
- **Operating System:**
  - [X] Windows, version: `8.1`
- **Build Tools:**
  -  Android Studio 3.2
- **`React Native` version: 0.55.4
- **`React Native Firebase` library version: 5.1.1
- **`Firebase` module(s) you're using that has the issue:
  - [X] Storage
- **Are you using `TypeScript`?**
  - [X] No
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No

**Comment by mikehardy** [comment]
@Salakar This is a tangent but they just added multi-app support to remoteconfig - not sure if that is in v6 (you can see it in the android sdk release notes and they link here: https://firebase.google.com/docs/reference/android/com/google/firebase/remoteconfig/FirebaseRemoteConfig#getInstance(FirebaseApp) )

For the specific issue the API for storage does seem to support multi-app so it seems like this should work, though @AlexandreMaistret may have learned something in the time after filing the issue and just isn't responding to the stale-bot ?

**Comment by AlexandreMaistret** [comment]
Unfortunately @mikehardy I didn't find any solution for this. I am just using several databases for one bucket storage.

**Comment by mikehardy** [comment]
I think this is valid then, and more over I believe @Salakar is right.this.moment. working on storage v6 so it might be easy to investigate while he's got all the right tools laid out on the workbench

**Comment by Salakar** [comment]
The correct usage is as demonstrated in Example 2 & 3 here: https://dev.invertase.io/oss/react-native-firebase/v6/storage/reference/module

Multiple apps work in v5 this way, multi-buckets support however only lands in v6 - have just finished the storage re-write about an hour ago (just working through android CI being a PITA)

**Comment by Salakar** [comment]
Closing as v6 Cloud Storage PR has landed. Will publish an alpha release later today.

Thanks again 👍
