### ISSUE TITLE
App crashes when user "cancels" google signin

### ISSUE THREAD

**Issue by addu1** [invertase/react-native-firebase#1927]
## Issue
Integrated Social Auth google signin as per the documentation.
App works fine when user continues with login, but crashes when user cancels the google signin.
This issue occurred on iOS simulators(haven't checked on real devices & android devices)

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [

![error](https://user-images.githubusercontent.com/17162834/53411520-b0a24380-39ec-11e9-9687-d1a47aad05f2.png)

x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `ADD_SOMETHING_HERE`
- **`React Native` version:**
  - `0.58.5`
- **`React Native Firebase` library version:**
  - `5.2.2`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [x] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

**Comment by addu1** [comment]
@Salakar any workaround for this ?

**Comment by rborn** [comment]
@addu1 how are you signing in? I'm on `5.2.3` and all works as expected

```
const googleSignIn = async () => {
    try {
        // add any configuration settings here:
        await GoogleSignin.configure({
            iosClientId: firebase.app().options.clientId
        });

        const data = await GoogleSignin.signIn();
        const credential = firebase.auth.GoogleAuthProvider.credential(data.idToken, data.accessToken);
        const firebaseUserCredential = await firebase.auth().signInWithCredential(credential);
        return firebaseUserCredential;
    } catch (error) {
        // console.warn(error);
        return { error };
    }
};

```

**Comment by Salakar** [comment]
Closing this as it's not an issue with this library specifically. You should catch your JS exceptions to handle user cancellation, as per @rborn's example.

Thanks
