### ISSUE TITLE
HEADER_SEARCH_PATHS problem

### ISSUE THREAD

**Issue by hamidhadi** [invertase/react-native-firebase#193]
When I run `pod install` I get this warning 

     target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-AppName/Pods-AppName.debug.xcconfig'. This can lead to problems with the CocoaPods installation

**Comment by SamMatthewsIsACommonName** [comment]
HI @hamidhadi there are problems in the documentation for fixing this here: http://invertase.io/react-native-firebase/#/installation-ios

**Comment by hamidhadi** [comment]
@SamMatthewsIsACommonName I know there are some instructions in the documentation about target overrides 'OTHER_LDFLAGS'` and I fixed, but my problem is different from that. 
If you recheck my question, you can see I have a problem with `HEADER_SEARCH_PATHS` defined in `Pods/Target` not in main  app target.

**Comment by SamMatthewsIsACommonName** [comment]
Sorry I misread it. Does doing the same thing of adding the inherited tag to the header search paths help?

**Comment by hamidhadi** [comment]
@SamMatthewsIsACommonName cocoapods automatically added the `$(inherited)` tag to the `Pods/Target` header search paths.

**Comment by chrisbianca** [comment]
@hamidhadi the same does apply for header search paths - you need to make sure that `$(inherited)` is set as the top line of your header search paths setting.  This should take away the morning.

Out of interest, what is the header search paths currently set to?

**Comment by chrisbianca** [comment]
@hamidhadi I'm going to assume this is no longer an issue and close it.  Please let me know if this is not the case.

**Comment by ziyafenn** [comment]
Still have the problem
