### ISSUE TITLE
No sound and vibrations with local notification on Android 8.x - 9.x

### ISSUE THREAD

**Issue by lorenc-tomasz** [invertase/react-native-firebase#1930]
RN 0.58.5
RN-firebase: 5.xx (latest)

I create the channel

>     const channel = new firebase.notifications.Android.Channel(
>       ANDROID_CHANNEL_ID,
>       ANDROID_CHANNEL_NAME,
>       firebase.notifications.Android.Importance.Max,
>     ).setSound('default')
>       .enableLights(true)
>       .enableVibration(true)
>       .setVibrationPattern(ANDROID_VIBRATION_PATTERN);
> 
>     // Create the channel; This method can be called many times
>     return firebase.notifications().android.createChannel(channel);

Then I schedule local notification where I set the sound and vibration pattern.

>   .setSound('default')
>   .android.setChannelId(ANDROID_CHANNEL_ID)
>   .android.setGroup(ANDROID_GROUP)
>   .android.setGroupSummary(true)
>   .android.setGroupAlertBehaviour(firebase.notifications.Android.GroupAlert.Children)
>   .android.setCategory(firebase.notifications.Android.Category.Reminder)
>   .android.setAutoCancel(true)
>   .android.setSmallIcon(ANDROID_SMALL_ICON)
>   .android.setLargeIcon(ANDROID_LARGE_ICON)
>   .android.setColor(ANDROID_NOTIFICATION_ACCENT_COLOR)
>   .android.setColorized(true)
>   .android.setPriority(firebase.notifications.Android.Priority.Max)
>   .android.setVisibility(firebase.notifications.Android.Visibility.Public)
>   .android.setVibrate(ANDROID_VIBRATION_PATTERN);

But there is no sound and vibration in foreground and background. Any idea?

**Comment by lorenc-tomasz** [comment]
Works with Android 5.x, 6.x, 7.x

@Salakar Any idea why there is a problem with Android 8.x? There are many notes suggesting than sounds and vibration don't work with RN-firebase.

**Comment by RajPatel9490** [comment]
does it play mobile default notification sound or not?

**Comment by lorenc-tomasz** [comment]
Nothing. No sound, no vibration. I have checked the app settings (notification channel settings) and there should be sound and vibration but there is non. On Androids lower than 8.x everything works ok.

**Comment by RajPatel9490** [comment]
yes for me also lower than os 8 working.so put one alert.mp3 file in raw directory in your app and set that sound in like:-
const channel = new firebase.notifications.Android.Channel(
  ANDROID_CHANNEL_ID,
  ANDROID_CHANNEL_NAME,
  firebase.notifications.Android.Importance.Max,
).setSound('alert');

and check its working or not...i think this will work...so pls try this.thanks.

**Comment by lorenc-tomasz** [comment]
No luck. I have added alert.mp3 file to raw directory. Within app setting there was information that sound within the channel will you file from application but there was no sound :(

**Comment by lorenc-tomasz** [comment]
I have managed it to work. Firstly I create new channel as below. Remember to change channel ID as channel cannot be changed after creation. 

> const channel = new firebase.notifications.Android.Channel(
>   ANDROID_CHANNEL_ID,
>   ANDROID_CHANNEL_NAME,
>   firebase.notifications.Android.Importance.Max,
> ).setSound('default')
>   .enableLights(true)
>   .enableVibration(true)
>   .setVibrationPattern(ANDROID_VIBRATION_PATTERN);

Then I have setup those two value when I creating notification:

> .android.setGroupAlertBehaviour(firebase.notifications.Android.GroupAlert.All)
>   .android.setCategory(firebase.notifications.Android.Category.Alarm)

And it started to work.

**Comment by SteponasIvasovas** [comment]
@lorenc-tomasz hey can you please post your full code of creating notification because your solution doesn't work for me :(

**Comment by lorenc-tomasz** [comment]
Did you create new channel? I'm using the sane code from first post with the changes mentioned above. Nothing more. 

PS Based on all the issues here, each user has find his own solution.

**Comment by marchaos** [comment]
Same here - this is not working. I've created the channel as per  your sample code.

**Comment by micrax** [comment]
If you had create a channel, uninstall your apk and try again. 
You can't update channel settings after it created

**Comment by mikehardy** [comment]
@micrax - one tidbit - some settings may be updated after channel creation, name and description mainly. You are correct for the context here in that sound / vibration can only be changed by settings panel or reinstall though

**Comment by bhaskar8088** [comment]
I tried this but this is not working. I tried creating multiple channels for testing but none worked.
