### ISSUE TITLE
All the hyperlinks in the documentation are broken. 

### ISSUE THREAD

**Issue by redelman431** [invertase/react-native-firebase#1936]
## Documentation Feedback

Hello, I just want to report that all the hyperlinks in the documentation are broken and seem to just anchor the URL with #TODO. Especially in the Cloud Messaging, Guides, and installation links. Can you please fix this problem so I can read the documentation please? The problem is in both Chrome and Firefox on a Linux OS. Thank you. 

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by Ehesp** [comment]
Sorry they're place holders for v6! Check out https://rnfirebase.io for now 👍
