### ISSUE TITLE
RemoteInput is not available on submit

### ISSUE THREAD

**Issue by santhosh77h** [invertase/react-native-firebase#1937]
## Issue

Issue regarding the notification with action reply inputText details whatever sent by the user is not received to the headless js service or listner.

In case of `onNotificationOpened` results field is undefined and in case of `RNFirebaseBackgroundNotificationAction` service results field is not found at all.

actions creation looks like this 

```Javascript
const reply = new firebase.notifications.Android.Action(
      "action_reply",
      "ic_stat_ic_notification",
      "Reply"
    );
    const ActionReply = firebase.notifications.Android.SemanticAction.Reply;
    reply.setSemanticAction(ActionReply);
    const remoteInput = new firebase.notifications.Android.RemoteInput(
      "inputText"
    ).setLabel("Reply Message");
    reply.addRemoteInput(remoteInput);
    reply.setAllowGenerateReplies(true);
    reply.setShowUserInterface(false);
    notification.android.addAction(reply);
```

---

#### `AndroidManifest.xml`:

```xml
        <receiver android:name="io.invertase.firebase.notifications.RNFirebaseBackgroundNotificationActionReceiver" android:exported="true">
            <intent-filter>
                <action android:name="io.invertase.firebase.notifications.BackgroundAction"/>
            </intent-filter>
        </receiver>
        <service android:name="io.invertase.firebase.notifications.RNFirebaseBackgroundNotificationActionsService"/>
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `ADD_SOMETHING_HERE` e.g. Xcode 10, Android Studio 3.2
- **`React Native` version:**
  - `0.52.0`
- **`React Native Firebase` library version:**
  - `^4.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - [] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [x] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by mikehardy** [comment]
This is only a snippet of the files requested in the template - have you integrated anything that also may grab Intents as they are passed through Activities when notifications are tapped, like the common way of integrating react-native-splash-screen?
