### ISSUE TITLE
Android: play services prompt cannot be disabled

### ISSUE THREAD

**Issue by paladin952** [invertase/react-native-firebase#1938]
🔥
# Issue
I am trying to turn off Google Play Services availability errors because amazon devices don't have Play Services.
I tried:
- firebase.utils().errorOnMissingPlayServices = false;
- firebase.utils().promptOnMissingPlayServices = false;
as described but doesn't seem to do anything.

I tried debugging and seems that assigning those fields happen after the initial setup of the library, after the dialog is shown, but couldn't find a way to set them before.

Am I missing something?
Thanks!

## Environment
- **Platform that you're experiencing the issue on**:
  - [x] Android
- **`React Native` version:**
  - `0.55.3`
- **`React Native Firebase` library version:**
  - `4.0.3`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] Analytics
- **Are you using `TypeScript`?**
  - [x] No

**Comment by AndreasBoehm** [comment]
Same issue here!
Trying to publish an app to the Amazon Store and none of the Amazon Devices has Play Services.
Please keep it open and take a look.

**Comment by tomosedplus** [comment]
Also keen to understand this one a little better!

**Comment by curiousdustin** [comment]
I would also like to be able to disable this prompt. I am trying to use Firebase Analytics, but this prompt is a dealbreaker.

**Comment by curiousdustin** [comment]
There might be a better solution, but I found that I could modify these lines in `internals.js`:

```
OPTIONS: {
    logLevel: 'warn',
    errorOnMissingPlayServices: false,
    promptOnMissingPlayServices: false
  },```

**Comment by mikehardy** [comment]
@curiousdustin https://rnfirebase.io/docs/v5.x.x/troubleshooting/android#Turning-off-Google-Play-Services-availability-errors

**Comment by curiousdustin** [comment]
Thanks @mikehardy :)

This DID work for me. I put those lines immediately after the import.

```
import firebase from 'react-native-firebase';
firebase.utils().errorOnMissingPlayServices = false;
firebase.utils().promptOnMissingPlayServices = false;
```

**Comment by AndreasBoehm** [comment]
@curiousdustin which version of `react-native-firebase` are you using?

**Comment by curiousdustin** [comment]
`5.2.2`
