### ISSUE TITLE
Unable to resolve dependency for ':app@prodDebugAndroidTest/compileClasspath': Failed to transform file 'react-native-firebase-release.aar' to match attributes {artifactType=processed-aar} using transform IdentityTransform

### ISSUE THREAD

**Issue by denizbas92** [invertase/react-native-firebase#1939]
Hi I am getting this strange error. After I open my react-native project on android studio, when I make sync android/app/build.gradle file, I am getting the error as shown above, I have no idea what is going on ? Gradle always sync failed 
My platform is Android.
React-Native version is 0.58.5
Android studio version is 3.2.1
classpath 'com.android.tools.build:gradle:3.2.0'
classpath 'com.google.gms:google-services:4.0.1'
classpath 'com.google.firebase:firebase-plugins:1.1.5'
 "react-native-firebase": "5.2.2",

Is there any solution ?

**Comment by hackyxicor** [comment]
any solution?

**Comment by denizbas92** [comment]
Clean and rebuild project worked for me. However ,I am not sure the problem is gonna happen again or completely solved

**Comment by NativLouie** [comment]
same issue

**Comment by fgagneten** [comment]
+1. Same issue

**Comment by fgagneten** [comment]
This is the detail:
![image](https://user-images.githubusercontent.com/14353978/55669955-f7892180-5853-11e9-9697-73460755aa0b.png)

I think is related to this issue (cleaning the solution I got MultiDex error):
https://github.com/invertase/react-native-firebase/issues/2032

**Comment by fgagneten** [comment]
Cleaning the project you will get the real error

**Comment by Salakar** [comment]
Make sure your app/build.gradle has react-native firebase in dependencies like this:

```groovy
implementation project(path: ':react-native-firebase')
```

and **not**:

```groovy
implementation project(path: ':react-native-firebase', configuration: 'default')
```

**Comment by denizbas92** [comment]
> Make sure your app/build.gradle has react-native firebase in dependencies like this:
> 
> ```groovy
> implementation project(path: ':react-native-firebase')
> ```
> 
> and **not**:
> 
> ```groovy
> implementation project(path: ':react-native-firebase', configuration: 'default')
> ```

Thanks, it worked.
