### ISSUE TITLE
RNFirebaseMessaging.m have some errors now

### ISSUE THREAD

**Issue by GoldenStar1024** [invertase/react-native-firebase#194]
I have built the app using react-native-firebase v2
But I have some errors now.
![screen shot 2017-06-22 at 5 53 53 pm](https://user-images.githubusercontent.com/23504042/27440713-462a7736-5774-11e7-811d-e71cff501e88.png)

**Comment by chrisbianca** [comment]
Please see: https://github.com/invertase/react-native-firebase/issues/186

You need to ensure that the correct version of Firebase is being installed, which may mean bumping from iOS 8 to iOS 9 as a minimum supported version
