### ISSUE TITLE
ArrayUnion allows adding duplicate elements (on client DB)

### ISSUE THREAD

**Issue by jakebern** [invertase/react-native-firebase#1943]
Posted on [GitHub](https://stackoverflow.com/questions/54967021/firestore-arrayunion-adds-duplicates), but figured this was maybe an RN-Firebase issue since a newly added feature.

**Comment by Salakar** [comment]
Please correctly fill out the issue template, specifically the versions you're using of everything, without this, we can't really help. Also if you could provide code that demonstrates the incorrect behaviour this will help investigation towards a fix if an issue is found.

Locking and closing this issue. Feel free to raise another issue that correctly follows the issue template as mentioned above.
