### ISSUE TITLE
:fire: Badge counter does not work

### ISSUE THREAD

**Issue by mtieltjes** [invertase/react-native-firebase#1945]
## Issue
Im able to fully receive and show notifications on iOS, but I'm not able to show a reliable badge counter.
What im trying to do is simple:
- Receive notification --> increase badge by 1

In React we register to firebase stuff asap with this method:
```javascript
firebase.notifications().onNotificationDisplayed((notification: Notification) => {
       firebase.notifications().getBadge()
          .then( count => {
            count++
            firebase.notifications().setBadge(count)
         })
         .then(() => {
           console.log('Doing great')
         })
         .catch( error => {
           console.log('fail to count')
         })
    });
```
`onNotificationDisplayed` because I want this to work in the background/while killed as well. If I use `onNotification`, the badge sometimes gets increased twice.

Which works the first boot and while app stays in memory. Both in foreground and background.
HOWEVER!
When the app is killed (first time since initial boot) the callback breaks. Restarting the app does not help and the badge is not incremented anymore.

### Bonus issue
I found out that while incrementing the badge counter through code, the library/firebase/witches override the change. I see the counter being incremented and immediately reset to its previous value. 
If I use a Math.random() to set the coutner in code I see the random value being set, and immedtiately back to its previous value. It seems like firebase remembers its last `"badge":<value>` thats beint sent with firebase. When not providing the `badge` field in the notification, it keeps restoring the last set value that was set through a notification

### Notification format used to replicate the issue
```json
{
  "to" : "%TO%",
  "priority": "high",
  "content_available": true,
  "notification" : {
    "body" : "noti body",
    "title" : "noti title",
    "link": "noti link ",
    <Optional>"badge": 4 <-- Badge is always sets to the last value you put in here if you let it out for some reason
  }
}
```

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods

#### `AppDelegate.m`:

```objc
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
    [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [X] iOS
- **If known, the version of the platform are you experiencing the issue on:**
  - `iOS 11` e.g. iOS 10 or Android API 28
- **Build Tools:**
  - `Xcrash 10.1` 
- **`React Native` version:**
  - `0.57.8`
- **`React Native Firebase` library version:**
  - `5.2.2`
- **`Firebase` module(s) you're using that has the issue:**
  - [X] Notifications
- **Are you using `TypeScript`?**
  - [X] no
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] no
- **Do you think this template should be cleaned up?**
  - [x] yes
---

**Comment by mikehardy** [comment]
See discussion here #2076 - not sure if Android badging is ever going to work well

**Comment by brunolemos** [comment]
I’m also not able to get badges to work on either iOS nor Android.

I call `firebase.notifications().setBadge(5)` and nothing happens, not even an error at the console.

My Podfile:

```ruby
platform :ios, '9.0'

target 'devhub' do
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'GoogleIDFASupport'
end
```

My AppDelegate.m:

```obj-c
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTLinkingManager.h>
#import <React/RCTRootView.h>

#import "RNSplashScreen.h"

#import <Firebase.h>
#import "RNFirebaseNotifications.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"devhub"
                                            initialProperties:nil];

  // #1F2229 (dark-gray)
  rootView.backgroundColor = [UIColor colorWithRed:0.12 green:0.13 blue:0.16 alpha:1.0];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [FIRApp configure];
  [RNFirebaseNotifications configure];

  [RNSplashScreen show];

  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"packages/mobile/index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}

- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [[RNFirebaseNotifications instance] didReceiveLocalNotification:notification];
}

@end
```

**Comment by brunolemos** [comment]
^ Nevermind, calling `firebase.messaging().requestPermission()` made it work.

**Comment by Laguigue** [comment]
Hello,

I'm still not able to increment my badge value from mobile side when the app is killed, on IOS. It works on foreground. I only need to increment my value by +1 everytime i receive a remote notification. I never go in my listener (onNotification) when app is closed. Is there any way to do it natively ? Is this even possible with react-native-firebase ?

I have been stuck with this problem for weeks now. I've searched on every sources i could find, still no results.

Thanks a lot for your help

**Comment by mikehardy** [comment]
You might check the PRs, there’s one for iOS that allows for native handling of messages, with some commentary about how the app can’t successfully wake up completely to react-native javascript control flow because of iOS background processing limits. Maybe it is related?

**Comment by arunkmoury** [comment]
@brunolemos interesting !!! can you show the code which you used to set badge

**Comment by ghasemikasra39** [comment]
I cannot find any `setBadge ` or `getBadge` method. When I receive a notif, there is no badge on the app icon.
```
    "@react-native-firebase/app": "^7.1.0",
    "@react-native-firebase/messaging": "^7.1.1",
```

**Comment by mikehardy** [comment]
Badging for iOS is part of local device notification functionality, you'll need a package that handles local device notification APIs in order to handle it I think. For Android it is possible on some devices but runs contrary to the platform UI advice and is in general not recommended

**Comment by ghasemikasra39** [comment]
Dear @mikehardy 
Can I use [this](https://github.com/react-native-community/push-notification-ios) for ios? Is it comparable with the react native firebase cloud messaging (notification) ?

**Comment by mikehardy** [comment]
@ghasemikasra39 the very short answer is I think you can do what you want with that package

But I will be very very clear that you must separate the idea of "cloud messaging" (JSON packets going from the cloud to a device) and "notifications" (things a user can see, APIs on the local device to interact with them etc)

It is true that most cloud messaging libraries contain some code to handle local notifications - even react-native-firebase/messaging v6+ does, and the underlying messaging library will do *some* local notification stuff, but it is only for the most basic use cases.

So the combo of a messaging package and a full featured notification package integrated in your project is the goal. react-native-push-notification can handle both parts depending on your use case. Or you can combine react-native-firebase (for messaging) + react-native-push-notification just for notification API access. Or you can do react-native-firebase/messaging + notifee or react-native-notifications. Lots of options but keep it clear in your mind which part is doing what for when you need help with integration etc
