### ISSUE TITLE
Google Firebase sign out and forget user in Android app

### ISSUE THREAD

**Issue by dhanababum** [invertase/react-native-firebase#1956]
The sign out is not forgetting the google user. Is there any way to forget the user and again show the list?
I did `firebase.auth().signOut()`, But it is not asking google user list when I click on google login button. Could you help me with this?

**Comment by hackrx** [comment]
Hey, @dhanababum I am facing the same issue can you please help me with this.
It is not forgetting the user after log out and when I am clicking on google logIn it is not prompting for google account list. Please help me if you found a solution.

**Comment by mikehardy** [comment]
@hackrx I believe you have to sign out of the underlying auth mechanism as well. For instance if you are using react-native-google-signin, you also need to call GoogleSignin.signOut(). I just tested this in my app and I get the google auth popup again where I can use a different account if I want

**Comment by hackrx** [comment]
Hey @mikehardy  Thanks for the quick reply I am still facing issues
` const logOutHandler = async () => {
    try {
      await GoogleSignin.revokeAccess();
      await GoogleSignin.signOut();
      auth()
        .logOut()
        .then(props.logOut());
    } catch (err) {
      console.log(err);
    }
  };`
This is what I am using to LogOut

**Comment by hackrx** [comment]
Hey @mikehardy  Solved my issue actually I was calling logoutHandler through Onpress
Finally, the issue is resolved thanks for your support.

**Comment by rzfzr** [comment]
GoogleSignin.revokeAccess() should be mentioned in the docs, not giving the option to use another account for login should be the exception

**Comment by mikehardy** [comment]
Hey @rzfzr 👋 - every docs page has an edit button at the top right that takes you through the quick + easy web UI on github to propose a text edit somewhere. We merge all reasonable docs PRs, your suggestion sounds reasonable if you want to post a PR

**Comment by rzfzr** [comment]
Done 👍
