### ISSUE TITLE
how to disable push notifications on device

### ISSUE THREAD

**Issue by tenchoklang** [invertase/react-native-firebase#1957]
How to disable push notifications on device for example when a user logs out of the account. Tried invoking the function returned from `firebase.notifications().onNotification(...)` which in the documentation says that it's used to unsubscribe from notifications, but I am still able to receive push notifications. Again i only want to receive notification when the user is logged in and disable it when the user is logged out. I am generating the device token id by doing `firebase.messaging().getToken();`

**Comment by Worik42** [comment]
+

**Comment by salmanbukharihitori** [comment]
Any updates on  this one pls?

**Comment by mikehardy** [comment]
@salmanbukharihitori this is a closed issue and didn't follow the template anyway. Open a new issue following the template - and for messaging / notifications things please be extremely precise about app status (foreground, background, killed) and platform etc

**Comment by waqaramjad** [comment]
any update ?

**Comment by efstathiosntonas** [comment]
Yes
