### ISSUE TITLE
IOS:: Getting duplicate notification popups for single event using FCM

### ISSUE THREAD

**Issue by archana-iron** [invertase/react-native-firebase#1959]
**Issue Description::** 
I am getting double notification popups inside my app when sending a single notification using FCM. I comes after I am login logout multiple times, or reinstall the app. On first login it works fine, after making these cases again and again, it sends double notification popups for single event.

I am only getting this on IOS devices. I have checked this on IOS: 10, 11, and 12
Why I am getting double popups for single event, is there any method to resolve this.
For IOS I have just installed pod, and added a function to open the notification popup.

```
let notificationHandler = new NotificationsHandler();
this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
	notificationHandler.handleNotification(notificationOpen.notification);
});
```

**Environment::**
Binaries:
      Node: 10.15.0 - /usr/local/opt/node@10/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
npmPackages:
      react: ^16.8.2 => 16.8.3 
      react-native: ^0.58.5 => 0.58.5 
      react-native-firebase: 5.2.3
npmGlobalPackages:
      react-native-cli: 2.0.1

How I can resolve this problem?

**Comment by pmemids** [comment]
I am facing same issue. Any solution you got @archana-iron

**Comment by archana-iron** [comment]
I have not unsubscribe from listener. That was the issue for me.
You have to unsubscribe from your listener when the component will unmount. If you don't do that you are subscribing two listeners.

componentWillUnmount() {
    this.notificationListener(); // it's unsubscribing your listener
}

**Comment by sagarguhe** [comment]
Yes I am also getting duplicate notifications on both android and ios

**Comment by mikehardy** [comment]
This is a closed issue with provided resolution, there will most likely not be further discussion here

**Comment by vipindhangar1107** [comment]
Yes I am also getting duplicate notifications on both android and ios
  "react": "16.8.3",
    "react-native": "0.59.1",
  "react-native-firebase": "5.4.2",

**Comment by vipindhangar1107** [comment]
getting duplicate notifications still now on both ios & android
  "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-firebase": "5.6.0",

**Comment by vipindhangar1107** [comment]
Still struggling with same issue at this time.
"react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-firebase": "5.6.0",

**Comment by pragneshpj** [comment]
can anyone help me to solve this issue in both platform Android, iOS

react-native - 0.61.5
@react-native-firebase/app - ^7.1.4
@react-native-firebase/messaging - ^7.1.6

**Comment by chouaibemir** [comment]
I'm also facing this issue, any updates on this ?
