### ISSUE TITLE
React-native bundle with RNFirebase not found on Android

### ISSUE THREAD

**Issue by niiaou** [invertase/react-native-firebase#1961]
Hello,

I'm having quite a headache recently. 

I'm trying to implement React-Native Firebase Analytics through the React-Native Bundle in my Android Project and when I try to start the ReactActivity I get the following error : 

> RNFirebase core module was not found natively on Android, ensure you have correctly added the RNFirebase and Firebase gradle dependencies to your `android/app/build.gradle` file.

I saw answers about adding these import lines in my MainActivity.java : 

`import io.invertase.firebase.RNFirebasePackage` and `new RNFirebasePackage()`

But I can't add those because, it doesn't even find the code. Even though node_modules folder has the react-native-firebase package.

**Comment by FibreFoX** [comment]
did you add the project via `react-native link` or manually via adding the project to `settings.gradle` and the dependency to the `app/build.gradle`-file?
