### ISSUE TITLE
must initialize fabric before using singleton() in android

### ISSUE THREAD

**Issue by mohitkc71** [invertase/react-native-firebase#1966]
Getting this error while trying to crash in android. IOS is working fine.

**Comment by Salakar** [comment]
@mohitkc71  this and other Crashlytics issues are being addressed in https://github.com/invertase/react-native-firebase/pull/1958 - will close this in favour of that PR.

Thanks

**Comment by adrianha** [comment]
hi @Salakar ,
is it not possible to use Crashlytics on v5?

**Comment by mikehardy** [comment]
@adrianha I use crashlytics successfully on v5 (in android) - I have gotten crash reports with stacks -  and the starter app has it as well
