### ISSUE TITLE
Exception in HostObject

### ISSUE THREAD

**Issue by ArunaMahaGamage** [invertase/react-native-firebase#1969]
i following firebase implementation documentation but application at tun time show this issue. let me know how to fix it . this is my work. https://github.com/ArunaMahaGamage/React_Native_Firebase_Authentication

![Screenshot_20190312-073100](https://user-images.githubusercontent.com/25635071/54169641-927f1d80-4499-11e9-8cd9-8d94780fcde6.png)

**Comment by YazeedAsaad** [comment]
Encountering same issue here after upgrading to 0.59

**Comment by staufman** [comment]
I encountered this same issue and it was because I glazed over a few steps in the setup process. In particular:

In `MainApplication.java`:

```
import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;
```

and then add the following to the `getPackages()` list:

```
new RNFirebaseMessagingPackage(),
new RNFirebaseNotificationsPackage()
```

Finally, in your app `build.gradle`, add the following to your `dependencies`:

```
implementation "com.google.firebase:firebase-messaging:17.3.4"
implementation 'me.leolin:ShortcutBadger:1.1.21@aar'
```

That fixed it for me.

**Comment by Salakar** [comment]
@ArunaMahaGamage looks like you're using an old version of the Firebase Auth Android SDK [here](https://github.com/ArunaMahaGamage/React_Native_Firebase_Authentication/blob/master/android/app/build.gradle#L154) (11.8.0)

This should be `16.1.0` as the [docs indicate](https://rnfirebase.io/docs/v5.x.x/auth/android).

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
