### ISSUE TITLE
Question about transitive = false in build.gradle

### ISSUE THREAD

**Issue by nico1510** [invertase/react-native-firebase#197]
The[ migration guide](http://invertase.io/react-native-firebase/#/migration-guide?id=_4-android-update-appbuildgradle) advises to set `transitive = false` on the react-native-firebase project and then manually add the desired dependencies. But won't this leave out the `me.leolin:ShortcutBadger:1.1.10@aar` dependency which is used in the main project too ? Is this not needed ? 
Maybe one should just use `exclude group: 'com.google.firebase'` instead ?

**Comment by Ehesp** [comment]
cc @chrisbianca

**Comment by Ehesp** [comment]
@nico1510 I think you're right regarding ShortcutBadger. Maybe that would be the better option here. I'll speak internally and see what they say.

**Comment by chrisbianca** [comment]
@nico1510 Good spot, though it's interesting that it doesn't cause any compilation errors when building the project as I'd have expected it to.  You're right that `exclude group: 'com.google.firebase'` should work, though I think we'll need to exclude a couple of others too.

Will give it a try shortly and update the documentation.

**Comment by chrisbianca** [comment]
@nico1510 Sorry for the delay on this one.  Have you experienced any issues with the setup we currently recommend?

What you're saying is definitely correct, but whilst there aren't any compilation errors, I'm loathe to make the change for risk of it opening up a possible can of worms.

If you're not experiencing issues then I'm going to close off this issue until we get reports of problems.

**Comment by nico1510** [comment]
No problem, I'm currently using the `exclude` option but I haven't had compilation problems with tbe `transitive` option neither. I think it's okay to close it for now and keep it in the back of the head.

**Comment by chrisbianca** [comment]
Great, thanks for confirming @nico1510
