### ISSUE TITLE
Error: You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.messaging().

### ISSUE THREAD

**Issue by seongminchoob** [invertase/react-native-firebase#1976]
## Issue

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [X ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [X ] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - XCode 10
- **`React Native 0.58.6
- **`React Native Firebase` library version:5.15.00
  - `ADD_SOMETHING_HERE`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [X ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [X ] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

Everything else in firebase worked fine, however when I try to use fcm, it starts to fail. 

when I try to run it in xcode, I get 

Error: You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.messaging().
Ensure you have the required Firebase iOS SDK pod for this module included in your Podfile, in this instance confirm you've added "pod 'Firebase/Messaging'" to your Podfile

However, I do have   pod 'Firebase/Messaging', '~> 5.15.0' in my cocoapods.
none of the messaging function is working right now

**Comment by BaderSerhan** [comment]
try deleting the pod, running `pod install`, then adding the pod again and installing. re-check if you have followed all of the instructions steps.

**Comment by seongminchoob** [comment]
I tried deleting the podfile, pod.lock, xcspace and all the files and re-ran pod install and pod update but it did not fix.

**Comment by cmmartin** [comment]
What does you Podfile look like?

**Comment by willymulyana** [comment]
I have exactly same issue but without using Pod (download Firebase-5.19.0.zip and follow readme inside it). Something I missed?

**Comment by willymulyana** [comment]
For those who stumble with this issue AND add this module manually (not using Pod), 12 steps (yes not 11, read the thread carefully) in this [thread](https://github.com/invertase/react-native-firebase/issues/1016) is the solution (readme should be updated actually).

**Comment by mikehardy** [comment]
https://github.com/invertase/react-native-firebase/edit/v5.x.x/README.md

:-)
