### ISSUE TITLE
Callable Functions timeout issue

### ISSUE THREAD

**Issue by aliozinan** [invertase/react-native-firebase#1979]
## Issue

:fire:

Callable functions are returning HttpsError: timeout. The reason of the issue is the default 10 seconds limitation of the Java library used for HTTP requests. If a callable function runs over 10 seconds, even it goes on running and completes its job on Firebase server, while the library throws timeout error on the client side. I raised a request to the Google Cloud Team long time ago but it's still not resolved. A workaround solution has been provided below, which could be considered to be implemented : 

[https://stackoverflow.com/questions/50971356/firebase-cloud-functions-change-timeout](https://stackoverflow.com/questions/50971356/firebase-cloud-functions-change-timeout)

---

#### `ios/Podfile`:

- [x] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
N/A
```

#### `AppDelegate.m`:

```objc
N/A
```

---

#### `android/build.gradle`:

```groovy
N/A
```

#### `android/app/build.gradle`:

```groovy
N/A
```

#### `android/settings.gradle`:

```groovy
N/A
```

#### `MainApplication.java`:

```java
N/A
```

#### `AndroidManifest.xml`:

```xml
N/A
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `Android API 21 to 28`
- **Operating System:**
  - [ ] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [x] Other, please specify: `Ubuntu 16.04`
- **Build Tools:**
  - Android Studio 3.3.2
  - buildToolsVersion 28.0.3
  - gradleVersion 4.6
- **`React Native` version:**
  - 0.57.8
- **`React Native Firebase` library version:**
  - 5.2.1
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [x] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: N/A

**Comment by aliozinan** [comment]
**Update**

firebase-functions version 16.3.0, released 15 Mar 2019, adds the ability to configure the timeout.

[https://firebase.google.com/docs/reference/android/com/google/firebase/functions/HttpsCallableReference](https://firebase.google.com/docs/reference/android/com/google/firebase/functions/HttpsCallableReference)

Looks like the Google Team came up with a solution and set the default timeout to 60 seconds for callable functions. I'll be sharing the test results here.

**Comment by bitfabrikken** [comment]
@aliozinan any news? I'm also stuck with the 10 second timeout here and am wondering if you learned something new?

**Comment by bsendras** [comment]
Here is a workaround for this issue. Since the limitation is within the library for HTTP requests used by react-native-firebase, we tried to use another one. So instead of use functions().httpsCallable(), we decided to call the function with a http client like axios.

We were concerned about authentication, because if you call the function in this way, the function won't receive the context object. Hopefully, firebase automaticaly validates a bearer token that you can provide in the [Authorization](https://firebase.google.com/docs/functions/callable-reference) header

Here's my example
```javascript
import { auth } from 'react-native-firebase';
import axios from 'axios';

const token = await auth().currentUser.getIdToken();
axios.post(
    '<Your Firebase Cloud Function URL>',
    {
      data: { 'parameters of the function' }
    },
    {
      headers: {
        'Content-Type': 'application/json',
        // This will be automatically validated in the server
        Authorization: `Bearer ${token}`
      },
      transformResponse: [
        response => {
          const res = JSON.parse(response);
          // unwrap the object returned by the function
          return res.result;
        }
      ]
    }
  );
```

Hope it helps!

**Comment by aliozinan** [comment]
It seems like with the Google's update I mentioned above must be implemented on react-native-firebase side as well. Now that there's the timeout parameter available for HttpsCallableReference, the team can do something about it I guess?

**Comment by mikehardy** [comment]
@aliozinan PRs are welcome if you’d like to propose one

**Comment by mikehardy** [comment]
it does seem valid to re-open this one as no longer blocked though?

**Comment by aliozinan** [comment]
> @aliozinan PRs are welcome if you’d like to propose one

I would love to, if I knew how to code Java

> it does seem valid to re-open this one as no longer blocked though?

Yes this issue is still unresolved and needs to be re-opened.
