### ISSUE TITLE
🔥firebase.messaging().ios.getAPNSToken() always returns null

### ISSUE THREAD

**Issue by naorzr** [invertase/react-native-firebase#1990]
## Issue

On the server side we are using amazon sns service for the fcm communication with the devices, so the token returned from 
``` firebase.messaging().getToken() ```
is just too long.
So we've figured we should get the token with getAPNStoken call
``` 
import firebase from 'react-native-firebase'

const token = await firebase.messaging().ios.getAPNSToken() // null
```
only that this call returns null no matter what I try, the documentation isn't very clear about how to use and use cases, but I guess that it should be inferred from the name.
anyhow, I've also tried to register first using
```
firebase.messaging().ios.registerForRemoteNotifications().then(() => 
const token = firebase.messaging().ios.getAPNSToken()) // null
```
still no success.
Am I doing something wrong, or is that a bug?
---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

require_relative '../node_modules/@unimodules/core/podfile-macro'

# The target name is most likely the name of your project.
target 'broadcaster' do

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    'RCTImage'
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'EXFont', path: '../node_modules/expo-font/ios'
  pod 'EXImagePicker', path: '../node_modules/expo-image-picker/ios'
  pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker/react-native-orientation-locker.podspec'
  pod 'EXAV', path: '../node_modules/expo-av/ios'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  use_unimodules!


end

```

#### `AppDelegate.m`:

```objc
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <EXCore/EXModuleRegistry.h>
#import <EXReactNativeAdapter/EXNativeModulesProxy.h>
#import <EXReactNativeAdapter/EXModuleRegistryAdapter.h>
#import "Orientation.h"
#import <Firebase.h>
#import "RNFirebaseNotifications.h"
#import "RNFirebaseMessaging.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  [RNFirebaseNotifications configure];
  self.moduleRegistryAdapter = [[EXModuleRegistryAdapter alloc] initWithModuleRegistryProvider:[[EXModuleRegistryProvider alloc] init]];
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"broadcaster" initialProperties:nil];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [[RNFirebaseNotifications instance] didReceiveLocalNotification:notification];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
  [[RNFirebaseMessaging instance] didRegisterUserNotificationSettings:notificationSettings];
}

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
  NSArray<id<RCTBridgeModule>> *extraModules = [_moduleRegistryAdapter extraModulesForBridge:bridge andExperience:nil];
  // If you'd like to export some custom RCTBridgeModules that are not Expo modules, add them here!
  return extraModules;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
}

- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
  return [Orientation getOrientation];
}

@end
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - Xcode 10
- **`React Native` version:**
  - `0.57.3`
- **`React Native Firebase` library version: 
  - `5.2.3`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [x] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [ ] No
  - [x] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [ ] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [x] Yes, but I **have** ejected to vanilla React Native

**Comment by nigel-smk** [comment]
I have seen the same issue. I was able to get the APNs token only on first launch though.

**Comment by naorzr** [comment]
@nigel-smk the first launch of the app? cause I didn't managed to even make that happen

**Comment by nigel-smk** [comment]
@naorzr I think I have solved this.

I found this issue for a competing library that had [the same issue](https://github.com/evollu/react-native-fcm/issues/510) 

I don't understand it entirely but it seems that we need to registerForRemoteNotifications first.

The `react-native-firebase` messaging reference docs are [currently broken](https://rnfirebase.io/docs/v5.x.x/messaging/reference/messaging). But if we dig into the [docs in the repo](https://github.com/invertase/react-native-firebase-docs/blob/master/docs/messaging/reference/IOSMessaging.md) we find that `react-native-firebase` has the `registerForRemoteNotifications` method as well.

This reliably got me the APNs Token:
```
    firebase.messaging().ios.registerForRemoteNotifications().then(() => {
      firebase.messaging().ios.getAPNSToken().then(token => {
        // token not null
      });
    })
```
While this did not:
```
    firebase.messaging().ios.getAPNSToken().then(token => {
      // token always null
    });
```

**Comment by nigel-smk** [comment]
Based on my reading of the solution to https://github.com/evollu/react-native-fcm/issues/510 I think that this issue is a bug with react-native-firebase

**Comment by naorzr** [comment]
@nigel-smk thanks for taking your time with the comment
though I have done it, and still getting null..
is the token not being null behaviour persistent for you?

**Comment by nigel-smk** [comment]
Are you using a real device? The simulator [will never get and APNs token](https://rnfirebase.io/docs/v5.x.x/messaging/ios)

When running on a real device I get the above described behaviour every time. I have switched between the two appraoches 3-4 times now and without the register call I always get null.

**Comment by naorzr** [comment]
@nigel-smk yea I am

**Comment by naorzr** [comment]
@nigel-smk any chance you could please post here your AppDelegate.m and Podfile?
Can't get this to work no matter what, reinstalled and refollowed the tutorials over and over.

**Comment by naorzr** [comment]
well in the end i've reinstalled, reconfiged everything from scratch and it was resolved.

**Comment by evanjmg** [comment]
I'm having the same issue

**Comment by luatvudinh** [comment]
Add this function to AppDelegate.m:
```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [FIRMessaging messaging].APNSToken = deviceToken;
}
```
Hope this will be helpful.

**Comment by ivangr1** [comment]
I was having the same issue for days and nothing from the above helped, but I got it working myself.
I just added this to `didFinishLaunchingWithOptions` method in `AppDelegate.m`:

`[[UIApplication sharedApplication] registerForRemoteNotifications];`

**Comment by dusan-dragon** [comment]
This is kind of strange, but for me this was behavior:

```

**Comment by Jcbgid** [comment]
I've tried everything here (setting everything up from scratch based on `react-native-firebase` docs, AppDelegate.m additions, request permission immediately before getting token, registering for remote notifications immediately before getting token, etc.) and am still running into this issue. 

Firebase gets FCM tokens just fine, but always returns a `null` APNS token.

Any other potential fixes?

**Comment by alipetarian** [comment]
This helped me get the APNS token:

      firebase
        .messaging()
        .ios.registerForRemoteNotifications()
        .then(() => {
          console.log('REGISTER FOR REMOTE NOTIFICATIONS');

          firebase
            .messaging()
            .ios.getAPNSToken()
            .then(token => {
              console.log(
                'APNS TOKEN AFTER REGISTRATION FOR BACKGROUND',
                token,
              );
            });
        });

**Comment by luatnd** [comment]
In my case, calling ios.registerForRemoteNotifications() in release build:
```
firebase.messaging().ios.registerForRemoteNotifications().then(() => {
     firebase.messaging().ios.getAPNSToken().then((apnsToken) => {
              console.log(apnsToken)
      })
})
```
apnsToken sometime null, is this normal behavior?

**Comment by MinskLeo** [comment]
> I was having the same issue for days and nothing from the above helped, but I got it working myself.
> I just added this to `didFinishLaunchingWithOptions` method in `AppDelegate.m`:
> 
> `[[UIApplication sharedApplication] registerForRemoteNotifications];`

This really helped me! Thank you so much buddy!

**Comment by mifi** [comment]
Even using `registerForRemoteNotifications` before calling `getAPNSToken` I get null the first time the app launches. Then when calling `getAPNSToken` later, it correctly returns the token.
```js
    await firebase.messaging().ios.registerForRemoteNotifications();
    const apnsToken = await firebase.messaging().ios.getAPNSToken();
    apnsToken === null
```

I'm suspecting that the promise returned from `registerForRemoteNotifications` does not wait for the token to be registered before resolving, so I don't know why it's returning a promise at all.

**Comment by mifi** [comment]
Although very hacky, this seems to work and will never return null:

```js
async function getAPNSToken() {
  while (true) {
    await new Promise((resolve) => setTimeout(resolve, 1000));
    const apnsToken = await firebase.messaging().ios.getAPNSToken();
    if (apnsToken !== null) return apnsToken;
  }
}

 await firebase.messaging().ios.registerForRemoteNotifications();
 const apnsToken = await getAPNSToken();
```

**Comment by ridawidchlodnicki** [comment]
> Add this function to AppDelegate.m:
> 
> ```
> - (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
>   [FIRMessaging messaging].APNSToken = deviceToken;
> }
> ```
> 
> Hope this will be helpful.

Many thanks, you saved my day!

**Comment by idylmz** [comment]
> I was having the same issue for days and nothing from the above helped, but I got it working myself. I just added this to `didFinishLaunchingWithOptions` method in `AppDelegate.m`:
> 
> `[[UIApplication sharedApplication] registerForRemoteNotifications];`

I have no idea why, but this also solved my issue. The strange thing is, I did not changed anything in my project. But I believe it happened right after I implemented react-native-splash-screen.

My AppDelegate file was changed from this
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  self.moduleName = @"Gardrows";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
```

To this after RN Splash Screen:
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  self.moduleName = @"Gardrows";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};
  bool didFinish = [super application:application didFinishLaunchingWithOptions:launchOptions];
  [RNSplashScreen show];
  return didFinish;
}
```

I believe somehow I messed with Firebase initial configuration by changing return of the function even though the type and value checks out.

Now the successful solution of the AppDelegate goes like:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  [[UIApplication sharedApplication] registerForRemoteNotifications];
  self.moduleName = @"Gardrows";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};
  bool didFinish = [super application:application didFinishLaunchingWithOptions:launchOptions];
  [RNSplashScreen show];
  return didFinish;
}
```
