### ISSUE TITLE
🔥signInWithCredential() uncaught NSInvalidArgumentException

### ISSUE THREAD

**Issue by j-cheung** [invertase/react-native-firebase#1993]
## Issue

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Mellow' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
    'RCTImage'
  ]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Pods for ----
   pod 'Firebase'
   pod 'Firebase/Core', '~> 5.15.0'
   pod 'Firebase/Auth', '~> 5.15.0'
   pod 'Firebase/Messaging'

end
```

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [x] MacOS, version: 10.14
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `ADD_SOMETHING_HERE` e.g. Xcode 10, Android Studio 3.2
- **`React Native` version:**
  - `ADD_SOMETHING_HERE`
- **`React Native Firebase` library version:**
  - `ADD_SOMETHING_HERE`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [x] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [ ] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Hi, 

I'm trying to use react-native-firebase and starting off with authentication, but when trying to call signInWithCredential(), I experienced this uncaught exception, and the .catch() or try/catch blocks are not catching them in JS.

`
firebaseAuth = userId => {
    try{
      firebase.auth().signInWithCredential(userId).then(data => console.warn(data)).catch(function(error){ console.warn(error)})
    } catch(err) {
      console.warn(err)
    }
  };
`

<img width="611" alt="Screenshot 2019-03-20 at 13 01 08" src="https://user-images.githubusercontent.com/10898809/54660168-3eff7600-4b10-11e9-99f5-48fc98fabac0.png">

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by calintamasyopeso** [comment]
Just ran into the same thing with `firebase.auth().signInAnonymously()`. 

Commented out the method call, ran the app -> working.
Put it back in, rand the app -> working?!

**Comment by calintamasyopeso** [comment]
Running into something similar with `firebase.auth().signInAnonymously()`.

![H8seXYgA](https://user-images.githubusercontent.com/40857863/54826607-c8ea4300-4cb8-11e9-8d38-c8bec36ffed2.png)

**Comment by eliabiraschi** [comment]
I'm experiencing the same on both Android and iOS.

**Comment by eliabiraschi** [comment]
I've changed the `signInWithCredential` method in `node_modules/react-native-firebase/dist/modules/auth/index.js` to handle the promise rejection like this:
```
signInWithCredential(credential) {
    return getNativeModule(this)
      .signInWithCredential(credential.providerId, credential.token, credential.secret)
      .then(
        userCredential => this._setUserCredential(userCredential),
        error => Promise.reject(error) // <-- I've just added this ugliness
      );
  }
```
and it _fixed_ the issue allowing me to catch and handle the exceptions at the right link of the promises chain as expected (at least on Android - I haven't tested on iOS).
The issue might be related to this one https://github.com/facebook/react-native/issues/20262

**Comment by Salakar** [comment]
Closing issue as it has since been resolved in later RN versions.
