### ISSUE TITLE
[Cloud Storage] - Metadata using MD5 cryptography

### ISSUE THREAD

**Issue by renatobenks** [invertase/react-native-firebase#1999]
## Issue

Hey guys, we have a question about the use of md5 cryptography to build a hash to metadata into the bridge of cloud storage.

https://github.com/invertase/react-native-firebase/blob/f3e0d06608f6c8a2d971f48e11be8cd9c20dd5e5/android/src/main/java/io/invertase/firebase/storage/RNFirebaseStorage.java#L559

Our security team has been worried about the use of md5 as a type of cryptography. So, we need to know why was used the md5 and why not, and maybe, propose a new type of cryptography to be used on.

Usually, we need to know what it's the reason behind the md5 uses.

---

## Project Files

- Android: `android/src/main/java/io/invertase/firebase/storage/RNFirebaseStorage.java` https://github.com/invertase/react-native-firebase/blob/f3e0d06608f6c8a2d971f48e11be8cd9c20dd5e5/android/src/main/java/io/invertase/firebase/storage/RNFirebaseStorage.java#L559

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Operating System:**
  - [x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **`React Native` version:** 0.55.4
- **`React Native Firebase` library version:** 4.3.8
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [ ] Authentication
  - [x] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by Salakar** [comment]
@renatobenks MD5 behaviour comes from the Firebase SDKs directly and not in our control.

Unless you're specifically using the MD5 values yourself for something then there's nothing to be concerned with.

If you need your own hash, then I'd suggest adding a Cloud Function that calculates this on file upload with your hashing algorithm of choice, but as I said above, not needed if you're not using it.

Thanks
