### ISSUE TITLE
error : [!] No `Podfile' found in the project directory.

### ISSUE THREAD

**Issue by jasan-s** [invertase/react-native-firebase#2]
After I run pod update --verbose

**Comment by Salakar** [comment]
@jasan-s hello, this is not yet deployed yet on npm, the one on npm is from the previous owner of the npm name. Hoping to get it up soon, just sorting a few more tests out.

Feel free to npm install from the git repo instead:
```
npm i https://github.com/invertase/react-native-firebase
```

**Comment by jasan-s** [comment]
thanks. may i ask How is that project different from Firestack?

**Comment by Ehesp** [comment]
We're currently having trouble managing the firestack repo as we don't own
it. There's also lots of issues which have been fixed but would conflict
heavily with firestack.

For now install from the fork using the git path.

**Comment by IljaDaderko** [comment]
Do you guys have public road map / tasks left to do that could give an idea about how ready the repo is for the release and potentially expose tasks that we could pick up and pr in order to help?

**Comment by Ehesp** [comment]
Yeah sure we'll pick it up tomorrow. We are using @Salakars firestack fork
in production at the moment, however it's not ideal.

We're not the strongest with Objective C unfortunately so @chrisbianca is
picking that side up at the moment.

**Comment by Salakar** [comment]
This has been deployed now, closing.
