### ISSUE TITLE
Email verification only updates after clearing cache/app data

### ISSUE THREAD

**Issue by Ehesp** [invertase/react-native-firebase#20]
When creating an account and sending an email verification, after verifying the email address I can only get the `emailVerified` prop from `onAuthStateChanged` to return true after clearing the app data and logging in again.

Only tested on Android at the moment.

**Comment by Ehesp** [comment]
Also calling `auth().currentUser.reload()` has no impact.

**Comment by Salakar** [comment]
Definitely a firebase issue, need to try this on ios also, think it's just android with the problem.

**Comment by Ehesp** [comment]
Yep seems so: https://groups.google.com/forum/#!topic/firebase-talk/hd6ZtwfDeyQ

**Comment by IljaDaderko** [comment]
There is a sollution to this

```
await auth.currentUser.reload()
auth.currentUser.getToken(true)
```

performing both of these will trigger onAuthStateChanged with updated email without sign out. Only drawback is this won't happen automatically, so you need to provide some sort of screen that asks user to verify their email and has `Continue` or some other call to action to do this refresh.

What I did is just deep link verification link into email and trigger those functions, that way it works as expected. @Ehesp

**Comment by Ehesp** [comment]
@IljaDaderko sounds good will give it a try!

When the user registers I do an Alert with an OK action so I'll give it a go in there (and then on app reloads if it's still false). Could you explain/show a bit more on the deep linking? Not actually tried that yet.

**Comment by IljaDaderko** [comment]
@Ehesp I use firebase's [Dynamic links](https://firebase.google.com/docs/dynamic-links) for this. Essentially you need to set up email verification to go to your custom page, where you then retrieve verification token and pass it to firebase manually, after this you can redirect to url that is set up in firebase as dynamic link, once app opens this url you can preform that token refresh automatically.

I haven't done this myself but even better approach would be to have email verification link go straight into the app and validate user's token in there.

On react native side, you'll be handling these as per following doc https://facebook.github.io/react-native/docs/linking.html#handling-deep-links

**Comment by Salakar** [comment]
@Ehesp @IljaDaderko I could potentially add a native method that runs both reload and getToken(true) for this if needed? Something along the lines of `hardRefresh`?

**Comment by IljaDaderko** [comment]
@Salakar personally, I'd stick to calling these two methods as is, so you guys can keep your repo as close to firebase as possible.

**Comment by Salakar** [comment]
@Ehesp @IljaDaderko in that case can I close this issue? Not much else I can do as its a firebase issue 🙈

**Comment by jasan-s** [comment]
@iljadaderko @Ehesp  **just for clarification  Ideally I want this to happen:** 

1.  I send a verification email to user, 
2. User open my custom page and verifies email.
3. Then there is a dynamic link there that send the user to a screen in my app
4. When this screen mounts in my app I calls the the two methods:

```
await auth.currentUser.reload()
auth.currentUser.getToken(true)
```
5. Then this would trigger the onAuthStateChanged function.

But If the User decides to instead close the browser(ignoring the dynamic link) and launch my app again. I should keep track that previously verification email was sent, thus take the user to a screen (which shows whenever email is not verified and email has been sent).   Upon this Screen mounting I ask User if they already verified their email , is so do some action. At this action run the above 2 methods?

**Comment by jasan-s** [comment]
I tried the above solution yet I get the error below whenever I just login or signup a user: 

` TypeError: Cannot read property 'reload' of null
    at reloadUserAndGetToken$ (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:61924:78)
    at tryCatch (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:16868:40)
    at Generator.invoke [as _invoke] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:17056:22)`

After refresh with a user logged in the solution works.

**Comment by Vaibhavmarch98** [comment]
I faced the same prblm
soln
make a button-> on click-> reload
ask the user to verify after the user has been verfied
in reload do not run .reload() its not working
but manually sign in and sign out

**Comment by tkow** [comment]
Same to me.  And getToken method may be currently removed.
Is there an alternative way?

**Comment by mikehardy** [comment]
@tkow you have added a comment to a closed issue almost a year old, open a fresh issue with full information. I suspect this may be a need to update all the dependencies, because I have integrated firebase recently with current dependencies and this does not happen to me - I was able to use the sample code in the auth docs on rnfirebase.io and everything is fine.
