### ISSUE TITLE
Typescript definitions not found (v. ^5.2.3)

### ISSUE THREAD

**Issue by 7arsandre** [invertase/react-native-firebase#2000]
```
{
  "compilerOptions": {  
    "target": "es5",
    ...
  },
  "files": ["./src/index.d.ts"]
}
```

` "files": ["./src/index.d.ts"]` yields error because it's the wrong path. 

<img width="266" alt="Screenshot 2019-03-23 at 13 36 47" src="https://user-images.githubusercontent.com/20848327/54866185-1e822680-4d71-11e9-8469-aa4ea35598c3.png">

As you could see from the image above the path should be `./dist/index.d.ts`

**Comment by lpetkov-sw** [comment]
Hi, I can confirm that I have the same issue.
![image](https://user-images.githubusercontent.com/26001304/67461748-c2ed8380-f646-11e9-8913-c080ba2b96c8.png)
