### ISSUE TITLE
not able to recieve push notification on ios device

### ISSUE THREAD

**Issue by yusuf987** [invertase/react-native-firebase#2001]
package.json
```
 "react": "16.3.1",
  "react-native": "0.55.1",
  "react-native-firebase": "^5.0.0",

```
pod file

```
platform :ios, '9.0'

target 'XYZ' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging'
  # Pods for XYZ
```
I am implementing react-native-firebase to my app i have followed steps from official document(https://rnfirebase.io/docs/v5.x.x/installation/ios) as well as some other similar blogs (https://medium.com/@anum.amin/react-native-integrating-push-notifications-using-fcm-349fff071591),

but I am not able to receive any notification on my real device,

I followed all steps excepts generating key's, ID, and provisioning as I had already these while publishing my app

i have tried to send a notification from firebase console like below 
![image](https://user-images.githubusercontent.com/24749530/54867030-d7605980-4da1-11e9-9992-76d7149de341.png)

and from postman

Screen Shot 2019-03-23 at 6.53.33 PM
![image](https://user-images.githubusercontent.com/24749530/54867032-db8c7700-4da1-11e9-8fe6-7753662a65d0.png)

it shows succeed but no notification on the real device

I have tried some solutions like changing **search header path** and **link binary with library** but nothing worked

my distribution provisining profile showing expire but I am able to publish my app so i am assuming this would not be an issue enter image description here
![image](https://user-images.githubusercontent.com/24749530/54867052-07a7f800-4da2-11e9-90db-d9d4bca2d229.png)

I am expecting to just receive my first push notification I am struggling from last three days please help.

thank you

**Comment by vsamotskiy** [comment]
In my case APNs key was not added to ios application in firebase project. Try https://firebase.google.com/docs/cloud-messaging/ios/client#upload_your_apns_authentication_key

**Comment by evanjmg** [comment]
I get null when fetching the APNS token with FB.messaging().ios.getAPNSToken()- this is after registering too. I am migrating a swift app to react native with the same FB version 5.18.0. If I download the app from scratch everything works.

**Comment by skoob13** [comment]
I had the same issue. It looks like the order of calls matters. E.g. when I use the following code, APN token is always null:

```javascript
runFlow = async () => {
  const enabled = await firebase.messaging().hasPermission();

  if (enabled) {
    try {
      const fcmToken = await firebase.messaging().getToken();
      if (fcmToken) {
        this.props.registerToken({
          device_token: fcmToken,
        });
      }
    } catch (e) {
      console.log(e);
    }
  }
}
```

However, if I add a line, that requests permissions, it works as expected:

```javascript
runFlow = async () => {
  await firebase.messaging().requestPermission(); // Here
  const enabled = await firebase.messaging().hasPermission();

  if (enabled) {
    try {
      const fcmToken = await firebase.messaging().getToken();
      if (fcmToken) {
        this.props.registerToken({
          device_token: fcmToken,
        });
      }
    } catch (e) {
      console.log(e);
    }
  }
}
```

I didn't request permissions since we were assuming that a user allowed to receive push notifications previously. Hope it helps.

**Comment by mikehardy** [comment]
I have observed with tokens that there is latency. It is an asynchronous network call to generate the token, and it happens outside the app in the Google libraries. In testing, I have to add semi-large (5 seconds) sleeps before I can guarantee token requests will reliably deliver the expected results. For the end-to-end tests that are part of CI in this project, when I run them locally I didn't have 100% success until I added a 10s sleep. That's network-dependent but keep it in mind.

If this is not a problem for anyone anymore *after taking latency into account*, then we should close this. iOS push notifications definitely work, though they are difficult to do well in general (not specific to this library)

**Comment by mikehardy** [comment]
push notifications definitely work, so I'm closing this - but it is easy to get them wrong. Follow the troubleshooting blog posts from firebase blog, make sure you wait and re-try if the token is null (there is latency if it has to get a new one) etc etc.
