### ISSUE TITLE
👩‍💻 Work With Us - Link Broken

### ISSUE THREAD

**Issue by jonas-arkulpa** [invertase/react-native-firebase#2005]
## Documentation Feedback
The »👩‍💻 Work With Us« link at the end of the readme is broken.
https://invertase.io/jobs is not available anymore.
Haven't found an alternativ for a PR.
https://github.com/invertase/react-native-firebase/blob/master/README.md#license

**Comment by Salakar** [comment]
Hey @jonas-arkulpa thanks for letting us know. @Ehesp is working on updating the sites and all the broken links on Readmes etc - hopefully, we'll have this sorted soon.

If you want to [get in touch](https://github.com/invertase/react-native-firebase/blob/master/CONTRIBUTING.md#what-about-if-you-have-problems-that-cannot-be-discussed-in-a-public-issue) though feel free to do so 💯
