### ISSUE TITLE
NativeModules.RNFirebase returns UNDEFINED

### ISSUE THREAD

**Issue by barjas** [invertase/react-native-firebase#201]
after installation, i run the app and i get the following red screen error:
cannot read property 'googleAPIAvailability' of undefined 
i tracked the issue and found that 
`const FirebaseModule = NativeModules.RNFirebase;` IN "**node_modules/react-native-firebase/lib/firebase.js**" is returning "**undefined**"

any help please ?

My RN is v0.44

**Comment by Ehesp** [comment]
You haven't installed the library properly. Please follow the instructions and if you need more help show us your build.gradle files and MainActivity.

**Comment by barjas** [comment]
thanks for the quick reply,

i followed the installation steps step by step, 
i\m on iOS, which files would u like for me to share ?

**Comment by simpleblack** [comment]
I has been screen error too.

![image](https://user-images.githubusercontent.com/5565272/27484499-6a76d760-5864-11e7-96f8-67f92411dce6.png | width=300)

My RN is v.0.44 and 
I used it podfile this [https://github.com/invertase/react-native-firebase-examples/blob/master/ios/Podfile
](https://github.com/invertase/react-native-firebase-examples/blob/master/ios/Podfile)

**Comment by barjas** [comment]
i deleted the **build** folder in the ios and ran "react-native run-ios" again and all worked fine ! 
i guess something was not getting updated in the build

**Comment by simpleblack** [comment]
@barjas 
I deleted the build and `run-ios` 
but i get next error 

`Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

You don't get error?

**Comment by barjas** [comment]
this is not related to firebase at all
try clear cache , or run with sudo, ...or check this page, https://github.com/facebook/react-native/issues/7308

**Comment by simpleblack** [comment]
@barjas thank you.
I will try.

**Comment by simpleblack** [comment]
@barjas
I tried every method
catch clear, sudo, re make file etc...
but I get all error `":CFBundleIdentifier", Does Not Exist`

my test.
1. create react-native => success
2. change BundleIdentifier => success || not change BundleIdentifier => success
3. MyGame.xcworkspace indexing => success
4. I followed the installation for IOS => fail('googleAPIAvailability' of undefined error)
5. delete (APP_ROOT_FOLDER/ios/build/) and `run-ios` => fail(CFBundleIdentifier error)

I guess something `pod init`, `pod install` after get error
Could you share used podfile?

Thank you.

**Comment by lehainam125** [comment]
My app run is fine. But when I run "jest" (test app), the error raises. I tried to remove `build` folder and rerun `react-native run-android`, the result is still same. Can you take a look?

![image](https://user-images.githubusercontent.com/12379457/27950142-5ff31f9e-632a-11e7-925b-387a6c8d5654.png)

**Comment by Ehesp** [comment]
@lehainam125 is this related? https://github.com/invertase/react-native-firebase/issues/215

**Comment by lehainam125** [comment]
@Ehesp No, I don't think it's related. I've tried to add `compile "com.google.android.gms:play-services-base:11.0.0"` to my `build.gradle`, the error still appear.

**Comment by Ehesp** [comment]
@lehainam125 Okay I'll take a look. https://github.com/invertase/react-native-firebase/issues/162 might be worth checking too.

**Comment by rightaboveit** [comment]
I have the same issue that @barjas had. RN 0.43.3

Tried deleting ios/build/ as well as ios/build/Build, and both result in the error that @simpleblack was having. 

There seems to be no information anywhere about this "cannot read property 'googleAPIAvailability of undefined".

**Comment by connercms** [comment]
Also getting error 'TypeError: Cannot read property 'googleApiAvailability' of undefined' when running npm test. Error occurs on this line
`const firebase = RNFirebase.initializeApp`
Deleting build folder and running react-native run-android again then npm test still doesn't work.

**Comment by johngoren** [comment]
Same issue here as @lehainam125. Works great in the app, throws this error in Jest.

**Comment by nanduahmed** [comment]
Same issue I have observed 

![image](https://user-images.githubusercontent.com/2088754/29344940-37ee868e-81f0-11e7-974b-1b30d5138325.png)

**Comment by PoojaVM** [comment]
Getting NativeModules.RNFirebase undefined. Pretty sure I have followed all the steps suggested at here
https://github.com/evollu/react-native-fcm
Have linked library both manually and using rnpm link.
Still getting the issue

**Comment by RicardoBer** [comment]
Me too,

I use react-native-jitsi-meet library in conjuntion with this, and this problem raised.

I detailed the issue for test here [`https://github.com/skrafft/react-native-jitsi-meet/issues/18`](https://github.com/skrafft/react-native-jitsi-meet/issues/18)

**Comment by saadqbal** [comment]
@RicardoBer did you find any solution for this?

**Comment by RicardoBer** [comment]
I can make it work after many weeks, it's no joke, many weeks. After make a lot of changes on many code places and change xcode config, but I can't reproduce the solution.

I can build and make the app works but I can't make it again. The project is ended (lost money and time with it) and I can't make more test, Sorry.

The only conclusion I have is that it is not related to firebase problem, it is related to xcode and react native problem, but arrise on extrange sites.

Sorry, if I have more time to test and find the solution I publish it here.
