### ISSUE TITLE
🔥 Interstitials only work once

### ISSUE THREAD

**Issue by erandagan** [invertase/react-native-firebase#2013]
## Issue
**The Problem**
Different interstitials created with the same ad unit ID can't be shown in a single session.

For example, in the below snippet, attempting to display the `secondAd` will never work:

```js
const demo = () => {
  const ad = firebase.admob().interstitial(adUnitId);
  const request = new firebase.admob.AdRequest();

  ad.loadAd(request.build());

  // later on...
  ad.show(); // Works fine

  // later on...
  const secondAd = firebase.admob().interstitial(adUnitId);
  const secondRequest = new firebase.admob.AdRequest();
  secondAd.loadAd(secondRequest.build()); // will never load
  
  secondAd.on('onAdLoaded', () => {} ) // callback never called
  secondAd.on('onAdFailedToLoad', () => {} ) // callback never called

  // Won't work:
  secondAd.show();
};
```

**The Cause**
Firebase's `InterstitialAd` object is meant to be used **once**. If you wish to display multiple interstitials during a single session, you may do so by creating separate `InterstitialAd` instances.

[RNFirebase maintains a cache between an ad unit ID and the `InterstitialAd` instance](https://github.com/invertase/react-native-firebase/blob/93ec908f03d719c03e8445f9654fb2712769c3d7/android/src/main/java/io/invertase/firebase/admob/RNFirebaseAdMob.java#L21) bound to it. This means that, in the above snippet, both `ad` and `secondAd` referenced the same native `InterstitialAd` object, which is why `secondAd` doesn't work correctly.

---

## Project Files
(Irrelevant)

## Environment
- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `android 26` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Android Studio 3.2, Xcode 10`
- **`React Native` version:**
  - `0.59.1`
- **`React Native Firebase` library version:**
  - `5.2.3`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [ ] No
  - [x] Yes, version: `3.2.2`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`
---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by erandagan** [comment]
Opened by accident while filling the template, will reopen once I finish debugging this to provide some extra context.

**Comment by rochapablo** [comment]
For me it's not working at all on Android (iOS works fine).

```
"react": "16.8.6",
"react-native": "^0.59.8",
"react-native-firebase": "^5.3.1",
```

**Comment by nvtamcntt** [comment]
I happy with this code 
`
let advert = firebase.admob().interstitial(interstitialId)

export const interstitialRequest = () => {
    const { AdRequest } = firebase.admob
    const request = new AdRequest()
    request.addKeyword('mazi')
    request.addKeyword('JLPT')
    request.addKeyword('tung vung')
    request.addKeyword('tieng nhat')
    
    // Load the advert with our AdRequest
    advert.loadAd(request.build())

    advert.on('onAdClosed', () => {
      console.log('show admob =====>>> onAdClosed ....')
      advert = firebase.admob().interstitial(interstitialId)
      interstitialRequest() 
    })
}

// advert.on('onAdLoaded', () => {
//   console.log('Advert ready to show.')
// })

export const showInterstitial = () => {
  console.log("show admob =====>>> click..")
    if (advert.isLoaded()) {
      console.log("show admob =====>>> action show")
        advert.show()
      }
}`
