### ISSUE TITLE
Firestore offline performance

### ISSUE THREAD

**Issue by agrass** [invertase/react-native-firebase#2019]
Hello, 
Firestore offline Queries are taking too much time, around 8-12 seconds. Any recommendation??  May be is the timeout with the connection??  It's a small 
query and small database, only 20kb the whole database. I'm using Android with react-native 
and react-native-firebase with Android SDK version 
firebase-firestore:17.0.2 . 

Thanks

**Comment by mgenov** [comment]
We experiencing similar performance issue (small and large collections). The things that It may be tried is library dependencies to firestore-firestore to be updated to 18.0.1+.

This is what I see in the changelog:
![image](https://user-images.githubusercontent.com/209223/55509392-994a1c00-5664-11e9-9187-ffa4374c8fc5.png)

I suppose this could speed things up but the librayr needs to update it's dependencies to the sdk of firestore.

**Comment by agrass** [comment]
Cool! Thanks for the info @mgenov,  Let me know if that works for you. I'm going to try it as well. 

 I reported to Google Support team and they told me to try the same query without react-native-firebase library, to check if is a problem of firestore library or the implementation for RN.

**Comment by mgenov** [comment]
It's easy to be checked. Just add few logs in the native code of java and you will see how much time it takes for the SDK to process it.

I'm not sure but I think that JS API of react-native-firebase and the latest SDK are not fully compatible and it may require some minor tweaks to be performed for it. Would be nice if you can share the results.

**Comment by agrass** [comment]
v18 not currently supported with RN-firebase so I can't test it. I get the error `Could not invoke RNFirebaseFirestore.documentSet`

**Comment by Salakar** [comment]
Attempting the upgrade today for v5.3.0 release. Will respond back on progress.

Thanks

**Comment by Ehesp** [comment]
5.3.0 is out, please see the release notes on how to upgrade: https://rnfirebase.io/docs/v5.x.x/releases/v5.3.x
