### ISSUE TITLE
Event Property Data not shown in Firebase

### ISSUE THREAD

**Issue by mxmtsk** [invertase/react-native-firebase#202]
Hey,

I'm logging events the following way:

```
firebase.analytics().logEvent('thesis_answered', {
      id,
      title: question.title,
      thesis: question.thesis,
      answer: 2,
      timeElapsed: this.timer(),
    });
```

Seems to work, firebase is showing me the 5 properties but they have no values. Is there a way to debug this or am I doing something wrong?

<img width="1015" alt="bildschirmfoto 2017-06-24 um 01 04 04" src="https://user-images.githubusercontent.com/4848184/27503045-17cfbcec-5879-11e7-9a0a-8bb559179ae0.png">
<img width="1054" alt="bildschirmfoto 2017-06-24 um 01 03 58" src="https://user-images.githubusercontent.com/4848184/27503044-17c02372-5879-11e7-96a4-85ca89c5a3b9.png">

**Comment by esdrasportillo** [comment]
Hey,

Yes, you can debug using the [DebugView](https://firebase.google.com/docs/analytics/debugview).

You can follow this [steps](https://support.google.com/firebase/answer/7201382?hl=en).

Then you can see everything that is being logged in real-time.

**Comment by mxmtsk** [comment]
Thank you very much... while it helped (my code is correct and the right values are sent) I guess I have to go figure out why it's not shown. The package seems work alright, thanks

**Comment by Ehesp** [comment]
I think I saw this a while ago. I hooked my Firebase Analytics up with Google Analytics and they showed in the latter. Not sure whether it's the same now after the changes from Firebase.
