### ISSUE TITLE
Can't build after installing react-native-firebase

### ISSUE THREAD

**Issue by kobimilan995** [invertase/react-native-firebase#2021]
## Issue

I m having trouble building an app after fresh firebase installation. It just gives this weird error. Please help. I have tried all the other fixes suggested, nothing helped.

## Project Files
<img width="1197" alt="Screenshot 2019-04-02 at 21 21 51" src="https://user-images.githubusercontent.com/31390546/55430292-ff17a480-558d-11e9-9c9e-069eb4e06d8d.png">

#### `ios/Podfile`:

- [x] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:

## Environment

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Operating System:**
  - [x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **`React Native` version:**
  - Latest
- **`React Native Firebase` library version:**
  - Latest version

- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

**Comment by mikehardy** [comment]
I would recommend using Pods personally. Make sure you get the starter app working as a test of your environment and build toolchain then do what it does (using a Podfile). react-native will move to pods and Google Firebase is pod based so it should be the path of least resistance going forwards

**Comment by mikehardy** [comment]
https://github.com/invertase/react-native-firebase/issues?q=is%3Aissue+sort%3Aupdated-desc+firebase.h+not+found+is%3Aclosed

**Comment by iamclaytonray** [comment]
React Native 0.59.0+ now ships without support for Pods. Technically, you can add them back in but this seems to go against what RN is trying to do.

**Comment by mikehardy** [comment]
I'm not sure what you mean by "without support for Pods". I'm using 0.59.3 with Pods fine. Where was pod support taken out?

**Comment by Ehesp** [comment]
Going to close this one as standard install should be fine. Please ensure you have followed all setup instructions - ping us on Discord if you're still having issues.
