### ISSUE TITLE
Grouped notifications on iOS

### ISSUE THREAD

**Issue by Badbreaddead** [invertase/react-native-firebase#2022]
First of all thank you for all your work you have done for the community!

It would be great to have grouped notifications on [iOS](https://developer.apple.com/videos/play/wwdc2018/711/) as well as in [Android](https://developer.android.com/training/notify-user/group). They were released in iOS 12. Any plans on implementing?

**Comment by Ehesp** [comment]
Thanks for the feature request; to ensure we capture it, please add it to our Canny board: https://boards.invertase.io/react-native-firebase
