### ISSUE TITLE
Implement `isEqual` method on firestore's `DocumentReference`

### ISSUE THREAD

**Issue by cmmartin** [invertase/react-native-firebase#2028]
According to the [Firestore docs](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference#isequal) the `DocumentReference` object should implement an [`isEqual`](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference#isequal) method for equality testing document references

Please see [this issue](https://github.com/CSFrequency/react-firebase-hooks/issues/11) for an example use case for this method in `react-native-firebase`

Thank you everyone for all the hard work on this project

**Comment by Salakar** [comment]
Hey @cmmartin - thanks for letting me know - I'll push a patch release of v5.2.x with this in shortly.

**Comment by Salakar** [comment]
Hey @cmmartin 

This is up on the NPM 'next' tag now if you'd like to use it:

```
npm install react-native-firebase@5.2.4
```

I'll publish to the 'latest' tag once I can confirm https://github.com/invertase/react-native-firebase/issues/2009#issuecomment-480219054 is resolved.

Thanks :)

**Comment by cmmartin** [comment]
Thank you for the quick turnaround!

**Comment by cmmartin** [comment]
Hey @Salakar. Sorry I missed this the first time, but `CollectionReference` should also implement `isEqual` as documented [here](https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference#isEqual)

Let me know if you rather I open a new issue. Sorry again for missing it the first time
