### ISSUE TITLE
error in phone authentication in ios

### ISSUE THREAD

**Issue by seongminchoob** [invertase/react-native-firebase#2029]
## Issue

phone auth was working fine until not but suddenly it started to not work.

I run         firebase.auth().signInWithPhoneNumber('MY PHONE NUMBER')
            .then(confirmResult => {
                this.setState({confirmResult, verificationOpened: false})
            })
            .catch(error => console.log(error));

and then I get 

Error: {"error":{"code":403,"message":"Requests from this ios client application <empty> are blocked.","errors":[{"message":"Requests from this ios client application <empty> are blocked.","domain":"global","reason":"forbidden"}],"status":"PERMISSION_DENIED"}}
    at createErrorFromErrorData (NativeModules.js:155)
    at NativeModules.js:104
    at MessageQueue.__invokeCallback (MessageQueue.js:414)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at e (RNDebuggerWorker.js:1)

in my console.

It's quite bizarre that it was working fine until not and suddenly is not working
---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:
platform :ios, '9.0'

target 'studyDot' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # Pods for studyDot
  pod 'React', :path => '../node_modules/react-native', :subspecs => [ 'Core', 'CxxBridge', 'DevSupport', 'RCTText', 'RCTActionSheet', 'RCTNetwork', 'RCTWebSocket', 'RCTGeolocation', 'RCTAnimation', 'RCTImage', 'RCTVibration', 'RCTSettings', 'RCTLinkingIOS', ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-ccs-naver-login', :path => '../node_modules/react-native-ccs-naver-login'
  pod 'react-native-blur', :path => '../node_modules/react-native-blur'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
  pod 'GoogleSignIn', '~> 4.4.0'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
    # React Native third party dependencies podspecs

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```ruby
# N/A
```

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [x ] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `ADD_SOMETHING_HERE` e.g. Xcode 10, Android Studio 3.2
newest xcode
- **`React Native` version:**
  - `0.59.2'
- **`React Native Firebase` library version:**
  - `5.15.0`
- **`Firebase` module(s) you're using that has the issue:**
  - [] **N/A**
  - [x ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x ] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by mikehardy** [comment]
Looks similar. Maybe you restricted something? https://stackoverflow.com/questions/54720651/firebase-error-requests-from-this-ios-application-empty-are-blocked

**Comment by seongminchoob** [comment]
I don't think I restricted anything..

**Comment by abegehr** [comment]
I'm having the same problem – How can I fix this?

**Comment by mikehardy** [comment]
This showed up for other users recently. It appears to work if you upgrade your Pods to the maximum current version supported by react-native-firebase 5.3.1 (the current max version on the 5.x series). Those pods are 5.20.2

**Comment by abegehr** [comment]
Thank you for your quick reply @mikehardy! I am running RNFirebase 5.3.1 and just updated the pods from 5.20.1 to 5.20.2. I'm still getting the error. Could I try something else? Do you have further ideas or can I provide more info/logs?
I also enabled push notifications, added an APN key in Firebase Console, and added the URL Scheme as described here: https://firebase.google.com/docs/auth/ios/phone-auth#enable-app-verification – I this link could be added to the docs?

**Comment by mikehardy** [comment]
Hmm - if it's straight up blocking them, it sounds like maybe the Google-services.plist bundle id is not 100% equal to the bundle id from your ipa or something? But honestly I'm not sure beyond what you're doing. Sorry..

**Comment by abegehr** [comment]
Thanks for the help, @mikehardy – The bundle ids from Google-services.plist and the iOS project match. After setting the pods to 5.20.2:
`  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Firestore', '~> 5.20.2'
  pod 'Firebase/Storage', '~> 5.20.2'
  pod 'Firebase/Auth', '~> 5.20.2'`
and running `pod install`, git shows this only changed the Podfile.lock and Pods/Manifest.lock, so no updates were installed. Do you have a link to the issue of the other users whom this also affected?

@seongminchoob did you solve the problem?
