### ISSUE TITLE
Messaging - Android RequestPermission

### ISSUE THREAD

**Issue by adamfellon** [invertase/react-native-firebase#2031]
## Documentation Feedback

Hi,

I was wondering why the documentation for messaging has us call `.requestPermission()` when in android the function seems to be doing nothing:

```
  @ReactMethod
  public void requestPermission(Promise promise) {
    promise.resolve(null);
  }
```

Am I missing something with how Android handles permissions for messages?

Or is there a giant leap between them & "Remote Notifications"?

**Comment by SMKH-PRO** [comment]
I am also having same problem it returns null no matter the permission was granted or not
```
  RNfirebase.messaging().hasPermission()
  .then(enabled => {
              if (enabled) {
                // user has permissions
               console.log("have");
               this.SavePushToken()
    } else {
      // user doesn't have permission
      console.log("dont have");
      RNfirebase.messaging().requestPermission()
      .then((res) => {
        // User has authorised 
        this.SavePushToken()  

      })
      .catch(error => {
        // User has rejected permissions  
this.NoNotifPermision() //alert no notic permission

      });
    } 
  });
```

Now the problem here is that, Request permission will never ask for permission and returns .then no matter the permissions are really granted or not or even blocked.  it is always returning then, it should reject instead

It never asked for permissions, I am so shocked that it even generates the token for device too :/ at-least token generate should return a reject promise when permissions are not allowed.


I am actually saving token when permissions are granted, it is generating the token even when the notifications are blocked, just because it is returning resolve promise.

**Comment by SMKH-PRO** [comment]
How I Temporarily Solved this problem, Using "react-native-app-setting"  package

`import React, { Component } from 'react'
import { Text, View ,AppState} from 'react-native'


import RNfirebase from 'react-native-firebase' 
import OpenAppSettings from 'react-native-app-settings' 

export default class componentName extends Component {
constructor(props){

    super(props)
    this.state={

        GoneToSetting:false
    }
}


componentDidMount=()=>{
    AppState.addEventListener('change',this.UserCameBack); //It will detect AppState is changed
    this.CheckPermissions()
}


componentWillUnmount=()=>{
    AppState.removeEventListener('change', this.UserCameBack);
}



CheckPermissions=()=>{

    RNfirebase.messaging().hasPermission()
    .then(enabled => {
  if(enabled){ //Permission is granted
  //your functions to generate/save token
  }
  else{
  
  this.NoPermission() //Permissions are not granted, we will show alert and manually ask
  }
  
    });
}



NoPermission=()=>{
    AsyncStorage.getItem('NeverAskNotifPermission').then(Never=>{
        let NeverAsk = JSON.parse(Never)
    if(!NeverAsk){ //Never ask must  not be true

      this.ShowAlert() 
    }

})

}



ShowAlert=()=>{
    Alert.alert(
        'Warning!',
        "Please Allow Notification Permissions", //Your message to user for allowing permission
        [
          {text: 'Never Ask!', onPress: () =>  AsyncStorage.setItem('NeverAskNotifPermission',JSON.stringify(true)).then(Done=>{console.log(Done)})}, //It will never ask untill user clear cache
          {
            text: 'Later',
            onPress: () => console.log('Later Pressed'), //Will just ignore the alert 
            style: 'cancel',
          },
          {text: 'Turn On', onPress: () =>this.UserGone()  }, //Will go to app setting screen
        ],
        {cancelable: false},
      );
}



UserGone=()=>{
    this.setState({GonToSetting:true},()=>OpenAppSettings.open())
}



UserCameBack=()=>{
    if(this.state.GoneToSetting){ 
//User came back from settings screen, now you check again for permissions
       this.CheckPermissions()
//Note: if you check permissions here, it may show an alert again if the permission are not granted by user after coming back from settng screen, it won't alert again if permissions are granted

    }
}



  render() {
    return "WhatEver You Want to return"
  }
}

`

**Comment by adamfellon** [comment]
Nice!

Thanks, I think we'll end up doing something similar!

Have you tried `.requestPermission()` on iOS?  I assume that function is actually going to prompt the user, but I haven't tested it yet.

**Comment by SMKH-PRO** [comment]
> Nice!
> 
> Thanks, I think we'll end up doing something similar!
> 
> Have you tried `.requestPermission()` on iOS? I assume that function is actually going to prompt the user, but I haven't tested it yet.

Nope, I havent tried on iOS yet.
Even if it doesnt then, According to this doc:- `https://facebook.github.io/react-native/docs/pushnotificationios`
we can request permission on ios, (Havent tried myself)

**Comment by DV31** [comment]
even i get null in requestPermission() method.

**Comment by adamfellon** [comment]
If you look in the java code the function just resolves a promise of null. Think the whole requestpermission() is an iOS required thing, and not on android.

**Comment by DV31** [comment]
getToken() method is also giving null response can you help me with that...?

initially it was working well but after some time i did not found the FCM token in the response. 
so please help me with this issue. 
tell me the place or file or methods that i have to check for the same.

**Comment by DV31** [comment]
@adamfellon  currently Im using it for android. and i have checked console log as well console error didn't found any issue.

**Comment by manhtienptit** [comment]
Have anyone still met on this issue??

**Comment by upngo** [comment]
for anyone who stumbles onto this in '22
Android from 33 requires permission to be requested, but fortunately react native offers this functionality
```
import {PermissionsAndroid} from 'react-native';
PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS);
```
