### ISSUE TITLE
firestore get API not working

### ISSUE THREAD

**Issue by uditbansal2007** [invertase/react-native-firebase#2037]
## Issue

I am using RNFirebase for interacting with my firestore database. While I am able to update and create the documents via SET API, I am not able to do a GET on the document reference. While there is no error, there is no result as well.

This works:
 this.ref = firebase.firestore().collection('user').doc(this.state.user.phoneNumber);
        this.ref.set({
            name: this.state.name
        }, {merge: true})

This does not works (console log not present):
this.ref = firebase.firestore().collection('user').doc(this.state.user.phoneNumber);
   
this.ref.get()
  .then(doc => {
    if (!doc.exists) {
      console.log('No such document!');
    } else {
      console.log('Document data:', doc.data());
    }
  })
  .catch(err => {
    console.log('Error getting document', err);
  });

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [ ] MacOS, version: `N/A`
  - [x] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Visual studio code`
- **`React Native` version:**
  - `react-native-cli: 2.0.1 react-native: 0.59.2`
- **`React Native Firebase` library version:**
  - `"react-native-firebase": "^5.2.3",`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [x] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [ ] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by LuisRodriguezLD** [comment]
I feel you, I've been having the same problem for the last couple of days. I am sure they already know this, I was checking our their twitter and saw [this tweet](https://twitter.com/rnfirebase/status/1114350926448476161) so I gave it a go. 

Apparently it's still a release candidate but it works now. Just update to version `5.3.0`

**Comment by uditbansal2007** [comment]
Workaround: https://stackoverflow.com/questions/55476263/unable-to-fetch-data-from-firebase-firestore-in-react-native

**Comment by mikehardy** [comment]
it is not published yet it is still WIP but will be shortly per this:

https://github.com/invertase/react-native-firebase/pull/2033#issuecomment-480491511

**Comment by Salakar** [comment]
Just published `5.3.0-rc1` if you'd like to switch - this will be the full release - I just need to add docs, migration notes & update the starter before I can switch it over.

**Comment by mikehardy** [comment]
NM my comment on other thread, I will get it. Thanks!

**Comment by Salakar** [comment]
No worries; if you need to know which versions of dependencies etc; you can use the testing app as a reference: https://github.com/invertase/react-native-firebase/tree/%40salakar/v5/v5.3.x/tests  (ios/Podfile for ios & android/app/build.gradle for Android)

**Comment by uditbansal2007** [comment]
> Just published `5.3.0-rc1` if you'd like to switch - this will be the full release - I just need to add docs, migration notes & update the starter before I can switch it over.

Got dependency resolution issues with 5.3.0-rc1

 The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[16.0.5,16.0.5]], but resolves to 16.4.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
> The library com.google.firebase:firebase-analytics is being requested by various other libraries at [[16.0.6,16.0.6]], but resolves to 16.4.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

**Comment by Salakar** [comment]
👋 hey - thanks for the report. v5.3.0 is now published on NPM which fixes this issue.


Please see the [change log](https://rnfirebase.io/docs/v5.x.x/releases/v5.3.x) for more info & upgrade steps.

**Comment by uditbansal2007** [comment]
Not sure if it fixes it entirely.

I am trying to get a collection via reference, and same thing happens, no result.

getMenu() {
    this.ref = firebase.firestore().collection('menu');
    this.ref
     .get()
      .then(
        querySnapshot => {
          console.log('x');
        }
      ).catch(
        err => {
          console.log('get menu error', err);
        }
      ).finally(
        err => {
          console.log('get menu error', err);
        }
      ).done(
        err => {
          console.log('get menu done', err);
        }
      );
  }

**Comment by LuisRodriguezLD** [comment]
@uditbansal2007 did you update the [Android dependencies](https://rnfirebase.io/docs/v5.x.x/releases/v5.3.x#Android---Update-Dependencies)?

**Comment by uditbansal2007** [comment]
@LuisRodriguezLD Yup

I tried onSnapshot as well.. Not working..

   this.ref = firebase.firestore().collection('user');
  
  this.ref.onSnapshot(docSnapshot => {
    console.log(`Received doc snapshot: `);
    // ...
  }, err => {
    console.log(`Encountered error: `);
  });

**Comment by LuisRodriguezLD** [comment]
@uditbansal2007 

This is working for me:
```js
this.ref = firebase.firestore().collection('users');
this.ref.get()
    .then(querySnapshot => {
        console.log(querySnapshot);
	console.log(querySnapshot._docs);
})
```

**Comment by uditbansal2007** [comment]
I upgraded my build.gradle to 3.3.2, and it is now working for me. Thanks for the help @LuisRodriguezLD

**Comment by yuritoledo** [comment]
Any update? I have the same environment, but it dont work :/

**Comment by LuisRodriguezLD** [comment]
@yuritoledo this has been fixed in v5.3 Did you double check your build.gradle version?

**Comment by yuritoledo** [comment]
yes, i've opened an issue #2270

**Comment by Robotecom** [comment]
This issue has returned again,I have all other APIs of query and updating and creating document but GET it just returns an empty document without any error thrown ,Please help

**Comment by masterkrang** [comment]
@LuisRodriguezLD's solution worked for me. one issue is that the Google Firebase - Node.js docs say to get like this:

```
  let getDoc = this.ref.get()
      .then(doc => {
        if (!doc.exists) {
          console.log('No such document!');
        } else {
          console.log('Document data:', doc.data());
        }
      })
      .catch(err => {
        console.log('Error getting document', err);
      });
```

i think this means simply that `!doc.exists` is failing, not the queries. that documentation that might need updating. find it here: https://firebase.google.com/docs/firestore/query-data/get-data#get_a_document
