### ISSUE TITLE
[iOS] can not open app store when click on dynamic link

### ISSUE THREAD

**Issue by dantn93** [invertase/react-native-firebase#2039]
## Issue

I create a dynamic link by ".createShortDynamicLink(link, 'UNGUESSABLE')". Everything is ok if the app is installed. But if I don't install the app, the dynamtic link don't redirect to app store. The browser show: Dynamic Link not found
I reported this issue to firebase team, and they said
## Checking your Firebase Dynamic Link (FDL), the link parameter is also a Firebase Dynamic Link. Take note that deep link must be a well-formatted URL, be properly URL-encoded, use either HTTP or HTTPS, and cannot be another Dynamic Link. It also seems that your FDL doesn't have an 'isi' parameter, kindly include it when reconstructing your Dynamic Link. You could check out this link for more information. ##
Then I see my link which does not have 'isi' parameter really

.createShortDynamicLink(link, 'UNGUESSABLE'):  https://test02.page.link/3rNsHVM4VebCpKnv8

.createDynamicLink(link):
https://test02.page.link/?link=https%3A%2F%2Ftest02%2Epage%2Elink%2FreferralCode%3DTASKER1&ibi=com%2Ebtaskee%2Epartner&apn=com%2Ebtaskee%2Epartner

so how can I add isi parameter into the dynamic link or any solution to resolve it?

---

### iOS

React Native: 0.55.4
React Native Firebase: 4.3.8

**Comment by affanhashone** [comment]
@dantn93  Did You resolve this issue ?
