### ISSUE TITLE
iOS notification not handled on app start

### ISSUE THREAD

**Issue by havaliza** [invertase/react-native-firebase#204]
I'm trying to setup FCM in iOS. It works well except when the iOS app is closed and is launched by opening the notification. It triggers `didReceiveRemoteNotification` in `AppDelegate` but no notification is received in JS code.

I traced the calls via breakpoints and found out that in this case `RNFirebaseMessaging.didReceiveRemoteNotification` is called earlier than `RNFirebaseMessaging.initialiseMessaging`. So the `MESSAGING_NOTIFICATION_RECEIVED` is emitted while the observer `handleNotificationReceived` is not added yet.

Do you have any suggestions to fix this. Am I missing some initialization call that I should make earlier?

**Comment by havaliza** [comment]
To prove that the problem is about order of calls I delayed calling `RNFirebaseMessaging.didReceiveRemoteNotification` for 4 seconds and It worked correctly as expected.

```objc
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 4 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
    [RNFirebaseMessaging didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
  });
}
```

**Comment by chrisbianca** [comment]
@havaliza The notification that triggers the app to initialise is available using:

```
firebase.messaging().getInitialNotification().then((notification) => {
  // process notification here
});
```

rather than the standard `onMessage()`

**Comment by havaliza** [comment]
@chrisbianca Damn it. I just found out that Firebase is blocking connections from Iran. I didn't investigate the issue further but as long as nobody else has the same issue and others are fine it might be related to Google's restrictions on Iran. Therefore I close this issue. Thanks for your time :)
