### ISSUE TITLE
[Question] Does this work with a "managed" expo application?

### ISSUE THREAD

**Issue by OwenMelbz** [invertase/react-native-firebase#2040]
## Documentation Feedback

Nowhere that I can find says if expo managed flow is supported - is it?

You can't search the issues for this as the bug template says "are you using expo" so every bug in github returns as a result.

Thanks

**Comment by Ehesp** [comment]
Hello - it doesn't I'm afraid, as at the moment you can't use other native modules in a fully managed Expo project.

The Expo team [did start working on it](https://www.npmjs.com/package/expo-firebase-app), however you can read their reasoning [here](https://gist.github.com/brentvatne/9038b16b4f42a21cea40ad5c35fdb74c) for deprecating the support.

Your options are to eject or use the Firebase Web SDK.
