### ISSUE TITLE
🔥 'No known class method for selector fieldValueForDoubleIncrement'

### ISSUE THREAD

**Issue by Eralyne** [invertase/react-native-firebase#2044]
## Issue

Whenever I try to build the app for iOS in Xcode 10.1, I get the error shown in the image below: 
<img width="270" alt="Screen Shot 2019-04-09 at 10 58 25 PM" src="https://user-images.githubusercontent.com/7963271/55850699-140aaf80-5b1b-11e9-8bdd-ca6d1cccaf5e.png">

This occurs when building on the new build system and has started happening since I've upgraded to the library version 5.2.1

Previously, I was on an older version but building off of the legacy system. I didn't want to do this, so I followed [this step](https://github.com/invertase/react-native-firebase/issues/1610#issuecomment-455418564) to get to where I am now. No matter what I do, I cannot fix this current error that I have right now. I've attempted upgrading and downgrading the library as well as the firebase module pods. I've tried manually linking and, what's currently there, linking through the pods. 

I'm just trying to see where I went wrong and if there's another fix to #1610 that doesn't cause my current issue or just a straight fix to the error I have now.

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '9.0'

target 'Comely' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Comely

  # React
  rn_path = '../node_modules/react-native'
  
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # Facebook
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FBSDKCoreKit', '4.38'
  pod 'FBSDKLoginKit', '4.38'
  pod 'FBSDKShareKit', '4.38'

  # RNFirebase
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Analytics', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'Firebase/Storage', '~> 5.15.0'
  pod 'Firebase/Functions', '~> 5.15.0'

  # Crashlytics
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'

  # Navigation
  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

  # Radar
  pod 'RadarSDK', '~> 2.1.3'
  pod 'react-native-radar', :path => '../node_modules/react-native-radar'

  # Image Crop Picker
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  # Image Resizer
  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  # Mapbox
  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'

  # Touch Through View
  pod 'RNTouchThroughView', :path => '../node_modules/react-native-touch-through-view'

  # Clear React
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

  target 'ComelyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Environment

- **Platform that you're experiencing the issue on**:
  - [X] iOS
- **If known, the version of the platform are you experiencing the issue on:**
  - `iOS 9`
- **Operating System:**
  - [x] MacOS, version: `macOS Mojave 10.14`
- **Build Tools:**
  - `Xcode 10.1`
- **`React Native` version:**
  - `0.57.3`
- **`React Native Firebase` library version:**
  - `5.2.1`
- **`Firebase` module(s) you're using that has the issue:**
  - [X] **N/A**
- **Are you using `TypeScript`?**
  - [X] No
- **Are you using Expo, e.g. `ExpoKit`?**
  - [X] No

**Comment by cristianPerez** [comment]
I got the same problem !!

**Comment by RichardFevrier** [comment]
Available in the [5.19 Firebase SDK version](https://github.com/firebase/firebase-ios-sdk/blob/release-5.19.0/Firestore/Source/Public/FIRFieldValue.h).

@team-rnfirebase you should update your documentation :

![ydkw5hon2ou8bgjot0uVtCUd5fHrl-FVR36G5pYevSGrp4JDRpc9CkDrHbJkeOBbnf6zLTgbIoZLFSRyhZFNaTJprjKJn4snkOQIlHyX-Do](https://user-images.githubusercontent.com/5154754/55867577-0c7ef100-5b83-11e9-85cb-d6c8758a1edd.png)

**Comment by Salakar** [comment]
Docs have been updated to reflect, though 5.2.1 specifically has no Increment code in it so this should not be erroring?

Only 5.3.x has this which I imagine is what has been installed here - the docs for 5.3.x specifically state 5.19 and above.

Please see the 5.3.x release notes: https://rnfirebase.io/docs/v5.x.x/releases/v5.3.x

**Comment by ccoeder** [comment]
I have the same error, and updating `react-native-firebase` to 5.3.1 doesn't make it work. Can you help me?

**Comment by Eralyne** [comment]
@Codeseer Updating Pods to 5.20.1 fixed the issue for me. You can see the guide for all of the important upgrading info here: https://rnfirebase.io/docs/v5.x.x/releases/v5.3.x

**Comment by TranVanThaiSon** [comment]
slove step intrusctions :https://rnfirebase.io/docs/v5.x.x/releases/v5.3.x

**Comment by matong1745** [comment]
How can I solve this problem if I have no Podfile ?
And I use https://github.com/firebase/firebase-ios-sdk/releases/download/5.15.0/Firebase-5.15.0.zip for project, if I upgrade to any new version I will get error "Not found boringSSL framework".

**Comment by mikehardy** [comment]
@matong1745  - 2 thoughts 

- 1 - I would strongly encourage a Podfile and using Pods for Firebase. Why? Because Pods is the recommended way from the Google Firebase team, and it is the decided direction for React-Native itself (with RN0.60 they will move to that as a default for iOS basically, and alter linking style), because it is the way the starter works so you have a nice "toy" app to look at that is a running example, and also because in my opinion it is easier.

- 2 - If you take the advice from No 1 above, you just need to include the right Pods for Firebase and the BoringSSL framework is *automatically* included since it is a dependency. Which is the whole point of Pods being easier :-)

**Comment by matong1745** [comment]
@mikehardy Please help me out.
I already delete node_modules and Pods folder and then i enter the "yarn" and pod install
this is my Podfile. Still get the same error. 
![image](https://user-images.githubusercontent.com/25519723/57063174-90447d00-6cec-11e9-9465-03e42db7f024.png)

```ssh
target 'Project' do
    pod 'Firebase/Auth', '~> 5.20.1'
    pod 'Firebase/Core', '~> 5.20.1'

    target 'Project-tvOSTests' do
      inherit! :search_paths
      # Pods for testing

    end
  
    target 'ProjectTests' do
      inherit! :search_paths
      # Pods for testing
    end
  end
  ```
This is version on package.json
```ssh
"react-native-firebase": "^5.3.1"
```

**Comment by mikehardy** [comment]
looks like something is including firestore but it is not in your podfile

**Comment by TranVanThaiSon** [comment]
sorry because reply delay, and react-native firebase 5.x.x have upgrade,
Please commit  https://rnfirebase.io/docs/v5.x.x/getting-started

Vào Th 5, 2 thg 5, 2019 vào lúc 23:00 Mike Hardy <notifications@github.com>
đã viết:

**Comment by iWaleedibrahim** [comment]
I have this exact issue with react-native-firebase when I upgraded to react native 0.63.0 from 0.61.5, Any clues?

**Comment by mikehardy** [comment]
In my experience no one has the exact same issue. @iWaleedibrahim this is a closed issue. Please open a new issue respecting the issue template
My guess is you are still using old versions somewhere, if you can reproduce by cloning this repo and running this script https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh hooked to an example project with a simple reproduction added in the App.js, we have a problem with the module, otherwise I suspect you have an integration issue in your local project

**Comment by harshitsmt** [comment]
Facing this same issue while running the app the build fails throwing the same error

**Comment by mikehardy** [comment]
@harshitsmt you likely have out of date underlying SDKs (firebase-ios-sdk / firebase-android-sdk) the main page of rnfirebase.io shows you how to override them so that you are current (and the same information may be used to remove any overrides you have now, such that you get the matched SDK used during the release, which will have all the symbols defined correctly)

**Comment by razahameedkhan** [comment]
if (![TwilioVoice handleNotification:payload.dictionaryPayload delegate:self delegateQueue: nil]) {
          NSLog(@"This is not a valid Twilio Voice notification.");
      }
      
      No known class method for selector 'handleNotification:delegate:delegateQueue:'
      
someone plz help. how to remove that error in react native iOS?

**Comment by mikehardy** [comment]
I believe you contact who ever wrote "TwilioVoice" and ask for support @razahameedkhan
