### ISSUE TITLE
Version 5.3.0 no longer compiles on Android

### ISSUE THREAD

**Issue by franck-nadeau** [invertase/react-native-firebase#2050]
## Issue

Version 5.3.0 no longer compiles on Android.

I get the following errors:

````
ERROR: Unable to resolve dependency for ':react-native-firebase@release/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.11.0.
Show Details
Affected Modules: react-native-firebase

ERROR: Unable to resolve dependency for ':react-native-firebase@release/compileClasspath': Could not resolve com.squareup.okio:okio:1.14.0.
Show Details
Affected Modules: react-native-firebase

ERROR: Unable to resolve dependency for ':react-native-firebase@release/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.11.0.
Show Details
Affected Modules: react-native-firebase

ERROR: Unable to resolve dependency for ':react-native-firebase@release/compileClasspath': Could not resolve com.squareup.okio:okio:1.14.0.
Show Details
Affected Modules: react-native-firebase

ERROR: Unable to resolve dependency for ':react-native-firebase@release/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.12.1.
Show Details
Affected Modules: react-native-firebase

ERROR: Unable to resolve dependency for ':react-native-firebase@release/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.10.0.
Show Details
Affected Modules: react-native-firebase

ERROR: Unable to resolve dependency for ':react-native-firebase@release/compileClasspath': Could not resolve com.squareup.okio:okio:1.15.0.
Show Details
Affected Modules: react-native-firebase

ERROR: Unable to resolve dependency for ':react-native-firebase@release/compileClasspath': Could not resolve com.squareup.okio:okio:1.6.0.
Show Details
Affected Modules: react-native-firebase

ERROR: Unable to resolve dependency for ':react-native-firebase@release/compileClasspath': Could not resolve com.squareup.okio:okio:1.13.0.
Show Details
Affected Modules: react-native-firebase
````

---

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        maven {
            url 'https://maven.fabric.io/public'
        }
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'com.google.gms:google-services:4.2.0' // google-services plugin
        classpath 'io.fabric.tools:gradle:1.26.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        jcenter()
    }
}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28     //do this in android/app/build.gradle too
                buildToolsVersion '28.0.3'  //do this in android/app/build.gradle too
            }
        }
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}
```

#### `android/app/build.gradle`:

```groovy
apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js",
    bundleInRelease: true
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion '28.0.3'

    defaultConfig {
        applicationId ""
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "11.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
...
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        debug {
            applicationIdSuffix ".debug"           
        }
        releaseStaging {
            applicationIdSuffix ".staging"
            matchingFallbacks = ['release']
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation project(':react-native-view-pdf')
    implementation project(':react-native-firebase')
    // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:16.0.1"
    implementation "com.google.firebase:firebase-core:16.0.8"
    implementation 'com.google.firebase:firebase-messaging:17.4.0'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.9.9'

    implementation 'me.leolin:ShortcutBadger:1.1.21@aar' // <-- badge on Android

    implementation project(':react-native-device-info')
    implementation project(':react-native-svg')
    implementation project(':react-native-offline-cache-webview')
    implementation project(':react-native-keychain')
    implementation project(':react-native-camera')
    implementation project(':react-native-code-push')
    implementation project(':react-native-fast-image')
    implementation project(':react-native-fs')
    implementation project(':react-native-gesture-handler')
    implementation project(':react-native-i18n')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-sound')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-version-number')
    implementation project(':react-native-view-overflow')

    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}


apply plugin: 'com.google.gms.google-services'
apply plugin: 'io.fabric'

com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [ x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `ADD_SOMETHING_HERE` e.g. Xcode 10, Android Studio 3.2
- **`React Native` version:**
  - `ADD_SOMETHING_HERE`
- **`React Native Firebase` library version:**
  - `ADD_SOMETHING_HERE`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x ] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

**Comment by Salakar** [comment]
Hey @franck-nadeau I think this is down to React Native using an older version of `okhttp3` / `okio`.

If you can please could you update to RN 59.3+ (I had no issues compiling on this version) - not sure what else we can do here other than force the version that RN uses.

**Comment by Kazn** [comment]
version 5.2 is also no longer compiles on Android.

**Comment by hoseineghbal** [comment]
what must we do then ???

**Comment by mikehardy** [comment]
I can't imagine what would cause the firebase starter to not work if you checked it out at this commit (prior to the 5.3.0 release) https://github.com/invertase/react-native-firebase-starter/commit/97bb70f9802d34fdc496e91d2eec4139e00654ed

Which is to say, I would need to see that fail before I thought "version 5.2 no also no longer compiles on Android"

These are really big chunks of functionality, depending on a very large amount of libraries all versioned independently - being very very careful with the versioning by reverting/starting out from a known good point (like the starter app) then very very carefully applying it to my own project is how I manage

The issue template was not followed so I can't comment on specific versions but the starter while it was on react-native-firebase 5.2.x was working with RN0.58.x and 0.59.x.

**Comment by nicoburns** [comment]
@mikehardy We can't build 5.3 or 5.1. I suspect that one of your dependencies has not been as careful with their version pinning.... (https://github.com/invertase/react-native-firebase/issues/2048)

**Comment by niteenach** [comment]
I am also facing the same issue in project...Not able to build the apk...

react-native: 58.0
react-native-firebase - 5.3.1

**Comment by franck-nadeau** [comment]
Thanks everyone for the quick responses! Here is what I found out:

1. Forcing the lib to 5.2.3 resolved the issue.
2. Updating react-native from 0.57.8 to **0.59.4** allowed me to use the latest version (5.3.1)

Thank you @Salakar for putting me on the right track.

**Comment by niteenach** [comment]
My code is already working with first option..now will try 2 option too as latest version will be better. 
I faced problem with another package also **react-native-gesture-handle**r..need to use 1.0.17 version of the same if anybody using it.

**Comment by Salakar** [comment]
Thanks for the update @franck-nadeau 👍 based on this I'll update the docs to indicate that 59.3+ is the recommended version for 5.3.1.

**Comment by faisal3413** [comment]
Downgrading firebase to 5.1.0, 
react-native-gesture-handler to 1.0.5 
react-native 0.56.0

is now working for me.

**Comment by franck-nadeau** [comment]
I am closing this issue since it was caused by incompatibilities from an other library (react native).

**Comment by ccorcos** [comment]
> incompatibilities from an other library (react native)

That's weird because this is a react native library right?

I'm having issues with the latest react-native and latest react-native-firebase packages together.

```
react-native-firebase 5.5.6
react-native 0.60.5
```

**Comment by ccorcos** [comment]
Hmm. Some quick searching around and it appears the version numbers should line up...

react-native

    OKHTTP_VERSION=3.12.1
    api("com.google.code.findbugs:jsr305:3.0.2")
    api("com.squareup.okhttp3:okhttp:${OKHTTP_VERSION}")
    api("com.squareup.okio:okio:1.15.0")


react-native-firebase

    <orderEntry type="library" name="Gradle: com.google.code.findbugs:jsr305:3.0.2@jar" level="project" />
    <orderEntry type="library" name="Gradle: com.squareup.okhttp3:okhttp:3.12.1@jar" level="project" />
    <orderEntry type="library" name="Gradle: com.squareup.okio:okio:1.15.0@jar" level="project" />

**Comment by ccorcos** [comment]
I am noticing multiple versions being defined in this library though:

    <orderEntry type="library" name="Gradle: com.squareup.okio:okio:1.15.0@jar" level="project" />
    <orderEntry type="library" scope="TEST" name="Gradle: com.squareup.okio:okio:1.6.0@jar" level="project" />
