### ISSUE TITLE
Using Facebook Audience as mediation network in Admob.

### ISSUE THREAD

**Issue by jpm8888** [invertase/react-native-firebase#2053]
RN-Firebase Version : 5.3.0

Facebook Test Ad is showing in both platforms. but I think something is wrong with mediation layer between admob and facebook mediation library.

I've using same base code for ios and android.

When i'm testing for android it is not showing requests in debugger.

Please take a look on screenshots.

iOS is working fine with debugger, android is not showing the debugger results.

![Screenshot 2019-04-12 at 3 24 41 PM](https://user-images.githubusercontent.com/1531956/56029485-139b3000-5d38-11e9-9c13-b86c92cdef6f.png)
![Screenshot 2019-04-12 at 3 25 44 PM](https://user-images.githubusercontent.com/1531956/56029486-14cc5d00-5d38-11e9-81a4-75728ed19185.png)

I've also double checked the integration guide provided by both platforms (Admob and Facebook).

```
//build.gradle
implementation "com.google.firebase:firebase-ads:17.2.0"
implementation "com.google.firebase:firebase-core:16.0.8"
implementation 'com.facebook.android:audience-network-sdk:5.2.0'
implementation 'com.google.ads.mediation:facebook:5.2.0.1'
```

**Comment by babyrusa** [comment]
@jpm8888 Hello. I'm integrating FB Audience for my Admob Mediation. There isn't much instruction online for the case of React Native. I'm wondering if you have to install some sort of "react native facebook audience" library to Admob to work (mine is not receiving bidding right now), or do you just add 
```
 implementation 'com.google.ads.mediation:facebook:6.5.1.1'
    implementation 'androidx.annotation:annotation:1.0.0'
    implementation 'com.facebook.android:audience-network-sdk:6.+'
```

in the app/build.gradle file? 
Thank you
