### ISSUE TITLE
[Request] Manually Link to Android

### ISSUE THREAD

**Issue by dandesdel** [invertase/react-native-firebase#2055]
## Documentation Feedback

I usually link all my projects to android manually since I can't use "react-native link" (It tends to generate problems and not successfully linking any package). 

This process is usually pretty straight forward in most packages but in this case this package seems to have several sub-packages.

I was wondering if it's possible to include manual linking in the documentation.

**Comment by Salakar** [comment]
👋 Hey @dandesdel - thanks for the issue report.

Every package afaik has manual linking instructions, e.g.: https://rnfirebase.io/docs/v5.x.x/auth/android#Install-the-RNFirebase-Authentication-package

Could you let me know where it does not exist and we can update it, thanks

**Comment by japser36** [comment]
The missing manual linking process seems to be here: [https://invertase.io/oss/react-native-firebase/quick-start](https://invertase.io/oss/react-native-firebase/quick-start)

**Comment by BallardB** [comment]
Hi @Salakar! 

Any chance this could be re-opened? I see that there is no documentation for the manual linking process for the initial set up for `react-native-firebase`: https://rnfirebase.io/docs/v5.x.x/installation/android 

There may be docs to this but I may just be looking in the wrong place! 

Cheers!

**Comment by Ehesp** [comment]
That's odd I'll take a look at those pages tomorrow.

As for auto linking, no reason it shouldn't be working. You shouldn't be using react-native link though.
