### ISSUE TITLE
iOS - Can't get URL of Dynamic links on react-native-firebase version 5.3.1 on Firebase/Core 5.20.1

### ISSUE THREAD

**Issue by tamirrab** [invertase/react-native-firebase#2058]
## Issue

iOS - Can't get URL of Dynamic links on react-native-firebase version 5.3.1 on Firebase (Pods) 5.20.1 when call links().getInitialLink()

On react-native-firebase version 5.2.25 and Firebase (Pods) 5.15.0 it's work great.

Android no problem

---

## Project Files

 ```
pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Auth'
  pod 'GoogleTagManager', '~> 7.0'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'

  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
```

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```
 pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Auth'
  pod 'GoogleTagManager', '~> 7.0'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'

  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
```

## Environment

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both

- **Operating System:**
  - [x] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
Xcode 10.2

- **`React Native` version:**
 "0.59.2"

- **`React Native Firebase` library version:**
  "5.3.1"

- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [x] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

**Comment by tamirrab** [comment]
Any updates on this?

**Comment by Maximell** [comment]
Hey @tamirrab - I think I am seeing this as well. Any luck resolving it?
