### ISSUE TITLE
Promise when set data offline

### ISSUE THREAD

**Issue by rodolfobarretoweb** [invertase/react-native-firebase#206]
Hello guys, I have a question.

I have this action on my project:

```
export function save(data) {
    return (dispatch, getState) => {
        return Firebase.database().ref(`profiles/${data.uid}`).set(data).then(() => {
           dispatch({ type : SAVE_PROFILE });
        });
     }
}
```

But when I go to offline mode this promise never resolving. How to fix that ?

PS: The data persiste localy, just the promise never resolving

--------------------------------------------
"react": "16.0.0-alpha.12",
"react-native": "0.45.1",
"react-native-firebase": "1.1.1"

I test this using genymotion and real device

**Comment by rodolfobarretoweb** [comment]
Hi, additional information:

When I try to get data, the promise always resolving online or offline. So, probably has a bug on set method of this library.

**Comment by Ehesp** [comment]
Hey, is it still actually setting/updating on Firebase?

**Comment by rodolfobarretoweb** [comment]
Yes, pretty sure

**Comment by chrisbianca** [comment]
@rodolfobarretoweb is this on iOS, Android or both? Do you have persistence enabled?

**Comment by rodolfobarretoweb** [comment]
@chrisbianca Yes, I have the persistence enable, but I not test in ios devices.

**Comment by SamMatthewsIsACommonName** [comment]
@rodolfobarretoweb @chrisbianca  my experience with this is that for update and set the callback happens when the data actually syncs with the real database (not the local cached version)

**Comment by rodolfobarretoweb** [comment]
@SamMatthewsIsACommonName Yes, works like you describe but the promise haft to be solved, independent of synchronization or not

**Comment by chrisbianca** [comment]
Unfortunately this is out of our control as we rely on the native SDK behaviour.  As the iOS documentation states, the set method will only resolve when the data has been committed to the Firebase servers.

https://firebase.google.com/docs/reference/swift/firebasedatabase/api/reference/Classes/DatabaseReference#/c:objc(cs)FIRDatabaseReference(im)setValue:withCompletionBlock:

**Comment by i2chris** [comment]
What's the workaround for this? Do we just stop using promises and assume the data was written?  Seems a shame.

**Comment by koloff** [comment]
It seems like the only workaround is to check if offline and resolve the promise, hoping the data got written.
