### ISSUE TITLE
🔥Firebase AdMob SSV identification

### ISSUE THREAD

**Issue by nromptea42** [invertase/react-native-firebase#2060]
Hello,
I implemented AdMob successfully and wanted to verify ads seen from the server.
I added the link of my API here : 
<img width="968" alt="Screenshot 2019-04-15 at 12 47 13" src="https://user-images.githubusercontent.com/9318179/56127127-c5c33980-5f7c-11e9-8f55-d8c07128fea2.png">
and like it should, it's called a few minutes after the ads being seen.

## Issue

I want to identify the ads validated by the server.
I can't find any docs about this here  : https://rnfirebase.io/docs/v5.x.x/admob/reference/RewardedVideo  
It seems it's possible to do it when I look at this docs :
https://developers.google.com/admob/android/rewarded-video-ssv  

Is there a way to set the property `user_id` from the RNFirebase package ?  
I couldn't find a way to get the `transaction_id` from the client side. Is it possible ?  

One of these two things would be enough to do a server side check.

Feel free to close this if it's not an issue but a feature request instead and I apologise if that's the case.
Thank you.
#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [ ] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `ADD_SOMETHING_HERE` e.g. Xcode 10, Android Studio 3.2
- **`React Native` version:**
  - `ADD_SOMETHING_HERE`
- **`React Native Firebase` library version:**
  - `ADD_SOMETHING_HERE`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by nromptea42** [comment]
Hi,

I really needed to verify from my server the ads seen by my users so I used another library.
Still, I think it could be great to have this feature with AdMob.
I'm going to close this for now

**Comment by veanhart** [comment]
@nromptea42 what library did you use for verification? Thanks a lot for the reply.

**Comment by nromptea42** [comment]
I used another ad provider

**Comment by shanemduggan** [comment]
@nromptea42 what ad provider did you end up using?

**Comment by nromptea42** [comment]
Hey @shanemduggan I used iron source.
