### ISSUE TITLE
Task :react-native-firebase:compileDebugRenderscript FAILED

### ISSUE THREAD

**Issue by JintoAntony** [invertase/react-native-firebase#2063]
When I try to run-android, it show the following error. I recetnly updated packages.json. 

> Task :react-native-firebase:compileDebugRenderscript FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify dependency resolution listener.
> The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[16.0.5,16.0.5]], but resolves to 16.4.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
> The library com.google.firebase:firebase-analytics is being requested by various other libraries at [[16.0.6,16.0.6]], but resolves to 16.4.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

android/build.gradle  : 

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.0.1'
    }
}

packages.json dependencies : 

  "dependencies": {
    "moment": "^2.24.0",
    "react": "16.6.3",
    "react-native": "0.58.3",
    "react-native-calendars": "^1.32.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-elements": "^1.1.0",
    "react-native-firebase": "^5.3.1",
    "react-native-indicators": "^0.13.0",
    "react-native-root-toast": "^3.0.2",
    "react-native-svg": "^9.4.0",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^2.18.3",
    "socket.io-client": "^2.2.0",
    "victory-native": "^31.0.0"
  },

**Comment by mikehardy** [comment]
If I remember correctly this is a ridiculous error in the google play version check plugin, where it tries to resolve the *range* as a specific *version*. And until it is fixed upstream the only way to build is to turn off their version checker (which is fine, since it is failing at it's job anyway). But I'd subscribe to the upstream issue so you can turn it on later 

https://github.com/google/play-services-plugins/issues/30

workaround https://github.com/Microsoft/react-native-code-push/issues/1448#issuecomment-441269149

**Comment by BachirKhiati** [comment]
@mikehardy shouldn't this be a better solution:
https://github.com/Microsoft/react-native-code-push/issues/1448#issuecomment-487270749

**Comment by mikehardy** [comment]
@BachirKhiati seems like a sane approach. More than anything, an approach you have tested and know works is good, and until they fix the plugin then use it seems smart to be very precise about the metadata values you are clobbering instead of turning off the whole verification - good idea

**Comment by mikehardy** [comment]
This is an upstream bug with 2 possible workarounds documented - closing
