### ISSUE TITLE
Firestore set() and add() no work offline

### ISSUE THREAD

**Issue by diegocalero0** [invertase/react-native-firebase#2065]
Hello, I have a problem with firestore and React Native.

When the application is online everything works fine, but when it is offline only allows me to modify and delete data, but not add.

for example: Add a new document.

![WhatsApp Image 2019-04-18 at 12 31 28 PM](https://user-images.githubusercontent.com/20039102/56379739-08338300-61d6-11e9-8ec0-d5af6b2a33f3.jpeg)

This is code:

`addCourse(){
        if(this.state.id.trim() === ''){
            ToastAndroid.show('El id debe contener al menos un caracter', ToastAndroid.SHORT);
            return;
        }

        this.refs.collection('cursos').doc(this.state.id).get()
        .then((doc) => {
            if(doc.exists){
                ToastAndroid.show('Ya existe un curso con el ID ingresado', ToastAndroid.SHORT);
            }else{
                this.refs.collection('cursos').doc(this.state.id).set({ //here is error
                    "id": this.state.id
                }, {"merge": true}).then(() => {
                    this.props.navigation.navigate('courses')
                })
                .catch((err) => {
                    ToastAndroid.show('Ha ocurrido un error, intente más tarde', ToastAndroid.SHORT);
                })
            }
        })
    }`

i need help, thanks.

**Comment by rzfzr** [comment]
@diegocalero0 you closed this without mentioned a solution...
