### ISSUE TITLE
Unknown data type received timestamp

### ISSUE THREAD

**Issue by flutterhope** [invertase/react-native-firebase#2068]
after update react-native-firebase 5.3.1

This warning has begun. "Unknown data type received timestamp"

Recognize timestamp type as a warning

example
1. set data
firebase.firestore().collection('Test').doc('Test1')
        .set({
            createAt:firebase.firestore.FieldValue.serverTimestamp()            
        })

no problem!

after that
2. get data
firebase.firestore().collection('Test').doc('Test1')
        .get()
        .then(snapshot =>{
            //warning!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            //Unknown data type received timestamp
        });

"react-native-firebase": "^5.3.1"
"react-native": "^0.59.5"

**Comment by mikehardy** [comment]
Did you update all the deps in gradle as well? The firestore change was to track upstream as they changed, you'll need the 18.x version

https://github.com/invertase/react-native-firebase-starter/commit/926a4f89b9087096c901670896c55407d626a60d#diff-dc46f9f5dfe204e394fb41395ccd03cfR189

**Comment by flutterhope** [comment]
this is my build.gradle

// RNFirebase required dependencies
    implementation "com.google.firebase:firebase-core:16.0.8"
    implementation "com.google.android.gms:play-services-base:16.1.0"
    // RNFirebase optional dependencies
    implementation "com.google.firebase:firebase-analytics:16.0.4"
    implementation "com.google.firebase:firebase-ads:15.0.1"
    implementation "com.google.firebase:firebase-auth:16.2.1"
    implementation "com.google.firebase:firebase-config:16.5.0"    
    implementation "com.google.firebase:firebase-database:16.1.0"
    implementation "com.google.firebase:firebase-firestore:18.2.0"
    implementation "com.google.firebase:firebase-messaging:17.5.0"
    implementation "com.google.firebase:firebase-perf:16.2.5"
    implementation "com.google.firebase:firebase-storage:16.1.0"
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.5@aar') {
    transitive = true
    }

I think its latest

**Comment by flutterhope** [comment]
Yes this is my build.gradle

// RNFirebase required dependencies
    implementation "com.google.firebase:firebase-core:16.0.8"
    implementation "com.google.android.gms:play-services-base:16.1.0"
    // RNFirebase optional dependencies
    implementation "com.google.firebase:firebase-analytics:16.4.0"
    implementation "com.google.firebase:firebase-ads:15.0.1"
    implementation "com.google.firebase:firebase-auth:16.2.1"
    implementation "com.google.firebase:firebase-config:16.5.0"    
    implementation "com.google.firebase:firebase-database:16.1.0"
    implementation "com.google.firebase:firebase-firestore:18.2.0"
    implementation "com.google.firebase:firebase-messaging:17.5.0"
    implementation "com.google.firebase:firebase-perf:16.2.5"
    implementation "com.google.firebase:firebase-storage:16.1.0"
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.5@aar') {
    transitive = true
    }

**Comment by mikehardy** [comment]
Huh. Versions look good (at least for firestore) - @Salakar - this work is fresh and the timestamp is *exactly* in the area that was changed. Might be something here...

**Comment by Salakar** [comment]
Hmm may be an issue with the bridge serialisation logic, will take a look tomorrow and report back.

Thanks for all the help you've been giving with issue triaging btw @mikehardy - really appreciate it

**Comment by Salakar** [comment]
@flutterhope I can't reproduce this, as you can see here: https://github.com/invertase/react-native-firebase/blob/5e2d1bd7a90be2bfac97c7788d23b0fb95c22ea4/src/modules/firestore/utils/serialize.js#L216 the `timestamp` case is handled and should not be warning here: https://github.com/invertase/react-native-firebase/blob/5e2d1bd7a90be2bfac97c7788d23b0fb95c22ea4/src/modules/firestore/utils/serialize.js#L235

Maybe your JS bundle is out of sync?

**Comment by flutterhope** [comment]
@Salakar 
The folder you mentioned does not exist
Is the path right?

![image](https://user-images.githubusercontent.com/39448892/56501000-07894c80-6548-11e9-8a3e-9b010ecbf870.png)

**Comment by andyylam** [comment]
Getting this error as well, any updates? I get "Unknown data type received function" infinitely, until I reload the app.

**Comment by mikehardy** [comment]
As near as we can tell, if you are on react-native-firebase 5.x.x current (5.4.2 now I believe), *and* you are on current firestore (`com.google.firebase:firebase-firestore:19.0.0` for me on android, `pod 'Firebase/Firestore', '~> 5.20.2'` on iOS) this should work. It was a specific change in firestore, and a specific change in react-native-firebase to handle it, so the versions are vital.

To make sure your project doesn't have some bizarre state, I recommend `npm i react-native-clean-project && react-native clean-project-auto && cd ios && pod install` - it will take a while but you should be pretty clean after that in case there is some old bundle or something. Even then you might `react-native start -- --reset-cache` and do a specific search for bundles in your assets files (I know I have to pre-build a bundle for old APIs like API17 at least since it can't do reverse port forwarding to load it from the dev server, and sometimes forget it's there)

**Comment by mikehardy** [comment]
I'm shaping up the next release and this was tagged for it but we can't reproduce this and haven't heard back. I'm going to close this but of course we can discuss again or reopen as needed.

**Comment by quiringk** [comment]
I'm getting this error as well. `react-native: 0.60.6` `react-native-firebase: 5.5.6`. This is one of those "this makes no sense, this should be working" errors. I'm calling the same function with the same data and it works from one component, get the error (infinite warnings) from another component. 

![image](https://user-images.githubusercontent.com/6529857/72771752-c09fb480-3bb6-11ea-847b-938527d4223f.png)

After line 281 executes I get these infinite warnings and I have to restart the app

![image](https://user-images.githubusercontent.com/6529857/72771773-d1502a80-3bb6-11ea-8d42-2aa4c5ef6503.png)

**Comment by quiringk** [comment]
Nevermind, I figured it out! I have an object with lots of data that at some point in my application in one of my components I add a React<RefObject> property to (to reference markers on a map). This Ref had "symbols" and "functions" inside it's properties (i.e. __proto__, etc). So I actually did have bad data updating to firestore.
