### ISSUE TITLE
Analytics docs don't mention how to enable automatic audience metrics on iOS

### ISSUE THREAD

**Issue by mikehardy** [invertase/react-native-firebase#2071]
## Documentation Feedback

If I am not mistaken, on iOS you need to link in a separate Pod on order to get the benefit of automatic collection of audience metrics.

https://stackoverflow.com/questions/54437891/firebase-linking-to-libadidaccess-a

https://support.google.com/firebase/answer/6318039

```
For iOS apps, the app must collect IDFA in order to automatically derive the Age,
Gender, and Interests properties.
```

I believe the documentation update should be something along the lines of 

```
If you would like to enable Firebase Analytics to generate automatic audience 
metrics for iOS, you must also link in the IDFA support libraries, available via 
the CocoaPod GoogleIDFASupport
```

Seems like it should be here with some links out to supporting docs:
https://rnfirebase.io/docs/v5.x.x/analytics/ios

Happy to PR this if it seems sensible.

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by Ehesp** [comment]
@Salakar how does this apply to v6?

**Comment by mikehardy** [comment]
for me - I'd take whatever Podfile you publish as an example and add a commented out line for GoogleIDFASupport (currently version 3.14.0) with a note it is optional for iOS audience measurement, along with a note in the analytics docs since analytics otherwise has no setup. But I'm just thinking out loud on what I actually did, and what would have prompted me to do it

**Comment by Salakar** [comment]
@Ehesp for v6 it'd be as @mikehardy mentioned, we can put this on `/oss/react-native-firebase/v6/analytics/ios` as an optional step?

@mikehardy if you're willing to send a docs PR up for this; this is the place for it to be added to for the new site: https://github.com/invertase/react-native-firebase/blob/master/docs/analytics/ios.md

**Comment by mikehardy** [comment]
that pointer to the spot for the new-new is helpful - I'm on it. thanks

**Comment by mikehardy** [comment]
Opened #2082 for v6 and https://github.com/invertase/react-native-firebase-docs/pull/180 for v5.x

Cheers guys

**Comment by Salakar** [comment]
Thanks again for sorting this and for both versions 👏 

Docs are live on both now:

 - **v5 (💩)**: https://rnfirebase.io/docs/v5.x.x/analytics/ios
 - **v6 (✨)**: https://dev.invertase.io/oss/react-native-firebase/v6/analytics/ios

**Comment by Salakar** [comment]
While on the topic, is there any reason we shouldn't just include this pod automatically as part of the new Analytics package? Does using IDFA stuff cause issues on the App store re approvals etc?

**Comment by mikehardy** [comment]
I believe it might. Using the IDFA means you start accessing Apple device identifiers, which may trigger rigorous review of privacy policies, GDPR compliance issues etc etc. It's another level of privacy concern that has lots of non-code tangent effects. I wouldn't do it by default, at the same time the page I linked talks about those effects, so I think the docs are nevertheless a good pointer to the relevant privacy concerns

**Comment by Salakar** [comment]
Right ok, thanks for clarifying, perhaps then; having it as an optional subspec then on the Podspec for Analytics would be best - we can at least manage the version internally if people opt in-to using IDFA via the subspec.

I'll re-open to track.

**Comment by Ehesp** [comment]
Also is it worth breaking out:

```ruby
  pod 'GoogleIDFASupport', '~> 3.14.0'
```

to be 

```ruby
  pod 'GoogleIDFASupport', '~> {{ ios.google_idfa }}'
```

or something from the config yaml?

**Comment by mikehardy** [comment]
I know nothing of this config yaml you speak of 😆 so that is fully up to you guys

**Comment by Salakar** [comment]
Gonna close this given that it's merged, we can re-iterate on the docs if needed but it's ok for now.

Thanks again @mikehardy 🎉
