### ISSUE TITLE
Multiple Warnings when importing react-native-firebase

### ISSUE THREAD

**Issue by Ethan0007** [invertase/react-native-firebase#2072]
Hi, 

I just follow the the given documents on how to install the react-native-firebase but when i started to import in the script -> import firebase from 'react-native-firebase' multiple warnings appears in the dev tools.

Thank you.

<img width="1440" alt="warnings" src="https://user-images.githubusercontent.com/12542052/56479065-c82a1400-64e5-11e9-96ee-4cbf1d532ea6.png">

**Comment by Salakar** [comment]
Hey @Ethan0007 - this is a known issue that can be ignored for now until v6. Please see the main issue here: https://github.com/invertase/react-native-firebase/issues/1446
