### ISSUE TITLE
Not receiving message when app is close on Android

### ISSUE THREAD

**Issue by chevulkar** [invertase/react-native-firebase#2074]
I followed the steps mentioned here.

Now, I'm receiving messages when app is in foreground via firebase.messaging().onMessage and in the background via a headless task I defined according to the same guide, but I don't receive messages when the app is closed

I am using one plus 6, where I even disabled the Battery optimise option for my phone, tried installing a signing build but none of it is working.

```
import firebase from 'react-native-firebase';
// Optional flow type
import type { RemoteMessage } from 'react-native-firebase';

export default async (message: RemoteMessage) => {

    const channel = new firebase.notifications.Android.Channel('channel-id', 'channel-Name', firebase.notifications.Android.Importance.Max)
    .setDescription('Description');
    firebase.notifications().android.createChannel(channel);

    const localNotification = new firebase.notifications.Notification()
    .setNotificationId(message.messageId)
    .setTitle("Title")
    .setSubtitle('Test')
    .setBody("Body")
    .setData(message.data)
    .android.setChannelId('channel-id')
    .android.setAutoCancel(false)
    .android.setPriority(firebase.notifications.Android.Priority.High);

  firebase.notifications().displayNotification(localNotification);

    return Promise.resolve();
}
```
Even added this on AndroidManifest.xml

```<service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />```

Am I missing anything on native side ?

**Comment by mikehardy** [comment]
It is my understanding for Android development that if your app is actually closed/killed, it is not running at all, so it may not receive messages period - it can't do anything.

The only way to then have it come alive again is to register for some Intent that the system will send. I am naive with regard to firebase messaging in particular but I would look in the docs for some form of BroadcastReceiver (to catch an Intent) that you are supposed to put in your AndroidManifest, hooked to Google Play services for messaging somehow. If you are able to look in Android Studio at the "merged" AndroidManifest and you see no receivers (either from your project or merged in from a library) then there's no mechanism to start the app in response to an Intent so it isn't able to do anything

**Comment by chevulkar** [comment]
Is there any working code that I can refer. I have searched across the internet tied different codes but nothing seems to work :(

**Comment by mikehardy** [comment]
Looks like it is almost impossible to do it reliably

https://github.com/firebase/quickstart-android/issues/41#issuecomment-387469761

**Comment by quarryman** [comment]
@chevulkar 

> I followed the steps mentioned here.
Can you provide a link to steps you followed?

**Comment by ricardoroth** [comment]
Looks like this is a very weird intended behavior:

https://github.com/firebase/quickstart-android/issues/368#issuecomment-424454844

**Comment by yudizvipulp** [comment]
This issue is not fixed yet, I need more help from community. It would be glad for me or others, if anyone found solution.

**Comment by michaelr524** [comment]
Looking for a solution as well.
