### ISSUE TITLE
🔥 cancelAllNotifications does NOT cancel repeating notifications that has been displayed already

### ISSUE THREAD

**Issue by strindhaug** [invertase/react-native-firebase#2075]
## Issue

Scheduled notifications that are repeating is not listed by `getScheduledNotifications` neither are they actually cancelled by `cancelAllNotifications` or `removeAllDeliveredNotifications`.

The only way to kill a repeating notification after it has been displayed once seems to be to explicitly canceling it by id using `cancelNotification` with an explicit id. 
But if you were stupid enough to test one using a random id and didn't take note what the id was, you'll presumably have to uninstall the app to kill it. (Not tested since I fortunately had a hardcoded id when I started experimenting; and I'm sure not going to try to test an unkillable notification on my personal phone)

Code to reproduce:

```js
/* eslint no-console: 0 */
import { Platform } from 'react-native';
import firebase from 'react-native-firebase';

const channelID = 'notification-channel';
const channelName = 'Notification Channel';

const MY_ID = 'repeatingNotificationId';

const setNotificationsConfig = () => {
  if (Platform.OS === 'android') {
    // Build the channel
    const channel = new firebase.notifications.Android.Channel(
      channelID,
      channelName,
      firebase.notifications.Android.Importance.Max,
    );
    // Create the channel
    firebase.notifications().android.createChannel(channel);
  }
  firebase.notifications().onNotificationOpened(notificationOpen => {
    console.log(notificationOpen.notification.data);
    // Do something
  });
};

const cancelNotifications = async () => {
  let scheduledNotifications = await firebase
    .notifications()
    .getScheduledNotifications();

  console.log('scheduled before the cancel', scheduledNotifications);
  // This does in fact NOT list repeating notifications that have been displayed already only future ones

  console.log('Supposedly removing all notifications');

  firebase.notifications().cancelAllNotifications();
  // This does in fact NOT cancel all notifications since repeating ones that have already been displayed will continue forever
  firebase.notifications().removeAllDeliveredNotifications();

  scheduledNotifications = await firebase
    .notifications()
    .getScheduledNotifications();

  console.log('after the cancel', scheduledNotifications);
};

const scheduleRepeatingMadness = () => {
  setNotificationsConfig();

  const id = MY_ID;
  // NOTE it's important to use a known id! If you use a random id you will not be able to kill it later
  // (though presumably uninstalling the app will do it)
  const date = new Date();
  date.setMinutes(date.getMinutes() + 1);
  const title = 'Notification every minute';
  const body = 'This will soon become very annoying';
  const repeatInterval = 'minute';

  firebase.notifications().cancelNotification(id);
  firebase.notifications().removeDeliveredNotification(id);

  // Build notification
  const notification = new firebase.notifications.Notification()
    .setNotificationId(id)
    .setTitle(title)
    .setBody(body)
    .setData({ id, something: 'whatever' })
    .android.setAutoCancel(true)
    .android.setChannelId(channelID)
    .android.setLargeIcon('ic_launcher_round')
    .android.setSmallIcon('ic_notification');

  // if (Platform.OS === 'android') {
  // }

  // Schedule notification
  firebase.notifications().scheduleNotification(notification, {
    fireDate: date.getTime(),
    repeatInterval,
  });
};

const endTheMadness = async () => {
  let scheduledNotifications = await firebase
    .notifications()
    .getScheduledNotifications();

  console.log('scheduled before ending the madness', scheduledNotifications);

  console.log('Cancel notifications by id');

  firebase.notifications().cancelNotification(MY_ID);
  firebase.notifications().removeDeliveredNotification(MY_ID);

  console.log(
    'Use cancelAllNotifications and removeAllDeliveredNotifications as well (just for good measure)',
  );
  firebase.notifications().cancelAllNotifications();
  firebase.notifications().removeAllDeliveredNotifications();

  scheduledNotifications = await firebase
    .notifications()
    .getScheduledNotifications();

  console.log('after ending the madness', scheduledNotifications);
};

export { scheduleRepeatingMadness, cancelNotifications, endTheMadness };

```
Put this code in a react native app and make three buttons for each of the exported methods.
If you call `scheduleRepeatingMadness` then minify/close the app and wait for the first notification, then try to call `cancelNotifications` it does nothing. And it lists no scheduled notifications before or after supposedly canceling the notification. Close the app and see the madness continues.

When you get sick of it call the `endTheMadness` function.

Unless you have a very different idea of what "all" means than everyone else; I would say this is buggy behavior. The method `cancelAllNotifications` should cancel *all* notifications no matter if they've already been displayed or not; and `getScheduledNotifications` should list every notification that will fire in the future no matter if they've been displayed before or not.

This issue or something similar has been reported before, but these have been just closed for inactivity without any resolution: https://github.com/invertase/react-native-firebase/issues/1798 https://github.com/invertase/react-native-firebase/issues/681

(Though if this is intended behavior, then the api is missing a few methods to list and kill repeating notifications even if you don't know the id; and also in this case the mentioned functions should be renamed so that they do not incorrectly imply that they does work on "all" notifications)

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [ ] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `ADD_SOMETHING_HERE` e.g. Xcode 10, Android Studio 3.2
- **`React Native` version:**
  - `0.57.8`
- **`React Native Firebase` library version:**
  - `5.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [x] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [ ] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by strindhaug** [comment]
Just realized another problem with this... I can work around the issue of not being able to cancel the notifications by carefully keeping track of what id's I've used and cancel them explicitly when needed. 

But if I want to have a toggle for

**Comment by zomars** [comment]
Did you managed to solve this @strindhaug ?
