### ISSUE TITLE
Cannot update Badge Icon at background/close (Android)

### ISSUE THREAD

**Issue by shinnachot** [invertase/react-native-firebase#2076]
Hi my problem is when i send notification from cloud messaging and my app is in background/close my badge app icon not update from now display 1 it's should be display 2 when have another notification
here is my code

package.json

> "react-native": "0.58.6",
    "react-native-calendars": "^1.22.0",
    "react-native-camera": "^2.0.1",
    "react-native-communications": "^2.2.1",
    "react-native-config": "^0.11.7",
    "react-native-drawer-menu": "^0.2.5",
    "react-native-dropdownalert": "^3.10.0",
    "react-native-elements": "^1.1.0",
    "react-native-fbsdk": "^0.8.0",
    "react-native-fetch": "^2.0.0",
    "react-native-firebase": "^5.3.1",

AndroidManifest.xml

> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.loanme">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
        <meta-data android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id"/>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService"
        android:enabled="true"
        android:exported="true">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />

        <activity
            android:launchMode="singleTop"
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

MainApplication.java

> import android.app.Application;
import com.facebook.CallbackManager;
import com.facebook.FacebookSdk;
import com.facebook.appevents.AppEventsLogger;
import com.facebook.react.ReactApplication;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
import co.apptailor.googlesignin.RNGoogleSigninPackage;
import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;
import io.invertase.firebase.auth.RNFirebaseAuthPackage;
import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

public class MainApplication extends Application implements ReactApplication {
  private static CallbackManager mCallbackManager = CallbackManager.Factory.create();
  protected static CallbackManager getCallbackManager() {
    return mCallbackManager;
  }
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new FBSDKPackage(mCallbackManager),
            new RNGoogleSigninPackage(),
            new RNFirebasePackage(),
            new RNFirebaseMessagingPackage(),
            new RNFirebaseAuthPackage(),
            new RNFirebaseNotificationsPackage(),
            new RNSendIntentPackage(),
            new ReactNativeWheelPickerPackage(),
            new RNCameraPackage(),
            new ImagePickerPackage(),
            new RCTPdfView(),
            new RNFetchBlobPackage(),
            new RNI18nPackage(),
            new ReactNativeConfigPackage(),
            new VectorIconsPackage(),
            new RNUnifiedContactsPackage()
      );
    }

    @Override
        protected String getJSMainModuleName() {
        return "index";
        }
    };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        SoLoader.init(this, /* native exopackage */ false);
    }
}

MainActivity.java

> public

 class MainActivity extends ReactActivity {
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
    }

    @Override
    protected String getMainComponentName() {
        return "loanme";
    }

    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
    }
}

build.gradle

> implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation "com.google.firebase:firebase-core:15.0.2"
    implementation "com.google.firebase:firebase-messaging:15.0.2"
    implementation "com.google.firebase:firebase-auth:16.2.1"
    implementation "me.leolin:ShortcutBadger:1.1.22@aar"

index.js
>import {AppRegistry} from 'react-native';
import App from './src/App';
import {name as appName} from './app.json';
import bgMessaging from './src/bgMessaging';
AppRegistry.registerComponent(appName, () => App);
AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => bgMessaging);

Home.js
>this.notificationListener = firebase.notifications().onNotification((notification: Notification) => {
            firebase.notifications().getBadge()
                .then( count => {
                        count++
                        firebase.notifications().setBadge(count)
                })
                .then(() => {
                    console.log('Doing great')
                })
                .catch( error => {
                    console.log('fail to count')
                })
        });
this.notificationDisplayedListener = firebase.notifications().onNotificationDisplayed((notification: Notification) => {
            firebase.notifications().getBadge()
            .then( count => {
                count++
                firebase.notifications().setBadge(count)
            })
            .then(() => {
                console.log('Doing great')
            })
            .catch( error => {
                console.log('fail to count')
            })
        });
        // Foreground
        this.notificationListener = firebase.notifications().onNotification(async (notification) => {
            console.log(notification)
            firebase.notifications().displayNotification(notification);
            const { title, body } = notification;
            console.log(`${title}, ${body}`)
            this.showAlert(title, body);
        });

what am i missing from these code it's working well when in foreground
and in background get notification on top working well too

**Comment by MinaFSedrak** [comment]
+1

**Comment by MinaFSedrak** [comment]
any update ?

**Comment by ThienMD** [comment]
same issue, please fix it.

**Comment by basir** [comment]
same issue , please fix it bro

**Comment by mikehardy** [comment]
@ThienMD  @basir I will happily merge your pull requests with proposed solutions

**Comment by sorin-f-wiredelta** [comment]
@mikehardy Is there a possiblity that this will be done at some point by one of the collaborators of this project ? thank you

**Comment by mikehardy** [comment]
Android badging in general is not an AOSP feature, so it is unreliable at best and is not supported everywhere, so I can't speak for the other collaborators but I see it as a waste of time - like pushing string. The documentation on the ShortcutBadger extension that react-native-firebase uses to even make a best effort is illuminating (or was for me). If there is a problem in how this module uses that package that causes it to not work in the background I could see updating it, but if it's just badging in general being terrible on Android, it's a nope from me

**Comment by aMarCruz** [comment]
I spent time trying to make that feature work in a reliable way in Androids, I even made [an extension](https://www.npmjs.com/package/react-native-shortcut-badge) for that. At the end of the day, the solution was to forget about it.

**Comment by mikehardy** [comment]
ok, that makes me think that I'm not crazy in my understanding of android badging in general then. So I'm going to close this issue but it's with the idea that badging in general is terrible but we're doing our best with the use of ShortcutBadger. If for some reason we are not calling the ShortcutBadger APIs correctly on background, then we can reopen. If it's just that ShortcutBadger doesn't work well - that's Android in general.
