### ISSUE TITLE
[v6] Crashlytics.h file not found error [ios]

### ISSUE THREAD

**Issue by RoliKatiyar** [invertase/react-native-firebase#2078]
getting below build error after integrating firebase crashlytics [V6] in react native app.

I have linked the ios dependencies, still the error shows.

/node_modules/@react-native-firebase/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsInitProvider.m:19:9: fatal error: 'Crashlytics.h' file not found

using xcode 9.3, iphone 8 simulator to build

**Comment by mikehardy** [comment]
If you are really using XCode 9.3 that is a fundamental problem. Apple won't even let you publish with that anymore. You should in general upgrade to latest XCode on release - current is 10.2 - try that, then post back

**Comment by zerazeru** [comment]
#2080

**Comment by mikehardy** [comment]
#2080 is a good reference for this one
