### ISSUE TITLE
Documentation Points to Wrong Versions of Pods

### ISSUE THREAD

**Issue by mikeborozdin** [invertase/react-native-firebase#2079]
When I go to the installation instruction of [Firestore for iOS](https://rnfirebase.io/docs/v5.x.x/firestore/ios) it'll have a wrong version of the Pod - `5.15.0`. If I follow those instructions on React Native Firebase of version `5.3.1` then the iOS app won't start. 

The solution to that is to use newer Pod versions - `5.20.1`. 

I would've happily submitted a PR to update the documentation, however it refers to variable - `ios.firebase.firestore` which I cannot modify.

**Comment by Ehesp** [comment]
Hey - those variables are from: https://github.com/invertase/react-native-firebase-docs/blob/v5.3.x/docs/_config.yaml (branch is for the version)

**Comment by mikeborozdin** [comment]
@Ehesp ,

Thanks! I've opened a [PR](https://github.com/invertase/react-native-firebase-docs/pull/179).

**Comment by Salakar** [comment]
@mikeborozdin thanks again for flagging this and sending a PR - I've merged it - site should be showing latest versions shortly.
