### ISSUE TITLE
Database warning

### ISSUE THREAD

**Issue by niros001** [invertase/react-native-firebase#208]
Hi i have a chat app but have some problems while trying to setState component with firebase  listener: 
that my warning that i got: 
`Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.`
I follow the docs and in componentWillMount i start the listener:
`this.itemsRef.orderByChild('date').startAt(lastDateSync).on('child_added', this.handleGetMessages.bind(this));`
and in componentWillUnmount i disconnected  from listener like that:
`this.itemsRef.off();`

* Another thing - when i close the screen and enter again i will get the warning 2 times per `setState` when i close and enter again i will get the warning 3 times and so on and so forth...

**Comment by Ehesp** [comment]
Can you show more code please. I don't think you're setting the ref correctly.

**Comment by niros001** [comment]
` this.itemsRef = FirebaseApp.database().ref(`${ENV_PREFIX}/chats/${uuid}/messages`);`

**Comment by niros001** [comment]
The ref is right, i can read/write without problems.

**Comment by Ehesp** [comment]
You need to do the following:

```
this.itemsRef = FirebaseApp.database().ref(...).orderByChild('date').startAt(lastDateSync);
this.itemsRef.on('child_added', this.handleGetMessages);
this.itemsRef.off('child_added', this.handleGetMessages);
```

Note that the `off` also has the same event & handler: `this.handleGetMessages`.

Also `this.handleGetMessages` is does not get bound when it's declared as the handler, as this creates a new instance of the function.

**Comment by niros001** [comment]
But i need to use `this` inside the handleGetMessages function...

**Comment by Ehesp** [comment]
Yeah so you need to bind it to the class, 2 options:

```
constructor() {
   super();
   this.handleGetMessages = this.handleGetMessages.bind(this);
}

handleGetMessages() {
  // this = class
}
```

```
handleGetMessages = () => {
  // this = class
};
```

**Comment by niros001** [comment]
Still same warning..
By the way it happen after i `setState` inside the `handleGetMessages`

**Comment by Ehesp** [comment]
Can we see your full class/component please? Take out anything unrelated. It's hard to say without seeing it.

**Comment by niros001** [comment]
```
    handleGetMessages(snap) {
        const messages = [...this.state.messages];
        let message = snap.val();
       message.position = message.phone ? message.phone === this.props.currentUser.phone ? 'right' : 'left' : 'center';
messages.push(message);
//Not relevant code
....
....

            this.setState({messages});
            AsyncStorage.setItem(this.MY_CHAT_MESSAGES_STORAGE, JSON.stringify(messages));
    }
```

**Comment by Ehesp** [comment]
@niros001 please provide the constructor/willMount & componentDidMount too.

**Comment by niros001** [comment]
```
constructor(props) {
        super(props);
        this.handleGetMessages = this.handleGetMessages.bind(this);
        const uuid = this.props.route.data.uuid;
        this.itemsRef = FirebaseApp.database().ref(`${ENV_PREFIX}/chats/${uuid}/messages`);
        this.MY_CHAT_MESSAGES_STORAGE = `@ChatMessages:${uuid}`;
        this.state = {
            chat: null,
            messages: [],
            loadEarlier: false,
            lastMessage: null,
        }
    }


    componentWillMount() {
        FirebaseApp.analytics().setCurrentScreen('ChatMessages');
        this._loadInitialState().then(()=> InteractionManager.runAfterInteractions(() => {
            let chat = this.state.chat;
            let lastDateSync = chat.lastDateSync;
            if(typeof lastDateSync === 'undefined')
                lastDateSync = null;

            // Get local messages
            this.getLocalMessages().then(()=> {
                this.itemsRef.orderByChild('date').startAt(lastDateSync).on('child_added', this.handleGetMessages)
            })
        }));

    }

    _loadInitialState = async () => {
        try {
            let value = await AsyncStorage.getItem(`@ChatsStorage:${this.props.route.data.uuid}`);
            if (value !== null){
                this.setState({chat: JSON.parse(value)});
                console.log(JSON.parse(value))
            } else {
                console.log('empty list')
            }
        } catch (error) {
            console.log(error)
        }
    };
```

**Comment by niros001** [comment]
I'am don't use` componentDidMount`

**Comment by niros001** [comment]
ok Solved by change `this.itemsRef` to `this.chatMessagesRef`.
The reason is that i used the name of `this.itemsRef` in the app but in other class that still open.

**Comment by Salakar** [comment]
@niros001 we can not help you until you provide us the full code for the component class you have the issue with - please stop pasting random snippets of it - it doesn't help us debug the issue. We need to see **ALL** of the class code.

**Comment by chrisbianca** [comment]
I'm going to close this as we've not had any further feedback.

@niros001 if you're still having an issue, please post the complete component class for us to be able help you.

**Comment by devarthurribeiro** [comment]
Same problem!

`import React, { Component } from 'react';
import { View, TouchableOpacity } from 'react-native';
import { List, ListItem, Text, Icon, Left, Body, Right } from 'native-base';

import firebase from '../api/firebase';

export default class NotificationList extends Component {
  constructor(props) {
    super(props);
    this.state = { notifications: [], color: '#fff' };
    setInterval(() => {
      this.setState({
        color: this.state.color === '#fff' ?
        'rgba(255, 255, 255, 0.51)' :
        '#fff',
      });
    }, 600);
    this.ref = firebase.database().ref(`notifications/${currentUser.uid}`);
    this.handleValue = this.handleValue.bind(this);
  }
  componentDidMount() {
    this.ref.on('value', this.handleValue);
  }
  handleValue(snapshot){
    const data = [];
    snapshot.forEach((item) => {
      data.unshift({ ...item.val(), key: item.key });
    });
    this.setState({
      notifications: data,
    });
  }
  componentWillUnmount() {
    this.ref.off();
    this.ref.off('value', this.handleValue);
  }
  removeNotification(nid) {
    firebase.database().ref(`notifications/${currentUser.uid}/${nid}`).remove();
  }
  getStyle(style) {
    switch (style) {
      case 'success':
      return {
        backgroundColor: 'rgba(0, 191, 165, 0.6)',
        borderRadius: 4,
        marginBottom: 8,
        height: 'auto',
        padding: 8,
      };
      break;
      case 'danger':
      return {
        backgroundColor: 'rgba(244, 67, 54, 0.7)',
        borderRadius: 4,
        marginBottom: 8,
        height: 'auto',
        padding: 8,
      };
      break;
      default:
      return {
        backgroundColor: 'rgba(0, 0, 0, 0.66)',
        borderRadius: 4,
        marginBottom: 8,
        height: 'auto',
        padding: 8,
      };
    }
  }
  render() {
    if (this.state.notifications.length < 1) {
      return null;
    }
    return (
      <View style={{ marginRight: 14, marginTop: 10 }}>
        <List style={{ width: '100%', margin: 0 }}>
          {this.state.notifications.map(item => (
            <ListItem key={item.key} style={this.getStyle(item.style)} icon>
              <Left>
                <TouchableOpacity
                  onPress={() => { this.removeNotification(item.key); }}
                  transparent
                  >
                    <Icon
                      style={{ fontSize: 26, color: this.state.color }}
                      name="ios-notifications"
                    />
                  </TouchableOpacity>
                </Left>
                <Body style={{ borderBottomWidth: 0, height: 'auto' }}>
                  <Text style={{ color: '#fff' }}>{item.text}</Text>
                </Body>
                <Right style={{ borderBottomWidth: 0 }}>
                  <TouchableOpacity
                    onPress={() => { this.removeNotification(item.key); }}
                    transparent
                    >
                      <Icon style={{ fontSize: 26, color: '#fff' }} name="close-circle" />
                    </TouchableOpacity>
                  </Right>
                </ListItem>
              ))}
            </List>
          </View>
        );
      }
    }
`

**Comment by chrisbianca** [comment]
@devarthurribeiro Does this happen just the once, or multiple times as reported previously?

Looking through your code, the only reason this might happen, is if your component received a `value` event as your component was about to unmount.  In this instance, `handleValue` may still be running after the component has unmounted, hence giving the warning.

It is just a warning, not an error, and is there to make sure you're not doing something completely invalid.  So, unless the warning starts multiplying (you get 2 warnings the second time the component has mounted) then I would not be too worried.

I get the same warning from time to time in my apps.

**Comment by devarthurribeiro** [comment]
@chrisbianca I get the warning in infinite loop, only after restarting the application it stops.

**Comment by devarthurribeiro** [comment]
I use this component to get the data and it does not show the same error. Already tried to use it, but the same warning happens.

`import React, { Component } from 'react';
import firebase from '../api/firebase';

class Firebase extends Component{
  constructor(props) {
    super(props);

    const { chield } = this.props;
    this.ref = firebase.database().ref(chield);

    this.state = {
      data: null,
      loading: true,
    }
  }
  componentWillMount() {
    const { method } = this.props;
    this.ref.on('value', (snapshot) => {
      var data = [];

      if (method === "single") {
        data =  { ...snapshot.val(), key: snapshot.key };
      }else {
        snapshot.forEach((item) => {
          const obj = { ...item.val(), key: item.key };
          data.push(obj);
        });
      }

      this.setState({
        data: data,
        loading: false,
      });

    });
  }
  componentWillUnmount() {
    this.ref.off();
  }
  render() {
    if (!this.props.children) {
      return null
    }
    return (
      this.props.children({
        data: this.state.data,
        loading: this.state.loading,
      }) || null
    )
  }
}

export default Firebase;
`

**Comment by DavitVosk** [comment]
the same problem here. Has anybody solved this problem?

**Comment by Ehesp** [comment]
@devarthurribeiro You're not `off`ing correctly. See https://invertase.io/react-native-firebase/#/modules/database?id=unmounted-components
