### ISSUE TITLE
Documentation Points to 5.xx instead of 5.3.3

### ISSUE THREAD

**Issue by mikeborozdin** [invertase/react-native-firebase#2085]
When I go to the [main website](https://rnfirebase.io/) and press [Documentation](https://rnfirebase.io/docs) it redirects me to the documentation for [5.x.x](https://rnfirebase.io/docs/v5.x.x/getting-started).

Should not it go to [5.3.x](https://rnfirebase.io/docs/v5.3.x/getting-started), given the issues described in #2079 ?

Although I addressed the issue for [5.3.x](https://rnfirebase.io/docs/v5.3.x/getting-started) users will still see wrong Pod versions because the website still points them to `5.x.x`.

There is an alternative which is to update to do a similar PR to `5.x.x`, but I'm not sure if it's a right option. `5.x.x` is a bit ambiguous given that we already have a fresh minor version - `5.3.`.

**Comment by Ehesp** [comment]
Fair comment, we'll get this changed + ensure it's added to the dropdown.

**Comment by Salakar** [comment]
Thanks, will sort this afternoon 🙈

**Comment by Salakar** [comment]
Right, I've merged v5.3.x into v5.x.x - there should only be docs separation between Major versions, otherwise it gets out of hand fast.

Where was v5.3.x being linked from, was it us - if so the links will need editing to v5.x.x.
