### ISSUE TITLE
Image Upload with react-native-firebase

### ISSUE THREAD

**Issue by sardarusama41062** [invertase/react-native-firebase#2087]
Hello everyone, I'm new to firebase and react-native, and having a problem in uploading an image to firebase.
I have done all the things as specified in the documentation or any other post on this issue but could not solve the problem.
`ImagePicker.showImagePicker(null, (response) => {
      console.log('Response = ', response);
      if (response.didCancel) {
        console.log('User cancelled image picker');
      } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      } else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      } else {
        this.setState({
          avatar: response.uri,
        });
        // let mime = 'image/jpg'
        const imgRef = firebase.storage().ref()
        imgRef.putFile(response.uri)
          .then((res) => {
            console.log(res)
          }).catch((error) => console.log(error))
      }
    })`

![Capture](https://user-images.githubusercontent.com/35162581/56900556-88e46000-6aaf-11e9-91b0-97b44f191684.PNG)

I'm using windows 10 and creating an android app for practice.

Any help will be appriciated, Thanks

**Comment by AlcuinGuest** [comment]
@sardarusama41062 This should work:

```
  ImagePicker.showImagePicker(options, response => {
      if (response.didCancel) {
        // Nothing
      } else if (response.error) {
        NotificationService.open(response.error, 'error');
      } else {
        const { uri } = response;
        const uploadUri = Platform.OS === 'ios' ? uri.replace('file://', '') : uri;
        return firebase.storage()
         .ref(`photos/newPhotoId`)
         .putFile(uploadUri)
         .then(file => file.ref)
         .catch(error => error);
      }
    });
```
