### ISSUE TITLE
🔥Firebase ID token has no "kid" claim

### ISSUE THREAD

**Issue by holtc** [invertase/react-native-firebase#2089]
## Issue
I am listening to auth state changes using `firebase.auth().onAuthStateChanged(...)`, and I am then getting the id token using `const idToken = await user.getIdToken()`.  I am then sending this token to my server to validate the user and get additional information.  However, when validating on my server, I get the following error: ` Firebase ID token has no "kid" claim.`.  Why is this happening?  In my app, I am using `"react-native-firebase": "^4.2.0"`, and in the server, I am using `"firebase-admin": "^5.13.1"`.  For comparison, I am using `"firebase": "^5.3.1"` in a web app, and the tokens validate fine.  Are the tokens generated by `react-native-firebase` incompatible with `firebase-admin`, or do I just need to update `react-native-firebase`?

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App' do
  pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'RCTImage' # for react-native-svg
  ]

  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'

  pod 'Intercom'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
end


# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [x] MacOS, version: `10.14.4`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Xcode 10.2.1` e.g. Xcode 10, Android Studio 3.2
- **`React Native` version:**
  - `0.55.4`
- **`React Native Firebase` library version:**
  - `^4.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [x] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by Jigneshmayani90** [comment]
Hi can you provide what solution you get related to this. As i am facing the same issue.

**Comment by Johnathon332** [comment]
+1 on this, what is the resolution

**Comment by mikehardy** [comment]
https://stackoverflow.com/questions/37358105/firebase-3-0-tokens-error-firebase-auth-id-token-has-no-kid-claim

Likely trying to use auth emulator tokens, which do not have the full token contents expected - if people are seeing this in 2024 (note the last answer on that link...)
