### ISSUE TITLE
FCM: notification gets to the device, getting warning `messaging_notification_received` with no listeners registered.

### ISSUE THREAD

**Issue by DavideValdo** [invertase/react-native-firebase#209]
Testing out FCM from the Notifications panel in Firebase.
Notification is delivered to my iPhone, but all I'm getting is that warning.

This logs the message object correctly:
```
    firebase.messaging().onMessage((message) => {
      console.debug(message);
    })
```

Any hints?

react-native-cli: 2.0.1
react-native: 0.45.1
yarn: v0.24.5
react-native-firebase: 2.0.0
XCode: 8.3.3
iOS 10.3.2

**Comment by havaliza** [comment]
What you mentioned makes sense with what I described in issue #204

**Comment by DavideValdo** [comment]
Thank you.
I did try your workaround, but it seems like it's a different problem.
I now get an additional message in console from infoLog.js:

```
infoLog.js:17 Failed to symbolicate warning, "Sending `messaging_notification_received` with no listeners registered.": TypeError: Network request failed
    at XMLHttpRequest.xhr.onerror (fetch.js:441)
    at XMLHttpRequest.dispatchEvent (event-target.js:172)
    at XMLHttpRequest.setReadyState (XMLHttpRequest.js:546)
    at XMLHttpRequest.__didCompleteResponse (XMLHttpRequest.js:381)
    at XMLHttpRequest.js:485
    at RCTDeviceEventEmitter.emit (EventEmitter.js:181)
    at MessageQueue.__callFunction (MessageQueue.js:245)
    at MessageQueue.js:101
    at MessageQueue.__guard (MessageQueue.js:213)
    at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:100)
```

**Comment by DavideValdo** [comment]
**After a clean install, I can get the alert when app is in the background.**
For Android, I was expecting to get the alert automatically when app is in the foreground as well.
Is this expected behaviour?

**Comment by Ehesp** [comment]
@DavideValdo the notification wont show when the app is open, which is intended. Currently there's a work around in place by putting `show_in_foreground: true` in the payload.

**Comment by DavideValdo** [comment]
If this is the only way, to accomplish chatroom functionality I would need to:

1. Set flags in Firebase that signal whether the room screen is in foreground
2. Through Cloud Functions, when I send the notification I should add `show_in_foreground: true` only if those flag are true

**Comment by DavideValdo** [comment]
Seems like a different issue anyway, closing this and opened #223

**Comment by Harryki** [comment]
i have not known this issue here, my mystery solved
