### ISSUE TITLE
The Android app is reporting an error!

### ISSUE THREAD

**Issue by sliverRing** [invertase/react-native-firebase#2093]
When I was using this plugin, I made an error in building the Android app. I reported the error as follows:
Failed to notify dependency resolution listener.
> The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[16.0.5,16.0.5]], but resolves to 16.4.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
> The library com.google.firebase:firebase-analytics is being requested by various other libraries at [[16.0.6,16.0.6]], but resolves to 16.4.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

**Comment by mikehardy** [comment]
So, you have incompatible google play component versions, as the error indicates. Update them all to current https://firebase.google.com/support/release-notes/android, get your react-native to 0.59.3+ and react-native-firebase to 5.3.1 and it works
