### ISSUE TITLE
I have encountered this error and hope to be solved.

### ISSUE THREAD

**Issue by sliverRing** [invertase/react-native-firebase#2094]
I followed the official documentation step by step, but I encountered this error.
**Error is as follows**
FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':app:checkDebugClasspath' property 'compileClasspath' during up-to-date check.
> The library com.google.android.gms:play-services-basement is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 16.2.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
12 actionable tasks: 1 executed, 11 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by sliverRing** [comment]
This is the error code：
`FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':app:checkDebugClasspath' property 'compileClasspath' during up-to-date check.
> The library com.google.android.gms:play-services-basement is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 16.2.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org`

**Comment by sliverRing** [comment]
`
dependencies {
	implementation project(':react-native-firebase')
	implementation project(':@react-native-community_async-storage')
	implementation project(':react-native-vector-icons')
	implementation project(':react-native-gesture-handler')
	implementation fileTree(dir: "libs", include: ["*.jar"])
	implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation  project(path: ':faceplatform-ui')
    implementation project(':react-native-camera')
    implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation 'com.google.firebase:firebase-core:16.0.1'
}
`

**Comment by mikehardy** [comment]
you can google how to run a deps report in gradle, and that will show you who is requesting the old version of whatever library is causing the error. You can also look at the ext {} block for gradle in the react-native-firebase starter and imitate that style. I'd recommend starting with the starter project to make sure it runs, then slowly integrating it into your app exactly like the starter has it

**Comment by sliverRing** [comment]
> you can google how to run a deps report in gradle, and that will show you who is requesting the old version of whatever library is causing the error. You can also look at the ext {} block for gradle in the react-native-firebase starter and imitate that style. I'd recommend starting with the starter project to make sure it runs, then slowly integrating it into your app exactly like the starter has it

But the project simply couldn't run. I found out that it was a problem with the Google service version during debugging. One of my plugins relies on 15.0.1, but the react-native-firebase requires 16.0.1, which causes the project to not find 16.0.1 when it is running.

**Comment by mikehardy** [comment]
That's a bug in the other library. They must respect a version specified in the ext {} block of gradle, to avoid these problems

**Comment by sorin-f-wiredelta** [comment]
@mikehardy I just checked the react-native-firebase starter project and it doesn't have the root ext {} as you are mentioning.

**Comment by mikehardy** [comment]
Oh sorry - here's an example then - all the example apps built from recent templates have them, and all libraries *should* support the style https://github.com/react-native-community/react-native-device-info/blob/master/example/android/build.gradle#L4
