### ISSUE TITLE
android functions httpsCallable doesn't resolve when receiving big amount of data

### ISSUE THREAD

**Issue by EvolveYourMind** [invertase/react-native-firebase#2097]
Hello.
I have a problem with the firebase.functions().httpsCallable function on android (haven't tested for ios).
Basically, my promise doesn't complete if it receives a big amount of data as a response (verified with 100KB, probably happens with less).

If I call the firebase function through Postman I receive a correct response.
On react native side the promise never completes.

How to reproduce

Clone https://github.com/invertase/react-native-firebase-starter
Put the following code in App.js (the emulator ip is relative to the android emulator if you use it)

result
"got response" doesn't get logged (after pressing the button many times it gets a couple of responses).
```
import React from 'react';
import { View, Button, Text } from 'react-native';
import firebase from 'react-native-firebase';

firebase.functions().useFunctionsEmulator("http://10.0.2.2:5000");

async function apicall(funcname, data) {
  try {
    console.log("calling");
    const response = await firebase.functions().httpsCallable(funcname)(data);
    console.log("got response");
    return response;
  } catch(error) {
    console.error(error);
  }
  return ["fail"];
}

export default function () {
  const [bar, setBar] = React.useState([]);
  
  async function refresh() {
    setBar([]);
    setBar(await apicall("foo"));
  }

  return (
    <View>
      <Button onPress={refresh} title={"press here"} />
      <Text>{JSON.stringify(bar)}</Text>     
    </View>
  );
} 
```

Sample Firebase Function code
```
exports.foo = functions.https.onCall(async (data, context) => {
    let a = [];
    for(let i = 0; i < 30000; i++) 
	a.push(i)
    return a;
})
```
EDIT:
Versions:
"react": "16.8.3",
"react-native": "0.59.3",
"react-native-firebase": "^5.3.1"

**Comment by Ehesp** [comment]
Have you tried:

```js
try {
  const response = await firebase.functions().httpsCallable(funcname)(data);
  return response;
} catch (e) {
  console.error(e);
}
```

There could be an error you're not capturing

**Comment by EvolveYourMind** [comment]
@Ehesp tried that too, nothing happens

**Comment by Ehesp** [comment]
@EvolveYourMind ok thanks, could you edit the issue to include your versions and we'll take a look.

**Comment by ShaMan123** [comment]
Hi, crashing in.
Before raising any related input, I noticed that when calling `httpsCallable` in small time diffs it drops some calls (is there any cache mechanism?).

I have something similar/related happening when using `httpsCallable`.
Just started looking into it yesterday, glad I saw this issue.

**When the function receives a large amount of data it blocks the main thread and the app is unresponsive for 5-10 seconds.**
```
05-02 12:12:37.199 16919-17647/io.autodidact D/RNFirebaseFunctions: function:call:input:getItems:{items=true, query={limitToFirst=25.0}, scale=360.0}
05-02 12:12:37.239 16919-17102/io.autodidact W/DynamiteModule: Local module descriptor class for providerinstaller not found.
...
...
05-02 12:12:54.529 16919-16919/io.autodidact D/RNFirebaseFunctions: function:call:onSuccess:getItems
05-02 12:12:54.529 16919-16919/io.autodidact D/RNFirebaseFunctions: function:call:onSuccess:result:type:getItems:java.util.HashMap
...
05-02 12:13:00.329 16919-16919/io.autodidact I/Choreographer: Skipped 346 frames!  The application may be doing too much work on its main thread.

```

After some investigation I found the source of the problem to be `io.invertase.firebase.Utils.mapPutValue`  in [RNFirebaseFunctions.java](https://github.com/invertase/react-native-firebase/blob/v5.x.x/android/src/main/java/io/invertase/firebase/functions/RNFirebaseFunctions.java#L119):
```java
import io.invertase.firebase.Utils;

...
Log.d(
TAG,
"function:call:onSuccess:result:data:" + name + ":" + (result != null ? result.toString() : "null")
);

Utils.mapPutValue(DATA_KEY, result, map); 
promise.resolve(map);
```

### Test A:
```java
import io.invertase.firebase.Utils;

...
/*
Log.d(
TAG,
"function:call:onSuccess:result:data:" + name + ":" + (result != null ? result.toString() : "null")
);
*/

map.putString("result",result.toString());     //Utils.mapPutValue(DATA_KEY, result, map); 
promise.resolve(map);
```

### Result: 
```
I/Choreographer: Skipped 79 frames!  The application may be doing too much work on its main thread.
```
Much better but still not good enough.

### Test B:
Sending an empty map.
```java
import io.invertase.firebase.Utils;

...
//Utils.mapPutValue(DATA_KEY, result, map); 
promise.resolve(map);
```
### Result:
no frames dropped.

**I think this is a regression because I don't recall having this problem before upgrading to v5.**


Versions:
    "react": "^16.8.5",
    "react-native": "^0.57.4",
    "react-native-firebase": "^5.2.3",

**Comment by EvolveYourMind** [comment]
I've written a simple js client-side workaround that doesn't require a downgrade (it can be improved)
```
import firebase from 'react-native-firebase';

const FB_FUNCTIONS_HOST = 'http://10.0.2.2:5000'; // or your real project functions endpoint
const FB_PROJECT_REGION = '/project-name/us-central1/';

export function httpsCallable(functionName) {
    return async data => {
        if(data === undefined || data === null) {
            data = {};
        }
        return fetch(
            `${FB_FUNCTIONS_EMULATOR_HOST}${FB_PROJECT_REGION}${functionName}`
            , {
                method: 'POST',
                headers: {
                    'Authorization': 'Bearer ' + await firebase.auth().currentUser.getIdToken(),
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ data })
            }
        ).then(res => res.json())
       .then(json => ({ data: json.result }));
    }
}
```

**Comment by ShaMan123** [comment]
Thanks!

**Comment by EvolveYourMind** [comment]
My bad, the workaround still has the same issue, but at least it resolves with *Network request failed*.

**Comment by ShaMan123** [comment]
so it's unreliable in it's core?

**Comment by Salakar** [comment]
@ShaMan123 re the logging, this has been removed in v6: https://github.com/invertase/react-native-firebase/blob/master/packages/functions/android/src/main/java/io/invertase/firebase/functions/ReactNativeFirebaseFunctionsModule.java

**Comment by ShaMan123** [comment]
@Salakar is `RCTConvertFirebase.mapPutValue` the same as v5 `Utils.mapPutValue`?

**Comment by Salakar** [comment]
@ShaMan123 pretty much: https://github.com/invertase/react-native-firebase/blob/master/packages/app/android/src/main/java/io/invertase/firebase/common/RCTConvertFirebase.java#L126

Not sure if there are any improvements to be had there for large data other than serialising in a thread or something, which adds it's own complications.

I'm working on threaded serialisation conversion utils for Firestore on Android - pretty much the same issue there, transforming a large amount of data will slow it right down. Would love some advice if anyone is more familiar on handling threads etc on android.

**Comment by ShaMan123** [comment]
Would love to help but I'm not familiar enough either.
Thanks for the answers.
react-native-firebase is a fantastic job.

**Comment by ShaMan123** [comment]
I have a strange hacky idea if threading won't provide the answer.
Something like FlatList but for pieces of data instead of UI, thus not needing to serialize all at once and not seriously degrading performance.

**Comment by Salakar** [comment]
No problems, I'll get through the same issue on Firestore and apply lessons learnt there to both Functions & Database - I've already applied some threaded serialisation to database and is working well, just needs a re-think on how it can be used in not just Database: A before (left) and after (right) preview of UI framerates when I applied to thread - so it's definitely the way to go

**Comment by Salakar** [comment]
If you feel like experimenting, here's the DB ones for reference:

https://github.com/invertase/react-native-firebase/blob/v5.x.x/android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabaseReference.java#L583
https://github.com/invertase/react-native-firebase/blob/v5.x.x/android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabaseReference.java#L163

**Comment by ShaMan123** [comment]
saw [this](https://github.com/react-native-community/react-native-async-storage/blob/master/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java#L51) - form async-storage

**Comment by Salakar** [comment]
Figured this out the proper way to do this, will push something up for v5 next week hopefully if I have time. This has been applied to v6 though.
