### ISSUE TITLE
'Firebase/Firebase.h' file not found file . not found

### ISSUE THREAD

**Issue by irohitb** [invertase/react-native-firebase#2098]
🔥

## Issue

I followed all the instructions mentioned in your documentation to get started with using react-native-firebase for iOS 

but whenever try to build the project in xcode, i get **`#import <Firebase/Firebase.h>`** file . not found

 Here is the screenshot of my googleService-info-plist

<img width="414" alt="Screenshot 2019-05-02 at 8 31 53 AM" src="https://user-images.githubusercontent.com/32276134/57054846-c36b1a00-6cb4-11e9-8508-496ee7d1afaa.png">

This issue happens at 

<img width="973" alt="Screenshot 2019-05-02 at 8 38 23 AM" src="https://user-images.githubusercontent.com/32276134/57054996-d2060100-6cb5-11e9-814c-d7de35042064.png">

 Note:  Check file path above
---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```
# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'entreClientwithoutExpo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for entreClientwithoutExpo
   pod 'Firebase/Core'
   pod 'Firebase/Auth', '~> 5.20.1'

  target 'entreClientwithoutExpo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  end

  target 'entreClientwithoutExpoTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

#### `AppDelegate.m`:

```
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"
#import <Firebase.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"entreClientwithoutExpo"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [UIColor blackColor];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

@end
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [X] iOS
  - [ ] Android
  - [X] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [X ] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Xcode 10`
- **`React Native` version:**
  - `0.58.6`
- **`React Native Firebase` library version:**
  - `5.2.3`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [X] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [ ] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by mikehardy** [comment]
open the xcworkspace, not the xcproject

Note: this is a guess. if I'm correct, I want a 🍺

**Comment by irohitb** [comment]
@mikehardy  Nope! Tried that same error

**Comment by mikehardy** [comment]
strange, this (and your screenshot) is exactly what it looks like when you open the project instead of the workspace on a Pod project

**Comment by irohitb** [comment]
@mikehardy Can you please go through the GIF and confirm if I am actually opening xcworkspace?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32276134/57099092-403fd780-6d39-11e9-900e-aea6008c3108.gif)

**Comment by mikehardy** [comment]
Looked like it to me, yes. Maybe the pods are right and workspace is right but you did not do the link step?
For extra verification you can always clone the react-native-firebase starter, follow it's readme and just verify that we are not both losing our minds :-)

**Comment by irohitb** [comment]
@mikehardy I am doing a manual integration but this what I did 
1. Cloned the repo (starter kit) 
2. compared the pod configuration 
3. compared the AppDelegate.m 
4. Matched the framework Path 
5. Matched the header Search Path 

If it makes any difference, this is how they look now 
<img width="1440" alt="Screenshot 2019-05-03 at 7 44 52 PM" src="https://user-images.githubusercontent.com/32276134/57143218-02e05600-6ddc-11e9-873d-1eead296f153.png">
![Uploading Screenshot 2019-05-03 at 7.44.57 PM.png…]()

Still no luck

**Comment by mikehardy** [comment]
The clue here is manual integration vs link - there must be something missing either in the docs or in your execution of the docs...I'm not sure where the code is that executes on a link, but it's in this repo somewhere and if you study what it does, that might lead to success?

**Comment by mikehardy** [comment]
you posted elsewhere you are having firebase auth problems on ios, indicating your build is working. please update status.

**Comment by mikehardy** [comment]
If at all possible, after taking support time in an open source community - you should resolve an issue with details on resolution to help future people

**Comment by irohitb** [comment]
@mikehardy I wouldv'e marked the question closed and definitely helped out the others having the same problem but frankly, I just moved back to commits and started everything from the beginning (the first time I setup the project) 
I am still not sure what caused it.. But still thanks for helping out. 

I owe you a beer :)

**Comment by matthieunelmes** [comment]
I'm having exactly the same issue Pods and Sans-Pods. 

Tried a fresh repo, manual linking, react-native link, fresh vanilla react-native init project and integrating. No dice. Might just abandon this repo and find another. The docs are incomplete and I've wasted so much time already.

A lot of comments mention Seach Header Paths, $(inherited) but none of these work.

**Comment by mikehardy** [comment]
This is an old issue. Post a new issue with complete docs.
Also make sure to open the xcworkspace, not the xcproject when using Pods
The docs are actually astoundingly complete, and this is the semi-official repository for Firebase, says Google, for a reason - it works. 
Final try, check out the rn-firebase-starter repo to get the starter app - it also works. From there you can see what you need to do
