### ISSUE TITLE
getToken is forcing token refresh

### ISSUE THREAD

**Issue by gabrielmoreira** [invertase/react-native-firebase#21]
By default, firebase `currentUser.getToken()` does not refresh the token until it has expired. However, the react-native-firebase project is always forcing a new token.

https://firebase.google.com/docs/reference/js/firebase.User?hl=pt-br#getToken

**Comment by Ehesp** [comment]
Hey, thanks for reporting. Which platform(s) have you seen this on? We'll debug when we can however knowing if it only happens on a specific platform will help :)

**Comment by gabrielmoreira** [comment]
I just looked at your source code. Android native bridge.


Em 25 de mar de 2017 5:20 PM, "Elliot Hesp" <notifications@github.com>
escreveu:

Hey, thanks for reporting. Which platform(s) have you seen this on? We'll
debug when we can however knowing if it only happens on a specific platform
will help :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/invertase/react-native-firebase/issues/21#issuecomment-289237001>,
or mute the thread

**Comment by Salakar** [comment]
@gabrielmoreira ah ye, well spotted, not sure how that got there, will change

**Comment by Salakar** [comment]
Also looks like ios ignores the option completely, I'll sort both - thanks for the report.
