### ISSUE TITLE
[V6] official launch date

### ISSUE THREAD

**Issue by RoliKatiyar** [invertase/react-native-firebase#2100]
We would like to know the official launch date of v6.
As currently, we know crashlytics is ready to use, but we are using cloud messaging also in our app. So, we would like to know when the official version release (tentative date) including both cloud messaging and crashlytics features.

**Comment by Ehesp** [comment]
Hello, the current roadmap looks something like:

- [ ] Analytics
- [ ] Analytics
- [ ] Analytics
- [ ] Analytics
- [ ] Analytics
- [ ] Analytics

**Comment by Ehesp** [comment]
Hello,

Next up on the list is moving Auth over to v6 (as it's already fully tested, just needs some updates to use the better listeners/setup). 

We'd expect Messaging to be complete towards the end of July. It could be sooner, depending on how the ML Kit implementation goes.
