### ISSUE TITLE
Firebase Error: You must enable this service in the console

### ISSUE THREAD

**Issue by irohitb** [invertase/react-native-firebase#2105]
## Issue

Hey, This might be a long post but in general these are more or less instructions of what I have done 

<strong> My Problem in General: </strong> 
On signup request, I am getting the following error (I am trying it on iOS)  
**This operation is not allowed. You must enable this service in the console.**

There is an [active bounty for the same on stackoverflow as well,](https://stackoverflow.com/questions/55932931/firebase-error-you-must-enable-this-service-in-the-console) In case someone also encounters this problem, You should also check in SFO (in case someone solved there first) 

Stackoverflow also happens to be much detailed 

```
import firebase from "react-native-firebase";

export const signup = (fullName, username, email, password) => {
  console.log(`Full name: ${fullName} UserName: ${username} email: ${email} password: ${password}`)
  return function(dispatch) {
    dispatch({ type: PROFILE_LOADING });
    firebase
      .auth()
      .createUserWithEmailAndPassword(email, password)
      .then(user => {
        console.log("This is user from signup", signup);
        return dispatch({
          type: PROFILE_SUCCESS,
          payload: user
        });
      })
      .catch(error => {
        console.error(error)
        return dispatch({
          type: PROFILE_ERROR,
          payload: error.data
        });
      });
  };
};

```

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'entreClientwithoutExpo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for entreClientwithoutExpo
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'entreClientwithoutExpo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  end

  target 'entreClientwithoutExpoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"entreClientwithoutExpo"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [UIColor blackColor];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

@end

```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [X ] iOS
  - [ ] Android
  - [ X] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [ X] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Xcode 10` e.g. Xcode 10, Android Studio 3.2
- **`React Native` version:**
  - `0.58.6`
- **`React Native Firebase` library version:**
  - `^5.2.3`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [X ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [ ] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by mikehardy** [comment]
One of the comments has your answer

> If I understand it correctly, you're trying to run this on a simulator, firebase doesn't allow you to login on a simulator(I have had a similar problem on android emulator). 

For auth on the simulator to work you have to set up test numbers/codes. This is documented in firebase SDK auth docs. Web working while Native SDKs don't work means you are likely configured correctly on the server in general, but you haven't read the native SDK docs thoroughly enough.

Also, you have another pending issue here about builds and it seems iOS is working for now. Have you closed that issue?

**Comment by irohitb** [comment]
@mikehardy  Can you help me out with the link?

**Comment by irohitb** [comment]
@mikehardy I went through the SDK Docs and web and I don't see any mention of using it in simulator. Can you share what you are referencing to? 
Second, After the following the installation instruction, when I run the app 
<img width="1440" alt="Screenshot 2019-05-04 at 7 49 48 PM" src="https://user-images.githubusercontent.com/32276134/57180396-d98bfc80-6ea5-11e9-8e30-a5e47b0b9e75.png">
I was expecting my app to verify but it appears my app isn't being verified as well.

**Comment by mikehardy** [comment]
https://firebase.google.com/docs/auth/web/phone-auth#test-with-whitelisted-phone-numbers
