### ISSUE TITLE
🔥Data only remote push notification triggers app start on Android when app is killed

### ISSUE THREAD

**Issue by clfristoe** [invertase/react-native-firebase#2119]
## Issue

Describe your issue here

I am using react-native-navigation and react-native-firebase to handle data-only push notifications. The notifications trigger and handle properly for the foreground and background cases. However, when the app is killed and a data-only notification is sent, the app opens automatically.

I have it set up, so when the app is in the background or killed, when push is sent, the app creates and displays a local notification that the user can tap on to open the app. This works as expected when the app is in the background, but when the app is closed it starts up the app UI and displays the notification at the same time.

---

#### `ios/Podfile`:

- [X ] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

![image](https://user-images.githubusercontent.com/15655814/57332311-20fdcd00-70e0-11e9-9a7a-c355127ccc8c.png)

#### `android/app/build.gradle`:

![image](https://user-images.githubusercontent.com/15655814/57332697-e2b4dd80-70e0-11e9-909d-c0221891f996.png)

#### `android/settings.gradle`:

![image](https://user-images.githubusercontent.com/15655814/57332635-c1ec8800-70e0-11e9-9e5f-0e8d59833c0d.png)

#### `MainApplication.java`:

![image](https://user-images.githubusercontent.com/15655814/57332728-f5c7ad80-70e0-11e9-89ab-68d97e026950.png)

#### `AndroidManifest.xml`:

![image](https://user-images.githubusercontent.com/15655814/57332742-fe1fe880-70e0-11e9-8901-97eac94a7c30.png)

---

## Environment

**`react-native info` output:**

```
 React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 32.45 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 27, 28
        Build Tools: 28.0.2, 28.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.5 => 0.57.5 

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `N`

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by clfristoe** [comment]
@Salakar Do you have any idea why this would be happening? I tried a different library and experience the same issue with data-only payloads. I'm wondering if this library is somehow starting the app via headlessJS. Removing those lines prevent the app from start or the headlessJS script running to create a local notification, but that's as far as my understanding takes me.

**Comment by mikehardy** [comment]
@clfristoe does this happen for you on emulators or just real devices? which APIs have you observed it? I've seen notification taps relaunch the app (#1749) but I'm not sure that is higher APIs. I'm hoping to make a messaging demo in https://github.com/mikehardy/rnfbdemo ideally to surface issues like this once we have a reproducible chunk of react-native-firebase code that triggers it and a known API level where it should show up

**Comment by clfristoe** [comment]
@mikehardy this was happening to me on emulators and physical devices. It has to do with the way our app is set up, specifically the startApp functionality. I was able to solve the issue, but it required me to "catch" the app before it launched the UI. I'm using two notification libraries, this one and react-native-push-notification-ce (for iOS and Android) as well as react-native-navigation which I believe may be part of the issue. According to the other library, this is an intended result of a data-only push notification being sent: `If your Android app is not running when a silent notification is received then this library will start it. It will be started in the background however, and if the OS starts your app in this way it will not start the react-native lifecycle. This means that if your notification delivery code relies on the react-native lifecycle then it will not get invoked in this situation. You need to structure your app in such a way that PushNotification.configure gets called as a side effect of merely importing the root index.android.js file.`: https://github.com/calcazar/react-native-push-notification-CE/blob/master/trouble-shooting.md. I hope this helps...

**Comment by mikehardy** [comment]
Fascinating! Thanks so much for the extra detail, that may help me in my demonstration efforts for future users, and in my own app. Glad you are working well now

**Comment by clfristoe** [comment]
Good luck in your push notification endeavors!
