### ISSUE TITLE
firebase with code push integration

### ISSUE THREAD

**Issue by upputurisairaja** [invertase/react-native-firebase#2120]
For feature requests please visit our [Feature Request Board](https://invertase.io/oss/react-native-firebase/feedback/).

**Comment by upputurisairaja** [comment]
> Task :react-native-code-push:compileDebugAidl FAILED
Dependency resolved to an incompatible version: Dependency(fromArtifactVersion=ArtifactVersion(groupId=com.nimbusds, artifactId=n
imbus-jose-jwt, version=5.1), toArtifact=Artifact(groupId=net.minidev, artifactId=json-smart), toArtifactVersionString=[1.3.1,2.3
])

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture fingerprint of input files for task ':react-native-code-push:compileDebugAidl' property 'importDirs' during up-
to-date check.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.3.1
  ,2.3]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
  
  Dependency failing: com.nimbusds:nimbus-jose-jwt:5.1 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2
  .3.
  
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends on project 'react' which depends onto com.nimbusds:nimbus-jose-jwt@5.1
  
  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.

**Comment by mikehardy** [comment]
there are other bugs related to this I believe - something about the strict version checker for google play going haywire when combined with ranges, it checks for the exact string that is the range, instead of the values in between it. Probably have to disable the android compatibility version checker - search around for related issues in this tracker

**Comment by upputurisairaja** [comment]
I got resolved mine. I have followed react-native-firebase starter. And i made a changes on build.gradle file 
FROM 
ext{
      buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
}

TO

 ext {
        buildToolsVersion = "27.0.0"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 26
        supportLibVersion = "28.0.0"
    }.

And it solved.

**Comment by mikehardy** [comment]
That is unexpected and not a great thing though. Can you confirm toggling just that setting - buildToolsVersion - between 27 and 28 causes it to break or to work, respectively?

**Comment by upputurisairaja** [comment]
I confirm. By changing  to targetSdkVersion = 26, buildToolsVersion = "28.0.3. I have checked all other scenarios. But this is the culprit.

**Comment by mikehardy** [comment]
That is so strange. Thank you very much for double-checking - this issue hits a lot of people (and I'm about to integrate code-push myself!) so knowing all the little ins and outs of it is useful

**Comment by wojryba** [comment]
Changing versions in `build.gradle` didn't help me. What did work adding the line:
`com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true`
in `android/app/build.gradle` 
At the very bottom of file, after `apply plugin: 'com.google.gms.google-services'`

**Comment by alinoorinet** [comment]
this is the true solution
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true

**Comment by gravyplaya** [comment]
> Changing versions in `build.gradle` didn't help me. What did work adding the line:
> `com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true`
> in `android/app/build.gradle`
> At the very bottom of file, after `apply plugin: 'com.google.gms.google-services'`

This dosen't work for me as it says cant find plugin com.google.gms.google-services

**Comment by mikehardy** [comment]
@gravyplaya missing this I think https://github.com/invertase/react-native-firebase/blob/master/tests/android/build.gradle#L13

**Comment by gravyplaya** [comment]
[cordova] > Failed to apply plugin [id 'com.google.gms.google-services']
[cordova] > Cannot add extension with name 'googleServices', as there is an extension already registered with that name.

@mikehardy Tried that. Got this.

**Comment by mikehardy** [comment]
@gravyplaya open new issue following template, not enough info from your brief comments on this closed issue, sorry

**Comment by snkhan120** [comment]
its very simple just update your com.google.gms services 

**com.google.gms:google-services:4.3.2**
to
**com.google.gms:google-services:4.3.3**
