### ISSUE TITLE
Push Notification not showing on "foreground in android

### ISSUE THREAD

**Issue by ElangoPrince** [invertase/react-native-firebase#2121]
Hi, 
    I'm using react-native version( "react": "16.5.2","react-native": "^0.57.8"). 
    Here is my configuration:
```
              async createNotificationListeners() {
                       const channelId = new firebase.notifications.Android.Channel("Default", "Default", 
                       firebase.notifications.Android.Importance.High);
                       firebase.notifications().android.createChannel(channelId);
                      
                      this.notificationListener = firebase.notifications().onNotification((notification) => {
                      const localNotification = new firebase.notifications.Notification({
                             sound: 'default',
                             show_in_foreground: true,
                     });
                     firebase.notifications().displayNotification(localNotification)
                          .catch(err => console.error(err));
                      });
              }
```
But still the notification alert can't be shown in foreground.please suggest if any mistake in my code or configuration.

**Comment by jacek213** [comment]
@ElangoPrince what was the solution?

**Comment by lyseiha** [comment]
tell us about solution please

**Comment by faizantariq1** [comment]
check your AndroidManifest.xml file.

it should add these:

<service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
    <intent-filter>
      <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
  </service>
  <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
    <intent-filter>
      <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
    </intent-filter>
  </service>
 <receiver android:name="io.invertase.firebase.notifications.RNFirebaseNotificationReceiver"/>
        <receiver android:enabled="true" android:exported="true"  android:name="io.invertase.firebase.notifications.RNFirebaseNotificationsRebootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </receiver>

and user this answer to create your channel.
https://github.com/invertase/react-native-firebase/issues/988?fbclid=IwAR3uyHTh-8q1TRqnhNFX9IuTa8YHKkOzwhyEifyPUrF0CcX4HH3djC_2JHM#issuecomment-383175789
