### ISSUE TITLE
Foreground Notification can't be shown, when the app was closed

### ISSUE THREAD

**Issue by ElangoPrince** [invertase/react-native-firebase#2125]
### **React Native Foreground notification only shown when the app was opened . while the app is closed the notification can't be show in foreground, but background notification alert working fine.**

 **here my notification Listener function:**
```
createNotificationListeners() {
    this.notificationListener = firebase.notifications().onNotification((notification) => {
        const localNotification = new firebase.notifications.Notification({
            sound: 'default',
            show_in_foreground: true,
        })
        .setNotificationId(notification.notificationId)
        .setTitle(notification.title)
        .setBody(notification.body)
        .android.setChannelId('fcm_default_channel')
        .android.setSmallIcon('@mipmap/ic_launcher')
        .android.setColor('#000000')
        .android.setPriority(firebase.notifications.Android.Priority.High);
        
        firebase.notifications().displayNotification(localNotification)
        .catch(err => console.error(err));
    });

    // set  channelId
    const channel = new firebase.notifications.Android.Channel(
      "fcm_default_channel",
      "Firebase Alert",
      firebase.notifications.Android.Importance.High
    );
    firebase.notifications().android.createChannel(channel);
}
```
any idea about this?

**Comment by booleanBoy** [comment]
I'm also finding that all notifications via FCM are received as long as the app is open or suspended. If the app is not open at all, some devices handle it fine, others never show/receive the notification.

Hoping someone might have some ideas?

**Comment by mikehardy** [comment]
well, the issue template indicates all sorts of version informations that will be useful, and without them it's just :thinking: 

But I'm :thinking: you are having issues with android and you haven't seen  http://dontkillmyapp.com
