### ISSUE TITLE
[v6] 🔥 RNFBSharedUtils.h: 'FirebaseCore/FirebaseCore.h' file not found

### ISSUE THREAD

**Issue by benjarwar** [invertase/react-native-firebase#2128]
## Issue

I cannot get React Native Firebase to build without receiving various errors involving header files not being found, for example:

> [local path redacted]/RNFBApp/RNFBSharedUtils.h:21:9: 'FirebaseCore/FirebaseCore.h' file not found

I am trying to install alpha `v6.0` as per [this blog post](https://invertase.io/blog/firebase-crashlytics-for-react-native), as I am predominantly considering switching from [`react-native-fabric`](https://github.com/corymsmith/react-native-fabric) to take advantage of the "automatic" JS stack tracing in `@react-native-firebase/crashlytics`.

I am installing the Firebase SDK manually/statically as we are not yet using CocoaPods. I have followed the [instructions here](https://rnfirebase.io/docs/v5.x.x/crashlytics/ios#Manual) and the advice of other GitHub issues [here](https://github.com/invertase/react-native-firebase/issues/1977#issuecomment-473869487), [here](https://github.com/invertase/react-native-firebase/issues/627), and [here](https://github.com/invertase/react-native-firebase/issues/1016).

I have tried various ways of manually including the Firebase SDK into my project navigator and testing configuration options:

- Checking versus unchecking "Copy files if needed"
- Putting the Firebase SDK frameworks in a dedicated folder at the root versus inside a project folder at the root
- Editing my framework and header search paths in every conceivable way, including recursive and non-recursive
- Setting the header and framework search paths to `FirebaseCore` directly in `/Libraries/RNFBApp.xcodeproj`
- Including `react-native-firebase` as well as `@react-native-firebase/app` and `@react-native-firebase/crashlytics`. I have also tried *not* including the parent `react-native-firebase` lib, since the docs and aforementioned blog post are a little unclear as to whether it's needed or not.
- Adding an `#import <FirebaseCore/FirebaseCore.h>` to specifically include the header in my `AppDelegate.m` file
- Adding the `-ObjC` linker flag
- Cleaning and restarting Xcode, deleting `DerivedData` more times than I can count

My `Firebase.h` file is found by `AppDelegate.m`, although I needed to use quotes instead of angled include since the file is copied into my project navigator, e.g.:

```
#import "Firebase.h"
```

Instead of:

```
#import <Firebase.h>
```

Nothing seems to work after four solid days worth of attempts. I haven't even tried getting things to work on Android yet, so am removing that section from the Issue template below.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
@import AVKit;
#import "AppDelegate.h"
#import "Firebase.h"
#import <FirebaseCore/FirebaseCore.h>
#import <Appboy_iOS_SDK/AppboyKit.h>

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>
#import <React/RCTPushNotificationManager.h>
#import "ReactNativeConfig.h"

#import "VideoIntroViewController.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
//  Initialize Firebase, Fabric, and Crashlytics
  [FIRApp configure];
  
  [Appboy startWithApiKey:[ReactNativeConfig envFor:@"APPBOY_API_KEY_IOS"]
            inApplication:application
        withLaunchOptions:launchOptions];

  UIViewController *rootViewController = [UIViewController new];
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];

  VideoIntroViewController *introVC = [[VideoIntroViewController alloc] init];
  introVC.view.frame = self.window.frame;
  self.window.rootViewController = introVC;

  float delayInSeconds = 5.0;
  dispatch_time_t popTime = dispatch_time(DISPATCH_TIME_NOW, delayInSeconds * NSEC_PER_SEC);
  dispatch_after(popTime, dispatch_get_main_queue(), ^(void){
    RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
    RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                  moduleName:@"REDACTED"
                                          initialProperties:nil];
    rootView.backgroundColor = [[UIColor alloc] initWithRed:0.0f green:0.0f blue:0.0f alpha:1];
    rootViewController.view = rootView;
    self.window.rootViewController = rootViewController;
    [self.window makeKeyAndVisible];
  });

  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```

info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 31.06 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-23 | Intel x86 Atom_64
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.4 
      react-native: ^0.59.4 => 0.59.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `Analytics` (my understanding is this is the only module required for RN Firebase Crashlytics)
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by benjarwar** [comment]
Latest build attempt produced two `Lexical or Preprocessor Issue`s:

```
/[local path redacted]/node_modules/@react-native-firebase/app/ios/RNFBApp/RCTConvert+FIROptions.h:19:9: 'FirebaseCore/FirebaseCore.h' file not found
```

```
/[local path redacted]/node_modules/@react-native-firebase/app/ios/RNFBApp/RNFBSharedUtils.h:21:9: 'FirebaseCore/FirebaseCore.h' file not found
```

**Comment by benjarwar** [comment]
Latest build attempt produced two "Lexical or Preprocessor Issue" errors:

```
/[local path redacted]/node_modules/@react-native-firebase/app/ios/RNFBApp/RCTConvert+FIROptions.h:19:9: 'FirebaseCore/FirebaseCore.h' file not found
```

```
/[local path redacted]/node_modules/@react-native-firebase/app/ios/RNFBApp/RNFBSharedUtils.h:21:9: 'FirebaseCore/FirebaseCore.h' file not found
```

**Comment by Salakar** [comment]
Hey @benjarwar, sorry about this, we've not yet tested manual non-pods integration yet (Pods will be the default in RN 0.60 onwards)

There's a PR (https://github.com/invertase/react-native-firebase/pull/2080) to address the header search paths needing updating, I've not merged it yet as this needs applying to all the modules not just the ones in the PR.

I'll try get this changed in the next couple of days and publish another alpha

**Comment by Salakar** [comment]
(and thanks for a nicely detailed issue, appreciate it)

**Comment by benjarwar** [comment]
@Salakar ah, well. Thanks for the reply. Might be a good idea to include a note somewhere about this, perhaps on the [blog post announcing version 6.0.0](https://invertase.io/blog/firebase-crashlytics-for-react-native) to save other folks some pain. I know non-Pods users are the minority, but it wasn't obvious to me that static integration of the Firebase SDK isn't yet supported.

And thanks for the clarification RE `react-native-firebase` not being needed for v6. I think this also deserves a call out in the docs.

**Comment by kesha-antonov** [comment]
@Salakar same issue. Waiting for the fix
Thanks!

**Comment by kesha-antonov** [comment]
Switched to Podfile:
```
pod 'RNFBApp', path: '../node_modules/@react-native-firebase/app/ios/RNFBApp.podspec'
pod 'RNFBAnalytics', path: '../node_modules/@react-native-firebase/analytics/ios/RNFBAnalytics.podspec'
```

Build succeed

**Comment by Salakar** [comment]
> Switched to Podfile:

Aye via Pods will definitely work as that's what we test with.

----

If anyone is able to take charge of #2080 then please do, ideally, it'd also be nice to add a clone of the `tests/ios` project e.g. `tests/ios_manual` that uses manual linking only and no Pods - then we can add a CI step to ensure manual linking also builds, CI step would need a script that downloads the Firebase frameworks zip and unpacks it.

**Comment by bondparkerbond** [comment]
I'm trying to integrate v6 as well and am running into some similar issues. I've tried going to the individual header and framework search paths as show in [this open PR](https://github.com/invertase/react-native-firebase/pull/2080/files), and while most of the errors have gone away I'm now getting one from the RNFBanalytics.xcodeproj Library, specifically when the RNFBAnalytics/RNFBAnalyticsModule.m with `#import "RNFBApp/RNFBSharedUtils.h"` throwing an error and saying file is not found. I don't think I'm missing any search paths, but maybe I am or maybe I'm missing something else?

**Comment by Salakar** [comment]
@bondparkerbond in v6 every RNFirebase module relies on shared code that's located in RNFBApp - so there should be a header search path in RNFBAnalytics that add a search path for RNFBApp as well - so maybe this is what is missing, that or the import path is wrong when using non-pods - needs confirming.

----

@benjarwar I understand the frustration and I know the non-pods flow is an issue; it is something we'll polish before the first beta release (early-mid July) - we've just got a lot on our plate to do before then as you can imagine - which is why I would really appreciate a complete PR for this to help us out.

I'll see if we can get this mentioned on the docs that it's not yet fully supported

**Comment by Salakar** [comment]
Also worth noting we pay for contributions via our Open Collective, see [here](https://opencollective.com/react-native-firebase/expenses/new) for more info.

**Comment by claudioviola** [comment]
Hey guys
I'have been facing same error of @benjarwar 
`/[local path redacted]/node_modules/@react-native-firebase/app/ios/RNFBApp/RCTConvert+FIROptions.h:19:9: 'FirebaseCore/FirebaseCore.h' file not found`

I have installed
"react-native": "0.59.9",
"@react-native-firebase/analytics": "^0.3.0",
"@react-native-firebase/app": "^0.3.0",
"@react-native-firebase/crashlytics": "^0.3.0",


@Salakar my Pod file is follow

```
platform :ios, '9.0'

target 'ParkHereWork' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ParkHereWork

  pod 'RNFBApp', path:'../node_modules/@react-native-firebase/app/'

  pod 'RNFBCrashlytics', path:'../node_modules/@react-native-firebase/crashlytics/'

  pod 'RNFBAnalytics', path:'../node_modules/@react-native-firebase/analytics/'

end

```

Here my current header search path
![search_path](https://user-images.githubusercontent.com/6689594/64106969-9e2d0c00-cd79-11e9-8b97-920f90dafd20.jpg)


Something is wrong?

**Comment by mikehardy** [comment]
I'm going to close this out, it's been a year with no traffic and we never had a reproduction. We know this has a serious effect for the people it strikes, so we'll be listening if anything actionable comes up on current versions and can re-open then if needed
