### ISSUE TITLE
admob onAdLoaded always call multiple times

### ISSUE THREAD

**Issue by SwiftyWang** [invertase/react-native-firebase#2130]
## Issue

`<Banner
    size={"SMART_BANNER"}
    unitId={AdsBannerId}
    request={adRequest}
    onAdLoaded={() => {
      // don't know why always call 3 times
      console.log("ad loaded");
    }}
    onAdFailedToLoad={(err) => {
      console.log(err);
    }}
  />`

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Can you share the wider code? Could be a React rendering thing or an issue our end.

**Comment by SwiftyWang** [comment]
`     <SafeAreaView style={commonStyles.container} forceInset={{ top: 'always' }}>
...
        <View style={!this.state.hasAd ? { height: 0 } : {}}>
          <AdBanner
            onAdFailedToLoad={() => this.setState({ hasAd: false })}
            onAdLoaded={() => this.setState({ hasAd: true })}
          />
        </View>
 ...
        <Toast ref="toast"/>
      </SafeAreaView>`

And I wrapper **Banner** to **AdBanner**
`export const AdBanner = ({ size, onAdLoaded, onAdFailedToLoad }) => {
  return (<Banner
    size={size === undefined ? "SMART_BANNER" : size}
    unitId={AdsBannerId}
    request={adRequest}
    onAdLoaded={() => {
      // don't know why always call 3 times
      console.log("ad loaded");
      if(onAdLoaded !== undefined) {
        onAdLoaded();
      }
    }}
    onAdFailedToLoad={(err) => {
      console.log(err);
      if(onAdFailedToLoad !== undefined) {
        onAdFailedToLoad();
      }
    }}
  />);
};`

**Comment by emrevural20** [comment]
Same here

**Comment by saribalorhan** [comment]
+1

**Comment by emrevural20** [comment]
Delete console.log() from onAdLoaded and onAdFailedToLoad.
