### ISSUE TITLE
Having problem with link an anonymous account with the existing google account

### ISSUE THREAD

**Issue by ManalLiaquat** [invertase/react-native-firebase#2132]
## Issue

I am having problem with the linking an anonymous account with the existing google account in the firebase project.
The scenario of application is very simple, when the user open myApp first time, an anonymous account is created and if the user wants to signInWithGoogle the current anonymous account is link with user's google google, but if the user uninstall the application or lost his phone and reinstall it on other phone, a new anonymous user is created and if the user wants to signInWithGoogle account (which he/she used earlier), it throws an error in linking with anonymous user and google user.

I want to link/merge the anonymous account with the existing google account.
Any solution will be appreciated.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Check out the advice on error code 'auth/credential-already-in-use'  on https://rnfirebase.io/docs/v5.x.x/auth/reference/User#linkWithCredential

**Comment by ManalLiaquat** [comment]
> Check out the advice on error code 'auth/credential-already-in-use' on https://rnfirebase.io/docs/v5.x.x/auth/reference/User#linkWithCredential

@mikehardy I already read it before and I want any solution for my problem, but thanks for your time. Is there any way to get this done?

**Comment by Ehesp** [comment]
@ManalLiaquat please show us your current code and workflow. It should be possible but it would be easier to see how you currently have it setup.

**Comment by ManalLiaquat** [comment]
@Ehesp, 

```
```

**Comment by ManalLiaquat** [comment]
@Ehesp 

> @ManalLiaquat please show us your current code and workflow. It should be possible but it would be easier to see how you currently have it setup.

```
export const anonymousLogin = () => {
    return async () => {
      try {
        const { additionalUserInfo, user } = await firebase.auth().signInAnonymously()
        console.log('anonymousUser.additionalUserInfo =====> ', additionalUserInfo);
        console.log('anonymousUser.user =====> ', user);

      } catch (error) {
        console.log("Error Anonymous Login", error);
      }
    }
  }

  export const googleLogin = () => {
    return async () => {
      try {
        await GoogleSignin.hasPlayServices();
        const userInfo = await GoogleSignin.signIn();
        console.log("sucess: ", userInfo);
        const credential = firebase.auth.GoogleAuthProvider.credential(
          userInfo.idToken,
          userInfo.accessToken
        );
        console.log("credential: ", credential);
        firebase.auth().currentUser.linkWithCredential(credential).then(function (usercred) {
          var user = usercred.user;
          console.log("Anonymous account successfully upgraded", user);
        })
      } catch (error) {
        console.log(error, " error googleLogin ");
      }
    };
  };
```

I have these two functions and I called anonymousLogin function on the first run `in the componentDidMount method` of the app and get the anonymous id after that when the user sign in with google this will link with the generated anonymous id successfully, if user uninstall my app or remove data of app from settings and reinstall the app or open the app, a new anonymous id is created and if user tries to sign in with google it throws an error `This credential is already associated with a different user account.`, so what can I do to merge data against my new anonymous id with the previously signed in user `(google user)`? how to link the new anonymous id with already signed user?

![CvdkEy](https://user-images.githubusercontent.com/36041100/57909737-7badcc00-7838-11e9-96a6-341a01090517.png)
