### ISSUE TITLE
react-native-firebase  iOS linking issue with manual installation

### ISSUE THREAD

**Issue by mhkasif** [invertase/react-native-firebase#2134]
## Issue

Describe your issue here
No known class method for selector 'componentsWithLink:domain:'
![Screen Shot 2019-05-14 at 12 47 46 AM](https://user-images.githubusercontent.com/30750191/57649681-4b6cf000-75e2-11e9-8517-04e9c5eece7b.png)

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Steve1820** [comment]
Following!

**Comment by mikehardy** [comment]
@Steve1820 that sends mail to everyone, with no value. Just hit the subscribe button to follow (same as facebook where rather than a useless "follow" or +1 you can enable notifications by using an action from their menu)

**Comment by AndreyPatseiko** [comment]
Have the same error.

**Comment by mikehardy** [comment]
Hi guys - I apologize but there are so many install issues, and they are so hard to work out that while others might be able to sort out the manual install style, I have only had success with pods. I recommend you look at https://github.com/mikehardy/rnfbdemo as it goes from nothing to working in just a few lines, using Pods.

**Comment by AndreyPatseiko** [comment]
Thanks, installed via pods. [Nice tutorial](https://www.youtube.com/watch?v=qiOGMcX6Xtw)

**Comment by RockyRx** [comment]
I'm having the exact same issue.

Podfile

```
# platform :ios, '11.0'

target 'testMobileApp' do
  # this is very important to have!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
  pod 'GoogleIDFASupport', '~> 3.14.0'

end

# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

```
react-native-firebase v5.3.1
firebase v6.0.2
react-native 0.58.4
```

**Comment by RockyRx** [comment]
Tried after cleaning uninstalling and reinstalling Pods. Still the same issue.

**Comment by halileohalilei** [comment]
I have the same issue. It seems like `componentsWithLink:domain:` was deprecated and replaced with `componentsWithLink:domainURIPrefix:` but the deprecated one is still being used.

**Comment by mikehardy** [comment]
If it's a problem with domain vs domainURIPrefix please check the release notes for react-native-firebase v5.5.x - this was a breaking change and things should work if you carefully follow the compatibility matrix in the getting started page on rnfirebase.io

**Comment by Zabi-Progton** [comment]
So did anyone find a fix for this?

**Comment by tamirrab** [comment]
Yes,
you need to add ```https://``` to domainPrefix

example:
```
 new RNFirebase.links.DynamicLink(`https://www.google.com`, 'https://example.page.link')
            .android.setPackageName('com.example')
            .ios.setBundleId('org.example');
```

**Comment by efronnyp** [comment]
In case of anyone who still face this issue, I solved this by upgrading/ensure the `react-native-firebase` version is at least `~5.5.7`, if you are still using v5.x.x it is. In addition to that, my app works properly using `Firebase/DynamicLinks, '~> 6.13.0'`.

The reason for the error is because there is a breaking change for the mentioned method above and the `domain` parameter name is changed to `domainURIPrefix`.
