### ISSUE TITLE
firebase.messaging() does not work in release mode for IOS

### ISSUE THREAD

**Issue by hellpirat** [invertase/react-native-firebase#2135]
## Issue
Hello, I have an issue with my release mode app for ios. It appears only in release mode.
```
You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.messaging().

Ensure you have the required Firebase iOS SDK pod for this module included in your Podfile, in this instance confirm you've added "pod 'Firebase/Messaging'" to your Podfile

See http://invertase.link/ios for full setup instructions.
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 478.41 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.7.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 26.0.1, 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.4 => 0.59.4 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `Firebase/Messaging`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

**Comment by mikehardy** [comment]
I think 5.20.2 is current for the pod versions. Are you certain you ran pod install afterwards?

**Comment by hellpirat** [comment]
Yeah, I did a pod install before made release build. 

Actually, It happens sometimes before 🤔

Now I will try to install a newer version of react-native-firebase.

**Comment by mikehardy** [comment]
Hmm - I don't think the new version will actually fix it, but it's good practice. Perhaps you're missing some install step required in the Obj-C .m files or similar? maybe react-native-firebase-starter has hints if you look at how it is done?

**Comment by hellpirat** [comment]
Hm, it didn't help me at all. 

It works on my phone with the development release. 
```
react-native run-ios --device    
```
But it doesn't work in release mode 🤔

**Comment by hellpirat** [comment]
Hm new information from me:
It's work in debug and even react-native run-ios --device --configuration Release
But does not work after Xcode archive and publish to testflight

**Comment by mikehardy** [comment]
There is an official firebase video that walks through how to test every link in the chain for messaging for iOS - I highly recommend, in order to figure out where the problem is https://firebase.googleblog.com/2017/01/debugging-firebase-cloud-messaging-on.html

This (and related articles) are also interesting https://firebase.googleblog.com/2019/02/life-of-a-message.html

**Comment by dooleyb1** [comment]
@hellpirat Did you manage to resolve this issue? Currently encountering the same issue. Works in debug mode however when I build in release mode it does not work.

**Comment by dooleyb1** [comment]
Just to note, I am successfully receiving the notifications (can see them when app is in the background i.e screen locked). However, the functionality defined in my listeners is not being executed as expected.

**Comment by dooleyb1** [comment]
Managed to resolve this, issue was that CodePush was overwriting my file changes when I built in Release mode. By commenting out the wrapper `export default codePush(codePushOptions)(...)` before building in Release mode on a test device I managed to get my listeners to work as expected 👍
