### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by onitzschke** [invertase/react-native-firebase#2136]
```
FAILURE: Build failed with an exception.
android.enableAapt2

This property has no effect, AAPT2 is now always used.
* Where:

android.useDeprecatedNdk
Build file '***/node_modules/@react-native-firebase/analytics/android/build.gradle' line: 58
NdkCompile is no longer supported


* What went wrong:

A problem occurred evaluating project ':@react-native-firebase_analytics'.
> Project with path ':@react-native-firebase/app' could not be found in project ':@react-native-firebase_analytics'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

`@react-native-firebase/app`  is installed and linked.

**Comment by mikehardy** [comment]
Near as I can tell you have skipped the entire issue template.

**Comment by kasterlod** [comment]
`api project(':@react-native-firebase/app')` -> `api project(':@react-native-firebase_app')` is working for me

in `@react-native-firebase/analytics/android/build.gradle:58`

**Comment by santoshachari** [comment]
> 
> api project(':@react-native-firebase/app') -> api project(':@react-native-firebase_app') is working for me
> 
> in @react-native-firebase/analytics/android/build.gradle:58
> 

This throws the error: 

Unable to find a matching configuration of the project :@react-native-firebase_app: None of the consumable configurations have attributes.

**Comment by kasterlod** [comment]
That's weird. Do you have `:@react-native-firebase_app` integrated into your project?

**Comment by santoshachari** [comment]
@kasterlod I did install `/app` version. 

FYI - also the same issue : https://github.com/invertase/react-native-firebase/issues/2149
