### ISSUE TITLE
Integrate this lib is PAINFUL

### ISSUE THREAD

**Issue by anhtuank7c** [invertase/react-native-firebase#214]
I spent whole day to integrate.
Tried with RN 44, RN 45, Firebase 3.17.0, react-native-firebase 1.1.1, 1.1.2, 2.0.0 but none of them work for me 👎 

FCM Token not found even `GoogleService-Info.plist` existing, clean cache, rm node_modules, yarn etc....

**Comment by Ehesp** [comment]
Hello. Indeed most native integrations with React Native are painful when developers have no native experience. The library does work, but unfortunalty apps are not as easy to make with just an "npm install".

Please upload your project somewhere and we can take a look, or at least give us some logs to work with. We're happy to help, but you need to also help us help you.

**Comment by anhtuank7c** [comment]
@Ehesp Hi, can we talk on discordapp?

**Comment by anhtuank7c** [comment]
@Ehesp I am on discord now: https://discordapp.com/channels/295953187817521152/295953187817521152

**Comment by andfk** [comment]
Agree with @Ehesp. This library works perfectly but somehow im having issues with v2.0.0 and with new Firebase Pods (v4.x.x) BUT im pretty sure will be solved soon. Using v1.1.2 and Pods of v3.1.7 works perfectly.

**Comment by Ehesp** [comment]
@andfk unfortunalty we've never used Expo. Do you have the project anywhere to take a look?

**Comment by andfk** [comment]
@Ehesp don't worry, is totally expected to have issues with Expokit but IMO this is not responsibility of the team behind RNFirebase :). Im trying now with react-native only following how this library is developed and IOS for now its working perfectly. Thanks anyway!

**Comment by anhtuank7c** [comment]
I wasted whole day to find out that i have to use Firebase cocoapods version 4.0.2 (My old one is 3.17.0)

I am now integrated successful to ios project.
@andfk Thank you for your help. You're super man.

**Comment by amitailanciano** [comment]
I think there should be a mention of this in the docs somewhere, definitely bit me too

**Comment by anhtuank7c** [comment]
Also use version `11.0.1` for Android project ;)

**Comment by Salakar** [comment]
Not to be the guy that points out the obvious but on the homepage of the docs and on the readme it does have a versions table:
![image](https://user-images.githubusercontent.com/5347038/27744846-15788574-5db9-11e7-88d5-185ed0cc9976.png)


:eyes:

**Comment by ethanyuwang** [comment]
@andfk Have you got this library working with ExpoKit? I followed the instructions but my android app would just crash on start

**Comment by andfk** [comment]
@ethanyuwang sorry my friend but as I remember it was lot of issues in general at that time. Not sure if current version of RNFirebase and Expokit works much better. If you need this library I suggest you to start from react-native instead of expokit as you will deal with lot of issues. Hopefully like I said, it works much better now. Good luck!
