### ISSUE TITLE
Android badges doesn't work, ShortcutBadger not working

### ISSUE THREAD

**Issue by lorenc-tomasz** [invertase/react-native-firebase#2141]
Hi,
Android 8.0 (Samsung), RN 0.59.8, RNFirebase 5.x

I would like to show badges on local notifications on Android but it doesn't work. I have tested ShortcutBadger by writing native app and the same result. So the issue is with ShortcutBadger. Could you replace it to make it working again?

**Comment by mikehardy** [comment]
Hey @lorenc-tomasz - I just worked through this sort of functionality in my own app.
All I can say is that there is really nothing you can do. Android in general does not support badging. ShortcutBadger's documentation is clear on this point as well.

AOSP (and thus Google Nexus or emulators) don't support it.
Various vendors have implemented the capability and ShortcutBadger attempts to use them but it's a doomed effort really.

I can say that on an LG and Moto device, my badges show up. on iOS my badges show up, as expected.

So I think this is sadly an upstream issue, ShortcutBadger is still the best choice, but in general it's just not great and can't be.

If you dig in on ShortcutBadger (or the badging area in general) and find different please re-open with your findings as I'd love to know

**Comment by mikehardy** [comment]
just to say I've marked it "invalid" but that's only because it's upstream, I recognize it's an issue

**Comment by lorenc-tomasz** [comment]
@mikehardy  Agree. It works better with channels from Android 8.x.
