### ISSUE TITLE
[QUESTION]Setting State after Verifying Email address?

### ISSUE THREAD

**Issue by troy1129** [invertase/react-native-firebase#2143]
Ive been reading the documentations particularly:
https://firebase.google.com/docs/auth/ios/passing-state-in-email-actions

Though I havent gotten around to actually making things work, the function im trying to achieve would be that id be able to set a state e.g emailVerified if the link sent to my email address after registering is pressed. As of the moment even though the link is not pressed I am still able to login with the newly registered account, any ideas?

**Comment by mikehardy** [comment]
Once firebase registers the email it is possible to log in with it anytime.
It is up to your app to force some sort of flow that you want *if* emailVerified is not true.
Once they click the link, by default given the auth templates they provide you in the default emails etc, firebase will set emailVerified to true, so when the comes back if you re-fetch the user you'll see it and can proceed accordingly in your app

**Comment by troy1129** [comment]
> Once firebase registers the email it is possible to log in with it anytime.
> It is up to your app to force some sort of flow that you want _if_ emailVerified is not true.
> Once they click the link, by default given the auth templates they provide you in the default emails etc, firebase will set emailVerified to true, so when the comes back if you re-fetch the user you'll see it and can proceed accordingly in your app

thank you! I never saw emailVerified, guess i didnt see that part. Great help thank you!
