### ISSUE TITLE
crashlytics

### ISSUE THREAD

**Issue by hadare1** [invertase/react-native-firebase#2144]
I'm new to react-native . I'm trying to add crashlytics to my app , this is my podfile:

    # Required by RNFirebase
    pod 'Firebase/Core', '~> 5.15.0'
    pod 'Firebase/Auth', '~> 5.15.0'
    pod 'Fabric', '~> 1.9.0'
    pod 'Crashlytics', '~> 3.12.0'
    pod 'GoogleIDFASupport', '~> 3.14.0'

this is my code:

    import React, {Component} from 'react';
    import {View} from 'react-native';
    import {Provider} from "mobx-react";
    import rootStore from './src/stores/RootStore';
    import firebase from "react-native-firebase";

    class App extends Component {

    componentDidMount(){
        firebase.crashlytics().enableCrashlyticsCollection();
    }

    render() {

        return (
            <Provider rootStore={rootStore}>
                <View/>
            </Provider>

        )}
    }
    export default (App);

I get this error message :

371d29ab-9482-42bd-a…-4915912912cd:25629 Error: You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.crashlytics(). Ensure you have the required Firebase iOS SDK pod for this module included in your Podfile, in this instance confirm you've added "pod 'undefined'" to your Podfile

Am I missing something?

**Comment by mikehardy** [comment]
Getting react-native-firebase working is not an easy task for someone new to react-native (I know, that was me just a couple months ago). I cannot recommend strongly enough that you begin with the react-native-firebase-starter app and exercise it completely, see how it works. Your error is a simple (once you have experience) linking / installation error (the iOS-specific docs for the crashlytics module have the answer) but these aren't easy to figure out the first time. Also, your dependencies are already out of date, most of them should be 5.20.2 now though the Fabric/Crashlytics ones are in a different series
