### ISSUE TITLE
Not able to get events source

### ISSUE THREAD

**Issue by Pruthvirajcodewave** [invertase/react-native-firebase#2148]
Hi 
I am using this npm for analytics events. All the events are tracking as expected. 
My issue is with respect to capturing the lead source. Most of the sources are coming as (direct) or (not set).

I have used the following code snippet inside manifest to receive the broadcasts sources.

`<receiver android:name="com.google.android.gms.analytics.CampaignTrackingReceiver"
        android:enabled="true"
        android:exported="true">
        <intent-filter>
            <action android:name="com.android.vending.INSTALL_REFERRER" />
        </intent-filter>
    </receiver>
    <service android:name="com.google.android.gms.analytics.CampaignTrackingService"
        android:enabled="true"
        android:exported="false" />`

When I test this as specified by this link [https://developers.google.com/analytics/solutions/testing-play-campaigns#prepare.](url)

I am getting the below logcat.

> 05-21 18:49:35.975  8806  9318 W GAv4    : CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3yj for instructions.

Should I be using `react-native-google-analytics-bridge` to track all the sources or is there a way to track the sources within this npm itself?

**Comment by ankitwandx** [comment]
I am having the same problem. Were you able to solve this? I am using the latest @react-native-firebase/analytics and trying to test using https://developers.google.com/analytics/solutions/testing-play-campaigns#prepare.
