### ISSUE TITLE
firebase.messaging().onDeleteMessages not implemented?

### ISSUE THREAD

**Issue by mikehardy** [invertase/react-native-firebase#2154]
I'm not sure if an unimplemented firebase sdk API is a feature request or a bug? I couldn't find it either here or on the feature request board though, so I'm putting it here provisionally - either way I don't believe this API exists based on my search of the codebase:

https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessagingService.html#onDeletedMessages()

```
Called when the FCM server deletes pending messages. This may be due to:

Too many messages stored on the FCM server. This can occur when an app's 
servers send a bunch of non-collapsible messages to FCM servers while the 
device is offline.

The device hasn't connected in a long time and the app server has recently 
(within the last 4 weeks) sent a message to the app on that device.

It is recommended that the app do a full sync with the app server after 
receiving this call. See here for more information.
```

**Comment by Salakar** [comment]
Thanks Mike, will get this in the pipeline for Messaging v6 - not long now.

Main question from me really is does the iOS SDK support it as well?

**Comment by mikehardy** [comment]
https://firebase.google.com/docs/cloud-messaging/ios/receive#handle_queued_and_deleted_messages I believe so

**Comment by mikehardy** [comment]
Maybe worth mentioning (for prioritization) that this is for the FCM direct case only - so as a test plan anything involving APNs on Android won't matter, but for Android in general and iOS sometimes (when connected directly to FCM, which I presume is foreground?) it is possible for the library to call this hook.

**Comment by Salakar** [comment]
Done - [[changelog]](https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md#cloud-messaging-messaging).
