### ISSUE TITLE
v6 'Firebase/Firebase.h' file not found

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [invertase/react-native-firebase#2156]
## Issue

'Firebase/Firebase.h' file not found

npm:
 "@react-native-firebase/analytics": "alpha",
  "@react-native-firebase/app": "alpha",

Describe your issue here
The react related libraries are not installed via pods

---

## Project Files

cocoapods：
platform :ios, '10.0'
target 'Combo' do
pod 'Reveal-iOS-SDK' ,:configurations => ['Debug']
pod 'Firebase/Core'
end

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Install / linking failure
https://github.com/invertase/react-native-firebase/issues?q=is%3Aissue+sort%3Aupdated-desc+Firebase.h+not+found+is%3Aclosed

Use the react-native-firebase-starter project, as a test, if you can use it this is not a problem with the library, it is a problem with the way you integrated it. There are so many ways that can go wrong it's hard to say, but I'd revert whatever you did and re-do it following the documentation as closely as possible while comparing to the starter

**Comment by mikehardy** [comment]
Possible duplicate #2128

**Comment by mikehardy** [comment]
If you haven't followed https://github.com/invertase/react-native-firebase/issues/2126 you might check it out
Building a fresh react-native app using the react-native-firebase v6 template works, but you must be very careful on your command lines. The linked issue has the ones you need.

I'm going to close this as it appears to be working in my testing.
