### ISSUE TITLE
🔥RNFirebase 5.x.x signInWithPhoneNumber Phone Auth freezes iPhone

### ISSUE THREAD

**Issue by Asalem1** [invertase/react-native-firebase#2161]
## Issue

The issue I'm encountering is that the `firebase.auth().signInWithPhoneNumber()` function seems to hang on apps with TestFlight. 

The function works on productions for android, and on my local iOS emulator, but after archiving and uploading the app onto TestFlight, the app seems to hang during the execution of the function. I've searched stackoverflow and previous issues, but can't seem to pin down the exact cause of the issue (nor am I entirely sure that the issue will persist in production).

Code Snippet:

```
    firebase
        .auth()
        .signInWithPhoneNumber(`${phone_number}`)
        .then((confirmationResult) => {
          // save confirm result to use with the manual verification code
          window.confirmationResult = confirmationResult;
          dispatch({
            type: GETPIN_SUCCESS,
            data: {
              carrier_id,
              phone_number,
            },
          });
        })
        .then(() => {
          dispatch(NavigationActions.navigate({ routeName: 'Login' }));
        })
        .catch((err) => {
          dispatch(setMessage('Invalid Phone Number or No Phone Number Found', true, true));
          callback();
        });
```

Since this works on the iOS simulator and on the android app in production, I'm not sure if this is a TestFlight thing or a RNFirebase thing

## Project Files

`package.json`

```
"react-native": "^0.59.0",
...
"react-native-firebase": "^5.3.1",
```

### iOS

<details><summary>signInWithPhoneNumber hangs on TestFlight</summary>
The signInWithPhoneNumber method seems to hang whenever it is triggered via TestFlight on iOS. I can't reproduce this error on the simulator in debug or release mode (for iOS). This error is not occurring on android (both for debug and release).
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'FirebaseAnalytics'
  pod 'Firebase/Messaging'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
```

#### `AppDelegate.m`:

```objc
@import Firebase;
#import "AppDelegate.h"
#import "RNFirebaseNotifications.h"
#import "RNFirebaseMessaging.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>


@import AirshipKit;
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
  [RNFirebaseNotifications configure];
  NSURL *jsCodeLocation;
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"trkxmobilereact"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
  
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [UAirship takeOff];
  return YES;
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
  [[RNFirebaseMessaging instance] didRegisterUserNotificationSettings:notificationSettings];
}

-(void) userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler {
  
  [[RNFirebaseMessaging instance] didReceiveRemoteNotification:response.notification.request.content.userInfo];
  completionHandler();
}

@end
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
      Memory: 574.61 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6
      react-native: ^0.59.0 => 0.59.8
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

- **Platform that you're experiencing the issue on**:
  - [x ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `auth`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

#Related Issue on SO

The only other issue that I found is on SO, but doesn't have much traction:

https://stackoverflow.com/questions/49136308/react-native-firebase-phone-auth-freezes-iphone

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
does it work with an iOS device connected to your machine in debug or release modes?

I'll add that you can watch iOS device logs via Console.app on your desktop while they are plugged in, and you can add this in your AppDelegate.m to get console logging to show up: 

```obj-c
  RCTSetLogThreshold(RCTLogLevelInfo - 1);

..- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  RCTSetLogThreshold(RCTLogLevelInfo - 1);
  //...

...
```

**Comment by Asalem1** [comment]
@mikehardy I've just gotten ahold of an iOS device so I'll try to build it directly onto there and see if I can create the issue there. I appreciate you sending over that information, I'll go ahead and take that onto the `AppDelegate.m` and let you know if anything pops up.

**Comment by Asalem1** [comment]
Quick update, I am able to reproduce this error when building directly onto my phone (not the simulator). Super weird thing is that I'm getting a `Error: Invalid token` error when trying to login.  I will investigate this further and hopefully come to a resolution. Thanks for the advice @mikehardy

**Comment by Asalem1** [comment]
Solution for anyone encountering the same issue:

Make sure that the name given to your APN matches the app name

**Comment by ferryhinardi** [comment]
Hi @Asalem1, i got the same issue, for configuration APN do you mean Menu Keys in this https://developer.apple.com/account/resources?

**Comment by ithustle** [comment]
> Solution for anyone encountering the same issue:
> 
> Make sure that the name given to your APN matches the app name

I'm having the same issue on RN 0.64.2 and RNFB 12.1.0 and give the name on APN as match the app name didn't work
