### ISSUE TITLE
AdRequest: addKeyWord

### ISSUE THREAD

**Issue by karvulf** [invertase/react-native-firebase#2162]
## Documentation Feedback

I am a little bit confused. I have the possiblity to add a keyword to my adrequest. But do I need a keyword and what exactly is that doing?
I hope you can help me.

'''
const AdRequest = firebase.admob.AdRequest;
  const request = new AdRequest();
  request.addKeyword('Do_I_Need_That?');
---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
This is not react-native-firebase specific, it's base library functionality
You should consult the relevant docs: https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest.Builder.html#addKeyword(java.lang.String)

Looks optional, but if you're not sure, you should read the whole documentation set https://firebase.google.com/docs/admob/admob-firebase (among others)

**Comment by karvulf** [comment]
Thank you very much! @mikehardy
