### ISSUE TITLE
🔥 FieldValue.increment is not a function

### ISSUE THREAD

**Issue by AlcuinGuest** [invertase/react-native-firebase#2164]
## Issue
When using FieldValue.increment, it errors: 
```TypeError: _reactNativeFirebase.default.firestore.FieldValue.increment is not a function```
<img width="622" alt="Screen Shot 2019-05-25 at 11 04 17" src="https://user-images.githubusercontent.com/17879993/58367998-48c1a300-7ede-11e9-879d-175f811b9b28.png">

**Usage:**
```
import firebase from 'react-native-firebase';

db
    .collection(...)
    .doc(...)
    .set(
       {
          count: firebase.firestore.FieldValue.increment(1),
       },
       { merge: true },
    )
```
Using v^5.3.1 of the library.

**Note**: firebase.firestore.FieldValue.serverTimestamp() works fine.

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

**Comment by mikehardy** [comment]
Hmm - I can't see how your code would work, it would be `firebase.firestore().etc` wouldn't it - note parentheses

Also, you did not fill the template. I have no idea what versions of the firebase SDKs you are using.

**Comment by Ehesp** [comment]
@mikehardy FieldValue is exported (or should be!) as a static on `firestore`: https://github.com/invertase/react-native-firebase/blob/v5.x.x/src/modules/firestore/FieldValue.js#L31

A repro would be good to check.

**Comment by Salakar** [comment]
I'd also double check your version installed is definitely 5.3.0 or above, check your node modules and the package json of react-native-firebase

**Comment by AlcuinGuest** [comment]
Thanks all, I will look further into it and update if I make any progress. 

_@mikehardy Interesting that the serverTimestamp works without the () on the firestore._

**Comment by mikehardy** [comment]
> _@mikehardy Interesting that the serverTimestamp works without the () on the firestore, for me anyway._

Yeah - apparently it is a static export and I just hadn't checked the code, my mistake!

**Comment by rishiankush** [comment]
<img width="1292" alt="Screen Shot 2019-05-28 at 3 44 21 PM" src="https://user-images.githubusercontent.com/25289937/58470537-841ed480-815f-11e9-95a4-6705450caf93.png">

**Comment by mikehardy** [comment]
no follow up, no template
