### ISSUE TITLE
db.collectiion("somecollection").get().then(data => data).catch(err => err) won't return any data or error 

### ISSUE THREAD

**Issue by arcr06** [invertase/react-native-firebase#2165]
I Tried a Lot but some time its works proper but sometime wont ....

### `constructor() {
        super();
        this.ref = firebase.firestore().collection('default');
        this.state = { 
        }
    }
    static navigationOptions = { header: null }
    componentWillMount = () => {
        auth.onAuthStateChanged((user) => {
            if(user) { 
                this.props.navigation.navigate("MainPage",{user});
            }  else {
                this.ref.get().then((querySnapshot) =>{
                    console.log("done");
                    querySnapshot.forEach((doc) => { 
                        this.setState({zipcode: doc.data().pincode,loading: false})
                    });
                });
            }
        }); 
    }`

**Comment by Ehesp** [comment]
Please follow the issue template so we can help.
