### ISSUE TITLE
RNFirebase FirebaseCore/FirebaseCore.h file not found 

### ISSUE THREAD

**Issue by getinfyKiranreddy** [invertase/react-native-firebase#2167]
I have followed RNFirebase documentation I have been getting FirebaseCore/FirebaseCore.h file not found Firebase.h

XCode: 10.2.1
React-Native : 0.57.8
ReactJs: 16.6.3
RNFirebase: 5.2.5

I have linked react-native-link-firebase also after added search path and all but Still I am getting same issues can you one help me out 

Thanks

**Comment by mikehardy** [comment]
I definitely see this problem also, but I'm tracking it comprehensively with a demonstration repo here #2163 - there is also a probably workaround you can follow there

**Comment by getinfyKiranreddy** [comment]
Thanks for replying @mikehardy but I didn't get you what you have tried to tell me.  I followed RNFirebase IOS documentation but still I am facing this issue please try to help out 
Thanks

**Comment by mikehardy** [comment]
I'm trying to tell you to go that issue. Read that issue. Follow the advice in that issue to add a line in your podfile that copies headers files to a location where apparently react-native-firebase is looking for them, then build your app. It should work. If it does not work, please add context in that issue so we can figure out why

**Comment by Jackyaung** [comment]
have you found the reason ? I have the same problem, the problem is very strange, everytime when I run it on xcode, it always reports the error (firebaseCore.h can not found), then I click the run button again , it works. I always have to do like this, run two times, the first time reports error, second time it works.
