### ISSUE TITLE
Project with path ':react-native-firebase' could not be found in project ':app'.

### ISSUE THREAD

**Issue by Vivekban** [invertase/react-native-firebase#2171]
## Issue

i am using react native  0.59.8 and it is giving me error with firebase 5.4.0

Describe your issue here

Build file 'E:\ReactNative Project\LIVE PROJECTS\storage\android\app\build.gradle' line: 145

* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':react-native-firebase' could not be found in project ':app'.
---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:
implementation project(':react-native-gesture-handler')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-firebase')     // This should be here already
    implementation "com.google.android.gms:play-services-base:16.1.0"  // Firebase dependencies
    implementation "com.google.firebase:firebase-core:16.0.9"
```groovy
// N/A
```

#### `android/settings.gradle`:
rootProject.name = 'storage'
include ':react-native-gesture-handler'
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gesture-handler/android')

include ':app'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
```groovy
// N/A
```

#### `MainApplication.java`:
import io.invertase.firebase.RNFirebasePackage;
            new RNFirebasePackage(),

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment
 "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-firebase": "^5.4.0",
    "react-native-gesture-handler": "^1.2.1",
    "react-navigation": "^3.4.0"
<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You should have included android/build.gradle as instructed, I think that's the source of your problem. I would bet you did a manual integration on android instead of a link, and you forgot the entry there.

**Comment by Vivekban** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
         jcenter()
        google()      
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
    classpath 'com.google.gms:google-services:4.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
         maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com" }
    }
}

**Comment by mikehardy** [comment]
android/settings.gradle FOLLOW THE TEMPLATE

**Comment by sharadpro** [comment]
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
include ':app'

//add these lines in the android/settings.gradle

**Comment by imcnaney** [comment]
In the process of doing a manual upgrade to RN 0.60.0 I ran into this problem.  I had reordered my android/settings.gradle file to separate standard RN stuff from my added projects, but putting `include ':app'` above the react-native-firebase lines caused this error.  Moving it back to the bottom fixed the problem.
