### ISSUE TITLE
Support to multi targets on iOS

### ISSUE THREAD

**Issue by MorochoRochaDarwin** [invertase/react-native-firebase#2172]
I have  multiples  targets on my iOS project like this
![image](https://user-images.githubusercontent.com/15864336/58517915-b71e9380-8172-11e9-96f2-8381b569c75d.png)

this is my script in  my target "valientes"
```
INFO_PLIST_FILE=${PROJECT_DIR}/pas/GoogleService-valiente-Info.plist

cp -r "${INFO_PLIST_FILE}" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist"
```

when I run the target valientes phone auth return the next error
```
{ error_name: 'INVALID_APP_CREDENTIAL',
     NSLocalizedDescription: 'Invalid token.' },
  domain: 'FIRAuthErrorDomain',
```

that is because rnfirebase is taking the file  GoogleService-Info.plist  and not  the GoogleService-valiente-Info.plist

Could you provide some docs about this?

**Comment by mikehardy** [comment]
There are so many ways to do this, it can't really be specified I don't think. You can use a run script at build time to copy the file you want into a static spot. You can use code to dynamically load a file before you load firebase. You can put all the files in and just include the right one for the right target.

I've got 4 different firebase targets from the same .xcworkspace for instance. I used the method where I have all the plist files for all the environments in the project, each in a separate directory, and I only include the specific plist you want for the target you want. 

https://stackoverflow.com/a/47074634/9910298
