### ISSUE TITLE
What package.json/Podfile is suitable for RNFirebase 6.0?

### ISSUE THREAD

**Issue by salmazov** [invertase/react-native-firebase#2178]
I spent a lot of time to balance my npm packages with pod files. I just want to upgrade my RN app to RNFirebase 6, React 16.8 and last versions of react-redux/redux/firebase.

But didn't succeeded. What is ideal configuration of package.json/podfile?

**Comment by Salakar** [comment]
I replied to your comment on the v6 issue, let's continue the discussion there.
