### ISSUE TITLE
onNotification not triggered when app in background

### ISSUE THREAD

**Issue by suswariadla** [invertase/react-native-firebase#2181]
Hi,
My app uses schedule local notifications. I have some feature that works with onNotification listener. My problem here is that onNotification listener is not triggered when the app is in background unlike the app in foregorund. Anybody anyidea what is the equivalent listener for onNotifcation when the app is in foreground.

**Comment by mi-mazouz** [comment]
I have the same issue on android only, background notifications not working. Any ideas?

**Comment by mikehardy** [comment]
https://rnfirebase.io/docs/v5.x.x/notifications/introduction#Local-Notifications

**Comment by mikehardy** [comment]
At the same time, I've seen some issues with regard to notifications triggering or not. This issue specifically asks "what is the equivalent listener for onNotification when the app is in the foreground", I have answered that, so I will close this specific issue.

However with #2163 I'm attempting to put a reproducible from-scratch demo together of all the notification features in one demo app so I/we can verify it all works. You can follow this repo if you like https://github.com/mikehardy/rnfbdemo

**Comment by Ilario17** [comment]
@suswariadla did you find a solution?

**Comment by Sanan4li** [comment]
facing this issue on Scheduled Notifications
