### ISSUE TITLE
Imports are configued wrong causing Firapp.h missing + Firebasecore/Firebasecore.h missing

### ISSUE THREAD

**Issue by xcxooxl** [invertase/react-native-firebase#2182]
version 5.4.2

I had those errors started with firApp.h missing

I solved it by adding this to the header search paths
$(SRCROOT)/../../../ios/Pods/FirebaseCore/Firebase/Core/Public/
to the RNFirebase project 

second error was failing to find Firebasecore/firebasecore.h

imports looked like

`import <FirebaseCore/FirebaseCore.h>`
changing it to 
`import <FirebaseCore.h>`

solved the issue and now the project builds fine.

hopefully there will be a fix where we don't need to do this manually ?

**Comment by mikehardy** [comment]
There will be a fix as soon as someone has a reproduction and proposes a clean PR to fix these headers issues

I'm working on a reproduction here #2163 for v5, and while it does not propose a clean PR it points out the problem in a reproducible way for quick testing/iteration.

@Salakar mentioned he might try to take a look this weekend - time permitting - so I'd focus on that one and put your findings there. If you do that, please please please follow the iOS/XCode parts of the template. You deleted them here so I have no idea your XCode, your Pod versions, or if you did manual link etc. All of those are important.

**Comment by zabojad** [comment]
I just installed the rnf v5 and faced the exact same issues as reported by @xcxooxl. However, the first step (header search path) did solve the first issue (firApp.h missing) but the second step (editing RNFirebase.m to replace `import <FirebaseCore/FirebaseCore.h>` by `import <FirebaseCore.h>`) did not solve the second issue at my end.

I ended up executing `mkdir -p Pods/Headers/Public/FirebaseCore && cp Pods/FirebaseCore/Firebase/Core/Public/* Pods/Headers/Public/FirebaseCore/` as suggested by @mikehardy [there](https://github.com/invertase/react-native-firebase/issues/2163#issuecomment-495929760) and removed the fixes proposed by @xcxooxl and then my project eventually builded successfully.

@mikehardy, thank you for your fix. If this is the definitive fix for that issue, it should be mentioned in the install steps there : https://rnfirebase.io/docs/v5.x.x/installation/ios
That would have saved me a couple of hours...

**Comment by mikehardy** [comment]
@zabojad sorry that spent some of your time, but I was waiting for someone else to confirm the fix before working on the docs. I'd like a *real* fix but haven't had time yet. If you want to make a PR for the docs on the 5.x.x branch it would be welcome - there is an edit button on every docs page and editing markdown for PRs is possible in the github web UI
