### ISSUE TITLE
The [[DEFAULT]] firebase app has not been initialized!

### ISSUE THREAD

**Issue by rambo006mm** [invertase/react-native-firebase#2187]
![Screenshot_20190602_125605](https://user-images.githubusercontent.com/45843037/58758247-1fd08c00-8536-11e9-9c82-c45377facde8.jpg)

apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }// Top-level build file where you can add configuration options common to all sub-projects/modules.

    defaultConfig {
        applicationId "com.learning_medium"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-google-signin')

    implementation project(':react-native-firebase')
    implementation project(':react-native-gesture-handler')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules

     implementation "com.google.android.gms:play-services-base:16.1.0" //firebase
      implementation "com.google.firebase:firebase-core:16.0.9"//firebase

        implementation "com.google.firebase:firebase-auth:17.0.0"

}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

//manifest here

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.learning_medium">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

 OUTPUT GOES HERE
```
![Screenshot_20190602_125605](https://user-images.githubusercontent.com/45843037/58758238-f879bf00-8535-11e9-9e97-ecc784c8a6b2.jpg)


<!-- change `[ ]` to `[x]` to select an option(s) -->

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>


<!-- Thanks for reading this far down ❤️  -->
<!-- High quality, detailed issues are much easier to triage for maintainers -->

<!-- For bonus points, if you put a 🔥 (:fire:) emojii at the start of the issue title we'll know -->
<!-- that you took the time to fill this out correctly, or, at least read this far -->

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

![Screenshot_20190602_125605](https://user-images.githubusercontent.com/45843037/58758241-0c252580-8536-11e9-9b3e-ca003c49e684.jpg)

**Comment by mikehardy** [comment]
This issue report is terribly misformatted, I can't parse through it.
However, you can look at the react-native-firebase-starter to see what needs to be done. It's probably not following instructions with regard to your java Application object but I'm just guessing https://github.com/invertase/react-native-firebase-starter/blob/master/android/app/src/main/java/com/invertase/rnfirebasestarter/MainApplication.java#L44

**Comment by Subway19** [comment]
I was getting this error and I resolved this after a lot of efforts. Now I am stuck in this error.

`app.utils(...).checkPlayServicesAvailability is not a function`

Anybody can help me out on this?

**Comment by MeisterTea** [comment]
> I was getting this error and I resolved this **after a lot of efforts**. Now I am stuck in this error.
> 
> `app.utils(...).checkPlayServicesAvailability is not a function`
> 
> Anybody can help me out on this?

...Which are ?

**Comment by Subway19** [comment]
@MeisterTea  I followed all the steps from firebase documentation again. My firebase-core and other services modules which I am using where not updated. So I updated each and every one with as mentioned in the documentation. and this error was gone. For more info, you can see the issue I opened here - #2380

**Comment by Subway19** [comment]
@MeisterTea 

After closely following - I found that 
`classpath 'com.google.gms:google-services:4.2.0' `   - I get #2380 error.
`classpath 'com.google.gms:google-services:4.1.0' ` - I get  The [[DEFAULT]] firebase app has not been initialized!  error. 

Any clue?

**Comment by MeisterTea** [comment]
Yes, I had your issue earlier.

Follow these steps and it will work

* https://rnfirebase.io/docs/v5.x.x/installation/initial-setup
* https://rnfirebase.io/docs/v5.x.x/installation/android
* in MainApplication.java you should have import ```io.invertase.firebase.RNFirebasePackage```
The AdMob import shouldn't be there. It's an error from the link script !
Replace it in imports and ```return Arrays.<ReactPackage>asList(``` section
* https://rnfirebase.io/docs/v5.x.x/messaging/android
* https://rnfirebase.io/docs/v5.x.x/notifications/android
* ???
* PROFIT

Please note that you **have to** use "channels" for android
I have an error regarding gradle which wasn't working. I had to remove the "task" keyword in my android/build.gradle like so ```wrapper {```
I also upgraded my gradle in gradle-wrapper.properties: ```distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip```

**Comment by Subway19** [comment]
@MeisterTea  followed your steps, still not working. :(

**Comment by rambo006mm** [comment]
so what i have done when i get this issue i just move my project in new new project and it solved try this u will get the solution

**Comment by infiniteline** [comment]
I have been getting this error and I'm assuming it revolves around having to comment out the following from app/build.gradle.

```
apply plugin: 'com.google.gms.google-services'
```

However, if I don't comment this out, the app fails to build with the following error:

```
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'com.wmm'
```

**Comment by AbhishekNairOfficial** [comment]
Hi, I had this issue running RN 0.60.4
Tried all the above methods, but it didn't work.
In the end, I had to update the version of all the firebase related plugins in android/build.gradle.

**Comment by rambo006mm** [comment]
the way i solve this problem is to bring my project into its previous state or move your project to another projects it will be solved this is only solution

**Comment by fkotsian** [comment]
I have had some success with https://stackoverflow.com/questions/37517860/how-to-handle-firebaseinstanceid-getinstance-gettoken-null/45184967#45184967

See also: https://github.com/invertase/react-native-firebase/issues/2624#issuecomment-535036967

```
<application
  ...
  tools:node="replace"
  ...
>
```
