### ISSUE TITLE
Upload to storage from folder fails

### ISSUE THREAD

**Issue by nes123** [invertase/react-native-firebase#2188]
Trying to upload this file in android to storage using putFile:

content://com.google.android.apps.photos.contentprovider/-1/1/content://media/external/images/media/99/ORIGINAL/NONE/760657124

i am getting this output

I/TAG: Finished scanning /storage/emulated/0/Download/5377181.jpg
I/ReactNativeJS: An unknown error has occurred.
I/ReactNativeJS: { [Error: An unknown error has occurred.]
      framesToPop: 1,
      nativeStackAndroid: 
       [ { methodName: 'createException',
           lineNumber: 1942,
           file: 'Parcel.java' },
         { methodName: 'readException',
           lineNumber: 1910,
           file: 'Parcel.java' },
         { methodName: 'readExceptionFromParcel',
           lineNumber: 183,
           file: 'DatabaseUtils.java' },
         { methodName: 'readExceptionWithFileNotFoundExceptionFromParcel',
           lineNumber: 146,
           file: 'DatabaseUtils.java' },
         { methodName: 'openTypedAssetFile',
           lineNumber: 698,
           file: 'ContentProviderNative.java' },
         { methodName: 'openTypedAssetFileDescriptor',
           lineNumber: 1458,
           file: 'ContentResolver.java' },
         { methodName: 'openAssetFileDescriptor',
           lineNumber: 1295,
           file: 'ContentResolver.java' },
         { methodName: 'openFileDescriptor',
           lineNumber: 1148,
           file: 'ContentResolver.java' },
         { methodName: 'openFileDescriptor',
           lineNumber: 1102,
           file: 'ContentResolver.java' },
         { methodName: '<init>',
           lineNumber: 120,
           file: 'com.google.firebase:firebase-storage@@17.0.0' } ],
      userInfo: null,
      code: 'storage/unknown',
      line: 7812,
      column: 26,

Any ideas what is going wrong? I have tried both on device and emulator and I am getting the same error

**Comment by Ehesp** [comment]
Please follow the issue template so we're able to help. Without versions and code samples it's very hard to help.
