### ISSUE TITLE
when not login firebase, getdownloadurl doesn't work

### ISSUE THREAD

**Issue by TrustOne** [invertase/react-native-firebase#2190]
when I'm login firebase on My App, getdownloadUrl is perfectly working, 
but when I'm not login, the getdownloadUrl is perfectly not working,
as the code below, I tried to put console.log and The ref is fine login or logout,
but inside the log in getdownloadUrl is not working when I'm not login.

 `     const ref = firebase.storage().ref(Photourl);
      console.log(ref);

          ref.getDownloadURL().then(url => {
          console.log("url not");
          console.log(url);
          }) `

**Comment by Ehesp** [comment]
Please follow the issue template with what versions you're using so we can help.

**Comment by TrustOne** [comment]
> Please follow the issue template with what versions you're using so we can help.
I'm using this version
"react-native-firebase": "^5.3.1",

**Comment by mikehardy** [comment]
@TrustOne open a new issue and witness the full issue template - we need that information to help
