### ISSUE TITLE
fix autolink for react-native-firebase v5

### ISSUE THREAD

**Issue by sibelius** [invertase/react-native-firebase#2194]
There are 2 warnings when trying to use autolink with react-native-firebase v5

```
[!] Package react-native-firebase is using deprecated "rnpm" config that will stop working from next release. Please notify its maintainers about it.
```

```
Package react-native-firebase has been ignored because it contains invalid configuration. Reason: Unknown option dependency.platforms.android.buildPatch with value "" implementation project(':react-native-firebase')"" was found. This is either a typing error or a user mistake. Fixing it will remove this message.
```

We can fix the first one, using this config https://github.com/react-native-community/cli/issues/411#issuecomment-498066479:

react-native.config.js
```jsx
module.exports = {
  dependency: {
    platforms: {
      ios: {
        podspec: './ios/RNFirebase.podspec'
      }
    }
  }
};
```

or move the podspec to root folder

I'm not sure about the second warning

**Comment by mikehardy** [comment]
I'll see what I can do - thanks for reporting this @sibelius

**Comment by ameyer117** [comment]
The second one is complaining about ```      "buildPatch": "    implementation project(':react-native-firebase')"``` in package.json. 

If you remove the leading spaces, it will simply just tell you:
```Unknown option dependency.platforms.android.buildPatch with value ""implementation project(':react-native-firebase')"" was found.```

**Comment by mikehardy** [comment]
Until this is fixed, you will want to turn autolink off for react-native-firebase:

You will want a `react-native-.config.js` file in root of your project directory, and it should contain at least this for android:

```javascript
module.exports = { 
  dependencies: { 
    ‘react-native-firebase’: { 
      platforms: { 
        android: undefined 
      } 
    } 
  } 
};
```

You may paste this into your shell in root of your project to do it:

```shell
echo "module.exports = { dependencies: { 'react-native-firebase’: { platforms: { android: undefined } } } };" > react-native.config.js
```

**Comment by ameyer117** [comment]
@mikehardy Didn't seem to have any effect for me. My react native config at the root of my project directory is now: 
```
module.exports = {
  dependencies: {
    'appcenter': {
      platforms: {
        android: null
      }
    },
    'appcenter-crashes': {
      platforms: {
        android: null
      }
    },
    'appcenter-analytics': {
      platforms: {
        android: null
      }
    },
    'react-native-code-push': {
      platforms: {
        android: null
      }
    },
    'react-native-firebase': {
      platforms: {
        android: undefined
      }
    }
  }
}
```

I even re-ran the packager with ```yarn run start --reset-cache```

**Comment by mikehardy** [comment]
it could be that once generated the java file is there for a bit. `npm i —save-dev react-native-clean-project && npx react-native clean-project-auto` to have a fresh go at it

**Comment by mikehardy** [comment]
also, why some null and some undefined? just curious

**Comment by ameyer117** [comment]
@mikehardy tried that tool (which is awesome btw) still no luck honestly :/. I'll try to reproduce a minimal repo with RN 0.60 and see if I can debug it further. As far as the null/undefined. I just wanted to do exactly what you said instead of making any assumptions.

**Comment by mikehardy** [comment]
Hmm - I’ll try also - if you can reproduce in https://github.com/mikehardy/rn-androidx-demo/blob/master/make-demo.sh for AndroidX/jetifier issues or https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh for react-native-firebase issues it’s really easy for us to then retry. Although if it’s blowing up on RN0.60 then it should be obvious - I’m just about to travel and haven’t had time / won’t have time, sorry

As for null or undefined - I’m certain the code I pasted in worked for react-native-fbsdk when I was testing it for rn-androidx-demo (they fixed their repo so auto-link worked since then, so I took it out). That said, if you are also certain your worked then I think we’ve learned null *or* undefined will work

**Comment by mikehardy** [comment]
@Salakar here’s the v5 autolink issue if you’re curious - I am not sure I’ll have time to push the 2 merged/pending changes post-v5.5.4 out as a v5.5.5 before I go, so at this point if you’ve got time, awesome :-)

**Comment by bramski** [comment]
The suggested fix here fails on RN 0.60:
```
./node_modules/.bin/react-native config --verbose
error Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at isValidRNDependency (/Users/bram/source/applydigital/zo-react-native/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/config/config.js:13:109)
    at Object.keys.forEach.item (/Users/bram/source/applydigital/zo-react-native/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/config/config.js:20:10)
    at Array.forEach (<anonymous>)
    at filterConfig (/Users/bram/source/applydigital/zo-react-native/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/config/config.js:19:38)
    at Object.func (/Users/bram/source/applydigital/zo-react-native/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/config/config.js:31:32)
    at Command.handleAction (/Users/bram/source/applydigital/zo-react-native/node_modules/react-native/node_modules/@react-native-community/cli/build/cliEntry.js:166:21)
    at Command.listener (/Users/bram/source/applydigital/zo-react-native/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:197:13)
    at Command.parseArgs (/Users/bram/source/applydigital/zo-react-native/node_modules/commander/index.js:651:12)
```

**Comment by ibtesamlatif2997** [comment]
Is this issue fixed?  :-)

I am getting this warning during build 

> warn Package react-native-firebase has been ignored because it contains invalid configuration. Reason: Unknown option dependency.platforms.android.buildPatch with value "" implementation project(':react-native-firebase')"" was found. This is either a typing error or a user mistake. Fixing it will remove this message.

After adding react-native.config.js. Getting error => Text must not be null or empty

```
module.exports = {
  dependencies: {
    ‘react-native-firebase’: {
      platforms: {
        android: undefined
      }
    }
  }
};
```

**Comment by massivebrains** [comment]
Anyone with a working solution to this?

**Comment by apps-and-ideas** [comment]
Has anyone found a fix yet for the issue?

**Comment by zico4reel** [comment]
Hi guys, I've being able to get a solution for it, all you need to do is download this file react-native.config.js from this repo https://github.com/zico4reel/React-Native-Firebase-implementation-fix and place it in the react-native-firebase directory which is inside your node_modules worked like a charm for me when I wrote it, So I felt I should share it for others as well

**Comment by zico4reel** [comment]
> Has anyone found a fix yet for the issue?

Yea, I just added a repo link I created for the fix I did

**Comment by paolospag** [comment]
@zico4reel and for iOS?

**Comment by zico4reel** [comment]
@paolospag Oh yea, forgot  to work on that, noticed the attention here was on android, Although I have little knowledge on iOS workings, I'd do that later in the day, if someone else has not fixed it already

**Comment by paolospag** [comment]
This [PR](https://github.com/invertase/react-native-firebase/pull/2335) should solve all the problems related to autolinking

**Comment by sibelius** [comment]
After the PR we still need to include some packages manually

```jsx
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;
import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;

@Override
    protected List<ReactPackage> getPackages() {
    @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();

      packages.add(new RNFirebaseMessagingPackage());
      packages.add(new RNFirebaseNotificationsPackage());

      return packages;
    }
````

Good enough for me, tks guys
