### ISSUE TITLE
Update RN Firebase Performance to match firebase-perf 17.0.0 API updates

### ISSUE THREAD

**Issue by clementlamoureux** [invertase/react-native-firebase#2198]
## Issue

When upgrading to Firebase Performance 17.0.0, an exception is thrown from RNFirebasePerformance.java:126 as it still uses `incrementCounter` method whereas this method has been deleted from android package.

From [Firebase Performance docs](https://firebase.google.com/support/release-notes/android#version_1700) : 
```
Performance Monitoring version 17.0.0
Removed the deprecated counter API. Use metrics API going forward.
```

This issue is related to a [previous closed issue](https://github.com/invertase/react-native-firebase/issues/2175#issue-449582847).

The package.json version of react-native-firebase is **5.4.2**.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

Not relevant
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy

...
allprojects {
    repositories {
        configurations.all {
            resolutionStrategy {

                force "com.google.firebase:firebase-perf:17.0.0" // previously 16.2.5
            }
        }
    }
}
..

```

#### `android/app/build.gradle`:

```groovy
dependencies {
    implementation(project(':react-native-firebase')) {
      transitive = false
    }
    implementation 'com.google.firebase:firebase-perf:17.0.0' // previously 16.2.5
}
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

``` 
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
      Memory: 1.82 GB / 15.85 GB
    Binaries:
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [X] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `com.google.firebase:firebase-perf`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Related thought: it seems undeniable that v5 will need breaking changes until v6 is out. 

As a library user I'm keen to stay current with Google updates, but I rely on semver and node version ranges in my dependencies to stay sane.

I think the two desires can be balanced though

Maybe we could have an official notice that react-native-firebase v5 will use a  modified semver, specifically compressing semver into the x/y on 5.x.y, where X is breaking change, and Y is any other change you can safely update to, but might have a feature.

I think that is reality right now anyway with 5.2 -> 5.3 ? If it was formalized with the recommendation of a different package.json reference (a '~' versus a '^' to only auto-accept "semver patch" / "rnfb-v5 minor/patch" in this idea)

As a consumer, I'd dig that and it would free the community to maintain v5 as google moves forward while the v6 reorg continues

What do you think @Salakar  ? If you like it, I could work up a docs PR.

**Comment by mikehardy** [comment]
Then I could probably work up some PRs to match recent changes as well - or maybe @clementlamoureux could :-)
