### ISSUE TITLE
RNF PushNotifications supports APNs Key?

### ISSUE THREAD

**Issue by ucvdesh** [invertase/react-native-firebase#2199]
I'm having problems with notifications in iOS since changed from APNs Certificate to APNs Key. When i send a Push Notifications through FCM using Postman or Firebase Console, the notification body and title returns as **_Undefined_**, it was working perfect, then I changed the APNs and 2 days later starts failing notifications. 

I was wondering if there in't support por APNs Key?

**Comment by mikehardy** [comment]
I use APNs Key, I get messages. This stuff is very very subtle though. And maybe you need to expire a token and get a new token, I dunno - there are other issues about that, but to answer your question, APNs Keys work

**Comment by ucvdesh** [comment]
Thanks, @mikehardy. Actually i'm having something weird issue with FCM token. Even if my token it's old and getToken() return a new one, if i try to send a PN to the old FCM Token server return **_success: 1_**, also return the same when trying to send to a new FCM token. How can I expire old tokens?

**Comment by mikehardy** [comment]
I wish I knew! I'd try to help. This was reported recently though - check the issues list for something updated in the last couple days, there was discussion very recently about token oddities
