### ISSUE TITLE
How to keep a user logged in

### ISSUE THREAD

**Issue by manjeets12** [invertase/react-native-firebase#22]
is there a way to keep a user logged in I mean authentication should not lost even after refreshing the app?

**Comment by Ehesp** [comment]
Yeah this should work as default. You do however need to check for this yourself when the app boots. I do something like so in the "first step component" of my app (cut down a lot):

```
class App extends React.Component {

  constructor() {
    super();
    this.state = {
      loading: true,
      authenticated: false,
    };
  }

  componentDidMount() {
    firebase.auth().onAuthStateChanged((user) => {
      if (user) {
        this.setState({ loading: false, authenticated: true });
      } else {
        this.setState({ loading: false, authenticated: false });
      }
    });
  }

  render() {
    if (this.state.loading) return null; // Render loading/splash screen etc

    if (!this.state.authenticated) {
      return <Login />;
    }

    return <Home />;
  }
}
```

**Comment by rgm93** [comment]
Thanks so much @Ehesp! You're amazing!

**Comment by mayuraitavadekar** [comment]
@Ehesp I have my express server issuing JWT tokens to my react-native app on signin. So what should I do in this case. even if I store JWT token in AsyncStorage, it is going to expire after some time.

**Comment by Ehesp** [comment]
When the app boots, you could fire a "ping" request at the server which returns a refreshed token (or checks whether it's expired or not. If it's expired, show them the login page.

Also, each time a request is made to the server also return a refreshed token and keep updating it.

**Comment by mayuraitavadekar** [comment]
Thanks @Ehesp :)

**Comment by AnikDey-exe** [comment]
Tysm @Ehesp this helped very much!

**Comment by Shahriar-Bhuiyan** [comment]
I am also facing the same issue but I want to use Redux and firebase to check my authentication but when I refresh my app it log me out. 
i have create app.js login.js component and imported auth from my firebase.js file.

I couldn't understand how to configure this
