### ISSUE TITLE
How do i set/create a local path to download files to

### ISSUE THREAD

**Issue by vahuja13** [invertase/react-native-firebase#220]
Hi,
If I understand the storage API correctly, when doing a 'downloadFile', I need to provide a local path on the device to download the file to. How can I know/provide this? Thanks in advance.

**Comment by vahuja13** [comment]
In my use case, I actually just needed the https url so that i could plug it into a react-native `Image` component. So i could do `getDownloadURL`

**Comment by ollieh-m** [comment]
Hi, 

I'm struggling with this issue - are there any examples of what the local path on the device should be. 

The below is error-ing with `The specified device file path is invalid or is restricted.`:
```
const filePath = `/images/abc/123`
return this.storage
  .ref(filePath)
  .downloadFile(filePath)
  .then( (downloadedFile) => {
    return filePath;
  })
```

Many thanks

**Comment by Salakar** [comment]
@ollieh-m see the examples here: https://rnfirebase.io/docs/v4.3.x/storage/reference/Reference#downloadFile

The argument passed to `downloadFile(here)` must be a full path to a directory on the local device - not the ref path (that's the path on Firebase Storage).

Hope that helps.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by ollieh-m** [comment]
Great, thank you! That example pointed me to this, which is what I was missing: `https://rnfirebase.io/docs/v4.3.x/storage/reference/storage#Native`
