### ISSUE TITLE
when not login firebase, getdownloadurl perfectly not working

### ISSUE THREAD

**Issue by TrustOne** [invertase/react-native-firebase#2204]
when I'm login firebase on My App, getdownloadUrl is perfectly working,
but when I'm not login, the getdownloadUrl is perfectly not working,
as the code below, I tried to put console.log and The ref is fine login or logout,
but inside the log in getdownloadUrl is not working when I'm not login.

		` const ref = firebase.storage().ref(Photourl);
		console.log(ref);                         //it's working, and nothing strange

      ref.getDownloadURL().then(url => {   // this is not working 
      console.log("url not");
      console.log(url);
      }) `

Environment
Application Target Platform:Both
Development Operating System: Windows
Build Tools: VScode
React Native version: 0.59.5
React Native Firebase Version: 5.3.1
Firebase Module: Firesotre, GetdownloadUrl
Are you using typescript? No

**Comment by mikehardy** [comment]
Hmm. I dunno, maybe you have security rules on firestore? I can't see why it would work one way but not the other

**Comment by Ehesp** [comment]
Are you catching errors from the promise? It maybe coming through there as an error.

**Comment by TrustOne** [comment]
> Are you catching errors from the promise? It maybe coming through there as an error.

no errors happen

**Comment by TrustOne** [comment]
> Hmm. I dunno, maybe you have security rules on firestore? I can't see why it would work one way but not the other

I have no security rules,

**Comment by Ehesp** [comment]
> I have no security rules,

By default security rules require authentication. You have to manually set these to be public.

**Comment by mikehardy** [comment]
Yeah - here's all sorts of example stuff 

https://stackoverflow.com/questions/37374868/how-to-get-url-from-firebase-storage-getdownloadurl

- this is a security issue, and maybe an issue with not getting the url correctly from the callback? I don't believe it is a module issue though, so closing

**Comment by TrustOne** [comment]
My Repo is https://github.com/TrustOne/farmers
file is HomeTab.js

**Comment by TrustOne** [comment]
Thank you I'll find out

**Comment by TrustOne** [comment]
Thank you so much ,
The rule was setting like this,

service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth!=null;
    }
  }
}

I changed just before, And it's perfectly working....

sorry to bother you guys, It won't happen again

**Comment by mikehardy** [comment]
Glad that worked! And no problem, plenty of problems everywhere and normally not so easy to solve. Definitely search stackoverflow first, but if there's a problem definitely open an issue. Good luck
