### ISSUE TITLE
Axios vulnerability

### ISSUE THREAD

**Issue by patrick-domegan-rbc** [invertase/react-native-firebase#2208]
## Issue

There is an issue reported with Axios (Affecting axios package, versions <0.18.1) which is used by react-native-firebase
https://snyk.io/vuln/SNYK-JS-AXIOS-174505

---

## Project Files

 react-native-firebase/package.json 
### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Got it - we're working on some other things for v5 and getting CI green. I'll do an npm update there once we've got the branch in shape to tolerate change. Should be soon

**Comment by Salakar** [comment]
Thanks for the headsup; this is only a dev dependency and is not used in the rnfb code itself, it's only used on tests/ci.

Thanks for looking at this @mikehardy

**Comment by mikehardy** [comment]
This is closed on v5 and as it is a devDependency does not require a release.
Regardless, we will probably have a v5 release soon so it will be published in a released version as well
v6 needs a yarn update sweep in general and this will be fully resolved then

**Comment by mikehardy** [comment]
released versions no longer have this problem, I'm going to close this
