### ISSUE TITLE
For child_added snapshots, seeing parent key instead of child key in snapshot.ref.key

### ISSUE THREAD

**Issue by TiraO** [invertase/react-native-firebase#221]
I just switched over to `react-native-firebase` from regular old web `firebase`, and I'm seeing an issue with the way keys are showing up in `child_added` events. I'm getting the parent's key showing up as `child.ref.key`. I don't see the child's key anywhere in the `react-native-firebase` `child_added` event snapshot.
(I've only tried it on Android.)

[Here's a test that demonstrates the issue](https://github.com/TiraO/react-native-firebase/commit/e36a38136cd90a128fd522a497e3f6f79e9cdff7)

**Comment by Salakar** [comment]
@TiraO thanks for the report and the test! Am looking into this at the moment, not sure why it would show the parent key though as the native side directly grabs the key from the native snapshot here: https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/Utils.java#L92 which is passed through to here: https://github.com/invertase/react-native-firebase/blob/master/lib/modules/database/snapshot.js#L21

If I understood the issue correctly you're saying `snapshot.key` is returning the parent ref's key?

**Comment by Salakar** [comment]
Ah I think I've found the issue, derp, let me see if I can get a fix in order.

**Comment by Salakar** [comment]
Have figured out a fix - will push up a patch version to npm shortly.

**Comment by Salakar** [comment]
@TiraO fixed in https://github.com/invertase/react-native-firebase/releases/tag/v2.0.1

Thanks again!
