### ISSUE TITLE
Android setBigText not working

### ISSUE THREAD

**Issue by windydang26** [invertase/react-native-firebase#2213]
## Issue

Describe your issue here
    // Build a channel
    const channel = new firebase.notifications.Android.Channel(channelId, 'Equix Android Notification Channel', firebase.notifications.Android.Importance.Max)
        .setDescription('Equix Android Notification Channel');

    // Create the channel
    firebase.notifications().android.createChannel(channel);

    const notification = new firebase.notifications.Notification({
        show_in_foreground: true
    })
        .setNotificationId(notificationId)
        .setBody(body)
        .setTitle(title)
        .setData(data)
        .android.setChannelId(channelId)
        .android.setBigText(body)
        .android.setVibrate(500)
        .android.setPriority(firebase.notifications.Android.Priority.Max)
        .ios.setBadge(badge)
    if (Controller.getSound() === 'default' || Util.isAndroid()) { // with android < 8 need set sound to show head-up notification
        notification.setSound('default')
    }

   firebase.notifications().displayNotification(notification)
---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
No versions, please follow the template

**Comment by windydang26** [comment]
sorry! i'm using RNN ver 4.3.8. and notification on android only show one line although i was set big text as example.
