### ISSUE TITLE
Hide a push notification on a particular condition sent in notification data

### ISSUE THREAD

**Issue by NIJAAHNANDH** [invertase/react-native-firebase#2218]
I have checked all the rnfirebase docs no where its mentioned, Is there any way to hide a notification when the app is in background or app is in closed condition, I want to hide a push notification if a key in the notification data is set to false.

**Comment by mikehardy** [comment]
Hi there! What you're asking, if I understand correctly, is how to send a silent push notification (firebase calls this part "messaging") to a device, and generate a local notification as your app handles it. That's the basic 1-2 set of actions to do. It is very difficult to get these things correct (silent push notifications on both platforms, successfully waking up the app and handling things quickly enough, then doing your local notification correctly). But it all works.

**Comment by NIJAAHNANDH** [comment]
Yes @mikehardy  I'm asking for silent push notifications only. This is my code which I have written in bgmessaging.js. If the value of popup is true only push notification should display or else it should not be displayed.

```
import firebase from "react-native-firebase";
import type { RemoteMessage } from 'react-native-firebase';

export default async (message) => {
    const notificationToBeDisplayed = new firebase.notifications.Notification({
      data: message.data,
      sound: 'default',
      title: message.title,
      body: message.body
    });
  
    if (Platform.OS === 'android') {
      notificationToBeDisplayed.android
        .setPriority(firebase.notifications.Android.Priority.Max)
        .android.setChannelId('channel-bublenet')
        .android.setVibrate(1000);
    }
    if (message.data && message.data.popup && message.data.popup === 'true') {
        await firebase.notifications().displayNotification(notificationToBeDisplayed);
    }
  }
```

**Comment by mikehardy** [comment]
code in isolation is not useful when debugging messaging, in my experience. My headless task didn't work when it was hooked too late in my app's initialization for instance. Post a demonstration repo on github maybe if you're still having problems

I will say there isn't a console.log statement at all here. How do you know it's working? I would have no idea. And I didn't realize my headless task wasn't even hooked until I put logging in. So add some logging to the task itself that should log as it is initialized, and make sure it is actually initialized

**Comment by saczuac** [comment]
Is it possible ?, there is any solution for this ?, this issue on github it is closed, but no real answer for the problem was post on it

**Comment by poojalivin** [comment]
> Is it possible ?, there is any solution for this ?, this issue on github it is closed, but no real answer for the problem was post on it

have you find some solution?
