### ISSUE TITLE
putFile not give return response after store image in firebase storage(ios only)

### ISSUE THREAD

**Issue by bhushannirmal** [invertase/react-native-firebase#2219]
## Issue

Hello
I am adding image by using putFile in firebase storage, The image is successfully added in storage from both IOS and android devices, but after adding the images in storage i can get response from firebase in only android devices.

In IOS device image is successfully inserted but i can not get response(downloadURL,ref) from firebase.

**In android device, It is working perfectly.**

Below is my code:

```javascript
firebase.storage().ref('imagepath')
.putFile(response.path, metaData)
.then(function(data)
{
    console.log('Uploaded Successfully',data.downloadURL, data.ref, filename);
    config.uploadedSuccess = '1'
    dispatch(uploadPhotoOfferSuccessAction(data.downloadURL, data.ref, filename))
})
.catch((error) => {
    console.log('Error', error);
    dispatch(uploadPhotoOfferFailureAction(error.message))})
}
```
Many thanks in advance

**Comment by mikehardy** [comment]
I altered your code to use triple-backticks with javascript highlighting - a very neat markdown trick that means I can actually read it ;-)

**Comment by mikehardy** [comment]
I wonder if this is some sort of timeout thing. Apple is aggressive about killing apps. Maybe better to use a cloud function that kicks a message back to the device via token and handles all the post-processing via hook or something. Or that might be worse I don't know - certainly more complicated.

You didn't follow the template either way, please find the template (it's in this repo), paste it back in, fill it out, and also include the logs from both platforms, and we can reopen and look

**Comment by Salakar** [comment]
You should also be using the `getDownloadURL()` method to get the URL, `state.downloadURL` is deprecated on both SDKS; docs: https://rnfirebase.io/docs/v5.x.x/storage/reference/Reference#getDownloadURL
