### ISSUE TITLE
Android Build fail!

### ISSUE THREAD

**Issue by michaelspeed** [invertase/react-native-firebase#222]
While building for android i am getting this error - 

Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zze.class

my deps are - 

> compile(project(':react-native-firebase')) {
            transitive = false
          }
    compile "com.google.firebase:firebase-core:11.0.2"
    compile "com.google.firebase:firebase-storage:11.0.2"
    compile project(':react-native-fbads')
    compile project(':react-native-photo-view')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-spinkit')
    compile project(':react-native-video')
    compile 'com.facebook.android:facebook-android-sdk:4.+'
    compile project(':react-native-link-preview')
    compile project(':react-native-image-resizer')
    compile project(':react-native-image-picker')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-camera')
    compile project(':react-native-audio-toolkit')
    compile project(':react-native-navigation')
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:25.3.1"
    compile "com.facebook.react:react-native:+"

any thoughts how to fix this?

**Comment by Salakar** [comment]
For future reference for anyone searching for this issue: http://invertase.io/react-native-firebase/#/faqs?id=android-duplicate-dex-files-error-build-time-error

It's in the FAQ section of the docs.
