### ISSUE TITLE
error on release build "parsing google-services.json file"

### ISSUE THREAD

**Issue by rahultatvasoft** [invertase/react-native-firebase#2230]
> Task :app:processReleaseGoogleServices
Parsing json file: D:\Projects\wamp\www\Reactnative-projects\Hobiz\Hobiz_Git\android\app\google-services.json

> Task :app:mergeReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT error: check logs for details

**Comment by mikehardy** [comment]
We do builds all the time. Every CI does a build. This must be a project error. If you can post a reproduction we can help, but you have not even followed the template, sorry.

**Comment by VadimCeretean** [comment]
did you fix this error?
