### ISSUE TITLE
🔥Messaging error: Invalid notification (no valid small icon)

### ISSUE THREAD

**Issue by JinYuSha0** [invertase/react-native-firebase#2231]
## Issue

I trying to send notification in firebase  console, but sometime can receive that more time can't,first i thought it is network problem until i see the error log:

 DisplayNotificationTask: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=channelId pri=1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0xff000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
06-13 20:51:47.801  2070  5153 E DisplayNotificationTask:       at android.app.NotificationManager.notifyAsUser(NotificationManager.java:417)
06-13 20:51:47.801  2070  5153 E DisplayNotificationTask:       at android.app.NotificationManager.notify(NotificationManager.java:379)
06-13 20:51:47.801  2070  5153 E DisplayNotificationTask:       at io.invertase.firebase.notifications.DisplayNotificationTask.doInBackground(DisplayNotificationTask.java:383)
06-13 20:51:47.801  2070  5153 E DisplayNotificationTask:       at io.invertase.firebase.notifications.DisplayNotificationTask.doInBackground(DisplayNotificationTask.java:32)
06-13 20:51:47.801  2070  5153 E DisplayNotificationTask:       at android.os.AsyncTask$2.call(AsyncTask.java:333)
06-13 20:51:47.801  2070  5153 E DisplayNotificationTask:       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-13 20:51:47.801  2070  5153 E DisplayNotificationTask:       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
06-13 20:51:47.801  2070  5153 E DisplayNotificationTask:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-13 20:51:47.801  2070  5153 E DisplayNotificationTask:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-13 20:51:47.801  2070  5153 E DisplayNotificationTask:       at java.lang.Thread.run(Thread.java:764)

Is there a good way to fix it?

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Probably by putting in a valid small icon?

`
DisplayNotificationTask: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=channelId pri=1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0xff000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
`

**Comment by vongohren** [comment]
@mikehardy is there no possibility to rely on the default small icon?

**Comment by vongohren** [comment]
Well yeah it fixed it for me as well, but I do believe when sending off the recieved notification, that would acctually use a default icon, why would we have to set it again, when there potentially is a default icon.

**Comment by vongohren** [comment]
Also the error log is not optimal, as it just sends cannot send. But the ADB log clearly states the problem :)

**Comment by Boburbek6010** [comment]
Is there any solution for fixing this problem. Attention : I am using Awesome Notification package in flutter...


#
E/Android: [Awesome Notifications](25254): Invalid notification (no valid small icon): Notification(channel=basic_channel shortcut=null contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x11 color=0xff009688 vis=PRIVATE) (NotificationThread:58)
W/System.err(25254): me.carda.awesome_notifications.core.exceptions.AwesomeNotificationsException: Invalid notification (no valid small icon): Notification(channel=basic_channel shortcut=null contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x11 color=0xff009688 vis=PRIVATE)
W/System.err(25254): 	at android.app.NotificationManager.fixNotification(NotificationManager.java:606)
W/System.err(25254): 	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:585)
W/System.err(25254): 	at android.app.NotificationManager.notify(NotificationManager.java:534)
W/System.err(25254): 	at android.app.NotificationManager.notify(NotificationManager.java:510)
W/System.err(25254): 	at me.carda.awesome_notifications.core.managers.StatusBarManager.showNotificationOnStatusBar(StatusBarManager.java:86)
W/System.err(25254): 	at me.carda.awesome_notifications.core.threads.NotificationSender.showNotification(NotificationSender.java:260)
W/System.err(25254): 	at me.carda.awesome_notifications.core.threads.NotificationSender.doInBackground(NotificationSender.java:147)
W/System.err(25254): 	at me.carda.awesome_notifications.core.threads.NotificationSender.doInBackground(NotificationSender.java:32)
W/System.err(25254): 	at me.carda.awesome_notifications.core.threads.NotificationThread.runOnForegroundThread(NotificationThread.java:106)
W/System.err(25254): 	at me.carda.awesome_notifications.core.threads.NotificationThread.execute(NotificationThread.java:34)
W/System.err(25254): 	at me.carda.awesome_notifications.core.threads.NotificationSender.send(NotificationSender.java:101)
W/System.err(25254): 	at me.carda.awesome_notifications.core.AwesomeNotifications.createNotification(AwesomeNotifications.java:569)
W/System.err(25254): 	at me.carda.awesome_notifications.AwesomeNotificationsPlugin.channelMethodCreateNotification(AwesomeNotificationsPlugin.java:1274)

**Comment by mikehardy** [comment]
@Boburbek6010 this has nothing to do with Flutter, it's a react-native package :thinking: ?
