### ISSUE TITLE
crashlytics.recordCustomError ?

### ISSUE THREAD

**Issue by timomeara** [invertase/react-native-firebase#2233]
it's in the docs:
[https://rnfirebase.io/docs/v5.x.x/crashlytics/reference/crashlytics#recordCustomError](https://rnfirebase.io/docs/v5.x.x/crashlytics/reference/crashlytics#recordCustomError
)

but not in the interface:
```namespace crashlytics {
      interface Crashlytics {
        /**
         * Forces a crash. Useful for testing your application is set up correctly.
         */
        crash(): void;

        /**
         * Logs a message that will appear in any subsequent crash reports.
         */
        log(message: string): void;

        /**
         * Logs a non fatal exception.
         */
        recordError(code: number, message: string): void;

        /**
         * Set a boolean value to show alongside any subsequent crash reports.
         */
        setBoolValue(key: string, value: boolean): void;

        /**
         * Set a float value to show alongside any subsequent crash reports.
         */
        setFloatValue(key: string, value: number): void;

        /**
         * Set an integer value to show alongside any subsequent crash reports.
         */
        setIntValue(key: string, value: number): void;

        /**
         * Set a string value to show alongside any subsequent crash reports.
         */
        setStringValue(key: string, value: string): void;

        /**
         * Set the user ID to show alongside any subsequent crash reports.
         */
        setUserIdentifier(userId: string): void;

        /**
         * Enable Crashlytics reporting. Only avaliable when disabled automatic initialization
         */
        enableCrashlyticsCollection(): void;
      }
    }```

or am i missing something obvious?

**Comment by mikehardy** [comment]
Sorry - this was a PR that was all queued and ready for version 5.4.3 and reverted at the last minute, after the docs were merged. #1940 / https://github.com/invertase/react-native-firebase/pull/2224 

We are still actively troubleshooting it and hoping to get it in, but if it takes more than a day longer I'll revert the docs as well

**Comment by bthurlow** [comment]
See PR #2237 for updates.

**Comment by mikehardy** [comment]
The code that implements the docs just merged on to master - you can pull it directly via github if you like, or I will do another release probably middle of next week with this and other changes. Thanks to @bthurlow for getting it all squared away!

I will leave this open until I do the release in case others notice it and come looking

**Comment by mikehardy** [comment]
This is live now with v5.5.0
