### ISSUE TITLE
Auth email expiration time

### ISSUE THREAD

**Issue by nes123** [invertase/react-native-firebase#2236]
Hi, I didnt find any documentation for the expiration times of password rest, email verification etc. I am especially interested in passwordless sign-in with email link (signInWithEmailLink). It seems that the links expire after a hour and I am curious if we can programmatically extend this time. I am using these links to invite users to my app and since I am the one to send them it usually take the users several hours to open them.

**Comment by mikehardy** [comment]
I don't know - I don't see any API support for it in the underlying SDKs but I might be missing something. You might try stackoverflow and use the firebase tags to catch the attention of the SDK team, or try their github?

**Comment by Ehesp** [comment]
This doesn't exist I'm afraid and is probably more of a security thing. You could use Dynamic Links to build your own flow which handles this, although I appreciate that's not ideal!
