### ISSUE TITLE
putFile upload progress not working while using uuid for file name

### ISSUE THREAD

**Issue by yogeshry** [invertase/react-native-firebase#2238]
My code is as below: 

 const ref = firebase.storage().ref("/images").child(uuid.v4());
        const unsubscribe = ref.putFile(uri).on(
            firebase.storage.TaskEvent.STATE_CHANGED,
            (snapshot) => {
                console.log(snapshot.bytesTransferred);
                let progress = (snapshot.bytesTransferred / snapshot.totalBytes);
                this.setState({uploadProgress: progress})
                if (snapshot.state === firebase.storage.TaskState.SUCCESS) {
                    //predict
                }
            },
            (error) => {
                unsubscribe();
                console.error(error);
            },()=>{
                console.log(this.state.name)
                this.predictOnline(this.state.name)
            })

**Comment by mikehardy** [comment]
I think we literally just merged a fix for this! It's on master but not released yet #2228 with thanks to @jakehedman - should do a release for it this week, until then you may use patch-package or depend on master to get the fix
