### ISSUE TITLE
NotificationOpen object not the same on android and iOS

### ISSUE THREAD

**Issue by mikehardy** [invertase/react-native-firebase#2239]
The `notificationOpen` object is different for `android` and `ios`. This also applies with `getInitialNotification()`

Here's my code
```
firebase.notifications().onNotificationOpened(notificationOpen => {
  const data = Platform.OS === 'android' ? notificationOpen.notification.data.customDataKeyName : notificationOpen.customDataKeyName;
  this.navigate(data);
});
```

![background_test](https://user-images.githubusercontent.com/10791201/53718945-a45c3180-3e97-11e9-9716-fb8be8b642a0.gif)

_Originally posted by @jettandres in https://github.com/invertase/react-native-firebase/issues/1149#issuecomment-469158362_

**Comment by nica0012** [comment]
I am still not able to receive anything in my callback (IOS)... I am getting the notifications okay but nothing is being triggered. 

if someone can please look at this to see if I am doing anything wrong I would greatly appreciate it...

` async componentDidMount() {
    this.checkPermission();
    this.notificationOpenedListener();
  }

  //1
async checkPermission() {
  const enabled = await firebase.messaging().hasPermission();
  if (enabled) {
      this.getToken();
  } else {
      this.requestPermission();
  }
}

  //2
  async requestPermission() {
    try {
        await firebase.messaging().requestPermission();
        // User has authorised
        this.getToken();
    } catch (error) {
        // User has rejected permissions
        console.log('permission rejected');
    }
  }

  //3
async getToken() {
  let fcmToken = await AsyncStorage.getItem('fcmToken');
  if (!fcmToken) {
      fcmToken = await firebase.messaging().getToken();
      if (fcmToken) {
          // user has a device token
          await AsyncStorage.setItem('fcmToken', fcmToken);
      }
  }
}

////////////////////// Add these methods //////////////////////
  
  //Remove listeners allocated in createNotificationListeners()
  componentWillUnmount() {
    this.notificationListener();
    this.notificationOpenedListener();
  }
  
  async createNotificationListeners() {
    /*
    * Triggered when a particular notification has been received in foreground
    * */
    this.notificationListener = firebase.notifications().onNotification((notification) => {
        const { title, body } = notification;
        this.showAlert(title, body);
    });
  
    /*
    * If your app is in background, you can listen for when a notification is clicked / tapped / opened as follows:
    * */
    this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
        const { title, body } = notificationOpen.notification;
        // const { screen } = notificationOpen.data;
        this.showAlert(title, body);
        //alert won't show when app opens from notifiation...
        // alert('NOTIFICATION OPENED' + screen);
    });
  
    /*
    * If your app is closed, you can check if it was opened by a notification being clicked / tapped / opened as follows:
    * */
    const notificationOpen = await firebase.notifications().getInitialNotification();
    if (notificationOpen) {
        const { title, body } = notificationOpen.notification;
        this.showAlert(title, body);
    }
    /*
    * Triggered for data only payload in foreground
    * */
    this.messageListener = firebase.messaging().onMessage((message) => {
      //process data message
      console.log(JSON.stringify(message));
    });
  }
  
  showAlert(title, body) {
    Alert.alert(
      title, body,
      [
          { text: 'OK', onPress: () => console.log('OK Pressed') },
      ],
      { cancelable: false },
    );
  }`

**Comment by Ehesp** [comment]
Hey all 👋 There's a draft PR available which fixes this issue and others, please check it out: https://github.com/invertase/react-native-firebase/pull/3339

We'll be doing a RC release once a few more things are implemented.

**Comment by Ehesp** [comment]
(Going to close this one, not had much interaction).
