### ISSUE TITLE
iOS React/RCTEventEmitter.h file not found

### ISSUE THREAD

**Issue by hama** [invertase/react-native-firebase#224]
"react": "16.0.0-alpha.6",
"react-native": "0.44.0",
"react-native-firebase": "^2.0.0",

<img width="790" alt="qq20170703-195408 2x" src="https://user-images.githubusercontent.com/542227/27791814-7804d1d0-6029-11e7-8359-965c20aacfcb.png">

**Comment by SteffeyDev** [comment]
This is most likely an issue with your CocoaPods or project configuration, and not with this library.  Can you post the contents of your podfile?

**Comment by phetsana** [comment]
Almost same for me, I followed from scratch the installation and got a React/* file not found from RNFirebase

**Comment by chrisbianca** [comment]
@hama @phetsana Have you switched to using the `.xcworkspace` file rather than `.xcproj`?

**Comment by phetsana** [comment]
@chrisbianca I don't know how exactly but It works now ! I guess It's a cleanup and derived data directory delete.

**Comment by Ehesp** [comment]
I'd suggest in the future users need to ensure that they delete everything build/cache wise! @hama please try deleting node_modules, xcode cache & build directories inside your project, let us know if you have further issues.

**Comment by ccorcos** [comment]
Clearing the cache seemed to work, but now it cant find firebase.h! lol
