### ISSUE TITLE
react-native-firebase phone auth on simulator navigating to "about:blank"

### ISSUE THREAD

**Issue by hadare1** [invertase/react-native-firebase#2242]
Hi, out app uses react-native-firebase with phone authentication .
we followed the documentation about enabling reCAPCHA and push notifications , once we enabled push notifications the reCAPCHA stopped working on the simulator (still works on device) . We added the `REVERSED_CLIENT_ID ` as described in the documentation .
once I input the phone number the app transfer me to the reCAPCHA and then to an "about:blank" page and does nothing.

![Simulator Screen Shot - iPhone X - 2019-06-17 at 09 23 52](https://user-images.githubusercontent.com/32154203/59582729-dbbabb00-90e1-11e9-93b4-ab2a94840a5d.png)
![Simulator Screen Shot - iPhone X - 2019-06-17 at 09 23 59](https://user-images.githubusercontent.com/32154203/59582738-e07f6f00-90e1-11e9-8019-b21f66977f61.png)
![Simulator Screen Shot - iPhone X - 2019-06-17 at 09 23 46](https://user-images.githubusercontent.com/32154203/59582740-e2493280-90e1-11e9-8b08-8d4369bc82da.png)

Describe your issue here

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm using Pods and my Podfile looks like:

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jesta' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Jesta
# Required by RNFirebase
pod 'Firebase/Core', '~> 5.15.0'
pod 'Firebase/Auth', '~> 5.15.0'
  target 'Jesta-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

    pod 'react-native-mail', :path => '../node_modules/react-native-mail'

    pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

    pod 'instabug-reactnative', :path => '../node_modules/instabug-reactnative'

  end

  target 'JestaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Jesta-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Jesta-tvOS

end

#### `AppDelegate.m`:
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate
@synthesize oneSignal = _oneSignal;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"Jesta"
                                            initialProperties:nil];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [FIRApp configure];

    NSURL *jsCodeLocation;
    jsCodeLocation = [NSURL URLWithString:@"http://127.0.0.1:8081/index.ios.bundle?platform=ios&dev=true"];

    self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions
                                                         appId:@"88743ac0-c32c-4789-b640-0c92fff49e39"];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

 React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
      Memory: 78.75 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 28
        Build Tools: 28.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  N
</p>
</details>

---

**Comment by mikehardy** [comment]
If I understand correctly, neither push notifications nor phone auth work on the simulator
You must use the firebase ability to specify "known" phone number + code combos for testing in order to do get past phone auth on a simulator, and push notifications won't work. That's for real devices only. I am going to provisionally close this, expecting that it will work for you, but we can reopen if test number+codes don't work for some reason

**Comment by hadare1** [comment]
This is not what I meant. I know push notifications will not work on a simulator..

let me start over.
 
first, I integrated react-native-firebase phone authentication . (I did not enable push notifications yet in my app.) , using the test number and code that I added in firebase with the reCAPCHA I had the phone auth up and running on both the simulator and the device .

then I added push notifications in my app . which also enabled the silent notification on the device therefore no more reCAPCHA on the device - (this still works). 
but on the simulator, which as I understand should take me to the reCAPCHA is not working anymore . after the "verifying you're not a robot" phrase i get navigated to a "about:blank" domain and nothing happens. 
as the screenshots describe.

this issue should not be closed just yet.

**Comment by mikehardy** [comment]
I haven't read your comment (sorry! really busy today) but will reopen sure

**Comment by hadare1** [comment]
Hi, Still have this issue. 
any suggestions?

**Comment by Yahavcaine** [comment]
Having the exact same issue. Could someone could help?

**Comment by hadare1** [comment]
After debugging this issue I realized the bug is not with react-native-firebase but with a third party for the remote notifications (one signal) apparently the issue occurs when the react-native-library is integrated with react-native-onesignal

**Comment by vinpro24** [comment]
having same issue. Any idea please?

**Comment by yoavapi** [comment]
+1

**Comment by yoavapi** [comment]
I have the same issue here.

**Comment by RominHalltari** [comment]
Same issue.

**Comment by mikehardy** [comment]
@RominHalltari does it work on a real device?

**Comment by netfirelabs** [comment]
We are facing the same issue. Even in device.
