### ISSUE TITLE
how can we get email verification code so we can put in this method confirmPasswordReset(code, newPassword)

### ISSUE THREAD

**Issue by nomi9995** [invertase/react-native-firebase#2244]
how can we get email verification code so we can put in this method confirmPasswordReset(code, newPassword)

because this method sendPasswordResetEmail(email) do not provide any email verification code

**Comment by Ehesp** [comment]
Are you using a custom email template?

**Comment by nomi9995** [comment]
@Ehesp no I am not using custom email template

**Comment by nomi9995** [comment]
Are you thers

**Comment by nomi9995** [comment]
@ehesp are you there?

**Comment by JFGHT** [comment]
`admin.auth().generatePasswordResetLink`

;).
