### ISSUE TITLE
package com.google.firebase.platforminfo does not exist

### ISSUE THREAD

**Issue by badrey** [invertase/react-native-firebase#2248]
### Environment
"react-native-firebase": "5.4.0",
"react-native": "0.59.9",
"react": "16.8.3"

Gradle 5.1.1
Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.13.6 x86_64

### Issue
Getting an error for Android build. It fails on task `Task :react-native-firebase:compileDebugJavaWithJavac` with an error:
```

/Users/user/misc/code/mobile/nfl-rn/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/ReactNativeFirebaseAppRegistrar.java:24: error: package com.google.firebase.platforminfo does not exist
import com.google.firebase.platforminfo.LibraryVersionComponent;
                                       ^
/Users/user/misc/code/mobile/nfl-rn/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/FirestoreSerialize.java:488: error: cannot find symbol
        return FieldValue.increment(fieldValueMap.getDouble(TYPE_FIELDVALUE_ELEMENTS));
                         ^
  symbol:   method increment(double)
  location: class FieldValue
/Users/user/misc/code/mobile/nfl-rn/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/ReactNativeFirebaseAppRegistrar.java:34: error: cannot find symbol
      LibraryVersionComponent.create(
      ^
  symbol:   variable LibraryVersionComponent
  location: class ReactNativeFirebaseAppRegistrar
```

**Comment by mikehardy** [comment]
You didn't follow the template - I'm usually able to offer some advice,  but you must follow the template

**Comment by Nehal-29** [comment]
@badrey hey I'm facing same issue.
Did you find the solution ?

"react-native-firebase": "5.6.0",
"react-native": "0.60.4",
