### ISSUE TITLE
Migration Issue: onMessage not being called on iOS 10+ in v2

### ISSUE THREAD

**Issue by SteffeyDev** [invertase/react-native-firebase#225]
After updating to v2, and verifying I have the correct native and javascript versions, it seems that onMessage is never called on iOS when a notification comes in on my physical device, though it works in the iOS simulator.  Notifications still work as expected when opened when the app is in the background.

The root cause is that neither `didReceiveRemoteNotification` method is called in my AppDelegate when a notification should be received, and it appears that the removal of handling the `userNotificationCenter: willPresentNotification: withCompletionHandler:` in v2 is the culprit.  That method is the only one called when a notification is received in the foreground and it contains the correct data that should be passed into onMessage.

Because this method was removed in v2, what was the intended replacement for intercepting foreground messages on iOS 10+ iOS Devices.

**Comment by Salakar** [comment]
cc @chrisbianca 🙈

**Comment by chrisbianca** [comment]
@SteffeyDev sorry for the delay - the methods were removed because Firebase 4.0.0 removed the requirement to include them from their documentation.  My assumption was that it was handling them internally, but perhaps this isn't the case and it's an oversight in their docs.  

I did test background and foreground messages before confirming the change, but will take another look and see whether there's something amiss.

**Comment by SteffeyDev** [comment]
@chrisbianca Thanks for looking into this.  I will admit that foreground messaging does work in the iOS 10.3 simulator, but not on my physical device running iOS 10.3.2 running the exact same code, so it very well may be a misconfiguration on my part.  The fact that the simulator works without that method means that they may have found another way to handle foreground notifications, which would explain the removal, but I have no idea why it would not work on a physical device as well.

**Comment by chrisbianca** [comment]
Ok, so it looks like Firebase have updated their documentation again to include simply:

```
Since iOS 10, you can set UNUserNotificationCenter delegate to receive display notifications from Apple and FIRMessaging remoteMessageDelegate to receive data messages from FCM. If you do not set these two delegates with AppDelegate, method swizzling for message handling is disabled. You'll need to call method appDidReceiveMessage: to track message delivery and analytics.
```

No code to demonstrate what the cryptic note means, just that note!

From this, it does seem that the previous methods are needed, so I've just added them back in and updated the documentation as part of the 2.0.4 release: https://github.com/invertase/react-native-firebase/releases/tag/v2.0.4
