### ISSUE TITLE
Module 'Firebase' not found on @import Firebase (6.0.0-alpha.25)

### ISSUE THREAD

**Issue by davetownsend** [invertase/react-native-firebase#2252]
Wanting to try out `6.0.0-alpha.25` for Analytics only on an existing RN iOS app that is using an exsting pod file.

Using RN 0.59.5

**Steps I've taken:**

1. `yarn add @react-native-firebase/app`
2. `yarn add @react-native-firebase/analytics@alpha`
3. `react-native link @react-native-firebase/analytics`
    - I can see the pod file has been updated with:
 `pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'`
4. Followed these steps to add Firebase credentials. https://invertase.io/oss/react-native-firebase/quick-start/ios-firebase-credentials

**Issue I'm having**
Xcode giving error in `AppDelegate.m`: **Module 'Firebase' not found** on`@import Firebase;` 

Recommended in docs:
<img width="947" alt="Screen Shot 2019-06-18 at 6 30 31 PM" src="https://user-images.githubusercontent.com/91259/59730453-4c9fc700-91f7-11e9-86ed-e35501f25ed7.png">

Libraries were not showing up linked in Xcode as I expected, so i linked them manually:
<img width="203" alt="Screen Shot 2019-06-18 at 6 44 12 PM" src="https://user-images.githubusercontent.com/91259/59731028-7823b100-91f9-11e9-9c63-3b7cd75aae8d.png">
<img width="354" alt="Screen Shot 2019-06-18 at 6 44 39 PM" src="https://user-images.githubusercontent.com/91259/59731027-7823b100-91f9-11e9-8e03-40ba82b779b2.png">

Still getting same error.  Am I missing anything here?

**Comment by mayermatheus** [comment]
I'm having same issue

**Comment by suretarget** [comment]
The doc said supported versions required minimum RN 0.60.0.
[https://invertase.io/oss/react-native-firebase/v6](url)

**Comment by mihaidaviddev** [comment]
Did you link it ?
> yarn add @react-native-firebase/app
react-native link @react-native-firebase/app

https://www.npmjs.com/package/@react-native-firebase/app

**Comment by davetownsend** [comment]
@mihaidaviddev - Yes I did, thanks. Seems I've tried just about every suggested trick with and w/o pods.  Gonna try and spin up a new app to see if this will work.

**Comment by hpelitebook745G2** [comment]
@davetownsend did you find a solution?
