### ISSUE TITLE
Could not find any version that matches androidx.legacy:legacy-support-v4:28.+.

### ISSUE THREAD

**Issue by nahidmbstu** [invertase/react-native-firebase#2255]
Could not find any version that matches androidx.legacy:legacy-support-v4:28.+.
     Versions that do not match:
         1.0.0
         1.0.0-rc02
         1.0.0-rc01
         1.0.0-beta01
         1.0.0-alpha3
         + 1 more
     Required by:
         project :app > project :react-native-firebase

 "react-native-firebase": "^5.2.2",

**Comment by mikehardy** [comment]
Hi there!
The library does not natively support AndroidX #1588 
There are strategies there you can use if your app has to be AndroidX and you have to use this library, namely you should (after reading the docs) do `npm i jetifier && npx jetify` in order to use native android react-native dependencies with an AndroidX project before the dependencies have converted.

This will be project-specific though, it isn't related to this specific library

**Comment by raja09569** [comment]
> Hi there!
> The library does not natively support AndroidX #1588
> There are strategies there you can use if your app has to be AndroidX and you have to use this library, namely you should (after reading the docs) do `npm i jetifier && npx jetify` in order to use native android react-native dependencies with an AndroidX project before the dependencies have converted.
> 
> This will be project-specific though, it isn't related to this specific library

this worked for me

**Comment by mikehardy** [comment]
Glad to hear the success report @raja09569 - thank you, jetifier is also my package, designed with the help of react-native-community to fix these problems but it is brand new so the success reports help.

**Comment by raja09569** [comment]
> Glad to hear the success report @raja09569 - thank you, jetifier is also my package, designed with the help of react-native-community to fix these problems but it is brand new so the success reports help.
i struggled with this issue from 2 days. you saved my day thank you @mikehardy

**Comment by mikehardy** [comment]
next jetify release will have performance improvements and if you rely on it, you might put 
a call to it in postinstall in your package.json so you don't forget to run it. Good luck :-)

**Comment by abhishekmobile** [comment]
> Hi there!
> The library does not natively support AndroidX #1588
> There are strategies there you can use if your app has to be AndroidX and you have to use this library, namely you should (after reading the docs) do `npm i jetifier && npx jetify` in order to use native android react-native dependencies with an AndroidX project before the dependencies have converted.
> 
> This will be project-specific though, it isn't related to this specific library

Awesome answer. This was nagging me for 2 days, and this small solution helped me. Kudos to mike.

**Comment by hakkikonu** [comment]
jetify is life saver!
