### ISSUE TITLE
Build error v5.5.1 - 'FirebaseCore/FIRAnalyticsConfiguration.h' file not found

### ISSUE THREAD

**Issue by smeekmeister** [invertase/react-native-firebase#2259]
Ios no longer builds after upgrading from 5.4.3 to 5.5.1
Done everything as per release notes in rn firebase.
Did repo update, pod cache clean. Cleaned the build folder.
Nothing seems to solve this

Pod file

 # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
      
    # Pods for World Test
    pod 'Firebase/Core', '~> 6.2.0'
    pod 'Firebase/Database', '~> 6.2.0'
    pod 'Firebase/Auth', '~> 6.2.0'
    pod 'Firebase/Firestore', '~> 6.2.0'
    pod 'Firebase/Storage', '~> 6.2.0'
    pod 'Fabric', '~> 1.10.0'
    pod 'Crashlytics', '~> 3.13.1'
    pod 'Firebase/Functions', '~> 6.2.0'
    pod 'Firebase/DynamicLinks', '~> 6.2.0'
    pod 'Firebase/Messaging', '~> 6.2.0'
    pod 'FBSDKCoreKit', '~> 4.38.1'
    pod 'FBSDKLoginKit', '~> 4.38.1'
    pod 'FBSDKShareKit', '~> 4.38.1'
    pod 'GoogleSignIn', '~> 4.4.0'
    # Add new pods below this line

#import "RNFirebaseAnalytics.h"
#import <React/RCTUtils.h>

#if __has_include(<FirebaseAnalytics/FIRAnalytics.h>)
#import <FirebaseAnalytics/FIRAnalytics.h>
**#import <FirebaseCore/FIRAnalyticsConfiguration.h>**

@implementation RNFirebaseAnalytics
RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(logEvent:(NSString *)name props:(NSDictionary *)props) {
  [FIRAnalytics logEventWithName:name parameters:props];
}

RCT_EXPORT_METHOD(setAnalyticsCollectionEnabled:(BOOL) enabled) {
  [[FIRAnalyticsConfiguration sharedInstance] setAnalyticsCollectionEnabled:enabled];
}

**Comment by mikehardy** [comment]
I have a tested fix for this and a 5.5.2 coming shortly - for various reasons analytics isn't in CI so I didn't catch it until I released 5.5.0/5.5.1 and started integrating it into my project - sorry for the trouble

**Comment by mikehardy** [comment]
If you are completely blocked the change is simple - in node_modules/react-native-firebase/ios/RNFirebase/analytics/RNFirebaseAnalytics.m make the top of the file match this - they just moved where the API was:

```
#import "RNFirebaseAnalytics.h"
#import <React/RCTUtils.h>

#if __has_include(<FirebaseAnalytics/FIRAnalytics.h>)
#import <FirebaseAnalytics/FIRAnalytics.h>

@implementation RNFirebaseAnalytics
RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(logEvent:(NSString *)name props:(NSDictionary *)props) {
  [FIRAnalytics logEventWithName:name parameters:props];
}

RCT_EXPORT_METHOD(setAnalyticsCollectionEnabled:(BOOL) enabled) {
  [FIRAnalytics setAnalyticsCollectionEnabled:enabled];
}

```

**Comment by mikehardy** [comment]
Okay, just pushed 5.5.2 to npmjs.com - grab the new package and you're set

**Comment by smeekmeister** [comment]
Hi Mike, thanks for the very quick reply. I manually applied the changes and it works.
I will now grab 5.5.2

**Comment by vinaygoyal20** [comment]
@mikehardy your suggested changes in node_modules folder solved the issue for me
Thanks!!

**Comment by mikehardy** [comment]
That will work for 5.5.1 but it should not be necessary now, the current release 5.5.3 contains the real fix (but packaged officially) @vinaygoyal20

**Comment by Dipak26** [comment]
Hi @mikehardy, I upgraded react-native-firebase@5.2.3 to react-native-firebase@5.5.3. 
AM i need to also increase the pod file firebase pod version to work it correctly ?
Which Pod version is used with 5.5.3 for firebase core pod.

**Comment by Dipak26** [comment]
OK I update the pod to 6.2.0 as per doc for version 5.X.X but it now work same error

error: no known class method for selector 'setAnalyticsCollectionEnabled:'
[FIRAnalytics setAnalyticsCollectionEnabled:enabled];

I used CI tools to create an signed build.

**Comment by mikehardy** [comment]
You have some sort of caching or something. It definitely works, CI proves it as does my project

`npm i react-native-clean-project && react-native clean-project-auto` then retry

**Comment by JanErikFoss** [comment]
Seems like the fix has been reverted in 5.5.6?

I had to manually apply the changes @mikehardy posted to make it work.

react-native-firebase: 5.5.6,
pod 'Firebase/Core', '~> 6.3.0'

**Comment by mikehardy** [comment]
You guys can thumbs down me all you want, but I am not just blabbering, I show it works here: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by noveleven** [comment]
check change log `https://rnfirebase.io/docs/v5.x.x/releases/v5.0.0#iOS---Update-Firebase-SDKs`
