### ISSUE TITLE
react-native-firebase/tests problem - ANDROID

### ISSUE THREAD

**Issue by MichelDiz** [invertase/react-native-firebase#226]
>yarn run android:dev

react-native-firebase/tests/firebase/firebase doesn't exist
:app:bundleDebugJsAndAssets FAILED

FAILURE: Build failed with an exception.

I'm just having a look to the test files and I'm geting this error.
Is related to this line from src/firebase.js
import RNfirebase from './../firebase/firebase';

I tryed this in the "src/firebase.js"
import RNfirebase from './../node_modules/firebase/firebase';

>get more errors.

Or when I copy firebase from npm modules folders to outside - this happen.

Loading dependency graph, done.
Bundling `index.android.js`  100.0% (841/841), done.
error: bundling: UnableToResolveError: Unable to resolve module `./../firebase/firebase` from 'react-native-firebase/tests/src/firebase.js`:
react-native-firebase/tests/firebase/firebase doesn't exist

**Comment by Ehesp** [comment]
Hi, I just added some docs on this: https://github.com/invertase/react-native-firebase/blob/master/docs/contributing/testing.md

Let me know if they work.

**Comment by Salakar** [comment]
Hello!

The tests readme probably needs an update, here's how to get it working:

In the root of the project (not the tests dir) there's several npm scripts. You'll need to have run `npm i` here also as well as `npm i` in the tests directory before using these npm scripts.

 - As a one off run the `tests-watch-init` script - this is only a one off per project init.
 - Run `tests-watch-start` - run this every time you start doing work on the project and leave it open. This script watches and copies changes to the js lib into the tests directory (you'll need to change the import statement that you changed above back to how it was).
 - Run `tests-packager` to start the test projects RN packager.

And then you can continue a normal i.e. `cd tests && yarn run android:dev`.

**Comment by Salakar** [comment]
@Ehesp damn, you fast. 🙈

**Comment by MichelDiz** [comment]
I'm following your advice but this

```
git clone git@github.com:invertase/react-native-firebase.git
Cloning into 'react-native-firebase'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by Ehesp** [comment]
Ah yes sorry, fork it as your own and clone! Will update the docs.

**Comment by MichelDiz** [comment]
Perfect! Working! I cloned the main repository and follow your advices.
