### ISSUE TITLE
Unnecessary validation in `setUserIdentifier`

### ISSUE THREAD

**Issue by maxkomarychev** [invertase/react-native-firebase#2261]
## Issue

I want to be able to reset user id on crashlyltics via
```js
    firebase.crashlytics().setUserIdentifier(null)
```

it throws an error because of this check:
```js
  /**
   * Set the user ID to show alongside any subsequent crash reports.
   */
  setUserIdentifier(userId: string): void {
    if (typeof userId === 'string') {
      getNativeModule(this).setUserIdentifier(userId);
    } else {
      throw new Error('Invalid parameter type!');
    }
  }
```

crashlytics ios sdk does allow nullability of the parameter:

<details>
<summary>Piece of Crashlytics.h</summary>

```objc
/**
 *  Specify a user identifier which will be visible in the Crashlytics UI.
 *
 *  Many of our customers have requested the ability to tie crashes to specific end-users of their
 *  application in order to facilitate responses to support requests or permit the ability to reach
 *  out for more information. We allow you to specify up to three separate values for display within
 *  the Crashlytics UI - but please be mindful of your end-user's privacy.
 *
 *  We recommend specifying a user identifier - an arbitrary string that ties an end-user to a record
 *  in your system. This could be a database id, hash, or other value that is meaningless to a
 *  third-party observer but can be indexed and queried by you.
 *
 *  Optionally, you may also specify the end-user's name or username, as well as email address if you
 *  do not have a system that works well with obscured identifiers.
 *
 *  Pursuant to our EULA, this data is transferred securely throughout our system and we will not
 *  disseminate end-user data unless required to by law. That said, if you choose to provide end-user
 *  contact information, we strongly recommend that you disclose this in your application's privacy
 *  policy. Data privacy is of our utmost concern.
 *
 *  @param identifier An arbitrary user identifier string which ties an end-user to a record in your system.
 */
- (void)setUserIdentifier:(nullable NSString *)identifier;
```
</details>

why does js counterpart of this lib throws an error? is this on purpose or by mistake?

Describe your issue here

---

## Project Files

I am using `react-native-firebase` 5.5.1 and 
this is what I have in my Podfile:
```
    pod 'Fabric', '~> 1.10.1'
    pod 'Crashlytics', '~> 3.13.1'
    pod 'Firebase/Core', '~> 5.18'
    pod 'Firebase/RemoteConfig', '~> 5.18'
    pod 'Firebase/Messaging', '~> 5.18'
```

and gradle:
```
    implementation "com.crashlytics.sdk.android:crashlytics:2.10.1"
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi! This was changed just recently in #2237 by @bthurlow - the validation was added to guard against some problems with recordCustomError - maybe he has some thoughts? This might apply in general to other APIs in the crashlytics module that were altered by that PR (I am unsure which ones are nullable, or if it is better to send in an "" string to reset them, or ?)

**Comment by bthurlow** [comment]
For now pass an empty string. Let me do some in depth testing on passing nulls as a couple of the methods were generating errors when trying to pass nulls.  The errors were coming from RN object translations and not from the crashlytics module itself.  Will comment when I have more info.

**Comment by mikehardy** [comment]
Thanks @bthurlow ! I believe @maxkomarychev is getting set up to run e2e tests locally so should be able to collaborate

**Comment by bthurlow** [comment]
Before I got started I wanted to check the official docs and I'm not sure that we need to change anything with this.  According to the official docs, you're supposed to set a blank string to reset the userid value.  

https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=ios  

I'm happy to spend some time on it if we think it's necessary. What do you think @mikehardy?

**Comment by mikehardy** [comment]
I will always defer to the official documentation :-) - if @maxkomarychev can confirm this works for him, then it's closable - thanks @bthurlow for the attention, much appreciated

**Comment by mikehardy** [comment]
@maxkomarychev is using an empty string working for you?

**Comment by maxkomarychev** [comment]
well what can I say against docs :)

I guess I was just confused with analytics module which tells to send `null`/`nil` to get user id erased and objc code allowing `nil`.

On more general note: I wonder if it is reasonable to somehow bring some consistency between various parts of firebase apis at js level or you prefer seeing this library as rather dumb wrapper around whatever native provides? By far fabric is the single analytics lib I approach with many try-catches around due to weird limitations here and there (e.g. 25 params per event, event name length cap etc)

**Comment by mikehardy** [comment]
I have the same issue with protecting for all the analytics parameters. For design things I'd post something tagged v6 if you want to discuss - and you might have some good points, with the library maybe being able to do some validation. In general the goal is to mimic the JS API I believe, but crashlytics for instance is native-only so it likely feels different. Analytics can also feel different for that reason

but it seems like this one is solved
