### ISSUE TITLE
Could not create dynamic link on Android. setDomainURIPrefix couldn't find the relavant key in the ReadableMap.

### ISSUE THREAD

**Issue by sauravexodus** [invertase/react-native-firebase#2262]
I am using
`react-native-firebase: 5.5.2`
`implementation "com.google.firebase:firebase-invites:17.0.0"`
`implementation "com.google.firebase:firebase-dynamic-links:17.0.0"`

The problem is at line:222 of RNFirebaseLinks.java where the `domainURIPrefix` is extracted from `linkData` `ReadableMap`. It should be `dynamicLinkDomain`.

**Comment by sauravexodus** [comment]
I faced the same issue on iOS as well. The key should be `dynamicLinkDomain` on Line:206 in `RNFirebaseLinks.m`

**Comment by sauravexodus** [comment]
I think you misunderstood the issue. I read the docs and breaking changes. But the changes don't align with code in JS and Native SDKs. That's what I am trying to point out here.

**Comment by sauravexodus** [comment]
Unless someone goes and changes the key name in bridge files inside node_modules, creating dynamic links doesn't work at all. I am just pointing out so that it gets fixed in the next releases.

**Comment by mikehardy** [comment]
Oh - that's potentially very different then. Let me look more closely and if I didn't get those changes aligned all the way through then yes we'll need a 5.5.3 quickly with the fix.

**Comment by mikehardy** [comment]
https://github.com/invertase/react-native-firebase/pull/2240 is the PR that changed it

[Here is where iOS uses the new key
](https://github.com/invertase/react-native-firebase/pull/2240/files?file-filters%5B%5D=.gradle&file-filters%5B%5D=.java&file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.log&file-filters%5B%5D=.m&file-filters%5B%5D=.pbxproj&file-filters%5B%5D=.ts&file-filters%5B%5D=.xml&file-filters%5B%5D=No+extension&file-filters%5B%5D=dotfile#diff-c2b15a47f1d5ea1eaa13a7f57cf523c4R205)

[Here is where Android uses it
](https://github.com/invertase/react-native-firebase/pull/2240/files?file-filters%5B%5D=.java&file-filters%5B%5D=.m&hide-deleted-files=true#diff-ffbd665ef07f9c83b4b7a2183338130cR222)


[Here is the Typescript change](https://github.com/invertase/react-native-firebase/pull/2240/files?file-filters%5B%5D=.gradle&file-filters%5B%5D=.java&file-filters%5B%5D=.js&file-filters%5B%5D=.lock&file-filters%5B%5D=.log&file-filters%5B%5D=.m&file-filters%5B%5D=.pbxproj&file-filters%5B%5D=.ts&file-filters%5B%5D=.xml&file-filters%5B%5D=No+extension&file-filters%5B%5D=dotfile#diff-b739f95ace6bbf2f0fd5e8cf1dab97d8R2132)

Ah but dangit - I thought I got this one but it must have been lost in the git shuffle - [I'm not hooking the new key up correctly](https://github.com/invertase/react-native-firebase/blob/v5.5.0/src/modules/links/DynamicLink.js#L31) - you are 100% right. 5.5.3 in just a moment

Sorry for the trouble - this module doesn't have CI / testing support in v5 so it is harder to get the change correct

**Comment by mikehardy** [comment]
Will you be able to test this? 5.5.3 is out on npmjs.com now

**Comment by mikehardy** [comment]
I believe this is closed, please re-open if it does not work for you - I will do my best to fix it. Thanks for the quick report!

**Comment by sauravexodus** [comment]
Thanks for the quick revert. I'll do a quick test and let you know.

**Comment by sauravexodus** [comment]
It works. Thanks!

**Comment by mikehardy** [comment]
Very happy to hear this! Thanks for the success report so I know the fix was good
