### ISSUE TITLE
[ANDROID] Could not determine the dependencies of task ':react-native-firebase:compileReleaseAidl'.

### ISSUE THREAD

**Issue by roshan-p** [invertase/react-native-firebase#2264]
I'm working around to migrating android x and get this problem.
I'm using
"react-native": "0.57.0",
"react-native-firebase": "^5.5.3"
build.gradle:
 implementation 'com.google.android.gms:play-services-base:17.0.0'
 implementation 'com.google.firebase:firebase-core:17.0.0'

`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-firebase:compileReleaseAidl'.
-> Could not resolve all task dependencies for configuration ':react-native-firebase:releaseCompileClasspath'.
   -> Could not resolve com.squareup.okhttp3:okhttp:{strictly 3.10.0}.
     Required by:
         project :react-native-firebase
      -> Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints: 
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-perf:17.0.2' --> 'com.squareup.okhttp3:okhttp:3.0.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-functions:17.0.0' --> 'com.squareup.okhttp3:okhttp:3.12.1'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0

   -> Could not resolve com.squareup.okio:okio:{strictly 1.14.0}.
     Required by:
         project :react-native-firebase
      -> Cannot find a version of 'com.squareup.okio:okio' that satisfies the version constraints: 
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okio:okio:1.14.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okhttp3:okhttp:3.12.1' --> 'com.squareup.okio:okio:1.15.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-firestore:19.0.2' --> 'com.squareup.okhttp:okhttp:2.7.5' --> 'com.squareup.okio:okio:1.6.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-firestore:19.0.2' --> 'io.grpc:grpc-okhttp:1.21.0' --> 'com.squareup.okio:okio:1.13.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0

   -> Could not resolve com.squareup.okhttp3:okhttp:3.10.0.
     Required by:
         project :react-native-firebase -> com.facebook.react:react-native:0.57.0
         project :react-native-firebase -> com.facebook.fresco:imagepipeline-okhttp3:1.10.0
         project :react-native-firebase -> com.squareup.okhttp3:okhttp-urlconnection:3.10.0
      -> Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints: 
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-perf:17.0.2' --> 'com.squareup.okhttp3:okhttp:3.0.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-functions:17.0.0' --> 'com.squareup.okhttp3:okhttp:3.12.1'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0

   -> Could not resolve com.squareup.okio:okio:1.14.0.
     Required by:
         project :react-native-firebase -> com.facebook.react:react-native:0.57.0
      -> Cannot find a version of 'com.squareup.okio:okio' that satisfies the version constraints: 
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okio:okio:1.14.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okhttp3:okhttp:3.12.1' --> 'com.squareup.okio:okio:1.15.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-firestore:19.0.2' --> 'com.squareup.okhttp:okhttp:2.7.5' --> 'com.squareup.okio:okio:1.6.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-firestore:19.0.2' --> 'io.grpc:grpc-okhttp:1.21.0' --> 'com.squareup.okio:okio:1.13.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0

   -> Could not resolve com.squareup.okhttp3:okhttp:3.0.0.
     Required by:
         project :react-native-firebase -> com.google.firebase:firebase-perf:17.0.2
      -> Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints: 
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-perf:17.0.2' --> 'com.squareup.okhttp3:okhttp:3.0.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-functions:17.0.0' --> 'com.squareup.okhttp3:okhttp:3.12.1'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0

   -> Could not resolve com.squareup.okhttp3:okhttp:3.12.1.
     Required by:
         project :react-native-firebase -> com.google.firebase:firebase-functions:17.0.0
      -> Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints: 
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-perf:17.0.2' --> 'com.squareup.okhttp3:okhttp:3.0.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-functions:17.0.0' --> 'com.squareup.okhttp3:okhttp:3.12.1'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okhttp3:okhttp:{strictly 3.10.0}' because of the following reason: releaseRuntimeClasspath uses version 3.10.0

   -> Could not resolve com.squareup.okio:okio:1.15.0.
     Required by:
         project :react-native-firebase -> com.squareup.okhttp3:okhttp:3.12.1
      -> Cannot find a version of 'com.squareup.okio:okio' that satisfies the version constraints: 
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okio:okio:1.14.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okhttp3:okhttp:3.12.1' --> 'com.squareup.okio:okio:1.15.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-firestore:19.0.2' --> 'com.squareup.okhttp:okhttp:2.7.5' --> 'com.squareup.okio:okio:1.6.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-firestore:19.0.2' --> 'io.grpc:grpc-okhttp:1.21.0' --> 'com.squareup.okio:okio:1.13.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0

   -> Could not resolve com.squareup.okio:okio:1.6.0.
     Required by:
         project :react-native-firebase -> com.google.firebase:firebase-firestore:19.0.2 -> com.squareup.okhttp:okhttp:2.7.5
      -> Cannot find a version of 'com.squareup.okio:okio' that satisfies the version constraints: 
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okio:okio:1.14.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okhttp3:okhttp:3.12.1' --> 'com.squareup.okio:okio:1.15.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-firestore:19.0.2' --> 'com.squareup.okhttp:okhttp:2.7.5' --> 'com.squareup.okio:okio:1.6.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-firestore:19.0.2' --> 'io.grpc:grpc-okhttp:1.21.0' --> 'com.squareup.okio:okio:1.13.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0

   -> Could not resolve com.squareup.okio:okio:1.13.0.
     Required by:
         project :react-native-firebase -> com.google.firebase:firebase-firestore:19.0.2 -> io.grpc:grpc-okhttp:1.21.0
      -> Cannot find a version of 'com.squareup.okio:okio' that satisfies the version constraints: 
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okio:okio:1.14.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.57.0' --> 'com.squareup.okhttp3:okhttp:3.12.1' --> 'com.squareup.okio:okio:1.15.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-firestore:19.0.2' --> 'com.squareup.okhttp:okhttp:2.7.5' --> 'com.squareup.okio:okio:1.6.0'
           Dependency path 'ProjectName:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-firestore:19.0.2' --> 'io.grpc:grpc-okhttp:1.21.0' --> 'com.squareup.okio:okio:1.13.0'
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0
           Constraint path 'ProjectName:react-native-firebase:unspecified' --> 'com.squareup.okio:okio:{strictly 1.14.0}' because of the following reason: releaseRuntimeClasspath uses version 1.14.0`

**Comment by mikehardy** [comment]
Unsupported version combination https://rnfirebase.io/docs/v5.x.x/getting-started#Supported-versions---React-Native-/-Firebase

**Comment by poojasharma3106** [comment]
same issue

**Comment by cmcaboy** [comment]
I ran into this issue when I attempted to use a forked version of React Native. I was able to fix it by following this article: https://github.com/facebook/react-native/wiki/Building-from-source

**Comment by danghung24031992** [comment]
same issue
