### ISSUE TITLE
no known class method for selector 'setAnalyticsCollectionEnabled:'     --> node_modules/react-native-firebase/ios/RNFirebase/analytics/RNFirebaseAnalytics.m

### ISSUE THREAD

**Issue by abhi-nahi** [invertase/react-native-firebase#2272]
## Issue

Describe your issue here
 'no known class method for selector 'setAnalyticsCollectionEnabled:'  I found this issue after the last update of RNFirebase 2 days ago. Don't know what to do next

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '9.0'

target 'AppName' do
  pod 'GoogleSignIn', '~> 4.4.0'

  pod 'Firebase/Core', '~> 5.6.0'
  pod 'Firebase/Auth', '~> 5.6.0'
  pod 'Firebase/Messaging', '~> 5.6.0'

  pod 'FBSDKCoreKit', '~> 4.38.0'
  pod 'FBSDKLoginKit', '~> 4.38.0'
  pod 'FBSDKShareKit', '~> 4.38.0'

end

```

#### `AppDelegate.m`:

```objc
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "RNSplashScreen.h"
#import <Firebase.h>
#import "RNFirebaseNotifications.h"
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  NSURL *jsCodeLocation;

 
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  
  [FIRApp configure];
  [RNFirebaseNotifications configure];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"sbChat"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];
  
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];

  return YES;
}
  
  - (BOOL)application:(UIApplication *)application
              openURL:(NSURL *)url
              options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    
    BOOL handled = [[FBSDKApplicationDelegate sharedInstance] application:application
                                                                  openURL:url
                                                        sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                                                               annotation:options[UIApplicationOpenURLOptionsAnnotationKey]
                    ];
    
    return handled;
  }

@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  Y
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by abhi-nahi** [comment]
BTW the whole problem is appearing on buddy build only.

**Comment by mikehardy** [comment]
You are using unsupported pod versions - when you upgraded it was noted there were breaking changes and the pod versions you should use were specified. Use those versions

**Comment by abhi-nahi** [comment]
> You are using unsupported pod versions - when you upgraded it was noted there were breaking changes and the pod versions you should use were specified. Use those versions

Can you please suggest me which pod version of firebase will be supportive if I'm using 
**"react-native": "^0.57.8",
"react-native-firebase": "^5.0.0",**
in my application.

**Comment by mikehardy** [comment]
https://rnfirebase.io/docs/v5.x.x/getting-started#Supported-versions---React-Native-/-Firebase

**Comment by abhi-nahi** [comment]
> https://rnfirebase.io/docs/v5.x.x/getting-started#Supported-versions---React-Native-/-Firebase

Thank you. Now I can keep my eyes on these scenarios too.

**Comment by Buwaneka-Sumanasekara** [comment]
Same issue getting in 
`react-native": "0.57.8`
`"react-native-firebase": "^5.2.5"`

**Comment by mikehardy** [comment]
@Buwaneka-Sumanasekara  you don't list your underlying firebase ios sdk version. Looks to me like you are not using the compatible versions for your react-native-firebase verison

**Comment by m-tymchyk** [comment]
By the information from @mikehardy's link:
https://rnfirebase.io/docs/v5.x.x/getting-started#Supported-versions---React-Native-/-Firebase

To resolve this issue you need to update RN version to `0.59.3 +`

And update Pod deps:
```
pod 'Firebase/Core', '~> 5.19.0'
pod 'Firebase/Messaging', '~> 5.19.0'
pod 'Firebase/Performance', '~> 5.19.0'
pod 'Firebase/DynamicLinks', '~> 5.19.0'
pod 'Firebase/RemoteConfig', '~> 5.19.0'
```

**Comment by ruslanzharkov** [comment]
> By the information from @mikehardy's link:
> https://rnfirebase.io/docs/v5.x.x/getting-started#Supported-versions---React-Native-/-Firebase
> 
> To resolve this issue you need to update RN version to `0.59.3 +`
> 
> And update Pod deps:
> 
> ```
> pod 'Firebase/Core', '~> 5.19.0'
> pod 'Firebase/Messaging', '~> 5.19.0'
> pod 'Firebase/Performance', '~> 5.19.0'
> pod 'Firebase/DynamicLinks', '~> 5.19.0'
> pod 'Firebase/RemoteConfig', '~> 5.19.0'
> ```

Thanks a lot, I updated pods and firebase for npm too and it worked!
