### ISSUE TITLE
On iOS, Dynamic Link only work on simulator not on real device.

### ISSUE THREAD

**Issue by jeonghoonkim** [invertase/react-native-firebase#2273]
## Issue

1. Create dynamic link on Firebase console: `https://abc.page.link`
2. Set Associated Domains: `applinks:abc.page.link`
3. Put "Info > URL Types >  identifier and URL Schemes" : `abc.page.link`
4. `[FIROptions defaultOptions].deepLinkURLScheme = @"abc.page.link";`

After then, create link with following method
```
// link: is DynamicLink instance
const dynamiclink = await firebase.links().createDynamicLink(link); 
```
- When I put this `dynamiclink` to safari on simulator, works fine but not work on real device.
- On real device, it always open App Store even if app already installed.
- On real device, if I put the link Chrome app, it works fine.

on Android works fine.
---

#### `ios/Podfile`:
- [x] I'm using Pods and my Podfile looks like:

```ruby
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'Firebase/DynamicLinks', '~> 5.20.1'
```

#### `AppDelegate.m`:

```objc
[FIROptions defaultOptions].deepLinkURLScheme = @"abc.page.link";
[FIRApp configure];
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
      Memory: 98.40 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 24, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by ealmiladi** [comment]
Running into a similar issue. Anyone able to help?

**Comment by qwerqy** [comment]
Running into similar issue. my situation however, 
on ios/android emulators, the dynamic link works (redirected to app)

however, on ios, it only works on chrome, not safari and any other browsers.
in android, it works on chrome, but not in any other native browsers.

parking.

**Comment by vineetsagar369** [comment]
I'm also facing the same issue. It works on the simulator but no real device it shows Dynamic link not found.

**Comment by tapizquent** [comment]
This is still an issue. Root link navigates to app on simulator but opens safari with the Invalid Dynamic Link page on a real device

**Comment by Alb93** [comment]
Did someone solved this behaviour?

**Comment by tapizquent** [comment]
> Did someone solved this behaviour?

Honestly, I’m not sure. It was not working properly with the subdomain link Firebase provides, as soon as I changed it to my custom domain, it began working fine

**Comment by Alb93** [comment]
Can you please share your AppDelegate.m file? Are you using react-native-firebase >= v6? @tapizquent

**Comment by cristiancamilo070** [comment]
I'm still having issues with this, the deep link takes me to de app properly, but i'm also using this link to open a specific detail page, it's working on android and iOS simulator but not in testflight
