### ISSUE TITLE
[QUESTION] missing JSON Structure FCM notification in server side

### ISSUE THREAD

**Issue by faustinogagneten** [invertase/react-native-firebase#2277]
I tried to use Discord to post the question but the URL didn't work.

My question is really simple: What is the JSON structure for sending FCM push notification? (server side). I know is a client side library, but the client need to know the notification server json structure  to receive correctly the notification.

Searching issues I found a basic implementation :
{
  "to" : "%TO%",
  "priority": "high",
  "content_available": true,
  "notification" : {
    "body" : "body",
    "title" : "title",
    "link": "link ",
    "badge": 4 <
  }
}

Great. But... What If I want to send more complex data? For example in "body" (I want to send ids, names, addresses, etc). Do I need to send a Payload to send more data? If so, How can I do it? Is here any documentation to follow so I can know how to send the json so the library can read every single data?

Thanks.

**Comment by mikehardy** [comment]
I think this is what you want https://firebase.google.com/docs/cloud-messaging/concept-options
