### ISSUE TITLE
[iOS] Terminating app due to uncaught exception 'com.firebase.core', reason: 'Options is nil. Please pass a valid options.

### ISSUE THREAD

**Issue by ferryhinardi** [invertase/react-native-firebase#2278]
## Issue

Describe your issue here

Got this error:
<img width="824" alt="Screen Shot 2019-06-23 at 21 36 56" src="https://user-images.githubusercontent.com/5007428/59977713-0d121a00-95ff-11e9-9074-02ff005b62ed.png">

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Jaztip' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Jaztip

  pod 'FLEX', '~> 2.4.0', :configurations => ['Debug']

  # react
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'RCTText',
    'RCTWebSocket',
    'RCTNetwork',
    'DevSupport',
    'RCTVibration',
    'RCTImage',
    'RCTGeolocation',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTSettings',
    'RCTLinkingIOS',
    'RCTCameraRoll'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # fabric
  pod 'Fabric'
  pod 'Crashlytics'

  # Add new pods below this line
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

  pod 'react-native-google-analytics-bridge', :path => '../node_modules/react-native-google-analytics-bridge'

  pod 'react-native-amplitude-analytics', :path => '../node_modules/react-native-amplitude-analytics'

  pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  # firebase
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'

  # image crop picker
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  # react-native-vector-icons
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  # branch
  pod 'react-native-branch', :path => '../node_modules/react-native-branch'
  pod 'Branch-SDK', :path => '../node_modules/react-native-branch/ios'

  # react-native-maps
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils'

  # zendesk
  pod 'react-native-zendesk-support', :path => '../node_modules/react-native-zendesk-support'
  pod 'ZendeskSDK', '~> 1.9.2.2'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
    target.build_configurations.each do |config|
      target.build_settings(config.name)['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Didn't follow the template. I don't know what versions you are on. At first glance though, you have not followed the install instructions, as you have not specified your pod dependencies to be something specific for Firebase. This is important as react-native-firebase versions have specific compatibility ranges https://rnfirebase.io/docs/v5.x.x/getting-started#Supported-versions---React-Native-/-Firebase
