### ISSUE TITLE
Android: Interstitials skippable immediately (admob)

### ISSUE THREAD

**Issue by bitfabrikken** [invertase/react-native-firebase#228]
Not sure if it's a bug or not. 
When an android interstitial is shown, you can close it right away with the android hardware back button.
Users will probably learn that real fast :)

**Comment by Ehesp** [comment]
The activity is controlled by the AdMob SDK once it's shown, which we don't have control over. See; https://stackoverflow.com/questions/26641673/blocking-back-button-to-close-interstitial-ad
