### ISSUE TITLE
Unable to genrate dynamic link, Error: 400: Long link is not parsable: watchugot.page.link

### ISSUE THREAD

**Issue by vinaygoyal20** [invertase/react-native-firebase#2282]
## Issue

new firebase.links.DynamicLink(
			`https://example.page.link?challengeId=${challengeId}&userId=${userId}&route=challangescreen`,
			"example.page.link"
		).android
			.setPackageName("com.test")
			.ios.setBundleId("org.reactjs.native.example");
		firebase
			.links()
			.createShortDynamicLink(link, "UNGUESSABLE")
			.then(url => {
				Clipboard.setString(url);
				this.refs.toast.show("Link Copied!",900);
				console.log(url, "the dynamic link url created is as follow");
				// ...
			});

this should generate a dynamic link, i was able to do so while i was using version 5.3 but today i updated to version 5.5 after that i am gettting this issue. i don't know why its happening.

I am getting the errror:
 Possible Unhandled Promise Rejection (id: 0):
Error: 400: Long link is not parsable:

Describe your issue here

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Didn’t follow the template so I’m not sure what version you are using - also please use code blocks (triple-backticks like ` ```javascript ` on newline to start, then triple-backticks on newline at end to finish) for formatting so they’re readable

**Comment by Findiglay** [comment]
Have the same issue when trying to create short links

**Comment by vinaygoyal20** [comment]
> Have the same issue when trying to create short links
Here is the solution
https://github.com/invertase/react-native-firebase/issues/2289#issuecomment-505739031

**Comment by EbenOladutemu** [comment]
Make you add `domainUriPrefix` to your parameters.
