### ISSUE TITLE
(:fire:) Error occurred while parsing your function triggers.Unexpected token import

### ISSUE THREAD

**Issue by dede65** [invertase/react-native-firebase#2286]
## Issue

I am trying to deploy firebase cloud functions but getting the error below:

Error: Error occurred while parsing your function triggers.

/home/dd/Desktop/hadimaca/node_modules/react-native-firebase/dist/index.js:1
(function (exports, require, module, __filename, __dirname) { import firebase from './modules/core/firebase';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dd/Desktop/hadimaca/functions/index.js:3:18)

below is the package.json file in functions folder:

{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "dependencies": {
    "firebase-admin": "^8.0.0",
    "firebase-functions": "^3.0.0"
  },
  "devDependencies": {
    "eslint": "^5.12.0",
    "eslint-plugin-promise": "^4.0.1",
    "firebase-functions-test": "^0.1.6"
  },
  "private": true
}

Can someone please help me resolve this issue? really appreciate your help. 

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 3.17 GB / 15.55 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.16.0 - /usr/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: ^0.59.3 => 0.59.9 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `Cloud functions`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I don’t believe react-native-firebase has anything to do with deploying cloud functions, only using them? And I don’t see react-native in your dependencies? This looks like you are following the cloud functions admin tutorials online to create and deploy functions as opposed to creating a react-native app that uses cloud functions?

**Comment by dede65** [comment]
thank you for your feedback.
I do use react-native firebase. when i init cloud functions, it created functions folder. everyting works fine except that when deploying functions it gives the error "Error: Error occurred while parsing your function triggers." and doesnt accept import statement in /home/dd/Desktop/hadimaca/node_modules/react-native-firebase/dist/index.js:1
(function (exports, require, module, __filename, __dirname) { import firebase from './modules/core/firebase';
I do not have any issue with react-native dependencies. the dependencies i shared belongs to functions folder since it is server code that will be deployed to firebase.

below code is an example of what i am trying to do.

const functions = require("firebase-functions");
const admin = require("firebase-admin");
const firebase = require("react-native-firebase");

admin.initializeApp(functions.config().firebase);;

exports.sendWelcomeNotification = functions.auth.user().onCreate(async user => {
  try {
    const uid = user.uid;
    const doc = await firebase
      .firestore()
      .collection("notificationTokens")
      .doc(uid);
    const payload = {
      notification: {
        title: "Welcome",
        body: "Thank you for using our app."
      }
    };

    const { token } = doc;
    return admin.messaging().sendToDevice(token, payload);
  } catch (error) {
    console.log("Error while sending welcome notification", error.message);
  }
});

I have followed react-native firebase docs and firebase docs. I dont know why i am getting this error. 
If you need any file, feel free to ask. I will share

**Comment by mikehardy** [comment]
I think you need to keep the development/deployment of cloud functions fully separate from the react-native app but I could be wrong?

**Comment by dede65** [comment]
thank you for your prompt response. you are right. I should access firebase via admin SDK not react-native-firebase package.
