### ISSUE TITLE
⚠️ 5.x.x is not compatible w/ Expo 33 (RN 59)

### ISSUE THREAD

**Issue by n-sviridenko** [invertase/react-native-firebase#2287]
I created a separate [repo](https://github.com/n-sviridenko/expo-firebase-demo) to easily reproduce the issue (it's a clean ejected Expo 33 project w/ [a single commit](https://github.com/n-sviridenko/expo-firebase-demo/commit/47b9db960995aac0f77d893669469ca14a77ad36) integrating `react-native-firebase`):

1. clone & install it:

```
git clone git@github.com:n-sviridenko/expo-firebase-demo.git
cd expo-firebase-demo
yarn
```

2. open `android` folder in Android Studio and run it

The commit integrating `react-native-firebase` is here https://github.com/n-sviridenko/expo-firebase-demo/commit/47b9db960995aac0f77d893669469ca14a77ad36

You'll see a similar error (it's always different):

```
Error: Interface `com.google.android.gms.internal.measurement.zzq(classpath class)` used as super class of `com.google.android.gms.internal.measurement.zzcm`.
```

Help me please 😭

**Comment by n-sviridenko** [comment]
1. We cannot use `4.3.x` due to dependency on RN < 59 (as per [Supported versions](https://rnfirebase.io/docs/v5.x.x/getting-started#Supported-versions---React-Native-/-Firebase)).

2. In case the issue is in Grandle build tools version (in Expo it's `com.android.tools.build:gradle:3.3.2` when in RNFB it's `com.android.tools.build:gradle:3.4.1`), we cannot update to `3.4.1` because it's dependent on Grandle 5.x.x while Expo is dependent on Grandle 4.x.x.

**Comment by mikehardy** [comment]
I dunno - in general I don’t use Expo for these reasons ?

**Comment by mikehardy** [comment]
I don’t think it’s the gradle version though - that’s important to say. That version shouldn’t matter I don't think

**Comment by n-sviridenko** [comment]
> I dunno - in general I don’t use Expo for these reasons ?

We already have a project on expo 30 w/ RN firebase 4.3 and want to migrate it on expo 33 w/ RNFB 5.5 (as per docs this is the right version for us). The issue is in difference b/w RN (v30 has RN 57 and now it's 59).

We are able to launch expo 33 w/ RNFB 4.3, but don't know about side effects it may cause (for some reasons it's written that only RN 59+ can be used w/ it 🤷‍♂️?)

**Comment by mikehardy** [comment]
Hmm - unsure on the dependency snarl for RNFB4.3 I only started with it at 5.2 and for 5.3 at least (if I remember correctly) it was *definitely* 0.59.3+ - there was something weird below that). For RNFB4.3 I don’t know.

One trick I use for android is ./gradlew :app:dependencies - get the report to find out who is using what and then you can nail even the trickiest dependency snarls. If Expo33 handles RN0.59.x then all this stuff should work together, your error message is new to me though unfortunately

**Comment by mikehardy** [comment]
I pasted this in the other Expo33 bug, but specifically for this one, If you can use RNFB 4.3 and it has the functionality you need, I don't think just using that version with RN59+ is a problem. It may be the "Expo 33 with firebase how?" answer

----

Wow, I went to see what was going on in Expo-land and ...no way I'd wade into gradle upgrades they don't approve: https://github.com/expo/expo/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+gradle

Oof!

Here's the thing. Our of our normal dependency matrix between react-native + react-native-firebase + google firebase sdks, I think the least important is the react-native one

What I mean by that, is that I think you can most safely try violating the react-native constraints and using non-specified tech there.

And you can always use older versions of react-native-firebase and google firebase sdks, at your peril for dealing with fixed bugs, and as long as they line up.

So I'd go with current whatever react-native expo requests, doing it the way they want. Then for whatever version you landed on, try corresponding RNFB and Google FB stuff. Maybe it works?

But Expo has some pretty hard version requirements as does react-native-firebase. And we have a serious and vital job keeping up with google current, making older stuff work in dependency tangles, I personally don't have the time for it except to say it might be possible. RNFB and Google SDKs worked back then right?

So I'm going to close this but if discussion continues and there's an eventual result of a nice doc snippet that explains what exact versions of RN+RNFB+Google Firebase work with what versions of Expo, that's useful and maybe we can put it somewhere?
