### ISSUE TITLE
Android Install error 

### ISSUE THREAD

**Issue by agumack** [invertase/react-native-firebase#229]
Hi all,

I have get a error when install on android. 

`java.lang.RuntimeException: Unable to get provider com.google.firebase.perf.provider.FirebasePerfProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.perf.provider.FirebasePerfProvider" on path: DexPathList[[zip file "/data/app/com.myapp-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.myapp-2, /vendor/lib, /system/lib]]
`

Thanks so much!

**Comment by Ehesp** [comment]
If you've added the Performance package make sure you also do step 4: http://invertase.io/react-native-firebase/#/installation-android?id=_4-performance-monitoring-optional

**Comment by agumack** [comment]
@Ehesp I tried to remove setting Performance package but same error.

**Comment by Ehesp** [comment]
Upload your code base somewhere to look. You're not installing something incorrectly.

**Comment by agumack** [comment]
@Ehesp thanks for support, this is my setting.

<img width="750" alt="build_gradle" src="https://user-images.githubusercontent.com/19372005/27854519-4ee8ee3a-6191-11e7-88b2-7ad1419383d1.png">
<img width="463" alt="screen shot 2017-07-05 at 2 48 21 pm" src="https://user-images.githubusercontent.com/19372005/27854520-4f28741a-6191-11e7-8316-08dda37bc6e8.png">
<img width="581" alt="screen shot 2017-07-05 at 2 48 40 pm" src="https://user-images.githubusercontent.com/19372005/27854522-4f2ae5d8-6191-11e7-9377-6847879c6f76.png">
<img width="588" alt="screen shot 2017-07-05 at 2 49 01 pm" src="https://user-images.githubusercontent.com/19372005/27854523-4f2c088c-6191-11e7-8e4f-f52e68eff1f3.png">
<img width="727" alt="setting" src="https://user-images.githubusercontent.com/19372005/27854524-4f2c0c2e-6191-11e7-9acf-b1d968ce3ebf.png">

**Comment by Ehesp** [comment]
![image](https://user-images.githubusercontent.com/842078/27854686-a8e7d112-615f-11e7-8b4c-3501e79ea7e3.png)

You're requiring the library twice, where the first one is pulling in all of the modules. Also have the same issue in `settings.gradle`.

**Comment by agumack** [comment]
sorry @Ehesp i do not know how to fix it :D

**Comment by Ehesp** [comment]
In `settings.gradle`, remove the first instance of where you're include `react-native-firebase`. Then in `build.gradle`, remove the line `compile project(':react-native-firebase')`.

**Comment by agumack** [comment]
@Ehesp 

I tried edit setting but not working

`java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.myappr-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.myappr-2, /vendor/lib, /system/lib]]
`

"react-native": "0.45.1",
"react-native-firebase": "^2.0.1",

<img width="583" alt="screen shot 2017-07-05 at 4 01 06 pm" src="https://user-images.githubusercontent.com/19372005/27857374-a32264ea-619b-11e7-95a7-a39bb0a05a92.png">
<img width="562" alt="screen shot 2017-07-05 at 4 01 22 pm" src="https://user-images.githubusercontent.com/19372005/27857383-ab4cc9ee-619b-11e7-931e-0c29508c27c2.png">

**Comment by Ehesp** [comment]
Hmm sorry, there has to be something wrong with your setup. I'd suggest looking at the tests/demo app on this repo and comparing how you've tried to install it. 

Without seeing your whole project its hard to debug.

**Comment by agumack** [comment]
thanks @Ehesp 

I follow examples project and work fine.
But when i integrate https://github.com/facebook/react-native-fbsdk 
Then if run project return error:

`"Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created"`

If I uninstall react-native-firebase or react-native-fbsdk => all work fine.
react-native-firebase and react-native-fbsdk conflict? what wrong my setting?

Thanks so much!

**Comment by chrisbianca** [comment]
@agumack react-native-fbsdk is definitely compatible with react-native-firebase as I'm using them both in my project.  As @Ehesp says, without seeing your whole project, it's impossible for us to debug.
