### ISSUE TITLE
firebase phone auth not works after generating signed APK 

### ISSUE THREAD

**Issue by rambo006mm** [invertase/react-native-firebase#2296]
phone auth is not working in release apk 
i already put sha 1 on my react native project and google play console in firebase and download google service json in my project

#### `android/build.gradle`:

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'com.google.gms:google-services:4.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

#### `android/app/build.gradle`:

apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

def enableProguardInReleaseBuilds = true
def enableSeparateBuildPerCPUArchitecture = true
android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.learning"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }

  signingConfigs {
          release {
              if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                  storeFile file(MYAPP_RELEASE_STORE_FILE)
                  storePassword MYAPP_RELEASE_STORE_PASSWORD
                  keyAlias MYAPP_RELEASE_KEY_ALIAS
                  keyPassword MYAPP_RELEASE_KEY_PASSWORD
              }
          }
      }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "arm64-v8a", "x86_64"
        }
    }
    buildTypes {
        release {

            minifyEnabled

            enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"

               signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)

            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {

    compile project(':react-native-fs')
    implementation project(':react-native-vector-icons')
     implementation project(':rn-fetch-blob')

    implementation project(':@react-native-community_viewpager')

compile project(':react-native-linear-gradient')
   compile project(':react-native-view-pdf')
    implementation project(':react-native-firebase')
    implementation project(':react-native-gesture-handler')

    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation "com.google.android.gms:play-services-base:16.1.0"
     implementation "com.google.firebase:firebase-core:16.0.9"
      implementation "com.google.firebase:firebase-auth:17.0.0"
     compile project(':react-native-google-signin')
       implementation project(':react-native-google-signin')
       implementation "com.google.firebase:firebase-storage:17.0.0"
         compile "com.google.firebase:firebase-storage:11.6.0"

}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
apply plugin: 'com.google.gms.google-services'

#### `android/settings.gradle`:

rootProject.name = 'learning'

include ':rn-fetch-blob'
project(':rn-fetch-blob').projectDir = new File(rootProject.projectDir, '../node_modules/rn-fetch-blob/android')

include ':react-native-fs'
project(':react-native-fs').projectDir = new File(settingsDir, '../node_modules/react-native-fs/android')
include ':react-native-linear-gradient'
project(':react-native-linear-gradient').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-linear-gradient/android')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')

include ':@react-native-community_viewpager'
project(':@react-native-community_viewpager').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/viewpager/android')

include ':react-native-view-pdf'
project(':react-native-view-pdf').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-view-pdf/android')
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
include ':react-native-gesture-handler'
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gesture-handler/android')
include ':react-native-google-signin'
project(':react-native-google-signin').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-google-signin/android')
include ':app'

#### `MainApplication.java`:

package com.learning;

import android.app.Application;

import com.facebook.react.ReactApplication;

import com.rnfs.RNFSPackage;
import com.oblador.vectoricons.VectorIconsPackage;

import com.reactnativecommunity.viewpager.RNCViewPagerPackage;

import com.BV.LinearGradient.LinearGradientPackage;
import com.RNFetchBlob.RNFetchBlobPackage;
import com.rumax.reactnative.pdfviewer.PDFViewPackage;
import io.invertase.firebase.RNFirebasePackage;
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import io.invertase.firebase.auth.RNFirebaseAuthPackage;
import co.apptailor.googlesignin.RNGoogleSigninPackage;
import io.invertase.firebase.storage.RNFirebaseStoragePackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),

          new RNFSPackage(),
           new RNFetchBlobPackage(),

           new LinearGradientPackage(),
            new VectorIconsPackage(),

            new RNCViewPagerPackage(),

            new PDFViewPackage(),
            new RNFirebasePackage(),
            new RNGestureHandlerPackage(),
            new RNFirebaseAuthPackage(),
            new RNFirebaseStoragePackage(),

            new RNGoogleSigninPackage()

      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

#### `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.learning">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> 
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE " />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
     <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
     <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>


















## Environment
ANDROID




```
 OUTPUT GOES HERE
``` app working fine but not phone auth
after pressing signin my next page dont show up app just stay there but in debug version everything working fine SHA1 already added

**Comment by mikehardy** [comment]
I’m not sure what exactly is wrong with your specific project but I can say auth is a vital feature for most, including my app, and it is working for me as of this morning. So it should be possible, I would continue attempting things locally and triple-checking all settings, including trying with test phone/code combos that you can set up in the firebase console

**Comment by rambo006mm** [comment]
if you can

> I’m not sure what exactly is wrong with your specific project but I can say auth is a vital feature for most, including my app, and it is working for me as of this morning. So it should be possible, I would continue attempting things locally and triple-checking all settings, including trying with test phone/code combos that you can set up in the firebase console

if you can share your code or make it a git repo of your phone auth it would be helpful for me

**Comment by rambo006mm** [comment]
as it working perfectly fine in debug version .

**Comment by mikehardy** [comment]
Mine is basically react-native-firebase-starter, and then the example code from the rnfirebase.io site - I added logic essentially where it said to but did not modify control flow. All firebase documentation around how to configure it was followed, but nothing special besides the starter and pasting that example in and starting with console.log statements to make sure it worked fully as a sample app in my account

**Comment by rambo006mm** [comment]
mine code is also copied for rn firebase some feature added externally but it still shows me the same screen i need some solution for this as my app is fully prepared but auth is creating problem

**Comment by mikehardy** [comment]
It works for me so I can´t reproduce, you´ll have to work through it, sorry

**Comment by rambo006mm** [comment]
im checking it now and no auth is working not even google sign in in release version

**Comment by rambo006mm** [comment]
what is the procedure for getting sha1 for release version and what to do after that if i may doing it worng

**Comment by mikehardy** [comment]
it’s all documented on the firebase console - I just used their instructions. If you do it wrong you double-check everything and do it again :-), there’s no option but getting it right

https://developers.google.com/android/guides/client-auth

I had a case once where my signingConfigs weren’t working the way I thought they were, so just very carefully check you have your keystore correct, your signingConfig correct, and the generated APK has the SHA you expect and configured

**Comment by rambo006mm** [comment]
i got the solution by adding upload sha1 in google play console instead for app signing thanks for your help and time...mike
