### ISSUE TITLE
react-native-firebase phoneAuth is not working when in production build

### ISSUE THREAD

**Issue by sardarusama41062** [invertase/react-native-firebase#2297]
I'm using react-native-firebase v 5.0 +.
The phone number authentication is working good for development build but in the production build it is only working for testing numbers and for any other number.

`    Here is the code for this

    export const signInWithPhone = (phoneNumber) => {
        return (dispatch) => {
            firebase.auth().signInWithPhoneNumber(phoneNumber)
                .then((confirmResult) => {
                    dispatch({
                        type: 'SIGN_IN_WITH_PHONE',
                        payload: confirmResult,
                        phoneNumber
                    })
                })
                .catch((error) => {
                    dispatch({
                        type: 'INVALID_PHONE_NUMBER',
                    })
                })
        }
    }
`
here is log cat logs
![cmd](https://user-images.githubusercontent.com/35162581/60265610-98412780-98ff-11e9-92ba-0768ffa48a99.PNG)

**Comment by mikehardy** [comment]
does not follow the template :-(

**Comment by sardarusama41062** [comment]
firebase.auth().signInWithPhoneNumber(phoneNumber)
  .then(confirmResult => // save confirm result to use with the manual verification code)
  .catch(error => /error);

quite similar to my code. but i am using redux to handle firabse calls
Here is template code. it is working fine in testing mode, not in the production.
