### ISSUE TITLE
🔥 Firebase module not installed natively issue only after archiving

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [invertase/react-native-firebase#2298]
## Issue

Describe your issue here

Getting this error after installing application via testflight.
`*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.messaging().
Ensure you have the required Firebase iOS SDK pod for this module included in your Podfile, in this instance confirm you've added "pod 'Firebase/Messaging'" to your Podfile`

Running the application with release config works perfectly fine. Issue happens only after archive.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'YouOnline' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YouOnline
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.2.0'
  pod 'Firebase/Messaging', '~> 6.2.0'

  post_install do |installer|
    system("mkdir -p Pods/Headers/Public/FirebaseCore && cp Pods/FirebaseCore/Firebase/Core/Public/* Pods/Headers/Public/FirebaseCore/")
  end

  target 'YouOnline-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YouOnlineTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'YouOnline-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YouOnline-tvOS

end

```

#### `AppDelegate.m`:

```objc
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
#import <Firebase.h>
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"YouOnline"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 787.22 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.0
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `firebase Messaging`
- **Are you using `TypeScript`?**
  - `Y`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I'm not sure it will work with use_frameworks without this patch.
I intend to release it shortly as react-native-firebase 5.5.5 but you might try integrating it via patch-package (or using an npm install that references the merged commit hash directly) to see if it fixes your issue?

https://github.com/invertase/react-native-firebase/pull/2235/files

**Comment by ASHFAQPATWARI** [comment]
@mikehardy I'm just not able to understand how is it working woith release configuration on device and issue only pops up on archive?

And for your solution, if i comment use_frameworks, will it work without patch?

**Comment by mikehardy** [comment]
I am not good enough at iOS yet to understand how there can be differences between release and archive either, with the exception that I just learned recently release mode might re-use information from previous builds whereas archive prompts Xcode to do a bit more local cache/state clearance prior to build

With regard to use_frameworks, you would have you to try it

You might try the react-native-clean-project module with a call to `react-native clean-project-auto` after install, and possible these commands which are not present in that project (yet) - https://github.com/pmadruga/react-native-clean-project/issues/18

That may surface the problem you are currently having on archive at an earlier date - ideally in debug if not at least release

**Comment by ASHFAQPATWARI** [comment]
@mikehardy ok let me try and get back

**Comment by ASHFAQPATWARI** [comment]
@mikehardy using your steps to clean and commenting use_frameworks solved the issue

**Comment by mikehardy** [comment]
did you test independently or both at once? My money is on the cleaning step as I believe use_frameworks failures result in compile problems in debug even but it would be useful to know. Either way glad you are working now!

**Comment by mikehardy** [comment]
Also, +1 internet points of you propose a PR to react-native-clean-project to close the related issue, so others benefit :-)

**Comment by ASHFAQPATWARI** [comment]
@mikehardy i tested both at once. but i bet its commenting use_frameworks because i was already using your react-native-clean-project. The only extra thing was the commands which you gave me apart from clean-auto

**Comment by mikehardy** [comment]
okay - thanks for reporting back. I made the PR to react-native-clean-project since that was *definitely* a thing (I proved it forwards and backwards) and I don't use use_frameworks myself but it was independently verified and vital if you needed it. So I think we're all good. Cheers!
