### ISSUE TITLE
 Firebase Dynamic Links and invites

### ISSUE THREAD

**Issue by Thawab** [invertase/react-native-firebase#23]
Hello, 
I know this project is in alpha and the other features and issues are more important than these two. I hope you consider supporting these two features in the roadmap.

https://firebase.google.com/docs/dynamic-links/
https://firebase.google.com/docs/invites/

Thanks

**Comment by Salakar** [comment]
It's not priority for us at the moment, but in the long run I would like to reach parity with what the native SDK's provide. 

The higher priority for us at the moment new feature wise would be ads. 

But, PR's that implement new features are also welcome. I'll add this onto the product board though now and close this issue for the time being.
