### ISSUE TITLE
"RNFirebaseAdMobNativeExpress" does not exist

### ISSUE THREAD

**Issue by nhoclove9x** [invertase/react-native-firebase#230]
Hi all,

I am getting this error Warning: Native component for "RNFirebaseAdMobNativeExpress" does not exist.

My code:

import RNFirebase from 'react-native-firebase';

const configurationOptions = {
  debug: true
};
const firebase = RNFirebase.initializeApp(configurationOptions);

const Banner = firebase.admob.Banner;
const NativeExpress = firebase.admob.NativeExpress;
const AdRequest = firebase.admob.AdRequest;

const request = new AdRequest();

<NativeExpress
                unitId={"ca-app-pub-7067933465676350/243688383"}
                size={"300x400"}
                request={request.build()}
                onAdLoaded={() => {
                  console.log('Advert loaded and is now visible');
                }}
              />

Help me !

**Comment by Ehesp** [comment]
Have you added the RNFirebaseAdMobPackage (`new RNFirebaseAdMobPackage()`)? Also Android or iOS?

**Comment by nhoclove9x** [comment]
in iOS i found problem and solved but i have problem in Android get error "null is not an object (evaluating 'internalInstance.getHostNode')"

**Comment by Salakar** [comment]
You need to do the same and include the admob package for android, see: http://invertase.io/react-native-firebase/#/migration-guide?id=_6-android-update-mainapplicationjava

**Comment by AlokGupta007** [comment]
Hi ,

I am getting following error.
![screenshot_1515589423](https://user-images.githubusercontent.com/8522143/34774397-2de491ba-f635-11e7-84b8-05381c1e8889.png)
