### ISSUE TITLE
Support For Firestore collectionGroup

### ISSUE THREAD

**Issue by shameemz** [invertase/react-native-firebase#2305]
Unhandled JS Exception: TypeError: TypeError: _reactNativeFirebase.default.firestore(...).collectionGroup is not a function

This issue is happening for both iOS and Android.

**Comment by mikehardy** [comment]
No template

**Comment by BartJanvanAssen** [comment]
checkout their feedback page https://invertase.io/oss/react-native-firebase/feedback/p/add-collectiongroup-query-support

**Comment by nwaughachukwuma** [comment]
That link is broken @BartJanvanAssen. Please is there any plan to support this in v5? Thanks so much

**Comment by holgersindbaek** [comment]
I really need this functionality as well @BartJanvanAssen.

**Comment by Ehesp** [comment]
This is possible in v5 but it's not as simple to implement due to the way the module is setup. Once we get v6 out we may backport it however we have to really focus on v6 at the moment.

**Comment by holgersindbaek** [comment]
@Ehesp When is v6 expected to release?

I've tried to look at bit into v6, but it seems unclear to me how far you are with it. Is there any guides on how to upgrade from v5 to v6?

**Comment by Ehesp** [comment]
@holgersindbaek apart from AdMob and Notifications, it's all "working" (apart from some build error/setup bugs). 

Re migration - planning on writing that soon... I'll post in here once I get there.

**Comment by holgersindbaek** [comment]
@Ehesp Thanks. The faster, the better. I really need the collectionGroup functionality.

**Comment by qalqi** [comment]
+1 for v5

**Comment by Ehesp** [comment]
We won't be adding collection group to v5 I'm afraid unless it's from a community contribution.

**Comment by rayvenz23** [comment]
I know this is old thread, but this might help others who wants to stick with v5. I was facing the same issue while using v5, I upgraded to v6 but the push notification is not working, and I don't want that.

I found my solution:
I reverted to v5, then I added [firebase](https://www.npmjs.com/package/firebase) to my project ( so there's now 2 firebase on my app ) but I call the 2nd one as :
import * as firebase2 from 'firebase';

then (after config ) :
firebase2.firestore().collectionGroup('mySubCollections').get()
