### ISSUE TITLE
Messaging and Notifications Packages

### ISSUE THREAD

**Issue by erksch** [invertase/react-native-firebase#2308]
Hey folks, love what you're doing!

Can you give information about when `@react-native-firebase/messaging` and `@react-native-firebase/notifications` will be available? 

Looking forward to using v6!

**Comment by Ehesp** [comment]
Hey Messaging is currently in progress. The goal in this version is to make it as bullet proof as possible so it's taking a while. Once complete, notifications will start to be implemented on top of messaging.
