### ISSUE TITLE
🔥Migration to Google Play Developer API v3

### ISSUE THREAD

**Issue by wmonecke** [invertase/react-native-firebase#2311]
## Issue

I recently got the following message on my google play dev console:

<img width="908" alt="Screenshot 2019-07-02 at 11 56 52" src="https://user-images.githubusercontent.com/24256469/60503783-aeb0ff80-9cc0-11e9-8ef7-64dbf6d380ee.png">

I think this is the only package I am using that has anything to do with the Google Play Developer API. Is this package using v1 or v2? And how would I migrate to v3 (if so)?

---

## Project Files

this is my package.json

````
"@kudo-ci/jsc-android": "^245459.9000.0",
    "axios": "^0.19.0",
    "chroma-js": "^2.0.2",
    "moment": "^2.23.0",
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-chart-kit": "^3.0.0",
    "react-native-color-picker": "github:FrederickEngelhardt/react-native-color-picker",
    "react-native-device-info": "^0.25.1",
    "react-native-easy-toast": "^1.2.0",
    "react-native-fbsdk": "^0.8.0",
    "react-native-firebase": "^5.2.0",
    "react-native-fs": "^2.13.3",
    "react-native-google-drive-api-wrapper": "^1.1.2",
    "react-native-google-places": "^3.1.1",
    "react-native-google-signin": "^1.2.3",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-localization": "^2.1.1",
    "react-native-location": "^2.3.0",
    "react-native-router-flux": "^4.0.6",
    "react-native-sortable-grid": "^2.0.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^9.5.1",
    "react-native-swiper": "^1.5.14",
    "react-native-text": "0.0.8",
    "react-native-vector-icons": "^6.1.0",
    "react-native-video": "^4.4.1",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "redux-persist": "^5.10.0",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.10.15",
    "unsplash-js": "^5.0.0"
````

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 5.92 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google Play Intel x86 Atom, android-P | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
So, what’s the URL at the link I can see but can’t click? What’s it say?
Does it go away when you upgrade to react-native-firebase v5.5.4 (and related react-native >= 0.59.3 / firebase android SDKs up to the last release before the AndroidX breaking change)?

**Comment by adamfisher** [comment]
The blog entry with more details can be found here:
 https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html

**Comment by shan-du** [comment]
The same warning message started showing up on our Android app, and I can't find a proper doc on how/where to exactly update the API version, I emailed Google and am waiting for an answer.

But did you try look into your CI tool if you use it to deploy to Google Play Store? There may be something there that use the API to push/publish your app

**Comment by Salakar** [comment]
Closing as not related to this library specifically, most likely a CI tool you may be using to publish your app to the store as @shan-du suggested. Feel free to continue the discussion though.
