### ISSUE TITLE
Getting Error Undefined symbols for architecture x86_64:   "_sqlite3_prepare_v3"

### ISSUE THREAD

**Issue by ririlya94** [invertase/react-native-firebase#2313]
## Issue

Hi all.. I'm quite newbie with RN and ios plattform.. So far, I follow the instruction to install the pods and firebase.. Everything works well.. But i keep getting error (refer to pic below)

![Screen Shot 2019-07-03 at 1 33 30 PM](https://user-images.githubusercontent.com/11284989/60565693-323d2000-9d97-11e9-966a-bf8afbe7f093.png)

Anyone know how to solve this? Thank you in advance

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'eeaproj' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eeaproj

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'eeaprojTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"
#import <CoreFoundation/CoreFoundation.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"EEA"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

@end

```

</p>
</details>

---

### Android

<details><summary>N/A</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 10.6.0
  Yarn: 1.16.0
  npm: 6.9.0
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.4 AI-183.6156.11.34.5522156

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.1 => 0.54.1
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^4.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Messaging & Notification`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by KyawSawThu** [comment]
did u solved this issued?
how did you solved?
please.

**Comment by ririlya94** [comment]
> did u solved this issued?
> how did you solved?
> please.

hi there @KyawSawThu .. i just manage to solve it ytd.. i'm not sure what OS and xcode version you use, but for me upgrade the os and xcode totally solve the problem

**Comment by dlajarretie** [comment]
I am facing the exact same issue with Xcode 11.6 on OS X 10.15.5, targeting iOS 13.6. Could this issue be reopened or should I create a new one ?

The issue happens when adding `@react-native-firebase/crashlytics` (version 8.3.1)

**Comment by mikehardy** [comment]
@dlajarretie no it cannot, open a new issue with fresh details, do not post on a year old issue.
Also, try `npx react-native-clean-project` and rebuild - this does not happen in our CI or on my work projects

**Comment by dlajarretie** [comment]
Thanks, `npx react-native-clean-project` fixed the problem. I love determinism 🙂

**Comment by mikehardy** [comment]
There are enough cache layers in the react-native house of cards that I feel like no CI is complete without react-native-clean-project. The iOS side of the build chain is the worst with regard to non-determinism as well, but occasionally gradle or yarn or metro will be caught out as well
