### ISSUE TITLE
Is there a "how-to" for making this work in expo?

### ISSUE THREAD

**Issue by ODelibalta** [invertase/react-native-firebase#232]
Hi all, 

I am very new to react native world and I would like to implement this library in my expo project. Is there a how to guide for exponent projects? thank you

**Comment by Salakar** [comment]
Hello!

See the section on our faq docs: http://invertase.io/react-native-firebase/#/faqs?id=usage-with-expo

**Comment by ZakherM** [comment]
There's a feature request on the expo canny.io
https://expo.canny.io/feature-requests/p/adding-react-native-firebase-to-expo
it deserves a vote.
