### ISSUE TITLE
Exception 'Can't use queryEndingAtValue: + iOS 

### ISSUE THREAD

**Issue by rajscet** [invertase/react-native-firebase#2325]
Exception 'Can't use queryEndingAtValue: with other types than string in combination with queryOrderedByKey'

I am getting above exception in iOS

![Simulator Screen Shot - iPhone X - 2019-07-05 at 02 54 38](https://user-images.githubusercontent.com/6961313/60723502-68be9a80-9f51-11e9-9f20-77b9151325d0.png)

const messagesRef = firebase
  .database()
  .ref()
  .child('messages');
let activeChatListener;
function fetchChatMessages(dispatch, chat_code, page, user_data, oldest_message) {
  currMessagesRef = messagesRef.child(chat_code);
  if (page == 1) {
    activeChatListener = currMessagesRef.orderByKey().limitToLast(1);
    dispatch(clearMessages());
    activeChatListener.on('child_added', data => {
      fetchUserData(dispatch, data.val().user, user_data);
      dispatch(appendMessage(createFirebaseMessage(data)));
    });
  } else if (page >= 2) {
    let old_messages = [];
    currMessagesRef
      .orderByKey()
      .endAt(oldest_message)
      .limitToLast(CHAT_PER_PAGE)
      .once('value', snapshot => {
        let old_messages = [];
        snapshot.forEach(function(data) {
          old_messages.unshift(createFirebaseMessage(data));
        });
        dispatch(prependMessages(old_messages.slice(1, old_messages.length)));
      });
  }

**Comment by Salakar** [comment]
Please can you fill out the issue template, otherwise we can't help you.

**Comment by Ehesp** [comment]
Also please format your code.

Closing until sorted, will reopen once we have everything we need.
