### ISSUE TITLE
Rendering Admob Banner inside react native flatlist items causes app to crash

### ISSUE THREAD

**Issue by andy-asi** [invertase/react-native-firebase#2331]
## Issue

I have integrated react-native-firebase and the AdMob module into my react native project and everything is working as expected (test ads and ads in production). I now want to add banners within my Flatlist (rendering a banner every X number of rows).

this is an example of the data I'm receiving from the server:

```
[
  {
   ...item 1 details
  },{
   ...item 2 details
  },{
   ...ad details
  },{
   ...item 3 details
  },{
   ...item 4 details
  },{
   ...ad details
  }
]
```
and this is the Flatlist component

```
class ItemsList extends React.Component {
  _renderItem = ({item, index}) => {

    if (item.isAd) {
      const unitId = Platform.OS === "ios" ? item.adIdIOS : item.adIdAndroid;
      const Banner = firebase.admob.Banner;
      const AdRequest = firebase.admob.AdRequest;
      const request = new AdRequest();
      const keyWords = item.admobKeywords || [];
      keyWords.forEach(keyword => {
        request.addKeyword(keyword);
      });

      return (
        <View style={{ width:"100%", height: item.adHeight || "auto", marginTop: 5, marginBottom: 15, alignItems: 'center', justifyContent: 'center' }}>
          <Banner
            size={item.adSize}
            request={request.build()}
            unitId={unitId}
            onAdLoaded={() => {}}
          />
        </View>
      )

    } else {
     renderItem()
    }
  }

  render() {
    return(
        <View>
          <FlatList 
            data={this.state.data}
            renderItem={this._renderItem}
            ...
          />
        </View>
    )
  };
};
```
the problem is that whenever a scroll event happens (user scrolls down), the Flatlist keeps re-rendering the banner (firing a new request) and the banner keeps refreshing. After a while, a lot of requests get fired and the application crashes!

I know that calling a network request inside a renderItem method is not a good practice so I also tried the following but the problem is still the same:

const Banner = firebase.admob.Banner;
const AdRequest = firebase.admob.AdRequest;
const request = new AdRequest();

```
class CatalogueSalesList extends React.Component {
  _renderItem = ({item, index}) => {

    if (item.isAd) {
      const unitId = Platform.OS === "ios" ? item.adIdIOS : item.adIdAndroid;
      const keyWords = item.admobKeywords || [];
      keyWords.forEach(keyword => {
        request.addKeyword(keyword);
      });

      return (
        <View style={{ width:"100%", height: item.adHeight || "auto", marginTop: 5, marginBottom: 15, alignItems: 'center', justifyContent: 'center' }}>
          <Banner
            size={item.adSize}
            request={request.build()}
            unitId={unitId}
            onAdLoaded={() => {}}
          />
        </View>
      )

    } else {
     renderItem()
    }
  }

  render() {
    return(
        <View>
          <FlatList 
            data={this.state.data}
            renderItem={this._renderItem}
            ...
          />
        </View>
    )
  };
};
```

Can someone please provide me with a solution to how a banner ad could be implemented inside a Flatlist without the banner getting re-rendered every time the user scrolls through the list?

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm using Pods and my Podfile looks like:

platform :ios, '9.0'

target 'Admob' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # # # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.2.0'
  pod 'Firebase/Auth', '~> 6.2.0'
  pod 'Firebase/Database', '~> 6.2.0'
  pod 'Firebase/Messaging', '~> 6.2.0'
  pod 'Firebase/AdMob', '~> 6.2.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [X ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
      Memory: 137.14 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.4.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 19, 21, 23, 24, 25, 26, 28
        Build Tools: 21.1.2, 23.0.2, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.0, 27.0.3, 28.0.2, 28.0.3
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

- **Platform that you're experiencing the issue on**:
  - [X] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 5.5.3
- **`Firebase` module(s) you're using that has the issue:**
  - Admob
- **Are you using `TypeScript`?**
  - N
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
this seems like a general react question, not anything to do with react-native-firebase?

My first idea would be to override shouldComponentUpdate in a special component included in the flatlist for banner display, and toggle to false after the first render, only fetch if true

But this question could as easily apply to any thing you did in a flatlist and we're pretty swamped with firebase-specific questions, so I think it's more suited to stackoverflow
