### ISSUE TITLE
🔥 Doing user.sendEmailVerification() multiple times returns "auth/unknown" in Android

### ISSUE THREAD

**Issue by Hachimori** [invertase/react-native-firebase#2337]
## Issue

Firebase Authentication returns an error when the app tries to do user.sendEmailVerification() multiple times in a short period of time.
Returning an error itself is OK, however, I noticed that different error codes are returned depending on device's OS.
  - In Android, an error code "auth/unknown" is provided.
  - In iOS, an error code "auth/too-many-requests" is provided.

For me, returning "auth/too-many-requests" sounds more reasonable.
Is there anything wrong with my setup, or is it a known issue on library side?

---

## Project Files

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
    classpath 'com.android.tools.build:gradle:3.3.0'
    classpath 'io.fabric.tools:gradle:1.+'
    classpath 'com.google.gms:google-services:4.2.0'
    classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31'
```

#### `android/app/build.gradle`:

```groovy
    implementation "com.google.android.gms:play-services-base:16.0.0"
    
    implementation "com.google.firebase:firebase-core:17.0.0"
    implementation "com.google.firebase:firebase-firestore:20.1.0"
    implementation "com.google.firebase:firebase-auth:18.0.0"
    implementation "com.google.firebase:firebase-invites:17.0.0"
    implementation "com.google.firebase:firebase-messaging:19.0.1"
    implementation "com.google.firebase:firebase-storage:18.0.0"
    implementation "com.google.firebase:firebase-database:18.0.0"
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 445.26 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 26.0.3, 27.0.3, 28.0.1, 28.0.3
        System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `5.5.4`
- **`Firebase` module(s) you're using that has the issue:**
  - `Auth`
- **Are you using `TypeScript`?**
  - `Y`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Salakar** [comment]
![image](https://user-images.githubusercontent.com/5347038/60883674-b7668000-a242-11e9-8dc8-40c959e43924.png)


Please change this to the React Native Firebase library version, not the React Native version, thanks.

**Comment by Ehesp** [comment]
There's a few differences like this between the Android/iOS SDKs. The issue will be too many requests on Android but it's not handled hence defaults to the unknown error. Not much we can do here as we couldn't guarantee an "unknown" is too many requests.
