### ISSUE TITLE
Initializing admob throws an error

### ISSUE THREAD

**Issue by kashmiry** [invertase/react-native-firebase#2338]
## Issue

after upgrading to the latest 5.5.4 from 5.3.1. I am getting issues linking admob. I spent half a day trying to fix this resetting everything, but the issues still remains.
I get this when I run the app from Xcode, first I see the splash screen then app goes blank, and throws this error.
`Unhandled JS Exception: You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.admob().`

The issue only happens if initialize admob on App.js, like this:

```
//Firebase and admob
import firebase from 'react-native-firebase';
firebase.admob().initialize('ca-app-pub-###');
```

It used to work fine, not sure whats wrong with linking admob.
I tried to remove pods, and then installing them again, doing pod update. I reseted all packages. did `react-native link react-native-firebase`.
what else can I do to fix this?

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'appalpha' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'GoogleIDFASupport', '~> 3.14.0'
  pod 'Firebase/AdMob', '~> 6.3.0'
  # Pods for appalpha

  target 'appalphaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'appalpha-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for appalpha-tvOS

  target 'appalpha-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  [FIRApp configure];
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"appalpha"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [UIColor blackColor];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  //[GADMobileAds configureWithApplicationID:@"ca-app-pub-###"];
  // Initialize the Google Mobile Ads SDK.
  [[GADMobileAds sharedInstance] startWithCompletionHandler:nil];
  
  return YES;
}

@end

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
      Memory: 68.75 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.6 
      react-native: ^0.59.0 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `5.5.4`
- **`Firebase` module(s) you're using that has the issue:**
  - `AdMob`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I apolo8, we have been battling some ios linking problem in 55x and I'm not sure what the root cause is yet. Two options one is to look at at recent issues to see if someone else has a solution already, other is to use rnfb 54x and ios pods 5.20.,x for now

**Comment by kashmiry** [comment]
> I apolo8, we have been battling some ios linking problem in 55x and I'm not sure what the root cause is yet. Two options one is to look at at recent issues to see if someone else has a solution already, other is to use rnfb 54x and ios pods 5.20.,x for now

Thank you! I used to try to downgrade without luck, I was not aware I should downgrade the pods as well.
Currently using rnfb 5.4.0 & pods like this:

>   pod 'Firebase/Core', '~> 5.20.1'
>   pod 'GoogleIDFASupport', '~> 3.14.0'
>   pod 'Firebase/AdMob', '~> 5.20.1'

and everything is working.

I wanted to know also what the right way to initialize admob in appDelegate
I used to do it like this 
`[GADMobileAds configureWithApplicationID:@"ca-app-pub-###"];`
know its seems to be changed to this
`[[GADMobileAds sharedInstance] startWithCompletionHandler:nil];`

When was this ever changed? was it a change by google?
