### ISSUE TITLE
Persisting second app initialization.

### ISSUE THREAD

**Issue by sauravexodus** [invertase/react-native-firebase#2339]
I am initializing another firebase app instance in my root component. But whenever I restart the app I lose this second firebase app and only the default app instance is available. Any idea how to fix this? Or will I have to initialize it every time?

I am also passing `persistence: true` to the initializeApp function when I initialize the second app.

**Comment by Salakar** [comment]
@sauravexodus you need to call `initializeApp` every time your app boots. If you don't want to do this everytime then you can initialize additional apps in native code on Android & iOS - RNFirebase will pick these up and make them available in JS immediately without you needing to initialize them (same as the default app)

Example below:

### Create a secondary Firebase app on iOS

`ios/AppDelegate.m`:
```objc
// ...
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // your default app
  [FIRApp configure];
  // your secondary app
  [FIRApp configureWithName:@"cats" options:[FIRApp defaultApp].options];
  // ...
}

// ...
```

### Create a secondary Firebase app on Android

`android/app/**/MainApplication.java`:
```java
// ...
// add the import with the other imports
import com.google.firebase.FirebaseApp;
// ...

// make a secondary app inside your main application onCreate method
public class MainApplication extends Application implements ReactApplication {
  // ...
  @Override
  public void onCreate() {
    super.onCreate();

    // your secondary app
    FirebaseApp.initializeApp(this, FirebaseApp.getInstance().getOptions(), "cats");

    // ...
  }
  // ...
}
```


### Accessing Secondary App in JavaScript

```js
const catsApp = firebase.app('cats');
```

----

The example above assumes you want a secondary app that uses the same credentials/firebase project as the default app. If you need to use different credentials then you'll need to build the via `FirebaseOptions.Builder` on Android or `FIROptions` on iOS.

Hope that helps.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
