### ISSUE TITLE
Implicit declaration of function RCTJSErrorFromNSError

### ISSUE THREAD

**Issue by cladjules** [invertase/react-native-firebase#234]
(Please write your issue here along with the environment details below)

### Environment

1. iOS
2. macOS Sierra
3. Xcode 8.3.3
4. React Native Version 0.42.0
5. RNFirebase Version 2.0.0

Hi there,

I followed all the step,
I managed to include Firebase and it's all linking together.

Though when building, I get that error:

`node_modules/react-native-firebase/ios/RNFirebase/config/RNFirebaseRemoteConfig.m:62:41: Implicit declaration of function 'RCTJSErrorFromNSError' is invalid in C99`

The function RCTJSErrorFromNSError exists in the files but nothing helps to get that working.

Thanks,

best regards,

**Comment by erezrokah** [comment]
I have the same issue.

Environment:
iOS
macOS Sierra
Xcode 8.3.3
React Native Version 0.42.3
RNFirebase Version 2.0.2

**Comment by chrisbianca** [comment]
I think this is missing an import of `RCTUtils` as `RCTJSErrorFromNSError` is part of that package

**Comment by akshetpandey** [comment]
😨  This exists at the top

```objc
#if __has_include(<React/RCTUtils.h>)
#import <React/RCTUtils.h>
#else // Compatibility for RN version < 0.40
#import "RCTUtils.h"
#endif
```

**Comment by akshetpandey** [comment]
But maybe the functions don't exists in RN < 0.40?

**Comment by Ehesp** [comment]
@akshetpandey which file is that? In v2 we removed that code as we moved to only supporting 0.40+.

**Comment by akshetpandey** [comment]
Oh, it's there in 1.x in RNFirebaseRemoteConfig.m
Maybe they are on a react version older than 0.40?

**Comment by cladjules** [comment]
In the latest version, adding the import to RNFirebaseRemoteConfig.m
`#import <React/RCTUtils.h>`

solves the issue though, 

shall it be added to a PR fix the issue? 

Thanks

**Comment by chrisbianca** [comment]
@cladjules it's strange that this doesn't happen for us as well.  I've added the import and pushed the code.

Are you able to check if the latest commit fixes the issue?  If so, I will bundle it up in a release with a few other fixes later today.

Simply run: `npm install --save git+https://github.com/invertase/react-native-firebase.git` to install the latest GitHub commit.

**Comment by chrisbianca** [comment]
I'm going to close this as fixed, and it will be bundled up into the next release.
