### ISSUE TITLE
firebase.admob().rewarded.off in not a function

### ISSUE THREAD

**Issue by iLyxa3D** [invertase/react-native-firebase#2340]
```
const advert = firebase.admob().rewarded(...);

componentDidMount() {
    advert.on('onRewarded', this.onRewardedHandler);
}

componentWillUnmount() {
    advert.off('onRewarded', this.onRewardedHandler);
}

**Error**: _App.advert.off is not a function
```

Can not find how to unsubscribe listener from **firebase.admob().rewarded**.
It looks like it is not implemented in the package code.

"react-native-firebase": "^5.5.3",
OS: Android

**Comment by Ehesp** [comment]
On v6, the `onAdEvent` listener now returns an unsubscribe event.
