### ISSUE TITLE
Doc says gradle 3.4.1 can be used but it is incompatible with latest React-native

### ISSUE THREAD

**Issue by TomBerriot** [invertase/react-native-firebase#2344]
## Documentation Feedback

Page concerned : https://rnfirebase.io/docs/v5.x.x/releases/v5.5.x#Android---Update-Dependencies

On the 5.5.X release upgrade instructions, it is mentioned that you must upgrade gradle build tools to 3.3.2 or higher.
As an exemple, it is shown to upgrade it to 3.4.1 (`classpath 'com.android.tools.build:gradle:3.4.1'`), but this version is incompatible with the react-native 0.59 (and maybe above, i don't know).

Source -> https://github.com/facebook/react-native/issues/24854#issuecomment-493925483

This has led to this sort of issue https://github.com/react-native-community/async-storage/issues/151

**Comment by wellmonge** [comment]
Same issue here! Getting error running rnfirebase with RN 0.59.9

**Comment by mikehardy** [comment]
I read the comments - clearly an issue for some, but I've had no problems personally. I'd suppose 3.3.x gradle would be fine.

**Comment by TomBerriot** [comment]
@mikehardy Yes this is it. So we set our gradle version to 3.3.2 instead of 3.4.X

**Comment by wodka** [comment]
At the same time if you use 0.59.9 it should work -> it the reason the build did not work was an invalid path for gradle (https://github.com/facebook/react-native/releases/tag/v0.59.9)
