### ISSUE TITLE
🔥 osx template installation fails

### ISSUE THREAD

**Issue by gorhgorh** [invertase/react-native-firebase#2351]
## Issue

Hi there, I'm trying to install the rn/firebase template using nxp, following the guide for setting up a new project, installation fails on osx during the ios dependencies installation part for a pod issue 

```
[!] CocoaPods could not find compatible versions for pod "Firebase/Core":
  In Podfile:
    RNFBApp (from `../node_modules/@react-native-firebase/app/ios`) was resolved to 0.0.26, which depends on
      Firebase/Core (~> 5.20.2)
```

As the error happen during the installation, no project is created so i can not try to update the podfile

the full installation log is available [here](https://gist.github.com/gorhgorh/3f38d4f6a7909c5948aaf346f005f10f)

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

As the project is not installed because of the issue i can not run `react-native info` so this is the output of another project as the platform and ide infos are still valid.

```
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
      Memory: 139.39 MB / 16.00 GB
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
      npm: 6.10.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 21, 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.3
        System Images: android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - N/A
- **`Firebase` module(s) you're using that has the issue:**
  - N/A
- **Are you using `TypeScript`?**
  - N/A
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Salakar** [comment]
Hey, this is related to an RN cli issue discussed here: https://github.com/invertase/react-native-firebase/issues/2025#issuecomment-497696912

Can you try the mentioned solution before trying to init the template, thanks

**Comment by gorhgorh** [comment]
yay, that was that 🎉, I did search for the error before making this issue, sorry about the duplicate ...

**Comment by Salakar** [comment]
@gorhgorh no problem :)

Will close this issue for now as we're tracking it on v6 issue.

**Comment by mikehardy** [comment]
This just bit someone that posted on Discord, I believe the CLI has the feature now where it you can request to run a pod repo update prior to the pod install, and for react-native-firebase that will be important as the normal react-native-firebase v6 documentation path for the new project flow will result in users with outdated pod repos failing on template install now

**Comment by Ehesp** [comment]
Docs now include commands to make sure users pods are updated. I think it's worth leaving out any CLI specific commands until it's officially landed/tested on their end.
