### ISSUE TITLE
Cannot find symbol RNFirebasePackage

### ISSUE THREAD

**Issue by sandy2196** [invertase/react-native-firebase#2353]
## Issue

Describe your issue here

---
When I am adding React-Native-Firebase to my existing project. Then Build gets Failed with error: Cannot Found Symbol RNFirebasePackage. This problem is occurring due to react-native link react-native-firebase.
The link command adds 
import io.invertase.firebase.RNFirebaseAdMobPackage;
instead of 
import io.invertase.firebase.RNFirebasePackage;
and also in protected List<ReactPackage> getPackages() {...}
### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by robleds** [comment]
Same here ... RN 0.59.10 and RNF 5.3.1
I tried several times but nothing worked
... still researching

**Comment by muhammadsarim555** [comment]
@robleds robleds have you found solution?

**Comment by sandy2196** [comment]
The temporary solution would be
**In MainApplication.java**
Replace
import io.invertase.firebase.RNFirebaseAdMobPackage;
With
import io.invertase.firebase.RNFirebasePackage;
And Replace
new RNFirebaseAdMobPackage();
With
new RNFirebasePackage();

**Comment by ravikiran6763** [comment]
> RNFirebasePackage

did not work for me

**Comment by sandy2196** [comment]
@ravikiran6763: What error did you get?

**Comment by ravikiran6763** [comment]
> @ravikiran6763: What error did you get?

import io.invertase.firebase.RNFirebaseAdMobPackage;
                            ^
  symbol:   class RNFirebaseAdMobPackage
  location: package io.invertase.firebase
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by sandy2196** [comment]
@ravikiran6763
Remove that import and add:
`import io.invertase.firebase.RNFirebasePackage;`
and if is in here, also remove it:
```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(new MainReactPackage(), new RNGestureHandlerPackage(),
          );
    }
```

**Comment by robleds** [comment]
> @robleds i am having the same issue .have you found solution?

Yes @muhammadsarim555 ... I did remove iOS and Android folder, clean project cache and did `react-native eject` and `react-native link` to start from beginner. 

I followed these steps:
https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

I didn't run the script. I just followed each line step by step.
Works.

**Comment by bitlab-code** [comment]
Same here. RN v0.59.10 and RNF v5.3.1
[this work](https://github.com/invertase/react-native-firebase/issues/2353#issuecomment-511198928)
