### ISSUE TITLE
iOS build error Undefined symbols for architecture x86_64 

### ISSUE THREAD

**Issue by smeekmeister** [invertase/react-native-firebase#2354]
Build on iOS fails for some mysterious reason
Using version 5.5.5
Previously I did not run into any trouble

Error encountered
warning: directory not found for option '-F/Users/smekens/Github/js-in-the-loop-mobile/ios/Frameworks'
Undefined symbols for architecture x86_64:
  "_FIRFirestoreErrorDomain", referenced from:
      ___54-[RNFirebaseFirestore transactionBegin:transactionId:]_block_invoke in libRNFirebase.a(RNFirebaseFirestore.o)
  "_OBJC_CLASS_$_FIRActionCodeSettings", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIRAuth", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIRDocumentReference", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseFirestoreDocumentReference.o)
  "_OBJC_CLASS_$_FIREmailAuthProvider", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIRFacebookAuthProvider", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIRFieldPath", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseFirestoreDocumentReference.o)
      objc-class-ref in libRNFirebase.a(RNFirebaseFirestoreCollectionReference.o)
  "_OBJC_CLASS_$_FIRFieldValue", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseFirestoreDocumentReference.o)
  "_OBJC_CLASS_$_FIRFirestore", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseFirestore.o)
  "_OBJC_CLASS_$_FIRFirestoreSettings", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseFirestore.o)
  "_OBJC_CLASS_$_FIRGeoPoint", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseFirestoreDocumentReference.o)
  "_OBJC_CLASS_$_FIRGitHubAuthProvider", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIRGoogleAuthProvider", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIROAuthProvider", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIRPhoneAuthProvider", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIRTimestamp", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseFirestoreDocumentReference.o)
  "_OBJC_CLASS_$_FIRTwitterAuthProvider", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Pod file

target 'Test' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
      
    # Pods for Test
    pod 'Firebase/Core', '~> 6.2.0'
    pod 'Firebase/Database', '~> 6.2.0'
    pod 'Firebase/Storage', '~> 6.2.0'
    pod 'Fabric', '~> 1.10.0'
    pod 'Crashlytics', '~> 3.13.1'
    pod 'Firebase/Functions', '~> 6.2.0'
    pod 'Firebase/DynamicLinks', '~> 6.2.0'
    pod 'Firebase/Messaging', '~> 6.2.0'
    pod 'FBSDKCoreKit', '~> 4.38.1'
    pod 'FBSDKLoginKit', '~> 4.38.1'
    pod 'FBSDKShareKit', '~> 4.38.1'
    pod 'GoogleSignIn', '~> 4.4.0'
    # Add new pods below this line

**Comment by smeekmeister** [comment]
I have tried quite a lot. eg. the advice on RN Firebase site
product > clean
close Xcode
pod install
open workspace
product clean
build
run symbols error keeps on appearing

**Comment by smeekmeister** [comment]
For what it is worth, managed to work around the build error with symbols, by comparing with another project where there were no build errors. Turns out that in Target Linked Libraries, libRNFirebase.a needs to be positioned UNDER the Javascript Framework entry, instead of above. Does this ring a bell ?

**Comment by jorisw** [comment]
Tried what you did, smeekmeister, but it made my problem worse:

```
Undefined symbols for architecture x86_64:
  "_GPBCheckRuntimeVersionSupport", referenced from:
      _GPB_DEBUG_CHECK_RUNTIME_VERSIONS in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      _GPB_DEBUG_CHECK_RUNTIME_VERSIONS in libFirebaseMessaging.a(GtalkExtensions.pbobjc.o)
  "_GULIsLoggableLevel", referenced from:
      _FIRIsLoggableLevel in libFirebaseCore.a(FIRLogger.o)
  "_GULLogBasic", referenced from:
      _FIRLogBasic in libFirebaseCore.a(FIRLogger.o)
  "_GULLoggerEnableSTDERR", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in libFirebaseCore.a(FIRLogger.o)
  "_GULLoggerForceDebug", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in libFirebaseCore.a(FIRLogger.o)
  "_GULLoggerInitializeASL", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in libFirebaseCore.a(FIRLogger.o)
  "_GULLoggerRegisterVersion", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in libFirebaseCore.a(FIRLogger.o)
  "_GULResetLogger", referenced from:
      _FIRResetLogger in libFirebaseCore.a(FIRLogger.o)
  "_GULSetLoggerLevel", referenced from:
      _FIRSetLoggerLevel in libFirebaseCore.a(FIRLogger.o)
  "_OBJC_CLASS_$_GPBCodedOutputStream", referenced from:
      objc-class-ref in libFirebaseMessaging.a(FIRMessagingSecureSocket.o)
  "_OBJC_CLASS_$_GPBDescriptor", referenced from:
      objc-class-ref in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      objc-class-ref in libFirebaseMessaging.a(GtalkExtensions.pbobjc.o)
  "_OBJC_CLASS_$_GPBEnumDescriptor", referenced from:
      objc-class-ref in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      objc-class-ref in libFirebaseMessaging.a(GtalkExtensions.pbobjc.o)
  "_OBJC_CLASS_$_GPBFileDescriptor", referenced from:
      objc-class-ref in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      objc-class-ref in libFirebaseMessaging.a(GtalkExtensions.pbobjc.o)
  "_OBJC_CLASS_$_GPBMessage", referenced from:
      _OBJC_CLASS_$_GtalkHeartbeatPing in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      _OBJC_CLASS_$_GtalkHeartbeatAck in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      _OBJC_CLASS_$_GtalkErrorInfo in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      _OBJC_CLASS_$_GtalkSetting in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      _OBJC_CLASS_$_GtalkHeartbeatStat in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      _OBJC_CLASS_$_GtalkHeartbeatConfig in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      _OBJC_CLASS_$_GtalkLoginRequest in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      ...
  "_OBJC_CLASS_$_GPBRootObject", referenced from:
      _OBJC_CLASS_$_GtalkGtalkCoreRoot in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      _OBJC_CLASS_$_GtalkGtalkExtensionsRoot in libFirebaseMessaging.a(GtalkExtensions.pbobjc.o)
  "_OBJC_CLASS_$_GULAppDelegateSwizzler", referenced from:
      objc-class-ref in libFirebaseMessaging.a(FIRMessaging.o)
      objc-class-ref in libFirebaseMessaging.a(FIRMessagingAnalytics.o)
      objc-class-ref in libFirebaseMessaging.a(FIRMessagingContextManagerService.o)
      objc-class-ref in libFirebaseMessaging.a(FIRMessagingRemoteNotificationsProxy.o)
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
      objc-class-ref in libFirebaseCore.a(FIRBundleUtil.o)
      objc-class-ref in libFirebaseInstanceID.a(FIRInstanceID.o)
  "_OBJC_CLASS_$_GULReachabilityChecker", referenced from:
      objc-class-ref in libFirebaseMessaging.a(FIRMessaging.o)
  "_OBJC_CLASS_$_GULUserDefaults", referenced from:
      objc-class-ref in libFirebaseMessaging.a(FIRMessaging.o)
      objc-class-ref in libFirebaseMessaging.a(FIRMessagingPubSub.o)
      objc-class-ref in libFirebaseInstanceID.a(FIRInstanceIDUtilities.o)
      objc-class-ref in libFirebaseInstanceID.a(FIRInstanceIDCheckinPreferences.o)
  "_OBJC_METACLASS_$_GPBMessage", referenced from:
      _OBJC_METACLASS_$_GtalkHeartbeatPing in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      _OBJC_METACLASS_$_GtalkHeartbeatAck in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      _OBJC_METACLASS_$_GtalkErrorInfo in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      _OBJC_METACLASS_$_GtalkSetting in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      _OBJC_METACLASS_$_GtalkHeartbeatStat in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      _OBJC_METACLASS_$_GtalkHeartbeatConfig in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      _OBJC_METACLASS_$_GtalkLoginRequest in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      ...
  "_OBJC_METACLASS_$_GPBRootObject", referenced from:
      _OBJC_METACLASS_$_GtalkGtalkCoreRoot in libFirebaseMessaging.a(GtalkCore.pbobjc.o)
      _OBJC_METACLASS_$_GtalkGtalkExtensionsRoot in libFirebaseMessaging.a(GtalkExtensions.pbobjc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by smeekmeister** [comment]
@jorisw I am getting reference errors from libRNFirebase.a only. I am on RN 059.10
And RNFirebase is the only Firebase library linked 

(not FirebaseCore, Messaging, etc ... )
