### ISSUE TITLE
Enabling/Disable Firebase Snapshot Listener

### ISSUE THREAD

**Issue by Hirvesh** [invertase/react-native-firebase#2358]
I have an issue, where I am attaching a listener to a collection on my "Home" screen:

```
componentWillMount() {
    this.ref = firebase.firestore().collection('users').doc(this.state.user.uid).collection('items');
}

componentDidMount() {
    this.unsubscribe = this.ref.onSnapshot(this.onCollectionUpdate);
}
```

Now I have another page where I can change the firebase user, basically migrating an anonymous user to an existing Google account - the page is called "AddAccount"

My issue is, when I delete the anonymous account and login using the existing Google account to restore data for that account, my listener on the "Home" screen is still listening to the old anonymous account collection and throws a permission error since the account is deleted now.

Is there a way where I can globally access listeners and switch them on/off as I perform data migration on the "AddAccount" page?

**Comment by Ehesp** [comment]
You need to call the unsubscribe function when the component unmouts.

Also please follow the issue template. I'm not sure what version all of this is running on.
