### ISSUE TITLE
App does not start if I add the stuff to AppDelegate.m

### ISSUE THREAD

**Issue by ODelibalta** [invertase/react-native-firebase#236]
When I add those two lines to AppDelegate.m, simulator fires up and nothing happens after that. 

### Environment

1. Target Platform iOS:
2. Development Operating System macOS Sierra:
3. Build tools (Xcode: Version 8.3.3 (8E3004b), iPhone 6 ios 10.3):
```
"scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.1",
    "react-native-firebase": "^2.0.2"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.1.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
```

```
#import "AppDelegate.h"
#import <Firebase.h>

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

.
.
.

  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [FIRApp configure];
  return YES;
}
```

**Comment by Ehesp** [comment]
Anything in the xcode logs?

**Comment by ODelibalta** [comment]
How do I find that? I open xcode window> devices and selected iphone6 (simulator uses that) but there is nothing about logs. 

I am about to lose it. It's been two days I've been trying to get this to work. I downloaded the example app from here and guess what, that works. When I do the steps, it does not.

**Comment by ODelibalta** [comment]
I figured out and it was my mistake. I was copying the .plist file via finder. I added the file to the project within xcode. everything works now. I literally spend my entire weekend for this. I do not feel too highly of myself right now :) please close. ty !
