### ISSUE TITLE
Build App IOS

### ISSUE THREAD

**Issue by lfoliveir4** [invertase/react-native-firebase#2368]
After I install react-native-firebase with the following command: 

yarn add react-native-firebase 

and link the native dependencies with the command: 

react-native link react-native-firebase 

when I build the application by command: react-native run-ios 

the error below appears:

![IMG-20190715-WA0171](https://user-images.githubusercontent.com/32423942/61260627-5284bb80-a755-11e9-9094-40d1f3793f7d.jpg)

Version:
react-native: 0.59.9
react-native-firebase: 5.5.5

**Comment by ankha0109** [comment]
same here
