### ISSUE TITLE
No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()

### ISSUE THREAD

**Issue by diegojimenes** [invertase/react-native-firebase#2369]
## Issue

Describe your issue here

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by SimonErich** [comment]
@diegojimenes how did you solve this?
Having the same problem right now.

**Comment by mikehardy** [comment]
This shows up when RNFB isn't installed correctly - firebase will create the default app for you if you install - you might check my install demo in particular this line for iOS at least https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh#L14

**Comment by SimonErich** [comment]
Thanks @mikehardy that solved it for me.
I used the react-native-firebase cli and thought that would have initialized it automatically.

**Comment by jasperkuperus** [comment]
I initially placed the `[FIRApp configure];` just before `return YES;` in `application:didFinishLaunchingWithOptions`. Moving the `configure` to the start of this method solved it for me.

**Comment by thanhduyspkt** [comment]
> I initially placed the `[FIRApp configure];` just before `return YES;` in `application:didFinishLaunchingWithOptions`. Moving the `configure` to the start of this method solved it for me.
it's magic, man

**Comment by adamgajzlerowicz** [comment]
feels like the documentation is wrong...

**Comment by mikehardy** [comment]
There is an edit button at the top right of every documentation page. The docs aren't perfect, but are easy to fix at least...

**Comment by rob5408** [comment]
I'm having this issue, but on the Android side. Is there an equivalent to `[FIRApp configure];` that belongs in `MainApplication` or `MainActivity`?

**Comment by mikehardy** [comment]
@rob5408 so it's not the same issue, it's different. You should open a new issue with full details in the template, but I'd encourage you to try a throw-away app first, clean and simple, to see how things work. I usually point people to this to see how things are integrated from scratch (you can clone the repo, follow the comments in the script and run it - it'll work) - you don't mention your version but the repo has a make-demo script for all the major variants people use react-native-firebase for, you can find one that fits: https://github.com/mikehardy/rnfbdemo

**Comment by rob5408** [comment]
Cool, I'll try the v6 script to make a demo app. I'm upgrading from a 0.59.x react-native project with rnfirebase 5.3.1 to react-native 0.61.5 and rnfirebase 6.3.0. The iOS upgrade process was about an hour. I'm on my second week of the Android upgrade 😬.

**Comment by rob5408** [comment]
@mikehardy Your script was super helpful (specifically https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh), thanks a bunch.

**Comment by abdi4** [comment]
Is there any reason why this might work in ios and the error in the titile show in android??

**Comment by chengsam** [comment]
If you are using other dynamic frameworks with `use_frameworks!` in your pod file, you have to force using firebase as a static framework. To do this, put the following line at the top of your pod file.

`$RNFirebaseAsStaticFramework = true`

**Comment by Eumhongin** [comment]
omg.. 

> I initially placed the `[FIRApp configure];` just before `return YES;` in `application:didFinishLaunchingWithOptions`. Moving the `configure` to the start of this method solved it for me.

LEGEND...

**Comment by Ehesp** [comment]
@Eumhongin how come you ran into this issue? It is explained on the first page in the docs:

![image](https://user-images.githubusercontent.com/842078/80907698-f3f2f300-8d10-11ea-9af2-bcd88ef04b7f.png)

**Comment by Tichuottt** [comment]
> I initially placed the `[FIRApp configure];` just before `return YES;` in `application:didFinishLaunchingWithOptions`. Moving the `configure` to the start of this method solved it for me.

I blame google for not suggesting me this solutions an hour ago

**Comment by minsoo-web** [comment]
> I initially placed the `[FIRApp configure];` just before `return YES;` in `application:didFinishLaunchingWithOptions`. Moving the `configure` to the start of this method solved it for me.

Thanks, you saved my life

**Comment by ahaseeb001** [comment]
> I initially placed the `[FIRApp configure];` just before `return YES;` in `application:didFinishLaunchingWithOptions`. Moving the `configure` to the start of this method solved it for me.

you are an angel save my life thanks for this reply

**Comment by jotilohana** [comment]
would it be added in appdelegate.m file??

**Comment by mikehardy** [comment]
@jotilohana here is a script that follows our docs and takes a bare react-native project from scratch to fully configured for react-native-firebase, with comments, examine that (run it even...) and you'll see how a project is supposed to look. I use it for build testing while maintaining this repo so I run it all the time and I know it works https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

**Comment by hassanharoon321** [comment]
I initially placed the [FIRApp configure]; just before return YES; in application:didFinishLaunchingWithOptions. Moving the configure to the start of this method solved it for me.

file name??
