### ISSUE TITLE
RNFirebase Android Gradle Sync/Build Issue

### ISSUE THREAD

**Issue by AndyScottt** [invertase/react-native-firebase#2370]
Hi there, after upgrading to the recent RNFirebase v5.5.5, I started experiencing some issues with an existing RN 0.60.0 project. Initially I had autolinking issues but that was resolved with the fix from [here](https://github.com/zico4reel/React-Native-Firebase-implementation-fix). So I tried creating a brand new react-native project using react-native init, and I'm hitting the same issues.

I ran **npm install react-native-firebase**  and _didn't_ run **react-native link react-native-firebase** due to the recent autolinking fix. 

When I attempt to gradle sync or build the project via Android Studio (Newest version, newest SDK) I get the following errors:

> ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :react-native-firebase.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :react-native-firebase.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :react-native-firebase.
> Show Details
> Affected Modules: app

I also tried running **react-native link react-native-firebase** but that didn't help at all.

I'm wondering if anyone is hitting the same issue or could possibly replicate it?

Cheers.
---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by slushman** [comment]
@AndyScottt I ran into this on a new install. Did you resolve this?

**Comment by mikehardy** [comment]
I can't reproduce this on a new app - I use this script for reproductions, it builds one from scratch each time: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by slushman** [comment]
Thanks @mikehardy! In the script it says it’s for RN 0.60. Have you tried this with 0.61? I’m wondering if that might be part of my issue.

**Comment by mikehardy** [comment]
I just had a [user report that it was broken on RN61 for a very specific reason](https://github.com/invertase/react-native-firebase/issues/2517#issuecomment-536161046) which I literally https://github.com/mikehardy/rnfbdemo/commit/1ba0e5675c6e16a6cd6fd792f1bec26b4ae6a3c3 :-) 

If you update (or haven't cloned yet) It should work. I'm in the final steps of verifying it to make sure

It definitely worked for RN60, just validating RN61 is the task at hand

**Comment by mikehardy** [comment]
Oh - and react-native-firebase v5.5.6 (and v6 I believe) definitely work with react-native 0.61.x in general - my work project is already upgraded and we're launching it in prod today
