### ISSUE TITLE
No Notification Sound or Vibration on Receiving Notification  

### ISSUE THREAD

**Issue by sourabhchotia** [invertase/react-native-firebase#2379]
this.notificationListener = firebase.notifications().onNotification(async (notification: Notification) => {
      
      console.log(notification);
      const newNotification = new firebase.notifications.Notification()
        .setNotificationId(new Date().getTime().toString())
        .setTitle(notification.title)
        .setSubtitle(notification.subtitle || "")
        .setBody(notification.body)
        .setSound('default')
        .setData(notification.data)
        .android.setVibrate(1000)
        .android.setChannelId('test-channel')
        .android.setPriority(firebase.notifications.Android.Priority.Max);
      await firebase.notifications().displayNotification(newNotification).catch((err) => {
        console.log('err---****', err);
      });
    });

This is my Function and i am Sending Notification by Sound enabled 

Please Help

**Comment by Ehesp** [comment]
Please follow the issue template.
