### ISSUE TITLE
undefined is not an object (evaluating 'FirebaseModule.googleApiAvailability')

### ISSUE THREAD

**Issue by linnett** [invertase/react-native-firebase#238]
I've tried re-installing this many times and keep getting the same error for iOS - `undefined is not an object (evaluating 'FirebaseModule.googleApiAvailability')`. 

I am following the steps for installation but something seems to be going wrong. Has anyone else encountered this issue for iOS? 

Full error from Xcode logs: 

`2017-07-10 13:28:30.946 [error][tid:com.facebook.React.JavaScript] undefined is not an object (evaluating 'FirebaseModule.googleApiAvailability')
2017-07-10 13:28:30.950 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'FirebaseModule.googleApiAvailability')`

I have uploaded an example of it not working to a repo here: https://github.com/linnett/test-firebase

Thanks

### Environment

1. Dev platform: iOS & Android (although this particular problem is iOS)
2. OS: MacOS Sierra
3. Xcode / `react native` cli
4. React Native version (e.g. 0.45.1): 0.45.1
5. RNFirebase Version (e.g. 2.0.2): 2.0.0

**Comment by chrisbianca** [comment]
@linnett you have not set up react-native-firebase in your Podfile.  This is why FirebaseModule is undefined.

**Comment by Ehesp** [comment]
http://invertase.io/react-native-firebase/#/installation-ios?id=_21-add-the-required-pods

**Comment by linnett** [comment]
🤦🏼‍♂️! My bad, apologies - thank you!!!

**Comment by hadirkhan499** [comment]
Hi, i am facing this issue on android, please help needed :/

**Comment by Ehesp** [comment]
@hadirkhan499 Follow the Android setup docs, iOS & Android are totally different.

**Comment by hadirkhan499** [comment]
I did follow the Android steps but getting the same error

**Comment by hadirkhan499** [comment]
@Ehesp

**Comment by Ehesp** [comment]
Please search the other issues (many people have created issues for this), and if you REALLY can't figure it out create a new one with as much information as possible.

**Comment by hadirkhan499** [comment]
Can you provide me the link for  this issue that other people created @Ehesp ? I cannot find it

**Comment by Ehesp** [comment]
Lol... https://github.com/invertase/react-native-firebase/issues?utf8=%E2%9C%93&q=is%3Aissue%20undefined%20is%20not%20an%20object

**Comment by smart-mickey** [comment]
hi chrisbianca, can you tell me how to set up react-native-firebase in the podfile? Thanks

**Comment by smart-mickey** [comment]
hi chrisbianca, can you tell me how to set up react-native-firebase in the podfile? Thanks
