### ISSUE TITLE
Left Hand Side bar missing from the documentation site for a week

### ISSUE THREAD

**Issue by amitbravo** [invertase/react-native-firebase#2385]
## Documentation Feedback
for last a week , left hand side bar is missing from the site, even with chrome, firefox too 
![Screenshot 2019-07-21 at 12 06 38 PM](https://user-images.githubusercontent.com/16644357/61587886-2aabb280-abb0-11e9-9fda-05353031141e.png)

**Comment by Ehesp** [comment]
Erm, I'm not seeing this at all. Can you make sure adblocker is not having any impact? We have had a few issues with that before.
