### ISSUE TITLE
Android X support in Firebase

### ISSUE THREAD

**Issue by tusharmutreja** [invertase/react-native-firebase#2387]
Hey Guys,

I have upgraded my app to android X. But react-native-firebase still giving the issue for android X.

Is there any updated version that contains the android X  support.

**Comment by akhavein** [comment]
Maybe you can use [Jetifire](https://github.com/mikehardy/jetifier) in the meantime.

**Comment by mikehardy** [comment]
Yes, jetifier is the current recommend forward- or backward- androidx/support library alignment situation. Actually, if you use react-native 0.60 they baked it into the CLI, so when you do "react-native run-android" it will run jetifier by default unless you disable it with a flag.

It should work with RN0.59+AndroidX too

**Comment by mikehardy** [comment]
#1588 is the main tracking issue
