### ISSUE TITLE
🔥 react-native-firebase local notifications not being displayed on iOS

### ISSUE THREAD

**Issue by 0x01Brain** [invertase/react-native-firebase#2389]
## Issue

In my app, I integrated react-native-firebase and I am using local notifications to notify the user once they get a new message or any new activity happening. However, the notifications are not being displayed on both real device and simulator. and both are running iOS 9.0+ (iOS 12).

Code  I am using: 

```
const notification = new firebase.notifications.Notification()
  .setNotificationId('1')
  .setTitle('My notification title')
  .setBody('My notification body')
  .setData({});

notification.ios.setBadge(2)

firebase.notifications().displayNotification(notification)
```

Note: Notifications is not being displayed on background mode and foreground mode. 

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase'
pod 'Firebase/Database', '~> 6.3.0'
pod 'Firebase/Auth', '~> 6.3.0'
pod 'Firebase/Messaging', '~> 6.3.0'

target 'ChattieEm' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for ChattieEm

  #target 'ChattieEm-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
  #end

  #pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'

  #pod 'react-native-udp', :path => '../node_modules/react-native-udp'

  target 'ChattieEmTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

#### `AppDelegate.m`:

```objc
/**

 * Copyright (c) Facebook, Inc. and its affiliates.

 *

 * This source code is licensed under the MIT license found in the

 * LICENSE file in the root directory of this source tree.

 */



#import "AppDelegate.h"



#import <React/RCTBridge.h>

#import <React/RCTBundleURLProvider.h>

#import <React/RCTRootView.h>

#import <Firebase.h>

#import "RNFirebaseNotifications.h"



@implementation AppDelegate



- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions

{

  [FIRApp configure];

  [RNFirebaseNotifications configure];

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge

                                                   moduleName:@"ChattieEm"

                                            initialProperties:nil];



  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];



  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];

  UIViewController *rootViewController = [UIViewController new];

  rootViewController.view = rootView;

  self.window.rootViewController = rootViewController;

  [self.window makeKeyAndVisible];

  return YES;

}



- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {

  [[RNFirebaseNotifications instance] didReceiveLocalNotification:notification];

}


- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge

{

#if DEBUG

  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

#else

  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];

#endif

}



@end


```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `5.5.4`
- **`react-native` version:**
 - `0.59`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by 0x01Brain** [comment]
Anyone?

**Comment by fabiowallner** [comment]
Have you found a solution yet? I have the same issue..

**Comment by rafalzawadzki** [comment]
Have the same problem, notifications not showing on iOS. They work fine on Android.
No callbacks are called. Permissions are granted, fcm token is there.

**Comment by MattyK14** [comment]
Is there any documentation now on local notifications? Using OP's snippet, it worked for me on iOS but not Android. Remote FCM notifications are working fine on both platforms.

**Comment by 0x01Brain** [comment]
@rafalzawadzki Yeah that was my problem, did not had permissions granted. Thanks.

**Comment by 0x01Brain** [comment]
@MattyK14 Perhaps you need to create a channel and give it an id. As it is stated here:

https://rnfirebase.io/docs/v5.x.x/notifications/android-channels

**Comment by MattyK14** [comment]
@0x01Brain unfortunately no such luck, but thank you!

**Comment by ghumman** [comment]
@0x01Brain  thanks, it worked for me too. @MattyK14 please make sure that notification.android.setChannelId('test-channel') is same as const channel = new firebase.notifications.Android.Channel('test-channel', .......
Following is example code. 


`
  componentDidMount() {
    // Build a channel
    const channel = new firebase.notifications.Android.Channel(
      'test-channel',
      'Test Channel',
      firebase.notifications.Android.Importance.Max,
    ).setDescription('My apps test channel');

    // Create the channel
    firebase.notifications().android.createChannel(channel);

    const notification = new firebase.notifications.Notification()
      .setNotificationId('notificationId')
      .setTitle('My notification title')
      .setBody('My notification body')
      .setData({
        key1: 'value1',
        key2: 'value2',
      });

    notification.android
      .setChannelId('test-channel')
      .android.setSmallIcon('ic_launcher');

    // Display the notification
    firebase.notifications().displayNotification(notification);
  }
`
