### ISSUE TITLE
RN 0.46.1  iOS build fails.

### ISSUE THREAD

**Issue by JJMoon** [invertase/react-native-firebase#239]
### Environment
1. Target Platform (e.g. iOS, Android): iOS
2. Development Operating System (e.g. macOS Sierra, Windows 10): Mac Sierra
3. Build tools : Xcode 8.3.3
4. React Native version (e.g. 0.45.1): 0.46.1
5. RNFirebase Version (e.g. 2.0.2):  2.0.2

I have so many issues on RN 0.46.1. But, I need this version for updated WebView.

When I add   pod 'Firebase/Core', it's OK.

But, after add  this line
pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
I got this error on terminal.  But, it runs on iOS simulator.
But, build failed on Xcode.

#import <React/RCTViewManager.h>
        ^
1 error generated.

How can I resolve this?

**Comment by Ehesp** [comment]
What's the error? It's generated one but you've not put it down.

**Comment by JJMoon** [comment]
The error says...

In file included from /Users/moon/Dev/rntest/reactFire/node_modules/react-native-firebase/ios/RNFirebase/admob/RNFirebaseAdMobNativeExpressManager.m:1:
/Users/moon/Dev/rntest/reactFire/node_modules/react-native-firebase/ios/RNFirebase/admob/RNFirebaseAdMobNativeExpressManager.h:1:9: fatal error: 'React/RCTViewManager.h' file not found
#import <React/RCTViewManager.h>
        ^

1 error generated.


** BUILD FAILED **


The following build commands failed:

	CompileC /Users/moon/Dev/rntest/reactFire/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/RNFirebase.build/Objects-normal/x86_64/RNFirebaseAdMobBannerManager.o /Users/moon/Dev/rntest/reactFire/node_modules/react-native-firebase/ios/RNFirebase/admob/RNFirebaseAdMobBannerManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/moon/Dev/rntest/reactFire/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/RNFirebase.build/Objects-normal/x86_64/RNFirebaseAdMobNativeExpressManager.o /Users/moon/Dev/rntest/reactFire/node_modules/react-native-firebase/ios/RNFirebase/admob/RNFirebaseAdMobNativeExpressManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

**Comment by Ehesp** [comment]
Could you show the contents of your Podfile.lock please

**Comment by JJMoon** [comment]
PODS:
  - Firebase/Core (4.0.3):
    - FirebaseAnalytics (= 4.0.2)
    - FirebaseCore (= 4.0.3)
  - FirebaseAnalytics (4.0.2):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseCore (4.0.3):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseInstanceID (2.0.0):
    - FirebaseCore (~> 4.0)
  - GoogleToolboxForMac/Defines (2.1.1)
  - GoogleToolboxForMac/NSData+zlib (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - JLRoutes (2.0.5)
  - RNFirebase (2.0.2)

DEPENDENCIES:
  - Firebase/Core
  - JLRoutes
  - RNFirebase (from `../node_modules/react-native-firebase`)

EXTERNAL SOURCES:
  RNFirebase:
    :path: ../node_modules/react-native-firebase

SPEC CHECKSUMS:
  Firebase: 9e33fdfbca37cab635c693883caa90a4475b842b
  FirebaseAnalytics: ad41720e3e67fc63fbe3d2948d3e26932a8de311
  FirebaseCore: c709067051de07bdaffdc4e735cd7299a23c463a
  FirebaseInstanceID: 9fbf536668f4d3f0880e7438456dabd1376e294b
  GoogleToolboxForMac: 8e329f1b599f2512c6b10676d45736bcc2cbbeb0
  JLRoutes: 2a5ee61d739b51a98c9d8112bee5149a19de8854
  RNFirebase: c77e3c228fef3dafb243db79394b797b9639ba30

PODFILE CHECKSUM: 6fecac838dbde8bbb511b78fc612d8267d3d0ec1

COCOAPODS: 1.1.1

**Comment by Ehesp** [comment]
Have you installed the React pod?

**Comment by JJMoon** [comment]
I didn't install React pod.

Podfile..

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactFire' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactFire
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'JLRoutes'
  #pod 'Firebase/Messaging'


  target 'reactFire-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reactFireTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by Ehesp** [comment]
Well it's not going to find `React/RCTViewManager.h` because there is no React pod. It either needs to be installed via the Pods or manually. Please see http://invertase.io/react-native-firebase/#/installation-ios?id=_21-add-the-required-pods for how to install it all correctly.
