### ISSUE TITLE
Dynamic Link Not Found

### ISSUE THREAD

**Issue by affanhashone** [invertase/react-native-firebase#2391]
![WhatsApp Image 2019-07-22 at 4 37 49 PM](https://user-images.githubusercontent.com/43112425/61636917-4cd02e00-ac9f-11e9-9462-139e3bef1a41.jpeg)

Dynamic Link Not Found Error ON IOS, Do anyBody Have any Idea ?

**Comment by Ehesp** [comment]
Please follow the issue template.
