### ISSUE TITLE
[v6][vision] Release ml-vision package in npm with android-only remark

### ISSUE THREAD

**Issue by kokeksibir** [invertase/react-native-firebase#2392]
ml-vision package seems to be working for android already, even if it is not ready for release, it might be useful to make it accessible for community somehow. Currently I need to install it from source repo.

**Comment by Ehesp** [comment]
We've got a batch of JS API changes which also need to be pushed so we're not really considering it even alpha stable yet. It's a large API surface area so we just want to make sure we're happy with the implementation before publishing.

Will let you know when that's been done 👍
