### ISSUE TITLE
Firestore in too slow

### ISSUE THREAD

**Issue by michaelspeed** [invertase/react-native-firebase#2398]
React native firestore has a very slow performance in some cases,
is this recurring or new to me

it sometimes does not even return results of root collection query

RN: 0.60.4
React native firebase: 5.3.0-rc3

**Comment by Ehesp** [comment]
Please provide more details.

What query? What data size? What data? What device?

**Comment by michaelspeed** [comment]
One query size is just 10, which fails if i make a simultaneously query with size 700.
i dont know if its from my end of the firestore

**Comment by michaelspeed** [comment]
![Screenshot at Jul 23 19-41-54](https://user-images.githubusercontent.com/1447958/61719215-1fa87c00-ad82-11e9-887d-54f536e12811.png)
![Screenshot at Jul 23 19-42-25](https://user-images.githubusercontent.com/1447958/61719220-246d3000-ad82-11e9-85c3-38380fde3d41.png)
![Screenshot at Jul 23 19-42-37](https://user-images.githubusercontent.com/1447958/61719227-2800b700-ad82-11e9-8888-9251ec6acd45.png)

**Comment by michaelspeed** [comment]
now its not even quering anything

**Comment by bosung90** [comment]
You should probably run it within an actual device or emulator running x86 architecture (not ARM)

**Comment by Ehesp** [comment]
Spin up a quick web instance and run the query on there. If it's quick there and doesn't throw any warnings let us know.

**Comment by michaelspeed** [comment]
ok will do, update it here

**Comment by Ehesp** [comment]
@michaelspeed if it helps, here's a gist: https://gist.github.com/Ehesp/46a68de3e2760dc2677fec837a285f74

Add in your modules via the Firebase CDN and your project web config and run some code.

**Comment by michaelspeed** [comment]
ok thanks, closing it now, untill i have an update
