### ISSUE TITLE
[v6] Instructions for Integrating into an Existing Project

### ISSUE THREAD

**Issue by Metroxe** [invertase/react-native-firebase#2399]
## Documentation Feedback

In the [Integrate Into Existing Project](https://invertase.io/oss/react-native-firebase/quick-start/existing-project) section of the quick start, there is '// TODO(@Salakar) React Native version requirements' and '// TODO(@Salakar): Manual or Automatic linking for Android & ios' under **'Before you begin'** and **'Guide'** respectively.

When are these going to be completed or is there anywhere a guide can be found?

![image](https://user-images.githubusercontent.com/19210023/61737155-8145f780-ad3c-11e9-95d5-ecf49e5a3f42.png)

**Comment by Ehesp** [comment]
Will be working on them in the next couple of weeks, sorry about the delay.
