### ISSUE TITLE
Login with Facebook Not Working

### ISSUE THREAD

**Issue by AndrewHenderson** [invertase/react-native-firebase#24]
This conversation has moved from [React Native Firestack issue #121](https://github.com/fullstackreact/react-native-firestack/issues/121#issuecomment-289525106)

version: 1.0.0-alpha9

@Salakar The following enters neither the `then` or `catch` callbacks:
```js
const credential = firebase.auth().FacebookAuthProvider.credential(data.accessToken);
// firebase.auth().FacebookAuthProvider will soon be moved to 
// firebase.auth.FacebookAuthProvider to match the firebase web sdk
firebase.auth().signInWithCredential(credential)
  .then(currentUser => {
  // now signed in
   console.warn(JSON.stringify(currentUser.toJSON()));
  })
  .catch(error => console.error(error));
```

**Comment by Salakar** [comment]
@AndrewHenderson what are you using to get the accessToken for facebook?

**Comment by AndrewHenderson** [comment]
@Salakar The React Native Facebook SDK:

```js
import {
  AccessToken
} from 'react-native-fbsdk';
const data = AccessToken.getCurrentAccessToken();
const credential = firebase.auth().FacebookAuthProvider.credential(data.accessToken); // token present on object

…
```

**Comment by AndrewHenderson** [comment]
@Salakar In my app [`promise`](https://github.com/invertase/react-native-firebase/blob/86512320f0694f847cac5e91c84cf4b7b7bcd3cb/lib/modules/auth/index.js#L67) never resolves:

```js
_interceptUserValue(promise) {
  return promise.then((result) => {
    if (!result) return this._onAuthStateChanged(null, false);
    if (result.user) return this._onAuthStateChanged(result, false);
    if (result.uid) return this._onAuthStateChanged({ authenticated: true, user: result }, false);
    return result;
  });
}
```

**Comment by AndrewHenderson** [comment]
@Salakar ios.

**Comment by AndrewHenderson** [comment]
@Salakar I can screenshare if that would help.

**Comment by Salakar** [comment]
The example of your fbsdk code doesn't include you logging, i assume you're doing a button as per https://github.com/facebook/react-native-fbsdk/blob/master/README.md#login-button--access-token  and then in the handler calling getCurrentAccessToken?

**Comment by Salakar** [comment]
On my way home at the moment so can debug when i get home

**Comment by AndrewHenderson** [comment]
> The example of your fbsdk code doesn't include you logging, i assume you're doing a button as per https://github.com/facebook/react-native-fbsdk/blob/master/README.md#login-button--access-token and then in the handler calling getCurrentAccessToken?

That's correct. The access token is accessible and being passed to `firebase.auth().FacebookAuthProvider.credential`

In the library code, `FirebaseAuth.signInWithCredential(credential.provider, credential.token, credential.secret)` all three arguments are being provided.

**Comment by Salakar** [comment]
Ok, can you try adding the `public_profile` and the `email` scopes to the login button perhaps?

**Comment by Salakar** [comment]
Also, do you know how to use the xcode deugger? If so can you line break on https://github.com/invertase/react-native-firebase/blob/master/ios/RNFirebase/RNFirebaseAuth.m#L310 and tell me / print screen what the value of credential is?

If you don't then i can look at this over screen share, in a few mins.

**Comment by Salakar** [comment]
![image](https://cloud.githubusercontent.com/assets/5347038/24373789/71f8d346-132a-11e7-91a7-cf1217314a96.png)

^--- is where you can find the file.

**Comment by AndrewHenderson** [comment]
I'm essentially taking [this approach](https://github.com/facebook/react-native-fbsdk#login-button--access-token). I'm not sure how to add scopes to the button.

```js
const FBSDK = require('react-native-fbsdk');
const {
  LoginButton,
  AccessToken
} = FBSDK;

var Login = React.createClass({
  render: function() {
    return (
      <View>
        <LoginButton
          onLoginFinished={
            (error, result) => {
              if (error) {
                alert("login has error: " + result.error);
              } else if (result.isCancelled) {
                alert("login is cancelled.");
              } else {
                AccessToken.getCurrentAccessToken().then(
                  (data) => {
                    alert(data.accessToken.toString())
                  }
                )
              }
            }
          }
          onLogoutFinished={() => alert("logout.")}/>
      </View>
    );
  }
});
```

**Comment by Salakar** [comment]
https://github.com/facebook/react-native-fbsdk/blob/master/js/FBLoginButton.js#L56

Add that as an array prop to your <LoginButton> component, and add the two scopes as above

**Comment by AndrewHenderson** [comment]
> Also, do you know how to use the xcode deugger

I thought so. I set a breakpoint in Xcode but it's not hitting. My folder structure looks different. I have the project in Libraries:

<img width="1251" alt="screen shot 2017-03-27 at 12 21 52 pm" src="https://cloud.githubusercontent.com/assets/1031565/24373943/05c28a2e-12e8-11e7-89c6-882a1a3876c4.png">

**Comment by Salakar** [comment]
Does it even get into that function? If it does try break here: https://github.com/invertase/react-native-firebase/blob/master/ios/RNFirebase/RNFirebaseAuth.m#L450 . does it get there?

**Comment by AndrewHenderson** [comment]
OK after adding `readPermissions` array, I hit the breakpoint in Xcode.

Is this what you're referring to `<FIRFacebookAuthCredential: 0x60800042f4a0>`?

**Comment by Salakar** [comment]
OK, try without the breakpoints now, leave the readPermission array in there. Seems like its working now?

**Comment by AndrewHenderson** [comment]
It's not because neither of these breakpoints ever hit:

<img width="950" alt="screen shot 2017-03-27 at 12 30 46 pm" src="https://cloud.githubusercontent.com/assets/1031565/24374330/45d0ae24-12e9-11e7-9d4d-5b8b7bcd421f.png">

**Comment by Salakar** [comment]
Ah, is it hitting the reject in the if statement above?

**Comment by AndrewHenderson** [comment]
No, it's not nil, so it makes it into the if statement inside:

`[[FIRAuth auth] signInWithCredential:credential completion:^(FIRUser *user, NSError *error) {`

**Comment by AndrewHenderson** [comment]
Does this look right?

<img width="991" alt="screen shot 2017-03-27 at 12 44 15 pm" src="https://cloud.githubusercontent.com/assets/1031565/24374878/4821fe1a-12eb-11e7-8fa6-f2ace85eafae.png">

**Comment by Salakar** [comment]
![image](https://cloud.githubusercontent.com/assets/5347038/24375958/2325a304-1332-11e7-809f-adeaf9edf5b7.png)

The code is correct, can you try re-start your emulator, might be an emulator network issue, should deffo get into that callback =/

**Comment by AndrewHenderson** [comment]
I'm getting the same issue with creating a user via email. This breakpoint never hits.

<img width="981" alt="screen shot 2017-03-27 at 1 18 54 pm" src="https://cloud.githubusercontent.com/assets/1031565/24376295/3a6e1100-12f0-11e7-8ceb-008608f95c39.png">


Something must be wrong with my install then.

**Comment by AndrewHenderson** [comment]
Should RNFirebase be in my Pods directory? Does it matter that it's in my Libraries directory?

**Comment by Salakar** [comment]
Ye its your simulator, network issues, stop it and reboot the emulator, the email sign in tests are all passing on ios and android emulator here: 

![moo](https://cloud.githubusercontent.com/assets/5347038/23989816/d80e0690-0a2b-11e7-9b95-8bc2ed323e9b.png)

**Comment by Salakar** [comment]
Your emulator would be redboxing if it wasn't required properly

**Comment by AndrewHenderson** [comment]
@Salakar by emulator do you mean simulator? I've restarted Xcode and iOS simulator. I've closed and rebooted the React Packager to no avail.

**Comment by AndrewHenderson** [comment]
Maybe it has something to do with my Pods. This is my PodFile:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyApp' do
  use_frameworks!
  pod 'GooglePlacePicker', '= 2.0.1'
  pod 'GooglePlaces', '= 2.0.1'
  pod 'GoogleMaps', '= 2.0.1'

  # Pods for MyApp

end
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

[
  'Firebase',
  'Firebase/Core',
  'Firebase/Auth',
  'Firebase/Storage',
  'Firebase/Database',
  'Firebase/RemoteConfig',
  'Firebase/Messaging',
  'Firebase/Analytics',
].each do |lib|
  pod lib
end
```

**Comment by Salakar** [comment]
@chrisbianca can you see anything wrong here? I'm stumped, seems like all the auth methods on firebase are hanging and not getting into the ios completion callbacks?

**Comment by designorant** [comment]
@AndrewHenderson This is just a guess but I've noticed you still have Firestack in your libraries so maybe there are some leftovers that cause this behaviour? It's unlikely the reason but I've seen some XCode voodoo in the past.

**Comment by AndrewHenderson** [comment]
@Salakar Screenshare? I'd eager to get this resolved. I'd like to migrate to this library from Firestack.

**Comment by AndrewHenderson** [comment]
@designorant I'll take a look.

**Comment by Salakar** [comment]
@AndrewHenderson do you have screen hero?

**Comment by AndrewHenderson** [comment]
@Salakar @designorant

I removed any reference to Firestack from my codebase. I'm getting the following error in Xcode console:
```
<Error> [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
```

I did execute `new RNFirebase(configOptions)` in my JavaScript. Is there something else I have to do in Xcode files?

**Comment by designorant** [comment]
@AndrewHenderson https://github.com/invertase/react-native-firebase/issues/10#issuecomment-287577002 ?

**Comment by Salakar** [comment]
Was added to the docs too: https://github.com/invertase/react-native-firebase/blob/master/docs/installation.ios.md . at the bottom, if it helps

**Comment by AndrewHenderson** [comment]
@Salakar 

Followed instructions at that link and ran pod install.

This is what my podfile looks like now:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'socadv' do
  use_frameworks!
  pod 'GooglePlacePicker', '= 2.0.1'
  pod 'GooglePlaces', '= 2.0.1'
  pod 'GoogleMaps', '= 2.0.1'

  # Pods for socadv

end
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

# Required by RNFirebase
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/AppIndexing'
pod 'Firebase/Core'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
```

This was the output:

<img width="692" alt="screen shot 2017-03-27 at 2 13 06 pm" src="https://cloud.githubusercontent.com/assets/1031565/24378382/994169e6-12f7-11e7-950a-8bc741b53e12.png">

The build now fails and I get the following error in Xcode:

<img width="1014" alt="screen shot 2017-03-27 at 2 14 00 pm" src="https://cloud.githubusercontent.com/assets/1031565/24378412/ae8cfda6-12f7-11e7-852d-39fa8d4f7cb2.png">

**Comment by AndrewHenderson** [comment]
Should these header search paths be recursive?

<img width="849" alt="screen shot 2017-03-27 at 2 20 14 pm" src="https://cloud.githubusercontent.com/assets/1031565/24378652/8e8dbdb4-12f8-11e7-92c7-9e21905c8df6.png">

**Comment by Salakar** [comment]
Someone mentioned on gitter a while back there was an issue with the rnpm link and header paths:

![image](https://cloud.githubusercontent.com/assets/5347038/24378892/85c89b56-133c-11e7-8101-1205ee8f3731.png)

If thats of any help?

**Comment by Salakar** [comment]
it was @designorant as above, what did you do to fix it?

**Comment by AndrewHenderson** [comment]
I removed `pod 'RNFirebase', :path => '../node_modules/react-native-firebase'`

Which resulted in React not being installed as a Pod. I think that was causing a recursion issue with the frameworks.

The project now builds and it appears as though I'm authenticated through Firebase.

I'll report back once I get my JS back to a stable state.

**Comment by Salakar** [comment]
I think @chrisbianca installed via the pod and updated docs accordingly as he had no issues there, maybe the docs need a revisit then / these kind of things adding.

Getting it all installed was the hardest part though :) the rest should be a breeze from now on

**Comment by AndrewHenderson** [comment]
@Salakar Thanks for your help!

**Comment by Salakar** [comment]
@AndrewHenderson sorry I couldn't of been more help, i'm just the code monkey that churns out the code here, I get the code, it's the fiddly setup that i'm not 100% familiar with, deffo needs ironing out.

https://github.com/invertase/react-native-firebase-tests
https://github.com/invertase/react-native-firebase-examples

There's two apps in the org also if you want to check out some of the usage, the tests one has a lot of all the various firebase features being used in tests and the examples app is real-world scenarios etc.

**Comment by designorant** [comment]
In terms of header paths the issue I had was that RNPM was joining the string paths instead of putting them into arrays which in turn caused XCode to moan (compare top and bottom examples on [that screenshot](https://github.com/invertase/react-native-firebase/issues/24#issuecomment-289591636) to see the issue). I fixed the messed up lines manually, in a text editor.

In terms of the recent iOS installation changes, [I've just left a comment on the commit](https://github.com/invertase/react-native-firebase/commit/f300149d2f67a384c62924a35461dd85d2a68070#commitcomment-21509552) as I've just found out I can't get my RN project to start with the recent Podfile changes. Getting rid of `  pod 'RNFirebase'` makes everything fine but I've had previous RNFirebase linked the 'old' way.

I don't think it's the same issue as @AndrewHenderson's but leaving this here for any [wanderers out there](https://xkcd.com/979/).

**Comment by chrisbianca** [comment]
Just as a follow up, I've updated the docs to give setup options based on how your project is currently setup.  If you're already using a Podfile with React Native installed as a pod then adding RNFirebase as a pod is by far the simplest way to go.  Otherwise, you can use react-native link or a manual set up, depending on what you'd prefer.
