### ISSUE TITLE
'React/RCTEventEmmiter.h not found, React/RCTComponent.h not found, React/RCTBridgeModule.h. 

### ISSUE THREAD

**Issue by boplennon** [invertase/react-native-firebase#240]
I tried to install react-native-firebase by CocoaPod way. But when i run react-native run-ios i got a fail build relate to 'React/RCTEventEmmiter.h not found, React/RCTComponent.h not found, React/RCTBridgeModule.h. 
Here is my Podfile
`
platform :ios, '9.0'

target 'NativeStarterKit' do
  use_frameworks!

  react_native_path = "../node_modules/react-native"
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

pod 'Firebase', '~> 4.0.0'
pod 'Firebase/Core', '~> 4.0.0'
pod 'Firebase/Storage', '~> 4.0.0'
pod 'Firebase/Database', '~> 4.0.0'
pod 'Firebase/Crash', '~> 4.0.0'
pod 'Firebase/Messaging', '~> 4.0.0'

pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
end`

### Environment

1. Target Platform (e.g. iOS, Android): iOS
2. Development Operating System  macOS Sierra
3. Build tools Xcode 8.3.3
4. React Native version: 0.46.1
5. RNFirebase Version : 2.0.2

**Comment by eduardoleal** [comment]
Are you using Expo?
Checkout this: https://docs.expo.io/versions/v18.0.0/guides/expokit.html#ios
It seems that you need to fix the paths to React in your dependency build settings since you are using cocoapods.

**Comment by boplennon** [comment]
Thanks for your help!
Though Im not using expo but the link you provided give me some insight! I comment out "use_frameworks!" and re-run, now Its build successfully.
