### ISSUE TITLE
firestore : We ran "xcodebuild" command but it exited with error code 65

### ISSUE THREAD

**Issue by creative-git** [invertase/react-native-firebase#2400]
after i installed firestore via Pod , i start getting the following error when i run `react-native run-ios` 

`error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening myApp.xcworkspace
`
the project builds successfully via Xcode 

## Project Files

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'myApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myApp
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/Firestore', '~> 6.3.0'
end

```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [x] **iOS** but have not tested behavior on Android
- **`react-native-firebase`: 5.5.5**
- **`Firebase` module(s) you're using that has the issue: firestone`**
  
</p>
</details>

i tried running :
`yarn add https://github.com/invertase/react-native-google-signin.git#v0.12.1` . didnt work

**Comment by creative-git** [comment]
solved by running:
`npm install --save https://github.com/invertase/react-native-google-signin.git#v0.12.1`

**Comment by eugenegodun** [comment]
@creative-git Have you fixed this issue?
