### ISSUE TITLE
storageRef.listAll() function does not exists

### ISSUE THREAD

**Issue by muhammadwfa** [invertase/react-native-firebase#2402]
listing files does not work.

https://firebase.google.com/docs/storage/web/list-files

**Comment by Ehesp** [comment]
This feature will be added once v6 is live. Please add it to our feature board on Canny.

**Comment by Ehesp** [comment]
https://github.com/invertase/react-native-firebase/pull/2424

**Comment by anastely** [comment]
Hey @Ehesp, I'm trying to get download URL from the list of items but I got this error 

>  itemRef.getDownloadUrl is not a function

although in [docs](https://rnfirebase.io/reference/storage/listresult#items
) says 

>  You can call getMetadate() and getDownloadUrl() on them.

So what's the wrong here

here's my code
  ```
  const refList = storage().ref('/categories/Air/');
    const listAll = await refList.listAll();
    listAll.items.forEach(async itemRef => {
      let url = await itemRef.getDownloadUrl();
      console.log('itemRefURL', url); // itemRef.getDownloadUrl is not a function
    });
```
