### ISSUE TITLE
Local push is not passed to `getInitialNotification()` when app is closed

### ISSUE THREAD

**Issue by Simek** [invertase/react-native-firebase#2405]
## Issue

Scan QR code assigned to your app (via DynamicLinks) using default iOS Camera app. Press on push to open app, earlier after launch `getInitialNotification()` was populated with push data, but now content is empty.

It feels like regression - before updating RN to `0.60.4` (from `0.59.6`) and RNFB to `5.5.5` (from `5.4.2`) this feature works as intended. 

Same local push generated by Camera when app is in background works properly (different handler).  

Remote pushes works correctly in any state, even when app is closed. 

## Environment
**`react-native info` output:**

```
System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1703.83 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2/10E125 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4
```

- **Platform that you're experiencing the issue on**:
  - [X] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both

**Comment by Simek** [comment]
@Salakar ?

**Comment by lovekothari123** [comment]
Same problem from my side.
i am also not getting any response(payload) while application. In background/killed state
i am using this :-

import firebase from "react-native-firebase";
import {
Notification,
NotificationOpen,
RemoteMessage,
Firebase
} from "react-native-firebase";
firebase
.notifications()
.getInitialNotification()
.then((notificationOpen: NotificationOpen) => {
if (notificationOpen) {
alert("get data testing done")
}
});

also i am trying that 👎 but did't get any solution

firebase.messaging().onMessage((message: RemoteMessage) => {
// Process your message as required
console.log("Notification open App closed in open " + message);
});

If is there any one who can resolved this issues please update.

**Comment by mikehardy** [comment]
oh my god man, you pasted that into 8 places.

**Comment by lovekothari123** [comment]
Yes @mikehardy   because i am spending 1 week for resolving this issues most of peoples suggest there is an issues in iOS and android (native code ). 
so @mikehardy  is there any issues in Android/iOS(native codes) ? 
Now,
when my application is in background/killed state how can i received any payload ?
as per react-native-firebase documentation they will provide this function :- 
https://rnfirebase.io/docs/v4.2.x/notifications/receiving-notifications#4)-Listen-for-a-Notification-being-opened

App Closed 👎  then use this 
const notificationOpen: NotificationOpen = await firebase.notifications().getInitialNotification();
    if (notificationOpen) {
        // App was opened by a notification
        // Get the action triggered by the notification being opened
        const action = notificationOpen.action;
        // Get information about the notification that was opened
        const notification: Notification = notificationOpen.notification;
    }

but it's not working i did't get any call back while using this function. 
thank-you 👍

**Comment by mikehardy** [comment]
@lovekothari123 open a new issue, follow the template

**Comment by Simek** [comment]
After updating RN and RNFB to latest version problem disappeared.
