### ISSUE TITLE
Unable to set image on notification when the app is in background

### ISSUE THREAD

**Issue by Sandipnag** [invertase/react-native-firebase#2407]
### setBigPicture is not working when the app is in back ground.

Describe your issue here

I am trying to set an Image in notification when the app is in background or killed. It is ok when the app is in foreground.
---

## Code(bgMessaging.js)

<p>

### `import firebase from 'react-native-firebase';
export default async message => {
    const channel = new firebase.notifications.Android.Channel(
        'fcm_default_channel_bkgrnd',
        'SAT VS ACT 11',
        firebase.notifications.Android.Importance.Max
      ).setDescription('A natural description of the channel');
    firebase.notifications().android.createChannel(channel);
    const notification = new firebase.notifications.Notification();
    notification.android
      .setChannelId("fcm_default_channel_bkgrnd")
      .setNotificationId('IWA-788-YHH-087')
      .setSound('default')
      .setTitle('From Background')
      .setBody('I am the body');
    notification.android.setBigPicture('https://picsum.photos/200/300');
    firebase.notifications().displayNotification(notification);
    return Promise.resolve();
  };`

</p>
</details>

I am sending this data:-

**{
    "to":
"ekh5OmQgkmo:APA91bFZlGZwkZMJFqbAphNI6Vi5cQ7x2PKAK5QSbFSkKhfz4lWNpE0lf8W6H-M4Ae6HIzLOSyzpySeRqd8CLE-7D1a-0OTvZPH6-vn6YmTq0t-WcsYZu-zQp3-9AnO_Vsdnmg8pIBgi",
"notification":
    {
        "title":"Working Good","body":"Exam ongoing",
        "data":
        {
            "image": "https://picsum.photos/200/300"
        }
    },
"priority":"high"
}
---**

**Comment by tinpt123** [comment]
same issue ?
