### ISSUE TITLE
listRef.listAll() function is undefined (react-native-firebase)

### ISSUE THREAD

**Issue by muhammadwfa** [invertase/react-native-firebase#2408]
I am trying to get the list of images in a directory from firebase storage.

Example I want to get all image in users/userid/images, but it does not work and popup an error which the function is undefined.

```
const listRef = storageRef.child('users/userid/images');
listRef.listAll().then(res=>{
  res.items.forEach(itemRef=>{
    // console.log(itemRef);
  });
}).catch(e =>{});
```

react-native-firebase v 5.5.3

**Comment by kajiru** [comment]
Having the same issue.

**Comment by Ehesp** [comment]
https://github.com/invertase/react-native-firebase/issues/2402

**Comment by Ehesp** [comment]
https://github.com/invertase/react-native-firebase/pull/2424
