### ISSUE TITLE
Can't show notification on real device

### ISSUE THREAD

**Issue by Shinichi52** [invertase/react-native-firebase#241]
Hi,
I tried test display notification. 
In Simulator: it's work fine
In Real device: it's not work

can you help me resolve issue
Thanks!

### Environment

1. Target Platform (e.g. iOS, Android): IOS
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): IOs 10.3
4. React Native version (e.g. 0.45.1): 44.1
5. RNFirebase Version (e.g. 2.0.2): 1.1.2

**Comment by chrisbianca** [comment]
What type of notification are you trying to send?  
Remote or local?
Background or foreground?

**Comment by Shinichi52** [comment]
i send message with fcm token from firebase cloud message. on android device it's work fine. But in IOS it's not work. I trigger on onMessage function.

 firebase.messaging().onMessage((message) => {
            console.log('message: ', message);
            Alert.alert('Test Notify', JSON.stringify(message));
        });

My File AppDelegate.h
#import <UIKit/UIKit.h>
@import UserNotifications;

@interface AppDelegate : UIResponder <UIApplicationDelegate,UNUserNotificationCenterDelegate>

@property (nonatomic, strong) UIWindow *window;

@end


My File AppDelegate.m

#import "AppDelegate.h"
#import <CodePush/CodePush.h>
#import "RCCManager.h"
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "ReactNativeConfig.h"
#import <Firebase.h>
#import "RNFirebaseMessaging.h"
#import "SplashScreen.h"  // here


@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
  

  NSURL *jsCodeLocation;

  // rn-config
  NSDictionary *config = [ReactNativeConfig env];

  #ifdef DEBUG
    
#ifdef DEBUG
    jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
#else
    jsCodeLocation = [CodePush bundleURL];
#endif
  #else
  	jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
  #endif
  
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  self.window.backgroundColor = [UIColor whiteColor];
  [[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation];

  [SplashScreen show];  // here
  return YES;
}
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler
{
  [RNFirebaseMessaging willPresentNotification:notification withCompletionHandler:completionHandler];
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)())completionHandler
{
  [RNFirebaseMessaging didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}

-(void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [RNFirebaseMessaging didReceiveLocalNotification:notification];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [RNFirebaseMessaging didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

@end

**Comment by Shinichi52** [comment]
ANd I tried upgrade to "react-native-firebase": "^2.0.2" And Firebase Pod to 4.0.3. But I built it, It's showed error: React/RCTComponent.h not found

**Comment by Ehesp** [comment]
@Shinichi52 please format your code above. Can we also see your Podfile.

**Comment by Shinichi52** [comment]
My Podfile:
`target 'equix' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for 'movieapp'
  pod 'SwiftyJSON', '3.1.4'
	pod 'Charts', '3.0.1'
end

# RNFirebase
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/AppIndexing'
pod 'Firebase/Core'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'

use_frameworks!

	
post_install do |installer|
	installer.pods_project.targets.each do |target|
	  target.build_configurations.each do |config|
	    config.build_settings['SWIFT_VERSION'] = '3.0'
	  end
	end
end`

**Comment by Shinichi52** [comment]
sorry. I re-format my code.

**Comment by chrisbianca** [comment]
@Shinichi52 Try commenting out the `use_frameworks!` line of the Podfile

**Comment by Shinichi52** [comment]
version 1.1.2: i tried comment ```use_frameworks!``` but not work

**Comment by chrisbianca** [comment]
Comment out `use_frameworks!` on v2.0.2 and that should fix your compilation problems.  It's better to try and get 2.0.2 working than 1.1.2 as there are some messaging fixes in 2.0.2

**Comment by Shinichi52** [comment]
i'm using Chart. When Comment ```use_frameworks!``` has error 
```Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pods being used are: Chart s and SwiftyJSON```

how to resolve my issue

**Comment by SamMatthewsIsACommonName** [comment]
@Shinichi52 this may be a very stupid suggestion but have you tried making sure the message has some sort of data attribute? Mine wouldn't show without that

**Comment by Shinichi52** [comment]
@SamMatthewsIsACommonName i resolved my issue. Thanks for supported :)
