### ISSUE TITLE
RNFirebase v.5.5.5 not working on Android with react-native 0.60?

### ISSUE THREAD

**Issue by chetan-zalake** [invertase/react-native-firebase#2413]
I create a project with react-native version 0.60. I am trying to link the RNFirebase v.5.5.5 to Android. It works well in iOS but throws an error in Android. Please let me if anyone has resolved this issue. If Yes, how?
I even migrated my project to Android X support.

ERROR:
Task :react-native-firebase:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.

Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
56 actionable tasks: 9 executed, 47 up-to-date

**Comment by mikehardy** [comment]
template is vital, you didn't follow it

**Comment by ashwingattani** [comment]
@chetan-zalake did you find any solution to this?

**Comment by mikehardy** [comment]
@ashwingattani was a completely unspecified problem, so there's no solution directly to it. However v5.5.x works just fine from react-native 0.59.3 up through 0.61.3 (that is, current) https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh - you can use that script to quickly build a little test and verify it
