### ISSUE TITLE
RN 0.60 Android error: native module RNFirebase tried to override RNFirebaseModule

### ISSUE THREAD

**Issue by luisfuertes** [invertase/react-native-firebase#2417]
New rn version crash with react-native-firebase on Android

Versions
```
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-firebase": "^5.5.5",
```

MainApplication.java with new `getPackages()` function
```
    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      packages.add(new RNFirebasePackage());
      packages.add(new RNFirebaseDatabasePackage());
      packages.add(new RNFirebaseAuthPackage());
      return packages;
    }
```

Error:
![Screenshot_2019-07-27-14-51-49-694_com smok_app](https://user-images.githubusercontent.com/18212615/61994717-719d1a80-b07e-11e9-9fce-34dd957cc3d2.png)

**Comment by fungilation** [comment]
Overlap with 0.60 autolink. Remove from MainApplication.java like it says. But eventually you will likely hit the redbox I'm getting: https://github.com/invertase/react-native-firebase/issues/2411

**Comment by Mavenic** [comment]
protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      packages.add(new RNFirebasePackage()); //=> remove this line and also from header import
      packages.add(new RNFirebaseDatabasePackage());
      packages.add(new RNFirebaseAuthPackage());
      return packages;
    }

**Comment by mikehardy** [comment]
This is unrelated to react-native-firebase, I have a demo that shows how to successfully build and run RN60 - you can see how it does what it does, or just use it for boilerplate https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by TrekSoft** [comment]
Can the documentation be updated to reflect this? It still shows the old way where the package is included and the old way of including module packages as well.

**Comment by mikehardy** [comment]
@TrekSoft it certainly can be! There's an edit button at the top of each documentation page, please make a PR 🙏

**Comment by TrekSoft** [comment]
Ok awesome - let me verify my code works and I'll do that.

**Comment by TrekSoft** [comment]
Here it is for auth and if this looks good, will submit another one for all the other modules: https://github.com/invertase/react-native-firebase-docs/pull/208

**Comment by hopewise** [comment]
I still have the same issue, I've noticed that `android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java` has `new RNFirebasePackage()` twice in there.. but why??

**Comment by huyhomie66** [comment]
> ```
> protected List<ReactPackage> getPackages() {
>       @SuppressWarnings("UnnecessaryLocalVariable")
>       List<ReactPackage> packages = new PackageList(this).getPackages();
>       // Packages that cannot be autolinked yet can be added manually here, for example:
>       // packages.add(new MyReactNativePackage());
>       packages.add(new RNFirebasePackage()); //=> remove this line and also from header import
>       packages.add(new RNFirebaseDatabasePackage());
>       packages.add(new RNFirebaseAuthPackage());
>       return packages;
> }
> ```

thanks god for born you

**Comment by edilsonlsouza** [comment]
Thank-you!

**Comment by pruteanualex** [comment]
> ```
> protected List<ReactPackage> getPackages() {
>       @SuppressWarnings("UnnecessaryLocalVariable")
>       List<ReactPackage> packages = new PackageList(this).getPackages();
>       // Packages that cannot be autolinked yet can be added manually here, for example:
>       // packages.add(new MyReactNativePackage());
>       packages.add(new RNFirebasePackage()); //=> remove this line and also from header import
>       packages.add(new RNFirebaseDatabasePackage());
>       packages.add(new RNFirebaseAuthPackage());
>       return packages;
> }
> ```

dud if i remove that line of code my application it breaks
