### ISSUE TITLE
Multiple Build failure on firebase on react-native 0.60.4 version

### ISSUE THREAD

**Issue by ashokadichill** [invertase/react-native-firebase#2418]
## Issue

Have been integrating firebase to react-native latest version once firebase linked in to the Android it shows many errors  from diffrent sub packages like messaging, notifications, analaytics

ReactNativeFirebaseAppRegistrar.java
error: package android.support.annotation does not exist

RNFirebaseStoragePackage.java
error: package android.support.annotation does not exist

RNFirebaseMessagingService.java
error: cannot find symbol class LocalBroadcastManager
error: cannot find symbol variable LocalBroadcastManager
error: cannot find symbol variable LocalBroadcastManager

RNFirebaseNotificationManager.java
error: package android.support.annotation does not exist
error: cannot find symbol class RequiresApi
error: cannot find symbol class RequiresApi
error: cannot find symbol class RequiresApi

RNFirebaseAnalyticsPackage.java
error: package android.support.annotation does not exist

RNFirebaseMessaging.java
error: cannot find symbol variable LocalBroadcastManager

RNFirebaseNotifications.java
error: cannot find symbol variable LocalBroadcastManager

**Have been tried migrate to androidX by refactor-Migrate to AndroidX**

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application? Yes
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility? Yes
- [ ] I am using the NPM package `jetifier` for react-native compatibility? No

#### `android/app/build.gradle`:

```

apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

def jscFlavor = 'org.webkit:android-jsc:+'

def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.exampleapp"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }

    packagingOptions {
        pickFirst '**/armeabi-v7a/libc++_shared.so'
        pickFirst '**/x86/libc++_shared.so'
        pickFirst '**/arm64-v8a/libc++_shared.so'
        pickFirst '**/x86_64/libc++_shared.so'
        pickFirst '**/x86/libjsc.so'
        pickFirst '**/armeabi-v7a/libjsc.so'
    }
}

dependencies {
    implementation project(':react-native-firebase')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-splash-screen')
    implementation project(':react-native-code-push')
    implementation project(':react-native-gesture-handler')
    implementation fileTree(dir: "libs", include: ["*.jar"])

    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "com.google.firebase:firebase-core:16.0.9"

    if (enableHermes) {
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
      implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}


apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply plugin: 'com.google.gms.google-services'
```

#### `android/build.gradle`:

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "11.8.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.1")
        classpath 'com.google.gms:google-services:4.0.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
    }
}

```

#### `android/settings.gradle`:

```
rootProject.name = 'exampleapp'
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
include ':react-native-linear-gradient'
project(':react-native-linear-gradient').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-linear-gradient/android')
include ':react-native-gesture-handler'
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gesture-handler/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':react-native-splash-screen'
project(':react-native-splash-screen').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-splash-screen/android')
include ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')
include ':app'

```

#### `MainApplication.java`:

```
package com.exampleapp;

import android.app.Application;
import android.util.Log;

import com.facebook.hermes.reactexecutor.HermesExecutorFactory;
import com.facebook.react.PackageList;
import com.facebook.react.bridge.JavaScriptExecutorFactory;
import com.facebook.react.ReactApplication;
import io.invertase.firebase.RNFirebasePackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import com.microsoft.codepush.react.CodePush;
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;

import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected String getJSBundleFile(){
      return CodePush.getJSBundleFile();
    }

    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

```

#### `AndroidManifest.xml`:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.exampleapp">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustPan">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```

System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 19.61 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.0, 27.0.3, 28.0.2, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-code-push: 5.4.2
```

- **Platform that you're experiencing the issue on**:
  - [ ] Android
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.5.5`
- **`Firebase` module(s) you're using that has the issue:**
  - `storage`
- `messaging`
 - `analytics`
- `notifications`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

**Comment by mikehardy** [comment]
This is not a react-native-firebase problem. You've migrated to AndroidX incorrectly. There are a million ways to do it wrong so trying to troubleshoot it is inefficient.

Here's one way to do it right https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by mikehardy** [comment]
This is not related to react-native-firebase, the demo successfully builds with RN60

**Comment by selvadrew** [comment]
im starting a new project with RN60. What version of RNFB do you recommend?

**Comment by mikehardy** [comment]
@selvadrew not just RNFB v5.x.x, but unreleased tip of the branch so you get the [AdMob fix there](https://github.com/invertase/react-native-firebase/commits/v5.x.x) that will go out in v5.5.6.

And make sure to use current Firebase SDKs (that's iOS pods 6.5.0 as of today but they move every week or two)

**Comment by kdastan** [comment]
@ashokadichill did you find solution?

**Comment by ashokadichill** [comment]
@kdastan Still not..

**Comment by MssMaster** [comment]
Any solution for above? 
Facing the same issue.
versions i am using :
` "react-native": "0.60.4",
    "react-native-firebase": "^5.5.6",`

Please let me know the compatible version so that I can use this plugin

**Comment by mikehardy** [comment]
everything's working fine here as far as I can tell and I demonstrate it here https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh. This is not an open issue from my perspective

**Comment by kdastan** [comment]
Hey @ashokadichill, I have some solution for this, after migrating to AndroidX import path was LocalBroadcastManager incorrect some way.

I've changed it to:
```
import androidx.localbroadcastmanager.content.LocalBroadcastManager
```

If you click errors from your console of Android Studio it will show you were you should change imports.

That worked for me, hope it will help you, too.

**Comment by mikehardy** [comment]
This continues to be incorrect advice. I would not follow any advice on this thread other than to examine the make-demo.sh script, it does the install and works.

Any import issue like you mention @kdastan is the result of not using jetifier, which should be impossible basically as it is built into the RN60 CLI, it will run as soon as you run react-native start, you can run it yourself also with `npx jetify`

**Comment by kdastan** [comment]
@mikehardy I have run ```npx jetify``` but it doesn't help me with import issue. 

I'm not telling that my solution with import changing is perfect solution, but it works for me and it can be useful for others 😉

**Comment by ashokadichill** [comment]
@mikehardy 
Starter demo project [https://github.com/invertase/react-native-firebase-starter]() build on 
react-native version 0.59.9

Could you please give me the demo project link
so that I can test it and give you the results.

**Comment by mikehardy** [comment]
@ashokadichill it's in this issue linked above https://rnfirebase.io/docs/v5.x.x/auth/phone-auth#Example

@kdastan there is something going on with your local environment - no import with non-AndroidX should exist after conversion from jetifier - I would look into that more deeply if I were you - it is very odd!

**Comment by mikehardy** [comment]
(as an aside, hoping to update the starter project to RN60 soon, but first need to update the react-native-firebase test project itself and get a 5.5.7 out - but the make-demo.sh script I provide along with the Podfile should be sufficient)

**Comment by mikehardy** [comment]
To be clear on one thing - there is a change on the tip of the v5.x.x branch that is unreleased (it will be in 5.5.7) that allows for better library specification for AndroidX in react-native 0.60 - I use the branch reference as my dependency currently: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh#L12

https://github.com/invertase/react-native-firebase/pull/2476

**Comment by ashokadichill** [comment]
```
"@react-native-firebase/app": "^0.1.5",
    "@react-native-firebase/crashlytics": "^0.1.5",
    "react": "16.8.6",
    "react-native": "0.60.4",
```

These library solves the issue

New documentation is out there 
[https://invertase.io/oss/react-native-firebase/]()

**Comment by ashokadichill** [comment]
Crashlytics and analytics work well
but messaging has failed 

`"@react-native-firebase/messaging": "^0.1.5",
`
```
import firebase from "@react-native-firebase/app";
import messaging from "@react-native-firebase/messaging";

firebase.messaging().getToken()
.then(res => {
  console.log("get token res", res);
})
.catch(err => {
  console.log("get token err", err);
});
```

Running on Android
`'get token res', 'es1JcIiSClU:APA91bGzBY5HrDVwmCYaA6aNsnPahFeP2_TF47rgW775w-MnGwBowqpnzDVfyUsCoYJeR632RS_7uEpsaSrSKFYoXaB7AXEPl7YlJCRRcPn5rUPy-CQON_mQKfxhKKzwebZF-YbYB1rq'`

Running on iOS
`'get token err', { [Error: [messaging/unknown] The operation couldn’t be completed. (com.firebase.iid error 1001.)]`


Enabled push notification for the ios app in the build setting generated the certificate for them installed in the keychain access but still the problem for resolves...

**Comment by mikehardy** [comment]
@ashokadichill that's a separate issue, not related to build failures.

Messaging is notoriously difficult to do correctly, but there are not known issues in react-native-firebase at the moment, that I know of?

Here is some interesting info on the first answer here: https://stackoverflow.com/questions/38909670/firebase-fcm-failed-to-fetch-apns-token-error-domain-com-firebase-iid-code-100

Also some whole countries firewall connections so you might try with a VPN as well.

If the issue persists you should open a fresh messaging issue

**Comment by mikehardy** [comment]
also worth noting that notifications for react-native-firebase v6 has not been implemented yet, so you may be in for issues there. If you need notifications you need to stay on v5 for now
