### ISSUE TITLE
Auth: It is not possible to unlink linked providers

### ISSUE THREAD

**Issue by Damnum** [invertase/react-native-firebase#242]
I can link users to providers with the function linkWithCredential: https://github.com/invertase/react-native-firebase/blob/master/lib/modules/auth/user.js#L116

However, the unlink function seems to be missing: https://firebase.google.com/docs/auth/web/account-linking#unlink-an-auth-provider-from-a-user-account

**Comment by chrisbianca** [comment]
@Damnum good spot! We'll look at getting this implemented as soon as we can.  Alternatively, if it's holding you up, please feel free to submit a PR.

**Comment by Salakar** [comment]
@Damnum Taking a look at this now, will push up a patch for it shortly.

**Comment by Salakar** [comment]
Implemented on v2.0.3: 
`firebase.auth().currentUser.unlink(providerId: string): Promise<FirebaseUser>`
