### ISSUE TITLE
Thread 1: signal SIGABRT when sign in to firebase using google sign in

### ISSUE THREAD

**Issue by Talkwondo** [invertase/react-native-firebase#2425]
I have been looking to resolve this issue for 2 weeks now.
many of you encountered this issue and I tried everything and it does not help.
* add GoogleService-info.plist from Xcode itself (add files to project...) and it is recognized. (there is an A besides it)
*pod update firebase and others (core/auth...)
*make sure the .plist has the right client ID like from firebase
*firebase successfully connected to Xcode in firebase.

when I click the button for GoogleSignIn I reach to email and pass and then when it should sign in I got the famous : libc++abi.dylib: terminating with uncaught exception of type NSException.

Facebook login is works properly. 

Any other suggestion?

Pod file:
pod 'Firebase/Core', '~> 5.20.1'
pod 'Firebase/Messaging', '~> 5.20.1'
pod 'GoogleSignIn'
pod 'Firebase'

"react-native-firebase": "^5.1.1",
"react-native-google-signin": "^2.0.0",

Thanks,

**Comment by Ehesp** [comment]
If you could post a reproduction repo up we can take a look a lot easily. These issues are very hard to help with with no code, logs, examples.

**Comment by Talkwondo** [comment]
I don't think my code make this issue. I can post here the code i use:

import firebase from 'firebase';
import { GoogleSignin } from 'react-native-google-signin';

  logInWithGoogle() {
        var datatrans;
        GoogleSignin.
            signIn()        
            .then((data) => {
                console.log(data)
                datatrans = data
                const credential = firebase.auth.GoogleAuthProvider.credential(data.idToken, data.accessToken)
                return firebase.auth().signInWithCredential(credential)
            })
            .catch((error) => {
                console.log('Login Fail with an error: ' + error.toString())
                this.toggleOffLoading()
            })
            firebase.auth().onAuthStateChanged((user) => {
                if (user) {
                    var userId = user.uid;
                    if(datatrans.email) {
                        var email = datatrans.email;   
                    }
                    var googleID = datatrans.id; 
                    var profilePicture = datatrans.photo;
                    if (datatrans.givenName) {
                    var firstName = datatrans.givenName;
                    }
                    
                    firebase.database().ref('users/' + userId + '/Personal_Details').set({
                        username: firstName,
                        email: email,
                        profile_picture: profilePicture,
                        googleID: googleID
                    });
                }
            });    
    }

**Comment by deep-link** [comment]
adding `GoogleService-Info.plist` fixed me this issue
