### ISSUE TITLE
iOS: Failed to enable Analytics DebugView 

### ISSUE THREAD

**Issue by iKoala** [invertase/react-native-firebase#2426]
## Issue

iOS FIRDebugEnabled and FIRAnalyticsDebugEnabled doesn't enable debugview on Firebase console.
(it's working properly on Android)

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by maestor** [comment]
just noticed same thing. about month ago it work well and today after break can't get iOS device to FB console debug view anymore. upgraded RN to 0.59.9 -> 0.60.4 and latest stable react-native-firebase (5.5.6, month ago when DebugView work properly, had 5.5.3), not sure if that is the reason or something else.

**Comment by JanCVanB** [comment]
We're experiencing something similar on RNF v6.2.0 (and RN v0.61.5), but we haven't found a solution yet. I've commented on the open thread #2829.

**Comment by mikehardy** [comment]
I read this and the related comment you left @JanCVanB - did anything interesting come up in the Xcode console when you launch it that way? Is it on a real device? Is it release mode or debug mode? The last two are hunches, the first is because I know I see logging from the firebase SDKs indicating analytics stuff in the console

**Comment by JanCVanB** [comment]
We're launching the app on a simulator (no physical development devices yet) by running `npm run start` in one terminal window and `npm run run:ios` in another. The output for each (below) seems pretty healthy, but is there some other output (in XCode or elsewhere) that I'm missing? Based on the `xcodebuild` command in the runner output and the `-FIRDebugEnabled` and `-FIRAnalyticsDebugEnabled` command line arguments in the scheme, I imagine that the app is running in debug mode and not release mode.

### Bundler output
```
✔ ~/projects/tester
09:35 $ npm run start

> tester@6.2.0 start /Users/jan/projects/tester
> react-native start

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/jan/projects/tester

Loading dependency graph, done.
 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (473/473), done.

```

### Runner output
```
✔ ~/projects/tester
09:35 $ npm run run:ios

> tester@6.2.0 run:ios /Users/jan/projects/tester
> react-native run-ios --simulator="iPhone X"

info Found Xcode workspace "tester.xcworkspace"
info Launching iPhone 8 (iOS 13.3)
info Building (using "xcodebuild -workspace tester.xcworkspace -configuration Debug -scheme tester -destination id=19E6F56F-2F89-474E-8FD5-2BA0E3FC8C0B -derivedDataPath build/tester")
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
info Installing "build/tester/Build/Products/Debug-iphonesimulator/tester.app"
info Launching "org.reactjs.native.example.tester"
success Successfully launched the app on the simulator
✔ ~/projects/tester
09:37 $
```

### Debugger UI output
This is from pressing Cmd+D in the simulator and opening dev tools on http://localhost:8081/debugger-ui/
```
Running application tester ({
    initialProps =     {
    };
    rootTag = 21;
})
Running "tester" with {"rootTag":21,"initialProps":{}}
Return value of analytics().logEvent(...): Promise {_40: 0, _65: 0, _55: null, _72: null}
```
