### ISSUE TITLE
pod install fails after npm install @react-native-firebase/firestore

### ISSUE THREAD

**Issue by cltsang** [invertase/react-native-firebase#2427]
## Issue

Greetings. Thanks for the new release yesterday. I can't wait to try it out!
However, after npm install the latest app, auth, dynamic-links and firestore, I encountered error when I run pod install in the ios folder, which outputs

```
[!] CocoaPods could not find compatible versions for pod "Firebase/Firestore":
  In Podfile:
    RNFBFirestore (from `../node_modules/@react-native-firebase/firestore`) was resolved to 0.1.1, which depends on
      Firebase/Firestore (~> 6.5.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/Firestore (~> 6.5.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'MyAwesomeProject' do
  # Pods for MyAwesomeProject
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'MyAwesomeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'MyAwesomeProject-tvOS' do
  # Pods for MyAwesomeProject-tvOS

  target 'MyAwesomeProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 279.83 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.10.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.3, 27.0.3, 28.0.3
      System Images: android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `0.1.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `app, auth, dynamic-links, firestore`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by cltsang** [comment]
After uninstalling @react-native-firebase/firestore, the same error shows for Firebase/Auth. Then Firebase/Core.

**Comment by cltsang** [comment]
After running react-native link on the modules, I still see the same error.

**Comment by Salakar** [comment]
Hey 👋

Run `pod install --repo-update` - your pod specs repo needs updating locally.

**Comment by potatowave** [comment]
I am still having trouble with this. 

I am using the "Firebase Authentication Kit" https://react-native.market/products/firebase-authentication-kit

The app works out of the box without `@react-native-firebase/firestore`

Process:

1. `yarn add @react-native-firebase/firestore`
2. `cd ios/ && pod install --repo-update

Result:

```
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Detected React Native module pods for BVLinearGradient, RNCMaskedView, RNFBApp, RNFBAuth, RNFBFirestore, RNGestureHandler, RNGoogleSignin, RNReanimated, RNScreens, RNVectorIcons, and react-native-fbsdk
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Firebase/Core":
  In snapshot (Podfile.lock):
    Firebase/Core (= 6.8.1, ~> 6.8.1)

  In Podfile:
    RNFBApp (from `../node_modules/@react-native-firebase/app`) was resolved to 6.0.0, which depends on
      Firebase/Core (~> 6.8.1)

    RNFBFirestore (from `../node_modules/@react-native-firebase/firestore`) was resolved to 6.2.0, which depends on
      Firebase/Core (~> 6.13.0)


You have either:
 * changed the constraints of dependency `Firebase/Core` inside your development pod `RNFBFirestore`.
   You should run `pod update Firebase/Core` to apply changes you've made.
```

How do I fix this?

**Comment by ilibilibom** [comment]
I had the same issue, I updated all @react-native-firebase packages to  6.2.0 
and that solved it for me

**Comment by franciscocobas** [comment]
I tried the above solutions and didn't work for me, I solved the issue by deleting the `./ios/Podfile.lock` and run again `pod install --repo-update` command.

**Comment by jyoo** [comment]
> I tried the above solutions and didn't work for me, I solved the issue by deleting the `./ios/Podfile.lock` and run again `pod install --repo-update` command.

Thank you!
I had encountered the following logs, and could solve the issue by deleting `Podfile.lock` and run `pod install --repo-update` command

```
[!] CocoaPods could not find compatible versions for pod "nanopb":
  In snapshot (Podfile.lock):
    nanopb (= 1.30905.0, ~> 1.30905.0)

  In Podfile:
    RNFBApp (from `../node_modules/@react-native-firebase/app`) was resolved to 7.0.1, which depends on
      Firebase/CoreOnly (~> 6.13.0) was resolved to 6.13.0, which depends on
        FirebaseCore (= 6.4.0) was resolved to 6.4.0, which depends on
          FirebaseCoreDiagnostics (~> 1.0) was resolved to 1.3.0, which depends on
            nanopb (~> 1.30905.0)

    RNFBFirestore (from `../node_modules/@react-native-firebase/firestore`) was resolved to 7.0.1, which depends on
      Firebase/Firestore (~> 6.13.0) was resolved to 6.13.0, which depends on
        FirebaseFirestore (~> 1.8.0) was resolved to 1.8.3, which depends on
          nanopb (~> 0.3.901)


You have either:
 * changed the constraints of dependency `nanopb` inside your development pod `RNFBFirestore`.
   You should run `pod update nanopb` to apply changes you've made.
```

**Comment by prateekchitransh1907** [comment]
[!] CocoaPods could not find compatible versions for pod "Firebase/Core":
  In Podfile:
    RNFBIid (from `../node_modules/@react-native-firebase/iid`) was resolved to 6.7.1, which depends on
      Firebase/Core (~> 6.13.0)

    RNFBMessaging (from `../node_modules/@react-native-firebase/messaging`) was resolved to 7.1.5, which depends on
      Firebase/Analytics (~> 6.25.0) was resolved to 6.25.0, which depends on
        Firebase/Core (= 6.25.0)

I tried deleting the ./ios/Podfile.lock and run again pod install --repo-update command.It didnt'work.

**Comment by mikehardy** [comment]
@prateekchitransh1907 then you have something else pinning the version down. Check all your dependencies

**Comment by prateekchitransh1907** [comment]
> @prateekchitransh1907 then you have something else pinning the version down. Check all your dependencies

I fixed it by installing RNFBIid version 7.1.5. Thanks for the suggestion.

**Comment by mikehardy** [comment]
Glad that got sorted out - thanks for reporting back @prateekchitransh1907 - I know this is unexpected and irritating when it happens, but it seems "normal" ways of resolving it are working and if this strikes you (unknown reader from the future...) work through it and it should be possible to get moving again.

**Comment by webuijorgeGL** [comment]
> I tried the above solutions and didn't work for me, I solved the issue by deleting the `./ios/Podfile.lock` and run again `pod install --repo-update` command.

Thanks...this works for me.

**Comment by Sikandarkhan** [comment]
> > @prateekchitransh1907 then you have something else pinning the version down. Check all your dependencies
> 
> I fixed it by installing RNFBIid version 7.1.5. Thanks for the suggestion.

I was hoping to resolve this issue by this solution but it didn't work.

**Comment by CarlosDanielDev** [comment]
Woks for me run
```bash
pod install
```
after run this
```bash
pod install  --repo-update
```

**Comment by bharatbrovitech** [comment]
Following solution worked for me,

Pod.file
Change **platform :ios, '9.0'** to **platform :ios, '10.0'**

**Comment by mikehardy** [comment]
Yep. When upgrading, it's necessary to carefully read the changelog, this is an extraordinarily complex module and the notes indicate required steps.

https://github.com/invertase/react-native-firebase/blob/master/packages/app/CHANGELOG.md#900-2020-11-10

which links to

https://firebase.google.com/support/release-notes/ios#version_700_-_october_26_2020

**Comment by AhmedSamir74** [comment]
I had the same issue even if after `pod install --repo-update` 
But after changing the `platform :ios, 9.0` to `platform :ios, 10.0` in `ios/podfile ` it works fine
