### ISSUE TITLE
Previous badge count is getting displayed once uninstall and install the app again.

### ISSUE THREAD

**Issue by saikiranoptisol** [invertase/react-native-firebase#2429]
i was facing a weird issue. once i install the app and login and if any notification received the badge count will be set. now if uninstall the app and install again the previous badge count is getting displayed immediately before i logged in or before i installed the app. 

How to fix this issue???

**Comment by gamenic-arim** [comment]
componentDidMount() {
firebase.notifications().setBadge(0) // rebuild the app again. It will remove previous badge count
}

**Comment by saikiranoptisol** [comment]
@gamenic-arim  if i open the app the badge count is getting refreshed but that is not the solution i need. if i had some badge count before unistalling the app and installing again the badge is showing up. it should not happen beacuse its a fresh installation

**Comment by saikiranoptisol** [comment]
Closing this issue because its a default nature in ios Push notification.Ref link: [https://stackoverflow.com/a/33140689](link) @Ehesp  thanks for the awesome library
