### ISSUE TITLE
Not receiving SMS for firebase sms authorization

### ISSUE THREAD

**Issue by favri** [invertase/react-native-firebase#2430]
## Issue

Describe your issue here
I'm not receiving SMS for iOS phone verification. If i input a phone number that is working on android device, the android device receives the sms (being sent from an app runing on iOS) but if i input the iOS phonenumber no SMS is received.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [X] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.5.5`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. SMS PHONE VERIFICATION`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Are you running this in debug or prod build?

**Comment by favri** [comment]
Debug and Testflight.

**Comment by Ehesp** [comment]
Ok so I need to check this, but I'm fairly sure they don't get delivered on simulators or non-release. cc @Salakar any idea?

**Comment by mikehardy** [comment]
Sms never works on emulator or simulator, you have to use the preset test code system in the firebase console

**Comment by ckOfor** [comment]
```Please make sure you are not using the same number you used as default in firebase console```
