### ISSUE TITLE
[IOS] firebase database ERROR: You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.database().

### ISSUE THREAD

**Issue by deflorilemarului** [invertase/react-native-firebase#2431]
I am getting this error recently although i have added the pod in Podfile for database and ran the pod install. Porject builds in Xcode and fails in the app.

Portion of my pod file with other firebase modules working ok:

  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/DynamicLinks', '~> 6.3.0'
  pod 'Firebase/Storage', '~> 6.3.0'
  pod 'Firebase/Database', '~> 6.3.0'   <--- TIHIS NOT WORKING

Any advice ?

Error is: "You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.database().
Ensure you have the required Firebase iOS SDK pod for this module included in your Podfile, in this instance confirm you've added "pod 'Firebase/Database'" to your Podfile
See http://invertase.link/ios for full setup instructions."

UPDATE: deleted and reinstalled both Pods and node_modules - error still persists.
How is NativeModule looking for FirebaseDatabase ?

[x] Using pods

Versions:
    "react-native-firebase": "^5.5.6",

System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Memory: 45.63 MB / 16.00 GB
    Shell: 4.4.19 - /usr/local/bin/bash
  Binaries:
    Node: 11.12.0 - /usr/local/bin/node
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 27.0.3, 28.0.3, 29.0.0
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6
    react-native: ^0.60.3 => 0.60.3
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

**Comment by Ehesp** [comment]
Can you fill out the issue template so we can see versions of things etc.

**Comment by deflorilemarului** [comment]
Updated the issue withe the versions,
I also removed the node_modules and reintalled again the pod install after that. 
same error every time.

is databaseI() different than any other module from RNF ? links, messagging etc all work. why the difference for database ? is it treated differently ? i saw a imilar issue was solved in 5.5.6 yet not working.

**Comment by snamstorm** [comment]
I'm also having the same issue, all other modules work fine except for firebase database

**Comment by danielfein** [comment]
Facing this issue now.
