### ISSUE TITLE
Notification iOS with image not showing with FCM

### ISSUE THREAD

**Issue by idir-s** [invertase/react-native-firebase#2432]
## Issue

I want to receive notification with an image from FCM but the image is not display in the notification banner on iOS but work on Android.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
    pod 'Firebase/Core', '~> 6.3.0'
    pod 'GoogleIDFASupport', '~> 3.14.0'
    pod 'Firebase/Messaging', '~> 6.3.0'
    pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
```

#### `AppDelegate.m`:

```objc
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [[RNFirebaseNotifications instance] didReceiveLocalNotification:notification];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
  [[RNFirebaseMessaging instance] didRegisterUserNotificationSettings:notificationSettings];
}
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
react-native : 0.60.4
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
- **react-native-firebase
  - 5.5.6

  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by booboothefool** [comment]
I'm also having this problem. After attaching an image to a notification in Firebase, I would have expected the puppy to show up in the notification, but there's only text. Are there any extra steps or iOS code that has to be added?

![Screenshot 2019-08-04 17 48 43](https://user-images.githubusercontent.com/13257645/62429708-21f2ca80-b6e0-11e9-93ef-90d6b2f4d5ab.png)

**Comment by Ehesp** [comment]
This should be something handled automatically ny the device. I guess, it would be an SDK version update?

**Comment by LuisRodriguezLD** [comment]
I [can see](https://firebase.google.com/support/release-notes/android#version_1760) this was implemented back in April for Android but I can't find something similar on iOS

**Comment by LuisRodriguezLD** [comment]
Apparently we need to create an extension -> [docs here.](https://firebase.google.com/docs/cloud-messaging/ios/send-image) 

Would be great if `react-native-firebase` could do this automatically :)

**Comment by booboothefool** [comment]
@LuisRodriguezLD Any tips on how to add that? I went to New > Target> Notification Service Extension, then pasted in the FIR line, but getting all sorts of Firebase import issues in the new target e.g. FIRMessaging not found, Firebase.h not found, etc. Not too familiar with iOS. :P

**Comment by booboothefool** [comment]
@LuisRodriguezLD Were you able to set up the notification service extension successfully? I went to New > Target > Notification Service extension, embedded new service extension target in my original target, added the FIRMessaging line, but now having trouble with Firebase imports not found (Firebase works in the original target). Any suggestions would be appreciated.

**Comment by booboothefool** [comment]
@LuisRodriguezLD Were you able to get that notification service extension set up properly? If so, could you provide some steps?

**Comment by LuisRodriguezLD** [comment]
**Yes!** I made it work :) 
Here is what I did:

1. Create a new `Notification Service Extension` 
In Xcode, File -> New -> Target -> Notification Service Extension
Name it and save it ( I used `NotificationServiceExtension` but you can use whatever )

2. This new target will need the pods as well, so in your pod file add
```
target 'NotificationServiceExtension' do
    pod 'Firebase/Messaging', '~> 6.3.0'
end
```
(Don't forget to pod install)

3. Edit your `NotificationService.m` file in the `NotificationServiceExtension` folder, this was created automatically in step 1.


Import RNFirebaseMessaging at the top
```
#import "RNFirebaseMessaging.h"
```
And replace
```
self.contentHandler(self.bestAttemptContent);
```
with
```
[[FIRMessaging extensionHelper] populateNotificationContent:self.bestAttemptContent withContentHandler:contentHandler];
```

[This video](https://www.youtube.com/watch?v=MybLsPhz27g) can get you started in step 1.
[This page](https://firebase.google.com/docs/cloud-messaging/ios/send-image) has instructions on step 3.

If you get stuck let me know

**Comment by booboothefool** [comment]
![Screenshot 2019-08-11 00 25 54](https://user-images.githubusercontent.com/13257645/62829561-9ccf5000-bbce-11e9-81f6-d1b63671bfb6.png)

Ugh I'm stuck on `5.3.0` and this might have to do with it? https://github.com/firebase/firebase-ios-sdk/pull/1503

**Comment by LuisRodriguezLD** [comment]
Yeah. I highly recommend you upgrade `react-native-firebase` to 5.5.6 which has the firebase sdk in `6.3.0`

**Comment by ThanhQuang1410** [comment]
@LuisRodriguezLD thanks for your solution but I still get some glitch here. When app in background or foreground, my notification display perfectly with image. But when app is open image dose not show. Do you have any solution for that?
Thanks for your support

**Comment by sakina1403** [comment]
> **Yes!** I made it work :)
> Here is what I did:
> 
> 1. Create a new `Notification Service Extension`
>    In Xcode, File -> New -> Target -> Notification Service Extension
>    Name it and save it ( I used `NotificationServiceExtension` but you can use whatever )
> 2. This new target will need the pods as well, so in your pod file add
> 
> ```
> target 'NotificationServiceExtension' do
>     pod 'Firebase/Messaging', '~> 6.3.0'
> end
> ```
> 
> (Don't forget to pod install)
> 
> 1. Edit your `NotificationService.m` file in the `NotificationServiceExtension` folder, this was created automatically in step 1.
> 
> Import RNFirebaseMessaging at the top
> 
> ```
> #import "RNFirebaseMessaging.h"
> ```
> 
> And replace
> 
> ```
> self.contentHandler(self.bestAttemptContent);
> ```
> 
> with
> 
> ```
> [[FIRMessaging extensionHelper] populateNotificationContent:self.bestAttemptContent withContentHandler:contentHandler];
> ```
> 
> [This video](https://www.youtube.com/watch?v=MybLsPhz27g) can get you started in step 1.
> [This page](https://firebase.google.com/docs/cloud-messaging/ios/send-image) has instructions on step 3.
> 
> If you get stuck let me know.
> Please note, step 1 automatically adds a deployment target version. Adjust according to your needs.

I tried your solution and the App builds and runs on Simulator, however, when I try to run the App on physical device I am getting this error:

<img width="1150" alt="Screenshot 2019-09-16 at 3 56 49 PM" src="https://user-images.githubusercontent.com/42813443/64951357-5048f580-d89b-11e9-8c4c-5ed4cfd36b35.png">

Please review @LuisRodriguezLD  ASAP.

**Comment by yoopoong96** [comment]
> Yeah. I highly recommend you upgrade `react-native-firebase` to 5.5.6 which has the firebase sdk in `6.3.0`

I get sharedApplication is unavailable error. How did you handle this problem?

**Comment by LuisRodriguezLD** [comment]
@ThanhQuang1410 Sorry, I do not have a current solution for when the app is open. I am pretty sure it's a very similar approach. 

I'll try to get an example running today but no promises. Feel free to [DM](https://twitter.com/luisrodriguezLD) me.

**Comment by sakina1403** [comment]
@LuisRodriguezLD Awesome. Did you get a chance to try? I am facing a similar issue on Android as well. When the App is open expandable Notifications don't come, even if it's text. The Notification is received but it's not expandable.

**Comment by yoopoong96** [comment]
> @LuisRodriguezLD Awesome. Did you get a chance to try? I am facing a similar issue on Android as well. When the App is open expandable Notifications don't come, even if it's text. The Notification is received but it's not expandable.

In android handle it with local notification.

**Comment by NikitaPFE** [comment]
> **Yes!** I made it work :)
> Here is what I did:
> 
> 1. Create a new `Notification Service Extension`
>    In Xcode, File -> New -> Target -> Notification Service Extension
>    Name it and save it ( I used `NotificationServiceExtension` but you can use whatever )
> 2. This new target will need the pods as well, so in your pod file add
> 
> ```
> target 'NotificationServiceExtension' do
>     pod 'Firebase/Messaging', '~> 6.3.0'
> end
> ```
> 
> (Don't forget to pod install)
> 
> 1. Edit your `NotificationService.m` file in the `NotificationServiceExtension` folder, this was created automatically in step 1.
> 
> Import RNFirebaseMessaging at the top
> 
> ```
> #import "RNFirebaseMessaging.h"
> ```
> 
> And replace
> 
> ```
> self.contentHandler(self.bestAttemptContent);
> ```
> 
> with
> 
> ```
> [[FIRMessaging extensionHelper] populateNotificationContent:self.bestAttemptContent withContentHandler:contentHandler];
> ```
> 
> [This video](https://www.youtube.com/watch?v=MybLsPhz27g) can get you started in step 1.
> [This page](https://firebase.google.com/docs/cloud-messaging/ios/send-image) has instructions on step 3.
> 
> If you get stuck let me know.
> Please note, step 1 automatically adds a deployment target version. Adjust according to your needs.

Сan you show an example of your code?
When i try to add #import "RNFirebaseMessaging.h" i have error "file not found".
Рow did you modify the AppDelegate.m and AppDelegate.h  files?

I use Firebase/Messaging', '~> 6.3.0'
and react native 0.59.9

**Comment by LuisRodriguezLD** [comment]
@NikitaPFE file not found could be because you did not install the pods. did you follow step 2? Don't forget you need to `pod install`

**Comment by NikitaPFE** [comment]
@LuisRodriguezLD 
Yes, I did `pod install `

You do not know whether to remove these methods from the AppDelegate.m?

![Screen Shot 2019-09-19 at 19 50 54](https://user-images.githubusercontent.com/43850394/65264244-e2a8fd80-db16-11e9-8464-f98c91245861.png)

**Comment by sakina1403** [comment]
@NikitaPFE There is no need to remove that code from Appdelegate.m

Go to `NotificationService` Target -> Build Settings -> Search Header paths and add -> 

`$(SRCROOT)/../node_modules/react-native-firebase/ios/RNFirebase/messaging`

Refer https://github.com/invertase/react-native-firebase/issues/632#issuecomment-359673796 for the same.

**Comment by Dhavalmaheta** [comment]
> I'm also having this problem. After attaching an image to a notification in Firebase, I would have expected the puppy to show up in the notification, but there's only text. Are there any extra steps or iOS code that has to be added to enable this functionality?
> 
> ![Screenshot 2019-08-04 17 48 43](https://user-images.githubusercontent.com/13257645/62429708-21f2ca80-b6e0-11e9-93ef-90d6b2f4d5ab.png)

any solution you got for this ?

**Comment by Anshuman71** [comment]
> **Yes!** I made it work :)
> Here is what I did:
> 
> 1. Create a new `Notification Service Extension`
>    In Xcode, File -> New -> Target -> Notification Service Extension
>    Name it and save it ( I used `NotificationServiceExtension` but you can use whatever )
> 2. This new target will need the pods as well, so in your pod file add
> 
> ```
> target 'NotificationServiceExtension' do
>     pod 'Firebase/Messaging', '~> 6.3.0'
> end
> ```
> 
> (Don't forget to pod install)
> 
> 1. Edit your `NotificationService.m` file in the `NotificationServiceExtension` folder, this was created automatically in step 1.
> 
> Import RNFirebaseMessaging at the top
> 
> ```
> #import "RNFirebaseMessaging.h"
> ```
> 
> And replace
> 
> ```
> self.contentHandler(self.bestAttemptContent);
> ```
> 
> with
> 
> ```
> [[FIRMessaging extensionHelper] populateNotificationContent:self.bestAttemptContent withContentHandler:contentHandler];
> ```
> 
> [This video](https://www.youtube.com/watch?v=MybLsPhz27g) can get you started in step 1.
> [This page](https://firebase.google.com/docs/cloud-messaging/ios/send-image) has instructions on step 3.
> 
> If you get stuck let me know.
> Please note, step 1 automatically adds a deployment target version. Adjust according to your needs.

@LuisRodriguezLD thanks for your help. Your solution worked like a charm and now I can send push with images from the console. Can you please share your push notification code, the payload you send from your server.

**Comment by casualcoder404** [comment]
> **Yes!** I made it work :)
> Here is what I did:
> 
> 1. Create a new `Notification Service Extension`
>    In Xcode, File -> New -> Target -> Notification Service Extension
>    Name it and save it ( I used `NotificationServiceExtension` but you can use whatever )
> 2. This new target will need the pods as well, so in your pod file add
> 
> ```
> target 'NotificationServiceExtension' do
>     pod 'Firebase/Messaging', '~> 6.3.0'
> end
> ```
> 
> (Don't forget to pod install)
> 
> 1. Edit your `NotificationService.m` file in the `NotificationServiceExtension` folder, this was created automatically in step 1.
> 
> Import RNFirebaseMessaging at the top
> 
> ```
> #import "RNFirebaseMessaging.h"
> ```
> 
> And replace
> 
> ```
> self.contentHandler(self.bestAttemptContent);
> ```
> 
> with
> 
> ```
> [[FIRMessaging extensionHelper] populateNotificationContent:self.bestAttemptContent withContentHandler:contentHandler];
> ```
> 
> [This video](https://www.youtube.com/watch?v=MybLsPhz27g) can get you started in step 1.
> [This page](https://firebase.google.com/docs/cloud-messaging/ios/send-image) has instructions on step 3.
> 
> If you get stuck let me know.
> Please note, step 1 automatically adds a deployment target version. Adjust according to your needs.

I implemented these steps in my code. However when I send =>

{
   "to": "dWB537Nz1GA:APA91bHIjJ5....",
   "content_available": true,
   "mutable_content": true,
   "data":
   {
      "message": "Offer!",
      "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/FloorGoban.JPG/1024px-FloorGoban.JPG"
   },
   "notification":
   {
      "body": "Enter your message",
      "sound": "default"
   }
}


I am still not able to see the image in the notification.

**Comment by pilot4u** [comment]
did anyone solved this issue I'm struggling with the same one
I added :
target 'NotificationServiceExtension' do
    pod 'Firebase/Messaging', '~> 6.3.0'
end
to pod file and did pod install
as well edited NotificationService.m file
and replaced self.contentHandler(self.bestAttemptContent);
with:
[[FIRMessaging extensionHelper] populateNotificationContent:self.bestAttemptContent
                                            withContentHandler:contentHandler];

but cannot receive notification after successfully sending following FCM POST
`
  "notification": {
    "title": “test”,
    "body": “test”,
    "icon": "",
    "sound": ""
  },
  "apns": {
    "payload": {
      "aps": {
        "mutable-content": 1
      },
      "mediaUrl": "<img url>",
      "mediaType": "image"
    },
    "fcm_options": {
      "image": “<img url>“
    }
  },
  "data": {
<custom json>
      },
  "to": “<fcm token>”
}`

please note that this message is received when the application is in the foreground.
but nothing is received when the app in the background or closed
please help us to resolve this issue

**Comment by gianpaj** [comment]
If you have this iOS app build error:
```
'openURL:options:completionHandler:' is unavailable: not available on iOS (App Extension
```

you have to add this at the end of your `Podfile`:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end
```

from: https://github.com/facebook/react-native/issues/25792#issuecomment-517295859

**Comment by pranav-jayadev** [comment]
I have tried this, and am getting some error like the provisioning profile is not matching. Here my question is after adding the Notification service extension do we need to create another provisioning profile for this bundle id?

**Comment by ali-tit** [comment]
**Check your deployment target on Service Extension.**

by default the **Extension deployment target** is set to **iOS 13.1** ( depending on your sdk version ), so you need a device with same iOS version OR you have to choose a lower value to match your device iOS
<img width="1060" alt="apns" src="https://user-images.githubusercontent.com/17291472/75139113-228a9700-56ec-11ea-8c33-d68e8b584998.png">

**Comment by davidepalazzo** [comment]
> Import RNFirebaseMessaging at the top
> `#import "RNFirebaseMessaging.h"`

For people using RNF 5 or greater change the import to `#import “FirebaseMessaging.h”`.

**Comment by yash-atreya** [comment]
> **Yes!** I made it work :)
> Here is what I did:
> 
> 1. Create a new `Notification Service Extension`
>    In Xcode, File -> New -> Target -> Notification Service Extension
>    Name it and save it ( I used `NotificationServiceExtension` but you can use whatever )
> 2. This new target will need the pods as well, so in your pod file add
> 
> ```
> target 'NotificationServiceExtension' do
>     pod 'Firebase/Messaging', '~> 6.3.0'
> end
> ```
> 
> (Don't forget to pod install)
> 
> 1. Edit your `NotificationService.m` file in the `NotificationServiceExtension` folder, this was created automatically in step 1.
> 
> Import RNFirebaseMessaging at the top
> 
> ```
> #import "RNFirebaseMessaging.h"
> ```
> 
> And replace
> 
> ```
> self.contentHandler(self.bestAttemptContent);
> ```
> 
> with
> 
> ```
> [[FIRMessaging extensionHelper] populateNotificationContent:self.bestAttemptContent withContentHandler:contentHandler];
> ```
> 
> [This video](https://www.youtube.com/watch?v=MybLsPhz27g) can get you started in step 1.
> [This page](https://firebase.google.com/docs/cloud-messaging/ios/send-image) has instructions on step 3.
> 
> If you get stuck let me know.
> Please note, step 1 automatically adds a deployment target version. Adjust according to your needs.

This did not work for me.
Build was successful but it still didn't work

**Comment by jagwingchoy** [comment]
> after adding a **NotificationServiceExtension** please **Check your deployment target on Service Extension.**
> 
> by default the **Extension deployment target** is set to **iOS 13.1** ( depending on your sdk version ), so you need a device with same iOS version OR you have to choose a lower value to match your device iOS
> <img alt="apns" width="1060" src="https://user-images.githubusercontent.com/17291472/75139113-228a9700-56ec-11ea-8c33-d68e8b584998.png">

Thanks you make my day!!

**Comment by Daha62** [comment]
> > Import RNFirebaseMessaging at the top
> > `#import "RNFirebaseMessaging.h"`
> 
> For people using RNF 5 or greater change the import to `#import “FirebaseMessaging.h”`.

I've one everything that was written above, but got an error 
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRMessaging", referenced from:
      objc-class-ref in NotificationService.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

react-native v0.63.3
RNF is greater than 5

Here is a part of my NotificationService.m

```
#import "NotificationService.h"
#import "FirebaseMessaging.h"

@interface NotificationService ()
@property (nonatomic, strong) void (^contentHandler)(UNNotificationContent *contentToDeliver);
@property (nonatomic, strong) UNMutableNotificationContent *bestAttemptContent;
@end

@implementation NotificationService

- (void)didReceiveNotificationRequest:(UNNotificationRequest *)request withContentHandler:(void (^)(UNNotificationContent * _Nonnull))contentHandler {
    self.contentHandler = contentHandler;
    self.bestAttemptContent = [request.content mutableCopy];
    
    // Modify the notification content here...
    self.bestAttemptContent.title = [NSString stringWithFormat:@"%@ [modified]", self.bestAttemptContent.title];
    
    [[FIRMessaging extensionHelper] populateNotificationContent:self.bestAttemptContent withContentHandler:contentHandler];
}

@end
```

Also I have in my podFile

```
  target 'NotificationService' do
    pod 'Firebase/Messaging', '~> 6.30.0'
  end
```

Any ideas?

**Comment by haduy97** [comment]
> after adding a **NotificationServiceExtension** please **Check your deployment target on Service Extension.**
> 
> by default the **Extension deployment target** is set to **iOS 13.1** ( depending on your sdk version ), so you need a device with same iOS version OR you have to choose a lower value to match your device iOS
> <img alt="apns" width="1060" src="https://user-images.githubusercontent.com/17291472/75139113-228a9700-56ec-11ea-8c33-d68e8b584998.png">

Thank you very much, you just save my whole day. I appreciate it

**Comment by curiousdustin** [comment]
Another tip for those trying to cruise through this thing that should be handled automatically...

The NotificationService.m is created with boilerplate code already in it.

You probably want to remove or edit this line, which modifies the notification title:

```
self.bestAttemptContent.title = [NSString stringWithFormat:@"%@ [modified]", self.bestAttemptContent.title];
```

**Comment by rjuevesano** [comment]
Can someone help me? Image not showing in notification with FCM.

![image](https://user-images.githubusercontent.com/4033035/108386021-32798000-7247-11eb-95b2-b9f6f2af24db.png)

I'm using postman to send this notification
![image](https://user-images.githubusercontent.com/4033035/108385766-f514f280-7246-11eb-8bb9-689a47510fee.png)

package.json
```
"@react-native-firebase/app": "8.4.7",
"@react-native-firebase/messaging": "7.9.2",
"react-native": "0.63.4",
```

Podfile
```
target 'ImageNotification' do
  pod 'Firebase/Messaging', '~> 6.34.0'
end
```

**Comment by r1skz3ro** [comment]
Thanks for the instructions! I'm still facing a problem with displaying image when app is open. Image is displayed perfectly fine when app is in the background but not if app is open. Anyone was able to solve that issue?

**Comment by Hyllesen** [comment]
For anyone with ``RNFirebaseMessaging.h file not found error`` or errors with `#Import "FirebaseMessaging.h"` use 
``@import Firebase`` instead

**Comment by anhquan291** [comment]
> > **Yes!** I made it work :)
> > Here is what I did:
> > 
> > 1. Create a new `Notification Service Extension`
> >    In Xcode, File -> New -> Target -> Notification Service Extension
> >    Name it and save it ( I used `NotificationServiceExtension` but you can use whatever )
> > 2. This new target will need the pods as well, so in your pod file add
> > 
> > ```
> > target 'NotificationServiceExtension' do
> >     pod 'Firebase/Messaging', '~> 6.3.0'
> > end
> > ```
> > 
> > 
> > (Don't forget to pod install)
> > 
> > 1. Edit your `NotificationService.m` file in the `NotificationServiceExtension` folder, this was created automatically in step 1.
> > 
> > Import RNFirebaseMessaging at the top
> > ```
> > #import "RNFirebaseMessaging.h"
> > ```
> > 
> > 
> > And replace
> > ```
> > self.contentHandler(self.bestAttemptContent);
> > ```
> > 
> > 
> > with
> > ```
> > [[FIRMessaging extensionHelper] populateNotificationContent:self.bestAttemptContent withContentHandler:contentHandler];
> > ```
> > 
> > 
> > [This video](https://www.youtube.com/watch?v=MybLsPhz27g) can get you started in step 1.
> > [This page](https://firebase.google.com/docs/cloud-messaging/ios/send-image) has instructions on step 3.
> > If you get stuck let me know.
> > Please note, step 1 automatically adds a deployment target version. Adjust according to your needs.
> 
> This did not work for me.
> Build was successful but it still didn't work

Hi there, I'm facing the same problem here. Did you find a solution? Thanks

**Comment by lauro-cesar** [comment]
Don't miss this detail: Check Frameworks and Libraries and make sure the extension is embedded.

<img width="1214" alt="Screen Shot 2021-04-30 at 21 34 57" src="https://user-images.githubusercontent.com/99175/116765628-7a154880-a9fc-11eb-88cd-835dcfaaa31f.png">

**Comment by vipu-sa** [comment]
> https://rnfirebase.io/messaging/ios-notification-images

I am following this link for the notification with the image in iPhone, but the image is not getting with notification.

I am sharing the details of current versions which are used in my project.
"react-native": "0.62.2",
"@react-native-firebase/app": "^8.4.0",
 "@react-native-firebase/messaging": "^7.8.1",
Firebase/Messaging (6.34.0) in Podfile.lock
In project, Deployment Info, iOS version is 14.4 
In my iPhone device version is 14.7.1

Getting build fail issue when inserting the below line in NotificationService file.
#import "FirebaseMessaging.h" 
[[FIRMessaging extensionHelper] populateNotificationContent:self.bestAttemptContent withContentHandler:contentHandler];

Please help to solve this issue.

**Comment by ydv0121** [comment]
> after adding a **NotificationServiceExtension** please **Check your deployment target on Service Extension.**
> 
> by default the **Extension deployment target** is set to **iOS 13.1** ( depending on your sdk version ), so you need a device with same iOS version OR you have to choose a lower value to match your device iOS <img alt="apns" width="1060" src="https://user-images.githubusercontent.com/17291472/75139113-228a9700-56ec-11ea-8c33-d68e8b584998.png">

after spent many hours.this worked like a charm.
thanks

**Comment by congduong97** [comment]
Any solution for #import "RNFirebaseMessaging.h"  not found?, thanks

**Comment by mikehardy** [comment]
@congduong97 it is not polite to post unrelated comments to other people's issues

**Comment by congduong97** [comment]
@mikehardy  Sorry, 
I had this problem while following the instructions and I saw that someone had the same problem as me

**Comment by yousrasd** [comment]
Is anyone running into this after upgrading to firebase/messaging v16.1? With v14.10,  the images show up (we have a notification service extension). But after upgrading to v16.1, push notifications are shown without images.

**Comment by JeanHules** [comment]
After a bit of struggling, Xcode set my extension iOS version to the latest while the main app's version was set to 12.4. Changing the extension to 12.4, the image comes through.

**Comment by fattahmuhyiddeen** [comment]
there is official doc for this

https://rnfirebase.io/messaging/ios-notification-images

**Comment by isaacbatst** [comment]
I had to do it a bit different:

```
target 'ImageNotification' do
  use_frameworks! :linkage => :static
  
  pod 'Firebase/Messaging', '~> VERSION'
end
```

**Comment by DaveTolulope22** [comment]
Notification image only shows when in the app is in the background  not when the app is in the  Foreground how do I solve this ?

**Comment by Djain1764** [comment]
> Notification image only shows when in the app is in the background not when the app is in the Foreground how do I solve this ?

hey @DaveTolulope22 , are you able to make image notifications work ??
I am not even able to make it work for background notifications, can you please help me on that, can you tell me what reference you followed exactly !!

**Comment by ehtishamali042** [comment]
> after adding a **NotificationServiceExtension** please **Check your deployment target on Service Extension.**
> 
> by default the **Extension deployment target** is set to **iOS 13.1** ( depending on your sdk version ), so you need a device with same iOS version OR you have to choose a lower value to match your device iOS <img alt="apns" width="1060" src="https://user-images.githubusercontent.com/17291472/75139113-228a9700-56ec-11ea-8c33-d68e8b584998.png">

amazing amazing amazing

**Comment by danishsaleem0** [comment]
working in forground but not in background how to solve this? 
here is my notification-service
import PushNotification from 'react-native-push-notification';
import PushNotificationIOS from '@react-native-community/push-notification-ios';
import {Platform} from 'react-native';

class LocalNotificationService {
  configure = onOpenNotification => {
    PushNotification.configure({
      // (optional) Called when Token is generated (iOS and Android)
      onRegister: function (token) {},

      // (required) Called when a remote is received or opened, or local notification is opened
      onNotification: function (notification) {
        if (!notification?.data) {
          return;
        }
        notification.userInteraction = true;
        onOpenNotification(
          Platform.OS === 'ios' ? notification.data.item : notification.data,
        );

        if (Platform.OS === 'ios') {
          notification.finish(PushNotificationIOS.FetchResult.NoData);
        }
      },

      // (optional) Called when Registered Action is pressed and invokeApp is false, if true onNotification will be called (Android)
      onAction: function (notification) {
        console.log('ACTION:', notification.action);
        console.log('NOTIFICATION:', notification);
      },

      // (optional) Called when the user fails to register for remote notifications. Typically occurs when APNS is having issues, or the device is a simulator. (iOS)
      onRegistrationError: function (err) {
        console.error(err.message, err);
      },

      permissions: {
        alert: true,
        badge: true,
        sound: true,
      },

      popInitialNotification: true,
      requestPermissions: true,
    });
  };
  unRegister = () => {
    PushNotification.unregister();
  };

  showNotification = (id, title, message, data = {}, options = {}) => {
    PushNotification.localNotification({
      /* Android only Properties*/
      ...this.buildAndroidNotification(id, title, message, data, options),
      /* IOS and Android properties*/

      ...this.buildIOSNotification(id, title, message, data, options),
      /* IOS and Android properties */
      title: title || '',
      message: message || '',
      playSound: options.playSound || false,
      soundName: options.soundName || 'default',
      channelId: 'mindnourishment',
      userInteraction: false, // BOOLEAN: If the notification was opened by the user from the notification area or not
    });
  };
  buildAndroidNotification = (id, title, message, data = {}, options = {}) => {
    return {
      id: id || 1,
      autoCancel: true,
      largeIcon: options.largeIcon || 'ic_launcher',
      smallIcon: options.smallIcon || 'ic_notification',
      bigText: message || '',
      subText: title || '',
      vibrate: options.vibrate || true,
      vibration: options.vibration || 300,
      priority: options.priority || 'high',
      importance: options.importance || 'high', // (optional) set notifications importance
      data: data,
    };
  };

  buildIOSNotification = (id, title, message, data = {}, options = {}) => {
    console.log(data, 'data');
    return {
      alertAction: options.alertAction || 'view',
      category: options.category || '',
      userInfo: {
        id: id,
        item: data,
        // image: data?.data?.fcm_options?.image || null,
      },
    };
  };

  createNotificationChannel = () => {
    PushNotification.createChannel({
      channelId: 'mindnourishment',
      channelName: 'mindnourishment',
      channelDescription: 'Mindnourishment Channel Description ',
      importance: 4, // 4 = Max, 3 = High, 2 = Default, 1 = Low, 0 = None
      vibration: true,
    });
  };
  cancelAllLocalNotifications = () => {
    {
      PushNotification.cancelAllLocalNotifications();
    }
  };
  removeDeliveredNotificationByID = notificationId => {
    console.log(
      '[LocalNotificationService] removeDeliveredNotificationByID: ',
      notificationId,
    );
    PushNotification.cancelLocalNotifications({id: `${notificationId}`});
  };
}

export const localNotificationService = new LocalNotificationService();

and fcm-service
import messaging from '@react-native-firebase/messaging';
import {Platform} from 'react-native';

class FCMService {
  register = (onRegister, onNotification, onOpenNotification) => {
    this.checkPermission(onRegister);
    this.createNotificationsListeners(
      onRegister,
      onNotification,
      onOpenNotification,
    );
  };

  registerAppWithFCM = async () => {
    if (Platform.OS === 'ios') {
      await messaging().registerDeviceForRemoteMessages();
      await messaging().setAutoInitEnabled(true);
    }
  };

  checkPermission = onRegister => {
    messaging()
      .hasPermission()
      .then(enabled => {
        if (enabled) {
          // User has permission
          this.getToken(onRegister);
        } else {
          // User doesn't have permission
          this.requestPermission();
        }
      })
      .catch(error => {
        console.log('[FCMService] Permission rejected', error);
      });
  };

  getToken = onRegister => {
    messaging()
      .getToken()
      .then(fcmToken => {
        if (fcmToken) {
          onRegister(fcmToken);
        } else {
          console.log('[FCMService] user does not have a device token');
        }
      })

      .catch(error => {
        console.log('[FCMService] getToken rejected', error);
      });
  };

  requestPermission = onRegister => {
    messaging()
      .requestPermission()
      .then(() => {
        this.getToken(onRegister);
      })
      .catch(error => {
        console.log('[FCMService] Request permission rejected');
      });
  };

  deleteToken = () => {
    console.log('[FCMService] deleteToken');
    messaging()
      .deleteToken()
      .catch(error => {
        console.log('[FCMService] Delete token error ', error);
      });
  };

  createNotificationsListeners = (
    onRegister,
    onNotification,
    onOpenNotification,
  ) => {
    // When the application is running ,but in background
    messaging().onNotificationOpenedApp(remoteMessage => {
      if (remoteMessage) {
        const notification = remoteMessage.notification;
        console.log(notification, 'remoteMessage');
        onOpenNotification(remoteMessage);
      }
    });

    messaging().setBackgroundMessageHandler(async remoteMessage => {
      if (remoteMessage) {
        const notification = remoteMessage;
        console.log(notification);
        onOpenNotification(remoteMessage);
      }
    });
    // when the application is opened from a quite state.
    messaging()
      .getInitialNotification()
      .then(remoteMessage => {
        if (remoteMessage) {
          const notification = remoteMessage.notification;
          onOpenNotification(remoteMessage);
        }
      });
    // Foreground state messages
    this.messageListener = messaging().onMessage(async remoteMessage => {
      if (remoteMessage) {
        let notification = null;
        if (Platform.OS === 'ios') {
          notification = remoteMessage;
        } else {
          notification = remoteMessage;
        }
        onNotification(notification);
      }
    });

    // Triggered when have new token
    messaging().onTokenRefresh(fcmToken => {
      console.log('[FCMService] New token refresh: ', fcmToken);
      onRegister(fcmToken);
    });
  };

  unRegister = () => {
    this.messageListener();
  };
}

export const fcmService = new FCMService();
