### ISSUE TITLE
IOS Unable to receive notifications v-5.x.x

### ISSUE THREAD

**Issue by KiranreddySrDev** [invertase/react-native-firebase#2433]
## Issue

React-native : 0.59.3
react: 16.8.3
rnFirebase : 5.x.x

I have added React native firebase in both android and IOS platforms, android is working fine but the issue with IOS here is the thing that when I am running app Xcode Emulator it shows firebase tokens and alerts but when I app build in another IOS mobile it didn't get any alerts and tokens.

Why I didn't know actually can anyone help me out. why firebase is running emulator why did not work in normal mobiles 
is there any difference ?

Thanks

**Comment by donedgardo** [comment]
I dont think push notifications work on simulators. not sure

**Comment by KiranreddySrDev** [comment]
That means alerts I have put an alert when firebase is being sent a message then It gets an alert in emulator but not in normal phones

**Comment by maxconnectAbhi** [comment]
same issue any solution?
