### ISSUE TITLE
Disable/Enable notification permission through react native code.

### ISSUE THREAD

**Issue by abhi-nahi** [invertase/react-native-firebase#2437]
For feature requests please visit our [Feature Request Board](https://invertase.io/oss/react-native-firebase/feedback/).
I want to turn off the notification from my application command but we don't have ant feature like this.
Even firebase.messaging().requestPermission() is not revoking again if user already has permission.

Do whatever is possible.

**Comment by Ehesp** [comment]
Please add it here: http://boards.invertase.io/react-native-firebase
