### ISSUE TITLE
iOS Messaging removed methods notificationResponse and willPresent

### ISSUE THREAD

**Issue by dgruseck** [invertase/react-native-firebase#245]
Hi,

why do you have removed didReceiveNotificationResponse and willPresentNotification in v2?
How can I distinguish if a message is opened when app is in foreground or a notification is presented or even intercept a notification with WillPresent.

I'm now only receiving the type Remote. Do I miss something?

### Environment

1. Target Platform: iOS
2. Development Operating System: macOS
3. React Native version: 0.44.3
4. RNFirebase Version: 2.0.2

**Comment by SteffeyDev** [comment]
This looks very similar to my issue #225, so thank you for confirming that you are having this issue as well.

**Comment by chrisbianca** [comment]
@dgruseck This was a mix up by me when upgrading to the iOS 4.0.0 SDK.  The documentation removed these two methods so I wrongly assumed that Firebase was handling these internally.

They have since included this note, rather than an example:
```
Since iOS 10, you can set UNUserNotificationCenter delegate to receive display notifications from Apple and FIRMessaging remoteMessageDelegate to receive data messages from FCM. If you do not set these two delegates with AppDelegate, method swizzling for message handling is disabled. You'll need to call method appDidReceiveMessage: to track message delivery and analytics.
```

I have just re-added the methods as part of the 2.0.4 release: https://github.com/invertase/react-native-firebase/releases/tag/v2.0.4

**Comment by dgruseck** [comment]
Thanks alot for the quick fix and keep up the good work.

**Comment by dgruseck** [comment]
@chrisbianca Today I had a chance to upgrade.
Unfortunately I'm still only receiving remote_notification in the onMessage callback.
I upgraded to version 2.0.4, did a pod install and added the methods:
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {
  [RNFirebaseMessaging willPresentNotification:notification withCompletionHandler:completionHandler];
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)())completionHandler {
  [RNFirebaseMessaging didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}
``` 

Did I miss something?

**Comment by chrisbianca** [comment]
@dgruseck I'm a little confused. What are you expecting to received in the onMessage callback?

**Comment by dgruseck** [comment]
Hey in version 1... I received:
- `firebase.messaging().NOTIFICATION_TYPE.WillPresent` where I can modify the message
- `firebase.messaging().NOTIFICATION_TYPE.NotificationResponse` which is received when the user clicks on the notification

with the `firebase.messaging().NOTIFICATION_TYPE.Remote` I can not differentiate if the user has clicked the notification or not if the app is in foreground.

**Comment by dgruseck** [comment]
@chrisbianca Did you have some time to look into this?
