### ISSUE TITLE
Build gradle

### ISSUE THREAD

**Issue by crosskpixel** [invertase/react-native-firebase#2451]
I am trying to build the starter kit project but the process: app: transformDexArchiveWithDex is never finalized. I followed all the steps in the document https://rnfirebase.io/docs/v5.x.x/installation/basic-kit

Thank you

**Comment by samad324** [comment]
I have the issue, but I solved it by migrating my project on AndroidX

**Comment by Salakar** [comment]
Please correctly fill out the issue template, without this, we can not help. 

Locking and closing this issue. Feel free to raise another issue that correctly follows the issue template.
