### ISSUE TITLE
cant install @react-native-firebase/notifications

### ISSUE THREAD

**Issue by shantidyah** [invertase/react-native-firebase#2459]
## Issue

Describe your issue here

install notification : 
yarn add @react-native-firebase/notifications

and i got this : 
error An unexpected error occurred: "https://registry.yarnpkg.com/@react-native-firebase%2fnotifications: Not found".

react-native version is 0.60.4
firebase v6

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. v6`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
@react-native-firebase/notifications Hasn't been completed yet. Please keep an eye on the v6 issue thread.

**Comment by ganpatipaswan** [comment]
![Screenshot 2019-08-12 at 12 56 24 PM](https://user-images.githubusercontent.com/32195368/62850532-c5effd80-bd00-11e9-96c1-022b51b1283a.png)
yarn add @react-native-firebase/notifications is not working?
1. when i send push notification then app crashes .please help me?

**Comment by Ehesp** [comment]
> @react-native-firebase/notifications Hasn't been completed yet. Please keep an eye on the v6 issue thread.

**Comment by har2008preet** [comment]
any update?

**Comment by dusan-dragon** [comment]
@har2008preet not yet. You can watch the status here. https://invertase.io/oss/react-native-firebase/releases/v6.0.0 They stated it will be released later on. So I would not expect it to be ready with release of v6....

**Comment by har2008preet** [comment]
@dusan-dragon looks like I have to revert back to v5.
Thanks for the info anyway. 
Will keep an eye to that.

**Comment by leotm** [comment]
Spotted some alpha version on Google but looks like it's been removed for time being

<img width="609" alt="Screenshot 2019-09-25 at 15 42 41" src="https://user-images.githubusercontent.com/1881059/65611741-26828380-dfab-11e9-8c3e-dc7b6eb59c89.png">

**Comment by thecodecafe** [comment]
Please is there a determined date for when this will be ready? Have already started integrating and upgraded firebase and all my google services only to find out this isn't ready.

**Comment by mikehardy** [comment]
@thecodecafe there is never a determined date for open source software (which is just being honest really - commercial software slips deadlines all the time, in open source it's usually just that promises aren't made in the first place). The information above is the most up to date and #2566 can be subscribed to if you like

**Comment by leotm** [comment]
Subbed, cheers @mikehardy

**Comment by thecodecafe** [comment]
@mikehardy thanks, subscribed!

**Comment by maria-tahir** [comment]
This is quite a surprise. The github repo points to version 6 and version 5 document states that it is on lifesupport. This led us to upgrade react-native firebase, and after all the upgrade and testing, we are finding this issue giving a disclaimer.

Kindly consider adding to the README

**Comment by mikehardy** [comment]
@maria-tahir perhaps suggest where that would go best, as a user? I agree it would be useful I'm just not sure where I'd put it, myself.

**Comment by maxkomarychev** [comment]
hey @mikehardy , thanks for the amazing work you're doing!

I wonder what was the scale of troubles dragging notifications module from 5 to 6?
Is there any work being done at the moment or planned?
Anything community can help with?

**Comment by Ehesp** [comment]
@maxkomarychev It's a massive job, especially given how out of date the underlying SDKs are.
