### ISSUE TITLE
Firebase auth native sdk has not been included

### ISSUE THREAD

**Issue by egunsoma** [invertase/react-native-firebase#246]
I'm in the middle of the migration from v1 to v2. I've done all the steps described for Android, but still I get this error: 

**Firebase auth native sdk has not been included in your build.gradle - auth methods have been disabled.**

### Environment

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): 23
4. React Native version (e.g. 0.45.1): 45
5. RNFirebase Version (e.g. 2.0.2): 2

**Comment by Ehesp** [comment]
You're trying to use auth methods in your app, but not imported the
RNFirebaseAuth module in your MainApplication.

**Comment by Salakar** [comment]
Specific doc link for this can be found here: http://invertase.io/react-native-firebase/#/installation-android?id=_2-link-rnfirebase
