### ISSUE TITLE
Update Docs for installation on react-native 0.60

### ISSUE THREAD

**Issue by AmeerHamzaRiaz** [invertase/react-native-firebase#2463]
## Documentation Feedback

Hello, I'm confused on how to setup RNFirebase with react-native 0.60.4,
After running `npm install --save react-native-firebase`, it did not got autolinked.
So I ran `react-native link react-native-firebase`
It works fine, but now I'm getting following warning when run `react-native run-android`

```
D:\App>react-native run-android
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - react-native-firebase (to unlink run: "react-native unlink react-native-firebase")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

```

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You do not need to link, auto-link does work but only with the most current versions. You did not follow the template, so I will close this as I can't really help.

You can examine this script to see a complete / functional install on RN60 though https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by mikehardy** [comment]
To be clear on one thing - there is a change on the tip of the v5.x.x branch that is unreleased (it will be in 5.5.7) that allows for better library specification for AndroidX in react-native 0.60 - I use the branch reference as my dependency currently: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh#L12

https://github.com/invertase/react-native-firebase/pull/2476
