### ISSUE TITLE
Firebase Phone Auth returning a null verificationID & no more SMS codes after first try

### ISSUE THREAD

**Issue by alittletf** [invertase/react-native-firebase#2465]
The first time I ran signInWithPhoneNumber, I was able to get the verificationID in the confirmResult callback. However, I wasn't fully finished writing the code to verify the SMS code So i just console logged the confirmResult callback which is where I saw the verificationID present.

When I finished the confirmResult.confirm(verificationCode) part, I went into the firebase console and deleted myself to what I thought would 'restart' the process.

I ran it again and now i am getting null in the verificationID property of confirmResult object, no new SMS code, and using the original SMS code leads to a 'Cannot create PhoneAuthCredential without either verificationProof, sessionInfo, or temporary proof' error.

Does deleting a user in the firebase console not allow them to go back through and get a new verificationID/SMS code when using phoneAuth? I am confused why it was there the first time and null every time after.
RN 0.58.5
RNF 5.2.2

Response I get back from Firebase:
![image](https://user-images.githubusercontent.com/17679691/62754042-fabf3480-ba22-11e9-9d67-c10b77ed5a43.png)

**Comment by mikehardy** [comment]
I do that all the time, and it works for me to auth with the same phone number. I use current versions though. I use pretty much the code on the rnfirebase.io docs site to do this, but I use v5.5.6 and the most up to date firebase sdks, so I'm not sure about the old versions. I can say it should work though it is difficult to set everything up correctly. If you continue to see the issue please follow the full template and open a new issue

**Comment by alittletf** [comment]
@mikehardy When you auth with the same phone number again, do you always get a verification ID? I am actually now wondering that since I am on Android it was Auth'ing automatically and a verification ID was not necessary

**Comment by mikehardy** [comment]
@alittletf not sure, you'd have to test it - for me the verification codes have no value after auth, and if auth was automatic then for me the code is throw-away, I've never had my app pay attention to it really other than (when first integrating auth) console.logging it out of curiosity

**Comment by alittletf** [comment]
@mikehardy Gotcha, ok well then maybe it was working all along and Im being a doofus about it. Thanks for the reply!

**Comment by mikehardy** [comment]
If you haven't done messaging and notifications etc, especially the background / silent-push stuff, be prepared for real doofus-ness :-). Seems like every bit of that stuff held an "interesting" surprise. This stuff is all just complicated and near as I can tell there's not much way to make it easier other than really tiny increments of feature integration with really thorough verification. Good luck!

**Comment by aliasad106** [comment]
@mikehardy this happens only when the very first time sms code wasn't verified . And then we resend the sms. After that firebase sends verificationID as `null`

**Comment by mikehardy** [comment]
@aliasad106 not really an answer but phone verification is a hot topic right now - and I'm going to cross-link #2895  and maybe #2543 - there's a bit of a tangle here with phone auth issues at the moment, perhaps those are of interest though they didn't seem the same to me, might be best to log an issue with the full template information as this one was missing it originally
