### ISSUE TITLE
How to get auto verified confirmation code in android.

### ISSUE THREAD

**Issue by abhi-nahi** [invertase/react-native-firebase#2466]
## Issue

Describe your issue here

Hello there, I need to show the auto fetch confirmation code in my UI for android device but I did not find anything which can provide me what I wanted. Can you please help me. 

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You didn't follow the template - but I can say the example code for phone auth on the rnfirebase.io site contains an example that does what you want

**Comment by abhi-nahi** [comment]
I might have missing something but I didn't find anything in the template. Let me know if I am looking it in wrong place. 
I am following this : 

[https://rnfirebase.io/docs/v5.x.x/auth/phone-auth#3.-[Android]-Handle-Auto-Verification](https://rnfirebase.io/docs/v5.x.x/auth/phone-auth#3.-[Android]-Handle-Auto-Verification)

**Comment by mikehardy** [comment]
I think the verify example shows it more clearly? https://rnfirebase.io/docs/v5.x.x/auth/phone-auth#Example

**Comment by mikehardy** [comment]
and by "didn't follow the template" I mean you logged an issue without providing any of the detail about your setup that we need to make conclusive statements (version numbers, gradle configs etc etc)
