### ISSUE TITLE
firebase.auth().currentUser returns null

### ISSUE THREAD

**Issue by Tinmania2018** [invertase/react-native-firebase#2474]
## Issue

I'm having a hard time getting this to work. I have an app build with react-native and I am using a Firebase database. I use react-native-firebase to try to retrieve the current user. The user can sign up/sign in and everything works as expected so there is no problem here (this does not use react-native-firebase, if needed I can post my auth script here)
I have a "add place" page, on this page users upload a photo with some data to the firebase database. On another page users can view this place with the photo and extra data. I would now like to store the Firebase user UID with the photo in the database as well. The idea is to check wether the current signed in user is equal to the user UID stored with the image, if so a delete button is shown so only the user that uploaded the picture can remove it.

On my authentication screen I have added the following;

`    
import firebase from 'react-native-firebase';

...

componentDidMount() {
              console.log("ComponentdidMount() Called.");    
            this.FirebaseID = firebase.auth().currentUser
            console.log("FirebaseID =", this.FirebaseID);   
            console.log("current user =", firebase.auth().currentUser);
            console.log("Firebase all =", firebase.auth()); 
        this.props.onAutoSignin();
    }`

I have added the above code also to my add place page to check whatever information would be shown in the React Native Debugger logs. Only with the Firebase all rule I can view information about the logged in user, however user and current user remain null. 

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

No I have not

#### `android/build.gradle`:

```groovy
   dependencies {
         ......
        classpath 'com.google.gms:google-services:3.2.1'
```

#### `android/app/build.gradle`:

```groovy
dependencies {
    implementation project(':react-native-firebase')

    ...

    // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation "com.google.firebase:firebase-core:16.0.9"
    implementation "com.google.firebase:firebase-auth:16.0.2"
```

#### `android/settings.gradle`:

```groovy

...

include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')

...

```

#### `MainApplication.java`:

```java

...

import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.auth.RNFirebaseAuthPackage;

...

  protected List<ReactPackage> getPackages() {
    // Add additional packages you require here
    // No need to add RnnPackage and MainReactPackage
    return Arrays.<ReactPackage>asList(
...
      new RNFirebasePackage(),
 
...
      new RNFirebaseAuthPackage()


```

#### `AndroidManifest.xml`:

```xml
No reference to RNFirebase here
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
      Memory: 618.70 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 25.0.1, 26.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.1
        System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.6 => 0.58.6 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1```

<!-- change `[ ]` to `[x]` to select an option(s) -->

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [X] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
Sorry I can't find this, how can I check easy? 
- **`Firebase` module(s) you're using that has the issue:**
auth? 
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

So in short, I want to find out the current user and upload this as extra information to the Firebase database to user on a different view but I am unable to get the correct information with firebase.auth().currentUser. 

<!-- Thanks for reading this far down ❤️  -->
<!-- High quality, detailed issues are much easier to triage for maintainers -->

<!-- For bonus points, if you put a 🔥 (:fire:) emojii at the start of the issue title we'll know -->
<!-- that you took the time to fill this out correctly, or, at least read this far -->

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
You shouldn't use `currentUser` to determine whether the user is signed in or not. The docs recommend using `onAuthStateChanged` instead: https://firebase.google.com/docs/auth/web/manage-users#get_the_currently_signed-in_user

**Comment by Tinmania2018** [comment]
Thank you Ehesp. To me, with my lack of knowledge I am sure, it is not really clear where I have to find out the current user the way the docs mentioned. 

I used the code shown below and my react-native-debugger is showing the "No user is signed in" in the log. Am I doing something wrong? I am not sure if I should use this part of code in my SharePlace screen or not, also not sure if I should write it in the componentWillMount or a different place. 

The this.reset() is used for getting a clear screen without information when returning to this page from another tab. 

`    componentWillMount(){
        this.reset();
        firebase.auth().onAuthStateChanged(function(user) {
            if (user) {
                this.state.controls.FirebaseID = user
            } else {
              console.log("No user is signed in")
            }
          });
    }`

**Comment by Ehesp** [comment]
Try this:

```js
class MyScreen extends React.Component {
    constructor() {
		this.state = {
			user: null,
			loading: true,
		};
	}

	componentDidMount() {
		firebase.auth().onAuthStateChanged(function(user) {
			if (user) {
				this.setState({ user });
			} else {
				this.setState({ user: null });
			}
			
			if (this.state.loading) {
				this.setState({ loading: false });
			}
		});
	}

	render() {
   		if (this.state.loading) return null;

		if (!this.state.user) return <Text>Please login</Text>;

		return <Text>Welcome {this.state.user.uid}</Text>
  }
}
```

Note you need to call `this.setState` to trigger the component to reload.

**Comment by amit-bs23** [comment]
What if I want to get the current user token I have to use currentUser but currentUser is null at that moment `auth().currentUser?.getIdToken();` How can I resolve this?

**Comment by surafelbm** [comment]
@amit-bs23, were you able to resolve this I am also currently facing the same issue where I am trying to access getIdToken()
