### ISSUE TITLE
Build fail if uncomment use_frameworks! in Podfile

### ISSUE THREAD

**Issue by gyfelton** [invertase/react-native-firebase#248]
### Environment

1. Target Platform (e.g. iOS, Android): iOS
2. Development Operating System (e.g. macOS Sierra, Windows 10): MacOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): XCode 8.3, Cocoapods 1.2.0
4. React Native version (e.g. 0.45.1): 0.46.2
5. RNFirebase Version (e.g. 2.0.2): 2.0.2

### Step to reproduce

1. Create a new project by `react-native init` in a folder, navigate to the new react-native project i terminal
2. `cd ios` then `pod init`
3. do `npm install --save react-native-firebase` according to installation guide
4. `vim ios/Podfile` then add Pods according to installation guide 
5. Open `.xcodeworkspace` file and make sure the project build
6. Now go to Podfile and uncomment the `use_frameworks` 
7. Build again, this time there should be "React/*.h" header file not found error

This could potentially stop developer from building Swift project or use pods that written in Swift?

Not blocking my project but I just want to raise this issue early.

**Comment by Salakar** [comment]
Consolidating into #252 - closing.
