### ISSUE TITLE
🔥[Analytics] logEvent error in native ios code

### ISSUE THREAD

**Issue by rsouthgate** [invertase/react-native-firebase#2488]
## Issue

I've got a redux middleware attempting to log any custom actions as events to analyics:
```
import firebase from "react-native-firebase";
...
firebase.analytics().logEvent(action.type, { payload: action.payload });
```
---

There are no errors within the JS but I noticed recently when running from xCode the following errors popping up:

[Firebase/Analytics][I-ACS035001] Cannot create Value type with unsupported value. The Value has to be NSNumber or NSString. Value: {
    searchText = "";
}

I get a bunch of different errors for different types of payloads being passed to logEvent, but your documentation indicates that the param to logEvent can be an object... so I'm wondering what I should be doing here?

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PayX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PayX
  pod 'Firebase/Core', '~> 5.20.2'
  pod 'Firebase/Analytics', '~> 5.20.2'
  pod 'Firebase/RemoteConfig', '~> 5.20.2'
  pod 'GoogleIDFASupport', '~> 3.14.0'
  pod 'Fabric', '~> 1.10.1'
  pod 'Crashlytics', '~> 3.13.1'
end

# React-Native is not great about React double-including from the Podfile
post_install do |installer|
  # This fixes the problems with headers not found
  system("mkdir -p Pods/Headers/Public/FirebaseCore && cp Pods/FirebaseCore/Firebase/Core/Public/* Pods/Headers/Public/FirebaseCore/")

  installer.pods_project.targets.each do |target|

    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
```

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
      Memory: 113.30 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 25.0.2, 27.0.3, 28.0.0, 28.0.0, 28.0.2, 28.0.3
        System Images: android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7
      react-native: 0.56.0```

<!-- change `[ ]` to `[x]` to select an option(s) -->

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 5.20.2
- **`Firebase` module(s) you're using that has the issue:**
  - Analytics
- **Are you using `TypeScript`?**
  - N
  
</p>
</details>


<!-- Thanks for reading this far down ❤️  -->
<!-- High quality, detailed issues are much easier to triage for maintainers -->

<!-- For bonus points, if you put a 🔥 (:fire:) emojii at the start of the issue title we'll know -->
<!-- that you took the time to fill this out correctly, or, at least read this far -->

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by IljaDaderko** [comment]
Hey @rsouthgate, param can indeed be an object (that is the second argument of `logEvent`), however event name needs to be either a string or a number https://rnfirebase.io/docs/v5.x.x/analytics/reference/analytics#logEvent

I'm looking at your error and I think something might be wrong with `action.type`. Can you console log it above your `logEvent` and confirm that it is a string or a number and not `null` / `undefined` or object.

Second idea I can suggest is to keep your parameter object flat i.e. don't nest more objects in there (see example below), but this is just a guess.

Valid code would look like this for example

```js
firebase.analytics().logEvent("submit_search", { searchText: "" });
```

Also, version of firebase you specified `5.20.2` relates to firebase native cocoapod, not this library. Current stable version for react-native-firebase is `5.5.6`. Is that what you are on?

**Comment by rsouthgate** [comment]
Hi @IljaDaderko. Sorry about the version number - I am indeed on 5.5.6... Here's some logging as captured by xcode:
```
2019-08-16 11:10:22.777 [info][tid:com.facebook.react.JavaScript] Log event get_remote_config_SUCCESS
2019-08-16 11:10:22.777110+1200 PayX[77129:3284113] Log event get_remote_config_SUCCESS
2019-08-16 11:10:22.777 [info][tid:com.facebook.react.JavaScript] Log payload
2019-08-16 11:10:22.777320+1200 PayX[77129:3284113] Log payload
2019-08-16 11:10:22.778 [info][tid:com.facebook.react.JavaScript] { requirePayeeAddressCapture: true, netcodeEnabled: true }
2019-08-16 11:10:22.777629+1200 PayX[77129:3284113] { requirePayeeAddressCapture: true, netcodeEnabled: true }
2019-08-16 11:10:22.781514+1200 PayX[77129:3284097] 5.20.0 - [Firebase/Analytics][I-ACS035001] Cannot create Value type with unsupported value. The Value has to be NSNumber or NSString. Value: {
    netcodeEnabled = 1;
    requirePayeeAddressCapture = 1;
}
2019-08-16 11:10:22.781683+1200 PayX[77129:3284097] 5.20.0 - [Firebase/Analytics][I-ACS016000] Event parameter value must be of type NSString or NSNumber. Type: __NSDictionaryM
```

There's a bit of noise there because console.log seems to get spat out twice but anyway... you can see the event name is `get_remote_config_SUCCESS` - a string.

Your second guess got me to the root of the problem: it appears by nesting the payload under a 'payload' key I'm making it not flat enough: `{ payload: { requirePayeeAddressCapture: true, netcodeEnabled: true }}` which when it gets to [Firebase/Analytics] seems to be a dictionary as far as I can tell from these messages. If I change my JS to `firebase.analytics().logEvent(action.type, action.payload);` then it stops complaining (at least when my payload is just those two keys in the example above.

**Comment by Ehesp** [comment]
On Android, the log event method takes a Bundle, which technically a nested object can be converted to... one for me to test.

On iOS however, it's more specific:

```
+ (void)logEventWithName:(nonnull NSString *)name
              parameters:(nullable NSDictionary<NSString *, id> *)parameters;
```

It only accepts an object/dict with a string or id, hence the error. I suggest we do an additional check on JS land to prevent a nested object being sent. This needs applying to v6 too.

**Comment by Ehesp** [comment]
Just pushed some test updates to analytics for v6: https://github.com/invertase/react-native-firebase/commit/35c18d67d399e8c794a31d64a91babb16909c756

If anyone wants to backport to v5 feel free to send a PR. Closing this off for now.
