### ISSUE TITLE
Storage utils getHttpUrlParts function has an invalid regex

### ISSUE THREAD

**Issue by tahasabih** [invertase/react-native-firebase#2489]
## Issue

Describe your issue here

The getHttpUrlParts(url) function in @storage/lib/utils.js has an invalid regex. This prevents release builds from happening since the minifier fails.

https://regex101.com/r/99E00o/2/
```
const parts = url.match(
    /\/b\/(?<bucket>.*)\.appspot.com\/o\/(?<path>[a-zA-Z0-9./\-_]+)(?<params>.*)/,
  );
```
---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
@Salakar

**Comment by Ehesp** [comment]
Hi @tahasabih 

The following command minifies fine on our end and successfully outputs a bundle:

`react-native bundle --entry-file=index.js --bundle-output=app.bundle --minify=true --dev=false`

Can you confirm the error and what command you're running please

**Comment by tahasabih** [comment]
Getting this error when I run it:
```
error node_modules/@react-native-firebase/storage/lib/utils.js: Invalid regular expression: /\/b\/(?<bucket>.*)\.appspot.com\/o\/(?<path>[a-zA-Z0-9./\-_]+)(?<params>.*)/: Invalid group in file node_modules/@react-native-firebase/storage/lib/utils.js at 33:26. Run CLI with --verbose flag for more details.
Error: Invalid regular expression: /\/b\/(?<bucket>.*)\.appspot.com\/o\/(?<path>[a-zA-Z0-9./\-_]+)(?<params>.*)/: Invalid group in file node_modules/@react-native-firebase/storage/lib/utils.js at 33:26
```

I am using `v0.2.3`.

The line here `https://github.com/invertase/react-native-firebase/blob/b40d44c57e81a4110cbb4e6204c400cb8f78b00a/packages/storage/lib/utils.js#L44` is the issue and can be verified by running the regex in any js context (incl browser console) where it throws an error.

**Comment by Ehesp** [comment]
@tahasabih 	could you try to locally modify it for us to this:

```js
  const parts = url.match(
    /\/b\/(.*)\.appspot.com\/o\/([a-zA-Z0-9./\-_]+)(.*)/,
  );
```

Looks like the grouping on the regex is erroring on your environment for some reason, and they're not being used anyway.

**Comment by tahasabih** [comment]
@Ehesp yes this one works!

**Comment by technoplato** [comment]
Hey @Ehesp I came across this and am trying to learn - why do you think this would error on particular environments and what do you mean when you say, "they're not being used anyway?"

Thanks for the tip to fix!

**Comment by Ehesp** [comment]
The original regex contained group names (`?<bucket>`) which are used to help pluck out matches from a string and give them a specific name (rather than an array index). The code using the string matches regex, but doesn't use the groups/matches of it.

As for why it fails, well group names are a newer regex feature (which should be supported in the RN environment). The only reason I can think of why this fails is because @tahasabih was using [Hermes](https://facebook.github.io/react-native/docs/hermes/), which is it's own JavaScript engine which doesn't support group names.

**Comment by technoplato** [comment]
@Ehesp Thanks for taking the time to explain, that make sense.
