### ISSUE TITLE
React Native / Firebase compatibility chart out of sync between npmjs.com and doc site

### ISSUE THREAD

**Issue by tjann** [invertase/react-native-firebase#2492]
## Documentation Feedback

The RN / Firebase charts are out of sync:

https://www.npmjs.com/package/react-native-firebase

https://rnfirebase.io/docs/v5.x.x/getting-started#Supported-versions---React-Native-/-Firebase

**Comment by mikehardy** [comment]
Root cause is that npmjs.com caches the README file from a release when it's released and the README file has not been updated

Could you make a PR to the README that just points the features section and the supported versions section to the right areas of rnfirebase.io ? That would help a lot
