### ISSUE TITLE
iOS push notifications method getDeliveredNotifications?

### ISSUE THREAD

**Issue by eatoncw** [invertase/react-native-firebase#2496]
I'm using version 5.20.1 - For iOS, looking through your documentation I'm finding the method `removeAllDeliveredNotifications`, but not a way to get all the delivered push notifications in the Notification Center, like the method `getDeliveredNotifications` (https://facebook.github.io/react-native/docs/0.55/pushnotificationios#getdeliverednotifications)

I'd expect to get an array of all existing notifications. 

Am I just not seeing this method, or something similar, in your documentation, or is it not a method you've included?

Thanks!

**Comment by IljaDaderko** [comment]
v5 doesn't have that function https://rnfirebase.io/docs/v5.x.x/notifications/reference/Notifications
But I believe you can use `getDeliveredNotifications` from rn?
