### ISSUE TITLE
Firebase console target users by language not working properly 

### ISSUE THREAD

**Issue by eanota** [invertase/react-native-firebase#2499]
My project suddenly not filter the user correctly by language, for example Now I have
Total users for android = **500** 
After applying filter by language is English = **100** 

after register new device with English language 
Total users for android = **501**
After applying filter by language is English = **100** 

**So I can not target these new devices.**
This happen only with this old project, I created a new FCM project and connected with the same react native app its working fine and this issue not exist 

After discussion with Firebase Support Team, they said the problem from **react-native-firebase** SDK 

**"react-native-firebase": "^5.2.2"**

**Comment by mikehardy** [comment]
No template. I'm curious for the details though. "problem from react-native-firebase" how? We can reopen if you follow the template
