### ISSUE TITLE
Admob banner ad are loading with delay

### ISSUE THREAD

**Issue by selvin007** [invertase/react-native-firebase#2500]
Hi,

i was using react-native-admob

Impression/request was 900-950 out of 1000

after switching to react-native-firebase admob

Impression/request is 350-400 out of 1000

significant drop

![image](https://user-images.githubusercontent.com/7314081/63272935-9c177780-c2ba-11e9-8100-0e9733c94562.png)

    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-firebase": "^5.5.6",

**Comment by Ehesp** [comment]
Anymore details? What request options? What banner sizes?

**Comment by selvin007** [comment]
Using MEDIUM_RECTANGLE, BANNER, SMART_BANNER all are having this issue
Below is the code

`const Banner = firebase.admob.Banner;
const AdRequest = firebase.admob.AdRequest;
const request = new AdRequest();

<TouchableWithoutFeedback
    onPress={() => firebase.analytics().logEvent('ad_click_home', {})}
>
    <Banner
        unitId={'xxxxx'}
        size={'MEDIUM_RECTANGLE'}
        request={request.build()}
        onAdLoaded={() => {
            this.setState({
                adLoaded: true
            })
        }}
        onAdFailedToLoad={(e) => {
            this.setState({
                adLoaded: false
            })
        }}
    />
</TouchableWithoutFeedback>`
