### ISSUE TITLE
Error: An internal error has occurred. [ API Key not valid. Please pass a valid API key.]

### ISSUE THREAD

**Issue by EhsanSarshar** [invertase/react-native-firebase#2506]
## Issue
react native firebase always return API Key not valid error.
even I have tried to re-download the google-service.json but still have the same problem
## Project Files
- Android: `android/app/google-services.json

## Environment
<p>

#### `App.js`:

```javascript

signIn = async () => {
     try {
             const confirmResult = await firebase.auth().signInWithPhoneNumber(this.state.phoneNumber)
    } catch (error) {
             alert(error)
   }

}
```

**`react-native info` output:**

```
 System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
    Memory: 1.84 GB / 7.69 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772
```

- **Platform that I am experiencing the issue on**:
  - Android

- **`react-native-firebase` version that has this issue:**
  - `^5.5.6`
  
</p>

**Comment by IljaDaderko** [comment]
Hi @EhsanSarshar could you please follow the issue template and provide more details about your use case.

**Comment by EhsanSarshar** [comment]
any help

**Comment by IljaDaderko** [comment]
This error is not related to `react-native-firebase`, it happens when something is wrong with Android set up i.e. make sure you have added all necessary data like debugKey and place `google-service.json` where it belongs. I'm afraid we can't help much here 😕

**Comment by EhsanSarshar** [comment]
@IljaDaderko I have followed the documentation. and every things are checked

**Comment by likern** [comment]
> @IljaDaderko I have followed the documentation. and every things are checked

I've came across with this several times.
Looks like this question is related - https://stackoverflow.com/questions/58654144/com-google-firebase-firebaseexception-an-internal-error-has-occurred-api-key

I don't know exact reason, but it looks like the problem is in firebase android native part.
For me helped that I opened project using Android Studio and run **clean** taks and later _installed_ and _run_ application through Android Studio.

All my other settings and code were correct.

**Comment by AGDV** [comment]
you must check google cloud console, find api section click it to see you have the right retriction enabled or not and check the SHA-1 if elease one or debug then compare it ith your json file in firebae app and also compate with json inside your android studio.

**Comment by omarakl** [comment]
I have the same problem in android studio with firebase (Java).
I tried to configure the version of google services at project level gradle and then syncing the project, it still doesn't work.
I tried also cleaning the project then rebuilding it, still doesn't work ... any solutions ?
