### ISSUE TITLE
How to deleteToken when user is offline

### ISSUE THREAD

**Issue by namvoeh** [invertase/react-native-firebase#2509]
## Documentation Feedback
I could not found a place to describe a solution for delete firebase token when user is offline.

for Android it works with this solution below
```
    firebase
      .iid()
      .delete()
```

while iOS does not work both 2 solution:
```
    firebase
      .iid()
      .delete()
```
and
```
    firebase
      .messaging()
      .deleteToken()
```

**Comment by IljaDaderko** [comment]
Looking in iOS source, it seems that this method is implemented correctly
https://github.com/invertase/react-native-firebase/blob/b792fcb9ef0c3386268dd4b448dbec69e699bf81/ios/RNFirebase/instanceid/RNFirebaseInstanceId.m#L10-L18

Do you see any errors when you call it?

Also, could you please re-fill your question using issue template and not documentation one, as it is hard to see what's wrong here without knowing more about your environment and detailed usage example.
