### ISSUE TITLE
react-native-firebase/ios/RNFirebase/admob/BannerComponent.h:1:9: 'React/RCTComponent.h' file not found

### ISSUE THREAD

**Issue by tomdaniel0x01** [invertase/react-native-firebase#251]
I follow all iOS installation steps and get this error.

### Environment

1. Target Platform (e.g. iOS, Android): iOS 8
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Xcode Version 8.3.3 (8E3004b)
4. React Native version (e.g. 0.45.1): 0.46.2
5. RNFirebase Version (e.g. 2.0.2): 2.0.2

**Comment by paulftw** [comment]
This error happens to me when I have use_frameworks! in my Podfile.
Also, do you added this to your Podfile:

```
  pod 'Yoga', :path => react_native_path + '/ReactCommon/yoga'
  pod 'React', :path => react_native_path, :subspecs => [
    'BatchedBridge',
    'Core',
  ]
```

**Comment by Salakar** [comment]
Consolidating into #252 - closing.

**Comment by tomdaniel0x01** [comment]
Thanks!

"If you are new to Cocoapods or do not already have React installed as a pod, then add Yoga and React to your Podfile as follows:"

In documentation that statement is a bit confusing because of the "If you are new to Cocoapods" part.
