### ISSUE TITLE
Firestore RIDICULOUSLY slow (on IOS)

### ISSUE THREAD

**Issue by smeekmeister** [invertase/react-native-firebase#2518]
Using react-native-firebase 5.5.6 both on Android & iOS (via CocoaPods current iOS SDK version 6.6.0.  As of today receiving snapshots is ridiculously slow (over 1 minute). I have logged this to Firebase support as well. But what puzzles me is that on Android everything is working lightning fast as it was before also on ios. So this tells me it's not the listener codebase. Updates to Firestore documents the same. Takes very long. Is there incompatibility between 6.6.0 and RNFirebase 5.5.6. Previously it worked. Also tested an upgrade to 6.7.0 just released but problem persists. I also cloned a previous version of the repo to test if the problem lies in the updates I have made but the previous version has it as well.

**Comment by mikehardy** [comment]
Strange - no report of it from their side https://status.cloud.google.com/ as a service disruption.

I am not aware of compatibility issues, and I have read the release notes on the iOS SDKs. I've been using/testing 6.6.0 Pods all week and 6.7.0 since yesterday, nothing seemed off to me.

**Comment by smeekmeister** [comment]
Isolated a simple test in the app, with a separate screen that triggers a listening process.
Hereunder the listener that is wrapped in the render component.

const DbfAssetsListener = ({ children }) => {
    const language = useSelector((state) => state.user.settings.language)

    const [isLoading, setIsLoading] = useState(true)
    const [records, setRecords] = useState([])
    const unsubscribe = useRef(null)
    console.log('in assets listener')
    useEffect(() => {
        if (unsubscribe.current) {
            unsubscribe.current()
            setIsLoading(true)
            setRecords([])
        }
        unsubscribe.current = queries.assets().onSnapshot((docs) => {
            setIsLoading(false)
            console.log(transformDocs(docs))
            setRecords(transformDocs(docs))
        }, (error) => console.log('Dbf Assets Listener', error))
        console.log(unsubscribe.current)
        return () => {
            console.log('cleaning up')
            unsubscribe.current()
        }
    }, [])
    const assets = React.useMemo(() => translate(records, language), [records, language])
    return children({ isLoading, assets })
}

export default DbfAssetsListener

From the moment of subscription (console.log(subscribe current) until I get the snapshot (console.log (transform(docs). It takes on average 1.5 minute ????. On android less than 1 second

**Comment by mikehardy** [comment]
https://github.com/firebase/firebase-ios-sdk/releases/tag/Firestore-1.4.5

not sure if that is a thing or not, but for unrelated reasons I just did a pod outdated on my project (already moved to 6.7.0 pods) and saw firestore was outdated, then checked the release notes

```
* Fix connectivity monitor redispatching.

In #3467, we changed the connectivity monitor to take callbacks from
SCNetworkReachability on the main thread but didn't make the
corresponding change to enqueue the notification back onto Firestore's
worker.

* Bump patch version

* CHANGELOG
```

**Comment by smeekmeister** [comment]
cleaned everything up, moved to 6.7.0 and seems back ok. strange. thx for looking into this.
