### ISSUE TITLE
Same Account automatically Logging in on 2 devices, if i have ever use the same account in the first device

### ISSUE THREAD

**Issue by muhammadmisbah** [invertase/react-native-firebase#2519]
**Problem:**

I have 2 emulators on same MacBook (Genemotion and iPhone7) 
Case 1.
I have **user1**
Step 1: Login the user1 on Android and then signout now i have loging page on android.
Step 2: Login the user1 on iPhone => it also logged in on Android

Same happen if in this case iPhone was first.

I have **user1** and **user2**
Case 2:
Step 1: Login the user1 on Android and then signout then Login the user2 on Android now i have Dashboard page on Android.
Step 2: Login the user1 on iPhone => it also logged in on Android and replace the user2 to user1.

Same happen if in this case iPhone was first.

it's like they are synced to each other

### **It Keeps Previous cache and check state if user hits login from anywhere then it gets fired .onAuthStateChanged()**

I read somewhere to remove cache I don't remember where from i read that adding this code in your AppDelegate.m will clear signing cache your issue but it didn't work for me.

  ```
NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
  if (![defaults boolForKey:@"notFirstRun"]) {
    [defaults setBool:YES forKey:@"notFirstRun"];
    [defaults synchronize];
    [[FIRAuth auth] signOut:NULL];
  }
```

Previously I was using
```
"react-native": "0.55.4",
"react-native-firebase": "4.3.8",

```
Pod versions
```
pod 'Firebase/Core', '~> 5.3.0'
pod 'Firebase/Auth', '~> 5.3.0'
pod 'Firebase/Database', '~> 5.3.0'
pod 'Firebase/Storage', '~> 5.3.0'

```

Now I upgraded
```
"react-native": "0.59.2",
"react-native-firebase": "5.5.5",

```
Pod versions
  ```
pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Database', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'
```
  
**Still facing same issue.**

**Comment by mikehardy** [comment]
careful with those versions, I believe you need RN0.59.3+ to use RNFBv5.4+

That should be a nearly trivial upgrade? (you should go to RN0.59.10 to get all the bugfix releases on that codeline really)

At that point you have also a quick upgrade to RNFBv5.5.6 and (the important part) you can move to the new 6.7.0 ios PODS and the newest android bom version (if you haven't converted to bill of materials style, it is quite nice for versioning the android deps, like so: 

```groovy

 implementation platform("com.google.firebase:firebase-bom:22.0.0")
    implementation "com.google.firebase:firebase-core"
    implementation "com.google.firebase:firebase-auth"
    implementation "com.google.firebase:firebase-analytics"
    implementation "com.google.firebase:firebase-perf"
    implementation "com.google.firebase:firebase-config"
    implementation "com.google.firebase:firebase-storage"
    implementation "com.google.firebase:firebase-dynamic-links"
    implementation "com.google.firebase:firebase-firestore"
    implementation "com.google.firebase:firebase-messaging"
    implementation 'com.crashlytics.sdk.android:crashlytics'
```

That way we make sure we waste no time troubleshooting code from March (I just checked https://firebase.google.com/support/release-notes/ios#version_5201_-_march_30_2019)

**Comment by muhammadmisbah** [comment]
It was my mistake, when i checked currentUser in Dashboard so it was null then I realised I wasn't turning off the real time Database listener for Online|Offline of user, that keeps pushing me inside the app
