### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/FirebaseApp;

### ISSUE THREAD

**Issue by techexe-code** [invertase/react-native-firebase#2520]
firebase import error, 
![Screenshot_1566823905](https://user-images.githubusercontent.com/8767521/63692178-ae4f6380-c82e-11e9-959e-7e61a5d33949.png)

**Comment by mikehardy** [comment]
no template

**Comment by techexe-code** [comment]
means, i didn't get you
