### ISSUE TITLE
Messaging: APNs out of sync after FCM updates

### ISSUE THREAD

**Issue by usrbowe** [invertase/react-native-firebase#2522]
## Documentation Feedback

I had an issue on iOS, in my app with `APNs` token not being registered with `FCM` token upon user log-out/log-in.

I'll try to explain flow of the app.

### Flow  ✅ 
1. User installs the app
2. Enable Push Notifications 
2.1 enabling push notifcations will trigger -> `didRegisterForRemoteNotificationsWithDeviceToken` and `APNS` token is properly registered to firebase along with FCM token.

### Logout Flow 🔴 
> This flow will break the APNs <=> FCM token
1. User log-out from app
1.2 We destroy FCM token `firebase.messaging().deleteToken();`.
1.3 Reload the JS 
2. App wil land on Login screen
3. User will login, but this time, he already allowed Push Notifications, so the `didRegisterForRemoteNotificationsWithDeviceToken` will not be called and FCM will not have `APNs` token. So the receiving of push notifications will be broken.

### Possible fixes I tried and worked:
A. call `firebase.messaging().ios.registerForRemoteNotifications()` every time user logs in.
B. call `firebase.messaging().requestPermission()`, which would turns annoying for users who did not enable push notification.

Is this something, which can be potentially added to documentation? Or I'm not doing the flow when log-out correctly.

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by usrbowe** [comment]
If possible, would be nice to know more details on this.
Basically restarting only `JS thread` + `cleaning FCM token`, will break the push notifications.

**Comment by unfrgivn** [comment]
Did you ever figure this out @usrbowe? I have the same issue right now and I appreciate your comments because I concur that calling `firebase.messaging().ios.registerForRemoteNotifications()` after generating a new FCM token works, but I don't know if this causes other issues.

I'm also confused because this says it was added to and fixed in v6, but I am on v5 and was under the impression v6 was not going to support push notes because that has spun off into a new package?
