### ISSUE TITLE
Confusing setup documentation 

### ISSUE THREAD

**Issue by prasadpilla** [invertase/react-native-firebase#2523]
## Documentation Feedback

https://rnfirebase.io/docs/v5.x.x/installation/initial-setup#Platform-Specific-Installation is confusing. I got stuck in the endless loop of issues while following this doc for 2 days. 

I am not very experienced with RN but fairly familiar. But I think the docs should be facilitating to new devs also.

I followed https://medium.com/@oakromulo/firebase-analytics-on-react-native-4b348466f025 and got it working within 50 mins. 2days vs 50min is huge.

Although this article has been mentioned in the refs, there's a very good chance that devs only refer to the official doc which is the primary source while integrating any lib.

Solutions I propose:

1. Let's see if we can add more details to the official doc to make it clearer and more explicit 2. Some way we can prominently guide devs to the community doc instead of the official one

#2 is probably not long term, just added as a possibility.

**Comment by IljaDaderko** [comment]
@prasadpilla Thank you for your feedback! We are working on a new version of `react-native-firebase` (v6) and along with it are re-writing / re-designing our documentation site as well.

Any chance you could review quick start guide https://invertase.io/oss/react-native-firebase/quick-start and let me know if it makes setup a bit easier? 

I believe these 2 sections are ones that you found hard in current documentation?
https://invertase.io/oss/react-native-firebase/quick-start/android-firebase-credentials

https://invertase.io/oss/react-native-firebase/quick-start/ios-firebase-credentials

**Comment by prasadpilla** [comment]
@IljaDaderko Sorry, I should have been specific. The platform-specific docs are the ones not clear enough https://rnfirebase.io/docs/v5.x.x/installation/ios. Thinking more about it, it probably just needs notes in one or two places. I'll open a PR for that. Closing this one.

And I did review the new quick guide, it's pretty neat. It's very clear with screenshots etc. Great work.

**Comment by jbschaff** [comment]
Started a new project using the new documentation and one line installation and now running in the simulator -- needed to do the following to get it running without errors: 

Added the following to AppDelegate.m --> 

```
@import Firebase;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure]; 
```


cd iOS 
pod install

cd ProjectDirectory
yarn run start
react-native run-ios
