### ISSUE TITLE
Build failed : Execution failed for task ':app:transformClassesWithMultidexlistForDebug

### ISSUE THREAD

**Issue by jeevankumarkanuganti** [invertase/react-native-firebase#2536]
* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

**Comment by Ehesp** [comment]
Please follow the issue template.

**Comment by hpelitebook745G2** [comment]
@Ehesp which one?
