### ISSUE TITLE
Firebase.crash().report() crashes the app

### ISSUE THREAD

**Issue by sourabhv** [invertase/react-native-firebase#254]
Calling `Firebase.crash().report(...)` throws error in `RNFirebaseCrash.h` with `assert(NO)`

```
RCT_EXPORT_METHOD(report:(NSString *) message) {   
    FIRCrashLog(message);
    assert(NO); 
}
```

Is it supposed to be like this?

### Environment

1. Target Platform: iOS 10.3 Simulator
2. Development Operating System: macOS High Sierra
3. Build tools Xcode
4. React Native version: 0.46.1
5. RNFirebase Version: 0.4.1

**Comment by Ehesp** [comment]
Well it is called crash for a reason :rofl: 

We shall check this out, seems strange!

**Comment by sourabhv** [comment]
Ok, great. Meanwhile I'm using `.crash().log()` and it works fine

**Comment by Salakar** [comment]
The firebase docs for report mentions: 

`This method should be used for unexpected exceptions where recovery is not possible.`

The official android firebase sdk crash `report` function throws immediately after calling report, but the ios one does not, so to keep the behaviour consistent on both platforms we added that assert on iOS to cause an uncaught exception leading to a crash.

If that makes sense?

**Comment by sroze** [comment]
That seems weird, as a developer, to hear that. There is therefore no way to log an `Error` in a simple way then? (including the stack)

**Comment by Salakar** [comment]
@sroze we're just proxying to the native firebase SDK's may seem weird but that is what they do :)
