### ISSUE TITLE
SMS code is always expired on real device iOS

### ISSUE THREAD

**Issue by jpudysz** [invertase/react-native-firebase#2541]
## Issue

Hello everyone, I'm trying to impelment SMS verification on iOS. I checked previous issues but it was only reported for Android. I would like to mention that i tried both methods from docs (https://rnfirebase.io/docs/v5.x.x/auth/phone-auth) with same result.

### What I would like to achieve?
SignIn already linked user with SMS provider

### What am I doing?
I created mobile app with anonymous accounts for every user.
I addedd multiple signup methods like Facebook, Google etc (these providers are working correctly) and SMS.
**I'm able to link anonymous account with SMS provider** but after signout I'm starting to encounter errors (details below).

Linking anonymous user with SMS provider (working as exptected)
```
 firebase
    .auth()
    .signInWithPhoneNumber(phoneNumber, Boolean(resend))
```
I'm saving `verificationId` from `confirmationResult`, redirecting user to other screen with input and after user enters verification code I'm using 
```
const credential = firebase.auth.PhoneAuthProvider.credential(verificationId, code)
user.linkWithCredential(credential)
```
Then I'm signingOut with firebase:
```
firebase.auth().signOut()
```
And signing again with new `verificationId` and `code` received by my iPhone:
```
const credential = firebase.auth.PhoneAuthProvider.credential(verificationId, code)
firebase.auth().signInWithCredential(credential)
```
---
Each time I'm receiving: `auth/code-expired` error
## Project Files
Everything is linked correctly, no need to paste my configs here as `auth()` package is available and all methods are working

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
pod 'Firebase/Core', '~> 6.2.0'
pod 'Firebase/Auth', '~> 6.2.0'
```

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 "react-native": "0.59.10",
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `5.5.6`
- **`Firebase` module(s) you're using that has the issue:**
  - `Auth`
- **Are you using `TypeScript`?**
  - `Y`
  
</p>
</details>

---

**Comment by jpudysz** [comment]
I checked your native code and it seems that:
- you're auto-linking user with `confiormationResult.confirm` method
- additionally, you're calling `signInWithCredential` underneath and that's why my `signIn` will always throw an error

Which is breaking other provider signup/signin flow

**Comment by Pardeep03315** [comment]
Facing same issue on android and ios both , anybody help please ???

**Comment by andikare** [comment]
anyone can fix this issue ?

**Comment by aadityapaliwal94** [comment]
@mikehardy I am still facing this issue. This is the case is with me. `signInWithCredential` method returns code expired for a user who already linked earlier.

**Comment by mikehardy** [comment]
@aadityapaliwal94 you are spamming issues. Stop.
