### ISSUE TITLE
Data-only message not received due to completion handler not being called

### ISSUE THREAD

**Issue by PiotrD-MR** [invertase/react-native-firebase#2545]
## Issue

Hello,

I'm having issue with data-only messages not being received in background on IOS. There are no problems with foreground app. 

In console log I can see this message:

``` 
Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
```

even though 

```- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  
  [[RNFirebaseMessaging instance] didReceiveRemoteNotification:userInfo];
}
```
is implemented.

I have tried updating the lib but it didn't help. It happens that I receive message when app is in background - it happens around 1/20 times.

Thanks for your support!

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:
```
 Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'App' do
  Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
    pod 'Braintree'
    pod 'Firebase/Core', '~> 5.20.1'
    pod 'Firebase/Messaging', '~> 5.20.1'
    pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 18.78 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.2 => 0.59.2 

```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 5.5.5
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
if I understand iOS power management correctly, background data-only messsage delivery is best-effort / non-deterministic. Your app may be woken for delivery but it might depend on user affinity for your app, how heavy your app is usually when handling messages, battery status on the device, power save mode on the device etc. If the device is plugged in, fully charged, and the app has seen interaction etc you have a better chance of seeing if it *would* work as a test.

**Comment by redexp** [comment]
I solved it on ios with calling `firebase.messaging().ios.registerForRemoteNotifications()`

**Comment by shekharskamble** [comment]
Hi @redexp, I used  firebase.messaging().ios.registerForRemoteNotifications() but my data-only remote notification is still not received when app is closed

**Comment by VanHop94** [comment]
> I solved it on ios with calling `firebase.messaging().ios.registerForRemoteNotifications()`

I tried but can not compile. It said ios is undefine

**Comment by VanHop94** [comment]
> I solved it on ios with calling `firebase.messaging().ios.registerForRemoteNotifications()`

I tried on simulator IOS 13 and still not work. When I press home button, iPhone doesn't receive my data

**Comment by redexp** [comment]
@shekharskamble I solved problem when app in background, not when it closed.
@VanHop94 as I remember push notifications not working on simulators.
Any way I'm not iPhone developer, I just found this method and it worked for me, sorry guys

**Comment by VanHop94** [comment]
> @shekharskamble I solved problem when app in background, not when it closed.
> @VanHop94 as I remember push notifications not working on simulators.
> Any way I'm not iPhone developer, I just found this method and it worked for me, sorry guys

Thank you. But Did you need to config APNS for firebase?
