### ISSUE TITLE
[v6][android] Installing module causes MultiDex warning

### ISSUE THREAD

**Issue by Ehesp** [invertase/react-native-firebase#2549]
Placeholder issue.

After installing `firestore` onto a fresh React Native project I get a multi-dex warning. Need to figure out if this can be prevented to improve the user installation process.

**Comment by mikehardy** [comment]
Not that I'm aware of. If you use the dexcount plugin to see where things are coming from there's just no way around it AFAICS unless you clip off android API support up to API19 if I recall (where they switched from Dalvik VM to ART)

I investigated it for my app and as soon as I add that dependency multidex is required

I *am* able to keep below 64k methods on the D8/R8 shrunken release version but only just barely and I don't count on it

https://github.com/KeepSafe/dexcount-gradle-plugin

**Comment by Ehesp** [comment]
Thanks @mikehardy - my initial thought was that, however even if it's not possible to "remove", I'm not sure what the best way to handle it is. From a new user perspective:

1. Open docs
2. Install `app` (generally won't cause the issue)
3. Go to module (e.g. Firestore), `yarn add` the module
4. Multidex error

For a new user, it seems as though it's an issue with this library as it's caused by adding the package. We can either:

- Add a step into the docs
- Ignore it and let the user figure it out
- Catch the error, and display a bespoke message (no clue if possible or a good idea)
- Look into ways to simplify the process of fixing it - e.g. set a flag inside of the `firebase.json` file which we read and install the dex plugin (if possible).

Would be interesting to hear some thoughts...!

**Comment by mikehardy** [comment]
🤔 in the Java code see if the Application is type of MultiDexApplication and if not emit a warning in debug pointing at documentation?

**Comment by mikehardy** [comment]
Or regex search the MainApplication.java for 'extends.w*MultiDexApplication' in javascript and do similar
