### ISSUE TITLE
Missing Documentation: AdMob

### ISSUE THREAD

**Issue by hofuchi** [invertase/react-native-firebase#255]
Navigating to the modules->AdMob page in the documentation shows "not found"

Link to the Docs
http://invertase.io/react-native-firebase/#/

Link to the AdMob (not found) Docs:
http://invertase.io/react-native-firebase/#/modules/admob

Photo:
![untitled](https://user-images.githubusercontent.com/9373942/28241643-1a368ace-695e-11e7-9fa9-6ec2bd28b800.png)

### Environment
2. Development Operating System:
      * Windows 10
5. RNFirebase Version:
      * v2.0.3

**Comment by bitfabrikken** [comment]
Disable your ad blocker :)

**Comment by hofuchi** [comment]
cheeky, Thanks. It's all good
