### ISSUE TITLE
using firebase.analytics() - Android App force closes

### ISSUE THREAD

**Issue by jeevankumarkanuganti** [invertase/react-native-firebase#2552]
import {firebase} from 'react-native-firebase';
let FirebaseAnalytics = **firebase.analytics();**

using **firebase.analytics()** in code , app gets force close.

Below versions used in my project:
"react-native": "^0.55.3",
"react-native-firebase": "^5.2.1",

**Comment by Ehesp** [comment]
Please follow the issue template, and provide some logs please.

**Comment by mikehardy** [comment]
Also worth noting - those releases are all more than a year old at this point I think? I would spend zero time investigating them and instead get my project to current (react-native 0.60.5, react-native-firebase 5.5.6, android firebase sdk bill of materials 22.1.0) before spending a second doing any troubleshooting
