### ISSUE TITLE
Notification not receiving when App is in focus

### ISSUE THREAD

**Issue by nileshprajapati007444** [invertase/react-native-firebase#2553]
**When my App is in focus (means open in device), I am not receiving push notification on tray.** 

I receiving push notification when app is fully closed and also receiving when app is in background.

I followed below link to fix, but still not fixed:
https://github.com/invertase/react-native-firebase/issues/1642

Can anyone help me as early as possible. It is my urgent task to fix.

Thank you in Advance.

Below is my AndroidManifest.xml file:

<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" package="com.mycompany.appname" android:versionCode="1" android:versionName="0.0.1">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" android:description="@string/camerapermission" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    
    <uses-permission android:name="com.android.vending.BILLING" />
    
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

    <application android:name="com.mycompany.appname.MainApplication" android:launchMode="singleTop" android:allowBackup="true" android:networkSecurityConfig="@xml/network_rules" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:theme="@style/AppTheme">

        <activity android:name="com.mycompany.appname.MainActivity" android:label="@string/app_name" android:screenOrientation="portrait" android:configChanges="keyboard|keyboardHidden|orientation|screenSize" android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id" />
        <activity android:name="com.facebook.FacebookActivity" tools:replace="android:theme" android:screenOrientation="portrait" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:label="@string/app_name" />

        <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />

    </application>

</manifest>

**Comment by vikrantshroti** [comment]
When app is in focus then it is react-native job to deliver notification else in all scenario if you had configured FCM, you will receive notifications.
This means you react-native-firebase is not proper.
You may have to implement messaging alongside notification from react-native-firebase package.
Check docs [here](https://rnfirebase.io/)

**Comment by nileshprajapati007444** [comment]
@vikrantshroti 

Can you say what configuration i may miss to configure ?

Let me know if you need any file or code to check from your-side.

**Comment by vikrantshroti** [comment]
So you are getting notification when app is in bg then your FCM set up on android client is right.
But not on react-native-firebase which leads to following checklist :
-  you added RNFirebasePackage, RNFirebaseNotificationsPackage, RNFirebsaeMessagingPackage in MainApplication.java file
-  you added RNFirebaseNotificationReceiever 
-  you might have to create different MessagingService, using your custom code to build notification and code from RNFIrebaseMessagingService.

I recommend to go through react-native-firebase messaging and notification documentation.

**Comment by nileshprajapati007444** [comment]
I fixed this issue by adding setChannelId & setSmallIcon in onNotification method.


this.notificationListener = firebase.notifications().onNotification(notification => {
      notification
        .android.setChannelId('test-channel')
        .android.setSmallIcon('ic_launcher');
      firebase.notifications().displayNotification(notification);
    })

Thanks.
