### ISSUE TITLE
🔥react-native-firebase/template 0.3.0

### ISSUE THREAD

**Issue by benoitdion** [invertase/react-native-firebase#2557]
## Issue

`npx @react-native-community/cli init --template=@react-native-firebase/template`

throws 

```
Using React Native Firebase version '0.3.0'
 -> Detecting Firebase modules...

[!] Invalid `Podfile` file:
[!] Invalid `RNFBApp.podspec` file: No such file or directory @ rb_sysopen - ../node_modules/@react-native-firebase/app/ios/../package.json.

 #  from ../node_modules/@react-native-firebase/app/ios/RNFBApp.podspec:3
 #  -------------------------------------------
 #  require '../firebase_json'
 >  package = JSON.parse(File.read(File.join(__dir__, '..', 'package.json')))
 #
 #  -------------------------------------------
.

```
---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 0.3.0
- **`Firebase` module(s) you're using that has the issue:**
  - `N/A`
- **Are you using `TypeScript`?**
  - `/NA`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
I'll try this out and get back. There was previously an issue with the CLI and a mono-repo setup but I think a fix went into it recently which may impact this.

**Comment by benoitdion** [comment]
thanks @Ehesp!

**Comment by Ehesp** [comment]
All seems to be working on my end/testing. Please ensure all CLI (including global) are up-to-date, as it seems the older versions cause issues.
