### ISSUE TITLE
🔥 Android installation not working despite following all instructions

### ISSUE THREAD

**Issue by michaelmorar** [invertase/react-native-firebase#2559]
🔥
## Issue 

I have meticulously followed the thorough installation instructions for Android but continue to encounter this error when trying invoking this function: 

firebase.messaging().hasPermission() 

"Possible Unhandled Promise Rejection (id: 0):
Error: You attempted to use a firebase module that's not installed on your Android project by calling firebase.messaging()"

I would appreciate your help because I am believe in your project and I am excited to use it for my freelance app. I am also happy to contribute in any way I can - including contributing to your documentation. 

Snippets of my code: 
import firebase from 'react-native-firebase';
...
   firebase.initializeApp(
      // use platform specific firebase config
      Platform.OS === 'ios' ? iosConfig : config.getAndroidConfig(),
    );
...
const enable = await firebase.messaging().hasPermission()

Describe your issue here:
MAIN ERROR : Error: You attempted to use a firebase module that's not installed on your Android project by calling firebase.messaging()"

Background info: 

1) Android Studio throws this error- not sure if this is relevant but sounds severe:

- Compilation is not supported for following modules: react-native-firebase. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

2) getPackages() method in MainApplication.java has an Override annotation. This causes a compilation error due to the fact that it does not seem to override anything. I had to comment out that annotation before the project could build.
---

#### `android/build.gradle`:
```
buildscript { 
    repositories {
        mavenLocal()
        google()
        jcenter()
    }

    dependencies {
        classpath('com.android.tools.build:gradle:3.4.1')
        classpath 'com.google.gms:google-services:4.2.0'

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
    }
```
#### android/app/build.gradle: 
```
dependencies {
    implementation project(':react-native-firebase')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-reanimated')
    implementation project(':react-native-localize')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-gesture-handler')
    implementation project(':react-native-config')
    implementation 'com.google.firebase:firebase-analytics:17.2.0'
    implementation project(':@react-native-community_async-storage')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.google.firebase:firebase-messaging:20.0.0'

    implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation "com.google.firebase:firebase-core:16.0.9"


apply plugin: 'com.google.gms.google-services'
```
#### gradle.wrapper.properties ***

distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

#### MainApplication.java 
```
public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }

  //@Override HAD TO comment this out to avoid compiler error (no superclass method)
  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new RNFirebasePackage(),
            new RNFirebaseMessagingPackage(),
            new RNFirebaseNotificationsPackage()
    );
  }
}

```
I have converted to AndroidX 

#### `android/settings.gradle`:
```
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
include ':react-native-reanimated'
project(':react-native-reanimated').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-reanimated/android')
include ':react-native-localize'
project(':react-native-localize').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-localize/android')
include ':react-native-linear-gradient'
project(':react-native-linear-gradient').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-linear-gradient/android')
include ':react-native-gesture-handler'
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gesture-handler/android')
include ':react-native-config'
project(':react-native-config').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-config/android')
include ':@react-native-community_async-storage'
project(':@react-native-community_async-storage').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/async-storage/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.spree2">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
             android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>
</manifest>
```
## Environment

**`react-native info` output:**
```
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 1.39 GB / 15.38 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 23.0.1, 26.0.1, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-native: ^0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
5.5.6
- **`Firebase` module(s) you're using that has the issue:**
  - Messaging
- **Are you using `TypeScript`?**
  - N
  

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
If you are using react-native 0.60+ and are having problems installing dependencies you can copy the style used for each dependency in this demo react-native-firebase install script https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

I do not demo messaging there, but the android dependency install is the same for each package (auth, analytics, etc etc) so the style should work

If there is something it does that is not in the docs at rnfirebaseio.com I'll be surprised but a PR would be welcome

**Comment by michaelmorar** [comment]
HI Mike - thank you, I will try that. I've been poring over the documentation and normally, I find these kinds of errors to be the result of my having missed a step. However, in this case, I just cannot find that step. I will keep at it and feed back when I've solved my problem. 

Just a question though: should I have had to comment out the @override in getPackages() method in the MainActivity class? I feel like I need to eliminate that as an option.

**Comment by mikehardy** [comment]
No the `@override` shouldn't do it. It doesn't look to me like you're actually including react-native-firebase's messaging component, in MainApplication.java. Definitely check out the scripted install stanzas in that demo script I linked. It will give you the feel for the things needed for each component. That said the reason I don't demo messaging/notifications is because it needs so much more to be thorough (all documented on rnfirebase.io but it's a lot - headless tasks, listeners, receivers etc etc)

**Comment by michaelmorar** [comment]
Hi Mike - thank you so much for the advice. I have managed to clear the error. The problem came dow to a basic but unnoticeable error in my getPackages() method in MainActivity.
