### ISSUE TITLE
Analytics : VALUE data type is it number or string?

### ISSUE THREAD

**Issue by hotaryuzaki** [invertase/react-native-firebase#2567]
## Issue

in debug view i succeed sent VALUE data as number, but i don't understand why in Events menu accumulated value is 0 (even for few days data)

i am confused with Firebase guide for VALUE data type, because it said as DOUBLE here: https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event.html#ECOMMERCE_PURCHASE

but it said as STRING here:
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Param.html#VALUE
it is mention to use putDouble(String, double), is it still STRING or change to DOUBLE?
How to set DOUBLE in JS? because if using toFixed() it will change to STRING.

Or maybe im in the right track sent it as number, but why accumulated VALUE and purchase is 0???? 

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
It can be a `string` or `number` in JavaScript land. We convert the values to [a Bundle](https://github.com/invertase/react-native-firebase/blob/v5.x.x/android/src/main/java/io/invertase/firebase/analytics/RNFirebaseAnalytics.java#L37) which maps to `putString` or `putDouble`.

Note for myself; apparently v6 accepts a `boolean` so need to investigate that.

**Comment by lysontrung1706** [comment]
@hotaryuzaki 
Have you solved your problem yet?
I got same issues
My dashboard  can not show Product revenue & Average Price for add_to_cart event
my currency is 'VND'

**Comment by hotaryuzaki** [comment]
No.
Until now the second and third problem still exist.
 I'm really sure my code is right.

**Comment by lysontrung1706** [comment]
> No.
> Until now the second and third problem still exist.
> I'm really sure my code is right.

in my case
my dashboard can show Accumulated VALUE in ecommerce_event event , but in add_to_cart event not

**Comment by hotaryuzaki** [comment]
Oh. Are you already check what is the different with that?
So weird.

**Comment by lysontrung1706** [comment]
> Oh. Are you already check what is the different with that?
> So weird.

I checked many time, nothing different

**Comment by hotaryuzaki** [comment]
And I already verified my code, and I didn't know what was the problem.
So weird.

Which RNFirebase version do you use?

**Comment by lysontrung1706** [comment]
> And I already verified my code, and I didn't know what was the problem.
> So weird.
> 
> Which RNFirebase version do you use?

I used "react-native-firebase": "5.5.5",

**Comment by silviukreactive** [comment]
Hello everyone! This topic is closed, but I can't find the solution in this thread. What was it, in the end? (I have the same issue in my project). Thanks!

**Comment by mikehardy** [comment]
The solution was I think to not spend too much time looking at issues closed approximately a year ago related to very old code :laughing: - but seriously! Make sure you are on current versions and if the problem happens post a new issue
