### ISSUE TITLE
signInWithPhoneNumber getting error 

### ISSUE THREAD

**Issue by sombizbuzzz** [invertase/react-native-firebase#2576]
Hello everyone, I'm trying to impelment  Phone Number Auth verification on mobile app. 
What I would like to achieve?

**Illegal callback invocation from native module. This callback type only permits a single invocation from native code**.

   ` makeFireBaseCall = async (sendPhoneNumber) => {

    try {
      firebase
        .auth()
        .signInWithPhoneNumber(sendPhoneNumber)
        .then((confirmResult) => {

          this.setState({
            confirmResult,
            message: 'Code has been sent!',
            step: 2,
          });
          this.goToOtpScreen();

        })
        .catch((error) => {
          this.setState({
            message: `Sign In With Phone Number Error: ${error.message}`,
          });
          Toast.show(error.message, Toast.SHORT);
        });

    } catch (error) {
      Toast.show(error.message, Toast.SHORT);
    }
  }
`

 "react-native-firebase": "^5.5.4",

  `  # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.3.0'
  
  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/Database', '~> 6.3.0'
  pod 'Firebase/Functions', '~> 6.3.0'
  pod 'Firebase/DynamicLinks', '~> 6.3.0'
  pod 'Firebase/Firestore', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/RemoteConfig', '~> 6.3.0'
  pod 'Firebase/Storage', '~> 6.3.0'
  pod 'Firebase/Performance', '~> 6.3.0'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.2'`
  
![Simulator Screen Shot - iPhone Xs - 2019-09-05 at 12 59 25](https://user-images.githubusercontent.com/43329978/64825304-68d6b880-d5da-11e9-8695-3bbff1294eef.png)

**Comment by HubertRyanOfficial** [comment]
How did you put your sendPhoneNumber?

**Comment by sombizbuzzz** [comment]
+91 mob number (country code mob number )

**Comment by parthya** [comment]
This occurs while trying to open the CAPTCHA screen on WebView. Worked a few times for me, but now getting the error everytime.

**Comment by saurabh-dedhia** [comment]
I'm facing the same issue. For me, the issue is on iOS simulator when I try to live reload the modified code and then try to login. But if I kill the app and try again then it works fine always. Not sure how to resolve this issue. Also, I'm not able to reproduce this on an actual device.

**Comment by rahul-rijhwani-openxcellinc** [comment]
Hi @sombizbuzzz  @parthya @saurabh-dedhia  

Did you guys find out any solution ?

**Comment by kunalsolanki1992** [comment]
+1

**Comment by parthya** [comment]
> Hi @sombizbuzzz @parthya @saurabh-dedhia
> 
> Did you guys find out any solution ?

This is Simulator specific random issue. No user got this on actual devices.

**Comment by rahul-rijhwani-openxcellinc** [comment]
Thanks @parthya,
It works !

**Comment by Seanmclem** [comment]
> > Hi @sombizbuzzz @parthya @saurabh-dedhia
> > Did you guys find out any solution ?
> 
> This is Simulator specific random issue. No user got this on actual devices.

Also, even in the simulator, it doesn't seem to actually cause an issue
