### ISSUE TITLE
Set custom sound in notification

### ISSUE THREAD

**Issue by HubertRyanOfficial** [invertase/react-native-firebase#2579]
I'm trying to use setSound ('notification.mp3'), but it doesn't work to put a custom notification sound in react native firebase 5.4.0, how can I do this?

*

Already tried to put a require ('path'),
but it doesn't work.

**Comment by Ehesp** [comment]
This isn't very well documented sorry. 

It needs to be inside of a `res/raw` directory inside of your Android build. It's not possible to provide a sound from a JS file.

**Comment by HubertRyanOfficial** [comment]
Putting my sound file in res/raw it works?

**Comment by anooj1483** [comment]
By keeping the file in res/raw, it will work when app is in foreground. But if app is in background, app is playing default notification sound. Tried sending sound parameter with custom sound name. Still it is playing default (only in background state).

**Comment by kalpesh9896** [comment]
If your android channel id is the same (AndroidManifest.xml => default_notification_channel_id and notif.android.setChannelId('Test Notification')), in both ways(in the background and in foreground) custom notification tone will be work.

**Comment by ankitbaid11326** [comment]
@kalpesh9896 can you elaborate your answer. Its hard to understand. I am able to play custom sound with Notification data that when app is in background, But its not playing when app is in background

**Comment by JohnVidal77** [comment]
> @kalpesh9896 can you elaborate your answer. Its hard to understand. I am able to play custom sound with Notification data that when app is in background, But its not playing when app is in background

Hey, how you make it work in background? i'm using the android 9

**Comment by annaostapenko22** [comment]
> This isn't very well documented sorry.
> 
> It needs to be inside of a `res/raw` directory inside of your Android build. It's not possible to provide a sound from a JS file.

Hello! Where exactly should be this "res/raw " directory?cd android/app/build?

**Comment by Ehesp** [comment]
If you open your projects `android` directory with Android studio, right click the `app` directory and add a new resource:

![image](https://user-images.githubusercontent.com/842078/78020775-f812a600-7349-11ea-9dca-88ae8a3e2514.png)

Needs a new directory adding with the file in it.

**Comment by meliodev** [comment]
@ankitbaid11326 @JohnVidal77 Did you succeed making sound working in background ?

**Comment by andidev** [comment]
@meliodev and others
I can confirm it works, 

place your sound file, e.g. mycustomsound.ogg, here:
```
android/app/src/main/res/raw/mycustomsound.ogg
```
(probably you need to create the raw directory)

Then create a notificaiton:
```js
        const DELIVERY_NOTIFICATIONS_CHANNEL = new firebase.notifications.Android.Channel('MY_CHANNEL_ID', 'Channel name', firebase.notifications.Android.Importance.Max)
            .setDescription('Notifications with available deliveries')
            .enableVibration(true)
            .enableLights(true)
            .setSound("mycustomsound.ogg");

        await firebase.notifications().android.createChannel(DELIVERY_NOTIFICATIONS_CHANNEL);
        const localNotification = new firebase.notifications.Notification()
            .setNotificationId("MY_ NOTIFICATION_ID")
            .setTitle("any title")
            .setBody("any body")
            .setSound("mycustomsound.ogg")
            .setBigText("any body")
            .setAutoCancel(true)
            .setSmallIcon('@drawable/ic_stat_ic_notification')
            .setLargeIcon('@drawable/ic_stat_ic_notification')
            .setColor('#006064')
            .setChannelId(DELIVERY_NOTIFICATIONS_CHANNEL.channelId);
        await firebase.notifications().displayNotification(localNotification);
```

**Comment by Uzef1997** [comment]
Hello,
I am able to set custom sound for notification but when my app is in the background or killed state it plays default sound only not custom sound if anyone knows about it please help me 
My code is the same as this one https://github.com/invertase/react-native-firebase/issues/2579#issuecomment-691899128
thank you
