### ISSUE TITLE
Error that prevented the build when trying to archive the project

### ISSUE THREAD

**Issue by faizmokhtar** [invertase/react-native-firebase#258]
I am currently unable to archive the project on xcode after adding the library. It throws the following error:

An error I got with fastlane `gym`:
```
❌  duplicate symbol _OBJC_CLASS_$_PodsDummy_Yoga in
> libYoga.a(Yoga-dummy.o)
> libyoga.a(Yoga-dummy.o)

❌  duplicate symbol _OBJC_METACLASS_$_PodsDummy_Yoga in
> libYoga.a(Yoga-dummy.o)
> libyoga.a(Yoga-dummy.o)

❌  ld: 2 duplicate symbols for architecture arm64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

My `Podfile` is as follows:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'VConsumer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ValyouConsumer
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  # [OPTIONAL PODS]
  pod 'Firebase/Analytics'
  pod 'Firebase/Crash'

  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    # Add any other subspecs you want to use in your project
  ]

  target 'VConsumer-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VConsumerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

I've ran `pod install` and still can run the project just fine. The error only happened when I tried to archived the project. I think there are some conflict between the react that is installed with `yarn` and `cocoapods` but I'm not sure what and where to change it. Anyone experienced something similar?

### Environment

1. Target Platform (e.g. iOS, Android): 
> iOS
2. Development Operating System (e.g. macOS Sierra, Windows 10):
> macOS Sierra 10.12.5 (16F73)
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
>  Xcode Version 8.3.3 (8E3004b)
4. React Native version (e.g. 0.45.1):
> react-native-cli: 2.0.1
> react-native: 0.42.0
5. RNFirebase Version (e.g. 2.0.2):
> react-native-firebase@2.0.3

**Comment by chrisbianca** [comment]
This looks libYoga.a is being linked twice.  Are you manually linking it as part of your project in Xcode?

**Comment by faizmokhtar** [comment]
Yup, it is being linked twice and I linked it with cocoapods. The issue was solved today though. What I did was that I delete `Yoga` binary inside `Targets > Yoga` and that helps avoid the duplicate.

**Comment by appatappa** [comment]
> Yup, it is being linked twice and I linked it with cocoapods. The issue was solved today though. What I did was that I delete `Yoga` binary inside `Targets > Yoga` and that helps avoid the duplicate.

Can you show exactly what you did?

**Comment by faizmokhtar** [comment]
@appatappa 	sorry can't help. I didn't work on RN anymore.
