### ISSUE TITLE
🔥 Index Creation Error Message Surfacing

### ISSUE THREAD

**Issue by technoplato** [invertase/react-native-firebase#2581]
## Issue

Describe your issue here

This may be on the border of a feature request and a bug report, but I'm going to file it as a bug report. On the native platforms, Firebase will error out if you attempt to query something where an index is required, but has not been created yet. Here's an example of one: 
![A685B366-4733-471A-B5B1-440D948D169A](https://user-images.githubusercontent.com/6922904/64891606-627b2780-d640-11e9-8765-79d1bd11a61d.png)

My app errored using react-native-firebase but I had to crack open a vanilla native Firebase Android application and run the query to show this error message. I know I could learn how to write the index myself, and probably should, but I was hoping the RNF team could come through and surface these error messages for me.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:
N/A
```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Hey - this is a highly requested feature... And I'm not 100% sure it's do-able. On Android & iOS the error thrown doesn't include the message the web SDK shows.

On v6 I added an extra bit of text ([example](https://github.com/invertase/react-native-firebase/blob/master/packages/firestore/android/src/main/java/io/invertase/firebase/firestore/UniversalFirebaseFirestoreException.java#L133)), but it's not ideal.

I'll leave this open for a while to see if it's possible to yank the error from native logs and pass it back to JS somehow.

**Comment by technoplato** [comment]
>On Android & iOS the error thrown doesn't include the message the web SDK shows. 

I'm not sure I understand. The error that I screenshotted above was from the Native Android SDK. Am I correct that RNF wraps the native SDKS?

You can reproduce the error production on Android by simply creating a compound query and attempting to run it. Let me know if you want any help in figuring this out. I'd love to contribute.

**Comment by Ehesp** [comment]
Hmm, I'll check this out again then - hopefully it's the same on iOS!

**Comment by Ehesp** [comment]
All sorted, will be live in next release.

**Comment by technoplato** [comment]
You're the man 👌

**Comment by Salakar** [comment]
Hey 👋 this is now live in v6.0.1, thanks. [[release notes]](https://invertase.io/oss/react-native-firebase/releases/v6.0.1)
