### ISSUE TITLE
Module '"@react-native-firebase/admob"' has no exported member 'BannerAd'.ts(2305)

### ISSUE THREAD

**Issue by guhyeon** [invertase/react-native-firebase#2586]
## Issue

When I import firebase admob

import { BannerAd, BannerAdSize, TestIds }  from "@react-native-firebase/admob";

then vscode shows ts error and intellisense not working.

bellow is error messages
Module '"@react-native-firebase/admob"' has no exported member 'BannerAd'.ts(2305)
Module '"@react-native-firebase/admob"' has no exported member 'BannerAdSize'.ts(2305)
Module '"@react-native-firebase/admob"' has no exported member 'TestIds'.ts(2305)

Describe your issue here

---

## Project Files

- Root: `tsconfig.json` contents. 
{
  "compilerOptions": {
    "allowJs": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "jsx": "react-native",
    "lib": ["es6"],
    "moduleResolution": "node",
    "noEmit": true,
    "strict": true,
    "target": "esnext"
  },
  "exclude": ["node_modules"]
}

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
-"@react-native-firebase/admob@^0.4.1":
-"@react-native-firebase/app@^0.4.1":

- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
-'admob'
- **Are you using `TypeScript`?**
  - `Y`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Salakar** [comment]
cc @Ehesp

**Comment by Salakar** [comment]
@guhyeon please update to v0.4.3 of the new modules and see if you have any more issues, I pushed up a few improvements to the types.
