### ISSUE TITLE
Admob:  No signature of method: java.util.LinkedHashMap.getStringValue(), after creating my firebase.json file

### ISSUE THREAD

**Issue by jehuayhualla** [invertase/react-native-firebase#2587]
## Issue

After creating my firebase.json file at the root of my project as it says in the documentation. I get the following error

`* Where:
Build file 'D:\Jesus\IFEEP AT\StoreClicker\StoreSkinClicker\node_modules\@react-native-firebase\admob\android\build.gradle' line: 44

* What went wrong:
A problem occurred evaluating project ':@react-native-firebase_admob'.
> No signature of method: java.util.LinkedHashMap.getStringValue() is applicable for argument types: (String, String) values: [admob_app_id, ]`

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 6.44 GB / 15.85 GB
  Binaries:
    Node: 12.6.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6`
- **`Firebase` module(s) you're using that has the issue:**
  - `ADMOB`
  -`"@react-native-firebase/admob": "^0.4.1",
    "@react-native-firebase/app": "^0.1.2",
    "@react-native-firebase/auth": "^0.1.2",
    "@react-native-firebase/firestore": "^0.1.2",`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by jehuayhualla** [comment]
I close this, as it is my fault not to have all the dependencies updated.

**Comment by babyrusa** [comment]
@jehuayhualla  I'm having the same issue when installing with npm. What dependencies did you miss?
