### ISSUE TITLE
Notification Events are not getting logged in Firebase

### ISSUE THREAD

**Issue by sangupandi** [invertase/react-native-firebase#2588]
## Doubts

There are some events that are logged on Firebase Analytics when we send an notification through the Firebase Notifications from Console (notification_receive, notification_dismiss, notification_foreground, notification_open).

I would like to know if it is possible to log those same events sending the Push Notification through the API (Firebase Cloud Messaging - FCM).

And one more doubt in **firebase.analytics** , Is there an option to passing the params to default event on firebase?

**Comment by Ehesp** [comment]
Please follow the issue template so we can help knowing what versions you are using/expecting this to work with.
