### ISSUE TITLE
Fluid Native Ad Support

### ISSUE THREAD

**Issue by ryandt** [invertase/react-native-firebase#2590]
Is anyone familiar with support for 'FLUID' native ads? I'm working on a project with Ad Manager (not Admob, but the APIs are very similar) to include fluid native support. However, I'm having difficulties rendering/drawing fluid native ads through React Native. I can successfully load and render banner ads in RN, successfully load and render fluid native ads in a native Android-only project, and successfully load fluid native ads in RN, but when I go to add it to my view hierarchy, it doesn't show up (blank view). I noticed this line in the source code of this library which leads me to believe this library is experiencing the same issue I'm seeing:

`// TODO size=FLUID not loading ad, height of child FrameLayout incorrect?`

**Comment by ianwelsh** [comment]
@ryandt I'm having the same issue trying to implement DFP fluid ads on Android, banner ads render but fluid ads do not. Did you find a solution?

**Comment by StaticSpark** [comment]
The documentation on intertase site says they only support 3 types of ads:
 - banners
 - instertitial
 - rewarded
Is Native(fluid) ads possible?, if so it should really be updated in the documentation.

**Comment by sang2087** [comment]
> Hey @ianwelsh. I did find a solution to this. The key was ensuring that `measure` and `layout` passes are executed after `requestLayout` is called. For example:
> 
> ```
> @Override
> public void requestLayout() {
>     super.requestLayout();
>     post(measureAndLayout);
> }
> 
> private final Runnable measureAndLayout = () -> {
>     measure(
>         MeasureSpec.makeMeasureSpec(getWidth(), MeasureSpec.EXACTLY),
>         MeasureSpec.makeMeasureSpec(getHeight(), MeasureSpec.EXACTLY)
>     );
>     layout(getLeft(), getTop(), getRight(), getBottom());
> };
> ```

hey, @ryandt could you explain in more detail?
I cannot find requestLayout method. I do not know what should I do.

Can you tell me which file you modified?

I'm already spending too much time applying 'FLUID' native ads. Please let me know.

**Comment by dolhadan** [comment]
@sang2087  did you manage to find a solution ?
