### ISSUE TITLE
firebase.auth().signInWithPhoneNumber(phoneNumber) not working FIRAuthErrorUserInfoNameKey=ERROR_WEB_CONTEXT_ALREADY_PRESENTED}`

### ISSUE THREAD

**Issue by sombizbuzzz** [invertase/react-native-firebase#2594]
hi I am getting this error 

Error Domain=FIRAuthErrorDomain Code=17057 "User interaction is still ongoing, another view cannot be presented." UserInfo={NSLocalizedDescription=User interaction is still ongoing, `another view cannot be presented., FIRAuthErrorUserInfoNameKey=ERROR_WEB_CONTEXT_ALREADY_PRESENTED}`

in RNFirebaseAuth.m 

```
 const confirmResult = await firebase.auth().signInWithPhoneNumber(phoneNumber);
      if (confirmResult) {
        this.setState({
          confirmResult,
          message: 'Code has been sent!',
          step: 2,
        }, this.goToEnterOtpScreen());
      }

 Illegal callback invocation from native module. This callback type only permits a single invocation from native code.

    "react-native-firebase": "^5.5.4",

pod 'Firebase/Core', '~> 6.3.0'
  
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/Database', '~> 6.3.0'
  pod 'Firebase/Functions', '~> 6.3.0'
  pod 'Firebase/DynamicLinks', '~> 6.3.0'
  pod 'Firebase/Firestore', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/RemoteConfig', '~> 6.3.0'
  pod 'Firebase/Storage', '~> 6.3.0'
  pod 'Firebase/Performance', '~> 6.3.0'


```

<img width="871" alt="Screen Shot 2019-09-18 at 8 16 42 AM" src="https://user-images.githubusercontent.com/43329978/65104048-bba2dc80-d9ed-11e9-8993-5493a8b8bf0d.png">

![Simulator Screen Shot - iPhone Xʀ - 2019-09-18 at 08 05 24](https://user-images.githubusercontent.com/43329978/65104011-9c0bb400-d9ed-11e9-91c9-6685560ba92f.png)

**Comment by sombizbuzzz** [comment]
https://stackoverflow.com/questions/57986052/signinwithphonenumber-is-not-working-in-react-native added here also

**Comment by Ehesp** [comment]
Please re-create this issue following the issue template. It's hard for us to debug without the required information!

Please consider upgrading to v6. These types of issues are much easier for us to test.

**Comment by PomegranateApps** [comment]
I'm having this same issue too.

**Comment by Seanmclem** [comment]
any solution to this?
