### ISSUE TITLE
V6 Android - unable to add firebase analytics to an existing project 

### ISSUE THREAD

**Issue by eranbo** [invertase/react-native-firebase#2595]
I have an existing project with V5. after following the documentation on how to remove and install the V6, I have trouble make it work with the Client Initialisation instruction. It feels like something is missing + more explanation on how the initialisation should work.
Can you please provide a step by step how to use the new version in react native with no type script?
Thanks,
Eran

**Comment by eranbo** [comment]
After doing some digging I noticed that the point where it breaks is at:  
node_modules/@react-native-firebase/app/lib/internal/registry/app.js:52   
```NATIVE_FIREBASE_APPS.length === 0``` so no '[DEFAULT]' app is created

**Comment by Ehesp** [comment]
Closing this one. Analytics works with the default app which is created via the Google services/plist file downloaded from the Firebase console. Please follow https://invertase.io/oss/react-native-firebase/quick-start on to set this up.
