### ISSUE TITLE
mediation Issue

### ISSUE THREAD

**Issue by IamMHC** [invertase/react-native-firebase#2597]
How to use mediation with 5.xx version kindly guide

**Comment by Ehesp** [comment]
If you can find some Android/iOS docs on mediation with AdMob please let us know. We've only implemented the basics which Firebase provides in the docs.

**Comment by IamMHC** [comment]
https://developers.google.com/admob/android/mediate

**Comment by Ehesp** [comment]
From what I understand, this is handled all via the console? The unit ID is hooked up to your AdMob account where you enable mediation?

**Comment by IamMHC** [comment]
yes but i think when we connect any source like facebook native ads then we need add
    implementation 'com.google.ads.mediation:facebook:5.5.0.0'

in build.gradle file so i wanna ask after this my ads serve from mediation

**Comment by Ehesp** [comment]
Honestly, I have no idea sorry. Give it a go in your own app I guess!

Unfortunately I haven't got time right now to dig into it, so please report any progress back here. As far as I'm aware, this is out of scope for us.
