### ISSUE TITLE
firebase.auth().signInWithPhoneNumber(phoneNumber).then((confirmResult) => { }) not working on android

### ISSUE THREAD

**Issue by mannat26** [invertase/react-native-firebase#2598]
## Issue

not working on android
"react-native-firebase": "~5.4.0"
"react-native": "0.59.3"

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Please follow the template

Also you may be interested in #2543

Or just in general a search for SMS in the issues list - a surprising number of them but I believe most found resolution
