### ISSUE TITLE
Server onDisconnect event

### ISSUE THREAD

**Issue by toninho** [invertase/react-native-firebase#26]
I'm trying create a presence system using react-native-firebase but it seems the onDisconnect callback is never called.

`var userid = 33;`
`    var amOnline = firebase.database().ref('.info/connected');`
`    var userRef = firebase.database().ref('presence/' + userid );`
`    amOnline.on('value', function(snapshot) {`
`         if (snapshot.val()) {`
`            userRef.onDisconnect().remove();`
`            userRef.set(true);`
`          }`
`    });`

it's not this available to be used or am I making some confusing?

**Comment by Ehesp** [comment]
Thanks for reporting. Will be looked at this weekend. It's probably related to https://github.com/invertase/react-native-firebase/issues/25 where the events and listeners are all mangled up.

**Comment by toninho** [comment]
It's working.
Sorry, I just realized now this operation takes some time to be processed by the server.

**Comment by AndrewHenderson** [comment]
> the events and listeners are all mangled up.

@Ehesp by mangled do you mean the approach to using the listeners? My code in particular, or on Firebase's end?

If there is an issue in the approach of my code sample in https://github.com/invertase/react-native-firebase/issues/25, please advise. I'm open to changing it. I was following the approach shared in the RNF examples: https://github.com/invertase/react-native-firebase-examples/blob/1d3fd13d2f552560fa5630bc12ad04785e301edf/src/examples/chat/Chat.js

**Comment by Salakar** [comment]
@AndrewHenderson there's some logic in the RNFirebase db implementation that's causing the issue you're experiencing.

RNFirebase's initial implementation of database refs has some logic in to de-duplicate refs and their listeners at the same path and query modifiers, obviously this is incorrect, two refs to the same path should both still get the initial event as well as the subsequent events, but the de-dupe logic breaks this, the first listener to a path with get both, the 2nd listener and onwards will only get new events that come through and no initial events. This is what needs fixing our end.

Nothing to worry about your end 👍
