### ISSUE TITLE
Android verifyPhoneNumber with autoVerifyTimeoutOrForceResend parameter is not working

### ISSUE THREAD

**Issue by jpudysz** [invertase/react-native-firebase#2606]
## Issue

`autoVerifyTimeoutOrForceResend` parameter inside `verifyPhoneNumber` is not working at all. Timeout occurs always after 30 seconds.

Steps to reproduce:
```
firebase
    .auth()
    .verifyPhoneNumber('validPhoneNumber', 10)
```

Result:
```
Timeout after 30 seconds
```

Expected result:
```
Timeout after 10 seconds
```

**Comment by abhiram-n** [comment]
@jpudysz  Were you able to figure this out? Seeing the same issue and other than adding a native timeout handler I don't see any other way around this.

**Comment by jpudysz** [comment]
@abhiram-n unfortunately not. The issue is not resolved.

**Comment by hadare1** [comment]
Is there any solution for this?? waiting 30 sec for the timeout shreds the user experience
