### ISSUE TITLE
currentUser is null after updatePassword

### ISSUE THREAD

**Issue by Vietvantue** [invertase/react-native-firebase#2607]
When I change password successfully, then  **firebase.auth().currentUser** is **null**. Password already changed successful, and I also have app recently logged as require: https://firebase.google.com/docs/auth/web/manage-users#re-authenticate_a_user

**Comment by Ehesp** [comment]
cc @IljaDaderko seen this?

**Comment by IljaDaderko** [comment]
@Vietvantue Can you please fill out the issue template and provide an example of how you are changing the password and afterwards accessing `currentUser`

**Comment by IljaDaderko** [comment]
Since you are changing password, I assume you are using email / password authentication method? I'm a bit confused because you linked to third-party re-authentication docs i.e. google / facebook.

So assuming email / password flow, I tested following and it worked for me.

```js
 async function changePassword(currentPassword) {
      const {auth} = firebase;
      const {currentUser} = auth();

      try {
        await auth().signInWithEmailAndPassword(currentUser.email, currentPassword);
        await currentUser.updatePassword(newPassword);
        console.log(firebase.auth().currentUser); // Exists
      } catch (e) {
        Alert.alert(e.message);
      }
    }
```
