### ISSUE TITLE
Auth - verifyPhoneNumber is returning error 'auth/unknown' rather than 'auth/too-many-requests'

### ISSUE THREAD

**Issue by jpudysz** [invertase/react-native-firebase#2608]
## Issue

Nothing to add, that method should return  `auth/too-many-requests` rather than `auth/unknown`

Steps to reproduce:

1. You can use iOS or Android and try to send multiple sms verification codes to your phone
2. You should start to get `auth/unknown` errors 
 
Result:
`auth/unknown` error

Expected result:
`auth/too-many-requests` error

**Comment by giovannilima262** [comment]
this error persists when logging in through the web and then trying to access it through the app. This problem is only for new users.

**Comment by mikehardy** [comment]
Interesting - we'd take a PR to transform that if possible, I believe we work around a few others the same, but I'd be careful and make sure (from logcat or Xcode console) that the SDK was giving enough information that we didn't false-positive or false-negative on detecting the exact error case to transform. It would be better perhaps to verify with firebase-android-sdk / firebase-ios-sdk (via their quickstart apps for auth) that this was an underlying issue and open it with them for a real fix I think
