### ISSUE TITLE
🔥 Which version are we supposed to choose?

### ISSUE THREAD

**Issue by pierroo** [invertase/react-native-firebase#2609]
## Issue

How do we know which version we are supposed to choose for each dependencies on Android?
The documentation doesn't seem up to date on version 5xx

Here is my app/build.gradle:

implementation 'com.google.gms:google-services:4.2.0'
    implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation "com.google.firebase:firebase-core:17.0.0"
    implementation "com.google.firebase:firebase-database:17.0.0"
    implementation "com.google.firebase:firebase-auth:17.0.0"
    implementation "com.google.firebase:firebase-storage:17.0.0"
    implementation "com.google.firebase:firebase-analytics:17.0.0"
    implementation "com.google.firebase:firebase-ads:17.0.0"

I read somewhere that com.google.android.gms:play-services-base should use 16.1.0, but why not 17.0.0 like everything else?
As for com.google.gms:google-services:4.2.0 this is the one mentioned in the doc, but it goes with firebase dependencies of 16.xxx, not 17 like mine.

I would REALLY appreciate any feedback on this, for I am afraid these lead to issue with app crashing when using putFile on firebase storage on android, and some other issues.

Thank you!

---

## Project Files
- Android: `android/app/build.gradle` contents.

#### Have you converted to AndroidX?

- [X ] my application is an AndroidX application?
- [ X] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [X ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 949.41 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.1
      System Images: android-19 | Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  v 5.8.5
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You should convert to the BOM style and use the most current BOM version per google android release notes if you are on RNFB5.5.6, it's way easier to manage the versions

Details here:
https://github.com/invertase/react-native-firebase/issues/1054#issuecomment-533234305

PRs for the docs are always appreciated if that works for you - we've hesitated to update them because the BOM style is new but we've heard nothing but success reports so far
