### ISSUE TITLE
V6 Admob / admob_app_id / firebase.json

### ISSUE THREAD

**Issue by manuhook** [invertase/react-native-firebase#2611]
## Documentation Feedback

The docs says to add the App ID (under the "App settings" from the Admob Account) to our root level firebase.json.

```
{
  "react-native": {
    "admob_app_id": "ca-app-pub-xxxxxxxx~xxxxxxxx"
  }
}
```

However I have **2** "App ID", one for iOS, one for Android. How I can set up my 2 "App ID" like I've used to do on Firebase AdMob 5.x (they were respectively on AndroidManifest.xml and info.plist) ?

Thank you !

**Comment by Salakar** [comment]
We're currently fixing this, this was an oversight on our part sorry, a PR should be up in a couple of hours

**Comment by Salakar** [comment]
This has been sorted in v0.5.4 of the pre-release packages, please give it a go.

There are 2 configs now, 1 per platform:

https://invertase.io/oss/react-native-firebase/v6/app/reference/firebasejsonconfig#admob_android_app_id

https://invertase.io/oss/react-native-firebase/v6/app/reference/firebasejsonconfig#admob_ios_app_id

**Comment by manuhook** [comment]
Thank you :)

**Comment by Ehesp** [comment]
Closing - please let us know if you have any issues with this!

**Comment by Jeadonara** [comment]
@Ehesp  please update also the doc: https://invertase.io/oss/react-native-firebase/v6/admob/european-user-consent
