### ISSUE TITLE
Unhandled JS Exception: usersRef.collectionGroup is not a function

### ISSUE THREAD

**Issue by joeljerushan** [invertase/react-native-firebase#2613]
## Issue

Unhandled JS Exception: usersRef.collectionGroup is not a function 

```
var usersRef = set.ref.collection("users").doc('r4EodZvvdK3Gy5oc6E3t');
        var museums = usersRef.collectionGroup('fcmToken').where('token', '==', 'djahiwh92832hjasfs');
        museums.get().then(function (querySnapshot) {
            querySnapshot.forEach(function (doc) {
                console.log(doc.id, ' => ', doc.data());
            });
        });
```

![image](https://user-images.githubusercontent.com/10111309/65407430-1c705180-de00-11e9-923b-0d92ae1fcaea.png)

i have properly setup everything .. but im getting this issue :( any help ?

**Comment by Ehesp** [comment]
Please follow the issue template - v5 or v6?

Also, your query is wrong. `ref` is not for Firestore.

**Comment by AlexR10** [comment]
Hi, I've the same issue my RNF version is 5.5.6. could you fix it?

**Comment by mikehardy** [comment]
@AlexR10 this issue will receive no attention. It lacks the required details.

**Comment by joeljerushan** [comment]
@Ehesp my query ref is okay check this code

```
 constructor() { 
        super();
        this.ref = firebase.firestore();
        this.state = {
            loading: false,
        };
};

getCollectionGroup(){
    var museums = this.ref.collectionGroup('landmarks').where('type', '==', 'museum');
    museums.get().then(function (querySnapshot) {
        querySnapshot.forEach(function (doc) {
            console.log(doc.id, ' => ', doc.data());
        });
   });
}
```

and i'm using `"react-native-firebase": "^5.5.6",`

**Comment by joeljerushan** [comment]
if anyone has trouble refer this link. https://invertase.io/blog/react-native-firebase-v6 `collectionGroup ()` won't work in v5 :) thanks for the support @Ehesp

**Comment by rayvenz23** [comment]
I was facing the same issue while using v5, I upgraded to v6 but the push notification is not working, and I don't want that.

I found my solution:
I reverted to v5, then I added [firebase](https://www.npmjs.com/package/firebase) to my project ( so there's now 2 firebase on my app ) but I call the 2nd one as :
import * as firebase2 from 'firebase';

then (after config ) :
firebase2.firestore().collectionGroup('mySubCollections').get()
