### ISSUE TITLE
invalid token

### ISSUE THREAD

**Issue by robertototti** [invertase/react-native-firebase#2615]
I get an error when signInWithPhoneNumber

signIn = () => {
    const phoneNumber = '+380975556688';

    firebase.auth().signInWithPhoneNumber(phoneNumber)
      .then(confirmResult => console.log(confirmResult))
      .catch(error => {console.log(error)}); // get error: Invalid Token
  };

what token invalid?

**Comment by AbanoubNassem** [comment]
did you figure out what was wrong ?

**Comment by robertototti** [comment]
Yes, I had the wrong bundle ID)
