### ISSUE TITLE
notification does not work in testflight

### ISSUE THREAD

**Issue by shenzheng220** [invertase/react-native-firebase#2616]
Hi, everyone.
i integrated firebase on React native 0.60.5.
it works on debugging version. but i published it on flight test. not working now.
what's the problem.
help me

**Comment by Salakar** [comment]
> what's the problem.

☝️

**Comment by mikehardy** [comment]
the problem is somewhere in your setup, which would possibly be visible if you followed the issue template and put the info in, instead of deleting it
