### ISSUE TITLE
 🔥firebase.auth().getRedirectResult() when remote js debugging

### ISSUE THREAD

**Issue by khlling** [invertase/react-native-firebase#2619]
## Issue

Get when using 'Remote JS Debug' I get 

> firebase.auth().getRedirectResult() is unsupported by the native Firebase SDKs.

package.json:

> "dependencies": {
>     "jetifier": "^1.6.4",
>     "prop-types": "^15.7.2",
>     "react": "16.8.6",
>     "react-native": "0.60.5",
>     "react-native-elements": "^1.2.0",
>     "react-native-firebase": "^5.5.6",
>     "react-native-gesture-handler": "^1.4.1",
>     "react-native-unimodules": "^0.6.0",
>     "react-native-vector-icons": "^6.6.0",
>     "react-navigation": "^4.0.5",
>     "react-navigation-stack": "^1.8.0",
>     "react-redux": "^7.1.1",
>     "react-redux-firebase": "^2.4.1",
>     "redux": "^4.0.4",
>     "redux-form": "^8.2.6",
>     "redux-thunk": "^2.3.0"
>   },

I've tried this solution: https://github.com/invertase/react-native-firebase/issues/431

i.e.

> import { applyMiddleware, compose, createStore } from 'redux';
> import { getFirebase, reactReduxFirebase } from 'react-redux-firebase';
> import firebase from 'react-native-firebase';
> import thunk from 'redux-thunk';
> import makeRootReducer from './reducers';
> 
> // for more config options, visit http://docs.react-redux-firebase.com/history/v2.0.0/docs/api/compose.html
> const reduxFirebaseConfig = {
>   userProfile: 'users', // save users profiles to 'users' collection
>   **enableRedirectHandling: 'false'**
> };
> 
> export default (initialState = { firebase: {} }) => {
> 
>   const middleware = [
>      // make getFirebase available in third argument of thunks
>     thunk.withExtraArgument({ getFirebase }),
>   ];
> 
>   const store = createStore(
>     makeRootReducer(),
>     initialState, // initial state
>     compose(
>      reactReduxFirebase(firebase, reduxFirebaseConfig), // pass initialized react-native-firebase app instance
>      applyMiddleware(...middleware)
>     )
>   )
>   return store
> }

This only happens with debug mode on.
---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 45.11 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.0 AI-171.4443003
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 5.5.6
- **`Firebase` module(s) you're using that has the issue:**
  - Auth
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

**Comment by Ehesp** [comment]
I don't have experience with `react-redux-firebase`, however from your code you need to change the `enableRedirectHandling` param to be a boolean not a string:

```diff
- enableRedirectHandling: 'false'
+ enableRedirectHandling: false
```

**Comment by khlling** [comment]
derp. That's how I originally had it but I copied it in wrong second time. I also had remove the cache and rerun the build to get it to work fyi to anyone else who has this issue. Thanks for you help!
