### ISSUE TITLE
Android Slow To Reconnect After Device Goes To Sleep

### ISSUE THREAD

**Issue by jemise111** [invertase/react-native-firebase#262]
Hey guys, Awesome work on this library!

Running into one weird issue. Android only but happening on multiple Android devices that are running a number of apps. The repro is something like:

1. Open App
2. Let phone sleep for five minutes
3. Wake phone
4. Push to a firebase Ref (e.g. `firebaseDatabase.ref('rooms/roomId/messages').push(newMessage);`)

The new message is synced to the localCache but NOT to my firebase DB. This is normal, it's working as if it were offline. I would expect it to sync shortly after but it's taking over 60 seconds to sync.

Running `adb logcat` whenever I try to call `.push` I see the message `Calling JS function after bridge has been destroyed`

Have you guys ever encountered anything like this / have any idea what's going on? Thanks!

### Environment

1. Target Platform (e.g. iOS, Android): **Android**
2. Development Operating System (e.g. macOS Sierra, Windows 10): 
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): 
4. React Native version (e.g. 0.45.1): **0.44.3**
5. RNFirebase Version (e.g. 2.0.2): **1.1.0**

**Comment by Ehesp** [comment]
Hey,

Is this on a production build? You you try adding `firebase.database().goOnline();` when the app wakes to see if it helps?

**Comment by jemise111** [comment]
Hey @Ehesp thanks for the reply. This is on production and debug builds.

I can give that a shot

**Comment by Ehesp** [comment]
I'd suspect this is down to the Firebase SDK detecting both when the phone moves to the background (plus network connection state). In one of our apps we have:

```
componentDidMount() {
  AppState.addEventListener('change', this.handleAppStateChange);
}
handleAppStateChange() {
    if (state === 'active' && this.isConnected) {
      firebase.database().goOnline();
      this.props.loadConfig();
    } else if (state === 'background') {
      firebase.database().goOffline();
    }
}
```

**Comment by jemise111** [comment]
@Ehesp Thanks for the tip. Yeah it seems `goOnline` doesn't work unless `goOffline` is called first. I'm working on a messaging app so it's very inconvenient (and a bit buggy) to disconnect from firebase every time the app is backgrounded.

Wondering if you have any other ideas?

**Comment by Salakar** [comment]
@jemise111 you could perhaps try something similar to @Ehesp 's example but instead do something like:

```javascript
componentDidMount() {
    AppState.addEventListener('change', this.handleAppStateChange);
}
handleAppStateChange() {
    if (state === 'active' && this.isConnected) {
      // force the db back into an online state
      firebase.database().goOffline();
      // on the next event loop
      setImmediate(() => firebase.database().goOnline());
    } else if (state === 'background') {
      // do nothing
    }
}
```

Probably not the nicest solution but i'm not sure if the native firebase sdk's provide any functionality to persist the connection in the background unless you write some native code to create a background service. See firebase reply on this SO post: https://stackoverflow.com/questions/42210186/handling-keepsynced-while-on-background-on-android-and-with-fcm

Ideally your messages should also route through FCM, that way when the app is in the background you still get message notifications/events.

**Comment by jemise111** [comment]
@Salakar we tried something similar to your latest suggestion and in a few days of testing we haven't seen the issue again, so thank you!

Going to close this and may reach out again if the problem pops back up

**Comment by SamMatthewsIsACommonName** [comment]
Do you guys know if there's any kind of reason why android just won't connect under certain network circumstances? We've had it with a few users where they just go offline and don't go back online, over a few versions now (currently 3.1.0), and it only happens on android. Is anyone else experiencing this?
