### ISSUE TITLE
Is there anyway to upload APN/Certificate automatically?

### ISSUE THREAD

**Issue by CaptainJeff** [invertase/react-native-firebase#2620]
Is there anyway to upload the APN certificate from fastlane or an API at all. I need a way to avoid manually uploading it

**Comment by mikehardy** [comment]
I don't know, a quick scan of their docs doesn't look promising https://firebase.google.com/docs/reference/admin

I think this question might be better on the firebase-ios-sdk official github, or maybe via stackoverflow as it's not really react-native-firebase specific, and they'll be authoritative on their own github

**Comment by CaptainJeff** [comment]
@mikehardy thanks for the advice. Will do
