### ISSUE TITLE
Rewarded video not opening when called from modal on ios

### ISSUE THREAD

**Issue by CoderProject** [invertase/react-native-firebase#263]
I'm using wix/react-native-navigation to open a modal and showing a rewarded ad from modal. Ad is loaded but never shown on ios. On Android it works perfectly.
This is the warning i get on console:
`Warning: Attempt to present <GADInterstitialViewController: 0x7ffefdd020a0> on <RCCDrawerController: 0x7ffefdc018a0> whose view is not in the window hierarchy!`

When i move the code to the root screen, the ad is shown as expected. So the problem is opening from modal. As a workaround I will close modal to show ad and then open again on onAdClosed event.

### Environment

1. Target Platform (e.g. iOS, Android): iOS
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS/ Windows 10
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Xcode
4. React Native version (e.g. 0.45.1): 0.45.1
5. RNFirebase Version (e.g. 2.0.2): 2.0.1

**Comment by Ehesp** [comment]
When you say Modal, is that the React Native Modal or the navigation type Modal on Wixs end?

**Comment by CoderProject** [comment]
its the navigation type Modal which is shown by calling `showModal()`

**Comment by CoderProject** [comment]
>  As a workaround I will close modal to show ad and then open again on onAdClosed event.
When using this workaround I found another bug. I was using a class-wide variable as below:
```
export default class MyScreen extends Component {
    firebase = RNFirebase.initializeApp();
    advert = this.firebase.admob().rewarded('ca-app-pub-adunit...');
    
    constructor(props) {		
        super(props);
        this.advert.on('onAdClosed', () => {
			console.log('ad closed');
		});
    }
...
```

On first ad view it was working great, but on the second time that I open this modal, `onAdClosed` event was being called multiple times. On third time even more, I guess the events was not being removed.

So I solved it by making advert static and adding event only once:
```
export default class MyScreen extends Component {
    firebase = RNFirebase.initializeApp();
    static advert=null;
    
    constructor(props) {		
        super(props);
        if (!MyScreen.advert) {
		MyScreen.advert = this.firebase.admob().rewarded('ca-app-pub-adunit...');
		MyScreen.advert.on('onAdClosed', () => {
			console.log('ad closed');
		});
	}
    }
```

I did not understand why old `onAdClosed` events are also fired, even though a new instance of advert is created.

**Comment by Salakar** [comment]
Cc @ehesp we had the duplicating events before didn't we on something else?

**Comment by ianzitow** [comment]
I'm also facing this issue, any way to play rewarded video from a modal presented by React Native Navigation?

**Comment by ianzitow** [comment]
Here's my proposed solution. #615

**Comment by Salakar** [comment]
Thanks for reporting this issue. We're aware that AdMob has fallen behind on React Native Firebase and would like to bring it up to speed again. I will close this issue for now and track it as well as other issues collectively over on the `AdMob overhaul proposal` to be addressed in a future release. See #1259
