### ISSUE TITLE
Unable to find a specification for `RNFBApp` depended upon by `RNFBMessaging`

### ISSUE THREAD

**Issue by mahdidavoodi7** [invertase/react-native-firebase#2630]
Hi i got this error when i'm trying to run `pod install`
I don't know what is wrong with this 

<img width="826" alt="Screen Shot 2019-09-25 at 1 11 20 PM" src="https://user-images.githubusercontent.com/29153345/65589506-06949500-df96-11e9-9fe0-d544232f020f.png">

im using  `react native -> 0.60.4`
and `firebase -> 6.0.0`

**Comment by mikehardy** [comment]
Please follow the template, it would provide the data needed to troubleshoot. I'd open a new issue so the template is intact

**Comment by vladbars** [comment]
the same issue

**Comment by cesar3030** [comment]
I'm having the same issue as well

**Comment by mahdidavoodi7** [comment]
@mikehardy I think this guy is so strict 
A good question is what people can understand not the one which follows the template  .

**Comment by mikehardy** [comment]
@mahdidavoodi7 the template requests your Podfile contents among other things. It would contain the reason. You'll notice we're on issue 2361 in the repo - the things we ask for in the template are based on a loooot of experience. So, we're strict about it, sorry :-)

**Comment by cesar3030** [comment]
@mahdidavoodi7 I created a new issue with the required info: #2662

**Comment by mahdidavoodi7** [comment]
@cesar3030 Thanks

**Comment by cesar3030** [comment]
@madidavoodi7 I forgot to run `yarn add @react-native-firebase/app` ...

**Comment by mugabodeo** [comment]
> @madidavoodi7 I forgot to run `yarn add @react-native-firebase/app` ...

it works thx @cesar3030

**Comment by Coforge** [comment]
> @madidavoodi7 I forgot to run `yarn add @react-native-firebase/app` ...

It worked for me too.

**Comment by patik** [comment]
I'm having this issue even though I already have `@react-native-firebase/app` installed

```json
    "@react-native-firebase/app": "11.5.0",
    "@react-native-firebase/messaging": "11.5.0",
```

**Comment by mikehardy** [comment]
@patik this is a resolved issue, and your versions are so old they are unsupportable at this point
Here's a script that reproduces a fully working integration step by step from scratch with comments explaining: https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
I worked on that yesterday and it runs, so you must have a local project integration issue. If you can show a reproduction with a problem from scratch like that on current versions please open a new issue. Thanks!
