### ISSUE TITLE
App is open for too long firebase stops working after few hours.

### ISSUE THREAD

**Issue by Nidhi-Gandhi** [invertase/react-native-firebase#2632]
If app is open for long time then after few hours firebase stops working. I am working with react-native and react-native-firebase on chat application. If I leave chat screen open overnight then in morning it stops working. Once I closed and reopened it then it working fine.

For Example: I sent my last message "Good night" and I slept but my chat screen was open. When I wakeup in morning at that time app was open and I could see my chat screen. I tried to sent message in chat to wish 'Good Morning' but it was stops working, nothing happened. When I closed the app and reopened it then it was works fine. I also received some other messages that arrived in morning.

It seems like firebase looses connectivity after few hours. Not any firebase queries are executes. I use Phone authentication for sign up. Android release SHA-1 key was already added in firebase.
```
    "react-native-firebase": "^5.5.6",
    "react-native-gifted-chat": "^0.7.2",
    "react-native": "0.59.10",
```

**Comment by mikehardy** [comment]
you didn't actually follow the template. I have no idea what firebase release you're on. iOS or Android. Open a new issue but don't ignore the template, and we can try to help

**Comment by R-D-P** [comment]
The firebase idToken expires in 60 minutes, that could be a possible reason.
