### ISSUE TITLE
[v6] pod install doesn't install RNFBApp

### ISSUE THREAD

**Issue by sercanov** [invertase/react-native-firebase#2633]
## Issue

I was already using v5 and migrated to v6 by following the steps on [docs](https://invertase.io/oss/react-native-firebase/migrating-to-v6)

`pod install --repo-update`  didn't installed any firebase pods. Autolinking doesn't seem to be working. So, it throws "Firebase module not found." on AppDelegate `@import Firebase;`

Also tried removing pods directory, podfile.lock and run pod install, pod update, pod repo update, no luck. 

Using RN 0.60.3, RNF 6.0.0, @react-native-community/cli 2.9.0, cocoapods 1.8.0

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '9.3'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'App' do
  # Pods for App
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'ViroKit_static_lib', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/static_lib'

  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'App-tvOS' do
  # Pods for App-tvOS

  target 'App-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 129.60 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.3 => 0.60.3
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.0.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by sercanov** [comment]
After I updated react-native to 0.61.1 it resolved. Actually, `react-native upgrade` command updated the react-native and installed RNFBApp pods, amazing tool 😄

**Comment by arrygoo** [comment]
@sercanov Can you pls reopen this issue? How can it be fixed without upgrading RN to 61?

**Comment by sercanov** [comment]
@arrygoo upgrading to RN 61 seems easier than tracking this issue. It may be related to the auto-linking issue on RN 0.60.x

**Comment by cesar3030** [comment]
Upgrading RN to 0.61.1 did not solve the issue for me

**Comment by sercanov** [comment]
It seems there's something wrong with auto-linking in some cases. Reopening the issue

**Comment by FDiskas** [comment]
Did you follow the docs? 
https://invertase.io/oss/react-native-firebase/quick-start/ios-firebase-credentials

**Comment by sercanov** [comment]
Yeah, I followed both quick start and migration docs when I had the issue. Guys, could one of you upload a reproducible demo? @cesar3030 @arrygoo

**Comment by zwenza** [comment]
I also had a problem but `pod install --repo-update` solved it in my case

**Comment by Ehesp** [comment]
I recently updated the docs to include a repo update, as it seems a lot of people hit this issue.

**Comment by cesar3030** [comment]
@sercanov I forgot to run `yarn add @react-native-firebase/app`. That's why I was having this issue

**Comment by sercanov** [comment]
@cesar3030 lol.

It seems everyone happy with `pod install --repo-update` I'm closing the issue.

**Comment by carmenchapa** [comment]
@sercanov `pod install --repo-update` did not work for me. I'm using rn0.61.4

**Comment by ahanusek** [comment]
^^
I have the same problem with RNF 6.2.0 and RN 0.61.5. Android app is successfully auto linked, but iOS somehow cannot detect required pods to install.

**Comment by mikehardy** [comment]
Suspect incorrect react-native auto-linking Podfile integration
https://github.com/facebook/react-native/blob/master/template/ios/Podfile#L2
https://github.com/facebook/react-native/blob/master/template/ios/Podfile#L78

**Comment by ahanusek** [comment]
@mikehardy Any tip how fix this issue? Should downgrade to the other RN version or add manually 'Firebase/Core' and other FB libraries to Podfile?

**Comment by mikehardy** [comment]
There's a million ways a project can integrate incorrectly. I can't say how you need to fix your project.

For that reason (that fixing independent projects is open-ended use of time) I switched styles for helping - I provide a set of scripts (one each for [RNFBv5+RN59](https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh), [RNFBv5+RN60+](https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh), [RNFBv6+RN60+](https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh)) that does all the work in one script of making a new react-native app from template, integrating react-native-firebase, and making a sample app that proves it works.

Check them out, run the one that fits you and compare what it did with what your project looks like. The issue will be found in the difference
