### ISSUE TITLE
Cannot get property 'parentFile' on null object

### ISSUE THREAD

**Issue by devWaleed** [invertase/react-native-firebase#2635]
I have installed @react-native-firebase/app package only and its giving me the following error when I build project. I have added all things in settings.gradle and in main.java file as well.

```
> Configure project :@react-native-firebase_app
:@react-native-firebase_app:firebase.bom using default value: 21.1.0

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script 'D:\IteckMobileAppTesting\node_modules\@react-native-firebase\app\android\firebase-json.gradle' line: 11

* What went wrong:
A problem occurred evaluating script.
> Cannot get property 'parentFile' on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':@react-native-firebase_app'.
> compileSdkVersion is not specified.
```

**My settings.gradle under Android folder:**

```
rootProject.name = 'asdf'
include ':@react-native-firebase_app'
project(':@react-native-firebase_app').projectDir = new File(rootProject.projectDir, './../node_modules/@react-native-firebase/app/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'

```

**MainActivity.java**

```
package com.avolox.iteck;

import io.invertase.firebase.app.ReactNativeFirebaseAppPackage;
import com.facebook.react.ReactActivity;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "iTecknologi";
    }

    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.asList(
            new MainReactPackage(),
            new ReactNativeFirebaseAppPackage()
        );
    }
    
```

My dependences in android/app/build.gradle

```
dependencies {
...
  implementation project(path: ":@react-native-firebase_app")
...
}

```

**Comment by devWaleed** [comment]
I solved this issue by creating an empty firebase.json file at the root but I am not sure what to put in that firebase.json file?

**Comment by Salakar** [comment]
Hey @devWaleed - this must be a bug then I think, it should still work even without a firebase.json file - we'll get this sorted next week.

For what the firebase.json can contain: https://invertase.io/oss/react-native-firebase/v6/app/reference/firebasejsonconfig

**Comment by devWaleed** [comment]
@Salakar can you help me with this question please: https://stackoverflow.com/questions/58115348/does-react-native-firebase-work-in-background

Does this package work itself in background ? or do I have to implement headless js and make a background worker to listen to FCM messages?

**Comment by mikehardy** [comment]
@devWaleed I could be wrong (I haven't tested it on v6) but it looks like you need to execute this API to get set up to handle FCM data messages in the background: https://github.com/invertase/react-native-firebase/blob/master/packages/messaging/lib/index.js#L221

If it is an FCM message in the background that is not data-only (i.e., it contains notification+data or just notification) then it will be delivered to the system tray I believe. (the workaround there is to only ever send data-only messages, then generate your own notification - that way you can do big-picture stuff or whatever else you want to do, however notifications won't be present in v6 for a little while so that use case isn't covered - follow here #2566

**Comment by cw-sanjeev** [comment]
I created an empty firebase.json file, but the error persists.
Is there an other solution to iit.
Thank you.

**Comment by Salakar** [comment]
I tried replicating this today and have been unable to do so, could you provide with more information such as the versions you're using of the library, your gradle versions, etc - as per the issue template.

Also; I noticed you've manually linked the library in Android even though you have auto-linking enabled:
![image](https://user-images.githubusercontent.com/5347038/66277690-dc967900-e899-11e9-90eb-2183f6838e03.png)
![image](https://user-images.githubusercontent.com/5347038/66277692-e28c5a00-e899-11e9-94c6-df91313728e1.png)


I'd remove these if using auto-linking.

**Comment by Salakar** [comment]
Hold up, I've just replicated it - leave it with me and I'll get a fix up

**Comment by Salakar** [comment]
Hey 👋 this issue is now fixed in v6.0.1, thanks. [release notes](https://invertase.io/oss/react-native-firebase/releases/v6.0.1)

**Comment by viky293** [comment]
Is there any explanation on why empty firebase.json was required.

**Comment by androidIsForVivek** [comment]
i am still getting this issue on version 12.1.0
