### ISSUE TITLE
🔥Remote Config returns invalid JSON on Android only

### ISSUE THREAD

**Issue by DawTaylor** [invertase/react-native-firebase#2636]
Hi, thanks for the great work with this library.

## Issue
Remote Config returns invalid stringified JSON on Android platform only.

I have a `enUS` config that looks like this;
```json
{
  "greet": "Hello World!"
}
```

When parsing this config on Android I get the following output.
```
"{greet=Hello World!}"
```

When parsing this config on iOS I get a proper stringified JSON output, which I can parse.
```
"{"greet":"Hello great big world"}"
```

This is my `RemoteConfig` Typescript class.
```ts
import reactNativeFirebase, { Firebase } from 'react-native-firebase'
import { REMOTE_CONFIG_DEFAULTS } from './defaults'

export class RemoteConfig {
  constructor(private readonly firebase: Firebase, defaults: IHashMap<any>) {
    this.firebase = firebase

    this.configureDefaults(defaults)
  }

  public getConfig(key: string): Promise<any> {
    return this.firebase
      .config()
      .fetch()
      .then(() => {
        return this.firebase.config().activateFetched()
      })
      .then(activated => {
        if (!activated) {
          console.log('Fetched data not activated')
        }
        return this.firebase.config().getValue(key)
      })
      .then(snapshot => {
        const jsonConfig = JSON.parse(snapshot.val())
        return jsonConfig
      })
  }

  private configureDefaults(defaults: IHashMap<any>) {
    this.firebase.config().setDefaults(defaults)
  }
}

export const remoteConfig = new RemoteConfig(reactNativeFirebase, REMOTE_CONFIG_DEFAULTS)
```

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Memory: 20.97 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 28.0.2, 28.0.3
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 5.5.6
- **`Firebase` module(s) you're using that has the issue:**
  - Remote Config
- **Are you using `TypeScript`?**
  - Yes
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by DawTaylor** [comment]
After further investigation/testing it turns out that the parser was having problems parsing a one key only json, which I was using for testing.

After simply adding another key to the json, the parser worked fine.

**Comment by mikehardy** [comment]
interesting - that must be why I haven't seen this - I have a one-key json and it works (except, maddeningly, on very old android APIs, specifically API17 seems to fail?) but my code looks ever so different at the end:

```typescript

    firebase
      .config()
      // FIXME need some sort of refresh control right now - 12hr default slow...
      .fetch(this.duration)
      .then(() => {
        return firebase.config().activateFetched();
      })
      .then(activated => {
        if (!activated) console.log('RemoteConfigService::startup - Fetched data not activated');
        return firebase.config().getValue('hasCalculator');
      })
      .then(snapshot => {
        console.log(
          'RemoteConfigService::startup - received hasCalculator value: ' + snapshot.val()
        );
        RemoteConfigService.hasCalculator = snapshot.val();
      })
      .catch(e => {
        console.log('RemoteConfigService::startup - fetch/activate/val failure', e);
      });

```

**Comment by nikhilk1993** [comment]
@mikehardy @DawTaylor  I am having the exact same problem on android only. 
My JSON has 4 keys but still returns invalid stringified JSON. Is there any fix for this?

**Comment by mikehardy** [comment]
@nikhilk1993 this was closed 2 and a half years ago. If you're still seeing strange behavior please **make sure you are on current versions** then follow the philosophy of https://stackoverflow.com/help/minimal-reproducible-example / https://stackoverflow.com/help/how-to-ask

Using my reproduction app creator https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh make an App.js that demonstrates it when you drop in your google service files and we'll see what we can do.

No one else is reporting this, and in my projects at least I get valid JSON from both android and iOS so I'll be surprised if it reproduces on a fresh project + current versions, but maybe there's something wrong

**Comment by HishamMubarak** [comment]
I still had the same issue of getting JSON like `"{greet=Hello World!}"` even after upgrading to the latest version (18.3.0). Finally use the JSON5 package to parse json instead of native JSON.parse() and got it working

https://github.com/json5/json5
