### ISSUE TITLE
@react-native-firebase/dynamic-links uses UIWebView APIs

### ISSUE THREAD

**Issue by big-toni** [invertase/react-native-firebase#2638]
## Issue

"@react-native-firebase/dynamic-links": "^0.4.3",
We identified one or more issues with a recent delivery for your app. Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:
- as sa standard podfile on a RN 0.60+ project, no added lines , because pods are autolinked via npm modules podspec...

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 749.46 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.3.1 - ~/.nvm/versions/node/v12.3.1/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v12.3.1/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.3.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-native: ^0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-log-ios: 1.0.1

```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  -  "@react-native-firebase/analytics": "^0.4.3",
    "@react-native-firebase/app": "^0.4.3",
    "@react-native-firebase/dynamic-links": "^0.4.3",
    "@react-native-firebase/remote-config": "^0.4.3",
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by big-toni** [comment]
resolved when updated to :
    "@react-native-firebase/analytics": "^6.0.0",
    "@react-native-firebase/app": "^6.0.0",
    "@react-native-firebase/dynamic-links": "^6.0.0",
    "@react-native-firebase/remote-config": "^6.0.0",

misunderstanding was due to confusing versioning of the **new npm separated packages starting from 0.0.0 instead of 6.0.0**

**Comment by mikehardy** [comment]
I think you just got caught during the switch from the pre-release v6 code to the official release - a bit tumultuous here. Glad you got it sorted! now you should be in regular semver releases with v6

**Comment by fxhrgco** [comment]
Hi there I've tried to upgrade to the v6 version but it seems that the Notifications module isn't released yet.

My question is: Is there a v5.5.X version with the UIWebView issue solved?

I was currently using the 5.5.6

**Comment by mikehardy** [comment]
@fxhrgco - hi there! react-native-firebase does not actually include the UIWebView symbols at all. So what you mean with the question is "Google's iOS Firebase SDK included UIWebView symbols, is there a version where they resolved that, and is react-native-firebase compatible with it?"

The answer to both is (happily), yes. They released 6.8.1 with fixes for it -https://firebase.google.com/support/release-notes/ios - and react-native-firebase v5.5.6 is compatible up to 6.12.0 (current as of now)

I have submitted multiple releases of my work project with these combos without receiving UIWebView warnings. If you continue to receive them from the App Store you'll have to look into other modules

**Comment by fxhrgco** [comment]
Thanks for your response!
Actually I'm seeing this right now:
<img width="1186" alt="Captura de pantalla 2019-11-12 a las 9 45 59" src="https://user-images.githubusercontent.com/47970728/68656009-51ac3c80-0531-11ea-8f69-c3d7ccdc986e.png">

Here is my podfile:
```
pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/RemoteConfig', '~> 6.3.0'
  pod 'Firebase/Analytics', '~> 6.3.0'
  pod 'Firebase/DynamicLinks', '~> 6.3.0'
  pod 'GoogleAppMeasurement', '~> 6.0.2'
```

Do you mean that I can update the pods to the 6.8.1 and that would be fixed?

Cheers!

**Comment by mikehardy** [comment]
@fxhrgco yes, exactly that: https://firebase.google.com/support/release-notes/ios#version_681_-_september_10_2019
