### ISSUE TITLE
Support for Firestore Compound queries/Composite Index

### ISSUE THREAD

**Issue by qalqi** [invertase/react-native-firebase#2644]
Currently, in `5.5.5`
For a Compound query like so,
 ```javascript
firebase.firestore().collection("conversations").where('members', 'array-contains', myUID).where('members', 'array-contains', otherUID)
```
Compound queries are throwing an error as
`Invalid Query: Queries only support having a single array-contains filer.`

But, firestore has compound query support for array-contains
https://cloud.google.com/firestore/docs/query-data/queries#compound_queries
https://firebase.google.com/docs/firestore/query-data/index-overview#queries_supported_by_composite_indexes

As a temporary workaround, in 5.5.5 as suggested in https://stackoverflow.com/questions/52837711/firestore-multiple-array-contains
I am currently creating a manual membersComposite with array values `[myUID+"_"+otherUID, otherUID+"_"+ myUID]` and querying membersComposite instead as 

 ```javascript
firebase.firestore().collection("conversations").where('membersComposite', 'array-contains', otherUID+'_'+ myUID)
```

Please provide this feature

For feature requests please visit our [Feature Request Board](https://invertase.io/oss/react-native-firebase/feedback/).

**Comment by Salakar** [comment]
cc @ehesp

**Comment by JanErikFoss** [comment]
@qalqi Until it gets implemented, you could probably just sort the uids alphabetically and then save them once, instead of double saving like in your example.

**Comment by Ehesp** [comment]
I'll investigate this next week as I'm away at the moment. Could you also try the same query using the Web sdk?

**Comment by Ehesp** [comment]
I have just tried this functionality out on the web SDK with the following code:

```js
  await firebase
    .firestore()
    .collection("playground")
    .add({
      title: "Convo 1",
      members: [1, 2, 3]
    });

  await firebase
    .firestore()
    .collection("playground")
    .add({
      title: "Convo 2",
      members: [4, 5, 6]
    });

  const foo = await firebase.firestore().collection('playground')
    .where('members', 'array-contains', 1)
    .where('members', 'array-contains', 4)
    .get();

console.log(foo.docs);
```

The Web SDK also reports: `FirebaseError: Invalid query. Queries only support a single array-contains filter.`.

If we allowed this on the native SDKs, it returns the same errors, so we capture it in JS side.
