### ISSUE TITLE
Can't Push a Object containing array in Firebase in React Native

### ISSUE THREAD

**Issue by thanhtan27081998** [invertase/react-native-firebase#2646]
## Issue

Describe your issue here
I created a user model for a social media that each user model has its own array of posts bellow.

class UserModel {
  feeds: FeedModel[] = []
}
But when i use firebase to push this user, it doesn't not appear in the database even there is no error, instead, if i remove the feeds array, then it does. 

export async function createUserData (user: UserModel, callBack: void, finish: void) {
  await firebase.database().ref('Users').push(user).then(() => {
    handleCallBack(callBack)
  }).catch((error) => {
    handleError(error, finish)
  })
}

I also log the user.feeds and the data is still in it.

**Comment by Ehesp** [comment]
Please follow the issue template.
