### ISSUE TITLE
 🔥After disabling push notifications on IOS I can not get it to work again 🔥

### ISSUE THREAD

**Issue by marko2606** [invertase/react-native-firebase#2649]
## Issue

Describe your issue here

I have enabled push notifications on both android and IOS, everything works as expected. Problem starts when user needs to sign out. In that case I must disable notifications completely. I have managed to do that by deleting token i got from firebase and removing listeners below.

firebase.notifications().onNotification()
firebase.notifications().onNotificationOpened()

By removing listeners notifications are not arriving when the app is active but they still arrive when the app is in background/closed.

In order to disable notifications in background and closed state i have tried the following:

deleted the token => notifications are disabled in both background and closed state
deleted the firebase instance => notifications are disabled in both background and closed state

Problem is that after deleting the token I can not enable notifications again. I am creating a new token when user sing in again. On Android everything works fine with enabling and disabling the notifications but on IOS after deleting the token or firebase instance I can not get notifications to arrive to the device again.

Please advice.
---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ x ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `notifications`
  - `messaging`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
This is going to be a very vague response and I apologize in advance - but I feel like there was an issue with the APNS token refresh being slow and that retries or delays before retrying were a workaround. I have nothing more concrete to offer than that, but if it were me I'd investigate by console logging all state and for the attempt to get the new token I'd try, wait + retry etc all the while logging it to see if there was something there.

**Comment by marko2606** [comment]
I got the new token after deleting the old one, but notifications are still not appearing... Will do some further testing, but it doesn't look promising...
