### ISSUE TITLE
Documentation a little unclear about how to use the vision library

### ISSUE THREAD

**Issue by tb91** [invertase/react-native-firebase#2650]
## Documentation Feedback

Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation.

---
https://invertase.io/oss/react-native-firebase/v6/ml-vision/quick-start talks about how to setup the vision library and I followed it. I suggest adding an example in the bottom of the page to clear any confusion like I had. Please check my problem here in detail on stackoverflow: 
[https://stackoverflow.com/questions/58137053/react-native-firebase-mlkit-textrecognizerprocessimage-is-not-a-function/58137413#58137413](https://stackoverflow.com/questions/58137053/react-native-firebase-mlkit-textrecognizerprocessimage-is-not-a-function/58137413#58137413)

Suggest: make sure that somebody sees in the example that you must use vision().somefunction and not vision.somefunction.

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
I've just added an example for this: https://github.com/invertase/react-native-firebase/commit/98978de27d653919588b407ba4f75f65618f973e

For anyone else who comes across this issue, the tests are a good place to see usage: https://github.com/invertase/react-native-firebase/tree/master/packages/ml-vision/e2e
