### ISSUE TITLE
Error: The [[DEFAULT]] firebase app has not been initialized!

### ISSUE THREAD

**Issue by kukadiyaAni** [invertase/react-native-firebase#2655]
## Error: The [[DEFAULT]] firebase app has not been initialized!

![Screenshot_1569693370](https://user-images.githubusercontent.com/16218216/65820536-fd325380-e247-11e9-83e1-a369b5e4aa92.png)

I got issue when I use below code 

```
 firebase.auth().signInWithPhoneNumber(phoneNumber)
      .then(confirmResult => {
      })
      .catch(error => {
      });

```
I have checked .json file correctly setup 

`firebase.auth.nativeModuleExists` this working 

Please help me fix this issue
---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:
<img width="854" alt="Screenshot 2019-09-28 at 11 18 55 PM" src="https://user-images.githubusercontent.com/16218216/65820545-2b179800-e248-11e9-8610-1deb26a90772.png">
```groovy
// N/A
```

#### `android/app/build.gradle`:
<img width="788" alt="Screenshot 2019-09-28 at 11 18 38 PM" src="https://user-images.githubusercontent.com/16218216/65820542-1b984f00-e248-11e9-9141-724aab6d62de.png">
```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
Error: The [[DEFAULT]] firebase app has not been initialized!
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `5.5.6`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
There is something wrong with your react-native-firebase integration.
You have not filled out the issue template completely so I am missing vital information needed to troubleshoot (specifically, what react-native version?)

For react-native 0.60 and higher, clone and run this repo then **carefully** examine everything it does, and compare it to your integration. Something was missed or is different and that will be the problem.https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

For react-native 0.59 do the same but with this version https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh

**Comment by kukadiyaAni** [comment]
I have clone 0.60 and run it's work fine, I also compare with my project it's all looks same

Can you please help me what's going wrong?

**Comment by mikehardy** [comment]
If it works fine, I have essentially done all I can - prove without question that it works. Each line in that script is a reason a project can't go wrong. I would examine each line as if it were a todo list and find whatever it is - sorry I can't be more specific but if you don't follow the template there's nothing I can do.

**Comment by kukadiyaAni** [comment]
Work fine only demo project which clone from GitHub but my actual project
not work with react native firebase

**Comment by kukadiyaAni** [comment]
@mikehardy Let me know which react-native-firebase version I can use for react-native:0.59.9?

**Comment by mikehardy** [comment]
@kukadiyaAni 
react-native-firebase v5 will work for you

https://rnfirebase.io/docs/v5.x.x/getting-started#Supported-versions---React-Native-/-Firebase

I would integrate it exactly like so https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh
