### ISSUE TITLE
Firebase Dynamic Links are not opening App from Facebook, it opens just web preview  

### ISSUE THREAD

**Issue by imdadhussain004** [invertase/react-native-firebase#2658]
I have implemented Firebase Dynamic links in React-Native app. They are working fine for both Android & iOS, but from Facebook App link is not being redirect to my App it shows blank page whenever i click on dynamic link from facebook. It would be really nice of you, if you help me with that regards. Thank you.

reactnative #firebase #dynamiclinks

**Comment by Ehesp** [comment]
Please follow the issue template.
