### ISSUE TITLE
Mention "Additional Installation Steps" for Crashlytics in "Quick Start"

### ISSUE THREAD

**Issue by 3rfan** [invertase/react-native-firebase#2659]
## Documentation Feedback

https://invertase.io/oss/react-native-firebase/v6/crashlytics/android

As far as I can tell the part about "Additional Installation Steps" isn't specific to manual linking, is it? I also get the described error about "Crashlytics build ID" if I just rely on autolinking without doing those additional steps. 

Finding the cause of the issue was pretty difficult since the page doesn't show up when you search for the error on Google.

I would recommend to add a reference to the "Additional Installation Steps" in the "Quick Start" guide for Android.

**Comment by Ehesp** [comment]
Good point! Also looks like iOS Installation Steps need adding.

**Comment by cesar3030** [comment]
@3rfan I completely agree! Thanks for creating this issue, it saved me a lot of time...

@Ehesp Also that would be nice to explain what the additional step for iOS does (sorry for my ignorance if it is obvious but i'm not from the mobile world and I'm sure I'm not the only one around her 😄 ). It was working fine without doing the additional steps, I could see the crashes on the firebase console. 

I did the additional steps but I've no idea what it changed so I'm not sure if it is working properly. Is the script uploading `dSYM`?

**Comment by Ehesp** [comment]
I've reworked the Crashlytics docs a bit and broken out the additional steps + manual installation. Cheers.

**Comment by cesar3030** [comment]
@Ehesp Could you just help me understand what `"${PODS_ROOT}/Fabric/run"` does?
