### ISSUE TITLE
TypeError: new _mlvision.default().visionImageLabelerOptions is not a function

### ISSUE THREAD

**Issue by sidpauhal** [invertase/react-native-firebase#2663]
Hi I am trying to integrate ml-vision in project

But I am not able to integrate the lib properly in project 
Documentation is also not clear

--*OS*-
Android

--*Package.json file *-
dependencies": {
    "@react-native-firebase/app": "^6.0.0",
    "@react-native-firebase/ml-vision": "^6.0.0",
    "react": "16.9.0",
    "react-native": "0.61.1",
    "react-native-file-share-intent": "^1.1.2",
    "rn-fetch-blob": "^0.11.2"
  },

My App.js file

import vision, { firebase } from '@react-native-firebase/ml-vision';

const options = new vision().VisionImageLabelerOptions();
options.setConfidenceThreshold(0.8);

const labels = await vision().imageLabelerProcessImage(uri, options);

console.log(labels);

I am getting yellow warning
TypeError: new _mlvision.default().visionImageLabelerOptions is not a function
new _mlvision.default().visionImageLabelerOptions is undefined

Please help

**Comment by Ehesp** [comment]
Sorry it looks like that example was wrong (we changed the API before release).

This is the correct syntax:

```js
const labels = await vision().imageLabelerProcessImage(uri,{
  confidenceThreshold: 0.8,
});
```

**Comment by sidpauhal** [comment]
> Sorry it looks like that example was wrong (we changed the API before release).
> 
> This is the correct syntax:
> 
> ```js
> const labels = await vision().imageLabelerProcessImage(uri,{
>   confidenceThreshold: 0.8,
> });
> ```

Hi thanks
but now I am getting error
'You attempted to use an optional API thats not enabled natively.

To enable ML Kit Vision Image Labeler please set the 'react-native ml_vision_image_label_model' key to true in your firebase.json file and rebuild your Android App'

where can I find this firebase.json file 
I only have google-services.json file in my android/app/ folder

**Comment by sidpauhal** [comment]
As per the docs I have added firebase.json file in my project root folder with these contents

{
  'react-native': {
    // on device face detection
    ml_vision_face_model: true,
    // on device text recognition
    ml_vision_ocr_model: true,
    // on device barcode detection
    ml_vision_barcode_model: true,
 
    // on device image labelling
    // TODO: merge these options into one
    ml_vision_label_model: true,
    ml_vision_image_label_model: true,
  },
}


but it is still not working and showing the same error.

Where should I place this firebase.json file?

**Comment by Ehesp** [comment]
It should be in the root of your project, like so: https://github.com/invertase/react-native-firebase/blob/master/tests/firebase.json

**Comment by Salakar** [comment]
> As per the docs I have added firebase.json file in my project root folder with these contents
> 
> {
> 'react-native': {
> ml_vision_face_model: true,
> ml_vision_ocr_model: true,
> ml_vision_barcode_model: true,
> ml_vision_label_model: true,
> ml_vision_image_label_model: true,
> },
> }
> 
> but it is still not working and showing the same error.
> 
> Where should I place this firebase.json file?

The contents of the JSON file also need to be valid JSON, the above is not valid JSON.

**Comment by sidpauhal** [comment]
Hi

I have sorted it out by fixing my firebase.json file Now it looks like this

{
  "react-native": {
    "ml_vision_face_model": true,
    "ml_vision_ocr_model": true,
    "ml_vision_barcode_model": true,
    "ml_vision_label_model": true,
    "ml_vision_image_label_model": true
  }
}

Also firebase app module is also required to use vision feature
If you dont require it will ignore firebase.json file

include like this in your file

import firebase from '@react-native-firebase/app';
import vision from '@react-native-firebase/ml-vision';

let uri = this.state.fileUrl;
if(uri == ''){
	return;
}

try{
	const labels = await vision().imageLabelerProcessImage(uri,{confidenceThreshold: 0.8,	});
	alert(JSON.stringify(labels));
} catch (error) {
	alert(error.message);
}

**Comment by Ehesp** [comment]
Glad to hear it's working. We do mention in the docs `app` is required:

![image](https://user-images.githubusercontent.com/842078/66031697-d308bc00-e4fb-11e9-8aab-5fdfe9bb920b.png)

**Comment by helsey33** [comment]
> Hi
> 
> I have sorted it out by fixing my firebase.json file Now it looks like this
> 
> ```
> {
>   "react-native": {
>     "ml_vision_face_model": true,
>     "ml_vision_ocr_model": true,
>     "ml_vision_barcode_model": true,
>     "ml_vision_label_model": true,
>     "ml_vision_image_label_model": true
>   }
> }
> ```
> 
> Also firebase app module is also required to use vision feature
> If you dont require it will ignore firebase.json file
> 
> include like this in your file
> 
> ```
> import firebase from '@react-native-firebase/app';
> import vision from '@react-native-firebase/ml-vision';
> 
> let uri = this.state.fileUrl;
> if(uri == ''){
> 	return;
> }
> 
> try{
> 	const labels = await vision().imageLabelerProcessImage(uri,{confidenceThreshold: 0.8,	});
> 	alert(JSON.stringify(labels));
> } catch (error) {
> 	alert(error.message);
> }
> ```

Hi,
Can you tell me what the uri in this case stands for. I tried using local images in my project directory but it doesn't seem to work.
