### ISSUE TITLE
🔥 analytics().setUserProperty does not show up in Firebase console

### ISSUE THREAD

**Issue by kevinvugts** [invertase/react-native-firebase#2664]
##  Issue

Describe your issue here

When a user logs into my app I set userproperties that should appear next to analytics and crashlytics reports. The code looks as following:

### login / get me function that should set the user properties in the success callback

```
export default function getUser() {
  return (dispatch) => {
    dispatch({type: GET_USER});
    return client
      .getMe({
        fields: ['*', 'avatar.*'],
      })
      .then(response => {
        dispatch(getUserSuccess(response));
        dispatch({type: GET_USER_ROLES});
        const userId = response.id;
        const userEmail = response.email;
        client.getRoles()
          .then(response => {
           const userType = response.data[0].name;
           dispatch(getUserRolesSuccess(response));
           GAManager.setUserProperties(userId, userEmail, userType);
           CrashlyticsManager.setUserProperties(userId, userEmail, userType);
          }).catch(error => {
            dispatch(getUserRolesFail(error))
          });
      }).catch(error => {
        dispatch(getUserFail(error))
      });
  };
}
```
### A helper class for RNFirebase analytics

```
import analytics from '@react-native-firebase/analytics';
analytics().setAnalyticsCollectionEnabled(true);


/**
 * A simple Google Analytics Helper Class
 * that might be overkill for now, but it's just for tutorial purposes.
 *
 * https://redux.js.org/basics/usage-with-react
 * More on this topic: https://invertase.io/oss/react-native-firebase/v6/analytics/quick-start
 */
export default class GAManager {
  static setScreen = (screenname = 'default') => {
    const cleanScreenName = GAManager.replaceWhiteSpaceWithUnderscore(screenname);
    console.log("SETTING_SCREEN: ", cleanScreenName);
    analytics().setCurrentScreen(cleanScreenName, cleanScreenName);
  }

  static replaceWhiteSpaceWithUnderscore = (string) => {
    return string.replace(/ /g, "_");
  }

  static logEvent = (eventName, parameters) => {
    console.log("LOG_EVENT: ",eventName);
    console.log("PARAMETERS: ", parameters);
    analytics().logEvent(eventName, parameters);
  };

  static setUserProperties = async (userId, userEmail, userType) => {
     console.log("THE USER TYPE >>>>>", userType);
    await Promise.all([
      analytics().setUserId(userId),
      analaytics().setUserEmail(userEmail),
      analytics().setUserProperty('freemiumOrPremiumMember', userType)
    ]);
  }
}
```

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
      Memory: 134.21 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.npm/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.1.tar.gz => 0.59.8 
```

- **Platform that you're experiencing the issue on**:
  - [ x] iOS
  - [ ] Android
  - [ x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.0.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `analytics()`
- **Are you using `TypeScript`?**
  - `Y/**N**`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Ok so there is a couple of issues with the code you posted above, which may be causing issues:

1. `getUser` is incorrectly chaining the promises. You shouldn't be nesting `then` & `catch` when you're already inside of a promise.
2. `GAManager.setUserProperties` is a promise, but you don't wait for it.
3. The nested `catch` may not catch the errors, which could be causing problems you don't see.

**Comment by kevinvugts** [comment]
> * `GAManager.setUserProperties` is a promise, but you don't wait for it.

Hi Ehesp,

Thank you for your reply.

1. I agree on that but that shouldn't cause the issue in my opinion
2. I am using async await in the Google Analaytics Manager helper class. This should do the trick, right? Or am I wrong. :( 
3. I agree on that

I just tested a different scenario and it does work when it is set right in front of a analytics().logEvent() action. Like this:

```
GAManager.setUserProperty('freemiumOrPremiumMember', userType)
GAManager.setScreen(`pin_popup_${privilege.title}`);
GAManager.logEvent("new_privilege_claim", { value: privilege.privilege_value, action: "claim_privilege", privilege: privilege.title, category_id: privilege.category.id, category_name: privilege.category.title });
```

Is this how the library works? You set it right before an logEvent() or can you set it in any point in time?

**Comment by Ehesp** [comment]
> I am using async await in the Google Analaytics Manager helper class. This should do the trick, right? Or am I wrong. :(

Wrong I'm afraid. You're correct in saying that `GAManager.setUserProperties` awaits for the `Promise.all` to complete, however in this `setUserProperties` is called but in the flow of your parent function, it won't wait for the `Promise.all` to complete. So your parent function could well be finishing before `setUserProperties` completes.

```
let userId;
let userEmail;
let userType;

return client
      .getMe({
        fields: ['*', 'avatar.*'],
      })
      .then(response => {
        dispatch(getUserSuccess(response));
        dispatch({type: GET_USER_ROLES});
        userId = response.id;
        userEmail = response.email;

        return client.getRoles();
	  })
      .then(response => {
         userType = response.data[0].name;
         dispatch(getUserRolesSuccess(response));

		// Wait for it to resolve
		return GAManager.setUserProperties(userId, userEmail, userType);
      })
	  .then(() => {
		return CrashlyticsManager.setUserProperties(userId, userEmail, userType);
      }).catch(error => {
        // handle error here for all
      });
```

Something like that should work - howver that is obviously untested and could have a few typeerrors.

**Comment by kevinvugts** [comment]
> let userId;
> let userEmail;
> let userType;

Thank you for your code sample. I made some changes and it is executing the promises correctly. However it still does not appear in the firebase debug console. It's not being set I guess.

**Comment by kevinvugts** [comment]
@Ehesp 

I finally found the issue why it didn't report to firebase. In the first version of the v6.0.0 docs there was a userproperty called setUserEmail() and this was causing it to fail in the promise. 🗡 

Thanks for you help anyways. I am closing this issue now.
