### ISSUE TITLE
textRecognizerProcessImage() - [vision/file-not-found] 

### ISSUE THREAD

**Issue by jalmendhry** [invertase/react-native-firebase#2666]
Hi 

This issue has been raised on the Discord channel.

This is a bug with **IOS** and works fine on Android

Currently while using React-native-camera (v3.4.0) and @react-native-firebase/app & /ml-vision v6.0.0

I am receiving the error `[vision/file-not-found] The local file specified does not exist on the device.` when calling function `vision().textRecognizerProcessImage(data.uri)`

Temporary work around is to remove the file:// scheme from the URI

file:///var/mobile/Containers/etc...

All I had to do was delete the file scheme, so the URI ended up being:
/var/mobile/Containers/etc...

Cheers

**Comment by Salakar** [comment]
Guessing this issue was raised based on the conversation on Discord;

![image](https://user-images.githubusercontent.com/5347038/65981214-8af08780-e470-11e9-8ee0-3dab4c95e01e.png)


Thanks for making an issue

**Comment by Salakar** [comment]
Hey 👋 this issue should now be fixed in v6.0.1, thanks. [[release notes]](https://invertase.io/oss/react-native-firebase/releases/v6.0.1)
