### ISSUE TITLE
undefined is not an object(evalutating 'FirebaseModule.googleApiAvailability'

### ISSUE THREAD

**Issue by connercms** [invertase/react-native-firebase#267]
Receiving "undefined is not an object(evalutating 'FirebaseModule.googleApiAvailability') error on app startup

Stacktrace:
get @ firebase.js:137:26
Firebase @ firebase.js:75:14
initializeApp @ firebase.js:123:57
unknown @ FirebaseController.js:3:42

My FirebaseController file looks like 
```
import RNFirebase from 'react-native-firebase'

const firebase = RNFirebase.initializeApp({debug: true})

export default firebase
```

Running on LG v20 Nougat 7.0

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): Mac
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
4. React Native version (e.g. 0.45.1):  0.46.2
5. RNFirebase Version (e.g. 2.0.2):  2.0.4

My build.gradle
```
//...
dependencies {
  compile(project(':react-native-firebase')) {
    transitive = false
  }
  compile 'com.google.firebase:firebase-core:10.0.1'
  compile "com.google.firebase:firebase-auth:11.0.0"
  compile "com.google.firebase:firebase-messaging:11.0.0"
  compile project(':react-native-config')
  compile project(':react-native-vector-icons')
  compile project(':react-native-linear-gradient')

  compile fileTree(dir: "libs", include: ["*.jar"])
  compile "com.android.support:appcompat-v7:23.0.1"
  compile "com.facebook.react:react-native:+"  // From node_modules
}
//...
apply plugin: "com.google.gms.google-services"
```

**Comment by Ehesp** [comment]
Hi please add Google Services to your build gradle file. Docs will show you how.
Cheers

**Comment by connercms** [comment]
app level build.gradle? I have apply plugin: "com.google.gms.google-services" at the bottom of the file. My project level build.gradle has classpath 'com.google.gms:google-services:3.0.0' under dependencies

**Comment by Ehesp** [comment]
On my phone sorry, but this line: compile "com.google.android.gms:play-services-base:11.0.0"

**Comment by connercms** [comment]
Added and still receiving error

**Comment by connercms** [comment]
Have tried uninstalling and reinstalling the package as well as
```
rm -rf node_modules 
rm -fr $TMPDIR/react-*
npm i
```

Am I configuring correctly? Whenever I need to use firebase I just reference my export from my FirebaseController.js file?

**Comment by chrisbianca** [comment]
@connercms Have you added the required RNFirebase module to MainApplication.java as per: http://invertase.io/react-native-firebase/#/installation-android?id=_2-link-rnfirebase?

**Comment by connercms** [comment]
@chrisbianca I think that was it. Unlinked, Uninstalled and removed node modules and cleared cache again then reinstalled and relinked . It didn't automatically link RNFirebasePackage(), but instead automatically linked the admob package instead.  Replaced that with RNFirebasePackage() and appears to be working. Sorry to open a thread for my error!

**Comment by chrisbianca** [comment]
We purposefully don't link any packages automatically as it's up to the user which Firebase modules they wish to include.   Glad you've resolved the issue, I'll close this off now
