### ISSUE TITLE
v6 support for iOS 9

### ISSUE THREAD

**Issue by t-ricci-enhancers** [invertase/react-native-firebase#2672]
Hi, I was wondering why is it that the version 6 of react-native-firebase requires iOS 10, when it can run on a very old Android version (API 16). (link to docs: https://invertase.io/oss/react-native-firebase/v6)

React native itself supports iOS 9, so is there a technical limitation that makes it impossible to have react-native-firebase support iOS 9?

**Comment by Ehesp** [comment]
Related https://github.com/invertase/react-native-firebase/issues/2668

**Comment by Salakar** [comment]
@t-ricci-enhancers I think the docs need updating, iOS9 is supported on all modules except for messaging & notifications (these two require 10+)

**Comment by t-ricci-enhancers** [comment]
Yeah, I'm using FCM. Do we know why is it that iOS 9 can't be supported for FCM?

**Comment by mikehardy** [comment]
The NotificationCenter changes in the OS between iOS9 and iOS10 are enormous, If I were to guess it's like a completely different set of APIs to handle iOS9 vs iOS10, that was the state of the previous discussion. Luckily iOS9 should die shortly based on my related research into how many people were using it, and what devices are dropped when  you move to iOS10, but unfortunately I only have 2 physical devices for iOS and one can't go past iOS9, so I feel your pain

**Comment by t-ricci-enhancers** [comment]
Uhm, but if I use react-native 6 with the 5.x version of react-native-firebase I should be good, right?

**Comment by Ehesp** [comment]
You can't use both together sorry.

**Comment by mikehardy** [comment]
the supported versions charge on rnfirebase.io show that yes, react-native-firebase v5.5.x and react-native 0.60+ work fine together. That's my production setup.
