### ISSUE TITLE
v6 mesagging - crash at init

### ISSUE THREAD

**Issue by 15matias15** [invertase/react-native-firebase#2674]
## Issue

I'm using haul packager (webpack) and the app it's crashing at init, with this message

![Screenshot_20191002-135911_Happy Pineapple Dev](https://user-images.githubusercontent.com/41986785/66042952-28ee5b80-e51e-11e9-8f8a-126f7a6f6725.jpg)
![Screenshot 2019-10-02 at 13 59 45](https://user-images.githubusercontent.com/41986785/66042961-2c81e280-e51e-11e9-8682-386f82650c2e.png)

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
ext {
        minSdkVersion = 18
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }

 dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath 'com.google.gms:google-services:4.2.0'
    }
```

#### `android/app/build.gradle`:

```groovy
...
 implementation project(':@react-native-firebase_app')
 implementation project(':@react-native-firebase_messaging')
...
```

#### `android/settings.gradle`:

```groovy
...
include ':@react-native-firebase_app'
project(':@react-native-firebase_app').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-firebase/app/android')
include ':@react-native-firebase_messaging'
project(':@react-native-firebase_messaging').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-firebase/messaging/android')
...
```

#### `MainApplication.java`:

```java
...
public void onCreate() {
    super.onCreate();
    SoLoader.init(getApplicationContext(), false);
...
```

#### `AndroidManifest.xml`:

```xml
...
    <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />
...
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 978.33 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.0.0`
- **`Firebase` module(s) you're using that has the issue:**
  - 
```
    "@react-native-firebase/app": "6.0.0",
    "@react-native-firebase/messaging": "6.0.0"
```
- **Are you using `TypeScript`?**
  - `Y`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
The error seems pretty descriptive - I contemplated not using metro but it already comes configured with all the stuff you need - seems like you're missing some webpack plugin or config thing? I'm not sure anyone is going to be able to help with this, but I know if you check maybe the reactxp repo, specifically the TodoList example, you might find some inspiration on how to configure webpack/haul to correctly work with react-native etc

**Comment by Ehesp** [comment]
Can't say we've ever used the haul packager. Unfortunately we don't have time to investigate into issues with "non-standard" packagers, however we'll welcome PRs to fix any issues with them and this library.

Going to close this for now, happy to keep the discussion going though.

**Comment by mikehardy** [comment]
@Ehesp just for context - it is my understanding that this is the typical way you would want to do things if you were also covering web at the same time (thus my pointer to ReactXP which is like react-native-windows in that it allows react-native-like programming but extends you to web at the same time. I'm guessing that's the use case here - either someone wanting to do react-native-windows/reactxp or someone so familiar with the web use cases of react (where metro is I think never used?) that they want to use familiar and arguably superior tools (webpack + haul and/or gulp etc). With the react-native-firebase API being so close to the firebase javascript SDK API this is actually in my product roadmap, but I haven't tried it yet so never seen the error above, personally.

**Comment by brownieboy** [comment]
I got this same error.

Maybe report in the Haul repository?
