### ISSUE TITLE
 Exception java.lang.OutOfMemoryError: std::bad_alloc

### ISSUE THREAD

**Issue by SamMatthewsIsACommonName** [invertase/react-native-firebase#268]
Hi guys,
I'm having constant crashes now with the following error on android:

Exception java.lang.OutOfMemoryError: std::bad_alloc
com.facebook.react.bridge.WritableNativeArray.pushNull (WritableNativeArray.java)
io.invertase.firebase.Utils.buildArray (Utils.java:270)
io.invertase.firebase.Utils.castValue (Utils.java:160)
io.invertase.firebase.Utils.buildMap (Utils.java:360)
io.invertase.firebase.Utils.castValue (Utils.java:162)
io.invertase.firebase.Utils.snapshotToMap (Utils.java:99)
io.invertase.firebase.database.RNFirebaseDatabaseReference.handleDatabaseEvent (RNFirebaseDatabaseReference.java:170)
io.invertase.firebase.database.RNFirebaseDatabaseReference.access$000 (RNFirebaseDatabaseReference.java:26)
io.invertase.firebase.database.RNFirebaseDatabaseReference$1.onChildAdded (RNFirebaseDatabaseReference.java:53)
com.google.android.gms.internal.zzbox.zza ()
com.google.android.gms.internal.zzbqx.zzZV ()
com.google.android.gms.internal.zzbra$1.run ()
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6077)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:866)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:756)

Is there something that immediately sticks out from that crash report? I'm going to spend today slowly debugging what is going on in those two R.N.F. java files but I wouldn't say I know what I'm doing when it comes to java code haha.

### Environment

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Android Studio
4. React Native version (e.g. 0.45.1): 0.44.2
5. RNFirebase Version (e.g. 2.0.2): 1.1.0

**Comment by Ehesp** [comment]
There was a fix @chrisbianca did for Android DB which reworked some of the database code in V2 (I think). There was a problem with an infinity loop.... Suggest you upgrade!

**Comment by SamMatthewsIsACommonName** [comment]
Will try that cheers!

**Comment by SamMatthewsIsACommonName** [comment]
That did it. Thanks!

**Comment by ShariqMush** [comment]
@Ehesp What causes this issue?

**Comment by chrisbianca** [comment]
@ShariqMush this issue happened when there was a sparsely populated array like field of data in the realtime database. It has been fixed in v2+
