### ISSUE TITLE
Native module cannot be null.

### ISSUE THREAD

**Issue by irohitb** [invertase/react-native-firebase#2684]
## Issue
1. I haven't used any pods file yet but still, I did pod init
2. Also, I am using `"react-native": "0.60.6"`
3. I haven't made any changes in AppDelegate.m

**Procedure 1**

[Following the instructions here](https://invertase.io/oss/react-native-firebase/v6/app/quick-start), I did

```
yarn add @react-native-firebase/app
yarn add @react-native-firebase/auth
```

and then I did add `GoogleService-Info.plist` 

<img width="266" alt="Screenshot 2019-10-04 at 5 01 19 PM" src="https://user-images.githubusercontent.com/32276134/66205401-f2a20f00-e6ca-11e9-8dfe-94cf8a8ca721.png">

Then on running the app, I was expecting everything to go fine but I got following error in terminal 

**`ExceptionsManager.js:86 Native module cannot be null.`**

Do I need to run react-native link or something like that command as well?
 
**Procedure 2**

Then I did [iOS Manual initialization](https://invertase.io/oss/react-native-firebase/v6/app/ios)

Where I added 

` pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app' ` in my pod file 

this gave following error 

<img width="784" alt="Screenshot 2019-10-04 at 5 07 18 PM" src="https://user-images.githubusercontent.com/32276134/66205748-ccc93a00-e6cb-11e9-99b6-30697973e525.png">

Then I added firebase/core which resulted in following error 

<img width="778" alt="Screenshot 2019-10-04 at 5 08 55 PM" src="https://user-images.githubusercontent.com/32276134/66205772-e4082780-e6cb-11e9-8136-4de6efc703bf.png">

As instructed I did, pod install --repo-update which gave following error 

<img width="742" alt="Screenshot 2019-10-04 at 5 09 39 PM" src="https://user-images.githubusercontent.com/32276134/66205816-013cf600-e6cc-11e9-8ab8-0075117b2d62.png">

Lastly, I went to firebase site and instead of using firebase/core I added firebase/auth which didn't work either

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'frontend' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for frontend

  target 'frontend-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'frontendTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"frontend"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`` output:**

```
System:
    OS: macOS Mojave 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 156.28 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    Android SDK:
      API Levels: 21, 23, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
      System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5014246
    Xcode: 10.0/10A255 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.6 => 0.60.6
```

- **Platform that you're experiencing the issue on**:
  - [ x] iOS
  - [ ] Android
  - [x ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Hello. I see something very strange in one of them logs. It's trying to install `Firebase/core` pod, which it should be `Core` (capital C). Let me take a look to see why that is at all possible!

**Comment by Ehesp** [comment]
Infact, can you delete your own Podfile changes, delete the `Podfile.lock` and do a `pod install --repo-update`?

**Comment by irohitb** [comment]
@Ehesp  Did that, To summarize, this is my pod file now 

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'frontend' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for frontend

  target 'frontend-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'frontendTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

removed Podfile.lock and then did `pod install --repo-update`. Same error on running the app 

```
Native module cannot be null.
handleException @ ExceptionsManager.js:86
handleError @ setUpErrorHandling.js:23
reportFatalError @ error-guard.js:42
guardedLoadModule @ require.js:197
metroRequire @ require.js:122
(anonymous) @ reactBatchedUpdates.native.js:7
executeApplicationScript @ debuggerWorker.js:40
(anonymous) @ debuggerWorker.js:72
```
These are the logs in my terminal after pod install --repo-update and before  running the project 

<img width="986" alt="Screenshot 2019-10-04 at 5 43 04 PM" src="https://user-images.githubusercontent.com/32276134/66206713-845f4b80-e6ce-11e9-9928-a08130461bbe.png">

**Comment by irohitb** [comment]
> Hello. I see something very strange in one of them logs. It's trying to install `Firebase/core` pod, which it should be `Core` (capital C). Let me take a look to see why that is at all possible!

That could be typo from my end

**Comment by irohitb** [comment]
> Hello. I see something very strange in one of them logs. It's trying to install `Firebase/core` pod, which it should be `Core` (capital C). Let me take a look to see why that is at all possible!

That was a type from my end

**Comment by irohitb** [comment]
There was error with my pods, Deleting the entire iOS folder and starting fresh fixed it,

**Comment by alammoiz** [comment]
Getting same error @irohitb . How did you resolve that?
