### ISSUE TITLE
Equivalent of onNotificationOpened in 6.x ?

### ISSUE THREAD

**Issue by alexsegura** [invertase/react-native-firebase#2690]
## Issue

Hi,

I'm trying to migrate to version 6.x, but I can't find a way to implement the same behavior as `onNotificationOpened` on 5.x, i.e when the user taps on a notification in the system tray. 
I want to trigger a screen navigation when the notification is tapped. 

From what I understand in the docs, I should be using `setBackgroundMessageHandler` (is that correct?), but it seems it's never called.

You can see the diff [here](https://github.com/coopcycle/coopcycle-app/compare/bump-react-native-firebase)

I'm not using Firebase Messaging on iOS

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

https://github.com/coopcycle/coopcycle-app/blob/43a479ef537cdd2588606311732b4a9a60ba42b4/android/build.gradle

#### `android/app/build.gradle`:

https://github.com/coopcycle/coopcycle-app/blob/43a479ef537cdd2588606311732b4a9a60ba42b4/android/app/build.gradle

#### `android/settings.gradle`:

https://github.com/coopcycle/coopcycle-app/blob/bbc09b5f062d376db63faff25f6d018ba824cf65/android/settings.gradle

#### `MainApplication.java`:

https://github.com/coopcycle/coopcycle-app/blob/43a479ef537cdd2588606311732b4a9a60ba42b4/android/app/src/main/java/fr/coopcycle/MainApplication.java

#### `AndroidManifest.xml`:

https://github.com/coopcycle/coopcycle-app/blob/43a479ef537cdd2588606311732b4a9a60ba42b4/android/app/src/main/AndroidManifest.xml

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 268.45 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.16.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.0.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `messaging`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
This may be related to #2566

**Comment by alexsegura** [comment]
Thanks a lot @mikehardy 

I wanted to know if I was right to expect the same feature (as this is a major bump). 
Answer seems to be "yes", cool 😊

I would love to contribute, but I'm afraid I don't have enough skills for that 😔
The only thing I can help with is tiny documentation issues like #2689, or testing

I can totally wait and stick with 5.x until it's ready. 
You can close this issue if you think it's a duplicate, or brings too much noise
