### ISSUE TITLE
I don't receive notification when I set notification for next day

### ISSUE THREAD

**Issue by iutin** [invertase/react-native-firebase#2692]
const dateObj = moment(date, "DD-MM-YYYY").toDate();
      let dueDate = moment(dateObj).subtract(1, "d");
      dueDate = dueDate.set("hour", 8);
      dueDate = dueDate.set("minute", 10);
      dueDate = dueDate.toISOString();

 firebase
      .notifications()
      .scheduleNotification(this.buildNotification(title, body, regiPlate), {
        fireDate: moment.utc(dueDate).toDate().getTime()
      });

This code doesn't work.
 but if change date like this, it is works good
 const date = new Date();
 date.setMinutes(date.getMinutes() + 1);
 firebase
      .notifications()
      .scheduleNotification(this.buildNotification(title, body, regiPlate), {
        fireDate: date.getTime()
      });

do you have any advice? Thanks

**Comment by mikehardy** [comment]
My advice is to always follow issue templates provided by repositories when opening issues. Without the information there no one can effectively offer advice, sorry

**Comment by mikehardy** [comment]
(note: not saying this is not an issue - just open a new issue and provide all the info from the template)
