### ISSUE TITLE
Cancel notification not works

### ISSUE THREAD

**Issue by ermand-hoxha** [invertase/react-native-firebase#2696]
I'm using react-native-firebase: 5.5.6 and react-native:0.59.10 on my project. I've created some schedule notifications.

cancelNotification = async (Id) => {
    try{
        await firebase.notifications().cancelNotification(Id);
    }
    catch(e){
        console.error(e);
    }
}
It not works only if put an interval time. As i tested it, if i add an interval time example by "minute", after some notifications i decide to delete it, but notifications keep coming in interval by 1 minute.

**Comment by mikehardy** [comment]
Canceling an alarm schedule is different from canceling a notification - I haven't dived into the react-native-firebase code to see how it does what it does, but that difference will be at the root of it https://stackoverflow.com/a/35342066/9910298

**Comment by ermand-hoxha** [comment]
That doesn't help me @mikehardy . I haven't found a solution yet.
