### ISSUE TITLE
getInitialNotification not called when app is closed

### ISSUE THREAD

**Issue by luifer94** [invertase/react-native-firebase#2699]
getInitialNotification not called when app is closed for both: Android and IOS. Here is the scenario:
* Notication + Data 
* I call:  await firebase.notifications().getInitialNotification() from componentDidMount on AppComponent and it always returns null.
* When app is on Foreground or/and Background onNotification and onNotificationOpened are working as expected.
* I have setup all as the guide suggests
* I am using dynamic links, cloud messasing and phone auth(all of them work fine)
* Important Libraries:
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-firebase": "5.5.6",
    "react-navigation": "4.0.10", ( I think here is the problem because it handles the navigation or am I wrong)?
    "react-native-gesture-handler": "1.4.1", //used by react-navigation
    "react-native-screens": "1.0.0-alpha.23", //used by react-navigation
    "react-native-reanimated": "1.3.0", //used by react-navigation

**Comment by lovekothari123** [comment]
Same problem from my side.
i am also not getting any response(payload) while application. In background/killed state
i am using this :-

import firebase from "react-native-firebase";
import {
Notification,
NotificationOpen,
RemoteMessage,
Firebase
} from "react-native-firebase";
firebase
.notifications()
.getInitialNotification()
.then((notificationOpen: NotificationOpen) => {
if (notificationOpen) {
alert("get data testing done")
}
});

also i am trying that 👎 but did't get any solution

firebase.messaging().onMessage((message: RemoteMessage) => {
// Process your message as required
console.log("Notification open App closed in open " + message);
});

If is there any one who can resolved this issues please update.

**Comment by mikehardy** [comment]
Neither of these follow the template, so I have no idea sorry :cry:
