### ISSUE TITLE
Analytics Debug view

### ISSUE THREAD

**Issue by stoneman1** [invertase/react-native-firebase#27]
Hello,

Was just wondering if you are going to add debug view support in the near future?

https://firebase.google.com/docs/analytics/debugview

**Comment by Salakar** [comment]
@stoneman1 

This is something you enable via adb shell on android or xcode command line arguments. RNFirebase has analytics built in, so if you enable this as the docs on the link above suggests and use the methods as documented [here](https://github.com/invertase/react-native-firebase/blob/master/docs/api/analytics.md) then you're good to go.
