### ISSUE TITLE
How working cache ?

### ISSUE THREAD

**Issue by NachosSs** [invertase/react-native-firebase#270]
(Please write your issue here along with the environment details below. Include any key files which will help us to debug, such as your `Podfile` and/or `app/build.gradle` file).

### Environment

1. Target Platform (e.g. iOS, Android):
IOS / ANDROID
2. Development Operating System (e.g. macOS Sierra, Windows 10):
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
4. React Native version (e.g. 0.45.1):
0.43.4
5. RNFirebase Version (e.g. 2.0.2):
2.0.2

Hi,
I have a screen which is refresh in every click.
When i try to modify data in one device, and refresh the screen on other device, the update does not appear. But if i stop the app and if i come again on the screen, the update appear.
Is there any cache on same request with same parameter ? I don't find information on this.

Thanks in advance.

**Comment by Salakar** [comment]
@NachosSs can you provide a sample of your code where you are listening to the data, you need to be using .on() for realtime updates.

**Comment by NachosSs** [comment]
I don't want realtime data because my use case is like list of article.  When i click on article i show the detail. I would like to just refresh the article when i come back on the detail screen.

List => Click on article 1 => Detail article 1 => Return to list => click again on article 1 => Detail article 1 (not up to date) 

the function above is called every time i go to the detail of an article
```
  /**
  * Méthode permettant de récupérer le détail des evenements d'un user
  **/
  static fetchDetailEvent (eventId) {
    return firebase.database().ref('events').orderByKey().equalTo(eventId).once('value')
      .then(function (snapshot) {
        return snapshot.child(eventId)
      })
      .catch((err) => {
        console.tron.log(err)
        return { 'status': 'failure' }
      })
  }

```

Thanks for your help.

**Comment by Ehesp** [comment]
This is expected behaviour with `on`:

![image](https://user-images.githubusercontent.com/842078/28530400-9a66b208-708b-11e7-9a56-9e0543fafc9c.png)

How you force a refresh I'm not actually sure...  Try out `ref.keepSynced(true);`?

**Comment by NachosSs** [comment]
i will try, but i have not enabled offline capacity. (persistenceEnabled: true).
So i don't understand why there is this behavior

**Comment by NachosSs** [comment]
I tried, it did notwork :(

**Comment by chrisbianca** [comment]
@NachosSs I'm not sure there's anything else we can suggest here. @Ehesp has pointed you at the documentation to explain how this works - and this is based on how the native SDKs behave so we have no control over it.

Please let us know if you're still experiencing issues.
