### ISSUE TITLE
v6 : Function with region not working anymore

### ISSUE THREAD

**Issue by rphlmr** [invertase/react-native-firebase#2700]
## Issue

All my functions are localized to "europe-west1".
I read the documentation and try : 

```
import firebase from "@react-native-firebase/app";
import "@react-native-firebase/firestore";
import "@react-native-firebase/auth";
import functions from '@react-native-firebase/functions';
 
functions('europe-west1').httpsCallable(...);
```
But `functions` only accept `ReactNativeFirebase.FirebaseApp` arg.

So, I try to set my function region with the  firebase app instance : 

```
import firebase from "@react-native-firebase/app";
import "@react-native-firebase/firestore";
import "@react-native-firebase/functions";
import "@react-native-firebase/auth";

const functions = firebase.app().functions("europe-west1");
```

In this case, `functions` accept the region arg, but no call are made :( 

If I look at the  source code (function package) : 
```
class FirebaseFunctionsModule extends FirebaseModule {
  constructor(...args) {
    super(...args);
    this._customUrlOrRegion = this._customUrlOrRegion || "europe-west1";
    this._useFunctionsEmulatorOrigin = null;
  }

  httpsCallable(name) {
    return data => {
      const nativePromise = this.native.httpsCallable(this._useFunctionsEmulatorOrigin, name, {
        data
      });
      return nativePromise.catch(nativeError => {
        const { code, message, details } = nativeError.userInfo || {};
        return Promise.reject(
          new HttpsError(
            HttpsErrorCode[code] || HttpsErrorCode.UNKNOWN,
            message || nativeError.message,
            details || null,
            nativeError
          )
        );
      });
    };
  }
```

It seems that we never pass "_customUrlOrRegion", I'm right ?

Did I forgot something ?

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Salakar** [comment]
The region arg is internally prepended to the args by the FirebaseModule class and does get sent to native: https://github.com/invertase/react-native-firebase/blob/master/packages/functions/android/src/main/java/io/invertase/firebase/functions/UniversalFirebaseFunctionsModule.java#L42

We also have end to end tests that confirm this is working on both iOS & Android: https://github.com/invertase/react-native-firebase/blob/master/packages/functions/e2e/functions.e2e.js#L43-L87 

So i'm not sure what the issue is here, can you add more detail, you've not provided version information or mentioned which platform you're having an issue on.

Thanks

**Comment by rphlmr** [comment]
Thanks, It was on IOS. I clean build folder, pods and re install and that's ok.

Sorry for the alert :/
