### ISSUE TITLE
+[FIRAnalytics setAnalyticsCollectionEnabled:]: unrecognized selector sent to class

### ISSUE THREAD

**Issue by TommyLeong** [invertase/react-native-firebase#2702]
## Issue

App Crashed, issue reported from xCode as following: 
```
[fatal][tid:com.facebook.react.RNFirebaseAnalyticsQueue] Exception '+[FIRAnalytics setAnalyticsCollectionEnabled:]: unrecognized selector sent to class 0x10a387ed0' was thrown while invoking setAnalyticsCollectionEnabled on target RNFirebaseAnalytics with params (
    1
)
```

I have spent ample amount of time in testing and reading before I decided to file this issue 😅Hopefully to get help from the community. 

Referred the following post:
https://github.com/invertase/react-native-firebase/issues/2275
https://github.com/invertase/react-native-firebase/issues/2272

Posted in stackoverflow:
https://stackoverflow.com/questions/58283563/firanalytics-setanalyticscollectionenabled-unrecognized-selector-sent-to-cl

I'm working on React Native upgrade from RN0.59.10 to RN0.60.0 (Using Podfile). Managed to build the project successfully (iOS & Android) but my app (iOS) crashed on native side when it reached the following line of code:
```[FIRAnalytics setAnalyticsCollectionEnabled:enabled];```

**A few things I have tried out:** 

1. Appending framework into xCode under **Link Binary with Libraries**
-  libRNFirebase.a 
Result in **build failure** (Command Ld failed with a nonzero exit code), hence I have removed the framework

I also removed the following framework which was appended earlier during <=RN59.10, since autolinking exist, I think this is no longer required
- FIRAnalyticsConnector.Framework
- FirebaseAnalytics.Framework
- FirebaseCore.Framework

2. I have tried the following (in sequence):

- 1.  remove node_modules + pods + podfile.lock
- 2. yarn cache clean + yarn install + pod install
- 3. react-native start --reset-cache 
- 4. rebuild: Build successfully but.. ```+[FIRAnalytics setAnalyticsCollectionEnabled:]: unrecognized selector sent to class```

3. Tried to downgrade react-native-firebase to lower version such as 5.5.5 and 5.2.0 but it doesn't seems to help. Understand from @mikehardy the method (setAnalyticsCollectionEnabled) should have exist in [5.19](https://firebase.google.com/support/release-notes/ios#version_5190_-_march_19_2019)
<img width="811" alt="Screenshot 2019-10-09 at 4 29 54 PM" src="https://user-images.githubusercontent.com/9990179/66464792-35d8f500-eab2-11e9-8f8f-7330a2b12bad.png"> However I believe this is not my issue, since I'm able to build the project successfully. 

4. Point my Firebase/Core to 6.9.0 in Podfile
``` pod 'Firebase/Core', '~> 6.9.0'``` but the result is the same. 

5. SURPRISINGLY... data is able to collect while I'm testing in [DebugView](https://firebase.google.com/docs/analytics/debugview).  I tapped on *Esc), so I'm allowed to bypass the crash and continue with my application.  Is this expected/normal? 

![Screenshot 2019-10-09 at 5 17 58 PM](https://user-images.githubusercontent.com/9990179/66468477-ca465600-eab8-11e9-9326-727aabec7c6b.png)
![Screenshot 2019-10-09 at 5 19 11 PM](https://user-images.githubusercontent.com/9990179/66468679-25784880-eab9-11e9-9e73-94f164d25b15.png)

**Question:**
However, does it make sense if we remove ```pod 'Firebase/Core', '~> 6.9.0'``` from podfile and point specifically to the pod we need?  

[Read more:](https://firebase.google.com/docs/ios/setup#available-pods)
> You no longer need to add the iOS pod Firebase/Core. This SDK included the Firebase SDK for Google Analytics. Now, to use Analytics (or any of the Firebase products that require or recommend the use of Analytics), you need to explicitly add the Analytics pod: Firebase/Analytics.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'testapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for testapp
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  # Crashlytics
  # pod 'Fabric', '~> 1.10.1'
  # pod 'Crashlytics', '~> 3.13.1'

  # FBSDK
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  # Testing
  pod 'react-native-config', :path => '../node_modules/react-native-config'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'react-native-http-cache', :path => '../node_modules/react-native-http-cache/ios'
  

  target 'testapp-tvOSTests' do
    inherit! :search_paths
  end

  target 'CPFToolReactNativeTests' do
    inherit! :search_paths
  end

end

target 'testapp-Shared' do
  use_frameworks!
end

target 'testapp-tvOS' do
  use_frameworks!
end

post_install do |installer|
 installer.pods_project.targets.each do |target|

  # Following action is to remove "React" from project's target, otherwise project will have duplicate symbol issues
  if target.name == "React"
    target.remove_from_project
  end

  # react-native-config
  if target.name == 'react-native-config'
    phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
    phase.shell_script = "cd ../../"\
    " && RNC_ROOT=./node_modules/react-native-config/"\
    " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
    " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
    
    target.build_phases << phase
    target.build_phases.move(phase,0)
  end

 end
end
```

#### `RNFirebaseAnalytics.m`:

```
#import "RNFirebaseAnalytics.h"
#import <React/RCTUtils.h>

#if __has_include(<FirebaseAnalytics/FIRAnalytics.h>)
#import <FirebaseAnalytics/FIRAnalytics.h>

@implementation RNFirebaseAnalytics
RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(logEvent:(NSString *)name props:(NSDictionary *)props) {
  [FIRAnalytics logEventWithName:name parameters:props];
}

RCT_EXPORT_METHOD(setAnalyticsCollectionEnabled:(BOOL) enabled) {
  [FIRAnalytics setAnalyticsCollectionEnabled:enabled];
}

RCT_EXPORT_METHOD(setCurrentScreen:(NSString *) screenName screenClass:(NSString *) screenClassOverriew) {
  RCTUnsafeExecuteOnMainQueueSync(^{
    [FIRAnalytics setScreenName:screenName screenClass:screenClassOverriew];
  });
}

RCT_EXPORT_METHOD(setUserId: (NSString *) id) {
  [FIRAnalytics setUserID:id];
}

RCT_EXPORT_METHOD(setUserProperty: (NSString *) name value:(NSString *) value) {
  [FIRAnalytics setUserPropertyString:value forName:name];
}

// not implemented on iOS sdk
RCT_EXPORT_METHOD(setMinimumSessionDuration:(nonnull NSNumber *) milliseconds) {}
RCT_EXPORT_METHOD(setSessionTimeoutDuration:(nonnull NSNumber *) milliseconds) {}
@end

#else
@implementation RNFirebaseAnalytics
@end
#endif

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 34.04 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-24 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.2/10E125 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `"react-native-firebase": "^5.5.6"`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Analytics`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Thanks for the detailed issue! We'll get this looked into ASAP.

**Comment by mikehardy** [comment]
I looked at this via Discord I believe and maybe another issue and it "smells" like Xcode caching and react-native-clean-project with 'wipe iOS build' would do it but I'm not sure.

**Comment by TommyLeong** [comment]
@mikehardy I have doubt that this would be a xCode caching issue, due to the fact I purposely download xCode11 (a new xCode, instead of xCode 10.2 that I've been using) to test the build. 

At the same time I did clean the project (from xCode) and physically removing the build folder under iOS folder.

**Comment by mikehardy** [comment]
Every time I have the versions right, but I get an unknown selector, it's DerivedData cache. Did you try it?

**Comment by TommyLeong** [comment]
Now this is strange, I tried to repeat everything I've done today and remove the DerivedData as mentioned by you. Im getting `no known class method for selector 'setAnalyticsCollectionEnabled:' [FIRAnalytics setAnalyticsCollectionEnabled:enabled];` as my error instead of the previous error. 

I have not changed RNFirebase version or anything.

**Comment by mikehardy** [comment]
I feel like the versions are moving back and forth and I'm not certain what commands you are using to clean. I'm not sure what state we are in. 

This definitely does not happen to me though, so it must be your local state somehow. There is no bug like this in RNFB, other than perhaps a compatible versions documentation error as pods 5.19 and above are required for a version of RNFB that doesn't say it needs a version that high.

Please confirm you are on RN60+, RNFB5.5.6 and pods 6.9.0 and you have done `npx react-native-clean-project`

**Comment by TommyLeong** [comment]
This time I have done it right with `npx react-native-clean project` , the error (`no known class method for selector 'setAnalyticsCollectionEnabled:' [FIRAnalytics setAnalyticsCollectionEnabled:enabled];`) no longer display. 

However I'm back to square for the issue I've been facing.
```
Exception '+[FIRAnalytics setAnalyticsCollectionEnabled:]: unrecognized selector sent to class 0x10893c760' was thrown while invoking setAnalyticsCollectionEnabled on target RNFirebaseAnalytics with params (
    1
)
```

**Comment by TommyLeong** [comment]
Just to put a hold on this issue, I guess I have managed to solve the issue. Turns out my project holds some old Firebase frameworks which were appended in Link Binary with Libraries, hence the version was going back and forth (I guess this is the best explanation why I've been building successfully and failing from time to time)

**Advise to others:**
If you face this issue and how you can identify if you are using the correct framework, 
- I went to Xcode look for ```FIRAnalytics setAnalyticsCollectionEnabled:enabled```
- (command + click) on FIRAnalytics, jumped to definition
- You'll be navigated to where the FIRAnalytics located, check the path on top...make sure your framework comes from Pod folder. 

**What I did:**
- Removed all the old firebase libraries
- Re-append the required framework (FirebaseAnalytics.framework, etc) back to Build Phases
- Build & Run - successfully without the crash issue I mentioned earlier.

**Why put a hold since issue solved?**
- My app is crashing due to another library, which I'm uncertain if RNFirebase will re-appear the same issue (although this evening I've tried to re-load & re-build the project without issue a few rounds). 
- I'll close the issue ticket by this week once I've verified. 

Thank you.
