### ISSUE TITLE
🔥 Cannot putString() with UTF8 encoding (€ symbol)

### ISSUE THREAD

**Issue by let-aurn** [invertase/react-native-firebase#2708]
### 🎩,

By doing

```
const currency = {
   name: 'EUR',
   symbol: '€'
};

const data = JSON.stringify(currency);

storage().app.storage(BUCKET).ref(FILE).putString(data);
```

I get the following error
```
"'RNFirebase.Base64.btoa' failed: The string to be encoded contains characters outside of the Latin1 range."
```

By looking at the code, [packages/storage/lib/StorageReference.js#L218](https://github.com/invertase/react-native-firebase/blob/master/packages/storage/lib/StorageReference.js#L218), I can see that we call Base64.btoa before uploading. Why?

What is the workaround?

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^6.0.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/app`
  - `@react-native-firebase/analytics`
  - `@react-native-firebase/storage`
- **Are you using `TypeScript`?**
  - `Y`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
cc @Salakar on the `btoa` question. My advise on this stuff would be to not store symbols like this anyway, as they're not always supported, espeically if using various different tools/services.

Workaround would be to use a code version (e.g. ASCII): http://eurosymbol.eu/ascii-code

**Comment by let-aurn** [comment]
Thank you @Ehesp ! 🔥
