### ISSUE TITLE
[5.x.x] Support for iOS 13

### ISSUE THREAD

**Issue by usrbowe** [invertase/react-native-firebase#2709]
## Documentation Feedback

I faced an issue when app crashed on app startup. I used **Xcode 11.1** with **iOS 13**. 
Later I found out issue was in `Firebase/Performance`. Which was fixed by Firebase team on 8th October in Firebase `6.10.0`. 
I think, if possible, it would be good to provide guidance on how to use RNFirebase 5.x.x. on iOS 13.

I guess something like, make sure to use `6.10.0` in your **Podfile**
```Podfile
pod 'Firebase/Core', '~> 6.10.0'
pod 'Firebase/Performance', '~> 6.10.0'
```

Release info: https://firebase.google.com/support/release-notes/ios#version_6100_-_october_8_2019
Issue: https://github.com/firebase/firebase-ios-sdk/issues/3929

**Comment by mikehardy** [comment]
I have a pull request pending review that updates the supported version table https://github.com/invertase/react-native-firebase-docs/pull/217

The problem with this is that they have released MLKit breaking changes at the same time. I don't think that will affect v5.x.x (I don't believe there is any MLKit stuff in there) but I need to verify it

**Comment by mikehardy** [comment]
@Salakar this ios13 crash is packaged in the release notes with MLKit breaking changes. Firebase statement on the subject is that MLKit is beta so breakage in semver minors is something to be prepared for. Worth noting... https://github.com/firebase/firebase-ios-sdk/issues/3929#issuecomment-540602445
