### ISSUE TITLE
How to configure multiple firebase projects?

### ISSUE THREAD

**Issue by flaviocarvalho** [invertase/react-native-firebase#271]
Hi, does anyone know how to configure multiple firebase projects with this library?
I'm looking at https://firebase.google.com/docs/configure/ but I'm not sure how to do it, my non JS skills are not that good.

**Comment by Salakar** [comment]
@flaviocarvalho it's work in progress at the moment, see the multi-apps branch, it's getting there!

**Comment by flaviocarvalho** [comment]
@Salakar Awesome, I researched a little more and found out that db storage can be over 100gb (the blaze calculator only goes to 100gb, I just assumed it wouldn't go past that), which was the main reason I was thinking of linking multi projects.
Keep up the good work!

**Comment by rtman** [comment]
@Salakar 

Has this feature been implemented? I'm having a hard time finding documentation on this.
