### ISSUE TITLE
🔥XCode FirebaseMessaging pod compile failure, <FirebaseInstanceID/FIRInstanceID_Private.h> file not found

### ISSUE THREAD

**Issue by jakecronin** [invertase/react-native-firebase#2710]
## Issue

Project no longer builds on Xcode after installing FirebaseMessaging giving the error: <FirebaseInstanceID/FIRInstanceID_Private.h> file not found

To isolate the issue to the Messaging product, I followed the following steps: 

1. Created a brand new project and confirmed the file built and ran successfully
`npx @react-native-community/cli init --template=@react-native-firebase/template <name>
`
2. Added the firebase app and confirmed the file built and ran successfully
`Yarn add @react-native-firebase/app && cd ios && pod update`
3. Added my GoogleService.plist file and confirmed that the project built and ran successfully, indicating that it detected my firebase project
4. Added Auth and Firestore and confirmed that the project built and ran successfully
`Yarn add @react-native-firebase/auth && cd ios && pod update`
`Yarn add @react-native-firebase/firestore && cd ios && pod update`
5. Added messaging and project build failed with compilation error <FirebaseInstanceID/FIRInstanceID_Private.h> file not found 
`Yarn add @react-native-firebase/messaging && cd ios && pod update`

I've tried cleaning the project as well as running `pod deintegrate` and `pod install`, but have found no success. Has anyone else seen this issue? Any thoughts on troubleshooting steps?

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

{
  "name": "MyCoolProject",
  "version": "6.0.0",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "run:android": "react-native run-android",
    "run:ios": "react-native run-ios --simulator=\"iPhone X\"",
    "build:apk": "cd android && ./gradlew assembleRelease",
    "test": "jest",
    "prepare": "patch-package"
  },
  "dependencies": {
    "@react-native-firebase/analytics": "^6.0.1",
    "@react-native-firebase/app": "6.0.0",
    "@react-native-firebase/auth": "^6.0.1",
    "@react-native-firebase/firestore": "^6.0.1",
    "@react-native-firebase/messaging": "^6.0.1",
    "react": "16.8.6",
    "react-native": "0.60.5"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/cli": "^2.9.0",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.1.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "patch-package": "^6.1.4",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [N] my application is an AndroidX application?
- [N/A] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [N/A] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 594.99 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v11.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.0
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-P | Google APIs Intel x86 Atom, android-P | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^2.9.0 => 2.9.0 
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [X] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 6.0.0` as seen on @react-native-firebase/app package
- **`Firebase` module(s) you're using that has the issue:**
  - `Messaging`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
The test project uses Messaging and it works https://github.com/invertase/react-native-firebase/blob/master/tests/ios/Podfile.lock#L434

I suspect a local project state issue - overly aggressive caching or similar. I highly recommend `npx react-native-clean-project` in cases like this as a first step in any case like this

**Comment by jakecronin** [comment]
Thanks, @mikehardy! I had to update my xcode gem to get that command to work, but now my project runs successfully!
