### ISSUE TITLE
FCM notification on IOS using direct channel

### ISSUE THREAD

**Issue by nes123** [invertase/react-native-firebase#2712]
Hi,

In the firebase for IOS there is an option to open a direct channel and not use the APN for a data-only messages. To do that one needs to define shouldEstablishDirectChannel flag to YES.

Is there a way to do it with react-native-firebase ? I didnt find any remark on that in the documents.

**Comment by nes123** [comment]
can someone help with that?

**Comment by nes123** [comment]
Will appreciate your help

**Comment by Salakar** [comment]
This is set to `YES` by default in both v5 & v6: https://github.com/invertase/react-native-firebase/blob/master/packages/messaging/ios/RNFBMessaging/RNFBMessagingDelegate.m#L34

**Comment by nes123** [comment]
I think that you rushed to close it, notification are not received in IOS when the app is closed even with the configuration you suggested (which is in any case the default one)
