### ISSUE TITLE
How catch event when notification is received, when app is in background state

### ISSUE THREAD

**Issue by Dhirajbhujbal** [invertase/react-native-firebase#2714]
I want to catch the event in the react-native when the app receives notification and the app is in the background state.
onNotification is working fine when the app is in the foreground state.

**Comment by mikehardy** [comment]
I realize it's a question but there is no mention of versions or platform here. This stuff is all pretty specific and varies based on those things

**Comment by Dhirajbhujbal** [comment]
ok!
A version of react-native-firebase - v5.5.5, React-Native: v0.59.5, 
Platform iOS and Android.

**Comment by mikehardy** [comment]
okay - still not all the info in the template, but the documentation is useful here. First you'll have to make sure you get the terms right - messaging vs notifications. You mention "receiving notifications" but "receiving" is usually for messages as a word - I realize that may be just a translation thing though, so I'll assume you're saying your app is in the background and a user taps a notification, how to handle it? You have to understand that android and ios are different here - on ios the app is completely dead, there is no background. So you'll have to check getInitialNotification at startup. For Android your app may be alive but in the background so you'll see onNotification, or it might be dead so getInitialNotification should work for you

**Comment by blastering66** [comment]
Hi @mikehardy just simple question.

Can i handle the Notification if the app is background / killed. I Wanna Custom the Notification (in these case i want to Vibrate and others cuz some device like Android M, in background is not VIBRATING but on newer OS is fine )

Basically i need to add more logic for notification in background / killed state.

Thanks mate

**Comment by mikehardy** [comment]
@blastering66 I think the best bet is to separate concerns. One is to receive the notifications in background - that's going to be cloud messaging silent push with data only payload and a headless task to handle it. Get that working so you can at least so console.log() output when you get a message. Second concern is a notification the way you want it. Use the data payload to carry information into the app, then construct a separate local notification using the data, when you get the message

**Comment by blastering66** [comment]
Thank for the tips!i really need this.

Gonna try. If i got some a bit question, mind if i ask again in here ?

**Comment by mikehardy** [comment]
sure - you might find the Discord better though - it's more real-time and has lots of people listening, I think I'm the only person that really globally watches issues in this repo so I'm more hit or miss https://discord.gg/X6FtsJ3

**Comment by blastering66** [comment]
Nice info... Thanks mate 👍👍
