### ISSUE TITLE
🔥 Impossible connection only for some IP addresses

### ISSUE THREAD

**Issue by pierroo** [invertase/react-native-firebase#2715]
## Issue

Some users manage to authenticate in the app, but then are completely stuck on infinite loading, which means that the initial query to firebase realtime database never returns any result.

It's like the endpoint of firebase just won't answer (I am unable to reproduce this issue on my side, so I can't catch the error if there is any)

HOWEVER, where it gets interesting is that as soon as they connect through a VPN (or change their IP address, very simply) then everything works fine for them again.

Which leads me to believe there might be some kind of "blacklisting" on your side?

This has been happening for all users in Egypt for the past month; which lead me to believe at first it was the kind of issue we see with Iran or UAE sometimes blocking some google services you guys rely on.

BUT lately it also started happening to some indonesian users, as well as americans.

WHY does changing the IP resolve firebase connection issue for these users, right away?

If there was any problem in my firebase configuration, it wouldn't work for all users, but it works fine for 99% of users.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 5.5.6
- **`Firebase` module(s) you're using that has the issue:**
  - realtime database / auth
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by pierroo** [comment]
Hi @mikehardy ,

Thank you for answering as always.

"black list" wasn't the best term; what I meant is that some countries' ISP block the google services needed for firebase to operate. (such as Iran)

So I was suggesting it could be related somehow?

But the main question remain the same: why does connecting through a VPN works right away for these users?

I have been unable to reproduce the issue.

I already approached google firebase, they keep redirecting me here since they do not officially support react-native-firebase ...

**Comment by mikehardy** [comment]
> I already approached google firebase, they keep redirecting me here since they do not officially support react-native-firebase ...

Right - `Best bet is to make sure it is reproducible in a small sample app based entirely on the native SDKs and approach google firebase (they are also on github) for support`

You must reduce the problem to something they will support - this issue won't be at the react-native-firebase level

Why is it happening? No idea unfortunately, network path troubleshooting is not easy

**Comment by mikehardy** [comment]
there was a good link there to a sample app though https://github.com/firebase/quickstart-android/tree/master/database

**Comment by pierroo** [comment]
Thank you Mike for the link, I will look into it.

By the way, isn't it an interesting case that the exact same code but from web sdk does work fine for these users?

It's only when moving to react native android that they started facing this issue... so I'm pretty sure sending them this firebase test case will work for them, and that won't bring me any progress on this situation. :/

**Comment by mikehardy** [comment]
I'm actually pretty sure it won't - the web is constrained to the networking tech available via the browser (so it will use the back-end REST API over HTTPS) while the native modules can use whatever networking tech they want so they might be using something more efficient for them but rarer for networks - and thus maybe not configured correctly everywhere - like multicast UDP or HTTP/3 or something

Either way they will be using the same networking tech in their native quickstart as react-native-firebase wraps and uses, so it should demonstrate.

**Comment by pierroo** [comment]
Very interesting, I didn't know that.

So all I have to do now is finding a way to compile this sampe project into an apk I can send one of these users, time to experiment I guess. I will update you if I find a way

**Comment by mikehardy** [comment]
Usually it's a `./gradlew assembleDebug` or `./gradlew assembleRelease` then you look in build/outputs/...../ (the path will change depending on release mode) for the apk, so `find build |grep apk` should show you where pretty quickly. The user will have to check a scary security setting for the app they use to install it that says "trust apks from unknown sources" then it should work

**Comment by pierroo** [comment]
Hello @mikehardy (and everyone else interested)!

I managed to create a simple apk with the firebase-android project you sent me, and sent it to one of the users facing issue connecting to realtime database unless they change VPN.

Result: he was NOT able to get it to work either, even using this native java sample app!
The newsfeed was not showing anything (in spite of posts being added), and wasn't able to add a new post either.

However, again, if he connects through a VPN: everything works fine again!


So there is definitely something off with the realtime database on android, and I'm back clueless.


Interesting extra info: this user is also unable to use gmail properly without vpn (maybe some google services in common?)

**Comment by Salakar** [comment]
> I managed to create a simple apk with the firebase-android project you sent me, and sent it to one of the users facing issue connecting to realtime database unless they change VPN.
> 
> Result: he was NOT able to get it to work either, even using this native java sample app!
> The newsfeed was not showing anything (in spite of posts being added), and wasn't able to add a new post either.

And now that you've reproduced with just the Android SDK, you can definitely send this to Firebase Support

**Comment by mikehardy** [comment]
Yep - reproduction at the layer below react-native-firebase, with just the pure android SDK was the goal, it means you are unblocked with them on seeking support.

My hunch is still that they are using some sort of unusual networking style in the native SDKs, the trick is to find out what it is and convince them to stop doing it. In the meantime If that is really the case I'm not sure you've got a workaround other than for at least these parts of your app using the web SDK or the REST API directly

**Comment by pierroo** [comment]
Yes, I resent them an email linked with this thread hoping they will help me and take it seriously now.

Unfortunately, IMPOSSIBLE for me to go back to using Web SDK; I just came back from using it, and the migration from web to native logged every users out (token being different I guess); which lead to nearly 10,000 emails I got from users who forgot their email / password they registered with... (this is what happens when millions of users :/ )

I will just pray they will find a way to fix this...
