### ISSUE TITLE
Android background push notification shows image but not action buttons.

### ISSUE THREAD

**Issue by Ashwini-ap** [invertase/react-native-firebase#2718]
## Issue

Not able to show action buttons on android notification when in background. Also when click on notification application opens but not getting callback in app.
Tried https://github.com/invertase/react-native-firebase/issues/1811#issuecomment-457995626 but no luck. Below is my code,

**bgMessaging.js**

import firebase from 'react-native-firebase';
export default async (message) => {
  try {
    console.log(message)
    const text = message.data.message;
    const payload = JSON.parse(message.data.sendbird);
    const localNotification = new firebase.notifications.Notification({
      show_in_foreground: true
    })
      .android.setChannelId('com.myapp.default_channel_id')
      .android.setPriority(firebase.notifications.Android.Priority.High)
      .setNotificationId(message.messageId)
      .setTitle('New message')
      .setSubtitle(`Unread message: ${payload.unread_message_count}`)
      .setBody(text)
      .setData(payload);
 const action = new firebase.notifications.Android.Action('Reply', 'ic_launcher', 'My Test Action');
    // Add the action to the notification
    localNotification.android.addAction(action);
    return firebase.notifications().displayNotification(localNotification);
  } catch (e) {
    return Promise.resolve();
  }
}

**AndroidMenifest.xml**

<service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
    </service>
    <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
      <intent-filter>
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
      </intent-filter>
    </service>
    <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />

    <receiver android:name="io.invertase.firebase.notifications.RNFirebaseBackgroundNotificationActionReceiver" android:exported="true">
      <intent-filter>
        <action android:name="io.invertase.firebase.notifications.BackgroundAction"/>
      </intent-filter>
    </receiver>
    <service android:name="io.invertase.firebase.notifications.RNFirebaseBackgroundNotificationActionsService"/>

**index.js**
import bgMessaging from './src/bgMessaging'

and tried both below,

AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => bgMessaging);
AppRegistry.registerHeadlessTask('RNFirebaseBackgroundNotificationAction', () => bgMessaging); 

**App.js**

componentDidMount() {
    this.checkPermission()
    this.createNotificationListeners();
  }

  checkPermission() {
    firebase.messaging().hasPermission().then((enabled) => {
      if (enabled) {
        this.removeNotificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
          // Get the action triggered by the notification being opened
          const action = notificationOpen.action;
          console.log('action tapped - ', action);
          // Get information about the notification that was opened
          const notification = notificationOpen.notification;
          console.log("opened notification - ", notification);
        });
      }
    })
  }

  componentWillUnmount() {
    this.notificationOpenedListener();
this.removeNotificationOpenedListener();
  }

  createNotificationListeners() {
//If your app is in background
 this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
      const { title, body } = notificationOpen.notification;
      console.log(notificationOpen.notification)
    });
}

 Anyone knows where exactly I made mistake? 

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by MK3690** [comment]
@Ashwini-ap 
how you solve this issue ?

**Comment by Praful2511** [comment]
@Ashwini-ap is this issue solved or unsolved?
