### ISSUE TITLE
[iOS] onDisconnect().update() missing

### ISSUE THREAD

**Issue by monkwooo** [invertase/react-native-firebase#272]
Please add following lines in _"ios/RNFirebase/database/RNFirebaseDatabase.m"_

`RCT_EXPORT_METHOD(onDisconnectUpdate:
    (NSString *) path
            props:
            (NSDictionary *) props
            callback:
            (RCTResponseSenderBlock) callback) {
    [[self getPathRef:path] onDisconnectUpdateChildValues:props];
}`

just after `RCT_EXPORT_METHOD(onDisconnectSet:` method

**Comment by Salakar** [comment]
Thanks for flagging this missing functionality @monkwooo and for the basic code example (needs tweaking to handle callback). We'll get this in for the next release.

**Comment by Salakar** [comment]
Fixed in v3 (not yet released).

Thanks for reporting the issue.
