### ISSUE TITLE
you attempted to use a firebase module that is not installed on your android project by calling firebase.app()

### ISSUE THREAD

**Issue by rendomnet** [invertase/react-native-firebase#2721]
## Issue

Describe your issue here

`import firebase from '@react-native-firebase/app';`
...
`console.warn(firebase.app().name);`

`you attempted to use a firebase module that is not installed on your android project by calling firebase.app()`

I'm using RN 0.60.2 and rn-firebase 6.0.1
rn-firebase should autolink right? Why it is asking me to make manual linking?

I have 3 firebase packages in my package.json
    "@react-native-firebase/app": "^6.0.1",
    "@react-native-firebase/auth": "^6.0.1",
    "@react-native-firebase/firestore": "^6.0.1",

![image](https://user-images.githubusercontent.com/18900210/66712062-e8fa6480-edb8-11e9-9f43-1d06e8e1a142.png)

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.0.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `6.0.1`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You didn't follow the template

My best advice is to init a sample project using the react-native template to see how a project should be initially built https://invertase.io/oss/react-native-firebase/quick-start/new-project

**Comment by rendomnet** [comment]
I think problem is in react-native-navigation v3. For some reason it is not working with RN-Firebase v6.
I'm testing on init sample project. They work independently  but together this error occurs.

**Comment by mikehardy** [comment]
:thinking:  that is unexpected of course. A reproduction repo on github using samples as a base should allow for a fix though

**Comment by rendomnet** [comment]
@mikehardy
Here sample repo
 https://github.com/rendomnet/firebasernn

**Comment by WJimmyCook** [comment]
@rendomnet Did you ever find a solution for this? I'm running into the same issue and can't figure it out.

**Comment by rendomnet** [comment]
@WJimmyCook clean cache and restart.

**Comment by RiatIO** [comment]
I'm getting an error message instead of a warning. I've been following the steps for setup, but no luck - any ideas?

**Comment by mikehardy** [comment]
@RiatIO 

> My best advice is to init a sample project using the react-native template to see how a project should be initially built invertase.io/oss/react-native-firebase/quick-start/new-project

**Comment by potatosenior** [comment]
I having this issue, i tried cleaning cache and still not working, im using react-native 0.6 and expo, i just upgraded to react-native-firebase 6

**Comment by alexaragao** [comment]
@potatosenior I'm having the same problem. It's really necessary to eject the project to edit android modules? If yes, whats the point of use Expo?

**Comment by potatosenior** [comment]
> @potatosenior I'm having the same problem. It's really necessary to eject the project to edit android modules? If yes, whats the point of use Expo?
> Edit:
> According to [this forum](https://expo.canny.io/feature-requests/p/adding-react-native-firebase-to-expo) expo "doesn't works" with firebase (JS SDK and all others dependencies). So unfortunately I suppose the best solution so far is to run `npm run eject` and then edit android project files.

I had to go back to react native 5, i didnt find a solution for this, sorry! Expo works very well with firebase (_firebase 5 at least_), i dint have any problem with expo and firebase, just this one, when i tried to update firebase to version 6.
