### ISSUE TITLE
Exception in Host Object::get: <propsName: RNFirebaseAuth> java.lang.NoClassDefFoundError on React-Native 0.61.2

### ISSUE THREAD

**Issue by truongnv91** [invertase/react-native-firebase#2729]
## Issue
I got a error "Exception in Host Object::get: <propsName: RNFirebaseAuth> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/auth/FirebaseAuth " on android.

[https://drive.google.com/file/d/14mVYOi-pZa4nNFoC16UglK8b349wZlG5/view?usp=sharing](url)
## Project Files

"react-native": "0.61.2",
"react-native-firebase": "^5.5.6",

**Comment by mikehardy** [comment]
Please follow the template, or we can't help
