### ISSUE TITLE
Misc messaging bugs

### ISSUE THREAD

**Issue by Salakar** [invertase/react-native-firebase#273]
Notes to self/devs:

1. https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/messaging/RNFirebaseLocalMessagingHelper.java#L157-L160 causing duplicate pushes - should only do these lines if there's a `fire_date` on bundle.
2. Receiving a notification in onMessage that uses `custom_notification` has the `custom_notification` property as a string rather than an object - should be parsed. However when clicking/tapping the notification the 2nd `onMessage` event now has a valid `custom_notification` object:
![wut](https://pbs.twimg.com/profile_images/728309243011604482/WmkkxDr1.jpg) 

Pointed out by @wizloc on discord:
![image](https://user-images.githubusercontent.com/5347038/28537652-8c9c8f18-70a3-11e7-8403-fc365f419649.png)

**Comment by Salakar** [comment]
I think we should also internally rename it when it's received to `notification` and added a `custom`: true/false flag to the object - for sake of standardisation, and make sure it's actually an object 🙈 

cc @chrisbianca @Ehesp

**Comment by chrisbianca** [comment]
@Salakar personally, I think we should completely remove the custom_notification behaviour as it's Android specific and not part of the FCM spec.  We could then provide a guide for how users can replicate this functionality themselves using local notifications instead which would work cross-platform.

**Comment by Salakar** [comment]
@chrisbianca I was all for that, but there's no way of doing that without the end user having to write native code, I know this is something we use heavily in our apps, but we're not native code shy like the majority of our user base, it's just much simpler. Is there no way we could replicate or even partially the feature set for iOS?
