### ISSUE TITLE
I haven't eject my App to Android nor IOS so far, is it necessary?

### ISSUE THREAD

**Issue by MichaelSzer** [invertase/react-native-firebase#274]
Do I have to eject my App to Android or IOS to install this Library? (I am asking because I am having the error: 'undefined is not an object (evaluating FirebaseModule.googleApiAvailability)' )

**Comment by chrisbianca** [comment]
@MichaelSzer Assuming that you're ejecting from Expo, then yes you do need to eject in order to use this library.
