### ISSUE TITLE
[v5][iOS] OnNotification Work fine in Debug but not work in Release Mode

### ISSUE THREAD

**Issue by mozry** [invertase/react-native-firebase#2742]
this issue look like #2153 
any suggestion ?

react-native: 0.59.8
react-native-firebase: 5.5.6

pod 'Firebase/Core', 6.3.0
pod 'Firebase/Messaging', 6.3.0

**Comment by mikehardy** [comment]
Please follow the template - without that information we can't help
In general though, I don't understand why you wouldn't be on 0.59.10 at least (most recent patch version there) and 6.10 pods (most recent there). Being up to date helps.

**Comment by mozry** [comment]
hi @mikehardy 

so sorry I'm missing the template.
I upgraded react-native 0.59.8 ~> 0.59.10 and pod from 6.3.0 ~> 6.10.0 but in release mode iOS still not work like debug mode. can you have any suggestion for me ?

Xcode: Version 11.1

Test on
iPhone 6s (iOS 13.1.2)

thank you.

**Comment by mikehardy** [comment]
without all the info from the template I'm not exactly sure, sorry. I will reopen this provisionally though, at least for a test. I'm about to work on notifications again in my work project, so I can try to replicate

**Comment by mozry** [comment]
@mikehardy thank you so much.

**Comment by slonv23** [comment]
Hi, I am having the same issue, react-native version 0.59.10, react native firebase version 5.5.6

**Comment by akhlopyk** [comment]
Hello,
Just want to say - I have the same issue only for IOS.

This is tricky case, because I got notification only while debug is enabled (shake the device and select it from the list). Once I disable debug - it still working until I close the app and open it again.

RN - 59.2

I assume latest version.
pod 'Firebase/Core'
pod 'Firebase/Messaging'

What do you suggest? This is a huge issue.

**Comment by mikehardy** [comment]
I think I answered elsewhere but hard to say @akhlopyk you are sort of spamming the issues here. Open a fresh issue with full details, but in general upgrade your versions first, troubleshooting old versions is usually a time malinvestment

**Comment by akhlopyk** [comment]
@mikehardy 
It's kind of spamming the issue. We need to have such issues on top to be resolved very quick. 
So for know, millions using this library and it just does not work.

I have updated FB(6.2.0 i suppose), RN(51.2) and react-navigation 3 .
It was the same on old version.

**Comment by mikehardy** [comment]
The library works.
Spamming sucks.
The people helping you are unpaid, and comments like this are irritating. They make me not want to help you. 🤷‍♂ 

Your versions are sorely out of date. If you checked the upstream docs or our release notes, you'd notice

**Comment by mikehardy** [comment]
Also worth mentioning notifications inside react-native-firebase is a dead-end solution. Check the pinned issue in the repo, likely move to react-native-push-notifications as an alternate for you
