### ISSUE TITLE
firebase.notifications().getInitialNotification() doesn't work when app is in background in IOS

### ISSUE THREAD

**Issue by srichallamalla935** [invertase/react-native-firebase#2743]
## Issue
 firebase.notifications().getInitialNotification() doesn't work when app is in background in IOS

##Actual Behaviour:- After killing app I am getting notifications but below code doesn't work when the app is in background. I want to redirect the user to a specific page when a user comes to the app through notification but below code is not working when the app is in background

##Code
 ```
componentDidMount()
{
 const notificationOpen: NotificationOpen = await firebase
      .notifications()
      .getInitialNotification();
    if (notificationOpen) {
     alert("getInitialNossssssssstification");

      if (this.state.isUser) {
        await AsyncStorage.setItem("getNotificationsKey", "true");
        // console.log("jkasghfghdfgj isUser true");
      } else {
        // console.log("jkasghfghdfgj isUser false");
      }
    } else {
      console.log("elseeeeeeee");
    }
}
```

##Expected Behaviour: I am getting notifications  when app is in background and I want to redirect the user to a specific page when a user comes to the app through notification for that i have used the above code

## Environment

react-native:-0.60.5
Firebase version:5.5.6

**Comment by luifer94** [comment]
exactly same problem! but in my case does not work for both: Android and IOS

**Comment by mikehardy** [comment]
...which is not exactly the same problem ?

**Comment by lovekothari123** [comment]
Same problem from my side.
 i am also not getting any response(payload) while application. In background/killed state
i am using this :- 

import firebase from "react-native-firebase";
import {
  Notification,
  NotificationOpen,
  RemoteMessage,
  Firebase
} from "react-native-firebase";
firebase
    .notifications()
    .getInitialNotification()
    .then((notificationOpen: **NotificationOpen**) => {
      if (notificationOpen) {
        alert("get data testing done")
      }
    }); 

also i am trying that 👎  but did't get any solution 

firebase.messaging().onMessage((message: RemoteMessage) => {
    // Process your message as required
    console.log("Notification open App closed in open " + message);
  });

If is there any one who can resolved this issues please update.

**Comment by minhnguyenwp** [comment]
Same on my side. 
**Android works well all cases.** 
IOS only does not work when killed app. 
 - "react-native": "0.59.9",
-  "react-native-firebase": "5.5.6",
- "react-native-splash-screen": "3.1.1", (i knew this issue, but it's not)

Hope there is a solution.

**Comment by ramonvermeulen** [comment]
Got the same issue here, android works fine but on iOS the `getInitialNotification().then(...)` is always returning null. Using react-native 0.59 and react-native-firebase 5.5.6.

**Comment by DuranMoodley** [comment]
Hi , i am also getting the same issue on my side. 

Does anyone have a workaround ?

**Comment by snkhan120** [comment]
Same issue occurred, When app is killed, i got notification, i got notification badge on app icon, but then i open app, no notification data got

I tried both codes but i didn't get success
 
`const notificationOpen = await firebase.notifications().getInitialNotification();
    if (notificationOpen) {
      const { title, body, data } = notificationOpen.notification;
      console.log('App closed: ', JSON.parse(data.data))
      this._addDataToList(JSON.parse(data.data));
      //this.showAlert(title, body);
    } else {
      console.log('No notification:', notificationOpen)
    }`  
 or
`firebase.notifications().getInitialNotification()
      .then((notificationOpen: NotificationOpen) => {
        if (notificationOpen) {
          // App was opened by a notification
          // Get the action triggered by the notification being opened
          const action = notificationOpen.action;
          // Get information about the notification that was opened
          const notification: Notification = notificationOpen.notification;  
          console.log('then notification:', notification)
        }
      });`

**Comment by Juliocbr** [comment]
Did anyone find a solution for this error? I planned to upgrade from version 3.3.1 to 5.5.6 but apparently I will not do so for now.

**Comment by tommypd** [comment]
Same here

**Comment by snkhan120** [comment]
There is no solution as per my R&D, but there is one way you can manage this situation, 

`firebase.notifications().removeAllDeliveredNotifications();` 

above line kill all your notification

**Comment by davidwlhlm** [comment]
Hi, do you have remote debugging enabled? I had the same issue last week with `react-native 0.60.5` and `react-native-firebase 5.5.6`, but I could resolve the issue after turning "Debug JS Remotely" off.

I came to the solution after encountering a similar behaviour with React Native's Linking module. `Linking.getInitialURL()` (detecting with which link the app was initially opened) always returns null, if remote debugging is on.

**Comment by tommypd** [comment]
@davidwlhlm debug remotly is not enabled and this is happening also in release build

**Comment by daithinh2401** [comment]
Hi, I've the same issue, did anyone find a solution ?
