### ISSUE TITLE
document.set() promise never resolves

### ISSUE THREAD

**Issue by mikemcelligott** [invertase/react-native-firebase#2745]
## Issue

Using firestore and setting the contents of a document to merge, the promise never resolves (neither then nor catch branches are followed).  The data does, however, seem to be set (listeners on the same document fire fairly quickly).  This eventually leads to an error on the console:  "Please report: Excessive number of pending callbacks: 4089.  Some pending callbacks that might have leaked by never being called from native code:", along with some not very useful descriptors of those callbacks.  Note that I'm setting a location, so these set() calls are coming in regularly (hence the large number of unresolved promises).

```
  import firestore from '@react-native-firebase/firestore';
  ...
  let ref = firestore().collection('latest');
  let doc = ref.doc(user.account.key)
  .set(update, {merge : true})
  .then(result => {
    console.log('location transmitted');  // <-------- never gets called, adding catch does nothing
  })
```

Describe your issue here

---

## Project Files

Not yet working with the android side.

Not yet working with the android side.

Not yet working with the android side.

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Tracker' do
  # Pods for Tracker
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'Firebase/Analytics'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-Motion', :path => "#{permissions_path}/Motion.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"

  pod 'GoogleMaps'
  pod 'GooglePlaces'
  
  target 'TrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'Tracker-tvOS' do
  # Pods for Tracker-tvOS

  target 'Tracker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)

    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
@import Firebase;
@import GoogleMaps;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                            moduleName:@"Tracksy"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [GMSServices provideAPIKey:@"XXXXXXXXXXX"];
  [FIRApp configure];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS Mojave 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 168.00 MB / 32.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.3.0 - ~/.nvm/versions/node/v8.3.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v8.3.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.0, 28.0.1, 28.0.3, 29.0.2
      System Images: android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7```

<!-- change `[ ]` to `[x]` to select an option(s) -->

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
6.8.1
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
Firestore
- **Are you using `TypeScript`?**
  - `Y/N`
  N

</p>
</details>


<!-- Thanks for reading this far down ❤️  -->
<!-- High quality, detailed issues are much easier to triage for maintainers -->

<!-- For bonus points, if you put a 🔥 (:fire:) emojii at the start of the issue title we'll know -->
<!-- that you took the time to fill this out correctly, or, at least read this far -->

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
There is no react-native-firebase 6.8.1, what react-native-firebase are you on?

**Comment by mikemcelligott** [comment]
My bad, was looking at the podfile.

```
    "@react-native-firebase/app": "^6.0.0",
    "@react-native-firebase/auth": "^6.0.0",
    "@react-native-firebase/firestore": "^6.0.0",
```

**Comment by mikemcelligott** [comment]
6.0.0.  I'll specify 6.0.1 and see if that improves the situation.

**Comment by mikemcelligott** [comment]
Specified 6.0.1, no apparent change, still waiting on the leaked callback error.  I've added logging to show that the function call to set is never paired up with an outcome.  So this code:
```
  firestore().collection('latest').doc(user.account.key)
  .set(update, {merge : true})
  .then(result => {
    console.log('location transmitted');
  }).
  catch(err => {
    console.log('got error on document.set: ' + err.message);
  })

  return {
    type: LOCATION_TRANSMIT_BEGIN,
    payload: {}
  }
```
only ever results in the first console.log being executed (though I believe the document is being set as I'm currently waiting on a document snapshot to actually show a location change, and location is changing).

**Comment by mikemcelligott** [comment]
Have verified that the location updates are being received from firestore as a result of the document.set referenced above, just the promise never resolves with then or catch.  Have also tried the same experiment without the merge option, same result.  Going to try update now.

**Comment by Ehesp** [comment]
Ok so `set` simply returns a native call, so if it's not resolving in JS land the native promise isn't resolving. Strange though, as tests are passing on all sorts of usages with `set`, they'd time out if the promise didn't resolve. Do you have the JS debugger running or anything?

**Comment by mikemcelligott** [comment]
I do have it running, neither branch resolves until the number of leaked callbacks becomes too high, then the whole thing tanks.  I'm still trying to figure out if I'm doing something wrong but nothing is jumping out at me.  I'm printing the resulting promise to the console at this point.  Some functions seem like they're not specified, that's the next thing I'm trying to investigate.

<img width="1203" alt="Screen Shot 2019-10-17 at 12 58 10 PM" src="https://user-images.githubusercontent.com/487946/67030681-edd35700-f0dd-11e9-8517-30b4f80d282a.png">

**Comment by mikemcelligott** [comment]
'reporting location' is coming from the device receiving location from gps/whatever (causes the document.set), 'peer changed' above is the result of a document change.  So the change is happening in firestore, but the promise that comes back from document.set()  (also on the console) just doesn't resolve.  I thought I had my promise syntax right but it's possible I'm doing something wrong.

**Comment by mikemcelligott** [comment]
And then eventually this.
<img width="1226" alt="Screen Shot 2019-10-17 at 11 59 19 AM" src="https://user-images.githubusercontent.com/487946/67031321-3dfee900-f0df-11e9-9ede-8d6c5e7abc36.png">

**Comment by Ehesp** [comment]
Where is that code you posted executing? Is it with a React function context or outside of it?

You're returning straight away, so maybe something is happening where the promise doesn't resolve because the function has been cleaned up?

**Comment by mikemcelligott** [comment]
Hmm, that's an interesting idea.  It is in a headless react component that should stick around for the duration my app is open.  I'll check to see if it's being unmounted but I don't believe it is.  This is in my App.js, I'm just taking advantage of the react lifecycle to have some services (headless react components with render functions that return null) connect to redux.

The call that is triggering that promise (and receiving it back) is in ServiceLocation.

```      <Provider store={store}>
        <ServiceAccount/>
        <ServiceLocation/>
        <Navigation/>
      </Provider>
```

**Comment by mikemcelligott** [comment]
Doesn't seem to be unmounted so I don't think the context is going away.  I'm going to try a few different onReject syntaxes than what I'm using, though that doesn't seem like it should change anything.

**Comment by mikehardy** [comment]
This smells like it might be easier to use https://github.com/transistorsoft/react-native-background-geolocation-firebase with https://github.com/transistorsoft/react-native-background-geolocation :-)

Industrial strength, startup pricing (I am not affiliated at all, I just use background-geolocation and will probably use the firebase adapter as well, shortly, but even if not I will probably just have the geolocation post to a firebase function as a regular HTTP endpoint, as the geolocation plugin is able to do that easily)

**Comment by mikemcelligott** [comment]
It's useful for what I'm doing but I'm sure I'll have no shortage of document.sets for other purposes.  Actually that brings up a good point, I'll see if the callbacks are succeeding anywhere (after I try a few different approaches on the rejection path), since if they are it definitely suggests it's how I'm using it.

**Comment by mikemcelligott** [comment]
Trying to handle the promise differently (specifying success and error paths immediately on then()) or with a try/catch clause (or as above with .then and .catch) had no different effect, as you'd expect.

I'm far from my expertise here, but tracing into what the ios client is doing seems to show that these callbacks are never being called (firestore_client.mm:431-433):

```
      shared_this->sync_engine_->WriteMutations(
          std::move(mutations), [callback, shared_this](Status error) {
            // Dispatch the result back onto the user dispatch queue.
            if (callback) {
              shared_this->user_executor()->Execute(
                  [=] { callback(std::move(error)); });
            }
          });
```

**Comment by mikemcelligott** [comment]
I believe I may have found the problem by turning on logging in the ios app, and it may just be an incorrect project reference.  I believe I've followed all of the directions but possibly not.  The message is:

```Stream error: 'Not found: The project tracksy-31e8b does not exist or it does not contain an active Cloud Datastore or Cloud Firestore database. Please visit http://console.cloud.google.com to create a project or https://console.cloud.google.com/datastore/setup?project=tracksy-31e8b to add a Cloud Datastore or Cloud Firestore database. Note that Cloud Datastore or Cloud Firestore always have an associated App Engine app and this app must not be disabled.'```

My guess is I'm only seeing success because mutations are happening locally and my local subscriber is then picking them up.  I'll attempt to resolve this and post here with success or failure.

**Comment by mikemcelligott** [comment]
Thanks everyone!

**Comment by HYJ29** [comment]
> ## Issue
> Using firestore and setting the contents of a document to merge, the promise never resolves (neither then nor catch branches are followed). The data does, however, seem to be set (listeners on the same document fire fairly quickly). This eventually leads to an error on the console: "Please report: Excessive number of pending callbacks: 4089. Some pending callbacks that might have leaked by never being called from native code:", along with some not very useful descriptors of those callbacks. Note that I'm setting a location, so these set() calls are coming in regularly (hence the large number of unresolved promises).
> 
> ```
>   import firestore from '@react-native-firebase/firestore';
>   ...
>   let ref = firestore().collection('latest');
>   let doc = ref.doc(user.account.key)
>   .set(update, {merge : true})
>   .then(result => {
>     console.log('location transmitted');  // <-------- never gets called, adding catch does nothing
>   })
> ```
> 
> Describe your issue here
> 
> ## Project Files
> Not yet working with the android side.
> 
> Not yet working with the android side.
> 
> Not yet working with the android side.
> 
> ### iOS
> Click To Expand
> ### Android
> Click To Expand
> ## Environment
> Click To Expand

I had the same problem and solved it with 'await'. Just like below
```
 let ref = await firestore().collection('latest');
 let doc =await ref.doc(user.account.key)
```

**Comment by universal-alert** [comment]
I'm getting this issue right now. @HYJ29 Did you already have the firebase store, if so how did you transfer the data cross to the one made in the cloud console?

**Comment by Vadorequest** [comment]
Having the same issue, first time ever I see a Promise that doesn't resolve. What a lie.

**Comment by AbdulBsit** [comment]
Any updates on this ? suddenly this issue comes today, it was all working since before today, but know promise not resolving, 
"@react-native-firebase/firestore": "6.4.0",
"@react-native-firebase/remote-config": "6.4.0",
"@react-native-firebase/storage": "6.4.0"

**Comment by mikehardy** [comment]
@AbdulBsit no time whatsoever will be spent investigating issues on non-current versions. 6.4.0 is *really* old, you should definitely update!

**Comment by AbdulBsit** [comment]
@mikehardy Thanks, I figured out, my usage quota used up 100%, after upgrading it start working as usual, but strange, it's not giving any error/warning in such case as an exception, moreover operation completes but just promise doesn't resolves, Upgarding to blaze works for me
