### ISSUE TITLE
v6 Storage refFromUrl does not work correctly

### ISSUE THREAD

**Issue by ThomasFindlay** [invertase/react-native-firebase#2753]
## Issue

Describe your issue here

v6 refFromURL does not work on the url below. v5 worked without problems.

```
firebase.storage().refFromURL(https://firebasestorage.googleapis.com/v0/b/<project-name>.appspot.com/o/<image-path>)
```

In v6 it throws an error that object was not found even though it exists. I was able to delete the file when using .ref(path).delete(). I don't think that the stack trace is really useful, but here it is.

```
code:"storage/object-not-found"
jsStack:"Error↵    at Object.delete (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:97535:23)↵    at StorageReference._delete (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:106533:43)↵    at _removeProfilePic$ (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:348611:59)↵    at tryCatch (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:5488:19)↵    at Generator.invoke [as _invoke] (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:5663:24)↵    at Generator.prototype.(anonymous function) [as next] (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:5531:23)↵    at tryCatch (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:5488:19)↵    at invoke (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:5564:22)↵    at blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:5594:13↵    at tryCallTwo (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:49272:7)"
message: "[storage/object-not-found] No object exists at the desired reference."
namespace: "storage"
nativeErrorCode: null
nativeErrorMessage: null
stack: "NativeFirebaseError: [storage/object-not-found] No object exists at the desired reference.↵    at StorageReference._delete (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:106533:43)↵    at _removeProfilePic$ (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:348611:59)↵    at tryCatch (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:5488:19)↵    at Generator.invoke [as _invoke] (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:5663:24)↵    at Generator.prototype.(anonymous function) [as next] (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:5531:23)↵    at tryCatch (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:5488:19)↵    at invoke (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:5564:22)↵    at blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:5594:13↵    at tryCallTwo (blob:file:///06ce93ab-5900-4f65-9a07-f6d7415cdc5e:49272:7)"

```

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ x ] my application is an AndroidX application?
- [ x ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ x ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ x ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 6.0.2
- **`Firebase` module(s) you're using that has the issue:**
  - @react-native-firebase/storage
- **Are you using `TypeScript`?**
  - N
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Could you try the URL shown in the Firebase console, e.g:

![image](https://user-images.githubusercontent.com/842078/67189772-be2a9480-f3e6-11e9-93f5-06a0c6ae82ee.png)

The tests also show this working: https://github.com/invertase/react-native-firebase/blob/master/packages/storage/e2e/storage.e2e.js#L39

**Comment by rkuncewicz** [comment]
I'm having a similar issue with the `https` URL. The `gs://` URL works as expected, but if we try to use the `https://` version the library thinks that it doesn't exist. Also, if there are any spaces in the URL it thinks that the space is the end of the file (i've tried both an encoded space `%20` and a regular space ` `). 

I can reproduce this with
```
  const foo= storage.refFromURL('hhttps://firebasestorage.googleapis.com/v0/b/lumiq-dev.appspot.com/o/file_example_MP3_1MG.mp3?alt=media');
  const bar = await a.getMetadata();
  console.log(bar);
```

which results in 
```
Error: [storage/object-not-found] No object exists at desired reference.
```

Using `gs://lumiq-dev.appspot.com/file_example_MP3_1MG.mp3` works. 

If you use `https://firebasestorage.googleapis.com/v0/b/lumiq-dev.appspot.com/o/file%20example%20MP3%201MG.mp3?alt=media` it will parse the path as just `file`. 

Is this expected? v5 was working properly.

**Comment by Rob117** [comment]
This is _100%_ still an issue, btw. I'm experiencing it exactly as described above.

I have no idea if it helps, but this is only happening on android.

**Comment by sarykemmoun** [comment]
I have this issue too.
The download url is correct, I use it for displaying the image properly, But when I do `refFromUrl` and try to delete the ref I'm getting `storage/object-not-found`

**Comment by dackers86** [comment]
@rkuncewicz We seem to have an issue with handling encoded urls which I will create a new issue for.

@ThomasFindlay If you can still provide an example of what url you are using then we can potentially se that for an different test case?

@sarykemmoun If you could also provide an example of this, most cases we have found so far have been encoded or incorrect urls

**Comment by dackers86** [comment]
PR Added at https://github.com/invertase/react-native-firebase/pull/3368

**Comment by HwangPeter** [comment]
Seems to have something with how the ref is generated from HTTP URLs. By printing the storage ref that "doesn't exist" to console, it was missing the ".appspot.com" part of the bucket name. Normally you get something like gs://${project id}.appspot.com/${restOfPath}

As a temporary workaround I grabbed the rest of the pathname and created a new ref using storage().ref().child(`${restOfPath}`);

**Comment by phatmann** [comment]
This issue still exists with version 7.0.1. The slashes within the path are now handled correctly, but the ref is still not valid. Like @HwangPeter observed, I confirmed that valid refs have a bucket named "{BUCKET}.appspot.com" but the refs from `refFromURL` have a bucket named "{BUCKET}".

**Comment by dackers86** [comment]
PR added at https://github.com/invertase/react-native-firebase/pull/3775

**Comment by hackrx** [comment]
I am also facing the same issue, refFromURL is not working
I generated using below code,
```
 try {
            //console.log('Photo we need to delete ', this.state.photoURL);
            const deletePostImageFromStorageRef = Storage().refFromURL(
              this.state.photoURL,
            );
}
catch(err){
console.log("Error ",err);
}
```

And the error I got is
`Error in deleting the post NativeFirebaseError: [storage/object-not-found] No object exists at the desired reference.
    at StorageReference._delete`
Any workaround for this?

**Comment by hackrx** [comment]
Solved this issue #3820

**Comment by enosh94** [comment]
I am having the exact same issue when using refFromURL. Any solutions?

**Comment by mikehardy** [comment]
@enosh94 there's a PR #3775 working through review now, you can probably apply the fix locally via https://github.com/ds300/patch-package - when you say it "needs to be fixed" it implies someone should do it, with open source that's all of us and if you are suffering from this exact problem you would be a perfect test case, getting success reports for the proposed change would help it be fixed

**Comment by akinlekan28** [comment]
> I am having the exact same issue when using refFromURL. And following temporary solution worked like a charm.
> 
> ```
> const fileRefFromUrl = storage().refFromURL("https://<pathtoyourfile> ");
> storage().ref(fileRefFromUrl .fullPath).delete()
> ```
> 
> However, this is a workaround. This bug needs to be fixed.

Thank you very much for this

**Comment by zzterrozz** [comment]
> const fileRefFromUrl = storage().refFromURL("https://<pathtoyourfile> ");
> storage().ref(fileRefFromUrl .fullPath).delete()

Unfortunately not working for me, getting the error
`[firebase_storage/object-not-found] No object exists at the desired reference.`

I tried
```
final Reference fileRefFromUrl = FirebaseStorage.instance.refFromURL(fileUrl);
await FirebaseStorage.instance.ref(fileRefFromUrl.fullPath).delete();
```
also 
```
final Reference fileRef = FirebaseStorage.instance.refFromURL(fileUrl);
await fileRef.delete();
```

I have been stuck for hours and can't find any solution. Any idea please ?

**Comment by WiseTap** [comment]
My workaround:

```
final path = Uri.decodeFull(url.substring(url.indexOf('appspot.com/o/',) 
    + 'appspot.com/o/'.length, url.indexOf('?')));
return storage().ref(path).delete();
```
