### ISSUE TITLE
[v6][firestore]: offline lookup crashes with Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage() on a null object'

### ISSUE THREAD

**Issue by mgenov** [invertase/react-native-firebase#2757]
## Issue
The issue is encountered in offline mode when the app is looking for a document. The crash is on line 33 when calling the constructor of UniversalFirebaseFirestoreException:

![image](https://user-images.githubusercontent.com/209223/67198965-c5629a00-f408-11e9-889e-89d8dec34866.png)

e.g the problem is that getCause().getCause() is null and adding of an additional check is fixing the issue:

```java
} else if (exception.getCause() != null && exception.getCause().getCause() != null &&  exception.getCause() instanceof FirebaseFirestoreException) {
  // ...
}

```

---

## Project Files

```groovy
implementation project(path: ":@react-native-firebase_firestore")
implementation "com.google.firebase:firebase-firestore"
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy

```

#### `android/app/build.gradle`:

```groovy
implementation project(path: ":@react-native-firebase_firestore")
implementation "com.google.firebase:firebase-firestore"
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 171.91 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.10.1 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.npm-packages/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native: 0.55.4

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.0.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Hmm good spot. The exceptions from native can be hit and miss on their format/type so looks like this one slipped under the radar. I'll give it a go

**Comment by mgenov** [comment]
I'm not sure that the issue is fixed, so marking it as staling doesn't sound good.

**Comment by mgenov** [comment]
Any news on this issue?

**Comment by mgenov** [comment]
Any news on this issue?

I could fire PR with an added null check but I'm not sure that this is the overall goal.

**Comment by Salakar** [comment]
@mgenov yes please, send a PR over and I'll get it merged.

**Comment by russellwheatley** [comment]
Thanks for reporting this issue @mgenov. I've fixed this issue in PR: https://github.com/invertase/react-native-firebase/pull/3116

**Comment by mgenov** [comment]
Good work. Thanks.
