### ISSUE TITLE
[5.5.6] and react-native 0.60 auto-linking

### ISSUE THREAD

**Issue by rendomnet** [invertase/react-native-firebase#2759]
Auto-linking is working for react-native-firebase 5.5.6 with react-native >0.60??

`yarn add react-native-firebase@5.5.6 `is enough? or do we need additional steps?

**Comment by oviedo97fer** [comment]
No. You must link it manually

**Comment by mikehardy** [comment]
@oviedo97fer false
@rendomnet yes it works

Working demonstration of my statements - start to finish: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh
