### ISSUE TITLE
feature to capture app_remove event in ios

### ISSUE THREAD

**Issue by abhilashfancy** [invertase/react-native-firebase#2765]
Please add the feature to capture app_remove event in iOS. Currently it is being captured only in android.

**Comment by Ehesp** [comment]
Unfortunately, Firebase only captures Android events. With limited knowledge, I assume this is because it is not achievable with iOS: https://support.google.com/firebase/answer/6317485

I'd suggest picking this up with Firebase support, as we simply wrap their SDK to provide these events.
