### ISSUE TITLE
🔥 Native module cannot be null

### ISSUE THREAD

**Issue by Tommoore96** [invertase/react-native-firebase#2769]
I'm using RN version 0.60.6 with RNF version 6.0.2 and on ios I keep getting the error `Native module cannot be null`.  I know it's RNF because when I stop importing the module it works.

I have followed the instructions and installed `@react-native-firebase/app` as well as removed the references to the last version of RNF.

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SchoolSpiderParentApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  target 'SchoolSpiderParentApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'SchoolSpiderParentAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 269.15 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.3 => 16.11.0
    react-native: ^0.60.4 => 0.60.6
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-rename: 2.4.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.0.2`
- **`Firebase` module(s) you're using that has the issue:**
  - `/app`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

**Comment by mezhik91** [comment]
@mikehardy I have the same issue as @Tommoore96  has, despite my Podfile includes those 2 lines.
platform :ios, '9.0'

"react-native": "0.61.2",
"@react-native-firebase/app": "^6.0.2"

Project was created with @react-native-community/cli and typescripts template

**Comment by alammoiz** [comment]
I'm also getting that, can anyone help me

**Comment by rhaegar453** [comment]
Same here. Please can anyone resolve this ?

**Comment by mikehardy** [comment]
Everyone else has resolved this I believe. It is a project integration issue, not a module problem. Investigate the areas of your project that handle linking in modules.

Here is an example script that generates a fully working react-native-firebase application from scratch, with comments. Somewhere in the difference between your project and the created demo you will find the problem: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh
