### ISSUE TITLE
[Argument list too long: recursive header expansion failed] at after following the installation instructions on IOS

### ISSUE THREAD

**Issue by IvRRimum** [invertase/react-native-firebase#277]
Hello,

Iphone 6 Emulator
Mac Os Sierra
Xcode
react-native 0.38.0
react-native-firebase 2.0.4

Followed the instructions here: http://invertase.io/react-native-firebase/#/installation-ios?id=_1-setup-googleservice-infoplist

And after pods install i encouraged this error:
`Argument list too long: recursive header expansion failed at /Users/user/Projects/Myapp/Myapp/node_modules/react-native-admob/ios/../../../ios/Pods/React/node_modules/react-tools/src/renderers/shared/reconciler/__tests__.
`
inside of RNAdMobManager

Is this a bug?

Thanks!

**Comment by IvRRimum** [comment]
My Pods file:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Myapp' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AdPagesGo

  pod 'OneSignal', '~> 1.13.3'
  pod 'RNFirebase', :path => 'react-native-firebase'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'

end
```

**Comment by chrisbianca** [comment]
@IvRRimum have you installed another library called react-native-admob?  The error relates to that library, not react-native-firebase.  I'd suggest you remove that library and use the Admob functionality from this library.

**Comment by IvRRimum** [comment]
Yeah, removed the react-native-admob, i got next error:
<img width="260" alt="screen shot 2017-07-26 at 14 30 14" src="https://user-images.githubusercontent.com/5957079/28618703-fd9422d8-720d-11e7-986d-8bf681246071.png">

<img width="915" alt="screen shot 2017-07-26 at 14 30 53" src="https://user-images.githubusercontent.com/5957079/28618714-06c0dd88-720e-11e7-8a7b-f7bea78d5320.png">

**Comment by IvRRimum** [comment]
And after this next error: 
`Argument list too long: recursive header expansion failed at /Users/Myuser/Projects/adpages/adpagesgoapp/node_modules/react-native-firebase/ios/../../../ios/Pods/React/node_modules/react-tools/src/renderers.`

**Comment by IvRRimum** [comment]
I am playing with the Header paths and got htis again:
```
#import <React/RCTBridgeModule.h>
not found
```

**Comment by IvRRimum** [comment]
I think this might be dependency version problem..

**Comment by chrisbianca** [comment]
@IvRRimum Just noticed, you're on RN 0.38.0.  You need to be on RN 0.40.0 or greater to use react-native-firebase 2.0.X as stated here: http://invertase.io/react-native-firebase/#/?id=supported-versions-firebase-react-native

**Comment by IvRRimum** [comment]
Yeah, thanks man. Upgrading the whole app rn.

**Comment by chrisbianca** [comment]
No problem.  Sorry I didn't pick up on that straight away!
