### ISSUE TITLE
onAuthStateChanged not called when on debug mode on iOS

### ISSUE THREAD

**Issue by pierregoutheraud** [invertase/react-native-firebase#2777]
## Issue

If I relaunch my app (full close and relaunch), the `onAuthStateChanged` callback is not called after I log-in using `firebase.auth().signInWithCredential(credential)` (using Facebook).
After that, if I reload it will work fine.
This only happens when in debug mode and on iOS.
`_setUserCredential` is called, `auth_state_changed` native event is not emitted.

Here is a video recording of the process:
https://cl.ly/5530dc8e6847
First I try logging-in when not in debug mode, login works.
I go into debug mode and relaunch the app, the first login hangs.
When I reload, it works again.

## Project Files

```javascript
auth.onAuthStateChanged(function(user) {
  console.log("-- onAuthStateChanged, user:", user);  // log you can see in the video
});

/* ... */

console.log("-- signInWithCredential()"); // log you can see in the video
firebase.auth().signInWithCredential(credential);
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 6.0.2
- **`Firebase` module(s) you're using that has the issue:**
  -  auth
- **Are you using `TypeScript`?**
  - N
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by UrbanChrisy** [comment]
I have been experiencing this issue as well, just upgraded from v5 to v6 and onAuthStateChanged is never called in my instance. I am trying this on android now as I was only trying on iOS. Will try to create a reproducible demo soon.

**Comment by rpadilla6** [comment]
Bumping this since I thought I was taking crazy pills when this happened to me, looks like it might still be an issue.

**Comment by perminder-klair** [comment]
happing for me too!

**Comment by yernandus** [comment]
same thing. latest rn latest firebase

**Comment by nmilcoff** [comment]
I'm experiencing this issue as well!

**Comment by alitsvin** [comment]
Faced this issue as well
