### ISSUE TITLE
[Question] How to setup crashlytics to log unhandled promises ?

### ISSUE THREAD

**Issue by amadeu01** [invertase/react-native-firebase#2778]
## Documentation Feedback

I checked at the doc [v6/crashlytics/reference](https://invertase.io/oss/react-native-firebase/v6/crashlytics/reference/module), however, I couldn't find any instructions to how to activate the log of uncaught failed promises.

Also, I was only able to log and report crashes for `Releases` variant in Android. How can I activate to debug variants?

[Here](https://invertase.io/blog/firebase-crashlytics-for-react-native) is told that 
> JavaScript stack traces are now automatically captured and visible on the Firebase Crashlytics console. > We know you were excited about this when we announced it.

How can I activate that? I haven't found in the documentation either.

**Comment by osrl** [comment]
I'm also interested in this. My craslytics crashes are bundled together. I've seen a  [`setGlobalErrorHandler`](https://github.com/invertase/react-native-firebase/blob/b40d44c57e81a4110cbb4e6204c400cb8f78b00a/packages/crashlytics/lib/handlers.js#L48) function but it's not documented how to use it

**Comment by edmand46** [comment]
and how to use?
