### ISSUE TITLE
[Android] 6.0.2 phone auth failed (evaluating 'this._auth.native')

### ISSUE THREAD

**Issue by kolyasya** [invertase/react-native-firebase#2782]
## Issue

Nothing special, I just setting up a clean project with react-native-firebase

`"react-native": "0.61.2"`
`"@react-native-firebase/auth": "^6.0.2"`

Then running 

```
try {
      const { confirm } = await auth().signInWithPhoneNumber(phone);

      if (confirm) {
        await confirm('111111');
      }
    } catch (err) {
      console.log(err);
    }
```

I get a:

`TypeError: undefined is not an object (evaluating 'this._auth.native')`

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
not following template - can't help
make sure you pod install
I think the suggested pattern is actually to hook onAuthUserChanged listener vs using the async results of the auth functions - the react-native-firebase docs for v5 demonstrate that in their auth section and I don't think it changed for v6?

**Comment by kolyasya** [comment]
@mikehardy I make a second attempt creating a clean project for Android just to test the Auth. I have the same result:

![Screenshot_20191028-153928_Hello App Display Name](https://user-images.githubusercontent.com/3371143/67679103-5e5d5c00-f999-11e9-969f-c68f80169b85.jpg)

**Comment by kolyasya** [comment]
@mikehardy added more info to Environment section in case it makes any sense

**Comment by mikehardy** [comment]
If you'd included gradle I could see if you were on hermes or not. The template is important.

**Comment by kolyasya** [comment]
@mikehardy I didn't change any settings. Clean install with 
`npx @react-native-community/cli init --template=@react-native-firebase/template <name>`

Then setup my Firebase app, set Auth to phone and add phone number.

After that setup auth [https://invertase.io/oss/react-native-firebase/v6/auth/phone-auth](https://invertase.io/oss/react-native-firebase/v6/auth/phone-auth)

I haven't switch on Hermes and didn't change anything in Android settings besides my app's name.

**Comment by kolyasya** [comment]
@mikehardy added all files according to template

**Comment by pavsidhu** [comment]
I'm also getting this error with the same setup.

**Comment by kolyasya** [comment]
@mikehardy are you able to reproduce?

**Comment by mikehardy** [comment]
My work project is still on react-native-firebase.git#v5.x.x sorry - but phone auth (or at least, adding a phone number with SMS verification to an existing email authenticated user account) is working fine for me. I use the auth user changed event listener as mentioned
