### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64 with RN@0.59.10 and CocoaPods

### ISSUE THREAD

**Issue by lucianomlima** [invertase/react-native-firebase#2783]
## Issue

RNFirebase v6 needs RN@0.60+, I have an RN app in v0.59.10.
I'm try to move rnfirebase to CocoaPods, but I always have the `ld: symbol(s) not found for architecture x86_64` error during build. I'm not using any modules yet.

I move carefully through steps. And get this error only when add RNFirebase pod to Podfile.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '9.0'

target 'residencia' do

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'

  # Pods for residencia
  pod 'Firebase/Core', '~> 6.3.0'
  # If I remove the line below, build successfully
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

end
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info
  React Native Environment Info:
    System:
      OS: macOS 10.15
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 598.34 MB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.11.2 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 25, 26, 27, 28, 29
        Build Tools: 25.0.3, 26.0.3, 27.0.3, 28.0.3, 29.0.0, 29.0.2
        System Images: android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6
      react-native: 0.59.10 => 0.59.10
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `v5.5.6`
- **`Firebase` module(s) you're using that has the issue:**
  - `None`
- **Are you using `TypeScript`?**
  - `v3.4.5`
  
</p>
</details>

**Comment by mikehardy** [comment]
I would clone this repo and run this script first: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh - to see how it does what it does. Getting it to work is not easy and there are a few little tricks in there - I only know how to communicate them well by just showing how they work so it means you have to puzzle through the script a little, and be careful to stick closely to it, but it results in a working project android and ios

**Comment by lucianomlima** [comment]
Thanks! For what I can see, in my case, I following all the needed steps. The only difference it's that I declare RNFirebase in my Podfile and [here](https://github.com/mikehardy/rnfbdemo/blob/master/PodfileRN59) doesn't have it.
But on RNFirebase docs says to add it. I'm confuse. Doesn't need the RNFirebase dependency declared on Podfile?

**Comment by mikehardy** [comment]
No - that one doesn't need to be in there - because if you see above in the script we link react-native-firebase *before* the Podfile is in place, which means it is linked in the old way not in the Podfile. react-native-firebase and react-native < 0.60 do not work well with react-native-firebase integrated via Pods. I'm not sure it works at all

**Comment by mikehardy** [comment]
The trick to make that happen if you already have a Podfile is to move your Podfile out of the way (any other place), do the link, then move Podfile back
