### ISSUE TITLE
🔥 auth/unknown an internal error has occurred on android

### ISSUE THREAD

**Issue by eambutu** [invertase/react-native-firebase#2785]
## Issue

When trying to login with email/password, I get an error on my Android Version 9.0 phone (Pixel 2):
```
WARN  Possible Unhandled Promise Rejection (id: 0):
Error: [auth/unknown] An internal error has occurred. [ 7: ]
NativeFirebaseError: [auth/unknown] An internal error has occurred. [ 7: ]
```
There is very little code here, it's merely:
```
import auth from '@react-native-firebase/auth';
...
auth().signInWithEmailAndPassword(email, password);
```
When I run this exact code on my Android Version 7.0 phone (Samsung Galaxy Note 5), it works just fine.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 223.98 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 24, 27, 28
      Build Tools: 27.0.3, 28.0.2, 28.0.3
      System Images: android-27 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | China version of Wear OS Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-fbsdk: 0.8.0
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 6.0.1 for /app and /auth
- **`Firebase` module(s) you're using that has the issue:**
  - auth
- **Are you using `TypeScript`?**
  - N
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by developerashish01** [comment]
any clue on this? I am stuck

**Comment by rafalzawadzki** [comment]
I'm having a similar issue with phone authentication, on `firebase.auth().signInWithPhoneNumber(phoneNumber)` call.

Affects users on:
Android 7, 9
Devices HTC U11 EYEs, Galaxy S8+

**Comment by Rushabhshroff** [comment]
Did anyone find the fix?

**Comment by tarunjuneja** [comment]
Guys i was getting this because i was on Airplane mode
Ensure you are on a valid n/w
the moment i enabled that it started working

**Comment by switch13** [comment]
Still having the same issue.

**Comment by tarunjuneja** [comment]
> Still having the same issue.

Have you already tired adding a pre-validated mobile number on firebase portal

Moreover you will need to build your application with valid deployment key certificate in release mode (which you can generate it on your machine and add it to your app on firebase on firebase portal)

Until i built using release mode with valid certificate i was not able to test it.

**Comment by afx31** [comment]
My app which I started building last year worked fine with the auth, now coming back it it I'm getting the API key not valid message as well.. Was there any solution for this in the end?

Following error when using '.createUserWithEmailAndPassword' method

`[Error: [auth/unknown] An internal error has occurred. [ API key not valid. Please pass a valid API key. ]]`

**Comment by mikehardy** [comment]
@afx31 install fresh google descriptors (GoogleService-Info.plist google-services.json)

**Comment by afx31** [comment]
> @afx31 install fresh google descriptors (GoogleService-Info.plist google-services.json)

I have already installed a fresh google-services.json and this error still pops up

**Comment by afx31** [comment]
@mikehardy  I have already re-installed fresh google-services.json files which didn't do anything.

**Comment by theronic** [comment]
Make sure to enable the sign-in method you are using via the Firebase console. It's a non-descriptive error.

**Comment by bimix** [comment]
Still having this issue when calling a function in the cloud while authenticated with email and password

**Comment by mrlego** [comment]
i am having the same problem please  help

**Comment by tarunjuneja** [comment]
> i am having the same problem please help

#1 add a pre-validated mobile number on firebase portal

#2 generate new deployment key certificate in release mode on your machine 

#3 add this certificate it to your app on firebase on firebase portal

#4 build in release mode

#5 run your app. 

that worked for me.

I was never able to test in debug mode with development certificate.

**Comment by lyseiha** [comment]
any update on it?

**Comment by mikehardy** [comment]
@lyseiha why would there be an update on a closed issue? It's open source --> all updates are visible. And all comments generate notifications.

**Comment by Anadi9** [comment]
> I'm having a similar issue with phone authentication, on `firebase.auth().signInWithPhoneNumber(phoneNumber)` call.
> 
> Affects users on:
> Android 7, 9
> Devices HTC U11 EYEs, Galaxy S8+

have you found any fix for it? i am facing same issue

**Comment by hungdev** [comment]
+1

**Comment by RajanRV** [comment]
[Error: [auth/unknown] An internal error has occurred. [ Internal error encountered. ]]

**Comment by hamzakashifCL** [comment]
I am also getting this error "[Error: [auth/unknown] An internal error has occurred. [ Internal error encountered. ]]" when I want to fetch OTP for mobile signIn

**Comment by brandonsavagesoftware** [comment]
Started getting the same error when the code worked previously.

**Comment by Shyam-Khokhariya** [comment]
I am also getting same error only on release app in android device. Working fine in emulator.
![Screenshot 2023-05-17 at 7 56 53 PM](https://github.com/invertase/react-native-firebase/assets/40089839/56749455-7ccf-4720-90a1-61169e0a89e7)

**Comment by davidcort** [comment]
Same error just now:

Error: [auth/unknown] An internal error has occurred. [ Internal error encountered. ]

**Comment by davidcort** [comment]
> Same error just now:
> 
> Error: [auth/unknown] An internal error has occurred. [ Internal error encountered. ]

This error only happens on Android. I will trying to generate another SHA. Again ...

**Comment by davidcort** [comment]
Ok, i resolved this with the SHA-1 Certificate Fingerprint, i take it from Expo console. (My app uses Expo).
I placed this on the firebase console for my Android Project and works like a charm.

**Comment by Gaurav17-patel** [comment]
Error [auth/unknown] An internal error has occurred. [ Firebase App Check token is invalid. ]

I've facing this error any solution?

**Comment by 69690000** [comment]
🙏🥰🙂
