### ISSUE TITLE
Is it possible "disable" AdMob and keep only AdManager?

### ISSUE THREAD

**Issue by rochapablo** [invertase/react-native-firebase#2795]
For feature requests please visit our [Feature Request Board](https://invertase.io/oss/react-native-firebase/feedback/).

The link above it's not working.

At v5 it was possible use only Banner without the APPLICATION_ID. But Now If I don't have the AdMob ID, the app will crash (https://developers.google.com/admob/android/quick-start#update_your_androidmanifestxml). For Now I have add the sample ID.

On iOS, just adding (https://developers.google.com/ad-manager/mobile-ads-sdk/android/quick-start) It will work, but on Android I need to have this AdManager ID.

**Comment by rochapablo** [comment]
it still require the community's attention

**Comment by Ehesp** [comment]
I'm not sure what the question is? v5 AdMob was running an old SDK version and there were a number of changes we had to make for v6.

What's AdManager?

**Comment by rochapablo** [comment]
["Google Ad Manager is a great way for publishers to start monetizing their apps. It's a rich targeting, reporting, and optimization engine."](https://support.google.com/admanager/answer/6238688?hl=en)

In my applications I just don't show random ads, I have an account at Google Ad Manager and the loaded banners came from a specific ID witch it's different from the Ad Mob App ID's that start with `ca-app-pub-`.

So in the RN Firebase v5, there was no need to have the follow config in AndroidManifest.xml file.

```
<meta-data
          tools:replace="android:value"
          android:name="com.google.android.gms.ads.APPLICATION_ID"
          android:value="ca-app-pub-..."/>
```

But now at v6, if I don't add that code, the app wont build, giving the error message `The Google Mobile Ads SDK was initialized incorrectly.`.  But because I have add a "fake" ID, from the google example, the error stopped.

Because of this, I was wondering, now that I have a fake code running, why not disable this instead. That's why I came here with this question, just to know if this is possible.

**Comment by Ehesp** [comment]
I'll a look - from memory when I upgraded the AdMob SDKs to the latest versions, that "The Google Mobile Ads SDK was initialized incorrectly." message was from the SDK, not us (hence why it's required). I'm not sure there is any downside from adding in a fake App ID, although I'll have a read.

**Comment by cogell** [comment]
@rochapablo Were you able to get Ad Manager working? I'm just starting to see how to add Ad Manager to a React-Native project without writing bridge code (if possible)

**Comment by rochapablo** [comment]
@cogell, for me it's working (v6). you still need to do some work https://github.com/invertase/react-native-firebase/issues/2795#issuecomment-559037359
