### ISSUE TITLE
import type { RemoteMessage }.......There is a compilation error

### ISSUE THREAD

**Issue by cx5168** [invertase/react-native-firebase#2798]
react native: 0.60.4

import type { RemoteMessage } from 'react-native-firebase';

There is a compilation error: ['import ... =' can only be used in a .ts file.] in the vscode.

How to solve it?

**Comment by mikehardy** [comment]
I'm not sure how this is related to the plugin? This seems like a project setup error, like either you should use Typescript (highly recommended), or turn on flow support and turn off typescript support or similar.

There are stackoverflow posts and responses to this error on how to configure vscode

**Comment by faisalrajput** [comment]
use
import { RemoteMessage } from 'react-native-firebase';

**Comment by mm-webx** [comment]
```ts
import { FirebaseMessagingTypes } from '@react-native-firebase/messaging';

cost message: FirebaseMessagingTypes.RemoteMessage;
```
