### ISSUE TITLE
iOS 9 compatibility

### ISSUE THREAD

**Issue by iamkyleee** [invertase/react-native-firebase#28]
My app is built on IOS 9 and upgrading to iOS 10 is a last resort option.

having bugs with ios 9 particularly with UserNotifications

thank you

**Comment by Ehesp** [comment]
Hello, will take a look at this today. Which other features are you having
issues with?

**Comment by Salakar** [comment]
@iamkyleee what issues are you having specifically with ios 9, do you get any red box errors?

More detail would help debug the issue.

Thanks

**Comment by iamkyleee** [comment]
FIrebaseMessaging is where i am facing problems. I decided to remove all it's references and it works now however i wont be able to use it

**Comment by chrisbianca** [comment]
@iamkyleee Are you able to send us over some details of the errors you were getting when you were referencing FirebaseMessaging?

Can you also confirm that you're compiling with iOS 9 rather than iOS 10?

Finally, is there a reason that you're not simply compiling with iOS 10 but targeting iOS 9?

**Comment by Ehesp** [comment]
Closing this issue until further feedback + trying the above answer. Will reopen if needed.
