### ISSUE TITLE
RNFirebaseRemoteConfig.m has a bug

### ISSUE THREAD

**Issue by akshetpandey** [invertase/react-native-firebase#280]
convertFIRRemoteConfigFetchStatusToNSString function return 'config/failure' instead of 'config/success' when it succeeds.

**Comment by Ehesp** [comment]
Could you please place a debugger inside https://github.com/invertase/react-native-firebase/blob/master/ios/RNFirebase/config/RNFirebaseRemoteConfig.m#L10 on Xcode please and tell me what the value is?

**Comment by akshetpandey** [comment]
FIRRemoteConfigFetchStatusSuccess

**Comment by Salakar** [comment]
Looks like it's missing a switch case for success @Ehesp

**Comment by Ehesp** [comment]
@akshetpandey could you put your code here which you're using please? Just want to make sure the fix works for your use case when I fix it.

**Comment by akshetpandey** [comment]
@Ehesp Not sure what you mean, I will just create a PR to fix it.

**Comment by akshetpandey** [comment]
@Ehesp Created PR
