### ISSUE TITLE
Android app crash in start 

### ISSUE THREAD

**Issue by DeevD** [invertase/react-native-firebase#2810]
![Screenshot_20191102-194124](https://user-images.githubusercontent.com/22141397/68071658-e6cd6980-fdaa-11e9-8b6b-a866303adecd.png)

install followed React Native Firebase documentation for version 6
    my package.json file inside "@react-native-firebase/app": "^6.0.3"

**react native version** 
 "react-native": "0.61.2",

**Comment by mikehardy** [comment]
text greatly preferred over images, I can't copy/paste your error and hunt for it

When I do it manually for you the results indicate it is likely multidex
https://duckduckgo.com/?q=java.lang.NoClassDefFoundError%3A+Failed+resolution+of%3A+Lcom%2Fgoogle%2Fandroid%2Fgms%2Finternal%2Fzzbck&ia=web

You might try making sure you do all the required MultiDex enabling. Had you followed the template I would know if you did or not, but I can't without the needed info

https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh#L136

**Comment by DeevD** [comment]
Already solved with upgrade  playServicesVersion 11.xx to  15.0.0 . i was also using react native map package that will be conflict with React Native Firebase package.
