### ISSUE TITLE
Error: [messaging/unknown] The operation couldn’t be completed. (com.firebase.iid error 1001.) NativeFirebaseError: [messaging/unknown] The operation couldn’t be completed. (com.firebase.iid error 1001.)

### ISSUE THREAD

**Issue by ponleukea** [invertase/react-native-firebase#2814]
Error: [messaging/unknown] The operation couldn’t be completed. (com.firebase.iid error 1001.)
NativeFirebaseError: [messaging/unknown] The operation couldn’t be completed. (com.firebase.iid error 1001.) when to try get token with RNF V6.0.3 on IOS anyone can help ?

**Comment by forsen** [comment]
Wouldn't it be easier to take a glance at the issue tracker instead of creating a new issue? 

#2657 is currently the second most commented open issue in this repository, and it is also pinned to the top.

**Comment by BiplovQss** [comment]
> An issue already exist for this problem. Take a look at #2657

there is no solution proved @forsen .
