### ISSUE TITLE
🔥 textRecognizerProcessImage returns an object with blocks: Array(0) regardless of input image on iOS Emulator

### ISSUE THREAD

**Issue by Rob117** [invertase/react-native-firebase#2816]
#2591  Issue

When properly installed, the following code returns an empty array in the text variable: 

```javascript
async getOCR() {
    const text = await vision().textRecognizerProcessImage(
      "/Users/rob/Documents/englishtext.jpg"
    );
    debugger;
  }
```

The method seems to actually be called - when I use a filename with no valid file, it throws an error.

It calls the OCR (seems to take slightly longer the first time, I assume it's downloading the model) but always returns `{blocks: Array(0)}` as an object in debugger (an object with a blocks property set to an array with 0 items).

I thought it might be a problem with my firebase.json, but it's a short file that looks fine.

```
{
  "react-native": {
    "ml_vision_face_model": true,
    "ml_vision_ocr_model": false,
    "ml_vision_barcode_model": true,
    "ml_vision_label_model": true,
    "ml_vision_image_label_model": true
  }
}

```

The image is in English, and returns text no problem when used with the Vision API demo tool.

The code is running on iOS in an iPhone X simulator. The rest of the code in the project works just fine.

---

## Environment

**`react-native info` output:**

```
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Memory: 261.91 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.16.0 - /var/folders/ky/sfz6fdq90f534vsptlfv0x6m0000gn/T/yarn--1572866373075-0.6283137590236536/node
    Yarn: 1.15.2 - /var/folders/ky/sfz6fdq90f534vsptlfv0x6m0000gn/T/yarn--1572866373075-0.6283137590236536/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 28
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    eslint-plugin-react-native: 3.7.0
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.0.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `The Vision module`

Any feedback at all would be great - I'm thinking the firebase.json isn't working properly because I forgot it on first boot and I saw this functionality, then after placing it in the root folder nothing has changed.

**Comment by Salakar** [comment]
Can you try with `"ml_vision_ocr_model": true,`?

**Comment by Rob117** [comment]
Got it solved!

**For people from the future:**

Just updated the file, 
```json
{
  "react-native": {
    "ml_vision_face_model": true,
    "ml_vision_ocr_model": true,
    "ml_vision_barcode_model": true,
    "ml_vision_label_model": true,
    "ml_vision_image_label_model": true
  }
}
```

but also read some documentation and realized that you have to specify these settings **before running pod** install. If you don't, you have to run pod install again so that it will download the correct modules.

I do think it would be super helpful that if a module didn't download, trying to use it would result in an error.

Thank you for the help, @Salakar
