### ISSUE TITLE
'key' property is missing from database reference - Crash with GeoFire

### ISSUE THREAD

**Issue by crocodile** [invertase/react-native-firebase#2818]
## Issue

**I am trying to use 'react-native-firebase' with the ['geofire'](https://github.com/firebase/geofire-js) library as follows:**
```
import database, {firebase} from '@react-native-firebase/database';

let ref = database().ref('somepath')
let geoFire = new GeoFire(ref);
var geoQuery = geoFire.query({
        center: [51.296704, -0.8553124],
        radius: 5,
      });
...
```
**... also tried by referencing firebase directly:**
```
let ref = firebase.database().ref('somepath')
...
```

**Expected:**
No error

**Actual:**

- IDE is complaining the property 'key' is missing in type. 

- App crashes with the following error:
![image](https://user-images.githubusercontent.com/753268/68133947-3fbb1000-ff19-11e9-81fb-bff5f4d70a54.png)

- Basically the key property is not available on the database reference:
![image](https://user-images.githubusercontent.com/753268/68133892-24e89b80-ff19-11e9-98b8-6ac5f901f0ae.png)

This does not happen if I use the 'firebase' package directly (i.e. not using 'react-native-firebase'), but that's not an easy option for me as I am already using this library for authentication and other functions.

**package.json :**
```
  "dependencies": {
    "@react-native-firebase/app": "^6.0.3",
    "@react-native-firebase/auth": "^6.0.3",
    "@react-native-firebase/database": "^6.0.3",
    "@react-native-firebase/firestore": "^6.0.3",
    "@react-native-firebase/messaging": "^6.0.3",
    "react": "^16.9.0",
    "firebase": "^7.2.3",
    "react-native": "0.61.2",
    "@types/firebase": "^3.2.1",
    "geofire": "^5.0.1",
    ...
```
---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Can't say I've ever used GeoFire, but the `key` is/should be there: https://github.com/invertase/react-native-firebase/blob/4709781fb0f5b7a06e1b48d37ebb4363736bf79b/packages/app/lib/common/ReferenceBase.js#L40

My guess would be it's not being handled the same, maybe internally passing the class along and losing the context/serialising etc?

**Comment by ziyaddin** [comment]
@crocodile have you found solution for this issue?

**Comment by danielcolgan** [comment]
@ziyaddin @crocodile looking for an answer as well

**Comment by ziyaddin** [comment]
@danielcolgan I came up with temporary solution:

```ts
const firebaseDb = firebase.database();
const tempRef: any = firebaseDb.ref();
tempRef.key = null;
const firebaseRef: GeoFireTypes.firebase.Reference = tempRef;
const geofire = new GeoFire(this.firebaseRef);
```
Basically, `firebaseRef = tempRef + 'key' property`.

**Comment by crocodile** [comment]
@danielcolgan @ziyaddin I no longer have this issue after upgrading to 6.4.0.

**Comment by ziyaddin** [comment]
@crocodile thanks for informing.
