### ISSUE TITLE
undefined is not an object (evaluating 'FirebaseModule.googleApiAvailability') 

### ISSUE THREAD

**Issue by IvRRimum** [invertase/react-native-firebase#282]
Updated EVERYTHING!
But now, in my Root.js, when i do:
`import firebase from "./firebase";`

i get `undefined is not an object (evaluating 'FirebaseModule.googleApiAvailability') `
<img width="382" alt="screen shot 2017-07-26 at 20 32 30" src="https://user-images.githubusercontent.com/5957079/28634657-8d5ad59c-7240-11e7-9367-bde23b85ffd2.png">

my firebase.js:
```
import RNFirebase from 'react-native-firebase';

const configurationOptions = {
  debug: true
};

const firebase = RNFirebase.initializeApp(configurationOptions);

export default firebase;
```

Thanks!

**Comment by Salakar** [comment]
You're missing RNFirebase from your podfile I'd imagine, make sure you've followed the steps on the docs: http://invertase.io/react-native-firebase/#/installation-ios and the re-run pod install.

**Comment by IvRRimum** [comment]
Argh... added RNFirebase to podifle and got the nasty error again..

<img width="259" alt="screen shot 2017-07-27 at 16 13 06" src="https://user-images.githubusercontent.com/5957079/28671459-7839b926-72e5-11e7-9aa4-76d654167d05.png">

`Argument list too long: recursive header expansion failed at /Users/myapp/Projects/adpages/adpagesgoapp/node_modules/react-native-admob/ios/../../../ios/Pods/React/node_modules/react-tools/src/renderers/shared/reconciler/__tests__.`

**Comment by chrisbianca** [comment]
@IvRRimum it needs to be in cocoapods for RNFirebase to see the imports it requires.

You've still got react-native-admob which is causing the issues and clearly clashing with react-native-firebase.

**Comment by IvRRimum** [comment]
@chrisbianca Not really.
My Podfile:
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target `'MyApp'` do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AdPagesGo

  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crash'

end

**Comment by chrisbianca** [comment]
Is react-native-admob in your package.json?  If it is you'll have to remove it.

Then in both cases run `npm prune`

**Comment by IvRRimum** [comment]
@chrisbianca removed it, ran npm prune. Now i get:

<img width="267" alt="screen shot 2017-07-27 at 16 43 48" src="https://user-images.githubusercontent.com/5957079/28672939-c40d9332-72e9-11e7-901c-141ae593e366.png">

**Comment by chrisbianca** [comment]
And if you add the react and yoga pods to the podfile as per the instructions?

**Comment by IvRRimum** [comment]
@chrisbianca Okey, i could swear i already tryed that before and it didn't work., but next error:
<img width="256" alt="screen shot 2017-07-27 at 16 49 42" src="https://user-images.githubusercontent.com/5957079/28673195-9d5e61b6-72ea-11e7-9133-846da0fa2ec8.png">

**Comment by chrisbianca** [comment]
Can you check your podfile.lock and see which version of Firebase it has installed?

**Comment by chrisbianca** [comment]
If it is not 4.0.X then try running `pod update` to see if it will update to the newer version

**Comment by IvRRimum** [comment]
Almost, but :D:
```
Analyzing dependencies
Fetching podspec for `RNFirebase` from `../node_modules/react-native-firebase`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `Yoga` from `../node_modules/react-native/ReactCommon/yoga`
Removing GoogleInterchangeUtilities
Removing GoogleSymbolUtilities
Removing GoogleUtilities
Downloading dependencies
Installing Firebase 4.0.4 (was 3.5.2)
Installing FirebaseAnalytics 4.0.2 (was 3.3.1)
Installing FirebaseCore (4.0.4)
Installing FirebaseCrash 2.0.0 (was 1.0.7)
Installing FirebaseInstanceID 2.0.0 (was 1.0.8)
Installing Google-Mobile-Ads-SDK 7.21.0 (was 7.10.1)
Installing GoogleToolboxForMac (2.1.1)
Installing Protobuf (3.3.0)
Using RNFirebase (2.0.4)
Using React (0.46.4)
Using Yoga (0.46.4.React)
Installing nanopb (0.3.8)

[!] Error installing nanopb
[!] /usr/bin/curl -f -L -o /tmp/d20170727-13247-tq0c9d/file.tgz http://koti.kapsi.fi/~jpa/nanopb/download/nanopb-0.3.8.tar.gz --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   330  100   330    0     0   1688      0 --:--:-- --:--:-- --:--:--  1692
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 503 Service Unavailable
```

**Comment by IvRRimum** [comment]
And i don't see nanopb in the lock file

**Comment by chrisbianca** [comment]
Looks like it's a dependency of something else.  It's a 503 error which implies that the download site is down, I'd keep trying...

**Comment by jatazoulja** [comment]
Please note that this also happens in android...

does `react-native link` work?

**Comment by chrisbianca** [comment]
@jatazoulja As explained in the install steps (http://invertase.io/react-native-firebase/#/installation-ios?id=_2-setup-rnfirebase), we purposefully do not support `react-native link` as it is not customisable enough for the needs of this project.  As such you will have to go through all the iOS and Android install steps listed.

**Comment by MayasHaddad** [comment]
I ran into this issue a few hours ago.

`FirebaseModule` is `undefined`

```javascript
import { FirebaseModule } from 'react-native'
```

Dragging `libRNFirebase.a` into `XCode > General > Linked Frameworks and Libraries` solved my problem.

Hope it helps.

**Comment by Ehesp** [comment]
Where did you get `import { FirebaseModule } from 'react-native'` from?

**Comment by IvRRimum** [comment]
`pod update `did the trick. However, i don't see my logEvent's in firebase Events section ://

**Comment by IvRRimum** [comment]
I import firebase.js from room.js
`import firebase from "./firebase";`

and then pass it in router:
`<Screen route={route} navigator={navigator} firebase={firebase}/>`

then call in my components:
`this.props.firebase.analytics().logEvent('main_screen', {});`

**Comment by IvRRimum** [comment]
Okey, i got something in streamView. I presume, that data that is shown there will be put in events view after some time, right?

**Comment by Ehesp** [comment]
@IvRRimum yeah they take a number of hours.

**Comment by buremba** [comment]
I installed the library in my project and run into this problem. I even downloaded the `example/demo` project in order to be sure that if I'm missing something but even with your demo project, I still see this error. Any suggestion?

**Comment by JanErikFoss** [comment]
@MayasHaddad That solved my problem, thank you so much

**Comment by marcorm** [comment]
Please can someone tell me how is it possible i've got this issue only on iPhone 4s and on iPhone 5?
From iPhone 5s on it works...
