### ISSUE TITLE
🔥IOS Performance issues: High memory consumption on real time Firestore snapshot and high CPU consumption on fetching data from firestore.

### ISSUE THREAD

**Issue by umang-daffodil** [invertase/react-native-firebase#2823]
## Issue
I am facing some issues with my recent experience with react-native-firebase(using version 5.3.1) in **IOS**, which are affecting the overall app's performance. 
1. Heavy CPU consumption on Firestore query:
2. Heavy memory consumption on Firestore snapshots:

Describe your issue here
**Heavy CPU consumption on Firestore query:**
I am fetching data from a collection on firestore which consists approximately 50,000 records. For fetching first 1000 records (which usually takes approx 18sec), the CPU consumption climbs to 100% for the entire duration which is affecting the performance of the application.

**Heavy memory consumption on Firestore snapshots:**
In order to get real time updates for my firestore collection, I am using Firestore's 'onSnapshpot' function. For every new snapshot I receive, I am experiencing significant rise in the app's memory consumption (as high as 1.5gb on Iphone X), which eventually results in crashing of the app due to memory.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
5.3.1
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
v5 sends a LOT of data over the bridge which is serialised. This is causing the high memory issue, especially for 1k records. 

On v6, we re-wrote the serialiser to be much smaller so should help. The option for v5 would be to batch the data requests as and when you need them.
