### ISSUE TITLE
Notification not working (release mode)

### ISSUE THREAD

**Issue by devit919** [invertase/react-native-firebase#2839]
Hallo..... I am using react-native-firebase with react-native-push-notification for notification....

notification works well in debug mode...but it doesn't work in release mode on my device ......

this is the error while build release apk..

D:\mbire\mbire\android>gradlew app:assembleRelease
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :@react-native-community_checkbox
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.2.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-firebase
react-native-firebase: using React Native prebuilt binary from D:\mbire\mbire\node_modules\react-native\android

> Task :app:transformClassesAndResourcesWithR8ForRelease
R8 is the new Android code shrinker. If you experience any issues, please file a bug at
https://issuetracker.google.com, using 'Shrinker (R8)' as component name. You can
disable R8 by updating gradle.properties with 'android.enableR8=false'.
Current version is: 1.4.94 (build 390954928f0db9c3b888a367f7f128ce3bbfb160 from go/r8bot (luci-r8-ci-archive-0-5g74)).

D8: Missing class: com.google.firebase.database.ValueEventListener
D8: Missing class: com.google.firebase.auth.FirebaseAuth$AuthStateListener
D8: Missing class: com.google.firebase.storage.OnProgressListener
D8: Missing class: com.google.firebase.auth.FirebaseAuth$IdTokenListener
D8: Missing class: com.google.firebase.database.DatabaseReference$CompletionListener
D8: Missing class: com.google.android.gms.ads.VideoController$VideoLifecycleCallbacks
D8: Missing class: com.google.firebase.firestore.EventListener
D8: Missing class: com.google.android.gms.ads.reward.RewardedVideoAdListener
D8: Missing class: com.google.firebase.auth.PhoneAuthProvider$OnVerificationStateChangedCallbacks
D8: Missing class: com.google.android.gms.ads.AdListener
D8: Missing class: com.google.firebase.database.Transaction$Handler
D8: Missing class: com.google.firebase.database.ChildEventListener
D8: Missing class: com.google.firebase.storage.OnPausedListener
D8: Missing class: com.google.firebase.storage.StreamDownloadTask$StreamProcessor
D8: Missing class: com.google.firebase.firestore.Transaction$Function

D8: The rule `-keep class * extends com.facebook.react.bridge.JavaScriptModule {
  *;
}` uses extends but actually matches implements.
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.android.gms.ads.MobileAds` was not found, it is required for default or static interface methods desugaring of `void io.invertase.firebase.admob.RNFirebaseAdMob.initialize(java.lang.String)`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.remoteconfig.FirebaseRemoteConfig` was not found, it is required for default or static interface methods desugaring of `void io.invertase.firebase.config.RNFirebaseRemoteConfig.activateFetched(com.facebook.react.bridge.Promise)`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.auth.ActionCodeSettings` was not found, it is required for default or static interface methods desugaring of `com.google.firebase.auth.ActionCodeSettings io.invertase.firebase.auth.RNFirebaseAuth.buildActionCodeSettings(com.facebook.react.bridge.ReadableMap)`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.crashlytics.android.Crashlytics` was not found, it is required for default or static interface methods desugaring of `void io.invertase.firebase.fabric.crashlytics.RNFirebaseCrashlytics.crash()`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `io.fabric.sdk.android.Fabric` was not found, it is required for default or static interface methods desugaring of `void io.invertase.firebase.fabric.crashlytics.RNFirebaseCrashlytics.enableCrashlyticsCollection()`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.firestore.DocumentChange$Type` was not found, it is required for default or static interface methods desugaring of `void io.invertase.firebase.firestore.FirestoreSerialize$1.<clinit>()`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.firestore.FieldValue` was not found, it is required for default or static interface methods desugaring of `java.util.Map io.invertase.firebase.firestore.RNFirebaseFirestore.getConstants()`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.firestore.FirebaseFirestore` was not found, it is required for default or static interface methods desugaring of `void io.invertase.firebase.firestore.RNFirebaseFirestore.setLogLevel(java.lang.String)`D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_librD:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.auth.PhoneAuthProvider` was not found, it is required for default or static interface methods desugaring of `com.google.firebase.auth.PhoneAuthCredential io.invertase.firebase.auth.RNFirebaseAuth.getPhoneAuthCredential(java.lang.String, java.lang.String)`les\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.firestore
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.firestore.FieldPath` was not found, it is required for default or static interface methods desugaring of `java.lang.Object io.invertase.firebase.firestore.FirestoreSerialize.parseTypeMap(com.google.firebase.firestore.FirebaseFirestore, com.facebook.react.bridge.ReadableMap)`y_classes\release\classes.jar: D8: Type `com.google.firebase.perf.Fire
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.firestore.Blob` was not found, it is required for default or static interface methods desugaring of `java.lang.Object io.invertase.firebase.firestore.FirestoreSerialize.parseTypeMap(com.google.firebase.firestore.FirebaseFirestore, com.facebook.react.bridge.ReadableMap)`.1\dc6d02e4e68514eff5631963e28ca7742ac69efe\okhttp-3.12.1.jar: D8: Type `or
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.firestore.Query$Direction` was not found, it is required for default or static interface methods desugaring of `com.google.firebase.firestore.Query io.invertase.firebase.firestore.RNFirebaseFirestoreCollectionReference.applyOrders(com.google.firebase.firestore.Query)`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.dynamicli
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.auth.FacebookAuthProvider` was not found, it is required for default or static interface methods desugaring of `com.google.firebase.auth.AuthCredential io.invertase.firebase.auth.RNFirebaseAuth.getCredentialForProvider(java.lang.String, java.lang.String, java.lang.String)`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.auth.GoogleAuthProvider` was not found, it is required for default or static interface methods desugaring of `com.google.firebase.auth.AuthCredential io.invertase.firebase.auth.RNFirebaseAuth.getCredentialForProvider(java.lang.String, java.lang.String, java.lang.String)`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.auth.TwitterAuthProvider` was not found, it is required for default or static interface methods desugaring of `com.google.firebase.auth.AuthCredential io.invertase.firebase.auth.RNFirebaseAuth.getCredentialForProvider(java.lang.String, java.lang.String, java.lang.String)`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.auth.GithubAuthProvider` was not found, it is required for default or static interface methods desugaring of `com.google.firebase.auth.AuthCredential io.invertase.firebase.auth.RNFirebaseAuth.getCredentialForProvider(java.lang.String, java.lang.String, java.lang.String)`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.auth.OAuthProvider` was not found, it is required for default or static interface methods desugaring of `com.google.firebase.auth.AuthCredential io.invertase.firebase.auth.RNFirebaseAuth.getCredentialForProvider(java.lang.String, java.lang.String, java.lang.String)`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.auth.EmailAuthProvider` was not found, it is required for default or static interface methods desugaring of `com.google.firebase.auth.AuthCredential io.invertase.firebase.auth.RNFirebaseAuth.getCredentialForProvider(java.lang.String, java.lang.String, java.lang.String)`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.database.FirebaseDatabase` was not found, it is required for default or static interface methods desugaring of `void io.invertase.firebase.database.RNFirebaseDatabase.enableLogging(java.lang.Boolean)`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.auth.FirebaseAuth` was not found, it is required for default or static interface methods desugaring of `void io.invertase.firebase.auth.RNFirebaseAuth._confirmVerificationCode(java.lang.String, java.lang.String, com.facebook.react.bridge.Promise)`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.functions.FirebaseFunctions` was not found, it is required for default or static interface methods desugaring of `void io.invertase.firebase.functions.RNFirebaseFunctions.useFunctionsEmulator(java.lang.String, java.lang.String, java.lang.String, com.facebook.react.bridge.Promise)`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.storage.FirebaseStorage` was not found, it is required for default or static interface methods desugaring of `com.google.firebase.storage.StorageReference io.invertase.firebase.storage.RNFirebaseStorage.getReference(java.lang.String, java.lang.String)`
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.firebase.firestore.SetOptions` was not found, it is required for default or static interface methods desugaring of `void io.invertase.firebase.firestore.RNFirebaseFirestore.documentBatch(java.lang.String, com.facebook.react.bridge.ReadableArray, com.facebook.react.bridge.Promise)`

> Task :app:transformClassesAndResourcesWithR8ForRelease
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Interface `com.google.firebase.database.ValueEventListener` not found. It's needed to make sure desugaring of `io.invertase.firebase.database.RNFirebaseDatabaseReference$5` is correct. Desugaring will assume that this interface has no default method.
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Interface `com.google.firebase.database.DatabaseReference$CompletionListener` not found. It's needed to make sure desugaring of `io.invertase.firebase.database.RNFirebaseDatabase$5` is correct. Desugaring will assume that this interface has no default method.
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Interface `com.google.firebase.storage.OnPausedListener` not found. It's needed to make sure desugaring of `io.invertase.firebase.storage.RNFirebaseStorage$11` is correct. Desugaring will assume that this interface has no default method.
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Interface `com.google.firebase.database.Transaction$Handler` not found. It's needed to make sure desugaring of `io.invertase.firebase.database.RNFirebaseDatabase$1$1` is correct. Desugaring will assume that this interface has no default method.
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Interface `com.google.firebase.database.ChildEventListener` not found. It's needed to make sure desugaring of `io.invertase.firebase.database.RNFirebaseDatabaseReference$3` is correct. Desugaring will assume that this interface has no default method.
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Interface `com.google.firebase.firestore.EventListener` not found. It's needed to make sure desugaring of `io.invertase.firebase.firestore.RNFirebaseFirestoreDocumentReference$4` is correct. Desugaring will assume that this interface has no default method.
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Interface `com.google.firebase.firestore.Transaction$Function` not found. It's needed to make sure desugaring of `io.invertase.firebase.firestore.RNFirebaseFirestore$4$3` is correct. Desugaring will assume that this interface has no default method.
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Interface `com.google.android.gms.ads.reward.RewardedVideoAdListener` not found. It's needed to make sure desugaring of `io.invertase.firebase.admob.RNFirebaseAdMobRewardedVideo` is correct. Desugaring will assume that this interface has no default method.
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Interface `com.google.firebase.storage.OnProgressListener` not found. It's needed to make sure desugaring of `io.invertase.firebase.storage.RNFirebaseStorage$15` is correct. Desugaring will assume that this interface has no default method.
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Interface `com.google.firebase.auth.FirebaseAuth$AuthStateListener` not found. It's needed to make sure desugaring of `io.invertase.firebase.auth.RNFirebaseAuth$1` is correct. Desugaring will assume that this interface has no default method.
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Interface `com.google.firebase.storage.StreamDownloadTask$StreamProcessor` not found. It's needed to make sure desugaring of `io.invertase.firebase.storage.RNFirebaseStorage$13` is correct. Desugaring will assume that this interface has no default method.
D:\mbire\mbire\node_modules\react-native-firebase\android\build\intermediates\runtime_library_classes\release\classes.jar: D8: Interface `com.google.firebase.auth.FirebaseAuth$IdTokenListener` not found. It's needed to make sure desugaring of `io.invertase.firebase.auth.RNFirebaseAuth$2` is correct. Desugaring will assume that this interface has no default method.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings

please...... :'(

**Comment by akhilsanker** [comment]
Hi,

Notification is working on android but not on iOS. 
version:
 "react-native-firebase": "^5.4.0",
	pod 'Firebase/Core', '~> 5.20.1'
	pod 'Firebase/Messaging', '~> 5.20.1'

**Comment by jonystorm** [comment]
Same here, any luck?

**Comment by devit919** [comment]
> Same here, any luck?

solved...... notification already works well ..it cause sha 1 release key..... but the error still show like as above....

**Comment by devit919** [comment]
> Hi,
> 
> Notification is working on android but not on iOS.
> version:
> "react-native-firebase": "^5.4.0",

okay...thank you

**Comment by EhsanSarshar** [comment]
when enabling proguard 
I face the same issue on release mode
and app crash on startup

**Comment by mikehardy** [comment]
@EhsanSarshar I recommended in another spot that you open a new issue with full details, please do so.

**Comment by AfanasievN** [comment]
I fixed the issue after updating gradle by removing from my android folder .gradle

**Comment by AfanasievN** [comment]
also I did npm rm -rf node_modules && npm i && npx jetify && cd android && ./gradlew clean assembleRelease

**Comment by AfanasievN** [comment]
CMD's can be different for your projects

**Comment by mikehardy** [comment]
Save yourself the trouble, use the canonical solution: `npx react-native-clean-project`
