### ISSUE TITLE
updateChildren() is not a function

### ISSUE THREAD

**Issue by nmartin867** [invertase/react-native-firebase#284]
This is more of a question. I am trying to delete multiple children using updateChildren(). It seems this function is not declared on the database reference instance. Is this supported?

```
const fb = RNFirebase.initializeApp(configurationOptions)
fb.database().ref(updatedPath).updateChildren(keyMap) // updateChildren undefined
```

https://firebase.google.com/docs/reference/android/com/google/firebase/database/DatabaseReference.html#updateChildren(java.util.Map<java.lang.String, java.lang.Object>, com.google.firebase.database.DatabaseReference.CompletionListener)

**Comment by Salakar** [comment]
@nmartin866 RNFirebase implementation follows the web SDK API, so in this case you'd want to use `.update()`  -which internally maps through to updateChildren on android and iOS.

**Comment by nmartin867** [comment]
@Salakar works great. Thank you.
