### ISSUE TITLE
GoogleAppMeasurement linker command filed while compiling the iOS build. 

### ISSUE THREAD

**Issue by tejparekh** [invertase/react-native-firebase#2840]
## Issue

I am trying to setup Push Notification for my react native project. 
I have followed the tutorial from the documentations of Invertase. 
I am getting the Linker error while compiling the react native project as follow

ld: framework not found GoogleAppMeasurement
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

target 'XXXXXX' do
  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
  pod 'Firebase/Analytics'

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core', '~> 6.11.0'

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
    if target.name == "yoga"
      target.remove_from_project
    end
  end
end

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
      Memory: 28.37 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.4 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.5.0 => 16.6.0 
      react-native: ^0.57.0 => 0.57.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - "^5.5.6"
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Your Podfile looks odd - you specify a version for some things but not others?

You might try building out the example from here https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh then checking your Podfile vs the one generated. If you just add the Messaging pod extra it should work. There are no compile fails currently, I'm using that 6.11.0 firebase iOS SDK version in my work project with RNFBv5.5.6 and it's fine, so this is a local project setup issue of some kind.

**Comment by tejparekh** [comment]
> Your Podfile looks odd - you specify a version for some things but not others?
> 
> You might try building out the example from here https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh then checking your Podfile vs the one generated. If you just add the Messaging pod extra it should work. There are no compile fails currently, I'm using that 6.11.0 firebase iOS SDK version in my work project with RNFBv5.5.6 and it's fine, so this is a local project setup issue of some kind.

I had removed all the pods from the podfile and updated the file making all the files for Firebase removed. I have added  the Pod details and removed the version specifications I had earlier. Now it looks like this. 

```
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
```


Ran the pod install again. That execution was successful. 
I noticed that the GoogleAppMeasurement Package is downloaded as pods dependencies. 
I can see the framework in the Xcode > Project Workspace > Pods > Pods list 

![Screen Shot 2019-11-10 at 7 48 03 pm](https://user-images.githubusercontent.com/13714772/68541399-0be95a00-03f3-11ea-92ff-10cb8e7bfabc.png)

**Still I get the error of Linker command failed. framework not found GoogleAppMeasurement** 

Thanks in advance. Let me know if i need to share any more information to get the resolution. I have been stuck with this for a week now.

**Comment by mikehardy** [comment]
Ok. How'd it go when you tried the example?

**Comment by tejparekh** [comment]
> Ok. How'd it go when you tried the example?

Adding react-native-firebase dependency
make-demo.sh: line 24: yarn: command not found

Note that I dont have yarn globally install. I have npm installed globally.

**Comment by mikehardy** [comment]
so when you installed it globally to continue the test, what happened? You have to try harder, if you want help.
