### ISSUE TITLE
Implement the in/array-contains-any queries

### ISSUE THREAD

**Issue by FuriioS** [invertase/react-native-firebase#2842]
Firebase launched yesterday the in/array-contains-any queries. I would like the team implements these requests ASAP : )

Reference:
https://firebase.googleblog.com/2019/11/cloud-firestore-now-supports-in-queries.html
https://firebase.google.com/docs/firestore/query-data/queries

**Comment by Salakar** [comment]
We're still waiting on Android SDK support;

![image](https://user-images.githubusercontent.com/5347038/68482674-fa0c8900-0231-11ea-88d6-d6490dd46c2d.png)

**Comment by Salakar** [comment]
Android SDK is now up, we'll get this looked at 🎉

**Comment by meftunca** [comment]
Will 6.1.0 be released today? :)

**Comment by Ehesp** [comment]
@meftunca not today sorry, this isn't a trivial implementation so will take a few days. Should have something up around the weekend.

**Comment by Ehesp** [comment]
@meftunca if you want it sooner, a PR is welcome.

**Comment by meftunca** [comment]
> @meftunca if you want it sooner, a PR is welcome.
Yes I would like to have it earlier if possible

**Comment by Ehesp** [comment]
Started a branch: https://github.com/invertase/react-native-firebase/commit/d74be16f304b41be2b71e4a4077a91746ebb613b

Still needs testing & iOS support.

**Comment by meftunca** [comment]
Hello, what should I do to test the latest version in my project?

**Comment by Ehesp** [comment]
I know you're keen, but you're best waiting until we release it. The branch is WIP  and needs properly testing. Why don't you just mock the results locally for now and wait until we release - it'll be a few days.

**Comment by meftunca** [comment]
Hello, I didn't get the feature I expected in the last update. How soon will you make the update available?

**Comment by mikehardy** [comment]
@meftunca it isn't merged yet, but it appears you can pull the branch and test it if you like https://github.com/invertase/react-native-firebase/compare/@feat/firestore/in-query

**Comment by mikehardy** [comment]
can subscribe to the PR here as well, to see when it is merged https://github.com/invertase/react-native-firebase/pull/2868

**Comment by meftunca** [comment]
> can subscribe to the PR here as well, to see when it is merged #2868

thanks :)

**Comment by meftunca** [comment]
I have a little question. Can I add commit from github as package.json dependencies?

**Comment by meftunca** [comment]
example
`"@react-native-firebase/firestore":"https://github.com/invertase/react-native-firebase/packages/firestoe/#d74be16f304b41be2b71e4a4077a91746ebb613b"`

**Comment by FuriioS** [comment]
> example
> `"@react-native-firebase/firestore":"https://github.com/invertase/react-native-firebase/packages/firestoe/#d74be16f304b41be2b71e4a4077a91746ebb613b"`

npm install --save user/repo#branch

**Comment by meftunca** [comment]
> > example
> > `"@react-native-firebase/firestore":"https://github.com/invertase/react-native-firebase/packages/firestoe/#d74be16f304b41be2b71e4a4077a91746ebb613b"`
> 
> npm install --save user/repo#branch

Can you suggest a working example for Cloud firestore?

**Comment by mikehardy** [comment]
You can, but it's a little more complicated than that for monorepos or repos that are in typescript unfortunately as they aren't published as a copy. I have to admit - I only converted my work project to a monorepo recently and I'm not sure how I would depend on just one package from git from inside a monorepo. 

I have needed to do this before and after reading up on npm and yarn's capabilities, they cannot do it, *but* you can fake it with https://github.com/ramasilveyra/gitpkg

If I understand correctly, you create your own git repo on github that is *just* for publishing these temporary packages. Then you use gitpkg to create a tag of just the files you want from the monorepo (or post-build from a package that needs to be built) and you publish that. Then you depend on your github repo at that tag, and it works? Haven't tried it but the success reports were universal for those with this need.

Might work for you to try this module from this branch

**Comment by jerryheir** [comment]
Uhmmm, Hi Guys, March 27th and I am still on v5.6.0.

**Comment by mikehardy** [comment]
@jerryheir Happy March 27th!

**Comment by jerryheir** [comment]
😂 Okay this response is very funny. I can't stop laughing

**Comment by mikehardy** [comment]
Happy you took it that way, I realized after I typed it...it could go either way, but man I'm stuck in quarantine in my house 2 weeks and my family is tired of my terrible jokes, so I guess github is the outlet ;-). Cheers

**Comment by jerryheir** [comment]
Yeah I understand. Thanks for the reply
