### ISSUE TITLE
Banner Ad link in documentation is broken

### ISSUE THREAD

**Issue by downtowndev** [invertase/react-native-firebase#2851]
## Documentation Feedback

This link is broken:
https://invertase.io/oss/react-native-firebase/v6/admob/reference/bannerad/

This link is in various places, such as the left sidebar (BannerAd) on this page:
https://invertase.io/oss/react-native-firebase/v6/admob/quick-start

**Comment by Ehesp** [comment]
Hello - this is usually because of AdBlocker, not much we can do about it as it's all ad related content. Can you disable it on your browser?

**Comment by 404-html** [comment]
I reported this to AdBlock. Go ahead and do the same, from is pretty friendly. 

![image](https://user-images.githubusercontent.com/45104241/69007548-4dbc5800-093f-11ea-92eb-20787a7f887d.png)

**Comment by Ehesp** [comment]
Thanks!
