### ISSUE TITLE
🔥 Intermittent Crash When using putFile in storage [v6]

### ISSUE THREAD

**Issue by bcgilliom** [invertase/react-native-firebase#2858]
## Issue

Describe your issue here

In release builds on iOS I'm getting a 1-2/10 crash when uploading an image.

RN code:
```
...
    imageRef
      .putFile(uploadUri, {contentType: mime})
        .then(() => imageRef.getDownloadURL())
        .then(url => {
            console.log('Uploaded image to: ', url);
            resolve(url);
        })
      .catch(error => {
        console.log('Error uploading image!', error);
        reject(error);
      });
...
```

I managed to get a symbolicated crash from bugsnag:

`NSInvalidArgumentException *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]`

```
Frameworks/CoreFoundation.framework/CoreFoundation -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
Frameworks/CoreFoundation.framework/CoreFoundation +[NSDictionary dictionaryWithObjects:forKeys:count:]
<myapp>/mobile/node_modules/@react-native-firebase/storage/ios/RNFBStorage/RNFBStorageCommon.m:309:11 +[RNFBStorageCommon getUploadTaskAsDictionary:]
<myapp>/mobile/node_modules/@react-native-firebase/storage/ios/RNFBStorage/RNFBStorageModule.m:456:31 
```

It looks like in some cases, `storageMetadata` is coming back nil, which throws the above exception. I have a "fix" which might just be a band-aid on an underlying issue here:

https://github.com/bcgilliom/react-native-firebase/commit/a53f156c6150a4f274d50eb3b67ab3ef2a92dda4

If that seems like a reasonable way to fix it, I'm happy to make a PR
---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A - relevant stuff is auto-linked
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 243.78 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.0.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `Storage`
- **Are you using `TypeScript`?**
  - `N` & `N/A`
  
</p>
</details>

---

**Comment by Ehesp** [comment]
This is fixed in 6.0.4 - https://github.com/invertase/react-native-firebase/commit/eeb90c0a376e88f4ceb20a1dc5fd3bb4ce558a61 - thanks for the PR
