### ISSUE TITLE
Put with `state_changed` event hangs in Release mode

### ISSUE THREAD

**Issue by MayasHaddad** [invertase/react-native-firebase#287]
I did this http://invertase.io/react-native-firebase/#/modules/storage?id=listen-to-upload-state to be able to track file upload progress onto storage.

It works perfectly fine in debug mode (both on simulator and device).

However in release mode (both on simulator and device), the `progress` callback (second `.on()` parameter) is called only twice, the last call is (92 bytes transferred / ~15000 total bytes).

Neither error `callback`, nor `success` are called afterwards.

It just hangs.

Any clue?

### Environment

1. Target Platform: iOS
2. Development Operating System: macOS Sierra
3. Build tools: XCode 8.3.3
4. React Native version: 0.46.1
5. RNFirebase Version: 2.0.4

**Comment by chrisbianca** [comment]
@MayasHaddad That's strange.  When building in release mode are you targeting a difference project ID then to debug mode?  Just wondering whether it might be a permissions issue with different projects set up in different ways?

I've seen issues where the simulator and device behave differently, mostly caused by file permissions as the simulator doesn't emulate the device perfectly.  This sounds more like a configuration issue though if the device and simulator both work correctly in debug mode.

**Comment by MayasHaddad** [comment]
> When building in release mode are you targeting a difference project ID then to debug mode?

If you are referring to the `POJECT_ID` variable in `GoogleService-Info.plist` then yes, since I use the same file for both build configurations

> Just wondering whether it might be a permissions issue with different projects set up in different ways?
 
On which file in particular?

Troubleshooting this, I went through "Build Settings" section of my target and set "Release" values same as "Debug" ones (except those with variables e.g. `"$PODS_CONFIGURATION_BUILD_DIR/GTMSessionFetcher"`)

I switched to simple storage file upload (http://invertase.io/react-native-firebase/#/modules/storage?id=simple) to see wether it uploads and I realize it doesn't

I must be missing something here 🤔

**Comment by MayasHaddad** [comment]
Adding a breakpoint and that's what I get just before upload stops

![screen shot 2017-07-30 at 2 08 08 am](https://user-images.githubusercontent.com/1893921/28749575-32b5a5fc-74cc-11e7-9083-7b5c63bebc19.png)

Looks like remote server is preventing me from finishing uploading

**Comment by Salakar** [comment]
@MayasHaddad hmm interesting, ye does looks like it's getting rejected by firebase then - either it's firebase storage rules, or potentially something in release build is screwing up the firebase instance init from plist. Not sure what to suggest, my try debugging and see what the auth state is of the default instance or try temporarily allowing all read/write on your storage rules and see if it works.

**Comment by MayasHaddad** [comment]
@Salakar correct.

I debugged firebase login and found out that it returned a `ERROR_CUSTOM_TOKEN_MISMATCH` error.

The reason is that i'm using a custom token provided by my team's production API instead of the dev one, as I use `process.env.NODE_ENV` to know which one to load.

My apologies for spamming.

**Comment by Salakar** [comment]
@MayasHaddad did the auth promise not originally reject with this error when you signed in? Should've done - otherwise that's another issue that would need to be fixed on the lib ;p

**Comment by MayasHaddad** [comment]
@Salakar good point, the bug is on my side too.

I wrote something like this:

```javascript
login = async (username, password) => {
  try {
    const user = await apiLogin(username, password)
    const firebaseUser = firebase.auth().signInWithCustomToken(user.firebaseToken)
  } catch (e) {
    toast(e)
  }
}
```

I obviously forgot to add `await` before `firebase.auth()`
