### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.heartbeatinfo.HeartBeatInfo" 

### ISSUE THREAD

**Issue by barretodsp** [invertase/react-native-firebase#2871]
Hello!

The app crashes after build success and before launch on the device.
The react-native log-android showing anything about it, then next I tried the adb logcat | grep <app_name> and the output was it:

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.heartbeatinfo.HeartBeatInfo" on path: DexPathList[[zip file "/data/app/==/base.apk"],nativeLibraryDirectories=[/data/app/==/lib/arm64, /data/app/==/base.apk!/lib/arm64-v8a, /system/lib64]]

== Environment ===

react-native: 0.60.5
react-native-firebase: 5.5.6

**Comment by mikehardy** [comment]
Without the template I have no real idea. 

https://github.com/firebase/firebase-android-sdk/commits/master/firebase-common/src/main/java/com/google/firebase/heartbeatinfo/HeartBeatInfo.java This shows a history starting in September though, which is quite young

I bet $1 you have versions either mismatched or out of date. Highly recommend using the Bill of Materials style, and the current one (24.1.0?) https://firebase.google.com/support/release-notes/android#bom_v24-1-0
