### ISSUE TITLE
IOS - Push Notification(data message) should receive when app is closed

### ISSUE THREAD

**Issue by onkarjanwa** [invertase/react-native-firebase#2877]
IOS - App receives push notification when app is closed if we send notification message but if we send data message, app does not receive.

This could be a great feature because we also want to customise notification view and IMO that only works with data message.

**Comment by faisalrajput** [comment]
Data message

Use scenario: Client app is responsible for processing data messages. Data messages have only custom key-value pairs.

How to send:
Use your app server and FCM server API: Set the data key only. Can be either collapsible or non-collapsible.

**Comment by faisalrajput** [comment]
I fixed it by sending notification key as well as the data key like this.
{
"to": "",
"data": {
"flag": "",
"image": "",
"title": "Homework",
"message": "Get Today's Homework Done by Tomorrow",
},
"notification": {
"title": "Homework",
"body": "Get Today's Homework Done by Tomorrow"
},
"priority": "high",
"content_available": true,
}

**Comment by luatnd** [comment]
> This could be a great feature because we also want to customise notification view and IMO that only works with data message.

The term `notification` and `data` is on Android platform only.
In fact, iOS works directly with APNS to handle push notification.
IINM, the flow is: 

1. Send FCM message 
2. FCM transform your payload to APNS payload
3. Send to APNS 
4. APNS send push notification to iOS devices.

At step 2, FCM will convert `notification` key to APNS payload, your `data` key is just your custom data in this case, it depends on Firebase.

I cannot find any exist react-native-firebase's document support rich push notification I implement myself (followed this guide):
https://docs.mobile.sailthru.com/docs/ios-rich-push
