### ISSUE TITLE
[Firebase Performance] Installation issues Android 

### ISSUE THREAD

**Issue by minhmera** [invertase/react-native-firebase#288]
Hi everyone. I tried to install Firebase Performance, on iOS it work well but on Android i got issue at this lines 
"apply plugin: 'com.google.firebase.firebase-perf'" // locate on top of build.gradle
"compile "com.google.firebase:firebase-perf:11.0.2"" //locate  on dependencies
It say the error " No instance field zzcsd of type Lcom/google/android/gms/internal/adl" and more , please follow the bellow image and help me 
[http://imgur.com/a/ABFJI](url)

Many thanks
### Environment
1. Target Platform (Android):
2. Development Operating System (macOS Sierra 10.12.3 ):
3. Build tools (Android Studio 2.3.3, Android 6.0):
4. React Native version (0.42):
5. RNFirebase Version (2.0.4):

**Comment by Salakar** [comment]
@minhmera might have something to do with google services plugin version, check you're using the latest one in your build gradle

**Comment by minhmera** [comment]
zdasdasdasd

**Comment by chrisbianca** [comment]
@minhmera Can we see your `app/build.gradle`?  It sounds like something is misconfigured, as we've all been using the perf module without any issues.

**Comment by Ehesp** [comment]
Closing, please provide requested feedback and we can re-open if needed.

**Comment by tiofabby** [comment]
I had same issue when upgrading to Android Studio v3 and SDKs 26.0.2 and struggled days before finding the fix.

Into app/Build.gradle switch to 11.4.2 version:

    compile "com.google.android.gms:play-services-base:11.4.2"
    compile "com.google.firebase:firebase-core:11.4.2"

Into main Build.gradle
  Mobe to 3.1.1 version and add maven url
  classpath 'com.google.gms:google-services:3.1.1'

  maven {
      url 'https://maven.google.com'
  }
See https://rnfirebase.io/docs/v3.0.*/installation/android#4.-Install-modules
