### ISSUE TITLE
onAuthStateChanged fires callback on initialization

### ISSUE THREAD

**Issue by RamKrish2079** [invertase/react-native-firebase#2883]
## Issue

`onAuthStateChanged` fires the callback `AuthListenerCallback` on initialization which is not ideal behavior for event listener

The above behavior of  `onAuthStateChanged` results in unwanted side effects in use case like
```js
useEffect(() => {
    const unSubscriberWhenDone = auth().onAuthStateChanged((user) => {
        doSomethingWhichTriggersRerender()
        doSomethingWhichNeedsNewlyInitializedValues()
    });
    return unSubscriberWhenDone;
}); // no []
```
 `useEffect` invokes its callback after render which initializes `onAuthStateChanged` which triggers its callback even before it returns which then triggers rerender.....wait that doesn't sound good

There is no way you can unsubscribe without the callback getting invoked once

Also
```js
// one time listner
const unSubscriberWhenDone = auth().onAuthStateChanged((user) => {
    // called before onAuthStateChanged() even returns
   unSubscriberWhenDone() // error. Its not a function because its value is not yet set
});
```

currently, as the docs suggests
> It is recommended to use auth#onAuthStateChanged to track whether the user is currently signed in

But IMO using `currentUser` property or something like `getCurrentUser` should just work fine if all you need is to check the current user. And `onAuthStateChanged` can just trigger whenever auth state changes

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.0.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by RamKrish2079** [comment]
I've just realized that [firebase web](https://firebase.google.com/docs/auth/web/manage-users) works the same and this is just replication of its behavior. But still, there is room for improvement.

**Comment by mikehardy** [comment]
I believe the stated goal of this project is to follow the web sdk in all cases where it is practical (that is - is not forced to deviate by platform restrictions) so I'm going to close this as expected behavior, but at the same time that is not to say the upstream is perfect or anything - just that following it is it's own goal for portability in multi-platform apps

**Comment by RamKrish2079** [comment]
I would like to add that firebase-web sdk's `onAuthStateChanged` won't trigger callback synchronously as mentioned [here](https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/auth.js#L1437)

Considering that I think it's not expected behavior that `AuthListenerCallback` being called synchronously

**Comment by RamKrish2079** [comment]
If the `AuthListenerCallback` is not triggered synchronously, the issues mentioned above are fixable

**Comment by mikehardy** [comment]
Hmm - that sounds like a difference vs upstream web sdk behavior? I'll reopen

**Comment by Salakar** [comment]
@RamKrish2079 I guess wrapping [this line](https://github.com/invertase/react-native-firebase/blob/master/packages/auth/lib/index.js#L137) in a Promise like the WebSDK does should solve this issue for you?

**Comment by RamKrish2079** [comment]
@Salakar Yeah that makes its behavior similar to the WebSDK.

Also, it solves the one-time listener issue mentioned above. Unfortunately, it won't solve the issue with `useEffect` which I mentioned above, instead one should prefer using something similar to
```js
const [user, setUser] = useState(null);

useEffect(() => {
    const subscriber = auth().onAuthStateChanged((user) => {
        setUser(user);
    });
    return subscriber;
}, []);

// do everything else based on user object
```
