### ISSUE TITLE
Syntax issue on page with example for `BannerAd`

### ISSUE THREAD

**Issue by 404-html** [invertase/react-native-firebase#2885]
## Documentation Feedback

There's a syntax issue on page with example for `BannerAd`:
https://invertase.io/oss/react-native-firebase/v6/admob/reference/bannerad#requestOptions

```js
onAdFailedToLoad((error) => {
	console.error('Advert failed to load: ', error);
})
```

Should be:
```js
onAdFailedToLoad={(error) => {
	console.error('Advert failed to load: ', error);
}}
```

**Comment by mikehardy** [comment]
Hi there! There is an edit button top right of every page - you can make a PR easily and directly to alter it 💪

**Comment by jankrah12** [comment]
https://invertase.io/oss/react-native-firebase/v6/admob/reference/bannerad does not load. Cannot find doc for implementing banner ads.
