### ISSUE TITLE
Error: Firestore: The service is currently unavailable. (firestore/unavailable)

### ISSUE THREAD

**Issue by dgobaud** [invertase/react-native-firebase#2887]
Same issue as https://github.com/invertase/react-native-firebase/issues/1441

We get a lot of Firestore service unavailable errors we even have it retry once a second for 10 seconds doesn't go away.

Is this a React Native Firebase bug or is it Firestore itself and I need to contact Google?

using "react-native-firebase": "5.5.5",

```
Error: Firestore: The service is currently unavailable. (firestore/unavailable).
  at createErrorFromErrorData(/Users/vsts/agent/2.158.0/work/1/s/node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:155:36)
  at apply(/Users/vsts/agent/2.158.0/work/1/s/node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:31)
  at __invokeCallback(/Users/vsts/agent/2.158.0/work/1/s/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:414:13)
  at fn(/Users/vsts/agent/2.158.0/work/1/s/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:127:12)
  at __guard(/Users/vsts/agent/2.158.0/work/1/s/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:314:9)
  at value(/Users/vsts/agent/2.158.0/work/1/s/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:126:10)
  at [native code] value(:0:0)
```

**Comment by dgobaud** [comment]
anyone? this happened a lot today. firebase support won't help they say the problem is the library

**Comment by Ehesp** [comment]
I can't think of any reason why it would be us. We simply pass some data over to native land and then call the Firebase SDKs with that data. We'd really need some networking logs to really understand what's happening, but that needs to come from Firebase/Google.

**Comment by dgobaud** [comment]
@Ehesp firebase is saying "For libraries leveraging the Web SDK, you may enable debug logging using this line of code:

firebase.firestore.setLogLevel("debug");

Debug logs provides access to the internal state of the SDK, so this information would be valuable to us. Note that the React Native library may expose this method using a different syntax."

does this use the web SDK...? is there another way you have to turn on logging? I can try doing it

**Comment by Ehesp** [comment]
Your best bet would be checking the native logs in Studio/XCode for messages, as we can only relay errors back.

**Comment by dgobaud** [comment]
ok will look - confirming firebase.firestore.setLogLevel("debug"); works?

**Comment by dgobaud** [comment]
it still happens a lot

**Comment by dgobaud** [comment]
It isn't fixed

**Comment by zootopia106** [comment]
This issue still happens

**Comment by zootopia106** [comment]
@dgobaud 
did you solve this issue?

**Comment by dgobaud** [comment]
no - planning to get rid of react native seems to be thing to do

**Comment by zootopia106** [comment]
oh, sad to hear that

**Comment by brandtnewww** [comment]
I'm facing the same issue on my App in production now and then.

`Non-fatal Exception: UnhandledPromiseRejection [firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff. <unknown>`

Would be great to find a workaround soon.

**Comment by findnizam** [comment]
Anyone found a solution for this issue? I am facing this issue in flutter firestore .

**Comment by mikehardy** [comment]
@findnizam so far it seems to have always come down to someone actually not having network

**Comment by findnizam** [comment]
> Anyone found a solution for this issue? I am facing this issue in flutter firestore .

I solved this issue by updating google play services in Emulator.

**Comment by brandtnewww** [comment]
Still happens with
    "@react-native-firebase/app": "^8.4.2",
    "@react-native-firebase/auth": "^9.2.2",
    "@react-native-firebase/firestore": "^7.8.1"

**Comment by VanLaerAshley** [comment]
This issue still happens

**Comment by keving-vargasb** [comment]
Todavía sucede

**Comment by mikehardy** [comment]
I am locking this issue, "me too" comments with no supporting information are worse then unhelpful (since they provide no information to help) they actively take up maintainer time looking at the notification. Please open a new issue and follow the template if you need help, then we can try to see what is going on.
