### ISSUE TITLE
`onTokenRefresh` callback gives token as object not string

### ISSUE THREAD

**Issue by ghsdh3409** [invertase/react-native-firebase#2889]
## Issue

* As a [documentation](https://invertase.io/oss/react-native-firebase/v6/messaging/reference/module#onTokenRefresh), `onTokenRefresh` callback gives fcm token as **string**.
* But, it gives object like `{ token: string }`
* I checked that the native code send fcm object to as `messaging_token_refresh` event.
https://github.com/invertase/react-native-firebase/blob/3582e4865f5da49ba8b70b8681a03b7ba372aa51/packages/messaging/ios/RNFBMessaging/RNFBMessagingDelegate.m#L89-L91 
* We need to decide change documentation or fix return type of callback.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.0.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `messaging`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Corresponding web sdk method does not return anything I think? https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging.html#on-token-refresh

But getToken returns a string (presumably just the token? @ghsdh3409 do you know what the web sdk returns?) https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging.html#get-token


Raw return from Obj-C is just the token https://firebase.google.com/docs/reference/ios/firebasemessaging/api/reference/Protocols/FIRMessagingDelegate#-messaging:didreceiveregistrationtoken:

Same from Java  https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessagingService.html#public-void-onnewtoken-string-token ?

So probably should just be the raw token but that might be a breaking change for people

**Comment by mikehardy** [comment]
I tried to find how Java was handling it but got lost here https://github.com/invertase/react-native-firebase/blob/master/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingSerializer.java#L55 - I can't find the common package to see how it deserializes

**Comment by ghsdh3409** [comment]
@mikehardy 
As the code, you commented, `onTokenRefresh` gives an object containing `token` on the Android, too.
https://github.com/invertase/react-native-firebase/blob/1f622039ccde227cf8dbf9f32d997d3a95a021f8/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingSerializer.java#L52-L56

I also think that it would be better if `onTokenRefresh` gives raw token as `string` since each firebase sdk returns raw token as you commented. (I hope that `react-native-firebase` has a consistency with native sdk references)

Is there any reason why `v6` changed what `onTokenRefresh` gives? (In the previous v5, `onTokenRefresh` gives raw fcm token as `string` (https://rnfirebase.io/docs/v5.x.x/messaging/device-token#2)-Monitor-token-generation))

cc. @Salakar

**Comment by Salakar** [comment]
Pushed a backwards compatible change for this up that supports `onTokenRefresh(event => event.token)` & `onTokenRefresh(token => token)`

`onTokenRefresh(event => event.token)` will log a deprecation warning and will be removed in the next major version

**Comment by markmssd** [comment]
That still seems to happen, using `@react-native-firebase/messaging@6.2`. I suppose the next major version hasn't came out yet right?

Great library btw!

**Comment by markmssd** [comment]
It seems to be fixed with `v6.3.1`, thanks guys! 🎉

**Comment by TPXP** [comment]
A little note on https://github.com/invertase/react-native-firebase/commit/1940d6c8fbab64ccf739186cea9633a605237942 : it changes the type of the value to "object", which might affect the way it is interpreted by other libraries. Make sure to cast it as a string using `toString`or `+ ""` before passing it to other libraries.
```js
messaging().onTokenRefresh((token) => {
  token += "";
  // Now Token is a string
})
```

**Comment by RickWoltheus** [comment]
@Salakar When calling onrefreshToken i am receiving the token like this: ```{"0": "f", "1": "w", "10": "4", "100": "p", "101": "k", "102": "P", "103": "l", "104": "q", "105": "-", "106": "s", "107": "O", "108": "D", "109": "y", "11": ":", "110": "q", "111": "M", "112": "2", "113": "9", "114": "d", "115": "Y", "116": "5", "117": "V", etc etc......} ``` iam not really sure why this is happening

**Comment by TPXP** [comment]
@RickWoltheus That's excactly exactly what I was saying :wink: 
It's caused by the fact that the string is converted to a `String` class, which means it is not a "real" string. Just call `toString()` or force its cast with `+ ""` and you're good to go.
