### ISSUE TITLE
detailed documentation for integrating v6 with react native 0.59.x

### ISSUE THREAD

**Issue by koredeokelowo** [invertase/react-native-firebase#2892]
## Documentation Feedback

Hey guy, is there documentation on how to integrate v6 with react-native 0.59.x? The current documentation assumes the auto linking feature of react-native 0.60.x and above. Attempts to manually link has lead to compilation issues.

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by ziyaddin** [comment]
As I understand from this [source](https://invertase.io/oss/react-native-firebase/v6), the minimum version of React Native must be 0.60.0.
