### ISSUE TITLE
Firebase v6 with @aws-amplify/pushnotification ?

### ISSUE THREAD

**Issue by matamicen** [invertase/react-native-firebase#2894]
Hi Guys,

Do you know if there is any way to use @aws-amplify/pushnotification with Firebase V6? 

I saw this config in my build.gradle of @aws-amplify/pushnotification:
```

  implementation 'com.google.firebase:firebase-core:16.0.7'
  implementation "com.google.firebase:firebase-messaging:17.6.0" 
```

that means that it is using an incompatible version of firebase if I install v6? 
Is there any workaround ?

Thanks @mikehardy @Ehesp :)

**Comment by Ehesp** [comment]
You can try excluding the amplify package dependencies in your own gradle file, it's a bit manual however: https://stackoverflow.com/questions/36103299/in-an-android-gradle-build-how-to-exclude-dependencies-from-an-included-jar-fil
