### ISSUE TITLE
Flow version

### ISSUE THREAD

**Issue by Leeds-eBooks** [invertase/react-native-firebase#29]
Hello! Thanks for all your hard work on this. Great to see your fork graduate to a proper package!

The latest version of flow used by react-native is `0.40`. Running this version against my codebase, I'm getting ~42 flow errors in `react-native-firebase`. I'd love to help you fix these, but I'm not sure which version of flow you're working to. It could be that if I upgraded to `0.42`, there would be no `react-native-firebase` errors, but then I wouldn't be able to flow-check my code because `react-native` is pinned to `flow@0.40`.

Would it make sense to add `[version] ^0.40.0` to this package's `.flowconfig`, to ensure that it matches with react-native? Then I can start submitting PRs 🙂

**Comment by Ehesp** [comment]
Hey, yeah that sounds good. I don't actually think we worked to a flow version, just whatever we had on our macs at the time (woops).

**Comment by Leeds-eBooks** [comment]
Submitted a PR with further discussion
