### ISSUE TITLE
[iOS] Not showing notification banner when app running in Background

### ISSUE THREAD

**Issue by riftshock** [invertase/react-native-firebase#290]
Good Day Sir, 
I'm not really sure where to look and how to fix this Issue. But Apparently When app is running on background or app is closed. No notification banner is showing when receiving push notification.

But I when the app is running, Token is being generated and payload data is well received.
Is there something that I missed? I Don't really have any background on Objective C and I'm Kind of New To Xcode, I mean there's still a lot of stuff on Xcode that I haven't explored yet.

MacOs Sierra Version 10.12.6
Xcode Version 8.3.3
React-Native 0.46.4
RNFirebase Version 2.0.4

Hope anyone has better Ideas, Thank You. =)

**Comment by chrisbianca** [comment]
@riftshock What's the content of the FCM message that you're sending to the app?  Are you including a `notification` part as well as a `data` part?

**Comment by riftshock** [comment]
@chrisbianca Yes I'm Definitely Including **notification**  and **data** as a payload.

I have a backend that is implementing admin SDK of firebase and it works perfectly well on android.

I also tried using firebase console GUI filling out the advance form and still receiving payload as long as my app is opened. But no banners where found.

**Comment by chrisbianca** [comment]
@riftshock Some questions:

1) Are you testing on the simulator or a real device? Push notifications don't work on the simulator
2) Have you enabled the `Push Notifications` capability of your app from within Xcode?
3) Have you enabled `Remote notifications` in the `Background Modes` capability in Xcode?

**Comment by riftshock** [comment]
@chrisbianca I'm using a real device and I also have enabled Push Notifications and Remote notifications under Background Modes on capability within Xcode.

I'm kind of wondering also. On Xcode's **Build Settings** on **Header Search** Paths I can't seem to find any links that points to **react-native-firebase** package. I can see some of my packages are there but not the firebase package. I'm not sure if it's related though.

**Comment by chrisbianca** [comment]
Can you send me the complete FCM message that you're sending?

**Comment by riftshock** [comment]
It's just a basic message for now.

`const payload = {
    notification: {
      title: 'Helpbert Notification',
      body: message,
    },
    data: {
      title: 'Helpbert Notification',
      type,
      message,
      sound: 'default',
    },
  };`

**Comment by chrisbianca** [comment]
Are you setting a `priority` at all as part of the FCM options?  Try setting to `high` if not

**Comment by riftshock** [comment]
@chrisbianca Yes Already done that also. Anyway I Think I just found a better way to solve my case for now. 

I Just started a new fresh project again and tested PushNotif and it works. It's the third time I created A fresh project and I was just following the same steps. And now it works. I don't know where I got it wrong at first though. 

but still my current repo for the project still doesn't work though. Probably there some setting I messed it up with. I'll just migrate it overt the new project I created.

Sorry If I thought it was a bug on the package coz when my teamates did a research about this my fellow developers had the same problem and thought it was a bug. But I'm starting to think that its not.

But Anyways Really Thank You for your time Man. This package really helped a lot in our project. I still need to look this up again though if I had time so my team and I won't make the same mistake all over again.

have a nice day chris and thanks a lot =)

**Comment by chrisbianca** [comment]
No problem, glad you're up and running.  iOS and push notifications are a pain, there's no other way to describe it!

**Comment by riftshock** [comment]
@chrisbianca I figured it out. What I was lacking before was this line of code which works only for IOS:

`firebase.messaging().requestPermissions();`

**Comment by Ehesp** [comment]
Just added a note to the docs for this. Think I hit this issue too once upon a time! https://github.com/invertase/react-native-firebase/commit/989396131c2724095bdf0ce5c422a3cbcf4baf4b
