### ISSUE TITLE
How to work with 2 firebase projects?

### ISSUE THREAD

**Issue by oviedo97fer** [invertase/react-native-firebase#2901]
## Overview

Actually, I'm developing an app that has two environments (Projects) in Firebase: Prod and Dev. I need to create a switch in the UI that allows me to consume data from db prod or db dev according the switch button.
I read the documentation and I think it is possible

**Comment by mikehardy** [comment]
You can always initialize after the fact I suppose, but I've gone a different route - I have multiple backend apps in firebase - one for each environment (dev/test/staging/prod) and at build time on android I build a different flavor for each environment (with different bundle id and different google json) and similar with iOS but one of 4 "apps" with different Info.plit and google plist and app id. For the non-prod apps they just never promote out of "beta" but they are available on the stores, and prod of course promotes out. Took some setting up but there was a guide on the internet about it and it has worked great after initial setup

**Comment by oviedo97fer** [comment]
> You can always initialize after the fact I suppose, but I've gone a different route - I have multiple backend apps in firebase - one for each environment (dev/test/staging/prod) and at build time on android I build a different flavor for each environment (with different bundle id and different google json) and similar with iOS but one of 4 "apps" with different Info.plit and google plist and app id. For the non-prod apps they just never promote out of "beta" but they are available on the stores, and prod of course promotes out. Took some setting up but there was a guide on the internet about it and it has worked great after initial setup

:/ Thanks
