### ISSUE TITLE
Could not find com.google.firebase:firebase-bom:12.0.1

### ISSUE THREAD

**Issue by kirandash** [invertase/react-native-firebase#2902]
I am migrating from [react-native-google-analytics-bridge][1] to [react-native-firebase][2]. I followed the steps to add the package to my android project. At first I got an error saying `method platform()` is not available. Most of the stackoverflow posts said to upgrade the gradle from `3.1.3` to a higher version. So, I updated it to `3.5.0` plugin and `5.6.4` gradle version.

Now, On running the command 'react-native run-android', I am getting the below error:

    Could not determine the dependencies of task ':@react-native-firebase_app:compileDebugAidl'.
    > Could not resolve all task dependencies for configuration ':@react-native-firebase_app:debugCompileClasspath'.
       > Could not find com.google.firebase:firebase-bom:12.0.1.
         Required by:
             project :@react-native-firebase_app

Can someone help with any possible solution to this.

More details:
**android/build.gradle file**

    dependencies {
       classpath 'com.android.tools.build:gradle:3.5.0'
       classpath 'com.google.gms:google-services:4.3.2'
    }

**android/app/build.gradle file:**

    dependencies {
        implementation project(path: ":@react-native-firebase_app")
    }
    
    apply plugin: 'com.google.gms.google-services'

  [1]: https://github.com/idehub/react-native-google-analytics-bridge
  [2]: https://github.com/invertase/react-native-firebase

**Comment by Ehesp** [comment]
Not sure where that `12.0.1` is coming from, we `21.1.0`: https://github.com/invertase/react-native-firebase/blob/master/packages/app/android/build.gradle#L28

Maybe try deleting node_modules, your android build directory and File > invalidating cache on Android Studio and retrying?

**Comment by kirandash** [comment]
@Ehesp Thanks for the quick reply. Followed your instruction but still facing the same issue. I guess the version is being overwritten in `build.gradle` file. 

**build.gradle file**
```
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.google.android.gms'
            && !details.requested.name.contains('multidex') ) {
                details.useVersion "12.0.1"
            }

            if (details.requested.group == 'com.google.firebase') {
                details.useVersion '12.0.1'
            }
        }
    }
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27
                buildToolsVersion "28.0.3"
            }
        }
    }
}
```
Is there any way I can add some code here to make sure that `12.0.1` is not considered for the `firebase-bom`

Also, I have another question if you can answer: Is it mandatory to upgrade the gradle version for the `react-native-firebase` analytics to work. Is there no way we can implement it with `3.1.3` version. As upgrading the gradle is creating many issues for other modules in my project.

Thanks again!

**Comment by mikehardy** [comment]
I'm not sure what the point of all the old versions is. BoM is on 24.1.0 now.
if you use compileSdkVersion 27 I don't think you can use targetSdk 28, and if you don't use targetSdk 28 there's no point, you can't even publish an update to an existing app now unless it's >= 28. And you are overriding multidex to 12.0.1 which does not make sense to me? multidex is 1.0.2 I think? It all seems like a tangle.

I would run either make-demo.sh or make-demo-rn59.sh script from here https://github.com/mikehardy/rnfbdemo really quickly (they don't take long) to see what a from-scratch set of android files look like and work towards that

**Comment by kirandash** [comment]
Hi @mikehardy. Thanks for the quick reply. Spent yesterday trying to setup the `rnfbdemo`. But even there it is throwing some errors. Opened an [issue](https://github.com/mikehardy/rnfbdemo/issues/2). Will work towards the demo once it works.

**Comment by kirandash** [comment]
Hi @mikehardy . Finally I was able to successfully integrate `React Native Firebase` legacy `v5.5.6` to match with `react-native` `v0.59.10` for my project. Now, although I see the live hits report, I can't see the hits from yesterday. Looks like it's not being recorded. And there is a pop up on my analytics screen which still says:

> Notice - This property received hits from the Google Analytics Services SDK, which we have begun sunsetting. See details. On October 31st, 2019 we stopped processing incoming hits for this property and on February 1st, 2020 its data will be permanently deleted. To continue using Google Analytics for your app(s), use our latest App + Web property, which utilizes Google Analytics for Firebase SDK. Learn more.

Not completely sure of the error. As it might be because of the existing production hits coming from  [React Native Google Analytics Bridge](https://github.com/idehub/react-native-google-analytics-bridge)

So, I was wondering: If RNF5.5.6 is using the App + Web property. The `readme.md` file says that it uses the `Firebase SDK`, so I integrated it with my project but now as I am not seeing any past records, I thought of reaching you out for some clarification on: Can I use the RNF5.5.6 version for my project? Will it record analytics data? Or do I need to upgrade to RNF V6.0.4?

**Comment by mikehardy** [comment]
Hey @kirandash sounds like you have something specific happening with your project, all I can say is that you had me scared :sweat_smile: so I just verified and my react-native-firebase v5.5.6 project is logging analytics perfectly. No errors or anything. I have - in our project console - "upgraded analytics" to their new combined analytics thing but it had nothing to do with react-native-firebase, it was only a change in the firebase console. Maybe that's it? Unsure, I just now rnfb556 is fine with analytics

**Comment by kirandash** [comment]
Hey @mikehardy. Sorry for the trouble 😅. I am very much relieved to know that rnfb556 supports the new Analytics changes. I did put a lot of time to set this up. Thanks a lot for the confirmation. I will check why the past analytics data is not being recorded.

Thanks for your help! 🥇

**Comment by haveamission** [comment]
I am also seeing a similar issue here.

I just updated to RNFB 6.1.0.

I am getting the error:

Could not determine the dependencies of task ':app:preReleaseBuild'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.google.firebase:firebase-bom:[15.0.0, 16.0.0).
     Required by:
         project :app > project :@react-native-firebase_app

**Comment by haveamission** [comment]
I am getting a similar error.

* What went wrong:
Could not determine the dependencies of task ':app:preReleaseBuild'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.google.firebase:firebase-bom:[15.0.0, 16.0.0).
     Required by:
         project :app > project :@react-native-firebase_app
         project :app > project :@react-native-firebase_analytics
      > Failed to list versions for com.google.firebase:firebase-bom.

I updated RNFB to latest.

**Comment by mikehardy** [comment]
Not sure why the BOM is being resolved to something so old, but you may override it like so: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh#L29

(it just adds a chunk of gradle variable definition at the bottom of the build script)
