### ISSUE TITLE
Issue with firebase crashlytics with android app .

### ISSUE THREAD

**Issue by abhayjaiswal** [invertase/react-native-firebase#2905]
Hi

I have used react native technology for developing app but Pinpoint exact file name and line number not found on crashlytics dashboard . I have use some javascript file and other files .Please give me solutions . 

I have follow these link for integrate firebase with crashlytics :- https://invertase.io/blog/firebase-crashlytics-for-react-native?utm_source=invertase&utm_medium=blog

I have got java file name and line number on firebase dashboard but we need to found Javascript file name and line number for solve issues .

I have attach screen shoot of dashboard .
![javascript](https://user-images.githubusercontent.com/11692018/69307388-79e21c80-0c50-11ea-9a80-a172947a7e8d.png)

**Comment by mikehardy** [comment]
You've ignored the template, so I'm not sure what version you are on.
In v5 it's impossible.

In v6 the javascript stack trace is possible but you will still be responsible for de-obfuscating the javascript stack back to original source via sourcemaps etc

The first two responses to a search have relevant information https://duckduckgo.com/?q=react-native-firebase+javascript+stack+trace&ia=web
