### ISSUE TITLE
Security rules ignored for data created locally (with persistence enabled)

### ISSUE THREAD

**Issue by Leeds-eBooks** [invertase/react-native-firebase#291]
I'm facing a really weird issue with firebase security rules. I have the following rule:

```js
".read": "auth.uid !== null && (data.child('createdAt').val() > (now - 172800000))"
```

This works as expected, blocking reads for values created more than 172800000ms (48 hours) ago.

However, to test this rule on the iOS simulator, I am creating values with a "fake" `createdAt` value of more than 48 hours ago (I have tried 1000 hours ago, for example) and am still able to subsequently read those values, whether authenticated or not.

As far as I can think, 4 possible things are happening here:

1. `createdAt` is a special field, for every possible node in a firebase database, which is not overwritable. This seems unlikely and I can't find any reference to it.
2. The creator of a value always has permission to read it. By creator, I mean "instance of firebase" or "device", not "user". This also appears to go against all the firebase docs on security.
3. There is special behaviour when the global var `__DEV__` is `true`, or when the environment is signalled as dev in some other way. Again, I can't find any docs on this, and I think it's unlikely.
4. `react-native-firebase` is ignoring the security rules. **I am using offline persistence**, which may be the cause of this. To further test the issue, I tried reading the value not with `.once`, but with `.on`, and I came across the following behaviour which must be a bug: 

```js
db.ref('<refName>').child('<refKey>').on('value',
  () => console.log('success'),
  () => console.log('failure')
)

// > success
// > failure
```

To be clear: **both the success and the failure callbacks are called**. The success callback returns the specified data (which it shouldn't, according to the security rules), and the failure callback returns the following error (which it should, according to the security rules):

```js
Error: permission_denied at ...
```

Any thoughts? Thanks!

### Environment

1. Target Platform (e.g. iOS, Android): iOS
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS latest
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
4. React Native version (e.g. 0.45.1): `0.46`
5. RNFirebase Version (e.g. 2.0.2): `1.1.0`

**Comment by chrisbianca** [comment]
@Leeds-eBooks Interesting issue!  My guess is that it's something to do with the offline persistence as well, however, this would be an issue with the underlying iOS SDK and not `react-native-firebase` as we have no way to bypass the security rules.

You could try testing the official firebase web SDK in your app and see how this behaves?

Out of interest, what's your use case for blocking access to content older than a certain number of days?  I'm thinking that there might be other ways to address this.

Also, you should think about updating to v2 of `react-native-firebase` - whilst there's nothing our side that would have changed to fix this particular issue, it does use the latest v4.0.X version of the underlying Firebase pods so there may be something in there that could help.

**Comment by Leeds-eBooks** [comment]
@chrisbianca Thanks for getting back to me so quickly. I have literally just found this: https://firebase.googleblog.com/2016/11/what-happens-to-database-listeners-when-security-rules-reject-an-update.html

The salient part:
> The client SDK has no knowledge of the security rules for your project. They live and are enforced on the Firebase server side. However, when the SDK handles the call to setValue(), it goes ahead and assumes that the update will actually work on the server. This is the usual case for code that's been written for a database with a particular set of rules – the intent is typically never to violate any rules. With this assumption in play, the SDK goes ahead and acts early, as if the write to the database location has actually succeeded. The result of this is the triggering of all listeners currently added to the changed location within the same app process.

So, I think you're right – this is totally expected behaviour because the client has no knowledge of security rules, and while offline, these rules can't be enforced. And in fact, the success and failure callbacks both being called in `react-native-firebase` is useful, although it is surprising at first. I'm going to submit a PR to your docs mentioning this. Cheers!

**Comment by chrisbianca** [comment]
@Leeds-eBooks No problem, I thought it would be something along those lines.

**Comment by Leeds-eBooks** [comment]
@chrisbianca Also, yeah upgrading to `2.x` is on my todo list! Maybe you could answer the quick question that's holding me back? I read the following somewhere:
> RNFirebase v2 (firebase v4): BREAKING CHANGE firebase.auth.Auth.prototype.onAuthStateChanged now triggers on sign in and sign out.

I'm sure this is already the case in `r-n-firabase@1.x`? I think that's the behaviour I'm seeing anyway!

And to answer your other question, the 48 hours thing is because the data at this location is a "share code", allowing users to invite other users into their data. The share code needs to expire after a certain amount of time to limit the possible attack surface for this feature. I could run a cron job or something to delete codes older than 48 hours but invalidating them via security rules seemed the obvious option.

**Comment by chrisbianca** [comment]
@Leeds-eBooks You're right, that does happen on 1.x as I was using it.  I'm not sure why that's down as a breaking change. @Salakar @Ehesp any ideas?

That makes sense and it's an interesting use case for the security rules - I'd never really considered using them for anything like that!

**Comment by Salakar** [comment]
@Leeds-eBooks @chrisbianca not sure how that `onAuthStateChanged` change snippet snuck into our change log - the underlying official sdk change was for the web sdk - firebase ios and android sdk's have been doing this for a while now - I imagine it's just a long standing discrepancy that they've eventually got around to patching for the web SDK.
