### ISSUE TITLE
Multiple records are missed while trying to save data in offline

### ISSUE THREAD

**Issue by suneelkumargavara** [invertase/react-native-firebase#2924]
- **iOS**:
N/A
- **Android**:
N/A
- **React Native Environment Info**:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
      Memory: 148.77 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
- **Platform that you're experiencing the issue on**
  Android but have not tested behavior on iOS
- **Firebase module(s) you're using that has the issue**
firebase

- **Are you using TypeScript?**
No
I am working in an application where the user can save multiple records to firebase when he is not connected to internet. As per the react-native-firebase documentation, the results will be pushed to firebase when the app comes online. This scenario is working fine when the number of records were saved during the offline were few or very less. If the count increases, I can observe  in my firebase console that there are multiple records missing. I have checked it for multiple times and the issue is reproducible all time.

**Comment by Ehesp** [comment]
Please follow the issue template.

**Comment by suneelkumargavara** [comment]
> Please follow the issue template.

**Comment by suneelkumargavara** [comment]
###

**Comment by mikehardy** [comment]
@suneelkumargavara I would open a fresh issue so the template is fresh
