### ISSUE TITLE
Receiving null from react-native-firebase notification when app  is already killed.

### ISSUE THREAD

**Issue by imran1992** [invertase/react-native-firebase#2925]
Before **Splash Screen** and **Linking** Logic i am receiving data from notification correctly.
But After Adding them I always receive null. I think i am doing wrong in Manifest. 
So here is my Android Manifest:

    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
      package="com.myproject"
      android:versionCode="1"
            android:versionName="1.0"
            xmlns:tools="http://schemas.android.com/tools">
          <uses-permission android:name="android.permission.INTERNET" />
            <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
            <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
            <uses-permission android:name="android.permission.VIBRATE" />
            <uses-permission tools:node="remove" android:name="android.permission.READ_PHONE_STATE" />
         <application
              android:name=".MainApplication"
              android:allowBackup="true"
              android:label="@string/app_name"
              android:icon="@mipmap/ic_launcher"
              android:roundIcon="@mipmap/ic_launcher_round"
              android:theme="@style/AppTheme"
             >
               <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_stat_ic_notification" />
               <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/colorAccent" />
    
           
    
    <activity
              android:name=".SplashActivity"
              android:theme="@style/SplashTheme"
              android:screenOrientation="portrait"
              android:label="@string/app_name">
              <intent-filter>
                  <action android:name="android.intent.action.MAIN" />
                  <category android:name="android.intent.category.LAUNCHER" />
              </intent-filter>
            </activity>
          <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:windowSoftInputMode="adjustResize"
            android:launchMode="singleTask"
            android:exported="true">
            <intent-filter android:label="@string/filter_view_http_clicky">
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" /> 
            <data android:scheme="https"
                  android:host="com.myproject"
                  android:pathPrefix="/" />
            </intent-filter> 
          </activity>
          <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
          <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
            <intent-filter>
              <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
          </service>
          <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
            <intent-filter>
              <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
          </service>
        </application>
    </manifest>

**Comment by mikehardy** [comment]
This isn't a problem with this module, it's a problem with chaining things together as you are close to solving by realizing it was splash screen etc integration. Try the info here: https://github.com/crazycodeboy/react-native-splash-screen/issues/289#issuecomment-502406454

I'm going to close this though, as it is not really a react-native-firebase problem. I understand it *is* a problem though, I'll still be listening in.
