### ISSUE TITLE
Cloud Messaging

### ISSUE THREAD

**Issue by crazypioneer** [invertase/react-native-firebase#2927]
It needs to call below inside AppDelegate on v5.

> [RNFirebaseNotifications configure];

About v6, what I have to do instead?
Even I can't see Notification package...

I used below method but... related callbacks not work...

> firebase.firestore().sendMessage()

```
firebase.messaging().onMessage
firebase.firestore().onMessageSent
```

**Comment by mikehardy** [comment]
If you ignore the template, we can't help effectively

**Comment by crazypioneer** [comment]
I switched v5. It works well now...
