### ISSUE TITLE
Does @react-native-firebase/auth support 'Sign in with Apple' now?

### ISSUE THREAD

**Issue by proIT324** [invertase/react-native-firebase#2929]
Hi everyone,

Firebase announced 'Sign in with Apple' authentication on Nov 15, 2019. 🎉 
[https://firebase.googleblog.com/2019/11/sign-in-with-apple-auth.html](url) 

I would like to add the auth feature to a React Native app ⚛️  I'm working on. I believe it is absolutely GREAT to support it because it will be super widely used. Everyone will send @invertase double thumbs up 👍 👍 . Looking forward it to be published in NPM!!!

Best,
@proit324

**Comment by mikehardy** [comment]
Yeah so, it's more about someone doing the code then offering double thumbs up :-)

Duplicate #2884
