### ISSUE TITLE
FCM + react-native-push-notifications integration

### ISSUE THREAD

**Issue by alex-mironov** [invertase/react-native-firebase#2931]
As push notifications do not work with **react-native-firebase** v.6, I would like to get around this issue through the integration of **react-native-push-notification**.

In this regard, a very high-level question, how does **react-native-push-notification** is supposed to know about the RNF messages?

I've integrated the SDK, aquired the token, and send the message through the Firebase console using this token:
```
await messaging().registerForRemoteNotifications();
await messaging().requestPermission();
const token = await messaging().getToken();
```

From what I can see in **react-native-push-notification** documentation, among others there are `onRegister` and `onNotification` methods. **The question is how do I let this library know about the Firebase messages and connect them?**
```
PushNotification.configure({
  onRegister: function(token) {
    console.log("TOKEN:", token);
  },
  onNotification: function(notification) {
    console.log("NOTIFICATION:", notification);

  },
  senderID: "YOUR GCM (OR FCM) SENDER ID",

}
```

Appreciate a lot any help, I think it will be useful for others as well 🙏

**Comment by netbull** [comment]
@alex-mironov so far I did the same and it works as follows:

Case 1: The message is sent as notification /title, body, etc.../
 - it is handled by the OS and displayed to the user
 - the `onNotification` is triggered only when the notification is tapped by the user
 - `messaging().onMessage(...)` is not triggered /it works only with data messages/

Case 2: The message is sent as data
 - the notification is not shown
 - `onNotification` is always triggered instantly
 - in that case there is an option to use `RNPushNotification` to show local notifications with the data of the message

What is the issue in both cases /at least what i'm facing/:
In both cases the custom data which is from the message is not passed to the `notification` object, which is suppose to hold the data from the message.

**Comment by mikehardy** [comment]
@netbull if you get a data-only cloud message from firebase, it should be hooking firebase.messaging().onMessage, not onNotification? Either way if all the data isn't there, that is likely a messaging module integration issue (missing a service config in AndroidManifest or something etc - depends on platform)

**Comment by netbull** [comment]
@mikehardy it worked totally fine with react-native-firebase v5 and the payload of the message is not changed, I only switched to v6...

I'm currently testing only on iOS.

**Comment by mikehardy** [comment]
I'm less good at Obj-C then Java, so I'm not sure what's going on there. 6.1.0 was just released with a messaging registration fix, you might try it though I don't think it will affect this - low-probability. There may be something in the delegate registration flow changes from RNFBv5->v6 - I'd look through the init sequence and instrument the messaging module's Objc-C with some state dumps as it handles things, but I haven't checked those I'm still on v5 - sorry.
