### ISSUE TITLE
In react-native debug mode notification().onNotification() is working fine but in release mode it's not working. In release and simulator mode, react-native app messaging().onMessage() handler is triggered I don't know why this problem arises. please provide solution. 

### ISSUE THREAD

**Issue by bishwajeet-billme** [invertase/react-native-firebase#2932]
## Issue

Describe your issue here

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
No template -> can't help, sorry

**Comment by bishwajeet-billme** [comment]
@mikehardy 

here is the template

import React, { Component } from "react";
import { AppState, Platform, Alert } from "react-native";
import firebase from 'react-native-firebase';
import { storeFcmToken, fcmTokenStatus, getTokenFromLocal } from "../Config/setLocalDatabase";
import { baseUrl } from "../Config/config";
const Entities = require('html-entities').XmlEntities;
const entities = new Entities();
import { showingToast } from "../Components/CommonComponents/ShowToast";
import NetInfo from "@react-native-community/netinfo";
import axios from "axios";

const displayNotification = (notification) => {
  if (Platform.OS === 'android') {
    const localNotification = new firebase.notifications.Notification({
      sound: 'default',
      show_in_foreground: true,
    }).setNotificationId(notification.notificationId)
      .setTitle(notification.title)
      .setSubtitle(notification.subtitle)
      .setBody(notification.body)
      .setData(notification.data)
      .android.setChannelId('bill_delivery') // e.g. the id you chose above
      .android.setSmallIcon('ic_launcher') // create this icon in Android Studio
      //.android.setColor() // you can set a color here
      .android.setPriority(firebase.notifications.Android.Priority.High);

    firebase.notifications()
      .displayNotification(localNotification)
      .catch(err => console.log(err));
  } else {
    console.log(":FOR IOS :")
    const localNotification = new firebase.notifications.Notification({
      sound: 'default',
      show_in_foreground: true,
    }).setNotificationId(notification.notificationId)
      .setTitle(notification.title)
      .setSubtitle(notification.subtitle)
      .setBody(notification.body)
      .setData(notification.data)


    firebase.notifications()
      .displayNotification(localNotification)
      .catch(err => console.log(err));
  }
}


const subscribeToNotificationListeners = (onNotificationOpenCallback) => {
  //CREATING CHANNEL FOR ANDROID
  console.log("Subscribe to notification....")
  if (Platform.OS === 'android') {
    const channel = new firebase.notifications.Android.Channel(
      'bill_delivery', // To be Replaced as per use
      'Bill Delivery', // To be Replaced as per use
      firebase.notifications.Android.Importance.Max
    ).setDescription('This channel for Bill Delivery notification BillMe App.');
    firebase.notifications().android.createChannel(channel);
  }
  //ON NOTIFICATION REVEIVED
  firebase.notifications().onNotification((notification) => {
    console.log("****On Notification****")
    displayNotification(notification)
  });


  //  ON CLICK ON NOTIFICATION AND APP OPEN
  firebase.notifications().onNotificationOpened(onNotificationOpenCallback);

  // firebase.notifications().getInitialNotification(notification=>{
  //   console.log(notification)
  //   displayNotification(notification)
  // })

  firebase.messaging().onMessage((message) => {
    try {
      const {billUid, brandName, displayAddress, shortId, signedURL, transactionType } = message._data;
      const notifyObj={
        notificationId:message._messageId,
        title:brandName,
        body:'New Bill Arrived into your bucket',
        data:{billUid,brandName,displayAddress,shortId,signedURL,transactionType}
      }
      displayNotification(notifyObj)
    } catch (e) {
      console.log(e)
    }
    console.log("Notification arrived***")
  });


}

//If Token found then send its to sever
const sendFCMTokenToServer = async (pushNotificationToken) => {
  console.log(pushNotificationToken)
  NetInfo.fetch().then(async state => {
    if (state.isConnected || state.isInternetReachable) {
      try {
        const token = await getTokenFromLocal();
        const url = `${baseUrl}/auth/pushnotificationtoken`
        const response = await axios.post(url, { pushNotificationToken }, { headers: { authtoken: token } });
        console.log(response)
        console.log("****FCM Token Send successfully *****")
      } catch (e) {
        console.log(e);
      }
    } else {
      showingToast.internetConnectivity('Internet Connection is not available')
    }
  })

}


export const getFirebaseToken = async (onClickNotifiy) => {
  try {
    console.log(":GETTing firebase:")
    if (Platform.OS === 'android') {
      //Adding listener
      subscribeToNotificationListeners(onClickNotifiy);
      //if token not found then it's saved in local database
      if (await fcmTokenStatus() === null) {
        const fcmToken = await firebase.messaging().getToken();
        if (fcmToken) {
          console.log(":fcm token:");
          console.log(fcmToken);
          await storeFcmToken(fcmToken)
          sendFCMTokenToServer(fcmToken);
        }
      }
    } else {
      const enabled = await firebase.messaging().hasPermission();
      if (enabled) {
        try {
          subscribeToNotificationListeners(onClickNotifiy);
        } catch (error) {
          console.log('error : ', error);
        }
      } else {
        try {
          firebase.messaging().requestPermission()
            .then(async() => {
              subscribeToNotificationListeners(onClickNotifiy);
              const fcmToken = await firebase.messaging().getToken();
              if (await fcmTokenStatus() === null) {
                await storeFcmToken(fcmToken)
                sendFCMTokenToServer(fcmToken);
              }
            })
            .catch(error => {
              console.log('error :', error)
            });
        } catch (e) {
          console.log('error :', error)
        }
      }
    }
  } catch (e) {
    console.log(e)
    showingToast.errorToast('Please uninstall app and install again')
  }


}

**Comment by mikehardy** [comment]
the formatting is unreadable. triple-ticks help a lot. they are in the original template. Please open a new issue fresh + formatted

**Comment by bishwajeet-billme** [comment]
> the formatting is unreadable. triple-ticks help a lot. they are in the original template. Please open a new issue fresh + formatted

ok
