### ISSUE TITLE
Functions & Regions

### ISSUE THREAD

**Issue by l1v3** [invertase/react-native-firebase#2934]
Hey,

i've just started out with firebase functions and i'm not sure if this is a bug, something thats documented to be misunderstood or maybe i'm just doing something wrong :) But i thought it would be good to bring it up here.

I've setup a basic project with react-native-firebase (app, firestore, database, functions for what its worth). Now i've deployed a function in firebase in a non-default region (europe-west1).

Based on the documentation i should use:
import functions from '@react-native-firebase/functions';
functions('europe-west1').httpsCallable(...);

If i do this, i get the following error message:
Error: "firebase.functions(app)" arg expects a FirebaseApp instance or undefined.

What works fine:
firebase.app().functions('europe-west1').httpsCallable(...);

**Comment by mikehardy** [comment]
Could you link to the doc that says to do it the first way? My understanding is you always do the imports first then use them? The docs for v6 are still in a very collaborative / growing phase though so they might need some loving attention...

**Comment by l1v3** [comment]
https://invertase.io/oss/react-native-firebase/v6/functions/quick-start#cloud-functions-region

that code example doesnt work for me, but if i import the firebase instance und use it as described above, it does.

**Comment by mikehardy** [comment]
Thanks for that link! That is...odd. I checked the reference API (different page than quick-start for the module) and it seems to match your experience: https://invertase.io/oss/react-native-firebase/v6/functions/reference/module

There's an edit button at the top right of each page, and github has (in my opinion) a really slick flow for proposing edits to documents, it handles all the irritating fork/branch/propose-PR stuff so it's all done for you. Could you propose an edit to the quickstart that matches the reference (and actually works!) :pray:

**Comment by l1v3** [comment]
of course, i'll do that first thing tomorrow :)

i was just wondering if there was an intention to support the quickstart way. it feels style wise a bit cleaner and more in line with other modules. i'd argue that for another app those extra steps are quite fine, but its more common to select cloud function regions as soon as you leave the default us region (not sure why theyre not deployed close to the project anyway :D)

**Comment by mikehardy** [comment]
In multi-app aware modules (not all the firebase modules are, but some are and functions is) the app has to be part of the initializer when it's standalone because it has all the config info, so I don't think the way it's stated in the quickstart will work but @Salakar or @Ehesp might be more authoritative on it

**Comment by bimix** [comment]
I am having the same issue, I even tried with functions.app() but doesnt work

**Comment by Matgsan** [comment]
There is any way to set it globally?

**Comment by rolfb** [comment]
This just hit me as well, got it solved by using `firebase.app().functions("region_i_wanted")`
@bimix: make sure you use firebase.app(), not functions.app()

Why isn't it picking up the region from the global setup? Firestore has no issues picking the correct region. Happily help with a PR for this if someone can point me in the right direction.

**Comment by Matgsan** [comment]
> This just hit me as well, got it solved by using `firebase.app().functions("region_i_wanted")`
> @bimix: make sure you use firebase.app(), not functions.app()
> 
> Why isn't it picking up the region from the global setup? Firestore has no issues picking the correct region. Happily help with a PR for this if someone can point me in the right direction.

This sets the region globally? If not, do you know how to do so?

**Comment by rolfb** [comment]
I don’t think it will unless your app region and function region is exactly the same.
