### ISSUE TITLE
Update v5 npm README to encourage v6 upgrade

### ISSUE THREAD

**Issue by traviswimer** [invertase/react-native-firebase#2936]
If you look at the [v5 npm page](https://www.npmjs.com/package/react-native-firebase), the readme text does not mention that it is an outdated version.

I was experiencing a bug that had been fixed months ago, and it took me a while to figure out that v6 was released under another npm package name.

I imagine others will be confused by this, so I just wanted to suggest that it might be helpful to publishing a new v5 release to npm with a warning at the top of the README to point people to the [new v6 npm package](https://www.npmjs.com/package/@react-native-firebase/app).

**Comment by traviswimer** [comment]
It looks like this was fixed. 👍 

Thanks open-source people!

**Comment by mikehardy** [comment]
Oh yes! I got that last time, but forgot to circle back here. This was the issue that had me go in there and do it though, so thank you as well :-)
