### ISSUE TITLE
🔥Reset Password, thenreauthenticate with credentials causes stall and memory spike

### ISSUE THREAD

**Issue by dbarner1** [invertase/react-native-firebase#2937]
## Issue
Long time fan. First time caller.

- I have firebase authentication setup in my react native app running smoothly: Creating users, third party sign in, email sign in, sign out, delete account, etc.
 - I'm running into an issue with `user.updatePassword`
- I'm simply running this code block:
```
user.updatePassword(this.state.password).then(() => {
      console.info('Password updated!'); 
    }).catch((e) => {
      console.info(e);

      if (e.message.startsWith('This operation is sensitive')) {
        const credential = {
          email: user._user.email,
          password: [User's entered password]
        };

        user.reauthenticateWithCredential(credential).then(function() {
          console.log("3- Reauthenticated!")
        }).catch(function(error) {
          console.log("4- Error in reauthenticating!")
        });
```

- When `user.reauthenticateWithCredential` is called, xcode reports a memory spike within a block of code within react native firebase (I can provide, if helpful), and then doesn't perform further tasks.  The app just hangs.

Describe your issue here
I think I described it well above.

---

## Project Files

I don't think anything is needed.

### iOS
Not applicable?

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` .59

```
   React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 70.71 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 28, 29
        Build Tools: 28.0.3
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.4 => 0.59.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 5.3.1
- **`Firebase` module(s) you're using that has the issue:**
  - Authentication
- **Are you using `TypeScript`?**
  - No
  
</p>
</details>

🔥🔥🔥🔥🔥 Sending some heat your way, this winter, cause y'all are awesome.
---

**Comment by mikehardy** [comment]
I live in Ecuador, what is this winter you speak of? :smile: 

react-native-firebase 5.3.1, but what version of the underlying SDKs? That's why we ask for the Podfile

Unfortunately - the first thing I'm going to be curious about is if you can either a) reproduce on the tip of either v5.x.x branch or with react-native-firebase v6. I'm guessing v6 is a stretch but if you are on react-native 0.59.4 (why not 0.59.10?) then you can access the tip of the v5.x.x branch and the most up to date SDKs (firebase ios v6.13.0 unless they moved in the last day or so)

or b) compare the chunk of suspect code to the tip of the branch and show it is the same

or even c) produce a tiny reproduction repo on github that demonstrates it?

For hygiene's sake, I'd vote for A - that upgrade should not be much of a stretch and that's more than a year worth of bugfixes etc

**Comment by dbarner1** [comment]
Thanks Mike.

I just tried with 5.5.6.  Still the same error.

Here are screenshots:
[image: Screen Shot 2019-11-30 at 2.27.43 PM.png]
[image: Screen Shot 2019-11-30 at 2.27.39 PM.png]


Podfile:
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Messaging', '~> 5.15.0'
pod 'Firebase/Analytics'
pod 'Firebase/Performance'

I can give version 6+ a try, but it may be a few weeks due to other changes
needed first.

>

**Comment by mikehardy** [comment]
I would not say move to react-native-firebase v6 - that is a big change, but updating your pods to 6.13.0, why not? The changes there were not that great unless you were using invites, but those are all sunsetted at this point anyway I think, so should not matter?
