### ISSUE TITLE
App in background does not receive Cloud messages.

### ISSUE THREAD

**Issue by rogerkerse** [invertase/react-native-firebase#2940]
When I close the screen of my phone while app is opened and send a push notification, my code does not receive it. Only thing i receive is a warning:
`No task registered for key ReactNativeFirebaseMessagingHeadlessTask`

There is no documentation on how to make pushes go through while the app is not in foreground.

**Comment by mikehardy** [comment]
no template
didn't search repo https://github.com/invertase/react-native-firebase/issues?utf8=%E2%9C%93&q=+sort%3Aupdated-desc+ReactNativeFirebaseMessagingHeadlessTask

hopefully something there helps, otherwise new issue but follow template please

**Comment by rogerkerse** [comment]
the explanation is pretty simple, why the enterprise bureaucracy..

**Comment by mikehardy** [comment]
Have you ever attempted to support a module this complex with an installed base this large? If you were attempting to answer your own question what information would you need? that is why
