### ISSUE TITLE
Implementing v6 of Firebase and Firebase Messaging in IOS AppDelegate.m file

### ISSUE THREAD

**Issue by c0d3x** [invertase/react-native-firebase#2942]
I want to implement v6 of Firebase and Firebase Messaging in IOS AppDelegate.m file.
Basically doing an upgrade from v5 where I had my imports look like this:

#import <Firebase.h>
#import <RNFirebase/RNFirebaseNotifications.h>

Is there some documentation on the topic?

**Comment by mikehardy** [comment]
https://invertase.io/oss/react-native-firebase/migrating-to-v6
