### ISSUE TITLE
UIWebView : [Admob] (Deprecated Api Usage)

### ISSUE THREAD

**Issue by yannou788** [invertase/react-native-firebase#2943]
## Issue

"@react-native-firebase/admob": "6.1.0",
TMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView.

After some research, I found that in **RNFBAdMob.podspec** there was an dependency with **PersonalizedAdConsent** (https://github.com/googleads/googleads-consent-sdk-ios/tree/master/PersonalizedAdConsent/PersonalizedAdConsent) which contains call to "UIWebView".

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Admob`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
That's a google upstream bug. For v6 we need to change the issue template here as I need to see the contents of firebase.json to see if you are using the right versions - but I think this is unresolved anyway: https://github.com/googleads/googleads-consent-sdk-ios/issues/41 - follow along there and be prepared to do something like this when/if it is updated: https://github.com/mikehardy/rnfbdemo/blob/65a23cb22b4b91614746c1997f1bf83ca318016a/make-demo-v6.sh#L30

**Comment by douglaslondrina** [comment]
Will this be retrofitted into v5? I'm not ready to jump to 6 yet and I'm having this issue.

Thanks!

**Comment by mikehardy** [comment]
RNFBv5 has no deprecated API usage if you use the up to date firebase SDKs, which you can safely use because I have already retrofitted all the necessary bits

I release to the Apple app store regularly with RNFBv5 + firebase iOS SDKs 6.14.0 (current) and itś fine.

**Comment by douglaslondrina** [comment]
Oh my bad, I thought I was on the latest version.
Thanks Mike!

**Comment by rarira** [comment]
if you use v6 and pod, please try to patch..
I successfully released app to app store.
https://github.com/googleads/googleads-consent-sdk-ios/issues/41

**Comment by mikehardy** [comment]
Oh no - I did not realize there was another usage of UIWebView, thanks for that link @rarira - hopefully it is fixed upstream soon, in the meantime that comment has a great solution
