### ISSUE TITLE
Could not resolve com.google.firebase:firebase-bom:[15.0.0, 16.0.0).

### ISSUE THREAD

**Issue by haveamission** [invertase/react-native-firebase#2949]
##firebase-bom is not resolved

I recently upgraded to 6.1.0 and tried to build an Android app, and got this error message.

Could not determine the dependencies of task ':app:preReleaseBuild'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.google.firebase:firebase-bom:[15.0.0, 16.0.0).
     Required by:
         project :app > project :@react-native-firebase_app
         project :app > project :@react-native-firebase_analytics
      > Failed to list versions for com.google.firebase:firebase-bom.

---

#### `package.json`:

```json
    "@react-native-firebase/analytics": "^6.1.0",
    "@react-native-firebase/app": "^6.1.0",
```

#### `firebase.json` for react-native-firebase v6:

Not sure where this is

### iOS

Problem not occurring with iOS

#### `ios/Podfile`:

N/A

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

### Android
Does not work on app compile

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [X] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

dependencies {
    implementation project(':@react-native-community_netinfo')
    implementation project(':react-native-gesture-handler')
    //implementation project(':react-native-palette-full')
    implementation project(':react-native-onesignal')
    implementation project(':react-native-get-colors')
    implementation project(':@react-native-community_blur')
    implementation project(':@react-native-community_geolocation')
    implementation project(':react-native-radial-gradient')
    implementation project(':react-native-appsflyer')
    implementation project(path: ":@react-native-firebase_app")
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    // https://github.com/wix/react-native-interactable
implementation project(path: ":react-native-interactable")
implementation project(':react-native-maps')

    if (enableHermes) {
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
      implementation jscFlavor
    }
}

**Comment by mikehardy** [comment]
There is no bom of that version. It's on 24.2.0 now I think? Set Android BOM version like so: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh#L29 (but to whatever is current now, check firebase android release notes)
