### ISSUE TITLE
Native module RNFBAppModule tried to override ReactNativeFirebaseAppModule.

### ISSUE THREAD

**Issue by doruxan** [invertase/react-native-firebase#2950]
Hi there;

As I was migrating from v5 to v6 as described in the template, event if I've changed the MainApplication.java file and deleted all the caches from npm, deleting app from device, deleting debug apks etc.. I still face the issue. I think its a cache related issue but I could not resolve it.

This is the issue
![image](https://user-images.githubusercontent.com/45385634/69905546-1a111180-13c6-11ea-89fd-8e869fa04cc9.png)

MainApplication.java

![image](https://user-images.githubusercontent.com/45385634/69905554-31e89580-13c6-11ea-9d52-c1eec7cbea29.png)

app/build.gradle

![image](https://user-images.githubusercontent.com/45385634/69905561-4cbb0a00-13c6-11ea-9137-85d9adcdb981.png)

/build.gradle

![image](https://user-images.githubusercontent.com/45385634/69905565-5e9cad00-13c6-11ea-8fc2-647fd5edd59f.png)

package.json

![image](https://user-images.githubusercontent.com/45385634/69905570-75430400-13c6-11ea-940b-02cd63848d7f.png)

How to reproduce 
-Migrate from v5 to v6
-react-native run-android

How I cleaned cache
- cd android && ./gradlew clean
- watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-* && rm -rf node_modules/ && npm cache clean --force && npm install && npm start -- --reset-cache

Additional Note
-It crashes for every package at the MainActivity.java file. Just wich one comes first in line.

**Comment by mikehardy** [comment]
Text is so much better than graphics, pity the poor people that want to help you but are on a mobile device

`npx react-native-clean-project clean-project-auto` is the gold standard of cache cleaning, learn that tool and use at least some incarnation of it (it has command line switches to control how heavy it will be to rebuild things after)

react-native 0.60+ use auto-linking and in combination with the react-native-firebase v6 separate package style you need to evict all those @react-native-firebase dependencies from gradle, and purge all of the out of your MainApplication list.

This is all you need to to install v6 clean to a clean project - note nothing was done in MainApplication or build.gradle with regard to adding dependencies, just little tweaks for build memory and MultiDex and the gradle plugin processors for crashlytics and performance

**Comment by doruxan** [comment]
Thank you for your suggestions.

**Comment by Salakar** [comment]
You're importing the gradle dependency twice for each package which will cause duplicate module classes, you're importing once via `implementation` and the other is occurring from auto-linking;

![image](https://user-images.githubusercontent.com/5347038/71584198-8425ef00-2b09-11ea-87dc-7877960dab40.png)

Remove all these and you should be good to go:
![image](https://user-images.githubusercontent.com/5347038/71584220-a3bd1780-2b09-11ea-86d8-6f55491b1f8e.png)

**Comment by apotox** [comment]
the firebase massaging works well on debug mode but it doesn't receive messages on the release mode, I have added both debug and release keys SHA1  to my firebase project setting.
 I'm using the latest versions of react-native-firebase packages

`"@react-native-firebase/admob": "^6.7.1",
    "@react-native-firebase/app": "^6.7.1",
    "@react-native-firebase/auth": "^6.7.1",
    "@react-native-firebase/crashlytics": "^6.7.1",
    "@react-native-firebase/messaging": "^6.7.1",
    "@react-native-firebase/remote-config": "^6.7.1",`

everything works fine except the messaging on the release mode (assembleRelease)
