### ISSUE TITLE
🔥V6.X [iOS] Dynamic Links onLink not triggering

### ISSUE THREAD

**Issue by ammichael** [invertase/react-native-firebase#2954]
## Issue

After upgrading to V6 I'm not being able to get the data from Dynamic Link. Despite the link opening my app, I'm not receiving any trigger on JS side. If I put a `NSLog` in `restorationHandler` I can see it's being called when opening the link, but the `onLink` is never triggered on JS.

In summary:
- It correctly opens the app from email link after clicking a button from a preview page in Safari (is it possible to skip this step?)
- It triggers `application:continueUserActivity:restorationHandler` on `AppDelegate.m` but it *doesn't* trigger `onLink`.
- `getInitialLink` resolves to a previously opened link only when *uninstall and install* the app again, otherwise it resolves to `null`, even when force closing the app and opening it from the link.
- 

Important to notice I'm using react-native-fbsdk and @react-native-community/google-signin. Following the docs there are no instructions on how to handle multiple Universal Links handlers.

Describe your issue here

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

```JS
  const verifyLink = async link => {
    console.log('LOG: verifyLink');
    const isSignInLink = firebase.auth().isSignInWithEmailLink(link);
    console.log('LOG: isSignInLink', isSignInLink);
  };

  useEffect(() => {
    (async function checkInitialLink() {
      const initialLink = await firebase.dynamicLinks().getInitialLink();
      console.log('LOG: checkInitialLink -> initialLink', initialLink);
      if (initialLink) {
        verifyLink(initialLink);
      }
    })();
    // eslint-disable-next-line sonarjs/prefer-immediate-return
    const unsubscribe = firebase.dynamicLinks().onLink(link => {
      console.log('log: onLink', link);
      verifyLink(link);
    });
    return unsubscribe;
  }, []);
```
#### `package.json`:

```json
    "@react-native-firebase/analytics": "^6.1.0",
    "@react-native-firebase/app": "^6.1.0",
    "@react-native-firebase/auth": "^6.1.0",
    "@react-native-firebase/crashlytics": "^6.1.0",
    "@react-native-firebase/dynamic-links": "^6.1.0",
    "@react-native-firebase/firestore": "^6.1.0",
    "@react-native-firebase/iid": "^6.1.0",
    "@react-native-firebase/in-app-messaging": "^6.1.0",
    "@react-native-firebase/messaging": "^6.1.0",
    "@react-native-firebase/perf": "^6.1.0",
    "@react-native-firebase/remote-config": "^6.1.0",
    "@react-native-community/google-signin": "^3.0.3",
    "react-native-fbsdk": "^1.1.1",
```
</p>
</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Finex' do
  #Pods for Finex
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Third Parties
  use_native_modules!
  pod 'RNQuickAction', :path => '../node_modules/react-native-quick-actions'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

```

#### `AppDelegate.m`:

```objc
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"
#import <React/RCTBridge.h>
#import "RNQuickActionManager.h"
#import <Firebase.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>
#import <RNCPushNotificationIOS.h>
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <RNGoogleSignin/RNGoogleSignin.h>
#import "RNFBDynamicLinksAppDelegateInterceptor.h"

#if RCT_DEV
#import <React/RCTDevLoadingView.h>
#endif

@implementation AppDelegate

- (void)application:(UIApplication *)application performActionForShortcutItem:(UIApplicationShortcutItem *)shortcutItem completionHandler:(void (^)(BOOL succeeded)) completionHandler {
  [RNQuickActionManager onQuickActionPress:shortcutItem completionHandler:completionHandler];
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
  [FBSDKAppEvents activateApp];
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIROptions defaultOptions].deepLinkURLScheme = @"br.com.meevi.finex";
  [FIRApp configure];
  
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"Finex"
                                            initialProperties:nil];

#if RCT_DEV
  [bridge moduleForClass:[RCTDevLoadingView class]];
#endif
  // 1. Load the LaunchScreen from the xib file
  UIView *backgroundView = [[[NSBundle mainBundle] loadNibNamed:@"LaunchScreen" owner:self options:nil] firstObject];

  // 2. Set the backgroundColor of the react view to be transparent
  rootView.backgroundColor = [UIColor clearColor];
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  // 3. Set the backgroundView as main view for the rootViewController (instead of the rootView)
  rootViewController.view = backgroundView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  // 4. After the window is visible, add the rootView as a subview to your backgroundView
  [backgroundView addSubview:rootView];
  // 5. Then make the rootViews frame the same as the backgroundView
  rootView.frame = backgroundView.frame;
  return YES;
}//didFinishLaunchingWithOptions

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}//sourceURLForBridge


//// <----- START URL HANDLER CONFIGS ------>


- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<NSString *, id> *)options {
  NSLog(@"LOG: openURL");
  BOOL handledByFacebook = [[FBSDKApplicationDelegate sharedInstance] application:application
                                                                          openURL:url
                                                                sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                                                                       annotation:options[UIApplicationOpenURLOptionsAnnotationKey]];
  BOOL handledByGoogle = [RNGoogleSignin application:application openURL:url options:options];
  BOOL handledByFirebase = [[RNFBDynamicLinksAppDelegateInterceptor sharedInstance] application:application openURL:url options:options];

  return handledByFacebook || handledByGoogle || handledByFirebase;

}//openURL


- (BOOL)application:(UIApplication *)application
continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler: (nonnull void (^)(NSArray<id<UIUserActivityRestoring>> *_Nullable))restorationHandler {
   NSLog(@"LOG: restorationHandler");
  return [[RNFBDynamicLinksAppDelegateInterceptor sharedInstance] application:application
                            continueUserActivity:userActivity
                              restorationHandler:restorationHandler];
}

// <----- END URL HANDLER CONFIGS ------>


#if RCT_DEV
  - (BOOL)bridge:(RCTBridge *)bridge didNotFindModule:(NSString *)moduleName {
    return YES;
  }
#endif

  @end

```

</p>
</details>
---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
    Memory: 337.32 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [X] **iOS** but have not tested behavior on Android
- **`react-native-firebase` version you're using that has this issue:**
  - `6.x`
- **`Firebase` module(s) you're using that has the issue:**
  - `Dynamic Links`
  - `Auth`
  - `Crashlytics`
  - `Analytics`
  - `Firestore`
  - `Messaging`
  - `In App Messaging`
  - `Perf`
  - `Remote Config`
  - `IID`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
This is not documented well currently. Have you searched the related issues? There are some code snippets and workarounds there.

Initial thoughts:

- the google sign in docs have the best "handle multiple" openURL examples, something related is likely the real solution and needs documenting
- users have reported success using the built-in react-native Link APIs to get the links resolved, even within react-native-firebase. That could unblock you

**Comment by ammichael** [comment]
Thanks for your thoughts, @mikehardy 
I took your suggestion and tried using React Native Linking to it working, and it really worked fine replacing the `onLink` method. Still, it doesn't work when app is closed and it's opened through the dynamic link.

**Comment by mikehardy** [comment]
the answer for that one will be variable I think - it can work if configured perfectly but it can also fail if configured perfectly, for instance in one of the related issues here it turns out the facebook's in-app browser breaks things due to an upstream Firebase SDK bug - unsure if there is any resolution on that

**Comment by karanwadhwa** [comment]
@ammichael @mikehardy were you able to figure this out?
I did go back and refer docs for v5 and found this [link](https://github.com/invertase/react-native-firebase-docs/blob/master/docs/links/ios.md)
I also have facebook and google sign in which I've handled like so
```c#
- (BOOL)application:(UIApplication *)application openURL:(nonnull NSURL *)url options:(nonnull NSDictionary<NSString *,id> *)options {

  return [[FBSDKApplicationDelegate sharedInstance] application:application openURL:url options:options] || [RNGoogleSignin application:application openURL:url options:options];
}
```
idk if something similar has to be done for firebase dynamic links v6 as well?
@mikehardy I went through the v6 documentation, couldn't find any such setup. Did I miss anything?

I tried using Linking as well, no luck. still the same issue - app opens fine `dynamicLinks().getInitialLink()`/ `Linking.getInitialURL()` both return `null` and `dynamicLinks().onLink()` is never fired.

Tried the same on an empty project and that worked perfectly fine, no issues; which leads me to believe I probably need to edit `AppDelegate.m`
I even removed the openURL bit just to check if that might work, still the same.

**Comment by ammichael** [comment]
Hey there @karanwadhwa!

Somehow I got it working on my setup with Facebook and Google SignIn as well, but since I couldn't really pinpoint what was the fix, I didn't update here. So I'll try help by sharing my setup:

**AppDelegate.m**
```
//// <----- START URL HANDLER CONFIGS ------>


- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<NSString *, id> *)options {
  NSLog(@"NLOG: openURL");
  BOOL handledByFacebook = [[FBSDKApplicationDelegate sharedInstance] application:application
                                                                          openURL:url
                                                                sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                                                                       annotation:options[UIApplicationOpenURLOptionsAnnotationKey]];
  BOOL handledByGoogle = [RNGoogleSignin application:application openURL:url options:options];
  BOOL handledByFirebase = [[RNFBDynamicLinksAppDelegateInterceptor sharedInstance] application:application openURL:url options:options];
  BOOL handledLinking = [RCTLinkingManager application:application openURL:url options:options];

  return handledByFacebook || handledByGoogle || handledByFirebase || handledLinking;

}//openURL


- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}//restorationHandler

// <----- END URL HANDLER CONFIGS ------>

```
**Associated Domains**
![image](https://user-images.githubusercontent.com/6873880/82354580-61707600-99d7-11ea-9883-4415deb26815.png)

**ActionCodeSettings**
```
const actionCodeSettings: FirebaseAuthTypes.ActionCodeSettings = {
  url: 'https://{app}.firebaseapp.com',
  handleCodeInApp: true,
  iOS: {
    bundleId: '{bundleID}',
  },
  android: {
    installApp: true,
    packageName: '{packageName}',
  },
};

await FirebaseAuth.sendSignInLinkToEmail(email, actionCodeSettings);

```

**Deep linking:** 
```
 const checkInitialLink = async (): Promise<void> => {
    const initialLink = await Linking.getInitialURL();
    if (initialLink && initialLink.url) {
        Firebase.auth().signInWithEmailLink(email, initialLink.url);
    }
  };
```

I used [Linking](https://reactnative.dev/docs/linking) instead of Firebase's method to check for initial link.

Hope it helps!

**Comment by karanwadhwa** [comment]
@ammichael thanks a lot for that!
I was able to set it up using Linking, but heres the catch - `Linking.getInitialURL()` always returns `null` but `Linking.addEventListener("url", event => console.log(event))` works perfectly every time and gets me the url when the app is in foreground. Unfortunately this doesn't really solve my purpose.
Also I wasn't able to import `RNFBDynamicLinksAppDelegateInterceptor`. Could you help me out with that?

[From what I understand](https://reactnative.dev/docs/linking#enabling-deep-links) the `openURL` block in AppDelegate is for listening to incoming app links during your app's execution; which I got working with Linking
And `restorationHandler` is for universal links. I've set that up with Linking as well but can't get it to return anything other than `null`
```objective-c
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}
```

**Comment by karanwadhwa** [comment]
never mind. apparently it was working all along. problems with the debugger.
for anyone else facing this issue - follow the steps in the comments above and [disable remote debugging](https://github.com/facebook/react-native/issues/24429#issuecomment-489702443).

**Comment by mikehardy** [comment]
@c-emil I believe the link contents have to be url encoded? That `=` sign should be `%3D`, does it work if you do that?
