### ISSUE TITLE
Does Notification Module will not supported anymore?

### ISSUE THREAD

**Issue by SaeedZhiany** [invertase/react-native-firebase#2958]
I just saw a commit on README.md with ["goodbye notification"](https://github.com/invertase/react-native-firebase/commit/0e025a13c29c1787c3c3662befdb00e89ab99437)!!! what is mean by that? does the notification module will not supported on V6+ anymore? I didn't see any documentation for that and I just wondering what is the plan on this module?

**Comment by mikehardy** [comment]
@SaeedZhiany a status tracker is the first pinned issue on the repo: https://github.com/invertase/react-native-firebase/issues/2566

**Comment by SaeedZhiany** [comment]
Hi @mikehardy, Yeah I know, and I check that issue first but didn't see any related information about the "goodbye notification" commit, so I had to open a new issue again.

**Comment by SaeedZhiany** [comment]
Hi @mikehardy, Yeah I know, and I checked that issue first but didn't see any related information about the "goodbye notification" commit, so I had to open a new issue again.

**Comment by mikehardy** [comment]
It's going to be a standalone package I believe, so it needed to be refactored out of the react-native-firebase monorepo. The issue status in general (minus structural items) from the one I linked is still the best information we have. As mentioned there, it's a ridiculously large API, it takes time
