### ISSUE TITLE
How to import a package from a fork

### ISSUE THREAD

**Issue by 7patricia** [invertase/react-native-firebase#2964]
Hi!

I'm trying to import a package from a fork I created from your repo and I am not finding a solution.
I also searched the documentation and I didn't find anything regarding that.

I tried a few alternatives: 
-  Adding `"@react-native-firebase/app": "git+ssh://git@github.com/my-repo/react-native-firebase#mybranch"` to `package.json`;
- Adding `"@react-native-firebase/app": "git+ssh://git@github.com/my-repo/react-native-firebase/tree/master/packages/firestore#my-branch"` to `package.json`;

It always throws an error of `cannot find version of undefined` when running `yarn`.

----------------------------------
Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
which versions are you on? Based on your PR separate, I think it is react-native-firebase v6 yes? If so, I struggled with this as well - there is not good tooling support for installing one package from a monorepo. The best I saw was something called "gitpkg", that lets you have a fork, make changes, run the build then "publish" it as a special github repo with the single-package build result. You could also npm publish to a personal npmjs.com personal namespace maybe?

**Comment by 7patricia** [comment]
Hi @mikehardy! Yes, I am using v6. 
We were trying to avoid having to publish a package for this, but if that's the only way, it will have to do. 

Thank you!

**Comment by mikehardy** [comment]
There is always the patch-package option I use it all the time for small things, very effective

**Comment by mikehardy** [comment]
@Salakar I thought the react-navigation documented this pretty well, and recommends the only solution I'm aware of at the moment. Do you think this could fit in the docs anywhere? https://github.com/react-navigation/react-navigation#installing-from-a-fork-on-github
