### ISSUE TITLE
Error library not found for -lBoringSSL-GRPC when build app on ios

### ISSUE THREAD

**Issue by v2media** [invertase/react-native-firebase#2966]
## Issue

Ld /Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/reactnativesecretapp.app/reactnativesecretapp normal x86_64 (in target 'reactnativesecretapp' from project 'reactnativesecretapp')
    cd /Volumes/Work/workspace/app/reactnativesecretapp/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios9.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/BoringSSL-GRPC -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/DoubleConversion -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/FBReactNativeSpec -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/FirebaseAuth -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/FirebaseCore -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/FirebaseFirestore -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/FirebaseFunctions -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/FirebaseInstanceID -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/FirebaseMessaging -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/Folly -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/GTMSessionFetcher -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/GoogleUtilities -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/Protobuf -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/RCTTypeSafety -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/RNCAsyncStorage -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/RNDeviceInfo -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/RNFirebase -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/RNGestureHandler -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/RNSVG -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/RNScreens -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-Core -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-CoreModules -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTActionSheet -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTAnimation -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTBlob -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTImage -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTLinking -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTNetwork -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTSettings -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTText -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTVibration -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-cxxreact -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-jsi -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-jsiexecutor -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-jsinspector -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/ReactCommon -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/Yoga -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/gRPC-C++ -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/gRPC-Core -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/glog -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/leveldb-library -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/nanopb -L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/react-native-location -F/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator -F/Volumes/Work/workspace/app/reactnativesecretapp/ios/Pods/Crashlytics/iOS -F/Volumes/Work/workspace/app/reactnativesecretapp/ios/Pods/Fabric/iOS -F/Volumes/Work/workspace/app/reactnativesecretapp/ios/Pods/FirebaseAnalytics/Frameworks -F/Volumes/Work/workspace/app/reactnativesecretapp/ios/Pods/GoogleAppMeasurement/Frameworks -filelist /Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Intermediates.noindex/reactnativesecretapp.build/Debug-iphonesimulator/reactnativesecretapp.build/Objects-normal/x86_64/reactnativesecretapp.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -object_path_lto -Xlinker /Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Intermediates.noindex/reactnativesecretapp.build/Debug-iphonesimulator/reactnativesecretapp.build/Objects-normal/x86_64/reactnativesecretapp_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -lBoringSSL-GRPC -lDoubleConversion -lFBReactNativeSpec -lFirebaseAuth -lFirebaseCore -lFirebaseFirestore -lFirebaseFunctions -lFirebaseInstanceID -lFirebaseMessaging -lFolly -lGTMSessionFetcher -lGoogleUtilities -lProtobuf -lRCTTypeSafety -lRNCAsyncStorage -lRNDeviceInfo -lRNFirebase -lRNGestureHandler -lRNSVG -lRNScreens -lReact-Core -lReact-CoreModules -lReact-RCTActionSheet -lReact-RCTAnimation -lReact-RCTBlob -lReact-RCTImage -lReact-RCTLinking -lReact-RCTNetwork -lReact-RCTSettings -lReact-RCTText -lReact-RCTVibration -lReact-cxxreact -lReact-jsi -lReact-jsiexecutor -lReact-jsinspector -lReactCommon -lYoga -lc++ -lgRPC-C++ -lgRPC-Core -lglog -lleveldb-library -lnanopb -lreact-native-location -lsqlite3 -lstdc++ -lz -framework CoreLocation -framework Crashlytics -framework FIRAnalyticsConnector -framework Fabric -framework FirebaseAnalytics -framework FirebaseCoreDiagnostics -framework Foundation -framework GoogleAppMeasurement -framework JavaScriptCore -framework MobileCoreServices -framework SafariServices -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -weak_framework UserNotifications -ObjC -lc++ -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Intermediates.noindex/reactnativesecretapp.build/Debug-iphonesimulator/reactnativesecretapp.build/reactnativesecretapp.app-Simulated.xcent -lPods-reactnativesecretapp -Xlinker -dependency_info -Xlinker /Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Intermediates.noindex/reactnativesecretapp.build/Debug-iphonesimulator/reactnativesecretapp.build/Objects-normal/x86_64/reactnativesecretapp_dependency_info.dat -o /Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/reactnativesecretapp.app/reactnativesecretapp

ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/BoringSSL-GRPC'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/DoubleConversion'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/FBReactNativeSpec'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/FirebaseAuth'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/FirebaseCore'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/FirebaseFirestore'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/FirebaseFunctions'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/FirebaseInstanceID'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/FirebaseMessaging'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/Folly'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/GTMSessionFetcher'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/GoogleUtilities'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/Protobuf'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/RCTTypeSafety'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/RNCAsyncStorage'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/RNDeviceInfo'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/RNFirebase'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/RNGestureHandler'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/RNSVG'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/RNScreens'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-Core'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-CoreModules'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTActionSheet'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTAnimation'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTBlob'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTImage'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTLinking'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTNetwork'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTSettings'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTText'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-RCTVibration'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-cxxreact'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-jsi'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-jsiexecutor'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/React-jsinspector'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/ReactCommon'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/Yoga'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/gRPC-C++'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/gRPC-Core'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/glog'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/leveldb-library'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/nanopb'
ld: warning: directory not found for option '-L/Users/v2media/Library/Developer/Xcode/DerivedData/reactnativesecretapp-aodldwmlcpfuaffdjspidtcxpndq/Build/Products/Debug-iphonesimulator/react-native-location'
ld: library not found for -lBoringSSL-GRPC
clang: error: linker command failed with exit code 1 (use -v to see invocation)

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'reactnativesecretapp' do
  
  # Pods for reactnativesecretapp
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/Firestore', '~> 6.3.0'
  pod 'Firebase/Functions', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  
  target 'reactnativesecretappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'reactnativesecretapp-tvOS' do
  # Pods for reactnativesecretapp-tvOS

  target 'reactnativesecretapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

#### `AppDelegate.m`:

```objc
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>
#import "RNFirebaseNotifications.h"
#import "RNFirebaseMessaging.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  [RNFirebaseNotifications configure];
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"reactnativesecretapp"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [[RNFirebaseNotifications instance] didReceiveLocalNotification:notification];
}
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
                                                       fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
  [[RNFirebaseMessaging instance] didRegisterUserNotificationSettings:notificationSettings];
}
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 119.09 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
you don't say what react-native-firebase you are using? I will guess v5 based on state of AppDelegate.m - I would upgrade to react-native-firebase v5.5.6 and pods 6.13.0, pod repo update, pod install and `npx react-native-clean-project clean-project-auto` and re-try?

**Comment by mikehardy** [comment]
the implication is this is project-specific. There is nothing wrong the module, this is a request for support on a project-specific problem and I don't reproduce it locally or from clean repos unfortunately

**Comment by v2media** [comment]
> you don't say what react-native-firebase you are using? I will guess v5 based on state of AppDelegate.m - I would upgrade to react-native-firebase v5.5.6 and pods 6.13.0, pod repo update, pod install and `npx react-native-clean-project clean-project-auto` and re-try?

Thanks for your reply

yes, i'm using react-native-firebase v5.5.6
if i'm remove Firebase/Firestore, it working.

run by your command it error event i'm run-ios, previous run-ios is working, just error when i build on xCode

**Comment by mikehardy** [comment]
How strange. There is clearly something wrong, but what it is it? All I can point to (even though it is the start of a bit of work) is that this script https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh can go from "create a fresh empty react-native project" to "now integrate react-native-firebase v5" and it seems to work? Something about the difference between the Podfile/ios-config from that script and your project is the problem. What is it?

**Comment by v2media** [comment]
@mikehardy 
i don't know, if i build with .xcworkspace files working fine, but if build with .xcodeproj it showing error.

**Comment by mikehardy** [comment]
Welcome to cocoapods, always use workspace. Never project

**Comment by MujtabaFR** [comment]
I had similar issue after upgrading to RN 0.64.0

`ld: library not found for -lBoringSSL-GRPC`

The problem was In **LIBRARY_SEARCH_PATHS** (Project -> Build Settings -> LIBRARY_SEARCH_PATHS) I had this
```
"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)",
"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)",
"$(inherited)"
```

**Removing the quotes** solved the issue
```
$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME),
$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME),
$(inherited)
```
