### ISSUE TITLE
iOS cannot install pod when using use_framework! for v6.x.x

### ISSUE THREAD

**Issue by EzlyJohnnie** [invertase/react-native-firebase#2967]
## Issue

iOS cannot install pod when using use_framework! for v6.x.x

---

## Environment
<p>

**`pod install` output:**

```
 [!] The 'XXXX' target has transitive dependencies that include statically linked binaries: (FirebaseCore, FirebaseCoreDiagnostics, GoogleDataTransportCCTSupport, GoogleDataTransport, FirebaseInstanceID, and FirebaseDynamicLinks)
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both

**Comment by Aurelienlajoinie** [comment]
You have to add 
```
  pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end
```

**Comment by gran33** [comment]
@Aurelienlajoinie that's a workaround that working if you're lucky and any other Pods aren't needed that `verify_no_static_framework_transitive_dependencies`.

Basically it's wrong to effect other dependencies since RNFB force to eliminate that.

Need a better solution here.

Until then, I'm downgrading to v5 😞

**Comment by WeslleyNasRocha** [comment]
I'm having the same issue, downgrading to v5 until then

**Comment by wddwycc** [comment]
Same issue here, downgrade to v5

**Comment by WeslleyNasRocha** [comment]
It's still happening

**Comment by mikehardy** [comment]
Hey @WeslleyNasRocha check out #3253 - it might be interesting for you?
