### ISSUE TITLE
Multiple environements support within RNFirebase

### ISSUE THREAD

**Issue by ScreamZ** [invertase/react-native-firebase#2970]
Hello guys,

I guess it might be cool to add such paragraph to the documentation, it's a pretty common use case and we could help people deal with it, it can be nice.

# Handling multiples Environnement in RN Firebase

For the purpose of the example we are going to use the `dev/staging` environment and the `production` environment.

**For that I need two 🔥 Firebase Apps** and I get 2 GoogleServices-Info.plist and same for Android.

Firebase has a nice topic on how to deal with that, my question is **how this applies to RN Firebase https://firebase.google.com/docs/projects/multiprojects.**

It's best if we use the default configuration instead of the runtime one, for the issue reported with analytics which can lead to strange results.

## In android
It doesn't look too complicated, leveraging [Build Variants](https://developer.android.com/studio/build/build-variants.html). Nothing special seems related to RNFirebase as we use the default config file and delegate the good file choice to gradle at build.

## In IOS

If two targets, it seems not so complicated.

But if one target, they ask to do so:

```swift
// Load a named file.
let filePath = Bundle.main.path(forResource: "MyGoogleService", ofType: "plist")
guard let fileopts = FirebaseOptions(contentsOfFile: filePath!)
  else { assert(false, "Couldn't load config file") }
FirebaseApp.configure(options: fileopts)
```

But `Warning: This approach can impact Analytics collection in some circumstances, see the reliable analytics section.`

I guess it's best to use two targets on IOS, but in case we have one, should we rely on swift or JS api?

Thanks,
Andréas

**Comment by mikehardy** [comment]
I use 4 environments (separate firebase apps on backend) and for ios they are schemes with plists assigned membership in each scheme. Android I use applicationidsuffix and variants yes

**Comment by ScreamZ** [comment]
@mikehardy Do you have a in depth example / tutorial for IOS + scheme, the only one I found where about a custom build phase which copy depending on the scheme ?

**Comment by mikehardy** [comment]
No, I am an xcode newbie but I read about schemes and they seem to fit. I made Info-Dev.plist and so on, then there is a way in xcode to select or deselect whether a file is included in a scheme. I included the right one in each scheme, I have fastlane build the right scheme based on a custom command line argument and it works
