### ISSUE TITLE
How can I setup signInWithEmailLink() for Sign Up(creating and registering a user) and Sign In in react-native??

### ISSUE THREAD

**Issue by yash1511** [invertase/react-native-firebase#2971]
## Documentation Feedback
I am using react-native-firebase v6. I was going through its docs but I couldn’t find a good explanation for it or some examples.

I’m confused whether we have to do the iOS and Android setup or just JavaScript setup??

If you could elaborate yourself on how to do it successfully or point to some tutorial then that would be great

Thank you.

---

**Comment by yash1511** [comment]
Just a follow up, please help me with this.

I can't figure do we have to the Objective C and Java setup??

**Comment by mikehardy** [comment]
The docs are clear there is just less to do than you are expecting perhaps. Add auth and app module, configure in firebase according to app module docs. Try it

**Comment by yash1511** [comment]
Okay thanks

**Comment by Salakar** [comment]
The quick start for Auth covers most things; https://invertase.io/oss/react-native-firebase/v6/auth/quick-start

If you need specific examples; the official Firebase documentation for the Web SDK can also be followed as we maintain a compatible API in most places.
