### ISSUE TITLE
[!] No podspec found for `RNFirebase` in `../node_modules/react-native-firebase/ios`

### ISSUE THREAD

**Issue by kishansbs** [invertase/react-native-firebase#2972]
[!] No podspec found for `RNFirebase` in `../node_modules/react-native-firebase/ios`

 "@react-native-firebase/app": "^6.1.0",
    "@react-native-firebase/messaging": "^6.1.0",

 "react": "16.8.6",
    "react-native": "0.60.5",

**Comment by geek-ibrar** [comment]
Try

`pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'`

**Comment by rivailruiz** [comment]
Thanks @geek-ibrar !

**Comment by WilcoBreedt** [comment]
@geek-ibrar Works like charm!

**Comment by NunoObjr** [comment]
i tried pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios' but it returns
zsh: is a directory: ../node_modules/react-native-firebase/ios

**Comment by juanpestana96** [comment]
This solution doesn't work for me. This error is still appearing

`No podspec found for `RNFirebase` in `../node_modules/react-native-firebase/ios`

**Comment by mikehardy** [comment]
@juanpestana96  this script generates a fully working demo, it compiles fine on ios - something is wrong with your project's react-native + firebase integration https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by juanpestana96** [comment]
Thank you @mikehardy. I was doing something wrong on my project, after all it worked :)

**Comment by Vernika4** [comment]
> Try
> 
> `pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'`

Thank you @geek-ibrar .. It worked from me...Thank you very much...

**Comment by mikehardy** [comment]
That may work around whatever the root cause is, but it is an anti-pattern. There is no reason to do that if auto-linking is working correctly and your packages are current, that I know of. We have no reproduction of how to create the problem though, so root cause for your project is unknown

**Comment by Kajal0823** [comment]
> Try
> 
> `pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'`
