### ISSUE TITLE
Authentication failed error on getToken not working only in one android device

### ISSUE THREAD

**Issue by rmamtaventures** [invertase/react-native-firebase#2976]
async checkPermission() {
    const enabled = await firebase.messaging().hasPermission();
    if (enabled) {
      this.getToken();
    } else {
      this.requestPermission();
    }
  }

getToken = () => {
    firebase.messaging().getToken()
      .then(fcmToken => {
        if (fcmToken) {
          AsyncStorage.setItem('fcmToken', fcmToken);
        } else {
          // user doesn't have a device token yet
          firebase.messaging().requestPermission()
        }
      })
     .catch(error => console.log(error)); 
  }

In catch block i'm getting this **error only in one device OPPO A7**:- 

rootNavigator.js:97 Error: AUTHENTICATION_FAILED
   at createErrorFromErrorData (NativeModules.js:152)
   at NativeModules.js:104
   at MessageQueue.__invokeCallback (MessageQueue.js:442)
   at MessageQueue.js:127
   at MessageQueue.__guard (MessageQueue.js:343)
   at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
   at debuggerWorker.js:80

**Comment by Flouwrian** [comment]
i have the same issue. app works fine on every device besides my private android 9 tablet from a real cheap company

**Comment by smismailalam** [comment]
i am also facing this issue in huawei nova 7i
