### ISSUE TITLE
DynamicLinkIOSParameters Documentation

### ISSUE THREAD

**Issue by adteague** [invertase/react-native-firebase#2978]
## Documentation Feedback

Hi, I am looking to use DynamicLinks but am having trouble with the app being launched on my iOS simulator via the link. Instead I always get the fallback URL.

I found the following code snippet, but am not sure if it is relevant still.
```
const linkParams = firebase.dynamicLinks().newDynamicLinkParameters('https://invertase.io', 'https://xyz.page.link');
linkParams
  .ios.setBundleId('io.invertase.testing')
  .ios.setAppStoreId('123456789')
  .ios.setMinimumVersion('18');
```

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by adteague** [comment]
Here's the link creation part that I'm not sure where I've gone wrong:

```
    const link = await dynamicLinks().buildShortLink({
      domainUriPrefix: 'https://honeyandhome.co/recipe',
      link: `https://honeyandhome.co/recipe/${recipe.id}`,
      android: {
        fallbackUrl: 'https://www.honeyandhome.com/download',
        packageName: 'com.honeyandhome.shopping',
        minimumVersion: '1.3.1',
      },
      ios: {
        fallbackUrl: 'https://www.honeyandhome.com/download',
        bundleId: 'com.honeyandhome.shopping',
        appStoreId: 'XXXXXXXXXX', // omitted on purpose
        minimumVersion: '1.3.1',
      },
      analytics: {
        campaign: 'Recipe Share',
        content: recipe.name,
        medium: Platform.isPad ? 'Tablet' : 'Mobile',
        source: Platform.OS,
      },
      navigation: {
        forcedRedirectEnabled: true,
      },
      social: {
        descriptionText:
          recipe.description || 'Check out this recipe via Honey & Home!',
        imageUrl: recipe.feature_image,
        title: recipe.name,
      },
    });
```

**Comment by adteague** [comment]
@salakar @mikehardy @ammichael Do you have any thoughts on where I’m making a mistake?

**Comment by mikehardy** [comment]
Sorry @adteague I haven't implemented dynamic links in my app yet - that feature was postponed until January in our product roadmap - so I don't have enough experience to say

**Comment by ammichael** [comment]
I ended up using React Native default [Linking](https://facebook.github.io/react-native/docs/linking) lib. I couldn't manage to get Dynamic Link to receive the event, much less the params.
