### ISSUE TITLE
[v6] https://invertase.io/oss/react-native-firebase/v6/notifications/ goes nowhere

### ISSUE THREAD

**Issue by GuillotJessica** [invertase/react-native-firebase#2984]
## Documentation Feedback

after clicking on the left side menu `https://invertase.io/oss/react-native-firebase/` Cloud Messaging 
you get on` https://invertase.io/oss/react-native-firebase/v6/messaging` and 
click on `notifications` link url changes to `https://invertase.io/oss/react-native-firebase/v6/notifications/`
 it gets me nowhere

---

react-native-firebase is great

**Comment by mikehardy** [comment]
Hi there! Notifications for v6 will in the end not exist - but there are many options, see pinned issue at top of repo: #2566

**Comment by mikehardy** [comment]
Although actually, having a dangling link is a real deal bug :grimacing:

**Comment by GuillotJessica** [comment]
@mikehardy maybe you can provide the url meanwhile

**Comment by mikehardy** [comment]
I would but there is none :grimacing: - It would point to https://notifee.app for the future, or for the alternatives, as listed in the issue (with 'react-native-push-notification' being the 3rd party module with reported success from react-native-firebase v6 users currently)

**Comment by denisk20** [comment]
notifee.app seems to be dead -- last commit was made almost 2 months ago. What's the official state of it?

**Comment by Ehesp** [comment]
Check the branches/release issue.. it's very much not dead.
