### ISSUE TITLE
Improve Remote config parsing

### ISSUE THREAD

**Issue by ScreamZ** [invertase/react-native-firebase#2986]
Hello everyone,

Ping @Salakar

I'm currently highly relying on RNFirebase, I really love it and I would be very happy to contribute sometimes.

However, I'm having a hard time trying to develop and make a pull request with current documentation of the stack 😅, even in v6 and I'm not sure how to test what I will code. So I would like to share a design pattern you could maybe think about.

# My suggestion

I currently built in my own internal project template a pattern that I'm using to fetch remote config and handle default value. This pattern allows to:

- Decoding/unserializing remote config, to get correctly typed JSON object with the config
- Ensure default shipped config, that respect also the types.
- Easily inject remote config in the application tree, using hook

This will also be part of an article that I'm currently writing, we could add it to the documentation if you think this is not a thing that should be part of the core.

Here is the full code separated into two files but this could be in one…

**modules/firebase/remote-config/config.ts**
```ts
// Remote config is defined here, add a new key when needed.
export interface RemoteConfig {
  someRemoteKey: string;
}

// Default configuration for the remote config
export const DEFAULT_REMOTE_CONFIG: RemoteConfig = {
  someRemoteKey: "Hello World",
};
```

**modules/firebase/remote-config/hooks/useRemoteConfig.ts**
```ts
import remoteConfig from "@react-native-firebase/remote-config";
import { useState, useEffect } from "react";
import { mapValues } from "lodash-es";
import to from "await-to-js";
import { RemoteConfig, DEFAULT_REMOTE_CONFIG } from "../config";

// Transform object type to match network content: which means serialized (only string, boolean, number are returned from network)
const DEFAULT_VALUE_STRINGIFIED: Record<keyof RemoteConfig, string | boolean | number> = mapValues(DEFAULT_REMOTE_CONFIG, val =>
  typeof val === "object" ? JSON.stringify(val) : val,
);

export function useRemoteConfig() {
  const [config, setRemoteConfig] = useState<RemoteConfig | undefined>();

  useEffect(() => {
    async function getConfig() {
      // Set defaults and config
      await Promise.all([
        remoteConfig().setDefaults(DEFAULT_VALUE_STRINGIFIED),
        remoteConfig().setConfigSettings({
          isDeveloperModeEnabled: __DEV__,
        }),
      ]);

      // Get latest config
      const [activationError] = await to(remoteConfig().fetchAndActivate());

      // In case of first launch error
      if (activationError) {
        setRemoteConfig(DEFAULT_REMOTE_CONFIG);
        return;
      }

      // Transform incomming data from remote config. Can be number, boolean or string.
      const extractedData = mapValues(remoteConfig().getAll(), (snapshot: any) => {
        // If remote data is a string: it can be string, object or array once unserialized
        try {
          // Unserialize it
          return JSON.parse(snapshot.value);
        } catch (error) {
          // If crashing, return as it.
          return snapshot.value;
        }
      }) as RemoteConfig;

      setRemoteConfig(extractedData);
    }

    getConfig();
  }, []);

  return config;
}
```

This is presented as a React hook, but it's about default config, serialized and unserialized using `JSON.parse` and `JSON.stringify`.

That way the data you get from firebase is instantly converted to a Javascript object with proper types, depending on the data type, thanks to `JSON.parse`. I tested for all JS types and it works using the `try/catch`.

What do you think about that? Maybe we could implement it natively?
I'm not sure where to put that inside the module?

Regards,
Andréas

PS: Can't wait for notifee :D

**Comment by mikehardy** [comment]
My problems currently with patching on v6 are just the inherent difficulty of working with a monorepo that has build steps. To be clear: I like monorepos with build steps, but yes it is difficult to make a patch and test it (and then depend on it while waiting for a PR merge) locally isn't it? Or maybe there is a very easy way and I am just missing it, at which point I'd love a guide for that.

I believe the current way is to work on the "tests" app that lives inside the repo and develop e2e tests that exercise your feature: https://github.com/invertase/react-native-firebase/blob/master/tests/README.md

**Comment by mikehardy** [comment]
And hello by the way :-) :wave:

**Comment by ScreamZ** [comment]
Alright @mikehardy, I could give a try but are you interest in such a feature? Otherwise, there is no point having hard time pop in stack ahah

@Salakar, Also what do you think of that? Also as core contributor, what is the best way to test new development from your point of view?

**Comment by mikehardy** [comment]
I make no decisions here - I don't have enough experience in the domain (remote config etc) to have good taste with regard to decisions anyway. @Salakar or @Ehesp would be the voice here, for me.

**Comment by LuisRodriguezLD** [comment]
If I may add something, the parsing was great in v5. The issue started on v6
