### ISSUE TITLE
Can not setBadge when app is in background (IOS)

### ISSUE THREAD

**Issue by duyenhang2019** [invertase/react-native-firebase#2988]
When ios App is in foreground, it's work.
But when app is in background, I can not set badge number for app icon.
firebase.messaging().onMessage(async (message) => {
firebase.notifications().setBadge(1)
}

**Comment by panvourtsis** [comment]
same here !

**Comment by Ehesp** [comment]
See the `setBackgroundMessageHandler` api, `onMessage` only works in foreground.
