### ISSUE TITLE
Build error: no known class method for selector 'credentialWithProviderID:IDToken:rawNonce:'

### ISSUE THREAD

**Issue by zvs001** [invertase/react-native-firebase#2993]
Maybe You already found it, but...

When I updated to `react-native-firebase@5.6.0`, I started get build errors.
I fixed issue by downgrading to version `5.5.7`

Xcode 11.2.1 (New build system)

Error screen:
![Screen Shot 2019-12-11 at 12 20 44 PM](https://user-images.githubusercontent.com/25595191/70613412-407a4c80-1c11-11ea-8d53-baffd5e7fc59.png)

**Comment by mikehardy** [comment]
1) follow the template
2) just published and you are not following the compatibility matrix - read carefully, use correct pod versions: https://rnfirebase.io/docs/v5.x.x/getting-started#Supported-versions---React-Native-/-Firebase - 6.13.0+
