### ISSUE TITLE
No known class method for selector 'credentialWithProviderID:IDToken:rawNonce

### ISSUE THREAD

**Issue by anoopileaf** [invertase/react-native-firebase#2998]
After integrating Firebase Authentication i am unable to run the app on ios

<img width="298" alt="Screenshot 2019-12-12 at 6 03 26 PM" src="https://user-images.githubusercontent.com/23351560/70712426-ca0d4580-1d09-11ea-8ebb-e7500a44b37e.png">

<img width="1118" alt="Screenshot 2019-12-12 at 6 04 29 PM" src="https://user-images.githubusercontent.com/23351560/70712497-eb6e3180-1d09-11ea-8f45-d9864b8d6cab.png">

**Comment by mikehardy** [comment]
You skipped the template.
Your pods are out of date. Use 6.13.0

**Comment by AndrewMorsillo** [comment]
FYI the docs are out of date. The v5.x.x docs say to use `pod 'Firebase/Auth', '~> 6.3.0'`

https://rnfirebase.io/docs/v5.x.x/auth/ios

**Comment by mikehardy** [comment]
The versions move quickly and I was busy implementing the apple sign-in vs updating all the docs - but you can help, there's an edit button top-right of every page on the docs site

**Comment by mikehardy** [comment]
compatibility matrix says 6.13+ at least, so it's in one spot but not everywhere

**Comment by gurayyarar** [comment]
@mikehardy thanks, it's working when changed with 6.13.0

**Official Documentation Page Link:**
https://v5.rnfirebase.io/docs/v5.x.x/auth/ios

**Comment by MhamedRamadan10** [comment]
if you will not use apple as sign-in method you can easily comment this condition
in `RNFirebaseAuth.m` file where error occurred
  
`
//  else if ([provider compare:@"apple.com" options:NSCaseInsensitiveSearch] == NSOrderedSame) {
//    credential = [FIROAuthProvider credentialWithProviderID:@"apple.com" IDToken:authToken rawNonce:authTokenSecret];
//  }
`

**Comment by mikehardy** [comment]
@MhamedRamadan10 if you are on a firebase-ios-sdk version so old it does not have that method, you are most likely not compatible with ios14 and may not even be compatible with ios13. You should update.

**Comment by Jeyoung-Park** [comment]
in my case, I just remove pod and reinstall it.

`pod deintegrate`
`pod install`
