### ISSUE TITLE
Re-authenticate with phone Number

### ISSUE THREAD

**Issue by MamyChow** [invertase/react-native-firebase#2999]
Hi,
I would like to delete user, but documentation says that we have to re-authenticate user if we want to delete. 
Is there a solution to re-authenticate users that are authenticate with phone number ?
Thank you.

**Comment by mikehardy** [comment]
you skipped the template, no idea what versions you're using
should be like https://rnfirebase.io/docs/v5.x.x/auth/reference/auth#signInWithPhoneNumber I think?

**Comment by mikehardy** [comment]
Incidentally - you can try first and just catch the expired token error, only asking to reauthenticate when absolutely necessary (since it irritates the user)

**Comment by MamyChow** [comment]
Sorry, i'm using the v6.0.0. If it's not possible to re-authenticate, i'll call a cloud function maybe
