### ISSUE TITLE
Documentation Overhaul

### ISSUE THREAD

**Issue by Ehesp** [invertase/react-native-firebase#3]
Documentation needs simplifying across all areas. 

- Only the differences from the web SDK need to be mentioned in the docs. 
- Examples/best practices should be moved out into their own area.
- Setup for iOS & Android is out-dated.
- Contributing guidelines

**Comment by Salakar** [comment]
Contributing guides and test app guides need doing also

**Comment by jeveloper** [comment]
By the way, there is a missing link on "Messaging" unless its meant to be marked as pending feature.

Thanks for the great work !

**Comment by Salakar** [comment]
@jeveloper thanks for the heads up, FCM/messaging is implemented for android and has the full feature set that react-native-fcm lib has, ios will follow sometime this week.

**Comment by jeveloper** [comment]
Hey 
Thanks for comment and good work.
Curious if you can just re-use rn-fcm , what would make implementing the same features better in this lib?

thanks

**Comment by Salakar** [comment]
The code in messaging is based off rn-fcm, having it internal allows more control over the features and api as well as providing an all in one solution to get started with react-native and firebase.

**Comment by jeveloper** [comment]
ahh gotcha :)

**Comment by Salakar** [comment]
@jeveloper and on that note, just finished ios messaging, so will push up and do another release shortly

**Comment by jeveloper** [comment]
You rock man !!

**Comment by SamMatthewsIsACommonName** [comment]
Hey a couple of small things I noticed on the ios installation docs, there is still a referecne to firestack on the library image:
<img width="743" alt="screen shot 2017-03-23 at 14 10 23" src="https://cloud.githubusercontent.com/assets/21329063/24249193/9ee4f3b8-0fd2-11e7-83a1-7b8c7d78bfb8.png">

Also the podfile example at the bottom of the instructions is different to the one generated by link which is of the form:
````
target 'APPLICATION_NAME' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for 'APPLICATION_NAME'
end

# RNFirebase
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/AppIndexing'
pod 'Firebase/Core'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
````
Is this as it should be? Cheers

**Comment by Salakar** [comment]
Need a new screenshot or 2 then, think there's another one somewhere.

I updated the pod template and the pod script a while back, docs not been updated to reflect, so that needs doing also

**Comment by Salakar** [comment]
@SamMatthewsIsACommonName #10 and #17 also missing from docs i believe

**Comment by SamMatthewsIsACommonName** [comment]
Amazingly I need to research how to do a pull request haha... But I just mocked this up quickly that could be used?
<img width="716" alt="screen shot 2017-03-23 at 14 17 57" src="https://cloud.githubusercontent.com/assets/21329063/24249440/9494e19c-0fd3-11e7-95c0-c2baa85092e8.png">

**Comment by Salakar** [comment]
Danke, updated images for section a and b, still need an image for c if you have one?

**Comment by SamMatthewsIsACommonName** [comment]
Oh yup will make now

**Comment by SamMatthewsIsACommonName** [comment]
<img width="856" alt="screen shot 2017-03-23 at 14 35 01" src="https://cloud.githubusercontent.com/assets/21329063/24250094/f9c4811a-0fd5-11e7-9aac-760f1ee2fd8a.png">

**Comment by Salakar** [comment]
Thanks, updated: https://github.com/invertase/react-native-firebase/blob/master/docs/installation.ios.md

**Comment by SamMatthewsIsACommonName** [comment]
Sorry that one still had my document path could you please use this one? I tried to do the old 'delete before you noticed' haha
<img width="856" alt="screen shot 2017-03-23 at 14 41 20" src="https://cloud.githubusercontent.com/assets/21329063/24250349/da91284c-0fd6-11e7-8328-6008e462039e.png">

**Comment by Salakar** [comment]
You could of been internet famous hehe, changing now

**Comment by Salakar** [comment]
cc @greena13 as you're thinking about looking into JSDocs 😸

**Comment by Salakar** [comment]
Closing this now as we've moved over to the fancier docs.
