### ISSUE TITLE
Remote notifications are not displayed on ios device, firebase.notifications().onNotification is not getting triggered , instead  firebase.messaging().onMessage is triggered !

### ISSUE THREAD

**Issue by intruder09** [invertase/react-native-firebase#3002]
"react-native": "0.60.5",
"@react-native-firebase/app": "^6.0.4",
"@react-native-firebase/messaging": "^6.0.4", 
"react-native-firebase": "^5.5.6",

#1 AppDelegate.m (only firebase code)

  [FIRApp configure];

  [FIRMessaging messaging].delegate = self;

  if ([UNUserNotificationCenter class] != nil) {
   
    [UNUserNotificationCenter currentNotificationCenter].delegate = self;
    UNAuthorizationOptions authOptions = UNAuthorizationOptionAlert |
        UNAuthorizationOptionSound | UNAuthorizationOptionBadge;
    [[UNUserNotificationCenter currentNotificationCenter]
        requestAuthorizationWithOptions:authOptions
        completionHandler:^(BOOL granted, NSError * _Nullable error) {
          // ...
        }];
  } else {
  
    UIUserNotificationType allNotificationTypes =
    (UIUserNotificationTypeSound | UIUserNotificationTypeAlert | UIUserNotificationTypeBadge);
    UIUserNotificationSettings *settings =
    [UIUserNotificationSettings settingsForTypes:allNotificationTypes categories:nil];
    [application registerUserNotificationSettings:settings];
  }

  [application registerForRemoteNotifications];

#2 react-native code (only firebase code)

import firebase from 'react-native-firebase';

 componentDidMount(){

  
  this.checkPermission();

  firebase.messaging().onMessage((message) => {
    Alert.alert(message)
  })
  

  firebase.notifications().onNotification((notification) => {
    const { title, body } = notification;
    this.showAlert(title, body);
  });

}

async checkPermission() {
    const enabled = await firebase.messaging().hasPermission();
    if (enabled) {
      //firebase.messaging().registerForNotifications()
        Alert.alert('has premisson')
        this.getToken();

    } else {
      Alert.alert('no premisson')

        this.requestPermission();
    }
  }

async requestPermission() {
    try {
        await firebase.messaging().requestPermission();
        Alert.alert('user did give p')
       this.getToken();
    } catch (error) {
        // User has rejected permissions
        Alert.alert('user did not give p')
        console.log('permission rejected');
    }
  }

Please help ASAP! 
any input would be much appreciated .(tried and followed almost all other threads nothing seems to work)

**Comment by GioLogist** [comment]
This might help https://github.com/invertase/react-native-firebase/issues/2566#issuecomment-541109278

**Comment by finpeg123** [comment]
@GioLogist Thanks .. It looks like notifications are not supported in latest version. I should switch to v5.
