### ISSUE TITLE
Firebase Remote Config param not going immediately to iOS app

### ISSUE THREAD

**Issue by felipeaugusto1** [invertase/react-native-firebase#3003]
🔥

## Issue

I'm using Firebase Remote Config and it works great. However, the updated values (from firebase console) are not going instantaneously to the app.

This is the code I'm using:

```
firebase
      .config()
      .fetch(30 * 60) // 30 min
      .then(() => {
        return firebase.config().activateFetched();
      })
      .then(() => {
        return firebase.config().getValue('MY_VALUE');
      })
      .then(snapshot => {
        const myValye = snapshot.val();
      })
      .catch(
        console.log('error')
      );
```

When I run this code and I update the value on firebase, the app has to wait the 30 min set in the fetch function. I thought it would be available immediately?

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
```
"react": "16.8.6",
"react-native": "0.60.3",
"react-native-firebase": "^4.3.8",
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
pod 'Firebase/Core', '~> 5.14.0'
pod 'Firebase/RemoteConfig', '~> 5.14.0'
```
</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 65.38 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.2 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 17, 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 21.1.2, 22.0.1, 23.0.1, 25.0.0, 25.0.3, 26.0.1, 26.0.2, 27.0.2, 27.0.3, 28.0.2, 28.0.3
      System Images: android-17 | Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^4.3.8`
- **`Firebase` module(s) you're using that has the issue:**
  - `Firebase Remote Config`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

**Comment by damasofc** [comment]
did you find a solution? @felipeaugusto1 I've this same issue, but in my case I put the variable ''minimumFetchIntervalMillis" to 0 so when I make a change on remoteConfig it would updated the value immediately the next time I re-open the app.

The issue is happening to me only on IOS, on Android it works as expected.

**Comment by felipeaugusto1** [comment]
@damasofc I ended up doing my own cache system, so I only request the remote config params when something got changed

**Comment by ddikodroid** [comment]
> @damasofc I ended up doing my own cache system, so I only request the remote config params when something got changed

how did you implement it?
