### ISSUE TITLE
Not getting _data object in onNotificationOpened during foreground

### ISSUE THREAD

**Issue by Murugeshrockey-RN** [invertase/react-native-firebase#3005]
Platform: Android and IOS

Lib Package Version:    "react-native-firebase": "^5.5.6",

React Native Version:    "react-native": "0.60.5",
**CODE:**
this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
    console.log('output',notificationOpen)
    });
Here the input send from backend side.

URL:https://fcm.googleapis.com/fcm/send
Input: {
  "to":"c9kHZZSbReU:APA91bHafZuEi7JrDFM5WrGUHLl4MPrbBd6T_XwauMz5ff-cGViOfrJ8AYSn_pgOh-01-F56Nc0qxlfXZwsS5chZo7uBVOdNM8_g9i1S_f8Nr0XI-Iv6t0oN0LvrkPVRfruXwOm7LstE",
     "data" : { 
    "body" : "Welcome to Zark",
     "title": "Zark Gaming",
"target_screen":"notification"
 },
   "notification" : {
     "body" : "Welcome to Zark",
     "title": "Zark Gaming"
 }
}

Getting payload data on onNotificationOpened when tap the notification when app is from background but not getting payload data when tap the notification  from foreground. So I can't able pass the data or setting target_screen during foreground.

**Comment by mikehardy** [comment]
I suspect something like this: https://github.com/crazycodeboy/react-native-splash-screen/issues/289#issuecomment-502406454

You skipped the template though, so not all the information we'd need is present

**Comment by Murugeshrockey-RN** [comment]
Bu I got data payload when the app is background. my problem is i can't get payload data when I tap the notification during foreground and it happens in both android and ios.

**Comment by mikehardy** [comment]
If only you'd followed the template, we could maybe see what was going on...

(note: you can always open a new issue, carefully following the template...)
