### ISSUE TITLE
Not getting _data object in onNotificationOpened during foreground

### ISSUE THREAD

**Issue by Murugeshrockey-RN** [invertase/react-native-firebase#3006]
## Issue

Describe your issue here

Getting payload data on onNotificationOpened when tap the notification when app is from background but not getting payload data when tap the notification from foreground. So I can't able pass the data or setting target_screen during foreground.

CODE:
```javascript
this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
console.log('output',notificationOpen)
 var target_screen = notificationOpen.notification._data;
      if (target_screen.target_screen == 'notification') {
          this.props.navigation.navigate('Notification');
} else if (target_screen.target_screen == 'dashboard') {
          this.props.navigation.navigate('Home');
 } else if (target_screen.target_screen == 'single_challenge') {
          //alert(foregroundnotificationdata.target_screen)
          this.props.navigation.push('ChallangeDetails', { pushnotification: true, item: target_screen });
} else if (target_screen.target_screen == 'profile') {
          this.props.navigation.navigate('ProfilePage');
     } else if (target_screen.target_screen == 'leaderboard') {
          this.props.navigation.navigate('Global');
    } else if (target_screen.target_screen == 'create_challenge') {
          this.props.navigation.navigate('CreateChallenge', { pushnotification: true, item: target_screen });
    }
        else if (target_screen.target_screen == 'friend_request') {
          this.props.navigation.navigate('FriendsProfilePage', { friendId: target_screen.page_id });
   }
});
```
Here the input send from backend side.

URL:https://fcm.googleapis.com/fcm/send
Input:
```json {
"to":"c9kHZZSbReU:APA91bHafZuEi7JrDFM5WrGUHLl4MPrbBd6T_XwauMz5ff-cGViOfrJ8AYSn_pgOh-01-F56Nc0qxlfXZwsS5chZo7uBVOdNM8_g9i1S_f8Nr0XI-Iv6t0oN0LvrkPVRfruXwOm7LstE",
"data" : {
"body" : "Welcome to Zark",
"title": "Zark Gaming",
"target_screen":"notification",
"page_id":"786"
},
"notification" : {
"body" : "Welcome to Zark",
"title": "Zark Gaming"
}
}
```

## Project Files

IOS
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

classpath 'com.google.gms:google-services:4.3.2'
Android
```xml
<!--        - Android: `android/app/build.gradle` contents. -->
implementation "com.google.android.gms:play-services-base:16.1.0"
   implementation "com.google.firebase:firebase-core:17.0.1"
   implementation "com.google.firebase:firebase-messaging:19.0.1"
apply plugin: 'com.google.gms.google-services'

<!--        - Android: `AndroidManifest.xml` contents. -->
     <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />

     <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
       <intent-filter>
         <action android:name="com.google.firebase.MESSAGING_EVENT" />
       </intent-filter>
     </service>
     <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
    <intent-filter>
      <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
    </intent-filter>
  </service>
       <receiver android:name="com.appsflyer.MultipleInstallBroadcastReceiver" android:exported="true">
           <intent-filter>
               <action android:name="com.android.vending.INSTALL_REFERRER" />
           </intent-filter>
       </receiver>
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon"

            android:resource="@mipmap/ic_launcher" />
            <meta-data
        android:name="com.google.firebase.messaging.default_notification_color"
        android:resource="@color/colorPrimary" />
```

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
    "react-native": "0.60.5",
    "react": "16.8.6",

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:
```objc
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [[RNFirebaseNotifications instance] didReceiveLocalNotification:notification];
}
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}
- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
  [[RNFirebaseMessaging instance] didRegisterUserNotificationSettings:notificationSettings];
}
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:
  packages.add(new RNFirebaseMessagingPackage());
     packages.add(new RNFirebaseNotificationsPackage());
```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
    "react-native-firebase": "^5.5.6",

  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  Android and IOS
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Well, it almost followed the template. So, it almost had the info we needed. 🤷‍♂ 

I fixed up the formatting at least (check the source so you can learn the triple-backtick formatting tricks in github markdown - super useful) on the stuff you did post so I could read it

Might be missing singleTop on android https://rnfirebase.io/docs/v5.x.x/notifications/android#Update-Android-Manifest

Might be missing RNFirebaseNotifications configure in AppDelegate but it's incomplete so who knows? https://rnfirebase.io/docs/v5.x.x/notifications/ios#Update-%3Ccode%3EAppDelegate.m%3C/code%3E

**Comment by N3TC4T** [comment]
I have the same problem, opening notification when the app is in background (**getInitialNotification**) will contain the **data**  but opening notification when the app is on foreground which is handled by **onNotificationOpened** will not pass the data and **data** will be empty.

**Comment by yarikpwnzer** [comment]
Experiencing same issue:
onNotification everything is OK:
["{\"_body\":\"Hooh oh oh oh oh \",\"_data\":{\"invitiation_id\":\"15967\",\"title\":\"Ug ih i needs your support now\",\"kind\":\"join_invite\",\"id\":\"9992\"},\"_notificationId\":\"0:1579690736233844%be7b3382be7b3382\",\"_sound\":\"default\",\"_title\":\"Ug ih i needs your support now\",\"_android\":{\"_actions\":[],\"_people\":[],\"_smallIcon\":{\"icon\":\"ic_launcher\"}},\"_ios\":{\"_attachments\":[]}}"]

onNotificationOpened, receiving different notifcation id and data object is empty:
["{\"_body\":\"Hooh oh oh oh oh \",\"_data\":{},\"_notificationId\":\"-LzBtvkE5wtWLJFRJKri\",\"_sound\":\"default\",\"_title\":\"Ug ih i needs your support now\",\"_android\":{\"_actions\":[],\"_channelId\":\"default\",\"_people\":[],\"_smallIcon\":{\"icon\":\"ic_launcher\"}},\"_ios\":{\"_attachments\":[]}}"]

**Comment by mikehardy** [comment]
@yarikpwnzer out of curiosity, can you post your AndroidManifest.xml? There was problem with Intent handling and data passing with certain integrations (for example https://github.com/crazycodeboy/react-native-splash-screen/issues/289#issuecomment-502406454 ) and I'm curious if that interaction (or  a similar one) is responsible for this problem

**Comment by yarikpwnzer** [comment]
@mikehardy
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools"
  package="com.xxx">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="com.android.vending.BILLING" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <application
        android:name=".MainApplication"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:allowBackup="false"
        android:theme="@style/AppTheme"
        tools:replace="android:allowBackup"
        >
        <meta-data android:name="com.mixpanel.android.MPConfig.AutoShowMixpanelUpdates" android:value="false" />
        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_notification" />
        <meta-data android:name="com.mixpanel.android.MPConfig.ResourcePackageName" android:value="com.xxx.xxx" />
        <meta-data android:name="com.mixpanel.android.MPConfig.NotificationChannelId" android:value="default"/>
        <meta-data android:name="com.mixpanel.android.MPConfig.NotificationChannelName" android:value="XXX Channel"/>
        <meta-data android:name="com.mixpanel.android.MPConfig.NotificationChannelImportance" android:value="4" />
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:screenOrientation="portrait"
            android:launchMode="singleTask"
            android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="XXX">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="xxx"/>
            </intent-filter>
        </activity>
        <activity
            android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
            android:theme="@style/BootTheme"> <!-- apply the theme you created at step 3. -->
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="com.mixpanel.android.takeoverinapp.TakeoverInAppActivity" android:theme="@style/com_mixpanel_android_TakeoverInAppActivityTheme"/>
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
        <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />
        <service
            android:name=".TPFirebaseMessagingService"
            android:enabled="true"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>
        <meta-data
            android:name="io.fabric.ApiKey"
            android:value="xxx" />
    </application>

</manifest>
```

**Comment by mikehardy** [comment]
@yarikpwnzer remove your RNBootSplash integration, it is configured as your LAUNCHER activity and it is likely eating the intent data c.f. the link I posted to the separate but similar splash screen library

**Comment by yarikpwnzer** [comment]
@mikehardy issue that's not reproducing every time, once per 5-10 Push Notifications, I see logs from our clients on production.
P.S. RNBootSplash seems handle everything correctly: https://github.com/zoontek/react-native-bootsplash/blob/35cdf62cf2c4cf9cee73d1a8cad457fbf8d31c68/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashActivity.java#L26

**Comment by mikehardy** [comment]
@yarikpwnzer I agree it seems RNBootSplash is better than react-native-splash-screen I've reviewed that code before. It should. You didn't mention that it was inconsistent, that's worth mentioning every time. If if it works sometimes but not all times then the modules in use are likely not the cause it is potentially some device-type or device-state type issue. Can you generalize to what kind of devices it happens on? Essentially, without a reproduction or a hard lead on root cause, what can reasonably be done?

**Comment by yarikpwnzer** [comment]
@mikehardy yeah, sorry for that. Currently we can't reproduce(me and our QA). But our team member had this issue:
Pixel 2, Android OS 10.
Seems this issue happens only on Android devices, we suspect that this issue can happen if onNotification will follow by onNotificationOpened, still trying to reproduce...
