### ISSUE TITLE
error: no known class method for selector 'credentialWithProviderID:IDToken:rawNonce:'     credential = [FIROAuthProvider credentialWithProviderID:@"apple.com" IDToken:authToken rawNonce:authTokenSecret];

### ISSUE THREAD

**Issue by jimallen** [invertase/react-native-firebase#3007]
## Issue

error: no known class method for selector 'credentialWithProviderID:IDToken:rawNonce:'
File: RNFirebaseAuth..m line# 1184ish
    credential = [FIROAuthProvider credentialWithProviderID:@"apple.com" IDToken:authToken rawNonce:authTokenSecret];

Caused the above mentioned build issue. 

This line seems to be the culprit in v 5.5.6 

Describe your issue here

---

## Project Files

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'gbtesttwo' do
  # Pods for gbtesttwo
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RN-firebase-starter
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.8.1'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob', '~> 6.8.1'
  pod 'Firebase/Auth', '~> 6.8.1'
  pod 'Firebase/Database', '~> 6.8.1'
  pod 'Firebase/Functions', '~> 6.8.1'
  pod 'Firebase/DynamicLinks', '~> 6.8.1'
  pod 'Firebase/Firestore', '~> 6.8.1'
  pod 'Firebase/Messaging', '~> 6.8.1'
  pod 'Firebase/RemoteConfig', '~> 6.8.1'
  pod 'Firebase/Storage', '~> 6.8.1'
  pod 'Firebase/Performance', '~> 6.8.1'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'

  target 'gbtesttwoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!

end

target 'gbtesttwo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gbtesttwo-tvOS

  target 'gbtesttwo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "gbtesttwo",
  "version": "5.4.0",
  "private": true,
  "scripts": {
    "android-bundle": "ORG_GRADLE_PROJECT_bundleInDev=true npm run android",
    "android": "react-native run-android",
    "ios": "react-native run-ios --simulator=\"iPhone X\"",
    "apk": "cd android && ./gradlew assembleRelease",
    "rename": "node ./bin/rename.js",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "npx jetify"
  },
  "dependencies": {
    "jetifier": "^1.6.4",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-firebase": "^5.5.6"
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "@babel/runtime": "^7.6.0",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.1.0",
    "fs-extra": "^7.0.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6",
    "replace-in-file": "^3.4.4"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json

```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by jimallen** [comment]
I think the report format is a little wonky. Please let me know if you have any questions.

**Comment by mikehardy** [comment]
Check [compatibility matrix](https://rnfirebase.io/docs/v5.x.x/getting-started), and note that from v5.5 react-native-firebase will allow breaking changes in the minor

v5.6 minor release includes the breaking change that you must use pods 6.13+ - then that symbol will be defined

**Comment by jimallen** [comment]
@mikehardy - I am using the latest guide though. I don't understand how the pods could be out of date?

https://rnfirebase.io/docs/v5.x.x/installation/basic-kit#1)-Clone-&-Install-Dependencies

**Comment by mikehardy** [comment]
Simply because the starter has not been updated yet, I had forgotten about it

That's where they are coming from though: https://github.com/invertase/react-native-firebase-starter/blob/master/ios/Podfile#L34

You can do a `pod update` in your ios directory to get current. In general this is worth doing periodically as the firebase team releases maybe 1-2x/month on average

**Comment by mikehardy** [comment]
Fixed: https://github.com/invertase/react-native-firebase-starter/pull/142

**Comment by jimallen** [comment]
@mikehardy - Thanks for the quick fix. This project is super helpful. I'll see if I can pick off some low hanging issues.

**Comment by mikehardy** [comment]
Great - I think our biggest pain point right now, if you'll be in the area, is user confusion on how to handle dynamic links. People are having a real hard time getting the link data in all app states

one other thing I'll mention - while I keep the react-native-firebase v5 alive (along with this starter), if you are not using local notifications and are just starting out, I'd encourage you to start out with v6. They have a react-native CLI template that gives you a starter project too https://invertase.io/oss/react-native-firebase/quick-start/new-project#initializing-the-project. And if you are using local notifications then you can use v6 along with react-native-push-notifications.

**Comment by SirCameron** [comment]
I'm hitting this issue also. 
I ran ```pod update``` but no love.
react-native 0.59.8 (really don't want to attempt to upgrade this project)
react-native-firebasw 5.5.6

Help would be very very much appreciated. :)

**Comment by SirCameron** [comment]
I'm able to archive my project from xcode on my machine, but running it through AppCenter doesn't work.
