### ISSUE TITLE
onLink is not being triggered

### ISSUE THREAD

**Issue by gabrielbarbosanascimento** [invertase/react-native-firebase#3008]
I'm using dynamic links on my project. I can easy create and share then, but I wasn't able to receive it. It triggers the app to open, but the console.log was never called (I tried to change view as well but no sucess). The code is looking like how the documentation sugests

``` jsx
export const App = () => {
    const handleDynamicLink = (link) => {
        // Handle dynamic link inside your own application
        if (link.url) {
            console.log('works', link);
        }
    };

    useEffect(() => {
        const unsubscribe = dynamicLinks().onLink(handleDynamicLink);
        // When the component unmounts, remove the listener
        return () => unsubscribe;
    }, []);

    return (
        <Provider store={createStore(reducers, {}, applyMiddleware(ReduxThunk))}>
            <Router />
        </Provider>
    );
}
```

**Comment by mikehardy** [comment]
Please search in the repo for related issues, there are a few open regarding links at the moment with workarounds posted. Not sure what the root causes are yet, but if you found them that would be great.

In the meantime some of the other suggestions might be useful (for example: the native Linking APIs from react-native have been used by some for the inbound links)

**Comment by ilibilibom** [comment]
I'm experiencing this issue as well. 
Please update once this issue solved. 
Thanks

**Comment by russellwheatley** [comment]
Hi @gabrielbarbosanascimento, I've tested the `onLink` event listener on iOS v12.0. & Android v9.0. In both instances, a link object with the `url` property was passed into the callback function. Could you please give more details surrounding this issue?

As a side issue, you've implemented the `unsubscribe` function incorrectly. It should look like this:
```js
  useEffect(() => {
        const unsubscribe = dynamicLinks().onLink(handleDynamicLink);
        // When the component unmounts, remove the listener
        return unsubscribe;
    }, []);
```
[documentation](https://invertase.io/oss/react-native-firebase/v6/dynamic-links/reference/module#onLink)
