### ISSUE TITLE
Broken link for notifications in the docs 

### ISSUE THREAD

**Issue by yhenni1989** [invertase/react-native-firebase#3010]
## Documentation Feedback

Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation.

The link in the docs on how to set up Notifications for users is broken.

The error is located in here: https://invertase.io/oss/react-native-firebase/v6/notifications/

<img width="840" alt="Screenshot 2019-12-16 at 11 59 03" src="https://user-images.githubusercontent.com/26605247/70905355-911bec00-1ffb-11ea-967d-7096801af89c.png">

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
This is a duplicate  #2990  #2984 but @Ehesp continues to lure people in ...

**Comment by Ehesp** [comment]
https://github.com/invertase/react-native-firebase/commit/38ff48df30c08dad0c9dd55512273a1d92d3764f
