### ISSUE TITLE
No firebase app [default] has been created,  bug/fix

### ISSUE THREAD

**Issue by behrmann97** [invertase/react-native-firebase#3014]
Hello, I am just writing this issue to inform that my default app was not created automatically by RNFirebase even though I followed all the steps. This seemed to be due to it searching for an "apiKey" on my google-services.json, when the file generated by firebase actually has an "api_key". Just wanted to inform that and was not sure where to write it, hope it can help someone struggling with it :)

**Comment by mbretter** [comment]
you have to change your google services depedency to (android/build.gradle):
classpath 'com.google.gms:google-services:4.2.0'
the firebase wizzard proposes: 
classpath 'com.google.gms:google-services:4.3.2'
which does not work ...

**Comment by behrmann97** [comment]
Oh i see thanks!

**Comment by mikehardy** [comment]
You should change it to whatever current is, 4.3.3 is current and solves an important dependency resolution issue

**Comment by ramizahmed07** [comment]
> you have to change your google services depedency to (android/build.gradle):
> classpath 'com.google.gms:google-services:4.2.0'
> the firebase wizzard proposes:
> classpath 'com.google.gms:google-services:4.3.2'
> which does not work ...

I tried this but still getting that error :(
