### ISSUE TITLE
[iOS] Build target RNFBApp failed when use use_frameworks! 

### ISSUE THREAD

**Issue by hieupaul** [invertase/react-native-firebase#3024]
## Issue
Hi, I have issue when build target RNFBApp on iOS

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
      objc-class-ref in FirebaseCore(FIRBundleUtil.o)
  "_GULResetLogger", referenced from:
      _FIRResetLogger in FirebaseCore(FIRLogger.o)
  "_GULLoggerRegisterVersion", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULLoggerInitializeASL", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULLogBasic", referenced from:
      _FIRLogBasic in FirebaseCore(FIRLogger.o)
  "_GULLoggerEnableSTDERR", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULIsLoggableLevel", referenced from:
      _FIRIsLoggableLevel in FirebaseCore(FIRLogger.o)
  "_GULSetLoggerLevel", referenced from:
      _FIRSetLoggerLevel in FirebaseCore(FIRLogger.o)
  "_GULLoggerForceDebug", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**But if I remove `use_frameworks!` in Podfile then build successful.**

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "react": "16.9.0",
    "react-native": "0.61.5",
    "@react-native-firebase/analytics": "^6.2.0",
    "@react-native-firebase/app": "^6.2.0",
    "@react-native-firebase/messaging": "^6.2.0",
    "@react-native-firebase/remote-config": "^6.2.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
...
use_frameworks!
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by osdnk** [comment]
I fixed it with adding this at the end of Podfile
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['RNFBApp', 'RNFBMessaging'].include?(target.name)
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
      end
    if ['RNFBCrashlytics'].include?(target.name)
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'Fabric'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'Crashlytics'})
      end
  end
end
```
but I still face some issues regarding initialization of Firebase

**Comment by romanbarzyczakgelato** [comment]
I managed most problems by adding system_frameworks:

`  post_install do |installer_representation|

      installer_representation.pods_project.targets.each do |target|
        if ['RNFBApp', 'RNFBMessaging', 'RNFBCrashlytics', 'RNFBDatabase'].include?(target.name)
          target.add_system_framework(installer_representation.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
        elsif target.name.eql?('RNFBAnalytics')
          target.add_system_framework(installer_representation.pods_project.targets.find{|target| target.name == 'FirebaseAnalytics'})
          target.add_system_framework(installer_representation.pods_project.targets.find{|target| target.name == 'GoogleAppMeasurement'})
          target.add_system_framework(installer_representation.pods_project.targets.find{|target| target.name == 'nanopb'})
          target.add_system_framework(installer_representation.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
        end
        if ['RNFBCrashlytics'].include?(target.name)
          target.add_system_framework(installer_representation.pods_project.targets.find{|target| target.name == 'Fabric'})
          target.add_system_framework(installer_representation.pods_project.targets.find{|target| target.name == 'Crashlytics'})
          end
        if ['RNFBDatabase'].include?(target.name)
          target.add_system_framework(installer_representation.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
          target.add_system_framework(installer_representation.pods_project.targets.find{|target| target.name == 'FirebaseDatabase'})
          target.add_system_framework(installer_representation.pods_project.targets.find{|target| target.name == 'leveldb'})
          end
      end

  end`

but it doesn't work for FirebaseDatabase:

`Undefined symbols for architecture x86_64:
  "leveldb::WriteBatch::WriteBatch()", referenced from:
      -[APLevelDBWriteBatch .cxx_construct] in FirebaseDatabase(APLevelDB.o)
  "leveldb::WriteBatch::Clear()", referenced from:
      -[APLevelDBWriteBatch clear] in FirebaseDatabase(APLevelDB.o)
  "leveldb::Status::ToString() const", referenced from:
      -[APLevelDB initWithPath:error:] in FirebaseDatabase(APLevelDB.o)
  "leveldb::DB::Open(leveldb::Options const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, leveldb::DB**)", referenced from:
      -[APLevelDB initWithPath:error:] in FirebaseDatabase(APLevelDB.o)
  "leveldb::WriteBatch::Delete(leveldb::Slice const&)", referenced from:
      -[APLevelDBWriteBatch removeKey:] in FirebaseDatabase(APLevelDB.o)
  "leveldb::WriteBatch::~WriteBatch()", referenced from:
      -[APLevelDBWriteBatch .cxx_destruct] in FirebaseDatabase(APLevelDB.o)
  "leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&)", referenced from:
      -[APLevelDBWriteBatch setData:forKey:] in FirebaseDatabase(APLevelDB.o)
      -[APLevelDBWriteBatch setString:forKey:] in FirebaseDatabase(APLevelDB.o)
  "leveldb::Options::Options()", referenced from:
      +[APLevelDB defaultCreateOptions] in FirebaseDatabase(APLevelDB.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by Aurelienlajoinie** [comment]
> I fixed it with adding this at the end of Podfile
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     if ['RNFBApp', 'RNFBMessaging'].include?(target.name)
>       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
>       end
>     if ['RNFBCrashlytics'].include?(target.name)
>       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'Fabric'})
>       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'Crashlytics'})
>       end
>   end
> end
> ```
> 
> but I still face some issues regarding initialization of Firebase

Here is the same with this podfile config:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['RNFBApp', 'RNFBMessaging' ].include?(target.name)
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
    elsif ['RNFBCrashlytics'].include?(target.name)
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'Fabric'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'Crashlytics'})
    elsif target.name.eql?('RNFBAnalytics')
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'FirebaseAnalytics'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleAppMeasurement'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'nanopb'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
    elsif target.name.eql?('RNFBPerf')
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'FirebasePerformance'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'FirebaseSwizzlingUtilities'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GTMSessionFetcher'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleDataTransport'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleDataTransportCCTSupport'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleToolboxForMac'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'Protobuf'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'nanopb'})
    end
  end
end
```

IOS Native initialization in appDelegate seems to failed cause JS thread throw exception....
![Simulator Screen Shot - iPhone X - 2020-01-08 at 10 37 54](https://user-images.githubusercontent.com/27803113/71967043-f7fb8200-3202-11ea-9b28-892329e900de.png)

Android works fine

**Comment by Sly777** [comment]
Thanks a lot, @Aurelienlajoinie, it works for me!

**Comment by romanbarzyczakgelato** [comment]
Do you have any solution for `FirebaseDatabase` ?

**Comment by skullet** [comment]
I'm experiencing this error as well. I need to use Mapbox iOS SDK which requires use_frameworks!, so a work around or fix for this issue would help. To manually initialize the FirebaseDatabase do we just call initialiseApp()?

**Comment by llaine** [comment]
Getting issues with Firebase initialisation after adding the `post_install` hook.

**Comment by Aurelienlajoinie** [comment]
I manage to build my app without using the podfile postinstall script and i've no init error at launch on iOS.
I turn static_framework from podspec to true for each used package (using patch package)

Example for Analytics:

diff --git a/node_modules/@react-native-firebase/analytics/RNFBAnalytics.podspec b/node_modules/@react-native-firebase/analytics/RNFBAnalytics.podspec
index 0e09692..d865ab5 100644
--- a/node_modules/@react-native-firebase/analytics/RNFBAnalytics.podspec
+++ b/node_modules/@react-native-firebase/analytics/RNFBAnalytics.podspec
@@ -25,5 +25,5 @@ Pod::Spec.new do |s|
   s.dependency          'React'
   s.dependency          'Firebase/Core', firebase_sdk_version
   s.dependency          'RNFBApp'
-  s.static_framework    = false
+  s.static_framework    = true
 end

What does the static_framework attribute ? Is it a real solution to do that ?

Thanks in advance for your help :)

**Comment by BallardB** [comment]
Hi still having a similar issue when trying to install `react-native-firebase/analytics` 6.3.1 on RN 0.61.5. I have added that `post_install` script but have had no luck. Anyone else facing this issue??

**Comment by asafda** [comment]
> Hi still having a similar issue when trying to install `react-native-firebase/analytics` 6.3.1 on RN 0.61.5. I have added that `post_install` script but have had no luck. Anyone else facing this issue??

I had a similar issue because I use `abstract_target` for all of my schemas. My solution was to move `use_native_modules` to regular targets, so it looks like this:

```
abstract_target 'HomeisShared' do    
  // my shared dependencies go here
  
  target 'HomeisMobile' do
    use_native_modules!
  end

  target 'HomeisMobileStage' do
    use_native_modules!
  end

  target 'HomeisMobileDev' do
    use_native_modules!
  end
end  
```  

Hope this helps

**Comment by luatnd** [comment]
If you use RNFBAuth, add it like `RNFBAnalytics`:
```
elsif ['RNFBAnalytics', 'RNFBAuth'].include?(target.name)
       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'FirebaseAnalytics'})
       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleAppMeasurement'})
       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'nanopb'})
       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
```

**Comment by luatnd** [comment]
I found that this workaround can fix the issue too:
https://github.com/invertase/react-native-firebase/issues/3253#issuecomment-595022962

If it change to static_frameworks. You don't need to fix this anymore:
https://github.com/invertase/react-native-firebase/issues/3024#issuecomment-568287357

**Comment by Salakar** [comment]
v6.4.0 has been released which now has a flag to toggle using  RNFirebase as a static framework: https://rnfirebase.io/#allow-ios-static-frameworks

**Comment by rafaelmaeuer** [comment]
> I fixed it with adding this at the end of Podfile
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     if ['RNFBApp', 'RNFBMessaging'].include?(target.name)
>       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
>       end
>     if ['RNFBCrashlytics'].include?(target.name)
>       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'Fabric'})
>       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'Crashlytics'})
>       end
>   end
> end
> ```
> 
> but I still face some issues regarding initialization of Firebase

Thank you very much, I had a similar error after upgrading to react-native-firebase v15 when adding `use_frameworks!`:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRMessaging", referenced from:
      objc-class-ref in RNFBMessaging+AppDelegate.o
      objc-class-ref in RNFBMessaging+FIRMessagingDelegate.o
      objc-class-ref in RNFBMessagingModule.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It occurred very often, especially after installing pods or switching from debug to release builds. Adding the following block to post-install in podfile made the issue disappear:

```pod
installer.pods_project.targets.each do |target|
  if ['RNFBApp', 'RNFBMessaging'].include?(target.name)
    target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
  end
end
```

**Comment by rohanpanda001** [comment]
Thank you so much, it worked!!!
