### ISSUE TITLE
Realtime Database child_changed fires twice when value is set to ServerValue.TIMESTAMP

### ISSUE THREAD

**Issue by perrosnk** [invertase/react-native-firebase#3026]
## Issue

Describe your issue here
The `.on('child_added)` listener is called twice when the value is set to `ServerValue.TIMESTAMP`.

#### Steps to reproduce:
```javascript
        const updates = {};
        updates[`/user-chats/${user.id}/${chatId}`] = database.ServerValue.TIMESTAMP;
        database().ref().update(updates);

       userChatsRef.on('child_changed', (snap) => { console.log('called') })
```
I also receive different timestamp values

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by ItachiUchiha91** [comment]
Same issue here

**Comment by perrosnk** [comment]
According to [this](https://github.com/firebase/firebase-js-sdk/issues/2461) that's the intended behaviour

**Comment by DisruptLive** [comment]
if we are using `onValue` in order to listen for both types `child_added` and `child_changed` how can we check if a response was as a result of one of those events? Is there a method we can call on the resulting snapshot that will return the event type?

**Comment by mikehardy** [comment]
I think you made different listeners if the specific event type is a differentiator

**Comment by DisruptLive** [comment]
> I think you made different listeners if the specific event type is a differentiator

Well right, we can listen for events, be it onChildAdded, onChildChanged, onChildRemoved — and onValue executes for all events. It does not seem practical to me to have to setup 3 listeners in-order to know at execution which event has taken place, and thus i am wondering if there is a way to retrieve the event when `onValue` triggers. For example, with Firestore we can do this when using `onSnapshot` to listen for changes to a Firestore collection, we can then check the event type while looping through the results:
 ```
snapshot.docChanges().forEach((change) => {
  // here we can check 'change.type' for one of the folowing event types: 'added' | 'modified' | 'removed'
  console.log(change.type);
}
```

**Comment by mikehardy** [comment]
@DisruptLive we're talking about realtime database? `firebase.database()`?

https://rnfirebase.io/reference/database/reference#on
https://rnfirebase.io/reference/database/eventtype

The type is part of the callback?

I think I need to see more code, I'm confused
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by DisruptLive** [comment]
> @DisruptLive we're talking about realtime database? `firebase.database()`?
> 
> https://rnfirebase.io/reference/database/reference#on https://rnfirebase.io/reference/database/eventtype
> 
> The type is part of the callback?
> 
> I think I need to see more code, I'm confused https://stackoverflow.com/help/how-to-ask https://stackoverflow.com/help/minimal-reproducible-example

Yes i am asking specifically about `firebase.database()`

I was using Firestore as an example of how i am able to check the event type in a Firestore listener and was looking to find out if i can do the same with a realtime database listener.

**Comment by DisruptLive** [comment]
> @DisruptLive we're talking about realtime database? `firebase.database()`?
> 
> https://rnfirebase.io/reference/database/reference#on https://rnfirebase.io/reference/database/eventtype

^ To be specific, yes, regarding listening to realtime database using `onValue` to listen for updates to a node in the realtime database, i am trying to figure out how to retrieve that `EventType` which you have noted a reference to above, from the response snapshot.

**Comment by mikehardy** [comment]
What you see is what exists: https://rnfirebase.io/reference#database

It is possible that something is missing there, because that is generated from https://github.com/invertase/react-native-firebase/blob/main/packages/database/lib/index.d.ts programmatically while the implementation is still javascript, separate in https://github.com/invertase/react-native-firebase/blob/main/packages/database/lib/index.js but I think that is unlikely

You're free to look though. I believe the reference API I quoted which shows that the event type is a param but not on the actual data is what there is

**Comment by DisruptLive** [comment]
> What you see is what exists: https://rnfirebase.io/reference#database
> 
> It is possible that something is missing there, because that is generated from https://github.com/invertase/react-native-firebase/blob/main/packages/database/lib/index.d.ts programmatically while the implementation is still javascript, separate in https://github.com/invertase/react-native-firebase/blob/main/packages/database/lib/index.js but I think that is unlikely
> 
> You're free to look though. I believe the reference API I quoted which shows that the event type is a param but not on the actual data is what there is

I appreciate your help. Here is some code that shows exactly where id like to be able to check the `EventType`, via an `onValue` realtime listener:

```
realtimeListener.unsubscribe = onValue(query(ref(db, 'users')), (snapshot) => {

   // i am trying to find out if there is a method or reference point which i can use to retrieve the `EventType` from the `snapshot` that is returned here:  child_added, child_changed, child_removed
  
   if(snapshot.exists()) {
    // do stuff with snapshot.val()
  }

});
```

**Comment by mikehardy** [comment]
As mentioned I don't think that exists, whether it would be preferable or not. I believe you'll need to do your conditional on the EventType provided as a parameter on your listener callback per the API I linked before https://rnfirebase.io/reference/database/reference#on
