### ISSUE TITLE
🔥 Clear getInitialLink after first call

### ISSUE THREAD

**Issue by rtman** [invertase/react-native-firebase#3027]
## Issue

Just making an issue for this as it was part of another issue and was getting lost. 

`getInitialLink` will return the link until the app is killed. There are certain scenarios where you need to process the link on the first time it shows up only, it would be great if it returned null after the first call (or cleared the link in some manner). @mikehardy [was talking about dequeing in this comment ](https://github.com/invertase/react-native-firebase/issues/2618#issuecomment-543884753) seems like it would work great here.

### Javascript

<details><summary>Click To Expand</summary>
<p>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

#### `AppDelegate.m`:

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `AndroidManifest.xml`:

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.6.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `DynamicLinks`
- **Are you using `TypeScript`?**
  - `Y  3.7.3`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by ovy9086** [comment]
shouldn't really be stale bot . this is happening for a long time and should be addressed

**Comment by mikehardy** [comment]
PRs gladly accepted, could be similar to #1820

**Comment by ShyamPanchal** [comment]
Facing the same issue on ios version 13.3 and Android version 8.0.0, React Native version 0.61.5 and react-native-firebase version 5.6.0.

**Comment by Pierre-CLIND** [comment]
Any update? I'm facing the same issue

**Comment by mikehardy** [comment]
@Pierre-CLIND in an open source project, all development is here. This issue has been closed for a long time, all information is contained in it. There won't be updates on closed issues typically, and asking just generates notifications for people
