### ISSUE TITLE
Can we talk about error documentation please?

### ISSUE THREAD

**Issue by andersonaddo** [invertase/react-native-firebase#3033]
## Documentation Feedback
Hello guys!
First of all, great package. It's a huge help to developers everywhere!
Now back to the topic at hand:
I find it pretty irking how little documentation there is about there error codes and messages that this package will return for the different Firebase modules. And if it's the case that this package returns errors identical to Firebase Web, I think that should be explicitly stated somewhere, even if it may seem like an obvious assumption to make.
I understand that you guys only recently upgraded to v6, so there's a lot of work going on right now, but I'd love if this were improved because I find it super important.

**Comment by mikehardy** [comment]
I think this is in general the case for most of the modules, maybe propose a PR for one of the modules that links to the upstream error code list (like, auth maybe - it has so many possible errors) and if it seems to fit the need we could roll through the rest of the modules? There's an edit link on each documentation page at top right and github makes docs PRs almost trivial + fast

**Comment by andersonaddo** [comment]
Great, the PR has been merged!
Hopefully y'all will follow suit for the other modules.
