### ISSUE TITLE
Dynamic Links

### ISSUE THREAD

**Issue by g4laura** [invertase/react-native-firebase#304]
I saw it mentioned in another issue that dynamic links were a possible long term goal but not a priority right now, but I was wondering if anyone could give me any tips about how to set up dynamic links with react native, especially for iOS. 

I have receiving dynamic links working well on android but only sometimes on iOS. It works if the app is installed, on some iphones, it doesn't work on others. Also, when the app isn't installed, the dynamic link takes the user to the apple app store, but after the app is open, it doesn't take the user to the screen corresponding to the link.
Also, right now I'm creating the dynamic links with javascript so, they are very long.

If anyone could guide me on how to get dynamic links working, I'd appreciate it. 

I don't know Objective C, but I have experience with java.

**Comment by chrisbianca** [comment]
@g4laura This is still very much on the roadmap and I did start taking a look, but unfortunately got pulled away onto other priorities - multi app support being the main thing we're focusing on at the moment.

The best way to currently get Dynamic Links working on iOS is to make use of a combination of Firebase and the built in React Native linking library (https://facebook.github.io/react-native/docs/linking.html).  Follow the setup guide for the Linking library, then:

In your AppDelegate.m, you need to add the following methods:

```
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<NSString *, id> *)options {
  return [self application:app openURL:url sourceApplication:nil annotation:@{}];
}

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
  FIRDynamicLink *dynamicLink =
  [[FIRDynamicLinks dynamicLinks] dynamicLinkFromCustomSchemeURL:url];
  
  if (dynamicLink) {
    return [RCTLinkingManager application:application
                                  openURL:dynamicLink.url
                        sourceApplication:sourceApplication
                               annotation:annotation];
  }
  
  return [RCTLinkingManager application:application
                                openURL:url
                      sourceApplication:sourceApplication
                             annotation:annotation];
}
```
Then in your JS code you can add the following when the app mounts:
```
componentDidMount() {
  // Check if the app was opened from a link
  Linking.getInitialURL()
    .then(url => this.onLink({ url }))
    .catch(err => console.error('An error occurred getting the initial page', err));
  // Register Linking listener
  Linking.addEventListener('url', this.onLink);
}

onLink = ({ url }) => {
  // do something with the URL
}
```
The JS code should work for Android too.

**Comment by Ehesp** [comment]
@chrisbianca we could add this to the docs? Just state at the top it's a workaround solution until a full module is built (if it's even needed!)

**Comment by chrisbianca** [comment]
@Ehesp Yeah, I didn't close the issue to remind me to add to the docs

**Comment by g4laura** [comment]
Thank you! :)

**Comment by royisch** [comment]
@g4laura - could you write here the java implementation as well?

**Comment by g4laura** [comment]
@royisch 
For java, if you already have react-native-firebase set up,
Follow the steps here for android in the 'Set up Firebase and the Dynamic Links SDK' and 'Add an intent filter for deep links' sections https://firebase.google.com/docs/dynamic-links/android/receive

I added the intent filter within main activity. It's also a good idea to add the line android:launchMode="singleTask" . Mine looks like this, with my actual app_code where it says app_code and my actual deep link where it says my_deep_link:
      <activity
        android:name=".MainActivity"
        android:launchMode="singleTask"
       ........  
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https"
                  android:host="app_code.app.goo.gl"
                  />
          <data android:scheme="http"
                android:host="app_code.app.goo.gl"
                />
            <data android:scheme="app_code.app.goo.gl/?link=https"
                  android:host="my_deep_link"
                  />
        </intent-filter>
    </activity>
     ......



Then you can use the React Native Linking library to handle the links in your javascript code. I created my first test links using  the Dynamic Links section of the Firebase console and now I just create my links in javascript using this as a reference: https://firebase.google.com/docs/dynamic-links/create-manually

Hope that helps!

**Comment by stevenyap** [comment]
@g4laura Can you share your Java code on how you pass the Dynamic Link to React Native Linking?

**Comment by RedFu01** [comment]
Hey @g4laura,
Following your suggestions works for me for opening the app, but on android i will receive `null` as url through the RN Linking Library. Do you have a fix for that?

**Comment by SMJ93** [comment]
@chrisbianca does this work for you with universal links? In the [Firebase iOS docs](https://firebase.google.com/docs/dynamic-links/ios/receive?authuser=1#open-dynamic-links-in-your-app) (6.) it says to add this code in addition to the URL scheme code you listed above:

```
- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray *))restorationHandler {

  BOOL handled = [[FIRDynamicLinks dynamicLinks]
             handleUniversalLink:userActivity.webpageURL
             completion:^(FIRDynamicLink * _Nullable dynamicLink,
                          NSError * _Nullable error) {
               // ...
             }];


  return handled;
}
```

**Comment by g4laura** [comment]
@stevenyap
 I think the code I posted here was all of the java code I used for dynamic links, I did everything else in react native javascript

@RedFu01 
Is it working on iOS?
If it's not working on iOS either.. Are you placing the React Native Linking code in your router? If not, doing that might help.. 


@SMJ93 
I included this:
- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray *))restorationHandler {
   return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}

**Comment by dhansiddh** [comment]
I have created a npm module for iOS and Android for handling firebase dynamic links. You can look at this [https://www.npmjs.com/package/react-native-firebase-dynamic-links](url) for detail.

**Comment by Salakar** [comment]
@dhansiddh not that I'm complaining but why a separate module? Just means another thing to install :)

**Comment by dhansiddh** [comment]
@Salakar I agree that it would be best if it is supported by react-native-firebase out of box. And that is what I am working on as of now. Until then I have created a module to help myself and other with the deeplink functionality for iOS and Android.

**Comment by omer88** [comment]
Hi @Salakar  and @dhansiddh , I'm currently also working on react-native-firebase dynamic link support, and I think I'm pretty close to finish it.

**Comment by royisch** [comment]
@dhansiddh - your link is not working

**Comment by dhansiddh** [comment]
@royisch I have updated the url. You can click on this [link](https://www.npmjs.com/package/react-native-firebase-dynamic-links) for detail

**Comment by Ehesp** [comment]
@omer88 how are you getting on?

**Comment by omer88** [comment]
Hi @Ehesp, the PR is going to be ready tomorrow.
This is my branch: https://github.com/rmrs/react-native-firebase/tree/omer_links

**Comment by chrisbianca** [comment]
I'm closing this now that the PR has been merged in for the upcoming 3.1.0 release.  No date on that yet, but if you'd like to give it a try, you can install the master version of the library using the following:

`npm install --save https://github.com/invertase/react-native-firebase`

**Comment by FakhruddinAbdi** [comment]
@chrisbianca Dynamic link in my app open the app but doesn't fire `Linking.addEventListener('url' ...)
I read many threads, some of them mentioning we should use `RCTLinkingManager` library in the AppDelegate.m

But I failed using it ( came across chain of errors)
Do i need to use `RCTLinkingManager` or not ?

Clearly the rnfirebase doc doesn't use it

**Comment by anhtuank7c** [comment]
If you guys using `react-navigation`,  follow this guide: https://github.com/react-navigation/react-navigation.github.io/pull/326
