### ISSUE TITLE
RNFirebaseBackgroundMessage don't work

### ISSUE THREAD

**Issue by volodymyrFilatenko** [invertase/react-native-firebase#3043]
Hello, could yo help me?
My app don't work in background mode (AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => Push.hanldeBackgroundMessages);).
React native version 0.59.10.
"react-native-firebase": "5.5.1".

**android/build.gradle**

buildscript {
ext {
buildToolsVersion = "28.0.3"
minSdkVersion = 21
compileSdkVersion = 28
targetSdkVersion = 28
supportLibVersion = "28.0.0"
}
repositories {
mavenCentral()
jcenter()
google()
maven {url 'https://maven.fabric.io/public'}
}
dependencies {
classpath 'com.android.tools.build:gradle:3.4.1'
classpath 'com.google.gms:google-services:4.2.0'
classpath 'io.fabric.tools:gradle:1.25.4'

    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
}
}

subprojects {
afterEvaluate {project ->
if (project.hasProperty("android")) {
android {
compileSdkVersion 28 //do this in android/app/build.gradle too
buildToolsVersion '28.0.3' //do this in android/app/build.gradle too
}
}
}
}

allprojects {
repositories {
mavenLocal()
maven {
// All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
url "$rootDir/../node_modules/react-native/android"
}
maven { url "https://www.jitpack.io" }
maven { url "https://maven.google.com" }
google()
jcenter()
}
}

**app/build.gradle**

apply plugin: "com.android.application"
apply plugin: "io.fabric"

import com.android.build.OutputFile

project.ext.react = [
entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

def enableProguardInReleaseBuilds = false
android {
configurations.all {
resolutionStrategy {
force 'com.google.android.gms:play-services-gcm:16.1.0'
force 'com.google.android.gms:play-services-basement:16.2.0'
force 'com.google.android.gms:play-services-auth:16.0.1'
force 'com.google.firebase:firebase-messaging:18.0.0'
force 'com.google.firebase:firebase-common:17.0.0'
force 'com.google.firebase:firebase-iid:18.0.0'
force 'com.google.android.gms:play-services-stats:16.0.1'
force 'com.google.android.gms:play-services-base:16.0.1'
}
}
compileSdkVersion 28
buildToolsVersion '28.0.2'

defaultConfig {
    applicationId "com.wanda.carelink"
    minSdkVersion rootProject.ext.minSdkVersion
    targetSdkVersion rootProject.ext.targetSdkVersion
    missingDimensionStrategy 'react-native-camera', 'general'
    versionCode 41
    versionName "3.2.1"
    multiDexEnabled true

}
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
signingConfigs {
    release {
        if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
            storeFile file(MYAPP_RELEASE_STORE_FILE)
            storePassword MYAPP_RELEASE_STORE_PASSWORD
            keyAlias MYAPP_RELEASE_KEY_ALIAS
            keyPassword MYAPP_RELEASE_KEY_PASSWORD
        }
    }
}
splits {
    abi {
        reset()
        enable enableSeparateBuildPerCPUArchitecture
        universalApk false  // If true, also generate a universal APK
        include "armeabi-v7a", "x86", "arm64-v8a"
    }
}
buildTypes {
    release {
        minifyEnabled enableProguardInReleaseBuilds
        proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        signingConfig signingConfigs.release
    }
}
aaptOptions {
    additionalParameters "--no-version-vectors"
}

// applicationVariants are e.g. debug, release
applicationVariants.all { variant ->
    variant.outputs.each { output ->
        // For each separate APK per architecture, set a unique version code as described here:
        // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
        def versionCodes = ["armeabi-v7a":1, "x86":2]
        def abi = output.getFilter(OutputFile.ABI)
        if (abi != null) {  // null for the universal-debug, universal-release variants
            output.versionCodeOverride =
                    versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
        }
    }
}
}

dependencies {
implementation project(':react-native-sound')
implementation project(':@react-native-community_async-storage')
compile project(':ihealthlibrary-react-native')
compile project(':react-native-splash-screen')
compile project(':react-native-ble-manager')
compile project(':react-native-touch-id')
compile project(':react-native-keychain')
compile project(':react-native-barcode-scanner-google')
implementation project(':react-native-bluetooth-status')
implementation project(':realm')
implementation project(':react-native-vector-icons')
implementation project(':react-native-svg')
implementation project(':react-native-push-notification')
implementation project(':react-native-linear-gradient')
implementation project(':react-native-firebase')
implementation project(':react-native-device-info')
implementation project(':appcenter-crashes')
implementation project(':appcenter-analytics')
implementation project(':appcenter')
implementation project(':react-native-push-notification')
implementation project(':react-native-svg')
implementation project(':react-native-device-info')
implementation project(':realm')
implementation project(':react-native-vector-icons')
implementation project(':react-native-linear-gradient')

implementation fileTree(dir: "libs", include: ["*.jar"])
implementation "com.android.support:appcompat-v7:27.1.0" // please take this code required for build release apk
implementation "com.facebook.react:react-native:0.59.10"
implementation "me.leolin:ShortcutBadger:1.1.21@aar"

implementation 'com.twilio:video-android:5.0.0'
implementation "com.koushikdutta.ion:ion:2.1.7"
implementation "com.android.support:preference-v14:${rootProject.ext.supportLibVersion}"
implementation "com.android.support:design:${rootProject.ext.supportLibVersion}"

// Firebase dependencies
implementation "com.google.android.gms:play-services-base:16.1.0"
implementation "com.google.firebase:firebase-core:16.0.9"
implementation "com.google.firebase:firebase-messaging:18.0.0"
implementation('com.crashlytics.sdk.android:crashlytics:2.9.5@aar') {
  transitive = true
 }

 implementation 'com.google.android.gms:play-services-vision:15.0.2'
 implementation project(':react-native-camera')
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
from configurations.compile
into 'libs'
}

apply plugin: 'com.google.gms.google-services'

com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true

**Comment by mikehardy** [comment]
The template formatting is pretty fairly messed up here making it very difficult to read, and I am having trouble finding a single dependency that is actually up to date, implying that any bugs found may already be fixed, which would be an inefficient use of time

Can you fix the formatting (the triple-backticks from the issue template are what do that) and examine+update your dependencies then re-try?

I use the "Bill of Materials" style for firebase, and it's on 24.4.0 now, which works with react-native-firebase v5.5.6 just fine

**Comment by volodymyrFilatenko** [comment]
Thanks for answer, all  dependencies were updated in this files(it is actual version). What you mean under 'Bill of Materials" and 24.4.0 - what is it?

**Comment by mikehardy** [comment]
https://firebase.google.com/docs/android/setup#firebase-bom

they are not updated, you are on react-native 59 and android support libraries, and react-native-firebase 5.5.1, and google plugin 4.2.0 etc. Everything is old, I was not exaggerating, I can't find an up to date thing in that file

**Comment by volodymyrFilatenko** [comment]
Sorry, I didn't correct understand. So I have to update react native and other for correct work firebase in background?

**Comment by mikehardy** [comment]
No, just in general you have to be running current versions before support requests are efficient + useful. I can't speak for others, but I'm not personally motivated to spend any time looking at non-current versions, I've already worked so hard to fix the bugs that resulted in the current versions I don't want to see them again ;-)

**Comment by mikehardy** [comment]
worth mentioning that yes, the RN59->RN60 upgrade is very painful, I recognize that. But you can move to AndroidX and react-native-firebase 5.6.0 and current versions of everything else I think while still on RN59 as long as you use jetifier. That's current enough to try to puzzle through something I think. Example here (though versions there aren't likely up to date either as it's just a demo - you can see how to do AndroidX + RN59 + react-native-firebase) https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh

**Comment by aminosman** [comment]
I can confirm that we are also not seeing notifications when the app is in the background on android  after updating to RN 0.61.2 from 0.59.4. We are also using `RNFirebaseBackgroundMessage` to handle notifications. I am digging more but found this and thought I would chime in.

**Comment by aminosman** [comment]
Forgot to mention, we also updated from `5.5.6` to `5.6.0` but it is not working on either version

**Comment by aminosman** [comment]
Looking in the logs I see this 

> 2019-12-26 18:20:51.514 5553-8213/com.minderapps.minder E/ReactNativeJS: Error: You attempted to use a firebase module that's not installed on your Android project by calling firebase.notifications().
    
    Ensure you have:
    
    1) Installed the required Firebase Android SDK dependency 'com.google.firebase:firebase-notifications' in your 'android/app/build.gradle' file.
    
    2) Imported the 'io.invertase.firebase.notifications.RNFirebaseNotificationsPackage' module in your 'MainApplication.java' file.
    
    3) Added the 'new RNFirebaseNotificationsPackage()' line inside of the RN 'getPackages()' method list.
    
    See http://invertase.link/android for full setup instructions.

I am pretty sure I have messaging wired up as like I said this was working before and does work when app is in foreground

**Comment by mikehardy** [comment]
@aminosman good that you looked in logcat, that error is unambiguous. You have an integration error such that the notifications module is not integrated. Auto-linking handles the main react-native-firebase package integration, but for RNFBv5 you still must add the individual packages. Example (different module but same principle) on this line https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh#L101 - the gradle dep + the java class import + the object initialization

**Comment by aminosman** [comment]
I have completed these step, and read them over many times. Here is my get package:

`import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;`
>   protected List<ReactPackage> getPackages() {
    List<ReactPackage> packages = new PackageList(this).getPackages();
    packages.add(new RNFirebaseAnalyticsPackage());
    packages.add(new RNFirebaseAuthPackage());
    packages.add(new RNFirebaseDatabasePackage());
    packages.add(new RNFirebaseMessagingPackage());
    packages.add(new RNFirebaseNotificationsPackage());
    packages.add(new RNFirebaseRemoteConfigPackage());
    return packages;
   }

I have added `apply plugin: 'com.google.gms.google-services'` to app build.gradle

along with these implementations 

>     implementation ("com.google.android.gms:play-services-base:16.1.0") {
        force = true
    }
    implementation ("com.google.android.gms:play-services-gcm:16.0.0") {
        force = true
    }
    implementation ("com.google.firebase:firebase-analytics:17.2.1") {
        force = true
    }
    implementation ("com.google.firebase:firebase-auth:17.0.0") {
        force = true
    }
    implementation ("com.google.firebase:firebase-core:16.0.9") {
        force = true
    }
    implementation ("com.google.firebase:firebase-database:17.0.0") {
        force = true
    }
    implementation ("com.google.firebase:firebase-messaging:20.1.0") {
        force = true
        implementation "me.leolin:ShortcutBadger:1.1.21@aar"
    }
    implementation ("com.google.firebase:firebase-config:17.0.0") {
        force = true
    }

    implementation (project(':react-native-firebase')) {
        transitive = false
        exclude group: 'com.google.android.gms'
    }

**Comment by mikehardy** [comment]
Then the last thing I can think of (besides that your firebase deps are still really old), is that for the headlessJS I made sure it was initialized very early in the startup sequence, before the main app was registered

**Comment by aminosman** [comment]
This is our app start code:

> export default async function setup() {
  if (Platform.OS === 'android') {
    AppRegistry.registerHeadlessTask(
      'RNFirebaseBackgroundMessage',
      () => bgMessaging,
    )
    Navigation.events().registerAppLaunchedListener(() => {
      // eslint-disable-next-line no-console
      if (__DEV__) console.log('[MINDER] App launched event.')
      startApp()
    })
  } else {
    startApp()
  }
}

**Comment by aminosman** [comment]
Again, this was working before we updated. So this is either an issue with the update or some kind of new configuration that has not been made on our end.

**Comment by aminosman** [comment]
Did more digging. I am able to trace the call through ` int taskId = headlessJsTaskContext.startTask(taskConfig);` in the `HeadlessJsTaskService.java` not sure if that helps.

**Comment by aminosman** [comment]
Updated dependencies, still no luck

`implementation ("com.google.firebase:firebase-analytics:17.2.1")`
`implementation ("com.google.firebase:firebase-auth:17.0.0")`
`implementation ("com.google.firebase:firebase-database:19.2.0")`
`implementation ("com.google.firebase:firebase-messaging:20.1.0")`
`implementation ("com.google.firebase:firebase-config:19.1.0")`
`implementation ("com.google.firebase:firebase-core:17.2.1")`

**Comment by aminosman** [comment]
I have done more digging and have found that `NativeModules` is returning an empty object only in the Headless JS process.

**Comment by aminosman** [comment]
I am not sure we are seeing the same issue here so I am continuing my conversation under a new ticket https://github.com/invertase/react-native-firebase/issues/3053

**Comment by suren-gts** [comment]
Any update on issue ? For Expo Apps getting error "AppRegistry not able to register (calling headless)

**Comment by msqar** [comment]
Anyone was able to solve this error on Android? Still showing whenever I run the app every time. It's getting annoying. Any ideas?

**Comment by volodymyrFilatenko** [comment]
I solved this issue, when upgraded react native to RN0.61.5 and firebase to 5.6.0 for android. After this actions  you must open file node_modules/react-native-firebase/android/build.gradle and copy firebase-messaging version and others and insert to your build.gradle.

**Comment by mikehardy** [comment]
@volodymyrFilatenko no, there should never be a need to reach into node_modules and alter things unless you're fixing a bug that you have an active PR for that has some degree of acceptance from the maintainers, and I don't think that fits this case. You specify versions in your project android/app/build.gradle roughly like the lines here where the 'bom' platform is declared and then the dependency for each module: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

That's how the dependencies are added and versioned.

**Comment by msqar** [comment]
I was able to solve my error :)

**Comment by Salakar** [comment]
Closing as original poster and others fixed their issue.
