### ISSUE TITLE
Typo in /packages/app/lib/internal/registry/app.js

### ISSUE THREAD

**Issue by gustavopch** [invertase/react-native-firebase#3046]
There's a typo here. It should be `initialized`. Missing the "i":
https://github.com/invertase/react-native-firebase/blob/b40d44c57e81a4110cbb4e6204c400cb8f78b00a/packages/app/lib/internal/registry/app.js#L176

Just as a side note, this kind of typo (there may be a bunch of other ones, who knows) wouldn't exist if the code was written in TypeScript.

**Comment by mikehardy** [comment]
Typescript is great, and I believe it's on the roadmap, but code doesn't rewrite itself unfortunately and this package has been around long before TS was popular. Just as easy to PR this change vs log it, yes? Github handles the PR flow for simple things like this trivially so it doesn't feel as heavy as a normal fork/clone/edit/PR etc, it's all basically 2 pages (one for edit, one for PR submit)

**Comment by gustavopch** [comment]
@mikehardy Thanks for the suggestion. Just created the PR.

**Comment by Ehesp** [comment]
Thanks - yeah TS migration is on our roadmap but not a priority at the moment.
