### ISSUE TITLE
[v6] Change database URL during run time for same project

### ISSUE THREAD

**Issue by lisabaut** [invertase/react-native-firebase#3049]
## Issue

I am running my app on Android and have one firebase project with two databases.

**With version 5.x of RN-Firebase** I was able to change the database URL during runtime with simply calling the module with the URL string: 
```TS
firebase.database('https://path-to-database.url');
```

See older discussion on this implementation here: https://github.com/invertase/react-native-firebase/pull/649#issuecomment-375038938

**Since version 6 I get the error**
```TS
Error: No Firebase App ''https://path-to-database.url'' has been created 
- call firebase.initializeApp()
```

Initializing a new app with the exact same [DEFAULT] project's data and configuration would result in something like:
```TS
  // merge default app options with new databaseURL
  const options = {
    ...firebase.app().options,
    databaseURL: 'https://path-to-database.url'
  };

  // create new app with a custom name
  const app = await firebase.initializeApp(options, {
    name: 'can-be-any-name'
  });
  
 // get database instance
 database(app);
```

Now I am wondering, why since version 6 it is nessecary to initialize a new app again although it is the same app/project with the same configuration?
([This issue with a similar question](https://github.com/invertase/react-native-firebase/issues/2677) was closed unfortunately. [This issue with changing the module itself by hand](https://github.com/invertase/react-native-firebase/issues/2991) seems a bit of an overhead.)

Is there another way to simply point the database module to the correct database URL of my default app (like it was with version 5.x)?

Thanks a lot!

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/analytics": "^6.2.0",
    "@react-native-firebase/app": "^6.2.0",
    "@react-native-firebase/auth": "^6.2.0",
    "@react-native-firebase/database": "^6.2.0",
    "@react-native-firebase/messaging": "^6.2.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?
</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by r-a-o** [comment]
We are having the same exact issue with the 6.x version, with version 5.x we were able to change database using the `firebase.database('https://path-to-database.url');` method call.
How do we do this in version 6.x ?

**Comment by Jonovono** [comment]
@r-a-o  @lisabaut did you guys find an answer to this? Having the same issue.

**Comment by Jonovono** [comment]
Right now, I have to add a new project to connect to a new database (which then makes it so i'm not authed with these new database)

**Comment by lisabaut** [comment]
Unfortunately I can't see another solution than creating a new app on the client side if you want to switch the database URL within the same connected firebase project with React-Native Firebase >6.0

=> See also the [firebase google docs for multiple databases](https://firebase.google.com/docs/database/usage/sharding#connect_your_app_to_multiple_database_instances) 
(Caution: Different from the Web SDK => RN-Firebase `initializeApp ` returns a Promise)

As I need to run messaging and analytics too [which don't work with a client side firebase app in react native](https://invertase.io/oss/react-native-firebase/v6/app/client), I have now **two firebase apps** initialized which are connected to the same firebase project with the same credentials
- the native initialized [DEFAULT] one for messaging and analytics
- the client initialized "secondary" one for authentification and real time database

Depending on the authentification settings in the firebase project I need to register the user with this newly created client app as well (which @Jonovono also already stated above).

Which results in
```TS
// merge default app options with new databaseURL
const options = {
  ...firebase.app().options, // credentials and data from [DEFAULT] app
  databaseURL: 'https://path-to-database.url'
};

// create new app with a custom name
const clientApp = await firebase.initializeApp(options, {
  name: 'my-client-firebase-app'
});

// get auth instance and sign in
auth(clientApp).signInWithCredential(.....) 

// get database instance and read data from the correct database URL
database(clientApp).ref(....);

```

**Comment by lisabaut** [comment]
### UPDATE
@r-a-o @Jonovono 

I found an easier way to do it:

```TS

import firebase from '@react-native-firebase/app';
import '@react-native-firebase/database'; // <= otherwise a warning is thrown "you forgot to import database"

// call default app first and then database
// app().database() accepts a string as an argument => the databaseUrl

const database = firebase.app().database('https://my-database-url.firebase.com'); 

// database points to the correct database
console.log(database._customUrlOrRegion); // => 'https://my-database-url.firebaseio.com'; 

// do your stuff with database
database.ref()....

```

No need to create a secondary app !
No need to authenticate with a secondary app!

The only drawback I found is that `_customUrlOrRegion` is not declared within the Types.
Still it works for me.

**Comment by Jonovono** [comment]
@lisabaut ah no way, I will give this a try! thanks :)
