### ISSUE TITLE
Phone Auth with RN CLI

### ISSUE THREAD

**Issue by topguru228** [invertase/react-native-firebase#3055]
I tried several times with Phone Auth on React Native CLI.

Even if auth().signInWithPhoneNumber is executed successfully, no SMS message is received.

**Comment by mikehardy** [comment]
no template

That said, SMS message delivery from google firebase is entirely inconsistent and it is not the fault of firebase or google. It is a local carrier issue, you can search the issues here (closed and open) for more discussion

If you test with a test number (read the docs to see how to configure test numbers for SMS auth) and it works, but you still aren't receiving SMS, you'll need to test with a bunch of different phones and I bet you do receive an SMS on at least one of them.

For me it is not reliable enough in my primary country (Ecuador) to be useful, but for US phones it's great. Which means I can't really use this auth method in practice.
