### ISSUE TITLE
Firestore: collection group queries with bounds (e.g., `startAfter`) fail when the bound is a document snapshot

### ISSUE THREAD

**Issue by var-const** [invertase/react-native-firebase#3063]
(see the [original bug report](https://github.com/firebase/firebase-js-sdk/issues/2456) that we received)

When using React Native version of Firestore, code similar to the following:
```javascript
const docSnapshot = someDocumentSnapshot();
const cgQuery = firestore
    .collectionGroup('foo');
    .cgQuery.startAfter(docSnapshot);
await cgQuery.get();
```

will result in triggering this error from Firestore Android SDK:

https://github.com/firebase/firebase-android-sdk/blob/f629ebe50811f9b84ede5fd61d54573a7f283250/firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java#L387-L393

In other words, while the SDK allows passing a `FirestoreDocumentSnapshot` as an argument to `startAfter` (and similar functions), doing so results in a runtime error when the query is a collection group query.

My suspicion is that this data transformation step:
https://github.com/invertase/react-native-firebase/blob/da0408ca4eb254042fc10322597829094f7fab00/packages/firestore/lib/FirestoreQuery.js#L75
doesn't take into account that collection group queries require a full document path (not a plain document ID like regular queries). See e.g. the validation logic here:

https://github.com/firebase/firebase-js-sdk/blob/af162f975eb160b0d1ab1b64d4cee8e7313e0b68/packages/firestore/src/api/database.ts#L1857-L1877

**Comment by Ehesp** [comment]
Just pushed up a fix, thanks for the help debugging, really helped out.
