### ISSUE TITLE
Crashes do not appear in Crashlytics 

### ISSUE THREAD

**Issue by alex-mironov** [invertase/react-native-firebase#3065]
I've integrated `@react-native-firebase/crashlytics` as suggested in the documentation but crashes don't appear in Crashlytics for iOS. Surprisingly Android works fine.

`package.json`
```
    "@react-native-firebase/app": "^6.1.0",
    "@react-native-firebase/crashlytics": "^6.1.0",
    "react-native": "0.61.4",
```

Run Script  from the xcode build phases:
```
set -e

if [[ ${PODS_ROOT} ]]; then
  echo "info: Exec Fabric Run from Pods"
  "${PODS_ROOT}/Fabric/run"
else
  echo "info: Exec Fabric Run from framework"
  "${PROJECT_DIR}/Fabric.framework/run"
fi
```

<img width="664" alt="Screen Shot 2020-01-04 at 09 02 41" src="https://user-images.githubusercontent.com/2544767/71761197-ff542000-2ed0-11ea-9881-58e1c34af58f.png">

**Comment by alex-mironov** [comment]
Code I use to enforce crash:
```
function forceCrash () {
  crashlytics().log('Testing crash')
  crashlytics().crash()
}
```

**Comment by alex-mironov** [comment]
Crashes appear when a simulator is run with: `react-native run-ios --configuration Release`

Unfortunately for some crashes I still can see this:
<img width="962" alt="Screen Shot 2020-01-05 at 12 41 36" src="https://user-images.githubusercontent.com/2544767/71778633-f8084180-2fb8-11ea-8b5d-c2ee89609c3a.png">
Does anyone has an idea what could be wrong?

**Comment by mikehardy** [comment]
@alex-mironov https://stackoverflow.com/questions/54577202/how-to-run-upload-symbols-to-upload-dsyms-as-a-part-of-xcode-build-process/55796619#55796619

**Comment by marqroldan** [comment]
Sorry for reviving this topic, but may I know why it's happening most of the time now? It used to successfully automatically upload the dsyms before, but I'm not sure what causes it now
