### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by duarte-evocorp** [invertase/react-native-firebase#3066]
_____________________________________________________

React Native Environment Info:
    System:
      OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
      CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
      Memory: 1.15 GB / 7.60 GB
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 10.18.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 22, 23, 24, 25, 27, 28, 29
        Build Tools: 23.0.1, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-Q | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0

_______________________________________________________________

Problem: 

> Task :react-native-firebase:compileDebugJavaWithJavac FAILED
/home/evocorp/Projetos/Agility/Mobile/agility_mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/notification
s/RNFirebaseNotificationManager.java:231: error: cannot find symbol
      return createChannelGroupMap(notificationManager.getNotificationChannelGroup(channelGroupId));
                                                      ^
  symbol:   method getNotificationChannelGroup(String)
  location: variable notificationManager of type NotificationManager
/home/evocorp/Projetos/Agility/Mobile/agility_mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java:331: error: cannot find symbol
        notificationChannelGroup.setDescription(description);
                                ^
  symbol:   method setDescription(String)
  location: variable notificationChannelGroup of type NotificationChannelGroup
/home/evocorp/Projetos/Agility/Mobile/agility_mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java:407: error: cannot find symbol
        writableMap.putString("description", notificationChannelGroup.getDescription());
                                                                     ^
  symbol:   method getDescription()
  location: variable notificationChannelGroup of type NotificationChannelGroup
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

**Comment by mikehardy** [comment]
There is no compilation problem with the module in general though it is possible to integrate it with versions of things that don't work. You are on react-native 0.56 which is unfortunately pointless at this point anyway, as it is not capable of generating 64-bit binaries (that was added in react-native 0.58) so the Play Store won't accept the builds I don't think. I'd recommend using https://react-native-community.github.io/upgrade-helper/ to get up to react-native 0.59 at least, then this example that generates a fully working project (demonstrating compilation works): https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh

Tentatively closing as I have no reproduction of compile failures, but several close at hand where it compiles

If it continues to happen, open a new issue, but following the template

**Comment by gianpaj** [comment]
I had this issue as well.

<details><summary>react-native info</summary>
<p>

```bash
npx @react-native-community/cli info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 713.09 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.18.1 - ~/.nvm/versions/node/v10.18.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.18.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^2.9.0 => 2.10.0
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

</p>
</details>

Fixed after changing this:
https://github.com/facebook/react-native/issues/26625#issuecomment-560030421

---

Go to `android/gradle/wrapper/gradle-wrapper.properties`

Change the following line:

```diff
- distributionUrl=https\://services.gradle.org/distributions/gradle-5.5-all.zip
+ distributionUrl=https\://services.gradle.org/distributions/gradle-6.0.1-all.zip
```
That's what worked for me with the latest versions of everything on MacOS
