### ISSUE TITLE
Storage putFile returned ref is not the same on IOS and Android

### ISSUE THREAD

**Issue by z4qx** [invertase/react-native-firebase#307]
### Environment

1. Target Platform (e.g. iOS, Android): IOS last version, android last version
4. React Native version : 0.44
5. RNFirebase Version : 2.0.2

Hi,

I have an issue while I upload an images into the folder "images". 

The ref return on IOS is "images/myImageID".
The ref returned on android is "/images/myImagesID"
The begging "/" is missing on IOS. 

Thanks to fix it.

**Comment by chrisbianca** [comment]
This is an interesting one - both iOS and Android are using the build in Firebase method to get the full path:

iOS: `task.reference.fullPath`
Android: `taskSnapshot.getStorage().getPath()`

So the discrepancy is actually in the Firebase SDKs, not in anything that we're doing in RNFirebase.  We can resolve it, but I'm not sure which is the better approach, to add the / to iOS or remove the / from Android.

Thoughts @Ehesp @Salakar ?

**Comment by chrisbianca** [comment]
I've just been looking into this more closely, and there's no longer an issue in v3 (which is currently in alpha release)  The ref returned by an upload has exactly the same ref path as specified when you create it.  

So if you create the ref with a path of: `images/myImageID` it will have that path when it has uploaded.  If you create the ref with a path of: `/images/myImageID` then it will have that path when it has uploaded.

This is true across iOS and Android, so regardless of the differing behaviour of the iOS and Android SDKs, we already have a consistent view in the JS object.
