### ISSUE TITLE
🔥[v6] Type annotation for Reference "key" does not exist

### ISSUE THREAD

**Issue by NickCWilkins** [invertase/react-native-firebase#3072]
## Issue

It seems like the type Reference is missing the property"key" as described by the firebase web sdk documentation.

According to the docs I can do something like this to push a ref to a collection, and get out a corresponding key. 
```
const postRef= await this.database.ref('blogs').push(data);
return postRef.key;
```

**This actually works**, but the type for `key` doesn't exist, so I get errors.
![image](https://user-images.githubusercontent.com/13734246/71844585-7685e180-3094-11ea-83ec-14f14ad1d799.png)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Salakar** [comment]
Hey, thanks for the report, just to clarify are you saying that this works but its just the type thats missing?

If its just the type would you be able to send a PR for it by changing it in here: https://github.com/invertase/react-native-firebase/blob/master/packages/database/lib/index.d.ts#L112

Thanks

**Comment by NickCWilkins** [comment]
Yes, it works and I can access that property, but there is no type for it. I'll that PR when I have a moment.

**Comment by russellwheatley** [comment]
@NickCWilkins I've created a fix in this PR https://github.com/invertase/react-native-firebase/pull/3150. Should go out in the next release which we're looking at doing tomorrow (hopefully) for v6.3.0.
