### ISSUE TITLE
react-native 60+ is it recommended or minimum version?

### ISSUE THREAD

**Issue by totalamd** [invertase/react-native-firebase#3073]
All other pages say react-native 60+ is RECOMMENDATION and this page https://invertase.io/oss/react-native-firebase/v6 says it's MINIMUM VERSION.
So what is it?????

**Comment by mikehardy** [comment]
Depends on the version? RNFBv5 will work fine on RN<=59. RNFBv6 is RN60-only for support, though it appears at least one person has gotten it working on RN59.

That's the direct answer

I think the more important question at this point is, does this matter much? Staying on RN59 is nothing I'd recommend. The conversion to AndroidX and cocoapods are fundamental things to the infrastructure and they both need to happen. So I'd pretty firmly say convert to RN60+ then the question is moot. Even though I do recognize that conversion is painful, it's also from 6 months ago, waiting longer seems counterproductive.

**Comment by totalamd** [comment]
I work on kind of "legacy" project and just need to implement FCM and don't have time to check whether it produce any major problems upgrade RN to 60+.

**Comment by mikehardy** [comment]
Then use RNFBv5 - you would integrate it sort of like so https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh
