### ISSUE TITLE
[Feature Request] store auth state in iOS shared keychain via `useUserAccessGroup` method

### ISSUE THREAD

**Issue by poltak** [invertase/react-native-firebase#3074]
Hi there. First off, upon choosing to open a new feature req issue, I was directed to your [Feature Request Board](https://invertase.io/oss/react-native-firebase/feedback/), although there wasn't anything there apart from an email form. Please let me know if this is not appropriate to discuss here.

## Use-case background

I am currently developing an iOS app, where one of the main features is interacted with via a share extension. Both the main app and the share extension need access to the same Firebase auth state.

Currently the solution we have to share these states is set up a shared keychain (via `react-native-keychain` + an iOS access group) then, upon logging into Firebase on the main app and receiving a token, storing that token in the shared keychain. When the share ext starts, it checks the keychain for an existing token and uses that to log itself into Firebase.

This seems to work, however it is flawed in the way that if the user does not start the share extension before the token expires, they are unable to log into Firebase any more on the share ext.

## Idea

This page describes use of a `useUserAccessGroup` method on the Firebase Auth module to tell Firebase which access group to use and it seems to automatically manage the shared keychain:
https://firebase.google.com/docs/auth/ios/single-sign-on

This looks perfect for my use-case. Unfortunately this method is not provided in the React Native Firebase Auth module. 

**My feature request would be to add support for this method somehow.**

### What I've played with

I thought perhaps I can just add that method call into both my `AppDelegate.m` on the main app and the share ext's equivalent:
```[FIRAuth.auth useUserAccessGroup:@"MY_ACCESS_GROUP" error:nil];```

Doing this however does not give the expected results. After logging in on the main app, calling `firebase.auth().currentUser` (React Native Firebase API) on the share ext does not return a user.

<br />
Any ideas, questions, about how to do this? I personally have no experience with native ObjC or Swift iOS programming and am unsure of the difficulty of this request

**Comment by mtzfactory** [comment]
Hi, I'm very interested in this feature as well...

**Comment by mikehardy** [comment]
Best way to get new features is to make a PR, but so as not to waste anyone's time make sure Invertase likes the idea and will accept it. If anyone is serious about doing that just tag them in for discussion here

**Comment by Salakar** [comment]
Greenlight from me for this feature, if the iOS SDK has a method the we should probably expose it to JS under the same name.

Looks like this should be fairly trivial to implement also, its a method on a specific Firebase App auth instance so similar to how everything else works.

PRs are welcome, happy to point people in the right direction on how to implement if needed

**Comment by russellwheatley** [comment]
@poltak I've created a PR for this feature: #3122. So we'll hopefully get this out in the next release.

**Comment by poltak** [comment]
Thanks a lot for that @russellwheatley! Also a nice example, seeing how you implemented it.
