### ISSUE TITLE
@react-native-firebase/app/android/firebase-json.gradle' as it does not exist.  ##Android

### ISSUE THREAD

**Issue by seasonZzl** [invertase/react-native-firebase#3077]
## Issue
my project has integrated react-native-firebase, now an error is reported when integrating@react-native-firebase/admob, ( firebase-json.gradle' as it does not exist), what's the reason 

    "react": "16.8.6",
    "react-native": "0.59.10",
    "react-native-firebase": "5.3.1",

### Android

> Configure project :@react-native-firebase_admob
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/rss/talktok-main-android/node_modules/@react-native-firebase/admob/android/build.gradle' line: 44

* What went wrong:
A problem occurred evaluating project ':@react-native-firebase_admob'.
> Could not read script '/Users/rss/talktok-main-android/node_modules/@react-native-firebase/app/android/firebase-json.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 1s
/Users/rss/talktok-main-android/node_modules/@react-native-firebase/app/android/firebase-json.gradle (No such file or directory)
Open File

**Comment by aymkin** [comment]
@seasonZzl did you find solutions?

https://prnt.sc/ql9te7

**Comment by makarkotlov** [comment]
same

**Comment by amit13091992** [comment]
> Just install `@react-native-firebase/app` and be happy

@makarkotlov 
Thanks the error got resolved.
