### ISSUE TITLE
react-native-firebase 5.x Admob

### ISSUE THREAD

**Issue by seasonZzl** [invertase/react-native-firebase#3078]
Issue
my project has integrated react-native-firebase, now an error is reported when integrating@react-native-firebase/admob, ( firebase-json.gradle' as it does not exist), what's the reason

"react": "16.8.6",
"react-native": "0.59.10",
"react-native-firebase": "5.3.1",

**Comment by Ehesp** [comment]
You say you're using v5, but `@react-native-firebase/admob` is v6?

**Comment by seasonZzl** [comment]
> You say you're using v5, but `@react-native-firebase/admob` is v6?

How do I use admob on v5？

**Comment by mikehardy** [comment]
You're still on rn59, so roughly like this 

https://github.com/mikehardy/rnfbdemo/blob/29c3d84a0b9e28e18698ed8f2705ec8340621f04/make-demo-rn59.sh#L108-L125

**Comment by mikehardy** [comment]
(and if you run that script following the instructions you'll be able to see the correct result of a correct integration)

**Comment by seasonZzl** [comment]
Thank you, I have found 5.x documentation and integrated success !
