### ISSUE TITLE
Google Sign up/in implementation

### ISSUE THREAD

**Issue by evgeni-tsn** [invertase/react-native-firebase#308]
Okay, so I read the whole [documentation](http://invertase.io/react-native-firebase/#/modules/authentication) and [Firebase Docs](https://firebase.google.com/docs/auth/web/google-signin) at least twice. I still cannot understand how to implement Native Google sign up/in in the app. 
As I understand I need auth **token** from Google and then use it in `firebase.auth.GoogleAuthProvider.credential(**token**);` but I have no idea how to get it and is this a feature in this library or it has to be done with another one?
Can you guys please help me?
### Environment

1. Target Platform: Android
2. Development Operating System: Windows 10
3. Build tools: Android Studio 3.0 Canary 9
4. React Native version: 0.47
5. RNFirebase Version: 2.1.0

**Comment by chrisbianca** [comment]
@evgeni-tsn You'll need to use a library like https://github.com/devfd/react-native-google-signin to get the auth token from Google.  It's not part of this library or the native Firebase libraries.
