### ISSUE TITLE
The following build commands failed: app/node_modules/react-native-fbsdk/ios/RCTFBSDK/login/RCTConvert+FBSDKLogin.m

### ISSUE THREAD

**Issue by ilibilibom** [invertase/react-native-firebase#3082]
Hi 
I'm using xcode version: 
```
Xcode 11.3
Build version 11C29
```
When runing ```react-native run-ios```, My build is failing  with this error: 
```
app/ios/build/app/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/
react-native-fbsdk.build/Objects-normal/x86_64/RCTConvert+FBSDKLogin.o .../app/node_modules/react-native-fbsdk/ios/RCTFBSDK/login/RCTConvert+FBSDKLogin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
``` 
and in xcode error I'm getting: 
```
Module 'FBSDKCoreKit' not found
``` 
<img width="980" alt="Screen Shot 2020-01-09 at 10 31 58" src="https://user-images.githubusercontent.com/12745414/72051503-1a0d0700-32cc-11ea-8e92-9f7060c9d43a.png">

**Comment by mikehardy** [comment]
Appears to be an error related to the facebook SDK, nothing to do with react-native?

**Comment by ilibilibom** [comment]
@mikehardy Can you please explain?

**Comment by mikehardy** [comment]
Not intending to be short, but the relevant info is all in the comment as short as it is

That's a symbol from the facebook SDK.
Your error message references a path into the Facebook SDK.

So I infer you have a problem with facebook SDK integration.

There is no mention of react-native-firebase, so the issue does not belong here I don't think

**Comment by ilibilibom** [comment]
ok thanks

**Comment by fabiopaiva** [comment]
The error is indeed related to Facebook SDK, but I started having it only after installing react-native-firebase
