### ISSUE TITLE
[v6] Javascript source maps not available in crashlytics

### ISSUE THREAD

**Issue by kbanashek** [invertase/react-native-firebase#3084]
## Issue

I'm not seeing javascript stack traces being logged by default after implementing v6.2 running on iOS simulator & RN 61.5

![image](https://user-images.githubusercontent.com/2280402/72094188-d6be9280-32e3-11ea-9390-f5c2decf2e14.png)

![image](https://user-images.githubusercontent.com/2280402/72094153-ca3a3a00-32e3-11ea-807c-c242b77c518d.png)

**Comment by Salakar** [comment]
.crash() is a native method so causes a native error. Use `recordError(new Error('hello world'))` if you want to record a JS error

**Comment by kbanashek** [comment]
@Salakar Does `recordError` fire on both android and iOS? I was not seeing it fire on iOS
