### ISSUE TITLE
🔥Analytics setUserId not show on firebase debugView

### ISSUE THREAD

**Issue by binhvnguyenkms** [invertase/react-native-firebase#3088]
## Issue

When I use **firebase.analytics().setUserProperty('wingmanID', 'ID')**, it worked normally but **firebase.analytics().setUserId('userID')** is not.

Here is my screenshot of firebase debug view (**setUserProperty** worked)

<img width="1273" alt="Screen Shot 2020-01-13 at 11 06 31 AM" src="https://user-images.githubusercontent.com/48703896/72233504-5311e800-35fa-11ea-9a4a-dfc76d0c4068.png">

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package-lock.json`:

```json
    "react-native-firebase": {
      "version": "5.5.3",
      "resolved": "https://registry.npmjs.org/react-native-firebase/-/react-native-firebase-5.5.3.tgz",
      "integrity": "sha512-2r1SPAVtUuv0FNeJTdVlm5Kku1SQDRn++66abDuNSHa4zpOQc4S4KFgD7u6yTAjwo8+7H6awVeRC2wkh8kLBRA==",
      "requires": {
        "opencollective-postinstall": "^2.0.0",
        "prop-types": "^15.7.2"
      }
    },
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
  pod 'Firebase/Core', '~> 6.2.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionTextModel'
  pod 'Firebase/Messaging'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'libwebp', '~> 1.0'
  pod 'OpenCV2', '3.4.5'
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 18.16 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.13.0 - ~/.npm-global/bin/yarn
      npm: 6.9.0 - ~/.npm-global/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [X] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 5.5.3
- **`Firebase` module(s) you're using that has the issue:**
  - Firebase/Core 6.2.0 and FirebaseAnalytics 6.0.1.
  
</p>
</details>

**Comment by gabrielCodeSolutions** [comment]
This is happening to me too! I'm needing help to solve this!
