### ISSUE TITLE
🔥Notification: When tap on notification the app not being brought back to foreground

### ISSUE THREAD

**Issue by DevArenaCN** [invertase/react-native-firebase#3097]
## Issue

When receiving a notification with the app running in the background/closed, the app should reappear and should be in the foreground state, but instead it's still running in the background.

---

#### `package.json`:

```json
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-firebase": "^5.5.7",
```

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `AndroidManifest.xml`:

```xml
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:launchMode="singleTop"
        android:windowSoftInputMode="adjustResize">
</activity>
<service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
        <intent-filter>
            <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
</service>
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `5.5.7`
- **`Firebase` module(s) you're using that has the issue:**
  - `messaging`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

Logging is from adb log
```
01-14 08:35:30.892   865   865 V NotificationService: pkg=com.company.pkg canInterrupt=false intercept=true
01-14 08:35:39.047   865  3010 I ActivityManager: Setting hasTopUi=true for pid=1437
01-14 08:35:39.049  1437  1437 D PhoneStatusBar: disable: < expand ICONS* alerts SYSTEM_INFO* back home recent clock search quick_settings >
01-14 08:35:41.800   865  1766 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@66bc0cc attribute=null, token = android.os.BinderProxy@3d7e0c2
01-14 08:35:41.806   865  2272 I ActivityManager: START u0 {act=/inbox flg=0x14000000 pkg=com.playmetrics.mcr (has extras)} from uid 10384 on display 0
01-14 08:35:42.214   865  2272 I ActivityManager: Setting hasTopUi=false for pid=1437
```

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
not sure what's going on but I can say this does work for me in my project - I just tested it, RNFBv5 - I would try to make a minimal reproduction maybe starting from a template throw-away project like one generated from here https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by mikehardy** [comment]
maybe missing `    <receiver android:name="io.invertase.firebase.notifications.RNFirebaseNotificationReceiver"/>
` in AndroidManifest.xml ?

**Comment by DevArenaCN** [comment]
> maybe missing ` <receiver android:name="io.invertase.firebase.notifications.RNFirebaseNotificationReceiver"/>` in AndroidManifest.xml ? (that's from the scheduled notifications area, but I have it in my project where it's working, so maybe that's the trick, I'm not sure though - https://rnfirebase.io/docs/v5.x.x/notifications/android#Scheduled-Notifications-(Optional) )

Adding that to my AndroidManifest.xml, still nothing. I'm using React-Navigation v3 if that helps

**Comment by mikehardy** [comment]
that might - I'm not sure how it would affect Android's passing + handling of Intents as it tries to send them to the app. I'm using

```
mike@isabela:~/work/Kullki/ksocialscore/packages/public-app (onboarding) % cat package.json |grep navigation
    "react-navigation": "4.0.10",
    "react-navigation-drawer": "^2.2.2",
    "react-navigation-stack": "^2.0.9",
    "react-navigation-tabs": "^2.7.0",

```

So I don't have any good ideas but I can state at least that it should work. There may be some more clarity needed in the docs but the module works - this will be a project-specific issue in the end I think

**Comment by DevArenaCN** [comment]
@mikehardy Good to know, I'll try to upgrade my navigation and see. Are you running on RN 61 by any chance?

**Comment by mikehardy** [comment]
I am literally the current stable version of everything right now (firebase SDKs, react-native, react-native-firebase, everything - the curse of being a maintainer is that I'm the one that bleeds for the bleeding edge ;-) )

**Comment by DevArenaCN** [comment]
@mikehardy what's interesting is that it did call my
```
firebase.notifications().onNotificationOpened
```
function, the only thing it's not doing is bringing it back to foreground.

**Comment by DevArenaCN** [comment]
@mikehardy is there a sample app anywhere that I could check out? Trying to see what're the differences between yours and mine, still having trouble launching the app. If I try to send a push notification through the firebase console it would launch

**Comment by DevArenaCN** [comment]
Found the issue, it was my notification payload, closing this. Thanks for all the help!  @mikehardy

**Comment by Nicat26** [comment]
> Found the issue, it was my notification payload, closing this. Thanks for all the help! @mikehardy

how to fix that error? I have the same error

**Comment by DanMCX** [comment]
> Found the issue, it was my notification payload, closing this. Thanks for all the help! @mikehardy

Hi, you should put the solution here so the whole community benefit from this. :)
