### ISSUE TITLE
Cannot find a version of 'androidx.annotation:annotation' that satisfies the version constraints: 

### ISSUE THREAD

**Issue by danghung24031992** [invertase/react-native-firebase#3099]
Cannot find a version of 'androidx.annotation:annotation' that satisfies the version constraints: 
   Dependency path 'App:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.59.3' --> 'androidx.appcompat:appcompat:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
   Dependency path 'App:react-native-firebase:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.core:core:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
   Dependency path 'App:react-native-firebase:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.media:media:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
   Dependency path 'App:react-native-firebase:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-utils:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
   Dependency path 'App:react-native-firebase:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
   Dependency path 'App:react-native-firebase:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
   Dependency path 'App:react-native-firebase:unspecified' --> 'com.google.android.gms:play-services-base:17.1.0' --> 'androidx.collection:collection:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
   Dependency path 'App:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.59.3' --> 'androidx.appcompat:appcompat:1.0.0' --> 'androidx.cursoradapter:cursoradapter:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
   Dependency path 'App:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:0.59.3' --> 'androidx.appcompat:appcompat:1.0.0' --> 'androidx.vectordrawable:vectordrawable:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
   Dependency path 'App:react-native-firebase:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.core:core:1.0.0' --> 'androidx.lifecycle:lifecycle-runtime:2.0.0' --> 'androidx.annotation:annotation:1.0.0'
   Dependency path 'App:react-native-firebase:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.core:core:1.0.0' --> 'androidx.versionedparcelable:versionedparcelable:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
   Dependency path 'App:react-native-firebase:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-utils:1.0.0' --> 'androidx.documentfile:documentfile:1.0.0' --> 'androidx.annotation:annotation:1.0.0'

**Comment by mikehardy** [comment]
This will always be a project-specific problem likely to do with what versions you have specified in the ext{} block of android/build.gradle.

Here's an example of a build that works for react-native-0.59 with AndroidX showing clearly the module will build - https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh 

You may need to run `cd android && ./gradlew :app:dependencies` and work through the output to see what is including what at what version in order to untangle it`

Also, you ignored the template here

**Comment by qualitymanifest** [comment]
In case anyone comes across this and finds the above link dead, here is a link that should still work: https://github.com/mikehardy/rnfbdemo/blob/9e3a5a124edf5f7770165881b697e63d24564317/make-demo-rn59.sh
