### ISSUE TITLE
android storage got n arguments, expected n+1

### ISSUE THREAD

**Issue by taljacobson** [invertase/react-native-firebase#31]
been trying to download, upload, do any thing with storage and keep on getting errors for any method i use, seems like the js bridge is not sending all arguments to android.

the screen shot below is representative of putFile, downloadFile or any method I've tried.
although with different number of arguments got.

 

```javascript
try {
firebase.storage().ref('/audio').downloadFile('PTT-20170307-WA0001.opus')
   .then(download => Alert.alert('done'))
   .catch(err => Alert.alert('err'))
} catch (e) {
console.log(e)
}
```
 
tryCatch catches the fallowing error

```console
TypeError: Cannot read property 'then' of undefined
    at App.onDownload (index.android.bundle:46276)
    at Object.onPress (index.android.bundle:46291)
    at Object.touchableHandlePress (index.android.bundle:21187)
    at Object._performSideEffectsForTransition (index.android.bundle:15329)
    at Object._receiveSignal (index.android.bundle:15266)
    at Object.touchableHandleResponderRelease (index.android.bundle:15158)
    at Object.invokeGuardedCallback (index.android.bundle:10526)
    at executeDispatch (index.android.bundle:10405)
    at Object.executeDispatchesInOrder (index.android.bundle:10425)
    at executeDispatchesAndRelease (index.android.bundle:10062)

```

![screenshot_20170404-173435](https://cloud.githubusercontent.com/assets/13042769/24663492/bbdd0b80-1960-11e7-867b-ec2e2e1f6f34.png)

**Comment by Ehesp** [comment]
There's an issue at the moment with promises returning on storage, also happens on putFile. The issue is Firebase seems to do 101 ways of handling responses, which all need implementing (on the todo list).

I *think* the following will work for now. 

**PS - make sure you're on the latest alpha version**

```
firebase.storage().ref('/audio')
  .downloadFile('PTT-20170307-WA0001.opus')
  .on(firebase.storage.TaskEvent.STATE_CHANGED, (snapshot) => {
    // get snapshot state
  }, (error) => {
    console.error(error);
  }, () => {
    console.log('Done');
  });
```

Promise support will be added in soon, along with the other ways of handling a response.

**Comment by Salakar** [comment]
@taljacobson @Ehesp this definitely looks like you're on an older version, as Elliot said 'can you make sure you're on the latest alpha version'?

We also have tests for this [here](https://github.com/invertase/react-native-firebase-tests/blob/master/src/tests/storage/index.js#L24) and they're passing on both android and ios at the moment

**Comment by taljacobson** [comment]
looks like it was a version issue, had to delete the node_modules folder, since npm and yarn wouldn't update the depencencies
