### ISSUE TITLE
Firestore - Query - onSnapshot misleading docs

### ISSUE THREAD

**Issue by dccarmo** [invertase/react-native-firebase#3101]
## Documentation Feedback

If you see here:

https://invertase.io/oss/react-native-firebase/v6/firestore/reference/query#onSnapshot

The docs say that the `onSnapshot` would receive:

```
  .onSnapshot({
    error: (e) => console.error(e),
    next: (querySnapshot) => {},
  });
```

But the TS type says:

```
    onSnapshot(
      onNext: (snapshot: QuerySnapshot) => void,
      onError?: (error: Error) => void,
      onCompletion?: () => void,
    ): () => void;
```

And the actual implementation is:

```
  onSnapshot(...args) {
    let snapshotListenOptions;
    let callback;
    let onNext;
    let onError;

    try {
      const options = parseSnapshotArgs(args);
      snapshotListenOptions = options.snapshotListenOptions;
      callback = options.callback;
      onNext = options.onNext;
      onError = options.onError;
    } catch (e) {
      throw new Error(`firebase.firestore().collection().onSnapshot(*) ${e.message}`);
    }
   ...
```

Also: we're experiencing the `QuerySnapshot` coming `undefined` on `onNext`, but maybe I should report this bug somewhere else (unless it isn't!)

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Salakar** [comment]
cc @Ehesp

**Comment by Ehesp** [comment]
The library is written in JS, however there is actually multiple ways to implement `onSnapshot` in the web SDK. However, on TS you can provide multiple signatures of the same method:

https://github.com/invertase/react-native-firebase/blob/master/packages/firestore/lib/index.d.ts#L288

https://github.com/invertase/react-native-firebase/blob/master/packages/firestore/lib/index.d.ts#L318
...etc

If you scroll down in the docs, there is other implementations.

That being said, they should all be working (we have tests), each one in the docs has examples. Please let me know if something is wrong through!

**Comment by dccarmo** [comment]
Sounds good! Thanks for the clarification. We'll keep testing and let you know if we can reproduce the issue we're facing.
