### ISSUE TITLE
Notifications not received on restored devices

### ISSUE THREAD

**Issue by alexstoyanov** [invertase/react-native-firebase#3106]
## Issue
I have an issue with react-native-firebase. Whenever user changes his device(buy a new one) and restores the application the token remains the same for the restored app running on the new device. For some reason notifications are not received in this scenario.

## Environment
react: 16.9.0 => 16.9.0 
react-native: 0.61.5 => 0.61.5
react-native-firebase: 5.5.6

**Comment by alexstoyanov** [comment]
The issue still persists... Could someone of the team take a look?

**Comment by Ehesp** [comment]
What do you mean by "and restores the application"? 

Each device should be generating a new token, which is something the underlying SDKs do, we just pass the value back so I'm not sure what's going on.
