### ISSUE TITLE
No way to find if app opened via the FCM notification or from home screen

### ISSUE THREAD

**Issue by tusharlock10** [invertase/react-native-firebase#3113]
I am using the cloud messaging feature from react-native-firebase v6, there is a onNotification() method in v5 which fired when user opened the app via the notification. But I was not able to find a similar feature in v6. I am using the firebase-admin module in my Node.js server to send notifications to a device, and I am receiving the notifications without any problems.

The closest thing which I was able to find in the docs was the setBackgroundMessageHandler or onMessage function. But this isn't what I am looking for. Also, I looked through the documentation, and found that an equivalent to the onNotification function is still pending for completion in v6. But that was also way back in previous year, an it said that this feature will be added within 2-3 weeks. But still its not been added. Can you please suggest what should I do until then?

**Comment by mikehardy** [comment]
Please read the first pinned issue in the repo - notifications is not actually a firebase feature so it will not exist in RNFBv6
