### ISSUE TITLE
Add "Edit Page" button to Module Reference pages too

### ISSUE THREAD

**Issue by andersonaddo** [invertase/react-native-firebase#3115]
Hello y'all
Do you guys think it'd be possible to add the "Edit Page" button module reference to pages like [this](https://invertase.io/oss/react-native-firebase/v6/messaging/reference/module)? For a while I was thinking that maybe those pages are hosted somewhere outside of Github, but apparently they actually do source thier information from files on the repo (like this [one](https://github.com/invertase/react-native-firebase/blob/master/packages/messaging/lib/index.d.ts))

I think this would be a massive help in helping the docs improve their quality (less friction for people who feel the impulse to improve them). This especially applies to modules like the Messages module. I can see some recent Github Issues popping up  (and discussions on Discord) in which people are discussing some pretty important information that isn't in the docs.

**Comment by mikehardy** [comment]
Cross-reference really recent discussion https://github.com/invertase/react-native-firebase/pull/3092#issuecomment-574123464 where I think @Phaen was going to take a look at this

**Comment by andersonaddo** [comment]
@Phaen if there's any way I can help you with it, hmu!

**Comment by Phaen** [comment]
There's a PR ready to fix this issue on our repo, should be deployed soon.
