### ISSUE TITLE
Could not invoke RNFirebaseAnalytics.logEvent null in react-native-firebase v5.

### ISSUE THREAD

**Issue by mdfateh** [invertase/react-native-firebase#3118]
The error Could not invoke RNFIrebaseAnalytics.logEvent of null is occuring when I called the firebase analytics. The version I am using is react-native-firebase v5+. Code is:

firebase.analytics().logEvent("event_name", { test: "test" });

Is there any issue with the code? @Salakar

**Comment by mikehardy** [comment]
You skipped the template, so I have no idea.
Here is how to integrate analytics correctly in v5 with react-native 0.59: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh#L82

Here is how you do it with v5 in rn60+: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh#L91 (I use the 'bill of materials' style in that demo, highly recommended)

Verify your integration is correct. Use `npx react-native-clean-project clean-project-auto` to clean things then re-install node_modules and pods and retry

If it still happens open a new issue *with the template*

**Comment by mdfateh** [comment]
Hi @mikehardy, I have attached a template of error, Kindly suggest a solution on this.

![Screenshot_1579690494](https://user-images.githubusercontent.com/46807685/72888645-f0c09200-3d33-11ea-9f68-97723f7279b0.png)

**Comment by SahilKKothari** [comment]
@mdfateh is your issue fixed?
