### ISSUE TITLE
Cloud Messaging pure data notification on iOS

### ISSUE THREAD

**Issue by Jobeso** [invertase/react-native-firebase#312]
Hey there,
first of all, thanks for that awesome library. I got everything to work with notification etc. My use case is that I want to receive data from my API and then display a local notification. I was not able to do this in the background on iOS.
What was possible is: 
- creating a local notification with data when the app is in foreground and then closed
- creating a remote notification ( with `notification: {title: "example"}`
- receiving the data when I open the app from the background, so I send the data when the app is in the background but only receive it when I open the app.

So what I mean is a payload without a notification object like this:
```
data: {
  id: "123"
  type: "text"
}
```

I did `firebase.messaging().requestPermissions()` and enabled in xcode background remote notifications and push notifications.

I got the feeling that this is not possible on iOS but I am not sure. So does somebody know if this works?

### Environment

1. Target Platform (e.g. iOS, Android):
iOS
2. Development Operating System (e.g. macOS Sierra, Windows 10):
macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
n/a
4. React Native version (e.g. 0.45.1):
0.46.4
5. RNFirebase Version (e.g. 2.0.2):
2.1.0

**Comment by Jobeso** [comment]
Don´t know if this is related but it also doesn't output the notification by clicking it. It logs `undefined`
```
firebase.messaging().getInitialNotification().then(notification => {
      console.log('Notification which opened the app: ', notification)
})
```

**Comment by Jobeso** [comment]
I solved the issue after a lot of struggle and will document this for others with the same issue. In your payload of the data you need to send message options (where you put priority) and set `contentAvailable`see [here](https://firebase.google.com/docs/reference/admin/node/admin.messaging.MessagingOptions)
example:
```javascript
var payload = {
  notification: {
    title: "Urgent action needed!",
    body: "Urgent action is needed to prevent your account from being disabled!"
  }
};
var options = {
  priority: "high",
  contentAvailable: true,
  timeToLive: 60 * 60 * 24
};
admin.messaging().sendToDevice(registrationToken, payload, options)
  .then(function(response) {
    console.log("Successfully sent message:", response);
  })
  .catch(function(error) {
    console.log("Error sending message:", error);
  });
```

**Comment by rtman** [comment]
@Jobeso 

Have you found a way to receive a notification when the app is killed using a data only payload? I can only seem to get it to work with a notification payload. When I use a data payload only I get notifications in the background and foreground.

**Comment by Jobeso** [comment]
@rtman As far as I can tell it is **not possible** to receive a data only payload **when the app is killed**. So we switched to send a notification payload and create our notification on the server.
