### ISSUE TITLE
firebase.auth().signInWithPhoneNumber() not working as expected on iOS

### ISSUE THREAD

**Issue by ImVaibhav1877** [invertase/react-native-firebase#3128]
Hello, i have try to sign in with phone number in react native(iOS) app but i have found with unexpected results
Here is the code:

`   if (this.validateInput()) {
      firebase.
        auth()
        .signInWithPhoneNumber('89384**303', true)
        //.signInWithPhoneNumber(this.state.mobilenumber)
        .then(confirmResult => {
          this.setState({ confirmResult })
        })
        .catch(error => {
          alert(error.message)
          console.log(error)
        })
    } else {
      alert('Invalid Phone Number')
    }
  }
`
SignInWithPhoneNumber( ) method expected two parameters ( '89384**303' , true ) found with  "Second argument "applicationVerifier" must be an implementation of firebase.auth.ApplicationVerifier"

![Screenshot 2020-01-24 at 12 51 18 PM](https://user-images.githubusercontent.com/58763716/73051237-4918a080-3ea8-11ea-9ebc-a93d5c284f0b.png)

**Comment by mikehardy** [comment]
If this is still an issue for you, please open a fresh issue following the template
