### ISSUE TITLE
RemoteMessage.data has incorrect type in version 5.x.x

### ISSUE THREAD

**Issue by ziyaddin** [invertase/react-native-firebase#3129]
## Issue

`data` property type of `RemoteMessage` is `Object`.

https://github.com/invertase/react-native-firebase/blob/e7e6d6f4cb3ea2d257896be0a314fce4ff3a7ff3/src/index.d.ts#L1275

Thus, when trying to get some custom property value from `RemoteMessage.data`

```js
console.log(message.data.my_custom_property);
```

it gives an error like

`Property 'my_custom_property' does not exist on type 'Object'. ts(2339)`

I think the correct type for `RemoteMessage.data` is `[key: string]: any`.

## Environment
`react-native-firebase` version: `5.5.6`.

**Comment by mikehardy** [comment]
Hi there! :wave:

If you wanted to propose a PR that aligned it with current RNFBv6 types, I can't see any reason not to approve+merge+release 

https://github.com/invertase/react-native-firebase/blob/master/packages/messaging/lib/index.d.ts#L101

In the meantime (while the PR is in process) can you make sure whatever you propose in the PR works, via applying it in your node_modules and using patch-package to make it persistent - that would qualify for me as testing

Thanks!

**Comment by ziyaddin** [comment]
> and using patch-package to make it persistent

I did not understand this part. Could you post a resource about this procedure?

**Comment by ziyaddin** [comment]
@mikehardy is it a good idea to mark the type of object property values as `string` (as in `{ [key: string]: string }`) instead of `any` (as in `{ [key: string]: any }`) ?

**Comment by mikehardy** [comment]
Looks like both @Ehesp and @Salakar get 'git blame' for that typing. I will assume they know what they are doing unless they comment here to the contrary, and they chose string for the values, I'd keep it that way pending any other information
