### ISSUE TITLE
App crash on startup - (libc++abi.dylib: terminating with uncaught exception)

### ISSUE THREAD

**Issue by creative-git** [invertase/react-native-firebase#313]
After installing the package, the app crash on startup 
xcode shows the following error:

![screen shot 2017-08-05 at 2 03 05 pm](https://user-images.githubusercontent.com/2705091/28994789-791d6226-79e7-11e7-8108-aedfa7ceea0e.png)

**libc++abi.dylib: terminating with uncaught exception of type NSException**

my pod file is ass follows: 
```
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'AppName' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppName

  target 'AppNameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    #'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    # Add any other subspecs you want to use in your project
  ]
end

```

### Environment
1. iOS
2. macOS Sierra
3. Xcode
4. React Native version: 0.44):
5. same issue in RNFirebase Version : 2.0.5 & 2.1.0

**Comment by barjas** [comment]
got it working, [https://github.com/invertase/react-native-firebase/issues/247](https://github.com/invertase/react-native-firebase/issues/247 )

looke like iOS pasting the file into the directory doesn't automatically add the file to the iOS project. You need to manually add it (which I only know how to do within XCode) by:

- Right click on your project
- Click "Add files to 'project name'"
- Select the .plist file
- Click ok

**Comment by simplenotezy** [comment]
What `plist` file did your import @barjas?

**Comment by camel113** [comment]
@simplenotezy  Probably the GoogleService-Info.plist

**Comment by jsgovea** [comment]
I am getting the same error, did you solve it?

**Comment by abuammar** [comment]
where could i fined GoogleService-Info.plist

**Comment by abuammar** [comment]
@simplenotezy where can i find  GoogleService-Info.plist file.

**Comment by abuammar** [comment]
@camel113 where can i find  GoogleService-Info.plist

**Comment by camel113** [comment]
@abuammar /ios/your-app/GoogleService-Info.plist

**Comment by gomezfe** [comment]
have u guys found a solution to this problem ?

**Comment by onka13** [comment]
I got these errors after deleting fabric keys in info.plist. Therefore I added again.
Here are the details; [https://fabric.io/kits/ios/crashlytics/install](https://fabric.io/kits/ios/crashlytics/install)

**Comment by Ehesp** [comment]
@gomezfe yes you need to add the file with xcode so it correctly links the file.

**Comment by jmeyers91** [comment]
I'm getting this error. I've confirmed that `GoogleServices-Info.plist` is added to the project (visible under "Link Binary with Libraries"). This is all xcode is telling me:

```
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

Here's my podfile:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AppName' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppName
  pod 'Fabric'
  pod 'Crashlytics'
  # Add new pods below this line
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  pod 'React', :path => '../node_modules/react-native', :subspecs =>
  [
    'Core',
    'RCTNetwork',
    'DevSupport'
  ]
  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation-android'
  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  target 'AppNameTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

And `AppDelegate.m`:

```
#import "AppDelegate.h"
#import <Firebase.h>
#import "RNFirebaseNotifications.h"
#import "RNFirebaseMessaging.h"

#import <Fabric/Fabric.h>
#import <Crashlytics/Crashlytics.h>

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  [RNFirebaseNotifications configure];

  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"AppName"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];

  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [Fabric with:@[[Crashlytics class]]];

  return YES;
}

- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [[RNFirebaseNotifications instance] didReceiveLocalNotification:notification];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
                                                       fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
  [[RNFirebaseMessaging instance] didRegisterUserNotificationSettings:notificationSettings];
}

@end

```

**Comment by scottmas** [comment]
I too am getting this error. The plist file is present and linked. It was caused after upgrading to the latest 5.1.1 version.

**Comment by partriv** [comment]
I am also getting this error...

**Comment by scottmas** [comment]
Per the comments on the other thread, I tried upgrading to Firebase 5.14.0 in my Podfile, but I got a new error this time (with RN Firebase 5.1.1.):
```
Module AppRegistry is not a registered callable module (calling runApplication)
```
The error goes away after reverting back to RN Firebase 5.0.0 and Firebase 5.6.0 in my Podfile.

**Comment by scottmas** [comment]
Screenshot from the error with Firebase 5.11.0:
![screen shot 2018-12-18 at 8 41 20 am](https://user-images.githubusercontent.com/2257337/50164763-c71b7880-02a0-11e9-9614-76b65e602935.png)

**Comment by NativLouie** [comment]
i have tried every combination ive seen and i still have issues. question...does it matter that my react native maps stuff is in the same target location as firebase?

**Comment by Salakar** [comment]
@scottmas interesting, looks like Analytics inside Firebase/Core potentially the issue, what does your Podfile.lock look like, specifically bit that mention Core / Analytics?

**Comment by scottmas** [comment]
The relevant parts only of my Podfile.lock:
```
PODS:
  - boost-for-react-native (1.63.0)
  - BoringSSL-GRPC (0.0.2):
    - BoringSSL-GRPC/Implementation (= 0.0.2)
    - BoringSSL-GRPC/Interface (= 0.0.2)
  - BoringSSL-GRPC/Implementation (0.0.2):
    - BoringSSL-GRPC/Interface (= 0.0.2)
  - BoringSSL-GRPC/Interface (0.0.2)
  - DoubleConversion (1.1.6)
  - Firebase/Auth (5.11.0):
    - Firebase/CoreOnly
    - FirebaseAuth (= 5.0.4)
  - Firebase/Core (5.11.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.3.0)
  - Firebase/CoreOnly (5.11.0):
    - FirebaseCore (= 5.1.6)
  - Firebase/Firestore (5.11.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (= 0.13.6)
  - Firebase/Storage (5.11.0):
    - Firebase/CoreOnly
    - FirebaseStorage (= 3.0.2)
  - FirebaseAnalytics (5.3.0):
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.3)
    - GoogleAppMeasurement (~> 5.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - "GoogleUtilities/NSData+zlib (~> 5.2)"
    - nanopb (~> 0.3)
  - FirebaseAuth (5.0.4):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.0)
    - GoogleUtilities/Environment (~> 5.2)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (5.1.6):
    - GoogleUtilities/Logger (~> 5.2)
  - FirebaseFirestore (0.13.6):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.1)
    - FirebaseFirestore/abseil-cpp (= 0.13.6)
    - "gRPC-C++ (~> 0.0.3)"
    - gRPC-ProtoRPC (~> 1.0)
    - leveldb-library (~> 1.20)
    - nanopb (~> 0.3.8)
    - Protobuf (~> 3.1)
  - FirebaseFirestore/abseil-cpp (0.13.6):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.1)
    - "gRPC-C++ (~> 0.0.3)"
    - gRPC-ProtoRPC (~> 1.0)
    - leveldb-library (~> 1.20)
    - nanopb (~> 0.3.8)
    - Protobuf (~> 3.1)
  - FirebaseInstanceID (3.3.0):
    - FirebaseCore (~> 5.1)
    - GoogleUtilities/Environment (~> 5.3)
    - GoogleUtilities/UserDefaults (~> 5.3)
  - FirebaseStorage (3.0.2):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.0)
    - GTMSessionFetcher/Core (~> 1.1)
```

**Comment by Salakar** [comment]
@scottmas can you try force `FirebaseAnalytics (= 5.3.0)` to version 5.4.0 by adding it to your Podfile with that version, pod installing and seeing how you get on?

**Comment by MrLoh** [comment]
@Salakar I am also encountering the issue, however I cannot add a version other than `FirebaseAnalytics 5.3`. Getting

```
CocoaPods could not find compatible versions for pod "FirebaseAnalytics":
  In Podfile:
    Firebase/Core (~> 5.11.0) was resolved to 5.11.0, which depends on
      FirebaseAnalytics (= 5.3.0)
```

**Comment by MrLoh** [comment]
@Salakar updating to `Firebase/Core 5.15.0` solved the issue for me. Is there any danger that Firebase Core and Messaging in 5.15.0 will cause issues with react-native-firebease?

**Comment by ryanhomer** [comment]
I'm trying to update to `Firebase/Core ~> 5.15.0` but I get:
>Specs satisfying the `Firebase/Core (~> 5.15.0)` dependency were found, but they required a higher minimum deployment target.

I've tried `platform :ios, '9.0'` as well as `10.0`, `11.0` and `12.0`

**Comment by NativLouie** [comment]
i tried Firebase/core 5.15.0 and react-native firebase 5.1.1 but it was completely unresponsive. this is the only set up that worked with react-native firebase 5.0.0.


>   pod 'Firebase/Core', '~> 5.6.0'
> 
>   pod 'Firebase/Auth'
> 
>   pod 'Firebase/Database'
> 
>   pod 'Firebase/Firestore'
> 
>   pod 'Firebase/Functions'
>

**Comment by bartolkaruza** [comment]
I'm was facing the `[RNFirebaseNotifications configure]: unrecognized selector sent to class` issue on react-native-firebase 5.1.1 with Firebase SDK at 5.15.0. After upgrading react-native-firebase to 5.2.1 the issue was resolved.

@Salakar Maybe close this issue thread as it is old and the title `libc++abi.dylib: terminating with uncaught exception` describes a generic native app startup crash. This issue will just pool things together that should be separate issues.

Anyone looking for a resolution, this is my crash free dependencies from pods and npm:

yarn.lock
```
...
react-native-firebase@5.2.1:
  version "5.2.1"
  resolved "https://registry.yarnpkg.com/react-native-firebase/-/react-native-firebase-5.2.1.tgz#2904ccc80880930ea72fa152eae3c7f53a0d5e1c"
  integrity sha512-fwr4P7Bm0c2bHSwYnSyKZNW9BxXLqswff0yS5Fl6hzIf7hbGD85m06qzD/6JAFpX3Jk8r4PGtYintWm26LiZ/Q==
  dependencies:
    opencollective-postinstall "^2.0.0"
    prop-types "^15.6.2"

...
```

Podfile.lock
```
...
- Firebase/Core (5.15.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.4.0)
  - Firebase/CoreOnly (5.15.0):
    - FirebaseCore (= 5.1.10)
  - Firebase/Messaging (5.15.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (= 3.2.2)
  - FirebaseAnalytics (5.4.0):
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.3)
    - GoogleAppMeasurement (= 5.4.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - "GoogleUtilities/NSData+zlib (~> 5.2)"
    - nanopb (~> 0.3)
  - FirebaseAnalyticsInterop (1.1.0)
  - FirebaseCore (5.1.10):
    - GoogleUtilities/Logger (~> 5.2)
  - FirebaseInstanceID (3.3.0):
    - FirebaseCore (~> 5.1)
    - GoogleUtilities/Environment (~> 5.3)
    - GoogleUtilities/UserDefaults (~> 5.3)
  - FirebaseMessaging (3.2.2):
    - FirebaseAnalyticsInterop (~> 1.1)
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.0)
    - GoogleUtilities/Environment (~> 5.2)
    - GoogleUtilities/Reachability (~> 5.2)
    - Protobuf (~> 3.1)
...
```

**Comment by zek** [comment]
I am trying to use 5.20.0 and I get the same error but 5.15.0 works fine

**Comment by Pravesh701** [comment]
Open Xcode and open AppDelagate.m
 import this
 #import <Firebase.h> 
add in starting of didFinishLaunchingWithOptions [FIRApp configure];

for example

#import <Firebase.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
//rest codes
}

**Comment by seamive** [comment]
Firebase 7.6.0 doesn't seem to work and throws the same errors, which is the latest Firebase that works with this?

Thanks!

**Comment by mikehardy** [comment]
Do not post on old issues.
Create new issues if you need to.
However, "Firebase 7.6.0" (I assume you mean firebase-ios-sdk pod release 7.6.0?) works fine as proved by our e2e ci tests, my app, and https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

strongly recommend trying the make-demo script out yourself to show it works, then you may compare with your project to see where things went wrong

**Comment by seamive** [comment]
@mikehardy https://github.com/invertase/react-native-firebase/issues/4935
