### ISSUE TITLE
Can Firebase Analytics track and show individual user actions?

### ISSUE THREAD

**Issue by claudioviola** [invertase/react-native-firebase#3141]
Hello dears

I already installed and set react-native firebase for my project.
Firebase analytics dashboard report many events either custom events and reserved events.

And now the question: Is it possible with firebase analytics get the log of single individual user.

I'm struggling to find a solution to allow me to log and analyze specific events for individual users.

Do you know if it's possible and how can I get it?

**Comment by mikehardy** [comment]
Hi there!

This not react-native-firebase specific, so I'm going to close it - but I intend to be helpful. The short answer is I think yes, but you'll need to set the user id / some unique identifier for the user in the analytics, then export it to BigQuery and do your analysis like that if I understand correctly.

That's how I do it anyway - the upstream / google documentation for analytics has mountains of docs as it's an old but vital product, I'd go check up there

**Comment by faizanbuggy** [comment]
@claudioviola I am also looking for the same question. Please tell if you have achieved ? and if yes, how ?
