### ISSUE TITLE
Mediation Test Suite

### ISSUE THREAD

**Issue by djpetenice** [invertase/react-native-firebase#3144]
Anyone know how to implement the Google Mediation test suite?
https://developers.google.com/admob/android/mediation-test-suite

**Comment by djpetenice** [comment]
If anyone is interested add this to app level build.gradle:

  implementation ('com.google.android.ads:mediation-test-suite:1.2.1') {
    exclude group: "com.google.android.gms" 
}

In MainActivity.java import the library:

import com.google.android.ads.mediationtestsuite.MediationTestSuite;

Add this to the onCreate function:

String appId = "ca-app-pub-xxxxxxxxxx~xxxxxxxxxx"; // APP ID FROM ADMOB
MediationTestSuite.launch(MainActivity.this, appId);

**Comment by Ehesp** [comment]
This is outside of Firebase really, we only support AdMob. Probably worth it's own module!

**Comment by djpetenice** [comment]
Well the implementation didn't work and I didn't know if it was down to how admob was implemented via this module. In reality there was a Google Play Services clash hence the group exclusion show in my comment.

**Comment by zyzo** [comment]
Hey I had the same need & ended up writing this recently https://github.com/BetOnYou/react-native-mediation-test-suite. Hope this helps !

**Comment by puckey** [comment]
@zyzo wow that is awesome - thanks!
