### ISSUE TITLE
ld: library not found for -lRNFIRMessaging [IOS]

### ISSUE THREAD

**Issue by kundanbasha** [invertase/react-native-firebase#3145]
## Issue

ld: library not found for -lRNFIRMessaging [IOS]
---

I have created android app using react-native-firebase, which is working fine. Now I going to create IOS app with same code, after I have done so much of configuration. I'm stuck at one bug related to the firebase. I'm unable to find the solution. If anyone have the solution please help and Thanks in advance!

#### `package.json`:

```json
  "dependencies": {
    "@react-native-community/netinfo": "3.2.1",
    "axios": "^0.18.0",
    "expo": "^34.0.4",
    "html-to-text": "^5.1.1",
    "normalizr": "^3.4.1",
    "prop-types": "latest",
    "qs": "^6.7.0",
    "react": "16.8.3",
    "react-dom": "^16.9.0",
    "react-native": "0.59.10",
    "react-native-background-color": "0.0.8",
    "react-native-document-picker": "^3.2.4",
    "react-native-exit-app": "^1.1.0",
    "react-native-firebase": "^5.5.6",
    "react-native-gesture-handler": "^1.0.5",
    "react-native-htmlview": "^0.14.0",
    "react-native-image-pan-zoom": "^2.1.11",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-modal": "^11.3.1",
    "react-native-offline": "^4.3.1",
    "react-native-render-html": "^4.1.2",
    "react-native-snackbar": "^2.0.2",
    "react-native-snap-carousel": "^3.8.4",
    "react-native-sound": "^0.10.12",
    "react-native-splash-screen": "^3.2.0",
    "react-native-star-rating": "^1.1.0",
    "react-native-switch": "^1.5.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-version-number": "^0.3.6",
    "react-navigation": "^3.9.1",
    "react-redux": "^7.0.2",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "~5.6.0",
    "redux-saga": "^1.0.2",
    "reselect": "^4.0.0",
    "rn-fetch-blob": "0.10.15",
    "socket.io-client": "^2.2.0",
    "styled-components": "^4.4.0",
    "uuid": "^3.3.3"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/runtime": "^7.4.5",
    "babel-jest": "^24.8.0",
    "babel-preset-react-native": "^4.0.1",
    "jest": "^24.8.0",
    "jest-react-native": "^18.0.0",
    "jetifier": "^1.6.5",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-native-svg-transformer": "^0.13.0",
    "react-test-renderer": "^16.8.3"
  },
```

### iOS
<details><summary>Click To Expand</summary>
<p>
platform :ios, '9.0'

target 'ChatgenAndroid' do
  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"

  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  pod 'Firebase/Core', '~> 6.13.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'

  pod 'RNExitApp', :path => '../node_modules/react-native-exit-app'

  target 'ChatgenAndroidTests' do
    inherit! :search_paths
  end

  post_install do |installer|
    system("mkdir -p Pods/Headers/Public/FirebaseCore && cp Pods/FirebaseCore/Firebase/Core/Public/* Pods/Headers/Public/FirebaseCore/")
    rnfirebase = installer.pods_project.targets.find { |target| target.name == 'RNFirebase' }
    rnfirebase.build_configurations.each do |config|
      config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
    end
  end

end

#### `AppDelegate.m`:

```objc
#import <Firebase.h>
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"ChatgenAndroid"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

React Native Environment Info:
    System:
      OS: macOS 10.15.2
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 21.55 MB / 8.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      npm: 6.13.4 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
- **`react-native-firebase` version:**
  - `5.5.6`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

**Comment by mikehardy** [comment]
Clone this repo, try this script https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh and it will run for iOS. It does *not* add messaging because everyone gets that wrong and there is not enough time in the world to fix all of it unfortunately. But if you read the script (it has comments explaining what happens) then you can follow the examples from all the other modules to do the same thing for messaging. And it should work.

Once you've proven it works, then you can examine your project again and hopefully find what went wrong.

But it's not a problem with the module so we can't really reproduce it to help, sorry
