### ISSUE TITLE
Please help me sir, I want to use multiple resize-image extension functions in one bucket

### ISSUE THREAD

**Issue by saeromCho** [invertase/react-native-firebase#3155]
[**Question**]

To set different sizes for each type of image (for example, user-profile-image, post-thumbail-image), 
**Is it correct to set multiple resize-image extension functions in one bucket** of firebase storage?
If not, what if there's another solution?
If anybody know this issue, I'd **really appreciate** it.

[**Issue** ] 

Let me first explain my issue on the premise that it is right to create multiple resize-image extension functions in one bucket.
For example, my firebase storage bucket has two types: profile folder and thumbnail folder.
The folder in which each will contain the images to be resized.
In the profile folder resizes the image with 100X100, 340X250 and in the thumbnail folder, I set the extension function to resize the image to 400X500, 780X920.
When I upload **post-thumbnail-image**, I want to upload only to the thumbnail folder, but if I upload a file to root, the image is uploaded to the resizing value set in both profile folder and thumbnail folder.
I want to **upload** post-thumbnail-image **only to thumbnail folder**(I want to prevent uploading in profile folder). What can I do to fix it?
What can I do to fix it?

Please help me sir and my bros.

Thank you very much for reading the long article :)

**Comment by Ehesp** [comment]
Hey @saeromCho are you in the right repository? Sounds like you're using https://github.com/firebase/extensions?

**Comment by saeromCho** [comment]
@Ehesp 
Hi Guy! hanks for the reply. I think the git repository you told me is a better place to solve my questions and issues.
Thank you!
