### ISSUE TITLE
This document does not exist, it will not appear in queries or snapshots

### ISSUE THREAD

**Issue by ashokadichill** [invertase/react-native-firebase#3156]
## Issue
We are trying to use Firebase cloud firestore DB.
We are having db structure as nested collection and documents.
We cant able to insert a new document with the nested collection structure.

Collection Doctor / Document MobileNumber
         Collection Slot
              Document SlotName
                   Collection Date
                       Document Appointment

```
this.slotref = Firebase.firestore().collection('DOCTOR').doc("9090909090").collection("Slot").doc("12:30PM-12:40PM").collection("31-1-2020")
        this.slotref.add({})
        .then((data) => {
            console.log("new slot added successfully", data)
        }).catch( (err) => { console.log("error", err) })
```

```

_documentPath: Path
id: (...)
isDocument: (...)
isCollection: (...)
relativeName: (...)
_parts: Array(6)
0: "DOCTOR"
1: "90909090"
2: "Slot"
3: "12:30PM-12:40PM"
4: "31-1-2020"
5: "xiWqkNW7f1R9q0XyzI6T"
length: 6
__proto__: Array(0)
__proto__: Object
```

Firestore gives the response as added successfully
When opening firebase console the data is inserted as italic font and it gives the description

This document does not exist, it will not appear in queries or snapshots

---
### Project Files

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
{
  "name": "atRate",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/datetimepicker": "^2.1.0",
    "@react-native-community/geolocation": "^2.0.2",
    "lodash": "^4.17.15",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-code-push": "^5.6.0",
    "react-native-firebase": "^5.6.0",
    "react-native-geocoder": "^0.5.0",
    "react-native-geolocation-service": "^3.1.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-image-picker": "^1.1.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-radio-buttons-group": "^1.0.7",
    "react-native-size-matters": "^0.3.0",
    "react-native-snap-carousel": "^3.8.4",
    "react-native-svg": "^10.0.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-swiper": "^1.5.14",
    "react-navigation": "^3.11.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-persist": "^5.10.0",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.7.7",
    "@babel/runtime": "^7.7.7",
    "@types/jest": "^24.0.24",
    "@types/react": "^16.9.16",
    "@types/react-native": "^0.60.25",
    "@types/react-test-renderer": "^16.9.1",
    "babel-jest": "^24.9.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.57.0",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native",
    "testMatch": [
      "<rootDir>/Tests/**/*.js",
      "**/?(*.)(spec|test).js?(x)"
    ],
    "moduleNameMapper": {
      "^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "identity-obj-proxy"
    }
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

target 'sample' do
  rn_path = '../node_modules/react-native'
   pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
   pod 'React', path: rn_path, subspecs: [
     'CxxBridge',
     'DevSupport',
     'RCTImage',
     'RCTLinkingIOS',
     'Core'
   ]
 
   pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
   pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
   pod 'RNGestureHandler', :path => "../node_modules/react-native-gesture-handler"
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  
  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-geocoder', :path => '../node_modules/react-native-geocoder'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
    
    targets_to_ignore = %w(React yoga)
    
    if targets_to_ignore.include? target.name
        target.remove_from_project
    end
    
  end
end

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
      Memory: 134.05 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [] iOS
  - [] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - FireStore
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Have you tried adding some meaningful data? `this.slotref.add({})` - not an empty object. Not sure you can have an empty object document.

**Comment by ashokadichill** [comment]
@Ehesp 
Yes tried same thing no impact on the firebase console this.slotref.add({})

**Comment by brokercl** [comment]
### this code copied from document respond requested document don't exist
but exist in Firestore and I don't know why?

  checkIfExistUserDocInFirestore(user) {
    FirebaseFirestore.instance
    .collection('users')
    .doc(user.uid)
    .get()
    .then((documentSnapshot) {
      if (documentSnapshot.exists) {
        printOk('exist');
      } else {
        printError('DONT exist, sorry');
        printInfo('documentSnapshot.reference.path ${documentSnapshot.reference.path}');
      }
    },
    );
  }
