### ISSUE TITLE
"You attempted to use "firebase.app('[DEFAULT]').utils" but this module could not be found"

### ISSUE THREAD

**Issue by rafameyer** [invertase/react-native-firebase#3159]
I don't know about it

My specs:
react-native -> 0.61.5 
@react-native-firebase/app -> 6.0.2
@react-native-firebase/analytics -> 6.0.2

<img width="361" alt="Screen Shot 2020-01-31 at 11 31 56" src="https://user-images.githubusercontent.com/22173714/73536318-8edfe680-441d-11ea-9cfd-e242f2d8455b.png">

**Comment by mikehardy** [comment]
no template, sorry

You can see a full fledged example here though, it runs: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh
