### ISSUE TITLE
Enable ML Kit Translation (Commented out?)

### ISSUE THREAD

**Issue by RuairiOliver** [invertase/react-native-firebase#3161]
Hi,

Thanks for all the work on this library, v6 is great to work with.

I'm just wondering can ML Kit translation be enabled? Looks like all the code is there but commented out saying SDK 6 is needed. 
https://github.com/invertase/react-native-firebase/pull/2117

Is this library not already on SDK 6?

Thanks

**Comment by Salakar** [comment]
@RuairiOliver at the time of the v6 release of RNFB the Firebase iOS SDK was on v5 and translate APIs weren't yet supported iirc. So we held off adding support for it in v6 RNFB and commented out the Android code for the initial release.

We plan to add this in for v7

**Comment by RuairiOliver** [comment]
Thanks @Salakar

**Comment by lhk** [comment]
@Salakar is there a (rough) timeline for this?

I looked at the npm version history. You seem to have gone from 0.1 to 0.5 in a month and then to 6.0 in another month. Is v7 more like a month or a year away?

**Comment by Ehesp** [comment]
@lhk Versions 1-4 were on the `react-native-firebase` package, but allow them to be broken up into separately installable modules (which was highly requested) we moved v6 to the `@react-native-firebase` organisation, and used the `0.1` as the "alpha" state of v6.

Not sure on a timeline yet though.

**Comment by mikehardy** [comment]
ML undergoing large scale re-factor now
