### ISSUE TITLE
Documentation clarity on setting up additional services

### ISSUE THREAD

**Issue by TheSavior** [invertase/react-native-firebase#3162]
## Documentation Feedback

I'm trying to set up [instructions for setting up `analytics`](https://invertase.io/oss/react-native-firebase/v6/analytics/quick-start) and find the documentation a bit unclear.

<img width="1001" alt="Screen Shot 2020-02-01 at 1 16 24 PM" src="https://user-images.githubusercontent.com/249164/73599161-4b58ab80-44f5-11ea-901b-b0eca8728708.png">

It wasn't clear to me on initial read whether I needed both `/app` and `/analytics` or if `/app` included in the `/analytics` module. Or whether that first sentence was a typo that meant to say `/analytics` as well.

I think this could be made more clear by putting "This module depends on the @react-native-firebase/app module. To get started and install app, visit the project's quick start guide." inside a box that makes it clear it isn't part of the guide for setting up analytics, but a note of a prerequisite. Maybe something like this

<img width="1068" alt="Screen Shot 2020-02-01 at 1 20 41 PM" src="https://user-images.githubusercontent.com/249164/73599195-b4d8ba00-44f5-11ea-8881-b58889d77d73.png">

**Comment by Ehesp** [comment]
Without wanting to sound rude, it literally states the exact steps required in order to install the module - documentation is there to read, rather than skip to the parts with the code blocks. 

I'm not a fan of the blue blocks to be honest, I think it'd be more obvious if `yarn add @react-native-firebase/app` was added above the analytics import line. 

At some point we'll revist the docs flow. In hindsight the "module sections" would be better for pure usage, and the installation sections would be all in the same place.

**Comment by TheSavior** [comment]
No worries, feel free to do what you think is best. 

I got tripped up on this page trying to figure out what to do and it required reading it much closer in order to post this issue. I just wanted to share that snag in case others feel the same confusion (this is my first time using react-native-firebase). 

Feel free to close if you think this is fine

**Comment by Ehesp** [comment]
https://github.com/invertase/react-native-firebase/issues/3217

**Comment by Ehesp** [comment]
Hey @TheSavior - the updated docs site now has some notes about this, to hopefully make it clearer about the dependency on app: https://rnfb-docs.netlify.com/analytics/usage

I'll close this off, as we'll do the same for each module as we get to them.

**Comment by TheSavior** [comment]
Thanks, this is much clearer to me when scanning!
