### ISSUE TITLE
Broken link to iOS setup for Crashlytics

### ISSUE THREAD

**Issue by TheSavior** [invertase/react-native-firebase#3163]
## Documentation Feedback

The iOS additional steps link on the page for Crashlytics setup: https://invertase.io/oss/react-native-firebase/v6/crashlytics/quick-start links to https://invertase.io/oss/react-native-firebase/v6/crashlytics/ios-setup which is a broken link.

<img width="470" alt="Screen Shot 2020-02-01 at 11 25 41 PM" src="https://user-images.githubusercontent.com/249164/73604723-2d696600-454a-11ea-855a-d56dcc895c83.png">

The equivalent Android link seems to work: https://invertase.io/oss/react-native-firebase/v6/crashlytics/android-setup

It looks like this file doesn't exist in the docs folder: https://github.com/invertase/react-native-firebase/tree/master/docs/crashlytics

**Comment by TheSavior** [comment]
Looks like it was deleted three days ago in this commit https://github.com/invertase/react-native-firebase/commit/0bd1f54d522b74ade5f9e14fb463704d6049d4bb#diff-68cda6c0b48d0dff2cbe40b0d5007aa5

cc @Salakar

**Comment by Salakar** [comment]
I moved these docs to the manual steps guide as these were only required if you  weren't using auto linking. https://invertase.io/oss/react-native-firebase/v6/crashlytics/ios

I thought I removed all references to the link, sorry, could you link to the page that mentions this page and I can sort it, thanks.

**Comment by TheSavior** [comment]
👍 yep, this one. https://invertase.io/oss/react-native-firebase/v6/crashlytics/quick-start

**Comment by Salakar** [comment]
Cool, thanks for the link, have removed it now 👍
