### ISSUE TITLE
(:fire:) Image upload broken after switching from Firebase to RNFirebase

### ISSUE THREAD

**Issue by Tinmania2018** [invertase/react-native-firebase#3164]
## Issue

I am switching from the Firebase package to RNFirebase because with this package I could add more functionality using this single package in stead of installing different packages for every new function I would like to use. 

However when switching to RNFirebase my image upload function is broken. I receive the error; storageRef.putString is not a function. 

I believed that RNFirebase is based in Firebase and therefor the uploading of images should work as before? 

The issue is with Android and IOS, but focus on IOS for fixing the issue. 

Below is the uploadImages code. This takes an image array selected with react-native-image-crop-picker, and for every image in the array it takes the base64 value and tries to upload this. This worked without a problem using the Firebase package. 

```
    uploadImages = () => {
        const provider = firebase.database().ref(`providers/${uid}`);
        console.log(photos)
        return Promise.all(photos)
            .then(photoarray => {
                console.log('all responses are resolved successfully');
                // take each photo, upload it and then return it's download URL
                return Promise.all(photoarray.map((photo) => {
                    let file = photo.data;
                    const path = "Img_" + uuid.v4();
                    const storageRef = firebase
                        .storage()
                        .ref(`theft/${uid}/${path}`);
                    let metadata = {
                        contentType: 'image/jpeg',
                    };

                    // upload current photo and get it's download URL
                    return storageRef.putString(file, 'base64', metadata)
                        .then(() => {
                            console.log(`${path} was uploaded successfully.`);
                            return storageRef.getDownloadURL()
                                .then(fileUrl => ({ uri: fileUrl }));
                        });
                }));
            })
            .catch((err) => {
                console.error(err);
            });
    };
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
  #react-native-firebase
  pod 'Firebase/Core', '~> 6.13.0'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Database', '~> 6.13.0'
  pod 'Firebase/Storage', '~> 6.13.0'```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.15.2
      CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
      Memory: 1.87 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.8.1 - /usr/local/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.11.2 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 25.0.1, 26.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.1
        System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1```

<!-- change `[ ]` to `[x]` to select an option(s) -->

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ X] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `5.5.0` (Cannot use newer version because of other packages, using the latest 5.5 version failed)
- **`Firebase` module(s) you're using that has the issue:**
Database and Storage? 
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>


<!-- Thanks for reading this far down ❤️  -->
<!-- High quality, detailed issues are much easier to triage for maintainers -->

<!-- For bonus points, if you put a 🔥 (:fire:) emojii at the start of the issue title we'll know -->
<!-- that you took the time to fill this out correctly, or, at least read this far -->

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Need some errors or something to work with please?

**Comment by Tinmania2018** [comment]
![Screenshot 2020-02-02 at 12 37 51](https://user-images.githubusercontent.com/41525036/73607631-d64eaa00-45b8-11ea-9907-2a4d1aa14d03.png)

I receive this error when trying to upload. That the storageRef.putString is not a function.

**Comment by Ehesp** [comment]
Which RNFB version are you using?

**Comment by Tinmania2018** [comment]
This is shown under the OP however under the folded in Javascript part. I'm using 5.5.0 because of React-Native 59.x and newer versions break another package. (that's why I want to move to RNFirebase). 

- **`react-native-firebase` version you're using that has this issue:**
  - `5.5.0` (Cannot use newer version because of other packages, using the latest 5.5 version failed)
- **`Firebase` module(s) you're using that has the issue:**
Database and Storage?

**Comment by mikehardy** [comment]
You're stuck between a rock and a hard place with versions I think. In order to support iOS13 well (that is to say: without crashing) with the firebase packages you'll need a version of RNFB that is current enough to support the newest firebase SDKs, and that implies react-native 0.59.3 or newer. I would first focus effort on being able to use RNFBv6, which implies react-native 0.60+, then efforts here won't be in vain, as RNFBv5 is in maintenance mode and if there are serious storage-related issues they'll receive attention on the RNFBv6 branch but (as the only person doing v5 releases) I'm not interested in heavy work on the v5 branch. Alternatively, if you can show the actual problem (with a minimal reproducible example) and a PR that is clean+small with no backwards-compatibility issues for current v5 installed base, it's maybe merge-worth on v5, but that all seems like time malinvestment to me vs getting current.

**Comment by Tinmania2018** [comment]
I think it was the react-native-admob package that interfered with the RNFirebase package. So I now copied back a backup before the Admob package was installed and I am trying to install RNFBv6 with RN 59.10. 

See if I can get it to work and upload images as it was before using RNFB. Will get back to you with the results.

**Comment by mikehardy** [comment]
RNFBv6 and RN59 aren't going to be fun, you will be afoul of the required versions https://invertase.io/oss/react-native-firebase/v6#supported-versions

**Comment by Tinmania2018** [comment]
@mikehardy I noticed this as well indeed. I also saw that the notifications are stripped out of RNFBv6 and something about the rewardedads being replaced with Native ads. 

Notifications and rewarded ads are just the thing that I wanted to use RNFB for. So I started yesterday evening with installing 5.5.7 (without any problems now because I uninstalled react-native-admobs package). I'm hoping that this uploads images without a problem. If it doesn't I'm keeping the firebase package for my image uploading and RNFB for the notifications and admobs, hopefully that will work well enough for me to release my app and seeing if people will start working with it and see if it is worth the time to further work on updating everything by then.

**Comment by Tinmania2018** [comment]
5.5.7 also didn't work. Reverted to using the Firebase package for uploading photo's and trying to use Admob and notifications using rnfirebase for now.

**Comment by Egehanozsoy** [comment]
Just use the official firebase storage module for this one. I've tried for around 5-6 hours to get this one working but no results.

Here's the final function
``
uploadPicture = async (pictureUri, path) => {
        const storage = getStorage()
        let reference = await ref(storage, path)
        const blob = await (await fetch(pictureUri)).blob()
        console.log(blob)
        await uploadBytes(reference, blob, {
            contentType: 'image/png'
        })
        const downloadUrl = await getDownloadURL(reference)
        return downloadUrl
    }
``
