### ISSUE TITLE
BannerAd docs not working on desktop browser, functioning on mobile

### ISSUE THREAD

**Issue by JakeHadley** [invertase/react-native-firebase#3166]
## Documentation Feedback

I've seen recently different functionality on mobile vs desktop for some reason. Not sure if it's just me or if this is actually an issue, but I thought I'd show what I'm seeing. The link in question is https://invertase.io/oss/react-native-firebase/v6/admob/reference/bannerad. Screenshot from mobile:
![Screenshot_20200202-105907](https://user-images.githubusercontent.com/35585841/73613528-84535780-45ab-11ea-8c53-b53ae62d5461.jpg)
Screenshot from desktop:
![Screenshot_20200202-105852](https://user-images.githubusercontent.com/35585841/73613530-8fa68300-45ab-11ea-91d8-8a2e96c2804b.jpg)
Not much to reproducing this issue I guess. I don't really know if it's just me, but I do know I haven't ever been able to see this particular set of very necessary docs (to me at least) for a long time...

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Strange. I just clicked the link on desktop, works fine, can't reproduce

**Comment by JakeHadley** [comment]
Really dumb then. Might just be my network. I tried on another computer just now, same result. No go. I might try at my work computer tomorrow to see also.

**Comment by mikehardy** [comment]
Always have a VPN handy for comparison (and e.g. SSH being blocked by crappy networks making development impossible...). I think Firefox has one for free now.

**Comment by JakeHadley** [comment]
I just tried on Safari on my mac and it worked. Trying from Chrome did not...

**Comment by Ehesp** [comment]
Ad block sometimes causes issues with the content on that page.

**Comment by JakeHadley** [comment]
Oh that would make sense.
