### ISSUE TITLE
When App killed, on receive notification cant view it.

### ISSUE THREAD

**Issue by uendar** [invertase/react-native-firebase#3167]
I am using 
```
firebase.notifications().onNotificationOpened((notificationOpen) => {
   
  });
```
to open the notification when received. It works on componentDidMount() when app is in background.

While app is killed it does not work. How can we open the exact notification when app is killed ?

**Comment by mikehardy** [comment]
No template.

But you might like this https://github.com/invertase/react-native-firebase/issues/3095
