### ISSUE TITLE
Crashlytics does not communicate with Firebase servers

### ISSUE THREAD

**Issue by SMJ93** [invertase/react-native-firebase#3168]
## Issue

First of all, great works with the docs and improvements! I used this library a couple of years ago and it has come a long way! Nice one guys 👏 

I've got Analytics setup and working on both iOS and Android across different build environments. Then I moved onto Crashlytics, easy to setup on Android, but iOS doesn't seem to be connecting to the Firebase servers.

According to the [latest docs](https://invertase.io/oss/react-native-firebase/v6/crashlytics/quick-start) it should work automatically using RN auto install on iOS. Everything looks to be installed correctly -  I can see the `[CP-User] [RNFB] Crashlytics Configuration` script in xcode.

I've tried running it in release mode, debug mode, cleaned everything, reinstalled, but still nothing works:

![Screenshot 2020-02-03 at 13 32 41](https://user-images.githubusercontent.com/2145641/73657543-627cd200-468a-11ea-94bf-dd563cafb901.png)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
Dependencies:
- Node: v12.9.1
- yarn: 1.21.1
- "@react-native-community/async-storage": "1.7.1",
- "@react-native-firebase/analytics": "6.2.0",
- "@react-native-firebase/app": "6.2.0",
- "@react-native-firebase/crashlytics": "6.2.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "crashlytics_debug_enabled": true
  }
}

```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
Nothing shows in Podfile as its automatically installed / linked with RN
Podfile.lock:
- COCOAPODS: 1.8.4
- RNFBCrashlytics (6.2.0):
    - Crashlytics (~> 3.12.0)
- Crashlytics (3.12.0):
```

#### `AppDelegate.m`:

```objc
// inside  didFinishLaunchingWithOptions
[FIRApp configure];
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

Android is fine

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 376.07 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.9.1 - ~/.nvm/versions/node/v12.9.1/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v12.9.1/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.9.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 26.0.1, 26.0.3, 27.0.3, 28.0.0, 28.0.3, 29.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 6.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Crashlytics`
- **Are you using `TypeScript`?**
  - `Y` & `3.7.2`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I'm not sure that's a reliable indicator. 
I just tested this on purpose myself, recently by invoking their crash method
predictably it silent-fails without having matching dsyms, but when I load them up (and make sure I'm running e.g. the TestFlight binary that corresponds) then it works fine.
That's non-trivial though - getting the dSYMs right, c.f. https://stackoverflow.com/questions/54577202/how-to-run-upload-symbols-to-upload-dsyms-as-a-part-of-xcode-build-process/55796619#55796619

**Comment by SMJ93** [comment]
Thanks @mikehardy i'll take a look!
