### ISSUE TITLE
Notification Listener not working in v6

### ISSUE THREAD

**Issue by Ritesh175862** [invertase/react-native-firebase#3169]
async createNotificationListeners(callbackFun = () => { }) {
        /*
        * Triggered when a particular notification has been received in foreground
        * */
        this.notificationListener = firebaseIns.notifications().onNotification((notification) => {
            const { title, body } = notification;
            callbackFun(title, body, notification);

            this.showAlert(title, body);
        });

this.notificationOpenedListener = firebaseIns.notifications().onNotificationOpened((notificationOpen) => {
            const { title, body } = notificationOpen.notification;
            callbackFun(title, body, notification);
            this.showAlert(title, body);
        });

        /*
        * If your app is closed, you can check if it was opened by a notification being clicked / tapped / opened as follows:
        * */
        const notificationOpen = await firebaseIns.notifications().getInitialNotification();
        if (notificationOpen) {
            const { title, body } = notificationOpen.notification;
            callbackFun(title, body, notification);
            this.showAlert(title, body);
        }
        /*
        * Triggered for data only payload in foreground
        * */
        this.messageListener = firebaseIns.messaging().onMessage((message) => {
            //process data message
            console.log(JSON.stringify(message));
            callbackFun("", JSON.stringify(message), null);
        });
    }

**Comment by Ehesp** [comment]
Please follow the issue template. You say v6 but code is v5??
