### ISSUE TITLE
RN Firebase V6 - Notification

### ISSUE THREAD

**Issue by dhevendhiran-adt** [invertase/react-native-firebase#3170]
Hi,
We would like to use RNFirebase V6 Crashlytics in our app for JS stack traces. But the Notification library not yet released with V6. We are looking for this release for the last three months. 
But now this tracker issue [https://github.com/invertase/react-native-firebase/issues/2566] also closed.
It is better for us to know the approximate month when we can expect this V6 Notification library to be published.
Thanks.

**Comment by radko93** [comment]
There won't be a notification module in react-native-firebase, you can read about it in the issue you've linked.

**Comment by Ehesp** [comment]
As mentioned in the issue linked, we moved Notifications away from RNFB. We've been working for the last 5/6 months on [Notifee](https://notifee.app). If that doesn't suit your needs, you can integrate messaging with other [alternative solutions](https://notifee.app/react-native/docs/overview#alternative-solutions).
