### ISSUE TITLE
Remote Notifications Not Supported in Simulator

### ISSUE THREAD

**Issue by wincod75** [invertase/react-native-firebase#3174]
Possible Unhandled Promise Rejection (id: 1):
Error: [messaging/unknown] remote notifications are not supported in the simulator
NativeFirebaseError: [messaging/unknown] remote notifications are not supported in the simulator

"react": "16.9.0",
"react-native": "0.61.5",

Anyone else experiencing this, how to resolve?

**Comment by Ehesp** [comment]
You need to use a test device, this is an Apple limitation.

**Comment by Gustash** [comment]
The simulator on xcode 11.4 now supports remote push notifications. Can we add support for this? It's annoying not being able to use this feature now.

**Comment by Ehesp** [comment]
@Gustash that's not how it works sorry, it supports dragging a "message file" into the simulator which it handles as a "remote message".

**Comment by Gustash** [comment]
Ah, I see. Thanks for the clarification. Btw, is there a good way to disable the error letting me know I can't register on a simulator? I'd like to disable it without adding extra JS logic in production

**Comment by mikehardy** [comment]
I thought there was some command line magic you could run as well? Not just drag and drop? May not advance the request per se but as an idea if it were possible to automate it that's better, and I think it is. It's on my list of things to play with

**Comment by Ehesp** [comment]
Honestly I've not upgraded yet. We have real devices to test on so haven't had the need to try - it's low on our priority list so any help/investigation/PRs are welcome.

**Comment by ehijon** [comment]
@Gustash @wincod75 Did you find a work around for be able to continue working on the simulator?
What did you do for remove this warning?

**Comment by Gustash** [comment]
I haven't removed the warning, but I do feel it doesn't need to be there and should be removed, as after the first time we don't need to be told again

**Comment by mikehardy** [comment]
Something like this is what you want if it's just one of those yellow-box warnings at the bottom:
```typescript
import { YellowBox } from 'react-native';
YellowBox.ignoreWarnings(['Animated', 'Battery state', 'GeolocationService::onError - ERROR - ']);
```

Those are the 3 I'm ignoring right now, alter that array to suit your project

**Comment by Gustash** [comment]
I've tried this. It doesn't work because it's an actual error message and not a YellowBox warning. Maybe we should move it to a YellowBox, it seems more fitting and would give people the option to ignore it @Ehesp

**Comment by mtoninelli** [comment]
> ```ts
> 'Animated'
> ```

Thank you mike, where I can find the warning name to add in ignoreWarnings array?

**Comment by mikehardy** [comment]
@mtoninelli for actual warnings, its sort of a regex based on whatever is showing up in the yellow warning box, but per @Gustash above it sounds like this strategy won't work here. So it's a useful trick in general but does not seem like it will solve the issue here, sorry

**Comment by tomsiwik** [comment]
Quick solution for the curious like me who found this thread and wanted to get rid of the fatal red error:

```javascript
import { isEmulator } from 'react-native-device-info';
import PushService from '...';

if (!isEmulator() && Platform.OS !== 'ios') {
  PushService.init()
}
```

This way you can leave capabilities and native modules untouched (in case you don't initialize in obj-c code itself)

**Comment by Gustash** [comment]
> Quick solution for the curious like me who found this thread and wanted to get rid of the fatal red error:
> 
> ```javascript
> import { isEmulator } from 'react-native-device-info';
> import PushService from '...';
> 
> if (!isEmulator() && Platform.OS !== 'ios') {
>   PushService.init()
> }
> ```
> 
> This way you can leave capabilities and native modules untouched (in case you don't initialize in obj-c code itself)

Couple issues with that approach:

1. You're adding overhead on production for no reason, you know you won't be running a simulator at that point so you shouldn't do those checks if they're unnecessary. 

2. I still can't test local notifications on a simulator with that, but they're fully capable of handling those. This is why I think that error is completely unnecessary

**Comment by mikehardy** [comment]
@Gustash 

> any help/investigation/PRs are welcome.

**Comment by RaviRajaJangid** [comment]
> You need to use a test device, this is an Apple limitation.

Now Simulator supporting Push notification

**Comment by mikehardy** [comment]
@RaviRajaJangid yes, as a manual drag and drop. But does it test that you can properly construct the JSON and get through the FCM and APNS servers? That's a significant part of the testing effort, so the drag-n-drop part isn't great yet. If it had been programmatically possible it would have at least allowed for automated testing and have been more interesting

**Comment by ghasemikasra39** [comment]
I have been waiting for this for about a year. Can someone confirm that `React Native firebase push notification` works in a `bare-workflow react-native (NOT EXPO) project` using `ios simulator` on the latest `xcode` ?

**Comment by mikehardy** [comment]
@ghasemikasra39  How did it work when you tested it? in my experience it will work with the *testing* flow, where you drop a message on the simulator. It won't receive them from the cloud. Please test and confirm and report back

**Comment by alfosuag** [comment]
@ghasemikasra39 @mikehardy 

By today, I'm testing on `xcode 11.7` and `ios simulator: iPhone 11/iOS 13`, also using `react-native-push-notification` and `@react-native-community/push-notification-ios`. And nope, it says remote notifications are not supported. I only can drop on the file-based payload into it.

**Comment by mikehardy** [comment]
Upgrade to current stable xcode. And it never will work on the simulator. The simulator for ios is not a real machine with real address and will never be able to generate a token so is not addressable. Also json differences have been noted in delivery between real devuces and simulation even with drag and drop. Do not waste your time testing FCM on simulator

**Comment by SilenceCodder** [comment]
Read this

https://firebase.flutter.dev/docs/messaging/apple-integration/
