### ISSUE TITLE
ref.where query doesn't work with FieldPath (v 6.2.0)

### ISSUE THREAD

**Issue by ahanusek** [invertase/react-native-firebase#3178]
## Issue

Hi, I have a problem because it seems that react-native-firebase doesn't properly handle ref.where with FieldPath. Below code works perfectly fine with firebase js sdk, but with @react-native-firebase/firestore v.6.2.0 this query return always an empty array
Someone can give me a hint about how to deal with this?

Describe your issue here

---

### Javascript

       const fieldEmailPath = new firestore.FieldPath('users', user.email);
      
       ref
      .where('room', '==', roomId)
      .where(fieldEmailPath, '==', true)
      .onSnapshot(
        (snapshot) => {
          const list = snapshot.docs.map(doc => doc.data());
         console.log(list)
        },
        (error) => {
          console.log('error', error);
        }
      );

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/analytics": "^6.2.0",
"@react-native-firebase/app": "^6.2.0",
"@react-native-firebase/auth": "^6.2.0",
"@react-native-firebase/firestore": "^6.2.0",
"@react-native-firebase/functions": "^6.2.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - ` 6.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y` & `3.7.5`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Hey - could you try the following and see if it works?

```
ref
  .where('room', '==', roomId)
  .where(`users.${user.email}`, '==', true)
  .onSnapshot(
    (snapshot) => {
      const list = snapshot.docs.map(doc => doc.data());
     console.log(list)
    },
    (error) => {
      console.log('error', error);
    }
  );
```

If that works, there could be an issue with the FieldPath not converting. If it doesn't I'll try and replicate.

**Comment by ahanusek** [comment]
No, it doesn't work even with firebase js sdk in my react app, I think that firebase only supports the use of FieldPath when you want to check a nested field.

**Comment by Ehesp** [comment]
Eh interesting, swear I've done it that way a few times myself. I'll see if I can repro.

**Comment by Ehesp** [comment]
Found the problem..

Basically we were sending a string version of the field path over to native, so `['users', 'foo.bar@gmail.com']`was turning into `users.foo.bar@gmail.com`.

On native, this created the fieldpath `['users', 'foo', 'bar', '@gmail`, `com`]. It's now passing the array version over and creating a native field path.

**Comment by ahanusek** [comment]
@russellwheatley  @Ehesp 

After upgrade to 6.3.2 all query with .where return error (even without field path)

`ref
      .where('workspaceId', '==', workspaceId)
      .onSnapshot(
        snapshot => {
          const list = snapshot.docs.map(doc => doc.data() as Project);
          console.log(list)
        },
        (error: Error) => {
          console.log(error)
        }
      );`

![Zrzut ekranu 2020-02-11 o 11 30 43](https://user-images.githubusercontent.com/16654786/74229123-0c2f1500-4cc2-11ea-9539-674c7c2e9a3d.png)

**Comment by Ehesp** [comment]
Bah what! Tests were passing... let me check
