### ISSUE TITLE
error while working with Firebase and please solve this

### ISSUE THREAD

**Issue by vammu920** [invertase/react-native-firebase#3180]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/vamsi/Desktop/sample/node_modules/@react-native-firebase/admob/android/build.gradle' line: 44

* What went wrong:
A problem occurred evaluating project ':@react-native-firebase_admob'.
> Could not read script '/Users/vamsi/Desktop/sample/node_modules/@react-native-firebase/app/android/firebase-json.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':@react-native-firebase_admob'.
> compileSdkVersion is not specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

    at checkExecSyncError (child_process.js:621:11)
    at execFileSync (child_process.js:639:15)
    at runOnAllDevices (/Users/vamsi/Desktop/sample/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/vamsi/Desktop/sample/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at /Users/vamsi/Desktop/sample/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (/Users/vamsi/Desktop/sample/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:164:9)

**Comment by mikehardy** [comment]
You didn't follow the template.
But build errors are always a project integration issue. Something the docs specify is missing somewhere.
Clone this repo. Run this script. The build will work https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

**Comment by vammu920** [comment]
@mikehardy hey please can you tell me how to run the script.

**Comment by mikehardy** [comment]
No offense intended, but if you can't figure out how to run a well-documented script, I really can't help

**Comment by vammu920** [comment]
ok thanks i will figure it out . Till now i havent worked with .sh files @mikehardy

**Comment by mikehardy** [comment]
First time for everything :-). After you clone the repo, you should be able to just run it in a command prompt.

**Comment by vammu920** [comment]
Loll i  thought there is no readme file . my mistake thanks @mikehardy
