### ISSUE TITLE
🔥 Admob interstitial not showing after Modal (even after modal is closed)

### ISSUE THREAD

**Issue by Tinmania2018** [invertase/react-native-firebase#3181]
## Issue

I am using RNFirebase-Admob for showing Interstitial ads. Everything works fine but the ad is not showing after a modal on this page is closed. The ad is loaded because using the example code I can load the ad and immediately show the ad as wel. 
In the app users can upload information. When pressing the upload button a modal is opened which lets them choose between a free upload or not. The free upload should start the interstitial ad. 

I already read that the modal is causing this, so I have created a Timeout to give the modal time for closing and after this start the ad. However this isn't working as expected, even with the time-out the ad is not showing. 

```
`    const unitId =
        Platform.OS === 'ios'
            ? 'ca-app-pub-3940256099942544/8691691433'
            : 'ca-app-pub-3940256099942544/8691691433';
    const ad = firebasead.admob().interstitial(unitId);
    const AdRequest = firebasead.admob.AdRequest;
    const request = new AdRequest();
    ad.loadAd(request.build());

    ad.on('onAdLoaded', () => {
        console.log('Advert ready to show.');
        // ad.show();
    });`
```

Above code works. The advert is shown after loading when the ad.show line is active.

```
    const addUsingAdHandler = async () => {
        setIsAddMode(false)
        console.log('modal closed')
        await showingAd()
        ad.show()
        console.log("video shown")
    }
    const showingAd = async () => {
        return new Promise(res => setTimeout(res, 1000));
    }
```

The addUsingAdHandler is started when in the modal users opt for a free upload. With setIsAddMode the modal is closed, modal closed is logged and the 1 second delay start. After this the ad is not shown unfortunately. 

Also on a sidenote, how can I monitor if the ad is closed? 

`    ad.on('onAdClosed', () => {
        console.log('Advert closed');
       });
`

I tried this however it isn't loggin the Advert closed part? 

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```
json
  "dependencies": {
    "@expo/vector-icons": "^10.0.6",
    "expo": "^35.0.0",
    "expo-file-system": "~7.0.0",
    "expo-font": "~7.0.0",
    "expo-location": "~7.0.0",
    "expo-permissions": "~7.0.0",
    "firebase": "^7.8.0",
    "geolib": "^3.2.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "0.59.10",
    "react-native-firebase": "^5.5.7",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-google-signin": "^2.1.1",
    "react-native-image-crop-picker": "^0.24.1",
    "react-native-maps": "~0.25.0",
    "react-native-modal": "^11.5.3",
    "react-native-reanimated": "~1.2.0",
    "react-native-screens": "1.0.0-alpha.23",
    "react-native-unimodules": "0.6.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.2.2",
    "react-navigation-header-buttons": "^3.0.3",
    "react-navigation-stack": "^1.9.4",
    "react-navigation-tabs": "^2.5.6",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0",
    "uuid-v4": "^0.1.0"
  },
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```
ruby
#RNFirebase modules
pod 'Firebase/Core', '~> 6.13.0'
pod 'Firebase/AdMob', '~> 6.13.0'
```

#### `AppDelegate.m`:

```
objc
#import <Firebase.h>

#import <UMCore/UMModuleRegistry.h>
#import <UMReactNativeAdapter/UMNativeModulesProxy.h>
#import <UMReactNativeAdapter/UMModuleRegistryAdapter.h>

@implementation AppDelegate

@synthesize window = _window;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    [FIRApp configure];
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```
groovy
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
        classpath 'com.google.gms:google-services:4.3.0'
......
allprojects {
  repositories {
    google()
    jcenter()
    maven { url 'https://www.jitpack.io' }
    mavenLocal()
    maven {
      // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
      url("$rootDir/../node_modules/react-native/android")
    }
    maven {
      // Android JSC is installed from npm
      url("$rootDir/../node_modules/jsc-android/dist")
    }

```

#### `android/app/build.gradle`:

```
groovy
      // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation "com.google.firebase:firebase-core:16.0.9"
    implementation "com.google.firebase:firebase-ads:17.2.1"
    addUnimodulesDependencies()
```

#### `android/settings.gradle`:

```
groovy
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
```

#### `MainApplication.java`:

```
java
import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.admob.RNFirebaseAdMobPackage;
....
 new RNFirebasePackage(),
new RNFirebaseAdMobPackage(),
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.15.2
      CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
      Memory: 18.02 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.8.1 - /usr/local/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.11.2 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 25.0.1, 26.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.1
        System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  5.5.7
- **`Firebase` module(s) you're using that has the issue:**
Admob- **Are you using `TypeScript`?**
  - `N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by ugrdursun** [comment]
Have you found any solution for this ?

**Comment by Tinmania2018** [comment]
Unfortunatly not @ugrdursun. The time-out for showing the ad works on Android, however on IOS it never shows. Still havn't figured this one out.

**Comment by ugrdursun** [comment]
> Unfortunatly not @ugrdursun. The time-out for showing the ad works on Android, however on IOS it never shows. Still havn't figured this one out.

I temporarily solved issue by showing ad before modal. After closing ad it shows modal with a little timeout

**Comment by Tinmania2018** [comment]
> > Unfortunatly not @ugrdursun. The time-out for showing the ad works on Android, however on IOS it never shows. Still havn't figured this one out.
> 
> I temporarily solved issue by showing ad before modal. After closing ad it shows modal with a little timeout

Great you got it to work in your case! For my app the ad should have to be shown after closing the modal so this unfortunatly would not work for my case.

**Comment by mohity777** [comment]
This is still an issue why is it closed? I can not show ad when modal is open. The ad gets closed immediately.

**Comment by mikehardy** [comment]
@mohity777 do you propose some diagnosis and PR to fix the problem? There was no progress on the issue, those things are closed over time as it is a community module, and if there is no progress, that is a clear sign there is no interest.

I happily work with contributors to merge PRs though - post one up and I'll work with you to get it merged and released

Cheers

**Comment by SalmanCorleone** [comment]
Hey guys, I found a neat workaround for this, that does not require `timeout`.
Timeout works on certain cases but it seems kinda random across devices.

On Modal component, use both of these props : `onRequestClose` and `onDismiss`

```js
onRequestClose = { () => // set modal to false }
```

```js
onDismiss = { () => { // if ad is loaded, show the ad }
```

This way the modal won't block the ad from from showing up. 
Worked for me!
