### ISSUE TITLE
firebase phone auth Error: auth/invalid-app-credential Invalid token.

### ISSUE THREAD

**Issue by chellongCoder** [invertase/react-native-firebase#3183]
I resolved this issue.
I create Apple Development IO Push Services and Apple Push Services.
![image](https://user-images.githubusercontent.com/30166352/74078910-cc1e2700-4a62-11ea-99f8-7740e0a92671.png)

download both certificate.
export them to .p12 and add to firebase console. NOT add file .p8 
![image](https://user-images.githubusercontent.com/30166352/74078892-a55ff080-4a62-11ea-863f-2e905441c5fa.png)
hope that help to you.

**Comment by russellwheatley** [comment]
@chellongCoder Thank you for providing a resolution to your problem.

**Comment by lyseiha** [comment]
I follow your but seem like not working at all.

**Comment by Nsengiyunva** [comment]
Put simply, you should configure your ios react native app on the apple developer account with the certificate, provisioning profile attached with your bundle ID>
Import this into your xcode or enable auto import in the xcode. 
Then you will be able to use firebase auth for phone number authentication.

**Comment by yoavapi** [comment]
please review change in config explained here (relevant to Flutter as to React Native)
https://stackoverflow.com/questions/74340881/invalid-app-credential-token-mismatch-in-flutter-firebase-auth

**Comment by giacomoalonzi** [comment]
Thanks for the solution! It's work!

**Comment by jimmy123A** [comment]
> I resolved this issue. I create Apple Development IO Push Services and Apple Push Services. ![image](https://user-images.githubusercontent.com/30166352/74078910-cc1e2700-4a62-11ea-99f8-7740e0a92671.png)
> 
> download both certificate. export them to .p12 and add to firebase console. NOT add file .p8 ![image](https://user-images.githubusercontent.com/30166352/74078892-a55ff080-4a62-11ea-863f-2e905441c5fa.png) hope that help to you.

Lmao, I'd have NEVER figured that out myself. Thanks :)

**Comment by lasharela** [comment]
But it was working. Why it's not working after few days... hm.

**Comment by nanokoko89** [comment]
my app use expo and expo notifications and firebase functions. When push notifications successfully then can not sign in by phone authentication to firebase. It occurs this error: auth/invalid-app-credential.
Anyone could fix this please help me? I have tried to fix this like a month.

Thanks you

**Comment by DevTwana** [comment]
Thanks for the solution, It works great

**Comment by luckyhandler** [comment]
or you simply deleted your key because you didn't consider it is also used in the auth process...

**Comment by geoffcfchen** [comment]
it works!

**Comment by moscchi** [comment]
I love you man! i tried a lot of things and only this solution works for me ❤️ ❤️ ❤️ ❤️

**Comment by wolfxpertlab** [comment]
@chellongCoder  you suggest solution, after what changes in native file appdelegate.h or appdelegate.m in iOS please help to which change in android that show error like 

[Error: [auth/billing-not] An internal error has occurred. [ BILLING_NOT_ENABLED ]]

**Comment by priyanshi-chhabra** [comment]
I am using onesignal for push notification and firebase authentication for phone number OTP based login, still do i need to add APN in firebase ?

**Comment by mikehardy** [comment]
@priyanshi-chhabra 

> Phone auth requires app verification, and the automatic app verification process uses data-only firebase cloud messages to the app. Data-only cloud messaging only works on real devices where the app has background refresh enabled. If background refresh disabled, or if using the Simulator, app verification uses the fallback reCAPTCHA flow allowing you to check if it is configured correctly.

https://rnfirebase.io/auth/phone-auth#ios-setup

Feel free to skip that step, but you will have to accept all clients getting reCAPTCHA instead.
