### ISSUE TITLE
Google Signin do not use accessToken anymore

### ISSUE THREAD

**Issue by DLevai94** [invertase/react-native-firebase#3184]
## Steps to Reproduce

Linked to a brand new RN project. Called react-native-google-singin's `configure` method on `App.tsx` and trying to log in on button press, then link provider to Firebase. I wait for an accessToken in response, but there's never any in the new version.

They reference here, that usage of accessToken is discuaraged. https://github.com/react-native-community/google-signin#gettokens

![Screenshot 2020-02-09 at 8 18 45](https://user-images.githubusercontent.com/15244882/74098141-d8fb5300-4b14-11ea-8e9d-42cf230cc550.png)

![image](https://user-images.githubusercontent.com/15244882/74098080-27f4b880-4b14-11ea-80d7-d324c3339c94.png)

## Actual Behavior

<img width="734" alt="Screenshot 2020-02-09 at 8 11 11" src="https://user-images.githubusercontent.com/15244882/74098114-7efa8d80-4b14-11ea-9d9c-869f06167103.png">

## Environment

- react-native 60
- @react-native-community/google-signin v3
- `pod 'GoogleSignIn', '~> 5.0.2'`
- iOS 13.3.1

**Comment by mikehardy** [comment]
Can you replace the images with text perhaps? would really help see difference between expected vs actual

And what's the desired outcome here? A PR that changes the integration? You skipped much of the template so I'm not sure what react-native-firebase you're on either, so, a PR for v5 or v6? I assume v6 but assumptions are dangerous

Does the app crash, or is it just deprecated?

**Comment by DLevai94** [comment]
Thanks @mikehardy for the questions. I'm on v6, yes.

After further investigation, I think only the docs needs to be updated. I'm gonna send a PR with the update.

**Comment by Ehesp** [comment]
https://github.com/invertase/react-native-firebase/issues/3217

**Comment by mikehardy** [comment]
No action to take, this is correct in rnfirebase.io documentation relative to the google signin docs, we are only suggesting use of idToken now, which is what they document https://github.com/invertase/react-native-firebase/blame/master/docs/auth/social-auth.md#L249
