### ISSUE TITLE
Remote Config documentation says "Import the Performance Monitoring package"

### ISSUE THREAD

**Issue by TheMrZZ** [invertase/react-native-firebase#3186]
## Documentation Feedback

Remote Config documentation says "Import the Performance Monitoring package into your project", but it should say "Import the Remote Config package into your project".

Link to the typo : [https://invertase.io/oss/react-native-firebase/v6/remote-config/quick-start#module-usage](https://invertase.io/oss/react-native-firebase/v6/remote-config/quick-start#module-usage)

![image](https://user-images.githubusercontent.com/30944236/74107107-f8be6580-4b6c-11ea-9353-1055a3e8fe5b.png)

**Comment by mikehardy** [comment]
Hi there! Hit that edit button on the top right of the page and github will walk you through the pull request process really quickly so you can you fix it :-)

**Comment by russellwheatley** [comment]
@TheMrZZ Thanks for letting us know, I've fixed it :)
