### ISSUE TITLE
Undefined symbols for architecture x86_64 w/ RNFBAnalytics 

### ISSUE THREAD

**Issue by BallardB** [invertase/react-native-firebase#3193]
## Issue

Describe your issue here

I am having trouble installing the `React-Native-Firebase/Analytics` Module in my React-Native Project. When trying to build the project in iOS I get the error using `React-Native 0.61.5` & `React-Native-Firebase 6.3.1`: 

`Undefined symbols for architecture x86_64: 
"_OBJC_CLASS_$_FIRAnalytics", referenced from:
      objc-class-ref in RNFBAnalyticsModule.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

I have successfully installed the core `@react-native-firebase/app` and am able to run my project without any issues. My issue comes with trying to install `@react-native-firebase/analytics` specifically. 

I have closed my metro bundler, cleaned the project, cleaned my build folder, deleted my derived data, re-installed pods, re-installed node_modules. 

Any help would be greatly appreciated! Thanks

---
## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 `System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 373.05 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1
      System Images: android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-23 | Intel x86 Atom, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-24 | Google APIs ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^3.0.4 => 3.0.4 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1`
```

- **Platform that you're experiencing the issue on**:
  - [X] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.3.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/analytics`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You skipped big chunks of the template.
Are you using use_frameworks, for instance? Maybe that's the problem, but I don't see the Podfile.
Have you tried a minimal clean example, e.g.: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh#L52 (that's where my demo script installs analytics, and it built with 6.2.0 at least, maybe 6.3.2 has a problem but I'm doubtful?)

**Comment by BallardB** [comment]
Hi @mikehardy, I am using `use_frameworks!` because I am using 3rd party pods. I have tried using v6.2.0 of react native firebase but that did not solve the issue. 

Any other suggestions? 


Here is my Podfile: 
```# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Uncomment this line if you're using Swift
use_frameworks!


source 'https://github.com/CocoaPods/Specs.git'
source 'git@bitbucket.org:XXXLibrary.git'

def XXpods
  pod 'XXLibrary', '8.1.0'
end

XXpods

target 'myProject' do
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['RNFBApp'].include?(target.name)
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
    elsif target.name.eql?('RNFBAnalytics')
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'FirebaseAnalytics'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleAppMeasurement'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'nanopb'})
      target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
    end
  end
end```

**Comment by schlaegerz** [comment]
I am running into the same problems and I don't have use_frameworks
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def pod_installs
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Toybox
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'Mixpanel'
  pod 'OneSignal'

  # Add new pods below this line

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit' 

#  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  use_native_modules!
end


target 'Toybox' do
  pod_installs
end

target 'ToyboxTest' do
  pod_installs
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-config'
      phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
      phase.shell_script = "cd ../../"\
                           " && RNC_ROOT=./node_modules/react-native-config/"\
                           " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
                           " && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig"\
                           " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"

      target.build_phases << phase
      target.build_phases.move(phase,0)
    end
  end
end

My guess is there is some step missing in the setup instructions. I have read them multiple times and tried rebuilding my app many times with no luck.

**Comment by mikehardy** [comment]
I had a hunch that was it. use_frameworks is a thorn in the side of react-native right now - at the framework level and in the libraries everyone is trying to make it work, and only succeeding occasionally, then typically re-breaking it. My only advice is to search the repo for use_frameworks and check out some of the workarounds others list - some have success

**Comment by schlaegerz** [comment]
I tried 6.2 as well as 6.3 and have had no luck

**Comment by schlaegerz** [comment]
Figured out my problem, not sure if it will be the same as the original issue. I was converting from a fabric implementation and there were a couple files that I had removed from my xcode project, but not removed from my actual file system.

For whatever reason those were messing with my build and after I removed them all my problems went away.

**Comment by BallardB** [comment]
Thanks for the suggestion @mikehardy, due to 3rd party pods we can't get rid of `use_frameworks!`. Will continue searching around! It seems this has been giving a lot of people issues.

**Comment by mikehardy** [comment]
use_frameworks is definitely a big mess right now, everyone's trying to make it work though - which is to say that whatever you find, if you document it for others you might save someone's day. Hope you find a trick that works

**Comment by SaraChicaD** [comment]
Hi there can we bump this? I am installing this on a brand new project and getting the same error, not sure why and I've tried everything I could think of.
- `react-native`: 63.2
- `@react-native-firebase/analytics`: 10.8.0
- `@react-native-firebase/app`: 10.8.0

```
▸ Linking RNFBApp
▸ Processing RNFBAnalytics-Info.plist
▸ Copying RNFBAnalytics-umbrella.h
▸ Copying RNFBAnalyticsModule.h
▸ Compiling RNFBAnalyticsModule.m
▸ Compiling RNFBAnalytics-dummy.m
▸ Linking RNFBAnalytics

❌  Undefined symbols for architecture x86_64
> Symbol: _OBJC_CLASS_$_FIRAnalytics
> Referenced from: objc-class-ref in RNFBAnalyticsModule.o



❌  ld: symbol(s) not found for architecture x86_64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

 I would really, really appreciate any suggestions cc @mikehardy

**Comment by mikehardy** [comment]
It's been closed 10months? So opening a new issue is best. I'm on a really low bandwidth connection right now so can't link but search for my make-demo.sh script link in this repo and get a minimal reproduction, then we can check? Smells like some podfile / old version / apple silicon thing maybe

**Comment by kilimchoi** [comment]
> Thanks for the suggestion @mikehardy, due to 3rd party pods we can't get rid of `use_frameworks!`. Will continue searching around! It seems this has been giving a lot of people issues.

have you been able to make it work?

**Comment by mikehardy** [comment]
@kilimchoi I don't think there was a successful resolution that I know of though I'm curious too if Sara got something going, but I did test `use_frameworks!` locally and get it working

https://github.com/mikehardy/rnfbdemo/commit/8f7a33921e77c882398fb1c607c0a6eee4501e70#diff-3e27ae623577d0c559bd8ab973a0c34af8cc65ef9beb9868a9cdb029854f8078 - you have to set a Podfile variable to true as documented https://rnfirebase.io/#allow-ios-static-frameworks

then just recently (with react-native 0.64) I noticed there is a workaround needed as well

https://github.com/mikehardy/rnfbdemo/commit/f84ad523b37f19db46ac0710396c4769ea024808

**Comment by SaraChicaD** [comment]
hey y'all, what ended up fixing it was [this](https://github.com/firebase/firebase-ios-sdk/issues/7566#issuecomment-790110617), hope that helps @kilimchoi ? if not, i wish you all the best!!

> @kilimchoi I don't think there was a successful resolution that I know of though I'm curious too if Sara got something going, but I did test `use_frameworks!` locally and get it working
> 
> [mikehardy/rnfbdemo@8f7a339#diff-3e27ae623577d0c559bd8ab973a0c34af8cc65ef9beb9868a9cdb029854f8078](https://github.com/mikehardy/rnfbdemo/commit/8f7a33921e77c882398fb1c607c0a6eee4501e70#diff-3e27ae623577d0c559bd8ab973a0c34af8cc65ef9beb9868a9cdb029854f8078) - you have to set a Podfile variable to true as documented https://rnfirebase.io/#allow-ios-static-frameworks
> 
> then just recently (with react-native 0.64) I noticed there is a workaround needed as well
> 
> [mikehardy/rnfbdemo@f84ad52](https://github.com/mikehardy/rnfbdemo/commit/f84ad523b37f19db46ac0710396c4769ea024808)
