### ISSUE TITLE
Advert failed to load:  [Error: [admob/error-code-internal-error] Something happened internally; for instance, an invalid response was received from the ad server.]

### ISSUE THREAD

**Issue by jeversonjv** [invertase/react-native-firebase#3194]
When I use the real unitId, I am having this error. If I use TestIds, I am not having the problem.

I'm using @react-native-firebase/app": "^6.3.1 and @react-native-firebase/admob 6.3.1

![Captura de tela_2020-02-11_22-48-28](https://user-images.githubusercontent.com/46850397/74296010-775c0400-4d21-11ea-8167-244b6ab9c2f8.png)

![adsad](https://user-images.githubusercontent.com/46850397/74296303-2698db00-4d22-11ea-85b4-5c4a78200e00.png)

**Comment by Ehesp** [comment]
This usually happens when the request against your admob account fails - do you have payment setup/all actions covered in your account which allows for real requests?

**Comment by jeversonjv** [comment]
No, I don’t have it, i'll configure it. But will it even work in development?

**Comment by jeversonjv** [comment]
> This usually happens when the request against your admob account fails - do you have payment setup/all actions covered in your account which allows for real requests?

No, I don’t have it, i'll configure it. But will it even work in development?

**Comment by Ehesp** [comment]
Yeah, should do, just make sure you set a test device: https://invertase.io/oss/react-native-firebase/v6/admob/reference/requestoptions#testDevices

Let me know if you have issues!

**Comment by AndyCC25** [comment]
Hey, I'm having the same issue, but I have all the configuration set including the payment method, also I receive a notification that I can use the ad server, but the logs stills show me
```javascript
Advert failed to load:  [Error: [admob/error-code-internal-error] Something happened internally; for instance, an invalid response was received from the ad server.]
 WARN  [Error: Internal error, an invalid response was received from the ad server.]
 WARN  [Error: Internal error, an invalid response was received from the ad server.]
```
And is the same case when I use the test ads, what can be the issue?

**Comment by kdpadhiyar** [comment]
I am facing this issue with test ids and it appears when net got disconnected in between banner ads are loading 
and app got crash.
