### ISSUE TITLE
How to disable sound in localNotification?

### ISSUE THREAD

**Issue by Shinichi52** [invertase/react-native-firebase#320]
hi,
i don't want to play sound in localNotification. i tried set property sound in object notification = empty, but it's not work. How to disable sound in localNotification?
my notify object 
```
const notify = {
     ...message.notification,
     show_in_foreground: true,
     notify_type: message.NotificationType,
     obj_id: message.ObjectId,
     sound: ''
};
firebase.messaging().createLocalNotification(notify);
```
### Environment

1. Target Platform (e.g. iOS, Android): iOS
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
4. React Native version (e.g. 0.45.1): 0.46.0
5. RNFirebase Version (e.g. 2.0.2): 1.1.2

**Comment by chrisbianca** [comment]
@Shinichi52 Apologies for the delay on this one.  I believe you should be able to remove the `sound` parameter completely to disable the sound.

**Comment by windydang26** [comment]
haizz sinichi52 :)
