### ISSUE TITLE
Can't access documentation of BannerAd

### ISSUE THREAD

**Issue by fachryansyah** [invertase/react-native-firebase#3208]
## BannerAd can't be access
i tried to find about how to implement BannerAd in react-native-firebase/admob, but i can't access the docs, i've already check my internet. the docs showing like this
![image](https://user-images.githubusercontent.com/14109765/74553113-39f9af80-4f89-11ea-8b59-a7a583154682.png)

Here link of page https://invertase.io/oss/react-native-firebase/v6/admob/reference/bannerad/

**Comment by mikehardy** [comment]
Works fine for me in chrome. This happens a lot when there are adblockers installed

**Comment by selvin007** [comment]
Hard Refresh(Ctrl + Shift + r) or open in private window

Page fails some time due to service-worker.js caching

**Comment by Ehesp** [comment]
Same issue with v5 docs too, it's heavily ad related so gets picked up by adblockers.
