### ISSUE TITLE
 Scope firebase-admin using `databaseAuthVariableOverride` or similar

### ISSUE THREAD

**Issue by alexpchin** [invertase/react-native-firebase#3214]
This is more of a question rather than a feature request...

I am unsure why it's not more commonplace to "scope" the firebase admin using a UID of a logged-in user so that you can use the same client-side rules on the server-side? It seems odd to be able to implement one set of rules for the clientside but then have to perform lots more lookups if you move the logic to the server-side?

It seems like it could potentially be achieved with: `databaseAuthVariableOverride`

**End goal**: To be able to implement firestore rules on the server using the same rules file as is used on the client?

https://stackoverflow.com/questions/55554667/firestore-security-rules-for-server-side-code

**Comment by russellwheatley** [comment]
Hi @alexpchin, please fill out the issue template. Thank you.
