### ISSUE TITLE
firestore query validators

### ISSUE THREAD

**Issue by russellwheatley** [invertase/react-native-firebase#3220]
## Issue

[firestore]Firebase web version allows the use of `where` query to be invoked before and after `orderBy` query. On RNFB, if a user invokes the `where` query after the `orderBy` query, the validation is bypassed. Perhaps merging the validation for `where` and `orderBy` query to ensure it is consistent.

**Comment by dackers86** [comment]
@russellwheatley Just to clarify, what do you mean by validation?

Does this mean to say the where clause is not executed?
