### ISSUE TITLE
Do you support coddles analytics for screen view

### ISSUE THREAD

**Issue by MikePendo** [invertase/react-native-firebase#3226]
I there any support for screen views analytics without code (like in google analytics)
or `setCurrentScreen(screenName, screenClassOverride)` is the only way?

**Comment by Ehesp** [comment]
You have to do it yourself. The thing is, an app with React Native could be anything - navigation can be implemented in many ways using various libraries. As everything in RN runs in a single "activity", the analytics module doesn't see any "screen changes" with RN, hence you need to do it yourself.

**Comment by MikePendo** [comment]
is there any reference on how to accomplish it?

**Comment by shamilovtim** [comment]
Landed in #6588
