### ISSUE TITLE
IOS notifications (5.5.0): native.getNativeModule)(...).complete is not a function

### ISSUE THREAD

**Issue by yeremyantshrach** [invertase/react-native-firebase#3227]
## Issue

I have the following code in a react component and when I'm receiving notification(the app is opened) I'm getting error like this.

**react-native version: 0.60.4
react-native-firebase version: 5.5.0**

![IMG_61BADB91B363-1](https://user-images.githubusercontent.com/45326869/74936237-393aa080-5403-11ea-8128-df0b8ffa0a40.jpeg)

 

---

### Javascript

```javascript 

const convertNotification = notification => ({
  data: notification.data || notification._data,
  notificationId: notification.notificationId || notification._notificationId,
  id:
    notification.id ||
    notification._id ||
    notification.notificationId ||
    notification._notificationId,
});

const notificationListener = await firebase
    .notifications()
    .onNotification(async notificationData => {
      notificationData = convertNotification(notificationData);
      // local notifications
      const notification = new firebase.notifications.Notification()
        .setNotificationId(notificationData.notificationId)
        .setTitle(notificationData.data.type)
        .setBody(notificationData.data.body)
        .setData({
          ...notificationData.data,
          isLocal: true,
        })
        .android.setChannelId(constants.channelId)
        .android.setSmallIcon(constants.notificationIconName)
        .android.setLargeIcon(constants.notificationIconName)
        .android.setColorized(true)
        .android.setColor(bluePale);

      await firebase
        .notifications()
        .displayNotification(notification)
        .catch(err => console.error(err));
    });

```

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `5.5.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by lorenc-tomasz** [comment]
Similar issue.
