### ISSUE TITLE
[Migration v5 -> v6] Question: Is anonymous user token lost after migration ?

### ISSUE THREAD

**Issue by appli-intramuros** [invertase/react-native-firebase#3228]
Hello,

I plan to migrate to v6 (from v5), but I am wondering if users tokens (anonymous user) will be lost after migration ?
In my app, users sign in anonymously (`signInAnonymously()`). 
I am using users tokens to track them and generate analytics reports.
So I need to know if the users data will be lost or not after v6 migration.

Thanks for your help.

PS: sorry for my bad english.

**Comment by Ehesp** [comment]
Hello... Good question! I don't think so, only if the app is reinstalled/deleted. v6 works with newer Firebase SDKs so you should be ok.

**Comment by appli-intramuros** [comment]
I think I found the answer:
https://github.com/firebase/firebase-android-sdk/blob/master/firebase-installations/FCM_TOKENS_CHANGE.md

> If you use a Firebase application instance different to the default instance, the FCM registration tokens of installed instances of your applications may change one time after the migration.

> Please note that if you only use the default Firebase application instance, your applications will not be affected.
