### ISSUE TITLE
Fabric and Crashlytics

### ISSUE THREAD

**Issue by alizahid** [invertase/react-native-firebase#323]
Hey,

<img src="https://user-images.githubusercontent.com/941775/29155832-6ca8e10c-7daf-11e7-9dc4-3e77e0c04560.png">

So, Firebase is going to adopt Crashlytics as their crash reporting tool. How will that affect this library? Will you move or should I add the Fabric SDK separately? I really enjoy this all in one package!

**Comment by chrisbianca** [comment]
@alizahid Until Firebase announce exactly how they plan on adopting Crashlytics and the rest of the Fabric suite we can't really answer this.  But rest assured, assuming they integrate into the Firebase suite, then we will look to add support for it as soon as they do.

**Comment by aranda-adapptor** [comment]
@chrisbianca any update on this? Firebase has integrated Crashlytics, albiet still using Fabric libraries, but it looks like react-native-firebase could be made to support it fairly easily?

**Comment by Ehesp** [comment]
@aranda-adapptor We did speak on Discord about maybe doing something along the lines of `firebase.fabric()` but not sure where it got to. Support is the easy part, it's just the integration and maintenance of it.
