### ISSUE TITLE
Is react-native-firebase secure when offline mode is active?

### ISSUE THREAD

**Issue by muhammadwafa** [invertase/react-native-firebase#3230]
Where the firebase `offline data` stored, Is that `secure`? I have some important id like `UID` which it is available in all user messages (`online, offline`), and actually in firebase security rule I have to check only that.

I tried to `encrypt` it, but I faced with `decryption` in firebase security rule, because there was not any `decryption` possibilities, so how can I secure the `offline data` which is available on users phone.

**Comment by Ehesp** [comment]
We only use the Firebase SDKs under the hood, therefore any data stored happens via their own SDKs.

I'd suggest reaching out to support directly if you have specific questions about security: https://firebase.google.com/support
