### ISSUE TITLE
🔥Unable to find a specification for `Fabric (~> 1.10.2)` depended upon by `RNFBCrashlytics`

### ISSUE THREAD

**Issue by pani7** [invertase/react-native-firebase#3232]
## Issue

Can not install IOS crashlytics.

Describe your issue here

I am trying to install crashlytics, everything went fine with android, but with IOS on pod install i get error:

**`Unable to find a specification for `Fabric (~> 1.10.2)` depended upon by `RNFBCrashlytics``**

I tried adding new run script on xcode even tough it is in manual guide so i assume i don/t need it - still same error. Also it says in documentation that 'Both platforms require additional steps to complete installation' but there is only guide for android -> [https://invertase.io/oss/react-native-firebase/v6/crashlytics/quick-start](url)

## Project Files

I am using RN 0.61.2, and react-native-firebase/app 6.3.4. 
I installed first firebase /app 

#### `package.json`:

    "@react-native-firebase/analytics": "^6.3.4",
    "@react-native-firebase/app": "^6.3.4",
    "@react-native-firebase/crashlytics": "^6.3.4",
    "@react-native-firebase/perf": "^6.3.4",

#### `AppDelegate.m`:

</p

## Environment

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `crshlytics`
- **Are you using `TypeScript`?**
  - `N`

**Comment by mikehardy** [comment]
pod repo update?

**Comment by pani7** [comment]
Nope, after pod repo update i get same error -> Unable to find a specification for `Fabric (~> 1.10.2)` depended upon by `RNFBCrashlytics`

**Comment by pani7** [comment]
Should i do anything manually for crashlytics on RN > 0.60 or npm install and pod install is enough? Because in documentation it says additional setup is required and then there is only android additional instructions

**Comment by mikehardy** [comment]
This usually works to make a throwaway app and verify that everything should work https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh
