### ISSUE TITLE
'protobuf/GPBProtocolBuffers_RuntimeSupport.h' file not found

### ISSUE THREAD

**Issue by adkaushik** [invertase/react-native-firebase#3235]
## Issue

Describe your issue here

I am using react-native version 0.60. When installing @react-native-firebase/messaging, the following error gets thrown when building the app. 

```
/ios/Pods/Protobuf/objectivec/google/protobuf/Duration.pbobjc.m:11:10: fatal error: 'protobuf/GPBProtocolBuffers_RuntimeSupport.h' file not found
 #import <protobuf/GPBProtocolBuffers_RuntimeSupport.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

```
These pods got installed during `pod install`

```
Installing Firebase 6.13.0
Installing FirebaseMessaging (4.1.10)
Installing Protobuf (3.11.4)
Installing RNFBMessaging (6.3.4)
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Skipped the template

For v5 on rn60 clone and examine this, it should work https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

I don't see any reason not to use those versions plus most up to date pods and Android bom (6.17 pods bom 24.4.0 I think). I'm current on all of those and would not want to waste time troubleshooting old versions. Be sure to use react-native-clean-project after changing versions

**Comment by adkaushik** [comment]
I am using v6 on react-native 0.60 not v5 of react-native-firebase

**Comment by mikehardy** [comment]
You skipped the template, so how could I know that?

You'll want this then https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

...and maybe to provide the template details to obtain on-target help

**Comment by filmhomage** [comment]
Same here.
Revert to `Protobuf 3.11.3` and working.

**Comment by adkaushik** [comment]
How did you revert the protobuf version? Are you adding Protbuf as a separate pod in the podfile ? For me it gets installed as a dependency of firebase messaging.

**Comment by adkaushik** [comment]
Added `Protobuf, 3.11.3` and ran pod update and the issue got fixed now.

**Comment by filmhomage** [comment]
After updated Firebase version to 6.18.0  in Podfile + Protobuf 3.11.4 is working.
I removed protobuf 3.11.3 from Podfile now.

**Comment by CleberReis** [comment]
For me in iOS Swift works... 
In File googleapis.podspec
change the 
s.dependency "!ProtoCompiler-gRPCPlugin"
for
s.dependency "!ProtoCompiler-gRPCPlugin", "~> 1.24.2"

Clean Project and delete DerivedData
and pod install again

**Comment by sakthiinfotec** [comment]
Thanks @CleberReis 

In File `googleapis.podspec`, I updated like below

`s.dependency "!ProtoCompiler-gRPCPlugin", "~> 1.29.1"`

Then 
1. Clean Project and 
2. Delete DerivedData
3. pod install

My iOS build worked.

> For me in iOS Swift works...
> In File googleapis.podspec
> change the
> s.dependency "!ProtoCompiler-gRPCPlugin"
> for
> s.dependency "!ProtoCompiler-gRPCPlugin", "~> 1.24.2"
> 
> Clean Project and delete DerivedData
> and pod install again
