### ISSUE TITLE
Auto-Linking does not work for Cloud Messaging in v6

### ISSUE THREAD

**Issue by orofbrown** [invertase/react-native-firebase#3237]
## Documentation Feedback

Auto-Linking does not work for Cloud Messaging in RN Firebase 6, and this is not noted in the documentation at https://invertase.io/oss/react-native-firebase/v6/messaging/quick-start. I successfully set up Remote Config and got it working, but then spent a few hours after that trying to track down why the Cloud Messaging was not working and not giving me any output.

Please update the docs, either to make a note that this is a known issue, or fix the problem with having to manually link this package.

**Comment by mikehardy** [comment]
This is an assertion without following the template so we can see what went wrong.

Lots and lots of people use cloud messaging and it works for everyone else, so you'll have to provide a reproducible example to show how/why it fails. You can start by cloning this https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh and if you just add in the messaging dependency it should be easy to demonstrate the failure

**Comment by orofbrown** [comment]
@mikehardy I clicked "New Issue" and chose "Documentation Feedback" and this is what it gave me. So maybe you guys need to update your templates. I can give you examples of it not working for me, though.

**Comment by Ehesp** [comment]
It does work, just something must not be working in your setup so it's not really a documentation issue. 

Can you share why it doesn't work?

**Comment by mikehardy** [comment]
@orofbrown interesting re: templates, if something isn't working I'd say it's a code issue not doc feedback, and that template has all the details that can help troubleshoot: https://github.com/invertase/react-native-firebase/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by Salakar** [comment]
Closing this as part of #3339
