### ISSUE TITLE
🔥 App crash on android 4.4 (Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider)

### ISSUE THREAD

**Issue by Dheeeraj** [invertase/react-native-firebase#3239]
## Issue
Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider

Describe your issue here
App crash on android 4.4 .woking fine in 6.0 and above

Things i tried prior posting this
some says its from multidex but still crashes after adding multidex 
have added "multiDexEnabled true" and below code to build.gradle of app
```
implementation 'com.android.support:multidex:1.0.3'
```
and i did make sure there is below line of code in androidmanifest
```
 <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="app_id"/>
```

**Steps to reproduce**
1) Created a new project with react native init and just added this lib as instructed in docs 
2) Executed on a emulator of OS androd 4.4

---

## Project Files

From android Logs
```
02-25 19:07:13.392 14413-14413/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.testapp.app, PID: 14413
    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.MobileAdsInitProvider" on path: DexPathList[[zip file "/data/app/com.testapp.app-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.testapp.app-2, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:4793)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.MobileAdsInitProvider" on path: DexPathList[[zip file "/data/app/com.testapp.app-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.testapp.app-2, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4778)
```
### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"react": "16.9.0",
 "react-native": "0.61.5",
"react-native-firebase": "^5.5.6",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Last I checked it worked but with an ios workaround needed not android https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh#L132

Please clone that repo and if you can reproduce with that script we can look

**Comment by Dheeeraj** [comment]
> Last I checked it worked but with an ios workaround needed not android https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh#L132
> 
> Please clone that repo and if you can reproduce with that script we can look

Sir im not on mac is there any work around for windows

**Comment by mikehardy** [comment]
React native implies ios development implies Mac. I also run it on Linux though. I don't personally use windows so maybe via Linux subsystem for windows but that's unknown

**Comment by amin79** [comment]
Hi @Dheeeraj , 

I have the same problem. Did you find any solution?

**Comment by Dheeeraj** [comment]
> Hi @Dheeeraj ,
> 
> I have the same problem. Did you find any solution?

i sloved it by adding multidex

steps i followed in app/build.gradle
```
defaultConfig{
   ...
  multiDexEnabled true
} 
```
```
dependencies {
   ...
  implementation 'androidx.multidex:multidex:2.0.1'
} 
```
and in mainApplication.java extend mainapplication with mutliDex like below(this step i missed while posting this issue)
```
import androidx.multidex.MultiDexApplication;
public class MainApplication extends MultiDexApplication implements ReactApplication
```

**Comment by amin79** [comment]
@Dheeeraj Thank you for your answer. Do I need also to add   
`<meta-data 
           android:name="com.google.android.gms.ads.APPLICATION_ID" 
           android:value="[app id]"/>` in AndroidManifest.xml ?

**Comment by Dheeeraj** [comment]
yes i was using "react-native-firebase": "^5.x.x" in that we have to add in androidmanifest if your version is different just go with the docs 

> @Dheeeraj Thank you for your answer. Do I need also to add
> `<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="[app id]"/>` in AndroidManifest.xml ?
