### ISSUE TITLE
Each module must have a unique path.

### ISSUE THREAD

**Issue by dileepbolisetti** [invertase/react-native-firebase#3245]
![Screenshot 2020-02-27 at 11 58 07 AM](https://user-images.githubusercontent.com/8918698/75418115-a5178e80-5958-11ea-969b-052dc09b1930.png)

## Issue

Describe your issue here

Unable to Run React native project with react-native-firebase 6.3.4. getting the error Project Structure Issues. Each module must have a unique path.
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

 "@react-native-firebase/app": "^6.3.4",
    "@react-native-firebase/auth": "^6.3.4",
    "@react-native-firebase/crashlytics": "^6.3.4",
    "@react-native-firebase/database": "^6.3.4",
    "@react-native-firebase/functions": "^6.3.4",
    "@react-native-firebase/messaging": "^6.3.4",
    "@react-native-firebase/storage": "^6.3.4",
    "react": "16.9.0",
    "react-native": "0.61.5"

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:
rootProject.name = 'PT'
include ':@react-native-firebase_database'
project(':@react-native-firebase_database').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-firebase/database/android')
include ':@react-native-firebase_crashlytics'
project(':@react-native-firebase_crashlytics').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-firebase/crashlytics/android')
include ':@react-native-firebase_storage'
project(':@react-native-firebase_storage').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-firebase/storage/android')
include ':@react-native-firebase_messaging'
project(':@react-native-firebase_messaging').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-firebase/messaging/android')
include ':@react-native-firebase_functions'
project(':@react-native-firebase_functions').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-firebase/functions/android')
include ':@react-native-firebase_auth'
project(':@react-native-firebase_auth').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-firebase/auth/android')
include ':@react-native-firebase_app'
project(':@react-native-firebase_app').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-firebase/app/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
ERROR: The modules ['@react-native-firebase_database', 'react-native-firebase_database'] point to the same directory in the file system.
Each module must have a unique path.


ERROR: The modules ['@react-native-firebase_storage', 'react-native-firebase_storage'] point to the same directory in the file system.
Each module must have a unique path.


ERROR: The modules ['@react-native-firebase_auth', 'react-native-firebase_auth'] point to the same directory in the file system.
Each module must have a unique path.


ERROR: The modules ['@react-native-firebase_messaging', 'react-native-firebase_messaging'] point to the same directory in the file system.
Each module must have a unique path.


ERROR: The modules ['@react-native-firebase_app', 'react-native-firebase_app'] point to the same directory in the file system.
Each module must have a unique path.


ERROR: The modules ['@react-native-firebase_crashlytics', 'react-native-firebase_crashlytics'] point to the same directory in the file system.
Each module must have a unique path.


ERROR: The modules ['@react-native-firebase_functions', 'react-native-firebase_functions'] point to the same directory in the file system.
Each module must have a unique path.

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Salakar** [comment]
Please show your gradle files like the issue template requests. Can't help you otherwise.

**Comment by dileepbolisetti** [comment]
![Screenshot 2020-02-27 at 7 19 31 PM](https://user-images.githubusercontent.com/8918698/75451209-204b6580-5996-11ea-978e-2f13d8b34c0b.png)

that settings gradle is giving this error,

and i added build files. @Salakar

**Comment by Salakar** [comment]
Remove these line from your `android/app/build.gradle` file;

```groovy
   implementation project(path: ':@react-native-firebase_database')
    implementation project(path: ':@react-native-firebase_crashlytics')
    implementation project(path: ':@react-native-firebase_storage')
    implementation project(path: ':@react-native-firebase_messaging')
    implementation project(path: ':@react-native-firebase_functions')
    implementation project(path: ':@react-native-firebase_auth')
    implementation project(path: ':@react-native-firebase_app')
```
