### ISSUE TITLE
Support for Actionable Notifications in IOS?

### ISSUE THREAD

**Issue by Rohithzr** [invertase/react-native-firebase#3246]
I have implemented actionable notification (reply via notification) on Android and want to implement the same on IOS.

I am using the 5.x.x version of rnfirebase. I am looking for a guide I can go through.

**Comment by Ehesp** [comment]
This isn't something we're planning to support in v5 sorry due to the sizeable changes which are required. We're working on [Notifee](https://notifee.app) as a separate product which has support for this though.
