### ISSUE TITLE
Can't handle Error in React-Native-Firebase SMS Confirmation function

### ISSUE THREAD

**Issue by ikismail** [invertase/react-native-firebase#3247]
## Issue

Cant able to handle error while Phone Authentication, followed the documentation [Phone Auth Docs](https://invertase.io/oss/react-native-firebase/v6/auth/phone-auth)

```
try {
  await confirmation.confirm('12345'); // User entered code
  // Successful login - onAuthStateChanged is triggered
} catch (e) {
  console.error(e); // Invalid code
}
```

Trying to Implement Phone Authentication, Everything works fine, When I tried to enter wrong verification for handling Error I can't able to catch the error in console, Instead I'm getting the Error Screen

Here is my actual code:
```
const submitAuth = async () => {
    try {
      authLoader(true);
      await params.confirmation.confirm(smsCode);
      // Successful login - onAuthStateChanged is triggered
    } catch (e) {
      console.error(e); // Can't able to catch the Error
    }
  };
```
Is that am I missing something ?

also posted question in stackoverflow : [Stackoverflow Question](https://stackoverflow.com/q/60412126/9640128)

## Error Screenshot:
![image](https://user-images.githubusercontent.com/17190913/75420993-4acdfc00-595f-11ea-9bbd-821fd7feac8b.png)

---

#### `package.json` for react-native-firebase v6:

```
    "@react-native-firebase/app": "^6.3.1",
    "@react-native-firebase/auth": "6.3.1",
    "@react-native-firebase/database": "^6.3.1",
    "@react-native-firebase/messaging": "6.3.1",
```

**Comment by russellwheatley** [comment]
I'm afraid I can't reproduce your error. 
```
// Test phone number input
const confirmResult = await firebase.auth().signInWithPhoneNumber(TEST_PHONE_NUMBER);
  
try {
    // incorrect confirmation code
    const user = await confirmResult.confirm('435656');
  } catch (e) {
  // successfully catches the error
      console.log( e);
  }
```
This code successfully catches the error appearing on your screen. Please reconsider your implementation as I presume it is something to do with how you're calling the method.
