### ISSUE TITLE
Retrieving firebase dynamic link value with getInitialLink cutting of the link after "&" sign and returning the values only before the '&' sign in iOS.

### ISSUE THREAD

**Issue by RishavKumar-3796** [invertase/react-native-firebase#3249]
## Issue
Retrieving firebase dynamic link value with getInitialLink cutting of the link after "&" sign and returning the values only before the '&' sign

Describe your issue here

I am facing a very odd issue that the firebase dynamic link cuts off the link after "&" sign and returns the value before the '&' sign.

The links are successfully created and it is : 

    https://frendship.page.link/?link=https://frendship.in&ibi=in.frendship.app&apn=in.frendship.app&isi=1491317047&efr=1?referral_code=FRN0152584

The problem is when I try to retreive this link it just returns me `in.frendship.app` and nothing before or after.

**However this is working great in android I only face the issue in iOS.**

When I try to get the value by : 
`Linking.getInitialURL()` it returns perfectly but fails to return any val to me when the link directs to app store and then the user installs it.
---

## Project Files

My AppDelegate looks like : 
#### `AppDelegate.m`:
    #import "RNFirebaseLinks.h"

    - (BOOL)application:(UIApplication *)application
               openURL:(NSURL *)url
               options:(NSDictionary<NSString *, id> *)options {
       return [[RNFirebaseLinks instance] application:application openURL:url options:options];
    }
    
    - (BOOL)application:(UIApplication *)application
    continueUserActivity:(NSUserActivity *)userActivity
    restorationHandler:(void (^)(NSArray *))restorationHandler {
       return [[RNFirebaseLinks instance] application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
    }
-

### Javascript

I try getting the values by :

     firebase
          .links()
          .getInitialLink()
          .then(url => { alert(url) })

I create my dynamic link using : 

    let link = new firebase.links.DynamicLink("https://frendship.in", "https://frendship.page.link")
          .android
          .setPackageName("in.frendship.app")
          .ios.setBundleId("in.frendship.app");
        firebase.links().createDynamicLink(link)
          .then(url => {
            link = decodeURIComponent(url);
          })
          .catch(error => console.log("error from Dynamic Link" + error));
    }

#### `package.json`:
> My React native version is : 0.59.10  Firebase version is :
> "react-native-firebase": "5.5.7",

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

And pod version is : 

      pod 'Firebase', '~>6.13.0'
      pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios' 
      pod 'Firebase/Core', '~>6.13.0'
      pod 'Firebase/DynamicLinks', '~>6.13.0'
- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```--

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

<!--- Mark any options that apply below -->
- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by RishavKumar-3796** [comment]
Please look into ASAP.. If something is wrong please guide me .

**Comment by Zahid404** [comment]
I'm also facing the same issue. Please help.

**Comment by sweetupatel6933** [comment]
+1 I am also facing this issue

**Comment by Nehal-29** [comment]
Hi @RishavKumar-3796 ,
This is my AppDelegate.Swift
`func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
    let handled = RNFirebaseLinks().application(app, open: url, options: options)
      print("Firebase \(handled)")
    return handled
  }
  
  func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool {
   let handled = RNFirebaseLinks().application(application, continue: userActivity, restorationHandler: restorationHandler)
      print("Firebase \(handled)")
    return handled
  }`

<img width="645" alt="Screenshot 2020-06-15 at 7 44 50 PM" src="https://user-images.githubusercontent.com/41570871/84668053-c10f6200-af40-11ea-9042-c4db1c755d74.png">
<img width="551" alt="Screenshot 2020-06-15 at 7 44 34 PM" src="https://user-images.githubusercontent.com/41570871/84668066-c40a5280-af40-11ea-8cae-cca7d491946e.png">


I'm getting false returned from app delegate openURL method. Can you help me why is that happening?
