### ISSUE TITLE
storage.ref(path_string).put(blob) returns promise other than task

### ISSUE THREAD

**Issue by LucienChu** [invertase/react-native-firebase#3250]
while I am trying to upload a file, transferred to blob, it returns a promise other than a task instance.

However, if I use putFile(file_uri), then it returns a task properly, anyone have any idea?

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

{
  "name": "myapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/cameraroll": "^1.4.1",
    "@react-native-community/masked-view": "0.1.6",
    "@react-native-firebase/app": "^6.3.4",
    "@react-native-firebase/database": "^6.3.4",
    "@react-native-firebase/storage": "^6.3.4",
    "haversine": "1.1.1",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-background-upload": "5.1.0",
    "react-native-camera": "3.15.0",
    "react-native-device-info": "5.4.3",
    "react-native-fs": "^2.16.4",
    "react-native-geocoding": "0.4.0",
    "react-native-geolocation-service": "3.1.0",
    "react-native-gesture-handler": "1.5.3",
    "react-native-idle-timer": "2.1.6",
    "react-native-maps": "^0.26.1",
    "react-native-orientation": "3.1.3",
    "react-native-reanimated": "1.7.0",
    "react-native-safe-area-context": "0.6.2",
    "react-native-screens": "2.0.0-alpha.32",
    "react-native-sensors": "^5.3.3",
    "react-native-sound": "0.11.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-tts": "3.1.0",
    "react-native-voice": "0.3.0",
    "react-navigation": "4.0.10",
    "react-navigation-animated-switch": "0.4.1",
    "react-navigation-stack": "2.0.16",
    "typescript": "3.7.3"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^0.0.7",
    "babel-jest": "^25.1.0",
    "eslint": "^6.8.0",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

#### `firebase.json` for react-native-firebase v6:
import storage,  from "@react-native-firebase/storage"
import database from "@react-native-firebase/database";
export const firebaseStorage = storage();
export const firebaseDatabase = database();

```

#### `upload.js`
let task = firebaseStorage
            .ref()
            .child('videos/' + '_' + defect[1])
            .put(blob)
          console.log('task', task) // here, the task returned as a promise


## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 6.21 GB / 15.74 GB
  Binaries:
    Node: 12.16.0 - C:\Program Files\nodejs\node.EXE    
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD       
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

```
 OUTPUT GOES HERE
```

<!-- change `[ ]` to `[x]` to select an option(s) -->

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>


<!-- Thanks for reading this far down ❤️  -->
<!-- High quality, detailed issues are much easier to triage for maintainers -->

<!-- For bonus points, if you put a 🔥 (:fire:) emojii at the start of the issue title we'll know -->
<!-- that you took the time to fill this out correctly, or, at least read this far -->

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by ahanusek** [comment]
I have the same issue. Storage.ref(path_string).put(blob) returns only a promise.

 

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [X ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 6.3.4`
- **Are you using `TypeScript`?**
  - `Y` & `3.83`
  
</p>
</details>

**Comment by russellwheatley** [comment]
@LucienChu you're correct. The `put` method returns a promise. I'v created a PR that addresses the issue #3330.
