### ISSUE TITLE
Replace com.google.firebase:firebase-core with firebase-analytics?

### ISSUE THREAD

**Issue by unfrgivn** [invertase/react-native-firebase#3256]
## Documentation Feedback

I was updating my Android dependencies and noticed this on the [Firebase SDK site](https://firebase.google.com/support/release-notes/android)

So first thing I did was come here and search for those package names and didn't turn up much. I am using `5.5.6` but I checked the install docs for v5 and v6 and didn't see this mentioned either. Am I missing something here?

> No longer add the Android library **com.google.firebase:firebase-core**.
>
> This SDK included the Firebase SDK for Google Analytics. Now, to use Analytics (or any of the Firebase products that require or recommend the use of Analytics), you need to explicitly add the Analytics dependency: **com.google.firebase:firebase-analytics:17.2.2**

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by unfrgivn** [comment]
Sorry I suppose I should clarify, it looks like v6 install instructions just say that core is automatically installed and you should remove the explicit implementation from gradle.build but makes no mention of the change from core to analytics. 

For v5, should we simply stop upgrading at `com.google.firebase:firebase-core:17.2.2`? I realize these docs are no longer being maintained but enough people are stuck on v5 for now due to the changes with Push Notes.

I'm currently using the following with `react-native-firebase:5.5.6` + `react-native:0.59.10` without problem but I was gonna try to keep upgrading these until I ran into incompatibilities. Did I miss a compatibility guide already maintained for v5 and if not should we start one here?

```
implementation "com.google.android.gms:play-services-base:17.1.0"
implementation "com.google.firebase:firebase-core:17.1.0"
implementation "com.google.firebase:firebase-messaging:19.0.0"
```

**Comment by mikehardy** [comment]
I'm not aware of any problems upgrading all of the way to current. I think the change is mostly related to disentangling analytics for privacy reasons. You may follow their instructions and things should still work. I'm on rn61 but still rnfb v5 and keeping it on track for up to date upstream sdk guidance. Have you tried it?

**Comment by unfrgivn** [comment]
I have not yet @mikehardy but when looking at the changelog on Google it didn't seem like a recent change and I was surprised to not see anyone else asking about this. 

I'm in the middle of a critical app deployment so I won't be testing this right away, but I will test swapping out these packages once things calm down.

**Comment by mikehardy** [comment]
I am going to preliminarily close this then pending your test, as I have done it and it works for me (I no longer have core at all as a dependency in my app/build.gradle)

```groovy
    implementation platform("com.google.firebase:firebase-bom:24.5.0")
    implementation "com.google.firebase:firebase-auth"
    implementation "com.google.firebase:firebase-analytics"
    implementation "com.google.firebase:firebase-perf"
    implementation "com.google.firebase:firebase-config"
    implementation "com.google.firebase:firebase-functions"
    implementation "com.google.firebase:firebase-storage"
    implementation "com.google.firebase:firebase-dynamic-links"
    implementation "com.google.firebase:firebase-firestore"
    implementation "com.google.firebase:firebase-messaging"
    implementation "com.google.firebase:firebase-iid"
    implementation 'com.crashlytics.sdk.android:crashlytics'
```
