### ISSUE TITLE
Cannot read property 'googleApiAvailability' of undefined' ios simulator throws

### ISSUE THREAD

**Issue by gvimlan95** [invertase/react-native-firebase#326]
Hey everyone

I am getting the above error from the simulator 
> Cannot read property 'googleApiAvailability' of undefined'

after adding this line of code to the index.ios.js

`
import RNFirebase from 'react-native-firebase'
const firebase = RNFirebase.initializeApp({
      debug:true
    });`

Any reason for such error?

Thank you

**Comment by Ehesp** [comment]
Try seeing if https://github.com/invertase/react-native-firebase/issues/282 helps you out.

Usually means something hasn't been installed properly.

**Comment by gvimlan95** [comment]
@Ehesp Thank you for your reply.

I have tried to redo the project 4 times and I am getting the same error.
[http://invertase.io/react-native-firebase/#/installation-ios](React Native Firebase), I followed this guide thoroughly and got the same error each time.

**Comment by Ehesp** [comment]
Can we see your Pod lock file please.

**Comment by gvimlan95** [comment]
@Ehesp 

This is the pod lock file.

PODS:
  - Firebase/Core (4.0.4):
    - FirebaseAnalytics (= 4.0.2)
    - FirebaseCore (= 4.0.4)
  - FirebaseAnalytics (4.0.2):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseCore (4.0.4):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - nanopb (~> 0.3)
  - FirebaseInstanceID (2.0.0):
    - FirebaseCore (~> 4.0)
  - GoogleToolboxForMac/Defines (2.1.1)
  - GoogleToolboxForMac/NSData+zlib (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - nanopb (0.3.8):
    - nanopb/decode (= 0.3.8)
    - nanopb/encode (= 0.3.8)
  - nanopb/decode (0.3.8)
  - nanopb/encode (0.3.8)
  - React (0.47.1):
    - React/Core (= 0.47.1)
  - React/BatchedBridge (0.47.1):
    - React/Core
    - React/cxxreact_legacy
  - React/Core (0.47.1):
    - Yoga (= 0.47.1.React)
  - React/cxxreact_legacy (0.47.1):
    - React/jschelpers_legacy
  - React/jschelpers_legacy (0.47.1)
  - RNFirebase (2.1.0):
    - React
  - Yoga (0.47.1.React)

DEPENDENCIES:
  - Firebase/Core
  - React/BatchedBridge (from `../node_modules/react-native`)
  - React/Core (from `../node_modules/react-native`)
  - RNFirebase (from `../node_modules/react-native-firebase`)
  - Yoga (from `../node_modules/react-native/ReactCommon/yoga`)

EXTERNAL SOURCES:
  React:
    :path: ../node_modules/react-native
  RNFirebase:
    :path: ../node_modules/react-native-firebase
  Yoga:
    :path: ../node_modules/react-native/ReactCommon/yoga

SPEC CHECKSUMS:
  Firebase: 1492bf04e1b73a7353b4fb2cf5a20bac9692f341
  FirebaseAnalytics: ad41720e3e67fc63fbe3d2948d3e26932a8de311
  FirebaseCore: cfc042628ef9f20debe09c0eb683135fcd404cb4
  FirebaseInstanceID: 9fbf536668f4d3f0880e7438456dabd1376e294b
  GoogleToolboxForMac: 8e329f1b599f2512c6b10676d45736bcc2cbbeb0
  nanopb: 5601e6bca2dbf1ed831b519092ec110f66982ca3
  React: f705239a901cb3f95445c34468e5b37b6f80a0d4
  RNFirebase: dcdb1be13628827647bba47592d4d19fba5ba84d
  Yoga: 13a12502dfabb4c75b914071dcb542af800deed4

PODFILE CHECKSUM: ecfd89149582e5a2c86df44277fa0c6854ecdc49

COCOAPODS: 1.3.1

**Comment by gvimlan95** [comment]
@Ehesp 

This is the pod lock file. 
PODS:
  - Firebase/Core (4.0.4):
    - FirebaseAnalytics (= 4.0.2)
    - FirebaseCore (= 4.0.4)
  - FirebaseAnalytics (4.0.2):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseCore (4.0.4):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - nanopb (~> 0.3)
  - FirebaseInstanceID (2.0.0):
    - FirebaseCore (~> 4.0)
  - GoogleToolboxForMac/Defines (2.1.1)
  - GoogleToolboxForMac/NSData+zlib (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - nanopb (0.3.8):
    - nanopb/decode (= 0.3.8)
    - nanopb/encode (= 0.3.8)
  - nanopb/decode (0.3.8)
  - nanopb/encode (0.3.8)
  - React (0.47.1):
    - React/Core (= 0.47.1)
  - React/BatchedBridge (0.47.1):
    - React/Core
    - React/cxxreact_legacy
  - React/Core (0.47.1):
    - Yoga (= 0.47.1.React)
  - React/cxxreact_legacy (0.47.1):
    - React/jschelpers_legacy
  - React/jschelpers_legacy (0.47.1)
  - RNFirebase (2.1.0):
    - React
  - Yoga (0.47.1.React)

DEPENDENCIES:
  - Firebase/Core
  - React/BatchedBridge (from `../node_modules/react-native`)
  - React/Core (from `../node_modules/react-native`)
  - RNFirebase (from `../node_modules/react-native-firebase`)
  - Yoga (from `../node_modules/react-native/ReactCommon/yoga`)

EXTERNAL SOURCES:
  React:
    :path: ../node_modules/react-native
  RNFirebase:
    :path: ../node_modules/react-native-firebase
  Yoga:
    :path: ../node_modules/react-native/ReactCommon/yoga

COCOAPODS: 1.3.1

**Comment by chrisbianca** [comment]
@gvimlan95 Are you still experiencing issues with this?  If so, please try the latest version of RNFirebase (2.2.2) - there have been a few tweaks to improve project compatibility since 2.1.0
