### ISSUE TITLE
[Android] Cannot retrieve FCM token Error: SERVICE_NOT_AVAILABLE (reopen for #2285)

### ISSUE THREAD

**Issue by CoSNaYe** [invertase/react-native-firebase#3266]
## Issue

This is basically the same issue as https://github.com/invertase/react-native-firebase/issues/2285. But, according to @mikehardy's reply, he seems to categorize this into a network issue, so I guess no fixes have been implemented.

Thanks for the reply. After wrapping the code into a Network status check, this type of error has decreased a lot from my project. However, I'm still getting some. 

After researching the issue online, [this article](https://snow.dog/blog/dealing-with-service_not_available-google-cloud-messaging) addresses some other situations which may cause this issue also.

For example: 
1. App gets an update
2. Android System update

These cases are more like the normal edge-cases that we should handle. But, since the article is quite old (written in 2014) and sorry that I'm not familiar with Android (JAVA). Could anyone help to check if the fixes mentioned in the article should be put in RN as well?

Thanks

---

## Project Files

---

## Environment

**`react-native info` output:**

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 43.61 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-25 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! You skipped a big chunk of the template. What react-native-firebase are we talking about here?
