### ISSUE TITLE
🔥 querySnapshot.docChanges() hang android on query with ~700 docs. (6.2.0)

### ISSUE THREAD

**Issue by lironsher** [invertase/react-native-firebase#3268]
## Issue
I'm using firestore to sync documents, I'm using the following command:

` this.ref.where('members', 'array-contains', uid).onSnapshot({
      error: e => console.error(e),
      next: querySnapshot => {
        this.onSnapshot(querySnapshot);
      },
    });`

`async onSnapshot(list) {
    LogDebug('on snapshot');
    const res = [];
    let promises = [];
    list.docChanges().forEach(change => {
      const p = this.handleDoc(change);
      if (p) {
        promises.push(p);
      }
    });
    LogDebug('onSnapshot after');
    Promise.all(promises).then(res => {
      LogDebug(`event count: ${res.length}`);
      this.handleEvents(res);
    });
  }`

when onsnapshot is invoked my app hangs and releases only after docChanges() finished.

--

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
  "@react-native-firebase/analytics": "^6.2.0",
    "@react-native-firebase/app": "^6.2.0",
    "@react-native-firebase/auth": "^6.2.0",
    "@react-native-firebase/crashlytics": "^6.2.0",
    "@react-native-firebase/dynamic-links": "^6.2.0",
    "@react-native-firebase/firestore": "^6.2.0",
    "@react-native-firebase/functions": "^6.2.0",
    "@react-native-firebase/iid": "^6.2.0",
    "@react-native-firebase/in-app-messaging": "^6.2.0",
    "@react-native-firebase/messaging": "^6.2.0",
    "@react-native-firebase/ml-natural-language": "^6.2.0",
    "@react-native-firebase/ml-vision": "^6.2.0",
    "@react-native-firebase/perf": "^6.2.0",
    "@react-native-firebase/remote-config": "^6.2.0",
    "@react-native-firebase/storage": "^6.2.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX? 
- [X] my application is an AndroidX application?
- [X ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
    Memory: 869.20 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/opt/node@10/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [X] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 6.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. FireStore`
- **Are you using `TypeScript`?**
  - `N` & ``
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
To clarify, it's the `onSnapshot` call hanging, not the `docChanges` call?

**Comment by lironsher** [comment]
after more testing, I believe both calls,

Also, the same code was working well in version 5.4

**Comment by Ehesp** [comment]
Could you send a mock document (replicate the type of data/size)? Should be fairly ok to replicate.

**Comment by lironsher** [comment]
Hi
Mock document will be hard to replicate, I can tell that the Avg size is 1908 bytes

**Comment by lironsher** [comment]
also same issue in 6.3.2,
Im considering to downgrade to 5.4

**Comment by Ehesp** [comment]
The volume of data isn't the sole issue, it's down to volume + types. 

We have to bridge a lot of data to native and back with Firestore, and the more data that goes across that bridge the slower the call gets. In v6 we slimmed down the size, however there could just be a single data type causing issues still.

**Comment by lironsher** [comment]
After downgrade to 5.4 getting better performance

**Comment by Ehesp** [comment]
That doesn't solve the issue in v6, but in fact highlights it can be sorted for v6... Please send your data structure over so we can help get it sorted.
