### ISSUE TITLE
App crashes on debug 

### ISSUE THREAD

**Issue by uendar** [invertase/react-native-firebase#3277]
I get a problem when i install react-native-firebase on RN 0.61.5. When i run on debug mode the app executes  but as it opens it crashes immediately.

> {
  "name": "X",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/google-signin": "^3.0.4",
    "@react-native-community/netinfo": "^5.5.1",
    "@react-native-firebase/app": "^6.3.4",
    "base64-js": "^1.3.1",
    "create-react-native-module": "^0.16.0",
    "dateformat": "^3.0.3",
    "formik": "^2.1.4",
    "global": "^4.4.0",
    "install": "^0.13.0",
    "json2csv": "^4.5.4",
    "mime": "^2.4.4",
    "moment": "^2.24.0",
    "native-base": "^2.13.8",
    "prop-types": "^15.7.2",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-charts-wrapper": "^0.5.7",
    "react-native-document-picker": "^3.2.4",
    "react-native-elements": "^1.2.7",
    "react-native-exit-app": "^1.1.0",
    "react-native-file-picker": "0.0.19",
    "react-native-file-viewer": "^2.0.2",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-google-drive-api-wrapper": "^1.2.0",
    "react-native-html-to-text": "0.0.5",
    "react-native-image-crop-picker": "^0.28.0",
    "react-native-image-picker": "^2.3.1"
  },
  "devDependencies": {
    "@babel/core": "7.8.7",
    "@babel/runtime": "7.8.7",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.8.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.4",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by mikehardy** [comment]
Skipped template, no crash trace, no indication of platform, nothing to work with.
I see you are on v6, before logging a fresh issue with the template filled in, clone this repo and run this script https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh and execute the app in debug, it works, indicating you have a project integration issue somehow - the difference between the throwaway app generated and your app will be the root cause
