### ISSUE TITLE
E/Fabric: Failed to retrieve settings from [Android]

### ISSUE THREAD

**Issue by Acetyld** [invertase/react-native-firebase#3279]
E/Fabric: Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/nl.dactec.mrbeastsoundboard/settings

So yhea.. we are so stuck in this. We are rebuilding our soundboard succes app in react native, we are 95% done! But.. firebase crashlytics is being a pain... 
We keep getting the above error.

We are using flavours/whitelabeling.
![afbeelding](https://user-images.githubusercontent.com/55088242/76152383-5d62d680-60bf-11ea-8013-5fbf76e64f66.png)
![afbeelding](https://user-images.githubusercontent.com/55088242/76152388-69e72f00-60bf-11ea-95d0-c8967ddb7082.png)
![afbeelding](https://user-images.githubusercontent.com/55088242/76152394-74092d80-60bf-11ea-8371-c40c0b037025.png)

We added 
- **apply plugin: 'com.google.gms.google-services'** to the **app/build.gradle**
- **classpath 'com.google.gms:google-services:4.3.3'** to the **/build.gradle**

**Comment by mikehardy** [comment]
Please don't skip the template, and please post text not images, I'm going to close this because we really need the template - please open a new one but fill it in. You can skip iOS if it's android only

**Comment by mikehardy** [comment]
You may find this useful though - it does a full crashlytics integration (linked directly to that line): https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh#L69
