### ISSUE TITLE
Missing documentation of App Indexing

### ISSUE THREAD

**Issue by frankyjuang** [invertase/react-native-firebase#3283]
## Documentation Feedback

Thanks for the awesome work. One small question not sure if it's suitable here. 

According to the npm package page of [@react-native-firebase/indexing](https://www.npmjs.com/package/@react-native-firebase/indexing), app indexing is deprecated. Can we have more information about why it is not supported anymore? The package was documented in v6 changelog at some point, but then disappeared after v6 changelog is moved to invertase website. 

[changelog history](https://github.com/invertase/react-native-firebase/commit/a498d011cbd1e5d4022287d9f18aaa83e365273e#diff-4ac32a78649ca5bdd8e0ba38b7006a1e)

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Okay so you've confused me :D App index was being deprecated by Firebase, however now when I go on their website there is a load of docs, and the API is totally different.

Trying to find their notice about it being deprecated...!

**Comment by Ehesp** [comment]
Okay so that was Invites which was deprecated...! Long day.

I believe the reason there is no module is because there is nothing we can provide. If you take a look at the iOS guide, you simply add some setting to your project via XCode and away you go: https://firebase.google.com/docs/app-indexing/ios/app

**Comment by frankyjuang** [comment]
Thanks for clarifying it!
