### ISSUE TITLE
Admob propType not exists

### ISSUE THREAD

**Issue by jcarlosjl** [invertase/react-native-firebase#329]
Hi,

I have problems with the admob module, I have the follow code:

```
const AdRequest = firebase.admob.AdRequest;
const NativeExpress = firebase.admob.NativeExpress;
firebase.admob().initialize('ca-app-pub-xxxxxxxxxxx~zzzzzzzz');
const request = new AdRequest();
<NativeExpress 
            size="SMART_BANNER"
            request={request.build()}
            unitId="ca-app-pub-xxxxxxxxxxxxx/zzzzzzz"
/>
```

When I run into the app I have this error:

_`AdMobComponent` has not propType for native prop `RNFirebaseAdMobNativeExpress.testID` of native type String_

### Environment

1. Target Platform: Android
2. Development Operating System: macOS Sierra
3. Build tools : Google service 3.0.0 and Firebase core / ads 11.0.4
4. React Native version: 0.41.2
5. RNFirebase Version: 2.0.5

**Comment by Ehesp** [comment]
Hey, is this a yellow box or throwing a red box error?

**Comment by jcarlosjl** [comment]
@Ehesp is a red box error

**Comment by jcarlosjl** [comment]
This is the specific error:

![screenshot_2017-08-10-14-01-19](https://user-images.githubusercontent.com/27894115/29187251-ab8541de-7dd4-11e7-8521-db5c34ed2776.png)

**Comment by Ehesp** [comment]
@jcarlosjl I can't reproduce this :( That error usually appears when there's a prop being passed down to the native side, which the `SimpleViewManager` doesn't know how to handle. Are you sure it's not finding it's way into the component prop?

**Comment by jcarlosjl** [comment]
@Ehesp I am not sure, as you can see the code is very simple. I don't know if something is wrong with my configuration or something with the version of the build tools

**Comment by Ehesp** [comment]
I can screen share if you like - if you're on Discord give me a ping.

**Comment by jcarlosjl** [comment]
@Ehesp shure, what is your DiscrodTag?

**Comment by Ehesp** [comment]
I'm Alias on here: https://discordapp.com/invite/t6bdqMs

**Comment by chrisbianca** [comment]
@Ehesp Did you ever get to the bottom of this?

@jcarlosjl Are you still experiencing issues?

**Comment by Ehesp** [comment]
Hi @jcarlosjl

Were you running tests against your app or just standard usage? I believe testID is applied to a component when accessibility is enabled, however I did think the ViewPropTypes would take care of this.

**Comment by Salakar** [comment]
Closing due to no response, feel free to reply if this needs re-opening.
