### ISSUE TITLE
catch not handled in android 

### ISSUE THREAD

**Issue by andresd** [invertase/react-native-firebase#3290]
## Issue

when signInWithEmailAndPassword fails exceptions are not handled and a red screen is shown.
(on IOS work as expected)

try {
  await firebase.auth.signInWithEmailAndPassword(email, password);
}
 catch(e) {
  console.log(e); // NOT GETTING HERE
}

instead I get this:

![image](https://user-images.githubusercontent.com/4082841/76316286-00e00100-62e3-11ea-83b7-cb9c071f63cd.png)
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
"@react-native-firebase/app": "^6.3.4",
"@react-native-firebase/auth": "^6.3.4",
```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```
</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.3.4`
- **`Firebase` module(s) you're using that has the issue:**
  - `auth`
- **Are you using `TypeScript`?**
  - `Yes` & `3.7.5`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Phaen** [comment]
Looks like this method calls `console.error` with the error, which interrupts the app and is not a catchable exception, rather than throwing the error. I'm looking into fixing this, thanks!

**Comment by MayoudP** [comment]
Got the same Android React-Native 0.62. The catch is not called if authentification failed.

**Comment by yunusemregul** [comment]
I get this on react-native 0.62.2, react-native-firebase/auth 8.1.1. Code below does not catch the error:
`    auth()
      .signInWithEmailAndPassword(email, pass)
      .then(() => {
        console.log("User with email '" + email + "' logged in!");
      })
      .catch((error) => {
        console.log(error);

        //console.error(error);
      });`

**Comment by kalyanteja** [comment]
Don't believe it is fixed still. I still get thrown an uncaught error. Is this fixed?

**Comment by mikehardy** [comment]
No progress I'm aware of based on the thread here, it just staled out. Needs someone to adopt it as their personal missions and crush it, like all bugs deserve :smile: . Could be you? :pray:
