### ISSUE TITLE
6.3.4 - [auth/internal-error] An internal error has occurred, please try again

### ISSUE THREAD

**Issue by warunacds** [invertase/react-native-firebase#3297]
When I try to use in iOS signInWithPhoneNumber  , I'm getting following error on the devices. Again I'm not trying this on the simulator. This only happens on iOS, it works fine on Android. 

[info][tid:com.facebook.react.JavaScript] { [Error: [auth/internal-error] An internal error has occurred, please try again.]
  line: 180802,
  column: 28,
  sourceURL: '/private/var/containers/Bundle/Application/7C461AB7-9FA4-4F24-B803-3190339E66B6/Loke.app/main.jsbundle' }

I import` import auth from '@react-native-firebase/auth';`

and execute. 
`const confirmation = await auth().signInWithPhoneNumber(fullNumber);`

This is very there error is happening. on the return line
`return new _PhoneAuthListener.default(this, phoneNumber, _autoVerifyTimeout, _forceResend);
`
```
{
      key: "verifyPhoneNumber",
      value: function verifyPhoneNumber(phoneNumber, autoVerifyTimeoutOrForceResend, forceResend) {
        var _forceResend = forceResend;
        var _autoVerifyTimeout = 60;

        if ((0, _common.isBoolean)(autoVerifyTimeoutOrForceResend)) {
          _forceResend = autoVerifyTimeoutOrForceResend;
        } else {
          _autoVerifyTimeout = autoVerifyTimeoutOrForceResend;
        }

        return new _PhoneAuthListener.default(this, phoneNumber, _autoVerifyTimeout, _forceResend);
      }
```

**Comment by chiefchief** [comment]
has same issue

**Comment by lyseiha** [comment]
+1

**Comment by lyseiha** [comment]
simulator working as normal, but when i run on ios device i got that error.

**Comment by 0xori** [comment]
same here, working on a simulator but not on a real device
