### ISSUE TITLE
Push Notifications are disappeared automatically once the app is opened. 

### ISSUE THREAD

**Issue by shan229** [invertase/react-native-firebase#3298]
Push Notifications are disappeared automatically once the app is opened. 

I have used the library in many apps earlier, with same framework versions but haven't faced this issue. 
Please provide suggestions or link to any other related issues

library version - 5.6.0

**Comment by Ehesp** [comment]
Please show some code/usage of how you create a notification...

**Comment by 0length** [comment]
i gote same issues
