### ISSUE TITLE
Error: You attempted to use a firebase module that's not installed on your Android project by calling firebase.notifications().

### ISSUE THREAD

**Issue by hardikvirani6** [invertase/react-native-firebase#3301]
![Screenshot_1584169330](https://user-images.githubusercontent.com/39665231/76677493-f2e8f380-65f4-11ea-9e9c-24ba0b8734a1.png)

    "react-native": "0.61.5",
    "react-native-firebase": "^5.6.0",

CODE:

import firebase, { notifications } from 'react-native-firebase';
const notificationOpen = await firebase
      .notifications()
      .getInitialNotification();

**Comment by mikehardy** [comment]
Please do not ignore the template.
Please do not post images, text is sufficient
Please examine the documentation for notification integration, and see how each module is integrated in this example (clone it and run it) - you can add notifications easily following the pattern: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh#L100

I linked directly to the stanza that adds firestore. I don't display how to do notifications but the addition will be similar
