### ISSUE TITLE
[iOS] Push notifications are not received on all devices (onMessage triggered instead of onNotification)

### ISSUE THREAD

**Issue by ugomarinelli1** [invertase/react-native-firebase#3304]
## Issue

Hello ! 

I implemented an app in react-native that send push notifications via Firebase. Most of the time, it is working well, but sometimes, and very randomly, the push notifications are not received by some iOS  devices (mostly iOS 13).
To test my push notifications, I am running my app through XCODE, in a real device. 
I am sending my push notification via POSTMAN (payload below).

For the devices receiving my push notifications correctly, **onNotification** is triggered everytime (foreground and background).

For the devices not receiving my push notifications, **onMessage** is triggered (only on foreground).

I am a bit confused, because in some issues some put **FirebaseAppDelegateProxyEnabled** to true , some to false, some to FALSE, but as a String ... 

Thanks a lot for your help !

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
    "@react-native-community/netinfo": "^4.7.0",
    "intl": "^1.2.5",
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-dialog": "^5.6.0",
    "react-native-dialog-input": "^1.0.7",
    "react-native-elements": "^1.2.0",
    "react-native-firebase": "^5.6.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-htmlview": "^0.14.0",
    "react-native-pdf": "^5.1.4",
    "react-native-picker-select": "^6.3.2",
    "react-native-render-html": "^4.1.2",
    "react-native-restart": "0.0.12",
    "react-native-slideshow": "^1.0.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-swiper": "^1.5.14",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.11.1",
    "react-redux": "^7.1.0",
    "redux": "^4.0.4",
    "redux-persist": "^5.10.0",
    "rn-fetch-blob": "^0.10.16",
    "typescript": "^3.5.3"
  },
```
Here is the Payload for the notification I am sending via POSTMAN : 

```json
{
"to" : "my_FCM_token",
"priority" : "high",
"notification" : {
    "body" : "Body TEST",
    "title": "TEST Notification",
    "vibrate": 1,
    "sound": 1
},
"data" : {
    "key" : "value"
}
}
```

#### `App.js` 

```javascript
async componentDidMount() {

  firebase.messaging().hasPermission().then(enabled => {
    if (enabled) {
      firebase.messaging().getToken().then(token => {
        global.token = token;
      })
    } else {
      firebase.messaging().requestPermission()
        .then(() => {
          alert("Permission Accepted", error)
        })
        .catch(error => {
          alert("Permission Denied", error)
        });
     }
  });

  this.initialNotificationListener = firebase.notifications().getInitialNotification().then((notificationOpen: NotificationOpen) => {
    alert("Getting initial Notification")
  });

  this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen: NotificationOpen) => {
    alert("onNotificationOpened triggered")
  });

  this.notificationListener = firebase.notifications().onNotification((notification: Notification) => {
    alert("onNotification triggered")
  });

  this.onMessageListener = firebase.messaging().onMessage(async (remoteMessage) => {
    alert("onMessage triggered")
  });
}

componentWillUnmount() {
this.notificationOpenedListener();
this.notificationDisplayedListener();
this.notificationListener();
this.initialNotificationListener();
this.onMessageListener();
}
```
</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
  pod 'Firebase/Core', '~> 6.19.0'
  pod 'Firebase/Functions', '~> 6.19.0'
  pod 'Firebase/Messaging', '~> 6.19.0'
  pod 'Firebase/Auth', '~> 6.19.0'
```

#### `AppDelegate.m`:

```objc
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    // FIREBASE CONFIG
    [FIRApp configure];

    // SETTING ROOT VIEW CONTROLLER
    RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
    RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                               moduleName:@"MyModule"
                                        initialProperties:nil];
    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
    UIViewController *rootViewController = [UIViewController new];
    rootViewController.view = rootView;
    self.window.rootViewController = rootViewController;
    [self.window makeKeyAndVisible];
    [RNSplashScreen show];
    return YES;
 }  
```

</p>
</details>

---

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 5.6.0
- **`Firebase` module(s) you're using that has the issue:**
  - Messaging
- **Are you using `TypeScript`?**
  - Yes 3.5.3
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Salakar** [comment]
This has been fixed in #3339 - thanks
