### ISSUE TITLE
For unsubscribing all snapshot on logout

### ISSUE THREAD

**Issue by abhi-nahi** [invertase/react-native-firebase#3306]
Hello there,

I don't know if this already exists or not, but I want to know if we can have something to unsubscribe all the running snapshots when we logout from the firebase ...!!!

**Comment by Ehesp** [comment]
There's nothing built in for this, however you could do something which holds it in the global scope:

```js
const subscribers = [];

...

const usersSubscriber = firestore().collection('users').onSnapshot(...);
const postsSubscriber = firestore().collection('posts').onSnapshot(...);

subscribers.push(usersSubscriber);
subscribers.push(postsSubscriber);

...

function onSignOut() {
  subscribers.forEach(subscriber => subscriber());
}
```

**Comment by theSoberSobber** [comment]
Hi, Sorry to comment on an old issue, but how is the subscriber array persisting over app restarts? I am trying to do this to store my unsubscribe's from onTokenRefresh and backgroundMessageHandler, so that I can remove them on signout

**Comment by mikehardy** [comment]
@theSoberSobber a subscriber is in memory / local app state, just like a counter variable for a while loop. react-native-firebase makes no effort to persist those and in fact on hot reload it removes them at the native layer during the teardown process before the app reloads. It is assumed that any subscriptions you need to make will be remade by your code in a useEffect or similar. This is a react-native question though as it is more general "how to I handle application state during app restarts" as opposed to a react-native-firebase question
