### ISSUE TITLE
firestore.FieldPath.documentId() doesn't work with orderBy - firestore/invalid-argument

### ISSUE THREAD

**Issue by hutsi** [invertase/react-native-firebase#3310]
## Issue

hello every1,
my issue case is pretty simple & straight-forward:
```
await firestore().collection('user')
    .where(firestore.FieldPath.documentId(), 'in', userIds)
    .orderBy('added', 'desc')
    .get()
```
fails with:

![image](https://user-images.githubusercontent.com/2057586/76792329-df47b380-67d3-11ea-8f34-381eb2c6478f.png)

however it works well when I remove the `orderBy` statement..

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```
</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 25.71 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.5.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.1 => 16.8.1
    react-native: 0.61.3 => 0.61.3
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.3.4`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
I just tried this with the web SDK, and get the following error:

`FirebaseError: inequality filter property and first sort order must be the same: __name__ and added`

Looks like we miss this check on the JS side of our code, so it errors on native (which doesnt provide user friendly messages like the web SDK).

**Comment by V3RT1AG0** [comment]
Error: firebase.firestore().collection().orderBy() Invalid query. Query.where() fieldPath parameter: 'FirestoreFieldPath' cannot be used in conjunction with a different Query.orderBy() parameter

I am getting above error even when I am using FirestoreFieldPath as first orderBy parameter. As mentioned [here](https://github.com/googleapis/nodejs-firestore/issues/990#issuecomment-754737700) it should work. Below is my block of code. @Ehesp were you able to resolve your issue?

```
globalGroups
          .where(firestore.FieldPath.documentId(), 'in', conversationIdArr)
          .orderBy(firestore.FieldPath.documentId())
          .orderBy('updatedAt') //no error after removing this line 
          .get()
```

**Comment by mikehardy** [comment]
@V3RT1AG0 please do not post on old issues. If you are experiencing a problem, please open a new issue following the template so we may provide help that is correct for your context.

As a side note - please ensure you are using current versions of everything (react-native-firebase, plus the underlying native SDKs) so we aren't chasing possibly-closed problems

Thanks

**Comment by djaBalasbas** [comment]
I got the same issue
