### ISSUE TITLE
Content-available is missing from the remote message

### ISSUE THREAD

**Issue by fruedaCode** [invertase/react-native-firebase#3312]
I have made the following change in order to emit the notification from the native code to he RN listener.
https://github.com/invertase/react-native-firebase/blob/cf0bbdcaf06a3f1ba8c210ef1c03bcfff10b5522/packages/messaging/ios/RNFBMessaging/RNFBMessagingAppDelegateInterceptor.m#L67

Instead of content-avaiable I'm receiving @alert the data in an entry called alert.
![image](https://user-images.githubusercontent.com/22854367/76872973-6f860700-686d-11ea-824d-59c62330a135.png)

So the line should look like this for my case:
```Objective-C
if (userInfo[@"aps"] && ((NSDictionary *) userInfo[@"aps"]).count >= 1 && userInfo[@"aps"][@"alert"]) {
```

Do you think you can include this change please?

Thanks!

**Comment by Ehesp** [comment]
Can you submit a PR so we can review please. Thanks
