### ISSUE TITLE
Suggestion: mention non-pod based installation of RNFirebase in docs

### ISSUE THREAD

**Issue by kyle-ssg** [invertase/react-native-firebase#332]
After facing several issues trying to install your module via pods including the following mentioned below as well as module collisions caused by having the React pod, I simply ended up adding your RNFirebase to libraries and installed Firebase with pods. It might be worth offering this as a suggestion to mitigate any issues, especially seeing as adding RNFirebase itself to pods offers little value.

https://github.com/invertase/react-native-firebase/issues/324
https://github.com/invertase/react-native-firebase/issues/277
https://github.com/invertase/react-native-firebase/issues/252

**Comment by Jonovono** [comment]
Can you go into a bit more detail about what you did @kyle-ssg

**Comment by kyle-ssg** [comment]
Hey @Jonovono sure thing - glad to help out.

1: Install whatever firebase modules you need via pods, for example my Podfile looks like this :  
<img src="https://image.prntscr.com/image/IYtIoX7lSSqlKm37uAvfyA.png"/> 

As you can see this also allows for you to keep the ```use_frameworks!``` flag if some of your other dependencies require (a few people have mentioned this from glancing through issues).

2. Drag the RNFirebase.xcodeproj from node_modules/react-native-firebase/  and ensure it's added to the lnk binary with libraries flag.

<img src="https://image.prntscr.com/image/zzKQdi9zSl2Jdz7Xygx6Mw.png"/>
<img src="https://image.prntscr.com/image/fldGFhRXST_nEaR6rpQonA.png"/>

**Comment by Jonovono** [comment]
@kyle-ssg awesome seems to work. Wonder why this isn't suggested hah.

**Comment by kyle-ssg** [comment]
Yeah I'd definitely rather do this. I mainly tried this as I also always try to avoid adding React to podfile, it's caused loads of issues in the past for the projects I've done - some of which only occur when archiving. 

Anyway, glad I could help out 👍

**Comment by chrisbianca** [comment]
@kyle-ssg Thanks for this - we made some changes yesterday that have smoothed over the manual linking of the library.  We just haven't had a chance to bring the documents back in line yet and offer it as an option.  Good news is, that we should also be able to support react-native link which has also previously caused us some issues

**Comment by tirrorex** [comment]
For people that have troubles to build this on swift, the solution of @kyle-ssg works, just add firebase through your podfile and add ${BUILT_PRODUCTS_DIR} recursive to RNFirebase target framework search paths.
It's a workaround but it works so...
