### ISSUE TITLE
Message sent from FCM has empty data - RNFirebase v6

### ISSUE THREAD

**Issue by nenjamin2405** [invertase/react-native-firebase#3321]
## Issue

I'm using React Native Firebase v6 together with RN 0.61.5, I followed exactly every step in the new documentation, when I try to send a test message from FCM console, the method `messaging().onMessage` receives new remoteMessage with content which its data key is always an empty object although I already inputted Notification title and Notification text in the FCM console.

The sample message that I got so far:
```
{"collapseKey": "my-app-bundle-id", "data": {}, "from": "155942987490", "messageId": "0:1584586227493392%b7d4394cb7d4394c"}
```
I've tried different methods to send the message (send via messaging().getToken() and send via targets of my app) but the data is always empty. Any idea why this happened, many thanks!

---

### Javascript

<details><summary>Click To Expand</summary>

```javascript
useEffect(() => {
    async function requestNotiPermission() {
      const data = await requestNotifications(['alert', 'sound']);
      console.log('data', data);
    }
    requestNotiPermission();
    async function registerAppWithFCM() {
      console.log('register');
      await messaging().registerForRemoteNotifications();
    }
    registerAppWithFCM();
    const unsubscribe = messaging().onMessage(async remoteMessage => {
      console.log('FCM Message Data:', remoteMessage);
    });

    return () => {
      unsubscribe();
    };
  }, []);
```

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```
</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 137.68 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.5.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - "@react-native-firebase/app": "^6.3.4",
- **`Firebase` module(s) you're using that has the issue:**
  - "@react-native-firebase/messaging": "^6.3.4",
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Hey is this android or ios?

**Comment by Ehesp** [comment]
Guessing it's iOS looking at our code, looking into it.

**Comment by nenjamin2405** [comment]
Hi @Ehesp , many thanks for your support. I already tried to re-install everything again, follow everything in these docs: 
https://invertase.io/oss/react-native-firebase/v6/messaging/ios-configure-apns, https://invertase.io/oss/react-native-firebase/v6/messaging/ios-xcode-project-capabilities

**Comment by Ehesp** [comment]
We know what the problem is, just going to be a fix as part of a larger update on messaging. Currently XCode is giving us some pains testing terminated apps...

**Comment by Ehesp** [comment]
Hey all 👋 There's a draft PR available which fixes this issue and others, please check it out: https://github.com/invertase/react-native-firebase/pull/3339

We'll be doing a RC release once a few more things are implemented.
