### ISSUE TITLE
Build IOS fails on RN 0.61.3 after running npx react-native run-ios

### ISSUE THREAD

**Issue by DanMCX** [invertase/react-native-firebase#3322]
**Environment**

Target Platform (e.g. iOS, Android): iOS
Development Operating System (e.g. macOS Sierra, Windows 10): macOS Catalina 10.15.3
Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Xcode, iOS 13.2.2

React Native version (e.g. 0.45.1): 0.61.3
RNFirebase Version (e.g. 2.0.2): ^5.6.0

After running pod install and npx react-native run-ios I get he following error:

The following build commands failed:

CompileC /Users/user/Desktop/App/ios/build/App/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNFirebase.build/Objects-normal/x86_64/RNFirebaseAuth.o /Users/user/Desktop/App/node_modules/react-native-firebase/ios/RNFirebase/auth/RNFirebaseAuth.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by Ehesp** [comment]
That error isn't helpful I'm afraid. Try to clear your Pods/Cache etc and try again, it's a local issue going on here, I think.

**Comment by DanMCX** [comment]
> That error isn't helpful I'm afraid. Try to clear your Pods/Cache etc and try again, it's a local issue going on here, I think.

I've tried but not success.  Any clear instructions  on how to do it?

**Comment by mikehardy** [comment]
npx react-native-clean-project 

answer yes to everything, then reinstall pods and build again

**Comment by DanMCX** [comment]
> npx react-native-clean-project
> 
> answer yes to everything, then reinstall pods and build again

Hi, I just did that 3 times and with the same error. Any more advice? :)

**Comment by mikehardy** [comment]
This demo script will give you a complete, working throw-away project on RN 0.61.5 and RNFBv5 - clone it and run it - https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh - compare the project to find the difference, it's in there somewhere

**Comment by DanMCX** [comment]
> This demo script will give you a complete, working throw-away project on RN 0.61.5 and RNFBv5 - clone it and run it - https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh - compare the project to find the difference, it's in there somewhere

Thank you, indeed. It took me some time to indentify the problem. 

The solution was this line (1184) from RNFirebaseAuth:

`credential = [FIRGoogleAuthProvider credentialWithIDToken:authToken accessToken:authTokenSecret];`
