### ISSUE TITLE
firebase app has not been initialized!

### ISSUE THREAD

**Issue by uendar** [invertase/react-native-firebase#3324]
Hi everyone,

I upgraded the aRN app to 

```
"react": "16.9.0",
"react-native": "0.61.5",

"react-native-firebase": "^5.6.0"
```

and now i get this error with firebase.

![Screenshot_20200319-154643](https://user-images.githubusercontent.com/13899301/77080152-41353280-69f9-11ea-8c4a-cbde5cdeed48.png)

**BUILD.GRADLE**
// Top-level build file where you can add configuration options common to all sub-projects/modules.

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        androidXCore = "1.0.2"
        googlePlayServicesAuthVersion = "15.0.1" // <--- use this version or newer
        firebaseVersion ="17.3.4"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")
        classpath 'com.google.gms:google-services:4.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            url "https://maven.google.com"
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}


subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                defaultConfig {
                    targetSdkVersion 28
                }
            }
        }
    }
}
```

**APP/BUILD.GRADLE**

```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation 'com.google.firebase:firebase-messaging:18.0.0'
    implementation "com.google.android.gms:play-services-base:16.0.1"
    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}


apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

apply plugin: 'com.google.gms.google-services'
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
```

**Comment by Ehesp** [comment]
Have you added the Google services file from the google console?

**Comment by mikehardy** [comment]
disable version check should no longer be used with google services plugin 4.3.3

I see lots of out of date versions like the above, I wouldn't recommend that. For RNFBv5 on RN0.60+ check the results of cloning and running this script to see how things look? https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by uendar** [comment]
@Ehesp  yes i have . It is not issue with notification. It crases the app when i run on debug mode.

**Comment by uendar** [comment]
@MichaelTamm  i removed it. 
Now i get 


`
Could not determine the dependencies of task ':app:preDebugBuild'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[10.2.
  1, 16.0.99]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.onesignal:OneSignal:3.12.7 -> com.google.android.gms:play-services-location@[10.2.1, 16.0.99], b
  ut play-services-location version was 16.0.0.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.onesignal:OneSignal@{strictly 3.12.7}
  -- Project 'app' depends on project 'react' which depends onto com.onesignal:OneSignal@3.12.7
  -- Project 'app' depends onto com.google.android.gms:play-services-location@{strictly 16.0.0}

  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.
`

**Comment by Ehesp** [comment]
You have multiple dependencies with multiple versions of Google Play services (One Signal includes it). On Android, it won't build with multiple versions.

Have a read of this article on how to solve: https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f

**Comment by mikehardy** [comment]
Fascinating! Those tangles are the worst. I had not seen that article, but it mentions react-native-device-info (which I maintain) - it worries me to think someone might force a play services version lower than what I intend. I suppose it's possible, but as play services adds APIs device-info might rely on them (like the Install Referrer API or similar, which we just started using). If you force the versions be very sure you test all functionality in your app to make sure you don't touch some part of it that requires a different dependency version

Otherwise...should work
