### ISSUE TITLE
🔥Functions httpsCallable() throws error with code UNAVAILABLE for network io error on iOS, and INTERNAL on Android

### ISSUE THREAD

**Issue by justinwh** [invertase/react-native-firebase#3326]
## Issue
On iOS devices, if you put your phone into airplane mode and execute a `httpsCallable()` to call a cloud function, the error thrown has code=`UNAVAILABLE`.

On Android devices, if you do the same thing, the error has code=`INTERNAL`.

This reflects the behavior of the underlying Firebase SDKs for each platform.  Network IO errors (which 'airplane mode' triggers) are returned differently.

However, `INTERNAL` is also used to report HTTP 500 response status—meaning your server-side code crashed.  It's important for apps to be able to distinguish between a momentary network IO error and a 500 response.  The native Android Firebase SDK provides the underlying Exception in the error's `cause` property for this purpose.  react-native-firebase has no equivalent mechanism, which makes it impossible to distinguish between these cases on Android.

I propose to make react-native-firebase for Android check the `cause` and return code=`UNAVAILABLE` for network IO errors, to match the iOS behavior.

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 220.16 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.18.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.6 => 0.60.6
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.x.x`
- **`Firebase` module(s) you're using that has the issue:**
  - `Functions`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Thanks for looking into it! That definitely sounds plausible, probably needs another specific catch statement adding.

One of us will get this looked into. Thanks!

**Comment by conrado** [comment]
thanks, this is useful as I spent a couple of hours wondering why things weren't working after adding an if(__DEV__) check on whether to use the development server and wondered what error was really happening since the functions dev server wasn't running.
