### ISSUE TITLE
Update firebase ios sdk to 6.21.0

### ISSUE THREAD

**Issue by dbuarque** [invertase/react-native-firebase#3329]
Current Firebase ios sdk is 6.13.0. Please update the Firebase ios sdk to 6.21.0

**Comment by mikehardy** [comment]
I don't see 6.21.0 in the release notes? https://firebase.google.com/support/release-notes/ios

Regardless, you have control, you may upgrade yourself, here is exactly how to do so: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh#L31

Finally, if you do this and you use in-app-messaging, I believe once you go past 6.16.0 you will need this small patch until the next main release: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh#L146

**Comment by dbuarque** [comment]
Should be available there soon. It's already available on github.

https://github.com/firebase/firebase-ios-sdk/releases/tag/6.21.0
