### ISSUE TITLE
[AdMob] Impression RPM way too low

### ISSUE THREAD

**Issue by pawelsas** [invertase/react-native-firebase#3332]
Hi,

I am using the AdMob module in my bare React Native App on Android and iOS. It's a production app with several thousand users per month. I have used the Expo AdMob plugin before but after some big issues with other Expo modules I replaced every Expo module.

After some weeks of usage I noticed that my AdMob income dropped about 30-40% due to a very low impression RPM. The impression RPM is volatile but it's obvious that it dropped due to the plugin change.

I have made some split tests

- show a mix of personalized and non-personalized ads
- show non-personalized ads only
- show personalized ads only
- show non-personalized ads with custom keywords

but the RPM didn't increase.

Did anyone notice that issue before? Any possible solutions?

Thanks!

**Comment by Ehesp** [comment]
Hey

Not heard this before to be honest. The other possibility (no idea) is that with the other module it was too high, just one to keep in mind.

I'm not too clued up on AdMob, however are there any sort of metrics which point to a particular platform/device etc?

**Comment by pawelsas** [comment]
Unfortunately there are no noticeable metrics.

Actually there are still some people using the old version of my app. This is the report for the last 7 days.
 
<img width="129" alt="comparison" src="https://user-images.githubusercontent.com/15066762/77354848-c6934c80-6d43-11ea-9b47-7e552280ecb3.png">

**Comment by Ehesp** [comment]
I wonder if the Expo module does anything under the hood with the outbound requests? We keep it pretty bare-bones to give users full control. Could be worth digging into the source code.
