### ISSUE TITLE
No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()

### ISSUE THREAD

**Issue by alihassan711** [invertase/react-native-firebase#3333]
It happens when it calls database().ref()
---

![Screenshot_1584898100](https://user-images.githubusercontent.com/5141703/77259385-e1fa4b00-6ca2-11ea-9192-63d7df80cff8.png)

`import React, { Component } from 'react';

import {
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  Image,
  FlatList,
  StatusBar,
  TextInput,
  Alert,
  SafeAreaView,
} from 'react-native';

//import react in our code.
import database, { firebase } from '@react-native-firebase/database';

//import all the components we are going to use.

const options = {
  title: 'Select Image',
  storageOptions: {
    skipBackup: true,
    path: 'images'
  }
};
const ImageRow = ({ image, windowWidth, popImage }) => (
  <View>
    <Image
      source={{ uri: image }}
      style={[styles.img, { width: windowWidth / 2 - 15 }]}
      onError={popImage}
    />
  </View>
);
export default class RegisteredCaseScreen extends Component {
  state = {
    imgSource: '',
    uploading: false,
    progress: 0,
    images: [],
    isAuthenticated: false, 
    isLoading: false, 
    country: '', 
    city: '', 
    cState:'', 
    area:'',
    patientsArr:[],
    height: 0,
    width: 0
  };
  componentDidMount() {
    
  }
  /**
   * Select image method
   */
  pickImage = () => {
    
    const db_ref = database().ref(`/patients`+"/"+this.state.country+"/"+this.state.cState+"/"+this.state.city+"/"+this.state.area);
    db_ref.once('value', function(snap){
      resultSet = [];
      console.log("\n\n\n\n"+`/patients`+"/"+this.state.country+"/"+this.state.cState+"/"+this.state.city+"/"+this.state.area);
      snap.forEach(function(countryObj){
        if(countryObj.val().area==undefined)
        {......... `

**Comment by mikehardy** [comment]
You did not follow the template, it's hard to say why your project isn't working.
As a quick check before trying again with full information, you might try cloning this repo, and running this script: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh - it will generate a complete + functioning throwaway demo and you can try putting your db code in there to see if it works. If it does then the difference will be found by comparing it's output with your project

**Comment by steniobarroso** [comment]
Thank you very much for the quick answer, I created a new example project but it keeps going wrong

**Comment by HadiKhalifeh** [comment]
@steniobarroso u solve it?

**Comment by mikehardy** [comment]
@HadiKhalifeh this has been reported in projects that use firebase SDKs in native code outside react-native-firebase, but in general as I mentioned above - without the information in the issue template, it is all just guesswork.

**Comment by steniobarroso** [comment]
My friend I don't remember very well, but I inserted in the index.js or in the app.js file, some requests from the notifications firebase because I was giving an error. it must be called at the beginning.

**Comment by steniobarroso** [comment]
@HadiKhalifeh What do you want to implement from firebase?

**Comment by steniobarroso** [comment]
@mikehardy There is a firebase bug with phone authentication it does not accept async await the error just works with .them, at least for me it just worked that way

**Comment by mikehardy** [comment]
@steniobarroso if you are aware of a phone auth bug that is bubbling up unexpectedly please do log an issue (or link an existing one here) and we can try to prioritize fixing it!

**Comment by HadiKhalifeh** [comment]
@steniobarroso @react-native-firebase/messaging

**Comment by steniobarroso** [comment]
@HadiKhalifeh This code must be in your initial 

`messaging (). SetBackgroundMessageHandler (async remoteMessage => {

  to try {
    asynchronous function requestUserPermission () {
      const authStatus = await messaging (). requestPermission ();
      const enabled =
        authStatus === AuthorizationStatus.AUTHORIZED || authStatus === AuthorizationStatus.PROVISIONAL;
    
      if (enabled) {
        
      }
    }
  } catch (error) {
    
  }

  
    Notification.configure (). LocalNotification ({
        message: remoteMessage.data.message
    })

  });`

**Comment by HadiKhalifeh** [comment]
`saveFcmToken() { messaging() .hasPermission() .then(enabled => { if (enabled) { messaging() .getToken() .then(fcmtoken => { if (fcmtoken) { console.log(fcmtoken, 'fcmtoken'); UserAPIs.updateUser({ fcmtoken, }); } else { // user doesn't have a device token yet } }); } else { messaging() .requestPermission() .then(() => { messaging() .getToken() .then(fcmtoken => { if (fcmtoken) { UserAPIs.updateUser({ fcmtoken, }); } else { // user doesn't have a device token yet } }); }) .catch(error => { // User has rejected permissions }); } }); }`




`messaging().onMessage(async remoteMessage => {
      console.log(remoteMessage, 'from dady assem');
      window.refreshNotifications ? window.refreshNotifications() : null;
      window.refreshOrderDetails ? window.refreshOrderDetails() : null;
    });
    messaging().onNotificationOpenedApp(remoteMessage => {
      console.log(remoteMessage, 'from dady assem');
      this.createNotificationListeners(remoteMessage);
    });

`

these lines are causing trouble,in old project its working but in my new project no

**Comment by steniobarroso** [comment]
What is your initial file?

**Comment by steniobarroso** [comment]
What worked for me was starting fiirebase in the initial application file.

**Comment by HadiKhalifeh** [comment]
@steniobarroso  what u mean initial file?

**Comment by steniobarroso** [comment]
The first file to be executed. E.g. index.js or App.js

**Comment by HadiKhalifeh** [comment]
@steniobarroso  App.js

**Comment by steniobarroso** [comment]
In App.js or Index.js you must start Firebase with this code for notifications.
Checks that in your project you don't have index.js

``messaging().SetBackgroundMessageHandler (async remoteMessage => {
  to try {
    asynchronous function requestUserPermission () {
      const authStatus = await messaging (). requestPermission ();
      const enabled =
        authStatus === AuthorizationStatus.AUTHORIZED || authStatus === AuthorizationStatus.PROVISIONAL;
      if (enabled) {
        
      }
    }
  } catch (error) {
    
  }
    Notification.configure (). LocalNotification ({
        message: remoteMessage.data.message
    })

  });``
