### ISSUE TITLE
Android Not working - 6.x

### ISSUE THREAD

**Issue by ezos86** [invertase/react-native-firebase#3334]
## Issue

The android build does not work. It seems many people have struggled with this but documentation and everything I read does not lead to a conclusion. And it seems my problem highlights a different line of code.

Describe your issue here
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ecavazos/sites/cl/rn-code/node_modules/@react-native-firebase/app/android/build.gradle' line: 66

* What went wrong:
A problem occurred evaluating project ':@react-native-firebase_app'.
> Could not find method platform() for arguments [com.google.firebase:firebase-bom:24.1.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

Can anyone help with this? Cause all the solutions I have read were for v5.x and did not work.

**Comment by mikehardy** [comment]
Android does work fine, and I think the docs are up to date? This is *exactly* how to do it: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh (read the script, clone the repo and run it - it does a release build test for android and a debug run on the emulator you're running at the time

**Comment by ezos86** [comment]
It was Gradle versions and Java versions being different @mikehardy - I haven't had to change before for other packages, Thanks. 

Maybe someone else needs this too. Check your Gradle and Java versions.
