### ISSUE TITLE
Can expose initializeApp?

### ISSUE THREAD

**Issue by railsjack** [invertase/react-native-firebase#3337]
In my project, I have a need of changing configuration of Firebase on the fly.

For example, I would like to use the method like this.
```
if( environment === 'TESTING'){
  firebase_app.initializeApp("google-services-testing.json");
} else if( environment === 'PRODUCTION') {
  firebase_app.initializeApp("google-services-production.json");
}
```
To this end, I believe that the method `initializeApp()` needs to be exposed.
Is this possible in this project?

Thank you for reading

**Comment by Ehesp** [comment]
https://invertase.io/oss/react-native-firebase/v6/app/reference/module#initializeApp

It's not very well documented, but you can expose a secondary app by initialising it manually.

**Comment by railsjack** [comment]
Anything else for my request?

**Comment by Ehesp** [comment]
Those modules don't support secondary apps sorry, that's a Firebase SDK limitation.

**Comment by railsjack** [comment]
And that's why I want to have an ability to run the method `initializeApp()` from React-Native just in case when the app needs to be initialized with just necessary configuration.
In native (iOS or Android), it was possible initialize the app with the necessary configuration (non-static).
Can you please have a possibility for this?
For example, we can have a solution like this.
firebase.json
```
{
  auto_initialize: true/false
}
```
And then, 
```
firebase.ainitalizeApp(configurationForTesting);
// or
firebase.ainitalizeApp(configurationForProduction);
```

If you can agree but there is no enough time, then I can contribute for this feature.
Can you please solve this problem for me?

Thank you,

**Comment by Ehesp** [comment]
That's not possible with the native SDKs I'm afraid. 

Your best option is to have a script which swaps out the native config files before building.

**Comment by mikehardy** [comment]
For an example you can do a script that moves files as Elliot mentions, or you can also use Xcode targets, and have one plist per target (bound together by the Xcode ability to selectively include different files in different targets). I do that, so I don't have to move files around, I just build a different target (pointing at a different firebase backend app - dev/test/staging/prod) and it works fine.

**Comment by railsjack** [comment]
Thank you all of you for commenting.
To be honest, I was going to put some codes before `[FIRApp configure]` to choose a necessary configuration file. And I believe in that way, I can achieve my goal in iOS, by the way, in Android, I couldn't find anywhere I can put my some codes in.

Ehesp, can you please give any hint?

**Comment by mikehardy** [comment]
@railsjack that seems complicated (adding code == adding bugs, normally) vs using built-in build system features, but I suppose that would work. For Android the standard method is to use gradle product flavors:

```groovy
    flavorDimensions "release_streams"
    productFlavors {
        dev {
            applicationIdSuffix ".dev"
            versionNameSuffix applicationIdSuffix
        }
        qa {
            applicationIdSuffix ".test"
            versionNameSuffix applicationIdSuffix
        }
        staging {
            applicationIdSuffix ".staging"
            versionNameSuffix applicationIdSuffix
        }
        prod {

        }
    }

```

then have directories in your app like:

```
mike@isabela:~/work/Kullki/ksocialscore/packages/public-app (rebranding) % ls -lat android/app/src/dev/
total 20
drwxr-xr-x 3 mike mike 4096 Jan 26 16:16 ./
-rw-r--r-- 1 mike mike  552 Jan 26 16:16 AndroidManifest.xml
-rw-r--r-- 1 mike mike 1348 Jan 26 16:16 google-services.json
drwxr-xr-x 8 mike mike 4096 Nov 18 13:06 ../
drwxr-xr-x 8 mike mike 4096 Nov 18 13:06 res/
mike@isabela:~/work/Kullki/ksocialscore/packages/public-app (rebranding) % ls -lat android/app/src/prod/
total 16
drwxr-xr-x 2 mike mike 4096 Jan 26 16:16 ./
-rw-r--r-- 1 mike mike  378 Jan 26 16:16 AndroidManifest.xml
-rw-r--r-- 1 mike mike 2105 Jan 26 16:16 google-services.json
drwxr-xr-x 8 mike mike 4096 Nov 18 13:06 ../
```

This is a fundamental thing to get right with respect to firebase back-ends and react-native development but it is not easy - my point in saying that is an attempt to motivate reading a few articles on it like

https://medium.com/@andersongusmao/xcode-targets-with-multiples-build-configuration-90a575ddc687

https://www.folio3.com/blog/how-to-manage-multiple-environments-in-a-react-native-app-for-android/

**Comment by railsjack** [comment]
Mike Hardy
I appreciate your kind explanation.
Yes, It's complicated and it's more complicated than you said.
I have a situation to implement things like this.

Scenario
1) Upload & Release the app to AppStore and Google PlayStore
Backend plays with the API version (like as v1.1 - production version)
It recognizes that the backend API is production version, and it will use "google-services.json".

2) Backend updates the API version to 2.0.
The app recognizes that the backend API is newer version.
In this case the app will restart and next time should work with "google-services-testing.json".

To this end, I need the feature like as above.

I am sorry if it was complicated more.

**Comment by railsjack** [comment]
Anyway, since @Ehesp said it is not possible with this "react-native-firebase", I am going to try to find another solution to implement this feature.

**Comment by sergeymorkovkin** [comment]
Is there any progress on this 10 months later? There is no clarity on whether messaging and crashlytics support secondary apps in 2021. A lot of contradicting information.

**Comment by mikehardy** [comment]
This is where any progress would be tracked, what you see is what you get. Do you have any new information @sergeymorkovkin ? Have you looked at the upstream docs for firebase-ios-sdk and firebase-android-sdk to see if messaging or crashlytics support multiple applications? Those docs won't be contradictory, they are upstream and they are authoritative. Please do that and report back then we'll all know

Thanks!

**Comment by sergeymorkovkin** [comment]
@mikehardy My apologies if I appeared to be demanding - I didn't really mean that. Let me check there and I'll get back here.

**Comment by sergeymorkovkin** [comment]
Answered [here](https://stackoverflow.com/questions/62253691/firebasemessaging-getinstancefirebaseapp-for-secondary-app-supposed-to-be-publ).

**Comment by mikehardy** [comment]
Most specifically, from that link (good find!):

> Answer regarding separate projects for FCM and Crashlytics:

>>    Upon discussing with the team, they’ve verified that your use case is not supported by Firebase. You should be using a single Firebase Project/Firebase App for both FCM and Crashlytics. Thanks for understanding.

**Comment by sergeymorkovkin** [comment]
> Hello Sergey,
> 
> I do understand what you’ve been through on implementing that type of use-case with Firebase. However, this is not 
> possible with the native Firebase Crashlytics and Firebase Cloud Messaging SDK. The initialization of the SDK is 
> dependent on the default configuration file associated with a Firebase project application.
> 
> As you’ve used React Native implementations, you could check this type of use-case in the React Native community, but > our channel doesn't have any relation with the React Native framework integrations or improvements. Hope you 
> understand.
> 
> Regards,
> Alvin
