### ISSUE TITLE
While using Anonymous Signin: API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device

### ISSUE THREAD

**Issue by joecaraccio** [invertase/react-native-firebase#334]
Hi Everyone,
Running on Android. Trying to use anonymous auth with this simple code:
```
  firebase.auth().signInAnonymously()
  .then((user) => {
    console.log('Anonymous user successfully logged in', user)
  })
  .catch((err) => {
    console.log('Anonymous user signin error', err);
  });

```
However, when doing that it throws the error:
signin error Error: API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device.

Upon a quick google, it seems that this was an issue with the firebase auth api.. but it looks like as of version 9 they fixed it.. I did enable anonymous auth in the firebase console.. do I also have to regenerate that json file?

**Comment by Ehesp** [comment]
Have you updated all of your apis on the SDK manager from android studio?
Could be an older SDK it's using

**Comment by joecaraccio** [comment]
Yeah.. think everything I am using is the latest

**Comment by Salakar** [comment]
Could you paste us a copy of your grade file so we can see the versions you're running etc? Thanks

**Comment by joecaraccio** [comment]
Sure! Thanks so much by the way...

`def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 25
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.pack"
        minSdkVersion 16
        targetSdkVersion 22
        multiDexEnabled true
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-vector-icons')
    compile project(':react-native-firebase')
    compile project(':react-native-linear-gradient')
    compile project(':lottie-react-native')
    compile project(':react-native-camera')

    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
      // RNFirebase required dependencies
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile "com.google.firebase:firebase-core:11.0.0"

    // If you are receiving Google Play API availability issues, add the following dependency
    compile "com.google.android.gms:play-services-base:11.0.0"

    // RNFirebase optional dependencies
    compile "com.google.firebase:firebase-ads:11.0.0"
    compile "com.google.firebase:firebase-analytics:11.0.0"
    compile "com.google.firebase:firebase-auth:11.0.0"
    compile "com.google.firebase:firebase-config:11.0.0"
    compile "com.google.firebase:firebase-crash:11.0.0"
    compile "com.google.firebase:firebase-database:11.0.0"
    compile "com.google.firebase:firebase-messaging:11.0.0"
    compile "com.google.firebase:firebase-perf:11.0.0"
    compile "com.google.firebase:firebase-storage:11.0.0"

}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
apply plugin: 'com.google.gms.google-services'`

**Comment by chrisbianca** [comment]
@joecaraccio Any luck with this yet?  I'd suggest bumping to 11.0.4 which is the latest version of Firebase and Google Play Services to see if it's a bug in the library - I know 11.0.0 and 11.0.1 did have a few issues.

Alternatively, based on: https://github.com/firebase/quickstart-android/issues/249 it looks to be an issue when Google Play Services aren't correctly installed on the device / emulator being used for testing.

**Comment by chrisbianca** [comment]
I'm going to close this as we've not heard anything for the past week.  Please feel free to re-open if this is still an issue

**Comment by bobmulder** [comment]
Is there any update on this issue? Facing the same...

**Comment by rhroyston** [comment]
You don't do `.then` on the `.signInAnonymously()` method. You watch the `.onAuthStateChanged()` observer.
