### ISSUE TITLE
AppleAuthProvider issue for version 5.2.3

### ISSUE THREAD

**Issue by theromie** [invertase/react-native-firebase#3344]
After installing version 5.2.3 its giving me error

`bundling failed: Error: Unable to resolve module `./providers/AppleAuthProvider` from `node_modules\react-native-firebase\dist\modules\auth\index.js`:`

**Comment by mikehardy** [comment]
AppleAuthProvider was not available in that version. It was implemented for the last v5.5.x release and in v5.6.0 plus v6 current releases.
