### ISSUE TITLE
Background notification not coming in release IOS build

### ISSUE THREAD

**Issue by NiveshShastri** [invertase/react-native-firebase#3346]
I am getting notification callback while the app is in the foreground but not getting notifications on the mobile notification tray when the app is in the background or gets killed in case of IOS but in android, both cases are working fine.

"react": "16.9.0",
"react-native": "0.61.5",
 "@react-native-firebase/app": "^6.3.4",
 "@react-native-firebase/messaging": "^6.3.4",

**Comment by Steffi3rd** [comment]
Hello, can you fill the template issue please? 
Because we don't know the context about your case, which version of Firebase, of RN and put some snippet code.  👍

**Comment by NiveshShastri** [comment]
@Steffi3rd  I have updated my question please check

**Comment by Ehesp** [comment]
Could you give `6.4.0-rc2` a try please? For reference, here are the changes: https://github.com/invertase/react-native-firebase/pull/3339

**Comment by NiveshShastri** [comment]
@Ehesp currently I am going to release the build by tomorrow so I cant try or use any other library for this time, please understand thank you.

**Comment by Ehesp** [comment]
Ok no problem. Going to close this one then as it's covered in that PR. Thanks

**Comment by NiveshShastri** [comment]
@Ehesp  I tried the `6.4.0-rc2` but the notification still not coming on the Background

**Comment by Ehesp** [comment]
Need some more information to help. Release builds need everything setting up, please see https://rnfb-docs.netlify.com/messaging/usage/ios-setup

**Comment by NiveshShastri** [comment]
@Ehesp I have done all the steps already and double-checked, setting are fine.
But with the version `6.4.0-rc2`, I am getting all the notification in debug build that is not coming on the `6.3.4`.

**Comment by NiveshShastri** [comment]
@Ehesp my issue has been resolved.

**Comment by fareedagha** [comment]
@NiveshShastri how to resloved the issue? im also facing the same issue
