### ISSUE TITLE
IOS not notification when background and app close

### ISSUE THREAD

**Issue by thanhtuyenpkk** [invertase/react-native-firebase#3348]
My project work well in android but. can't show notification on ios when hidden app or close app
I seach my problem but can't resolve it. 
My APP.JS

> componentWillUnmount() {
>         this.notificationListener();
>         this.notificationOpenedListener();
>     }
> 
>     async componentDidMount() {
>         this.checkPermission();
>         this.createNotificationListeners();
>     }
> 
>     //1
>     async checkPermission() {
>         const enabled = await firebase.messaging().hasPermission();
>         if (enabled) {
>             this.getToken();
>         } else {
>             this.requestPermission();
>         }
>     }
> 
>     //3
>     async getToken() {
>         let fcmToken = await AsyncStorage.getItem('fcmToken');
>         console.log('fcmToken', fcmToken);
>         if (!fcmToken) {
>             fcmToken = await firebase.messaging().getToken();
>             if (fcmToken) {
>                 // user has a device token
>                 await AsyncStorage.setItem('fcmToken', fcmToken);
>             }
>         }
>     }
> 
>     //2
>     async requestPermission() {
>         try {
>             console.log('requestPermission');
>             await firebase.messaging().requestPermission();
>             // User has authorised
>             this.getToken();
>         } catch (error) {
>             // User has rejected permissions
>             console.log('permission rejected');
>         }
>     }
> 
>     async createNotificationListeners() {
>         //Triggered when a particular notification has been received in foreground
>         this.notificationListener = firebase.notifications().onNotification((notification) => {
>             console.log('notificationListener', notification);
>             const { title, body } = notification.data;
>             this.showAlert(title, body);
>         });
> 
>         /*
>          If your app is in background, you can listen for when a notification is clicked / tapped / opened as follows:
>         */
>         this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
> 
>             console.log('lang notificationOpenedListener', notificationOpen);
>             const { title, body } = notificationOpen.notification.data;
>             this.showAlert(title, body);
>         });
> 
>         /*
>          If your app is closed, you can check if it was opened by a notification being clicked / tapped / opened as follows:
>         */
>         const notificationOpen = await firebase.notifications().getInitialNotification();
>         if (notificationOpen) {
>             console.log('getInitialNotification', notificationOpen)
>             const { title, body } = notificationOpen.notification.data;
>             this.showAlert(title, body);
>         }
>         /*
>          Triggered for data only payload in foreground
>         */
>         this.messageListener = await firebase.messaging().onMessage((message) => {
>             //process data message
>             console.log('messageListener', JSON.stringify(message));
>             const { title, body } = message.data;
>             this.showAlert(title, body);
>         });
>     }
> 
>     showAlert(title, body) {
>         Alert.alert(
>             title, body,
>             [
>                 { text: 'OK', onPress: () => console.log('OK Pressed') },
>             ],
>             { cancelable: false },
>         );
>     }
> 
>     render() {
>         return (
>             <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
>                 <Text> Hello FireBase</Text>
>             </View>
>         );
>     }

In adroid when app open will go to onNotification, app hidden ( background ) go to onNotificationOpened, app close go to getInitialNotification.
In IOS not go to that function, it only go to onMessage when app open. 
APP close and hidden notification not work.
how to fix it.
Thanks you

**Comment by Ehesp** [comment]
Please use `6.4.0-rc2`. See this PR for more details: https://github.com/invertase/react-native-firebase/pull/3339

**Comment by thanhtuyenpkk** [comment]
Thanks you. I'm will try it. is that vesion 6.4.0-rc2.
