### ISSUE TITLE
dynamicLinks().onLink() not getting called when app is freshly launched from link

### ISSUE THREAD

**Issue by HannanShaikYara** [invertase/react-native-firebase#3350]
Hello Guys,

I have integrated Firebase dynamic links with `@react-native-firebase/dynamic-links` version `6.3.4`

```
const handleDynamicLink = async link => {
    console.log('***', link)
}

  useEffect(() => {
    const unsubscribe = dynamicLinks().onLink(handleDynamicLink)
    // When the is component unmounted, remove the listener
    return () => unsubscribe()
  })

```

The `handleDynamicLink` is called when the app is already in background. 

However if the app is closed and freshly launched by tapping on the link it does not get called. 

Please help.

#### `package.json`:

```json
"@react-native-firebase/app": "^6.3.4",
"@react-native-firebase/dynamic-links": "^6.3.4",
```

**Comment by ahanusek** [comment]
I have the same issue on Android (RNF 6.3.4). iOS not tested yet.

**Comment by Ehesp** [comment]
Have you tried usage with getInitialLink? The onLink handler will only be called when the app is in the foreground.

**Comment by ahanusek** [comment]
> Have you tried usage with getInitialLink? The onLink handler will only be called when the app is in the foreground.

Oh my fault, getInitialLink works and returning a link. Sorry, I miss understood the documentation about this method.

**Comment by ahanusek** [comment]
@Ehesp 

Probably I found another issue connected with this feature. I have below flow in my app:

1. The user gets an invitation with a dynamic link to the chat room on email
2. Open the link and goes to the app, then App read the token from a link and processing registration to the chat room.

So when I'm testing this on Android (debug mode) the dynamic link from the first invitation works well, but when you open another invitation, getInitialLink method still returns link with the token from the first link. onLink method doesn't work too because every time I'm clicking on the link the app starts from scratch. 

I'm missing something or should I generate not only a new token but the whole link should be different? Or maybe there is the way to clear the initial link?

**Comment by Ehesp** [comment]
That seems like a bug with the initial link not getting removed once it's been consumed. Let me take a look, however it's probably worth creating a separate issue so we can track it.

**Comment by ahanusek** [comment]
@Ehesp 
I found an old bug with a possible solution. I will check that and will return with feedback.

https://github.com/invertase/react-native-firebase/issues/2631

**Comment by ahanusek** [comment]
Nope, I've added:

`android:launchMode="singleTask"` 

to AndroidManifest but still getInitialLink returns link from the first invitation.

**Comment by Ehesp** [comment]
Yeah I don't think that would sort it, that's just how Android handles the activity when launching an intent. 

Does it work on iOS?

**Comment by ahanusek** [comment]
Can I test this feature without the deployed app to the App Store? I have the app only in TestFlight now.

**Comment by Ehesp** [comment]
Yeah you can, we test on real devices with it just being installed from XCode.

**Comment by ahanusek** [comment]
But when I'm trying open link on ma device (iPhone XS) iOS redirect me to the fallback page (website).
I've added App Store ID, Bundle ID, and Team ID in the firebase console few days ago.

**Comment by ahanusek** [comment]
Ok, I got it, the app is opening after clicking on the link but it is even worse than on Android. getInitiaLink returns always null and onLink doesn't work too. 😢

**Comment by thilinawarnakula** [comment]
@ahanusek did you found any solution ?

**Comment by ahanusek** [comment]
@thilinawarnakula Yes, I will try to share my solution later (today or tomorrow).

**Comment by markuscosinus** [comment]
@ahanusek Could you share your solution for iOS? I am having the same issue.

**Comment by thilinawarnakula** [comment]
@markuscosinus  there are two separate methods to handle this.
1.App in Foreground events
2.App in Background/Quit events

**Comment by adarshponaka** [comment]
same issue happens for me. Backround/quit method works. Foregound method doesnt

**Comment by jyotishman** [comment]
Can someone help on this? dynamicLinks()
      .getInitialLink() is working properly. but dynamicLinks()
      .onLink is not getting called when app is in foreground state. someone?

**Comment by RishavKumar-3796** [comment]
+1..

Facing the same issues

**Comment by mikehardy** [comment]
@RishavKumar-3796 This is a closed issue. Please open a new issue following the issue template. Please make sure you are using up to date versions and still reproducing the problem

**Comment by GhayoorUlHaq** [comment]
> Can someone help on this? dynamicLinks()
> .getInitialLink() is working properly. but dynamicLinks()
> .onLink is not getting called when app is in foreground state. someone?

facing same issue

**Comment by mikehardy** [comment]
@GhayoorUlHaq 

> This is a closed issue. Please open a new issue following the issue template. Please make sure you are using up to date versions and still reproducing the problem

**Comment by anandchakru** [comment]
agh,. I had the wrong domain on host


        <intent-filter android:label="Rathnas Invite">
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          
          <data android:scheme="https"
            android:pathPrefix="/v"
            android:host="EnsureThisIs.Correct.com" />
        </intent-filter>

**Comment by anandchakru** [comment]
agh,. I had the wrong domain on host 😢 


        <intent-filter android:label="Rathnas">
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data android:scheme="https"
            android:pathPrefix="/v"
            android:host="EnsureThisIs.Correct.com" />
        </intent-filter>

**Comment by lochan1shubham** [comment]
I am using RnFirebase in react native app dynamic link created successfully , firebase notification token generate successfully but no any listener working in any case forground/Background .
**onMessage** not trigger for notification and **onLink** not trigger for dynamic link

**Comment by lochan1shubham** [comment]
> @RishavKumar-3796 This is a closed issue. Please open a new issue following the issue template. Please make sure you are using up to date versions and still reproducing the problem

@mikehardy  i am using all thing updated version but still getting issue

**Comment by lochan1shubham** [comment]
> > Can someone help on this? dynamicLinks()
> > .getInitialLink() is working properly. but dynamicLinks()
> > .onLink is not getting called when app is in foreground state. someone?
> 
> facing same issue

getInitialLink getting null URL

**Comment by mikehardy** [comment]
@lochan1shubham 
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example
Produce an index.js/App.js that drops into a clean + minimal reproduction app (like from https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh)
Make sure you add your listeners out side of react-native life cycle, that is, in index.js before you register the app via AppRegistry. Make sure the listeners are async following the examples in the documentation
