### ISSUE TITLE
DEVELOPMENT_MODE_MISMATCH:Non-development mode Verification Proof given in development mode request

### ISSUE THREAD

**Issue by LyhengTep** [invertase/react-native-firebase#3353]
Hello, I have a problem when calling method `auth().signInWithPhoneNumber()` with whitelist number that I have added to the firebase console. but everything seems okay when the number is not in the whitelist.

The error message:
NativeFirebaseError: [auth/development-mode] An internal error has occurred. [ DEVELOPMENT_MODE_MISMATCH:Non-development mode Verification Proof given in development mode request. ]

Environments:
"react-native": "^0.60.4"
"@react-native-firebase/app": "^6.3.4",
"@react-native-firebase/auth": "^6.3.4",

**Comment by russellwheatley** [comment]
Could you please follow the issue template otherwise we cannot reproduce. From that error alone it looks like the app is launched in production whilst you're making a request specifically for a development environment.
