### ISSUE TITLE
IOS - Explicitly Request Authorization , notification alert not comming!

### ISSUE THREAD

**Issue by chamilacnb** [invertase/react-native-firebase#3354]
I have implemented ,
@react-native-firebase/messaging": "^6.3.4"
@react-native-firebase/app": "^6.3.4"

it does not show ,
![image](https://user-images.githubusercontent.com/60600065/77750882-9cdf6b80-704a-11ea-95be-7fd5553971c1.png)

but get the, following alert for the first notification, how to get the above permission request alert when the app starts.
![image](https://user-images.githubusercontent.com/60600065/77751005-e5972480-704a-11ea-9e08-1b03bbec4866.png)

**Comment by Ehesp** [comment]
Fixed in `6.4.0` which is currently under RC as `6.4.0-rc4`. See https://github.com/invertase/react-native-firebase/pull/3339

**Comment by kasunascentic** [comment]
I have tried `6.4.0-rc4`. it works. But there is an another problem. push notification doesn't show when app is background or close. But `messaging().onMessage` fires when app open.

**Comment by Ehesp** [comment]
Could be a few things. That payload looks incorrect with duplicate fields etc, and also you may need to setup apns correctly

https://rnfb-docs.netlify.com/messaging/usage/ios-setup

These are the work in progress docs, take a look

**Comment by JeffGuKang** [comment]
@kasunascentic Did you check the `getAPNSToken`? It should gives not null.

**Comment by kasunascentic** [comment]
@Ehesp @JeffGuKang  Yeah I managed it to work. Removed

`<key>FirebaseAppDelegateProxyEnabled</key>
<string>NO</string>` from plist.

First time I got foreground push notification  in `messaging().onMessage` . After I close the app and open app again.Then I sent a push notification.In this time  `messaging().onMessage` is not fired.

using debug version on phone. Not release version
