### ISSUE TITLE
onMessage triggers two times when tap notification

### ISSUE THREAD

**Issue by chamilacnb** [invertase/react-native-firebase#3355]
Implemented  following versions,

 "@react-native-firebase/app": "^6.3.4"
 "@react-native-firebase/messaging": "^6.3.4"

    this.unsubscribeOnMessageListner = messaging().onMessage(async remoteMessage => {
      console.log('FCM Message Data:', remoteMessage.data);
      Alert.alert(
        remoteMessage.data.body ? remoteMessage.data.body : '',
        remoteMessage.data.title ? remoteMessage.data.title : ''
      )
    });

onMessage **triggers two times** when you tap on a notification when app is on background or app is killed.

**Comment by Ehesp** [comment]
Can you please try `6.4.0-rc4`?

**Comment by chamilacnb** [comment]
ahh.. haa, the fix, will this work for ios?

**Comment by rananajam1** [comment]
How did you resolve this?
