### ISSUE TITLE
Unable to resolve module 'ReactNativeART' from ...

### ISSUE THREAD

**Issue by MelodiiLy** [invertase/react-native-firebase#336]
Unable to resolve module 'ReactNativeART' from .../node_modules/react-native/Libraries/react-native/react-native-implementation.js'.

I tried all the way that I can do, but still can't solve this issue. I found this issue happens after I installed 'pod 'RNFirebase', :path => '../node_modules/react-native-firebase'' in Podfile.

Anyone has solution or similar issue?

### Environment

1. Target Platform (iOS):
2. Development Operating System (macOS):
3. React Native version (0.47.1):
4. RNFirebase Version (2.0.2):

**Comment by saxahan** [comment]
Same as here

**Comment by Ehesp** [comment]
Duplicate https://github.com/invertase/react-native-firebase/issues/278
