### ISSUE TITLE
Ensure you have imported 'io.invertase.firebase.auth.ReactNativeFirebaseAuthPackage' module in your 'MainApplication.java' file

### ISSUE THREAD

**Issue by astroana** [invertase/react-native-firebase#3361]
## Issue

I need some help finding a fix for this errors. I have just created a new project using the template:

$ npx @react-native-community/cli init --template=@react-native-firebase/template myproject

I Initialized firebase and tested with react-native run-android and it is working fine without any installed packages yet. 

Then I installed @react-native-firebase/auth and there the problem begins and I don't know how to fix this.

error message that appear when I try to sign up:
-----------------------------------------------------------------------------------------------------
Error: You attempted to use a firebase module that's not installed on your Android project by calling firebase.auth().

Ensure you have:

1) imported the 'io.invertase.firebase.auth.ReactNativeFirebaseAuthPackage' module in your 'MainApplication.java' file.

2) Added the 'new ReactNativeFirebaseAuthPackage()' line inside of the RN 'getPackages()' method list.
----------------------------------------------------------------------------------------------------

The version I have was "@react-native-firebase/app": "6.3.4", "@react-native-firebase/auth": "^6.3.4".
Which says in the documentation that ver 6 will be automatically linked wit RN 0.60 above.

But I still did try to include it in my MainApplication.java but then when I run react-native run-android it gives me another error conflict with gradle in the terminal. I did try ver 5.5 5.6.4 and 6.3 of gradle but no luck. Metro bundler wont start.

-------------------------------------------------------------------------------------------------
> Task :app:mergeDexDebug FAILED
.
.
* What went wrong:
Execution failed for task ':app:mergeDexDebug'.
.
.
BUILD FAILED in 9s
error Failed to install the app. Make sure you have the Android development environment set up
---------------------------------------------------------------------------------------------------

But when removed the packages "@react-native-firebase/app": "6.3.4", "@react-native-firebase/auth": "^6.3.4"

Without them everything works fine. But I wont be able to create a project without this packages. Other package are working fine. The firebase packages are the only one having conflict in react-native-firebase/template which is weird. I new to react native and I am still trying to learn litle by litle.
Thank you in advance for any help.

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```
</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
It should have auto-linked yeah. However that error looks like multi-dexing issues.. see https://invertase.io/oss/react-native-firebase/v6/firestore/android#enable-multidex

**Comment by astroana** [comment]
I just tried the manual multi-dexing the error warning is still there

Error: You attempted to use a firebase module that's not installed on your Android project by calling firebase.auth().

and another error in the terminal appears

> Task :app:compileDebugJavaWithJavac FAILED
error: package android.support.multidex does not exist
import android.support.multidex.MultiDexApplication;

>error: cannot find symbol
public class MainApplication extends MultiDexApplication implements ReactApplication

>symbol: class MultiDexApplication
error: incompatible types: MainApplication cannot be converted to Application
      new ReactNativeHost(this)

>error Failed to install the app. Make sure you have the Android development environment set up

**Comment by astroana** [comment]
I have given up...I am just going to use firebase directly without react-native-firebase

**Comment by Ehesp** [comment]
It's a local issue with your setup. Make sure all the SDKs are updated locally.

**Comment by mikehardy** [comment]
@astroana you should try creating a fully-integrated throwaway app to see how it all works. All you have to do is clone this repo and run this: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

You'll notice the comments spell out how and why everything is done, here is multidexing: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh#L124

**Comment by astroana** [comment]
the error only appears if I installed @react-native-firebase/auth and other firebase packages if I removed them the error disappear. I cant continue with anything because those are the packages that I need to create my app

**Comment by mikehardy** [comment]
Understood. How'd it go with trying the example (which demonstrate auth, as well as nearly every other firebase example)?

**Comment by astroana** [comment]
I will try the demo. thanks

**Comment by MPuzio15** [comment]
> It should have auto-linked yeah. However that error looks like multi-dexing issues.. see https://invertase.io/oss/react-native-firebase/v6/firestore/android#enable-multidex

thank you, that helped :)
