### ISSUE TITLE
Query doesn't work correctly with persistence=true

### ISSUE THREAD

**Issue by markhalonen** [invertase/react-native-firebase#337]
### Environment

1. Target Platform: iOS and Android
2. Development Operating System: macOS
3. React Native version: 0.43.3
4. RNFirebase Version: 2.0.4

I'm running this query: 

`firebaseApp.database().ref("<Path>").orderByKey().limitToLast(20).once('value')`

The only time it makes the query correctly (to the Firebase server) is when the app launches for the first time. 
 
When `persistence = true`, it does not get the updated data. Without the `persistence` parameter, it works. I push to this path from a Firebase Function, so that's why I think the `persistence` isn't working locally. Shouldn't persistence use the network when possible or am I missing something??

The only way I've found to force it to make the correct query is to _reinstall the app_ — closing the app, including in the background, does not work. It doesn't sync for hours or even days.

For now I am forced to remove the `persistence` feature, which I wish I could have so my app continues to work offline.

**Comment by wwwillchen** [comment]
Take a look at http://invertase.io/react-native-firebase/#/modules/database?id=differences-between-on-amp-once

**Comment by markhalonen** [comment]
Thanks @wwwillchen. So I will basically try to use `on` as a `once`. I don't want to keep the listener active, so I'll just turn it off immediately.

**Comment by Salakar** [comment]
@markhalonen The behaviour @wwwillchen linked to is correct this behaviour comes directly from the firebase android and ios sdk's. 

Try `ref.keepSynced(true);` - which should keep it up to date at all times in the local disk cache. Otherwise use `.on` - wait for the 2nd event - then call `.off` to remove the subscription.

**Comment by markhalonen** [comment]
@Salakar Ok, thanks. You guys are awesome!

**Comment by dannycochran** [comment]
@wwwillchen @Salakar I'm having the same issue but the link above is no longer working. Is there updated documentation around best practices for using setPersistence?

Also +1 to @markhalonen comment, this is a great library, thank you for all your hard work!
