### ISSUE TITLE
firestore error while fetching document

### ISSUE THREAD

**Issue by sgawade13** [invertase/react-native-firebase#3370]
## Issue

I am trying to fetch a particular document using document id but getting error "Error: firestore.Blob.fromBase64String expects a string of at least 1 character in length". For some document id's I am getting data but for some document id's I am facing the same issue. Other queries are working fine. Please help me to solve the error.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```
</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by sgawade13** [comment]
Hello Team,
Please help me to solve this issue as early as possible. Our react-native app is crashing because of this error.

Thanks in advance

**Comment by russellwheatley** [comment]
Please follow the issue template so we can help you. From that error I can tell you that whatever you're doing, you're not passing a string or you're passing an empty string to this function call `FirestoreBlob.fromBase64String()`

**Comment by sgawade13** [comment]
Hello Team,
Thanks for your reply.
My query is firestore().collection('Root').doc('Live').collection('Users_Consumers').doc(consumerId).get() where consumerId is a variable. If I try to console.log(consumerId), it is not a blank string. This error occurs only for some consumerId's, for other the same query works fine.
Thanks in advance

**Comment by Salakar** [comment]
@sgawade13 would need to see your **full** code of your query to help

**Comment by sgawade13** [comment]
Hello Team,
**Here is complete code for the query function**
import firestore from '@react-native-firebase/firestore';
function getConsumer(consumerId) {
    return firestore().collection('Root').doc('Live')
        .collection('Users_Consumers')
        .doc(consumerId)
} 

**below code is for calling query function:**
getConsumer(consumerId).onSnapshot({
                error: e => {
                    this.setState({ loader: false });
                    console.error(e);
                },
                next: snapShotData => {
                    console.log(" in consumer detail>>>>>>>>>>>>>>>>>>", snapShotData.data())
                     }
 });

Thanks in advance.

**Comment by russellwheatley** [comment]
@sgawade13 do you have a `Blob` data type in your firebase collection?

**Comment by sgawade13** [comment]
Hey @russellwheatley 
Thanks for your reply. 
We have not used the blob data type in our firestore collection. I Have attached a screenshot of the collection and JSON of the consumer data for your reference.
`{
  "Location": {
    "addressFull": "building b, 6, Popular Nagar, Giridhar Nagar,  India",
    "city": "Pune",
    "country": "India",
    "lat": 18.484316090545834,
    "long": 73.79656754892709,
    "place": "building b, 6, Popular Nagar, Giridhar Nagar, Warje, Pune, Maharashtra 411058, India",
    "postalCode": "411058",
    "state": "Maharashtra",
    "timezone": {
      "dstOffset": 0,
      "rawOffset": 19800,
      "status": "OK",
      "timeZoneId": "Asia/Calcutta",
      "timeZoneName": "India Standard Time"
    },
    "updatedAt": 1584426480786,
    "zip": "411058"
  },
  "SelectedOrderType": "Takeout",
  "city": "Pune",
  "consumerLocation": {
    "addressFull": "building b, 6, Popular Nagar, Giridhar Nagar, Warje, Pune, Maharashtra 411058, India",
    "city": "Pune",
    "country": "India",
    "lat": 18.484316090925834,
    "long": 73.79657104892709,
    "place": "building b, 6, Popular Nagar, Giridhar Nagar, Warje, Pune, Maharashtra 411058, India",
    "postalCode": "411058",
    "state": "Maharashtra",
    "updatedAt": 0,
    "zip": "411058"
  },
  "country": "India",
  "created_at": 1584362191216,
  "emailID": "c7gx5q@spamox.me",
  "isMobileNumberVerified": false,
  "key": "",
  "loginType": "Email ID",
  "mobileNumber": "2314567895",
  "name": "John",
  "nearest_restaurant_id": "",
  "platform": "iOS",
  "profileImageURL": "",
 "res_Id": "dHgHbEpQLSNWBFeEiOPWPKasmgi1",
  "state": "Maharashtra",
  "validData": true,
  "zip": "411058"
}`
Thanks in advance
![consumerDataSnap](https://user-images.githubusercontent.com/61136211/78120730-12bb4c80-7428-11ea-9fb0-0eebb78c3579.png)

**Comment by russellwheatley** [comment]
The only thing I can suggest is to add this code snippet:
```
if (type === 'blob') {
    console.log('blob', value);
  }
```
at this [point](https://github.com/invertase/react-native-firebase/blob/master/packages/firestore/lib/utils/serialize.js#L225) in your firestore package in `node_modules/` directory and debug what property is being evaluated as a `blob`. The error occurs because the value is either an empty string or it isn't a string.

**Comment by sgawade13** [comment]
Hey @russellwheatley 
Thanks for your reply
I tried adding the above code in the npm package. Yes, I am getting a blank string in blob. Please help me to handle this condition in my code because when I console.log(consumerId) before query then that value is not blank. Even I tried to handle this if(condition) but I am getting the same error.
Thanks in advance


function getConsumer(consumerId) {
    if (consumerId) {
        console.log("in if", typeof (consumerId))

        return firestore().collection('Root').doc('Live')
            .collection('Users_Consumers')
            .doc(consumerId)
    } 

}

**Comment by sgawade13** [comment]
Hello Team,
Thank you for your support. I got the solution by debugging the npm package.

**Comment by Salakar** [comment]
@sgawade13 what was the solution?

**Comment by sgawade13** [comment]
Hello @Salakar 
Actually, in some of the consumer data, there was one variable with blank value that was of blob datatype in firestore. I was unaware of that variable in the database and I got to know this when I debug using npm package. Now I assigned value to that variable and I am able to get data.
Thank you for your support.
