### ISSUE TITLE
Push notification is not stable on iOS

### ISSUE THREAD

**Issue by LuongTruong** [invertase/react-native-firebase#3373]
## Issue

I am working on Push Notification. There is one thing that is really bothering me. The push notification sometimes works, sometimes doesn't.

For example:
- I am able to make the push notification today
- The next day, I change the UI components like: adding more color, adding border radius,... but absolutely nothing change related to the push notification.

When I run the app, The push notification doesn't work anymore. My app is able to receive push, but everything go directly to the function `firebase.messaging().onMessage()` instead of `firebase.notifications().onNotification()` as it is used to be

---

## Project Files

My Podfile:

    # Pods for Project
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'

My AppDelegate.h

    #import <React/RCTBridgeDelegate.h>
    #import <UIKit/UIKit.h>

    @interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate>

    @property (nonatomic, strong) UIWindow *window;

    @end

My AppDelegate.m

    // Firebase
    #import <Firebase.h>
    #import "RNFirebaseNotifications.h"
    #import "RNFirebaseMessaging.h"

    @implementation AppDelegate

    - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
    {
        // Firebase
        [FIRApp configure];
        [RNFirebaseNotifications configure];
        // ========

        ...
    }

    // Push Notification
    - (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
        [[RNFirebaseNotifications instance] didReceiveLocalNotification:notification];
    }

    - (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
                                                       fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
        [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
    }

    - (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
        [[RNFirebaseMessaging instance] didRegisterUserNotificationSettings:notificationSettings];
    }

### Javascript

My Firebase Wrapper - PushController.tsx:

    import firebase from 'react-native-firebase';
    import {Platform} from 'react-native';
    
    import * as ColorConfig from "../../configs/ColorConfig";
    
    import * as LocalStorage from "../../store-local/async-storage/LocalStorage";
    import * as LocalStorageKey from "../../store-local/async-storage/Key";
    
    const CHANNEL_ID = "Chanel ID for Android Notification";
    
    interface IPushControllerType {
    
        _isNotificationReceived: boolean,
    
        checkPermission(): Promise<void>,
    
        getToken(): Promise<void>,
    
        requestPermission(): Promise<void>,
    
        createAppForegroundNotificationListeners(): void,
    
        createAppBackgroundNotificationListeners(): void,
    
        createPayloadOnlyNotificationListeners(): void,
    
        createAppClosedNotificationListeners(): Promise<void>,
    }
    
    const PushController: IPushControllerType = {
    
        /*
         * In iOS, the if the app receives notification when it is closed
         *
         * There are 2 notification listeners executed: onNotificationOpened and getInitialNotification
         *
         * Solution: having a variable to block duplication
         */
        _isNotificationReceived: false,
    
        async checkPermission(): Promise<void> {
    
            const enabled = await firebase.messaging().hasPermission();
    
            if (enabled) {
    
                await this.getToken();
    
            } else {
    
                await this.requestPermission();
            }
        },
    
        async getToken(): Promise<void> {
    
            let fcmToken = await LocalStorage.load(LocalStorageKey.FCM_TOKEN);
    
            if (!fcmToken) {
    
                fcmToken = await firebase.messaging().getToken();
    
                if (fcmToken) {
    
                    // user has a device token
                    await LocalStorage.save(LocalStorageKey.FCM_TOKEN, fcmToken);
                }
            }
    
            console.log("fcmToken", fcmToken);
        },
    
        async requestPermission(): Promise<void> {
    
            try {
                await firebase.messaging().requestPermission();
    
                // User has authorised
                await this.getToken();
    
            } catch (error) {
    
                // User has rejected permissions
                console.log('permission rejected');
            }
        },
    
        createAppForegroundNotificationListeners(): void {
    
            /*
             * Triggered when a particular notification has been received in foreground
             */
            firebase.notifications().onNotification((notification) => {
    
                if (!this._isNotificationReceived) {
    
                    this._isNotificationReceived = true;
    
                    const {title, body} = notification;
    
                    console.log("_notificationListener", notification);
    
                    console.log("title", title);
                    console.log("body", body);
    
                    if (Platform.OS === "ios") {
    
                        const notificationView = new firebase.notifications.Notification()
                            .setNotificationId('notificationId')
                            .setTitle(title)
                            .setBody(body)
                            .setSound("default");
                        firebase.notifications().displayNotification(notificationView).then();
    
                    } else {
    
                        const notificationView = new firebase.notifications.Notification()
                            .setNotificationId('notificationId')
                            .setTitle(title || "Project name")
                            .setBody(body || "You got some news")
                            .setSound("default")
                            .android.setChannelId(CHANNEL_ID)
                            .android.setSmallIcon('ic_notification')
                            .android.setColor(ColorConfig.PRIMARY);
                        firebase.notifications().displayNotification(notificationView).then();
                    }
    
                    // TODO This function will be remove by more reasonable function
                    setTimeout(() => {
                        this._isNotificationReceived = false;
                    }, 1000);
                }
            });
        },
    
        createAppBackgroundNotificationListeners(): void {
    
            /*
             * If your app is in background, you can listen for when a notification is clicked / tapped / opened as follows:
             */
            firebase.notifications().onNotificationOpened((notificationOpen) => {
    
                if (!this._isNotificationReceived) {
    
                    this._isNotificationReceived = true;
    
                    const {title, body} = notificationOpen.notification;
    
                    console.log("_notificationOpenedListener", notificationOpen);
    
                    console.log("title", title);
                    console.log("body", body);
    
                    // TODO This function will be remove by more reasonable function
                    setTimeout(() => {
                        this._isNotificationReceived = false;
                    }, 1000);
                }
            });
        },
    
        createPayloadOnlyNotificationListeners(): void {
    
            /*
             * Triggered for data only payload in foreground
             */
            firebase.messaging().onMessage((message) => {
    
                if (!this._isNotificationReceived) {
    
                    this._isNotificationReceived = true;
    
                    console.log("_messageListener");
    
                    //process data message
                    console.log(JSON.stringify(message));
    
                    // TODO This function will be remove by more reasonable function
                    setTimeout(() => {
                        this._isNotificationReceived = false;
                    }, 1000);
                }
            });
        },
    
        async createAppClosedNotificationListeners(): Promise<void> {
    
            /*
             * If your app is closed, you can check if it was opened by a notification being clicked / tapped / opened as follows:
             */
            const notificationOpen = await firebase.notifications().getInitialNotification();
    
            if (notificationOpen) {
    
                if (!this._isNotificationReceived) {
    
                    this._isNotificationReceived = true;
    
                    const {title, body} = notificationOpen.notification;
    
                    console.log("_notificationOpenedListener closed", notificationOpen);
    
                    console.log("title", title);
                    console.log("body", body);
    
                    // TODO This function will be remove by more reasonable function
                    setTimeout(() => {
                        this._isNotificationReceived = false;
                    }, 1000);
                }
            }
        },
    };
    
    export default PushController;

My PushNotificationComponent

    import PushController from "../controller/push-notification/PushController";

    // These lines of code is written in ComponentDidMount
    PushController.checkPermission().then(() => {
    PushController.createAppForegroundNotificationListeners();
    PushController.createAppBackgroundNotificationListeners();
    PushController.createAppClosedNotificationListeners().then();
    PushController.createPayloadOnlyNotificationListeners();
    });

#### `package.json`:

    "@react-native-community/async-storage": "1.7.1",
    "@react-native-community/cameraroll": "1.3.0",
    "@react-native-community/masked-view": "0.1.5",
    "@react-native-community/netinfo": "5.3.1",
    "axios": "0.19.0",
    "moment": "2.24.0",
    "prop-types": "15.7.2",
    "ramda": "0.26.1",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-background-timer": "2.1.1",
    "react-native-camera": "3.15.1",
    "react-native-device-info": "5.4.0",
    "react-native-firebase": "5.6.0",
    "react-native-fs": "2.16.2",
    "react-native-gesture-handler": "1.5.3",
    "react-native-image-resizer": "1.1.0",
    "react-native-image-zoom-viewer": "2.2.27",
    "react-native-keep-awake": "4.0.0",
    "react-native-orientation-locker": "1.1.8",
    "react-native-pdf": "6.0.1",
    "react-native-reanimated": "1.4.0",
    "react-native-safe-area-context": "0.6.2",
    "react-native-screens": "2.0.0-alpha.22",
    "react-native-signature-capture": "0.4.10",
    "react-native-sound": "0.11.0",
    "react-native-splash-screen": "3.2.0",
    "react-native-vector-icons": "6.6.0",
    "react-navigation": "4.0.10",
    "react-navigation-stack": "2.0.8",
    "react-redux": "7.1.3",
    "redux": "4.0.5",
    "redux-promise": "0.6.0",
    "redux-thunk": "2.3.0",
    "rn-fetch-blob": "0.12.0",
    "uuid": "3.3.3"

## Environment

    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 129.18 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
    Binaries:
    Node: 13.3.0 - /usr/local/bin/node
    npm: 6.13.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
    iOS SDK:
    Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
    API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28, 29
    Build Tools: 28.0.3, 29.0.2
    System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
    npmGlobalPackages:
    react-native-cli: 2.0.1

- **Platform that you're experiencing the issue on**:
  - [x] iOS
- **Are you using `TypeScript`?**
  - `Y` & `3.7.4`

---

Last but not least, thank you for the great library ❤️

**Comment by Ehesp** [comment]
Version 6.4.0 release candidate is available and fixes the major ios messaging issues.

We can't support v5, it's over a year old. Can you upgrade and let us know how you get on?

**Comment by LuongTruong** [comment]
Hello @Ehesp , I am really appreciated your help. I will try

**Comment by Ehesp** [comment]
Thanks. Let us know how you get on. Will close for now.

**Comment by LuongTruong** [comment]
Hello @Ehesp , sorry writing a comment in a closed ticket, you are my only hope. I wonder how can we receive a notification in v6. I use the below code for v5:

    firebase.notifications().onNotification((notification) => {
    });

In v6, I am able to get the FCM token by following the below link:

- [Set up @react-native-firebase/app](https://invertase.io/oss/react-native-firebase/quick-start/existing-project) 
- [Android Firebase Credentials](https://invertase.io/oss/react-native-firebase/quick-start/android-firebase-credentials)

But when I send push notification using Firebase Console, I am not able to receive it.

Please let me know what am I missing.

Thank you in advanced!

**Comment by Ehesp** [comment]
We're working on new documentation, you can check a preview out here: https://rnfb-docs.netlify.com/messaging/usage

It's currently work in progress but it a LOT more detailed than the current docs.

**Comment by LuongTruong** [comment]
Thank you @Ehesp for the extremely quick response. I found this in your link

- [Message Handler](https://rnfb-docs.netlify.com/messaging/usage#message-handlers)

From my understanding, everything will be move into `onMessage` function, however, I receive nothing from my `onMessage` when my app is in foreground

Below is my code:

    export async function onPayloadReceived() {
    
        console.log('listening for Payload');
    
        messaging().onMessage(async (remoteMessage) => {
            console.log('FCM Message:', remoteMessage);
        });
    }

And I call it in ComponentDidMount.

Please let me know if I did anything wrong. Thank you in advanced!
