### ISSUE TITLE
No way to unsubscribe from notifications

### ISSUE THREAD

**Issue by JesperLekland** [invertase/react-native-firebase#338]
There is currently no way to programmatically detach from FCM, say for example when a user logs out. For example `deleteInstanceId` with `react-native-fcm`

**Comment by chrisbianca** [comment]
You're right, there isn't at the moment, though you don't need to necessarily detach from FCM.  The other way of approaching this is to remove the link in your own DB between the user and the token, so that your backend will no longer send notifications to the device.

This is the design that I use in my apps.  Is there a reason that programmatically detaching from FCM is better?

**Comment by JesperLekland** [comment]
That is indeed a possible solution. My main issue with that is if the user is currently offline, then we need to implement a bunch of fallbacks. Nothing major, but still cumbersome.

Unrelated to this issue but a question now that I have you "on the line". The documentation regarding received messages is pretty poor. Why is for example a message body from iOS wrapped in an `aps: {alert: 'body'}` but on android it wrapped in something different `fcm: {body: 'body'}(?)`?. And do we need to call the `finish` function?

**Comment by chrisbianca** [comment]
Offline is a fair scenario which I hadn't considered.  As you can see I've marked this as a feature request which we'll look to incorporate as soon as we can.  We're focused on getting v3 out of the door right now, along with a few other bits.  Please feel free to submit a PR if you'd like to and we'll be able to get this incorporated much more quickly.

Messaging in general is an area that we need to spend some time with, not just on documentation, but also on how it works.  The differences between how notifications work across the Android and iOS operating systems does present some challenges, but ones that we feel we can better abstract away from the user.  We're just working out how best to approach this and will look to tackle in a future release.

The `finish` function is iOS specific, and is called automatically if you don't choose to invoke it manually.

**Comment by JesperLekland** [comment]
Great! Thanks for the quick feedback. If I get some spare time I'll definitely have a look at contributing.

**Comment by bm-software** [comment]
Any news?

**Comment by bm-software** [comment]
I've create a [PR#443](https://github.com/invertase/react-native-firebase/pull/443) that will add this feature.

**Comment by chrisbianca** [comment]
@bm-software Thanks for the PR - it has now been merged and will be a part of the upcoming v3 beta.
