### ISSUE TITLE
On iOS devices, I cannot receive notifications when the application is on the front.

### ISSUE THREAD

**Issue by Akifblc** [invertase/react-native-firebase#3383]
Hello,

I am using version 5.6.0 of react-native-firebase. My purpose is to use firebase analytics.

I use another notification center as the notification center.
IOS phones do not receive notifications when the application is in the foreground.
When I debugged the problem, I found that the following code in RNFirebase / notification / RNFirebaseNotifications.m blocked the preliminary notifications.

Can you help with the subject?

    if (isFcm || isScheduled) {
        // If app is in the background
        if (RCTSharedApplication().applicationState == UIApplicationStateBackground
            || RCTSharedApplication().applicationState == UIApplicationStateInactive) {
            // display the notification
            options = UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionBadge | UNNotificationPresentationOptionSound;
            // notification_displayed
            event = NOTIFICATIONS_NOTIFICATION_DISPLAYED;
        } else {
            // don't show notification
            options = UNNotificationPresentationOptionNone;
            // notification_received
            event = NOTIFICATIONS_NOTIFICATION_RECEIVED;
        }
    } else {
        // Triggered by `notifications().displayNotification(notification)`
        // Display the notification
        options = UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionBadge | UNNotificationPresentationOptionSound;
        // notification_displayed
        event = NOTIFICATIONS_NOTIFICATION_DISPLAYED;
    }

**Comment by Akifblc** [comment]
While the application is in the foreground, it falls on the "else" line without entering the below "if" line.

if (RCTSharedApplication().applicationState == UIApplicationStateBackground
        || RCTSharedApplication().applicationState == UIApplicationStateInactive) {
        // display the notification
        options = UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionBadge | UNNotificationPresentationOptionSound;
        // notification_displayed
        event = NOTIFICATIONS_NOTIFICATION_DISPLAYED;
    } else {
        // don't show notification
        options = UNNotificationPresentationOptionNone;
        // notification_received
        event = N

**Comment by Ehesp** [comment]
Please upgrade to `6.4.0-rc4`, it includes loads of messaging updates.

When your application is in the foreground, the FCM SDKs will not present a notification if it includes a notification payload. They will only be shown when the app is in the background or quit.

**Comment by ramakula** [comment]
There is a requirement in our app to show notification even when the app is in foreground (both iOS and Android). Is it possible to do that? We are on version 6.3.0. I can't find any such option in your documentation.

**Comment by Ehesp** [comment]
@ramakula it's possible, but it's called a local notification rather than remote.  Solutions such as [Notifee](https://notifee.app/), https://github.com/wix/react-native-notifications, https://github.com/zo0r/react-native-push-notification exist.

**Comment by ramakula** [comment]
@Ehesp Thanks for the prompt response. So rnfirebase doesn't support local notifications? If not,  I would like to implement our own solution for local notifications but how do we know when it arrives from firebase? Is there a listener in rnfirebase framework that we can listen to? I tried onMessage and it is not working for notif only notifications.  we are on version 6.3.0

**Comment by Ehesp** [comment]
Check the updates on 6.4.0, there was a big rework of messaging. on Message should still be working.

**Comment by ramakula** [comment]
Sure @Ehesp Thank you.

**Comment by bhvk121** [comment]
In iOS, when my App fires local notification which needs to be shown when App is in the Foreground -  using NativeModules with UNUserNotificationCenter:

It is not getting handled by this method, and ultimately - UNNotificationPresentationOptionNone is returned - so App is not able to show local notification in the Foreground. 

- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler {
  
if (notification.request.content.userInfo[@"gcm.message_id"]) {
    NSDictionary *notificationDict = [RNFBMessagingSerializer notificationToDict:notification];

    // Don't send an event if contentAvailable is true - application:didReceiveRemoteNotification will send the event
    // for us, we don't want to duplicate them
    if (!notificationDict[@"contentAvailable"]) {
      [[RNFBRCTEventEmitter shared] sendEventWithName:@"messaging_message_received" body:notificationDict];
    }

    // TODO in a later version allow customising completion options in JS code
    completionHandler(UNNotificationPresentationOptionNone);
} }


Using: "@react-native-firebase/messaging": "version": "6.4.0"

Can someone help with this, so App can show local notification for the Foreground state.

@Akifblc  @Ehesp

**Comment by sewerynzalupka** [comment]
@bhvk121 I have the exact same problem

Changing implementation of `RNFBMessagingUNUserNotificationCenter`, in particular the `userNotificationCenter:willPresentNotification:withCompletionHandler:` method body to:
```objective-c
- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler {
  if (notification.request.content.userInfo[@"gcm.message_id"]) {
    NSDictionary *notificationDict = [RNFBMessagingSerializer notificationToDict:notification];

    // Don't send an event if contentAvailable is true - application:didReceiveRemoteNotification will send the event
    // for us, we don't want to duplicate them
    if (!notificationDict[@"contentAvailable"]) {
      [[RNFBRCTEventEmitter shared] sendEventWithName:@"messaging_message_received" body:notificationDict];
    }
  }

  if (_originalDelegate != nil && originalDelegateRespondsTo.willPresentNotification) {
    [_originalDelegate userNotificationCenter:center willPresentNotification:notification withCompletionHandler:completionHandler];
  } else {
    completionHandler(UNNotificationPresentationOptionNone);
  }
}
```
fixes that for me

the question is - why notifications which contain `"gcm.message_id"` key in `userInfo` dictionary are currently handled differently from all others in several methods of `RNFBMessagingUNUserNotificationCenter` and basically blocking the original delegate code from executing?

**Comment by russellwheatley** [comment]
Thanks for the issue report @Akifblc. I'm going to close this issue as the OP intended it for `react-native-firebase` `v5` which is no longer actively supported. If you wish to open an issue relating to the messaging API for `>= v6`, then please feel free to do so.
