### ISSUE TITLE
Firebase not compatible with RN 0.47.1

### ISSUE THREAD

**Issue by soundstage** [invertase/react-native-firebase#339]
1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): Windows 10
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Nuclide
4. React Native version (e.g. 0.45.1): 0.47.1
5. RNFirebase Version (e.g. 2.0.2): 4.2.0

After installing Firebase to the application that I am developing, it has become impossible to run the application as I constantly keep getting an that reads "Cannot find module 'set-blocking'". 

I think this error is due to incompatibility between RN 0.47.1 and RNFirebase as I get this error only if RNFirebase is installed in the application.

**Comment by Salakar** [comment]
This is an issue with your installation and not RNFirebase 🙈 

One of your dependencies is trying to require the npm library 'set-blocking' and it's not finding it installed in node_modules, see here: https://www.npmjs.com/browse/depended/set-blocking to figure out which one of your dependencies it could be.
