### ISSUE TITLE
Update Phone Auth demonstration code

### ISSUE THREAD

**Issue by DipanshKhandelwal** [invertase/react-native-firebase#3397]
## Documentation Feedback

The code does not work due to incomplete imports

`useState` is not imported from `react`

- 👉 Check out [`Phone Auth Doc`](https://github.com/invertase/react-native-firebase/blob/master/docs/auth/phone-auth.md)

**Comment by DipanshKhandelwal** [comment]
The OTP is also not picked up from text field.

**Comment by russellwheatley** [comment]
Thanks for picking that up, I've approved your PR 👍
