### ISSUE TITLE
IOS remote notification not working

### ISSUE THREAD

**Issue by Zilleabbas10** [invertase/react-native-firebase#3400]
Hi,

I am recieving payload of notification when app is open but i am not getting notification popup when app is in background or killed. Following is the payload i am recieving

`{"_collapseKey":"ai.twic.twicapp","_data":{"body":"Payload notification message","title":"New Notification","content_available":"true","priority":"high"},"_from":"448164920871","_messageId":"-M4Df5IHogstaYiXTzOS","_ttl":3600}`

Don't know what i am missing. @Salakar  Please help, i am stuck in this for last few days!

**Comment by Salakar** [comment]
Please fill out the issue template, I have no idea what versions you're using etc. Please try again with the template filled out.
