### ISSUE TITLE
Application stuck in splash screen after upgrade to 6.4, LogBox error

### ISSUE THREAD

**Issue by beetlebum** [invertase/react-native-firebase#3401]
## Issue
After upgrading from 6.3.x to 6.4, the application on the simulator could not get past the splash screen. Downgrading the packages to 6.3 would immediately make the app boot, even without downgrading the pods.

After some tinkering and disabling the splash screen, I managed to see this error:
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-06 at 11 54 31](https://user-images.githubusercontent.com/227258/78551788-369ed980-77fe-11ea-89f1-4aae437841aa.png)

It's related to the new logbox in React Native 0.62, which is not on by default. After removing the line that enables it, the app boots normally again.
```require('react-native').unstable_enableLogBox();```
That line is at the top of index.js. I've commented it out for now as a workaround.

Any ideas about changes in the latest release that might have triggered this issue?

Thanks!

---
## Environment

**`react-native info` output:**
```
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 252.22 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.0 => 16.13.1 
    react-native: ^0.62.0 => 0.62.1 
```

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Interesting! Can I ask a favor? Can you try reproducing this with the throwaway project generated when you run: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

That should generate a react-native 0.62 project with react-native-firebase 6.4.0, and if altering the index.js to include the logbox line shows it there then we have a really clean reproduction

**Comment by diego-better-half** [comment]
@mikehardy I've followed the steps but can't get the demo project to run on the simulator, application won't even start.
Before digging any further, it has occurred to me that this error might be related to the `isHeadless` prop? is the app wrapped in another component when using messaging? that might make logbox not the first code to run and hence the error. 
I believe it's going to be enabled by default in RN 0.63 so this wouldn't be an issue anymore.

**Comment by Ehesp** [comment]
The messaging module passes that prop down to your registered component on ios, maybe that's causing some problems?

**Comment by mikehardy** [comment]
Strange - I just re-ran make-demo-v6.sh and it works for me, however I specifically do not do the messaging module in that one. I should add it now that messaging integration is so much easier, but that's the one I don't do. So the script works as is but if you add messaging and demonstrate the failure, then we have something to look at. Is that what you did @diego-better-half ?

**Comment by mateusmirandaalmeida** [comment]
This is a temporary solution: https://github.com/react-native-community/upgrade-support/issues/39
