### ISSUE TITLE
Invaild Dynamic Link -  ( iOS) 

### ISSUE THREAD

**Issue by Kiranyellu** [invertase/react-native-firebase#3404]
## Issue

I have been working on RNFirebase iOS dynamic link.
When I try to open the app through the dynamic URL which is created in Firebase Dynamic link and when I run the URL  in Safari / Chrome then it gives the "Invalid Dynamic Link" Firebase.

React-Native : 0.62,
RNFirebase: 5.6.0,

bundle Identifier : com.appName.app
URL type:  Identifier : com.appName.app
Schemas: https://appNameDemo.page.link
Dynamic link : https://appNameDemo.page.link
### iOS

<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
pod 'Firebase/Core', '~> 6.13.0'

```

#### `AppDelegate.m`:

```objc
    [FIRApp configure];
    [FIROptions defaultOptions].deepLinkURLScheme = @"https://appNameDem0.page.link";
     
```

</p>
</details>

## Environment

<p>

**`react-native info` output:**

```
Invalid Dynamic LInk

Requested URL (https://appName.page.link) must be a parable and complete DyanamicLink.

If you are the developer of this app, ensure that youR Dynamic Link domain is correctly configured and that the path component of this URL is valid. 
```

- **Platform that you're experiencing the issue on**:
  - [x]  iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by pabloluz** [comment]
@Kiranyellu `deepLinkURLScheme` should be your app's scheme local your deep link domain url.

**Comment by JongGyuChoi** [comment]
i have same error in ios

**Comment by russellwheatley** [comment]
Thanks for the issue report, @Zilleabbas10, however we’re no longer actively supporting `<= v5` development so I’m going to go ahead and close this issue - but feel free to continue the discussion if required. If there are any persisted issues regarding React Native Firebase `>= v6`, please raise a new issue.
