### ISSUE TITLE
OTP verification is not working in react-native firebase on release Android Apk

### ISSUE THREAD

**Issue by raviranjan528** [invertase/react-native-firebase#3407]
Hello,
after I generated signed apk in android by
cd android && ./gradlew release apk
I tested on my phone with the apk I generated and when I enter my phone I got otp but I am getting error like your OTP is expired, I tried multiple times .

HERE IS THE CODE for send verification code from sign-in screen.

 validatePhoneNumber = () => {
    var regexp = /^\+[0-9]?()[0-9](\s|\S)(\d[0-9]{8,16})$/
    console.log('this.state.phone', this.state.phone);
    return regexp.test(this.state.phone);
  }

  handleSendCode = () => {
    // Request to send OTP
    console.log('handleSendCode', this.state.phone);
    if (this.validatePhoneNumber()) {
      auth()
        .signInWithPhoneNumber(this.state.phone)
        .then(confirmResult => {
          console.log('confirmResult', confirmResult);
          this.setState({ confirmResult });
          this.props.navigation.navigate('OTPScreen', {
            confirmResult: this.state.confirmResult,
        });
        })
        .catch(error => {
          alert(error.message)

          console.log(error)
        })
    } else {
      alert('Invalid Phone Number ----', this.state.phone)
    }
  }

  changePhoneNumber = () => {
    this.setState({ confirmResult: null, verificationCode: '' })
  }

  render() {
    const styles = Theme.getStyles(styleSheet);
    return (
      <SafeAreaView style={{ flex: 1}}>
      <ScrollView contentContainerStyle={styles.container}>
        <View style={styles.welcomeText}>
          <Heading value="Welcome" color={Colors.white} type="h1" marginBottom={10}/>
          <Heading value="App allows to track your expenditures and credit bill payments" color={Colors.white} type="h2"/>
        </View>
        <View style={styles.inputWrapper}>
          <DefaultInput placeholder="Enter your phone number" keyboardType='phone-pad'
            value={this.state.phone}
            onChangeText={phone => {
              this.setState({ phone: phone })
            }} maxLength={15} marginBottom={30} inputIcon={PhoneCall} />
          <DefaultButton buttonText="Continue"
                    // marginBottom = {40}
                    position ="center"
                    Icon={RightArrow}
                    onPress={
                      this.state.confirmResult
                        ? this.changePhoneNumber
                        : this.handleSendCode
                    } />
      </ScrollView>
      </SafeAreaView>
    );
  }

HERE IS THE CODE for send verification code from OTP screen.

  handleVerifyCode = () => {
    // Request for OTP verification
    const { confirmResult, verificationCode } = this.state
    console.log('verificationCode', this.state.verificationCode);
    if (verificationCode.length == 6) {
      confirmResult
        .confirm(verificationCode)
        .then(user => {
          this.setState({ userId: user.uid })
          this.props.navigation.navigate('OTPSuccess', {
            userId: user.uid,
          });
        })
        .catch(error => {
          alert(error.message)
          console.log(error)
        })
    } else {
      alert('Please enter a 6 digit OTP code.')
    }
  }

  render() {
    const styles = Theme.getStyles(styleSheet);
    return (
      <SafeAreaView style={{ flex: 1}}>
      <ScrollView contentContainerStyle={styles.container}>
        <View style={styles.welcomeText}>
          <Heading value="Welcome" color={Colors.white} type="h1" marginBottom={10}/>
          <Heading value="App allows to track your expenditures and credit bill payments" color={Colors.white} type="h2"/>
        </View>
        <View style={styles.inputWrapper}>
          <DefaultInput placeholder="Enter OTP" marginBottom={30} inputIcon={PhoneCall} 
          value={this.state.verificationCode}
          keyboardType='numeric'
          onChangeText={verificationCode => {
            this.setState({ verificationCode })
          }}
          maxLength={6} />
          <Heading  value="Please, enter 6-digit code sent on your number"  type="h2" marginHorizontal={30} marginBottom={20}/>
          <DefaultButton buttonText="Continue"
                    // marginBottom = {40}
                    position ="center"
                    Icon={RightArrow}
                    onPress={this.handleVerifyCode} />
          </View>
        
      </ScrollView>
      </SafeAreaView>
    );
  }
}

Version
Android version 9
react-native :  "0.61.5",
 "@react-native-firebase/auth": "^6.3.1",

**Comment by Ehesp** [comment]
Have you added the SHA fingerprint to your app?

Under Settings in the console, select your app and add the fingerprint. Re-download the config file and rebuild.

**Comment by raviranjan528** [comment]
Yeah, I had already added the SHA fingerprint in the application.

**Comment by raviranjan528** [comment]
Yeah, I had already added the SHA fingerprint in the application.

<img width="631" alt="Screenshot 2020-04-07 at 2 16 59 PM" src="https://user-images.githubusercontent.com/5329275/78649566-3fb1a880-78db-11ea-967a-5ee7d4c1632c.png">

**Comment by raviranjan551994** [comment]
@Ehesp @russellwheatley @ Can you please help me to get rid of this?

**Comment by raviranjan528** [comment]
@Ehesp @russellwheatley Can you please help me to get rid of this ?

**Comment by suretarget** [comment]
Just want to confirm that SHA-1 fingerprint in release are not the same as the one in app-signing in play store console.
[Check this link](https://stackoverflow.com/a/53513327)

**Comment by MuhammadUsman786786** [comment]
@raviranjan528  have ur issue is fixed?

**Comment by tunm1228** [comment]
On some Android devices, it's always on auth/session-expired

**Comment by rajparmar7879** [comment]
Yes On some Android devices, it's always on auth/session-expired issue.
