### ISSUE TITLE
Push notification received in debug mode but not in release mode on ios 

### ISSUE THREAD

**Issue by liamtraAditya** [invertase/react-native-firebase#3409]
Hi, I am trying to implement react native firebase push notifications on my project.
I have successfully implemented in==on android and its working fine the issue is with the IOS version. I tried what doc says but the issue is sometimes I started to get the notification in debug mode but when I change it to release mode and build the app then it would not work.
I am not sure what  is happening sometimes it not even work in debug mode

**Package.json**
    "react-native": "0.61.5",
  "react-native-firebase": "^5.6.0",

**Podfile**

pod 'Firebase/Core'
pod 'Firebase/Messaging'

pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
 post_install do |installer|
   rnfirebase = installer.pods_project.targets.find { |target| target.name == 'RNFirebase' }
   rnfirebase.build_configurations.each do |config|
     config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
   end
 end

**AppDelegate.m**

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>
#import "RNFirebaseNotifications.h"
#import "RNFirebaseMessaging.h"
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
[FIRApp configure];
[RNFirebaseNotifications configure];
  [application registerForRemoteNotifications];
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"liamtraApp"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
[[RNFirebaseNotifications instance] didReceiveLocalNotification:notification];
}
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
[[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}
- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
[[RNFirebaseMessaging instance] didRegisterUserNotificationSettings:notificationSettings];
}

@end

**Comment by russellwheatley** [comment]
Thanks for the issue report, @liamtraAditya , however we’re no longer actively supporting `<= v5` development so I’m going to go ahead and close this issue - but feel free to continue the discussion if required. If you have any issues regarding React Native Firebase `>= v6`, please raise a new issue.
