### ISSUE TITLE
Is there a way to set the persistence cache size?

### ISSUE THREAD

**Issue by escobar5** [invertase/react-native-firebase#341]
Is it possible to set the cache size?

https://firebase.google.com/docs/reference/android/com/google/firebase/database/FirebaseDatabase.html#setPersistenceCacheSizeBytes(long)

**Comment by Ehesp** [comment]
I don't believe this is implemented, however we'll do that today on both the v2 & v3 branch. I'll check out ios side too.

**Comment by Ehesp** [comment]
Just quickly did this for v2 on the train, https://github.com/invertase/react-native-firebase/tree/cache-size, needs testing etc though which I'll do in a bit.

**Comment by escobar5** [comment]
you're quick man! 😄 

Thanks
