### ISSUE TITLE
🔥Issue with fabric

### ISSUE THREAD

**Issue by dakkafex** [invertase/react-native-firebase#3410]
## Issue

Describe your issue here
I have updated from 6.2 to 6.4 and when trying to install pods im getting the following error
```
[!] CocoaPods could not find compatible versions for pod "Fabric":
  In snapshot (Podfile.lock):
    Fabric (= 1.9.0, ~> 1.9.0)

  In Podfile:
    RNFBCrashlytics (from `../node_modules/@react-native-firebase/crashlytics`) was resolved to 6.4.0, which depends on
      Fabric (~> 1.10.2
```
---

#### `package.json`:

```json
  "dependencies": {
    "@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/slider": "^2.0.5",
    "@react-native-firebase/app": "6.4.0",
    "@react-native-firebase/auth": "6.4.0",
    "@react-native-firebase/crashlytics": "6.4.0",
    "@react-native-firebase/database": "6.4.0",
    "@react-native-firebase/firestore": "6.4.0",
    "@react-native-firebase/storage": "6.4.0",
    "@turf/distance": "^6.0.1",
    "firebase": "^7.5.0",
    "latlon-geohash": "^2.0.0",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "react": "16.9.0",
    "react-native": "0.61.3",
    "react-native-background-fetch": "^2.7.1",
    "react-native-background-geolocation": "^3.4.2",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "^1.5.0",
    "react-native-image-picker": "^1.1.0",
    "react-native-image-view": "^2.1.8",
    "react-native-maps": "0.26.1",
    "react-native-reanimated": "^1.3.1",
    "react-native-screens": "^2.0.0-alpha.6",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^9.13.3",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.0.10",
    "react-navigation-header-buttons": "^3.0.4",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.5.6"
  },
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

Shouldnt this be automated?

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.4.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `crashlytics`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
How did it go when you removed Podfile.lock and ran pod install?
