### ISSUE TITLE
Why are these entries required in Podfile ?

### ISSUE THREAD

**Issue by ajonno** [invertase/react-native-firebase#342]
I don't understand what these entries are required in a Podfile and so would like to understand this better. My concern is that they appear to be core React Native libs - why are they required to be installed via Cocoapods ? Many thanks.

**Comment by Ehesp** [comment]
Which entries?

**Comment by ajonno** [comment]
Doh that's what happens when too busy..

These ones:

pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
pod 'React', :path => '../node_modules/react-native', :subspecs => [
 'BatchedBridge', # Required For React Native 0.45.0+
 'Core',
 # Add any other subspecs you want to use in your project
]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chrisbianca** [comment]
They are there to allow RNFirebase to compile as a pod.  I'm currently looking at ways to get RNFirebase working without needing to be set up in Cocoapods, and using `react-native link` instead.  However there are some limitations in `react-native link` which need to be overcome first.
