### ISSUE TITLE
Testing not documented

### ISSUE THREAD

**Issue by karlmarxlopez** [invertase/react-native-firebase#3421]
## Documentation Feedback

Please add documentation on testing/mocking on every release. 

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
We test the library internally, however haven't pursued how to allow external integration testing (e.g. mocking). This is possible as there is a few other issues about it. Happy to accept PRs to improve the docs or any library requirements.

**Comment by karlmarxlopez** [comment]
Hi @Ehesp, can we include the `__mocks__` on the build so that the library consumes will just include it on their `jest.setup.js`?
