### ISSUE TITLE
migrated to v6 from v5 and facing challenges

### ISSUE THREAD

**Issue by rananajam1** [invertase/react-native-firebase#3424]
## Issue

Describe your issue here

---
Migrated to v6 using https://rnfirebase.io/migrating-to-v6 and facing the following issues:
1) App gets crashed on launch
2)App gets crashed when I recieve message using messaging().onMessage()
3)Whats the equivalent of firebase.notifications().onNotification()?
4)Whats the equivalent of firebase.notifications().getBadge()?

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ x ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 3.59 GB / 15.88 GB
  Binaries:
    Node: 13.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 6.4.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. messaging().onMessage, firebase.notifications()`
- **Are you using `TypeScript`?**
  - `N` 

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
All crash reports need their associated stack traces in order to help
in Android you can get them with logcat, on iOS they'll show up in Xcode

**Comment by rananajam1** [comment]
@mikehardy thanks! and how can I use firebase.notifications().getBadge() in v6

**Comment by mikehardy** [comment]
There are no notifications in v6, and (though I recognize it's not really helpful) I wouldn't recommend badging at all. It's a disavowed design pattern on Android

**Comment by rananajam1** [comment]
@mikehardy sad but thanks

**Comment by rananajam1** [comment]
@mikehardy by app crash i actually meant it minimizes when i recieve a message on the listener. No log for that

**Comment by mikehardy** [comment]
You did not fill out the template, so I'm not sure what versions you are on, but I'd strongly recommend making sure you were on react-native-firebase 6.4.0 as it saw a *massive* change with regard to internal handling of FCM, and might behave differently if you are not on it. If you are on it, then I'm sorry but I don't know why your app would minimize when you received a message, I've not heard of that

**Comment by Salakar** [comment]
Closing in favour of #3413
