### ISSUE TITLE
How to reauthentificate on app launch?

### ISSUE THREAD

**Issue by zoontek** [invertase/react-native-firebase#344]
Hello,

I think it's not really an issue, but more a question.
After using firebase auth `signInWith...` methods and having a `currentUser`, how can I keep it thought app closes? (or reauthentificate the user without asking him to enter his credentials again)

I try various things, none of them seems to work.
Thanks!

**Comment by Ehesp** [comment]
You should look into `auth().onAuthStateChanged()`. By default, unless you call `signOut()` the user will be persisted across app restarts.

Basically you want to subscribe to `onAuthStateChanged` when the app opens, and have this reflect your apps state, whether that be through redux or other ways.
