### ISSUE TITLE
Proguard rules needed for projects using code shrinking

### ISSUE THREAD

**Issue by SaeedZhiany** [invertase/react-native-firebase#3440]
## Documentation Feedback

library version: 6.4.0

I couldn't find what proguard rules are needed for adding in my project's proguard file.
I didn't find any proguard file in packages' android folder too.

I'm already facing with 64k reference limit and needed to enable code shrinking. I'll be appreciated for any quick response.

Thanks.

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
That's a losing fight, use MultiDex is my standard response - but I think you're really skilled at gradle and java build if my memory is correct, so you probably know that and must have some other reason?

Either way, proguard should work (works for me?) and any necessary rules (like those from the upstream SDKs) should be included without doing anything if I understand correctly?

For v5 I have:

```

# react-native-firebase section
-keep class io.invertase.firebase.** { *; }
-dontwarn io.invertase.firebase.**
# end react-native-firebase section
```

But I'm not sure that's even necessary.

**Comment by SaeedZhiany** [comment]
According to Android documentation, using MultiDex should be the last approach for 64k reference limit, because it may cause a  noticeable delay when reloading Dex files at runtime. (the problem is more likely happens on low-end devices)

The thing is I migrated my RN project from 0.59.10 to 0.62.2. for auto-link supporting, I have to upgrade all dependencies of the project to the latest version. some of them are changed completely especially `react-navigation` and add too many peer dependencies with native modules. so it causes the 64k reference limit problem.

For the first try, I start using `minifyEnabled true` and the project could build into one Dex file (the 64k reference limit has been solved) but the application force closed on runtime.

so I need to config my proguard rules to keep the necessary files.

I remembered RNF v5 there are some proguard rules which you mentioned above.
My actual question is, does RNF v6 needed or have some rules like RNF v5? can we use the above rules for RNF v6? is package naming in RNF v6 is the same as RNF v5, I couldn't find `io.invertase.firebase` package. which package should I look for them?

> Either way, proguard should work (works for me?) and any necessary rules (like those from the upstream SDKs) should be included without doing anything if I understand correctly?

are these questions? or an answer to me? (you using question marks, makes me confused 😄 )

**Comment by mikehardy** [comment]
I see them as separate
Avoiding proguard while using firebase is to me a lost battle. You don't want to minify dev builds while testing old APIs? I enable MultiDex every time. I don't notice delays really when I test, and I have some old real devices. That's one part

Second part is you are going to minify release builds no matter what, or you should - that's a space optimization so you take up less storage etc, it can save megabytes. And for that from v5 to v6 I don't think v6 has any required rules. The template here has none, the docs have none etc. The final answer is to test and make sure though of course

**Comment by SaeedZhiany** [comment]
Saving some megabytes is not my priority for building apps. So I don't minify for that purpose. as I said I'm worried about devices running androids lower than v5 (API 21) and I have no such device to test my app on them before publishing a new version.

As I never had to enable multidex and even proguard for my other applications this is my first experience with them. I wanted to take the best option I have.

I'll try to enabling proguard in the first step and see how it is going. I'll submit a PR if I found some necessary rules for this library.

Thank you for your response.

**Comment by SaeedZhiany** [comment]
Saving some megabytes is not my priority for building apps. So I don't minify for that purpose. as I said I'm worried about devices running androids lower than v5 (API 21) and I have no such device to test my app on them before publishing a new version.

As I never had to enable multidex and even proguard for my other applications before, this is my first experience with them. I wanted to take the best option I have.

I'll try to enabling proguard in the first step and see how it is going. I'll submit a PR if I found some necessary rules for this library.

Thank you for your response.

**Comment by SaeedZhiany** [comment]
a

**Comment by SaeedZhiany** [comment]
a

**Comment by SaeedZhiany** [comment]
a

**Comment by HigorMartinez** [comment]
> Saving some megabytes is not my priority for building apps. So I don't minify for that purpose. as I said I'm worried about devices running androids lower than v5 (API 21) and I have no such device to test my app on them before publishing a new version.
> 
> As I never had to enable multidex and even proguard for my other applications before, this is my first experience with them. I wanted to take the best option I have.
> 
> I'll try to enabling proguard in the first step and see how it is going. I'll submit a PR if I found some necessary rules for this library.
> 
> Thank you for your response.



> ## Documentation Feedback
> library version: 6.4.0
> 
> I couldn't find what proguard rules are needed for adding in my project's proguard file.
> I didn't find any proguard file in packages' android folder too.
> 
> I'm already facing with 64k reference limit and needed to enable code shrinking. I'll be appreciated for any quick response.
> 
> Thanks.
> 
> * 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

Hi,

I had this problem days ago, just add this line "multiDexEnabled true" to the android/app/build.gradle document:

   defaultConfig {
        applicationId "com.socialapp_teste2"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        multiDexEnabled true //add this...
    }

I hope it works for you.

**Comment by SaeedZhiany** [comment]
Thanks, @HigorMartinez

Yes, Already I use `multiDexEnabled true`. but I prefer to complete my proguard configs and shrink my code and reduce my apk size (in my free time). that's why I'm still keeping this issue open. maybe someone can complete the RNFB related configs sooner.

**Comment by mikehardy** [comment]
I'm still unaware of any proguard-related failures. I use proguard with v6. This issue is open but I predict the stale bot will get it and close it for lack of interest, as it appears to be working. It's unrelated to multidex, that's documented already, and you need 3 items not just the one you mention.

**Comment by SaeedZhiany** [comment]
It's true. I didn't ask for the multidex configuration in this issue because I knew how to do it.

I just opened this issue to ask help from someone (that probably has the same goal and maybe has more free time) to find and complete RNFB's proguard rules.

It's really a hard task and needs more tries to complete the rules and finding what part of proguqrd errors are related to RNFB, because I'm using about ten other modules and the errors log is too many.

I have no problem closing it, if my attempt succeeds I can leave a comment here again for reopening this issue.

**Comment by mikehardy** [comment]
I will close then. I have no issue using ProGuard and RNFBv6+. It works.
