### ISSUE TITLE
notifications was not showing, had to make some changes to work it 

### ISSUE THREAD

**Issue by nikTC** [invertase/react-native-firebase#3441]
## Documentation Feedback
I have followed each step and everything was working fine except popping up the notification after receiving from the server (which I was sending from postman). It was coming to the phone I can see them on the console.

to fix them I have to install new library react-native-push-notification and had to do androidManifest.xml settings as per their docs to show notifications.

please have a look into this and add the same into your documents.

sorry if you have already added that into the existing guide and I have missed it.

**Comment by Ehesp** [comment]
PR welcome. No idea what changes you did, or why, so not too sure what to add in.
