### ISSUE TITLE
Receiving null verification ID and not receiving OTP for android

### ISSUE THREAD

**Issue by ahadshaikh05** [invertase/react-native-firebase#3445]
I am using the latest version of the react native firebase(6.4.0).
It is working well in ios . But android is not receiving otp and getting verification id as null.

**Comment by suretarget** [comment]
Hi, I guess the phone you are using for testing perform an **instant verification** 
[More info](https://stackoverflow.com/questions/48334262/firebase-phone-authentication-sms-code-null-android/48906032#48906032). You can verify by observing the **state_changed**

```
const phoneNumber = '+44 7444 555666';
auth().verifyPhoneNumber(phoneNumber).on('state_changed', phoneAuthSnapshot => {
    if (phoneAuthSnapshot.state === 'verified') {
        console.log(phoneAuthSnapshot.state);
    } else if (phoneAuthSnapshot.state === 'sent') {
        console.log(phoneAuthSnapshot.state);
    } else if (phoneAuthSnapshot.state === 'timeout') {
        console.log(phoneAuthSnapshot.state);
    } else {
        console.log(phoneAuthSnapshot.state);
    }
});
```
In your case you should see 'verified' in your console. Thus, you don't have to display input verification code.

**Comment by ahadshaikh05** [comment]
Hello, 
Thank you, the method works fine. But it sends the otp again. I am using it after getting the results of  firebase.auth().signInWithPhoneNumber. I will only have to use auth().verifyPhoneNumber only. Then how to verify the code

**Comment by suretarget** [comment]
Hi,
Before this I use auth().signInWithPhoneNumber too, which is **short an easy**. 
It works fine on iOS & Android but it doesn't work on some Android phone number that perform an instant verification (verification id: null).

Yes, you have to use  auth().verifyPhoneNumber only. You will get otp (SMS) twice if you use it after signInWithPhoneNumber. 

To verify the code, I did:

// if phoneAuthSnapshot.state is sent I show input verification code
```
import app from '@react-native-firebase/app';

const credential = app.auth.PhoneAuthProvider.credential(
    verificationId,
    code,
);

auth().signInWithCredential(credential)
     .then(userCredential => {
       // Navigate to other screen.
       console.log(userCredential);
    })
    .catch(error => {
       console.log(error);
});

```
That's what I did to solve instant verification (verification id: null).
If someone has an easier way to solve instant verification kindly share. Thanks.

**Comment by russellwheatley** [comment]
Hi @ahadshaikh05, thanks for raising the issue. This problem is already being tracked [here](#2895), so I'm going to close this issue. If you have any other problems with React Native Firebase `>= v6`, please raise a new issue.

**Comment by LuciferLat** [comment]
> Hi,
> Before this I use auth().signInWithPhoneNumber too, which is **short an easy**.
> It works fine on iOS & Android but it doesn't work on some Android phone number that perform an instant verification (verification id: null).
> 
> Yes, you have to use auth().verifyPhoneNumber only. You will get otp (SMS) twice if you use it after signInWithPhoneNumber.
> 
> To verify the code, I did:
> 
> // if phoneAuthSnapshot.state is sent I show input verification code
> 
> ```
> import app from '@react-native-firebase/app';
> 
> const credential = app.auth.PhoneAuthProvider.credential(
>     verificationId,
>     code,
> );
> 
> auth().signInWithCredential(credential)
>      .then(userCredential => {
>        // Navigate to other screen.
>        console.log(userCredential);
>     })
>     .catch(error => {
>        console.log(error);
> });
> ```
> 
> That's what I did to solve instant verification (verification id: null).
> If someone has an easier way to solve instant verification kindly share. Thanks.

Perfectly working, how can i recognise already existing number in firebase users list. which helps not to save to back end database.
