### ISSUE TITLE
🔥 Messaging - #requestPermission & #hasPermission Truthy Results

### ISSUE THREAD

**Issue by Sunakujira1** [invertase/react-native-firebase#3448]
## Issue

Hello,

I'd like to clarify some doubts I have with the v6.4.0 change:

I have recently upgraded to v6.4.0 and noticed the changes made on [`requestPermission` & `hasPermission` to return `AuthorizationStatus` instead of a boolean](https://github.com/invertase/react-native-firebase/commit/d66a6118f82005087f53b86571990fc071402153).

However, the logic seems off to me. On iOS there are 4 enums based on their [documentation](https://developer.apple.com/documentation/usernotifications/unauthorizationstatus):
```
UNAuthorizationStatusAuthorizedNotDetermined = 0
UNAuthorizationStatusDenied = 1
UNAuthorizationStatusAuthorized = 2
UNAuthorizationStatusProvisional = 3
```

The following was previous logic prior to switching to enum:
https://github.com/invertase/react-native-firebase/blob/ea66c683cafe3a19ff84d97231a383afdc99cea7/packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m#L252-L255

Based on the previous logic, it yields the following result:
```
UNAuthorizationStatusAuthorizedNotDetermined -> false
UNAuthorizationStatusDenied -> false
UNAuthorizationStatusAuthorized -> true
UNAuthorizationStatusProvisional -> true
```

And this is the new logic:
https://github.com/invertase/react-native-firebase/blob/d66a6118f82005087f53b86571990fc071402153/packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m#L254-L272

Which will yield different result:
```
UNAuthorizationStatusAuthorizedNotDetermined -> -1 -> truthy
UNAuthorizationStatusDenied -> 0 -> falsy
UNAuthorizationStatusAuthorized -> 1 -> truthy
UNAuthorizationStatusProvisional -> 2 -> truthy
```

Notice the result of `UNAuthorizationStatusAuthorizedNotDetermined` would now be considered truthy since `Boolean(-1) === true`.

I'm not expert at these so I may be going crazy, but the logic seems to be off to me, and if it is off then the current suggestion to keep the result of these APIs as truthy value will be misleading.

Some comment or validation on this would be much appreciated. Thanks!

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 6.4.0
- **`Firebase` module(s) you're using that has the issue:**
  - messaging
- **Are you using `TypeScript`?**
  - `N

</p>
</details>

**Comment by Ehesp** [comment]
Wow that is a pretty silly mistake on our part! Thanks for flagging. 

There's not really much we can do without making a breaking change. I've instead updated the docs to check via the enum export rather than a truthy check.

**Comment by ahuounan** [comment]
The example listed here is still using a truthy check, would be great if it could be updated!

https://rnfirebase.io/messaging/usage#ios---requesting-permissions

**Comment by mikehardy** [comment]
@ahuounan there is an edit button on the top of each page of documentation and github will walk you through making a PR to docs so easily it's painless - can you submit a PR for that piece of documentation?

**Comment by ahuounan** [comment]
Was not aware of that, will do!

**Comment by Jhonte** [comment]
Got this error as well when upgrading from 5.4.0...   I would argue this would/should be changed anyway since not that many read the change logs when upgrading?   For me it worked like it should since I already had a token set when testing and I missed this until everything was out in production.
