### ISSUE TITLE
Support auth().onIdTokenChanged

### ISSUE THREAD

**Issue by ajostergaard** [invertase/react-native-firebase#345]
Any chance of support for _onIdTokenChanged_? Unless I'm mistaken _onAuthStateChanged_ is no longer being called when linking an anonymous account using _linkWithCredential_ so I need _onIdTokenChanged_ to get the updated _user_ object.

**Comment by Salakar** [comment]
Will get this added for v3, thanks for the report!

**Comment by ajostergaard** [comment]
I don't know but it's not obvious to me that linking equates to any of _When a user is signed in_, _When the current user is signed out_ or _When the current user changes_ and the auth state hasn't actually changed (was and is still authorised).

Actually I'm just really hoping that the token changes otherwise I can't see any elegant way to update my state after a successful link.

**Comment by Salakar** [comment]
@ajostergaard you can call `firebase.auth().getCurrentUser(): Promise<User>` after linking, this will grab the user directly from native (and also internally will update `firebase.auth().currentUser` on promise resolve completion.

Try that after linking?

**Comment by ajostergaard** [comment]
@Salakar :) that works for my case - no clue why I didn't think of that (thanks!).

Leaving this open for the parity with Web SDK, also I assume there are some cases where token might change without changing authentication state and we should react appropriately.

**Comment by chrisbianca** [comment]
Added support for `onIdTokenChanged` to the upcoming v3 release.

@Salakar The other methods are detailed on the discrepancies document
