### ISSUE TITLE
Custom notification sounds not working on newer Android versions

### ISSUE THREAD

**Issue by sterjoski** [invertase/react-native-firebase#3451]
## Issue

Custom notification sound doesn't work on newer Android versions. It works fine on older ones so I won't include files that I find irrelevant since the library is setup properly.

I have added a android channel ID in `firebase.json` in trying to replicate this solution https://stackoverflow.com/questions/52929138/no-custom-sound-with-android-firebase-notification .

The backend is sending that `channelId` and it's still not working.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "dependencies": {
        "@react-native-community/async-storage": "^1.8.1",
        "@react-native-community/datetimepicker": "^2.3.1",
        "@react-native-community/masked-view": "^0.1.7",
        "@react-native-firebase/app": "^6.4.0",
        "@react-native-firebase/messaging": "^6.4.0",
        "@react-navigation/bottom-tabs": "^5.2.4",
        "@react-navigation/drawer": "^5.3.4",
        "@react-navigation/native": "^5.1.3",
        "@react-navigation/stack": "^5.2.8",
        "axios": "^0.19.2",
        "base-64": "^0.1.0",
        "dayjs": "^1.8.23",
        "formik": "^2.1.4",
        "humps": "^2.0.1",
        "lodash": "^4.17.15",
        "react": "16.9.0",
        "react-native": "0.61.5",
        "react-native-bootsplash": "^2.1.0",
        "react-native-elements": "^1.2.7",
        "react-native-gesture-handler": "^1.6.1",
        "react-native-keyboard-aware-scroll-view": "^0.9.1",
        "react-native-modal-datetime-picker": "^8.5.2",
        "react-native-picker-select": "^6.6.0",
        "react-native-reanimated": "^1.7.1",
        "react-native-safe-area-context": "^0.7.3",
        "react-native-screens": "^2.4.0",
        "react-native-vector-icons": "^6.6.0",
        "react-use": "^13.27.1",
        "yup": "^0.28.3"
    },
```

#### `firebase.json` for react-native-firebase v6:

```json
{
    "react-native": {
        "messaging_android_notification_channel_id": "high-priority"
    }
}
```

</details>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: Linux 5.3 KDE neon 5.18
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 2.82 GB / 15.39 GB
    Shell: 3.1.0 - /usr/bin/fish
  Binaries:
    Node: 13.5.0 - /tmp/yarn--1586702994514-0.21430758830131702/node
    Yarn: 1.22.4 - /tmp/yarn--1586702994514-0.21430758830131702/yarn
    npm: 6.13.4 - ~/.config/nvm/13.5.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.4.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/messaging`
- **Are you using `TypeScript`?**
  - `Y` & `3.7.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Have you created the channel?

**Comment by sterjoski** [comment]
> Have you created the channel?

@Ehesp all I did was this https://rnfirebase.io/messaging/usage#notification-channel-id

The backend sends the matching `channelId` in the android field along with the `sound`.

Could you point me to what exactly do you mean by that?

**Comment by Ehesp** [comment]
Yeah that assigns a default channel to incoming notifications, however you still need to create a channel and add properties such as sound to it.

This library doesn't create channels as its out of scope, however it just allows you to use them

**Comment by sterjoski** [comment]
@Ehesp was that possible with v5? Can you point me to a way of creating channels (via JS/TS code, since I conditionally want to setSound for only one type of notifications) or should I downgrade?

**Comment by lyseiha** [comment]
how to do it please let me know too i am stuck with it too.

**Comment by Ehesp** [comment]
You cannot create a channel in v6, that functionality is out of scope.

**Comment by Eramirez06** [comment]
I have a issue i'm creating the channel and adding correctly the sound to notification and channel my problem is that notification setting allow sound is desactivated for my app do you have any idea of what can i do to automatic enable that cause if i manually active the notificacion sound nice

**Comment by vishnu-apollo247** [comment]
How can I set different notification sound based on notification type lets say caller type notification of one sound and message type of another sound. Please provide the proper documentation for this.

**Comment by odesey** [comment]
In case anyone stumbles upon this issue trying to configure custom sounds for `Android > API level 26`, it is NOT possible with `react-native-firebase v6`. You have 2 choices:

1 - Use [notifee](https://notifee.app/react-native/docs/android/behaviour) to create your channel and a custom sound with it

2 - Follow [this post](http://www.embusinessproducts.com/how-to-add-a-custom-push-notification-sound-on-ios-and-android-with-react-native-firebase-and-fcm/) here on medium
