### ISSUE TITLE
You've attempted to require '@react-native-firebase/messaging' version '6.3.4', however, the '@react-native-firebase/app' module is of a different version (6.4.0)

### ISSUE THREAD

**Issue by AnasAlsaadi** [invertase/react-native-firebase#3452]
i am trying all thing about **clear cash or build** but not working, and i have tried change all 
**react-native-firebase** modules to **version 6.3.4** , and  **version 6.4.0**

but all solution not working

**Comment by mikehardy** [comment]
Duplicate #3396
