### ISSUE TITLE
Document usage of GithubAuthProvider

### ISSUE THREAD

**Issue by crutchcorn** [invertase/react-native-firebase#3456]
## Documentation Feedback

It seems that the library includes support for using GitHub auth providers:

https://rnfirebase.io/reference/auth#GithubAuthProvider

But there is no documentation for how to use the auth provider like there is for Facebook or Google here:

https://rnfirebase.io/auth/social-auth

**Comment by andersonaddo** [comment]
I remember talking about this on Discord with @mikehardy. Apparently getting Github authentication to work is still pretty finicky. Is that still the case, Mike?

**Comment by Ehesp** [comment]
It's from my understanding GitHub surprisingly don't follow the OAuth standards - there's a long thread on one of the underlying libraries about it where the authors don't want to change their library just to handle GitHub - I'll try and dig it out.

**Comment by mikehardy** [comment]
Yep - that was exactly my understanding. There's some small oauth library patch that would allow it to work around some small deviation from the standard github does but that would start the oauth library down the slippery slope of hacks for every deviation etc so they didn't. But it has been a while, maybe the status is different now
