### ISSUE TITLE
[Question] is it possible to use custom MessagingService with RNFirebase?

### ISSUE THREAD

**Issue by lorenc-tomasz** [invertase/react-native-firebase#3457]
Hi,
as Notifee is closer to stable 1.0.0 I want to prepare myself to migrate from v5 to v6. I just read within migration guide that:
```
[android] The manually added RNFirebaseMessagingService service in your AndroidManifest.xml file is no longer required - you can safely remove it.
```

So my question is - is it possible to use custom MessagingService? As far I know there can be only one `MESSAGING_EVENT` registered. Currently with v5 I use my own custom service that allows me to use RNFirebaseMessagingService  and Mixpanel in the same time. If it's possible it would be great to have information about it within documentation.

**Comment by lorenc-tomasz** [comment]
Can someone answer that question?

**Comment by hqarymkevich** [comment]
Any updates here?

**Comment by LRNZ09** [comment]
I'd also be very interested in this.

**Comment by lorenc-tomasz** [comment]
It's possible. 

1. You need to add this to `app/build.gradle`

```
    // Import the BoM for the Firebase platform
    // keep te same version from RNFirebase lib
    implementation platform('com.google.firebase:firebase-bom:26.6.0')
    // Declare the dependencies for the desired Firebase products without specifying versions
    // because the BoM is declared
    implementation 'com.google.firebase:firebase-core'
    implementation 'com.google.firebase:firebase-messaging'
```

2. You need to write your own provider. (I needed to add mixpanel)  

```
package com.x.y.z;

import android.content.Intent;
import android.util.Log;

import com.google.firebase.messaging.FirebaseMessagingService;
import com.google.firebase.messaging.RemoteMessage;
import com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService;

import io.invertase.firebase.messaging.ReactNativeFirebaseMessagingService;

public class PushProvidersHandler extends FirebaseMessagingService {
    private static final String TAG = "RNFMessagingService";

    private static ReactNativeFirebaseMessagingService reactNativeFirebaseMessagingService = new ReactNativeFirebaseMessagingService();

    @Override
    public void onSendError(String messageId, Exception sendError) {
        reactNativeFirebaseMessagingService.onSendError(messageId, sendError);
    }

    @Override
    public void onDeletedMessages() {
        reactNativeFirebaseMessagingService.onDeletedMessages();
    }

    @Override
    public void onMessageSent(String messageId) {
        reactNativeFirebaseMessagingService.onMessageSent(messageId);
    }

    @Override
    public void onNewToken(String token) {
        // super.onNewToken(token);

        MixpanelFCMMessagingService.addToken(token);
        reactNativeFirebaseMessagingService.onNewToken(token);
    }

    @Override
    public void onMessageReceived(RemoteMessage message) {
        /* CUSTOM DATA
            CHECK README.MD
         }
        */
        // super.onMessageReceived(message);

        // Mixpanel code
        if (message.getNotification() == null && message.getData().containsKey("mp_message")) {
            Intent intent = message.toIntent();
            if (!intent.hasExtra("mp_icnm")) {
                String ANDROID_SMALL_ICON = "pw_notification";
                intent.putExtra("mp_icnm", ANDROID_SMALL_ICON);

                if (!intent.hasExtra("mp_icnm_w")) {
                    intent.putExtra("mp_icnm_w", ANDROID_SMALL_ICON);
                }
                if (!intent.hasExtra("mp_icnm_l")) {
                    String ANDROID_LARGE_ICON = "ic_launcher";
                    intent.putExtra("mp_icnm_l", ANDROID_LARGE_ICON);
                }
            }

            if (!intent.hasExtra("mp_color")) {
                String ANDROID_NOTIFICATION_ACCENT_COLOR = "#0013bc";
                intent.putExtra("mp_color", ANDROID_NOTIFICATION_ACCENT_COLOR
                );
            }
            MixpanelFCMMessagingService.showPushNotification(getApplicationContext(), intent);
        }
        Log.d(TAG, "onMessageReceived event received");
    }
}
```

3. You need to register the new service in Manifest

```
        <service
            android:name=".PushProvidersHandler"
            android:enabled="true"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
 ```

**Comment by LRNZ09** [comment]
@lorenc-tomasz why you don't extend the class from `ReactNativeFirebaseMessagingService` instead?

**Comment by lorenc-tomasz** [comment]
I don't remember why. Extend the class if possible and give us a feedback.

**Comment by lorenc-tomasz** [comment]
Aa, ok. Just checked why. The `onMessageReceived` is protected.

**Comment by lorenc-tomasz** [comment]
This should work as well:

```
package com.purple.interpolis.automodus;

import android.content.Intent;
import android.util.Log;

import com.google.firebase.messaging.RemoteMessage;
import com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService;

import io.invertase.firebase.messaging.ReactNativeFirebaseMessagingService;

public class PushProvidersHandler extends ReactNativeFirebaseMessagingService {
    private static final String TAG = "PushProvidersHandler";

    @Override
    public void onSendError(String messageId, Exception sendError) {
        super.onSendError(messageId, sendError);
    }

    @Override
    public void onDeletedMessages() {
        super.onDeletedMessages();
    }

    @Override
    public void onMessageSent(String messageId) {
        super.onMessageSent(messageId);
    }

    @Override
    public void onNewToken(String token) {
        super.onNewToken(token);

        MixpanelFCMMessagingService.addToken(token);
    }

    @Override
    public void onMessageReceived(RemoteMessage message) {
        super.onMessageReceived(message);

        if (message.getNotification() == null && message.getData().containsKey("mp_message")) {
            Intent intent = message.toIntent();
            if (!intent.hasExtra("mp_icnm")) {
                String ANDROID_SMALL_ICON = "pw_notification";
                intent.putExtra("mp_icnm", ANDROID_SMALL_ICON);

                if (!intent.hasExtra("mp_icnm_w")) {
                    intent.putExtra("mp_icnm_w", ANDROID_SMALL_ICON);
                }
                if (!intent.hasExtra("mp_icnm_l")) {
                    String ANDROID_LARGE_ICON = "ic_launcher";
                    intent.putExtra("mp_icnm_l", ANDROID_LARGE_ICON);
                }
            }

            if (!intent.hasExtra("mp_color")) {
                String ANDROID_NOTIFICATION_ACCENT_COLOR = "#0013bc";
                intent.putExtra("mp_color", ANDROID_NOTIFICATION_ACCENT_COLOR
                );
            }
            MixpanelFCMMessagingService.showPushNotification(getApplicationContext(), intent);
        }
        Log.d(TAG, "onMessageReceived event received");
    }
}
```

**Comment by mikehardy** [comment]
If opening up programmatic access to a method in our native code makes the native code more useful to people, historically we have been okay with opening up access, FYI - just propose a PR for it with an explanation, will likely merge :+1:

**Comment by lorenc-tomasz** [comment]
@mikehardy I don't think it's necessary as all methods from the RNFirebase are public. The "issue" with not extending the `ReactNativeFirebaseMessagingService` class is historically from v5 and the Mixpanel (which has some protected methods). From what I have checked you can do it as I did it with static member, or to extend `ReactNativeFirebaseMessagingService` as in second example. In most cases it all depends on how the custom providers need to be consumed by the messaging service.

**Comment by rgbedin** [comment]
Hey guys. Thanks for this post. I tried a similar approach, but the issue is that once I implement a custom service the callback `onNotificationOpenedApp()` does not get triggered. 

I have created a post [here](https://github.com/invertase/react-native-firebase/discussions/5018) explaining in detail what I am trying to achieve.

I tried updating my custom service to extend  `ReactNativeFirebaseMessagingService`, but still no luck. Any insights?

Cheers!

**Comment by artyorsh** [comment]
@rgbedin the trick is to make 3rd party push notification message providers be compatible with RNFB. We're currently struggling with Braze. They provide a custom MessagingService, and their handling logic differs to what we have in RNFB. Platform-wise, the push click event triggers `onNewIntent` in running activity, so the trick is to somehow (depending on the message provider) get [this code executed](https://github.com/invertase/react-native-firebase/blob/main/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java#L259).

We weren't successful in it with running Braze, because they don't provide `message_id` in the intent payload. Moreover, RNFB does some [tricky things with caching push notifications](https://github.com/invertase/react-native-firebase/blob/main/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingReceiver.java#L33) to be able to retrieve it's content when the user click is deferred (by the time of arrival, app process is not running at all).

@mikehardy I think this is a good topic in general. Currently there is no (easy) way for apps to integrate CRM tools and be compatible with JS APIs from RNFB.

**Comment by mikehardy** [comment]
I'm not sure what's actionable, if you can propose a concrete change to make, anything is possible. We've made brownfield-compatibility changes before and I'm always open to them
