### ISSUE TITLE
annotationProcessors.json error

### ISSUE THREAD

**Issue by wontone18** [invertase/react-native-firebase#3458]
This module having a bug node_modules\@react-native-firebase\messaging\android\build\intermediates\annotation_processor_list\release\annotationProcessors.json (The system cannot find the path specified)

during the compilation of .apk i am getting this error.

**Comment by mikehardy** [comment]
You ignored the issue template, so we can't help

I can say I have seen similar things when build caches have become incoherent, I have learned to use `npx react-native-clean-project` to delete build caches in order to fix them
