### ISSUE TITLE
Automatic merge when existing account with email&password provider on Firebase

### ISSUE THREAD

**Issue by TheJonk** [invertase/react-native-firebase#3462]
Hi! I've been using invertase@react-native-apple-authentication to implement Sign in with Apple combined with firebase authentication.

When I perform this code snippet and choosing "Share my Email" and I already have an existing “email & password-provider” on Firebase with the same email as the one I have on my Apple ID, the providers automatically merge. 

```
const appleAuthRequestResponse = await appleAuth.performRequest({
				requestedOperation: AppleAuthRequestOperation.LOGIN,
				requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
})
const { user, email, nonce, identityToken } = appleAuthRequestResponse
const appleCredential = firebase.auth.AppleAuthProvider.credential(identityToken, nonce)
const userCredential = await firebase.auth().signInWithCredential(appleCredential)
```

If I instead were to use for example Facebook sign in through react-native-fbsdk to sign in with these lines: 

```
const credential = firebase.auth.FacebookAuthProvider.credential(accessToken)
firebase.auth().signInWithCredential(credential)
```

the auth module correctly throws an error ‘auth/account-exists-with-different-credentials’ since it detects that an account already occupies the email-address on firebase.

The issue is that I cannot stop the merge from happening during the sign in flow, unless I manually prevent it by looking up the authenticated Apple email's firebase login providers in-between the request and the sign-in. 

I’d wish to be able to handle an error such as auth/account-exists-with-different-credentials even when signing in with Apple, but unfortunately nothing gets thrown.

Is this behaviour intended?

Edit: 
react-native-firebase version 5.6.0
Firebase/Auth version 6.15.0

Kind Regards, Jonathan

**Comment by mikehardy** [comment]
Hey @TheJonk - this is actually mostly the same crew of maintainers as the apple auth authenication repo - https://github.com/invertase/react-native-apple-authentication/issues/64 - when I suggested firebase contact I meant the truly official folks behind this: https://github.com/firebase/firebase-ios-sdk - they will have authoritative answers, we just use their APIs :-)

**Comment by TheJonk** [comment]
> Hey @TheJonk - this is actually mostly the same crew of maintainers as the apple auth authenication repo - [invertase/react-native-apple-authentication#64](https://github.com/invertase/react-native-apple-authentication/issues/64) - when I suggested firebase contact I meant the truly official folks behind this: https://github.com/firebase/firebase-ios-sdk - they will have authoritative answers, we just use their APIs :-)

My bad! Will look into it :)
