### ISSUE TITLE
Unable to integrate FirebaseCrashlytics in Android

### ISSUE THREAD

**Issue by Dattakunde** [invertase/react-native-firebase#3465]
**React native configuration**
      "react": "16.8.6"
       "react-native": "0.60.4"
       "react-native-firebase": "^5.6.0"

**Android build configuration**
project build.gradle dependencies 
           classpath 'com.google.firebase:firebase-crashlytics-gradle:2.0.0-beta04'

app build.gradle dependencies
           implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'
           implementation 'com.google.firebase:firebase-crashlytics:17.0.0-beta04'

setting.gradle:
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')

<img width="330" alt="2020-04-14_1839" src="https://user-images.githubusercontent.com/3377941/79228928-db18bf80-7e7f-11ea-9ed5-1fb7468e0476.png">

I have followed steps from firebase official document
https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android#fabric_sdk_2
 
@mikehardy

**Comment by mikehardy** [comment]
Don't use that crashlytics, this module hasn't moved to it
Use the other crashlytics, like so: 

https://github.com/mikehardy/rnfbdemo/blob/7d77f103d00b4c5a2288d3cefeb4b773a9e5531e/make-demo.sh#L60-L73

**Comment by Nehal-29** [comment]
Hey @mikehardy 
I want to use the latest version of react-native-firebase (5.6.0v )in my project. I can successfully run it on ios but I'm getting error on Android 

"java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/platforminfo/LibraryVersionComponent; "

**Comment by mikehardy** [comment]
@Nehal-29 That's not the latest version. v6.4.0 is the latest version

Either way, if you still want to use v5 in your project, it integrates and works still, follow this script and run it to generate a sample project. Whatever local project problem causing your error message can be found in the difference between the two; https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by Nehal-29** [comment]
<img width="1262" alt="Screenshot 2020-04-15 at 7 01 39 PM" src="https://user-images.githubusercontent.com/41570871/79343112-9fe3c280-7f4b-11ea-85fe-12c4960ce56f.png">

Are you sure ? @mikehardy 

I'd installed the package by npm i --save react-native-firebase@latest

I'd tried following your script also but it gives the same error

**Comment by mikehardy** [comment]
I am sure. Head to the link they mention IN BRIGHT RED

The package name changed so your npmjs screen capture is irrelevant, you must read documentation closely. 

My script runs perfectly, please post an issue in that repo if not.

**Comment by Nehal-29** [comment]
ohh Thanks. I missed it.
Just a quick question:
new FirebaseCrashlytics is not integrated in this package yet but firebase is going to stop the support for Fabric from May 1,2020. How are we going to manage crashlytics data then ?
@mikehardy

**Comment by mikehardy** [comment]
@Nehal-29 3 levels of crashlytics if I understand. 

1. Fabric (old, sunsetted, from before the firebase acquisition), 
1. existing firebase crashlytics (what this module has integrated), 
1. "new crashlytics" which if I understand correctly is still in beta https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/CHANGELOG.md

I am sure PRs to forward-port to the new SDK would be welcome, but I believe what the module is currently integrated with is the correct stance at the moment and will be valid past May 1 2020, vs switching to beta software right now, for something as important as crash reporting.

I think this is backed up by a careful read of the related documentation as well

**Comment by infinitbility** [comment]
Learn to integrate react native firebase crashlytics in android. 

https://infinitbility.com/implement-react-native-firebase-crashlytics-on-android
