### ISSUE TITLE
V6. How to handle displaying notifications in foreground?

### ISSUE THREAD

**Issue by Gusakovskyi** [invertase/react-native-firebase#3468]
in v5 i used this function to display or not push notifications.
(e.g. in chat screen i don't need chat related notifications, but they are useful in other screens)

```
const displayNotification = (input: Notification) => {
    const notification = new firebase.notifications.Notification()
      .setNotificationId(input.notificationId)
      .setTitle(input.title)
      .setSound('default')
      .setBody(input.body)
      .setData(input.data);
    firebase.notifications().displayNotification(notification);
  };
```

Does V6 has similar functionality?

**Comment by mikehardy** [comment]
V6 does not implement local/device notification APIs -> https://github.com/invertase/react-native-firebase/issues/2566
