### ISSUE TITLE
fetchTimeoutMillis - in unavaliable to consume with the SDK

### ISSUE THREAD

**Issue by sahanatroam** [invertase/react-native-firebase#3473]
Hi @Salakar @Ehesp 

According to the Remote config documentation there is a variable you could set `fetchTimeoutMillis` which would set a timeout if the remote config fetch takes longer than expected.

https://firebase.google.com/docs/reference/js/firebase.remoteconfig.Settings

But this options [doesn't seem to be available in the SDK](https://github.com/invertase/react-native-firebase/search?q=fetchTimeoutMillis&unscoped_q=fetchTimeoutMillis) for us to consume. Could you advice if this is a type related issue or if it's not supported by the SDK for a reason ?

Thank you.

**Comment by russellwheatley** [comment]
Hi @sahanatroam, we plan to release this API support for `remote-config` as part of v7. Although the release date of v7 is to be confirmed.

**Comment by CyxouD** [comment]
It is available now as `fetchTimeMillis` when call`remoteConfig().setConfigSettings` in case someone didn't find

**Comment by mikehardy** [comment]
@jeafgilbert thanks for noticing that! #6102 should correct the example once merged
