### ISSUE TITLE
No manual linking described for Android

### ISSUE THREAD

**Issue by tomekzawada** [invertase/react-native-firebase#3474]
## Documentation Feedback

Auto-linking didn't work for me on Android and cannot find up-to-date info in the docs.
The main installation page (https://rnfirebase.io/) mentions additional steps for ios and android manual linking, but...

https://rnfirebase.io/v6/app/android is a dead link. 

Not sure about legacy docs for 5.x being 100% useful...

There was an issue open (https://github.com/invertase/react-native-firebase/issues/2055) but it has been closed without solution.

**Comment by mikehardy** [comment]
On Android auto-linking works. It really does. It just works. If it does not, there is something wrong with your project, and *usually* it is because during an upgrade the auto-linking things weren't added - they're easy to miss

All I can say is that if you take a fresh project, and you integrate RNFBv6 into it, it definitely works - you can clone this repo and generate a quick throwaway project to verify https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

if you can post a new issue that's a bug report and include the gradle files that might explain why autolinking isn't working?

**Comment by tomekzawada** [comment]
Unfortunately, our project does not support autolinking for anything else
than expo modules, and it would not change anytime soon.
I did try a fresh project with some hiccups ass well.
I can see, however, that the docs are no longer dead...

**Comment by mikehardy** [comment]
Expo problems will have to go to expo. Auto-linking really should work, it is one of the crowning achievements of react-native development in the last year. Probably the crowning achievement!

I'd be curious what hiccups you saw, as my script above does a fresh project fully automated, no hiccups, and any hiccups I find I PR back to the main repo so it's smooth.

If expo gets in the way of something of course, can't change that but that's the downside to expo (interaction outside their ecosystem)

**Comment by ckalika** [comment]
I'm running RN 0.62.2 & RNFB 6.4.0.

Not sure if it's relevant to this particular discussion, but thought I'd mention it, just in case.

The build was fine in iOS, but on Android, gradle kept complaining with the following error:

```
* What went wrong:
A problem occurred evaluating project ':react-native-firebase_app'.
> Android tasks have already been created.
  This happens when calling android.applicationVariants,
  android.libraryVariants or android.testVariants.
  Once these methods are called, it is not possible to
  continue configuring the model.
```

The solution was to add the following to the `node_modules/@react-native-firebase/app/android/build.gradle`:

```
...
plugins {
  id "io.invertase.gradle.build" version "1.4"
}

**apply plugin: 'com.android.library'** // <!-- Apply this plugin.
...
```

@mikehardy... Any chance this is occurring on a fresh project, pulling from NPM? If so, can up update the package and republish?

Thanks a lot.

**Comment by mikehardy** [comment]
No

> All I can say is that if you take a fresh project, and you integrate RNFBv6 into it, it definitely works - you can clone this repo and generate a quick throwaway project to verify [mikehardy/rnfbdemo:make-demo-v6.sh@`master`](https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh) [](/mikehardy/rnfbdemo/blob/HEAD@{2020-04-15T03:44:39Z}/make-demo-v6.sh)

Have you run that? it works

**Comment by ckalika** [comment]
@mikehardy I have not, no, as I was trying to integrate it into an existing project. I'll say though... I rather love the script. :)

Thanks for the reply. I've got my stuff working, so I'm a happy camper. Just thought I'd ask/check.

**Comment by ckalika** [comment]
And for anyone who finds this, in future... I also had to apply the plugin to firebase-json.gradle when I wanted to go do './gradlew clean'

**Comment by russellwheatley** [comment]
I'm going to close this issue as I don't see this as being a problem with React Native Firebase.
