### ISSUE TITLE
In version 5.6.0, firebase.messaging().getToken() not providing the valid and latest messaging token in iOS version 13.3.

### ISSUE THREAD

**Issue by vtn-dev-sameer** [invertase/react-native-firebase#3477]
Hi, 
While implementing the react-native firebase version 5.6.0. I have found that the token is provided by “firebase.messaging().getToken()” method is not valid for push notification messages in iOS version 13 and above. But the token is valid for the iOS version 12 or less.

Internally while checking the log in Xcode, I have found that the token is generated twice under

-[RNFirebaseMessaging messaging:didReceiveRegistrationToken:] [Line 86] Received new FCM token: 

My project setup: 

package.json

"react-native-firebase": "^5.6.0",
    "react": "16.13.1",
    "react-native": "^0.61.5",

podfile

pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/DynamicLinks'
pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
pod 'RNFirebase/Crashlytics', :path => '../node_modules/react-native-firebase/ios'

React native:

firebase.messaging().getToken();

iOS console

-[RNFirebaseMessaging messaging:didReceiveRegistrationToken:] [Line 86] Received new FCM token: e2k68qXc0kXqljYgp5tMCi:APA91bE2_jUZR0wk8Y9CQUBf5wI1REK1ZsrcCczPq7YWy261-UwwRhi-eivBmqXqck4RcTdQu_7PZLhsatJ0GEMtENvcReyj8ce-Qyp5GLE2MXag1h_65BgP-d4DowooTDjMdNS1eQ4P

Thanks

**Comment by mikehardy** [comment]
Hi there! Unfortunately I don't believe react-native v5 will be receiving any bugfixes unless you provide them yourself. I suggest upgrading to v6 and re-testing to see if this happens. Important to note that at this point you should try the `@next` tag on v6 as messaging just saw a massive pile of fixes in #3339 

I will say that no one else has reported this yet though, so I do suspect this is either a local project problem or if you were careful with waits and listeners you could get the updated token, or I suspect more would have reported it?

Feel free to propose a PR for v5 if  you figure it out and I can try to do a release, and you communication can happen here, but it won't be officially supported so I'm going to close this

**Comment by krupalikevadiya** [comment]
I'm facing same issue in version 5.6.0 of react-native-firebase.Please suggest some way.

**Comment by mikehardy** [comment]
@krupalikevadiya v5 is far out of support now. "some way" is "upgrade to current stable versions, post a new issue if you reproduce"
