### ISSUE TITLE
The library dos not supported for new Crashlytics . we can not use Fabric anymore.

### ISSUE THREAD

**Issue by RNTop** [invertase/react-native-firebase#3482]

**Comment by mikehardy** [comment]
Is there a stable version of the new Crashlytics? Please point to the release you see, I only see betas
Do you have a date for when the current APIs we use will be sunsetted, you could propose a PR to the docs with that information perhaps?
Do you have a PR you would propose to move to the new APIs?

**Comment by Aure77** [comment]
This is the migration guide to the new SDK (aka Firebase Crashlytics SDK) :

https://firebase.google.com/docs/crashlytics/upgrade-sdk

**Comment by RNTop** [comment]
Thanks. I will check

**Comment by RNTop** [comment]
Is it working to react-native? even I can not install new SDK as a pod
command. Is there any other options to do?.

**Comment by Aure77** [comment]
You can use it manually (configure in native side). But if you wan't to use react-native-firebase, this lib need an update (I trying to work on it in a fork).

**Comment by RNTop** [comment]
Which is better in react-native-firebase and @react-native-firebase/app ?

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/29/20,
10:05:03 AM

**Comment by mikehardy** [comment]
> Which is better in react-native-firebase and @react-native-firebase/app ? [image: Mailtrack] 

This question makes no sense I think - 'react-native-firebase' as a package means version 5, which is out of support and no development should go to it. '@react-native-firebase/app' is v6, but work in v6 related to crashlytics would be '@react-native-firebase/crashlytics'

**Comment by RNTop** [comment]
`pod Crashlytics`  this is working for you ? and did not use Fabric at all ?

**Comment by russellwheatley** [comment]
I'm not entirely sure what this issue is tracking, but I know we're trying to resolve the merge conflicts for this PR #3580 which is an upgrade to the latest Crashlytics that @Aure77 has kindly submitted. I suggest tracking that PR as I'll be closing this issue. Thanks.
