### ISSUE TITLE
[Messaging][Question] Scheduled notifications in Recipient time zone

### ISSUE THREAD

**Issue by beetlebum** [invertase/react-native-firebase#3486]
I have managed to set up an iOS project where push notifications from Firebase are received properly when sent from a Firebase Function or scheduled at a given time.

However, when I schedule a notification using the Recipient time zone setting, they don't work.
I've contacted Firebase and they have come back to me saying these are sent silently to the device up to 26h in advance and should be scheduled as local notifications by the SDK.

I haven't found any mention of this either in previous issues or in the documentation of this project, so my question is:

- Are scheduled notifications with recipient time zone supported out of the box by react-native-firebase?

A few reasons as to why it might not work mentioned by the Firebase support team:
```
- There is logic to clear local notifications in the app, e.g. UIApplication.clearAllLocalNotifications()
- Background Modes > Remote Notifications is not enabled in Xcode's target's Capabilities
- Method swizzling is disabled and [[FIRMessaging messaging] appDidReceiveMessage:userInfo] isn't implemented in the notification handlers
- The app is not running in foreground or background (e.g. user killed the app manually) when the scheduled message arrives to the device.
```

Thanks in advance.

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment]
Seems related https://github.com/FirebaseExtended/flutterfire/issues/1509
