### ISSUE TITLE
signInWithCustomToken not returning any value

### ISSUE THREAD

**Issue by agrass** [invertase/react-native-firebase#3487]
I'm working with react-native-firebase 5.5.7 and react-native 59 and suddenly the signInWithCustomToken stop returning the callback without any error. Could be a change of Google API? Anyone know what I can do to fix this? 

Best

**Comment by mikehardy** [comment]
Hi there - no template, and those versions are all old enough they are almost not supportable
I do my best to support v5.6.0 but I don't think you can successfully follow iOS version support guidelines without being at least on RN0.60 at this point. Either way, no template, no support at all
