### ISSUE TITLE
Support auth().signInWithPopup

### ISSUE THREAD

**Issue by ajostergaard** [invertase/react-native-firebase#349]
This seems to be by far the easiest way to auth using providers without native SDKs (e.g. Twitter) so can this be supported? Or is there a better alternative?

http://www.androdevelopment.com/tag/how-to-use-firebase-twitter-authentication-with-react-native/

**Comment by Ehesp** [comment]
Hi @ajostergaard, thanks for the suggestion. Right now this isn't on our roadmap as if we were to do this, we'd want the integration to be native (I think). Unfortunalty this means integrating more native libraries (Google, Facebook, Twitter SDKs etc) which isn't something we want to bring into this library.

We have had discussions around this, and I do think the best route would be providing a separate module, or a UI based module to handle the entire flow for users. Right now though, we're focussed on getting RNFirebase working really well. For now I'd suggest react-native-oauth and passing the credentials returned back to this library.

I'll close for now and we can revist when v3 is stable.
