### ISSUE TITLE
Xcode build Failed 

### ISSUE THREAD

**Issue by guoliang1206** [invertase/react-native-firebase#350]
I have follow the guide and install the Firebase  SDK and react-native-firebase , it appears error when I have build my project with Xcode.
I have test run `react-native link` and `unlink` it both.
this is the error in Xcode
![2017-08-22 4 27 29](https://user-images.githubusercontent.com/12846676/29556143-7e6413ce-8757-11e7-8ce3-f4907a2108b9.png)
this is my podfile
![2017-08-22 4 29 33](https://user-images.githubusercontent.com/12846676/29556164-8c8506a2-8757-11e7-94ee-20ec54355e4d.png)

 

### Environment

1. Target Platform :iOS
2. Development Operating System : macOS Sierra
3. Build tools :Xcode 8.3.3 
4. React Native version :0.47.1
5. RNFirebase Version :2.1.2

**Comment by chrisbianca** [comment]
@guoliang1206 Can you send the contents of your Podfile.lock?  My assumption is that you're on an older version of Firebase, not the latest 4.X version.

**Comment by guoliang1206** [comment]
PODS:
  - Firebase/Analytics (3.17.0):
    - Firebase/Core
  - Firebase/Core (3.17.0):
    - FirebaseAnalytics (= 3.9.0)
    - FirebaseCore (= 3.6.0)
  - Firebase/Messaging (3.17.0):
    - Firebase/Core
    - FirebaseMessaging (= 1.2.3)
  - FirebaseAnalytics (3.9.0):
    - FirebaseCore (~> 3.6)
    - FirebaseInstanceID (~> 1.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseCore (3.6.0):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseInstanceID (1.0.10):
    - FirebaseCore (~> 3.6)
  - FirebaseMessaging (1.2.3):
    - FirebaseAnalytics (~> 3.8)
    - FirebaseInstanceID (~> 1.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - Protobuf (~> 3.1)
  - GoogleToolboxForMac/Defines (2.1.1)
  - GoogleToolboxForMac/Logger (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - GoogleToolboxForMac/NSData+zlib (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - Protobuf (3.3.0)
  - React (0.47.1):
    - React/Core (= 0.47.1)
  - React/BatchedBridge (0.47.1):
    - React/Core
    - React/cxxreact_legacy
  - React/Core (0.47.1):
    - Yoga (= 0.47.1.React)
  - React/cxxreact_legacy (0.47.1):
    - React/jschelpers_legacy
  - React/jschelpers_legacy (0.47.1)
  - RNFirebase (2.1.2):
    - React
  - Yoga (0.47.1.React)

DEPENDENCIES:
  - Firebase/Analytics
  - Firebase/Core
  - Firebase/Messaging
  - React/BatchedBridge (from `../node_modules/react-native`)
  - React/Core (from `../node_modules/react-native`)
  - RNFirebase (from `../node_modules/react-native-firebase`)
  - Yoga (from `../node_modules/react-native/ReactCommon/yoga`)

EXTERNAL SOURCES:
  React:
    :path: ../node_modules/react-native
  RNFirebase:
    :path: ../node_modules/react-native-firebase
  Yoga:
    :path: ../node_modules/react-native/ReactCommon/yoga

SPEC CHECKSUMS:
  Firebase: 4b66b5b59c43edac745b87f0c87e42cdd0279c13
  FirebaseAnalytics: e5fe8486efc01bec33f6bf82e2fa9fce4b124052
  FirebaseCore: 9691ee2ade70c098d7cf92440f4303f16d83ca75
  FirebaseInstanceID: b9eedd6846fb5e1f0f7279e1deaa7a7e4cf8392e
  FirebaseMessaging: 753d05a925e9eb8eadd09a0ffc9b808578b72fac
  GoogleToolboxForMac: 8e329f1b599f2512c6b10676d45736bcc2cbbeb0
  Protobuf: d582fecf68201eac3d79ed61369ef45734394b9c
  React: f705239a901cb3f95445c34468e5b37b6f80a0d4
  RNFirebase: f796cb5ff9c09f72f181f72a8b9fd972fccc9c49
  Yoga: 13a12502dfabb4c75b914071dcb542af800deed4

PODFILE CHECKSUM: f3902942965467ae3434ad65ebc9ebf98129c227

COCOAPODS: 1.2.0

**Comment by chrisbianca** [comment]
Yep, you're on the old version of Firebase.  Try running the following:

1) `pod outdated` - this should list Firebase 4.0.X as available
2) `pod update` - will update all outdated dependencies

If this doesn't work, you might need to bump the minimum supported version of iOS to 9.0 in your Podfile, then repeat the above.

**Comment by guoliang1206** [comment]
@chrisbianca  hi, I find the version of messaging is 3.17.0 , so you mean that I need specify the version manually?  I thought it will be install the latest version auto. I will try

**Comment by chrisbianca** [comment]
Try the commands I listed above, otherwise, in your Podfile, change this line:

`platform :ios, '8.0'`
to
`platform :ios, '9.0'` 

and retry the `pod update` command.

**Comment by guoliang1206** [comment]
@chrisbianca thank you ,  it works.

**Comment by guoliang1206** [comment]
@chrisbianca 
Hi, I faced another issue, I can run my project with the simulator, and it will log "remote notification not support simulator", all thing is right.
Then I run the project on the device, build success, but it shows "No bundle URL present", And I check my network, close the shadowsocks and re-run, it still happened . I think it is cannot find the bundle fie, Is it caused by cocoapods? I check my podfile with the example of this lib, it is not has different place.

**Comment by chrisbianca** [comment]
@guoliang1206 This sounds like your device isn't on the same network as the machine running the packager

**Comment by guoliang1206** [comment]
@chrisbianca  I had create a new project and test , All things was ok. Thank you for your help!
