### ISSUE TITLE
[jest] How to test the onMessage?

### ISSUE THREAD

**Issue by prescindivel** [invertase/react-native-firebase#3505]
## Documentation Feedback

How can I test the `messaging().onMessage` method?

I tried to issue the `SharedEventEmitter.emit ('messaging_message_received')` event but was unsuccessful.

Any workaround?

**Comment by rafaelcavalcante** [comment]
I'm having the same problem

**Comment by Salakar** [comment]
@dackers86 perhaps you can add a Jest test for this on messaging and then @rafaelcavalcante & @prescindivel can use that as an example?

**Comment by prescindivel** [comment]
I need to test the code inside `onMessage`, for example:

```
const unsubscribe = messaging().onMessage(response => {
  // this code needs to be tested
}) 
```

**Comment by dackers86** [comment]
@prescindivel  @rafaelcavalcante 

We are currently investigating this issue, please isssue https://github.com/invertase/react-native-firebase/issues/3817#issuecomment-651779925

**Comment by rafaelcavalcante** [comment]
Hey @dackers86! 

Me and @prescindivel are using this mock:

```
jest.mock('@react-native-firebase/messaging', () => () => {
  return {
    onMessage: jest.fn(() => jest.fn())
  }
})
```

**Comment by dackers86** [comment]
Thanks @prescindivel. 

That would work, an example with the above PR demonstrates creating a custom implementation for sending and receiving messages.

Feel free to add to that PR if you encounter any further issues!

**Comment by Nagibaba** [comment]
Just decuple your code:
useMessage.ts
```
const useMessage = () =>{
    const onMessage = async (remoteMessage: FirebaseMessagingTypes.RemoteMessage) => {
        // your handler
    }
    useEffect(()=>{
        const unsubscribe = messaging().onMessage(onMessage);
        return unsubscribe;
    }
    ,[])

    return {onMessage}
}
```

Now you can test the `onMessage`
```
it('trigger onMessage()', () => {
    const { result } = renderHook(() => useMessage());
    act(() => result.current.onMessage(notificatin));
});
```
