### ISSUE TITLE
Firebase.json with product flavours.

### ISSUE THREAD

**Issue by Acetyld** [invertase/react-native-firebase#3507]
Hello,

We are using product flavors for whitelabeling.
How do we use mulitple firebase.json for admob?
Because we can only specify:
`    "admob_android_app_id": "ca-app-pub-xxxxxxxx~xxxxxxxx",
    "admob_ios_app_id": "ca-app-pub-xxxxxxxx~xxxxxxxx"
 `
And we have atm 3 different flavours with each their own android/ios firebase.

We would love to hear! Maybe its possible to set it when intializing admob?

**Comment by Ehesp** [comment]
Hmm, not possible right now. Quickest solution would be to make a quick script which is run before build. The script could read and parse the file, change the JSON values to whatever you need for that build and write the file again.

**Comment by Acetyld** [comment]
Hey! Is is possible to place the id's inside the AndroidManifest.xml, like this: https://developers.google.com/admob/android/quick-start
`<manifest>
    <application>
        
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
    </application>
</manifest>
`

Would love to hear!

**Comment by Acetyld** [comment]
> 
> 
> Hmm, not possible right now. Quickest solution would be to make a quick script which is run before build. The script could read and parse the file, change the JSON values to whatever you need for that build and write the file again.

ATM we got it inside the androidmanifest and the info.plist on GADApplicationIdentifier, (https://developers.google.com/admob/ios/quick-start)  and we are getting ads.

So this could work right?

**Comment by medonagy45** [comment]
Is there any solution as I am facing the same problem ??

**Comment by Acetyld** [comment]
> Is there any solution as I am facing the same problem ??

Yes see my reaction earlier, this is what we use right now. It overrides the firebase.json
And for iOS same thing see:
https://developers.google.com/admob/ios/quick-start

**Comment by medonagy45** [comment]
It worked for me to show the ads right , but I think the ads for the two flavors got recorded on Admob for the one mentioned in firebase.json
