### ISSUE TITLE
Could we get an "FAQ and Tips" section added to the docs please?

### ISSUE THREAD

**Issue by andersonaddo** [invertase/react-native-firebase#3508]
_Inspired by #3504_ 

Since I started my Firebase side project app, I've been monitoring the GitHub and Discord of this package so that I can keep up to date with new issues that may affect my projects and others.
I've noticed that some good practices and advice get shared slowly over time inside issue threads and over Discord.
I'm sure that the problems that these tips and tricks solve are actually bothering lots of devs.
Long story short I think there should be `FAQ and tips` section added to the docs website. That way when people have discussions on Github or on Discord that future people can definitely benefit from, the discussion could be linked to there (or in the case of Discord, the problem and solution could be mentioned there) by anyone in this community.

**Why don't people just search the Github issues themselves?**
Yes, that's true, people should definitely do that when they face a problem. And this also isn't meant to be an addition that gives people the false sense of security that routinely looking through the issues of this repo would no longer be necessary or advisable.
However, if the FAQs are the first place that people go when facing a problem that a bunch of others have faced in the past, it saves time. It also gives new people taking up this package a better idea of problems that may face in the future so that they can begin to think about them earlier.
Also, of course, we also have a Discord where valuable discussions are had and its a lot more tedious to traverse the timeline of a discord server.

**Comment by mikehardy** [comment]
Might be best as a wiki really, we do that for AnkiDroid (https://github.com/ankidroid/Anki-Android/wiki/) and it has worked out pretty well. We have an official manual, and the wiki is just for the kind of thing you're thinking about so it's a bit more wild west but has been effective without costing much (if any?) maintainer time really other than that which helps the maintainers themselves

**Comment by russellwheatley** [comment]
@mikehardy I had no idea you were a maintainer for Anki-Android, @mikehardy. I've incorporated Anki flashcards into my learning process a couple of months ago 😄

**Comment by Salakar** [comment]
Should be doable through a PR if anyone would like to start one;

Can just add a markdown file in the root of the docs/ folder, e.g. `faqs.md` and add a link to it on the sidebar by modifying: https://github.com/invertase/react-native-firebase/blob/master/docs/sidebar.yaml

**Comment by Ehesp** [comment]
> Off topic; @Ehesp - now that we're on GitHub actions could we setup deploy previews perhaps on netlify - I can easily ping an endpoint on PRs that touch /docs/**

Just checking if that's possible, since the website repo & docs are located in different repos:

![image](https://user-images.githubusercontent.com/842078/79990692-42022e00-84a9-11ea-9523-f6ee5fdd7ae5.png)


You can do this, but I'm not sure whether that creates a staging preview build or not.

**Comment by mikehardy** [comment]
@russellwheatley 

> @mikehardy I had no idea you were a maintainer for Anki-Android, @mikehardy. I've incorporated Anki flashcards into my learning process a couple of months ago 😄

Yeah one of the reasons I have been so quiet here is that I just took over maintainership there a couple months ago and there was a monster pile of unmerged PRs. Been merging about 4 PRs a day with a test version released every other day. Super hectic. You'll love Anki though! Build the daily habit and in a year you can reliably memorize like 50 new things a day, day after day after day. Crazy but awesome.

It will settle down shortly though then I'll be back to react-native land :). Honestly after touching java so much I really miss typescript.

**Comment by russellwheatley** [comment]
@mikehardy Yeah, I'm trying to do half an hour each day of answering questions. I really like it so far, looking forward to reaping the benefits in the future! :)

**Comment by andersonaddo** [comment]
@Salakar I'm all for submitting a PR for this, but just for clarity: y'all would rather this be a page on the docs and not a wiki (as per @mikehardy's suggestion)? I'm fine with either.

**Comment by Salakar** [comment]
Lets going with docs, thans
