### ISSUE TITLE
 Showing Recent Messages Argument list too long: recursive header expansion failed at /Users/dev/test_F/node_modules/react-native-firebase/ios/../../../ios/Pods/React/node_modules/yeoman-generator/lib/test.

### ISSUE THREAD

**Issue by MatthieuPeyrot** [invertase/react-native-firebase#351]
hi i'm using the lastest version of reactNative react-native-firebase last version of all pods, and i have that issue when i'm trying to build the app.

<img width="764" alt="screen shot 2017-08-22 at 12 38 19" src="https://user-images.githubusercontent.com/22000269/29561731-e0d7c4cc-8736-11e7-8d10-b32522ceea13.png">

1. Target Platform iOS
2. Development Operating System macOS Sierra
3. Build tools (Xcode
4. React Native version ( 0.47.2):
5. RNFirebase Version (e.g. v2.1.3):

**Comment by Ehesp** [comment]
Your headers will be mangled in your project. Open XCode up, go to build settings and check your headers list. I guess it's doing a circular path.

**Comment by MatthieuPeyrot** [comment]
i don't find headers list or circular path in build settings

**Comment by Ehesp** [comment]
Can you show us the settings?

**Comment by MatthieuPeyrot** [comment]
i push an example here 
https://github.com/MatthieuPeyrot/test_F

**Comment by MatthieuPeyrot** [comment]
It's ok i find the probleme it's building and it's because i have import the library in xcode and add it in the build phase after that it was because of [FIRApp configure]; . at the end of you documentation Configure is with an uppercase. so it can't find it.

But now i have an other issue  it's unable to resovle module  'ReactNativeART'
