### ISSUE TITLE
[analytics] ECOMMERCE_PURCHASE is now deprecated

### ISSUE THREAD

**Issue by Ehesp** [invertase/react-native-firebase#3512]
See https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event#public-static-final-string-ecommerce_purchase

API needs changing to support `logPurchase` and deprecate the old API.

https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event#PURCHASE

**Comment by russellwheatley** [comment]
This is already a PR with a lot more analytics changes #3385. I don't think it can be merged in until we have the ability to publish each package with major versions in place as it's an API change. Could be wrong though.

**Comment by russellwheatley** [comment]
I'll update the PR to indicate the methods not used are deprecated.

**Comment by agarwalnitesh** [comment]
@russellwheatley  Can you please suggest what we have to do as a quick-fix to setUp e-commerce GA events.

My current version:
react-native: "0.61.3"
react-native-firebase: "5.6.0",
