### ISSUE TITLE
Firebase binding to service failed

### ISSUE THREAD

**Issue by Acetyld** [invertase/react-native-firebase#3515]
`2020-04-22 15:49:31.875 11402-11402/? E/FirebaseInstanceId: binding to the service failed`

The error in the title keeps popping up on android.
- I tried with physical/emulator and with debug/release and virsa virsa, everytime i reinstalled the app.
- I Tried fabric and after that analytics sdk

Files:
![afbeelding](https://user-images.githubusercontent.com/55088242/79990292-2bf86b80-84b1-11ea-8ccf-84aa1ffd0481.png)

apply plugin: 'com.google.gms.google-services' is al the way at top (tried also at the bottom)

![afbeelding](https://user-images.githubusercontent.com/55088242/79990321-3450a680-84b1-11ea-9012-d123c0a2fcc7.png)

google-services json is in avaiable. (we use whitelabling and it get recognized) 
We installed react-native firebase.

We cant figure it out

**Comment by Ehesp** [comment]
Please follow the issue template. Images are also no good because we can't search them or pluck information out easily.
