### ISSUE TITLE
Where are the change logs after 6.4.0?

### ISSUE THREAD

**Issue by andersonaddo** [invertase/react-native-firebase#3518]
Hello again! It's me with another documentation thread :P

I just realized that the package had been upgraded to 6.7.x, but the [change logs ](https://rnfirebase.io/releases) stop after 6.4.0. Were the updates after that minor enough not to justify change logs, or is there another reason?

Or maybe it slipped your minds?

**Comment by mikehardy** [comment]
The releases are I think artifacts of an infrastructure change from a TeamCity CI system to GitHub actions at the same time they are going to independent versioning of the monorepo packages and switching to auto-release. We may be at 6.42.0 before there is another release worth documenting :-), hold tight

**Comment by Salakar** [comment]
Releases page has these now since last week - forgot to close this issue 😅 

https://rnfirebase.io/releases
