### ISSUE TITLE
How to include firebase-core and play-services-base for other Libraries

### ISSUE THREAD

**Issue by manjeets12** [invertase/react-native-firebase#3519]
## Description
Docs says that - Next remove the firebase-core and play-services-base dependencies. Note, other modules you are using may required play-services-base to be installed.
I am using some other modules that depends on **firebase-core** and **play-services-base**, after moving to v6 and opting for auto-linking I doesn't find a way to include those for my other module and exclude for react-native-firebase.
please mention a way (if any) to tackle this issue

---

**Comment by mikehardy** [comment]
It sounds like the other non-react-native-firebase modules don't have their dependencies set up correctly to handle this new + looser dependency. 
You should take it up with those modules and have them add the transitive dependency in their module dependencies (that is, the build.gradle or podspec of the modules that require them)

**Comment by manjeets12** [comment]
@mikehardy is there any docs regarding, I am up for raising PR in those particular modules

**Comment by mikehardy** [comment]
Core is already included if you include @react-native-firebase/app but for other modules they should do like so https://github.com/invertase/react-native-firebase/blob/master/packages/app/RNFBApp.podspec#L31 / https://github.com/invertase/react-native-firebase/blob/master/packages/app/android/build.gradle#L67
