### ISSUE TITLE
 Error installing firebase-react

### ISSUE THREAD

**Issue by AlexsanderManzoli** [invertase/react-native-firebase#352]
When trying to intslar the reac firebase always occurs this same error, I tried to download the demo of the project and even still persists someone has already solved, or even install this new version?

Note: I'm starting now in this dependence I tried to use it more nor can I install.

![image](https://user-images.githubusercontent.com/14675621/29598492-9442523a-879f-11e7-91e3-cbec7ee82b76.png)

### Environment

1. Target Platform ( iOS, Android):
2. Development Operating System ( Windows 10):
3. Build tools (Xcode or Android Studio version 2.3, Android SDK version 25.2.5):
4. React Native version (e.g. 0.45.1): 0.47
5. RNFirebase Version (e.g. 2.0.2):

**Comment by Ehesp** [comment]
Do you have the latest sdks installed on android studio?

**Comment by AlexsanderManzoli** [comment]
yes

**Comment by chrisbianca** [comment]
@AlexsanderManzoli This error will only occur if you don't have the correct SDKs installed within Android studio.  Please check again.

**Comment by agrosner** [comment]
add : `maven { url 'https://maven.google.com' }` to project as a repository in both the `buildscript` and `repositories` blocks:
```groovy
buildscript {
    ext.kotlin_version = '1.1.3-2'
    repositories {
        jcenter()
        maven { url 'https://maven.google.com' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:3.1.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven { url 'https://maven.google.com' }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

**Comment by agrosner** [comment]
note if you're running android build tools 3.0.0-beta2+ you can replace `maven { url 'https://maven.google.com' }` with `google()`

**Comment by AlexsanderManzoli** [comment]
It worked, brother, sorry for the delay I ended up getting involved in other projects here
