### ISSUE TITLE
the react-native firebase/firestore are demanding same version as auth and app has

### ISSUE THREAD

**Issue by dharmendrashah** [invertase/react-native-firebase#3521]
## Issue

Describe your issue here
i have install the app and the  auth they wererunning smoothly then i install the firestore and follow the guidelines run the app successfull but when i import the module the error console are saying please install the same version as app and auth it will cause an error but i install the app sll the same version but it still logging the same errror even i downgrade them all but it keep logging the same error please resoleve this.
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
{
  "name": "ChatOne",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "clean": "cd android && gradlew clean && cd ..",
    "WatchMan-Clear": "watchman watch-del-all"
  },
  "dependencies": {
    "@material-ui/core": "^4.9.10",
    "@react-native-community/masked-view": "^0.1.9",
    "@react-native-firebase/app": "^6.4.0",
    "@react-native-firebase/auth": "^6.4.0",
    "@react-native-firebase/firestore": "^6.4.0",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",
    "deprecated-react-native-listview": "0.0.6",
    "native-base": "^2.13.12",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-gifted-chat": "^0.11.4",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-reanimated": "^1.8.0",
    "react-native-responsive-screen": "^1.4.1",
    "react-native-router-flux": "^4.2.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.5.0",
    "react-native-simple-toast": "^1.1.1",
    "react-native-tab-view": "^2.14.0",
    "react-native-tab-view-viewpager-adapter": "^1.0.7",
    "react-native-touchable-scale": "^2.1.1",
    "react-native-vector-icons": "^6.6.0",
    "react-router-native": "^5.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/runtime": "^7.9.2",
    "@react-native-community/eslint-config": "^1.0.0",
    "babel-jest": "^25.3.0",
    "eslint": "^6.8.0",
    "eslint-plugin-react-hooks": "^3.0.0",
    "jest": "^25.3.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [yes ] my application is an AndroidX application?
- [yes ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ yes] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```
You've attemped to require @react-native-firebase/firestore version 6.4.1 however he @react-native-firebase/app module is of a differrent version 6.4.0
all the firebase modules must have to be the same version as well

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [] **Android** but have not tested behavior on iOS
  - [yes ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
All the modules need to be at the same version right now (though this may change in future)
If you get a redbox on device indicating they are not, you likely have a caching issue in your local system.
Try on a fresh machine, or try `npx react-native-clean-project`

**Comment by dharmendrashah** [comment]
thanks dude for reply i install the react-native-clean-project but it didn't solve any problem i aloso re-install the all node_modules  again and clean all the builds that i have but it didn't resolve any thing. do you have any other suggestions please suggest me

**Comment by mikehardy** [comment]
No, but there are related issues #2626 
This is *always* a local problem. Something is wrong with your project. I wish I had a crystal ball and could magically see and tell you what it was, but I can't - I can only say that the error message is descriptive and prescriptive = somehow you have a stale version of part of react-native-firebase installed on the device somehow, and something about your project config, install, compile, link, packaging or app install chain has done it.

**Comment by dharmendrashah** [comment]
thanks, Sorry for your inConvenience i figure out what was the problem i mywatchman has some cache and it was never been cleaned sice the project started tht cause me the problem but thanks for your worry and guide me what the problem it may be and how it could be resolved. 
thankyou very mouch

**Comment by mikehardy** [comment]
Watchman cache should have been cleared by my initial recommendation: https://github.com/pmadruga/react-native-clean-project/blob/master/source/internals/tasks.js#L27
