### ISSUE TITLE
Receiving [Error: Internal] in RN app when triggering a Cloud Function

### ISSUE THREAD

**Issue by bimix** [invertase/react-native-firebase#3523]
## Issue

Describe your issue here

I have a Google Cloud Function which I am calling from my RN app but it is returning 
[Error: Internal] 
I have set the permission to Unauthenticated users so anyone can call it - for testing purposes only. When I set to Authenticated users permission, it throws another error [Error: Unauthenticated] eventhough I am authenticated and I can get the currentUser id in my app. 
Tried searching for this error but it didnt send me to any possible solutions so decided to post here and hopefully recieve responses that will help me fix it. 

```javascript
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();

exports.createUser = functions.region('europe-west1').https.onCall(async (data, context) => {

try {
    //Checking that the user calling the Cloud Function is authenticated
    if (!context.auth) {
        throw new UnauthenticatedError('The user is not authenticated. Only authenticated Admin users can create new users.');
    }

    const newUser = {
        email: data.email,
        emailVerified: false,
        password: data.password,
        disabled: false
    }
    const role = data.role;
    const userRecord = await admin
        .auth()
        .createUser(newUser);
    const userId = userRecord.uid;
    const claims = {};
    claims[role] = true;
    await admin.auth().setCustomUserClaims(userId, claims);
    return { result: 'The new user has been successfully created.' };
} catch (error) {
    if (error.type === 'UnauthenticatedError') {
        throw new functions.https.HttpsError('unauthenticated', error.message);
    } else if (error.type === 'NotAnAdminError' || error.type === 'InvalidRoleError') {
        throw new functions.https.HttpsError('failed-precondition', error.message);
    } else {
        throw new functions.https.HttpsError('internal', error.message);
    }
}
});
in my RN app I am calling it like this: 
    var user = {
                role: role
               }

    const defaultApp = firebase.app();
    const functionsForRegion = defaultApp.functions('europe-west1');
    const createUser = await functionsForRegion.httpsCallable('createUser');
    createUser(user)
            .then((resp) => {
                //Display success
             });
                console.log(resp.data.result);
            })
            .catch((error) => {
                console.log("Error on register patient: ", error)
            });
```
I think the way I am calling it in my RN app is correct because I have tested it with a testFunction and I returned a simple string. So, I believe the problem is somewhere in the function itself. 
EDIT: I just tested by simply calling the function and returning the context and it always returns Internal error:
exports.registerNewPatient = functions.region('europe-west3').https.onCall((data, context) => {
 return context; //this is returned as INTERNAL error. 
}
```

I just cant get to understand whats going on here, why does it return Internal error when I am authenticated as a user and it should return the authenticated user data, isn't that right?

## Project Files

<!-- Provide the contents of key project files which will help to debug -->
<!--     For Example: -->
<!--        - iOS: `Podfile` contents. -->
<!--        - Android: `android/build.gradle` contents. -->
<!--        - Android: `android/app/build.gradle` contents. -->
<!--        - Android: `AndroidManifest.xml` contents. -->

<!-- ADD THE CONTENTS OF THE FILES IN THE PROVIDED CODE BLOCKS BELOW -->

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
firebase console lets you see the logs of function execution. What do they say?

**Comment by bimix** [comment]
> firebase console lets you see the logs of function execution. What do they say?

this is all I get in the Console: 
> Function execution took 988 ms, finished with status code: 500

**Comment by mikehardy** [comment]
So, in your firebase function, you log absolutely nothing? Because if it returned 500 that means your function had an error. You should add logging in the function. This sounds like something I do frequently, which is code up a function with an error. But I put all sorts of console.log statements in my functions while developing, so I get nice output and I can track the error down

**Comment by bimix** [comment]
> he function. This sounds like something I do frequently, which is code up a function with an err

I do have many logs all over the code but none of them is being triggered on this failure. However, I decided to return 'context' and now I see its Undefined. So, the problem obviously is that the context is just Undefined, why is this happening?!

**Comment by bimix** [comment]
> So, in your firebase function, you log absolutely nothing? Because if it returned 500 that means your function had an error. You should add logging in the function. This sounds like something I do frequently, which is code up a function with an error. But I put all sorts of console.log statements in my functions while developing, so I get nice output and I can track the error down

ma bad, its is not undefined, now I have a different problem coz I fixed the previous one. Was doing something stupid. The problem now is that I don't know how to import the Geopoint in RN Cloud Function.
