### ISSUE TITLE
[tests] Needlessly depends on fork of sinon

### ISSUE THREAD

**Issue by greena13** [invertase/react-native-firebase#353]
Hey guys,

The patch I submitted to sinon to accommodate React Native on iOS and Android has long been merged into master, so I believe there's no further need to depend on the fork of sinon I created asa temporary fix. 

As I've fallen out of touch with this project - it seems to be progressing fantastically - I thought it best to create an issue and let one of the members of the core team ensure the test suite behaves the same.

Thanks

**Comment by Salakar** [comment]
@greena13 switched it over this morning as part of v3 changes, thanks for flagging!
