### ISSUE TITLE
[auth] Wrong token format being passed from google-signin in documentation

### ISSUE THREAD

**Issue by jbrew138** [invertase/react-native-firebase#3531]
## Documentation Feedback

Following the documentation on setting up Google account authentication (https://rnfirebase.io/auth/social-auth#google), I ran into several issues and errors that prevented login. Since this is an issue that can be remedied by a simple fix to user code, I thought it would be more relevant to documentation than making an issue report. Currently I'm using @react-native-firebase/auth@6.7.1 and @react-native-community/google-signin@4.0.0

As is, the documentation shows the Google credential from GoogleAuthProvider being passed directly to signInWithCredential()

```javascript
    const token = await GoogleSignin.signIn();
    const googleCredential = auth.GoogleAuthProvider.credential(token);
    auth().signInWithCredential(googleCredential);
```

Running this code caused a Java error, `com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String`. I ran the debugger in Android studio and found that the error was being thrown on a ReadableNativeMap containing the "token" object provided by googleCredential:

```
{ NativeMap: 
  {
    "user": {
      "id":"**************",
      "name":"*****",
      "givenName":"****",
      "familyName":"****",
      "email":"****",
      "photo":"*****"
    },
    "idToken":"*****",
    "serverAuthCode":null,
    "scopes": [
      "https://www.googleapis.com/auth/userinfo.email", 
      "https://www.googleapis.com/auth/userinfo.profile"
    ]
  }
}
```

Since it appeared to want a string I overwrote the 'token' object with a JSON.stringified version, but it was rejected as malformed (not able to parse).

Finally, I set the 'token' property to point to the 'idToken' string, which then was accepted by Firebase auth and logged in as expected. The following is a working modification to the documentation, as an example:

```javascript
    const token = await GoogleSignin.signIn();
    const googleCredential = auth.GoogleAuthProvider.credential(token);
    googleCredential.token = googleCredential.token.idToken; //Adding this line fixed the issue
    auth().signInWithCredential(googleCredential);
```

**Comment by mikehardy** [comment]
I was curious if this had changed or if it had always been this way, I'm still on RNFBv5 and my code is doing similar:

```typescript
      const data = await GoogleSignin.signIn();

      // create a new firebase credential with the token
      const credential = firebase.auth.GoogleAuthProvider.credential(
        data.idToken
        // data.accessToken
      );
```

Seems like a docs PR would be best - you can just hit the edit button at the top right of any of the pages on the docs site and it'll walk you through the PR process via the github web UI

**Comment by arcollector** [comment]
if you read the docs, he is doing `const **{** idToken **}** = await GoogleSignin.signIn();` not `const idToken = await GoogleSignin.signIn(); `

**Comment by russellwheatley** [comment]
I ran this code on my android app and I was able to sign in:
```js
async function onGoogleButtonPress() {
    // Get the users ID token
    //correct
    const { idToken } = await GoogleSignin.signIn();

    // Create a Google credential with the token
    const googleCredential = auth.GoogleAuthProvider.credential(idToken);
    // Sign-in the user with the credential
    // googleCredential.token = googleCredential.token.idToken;

    return auth().signInWithCredential(googleCredential);
  }
```

If I uncomment this line as you suggest 
```js
googleCredential.token = googleCredential.token.idToken;
```
I get the following error:
<img width="357" alt="Screenshot 2020-04-28 at 11 31 32" src="https://user-images.githubusercontent.com/16018629/80477433-d2c28900-8943-11ea-958d-44d6f8e2a8ca.png">

As @arcollector mentioned, you also need to pluck out the `idToken` from the `GoogleSignin.signIn()` call.

**Comment by arcollector** [comment]
remember also that this is a promise as well
```
return await auth().signInWithCredential(googleCredential);
```

**Comment by jbrew138** [comment]
It's my bad, I missed the fact that they were using destructuring.

**Comment by Aung-Myint-Thein** [comment]
Hi @mikehardy, saw your comment that you are using GSignin with RNFBv5. I am having Google-Signin issue on iOS while my RNFB is still 5.5.7. I updated my RN to 0.62.2 and need to update my pod files for Firebase to 6.13.0 and updated my Google-Signin to 4.0.3 but it crashed upon start the app. I created a clean RN 0.62.2 project and added G-signin 4.0.3 there and it is working fine. Have you faced similar problem? Which versions of RN are you using now?

Any tip on how to read the following error stack? Thanks! 

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GIDSignIn handleURL:]: unrecognized selector sent to instance 0x600001114a50'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e39f0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ad79b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e5ac34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23e3e90c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23e40bf8 _CF_forwarding_prep_0 + 120
	5   myanlearn_for_students              0x0000000102e4833f +[RNGoogleSignin application:openURL:options:] + 159
	6   myanlearn_for_students              0x00000001025f1334 -[AppDelegate application:openURL:options:] + 212
	7   myanlearn_for_students              0x0000000102d498c5 -[GULAppDelegateSwizzler application:openURL:options:] + 485
	8   myanlearn_for_students              0x00000001028199d1 -[FIRDynamicLinks passRetrievedDynamicLinkToApplication:] + 337
	9   myanlearn_for_students              0x0000000102819c6f -[FIRDynamicLinks retrievalProcess:completedWithResult:] + 335
	10  myanlearn_for_students              0x000000010280f52d -[FIRDLDefaultRetrievalProcessV2 handleRequestResultsUpdated] + 541
	11  myanlearn_for_students              0x000000010280ea39 __68-[FIRDLDefaultRetrievalProcessV2 retrievePendingDynamicLinkInternal]_block_invoke + 425
	12  myanlearn_for_students              0x00000001028168d4 __105-[FIRDynamicLinkNetworking sendRequestWithBaseURLString:requestBody:endpointPath:parserBlock:completion:]_block_invoke_3 + 52
	13  libdispatch.dylib                   0x00000001075cdf11 _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x00000001075cee8e _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x00000001075dcd97 _dispatch_main_queue_callback_4CF + 1149
	16  CoreFoundation                      0x00007fff23d9da89 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	17  CoreFoundation                      0x00007fff23d985d9 __CFRunLoopRun + 2041
	18  CoreFoundation                      0x00007fff23d97ac4 CFRunLoopRunSpecific + 404
	19  GraphicsServices                    0x00007fff38b2fc1a GSEventRunModal + 139
	20  UIKitCore                           0x00007fff48bc7f80 UIApplicationMain + 1605
	21  myanlearn_for_students              0x00000001025f1830 main + 112
	22  libdyld.dylib                       0x00007fff519521fd start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by mikehardy** [comment]
Why stop at 6.13.0? Go to current stable on the upstream SDKs.
I am using current stable of literally every single thing except just recently eslint (I'm on v6 still, but this is not material to your question).
I have not faced this problem at all.
Perhaps `npx react-native-clean-project`

**Comment by Aung-Myint-Thein** [comment]
Thanks for reply. I tried npx react-native-clean-project and still the same error. For 6.13.0, it is the recommended version in the RNFB doc. Would you mind to share the pod versions that you are using? Thanks.

**Comment by mikehardy** [comment]
You can see in the script but the general them is "current stable of everything". iOS 6.24 I think / Android 25.3.1 but my memory might be off. Its in the script
