### ISSUE TITLE
useEffect(() => {dynamicLinks().getInitialLink() .then(link => {  // NOT WORKING IN in APK (NULL)  

### ISSUE THREAD

**Issue by girish54321** [invertase/react-native-firebase#3535]
## Issue

Describe your issue here

useEffect(() => {
    dynamicLinks()
      .getInitialLink()
      .then(link => {  // NOT WORKING IN in APK  
     using rnfirebase = 6
---

#### `AndroidManifest.xml`:
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.appname">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-feature android:name="android.hardware.camera.front" android:required="false" />
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:usesCleartextTraffic="true"
      android:theme="@style/AppTheme">
      <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
      <activity
          android:name=".SplashActivity"
          android:theme="@style/SplashTheme"
          android:configChanges="orientation"
          android:screenOrientation="portrait" 
          android:launchMode="singleTask">
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity
          android:name=".MainActivity"
          android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
          android:launchMode="singleTask"
          android:screenOrientation="portrait"
          android:windowSoftInputMode="adjustPan">
        <intent-filter>
        <data android:scheme="https"  
          android:host="appname.page.link" />
           <data android:host="appname.page.link" android:scheme="http"/>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

**Comment by Ehesp** [comment]
Please follow the issue template.
