### ISSUE TITLE
Firebase auth native sdk has not been included in your podfile - auth methods have been disabled.

### ISSUE THREAD

**Issue by michelalbers** [invertase/react-native-firebase#354]
(Please write your issue here along with the environment details below. Include any key files which will help us to debug, such as your `Podfile` and/or `app/build.gradle` file).

### Environment

1. Target Platform (e.g. iOS, Android): iOS
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Xcode 8.3.3
4. React Native version (e.g. 0.45.1): 0.47.1
5. RNFirebase Version (e.g. 2.0.2): 2.1.3

### Description

I installed react-native-firebase via cocoapods and all firebase dependencies with it:

```ruby
    # Uncomment the next line to define a global platform for your project
    platform :ios, '8.0'
    project 'my-app.xcodeproj'

    target 'my-app' do
      # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
      use_frameworks!
    
      pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'BatchedBridge', # Required For React Native 0.45.0+
        'Core',
        'ART',
        'RCTImage',
        'RCTNetwork',
        'RCTText',
        'RCTWebSocket',
        'RCTCameraRoll',
        'RCTGeolocation',
        'RCTPushNotification',
        'RCTSettings',
        'RCTLinkingIOS',
      ]
      pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

      pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk/ios'

      # Fetch blob
      pod 'react-native-fetch-blob',
          :path => '../node_modules/react-native-fetch-blob'

      # Camera & PhotoEditor
      pod 'react-native-camera', path: '../node_modules/react-native-camera'
      pod 'PhotoEditorSDK'
      pod 'photo-editor-sdk-react-native', path: '../node_modules/photo-editor-sdk-react-native'

      # React Native Firebase
      pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

      # Firebase Stuff
      pod 'Firebase/Core'
      pod 'Firebase/AdMob'
      pod 'Firebase/Analytics'
      pod 'Firebase/Auth'
      pod 'Firebase/Crash'
      pod 'Firebase/Database'
      pod 'Firebase/DynamicLinks'
      pod 'Firebase/Messaging'
      pod 'Firebase/RemoteConfig'
      pod 'Firebase/Storage'
    end
```

### Error

It builds just fine but when running on device I get: 

```Firebase auth native sdk has not been included in your podfile - auth methods have been disabled.```

**Comment by michelalbers** [comment]
Apparently the issue was 

```ruby
use_frameworks!
```

Firebase seems not to be working with that option. Removed it and it seems fine for now. Ugh.

**Comment by chrisbianca** [comment]
@michelalbers Unfortunately, this is a known issue that we note in the documentation: http://invertase.io/react-native-firebase/#/installation-ios

Firebase are working with the Cocoapods team to try and address this, but it might be a little while before that happens.  We're monitoring the situation and update RNFirebase to work if required.

**Comment by michelalbers** [comment]
Ah. Stupid me. Thanks anyway :)
