### ISSUE TITLE
Hermes

### ISSUE THREAD

**Issue by Bardiamist** [invertase/react-native-firebase#3549]
## Documentation Feedback

It works with Hermes now?

>At this time, React Native Firebase does not support the Hermes JavaScript engine due to compatibility issues. We are actively tracking the changes to Hermes and will ensure support once both are compatible with each other.

I see this in [documentation](https://rnfirebase.io/#hermes-support) but not found any related issue/discussion.

**Comment by Ehesp** [comment]
We haven't tried it in a little while, but it was missing a core feature last time we checked causing issues.

If anyone would like to try with the latest version please do.

**Comment by Bardiamist** [comment]
>it was missing a core feature

What is core feature? Something from [this list](https://github.com/facebook/hermes/blob/master/doc/Features.md#excluded-from-support)?

>last time we checked causing issues

What issues? It doesn't fully work? Or worked with some bugs?

I use Hermes and want mirgate `react-native-firebase` from v5 to v6. I need to understand how v6 stable with Hermes.

**Comment by Ehesp** [comment]
> What is core feature? Something from this list ?

Yep.

> What issues? It doesn't fully work? Or worked with some bugs?

Didn't even work. Like I said, we need to review it again.

**Comment by loverdeveloper** [comment]
is v5 support Hermes?

**Comment by mikehardy** [comment]
@loverdeveloper doubtful, only way to know though is to try it, then test your entire app on all target devices.

**Comment by Bardiamist** [comment]
@loverdeveloper I use v5 oly for push notifications, no problems were noticed.

**Comment by loverdeveloper** [comment]
it's not enough for me, i want to use analytics, crashlyrics and etc

**Comment by bell-steven** [comment]
I've been using v5 with hermes without any issues. Analytics, Auth and Messaging.

**Comment by comvenger-brandon** [comment]
Working for us without any problems. Analytics, Messaging, Crashlytics, Dynamic Links, Performance.

**Comment by loverdeveloper** [comment]
@comvenger-brandon 
How? I switched engine to Hermes and then my events not work, i think my screen views works but events not, i can't see them in firebase stream view!
Do you do something special?

**Comment by comvenger-brandon** [comment]
> @comvenger-brandon
> How? I switched engine to Hermes and then my events not work, i think my screen views works but events not, i can't see them in firebase stream view!
> Do you do something special?

RN 0.62.2, hermes 0.4.1, RNF 6.4.0.
No special config, just the regular installation.

**Comment by loverdeveloper** [comment]
@comvenger-brandon Thanks man, i will try it

**Comment by loverdeveloper** [comment]
@comvenger-brandon Do you testing on android? Or IOS?

**Comment by loverdeveloper** [comment]
Guys, after updating RN to **62**, it works :) I'm so happy

**Comment by billel-boudchicha** [comment]
guys , doesn't work , no events , no notifications
`"@react-native-firebase/app": "^7.0.0",`
  `"@react-native-firebase/messaging": "^7.0.0",`
`"react-native": "0.62.2"`

**Comment by RuairiOliver** [comment]
Fine for me with hermes enabled on v6:

"@react-native-firebase/analytics": "^6.3.4",
    "@react-native-firebase/app": "^6.3.4",
    "@react-native-firebase/crashlytics": "^6.3.4",
    "@react-native-firebase/dynamic-links": "^6.3.4",
    "@react-native-firebase/messaging": "^6.3.4",
    "@react-native-firebase/ml-vision": "^6.3.4",

**Comment by haswalt** [comment]
So ^6 works but ^7 doesn't?

**Comment by joshlbaker** [comment]
Hermes works with these two for me:
```
    "@react-native-firebase/app": "^6.7.1",
    "@react-native-firebase/messaging": "^6.7.1",
```

Someone should really update those docs. The default shouldn't be to disable Hermes

**Comment by Bardiamist** [comment]
I use
```
"react-native": "0.62.2",
"@react-native-firebase/app": "7.1.0",
"@react-native-firebase/messaging": "7.1.0",
```
looks good

**Comment by haswalt** [comment]
Thanks @joshlbaker @Bardiamist much appreciated

**Comment by joshlbaker** [comment]
Oh yeah I'm on `"react-native": "0.62.2"` as well

**Comment by chungweileong94** [comment]
Apparently, I faced an error while I try to push data to the realtime database, and it was working fine with Hermes disabled.

I'm on `react-native 0.62` & `react-native-firebase 6.7.1`

**Comment by Bardiamist** [comment]
I think Hermes will not support Proxy. Better if `react-native-firebase` will not use Proxy.

**Comment by mikehardy** [comment]
If Hermes is supposed to be a full fledged javascript implementation, shouldn't that read "better if hermes will support proxy"? Behold, it is possible, if anyone wants to try it: https://github.com/facebook/hermes/issues/33#issuecomment-606963341

**Comment by SudoPlz** [comment]
Looks like Hermes works on our end (react-native 0.63) without making any changes at all.

We're not using any firebase database at all, [which looks like it's the only thing using Proxy ](https://github.com/invertase/react-native-firebase/blob/7d55930ceb9e2843e975315fe7029cfa8882ab6c/packages/database/lib/DatabaseThenableReference.js) and thus blocking Hermes so far.

**Comment by Salakar** [comment]
@SudoPlz This is correct. Hermes should generally work, was just edge cases like Proxy in DB that were blocking. I believe Proxy support has landed in Hermes now (as @mikehardy mentioned above) but the version shipped with RN hasn't been updated yet (last checked RN 0.63). So it's just a matter of time, that or a PR would be welcome to remove proxy usage from DB :)

**Comment by deepakverma4** [comment]
@Salakar  I am not able to use firebase database with hermes enabled. Any workaround to use firebase database with hermes enabled?

**Comment by chungweileong94** [comment]
> @Salakar I am not able to use firebase database with hermes enabled. Any workaround to use firebase database with hermes enabled?

I'm not sure if this help, but someone actually using a polyfill to work around this issue. https://github.com/facebook/hermes/issues/33#issuecomment-664403786

**Comment by Lucas-Geitner** [comment]
Hello :^)

Hermes just released his version 0.7, with Proxy support by default 🚀

👉🏻 https://github.com/facebook/hermes/releases/tag/v0.7.0

**Comment by mikehardy** [comment]
@Lucas-Geitner do you confirm that it works with hermes? Including `@react-native-firebase/database`? If so, you could propose a docs PR that upgrades our Hermes-related documentation from a sort of "warning: don't use" to a "we think this should work now but test it carefully in your project to make sure" ?

**Comment by oguzhanali** [comment]
I tried it on RN 63 Hermes enabled Android with Auth, Firestore and Messaging and it seems everything works fine.

**Comment by leelandclay** [comment]
I just updated to RN 0.63. It still uses version 0.5 of hermes and does not work with Database. 
Has there been any mention from the react-native team if they're going to update the dependencies any time soon?

**Comment by Bardiamist** [comment]
@leelandclay [React native 0.64.0 will suport Hermes with Proxy](https://github.com/facebook/react-native/releases/tag/v0.64.0-rc.1) (read as react-native-firebase database)

**Comment by leelandclay** [comment]
@Bardiamist thanks. I totally missed the 64 part.

**Comment by iqqmuT** [comment]
I just updated to RN 0.64.0 with Hermes enabled and now Realtime Database functions are working!

**Comment by glesperance** [comment]
Just want to chime on this about how important Hermes support is. Some react-native app experience random thread crashes in libjsc.so. The only way to successfully fix the issue is to turn on Hermes[1].

I really hope RNFB continues to work with hermes as without it I can't get my app to not randomly crash. #2cents

[1] https://stackoverflow.com/questions/65418985/react-native-crashedthread-sigsegv-libjsc-so 

side note: RNFB is working for me with hermes w v14.11.1 (ios & android)

**Comment by mikehardy** [comment]
We have some new knowledge+wisdom in the area:
- there were patches added to react-native 0.69.1 in collaborate with our testing here that enables `use_frameworks!` (needed for react-native-firebase v15+) and `hermes_enabled` set to true, with those, hermes works!
- those patches caused a problem building to real devices though, if you have bitcode enabled (initially disappointing)
- it turns out Apple is killing bitcode with Xcode 14, so...actually just turn bitcode off (unexpected, but I will take it)

So at this point the current state of things is that with react-native-firebase v15+ and react-native 0.69.1+ we have hermes working.

And it turns out that use_frameworks in general was just not something lots of people tested but I'm *in* the react-native release testers group and clearly this is important for react-native-firebase so I will continue to make sure the `use_frameworks!` situation in react-native improves

Cheers!

**Comment by glesperance** [comment]
That's awesome. Thank you @mikehardy !

**Comment by brett-james-rocketlab** [comment]
With firebase/analytics (15.1.1), it's crashing with hermes enabled.
I have tried making a release build with bitcode disabled and this did not fix it.

When I go to run it on a real hardware device, the app will start and crash before anything is rendered to the screen.

Here are the workarounds that let me have it run in development:

`use_frameworks! :linkage => :static`
And another change that 0.69.1 includes that Mikehardy mentioned in a previous post:
https://github.com/facebook/react-native/issues/32451#issuecomment-1152044654

As it is, it makes it unusable. Should we roll back to the latest v14 instead?
