### ISSUE TITLE
"Duplicate declarations" error from AppDelegate.m for messaging on iOS

### ISSUE THREAD

**Issue by eemebarbe** [invertase/react-native-firebase#355]
In the installation guide for cloud messaging on iOS, it instructs me to add some methods to AppDelegate.m. The two methods included together below create a "duplicate declaration" error when attempting to build the app. When one method is removed, the app builds successfully.  I'm not familiar with OBJ-C, merely following the guide.

```
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo {
  [RNFirebaseMessaging didReceiveRemoteNotification:userInfo];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [RNFirebaseMessaging didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}
```

### Environment

1. Target Platform: iOS
2. Development Operating System: OSX
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): CLI
4. React Native version (e.g. 0.45.1): 0.43.1
5. RNFirebase Version (e.g. 2.1.2):

**Comment by chrisbianca** [comment]
@eemebarbe Can we see your complete `AppDelegate.m`?  These are different methods as they have different method signatures, so they should not cause a duplicate declaration error, unless you already have these methods in your `AppDelegate.m` already

**Comment by chrisbianca** [comment]
Closing this as no response.  Please re-open with the information requested.
