### ISSUE TITLE
undefined is not a function (near '...taskProvider()(data).then...'), stack:     startHeadlessTask

### ISSUE THREAD

**Issue by programmer-RN** [invertase/react-native-firebase#3554]
Hi, I'm facing this issue when received background notification in android device.
When open background notification in android build release, the app is crash.
I have write registerHeadlessTask in index.js, but error still exist.
```
const headlessTask = () =>{
  return Promise.resolve();
};
AppRegistry.registerComponent(appName, () => App);
AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => headlessTask);
```

May I know what is it the problem? 

 "@react-native-firebase/app": "^6.4.0",
 "@react-native-firebase/messaging": "^6.4.0",

**Comment by Ehesp** [comment]
Please read the docs. Your code is for v5 yet you have v6 installed.

https://rnfirebase.io/messaging/usage
