### ISSUE TITLE
Foreground iOS not working

### ISSUE THREAD

**Issue by programmer-RN** [invertase/react-native-firebase#3555]
Hi, I'm facing issue of failed to display foreground notification in iOS , background is working.Now I'm using react-native-push-notification to display notification received.
Hope someone can help me, because I have been stuck in this problem many days.

PushNotification.localNotification({
  title: title,
  message: body,
  bigText: body,
})

"@react-native-firebase/app": "^6.4.0",
"@react-native-firebase/messaging": "^6.4.0",

**Comment by Ehesp** [comment]
Please follow the issue template.

**Comment by programmer-RN** [comment]
Sorry, this is my first time using github, may I know where is issue template?

**Comment by Naveen562117** [comment]
hi I have followed all the steps given in the home page of this package and the on notification event listeners and background notification is working perfectly fine any update on this  foreground notification not working in iOS

**Comment by mikehardy** [comment]
foreground notification may only be achieved with a full featured local notification package, it is outside of scope for firebase

**Comment by Naveen562117** [comment]
@mikehardy thank you for the response I have figured this out , and working on it
