### ISSUE TITLE
Problem with manual linking

### ISSUE THREAD

**Issue by mkhlzaytsev** [invertase/react-native-firebase#3558]
## Issue

Hello guys,

I have a problem with manual linking in Android App. I think it weird with my project structure, it's look like: 

C:/AwesomeProject/mobile-android
C:/AwesomeProject/mobile-react-native

When I try to link project i get error: 

Build file 'C:\AwesomeProject\mobile-react-native\node_modules\@react-native-firebase\app\android\build.gradle' line: 76

* What went wrong:
A problem occurred evaluating project ':@react-native-firebase_app'.
> Cannot get property 'parentFile' on null object

How can I fix it? 

Thanks.

**Comment by mikehardy** [comment]
@Salakar is this related to the search for firebase.json? There was another issue crosslinking that

@mkhlzaytsev you can always diff into the build.grade file mentioned at exactly that line and hack around to disable things or try things. What have you experimented with and what ended up getting it working? patch-package module may be used to persist your change so you are not blocked locally

**Comment by afizboltz** [comment]
> @Salakar is this related to the search for firebase.json? There was another issue crosslinking that
> 
> @mkhlzaytsev you can always dive into the build.grade file mentioned at exactly that line and hack around to disable things or try things. What have you experimented with and what ended up getting it working? patch-package module may be used to persist your change so you are not blocked locally

what need to be done in build.gradle ? can you guide us how to fix this issue ?

**Comment by mikehardy** [comment]
No sorry - "hack around" means just try things. Android Studio contains language support for groovy (the language of gradle files) so it will assist you in commenting things out. It's a different language sure but code is code, you can try things
