### ISSUE TITLE
Unable to clear delivered notifications in v6

### ISSUE THREAD

**Issue by aravi365** [invertase/react-native-firebase#3563]
## Issue

Tried the code below,but nothing worked as i am on v6
 
```firebase.notifications().removeAllDeliveredNotifications()```

package.json
```"@react-native-firebase/app": "^6.4.0",```
```"@react-native-firebase/messaging": "^6.4.0",```

**Comment by benjaminaudet** [comment]
https://rnfirebase.io/messaging/notifications

Since the v6, the notifications are not manage as the same way as before, check the doc !

**Comment by aravi365** [comment]
> https://rnfirebase.io/messaging/notifications
> 
> Since the v6, the notifications are not manage as the same way as before, check the doc !

So, is there anyway to clear the notifications? I didn't find anything in the docs.

**Comment by mikehardy** [comment]
RNFBv6 does not do anything or have any APIs that handle local notifications.
It handles cloud messaging (which is a firebase thing, and the natural domain of this package) but for local notifications you'll need to integrate one of the local notification packages mentioned in the docs

**Comment by aravi365** [comment]
@mikehardy its an fcm notification from backend. Not the local notification.

**Comment by mikehardy** [comment]
People confuse this all the time, because firebase confuses it a bit.

It is *possible* but not advised to have the upstream/official Firebase SDKs pop a local notification for you, by including the correct key/value information in the cloud message.

That's handled outside react-native-firebase, the Firebase SDKs themselves do it.

In order to interact with those notifications you'll need a react-native package that handles local notification APIs, as react-native-firebase no longer covers local notification APIs on device, it's handled better by other packages

**Comment by aravi365** [comment]
@mikehardy  Can you please guide me with this? I have used react-native-firebase v6, and right now i am getting notifications delivered from the backend(using fcm).  The only issue i have right now is clearing the notifications. How to fix this?
Also, if i am wrongly implemented this, can you guide me how to properly implement push notifications now. I used to implement it using v5, earlier and i didnt find much difficulty at that times.

**Comment by mikehardy** [comment]
Cloud messages: handled by react-native-firebase
Any local notification interaction (including local notifications popped up by the underlying firebase SDKs if you sent a cloud message that made that happen): some other package.

Options for other packages
react-native-notifications
react-native-push-notifications
notifee

**Comment by barak109** [comment]
For IOS
```
- (void)applicationDidBecomeActive:(UIApplication *)application {
// delete the badge
   [UIApplication sharedApplication].applicationIconBadgeNumber = 0;
// delete the notifications
  [[UNUserNotificationCenter currentNotificationCenter] removeAllDeliveredNotifications];
}
```

to AppDelegate.m.

**Comment by lyseiha** [comment]
@barak109 how about android?

**Comment by barak109** [comment]
@lyseiha 

Import PushNotification from “react-native-push-notification”

PushNotification.cancelAllLocalNotifications()

**Comment by hammerstrike331** [comment]
For IOS
```
Import PushNotification from “react-native-push-notification”

PushNotificationIOS.setApplicationIconBadgeNumber(0)
```

**Comment by brianmak3** [comment]
> RNFBv6 does not do anything or have any APIs that handle local notifications.
> It handles cloud messaging (which is a firebase thing, and the natural domain of this package) but for local notifications you'll need to integrate one of the local notification packages mentioned in the docs

You have answered this irrelevantly. @aravi365 has not even mentioned anything with local notifications

**Comment by mikehardy** [comment]
@brianmak3 I suggest you re-read, his entire question was about clearing "local notifications" (that is, actual user-visible things in the notification tray users can see). And the solutions proposed (which are quite popular, judging by reactions!) are based on handling remote notifications. Perhaps you are confusing the terms.

**Comment by RKARaj** [comment]
I started using 
  "@react-native-firebase/app": "^12.0.0",
@react-native-firebase/messaging": "^12.0.0",

Is there anything like below to clear remote notifications WITHOUT installing any other like 'react-native-push-notification'
i used this before v6:   firebase.notifications().removeAllDeliveredNotifications()

Please let me know. Thank you

**Comment by mikehardy** [comment]
@RKARaj no there is not

**Comment by malmyros** [comment]
I don't understand why you have closed the post. The previous versions of this library supported the functionality and now it's no longer supported. No one is confusing things about local notifications.

Documentation is not clear, and it's not clear why the support for this was dropped in the first place. The library creates a notification badge which doesn't allow for removal and is asking for a separate library to handle it.

**Comment by mikehardy** [comment]
This library wraps firebase-ios-sdk and firebase-android-sdk. If you can point to some APIs regarding local notifications we are not covering, we can implement them. Local notification APIs were dropped because they are not firebase APIs, they are incredibly difficult to get correct, and other libraries handle it.

**Comment by TVMD** [comment]
> /push-notification-ios

how about android?

**Comment by TVMD** [comment]
> For IOS
> 
> ```
> Import PushNotification from "@react-native-community/push-notification-ios"
> 
> PushNotificationIOS.setApplicationIconBadgeNumber(0)
> ```

how about android ?

**Comment by yakmoon** [comment]
apparently this task is beyond your availability. it's been a long time since everyone asked for this.
and I was hoping to see this fixed in 2023, but Nope. maintainers are too busy fixing other minor stuff.

**Comment by mikehardy** [comment]
@yakmoon Hi there! This is an open source library, we welcome PRs - you can always fork it, develop the feature that is important to your and/or your business, and post a PR with the feature.

**Comment by mohamedshrif995** [comment]
> For IOS @aravi365
> 
> ```
> - (void)applicationDidBecomeActive:(UIApplication *)application {
> // delete the badge
>    [UIApplication sharedApplication].applicationIconBadgeNumber = 0;
> // delete the notifications
>   [[UNUserNotificationCenter currentNotificationCenter] removeAllDeliveredNotifications];
> }
> ```
> 
> In AppDelegate.m.

thanks you save my day
