### ISSUE TITLE
Notification sound default/custom react native firebase

### ISSUE THREAD

**Issue by mdrajibsk8** [invertase/react-native-firebase#3573]
Hi, Thanks for this module

I'm using - 

"react": "16.9.0",
"react-native": "^0.62.2",
"react-native-firebase": "^5.6.0",

I'm trying to set a custom notification sound to my app. I have an mp3 file that I'm trying to use as the sound.

I tried adding the mp3 file to the res/raw directory, and then passing the reference to the "setSound" method as a string
.setSound('notifSound.mp3')

I also tried passing a "require" function to the method
.setSound(require('notifSound.mp3'))

but it didn't workout and the default notification sound was played.

I tried to look for a guide in the documentation, but little was said about custom notifications sound.
Any idea on how to make this work?
And also default notification sound is not working as well ?
Please help..

**Comment by mikehardy** [comment]
local notifications APIs are a dead-end on react-native-firebase, and you've not followed the template.

For local notification APIs (like big picture, or sound, or any interaction with notifications at all) you need a separate package as these APIs were removed in react-native-firebase v6 and are unsupported.

There are several options
notifee
react-native-notifications
react-native-push-notifications

But no official support is offered for notifications here, and any time invested in the solution won't have value when you upgrade
