### ISSUE TITLE
🔥Boolean default remote config values are coerced to integers on iOS

### ISSUE THREAD

**Issue by vytautasvargonas** [invertase/react-native-firebase#3576]
## Issue
When setting default remote config values as booleans they are coerced to integers - `true` is coerced to `1` and `false` is coerced to `0` on iOS. No coercion happening on android.
```
import { firebase } from '@react-native-firebase/remote-config';

firebase.remoteConfig().setDefaults({ flag1: true, flag2: false });
console.log(firebase.remoteConfig().getAll());
// {flag1: {value: 1, source: "default"}, flag2: {value: 0, source: "default"}} on iOS
// {flag1: {value: true, source: "default"}, flag2: {value: false, source: "default"}} on android
```
**Expected behaviour**
On both - iOS and android - default remote config values should not be coerced.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/app": "6.4.0",
    "@react-native-firebase/auth": "6.4.0",
    "@react-native-firebase/database": "6.4.0",
    "@react-native-firebase/firestore": "6.4.0",
    "@react-native-firebase/remote-config": "6.4.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 448.15 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: 3.0.4 => 3.0.4
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    create-react-native-app: 2.0.2
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 6.4.0
- **`Firebase` module(s) you're using that has the issue:**
  - remote-config
- **Are you using `TypeScript`?**
  - `Y` & `3.7.4`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by dackers86** [comment]
Thanks @vytautasvargonas.

Added PR at https://github.com/invertase/react-native-firebase/pull/3611
