### ISSUE TITLE
ThenableRef doesn't have .then() method

### ISSUE THREAD

**Issue by nikhilag** [invertase/react-native-firebase#358]
Unlike the web sdk, a thenableRef that I get from `firebase.database().ref(action.path).push() `doesn't have a .then() method. I am using thenableRef to figure out when the update is complete and on web it works perfectly fine but the same code failed here.

### Environment

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): Mac OS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Android Studio
4. React Native version (e.g. 0.45.1): 0.47.2
5. RNFirebase Version (e.g. 2.0.2): 2.1.3

**Comment by Salakar** [comment]
This has already been fixed in the upcoming v3 release, see the upcoming v3 change log on the releases.

**Comment by Salakar** [comment]
The fix to get your code working in the meantime is to use .push() then call a .set on the newly returned reference.

**Comment by nikhilag** [comment]
Thanks a lot @Salakar for fixing this in v3 as well as for the workaround!
