### ISSUE TITLE
How to counting badge in ios using react-native-firebase when app is both closed and in background?

### ISSUE THREAD

**Issue by nziehanp** [invertase/react-native-firebase#3581]
How to know that the localnotification react-native-firebase entering and showing notification badge when the app is closed?

I use : 
-  react-native version 0.58.6
-  react-native-firebase version 5.5.5

I have tried my code and there are no showing up yet both of the badges and the number. Only the status bar arose.

Here are my codes:

```
const notificationOpen = await firebase.notifications().getInitialNotification();
if (notificationOpen) {
  const notificationShow = notificationOpen.notification;
  notificationShow.ios.setBadge(1);
  this.handleNotification(notificationShow);
}
```

For additional info, I got from Apple Developer Documentation written that UILocalNotification deprecated in IoS 10. Should we using UserNotification in appDelegate.m and if it is yes, how to convert them?

 I have tried [https://medium.com/@samuelsuther/handling-notification-badges-with-rnfirebase-io-2acd807d22f9] but turns out that it only worked when the app running in background. Still blank when the app is closed. Is there any mistake in my code? Here are my codes..

```
this.notificationListener = firebase.notifications().onNotification(async notification => {
  let localNotification;
  if (Platform.OS === 'ios') {
    const badgeCount = await firebase.notifications().getBadge(); localNotification = new 
    firebase.notifications.Notification()
      .setSound('bell.mp3')
      .setNotificationId(notification.notificationId)
      .setTitle(notification.title)
      .setBody(notification.body)
      .setData(notification.data);
    localNotification.ios.setBadge(badgeCount + 1);
  }
}
   
this.notificationOpenedListener = firebase .notifications() .onNotificationOpened(async notificationOpen => { 
  const badgeCount = await firebase.notifications().getBadge();
  const notificationShow = notificationOpen.notification; 
  firebase.notifications().setBadge(badgeCount - 1);
  console.log(notificationShow.ios.badge);
  this.handleNotification(notificationShow);
});
```

**Comment by LuigiMaestrelli** [comment]
I'm having the same problem. 
Did you find something?

**Comment by russellwheatley** [comment]
Hi @nziehanp, thanks for your issue report, however we’re no longer actively supporting `<= v5` development so I’m going to go ahead and close this issue - but feel free to continue the discussion if required. Should you have any problems regarding the latest version of React Native Firebase then please raise a new issue.
