### ISSUE TITLE
Can we systematically add release notes with every release

### ISSUE THREAD

**Issue by ssuchanowski** [invertase/react-native-firebase#3582]
This https://rnfirebase.io/releases seems to be lacking a lot.

**Comment by Ehesp** [comment]
The jump from 6.4 -> 6.7 was us breaking out of locked versioning and setting up automated released when something goes into master, so there isn't really many changes to document.

But yeah, we need to sort that out... One of the many tasks!

**Comment by andersonaddo** [comment]
#3518

**Comment by russellwheatley** [comment]
As mentioned by @andersonaddo, this issue is being tracked on #3518, so I'm going to close this one.
