### ISSUE TITLE
🔥 Docs suggest command which in result fails to install dependencies via cocoapod

### ISSUE THREAD

**Issue by Inukares** [invertase/react-native-firebase#3583]
## Issue

This issue is about error with `@react-native-firebase/template` and documentation.
Following `Quick Start` tutorial I ran `npx react-native init --template @react-native-firebase/template MyAwesomeApp` command, which results in:

```sh
error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
Please try again manually: "cd ./MyAwesomeApp/ios && pod install".
```

I followed suggestion and did `cd ./MyAwesomeApp/ios && pod install`, however it didn't help.
Then I tried to reinstall `cocoapods` with `brew`, again with no success.

I realised that maybe specific version of the template should work and I found on npm the following code: 
```sh
npx @react-native-community/cli@next init --template=@react-native-firebase/template@alpha <myProjectName>
```

Which actually successfully installs all dependencies and the template.
I suppose it'd be worth investigating why the template doesn't install correctly with the default method and whether it's worth to replace suggested command on https://rnfirebase.io/.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 6.8.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `template`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by russellwheatley** [comment]
Hey @Inukares, not sure why it failed on your machine. I ran the command `npx react-native init --template @react-native-firebase/template MyAwesomeApp` and it worked fine:
![Screenshot 2020-05-05 at 10 38 36](https://user-images.githubusercontent.com/16018629/81053832-a23b9b80-8ebd-11ea-9662-43cf819b9ddd.png)

**Comment by alexanderswerdlow** [comment]
Also encountered this issue.
