### ISSUE TITLE
App runs on emulator but crashes at launch on device

### ISSUE THREAD

**Issue by eemebarbe** [invertase/react-native-firebase#359]
App runs without issue on emulator (and Firebase works), APK builds successfully, but it crashes on launch on device. Started happening post-Firebase implementation. Not exactly sure what code to show you since I'm not getting any errors locally.

Let me know what code might be relevant and I'll share it.

### Environment

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): OSX
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
4. React Native version (e.g. 0.45.1): 0.43.1
5. RNFirebase Version (e.g. 2.0.2): 2.1.2

**Comment by Ehesp** [comment]
We can't really help here without any logs, as annoying as that sounds it could be anything (even unrelated to this lib). I'd suggest adding a crash library into your app and re-submitting to the play store/users. This will show you what is going on.

I'm going to close this as we really can't help with out more information. We'll happily re-open to once we've got more to work with. Regards.

**Comment by eemebarbe** [comment]
I installed a crash library and it looks like the app crashes before it even has a chance to initialize.

**Comment by wootwoot1234** [comment]
@eemebarbe did you end up solving this?  I'm having the same issue.

**Comment by Ehesp** [comment]
Guys need to see logs from logcat/xcode. We're not wizards!

**Comment by wootwoot1234** [comment]
Sorry about that.  I can only get the app to crash once I've submitted it to the app store and then downloaded it through testlfight.  Then it loads, hangs and then crashes.  Any idea how I can get the logs?

**Comment by Ehesp** [comment]
If you've got the crash module installed it'll log it!

**Comment by wootwoot1234** [comment]
Ok, cool.  I'm installing bugsnag now.  I'll post logs in a few.

**Comment by acro5piano** [comment]
For those who come here, check out this issue:

https://github.com/react-native-community/react-native-maps/issues/2418

in my case, it was helpful.
