### ISSUE TITLE
iOS background notifications not showing

### ISSUE THREAD

**Issue by anunes9** [invertase/react-native-firebase#3590]
## Issue

So I'm implementing push notifications on my app but on iOS the background notifications don't appear on the system tray but with the app open I can receive the notification.

I've searched all the other issues related with this, tried every solution but nothing worked...

Describe your issue here

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
Don't have this file...
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '11.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'HealthHive' do
  # Custom pods
  # pod 'Firebase/Core'
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  use_native_modules!
end
end
```

#### `AppDelegate.m`:

```objc
#import <Firebase.h>
#import <FirebaseMessaging.h>

@implementation AppDelegate
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  
  [FIRApp configure];
  [UNUserNotificationCenter currentNotificationCenter].delegate = self;
  UNAuthorizationOptions authOptions = UNAuthorizationOptionAlert | UNAuthorizationOptionSound | UNAuthorizationOptionBadge;
  [[UNUserNotificationCenter currentNotificationCenter]
      requestAuthorizationWithOptions:authOptions
      completionHandler:^(BOOL granted, NSError * _Nullable error) {
        // ...
      }];

  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
  [application registerForRemoteNotifications];
  
  return YES;
}
  
@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 57.98 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.1.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 21, 23, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom_64
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.60.6 => 0.60.6
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.7.1`
- **`Firebase` module(s) you're using that has the issue:**
  - "@react-native-firebase/app": "^6.7.1"
  - "@react-native-firebase/messaging": "^6.7.1",
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by anunes9** [comment]
I'm closing this... The problem was that I was testing on the simulator and not on an iPhone. When I connected the iPhone the notifications appear... My bad 😞

**Comment by anunes9** [comment]
Maybe add something on the documentation to test it on a real device 😅

**Comment by mikehardy** [comment]
@anunes9 Hi there! There is an edit button on the top right of every documentation page - if there's something that could be more clear or save other developers time, you can always do a quick PR that way - free internet points for all accepted PRs! 🥇

**Comment by Gabsys** [comment]
> I'm closing this... The problem was that I was testing on the simulator and not on an iPhone. When I connected the iPhone the notifications appear... My bad 😞

Hi, do you mind sharing ur react-native-firebase version and code in AppDelegate.M ? I can't get background notification to work and am wondering how did you have it to work? ><

**Comment by anunes9** [comment]
@Gabsys 

Just a reminder, iPhone simulator doesn't receive push notifications.

**react-native: 0.60.6
@react-native-firebase/app": "^6.7.1
@react-native-firebase/messaging": "^6.7.1**

```
#import <Firebase.h>
#import <FirebaseMessaging.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [FIRApp configure];
  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];
}
```
