### ISSUE TITLE
After sending email verification and click... emailVerified still false

### ISSUE THREAD

**Issue by carinlynchin** [invertase/react-native-firebase#3596]
## Issue
After clicking on email verification link, the user emailVerified is false. I even reloaded the user just in case, and it is still false. 

Describe your issue here
After clicking on email verification link, the user emailVerified is false. I even reloaded the user just in case, and it is still false. 
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Ironically I am literally testing this right now in my project.
It works, I just created a new user and verified their email, so this must be something project-specific.
You did not populate the template with the required information so I can't say what's wrong, but I know the module and firebase is working correctly in this area

**Comment by carinlynchin** [comment]
emailed you. Could use some assistance.. been spending hours on this.

**Comment by mikehardy** [comment]
To anyone else following along: never email me. I do public support via github

I recommend using the user changed listener hook provided by firebase.auth()

**Comment by carinlynchin** [comment]
i'm sorry I guess since I saw it available on your profile, i thought it was ok.
