### ISSUE TITLE
How to identify if user is registering/signing up using Phone Auth?

### ISSUE THREAD

**Issue by anjananeema1102** [invertase/react-native-firebase#3600]
firebase
        .auth()
        .signInWithPhoneNumber(this.state.phone)
        .then((confirmResult) => {
          this.setState({ confirmResult });
          this.props.navigation.navigate('OtpScreen', { confirmResult });
        })
        .catch((error) => {
          alert(error.message);
        });
    
I am using above code, `signInWithPhoneNumber` is doing registration & sign in both. But I have a component which I need to display only when user registers.

**Comment by mikehardy** [comment]
You skipped the template, so no idea what version you are on, thus I'll assume it's current
https://rnfirebase.io/reference/auth/additionaluserinfo#isNewUser
https://rnfirebase.io/reference/auth/additionaluserinfo#
