### ISSUE TITLE
'nanopb' pod vulnerability

### ISSUE THREAD

**Issue by OrRosenblatt** [invertase/react-native-firebase#3603]
## Issue

There is an issue reported with `nanopb` pod (affecting `nanopb` package, versions >=0.0.0) which is used by `react-native-firebase`:
https://snyk.io/vuln/SNYK-COCOAPODS-NANOPB-546355

<img width="800" alt="Synk report on nanopb issue introduced by RNFBApp & RNFBMessaging latest versions" src="https://user-images.githubusercontent.com/20166480/80956862-ba061780-8e0a-11ea-92ff-abd5dd1ea24f.png">

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
If you examine your Podfile.lock you'll see these are all transitive dependencies from the firebase-ios-sdk project.
There is an upstream issue / pull request already in that project https://github.com/firebase/firebase-ios-sdk/pull/4264
It should be in the next firebase ios sdk release, which (in my testing) should be fully compatible with react-native-firebase v5 and v6
