### ISSUE TITLE
Ambiguous in root project Candidates are: 'react-native-firebase_app'...."

### ISSUE THREAD

**Issue by barak109** [invertase/react-native-firebase#3606]
I'm using a new react-native init project, after setup all the things in docs and running android i get in android studio Error-

> "Project 'react-native-firebase' is ambiguous in root project 'MyAppName'. Candidates are: 'react-native-firebase_app', 'react-native-firebase_auth', 'react-native-firebase_messaging'."

Env -
```
 "@react-native-firebase/app": "^6.7.1",
  "@react-native-firebase/auth": "^6.7.1",
  "@react-native-firebase/messaging": "^6.7.1",
   "react": "16.11.0",
   "react-native": "0.62.2",
```
Thank you in advance

**Comment by mikehardy** [comment]
Hi there!
Either 1) provide every command line step you took to get to where you are so we can reproduce
or 2) follow the template, so we have the data we need to help

**Comment by mikehardy** [comment]
Incidentally - you might base a reproduction off https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh - it creates a working standalone react-native-firebase project from commands you can see in the script

**Comment by dangnguyen1004** [comment]
> Incidentally - you might base a reproduction off https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh - it creates a working standalone react-native-firebase project from commands you can see in the script

404 - Page not found

**Comment by mikehardy** [comment]
"v6" was a meaningful version when there was a major rewrite of react-native-firebase between v5 and v6, but now we are on v18, the URL is just https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh now :-) - cheers
