### ISSUE TITLE
Android quit state (not running) cannot execute asyn function in messaging().setBackgroundMessageHandler

### ISSUE THREAD

**Issue by CongTM1995** [invertase/react-native-firebase#3607]
I have a problem when receive notify when app in  **quit state** in **android**. I receive data in setBackgroundMessageHandler in fisrt time, app is waked. But enforcement code break when I use axios send request to server, I can't receive response success or error. But when I receive data next time I receive data after send request. Please help me!

**Comment by MichDreby** [comment]
I have the same issue, looks like await for axios() doesn't resolve
