### ISSUE TITLE
Running template command didn't include Firebase packages.

### ISSUE THREAD

**Issue by LukeV111** [invertase/react-native-firebase#3608]
The documentation says that if you run `npx react-native init --template @react-native-firebase/template MyAwesomeApp` you can skip to step 2, but in my case I still needed to run `npm install --save @react-native-firebase/app` (Step 1). 

Documentation is a bit confusing there.

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by dackers86** [comment]
Hi @LukeV111. Do you have a link for the documentation that shows this? I've read through the docs but cannot find those instructions. Thanks!

**Comment by LukeV111** [comment]
Hi @dackers86 - I see that the new documentation no longer includes these steps. Thanks for checking.
