### ISSUE TITLE
SignInWithCustomToken session doesn't persist on restarting the app

### ISSUE THREAD

**Issue by nikhilag** [invertase/react-native-firebase#361]
As per https://github.com/firebase/quickstart-android/issues/31, @samtstern pointed out:-

> Once you've called authWithCustomToken successfully, you stay logged in forever (until you sign out explicitly) so you should be able to get devices to have a long-lived authentication session without minting long-lived custom tokens. 
... on an Android device the session is cached in the SharedPreferences of your application. It should have the same lifecycle as that does, which should definitely persist across device reboots. Unfortunately you can't persist across hard resets.

I signed in the user using `firebase.auth().signInWithCustomToken(token)`. But when I start the app again, firebase.auth().authenticated is false. What is the right way to reuse the existing login session for the user when signed in with custom auth?
(Note that custom token is valid only for 1 hour as per Firebase documentation and hence it can't be stored and then reused later.)

### Environment

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): 
4. React Native version (e.g. 0.45.1): 0.47.2
5. RNFirebase Version (e.g. 2.0.2):  2.1.3

**Comment by chrisbianca** [comment]
@nikhilag You should use `firebase.auth().onAuthStateChanged` to listen for the user's authenticated status on app launch.  This will fire when the app loads and has retrieved the state of the user from the built in Firebase cache.

You can read some more here: https://firebase.google.com/docs/auth/web/manage-users#get_the_currently_signed-in_user
