### ISSUE TITLE
repeatType every minute is not working correctly

### ISSUE THREAD

**Issue by fabioplaka** [invertase/react-native-firebase#3610]
Hello
I am using react-native-firebase@5.6.0 version for pushing notification on iOS. I have a bug in repeatType every minute. The process is in this way: current time is 12:00 and I set the alarm in 12:10 with repeatType: every minute, but the notification will start 12:01. In android works perfectly. I want to mention that this bug occur only with **minute** option on iOS, and in the server everything is ok.
Let me post some piece of code:

           settingReminder(){

             let dataRemind = {
                 time: this.state.time,
                 repeatType: this.state.repeatType,
                 repeatTime: (this.state.timeRepeat).toString()
            }
 
            this.notifyServer(dataRemind)

          }

       notifyServer(remindbody) {
           remindbody.time = moment(remindbody.time).utc().format();

          fetch(getUserUrl() + this.state.id + "/reminders", {
          method: "POST",
          headers: {
              'x-access-token': this.state.token,
              'Accept': 'application/json',
              'Content-Type': 'application/json'
          },
          body: JSON.stringify(remindbody)
          }).then((response) => {
                  Toast.show("Bad request")
          }).then((responseJson) => {
           let data = responseJson.apiresponse;
               if(data){
                  let dataRemind = {
                         time: (data.time).toString(),
                          repeatType: data.repeatType === "" ? null:  data.repeatType,
                          repeatTime: data.repeatTime=== "" ? null: (data.repeatTime).toString()
                      };
                    this.setNotification(dataRemind);
                  }
            }
        })
          .catch((e)=>{
              console.log(e)
          })

          setNotification(dataRemind) {

               const notification = new firebase.notifications.Notification()
              .setNotificationId(dataRemind.localId)
              .setTitle(dataRemind.medical) 
              .setBody(dataRemind.note)
              .android.setPriority(firebase.notifications.Android.Priority.Max)
              .android.setChannelId("reminderLogin")
              .android.setAutoCancel(true);

              this.setReminder(notification);
         }

           setReminder = async (notification) => {
               let dataReminder = {
                     fireDate: (this.state.time).getTime(),
                     exact: true,
                     repeatInterval: 'minute'
               }

              firebase.notifications().scheduleNotification(notification, dataReminder);
          };

**Comment by russellwheatley** [comment]
Hey @fabioplaka, thanks for your issue report. We’re no longer actively supporting `<= v5` development so I’m going to go ahead and close this issue - feel free to continue the discussion if required. Should you have a problem with `>= v6`, please open a new issue.

**Comment by Aung-Myint-Thein** [comment]
@fabioplaka have you found the solution, sir?

**Comment by fabioplaka** [comment]
> @fabioplaka have you found the solution, sir?

Unfortunately no
