### ISSUE TITLE
Make window.crypto available in reactive native for Firestore

### ISSUE THREAD

**Issue by wu-hui** [invertase/react-native-firebase#3618]
Firestore recently merged a change (https://github.com/firebase/firebase-js-sdk/pull/3012) to utilize `window.crypto` for automatic Id generation. This is a change to reduced Id collisions in Firestore.

On reactive native, that change will fall back to the old logic of using `Math.random`, which has higher chance of collision. 

I am requesting react-native-firebase to make `window.crypto` available via `react-native-crypto` package, such at we get the strong random number generator for Id generation.

**Comment by mikehardy** [comment]
@wu-hui I agree with the need but disagree with your choice of package

From https://www.npmjs.com/package/react-native-crypto

```
A suggested workflow:

    Install

npm i --save react-native-crypto
# install peer deps
npm i --save react-native-randombytes
react-native link react-native-randombytes
# install latest rn-nodeify
npm i --save-dev rn-nodeify
# install node core shims and recursively hack package.json files
# in ./node_modules to add/update the "browser"/"react-native" field with relevant mappings
./node_modules/.bin/rn-nodeify --hack --install

    rn-nodeify will create a shim.js in the project root directory

// index.ios.js or index.android.js
// make sure you use `import` and not require!  
import './shim.js'
import crypto from 'crypto'
// ...the rest of your code
```

I see that as a developer and I think...you must be kidding.


[I just went through this recently with the uuidjs package](https://github.com/uuidjs/uuid/issues/375), where they offer guidance here https://github.com/uuidjs/uuid#react-native to use react-native-get-random-values which has a much easier integration path. That is, you just install it and you're done.

So I assert that the react-native-crypto developer experience is unreasonable.
Is there any way to do what you need that has a reasonable developer experience? Would react-native-get-random-values work?

**Comment by mikehardy** [comment]
Also, you assert they merged the change. It does not appear they merged it https://github.com/firebase/firebase-js-sdk/pull/3012

That is no small difference in meaning!

**Comment by wu-hui** [comment]
I agree with you, `react-native-get-random-values` should be good enough.

Also, I thought the change is merged, but then I got more comments, will address that.

**Comment by mikehardy** [comment]
Still not resolved is the idea in #3619 that this may not actually have anything to do with this module. We are wrapping the official Firebase Android SDK and Firebase iOS SDK and do not use the firebase-js-sdk at all, so while you may have a better module to try now, I don't think there is anything that we need to do here as react-native-firebase?

**Comment by wu-hui** [comment]
Yes, I had some misunderstanding of where to post issues and how react-native-firebase works. There is nothing required here, because you are only wrapping native SDKs.

Sorry for the confusion.

**Comment by mikehardy** [comment]
No problem, glad at least you will have a better dev experience with the other package though :-), good luck with your project

**Comment by Salakar** [comment]
Reopening as I'd like to take a look at this in more depth tomorrow - I think the original issue is a valid point given that we do generate ids in JS land still on RNFirebase, using the same bit of logic the web sdk does, or use to (math random) - though I'm not sure we could do anything about crypto support

**Comment by mikehardy** [comment]
Ah - was not aware there was id generation in JS-land. If so then I can only suggest a dependency on react-native-get-random-values then, it's working well for the users of the UUID package including verified success in my projects.
