### ISSUE TITLE
ML Vision autolinking documentation links broken

### ISSUE THREAD

**Issue by MoreSaltMoreLemon** [invertase/react-native-firebase#3620]
## Documentation Feedback

[ML Vision](https://rnfirebase.io/ml-vision/usage) documentation is missing install steps for linking older versions of ios and android:

> If you're using an older version of React Native without autolinking support, or wish to integrate into an existing project, you can follow the manual installation steps for iOS and Android.

The correct documentation exists, however the links themselves are wrong:

ios
existing: https://rnfirebase.io/installation/ios
correct: https://rnfirebase.io/ml-vision/usage/installation/ios

android
existing: https://rnfirebase.io/installation/android
correct: https://rnfirebase.io/ml-vision/usage/installation/android

**Comment by mikehardy** [comment]
PRs happily accepted :-)
