### ISSUE TITLE
registerDeviceForRemoteMessages is not a function

### ISSUE THREAD

**Issue by 15110011** [invertase/react-native-firebase#3626]
I call this func in App.js and it warning this. So I can not get the FCM Token. How do I solve this, is this a bug??
![image](https://user-images.githubusercontent.com/37216098/81368189-56852e00-9119-11ea-
9d12-89a505d51357.png)
Here this code: 
![image](https://user-images.githubusercontent.com/37216098/81368294-9d732380-9119-11ea-9c63-54ff821520e4.png)

* ` "@react-native-firebase/app": "^6.3.4",`
   ` "@react-native-firebase/messaging": "^6.3.4",`
   ` "react-native": "0.61.5",`

**Comment by mikehardy** [comment]
Please do not paste images, paste real code between triple-backticks so formatting is good.
You did not really follow the template.

**Comment by mikehardy** [comment]
Also definitely upgrade to 6.7.1+
