### ISSUE TITLE
heads-up (floating) notification is not getting when app is in background or foreground RN - 0.62.0

### ISSUE THREAD

**Issue by GovindAgarwa** [invertase/react-native-firebase#3627]
Hi 

For Android:-
I am not receiving floating notification on the top of the screen (like a tray) but I am getting data when my app is in background or foreground using method **messaging().setBackgroundMessageHandler()** and also my phone getting vibrate for a very small time when getting a notification at that time My app is killing mode.

should I need to add anything in a manifest file?? because as per document I am not adding anything in my manifest file? Just I am following this way https://rnfirebase.io/

and also not triggered/calling the other 2 methods when the app is in the background or foreground.
**1. messaging().onNotificationOpenedApp()
2.messaging().getInitialNotification()**
I am calling all the method inside **componentDidMount()** in **App.js** page

**React Native version - 0.62.0,
React Version - ^16.11.0**

I have searched a lot and burning my head for the last 3 days. I am looking for a response, thanks in advance.

Thanks
Govind

**Comment by motogod** [comment]
They wrote a library to handle notification.
https://github.com/notifee/react-native-notifee
`notifee` can solve your problem.

Just as they say https://github.com/invertase/react-native-firebase/issues/3564#issuecomment-620605928

**Comment by GovindAgarwa** [comment]
Hi @motogod 

Thanks for your quick reply, I have tried what have you suggested but it's not working for me.

Also, I have installed **react-native-notifications**  library in the project but this is also not working.

I am looking for another solution.
