### ISSUE TITLE
Error: Could not parse Event FE preflight response. react-native admob

### ISSUE THREAD

**Issue by amilaDulanjana** [invertase/react-native-firebase#3628]
I am getting following error when I am trying to get user consent for admob

"Could not parse Event FE preflight response."

```
 const consentInfo = await AdsConsent.requestInfoUpdate([
                'pub-xxxxxxxxxx',
            ]);
```

Please find the screenshot of the error 

![image](https://user-images.githubusercontent.com/16540483/81383136-23e53080-912d-11ea-98b1-ec62fc6e236f.png)

**Comment by mikehardy** [comment]
Please don't post screenshots. Post text.
Please follow the template.

**Comment by amilaDulanjana** [comment]
I posted the error message in text as well. I posted image to show more details of the error.

**Comment by mikehardy** [comment]
> Please follow the template.

**Comment by pietroanello** [comment]
Hi @amidulanjana, have you solved this?

**Comment by mikehardy** [comment]
I think the whole area here has shifted not once but twice, you might try the new native consent frameworks we've wrapped and exposed in react-native-google-movile-ads module
