### ISSUE TITLE
🔥#import <Firebase.h> - 'Firebase.h' file not found after migrating to RN 0.62 and v6

### ISSUE THREAD

**Issue by ram95krishh** [invertase/react-native-firebase#3636]
## Issue
I upgraded my project from RN 0.59.x to 0.62.2 and hence had to upgrade from v5 to v6

I removed the RNFirebase and Firebase/* pods from my podfile as instructed in the v6 migration guide. I removed the whole of node modules. Installed everything again with npm. Also removed the Pods/ directory and ran 
```
pod install --repo-update
```
Now when I try to run the project. It fails at my target's Appdelegate.m in the line where I import Firebase.h. 

![image](https://user-images.githubusercontent.com/45874777/81474569-02b33b80-9224-11ea-8cbd-570085dd6622.png)

---
#### `package.json`:
{
   "dependencies": {
        "react": "16.11.0",
        "react-native": "0.62.2",
        "@react-native-firebase/analytics": "^6.7.2",
        "@react-native-firebase/app": "^6.7.1",
    }
}

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

Am sorry if this doubt is too basic. But is there a new step introduced with respect to this section for v6? Or is this google-services.json? I am trying to figure out what am missing :(

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:
`
platform :ios, '10.0'

target 'targetName' do
    pod 'SwiftyJSON', '4.0.0'
    pod 'Charts', '3.2.0'

    pod 'React', :path => '../node_modules/react-native/'
    pod 'React-Core', :path => '../node_modules/react-native/'
    pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
    pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
    pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
    pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
    pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
    pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
    pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
    pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
    pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'

    # RN 62 upgrade
    pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
    pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
    pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
    pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
    
    pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
    pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
    pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
    pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
    pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
    pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
    pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
   
end
`

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
}
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 215.38 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`@react-native-firebase/app` version you're using that has this issue:**
  - `e.g. 6.7.1`
- **`Firebase` module(s) you're using that has the issue:**
  - Build fails. I use just the Analytics Module
- **Are you using `TypeScript`?**
  - Y - 2.9.1

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You can still use react-native-firebase v5 on react-native 0.62.2, I do so

I don't believe you even need that line in 0.62.2 per the template https://github.com/invertase/react-native-firebase/blob/master/packages/template/project/ios/HelloWorld/AppDelegate.m

You can always try to create a quick throw-away project from scratch to see what the result of a clean install of react-native-firebase v6 looks like, clone and run this: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

**Comment by ram95krishh** [comment]
Thanks for the quick reply! I removed those lines and ran into a different issue. Also, if the step
```
   [FIRApp configure]
```
is no longer required maybe it can be removed from https://rnfirebase.io/#validate-ios-credentials and added to the v6 migration guide to have it removed?

Coming to my issue. Yeah I will quickly try to see if the issue prevails in a fresh throw-away project. as you indicated. Meanwhile, was wondering if you came across this...

It now fails with this message..
```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
library not found for -lRCTBlob
```

**Comment by mikehardy** [comment]
I remember having a seemingly endless string of issues as I upgraded from react-native 0.59 to 0.60+. That looks sort of familiar but I'm not 100% sure. Always try `npx react-native-clean-project` when you see unexpected Xcode errors like this first, as sometimes they are just phantoms related to caching etc

**Comment by ram95krishh** [comment]
Did that, no luck. But yeah, definitely a handy option!
Finally followed this thread and cleared all binaries linked with the libraries in Build Phases and the linker error was resolved: https://stackoverflow.com/questions/59254299/ld-library-not-found-for-lrctblob-clang-error-linker-command-failed

Thanks for your time @mikehardy !! Closing this issue as it is no longer relevant to the migration!
And to folks who end up here attempting the RN 60+ migrations, we feel you! Stay strong! 😄

**Comment by mikehardy** [comment]
Glad that worked - and yes the RN60+ upgrade was painful but unlike some others I have done, once you are on the other side of it, it is really sweet - the auto-linking is not magic (I know exactly how it works) but it feels like magic. So much better than it was up to RN59. Good luck in your project

**Comment by ram95krishh** [comment]
The magic as you pointed out in one of your other comments.. 😄 
https://github.com/facebook/react-native/blob/master/template/ios/Podfile#L2
https://github.com/facebook/react-native/blob/master/template/ios/Podfile#L7

Super curious about the other side! Almost there! Happy coding to you too! 😁👋

**Comment by mash999** [comment]
For me, updating the pod with `pod update` solved the issue.
