### ISSUE TITLE
:fire: When disabling crashlytics auto-collection, not possible to re-enable it after opt-in

### ISSUE THREAD

**Issue by tfoel** [invertase/react-native-firebase#3645]
## Issue

Checking the latest source code, after some days of trying to figure out what's wrong with my project, it seems that the initialization for Android is dependent on the auto-collection-enabled flag.

In other words, if auto collection is disabled by means of `firebase.json`, then Fabric won't get initialized, and then if I enable collection later, calls to `log` and `recordError` will fail with
`Must Initialize Fabric before using singleton()`.
Is it just me then who's trying to do data collection the legal way? :)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [X] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I think it is more that the legal way has moved more rapidly than available maintainer time through the whole toolchain so you're on the leading edge?

Which is really just saying what you said ;-). You're the vanguard - anything you could figure out here and propose as a PR would be most welcome

**Comment by russellwheatley** [comment]
I've made this a feature request as it seems like a reasonable thing to want.

**Comment by andersonaddo** [comment]
@russellwheatley any update on this 👀

**Comment by mikehardy** [comment]
crashlytics PR migrating to firebase crashlytics just merged, so should be open to modification no worries now if anyone wants to start hacking

**Comment by mikehardy** [comment]
I am consolidating all the firebase crashlytics collection stuff in one spot: https://github.com/invertase/react-native-firebase/issues/3879 - we have lots of fundamental information collected there and are near to the point where a fix could be attempted
