### ISSUE TITLE
Detect firebase service update state

### ISSUE THREAD

**Issue by fabiancook** [invertase/react-native-firebase#3647]
## Issue

I am receiving this error here, I want to be able to detect this state before the error is thrown. 

Is this something in the realm of `react-native-firebase`? 

I checked the repo for `SERVICE_UPDATING` and see no handling of this case

```
Error Google Play Services is required to run firebase services on android but a valid installation was not found on this device.

-------------------------
SERVICE_UPDATING: Google Play services is currently being updated on this device. (code 18)
-------------------------

For more information on how to resolve this issue, configure Play Services checks or for guides on how to validate Play Services on your users devices see the link below:

http://invertase.link/play-services 
    index.android.bundle:1306:1004 value
    index.android.bundle:1212:1022 
    index.android.bundle:1212:2372 
    index.android.bundle:1207:2076 
    index.android.bundle:2:1474 v
    index.android.bundle:6:305 
    index.android.bundle:2:1474 v
    index.android.bundle:2:876 d
    index.android.bundle:1331:4 global code
```

---

## Project Files

_Sensitive client information, unable to provide_

### Javascript

_Unrelated to specific Javascript_

#### `package.json`:

```json
"react-native-firebase": "^5.0.0"
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

_Unrelated to iOS_

#### `ios/Podfile`:

- [x] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

:fire:

**Comment by mikehardy** [comment]
On RNFBv5,
https://github.com/invertase/react-native-firebase/blob/v5.x.x/android/src/main/java/io/invertase/firebase/RNFirebaseModule.java#L80
https://github.com/invertase/react-native-firebase/blob/v5.x.x/src/modules/utils/index.js#L39

**Comment by russellwheatley** [comment]
Hey @fabiancook, thanks for your issue report. We’re no longer actively supporting `<= v5` development so I’m going to go ahead and close this issue - feel free to continue the discussion if required. Should you have a problem with `>= v6`, please open a new issue. 

As @mikehardy suggested though, that method in `v5` ought to suit your use case.
