### ISSUE TITLE
JSON value of type NSMutableArray cannot be converted to NSString - Crash due to httpsCallable function

### ISSUE THREAD

**Issue by yash1511** [invertase/react-native-firebase#3649]
## Issue

![image](https://user-images.githubusercontent.com/44857776/81945912-52c34100-961c-11ea-8bbb-0452ee2b31b4.png)

The return value of the ```httpsCallable function``` is causing the crash.
---

### Javascript

```reportThread function```
```javascript
//=============REPORT AND BLOCK===========//

  async function reportThread(tweetId) {
    try {
      const instance = functions().httpsCallable('report');

      const res = await instance({
        tweetId: tweetId,
      });

      console.log('Res: ', res);

      Alert.alert('Thread successfully reported', [{text: 'OK'}]);
    } catch (e) {
      console.log('Error reporting tweet', e);
      Alert.alert('Error reporting tweet', 'Please try again', [{text: 'OK'}]);
    }
  }
```
<p>

#### `package.json`:

```json
"dependencies": {
    "@react-native-community/async-storage": "1.10.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-firebase/app": "6.7.1",
    "@react-native-firebase/auth": "6.7.1",
    "@react-native-firebase/crashlytics": "6.7.1",
    "@react-native-firebase/firestore": "6.7.1",
    "@react-native-firebase/functions": "6.7.1",
    "@react-native-firebase/messaging": "6.7.1",
    "@react-navigation/bottom-tabs": "5.2.8",
    "@react-navigation/native": "5.1.7",
    "@react-navigation/stack": "5.2.14",
    "axios": "0.19.2",
    "moment": "2.25.3",
    "oauth": "0.9.15",
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-actionsheet": "2.4.2",
    "react-native-code-push": "6.2.0",
    "react-native-collapsible-header-views": "1.1.2",
    "react-native-dark-mode": "0.2.2",
    "react-native-fast-image": "8.1.5",
    "react-native-gesture-handler": "1.6.1",
    "react-native-hyperlink": "0.0.19",
    "react-native-onboarding-swiper": "1.1.1",
    "react-native-permissions": "2.1.4",
    "react-native-reanimated": "1.8.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "2.7.0",
    "react-native-twitter-signin": "1.1.1",
    "react-native-vector-icons": "6.6.0",
    "react-redux": "7.2.0",
    "redux": "4.0.5",
    "redux-thunk": "2.3.0",
    "styled-components": "5.1.0",
    "twitter-lite": "0.11.0"
  },
  "devDependencies": {
    "@babel/core": "7.6.2",
    "@babel/runtime": "7.6.2",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.5.1",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.0",
    "react-test-renderer": "16.9.0"
  },
.
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint"
    ]
  }
}
```

</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 64.31 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 6.7.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/functions@6.7.1`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

## Cloud Function being called

```javascript
exports.report = async (data, context) => {
  const tweetId = data.tweetId;

  try {
    const discoverRef = admin
      .firestore()
      .collection('Discover')
      .doc(tweetId);

    const docData = (await discoverRef.get()).data();

    const reportedRef = admin
      .firestore()
      .collection('ReportedTweets')
      .doc(tweetId);

    return admin.firestore().runTransaction(async transcation => {
      return transcation.get(reportedRef).then(doc => {
        if (!doc.exists) {
          return transcation.set(reportedRef, {
            ...docData,
            reported_count: 1,
          });
        } else {
          return transcation.update(reportedRef, {
            reported_count: doc.data().reported_count + 1,
          });
        }
      });
    });
  } catch (e) {
    console.log('Erro reporting Tweet', e);
  }

  return 'OK';
};
```

**Comment by mikehardy** [comment]
Have you used functions successfully in the past? I use functions in my project a lot and they work fine, the implication being this is likely related to a coding error in your project. 

You can always use the automated tests as inspiration https://github.com/invertase/react-native-firebase/blob/master/packages/functions/e2e/functions.e2e.js

Here's a chunk of code I have that works fine?

```typescript

      const calculate = firebase.functions().httpsCallable('calculate');
      console.log('Calculate::calculate - calculating kullkiId: ' + this.state.kullkiId);
      const result = await calculate({
        kullkiId: this.state.kullkiId,
        'Correlation-ID': v4(),
      });
      console.log('Calculate::calculate - received result:', result);
      if (result?.data?.error) {
        console.log('data: ', JSON.stringify(result.data, null, 2));
        console.log('error: ', JSON.stringify(result.data.error, null, 2));
        throw new Error(result.data.error);
      }
      ksocial = result.data.ksocial;
      if (result.data.ksocialAdjusted) {
        ksocial = result.data.ksocialAdjusted;
      }
```

**Comment by yash1511** [comment]
@mikehardy  Yes, I have used functions successfully in another project, and I wrote them in a similar way.
I can't understand why its crashing now.

My code is also similar to yours.

Can it be due to the value I am returning from the cloud function??

**Comment by mikehardy** [comment]
Could be, but that's project-specific experimentation. Might end up being a react-native-firebase issue with parsing but at the same time if you discover something that worked you'd be unblocked while at the same time having something reproducible. It strikes me then that a function-related error report should have full example of the thing passed to the cloud function, and what the cloud function returns...

**Comment by yash1511** [comment]
@mikehardy I have issue with the ```cloud-function``` being called.

**Comment by mikehardy** [comment]
Examples of input / output JSON would be nice to be sure

**Comment by yash1511** [comment]
Input is the ```tweetId``` whose value is a long integer like this ```1002103360646823936
```
Output, I am returning the ```transaction``` in the cloud function, but on logging the response I am getting this:

```
Res:  {
  "data": {
    "_writeBatch": {
      "_firestore": {
        "_settings": {
          "port": 443,
          "firebaseVersion": "8.11.0",
          "clientConfig": {},
          "libVersion": "3.7.5 fire/8.11.0",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/datastore"
          ],
          "servicePath": "firestore.googleapis.com",
          "libName": "gccl",
          "projectId": "threads-1511"
        },
        "_clientPool": {
          "clientFactory": {},
          "concurrentOperationLimit": 100,
          "clientDestructor": {},
          "terminateDeferred": {
            "promise": {},
            "reject": {},
            "resolve": {}
          },
          "terminated": false,
          "maxIdleClients": 1,
          "activeClients": {}
        },
        "_settingsFrozen": true,
        "_backoffSettings": {
          "initialDelayMs": 100,
          "maxDelayMs": 60000,
          "backoffFactor": 1.3
        },
        "_projectId": "threads-1511",
        "_serializer": {
          "createReference": {}
        },
        "_lastSuccessfulRequest": 1589469458487,
        "_preferTransactions": true,
        "registeredListenersCount": 0
      },
      "_ops": [
        {}
      ],
      "_committed": true,
      "_serializer": {
        "createReference": {}
      }
    },
    "_backoff": {
      "_retryCount": 1,
      "maxDelayMs": 60000,
      "jitterFactor": 1,
      "currentBaseMs": 1000,
      "backoffFactor": 1.5,
      "awaitingBackoffCompletion": false,
      "initialDelayMs": 1000
    },
    "_firestore": {
      "registeredListenersCount": 0,
      "_preferTransactions": true,
      "_lastSuccessfulRequest": 1589469458487,
      "_serializer": {
        "createReference": {}
      },
      "_projectId": "threads-1511",
      "_backoffSettings": {
        "backoffFactor": 1.3,
        "maxDelayMs": 60000,
        "initialDelayMs": 100
      },
      "_settingsFrozen": true,
      "_clientPool": {
        "activeClients": {},
        "maxIdleClients": 1,
        "terminated": false,
        "terminateDeferred": {
          "resolve": {},
          "reject": {},
          "promise": {}
        },
        "clientDestructor": {},
        "concurrentOperationLimit": 100,
        "clientFactory": {}
      },
      "_settings": {
        "projectId": "threads-1511",
        "libName": "gccl",
        "servicePath": "firestore.googleapis.com",
        "scopes": [
          "https://www.googleapis.com/auth/cloud-platform",
          "https://www.googleapis.com/auth/datastore"
        ],
        "libVersion": "3.7.5 fire/8.11.0",
        "clientConfig": {},
        "firebaseVersion": "8.11.0",
        "port": 443
      }
    },
    "_transactionId": {
      "0": 17,
      "1": 251,
      "2": 113,
      "3": 100,
      "4": 249,
      "5": 189,
      "6": 43,
      "7": 51,
      "8": 1,
      "9": 34,
      "10": 89,
      "11": 0,
      "12": 220,
      "13": 202,
      "14": 29,
      "15": 178,
      "16": 207,
      "17": 169,
      "18": 16,
      "19": 192,
      "20": 208,
      "21": 115,
      "22": 52,
      "23": 182,
      "24": 66,
      "25": 252,
      "26": 234,
      "27": 162,
      "28": 252,
      "29": 250,
      "30": 20,
      "31": 91,
      "32": 92,
      "33": 167,
      "34": 0,
      "35": 93,
      "36": 99,
      "37": 167,
      "38": 89,
      "39": 114,
      "40": 226,
      "41": 152,
      "42": 251,
      "43": 230,
      "44": 154,
      "45": 60,
      "46": 138,
      "47": 107,
      "48": 243,
      "49": 231,
      "50": 217,
      "51": 142,
      "52": 180,
      "53": 10,
      "54": 21,
      "55": 102,
      "56": 122,
      "57": 14,
      "58": 185,
      "59": 165,
      "60": 71,
      "61": 188,
      "62": 116,
      "63": 247,
      "64": 232,
      "65": 253,
      "66": 134,
      "67": 208,
      "68": 170,
      "69": 44,
      "70": 252,
      "71": 141,
      "72": 52,
      "73": 152,
      "74": 77,
      "75": 144,
      "76": 7,
      "77": 60,
      "78": 2,
      "79": 148,
      "80": 107,
      "81": 147,
      "82": 87,
      "83": 28,
      "84": 122,
      "85": 84,
      "86": 151,
      "87": 70,
      "88": 75,
      "89": 121,
      "90": 39,
      "91": 107,
      "92": 184,
      "93": 32,
      "94": 77,
      "95": 112,
      "96": 211,
      "97": 67,
      "98": 41,
      "99": 242
    },
    "_requestTag": "ZldwI"
  }
}
```

```

**Comment by mikehardy** [comment]
That looks wrong of course.
I see some asyncs, I don't see any awaits. This is a local problem in your function I believe

**Comment by yash1511** [comment]
Okay thanks a lot, I'll try to fix it.

**Comment by Salakar** [comment]
Looks like you're returning the transaction class (and so it's getting serialized into JSON) rather than the actual transaction result.

**Comment by yash1511** [comment]
You are right, thanks
