### ISSUE TITLE
"autoVerifyTimeoutOrForceResend" parameter inside "verifyPhoneNumber" is not working - Timeout occurs always after 30 seconds.

### ISSUE THREAD

**Issue by anandhakumarpalanisamy** [invertase/react-native-firebase#3659]
## Issue

**" autoVerifyTimeoutOrForceResend "** parameter inside **" verifyPhoneNumber "** is not working.
 -  Timeout occurs always after 30 seconds.

**react-native-firebase Versions** 

@react-native-firebase/app": "^7.0.1",
@react-native-firebase/auth": "^7.0.1",

**Comment by jibinb** [comment]
autoVerifyTimeoutOrForceResend not working on version 12.3.0
