### ISSUE TITLE
How can i remove this package?

### ISSUE THREAD

**Issue by IvRRimum** [invertase/react-native-firebase#366]
Android.

Remove package.json
Removed all the android/ enteries with firebase in it. But every time i generate apk i see:
```
:app:prepareComGoogleFirebaseFirebaseAnalytics1021Library
:app:prepareComGoogleFirebaseFirebaseAnalyticsImpl1021Library
:app:prepareComGoogleFirebaseFirebaseAppindexing1021Library
:app:prepareComGoogleFirebaseFirebaseAuth1021Library
:app:prepareComGoogleFirebaseFirebaseCommon1021Library
:app:prepareComGoogleFirebaseFirebaseConfig1021Library
:app:prepareComGoogleFirebaseFirebaseCrash1021Library
:app:prepareComGoogleFirebaseFirebaseDatabase1021Library
:app:prepareComGoogleFirebaseFirebaseDatabaseConnection1021Library
:app:prepareComGoogleFirebaseFirebaseIid1021Library
:app:prepareComGoogleFirebaseFirebaseMessaging1021Library
:app:prepareComGoogleFirebaseFirebaseStorage1021Library
:app:prepareComGoogleFirebaseFirebaseStorageCommon1021Library
```

My package.json:

```
{
  "name": "Myapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "runiPhone5s": "react-native run-ios --simulator=\"iPhone 5s\""
  },
  "dependencies": {
    "@exponent/react-native-action-sheet": "^0.2.1",
    "@remobile/react-native-refresh-infinite-listview": "github:remobile/react-native-refresh-infinite-listview#pull/8/head",
    "react": "15.4.1",
    "react-mixin": "^2.0.2",
    "react-native": "0.38.0",
    "react-native-admob": "^1.1.5",
    "react-native-animation": "^1.0.6",
    "react-native-barcode-scanner-universal": "^1.0.5",
    "react-native-communications": "^2.1.0",
    "react-native-fetch-blob": "^0.10.4",
    "react-native-flurry-analytics": "^1.0.3",
    "react-native-gifted-listview": "github:faridsafi/react-native-gifted-listview#pull/51/head",
    "react-native-loading-container": "^0.4.0",
    "react-native-mail": "^1.5.0",
    "react-native-maps": "^0.12.2",
    "react-native-onesignal": "^1.2.3",
    "react-native-permissions": "git+https://github.com/alextkd/react-native-permissions.git",
    "react-native-share": "^1.0.13",
    "superagent": "^3.1.0"
  }
}
```

**Comment by IvRRimum** [comment]
And if i do a global search in the app, i see that firebase is in android/app/build

**Comment by IvRRimum** [comment]
I have tryed clearing watchdog cache, `react-native unlink react-native-firebase`, `react-native uninstall react-native-firebase`

but its still there...

**Comment by IvRRimum** [comment]
I checked out to older commit, where firebase was definitely not installed.. Its still there when i try to generate apk..

**Comment by IvRRimum** [comment]
I cloned my app from fresh.. Its still there. I am running out of ideas.

**Comment by chrisbianca** [comment]
@IvRRimum You need to remove the firebase libraries from your build.gradle - the logs that you're seeing are from there, nothing to do with RNFirebase...

**Comment by IvRRimum** [comment]
They are already removed from both build.gradle files.

**Comment by chrisbianca** [comment]
What about these entries in your `android/build.gradle` file?

```
classpath 'com.google.gms:google-services:3.1.0'
classpath 'com.google.firebase:firebase-plugins:1.1.1'
```

And this in your `android/app/build.gradle` file?

**Comment by IvRRimum** [comment]
I have none of the above in either of my `build.gradle` files.

**Comment by IvRRimum** [comment]
When i remove my android/app/build, android/.idea and app.im. And run a global search for that project, there is no keywords found "Firebase", "firebase".

As soon as i run a new build - firebase is back!

**Comment by chrisbianca** [comment]
@IvRRimum I'm sorry, but I'm not sure I can help any more.  You've done everything I can suggest and I can't see anything that would indicate this is an issue caused by `react-native-firebase`.

However I will point out that you do have `react-native-admob` specified which will no doubt require Firebase, so this may be the cause of your issues
