### ISSUE TITLE
Analytics: Link to "Building analytics funnel" is no longer valid

### ISSUE THREAD

**Issue by ASchwad** [invertase/react-native-firebase#3661]
## Documentation Feedback

The analytics documentation links to the following URL: https://blog.theodo.com/2018/01/building-google-analytics-funnel-firebase-react-native

Unfortunately, this blog entry no longer exists. I suggest removing it or replacing the reference.
Thanks for your awesome work!

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! Every documentation page has an edit button at the top right - can you propose an edit doing what you suggest?

**Comment by andersonaddo** [comment]
The link you've entered works

**Comment by ASchwad** [comment]
Very strange, if i try opening the URL in Firefox it is failing due to network protocol issues. In Chrome it works fine.
