### ISSUE TITLE
[AdMob] is it possible to persist rewarded video between app closing?

### ISSUE THREAD

**Issue by 6pm** [invertase/react-native-firebase#3662]
I'm working on rewarded video preloading, when user open app I load one video to improve usability. And it recommended by google.
How it works:
```javascript
// call 'createForAdRequest' on root componentDidMount
const video = RewardedAd.createForAdRequest(unit.id)

video.onAdEvent((type, error, reward) => {
    switch (type) {
      case 'closed': {
        // preload next video
        preloadVideo(id);
        break;
      }

      case RewardedAdEventType.EARNED_REWARD: {
        // preload next video
        preloadVideo(id);
        break;
      }

      default:
        break;
    }
  });

  unit.video.load();
```
In my case app downloads each time when user open it. Is it possible to persist video between app open and close lifecycles?
Think storing video instance in 'asyncStorage' is bad idea because video instance is not serialisable.

**Comment by andersonaddo** [comment]
Have you considered react-native-fs?

**Comment by 6pm** [comment]
@andersonaddo no. Any ideas how to combine 'react-native-fs' with 'react-native-firebase/admob'?

**Comment by andersonaddo** [comment]
Not really! But from your comments it looked like you had an idea as to how to integrate AsyncStorage and chose not to. If that's the case, RN-fs should be trivial (unless my assumption is wrong)

**Comment by 6pm** [comment]
@andersonaddo don't think that it's possible to persist via 'react-native-fs' or open rewarded video from fs. Or am I missed something?
Is requested ad removed from user device when app is closed?

**Comment by russellwheatley** [comment]
Hi @6pm, I'm not really sure how to persist a video across an apps open/closed lifecycle. This isn't as such an issue with React Native Firebase so I'm going to close, but feel free to continue discussion, and I hope someone with experience with what you're looking for will help you.
