### ISSUE TITLE
Alternative for firebase.notifications().displayNotification(remoteMessage) in v6.x

### ISSUE THREAD

**Issue by technoknol** [invertase/react-native-firebase#3668]
## Documentation Feedback

I have upgraded from 5.5.x to 6.x but I couldn't find any solution for displaying Local Notification. For advanced documentation suggest `[notifee](https://github.com/notifee/react-native-notifee)` package. Checking the documentation it says it's not for production use yet. 

So what's the alternative of `displayNotification` method ?

**Comment by mikehardy** [comment]
Hi there! I believe notifee is being used in production for a few and should likely go 1.0 to signify that, pushing existing roadmap to 2.0 etc (@Salakar / @Ehesp ? )

There are alternative (react-native-notifications / react-native-push-notification) but they have the same problem v5 of react-native-firebase had - notifications is a huge API surface area and none of those packages are perfect when it comes to supporting the API fully or offering timely support (which is why Notifee exists)

**Comment by abustamam** [comment]
Thanks @mikehardy! Can I request a migration guide for folks using `firebase.notifications()` from RN Firebase 5.x to using Notifee with RN Firebase >=6.x? The reason I ask is that I can't find any way to schedule a notification from _within_ the app. I can make a new issue but it seems related to this. Basically my use case is I want to schedule reminders for a user from within the app (no server) and I was able to do that pretty easily with RN Firebase 5.x but I can't find any documentation on how to do that with Notifee (docs say it's a WIP).

Thanks and I'd be happy to cut a PR for documentation/migration if I ever figure out how to do it!

**Comment by mikehardy** [comment]
A minimal integration of this (just to use the local notification features) seems like it would do it @abustamam https://github.com/zo0r/react-native-push-notification#scheduled-notifications until Notifee has it I think that's the only option, wix/react-native-notifications did not seem to have any scheduling APIs

**Comment by abustamam** [comment]
Ah, got it. Thank you for the clarification! I was gonna drive myself crazy trying to figure out how to do with with RN Firebase. 

(for the record, I inherited this project that used Firebase for local notifications, I didn't like it but I couldn't be bothered to refactor until I had to update to RN 0.62 so I decided to update RN Firebase and here we are :) )

Can I make a PR to add what you just said to the 6+ migration guide? Just to prevent any future issues.

**Comment by mikehardy** [comment]
Yes-  I finally updated from v5 to v6+ yesterday and it was pretty silent on notifications stuff. There *is* a mention there but I think it should be more prominent. Can't say what the Invertase guys will accept - they are picky about wording but it would help to try and they can work through any PR with you. Thanks @abustamam
