### ISSUE TITLE
Current user's creationtime,lastsignintime is wrong

### ISSUE THREAD

**Issue by erhan355** [invertase/react-native-firebase#3671]
## Issue

When you get current user's info, creationtime is different than firebase console value.It seems when you create multiple users on the same android emulator creation time is never updated.
---

### Javascript
 const { currentUser } = auth();
    await currentUser.reload();
let creationTime=currenUser.metadata.creationTime // Returns 2020-04-07T22:28:20Z (UTC)
//In fact I created this user today.
<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment
+-- @react-native-firebase/app@6.3.4
+-- @react-native-firebase/auth@6.3.4
<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
    Memory: 4.47 GB / 15.89 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 27, 28
      Build Tools: 27.0.3, 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
  npmPackages:
    react: 16.8.1 => 16.8.1
    react-native: 0.61.1 => 0.61.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by erhan355** [comment]
I updated to 6.7.1 which is the last version of 6.The issue still exists.

**Comment by mikehardy** [comment]
This won't make a difference in your situation, but v7 is more internal-vesrioning-related than a "major version release". You could/should move all the way to v7.x.x series releases

**Comment by erhan355** [comment]
> This won't make a difference in your situation, but v7 is more internal-vesrioning-related than a "major version release". You could/should move all the way to v7.x.x series releases

I moved to 7.x.x.x latest version ,still same,metadata values are wrong.

**Comment by dackers86** [comment]
@erhan355 Thanks for the info.

I have created a test case which works only when the user has been signed out...

  describe('reload()', () => {
    it.only('Meta data returns as expected', async () => {
      await firebase.auth().signInAnonymously();
      await Utils.sleep(50);
      const firstUser = firebase.auth().currentUser;
      await firstUser.reload();

      await firebase.auth().signOut();

      await firebase.auth().signInAnonymously();
      await Utils.sleep(50);
      const secondUser = firebase.auth().currentUser;
      await secondUser.reload();

      firstUser.metadata.creationTime.should.not.equal(secondUser.metadata.creationTime);
    });
  });

The above test works but only with the signOut function.

Can you provide any more information, for example are you creating the user anonymously?

Are there any records which are different which show the creation time that has not been updated?

**Comment by dackers86** [comment]
@erhan355 Thanks for the information.

I have created a test case which works only when the user has been signed out...

  describe('reload()', () => {
    it.only('Meta data returns as expected', async () => {
      await firebase.auth().signInAnonymously();
      await Utils.sleep(50);
      const firstUser = firebase.auth().currentUser;
      await firstUser.reload();

      await firebase.auth().signOut();

      await firebase.auth().signInAnonymously();
      await Utils.sleep(50);
      const secondUser = firebase.auth().currentUser;
      await secondUser.reload();

      firstUser.metadata.creationTime.should.not.equal(secondUser.metadata.creationTime);
    });
  });

The above test works but only with the signOut function.

Can you provide any more information, for example are you creating the user anonymously?

Are there any records which are different which show the creation time that has not been updated?

Also you mention lastsignintime, but the example code tests for creationTime?

**Comment by dackers86** [comment]
Test cases added at https://github.com/invertase/react-native-firebase/pull/3776

**Comment by erhan355** [comment]
> @erhan355 Thanks for the information.
> 
> I have created a test case which works only when the user has been signed out...
> 
> describe('reload()', () => {
> it.only('Meta data returns as expected', async () => {
> await firebase.auth().signInAnonymously();
> await Utils.sleep(50);
> const firstUser = firebase.auth().currentUser;
> await firstUser.reload();
> 
> ```
>   await firebase.auth().signOut();
> 
>   await firebase.auth().signInAnonymously();
>   await Utils.sleep(50);
>   const secondUser = firebase.auth().currentUser;
>   await secondUser.reload();
> 
>   firstUser.metadata.creationTime.should.not.equal(secondUser.metadata.creationTime);
> });
> ```
> 
> });
> 
> The above test works but only with the signOut function.
> 
> Can you provide any more information, for example are you creating the user anonymously?
> 
> Are there any records which are different which show the creation time that has not been updated?
> 
> Also you mention lastsignintime, but the example code tests for creationTime?

The user creation is via email and password.
const { user } = await auth().createUserWithEmailAndPassword(email, password);
And here is the logout code
await auth().signOut();
In fact all meta data values are wrong.
Can you execute the same scenario with email and password registration ?

**Comment by dackers86** [comment]
@erhan355 Test cases updated for email and password. Tests appear to pass successfully

**Comment by erhan355** [comment]
> @erhan355 Test cases updated for email and password. Tests appear to pass successfully.
> 
> Test cases added at #3776

I think problem causes from firebase itself.As far as I know,they identify device with unique device id.When you create multiple registrations from the same device,I guess they return previous user's lastsignintime and creation time.Anyway, I am closing this issue
