### ISSUE TITLE
Background mode iOS v7.1.0

### ISSUE THREAD

**Issue by 030131550542** [invertase/react-native-firebase#3679]
Today I installed this library and did everything as it written in the documentation. But notification works only on foreground mode. I 
`  var message = {
    "notification": {
      "title":"App Notification",
      "body":"This is to notify you"
    },
    "token": registrationToken
  };

  return admin.messaging().send(message)
    .then((response) => {
      // Response is a message ID string.
      console.log('Successfully sent message:', response);
      res.send("sent")
    })
    .catch((error) => {
      console.log('Error sending message:', error);
      res.send("error")
    });`

I sent like this one. 
![Снимок экрана 2020-05-23 в 21 37 06](https://user-images.githubusercontent.com/33483071/82734569-8e0cf080-9d3d-11ea-9208-5c567e3760aa.png) This is my code for background support, I enabled at Xcode, so don't know what to do. May someone share own AppDelegate file, I confused totally.

**Comment by mikehardy** [comment]
Hi there - you did not follow the template, so we can't really help sorry. Additionally for notifications we are not supporting v5 anymore, this area saw a lot of attention recently which will not be backported, you need to use react-native-firebase >v6.4 for reliable messaging and integrate a local notifications API package
