### ISSUE TITLE
Local notification repeat interval

### ISSUE THREAD

**Issue by Kernael** [invertase/react-native-firebase#368]
RN version : 0.46.1
RNFirebase version : 2.1.3

I want to schedule a local notification that is repeating itself every `repeat_interval` milliseconds, I came up with this code :

```
    firebase.messaging().scheduleLocalNotification({
       title: 'new msg',
      body: 'test',
      sound: 'test',
      priority: 'high',
      icon: 'ic_launcher',
      large_icon: 'ic_launcher',
      vibrate: 300,
      lights: true,
      show_in_foreground: true,
      repeat_interval: "2000",
      fire_date: moment().add(1, 'seconds').valueOf(),
      id: Math.floor((Math.random() * 500) + 0).toString(),
    });
```

but the notification never repeats. It the repeat_interval attribute working with this library ?

**Comment by chrisbianca** [comment]
Currently the library only supports the following intervals:

`year` - iOS
`month` - iOS
`week` - iOS and Android
`day` - iOS and Android
`hour` - iOS and Android
`minute` - iOS and Android

I realise that the documentation is lacking in this area, something that we are doing our best to resolve.  PRs are very welcome!!
