### ISSUE TITLE
Can't log certain properties with analytics().logBeginCheckout

### ISSUE THREAD

**Issue by bmamone** [invertase/react-native-firebase#3681]
## Issue

If `items` attribute is present in `analytics().logBeginCheckout()` the following error is thrown:

`[Error: firebase.analytics().logBeginCheckout(*): unknown property 'items'.]`

`items` should be an accepted parameter according to Google, [here](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event#BEGIN_CHECKOUT) and [here](https://support.google.com/analytics/answer/9268036?hl=en&ref_topic=9267641)

By checking your [docs](https://rnfirebase.io/reference/analytics/begincheckouteventparameters), I have also found out that `coupon` parameter should be accepted.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 7.0.1
- **`Firebase` module(s) you're using that has the issue:**
  - Analytics
- **Are you using `TypeScript`?**
  - No

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by russellwheatley** [comment]
Hey @bmamone, we do have a https://github.com/invertase/react-native-firebase/pull/3385 for analytics that will be updating to the latest analytics API that will be merged in at some point. I'd suggest following that as it has a lot of changes.

**Comment by DanGDroid** [comment]
this still reproduced on `"@react-native-firebase/analytics": "^11.3.3",`
all events that include `items` in params fail with the error example:
Analytics failed sendPredefinedFirebaseEvent` Error: firebase.analytics().logAddPaymentInfo(*): unknown property 'items'.

**Comment by mikehardy** [comment]
https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md#1140-2021-04-29

Yet people are now actually including prices ? https://github.com/invertase/react-native-firebase/pull/5232/files

is it working, or is it not? 🤔

**Comment by habeebtheprogrammer** [comment]
same issue.

**Comment by mikehardy** [comment]
@habeebtheprogrammer please open a new issue if you have a reproduction. This one is closed
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example
https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh + an App.js that reproduces when dropped in result of that
