### ISSUE TITLE
Dynamic Links setting up

### ISSUE THREAD

**Issue by luatnd** [invertase/react-native-firebase#3683]
## Documentation Feedback
I'm integrating Dynamic links into my app, but I cannot find any info describing how to do it in AppDelegate.m in the bellow docs:
https://rnfirebase.io/dynamic-links/usage

This guide seems to relate to v5:
https://github.com/invertase/react-native-firebase-docs/blob/master/docs/links/ios.md

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I believe that's because there's nothing to do in v6. Have you tried it?

**Comment by mikehardy** [comment]
https://github.com/invertase/react-native-firebase/blob/5cda0ddf3cc4e62c253d3d190a6cb089bf2ccc83/packages/dynamic-links/ios/RNFBDynamicLinks/RNFBDynamicLinksModule.m#L38-L46

**Comment by luatnd** [comment]
Thanks, 

As I tested, RNFirebaseLinks does not fire `dynamic_links_link_received` event
 -> `dynamicLinks().onLink(this.handleDynamicLink)`: handleDynamicLink was not triggered.

My app has been using deep link + universal link.
I don't have experience in iOS development, I guess my code prevent RNFBDynamicLinks to handle, here my AppDelegate.m:
```
...
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {

  BOOL handled = [[FBSDKApplicationDelegate sharedInstance] application:application
                                                                openURL:url
                                                      sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                                                             annotation:options[UIApplicationOpenURLOptionsAnnotationKey]
                  ];
  // Add any custom logic here.

  // if dynamic link can handle this link
  // BOOL handleLink = [[RNFirebaseLinks instance] application:application openURL:url options:options]; // comment because I'm using rnfirebase@6

  if(!handled){ // use deeplink
    handled = [RCTLinkingManager application:application openURL:url options:options];
  }

  return handled;
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
  // BOOL handled = [[RNFirebaseLinks instance] application:application continueUserActivity:userActivity restorationHandler:restorationHandler];  // comment because I'm using rnfirebase@6

  BOOL handled = false;
  
  if(!handled) {
    handled = [RCTLinkingManager application:application
                        continueUserActivity:userActivity
                          restorationHandler:restorationHandler];
  }

  return handled;
}
...
```

**Comment by leolusoli** [comment]
Any news about this.

I have the same configuration.
