### ISSUE TITLE
Type issue in RemoteMessage Interface

### ISSUE THREAD

**Issue by samzer** [invertase/react-native-firebase#3687]
## Issue

Describe your issue here
RemoteMessage interface has "data" field in parallel to the "notification" field whereas the payload that I receive from Firebase Notification testing on iOS has "notification" field within "data" field. This raises a typescript warning as data is defined as string.

```json
{
	"from": "3xxxxxx5",
	"data": {
		"notification": {
			"body": "Test Message",
			"title": "Test",
			"e": "1",
			"tag": "campaign_collapse_key_xxxxxxxxxxx"
		}
	},
	"collapseKey": "com.xxxxxxx.xxxxx"
}
```

---

## Project Files

react-native-firebase/packages/messaging/lib/index.d.ts 
### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there, you did not follow the template but I assume this is on master? Could you propose a PR to repair it in the way you think best?

**Comment by samzer** [comment]
So the notification payload that comes in the physical device has the same structure in typescript definition of the master. In the simulator, the payload differs as I stated above. 

This problem is related external to this so closing the issue.
