### ISSUE TITLE
v2: Using providerId vs provider causes 'not enabled' error'

### ISSUE THREAD

**Issue by SamMatthewsIsACommonName** [invertase/react-native-firebase#369]
In the case of Facebook, if I use 'providerId' as the new docs recommend, I get an error from FIrebase saying it's not allowed and that I need to enable it.
If I change it back to 'provider' it works fine.

Just thought it might be useful to point that out. Thanks

### Environment

1. Target Platform (e.g. iOS, Android): ios
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Xcode
4. React Native version (e.g. 0.45.1): 0.47.0
5. RNFirebase Version (e.g. 2.0.2): 2.1.0

**Comment by Salakar** [comment]
@SamMatthewsIsACommonName isn't this because facebook auth is disabled in your firebase console?

**Comment by SamMatthewsIsACommonName** [comment]
@Salakar sorry for the slow reply! No, it is enabled. It works if I use provider, and not if I use providerId. We have been using Facebook this whole time it was only switching to providerId that caused it to stop working.

**Comment by Salakar** [comment]
Could I see how you're using it code wise?

**Comment by SamMatthewsIsACommonName** [comment]
Yesh sure:
Token comes from react native fbsdk

````

const loginToFirebaseWithFacebook = (token, dispatch, navigation) => {
  const credential = {
    provider: 'facebook',
    token,
    secret: 'OOH_SECRET',
  };
  firebase
    .auth()
    .signInWithCredential(credential)
    .then(() => {
      dispatch({
        type: FIREBASE_LOGIN_SUCCESFUL,
      });
    })
    .catch((err) => {
      errorReporting.reportError(
        'Error logging into Firebase with Facebook credential',
        '00003',
        err,
      );
      navigation.navigate('LoginHome');
      dispatch({
        type: FIREBASE_LOGIN_ERROR,
        error: err,
      });
    });
};
````

**Comment by chrisbianca** [comment]
@SamMatthewsIsACommonName I believe I've resolved this issue on v3.  It's not a straightforward back port, and we're focused on getting v3 out of the door at the moment so I'm going to hold off doing this on v2 if possible!

By the way, you can and probably should construct the credential as:
```
firebase.auth.FacebookAuthProvider.credential(token, 'OOH_SECRET');
```

This will hide the internal representation from you and will work across both v2 and v3.
