### ISSUE TITLE
Android 7.0 - Auth is not working with version firebase 7.1.0

### ISSUE THREAD

**Issue by keremcubuk** [invertase/react-native-firebase#3693]
## Issue

I'm developing a react-native app and I upgrade the version of firebase 7.1.0 from 6.7.1 after update the packages. I realized that it wasn't working. When I try to email login nothing happen. However, It works Android API 26,28,29 and IOS 13 which I've tested.

```javascript
import auth from '@react-native-firebase/auth';

  const handleSignIn = () => {
    auth()
      .signInWithEmailAndPassword(userEmail, userPass)
      .then(response => {
        console.log(response);
      })
      .catch(error => {
        console.log(error);
      });
  }
```
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "dependencies": {
    "@react-native-community/async-storage": "^1.10.3",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-firebase/app": "^7.1.0",
    "@react-native-firebase/auth": "^7.1.0",
    "@react-native-firebase/firestore": "^7.1.0",
    "@react-navigation/bottom-tabs": "^5.4.7",
    "@react-navigation/native": "^5.4.2",
    "@react-navigation/stack": "^5.3.9",
    "axios": "^0.19.2",
    "buffer": "^5.6.0",
    "i18next": "^19.4.4",
    "immer": "^6.0.8",
    "native-base": "^2.13.12",
    "react": "^16.13.1",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-picker": "^2.3.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-localize": "^1.4.0",
    "react-native-safe-area-context": "^2.0.0",
    "react-native-screens": "^2.8.0",
    "react-native-vector-icons": "^6.6.0",
    "react-redux": "^7.2.0",
    "redux-saga": "^1.1.3",
    "reselect": "^4.0.0",
    "stream": "0.0.2",
    "xml-js": "^1.6.11"
  },
  "devDependencies": {
    "@babel/core": "7.7.2",
    "@babel/runtime": "7.7.2",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "babel-plugin-module-resolver": "3.2.0",
    "eslint": "6.6.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.3",
    "plop": "^2.6.0",
    "react-test-renderer": "16.9.0"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 22.10 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 28.0.0, 28.0.3, 29.0.0
      System Images: android-24 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.13.1 => 16.13.1 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-rename: 2.4.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 7.1.0
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - N

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
"is not working" -> do you have some evidence? results of API calls that differ (with specifics)? Some adb logcat or Xcode log trace?

**Comment by mikehardy** [comment]
Also - the firebase SDKs should have updated. You skipped that part of the template. Make sure you have the current stable Firebase SDKs in android and iOS and try `npx reat-native-clean-project` to blow out old state from the upgrade

**Comment by keremcubuk** [comment]
I have tried the clean project with `npx react-native-clean-project`. In my android logcat, I'm getting this error.

**Not Working Version:**
> API 24: Android 7.0

```shell
21705-21705/com.myapp W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
21705-21705/com.myapp W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
21705-21783/com.myapp D/Auth: signInWithEmailAndPassword
21705-21783/com.myapp I/BiChannelGoogleApi: [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@c64e91e
21705-21739/com.myapp W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
21705-21739/com.myapp W/GooglePlayServicesUtil: Google Play services out of date.  Requires 12451000 but found 11743470
```
---

**Working Version**

> API 26: Android 8.0

```shell
21594-21734/com.bookbase D/Auth: signInWithEmailAndPassword
21594-21734/com.bookbase I/BiChannelGoogleApi: [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@86d3251
21594-21634/com.bookbase D/FirebaseAuth: Notifying id token listeners about user ( bce60LNMepTC1ahAgt8Kszyz3S43 ).
21594-21634/com.bookbase D/FirebaseAuth: Notifying auth state listeners about user ( bce60LNMepTC1ahAgt8Kszyz3S43 ).
21594-21594/com.bookbase D/Auth: addAuthStateListener:eventBody { NativeMap: {"user":{"metadata":{"lastSignInTime":1590693994116,"creationTime":1588535472183},"providerData":[{"email":"keremcubuk@hotmail.com","phoneNumber":null,"photoURL":null,"displayName":"Kerem Çubuk","uid":"keremcubuk@hotmail.com","providerId":"password"}],"phoneNumber":null,"photoURL":null,"displayName":"Kerem Çubuk","email":"keremcubuk@hotmail.com","isAnonymous":false,"emailVerified":false,"providerId":"firebase","uid":"bce60LNMepTC1ahAgt8Kszyz3S43"},"appName":"[DEFAULT]"} }
```

I've just only implemented gms and firebase analytics manually. All other, firebase features are autolinked.

**android/build.gradle**

```shell
dependencies {
    classpath("com.android.tools.build:gradle:3.4.2")

     // Firebase
    classpath 'com.google.gms:google-services:4.3.3'
}
```

**android/app/build.gradle**

```shell
dependencies {
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
}
```

I think these information help us for resolve problem 😃

**Comment by mikehardy** [comment]
device play services out of date according to your android 7.0 log. How does it go when you follow the natural path from the log message (updating play services)?

**Comment by keremcubuk** [comment]
I reset the device by making wipe data. The problem persisted. I then logged in with my Gmail account. I updated "**Google Play Services**" on Google play and it worked.

<img width="368" alt="Screen Shot 2020-05-28 at 23 36 34" src="https://user-images.githubusercontent.com/29661833/83191087-27704400-a13c-11ea-83a3-678555cc67f7.png">

I am curious about **users who have not made this update on their phones**. Any idea about this case?

**Comment by mikehardy** [comment]
users update that normally, I've not seen it happen in the wild.
If you want to make sure then for react-native-firebase v6+ you are waiting on this PR 
https://github.com/invertase/react-native-firebase/pull/3601

Or you can use this from my rn-update-apk module (which is useful in that it patches SSL on older devices anyway) 

https://github.com/mikehardy/react-native-update-apk/blob/4bda32ee7b935a2e845601b62740a55f80c78297/example/App.js#L116-L137
