### ISSUE TITLE
onNotificationOpenedApp is not working on Android

### ISSUE THREAD

**Issue by 15110011** [invertase/react-native-firebase#3695]
Everything works well on the IOS device but Android not, on Android device it still receives notification but when pressing the noti, then the app opens itself but onNotificationOpenedApp function is not run. 
Package in used:
```
    "@react-native-firebase/app": "^7.1.0",
    "@react-native-firebase/messaging": "^7.1.0",
    "react-native-push-notification": "^3.5.1",
    "@react-native-community/push-notification-ios": "^1.2.0",
```

**Comment by Newbornbird** [comment]
Hello, I had same problem.
My problem was in SplashActivity file.
Do you use it?

**Comment by roni-castro** [comment]
I also had this problem and it was caused by the lib `react-native-splash-screen` as mentioned on this [thread](https://github.com/invertase/react-native-firebase/issues/3469#issuecomment-614990736), because it receives the push Intent on Android, but do not pass it to the MainActivity. If I understood right, this callback is just called when the app is on background state, not on foreground or in quit state, so to handle the notification on the quit state you will have to use the `getInitialNotification`, but for the `foreground` state I don't think there's a way to identify that the notification was tapped when the app as someone else also [reported](https://github.com/invertase/react-native-firebase/issues/3502) this problem

**Comment by 15110011** [comment]
@Newbornbird  Thanks, I solved this, so now I get a new problem that every I push a new notification from firebase console the onNotificationOpenedApp function run automatically one time with no data. When I press the notification o the notification panel of the device it will run onNotificationOpenedApp function with data. So how can I force first running this function when receiving notification from the firebase console?

**Comment by ghasemikasra39** [comment]
same here:
```
    "@react-native-firebase/analytics": "^7.1.0",
    "@react-native-firebase/app": "^7.1.0",
    "@react-native-firebase/auth": "^8.0.0",
    "@react-native-firebase/crashlytics": "^7.1.0",
    "@react-native-firebase/firestore": "^7.1.0",
    "@react-native-firebase/messaging": "^7.1.1",
```
Any solution?

**Comment by ghasemikasra39** [comment]
Dear @roni-castro
I am using  `react-native-splash-screen ` and facing this issue.
Can you confirm that by removing this package this issue will be solved?

**Comment by mikehardy** [comment]
@ghasemikasra39 https://github.com/crazycodeboy/react-native-splash-screen/issues/289#issuecomment-502406454

**Comment by russellwheatley** [comment]
Feel free to continue the discussion, but this is not an issue/bug with React Native Firebase.

**Comment by ZaikinaEvgeniya-2** [comment]
"@react-native-firebase/app": "^8.4.6",
"@react-native-firebase/messaging": "^7.9.1",
"react-native-push-notification": "^6.1.1",
"@react-native-community/push-notification-ios": "^1.6.1",

I see notification from Cloud Message in background, but `onNotificationOpenedApp` `onMessage` functions are not run in foreground

**Comment by mikehardy** [comment]
@ZaikinaEvgeniya-2 no comments here will receive attention. It's a closed issue nearly half a year, new issue with full template

**Comment by anupamhore** [comment]
> Feel free to continue the discussion, but this is not an issue/bug with React Native Firebase.

How are you so sure.. when many of us are facing this issues....

**Comment by mikehardy** [comment]
Because I personally use it. I have watched my apps logs on device and seen it work. That leads me to believe it is working

**Comment by datachanturia** [comment]
@mikehardy thanks react-native-splash-screen uninstall helped 👀
