### ISSUE TITLE
Using ":" in values for queries like "startAt" results in wrongly passed data and errors

### ISSUE THREAD

**Issue by DavidKuennen** [invertase/react-native-firebase#37]
The reason behind this seems to be, that the query array is split by ":", so when passing a time value for example, it breaks.

![react-native-firebase-bug](https://cloud.githubusercontent.com/assets/7766565/24676526/9912aaec-1983-11e7-9f59-17ca4aed6ffd.png)

**Comment by Salakar** [comment]
@DavidKuennen database will be getting re-done shortly, will no longer use strings to store queries like this, definitely will be fixed.

@Ehesp this is another thing that's broken in current implementation 🙈

**Comment by DavidKuennen** [comment]
Thanks. I really like this lib so far. Keep up the good work. :smile:

**Comment by chrisbianca** [comment]
This should be resolved as of 1.0.0-alpha13.
Please let us know if you're still having issues once you've updated.

**Comment by esdrasportillo** [comment]
I am not sure if it is related, but for queries using startAt on iPhone5 (either real device or simulator) doesn't work.

I am testing using the same user, the same piece of code, it works on Android, on iPhone 6, but doesn't work on iPhone 5.

Has anyone ever tested on an iPhone 5 before and got this error? I am on 1.0.0-alpha13.

**Comment by chrisbianca** [comment]
I can't think of a reason why the behaviour would be different on an iPhone 5 instead of an iPhone 6. Has the iPhone 5 definitely been updated with the latest version of the RNFirebase library?

**Comment by esdrasportillo** [comment]
Me too. I can't understand it. 

I am just changing the simulator in Xcode and works on every iPhone, but the 5.

**Comment by chrisbianca** [comment]
Have you tried "Resetting content and settings" on the iPhone 5 simulator?  Just in case something has got cached

**Comment by esdrasportillo** [comment]
Just did it and didn't work...
If the child I am trying to query is a string it works, but if it is a number so it doesn't work.
But what is funny for me is that it doesn't happen in other devices...
