### ISSUE TITLE
Events for Firebase Messaging to use with redux-observable and rxjs

### ISSUE THREAD

**Issue by nikhilag** [invertase/react-native-firebase#370]
I am using redux-observable and RxJS in my react native app and I was writing an epic to handle token refresh for cloud messaging when I realized that there is no `on` method in `RNFirebase.messaging.Messaging` interface. I need to add listeners for `onTokenRefresh` and `onMessage` and I would prefer to do it via `Observable.fromEvent()` which only seems to work with events.

Can we introduce `.on()` method on `RNFirebase.messaging.Messaging` interface with `token_refresh` and `on_message` events?

(Please note that using database events with code like `Observable.fromEvent(firebase.database().ref(action.path), 'child_added')` works perfectly fine for me.)

### Environment

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): Mac OS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
4. React Native version (e.g. 0.45.1): 0.47.2
5. RNFirebase Version (e.g. 2.0.2): 2.1.3

**Comment by chrisbianca** [comment]
@nikhilag Sorry for the delay on this one.  We've discussed this internally and we're not likely to expose a method specifically for use in third party libraries as it starts opening a can of worms.

You could get this working by tacking into some of the internals of the messaging module.  In v3, each module has an event emitter that you could use.

**Comment by altenorjr** [comment]
Looks like you're looking for the bindCallback operator. You should give it a try.

**Comment by ajcrites** [comment]
This worked for my use case and may be useful for some other people (using TypeScript but should also apply in JavaScript):

```
this.readSubscription = fromEventPattern<DataSnapshot>(
    (handler: () => any) => notesRef.on('value', handler),
    (handler: () => any) => notesRef.off('value', handler),
).subscribe();
```
