### ISSUE TITLE
remoteMessage from setBackgroundMessageHandler

### ISSUE THREAD

**Issue by KovalovIE** [invertase/react-native-firebase#3703]
Hello! I am use react-native-firebase v6. 
How can I not show a notification from setBackgroundMessageHandler? 
I tried to return null or Promise.resolve({}), but I always see a notification from firebase.
For local notification in foreground I use react-native-push-notification and I want to use the same local notification in background.
At the moment I can show a local notification in background, but it is displayed along with the notification from firebase, and I аm looking for an opportunity to remove notification from firebase.

**Comment by andersonaddo** [comment]
That means the notification data you're sending to FCM has a `notification` property. That, by default, will trigger a push notification when received. If you don't want this behavior, remove the `notification` property and put all your data in the `dats` field if the object. Then, your local push notification package will handle the rest. 

This is all explained in Firebase's documentation, I believe it's also mentioned in RNFB's docs too

**Comment by KovalovIE** [comment]
Thanks for the answer, try to do.
