### ISSUE TITLE
Firebase v5 crashlytics not working on iOS

### ISSUE THREAD

**Issue by latusdenis** [invertase/react-native-firebase#3704]
## Issue
Hello! I'm having an issue installing Firebase v5 Crashlytics for iOS, on Android it's working perfectly.

Here are the steps, I've followed from v5 docs:
1. pod 'RNFirebase/Crashlytics', :path => '../node_modules/react-native-firebase/ios'
2. pod install
3. ![image](https://user-images.githubusercontent.com/34662936/83135397-72fc0100-a0ee-11ea-8d2b-2e7bd305310a.png)

Describe your issue here
The crashes aren't appearing on Firebase and I'm seeing:
![image](https://user-images.githubusercontent.com/34662936/83135812-13522580-a0ef-11ea-829a-67ca63844b9f.png)

## Environment

<details><summary>Click To Expand</summary>
<p>

**System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 559.22 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
**
- **Platform that you're experiencing the issue on**:
  - [x] iOS
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.6.0`
- **Are you using `TypeScript`?**
  - Y, 3.7.4

</p>
</details>

**Comment by andersonaddo** [comment]
How long have you waited?
Sometimes they take a while to show for iOS.

**Comment by latusdenis** [comment]
@andersonaddo almost 2 days have passed. I'm wondering if I need to do some extra setup which is missing in the docs?

**Comment by andersonaddo** [comment]
Another question to ask is whether you're testing crashlytics with a debug build. I'm not sure about v5, but with v6 of this package, crashlytics is disabled by default for debug builds (this can de changed, instructions for that are in the docs)

**Comment by latusdenis** [comment]
@andersonaddo Testing on iOS real device, building from XCode using release schema and crashing the app using `firebase.crashlytics().crash();`.

**Comment by andersonaddo** [comment]
Alrighty, this is where I tap out 😂. 
Hopefully someone with more Crashlytics experience will see this issue and help. 
All the best

**Comment by mikehardy** [comment]
Crashlytics definitely works with v5 but v5 is no longer supported
Sample integration https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh but of course there is nothing to actually do for the iOS side
Classic issue about bitcode and dsyms meaning you'll never get stack location https://stackoverflow.com/a/55796619/9910298

Has to be release mode. Have to restart the app after crash. Have to make sure all the docs are followed and :shrug: it works

v5 is not supported though so other than the advice above you'll have to inspect your project, sorry - the answer is in there somewhere

**Comment by latusdenis** [comment]
@mikehardy I think that the problem is that the SDK wasn't installed properly?
![image](https://user-images.githubusercontent.com/34662936/83156590-45718080-a10b-11ea-904c-9a03afd867b9.png)

What could be the case if I followed all instructions from the docs?

**Comment by mikehardy** [comment]
That's just Google guessing. Try a sample / throwaway app. Test then re-test, I don't know. V5 is not supported, I will not respond further, sorry
