### ISSUE TITLE
Email verification failed in android

### ISSUE THREAD

**Issue by Badal1234** [invertase/react-native-firebase#3707]
## Issue

Describe your issue here ` auth()
      .currentUser.sendEmailVerification({
        handleCodeInApp: true,
        url: '',
        android:{
          installApp:true,
          packageName:''
        }
      })
      .then(data => {
        
      });`

The verification email has arrived but it did not verify my email.
But when I did it with out android method ,the email got verified

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
No template
Try using the onAuthChanged listener. Email verification does work, https://rnfirebase.io/auth/usage#listening-to-authentication-state

**Comment by Badal1234** [comment]
Not working.
I think the verification link redirects to application without verify the email.

**Comment by mikehardy** [comment]
Works fine, and I have just as much evidence as you have posted here to support my assertion (i.e., none).

But seriously, it works. If you use their default verifier you'll see a boring firebase web app open when you click the verify email, and the implementation of that toggles the auth state in the cloud.

Then if you refresh the user in the app (I have the app do that with a button plus I also listen to AppState) the auth state change listener is called and it's verified.

I will not respond further, it definitely works, and you've not provided any evidence otherwise
