### ISSUE TITLE
getting compile errors after following the initial setup

### ISSUE THREAD

**Issue by WaqqaR** [invertase/react-native-firebase#371]
Im Getting the following errors when I run run-android:

E:\Big Idea\BigIdea100\BigIdea100\node_modules\react-native-firebase\android\src\main\java\io\invertase\firebase\messaging\RNFirebaseMessaging.java:34: error: RNFirebaseMes
saging is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class RNFirebaseMessaging extends ReactContextBaseJavaModule implements LifecycleEventListener, ActivityEventListener {
       ^
E:\Big Idea\BigIdea100\BigIdea100\node_modules\react-native-firebase\android\src\main\java\io\invertase\firebase\messaging\RNFirebaseMessaging.java:262: error: method does
not override or implement a method from a supertype
  @Override
  ^
E:\Big Idea\BigIdea100\BigIdea100\node_modules\react-native-firebase\android\src\main\java\io\invertase\firebase\messaging\RNFirebaseMessaging.java:267: error: method does
not override or implement a method from a supertype
  @Override
  ^
Note: E:\Big Idea\BigIdea100\BigIdea100\node_modules\react-native-firebase\android\src\main\java\io\invertase\firebase\auth\RNFirebaseAuth.java uses or overrides a deprecat
ed API.

My build.gradle 
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.google.gms:google-services:3.0.0'
        
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
            url "https://maven.google.com"
        }
    }
}
`

**Comment by Ehesp** [comment]
Please format your code and provide the required information in the issue template, thanks.
