### ISSUE TITLE
Monorepo and forking

### ISSUE THREAD

**Issue by prasanthsd** [invertase/react-native-firebase#3712]
I would like to fork this repo and make some changes to the messaging module and then include that in my project. But the fact that this is a mono repo makes it difficult and npm does not allow you to include a subfolder of the forked repo into the project. Are there any workarounds for this?

**Comment by mikehardy** [comment]
fork, local publish via gitpkg so you can set it as a dependency, I think is it https://github.com/ramasilveyra/gitpkg

**Comment by mikehardy** [comment]
You can also just use patch-package

**Comment by prasanthsd** [comment]
Thanks for patch-package. Never knew such a thing existed.
