### ISSUE TITLE
stops receive silent push messages in setBackgroundMessageHandler if app was in background more then 15 minutes

### ISSUE THREAD

**Issue by bmp123** [invertase/react-native-firebase#3713]
## Issue
stops receiving messages if the application is in the background for more than 15 minutes. Perhaps this is due to the fact that the js thread is paused? How can I receive silent push notifications in background always?

"@react-native-firebase/messaging": "^7.1.0"

### Javascript
messaging().setBackgroundMessageHandler(async remoteMessage => {
  Logger.log('BackgroundMessage', JSON.stringify(remoteMessage));
  try {
    BackgroundTimer.setTimeout(() => {
      new GetWebrtcConnect(store.dispatch);
    }, 10);
  } catch (e) {
    Logger.error('BackgroundMessage', e);
  }
});
AppRegistry.registerComponent(appName, () => AppRoot);
### firebase request body
{
 "to" : ...,
 "content_available": true,
 "priority": "high",
 "apns":{
         "headers":{
            "apns-priority":"5",
            "apns-push-type":"background"
         },
         "payload":{
            "aps":{
               "content-available":1
            }
         }
      },
	 "data" : {
	 	"type":"call"
	 }
}

**Comment by andersonaddo** [comment]
I believe this has to do with certain brands of phones and how they handle battery optimization. 
You might want to look into that, I know its an pest for some people

**Comment by mikehardy** [comment]
dontkillmyapp.com - also no template...

**Comment by bmp123** [comment]
I see this only on iOS ((

**Comment by mikehardy** [comment]
Open a new issue, post complete details, ideally a full reproduction sample app on github. Also watch logs in Xcode running on a real device. This issue is closed though because you fully ignored the template, so I won't respond further, sorry

**Comment by bmp123** [comment]
@mikehardy https://github.com/invertase/react-native-firebase/issues/3724
