### ISSUE TITLE
Notification doesn't show in android notification bar when app is in fore ground

### ISSUE THREAD

**Issue by imansalhi** [invertase/react-native-firebase#3717]
## Issue

when the app is in background the notification is showing on android notification bar Yet it doesnt work when app is in fore ground....it means Notification doesn't show in android notification bar when app is in foreground state.
whats the solution for that?

```
conponentDidmount(){
messaging().onMessage(async remoteMessage => {
            
        //  event  this will happened when the notification is received but it does not show in notification bar 
        });
}
```
---
i use react-native 0.61.5
react-native-firebase V6  

and i am not using react hook

**Comment by mikehardy** [comment]
That is intended behavior. The SDKs from google do not show notificiation payloads when the app is foreground

**Comment by imansalhi** [comment]
@mikehardy i use react native firebase v5 i can see the notification in notification bar while the app is in foreground state
