### ISSUE TITLE
Set custom data by admob rewarded adv (SSV)

### ISSUE THREAD

**Issue by derRinat** [invertase/react-native-firebase#3722]
Hey guys,
currently need to validate rewarded admob adv on server side (https://developers.google.com/admob/android/rewarded-video-ssv).  Do you plan to add possibility to set custom data on adv request? (request id, user id etc.)

**Comment by mikehardy** [comment]
I think the crew is pretty busy right now, I would propose a PR that implements the required functionality if you need it

**Comment by kostiantyn-solianyk** [comment]
any updates on this issue? Also need this functionality.

**Comment by mikehardy** [comment]
@kostiantyn-solianyk PRs happily merged

**Comment by kostiantyn-solianyk** [comment]
ok, thanks, but is there any documentation or how to use it, because in index.d.ts I can't find anything with customData?

**Comment by kostiantyn-solianyk** [comment]
And also there is no `customData` in `RequestOptions`

**Comment by derRinat** [comment]
> And also there is no `customData` in `RequestOptions`, and there is no `setCustomData` in class `RewardedAd`

also can't find it...

**Comment by kostiantyn-solianyk** [comment]
@mikehardy so, any news?

**Comment by mikehardy** [comment]
@kostiantyn-solianyk PRs happily merged, it is *open source* everyone, there is not a magical fairy that goes around fixing your problems for you, you need to roll up your sleeves and fix the ones that interest you most, while enjoying the fixes from everyone else. You appear to the be the most interested here.

**Comment by kostiantyn-solianyk** [comment]
@mikehardy What?! Your answer is not even related to what we discussed above. You said that `PR happily merged`. So, it means that everything should be ok. But no, there is no working functionality, there is nothing actually. And as I said `there is no customData in RequestOptions, and there is no setCustomData in class RewardedAd` - so it means I did a research, so the question is what was merged? It's not only my issue, I see many people who ask the same.

**Comment by mikehardy** [comment]
"PRs happily merged" means: code the solution, propose a PR, it will be reviewed and happily merged

**Comment by derRinat** [comment]
@mikehardy What? Agree with @kostiantyn-solianyk  There is no requested/announced, please provide commitId or PR if it was merged

**Comment by mikehardy** [comment]
@iAmGhost wins the internet today with an actual PR to implement the functionality! :trophy: 

That's how open source works. Now we have a PR proposed, we can review it and hopefully everyone gets to enjoy the new functionality.

@kostiantyn-solianyk / @derRinat any help reviewing would be much appreciated and will probably speed things up for you as it will likely help the PR merge faster

**Comment by kostiantyn-solianyk** [comment]
@iAmGhost Thank you, I'll review and help check all the use cases for the functionality as soon as I can.

**Comment by mikehardy** [comment]
@kostiantyn-solianyk excellent! that will help

I've been working on CI here and one of the things I'll try to get together is that for each PR a set of patch-package files is generated so testing is easier - right now with the monorepo setup it's not very easy to test things.

It is possible though, if you pull the PR branch and just copy the files in (thankfully few in number)

**Comment by mikehardy** [comment]
@kostiantyn-solianyk @derRinat this is released, please test - if there's anything missing, 'PRs happily merged' ;-), and you can see how fast it can move when that happens

@iAmGhost fantastic work
