### ISSUE TITLE
unable to get push notification in kill and foreground state in latest version 7+ in react native

### ISSUE THREAD

**Issue by anshumanburman** [invertase/react-native-firebase#3726]
i am trying to integrate latest version of react-native-firebase  in my latest version react native project but only getting notification in background state not in quite(kill) and foreground state in android device.
```
"dependencies": {
    "@react-native-firebase/app": "^7.1.4",
    "@react-native-firebase/messaging": "^7.1.3",
    "react": "16.11.0",
    "react-native": "0.62.2"
  }
```

**Comment by mikehardy** [comment]
no template
