### ISSUE TITLE
analytics().setUserId is sometimes working

### ISSUE THREAD

**Issue by johantenghamn** [invertase/react-native-firebase#373]
Having trouble with analytics().setUserId(). Running on android, react-native 0.44.0 and RNFirebase 2.1.2.

`console.log('auth id::', auth.uid);`
`firebase.analytics().setUserId(auth.uid);`

The console.log() is always called but only occasionally I get an event in the firebase debugview.

**Comment by Ehesp** [comment]
This is a really simple call which gets piped directly to Analytics, so if there is an issue it has to be with the Native SDK. One thing though, if the user ID hasn't changed for a period of time it may not bother to update it.

https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/analytics/RNFirebaseAnalytics.java#L85

**Comment by johantenghamn** [comment]
Ok, seems to be working now, just took some time until the event popped up in the debugview :)
Thanks for the response!

One more question. How do I unset the user id? I'v tried with 
`firebase.analytics().setUserId(null)` 
and 
`firebase.analytics().setUserId('')`

**Comment by chrisbianca** [comment]
Check out: https://firebase.google.com/docs/analytics/debugview which explains how to turn on a faster update of the DebugView.

You need to set the userId to `null` to remove it.

I'll close this issue off now as you've confirmed it's working.
