### ISSUE TITLE
[iOS] Crashlytics cannot communicate with firebase

### ISSUE THREAD

**Issue by panda0603** [invertase/react-native-firebase#3730]
## Issue

Describe your issue here

Hello, I am trying to install firebase crashlytics to my app. 

I have followed every steps in the docs here: 
https://rnfirebase.io/crashlytics/ios-setup

Problem is I cannot get pass this screen in firebase crashlytics console (sorry for different language): 
![image](https://user-images.githubusercontent.com/34116285/83501845-b0e89300-a4fb-11ea-9c63-c07e7691b2b8.png)

Basically says 'build and run your app after adding the SDK. ', and it waits until app communicates with the server. 

Now with that waiting for my app, I already have tried turning off my simulator and successfully rebuilding my app again. However, it doesn't go pass that screen. Just infinitely waits at that view

For android, re-building the app went pass that screen flawlessly. I'm not sure why on iOS can't pass that step. 

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - ` "@react-native-firebase/analytics": "^7.1.2",
    "@react-native-firebase/app": "^7.1.4",
    "@react-native-firebase/crashlytics": "^7.1.3"`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by andersonaddo** [comment]
Probably cuz you haven't enabled debug mode logging. 
https://rnfirebase.io/crashlytics/usage#enable-debug-crash-logs

**Comment by panda0603** [comment]
@andersonaddo that was it. Thank for the help really appreciate it! 

p.s. on Android such config is not needed to pass the step.
