### ISSUE TITLE
🔥 Unable to retrieve the params information which is being passed while creating the link programmatically 

### ISSUE THREAD

**Issue by kushavi2509** [invertase/react-native-firebase#3731]
**Unable to retrieve the params information which is being passed while creating the link programmatically**. I am sharing the current configuration of firebase console /as well as  Implemented code.

**Current status**
When I tap on the link it opens. the app store  OR app depending upon whether it is installed or not and I can listen for the Dynamic link URL and can log it into the debug console.

What I want to achieve is given below -
-  To generate a link by which I can share any particular blog to anyone and whenever someone taps on that link it leads to that particular blog post on application.
**Firebase dashboard setup:> **

<img width="589" alt="Screenshot 2020-06-02 at 7 19 08 PM" src="https://user-images.githubusercontent.com/34898366/83528715-11310200-a507-11ea-8278-c979556d63af.png">

**Current code that is written  to generate the dynamic link: > **
![WhatsApp Image 2020-06-02 at 5 13 34 PM](https://user-images.githubusercontent.com/34898366/83528148-61f42b00-a506-11ea-92a4-f438a8749ce1.jpeg)

**Code to generate the link**
    const buildLink = async (id) => {
        const link = await dynamicLinks().buildLink({
            link:  `https://xyz.page.link/navigate_links/`,
            // domainUriPrefix is created in your Firebase console
            domainUriPrefix: 'https://xyz.page.link',
            navigation: {
                forcedRedirectEnabled: true,
            }
        }); 
        console.log(link)
        openShare(link)
    }

** current generated lInk**
https://xyz.page.link?efr=1&link=https%3A%2F%2Fxyz.page.link%2Fnavigate_links%2F%3Fid%3D%257B5IMgv4vpQLZkP0VFYWN2I7cXYtn2%257D

**Code to listen the link**
useEffect(()=>{
        dynamicLinks()
            .getInitialLink()
            .then(link => {
                console.log("link recieved=>", link)
            });
},[
]}

Link that is being recieved in app:>

<img width="422" alt="Screenshot 2020-06-02 at 6 24 00 PM" src="https://user-images.githubusercontent.com/34898366/83522538-6e748580-a4fe-11ea-97ad-b9ceade5f9cf.png">

**Comment by kushavi2509** [comment]
I didn't receive the  URL parameters to extract the.  URL ad navigates to particular blog.
The app is opening. but not  loggi2ng the created link as it is supposed to act after receiving param s.

**Comment by msrivas** [comment]
Hi, I have a similar issue but only seeing this with Android. The domain is configured such that dynamic link redirects to the deep link on desktops/browsers and to the app for iOS and Android. In iOS the data received is the embedded 'link' field added during dynamic link creation (which is expected) however on Android the dynamic link redirects to the deep link (browser behavior) unlike iOS. The assets.json file has the right SHA-256.

I am kind of stuck on this. Any help would be appreciated!

**Comment by henokweldemicael** [comment]
Any luck on this? I am also having this issue

**Comment by sikky99** [comment]
i am also having this issue

**Comment by mikehardy** [comment]
Then you should definitely upgrade, this issue was closed in August last year and we've had new versions since then! You could try posting a new issue with the details needed for triage and we could take a look
