### ISSUE TITLE
Crashlytics doesn't produce JavaScript stack traces 

### ISSUE THREAD

**Issue by panda0603** [invertase/react-native-firebase#3735]
## Issue

I am on latest firebase crashlytics version 7.1.3. 
I have seen the blog post about crashlytics supporting JavaScript stacktraces from v6. 
However I do not get any crash reports related to JavaScript so far. 

I do get reports using crashlytics().crash() method, but seems to only tell me about native error log. I deliberately caused javascript errors such as object undefined/null errors, but nothing seems to  be logged into crashlytics. 

Now there are workarounds here:
#1052
#1783

But I wish to know if crashlytics is currently supporting javascript stack traces or not. 
Others are also facing this issue until now in the issues mentioned above. 

Thanks, 
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
We can consider this when you fill out the template, can you update your report to include the requested information?

**Comment by patelnets** [comment]
Javascript traces not showing for me either `    "@react-native-firebase/app": "^8.3.1",
    "@react-native-firebase/crashlytics": "^8.3.1",`

**Comment by andersonaddo** [comment]
@patelnets make a new issue with the template; can't help otherwise.
