### ISSUE TITLE
Missing error code for Android Authentication(too many requests)

### ISSUE THREAD

**Issue by dackers86** [invertase/react-native-firebase#3739]
## Issue

When too many requests have occurred Android will see the error `auth/unknown`.
For iOS this appears correctly as auth/too-many-requests
---

![image](https://user-images.githubusercontent.com/2060661/83647814-3c6e2c80-a5ad-11ea-9b22-e41ee0ea105d.png)

![image](https://user-images.githubusercontent.com/2060661/83647796-35471e80-a5ad-11ea-9675-231d65b08956.png)

**Comment by mikehardy** [comment]
@dackers86 is actually one of the maintainers :-) (if you hover over his name here you'll see he's a member of the gitub invertase team), I assumed when I saw it he was just leaving a note for himself which is why I left it open instead of closing it no template. Cheers @andersonaddo

**Comment by andersonaddo** [comment]
Ooops, my bad 😅
As you were!

**Comment by Salakar** [comment]
@andersonaddo appreciate you replying to issues though, super helpful :) so thanks!

And this is one I raised internally, the error code being missing on Android and so needs fixing instead of it showing 'unknown'

**Comment by dackers86** [comment]
PR added at https://github.com/invertase/react-native-firebase/pull/3795/checks?check_run_id=780813295

**Comment by Salakar** [comment]
Shipped 🚢
