### ISSUE TITLE
ios build fails with Instance ID package

### ISSUE THREAD

**Issue by yesterday24** [invertase/react-native-firebase#3746]
When installing the instance ID package on IOS, I get the following errors (while building through XCODE, building through npx react-native run-ios just fails):

- Use of undeclared identifier 'FIRInstanceID' (line 43)
- Use of undeclared identifier 'FIRInstanceID' (line 68)
- Use of undeclared identifier 'FIRInstanceID' (line 83)
- Use of undeclared identifier 'FIRInstanceID' (line 102)
- Use of undeclared identifier 'FIRInstanceIDErrorAuthentication' (Line 121)
- Use of undeclared identifier 'FIRInstanceIDErrorNoAccess' (Line 124)
- Use of undeclared identifier 'FIRInstanceIDErrorTimeout' (Line 127)
- Use of undeclared identifier 'FIRInstanceIDErrorNetwork' (Line 130)
- Use of undeclared identifier 'FIRInstanceIDErrorOperationInProgress' (Line 133)
- Use of undeclared identifier 'FIRInstanceIDErrorInvalidRequest' (Line 136)

It's linked to this file: https://github.com/invertase/react-native-firebase/blob/master/packages/iid/ios/RNFBIid/RNFBIidModule.m

**Environment:**
- react-native 0.62.2
- react 16.11.0
- @react-native-firebase/app 7.2.0
- @react-native-firebase/idd 7.1.3

I followed the instructions in the documentation. I added the package through npm and did a pod install. When I delete the package an re-run pod install, it works fine. I also have the analytics package installed. This works.

**Comment by mikehardy** [comment]
close Xcode `npx react-native-clean-project` then pod install and try again
if building one way works and another way doesn't, there is likely some weird local caching going on. Xcode is pretty horrible that way

**Comment by yesterday24** [comment]
I did a clean-project, and installed the package again. Same error. I downgraded all packages to 7.1.0, still the same error.

**Comment by mikehardy** [comment]
clone this and run this script: if it fails then we can reproduce https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

As mentioned though, my local project is building fine with a `yarn upgrade --latest` as of around 18 hours ago

**Comment by yesterday24** [comment]
I've cloned the repo, but it fails at this line:
> Cloning spec repo `cocoapods` from `https://github.com/CocoaPods/Specs.git`
I've stopped the execution and did ``cd ios && pod install && cd ..``, but I get the same problem (it stops at that line so the pods aren't installed).

I'll try to install it in a bare project again, without any other libraries. I'll let you know asap.

Oh, and thanks for the fast replies! I really appriciate it!

PS: please check the edit in my previous comment. Maybe I don't need the instance ID package at all?

**Comment by mikehardy** [comment]
I think messaging.getToken() is enough, I believe it is specific to each app install? I get different tokens for the same firebase user on different devices (from react-native-device-info::getUniqueId())

I believe Instance ID in Firebase is a different concept and used more for securing content, not for targeting devices.

That said, failing to clone the CocoaPods git repo is a fundamental sort of infrastructure error. Something is wrong with your local machine or network for that not to work, or it's just large and timed out, unknown. That's not the sort of failure that has anything to do with react-native-firebase

**Comment by yesterday24** [comment]
I did a clean install, RN version **0.62.2**. I only installed firebase/app and firebase/iid. App works perfectly, with iid I get the error again.

I started a new project with RN version **0.61.5** (the version I built the previous app in). Again, the same error.

I removed the firebase/iid package and it all works again. I also tried firebase/messaging and firebase/storage (the other packages I need), they work perfectly.

In which file does FIRInstanceID get declared? Because my error says it's undeclared. Maybe this file is missing in my installation?

**Comment by mikehardy** [comment]
That is interesting and explains why my script and my project works. I know there is a connection between the messaging and instanceid packages but a hard dependency is not expressed no - @Ehesp / @Salakar are you guys aware of a hard dependency on IID in Messaging now? Should it be expressed in podspec+gradle or in package.json or similar?

**Comment by Salakar** [comment]
This shouldn't be happening, I think this is from the recent iOS CoreOnly podspec change we did, Core used to include IID, guessing CoreOnly now no longer does; https://github.com/invertase/react-native-firebase/blob/master/packages/iid/RNFBIid.podspec

**Comment by mikehardy** [comment]
I would say that not including IID by default is the intended outcome, for more privacy-concerned apps, so hopefully it's just a matter of making the dep more explicit for where it's needed and optional for the rest. Whichever way it goes let me know and I'll update my throwaway demo script (at least it's internal comments) for future explorers

**Comment by Greeniemax** [comment]
Ionic really SUCKS!!!
