### ISSUE TITLE
Admob - rewardedAd.load() and interstitial.load() not working the second time

### ISSUE THREAD

**Issue by enosh94** [invertase/react-native-firebase#3748]
Hey I'm experiencing the same error raised here [#3185](https://github.com/invertase/react-native-firebase/issues/3185) again on adMob Version "^7.1.3". I checked with interstitial.load() and It also does not work for the second time. 

( Note: ads are getting loaded for the first time. but not for the second time) 

![Annotation 2020-06-06 165625](https://user-images.githubusercontent.com/15036481/83943107-e1d80900-a816-11ea-8d72-f13f9c26e0a2.png)

**Comment by Choco-Dev** [comment]
i was struggling with same problem for past 2 days and i just could get over it today.
this is the solution that works for me. 
you should create a `ref` from the `RewardedAd.createForAdRequest()` instead of calling it out of component's function. this way we can have a fresh new object of rewardedAd in our component.

```js
const ComponentName = () => {
  const rewardedAdRef = useRef(RewardedAd.createForAdRequest(TestIds.REWARDED));
  const [adLoaded, setAdLoaded] = useState(false);

  useEffect(() => {
    const eventListener = rewardedAdRef.current.onAdEvent((type) => {
      if (type === RewardedAdEventType.LOADED) setAdLoaded(true);
    });

    // Start loading the interstitial straight away
    rewardedAdRef.current.load();

    // Unsubscribe from events on unmount
    return () => {
      eventListener();
    };
  }, []);

  if(adLoaded)
    return <Button title="Show ad" onPress={() => rewardedAdRef.current.show()} />;

  return null;
}
```

**Comment by enosh94** [comment]
Thank you so much @Choco-Dev . your solution worked well.

**Comment by enosh94** [comment]
> i was struggling with same problem for past 2 days and i just could get over it today.
> this is the solution that works for me.
> you should create a `ref` from the `RewardedAd.createForAdRequest()` instead of creating an object of it out of component's function. this way we can have a fresh new object of rewardedAd in our component.
> 
> ```js
> const ComponentName = () => {
>   const rewardedAdRef = useRef(RewardedAd.createForAdRequest(TestIds.REWARDED));
>   const [adLoaded, setAdLoaded] = useState(false);
> 
>   useEffect(() => {
>     const eventListener = rewardedAdRef.current.onAdEvent((type) => {
>       if (type === RewardedAdEventType.LOADED) setAdLoaded(true);
>     });
> 
>     // Start loading the interstitial straight away
>     rewardedAdRef.current.load();
> 
>     // Unsubscribe from events on unmount
>     return () => {
>       eventListener();
>     };
>   }, []);
> 
>   if(adLoaded)
>     return <Button title="Show ad" onPress={() => rewardedAdRef.current.show()} />;
> 
>   return null;
> }
> ```

**Comment by mikehardy** [comment]
If there is some problem with the library functionality and there is a working solution, please propose a PR! it will help everyone

**Comment by Choco-Dev** [comment]
i would like to help but i'm not familiar with the codes on this repo @mikehardy :) so i'm going to describe the way i could reproduce the problem for anyone who wants to work on it:

1. go to the screen where the ad is going to be loaded.
2. get back to previous screen.
3. then again go the same screen to see if the ad can get loaded for the second time.

packages i was using with my RN project:
- @react-navigatio:  >5.0.0
- @react-native-firebase/admob: 7.2.0

**Comment by bamunusingha** [comment]
Still having the issue with @react-native-firebase/admob: 7.3.3 :(

**Comment by Robiullah2244** [comment]
Facing the same issue. @Choco-Dev solution not working.
