### ISSUE TITLE
Error could not find com.google.firebase:firebase-

### ISSUE THREAD

**Issue by comycos** [invertase/react-native-firebase#375]
### Issue
While I compile I get these errors:
[http://imgur.com/a/7w6pQ](url)
I get the same error for each module of react-native-firebase

### Environment

1. Application Target Platform: Android

2. Development Operating System:  Windows 10

3. Build Tools: Android Studio

4. React Native version:  0.47.2

5. RNFirebase Version: 2.1.3

6. Firebase Module: all

**Comment by Salakar** [comment]
![image](https://user-images.githubusercontent.com/5347038/29900906-a6d8e9ec-8dec-11e7-98b6-fedf05513f15.png)

**Comment by comycos** [comment]
@Salakar Thanks!
