### ISSUE TITLE
Not receiving notification on device - did receive the FCM test message though

### ISSUE THREAD

**Issue by jhoodbossb** [invertase/react-native-firebase#3757]
Hi all

Currently have my react-native app installed on my physical iPhone device, and running it on iOS simulator as well.

I have this code on my server; tried both 'sendMulticast' and 'sendToDevice' methods.

```
app.post('/sendtodevice', async (req, res) => {

  const registrationTokens = [
    "FCMtoken1removedexactnameforsafety",
    "FCMtoken2removedexactnameforsafety"
  ];

  const message = {
    data: {score: '850', time: '2:45'},
    tokens: registrationTokens,
    contentAvailable: true,
    priority: 'high',
  }

  console.log('still going stronk');

  admin.messaging().sendMulticast(message)
    .then((response) => {
      console.log(response.successCount + ' messages were sent successfully');
    })
})
```
```
app.post('/sendtodevice', async (req, res) => {

  const registrationTokens = [
    "FCMtoken1removedexactnameforsafety",
    "FCMtoken2removedexactnameforsafety"
  ];

  await admin.messaging().sendToDevice(
  registrationTokens,
  {
    data: {
      owner: 'hi',
      user: 'hi',
      picture: 'hi',
    },
  },
  {
    // Required for background/quit data-only messages on iOS
    contentAvailable: true,
    // Required for background/quit data-only messages on Android
    priority: 'high',
  },
  );

  console.log('Notification sent');
`})`
```
When I press the 'Send notification' button on my iOS simulator (not shown here but it works), in both cases, the console logs that the notifications were sent.

However, I don't see it on my notification screen on my physical device. I have the app running in the background there, not open.

Is this a problem with having the app running at two places at a time? Not sure if the physical iPhone still uses the 'react-native start' metro, even if it is in background?

When I sent a test notification from Firebase console, it did show up on notification screen.

Kind regards

**Comment by mikehardy** [comment]
You have connected the physical phone to your computer and started the app from Xcode so you can watch the console logs, yes? The best info will come from that. There are so many reasons iOS will not show a notification in response to an FCM it's endlessly frustrating.

**Comment by jhoodbossb** [comment]
Hi Mike,

Yes I have. Actually I use 'react-native-log-ios', so I see the logs in my browser.

Sucks... Trying to find out what is the best way to test if my notifications are working.

**Comment by sulagarde** [comment]
I have the same problem. My app is in production since a month and everything worked but suddenly (since 26th may) none of platforms (iOs nor Android) display notifications.

I receive test notifications from fcm console but when I try in production mode, Xcode console show this message.
[] nw_read_request_report [C1] Receive failed with error "Software caused connection abort"

rnfb v.5.5.7
rn v.59.10

xcode v.11.5

**Comment by mikehardy** [comment]
Those versions (react-native 0.59 and RNFBv5.x) are effectively too old to support. No idea what could be going on there. Get current, re-test

**Comment by sulagarde** [comment]
@mikehardy I have other projects working well with the same version of RN & RNFB so I don't think it is about the versions I use. It's strange that suddenly something worked perfectly stop to work. Is RNFB v6 compatible with RN<0.60? (I think so but just to be sure)

**Comment by russellwheatley** [comment]
I'm going to close this issue as it relates to version 5 which we no longer support, feel free to continue the discussion.

**Comment by lylest** [comment]
same problem here on android
