### ISSUE TITLE
Compile RNFirebaseMessaging.m fails for iOS

### ISSUE THREAD

**Issue by matejukmar** [invertase/react-native-firebase#376]
### Issue

Using latest react native library (0.47.2) build fails for iOS with the following error:

```
In file included from .../node_modules/react-native-firebase/ios/RNFirebase/messaging/RNFirebaseMessaging.m:9:
In file included from .../Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:19:
In file included from .../Build/Products/Debug-iphonesimulator/include/yoga/Yoga.h:15:
../../../ios/Pods/leveldb-library/port/win/stdint.h:11:2: error: This file should only be included when compiling with MSVC.
#error This file should only be included when compiling with MSVC.
 ^
```
I could not find any information about this error. I think I followed installation instructions correctly. My pod file looks like this:

```
platform :ios, '10.0'
	
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!

	pod 'Firebase/Core'
	pod 'GoogleSignIn'
	pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

	#pod 'Firebase/AdMob'
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	#pod 'Firebase/Crash'
	pod 'Firebase/Database'
	#pod 'Firebase/DynamicLinks'
	pod 'Firebase/Messaging'
	#pod 'Firebase/RemoteConfig'
	#pod 'Firebase/Storage'

	pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
	pod 'React', :path => '../node_modules/react-native', :subspecs => [
		'BatchedBridge', # Required For React Native 0.45.0+
		'Core',
		# Add any other subspecs you want to use in your project
	 ]

```

There are some extra warnings after the error when compiling RNFirebaseMessaging.m: 

```
/Users/matej/Projects/HelloBeer/hellobeer-app2/node_modules/react-native-firebase/ios/RNFirebase/messaging/RNFirebaseMessaging.m:277:71: warning: assigning to 'id<UNUserNotificationCenterDelegate> _Nullable' from incompatible type 'RNFirebaseMessaging *const __strong'
        [UNUserNotificationCenter currentNotificationCenter].delegate = self;
                                                                      ^ ~~~~
/Users/matej/Projects/HelloBeer/hellobeer-app2/node_modules/react-native-firebase/ios/RNFirebase/messaging/RNFirebaseMessaging.m:373:47: warning: incompatible pointer types initializing 'UNMutableNotificationContent *' with an expression of type 'UNNotificationContent *' [-Wincompatible-pointer-types]
                UNMutableNotificationContent *content = notif.content;
                                              ^         ~~~~~~~~~~~~~
/Users/matej/Projects/HelloBeer/hellobeer-app2/node_modules/react-native-firebase/ios/RNFirebase/messaging/RNFirebaseMessaging.m:388:59: warning: incompatible pointer to integer conversion sending 'NSInteger *' (aka 'long *') to parameter of type 'NSInteger' (aka 'long'); dereference with * [-Wint-conversion]
    [RCTSharedApplication() setApplicationIconBadgeNumber:number];
                                                          ^~~~~~
                                                          *

```

### Environment

1. Application Target Platform: iOS: 10.0

2. Development Operating System: macOS Sierra

3. Build Tools:  Xcode 8.3.3

4. React Native version: 0.47.2

5. RNFirebase Version: 2.1.3

6. Firebase Module: messaging

**Comment by chrisbianca** [comment]
This is caused by the addition of LevelDB in the latest Firebase Database iOS library.  I have worked around this issue in v3, but will look at back porting the fix to v2.

**Comment by chrisbianca** [comment]
I have just published version 2.1.4 which should address this issue, please let me know if you're still experiencing issues.

**Comment by matejukmar** [comment]
Thanks Chris, for quick response, I can confirm that with 2.1.4 issue is fixed.

**Comment by chrisbianca** [comment]
Fantastic, thanks for confirming!

**Comment by jpokrzyk** [comment]
I still have this issue in `2.1.4`. Seems to be in remote config for me though. 

But it seems to only fail in xcode with that error. When I run `react-native run-ios` I can build and run it.

Let me know if you prefer I open a new issue.

![image](https://user-images.githubusercontent.com/4333958/29944078-033dd71a-8e6a-11e7-9985-d4b3e784a3cf.png)

**Comment by chrisbianca** [comment]
@jpokrzyk Sounds like a standard Xcode issue!  Try cleaning your project, restarting, cleaning the project again and then building!  Xcode can get itself in a bit of a mess...

**Comment by xolen** [comment]
Hello @jpokrzyk, I was having the same issue a couple of minutes ago, did just as @chrisbianca says and it is working properly now. Hope cleaning can help you as well.

**Comment by jpokrzyk** [comment]
Thanks for the quick responses! Yea I think xcode was the case. I saw those suggestions after I had gotten it working. I tried a bunch of version changes and stuff like that. But ultimately I restarted and cleaned a lot and those were probably the steps that actually got it working.
