### ISSUE TITLE
Enrich crashlytics stacktrace

### ISSUE THREAD

**Issue by thomasblom** [invertase/react-native-firebase#3760]
## Documentation Feedback

I have successfully integrated Firebase Crashlytics within my app, but one thing disturbs me.
If you look at the results in the Firebase Console, you see a non-fatal error that I logged.
![Schermafbeelding 2020-06-09 om 13 43 08](https://user-images.githubusercontent.com/8591153/84144314-5948ab00-aa58-11ea-8ee3-1caaa43f2a58.png)

But what I couldn't find in the documentation is how to modify this. Because every error that I will log will come from `io.invertase.firebase.crashlytics.JavaScriptError`

In the main overview page with all the errors, you see even less data. All you see is `index.android.bundle` and a minified function where the error came from (`.v`). And if it came from an anonymous function, the method is simply `.<unknown>`.
![Schermafbeelding 2020-06-09 om 13 53 42](https://user-images.githubusercontent.com/8591153/84144612-d6742000-aa58-11ea-87bf-f1d116df29c2.png)

Is it possible to change these values of the error log? Especially in the main view this is needed, because you won't see the difference between the errors if all you see is a minified function with `index.android.bundle`.

Thanks in advance.

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Did you keep the sourcemap for your bundle build? Or tag the source so you could regenerate it at that point in time and de-obfuscate? You'll need to map it back in order to get the stack trace you want. None of the crash services that I'm aware of handle react-native / javascript bundle de-obfuscation automatically

**Comment by angelos3lex** [comment]
I had same problem, trying to de-obfuscate. In [this SO post](https://stackoverflow.com/questions/62214336/react-native-firebase-crashlytics-deobfuscation/62300702#62300702), check the answer that helped us de-obfuscate ios crashlytics logs.

**Comment by thomasblom** [comment]
Thanks for a quick reply guys! I understand we can de-obfuscate with the sourcemap of our bundle build. The struggle we have is more about the Firebase Crashlytics overview, which will only show `index.android/ios.bundle`. So we cannot see any difference between two logs, except the line numbers. But there is nothing to do about this, am i correct @mikehardy?

@angelos3lex thanks for the tip! But `stack-beautifier` doesn't understand the stacktrace which Firebase Crashlytics gives me. Do you know what i'm doing wrong?

<details>
  <summary>Stack trace</summary>
```
Non-fatal Exception: io.invertase.firebase.crashlytics.JavaScriptError: TEST
       at .<unknown>(index.android.bundle:1221:2263)
       at .p(index.android.bundle:113:423)
       at .<unknown>(index.android.bundle:113:1724)
       at .p(index.android.bundle:113:423)
       at .o(index.android.bundle:113:900)
       at .<unknown>(index.android.bundle:113:1257)
       at .c(index.android.bundle:109:205)
       at .b(index.android.bundle:109:1623)
       at ._(index.android.bundle:109:488)
       at .h(index.android.bundle:113:1241)
       at ._invoke(index.android.bundle:113:1293)
       at .async(index.android.bundle:113:3688)
       at .onSelect(index.android.bundle:1221:2181)
       at .value(index.android.bundle:1223:28310)
       at .touchableHandlePress(index.android.bundle:217:2263)
       at .touchableHandlePress([native code]:0:0)
       at ._performSideEffectsForTransition(index.android.bundle:208:9675)
       at ._performSideEffectsForTransition([native code]:0:0)
       at ._receiveSignal(index.android.bundle:208:8357)
       at ._receiveSignal([native code]:0:0)
       at .touchableHandleResponderRelease(index.android.bundle:208:5645)
       at .touchableHandleResponderRelease([native code]:0:0)
       at .b(index.android.bundle:91:1197)
       at .k(index.android.bundle:91:1340)
       at .C(index.android.bundle:91:1394)
       at .N(index.android.bundle:91:1692)
       at .A(index.android.bundle:91:2482)
       at .forEach([native code]:0:0)
       at .z(index.android.bundle:91:2282)
       at .<unknown>(index.android.bundle:91:13914)
       at ._e(index.android.bundle:91:88659)
       at .Ne(index.android.bundle:91:13582)
       at .Ue(index.android.bundle:91:13755)
       at .receiveTouches(index.android.bundle:91:14547)
       at .value(index.android.bundle:27:3685)
       at .<unknown>(index.android.bundle:27:841)
       at .value(index.android.bundle:27:2939)
       at .value(index.android.bundle:27:813)
       at .value([native code]:0:0)
```
</details>

The package refers to the error [here](https://github.com/software-mansion-labs/stack-beautifier#getting-error-stack-trace-parse-error-at-line-n), but I think this is a valid format.

Thanks in advance.

**Comment by thomasblom** [comment]
@angelos3lex It works with a trace like yours, but of course not the right files/lines. 
It's weird the package says it supports the format of my stacktrace, but it doesn't. I will look into this. Thanks anyway for your help!

@mikehardy Do you know how I can get JSC stack traces instead of the format i'm getting?

**Comment by mikehardy** [comment]
I do not, sorry. I log synthetic analytics "screen" events via react-navigation on each navigation change (the typical pattern to work around react-native using only a single activity) and typically some other data related to session state. That in combination with even objectively terrible stack traces like the above, has been enough for me to quickly inspect code and see the problem in practice so I haven't dug deeper

**Comment by russellwheatley** [comment]
Feel free to continue the discussion but this isn't an issue with React Native Firebase, so I'm going to go ahead and close it.

**Comment by Daha62** [comment]
Got such error in firebase Console
![image](https://user-images.githubusercontent.com/6141193/87287440-8be03a80-c513-11ea-85e3-cb248842f401.png)

**Comment by mikehardy** [comment]
Yeah, I have my first live build out with the with the v8 crashlytics and I see similar on the java side @Daha62 so I can confirm that Firebase Crashlytics (the thing we just migrated to) can generate stacks like this. Why? I'm unsure in my case. I need to verify if I'm actually uploading the deobfuscation files (I may not be) etc.

Can you verify if you have sent all the de-obfuscation files up to firebase etc?

**Comment by andersonaddo** [comment]
I think this has to do with your project-specific environments. 
I'm on the move right now so I can't provide a proper screenshot, but my V8 test crash stack trace is fine:
```
Fatal Exception: java.lang.RuntimeException: Crash Test
       at io.invertase.firebase.crashlytics.ReactNativeFirebaseCrashlyticsModule$1.run(ReactNativeFirebaseCrashlyticsModule.java:45)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by mikehardy** [comment]
Great, thanks for the success report @andersonaddo I was pretty sure it was my local project, now I know to really focus on that

**Comment by abdullahizzuddiin** [comment]
Hi, will any update for this issue? or this issue has been closed permanently?

I also find my stacktraces is difficult to analyze?

- Android
![image](https://user-images.githubusercontent.com/6801853/92465929-82184200-f1f9-11ea-8eb1-ae0fa94304ac.png)

- iOS
![image](https://user-images.githubusercontent.com/6801853/92466060-bbe94880-f1f9-11ea-9d8c-95dd76654d89.png)

**Comment by mikehardy** [comment]
@abdullahizzuddiin Firebase Crashlytics knows nothing of javascript stack traces. You will need to post-process javascript stack traces https://stackoverflow.com/questions/62214336/react-native-firebase-crashlytics-deobfuscation/62300702#62300702 was posted above and I think it's useful

**Comment by mikehardy** [comment]
There is hope perhaps, it appears that firebase crashlytics has added some ability to add information to stack frames manually which would mean it is maybe possible to construct more informative stack traces from the javascript code https://github.com/firebase/firebase-ios-sdk/issues/5975 - not sure exactly how useful it would be but if someone was interested in advancing this area we could certainly merge related PRs...

**Comment by abdullahizzuddiin** [comment]
Awesome!

[stack-beautifier lib](https://github.com/software-mansion-labs/stack-beautifier#readme) worked beautifully on Android.

**Comment by abdullahizzuddiin** [comment]
But, is there a way to separate issues based on stacktraces?

Look at this pic,
![image](https://user-images.githubusercontent.com/6801853/92712324-aacc4300-f383-11ea-9ca3-ba6b5267d88d.png)

So many difference crashes is grouped together on `ExceptionsManagerModule.java – line 71: com.facebook.react.modules.core.ExceptionsManagerModule.reportException` issue. If we look at the detail, we will find many difference stacktraces (means difference bugs) collected there.

**Comment by mikehardy** [comment]
I am happy stack-beautifier worked for you! I am not aware of away to differentiate higher layers of the stack though unfortunately, for the same reason you have to post-process javascript stacks, Firebase simply does not know about differences that are higher than the native layer, yet

There is potential to pass this information to firebase with the APIs I linked above but we don't have that feature now, and it is not under development by us or anyone proposing a PR yet that I know about

**Comment by mikehardy** [comment]
Strangely the custom stack traces thing does not appear available on Android. On iOS it was added in pod 6.21.0

https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=ios#customize-stack-traces

**Comment by akshbn** [comment]
Hi @thomasblom did you solve the problem you were facing? I'm having the same issue.

**Comment by akshbn** [comment]
Ok, so i went through the source code of [stack-beautifier](https://github.com/software-mansion-labs/stack-beautifier).

The regex relevant to the format returned by Crashlytics is as follows.
[`/^at (.*) \((.*)\:(\d+)\:(\d+)\)$/`](https://github.com/software-mansion-labs/stack-beautifier/blob/master/stack-beautifier.js#L54)

For those of us who are using crashlytics on android will get the stack trace as txt in the below format:
```
Non-fatal Exception: io.invertase.firebase.crashlytics.UnhandledPromiseRejection: undefined is not an object (evaluating 'c.bodyString')
       at .<unknown>(index.android.bundle:1730:1890)
       at .p(index.android.bundle:79:423)
```

We need to pre-process the crashlytics trace file for stack-beautifier to parse it properly. I created a shell script to do this. Save the below code in a file called `preprocess.sh`
```
sed -i 's/\s*at/at/g' $1
sed -i 's/(/ (/g' $1
sed -i 's/:0:/:1:/g' $1 # Stack beautifier indexes lines from 1 and not 0
```
Run this script 
`bash preprocess.sh <stack trace filename>`

Now, we just have to run stack-beautifier.
`stack-beautifier <map file name> -t <stack trace filename>`

Hope this helps someone in the future.

**Comment by esutton** [comment]
@thomasblom 

Paring down my stack trace text to the first two lines, and adding a space after the stack trace function and before the opening parentheses fixed my  stack-beautifier **Stack trace parse error**.

File: mytrace.txt
```
# stack trace text copied from crashlytics after deleting all but first two lines
Non-fatal Exception: io.invertase.firebase.crashlytics.UnhandledPromiseRejection: undefined is not an object (evaluating 't.includes')
       at .removeFile(index.android.bundle:474:6500)
```


```
# Inserting a space after the 'removeFile' function and before opening '('  
# fixed the "Stack trace parse error"

Non-fatal Exception: io.invertase.firebase.crashlytics.UnhandledPromiseRejection: undefined is not an object (evaluating 't.includes')
       at .removeFile (index.android.bundle:474:6500)
```

Success!  

Found the originaltion of my removeFile function error in source file **Utility.js:567:17**  
```
stack-beautifier sourcemap.android.js -t mytrace.txt
Non-fatal Exception: io.invertase.firebase.crashlytics.UnhandledPromiseRejection: undefined is not an object (evaluating 't.includes')
  at includes (/Users/edward3/Documents/projects/react-native/field-scout/v1.6.1146/source/app/components/Utility.js:567:17)
```

**Comment by mikehardy** [comment]
If this is something we could alter here without affecting backwards compatibility we could take a PR for it
We're in control of this stack trace generation here:

https://github.com/invertase/react-native-firebase/blob/f4dfb1a2f6941ff44cf6e020c78d44b5a056d367/packages/crashlytics/lib/index.js#L114

(and in native android as example, perhaps this is the root of formatting issues as this appears to be the standard for Java error reporting at least [based on native experience](https://github.com/ankidroid/Anki-Android/issues/8940))

https://github.com/invertase/react-native-firebase/blob/f4dfb1a2f6941ff44cf6e020c78d44b5a056d367/packages/crashlytics/android/src/main/java/io/invertase/firebase/crashlytics/ReactNativeFirebaseCrashlyticsModule.java#L189-L194

We are using [stacktrace-js](https://www.stacktracejs.com/) though - odd that it is somehow not compatible out of the box with stack-beautifier :thinking:  ?

Perhaps if you tried stacktrace-gps instead https://www.stacktracejs.com/#!/docs/stacktrace-gps ?

**Comment by mikehardy** [comment]
Honestly I don't know :sweat_smile: - I have not tried them locally, I was just trying to provide brainstorming suggestions based on the context I have. It's all a bit of a science fair project in this area (decode of JS minified+etc stack traces) and I haven't seen anything yet that is quite ready for systemitization except maybe the script chunks above (those do look promising)

Confounding it is that I think with Hermes this will get even more difficult to resolve back to source lines

**Comment by esutton** [comment]
@mikehardy thanks for the input.  Any kind of brainstorming is good to help cut through the noise.

This seems to work for me if I remove all stack trace lines starting with first line containing "**[native code]**"
```
npx metro-symbolicate sourcemap.android.js < bug-android-stack-trace.txt
npx metro-symbolicate sourcemap.ios.js < bug-ios-stack-trace.txt
```
See: https://reactnative.dev/docs/next/symbolication

**Comment by yamila-fraiman** [comment]
> preprocess.sh

You save my time!
