### ISSUE TITLE
Proguard rules in v6

### ISSUE THREAD

**Issue by MohamadKh75** [invertase/react-native-firebase#3770]
## Documentation Feedback

Hi
I had the v5 and there was a section which suggests if I'm using Proguard, i should add some rules ([link](https://v5.rnfirebase.io/docs/v5.x.x/installation/android#Using-with-Proguard-enabled)).
But I can't see this in v6 docs! Should I create a PR for that or it's ok to not add those rules in v6 anymore :thinking: ?

**Comment by MohamadKh75** [comment]
I want to make a release 😅
Any idea...?

**Comment by mikehardy** [comment]
I have already made releases, the information in my comment above is still my "state of the art", it's literally what is in my release, which is actually working.

**Comment by roni-castro** [comment]
I tried this proguard configuration but it did not work for me =/, in Debug mode I receive push in all cases, but when i generate a release version I stop receiving on Foreground with data only and receives push on background with notification + data payload. Any idea how to debug what might be causing it in release version? 
I have `multiDexEnabled true` on `android/app/build.gradle` and my proguard have these rules:

```
# Add any project specific keep options here:
-keep public class com.dylanvann.fastimage.* {*;}
-keep public class com.dylanvann.fastimage.** {*;}
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}

# react-native-firebase section
-keep class io.invertase.firebase.** { *; }
-dontwarn io.invertase.firebase.**
# end react-native-firebase section

```

**Comment by mikehardy** [comment]
All I can offer is that if it is a proguard problem, an unfiltered logcat will show a ClassNotFoundException or NoClassDefError - they stick out wonderfully and indicate R8 shrunk something out while minimizing

I do not have this problem though so I'm surprised, although perhaps R8 "saw" I was using the classes from some other path and kept them for me, project-specifc style.

One thought - if the classes were missing, wouldn't all cases fail :thinking:

**Comment by roni-castro** [comment]
Never mind. I forgot the fact that I need a Notifee license in order to generate a release build. Soon I will have it again:  

```
2020-06-18 23:11:51.678 4664-4664/? D/RNFirebaseMsgReceiver: broadcast received for message
2020-06-18 23:11:51.773 4664-4735/? W/NOTIFEE: (License): Attempted to call method displayNotification but your license is invalid.
```

**Comment by mikehardy** [comment]
Interesting - I can see how that would be confusing as a platform difference. It's my understanding that licensing for notifee is still one of the areas seeing active development, with android receiving attention first as the (by far) majority platform - if that helps explain things tangentially
