### ISSUE TITLE
Question : Upgrade to the Firebase Crashlytics SDK from Fabric

### ISSUE THREAD

**Issue by helbery** [invertase/react-native-firebase#3771]
## Issue

We just received a mail from Firebase  : 
[Action Required] Update your apps to use the latest Firebase Crashlytics SDKs before November 15, 2020.

FirebaseCrashlytics no longer works with the Fabric SDK

Is there any plan for this?

Thanks

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by oferRounds** [comment]
Hey @mikehardy – it the PR you refer to already merged?
I’m facing the same issue after upgrading from Fabric: crash appears on Android dashboard, but not on iOS

**Comment by mikehardy** [comment]
> Hey @mikehardy – it the PR you refer to already merged?
> I’m facing the same issue after upgrading from Fabric: crash appears on Android dashboard, but not on iOS

Yes. You're having a related but new issue. Has a fix that needs someone to test and confirm and PR, it's tiny and easy, could be you 😁, check issues list sorted by recently updated, was just updated couple of hours ago

**Comment by oferRounds** [comment]
Yay! It worked! Thank you so much for the fast reply!
![image](https://user-images.githubusercontent.com/1477963/96505846-5f993000-125f-11eb-9381-c220ebc2e3f3.png)

This fix relates only to the usage of the testing `crash` method, right?

**Comment by oferRounds** [comment]
Is there an option to see the JS stack trace? as I don’t see it (I triggered the crash by pressing a button)

![Uploading image.png…]()

**Comment by mikehardy** [comment]
yes - this is just for test crash only, actual crashes are working but obviously if the test method doesn't give expected results it casts doubt on the whole thing which is unfortunate

there is no JS stack trace in the test crash method, it's a native crash, but you will see *non*-symbolicated JS stack traces if you take a JS crash, yes. Care to PR the switch to native-test-crash code? All the internet points could be yours :smile: :nerd_face:

**Comment by oferRounds** [comment]
Sure, will do tomorrow! 😊
