### ISSUE TITLE
[Android] 🔥Notification is dismissed on received on Quit state

### ISSUE THREAD

**Issue by JulioOrellana** [invertase/react-native-firebase#3779]
## Issue

Describe your issue here

Thanks in advance for reading this ❤️!

I am having an issue with notifications on Android. On notification received on `quit` state, notification is shown on status bar but after that it dissapears removing all old notifications with it. I have tried using `react-native-notifications` for local notifications but notifications are being dismissed too.

I have the following code:

```js
/** @format */

import messaging from '@react-native-firebase/messaging';
import React from 'react';
import { AppRegistry } from 'react-native';
import 'react-native-gesture-handler';
import App from './App';
import { name as appName } from './app.json';
// import { manageBackgroundNotification } from './app/shared/utils/receivedMessagesUtils';


messaging().setBackgroundMessageHandler((remoteMessage) => {
  // manageBackgroundNotification(remoteMessage);
});

const HeadlessCheck = ({ isHeadless }) => {
  if (isHeadless) {
    return null;
  }

  return <App />;
};

AppRegistry.registerComponent(appName, () => HeadlessCheck);
```

I have done an small video as proof.

[https://youtu.be/fe1kCiLxXmA](https://youtu.be/fe1kCiLxXmA)
---

#### `package.json`:

```json
"@react-native-firebase/app": "^7.2.1",
"@react-native-firebase/crashlytics": "^7.1.5",
"@react-native-firebase/database": "^7.2.2",
"@react-native-firebase/messaging": "^7.1.5",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```
</details>

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [X] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28
        googlePlayServicesVersion = "15.0.1"
    }
    repositories {
        maven {
            url 'https://maven.google.com'
            name 'Google'
        }
        jcenter()
        google()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'io.fabric.tools:gradle:1.28.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.1"
            }
        }
    }
}
```
---

</p>
</details>

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 22.41 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.13.0 - ~/.nvm/versions/node/v13.13.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 25.0.2, 25.0.3, 26.0.1, 27.0.3, 28.0.0, 28.0.3, 29.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-log-ios: 1.5.0
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [X] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by obernal** [comment]
@JulioOrellana did you manage to resolve this? I'm having the exact same issue and also suspect it has to do with not handling the notification on `setBackgroundMessageHandler` however it looks like like you already tried that with no luck?

**Comment by JulioOrellana** [comment]
@obernal yes, I was having trouble with `react-native-notifications`, had to uninstall it and reinstall again, delete app from device and clean build. Maybe a react-native-notifications listener was overlapping one of firebase.

**Comment by obernal** [comment]
@JulioOrellana ok great thanks for getting back to me so soon! Is it safe to say this notification being dismissed issue is caused by not handling the notification on `setBackgroundMessageHandler` then? Or did it just get resolved by reinstalling `react-native-notifications` without any need for handling it on `setBackgroundMessageHandler` ?

**Comment by JulioOrellana** [comment]
@obernal try reinstalling everything! `react-native-firebase/messaging`, `react-native-notifications` and comment listeners that set the handlers. To be honest, I don't know when it starts working correctly, but I can remmember it was because of react-native-notifications, I removed the wix library and backgroundHandler starts working again without dismissing the notifications. Remmember to clean build your app, deleting it from device too since listeners stays even if you clean build them from console.
Maybe the problem was that I was using firebase and wix background handlers for notifications. Remove any other notifications handler and leave firebase/messaging alone in your app, run it and test the behavior. If all works again, reinstall the other notifications library.

**Comment by obernal** [comment]
@JulioOrellana ok, makes sense. I might have some old notification libraries still lingering in the code base. I'll clean that up and see if that helps. Thanks!
