### ISSUE TITLE
Duplicate module name: react-native-packager

### ISSUE THREAD

**Issue by davieslee** [invertase/react-native-firebase#378]
### Issue

Hi, I'm new to react native and trying to setup a project with `RNFirebase` but encountered and issue as shown below.

Podfile:
```
platform :ios, '9.0'

target 'app' do
    pod 'Firebase/Core'
    pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

    pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', :path => '../node_modules/react-native'
end

```

Error:
```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-packager
  Paths: /Users/user/Developments/app/ios/Pods/React/packager/package.json collides with /Users/user/Developments/app/node_modules/react-native/packager/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-packager
  Paths: /Users/user/Developments/app/ios/Pods/React/packager/package.json collides with /Users/user/Developments/app/node_modules/react-native/packager/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/user/Developments/app/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/Users/user/Developments/app/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
    at <anonymous>
```

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS Sierra

3. Build Tools: VS Code / Xcode 

4. React Native version: 0.42

5. RNFirebase Version: 2.1.3

6. Firebase Module: Core

### Additional Info

- Ignite with NativeBase (https://github.com/GeekyAnts/ignite-native-base-boilerplate)
- Screenshot

![simulator screen shot 31 aug 2017 6 19 19 pm](https://user-images.githubusercontent.com/4436592/29918768-4aee82f8-8e79-11e7-9092-fb2430a96cd6.png)

**Comment by Salakar** [comment]
This is a just warning in RN I believe, it doesn't break the build - the error in your screenshot means you're not running your packager.

Would suggest nuke your node modules directory and start again with a fresh npm install.

**Comment by davieslee** [comment]
@Salakar thanks for the response. I've managed to run the build by deleting the `React` folder within the `Pod`.

**Comment by ganesh-pprasad** [comment]
I deleted the `React` folder in `pods`, but now I am getting following issue while building for release
`no such file or directory: '/Users/ganeshp/hiver-mobile/Hiver_updated/Hiver/ios/Pods/React/React/Modules/RCTAccessibilityManager.m'`

Can someone explain why I am getting this error?

**Comment by FullstackJack** [comment]
@tengfoung That is not a permanent fix. We need to know an automated way to handle this.
