### ISSUE TITLE
Invariant Violation: Native module cannot be null

### ISSUE THREAD

**Issue by afilp** [invertase/react-native-firebase#3781]
## Issue

I am using `react-native ^0.61.2` and `firebase ^7.1.0`

In Android I am OK.

In iOS, the project builds, the app starts but when it gets to reference the `messaging` import I get this error:

![image](https://user-images.githubusercontent.com/7850073/84591827-2896b600-ae4a-11ea-83bc-c1578e0f5bc7.png)

As you can see the problem is with the import (`FirebaseApp.js: 18`).

I believe that I did everything as expected (yarn, pods, etc.). Obviously I missed something or there are leftovers from previous versions.
Can you shed some light on the problem please?

Thanks.

---

### Javascript
This is where the JS fails:
`import messaging from '@react-native-firebase/messaging';`

#### `package.json`:

```json
  "dependencies": {
    "@react-native-community/async-storage": "^1.6.2",
    "@react-native-community/datetimepicker": "^2.2.3",
    "@react-native-community/netinfo": "^4.3.3",
    "@react-native-firebase/analytics": "^7.1.0",
    "@react-native-firebase/app": "^7.1.0",
    "@react-native-firebase/crashlytics": "^7.1.0",
    "@react-native-firebase/dynamic-links": "^7.1.0",
    "@react-native-firebase/in-app-messaging": "^7.1.0",
    "@react-native-firebase/messaging": "^7.1.0",
    "await-to-js": "^2.1.1",
    "crossroads": "^0.12.2",
    "email-validator": "^2.0.4",
    "lodash.debounce": "^4.0.8",
    "lodash.flattendeep": "^4.4.0",
    "lodash.get": "^4.4.2",
    "lodash.set": "^4.3.2",
    "moment": "^2.24.0",
    "query-string": "^6.8.3",
    "react": "16.9.0",
    "react-native": "^0.61.2",
.... (more below)
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

project 'ourmobileapp',
    'Debug' => :debug,
    'Release' => :release,
    'ABA.Debug' => :debug,
    'ABA.Release' => :release,

target 'ourmobileapp' do
 # Pods for ourmobileapp
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'Fabric', '~> 1.10.2'

  # Pods for react-native-permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"

  # CodePush plugin dependency
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

 # this is needed to avoid including multiple references to react.
 post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end


  target 'ourmobileappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!

end

target 'ourmobileapp-tvOS' do
    # Pods for ourmobileapp-tvOS

    target 'ourmobileapp-tvOSTests' do
      inherit! :search_paths
    # Pods for testing
  end

end

```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ x ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^7.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `"@react-native-firebase/messaging": "^7.1.0"`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Your iOS integration is not working so your assertion you have done everything must be incorrect somewhere, but where? Hard to say, there's so many ways to do it wrong. Using this script you can generate a clean / correct integration in a throwaway app and compare it with yours to see where the difference is, it has comments you can follow https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

**Comment by chetankotkar** [comment]
Am getting same error when i try to `import messaging from '@react-native-firebase/messaging'` on `react-native 0.62.2` and `"@react-native-firebase/messaging": "^7.7.2"` can someone please help.

**Comment by mikehardy** [comment]
@chetankotkar you have not integrated the module properly if the native module is not null. The difference between a throwaway project generated by this script: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh and your project should show what was missed

**Comment by tusharmutreja200** [comment]
I am facing the same issue

**Comment by mikehardy** [comment]
For anyone else that comes here: It is always a project-specific integration issue. The module works. If you see an issue like this you simply don't have it loaded into your native app before javascript tries to access it. You must fix your project.

You can use the make-demo script above to prove it works, but there's nothing we can do here to help you as it is project-specific, sorry
