### ISSUE TITLE
Android Background Notification crash android.app.Application cannot be cast to com.facebook.react.ReactApplication

### ISSUE THREAD

**Issue by devpascoe** [invertase/react-native-firebase#3783]
## Issue
I'm running the latest gear app 7.2.0 and messaging 7.1.4
If i run on device and suspend, use firebase web console to send a simple push note to my device, i get a crash complaining about a cast issue.
This is a project with adding to an existing app eg https://reactnative.dev/docs/integration-with-existing-apps
Here is the error
```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp.myappname/com.myapp.myappname.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
```

Here is the offending line of code.
```
  protected ReactNativeHost getReactNativeHost() {
    return ((ReactApplication) getApplication()).getReactNativeHost();
  }
```
Looks like it is unable to get the ReactNativeHost value due to the cast issue.

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

**Comment by mikehardy** [comment]
Skipped the template. Combo of AndroidManifest.xml + MainApplication likely to show that LAUNCHER intent is to some Android object type that is not ReactApplication, contrary to idiomatic React-Native style and thus violating the assumption that an unchecked cast to ReactApplication from getApplication() is valid.

But we can't tell.
