### ISSUE TITLE
Deep Linking not working in ios.

### ISSUE THREAD

**Issue by Nehal-29** [invertase/react-native-firebase#3784]
## Issue

Deep Linking not working in ios.

AppDelegate openURL method returning false. Hence getInitialURL() on react side is not getting called on clicking the deep linked url. 
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

    "react-native-firebase": "^5.3.1",

`import firebase, {RemoteMessage} from "react-native-firebase";
`
<img width="489" alt="Screenshot 2020-06-15 at 7 53 13 PM" src="https://user-images.githubusercontent.com/41570871/84668979-e6e93680-af41-11ea-8653-46042ee0a992.png">

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
    let handled = RNFirebaseLinks().application(app, open: url, options: options)
      print("Firebase \(handled)")
    return handled
  }
  
  func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool {
   let handled = RNFirebaseLinks().application(application, continue: userActivity, restorationHandler: restorationHandler)
      print("Firebase \(handled)")
    return handled
  }
```
  
<img width="645" alt="Screenshot 2020-06-15 at 7 44 50 PM" src="https://user-images.githubusercontent.com/41570871/84668742-9a9df680-af41-11ea-9362-f8832e3b0acf.png">
<img width="551" alt="Screenshot 2020-06-15 at 7 44 34 PM" src="https://user-images.githubusercontent.com/41570871/84668758-9eca1400-af41-11ea-8a90-b509b411b187.png">

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

<!--- Mark any options that apply below -->

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.
@mikehardy

**Comment by mikehardy** [comment]
You specified react-native-firebase version 5.3.1 - v5 is no longer supported, does this still occur on current version?

**Comment by Nehal-29** [comment]
I can't upgrade it immediately, will need to make lots of changes for it.
But even in the older version It should work. 
Can you just help me out here what setting or configuration I'm missing here that delegate in native side is returning false.
@mikehardy

**Comment by mikehardy** [comment]
Sorry, no. v5 is too old to support - the delta between it and current is astonishingly large and the grace period for upgrade was more than a year
