### ISSUE TITLE
[RN 0.62.2] Failed resolution of: Lcom/google/firebase/Firebaseapp; after manual linking

### ISSUE THREAD

**Issue by kelvin-dev** [invertase/react-native-firebase#3785]
Failed resolution of: Lcom/google/firebase/Firebaseapp; after manual linking

![screenshot-2020-06-16_03 28 04 085](https://user-images.githubusercontent.com/19224355/84702870-7feb7200-af81-11ea-971f-1fb326d3c884.png)

![image](https://user-images.githubusercontent.com/19224355/84702913-8ed22480-af81-11ea-9056-28d52ccdd890.png)

**Comment by mikehardy** [comment]
The issue template was not respected, we have no information to help.
It looks like a standard failure to integrate properly though, here's an example: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh
