### ISSUE TITLE
_firestore.default.collection is not a function

### ISSUE THREAD

**Issue by l4rnaud** [invertase/react-native-firebase#3789]
Got this kind of error when i tried to get a Collection / Document following the exemples available there  : https://rnfirebase.io/firestore/usage

Example - this doesn't work for me : 

_import firestore from '@react-native-firebase/firestore';
const usersCollection = firestore().collection('Users');_

but by doing this, it's ok

_`import firebase from '@react-native-firebase/app';
const firestore = firebase.firestore()
const usersCollection = firestore().collection('Users');``_

**Comment by andersonaddo** [comment]
Template? More info could prove useful.

**Comment by l4rnaud** [comment]
@react-native-firebase/app = 7.2.1
@react-native-firebase/firestore = 7.1.7
react-native = 0.62.2

do you want other information ? what kind ?

**Comment by l4rnaud** [comment]
StackTrace :
ReactNativeJS ▶︎ Possible Unhandled Promise Rejection (id: 5):
                             │ TypeError: _firestore.default.collection is not a function. (In '_firestore.default.collection('Movies')', '_firestore.default.collection' is undefined)

**Comment by mikehardy** [comment]
I'm going to close this. "template" means, when you open a new issue, you follow the template and provide the requested details. I'm not sure what your code looks like but this works for others - you have a local project issue there is not a problem with the module
