### ISSUE TITLE
Maybe be more explicit about v5's deprecation

### ISSUE THREAD

**Issue by andersonaddo** [invertase/react-native-firebase#3791]
Just a trivial though I got while 🚴🏽. 
Maybe we should be more explicit about v5's deprecation in the issue templates and in the docs? (or maybe in the to-be-merged FAQs section in the docs). 

Might reduce the number of v5 issues we get and further encourage upgrading.

**Comment by mikehardy** [comment]
+1 from me

**Comment by Salakar** [comment]
+1 from me too
