### ISSUE TITLE
npm after yarn causes issue with react-native-firebase

### ISSUE THREAD

**Issue by avenyproduction** [invertase/react-native-firebase#3796]
I am starting to work on new RN project and I have installed RNfirebase app, auth and firebase using Yarn (as stated in docs).
Everything worked well
After that I went and installed React Navigation using npm (as stated in their docs).
Then I've got problem running project on iOs simulator.

This is the message I am getting:
warn Package @react-native-firebase/firestore has been ignored because it contains invalid configuration. Reason: Cannot find module '@react-native-firebase/firestore/package.json'

Simulator shows this message:
Unable to resolve module `@babel/runtime/helpers/interopRequireDefault` from `index.js`: @babel/runtime/helpers/interopRequireDefault could not be found within the project.

I will go on with using only Yarn, but it shouldn't maybe be necessary as I have experienced with other modules.

**Comment by andersonaddo** [comment]
Since yarn is really just a wrapper for npm, there shouldn't really be a reason that a module can't be installed with it. 
Anywho, the React Navigation docs also have yarn installation instructions.

**Comment by russellwheatley** [comment]
For the most part, it's fine to use either package manager. But as a general rule, I'd recommend using either `yarn` or `npm` per project.
