### ISSUE TITLE
[QUESTION] Messaging V6 FCM sent to previous production.

### ISSUE THREAD

**Issue by Alejolas** [invertase/react-native-firebase#3799]
## Documentation Feedback

We pushed our app version 1.0.3 to production with just "@react-native-firebase/app" and "@react-native-firebase/analytics" and everything is working fine, we were just using analytics. For a future release we want to implement FCM and installed "@react-native-firebase/messaging"... 

While making an FCM test on devices for a possible version 1.0.4, on debug mode, Android users on production v. 1.0.3 got the test message, remember that version does not have /messaging library installed... how that happen? 

Does that means that the FCM service works on Android without installing "@react-native-firebase/messaging" ? Meaning that the messaging library only works for iOS ? If so, that should be updated on the documentation. 

Thank you for clarifications.

**Comment by russellwheatley** [comment]
It's not possible to use --> `firebase.messaging()....` without `@react-native-firebase/messaging` if that is what you mean.

**Comment by mikehardy** [comment]
But - if you don't attempt to call the APIs, and you send an FCM with notification payload, the SDKs will handle it themselves prior to passing control to anything in react-native-firebase. When I read the report I understood that there may be a case (somehow? how?) where without installing `@react-native-firebase/messaging` the underlying messaging SDK was somehow brought in, thus opening the possibility that an FCM-with-notification would show an unexpected notification

I haven't tested that, but it's plausible if the dependencies aligned in an unexpected way

**Comment by Alejolas** [comment]
> But - if you don't attempt to call the APIs, and you send an FCM with notification payload, the SDKs will handle it themselves prior to passing control to anything in react-native-firebase. When I read the report I understood that there may be a case (somehow? how?) where without installing `@react-native-firebase/messaging` the underlying messaging SDK was somehow brought in, thus opening the possibility that an FCM-with-notification would show an unexpected notification
> 
> I haven't tested that, but it's plausible if the dependencies aligned in an unexpected way

Exactly Mike! That happened... and I was testing on Android but sent the message thru the FCM system on firebase console. I thought it was going to be safe since that version on production didn’t have /messaging installed, but it got thru to 1800 users on Android haha.

**Comment by mikehardy** [comment]
In no way do I mean to make light of your situation but after considering the report, some hours later I thought "aha! That's how those 'test notifications' I read about in the news recently must happen' and chuckled, because they are always paired with a snarky comment about "someone's getting fired..." - though obviously I hope not. Kind of unbelievable this could happen but direct experience is a powerful thing.

Having a look at your Android files (as if you were opening a code issue, not a docs one - the template info we request for that https://github.com/invertase/react-native-firebase/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) might be illuminating

**Comment by Alejolas** [comment]
> In no way do I mean to make light of your situation but after considering the report, some hours later I thought "aha! That's how those 'test notifications' I read about in the news recently must happen' and chuckled, because they are always paired with a snarky comment about "someone's getting fired..." - though obviously I hope not. Kind of unbelievable this could happen but direct experience is a powerful thing.
> 
> Having a look at your Android files (as if you were opening a code issue, not a docs one - the template info we request for that https://github.com/invertase/react-native-firebase/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) might be illuminating

Hahaha I actually sent a message with just text that said: TEST ... luckily. I could have said outrageous things. As for the files, I will post them later for sure. And I would like to take a second to congratulate you guys in all your hard work.
