### ISSUE TITLE
undefined is not an object undefined is not an object FirebaseStorage.Main_budle_path

### ISSUE THREAD

**Issue by ramancodians** [invertase/react-native-firebase#38]
![image](https://cloud.githubusercontent.com/assets/2060784/24724505/f4ff6ac6-1a68-11e7-81cf-af3bec982e2a.png)

This happens when I Import 'react-native-firebase'

**Comment by Ehesp** [comment]
Have you added RNFirebase to the MainApplication?

**Comment by ezcoding** [comment]
Got the same error. The application crashes in Line 147 of **node_modules/react-native-firebase/lib/modules/storage/index.js**

I have successfully added RNFirebase to the MainApplication. The error remains however.

**Comment by ezcoding** [comment]
Nevermind. I forgot to build the project after adding the RNFirebase in `MainApplication`...

**Comment by rom1k** [comment]
@ezcoding 

I have the same error after insalling the module and following the android setup steps.
I did react-native start --reset-cache and react-native run-android but i'm still getting the error. 

Any ideas?

**Comment by Salakar** [comment]
@ramancodians this is most likely the same issue as @ezcoding please make sure you follow the android setup docs and add the bits to MainApplication. If this issue still persists then I'll re-open this issue.
