### ISSUE TITLE
Issue with global variables and other libs

### ISSUE THREAD

**Issue by sirilicious** [invertase/react-native-firebase#380]
I just came across the issue I described [here](https://github.com/layerhq/layer-websdk/issues/168).

The issue was caused by that [line](https://github.com/invertase/react-native-firebase/blob/ceedf9b85aed2f66954a3ccdcdf7e23e8715ee0e/lib/utils/log.js#L5) - IMHO using global variables is extremely dangerous. can you guys fix this?

**Comment by Salakar** [comment]
@sirilicious Dangerous how exactly? ;p RN isn't the same as the web, it's a closed global with the only way to access it being via the apps code itself, there's no web console on the device, same thing applies for node server side apps. The 'danger' is only for websites (as there's a console), or apps that use `eval()` - when they shouldn't be. 

Having said that, this was needed for bows to work annoyingly - however I'd like to get rid of it as a dependancy and plan to do so in the next couple of days whilst working on the next alpha for v3.
