### ISSUE TITLE
Does Firebase Phone Authentication work good with SMS Retriever API (Android)

### ISSUE THREAD

**Issue by felire** [invertase/react-native-firebase#3808]
My problem is quite simple and I think I don't need all this structure. Is this behaviour possible with the actual version of `react-native-firebase`? Because the structure of the firebase messages are not like the sms rules of SMS Retriever API. And watching some issues of Android Firebase I read that Firebase handle that by itself. But I don't know if there is some way to do this with `react-native`. What I want to do is the auto-complete of the verification code

**Comment by mikehardy** [comment]
On Android, if an SMS auth code comes in, the Google Android Frebase SDKs will consume the message and automatically log the user in, which will result in an event fired to the onAuthStateChanged listener

https://rnfirebase.io/auth/usage#listening-to-authentication-state

At which point you move right in to your app.

Without `@react-native-firebase/auth` installed (which implies `@react-native-firebase/app` this does not happen and there is no way for it to happen that I am aware of.
