### ISSUE TITLE
🔥 Link Multiple Auth Providers (email/facebook to an Account?

### ISSUE THREAD

**Issue by airowe** [invertase/react-native-firebase#3809]
## Issue
I have checked out other (much older) issues for linking two provider credentials when getting the `auth/account-exists-with-different-credential` error, but one of them says support will be added for `linkWithCredential` and another gives a lengthy workflow to prompt the user to sign in with another provider if the current user is null.

Is there more up-to-date documentation on how to link two providers when the current user is null? The specific workflow I'm having trouble with is -->

- User signs in with email/password
- User then attempts to sign in with Facebook

This results in the aforementioned error, but I am unable to get the current user value to link the two accounts and don't see another workaround.

Describe your issue here

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
  - Authentication
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Still the "lengthy workflow" for me. The credential is the email address, so get the other providers for that email address, and link them in. The lengthy bit is because, is that what the user wants? Maybe they want separate accounts? At which point you have to tell them to go delete the other one if they want to use the social login, and sign up with a different email or something. So you have to check first. It's messy but in my experience the way humans manage their online identities and accounts is messy, have to handle it

**Comment by fase** [comment]
I am having a similar issue linking Facebook to any existing account.  Google and Apple call `auth().signInWithCredential(credential);` without throwing an `auth/account-exists-with-different-credential` error.  They link to the correct Firebase account automatically.  Facebook throws this every time and `auth().currentUser` returns null so calling linkWithCredential is not possible.

**Comment by airowe** [comment]
Thanks for getting back to me @mikehardy. I implemented this solution and got things working for a seamless linking (if it's ok to assume that your users would like that behavior): https://github.com/cheungt6/public/tree/master/react-native-firebase-socialauth
