### ISSUE TITLE
getToken not working on device ios when build release Testflight

### ISSUE THREAD

**Issue by tunm1228** [invertase/react-native-firebase#3816]
"@react-native-firebase/app": "^7.2.1",
    "@react-native-firebase/auth": "^8.0.5",

  let firebaseToken = await messaging().getToken()

**Comment by russellwheatley** [comment]
Please fill in the template.

**Comment by tunm1228** [comment]
please help me, I encountered this error code [message/unregistered] when call function messaging().getToken()

**Comment by tranduy1401384** [comment]
![Screenshot 2020-06-22 at 16 00 33](https://user-images.githubusercontent.com/34645003/85269041-8908a180-b4a1-11ea-9077-cecd7f1790a6.png)

**Comment by tunm1228** [comment]
thank pro, i check and missing for the part Push Notification (release) <3

**Comment by lucassouza16** [comment]
> thank pro, i check and missing for the part Push Notification (release) <3

Hi, I'm dealing with the same problem, how did you manage to solve it?
