### ISSUE TITLE
Don't want to enlarge the image in the notification.

### ISSUE THREAD

**Issue by 345ml** [invertase/react-native-firebase#3818]
Our mobile app shows images in our notifications.
When expand in on the notification, the image is enlarged, but I don't want to enlarge the image.

This is intended to be a use case where, for example, a small image, such as a user icon, is displayed on the right side of the notification.

Is there an option to set this up?

<img width="1151" alt="Screen Shot 2020-06-22 at 20 00 28" src="https://user-images.githubusercontent.com/8254811/85280430-16a8b900-b4c3-11ea-967c-ab5edaecedf3.png">

**Comment by andersonaddo** [comment]
Doesn't look like it. 
You might have to go for a third party push notification package (coupled with data only FCM messages) if you really want this.

**Comment by 345ml** [comment]
So there's an approach that uses data messages.
I will consider it.
