### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by AfanasievAM** [invertase/react-native-firebase#3822]
Pls Help
I have 2 Swift Compiler Error

MacOs Catalina
CocoaPods Last version
Xcode Version 11.6 beta (11N700h)

Error #1
messenger/ChatApp/Core/Chat/ViewControllers/ATCChatThreadViewController.swift:25:80: 'MessageInputBarDelegate' has been renamed to 'InputBarAccessoryViewDelegate'

messenger/Pods/MessageKit/Sources/Supporting/MessageInputBar.swift:32:18: 'MessageInputBarDelegate' has been explicitly marked unavailable here

Error #2
messenger/ChatApp/Core/Chat/ViewControllers/ATCChatThreadViewController.swift:326:36: 'MessageInputBar' has been renamed to 'InputBarAccessoryView'

messenger/Pods/MessageKit/Sources/Supporting/MessageInputBar.swift:29:18: 'MessageInputBar' has been explicitly marked unavailable here

**Comment by mikehardy** [comment]
These appear to have nothing to with react-native-firebase.
No template, can't help
