### ISSUE TITLE
Can't get badge count when app is not in foreground - iOS

### ISSUE THREAD

**Issue by dhevendhiran-adt** [invertase/react-native-firebase#3826]
## Issue

Hey, I can't get the badge count on ios when the app is in the background and closed. 
I have referred this issue #1824. But it has closed, I didn't get any solution from that.

I am sharing a piece of code what I have used to get notifications
```
this.notificationListener = firebase
      .notifications()
      .onNotification(async (notification) => {

        const localNotification = new firebase.notifications.Notification({ show_in_foreground: false })
          .setNotificationId(notification.notificationId)
          .setTitle(notification.title)
          .setBody(notification.body)
          .setData(notification.data)
          .android.setChannelId("fcm_default_channel")
          .android.setSmallIcon("@drawable/wasfat")
          .android.setAutoCancel(true)
          .android.setColor("#b61b33")
          .android.setPriority(firebase.notifications.Android.Priority.High);

        let badgeCount = await firebase.notifications().getBadge();
        firebase.notifications().setBadge(badgeCount + 1);

        firebase.notifications().displayNotification(localNotification).catch(err => { });
      });
```

from the above code, I'm getting notification very fine in all cases. But I'm able to get badge count, only app is in the foreground.

Please suggest, If anything I have missed to get badge count when the app is in the background and closed. 

I am facing this only on ios. For android, it is working fine without the setBadge() method.

Thanks for any help.

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ Y] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 255.59 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

- **Platform that you're experiencing the issue on**:
  - `iOS`
- **`react-native-firebase` version you're using that has this issue:**
  - `5.5.6`
- **`Firebase` module(s) you're using that has the issue:**
  - `firebase.notifications()`
- **Are you using `TypeScript`?**
  - `N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by andersonaddo** [comment]
Chances that you'll find a solution for this from maintainers isn't great - v5 had been deprecated a while back.

**Comment by dhevendhiran-adt** [comment]
> Chances that you'll find a solution for this from maintainers isn't great - v5 had been deprecated a while back.

yeah, the same we felt so. we are planning for the update now. Actually Its been two months, we have planned for v6 update. But the notification feature was not there. I think now it is available.

**Comment by mikehardy** [comment]
Notifications is not and will not really be available in v6 - it's expected you will integrate with a separate library for local device notifications and firebase will just handle cloud messages (with the possibility of the underlying SDKs displaying notifications in some cases, but outside of react-native-firebase control). You'll want either notifee, react-native-push-notification or react-native-notifications to control local device notification display. There are success reports with all of them, but also it's just a difficult area in general so plenty of config problems and API usage mistakes too.

**Comment by dhevendhiran-adt** [comment]
> Notifications is not and will not really be available in v6 - it's expected you will integrate with a separate library for local device notifications and firebase will just handle cloud messages (with the possibility of the underlying SDKs displaying notifications in some cases, but outside of react-native-firebase control). You'll want either notifee, react-native-push-notification or react-native-notifications to control local device notification display. There are success reports with all of them, but also it's just a difficult area in general so plenty of config problems and API usage mistakes too.

ohh! thanks for the reply @mikehardy. In that case, If we continued with the firebase v5 notification, we are getting a problem with getting the badge count on ios as mentioned above. Can you please help us to find the possible workarounds?

**Comment by mikehardy** [comment]
@dhevendhiran-adt no, I can't help, sorry
