### ISSUE TITLE
After upgrade can't compile firestore project

### ISSUE THREAD

**Issue by bchapoton** [invertase/react-native-firebase#3828]
## Issue
Hi, I update my react-native project today, from 0.61.5 to 0.62.2, I encounter some issues with react-native-firebase dependencies, so I update our firebase dependencies too.

I update all the dependencies in the last available version, as you can see below in the package.json. I also update gradle in the process from 5.5 to 6.0.1.

I make a gradlew clean in the android/ folder, then when I try to run android application during the build I have this error : 

> > Task :react-native-firebase_firestore:compileDebugJavaWithJavac FAILED
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
> 92 actionable tasks: 14 executed, 78 up-to-date
> D:\workspace\myproject\node_modules\@react-native-firebase\firestore\android\src\reactnative\java\io\invertase\firebase\firestore\ReactNativeFirebaseFirestoreQuery.java:123: error: cannot find symbol
>       query = query.limitToLast(limitToLast);
>                    ^
>   symbol:   method limitToLast(int)
>   location: variable query of type Query
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 1 error
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-firebase_firestore:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 18s
> 
> error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
> Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
> D:\workspace\myproject\node_modules\@react-native-firebase\firestore\android\src\reactnative\java\io\invertase\firebase\firestore\ReactNativeFirebaseFirestoreQuery.java:123: error: cannot find symbol
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

What I understand of the error message, is it probably a dependency error within the java class, and the compiler can't find the method limitToLast(), I tried to clear my cache, and retry, but I still have this problem.

I search few hours on the internet, but I don't find anything revelant, someone have any idea on what going on ?

Thanks !

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
    ...
    "@react-native-firebase/app": "7.3.0",
    "@react-native-firebase/auth": "8.0.7",
    "@react-native-firebase/firestore": "7.2.1",
    "@react-native-firebase/messaging": "7.1.7",
    "@react-native-firebase/storage": "7.1.5",
    ...
}
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ x] my application is an AndroidX application?
- [ x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You have an android build failure but provide no android files, can't help.
Here is a working example that compiles correctly for android, from start to finish, clone the repo, run it, compare the generated throwaway project with yours: the problem will be in the difference: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh
