### ISSUE TITLE
Encountering an error which shouldn't exist anymore: "Error: firebase.firestore().runTransaction() Every document read in a transaction must also be written."

### ISSUE THREAD

**Issue by zaptrem** [invertase/react-native-firebase#3829]
## Issue

Encountering error ```Error: firebase.firestore().runTransaction() Every document read in a transaction must also be written.```
Even though I'm writing to the only doc I'm reading from, and this limitation was removed completely from Firestore in January with Firestore 1.10.0 (RNfirebase is now on 1.14.0). 

Here's the code I encountered it with:
https://stackoverflow.com/questions/62528913/rnfirebase-error-every-document-read-in-a-transaction-must-also-be-written

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
No template, no info to help
Perhaps `npx react-native-clean-project`

**Comment by zaptrem** [comment]
@mikehardy Fixed: https://github.com/invertase/react-native-firebase/issues/3830
