### ISSUE TITLE
Detecting sync process

### ISSUE THREAD

**Issue by rodolfobarretoweb** [invertase/react-native-firebase#383]
Hello guys!
I have a question, is there a way to detect the sync process? I wish to put some load when my app is syncing with the server.

PS: I`m not using method on, so the first option is to get data from local storage

**Comment by Salakar** [comment]
Not possible as far as I know in either the firebase web sdk or the native sdk's sorry. RNFirebase server syncing won't affect your js code though as this is all done natively and not in JS, so load shouldn't be a problem.
