### ISSUE TITLE
Custom events and user property not showing on firebase analytics console from a signed apk

### ISSUE THREAD

**Issue by egaleme** [invertase/react-native-firebase#3835]
## Issue

Describe your issue here

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by andersonaddo** [comment]
With no template, we can't help. 
Also, v5 has been deprecated.

**Comment by egaleme** [comment]
See I'm using the latest version. In debug mode all my custom events and user property shows on the firebase analytics dashboard. Buy when I build the Android app for release. No custom events or user property shows anymore. I have searched through the internet for solutions none forth coming.

**Comment by mikehardy** [comment]
With no information provided in the template, no one has information necessary to help, so no solution will be forthcoming, no

**Comment by egaleme** [comment]
### using :
 "@react-native-firebase/analytics": "^7.1.4",
 "@react-native-firebase/app": "^7.2.1",

### android/build.gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        // buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "28.0.0"
        // googlePlayServicesAuthVersion = "15.0.1"
    }
    repositories {
        google()
        jcenter()
        mavenLocal()
        
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.0")
        // classpath('com.android.tools.build:gradle:4.0.0')
        // classpath "com.google.gms:google-services:4.2.0"
        classpath("com.google.gms:google-services:4.3.3")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            android {
              compileSdkVersion 29
              buildToolsVersion "29.0.2"

              defaultConfig {
                minSdkVersion 19
                targetSdkVersion 29
                // versionCode 1
                // versionName "1.0"
              }    // version of build tool used for project
            }
        }
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://jitpack.io'
        }
        // maven {
        //     url 'https://maven.google.com'
        //     name "Google"
        // }
    }
}


### android/app/build.gradle 

buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: "com.android.application"



import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.leadway.pensure"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 200096
        versionName "3.0.4"

         multiDexEnabled true
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }

}

dependencies {
    implementation project(path: ":@react-native-firebase_app")
    implementation project(path: ":@react-native-firebase_analytics")
    implementation project(':react-native-webview')
    implementation project(':react-native-version-number')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-reanimated')
    implementation project(':react-native-onesignal')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-image-picker')
    implementation project(':react-native-gesture-handler')
    implementation project(':react-native-fingerprint-scanner')
    implementation project(':react-native-device-info')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  
    // From node_modules
    // implementation "com.google.android.gms:play-services-base:15.0.1"
    // implementation "com.google.firebase:firebase-core:16.0.9"
    // implementation "com.google.firebase:firebase-analytics: 16.5.0"

    //implementation 'com.google.android.gms:play-services:12.0.1'
    implementation platform("com.google.firebase:firebase-bom:24.5.0")
    
    implementation "com.google.android.gms:play-services-analytics:17.0.0"

    implementation "com.google.android.gms:play-services-base:17.3.0"
    implementation "com.google.firebase:firebase-core:17.4.3"
    implementation "com.google.firebase:firebase-analytics:17.4.3"
    implementation "com.google.firebase:firebase-inappmessaging:19.0.7"
    implementation "com.google.firebase:firebase-inappmessaging-display:19.0.7"
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: "com.google.gms.google-services"


### screen
import React, {Component} from 'react';
import {StyleSheet, View, Platform, Image} from 'react-native';
import {CONTAINER_STYLE} from "../shared/Styles";
import {BoldText, CommonHeader, RegularText} from "../components";
import VersionNumber from 'react-native-version-number';
// import firebase from 'react-native-firebase';
import analytics from '@react-native-firebase/analytics';

class About extends Component {

    componentDidMount() {
        analytics().setCurrentScreen("About Screen", "AboutScreen")
    }
    

    render() {
        let platforOS;
        if (Platform.OS === "android")
            platforOS = "Android";
        else if (Platform.OS === "ios")
            platforOS = "iOS";
        return (
            <View style={CONTAINER_STYLE}>

                <CommonHeader title='About'
                              backAction backActionPress={() => this.props.navigation.goBack()}
                />

                <View style={styles.column}>
                    <View style={{alignItems: 'center'}}>
                        <BoldText label='Pensure App' size={22} style={{marginBottom: 5}}/>
                        <RegularText label={VersionNumber.appVersion} size={16}/>
                    </View>

                    <Image
                        source={require('../assets/images/logo.png')}
                        style={styles.imageStyle}
                        resizeMode='cover'
                    />

                    <View style={{alignItems: 'center'}}>
                        <BoldText label='Platform' size={20} style={{marginBottom: 5}}/>
                        <RegularText label={platforOS} size={16} style={{marginBottom: 15}}/>

                        <BoldText label='Platform Version' size={20}/>
                        <RegularText label={Platform.Version} size={16}/>
                    </View>
                </View>

            </View>
        );
    }
}

const styles = StyleSheet.create({
    imageStyle: {
        height: 150,
        width: 150,
        justifyContent: 'center',
        alignItems: 'center',
    },
    column: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'space-evenly'

    }
});

export default About;

**Comment by Keshava11** [comment]
This is the same issue I have been facing too. 
Proper dependencies for firebase analytics present in build.gradle 

`sFirebaseAnalytics.setUserProperty(iPropertyName, iPropertyValue);`

Also it is release build.

**Comment by martin-richter-uk** [comment]
I have the same problem.

**Comment by mikehardy** [comment]
@martin-richter-uk - if you are having the same problem as this user from nearly a year ago that implies you are using our old old old v7 here, which is almost software developer malpractice at this point! We're on v11.3.x. Definitely upgrade, and (more seriously) if you are truly having the same problem you should file a new issue but (unlike this one) while respecting the issue template so we may help.

**Comment by anupamhore** [comment]
mine is 11.4 still the same problem. Not able to see any analytics in the dashboard.

**Comment by mikehardy** [comment]
Maybe related https://rnfirebase.io/faqs-and-tips#i-have-a-custom-analytics-parameter-called-items-and-its-not-showing-up-on-the-firebase-console-how-come
