### ISSUE TITLE
Firebase Realtime Database snapshot.forEach was not display suggestions

### ISSUE THREAD

**Issue by Eumhongin** [invertase/react-native-firebase#3836]
<img width="518" alt="스크린샷 2020-06-25 오후 11 04 56" src="https://user-images.githubusercontent.com/23710025/85735105-6e038f00-b738-11ea-92db-c819e33c737b.png">

Maybe Functions is Problem..

[https://github.com/invertase/react-native-firebase/issues/3823](url)
i think same problem

This is Firebase Database Admin ts
<img width="549" alt="스크린샷 2020-06-25 오후 11 10 09" src="https://user-images.githubusercontent.com/23710025/85735929-0863d280-b739-11ea-948e-737337dc8bb0.png">

Then i Fixed it. suggestion work.
<img width="558" alt="스크린샷 2020-06-25 오후 11 13 32" src="https://user-images.githubusercontent.com/23710025/85736496-8031fd00-b739-11ea-9d10-c7a4bb65f2f0.png">

how can i push this code?..

**Comment by andersonaddo** [comment]
Go ahead and make a pull request!

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

https://opensource.com/article/19/7/create-pull-request-github
