### ISSUE TITLE
iOS undefined is not an object (evaluating 'FirebaseAnalyitcs.SetCurrentScreen');

### ISSUE THREAD

**Issue by SMJ93** [invertase/react-native-firebase#385]
First of all, great plugin! Works like a charm on Android!

### Issue

I am having some problems getting iOS working. I have installed Firebase analytics using the instructions provided. Everything seems to be installed correctly.

Firebase starts and creates an event in the native SDK (from the Xcode debug window):
```
[Firebase/Analytics][I-ACS023007] Firebase Analytics v.40003000 started
[Firebase/Analytics][I-ACS016002] Event created with previous timestamp after current timestamp
```
If I look at the StreamView in Firebase Analytics I can see the user as expected.
But then when I run `RNFirebase.analytics().setCurrentScreen(page);`.

In the simulator I see the error:
```
Then I get undefined is not an object (evaluating 'FirebaseAnalyitcs.setCurrentScreen');
```

In the Xcode debug window it says:
```
[warn][tid:com.facebook.react.JavaScript] Firebase analytics native sdk has not been included in your podfile - analytics methods have been disabled.
```

If I run `console.log(RNFirebase);` it outputs the following object:

![screen shot 2017-09-04 at 16 08 52](https://user-images.githubusercontent.com/2145641/30032010-8b1448da-918b-11e7-80bc-584672a81c06.png)

In the console it also says
```
Firebase analytics native sdk has not been included in your podfile - analytics methods have been disabled
```

So everything seems to be setup correctly, but the RNFirebase library can't seem to find the Native SDK for iOS.

### Environment

1. Application Target Platform: **iOS**
2. Development Operating System: **macOS Sierra**
3. Build Tools: **Xcode Version 9.0 beta 6**
4. React Native version: **0.47.2**
5. RNFirebase Version: **2.1.3**
6. Firebase Module: **Analytics**

**Comment by Salakar** [comment]
@SMJ93 weird one, https://github.com/invertase/react-native-firebase/blob/v2.x.x/lib/modules/analytics/index.js#L74 is the internals for that, not sure why there's a capital `S` in set current screen either on your error `undefined is not an object (evaluating 'FirebaseAnalyitcs.SetCurrentScreen');`

How are you initialising RNFirebase, also could we see your podfile also

**Comment by SMJ93** [comment]
Thanks for the quick response! Sorry yes that was a typo, in the code I used `RNFirebase.analytics().setCurrentScreen(page);`.

I haven't used a POD file. I have installed all of the SDK's and their dependencies manually from each of the PodSpec's and place them in a `ios/Pods` before manually linking them to the targets in `Frameworks and Libraries`: https://github.com/CocoaPods/Specs/blob/master/Specs/0/3/5/Firebase/4.1.1/Firebase.podspec.json.

The SDK's are working as expected so maybe it's something to do with the Search Header Paths? Seems like the RN Firebase bridge cant find the native SDK's.

**Comment by Ehesp** [comment]
@SMJ93 Are you not initializing Firebase before you use it?

Make sure you're calling initializeApp before: https://invertase.io/react-native-firebase/#/v2/usage

**Comment by SMJ93** [comment]
@Ehesp  Yes, I use `const RNFirebase = Firebase.initializeApp();` to initialise it and then call `RNFirebase.analytics().setCurrentScreen(page);` each time the user changes route.

**Comment by Salakar** [comment]
@SMJ93 are you able to come on Discord and DM me, or twitter, I could screenshare and take a look - if you wanted.

**Comment by SMJ93** [comment]
@Salakar I've dm'd you on twitter. Thanks!

**Comment by SMJ93** [comment]
@Salakar, @Ehesp, we finally resolved this by removing the carot (`^`) from the `package.json` file.
`v2.1.3` works, but `v2.1.4` seems to be broken with RN `0.47.2`

**Comment by Salakar** [comment]
Have a feeling this was derived cache data in xcode screwing this up, similar to #391

**Comment by Jose4gg** [comment]
The @SMJ93 solution worked for me, Are you going to review this?
