### ISSUE TITLE
Firebase Auth : [auth/unknown] A network error (such as timeout, interrupted connection or unreachable host) has occurred

### ISSUE THREAD

**Issue by ththugues44** [invertase/react-native-firebase#3855]
Hello , 

My Application is in production and the verification works well, but I have a problem with the verification of phone numbers on  phones Samsung and other with run Android 5.X , 7.0.

The exeution of this code:
```
firebase
         .auth ()
         .verifyPhoneNumber (phoneFullNumber)
```

generate the error: `[auth/unknown] A network error (such as timeout, interrupted connection or unreachable host) has occurred`

My Package : 
"@react-native-firebase/app": "^6.4.0",
"@react-native-firebase/auth": "^6.3.4",
 "react-native": "0.61.5"

Thanks

**Comment by mikehardy** [comment]
Definitely upgrade to most current stable versions of the software (including overriding the firebase SDKs to their most current versions - they do work fine) before we try troubleshooting

**Comment by mikehardy** [comment]
Secondly, follow the issue template...

**Comment by ththugues44** [comment]
@mikehardy I have proceeded to an update, as requested:
```
     "@ react-native-firebase / app": "^ 7.3.1",
     "@ react-native-firebase / auth": "^ 8.0.8",
```
but the users who are on android 5.X always encounter this same problem of` [auth / network-request-failed] A network error`

Thank you

**Comment by mikehardy** [comment]
Only on Android 5? :thinking: have you checked even farther down, to Android 4.1? The only differences I'm aware of that require special handling down on those older APIs are for TLS1.2 support (but firebase handles things for you) and MultiDex (which you have to set up yourself)

You didn't follow the template at all though so I can't help

**Comment by ththugues44** [comment]
@mikehardy Please where can I have the template ?

**Comment by mikehardy** [comment]
Close this issue, and open a new one, and this time don't delete the thing in the text box asking you for information, rather, provide the information requested.

**Comment by ththugues44** [comment]
@mikehardy => https://github.com/invertase/react-native-firebase/issues/3858
