### ISSUE TITLE
Analytics setUserProperty is set But not showing in console

### ISSUE THREAD

**Issue by mym0404** [invertase/react-native-firebase#3859]
## Issue

I am using react native firebase analytics package for logging events with user properties. 
I can see user properties are set like this in DebugView.
![image](https://user-images.githubusercontent.com/33388801/86074893-ba94f480-bac1-11ea-9c8b-59e8b4b91f58.png)

But in `User Properties` tab in the left pane, my properties are not showing. and If I add properties manually and target with properties in services like FCM then there is no use having these properties.

![image](https://user-images.githubusercontent.com/33388801/86076180-a4d4fe80-bac4-11ea-947b-46e67bf8f60a.png)

![image](https://user-images.githubusercontent.com/33388801/86076216-af8f9380-bac4-11ea-841a-8d5e9efe2423.png)

Is there are further steps to unlock this feature? Thank you.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
target 'MathKing' do
  # Pods for MathKing
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

	
	pod 'SPPermissions/Notification'

	pod 'Firebase/Analytics'
	pod 'FirebaseInstanceID'
	
  pod 'RNSentry', :podspec => '../node_modules/@sentry/react-native/RNSentry.podspec' # or your path to node_modules

  use_native_modules!
	
	# Enables Flipper.
	#
	# Note that if you have use_frameworks! enabled, Flipper will not work and
	# you should disable these next few lines.
	add_flipper_pods!
	post_install do |installer|
		flipper_post_install(installer)
	end

end
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.3.72'
    ext {
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()

        maven { url 'https://maven.fabric.io/public' }

    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.2")
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'io.fabric.tools:gradle:1.28.1'
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        maven { url 'http://devrepo.kakao.com:8088/nexus/content/groups/public/' }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
        mavenCentral()
    }
}

```

#### `android/app/build.gradle`:

```groovy
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }

    implementation 'com.facebook.android:facebook-android-sdk:5.13.0'

    implementation 'androidx.multidex:multidex:2.0.1'
    implementation "androidx.core:core-ktx:1.2.0"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation 'com.google.firebase:firebase-analytics:17.3.0'

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.fbjni'
    }
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }
    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    implementation 'com.google.android.gms:play-services-ads:15.0.0'
    implementation 'com.android.installreferrer:installreferrer:1.1.1'

}

dependencies {
    // Required -- JUnit 4 framework
    testImplementation 'junit:junit:4.12'
    // Optional -- Robolectric environment
    testImplementation 'androidx.test:core:1.2.0'
    // Optional -- Mockito framework
    testImplementation 'org.mockito:mockito-core:2.28.2'
}
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
![image](https://user-images.githubusercontent.com/33388801/86074765-83264800-bac1-11ea-9db7-1bd67bcb48d8.png)

- **Are you using `TypeScript`?**
  - `Y` & `3.8.3`
- **Are you using `Expo`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by egaleme** [comment]
Also have the same issue. I don't know why the invertase isn't answering this issue.

**Comment by mikehardy** [comment]
Probably because it's open source and everyone is busy? If this is a serious problem for you:
- crack open the module in node_modules
- put some console.log() debug statements in the API calls you are using, verify they are all being called as expected with the arguments expected
- put some log statements in the native code in the module for those API calls, to make sure the data is passed down to the underlying API correctly. Fix it if not.
- If everything is being passed down correctly, verify your project setup, look in the upstream repos for issues

There's no magic code fairy in open source, it's us. We have to help ourselves

**Comment by mym0404** [comment]
This is resolved after I added my user properties manually in the console. I don't know why.

**Comment by mikehardy** [comment]
@mym0404 that's interesting - can you break down the exact chain of events to maybe help others. I'm just guessing but I infer:
- you started using analytics to set user properties
- they were not showing up on the firebase web console?
- you went to the firebase console and... I am unsure here? configured something?
- you tested JS code in a react-native-firebase app again that set analytics user properties
- they showed up on the firebase web console?
