### ISSUE TITLE
Can't update badge count when app has closed - iOS

### ISSUE THREAD

**Issue by dhevendhiran-adt** [invertase/react-native-firebase#3860]
## Issue

Describe your issue here
Hi, we are using react native firebase version 6 messaging to handle push notification. From the remote notification content, we are not able to increment/ decrement the badge count on ios. So we are using [push notification ios](https://www.npmjs.com/package/@react-native-community/push-notification-ios) to set badge count.

 It is working very well when app is in the foreground and background. But when app is closed, we are able to receive the notification, but not able to update badge count.

```
messaging().onMessage(async remoteMessage => {
      Alert.alert('A new FCM message arrived!', JSON.stringify(remoteMessage));
});

messaging().setBackgroundMessageHandler(async remoteMessage => {
      PushNotificationIOS.getApplicationIconBadgeNumber(number => {
        PushNotificationIOS.setApplicationIconBadgeNumber(number + 1);
      });
      asyncstorage.saveItem("remoteMessage", "only one killed message received");
    });
```

here setBackgroundMessageHandler is working when the app is in the background state. As per the documentation, this method should invoke even when the app is closed. But it is not. For more clarification, I have done an async storage operation inside this method when the app has killed. But it is not working as expected.

I am adding the server side data also which I have sent for notification from the backend,

```
{
"to":".................",
"notification":{
 "title":"Working Good",
 "body":"backgroudn noti",
 "badge":"1",
 "sound":"./app/assets/sound/alert.wav"
},
"priority":"high",
"badge":"1",
"content_available":true
}
```

I would like to mention some points with these keys,

There is a badge inside the notification object, which is setting to the icon every time even the app is closed. But not able to increment/ decrement the badge count. It is always 1. 

After adding "**content_available**" property, I am able to get update the badge count. This means after adding content_available only, I got the trigger inside **setBackgroundMessageHandler** method and I updated the badge count using push notification ios property. 

Now I am not getting any trigger inside **setBackgroundMessageHandler** method when app is closed.

Is there any other keys I need to add to get the trigger inside **setBackgroundMessageHandler** method, even the app is closed?

I planned to try with some background libraries like **react-native background fetch**. But after receiving notification, without getting any trigger in the code, I can't trigger the background fetch library also to wake up the application. 

**So how can I get into this method, while receiving notification when app closed?**

Please ping me if any more details are needed to clarify the issue. Thanks for the any help.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 110.27 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

- **Platform that you're experiencing the issue on**:
  - [x ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `7.3.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/messaging": "^7.1.7"`
- **Are you using `TypeScript`?**
  - `N` & `VERSION`
- **Are you using `Expo`?**
  - `N` & `SDK VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by forbesgillikin** [comment]
I posted in this issue yesterday #3530 , but understanding the latest APNs headers may help you with your issue here.

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns/
