### ISSUE TITLE
New firebase library is not support group notification in android.

### ISSUE THREAD

**Issue by TrushalRank** [invertase/react-native-firebase#3861]
I am using below firebase library version for push notification, In that version not support **group notification**. In earlier version 'react-native-firebase' it worked. If any one have solution with new latest library code then help me for that.

    "@react-native-firebase/analytics": "^7.1.4",
    "@react-native-firebase/app": "^7.2.1",
    "@react-native-firebase/messaging": "^7.1.6"

**When the multiple notification getting in same application then set as group and display to like as below in notification bar.**

![p04uO](https://user-images.githubusercontent.com/49527805/86134930-cc998600-bb07-11ea-9147-052b47330b7a.png)

Thanks for the help in advance !!

**Comment by andersonaddo** [comment]
Do you mean this: https://firebase.google.com/docs/cloud-messaging/android/device-group#managing_device_groups

Regardless, you didn't fill the template, so there's a high chance help will me minimal.

**Comment by TrushalRank** [comment]
@andersonaddo , No i am referring to below. when multiple notification getting from same application then it will make in a group and display as below.
![p04uO](https://user-images.githubusercontent.com/49527805/86133526-09647d80-bb06-11ea-931a-a7ebcca1a2bc.png)

**Comment by mikehardy** [comment]
You will want to integrate a full-featured local notification library for this functionality
react-native-firebase is focused exclusively on wrapping firebase functionality

That implies cloud messaging, and there is a small intersection with local notifications in that the firebase SDKs will display a notification if you send one directly, but there is no other support for device notification APIs in the firebase libraries and there is none here in v6+

Options: notifee, react-native-push-notification, react-native-notifications - all have reported user success integrating with react-native-firebase handling the cloud messages and those libraries handling notifications
