### ISSUE TITLE
Getting issue with phone auth.

### ISSUE THREAD

**Issue by S-Saagar1** [invertase/react-native-firebase#3863]
I'm getting below error while using a normal phone number. With the testing phone number, it is working fine. Any solution?

I apply all solutions I found on a search like change firebase account, replace JSON, try different os, and their sha-1. But the same result I found in all cases.

This issue is happening in Android did not check in iOS.

I am using latest SDK and latest doc from rnfirebase website.

NativeFirebaseError: [auth/rejected-credential] The request contains malformed or mismatching credentials [ App ID does not match requested project. ]
signInWithPhoneNumber$@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:104564:91
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:26922:23
invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27098:32
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:26922:23
invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:26998:30
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27028:19
tryCallTwo@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:28869:9
doResolve@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:29033:25
Promise@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:28892:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27027:33
enqueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27032:157

**Comment by S-Saagar1** [comment]
Hi,

Any update on this issue. I wan a live my app on the google app store. So please update as soon as possible.

**Comment by mikehardy** [comment]
@S-Saagar1 your project is misconfigured. The error message appears pretty clear, it's from the underlying SDK. There won't be more activity on this issue I don't think, phone auth is working in my project indicating the module functions. Examine the error message carefully and  your config to find the error - they can be subtle but it's in there somewhere.

**Comment by RathaIct** [comment]
I have the same problem. Solution please go to **Google Play Console** click on your app after find **Setup->App Signing**. In App signing key certificate copy key in **SH-1** and upload to Project Setting Android in Firebase. I think it should be work.
