### ISSUE TITLE
[Play Services utilities] resolutionForPlayServices

### ISSUE THREAD

**Issue by Bardiamist** [invertase/react-native-firebase#3864]
## Issue

`resolutionForPlayServices` don't work.

## Reason

[Here is](https://github.com/invertase/react-native-firebase/blob/master/packages/app/lib/utils/index.js#L72) should be
 ```
return this.native.androidResolutionForPlayServices();
```
instead
```
return this.native.androidGetPlayServicesStatus();
```

**Comment by mikehardy** [comment]
Nice one. Was looking for something easy to start the day and here this is on a silver platter, I just posted up the obvious one-liner to fix, thanks @Bardiamist

**Comment by Bardiamist** [comment]
Thanks:)
