### ISSUE TITLE
Crashlytics 8.0.0 iOS docs outdated

### ISSUE THREAD

**Issue by pehagg** [invertase/react-native-firebase#3871]
## Documentation Feedback

The extra steps for setting up Crashlytics for iOS seems to be outdated. Cocoapods adds a build phase script named "[CP-User] [RNFB] Crashlytics Configuration", which already contains a call to `${PODS_ROOT}/FirebaseCrashlytics/run`, so if I understand this correctly, the additional setup is in fact no longer needed. Also, the screenshot in the page is outdated since @react-native-firebase/crashlytics 8.0.0, as it refers to Fabric.

Addition to original issue: some of the crash attributes have been removed from the interface, e.g. setUserName and setUserEmail, but these are still referred to in the docs.

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! The PR that updated it to finish the migration from Fabric just landed, and the docs may not have caught up. If you could a PR to update them that would be fantastic - there's an edit button at the top right of each page and github makes it pretty painless. I'm afraid the people that worked on the PR don't have the fresh perspective to fix the docs anymore 😅

**Comment by pehagg** [comment]
@mikehardy , I'll try to get around to do this during the weekend.
