### ISSUE TITLE
[iOS] - onMessage problem

### ISSUE THREAD

**Issue by franj0** [invertase/react-native-firebase#3872]
## Issue

Describe your issue here
Hi everyone,

I have problem with FCM Messages not FCM push notifications.
my onMessage() listener works fine on Android(simulator/real device) but iOS onMessage trigger only for Simulator, for real device it's not working
ps. Push notifications works for both(simulator and real device)

Thanks
---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
- **Are you using `Expo`?**
  - `Y` & `SDK VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by dackers86** [comment]
Hi @franj0.

We are currently updating our documentation explaining how to use these functions correctly. Please see https://github.com/invertase/react-native-firebase/pull/3873

Additionally, this PR came from https://github.com/invertase/react-native-firebase/issues/3817.

Closing as any other information can be discussed in the above PRs. Thanks

**Comment by franj0** [comment]
I did exact everything by documentation. Still not working.

So android simulator and real device is working, ios simulator working, but ios real device receive only push notifications, while messages listener not triggered
