### ISSUE TITLE
Docs inconsistency about the location of apply plugin: 'com.google.gms.google-services'

### ISSUE THREAD

**Issue by andersonaddo** [invertase/react-native-firebase#3875]
I was just integrating the new Crashlytics SDK (#3580) into my project, and I ran into this little docs inconsistency.

When setting up the `/app` module, [the docs state](https://rnfirebase.io/#configure-firebase-with-android-credentials) that `apply plugin: 'com.google.gms.google-services'` should be placed at the very bottom of the `/android/app/build.gradle` file.

However, [in the new setup docs for Crashlytics](https://rnfirebase.io/crashlytics/android-setup#3-apply-the-firebase-crashlytics-plugin-to-your-app), that command is actually placed at the top instead. Clearly, order does matter, since `apply plugin: 'com.google.gms.google-services'` is always placed after `apply plugin: 'com.android.application'`, and `apply plugin: 'com.google.firebase.crashlytics'` is meant to be placed after `apply plugin: 'com.google.gms.google-services'` (wherever that may be).

 So what there a reason the docs seemed so insistent that it should be at the bottom? I didn't get any build errors when I moved it to the top

**Comment by andersonaddo** [comment]
I've looked at StackOverflow and it looks like the firebase docs used to specify that they should be at the bottom. [Example 1](https://stackoverflow.com/questions/39892622/plugin-with-id-com-google-gms-google-services-not-found), [Example 2](https://stackoverflow.com/questions/54347518/is-it-important-that-line-apply-plugin-com-google-gms-google-services-sho).

[They don't anymore](https://firebase.google.com/docs/android/setup#add-config-file), though, so I guess maybe our docs are outdated.

**Comment by mikehardy** [comment]
I may be wrong about the root cause but I think if you don't get this correct, you'll see this with current versions of react-native-firebase that are checking for google API availability:

```
/home/mike/work/Kullki/ksocialscore/packages/public-app/node_modules/@react-native-firebase/app/android/src/reactnative/java/io/invertase/firebase/utils/ReactNativeFirebaseUtilsModule.java:29: error: cannot find symbol
import com.google.android.gms.common.GoogleApiAvailability;
                                    ^
  symbol:   class GoogleApiAvailability
  location: package com.google.android.gms.common
/home/mike/work/Kullki/ksocialscore/packages/public-app/node_modules/@react-native-firebase/app/android/src/reactnative/java/io/invertase/firebase/utils/ReactNativeFirebaseUtilsModule.java:80: error: cannot find symbol
    GoogleApiAvailability gapi = GoogleApiAvailability.getInstance();
    ^
  symbol:   class GoogleApiAvailability
  location: class ReactNativeFirebaseUtilsModule
/home/mike/work/Kullki/ksocialscore/packages/public-app/node_modules/@react-native-firebase/app/android/src/reactnative/java/io/invertase/firebase/utils/ReactNativeFirebaseUtilsModule.java:80: error: cannot find symbol
    GoogleApiAvailability gapi = GoogleApiAvailability.getInstance();

```

I got those android compile errors at any rate, remembered this issue and moved the plugin up, then it seemed to work - I may only be describing a tangential problem but the correlation is strong :man_shrugging:
