### ISSUE TITLE
🔥 Crashlytics crash function seem to be broken in v8

### ISSUE THREAD

**Issue by MohamadKh75** [invertase/react-native-firebase#3877]
## Issue

There is a `crash` function in crashlytics which can be used to simulate a native crash but after upgrading to v8, when I use `crashlytics().crash()`, app freeze and I don't see any force stop message (which was the behavior of previous versions)

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: Windows 8.1 6.3.9600
    CPU: (8) x64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
    Memory: 9.59 GB / 15.91 GB
  Binaries:
    Node: 10.20.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `8.0.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `crashlytics`
- **Are you using `TypeScript`?**
  - `No`
- **Are you using `Expo`?**
  - `No`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by andersonaddo** [comment]
This also happens to me *sometimes*, but I've only used the `crash()` function dev builds.
If it *never* works for you, then there also might be something else at play.

**Comment by mikehardy** [comment]
I have personally never seen this. Test crash works for me android and iOS. I specifically tested this after the PR to firebase crashlytics landed
