### ISSUE TITLE
Notification not showing in first try  

### ISSUE THREAD

**Issue by girish54321** [invertase/react-native-firebase#3884]
## Issue

This notification received in console i can see the log but notification not showing in notification tray (android)
   `messaging().setBackgroundMessageHandler(async (remoteMessage) => {
  console.log("CODE 6 UPDA", remoteMessage, "setBackgroundMessageHandler");
  console.log("LOACE NOTIFICATION");`

Describe your issue here
The notification works but when we send notification for first time then notification not showing in notification tray
---

## Project Files

 NA

`

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
        googlePlayServicesAuthVersion = "16.0.1"
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
                url 'https://maven.fabric.io/public'
              }
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'io.fabric.tools:gradle:1.28.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
`

`apply plugin: "com.android.application"
apply plugin: 'com.android.application' // apply after this line
apply plugin: 'io.fabric'

crashlytics {
  enableNdk true
}

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.mypackage"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 6
        versionName "2.4.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {
    implementation project(':react-native-otp-verify')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-music-control')
    implementation project(':@react-native-community_google-signin')
    implementation project(':react-native-youtube')
    implementation project(":react-native-google-signin")
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
    //GIT SUPPOERT
  // For animated GIF support
    implementation 'com.facebook.fresco:animated-gif:2.0.0'

    // For WebP support, including animated WebP
    implementation 'com.facebook.fresco:animated-webp:2.1.0'
    implementation 'com.facebook.fresco:webpsupport:2.0.0'
    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply plugin: 'com.google.gms.google-services'`

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ x] my application is an AndroidX application?
- [ x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 924.21 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: ~0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native: 0.61.5
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y` & `VERSION` 
- **Are you using `Expo`?**
  - `No` 

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Use firebase-admin to send messages from the command line to reproduce the behavior, and please post the exact JSON that you use (minus your server key of course)

Also, can you fix the formatting by editing the issue ? The triple-backticks that do all the formatting in the markdown were lost somewhere as you entered info. The things are just in the wrong place I think. And I don't see a package.json in there?

**Comment by girish54321** [comment]
Hi @mikehardy thanks for the response  
This is my notification payload form backend 
`  let notifyMsg = {
            notification: {
              title: `New article available`,
              body: title,
            },
            condition,
            data: {
              new_article: "yes",
              article_id: articleID,
              affiliate_status_change: "no",
              new_mentorship: "no",
              mentorship_register_status: "no"
            },
            android: { priority: "high" }
          };`


and my package.JOSN
{
  "name": "MyProject",
  "description": "MyProject",
  "version": "2.4.0",
  "private": true,
  "license": "MIT",
  "author": "myname <myname@gmail.com>",
  "main": "./index.js",
  "workspaces": {
    "nohoist": [
      "*",
      "*/**"
    ]
  },
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "npm run env -- prod && react-native start",
    "start:dev": "npm run env -- dev && react-native start --reset-cache",
    "env": "node ./env/set-env.js",
    "build": "tsc -p ./tsconfig.json",
    "build:web": "expo build:web",
    "clean": "rimraf ./dist ./web-build",
    "lint": "tslint -c ./tslint.json ./src/**/*.{ts,tsx}",
    "changelog": "conventional-changelog -i ./CHANGELOG.md -s",
    "postinstall": "jetify",
    "ios11": "react-native run-ios --simulator=\"iPhone 11\"",
    "ios8": "react-native run-ios --simulator=\"iPhone 8\"",
    "release:android": "cd android && ./gradlew assembleRelease",
    "clean:android": "cd android && ./gradlew clean",
    "clean:build:android": "rm -rf android/app/build",
    "test:apk": "react-native run-android --variant=release",
    "prod:android": "npm run clean:build:android  && react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res",
    "build:assets": "fc-build-assets --fc-template ./assets/fusioncharts-tpl.html"
  },
  "dependencies": {
    "@eva-design/eva": "^1.4.0",
    "@eva-design/material": "^1.4.0",
    "@highcharts/highcharts-react-native": "^2.2.1",
    "@react-native-community/async-storage": "github:react-native-community/async-storage",
    "@react-native-community/checkbox": "^0.3.0",
    "@react-native-community/google-signin": "^4.0.0",
    "@react-native-community/masked-view": "^0.1.5",
    "@react-native-community/netinfo": "^5.8.0",
    "@react-native-firebase/app": "^6.4.0",
    "@react-native-firebase/auth": "^6.4.0",
    "@react-native-firebase/crashlytics": "^6.4.0",
    "@react-native-firebase/dynamic-links": "^6.4.0",
    "@react-native-firebase/messaging": "^6.4.0",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/drawer": "^5.0.0",
    "@react-navigation/material-top-tabs": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@types/react-native-snap-carousel": "^3.8.1",
    "@ui-kitten/components": "^4.4.0",
    "@ui-kitten/date-fns": "^4.4.0",
    "@ui-kitten/eva-icons": "^4.4.0",
    "@ui-kitten/moment": "^4.4.0",
    "accordion-collapse-react-native": "^0.2.8",
    "apollo-boost": "^0.4.4",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.13",
    "apollo-link-context": "^1.0.19",
    "apollo-link-error": "^1.1.12",
    "apollo-link-http": "^1.5.16",
    "apollo-upload-client": "^11.0.0",
    "crypto-js": "3.3.0",
    "date-fns": "^1.30.1",
    "expo": "^36.0.2",
    "expo-constants": "^8.0.0",
    "expo-web-browser": "~8.0.0",
    "fusioncharts": "^3.15.1-sr.1",
    "graphql": "^14.5.8",
    "graphql-tag": "^2.10.1",
    "install": "^0.13.0",
    "moment": "^2.24.0",
    "npm": "^6.14.5",
    "react": "~16.9.0",
    "react-adopt": "^0.6.0",
    "react-apollo": "^3.1.1",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.5",
    "react-native-appearance": "~0.3.1",
    "react-native-async-image-animated": "^4.3.0",
    "react-native-autoheight-webview": "^1.5.1",
    "react-native-banner-carousel": "^1.0.3",
    "react-native-chip-view": "0.0.12",
    "react-native-color-matrix-image-filters": "^5.2.4",
    "react-native-countdown-component": "^2.7.1",
    "react-native-device-info": "^5.5.4",
    "react-native-dialog": "^5.6.0",
    "react-native-dots-pagination": "^0.1.9",
    "react-native-dynamic-tab-view": "^1.0.7-0",
    "react-native-fbsdk": "^1.1.2",
    "react-native-fusioncharts": "^4.1.2",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-highcharts-wrapper": "^0.1.1",
    "react-native-htmlview": "^0.15.0",
    "react-native-hyperlink": "0.0.19",
    "react-native-icon-badge": "^1.1.3",
    "react-native-image-crop-picker": "^0.28.0",
    "react-native-image-placeholder": "^1.0.14",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-looped-carousel": "^0.1.13",
    "react-native-media-controls": "^1.1.1",
    "react-native-modal": "^11.5.6",
    "react-native-music-control": "^0.11.0",
    "react-native-notifications": "^3.1.4",
    "react-native-otp-textinput": "0.0.6",
    "react-native-otp-verify": "^1.0.3",
    "react-native-pages": "^0.9.0",
    "react-native-phone-input": "^0.2.4",
    "react-native-ratings": "^7.2.0",
    "react-native-raw-bottom-sheet": "^2.0.5",
    "react-native-razorpay": "^2.1.33",
    "react-native-reanimated": "~1.4.0",
    "react-native-reanimated-slider": "^1.0.5",
    "react-native-responsive-fontsize": "^0.4.3",
    "react-native-safari-view": "^2.1.0",
    "react-native-safe-area-context": "0.6.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-segmented-control-tab": "^3.4.1",
    "react-native-share": "^3.3.3",
    "react-native-smart-tip": "2.1.0",
    "react-native-sms-retriever": "^1.1.1",
    "react-native-snap-carousel": "^3.8.4",
    "react-native-social-buttons": "^1.1.3",
    "react-native-svg": "9.13.3",
    "react-native-swift": "^1.2.3",
    "react-native-swipeable-flat-list": "^0.1.2",
    "react-native-switch-selector": "^2.0.4",
    "react-native-tab-view": "^2.13.0",
    "react-native-track-player": "^1.2.3",
    "react-native-view-more-text": "^2.1.0",
    "react-native-viewpager": "github:zhaoqigang/react-native-viewpager#931541929e4c24e78a66372d838577fbd09383e6",
    "react-native-viewpager-carousel": "^0.3.2",
    "react-native-web": "^0.11.7",
    "react-native-webview": "^9.4.0",
    "react-native-youtube": "^2.0.0",
    "sha1": "^1.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.3",
    "@babel/runtime": "^7.8.3",
    "@expo/webpack-config": "^0.10.11",
    "@types/react-native": "ts3.7",
    "babel-plugin-module-resolver": "^4.0.0",
    "babel-preset-expo": "^8.0.0",
    "conventional-changelog-cli": "^2.0.21",
    "expo-cli": "^3.11.9",
    "husky": "^1.1.2",
    "jetifier": "^1.6.5",
    "rimraf": "^2.6.2",
    "tslint": "^6.0.0",
    "typescript": "^3.7.5"
  },
  "isSwift": true
}

**Comment by mikehardy** [comment]
The first thing I would do is upgrade to current react-native-firebase:

```

"@react-native-firebase/app": "^6.4.0",
"@react-native-firebase/auth": "^6.4.0",
"@react-native-firebase/crashlytics": "^6.4.0",
"@react-native-firebase/dynamic-links": "^6.4.0",
"@react-native-firebase/messaging": "^6.4.0",
```

Those are old, and it's hard to say what has been fixed in the meantime. You can also upgrade the SDKs to firebase-android-sdk BOM 25.5.0 to make sure you have the most current underlying code https://rnfirebase.io/#android

That fixes problems some times but not all the time, so if you can still reproduce then make sure you are creating notification channels, and watch `adb logcat` unfiltered, to see if the system is blocking it for some reason

**Comment by girish54321** [comment]
Oh updating package this thing scares me will do this is last septs 

this is my console.log()
`messaging().setBackgroundMessageHandler(async (remoteMessage) => {
  console.log("remoteMessage", remoteMessage, "setBackgroundMessageHandler");
});`

and output 
![Screenshot 2020-07-06 at 11 25 35 AM](https://user-images.githubusercontent.com/47414322/86560218-6d11ff00-bf7b-11ea-959b-bc77fba64541.png)

and in mobile phone notification shows up for only 0.5 sec tested with both firebase console and firebase-admin 

![20200706_112934](https://user-images.githubusercontent.com/47414322/86560573-3d172b80-bf7c-11ea-9063-b59694cd29c6.jpg)
 

and if this is because of notification channels can you plz share resource about creating notification channels.

**Comment by girish54321** [comment]
or some one can tell me how to just keep react-native-firebase notification off so i can only use local notification :-|

**Comment by girish54321** [comment]
No sure why this happing so i went with data only notification and added 3rd party notification like `react-native-push-notification`
so it works fine now.
