### ISSUE TITLE
Firebase Analytics Param : Items not sent

### ISSUE THREAD

**Issue by iancorales** [invertase/react-native-firebase#3886]
**Problem:** 
I can't receive the param called 'items' in the firebase console.

**Project Files**
_React Native : 0.61.5_

package.json :
"@react-native-firebase/analytics": "^7.1.7",
"@react-native-firebase/app": "^8.0.0",
"@react-native-firebase/messaging": "^7.2.1",
"@types/react": "^16.9.19",

**Code:**
var item = {
    item_category: 'test_category_name',
    item_id: 'test_id' ,
    item_name: 'test_name',
    price: 123,
    currency : 'PHP',
    quantity : 1
}
analytics().logEvent('view_item_list',{
          item_list_id : model.item_list_id,
          item_list_name : model.item_list_name,
          items : [item],
          section_name : model.section_name
})

The result of this code in Debug View of Firebase Analytics is : 
<img width="366" alt="Screen Shot 2020-07-06 at 2 50 38 PM" src="https://user-images.githubusercontent.com/34309152/86564038-0fd87680-bf98-11ea-9d87-02a1dcbee3cf.png">

**Comment by Aprenx** [comment]
@iancorales I think the items param only can be access by google big query, when we use the param items we only can see the param ga_extra_params_ct where show the number of indexes on array sented.

Another way to see the value of items is implements the google tag manager and sent the events to Google Analytics Standard. This is the events to can sent to the GA: 
https://developers.google.com/tag-manager/android/v5/enhanced-ecommerce?hl=pt-br
I do this with this tutorial: https://adswerve.com/blog/react-native-firebase-gtm-integration-installation/

**Comment by mikehardy** [comment]
Upstream issue, no action possible, details: https://github.com/invertase/react-native-firebase/issues/4018#issuecomment-682174087
