### ISSUE TITLE
Firebase Realtime Datebase Offline Mode Documentation

### ISSUE THREAD

**Issue by danmelton** [invertase/react-native-firebase#3889]
## Documentation Feedback

https://github.com/invertase/react-native-firebase/blob/master/docs/database/offline-support.md

The offline support documentation states 'Persistence is automatically enabled by default when using Realtime Database.' However, the default values in both the IOS and Android files are set to 'false.'

IOS method to setPersistenceEnabled on setup
https://github.com/invertase/react-native-firebase/blob/ca34cef160cd0e632bec6d60e10b45c8efd568c8/packages/database/ios/RNFBDatabase/RNFBDatabaseCommon.m#L78

Android method to setPersistenceEnabled on setup
https://github.com/invertase/react-native-firebase/blob/554c4b403520f537c10426ce377e32dd87d41469/packages/database/android/src/main/java/io/invertase/firebase/database/UniversalFirebaseDatabaseCommon.java#L59

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by andersonaddo** [comment]
Interesting. 
I think it'd be better to change the docs than change the package's behaviour. 
The actual SDKs have this disabled by default for Realtime Database.
