### ISSUE TITLE
Is there a way to catch specific errors?

### ISSUE THREAD

**Issue by himat** [invertase/react-native-firebase#3891]
Is there a way to catch specific errors like `auth/invalid-verification-code` in a `try... catch`?

I want to do something like
```
firebaseConfirmResult
    .confirm(code)
    .then(async (res: any) => {
        console.log("Successfully verified phone number with code!");
    })
    .catch((err as invalidVerificationCode) => { // * how do I do this?
        // something
   })
  .catch((err as anotherException) => { ... })
```

Can I somehow import the exceptions from this library into my code to catch them?
Or is the only way to pattern match the strings in the error code message?

**Comment by mikehardy** [comment]
They are not strongly typed but I do a switch on the `.code` inside the catch - it works well
You can just console.log(JSON.stringify(err)) to make sure you know exactly what the shape of the object is then switch on the right component. The SDKs upstream have the list of possible errors for each API

I'll reopen if you need but hopefully that's enough to get you going?
