### ISSUE TITLE
HELP !!! error: cannot find symbol import com.google.android.gms.common.GoogleApiAvailability;

### ISSUE THREAD

**Issue by NaufalAmmar** [invertase/react-native-firebase#3904]
![image](https://user-images.githubusercontent.com/34411256/86863064-a6ba4580-c0f4-11ea-8b0c-03af2cb0825c.png)

I didn't change anything, and this happened after I uninstalling the debug APK from the device then run again that error showed

please, help me.

I'm using :
"@react-native-firebase/app": "^8.1.0",
"@react-native-firebase/auth": "^8.1.1",
"@react-native-firebase/database": "^7.3.1",
"@react-native-firebase/storage": "^7.2.1",

**Comment by mikehardy** [comment]
Without following the template, we can't help. You  might try generating a sample project and comparing it with your local environment, somewhere in your integration of the module into your project, you have an error I think https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

**Comment by NaufalAmmar** [comment]
Hello, @mikehardy I have following your demo, but My Problem error **cannot find symbol import com.google.android.gms.common.GoogleApiAvailability; ** still show up. what I must to do ?? it was running fine before. 
I don't know what make that error happen suddenly.
I was try to create new project with package firebase/app installed and same error show.

**Comment by mikehardy** [comment]
Released version with fixes

```
 - @react-native-firebase/admob@7.6.1
 - @react-native-firebase/analytics@7.5.1
 - @react-native-firebase/auth@9.1.1
 - @react-native-firebase/crashlytics@8.4.1
 - @react-native-firebase/database@7.5.1
 - @react-native-firebase/dynamic-links@7.5.1
 - @react-native-firebase/firestore@7.6.1
 - @react-native-firebase/functions@7.4.1
 - @react-native-firebase/iid@7.4.1
 - @react-native-firebase/in-app-messaging@7.4.1
 - @react-native-firebase/messaging@7.8.1
 - @react-native-firebase/ml-natural-language@7.4.1
 - @react-native-firebase/ml-vision@7.4.1
 - @react-native-firebase/perf@7.4.1
 - @react-native-firebase/remote-config@8.2.1
 - @react-native-firebase/storage@7.4.1
 - react-native-firebase-tests@8.4.1
```
