### ISSUE TITLE
removeDeliveredNotification(id) not working on Android

### ISSUE THREAD

**Issue by hanzoow** [invertase/react-native-firebase#3906]
## Issue

Describe your issue here

Hi! i'm using  "react-native-firebase": "^5.6.0" and i'm trying to remove notifications in status bar by id, but seems like i could not do that. Trust me that i get exact id of notifications which available in status bar. I checked another issues like me but no helps :( i also use   .android.setAutoCancel(true) but it doesn't help.

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x ] my application is an AndroidX application?
- [x ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

 implementation project(':react-native-firebase')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation "com.facebook.react:react-native:+"  // From node_modules

    // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation "com.google.firebase:firebase-core:16.0.9"
    implementation "com.google.firebase:firebase-messaging:18.0.0"
    implementation 'me.leolin:ShortcutBadger:1.1.21@aar'
    implementation "com.google.firebase:firebase-database:17.0.0"
    implementation "com.google.firebase:firebase-auth:17.0.0"
#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```
System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
    Memory: 2.38 GB / 7.88 GB
  Binaries:
    Node: 13.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-fast-image: 7.0.2
    react-native-git-upgrade: 0.2.7

- **Platform that you're experiencing the issue on**:
  - [x ] Android
  - [x ] **Android** but have not tested behavior on iOS
- **`react-native-firebase` version you're using that has this issue:**
  - ^5.6.0
- **`Firebase` module(s) you're using that has the issue:**
  - removeDeliveredNotification(notificationId)
- **Are you using `TypeScript`?**
  - No
- **Are you using `Expo`?**
  - No

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
v5 is no longer supported and notifications in particular are not as they don't exist in v6, I'm going to close this but feel free to continue discussion if you like
I would upgrade and integrate a local notifications package, as described in documentation and related issues all over
