### ISSUE TITLE
Crashlytics documentation for setUserName and setUserEmail is possibly outdated

### ISSUE THREAD

**Issue by emeraldsanto** [invertase/react-native-firebase#3908]
## Documentation Feedback

I was using a previous version of the Crashlytics module which provided methods such as `setUserName` and `setUserEmail`. After updating to the latest version `8.1.1` which migrated away from Fabric, these 2 methods no longer exist. I already worked around the problem by setting those fields using the `setAttributes` method.

I wonder if that's simply a [documentation](https://rnfirebase.io/crashlytics/usage#crash-attributes) issue or a regression that was introduced in the latest version.

Cheers!

**Comment by mikehardy** [comment]
Needs a doc update that didn't ship as part of the PR, commented here https://github.com/invertase/react-native-firebase/pull/3580#pullrequestreview-405087960

If you have a moment can you hit the edit button on top right of the page and post up a PR for the changes pleeeeease :-) 🙏

**Comment by andersonaddo** [comment]
It's a documentation issue actually - those two methods were purposefully removed. 

You can use the edit button at the top of the docs page to submit a super quick PR 😁

**Comment by emeraldsanto** [comment]
Coolio, thanks for letting me know. I've opened #3909.

**Comment by andersonaddo** [comment]
Wow @mikehardy I just realized we added those comments at pretty much the exact same time, haha!
