### ISSUE TITLE
Missing call removeDeliveredNotificationsByTag() function in index.js.flow, index.js and index.d.ts files.

### ISSUE THREAD

**Issue by hanzoow** [invertase/react-native-firebase#3914]
## Issue

Describe your issue here

Seems like you forgot to call removeDeliveredNotificationsByTag() function in 3 files index.js.flow, index.js and index.d.ts so in my code i can't call that function to remove notifications by tags. Please check image to more info.
This image is about call remove notification functions in my code.

![image](https://user-images.githubusercontent.com/44063254/87019120-6d6cfd00-c1fc-11ea-907a-cc7c5a73e0e7.png)

This image is about your missing functions in mode_modules

![image](https://user-images.githubusercontent.com/44063254/87019372-b91fa680-c1fc-11ea-9651-97c7b67739e4.png)
![image](https://user-images.githubusercontent.com/44063254/87019397-c177e180-c1fc-11ea-84ea-07f4285ad70e.png)
![image](https://user-images.githubusercontent.com/44063254/87019471-da809280-c1fc-11ea-8b4f-564a018b9f3b.png)
![image](https://user-images.githubusercontent.com/44063254/87019502-e66c5480-c1fc-11ea-92c4-38843a22a4da.png)

PLEASE HELP THE DEADLINE IS THERE ! PLZ HELP

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.6.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
- **Are you using `Expo`?**
  - `Y` & `SDK VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Please don't post images. Post code in markdown format, which is triple-backticks and a language specifier like

```typescript
  let code = 'well formatted stuff'; // much easier to read, works on mobile while images don't
```

If you discover errors in the code, a liberal use of "grep" will help you find the symbols, or just opening the root of the monorepo in visual studio code will let you find things

Post a PR with your idea on the problem and the correction and we can review

**Comment by hanzoow** [comment]
close this. like @mikehardy recommend, use 
https://github.com/ds300/patch-package to make change from node_modules. It works to me ! Thank you so much @mikehardy

**Comment by mikehardy** [comment]
Glad that worked, and yes - in my opinion patch-package is just fantastic and is so useful when working in react-native. I always have a couple patches in my source tree (I usually make PRs upstream so what I have patched locally is always changing, but there's always something). With patch-package you're never really stuck, but you don't have to maintain tracking forks for small things
