### ISSUE TITLE
Hii Guys i want to know how i can off the rn firebase notification and use my local notification only 

### ISSUE THREAD

**Issue by girish54321** [invertase/react-native-firebase#3916]
For feature requests please visit our [Feature Request Board](https://invertase.io/oss/react-native-firebase/feedback/).

Hii Guys i want to know how i can off the rn firebase notification and use my local notification only

**Comment by andersonaddo** [comment]
Yeah you can. Use data-only FCM messages and handle them using your own logic, which can include local notifications. 

Lots of issues here explaining it in more detail. 

Also: https://rnfirebase.io/messaging/usage

**Comment by girish54321** [comment]
@andersonaddo Thanks..
