### ISSUE TITLE
onDisconnect this.database is undefined

### ISSUE THREAD

**Issue by brandonkwong** [invertase/react-native-firebase#392]
### Issue

I am working with `react-native-firebase@3.0.0.alpha-2`, and when using `someRef.onDisconnect().remove()`, I caught the below error:
```
TypeError: Cannot read property '_native' of undefined
```
I think the following may need to be added:

"lib/modules/database/reference.js#L406"
```
onDisconnect() {
  return new Disconnect(this, this.path);
}
```

"lib/modules/database/disconnect.js#L19"
```
constructor(ref: Reference, path: string) {
  this.database = ref._database;
  this.path = path;
}
```

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode 8.3.3

4. React Native version: 0.47.2

5. RNFirebase Version: 3.0.0.alpha-2

6. Firebase Module: database

**Comment by Salakar** [comment]
@brandonkwong thanks for flagging the issue. Have fixed it and published a new version with the `next` tag, if you could try it out that'd be great.

**Comment by brandonkwong** [comment]
@Salakar Thanks! This is working now in `3.0.0-alpha.3`.
