### ISSUE TITLE
Getting started link is broken

### ISSUE THREAD

**Issue by boraoren** [invertase/react-native-firebase#3921]
## Documentation Feedback

Getting started link is broken in https://github.com/invertase/react-native-firebase/blob/master/docs/app/usage.md

![image](https://user-images.githubusercontent.com/45959515/87099069-2e868800-c28c-11ea-8e9d-4bc36e1ebd3b.png)

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by andersonaddo** [comment]
All the links in the md files for the docs are pretty much like that.
They do work when they're reconstructed for the site itself though.
[Try it for yourself](https://rnfirebase.io/app/usage)
