### ISSUE TITLE
[Admob Android] Still request too much but too less impression at version 7.3.2

### ISSUE THREAD

**Issue by michuotvn** [invertase/react-native-firebase#3929]
**Issue**
I try implement firebase admob with this library (version 7.3.2). And then when look to admob dashboard, i release that android app request ads too much but only have a few impression. the show rate only ~20%.

<img width="1542" alt="Screen Shot 2020-07-13 at 07 45 38" src="https://user-images.githubusercontent.com/6366999/87260583-dabead80-c4dc-11ea-9894-19718776bad1.png">

i know this is a old issues and already have a merged request to fix this at [#3488 ](url) but maybe it's still not work because i'm using the latest version (7.3.2).
Can someone help me this issues, it's important because i will got banned from admob if the app keep continue request ads too much.

Thanks,

**Comment by mikehardy** [comment]
I think we'll need to see a reproduction app that shows the behavior.
I understand admob is tied to google accounts even more than firebase but if you could post a reproduction that uses the test AdMob account and just doesn't include your firebase account json/plist that could work

Also, you skipped the template entirely so for me at least I'll ignore this.

**Comment by mikehardy** [comment]
here's something to build a repro off though at least https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh
