### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Moshikol** [invertase/react-native-firebase#393]
I'm new to react-native with FireBase and I got  several errors on the build  that make it failed 
the errors are in the PS
I'm trying to compile for Android and this is the   ##output:
Thanks in advance :)
![image](https://user-images.githubusercontent.com/19548879/30158138-e0310626-93cc-11e7-85e0-82c1f71fb8d5.png)

**Comment by Salakar** [comment]
See https://github.com/invertase/react-native-firebase/issues/381

Also please fill out the issue template for future issues, we normally just close issues that don't follow the template otherwise. Thanks.
