### ISSUE TITLE
Build fail after upgrading to 8.x for crashyltics and app 

### ISSUE THREAD

**Issue by panda0603** [invertase/react-native-firebase#3930]
## Issue

Describe your issue here

After upgrading to version 8.2.0 from 7.2.1 for @react-native-firebase/app and 8.1.2 from 7.1.5 for @react-native-firebase/crashlytics, 

I am getting following build error: 

```
line 2: [project root]/ios/Pods/Fabric/run: No such file or directory
```

I do understand it is a breaking change to upgrade to 8.x from 7.x since fabric was removed, 
but I have no idea how to solve the build error.

I have already tried cleaning the build folder, removing npm cache, but no luck. 

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Browser' do
  # Pods for Browser
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'BrowserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'Browser-tvOS' do
  # Pods for Browser-tvOS

  target 'Browser-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```
```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  "@react-native-firebase/analytics": "^7.3.1",
    "@react-native-firebase/app": "^8.2.0",
    "@react-native-firebase/crashlytics": "^8.1.2"
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y` & `VERSION`
- **Are you using `Expo`?**
  - `N` & `SDK VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by andersonaddo** [comment]
So v8 changed to using a completely different SDK, so the installation steps have changed:
https://rnfirebase.io/crashlytics/usage
You might just have to delete your pods.lock file, redo the installation steps (that also includes removing references to fabric), then rerun `pod install`

**Comment by panda0603** [comment]
@andersonaddo thanks for reply. Just tried deleting the podfile.lock and re-do pod install, but same error. For installation steps, iOS installation didn't seem to be changed from 7.x.

**Comment by andersonaddo** [comment]
Check the Build Phases
The old isntallation steps had you add a build phase that referenced to fabric

**Comment by panda0603** [comment]
is there any way to reference the old docs? At the moment I can only seem to refer the newest version of the documentation

**Comment by andersonaddo** [comment]
Here's a reference to the old docs:
https://github.com/invertase/react-native-firebase/blob/7f52366e220411b368bd285192492c36572c7ecb/docs/crashlytics/ios-setup.md
(I got it by going through the git history)

**Comment by panda0603** [comment]
Thanks!! managed to get it working by removing the reference. Have a good day
