### ISSUE TITLE
firebase.notifications.Android.Channel alternative in new(6.*) version

### ISSUE THREAD

**Issue by imansalhi** [invertase/react-native-firebase#3933]
## Documentation Feedback
Actually i have a module uses react-native-firebase 5(Legacy version) and i want to replace it with the new version of react-native-firebase (version 6.*) therefore i should replace all functionalities with the new version functions. 
as a matter of fact i need to know below's function  alternative in new version but i could not find it in documents 

     
`const channel = new firebase.notifications.Android.Channel('voximplant_channel_id', 'Incoming call channel', firebase.notifications.Android.Importance.Max)
                .setDescription('Incoming call received');
            firebase.notifications().android.createChannel(channel);`

can any one help me to either find above code alternative in RN v6 or tell me how to do it in practice ? 

---
i'v checked out [this](https://rnfirebase.io/messaging/notifications) but find nothing :(

**Comment by andersonaddo** [comment]
As inferred [here](https://rnfirebase.io/messaging/notifications#notifee---advanced-notifications), advanced notification features are no longer part of this package. You're going have to use data-only FCM messages and handle them using a third party notification package, like Notifee or react-native-push-notifications

**Comment by andersonaddo** [comment]
This may also be a bit informative: https://rnfirebase.io/messaging/usage#notification-channel-id
