### ISSUE TITLE
🔥  Messaging unsubscribeFromTopic/subscribeToTopic throw ambiguous com.google.fcm error 501/0 codes

### ISSUE THREAD

**Issue by alexwasner** [invertase/react-native-firebase#3935]
## Issue

Looking at my logs in Sentry, I have some users who are receiving `code 0` when unsubscribing from a topic and `code 501` when trying to subscribe.

My code:
```
try {
    if (typeof topic !== 'string' || !topic.trim().length) {
      throw 'A valid string is required for the provided topic';
    }
    await messaging().subscribeToTopic(topic);
    Logging.log(
      'PUSH_NOTIFICATIONS',
      `Subscribed to notifications for ${topic}`,
    );
} catch (error) {
//this is where I get the log of the 501/0
    Sentry.captureException(error);
}
```

Describe your issue here

Errors in the logs:
  - `[messaging/unknown] The operation couldn’t be completed. (com.google.fcm error 501.)` when calling `messaging().subscribeToTopic(topic)`
  - `[messaging/unknown] The operation couldn’t be completed. (com.google.fcm error 0.)` when calling `messaging().unsubscribeFromTopic(topic)`

Some users are potentially not receiving push notifications due to errors in subscribing/unsubscribing from a topic. I found a [couple](https://github.com/firebase/firebase-ios-sdk/issues/2438) potentially related [issues](https://github.com/firebase/firebase-ios-sdk/issues/2625) but the fixes look to be resolved in the version of Pods we are using.

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'AppNameHere' do
  config = use_native_modules!
  use_react_native!

  pod 'GoogleTagManager', '~> 7.1'

  pod 'Permission-PhotoLibrary', :path => "../node_modules/react-native-permissions/ios/PhotoLibrary.podspec"

  use_flipper!

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
    if target.name == 'AppNameHere'
      use_flipper!
    end
  end
end
```

#### `AppDelegate.m`:

```objc
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#if DEBUG
#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitLayoutPlugin/SKDescriptorMapper.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#endif
#endif

@import Firebase;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  #if DEBUG
    [self initializeFlipper:application];
  #endif
  
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"AppNameHere"
                                            initialProperties:nil];

  rootView.backgroundColor = [UIColor colorNamed:@"SplashColor"];


  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [FIROptions defaultOptions].deepLinkURLScheme = @"firebasedynamiclinks";
  [FIRApp configure];
  return YES;
}


- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}


- (void) initializeFlipper:(UIApplication *)application {
  #if DEBUG
  #ifdef FB_SONARKIT_ENABLED
    FlipperClient *client = [FlipperClient sharedClient];
    SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
    [client addPlugin: [[FlipperKitLayoutPlugin alloc] initWithRootNode: application withDescriptorMapper: layoutDescriptorMapper]];
    [client addPlugin: [[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
    [client addPlugin: [FlipperKitReactPlugin new]];
    [client addPlugin: [[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
    [client start];
  #endif
  #endif
}

@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 297.18 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.0.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.0-rc.1 => 0.63.0-rc.1
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `"@react-native-firebase/analytics": "7.1.6"`
  - `"@react-native-firebase/app": "^7.3.1"`
  - `"@react-native-firebase/crashlytics": "7.1.7"`
  - `"@react-native-firebase/dynamic-links": "7.2.1"`
  - `"@react-native-firebase/iid": "7.1.7"`
  - `"@react-native-firebase/messaging": "7.1.8"`
- **`Firebase` module(s) you're using that has the issue:**
  - `Messaging`
- **Are you using `TypeScript`?**
  - `Y` & `^3.7.4`
- **Are you using `Expo`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Interesting

This comment from one of the main iOS developers seems authoritative:

https://github.com/firebase/quickstart-ios/issues/427#issuecomment-386048638

> If your error is a 501 error, please file a support ticket. It's likely a backend bug. Nothing you do on the client should result in a 501 error.

I am unsure on error code 0, but note that request for `-FIRDebugEnabled` and more complete logs in order to help them when/if you log a bug with firebase-ios-sdk repo

**Comment by alexwasner** [comment]
Thats some good info. I'll report back on this ticket after doing that
