### ISSUE TITLE
Do I need to run pod update after updating library

### ISSUE THREAD

**Issue by amitbravo** [invertase/react-native-firebase#394]
- just updated from 2.1.4 to 2.2.0 
with npm i --save react-native-firebase@latest
Should I need to run cd ios && pod update every time after updating a library ?

**Comment by Salakar** [comment]
No you're fine for most minors and all patch versions, only on major versions would you need to do this, i.e going from v2 to v3 - as we then increase the minimum firebase sdk dependencies.
