### ISSUE TITLE
use listen on class component 

### ISSUE THREAD

**Issue by imansalhi** [invertase/react-native-firebase#3945]
## Documentation Feedback

the new version of RNfirebase documentation is for the service users who use react-hook. it will be nice if react-native-firebase  has both class component and functional component, code samples inside its documents. how ever there isn't any code sample solution for the users who still use class components.. 

now the issue for me is this: 

```
import React, { useEffect } from 'react';
import { Alert } from 'react-native';
import messaging from '@react-native-firebase/messaging';

function App() {
  useEffect(() => {
    const unsubscribe = messaging().onMessage(async remoteMessage => {
      Alert.alert('A new FCM message arrived!', JSON.stringify(remoteMessage));
    });

    return unsubscribe;
  }, []);
} 
```

how to implement this listen function on **class-componen**t. means **without useeffect**  
how set unsubscribe?

is this true to call  unsubscribe  function again in `componenWillUnmount()` ??

**Comment by russellwheatley** [comment]
That is correct. You would put `unsubscribe` on a class instance property and you would call it in `componenWillUnmount()`

**Comment by imansalhi** [comment]
@russellwheatley  you mean this:
```
 const unsubscribe = messaging().onMessage(async remoteMessage => {
      Alert.alert('A new FCM message arrived!', JSON.stringify(remoteMessage));
    });
componentDidMount(){
unsubscribe()
}

componentWillUnmount(){
unsubscribe()
}
```

yes?

**Comment by russellwheatley** [comment]
This would actually unsubscribe immediately in the `componentDidMount`:
```
constructor(){
this.unsubscribe = messaging().onMessage(async remoteMessage => {
      Alert.alert('A new FCM message arrived!', JSON.stringify(remoteMessage));
    });
} 

componentDidMount(){
//this would unsubscribe the listener as soon as the component mounted.
this.unsubscribe()
}

componentWillUnmount(){
this.unsubscribe()
}
```

I would suggest invoking the listener in `componentDidMount` especially if you're going to affect state from the listener callback.
```
componentDidMount(){
this.unsubscribe =  messaging().onMessage(async remoteMessage => {
      Alert.alert('A new FCM message arrived!', JSON.stringify(remoteMessage));
    });
}

componentWillUnmount(){
this.unsubscribe()
}
```

**Comment by mikehardy** [comment]
I do this, it works fine in class components as @russellwheatley suggests
Only responding to say make sure to do the appropriate try/catch and check to make sure the unsubscribe variable is set before trying to invoke it. Always surprising how software fails... but adding the listener on mount and removing it on unmount works

For fancier situations (like navigation that maintains components mounted and offers an extra state of blur / focus) you can also do the listener add in the focus hook and unsubscribe in the blur hook

**Comment by mikehardy** [comment]
I think this is well-answered
