### ISSUE TITLE
write custom code in background job 

### ISSUE THREAD

**Issue by imansalhi** [invertase/react-native-firebase#3946]
is it possible to write custom code in background register function?

```
// Register background handler
messaging().setBackgroundMessageHandler(async remoteMessage => {
    console.log('Message handled in the background!', remoteMessage);
    ///////in this part
  });
```
would these codes run when the app receive notif??

**Comment by Ehesp** [comment]
Yes, however the code cannot impact application state. So doing things such as network requests is fine. You have about 30 seconds to execute any code.
