### ISSUE TITLE
[Question] Firebase Pod 4.1.1 with leveldb-library

### ISSUE THREAD

**Issue by dgruseck** [invertase/react-native-firebase#395]
Hi,

I just try to upgrade the firebase pods to version 4.1.1 and they need the leveldb-library pod.
The problem is when I try to build, the stdint.h from leveldb is used in Yoga.h but it thorws a error: 
`This file should only be included when compiling with MSVC`
Has anybody seen that error before and knows how to fix it?

In version 4.0.3 everything is working because the leveldb-library is not used.

Kind regards,
David

**Comment by Salakar** [comment]
Ye it's an annoying thing at the moment with having leveldb on cocoa pods,

I'd suggest doing what a user on discord did as a work around:
![image](https://user-images.githubusercontent.com/5347038/30165736-031644ec-93d9-11e7-93fb-93a50d1e17c5.png)

Add it as a package script so you can re-use it if needed later:
`cd ios && rm -rf Pods/leveldb-library/port/win`

**Comment by designorant** [comment]
I've just ran into this myself.

This workaround can be added to `Podfile` as follows:
```ruby
# Temporary workaround for https://github.com/invertase/react-native-firebase/issues/395
post_install do
  `rm -rf Pods/leveldb-library/port/win`
end
```

**Comment by wbattel4607** [comment]
Is this still necessary?
