### ISSUE TITLE
[QUESTION] How do I display an image in my notification?

### ISSUE THREAD

**Issue by mrousavy** [invertase/react-native-firebase#3950]
First off: sorry for posting this here. I haven't had any luck getting responses on the discord, and the docs aren't very clear about this either. I might add some info/more docs to the messaging page when I figure this out and create a PR.

### Question

How do I display an image in my notification? I have set up my notification handlers and everything, and send out a notification from my firebase admin sdk. My message looks like this:

```ts
token: token,
notification: {
	imageUrl: imageUrl,
	title: chatTitle,
	body: messagePrefix + message.message,
},
apns: {
	payload: {
		aps: {
			mutableContent: true,
			sound: 'default',
			badge: 1,
			threadId: threadId,
		},
	},
	fcmOptions: {
		imageUrl: sender.profilePictureURL,
	},
}
```

So I send the `imageUrl` with it (in `notification` and in `apns.fcmOptions`, whatever the difference is), but nothing gets displayed in my client. Do I need to create custom native Objective-C notification service extensions for this to work or can I somehow use the background handler from within the JS API?

thanks!

**Comment by mikehardy** [comment]
So, notifications is in general not handled by react-native-firebase
react-native-firebase handles cloud messaging as thoroughly as possible

The underlying SDKs from google allow for cloud messaging to have notification payloads, and they (not react-native-firebase) will react to them by displaying notifications themselves under certain conditions, but react-native-firebase does not do anything with the notification payload

That's probably the reason for no response anywhere. What you want is either to read the docs for the underlying SDKs, or you want to send a data-only payload in your cloud message, respond to it using react-native-firebase cloud messaging listeners and then drive a local device notification package (like react-native-push-notifications, or notifee, or something else) to do exactly what you want

**Comment by mrousavy** [comment]
makes sense. I have played around with an iOS notifications service extension which I got working fairly well. I think I'm going to stick to this, since receiving through JS and then displaying locally again seems like an unnecessary detour.

Thanks!
