### ISSUE TITLE
Error in ios build

### ISSUE THREAD

**Issue by Hamidrezana** [invertase/react-native-firebase#3951]
I want to use cloud messaging of firebase in my react native project. I followed installation in 
 [docs][1] but I got error when running project using `react-native run-ios`:

```
fatal error: 'GoogleUtilities/AppDelegateSwizzler/Private/GULApplication.h' file not found
#import 'GoogleUtilities/AppDelegateSwizzler/Private/GULApplication.h'
```

I run `pod install --repo-update` but not work.

It work on android but on ios not.

```
    "@react-native-firebase/app": "^8.2.0",
    "@react-native-firebase/messaging": "^7.4.2",
```

  [1]: https://rnfirebase.io/#generating-ios-credentials

**Comment by ryanwilson** [comment]
Tracked at https://github.com/firebase/firebase-ios-sdk/issues/6047.

**Comment by andersonaddo** [comment]
#3638
