### ISSUE TITLE
setTimeouts don't work in background message handler

### ISSUE THREAD

**Issue by compojoom** [invertase/react-native-firebase#3955]
## Issue
https://rnfirebase.io/messaging/usage#background--quit-state-messages

We have a server that delivers a data message to our app. The message contains just an id. Our BackgroundMessageHandler receives it and the fun starts. We were trying to run our redux sagas and fetch data from the server, but at one point the sagas were just not progressing. No error message, nothing. We tried to use a setTimeout and noticed that on first send of a message - the handler receives it - executes everything before the setTimeout call and then just stops. If we send a second message, then the first setTimeout call runs, followed by the new setTimeout run from the second message. If I now continue to send messages - it all runs fine.

After re-reading the headless js docs for I don't know how many times I noticed this: https://reactnative.dev/docs/headless-js-android#retries
in caveats they say:
`The function passed to setTimeout does not always behave as expected. Instead the function is called only when the application is launched again. If you only need to wait, use the retry functionality.`

So I went into the following file:
https://github.com/invertase/react-native-firebase/blob/master/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingHeadlessService.java

and added the retry policy from the RN docs. 

Then in our handler I was throwing a `HeadlessJsTaskError`until my setTimeout doesn't execute. 
My handler looks like this:
```
let i = 0;
// Register background handler
messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('i', i)
  setTimeout(() => {
    i = 1
    console.log('set timeout', i)
  }, 3000);

  if(i === 0) {
    console.log('error', i)
    throw new HeadlessJsTaskError();
  }

  console.log('i', i)
  console.log('i reached the end', remoteMessage)
});
```

Throwing a headlessJsTaskError seems the only way to make setTimeout work in the headless js task. I can create a PR with that if you guys are open to it.

**Comment by Salakar** [comment]
Your handler code is resolving immediately and hence the headless task is exiting before the timeout can trigger, you need to wrap it in a promise.

```js
let i = 0;
// Register background handler
messaging().setBackgroundMessageHandler(async remoteMessage => {
  await new Promise(resolve => {
    console.log('i', i);
    setTimeout(() => {
      i = 1;
      console.log('set timeout', i);
      resolve();
    }, 3000);
  });

  console.log('i', i);
  console.log('i reached the end', remoteMessage);
});
```

**Comment by compojoom** [comment]
I was actually testing with this:

```
export function sleep(time) {
  let timeout = null
  const promise = new Promise(resolve => {
    timeout = setTimeout(resolve, time)
  })

  promise.timeout = timeout
  return promise
}
// Register background handler
messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('Message handled in the background!', remoteMessage);
  const apiCall = await fetch(
    "https://postman-echo.com/get?foo1=bar1&foo2=bar2"
  )
  console.log("apiCall .....................", apiCall)
  await sleep(5000)
  const apiCall2 = await fetch(
    "https://postman-echo.com/get?foo1=bar1&foo2=bar2"
  )
  console.log("apiCall22222 .....................", apiCall2)
  
  
  // console.log('Message handled in the background!', remoteMessage);
});
```
and it doesn't work. The second api call doesn't execute.

I also did try you code. I only receive `i 0`. I have a dummy repo with RN 0.63 and rn-firebase do you want access to it?

**Comment by compojoom** [comment]
I'm closing this for now as it seems that the problem is on the javascript side in our app.

**Comment by bkdev98** [comment]
Hi @compojoom, did you find a solution to this issue?

**Comment by Andriiklymiuk** [comment]
Did anyone find the solution for that?

**Comment by Alonew0lfxx** [comment]
I have same issue

**Comment by Alonew0lfxx** [comment]
After 2 hours of search I fixed my problem by using this sleep function instead of `setTimeout()`.
This may not be the best or most optimized solution. However, it was very helpful in resolving my problem 💘

```
static async customSleep(ms) {
        const start = new Date().getTime();
        for (let i = 0; i < 1e7; i++) {
            try {
                await fetch("255.255.255.0");
            } catch (e) {}
            if ((new Date().getTime() - start) > ms) break;
        }
    }

```

**Comment by iDubok** [comment]
I was able to run delayed code, including logging by using native-powered background timer: [react-native-background-timer](https://github.com/ocetnik/react-native-background-timer):
```
BackgroundTimer.setTimeout(() => {
    console.debug('Running with delay from Background Message Handler');
}, 1000);
```

**Comment by marcesengel** [comment]
I've also run into this issue and debugged the root cause in `react-native` ([my original SO answer](https://stackoverflow.com/a/70971514/9204455)):

> I faced the same issue and went into debugging it. The problem is with how the ReactContext is constructed when your app is in the background. The context signals to have been created BEFORE the `TimingModule` is initialized and your task is instantly executed by the `HeadlessJsTaskService` (before the `TimingModule` is initialized).

> However the `TimingModule` adds a listener to the `HeadlessJsTaskContext` in order to only run while there are active background tasks. This listener is attached in `TimingModule.initialize()` - but due to the execution order this listener is attached after your task was already started, meaning it is never invoked and thereby the `TimingModule` is not running.

> This can be fixed by declaring `HeadlessJsTaskContext.addTaskEventListener(...)` as `synchronized` and then invoking the added listeners for every currently active task.
Before:
```java
  public void addTaskEventListener(HeadlessJsTaskEventListener listener) {
    mHeadlessJsTaskEventListeners.add(listener);
  }
```
> After:
```java
  public synchronized void addTaskEventListener(HeadlessJsTaskEventListener listener) {
    mHeadlessJsTaskEventListeners.add(listener);
    for (Integer activeTaskId: mActiveTasks) {
      listener.onHeadlessJsTaskStart(activeTaskId);
    }
  }
```

I'm going to create an issue in `react-native` linking this issue and could share a link to the patched version if there's interest.

**Comment by mikehardy** [comment]
If there is a bug in react-native definitely open an issue! Always interested in react-native fixing bugs...

**Comment by marcesengel** [comment]
@mikehardy done 👍

**Comment by Alexufo** [comment]
@compojoom have you solution?

**Comment by mikehardy** [comment]
I don't believe there is a general solution if the problem is "setTimeout does not work in react-native headlessJS". It's a known issue in react-native

**Comment by Aaronphy** [comment]
> I've also run into this issue and debugged the root cause in `react-native` ([my original SO answer](https://stackoverflow.com/a/70971514/9204455)):
> 
> > I faced the same issue and went into debugging it. The problem is with how the ReactContext is constructed when your app is in the background. The context signals to have been created BEFORE the `TimingModule` is initialized and your task is instantly executed by the `HeadlessJsTaskService` (before the `TimingModule` is initialized).
> > However the `TimingModule` adds a listener to the `HeadlessJsTaskContext` in order to only run while there are active background tasks. This listener is attached in `TimingModule.initialize()` - but due to the execution order this listener is attached after your task was already started, meaning it is never invoked and thereby the `TimingModule` is not running.
> > This can be fixed by declaring `HeadlessJsTaskContext.addTaskEventListener(...)` as `synchronized` and then invoking the added listeners for every currently active task.
> > Before:
> 
> ```java
>   public void addTaskEventListener(HeadlessJsTaskEventListener listener) {
>     mHeadlessJsTaskEventListeners.add(listener);
>   }
> ```
> 
> > After:
> 
> ```java
>   public synchronized void addTaskEventListener(HeadlessJsTaskEventListener listener) {
>     mHeadlessJsTaskEventListeners.add(listener);
>     for (Integer activeTaskId: mActiveTasks) {
>       listener.onHeadlessJsTaskStart(activeTaskId);
>     }
>   }
> ```
> 
> I'm going to create an issue in `react-native` linking this issue and could share a link to the patched version if there's interest.
> 
> Edit: Improved formatting
react-native ios has the same timer issue, Could you help to look into it? 😂

**Comment by marcesengel** [comment]
@Aaronphy you haven't added any comment to the text you cited 👀
