### ISSUE TITLE
RTDB Emulator

### ISSUE THREAD

**Issue by rishisingh-dev** [invertase/react-native-firebase#3957]
Can we use emulator for realtime database? 

I don't able to find any documentation about it. So posting here.

I've posted a SO question as well. 
https://stackoverflow.com/questions/62935494/react-native-firebase-rtdb-emulator

Cheers!

**Comment by mikehardy** [comment]
Don't just ask, try it

**Comment by rishisingh-dev** [comment]
Try what? how?

**Comment by mikehardy** [comment]
You asked a question. What if you could answer it yourself?
What I mean specifically is that you must realize react-native-firebase is really the thinnest possible wrapper around firebase-ios-sdk and firebase-android-sdk github repos, the official Google Firebase Native SDK libraries.

Those libraries have documentation.

And react-native-firebase is just a thin wrapper around the libraries

So, try following the official upstream documentation and using the emulators. See how it goes. Report back

**Comment by rishisingh-dev** [comment]
But when I use rn-firebase, I don't have got any `initializeApp`. 
how can I config Db url like web sdk?

**Comment by mikehardy** [comment]
Similar, maybe works? **try things**
https://rnfirebase.io/database/usage#using-a-secondary-database

Note you can also just hack right in to node_modules and alter code for quick checks of things

Open Source means "try things", there's no answer fairy with all the answers. I think you're first in this area which means you'll have to blaze some trail

**Comment by rishisingh-dev** [comment]
How is that possible that nobody tried rtdb emulator before? ;(
okay, I will be checking 2nd db.

**Comment by mikehardy** [comment]
My guess is react-native-y people are also JSON-y people and we're all in firestore, based on volume of traffic here in issues and PRs etc. Also the emulators are semi new? So here we are :-)

**Comment by SrBrahma** [comment]
To others, as the SO answer says and as I also tested and worked, this will work:

const database = firebase.app().database('http://localhost:9000?ns=YOUR_DATABASE_NAMESPACE');

If you are using this network configuration (https://stackoverflow.com/a/60906356), you may use 'http://192.168.x.x:9000?...' as the database URL.

**Comment by majirosstefan** [comment]
Hey guys, what about adding info "about how to setup RTDB emulator" into docs ? I think by doing that we would save time of other folks..

**Comment by mikehardy** [comment]
PRs happily accepted :pray: - docs in particular may be done just by hitting the edit button on top right of every page

**Comment by majirosstefan** [comment]
https://github.com/invertase/react-native-firebase/pull/4798
