### ISSUE TITLE
Issue writing array to Firestore on iOS only

### ISSUE THREAD

**Issue by Zloka** [invertase/react-native-firebase#3958]
## Issue

When writing data to Firestore, my write is allowed on Android devices (and web, for that matter), but not on iOS devices. From what I can tell, the write should succeed as the data passed on both Android and iOS is valid.

The user can submit an array possibly containing the numbers 1 to 4, and the rule that validates it is the following:
```
return
  request.resource.data.reasons is list &&
  request.resource.data.reasons.size() <= 4 &&
  request.resource.data.reasons.hasOnly([1,2,3,4]);
```

This works on Web and Android, and on iOS an empty array is accepted. However, including one or more of the accepted numbers 1, 2, 3 or 4 is for some reason denied. The write succeeds if I remove the `hasOnly` condition.

Any ideas what might be happening to my dear array of numbers? 🙁  

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
How odd! The source is available so I strongly recommend a bit of diagnosis, chasing the .hasOnly method through from JS to native SDK API calls with either some console/NSLog-debugging or Xcode breakpoints?

In general though, you have completely ignored the issue template, so how can I help?
