### ISSUE TITLE
"Crashlytics Android-Setup" docs missing something

### ISSUE THREAD

**Issue by daheeahn** [invertase/react-native-firebase#3959]
## Documentation Feedback

"react-native-firebase/docs/crashlytics/android-setup.md" is missing

```
implementation 'com.google.firebase:firebase-crashlytics:17.1.0'
```
in android/app/build.gradle

please add this step!

**Comment by andersonaddo** [comment]
I don't think that's needed.
A number of people have gotten Android Crashlytics working without that

**Comment by daheeahn** [comment]
Really? I couldn't work Crashlytics without that code.
And when I added that code, Crashlytics works well.

**Comment by andersonaddo** [comment]
Maybe provide more information about your environment, maybe something's up.

**Comment by daheeahn** [comment]
"@react-native-firebase/analytics": "^7.3.1",
    "@react-native-firebase/app": "^8.2.0",
    "react-native": "0.62.0",

If your answer is correct, I think android/app/build is problem.
I don't reproduce this problem because it is already connected, but it could have been if I had deleted it.

**Comment by andersonaddo** [comment]
Well from what you're saying it sounds like a local environment problem :/
You can still reproduce the problem, though.
Delete `implementation 'com.google.firebase:firebase-crashlytics:17.1.0'`, delete `android/app/build `, then try and see if a test crash comes into the crashlytics console.

**Comment by daheeahn** [comment]
OK I will try! Thanks :)

**Comment by andersonaddo** [comment]
Note: you usually don't have to manually enter `implementation xxx` into Gradle anymore in RN because of auto-linking. So I think this might be an auto-linking problem.

**Comment by sushant115** [comment]
Hi,
i am using following version, i don't see crashes in Firebase Dashboard. 
"@react-native-firebase/app": "8.2.0",
"@react-native-firebase/crashlytics": "8.1.2",

My project was using fabric after migrating RNFBV8, i removed fabric from project but now crash is not appearing in Firebase Dashboard

**Comment by andersonaddo** [comment]
@sushant115 start a new issue for this, and fill in the template. 
Also make sure you've done performed the new installation steps properly!
