### ISSUE TITLE
Failed to crunch file

### ISSUE THREAD

**Issue by comycos** [invertase/react-native-firebase#396]
### Issue

I'm getting this error when I sync the project with Gradle files:
[https://imgur.com/a/uo0IN](https://imgur.com/a/uo0IN)
Gradle output:
[https://imgur.com/a/KLST3](https://imgur.com/a/KLST3)
and when I try to compile, I get:
[https://imgur.com/a/L8Fss](https://imgur.com/a/L8Fss)

Can I fix it? How?

I only installed the RNFirebase nothing else.
### Environment

1. Application Target Platform: Android

2. Development Operating System: 

3. Build Tools:  Android Studio 2.3.3

4. React Native version:  0.48.1

5. RNFirebase Version: 2.2.0

6. Firebase Module: N/A

**Comment by Salakar** [comment]
Failed to crunch file means studio can't process the file as the file path has reached the max file path line of the operating system. Yay for windows \o/

-> **Crude way** to solve it is move the project to some folder in the root of your drive, so  "D:\" in this case.

-> **Better way** is to change the build directory of your project in your `build.gradle` file (Project gradle file)

```groovy
allprojects {
    buildDir = "C:/tmp/${rootProject.name}/${project.name}"
    // ..
    // ...
}
```

**Comment by skjangid** [comment]
This is the issue with the long path of folder, i just replace my project folder its working fine for me.
