### ISSUE TITLE
only Android: notification is displayed without image icon

### ISSUE THREAD

**Issue by azuxx** [invertase/react-native-firebase#3967]
## Issue

Here's the problem:

![Screenshot_20200717-161812](https://user-images.githubusercontent.com/16132913/87796370-8fdcc700-c849-11ea-99fc-bb00a7191a90.png)

Here I put the notification icons:

![Screenshot 2020-07-17 at 16 16 50](https://user-images.githubusercontent.com/16132913/87795927-00371880-c849-11ea-98d2-7cf4f4fb58ff.png)

Here's one of them created with: https://romannurik.github.io/AndroidAssetStudio/icons-notification.html

![Screenshot 2020-07-17 at 16 23 37](https://user-images.githubusercontent.com/16132913/87796658-f06c0400-c849-11ea-986b-74cd5f3890c0.png)

You can find the configuration in AndroidManifest.xml.
I also tried with firebase.json but problem still exists.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "XxxReactNative",
  "version": "0.8.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "graphql-init": "graphql-codegen init",
    "codegen": "graphql-codegen --config codegen.yml"
  },
  "dependencies": {
    "@airbrake/browser": "^1.3.0",
    "@apollo/client": "^3.0.0-rc.10",
    "@apollo/link-error": "^2.0.0-beta.3",
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/datetimepicker": "^2.4.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/picker": "^1.6.5",
    "@react-native-community/slider": "^3.0.0",
    "@react-native-firebase/app": "^8.2.0",
    "@react-native-firebase/messaging": "^7.4.2",
    "@react-navigation/bottom-tabs": "^5.5.2",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.5.1",
    "babel-plugin-module-resolver": "^4.0.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "base-64": "^0.1.0",
    "jetifier": "^1.6.6",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-background-timer": "^2.2.0",
    "react-native-ble-plx": "^2.0.1",
    "react-native-chart-kit": "^5.6.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-localization": "^2.1.6",
    "react-native-localize": "^1.4.0",
    "react-native-paper": "^3.10.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-restart": "^0.0.15",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.8.0",
    "react-native-secure-key-store": "^2.0.7",
    "react-native-svg": "^12.1.0",
    "react-native-vector-icons": "^6.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@graphql-codegen/cli": "^1.16.0",
    "@graphql-codegen/fragment-matcher": "^1.16.0",
    "@graphql-codegen/introspection": "^1.16.0",
    "@graphql-codegen/typescript": "^1.16.0",
    "@graphql-codegen/typescript-operations": "^1.16.0",
    "@graphql-codegen/typescript-react-apollo": "^1.16.0",
    "@react-native-community/eslint-config": "^1.1.0",
    "@types/base-64": "^0.1.3",
    "@types/jest": "^24.9.1",
    "@types/react": "^16.9.34",
    "@types/react-native": "0.62.2",
    "@types/react-native-background-timer": "^2.0.0",
    "@types/react-native-dotenv": "^0.2.0",
    "@types/react-test-renderer": "16.9.2",
    "@typescript-eslint/eslint-plugin": "^2.29.0",
    "@typescript-eslint/parser": "^2.29.0",
    "babel-jest": "^24.9.0",
    "eslint": "^6.8.0",
    "eslint-import-resolver-babel-module": "^5.1.2",
    "eslint-plugin-import": "^2.20.2",
    "graphql-tag": "^2.10.3",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "prettier": "^2.0.2",
    "react-native-dotenv": "^0.2.0",
    "react-test-renderer": "16.11.0",
    "typescript": "^3.8.3"
  },
  "resolutions": {
    "graphql": "^14.5.8"
  },
  "postinstall": "npx jetify",
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [X] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
rootProject.name = 'XxxxReactNative'
include ':react-native-ble-plx'
project(':react-native-ble-plx').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-ble-plx/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'

```

#### `MainApplication.java`:

```java
package com.app.xxxx;

import android.app.Application;
import android.content.Context;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.polidea.reactnativeble.BlePackage;
import com.polidea.reactnativeble.BlePackage;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import java.lang.reflect.InvocationTargetException;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }
      };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
  }

  /**
   * Loads Flipper in React Native templates. Call this in the onCreate method with something like
   * initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
   *
   * @param context
   * @param reactInstanceManager
   */
  private static void initializeFlipper(
      Context context, ReactInstanceManager reactInstanceManager) {
    if (BuildConfig.DEBUG) {
      try {
        /*
         We use reflection here to pick up the class that initializes Flipper,
        since Flipper library is not available in release mode
        */
        Class<?> aClass = Class.forName("com.app.xxxx.ReactNativeFlipper");
        aClass
            .getMethod("initializeFlipper", Context.class, ReactInstanceManager.class)
            .invoke(null, context, reactInstanceManager);
      } catch (ClassNotFoundException e) {
        e.printStackTrace();
      } catch (NoSuchMethodException e) {
        e.printStackTrace();
      } catch (IllegalAccessException e) {
        e.printStackTrace();
      } catch (InvocationTargetException e) {
        e.printStackTrace();
      }
    }
  }
}

```

#### `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.app.xxxx">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission-sdk-23 android:name="android.permission.ACCESS_COARSE_LOCATION"/>

    <!-- Add this line if your application always requires BLE. More info can be found on:
         https://developer.android.com/guide/topics/connectivity/bluetooth-le.html#permissions
      -->
    <uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>

    <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@mipmap/ic_stat_ic_notification" />

    <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="xxxxx-notifications"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:host="xxxx-staging.xxxxx.io"
                    android:scheme="https" />
          </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 1.21 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /Users/andreazorzi/.rvm/rubies/ruby-2.5.7/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_92 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - "@react-native-firebase/app": "^8.2.0",
     "@react-native-firebase/messaging": "^7.4.2"
- **`Firebase` module(s) you're using that has the issue:**
  - `idk`
- **Are you using `TypeScript`?**
  - `Y` & `v3.8.3`

</p>
</details>

**Comment by Ehesp** [comment]
Could you show you code?

**Comment by davidecastello** [comment]
Hi @Ehesp, a colleague of @azuxx here. 

I think the really interesting piece of code is inside the AndroidManifest.xml. 
`<meta-data`
`            android:name="com.google.firebase.messaging.default_notification_icon"`
 `           android:resource="@mipmap/ic_stat_ic_notification" />`
`<meta-data`
`           android:name="com.google.firebase.messaging.default_notification_color"`
`           android:resource="@color/notification_color" />`
`<meta-data`
`            android:name="com.google.firebase.messaging.default_notification_channel_id"`
`            android:value="xxxxx-notifications"/>`

We added the color and channel id with no problem, it's just the notification image that seems to be having some issues. 

The notification is showing a grey circle, with would be the app icon colored with "notification_color", as if we never provided a notification icon at all. 

We wanted to ask if there was something we missed about customizing the Android notification icon. 

Thanks, 
Davide

**Comment by Ehesp** [comment]
Have you added the name of the icon as described here: https://notifee.app/react-native/docs/android/appearance#small-icons

**Comment by mikehardy** [comment]
This looks like the classic "why is my notification gray" in android issue. https://stackoverflow.com/questions/45318614/why-is-my-smallicon-for-notifications-always-greyed-out

notifee docs are sometimes notifee-specific but sometimes just handle the general tasks necessary for notifications to work as desired, might still be worth a look

**Comment by davidecastello** [comment]
Yes, they say it should be a .png image with transparent background, and they suggest to generate it with the tool we used. 
You can see that the results is as requested: 
![ic_stat_ic_notifcation](https://user-images.githubusercontent.com/14249532/87802111-f9140880-c850-11ea-8117-a3a3e8f2cf9e.png)

I'm sorry to return on this point, but we do not have installed Notifee, we are only using your library, since Notifee is pretty expensive. Do we need Notifee to customize the Android notification icon?

Otherwise, do you have any other idea as to what may be causing the issue?

Thanks, 
Davide

**Comment by Ehesp** [comment]
> You're linking the Notifee docs, but I saw that Notifee has a license of $240 so we are not using it. We are just using your library.

So you're not using Notifee to show the notification?

**Comment by Ehesp** [comment]
Wow sorry I thought this was the Notifee repo 🤦 Long day

Yeah so we don't do anything special here with notifications, it comes down to the link @mikehardy sent over, it's more of an Android thing rather than RN or RNFB.

**Comment by davidecastello** [comment]
Ok, thanks. We've tried what was suggested on that link and it didn't work, but if you say it comes down to native things, I hope we'll figure it out. Thanks!

**Comment by JesperLekland** [comment]
> Wow sorry I thought this was the Notifee repo 🤦 Long day
> 
> Yeah so we don't do anything special here with notifications, it comes down to the link @mikehardy sent over, it's more of an Android thing rather than RN or RNFB.

Hi guys! 

I looks like you do supply us with the option to do [icon tinting](https://rnfirebase.io/messaging/usage#notification-color), but not the option to actually set the icon (this was available in v5 through `com.google.firebase.messaging.default_notification_icon` in the `AndroidManifest.xml`). From what I can see [digging through the code](https://github.com/invertase/react-native-firebase/blob/master/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingSerializer.java#L142) it looks like you no longer have a default icon, but just get it from the incoming RemoteMessage. Could we possibly add a default icon specified from the AndroidManifest like we used to have? 

This affects us, having upgraded from v5 to v6 (everything else is awesome! 🥇 )

**Comment by pabloearg** [comment]
> icon tinting

any update with this?

**Comment by pabloearg** [comment]
> > Wow sorry I thought this was the Notifee repo 🤦 Long day
> > Yeah so we don't do anything special here with notifications, it comes down to the link @mikehardy sent over, it's more of an Android thing rather than RN or RNFB.
> 
> Hi guys!
> 
> I looks like you do supply us with the option to do [icon tinting](https://rnfirebase.io/messaging/usage#notification-color), but not the option to actually set the icon (this was available in v5 through `com.google.firebase.messaging.default_notification_icon` in the `AndroidManifest.xml`). From what I can see [digging through the code](https://github.com/invertase/react-native-firebase/blob/master/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingSerializer.java#L142) it looks like you no longer have a default icon, but just get it from the incoming RemoteMessage. Could we possibly add a default icon specified from the AndroidManifest like we used to have?
> 
> This affects us, having upgraded from v5 to v6 (everything else is awesome! 🥇 )

any update with this?

**Comment by mikehardy** [comment]
No there is not - I believe it just uses the app icon? We process PRs and merge+release pretty quickly though if someone puts a PR together

**Comment by JerakRus** [comment]
I've been experimenting with firebase and other free libraries for the last few days. When you send a notification to fcm from the server, there is an icon field. In my case, it finds it by name in the mipmap folders. Also note that not all icons, even if they are .png and work on a transparent background.
I hope this helps in some way!

**Comment by mikehardy** [comment]
@JerakRus did you know most people are seeing the graphics included on react-native for their android apps completely by chance? I wonder if it's not finding them because they are not there? Seems if it finds one, it should find any, no? https://twitter.com/fastsquatch/status/1196475279688028160 (that is me on twitter with the details, not some random link)

**Comment by JerakRus** [comment]
It seems with my bad English, I did not quite understand the problem correctly.) And I tried to point out which way to think, but it seems my comment was not in the subject.

@mikehardy thanks for the link. Does this seem to make sense when we use `shrinkResources true`? But in any case, very interesting and useful information for the future!

**Comment by odesey** [comment]
@azuxx I was also having this issue, I did 2 things:

1 - I moved the icon files to the `drawable` folder in Android and updated my `AndroidManifest.xml` file like so:

```xml
<meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_stat_ic_notification" />
```

2 - I was missing the the `icon` field in my notification message:
https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support

Now my icons work as expected on Android.

Hope that helps.

**Comment by azuxx** [comment]
> @azuxx I was also having this issue, I did 2 things:
> 
> 1 - I moved the icon files to the `drawable` folder in Android and updated my `AndroidManifest.xml` file like so:
> 
> ```
> <meta-data
>             android:name="com.google.firebase.messaging.default_notification_icon"
>             android:resource="@drawable/ic_stat_ic_notification" />
> ```
> 
> 2 - I was missing the the `icon` field in my notification message:
> https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support
> 
> Now my icons work as expected on Android.
> 
> Hope that helps.

Hi @odesey ,
unfortunately it did not work. Here's the details:

1) As your advise I put the configuration
![Screenshot 2020-11-04 at 09 56 16](https://user-images.githubusercontent.com/16132913/98090341-30e89f80-1e84-11eb-9790-8ada430b97db.png)
2)Looking at the docs icon field is not compulsory as it tells Android manifest conf will be used ('Sets the notification icon to myicon for drawable resource myicon. If you don't send this key in the request, FCM displays the launcher icon specified in your app manifest.')
3)What I get: 
![Screenshot_20201104-095507](https://user-images.githubusercontent.com/16132913/98090775-ca17b600-1e84-11eb-8fdf-4011296523a1.png)
If you look also MiFit has the issue, apparently...


Am I doing something wrong?

**Comment by afilp** [comment]
I have the same problem, the default behavior of not including an icon and rather have the launcher icon to appear, does not work.

**Comment by axelnico** [comment]
@azuxx Hi! For me, adding this line inside the application tag in the AndroidManifest.xml did the trick (in your example you have it inside the manifest tag):

```
<application ......
<meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@mipmap/ic_notification" />
</application>

```
