### ISSUE TITLE
Sending notifications requires two messages

### ISSUE THREAD

**Issue by georgecirilo** [invertase/react-native-firebase#3968]
Hello.

I'm trying to send notifications to my devices and I'm getting an differences on the foreground and background behaviors.
If I send just the json messageForeground (see code), I'll get the dat by the messaging().onMessage() method and the background notification will not show while using the app (working as expected).
If I send just the json messageBackground (see code), I'll only get the background notification if the app is killed or in the background (working as expected).

Now, if I try to create an unique message with the fields {registration_ids: [...], data: {}, notifications: {}}, trying to combine the messages in one, then I'll get the notification if the app is killed or in the background but will not get the data with the messaging().onMessage() method when the app is runnig.

Result: I'm sending two separated messages as shown below. I'm not sure what I'm missing to get the json work propperly or if there is a bug preventing the listener to trigger.

```
             const messageForeground = {
			registration_ids: tokens,
			data: {
				title: title,
				body: body,
				url: url
			}
		}
		const messageBackground = {
			registration_ids: tokens,
			notification: {
				title: title,
				body: body,
				"vibrate": 1,
				"sound": 1,
				"show_in_foreground": true,
				"priority": "high",
				"content_available": true,
			},
		}
		let headers = new Headers({
			"Content-Type": "application/json",
			"Authorization": "key=" + APIKey
		});
		let responseFront = await fetch("https://fcm.googleapis.com/fcm/send", { method: "POST", headers, body: JSON.stringify(messageForeground) })
		let responseBack = await fetch("https://fcm.googleapis.com/fcm/send", { method: "POST", headers, body: JSON.stringify(messageBackground) })
		return {...await responseFront.json(), ...await responseBack.json()}
```

package.json: "react-native-firebase": "^5.6.0"

- [x] I'm using Pods and my Podfile looks like:
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Firebase/Messaging' 
[ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?
- [x] **Android** but have not tested behavior on iOS

Thank you!

**Comment by mikehardy** [comment]
Have you seen the changes since v5? #3339 

I can't imagine spending any time troubleshooting v5 issues at this point, sorry - it is definitely time to upgrade

**Comment by georgecirilo** [comment]
Hi @mikehardy . First, thanks for all the work you're doing around here.

Initially I was trying to use the sendMessage method, but I was not able to do so since I couldn't pass a proper RemoteMessage object. I run into this issue https://github.com/invertase/react-native-firebase/issues/3817 where you explain that this "works with custom servers that implement XMPP". Being that said, that options is out of the question since I'm trying to run everything with FMC. 

I was not able to find another firebase.messaging() method to fire the notifications, so after a lot of comes and goes I ended up sending the messages the way I originally posted here. Any ideas on what might I be missing?

**Comment by mikehardy** [comment]
just a note on XMPP, one of the interesting things about Firebase Cloud Functions is that you can effectively run node servers in them, which is to say, you could implement an XMPP server as a cloud function. So for people that really need to have actual devices send other devices messages (which implies XMPP) it's still possible to do entirely within firebase

As for your specific questions, I do not know, this might have been fixed in v6+, I would not attempt to troubleshoot anything in v5

**Comment by georgecirilo** [comment]
Thank you for the note, upgrading to v6. Closing ticket
