### ISSUE TITLE
iOS Crashlytics setup broken link

### ISSUE THREAD

**Issue by mconiglio** [invertase/react-native-firebase#3970]
## Documentation Feedback

Hello. First of all thank you for creating this libraries, they all work great, and the documentation is awesome!

I'm using the firebase/app (`7.2.1`), firebase/analytics (`7.1.4`) and firebase/crashlytics (`7.1.5`) packages on a RN `0.59.2` app. Android works well, but I'm facing an issue now where the dSYMs aren't being uploaded to the Crashlytics console.

I added the a script to the build phases as detailed in the docs that has this:
```"${PODS_ROOT}/Fabric/run"```

I noticed that there were some changes on the Crashlytics implementation on the last versions, and that the script ran the command `upload-symbols`, which now is not under Fabric, but under the `FirebaseCrashlytics` pod.

I was guessing that maybe upgrading to the last version of the RN firebase/crashlytics package could solve the problem, though I'm not sure about it (any guidance on this would be super helpful 🙏).

But when reading the last version of the docs about the iOS setup, and the dSYMs files upload step I didn't found anything. Not even the old `Fabric/run` script call. And I noticed that the "iOS additional config steps" link is broken ([under this section](https://rnfirebase.io/crashlytics/usage/installation/ios#2-ios-additional-steps)).

If you could give any guidance on this it would help a lot. I'm not sure if upgrading to the last version is the solution to this, or maybe I'm just missing something on the setup for the `upload-symbols` script to work as expected.

Thanks in advance for your help, and again for creating this set of libraries!

**Comment by mikehardy** [comment]
Hi there!

You are integrating an outdated version of crashlytics :fearful: 
But also, uploading dSYMS is in general not useful these days, worth mentioning: https://stackoverflow.com/questions/54577202/how-to-run-upload-symbols-to-upload-dsyms-as-a-part-of-xcode-build-process/55796619#55796619

We don't officially support RN59 for RNFBv6+ but that likely doesn't affect these docs

I believe this section of the docs was updated for #3580 ?

**Comment by mconiglio** [comment]
Thanks for the info @mikehardy! Yes, I'm using this version of the firebase package because I configured it like a month ago or maybe even more. I don't have the possibility to upgrade the RN version right now due to the nature of the project, but I'm aware of the troubles it implies sometimes.

I read your answer on SO, but this error appears on the Crashlytics console if I don't upload the dSYMs:
![image](https://user-images.githubusercontent.com/15303963/87837388-ba3e7c80-c869-11ea-9c91-1655f0d4054e.png)

Despite the RN version, and considering your answer on SO... do you think that the best choice should be to upload the dSYMs files manually by downloading them from AppStore connect? Or do you have any other recommendation?

**Comment by mikehardy** [comment]
My answer on SO is unequivocal, in the dSYM error if you do not somehow get the app-store-generated dSYMs into crashlytics *post-upload-to-the-app-store*, your work has no effect.

I recommend fastlane

**Comment by mconiglio** [comment]
Ok, thanks for the answer. I was just thinking that maybe the upload script can still be useful for the AppCenter (or other similar tools) builds, despite it's not useful for the AppStore ones. That's the main reason of my question.

**Comment by mikehardy** [comment]
Hmmm I was not thinking there was a viable pathway on to an iDevice except app store but if there are other avenues then I suppose those could use the dSYMs from the build, but at that point you've got two dSYMs pathways, is that viable? Wouldn't it be better to have one? Perhaps fastlane has plugins for all your use cases.

**Comment by mconiglio** [comment]
Ok, thanks for the info. I guess the best thing would be to use Fastlane and maybe customize the scripts a little depending on if it's a build for AppCenter or a build for the AppStore. Thanks again!
