### ISSUE TITLE
How can i navigate when setBackgroundMessageHandler run?

### ISSUE THREAD

**Issue by ali412** [invertase/react-native-firebase#3971]
import {AppRegistry, Alert} from 'react-native';
import App from './src/App';
import {name as appName} from './app.json';
import messaging from '@react-native-firebase/messaging';

messaging().setBackgroundMessageHandler(async result=>{
  
});

AppRegistry.registerComponent(appName, () => App);
-----------------------------------------------------------------------------

my index.js is above but how can i navigate to a page?
help me please!

**Comment by Ehesp** [comment]
There is nothing to navigate, your app is in the background and not running.

You'd handle this when the user opens the app.

**Comment by ali412** [comment]
> There is nothing to navigate, your app is in the background and not running.
> 
> You'd handle this when the user opens the app.

ok. But how can i handle ?
with which command?

**Comment by andersonaddo** [comment]
That depends on the third party notification package that you decided to use.
