### ISSUE TITLE
onMessage listener does no trigger when new message send v7.4.2

### ISSUE THREAD

**Issue by mtalhagaoglu** [invertase/react-native-firebase#3972]
##ISSUE

Hi. i am building an app that uses can receive messages when they need but they can't now because onMessage listener doesn't trigger when i send notifications from firebase console with spesific device token. It's not about push notifications because i just want to see on console for now and it doesn't happen.

other packages that i use ( database and auth ) works 

---

### Javascript

`
messaging().onMessage((response) => {
      console.log(JSON.stringify(response));
      alert(JSON.stringify(response));
    });
`
#### `package.json`:

```json
"@react-native-firebase/app": "^8.2.0",
    "@react-native-firebase/auth": "^8.2.0",
    "@react-native-firebase/database": "^7.3.2",
    "@react-native-firebase/messaging": "^7.4.2",
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 8.2.0
- **`Firebase` module(s) you're using that has the issue:**
  - message
- **Are you using `TypeScript`?**
  - N

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
based on the template information provided (it was not provided...) I cannot help
