### ISSUE TITLE
Non-fatal Exception: io.invertase.firebase.crashlytics.JavaScriptError

### ISSUE THREAD

**Issue by Daha62** [invertase/react-native-firebase#3973]
## Issue
After upgrading react-native-firebase to v5, I caught such non-fatal exceptions:

![image](https://user-images.githubusercontent.com/6141193/87911108-825f5100-ca84-11ea-8639-2d0e93706e79.png)
it happens every time I open my android app

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**
```
 System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 53.44 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 19, 21, 23, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 27.0.3, 28.0.3
      System Images: android-16 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_201 - /usr/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both

- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

**Comment by andersonaddo** [comment]
Send to be originating from `crashlytics().recordError()`

You've completely ignored the template, so noone can help. All I will say is that crashlytics was changed in V8, you might want to check the docs for that.
