### ISSUE TITLE
I don't find react native documentation about getting android device token to send push ( GSM token )

### ISSUE THREAD

**Issue by khaledBou** [invertase/react-native-firebase#3975]
## Issue

 I'm using :  
```
 "@react-native-firebase/app": "^8.2.0",
 "@react-native-firebase/messaging": "^7.4.2",
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [X] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Memory: 111.59 MB / 24.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/.npm-global/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native: 0.61.5
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^8.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/messaging`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by andersonaddo** [comment]
Are you walking about GCM? GCM has been replaced my FCM, and FCM token can be gotten via [getToken](https://rnfirebase.io/reference/messaging#getToken) and [onTokenRefreshh](https://rnfirebase.io/reference/messaging#onTokenRefresh)

**Comment by khaledBou** [comment]
but there's no documentation about how to use those methods, i can't find documentation about js implementation or java implementation for react native to show the android device token, i remember the documenation exists in an old version of cloud massaging

**Comment by andersonaddo** [comment]
Do you mean here?
https://rnfirebase.io/messaging/server-integration#device-tokens

**Comment by khaledBou** [comment]
yes it should be the implementation that i'm looking for. it's strange to find it in server implementation section. thanks

**Comment by andersonaddo** [comment]
Yes I agree, it not the most intuitive place for this information 😅
