### ISSUE TITLE
Firebase messaging.getToken() fails with MISSING_INSTANCEID_SERVICE error

### ISSUE THREAD

**Issue by hidayatridwan** [invertase/react-native-firebase#3980]
I am trying to integrate Firebase Cloud Messaging into an ongoing project. I followed the guide for installation [here](https://rnfirebase.io/messaging/usage) and installed both @react-native-firebase/app and @react-native-firebase/messaging. However, when I attempt to get device token with await messaging.getToken() it fails with this warning -NativeFirebaseError: [messaging/unknown] MISSING_INSTANCEID_SERVICE

Please note that if I send a push notification from firebase console, it gets delivered on a real phone, which shows that the issues is probably not with the FCM set up.

Any helpful suggestions will be appreciated

**Comment by hidayatridwan** [comment]
its solved. by install google play in emulator
thanks.

**Comment by talhatsk** [comment]
@hidayatridwan is there any way to check if the phone has google play services installed on it ?
