### ISSUE TITLE
AUTHENTICATION_FAILED when calling firebase.messaging().getToken();

### ISSUE THREAD

**Issue by FionaYam** [invertase/react-native-firebase#3981]
## Issue

> W/System.err: java.io.IOException: AUTHENTICATION_FAILED

Hi, I'm hitting this error message when i try to called firebase.messaging().getToken();
It only happens on few android devices such as Huawei P10 pro.
Does anyone have idea with this issue? :)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

        firebase.messaging().hasPermission()
        .then(enabled => {
            if (enabled) {
                getToken(callback);
            } else {
                requestPermission(callback);
            }
        });

        async function getToken(callback?) {
            let fcmToken = await AsyncStorage.getItem('fcmToken');
            if (!fcmToken) {
                try {
                    fcmToken = await firebase.messaging().getToken(); //returns AUTHENTICATION_FAILED error
    
                    if (fcmToken) {
                        await AsyncStorage.setItem('fcmToken', fcmToken);
                        if (callback) {
                            callback();
                        }
                    }
                } catch (error) {
                    console.log('error', error);
                }
            } else {
                if (callback) {
                    callback();
                }
            }
        }

#### `package.json`:

```json
"react-native-firebase": "5.5.6",
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
  pod 'Firebase/Messaging'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
```

#### `AppDelegate.m`:

```objc

#import <Firebase.h>
#import "RNFirebaseNotifications.h"
#import "RNFirebaseMessaging.h"

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
  [[RNFirebaseMessaging instance] didRegisterUserNotificationSettings:notificationSettings];
}

-(void) userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler {
 
  [[RNFirebaseMessaging instance] didReceiveRemoteNotification:response.notification.request.content.userInfo];
  completionHandler();
}


```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [X] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
classpath 'com.google.gms:google-services:4.2.0'
```

#### `android/app/build.gradle`:

```groovy
implementation "com.google.firebase:firebase-core:16.0.9"
implementation "com.google.firebase:firebase-messaging:20.1.0"
implementation "com.google.firebase:firebase-analytics:17.2.2"
```

#### `android/settings.gradle`:

```groovy
include ':@react-native-firebase_analytics'
project(':@react-native-firebase_analytics').projectDir = new File(rootProject.projectDir, './../node_modules/@react-native-firebase/analytics/android')
```

#### `MainApplication.java`:

```java

import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;
import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;
import io.invertase.firebase.analytics.RNFirebaseAnalyticsPackage;

new RNFirebasePackage(),
new RNFirebaseMessagingPackage(),
new RNFirebaseNotificationsPackage(),
new RNFirebaseAnalyticsPackage(),
```

#### `AndroidManifest.xml`:

```xml
      <meta-data
          android:name="com.google.firebase.messaging.default_notification_icon"
          android:resource="@mipmap/ic_launcher" />

      <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
          <intent-filter>
              <action android:name="com.google.firebase.MESSAGING_EVENT" />
          </intent-filter>
      </service>
      <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
          <intent-filter>
              <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
          </intent-filter>
      </service>
        
      <meta-data
          android:name="com.google.firebase.messaging.default_notification_channel_id"
          android:value="channelId" /> 
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 293.17 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 28, 29
        Build Tools: 23.0.3, 26.0.1, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.1, 29.0.2
        System Images: android-19 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [X] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 5.5.6
- **`Firebase` module(s) you're using that has the issue:**
  - getToken()
- **Are you using `TypeScript`?**
  - `Y` & `^3.7.0`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! v5 no longer receives support, please see if you can reproduce this on current versions

**Comment by FionaYam** [comment]
Hi Mike, i have tried update to v7 but still having the same issue

**Comment by mikehardy** [comment]
Okay @FionaYam - I am sorry to hear that but thank you for reporting back. The information provided in the bug report is likely no longer correct with regard to the current reproduction on current versions, can you edit it in order to represent your latest reproduction? And if there is any more information you could provide from the log that would be useful, like if there was a full stack trace or anything
