### ISSUE TITLE
error Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by viprathore** [invertase/react-native-firebase#3985]
Hello there everyone;
info: -> RNFB build script started
info: 1) Locating firebase.json file:
info:      (1 of 2) Searching in '/Applications/XAMPP/xamppfiles/htdocs/home/market/mobile' for a firebase.json file.
Unknown option: n
Usage: head [-options] <url>...
    -m <method>   use method for the request (default is 'HEAD')
    -f            make request even if head believes method is illegal
    -b <base>     Use the specified URL as base
    -t <timeout>  Set timeout value
    -i <time>     Set the If-Modified-Since header on the request
    -c <conttype> use this content-type for POST, PUT, CHECKIN
    -a            Use text mode for content I/O
    -p <proxyurl> use this as a proxy
    -P            don't load proxy settings from environment
    -H <header>   send this HTTP header (you can specify several)

    -u            Display method and URL before any response
    -U            Display request headers (implies -u)
    -s            Display response status code
    -S            Display response status chain
    -e            Display response headers
    -d            Do not display content
    -o <format>   Process HTML content in various ways

    -v            Show program version
    -h            Print this message

    -x            Extra debugging output
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by Salakar** [comment]
```
Unknown option: n
Usage: head [-options] ...
-m use method for the request (default is 'HEAD')
```

The RNFB build script doesn't do anything relating to requests so I don't think this error is coming from us.

**Comment by viprathore** [comment]
After intergrting react-native-firebase

Getting error 

The following build commands failed:
	PhaseScriptExecution [CP-User]\ [RNFB]\ Core\ Configuration /Users/m/Library/Developer/Xcode/DerivedData/market-fbvjyrqvgynvkheeqbcrsrwfuzfg/Build/Intermediates.noindex/market.build/Debug-iphonesimulator/market.build/Script-761D5DAB716865141E71D68B.sh

Please help, Thanks in advance

**Comment by mikehardy** [comment]
I never stop being amazed at how projects can be integrated incorrectly, in ways that are nearly impossible to figure out.
Rather than spend time figuring them out anymore, I offer this completely from-scratch throwaway app builder, read the comments in here to see how to integrate react-native-firebase and it should show you how to get it going in your project https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

**Comment by hari** [comment]
@mikehardy @Salakar  I did use rnfbdemo and still the same issue.

_Works fine if I run using Xcode but throws this error if I run using CLI._

```
rnfbdemo/rnfbdemo' for a firebase.json file.
Unknown option: n
Usage: head [-options] <url>...
    -m <method>   use method for the request (default is 'HEAD')

```

Looks like it's coming from:

https://github.com/invertase/react-native-firebase/blob/cad58e178b43dea461e17fa4a0a3fecd507ba68a/packages/app/ios_config.sh#L69

React-Native Info:
```

System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 637.06 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.3, 24.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 29.0.3
      System Images: android-24 | Android TV Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mghozyn** [comment]
I'm facing same issue when running using CLI.
Any idea how to run using CLI for this issue ?

**Comment by mikehardy** [comment]
@mghozyn in my experience 99% of people that say they have the same issue do not have the same issue. If you want support you should open a fresh ticket with full details.
