### ISSUE TITLE
Recommended way to unsubscribe to `setBackgroundMessageHandler`?

### ISSUE THREAD

**Issue by lorenz068** [invertase/react-native-firebase#3988]
## Documentation Feedback
Is it a recommended way to unsubscribe from `setBackgroundMessageHandler`?
https://rnfirebase.io/messaging/usage#background--quit-state-messages--

The documentation is very clear for foreground https://rnfirebase.io/messaging/usage#foreground-state-messages

Thank you

**Comment by Ehesp** [comment]
There's currently no way of doing that, however you can just "noop" it.

```
messaging().setBackgroundMessageHandler(async () => {
  // Do something
});

// Some time later when you don't need background handling

messaging().setBackgroundMessageHandler(async () => {});
```

**Comment by lorenz068** [comment]
The problem with that, i don't want to lost the data...i would like Firebase queue all failed messages.
Like that when the user register again, it will display all the messages.

**Comment by andersonaddo** [comment]
Why not just update the handler to save all messages to something like AsyncStorage when you want to temporarily disable the notifications?
Then when you re-enable notifications, check AsyncStorage, show anything stored there, clear it, and you're all good.

**Comment by lorenz068** [comment]
If i do that, is it possible to hide OS native notifications?

**Comment by mikehardy** [comment]
@lorenz068 you'll need to familiarize yourself with how the firebase SDKs handle cloud messages that include a notification payload. If you include a notification payload the answer is no. If you are data only, then the answer is - depends on what your handler does.

**Comment by lorenz068** [comment]
Thank you so much for the quick feedback.
