### ISSUE TITLE
Not Receiving Firebase push Notification in Background and in Appdelegate

### ISSUE THREAD

**Issue by 10xamohan** [invertase/react-native-firebase#3996]
react-native-firebase v5.2.3

My Appdelegate contains method didReceiveRemoteNotification

I was receiving logs and everything was working fine a day before.

Today again when I upload my p8 certificate to my firebase IOS app. only foreground App are showing. But I am not getting logs from Appdelegate file.

Also previously i was receiving foreground notification in firebase.notifications().onNotification((notification) => {})

but now i am geeting them in firebase.messaging().onMessage((message) => {}) method.

Overall there's no Background notifications.

My APPdelegate :

```
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
    fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{ NSLog(@"Here"); if([[userInfo objectForKey:@"UID"] isEqual: @"VideoMeeting"]){
    
    NSLog(@" contains type Here");

     if( [UIApplication sharedApplication].applicationState == UIApplicationStateInactive || [UIApplication sharedApplication].applicationState == UIApplicationStateBackground )
    {
      NSLog(@"Here 22");
      [self localNotificationRingerViewAdd:userInfo];
    }else{
      
      NSLog(@"Normal Noti 22");
      [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
    }
  }else{
    
        NSLog(@"Normal Noti 42");
       [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
  }
  
}
```

**Comment by andersonaddo** [comment]
Version 5 has been deprecated, so the chances of getting maintainer support are pretty low.

**Comment by russellwheatley** [comment]
Thanks for the issue report, @10xamohan, we’re no longer actively supporting <= v5 development so I’m going to go ahead and close this issue - but feel free to continue the discussion. If you have any issues regarding React Native Firebase >= v6, please raise a new issue.
