### ISSUE TITLE
[Android] Dynamic Link do not trigger the `getInitialLink` on fresh app install

### ISSUE THREAD

**Issue by kkusanagi** [invertase/react-native-firebase#3997]
I'm using react-native-firebase 5.6.0 and it is working.

But when i'm using `"@react-native-firebase/dynamic-links": "^7.4.3"`, it failed to get the param on device that do not have the app. Both IOS and Android have this issue.
By clicking the dynamic link, it should bring us to app store / play store if app is not installed. After installed, it should be able to get the param from the app when first called
```
firebase.dynamicLinks().getInitialLink().then((link)=>{
//use link.url
});
```
Anyone have this kind of problem?

```
const url = await DynamicLink().buildShortLink({
      link: "http://tootitoo.com?param=123456",
      domainUriPrefix: 'https://example.page.link',
      android:{
        packageName:'com.example.example'
      },
      ios:{
        bundleId: 'com.example.example',
        appStoreId: 'App Store id'
      }
    },"SHORT");
```     

All dynamic links WORKING when app is installed.

**Comment by kkusanagi** [comment]
Anyone here?

**Comment by kkusanagi** [comment]
Haha, I really mess up with the settings in Android. Luckily found some solution from Stackoverflow and old react-native-firebase 5.6.0 documentation.

Seems like the Android need to update some data in AndroidManifest.xml 

Need to change the 
`android:launchMode="singleTask"`
and Add new line for new link. Not replace them.
```
            <data android:host="example2.page.link" android:scheme="http"/>
            <data android:host="example2.page.link" android:scheme="https"/>
```

```
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:launchMode="singleTask">
        <intent-filter>
            <action android:name="android.intent.action.VIEW"/>
            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <data android:host="example.page.link" android:scheme="http"/>
            <data android:host="example.page.link" android:scheme="https"/>
            <data android:host="example2.page.link" android:scheme="http"/>
            <data android:host="example2.page.link" android:scheme="https"/>
        </intent-filter>
      </activity>
```

**Comment by mikehardy** [comment]
That's great information, it will probably help someone. I'm busy implementing dynamic links right now, might save me some time! You should really move to v6 though :-), it's needed for Firebase Crashlytics at least but the Messaging fixes post-v5 are also really important
