### ISSUE TITLE
"RNFirebaseAdMobBanner" does not exist

### ISSUE THREAD

**Issue by hackable** [invertase/react-native-firebase#400]
"RNFirebaseAdMobBanner" does not exist

### Environment

1. Application Target Platform:  iOS

2. Development Operating System:  iOS

3. Build Tools: Xcode

4. React Native version: 0.48.2

5. RNFirebase Version: 2.2.0

6. Firebase Module: 
admob

**Comment by soyangel** [comment]
Same error here also with iOS, but with React Native 0.44.0 & checked with RNFirebase 2.2.0 & 2.1.4.

**Comment by crowd-studio** [comment]
Same error with iOS, React Native 0.45.1 & RNFirebase 2.2.0

**Comment by soyangel** [comment]
I have fixed the error.

Open from Xcode: node_modules/react-native-firebase/ios/RNFirebase.xcodeproj

And now you need to add missing *.h & *.m files to the "admob" directory. You can do this drag&dropping  files from a finder (I unchecked the "copy" option in the dialog that appears).

Your admob dir should look like this:

![screen](https://user-images.githubusercontent.com/95073/30371650-83daa360-987b-11e7-9b70-52816dc968a4.jpg)

Then close Xcode & open the <your_project>.xcworkspace from your ios dir and do a clean.

After all this no warning is shown and the banner is displayed.

**Comment by chrisbianca** [comment]
Thanks for raising this.  I have just released version 2.2.1 which fixes this issue.
