### ISSUE TITLE
onTokenRefresh not generating a refreshed token for iOS/Android

### ISSUE THREAD

**Issue by kaushil111** [invertase/react-native-firebase#4001]
🔥

## Issue

I have an issue where `onTokenRefresh` is not generating a refreshed token for devices. I come to the conclusion as notifications work for devices for a couple of weeks and stop appearing after that. Also, there isn't a way to debug/check if the `onTokenRefresh` method works correctly
---

#### `onTokenRefresh` Implementation:

```
const onTokenRefresh = async (token: string) => {
    if (userStore && userStore.token) {
      postFirebaseTokenService(userStore.token, token);
    }
  };
const tokenRefreshUnsubscribe = messaging().onTokenRefresh(token =>
  onTokenRefresh(token)
);
```

#### `package.json`:

```
    "@react-native-firebase/analytics": "6.4.0",
    "@react-native-firebase/app": "6.4.0",
    "@react-native-firebase/auth": "6.4.0",
    "@react-native-firebase/crashlytics": "6.4.0",
    "@react-native-firebase/messaging": "6.4.0",
    "@react-native-firebase/remote-config": "6.4.0",
```

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods with auto linking

#### `AppDelegate.m`:

```
#import <Firebase.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  ...................
  //Configure Firebase
  [FIRApp configure];
  ...................
}

/**
* Set application's badge to 0 every time someone opens the app.
*/
- (void)applicationDidBecomeActive:(UIApplication *)application {
  [UIApplication sharedApplication].applicationIconBadgeNumber = 0;
}

@end
```

---

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 139.34 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: Not Found
    npm: 6.14.2 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /Users/kaushilruparelia/.rvm/rubies/ruby-2.6.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.4.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Messaging`
- **Are you using `TypeScript`?**
  - `N`

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by kaushil111** [comment]
👎

**Comment by dooleyb1** [comment]
@kaushil111 any update on this? Experiencing similar functionality.
