### ISSUE TITLE
react-native-firebase issue on react native version 6.14.4.

### ISSUE THREAD

**Issue by anandmahajan** [invertase/react-native-firebase#4002]
I am using react native 6.14.4.
I am getting following error..

error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-firebase (to unlink run: "react-native unlink react-native-firebase")
This is likely happening when upgrading React Native from below 0.60 
<img width="1650" alt="Firebase Issue" src="https://user-images.githubusercontent.com/1219379/88527266-aa1d5e80-d01a-11ea-926f-410fa48b9fe7.png">
to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

Can you please give me solution ASAP?
Thanks.

**Comment by Saurabh-Omega** [comment]
First of all, follow the "new issue template" to report any issue.
second, you have mentioned that 

> I am using react native 6.14.4.

but react-native don't have such version.

so, better to follow the issue template.

**Comment by anandmahajan** [comment]
Ok. 
I am new in React native development.
Please help me resolve above issue.

**Comment by andersonaddo** [comment]
We can't really help you if you don't follow the issue templates, it's especially important for issues like this. 

Without the template, all I can suggest is that you get the latest version of react native, make a fresh project, and follow the installation instructions carefully this time. 

And keep on mind that react native does auto-linking, so there are some manual installation steps that you don't have to do anymore. That's probably the source of your problem.

**Comment by anandmahajan** [comment]
ok thanks
