### ISSUE TITLE
Crashlytics does not display logs when I use ".log()'

### ISSUE THREAD

**Issue by DMZakaria** [invertase/react-native-firebase#4003]
## Issue

 `crashlytics().log('...');` does not work. I don't see the logs in the console but I got the logs when I use `recordError`.  

#### `package.json`:

```json
"@react-native-firebase/crashlytics": "^8.1.2"
```

#### `firebase.json` for react-native-firebase v6:

```json
  "react-native": {
    "crashlytics_debug_enabled": true
  }
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [x] Android

**Comment by Ehesp** [comment]
This is correct behaviour - if you want realtime logs look into analytics. Essentially Crashlytics logs are for giving you details about what the user is doing, and if the app crashes you then get those logs to help you see why it crashed.
