### ISSUE TITLE
Push notification with big picture received but image not showing

### ISSUE THREAD

**Issue by Mani1124** [invertase/react-native-firebase#4006]
` messaging().subscribeToTopic('testing')
          .then(() => {
              console.log("subscribe successfully");
          });
      messaging().onMessage(async remoteMessage => {
          console.log('A new FCM message arrived!', JSON.stringify(remoteMessage));
      });
      messaging().setBackgroundMessageHandler(async remoteMessage => {
          console.log('Message handled in the background!', remoteMessage);
      });
`
![console](https://user-images.githubusercontent.com/12595137/88620301-44cd7a00-d0bb-11ea-8c37-322293234e26.jpg)
![Screenshot_2020-07-28-10-11-06-487_com miui home](https://user-images.githubusercontent.com/12595137/88620393-8bbb6f80-d0bb-11ea-96bb-764081375f59.jpg)
![Uploading Screenshot_2020-07-28-10-11-06-487_com.miui.home.jpg…]()

Image url

![image](https://user-images.githubusercontent.com/12595137/88621568-6f6d0200-d0be-11ea-8a6f-826445e198c2.JPG)

**Comment by Mani1124** [comment]
Logcat show: FirebaseMessaging: Failed to download image in time, showing notification without it
Can we increase the image loading timeout?

**Comment by mikehardy** [comment]
@Mani1124 maybe? If it's not from the underlying SDK, find the java code here in the module and hack in a new value. Use patch-package to make it persistent for your project, and propose exposing it as an API here in a related PR

**Comment by harshmaisheri** [comment]
This is because your ImageUrl is in wrong place.
it should be like this :
```
notification : {
    title: "YOUR_TITLE",
    title: "YOUR_TITLE",
}
```

**Comment by mehul2013** [comment]
@Mani1124 
Same issue. I am facing right now. Did you find any solution for this?
@harshmaisheri Format is correct. Sometimes image displays but sometimes not and its returns an error of Failed to download image in time, showing notification without it.

**Comment by mikehardy** [comment]
If it failed to download it in time, you'll have to try a smaller image I think. Imagine if the android system allowed applications to download incredibly large files for remote notifications, and the system ran for hours draining battery and using bandwidth? The limits are there for good reasons, and we have to work within them while accepting that under some conditions the image may not show

**Comment by mehul2013** [comment]
@mikehardy We already resize the image up to 20-30Kb. I have tested on the same model of Samsung Galaxy A50 at the same time push notification and **one phone is getting push notification with image** and **another is getting only push notification without image**. Can I know which image size should I have to prefer?  And I am using a 2:1 ratio for the image.

**Comment by mikehardy** [comment]
I m not sure, it's a native sdk thing, react-native-firebase does not handle notification blocks they are handled by firebase-android-sdk. Perhaps they're have more information upstream or you could ask on stackoverflow.com

**Comment by MrIceman** [comment]
Still happening, can't load a picture after clicking on a notification
