### ISSUE TITLE
Can't see any custom user properties in Firebase console

### ISSUE THREAD

**Issue by hamidhadi** [invertase/react-native-firebase#4008]
## Issue

I'm trying to set custom user id for Firebase Analytics, but I can't see that in the firebase console.
So far I've tried these:
```javascript
firebaseAnalytics().setUserProperties({ user_id: 'XYZ' })
firebaseAnalytics().setUserProperty('user_id', 'XYZ')
firebaseAnalytics().setUserId('XYZ')
```
But none of them works. I have an Analytics module in my app which has a setup method. Whenever users accept to share their data for data tracking, I'll call that method and set the user id.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/analytics": "6.3.0",
    "@react-native-firebase/app": "6.3.0",
    "@react-native-firebase/dynamic-links": "6.3.0",
    "@react-native-firebase/messaging": "6.3.0",
    "@react-native-firebase/perf": "6.3.0",
    "@react-native-firebase/remote-config": "6.3.0",
.
.
.
    "react": "16.12.0",
    "react-native": "0.61.5",
```

#### `firebase.json` for react-native-firebase v6:

```json
{
    "react-native": {}
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.3.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Analytics`
- **Are you using `TypeScript`?**
  - `Y` & `VERSION: 3.7.5`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by andersonaddo** [comment]
Might be linked to #3843
