### ISSUE TITLE
Push notification not received in Testflight IOS build

### ISSUE THREAD

**Issue by ashish3303** [invertase/react-native-firebase#4015]
Hello, 

“@react-native-firebase/messaging”: “^7.5.0",
“react-native-firebase”: “^5.6.0",

I integrated react-native-firebase into my react-native application and integrate firebase messaging service but the problem is push notification working fine when the application is on debug mode but when i upload the build on TestFlight with distribution certificate push notification doesn't work, no push received on TestFlight IOS build. Please help me to find out from this. Here is my code : - 

AppDelegate.m 

#import “AppDelegate.h”
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>
#import “RNSplashScreen.h”
#if DEBUG
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
static void InitializeFlipper(UIApplication *application) {
 FlipperClient *client = [FlipperClient sharedClient];
 SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
 [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
 [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
 [client addPlugin:[FlipperKitReactPlugin new]];
 [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
 [client start];
}
#endif
@implementation AppDelegate
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
 if ([FIRApp defaultApp] == nil) {
  [FIRApp configure];
 }

-------------------------------------
app.js

setUpPush = () => {
        firebase.messaging().hasPermission()
            .then(enabled => {
                if (enabled) {
                    firebase.messaging().getToken().then(token => {
                        console.log(“LOG Messaging: “, token);
                        this.props.setDeviceToken(token);
                        this.messageListener();
                    })
                } else {
                    firebase.messaging().requestPermission()
                        .then(() => {
                            console.log(“User Now Has Permission”);
                            this.setUpPush();
                            this.messageListener();
                        })
                        .catch(error => {
                            console.log(“User Now Has No Permission”, error);
                            this.setUpPush();
                            // User has rejected permissions
                        });
                }
            });
    }
    /**
    * Push notification listener events
    */
    messageListener = async () => {
        console.log(“Message Listener.....“);
        messaging().setBackgroundMessageHandler(async remoteMessage => {
            console.log(‘Message handled in the background!’, remoteMessage);
        });
        messaging().onNotificationOpenedApp((message) => {
            console.log(‘Notification caused app to open from background state:’, message);
        });
        messaging().onMessage(async message => {
            console.log(‘A new FCM message arrived!’, JSON.stringify(message));
            console.log(message, “message”);
        });
    }

Thank you

**Comment by andersonaddo** [comment]
> ```
> “@react-native-firebase/messaging”: “^7.5.0",
> “react-native-firebase”: “^5.6.0",
> ```
How are you using both v5 and v7 at the same time 0.o

**Comment by ashish3303** [comment]
I am using react-native-firebase 5.6.0 for get device token and “@react-native-firebase/messaging”: “^7.5.0" for messageListner
