### ISSUE TITLE
Notification with image on iOS

### ISSUE THREAD

**Issue by sm2017** [invertase/react-native-firebase#4016]
When remote server send notification with image , Android show the image but iOS not showing
It is a missing feature?

**Comment by andersonaddo** [comment]
Have you set up the right APNS configurations?

https://firebase.google.com/docs/crashlytics/test-implementation?authuser=0#test_it_out

Provide more info please.

**Comment by sm2017** [comment]
> Have you set up the right APNS configurations?
I followed 
https://rnfirebase.io/#3-ios-setup
and 
https://firebase.google.com/docs/cloud-messaging/ios/certs

> https://firebase.google.com/docs/crashlytics/test-implementation?authuser=0#test_it_out
Why you send me crash test list of crashlytics ?

**Comment by nanthawat** [comment]
you need to add notification service extension in your ios project.

[https://firebase.google.com/docs/cloud-messaging/ios/send-image?hl=en&authuser=0#set_up_the_notification_service_extension](https://firebase.google.com/docs/cloud-messaging/ios/send-image?hl=en&authuser=0#set_up_the_notification_service_extension)

**Comment by andersonaddo** [comment]
@sm2017 my bad I meant to send this
https://firebase.google.com/docs/cloud-messaging/ios/send-image#build_the_send_request

**Comment by davidepalazzo** [comment]
@sm2017 @nanthawat is right. You need to create a notification service extension from Xcode. Follow the steps in this [comment](https://github.com/invertase/react-native-firebase/issues/2432#issuecomment-520196672) and you should be good to go.

**Comment by mikehardy** [comment]
Is this something someone could provide a PR for? If Android is doing it already it seems like having parity on the iOS platform would be good, even though notification functionality directly in react-native-firebase is otherwise limited.

Can someone confirm that this works correctly in react-native-firebase v6+ for android ?

**Comment by davidepalazzo** [comment]
Hi @mikehardy, I just pushed a PR ( #4085 ) with a solution that I've been using on some of my projects. And yes, it works in  react-native-firebase v6+ for both iOS and Android. Cheers.

**Comment by mikehardy** [comment]
@davidepalazzo - in my best kiwi voice, legend :-)
