### ISSUE TITLE
Push notifications not working when my app is closed 

### ISSUE THREAD

**Issue by sam9010** [invertase/react-native-firebase#4017]
i did not any receive fcm when my app is closed in foreground and open state i received but in background state not working i think all my code is ok but not receive
 my sample code this

https://stackoverflow.com/questions/63029273/push-notifications-not-working-when-my-app-is-closed-in-react-native-firebase/63029548?noredirect=1#comment111460980_63029548

plz help me

**Comment by andersonaddo** [comment]
V5 is deprecated, chances of support are low.

**Comment by argatahta** [comment]
You cannot handle push notification directly on the js file while in the background. But you still can show it. First, make sure your apps notification is turn on at device setting and set the priority to high for the channel. Then try to send push notification via postman `{
    "to": <fcmtoken>,
    "notification": {
        "body": "great match!",
        "sound": "wotznear.mp3",
        "title": "Testing with postman",
        "android_channel_id": "reminder",
        "icon": "ic_launcher_none"
    },
    "data": {
        "test": "testing"
    }
}`

POST https://fcm.googleapis.com/fcm/send
Content-Type : application/json
Authorization: key<server key>

And see if it works.

**Comment by russellwheatley** [comment]
Thanks for the issue report, @sam9010 , we’re no longer actively supporting <= v5 development so I’m going to go ahead and close this issue - but feel free to continue the discussion. If you have any issues regarding React Native Firebase >= v6, please raise a new issue.
