### ISSUE TITLE
Version 7 documents

### ISSUE THREAD

**Issue by sm2017** [invertase/react-native-firebase#4033]
Where is version 7 documentation?  What's breaking on v7?
https://rnfirebase.io/ has v6 and **Migrating to v6** only

**Comment by sm2017** [comment]
For some packages we have v8 too

```bash
> yarn outdated
Package                                Current Wanted  Latest  Package Type    URL
@react-native-firebase/app             6.7.1   6.7.1   8.2.0   dependencies    https://github.com/invertase/react-native-firebase/tree/master/packages/app
@react-native-firebase/crashlytics     6.7.1   6.7.1   8.1.2   dependencies    https://github.com/invertase/react-native-firebase/tree/master/packages/crashlytics
@react-native-firebase/messaging       6.7.1   6.7.1   7.5.0   dependencies    https://github.com/invertase/react-native-firebase/tree/master/packages/messaging
```

**Comment by andersonaddo** [comment]
So v7 didn't have any *huge* changes - it was a bunch of internal changes as the repo switched to GitHub Actions. 

V8's only major change is that we changed the Crashlytics SDK; we no longer use fabric. 

You can find the change logs on the site. 

I suppose, to prevent confusion, the docs should be updated a bit. Those new versions came a bit quickly so I guess the docs lagged behind. 

You can submit a PR 😁

**Comment by mikehardy** [comment]
Really anything in the docs should say "v6+" instead of "v6", the changelog does have the semver notes but the breaking changes are tiny now vs the v5 / v6 earthquake
