### ISSUE TITLE
Firebase support confirmation for react-native apps

### ISSUE THREAD

**Issue by tarunaahuja20** [invertase/react-native-firebase#4037]
## Issue

I am building an application that has a requirement of using a firebase realtime database. I tried using this library but facing some issues. Can someone please confirm if react-native supports firebase totally or it supports with some known bugs.

Describe your issue here

1. I created a react-native app. Now what I want is to stop the synchronization of the realtime database from the react-native application. So I used the property which is " keepSynced(false)" but it's not working as the expected behavior mentioned in the rnfirebase library. Also, there is another method named "setPersistenceEnabled(true)", this method is expected to return Promise but it is not doing so.
2. Need confirmation if this is a known bug and if there are some limitations in using firebase for react-native applications

---

## Project Files (Code)

const reference = database().ref('/');
reference.keepSynced(false);

database().setPersistenceEnabled(true).then() ; // not working as expected, Promise type return is not working.

**Comment by mikehardy** [comment]
To the best of my knowledge, it's working or should be working, it is not supposed to have limitations and issues when filed (with details + reproduction) are usually handled though obviously faster when a PR is posted vs an issue

I believe most react-native types are also nosql types so firestore receives more use and therefore is likely a bit more solid but you're not the only rtdb user, there others consuming the rtdb service through react-native-firebase as well

**Comment by mikehardy** [comment]
One thing that would be useful is to perhaps open single-item specific issues following the issue template so we are certain of all the versions etc, bonus points for making a demonstrator app that shows the problem and putting it up on github

**Comment by mikehardy** [comment]
Open a new issue with a reproduction (App.js or similar) following the template (with all requested information provided) and we can triage if needed
