### ISSUE TITLE
FireStore onSnapShot return document undefined whether  its exist  and [firestore/unavailable] the service is currently unavailable

### ISSUE THREAD

**Issue by osafahmad** [invertase/react-native-firebase#4039]
Hello there you awesome person;
Please note that the issue list of this repo is exclusively for bug reports;

OS  : mac catalina 
React Native : 0.61.5
Firestore version : 6.3.4

So the problem is . i am using firestore onsnapshot some time its return data undefined and services unavailable . but some time its return proper data.

**Comment by andersonaddo** [comment]
You completely ignored template; support unlikely
