### ISSUE TITLE
onRefreshToken in FCM work in background?

### ISSUE THREAD

**Issue by tastafur** [invertase/react-native-firebase#4041]
This question
onRefreshToken in FCM work in background?
is the FCM token update in background?

**Comment by mikehardy** [comment]
How did it work when you tried it?

**Comment by tastafur** [comment]
@mikehardy Well I have reproduced one of the cases for which it should refresh several times but it does not, then it must be that in the background the token does not refresh
https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceIdService#onTokenRefresh()

**Comment by mikehardy** [comment]
For Android we'll have to be specific about whether this is headless mode (launched this way if you have implemented headless cloud message handlers and you receive a cloud message) or just background (app is no longer foreground after the user has used it directly, but it has not been killed)

Can you provide the exact steps a user would take that would result in a token refresh happening, but the API not being called?

It may be that it's a documentation issue, where the API should be documented as not firing while in headless mode, and when the app boots into full UI mode or the background message handler is called, a fresh token should always be fetched ?
