### ISSUE TITLE
Displaying multiple when a notification arrives

### ISSUE THREAD

**Issue by mertbuldur** [invertase/react-native-firebase#4042]
Hello , Displaying multiple when a notification arrives on IOS. My code is 
`PushNotification.configure({
  // (optional) Called when Token is generated (iOS and Android)

  onRegister: function (token) {
    //console.log("TOKEN:", token);
  },

  // (required) Called when a remote or local notification is opened or received
  onNotification: function (notification) {

    // process the notification

    // required on iOS only (see fetchCompletionHandler docs: https://github.com/react-native-community/react-native-push-notification-ios)
    if (!notification.foreground) {
     //notification.finish(PushNotificationIOS.FetchResult.NoData);
    }
    notification.finish(PushNotificationIOS.FetchResult.NoData);
  },

  // ANDROID ONLY: GCM or FCM Sender ID (product_number) (optional - not required for local notifications, but is need to receive remote push notifications)
  senderID: "503601710565",

  // IOS ONLY (optional): default: all - Permissions to register.
  permissions: {
    alert: true,
    badge: true,
    sound: true
  },
  // Should the initial notification be popped automatically
  // default: true
  popInitialNotification: true,

  /**
   * (optional) default: true
   * - Specified if permissions (ios) and token (android and ios) will requested or not,
   * - if not, you must call PushNotificationsHandler.requestPermissions() later
   */
  requestPermissions: true
});
`

ComponentDidMount:
` messaging().onMessage(notification => {
  
      console.log('2');
      PushNotification.localNotification({
        title:notification.notification.title,
        message:notification.notification.body, // (required),
      });
      console.log('Notification received!', notification);
    });`

**Comment by andersonaddo** [comment]
Probably because your sending an FCM message that has the `notification` property (which automatically causes a push notification), and you're also making your own push notification from `onMessage`

**Comment by mertbuldur** [comment]
my send data is : 
` $fields = array(
            "registration_ids" => array_values($tokens),
            /*
            "notification" => array(
                "body" => $body,
                "title" => $title,
                "content_available"=>true,
                "tag"=> "GENERATED_UNIQUE_ID",
            ),
            */

            "apns"=> [ 'payload' => [ 'aps' =>[ "content-available"=> true,'contentAvailable'=>true ]] ],
            "content_available"=>true

        );

        if(count($params)!=0){
            $fields['data'] = $params;
        }`

**Comment by mertbuldur** [comment]
Solved this problem. sending more than once with foreach :)
