### ISSUE TITLE
[v6] Firebase Dynamic links  (iOS crash and Android buildShortLink not working)

### ISSUE THREAD

**Issue by patriciam97** [invertase/react-native-firebase#4045]
## Issue

Hey, so I had to add the @react-native-firebase/dynamic-links to my project but first had to migrate from v5 to v6. After doing that and testing that my app still works as before, I run npm i --save @react-native-firebase/dynamic-links.

After installing the library, the iOS app crashed. Everytime I run react-native run-ios the app installs correctly and then crashes in the splash screen. This gives me the idea that something is going wrong in the AppDelegate.m file but not sure what. Please note that after installing the library I followed the iOS setup instructions as mentioned here: https://rnfirebase.io/dynamic-links/usage#ios-setup.    Any clue?

The Android app worked fine so I proceeded with implementing my code. 

`await dynamicLinks()
      .buildShortLink({
        link: `XXXXXXXX `,
        domainUriPrefix: 'XXXXXXXX',
        ios: {
          bundleId: 'XXXXXXXX',
          appStoreId: 'XXXXXXXX',
        },
        android: {
          packageName: 'XXXXXXXX'
        }
      });`

The code used to work yesterday (03/08) but today it doesn't work (04/08).  **buildLink works but buildShortLink doesn't** it just never returns anything. I noticed that there was a last update yesterday(https://www.npmjs.com/package/@react-native-firebase/dynamic-links). Do you think that might have affected something?

## Project Files
 - iOS: Podfile: 

`platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'XXXXXXXX' do
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  target 'XXXXXXTests' do
    inherit! :search_paths
  end

  use_native_modules!
  end

  target 'XXXXXX-tvOS' do
  target 'XXXXX-tvOSTests' do
    inherit! :search_paths
  end

end
`

#### `package.json`:

```json
{
  "name": "XXXXXXX",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/netinfo": "^4.7.0",
    "@react-native-community/push-notification-ios": "^1.2.2",
    "@react-native-community/toolbar-android": "0.1.0-rc.2",
    "@react-native-firebase/analytics": "^7.3.1",
    "@react-native-firebase/app": "^8.2.0",
    "@react-native-firebase/auth": "^8.2.0",
    "@react-native-firebase/firestore": "^7.4.3",
    "@react-native-firebase/messaging": "^7.5.0",
    "@react-native-firebase/storage": "^7.2.2",
    "@react-native-firebase/dynamic-links": "^7.4.1",
    "emoji-utils": "^1.0.1",
    "instabug-reactnative": "^9.1.1",
    "lodash": "^4.17.15",
    "prop-types": "^15.7.2",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-document-picker": "^3.5.3",
    "react-native-dropdownalert": "^4.2.1",
    "react-native-elements": "^1.2.7",
    "react-native-form-validator": "^0.2.0",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-image-crop-picker": "^0.25.3",
    "react-native-image-picker": "^1.1.0",
    "react-native-material-dropdown": "git+https://github.com/harshitjee/react-native-material-dropdown.git",
    "react-native-modal": "^11.5.6",
    "react-native-push-notification": "^3.5.2",
    "react-native-reanimated": "^1.9.0",
    "react-native-responsive-screen": "^1.4.0",
    "react-native-screens": "^2.9.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-tab-view": "^2.14.4",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.13.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.10.16",
    "stream-chat-react-native": "^0.9.2"
  },
  "devDependencies": {
    "@babel/core": "7.5.5",
    "@babel/runtime": "7.5.5",
    "@react-native-community/eslint-config": "0.0.3",
    "babel-eslint": "^10.1.0",
    "babel-jest": "24.8.0",
    "eslint": "^6.1.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.3",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.54.1",
    "prettier": "^1.19.1",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Sorry this is happening - I will mention reporting a crash without a trace is not productive though, we need the crash trace

Note that for dynamic links you may be experiencing an issue that was solved with the release just yesterday (I think?) that bumped the upstream firebase-ios-sdk pods to 6.28.1

Android, unsure

**Comment by patriciam97** [comment]
Hey,

Thanks for your reply! Could you please tell me where I can find the crash trace?

**Comment by mikehardy** [comment]
@patriciam97 android use `adb logcat` from command line while running the app on a device plugged in, similarly for ios run it on device plugged in from an xcode build and the trace shows up in xcode

**Comment by mikehardy** [comment]
Or firebase crashlytics I suppose :-)

**Comment by patriciam97** [comment]
Hey! I read online that v6 is quite unstable so I migrated back to v5. Let me know what you think about this.

**Comment by mikehardy** [comment]
@patriciam97 honestly? I think it's ridiculous. I read "some people online said that an old unsupported version with bugs fixed in new versions is more stable". It just reads ridiculous to me.

To be clear: v5 will receive no support. v6 is working fine.

If you find a real issue, file a real bug, not an aspersion based on some online rumor.

**Comment by patriciam97** [comment]
I created an open issue after having problems with v6 not based on rumours. I will look into migrating to v6 when the time-schedule allows it. Thank you for your help.

**Comment by mikehardy** [comment]
Worth noting that apart from this module we obviously depend on a truly enormous pile of code that is the firebase-ios-sdk upstream and they have issues specifically with dynamic links right now, but the 6.28.1 SDK (or 6.29.0 - current as of a couple days ago at least) fixed most of them, with the remaining dynamic-link-related one being that on networks where IPv6 doesn't work at all there can be a multi-second hang on app init sometimes - https://github.com/firebase/firebase-ios-sdk/issues/5032

I'm not aware of any other dynamic links related issues

**Comment by patriciam97** [comment]
Oh I didn't know. I'll check it out! Thank you for the information 👍

**Comment by MaheshGawhane11** [comment]
@mikehardy I have attached the error screenshot. Please check
![IMG-0309](https://user-images.githubusercontent.com/16697851/138049342-46c97d9e-7908-455b-8714-448756d6d3b5.png)

**Comment by MaheshGawhane11** [comment]
@patriciam97 did you find any solution?
