### ISSUE TITLE
Firebase's auth currentUser's display name is null when you sign in with Apple

### ISSUE THREAD

**Issue by kdzapp** [invertase/react-native-firebase#4046]
## Issue

`auth().currentUser.displayName === null` when users login with apple. There's an issue for the firebase iOS SDK that I'm tracking here: https://github.com/firebase/firebase-ios-sdk/issues/4393. I was wondering if there's a work around from the RN side for the time being.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 48.80 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^4.9.0 => 4.10.1 
    react: ~16.9.0 => 16.9.0 
    react-native: ~0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-video: 5.0.2
```

- **Platform that you're experiencing the issue on**:
  - [X] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^8.0.6`
- **`Firebase` module(s) you're using that has the issue:**
  - `Auth Module`
- **Are you using `TypeScript`?**
  - `Y`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You'll have to refer to the apple API docs
They don't send the user name, it's just not available with apple signin

**Comment by kdzapp** [comment]
That's not true; you can request the name too. In fact for some reason this library allows you to include a perms request for the name but it's never returned.

**Comment by mikehardy** [comment]
@kdzapp Then please post a PR or at least open an issue with links to the relevant Apple API docs to https://github.com/invertase/react-native-apple-authentication/ using the available APIs, we'd love to support this but have not seen how.

**Comment by kdzapp** [comment]
No problem, I'll look into it

**Comment by AntonLukovtsev** [comment]
@kdzapp Hi! I have the same issue with apple sign in. Username and email absent in object. Do you know why this things absent?

**Comment by zchwyng** [comment]
I'm also having this problem. Anyone knows how to fix this?

**Comment by mikehardy** [comment]
@zchwyng it's not a "problem", it is how sign in with apple works. You don't get a display name, you need to consider the docs carefully, here is one from a related repo that has hopefully useful information that will allow you to resolve empty user name during testing plus some references to the project readme and explanations of why this happens https://github.com/invertase/react-native-apple-authentication/issues/11

**Comment by AlexRequelme** [comment]
It appears that the issue has been successfully resolved:

https://github.com/firebase/firebase-ios-sdk/issues/4393#issuecomment-1478733407

**Comment by mikehardy** [comment]
Apple users do not have to provide their name for privacy reasons. As I specifically mentioned in 2021 @longnguyen2508 👆 https://github.com/invertase/react-native-firebase/issues/4046#issuecomment-817307903

**Comment by zcmgyu** [comment]
@mikehardy I’m following up on my previous comment. [I noticed that firebase-ios-sdk now supports passing fullname as a parameter when creating a credential](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message)[1](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message). It would be awesome if react-native-firebase could also implement this feature.
[1](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message): https://github.com/firebase/firebase-ios-sdk/issues/4393#issuecomment-1478733407

**Comment by mikehardy** [comment]
Very interesting - I see it in firebase-ios-sdk 10.7.0 https://firebase.google.com/support/release-notes/ios#authentication_7

I wasn't reading that closely since this was a closed issue from 2020 and I expect enhancement requests typically to come in on a new issue. I'll do that now

**Comment by zcmgyu** [comment]
@mikehardy Sound great 😊

**Comment by sleekLancelot** [comment]
> It appears that the issue has been successfully resolved:
> 
> [firebase/firebase-ios-sdk#4393 (comment)](https://github.com/firebase/firebase-ios-sdk/issues/4393#issuecomment-1478733407)
> 
> I think that now, we can do something like this:
> 
> ```js
> const { identityToken, nonce, fullName } = appleAuthRequestResponse;
> const appleCredential = auth.AppleAuthProvider.credential(identityToken, nonce, fullName);
> ```

hmmm, seems like credential is expecting two arguments, "token" and "secret". No place for fullName here👇🏾.

`credential: (token: string | null, secret?: string) => AuthCredential;`

**Comment by EnginYilmaz** [comment]
I am not sure where have I read it but as I memorize from a thread apple only gives displayName on the first logging in after that null on other trying to get displayName

**Comment by kaleb-dev** [comment]
As stated by @mikehardy apple for privacy sake only allows name to be accessed on first sign in attempt so after receiving it with the following code below store in firestore or database of choice. Hope the solution below helps!

`async function onAppleButtonPress() {
  const appleAuthRequestResponse = await appleAuth.performRequest({
    requestedOperation: appleAuth.Operation.LOGIN,
    requestedScopes: [appleAuth.Scope.FULL_NAME, appleAuth.Scope.EMAIL],
  });
  if (!appleAuthRequestResponse.identityToken) {
    throw new Error('Apple Sign-In failed - no identify token returned');
  }

// Add full name property to response 
const { identityToken, nonce, fullName } = appleAuthRequestResponse;  
const appleCredential = auth.AppleAuthProvider.credential(identityToken, nonce);

// Call on fullName which is received in response 
const { givenName, familyName } = fullName;
const firstLastName = `${givenName} ${familyName}`;

  return auth().signInWithCredential(appleCredential);
}`

Response would look something like this

`{"familyName": "Doe", "givenName": "John", "middleName": null, "namePrefix": null, "nameSuffix": null, "nickname": null}`
