### ISSUE TITLE
🔥 Sending custom logs up to Crashlytics

### ISSUE THREAD

**Issue by iamjaytong** [invertase/react-native-firebase#4049]
## Issue

Trying to setup Android version of our React Native app to send [custom logs up to Firebase Crashlytics](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#add-logs). Tried to follow the [demo example](https://github.com/invertase/react-native-firebase/issues/3465) but ran into an issue with unexpected colon in `import com.crashlytics.sdk.android:crashlytics;`

1 error log while building
```
MainApplication.java:20: error: ';' expected 
import com.crashlytics.sdk.android:crashlytics;
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
    "@react-native-firebase/app": "6.7.1",
    "@react-native-firebase/crashlytics": "6.7.1",
    "react-native": "0.61.5",
  },
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "crashlytics_debug_enabled": true
  }
}

```

</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
buildscript {
    repositories {
        google()  // Moved above jcenter base on react-native-firebase docs
        jcenter()
        maven {
            // Add based on react-native-firebase crashlytics docs
            url 'https://maven.fabric.io/public'
        }
        
    }
    dependencies {
        classpath('com.android.tools.build:gradle:3.4.2')
        classpath 'com.google.gms:google-services:4.2.0' // react native firebase needs this
        classpath 'io.fabric.tools:gradle:1.28.1' // react native firebase crashlytics needs this
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
```

#### `android/app/build.gradle`:

```groovy
apply plugin: 'io.fabric'
...
dependencies {
    ... 
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.crashlytics.sdk.android:crashlytics' // Need for firebase crashlytics
}
...
```

#### `android/settings.gradle`:

```groovy
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
```

#### `MainApplication.java`:

```java
import com.crashlytics.sdk.android:crashlytics; // <-- Instead of this, what should I be importing here and referencing below?
...
public class MainApplication extends MultiDexApplication implements ReactApplication {
...
private void upgradeSecurityProvider() {
    ProviderInstaller.installIfNeededAsync(this, new ProviderInstallListener() {
      /**
      * This method is only called if the provider is successfully updated
      * (or is already up-to-date).
      */
      @Override
      public void onProviderInstalled() {
        crashlytics.getInstance().log("User successfully updated security provider.");
      }

      @Override
      public void onProviderInstallFailed(int errorCode, Intent recoveryIntent) {
        GoogleApiAvailability.getInstance().showErrorNotification(MainApplication.this, errorCode);
        crashlytics.getInstance().log("User failed to update security provider. Was shown Google Play services update notification.");
      }
    });
}
...
}
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 54.41 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.11.0 - ~/.nvm/versions/node/v13.11.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v13.11.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.7.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. FirebaseCrashlytics`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
That link was for react-native-firebase v5. 

Don't do anything like that, here's a script that generates a complete example (including crashlytics), read through and it shows you the only necessary things https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

**Comment by iamjaytong** [comment]
@mikehardy thanks for the quick response! 

Now that I'm re-reading my original issue description, I don't think I was clear on what the issue is. Everything is working in React Native and we've been using it in production for some time now. Now we want to directly log things in Java on the native side, how should we go about doing that? Does it require a separate install of Crashlytics?

**Comment by mikehardy** [comment]
Ah, the jargon for that is "brownfield app", as in you have a brownfield application where you want to access the firebase-android-sdk APIs from upstream or react-native-firebase directly, in the same app you use react-native-firebase via javascript

I do this for firestore. It looks a little like this for the init in my Java object, with usage then following the upstream docs:

```java

    private String mInstanceId;
    private FirebaseFirestore mFirestore;

    public GeneralReceiver() {
        super();
        if (mInstanceId == null) {
            mInstanceId = FirebaseInstanceId.getInstance().getId();
        }
        if (mFirestore == null) {
            mFirestore = FirebaseFirestore.getInstance();
        }
        Log.i(TAG, "GeneralReceiver() initialized - using instance id: " + mInstanceId);
        syncDeviceInfo(MainApplication.getContext(), null);
    }
```

I don't see why any of the modules would be different. Grab direct handles to them (they should already be initialized, by react-native-firebase) and use them, just as react-native-firebase does in it's native code.
