### ISSUE TITLE
iOS 14 onload app message popup "MyAPP pasted from {other installed app}"

### ISSUE THREAD

**Issue by aqib1604** [invertase/react-native-firebase#4050]
Getting Please provide all the information requested. Issues that do not follow this format are likely to stall.

**Description**
With iOS 14 new release, the device is detecting that my app is accessing clipboard and copying data from other apps, however, my app not even using Clipboard.

**React Native version:**
Run react-native info in your terminal and copy the results here.
System:
OS: macOS 10.15.8
Binaries:
Node: 14.5.0 
npm: 6.14.5
Watchman: 4.9.0 
SDKs:
iOS SDK:
Platforms: iOS 14.0, macOS 10.15

**npmPackages:**
react: 16.9.0 => 16.9.0
react-native: 0.61.5 => 0.61.5
react-native-firebase: 5.6.0

**Steps To Reproduce**
Provide a detailed list of steps that reproduce the issue.

**Set up a new project** 
Copy any text from another app
Open the react native app (iOS 14)
then the "MyAPP pasted from {other installed app}" as in the screenshot

[https://drive.google.com/file/d/1Vqg7Rxg_3TbCfjy7VAaoDG4mDbyOkitW](https://drive.google.com/file/d/1Vqg7Rxg_3TbCfjy7VAaoDG4mDbyOkitW)

**Comment by mikehardy** [comment]
This is an upstream issue with dynamic links

There is nothing we can do in this module to alter the behavior

You may follow along here to learn more about the issue and any related workarounds or mitigations or releases associated: https://github.com/firebase/firebase-ios-sdk/issues/5893
