### ISSUE TITLE
incorrect date-time on android

### ISSUE THREAD

**Issue by AidanHost** [invertase/react-native-firebase#4053]
Hi guys,

sorry, not really setup to create a pull request here, but there is a bug in the SharedUtils.java file

`timestamp` is seconds since Epoch https://firebase.google.com/docs/reference/android/com/google/firebase/auth/GetTokenResult#getExpirationTimestamp()

https://github.com/invertase/react-native-firebase/blob/3582e4865f5da49ba8b70b8681a03b7ba372aa51/packages/app/android/src/reactnative/java/io/invertase/firebase/common/SharedUtils.java#L101

the `calendar.getTimeZone().getOffset(timestamp)` call returns milliseconds, so it should be excluded from the `* 1000` calculation

Java docs: https://docs.oracle.com/javase/7/docs/api/java/util/TimeZone.html#getOffset(long)

**Comment by mikehardy** [comment]
Fantastic bug report. I went :cowboy_hat_face: and just created a PR based directly on this report, using the web UI :crossed_fingers:

**Comment by mikehardy** [comment]
should be in the next release and...I'm not 100% but I think it might be set up for semver and auto-launch so, be on the lookout
