### ISSUE TITLE
Android - after adding firebase - could not find tools.jar

### ISSUE THREAD

**Issue by msmfsd** [invertase/react-native-firebase#4056]
My react native android was compiling fine until I added react-native-firebase as per the docs (ios compiles fine).

- React Native `0.63.2` and react-native-firebase `8.3.0` latest versions and followed docs very carefully.
- OSX 10.15.6
- Deleted/cleared/reinstalled gradle and android gradle/build dirs etc.
- java JRE v8.202 `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin`
- java JRE v8.202 `/Library/Java/JavaVirtualMachines`
- Note that JAVA_HOME path set to `/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home`

Error:
```
> Task :react-native-firebase_app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-firebase_app:compileDebugJavaWithJavac'.
> Could not find tools.jar. Please check that /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home contains a valid JDK installation.
```

**Comment by msmfsd** [comment]
SO: `https://stackoverflow.com/questions/63278221/react-native-android-wont-compile-after-adding-react-native-firebase`

**Comment by msmfsd** [comment]
Ran `source ~/.bash_profile ` to ensure JAVA_HOME path set to `/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home` and it compiled, yay.

**Comment by mikehardy** [comment]
@msmfsd you may like this demo construction script, as there may be other steps missing, I think these highlighted lines are a similar workaround: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh#L159-L161

good luck with your project!

**Comment by msmfsd** [comment]
> @msmfsd you may like this demo construction script, as there may be other steps missing, I think these highlighted lines are a similar workaround: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh#L159-L161
> 
> good luck with your project!

Thanks for the tip @mikehardy Im actually a bit of noob w react-native but I'll have a look at your demo for some ideas for my firebase integration, thanks
