### ISSUE TITLE
App crashes after receiving push

### ISSUE THREAD

**Issue by kingzeng** [invertase/react-native-firebase#4059]
Fatal Exception: RCTFatalException: Unhandled JS Exception: (0,s.getNativeModule)(u).complete is not a function. (In '(0,s.getNativeModule)(u).complete(n,t)', '(0,s.getNativeModule)(u).complete' is undefined)
![屏幕快照 2020-08-07 上午11 41 38](https://user-images.githubusercontent.com/15261181/89631303-32311d00-d8d3-11ea-84cf-d0ed4832ab0f.png)

react-native-firebase": "5.5.7

**Comment by kingzeng** [comment]
react-native-firebase": "5.5.7

**Comment by mikehardy** [comment]
I was testing pushes to both platforms all days yesterday on current stable (not unsupported v5) and they all worked (ios silent push even once I addled content available!) . Recommend upgrading to current stable for support

**Comment by russellwheatley** [comment]
Thanks for the issue report, @ashishkumar1000, we’re no longer actively supporting <= v5 development so I’m going to go ahead and close this issue - but feel free to continue the discussion. If you have any issues regarding React Native Firebase >= v6, please raise a new issue.
