### ISSUE TITLE
Firebase module breaks some import features from Webstorm

### ISSUE THREAD

**Issue by SolutiLyon** [invertase/react-native-firebase#407]
### Issue
Because of :

```
declare module 'react-native' {
  // noinspection ES6ConvertVarToLetConst
  declare var exports: any;
}
```

It makes a conflict into Webstorm with react native imports then it can't know where to find 'react-native' components. That break the auto import & optimization of imports features.

[Screenshot](https://img11.hostingpics.net/pics/211299Capturede769cran20170913a768175343.png)

### Environment

1. Application Target Platform: 
All

2. Development Operating System: 
Mac

3. Build Tools: 
Latest Webstorm version (+ xcode + AndroidStudio)

4. React Native version: 
`>= 0.46.4`

5. RNFirebase Version: 
Latest stable on npm

6. Firebase Module: 
Messaging

**Comment by Salakar** [comment]
This is correct as is though, webstorm user myself and as far as I remember when I first started this project webstorm would grind to a halt trying to resolve react and all it's dependencies . This also fixed a flow issue I think.

If you could confirm the above 2 things are no longer an issue then I'd be happy to change this.

The module inspection does cause far more issues than it's worth though in my opinion, especially with react/webpack and all the module aliases that it can't resolve, I have mine turned off.

**Comment by Salakar** [comment]
Have just tested both myself and it's all working - so i'll remove it for the next alpha release.

**Comment by damienix** [comment]
I'm also affected. Removed flow.js file with this 'react-native' declaration which seems to solve the problem 👍

**Comment by Salakar** [comment]
@damienix it has been fixed in v3, beta landing tomorrow.

**Comment by damienix** [comment]
Great, thanks!
