### ISSUE TITLE
apple rejection on kids app: Messaging and DynamicLinks have a dependency of Firebase/Analytics

### ISSUE THREAD

**Issue by pabloearg** [invertase/react-native-firebase#4072]
## Issue

we just update to the latest version of:

```
    "@react-native-firebase/dynamic-links": "7.5.0",
    "@react-native-firebase/messaging": "7.5.0",
```

but Apple has a new rule for kids:  https://developer.apple.com/app-store/review/guidelines/#kids-category
in which you can't have any dependency to analytics, so, is really necessary to have this dependencies ?

```
  # Firebase dependencies
 _s.dependency          'Firebase/Analytics', firebase_sdk_version_ (remove this line)
  s.dependency          'Firebase/Messaging', firebase_sdk_version
```
```

  # Firebase dependencies
  s.dependency          'Firebase/Analytics', firebase_sdk_version (remove this line)
  s.dependency          'Firebase/DynamicLinks', firebase_sdk_version
```

 can i remove this lines from the podspecs?

or do you have any solution to this?

maybe this issues are related: 
https://github.com/firebase/firebase-ios-sdk/issues/1686
https://github.com/firebase/firebase-ios-sdk/issues/5153
https://github.com/firebase/firebase-ios-sdk/issues/5928

**Comment by mikehardy** [comment]
@pabloearg honestly, I'm not sure? I recommend using https://github.com/ds300/patch-package in conjunction with altering the .podspec files to remove those lines and seeing how it works

You linked what appear to me (as I read them) to be all the relvant issues, especially 5153, which indicates that it's an area of recently active development, so it might be that we are just not "caught up" here and in your testing it works (with patch-package keeping it working) and we'd take a PR here

**Comment by pabloearg** [comment]
@mikehardy  reading this issues specifically [ this comment ](https://github.com/firebase/firebase-ios-sdk/issues/5153#issuecomment-655228840 ) is says they release a new version with this, and following their releases, they  fix this in the 6.27.1 but in the latest version of the plugin you have this:

>  - RNFBDynamicLinks (7.5.0):
>     - Firebase/Analytics (~> 6.27.0)
>     - Firebase/DynamicLinks (~> 6.27.0)
>     - React
>     - RNFBApp
>   - RNFBMessaging (7.5.0):
>     - Firebase/Analytics (~> 6.27.0)
>     - Firebase/Messaging (~> 6.27.0)
>     - React
>     - RNFBApp

**Comment by mikehardy** [comment]
@pabloearg easily overridden:

https://rnfirebase.io/#ios

example https://github.com/mikehardy/rnfbdemo/blob/eda24a71990e95e8a91b17b27b0cc1417031808b/make-demo.sh#L32

**Comment by andersonaddo** [comment]
I think you're outdated?
We're using ios sdk 6.28.1
https://github.com/invertase/react-native-firebase/pull/3956

**Comment by mikehardy** [comment]
@pabloearg did you attempt the build without analytics in the podspecs? I'm curious how it went

**Comment by pabloearg** [comment]
> @pabloearg did you attempt the build without analytics in the podspecs? I'm curious how it went

yes, but only with messages (y removed the @react-native-firebase/dynamic-links package), the archive went good, and we received the push notifications, but apple continues to reject our app (without telling us which package is doing that)

**Comment by mikehardy** [comment]
I'm really sorry to hear that, but thank you for reporting in. This is obviously an area of current concern, I'll be listening for any future info but I thought that would be it so I'm stumped at the moment

**Comment by Salakar** [comment]
Check the Podfile.lock file, it has a dependency graph, should show whats pulling in analytics

**Comment by pabloearg** [comment]
> I'm really sorry to hear that, but thank you for reporting in. This is obviously an area of current concern, I'll be listening for any future info but I thought that would be it so I'm stumped at the moment

@mikehardy  after removing analytics from podspec and removing another package (branch.io) apple approve our new version.

for you to take it into account: we also removed the analytics dependency from @react-native-firebase/dynamic-links, and worked perfectly. (now we are sending a new version with dynamic-links to check if its work also)

could you also remove that dependency? so we dont need to fork or hardcode you podspecs

**Comment by mikehardy** [comment]
Excellent news! We can do anything that we need to do in order to make sure it's possible to approve things, I'm just waiting on reports of "what functionality is working" vs "what changes were made" vs "apple approved or not", which you are providing (thank you!), so I'll wait a bit longer to now to hear how dynamic-links works but https://github.com/ds300/patch-package is the way to do it so you don't have to fork or worry about hard-coding (it's very surgical!) and we'll get the needed changes in once we know what works

**Comment by Salakar** [comment]
The main reason its included in links podspec is because that's what the iOS Firebase docs suggest: https://firebase.google.com/docs/dynamic-links/ios/create#set-up-firebase-and-the-dynamic-links-sdk

It doesn't indicate though if its actually required, it may just be that its there for analytics related to links/sharing links etc

**Comment by mikehardy** [comment]
Appears to be useful but not required https://firebase.google.com/docs/dynamic-links/analytics

I'm guessing this is just a lag between the (frankly, quite large) amount of Pod / package reorganization done to have Analytics be optional and what current requirements and recommendations are documented.

Sounds like RNFBDynamicLinks.podspec could have it removed, and rnfirebase.io page for Dynamic Links could get a pointer to the page I link here with a note that Analytics is optional but works together with Dynamic Links to provide more information if desired.

I believe the exact same applies to Messaging (remove from podspec, indicate Analytics is optional but can work together with Messaging to provide more messaging-related information - https://firebase.google.com/docs/analytics#integrations_with_other_services )

**Comment by Salakar** [comment]
I think a PR to do that is in order then 🤔 

@pabloearg are you able to send a PR for this?

**Comment by mikehardy** [comment]
For anyone reading this later: firebase/crashlytics@8.3.4 or greater will be required if you want to use crashlytics and still put your app in the kids category, I think it's the last change required.

**Comment by mikehardy** [comment]
This may be of interest to people. firebase-ios-sdk 7.8.0 has apparently made enough changes that Analytics is possible from within an iOS-acceptable kids app? https://github.com/firebase/firebase-ios-sdk/issues/7652
