### ISSUE TITLE
🔥 Firestore Unavailable Error

### ISSUE THREAD

**Issue by tomhicks** [invertase/react-native-firebase#4074]
## Issue

Describe your issue here

On a fresh install, both iOS and Android, two different developers are both getting:
```
Error: [firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
```
when trying to do anything with Firestore. We are able to call functions, analytics, etc. all fine.

This also happens when trying to connect to the emulator using

```javascript
firestore().settings({host: 'localhost:8080'})
```

I've not really been able to verify whether or not that is even trying to connect to the emulator, because it errors either way.

I doubt very much that RNFirebase specifically is responsible. My bet is either:
- firebase being blocked by "the Internet" (I know that happens in some worldly locations). Would be weird though because the emulator firestore also doesn't work, apparently. Also, I have another firebase project using 5.x which works absolutely fine to connect to its firestore 🤷‍♀️
- some gRPC or similar dependency. Would be weird because it's affecting Android and iOS the same.

Here's all my RPC info from podfile.lock anyway, in case it is gRPC related:
```
  - BoringSSL-GRPC (0.0.7):
    - BoringSSL-GRPC/Implementation (= 0.0.7)
    - BoringSSL-GRPC/Interface (= 0.0.7)
  - BoringSSL-GRPC/Implementation (0.0.7):
    - BoringSSL-GRPC/Interface (= 0.0.7)
  - BoringSSL-GRPC/Interface (0.0.7)
    - "gRPC-C++ (~> 1.28.0)"
  - "gRPC-C++ (1.28.2)":
    - "gRPC-C++/Implementation (= 1.28.2)"
    - "gRPC-C++/Interface (= 1.28.2)"
  - "gRPC-C++/Implementation (1.28.2)":
    - "gRPC-C++/Interface (= 1.28.2)"
    - gRPC-Core (= 1.28.2)
  - "gRPC-C++/Interface (1.28.2)"
  - gRPC-Core (1.28.2):
    - gRPC-Core/Implementation (= 1.28.2)
    - gRPC-Core/Interface (= 1.28.2)
  - gRPC-Core/Implementation (1.28.2):
    - BoringSSL-GRPC (= 0.0.7)
    - gRPC-Core/Interface (= 1.28.2)
  - gRPC-Core/Interface (1.28.2)
    - BoringSSL-GRPC
    - "gRPC-C++"
    - gRPC-Core
  BoringSSL-GRPC: 8edf627ee524575e2f8d19d56f068b448eea3879
  "gRPC-C++": 13d8ccef97d5c3c441b7e3c529ef28ebee86fad2
  gRPC-Core: 4afa11bfbedf7cdecd04de535a9e046893404ed5
```

---

### Javascript

<details><summary>Click To Expand</summary>

```javascript
firebase
      .firestore()
      .collection('games')
      .doc(gameId)
      .get()
      .then((r) => r.data())
      .then(console.log)
      .catch(console.warn) // <-- this gives the error mentioned above
```

#### `package.json`:

```json
{
  "name": "swiz-mobile-app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios --simulator='(5.5) iPhone 8 Plus'",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "@expo-google-fonts/dev": "^0.1.0",
    "@react-native-firebase/analytics": "^7.4.1",
    "@react-native-firebase/app": "^8.3.0",
    "@react-native-firebase/auth": "^8.3.1",
    "@react-native-firebase/firestore": "^7.5.1",
    "@react-native-firebase/functions": "^7.3.1",
    "expo-font": "^8.2.2",
    "react": "16.13.1",
    "react-native": "0.63.0",
    "react-native-fast-image": "^8.3.2",
    "react-native-unimodules": "^0.10.1",
    "styled-components": "^5.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "@testing-library/jest-native": "^3.3.0",
    "@testing-library/react-native": "^7.0.1",
    "@types/jest": "^25.2.3",
    "@types/react-native": "^0.63.1",
    "@types/react-test-renderer": "^16.9.2",
    "@typescript-eslint/eslint-plugin": "^2.27.0",
    "@typescript-eslint/parser": "^2.27.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "prettier": "^2.0.5",
    "react-test-renderer": "16.13.1",
    "typescript": "^3.8.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
  },
  "emulators": {
    "functions": {
      "port": 5001
    },
    "firestore": {
      "port": 8080
    }
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# Override Firebase SDK Version
$FirebaseSDKVersion = '6.30.0' # Me trying to fix this issue to see if it's a dependency issue

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'swiz' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

```

#### `AppDelegate.m`:

Vanilla RN +
```objc
- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

  [FIRApp configure];
  
```

</p>
</details>

---

### Android

N/A - let's just stick to iOS for now!

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 127.14 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.18.1 - ~/.nvm/versions/node/v10.18.1/bin/node
    Yarn: Not Found
    npm: 6.13.4 - ~/.nvm/versions/node/v10.18.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 23.0.1, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `?? seems to be a mixture of 7 and 8 according to package.json @react-native-firebase/* entries`
- **`Firebase` module(s) you're using that has the issue:**
  - `Firestore`
- **Are you using `TypeScript`?**
  - `Y` & `3.9`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by lmcmz** [comment]
Same here

**Comment by mikehardy** [comment]
I think this is probably network related. I would actually lean towards Android as it's easy even if app is launched from the command line to use `adb logcat` directly (or via Android Studio) to attach to an emulator and watch the log - my hunch is that you find the firestore IPs aren't resolving or similar and it shows up in the logs - I just saw this last night with our E2E tests when they were expecting the 'firebase emulator' to be up and the android emulator couldn't communicate with them - `adb logcat` showed the issue.

Without a reproduction scenario I'm going to close this as unactoinable, but if there's something going on in the module and there's a reproduction demonstrating it, we can obviously reopen it

**Comment by tomhicks** [comment]
Thanks for the reply Mike. We’ve worked around it for now!!

**Comment by cvharris** [comment]
Seeing this as well. It seems like at some point the firestore results are cached from localhost and then it complains that the service is unavailable with any new, non-cached call. I can't seem to work around it though, @tomhicks what did you folks do?
