### ISSUE TITLE
Could not see crashlytic report on iOS app

### ISSUE THREAD

**Issue by dungle-groove** [invertase/react-native-firebase#4077]
## Issue

Describe your issue here

I was trying to integrate the Firebase Crashlytic into my app. When I triggered a force crashed by using **crashlytics().crash()**, it worked fine on Android app but stuck on iOS app. My report was still blocking add **Add the SDK, then build, run, and crash your app**
![image](https://user-images.githubusercontent.com/63702692/90089538-d5f35080-dd4b-11ea-9790-7faa1a0da172.png)

I have already tested with simulator and real devices on both Debug mode and release ah-hoc mode. I also enabled debug flag in **firebase.json** and set **-FIRDebugEnabled** & **-FIRAnalyticsDebugEnabled** in XCode however it did not help too much.

Could you please help me to identify the issue ?

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```
  "@react-native-firebase/analytics": "7.1.7",
  "@react-native-firebase/app": "8.0.0",
  "@react-native-firebase/crashlytics": "8.0.0",
```

#### `firebase.json` for react-native-firebase v6:

```
  "react-native": {
    "crashlytics_disable_auto_disabler": true,
    "crashlytics_debug_enabled": true,
    "crashlytics_auto_collection_enabled": true,
    "analytics_auto_collection_enabled": true
  }
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'MyApp' do
  pod 'GoogleIDFASupport', '~> 3.14.0'
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_native_modules!

end

```

#### `AppDelegate.m`:

```objc
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // config firebase sdk
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }

  [[FBSDKApplicationDelegate sharedInstance]
   application:application
   didFinishLaunchingWithOptions:launchOptions
   ];
 ...
}
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3330S CPU @ 2.70GHz
    Memory: 31.52 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 22, 23, 25, 26, 27, 28, 29
      Build Tools: 22.0.1, 23.0.1, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 30.0.1
      System Images: android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `react-native-firebase/analytics: 7.1.7`
  - `react-native-firebase/app: 8.0.0`
  -  `react-native-firebase/crashlytics: 8.0.0`,
- **`Firebase` module(s) you're using that has the issue:**
  - `Analytics`
  - `Crashlytics`
  - `App`
- **Are you using `TypeScript`?**
  - `No`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I looked at this but it appears you've covered the main things (analytics enabled, ios auto collection enabled per other issues in the repo - it's a current problem, up to date etc). Are you sure the dSYMs are uploaded? you restarted the app after etc? I'm guessing yes, but have to ask

**Comment by dungle-groove** [comment]
Thank Mike,

After asking the Google for supporting few day ago, it seems to work now. I think the problem may come from Firebase :)

Closing as resolved.

**Comment by girish54321** [comment]
@dungle-groove Hey how you solved this im all so facing same problem i have crashed the app in iPhone 2 days ago but its now showing in console just loading spinners..

I followed the docs pod install for IOS and noting more Additional Setups.. 

im doing it right.

**Comment by mikehardy** [comment]
@girish54321 this is covered most thoroughly on this issue, where we believe it is resolved - pending some docs updates and perhaps a change of the defaults - but should be working as per this comment https://github.com/invertase/react-native-firebase/issues/3879#issuecomment-678389795

**Comment by girish54321** [comment]
Update 
This is started working after 3 days don't know how it is working now changed nothing in code or in firebase console 

So just wait and relax 😄

**Comment by McDreamy** [comment]
Hi, I having the same issue, stuck at **Add the SDK, then build, run, and crash your app**

I'm using @react-native-firebase/crashlytics 8.3.2

and I have the following in the firebase.json
{
  "react-native": {
    "crashlytics_ndk_enabled": true,
    "crashlytics_debug_enabled": true,
    "crashlytics_auto_collection_enabled": true,
    "crashlytics_disable_auto_disabler": true,
    "analytics_auto_collection_enabled": true
   
  }
}

**Comment by mikehardy** [comment]
RNFB crashlytics 8.4.11 was just released that should work more reliably for *test* crash purposes. It was always working for real crashes but the test crashes weren't working well before, especially in debug. Cheers
