### ISSUE TITLE
How to properly mock v6 in Jest?

### ISSUE THREAD

**Issue by ospfranco** [invertase/react-native-firebase#4081]
## Documentation Feedback

Hey, I'm updating firebase v5 to firebase v6 in our codebase, main integration is done and now I'm trying to get our test suites to pass, I have managed to mock the firebases modules the following way:

```javascript
jest.mock('@react-native-firebase/messaging', () => {
  return () => ({
    hasPermission: jest.fn(() => Promise.resolve(true)),
    subscribeToTopic: jest.fn(),
    unsubscribeFromTopic: jest.fn(),
    requestPermission: jest.fn(() => Promise.resolve(true)),
    getToken: jest.fn(() => Promise.resolve('myMockToken')),
    onMessage: jest.fn(),
    onNotificationOpenedApp: jest.fn(),
    getInitialNotification: jest.fn(() => Promise.resolve(false))
  })
})

jest.mock('@react-native-firebase/crashlytics', () => ({}))

jest.mock('@react-native-firebase/app', () => {
  return () => ({
    onNotification: jest.fn(),
    onNotificationDisplayed: jest.fn()
  })
})

jest.mock('react-native/Libraries/EventEmitter/NativeEventEmitter')
// jest.mock('@react-native-firebase/app/lib/internal/RNFBNativeEventEmitter')
```

You can see I have had to mock the RN NativeEventEmitter, which I'm not sure if it's the best choice, in any case, that gets **almost** all of our test suites to green, however there is one test that fails:

```
$ jest --forceExit src/Sagas/InAppServicesSaga.test.js
 FAIL  src/Sagas/InAppServicesSaga.test.js
  ● Test suite failed to run

    TypeError: Super expression must either be null or a function

      at _inherits (node_modules/@babel/runtime/helpers/inherits.js:5:11)
      at node_modules/@react-native-firebase/app/lib/internal/RNFBNativeEventEmitter.js:29:26
      at Object.<anonymous> (node_modules/@react-native-firebase/app/lib/internal/RNFBNativeEventEmitter.js:71:2)
      at Object.<anonymous> (node_modules/@react-native-firebase/app/lib/internal/registry/nativeModule.js:21:1)
```

I have also tried to mock the `RNFBNativeEventEmitter` object, but that doesn't seem to be working, is there recommended way to mock the package? or anything I might be doing wrong?

**Comment by ospfranco** [comment]
Turns out, our test was submocking react-native which overrides the original mocking code, but maybe this ticket will provide information for other people

**Comment by sidVaidya** [comment]
@ospfranco hey how did you solve this issue. I am getting the same error as you.

**Comment by mikehardy** [comment]
Sounds like you may be re-mocking the mock in some other location, but in case it is useful you can look at our actual mock used for our testing:
https://github.com/invertase/react-native-firebase/blob/master/jest.setup.ts

**Comment by AravindExperion** [comment]
getting the same error
Test suite failed to run

    TypeError: Super expression must either be null or a function

      at _inherits (node_modules/@babel/runtime/helpers/inherits.js:5:11)
      at node_modules/@react-native-firebase/app/lib/internal/RNFBNativeEventEmitter.js:29:26
      at Object.<anonymous> (node_modules/@react-native-firebase/app/lib/internal/RNFBNativeEventEmitter.js:71:2)
      at Object.<anonymous> (node_modules/@react-native-firebase/app/lib/internal/registry/nativeModule.js:21:1)
how to resolve this?
