### ISSUE TITLE
Does onTokenRefresh gets called when the server invalidates the token?

### ISSUE THREAD

**Issue by emmanuelfrancis** [invertase/react-native-firebase#4086]
onTokenRefresh documentation mentioned that "_Called when a new registration token is generated for the device. For example, this event can happen when a token expires or when the server invalidates the token.
This subscriber method is only called when the app is active (in the foreground)._"

As its mentioned that onTokenRefresh subscriber method is only called when the app is active. I wanted to know what will happen if server invalidates the token when the app is in background or in quit state? In that case onTokenRefresh won't be called and push notification will stopped as the old token will be invalid.

Could you please clarify this case?

**Comment by mikehardy** [comment]
Need someone with more experience to weigh in on this one, if you have a moment @Salakar or @Ehesp  :pray:
