### ISSUE TITLE
Update usage docs with iOS image information

### ISSUE THREAD

**Issue by mikehardy** [invertase/react-native-firebase#4089]
Code LGTM. Re the docs, could maybe briefly mention it on this page: https://rnfirebase.io/messaging/server-integration#send-messages-to-topics - happy for this to be in a follow up PR if you want to ship this for now.

_Originally posted by @Salakar in https://github.com/invertase/react-native-firebase/pull/4085#issuecomment-674034120_

**Comment by mikehardy** [comment]
@davidepalazzo - I peeled off the docs suggestion so the functionality isn't blocked

**Comment by davidepalazzo** [comment]
Great, thanks for that @mikehardy. I just pushed the changes to the doc.
