### ISSUE TITLE
The description InterstitialAd provokes a violation of admob rules

### ISSUE THREAD

**Issue by KVinS** [invertase/react-native-firebase#4099]
## Documentation Feedback

Hello!
Your [example of using inter-screen advertising](https://rnfirebase.io/reference/admob/interstitialad) provokes violation of [admob rules](https://support.google.com/admob/answer/6201362?hl=en).
```
import { AdEventType } from '@react-native-firebase/admob';

interstitial.onAdEvent((type) => {
  if (type === AdEventType.LOADED) {
    interstitial.show();
  }
});

interstitial.load();
```
This is "Disallowed example: Interstitial launches after page load" in its pure form.
![91E0E29ADFA1A1BF42097E0699CC491BE874](https://user-images.githubusercontent.com/3009807/90342210-074f7300-e00f-11ea-9f16-a0516f86debc.jpg)

Or at least put a warning against showing ads immediately after loading.
You'd better duplicate this [example with tracking the load event](https://rnfirebase.io/admob/displaying-ads).

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
@KVinS very interesting! The reference docs are built from the typings, but they are easily editable if you could propose a PR that would eliminate this risk for people? 

I believe the relevant chunk starts right here and you just need to hit the "pencil" (edit) icon at top right to start https://github.com/invertase/react-native-firebase/blob/master/packages/admob/lib/index.d.ts#L932
