### ISSUE TITLE
Comparison to react-native-firestack

### ISSUE THREAD

**Issue by patrickdevivo** [invertase/react-native-firebase#41]
Does anyone have a comparison of this package to `react-native-firestack` https://github.com/fullstackreact/react-native-firestack ?

**Comment by DavidKuennen** [comment]
I'm actually coming from react-native-firestack, and switched after discovering some error when using child_added combined with child_removed/child_changed that, judging by the activity of that project, won't be fixed and time soon if ever. 

I like projects that are active/alive.

**Comment by patrickdevivo** [comment]
@DavidKuennen thanks for the info, I had a similar feeling / hunch and actually just ported a major project I'm building from `react-native-firestack` to `react-native-firebase` last night. Here's to this project staying maintained!

**Comment by Ehesp** [comment]
Well a few of us are using it in production apps so we'll need to keep it
maintained :)

**Comment by DavidKuennen** [comment]
That's reassuring to read. 👍

**Comment by joegoodall1** [comment]
How did people find the transition from react-native-firestack to react-native-firebase? We're looking to change to react-native-firebase and hoping the transition won't be too painful.

**Comment by Ehesp** [comment]
@joegoodall1 depends what you've got going really. Firestack has it's own method names and implementation, whereas we try our best to mimic the web SDK. In general, you should just be able to flip the names.

**Comment by Salakar** [comment]
Generally your transition guide is to switch over your code to match the firebase Web SDK as @Ehesp said. You'll find anything that differs will be documented over at http://invertase.io/react-native-firebase/#/

RNFirebase also has a lot of additional functionality - it has transactions, full messaging implementation, analytics and so on

**Comment by joegoodall1** [comment]
Thanks @Salakar and @Ehesp for the fast response.

Trying just to flip the names but when building get this error 
<img width="255" alt="screen shot 2017-05-09 at 14 49 03" src="https://cloud.githubusercontent.com/assets/8888799/25854085/c62dda8e-34c6-11e7-9631-b340de7d43e3.png">

**Comment by joegoodall1** [comment]
Thanks @Ehesp and @Salakar for the fast response.

**Comment by joegoodall1** [comment]
Any idea how to get around this?

<img width="779" alt="screen shot 2017-05-09 at 15 28 04" src="https://cloud.githubusercontent.com/assets/8888799/25855849/39b6a3f0-34cc-11e7-80a8-bd2298f44ad5.png">
