### ISSUE TITLE
Database reference update error

### ISSUE THREAD

**Issue by lucianomlima** [invertase/react-native-firebase#410]
### Issue

```
// path: /user/[user_key]
// data: Object
async function firebaseUpdate(path, data) {
    const update = {
        [path]: data
    };

    return await firebaseApp.database().ref().update(update);
    // returns same error if change to
    // return await firebaseApp.database().ref(path).update(data);
}

// In another file
// userData.user is data from firebase
firebaseUpdate(`users/${userData.user.key}`, userData.user).then(() => {
    this.props.saveUser(userData, this.props.userConfig);
    this._pager.setPage(page);
    this.setState({ isLoading: false });
}).catch(error => {
    // Always catched
    console.log('Firebase Database update error:', error);
    Alert.alert('', 'Error while trying to update your data.');
    this.setState({ isLoading: false });
});
```
This codes works time ago. But now only return error below
```
Error
    at index.js:332 -> react-native-firebase/lib/utils/index.js line 332
    at JSTimers.js:100
    at Object.callTimer (JSTimersExecution.js:95)
    at Object.callImmediatesPass (JSTimersExecution.js:199)
    at Object.callImmediates (JSTimersExecution.js:214)
    at MessageQueue.js:214
    at guard (MessageQueue.js:46)
    at MessageQueue.__callImmediates (MessageQueue.js:214)
    at MessageQueue.js:128
    at guard (MessageQueue.js:46)
```
### Environment

1. Application Target Platform: Android Lollypop

2. Development Operating System: macOS Sierra

3. Build Tools: Android SDK api 25

4. React Native version: 0.41.2

5. RNFirebase Version: 2.2.0

6. Firebase Module: Database

**Comment by chrisbianca** [comment]
@lucianomlima Is there a corresponding error in the native logs?

**Comment by chrisbianca** [comment]
@lucianomlima The issue is that you're returning the await, rather than the promise.  Your first method `firebaseUpdate` does not need to be async, and can just return the update, as follows:

```
function firebaseUpdate(path, data) {
    const update = {
        [path]: data
    };

    return firebaseApp.database().ref().update(update);
}
```

**Comment by chrisbianca** [comment]
What do you mean by it works in other projects in that way?
Regardless, my point is that `update()` returns a promise anyway, so there is no need for your async / await modifiers to use it in the way you have specified.

**Comment by lucianomlima** [comment]
As I said initially, it was working this way, with an async/await function.
Until now I have 2 apps, one works and another one don't.

**Comment by vzhen** [comment]
Same issue here,  version 11.0.4. It works for a week and suddenlly not working with this error. I am not using any async

**Comment by vzhen** [comment]
@lucianomlima  Did you find any solution ?

**Comment by vzhen** [comment]
@lucianomlima  I figured it out. Please check firebase security rules.
