### ISSUE TITLE
Invalid `RNFBAnalytics.podspec` file: No such file or directory @ rb_sysopen - ../app/package.json.

### ISSUE THREAD

**Issue by mossen** [invertase/react-native-firebase#4101]
Running following command:
user@192-168-1-109 ios % **pod install --repo-update**

**getting this:**

[!] Invalid `Podfile` file: 
[!] Invalid `RNFBAnalytics.podspec` file: No such file or directory @ rb_sysopen - ../app/package.json.

from ShelemCounter/node_modules/@react-native-firebase/analytics/RNFBAnalytics.podspec:3
  -------------------------------------------
  package = JSON.parse(File.read(File.join(__dir__, 'package.json')))
 >  appPackage = JSON.parse(File.read(File.join('..', 'app', 'package.json')))

Running:
"@react-native-firebase/analytics": "^7.4.2",
"react": "16.13.1",
"react-native": "0.63.2",

**Comment by mikehardy** [comment]
The installation instructions indicate the app module is required, it will work if you install it

**Comment by IrynaBt** [comment]
You should to add @react-native-firebase/app, so run

`yarn add @react-native-firebase/app`

**Comment by vinitsood** [comment]
> 

This helped me! Thanks for sharing it!

**Comment by vinitsood** [comment]
> Im commenting this here because this thread is ranked high on google, best case it saves somebody time in the future 😄

This helped me! Thanks for sharing it @lauhon

**Comment by Kawaljeet-AUI** [comment]
> Unrelated to this project, but:
> 
> This error also occurs when organizing a react-native project with yarn workspaces. To fix it add the `react_native_path` option to `react_native_post_install`
> 
> ```ruby
>   react_native_post_install(
>       installer,
>       react_native_path = "../../../node_modules/react-native",
>       # Set `mac_catalyst_enabled` to `true` in order to apply patches
>       # necessary for Mac Catalyst builds
>       :mac_catalyst_enabled => false
>     )
> ```
> 
> Im commenting this here because this thread is ranked high on google, best case it saves somebody time in the future 😄

Future saved. Mission successful!

**Comment by Kaveh-ap** [comment]
> Unrelated to this project, but:
> 
> This error also occurs when organizing a react-native project with yarn workspaces. To fix it add the `react_native_path` option to `react_native_post_install`
> 
> ```ruby
>   react_native_post_install(
>       installer,
>       react_native_path = "../../../node_modules/react-native",
>       # Set `mac_catalyst_enabled` to `true` in order to apply patches
>       # necessary for Mac Catalyst builds
>       :mac_catalyst_enabled => false
>     )
> ```
> 
> Im commenting this here because this thread is ranked high on google, best case it saves somebody time in the future 😄

I was facing this issue, and the problem was related to react_native_path! 
Thanks = )
