### ISSUE TITLE
🔥 Crashlytics reports are not containing proper variable names

### ISSUE THREAD

**Issue by thevishnupradeep** [invertase/react-native-firebase#4103]
## Issue

After upgrading to v6 (v8 now) crashlytics report are not exactly very helpful. I am not sure what I am doing wrong.
![Screenshot 2020-08-18 at 8 11 19 PM](https://user-images.githubusercontent.com/5638461/90538707-f417e100-e18f-11ea-9be2-bd6537602b89.png)

I am not sure which info to include as I am not sure what is the root cause. 
#### `package.json`:
```
"@react-native-firebase/analytics": "^7.4.2",
"@react-native-firebase/app": "^8.3.1",
"@react-native-firebase/crashlytics": "^8.3.1",
"@react-native-firebase/database": "^7.4.2",
"@react-native-firebase/dynamic-links": "^7.4.2",
"@react-native-firebase/messaging": "^7.7.1",
```

#### `firebase.json` for react-native-firebase v6:

```json
{
    "react-native": {
        "database_persistence_enabled": true
    }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
$FirebaseSDKVersion = '6.28.1'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'bgx' do
  pod 'GoogleIDFASupport'
  pod 'Intercom', '~> 7.1.0'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 1.10 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.7 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - < v0.60.x
- **Are you using `TypeScript`?**
  - No

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You're not doing anything wrong. This is a javascript stack trace. You have a javascript error and now at least the stack is available, that's a brand new features in react-native-firebase >= v6

But, similar to iOS dSYMs or Android deobfuscation files, how can crashlytics know how to decode your stack? The javascript build chain can be quite deep after all (mine does a typescript to javascript compile, then a separate gulp-based module aliasing transpile, then it is bundled and minified, how can crashlytics decode that)?

So what you do is tag your releases, then if you want to investigate one of these you pull that tag, re-run your build with source maps generated, and run the thing through a de-obfuscator - there are a few generally available

None of this is a module problem though, it is a technology thing inherent to javascript deployment style
