### ISSUE TITLE
📸  Built with React Native Firebase showcase

### ISSUE THREAD

**Issue by Ehesp** [invertase/react-native-firebase#4106]
We're looking to showcase Android and/or iOS applications on our website 🥳 If you're using React Native Firebase please let us know!

Please add a comment below 🔥

---

- **Name / Company**:
- **Application / Product Name:**
- **Play Store URL**:
- **App Store URL**:
- **Modules** (e.g: firestore, analytics):
- **Additional details**:

**Comment by AndrewJack** [comment]
Name / Company: Digital Tribe

**Application / Product Name:**  DriveTribe
**Play Store URL:** https://play.google.com/store/apps/details?id=com.drivetribe&hl=en
**App Store URL:** https://apps.apple.com/gb/app/drivetribe/id1164159977
**Modules:** analytics, crashlytics, in-app-messaging, messaging, perf, remote-config, dynamic-links
**Additional details:** An automotive online community platform founded by The Grand Tour presenters Jeremy Clarkson, James May and Richard Hammond.

**Application / Product Name:**  FoodTribe
**Play Store URL:** https://play.google.com/store/apps/details?id=com.foodtribe.app&hl=en_US
**App Store URL:** https://apps.apple.com/us/app/foodtribe-app-for-foodies/id1478284014
**Modules:** analytics, crashlytics, in-app-messaging, messaging, perf, remote-config, dynamic-links
**Additional details:** A food based online community platform founded by Jeremy Clarkson, James May and Richard Hammond.

**Comment by ahanusek** [comment]
Name / Company: fireup.pro

Application / Product Name: treneiro.me 
Play Store URL: https://play.google.com/store/apps/details?id=com.fireup.pro.treneiro
App Store URL: https://apps.apple.com/gb/app/treneiro-me/id1397018823
Modules: analytics, auth, crashlytics, dynamic-links, firestore, functions, messaging, perf, remote-config, storage
Additional details: App for personal trainers and their clients (workouts tracking, nutrition plans, body & weight measurements, and many more).

**Comment by diegolmello** [comment]
**Name / Company:** Rocket.Chat
**Application / Product Name:** Rocket.Chat
**Play Store URL:** https://play.google.com/store/apps/details?id=chat.rocket.android
**App Store URL:** https://apps.apple.com/us/app/rocket-chat/id1148741252
**Modules:** analytics, crashlytics
**Additional details:** The ultimate Free Open Source Solution for team communications.
Server repo: https://github.com/RocketChat/Rocket.Chat
App repo: https://github.com/RocketChat/Rocket.Chat.ReactNative

**Comment by shirakaba** [comment]
**Name / Company:** Jamie Birch
**Application / Product Name:** LinguaBrowse
~~Play Store URL:~~
**App Store URL:** https://apps.apple.com/gb/app/linguabrowse/id1281350165
**Modules:** Auth, Dynamic Links, Firestore, Analytics
**Additional details:** A web browser for studying foreign languages. Easily read any foreign-language website with the help of a one-tap popup dictionary; add transcriptions to languages such as Japanese and Chinese; hear pronunciations upon tapping words; and automatically build a vocabulary list of all the words that have challenged you. Follow [@LinguaBrowse](https://twitter.com/LinguaBrowse) on Twitter for progress updates on the upcoming macOS Safari App Extension.

**Comment by rahul2992** [comment]
**Name / Company:** HTT Holidaying Travel Technologies Pvt. Ltd.
**Application / Product Name:** Holidaying.travel 
**Play Store URL:** https://play.google.com/store/apps/details?id=com.holidaying.holidaying&hl=en
**App Store URL:** https://apps.apple.com/in/app/holidaying/id1497348229
**Modules (e.g: firestore, analytics):** firestore, auth, app, analytics, storage, crashlytics, dynamic-links
**Additional details:** We are a platform for people to discover, plan and book trips by travel influencers and locals. Anyone from a blogger, influencer or an avid traveller can create their travel blog/store on the app, and earn for any bookings. For travellers, it gives a one step solution from reading a blog to actually booking and planning the trip. 

Website: https://holidaying.travel/influencer/

**Comment by mikehardy** [comment]
- **Name / Company**: Kullki Fintech KSS S.A.
- **Application / Product Name:** Komp.ai
- **Play Store URL**: https://play.google.com/store/apps/details?id=com.kullki.kscore
- **App Store URL**: https://apps.apple.com/us/app/komp-ai/id1498259800?ls=1
- **Modules** (e.g: firestore, analytics): firestore, messaging, analytics, dynamic links, auth, crashlytics
- **Additional details**: Komp.ai is an award-winning, secure, privacy-focused technological solution focused on non-conventional data mining based on your mobile device information. This data can be used when making financial decisions and even predict behavior based on our KompAI score.

**Comment by andersonaddo** [comment]
**Name**: Anderson Addo
**Application**: Biteup
**App Store URL**: pending
**Play Store URL**:  pending
**Modules**: Firestore, Messaging, Performance, Crashlytics, Analytics, Auth, Database, Storage
**Additional Details**: Release delayed by COVID (will update comment when situation changes). Website: https://biteup.app

**Comment by DanGDroid** [comment]
**Name / Company:** Kimaia
**Application / Product Name:** [FARMER](https://www.farmerdirecto.com/)
**Play Store URL:** https://play.google.com/store/apps/details?id=com.agricula.farmer
**App Store URL:** https://apps.apple.com/il/app/farmer-direct/id1327728378
**Modules:** Analytics, Messaging, Notifications, Dynamic-Links;
**Future Modules**: A/B testing, Remote-Config
**Additional details:** FARMER is great news for farmers, and even bigger news for consumers. Because FARMER is a place where the farmer and the end consumer meet. That’s what we call “Direct Farming”.

**Comment by r0b0t3d** [comment]
**Name / Company:** STT LABS CO., LTD
**Application / Product Name:** Stuneo
**Play Store URL:** https://play.google.com/store/apps/details?id=com.stuneo
**App Store URL:** https://apps.apple.com/vn/app/stuneo-3d-video-for-run-ride/id1485979882
**Modules:** Firestore, Auth, Crashlytics, Analytics, Messaging, Dynamic-Links, Storage, Functions
**Additional details:** Stuneo is a FREE app helps to create 3D landscape video of your Strava outdoor activities such as: Running, Riding, Hiking & More. You connect with Strava account to import activities and then the app will generate 3D videos of bird-eye view for you automatically. You can also track your run, ride or hike in-app. The video then can be shared with friends & family.

**Comment by tuan072090** [comment]
Name / Company: Meete
Application / Product Name: Meete
Play Store URL: https://play.google.com/store/apps/details?id=com.cixa.meete
App Store URL: https://apps.apple.com/vn/app/meete/id1066923602
Modules: Auth, Crashlytics, Analytics, Messaging, Dynamic-Links, Remote config, A/B testing
Additional details: Meete is an e-voucher app that helps people can experience quality restaurants with the best promotion.

**Comment by laurentS** [comment]
Name / Company: MapSwipe
    Application / Product Name: MapSwipe
    Play Store URL: https://play.google.com/store/apps/details?id=org.missingmaps.mapswipe
    App Store URL: https://apps.apple.com/us/app/mapswipe/id1133855392
    Modules (e.g: firestore, analytics): Realtime Database, Auth, Analytics, Cloud Messaging
    Additional details: MapSwipe lets users label satellite imagery to help humanitarians find and help vulnerable people.

**Comment by ACHP** [comment]
**Name / Company:** GensDeConfiance
**Application / Product Name:** GensDeConfiance
**Play Store URL:** https://play.google.com/store/apps/details?id=fr.gensdeconfiance.app
**App Store URL:** https://apps.apple.com/us/app/gdc-petites-annonces/id1103739976
**Modules :** Crashlytics, Analytics, Messaging
**Additional details:** your ards on a trustworthy network. Tired of online scams? Time to try GensDeConfiance! With more than 500 000 members, GensDeConfiance offers a trustworthy and secured way to sell, buy, and rent with other individuals. Give it a try, it’s free!
