### ISSUE TITLE
android-message: after migration from v5 to v6 notifications are displayed without icons

### ISSUE THREAD

**Issue by pabloearg** [invertase/react-native-firebase#4108]
## Issue

after migrating from v5 to v6 notifications are displayed without icons

in the previous version on the package we put in the android manifest our notification icon like this:

```
 <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_notifications" />
```

but now, the only configuration i can see is the [notification color]( https://rnfirebase.io/messaging/usage#notification-color)

only in one device, ( a samsung s10 plus) i can see that is getting the notification icon from the android:icon attribute

```
<application
        android:name=".MainApplication"
        android:allowBackup="false"
        android:icon="@mipmap/ic_launcher"
```

but for all the other devices that i tested (android emulators and 4 other physical devices) the notification icon shows like this:

![image](https://user-images.githubusercontent.com/29818262/90675391-c636a900-e230-11ea-857d-b5ad2141a45f.png)

![image](https://user-images.githubusercontent.com/29818262/90675647-22013200-e231-11ea-8f49-436abf2ed430.png)

is there any hidden configuration that im missing?

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
 "@react-native-firebase/analytics": "7.4.1",
    "@react-native-firebase/app": "8.3.0",
    "@react-native-firebase/dynamic-links": "7.4.1",
    "@react-native-firebase/messaging": "7.6.1",
```

</details>

## Environment

<details><summary>Click To Expand</summary>
<p>

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I think there are two unrelated things
- one is that the notification that is being displayed is not following the android icon guidelines, that's a classic when you get a gray circle https://stackoverflow.com/questions/45318614/why-is-my-smallicon-for-notifications-always-greyed-out
- one is configuration - I'm not sure how to configure the default notifications icon though your AndroidManifest seems correct on the face of it, it may be that there is something to do in firebase.json but I'm not sure as I use my launcher icon as the notification icon...

**Comment by pabloearg** [comment]
> I think there are two unrelated things
> 
> * one is that the notification that is being displayed is not following the android icon guidelines, that's a classic when you get a gray circle https://stackoverflow.com/questions/45318614/why-is-my-smallicon-for-notifications-always-greyed-out
> * one is configuration - I'm not sure how to configure the default notifications icon though your AndroidManifest seems correct on the face of it, it may be that there is something to do in firebase.json but I'm not sure as I use my launcher icon as the notification icon...

@mikehardy 
- we are using the same icon that we had before the migration

- what do you mean with this?: **_i use my launcher icon as the notification icon..._**

- in the firebase.json there isn't any configuration about the message icon

**Comment by mikehardy** [comment]
Smells similar to this #3967 - especially note the last comment (you can audit it by opening the .apk in Android Studio to get a look at what was actually packaged after minification - in case this is a release mode issue)


This still applies:

>  that's a classic when you get a gray circle https://stackoverflow.com/questions/45318614/why-is-my-smallicon-for-notifications-always-greyed-out

>     * we are using the same icon that we had before the migration

Yet it is only gray now? That doesn't make sense. Either the icon works on newer APIs or it doesn't. Or perhaps you just changed your target API from way low to way high (so the icon restrictions apply to you now) but that is very improbable

>     * what do you mean with this?: **_i use my launcher icon as the notification icon..._**

Ah - I was mistaken anyway, here's my info:

```
mike@isabela:~/work/Kullki/ksocialscore/packages/public-app/android/app/src/main (rebranding) % cat AndroidManifest.xml |grep icon
      android:icon="@mipmap/ic_launcher"
    <!-- Set custom default icon. This is used when no icon is set for incoming notification messages.
    <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/minilogo_bw" />
```

> 
>     * in the firebase.json there isn't any configuration about the message icon

I don't have anything in there either, seems the AndroidManifest snippet is all I needed

```
mike@isabela:~/work/Kullki/ksocialscore/packages/public-app (rebranding) % more firebase.json 
{
  "react-native": {
    "messaging_android_notification_channel_id": "high-priority"
  }
}
```

**Comment by hadimoha** [comment]
Was this ever resolved? Having this issue with small icons in background and closed state. it was working in v5


```
<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_notification" />
<meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/white" />
```


<img width="347" alt="Screenshot 2020-09-10 at 09 02 42" src="https://user-images.githubusercontent.com/23414844/92687636-9d439880-f344-11ea-8c66-abcfcdbe8d14.png">

**Comment by mikehardy** [comment]
The comment above yours (from me) indicates it is working and I cannot reproduce. It works for me? Maybe @pabloearg has learned something while working on his case
