### ISSUE TITLE
ios  the app always goes to the appstore: having a previous version of the app in the market and adding dynamic links,

### ISSUE THREAD

**Issue by pabloearg** [invertase/react-native-firebase#4110]
## Issue

i have been searching everything  about this, and i found nothing, we have an app in the appstore right now that has branch.io, and we are replacing that for firebase dynamic links

But for some reason, in some devices and with a few apps  (messages, whatsapp and others...)  when opening our link , the link goes to safari directly, and then goes to the appstore, even if we have the app installed in the iphone or ipad.

i have installed ad-hoc versions of the ipa and even run the app directly from the xcode, but im getting different behaviours between iphones and applications

when we create the links we are using this flag:

 ```
navigation: {
        forcedRedirectEnabled: true,
      }
```

and we followed every step in your documentation and in the  [firebase tutorial](https://youtu.be/KLBjAg6HvG0)

is this the expected behaviour? is apple checking if the app that is installed in the phone was downloaded from the store before? i didnt find any documentations that support this

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/analytics": "7.4.1",
    "@react-native-firebase/app": "8.3.0",
    "@react-native-firebase/dynamic-links": "7.4.1",
    "@react-native-firebase/messaging": "7.6.1",
```

</details>

## Environment

<details><summary>Click To Expand</summary>

- **Platform that you're experiencing the issue on**:
  - [X] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both

</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Have you searched in https://github.com/firebase/firebase-ios-sdk/issues/ ? I seem to recall this being a tough topic - the related issues here seem to trail off and hit upstream (firebase-ios-sdk) questions
