### ISSUE TITLE
https://graph.facebook.com/v2.12/me on  auth().signInWithCredential(facebookCredential)

### ISSUE THREAD

**Issue by max010** [invertase/react-native-firebase#4112]
## Issue

Describe your issue here

I have react native app with facebook login via firebase.
The app is in live mode, but currently users can't login using facebook, only administrators and developers can signIn.
Starting from the date when Facebook Auth was added(4 months) to about two weeks ago it worked fine. After that something was broken.

When I try to login I get:
[ Failed to fetch resource from https://graph.facebook.com/v2.12/me, http status: 400, http response: {"error":{"message":"Unsupported get request.","type":"GraphMethodException","code":100,"fbtrace_id":"AtkozMyJv-hu5vH-12a-7Nn" ]

 
I asked Facebook support and get:
"I got information from the product team, the reason you saw this error was the version 2.12 of Graph API expired back in May 2020: https://developers.facebook.com/docs/graph-api/changelog/version2.12.
Please upgrade to the latest version then the issue will be fixed.
Hope this helps."

Additional info:
After I get token from AccessToken.getCurrentAccessToken(), I can successfully use graph api with them.
### Javascript

```javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import auth from '@react-native-firebase/auth';
import firebase from '@react-native-firebase/app';
import React,{useEffect} from 'react';
import {
  StyleSheet,
  View,
  Text,
  StatusBar,
  Alert,
  Button
} from 'react-native';
import { LoginManager, AccessToken } from 'react-native-fbsdk';


const App: () => React$Node = () => {
  useEffect(() => {
    LoginManager.logOut();
    if(auth().currentUser){
      auth().signOut().then(() => console.log('User signed out!'));
    }
  }, []);

  const login = () =>{
  LoginManager.logInWithPermissions(["public_profile"]).then(
      function(result) {
        if (result.isCancelled) {
          console.log("Login cancelled");
        } else {
          console.log(
            "Login success with permissions: " +
              result.grantedPermissions.toString()
          );
          AccessToken.getCurrentAccessToken().then(
            (data) => {
              console.log(data.accessToken.toString())
              const facebookCredential = auth.FacebookAuthProvider.credential(data.accessToken);
              auth().signInWithCredential(facebookCredential).then(result=>{
                console.log("firebase success",result)
              }, error=>{
                console.log("firebase failed",error)
              });
            }
          )
        }
      },
      function(error) {
        console.log("Login fail with error: " + error);
      }
    );
  }  
return (
     <View style={{flex:1, justifyContent:'center'}}>
       <Button title="Login" onPress={login}></Button>
     </View> 
  );
};

const styles = StyleSheet.create({
  
});

export default App;
```

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
```json
{
  "name": "facebookExaple",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-firebase/app": "^8.3.1",
    "@react-native-firebase/auth": "^8.3.3",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-fbsdk": "^2.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.11.1",
    "@babel/runtime": "^7.11.2",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.3.0",
    "eslint": "^7.7.0",
    "jest": "^26.4.0",
    "jetifier": "^1.6.6",
    "metro-react-native-babel-preset": "^0.62.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
This does not seem related to react-native-firebase, I'll need to see a demonstration app that reproduces it. 
I can say that I use facebook auth in my app, just did so this morning in fact, and it works fine with current stable versions of react-native-firebase and react-native-fbsdk so I can't reproduce this

We can reopen if you post a minimal reproduction showing the problem
