### ISSUE TITLE
RN 0.48.3 does not include `didFinishLaunchingWithOptions` in AppDelegate.m

### ISSUE THREAD

**Issue by samuela** [invertase/react-native-firebase#412]
### Issue

The docs here: https://invertase.io/react-native-firebase/#/installation-ios?id=_21-add-the-required-pods indicate that one should add `[FIRApp configure];` to the `didFinishLaunchingWithOptions:(NSDictionary *)launchOptions` method. However, the most recent version of react native (at least) does not template out that method in AppDelegate.m. It would be better to include a full method code sample in this case, including the relevant stuff necessary in AppDelegate.h.

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS 10.12.6

3. Build Tools: N/A

4. React Native version: 0.48.3

5. RNFirebase Version: 2.2.0

6. Firebase Module: N/A

**Comment by chrisbianca** [comment]
@samuela I've just tried this using 0.48.3 and the `AppDelegate.m` does include the `didFinishLaunchingWithOptions` method as expected.

Did you perhaps use `create-react-native-app` to initialise your app?  In which case, this doesn't support native code out of the box, you need to eject (which I'm assuming will create this method for you)

**Comment by samuela** [comment]
@chrisbianca Interesting... I was using `react-native init` with no extra flags. I'm using Xcode v9.0. Perhaps there are some spurious Xcode/iOS settings that matter.
