### ISSUE TITLE
[iOS] iOS-14 GMA compatibility

### ISSUE THREAD

**Issue by mars-lan** [invertase/react-native-firebase#4127]
More info at https://developers.google.com/admob/ios/ios14

tl;dr minimally RNFB will need expose API to
- request for tracking authorization
- get the status of tracking authorization

**Comment by mikehardy** [comment]
This is covered already: #4107 - use react-native-permissions, and do a pod update, should be good to go?

**Comment by mars-lan** [comment]
Thanks for the info. Will wait for https://github.com/react-native-community/react-native-permissions/pull/501 to be merged.

**Comment by mikehardy** [comment]
The related react-native-permissions PR has been merged, if you get `react-native-permissions@2.2.0` (or greater) and have Xcode12 + ios14 + `pod update` (to get the new Mobile-Ads-SDK) you should be set. 

Any reports of success or failure are welcome, this is the leading edge of development now but will affect lots of users so the reports will be useful to your fellow developers!
