### ISSUE TITLE
firebase.storage(app) arg expects a FirebaseApp instance or undefined.

### ISSUE THREAD

**Issue by yesterday24** [invertase/react-native-firebase#4135]
I get the following error while trying to upload a file to a bucket using @react-native-firebase/storage.

> firebase.storage(app) arg expects a FirebaseApp instance or undefined.

I have the following code (simplified):
````
import storage from '@react-native-firebase/storage';

const upload = () => {
  const ref = storage().ref('black-t-shirt.png');
  ref.putFile(filePath).then(() => {
    console.log('uploaded');
  }).catch((error) => {
    console.log('Error', error);
  });
};
````
**Environment:**
- iPhone 11, iOS 13.6
- React Native 0.63.0
- React 16.13.1

I followed the installation instructions as described [here](https://rnfirebase.io/#3-ios-setup). I also added the ``[FIRApp configure];`` to /ios/{projectName}/appDelegate.m. I've added a GoogleService-Info.plist to the ios folder as described. Basically I followed all the instructions like described here.

My question is: is this a bug, or do I have to initialize a firebase app (like the error says) as described [here](https://rnfirebase.io/app/usage#initializing-secondary-apps)?

**Comment by mikehardy** [comment]
Hi there! You have not included any versions of react-native-firebase or the firebase-ios-sdk pods or whether this is ios or android specific or on both, so it is hard to say if this is an old problem or not.

You can look for inspiration at the e2e (end-to-end) tests, they are running [mostly successfully](https://github.com/invertase/react-native-firebase/runs/1013935153?check_suite_focus=true#step:20:1091) (it's an area of current work but the easy cases all pass), so I would assume their usage pattern could be used in your project with success

There may be a bug still - but getting your project moving while triage happens is useful and that might point the way https://github.com/invertase/react-native-firebase/tree/master/packages/storage/e2e

**Comment by yesterday24** [comment]
package.json
````
    ...
    "@react-native-firebase/analytics": "^7.4.2",
    "@react-native-firebase/app": "^8.3.1",
    "@react-native-firebase/crashlytics": "^8.3.1",
    "@react-native-firebase/iid": "^7.3.3",
    "@react-native-firebase/messaging": "^7.7.1",
    "@react-native-firebase/storage": "^7.3.3",
    ...
    "react": "16.13.1",
    "react-native": "0.63.0",
````

GoogleServices-Info.plist-file is included in the root folder (/ios). I've added the ``[FIRApp configure];`` parto to my appDelegate.m-file (like I said).

I have only tested this on iOS because I'm developing an app only for iOS. I deleted the Android-folder from the project.

I'll check out the end-to-end tests now.
