### ISSUE TITLE
React pod has been deprecated and build fails

### ISSUE THREAD

**Issue by samuela** [invertase/react-native-firebase#414]
### Issue

The React pod, which is one of RNFirebase's dependencies, has been deprecated. A minimal Podfile looks something like

```ruby
platform :ios, '9.0'

target 'ReactNativePlayground' do
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
end
```

and running `pod update && pod install`, produces a warning

```
[!] React has been deprecated
```

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS 10.12.6

3. Build Tools: N/A

4. React Native version: 0.48.3

5. RNFirebase Version: 2.2.0

6. Firebase Module: N/A

**Comment by samuela** [comment]
Addendum: this causes builds to fail with RN 0.48.3, RNFirebase 2.2.0, and pods:
```
  - React (0.11.0):
    - React/Core (= 0.11.0)
  - React/Core (0.11.0)
```

The react native packager produces

```
This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: Object.es6
  Paths: /Users/samuelainsworth/Development/ReactNativePlayground/ios/Pods/React/packager/react-packager/src/DependencyResolver/polyfills/polyfills.js collides with /Users/samuelainsworth/Development/ReactNativePlayground/node_modules/react-native/Libraries/polyfills/Object.es6.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /Users/samuelainsworth/Development/ReactNativePlayground/ios/Pods/React/package.json collides with /Users/samuelainsworth/Development/ReactNativePlayground/node_modules/react-native/package.json

.......

This warning is caused by a @providesModule declaration with the same name across two different files.
Bundling `index.ios.js`  [development, non-minified, hmr disabled]  0.0% (0/1), failed.
error: bundling failed: ambiguous resolution: module `/Users/samuelainsworth/Development/ReactNativePlayground/index.ios.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `/Users/samuelainsworth/Development/ReactNativePlayground/ios/Pods/React/package.json`
  * `/Users/samuelainsworth/Development/ReactNativePlayground/node_modules/react-native/package.json`
```

I'm confident that this issue is tied to the deprecation of the React pod, etc. but I cannot be entirely certain, and others' insights here would of course be appreciated.

**Comment by samuela** [comment]
Ah, so the pod deprecation warning is because I am a fool and forgot the 

```ruby
pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'BatchedBridge', # Required For React Native 0.45.0+
  'Core',
  # Add any other subspecs you want to use in your project
]
```

section in my Podfile. However, the ambiguous resolution errors persist.

**Comment by samuela** [comment]
Further edit: I was having build issues, but I was able to resolve them by adding `DevSupport` to the subspecs list for React:

```ruby
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'BatchedBridge', # Required For React Native 0.45.0+
  'Core',
  'DevSupport'
  # Add any other subspecs you want to use in your project
]
```

Now the `react-native run-ios` build "succeeds." However, I'm still seeing the same bundling issue:

```
Bundling `index.ios.js`  [development, non-minified, hmr disabled]  0.0% (0/1), failed.
error: bundling failed: ambiguous resolution: module `/Users/samuelainsworth/Development/ReactNativePlayground/index.ios.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `/Users/samuelainsworth/Development/ReactNativePlayground/ios/Pods/React/package.json`
  * `/Users/samuelainsworth/Development/ReactNativePlayground/node_modules/react-native/package.json`
```

Here's the simulator perspective: 
![screen shot 2017-09-16 at 1 30 15 am](https://user-images.githubusercontent.com/226872/30509445-aa823e7e-9a7e-11e7-9b4d-ec4c04d4aa67.png)

**Comment by olivierlesnicki** [comment]
Seeing same issue as @samuela

**Comment by olivierlesnicki** [comment]
For some reason the install process also creates a React folder under /ios/Pods, deleting it fixes the issue:
https://github.com/Microsoft/react-native-code-push/issues/745

**Comment by samuela** [comment]
@olivierlesnicki My understanding is that the /ios/Pods/React/ folder is brought into existence because of the 

```
pod 'React', :path => '../node_modules/react-native' ...
```

bit in the Podfile. Are you sure it's safe to delete it?

**Comment by JackThomson2** [comment]
Hi guys I had a similar issue with you but it was to do with archiving try adding this at the bottom of your pod file:

```

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

**Comment by chrisbianca** [comment]
Docs have been updated with @JackThomson2's fix above which has been confirmed to work in certain situations.  Please re-open if this is still an issue.

With v3 we are looking at getting `react-native link` to work again - unfortunately basic support provided by React doesn't give us the right level of customisation for Android, but we'll figure something out.

**Comment by johnernaut** [comment]
Hi, I've added the fix described by @JackThomson2 for this in my Podfile, and I've confirmed that `Pods/React` does not exist, but I'm still getting the following error from the react packager:

```
Bundling `index.ios.js`  [development, non-minified, hmr disabled]  0.0% (0/1), failed.
error: bundling failed: ambiguous resolution: module `/Users/<john>/code/RMMobile/index.ios.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them:
* `/Users/<user>/code/RMMobile/ios/Pods/React/package.json`
* `/Users/<user>/code/RMMobile/node_modules/react-native/package.json`
```

Any ideas?

**Comment by bramus** [comment]
Referencing https://github.com/react-native-community/react-native-svg/issues/463

**Comment by staufman** [comment]
If anyone else is seeing there, it may be because the block of code in the Podfile (see the post a few above this one) which removes React was added after running `pod install` once. In this case, the React pod will be in your `Pods/` directory and it will _not_ be removed after running `pod intall` again with the block of code that removes React. In short, try deleting your `Pods/` directory and then run `pod install` again. You will most likely need to reset your cache too i.e. `npm start -- --reset-cache`.

**Comment by bramus** [comment]
Had the same issue. Running all typical sh*tfix-commands (`watchman watch-del-all`, `rm -rf $TMPDIR/react-*`, `yarn cache clean && rm -rf node_modules/ && yarn install`, etc) had no result.

Restarting my Mac eventually fixed it for me ¯\_(ツ)_/¯

**Comment by brenmcnamara** [comment]
I added the code snippet commented above and it fixed the issue, however I am getting 3 new warnings that I think are related to this:

1. `Pods-<Project Name>: Missing dependency target 'React'`
2. `Apple Mach-O Linker Warning:`

```
directory not found for option:
'-L\~/Library/Developer/Xcode/DerivedData/<Project Name>-brqiwtorgjqxrhcepigoefhmtcve/Build/Products/Debug-iphonesimulator/React'
```

3. The same warning as above, but for the test target.

I've tried the following:

```
yarn cache clean
watchman watch-del-all
rm -rf node_modules && yarn install
cd ios && rm -rf Pods && pod install
Clean xcode build, clean xcode build folders
Resetting the simulator to its default settings
Restarting my computer
```

None of those helped. Is anyone else seeing these warnings, or has any idea how to make them go away?

Thanks in advance!

**Comment by AbdallahNofal** [comment]
I fixed this issue 

>  `/Users/samuelainsworth/Development/ReactNativePlayground/ios/Pods/React/package.json`
 > `/Users/samuelainsworth/Development/ReactNativePlayground/node_modules/react-native/package.json`

Follow these steps:
1. Open xcode
2. Open folder "Recovered References" at the left sidebar. 
3. Remove "libReact.a" from it.

**Comment by Cawfree** [comment]
You can prevent `RNFirebase` from importing a duplicate instance of `react-native` by disabling all `subspecs` of the module:

`pod 'RNFirebase', :path => './../node_modules/react-native-firebase/ios', :subspecs => []`

**Comment by ShunYamada** [comment]
I have the same problem and fixed it yet.

1. deleted ios/Pods
2. Restart your Mac
3. Pod install on ios/Pods

And I removed them.
  # pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  #
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

**Comment by MaheshNandam** [comment]
I have fixed this issue by 'npm start -- --reset-cache' command.

**Comment by allanjsx** [comment]
I fixed it by adding below lines to the pod file, to make sure CocoaPod gets React dependency from node_modules instead of creating a new directory and pulling from other repo.

```
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
```
And in my case, I make sure that I also removed the above suggested: 

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```
so that the libs can be properly linked to my project.

**Comment by Nonnis-M** [comment]
@allanjsx is the only solution that fix the problem for me after I have spent 2 days searching around...

Anyway I'm struggling understand why on another machine (Mac osx) with same project configuration and same cocoapod version (1.40) the pod install command does not generate the React dependency and all works perfectly...

**Comment by wikieswan** [comment]
@MobileWojciec as you say, ```pod update``` works for me

**Comment by mahendrathotakura** [comment]
I am also having the same issue.

bundling failed: ambiguous resolution: module `/Users/**/**/index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `/Users/**/**/ios/Pods/React/package.json`
  * `/Users/**/**/node_modules/react-native/package.json

Can you please help me out

**Comment by MobileWojciec** [comment]
@mahendrathotakura  Can you show the detailed environment of your app?

**Comment by mahendrathotakura** [comment]
> @mahendrathotakura Can you show the detailed environment of your app?

here is the pod file

target 'SamsAdminApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	
	pod 'Firebase/Messaging'
    pod 'GoogleMaps'
  # Pods for SamsAdminApp


  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
   

  target 'SamsAdminAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SamsAdminApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SamsAdminApp-tvOS

  target 'SamsAdminApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by mahendrathotakura** [comment]
> @mahendrathotakura Can you show the detailed environment of your app?

Thanks for your response! I fixed the issue, it is due to Pods.

**Comment by felipemillhouse** [comment]
The complete solution to solve this, your Podfile should look likes that example below. After alter the file you have to do a `pod update`

```
 platform :ios, '9.0'

 install! 'cocoapods', :deterministic_uuids => false

target 'yourproject' do
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  # Pods for yourproject
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)

    if targets_to_ignore.include? target.name
      target.remove_from_project
    end
  end
end
```

**Comment by ThomasGHenry** [comment]
I was getting the "Multiple commands produce ..." for libRNFirebase.a and seem to have solved it based on this https://github.com/facebook/react-native/issues/20492#issuecomment-494929055

**Comment by leron8** [comment]
Omg I was struggling with this for two days. I did what @allanjsx said in his comment but I deleted the Pod directory and then `pod install`. That recreated the whole directory with the correct reference to React in node_modules.

**Comment by mikehardy** [comment]
You guys might like the addition I just made to react-native-clean-project - after you install that module you just run `react-native clean-project-auto` and it purges all the react-native state (including pod) that I'm aware of. You have to reinstall node and pod packages afterwards, but before tearing hear out, it's a good thing to try...

**Comment by stereodenis** [comment]
`cd android && ./gradlew clean` helps me
