### ISSUE TITLE
[📚] Reference docs edit links broken - missing package name

### ISSUE THREAD

**Issue by mikehardy** [invertase/react-native-firebase#4148]
## Documentation Feedback

Last night when I clicked on the edit button for one of the reference documentation pages, the link generated was 404, the package name was missing from the link

Example:

On page: https://rnfirebase.io/reference/messaging

Edit link is: https://github.com/invertase/react-native-firebase/blob/master/messaging/lib/index.d.ts#L515

But should be: https://github.com/invertase/react-native-firebase/blob/master/packages/messaging/lib/index.d.ts#L515

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
@Ehesp this might be one you know off the top of your head immediately - perhaps there is a redirect mapping file in the docs build somewhere? Even just a pointer to a general location of the docs build and I could try to untangle it

**Comment by Salakar** [comment]
I expect the culprit is probably around here: https://github.com/invertase/react-native-firebase/blob/master/website/scripts/utils.js#L109

**Comment by Salakar** [comment]
Edit Button links to the entity 'source' property, all referenced here: https://github.com/invertase/react-native-firebase/blob/aaebe42e4b5e73097be8ab869b2c3d913f60dc7a/website/scripts/source-reference.js and all using the `extractSourceFile` mentioned above, so must be that util 😅

**Comment by Salakar** [comment]
Slapping `packages` after `master` should do the trick
