### ISSUE TITLE
[🔥]@react-native-firebase_firestore has not defined a default in project.ext.'react-native'.versions.android.compileSdk

### ISSUE THREAD

**Issue by tranhuuthinhit** [invertase/react-native-firebase#4160]
Gradle Task fails on building the app.

A problem occurred configuring project ':@react-native-firebase_firestore'.
compileSdkVersion is not specified.

This is happening post release of new version 7.0.1 for @react-native-firebase/firestore

**Comment by mikehardy** [comment]
We are consolidating problems like this in the related issue #4154

I suspect you have an unexpected node_modules layout that violates an invariant assumption in our packaging (that app and all react-native-firebase modules will be peer-level in node_modules)

**Comment by ITLight** [comment]
downgrade version can solve this problem. In my case 7.6.2 -> 7.5.1

**Comment by mikehardy** [comment]
That's not a great solution. You want to be on current stable versions. Upgrading all packages to the current stable version should do it.
