### ISSUE TITLE
ld: library not found for -lFirebaseCore when build app on ios

### ISSUE THREAD

**Issue by LaQuang** [invertase/react-native-firebase#4167]
In Android, I get notification in quit, background, foreground state. They are Ok. 

But in Ios when building, I get the Error: ld: library not found for -lFirebaseCore

My packgage.json:
"@react-native-firebase/app": "^8.4.0",
"@react-native-firebase/messaging": "^7.8.1",

**Comment by mikehardy** [comment]
Looks like a pod install was not run perhaps?
This is a project-specific problem though, the module is building and running fine on iOS, you may use this script to generate a throwaway demonstrator that proves it is working - https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

The problem will be somewhere in the difference between that example project generated by the script, and your project

Can you try it and post the differences you find? Might help future people

**Comment by mikehardy** [comment]
Also - I forgot to recommend it previously, but sometimes a `npx react-native-clean-project` flushes out iOS build problems.

**Comment by LaQuang** [comment]
Thanks @mikehardy , I have just test your project, it run perfectly. I will try investigate and post the differences between your project and mine here when I come back from holiday.

**Comment by LaQuang** [comment]
Hi @mikehardy I fixed the Error ld: library not found for -lFirebaseCore by upgrading to the newest Xcode version: 11.7 and set the  New Build System in the Workspace Settings of the Xcode. My previous setting was: Legacy Build System.

**Comment by mikehardy** [comment]
Ah yes - it used to be legacy build system was needed but it has been a long while since that was the case. New build system all the way (and much faster!)
