### ISSUE TITLE
[!] There are multiple dependencies with different sources for `RNFirebase` in `Podfile`:

### ISSUE THREAD

**Issue by kid43** [invertase/react-native-firebase#4178]
[!] There are multiple dependencies with different sources for `RNFirebase` in `Podfile`:

- RNFirebase (from `../node_modules/react-native-firebase/ios`)
- RNFirebase (from `../node_modules/react-native-firebase`)

**Comment by mikehardy** [comment]
This contains nothing of the template. Please open a new issue and follow the template so we may help.
