### ISSUE TITLE
Local notification not showing in background

### ISSUE THREAD

**Issue by irsyadmhdilham** [invertase/react-native-firebase#418]
Hello
I'm having a problem where the local notification doesn't show in background
as for the foreground is showing when I set a property `show_in_foreground: true`

here is my code 
```
firebase.messaging().createLocalNotification({
   title: 'My app',     
   body: 'Hello world',
   icon: 'ic_launcher',
   priority: 'high',
   click_action: 'ACTION',
   show_in_foreground: true,
   sound: 'default',
   opened_from_tray: true
})
```
What are the property that I missing?

react native : 0.47
platform: android
react-native-firebase: v0.2
gradle build tool: 23.0.1

**Comment by Shinichi52** [comment]
Hi guy,
I have same problem. I can't show local notification when upgrade to v2. it's work fine with v1 :(
here is my code:
```sh
  firebase.messaging().createLocalNotification({
                        body: 'body',
                        show_in_foreground: true,
                        title: 'title',
                        local_notification: true,
                        priority: 'high'
                    });
```
react native : 0.47
platform: ios
react-native-firebase: v2.1.4

**Comment by kishanj918** [comment]
@irsyadmhdilham  on which phone you are testing?

**Comment by irsyadmhdilham** [comment]
@kishanj918 Xiaomi Redmi 4X

**Comment by kishanj918** [comment]
can you check that switch is enabled in permissions > Autostart > Your app?

**Comment by Shinichi52** [comment]
@kishanj918 can you run on IOS?

**Comment by kishanj918** [comment]
I haven't integrated cloud messaging in ios yet. I did admob.

**Comment by irsyadmhdilham** [comment]
@kishanj918 I've did switch the permissions in autostart. But still doesn't work 😭

**Comment by Shinichi52** [comment]
@irsyadmhdilham it's working fine for me on android. But on IOS it doesn't work.

**Comment by sirstevensu** [comment]
+1 i have some issue

**Comment by chrisbianca** [comment]
Thanks for reporting.  We're aware of lots of issues with notifications and will be addressing them all as part of the v3.2.0 release stream.  Please see https://github.com/invertase/react-native-firebase/issues/595 for updates.

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)

**Comment by rajeshzmoke** [comment]
how do i make local notification collapsible ? i cant make it work ..and its flooding the notification bar

`Cloud function`:

          let payload = {
            notification: {
              title: name,
              body: "New Anonymous message", //msg
              sound: "default",
              badge: "1",
              tag: "red"
            },
            data: {
              collapse_key: "red", //remote noti
              groupName: name,
              groupKey: groupkey
            }
          };
          const options = {
            collapseKey: "red",
            contentAvailable: true,
            priority: "high",
            timeToLive: 60 * 60 * 24
          };
          return admin.messaging().sendToTopic(myTopic, payload, options);



```
messaging.onMessage(payload => {
messaging.createLocalNotification({
      ...payload.fcm,
       local_notification: true,
      show_in_foreground: true,
      collapseKey: 'red'
       priority: 'high',
      tag: 'red'
    });
});
```
