### ISSUE TITLE
[🐛] firestore.onSnapshot ignoring firebase rules.

### ISSUE THREAD

**Issue by Solerx** [invertase/react-native-firebase#4185]
Hello;

When i use .get() it works as it has to but when using onSnapshot im getting all the data and then the error firestore/permission-denied wich is useless since already got data.

## Issue

firestore.collection('items').limit(15)
      .orderBy('cdate', 'desc')
      .get()

firestore.collection('items').limit(15)
      .orderBy('cdate', 'desc')
      .onSnapshot()

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
#  "@react-native-firebase/app": "^8.2.0",
    "@react-native-firebase/auth": "^8.2.0",
    "@react-native-firebase/firestore": "^7.7.0",
    "@react-native-firebase/messaging": "^7.4.2",
    "@react-native-firebase/storage": "^7.2.2",
    "@react-navigation/bottom-tabs": "^5.7.2",
    "@react-navigation/drawer": "^5.8.6",
    "@react-navigation/native": "^5.7.1",
    "@react-navigation/stack": "^5.7.1",
    "react": "16.13.1",
    "react-native": "0.63.1",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [ x] I'm using Pods and my Podfile looks like:

```ruby
# require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'app' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"

  target 'app' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'app-tvOS' do
  # Pods for app-tvOS

  target 'app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by andersonaddo** [comment]
Can you add your package.json? We need to know the versions of our packages that you're using.

**Comment by andersonaddo** [comment]
Seems to be an issue related to caching

https://stackoverflow.com/questions/52477687/cloud-firestore-security-rules-are-ignored-when-using-the-function-onsnapshot

https://github.com/invertase/react-native-firebase/issues/623

https://github.com/googleapis/google-cloud-go/issues/1029

https://github.com/firebase/firebase-ios-sdk/issues/469

**Comment by mikehardy** [comment]
So the test here is: if you completely clear data+cache on the device and uninstall the app, then the next time you install it, do you still see the unexpected / should-not-be-authorized data? The caching hypothesis means that with a clean install you should see the rules applied correctly. With possibly-cached data you might possibly see the cached data on read

**Comment by Solerx** [comment]
So i will need to clear cache after a user logout or is set to inactive so he wont be able to access that data? How can i clear cache when user logs out?

**Comment by Solerx** [comment]
Ok, it seems it was a cache data as you guys said. Thank you for your help. I will need to clear cache then when user logs out.

**Comment by mikehardy** [comment]
@Solerx I will be curious to see what works with regard to clearing cache - is it sufficient to setOfflinePersistence to false? Or do you have to setCacheSize to 0, or ? It seems to me that if you use the firestore APIs toggle offline persistence off and on it *should* work, but I'm not sure? Other users may run into this in the future though, so a confirmed working solution would be a help

Cheers

**Comment by Solerx** [comment]
@mikehardy I just set the store to its initials and that worked pretty well for me. Now im trying to Archive and send to TestFlight but im getting a error Use of unresolved identifier 'FIRApp' in   if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }

**Comment by mikehardy** [comment]
'npx react-native-clean-project' I think. That's the most fundamental firebase integration step, it's practically the first thing in the docs, it should work
