### ISSUE TITLE
Markdown issues in Android Docs

### ISSUE THREAD

**Issue by NathHorrigan** [invertase/react-native-firebase#419]
Hello!! Thought I should let you know there is some incorrect markdown at https://invertase.io/react-native-firebase/#/installation-android?id=_2-link-rnfirebase that is causing weird output with code fences. :+1:

**Comment by Salakar** [comment]
Thanks for flagging, think I see what the issue is, will sort tomorrow.

**Comment by Salakar** [comment]
This has been fixed now, may still be cached on your browser - just hard refresh if you need to.
