### ISSUE TITLE
How to access the UserCredential type?

### ISSUE THREAD

**Issue by chancesmith** [invertase/react-native-firebase#4193]
https://github.com/invertase/react-native-firebase/blob/c6e77a8c34c632eba119dc30a320675a142dabce/packages/auth/lib/index.d.ts#L319

I'm trying to extend using `UserCredential`:
```
import {UserCredential} from '@react-native-firebase/auth';
```

**Comment by mikehardy** [comment]
I believe:

```typescript
import { FirebaseAuthTypes } from '@react-native-firebase/auth';
```

Then `FirebaseAuthTypes.UserCredential` ?

I don't do that with this specific one (I just get the credential as a return value and typescript assigns the type to the variable without me having to name it, but I do it with related types in the same exported namespace:

```typescript
    additionalUserInfo?: FirebaseAuthTypes.AdditionalUserInfo
```

and that works, so this one should work
