### ISSUE TITLE
Phone auth can lose verificationId with no way of getting it back

### ISSUE THREAD

**Issue by TikiTDO** [invertase/react-native-firebase#420]
### Issue

When using firebase phone authentication, the app can lose a `verificationId` in between calls to `signInWithPhoneNumber` and `_confirmVerificationCode`. 

This is touched upon in [this comment](https://github.com/invertase/react-native-firebase/tree/master/android/src/main/java/io/invertase/firebase/auth#L632).

Since `signInWithPhoneNumber` already passes the `verificationId` to JS-land, it would be nice to have an alternate validation function such as `_confirmVerificationCodeWithId` so that this lib would not have to worry about managing that part of the life cycle.

I can submit a PR for Android part, and I could half-ass it for iOS, but I figured it would be better to ask.

### Environment

1. Application Target Platform: Android (Though likely affects both)

2. Development Operating System: Linux

3. Build Tools: Android Oreo

4. React Native version: 0.48.3

5. RNFirebase Version: 3.0.0-alpha.3

6. Firebase Module: auth

**Comment by chrisbianca** [comment]
@TikiTDO See: https://github.com/invertase/react-native-firebase/issues/119#issuecomment-330151028 for information about what we're proposing in terms of a more bespoke API.

We're aware of the fact that the verificationId can be lost as part of the lifecycle of the apps in Android - though this is already handled in iOS.

You can already make use of the verificationId yourself using a PhoneCredential directly:

```
const credential = firebase.auth.PhoneAuthProvider.credential(verificationID, authCode);
return firebase.auth().signInWithCredential(credential)
```

Closing this as we'll pick up as part of https://github.com/invertase/react-native-firebase/issues/119
