### ISSUE TITLE
[🐛] 🔥 FirebaseAnalyticsModule methods break the app on error

### ISSUE THREAD

**Issue by JoseLion** [invertase/react-native-firebase#4207]
## Issue

Hi!

Thanks in advance for taking the time to read this issue 🙂 

In the Analytics module, all the methods in the class [FirebaseAnalyticsModule](https://github.com/invertase/react-native-firebase/blob/8830fc27dda5125cc5e40dc1984aefd05afe9e64/packages/analytics/lib/index.js#L61) are expected to return a promise (because they use a native module I think). However, all validations in those methods throw errors directly instead of returning a rejected promise. So if an error occurs before the native module is called, the app breaks even if the method called is controlled with a `.catch(..)`. For instance:

```ts
import analytics from "@react-native-firebase/analytics";

export function logMyEvent(): Promise<void> {
  return analytics().logEvent("my_awesome_event!!!")
    .catch(error => {
      reportErrorAndContinue("Analytics", error);
    });
}
```

In the snippet above the `.logEvent(..)` method will fail because of the `name format validation`. However, it will never reach the `.catch(..)` and the app will break instead of just rejecting the promise.

<img width="348" alt="Screen Shot 2020-09-03 at 18 16 12" src="https://user-images.githubusercontent.com/3087228/92182546-8f0bee80-ee11-11ea-84d5-153761e9edbf.png">

**PS:** I'm not sure if this only happens on the Analytics module. It may be an issue in other modules too

---

### Javascript

<details><summary>Click To Expand</summary>
<p>
```js
logEvent(name, params = {}) {
    if (!isString(name)) {
      throw new Error("firebase.analytics().logEvent(*) 'name' expected a string value.");
    }

    if (!isUndefined(params) && !isObject(params)) {
      throw new Error("firebase.analytics().logEvent(_, *) 'params' expected an object value.");
    }

    // check name is not a reserved event name
    if (isOneOf(name, ReservedEventNames)) {
      throw new Error(
        `firebase.analytics().logEvent(*) 'name' the event name '${name}' is reserved and can not be used.`,
      );
    }

    // name format validation
    if (!isAlphaNumericUnderscore(name)) {
      throw new Error(
        `firebase.analytics().logEvent(*) 'name' invalid event name '${name}'. Names should contain 1 to 32 alphanumeric characters or underscores.`,
      );
    }

    // maximum number of allowed params check
    if (params && Object.keys(params).length > 25) {
      throw new Error(
        "firebase.analytics().logEvent(_, *) 'params' maximum number of parameters exceeded (25).",
      );
    }

    return this.native.logEvent(name, params);
  }
```

**Shouldn't the validations here return `Promise.reject(new Error(...))` instead?**

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `"@react-native-firebase/app": "^8.4.1"`
  - `"@react-native-firebase/analytics": "^7.6.1"`
- **`Firebase` module(s) you're using that has the issue:**
  - `analytics`
- **Are you using `TypeScript`?**
  - `Y` & `3.9.2`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Interesting.
I think this happens everywhere.
Have you tried making the function async and doing the whole thing in a try/catch?

That's the more typical style and I don't believe suffers the bubbling-up-and-crashing problem?

**Comment by JoseLion** [comment]
@mikehardy thank you for your quick response 🙂

That's right, making the function async and wrapping everything on a try/catch works, but only because of the try/catch. What I mean is that it will still break if we try to use any of these methods within a promise chain.

Personally, I prefer using the functional approach of promises rather than the imperative `async/await + try/catch` style (actually, it's a good practice policy in the company I work since we embrace functional programming 😬). So, to work around the `try/catch` we'll need to create abstractions of each method we need to use (or some kind of wrapper function).

I understand this may be a big change if it's happening everywhere 😅 so I wanted to know if we can expect a change in future versions? Just so we can check which is the best approach for us 🙂 

Thanks!

**Comment by mikehardy** [comment]
async/await is the way to go in javascript as far as I know, although I know this is religious territory

I can't imagine this changing, personally.

On the plus side, these are the most basic of formatting errors. There's no way they should get past development. A global catch (similar to what crashlytics does) may be sufficient in the since that failing one of these checks that throws immediately is akin to a debug-build assert

**Comment by mikehardy** [comment]
You're in Quito? Small world :-). If you see anything where we are not behaving like https://github.com/firebase/firebase-js-sdk/ - that's actually the trigger for us to alter API (even with a semver major / breaking change if necessary) but it was my understanding that they throw Errors immediately too for validation failure, reserving promise reject for execution failure. I also find it a bit strange actually but because my work project is all async/await it just never mattered personally :-)

**Comment by JoseLion** [comment]
Yeah, I noticed you're in Cuenca, such a small world 😅 
Thank's for the link I'll take a look, it makes sense to stick to the SDK, I think this could be closed for now. Thanks again for the help! 🙂
