### ISSUE TITLE
[📚] How to Help????

### ISSUE THREAD

**Issue by Wanderson77** [invertase/react-native-firebase#4210]
Hello guys, I would like to better understand this project and how it works and how.
I could assist in the development and preparation and / or translation of the documentation.

**Comment by mikehardy** [comment]
HI there! That's great!

We develop in a typical open source fashion where you could:

1.  post an issue describing a deficiency in the functionality of the module and a rough sketch on how you would fix it.
1.  we (and any interested community members) would look at the issue and discuss the solution design, or if you wanted to just get started (running the slight risk there is a design issue, but allowing progress to simply begin) you could go right to:
1.  you would use the design to alter the code and propose a PR
1.  we (and any interested community members) review the PR and look at the automated testing results and contributed feedback
1.  you integrate the feedback, this step and the above repeat until it's in good shape
1.  we merge and release

When it comes to creating a PR, the best way to do it is to check out the repo locally and look at the [README in the "tests" app ](https://github.com/invertase/react-native-firebase/blob/master/tests/README.md) - development here is always done against the tests app, by altering the code and then adding a corresponding "e2e" test to the test suite and running it. Here is an example #3814 - it shows the addition of a new API, with the corresponding changes to the javascript, the types, the Java/Objective-C native code, and a corresponding e2e test.

Documentation translation is not a thing - the docs are in English and will remain in English

However, we can always use help in tracking the API changes introduced by Google in the underlying Firebase APIs. 

Specifically right now the [machine learning module](https://developers.google.com/ml-kit/migration) and the [analytics modules](https://firebase.google.com/support/release-notes/android#analytics_v17-3-0) have had major API changes in the upstream modules, and we have not adapted to them yet, it would be great to get help in this area
