### ISSUE TITLE
Cancel uploads to firebase storage

### ISSUE THREAD

**Issue by meliodev** [invertase/react-native-firebase#4211]
Hello guys,
I am using react-native-firebase 5.6.0. I tried to use uploadtask.cancel(), but I got 'Cancel() is not supported by react-native-firebase'. Is there a promising PR to solve that or maybe a work around to this operation ?

**Comment by mikehardy** [comment]
react-native-firebase v5 will receive no support - you need to upgrade to current stable versions.

Current stable appears to support cancel: 
- https://rnfirebase.io/reference/storage/task#cancel
- https://github.com/invertase/react-native-firebase/blob/791bc9a7faa17b05845865ec099e1deb64780feb/packages/storage/lib/StorageTask.js#L229-L231
- https://github.com/invertase/react-native-firebase/blob/791bc9a7faa17b05845865ec099e1deb64780feb/packages/storage/e2e/StorageTask.e2e.js#L756-L852
