### ISSUE TITLE
[🐛] you attempted to use a firebase module that is not installed firebase.app() 

### ISSUE THREAD

**Issue by Soufiane-lab** [invertase/react-native-firebase#4219]
I am trying to link my react-native app to firebase and work on the auth module.

I followed the steps of the installation in https://rnfirebase.io/

It works when I run `npx react-native run-android`

But when I use expo start to work on the pre-production app I always get the error `you attempted to use a firebase module that is not installed firebase.app()` 

I tried the minimal app template with `expo` and I am having the same problem (I was trying to solve this problem for more than 3 days by building and re-building this project)

**Comment by andersonaddo** [comment]
I don't think you can use this package with expo.
https://rnfirebase.io/#expo

**Comment by Soufiane-lab** [comment]
> I don't think you can use this package with expo.
> https://rnfirebase.io/#expo

Thank you for mentioning that, I didn't understand well this last section.

I realize a small problem with the menus in the documentation, sometimes the links don't work. It will be great if you solve this issue

**Comment by mikehardy** [comment]
@Soufiane-lab I have noticed the linking issue in the website as well! For some reason the navigation bar becomes incorrectly rooted sometimes and you have to force it all the way back to rnfirebase.io then you can navigate again. I'll look into that hopefully early next week if @andersonaddo (who fixed the last website issue, actually :-) ) doesn't beat me to it
