### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by cameronb23** [invertase/react-native-firebase#422]
### Issue

When attempting to build and push to TestFlight with RNFirebase through CocoaPods, I get this error: 

`/Users/student/node/Dropday/node_modules/react-native-firebase/ios/RNFirebase/admob/RNFirebaseAdMobRewardedVideo.h:4:9: 'React/RCTBridgeModule.h' file not found`

I do know that this may have something to do with React-Native's breaking change, or at least that is what my research suggests. I have tried re-installing and changing my build settings to no avail. I am not sure exactly why it would be building this module though as I am not using it in my project.

### Environment

1. Application Target Platform: Both(but iOS through TestFlight currently main objective)

2. Development Operating System: macOS Sierra 10.12.6 

3. Build Tools: Xcode v8.3.3

4. React Native version: 
react-native-cli: 2.0.1
react-native: 0.47.1

5. RNFirebase Version: 2.2.0

6. Firebase Module: Authentication

**Comment by SamMatthewsIsACommonName** [comment]
Hey just double to check are you bringing in the react pods as part of your setup?

````
pod 'React', :path => '../node_modules/react-native', :subspecs => [
'BatchedBridge', # Required For React Native 0.45.0+
'Core',
# Add any other subspecs you want to use in your project
]
````
That RNFirebaseAdMobRewardedVideo file has the new needed syntax (#import <React/RCTBridgeModule.h>) that was the breaking change in RN so it shouldn't be that I would imagine...

**Comment by cameronb23** [comment]
Took me a while to get it figured out, but it seemed to be a weird mixture of my build phases/native modules and my Pods setup. Finally figured it out after a bunch of trying and retrying. Thanks 👍
