### ISSUE TITLE
Xcode build bug

### ISSUE THREAD

**Issue by davisuga** [invertase/react-native-firebase#4224]
I'm having some problems with google dependencies for react-native-firebase 
Lexical or Preprocessor Issue:
BoringSSL-GRPC
ios/Pods/BoringSSL-GRPC/src/crypto/x509/x_x509a.c:59:10: 'openssl_grpc/asn1t.h' file not found
x_x509a.c
I'm using the lastest version of macOS Catalina and Xcode

**Comment by andersonaddo** [comment]
Looks like a problem with a cocopods dependency, I would recommend clearing Xcode cache, calling `npx react-native-clean-project` and reinstalling pods. 

Follow issue template for more detailed assistance.

**Comment by mikehardy** [comment]
Very important to note that bug reports with "latest version of" are not useful. There are some of us testing with Xcode12beta5 for instance, is that what you meant? Most likely not. Specify exact versions when asking for help, for best results. But hopefully react-native-clean-project cleans things out for you

**Comment by davisuga** [comment]
> Looks like a problem with a cocopods dependency, I would recommend clearing Xcode cache, calling `npx react-native-clean-project` and reinstalling your project's pods. 
> 
> Follow issue template for more detailed assistance. 

Thanks, it worked :)
