### ISSUE TITLE
[🐛] 🔥 Broadcast of Intent ANRs on Android 10

### ISSUE THREAD

**Issue by floelm** [invertase/react-native-firebase#4237]
## Issue

I am getting a lot of ANRs on Android 10 and all of them have the same origin which is: 

**Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11000010 pkg=<mypackage>cmp=<mypackage>/io.invertase.firebase.messaging.ReactNativeFirebaseMessagingReceiver (has extras) }**

firebase messaging SDK version: 
`implementation "com.google.firebase:firebase-messaging:20.2.4"`

firebase messaging npm version:
`"@react-native-firebase/messaging": "^7.6.1"`

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `7.6.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You can do anything in the handler as we hook to your app code there, and it can be quite slow. It could be your entire app startup. Have you turned on strict mode in debug builds and seen what is slow?

**Comment by mikehardy** [comment]
They tighten ANR restrictions with almost every release (API11 might be even worse?) and I'm not surprised at all the message receiver causes problems. If the app is not resident in memory at all, that's the exact time that a complete app cold boot would happen, followed by all the handling logic. It's exactly when this would/should happen

**Comment by floelm** [comment]
Closing this issue as it is most likely not related to the package
