### ISSUE TITLE
Could not determine the dependecies of task ':app :installDebug'

### ISSUE THREAD

**Issue by Samyak-shah** [invertase/react-native-firebase#4238]
Hi I am new to both react native and firebase. I was using the npx @react-native-community/cli init --template=@react-native-firebase/template <project name> to set up a new firebase project with dependencies taken care of in the template. 

I keep getting this error. Please help me with understanding what's going wrong- 

  Configure project :react-native-firebase_app
:react-native-firebase_app:firebase.bom using default value: 24.1.0
:react-native-firebase_app package.json found at C:\Users\<user>\Big React folder\React Native\Firebase App\memo\memo\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_app:version set from package.json: 6.7.1 (6,7,1 - 6007001)
:react-native-firebase_app:android.compileSdk using custom value: 29
:react-native-firebase_app:android.targetSdk using custom value: 29
:react-native-firebase_app:android.minSdk using custom value: 16
:react-native-firebase_app:reactNativeAndroidDir C:\Users\<user>\Big React folder\React Native\Firebase App\memo\memo\node_modules\react-native\android

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:installDebug'.
> java.io.IOException: The filename, directory name, or volume label syntax is incorrect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by mikehardy** [comment]
Your react native firebase versions are terribly outdated. Try this https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

It will work
