### ISSUE TITLE
Google-services.json not working with flavors.

### ISSUE THREAD

**Issue by Acetyld** [invertase/react-native-firebase#4246]
Hey there!
Normally we put the google-services-json inside the /android/app/src/flavourname.
But RNFirebase seems its not picking it up.

Any clue on how to add this or support it?

**Comment by mikehardy** [comment]
Works for me?

```
mike@isabela:~/work/Kullki/ksocialscore/packages/public-app (rebranding) % find . | grep google-services.json
./android/app/src/qa/google-services.json
./android/app/src/staging/google-services.json
./android/app/src/prod/google-services.json
./android/app/src/dev/google-services.json
```

**Comment by mikehardy** [comment]
If you can provide the information we need (i.e., the template information we requested) and a reproduction we can see, but this definitely works for me, for what it's worth - this is my day-in/day-out work project I posted above

**Comment by Acetyld** [comment]
So its not working somehow. Authentication, firestore is working fine. But.. analytics is giving "Failed to retrieve FireBase instance ID"

The logEvents are not showing up in DebugView and every logEvent gives the Failed to retrieve firebase instance..

And i cant get the application verified in the firebase settings, it keeps asking to set SDK.

![afbeelding](https://user-images.githubusercontent.com/55088242/92966970-c36a5500-f478-11ea-8afd-150867dcf400.png)

` analytics().logEvent('test', {
      id: 3745092,
      item: 'mens grey t-shirt',
      description: ['round neck', 'long sleeved'],
      size: 'L',
    })`

I tried the following:

- Triple checked
- Disable Hermes
- Added Multidex
- `apply plugin: 'com.google.gms.google-services' // <- Add this line` added to the app/build.gradl;e
- classpath 'com.google.gms:google-services:4.3.3' added to the build.gradle.
- Updated EVERYTHING
- Tried with new firebase projects
- Used different types of logEvetns
