### ISSUE TITLE
Analytics not working with flavors

### ISSUE THREAD

**Issue by Acetyld** [invertase/react-native-firebase#4248]
So its not working somehow. Authentication, firestore is working fine. But.. analytics is giving "Failed to retrieve FireBase instance ID"

The logEvents are not showing up in DebugView and every logEvent gives the Failed to retrieve firebase instance..

And i cant get the application verified in the firebase settings, it keeps asking to set SDK.

![afbeelding](https://user-images.githubusercontent.com/55088242/92966970-c36a5500-f478-11ea-8afd-150867dcf400.png)

` analytics().logEvent('test', {
      id: 3745092,
      item: 'mens grey t-shirt',
      description: ['round neck', 'long sleeved'],
      size: 'L',
    })`

I tried the following:

- Triple checked the package name
- Disable Hermes
- Added Multidex
- `apply plugin: 'com.google.gms.google-services' // <- Add this line` added to the app/build.gradl;e
- classpath 'com.google.gms:google-services:4.3.3' added to the build.gradle.
- Updated EVERYTHING, react, react native other packages etc..
- Tried with new firebase projects
- Used different types of logEvetns

**Comment by mikehardy** [comment]
Why do you persist in ignoring our issue template?

**Comment by Acetyld** [comment]
Tbh instantly deleted the template, its a bad habit, as of writing this message i am filling in the template

**Comment by mikehardy** [comment]
Try this https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

And yes, that's a terrible habit. Instantly deletes my desire to help :shrug:

**Comment by Acetyld** [comment]
@mikehardy currently working on windows. We switched to only android because soundboards are a pain in the ass on iOS and copyright etc.. We currently have 11 in playstore with roughly 1mil users. I made a new post btw with the correct format ^_^ and all the info you asked for
