### ISSUE TITLE
Push.then is a promise, not the promise's then method

### ISSUE THREAD

**Issue by Alazoral** [invertase/react-native-firebase#425]
### Issue

`database.ref('things').push('something').then` seems to return a Promise rather than the actual then method. The workaround is to use `then.then(() => ...)`

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode 9

4. React Native version: 0.46.4

5. RNFirebase Version: 3.0.0-alpha.3

6. Firebase Module: database

**Comment by Salakar** [comment]
Thanks for flagging, have pushed up a version that should fix this, can your try `3.0.0-alpha.4` and get back to me.

**Comment by Salakar** [comment]
Closing due to no response - seems to be working on tests now as well.
