### ISSUE TITLE
[firestore/unknown] an unknown error occured

### ISSUE THREAD

**Issue by deepakverma4** [invertase/react-native-firebase#4254]
I'm getting this error randomly in slow network speed. Please tell me how can i fix this?

**Comment by mikehardy** [comment]
I believe this error is expected when network connections break - have you searched in the upstream repositories (firebase-ios-sdk / firebase-android-sdk on github) for related information?

**Comment by deepakverma4** [comment]
@mikehardy sorry i don't where to search and what to search. can you please guide me where to go from here?

**Comment by mikehardy** [comment]
You included none of the required information in the template we would use to help, so I don't have any good ideas for troubleshooting other than cloning our repo and the the upstream repo for the operating system you have the problem with and search for the error. Then trace how it can happen
