### ISSUE TITLE
'_reactNativeFirebase2.default.auth()' is undefined

### ISSUE THREAD

**Issue by plflanagan** [invertase/react-native-firebase#426]
### Issue
I have followed the iOS initialization directions a few times now and am encountering the same issue:
![simulator screen shot sep 20 2017 7 04 53 am](https://user-images.githubusercontent.com/9424428/30645181-1d9b9e36-9dd2-11e7-8ed3-d459c0b0f762.png)

Code at the LaunchScreen:
```
import firebase from 'react-native-firebase'
...
firebase.auth().onAuthStateChanged((user) => {
          if (user) {
            navigate('MainScreen')
          }
        })
...
```

The `reactNativeFirebase2` seems odd to me. I had been using the web version of firebase previously; so I don't know if that is where the 2 is coming from. I have tried removing the original firebase as well as add it back in but I always run into the same issue

Note, I am using yarn rather than npm because npm was literally destroying my project for some reason. yarn has been working fine with all other packages up till now; so I don't know if that might be causing an issue.

### Environment

1. Application Target Platform: iOS, first

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode 8.3.3, Simulator v10

4. React Native version: 0.45.1
react-native-cli: 2.0.1

5. RNFirebase Version: 2.2.1

6. Firebase Module: auth, if not everything.

**Comment by Ehesp** [comment]
You first need to ensure you're initializing firebase. Make sure you're on the v2 docs and not v3!

**Comment by plflanagan** [comment]
What if I would like to use v3?

**Comment by chrisbianca** [comment]
v3 is still in alpha, if you're comfortable with the fact there may be a few issues, then follow the instructions here: https://invertase.io/react-native-firebase/#/

The latest alpha is v3.0.0-alpha.5
