### ISSUE TITLE
[🐛] The logScreenView is not displayed

### ISSUE THREAD

**Issue by yuheiakita** [invertase/react-native-firebase#4260]
## Issue
I would like to know about this issue.
The logScreenView is not reflected in the Firebase DebugView.
I am currently getting the logEvent that I am using for other purposes correctly.
Ideally, I would like to get the ScreenName as well as screen_view.

The logScreenView used
```
import analytics from '@react-native-firebase/analytics';


useEffect = (() => {
 analytics().logScreenView({
  screen_class: 'ScreenClass',
  screen_name: 'ScreenName',
});
})
```

or
```
import analytics from '@react-native-firebase/analytics';


componentDidMount() {
 analytics().logScreenView({
  screen_class: 'ScreenClass',
  screen_name: 'ScreenName',
});
}
```
screen_view is shown, but the class,name is not shown
![xcode_settings](https://user-images.githubusercontent.com/46808542/93175243-45ed6000-f76a-11ea-9f10-2043f0c22c38.png)
![DebugView](https://user-images.githubusercontent.com/46808542/93175251-48e85080-f76a-11ea-819f-3da114bd87b3.png)
---

## Project Files
react-native-cli: 2.0.1
react-native: 0.62.2
yarn 1.22.4
pod 1.9.3
@react-native-firebase/analytics: ^7.6.1

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Pretty empty with regard to the template information we would normally want to see but it does look like most information is here, I can make some guesses but can't be certain

You specifically note that you enabled debug logging, but do not include any of the Xcode console debug logging output. What did it look like?

What did it look like on Android with android's analytics debugging enabled and did it work?

Can you reproduce with the native APIs directly? https://github.com/firebase/quickstart-ios/tree/master/analytics

Does it show up in the regular analytics, and is just missing from DebugView?

**Comment by yuheiakita** [comment]
Thank you for message.
I want to track which screen the user used.
I'm showing screen_view, but I don't know what screen it is.
The screen name doesn't show up in normal analytics either.

The native API displayed successfully.
Does Xcode show anything?
I haven't used Android yet.
