### ISSUE TITLE
[🐛] Invariant Violation: Native module cannot be null. - RNFBNativeEventEmitter

### ISSUE THREAD

**Issue by mechazod** [invertase/react-native-firebase#4265]
## Issue

I had tried to use the migration from v5 to [latest release](https://rnfirebase.io/migrating-to-v6) and it works fine. But my current concern is the `jest --coverage` test, which failing on my end.

##### react-native
```
"react": "16.9.0",
"react-native": "0.61.5",
```

##### package.json>dependencies:
```
"@react-native-firebase/analytics": "^7.6.2",
"@react-native-firebase/app": "^8.4.2",
"@react-native-firebase/crashlytics": "^8.4.4",
```
##### screenshot
<img width="910" alt="Screen Shot 2020-09-17 at 11 17 32 AM" src="https://user-images.githubusercontent.com/16739905/93416016-6850bc00-f8d7-11ea-9b2d-646928f4a4d2.png">

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x ] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:
- [x] Autolink in Podfile.lock on installation `pod install`
```ruby
Installing Firebase (6.30.0)
Installing FirebaseAnalytics (6.7.2)
Installing FirebaseCore (6.10.0)
Installing FirebaseCoreDiagnostics (1.5.0)
Installing FirebaseCrashlytics (4.4.0)
Installing FirebaseInstallations (1.7.0)
Installing RNFBApp (8.4.2)
Installing RNFBAnalytics (7.6.2)
Installing RNFBCrashlytics (8.4.4)
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
https://github.com/invertase/react-native-firebase/issues/4081

**Comment by kevinlin505** [comment]
Hey @mechazod any lucks on this one? I am getting the exact same issue and the reference on #4081 doesn't work for me.

**Comment by mechazod** [comment]
@kevinlin505 What solution I did was installing the new version of Firebase v6+ via `yarn`, then I removed some conflicting libraries and back again after successful install. Also removed all old firebase v5.

**Comment by michaelgill1969** [comment]
As mentioned by @mikehardy 
> #4081

mocking NativeEventEmitter worked for me,

```
jest.mock('react-native/Libraries/EventEmitter/NativeEventEmitter')
```

**Comment by mikehardy** [comment]
You may also like this, it's slowly grown more full-featured and it is what we use internally when we jest test the module itself

https://github.com/invertase/react-native-firebase/blob/master/jest.setup.ts
