### ISSUE TITLE
[📚] Initialise secondary app: remind to use different configs for android/ios

### ISSUE THREAD

**Issue by tristanbrandt014** [invertase/react-native-firebase#4272]
## Documentation Feedback

Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:

[Link to section](https://rnfirebase.io/app/usage#initializing-secondary-apps)

It wasn't immediately obvious that I was supposed to use `Platform.select` to use the correct configs for android/ios.

Suggestion: Add a section to highlight that you're supposed to use the relevant config for the platform
```typescript
import firebase from '@react-native-firebase/app';
import { Platform } from "react-native";

// If you're using multiple platforms 
const androidCredentials = {
  clientId: '',
  appId: '',
  apiKey: '',
  databaseURL: '',
  storageBucket: '',
  messagingSenderId: '',
  projectId: '',
};

const iosCredentials = {
  clientId: '',
  appId: '',
  apiKey: '',
  databaseURL: '',
  storageBucket: '',
  messagingSenderId: '',
  projectId: '',
};

const credentials = Platform.select({android: androidCredentials, ios: iosCredentials})

const config = {
  name: 'SECONDARY_APP',
};

await firebase.initializeApp(credentials, config);
```

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
PRs happily accepted :-), there's an edit button on the top right of every page and GitHub has a nice web-based flow for docs updates, give it a whirl and I'll merge it in
