### ISSUE TITLE
RNFIREBASE collection PATH not working as working in React firebase Web based library.. 

### ISSUE THREAD

**Issue by shtaimoortariq** [invertase/react-native-firebase#4277]
## Issue

Describe your issue here

---
I want to Get the deep down collection in collections like files/docId/files/docId/files
i want to Get and Set the Dataa with path on RNFirestore it is working like a charm in React Web but it doesn't work in Mobile platfrom 
My Code on Web Which is barely a one line code where i get and the data with desired path 
this is my Web Code : 
/files/wZQfo4v0NAhcMyzjXehG/sd9SClB192KoKaYjnvKN this is my REF variable which i am spliting in next Line
const upd = ref.split('/')
    upd.splice(0, 2)
    const result = upd.join('/files/')
    console.log(upd, 'AFTER SPLIT AND SPLICE')
    upd in console.log ["wZQfo4v0NAhcMyzjXehG", "sd9SClB192KoKaYjnvKN"] "AFTER SPLIT AND SPLICE"
    let newRef = '/files/'
    newRef = newRef.concat(result)
newRef would look like this after concat /files/wZQfo4v0NAhcMyzjXehG/files/sd9SClB192KoKaYjnvKN
const documentReference = db.collection(upd.length > 0 ? `${newRef}/files` : 'files').doc()
my newRef variable is /files/docid this is how i am setting data on my web but on mobile i have to make it like chain to the collection where it is consuming way more than 50 lines of codes 
this is my deepest hierarchy where i have to post this is just when we are on the 7th child of collection files (documentRef = db
          .collection('files')
          .doc(refArray[0])
          .collection('files')
          .doc(refArray[1])
          .collection('files')
          .doc(refArray[2])
          .collection('files')
          .doc(refArray[3])
          .collection('files')
          .doc(refArray[4])
          .collection('files')
          .doc(refArray[5])
          .collection('files')
          .doc(refArray[6])
          .collection('files')
          .doc(refArray[7])
          .collection('files')
          .doc())
i just want to shorten my code just as like my web in RNFIREBASE Could anyone please help me on this...? 
### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Opening multiple items for the same issue is not helpful #4273 

Ignoring the template is definitely not helpful

**Comment by shtaimoortariq** [comment]
@mikehardy  Hey Mike just made a new issue which is just elaborated and with mentioned screenshot and evident would you please have a look on that ? it would be thankful
