### ISSUE TITLE
RNFIREBASE Is not Making Document Node on Given Path throwing Error and making Orphaned Node of Documents

### ISSUE THREAD

**Issue by shtaimoortariq** [invertase/react-native-firebase#4279]
![RN](https://user-images.githubusercontent.com/11586628/93607162-658ebd80-f9e2-11ea-9c08-4c515e6c64ee.PNG)
![RNSNAP](https://user-images.githubusercontent.com/11586628/93607168-69224480-f9e2-11ea-804a-f3e2d5fcc345.PNG)
![tempsnip](https://user-images.githubusercontent.com/11586628/93607130-5c9dec00-f9e2-11ea-804e-1a6bb7e0d48a.png)
![tempsnip1](https://user-images.githubusercontent.com/11586628/93608570-3416f180-f9e4-11ea-9b14-0e383ed33daa.png)
![tempsnip1](https://user-images.githubusercontent.com/11586628/93608669-50b32980-f9e4-11ea-9867-5647a8fd9e46.png)

## Issue
I Am Using RNFIREBASE I have Collection of Files and there are Docs in the Files collection i want to make a Sub collection of Files on Selected Doc with Selected DocId  But I Am Getting A Error DocumentPath Must Point At Document Even My Reference To That Document Is Valid with collection Name "files/docId" as you can see in Console.log() and on the Firebase Console the same Id Is Present Which i Gave to Make a SubCollection and make a Document Node On That DocumentNode but instead I Am Getting Error Of DocumentPath must Point At Document But its Making a SubCollection but With a New DocumentNode on Parent node Which is Orphaned.... Please Help me To Solve This Bug.... 

Describe your issue here

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by shtaimoortariq** [comment]
@mikehardy how would i explain to you then i have provided my code snipper error and all the evidence which could be helpful to see whats going on in here..

**Comment by mikehardy** [comment]
You could be on version 5.
"explain" to us by simply filling in the template with required information.

**Comment by shtaimoortariq** [comment]
@mikehardy  i am on latest version check out new issue i opened where i gave all the information you would need
