### ISSUE TITLE
[Question] Best place for setCurrentScreen in RN component lifecycle

### ISSUE THREAD

**Issue by wbattel4607** [invertase/react-native-firebase#428]
Do you have a recommendation for where exactly in the React Native component lifecycle to implement the analytics function `setCurrentScreen`? At first I figured it would go in `componentDidMount` but the docs do not specify whether or not Firebase automatically logs the currently visible screens. If it does, then `componentDidMount` or `componentWillMount` would be a good place to put it, but if it doesn't, then it'd make more sense to put it in `render` so that it is called when the component is being shown- though it would be called multiple times per screen view.

What is the best place to implement this?

**Comment by chrisbianca** [comment]
@wbattel4607 I'd suggest hooking into whichever navigation library you're using.  As you've described, introducing it at the component level doesn't give you accurate screen recording as you'll end up missing things like tab changes, or ending up with duplicate recordings when using the `render` method.

Previously, I've used ExNavigation (not had a chance to switch to react-navigation yet), and with that hooked into Redux, I added some middleware to listen for navigation events and update the screen at that point.

I'd investigate trying to do something similar with whichever (of the many) RN navigation libraries you're using!  Please do let us know how you get on with this. It would be great to add some examples to our docs, so if you're happy to a PR with a working solution for your navigation library would be amazing.

I'll close in the meantime as I've hopefully given you enough direction.  Please re-open if not.
