### ISSUE TITLE
[🐛] Bug Report Title - Xcode 12 compatibility - firebase/messaging

### ISSUE THREAD

**Issue by Spit-Biagio** [invertase/react-native-firebase#4281]
**Summary**
Latest Xcode 12 fails to build while without a module to depend on React-Core directly hence this change is necessary for all native modules on iOS. This change requires React Native 0.60.2 or newer. For more details please check: facebook/react-native#29633 (comment)

**Test Plan**
Use this branch to install with an app running on Xcode 12.

**Comment by mikehardy** [comment]
#4275
