### ISSUE TITLE
[🐛] Bug Report Title - CHANGE ME 

### ISSUE THREAD

**Issue by teammob** [invertase/react-native-firebase#4294]
tdgybdiymxlmrvf/Build/Products/Debug-iphonesimulator -fmodule-map-file=/Users/yucelzengin/Library/Developer/Xcode/DerivedData/firebase22-gmixxwgwuuxfhtdgybdiymxlmrvf/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap -fmodule-map-file=/Users/yucelzengin/React_Projects/firebase22/firebase22/ios/Pods/Headers/Public/FlipperKit/FlipperKit.modulemap -fmodule-map-file=/Users/yucelzengin/React_Projects/firebase22/firebase22/ios/Pods/Headers/Public/yoga/Yoga.modulemap -MMD -MT dependencies -MF /Users/yucelzengin/Library/Developer/Xcode/DerivedData/firebase22-gmixxwgwuuxfhtdgybdiymxlmrvf/Build/Intermediates.noindex/firebase22.build/Debug-iphonesimulator/firebase22.build/Objects-normal/x86_64/AppDelegate.d --serialize-diagnostics /Users/yucelzengin/Library/Developer/Xcode/DerivedData/firebase22-gmixxwgwuuxfhtdgybdiymxlmrvf/Build/Intermediates.noindex/firebase22.build/Debug-iphonesimulator/firebase22.build/Objects-normal/x86_64/AppDelegate.dia -c /Users/yucelzengin/React_Projects/firebase22/firebase22/ios/firebase22/AppDelegate.m -o /Users/yucelzengin/Library/Developer/Xcode/DerivedData/firebase22-gmixxwgwuuxfhtdgybdiymxlmrvf/Build/Intermediates.noindex/firebase22.build/Debug-iphonesimulator/firebase22.build/Objects-normal/x86_64/AppDelegate.o
/Users/XXXX/React_Projects/firebase22/firebase22/ios/firebase22/AppDelegate.m:6:9: fatal error: 'Firebase.h' file not found
#import <Firebase.h>
        ^~~~~~~~~~~~
1 error generated.

**Comment by mikehardy** [comment]
Ignored template.
Probably missing pods.
Demonstration of working initial integration: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh
