### ISSUE TITLE
[🐛] 🔥  FirebaseMLVisionFaceModel has been deprecated in favour of MLKitFaceDetection

### ISSUE THREAD

**Issue by professorkolik** [invertase/react-native-firebase#4296]
## Issue

After upgrade `@react-native-firebase/app: "v6.3.4" to "v8.4.3"` and `@react-native-firebase/ml-vision: "v6.3.4" to "v7.4.3"` and run command "pod install" getting warning message 

`FirebaseMLVisionFaceModel has been deprecated in favour of MLKitFaceDetection`

After own investigation seems FirebaseMLVisionFaceModel deprecated but `@react-native-firebase/ml-vision` still reference pod to `Firebase/MLVisionFaceModel`

According to migration guide https://developers.google.com/ml-kit/migration/ios all pod were replaced.
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
{
	"react-native": {
		"ml_vision_face_model": true
	}
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 103.53 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.17.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/***/.rvm/gems/ruby-2.6.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 21, 23, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-21 | Google APIs Intel x86 Atom, android-22 | Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `8.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - "@react-native-firebase/app": "^8.4.3",
  - "@react-native-firebase/ml-vision": "^7.4.3",
- **Are you using `TypeScript`?**
  - `Y` & `VERSION 3.9.7`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Indeed it is deprecated. Do you have a PR in mind to migrate this module to the new separate MLKit implementation? If not, it could be some time before it happens, no one has offered to move the package to the new APIs yet.

**Comment by professorkolik** [comment]
@mikehardy If there is no breaking changes I think replacing dependencies [here](https://github.com/invertase/react-native-firebase/blob/master/packages/ml-vision/RNFBMLVision.podspec) would be enough.

**Comment by mikehardy** [comment]
My take on the migration strategy was that the ML features have been split to "on device" and "cloud" as much more distinct things, and as a firebase module, we should expose the cloud APIs, but every API that is now service by a non-firebase SDK should be part of some other module (react-native-mlkit or something - I'm just making up the name). So I think to do it right it is a pretty big API reorganization and deprecation in preparation for API removal (for the on-device APIs)
