### ISSUE TITLE
[🐛] Firebase Crashlytics not working with RN v0.63.0

### ISSUE THREAD

**Issue by ahmadallo1** [invertase/react-native-firebase#4305]
I'm working with react native app version v0.63.0 and I have installed @react-native-firebase/crashlytics in order to integrate my app with firebase crashlytics both android and ios app are running without errors, but the crashlytics is not working.

I have created a button to force a crash:
`
import crashlytics from "@react-native-firebase/crashlytics";

<ButtonDesign
            buttonType="button_text"
            btnText="Crash"
            btnAction={() => crashlytics().crash()}
 />
`

the button is pressed without any other action the crashlytics().crash() is not working the app is not crashing.

firebase.json:
`
{
  "react-native": {
    "crashlytics_auto_collection_enabled": false,
    "crashlytics_debug_enabled": true,
    "analytics_auto_collection_enabled": false,
    "perf_auto_collection_enabled": false,
    "_CRASHLYTICS_AUTO_DISABLE_ENABLED": false,
    "crashlytics_ndk_enabled": false,
    "crashlytics_disable_auto_disabler": true
  }
}
`

package.json:
`
"@react-native-firebase/analytics": "^7.6.4",
    "@react-native-firebase/app": "^8.4.3",
    "@react-native-firebase/crashlytics": "^8.4.5",
    "@react-native-firebase/perf": "^7.4.3",
    "react": "16.13.1",
    "react-native": "0.63.0",
`

xcode firebase scripts:

![Screen Shot 2020-09-24 at 3 33 49 PM](https://user-images.githubusercontent.com/56399010/94145528-5c3aa080-fe7b-11ea-9e6f-0c664c8085e8.png)

also the firebase console keeps loading for both IOS and Android apps
![Screen Shot 2020-09-24 at 3 32 10 PM](https://user-images.githubusercontent.com/56399010/94145367-1f6ea980-fe7b-11ea-9a2c-7bf3142e645f.png)

any idea about what should be the issue

@mikehardy

**Comment by mikehardy** [comment]
Could be so many things. Discussed at length originally on the first one below and currently on the second

#3879 
#4229
