### ISSUE TITLE
🔥 Crashlytics: The title of non-fatal reports is ".java / .value"

### ISSUE THREAD

**Issue by nokite** [invertase/react-native-firebase#4313]
## Issue

Non-fatal reports appear simply as ".java" (in the list of all reports in the Crashlytics console). I think it should at least hint that it's about ReactNative. My project has lots of Kotlin and Java code, and only a part is in ReactNative. Knowing at least a little bit about the problem from the title can help to get an idea.

Non-fatals title:  
```
.java
.value
```
Actual crashes at least have the decency to look like this:  
```
ExceptionsManagerModule.java line 71
com.facebook.react.modules.core.ExceptionsManagerModule.reportException
```

P.S. Stack traces are shown minified and unreadable, but I assume that I have to fix something in my setup for this to work.  
In both cases (fatal, non-fatal) I can see the textual message that I've logged when I open a specific report, so that's the only thing that's useful for me.

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
        "@react-native-firebase/app": "^8.4.3",
        "@react-native-firebase/crashlytics": "^8.4.5",
        "bluebird": "^3.5.5",
        "bottlejs": "^1.7.2",
        "eventemitter3": "^3.1.2",
        "hoist-non-react-statics": "^3.3.0",
        "laces": "^0.1.4",
        "lodash": "^4.17.19",
        "prop-types": "^15.7.2",
        "react": "16.9.0",
        "react-native": "0.61.5",
        "react-redux": "^7.0.3",
        "redux": "^4.0.0",
        "redux-logger": "^3.0.6",
        "redux-pack": "^0.1.5",
        "redux-thunk": "^2.3.0"
    }
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x ] my application is an AndroidX application?
- [x ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
implementation("com.google.firebase:firebase-crashlytics:${Versions.crashlytics}") { version { strictly "17.2.1" } }
    constraints {implementation("com.google.firebase:firebase-crashlytics-ndk") {version {strictly "17.2.1" } } }
```

#### `android/settings.gradle`:

```groovy
apply from: file("node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)

include ':app'

```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 2.62 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.12.0 - /var/folders/lh/vlsw338n0n98mp7s0gc6_46c0000gn/T/yarn--1601194705826-0.045099543535438213/node
    Yarn: 1.22.5 - /var/folders/lh/vlsw338n0n98mp7s0gc6_46c0000gn/T/yarn--1601194705826-0.045099543535438213/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 29.0.2, 29.0.3
      System Images: android-21 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^8.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `Crashlytics`
- **Are you using `TypeScript`?**
  - `no`

</p>
</details>

**Comment by mikehardy** [comment]
Have the decency to ?
Sure I guess. Duplicate - https://github.com/invertase/react-native-firebase/issues/3760

No one appeared to want to do any of the work though, perhaps you could propose a PR?

**Comment by nokite** [comment]
Ok I changed that sentence, "decency" apparently was a poor choice of words.

I see I provoked your reaction, but please understand I put no bad emotions into this. I just wanted to report something so it can eventually be improved. I believe the issue can be reopened, from my point of view it's valid.

Cheers, have a good day 🙂

**Comment by mikehardy** [comment]
Okay - yes decency as a word choice puts the mind into a binary either/or state where the only remaining option is that the library is indecent, which is sad to contemplate ;-)

I'd prefer to re-open the other issue, it has quite a bit of good information related on it.

It still needs someone to take it up though, there's work to do but no hands to do it yet...

**Comment by pi-xel** [comment]
@nokite I am experiencing the same issue. Did you find a solution to this?

**Comment by nokite** [comment]
@pi-xel No, I haven't tackled this problem.
