### ISSUE TITLE
[🐛] Settings in firebase.json are ignored

### ISSUE THREAD

**Issue by ahmadworks** [invertase/react-native-firebase#4315]
I have firebase.json file with custom settings in my project home directory (same directory that contains package.json), but when I build the app it just ignores settings in this file.

Platform: iOs
XCode 12
The latest version of RNfirebase
I only have one firebase.json in my project.

**Comment by mikehardy** [comment]
Perhaps try `npx react-native-clean-project`
Also, if you could post a reproduction (perhaps based off https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh) so we could see it, while specifying exactly what was specified and then ignored

As it is, there is nothing to go on in this issue and thus no action to take

**Comment by ahmadworks** [comment]
Tried npx react-native-clean-project still not working, I didn't get the point of https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh , how can this help?

**Comment by mikehardy** [comment]
You have come to unknown people on the internet (us) with a vague description of a problem no one else is having and said "please help"

We've said "sure, but we don't have your problem, perhaps you could post a reproduction?". Same thing you'd do if some random person came to you for help.

The make-demo.sh script creates a skeleton react-native-firebase project from scratch, based on all the documents, so you don't have to spend a lot of time creating one yourself

I look forward to seeing the github URL to your reproduction

**Comment by rivaros** [comment]
Can be because of this https://github.com/invertase/react-native-firebase/issues/5377
