### ISSUE TITLE
[🐛] Dynamic Links – Analytics not working?

### ISSUE THREAD

**Issue by lluia** [invertase/react-native-firebase#4320]
## Issue

Hello, thanks for the hard work with `@react-native-firebase` 💯 💪🏽 

We're using **dynamic links** and they mostly behave properly in both platforms for us, apart from tracking.

<img width="943" alt="Screenshot 2020-09-28 at 15 25 45" src="https://user-images.githubusercontent.com/5938217/94438106-f4e45f80-019e-11eb-808d-84b1f61d774c.png">

It seems the analytics associated to them don't work properly and they either don't register or register randomly for us.

I installed locally [`@react-native-firebase/dynamic-links`](https://rnfirebase.io/dynamic-links/usage#usage) and both listeners of the library for _foreground_ and _background_ events seem to work properly. I verified all the set-up steps for *XCode* and it all seems good as well.

Our only issue is that the events associated to them don't seem to be registered properly. For instance in *iOS* `APP_INSTALLS`, `FIRST_OPENS`, `RE-OPENS` is always `0` and Android has `APP_INSTALLS` but `FIRST_OPEN` is always `0` as well 😕 

Any help around this highly appreciated 🙏🏽 

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```diff
+   "@react-native-firebase/app": "^8.4.3",
+   "@react-native-firebase/dynamic-links": "^7.5.4",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

project 'app',
  'Dev.Debug' => :debug,
  'Dev.Release' => :release,
  'Argentina.Debug' => :debug,
  'Argentina.Release' => :release,
  'Brazil.Debug' => :debug,
  'Brazil.Release' => :release,
  'Chile.Debug' => :debug,
  'Chile.Release' => :release,
  'Colombia.Debug' => :debug,
  'Colombia.Release' => :release,
  'CzechRepublic.Debug' => :debug,
  'CzechRepublic.Release' => :release,
  'Italy.Debug' => :debug,
  'Italy.Release' => :release,
  'Mexico.Debug' => :debug,
  'Mexico.Release' => :release,
  'Peru.Debug' => :debug,
  'Peru.Release' => :release,
  'Poland.Debug' => :debug,
  'Poland.Release' => :release,
  'Portugal.Debug' => :debug,
  'Portugal.Release' => :release,
  'Spain.Debug' => :debug,
  'Spain.Release' => :release,
  'Turkey.Debug' => :debug,
  'Turkey.Release' => :release

target 'app' do
  # Pods for app
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'react-native-adjust', :path => '../node_modules/react-native-adjust'

  target 'appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'app-tvOS' do
  # Pods for app-tvOS

  target 'app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

#### `AppDelegate.m`:

```objc
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>

@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate>

@property (nonatomic, strong) UIWindow *window;

@end
```

#### `app.entitlements`

```diff
<key>com.apple.developer.associated-domains</key>
+ <array>
+   <string>applinks:patientsappspain.page.link</string>
+   <string>applinks:patientsapppoland.page.link</string>
+   <string>applinks:patientsappbrazil.page.link</string>
+   <string>applinks:patientsappturkey.page.link</string>
+   <string>applinks:patientsappitaly.page.link</string>
+   <string>applinks:patientsappmexico.page.link</string>
+   <string>applinks:patientsappargentina.page.link</string>
+   <string>applinks:patientsappcolombia.page.link</string>
+   <string>applinks:patientsappcolombia.page.link</string>
+   <string>applinks:patientsappportugal.page.link</string>
+   <string>applinks:patientsappczechrepublic.page.link</string>
+   <string>applinks:patientsappperu.page.link</string>
+   <string>applinks:patientsappchile.page.link</string>
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        playServicesVersion = "17.0.0"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")
        classpath("com.google.gms:google-services:4.2.0")
        classpath 'com.bugsnag:bugsnag-android-gradle-plugin:4.+'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.google.com' }
    }
}
```

#### `android/settings.gradle`:

```groovy
rootProject.name = 'app'
include ':react-native-webview'
project(':react-native-webview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview/android')
include ':@react-native-community_async-storage'
project(':@react-native-community_async-storage').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/async-storage/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

**Comment by mikehardy** [comment]
Coincidentally, I am working on this right right now in my work project.

One thing is certain - dynamically generated links won't show up in stats on the web console, only links generated there will show up. This is documented upstream (you should become very very familiar with those!)

Another thing is that the IOS stats don't include certain events as a platform difference, those are documented as well 

Here is the relevant doc I think https://firebase.google.com/docs/reference/dynamic-links/analytics?authuser=1#response_body - note the table with info on where you get what info and on what platform

You deleted so much from the template I can't see how AppDelegate is handlng linking (have you done something custom with inbound link handling?) and there's no reproduction on how you're handling the link in Javascript so I don't know.

I encourage you to try a minimal reproduction to show the problem, and if you still see it (or maybe start here first...) do a minimal reproduction based off the upstream firebase-ios-sdk quickstart in order to conclusively show it can work or that it is not working https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks

**Comment by lluia** [comment]
I think the cause might have been that we were sending malformed events in **firebase analytics** 📊  and that somehow might have caused the link analytics not working either. 

Anyway, we circumvented the issue by manually sending custom events every time a **dynamic link was open**; we haven't seen the need to debug further. Closing the issue, thanks for the help 💯
