### ISSUE TITLE
'FirebaseAnalytics/FIRAnalyticsConfiguration.h' file not found

### ISSUE THREAD

**Issue by dilawer** [invertase/react-native-firebase#4329]
I have been having this issue. My XCODE version is 11.7. 
# My **package.json** is: `{
  "name": "Echo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@expo/ex-navigation": "^3.1.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "firebase": "^4.8.0",
    "lodash": "^4.17.10",
    "moment": "^2.22.1",
    "prop-types": "^15.6.0",
    "react": "16.0.0",
    "react-moment": "^0.7.0",
    "react-native": "0.63.3",
    "react-native-datepicker": "^1.7.2",
    "react-native-datepicker-dialog": "0.0.9",
    "react-native-dev-menu-on-touch": "^1.0.3",
    "react-native-email": "^1.0.2",
    "react-native-firebase": "^5.2.3",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-lock": "^0.4.0",
    "react-native-popup-dialog": "^0.16.6",
    "react-native-step-indicator": "0.0.7",
    "react-native-swipe-list-view": "^1.3.1",
    "react-native-vector-icons": "^4.4.2",
    "react-redux": "^5.0.6",
    "realm": "^10.0.0-beta.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-eslint": "^8.0.3",
    "babel-jest": "21.2.0",
    "babel-preset-react-native": "4.0.0",
    "eslint": "^4.12.1",
    "eslint-plugin-react": "^7.5.1",
    "eslint-plugin-react-native": "^3.2.0",
    "jest": "21.2.1",
    "react-native-cli": "^2.0.1",
    "react-native-dotenv": "^0.1.0",
    "react-test-renderer": "16.0.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "js/assets/fonts"
    ]
  }
}
`
# My **Podfile** looks like this:
`
platform :ios, '12.0'

target 'Echo' do
  use_frameworks!
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/Yoga'
  pod 'Bolts'
  pod 'Firebase'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCore'
  
  target 'EchoTests' do
    inherit! :search_paths
  end

end

target 'Echo-tvOS' do
  use_frameworks!

end
`
# And my **Podfile.lock** looks like this:
`PODS:
  - Bolts (1.9.1):
    - Bolts/AppLinks (= 1.9.1)
    - Bolts/Tasks (= 1.9.1)
  - Bolts/AppLinks (1.9.1):
    - Bolts/Tasks
  - Bolts/Tasks (1.9.1)
  - Firebase (6.33.0):
    - Firebase/Core (= 6.33.0)
  - Firebase/Analytics (6.33.0):
    - Firebase/Core
  - Firebase/Auth (6.33.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.9.2)
  - Firebase/Core (6.33.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.8.3)
  - Firebase/CoreOnly (6.33.0):
    - FirebaseCore (= 6.10.3)
  - Firebase/Database (6.33.0):
    - Firebase/CoreOnly
    - FirebaseDatabase (~> 6.6.0)
  - Firebase/Messaging (6.33.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.7.0)
  - FirebaseAnalytics (6.8.3):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleAppMeasurement (= 6.8.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30906.0)
  - FirebaseAuth (6.9.2):
    - FirebaseCore (~> 6.10)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/Environment (~> 6.7)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseCore (6.10.3):
    - FirebaseCoreDiagnostics (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
  - FirebaseCoreDiagnostics (1.7.0):
    - GoogleDataTransport (~> 7.4)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
    - nanopb (~> 1.30906.0)
  - FirebaseDatabase (6.6.0):
    - FirebaseCore (~> 6.10)
    - leveldb-library (~> 1.22)
  - FirebaseInstallations (1.7.0):
    - FirebaseCore (~> 6.10)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (4.7.0):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
  - FirebaseMessaging (4.7.0):
    - FirebaseCore (~> 6.10)
    - FirebaseInstanceID (~> 4.7)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Reachability (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - GoogleAppMeasurement (6.8.3):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30906.0)
  - GoogleDataTransport (7.4.0):
    - nanopb (~> 1.30906.0)
  - GoogleUtilities/AppDelegateSwizzler (6.7.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.7.2):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (6.7.2):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.7.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.7.2):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.7.2)"
  - GoogleUtilities/Reachability (6.7.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.7.2):
    - GoogleUtilities/Logger
  - GTMSessionFetcher/Core (1.4.0)
  - leveldb-library (1.22)
  - nanopb (1.30906.0):
    - nanopb/decode (= 1.30906.0)
    - nanopb/encode (= 1.30906.0)
  - nanopb/decode (1.30906.0)
  - nanopb/encode (1.30906.0)
  - PromisesObjC (1.2.10)
  - Protobuf (3.13.0)
  - Yoga (1.14.0)

DEPENDENCIES:
  - Bolts
  - Firebase
  - Firebase/Analytics
  - Firebase/Auth
  - Firebase/Core
  - Firebase/Database
  - Firebase/Messaging
  - FirebaseAnalytics
  - FirebaseCore
  - Yoga (from `../node_modules/react-native/ReactCommon/Yoga`)

SPEC REPOS:
  trunk:
    - Bolts
    - Firebase
    - FirebaseAnalytics
    - FirebaseAuth
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseDatabase
    - FirebaseInstallations
    - FirebaseInstanceID
    - FirebaseMessaging
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleUtilities
    - GTMSessionFetcher
    - leveldb-library
    - nanopb
    - PromisesObjC
    - Protobuf

EXTERNAL SOURCES:
  Yoga:
    :path: "../node_modules/react-native/ReactCommon/Yoga"

SPEC CHECKSUMS:
  Bolts: 8c1e8aab2f603387b8b9924f57d1d64f43d3ffdc
  Firebase: 8db6f2d1b2c5e2984efba4949a145875a8f65fe5
  FirebaseAnalytics: 5dd088bd2e67bb9d13dbf792d1164ceaf3052193
  FirebaseAuth: c92d49ada7948d1a23466e3db17bc4c2039dddc3
  FirebaseCore: d889d9e12535b7f36ac8bfbf1713a0836a3012cd
  FirebaseCoreDiagnostics: 770ac5958e1372ce67959ae4b4f31d8e127c3ac1
  FirebaseDatabase: 13a865a4b85897462b930eb683bda8f52583713f
  FirebaseInstallations: 466c7b4d1f58fe16707693091da253726a731ed2
  FirebaseInstanceID: ac5a82fcd21f804dbfc8f318eff9e1d7a9916e49
  FirebaseMessaging: fc1f98b4592f8f2ea538169b1c317c6e76f81300
  GoogleAppMeasurement: 966e88df9d19c15715137bb2ddaf52373f111436
  GoogleDataTransport: b7f406340a291370045a270c599e53c6fa6ec20f
  GoogleUtilities: 7f2f5a07f888cdb145101d6042bc4422f57e70b3
  GTMSessionFetcher: 6f5c8abbab8a9bce4bb3f057e317728ec6182b10
  leveldb-library: 55d93ee664b4007aac644a782d11da33fba316f7
  nanopb: 59317e09cf1f1a0af72f12af412d54edf52603fc
  PromisesObjC: b14b1c6b68e306650688599de8a45e49fae81151
  Protobuf: 3dac39b34a08151c6d949560efe3f86134a3f748
  Yoga: 7d13633d129fd179e01b8953d38d47be90db185a

PODFILE CHECKSUM: fee4947162a8d8f1ccd6caf77b609d62676d763c

COCOAPODS: 1.9.3
`

**Comment by mikehardy** [comment]
Hi there! You have somehow destroyed the template formatting :sweat_smile: 

More importantly, we are no longer accepting any issues related to react-native-firebase v5. You must upgrade to receive any support: https://rnfirebase.io/migrating-to-v6
