### ISSUE TITLE
Admob smart banner not resizing when changing screen orientation

### ISSUE THREAD

**Issue by soyangel** [invertase/react-native-firebase#433]
### Issue

Right now Admob Smart banners don't resize on Android when changing screen orientation. This is not a big problem when changing from portrait to landscape (add is smaller than width but can be centered). The worst case is when changing from landscape to portrait where the ad is cut.

To replicate just start the app in landscape mode and then rotate to portrait.

### Environment

1. Application Target Platform: Android

2. Development Operating System: Linux

3. Build Tools: 

4. React Native version: 0.44

5. RNFirebase Version: 2.2.1

6. Firebase Module: admob

**Comment by Ehesp** [comment]
Hey, what Size are you passing in?

**Comment by soyangel** [comment]
I have not set the size attribute so it should be a smart banner (as told in the docs).

**Comment by Salakar** [comment]
Thanks for reporting this issue. We're aware that AdMob has fallen behind on React Native Firebase and would like to bring it up to speed again. I will close this issue for now and track it as well as other issues collectively over on the `AdMob overhaul proposal` to be addressed in a future release. See #1259
