### ISSUE TITLE
🔥 App is hanging/lagging after changing GoogleService-Info.plist

### ISSUE THREAD

**Issue by SplinterStan** [invertase/react-native-firebase#4332]
## Issue

We are using `react-native-firebase` and have configured it accordingly to the provided instructions here: https://rnfirebase.io/#3-ios-setup. After we have changed the firebase config file with a new one pointing to another firebase project and also another bundleID, the app builds and runs, but its extremely hanging and lagging, so that you can't really use the app (need to click on items >10 times and wait then several minutes until an action happens).

Here is some detailed repro:
1. We had used a certain firebase config in `GoogleService-Info.plist` for a long time, e.g. for the bundleID `com.mycompany.ourfancyapp` and the firebase project id `our-fancy-app-dev`.
2. Then, as we need to distribute the app to our client's private app store, we need to change the config to bundleID `com.client.myapp` and to a new Firebase project created to store specifically the client's data, e.g. projectID `our-fancy-app-for-client-x`.
3. As needed, we have registered a new bundleID within the new Firebase project and downloaded a new `GoogleService-Info.plist` file. But when we replaced the old firebase config file with the new one and ran the app, we could login using the new client-facing database, but after the login the whole app works, but it is extremely slow and nearly not usable (you have to click on an item 10 times and then wait for 2-3 minutes until it opens (sometimes it doesn't react at all)). In addition to that, the same error as described in [this issue](https://github.com/facebook/react-native/issues/27483) is shown, but for our case its showing a lot of `RNCAsyncStorage` pending callbacks:

<img width="907" alt="Bildschirmfoto 2020-09-27 um 23 09 59" src="https://user-images.githubusercontent.com/46443337/94737287-e39d7d80-036d-11eb-91d0-3b1abade78e3.png">

4. The funny thing is, if we close the hanging app, move back the old `GoogleService-Info.plist` for the old dev bundleID and projectID, then the app is not lagging anymore and the error regarding pending callbacks doesn't appear at all! 🤯 
5. We tried to test this on Android build using Android simulator and Android 10, and we've got exactly the same issue there!

**As it seems to be not a platform-specific issue, I will only provide some details for iOS below and leave Android out.**

We use the latest module versions, here some detailed info:
`react-native: 0.63.2`
`react: 16.13.1`
`@react-native-firebase/app: 8.4.4`
`@react-native-firebase/auth: 8.0.10`
`@react-native-firebase/firestore: 7.8.4`
`@react-native-firebase/messaging: 7.8.9`
`@react-native-community/async-storage: 1.12.0`

Our team would really appreaciate, if some of you guys can find a solution for this issue soon. Because, otherwise we are going to lose our client as we can't deliver the app in time 😢  Thank you very much in advance! 👍 

---

#### `package.json`:

```json
"dependencies": {
    "@react-native-community/async-storage": "^1.10.1",
    "@react-native-community/checkbox": "^0.4.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/picker": "^1.6.1",
    "@react-native-community/progress-bar-android": "^1.0.3",
    "@react-native-community/progress-view": "^1.0.3",
    "@react-native-firebase/app": "^8.0.1",
    "@react-native-firebase/auth": "~8.0.7",
    "@react-native-firebase/firestore": "^7.2.1",
    "@react-native-firebase/messaging": "^7.0.0",
    "@react-navigation/bottom-tabs": "^5.5.1",
    "@react-navigation/material-bottom-tabs": "^5.2.10",
    "@react-navigation/native": "^5.5.0",
    "@react-navigation/stack": "^5.4.1",
    "axios": "^0.19.2",
    "intl": "^1.2.5",
    "languagedetect": "^2.0.0",
    "react": "16.13.1",
    "react-devtools": "^4.6.0",
    "react-native": "0.63.2",
    "react-native-base64": "0.0.2",
    "react-native-crypto-js": "^1.0.0",
    "react-native-device-info": "^5.6.1",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-modal": "^11.5.6",
    "react-native-paper": "^3.10.1",
    "react-native-pdf": "^6.2.0",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^1.0.2",
    "react-native-screens": "^2.8.0",
    "react-native-snackbar": "^2.2.2",
    "react-native-splash-screen": "^3.2.0",
    "react-native-swipe-list-view": "^3.1.1",
    "react-native-vector-icons": "~6.6.0",
    "react-native-webview": "^10.8.3",
    "rn-fetch-blob": "^0.12.0",
    "rn-game-over": "^1.0.7"
  },
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ourFancyApp' do

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ourFancyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ourFancyApp-tvOS' do
  # Pods for ourFancyApp-tvOS

  target 'ourFancyApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

#### `AppDelegate.m`:

```objc
#import <Firebase.h>
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }

#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"cisionInsightsMobileApp"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
[Shortened]
[Wed Sep 30 2020 23:13:56.369]  ERROR    Warning: Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"132":{"module":"RNFetchBlob","method":"emitExpiredEvent"},"1585":{"module":"RNFBMessagingModule","method":"requestPermission"},"84988":{"module":"RNCAsyncStorage","method":"multiSet"},"84990":{"module":"RNCAsyncStorage","method":"multiSet"},"85193":{"module":"RNCAsyncStorage","method":"multiSet"},"85195":{"module":"RNCAsyncStorage","method":"multiSet"},"85398":{"module":"RNCAsyncStorage","method":"multiSet"},"85501":{"module":"RNCAsyncStorage","method":"multiSet"},"85503":{"module":"RNCAsyncStorage","method":"multiSet"},"85706":{"module":"RNCAsyncStorage","method":"multiSet"},"85708":{"module":"RNCAsyncStorage","method":"multiSet"},"85911":{"module":"RNCAsyncStorage","method":"multiSet"},"86014":{"module":"RNCAsyncStorage","method":"multiSet"},"86016":{"module":"RNCAsyncStorage","method":"multiSet"},"86219":{"module":"RNCAsyncStorage","method":"multiSet"},...["RNCAsyncStorage" goes until the output gets truncated]...
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase/app` version you're using that has this issue:**
  - `8.4.4`
- **`Firebase` module(s) you're using that has the issue:**
  - `react-native-firebase/app`
  -  and probably `react-native-firebase/firestore`
- **Are you using `TypeScript`?**
  - `No`

</p>
</details>

---

**Comment by mikehardy** [comment]
This is going to be project-specific somehow. If I were you I'd get busy with profilers - both Xcode native profilers and remote debugging at the JS level attached to a simulator (if you can reproduce there) and a real device, and see what the app is doing. It's likely that you have some sort of infinite loop on for example the app posting to firebase while you have a listener hooked to updates etc etc.

The only way we will be able to troubleshoot this here as module maintainers is if you produce a clean reproduction (start with `react-native init` in other words - or https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh) with a simple App.js that shows the problem. We can't dive into project-specific things because there are too any variables, it's tremendously inefficient

**Comment by SplinterStan** [comment]
The issue was caused by an infinite re-subscription loop to firestore collections in the JS code. So, it can be closed.
