### ISSUE TITLE
[🐛] 🔥 App crashes when calling vision.cloudDocumentTextRecognizerProcessImage

### ISSUE THREAD

**Issue by craig1123** [invertase/react-native-firebase#4334]
App crashes on iOS iphone 11 Xcode 12 when I follow the documentation for cloud document text recognition uploading a pdf file. I then ran it through Xcode's simulator on debug mode and this was the error:
`Thread 1: "*** -[NSURL URLByAppendingPathComponent:]: component, components, or pathExtension cannot be nil."`

```
    try {
      const res = await DocumentPicker.pick({
        type: [
          DocumentPicker.types.plainText,
          DocumentPicker.types.pdf,
          DocumentPicker.types.csv,
        ],
      });
      console.log(res);
      const visionResp = await vision().cloudDocumentTextRecognizerProcessImage(
        res.uri,
      );
    } catch (err) {
      console.log(err);
    }
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
  "dependencies": {
    "@react-native-firebase/analytics": "^7.6.7",
    "@react-native-firebase/app": "^8.4.5",
    "@react-native-firebase/auth": "^9.2.7",
    "@react-native-firebase/crashlytics": "^8.4.8",
    "@react-native-firebase/firestore": "^7.8.5",
    "@react-native-firebase/ml-natural-language": "^7.4.7",
    "@react-native-firebase/ml-vision": "^7.4.7",
    "@react-native-firebase/perf": "^7.4.7",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-document-picker": "^3.5.4"
  },
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "ml_vision_ocr_model": true,
    "ml_natural_language_language_id_model": true
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
$RNFirebaseAsStaticFramework = true

platform :ios, '11.4'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target '[app]' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  pod 'react-native-camera', :path => '../node_modules/react-native-camera', subspecs: [
    'TextDetector'
  ]
  # pod 'Firebase/Core'
  pod 'GoogleSignIn', '~> 5.0.2'
end

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <Firebase.h>
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <RNSplashScreen.h>
#import <RNGoogleSignin/RNGoogleSignin.h>
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <UserNotifications/UserNotifications.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"([app name])"
                                            initialProperties:nil];
  
  // Define UNUserNotificationCenter
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [RNSplashScreen show];

  return YES;
}

- (BOOL)application:(UIApplication *)application 
  openURL:(nonnull NSURL *)url 
  options:(nonnull NSDictionary<NSString *,id> *)options 
{
  return [[FBSDKApplicationDelegate sharedInstance] application:application openURL:url options:options] || [RNGoogleSignin application:application openURL:url options:options];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge

{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 2.02 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `7.4.7` for ml-vision and `8.4.5` for app
- **`Firebase` module(s) you're using that has the issue:**
  - `ml-vision`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there!

"iPhone 11" is not a useful version number. It could be iOS 13 or 14 right? I'll assume you're fully up to date, but a worthwhile point about precision in troubleshooting - be as precise as possible

Do you have a full stack trace? Have you tried tracing in to the Obj-C files in node_modules and instrumenting them at all to see if the assumptions about input built in to the code are valid?

What's "DocumentPicker"? What's JSON.stringify(res, null, 2) look like?

How does your usage compare with the end-to-end tests in the package? https://github.com/invertase/react-native-firebase/blob/master/packages/ml-vision/e2e/text.e2e.js

**Comment by craig1123** [comment]
Hi Mike, 

If you look in the "environment" portion, the SDK output says iOS 14. Next time, I'll put it first thing with my other details.

There is no JS stacktrace and system logs say "Service exited due to SIGABRT". The xcode stacktrace is 

<img width="533" alt="Screen Shot 2020-10-01 at 1 30 07 PM" src="https://user-images.githubusercontent.com/17581359/94864378-bc3bc480-03f0-11eb-9982-1c69c4480190.png">


DocumentPicker is just react-native-document-picker. It works and logs the local file's URI correctly. The app doesn't crash when I comment out the `vision().cloudDocumentTextRecognizerProcessImage(res.uri)` part. Here is the output as JSON:
```
{
  "size": 3908,
  "fileCopyUri": "file:///Users/[computer]/Library/Developer/CoreSimulator/Devices/2C8F4FAC-83F4-460F-8564-2956C7ADD664/data/Containers/Data/Application/585EFBC1-A0B5-4C34-967D-179BBA339637/tmp/[app-id]-Inbox/test.pdf",
  "name": "test.pdf",
  "uri": "file:///Users/[computer]/Library/Developer/CoreSimulator/Devices/2C8F4FAC-83F4-460F-8564-2956C7ADD664/data/Containers/Data/Application/585EFBC1-A0B5-4C34-967D-179BBA339637/tmp/[app-id]-Inbox/test.pdf",
  "type": "application/pdf"
}
```

There are no E2E tests on that file associated with `cloudDocumentTextRecognizerProcessImage`, but I did find some on `documentText.e2e.js`. I do use `cloudTextRecognizerProcessImage` for OCR on images and that works great, but now I'm trying to use `cloudDocumentTextRecognizerProcessImage` for extracting text from pdfs. The tests only reflect images and not pdfs or text files. I'm starting to think it's only meant for images and not for other files?

**Comment by craig1123** [comment]
Yeah, it actually does work with images, but not other file types. Looks like I need to pull in the Google vision API somehow https://cloud.google.com/vision/docs/pdf.

Thanks Mike for all that you do

**Comment by mikehardy** [comment]
Glad there were enough pointers to dig, but sorry it doesn't seem like the API's an exact fit. Perhaps a mention in the docs (github makes docs PRs super easy - and there's an edit link top right of every page) explaining it only works for image files could help others in the future, and also perhaps react-native image support itself is flexible and can be augmented somehow? That's just at the thinking-out-loud phase of idea development, no idea if that's possible. Other alternative if the vision APIs aren't easy to access is that perhaps there is a library that renders documents to images so you could push them through this API

Cheers :-)

**Comment by craig1123** [comment]
I think I'd rather find an endpoint for pdfs specifically rather than change all the pdf pages into images, loop over them and push them through this API. Not a bad idea, just not for my needs. Some users have up to 40 pages and that would take a while.

I'll make a PR to the docs :)
