### ISSUE TITLE
Is there a way, I could check the UUID is already available in Firebase ?

### ISSUE THREAD

**Issue by ShunmugamAiyappan** [invertase/react-native-firebase#434]
=Is there a way, I could check the UUID is already available in Firebase ?

**Comment by Ehesp** [comment]
The auth uuid? Why do you need to do that?

**Comment by ShunmugamAiyappan** [comment]
I need to check whether the Phone is already been registered to Firebase / not

**Comment by chrisbianca** [comment]
The only way you can do this is to try and register the user or sign them in, and see whether the account already exists or not.  This can be done using email and password, phone number or one of the other sign in methods.

**Comment by ShunmugamAiyappan** [comment]
Okay thanks . I have done in that way.
