### ISSUE TITLE
[🐛] Bug Report Title -  Could not find com.google.firebase:firebase-bom:12.0.1

### ISSUE THREAD

**Issue by D-Rosa99** [invertase/react-native-firebase#4341]
## Issue

I'm trying to use react-native-firebase/analytics but it keep gave me this error 

 ```
Could not determine the dependencies of task ':app:preDevDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:devDebugRuntimeClasspath'.
   > Could not find com.google.firebase:firebase-bom:12.0.1.
     Searched in the following locations:
       - file:/home/intellisys/.m2/repository/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - file:/home/intellisys/Desktop/covidMobile/covid-safe-paths/node_modules/react-native/android/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - file:/home/intellisys/Desktop/covidMobile/covid-safe-paths/node_modules/jsc-android/dist/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - file:/home/intellisys/Desktop/covidMobile/covid-safe-paths/node_modules/detox/Detox-android/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - https://jcenter.bintray.com/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - https://jitpack.io/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - https://maven.google.com/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - https://repo.maven.apache.org/maven2/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
     Required by:
         project :app
   > Could not find com.google.firebase:firebase-bom:12.0.1.
     Searched in the following locations:
       - file:/home/intellisys/.m2/repository/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - file:/home/intellisys/Desktop/covidMobile/covid-safe-paths/node_modules/react-native/android/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - file:/home/intellisys/Desktop/covidMobile/covid-safe-paths/node_modules/jsc-android/dist/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - file:/home/intellisys/Desktop/covidMobile/covid-safe-paths/node_modules/detox/Detox-android/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - https://jcenter.bintray.com/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - https://jitpack.io/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - https://maven.google.com/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
       - https://repo.maven.apache.org/maven2/com/google/firebase/firebase-bom/12.0.1/firebase-bom-12.0.1.pom
     Required by:
         project :app > project :@react-native-firebase_analytics
         project :app > project :react-native-firebase_analytics
         project :app > project :react-native-firebase_app

```
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
    "@react-native-firebase/analytics": "^7.6.7",
    "@react-native-firebase/app": "^8.4.5",
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
NO
</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Not enough template information to go on. That BOM does not exist though, for reference current is 25.11.0 so 12.0.1 is unexpected and would be unusable old if it existed.

Here's an example of correctly integrating react-native-firebase, analytics included, so you can see how to do it: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh
