### ISSUE TITLE
🔥 [🐛] NPM Publish actions are interrupted/incomplete

### ISSUE THREAD

**Issue by davidgovea** [invertase/react-native-firebase#4343]
## Issue

Re-opening of issue #4283 
#4330 attempted to fix, but did not.

Hey @mikehardy -- I discovered while working on #4331 that npm does not have the latest version of each package. It looks like the publish action still has some issues under certain concurrency scenarios.

* `npm info @react-native-firebase/database` => `latest: 7.5.10`
* In-repo version: `7.5.11`: https://github.com/invertase/react-native-firebase/blob/master/packages/database/CHANGELOG.md

---

Interestingly, the `app`, `analytics`, and `admob` are up-to-date on npm. They are alphabetically first, so I'm thinking we have an interrupted-publish issue.

Looking at the [Publish actions](https://github.com/invertase/react-native-firebase/actions?query=workflow%3APublish), here is my understanding of what happened:

1. `Publish` was manually triggered: https://github.com/invertase/react-native-firebase/actions/runs/281108519
   * Since the `app` module was updated, the peerDependency of each package was updated.
   * The new commits were pushed to master: https://github.com/invertase/react-native-firebase/runs/1189876219?check_suite_focus=true#step:6:104
1. The new master push triggers **another** `Publish` run: https://github.com/invertase/react-native-firebase/runs/1189883874?check_suite_focus=true
   * This job actually publishes the latest versions of `analytics` and `admob` before [being interrupted by a "You cannot publish over the previously published versions" `app` publish error](https://github.com/invertase/react-native-firebase/runs/1189883874?check_suite_focus=true#step:6:427)
1. The version-bumps are pushed to master, but the **action is skipped** https://github.com/invertase/react-native-firebase/runs/1189891921?check_suite_focus=true

---

### Javascript
N/A

### iOS
N/A

### Android
N/A

---

## Environment
N/A

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Yes - actually I was going to take this up with @Salakar - I'm not sure what's going on here and I don't have the push-to-master authority to conclusively un-fuddle it unfortunately. One hypothesis is the previous push breaks put things in a state the scripts can't self-correct out of. Another hypothesis is that it's something unknown (sounds silly but that hypothesis is always on my list of things to expect, keeps me honest). 

It's a bit of a frustration right now for sure but at least current merged functionality is out there I think

**Comment by mikehardy** [comment]
I received upgraded permissions just a moment ago and have manually pushed current packages to npmjs.com from the repo so we really should be coherent now for yarn/npm package management. This may keep us straight going forward but @Salakar said he'd take a look tomorrow to verify
