### ISSUE TITLE
🔥 Crashlytics reports error even if crashlytics_debug_enabled is false

### ISSUE THREAD

**Issue by MaxToyberman** [invertase/react-native-firebase#4348]
Hi, 
crash reporting is working but it is working in debug also, which is not desired.
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
    "@react-native-firebase/analytics": "6.7.1",
    "@react-native-firebase/app": "8.4.5",
    "@react-native-firebase/crashlytics": "8.4.8",
    "@react-native-firebase/in-app-messaging": "6.7.1",
    "@react-native-firebase/messaging": "6.7.1",
    "@react-native-firebase/remote-config": "6.7.1",

#### `firebase.json`:
```json
{
  "react-native": {
    "perf_auto_collection_enabled": false,
    "crashlytics_disable_auto_disabler": true,
    "crashlytics_debug_enabled": false
  }
}
```
</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 60.30 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 26, 27, 28, 29, 30
      Build Tools: 27.0.3, 28.0.3, 29.0.3, 30.0.2
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [X] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
That is an odd set of dependencies. I don't think it has bearing on your actual problem but you should upgrade to current stable on *all* packages if at all possible.

Why the disable auto disabler? What happens if you try that toggle? Also, I believe this is rendered into the plist file, do you verify you have done `npx react-native-clean-project` and a full rebuild in between altering firebase.json settings

One other thought - it is orthogonal and this would be a bug either way - but if it is a data pollution error because debug / dev firebase backends aren't separate, your analytics and everything will still be polluting unless you actually have a separate firebase project for non-production uses. If you haven't done it, it is possible using Android build "flavors" and iOS build "targets", then it doesn't matter as much (although you should be able to express "don't log crashes in debug" as a setting of course)

**Comment by MaxToyberman** [comment]
@mikehardy Thank you for your help.
I have removed the `crashlytics_disable_auto_disabler` i have done a full rebuild and ran `npx react-native-clean-project`.

I have to mention that this issue started happening after upgrading from :  
```
    "@react-native-firebase/app": "6.7.1",
    "@react-native-firebase/crashlytics": "6.7.1"
```

to:

```
    "@react-native-firebase/app": "8.3.1",
    "@react-native-firebase/crashlytics": "8.3.2",
```

I will use flavors and targets, currently i don't see other option.

**Comment by mikehardy** [comment]
Ok - I think flavors and targets is a superior solution for backend data pollution avoidance but as mentioned above there is no reason turning off debug crash reporting shouldn't be possible. We turned it on by default but turning it off is an expected feature. I'll keep this open and mark it for triage/review

Possibly related #4229 / #4236

If you want to help move it forward (fastest way to resolve it!) doing a bisect in the version range between what you were using and current to find the version that starts the unwanted behavior would help pinpoint the code change that did it and get us to a fix. Mathematically it's usually just 3 builds or so as bisect strategy works very quickly

**Comment by MaxToyberman** [comment]
Hey @mikehardy ,
looks like problem starts with version 8.0.0 ,will try to find the issue.

Thank you

**Comment by MaxToyberman** [comment]
@mikehardy as i see all references to `KEY_CRASHLYTICS_DEBUG_ENABLED` were removed in 8.0.0 except in Constants, i am not sure if this is the intended behaviour or not. 
we can use `setCrashlyticsCollectionEnabled` to disable it in debug.
