### ISSUE TITLE
<GoogleMobileAds/GADAdDelegate.h> file not found

### ISSUE THREAD

**Issue by GH974** [invertase/react-native-firebase#435]
### Issue

 Podfile error
/node_modules/react-native-firebase/ios/RNFirebase/admob/RNFirebaseAdMob.h:12:9: 'GoogleMobileAds/GADAdDelegate.h' file not found

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOs Sierra

3. Build Tools: Xcode

4. React Native version: 0.48.3

5. RNFirebase Version: 2.2.0

6. Firebase Module: admob

**Comment by kishanj918** [comment]
remove that line and it should work.

**Comment by chrisbianca** [comment]
As @kishanj918 says, as a temporary solution you can remove the line and everything will work as expected.

The latest version of the Google Ad SDK has removed this file. I’ll get a release out later this morning with a fix.

**Comment by GH974** [comment]
Ok thanks, after remove this, i have found new error compilation

#0	0x0000000109efada1 in facebook::react::RCTNativeModule::invokeInner(unsigned int, folly::dynamic const&&) at /node_modules/react-native/React/CxxModule/RCTNativeModule.mm:109

**Comment by chrisbianca** [comment]
@GH974 @kishanj918

Just published v2.2.2 which will resolve the initial issue.

@GH974 That doesn't look like a compilation error - we'll need more information, e.g. a proper stack trace to be able to help.  Feel free to open a new issue or try asking for some help on our Gitter.

**Comment by GH974** [comment]
Ok thanks. I create new issue
