### ISSUE TITLE
🔥 [🐛] onNotificationOpenedApp  and getInitialNotification only work for APNs messages sent via FCM

### ISSUE THREAD

**Issue by bdrobinson** [invertase/react-native-firebase#4350]
## Issue

I've been integrating the `react-native-firebase` messaging SDK for iOS, and I'm trying to respond to when a user taps on a notification to open the app, using `onNotificationOpenedApp` and `getInitialNotification`. The problem I'm having is that **when the notification has been sent directly via APNs (rather than via FCM), the callback is not triggered**, whereas when I send the notification via FCM it *is* triggered.

I dug into the source code and I found these `if` statements that explain what's happening:
https://github.com/invertase/react-native-firebase/blob/743edf8f39f2887190b4a078d41c77e861cfa1d9/packages/messaging/ios/RNFBMessaging/RNFBMessaging%2BAppDelegate.m#L112

https://github.com/invertase/react-native-firebase/blob/743edf8f39f2887190b4a078d41c77e861cfa1d9/packages/messaging/ios/RNFBMessaging/RNFBMessaging%2BUNUserNotificationCenter.m#L67

https://github.com/invertase/react-native-firebase/blob/743edf8f39f2887190b4a078d41c77e861cfa1d9/packages/messaging/ios/RNFBMessaging/RNFBMessaging%2BUNUserNotificationCenter.m#L89

Essentially – APNs messages that are *not* sent via FCM are discarded (I was able to verify this by adding an `else` statement).

Is this intended behaviour? I imagine you may be doing this to keep the project's scope well-bounded – in which case I'm happy to write my own extension to intercept non-FCM APNs messages and pass them up to JS. However I've been having trouble working out how to do that, as the RNFB integration is quite "magical" with method swizzling etc so it's hard to know (a) where I'm able to hook my code in and (b) whether that's a safe thing to do.

So it'd be really useful if there was some clear documentation about:
1. The fact that pure APNs messages will not be passed to `onNotificationOpenedApp`
2. Advice on workarounds in order to intercept pure APNs messages.

@Ehesp @Salakar I hope you don't mind me tagging you here, but your names came up on `git blame` for the above lines so I thought you might have a good idea what's going on.

Thanks very much for your hard work!

**Comment by mikehardy** [comment]
I recommend using a full featured 3rd party notification package. I'm aware of 3 that work, react-native-push-notification, react-native-notifications (I think?) and notifee

**Comment by bdrobinson** [comment]
Yeah I'd actually previously been using `react-native-notifications` (and have been pretty happy with it) but our team *are* planning to start sending notifications via FCM, so the reason we're trying to integrate the FCM SDK is to generate FCM tokens and get analytics reporting etc for those FCM notifications – it's just we also use some services that send notifications via APNs that we want to be able to respond to.

**Comment by mikehardy** [comment]
:thinking: So, even with 3rd party notification packages you are unable to get any response to on any notification handler? With react-native-notifications would not the same hooks be available, and they should still contain the same payload and allow for attribution? That's supposition on my part, I'm just surprised if you have a notification package that you don't have your handlers hooked on notification taps

I'm not sure what precisely the use case is that's missing, in combo with a 3rd party notification package

**Comment by bdrobinson** [comment]
Yeah I understand that you wouldn't want to add it to the library. In the end I decided not to use RNFB for FCM and instead directly integrated the `Firebase/Messaging` SDK in Obj-C, which made the stack a little simpler.

I do think it would be helpful if the docs made it clearer that FCM for RNFB won't pick up messages sent directly via APNs – my assumption was that since FCM on iOS is mostly just a wrapper around APNs it would be able to handle them just the same. But will close this now – thanks very much for your help!
