### ISSUE TITLE
* What went wrong: A problem occurred configuring project ':@react-native-firebase_firestore'. > compileSdkVersion is not specified.

### ISSUE THREAD

**Issue by BalakumaranNatrajan** [invertase/react-native-firebase#4354]
* What went wrong:
A problem occurred evaluating project ':@react-native-firebase_firestore'.
> :@react-native-firebase_firestore has not defined a default in project.ext.'react-native'.versions.android.compileSdk in its build.gradle file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':@react-native-firebase_firestore'.
> compileSdkVersion is not specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

**Comment by BalakumaranNatrajan** [comment]
* What went wrong:
A problem occurred evaluating project ':@react-native-firebase_firestore'.
> :@react-native-firebase_firestore has not defined a default in project.ext.'react-native'.versions.android.compileSdk in its build.gradle file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':@react-native-firebase_firestore'.
> compileSdkVersion is not specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

**Comment by mikehardy** [comment]
You're most likely just using old versions of the module, you need to upgrade them *all* to current stable. There are other issues in this repository that are similar I believe.

If that doesn't do it (though I hope it will) - you should log a fresh issue but this time don't delete the template, fill in the details so we can troubleshoot
