### ISSUE TITLE
[Docs] "Getting Started" sidebar link broken

### ISSUE THREAD

**Issue by easyaspi314** [invertase/react-native-firebase#4357]
It appears that the "Getting Started" link on the documentation page has an empty `href`, and thus it will always go to the page the user is on.
![image](https://user-images.githubusercontent.com/6258309/95116211-adb51c00-0714-11eb-8a5f-f3d2e8135f86.png)

**Comment by mikehardy** [comment]
All the source is here: https://github.com/invertase/react-native-firebase/tree/master/docs

I think this is the same as #4220 

If you can find a root cause for this and propose a fix it would be very very helpful :pray:

**Comment by easyaspi314** [comment]
Hmm. Apparently, "Getting Started" is supposed to point to `index.html`, but it doesn't.

**Comment by easyaspi314** [comment]
Wayback machine indicates that it is between July 10 and August 23. 

I am *guessing* it might have to do with aaebe42e4b5e73097be8ab869b2c3d913f60dc7a, as there was a removal of `typedoc`.

**Comment by mikehardy** [comment]
it was definitely related to that, we also switched hosts, it was a massive change to the whole thing even though the intention was it looked and worked the same in the end. Any solution will have to come from first principles reasoning vs bisect unfortunately

**Comment by DoctorJohn** [comment]
I'm almost certain the following line is causing the issue:

https://github.com/invertase/react-native-firebase/blob/aaebe42e4b5e73097be8ab869b2c3d913f60dc7a/website/src/components/Link.tsx#L72

**Comment by mikehardy** [comment]
I think - not 100% sure but think - that if you try a patch on that in a PR it will get auto-published in testing form to Vercel (the web host) for easy testing

**Comment by DoctorJohn** [comment]
Links work as expected in the preview.
