### ISSUE TITLE
🔥[🐛] iOS Quit State data only cloud message not arriving

### ISSUE THREAD

**Issue by supermar1010** [invertase/react-native-firebase#4358]
## Issue

My android app works flawless. But under iOS I'm experiencing the issue, that the push notifcation are not delivered when the app is in quit state. How I enter the quit state, I start the app, and then restart the device. Then in my understanding, there should still be push notifications. Is there any other way to force iOS to quit the app?

It works without problems if I just put the app in background state

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `index.js`:

```js
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import {initBackgroundGeolocation} from './src/services/location/location-api-client';
import {loadStore, store} from './src/store';
import {openLocationStreamAsync} from './src/store/actions/businessActions';
import BackgroundGeolocation from 'react-native-background-geolocation';
import {logDebug, logInfo} from './src/services/logger-service';
import messaging from '@react-native-firebase/messaging';
import {registerBackgroundNotificationEvents} from './src/services/local-notification-service';
import {onNotification} from './src/services/remote-notification-service';

messaging().setBackgroundMessageHandler(async remoteMessage => {
  await loadStore();
  await onNotification(remoteMessage, store.dispatch);
  logInfo('Message handled in the background!', remoteMessage);
});

registerBackgroundNotificationEvents(store.dispatch);

AppRegistry.registerComponent(appName, () => App);

initBackgroundGeolocation();

const BackgroundGeolocationHeadlessTask = async event => {
  const params = event.params;
  logInfo('[BackgroundGeolocation HeadlessTask] -', event.name, params);

  switch (event.name) {
    case 'location':
      logDebug('[BackgroundGeolocation HeadlessTask] - gotCurrentPosition:', params.coords);
      store.dispatch(
        openLocationStreamAsync.success({
          latitude: params.coords.latitude,
          longitude: params.coords.longitude,
        }),
      );
      break;
  }
};

BackgroundGeolocation.registerHeadlessTask(BackgroundGeolocationHeadlessTask);

```

#### `package.json`:

```json
{
  "version": "0.0.1",
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
  },
  "dependencies": {
    "@notifee/react-native": "^0.12.1",
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/datetimepicker": "^2.4.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-firebase/app": "^8.4.5",
    "@react-native-firebase/messaging": "^7.8.10",
    "@react-navigation/native": "^5.2.4",
    "@react-navigation/stack": "^5.2.19",
    "i18next": "^19.1.0",
    "immer": "^7.0.7",
    "lodash": "^4.17.20",
    "lottie-ios": "^3.1.8",
    "lottie-react-native": "^3.5.0",
    "parse": "^2.13.0",
    "react": "16.13.1",
    "react-dom": "~16.9.0",
    "react-i18next": "^11.3.1",
    "react-native": "0.63.2",
    "react-native-background-fetch": "^3.1.0",
    "react-native-background-geolocation": "^3.8.1",
    "react-native-device-info": "^5.6.1",
    "react-native-elements": "^2.2.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.7.0",
    "react-native-vector-icons": "7.0.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-observable": "^1.2.0",
    "redux-persist": "^6.0.0",
    "rn-swipe-button": "^1.3.0",
    "rxjs": "^6.5.4",
    "typesafe-actions": "^5.1.0",
    "util": "^0.12.3"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/plugin-proposal-numeric-separator": "^7.10.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.159",
    "@types/parse": "^2.12.1",
    "@types/react": "^16.9.20",
    "@types/react-native": "^0.60.31",
    "@types/react-redux": "^7.1.7",
    "@types/react-test-renderer": "16.9.1",
    "@typescript-eslint/eslint-plugin": "^2.12.0",
    "@typescript-eslint/parser": "^2.12.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-prettier": "^3.1.2",
    "jest": "^25.1.0",
    "jest-mock-extended": "^1.0.9",
    "jetifier": "^1.6.5",
    "metro-react-native-babel-preset": "^0.59.0",
    "prettier": "^1.19.1",
    "react-test-renderer": "16.13.1",
    "ts-jest": "^26.1.0",
    "typescript": "^3.7.3"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'reactNativeTsRxjsBoilerplate' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'reactNativeTsRxjsBoilerplateTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end


target 'reactNativeTsRxjsBoilerplate-tvOS' do
  # Pods for reactNativeTsRxjsBoilerplate-tvOS

  target 'reactNativeTsRxjsBoilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

```

#### `AppDelegate.mswift:

```swift
//
//  AppDelegate.swift
//  reactNativeTsRxjsBoilerplate
//

import UIKit
import Firebase

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate, RCTBridgeDelegate {
  
  var window: UIWindow?
  
  // MARK: - UIApplicationDelegate
  
  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    let properties = RNFBMessagingModule.addCustomProps(toUserProps: nil, withLaunchOptions: launchOptions)
    
    let bridge: RCTBridge = RCTBridge(delegate: self, launchOptions: launchOptions)
    let rootView: RCTRootView = RCTRootView(bridge: bridge, moduleName: "reactNativeTsRxjsBoilerplate", initialProperties: properties)
    rootView.backgroundColor = UIColor.white
    
    self.window = UIWindow(frame: UIScreen.main.bounds)
    let rootViewController = UIViewController()
    rootViewController.view = rootView
    self.window?.rootViewController = rootViewController
    self.window?.makeKeyAndVisible()
    FirebaseApp.configure()
    
    TSBackgroundFetch.sharedInstance()?.didFinishLaunching()
    return true
  }
  
  // MARK: - RCTBridgeDelegate

  func sourceURL(for bridge: RCTBridge!) -> URL! {
    #if DEBUG
    return RCTBundleURLProvider.sharedSettings()?.jsBundleURL(forBundleRoot: "index", fallbackResource: nil)
    #else
    return Bundle.main.url(forResource: "main", withExtension: "jsbundle")
    #endif
  }
}

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ x ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ x ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A

```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**json sent to node-gcm:**

```json
{
   "priority":"high",
   "data":{
      "data":{
         "someData":"asdf",
         "someOtherData":"gtfrd"
      },
      "push_id":"9SD4f4lY4e",
      "time":"2020-10-06T07:43:31.764Z"
   },
   "contentAvailable":true
}
```

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 180.45 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.1.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 21, 22, 23, 26, 27, 28, 29
      Build Tools: 23.0.1, 24.0.1, 26.0.1, 28.0.3, 29.0.2, 29.0.3
      System Images: android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ x ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^8.4.5`
- **`Firebase` module(s) you're using that has the issue:**
  - `Cloud Messaging ^7.8.10`
- **Are you using `TypeScript`?**
  - `Y` & `3.7.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there!

You are using 'await' in an async with no try/catch -> always a red flag for me. I give that a near-zero chance it's your problem but danger...danger...

Your dependencies and podfile and AppDelegate not only look up to date and clean, you make me want to change from AppDelegate.m to AppDelegate.swift, that looks so much nicer. I did think you wanted to do the Firebase configure first thing though? Or right after you do the headless launch options injection. I doubt that is the problem but it has a non-zero chance of being the problem.

I believe the most likely thing is that are not sending the content-available APNS-specific payload key in your data-only cloud message.

To start I want to be very very very precise about terms, they need to match the documentation:
- you are sending a cloud message (it's not a notification, that's a type of payload)
- it is a data-only message (it's not necessarily silent, as you can trigger a notification from it...)
- you assert it is not arriving but it may just not be waking up the app - that's semantics though I recognize.

So you send a data-only cloud message and your handler is not called, yes?

Here's the next troubleshooting step:

Make a small shell script using command line utility curl to send hand-crafted JSON to the FCM (firebase cloud message) REST API end point. There are examples online of doing this.

Post that here but do not post the device token or your API key of course. When we see the JSON we'll know the contents are correct. rnfirebase.ios messaging contains a hint on content-available payload key and that's my hunch

Slightly less probably is that you haven't enabled the background mode of messaging and rebuilt the app with fresh entitilements and everything, or that you are running it on a simulator (will never work, has to be a real device) or your app is being thermally or power throttled and not starting the app (launching it from Xcode so you can see the app log is required so you can see if this is the case)

**Comment by supermar1010** [comment]
Hi,

thank you for your answer. 

I moved the firebase configure to be the first thing to be done, unfortunately it did not fix my problem.

Yes I'm sending data-only messages and my handler is not called, and the app is not awoken. 

For the shell script I'm sending for testing dircetly to aps:

``bash
#!/bin/bash

PAYLOAD="{\"aps\":{\"content-available\" : 1, \"foo\":\"bar\"}}"
# PAYLOAD="{\"aps\":{\"alert\":\"Hello\"}}"

TEAMID=""
KEYID=""
SECRET=""
BUNDLEID=""
DEVICETOKEN=""

function base64URLSafe {
  openssl base64 -e -A | tr -- '+/' '-_' | tr -d =
}

function sign {
  printf "$1"| openssl dgst -binary -sha256 -sign "$SECRET" | base64URLSafe
}

time=$(date +%s)
header=$(printf '{ "alg": "ES256", "kid": "%s" }' "$KEYID" | base64URLSafe)
claims=$(printf '{ "iss": "%s", "iat": %d }' "$TEAMID" "$time" | base64URLSafe)
jwt="$header.$claims.$(sign $header.$claims)"

# Development server: api.sandbox.push.apple.com:443
#
# Production server: api.push.apple.com:443

ENDPOINT=https://api.sandbox.push.apple.com:443
URLPATH=/3/device/

URL=$ENDPOINT$URLPATH$DEVICETOKEN

curl -v \
   --http2 \
   --header "authorization: bearer $jwt" \
   --header "apns-topic: ${BUNDLEID}" \
   --data "${PAYLOAD}" \
   "${URL}"
```

What I see is, my handler in swift gets called, when the app is in the background. But when it is quit, for example after a device restart, it is not. I'm checking that by making a get request to a webservice. So the problem seems to be a failure of iOS to call the handler at all, not just for the react-native part. Do you have any idea

```swift
 func application(_ application: UIApplication,
  didReceiveRemoteNotification userInfo: [AnyHashable : Any],
  fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void){
    print("Received in background: \(userInfo)")
    // Simple webservice showing http requests
    let url = URL(string: "https://webhook.site/abcde/iosHandler")!
    var request = URLRequest(url: url)
    request.httpMethod = "GET"
    let task = URLSession.shared.dataTask(with: request) { (data, response, error) in
        // Check if Error took place
        if let error = error {
            print("Error took place \(error)")
            return
        }
        
        // Read HTTP Response Status code
        if let response = response as? HTTPURLResponse {
            print("Response HTTP Status code: \(response.statusCode)")
        }
        
        // Convert HTTP Response Data to a simple String
        if let data = data, let dataString = String(data: data, encoding: .utf8) {
            print("Response data string:\n \(dataString)")
        }
        
    }
    task.resume()
    completionHandler(.noData)
 }
```

Capabilities enabled are Push Notifications and in Background modes: Background Processing, Remote notifications, Background fetch and some other unrelated.

For the thermal throttling, I guess that's not the case, as the device is mostly charging while testing.
I don't see any special log output, so I guess not throttling?

**Comment by mikehardy** [comment]
Everything seems fine, if there is different behavior across device restart I'm not sure what to say - I'm not sure what would cause that difference

**Comment by mikehardy** [comment]
For reproduction, it would be easier to figure out if there was just a paste of the fully constructed JSON (without API/device keys of course)
