### ISSUE TITLE
Bug compilation React

### ISSUE THREAD

**Issue by GH974** [invertase/react-native-firebase#436]
### Issue

After build and app launch, xcode stopped app, and generating error and opened this file Librarie/React.xcodeproj/React/CxxModule/RCTNativeModule.mm/RCTNativeModule::invokelnner(unsineg int methodId, const folly::dynamic && params)
```
NSArray *objcParams = convertFollyDynamicToId(params);
  @try {
    id result = [method invokeWithBridge:m_bridge module:m_moduleData.instance arguments:objcParams];
    return convertIdToFollyDynamic(result);
  }
  @catch (NSException *exception) {
    // Pass on JS exceptions
    if ([exception.name hasPrefix:RCTFatalExceptionName]) {
      @throw exception;
    }

    NSString *message = [NSString stringWithFormat:
                         @"Exception '%@' was thrown while invoking %s on target %@ with params %@",
                         exception, method.JSMethodName, m_moduleData.name, objcParams];
    RCTFatal(RCTErrorWithMessage(message));
  }
```
=> Thread 6: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0

### Environment

1. Application Target Platform:  iOS

2. Development Operating System: macOs SIerra

3. Build Tools: Xcode

4. React Native version: 0.48.3

5. RNFirebase Version:  2.2.2

6. Firebase Module: N/A

**Comment by waisbek** [comment]
Any update about how to solve?
