### ISSUE TITLE
Exception 'Nested arrays are not supported' was thrown while invoking documentSet on target RNFBFirestoreDocumentModule with params

### ISSUE THREAD

**Issue by kresogalic8** [invertase/react-native-firebase#4371]
I am using the latest version of the packages and I am getting this error. I am sending this in the request: 

![Screenshot 2020-10-08 at 17 12 54](https://user-images.githubusercontent.com/7289406/95478210-8b780400-0989-11eb-8a2c-520f8775fd8a.png)

Here is the code i am using: 

![Screenshot 2020-10-08 at 17 15 09](https://user-images.githubusercontent.com/7289406/95478504-df82e880-0989-11eb-9e66-3461833c1849.png)

**Comment by mikehardy** [comment]
There is an issue template for a reason, and text is strongly preferred over images
Please log a new issue following the template, and if there is a crash, please post a stack trace
