### ISSUE TITLE
https://rnfirebase.io/docs is NOT FOUND !!

### ISSUE THREAD

**Issue by Moji0098** [invertase/react-native-firebase#4378]
in the origin page of _react-native-firebase_ exist a link https://rnfirebase.io/docs that has NOT FOUND error !!

**Comment by saptaksengupta** [comment]
Hi @Moji0098 can I work on it ?

**Comment by mikehardy** [comment]
Please provide the source link so we may examine @Moji0098

**Comment by Moji0098** [comment]
@mikehardy https://www.npmjs.com/package/react-native-firebase

**Comment by mikehardy** [comment]
Oh interesting. That's for the v5 package, we don't support that anymore, the package as moved on quite a bit and is now namespaced with the core package here https://www.npmjs.com/package/@react-native-firebase/app

We should put in some sort of redirect though, we understand some people haven't had the time to migrate yet and a 404 is an unfortunate experience. It should redirect to https://v5.rnfirebase.io/docs/v5.x.x/getting-started

@Salakar two questions - 1) how do we implement a custom 404 page on Vercel? It's stock right now 2) how do we implement a redirect to another site so we can (at least temporarily) handle this one - is it in here? https://github.com/invertase/react-native-firebase/blob/master/website/redirects.json
