### ISSUE TITLE
access_token is not for this project (Google Sign In)

### ISSUE THREAD

**Issue by NathHorrigan** [invertase/react-native-firebase#438]
So I'm trying to signIn with but I'm getting the following error: `access_token audience is not for this project `

Here is my code:

```
GoogleSignin.signIn()
      .then((user) => {
        const credential = this.props.firebase.auth.GoogleAuthProvider.credential(null, user.accessToken);
        this.props.firebase.auth().signInWithCredential(credential)
            .then((user) => {
                alert("We did it!!")
                console.log('User successfully signed in', user)
            })
            .catch((err) => {
                alert("Fuck!! " + err)
                console.error(err);
            });
      })
      .catch((err) => {
         alert("err " + err)
      })
      .done()
```

### Environment

1. Application Target Platform:  Android

2. Development Operating System: macOS Sierra

3. Build Tools: SDK 23

4. React Native version: 
react-native-cli: 2.0.1
react-native: 0.48.3

5. RNFirebase Version:  2.2.0

6. Firebase Module:  All

**Comment by chrisbianca** [comment]
This sounds like a configuration issue.  Is the app that's being signed into using GoogleSignIn linked to your firebase project?

**Comment by NathHorrigan** [comment]
Yes - Key's and Config files are correct and sha-1 hash is entered in firebase settings

**Comment by NathHorrigan** [comment]
Issue resolved itself. I'm guessing some sort of backend issue?! 😕
