### ISSUE TITLE
[admob] this.native.setRequestConfiguration is not a function

### ISSUE THREAD

**Issue by nunonam** [invertase/react-native-firebase#4386]
## Issue

I use React Native 0.63.2 + @react-native-firease/admob v7.6.8.
when call admob().setRequestConfiguration, 
**"this.native.setRequestConfiguration is not a function"**
error happen 

and when use BannerAd, 
**"ReactNativeFirebaseAdMobBannerView" was not found in the UIManager.** 
error happen.

and this issue was happened on only ios, android is working well

**App.js**
```
import admob, { MaxAdContentRating } from '@react-native-firebase/admob';

admob().setRequestConfiguration({
      maxAdContentRating: MaxAdContentRating.T,
      tagForChildDirectedTreatment: false,
      tagForUnderAgeOfConsent: false,
    });
```

**Banner.js**
```
import {
  BannerAd,
  BannerAdSize,
  TestIds,
} from '@react-native-firebase/admob';

<BannerAd
    unitId={adUnitId}
    size={BannerAdSize.FULL_BANNER}
    requestOptions={{
        requestNonPersonalizedAdsOnly: true,
    }}
/>
```

I followed install instruction of @react-native-firebase/admob

**package.json**
```
    "@react-native-firebase/admob": "^7.6.8",
    "@react-native-firebase/analytics": "^7.6.7",
    "@react-native-firebase/app": "^8.4.5",
    "@react-native-firebase/dynamic-links": "^7.5.9",
    "@react-native-firebase/messaging": "^7.9.0",
    "@react-native-firebase/storage": "^7.4.9",
```

**podfile**
```
pod 'RNFBAdMob', :path => '../node_modules/@react-native-firebase/admob'
```

**Comment by mikehardy** [comment]
Best guess is forgot `cd ios && pod install`

**Comment by nunonam** [comment]
@mikehardy  thanks for your reply.
but I already do this "cd ios && pod install"
additionally, clean pod and re-install all pod dependancy, 
but issue is still happening.

is there nobody struggling with this issue except me? :(

**Comment by mikehardy** [comment]
No other reports, no.
Also this works https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

It exercises admob a bit https://github.com/mikehardy/rnfbdemo/blob/fc7e943ca95fe1777300985f31db2a075d2da4a5/make-demo.sh#L154

**Comment by nunonam** [comment]
It was fixed after uninstall and reinstall ios app but dont know why
