### ISSUE TITLE
🔥[🐛] Emails are not localized

### ISSUE THREAD

**Issue by jordynchuhaloff** [invertase/react-native-firebase#4389]
## Issue

We're using RN Firebase to send email sign-in links and email verification links.

Both features are working as expected, except that they are always being sent in English, even when we've set a different language with RN Firebase auth.

Any help would be appreciated!

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### Setting the language like this:
```
import auth from "@react-native-firebase/auth";
auth().languageCode ='es';
```

#### Sending the sign-in link like this:
```
auth().sendSignInLinkToEmail(email, {
    dynamicLinkDomain: '[app].page.link',
    url: `https://[app].page.link/email-auth`,
    android: { installApp: true, packageName: '[packageName]' },
    iOS: { bundleId: '[bundleId]' },
    handleCodeInApp: true,
  })
```

#### `package.json`:

```json
"@react-native-firebase/app": "^8.4.5",
"@react-native-firebase/auth": "^9.2.7",
"@react-native-firebase/dynamic-links": "^7.5.9",
```

</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/auth`
  - `@react-native-firebase/dynamic-links`
- **Are you using `TypeScript`?**
  - `Y` & `3.9.7`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I think it has to be set / is no longer a property, have you tried something like this?

```javascript
   firebase.auth().setLanguageCode(I18NService.currentLocale);
```

I swear I just tested this recently and it worked for me, after it came up for someone else

**Comment by jordynchuhaloff** [comment]
that worked! thank you!! :)

**Comment by mikehardy** [comment]
Excellent - thanks for reporting back - good luck with your project
