### ISSUE TITLE
FCM token is getting renewed on every launch of app in iOS app.

### ISSUE THREAD

**Issue by ayon-affle** [invertase/react-native-firebase#4390]
I was using a library which is converting my device token into FCM token and I was getting the same FCM token on every launch of the application.
But after adding the RNFirebase library, the FCM is getting modified on every launch of the application. It is first showing the old FCM token and after that showing new FCM token

`2020-10-14 10:52:01.169329+0600 rnfirebasedemo[1580:475840] FCM token: d9IEzMfMlUKxsZSaDeUOxO:APA91bHHMLoMkekuI4z0GsJyKoQoL4CS7vXRCYcX7uEUhlQNn4NtvYRz-94Vb_KybJxZHaZkMShedGwcXz25YdzvX3Db5x-3vazx9jJK6LCReX4ex22UEzE-q-7H9heOEV2jPgcmCUdU
2020-10-14 10:52:01.653623+0600 rnfirebasedemo[1580:476051] [] nw_socket_handle_socket_event [C6:1] Socket SO_ERROR [61: Connection refused]
2020-10-14 10:52:01.653900+0600 rnfirebasedemo[1580:476055] [] nw_connection_get_connected_socket [C6] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-10-14 10:52:01.653935+0600 rnfirebasedemo[1580:476055] TCP Conn 0x2827cc540 Failed : error 0:61 [61]
2020-10-14 10:52:01.695533+0600 rnfirebasedemo[1580:476073] [javascript] Running "rnfirebasedemo" with {"rootTag":1,"initialProps":{}}
2020-10-14 10:52:01.732484+0600 rnfirebasedemo[1580:476073] [javascript] 'Authorization status:', 1
2020-10-14 10:52:02.446062+0600 rnfirebasedemo[1580:475840] FCM token: db3uPFS62EEhtgUwb5yamC:APA91bH8e7BMAu9wzeVkCyPHSLCysIWMEsaiBTrb3Hu7-H9a-8NNaV2w8QrHTXuwCrBmznM46xkf4l_HMCk9QTXvP_rlaH2tnWmQ1qgetaEN906L8Xdt2s6TWl5HXkwR514Ms9IcjKD4`

why the FCM token is getting renewed on every launch? Is there any correction available to fix this issue?

**Comment by mikehardy** [comment]
Is it an issue? Does the new token work? Unsure on other libraries, obviously we can only support this library. Otherwise since you skipped the whole template there's no action here

**Comment by ayon-affle** [comment]
@mikehardy 
Sorry for inappropriate use of word. Yes, you are right it's not an issue but an unexpected behaviour. So, is this expected behaviour for RNFirebase library?

**Comment by mikehardy** [comment]
@ayon-affle it does not happen in my app. My FCM tokens are relatively stable. It's possible to invalidate them and get a fresh one if you want though. Perhaps something in your app is doing that

**Comment by ayon-affle** [comment]
@mikehardy 
We have prepared a sample which includes RNFirebase library and it also has one native library which is also generating fcm token based on APNS token. Without rnfirebase react native app is working normally but with rnfirebase its genrating new fcm token on every launch.

The following link contains the sample app names as **rnFirebaseDemo**:
[rnFirebaseDemo](https://bitbucket.org/vizury/vizury-react-native/src/9b6e4479206d38859231fde57a7c650e30d6fabe/?at=RNFirebase%2FrnFirebaseDemo)

Here is the video of that:
https://drive.google.com/drive/folders/126m9vIV887s1O9su9-TcowcihimoBZ77?usp=sharing

we are passing hard time with our clients. So if you can suggest something that will be really helpful.

**Comment by mikehardy** [comment]
@ayon-affle I feel with iOS you may need to integrate this: https://github.com/invertase/react-native-firebase/issues/4299#issuecomment-705128266 - it might have bearing (and your other versions are a little out of date, not a great effect but that link might be a great effect)

When I hear "also has one native library" I think "reproduce this with a pure react-native init project adding nothing but app + messaging".
