### ISSUE TITLE
Android installation documentation leads to ERROR "Google play services valid installation not found"

### ISSUE THREAD

**Issue by ChristianTucker** [invertase/react-native-firebase#44]
Here's an image of the error: [Gyazo Screencapture](https://gyazo.com/b1fee4a1ead069f0470b39d43f172d5c.png)

I've double checked the installation documentation several times, but just in-case I'll list my changes in the gradle files

Changes in `android/app/build.gradle`

```
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(':react-native-firebase')
}
...
apply plugin: 'com.google.gms.google-services' // Very bottom of file
```

Changes in `android/build.gradle`

```
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.google.gms:google-services:3.0.0'
    }
```

Changes in `settings/gradle`

```
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
```

Changes in `MainApplication.java`

```
import io.invertase.firebase.RNFirebasePackage;
...
return Arrays.<ReactPackage>asList(
    new MainReactPackage(),
    new RNFirebasePackage()
);
```

**google-services.json** is stored in `android/app` and in the Android SDK tools I have the following installed:

- Google Play APK Expansion library
- Google Play Billing Library
- Google Play Licensing Library
- Google Play services

**Comment by Ehesp** [comment]
This is due to Play Services not being available on the device/emulator, rather than your build. You need to download via SDK manager in Android Studio and rebuild with Google APIs installed:

![image](https://cloud.githubusercontent.com/assets/842078/24864239/7b76f9a8-1dfb-11e7-91ae-9325d1b38d04.png)

**Comment by ChristianTucker** [comment]
@Ehesp  You just brought it to my attention that even though I have all of the proper software installed, that because I'm using GenyMotion for emulation. There's special steps for installing Google Play Services on the device, so I'll mark this as closed.

**Comment by Ehesp** [comment]
Ah yes, probably worth having some FAQs somewhere, you're not the first person with that issue.
