### ISSUE TITLE
firebase.messaging is undefined

### ISSUE THREAD

**Issue by qmegas** [invertase/react-native-firebase#440]
Hi,

I'm trying to use firebase cloud messaging, but `firebase.messaging` is `undefined` (on Android).
I followed all installation instructions, but it doesn't work. There is not errors during compilation.
What I'm missing?

Some check list:

`app\build.gradle` following lines added:
```
compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile "com.google.firebase:firebase-core:11.2.0"
    compile "com.google.android.gms:play-services-base:11.2.0"
    compile "com.google.firebase:firebase-messaging:11.2.0"
```

`settings.gradle` following lines added:
```
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
```

`MainApplication.java`:
```
import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;

....

protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new RNFirebasePackage(),
          new RNFirebaseMessagingPackage()
      );
    }
```

### Environment

Development Operating System: Windows 10
React Native version: 0.48.4
RNFirebase Version: 2.2.2

**Comment by Salakar** [comment]
You need to export an intialized instance of firebase in JS, you can't import rnfirebase and just use it - not until version 3

**Comment by qmegas** [comment]
@Salakar 
I did that. Here is my code:
```
import firebase from 'react-native-firebase';

export default class Test extends Component {
	componentDidMount() {
		console.log(firebase); // [Function: Firebase]
		console.log(firebase.messaging); //Undefined
	}
...
}
```

**Comment by yashaRO** [comment]
I'm about to test it, but I'm thinking he meant this
https://invertase.io/react-native-firebase/#/v2/usage

`import RNFirebase from 'react-native-firebase';

const configurationOptions = {
  debug: true
};

const firebase = RNFirebase.initializeApp(configurationOptions);

export default firebase;`

You need to initialize literally RNFirebase in another file or something, and then the functions work off of it.

**Comment by qmegas** [comment]
@yashaRO 
Yes, you right. Missed that page in library documentation.
