### ISSUE TITLE
[🐛] Overriding Android Firebase BoM doesn't work 

### ISSUE THREAD

**Issue by MujtabaFR** [invertase/react-native-firebase#4400]
## Issue

I'm trying to override Android Firebase BoM version to 25.12.0 using [this code](https://rnfirebase.io/#android) in my `/android/app/build.gradle` file
```
project.ext {
  set('react-native', [
    versions: [
      // Overriding Build/Android SDK Versions
      android : [
        minSdk    : 16,
        targetSdk : 29,
        compileSdk: 29,
        buildTools: "29.0.3"
      ],

      // Overriding Library SDK Versions
      firebase: [
        // Override Firebase SDK Version
        bom           : "25.12.0"
      ],
    ],
  ])
}
```

after running `react-native run-android` and then `./gradlew app:dependencies` I'm getting the same old BoM version as if I didn't override anything

tried to put the code in different lines in the gradle file, but none of them worked

** editing `@react-native-firebase/app/package.json` and changing the BoM version directly works correctly

**Comment by mikehardy** [comment]
This is how I do it - I'm certain it works, it may be the documentation is slightly off on where to put it?

https://github.com/mikehardy/rnfbdemo/blob/fc7e943ca95fe1777300985f31db2a075d2da4a5/make-demo.sh#L40

**Comment by MujtabaFR** [comment]
Thanks, the problem is in the documentation indeed.
The documentation mentions to add the code to `/android/app/build.gradle` which won't work
it should be added to `/android/build.gradle` instead

I will send a PR to fix this issue
