### ISSUE TITLE
FCM Invalid Token

### ISSUE THREAD

**Issue by gurmukhp** [invertase/react-native-firebase#441]
### Environment

1. Application Target Platform: iOS

2. Development Operating System: Mac OS

3. Build Tools: Xcode

4. React Native version: 0.48.3

5. RNFirebase Version: 2.2.2

6. Firebase Module: Messaging

I've generated a P8 file from Apple Member platform and uploaded it to Cloud Messaging in Firebase.

I have then got the token and saved it to Firebase database.

If I use this device token I always get 'invalid registration token'.

Is the library returning the wrong token?

```
          firebase.messaging().getToken()
          .then((token) => {
            console.log('Device FCM Token: ', token);
            this.firebase.database().ref('tokens/user1/').set(token);
          });
```

**Comment by subinsuresh991** [comment]
Any updates on this?

**Comment by mikehardy** [comment]
@subinsuresh991 why would there be updates on an issue closed in 2017? When you make comments like this, it generates notifications for people, which is not awesome if there is no valuable content. In general what you see on github is what exists, so if you don't see anything on an issue, there's nothing to see.

**Comment by subinsuresh991** [comment]
@mikehardy It's closed without any comments. That's the reason I asked for any updates.

**Comment by mikehardy** [comment]
2017!
