### ISSUE TITLE
[📚] Add documentation on MFA like authentication flow

### ISSUE THREAD

**Issue by g4laura** [invertase/react-native-firebase#4418]
## Documentation Feedback

Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:

Since a lot of people are interested in multifactor authentication, I think it might be useful to add some documentation on that. I think it can be achieved with a flow like this (error handling not included):
```
// call on your first authentication page after user presses create account button
await auth().createUserWithEmailAndPassword(email, password);
// call after user enters phone number and presses send verification code button
const confirmation = await auth().verifyPhoneNumber(phone);
/// call after getting verification code from user
const credential = auth.PhoneAuthProvider.credential(
      confirmation.verificationId,
      code,
 );
// call after successful code verification, to resend code call the verifyPhoneNumber function again
await auth().currentUser.linkWithCredential(credential);

```
---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Something like that could work great - one thing I can mention is that there is an edit button at the top right of every documentation page, so you could take code similar to the above and add it as a new heading perhaps to the auth page in the form of a PR? The Github PR flow for docs is all on the web and almost satisfyingly easy to work through
