### ISSUE TITLE
[Question] Does AdMob have to be reinitialized after app is reopened from background?

### ISSUE THREAD

**Issue by wbattel4607** [invertase/react-native-firebase#442]
### Question
AdMob works fine when I initially launch the app, but if I put it in the background (press home) and then later return to it the (rewarded video) ads no longer load. Do I have to reinitialize admob if the app is opened from the background? I initialize it in componentWillMount  but I'm not sure where/if it would make sense to reinitialize it.

EDIT: After further thought, maybe I should use Appstate to detect a return to foreground from background? But I don't know if it's proper to initialize admob more than once in a lifecycle.

### Environment

1. Application Target Platform: Both

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode 9

4. React Native version: 0.45.1

5. RNFirebase Version: 2.1.3

6. Firebase Module: admob

**Comment by Ehesp** [comment]
Hmm, I can test this out properly. I'd imagine that the Admob SDK handles background state too to save battery/network. AppState should work though for now.

**Comment by wbattel4607** [comment]
Even when reinitializing with AppState, Admob doesn't serve any (Rewarded) ads after the app returns from background state. I can't be the first person to experience this, right? It seems like it would be a big issue for many apps using Admob.

**Comment by Salakar** [comment]
Thanks for reporting this issue. We're aware that AdMob has fallen behind on React Native Firebase and would like to bring it up to speed again. I will close this issue for now and track it as well as other issues collectively over on the `AdMob overhaul proposal` to be addressed in a future release. See #1259
