### ISSUE TITLE
:react-native-firebase_in-app-messaging has not defined a default in project.ext.'react-native'.versions.android.compileSdk in its build.gradle file.

### ISSUE THREAD

**Issue by bpfeiffer187** [invertase/react-native-firebase#4422]
After adding the package with yarn, and auto linking becuase we are on react 61,

we get the following error:
:react-native-firebase_in-app-messaging has not defined a default in project.ext.'react-native'.versions.android.compileSdk in its build.gradle file.

i think the issue is becuase the min max sdk version in the in-app-messaging dynamic. the analytics package for example specifies the numbers instead.

**messaging**
project.ext {
  set('react-native', [
    versions: [
      android : [
        **minSdk    : jsonMinSdk,
        targetSdk : jsonTargetSdk,
        compileSdk: jsonCompileSdk,**
        // optional as gradle.buildTools comes with one by default
        // overriding here though to match the version RN uses
        buildTools: jsonBuildTools
      ],

**analytics**
project.ext {
  set('react-native', [
    versions: [
      android : [
        **minSdk    : jsonMinSdk,
        targetSdk : jsonTargetSdk,
        compileSdk: jsonCompileSdk,**
        // optional as gradle.buildTools comes with one by default
        // overriding here though to match the version RN uses
        buildTools: jsonBuildTools
      ],

anyone else running into this?

**Comment by mikehardy** [comment]
You skipped the template?
It works, clone this and prove it to yourself in your environment, though you'll have to change the script to show in RN61 which is more than a year old(?), we're on RN63 : https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

If you had not ignored the template we'd have more information to go on.
