### ISSUE TITLE
[🐛] For android while updating a document we are getting "removed" instead of "updated" for android for react-native-firebase/firestore

### ISSUE THREAD

**Issue by amitmundrag08** [invertase/react-native-firebase#4427]
I am using react-native-fireabse/firestore v7.8.7 and while fetching data using the library for android getting DocumentChangeType as "removed" instead of "modified"

**Comment by mikehardy** [comment]
Ignores the template, so no help can be offered
If you re-open, please fill out the entire template and include an App.js that reproduces the problem
Suggestion before trying to reproduce, make sure that you are using the most up to date firebase-ios-sdk an firebase-android-sdk https://rnfirebase.io/#overriding-native-sdk-versions
