### ISSUE TITLE
🔥 [🐛] Topics messages not working on iOS

### ISSUE THREAD

**Issue by elkinjosetm** [invertase/react-native-firebase#4429]
## Issue

Messages sent to topics are not being received by the iOS app in any of the states (background or foreground) but the app **does** get subscribed to topics correctly and **does** receive push notifications.

#### Subscribe to topic implementation:

```javascript
const subscribeToTopic = async topic => {
    ...
    await firebase.messaging().subscribeToTopic(topic);
    ...
};
```

#### Subscription result

`https://iid.googleapis.com/iid/info/{DEVICE_TOKEN}?details=true`

```json
{
    "applicationVersion": "{app_version}",
    "application": "{ios_bundle_id}",
    "scope": "*",
    "authorizedEntity": "807465869556",
    "rel": {
        "topics": {
            "myTestTopic": {
                "addDate": "2020-10-21"
            },
        }
    },
    "platform": "IOS"
}
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/analytics": "^7.6.8",
    "@react-native-firebase/app": "^8.4.6",
    "@react-native-firebase/crashlytics": "^8.4.11",
    "@react-native-firebase/messaging": "^7.9.1",
    "@react-native-firebase/perf": "^7.4.9",
    ...
    "react-native": "0.63.3",
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "analytics_auto_collection_enabled": false,
    "crashlytics_auto_collection_enabled": false,
    "crashlytics_debug_enabled": true,
    "perf_auto_collection_enabled": false
  }
}
```

#### Subscribe to topic implementation:

```javascript
const subscribeToTopic = async topic => {
    ...
    await firebase.messaging().subscribeToTopic(topic);
    ...
};
```

#### Subscription result

`https://iid.googleapis.com/iid/info/{DEVICE_TOKEN}?details=true`

```json
{
    "applicationVersion": "{app_version}",
    "application": "{ios_bundle_id}",
    "scope": "*",
    "authorizedEntity": "807465869556",
    "rel": {
        "topics": {
            "myTestTopic": {
                "addDate": "2020-10-21"
            },
        }
    },
    "platform": "IOS"
}
```

</p>
</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '13.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

install! 'cocoapods', :deterministic_uuids => false

target 'App' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Third party Pods
  pod 'ZendeskSupportSDK', '~> 5.0.3'
  pod 'Permission-Notifications', :path => '../node_modules/react-native-permissions/ios/Notifications.podspec'
  pod 'Permission-LocationAlways', :path => '../node_modules/react-native-permissions/ios/LocationAlways.podspec'
  pod 'Permission-LocationWhenInUse', :path => '../node_modules/react-native-permissions/ios/LocationWhenInUse.podspec'
  pod 'Permission-Motion', :path => '../node_modules/react-native-permissions/ios/Motion.podspec'
  pod 'react-native-flipper', :path => '../node_modules/react-native-flipper', :configuration => 'Debug'

  target 'AppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!('Flipper' => '0.62.0')
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```

#### `AppDelegate.m`:

```objc
...
#import "Firebase.h"
...
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  ...
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];

  NSDictionary *appProperties = [RNFBMessagingModule addCustomPropsToUserProps:nil withLaunchOptions:launchOptions];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"App"
                                            initialProperties:appProperties];
  ...
  return YES;
}
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 39.78 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.21.0 - ~/.nvm/versions/node/v10.21.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v10.21.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 30
      Build Tools: 30.0.1
      System Images: android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6821437
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_144 - /usr/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^8.4.6`
- **`Firebase` module(s) you're using that has the issue:**
  - `Cloud Messaging` -> `"@react-native-firebase/messaging": "^7.9.1"`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by zrg-team** [comment]
any help

**Comment by zrg-team** [comment]
@elkinjosetm elk
https://iid.googleapis.com/iid/info/{DEVICE_TOKEN}?details=true
how to request to above API? 
it always returns 
```
{
"error": "MissingAuthorization"
}
```

**Comment by elkinjosetm** [comment]
> @elkinjosetm elk
> [https://iid.googleapis.com/iid/info/{DEVICE_TOKEN}?details=true](https://iid.googleapis.com/iid/info/%7BDEVICE_TOKEN%7D?details=true)
> how to request to above API?
> it always returns
> 
> ```
> {
> "error": "MissingAuthorization"
> }
> ```

You need to use your Firebase api key as the authorization of the request.

**Comment by zrg-team** [comment]
@elkinjosetm thanks. 
did you find the solution? 
I found that the problem came after unSubscribeToTopic and then Subscribe again. all push notifications will not receive any more.

**Comment by elkinjosetm** [comment]
No @zrg-team, I haven’t had the chance to keep digging in to this problem. In my case, the never stop receiving push notifications. Only topics messages are the ones that are not coming through. Even silent push notifications handled in background work fine.

**Comment by elkinjosetm** [comment]
I recently updated the project to the latest react-native-firebase version (`v10.0.0`) and can confirm the issue is still happening. Any update?

```json
"@react-native-firebase/analytics": "^10.0.0",
"@react-native-firebase/app": "^10.0.0",
"@react-native-firebase/crashlytics": "^10.0.0",
"@react-native-firebase/messaging": "^10.0.0",
"@react-native-firebase/perf": "^10.0.0",
```

**Comment by mikehardy** [comment]
There is no update, sorry. This is unfortunately not a priority for development at the moment so the best I can advise is to mentally shift frame to anything you can do to move it forward individually - my best recommendations for that are:

- reach right into node_modules directly and instrument the code with printouts of all the javascript (and underlying Java or Objective-C) API calls with arguments prior to the call and return values after so you are sure you understand the control flow and can determine if react-native-firebase is doing anything incorrect and report same here
- if react-native-firebase appears to be doing everything correctly, then move upstream by doing a quickstart so you can log an issue there - https://github.com/firebase/quickstart-ios/tree/master/messaging
