### ISSUE TITLE
Not able to open notification display documents

### ISSUE THREAD

**Issue by yudiz-vipul** [invertase/react-native-firebase#4433]
Please check the below links which are not working!
https://rnfirebase.io/messaging

**Comment by mikehardy** [comment]
Hi there @yudiz-vipul ! Can you show where this link is coming *from*? I see it as 404 yes but I don't know what page is linking to it? Also note that there is an edit button at the top right of every documentation so you can propose edits easily, and the GitHub web PR flow is very easy to work through
