### ISSUE TITLE
Share Authentication State between Main App and Extension in Ios - useUSerAccessGroup not working

### ISSUE THREAD

**Issue by pulkit-gsynergy** [invertase/react-native-firebase#4440]
## Issue

I am working on react-native and using react-native-firebase library for connecting to firebase. I have a main application and a share extension. I want to share the authentication state between the main application and the share extension. In android, it is not a problem as the share extension and the main app is able to communicate and the auth state is preserved there. But in Ios, I am unable to get access to the auth state even when I have signed-in in my main app. This is because of the security restrictions that they put where they treat both as different applications.
Then, I came across this method in @react-native-firebase/auth - "useUserAccessGroup", which states to share the auth state between two different applications. This perfectly suits my scenario. So, going ahead with this I created a keychain for both my main app and share extension and it looks like this in my entitlements file.

Main-app.entitlements

<key>keychain-access-groups</key>
	<array>
		<string>$(AppIdentifierPrefix)com.abc.xyz</string>
		<string>$(AppIdentifierPrefix)com.abc.xyz.share</string>
	</array>

Share-entension.entitlements

<key>keychain-access-groups</key>
	<array>
		<string>$(AppIdentifierPrefix)com.abc.xyz.mno.ShareExtension</string>
		<string>$(AppIdentifierPrefix)com.abc.xyz.share</string>
	</array>

Then, in the main app in the login function which I use to sign in with email-password, google sign-in, apple sign-in. I call this function:- 

import auth, { FirebaseAuthTypes } from "@react-native-firebase/auth";
.....
....
....
...
const loginThroughMedium = async () => {
       await auth().useUserAccessGroup("<TEAM_ID>.com.abc.xyz.share");
       // login code
}

The problem which I am facing is after I logout of my main app and sign in,I get an error :- 
[Error: [auth/keychain-error] An error occurred when accessing the keychain. The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary will contain more information about the error encountered]

I get the same error when I try to do-  await auth().useUserAccessGroup("<TEAM_ID>.com.abc.xyz.share"); in my share extension before any other code. 

#### `package.json`:

"dependencies": {
    ......
    ......
    "@react-native-firebase/analytics": "6.3.4",
    "@react-native-firebase/app": "6.3.4",
    "@react-native-firebase/auth": "6.3.4",
    "@react-native-firebase/crashlytics": "6.3.4",
    "@react-native-firebase/dynamic-links": "6.3.4",
    "@react-native-firebase/firestore": "6.3.4",
    "@react-native-firebase/functions": "6.3.4",
    "@react-native-firebase/messaging": "6.3.4",
    "@react-native-firebase/perf": "6.3.4",
    "@react-native-firebase/storage": "6.3.4",
    "react": "16.11.0",
    "react-native": "0.61.5",
    "react-native-share-extension": "2.0.0",

#### `ios/Podfile`:

- [x] I'm using Pods and my Podfile looks like:

platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'main-app' do
  # Pods for main-app
  ......
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'
  pod 'ReactNativeShareExtension', :podspec => '../node_modules/react-native-share-extension/ReactNativeShareExtension.podspec'

  target 'ShareExtension' do
    use_native_modules!
    inherit! :complete
  end

  use_native_modules!
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end

#### `AppDelegate.m`:

/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <Firebase.h>

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>

#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import "RNSplashScreen.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {

  BOOL handledFB =  [[FBSDKApplicationDelegate sharedInstance] application:application openURL:url options:options];

  BOOL handledRCT = [RCTLinkingManager application:application openURL:url options:options];

  return handledFB || handledRCT ;
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

    if ([FIRApp defaultApp] == nil) {
      [FIRApp configure];
    }

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"findz"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [RNSplashScreen show];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
  #if DEBUG
    return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  #else
    return [CodePush bundleURL];
  #endif
}

@end

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 97.45 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.13.1 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.61.5 => 0.61.5

- **Platform that you're experiencing the issue on**:
  - [x ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 6.3.4
- **`Firebase` module(s) you're using that has the issue:**
  - auth
- **Are you using `TypeScript`?**
  - Y : "typescript": "3.8.3"

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there - there is no active development in this area that I'm aware of. I can only advise that you shift to a mode of exploration - instrument the related code with some debugging (console output or debugger breakpoints) and inspect the exact error message plus the values of any underlying API calls and all their results to see what went wrong. That should point the way for a PR which we would be happy to merge if you could get a working setup

**Comment by pulkit-gsynergy** [comment]
So am I right to say that, there is an issue with the library code there!

**Comment by mikehardy** [comment]
@pulkit-gsynergy possibly? I don't use the APIs personally, and there is no development effort currently happening in the area or planned for it, thus my advice for you to dig in, with specific points on how to do so, that you might quickly help yourself and in the process develop a PR to help other library users

**Comment by pulkit-gsynergy** [comment]
Thanks @mikehardy

**Comment by sanghaya** [comment]
Hi @pulkit-gsynergy I'm experiencing exactly the same issue. And have tried to solve in bunch different ways including the bundle identifier fix and adding group name at the back that you've tried. But it seems like now the login is working for me with <TEAM.ID>.<BUNDLE.IDENTIFER>, but the catch is that it's letting even new Apple sign in be diverted to the same user without creating one (in the same device). The behavior is a bit hard to debug, so I'm exploring a new solution.

**Comment by MaxAst** [comment]
@pulkit-gsynergy did you end up solving this?
