### ISSUE TITLE
[🐛] 🔥 AdMob ServerSideVerificationOptions cannot be set after RewardedAd has been loaded

### ISSUE THREAD

**Issue by jeanbmar** [invertase/react-native-firebase#4443]
## Issue

When using ServerSideVerificationOptions, you want usually to load generic ads and populate the custom data depending on which action is triggering the ad show. 
This is not possible with the current behavior, since setServerSideVerificationOptions is [called at load time](https://github.com/invertase/react-native-firebase/blob/master/packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobRewardedModule.java).

As Google says [here](https://developers.google.com/admob/android/rewarded-video-ssv#custom_data): 
`If you want to set the custom reward string, you must do so before showing the ad.`

[Google API](https://developers.google.com/android/reference/com/google/android/gms/ads/rewarded/RewardedAd#public-void-setserversideverificationoptions-serversideverificationoptions-options) exposes setServerSideVerificationOptions as a RewardedAd instance method and doesn't say it should be set before the ad has been loaded.

I suggest to set serverSideVerificationOptions possibly from both rewardedLoad and rewardedShow options to fix the issue without breaking existing implementations.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Seems sensible - if you propose a PR we can merge it
