### ISSUE TITLE
[🐛] Android - Permission comes back from messaging().requestPermission() always return 1

### ISSUE THREAD

**Issue by DevArenaCN** [invertase/react-native-firebase#4445]
## Issue

For Android, permission that comes back from messaging().requestPermission() is always 1 even though the user turned off the permission in the settings. With V5 it would get the correct permission, this only happens after migrating to V6

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/app": "^8.4.5",
    "@react-native-firebase/messaging": "^7.9.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 19.72 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.22.0 - /usr/local/opt/node@10/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /Users/reverbnation/.rvm/gems/ruby-2.5.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-24 | Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_131 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 8.4.5`
- **`Firebase` module(s) you're using that has the issue:**
  - `Messaging`
- **Are you using `TypeScript`?**
  - `N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Interesting - this does not manifest for me because I use react-native-permissions to manage things, it's a dedicated repo that tracks API changes actively. Adults would disagree about this but I'd actually purge the API from here and rely on that exclusively as policy since it lets you track things fine-grained


The behavior is as documented: https://rnfirebase.io/reference/messaging#requestPermission and I suggest react-native-permissions if you want fine grained control over device-local permissions, or perhaps notifee.app etc - those are all full-featured players in the device-local notifications/permissions combination space

**Comment by DevArenaCN** [comment]
> Interesting - this does not manifest for me because I use react-native-permissions to manage things, it's a dedicated repo that tracks API changes actively. Adults would disagree about this but I'd actually purge the API from here and rely on that exclusively as policy since it lets you track things fine-grained
> 
> The behavior is as documented: https://rnfirebase.io/reference/messaging#requestPermission and I suggest react-native-permissions if you want fine grained control over device-local permissions, or perhaps notifee.app etc - those are all full-featured players in the device-local notifications/permissions combination space

So after carefully reading the documentation, it seems like messaging().hasPermission would return the correct value. I'm gonna switch to that instead. Thanks for the quick reply

**Comment by DevArenaCN** [comment]
I also should point out the doc for those still referenced as `firebase.messaging().hasPermission` which with the new version should be `messaging().hasPermission`, not sure if those need to be updated, if so I'd work on a PR this weekend

**Comment by mikehardy** [comment]
@DevArenaCN - it depends on how the imports are done in the examples but they should be consistent internally - if the docs are internally inconsistent with how they reference the symbols than a docs PR would be very welcome!

I'm going to close this as the original issue seems resolved...
