### ISSUE TITLE
[🐛]🔥  iOS onMessage not firing if FirebaseMessage contains Notification

### ISSUE THREAD

**Issue by cameroncharles** [invertase/react-native-firebase#4447]
## Issue
I am in the process of switching from v5 to v6+ and am using all the latest versions of react-native-firebase and 0.60.6 of React native itself, everything is working as expected with one exception.

On iOS the onMessage method is not triggered if the FirebaseMessage contains a Notification object, it works as expected otherwise, both data-only with appropriate headers etc and a message that ive simply removed the Notification object from trigger onMessage, and the other listeners/handlers are all working too, likewise no issue on Android.

The only thing i can think of is maybe its an RN 0.60.6 thing but we can not currently update any further then this to test.

## Project Files

Not sure any specific files will help here, i have a pretty standard setup that is currently just doing a console.warn when it runs and it runs as expected on Android so the Java side doesnt appear to be an issue, that said im not sure what may help so anything requested can be supplied

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:
The standard RN 0.60+ podfile but with some permission handler modules added
---
</details>

### Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 457.39 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.3.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
  IDEs:
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.6 => 0.60.6 
  npmGlobalPackages:
    react-native-cli: 2.0.1

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
    - "@react-native-firebase/app": "^8.4.6",
    - "@react-native-firebase/dynamic-links": "^7.5.10",
    - "@react-native-firebase/messaging": "^7.9.1",
- **`Firebase` module(s) you're using that has the issue:**
  - Messaging
- **Are you using `TypeScript`?**
  - No

</p>
</details>

---

**Comment by mikehardy** [comment]
Hi there! Not sure why you'd go through the pain of a RNFB 5 -> 6+ conversion and not also ramp your RN from 60 to 63, which I mention only because I think those version bumps were fairly easy and thus cost-efficient wins. I don't believe they'll have bearing on the issue though

There is a chart somewhere about what gets called when, I think it has bearing

https://rnfirebase.io/messaging/usage#receiving-messages

You may not have notification permission, or you may be in the wrong state. Note that there should be a fourth row in the table with current iOS/Android behavior where a "Force Quit" (swipe away in iOS or app info + force quit in Android) means that your app is dead and nothing will run it again until the user interacts with either a visible notification or starts the app from the regular home screen / launcher

**Comment by cameroncharles** [comment]
I spent a few more hours with this issue and it turns out it was another library we have in place that was breaking the onMessage flow or more specifically the ios firebase messaging flow at large, in our case it's Countly and their countly-sdk-react-native-bridge implementation, i'm not sure which library is "at fault" but given react-native-firebase has made multiple commits in regards to making sure i plays nice with others i'm inclined to believe its on Countly this time.

Anyway countly-sdk-ios has a preprocessor flag to turn off "push notification" related code, the react native library doesnt actually implement the flag so there's a couple things to fix up on that side of the library but i can confirm with it disabled everything functions as expected
