### ISSUE TITLE
Push Notifications broken iOS 11

### ISSUE THREAD

**Issue by gurmukhp** [invertase/react-native-firebase#445]
An update needs to be made to the completion handler to allow push notifications to be received on iOS:

**(void(^)(void)**

```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void(^)(void))completionHandler {
  [RNFirebaseMessaging didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}
```

This allows push notifications to be received when app is in background, but for some reason when the app is in suspended state, the push notifications are never received. Any idea why this is?

Here's an example:

```
    admin.messaging()
    .sendToDevice(token, {
      notification: {
        title: 'title',
        body: 'body',
      }
    }, {
      contentAvailable: true,
      priority: 'high',
      timeToLive: 60 * 30,
      show_in_foreground: true
    })
```

**Comment by jlsuarezs** [comment]
I have the same issue, any help? Thanks.

**Comment by lukaleli** [comment]
I have no push notifications on iOS 11.0.2 as well...

**Comment by lukaleli** [comment]
I found related issues on SO:
https://stackoverflow.com/questions/46391818/fcm-push-notifications-do-not-work-on-ios-11
https://stackoverflow.com/questions/46391818/fcm-push-notifications-do-not-work-on-ios-11

**Comment by chrisbianca** [comment]
Thanks @lukaleli, those SO articles indicate that this is a Firebase SDK issue which has been resolved in the latest version of the `FirebaseInstanceID` pod.  Check that you're running at least version 2.0.4.

Please re-open if you think there are still RNFirebase specific issues.

**Comment by lukaleli** [comment]
I am on 2.0.4 and the problem still persists...

**Comment by chrisbianca** [comment]
@lukaleli Have you had them working previously with RNFirebase or is this a new set up?

**Comment by lukaleli** [comment]
Nope. This is a new setup. It works for different iOS versions and Android, though.

**Comment by studiobrain** [comment]
```iOS 11.1.1
Using Firebase (4.6.0)
Using FirebaseAnalytics (4.0.5)
Using FirebaseCore (4.0.11)
Using FirebaseInstanceID (2.0.6)
Using FirebaseMessaging (2.0.6)
Using GoogleToolboxForMac (2.1.3)
Using Protobuf (3.4.0)
Using SwiftyJSON (4.0.0)
Using nanopb (0.3.8)``` I am unable to see the successful notifications...
