### ISSUE TITLE
[🐛] Bug Report Title - App not launched on clicking remote notification when in quit state

### ISSUE THREAD

**Issue by annucy** [invertase/react-native-firebase#4464]
## Issue

I have integrated the following
    "@react-native-firebase/app": "^8.4.5",
    "@react-native-firebase/messaging": "^7.9.0",

I am using react-native 60+

Remote notifications are displayed properly for me once App is in background or quit state(totally swiped out of memory). 

   --> When  App is is in background, and once notification is clicked, it launches App and onNotificationOpenedApp() is triggered
   --> But issue happens in android when  App is is in quit state. Once notification is clicked, it does **not** launch the App and hence getInitialNotification() is not triggered

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
  {
  "name": "app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "rnpm": {
    "assets": [
      "./src/assets/fonts/"
    ]
  },
  "dependencies": {
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/masked-view": "^0.1.5",
    "@react-native-community/netinfo": "^5.9.4",
    "@react-native-firebase/app": "^8.4.5",
    "@react-native-firebase/crashlytics": "^8.4.9",
    "@react-native-firebase/messaging": "^7.9.0",
    "amazon-cognito-identity-js": "3.2.1",
    "apollo-boost": "^0.3.1",
    "async": "2.6.0",
    "aws-appsync": "^4.0.1",
    "aws-appsync-react": "^4.0.1",
    "aws-sdk": "2.596.0",
    "expr-eval": "2.0.2",
    "graphql": "^14.2.1",
    "install": "^0.13.0",
    "libphonenumber-js": "1.7.30",
    "moment": "2.24.0",
    "moment-timezone": "^0.5.23",
    "react": "16.9.0",
    "react-apollo": "^2.5.6",
    "react-localization": "1.0.15",
    "react-native": "0.61.5",
    "react-native-a": "^1.0.1",
    "react-native-action-button": "2.8.4",
    "react-native-actionsheet": "^2.4.2",
    "react-native-communications": "2.2.1",
    "react-native-contacts": "^6.0.3",
    "react-native-country-picker-modal": "^1.10.0",
    "react-native-document-picker": "^3.5.2",
    "react-native-easy-toast": "1.1.0",
    "react-native-elements": "^3.0.0-alpha.1",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-gifted-chat": "0.6.0",
    "react-native-global-props": "^1.1.5",
    "react-native-image-crop-picker": "^0.35.1",
    "react-native-indicator": "^1.2.2",
    "react-native-keyboard-aware-scroll-view": "0.9.1",
    "react-native-keyboard-aware-view": "0.0.14",
    "react-native-local-auth": "^1.6.0",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-material-ui": "^1.30.1",
    "react-native-mime-types": "^2.3.0",
    "react-native-modal": "11.5.3",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-modalbox": "1.6.0",
    "react-native-open-settings": "1.0.1",
    "react-native-passcode-auth": "^1.0.0",
    "react-native-passcode-status": "1.1.1",
    "react-native-permissions": "1.1.1",
    "react-native-phone-input": "^0.2.4",
    "react-native-popup-menu": "^0.14.1",
    "react-native-progress": "4.0.2",
    "react-native-razorpay": "^2.2.1",
    "react-native-reanimated": "^1.13.1",
    "react-native-root-toast": "3.0.1",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.11.0",
    "react-native-segmented-control-tab": "^3.3.1",
    "react-native-simple-radio-button": "^2.7.3",
    "react-native-snap-carousel": "^3.8.0",
    "react-native-step-indicator": "0.0.8",
    "react-native-svg": "^9.6.2",
    "react-native-svg-charts": "^5.3.0",
    "react-native-swiper-flatlist": "1.0.3",
    "react-native-switch": "^1.5.0",
    "react-native-tab-navigator": "0.3.4",
    "react-native-tab-view": "^2.15.2",
    "react-native-vector-icons": "^7.0.0",
    "react-native-version-number": "^0.3.6",
    "react-native-webview": "^5.9.1",
    "react-native-youtube": "^2.0.0-beta.2",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "2.3.3",
    "react-navigation-stack": "2.0.8",
    "react-navigation-tabs": "^2.9.2",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "rn-fetch-blob": "^0.12.0",
    "rrule": "^2.6.0",
    "sprintf-js": "^1.1.2",
    "url-parse": "^1.4.4",
    "uuid": "3.2.1"
  },
  "devDependencies": {
    "babel-preset-es2015": "6.24.1",
    "react-native-clean-project": "^3.3.0",
    "@babel/core": "7.6.2",
    "@babel/runtime": "7.6.2",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.5.1",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.0",
    "react-test-renderer": "16.9.0",
    "babel-eslint": "8.2.5"
  },
  "jest": {
    "preset": "react-native"
  }
}

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:
NOT present
```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [X] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
        // maven {
        //     url 'https://maven.fabric.io/public'
        // }        
    }
    dependencies {
        classpath 'com.google.firebase:firebase-plugins:1.1.5'
        classpath("com.android.tools.build:gradle:3.6.4")
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
        // Android JSC is installed from npm
        url("$rootDir/../node_modules/jsc-android/dist")
        }

        maven { url 'https://maven.google.com' }
        maven { url "https://jitpack.io" }        
    }
}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion '28.0.3'
            }
        }
    }
}
```groovy
// N/A
```

#### `android/app/build.gradle`:

apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'
/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"

    defaultConfig {
        applicationId 
        minSdkVersion 23
        targetSdkVersion 29
        versionCode 109
        versionName "2.0.109"
        ndk {
            abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
        }
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled = true
    }
    compileOptions {
            sourceCompatibility 1.8
            targetCompatibility 1.8
        }

    signingConfigs {
        release {
           ......
        }
    }    
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a":3, "x86_64":4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    packagingOptions {
        pickFirst '**/armeabi-v7a/libc++_shared.so'
        pickFirst '**/x86/libc++_shared.so'
        pickFirst '**/arm64-v8a/libc++_shared.so'
        pickFirst '**/x86_64/libc++_shared.so'
        pickFirst '**/x86/libjsc.so'
        pickFirst '**/armeabi-v7a/libjsc.so'
    }
}

dependencies {
    implementation "com.google.android.gms:play-services-base:16.1.0" 
    implementation 'me.leolin:ShortcutBadger:1.1.21@aar' // badge on Android

    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "androidx.appcompat:appcompat:1.1.0"
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
    implementation "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.android.support:multidex:1.0.1'
    if (enableHermes) {
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
      implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
apply plugin: 'com.google.gms.google-services'
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply plugin: 'com.google.firebase.crashlytics'

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Memory: 20.02 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.3, 25.0.3, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.2
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] **Android** but have not tested behavior on iOS

- **`react-native-firebase` version you're using that has this issue:**
    "@react-native-firebase/app": "^8.4.5",
- **`Firebase` module(s) you're using that has the issue:**
    "@react-native-firebase/messaging": "^7.9.0",

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I think the information you get from plugging the device in while doing the actions, and via USB debugging running `adb logcat` so you can see what's happening. The module works in this case though it really has no responsibility, the Android system itself has an "Intent" tagged on to the notification, and when you tap it, it will open the 'LAUNCHER' activity (I think? Unless you customize it) from AndroidManifest.xml and send the Intent in. So my guess is the app is crashing on launch for some reason and you'll get a stack trace. It won't be react-native-firebase specific is my guess, it will be a project-specific problem in your project. Could be wrong, but that's my bet

**Comment by annucy** [comment]
> I think the information you get from plugging the device in while doing the actions, and via USB debugging running `adb logcat` so you can see what's happening. The module works in this case though it really has no responsibility, the Android system itself has an "Intent" tagged on to the notification, and when you tap it, it will open the 'LAUNCHER' activity (I think? Unless you customize it) from AndroidManifest.xml and send the Intent in. So my guess is the app is crashing on launch for some reason and you'll get a stack trace. It won't be react-native-firebase specific is my guess, it will be a project-specific problem in your project. Could be wrong, but that's my bet

Thanks for the reply. I just did all the set up again from start and commented some receivers in Manifest(which was part of version 5.x) and it works fine now.

As you said, since it is firing an intent with launcher activity, i will see the adb logs if it happens again.

You can close the issue.
