### ISSUE TITLE
[🐛] Bug Report Title - NativeFirebaseError: [messaging/unknown] FIS_AUTH_ERROR Android React-Native

### ISSUE THREAD

**Issue by Waleed-Nasir** [invertase/react-native-firebase#4466]
## Issue

Facing this issue only in Android ,while IOS working perfectly , 
 NativeFirebaseError: [messaging/unknown] FIS_AUTH_ERROR 

---

## Error Details

<details><summary> NativeFirebaseError: [messaging/unknown] FIS_AUTH_ERROR
    at FirebaseMessagingModule.getToken (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:173165:28)
    at HeaderHome.getToken$ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:174261:77)
    at tryCatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:1426:19)
    at Generator.invoke [as _invoke] (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:1602:24)
    at Generator.prototype.<computed> [as next] (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:1469:23)
    at tryCatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:1426:19)
    at invoke (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:1502:22)
    at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:1512:15
    at tryCallOne (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:28905:14)</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### Package JSOn

<details><summary>

</summary>
<p>

#### Have you converted to AndroidX?

- [*] my application is an AndroidX application?
- [*] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 {
  "name": "My_app_name",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
   "@invertase/react-native-apple-authentication": "^1.1.2",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/cameraroll": "^4.0.1",
    "@react-native-community/google-signin": "^4.0.3",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/toolbar-android": "0.1.0-rc.2",
    "@react-native-firebase/app": "8.4.2",
    "@react-native-firebase/database": "^7.5.12",
    "@react-native-firebase/dynamic-links": "^7.5.10",
    "@react-native-firebase/messaging": "^7.8.4",
    "axios": "^0.19.2",
    "i": "^0.3.6",
    "jetifier": "^1.6.6",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.31",
    "native-base": "^2.13.14",
    "npm": "^6.14.8",
    "react": "16.11.0",
    "react-native": "0.62.1",
    "react-native-admob": "^2.0.0-beta.6",
    "react-native-chart-kit": "^5.6.1",
    "react-native-country-picker-modal": "^1.11.0",
    "react-native-draggable": "^3.3.0",
    "react-native-dropdown-picker": "^3.7.0",
    "react-native-easy-content-loader": "^0.3.2",
    "react-native-elements": "^1.2.7",
    "react-native-fbsdk": "^2.0.0",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-iap": "^4.6.3",
    "react-native-image-picker": "^2.3.4",
    "react-native-image-resizer": "^1.3.0",
    "react-native-iphone-x-helper": "^1.3.0",
    "react-native-loader-overlay": "^1.0.0",
    "react-native-modal": "^11.5.6",
    "react-native-photo-upload": "^1.3.0",
    "react-native-popover-view": "^3.0.4",
    "react-native-push-notification": "^5.1.1",
    "react-native-push-notification-popup": "^1.6.0",
    "react-native-reanimated": "^1.10.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.11.0",
    "react-native-segmented-control-tab": "^3.4.1",
    "react-native-select-input-ios": "^2.0.5",
    "react-native-share": "^3.8.5",
    "react-native-simple-dialogs": "^1.4.0",
    "react-native-simple-toast": "^1.1.3",
    "react-native-svg": "^12.1.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-swiper": "^1.6.0",
    "react-native-switch-toggle": "^1.1.4",
    "react-native-vector-icons": "^6.7.0",
    "react-native-video": "^5.1.0-alpha8",
    "react-native-view-shot": "^3.1.2",
    "react-native-webp-format": "^1.1.2",
    "react-navigation": "^4.4.2",
    "react-navigation-drawer": "^2.5.2",
    "react-navigation-stack": "^2.8.4",
    "react-navigation-tabs": "^2.9.2",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/runtime": "^7.12.1",
    "@react-native-community/cli-debugger-ui": "4.7.0",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`@react-native-firebase/app` version you're using that has this issue:**
  - `8.4.6`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
```

    "@react-native-firebase/app": "^8.4.6",
    "@react-native-firebase/database": "^7.5.12",
    "@react-native-firebase/dynamic-links": "^7.0.1",
    "@react-native-firebase/messaging": "^7.0.1",
```

Please reproduce with current stable, and making sure you have firebase-android-sdk 25.13.0 as an override per https://rnfirebase.io/#android and let us know if this still happens

**Comment by arsalananwar** [comment]
Hi @mikehardy i did that but still facing same issue ,


<img width="1066" alt="Screenshot 2020-10-28 at 8 51 21 PM" src="https://user-images.githubusercontent.com/1077850/97461222-5c88f880-195f-11eb-86aa-f4fbef514856.png">

**Comment by Waleed-Nasir** [comment]
Hi @mikehardy i did that but still facing same issue ,

<img width="1066" alt="Screenshot 2020-10-28 at 8 51 21 PM" src="https://user-images.githubusercontent.com/33671736/97462519-a1f9f580-1960-11eb-9dc0-94edb70a39fd.png">

**Comment by mikehardy** [comment]
🤔 Those appear to be the same. And there's no verification of firebase-android-sdk version

**Comment by MoOx** [comment]
I recently faced this issue without any particular change in the dependencies I was using. I just upgraded all my packages (app, messaging & analytics) to latest version, made a clean build & facing the same problem.
I have no clue on what I should do to debug what appear to be [an incorrect firebase initialisation](https://stackoverflow.com/a/61041461). I will try to rollback as explained in this link because I really don't know what to do.
Any help appreciated...

**Comment by MoOx** [comment]
Ok, using `adb logcat` you can quickly find an more explicit error `API key expired. Please renew the API key.` from firebase.

```
2020-10-29 11:35:18.368 4585-4669/com.kisio.adm W/Firebase-Installations: Error when communicating with the Firebase Installations server API. HTTP response: [400 Bad Request: {
      "error": {
        "code": 400,
        "message": "API key expired. Please renew the API key.",
        "status": "INVALID_ARGUMENT",
        "details": [
          {
            "@type": "type.googleapis.com/google.rpc.Help",
            "links": [
              {
                "description": "Google developer console API key",
                "url": "https://console.developers.google.com/project/*redacted*/apiui/credential"
              }
            ]
          }
        ]
      }
    }
    ]
```

**Comment by mikehardy** [comment]
@MoOx you must have crossed the version barrier that included this change as they migrate internally from instance id to installations: https://firebase.google.com/support/release-notes/android#iid_v20-1-7

I'll add a note the firebase app release notes indicating you may need to re-download your project firebase config files (android json / ios plist) as I believe that is the resolution?

**Comment by mikehardy** [comment]
https://github.com/invertase/react-native-firebase/commit/ee9edffdd506608554db7233d565b71d4148cf97

**Comment by MoOx** [comment]
Interesting. In my precise case, my bundle id has been changed (from the one when the API Key has been generated) a few month ago but the error only popped since a few days.

**Comment by MoOx** [comment]
I guess that's enough indeed.

**Comment by mikehardy** [comment]
the last update to app ratcheted the underlying firebase-android-sdk version up, and that one I believe included more of the dependency switching internally upstream from instance id to messaging, which likely triggered it even though it's been in process a while. Thanks for checking the change to see if was good, hopefully this helps others help themselves so they don't get stuck. Subtle issue!

**Comment by mikehardy** [comment]
@Waleed-Nasir I'm going to mark this is closed but I recognize that is a bit of an assumption, we can reopen if grabbing fresh copies of your project configs from firebase console doesn't resolve it as that would mean we have mis-diagnosed your problem and there is something else going on. Cheers

**Comment by grkemtneri** [comment]
same issue. I am using adb logcat ı take this error 

```
Error when communicating with the Firebase Installations server API. HTTP response: [400 Bad Request: {
  "error": {
    "code": 400,
    "message": "API key not valid. Please pass a valid API key.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console",
            "url": "https://console.developers.google.com"
          }
        ]
      }
    ]
  }
}
]
```

**Comment by mikehardy** [comment]
@grkemtneri you probably just need to download new project config files (google config json and plist) from the firebase web console for your apps, into your apps and rebuild / retry

**Comment by jehee-choi** [comment]
did u solve the issue?

**Comment by MoOx** [comment]
did u read previous comments?

**Comment by elinahovakimyan** [comment]
Getting this error on Android after upgrading to v6 on `messaging().getToken()`, while ios works fine. Found this error after running `adb logcat`.

```
Error when communicating with the Firebase Installations server API. HTTP response: [403 Forbidden: {
  "error": {
    "code": 403,
    "message": "Requests from referer \u003cempty\u003e are blocked.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_HTTP_REFERRER_BLOCKED",
        "domain": "googleapis.com",
        "metadata": {
          "consumer": "projects/313605343145",
          "service": "firebaseinstallations.googleapis.com"
        }
      }
    ]
  }
}
]
```

**Comment by mikehardy** [comment]
@elinahovakimyan - if you download a new google-services.json this should resolve for you - we discovered post-release that this was a requirement as we moved across one of the underlying firebase-android-sdk versions - now I can't find a link to either changelog or PR (sorry) but I'm pretty sure that will do it

**Comment by elinahovakimyan** [comment]
> @elinahovakimyan - if you download a new google-services.json this should resolve for you - we discovered post-release that this was a requirement as we moved across one of the underlying firebase-android-sdk versions - now I can't find a link to either changelog or PR (sorry) but I'm pretty sure that will do it

@mikehardy I have tried that but it didn’t help.

**Comment by mikehardy** [comment]
Only other thought is that it's API key restrictions that are project-specific somehow, or missing SHA hashes in Android config. It is project-specific though, messaging definitely works, sorry

**Comment by jehee-choi** [comment]
I solved error by re-checking sha-1 key again in Android config. I don't know why it worked well before upgrading and not working after upgrading though.

**Comment by mohitsharma90** [comment]
> Getting this error on Android after upgrading to v6 on `messaging().getToken()`, while ios works fine. Found this error after running `adb logcat`.
> 
> ```
> Error when communicating with the Firebase Installations server API. HTTP response: [403 Forbidden: {
>   "error": {
>     "code": 403,
>     "message": "Requests from referer \u003cempty\u003e are blocked.",
>     "status": "PERMISSION_DENIED",
>     "details": [
>       {
>         "@type": "type.googleapis.com/google.rpc.ErrorInfo",
>         "reason": "API_KEY_HTTP_REFERRER_BLOCKED",
>         "domain": "googleapis.com",
>         "metadata": {
>           "consumer": "projects/{id}",
>           "service": "firebaseinstallations.googleapis.com"
>         }
>       }
>     ]
>   }
> }
> ]
> ```

Have you got the solution? Please let me know as I am facing the same Error i.e. 403.

**Comment by elinahovakimyan** [comment]
The solution for me was to enable Firebase Installations API in Google Cloud console API key settings.

**Comment by co2nut** [comment]
i'm getting error in adb logcat:

Firebase Installations Service is unavailable. Please try again later.

**Comment by co2nut** [comment]
for my case, 
i solved it by the this solution https://stackoverflow.com/a/64315489/1978998

**Comment by mohitkumar-sharma** [comment]
NativeFirebaseError: [messaging/unknown] FIS_AUTH_ERROR Android React-Native. i am facing this error from last 15 day when i tried to migrate to v6 from v5 to make my crashlytics again.  i am getting this error in getting token in android as ios is working fine. can anyone please help , i am really stuck in this @mikehardy @MoOx @co2nut @grkemtneri @elinahovakimyan

**Comment by mikehardy** [comment]
@mohitkumar-sharma my best advice is to pretend you are setting up your project again. What does that mean specifically? For the services you use, re-read the documentation on rnfirebase.io and the official google docs, per service. Make sure you have all the setup steps done (like the API toggle mentioned a couple comments above), re-download your plist/json project files etc.

**Comment by mohitkumar-sharma** [comment]
@mikehardy  thanks for your prompt response , issue is that my api key was restricted in the google developer console and after adding my sha1 ket their the error was gone. thanks @mikehardy

**Comment by co2nut** [comment]
> NativeFirebaseError: [messaging/unknown] FIS_AUTH_ERROR Android React-Native. i am facing this error from last 15 day when i tried to migrate to v6 from v5 to make my crashlytics again. i am getting this error in getting token in android as ios is working fine. can anyone please help , i am really stuck in this @mikehardy @MoOx @co2nut @grkemtneri @elinahovakimyan

did you follow the solution? u might had the SHA1 restricted in your google cloud console

**Comment by compojoom** [comment]
I think I have the same issue or a similar one. It took me quite some time to figure out what's going on, but I hope that my finding will help others who don't know what is going on. (also @co2nut shared this above, but I overflew it: https://stackoverflow.com/a/64315489/1978998) 

In my case I was getting the same error for the debug version of our app. Our app bundle Id has the suffix `.debug` and we had registered the app in firebase. 
It used to work for me in the past just fine, but today I was getting this error. I asked a colleague to check on his machine and he was telling me that all is good. What I found out however was that my SHA-1 was not the same as the one added to firebase. Apparently my android.debug keystore has changed at one point and I was signing the app with the wrong keys. 
I added the sha-1 that was  output from 
```
$ keytool -list -v -keystore ~/.android/debug.keystore
```

(the pass for the debug.keystore is `android`) to the firebase project settings, but still nothing. 
Then I found out that if I go to the google developer console - there is an android api key. When I opened it I noticed that the key is restricted to android apps and there was the old sha-1 key, but not the one I just added to the firebase console. Once I added the SHA-1 key there the error was gone.

**Comment by HadiKhalifeh** [comment]
hi @mikehardy  i was getToken before,but now no ,i get this error NativeFirebaseError: [messaging/unknown] FIS_AUTH_ERROR

**Comment by mikehardy** [comment]
@HadiKhalifeh I look forward to seeing what the pertinent log entries from either Xcode console or adb logcat are when included with your new issue that includes all the troubleshooting information we need to do triage, vs the otherwise insufficient information you have posted on this closed issue.

**Comment by stackcru-tech** [comment]
I am facing the same issue in android with version
   "@react-native-firebase/app": "^11.4.1",
    "@react-native-firebase/auth": "^11.4.1",
    "@react-native-firebase/messaging": "^11.4.1",

**Comment by sherif95** [comment]
I was facing the same issue and after a couple of hours i fixed it by the following steps:

1. Go to google cloud console and select your project.
2. Select the **API&Services** from the left side menu then select **Credentials**.
3. Press on Edit API Key that related to Android from API Keys section.
4. Check on None in **Key restrictions** and Don't restrict Key in **API restrictions** then press save.
5. Wait for 5 minutes to take this effect and run the code again.

**Comment by mikehardy** [comment]
Not restricting the key has security implications. This advice should not be followed unless the tradeoffs are understood.
https://cloud.google.com/docs/authentication/api-keys#api_key_restrictions
@sherif95 be very, very careful handing out advice with security implications - it's never possible to know everyone's situation, and in particular offering advice where security is compromised, without any note about what it implies, is dangerous. You could responsible for someone's API key being misused at great cost

**Comment by sherif95** [comment]
> Not restricting the key has security implications. This advice should not be followed unless the tradeoffs are understood.
> https://cloud.google.com/docs/authentication/api-keys#api_key_restrictions
> @sherif95 be very, very careful handing out advice with security implications - it's never possible to know everyone's situation, and in particular offering advice where security is compromised, without any note about what it implies, is dangerous. You could responsible for someone's API key being misused at great cost

@mikehardy I do understand your words and many thanks for your advice.

**Comment by mikehardy** [comment]
> Had this same issue and all I needed to do was add Token Service API to my android and ios API keys. Would be great if these things were documented somewhere

maybe propose an edit here with a good searchable string of the exact error you saw? https://github.com/invertase/react-native-firebase/blob/main/docs/faqs-and-tips.md :pray:
