### ISSUE TITLE
[Q] Schedule notification interval doesn't work over the twice?

### ISSUE THREAD

**Issue by Bang9** [invertase/react-native-firebase#447]
### Issue

Hi, I want make function that alarm notification for every day
So, I used the **_fcm.scheduleLocalNotification()_**
It works very well, but just twice(only works on two days)
after the get two notifications, It doesn't work anything
scheduleLocalNotification doesn't support notification for every day?

It's my source code, thank you

```
fcm.scheduleLocalNotification({
    fire_date: this.getAlarmTime(hour, minute), 
    id: "alarm_notification",
    body: "How are you today?",
    push_type:'alarm',
    large_icon:'ic_launcher',
    icon:'ic_stat_ic_notification',
    repeat_interval: "day" // minute,hour,day,week
})
```

```
 getAlarmTime(hour,min){ //reserve time
    let now = new Date();
    let alarmStamp;

    if(now.getHours()<hour) { //set today
        let alarmHour = hour - now.getHours();
        let alarmMin = min - now.getMinutes();
        alarmStamp = now.getTime() + (alarmHour + alarmMin/60)*60*60*1000 - (now.getSeconds()*1000+now.getMilliseconds())
}
    else if(now.getHours()>hour) { //set tomorrow
        let nextDayStamp = now.getTime() + (24-now.getHours())*60*60*1000 - now.getMinutes()*60*1000 - (now.getSeconds()*1000+now.getMilliseconds())//tomorrow 00:00
        alarmStamp = nextDayStamp + (hour + min/60)*60*60*1000
}
    else{
        if(now.getMinutes()<min){ //set today
            let alarmHour = hour - now.getHours();
            let alarmMin = min - now.getMinutes();
            alarmStamp = now.getTime() + (alarmHour + alarmMin/60)*60*60*1000 - (now.getSeconds()*1000+now.getMilliseconds())
        }
    else if(now.getMinutes()>=min){ //set tomorrow
        let nextDayStamp = now.getTime() + (24-now.getHours())*60*60*1000 - now.getMinutes()*60*1000 - (now.getSeconds()*1000+now.getMilliseconds())//tomorrow 00:00
        alarmStamp = nextDayStamp + (hour + min/60)*60*60*1000
    }
}
    return alarmStamp
}
```

### Environment

1. Application Target Platform:
Android

2. Development Operating System:
Windows 10

3. Build Tools:
Android Studio 2.3.3
compileSdkVersion 25

4. React Native version: 
0.45.1

5. RNFirebase Version: 
2.0.5

6. Firebase Module: 
messaging

**Comment by chrisbianca** [comment]
Thanks for reporting.  We're aware of lots of issues with notifications and will be addressing them all as part of the v3.2.0 release stream.  Please see https://github.com/invertase/react-native-firebase/issues/595 for updates.

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)
