### ISSUE TITLE
[🐛] Can't add both email sign in methods (emailLink, password) for a user account

### ISSUE THREAD

**Issue by Agusfn** [invertase/react-native-firebase#4483]
## Issue

On the auth module, I cannot appear to add the 'emailLink' sign in method to an account that already has the 'password' sign in method (both belong to Email/Password sign in provider). I can do the opposite though.

Steps to reproduce:

1) Create user account with email and password. 
`auth().createUserWithEmailAndPassword(email, password)`

This creates a new auth user in firebase, with "password" sign in method. We can check this with. `auth().fetchSignInMethodsForEmail(email)`
Returns` ["password"]`

2) Sign into this account with mail and password
`auth().signInWithEmailAndPassword(email, password)`

3) Now we want to associate the "emailLink" sign in method as well. We send the normal sign in mail to this account's address.
`auth().sendSignInLinkToEmail(email, actionCodeSettings)`

4) Click the link sent to the e-mail, handle the event, and verify it:
`auth().isSignInWithEmailLink(emailLink)`

5) Sign in with email link (this account is already signed in in the app though)
`auth().signInWithEmailLink(email, link)`
This returns the account credentials.

6) Obtain the new account sign in methods for e-mail:
`auth().fetchSignInMethodsForEmail(email)`

Returns` ["emailLink"]`, which doesn't include password, it has been discarded instead of added as a new method. **Maybe I am using the wrong method, or maybe it's not possible, i couldn't find any info on the internet.**

If i do the opposite (login without password on a new account, which creates a new auth user with "emailLink" method, and then call `auth().currentUser.updatePassword(password)`) firebase does add "password" to the sign in methods, which end up being `["emailLink", "password"]`.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "Hybeans",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "androidar": "react-native run-android --variant=arDebug",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "npx jetify"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.12.0",
    "@react-native-community/masked-view": "0.1.5",
    "@react-native-community/netinfo": "^4.7.0",
    "@react-native-firebase/app": "^8.4.1",
    "@react-native-firebase/auth": "^8.3.3",
    "@react-native-firebase/database": "^7.5.5",
    "@react-native-firebase/firestore": "^7.8.0",
    "@react-native-firebase/functions": "^7.4.2",
    "@react-native-firebase/messaging": "^7.8.4",
    "@react-native-firebase/storage": "^7.4.2",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/native-stack": "^5.0.5",
    "@react-navigation/stack": "^5.9.0",
    "@types/ramda": "0.26.44",
    "geofirestore": "^3.4.1",
    "loadash": "^1.0.0",
    "mobx": "^4.15.6",
    "mobx-react-lite": "^1.4.1",
    "mobx-state-tree": "^3.14.1",
    "moment": "^2.24.0",
    "prop-types": "^15.7.2",
    "ramda": "^0.27.1",
    "react": "16.11.0",
    "react-emotion": "^10.0.0",
    "react-native": "^0.61.5",
    "react-native-autocomplete-input": "^4.1.0",
    "react-native-beacons-manager": "^1.0.7",
    "react-native-bluetooth-state": "^2.0.0",
    "react-native-camera": "^3.38.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-device-info": "^5.6.5",
    "react-native-easy-toast": "^1.2.0",
    "react-native-elements": "^1.2.7",
    "react-native-email-link": "^1.9.1",
    "react-native-encrypted-storage": "^3.0.0",
    "react-native-exif": "^0.4.0",
    "react-native-fast-image": "^7.0.2",
    "react-native-fbsdk": "^1.1.2",
    "react-native-fs": "^2.16.4",
    "react-native-geolocation-service": "^3.1.0",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-image-picker": "^1.1.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-localize": "^1.4.1",
    "react-native-map-clustering": "^3.3.9",
    "react-native-maps": "0.27.1",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-navigation": "^3.7.0",
    "react-native-permissions": "^2.2.0",
    "react-native-qrcode-svg": "^5.3.2",
    "react-native-reanimated": "~1.4.0",
    "react-native-responsive-screen": "^1.4.1",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-shadow": "^1.2.2",
    "react-native-share": "^2.0.0",
    "react-native-size-matters": "^0.2.1",
    "react-native-svg": "^9.13.6",
    "react-native-swipe-gestures": "^1.0.4",
    "react-native-swiper": "^1.5.14",
    "react-native-vector-icons": "^7.0.0",
    "react-navigation": "^4.1.1",
    "react-powerplug": "^1.0.0",
    "react-viro": "2.17.0",
    "reactotron-mst": "^3.1.1",
    "reactotron-react-native": "^4.0.3",
    "shortid": "^2.2.15",
    "uuid-random": "^1.3.0",
    "yup": "^0.28.3"
  },
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/runtime": "^7.11.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "@types/jest": "^25.1.5",
    "@types/react": "^16.9.49",
    "@types/react-native": "^0.62.1",
    "@types/react-test-renderer": "^16.9.3",
    "@types/yup": "^0.26.34",
    "@typescript-eslint/eslint-plugin": "^2.24.0",
    "babel-jest": "^24.9.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "babel-preset-mobx": "^2.0.0",
    "eslint": "^6.8.0",
    "i18n-js": "^3.0.11",
    "jest": "^24.9.0",
    "jetifier": "^1.6.5",
    "metro-react-native-babel-preset": "^0.56.4",
    "react-test-renderer": "16.8.6",
    "typescript": "^3.8.3"
  },
  "jest": {
    "preset": "react-native"
  },
  "parserOptions": {
    "project": "./tsconfig.json"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "emulators": {
    "functions": {
      "port": 5001,
      "host": "0.0.0.0"
    },
    "firestore": {
      "port": 8080,
      "host": "0.0.0.0"
    },
    "database": {
      "192.168.0.3": 8080,
      "port": 9000,
      "host": "0.0.0.0"
    },
    "ui": {
      "enabled": true
    }
  }
}

```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

**Comment by RandomToni** [comment]
Hello, we're having the same issue, when adding "emailLink" it looks like it overwrites the whole array and if the user had "password" previously it gets erased.

**Comment by mikehardy** [comment]
Very strange - sorry I haven't looked at this at all and I don't use emailLink in my project so I don't have experience personally.

My best advice (for much more speed in resolving this) is to do the initial triage here personally

Specifically - dive right into node_modules and add console.log's before all related native SDK calls in the auth module with arguments and returns printed out (I always just `JSON.stringify(thing, null, 2)` all the things, and it's nicely formatted

Once you figure out which native call is suspect, dive further into them (either Java or Objective-C) and do the same thing (but with native logging calls) around any of the suspect upstream (firebase-android-sdk / firebase-ios-sdk) google SDK calls.

This is how I triage basically every problem here, unfortunately it does take some time which I don't have right now but it should lead to the error pretty predictably and also usually makes it pretty easy to fix / post a pull request for

**Comment by lni600** [comment]
I met a similar problem so I found this issue, but I use Angular.

Then I contacted Google Firebase Support, and here's their reply:

> This sound related to the trusted providers behavior. There are trusted and not trusted providers, what happens is that when you sign in with a not trusted provider (Facebook, email/password without email verification) and then you sign in with a trusted one (Google, email link) we ‘elevate’ the verified provider and unlink the previously unverified or not trusted login.
> 
> You may check this links from members of our team ( [https://github.com/firebase/firebase-ios-sdk/issues/5344#issuecomment-618518918](GitHub) and [https://stackoverflow.com/questions/60258708/trying-to-understand-firebase-authentication-one-account-per-email-address-and-t/60276351#60276351](StackOverflow)), there's a list of the trusted providers and they also explain other behaviors like what happens when you use two trusted providers.

**Comment by mikehardy** [comment]
Oh that is subtle! This sounds like underlying SDK behavior then, and perhaps something that could be a docs PR if someone wanted to try hitting the edit button on the related page on rnfirebase.io :pray:

**Comment by lni600** [comment]
Now I'm using the trick with AdminSDK to set emailVerified to "true" when creating a firebase user (even it's still not verified). It works for me.
