### ISSUE TITLE
Firebase Auth doesn't work with Phone Verification reCAPTCHA workflow in IOS simulator

### ISSUE THREAD

**Issue by codifius** [invertase/react-native-firebase#4484]
## Issue

I installed a fresh react-native projet wiht only  "@react-native-firebase/app" and "@react-native-firebase/auth" modules and I flow the doc in this [Link](https://firebase.google.com/docs/auth/ios/phone-auth) to enable app verification during the phone verification but it failed in IOS simulator during the reCAPTCHA workflow and I have the error message below:

```javascript
Possible Unhandled Promise Rejection (id: 1):
Error: [auth/internal-error] {"error":{"code":403,"message":"Requests from this ios client application <empty> are blocked.","errors":[{"message":"Requests from this ios client application <empty> are blocked.","domain":"global","reason":"forbidden"}],"status":"PERMISSION_DENIED"}}
NativeFirebaseError: [auth/internal-error] {"error":{"code":403,"message":"Requests from this ios client application <empty> are blocked.","errors":[{"message":"Requests from this ios client application <empty> are blocked.","domain":"global","reason":"forbidden"}],"status":"PERMISSION_DENIED"}}
signInWithPhoneNumber$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:98984:91
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:28643:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:28816:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:28643:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:28716:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:28746:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3484:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3648:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3507:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:28745:33
enqueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:28750:157
```

But it works perfectly in IOS Device with Silent APNs notifications workflow.

## ENV
  - "@react-native-firebase/app": "^8.4.7"
  - "@react-native-firebase/auth": "^9.3.2"
  -  "react": "16.13.1"

## Platfrom
 - IOS 14 simulator
 - xCode Version 12.1
 - macOS Catalina 10.15.6

**Comment by mikehardy** [comment]
How did it work when you researched and fixed the underlying problem causing your project to be '<empty>'  and blocked ?

**Comment by codifius** [comment]
@mikehardy  I didn't understand your answer. But I think I found the issue why it is not working.

When I limit my IOS Firebase API key in the Google console to my bundle id it causes the issue and when I remove the restriction it works fine. it appears that the reCAPTCHA workflow is not sending the bundle id.

On Android it works fine with the restriction of the Android Firebase API key.

The issue persists even when I created new fresh project with :
    - "@ react-native-firebase / app": "^ 10.0.0",
    - "@ react-native-firebase / auth": "^ 10.0.0",

Is there something that I missed?

**Comment by mikehardy** [comment]
Hmm that would be new and would perhaps explain the app being blocked and the empty app identity. Is there any mention of this in the upstream docs? Perhaps there is a a divergence in documentation, perhaps there really is an error either upstream or in RNFB 🤔

**Comment by codifius** [comment]
@mikehardy the only documentation I founded about the restriction api key is https://firebase.google.com/docs/projects/api-keys#general-info, but i didn't found any documentation about phone auth configuration in react-native-firebase official documentation

**Comment by mikehardy** [comment]
Hey @codifius I just read through the related documentation and it doesn't seem like it should have an effect but I am not well-versed enough at the interaction between the services and the API keys to know. 

There was this note which might bear testing:

> Note: If you apply restrictions to an API key that's used for accessing Firebase services, and you're getting errors, you may need to include the Firebase Management API in the list of allowed APIs. This is especially true if you use Google Analytics with a web app.

Otherwise, I'd say you'll have a better chance at resolution pursuing it as an upstream issue in firebase-ios-sdk with a test app based on their auth quickstart: https://github.com/firebase/quickstart-ios/tree/master/authentication
