### ISSUE TITLE
Grouping notifications

### ISSUE THREAD

**Issue by bm-software** [invertase/react-native-firebase#449]
How can we group notifications?
I've seen the code of your library and the `setGroup` method is called on `NotificationBuilder` but my notifications are not grouped.

I'm using the following code to create a local notification:

    messaging.createLocalNotification({
        title: message.title,
        body: message.body,
        sound: message.sound,
        priority: 'high',
        click_action: message.action || 'android.intent.action.MAIN',
        ticker: 'Nuovo avviso',
        auto_cancel: true,
        icon: message.icon,
        large_icon: 'ic_launcher',
        big_text: message.body,
        sub_text: 'Avvisi',
        color: message.color,
        vibrate: 300,
        tag: message.tag,
        group: 'caliup',
        lights: true,
        show_in_foreground: true
    })

How can I handle grouping?

NOTE: I'm using android 8.0

**Comment by kevando** [comment]
where do you see documentation for functions like createLocalNotification?

All I could find is this and it doesnt seem comprehensive.
https://rnfirebase.io/docs/v3.0.*/messaging/reference/messaging#onTokenRefresh

**Comment by Ehesp** [comment]
The messaging docs are incomplete which we realise. There's some discussion about how we progress with it as it really needs an overhaul.

**Comment by kevando** [comment]
thanks @Ehesp the layout of that page and the ios installation instructions are quite good, so i thought i might be crazy.

have you thought about adding a "underconstruction" message with a link to contribute. I get a ton of value from rn+firebase and would be happy to help.

**Comment by Ehesp** [comment]
@kevando Yeah I guess we should - there is an edit button at the bottom of each page :)

**Comment by chrisbianca** [comment]
Thanks for reporting.  We're aware of lots of issues with notifications and will be addressing them all as part of the v3.2.0 release stream.  Please see https://github.com/invertase/react-native-firebase/issues/595 for updates.

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)

**Comment by bm-software** [comment]
I've tried to grouping notifications and still does not work. I'm using `v.4.2.0` of your library with `react-native v.0.55.1`. I've set the group with `setGroup` method and according to [this](https://developer.android.com/training/notify-user/group) on Android 7.0 and higher (I'm testing on android 8) the system automatically builds a summary for your group using snippets of text from each notification so setting the groud should be enough.

Can you help me please?

**Comment by tuomohopia** [comment]
I also can't get grouping to work, using _4.2.0_ too with _Android SDK 26_.
I wonder if `createChannelGroup` is the same as `createChannel` in the sense that it's safe to call again, so it could be called even everytime a message is received that should be displayed as a heads-up notif?

setVisibility also does not seem to be working but I think that's already a known issue, possibly fixed already.

**Comment by Salakar** [comment]
Re-opening to re-visit grouping issue, has been mentions on discord as well of it not working. Unless anyone can say otherwise or has it working for them?

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by aMarCruz** [comment]
@Salakar , grouping is working to me. This is a feature of Android 7.0 and above, as [documented here](https://developer.android.com/training/notify-user/group).

In my case, I'm creating local notifications from remote messages. The trick is to create an additional notification that contains the notifications for that group.

This is the relevant code:

```typescript
// ID for grouping notifications, always the same
const SUMMARY_ID = `${ALERTS_GROUP}.summary`

const sendIt = (notification: Firebase.notifications.Notification) => {
  return firebase.messaging().hasPermission().then((yes) => {
    if (yes) {
      try {
        return firebase.notifications().displayNotification(notification)
          .catch((err) => {
            Log.e(`[sendNotification] ERROR: ${err}`)
            return Promise.resolve()
          })
      } catch (err) {
        Log.e('[sendNotification] Error displaying notification: ' + err)
      }
    }
    return Promise.resolve()
  })
}

const sendSummary = (data: MessageData) => {
  const summary = new firebase.notifications.Notification()
    .setNotificationId(SUMMARY_ID)
    .setTitle(_T('notification.channels.alert.description'))
    .setData(data)
    .android.setAutoCancel(true)
    .android.setCategory(firebase.notifications.Android.Category.Message)
    .android.setChannelId(getChannelId(MsgType.Alert))
    .android.setColor(variables.scheme.primaryColor)
    .android.setSmallIcon(STATUS_ICON)
    .android.setGroup(ALERTS_GROUP)
    .android.setGroupSummary(true)
    .android.setGroupAlertBehaviour(firebase.notifications.Android.GroupAlert.Children)
  sendIt(summary)
}

/**
 * Called by `bgMessaging` or the `onMessage`  handler.
 */
export function sendNotification (message: Firebase.messaging.RemoteMessage) {
  const payload: MessagePayload = message.data as any || {}
  const notification = new firebase.notifications.Notification()
  // ... more code

  if (Platform.OS === 'android' && Platform.Version >= 24) {
    notification.android.setGroup(ALERTS_GROUP)
    sendSummary(notification.data)
  }
  Log.v('[sendSummary] sending notification.')
  return sendIt(notification)
}
```

There's an [inbox-style](https://developer.android.com/training/notify-user/expanded#inbox-style) which also allows grouping and works in SDK 23 and bellow, but is not implemented in RNF react-native-firebase.

**Comment by Salakar** [comment]
@aMarCruz thanks for confirming and the detailed example. Will close this again.

**Comment by rendomnet** [comment]
Not working for me.

**Comment by lutchobandeira** [comment]
@aMarCruz @Salakar Do you know if there is a way to group notifications for versions prior to Android 7.0?

**Comment by chinalwb** [comment]
I found it is pretty tricky to show the notification group. Thanks @aMarCruz 's comment, but it still costs me several hours to make it work so I'd like to share my code:

This is mine:

```
  const groupNotificationId = 'test'
  const body = 'Chats list'
  const smallIcon = 'ic_launcher'
  const color = '#FF00FF'

  const groupNotification = new firebase.notifications.Notification()
    .setNotificationId(groupNotificationId)
    .setSubtitle(body)
  groupNotification
    .android.setGroup(groupNotificationId)
    .android.setGroupSummary(true)
    .android.setChannelId('chat')
    .android.setSmallIcon(smallIcon)
    .android.setAutoCancel(true)
    .android.setColor(color)

  const title = 'Test Chat'
  const desc = 'User A added comment: Hello'
  const nid = '1001' // nid + tag is a composite key to identify the notification
  const tag = 'Test tag'

  const notification = new firebase.notifications.Notification()
    .setNotificationId(nid)
    .setTitle(title)
    .setBody(desc)
  notification
    .android.setBigText(desc)
    .android.setAutoCancel(true)
    .android.setChannelId('chat')
    .android.setTag(tag)
    .android.setGroup(groupNotificationId)

  firebase.notifications().displayNotification(groupNotification)
  firebase.notifications().displayNotification(notification)
```

Be careful, tag / notificationId, group, groupSummary and channel id, these are very important fields and you need to set.

Hope this will help someone.

**Comment by aMarCruz** [comment]
@chinalwb try using `.android.setGroupAlertBehaviour(firebase.notifications.Android.GroupAlert.Children)`

...and sorry, my example was incomplete and it missed relevant lines under "// ... more code"

**Comment by chinalwb** [comment]
@aMarCruz Thank you, I added the group alert behaviour to both group and child notification, it works now.

**Comment by chinalwb** [comment]
So this is the latest code.

```
  const groupNotificationId = 'test'
  const body = 'Chats list'
  const smallIcon = 'ic_launcher'
  const color = '#FF00FF'

  const groupNotification = new firebase.notifications.Notification()
    .setNotificationId(groupNotificationId)
    .setSubtitle(body) // This is setSubText(..) in Android
  groupNotification
    .android.setGroup(groupNotificationId)
    .android.setGroupSummary(true)
    .android.setGroupAlertBehaviour(firebase.notifications.Android.GroupAlert.Children)
    .android.setChannelId('chat')
    .android.setSmallIcon(smallIcon)
    .android.setAutoCancel(true)
    .android.setColor(color)

  const title = 'Test Chat'
  const desc = 'User A added comment: Hello'
  const nid = '1001' // nid + tag is a composite key to identify the notification
  const tag = 'Test tag'

  const notification = new firebase.notifications.Notification()
    .setNotificationId(nid)
    .setTitle(title)
    .setBody(desc)
  notification
    .android.setBigText(desc)
    .android.setAutoCancel(true)
    .android.setChannelId('chat')
    .android.setTag(tag)
    .android.setGroup(groupNotificationId)
    .android.setGroupAlertBehaviour(firebase.notifications.Android.GroupAlert.Children)


  firebase.notifications().displayNotification(groupNotification)
  firebase.notifications().displayNotification(notification)
```

**Comment by chinalwb** [comment]
@aMarCruz Sorry to bother you, I have one more issue about the group notification, that is you can see my code in above comment, I didn't set smallIcon to the (child) notification -- only setSmallIcon onto groupNotification, but in fact every child notification are being shown with a small icon.


<img width="320" alt="smallicon" src="https://user-images.githubusercontent.com/1758864/45466407-35094e80-b74c-11e8-9201-4ec1272bc3c5.png">

Notice the gray square to the left side of each notification. (The green one at the group notification is being shown as expected.)

Can you help to give me some advice?

Thanks.

**Comment by aMarCruz** [comment]
@chinalwb of course, you need set the desired icon and color for individual notifications as well, otherwise, rn-firebase will put this (contrary to what is said in the docs) to the default icon of your App (mipmap/ic_launcher).

**Comment by chinalwb** [comment]
@aMarCruz Thanks, I set a different small icon string and it shows, but in fact I want to remove the icon from the child notification. Just like this:
![notification-group_2x](https://user-images.githubusercontent.com/1758864/45468682-7bfd4100-b758-11e8-9f1a-d88e627a1030.png)

Also I want to remove the \/ icon from the child notification, it makes the child notification looks like a group.

Many Thanks.

**Comment by aMarCruz** [comment]
@chinalwb I really don't know how to hide the icon in group elements.
But try using `.android.setSmallIcon()` with `null`, an empty string, or an fake name (ex. "noname")... I think one of those parameters will work without generating error.

Also, check in your AndroidManifest.xml and **delete** the meta with the name "com.google.firebase.messaging.default_notification_icon" if any, ...it is something like this:

```xml
<meta-data
    android:name="com.google.firebase.messaging.default_notification_icon"
    android:resource="@drawable/ic_notification" />
```

Please tell me if some works.

**Comment by chinalwb** [comment]
@aMarCruz Thank you very much for your help!

I found the tricky.

To hide the smallIcon in the child notification, I need to keep the `setSmallIcon(smallIcon)` and `setColor(color)` of the child notification to be exactly same with the group notifications.

I.e.: with the code in my above comment, it was:

>   const groupNotificationId = 'test'
>   const body = 'Chats list'
>   const smallIcon = 'ic_launcher'
>   const color = '#FF00FF'
> 
>   const groupNotification = new firebase.notifications.Notification()
>     .setNotificationId(groupNotificationId)
>     .setSubtitle(body) // This is setSubText(..) in Android
>   groupNotification
>     .android.setGroup(groupNotificationId)
>     .android.setGroupSummary(true)
>     .android.setGroupAlertBehaviour(firebase.notifications.Android.GroupAlert.Children)
>     .android.setChannelId('chat')
>     .android.setSmallIcon(smallIcon)  // Sets small icon to group notification
>     .android.setColor(color)  // Sets color to group notification
>     .android.setAutoCancel(true)
> 
>   const title = 'Test Chat'
>   const desc = 'User A added comment: Hello'
>   const nid = '1001' // nid + tag is a composite key to identify the notification
>   const tag = 'Test tag'
> 
>   const notification = new firebase.notifications.Notification()
>     .setNotificationId(nid)
>     .setTitle(title)
>     .setBody(desc)
>   notification  // I didn't set smallIcon or color for child notification
>     **.android.setBigText(desc)**
>     .android.setAutoCancel(true)
>     .android.setChannelId('chat')
>     .android.setTag(tag)
>     .android.setGroup(groupNotificationId)
>     .android.setGroupAlertBehaviour(firebase.notifications.Android.GroupAlert.Children)
> 
> 
>   firebase.notifications().displayNotification(groupNotification)
>   firebase.notifications().displayNotification(notification)

See the embeded comment inside the code, I set smallIcon and color to group notification but didn't set either of them to child notification, this is one of the case that the child notification isn't the same to the group notification, so each child notification shows a small icon of itself -- in fact here, if there is no smallIcon set for child notification, it uses the default one, i.e.: 'ic_launcher', but because I set the color to group notification, so this action makes them different.

So to resolve (hide the smallIcon of the child notification) the issue, I did like this:
1. added `setSmallIcon(smallIcon)` to child notification
2. added `setColor(color)` to child notification

And BTW, to remove the \\/ icon at the RHS of the child notification, just need to  remove the call to `setBigText(..)`.

And what's more, remove or keep the `meta-info` from manifest doesn't affect the result.

Thank you @aMarCruz !

**Comment by marvinkome** [comment]
How's the PR coming up? Is there any way to show the messages in the group since the inbox style isn't available.

**Comment by iamsoorena** [comment]
Why is this thing closed? It's a must-have.

**Comment by tusharmutreja** [comment]
Hey guys,

Did anyone find the solution? I am still stuck in the grouping of notification

**Comment by firofame** [comment]
@chinalwb Thank you so much for your solution. it works perfectly when the app is in the foreground. unfortunately, the onNotification listener doesn't get triggered when the app is in the background or killed hence the notification doesn't group. do you have any workaround?
