### ISSUE TITLE
Phone Authentication only works with test numbers and not with my real number

### ISSUE THREAD

**Issue by Osamasomy** [invertase/react-native-firebase#4492]
Its working fine with the test numbers but when I added my real number its show me error

```
Possible Unhandled Promise Rejection (id: 0):
Error: [auth/app-not-authorized] This app is not authorized to use Firebase Authentication. Please verify that the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed ]
```
I already check these things are already there.
## Issue
import React, { useState } from 'react';
import { Button, TextInput } from 'react-native';
import auth from '@react-native-firebase/auth';

function PhoneSignIn() {
  // If null, no SMS has been sent
  const [confirm, setConfirm] = useState(null);

  const [code, setCode] = useState('');

  // Handle the button press
  async function signInWithPhoneNumber(phoneNumber) {
    const confirmation = await auth().signInWithPhoneNumber(phoneNumber);
    setConfirm(confirmation);
  }

  async function confirmCode() {
    try {
      await confirm.confirm(code);
    } catch (error) {
      console.log('Invalid code.');
    }
  }

  if (!confirm) {
    return (
      <Button
        title="Phone Number Sign In"
        onPress={() => signInWithPhoneNumber('+1 650-555-3434')}
      />
    );
  }

  return (
    <>
      <TextInput value={code} onChangeText={text => setCode(text)} />
      <Button title="Confirm Code" onPress={() => confirmCode()} />
    </>
  );
}

---

## Package.json
"react-native": "^0.63.2",
"@react-native-firebase/app": "^8.4.7",
"@react-native-firebase/auth": "^9.3.2",

**Comment by andersonaddo** [comment]
Have you checked online answers already?
This is a known error; you'll probably find an answer if you do a bit of digging

**Comment by Osamasomy** [comment]
hy @andersonaddo  thanks for your reply after some digging i change some lines of code but now i face 
**auth/missing-client-identifier** this error.

i try alot and digging alot but nothing to find. **Need Your Help**
Thanks.

**Comment by andersonaddo** [comment]
It's a new error now. 
Give us a new problem description, including sample code  (formatted properly this time, please 🙃).

**Comment by Osamasomy** [comment]
i just follow the docs and try to use its sample code and face this. my project is ejected from the expo.

**Comment by Abhaygadhavi** [comment]
hey, @Osamasomy  i am getting the exact same error i googled it but i got no solution can you please tell me what did you do?

**Comment by Enriquemnd** [comment]
> Osamasomy

Same problem here, do you remember what you did?

**Comment by abdu-zeyad** [comment]
same here

**Comment by Anushka3001** [comment]
Even i am getting the same error. After adding the sha1 and sha256 keys, I'm getting the same error: Error: [auth/app-not-authorized] This app is not authorized to use Firebase Authentication. Please verify that the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed ]
I checked the package name in firebase and my project, it is same.
checked the keys.
This error is showing only to real numbers. If any number is added in testing part, that will work, but if tried with any real number, it will give that error.
if anyone has found any solution for this, please do not forget to comment.
