### ISSUE TITLE
[🐛🍎🔥] Kids category app rejection.

### ISSUE THREAD

**Issue by curiousdustin** [invertase/react-native-firebase#4494]
## Issue

An iOS app I am working on is being rejected by Apple. As far as we can tell, the rejection is related to Firebase Analytics.

The message we get from Apple is this:

> Guideline 1.3 - Safety - Kids Category
> 
> We noticed that your Kids Category app includes analytics, advertising and collects, transmits, or has the ability to share personal information or device information with third parties.
> 
> Your app includes the following feature(s), contrary to guideline 1.3 of the App Store Review Guidelines:
> 
> Third-party analytics or third-party advertising with the ability to collect, transmit or share identifiable information, including, for example, IDFA.
>  
> Next Steps
>  
> To resolve this issue, please remove this functionality or revise your app so that no personally identifiable information or device information is sent to third parties.

Apple has also spoken to one of our team members briefly on the phone. They would not give much detail, other than to confirm that IDFA collection is the issue. They stated that simply disabling the collection is not enough. They instructed that we should remove any code that accesses IDFA even if it is never executed.

We have followed the [instructions to disabled IDFA collection](https://firebase.google.com/docs/analytics/configure-data-collection#disable_idfa_collection), but this does not satisfy Apple. As mentioned, they want the code removed, not disabled.

From what I can tell, this boils down to the dependency on `GoogleAppMeasurement`, and it contains code that can optionally access the IDFA.

We would like to use multiple Firebase services, however the version of the app that was rejected contained only the following:

``` json
"@react-native-firebase/analytics": "^7.6.9",
"@react-native-firebase/app": "^8.4.7",
```
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/analytics": "^7.6.9",
"@react-native-firebase/app": "^8.4.7",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative "../node_modules/@react-native-community/cli-platform-ios/native_modules"

platform :ios, "10.1"

def deploy_target_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == "react-native-background-downloader"
      target.build_configurations.each do |config|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "10.1"
      end
    end
  end
end

target "pinna" do
  # Pods for pinna
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target "pinnaTests" do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    deploy_target_post_install(installer)
  end
end

target "pinna-tvOS" do
  # Pods for pinna-tvOS

  target "pinna-tvOSTests" do
    inherit! :search_paths
    # Pods for testing
  end
end

```

#### `AppDelegate.m`:

```objc
...
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{  
  if (NSClassFromString(@"ASIdentifierManager")) {
    NSLog(@"⚠️ WARNING: AdSupport is present. IDFA can be accessed.");
  } else {
    NSLog(@"✅ AdSupport is NOT present. IDFA collection should be impossible.");
  }

  [Bugsnag start];
  
  // Firebase
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
...
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 675.26 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found```

<!-- change `[ ]` to `[x]` to select an option(s) -->

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `analytics`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

**Comment by curiousdustin** [comment]
I realize this is related to https://github.com/invertase/react-native-firebase/issues/4300 and https://github.com/invertase/react-native-firebase/issues/4021 but both of those are closed, and I wanted to provide my own details in case it helps others.

**Comment by mikehardy** [comment]
I'm not 100% sure @curiousdustin but I don't believe Kids category apps can use analytics. My best suggestion is to check out the issues list in firebase-ios-sdk and see if others have worked through this. https://github.com/firebase/firebase-ios-sdk

**Comment by curiousdustin** [comment]
Although it is hard to verify because Apple will not share any specific information, at this time is seems my specific rejection case is actually related to using Appsflyer, not Firebase.

I was able to get a build approved by Apple with the following packages installed:

```    "@react-native-firebase/analytics": "^7.6.9",
    "@react-native-firebase/app": "^8.4.7",
    "@react-native-firebase/crashlytics": "^8.4.12",
    "@react-native-firebase/perf": "^7.4.10",```

But, once I added AppsFlyer on to that build, it was rejected again.

I also talked a bit with some contributors on the Firebase modules, and they confirmed that there WAS an issue earlier this year that was causing Firebase Analytics to be flagged by Apple, but this has since bee resolved.

**Comment by mikehardy** [comment]
This may be of interest to people. firebase-ios-sdk 7.8.0 has apparently made enough changes that Analytics is possible from within an iOS-acceptable kids app? https://github.com/firebase/firebase-ios-sdk/issues/7652

**Comment by TheMordeus** [comment]
Im using Firebase Unity SDK and Apple keeps rejecting our app as it contains tracking. Will the fix to firebase-ios be applied to the unity package as well nytime soon, or is there a way to manually apply those fixes to the generated xcode project?

**Comment by mikehardy** [comment]
firebase-ios-sdk 7.8.1 from a few days ago had a *further* fix for kids apps - you check the firebase ios release notes, v11.1.1 here integrated firebase-ios-sdk 7.8.1. I have no experience with Unity, I am sorry

**Comment by jkb0o** [comment]
we also got a rejection from the Apple team with 7.8.1 (firebase-ios-sdk is the only third-party library we use)

**Comment by mikehardy** [comment]
There has been more development in this area, and I believe the combo of firebase-ios-sdk 7.11.0 (which added a cocoapods subspec to Analytics with no AdIds) in combo with the support I added for the same in react-native-firebase v11.4.x may be the final solution: https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md#1141-2021-04-29
