### ISSUE TITLE
[📚][Admob][iOS] Initialize GADMobileAds

### ISSUE THREAD

**Issue by JeffGuKang** [invertase/react-native-firebase#4495]
## Documentation Feedback

I am using mediations with Admob. It works well on Andorid. 
But the mediation adopter returns fail on iOS when I try [Mediation Test Suite](https://developers.google.com/admob/ios/mediation-test-suite).

I solved this issue with [initialize_the_mobile_ads_sdk](https://developers.google.com/admob/ios/quick-start#initialize_the_mobile_ads_sdk). 

```js
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }

// Initialize the Google Mobile Ads SDK.
  [[GADMobileAds sharedInstance] startWithCompletionHandler:nil];
}
```

Result screenshot

![image](https://user-images.githubusercontent.com/216363/98073378-900dda80-1eab-11eb-98dc-96554a81c2ec.png)

How about to add the initialize Admob SDK to the docs?

Thank you for the great library.

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! If there is something missing in the docs, there is an edit link at the top right of every page - we rely on users to help us keep the docs clean + up to date as there are just too many use cases for us to manage it ourselves, PRs happily accepted and merged :pray:
