### ISSUE TITLE
Needs to check the length of name for a method "logEvent(name, params)".

### ISSUE THREAD

**Issue by railsjack** [invertase/react-native-firebase#4496]
https://github.com/invertase/react-native-firebase/blob/81c4e3b7d2ce956ed6a2cc2f40a323ec5379d6a1/packages/analytics/lib/index.js#L79-L83

Here, there is a message string to restrict length of name, but in fact, it does not check the length of the name.
'... Names should contain 1 to 32 alphanumeric characters or underscores.'

Moreover, the limit of the name is 40, which is not 32.
Reference: https://firebase.google.com/docs/reference/cpp/group/event-names#summary

**Comment by mikehardy** [comment]
Thanks for the link to the documents, it appears you are correct. If you want to post a PR we can merge it

**Comment by railsjack** [comment]
Yes, of course, I can. By the way, I think that in order to push a new branch (for fix), I need to have a permission as a contributor.
Otherwise, I will be denied with 403 error.

**Comment by mikehardy** [comment]
Sure - but if you use the github web ui to do the fix (it's a simple one) it will auto-fork for you then start the PR, if you're not a contributor here you just need to do the typical github fork workflow style
