### ISSUE TITLE
[BUG] - onMessage stops to receive messages

### ISSUE THREAD

**Issue by franj0** [invertase/react-native-firebase#4497]
## Issue

react-native-firebase SDK is installed and linked properly by documentation and everything works fine.
I have web script as well  where I have onMessage listener just to keep track with onMessage listener at mobile device.
For some reason after some time, onMessage stop to receive messages while web script still receive them, so it's not backend issue.
If I kill and run app again, everything get back to normal and onMessage is working again until again stops to listen/receive?

It's same for android and iOS

![image](https://user-images.githubusercontent.com/11553585/98115675-7bc7de80-1ea7-11eb-8827-3be3430b3f94.png)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"react-native-firebase": "^5.6.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# pod 'Firebase/AdMob', '~> 6.13.0'
  pod 'Firebase/Auth', '~> 6.13.0'
  pod 'Firebase/Core', '~> 6.13.0'
  pod 'Firebase/Database', '~> 6.13.0'
  pod 'Firebase/Functions', '~> 6.13.0'
#  pod 'Firebase/DynamicLinks', '~> 6.13.0'
  pod 'Firebase/Firestore', '~> 6.13.0'
  pod 'Firebase/Messaging', '~> 6.13.0'
  pod 'Firebase/RemoteConfig', '~> 6.13.0'
  pod 'Firebase/Storage', '~> 6.13.0'
  pod 'Firebase/Performance', '~> 6.13.0'
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by andersonaddo** [comment]
Looks like you're using v5, which isn't supported anymore. 
Upgrade to newest versions and get back to us.

**Comment by franj0** [comment]
@andersonaddo can you repoen this case, it's still happening with last version of RN firebase.
Actually it seems now it's happening only on adroid platform. iOS working fine

use-case
1. User login into app and successfully subscribe to the firebase topic.
2. I send over postman/insomnia request and message it's successfully received in mobile onMessage listener
3. I send it again multiple times and everything it's working
4. And then after few minutes, onMessage stope to receive messages
5. Push notification from  firebase dashboard(cloud messaging) comes to onMessage listener but push notification is priority:high while FCM message is priority: normal

On the web script subscribed to the same topic, all messages comes successfully into listener...

I tried everything, I don't know what to do, is there anyone with similar issue?

![image](https://user-images.githubusercontent.com/11553585/99535712-9327c100-29a9-11eb-9da6-e7483b69ec23.png)

**Comment by mikehardy** [comment]
Latest version is actually v10 now ;-) - and it does include underlying SDK bumps (android can be v26.1.0 now, ios should be v7.1.0). On Android, this can happen due to device power management https://dontkillmyapp.com/ - on iOS similar. You need to use `adb logcat` on android to see what's going on and launch the release mode of your app on a real device from Xcode so you can watch the logs there

**Comment by franj0** [comment]
@mikehardy unfortunately even v10 did not fix my problem. I check power management settings and everything is fine.
iOS worked fine already on v8, Android is still problem for me, I'm stuck :S

**Comment by mikehardy** [comment]
@franj0 anything from this:

> You need to use adb logcat on android to see what's going on

?

**Comment by franj0** [comment]
I used it, there is nothing specifically.
There is logs about emulator cant connect to network (http), and I already add config for non secure protocols.
Also there is log about backround tasks can't receive messages but actually, that is expected. 
[FOREGROUND] -  I track logs while I'm sending FCM messages from server but there is no any log triggered at that point.

I think I'll try to setup new simple RN app with subscribe to topic and onMessage listener, and check again to see if it will be the same problem.
