### ISSUE TITLE
[🐛] No way to upload APNs authentication key in Firebase console

### ISSUE THREAD

**Issue by Luckygirlllll** [invertase/react-native-firebase#4498]
## Issue

Describe your issue here

---

In the official Firebase documentation it says that we need go to the Project settings and in Cloud Messaging Tab add APNs authentication key. However, when I go to the Cloud Messaging tab I see only Web Push Certificates, there is no possibility to upload APNs authentication key for IOS app there. How to upload this key to Firebase project?

<img width="1368" alt="Screenshot 2020-11-04 at 16 14 34" src="https://user-images.githubusercontent.com/10096433/98123363-6f00b600-1eba-11eb-9a00-fbd8f0ce78c7.png">

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Luckygirlllll** [comment]
I figured out what was wrong, I didn't have correct permission in Firebase console, once I got admin permission, I was able to see upload UI for APN key.

**Comment by imtiazraqib** [comment]
So I am having the same issue and I am the **owner** of the project as well but I still do not see the APN upload section.

<img width="1140" alt="Screenshot 2024-05-15 at 1 12 35 PM" src="https://github.com/invertase/react-native-firebase/assets/43179221/d800150e-9d29-4be2-a727-4deeba70a892">
