### ISSUE TITLE
Not able to open notification display documents

### ISSUE THREAD

**Issue by vipsbpatel** [invertase/react-native-firebase#4503]
Please check the below links which are not working!
https://rnfirebase.io/messaging

Notification section and see usage links not working.
![Screenshot 2020-11-05 at 11 16 06 AM](https://user-images.githubusercontent.com/7982710/98202656-74acd900-1f58-11eb-97e0-9dcbb5232103.png)

**Comment by mikehardy** [comment]
@vipsbpatel there is an edit link at the top right of each documentation page, we rely on users to help us keep the package clean + working, PRs happily accepted :pray:
