### ISSUE TITLE
[🐛] Xcode Build Error whit Firebase SDK 7.0

### ISSUE THREAD

**Issue by tekshark** [invertase/react-native-firebase#4504]
## Issue

On building i have some errors in RNFBMessagingSerializer.h and RNFBMessagingSerializer.m

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```
{
  "name": "testSDK",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.12.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-firebase/app": "^8.4.7",
    "@react-native-firebase/messaging": "^7.9.2",
    "@react-navigation/bottom-tabs": "^5.9.0",
    "@react-navigation/native": "^5.7.4",
    "@react-navigation/stack": "^5.9.1",
    "jetifier": "^1.6.6",
    "lodash": "^4.17.20",
    "moment": "^2.29.0",
    "numeral": "^2.0.6",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-device-info": "^6.0.4",
    "react-native-elements": "^2.3.2",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-notifications": "^3.4.0",
    "react-native-paper": "^4.2.0",
    "react-native-reanimated": "^1.13.0",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.11.0",
    "react-native-svg": "^12.1.0",
    "react-native-vector-icons": "^7.1.0",
    "react-navigation": "^4.4.0",
    "react-navigation-stack": "^2.8.2",
    "tekshark-react-native-chart-kit": "^5.6.16"
  },
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/runtime": "^7.11.2",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.3.0",
    "eslint": "^7.9.0",
    "jest": "^26.4.2",
    "metro-react-native-babel-preset": "^0.63.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Override Firebase SDK Version
$FirebaseSDKVersion = '7.00.0'

platform :ios, '10.0'

target 'testSDK' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'testSDKTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'testSDK-tvOS' do
  # Pods for testSDK-tvOS

  target 'testSDK-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Nehal-29** [comment]
Added this in AppDelegate.m

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<NSString *, id> *)options {
    return [[RNFBDynamicLinksAppDelegateInterceptor sharedInstance] application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray *))restorationHandler {
     return [[RNFBDynamicLinksAppDelegateInterceptor sharedInstance] application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
}


Not sure of issue though as It didn't work few times in the beginning and then started working eventually on deleting the build from device and installing a new one after doing a clean build.

**Comment by tekshark** [comment]
This not resolve my problem


Da: Nehal Sanklecha <notifications@github.com>
Risposta: invertase/react-native-firebase <reply@reply.github.com>
Data: venerdì 6 novembre 2020 06:49
A: invertase/react-native-firebase <react-native-firebase@noreply.github.com>
Cc: Francesco Di Vita <francesco.divita@iplusservice.it>, Author <author@noreply.github.com>
Oggetto: Re: [invertase/react-native-firebase] [🐛] Xcode Build Error whit Firebase SDK 7.0 (#4504)


Added this in AppDelegate.m

  *   (BOOL)application:(UIApplication *)application
openURL:(NSURL *)url
options:(NSDictionary<NSString *, id> *)options {
return [[RNFBDynamicLinksAppDelegateInterceptor sharedInstance] application:application openURL:url options:options];
}
  *   (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
restorationHandler:(void (^)(NSArray *))restorationHandler {
return [[RNFBDynamicLinksAppDelegateInterceptor sharedInstance] application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
}

Not sure of issue though as It didn't work few times in the beginning and then started working eventually on deleting the build from device and installing a new one after doing a clean build.

**Comment by Nehal-29** [comment]
@tekshark I'd removed my comment from this post because It was not related to this. I'd to comment it on different post.

**Comment by tekshark** [comment]
https://github.com/invertase/react-native-firebase/pull/4471
This Probably fix my errors...

**Comment by mikehardy** [comment]
Indeed @tekshark - this is in progress. firebase-ios-sdk v7+ will not be supported + buildable until it lands

**Comment by tekshark** [comment]
@mikehardy Great but this is VERY URGENT.
On iOS 14 if the application is uninstalled and reinstalled, notifications are no longer received by the user.
Firebase SDK 7.0 fixed this.
Best Regards

**Comment by mikehardy** [comment]
@tekshark I don't believe what you say is true. Have you seen the solutions posted here? #4299 

Either way, feel free to integrate the PR / patches from #4471 if it is VERY URGENT - they are actually functional just not polished enough for merge yet. All tests are passing on Android and iOS though, there is nothing wrong with the functionality and the polish required to get the PR merged will not actually be anything that changes the implementation or APIs or anything.
