### ISSUE TITLE
FirebaseMessaging not referenced

### ISSUE THREAD

**Issue by brandonkwong** [invertase/react-native-firebase#451]
### Issue

I am working with `react-native-firebase@3.0.0-alpha.5`, and when receiving remote notifications through `firebase.messaging().onMessage()`, I get an unhandled promise warning with the following:

```
ReferenceError · Can't find variable: FirebaseMessaging
```

Although these are just warnings, in some instances, we have experienced app crashes due to this.

I think the below needs to be fixed to properly reference `FirebaseMessaging` in `lib/modules/messaging/index.js#finish()`:

```
FirebaseMessaging.finishRemoteNotification()
FirebaseMessaging.finishNotificationResponse()
FirebaseMessaging.finishWillPresentNotification()
```

I can confirm this working if I manually `import { NativeModules } from 'react-native'` and replace `FirebaseMessaging` with `NativeModules.RNFirebaseMessaging`.

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode 9.0

4. React Native version: 0.47.2

5. RNFirebase Version: 3.0.0-alpha.5

6. Firebase Module: messaging

**Comment by faahmad** [comment]
+1

**Comment by jmhuret** [comment]
In the fix that was pushed, `FirebaseMessaging` was assigned to `NativeModules.FirebaseMessaging` instead of `NativeModules.RNFirebaseMessaging`

Is that correct? I had to use `NativeModules.RNFirebaseMessaging` or else I got errors for an undefined object.
