### ISSUE TITLE
[🐛] Bug Report Enabling Persistence for Realtime Database

### ISSUE THREAD

**Issue by zinnen** [invertase/react-native-firebase#4512]
## Issue

1. The code given in the documentation (setPersistenceEnabled) leads to an error message in index.js: cannot read property 'then' of undefined. It seems that no promise is returned. Without then the code compiles. 

----
index.js: 

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

import database from '@react-native-firebase/database';

database()
    .setPersistenceEnabled(true)
    .then(() => console.log('Realtime Database persistence enabled'));

AppRegistry.registerComponent(appName, () => App);
----

2. Putting a firebase.json in the project root with the documented content will lead to unexpected behaviour on persistence using the database.ServerValue.increment-method. The method checkTest (see below) is called to listen to a number field in realtime database. A testIncrement-method will increase this value. The value is locally added to 0, then propagated to the database leading to the correct final result (database value + increment value). Each time, the value is locally added to 0, and then corrected by the server value. Locally, the database value (that was correctly synced before) is not considered.
----
{
  "react-native": {
    "database_persistence_enabled": true
  }
}
----

----
export async function testIncrement(){
    database()
        .ref('/test/doc1')
        .set({
            number: database.ServerValue.increment(20),
        })
        .then(() => console.log('Data set.'));
}
----

----
export async function checkTest(){
    database()
        .ref('/test/doc1/number')
        .on('value', snapshot => {
            console.log('Data Query: ', snapshot.val());
        });
}
----

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by zinnen** [comment]
I need to take another closer look at where the problem lies and make the error reproducible.

**Comment by luskin** [comment]
We are having the same problem, @zinnen any update on this?
