### ISSUE TITLE
[🐛] React Native iOS Push Notification issues

### ISSUE THREAD

**Issue by rnnyrk** [invertase/react-native-firebase#4516]
## Issue
I'm currently building an app using Firebase for storage, database, authentication and push notifications. Although I'm running into an issue of the Push Noitifications not being displayed on iOS. I've seen some push notifications on iOS devices as well, so I'm not sure what I'm doing wrong at the moment. On Android everythings works fine, so I will try to state the differences. 

I've tried following the docs on https://rnfirebase.io/messaging/server-integration, but I'm running into issues with a couple of things. 

I'm certain;

1. Device tokens are registered
2. Requested for permissions correctly
3. `setBackgroundMessageHandler` called as early as possible
4. `onNotificationOpenedApp` called when app is loaded
5. Testing on a real device (iPhone 8, iOS 14.0.1)

**- First issue**
One thing that is not completly clear is how to use the Cloud Function. I do have the following code:

```javascript
tokens.forEach((token: string) => {
    const message = {
      token,
      notification: {
        title: 'Test title',
        body: `${data.name} heeft ${data.title} toegevoegd`,
      },
      apns: {
        payload: {
          aps: {
            'mutable-content': 1,
          },
        },
        fcm_options: {
          image,
        },
      },
      android: {
        notification: {
          image,
        },
      },
    };

    admin
      .messaging()
      // @ts-ignore
      .send(message)
      .then((response) => {
        console.log('Successfully sent message:', response);
      })
      .catch((error) => {
        console.log('Error sending message:', error);
      });
});
```

Although under "Server Integration" the docs state that I can use tokens as an array I do just use a single token. The reason is that if I pass an array I get the following error: `Unhandled error { Error: Exactly one of topic, token or condition is required`

I'm not sure why this is happening, since I'm just following the docs. 

Also when I remove the `ts-ignore` I get the following error:

```
Argument of type '{ apns: { payload: { aps: { 'mutable-content': number; }; }; fcm_options: { image: string; }; }; android: { notification: { image: string; }; }; token: string; notification: { title: string; body: string; }; }' is not assignable to parameter of type 'Message'.
Type '{ apns: { payload: { aps: { 'mutable-content': number; }; }; fcm_options: { image: string; }; }; android: { notification: { image: string; }; }; token: string; notification: { title: string; body: string; }; }' is not assignable to type 'TokenMessage'.
    The types of 'android.notification' are incompatible between these types.
      Type '{ image: string; }' has no properties in common with type 'AndroidNotification'.
```

I can't seem to find in the docs what part I'm doing incorrectly. So the **Pulling it all together** on [this page](https://rnfirebase.io/messaging/server-integration) seems to be not valid. 

I do doubt if that's the reason why my iOS app isn't receiving any notifications at the moment tho. 

**- Second issue**
While trying to setup the [iOS Notification Service part](https://rnfirebase.io/messaging/ios-notification-images), I got the following error: `'FirebaseMessaging.h' file not found`

My Podfile is below. Furthermore you I did nothing but add the `#import "FirebaseMessaging.h"` line and replace the libes 25-28 as mentioned in the docs.

### App index.js
```javascript
import '@babel/polyfill';
import { AppRegistry } from 'react-native';
import messaging from '@react-native-firebase/messaging';

import App from './src/app/App';
import { name as appName } from './app.json';

// Register background handler as early as possible
messaging().setBackgroundMessageHandler(async (remoteMessage) => {
  console.log('Message handled in the background!', remoteMessage);
});

AppRegistry.registerComponent(appName, () => App);
```

### AppDelegate.m
```
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];

  ....

  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
  [application registerForRemoteNotifications];

  return YES;
}
```

### Podfile
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

project 'APP_NAME',
  'Prod - Debug' => :debug,
  'Acc - Debug' => :debug,
  'Test - Debug' => :debug,
  'Prod - Release' => :release,
  'Acc - Release' => :release,
  'Test - Release' => :release

target 'APP_NAME' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'Firebase/Analytics'
  pod 'FBSDKLoginKit'

  target 'ImageNotification' do
    pod 'Firebase/Messaging', '~> 6.34.0'
  end

  target 'roommatesTests' do
    inherit! :complete
    # Pods for testing
  end
end
```

#### `package.json`:
```json
    "@react-native-firebase/app": "8.4.7",
    "@react-native-firebase/auth": "9.3.2",
    "@react-native-firebase/firestore": "7.9.1",
    "@react-native-firebase/functions": "7.4.10",
    "@react-native-firebase/messaging": "7.9.2",
    "@react-native-firebase/storage": "7.4.11",
    "react-native": "0.63.3",
```

**Comment by mikehardy** [comment]
Just looking really quickly, I think you're missing content-available in the payload for iOS

**Comment by rnnyrk** [comment]
@mikehardy Thanks for your reply. I'd try adding the `content-available` in the payload for iOS, but unfortunately it doesn't seem to work. My message looks like the following now;

```json
    const message = {
      token,
      notification: {
        title: 'Test title',
        body: `${data.name} heeft ${data.title} toegevoegd`,
      },
      apns: {
        payload: {
          aps: {
            'mutable-content': 1,
            'content-available': 1,
          },
        },
        fcm_options: {
          image,
        },
      },
      android: {
        notification: {
          image,
        },
      },
    };
```

I do actually not know where to look for at the moment. Can it maybe be related to one of my issues in the starting post?

**Comment by mikehardy** [comment]
Stop sending notification payload if you want onMessage to be called when not in foreground, when not in foreground if you send a notification payload the underlying SDKs handle it and you don't get control again until your app is foreground. It's in the docs I believe with a table of app states, FCM JSON payload, and hook called

**Comment by rnnyrk** [comment]
@mikehardy Thanks for trying to help out. At the moment I've got it working with the latest shared payload. The one thing I think I'd forget was uploading my .p8 file in the Firebase Console.

**Comment by mikehardy** [comment]
really glad you got it working - configuring this stuff (messaging) and getting it all working in on all the app states is a *bear*

**Comment by ithustle** [comment]
I'm getting the same error `Unhandled error { Error: Exactly one of topic, token or condition is required`. I have all configuration done (because I already tested) but when I try using `.send(message)` with the same payload, I got this message. @mikehardy

**Comment by mikehardy** [comment]
Hi @ithustle 

> Unhandled error { Error: Exactly one of topic, token or condition is required

1. Handle your errors. Everything should be in try/catch etc
2. If you have messaging issues you *must* test by posting raw JSON to the REST APIs. Why? So you can share the JSON here (minus your API key and/or device token of course) and we can see what is wrong
3. I would guess based on your message that you have either none of those three things, or more than one
4. Make sure you are up to date on all your packages before troubleshooting. Troubleshooting against old versions just wastes your time, and it would waste my time except I will spend no time doing so, because it would of course be a waste of time to discover a bug in an old version that was already fixed
5. open a new issue following the template if you are still having issues, but note that ".send()" is not an API I'm familiar with in react-native-firebase, I believe that's an admin SDK thing, so not this repo?

**Comment by ithustle** [comment]
Hi @mikehardy . Thanks for your reply. I have all packages up to date, try/catch and so on and yes, it is on admin SDK, but I saw this on RNFB... but I figure it out when I passed an array on structure referenced on **Pulling it all together** section I get this error, but if I passed a single token, notification is sent... Any ideas?

**Comment by mikehardy** [comment]
The admin sdk has a different API for sending to multiple tokens

**Comment by ithustle** [comment]
Thanks, @mikehardy . I solved using `.sendMulticast()`.
