### ISSUE TITLE
[🐛] Bug Report Title - @react-native-firebase/admob - in rewarded video ads close button is not clickable in iPhone 12 Pro Max

### ISSUE THREAD

**Issue by sagar-chhatrola** [invertase/react-native-firebase#4518]
## Issue

In IPhone 12 Pro Max close button of rewarded video ads is not clickable.

Close button is overlapping with status bar in iPhone 12 pro max.
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-09 at 15 13 00](https://user-images.githubusercontent.com/25894991/98526752-2a04c700-22a0-11eb-86a8-1629a686ac8a.png)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/admob": "^7.6.2",
 "@react-native-firebase/app": "^8.4.1",
```

#### `firebase.json` for react-native-firebase v6:

```json

  {
    "react-native": {
      "admob_android_app_id": "ca-app-pub-3940256099942544/6300978111",
      "admob_ios_app_id": "ca-app-pub-3940256099942544/6300978111"
    }
  }
```

</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 100.58 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2
      Android NDK: 21.0.6113669
  IDEs:
    Android Studio: Not Found
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS iPhone 12 Pro Max
 
- **`@react-native-firebase/app` version you're using that has this issue:**
  - `e.g. 8.4.1`
- **`@react-native-firebase/admob` version you're using that has this issue:**
  - `e.g. 7.6.2`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! Your versions are a bit old, and I know that means firebase-ios-sdk underneath is out of date (can be overridden to 6.34.0 in fact, using the override method detailed on rnfirebase.io front page). Can you make sure you are fully up to date then retry?

**Comment by shogotsuneto** [comment]
I am experiencing this in iPhone 12 pro & iPhone 12 (emu), and updating the package didn't help me.
Although I want this to be resolved in a smart way, there is a tentative workaround using `patch-package`.
What to patch: https://stackoverflow.com/a/64871749

Here is my `patches/@react-native-firebase+admob+10.0.0.patch` for example.

```
diff --git a/node_modules/@react-native-firebase/admob/ios/RNFBAdMob/RNFBAdMobInterstitialDelegate.m b/node_modules/@react-native-firebase/admob/ios/RNFBAdMob/RNFBAdMobInterstitialDelegate.m
index 149c69c..28d4f83 100644
--- a/node_modules/@react-native-firebase/admob/ios/RNFBAdMob/RNFBAdMobInterstitialDelegate.m
+++ b/node_modules/@react-native-firebase/admob/ios/RNFBAdMob/RNFBAdMobInterstitialDelegate.m
@@ -48,19 +48,23 @@ - (void)interstitialDidReceiveAd:(GADInterstitial *)ad {
 }
 
 - (void)interstitial:(GADInterstitial *)ad didFailToReceiveAdWithError:(GADRequestError *)error {
+  [[UIApplication sharedApplication] setStatusBarHidden:NO];
   NSDictionary *codeAndMessage = [RNFBAdMobCommon getCodeAndMessageFromAdError:error];
   [RNFBAdMobInterstitialDelegate sendInterstitialEvent:ADMOB_EVENT_ERROR requestId:[(RNFBGADInterstitial *) ad requestId] adUnitId:ad.adUnitID error:codeAndMessage];
 }
 
 - (void)interstitialWillPresentScreen:(GADInterstitial *)ad {
+  [[UIApplication sharedApplication] setStatusBarHidden:YES];
   [RNFBAdMobInterstitialDelegate sendInterstitialEvent:ADMOB_EVENT_OPENED requestId:[(RNFBGADInterstitial *) ad requestId] adUnitId:ad.adUnitID error:nil];
 }
 
 - (void)interstitialDidDismissScreen:(GADInterstitial *)ad {
+  [[UIApplication sharedApplication] setStatusBarHidden:NO];
   [RNFBAdMobInterstitialDelegate sendInterstitialEvent:ADMOB_EVENT_CLOSED requestId:[(RNFBGADInterstitial *) ad requestId] adUnitId:ad.adUnitID error:nil];
 }
 
 - (void)interstitialWillLeaveApplication:(GADInterstitial *)ad {
+  [[UIApplication sharedApplication] setStatusBarHidden:NO];
   [RNFBAdMobInterstitialDelegate sendInterstitialEvent:ADMOB_EVENT_CLICKED requestId:[(RNFBGADInterstitial *) ad requestId] adUnitId:ad.adUnitID error:nil];
   [RNFBAdMobInterstitialDelegate sendInterstitialEvent:ADMOB_EVENT_LEFT_APPLICATION requestId:[(RNFBGADInterstitial *) ad requestId] adUnitId:ad.adUnitID error:nil];
 }

```

**Comment by mikehardy** [comment]
I'd be willing to accept this as a PR here as long as there was an upstream tracking number in firebase-ios-sdk to pin it too so we could revert when fixed for real

If someone made a quickstart and logged it there we could do this

Until then, patch-package is of course magic :-)

Where to file the issue (check their list first, may already be logged!) https://github.com/firebase/firebase-ios-sdk

Quickstart to get attention upstream with a great repro: https://github.com/firebase/quickstart-ios/tree/master/admob
