### ISSUE TITLE
[🐛] 🔥 Can't find variable: MIN_SECONDS

### ISSUE THREAD

**Issue by Puyodead1** [invertase/react-native-firebase#4534]
## Issue

Randomly started getting this error from the package ``Can't find variable: MIN_SECONDS`` 
![img](https://cdn.moguldevs.xyz/u/hltJ4E.png)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "android-dev": "react-native run-android",
    "android-release": "react-native run-android --variant=release",
    "build-android-prod": "cd android && gradlew assembleRelease && cd ..",
    "start-emulator": "emulator -avd Pixel_4_API_30 -no-snapshot-load -restart-when-stalled"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.13.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.7",
    "@react-native-firebase/app": "^9.0.0",
    "@react-native-firebase/auth": "^9.3.5",
    "@react-native-firebase/database": "^7.5.15",
    "@react-native-firebase/firestore": "^7.10.3",
    "@react-native-firebase/remote-config": "^10.0.1",
    "@react-native-picker/picker": "^1.9.2",
    "@react-navigation/native": "^5.8.6",
    "@react-navigation/stack": "^5.12.3",
    "appcenter": "3.1.2",
    "appcenter-analytics": "3.1.2",
    "appcenter-crashes": "3.1.2",
    "formik": "^2.2.2",
    "moment": "^2.29.1",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-config": "^1.4.0",
    "react-native-elements": "^3.0.0-alpha.1",
    "react-native-fast-image": "^8.3.3",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-gradient-buttons": "^2.0.1",
    "react-native-image-picker": "^2.3.4",
    "react-native-loading-spinner-overlay": "^2.0.0",
    "react-native-modal": "^11.5.6",
    "react-native-modals": "^0.19.9",
    "react-native-network-logger": "^1.8.1",
    "react-native-offline": "^5.7.0",
    "react-native-reanimated": "^1.13.1",
    "react-native-root-toast": "^3.2.1",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.13.0",
    "react-native-side-menu-updated": "^1.2.1",
    "react-native-spinkit": "^1.5.1",
    "react-native-timeago": "^0.5.0",
    "react-native-toast-message": "^1.3.4",
    "react-native-vector-icons": "^7.1.0"
  },
  "devDependencies": {
    "@babel/core": "7.12.3",
    "@babel/runtime": "7.12.5",
    "@react-native-community/eslint-config": "1.1.0",
    "babel-jest": "25.5.1",
    "eslint": "6.8.0",
    "jest": "25.5.4",
    "metro-react-native-babel-preset": "0.59.0",
    "react-easter": "^1.0.6",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz
    Memory: 484.05 MB / 7.88 GB
  Binaries:
    Node: 15.0.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    Visual Studio: Not Found
  Languages:
    Java: 11.0.9
    Python: 2.7.15
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `7.10.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `firestore`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

**Comment by mikehardy** [comment]
I'm surprised you see that with `@react-native-firebase/firestore@7.10.3` - it was released specifically to fix the problem

https://github.com/invertase/react-native-firebase/blob/master/packages/firestore/CHANGELOG.md#7103-2020-11-11

Can you run `npx react-native-clean-project` after shutting your package down, reinstall node_modules / pods and try again?

**Comment by Puyodead1** [comment]
My bad, after looking closer at the stack trace, i found that the issue was caused by trying to sort by the timestamp object, problem disappeared after i added .seconds.
