### ISSUE TITLE
[🐛] Bug Report Title - Notification is not shown when app in foreground and inactive

### ISSUE THREAD

**Issue by thuongtv-vn** [invertase/react-native-firebase#4541]
## Issue

Describe your issue here

I am facing a problem with iOS that the Notification is not shown when the app in foreground and inactive. (App is in the foreground, I swipe down from the top of the device screen to open Notification Center. Now the app is inactive.). I sent a push from Server, I could receive the message via onMessage callback, then we can show an InAppNotification for example. But the app is inactive, then I could not see the InAppNotification. I think it is better if has a system notification on Notification Center, isn't it? Do you guys have any ideas? How can I do that?

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
0.60.5
```

- **Platform that you're experiencing the issue on**:
  - [ x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `app 8.3.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `analytics`
  - `crashlytics`
  - `messaging`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by andersonaddo** [comment]
Push notifications are a problem that need careful inspection to properly understand.
The first question that comes to mind is: is the problem that the notification message isn't being sent, or the in app notification isn't being shown?
Some other questions to think about (some may not apply to you, but I don't wanna keep retyping the same things haha):
https://github.com/invertase/react-native-firebase/discussions/4509#discussioncomment-122892

Also, by the way, you shouldn't  have left out important information like the package versions and the ios version you're working with. Lowers the chance of getting help.
