### ISSUE TITLE
[🐛] Not receiving notifications on ios

### ISSUE THREAD

**Issue by freedomzzzii** [invertase/react-native-firebase#4543]
Not receiving notifications on ios (setBackgroundMessageHandler, onMessage), test push notification on firebase console fill notification title and notification text and select fcm registration token (get fcm registration token from function handleGetFcmToken) but i don't have receiving any notifications. Anyone can help me.

my code
`
UNSAFE_componentWillMount() {
    this.handleRequestUserPermission();
    this.handleBackgroundMessageHandler();
}
componentDidMount() {
      messaging().onMessage(async remoteMessage => {
        console.log('onMessage>>>', JSON.stringify(remoteMessage));
      });
}

handleBackgroundMessageHandler = () => {
    try {
      messaging().setBackgroundMessageHandler(async remoteMessage => {
        console.log('Message handled in the background!', remoteMessage);
      });
    } catch (error) {
      return null;
    }
  }

  handleRequestUserPermission = async () => {
    const authStatus = await messaging().requestPermission();

    if (authStatus === messaging.AuthorizationStatus.AUTHORIZED || authStatus === messaging.AuthorizationStatus.PROVISIONAL) {
      this.handleGetFcmToken();
    }
  }

  handleGetFcmToken = async () => {
    try {
      const registerDevice = await messaging().registerDeviceForRemoteMessages();
      const fcmToken = await messaging().getToken();

      if (fcmToken) {
        console.log("Your Firebase Token is:", fcmToken);
      } else {
        console.log("Failed", "No token received");
      }
    } catch (error) {
      console.log('error>>>', error); // **** it's warning 
      return null;
    }
  }
`

environment
"react": "16.13.1",
"react-native": "0.63.3",
"@react-native-firebase/app": "^9.0.0",
"@react-native-firebase/messaging": "^8.0.1",

<project folder>/firebase.json
`{
  "react-native": {
    "in_app_messaging_auto_collection_enabled": false,
    "analytics_auto_collection_enabled": false,
    "messaging_auto_init_enabled": false,
    "messaging_ios_auto_register_for_remote_messages": false
  }
}
`
AppDelegate.m
`
#import <Firebase.h>

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
      [FIRApp configure];
    }
  // bra bra...
}
`

info.plist
`
<key>FIRAnalyticsDebugEnabled</key>
<false/>
<key>FirebaseAppDelegateProxyEnabled</key>
<false/>
<key>FirebaseScreenReportingEnabled</key>
<false/>
`
i set credentials GoogleService-Info.plist into the {projectName}/ios/{projectName}.xcodeproj

**Comment by zrg-team** [comment]
# Issue

Not receiving notifications on ios. It worked fine on Iphone X. But i tested with iphone 6 12.4.8, iphone 7, etc it not recieving notification

# Project Files
## Javascript
```javascript
class FireBase {
  constructor () {
    this.analyticsInstance = analytics()
    this.messagingInstance = messaging()
    this.crashlyticsInstance = crashlytics()
    this.firestoreInstance = firestore()
  }
  async unsubscribeTopics (lastTopics) {
    try {
      for (let i = 0; i < lastTopics.length; i++) {
        const topic = lastTopics[i]
        await Promise.race([
          this.messagingInstance.unsubscribeFromTopic(topic),
          new Promise((resolve, reject) => {
            setTimeout(() => {
              reject(new Error('TIME_OUT'))
            }, 5000)
          })
        ])
      }
      return true
    } catch (err) {
      console.debug('[FIREBASE] unsubscribeAllTopics ', err)
      storage.setDirectItem(STORAGE_KEYS.REMAIN_STOPICS, JSON.stringify(lastTopics))
      return false
    }
  }

  // topic checker: https://iid.googleapis.com/iid/info/{DEVICE_TOKEN}?details=true
  async subscribeTopics (topics) {
    try {
      for (let i = 0; i < topics.length; i++) {
        const topic = topics[i]
        if (!subscribedTopics.includes(topic)) {
          await this.messagingInstance.subscribeToTopic(topic)
        }
      }
      console.info('[FIREBASE] Topics', topics, ' isDeviceRegisteredForRemoteMessages ')
      return true
    } catch (err) {
      console.debug('[FIREBASE] handleTopics ', err)
      return false
    }
  }

  async initFirebaseRemoteSystem (address) {
    console.info('[FIREBAE] initFirebaseRemoteSystem')
    await this.subscribeTopics()
  }

  async init () {
    try {
      console.info('[FIREBASE] Init', {
        isAutoInitEnabled: this.messagingInstance.isAutoInitEnabled,
        isDeviceRegisteredForRemoteMessages: this.messagingInstance.isDeviceRegisteredForRemoteMessages
      })
      if (!this.messagingInstance.isAutoInitEnabled) {
        this.messagingInstance.setAutoInitEnabled(true)
      }
      this.messagingInstance.setBackgroundMessageHandler(remoteMessage => {
        // console.info('[FIREBASE] background onMessage', remoteMessage)
      })
      if (this.onMessageListener) {
        this.onMessageListener()
      }
      this.onMessageListener = this.messagingInstance.onMessage((remoteMessage) => {
        // console.info('[FIREBASE] onMessage', remoteMessage)
        // Process your notification as required
      })
      if (typeof this.removeOnRefresh === 'function') {
        this.removeOnRefresh()
      }
      this.removeOnRefresh = this.messagingInstance
        .onTokenRefresh(async newToken => {
          console.info('[FIREBASE] onTokenRefresh done', newToken)
        })
      await this.checkPermission()
    } catch (err) {
      console.debug('[FIREBASE] Init error', err)
    }
  }

  async getToken (options = {}) {
    try {
      const currentDeviceToken = await this.messagingInstance.getToken()
      storeAccessible.dispatch(setDeviceToken(currentDeviceToken))
      console.info('[FIREBASE] getToken done', currentDeviceToken)
      this.currentDeviceToken = currentDeviceToken
      // await this.messagingInstance.registerDeviceForRemoteMessages()
      const subscribed = await this.subscribeTopics()
      return {
        subscribed,
        token: currentDeviceToken
      }
    } catch (err) {
      console.debug('[FIREBASE] getToken', err)
      return {
        subscribed: false
      }
    }
  }

  async checkPermission (options = {}) {
    const enabled = await this.messagingInstance.hasPermission()
    console.info('[FIREBASE] checkPermission', enabled)
    if (
      enabled === messaging.AuthorizationStatus.AUTHORIZED ||
      enabled === messaging.AuthorizationStatus.PROVISIONAL) {
      if (!options.ignoreGetToken) {
        return this.getToken(options)
      }
      return true
    } else {
      return this.requestPermission(options)
    }
  }

  async requestPermission (options = {}) {
    try {
      // if (Platform.OS === 'ios') {
      //   await this.messagingInstance.requestPermission()
      // }
      await this.messagingInstance.requestPermission()
      if (!options.ignoreGetToken) {
        return this.getToken()
      }
      return true
    } catch (error) {
      console.debug('[FIREBASE] requestPermission err', error)
      return undefined
    }
  }
}

export default new FireBase()
```
## iOS
### Code
```
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // Add me --- \/
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  // Add me --- /\
  [RNFirebaseNotifications configure];
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif
  for (NSString* family in [UIFont familyNames])
  {
    NSLog(@"%@", family);
    for (NSString* name in [UIFont fontNamesForFamilyName: family])
    {
      NSLog(@"    %@", name);
    }
  }

  NSDictionary *appProperties = [RNFBMessagingModule addCustomPropsToUserProps:nil withLaunchOptions:launchOptions];

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"cpass"
                                            initialProperties:appProperties];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(screenshotDetected) name:UIApplicationUserDidTakeScreenshotNotification object:nil];
  [RNSplashScreen show];
  return YES;
}

- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}

- (void)screenshotDetected {
  NSLog(@"[TENTO][NATIVE] screenshotDetected");
    if (@available(iOS 11.0, *)) {
      QuantaSecurity *manager = [QuantaSecurity allocWithZone: nil];
      [manager isScreenCaptureEnabled:UIScreen.mainScreen.isCaptured];
    }
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```
### ios/Podfile:
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
$FirebaseSDKVersion = '6.34.0'

target 'cpass' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # pod 'SSZipArchive'
  # pod 'Alamofire', '~> 5.2'
  # pod 'KeychainSwift', '~> 19.0'
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'
  # pod 'react-native-exposure-notification-service', :path => "../node_modules/react-native-exposure-notification-service"

  target 'cpassTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```
## Environment
```
"@react-native-firebase/analytics": "^8.0.1",
    "@react-native-firebase/app": "^9.0.0",
    "@react-native-firebase/crashlytics": "^8.5.2",
    "@react-native-firebase/firestore": "^7.8.7",
    "@react-native-firebase/messaging": "^8.0.1",
```

**Comment by mikehardy** [comment]
Testing FCM using the console is not the best method since you don't control the json FCM message contents

Post specific json to the FCM rest API for you device token, and if it's correct (including content-available) it should work

Also I believe that you should set the handlers before you add the app component, long before component mount

**Comment by zrg-team** [comment]
@mikehardy 
I used topic and then push notification used firebase-admin
I received no notifications. Checked https://iid.googleapis.com/iid/info/{DEVICE_TOKEN}?details=true
and it returns iid registered with topic

**Comment by mikehardy** [comment]
That appears to be orthogonal to my comment.
What exact JSON did you post the FCM REST API, what was the app state on device when you did the post, and how did that work?

**Comment by freedomzzzii** [comment]
> Testing FCM using the console is not the best method since you don't control the json FCM message contents
> 
> Post specific json to the FCM rest API for you device token, and if it's correct (including content-available) it should work
> 
> Also I believe that you should set the handlers before you add the app component, long before component mount

@mikehardy 
I try to test push notification with curl on android is success but ios have error InvalidApnsCredential but I add APNs Authentication Key on the firebase (upload file .p8 and set team id). what should i do.
`
curl -X POST --header "Authorization: key=<KEY>"     --Header "Content-Type: application/json"     https://fcm.googleapis.com/fcm/send     -d "{\"to\":\"<TOKEN>\",\"notification\":{\"body\":\"ENTER YOUR MESSAGE HERE\"}}"
`

**Comment by freedomzzzii** [comment]
> > Testing FCM using the console is not the best method since you don't control the json FCM message contents
> > Post specific json to the FCM rest API for you device token, and if it's correct (including content-available) it should work
> > Also I believe that you should set the handlers before you add the app component, long before component mount
> 
> @mikehardy
> I try to test push notification with curl on android is success but ios have error InvalidApnsCredential but I add APNs Authentication Key on the firebase (upload file .p8 and set team id). what should i do.
> `curl -X POST --header "Authorization: key=<KEY>" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"to\":\"<TOKEN>\",\"notification\":{\"body\":\"ENTER YOUR MESSAGE HERE\"}}"`

I try delete APNs Authentication Key on the firebase and add again it work for me. Thank you.
I have one question  when push notification and user still in app it's trigger event onMessage but don't show notification on mobile phone (both of android and ios) i should be use [notifee](https://github.com/notifee/react-native-notifee) to show notification right?

**Comment by mikehardy** [comment]
Obviously as developers of notifee we would say use notifee ;-), and yes that would work in that case. For completeness I always mention that there are other "local device notification" libraries with success reports as well - react-native-push-notifications and react-native-notifications I think? I forget the names but as long as you have a local notification package, you can display a notification in the foreground case

**Comment by freedomzzzii** [comment]
> Obviously as developers of notifee we would say use notifee ;-), and yes that would work in that case. For completeness I always mention that there are other "local device notification" libraries with success reports as well - react-native-push-notifications and react-native-notifications I think? I forget the names but as long as you have a local notification package, you can display a notification in the foreground case

Thank you so much.
