### ISSUE TITLE
 Pushes are not received when the app is closed

### ISSUE THREAD

**Issue by arqhive** [invertase/react-native-firebase#4549]
Hello. I recently migrated my firebase package from v5 to v6.

When migrating to v6, the notification api used in v5 disappeared, so I had a hard time, but I managed to solve it.

However, there was a problem after migration. When the app is in the background or foreground, pushes are received normally.

However, when the app is closed, the push does not arrive no matter how long you wait.

My explanation is based on Android

**Here is my package version**
```
 "react-native": "0.63.3",
 "@react-native-firebase/app": "^8.4.7",
  "@react-native-firebase/messaging": "^7.9.2",
```

**And sent a push like this:**
```
{
  "to": someToken,
  "priority": "high",
  "notification":{
        "title" : "my title",
        "body" : "my body",
    },
    "data" : {
         "title" : "my title",
        "body" : "my body",
        "myData":"111",
    }
}
```

One more, when press push in the background to enter the app, getInitialNotification() is triggered, not onNotificationOpendApp(). Can you tell if this is the same issue as this one?

Thanks for reading.

**Comment by mikehardy** [comment]
Normally I'd say you're missing content-available https://rnfirebase.io/messaging/usage#data-only-messages
But with notification contents the SDK should get it. Perhaps you don't have the right permissions and or entitlements in the app to handle background

What I can say is that the module is working correctly. I send visible notifications, and data-only notifications in all app states on my work app and they work.

You might note that one of the big issues between firebase-ios-sdk v6.x.x and firebase-ios-sdk v7 is notifications not received until you open the app a second time. You don't have that change yet because your versions are a little behind (it was released earlier this week). You should adopt those versions and retry, then carefully examine your project setup

**Comment by raldred** [comment]
Same here. @mikehardy 
"@react-native-firebase/analytics": "^10.0.0",
"@react-native-firebase/app": "^10.0.0",
"@react-native-firebase/crashlytics": "^10.0.0",
"@react-native-firebase/messaging": "^10.0.0",
Firebase iOS SDK 7.1.0

App boots headless when notification is received, handler is never called.
Headless boot log output:

```
setting setBackgroundMessageHandler
Running application App ({
    initialProps =     {
        isHeadless = 1;
    };
    rootTag = 11;
})
Running "App" with {"rootTag":11,"initialProps":{"isHeadless":true}}
```

index.js
```
console.log('setting setBackgroundMessageHandler');
messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('called setBackgroundMessageHandler', remoteMessage);
});

function HeadlessCheck({ isHeadless }) {
  if (isHeadless) {
    // App has been launched in the background by iOS, don't render
    return null;
  }

  return <App />;
}

AppRegistry.registerComponent(appName, () => HeadlessCheck);
```

**Comment by mikehardy** [comment]
If you have a notification payload in your FCM json the underlying sdk sends it to the notification center with the possibility of gaining execution control. You only get control when the user taps the notification. If you take out the notification block and try it, it should work. I have this use case in my app and it appears to work

Side note thanks for adopting v10 quickly. Hopefully the unified versioning is easier but I'm glad that you aren't reporting it is totally broken mainly 😅

**Comment by raldred** [comment]
That seems to contradict the table under 'Message handlers' in the docs on this though?
https://rnfirebase.io/messaging/usage#message-handlers

That suggests to me, when quit with notification and data the handler given to `setBackgroundMessageHandler` would be called.

No worries, everything else seems fine.

**Comment by mikehardy** [comment]
Hmm - I see what you mean - I'm not sure it is an outright contradiction of that table, but there is a missing dimension in the table of "time" - when is the handler called. For mixed payloads I am *fairly* certain that my statement above holds - goes to notification center, you get control when user taps.

https://firebase.google.com/docs/cloud-messaging/concept-options#notification-messages-with-optional-data-payload
