### ISSUE TITLE
[🐛] Bug Report Title - Auth Emulator

### ISSUE THREAD

**Issue by jonathanroze** [invertase/react-native-firebase#4551]
Hi, 

On the documentation it's explain how to use firestore locally by using FireStore Emulator but I can't find anything about use Auth locally.

It's a missing part in docs or it's just not possible ? Thanks

**Comment by mikehardy** [comment]
Just merged auth emulator support, will be in the next release which should be tomorrow

You can see examples of how to use it by examining our test app:

https://github.com/invertase/react-native-firebase/blob/master/packages/auth/e2e/helpers.js
https://github.com/invertase/react-native-firebase/blob/master/.github/workflows/scripts/start-firebase-emulator.sh


https://github.com/invertase/react-native-firebase/blob/4c688413cb6516ecfdbd4ea325103d0d8d8d84a8/packages/auth/e2e/auth.e2e.js#L24-L41

**Comment by mikehardy** [comment]
v10, just released, has auth emulator support! Enjoy
