### ISSUE TITLE
Linker command failed with exit code 1

### ISSUE THREAD

**Issue by bm-software** [invertase/react-native-firebase#456]
After following [this](https://invertase.io/react-native-firebase/#/v2/installation-ios) guide to configure your library I'm getting a linker error.

I am trying to inclue RNFirebase in my project, but I'm getting a linker error. Please help me!

# **Environment**
Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
Build tools: XCode 8.3.3
React Native version: 0.48.4
RNFirebase Version: 2.2.3

# **Error**

    ld: library not found for -lRNFIRMessaging
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

# **Podfile**
        target 'CaliUp' do
      # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
      # use_frameworks!
    
      # Pods for CaliUp
      pod 'Firebase/Core'
      pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
    
      pod 'Firebase/Auth'
      pod 'Firebase/Database'
      pod 'Firebase/Messaging'
    
      # Explicitly include Yoga if you are using RN >= 0.42.0
      pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
      pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge', # Include this for RN >= 0.47
        'BatchedBridge', # Required For React Native 0.45.0+
        'DevSupport'
        # Add any other subspecs you want to use in your project
      ]
    
      pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
      pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'
      pod 'GLog', :podspec => react_native_path + '/third-party-podspecs/GLog.podspec'
    
      target 'CaliUpTests' do
        inherit! :search_paths
        # Pods for testing
      end
    
    end
    
    target 'CaliUp-tvOS' do
      # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
      # use_frameworks!
    
      # Pods for CaliUp-tvOS
    
      target 'CaliUp-tvOSTests' do
        inherit! :search_paths
        # Pods for testing
      end
    
    end

How can I solve this?

**Comment by bm-software** [comment]
I've solved the problem and it wasn't releated to this libary. The ios project file was dirty after another library removal (react-native-fcm). I've manually removed the dependecy and now xcode can build successfully.

Sorry for the non-issue.

**Comment by xstable** [comment]
@bm-software have exactly the same Issue. Can you describe more in detail what you've done to solve it?

**Comment by bm-software** [comment]
@xstable In my case I've manually removed all reference to _react-native-fcm_ library (searching in by name), then I've performed a clean and a new build. :)

**Comment by xstable** [comment]
@bm-software thanks for your response. I got it.
