### ISSUE TITLE
[🐛]React-native firebase dynamic link doesn't works on iOS

### ISSUE THREAD

**Issue by Shashank123sprive** [invertase/react-native-firebase#4564]
Hi @mikehardy 

I am using react native firebase dynamic link library react-native-firebase/dynamic-links version 7.0.1. In my app, after entering email and clicking on the login/registration, the user receives a verification email, and upon clicking on the verify(a deep link is associated to it), the app gets open.

On the android platform the deep link works without any issues across all the devices, unfortunately on iOS platform, the deep link doesn't works in all the devices, it works certain number of devices and doesn't work on others. 

For instance I have tried on iPhone 7, iOS 14.1, iPhone 11, iOS 13.2 the dynamic link didn't work, it was navigated to the app store, but at the same time in iPhone XS 14.2,  iPhone 7 , iOS 14.2, etc it is working like a charm. 

Hope this explains the scenario, I would really appreciate if you can help me out here, as this is really confusing why it works on some and doesn't works on other devices.

**Comment by mikehardy** [comment]
Hi there! This will not be react-native-firebase specific unfortunately, it will be a problem with the underlying firebase-ios-sdk library and interactions with the iOS operating system. One thing noted upstream (I've read some of the related issues - you should as well - https://github.com/firebase/firebase-ios-sdk ) is that sometimes it is solved by a phone reboot even, as the iOS OS needs to download the app links association files before it will work.

All of which is to say that it is of course not ideal that this is not deterministic for you, but it is not something actionable here, you'll have to chase it upstream, starting with a quickstart for reproduction if necessary: https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks

My take away is that dynamic links are *useful* and you *may* use them as a *convenience* but you must never rely on them. The underlying technology has too many failure modes, many of which are network or vendor specific. You have to have a reasonable backup solution.

**Comment by Shashank123sprive** [comment]
Hi @mikehardy ,

Thanks for sharing your insights on this issue. The rebooting way of resolving this issue didn't work out for me, as when I have tried on iOS simulator, and after rebooting the simulator, when I've tried the deep link again, it didn't work. Would you please let me know if there is any other way out, because my app is now being used by real users, and changing the architecture for verification at this moment can be really difficult, any further insights on this would be really helpful.

**Comment by mikehardy** [comment]
I provided tons of insights, and you focused only on rebooting. My comment contains everything I know on the issue, sorry

**Comment by Shashank123sprive** [comment]
hi @mikehardy ,

Thanks for your help on this.

I have actually chased the firebase-ios-sdk repo issue support as well, and I'm going through the issues list you have provided, if I need any further help, I'll reach out to you.

**Comment by mikehardy** [comment]
I do use links in my app as well so I'm very curious if you get any sort of resolution - cheers @Shashank123sprive
