### ISSUE TITLE
[📚] Firebase/app on updates

### ISSUE THREAD

**Issue by Lucasark** [invertase/react-native-firebase#4566]
## Documentation Feedback

Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:

When make updates indicate on changelog which firebase/app update was made for.
For example, I have this situation:
Using crashlytics on 8.4.11 that use firebase/app 8.4.6
And for because of limitation of crashlytics I need install analytics after that, but I can not install last version because it use firebase/app 9.0.0
So, I need discover for which version of analytics was made to firebase/app 8.4.6.
In the end, I found that was app v7.6.8 compatible saw in commits. But it can shortcut if already indicate on change.

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Indeed! This was so confusing and also a problem in the underlying SDKs that the upstream SDKs just switched to "One Version" (all packages share a single version, vs independent versions) and I literally *just* made the same switch here.

Starting with v10.0.0 of all of the react-native-firebase packages, they move together

Unless you are using on-device machine learning and can't update to v10, I recommend you update to that and then not worry about it again

Either way, I can say I totally agree and I *think* I solved it completely just today

**Comment by mikehardy** [comment]
https://rnfirebase.io/releases has the updated info
