### ISSUE TITLE
[🐛] [Android] auth 10.0.0 - Phone Authentication crash in emulator

### ISSUE THREAD

**Issue by codifius** [invertase/react-native-firebase#4573]
## Issue

I installed a fresh react-native projet with only "@react-native-firebase/app" and "@react-native-firebase/auth" and I use 
Phone Authentication  example in the [official documentation](https://rnfirebase.io/auth/phone-auth#sign-in) but  the app crash when using signInWithPhoneNumber method in the Android emulator.

# ENV
    - "@react-native-firebase/app": "^10.0.0",
    - "@react-native-firebase/auth": "^10.0.0",
    - "react": "16.13.1",
    - "react-native": "0.63.3"

**Comment by mikehardy** [comment]
Skipped template, can't help, sorry

**Comment by mikehardy** [comment]
also if there is a crash please please include the actual crash trace, `adb logcat`

**Comment by codifius** [comment]
@mikehardy Sorry for skipping the template 😔,  I formatted my issue to follow the template.

**Comment by mikehardy** [comment]
Oh hey - thanks for including the crash. It reminded me immediately of this #4490 - so it's a duplicate but happily there is a great temporary workaround on that issue that will solve your crash and it's already fixed upstream in firebase-android-sdk for the future
