### ISSUE TITLE
How to pass item value and quantity to analytics?

### ISSUE THREAD

**Issue by hwq0521** [invertase/react-native-firebase#4578]
Hi, I unable to pass the value and quantity of item with the code:
  await analytics().logEvent('purchase', {
      value: parseFloat(amount),
      currency: 'USD',
      items: [
        {
          item_name: PRODUCT_NAME,
          item_category: ITEM_CATEGORY,
          price: parseFloat(amount),
          quantity: 1
        },
      ],
    });

<img width="1013" alt="Screenshot 2020-11-20 at 11 48 10 AM" src="https://user-images.githubusercontent.com/74752520/99755758-867ca780-2b26-11eb-9104-6036aed80f6c.png">

May I know any missing code from my part?

**Comment by andersonaddo** [comment]
https://rnfirebase.io/faqs-and-tips#i-have-a-custom-analytics-parameter-called-items-and-its-not-showing-up-on-the-firebase-console-how-come

**Comment by PlatonSotnykov** [comment]
I have the same issue. They added the "quantity" field in the version 10.1.1 but still there is no any price related fields.

**Comment by mikehardy** [comment]
@PlatonSotnykov "they" was @Danchoys generously advancing the state of react-native-firebase for himself and everyone in #4536  - if you require price-related fields, please examine that PR (to see roughly how it's done) and propose a PR! I'll happily work with you to merge it

**Comment by brerdem** [comment]
Hello! I want to display `price` of the item that being sent with purchase method. I carefully read all comments and took a look at the solution that have been made for `quantity` in #4536. So I changed structs and modified native Java code for Items, in the end came up with the result below. As you can see the price is showing up but in incorrect format. Any idea how to fix it or anybody experienced such issue?

![image](https://user-images.githubusercontent.com/778976/106137471-cf328b80-617b-11eb-9d17-826e8dc74eff.png)

**Comment by mikehardy** [comment]
Oh that's great @brerdem - it sounds like it's really really close - perhaps @Danchoys might be able to lend a hand, if it's down to just formatting it should be something trivial

**Comment by Danchoys** [comment]
Hi, @brerdem ! I think you issue is that you copied this code for the new price parameter:
```
      if (item instanceof Bundle && ((Bundle) item).containsKey(FirebaseAnalytics.Param.QUANTITY)) {
        double number = ((Bundle) item).getDouble(FirebaseAnalytics.Param.QUANTITY);
        ((Bundle) item).putInt(FirebaseAnalytics.Param.QUANTITY, (int) number);
      }
```
It was meant to fix the problem of quantity being passed floating point, which obviously doesn't apply to prices, that are supposed to be such.

In fact I think in your case it is enough to update `structs.js` and `index.d.ts`, no need to modify any native iOS or Android code.

**Comment by aalmodovarr** [comment]
Hi @brerdem @Danchoys ! 

I have the same problem. Using the version `"@react-native-firebase/analytics": "10.5.1"` I cannot get the price of the item to be obtained correctly in firebase, it only comes out in integer format. If I pass` price: 211.48` I get:

![image](https://user-images.githubusercontent.com/19344758/106590893-e8598480-654d-11eb-8a66-5c6174f6ddfe.png)


I have modified the structs.js and index.d.ts files to add the price (and also the currency), but the currency doesn't even appear in the item's properties.

**Comment by Danchoys** [comment]
@aalmodovarr Hi! I have investigated this issue further and set up a native iOS project (using the latest SDK of 7.5.0) with this code:

```objc
- (IBAction)sendEvent:(id)sender {
    NSMutableDictionary *jeggings = [@{
      kFIRParameterItemID: @"SKU_123",
      kFIRParameterItemName: @"jeggings",
      kFIRParameterItemCategory: @"pants",
      kFIRParameterItemVariant: @"black",
      kFIRParameterItemBrand: @"Google",
      kFIRParameterPrice: @9.99,
    } mutableCopy];
    
    jeggings[kFIRParameterQuantity] = @2;

    NSMutableDictionary *itemDetails = [@{
      kFIRParameterCurrency: @"USD",
      kFIRParameterValue: @19.98
    } mutableCopy];
    
    itemDetails[kFIRParameterItems] = @[jeggings];
    
    [FIRAnalytics logEventWithName:kFIREventAddToCart parameters:itemDetails];
}
```

While 100% legit, it still results in the following:

![Screen Shot 2021-02-02 at 18 06 54](https://user-images.githubusercontent.com/2413081/106619253-700cb680-6581-11eb-946f-d826564a5e6a.png)

This makes me believe that this is an internal Firebase problem, and this issue has to be reported there.

**Comment by mikehardy** [comment]
One person's "problem" is another person's "avoid IEEE Floating Point errors when dealing with monetary values at all costs by internally using an integer with enough significant digits to carry any sub-currency-unit partial amounts"

Just sayin' :-)

**Comment by aalmodovarr** [comment]
Thanks @Danchoys for the clarification, it's appreciated!
Right, in Analytics we see the price information correctly, so it seems like a firebase display problem

**Comment by Duc333333** [comment]
> Hi, I unable to pass the value and quantity of item with the code:
> await analytics().logEvent('purchase', {
> value: parseFloat(amount),
> currency: 'USD',
> items: [
> {
> item_name: PRODUCT_NAME,
> item_category: ITEM_CATEGORY,
> price: parseFloat(amount),
> quantity: 1
> },
> ],
> });
> 
> <img alt="Screenshot 2020-11-20 at 11 48 10 AM" width="1013" src="https://user-images.githubusercontent.com/74752520/99755758-867ca780-2b26-11eb-9104-6036aed80f6c.png">
> 
> May I know any missing code from my part?
https://github.com/invertase/react-native-firebase/issues/4578#issue-747117159
