### ISSUE TITLE
[Feature] Firstore - Next generation DB by firebase? Integrate?

### ISSUE THREAD

**Issue by D1no** [invertase/react-native-firebase#458]
Anyone who struggled with flattening out data in the original real-time database maybe appreciates the news: The firebase team has launched Firestore, a new DB that is a more structured and query-chaining tolerant database.

**Product**: https://firebase.google.com/docs/firestore/
**Blog Post (Difference)**: https://firebase.googleblog.com/2017/10/cloud-firestore-for-rtdb-developers.html
**Spec Difference**: https://firebase.google.com/docs/firestore/rtdb-vs-firestore

It is currently in beta. The web sdk does also support offline persistence, so running that in the UI thread in react-native should (in theory) give the same result. Performance (?)

So I created this issue to discuss if this should go into rn-firebase.

Dino

Related (react-redux-firebase): https://github.com/prescottprue/react-redux-firebase/issues/284

**Comment by Salakar** [comment]
@D1no v3 is live since the announcement with firestore support ;) https://invertase.link/rn-firestore

**Comment by Salakar** [comment]
Can leave this open though for discussion I guess though, trigger happy closing of the issue there sorry.

**Comment by D1no** [comment]
outch... sorry I'm an idiot. I somehow got lost between the release notes. lets keep this closed and pretend this never happened... 🐌

**Comment by Salakar** [comment]
@D1no haha no worries, guess we're too quick on the ball 😸. Not much I can do about the releases on GH, they're ordered by when they were created rather than last updated, welp!

**Comment by D1no** [comment]
ah, yeah... forgot that you guys keep the release tag on all past releases. Than you're right. Not my day today.......

**Comment by wwwillchen** [comment]
Wow, really impressed with this team for being so on top of it! I've used v2 for a small project and it was easy-to-use, so I'm looking forward to trying out v3. Thank you!
