### ISSUE TITLE
Not getting notification on Android after release

### ISSUE THREAD

**Issue by pk936** [invertase/react-native-firebase#4581]
"@react-native-firebase/admob": "^7.6.12",
"@react-native-firebase/app": "^9.0.0",
"@react-native-firebase/messaging": "^8.0.1",

I followed all steps mentioned in these 2 pages:

https://rnfirebase.io/messaging/usage
https://rnfirebase.io/messaging/notifications

I used Firebase console's **Noification Composer** to send notification which worked fine in debug mode- emulator and real device both.

But in release mode I do not get notification in both states - quite or background.

I read that to send noification to a device I must have its token. But I have not used token yet and can getting notifications via **Noification Composer** in debug mode to my real device and emulator. Please clarify this too.

**Comment by mikehardy** [comment]
Hi there!
Please re-try with current stable versions
Please use the REST API to post hand-crafted JSON to a specific device token then include that JSON here (minus the device token) so we can see what you sent
Please open a new issue following the template so we have the information we need to troubleshoot
