### ISSUE TITLE
Not getting notification on Android after release for Firebase 10.0

### ISSUE THREAD

**Issue by pk936** [invertase/react-native-firebase#4586]
Following #4581

I upgraded firebase but still not getting notification after release.

    "@react-native-firebase/admob": "^10.0.0",
    "@react-native-firebase/app": "^10.0.0",
    "@react-native-firebase/messaging": "^10.0.0",

I am using **Notificaion Composer** of Firebase Console. Simply just filling textboxes and pubish.

Here is the request

```
{
  "to": "mytoken",
  "data": {
    "text": "There were more suicide deaths than coronavirus deaths in the last two months.",
    "name": "Full Fact",
    "site": "fullfact.org",
    "url": "https://fullfact.org/online/suicide-coronavirus-deaths/",
    "title": "It’s too early to say how many suicides have happened during the pandemic",
    "reviewDate": "2020-11-20T00:00:00Z",
    "textualRating": "There is no evidence for this. Due to the time taken to formally register a suicide death, official figures on recent suicides do not yet exist.",
    "languageCode": "en"
  },
  "notification": {
    "title": "title1",
    "body": "title2"
  }
}
```

**Comment by mikehardy** [comment]
Are you certain you have requested notification permissions, and have created a notification channel etc? And I don't see any channel in use in the JSON? Android requires those if I recall correctly. Use `adb logcat` on a plugged in device to diagnose these things

**Comment by pk936** [comment]
I don't need permission, as I am concerned with Android.

Firebase's **Noification Composer** has kept Channel id optional.

As a solution, I had to subscribe each device to a topic ("All")  and then send notification to that topic. Now it works in release mode.

I believe token/topic should be optional. Started discussion here #4588

**Comment by mikehardy** [comment]
I have sent notifications to all and it has worked 🤷 - no topic subscription.

**Comment by pk936** [comment]
Did you use Firebase's Notification Composer or rest api ?

**Comment by goleary** [comment]
I'm having the same problem, I can't get notifications to surface on Android using the composer or using the admin api from the server.

The exact same notifications do surface in iOS however.


versions:

```
    "@react-native-firebase/analytics": "^10.1.1",
    "@react-native-firebase/app": "^10.1.0",
    "@react-native-firebase/auth": "^10.1.1",
    "@react-native-firebase/crashlytics": "^10.1.1",
    "@react-native-firebase/firestore": "^10.1.1",
    "@react-native-firebase/functions": "^10.1.1",
    "@react-native-firebase/messaging": "^10.1.1",

**Comment by mikehardy** [comment]
@goleary in my experience with firebase cloud messaging, almost no one has the same problem. You should watch `adb logcat` on a real device plugged in to your computer with the app in release mode, and see what pops up - it's usually informative

**Comment by goleary** [comment]
Thanks for the suggestion @mikehardy!

I was previously using the Android emulator, which the docs mention should work. I hooked up a device and was able to receive notifications.

I wonder if it's worth adding a disclaimer in the docs about the Android emulator not always working? That might save you and others time down the road? I'd be happy to open a PR if you'd like.

**Comment by mikehardy** [comment]
I have success with the emulator for what it's worth but real devices are always the gold standard
