### ISSUE TITLE
 CocoaPods could not find compatible versions for pod "Firebase/Messaging"

### ISSUE THREAD

**Issue by sultan-arshi** [invertase/react-native-firebase#4587]
i install firebase app by following 

1. yarn add @react-native-firebase/app.
2. yarn add @react-native-firebase/messaging
3. cd ios/ && pod install

but getting the follwing issue
[!] CocoaPods could not find compatible versions for pod "Firebase/Messaging":
  In Podfile:
    RNFBMessaging (from `../node_modules/@react-native-firebase/messaging`) was resolved to 10.0.0, which depends on
      Firebase/Messaging (~> 7.1.0)

Specs satisfying the `Firebase/Messaging (~> 7.1.0)` dependency were found, but they required a higher minimum deployment target.

**I have tried** 
pod repo update
pod update
sudo gem uninstall cocoapods
and reinstall it 
delete yarn.lock, nod modules, pod folder, pod.lock file
but no gain

**Comment by mikehardy** [comment]
ios9 is no longer supported

> higher minimum deployment target

That message means exactly what it says it means - in general ios9 is being dropped from the entire ecosystem, react-native has dropped it as well, 9 months ago: https://github.com/facebook/react-native/commit/674b591809cd1275b5f1c4d203c2f0ec52303396
