### ISSUE TITLE
React native Firebase Crashlytics is not working on iOS

### ISSUE THREAD

**Issue by Shashank123sprive** [invertase/react-native-firebase#4589]
Hey @mikehardy 

I have recently update the firebase crashlytics libraries on my react native project, but still when I tried crashing the app, it is not being reported in the firebase crashlytics console. It still says gives the message to update the SDK. 

I've followed the doc: https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=ios&authuser=0

Following is my for firebase related libs and their version installed: 

react-native-firebase/crashlytics => 8.4.12 
react-native-firebase/analytics => 7.6.9,
react-native-firebase/app => 8.4.7,
react-native-firebase/dynamic-links => 7.5.11,

And I've removed all fabric instances from pod file, and used the below:

pod 'Firebase/Crashlytics','~> 6.34.0'
pod 'Firebase/Analytics', '~> 6.34.0'
pod 'Firebase/Core'

And in my app, I've used the following way to import the crashlytics  and crash the app on a button click : 
import crashlytics from '@react-native-firebase/crashlytics';
crashlytics().crash(); 

Now, still I can't see the crash reports on the firebase console. Would you please let me know what is missing here, or how can I achieve the successful crashlytics implementation. FYI the analytics is working fine, I can see the debug view as well. I am just facing issue with the crashlytics implementation. 

Any help on this would be really appreciable.

**Comment by andersonaddo** [comment]
You probably should've have followed our instructions for upgrading the Crashlytics than the native firebase docs, it would've been a smoother experience. 
I mean once you got to Crashlytics 8+ all you had to do was delete your pod lockfile and redo the pod install command. RNFB would handle the rest.
I wonder if that has anything to do with the problems you're having. 

Not sure tho; just speculation. 
Oh and also by the way v10 of everything is out so think about upgrading :0

**Comment by Shashank123sprive** [comment]
hi @andersonaddo 
Can you please share the doc link what you have mentioned, meanwhile I shall try deleting the pod lock file and I'll check

**Comment by mikehardy** [comment]
I have an older android package still related to my account, so I still get the upgrade message.

I would definitely move to v10 of everything since you are not using the ML packages (those are the only ones really affected as we bumped versions to V10 - though as always consult the release notes to see if there is some other API you use that was affected). Should be easy to move though.

I'm not sure that will fully fix your issue though. All I know is the current complete integration should look like what's done when you run this script: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by Shashank123sprive** [comment]
hi @mikehardy,

By updating to v10, you meant for all the libs ri8, for instance react-native-firebase/crashlytics => 8.4.12 react-native-firebase/analytics , react-native-firebase/app, and react-native-firebase/dynamic-links ? Please clarify once!

**Comment by Shashank123sprive** [comment]
hi @mikehardy ,

I have upgraded the libs to v10.0.0 and when I'm running the pod install, getting the following error: 

  In Podfile:
    RNFBDynamicLinks (from `../node_modules/@react-native-firebase/dynamic-links`) was resolved to 10.0.0, which depends on
      Firebase/DynamicLinks (~> 7.1.0)

Specs satisfying the `Firebase/DynamicLinks (~> 7.1.0)` dependency were found, but they required a higher minimum deployment target.

Package.json: Libs 

    "@react-native-firebase/analytics": "^10.0.0",
    "@react-native-firebase/app": "^10.0.0",
    "@react-native-firebase/crashlytics": "^10.0.0",
    "@react-native-firebase/dynamic-links": "^10.0.0",

Podfile configuration: 

  pod 'Firebase/Crashlytics', '~> 7.1.0'
  pod 'Firebase/Analytics',  '~> 7.1.0'
  pod 'Firebase/Core'
  pod 'Firebase/DynamicLinks', '~> 7.1.0'

** As per the instructions, I have tried changing the deployment target from Xcode to 10.0, 11.0, 12.0, even to 13.0 but it's giving the same issue.

Would you please let me know what I'm missing here?

**Comment by mikehardy** [comment]
Something is still 9 for ios I am guessing, not sure what but the message is clear. Maybe one of the other targets moved too (tvos or macos or something) but that will be the root cause.

**Comment by Shashank123sprive** [comment]
hi @mikehardy, let me check if tvOS is having lower deployment target or not, if its lower, I'll increase that as well, and post that I'll try installing pods and let you know!

**Comment by andersonaddo** [comment]
Honestly you should probably just remove tvOS anyways. It doens't benefit most RN devs, so removign it makes your project directory and Xcode a bit cleaner.

**Comment by Shashank123sprive** [comment]
hi @andersonaddo thanks for your suggestion, would you please let me know if removing tvOS will have any impact on the existing codebase?

**Comment by andersonaddo** [comment]
It shouldn't.
I removed it and had 0 problems. It was a while ago so I don't remember the exact details, but it was easy.

https://stackoverflow.com/questions/46770725/can-i-delete-the-tvos-from-react-native-project
(be sure to read the comments here first)

**Comment by Shashank123sprive** [comment]
thank you @andersonaddo I'll check this out and let you know!

**Comment by Shashank123sprive** [comment]
hi @mikehardy , I have tried increasing the deployment target, but it still gives the same error

**Comment by mikehardy** [comment]
Sorry this is happening for you but we'll need a reproduction in order to fix it, we can't reproduce this locally.
You can build a quick sample app from scratch with this script, and it shows everything working fine, so if you can then discover the difference between that app and your app, that will be the problem and you can either fix it in your project or it will result in a fix in this module if the module has a fault

https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by Shashank123sprive** [comment]
hi @mikehardy thanks for the response, I will try this, and let you know!

**Comment by Shashank123sprive** [comment]
hi @mikehardy I was able to upgrade the firebase lib versions to the latest version 10.1.0 😃, actually I kept deployment target in Xcode to 10.0 but in the Podfile it was 9.0 only, that was giving issue. Following is my configuration:

Package.json

    "@react-native-firebase/analytics": "^10.1.0",
    "@react-native-firebase/app": "^10.1.0",
    "@react-native-firebase/crashlytics": "^10.1.0",
    "@react-native-firebase/dynamic-links": "^10.1.0",

Podfile: 
  platform :ios, '10.0' ==> on the top
  and in target 
  pod 'Firebase/Crashlytics','~> 7.1.0'
  pod 'Firebase/Analytics', '~> 7.1.0'
  pod 'FirebaseCore'
  pod 'Firebase/DynamicLinks','~> 7.1.0'

Now, in my app, I've used the following way to import the crashlytics and crash the app on a button click :
import crashlytics from '@react-native-firebase/crashlytics';
crashlytics().crash();

I can't see the crashlytics updated in the firebase console, and it is still showing the error "As of November 16, we are only processing crashes from the Firebase iOS SDK 4.0.0+. As a result, you might be seeing no new crashes in your dashboard" 

Will it take time to update in crashlytics console, if yes, then please let know approximately how much?
 
Any suggestions on this would be appreciated.

**Comment by mikehardy** [comment]
Sometimes it takes a while for crashes to be processed yes.

Also, you must restart the app post-crash for it to send (because, the crash sending logic is *in* the app, the crash is just sitting on the mobile device storage until the app starts again, sees the crash dump and sends it)

There is lots of information on the upstream docs on turning on debugging so you can see what's happening and to make sure it works https://firebase.google.com/docs/crashlytics/test-implementation?platform=ios - note the '-FIRDebugEnabled' argument you can put in the build for instance

Note that in general doing it in release mode on a real device is most reliable. If you crash it under debugger it does not work. If you crash it in debug and haven't uploaded dSYMs for debug it won't work, etc.

Final note: it's working for everyone else - I say that to emphasize that the module is working. Once you get your local project working by following the docs etc, it will work for you. But it won't result in a change here so this issue may not get continued priority for interaction from us

**Comment by lukebrandonfarrell** [comment]
@mikehardy 

> Note that in general doing it in release mode on a real device is most reliable. If you crash it under debugger it does not work. If you crash it in debug and haven't uploaded dSYMs for debug it won't work, etc.

AKA. Test on real device. This one got me!

**Comment by Shashank123sprive** [comment]
hi @mikehardy thanks for your valuable response, crashing the app on a real device(in release mode  not in debug )worked for me, and now I can see the crashlytics is updated. Although I had to upload the missing .dSYM file reported in the console, as there was an alert saying " Upload missing dsym to process 2 crashes", any thoughts on this?

**Comment by mikehardy** [comment]
With no dsyms you get no reports, this is expected

https://stackoverflow.com/questions/54577202/how-to-run-upload-symbols-to-upload-dsyms-as-a-part-of-xcode-build-process/55796619#55796619

Sounds like things are working

**Comment by Shashank123sprive** [comment]
hi @mikehardy yes, but there is one more scenario, I crashed from two different devices, but I can see in the firebase crashlytics console only one user's crash report, any thoughts? 

<img width="1479" alt="Screenshot 2020-12-09 at 4 52 04 PM" src="https://user-images.githubusercontent.com/74611450/101624044-5d717780-3a3f-11eb-85f4-c3bd394ea985.png">

**Comment by mikehardy** [comment]
I think you should turn on firebase debugging and watch the xcode console from the device after launching the app from xcode

**Comment by Shashank123sprive** [comment]
hi @mikehardy I have pushed to the TestFlight from there I installed the app and then crash it by clicking one button(the logic to crash is defined there), however what you're suggesting is for in debug mode. One user is somewhere else, who installed the app and clicked on the button to crash. Please suggest!

**Comment by mikehardy** [comment]
You can do release mode from xcode. I believe my suggestion stands.

**Comment by mikehardy** [comment]
Also worth noting that if the user never restarts the app, the crash report will never be sent. It is sent during startup.

**Comment by Shashank123sprive** [comment]
hi @mikehardy Thanks for the response. I'm reaching out to the user, and I'll ask him to crash again, then restarts the app, and I'll also check the release mode from Xcode. I'll get back to you with the update!

**Comment by Shashank123sprive** [comment]
hi @mikehardy I check with the user, and asked him to crash the app and restart the app, it was reported, but he wasn't sure whether he restarted the app on the previous trial or not, but anyhoo, its working fine, it is reporting the crashes. If anything will come up in future, I'll reach out to you. Thank you!

**Comment by mikehardy** [comment]
glad it's working!

**Comment by markmoomoo** [comment]
Got a question about react-native-firebase/crashlytics
for the native(objective-C) crash report, does it need a separate configuration, or react-native-firebase/crashlytics added in react-native will handle that too?
