### ISSUE TITLE
The Firebase Android library firebase-core is no longer needed.

### ISSUE THREAD

**Issue by yum650350** [invertase/react-native-firebase#4593]
According to the [firebase release notes](https://firebase.google.com/support/release-notes/android)
![Screen Shot 2020-11-23 at 5 50 07 PM](https://user-images.githubusercontent.com/48589760/99948398-5ea27380-2db4-11eb-9844-292c94d0158f.png)

Shall it be removed from the `@react-native-firebase/app` dependencies?

@react-native-firebase/app/android/build.gradle
```diff
dependencies {
  implementation platform("com.google.firebase:firebase-bom:${ReactNative.ext.getVersion("firebase", "bom")}")
-  implementation "com.google.firebase:firebase-core"
  implementation "com.google.firebase:firebase-common"
  implementation "com.google.android.gms:play-services-auth:${ReactNative.ext.getVersion("play", "play-services-auth")}"
}
```

**Comment by mikehardy** [comment]
Hi there!
You can reach in to node_modules and edit the file to try it, if it works, make a PR for the same and then if that passes CI (it should? according to the release notes) then I can merge and release it

**Comment by yum650350** [comment]
@mikehardy Sure, here comes the PR.

I've run `tests:android:build` and tested on an app and see nothing wrong.
