### ISSUE TITLE
await firebase.messaging().getToken() - PHONE_REGISTRATION_ERROR

### ISSUE THREAD

**Issue by crtdaniele** [invertase/react-native-firebase#4599]
Hi,
I have an issue with a Xaomi Redmi Note 8T, the error is from this line of code (react native 0.63):

`await firebase.messaging().getToken()`

The error is PHONE_REGISTRATION_ERROR. The phone has google play services and google play store, I have tried to delete the cache and the data from google play services and google play store. I have tried also to login and logout again from my account google and with another account google without success.

Any ideas to resolve?

Thanks.

**Comment by andersonaddo** [comment]
Have you checked logcat? Will probably give some useful info.

**Comment by crtdaniele** [comment]
What is logcat?

**Comment by Rakhilpr96** [comment]
I have the same issue with my realme 8 pro device (Android 11). No idea how to
![firebaseissue](https://user-images.githubusercontent.com/62371651/128248340-09e8171b-6e9c-485d-8b96-100df781d1ef.png)
 fix it

**Comment by mikehardy** [comment]
Please understand posting on old closed issues with no meaningful reproduction information will not yield help, as we have no information to help you with.

You may have a phone without google play services though (there's an API on the app module here in Utils that can help you detect if you have them or not.). Or you may have an incorrect API key configured, or the API key may be restricted in google cloud platform, or...many other things

If you open a new issue the template asks for the information needed to troubleshoot, and a https://stackoverflow.com/help/minimal-reproducible-example in this case would be a small + complete App.js that may be dropped in a skeleton project (like that created by https://github.com/mikehardy/rnfbdemo/commits/master/make-demo.sh)

**Comment by Prasis73** [comment]
found solution?? Faced same issue.........

**Comment by Prasis73** [comment]
How? can you please explain

**Comment by Rakhilpr96** [comment]
It's an issue related to the device. When I reset my device this issue
resolved for me.

**Comment by AntonyDonald** [comment]
I am facing the same issue on the Redmi Note 7.
