### ISSUE TITLE
Can't run on android

### ISSUE THREAD

**Issue by Panda313** [invertase/react-native-firebase#46]
Hi guys

The lib is working like a charm on iOS (and thanks a lot for such an amazing job) ; However, I can't get it working on Android. 

<img width="344" alt="capture d ecran 2017-04-11 a 11 24 10" src="https://cloud.githubusercontent.com/assets/4342171/24902340/272d45dc-1eaa-11e7-8cc9-50eb02550715.png">

Here are my graddle config ; 
app.graddle : 
<img width="522" alt="capture d ecran 2017-04-11 a 11 21 48" src="https://cloud.githubusercontent.com/assets/4342171/24902304/12c53cc6-1eaa-11e7-936a-0552704450f9.png">
<img width="335" alt="capture d ecran 2017-04-11 a 11 22 03" src="https://cloud.githubusercontent.com/assets/4342171/24902312/17211be6-1eaa-11e7-9801-6b0e6a3fbb46.png">
<img width="399" alt="capture d ecran 2017-04-11 a 11 22 15" src="https://cloud.githubusercontent.com/assets/4342171/24902327/1ef2f5ec-1eaa-11e7-820d-b83780002555.png">

Also, my android device config : 
<img width="1188" alt="capture d ecran 2017-04-11 a 11 21 27" src="https://cloud.githubusercontent.com/assets/4342171/24902361/37c0c9be-1eaa-11e7-9b1a-0b1f4039036f.png">

I digged into the web and I think it might be a play-services dependices error or something like that, but I can't figure it out.

config : 
    "firebase": "^3.7.5",
    "react": "^15.4.2",
    "react-native": "^0.42.2",
    "react-native-firebase": "^1.0.0-alpha12",

Any ideas ?

Thanks

Romain

**Comment by Ehesp** [comment]
See https://github.com/invertase/react-native-firebase/issues/44 

Emulator doesnt have Play Services. Need to add this to a touble shooting guide!

**Comment by chrisbianca** [comment]
With the next release it will default to prompt to install Play Services rather than just throwing an error which will hopefully make it clearer as well

**Comment by Salakar** [comment]
Code 2 just means it's out of date, you can update your emulator image and make a new ine to fix this, but you can also just turn off this error as its generally fine if it's slightly out of date.

Turn off error:
In your initializeApp for Rnfirebase add the config option `errorOnMissingPlayServices` and set to false.

**Comment by Panda313** [comment]
Thanks guys,

Actually I was pretty sur Google services were installed and up to date. I'll have a deeper look. i'll keep you posted this afternoon.

Thanks

**Comment by Panda313** [comment]
You were right, I updated everything and now it's working. Thanks again !
