### ISSUE TITLE
Vercel deploy failing on normal PR test builds and merges

### ISSUE THREAD

**Issue by mikehardy** [invertase/react-native-firebase#4600]
https://vercel.com/invertase/react-native-firebase/l8xtr6lmy

Not sure why?

> Command "cd website && yarn && yarn run build" exited with 1

```

 
--
10:30:05.113 | $ gatsby build
10:30:08.374 | success open and validate gatsby-configs - 0.268s
10:30:08.977 | success load plugins - 0.602s
10:30:09.055 | success onPreInit - 0.076s
10:30:09.059 | success delete html and css files from previous builds - 0.003s
10:30:09.066 | success initialize cache - 0.006s
10:30:09.097 | success copy gatsby files - 0.031s
10:30:09.115 | success onPreBootstrap - 0.018s
10:30:09.163 | success createSchemaCustomization - 0.001s
10:30:10.358 | /vercel/workpath0/tsconfig.json
10:30:10.673 | Using TypeScript 3.9.7 from /vercel/workpath0/website/node_modules/typescript/lib
10:30:17.970 | Error: /vercel/workpath0/node_modules/@types/react-native/node_modules/@types/react/index.d.ts(2980)
10:30:17.970 | Duplicate identifier 'LibraryManagedAttributes'.
10:30:17.971 | Error: /vercel/workpath0/node_modules/@types/react-native/node_modules/@types/react/index.d.ts(2991)


```

**Comment by andersonaddo** [comment]
Let the entropy-induced headaches commence.

**Comment by mikehardy** [comment]
Yeah, entropy literally never stops. I released useful energy as pointless heat just by transmitting this message, and the heat probably broke something in the internet somewhere.

**Comment by mikehardy** [comment]
I have a rough root cause analysis on this one. 'react' as a dependency has moved from v16 to v17, and there are some types dependencies that are loose (`*` specified for `@types/react`) while others are pinning a version.

So multiple react types are coming in at the same time causing it to blow up. I can reproduce it in a clean RNFB checkout locally by doing `yarn && cd website && yarn && yarn build`) but I don't have a fix quite yet

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25145
