### ISSUE TITLE
[🐛] remote-config@10.0.1 has peer dependency app@9.0.0

### ISSUE THREAD

**Issue by robrechtme** [invertase/react-native-firebase#4607]
## Issue

When I install `@react-native-firebase/remote-config@10.0.1`, I get a warning stating that it needs `@react-native-firebase/app@9.0.0` as a peer dependency. Shouldn't it be `@react-native-firebase/app@10.0.0`?

I think this was [fixed recently](https://github.com/invertase/react-native-firebase/commit/363063b4137156d1a305b2545e51dd738f53bc8e) for `10.0.0`, but not for `10.0.1`

**Comment by mikehardy** [comment]
Hi there! Yes indeed

It's a duplicate in a way - was a publishing issue as I bumped everything to 10.0.0 - if you use 10.0.0 it should work great, and I'm sorry for the problem - first reported here https://github.com/invertase/react-native-firebase/discussions/4590

Easier to track here as it is an issue more than a discussion - so I will keep this one open until I release (should be today)

**Comment by mikehardy** [comment]
Note that when using v10+ you may ignore the peer dependency of course, *all* the versions should be v10.0.0 really - that was the intention, and I think with the next release they will all go to 10.1.0

**Comment by LonelyCpp** [comment]
I'm a bit confused about the versions. 
npm shows latest as `v10.0.1`, but changelog goes from `v10.0.1` -> `v10.0.0` 🤔

**Comment by robrechtme** [comment]
@LonelyCpp all firebase packages have been reversioned so that they have the same version (`10.0.0`). I believe `remote-config` was at `10.0.1` **before** the reversioning, which makes it confusing. I think there have been some issues with publishing to npm, but `v10.0.0` is in fact the _latest_ version.

**Comment by mikehardy** [comment]
The latest publish (v10.1.0) was done fully-automated via our github publish action here, and it appears to have resolved this 100% after all the recent changes. Individual and Aggregate changelogs were generated correctly, version bumps and peerDep cross-dependencies were auto-committed correctly, and published packages to npmjs.com all contain the right bits and deps. 💯
