### ISSUE TITLE
Error: You attempted to use 'firebase.analytics' but this module could not be found.

### ISSUE THREAD

**Issue by pavelustenko** [invertase/react-native-firebase#4608]
## Issue
I tried to migrate to v6 according to migrate docs. I doublechecked that I didn't missed anything.
I'm using messaging, crashlytics and analytics subpackages in my project.
Every Screen component in js has following code:

```
import firebase from "@react-native-firebase/app";
....
 componentDidMount() {
        firebase.analytics().logEvent("SCREEN_FindUser");
// log user navigates screen event
    }
```
but every time the code called I'm getting a warning:
` WARN     Possible Unhandled Promise Rejection (id: 2):
Error: You attempted to use 'firebase.analytics' but this module could not be found.`
I checked package.json - it has:
```
  "dependencies": {
...
    "@react-native-firebase/analytics": "^10.0.0",
    "@react-native-firebase/app": "^10.0.0",
    "@react-native-firebase/crashlytics": "^10.0.0",
    "@react-native-firebase/messaging": "^10.0.0",
...
}
```
I checked node_modules\@react-native-firebase\analytics\ dir it exists and contains code files

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there!
With apologies, this is project-specific. There is no problem with the module here, so I will close this. The resolution will be that you find the integration error in your project and correct it.

In an attempt to provide some guidance though, since this is a common problem, I have a script that builds a demo react-native-firebase project from scratch - it does every single thing in an automated way, and analytics does load correctly in it.

If you run that script (or simply read it and use it as a checklist for the full integration) it should help you find the problem

https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by pavelustenko** [comment]
I found that if I change import from
`import firebase from "@react-native-firebase/app";`
to 
`import {firebase} from "@react-native-firebase/analytics";`
warning is gone.

**Comment by mikehardy** [comment]
I don't get any errors when using analytics in functional components. It's used here in a template you can clone and use directly. Something's wrong with your project and bears closer examination on your part I think https://github.com/invertase/react-native-firebase-authentication-example/

**Comment by hotaryuzaki** [comment]
> I don't get any errors when using analytics in functional components. It's used here in a template you can clone and use directly. Something's wrong with your project and bears closer examination on your part I think https://github.com/invertase/react-native-firebase-authentication-example/

I get this error when I want to upgrade react-native-navigation to v6.
I tried to rollback (v3) and the error is gone.
I update again to v6 and the error is occur.
The error is solved if I change to direct call `firebase.analytics().setItem()`
I don't know what caused it.

**Comment by mikehardy** [comment]
Very strange. react-navigation has support for web, and a larger install base - it's one of the reasons I use it in work projects and in that template above even though I use other wix modules and am a fan of that shop, for sure. It does not suffer from this problem ;-) - something to consider

**Comment by carlosen14** [comment]
same problem, had to re-run `npm run ios`, to update the modules
