### ISSUE TITLE
Can't run application with RNFirebase 

### ISSUE THREAD

**Issue by gadfil** [invertase/react-native-firebase#462]
Hi!
Thank you for your library 
I cant install react-native-firebase
I have this error 

> Loading dependency graph, done.
Bundling `index.js`  [development, non-minified]  0.0% (0/1), failed.
error: bundling failed: ambiguous resolution: module `/Users/reed/WebstormProjects/chat/index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 
>
>  * `/Users/reed/WebstormProjects/chat/ios/Pods/React/package.json`
 > * `/Users/reed/WebstormProjects/chat/node_modules/react-native/package.json`

My Podfile:
platform :ios, '9.0'
  target 'chat' do
   pod 'Firebase/Core'
   pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  pod 'Firebase/Auth'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'BatchedBridge', # Required For React Native 0.45.0+
  'Core',
  ]
  end
 post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end
 

### Environment

1. Application Target Platform: ios

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode 9.0 (9A235), ios 11.0

4. React Native version: 0.49.1

5. RNFirebase Version: 3.0.0

6. Firebase Module: Auth

**Comment by jcharbo** [comment]
+1

**Comment by gadfil** [comment]
Thank you
