### ISSUE TITLE
[📚] Missing FirebaseJsonConfig types

### ISSUE THREAD

**Issue by b3coded** [invertase/react-native-firebase#4626]
## Documentation Feedback

Documentation about `FirebaseJsonConfig` types is missing [here](https://rnfirebase.io/reference/app/firebasejsonconfig), see the screenshot:

![image](https://user-images.githubusercontent.com/38642628/100445179-6a7b8780-308b-11eb-8542-233717dc52d9.png)

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! Where is the link that directs you to this page?

**Comment by b3coded** [comment]
https://rnfirebase.io/reference/app/firebasejsonconfig

When I search `json` and click on search result

![image](https://user-images.githubusercontent.com/38642628/100458371-69a22000-30a2-11eb-9ad6-044a4dcb1180.png)

**Comment by mikehardy** [comment]
Thank you. Interesting, going to have to dig deeper to see what's going on there.

**Comment by b3coded** [comment]
This can be related to this line

https://github.com/invertase/react-native-firebase/blob/11867daf493233eb05cb3224061b2a209a47b1df/packages/app/lib/index.d.ts#L245

because it is an empty interface and the script to generate the docs can't get the types from the other packages

**Comment by mikehardy** [comment]
That was my first guess as well but I wasn't concrete on it and I've got a pile of other priorities unfortunately. If you can untangle it at all I would :heart: a PR :-) :pray:

**Comment by b3coded** [comment]
@mikehardy I forked the project to see what is happening and when I ran this [script](https://github.com/invertase/react-native-firebase/blob/master/website/scripts/generate-typedoc.js) it generated a duplicated item of `FirebaseJsonModule`

this one is the empty interface
![image](https://user-images.githubusercontent.com/38642628/100516212-1fcc3f00-3161-11eb-9793-fd4c3f570ff3.png)

this one has all the keys of all the `@react-native-firebase` packages
![image](https://user-images.githubusercontent.com/38642628/100516217-2a86d400-3161-11eb-9824-c400add01c44.png)

**Comment by mikehardy** [comment]
So...it is actually capable of generating a useful file but also generates a useless one !?
- why the duplicate and/or
- can it either just generate the correct one or discard/reference the useful one

I'll admit I'm not that familiar with the script itself, I have no special knowledge here but this is a very interesting discovery

**Comment by b3coded** [comment]
Yes!
but if we are not going to use this interface in our code, we can transform this interface into a [JSON Schema](https://json-schema.org/learn/getting-started-step-by-step.html).

```json
// firebase.json
{
"$schema": "https://<firebase_config_schema_file_url>",
}
```

**Comment by mikehardy** [comment]
I'll ask for some architecture taste on that one :-), @Salakar - is it appropriate to change the firebase.json into a JSON Schema as @b3coded mentions? Seems correct to me on first thought, and would potentially help us untangle a typedoc generation error

**Comment by Salakar** [comment]
JSON Schema seems ok to me. We don't actually use the types for it other than to have them appear on the reference documation.
