### ISSUE TITLE
[v3-docs][iOS] The name of the given podspec `yoga` doesn't match the expected one `Yoga`

### ISSUE THREAD

**Issue by mjmaix** [invertase/react-native-firebase#463]
### Issue

following this [instruction link](https://invertase.io/react-native-firebase/#/installation-ios?id=_22-add-the-required-pods) `pod install` returns

```ruby
Analyzing dependencies
Fetching podspec for `RNFirebase` from `../node_modules/react-native-firebase`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `Yoga` from `../node_modules/react-native/ReactCommon/yoga`
[!] The name of the given podspec `yoga` doesn't match the expected one `Yoga`
```

### Solution

instead of

`pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"`

use lowercase yoga

`pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"`

### Environment

1. Application Target Platform: 
IOS

2. Development Operating System: 
macOS High Sierra

3. Build Tools: 

4. React Native version: 
		"react": "16.0.0-beta.5",
		"react-native": "0.49.1",

5. RNFirebase Version: 
"react-native-firebase": "^3.0.0"

6. Firebase Module: 
11.4.2

others:
7. Cocoapods version

```
Michael-MBP:~ mick$ gem which cocoapods
/Users/mick/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.3.1/lib/cocoapods.rb
```

**Comment by robdonn** [comment]
I'm running into this issue as well, but changing `"Yoga"` to `"yoga"` doesn't work for me, it still thinks it should be looking for `Yoga`.

```
pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'BatchedBridge', # Required For React Native 0.45.0+
  'Core',
  # Add any other subspecs you want to use in your project
]
```

```
[!] The name of the given podspec `yoga` doesn't match the expected one `Yoga`
```

**Comment by brianhiss** [comment]
I had the same issue as @mjmaix, I used the same solution to fix the issue.

`pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"`

**Comment by chrisbianca** [comment]
I have good news for you, as of last today's v3.0.2 release, `react-native link` is supported for iOS and Android so you no longer need to set up React, Yoga, `react-native-firebase`, etc as Pods.  You do still need to have Firebase installed using pods as recommended by Google.

Check out the new installation instructions:

iOS: http://invertase.link/ios
Android: http://invertase.link/android

I'm going to close this, but shout if you're still having issues

**Comment by lucasbento** [comment]
Just in case someone bumps into this (this is the first link on google when you search for that problem), I fixed mine doing the following:

#### `ios/Podfile`
```diff
-pod 'Yoga', path: "./../node_modules/react-native/ReactCommon/yoga/Yoga.podspec"
+pod 'yoga', path: "./../node_modules/react-native/ReactCommon/yoga/yoga.podspec"
```
