### ISSUE TITLE
Firebase Phone Auth Captcha

### ISSUE THREAD

**Issue by jcharbo** [invertase/react-native-firebase#465]
Am I correct in my understanding that the react-native-firebase implementation of Firebase phone auth has to use the web captcha?  If so, I consider that an really bad user experience for a native app.  Would implementing the native firebase auth library bypass this?  Are there any plans to do so?
thanks
Jeremey

**Comment by Ehesp** [comment]
Hey, no it doesn't require captcha. Check out our new WIP docs that explain one of the methods:

https://invertase-default.firebaseapp.com/docs/v3.0.*/auth/phone-auth

**Comment by bintoll** [comment]
Hello! I wrote like it is Described in docs, but it requests capcha. So the issue should be reopened

**Comment by chrisbianca** [comment]
@bintoll it will only use captcha on iOS if you haven't set up the silent notifications as detailed here: https://firebase.google.com/docs/auth/ios/phone-auth#start-receiving-silent-notifications

**Comment by congnguyen91** [comment]
- Hello, How can I remove reCaptcha for   
```
firebase
      .auth()
      .verifyPhoneNumber('xxxxxxxxx)
```
on iOS

**Comment by fisherwise** [comment]
@congnguyen91 check this https://github.com/invertase/react-native-firebase/issues/1171

**Comment by musicmeetscode** [comment]
Found this on github. Looks like it works

> https://github.com/thareekanvar/react-native-firebase-phone-auth

**Comment by Uttu316** [comment]
How will I use react-native-firebase in my expo project?

**Comment by mikehardy** [comment]
You don't, I think. Fifth question here. https://docs.expo.io/versions/latest/introduction/faq/

For anything expo-related, use Expo support channels

**Comment by aqdas-ilyas** [comment]
actually when i build APKfor android and when I click on sign up button it did not go to browser to check captcha ... that's why it does give me OTP SMS to register user.... but when i run my project with command on terminal 'react-native run-android' with the emulator or running on device .. it runs properly and it go to browser to verified an send me a SMS code for OTP to register and user successfully register

The main problem is when i built APK for android the browser does not work or not open to verified captcha ??

whta i doooo ??

**Comment by misfityudi** [comment]
same issue as above, what do i dooooo?

**Comment by vmmoorthy** [comment]
> Hey, no it doesn't require captcha. Check out our docs that explain one of the methods:
> 
> https://rnfirebase.io/docs/v5.x.x/auth/phone-auth

link broken

**Comment by mikehardy** [comment]
@vmmoorthy right, that link is from 2019, and v5 is deprecated / unusable at this point.
Did you try simply looking for phone auth on the main documentation site?

This search also works for me with expected result right at top: https://search.brave.com/search?q=react-native-firebase+phone+auth
