### ISSUE TITLE
[📚] Documentation Issue - Enabling MultiDex in RN Firebase

### ISSUE THREAD

**Issue by workpebojot** [invertase/react-native-firebase#4650]
## Enable MultiDex in React Native Firebase

If you read the **Miscellaneous** section of RN Firebase Documentation. You may encounter **Enabling MultiDex**. However, the documentation is not clear when you modify the **MainApplication.java**. And it says:

![rnfb](https://user-images.githubusercontent.com/38276345/101226911-ef405400-36d0-11eb-9279-e10194d8f7f2.png)

When you add native libraries like **Wix React Native Navigation** (https://github.com/wix/react-native-navigation), the MainApplication.java is different:

![Annotation 2020-12-05 081135](https://user-images.githubusercontent.com/38276345/101227053-84dbe380-36d1-11eb-9313-c13a51d50a9c.png)

And you can't just modify this line like this: 

`public class MainApplication extends MultiDexApplication implements NavigationApplication {`

As it will cause an **Error**. To get around this. I instead use this:

![immpor](https://user-images.githubusercontent.com/38276345/101227155-e2703000-36d1-11eb-9a7e-a96ff05b301c.png)

Solved my problem. 🎉

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! That's an advanced case, and it is specific to other (not react-native-firebase) libraries that are already extending MainApplication. It is certainly important to document it, but it's on those libraries to do so

At the same time, react-native 0.64 is bumping the minSdkVersion to 21 which means we will finally be able to forget about MultiDex forever when it releases in a week or two

For those two reasons, I don't think this is actionable here
