### ISSUE TITLE
Unable to find a matching configuration of project :@react-native-firebase_auth:

### ISSUE THREAD

**Issue by VISMAYAHARIDAS** [invertase/react-native-firebase#4651]
[](url)
![Screenshot (210)](https://user-images.githubusercontent.com/71158635/101237049-dc8f4480-36fb-11eb-8895-c6b0f85532fc.png)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :@react-native-firebase_auth.
     Required by:
         project :app
      > Unable to find a matching configuration of project :@react-native-firebase_auth:
          - None of the consumable configurations have attributes.

**Comment by mikehardy** [comment]
No template, no help - it's really disrespectful of maintainer time to do that.
Before trying again, run this and compare it to your project, this creates a demo app that runs: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh
