### ISSUE TITLE
[🐛] 🔥 Critical notification on click issue on some manufacturers

### ISSUE THREAD

**Issue by crushy26** [invertase/react-native-firebase#4655]
## Issue

Notification click doesn't let the user enter the app when the device is idle for 10 mins or so after notification is received. The click does nothing and simply disappears.

The issue persists especially on OnePlus devices running android 9 and above.

From what I have observed from LogCat after 10 mins of closing the app:

> ActivityManager: Killing 13935:com.hog.debug/u0a570 (adj 905): empty # 31

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```{
  "name": "hog",
  "version": "0.0.3",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "android": "cd ./android && ./gradlew app:assembleDebug && ./gradlew installDebug"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.6.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.3.2",
    "@react-native-firebase/app": "^10.1.0",
    "@react-native-firebase/dynamic-links": "^10.1.1",
    "@react-native-firebase/firestore": "^10.1.1",
    "@react-native-firebase/messaging": "^10.1.1",
    "@sentry/react-native": "^1.3.7",
    "axios": "^0.19.0",
    "lodash": "^4.17.15",
    "lottie-ios": "3.0.3",
    "lottie-react-native": "3.3.2",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.26",
    "normalizr": "^3.4.1",
    "react": "16.11.0",
    "react-native": "0.62.0",
    "react-native-code-push": "^6.2.0",
    "react-native-fast-image": "8.1.5",
    "react-native-fbsdk": "^2.0.0",
    "react-native-gallery-swiper": "^1.26.4",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-mixpanel": "^1.2.3",
    "react-native-modal": "^11.5.6",
    "react-native-navigation": "^6.8.0",
    "react-native-progress": "^4.0.3",
    "react-native-render-html": "^4.2.0",
    "react-native-share": "^4.1.0",
    "react-native-simple-toast": "^1.1.3",
    "react-native-skeleton-placeholder": "^3.0.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-swiper": "^1.6.0-rc.3",
    "react-native-thumbnail-video": "^0.1.2",
    "react-native-vector-icons": "^6.6.0",
    "react-native-version-number": "^0.3.6",
    "react-native-video-cache": "^1.0.0",
    "react-native-webview": "9.0.2",
    "react-native-youtube": "^2.0.0",
    "react-redux": "^7.1.1",
    "react-string-replace": "^0.4.4",
    "redux": "^4.0.4",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.12.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [X] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.whatsonnet">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
    android:usesCleartextTraffic="true"
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
      <meta-data
      android:name="JW_LICENSE_KEY"
      android:value="FYOIwlQGb8E20TTNbn6FidtLGtclQ0lG7aNnAv9GqWHSD/9hYT+n1oiHZiJ6XGjg" />
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:windowSoftInputMode="adjustResize"
        android:exported="true"
        >
        <intent-filter>
         <action android:name="android.intent.action.MAIN" />
         <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>

        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data
              android:host="www.hog.com"
              android:pathPrefix="/posts/"
              android:scheme="https" />
               <data
              android:host="hog.com"
              android:pathPrefix="/posts/"
              android:scheme="https" />

              <data android:scheme="https" android:host="more.hog.com" />
              <data android:scheme="http" android:host="more.hog.com" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    
    </application>

</manifest>



<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  -  `10.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `messaging`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
This smells like https://dontkillmyapp.com

**Comment by crushy26** [comment]
Hi @mikehardy but shouldn't the app notification be clickable in some way if it is shown.

If notification itself is not shown that would be an acceptable case. 

There are many small to large scale apps on my device who are able to make the notification work through some means.

**Comment by mikehardy** [comment]
The site I linked is merely a way to test *if* that is what is happening. Definitely a statement about what *should* be happening and may not even be relevant, it just smells like it might be. It is such a quick test to see if has an effect, I felt like it was worth doing first as it would inform any possible solution

**Comment by crushy26** [comment]
@mikehardy Yes, I have tried disabling battery optimization earlier and notification works flawlessly thereafter. So the problem is definitely, OS killing the main activity after it finds there's no associated process running with app.

**Comment by mikehardy** [comment]
Okay, that helps inform the discussion. There may be nothing we can do, and technically this is a vendor bug based in a non standard android implementation. The Android compliance check for vendors will actually start failing vendors that do this soon, but apparently not yet. I'll keep this open in case I have time but my best advice if these are critical is to check power management status in your app and direct the user to the settings screen. Transistorsoft is an example of apis for this, as is notifee. Might be possible with device module even. Other apps work either with workarounds (sometimes, special services etc) or because vendors maintain secret allow lists with popular apps)

**Comment by crushy26** [comment]
We could consider major apps as a special case of whitelisting by manufacturers,
But It's strange that many new android apps are able to execute this flawlessly without any extra steps to be taken by the user.
One such [example](https://play.google.com/store/apps/details?id=in.ideastoday&hl=en_IN&gl=US)
