### ISSUE TITLE
[Crash] putFile will crash when extension in unknown 

### ISSUE THREAD

**Issue by Maxoos** [invertase/react-native-firebase#4661]
I'm running xcode12 on Apple Silicon and it seems that pathExtension which used to return the extensions of the file in path is returning nil on iOS14 simulators (for gif files - does not happen on iOS13). This is probably a simulator issue, however, this code does not check if UTI is null and therefor crashes when trying to release:

`CFRelease(UTI);`

https://github.com/invertase/react-native-firebase/blob/b5357573e97ccc3bfdf6a190713a7df66e462c4b/packages/storage/ios/RNFBStorage/RNFBStorageCommon.m#L62-L66

It should be something like: 

`if (UTI) {
CFRelease(UTI);
}`

Return value can be null according to the [documentation](https://developer.apple.com/documentation/coreservices/1448939-uttypecreatepreferredidentifierf):
> Return Value
> A new CFStringRef containing a uniform type identifier, or NULL if inTagClass is not a known tag class

**Comment by mikehardy** [comment]
Oh my! Good catch @Maxoos - if you could work up a PR for this (for small patches I start by just modifying the file directly in node_modules then doing a patch-package for it) so you know it is tested and working and fixes your failure case, I'd happily merge it

**Comment by fongabc** [comment]
I have the same issue on Apple Silicon

**Comment by fongabc** [comment]
> I have the same issue on Apple Silicon

I found out that the issue occurs on simulator but not in the physical device.

**Comment by mikehardy** [comment]
I would still love to fix this for the simulator if someone worked up a PR for it and submitted it here. I don't have Apple Silicon so I cannot test it to verify if it's working, I will need someone from the community to propose it and verify it works for them

**Comment by Maxoos** [comment]
@mikehardy I've created a PR, however I'm pretty sure you can test this on an Intel based Mac but trying a file with no extension. Thanks!
