### ISSUE TITLE
Firestore - dependency were found, but they required a higher minimum deployment target

### ISSUE THREAD

**Issue by Frexuz** [invertase/react-native-firebase#467]
### Issue

```
pod install
Analyzing dependencies
Fetching podspec for `RNFirebase` from `../node_modules/react-native-firebase`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `Yoga` from `../node_modules/react-native/ReactCommon/yoga`
[!] Unable to satisfy the following requirements:

- `Firebase/Firestore` required by `Podfile`

Specs satisfying the `Firebase/Firestore` dependency were found, but they required a higher minimum deployment target.
```

Podfile
```
platform :ios, '9.0'

target 'flatelyNative' do
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  pod 'Firebase/Firestore'

  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core'
  ]
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```
I've tried 8.0, 9.0, 10.0 etc.. as well as matching the target platform in Xcode's *'Deployment target'*

### Environment

1. Application Target Platform: 
iOS

2. Development Operating System: 
macOS Sierra

3. Build Tools: 
Xcode 8.3.1

4. React Native version: 
0.45.1

5. RNFirebase Version: 
3.0.0

6. Firebase Module: 
Firebase/Firestore

**Comment by Frexuz** [comment]
Upgrading to RN 0.49.1 gives me
```
pod install
Analyzing dependencies
Fetching podspec for `RNFirebase` from `../node_modules/react-native-firebase`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `Yoga` from `../node_modules/react-native/ReactCommon/yoga`
[!] The name of the given podspec `yoga` doesn't match the expected one `Yoga`
```

just testing removing "yoga" and "react", still gives me

```
Fetching podspec for `RNFirebase` from `../node_modules/react-native-firebase`
[!] Unable to satisfy the following requirements:

- `Firebase/Firestore` required by `Podfile`

Specs satisfying the `Firebase/Firestore` dependency were found, but they required a higher minimum deployment target.
```

**Comment by devboy** [comment]
My Podfile looks like this:

```
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native'

  # Pods for Grasshopper
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  pod 'Firebase/Firestore'
```

and after a `pod update` it all worked fine

**Comment by Frexuz** [comment]
that kinda worked (with capital Y in pod 'yoga'), but now installing the BoringSSL dependency fails:

```
Analyzing dependencies
Fetching podspec for `RNFirebase` from `../node_modules/react-native-firebase`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `Yoga` from `../node_modules/react-native/ReactCommon/yoga`
Downloading dependencies
Installing BoringSSL (9.0)
[!] /bin/bash -c
set -e
# Replace "const BIGNUM *I" in rsa.h with a lowercase i, as the former fails when including
# OpenSSL in a Swift bridging header (complex.h defines "I", and it's as if the compiler
# included it in every bridged header).
....
etc
```

I'm not sure if this is a RN-firebase issue? But can't find a solution on Google..

**Comment by chrisbianca** [comment]
I have good news for you, as of last today's v3.0.2 release, `react-native link` is supported for iOS and Android so you no longer need to set up React, Yoga, `react-native-firebase`, etc as Pods.  You do still need to have Firebase installed using pods as recommended by Google.

Check out the new installation instructions:

iOS: http://invertase.link/ios
Android: http://invertase.link/android

I'm not sure this will necessarily fix the BoringSSL issue, but it should simplify some of the other issues that you've had

**Comment by stocksp** [comment]
After following the latest steps here (thanks @devboy for the 'pods update')
I get this message and again for the 'release' target

```
[!] The \`ACCBT [Debug]\` target overrides the \`FRAMEWORK_SEARCH_PATHS\` build setting 

defined in 'Pods/Target Support Files/Pods-ACCBT/Pods-ACCBT.debug.xcconfig'. This can lead 

to problems with the CocoaPods installation

    - Use the \`$(inherited)\` flag, or

    - Remove the build settings from the target.
```

my FRAMEWORK_SEARCH_PATHS looks like

```
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/FirebaseAnalytics/Frameworks" 

"${PODS_ROOT}/FirebaseAuth/Frameworks" "${PODS_ROOT}/FirebaseCore/Frameworks" 

"${PODS_ROOT}/FirebaseFirestore/Frameworks" 

"${PODS_ROOT}/FirebaseInstanceID/Frameworks"
```

Could someone please translate this message for me (what am I suppose to do?)  It looks to me like the setting has the `$(inherited)` flag.

**Comment by Frexuz** [comment]
Still doesn't fix BoringSSL. Which part uses that as dependency? Firebase Core?

```
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'flatelyNative' do
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
end
```

**Comment by chrisbianca** [comment]
Try bumping your minimum platform to 9.0 and see if that makes any difference?

**Comment by Salakar** [comment]
Just an FYI: further discussion on this issue was had on [discord](https://discord.gg/772CjpK), see the pinned message from @frexuz in the `react-native-firebase` channel for the start of the conversation. Still no resolution, have asked for assistance on the official Cloud Firestore google group

**Comment by Frexuz** [comment]
- Skipping BoringSSL problem for now, copying the Pods folder from a different computer where it worked.

Final Podfile that seems to work.

```
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'flatelyNative' do
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  pod 'Firebase/Core'
  pod 'RNFirebase', path: '../node_modules/react-native-firebase'
  pod 'Firebase/Firestore'
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'BatchedBridge',
    'Core',
    'ART'
  ]
end
```

I think we can close this issue, since my error is now something else (Related to build failing looking for FirebaseAnalytics, what @Salakar said)

**Comment by Salakar** [comment]
Ok will close this issue @Frexuz. If you get a response back from the google group or figure out the BoringSSL problem can you drop a message here or on discord, so we know what the resolution is for future reference.

Happy coding! :)

**Comment by bjornbjorn** [comment]
Hi guys, just wanted to chip in here cause I think I know what @Frexuz issue is.

I had that same error when trying to install BoringSSL with Cocoapods (```sed: -e expression #1, char 1: unknown command: `.'```) and found out that it was a non-standard version of ```sed``` which caused it.

If you're on OSX you should use ```/usr/bin/sed```. If you do a ```which sed``` you'll probably see that you have installed another version with brew, like I had:

```which sed
/usr/local/opt/gnu-sed/libexec/gnubin/sed
sed --version
sed (GNU sed) 4.4
````
I did a ```brew unlink gnu-sed``` (note 'gnu-sed' not 'sed') and then I also had to remove it from my $PATH .. so that when doing ```which sed``` it shows ```/usr/bin/sed```

Not sure if this is the solution to your problem but wanted to throw it in here in case anyone else is googling this error and randomly ending up here :-)

**Comment by Frexuz** [comment]
```
which sed
/usr/bin/sed
```

already correct :/

**Comment by Frexuz** [comment]
Finally found it! You could possibly add this to your requirements or something:

which sed
/usr/local/bin/sed
➜  starteam.com git:(iss39-employee-onboarding) ✗ brew unlink gnu-sed
Unlinking /usr/local/Cellar/gnu-sed/4.4... 3 symlinks removed
➜  starteam.com git:(iss39-employee-onboarding) ✗ which sed
/usr/bin/sed

Somehow I had an uncompatiable version of sed, someone found it here:
https://github.com/invertase/react-native-firebase/issues/467#issuecomment-336421708 <https://github.com/invertase/react-native-firebase/issues/467#issuecomment-336421708>

:D

**Comment by Frexuz** [comment]
Sorry, sent it to the wrong email :D

But thanks!!

**Comment by jamesTheKid** [comment]
I did this in order :
Remove `pod 'Firebase/Firestore'` from your Podfile, then 
```
pod repo update 
pod update 
```
Then I add `pod 'Firebase/Firestore'` to my Podfile and finally perform `pod install`

**Comment by Frexuz** [comment]
I decided to try creating a completely new react-native app (react-native init).

Suddenly, no issues at all. Copied over my app/navigation/screens/components, and voila :D

Still no idea what's causing this issues, but I think we can close this one..

**Comment by NordlingArt** [comment]
Only a `pod update` worked for me!

**Comment by ph0ph0** [comment]
I managed to do it by deleting all pods from the pod file, running pod install, (0 dependencies), then only adding 'Firebase/Firestore' to the pod file, running pod install, then opening the pod file and adding all the other pods.

**Comment by mertkahraman42** [comment]
Try only using `pod update`

**Comment by hcivelek** [comment]
Remove the lines from Podfile, then pod install, then add the lines again, then pod install.. it works for me too. Thanks

**Comment by erayaras** [comment]
Check the first line of `Podfile` if meets your need e.g. `platform :ios, '13.0'`
