### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException

### ISSUE THREAD

**Issue by Maharshi01** [invertase/react-native-firebase#4680]
Hello..

Recently, I upgraded firebase from v5.5.6 to v8. I saw these crashes being reported in firebase crashlytics for iOS devices only, earlier these crashes didn't occur. Can someone please help as why is this happening?

P.S: Majority of the crashes are happening for iOS 10 version only and devices like iPhone 5, 5c..

Fatal Exception: NSInternalInconsistencyException
An instance 0x180b7990 of class __NSCFLocalDataTask was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x180bd8a0> ( <NSKeyValueObservance 0x180bd020: Observer: 0x180bcab0, Key path: state, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x16e9daf0> )
0  CoreFoundation                 0x1bb3bb3d __exceptionPreprocess
1  libobjc.A.dylib                0x1adc3067 objc_exception_throw
2  CoreFoundation                 0x1bb3ba85 -[NSException initWithCoder:]
3  Foundation                     0x1c3fa729 (Missing)
4  libobjc.A.dylib                0x1addd259 objc_object::sidetable_release(bool)
5  libsystem_blocks.dylib         0x1b253bb9 _Block_release
6  libdispatch.dylib              0x1b209783 _dispatch_client_callout
7  libdispatch.dylib              0x1b20dd05 _dispatch_main_queue_callback_4CF
8  CoreFoundation                 0x1baf7d69 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
9  CoreFoundation                 0x1baf5e19 __CFRunLoopRun
10 CoreFoundation                 0x1ba491af CFRunLoopRunSpecific
11 CoreFoundation                 0x1ba48fd1 CFRunLoopRunInMode
12 GraphicsServices               0x1d1f3b41 GSEventRunModal
13 UIKit                          0x20dd1a53 UIApplicationMain
14 MyUMobile                      0x91389 main + 22 (main.m:22)
15 libdyld.dylib                  0x1b2364eb (Missing)

**Comment by andersonaddo** [comment]
Follow the template if you want to receive help. 

They only thing I can recommend:
Try an isolate the problem with a template React Native Firebase app. This bash script is particularly helpful in making an empty template app.
https://github.com/mikehardy/rnfbdemo

See how this app differs from yours in the native code.

**Comment by mikehardy** [comment]
Also, v8 is already old (apologies - a couple major bumps happened as we went to "one single version" between modules), you will want v10.2.0
