### ISSUE TITLE
[🐛] Not receiving notifications on iOS

### ISSUE THREAD

**Issue by rahulje9** [invertase/react-native-firebase#4681]
## Issue

I'm not receiving push notifications on iOS device. I tried both the google cloud message console and the rest API path, android is working fine, but in the case of iOS I'm not at all getting anything.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "react": "16.9.0",
    "react-native": "0.61.5",
```

#### `firebase.json` for react-native-firebase v6:

```json
    "@react-native-firebase/app": "^8.4.3",
    "@react-native-firebase/messaging": "^7.8.6",
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
    OS: macOS 10.15.4
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 2.83 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

I'm checking for permission and everything.

```
  checkPermission = async () => {
    const authStatus = await messaging().requestPermission();
    const enabled =
      authStatus === messaging.AuthorizationStatus.AUTHORIZED ||
      authStatus === messaging.AuthorizationStatus.PROVISIONAL;

    if (enabled) {
      this.getToken();
    }
  };

  getToken = async () => {
    await messaging()
      .getToken()
      .then(async (token) => {
        console.log('token', token);
        await AsyncStorage.setItem('fcmToken', token);
      });
  };
```

I'm not sure what I'm missing at this point, I have gone through the issues and tried the suggested fixes and none worked for me.

On receving notification I'm fetching some API's
```
    messaging().onMessage(async (remoteMessage) => {
      this.displayNotification();
      // Alert.alert('A new FCM message arrived!', JSON.stringify(remoteMessage));
    });
```

I had some issues with the project as something was missing,
turns out I had to apply a patch to run the project. the patch code is as follows.
```
diff --git a/node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m b/node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m
index 01aa75f..572572c 100644
--- a/node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m
+++ b/node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m
@@ -266,6 +266,9 @@ - (void)displayDidRefresh:(CADisplayLink *)displayLink
 
 - (void)displayLayer:(CALayer *)layer
 {
+  if (!_currentFrame) {
+    _currentFrame = self.image;
+  }
   if (_currentFrame) {
     layer.contentsScale = self.animatedImageScale;
     layer.contents = (__bridge id)_currentFrame.CGImage;
diff --git a/node_modules/react-native/scripts/.packager.env b/node_modules/react-native/scripts/.packager.env
new file mode 100644
index 0000000..361f5fb
--- /dev/null
+++ b/node_modules/react-native/scripts/.packager.env
@@ -0,0 +1 @@
+export RCT_METRO_PORT=8081

```

is this patch the culprit or something else is messing up my setup?

**Comment by mikehardy** [comment]
The module works, you have implemented the module integration or the push message incorrectly. The issues list is littered with issues similar to this one

You have ignored the issue template, so I will close this after this comment.

You should make sure you have up to date versions (we are on v10.2.0 here now)
You should make sure you follow the implementation instructions in the messaging section
You should reproduce with a clean demo https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh if you continue to have problems, prior to reporting
You should follow the issue template completely when reporting issues in order to receive real help

**Comment by rahulje9** [comment]
> The module works, you have implemented the module integration or the push message incorrectly. The issues list is littered with issues similar to this one
> 
> You have ignored the issue template, so I will close this after this comment.
> 
> You should make sure you have up to date versions (we are on v10.2.0 here now)
> You should make sure you follow the implementation instructions in the messaging section
> You should reproduce with a clean demo https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh if you continue to have problems, prior to reporting
> You should follow the issue template completely when reporting issues in order to receive real help

@mikehardy sorry for the missing parts, I have updated the missing part, if anything else is needed please let me know.
I know the module works since I have the exact same setup in my another project and I have replicated that to this one, so technically it should work. the difference being that and this is the react native version.

```
You should make sure you have up to date versions (we are on v10.2.0 here now)
```
I was on the latest and it was not working for me, so I downgraded that to the other version I have setup in the different project. any leads on this will be appreciated as I have been looking at this for days.

**Comment by mikehardy** [comment]
There is nothing in the new version that would cause this failure. It is a project specific issue, sorry
