### ISSUE TITLE
[🐛] Bug onTokenRefresh android not work

### ISSUE THREAD

**Issue by maystrenkoYurii** [invertase/react-native-firebase#4683]
I simulated onTokenRefresh
<img width="277" alt="Снимок экрана 2020-12-17 в 12 37 58" src="https://user-images.githubusercontent.com/23016311/102477234-c3c05080-4064-11eb-87a8-497c9b58125a.png">
<img width="512" alt="Снимок экрана 2020-12-17 в 12 38 06" src="https://user-images.githubusercontent.com/23016311/102477236-c4f17d80-4064-11eb-9a47-d81702758f02.png">

its perfect work on ios but not work on android

"@react-native-firebase/app": "10.2.0",
 "@react-native-firebase/iid": "^10.2.0",
 "@react-native-firebase/messaging": "10.2.0",

**Comment by mikehardy** [comment]
Failed to follow template.
