### ISSUE TITLE
[🐛] RTDB Android disconnecting even if attaching a dummy listener

### ISSUE THREAD

**Issue by SrBrahma** [invertase/react-native-firebase#4693]
## Issue
🔥

[ACTUALLY, READ THE COMMENT BELOW!! Leaving it here so it can help other people that may fall into the same problem]

First of all, I am aware of the

`on Android, the Realtime Database disconnects from the backend after 60 seconds of inactivity. Inactivity means no open listeners or pending operations. To keep the connection open, we recommended you add a value event listener to a path besides .info/connected. For example you could do FirebaseDatabase.getInstance().getReference((new Date()).toString()).keepSynced()` (https://firebase.google.com/docs/firestore/solutions/presence#limitations)

and I have tried this workaround (with the date non existing ref or with an existing dummy one). So, I am not sure what is happening here, if it's this package bug or the firebase-tools package (emulator) bug.

If I start my app not logged and do nothing, after ~1min the .info/connected will trigger with false. However, if I start it and do the Google login, it will stay connected.

---

**Comment by SrBrahma** [comment]
I tested better (deploying instead of Emulator and removing listeners that would be applied onAuth) and it would happen anyway.

I found out a funny thing: This doc is misleading. The ref I was listening to didn't have a read permission for anyone in Rules.

I basically in rules added 
`"keepAlive": { ".read": true }`
and I listen in my client to a timestamp child of this ref. (probably distributing the clients over multiple refs have better performance to the RTDB than all Android clients listening to a single ref)

Now it is working like a charm :)

**Comment by mikehardy** [comment]
@SrBrahma fascinating! If I understand correctly - and I am saying this to check that is the case / please correct me if wrong - this was an interaction between the rules on the realtime database and the listener? Such that if the rules do not permit reading then the listener does not work?

That sounds like expected behavior but if the documents can be improved in the area, there is an edit button on the top right of every documentation and API reference page, we do welcome documentation changes.

Thanks for following up and describing this either way, it does seem subtle

**Comment by SrBrahma** [comment]
> @SrBrahma fascinating! If I understand correctly - and I am saying this to check that is the case / please correct me if wrong - this was an interaction between the rules on the realtime database and the listener? Such that if the rules do not permit reading then the listener does not work?
> 
> That sounds like expected behavior but if the documents can be improved in the area, there is an edit button on the top right of every documentation and API reference page, we do welcome documentation changes.
> 
> Thanks for following up and describing this either way, it does seem subtle

I ain't sure about the conditional / relation directly causing this. Maybe if the read check fails, the listener is killed. Maybe it stays alive, but the Android 60s requires a listener that has a non-error listener on last callback. I haven't tested it specifically but is indeed a curious behavior. I am in a real rush right now to finish my app I won't go deeper into this at the current time.

It is indeed "expected"/logical when thinking about listening to something that the user don't have access. But this workaround should mention this.

The doc I mentioned and linked is Firebase official docs, not this package one. On the official there is only a send feedback button that I may send this issue link then. I don't remember of seeing about this in this package docs (actually maybe I first saw it there, because I don't visit firestore docs).

**Comment by SrBrahma** [comment]
**Maybe if the read check fails, the listener is killed.**
This. While I was doing the auth check of #4606, I've found out that if you try to read some data without permission, the error is thrown just once, even if you update the data you are "listening" to.
