### ISSUE TITLE
[🐛] sendPasswordResetEmail generic error 🔥 [SOLVED]

### ISSUE THREAD

**Issue by hmazer** [invertase/react-native-firebase#4694]
## Issue

I've been using firebase login for a long time now, however, the `sendPasswordResetEmail` have never worked.
If I call `auth().sendPasswordResetEmail(email)`, **I get a success from the Promise, but the email never arrives**.
I tried adding a second param:
`auth().sendPasswordResetEmail(email, {
            iOS: {
                bundleId: 'myapp.com'
            },
            android: {
                packageName: 'myapp.com'
            })` (yes, the bundle is correct in my code)
 This also resolves the promise, but no email ever arrives (it's a Gmail account, and there's nothing on spam folder as well. Different email providers have been tried).
I then tried adding one last param:
`url: 'https://myapp.com'`
This time the promise fails with a generic error: 
`auth/internal-error [auth/internal-error] An internal error has occurred, please try again`
(yes, the domain is authorized on my firebase project. I've also identified that there is a specific error for non authorized domains anyway)

## SOLUTION

It turns out that I had an SMPT settings on my firebase console to use my custom email account to send password reset emails. Even though there was something wrong with it, the promise would resolve. I'm not sure wether the API has an error for invalid/failed SMPT credentials that could be implemented by this library.
Also, the firebase dashboard itself doesn't show any errors about this matter, even though the email I configured is a GSuite account. (I know this is an open source project and you don't have control over the Firebase dashboard. Just mentioning).

Thanks.

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/analytics": "^10.2.0",
    "@react-native-firebase/app": "^10.2.0",
    "@react-native-firebase/auth": "^10.2.0",
    "@react-native-firebase/messaging": "^10.2.0",
```

#### `firebase.json` for react-native-firebase v6:

I don't think this is necessary since all other login and analytics features work.

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

#### Have you converted to AndroidX?

- [X] my application is an AndroidX application?
- [X] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

## Environment

**`react-native info` output:**
```
react: 16.13.1 => 16.13.1 
react-native: 0.63.2 => 0.63.2 
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [X] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `10.2`
- **`Firebase` module(s) you're using that has the issue:**
  - `auth`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

**Comment by mikehardy** [comment]
Hmmm - I have to admit I haven't ever tried this in my app. I can't promise when it will happen but I'll try to give it a try

**Comment by mikehardy** [comment]
Is this ios or android specific? Also I do not think it will matter for this bug but v10.3.1 is current and it does pull in fresh underlying native firebase SDKs.

**Comment by hmazer** [comment]
> Is this ios or android specific? Also I do not think it will matter for this bug but v10.3.1 is current and it does pull in fresh underlying native firebase SDKs.

Hi mike, thanks for your help. I've just updated the topic with the solution. As it turns out, it had nothing to do with de library itself, even though there **might** be a way of adding error handling for this type of situation.

**Comment by mikehardy** [comment]
Oh that is subtle! If you want to add a note on the API call mentioning that silent failure is possible if SMTP credentials are invalid, that might help future people - there's an edit button on top right of every docs and API reference page and we merge PRs quickly.

Glad your project is moving forward! Cheers
