### ISSUE TITLE
[🐛] Crashes occuring because of less RAM 

### ISSUE THREAD

**Issue by Maharshi01** [invertase/react-native-firebase#4695]
Hello...

Recently, i upgraded firebase version from v5.5.6 to v8.4.5. Earlier firebase used to not record crashes which are not related to low RAM, however now i can see in my firebase dashboard many of the crashes that are being captured because of low RAM. Can someone please help how to stop crashes in iOS devices having less RAM. I have attached screenshots for some of the crash issues....

P.S : Crash Insight is pointing that it's related to heap memory corruption.

![Screenshot 2020-12-21 at 6 36 55 PM](https://user-images.githubusercontent.com/48430425/102782313-28f6a780-43bf-11eb-93d3-48a82e8d935b.png)

![Screenshot 2020-12-21 at 7 01 16 PM](https://user-images.githubusercontent.com/48430425/102782351-39a71d80-43bf-11eb-9bf6-ebd798e53df2.png)

![Screenshot 2020-12-21 at 7 01 37 PM](https://user-images.githubusercontent.com/48430425/102782361-3ca20e00-43bf-11eb-94df-eeae98a33938.png)

![Screenshot 2020-12-21 at 7 01 56 PM](https://user-images.githubusercontent.com/48430425/102782362-3dd33b00-43bf-11eb-9ef3-62a4d03258f6.png)

**Comment by mikehardy** [comment]
Hi there! v10.3.1 is current, no support will be offered for v8. This may fix the heap corruption issues as well as it will pull in updated native firebase SDKs (assuming you do not have them overridden, if you do then you will need to update manually)

Low memory crashes are going to be project specific. They will not be the fault of this module. You will have to become comfortable with Xcode profiling tools and see what in your project is consuming RAM.

If you can still reproduce with an App.js that you drop in a clean project from https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh and you post a stack trace along with actually following the issue template we can work on this, but in the meantime I will assume 1) old SDKs could be crashing, 2) RAM consumption in your app is problematic
