### ISSUE TITLE
verifyPhoneNumber don't work this._auth.emitter.once is not a function

### ISSUE THREAD

**Issue by iddar** [invertase/react-native-firebase#4696]
I try run `auth().verifyPhoneNumber(phoneNumber)` like documentation examples (`use on and then syntax`) and show this message in a console. Same result in rnFirabse 10.3.0 and 10.2.0. 

All other Auth methods work fine in js engine and Hermes 

```
TypeError: this._auth.emitter.once is not a function.
(In 'this._auth.emitter.once(this._internalEvents[type], this["_" + type + "Handler"].bind(this))',
'this._auth.emitter.once' is undefined)
```

### my code

```jsx
async function signInWithPhoneNumber(phoneNumber) {
    const confirmationw = auth()
      .verifyPhoneNumber(phoneNumber)
      .on('state_changed', (phoneAuthSnapshot) => {
        console.log(phoneAuthSnapshot)
      })
    console.log(confirmationw)
}
```
### Env

```
iOS 14
Mac OS Big Sur
React-Native 0.64.0-rc.1
React 17.0.1
react-native-firebase/app 10.3.0
react-native-firebase/auth 10.3.1
react-native-firebase/firestore 10.3.1
```

**Comment by Esxiel** [comment]
Very sorry to kind of be slightly off-topic but, is it maybe related to the problem where RNFirebase doesn't support Hermes as per https://rnfirebase.io/#hermes-support ?

**Comment by shaurya2612** [comment]
I am facing the same problem on my android physical device.

Any updates?

**Comment by mikehardy** [comment]
Ah! This was solved. It was a forward port needed for react-native 0.64. I did that and released it: #5042 - you need v11.1.2 or higher of react-native firebase

**Comment by SornchaiTheDev** [comment]
I updated react-native to 0.64 and react-native-firebase to v11.2.0 but I has the same problem did I do it correct way ? 
It return 
Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not a function
TypeError: undefined is not a function

Code :
const getOTP = async () => {
 const confirmation = await auth()
        .verifyPhoneNumber("phone num here")
        .then((confirm) =>  console.log(confirm))
        .catch((err) => console.log(err.code));
}

**Comment by mikehardy** [comment]
If you have v11.2.0 then things should work, my guess is there is some level of caching happening meaning that you have the updated dependency version but that's not the actual code running. `npx react-native-clean-project` is my typical prescription for that
