### ISSUE TITLE
All firebase module's dependencies to be added mandatory

### ISSUE THREAD

**Issue by GarimaMathur07** [invertase/react-native-firebase#470]
I want to add only firebase analytics and cloud messaging module in app and want to use only these dependencies: 
```
compile "com.google.firebase:firebase-core:11.4.2"
compile "com.google.firebase:firebase-messaging:11.4.2"
```
But at compile time it gives the errors for all remaining dependencies
```
Error:Failed to resolve: com.google.firebase:firebase-database:11.4.2
Error:Failed to resolve: com.google.firebase:firebase-ads:11.4.2
Error:Failed to resolve: com.google.firebase:firebase-firestore:11.4.2
Error:Failed to resolve: com.google.firebase:firebase-crash:11.4.2
Error:Failed to resolve: com.google.firebase:firebase-config:11.4.2
```

So, how can i avoid remaining dependencies to be added in build.gradle file.

**Comment by Salakar** [comment]
Please fill out the issue template, we can't help without it 🙈  For example it asks for your `build.gradle` files - which we need in this instance to help you debug your issue.

**Comment by DavidKuennen** [comment]
Did you add react-native-firebase with the option `transitive = false` in your build.gradle?

```
compile(project(':react-native-firebase')) {
    transitive = false
}
```

Without that, it will add all the dependencies within react-native-firebase, which is everything.

**Comment by GarimaMathur07** [comment]
Thanks for the support @DavidKuennen It solved the issue completely 👍
