### ISSUE TITLE
RNfirebase phone auth not working with release apk

### ISSUE THREAD

**Issue by AdlakhaAnkit** [invertase/react-native-firebase#4709]
## Issue

I have implemented phone based authentication using rnfirebase. When I am testing it on emulator, it is working fine with testing phone numbers. But when I am creating the release apk and installing that apk on my phone then some times it sends OTP and works fine. but some times it is not working, not sending any OTP. I have used library @react-native-firebase/app (10.3.0) and @react-native-firebase/auth (10.3.1) because for @react-native-firebase/app (10.3.1) I am getting error as:

```
npm ERR! code ETARGET
npm ERR! notarget **No matching version found for @react-native-firebase/app@^10.3.1**
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

my code changes to send OTP:
```

newSignIn = async () => {
    let phoneNumber = this.state.phone;
    if (this.validatePhoneNumber(phoneNumber)) {
      try {
        const confirmation = await auth().signInWithPhoneNumber(phoneNumber);
        ToastAndroid.show(JSON.stringify(confirmation), ToastAndroid.SHORT);
        this.setState({ confirm: confirmation });
      } catch (error) {
        Alert.alert("Sorry!", "Error occurred. Check phone number.");
      }
    } else {
      Alert.alert(
        "Sorry!",
        "Invalid Phone Number, make sure to add + country code."
      );
    }
  }
```
I have already placed my SHA key in firebase console and phone based authentication is enabled.

After debugging and placing console, what I have observed is that it is getting stuck at line:

`    const confirmation = await auth().signInWithPhoneNumber(phoneNumber);`

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
"react-native": "^0.63.4",
"@react-native-firebase/app": "^10.3.0",
"@react-native-firebase/auth": "^10.3.1",

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Wow, after discussion on #4707 you are persistent! You persistently ignored nearly all the template. You realize as a maintainer this is a clear statement of disregard for my advice. That's always your choice, but to me the message is clear anyway, that you are not serious about resolving your issue.

My best advice is to continue with placement of console inside node_modules/@react-native-firebase/auth in order to trace the execution through, and further to continue doing same inside the Java API calls we make to the underlying firebase-android-sdk in order to see exactly where it is waiting and why based on arguments sent vs expected arguments.

Finally, realize that some carriers simply do not send OTPs. The cell carrier literally just does not send them. You can't rely on OTPs in practice - they are quite useful and may be used as a primary method but not as the only method.

I spoke with you on 4707 about following the issue template, and the consequence if you don't - I can't really provide help so I close issues. I believe by tracing execution you will find an answer though

**Comment by mikehardy** [comment]
one other possible thought - reproduce with a clean app or quickstart from the underlying SDK

https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh
https://github.com/firebase/quickstart-android/tree/master/auth

**Comment by AdlakhaAnkit** [comment]
@mikehardy  
Sorry about if still some things are missing as per template. This time I tried to add the details in the template instead of removing that.  Can you please point me out like in template what exactly I have missed ? So that same thing I will not repeat again.

I have tried with clean app as well.

**Comment by mikehardy** [comment]
Please report the result of the rest of my suggestions

Quickstart
Internal tracing

The template just is what it is. It's all there, skip sections at your peril 🤷

I would focus on tracing personally then the Quickstart

**Comment by AdlakhaAnkit** [comment]
@mikehardy  
Can you please reopen this? I have updated other details as well. 
I will try that console tracing suggestion.

**Comment by mikehardy** [comment]
> Please report the result of the rest of my suggestions

Then perhaps. The module works for others, my assumption is you have a local project problem, so it is not really an issue with the module

**Comment by AdlakhaAnkit** [comment]
@mikehardy 

I have tried putting logging to capture the execution flow:

Original code in index.js in node_module: react_native_firebase/auth:

```
signInWithPhoneNumber(phoneNumber, forceResend) {
    if (isAndroid) {
      return this.native
        .signInWithPhoneNumber(phoneNumber, forceResend || false)
        .then(result => new ConfirmationResult(this, result.verificationId));
    }

    return this.native
      .signInWithPhoneNumber(phoneNumber)
      .then(result => new ConfirmationResult(this, result.verificationId));
  }
```

I Updated the original code to:

```
signInWithPhoneNumber(phoneNumber, forceResend) {
    if (isAndroid) {
      **ToastAndroid.show(phoneNumber, ToastAndroid.SHORT);**
      return this.native
        .signInWithPhoneNumber(phoneNumber, forceResend || false)
        .then(result => 
          {    
            ToastAndroid.show(JSON.stringify(this), ToastAndroid.SHORT);
            ToastAndroid.show("testing", ToastAndroid.SHORT);
            return new ConfirmationResult(this, result.verificationId)
          }).catch(error =>{
            ToastAndroid.show(JSON.stringify(error), ToastAndroid.SHORT);
          });
    }
```

And then tried to run the app after creating the release apk and observed that phone number toast is coming but then after that nothing is coming.

**Comment by mikehardy** [comment]
> My best advice is to continue with placement of console inside node_modules/@react-native-firebase/auth in order to trace the execution through, **and further to continue doing same inside the Java API calls we make to the underlying firebase-android-sdk in order to see exactly where it is waiting and why based on arguments sent vs expected arguments.**
