### ISSUE TITLE
'FirebaseInstanceID/FIRInstanceID.h' file not found from 3.0.0-alpha.5 to 3.0.0

### ISSUE THREAD

**Issue by brianhiss** [invertase/react-native-firebase#471]
### Issue

Hey guys, wondering if anyone else is seeing the same issue as I am. I've been playing with this the last two days are narrowed it down to this [commit.](https://github.com/invertase/react-native-firebase/commit/a1534c23b84ad1b624aad2c05daa16ca97cb3ef4)

It's in: `ios/RNFirebase/messaging/RNFirebaseMessaging.m` adding `#import <FirebaseInstanceID/FIRInstanceID.h>`. It was added for this [PR.](https://github.com/invertase/react-native-firebase/pull/443)

When I upgraded from `react-native-firebase@3.0.0-alpha.5` to `react-native-firebase 3.0.0`, I couldn't compile. I checked Header Search Paths, made sure the FirebaseInstanceID.framework is as expected. I cannot seem to get it to compile with this commit. 

If I comment out the `#import <FirebaseInstanceID/FIRInstanceID.h>`, I can get `react-native-firebase 3.0.0` to compile and run great. Otherwise, I can downgrade back to `react-native-firebase@3.0.0-alpha.5` and it compiles again.

FIRInstanceID.h looks like a Swift file. Does this mean it requires `# use_frameworks!` uncommented in the `Podfile`?

Anyone else experiencing this? Appreciate any insight.

![screen shot 2017-10-06 at 4 42 28 pm](https://user-images.githubusercontent.com/1640257/31280626-9b09bf20-aab5-11e7-9f09-c0626082d8cc.png)

### Environment

1. Application Target Platform: iOS 11
2. Development Operating System: macOS Sierra 10.12.6 (16G29)
3. Build Tools: Xcode 9.0
4. React Native version: 0.49.1
5. RNFirebase Version: 3.0.0
6. Firebase Module: Messaging (deleteInstanceId)

**Comment by SteffeyDev** [comment]
I found you can fix this by going to your project in the left hand side (not Pods), -> Libraries -> Codepush.xcproj -> Build Settings (I think) -> Framework Search Paths -> Add FIRInstanceID (seemed to be missing there but you can add in the same format as the other ones).  I was wondering why this didn’t work as well but it’s hit or miss for me.

**Comment by brianhiss** [comment]
@SteffeyDev Thank you for the quick response. I'm not using `Codepush.xcproj`, don't think that's a requirement for `react-native-firebase`.

My Framework Search Paths already include the reference to FirebaseInstanceID.

![screen shot 2017-10-06 at 5 25 40 pm](https://user-images.githubusercontent.com/1640257/31282559-a090eae4-aabb-11e7-81a6-703f99844efa.png)

**Comment by SteffeyDev** [comment]
Oh sorry I put the wrong library name (I had issues with both), but you’re right, you do have it where it’s supposed to be.  It’s odd because I had the expect same issue but I guess your problem lies elsewhere. Maybe check you header search paths?

**Comment by brianhiss** [comment]
@SteffeyDev I added my Header Search Paths, was playing in there as well. Attaching in case there is anything abnormal.

This was a brand new project today, `react-native init MyProject`, so it's a fresh `0.49.1`, fresh `node_modules` and `pod install`, so wouldn't think there would be legacy conflicts.

I did set `FirebaseInstanceID` in the Framework Search Paths to `recursive` and that will let me build it.

Is anyone else seeing this on a new project, or old one?

![screen shot 2017-10-06 at 5 46 50 pm](https://user-images.githubusercontent.com/1640257/31283616-c72bfc18-aabe-11e7-97eb-3fc27e342c7d.png)

**Comment by chrisbianca** [comment]
I think this may be an issue our end.  I've just pushed a possible commit to ensure that FIRInstanceID is included in the library's framework search paths.

Could one of you try installing the latest version of the repo by running:

`npm install --save https://github.com/invertase/react-native-firebase.git'

And let me know if that resolves the issue?

**Comment by brianhiss** [comment]
@chrisbianca That seems to have worked for me. 

I did a `Clean Build Folder`, `yarn add https://github.com/invertase/react-native-firebase.git` and `pod update` to make sure nothing was cached.

Thanks for jumping on that!

**Comment by chrisbianca** [comment]
No problem - we'll get it included in a release very soon.  Just trying to get a few more bits in first...

**Comment by bramski** [comment]
Trying to use RNFirebase 3.3.1 I see this issue... any fix?

**Comment by farhanmannan** [comment]
I'm seeing this in react-native-firebase 5.0.0

**Comment by cmcaboy** [comment]
I am aslo getting this issue with version 4.2.0

**Comment by krimani** [comment]
$ pod update FirebaseInstanceID
just updating particular pod solved my issues the same issues.

**Comment by tlynchlaw** [comment]
I experienced this same problem on April 11, 2019.  Update did not work.  But deintegrating the firebase pods with a `pod deintegrate` and then reinstalling with a `pod install` solved the problem.

**Comment by allanzi** [comment]
Thanks @tlynchlaw 
Worked for me

**Comment by nthrussell** [comment]
Thanks @tlynchlaw 
Worked for me as well, brilliant
