### ISSUE TITLE
[🐛] 🔥 Admob crashes Android app on emulator just after successful build

### ISSUE THREAD

**Issue by betoharres** [invertase/react-native-firebase#4712]
## Issue

Describe your issue here

After following the the guide from https://rnfirebase.io/admob/usage
I did everything what it was saying and the app was crashing on emulator just after it launched after the build was complete.
After research I launched Flipper and found this error on`Crash Reporter`: 
``` 
FATAL EXCEPTION: main
Process: com.myapp, PID: 3755
java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException:
******************************************************************************
* Invalid application ID. Follow instructions here: *
* https://googlemobileadssdk.page.link/admob-android-update-manifest *
* to find your app ID. *
```
It happens that the guide doesn't mention this crucial step:
https://developers.google.com/admob/android/quick-start#update_your_androidmanifestxml
```
Update your AndroidManifest.xml

Add your AdMob app ID (identified in the AdMob UI) to your app's AndroidManifest.xml file by adding a <meta-data> tag with android:name="com.google.android.gms.ads.APPLICATION_ID", as shown below.

You can find your app ID in the AdMob UI. For android:value, insert your own AdMob app ID in quotes, as shown below.

<manifest>
    <application>
        <!-- Sample AdMob app ID: ca-app-pub-3940256099942544~3347511713 -->
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
    </application>
</manifest>
```
but even after doing that I wasn't able to build because for some reason that `meta-data` is already declared on admob library, 
thus throwing this error on build:
```
* What went wrong:
Execution failed for task ':app:generateDebugBuildConfig'.
> org.xml.sax.SAXParseException; systemId: file:/home/me/code/myapp/android/app/src/main/AndroidManifest.xml; lineNumber: 42; columnNumber: 34; The prefix "tools" for attribute "tools:replace" associated with an element type "meta-data" is not bound.
```
so if you go to `node_modules/@react-native-firebase/admob/android/src/main/AndroidManifest.xml` you'll find that meta-data tag:
```
      <meta-data
        android:name="com.google.android.gms.ads.APPLICATION_ID"
        android:value="${firebaseJSONAdmobAppID}"/>

```
my solution, for now, is to run `patch-package` on admob library and remove these 3 lines, now everything is working - at least the testing ads are showing and the app is building just fine; 
I already tried to add the `tools:replace` attribute but it didn't work.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.4")
        classpath("com.google.gms:google-services:4.3.3")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

```

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Linux 5.9 Arch Linux
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 2.09 GB / 15.56 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 15.4.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.8 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 3.9.1 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
```

libraries:
```
"@react-native-firebase/admob@^10.3.1":
  version "10.3.1"
"@react-native-firebase/app@^10.3.0":
  version "10.3.0"
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - N

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
The documents specify something different, they ask you to put it in firebase.json

https://rnfirebase.io/admob/usage#setting-up-google-admob

They explicitly warn you will crash if not

Here is an example that works using the standard example admob ids:

https://github.com/mikehardy/rnfbdemo/blob/62e8013a5b707c78d986eb3e9cee23f62dc994a0/make-demo.sh#L137-L154

**Comment by betoharres** [comment]
Hmm, I had that file at the project root with valid APP ID for both android and iOS, and the warning from the guide specify that it would crash during build and my problem was happening just after the app launched on emulator after the successful build, the app would open on emulator and in less than a second would crash with that error from Flipper that I pasted before.

I loved that code from the demo though! it's awesome

**Comment by mikehardy** [comment]
There may be a problem with the module - few things in software really surprise me anymore - but it would be unexpected. If you can run the demo and it crashes, we're on to something - post the App.js we can throw into the result of that make-demo script to crash it and we can get to work, otherwise it has to be something in your project

**Comment by pushpendra-choudhary** [comment]
I am also facing same issue and updated manifest file as well with respective ids: 


@betoharres  to use `tools:replace` attribute you need to add this line in your manifest file `xmlns:tools="http://schemas.android.com/tools"`

i.e.
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.yourpackage"
    xmlns:tools="http://schemas.android.com/tools">
```

**Comment by betoharres** [comment]
@pushpendra-choudhary thanks for the heads up! I'm going to try your tip later!
