### ISSUE TITLE
[🐛] pod install stuck after installing react-native-firebase/firestore

### ISSUE THREAD

**Issue by Sayyamabbasi786** [invertase/react-native-firebase#4716]
I have been stuck in this for 2 hours, I have been just waiting for the installation of pods, I have tried to update the pod repo and also updated cocoa pods but still stuck in there!

**Comment by mikehardy** [comment]
cocoapods problems should be logged in cocoapods repo
I expect cocoapods maintainers will ask you about your network situation and to inspect exactly what is running on your machine (like a process listing) and how network and disk traffic is going at the moment it appears "stuck". Note that cocoapods repo updates are very network and disk intensive and can violate expectations with regard to how long they "should" take. They can take a very long time.
