### ISSUE TITLE
🔥 [🐛] [iOS][Firestore] runTransaction hangs in some cases

### ISSUE THREAD

**Issue by cdunkel** [invertase/react-native-firebase#4720]
## Issue

My team has a mixed native/React Native application that is structured differently from most of the React Native apps that I have seen. The app is primarily native Objective-C code, but there are two screens that are 100% React Native. These screens view similar content but are reached through different paths in the app. The screens in question allow users to view available reservation times to speak with someone and then cancel or change those reservations.

All of the reservation-related operations (book, change, cancel) use Firebase transactions in order to ensure atomicity and prevent conflicts with other users. On RNFirebase v5 these transactions worked fine. Here's an example of a cancellation operation:

```
async cancelReservation(<props>) {

    // Several read operations are performed outside of the transaction for validation
    // This code is always run

    return this.database.runTransaction(async (transaction) => {

      // This code is never run when experiencing the issue

      // Several read operations are performed using the transaction to ensure that changes to that data will result in a re-run of the operation.

      // Update the Time Slot record (this is the first and primary write operation using the transaction)
      await TimeSlot.cancelTimeSlotForUserWithTransaction(userID, timeSlot, transaction);

        // Other write operations performed that complete the cancellation process for the given user

      return Promise.resolve({<Email Props>});
    })
      .then(({<Email Props>}) => {
        // Send Email
        API.sendReservationCancelledEmail({<Email Props>})
          .catch((err) => {
            console.warn('Error sending reservation canceled email', err);
          });
      })
      .catch((error) => {
        console.error(error);
        throw error; // Re-throw error
      });
  }
```

If the user visits just _one_ of the React Native screens in the app the transaction will work as expected. However, if the user visits both of the screens then the function will hang at the `runTransaction` call.

As stated above, these functions work fine on RNFirebase v5, and this issue only appears to be impacting the iOS app. The Android app appears to function as expected.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
    "@react-native-firebase/analytics": "7.6.7",
    "@react-native-firebase/app": "8.4.5",
    "@react-native-firebase/auth": "9.3.0",
    "@react-native-firebase/crashlytics": "8.4.9",
    "@react-native-firebase/database": "7.5.11",
    "@react-native-firebase/firestore": "7.8.6",
    "@react-native-firebase/storage": "7.4.9",
    ...
}
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target :'App' do

  # TwitterCore
  pod 'TwitterCore'

  # TwitterKit
  pod 'TwitterKit5'

  # Fingertips Presentation Overlay
  # pod 'Fingertips'

  # Empty Data Set View
  pod 'DZNEmptyDataSet', '= 1.8.1'

  # Update Status Notifications
  pod 'JDStatusBarNotification', '= 1.5.6'

  # Handy image download and caching lib
  pod 'SDWebImage', '= 5.0.5'

  # Progress indicator used throughout the app
  pod 'SVProgressHUD', '= 2.2.5'

  # Push Notification management
  pod 'OneSignal', '= 2.11.2'

  # Pulley drawer UI for bottom sheet (https://github.com/52inc/Pulley)
  pod 'Pulley', '= 2.3.2'

  # Mux Data
  pod 'Mux-Stats-Core', '= 2.0.6'
  pod 'Mux-Stats-AVPlayer', '= 0.1.3'

  # AWS SDK
  pod 'AWSS3', '= 2.6.0'

  # Pods for RnDiffApp
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  # React Native Firebase
  pod 'RNFBAnalytics',  :path => '../node_modules/@react-native-firebase/analytics'
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'
  pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'
  pod 'RNFBDatabase', :path => '../node_modules/@react-native-firebase/database'
  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'
  pod 'RNFBStorage', :path => '../node_modules/@react-native-firebase/storage'

  # Firebase
  pod 'Firebase/Core', '= 6.30.0'
  pod 'Firebase/Analytics', '= 6.30.0'
  pod 'Firebase/Auth', '= 6.30.0'
  pod 'Firebase/Crashlytics', '= 6.30.0'

  # Add new pods below this line comment
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  # React Native Permissions
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'
    pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
      'TextDetector',
      'BarcodeDetectorMLKit'
    ]

  # MS Code Push
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Pulley'
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    else
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end

    if target.name == 'yoga'
        target.build_configurations.each do |config|
            config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
            config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
        end
    end
  end
end

```

#### `AppDelegate.m`:

```objc
- (void)setupFirebase {
    [FIRApp configure];
    // Log level increased during debugging
    [[FIRConfiguration sharedInstance] setLoggerLevel:FIRLoggerLevelMax];
}
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
This issue does not seem to impact Android.
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.36 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.3.0 - ~/.nvm/versions/node/v9.3.0/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v9.3.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.3
      System Images: android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.1.1 4.1.1
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `v6`
- **`Firebase` module(s) you're using that has the issue:**
  - `Firestore`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Mmmmm this is going to be difficult to triage.

That it works on v5 and does not on v6+ is a great starting place though, that makes bisect vs instrument a good idea as a first strategy.

Normally I would say "update to current and see if you can reproduce", that is perhaps useful as an independent branch of investigation. That means specifically using https://react-native-community.github.io/upgrade-helper/ to get up to react-native 0.63.4 and moving forward to react-native-firebase 10.3.x along with underlying firebase-ios-sdk 7.3.0. I am not sure this will have any effect but it *might* and your resulting project will be more healthy at least, with whatever fix we implement being easily available to you. The versions you are on are not ones I would contemplate using for ios14, FWIW.

As for bisect, are there differences in versions in firebase-ios-sdk between working and non-working? I believe there was considerable range overlap between react-native-firebase v5 and and `@react-native-firebase/firestore` (v6+) with respect to the firebase-ios-sdk versions supported and your version (6.30.0) was in the range. Did 6.33.0 work on v5 but not v6?

What are the versions in react-native-firebase (v5) vs the first version of `@react-native-firebase/firestore` that fails? Fixing the firebase-ios-sdk to one that works in v5, then bisecting `@react-native-firebase/firestore` down to the first version that fails might be interesting.

If it turns out that the very first v6+ version of `@react-native-firebase/firestore` fails even with firebase-ios-sdk working, then at the very least we should have a small set of actual changes to look at I think.

**Comment by mikehardy** [comment]
Also, worth mentioning, any way you could create an App.js that creates a test data fixture and then demonstrates the problem when dropped into a clean project built running https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh would be great, clean reproductions are typically worth their weight in gold

**Comment by cdunkel** [comment]
@mikehardy, thanks for the quick reply!

Just for comparison, the working firebase-ios-sdk versions that I was using in conjunction with RNFB v5 are:
```
# Firebase
  pod 'Firebase/Core', '= 6.2.0'
  pod 'Firebase/Analytics', '= 6.2.0'
  pod 'Firebase/Auth', '= 6.2.0'
  pod 'Firebase/Database', '= 6.2.0'
  pod 'Firebase/Firestore', '= 6.2.0'
  pod 'Firebase/Storage', '= 6.2.0'
  pod 'Firebase/MLVisionTextModel', '= 6.2.0'
```

I upgraded to v6.30.0 as part of migrating to RNFB v6, but have not messed around with other versions of the firebase-ios-sdk. I did review the release notes for the firebase-ios-sdk and did not see anything that seemed related to this issue.

The "working" react-native-firebase version was v5.5.6 and the non-working @react-native-firebase/firestore is v7.8.6. I can experiment with updating the firebase-ios-sdk to v6.30.0 and see if that breaks anything.

My main limitation at the moment is that I'm on a very short deadline to release something that is at least functional, so that may necessitate just stripping out the transaction dependency for now and re-introducing it later when I have time to dig in a bit more. Knowing that the current versions that I'm running aren't recommended for iOS 14 support is good to know as well, since there may be another upgrade in my future anyway.

**Comment by mikehardy** [comment]
Okay - I'll wait to hear  back then but I am interested. The easiest first check is just your pre-migration (working) version, bumped to firebase-ios-sdk 6.30.0 to see if it is triggered immediately. That would isolate it to this module vs underlying SDK, which is important to know and starts focusing things. Good luck with your project!

**Comment by cdunkel** [comment]
@mikehardy, I ran through the test of running RNFB v5.5.6 with `firebase-ios-sdk` v6.30.0 and transactions seem to be working properly. That would lead me to believe that the problem is with RNFB and not with the `firebase-ios-sdk` version that we're using.

That also leads me to ask if there is any sort of rollback guide for RNFB. I have made significant additional changes to my mobile app(s) since that update and only recently discovered this issue, so I'd like to explore potentially reverting to RNFB v5.5.6 for this one release and then re-upgrading to a patch or working version in the near future.

Let me know your thoughts on the feasibility of that or if you have a better path. Thanks again for your help!

**Comment by mikehardy** [comment]
Very interesting, thanks for checking that.

Okay some somewhere between the firestore code in v5.5.6 and `@react-native-firebase/firestore` 7.8.6 we have a problem

There is no rollback guide as such, at this point v5.x.x is effectively unsupportable but I do understand your need. All I can say is to apply the forward guide but in reverse effectively. The original integration instructions for v5 do still live (https://v5.rnfirebase.io/docs/v5.x.x/getting-started) and an old version of my demo script showing how to do the v5 integration is also still available (https://github.com/mikehardy/rnfbdemo/blob/b97bc057bd6fddbc430f31bd9ef01aeff3b673f2/make-demo.sh)

**Comment by cdunkel** [comment]
@mikehardy thanks! I hate to rollback. I just need to weigh the potential downside of that vs. running those operations without transactions for the near future. Once I have the immediate issue addressed I will try to come back and run through some of the other tests that you mentioned since we definitely need transactions to work properly for our use case into the future.

If it's at all helpful, I did discover another strange aspect to this issue. Our two React Native `RCTRootView` instances are accessible in different ways. One lives as the parent view for a UITabBar item and one lives in a modal. The issue I've been seeing is that if you open the app fresh, open the UITabBar RN view, then visit the modal view, and then try to trigger the transaction-based operation from the UITabBar view it will fail. However, I just tested the reverse (visiting the modal first, then the UITabBar, and then triggering the transaction from the modal) and it seems to work. I have no idea why that would be the case other than that the RNRootView that lives in the Tab bar persists and the one in the modal is destroyed each time. Hopefully that's helpful.

Thanks again!

**Comment by cdunkel** [comment]
@mikehardy, just an update - I was able to roll RNFirebase back to the previous version without impacting any of the other updates that I had made recently. This seems to have "solved" the problem for now, but I know we're not going to want to stay on the old version for long.

**Comment by mikehardy** [comment]
I'm glad you were able to move forward - even if only temporarily - with your project

To move this forward for real, I'll reiterate this -

> Also, worth mentioning, any way you could create an App.js that creates a test data fixture and then demonstrates the problem when dropped into a clean project built running https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh would be great, clean reproductions are typically worth their weight in gold

This is an open source repo so our resources are pretty thin, and for complicated things (like transaction issues...) it is many times easier for us to investigate module issues when we start with a demonstration of the problem from the people experiencing the problem. In cases like this where the starting point is "try to reproduce the complicated problem" we frequently spend a great deal of time with no result, which means they don't get priority since the result vs spent effort is frequently low vs other areas that need attention.

**Comment by cdunkel** [comment]
Understood. I'll post again when I have a demo app that you and your team can play with that replicates the issue. Thanks again for your help!
