### ISSUE TITLE
🔥[🐛] signInWithCredential using OAuthProvider returns Invalid IdP response/credential

### ISSUE THREAD

**Issue by Appkidd** [invertase/react-native-firebase#4731]
## Issue

We are trying to use React Native Firebase to sign in with a Microsoft Account.

As detailed [here](https://github.com/invertase/react-native-firebase/issues/3926#issuecomment-657229455), in order to achieve this we must use a third party library. We decided to use [react-native-app-auth](https://github.com/FormidableLabs/react-native-app-auth) to complete the OAuth flow and retrieve the relevant tokens.

The code below shows us using the third party library to obtain an `idToken` and an `accessToken`. These are then passed to `OAuthProvider` via the `credential` method.

```javascript
const signIn = async () => {
  const config = {
    clientId: 'my-client-id',
    redirectUrl: 'my-app-url-scheme//oauth2/authorize',
    scopes: ['openid', 'profile', 'email', 'offline_access'],
    serviceConfiguration: {
      authorizationEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
      tokenEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
    },
  };
  
  // Log in to get an authentication token
  try {
    const authState = await authorize(config);
    const credential = firebase.auth.OAuthProvider.credential(authState.idToken, authState.accessToken);
    await firebase.auth().signInWithCredential(credential);
  } catch (e) {
    console.log(e);
  }
};

signIn();
```

When `signInWithCredential` is invoked with the credential, the library returns `internal error` in the console. I have printed the contents of the NSError variable below:

```
Error Domain=FIRAuthErrorDomain Code=17999 "An internal error has occurred, print and inspect the error details for more information." UserInfo={FIRAuthErrorUserInfoNameKey=ERROR_INTERNAL_ERROR, NSLocalizedDescription=An internal error has occurred, print and inspect the error details for more information., NSUnderlyingError=0x280ec75a0 {Error Domain=FIRAuthInternalErrorDomain Code=3 "(null)" UserInfo={FIRAuthErrorUserInfoDeserializedResponseKey={
    code = 400;
    errors =     (
                {
            domain = global;
            message = "INVALID_CREDENTIAL_OR_PROVIDER_ID : Invalid IdP response/credential: http://localhost?providerId=oauth&id_token=MY_ID_TOKEN_HERE&access_token=MY_ACCESS_TOKEN_HERE";
            reason = invalid;
        }
    );
    message = "INVALID_CREDENTIAL_OR_PROVIDER_ID : Invalid IdP response/credential: http://localhost?providerId=oauth&id_token=MY_ID_TOKEN_HERE&access_token=MY_ACCESS_TOKEN_HERE";
}}}}
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-firebase/app": "^10.3.0",
    "@react-native-firebase/auth": "^10.3.1",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-app-auth": "^6.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.16.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'app' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'app-tvOS' do
  # Pods for app-tvOS

  target 'app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <Firebase.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif
  
//  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
//  }
  
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"app"
                                            initialProperties:nil];

//  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *, id> *) options {
  return [self.authorizationFlowManagerDelegate resumeExternalUserAgentFlowWithURL:url];
}

@end
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 2.06 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v13.3.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [X] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `"@react-native-firebase/app": "^10.3.0"  and "@react-native-firebase/auth": "^10.3.1"`
- **`Firebase` module(s) you're using that has the issue:**
  - `Auth`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hmm, searching that up doesn't provide much, but there was a hint that it may be a project mismatch https://groups.google.com/g/firebase-talk/c/vDTR3sBmHKg

I would class that as unlikely but while triple-checking everything, that's one to check.

Your code is incomplete, so I can't reason about it, please post a full minimal reproduction

I'm expecting it to flow something like this? https://firebase.google.com/docs/auth/web/microsoft-oauth

It may be worth noting that you/we may pursue a different tactic - Firebase supports Microsoft Auth formally now, and adding a supported auth provider is not that difficult

Here is an example using Apple Sign-in which shows it wasn't that much code, and Apple was the worst case since they required nonce where others don't

https://github.com/invertase/react-native-firebase/pulls?q=is%3Apr+apple+authentication

The main PR was literally only 50 lines of code, and it was effectively all boilerplate:  https://github.com/invertase/react-native-firebase/pull/2979/files

The only thing missing in that PR (which did work for auth!) was a docs update showing usage like: https://github.com/invertase/react-native-firebase/blob/467a9c7e436e61ce3c31338b66448bb116d85760/docs/auth/social-auth.md#google

You might try reaching in to node_modules and just giving the native microsoft auth provider a shot. It might just be 10-20mins of work and poof RNFB has official support 🤔

**Comment by Appkidd** [comment]
> Hmm, searching that up doesn't provide much, but there was a hint that it may be a project mismatch

Double checked and unfortunately not that.

> Your code is incomplete, so I can't reason about it, please post a full minimal reproduction

The only thing missing is the imports of which all are Firebase except `authorize` which is from `react-native-app-auth`. The code just runs inside a `useEffect` with no dependencies. I've setup a repo 

> You might try reaching in to node_modules and just giving the native microsoft auth provider a shot. It might just be 10-20mins of work and poof RNFB has official support 🤔

Funny you should say that - that's exactly what I was doing very late last night! 😬

I've just revisited this now and [published the additional boilerplate to a repo](https://github.com/Appkidd/react-native-firebase/commit/83f50660fd31eb6c64813949d98921a85ebfd114).

Upon looking into this further, I noticed that the `redirectUrl` we were providing wasn't the one Firebase provides in the console when enabling Microsoft as a provider. Upon fixing this and updating the application registration in Azure, I then stumbled on a [completely different error upstream](https://github.com/firebase/firebase-ios-sdk/issues/7153) as shown in the screenshot below.

I'm no OAuth expert but presumably if the redirect URL isn't correct, it's possible this is creating the invalid credential error? Perhaps we should put this on pause until the upstream redirect issue is resolved? As time is of the essence I think we will pass our `accessToken` up to Cloud Functions, validate it and then create a custom token for the time being.

Thanks again for your continued help!

![Screenshot](https://i.imgur.com/XQ1kjqV.png)

**Comment by mikehardy** [comment]
> I've just revisited this now and published the additional boilerplate to a repo.

Your boilerplate looks great, if you PRd that I'd merge it

That other error looks fascinating! The code referenced has a related example in the Swift version from Step 6 here https://firebase.google.com/docs/auth/ios/microsoft-oauth#handle_the_sign-in_flow_with_the_firebase_sdk

If you switch that example code to Objective-C to match our implementation I end up with something that my limited Objective-C skills can't line up quite right.

We do signInWithCredential here https://github.com/invertase/react-native-firebase/blob/a8dcd54d8a7d49e3da05da9ddcfdd6abd976bb48/packages/auth/ios/RNFBAuth/RNFBAuthModule.m#L538-L565

...but I think the catch-error/delay-1-second/retry loop might be done by the poster in the upstream issue on the handler of getCredentialWithUIDelegate and I don't see us using that, we use getCredential. So I'm not sure how I would implement his workaround as a patch in our auth module

https://github.com/invertase/react-native-firebase/blob/a8dcd54d8a7d49e3da05da9ddcfdd6abd976bb48/packages/auth/ios/RNFBAuth/RNFBAuthModule.m#L948

It may be that microsoft is also a sort-of-special case like Sign In With Apple (which needed the nonce) where we allow the user to pass in the custom parameters etc in the upstream docs and then get the credential similar to the upstream code using that getCredientialWithUIDelegate method vs getCredential like the others. In other words: less boilerplate and more actual work unfortunately

**Comment by Appkidd** [comment]
I think based on the fact that this isn't a feature that is in high demand, it's better for now for us to use a custom auth token and get things working that way.

Thanks again for your help Mike!

**Comment by mikehardy** [comment]
No problem and I appreciate the collaboration either way - I learned it was going to be harder than I thought - I was thinking supporting Azure / MS login would be nearly trivial.

For any future readers please know that it may not be in super high demand but we would like to have 100% coverage of the providers the SDK covers so it's a desired feature and I'm happy to work with anyone to merge something in

Cheers @Appkidd

**Comment by joaonew** [comment]
Hey @mikehardy, any idea on how to successfully return a user job_title from Microsoft AD in the login process with Microsoft?

**Comment by mikehardy** [comment]
Hi @joaonew I wish I did know and could just tell you but unfortunately I've got no experience with it
