### ISSUE TITLE
[🐛] Bug Report Title - Firebase-Installations: Error when communicating with the Firebase Installations server API. HTTP response: 403 Forbidden

### ISSUE THREAD

**Issue by mohitsharma90** [invertase/react-native-firebase#4737]
## Issue
Getting this error on Android after upgrading  on messaging().getToken(), while ios works fine. Found this error after running adb logcat.

<details><summary>Click To Expand</summary>

W/Firebase-Installations: Error when communicating with the Firebase Installations server API. HTTP response: [403 Forbidden: {
      "error": {
        "code": 403,
        "message": "Requests from this Android client application ""app name"" are blocked.",
        "status": "PERMISSION_DENIED",
        "details": [
          {
            "@type": "type.googleapis.com/google.rpc.Help",
            "links": [
              {
                "description": "Google developer console API key",
                "url": "***"
              }
            ]
          }
        ]
      }
    }
    ]

Version Details:
 "@react-native-firebase/app": "^10.4.0",
    "@react-native-firebase/messaging": "^10.4.0",
<p>

**Comment by mikehardy** [comment]
Usually that's SHA config from your keystore key used for signing and the firebase console. Triple check all installation steps. 

You skipped the template, and the module definitely works (this is project specific) -> closing
