### ISSUE TITLE
[🐛] Not always receiving notification object in background state in ios

### ISSUE THREAD

**Issue by tagizade-samir** [invertase/react-native-firebase#4738]
## Issue

Hi,

We have chat project written in react-native where we send notifications through firebase to another user or user groups. The problem is that we don’t always get notification object in background state on ios that we sent using messaging().setBackgroundMessageHandler. We don’t know where problem exactly is. Seems like firebase not sending it right away, because after some time we receive several messages at once. We updated react-native, firebase to the latest versions, didn’t help. Notifications are sent with “data-message” type.

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

"@react-native-firebase/app": "10.4.0",
"@react-native-firebase/messaging": "10.4.0",
"@react-native-community/push-notification-ios": "1.2.2",

#### `This is notification object that we receive from firebase, when our app is in background`:

{ messageId: '1609865111283350',
  data: 
   { 'from-username': 'test',
     subtype: 'text },
     contentAvailable: true }

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

$FirebaseSDKVersion = '7.0.0'
$FabricSDKVersion = '1.6.0'
$CrashlyticsSDKVersion = '3.1.0'
 
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
install! 'cocoapods', :deterministic_uuids => false
target 'corporate_chat' do
  Pods for corporate_chat  
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios/RNCPushNotificationIOS.podspec'
 
  target 'corporate_chatTests' do
    inherit! :search_paths
    Pods for testing
  end
 
  use_native_modules!
end
 
target 'corporate_chat-tvOS' do
   Pods for corporate_chat-tvOS
  target 'corporate_chat-tvOSTests' do
    inherit! :search_paths
     Pods for testing
  end
 
end

#### `ios/Podfile.lock`:

- Firebase/CoreOnly (7.0.0):
    - FirebaseCore (= 7.0.0)
  - Firebase/Messaging (7.0.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 7.0.0)
  - FirebaseCore (7.0.0):
    - FirebaseCoreDiagnostics (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
  - FirebaseCoreDiagnostics (7.3.0):
    - GoogleDataTransport (~> 8.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
    - nanopb (~> 2.30906.0)
  - FirebaseInstallations (7.3.0):
    - FirebaseCore (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (7.3.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
  - FirebaseMessaging (7.0.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstanceID (~> 7.0)
  - RNFBApp (10.4.0):
    - Firebase/CoreOnly (= 7.0.0)
    - React-Core
  - RNFBMessaging (10.4.0):
    - Firebase/Messaging (= 7.0.0)
    - React-Core
    - RNFBApp

DEPENDENCIES:
  - "RNFBApp (from `../node_modules/@react-native-firebase/app`)"
  - "RNFBMessaging (from `../node_modules/@react-native-firebase/messaging`)"

SPEC REPOS:
  trunk:
    - Firebase
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseInstallations
    - FirebaseInstanceID
    - FirebaseMessaging

EXTERNAL SOURCES:
  RNFBApp:
    :path: "../node_modules/@react-native-firebase/app"
  RNFBMessaging:
    :path: "../node_modules/@react-native-firebase/messaging"

COCOAPODS: 1.10.0

</p>
</details>

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `7.0.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `messaging`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there

Update to latest stable
Use real devices only
Test with -FIRDebugEnabled added to command line (Google that in firebase docs)
Watch device logs from console.app or xcode
Respect that Apple can throttle you any time

**Comment by tagizade-samir** [comment]
We already tried latest firebase version and we are using real device and we can not always get message from firebase in background

**Comment by andersonaddo** [comment]
The fact that you're getting them means your setup is correct. 
Like Mike said, look into apples push notification throttling.

**Comment by tagizade-samir** [comment]
Okay, thank you, guys, for quick reply. We'll look into apples documentation about that
