### ISSUE TITLE
chiness rom (oppo, vivo) not getting notifications when app is killed

### ISSUE THREAD

**Issue by hieuuet** [invertase/react-native-firebase#4742]
Testing app in samsung working fine when app is killed,  in background or foreground. but when i test app in vivo, oppo not getting push notification if app is killed, they work fine if app is in background or foreground.
Please give me the solution?

**Comment by mikehardy** [comment]
Unfortunately there is not much we can do here
https://dontkillmyapp.com

It is not in scope for this module to determine if the app is subject to vendor-specific / android-API-violating power management restrictions or not but there are lots of solutions (many including code) online. It mostly involves detection of the state (in vendor specific ways) and then education for the users and an Intent that takes the user to the vendor-specific control panels to whitelist the app.

Android team is on record as saying these vendor-specific violations of platform expectations will no longer be tolerated in future Android versions at least, and tests were added to the compatibility suite so Android 12 may be better.
