### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":

### ISSUE THREAD

**Issue by saurabh874** [invertase/react-native-firebase#4743]
Hi i am using firebase v6. 
"@react-native-firebase/app": "^10.1.0",
"@react-native-firebase/crashlytics": "^8.4.9",
"@react-native-firebase/dynamic-links": "^7.5.9",
"@react-native-firebase/messaging": "^10.2.0",
"@react-native-firebase/ml": "^10.1.1",
"react-native-camera": "^3.40.0", 
i need textdetector which is come in react-native-camera
**pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  'TextDetector'
]** so when i am adding this line in my podfile. i am getting some error which is related from firebase.

**[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    RNFBAnalytics (from `../node_modules/@react-native-firebase/analytics`) was resolved to 10.3.0, which depends on
      Firebase/Analytics (~> 7.3.0) was resolved to 7.3.0, which depends on
        Firebase/Core (= 7.3.0) was resolved to 7.3.0, which depends on
          Firebase/CoreOnly (= 7.3.0)

    RNFBApp (from `../node_modules/@react-native-firebase/app`) was resolved to 10.3.0, which depends on
      Firebase/CoreOnly (~> 7.3.0)

    react-native-camera/TextDetector (from `../node_modules/react-native-camera`) was resolved to 3.40.0, which depends on
      Firebase/MLVisionTextModel was resolved to 5.0.0, which depends on
        Firebase/CoreOnly (= 5.0.0)**
        
        anybody have idea what is problem here. i tried with pod update pod install

**Comment by mikehardy** [comment]
Hi there!
We have a locked-version release policy now, so you may not pick and choose upgrades, if you upgrade one package to 10.3.0 (like analytics) then you must update them all. 10.4.0 is current in fact

Please update all your packages to 10.4.0, then re-install the pods. You may need to remove Podfile.lock first - but it should work

**Comment by saurabh874** [comment]
Hi @mikehardy  i upgrade all packages which is related from firebase but still faceing same issue.
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    RNFBApp (from `../node_modules/@react-native-firebase/app`) was resolved to 10.4.0, which depends on
      Firebase/CoreOnly (~> 7.3.0)

    RNFBDynamicLinks (from `../node_modules/@react-native-firebase/dynamic-links`) was resolved to 10.4.0, which depends on
      Firebase/DynamicLinks (~> 7.3.0) was resolved to 7.3.0, which depends on
        Firebase/CoreOnly (= 7.3.0)

    react-native-camera/TextDetector (from `../node_modules/react-native-camera`) was resolved to 3.40.5, which depends on
      Firebase/MLVisionTextModel was resolved to 5.0.0, which depends on
        Firebase/CoreOnly (= 5.0.0)
        
        **pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
'TextDetector'
]**
        problem is occur when we add subspeces: [
'TextDetector'
] in react-native-camera. if i dont add suspeces it will perfectly working.

**Comment by mikehardy** [comment]
We can't control version conflicts with other packages. There's a PR in the camera repo you might like though, allowing it to use the new mlkit pods you need in combo with firebase ios sdk 7+
