### ISSUE TITLE
[🐛] Auth Emulator strangely using production auth sometimes

### ISSUE THREAD

**Issue by SrBrahma** [invertase/react-native-firebase#4754]
## Issue

I really have no idea yet, but somehow after some time using the auth emulator, the app will use Production auth to login (only tested with Google provider). It happens kinda randomly. Reopening the app seems to temporarily fixes it.

It sometimes happens just by signing out of a recent successful login and right then signing in with another account, without doing any fast refresh / code change / app reopen. Just switching between my 4 Google accs will in a short time authenticate with prod, and give me auth errors in Database and Functions, as they are receiving wrong credentials.

I hope someone can share its similar experiences here.

My firebase.ts:

```ts
import '@react-native-firebase/database';
import '@react-native-firebase/functions';
import Firebase from '@react-native-firebase/app';
import '@react-native-firebase/auth';


export const firebaseEmulator = {
  emulating: true && __DEV__, // Just change to false if production. __DEV__ to be sure..
  url: 'http://192.168.0.18',
  authPort: 9099,
  functionsPort: 5001,
  databasePort: 9000,
};


export const firebase = Firebase.app();
export const auth = firebase.auth();
export const functions = firebase.functions();


if (firebaseEmulator.emulating) {
  // The Realtime Database emulator configs is set in the ./database.ts.
  console.warn(`Warning!! Using local emulated Functions, Auth and Database!!`);
  auth.useEmulator(`${firebaseEmulator.url}:9099`);
  functions.useFunctionsEmulator(`${firebaseEmulator.url}:5001`);
}


export const { GoogleAuthProvider } = Firebase.auth;


```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 378.76 MB / 7.65 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.20.1 - ~/n/bin/node
    Yarn: 1.22.4 - ~/n/bin/yarn
    npm: 6.14.11 - ~/n/bin/npm
    Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-28 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: ^0.63.4 => 0.63.4 
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [X] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 10.4.1
- **`Firebase` module(s) you're using that has the issue:**
  - Auth
- **Are you using `TypeScript`?**
  - Y 4.1.3

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
would be instructive to instrument (like, just output to System.err / console.log) inside node_modules all api calls to use emulator, and any underlying java calls that might be able to tell you just prior to execution whether they are pointing at auth or not, and watch adb logcat

Without a reproduction I'm not sure what we can do?

**Comment by SrBrahma** [comment]
There doesn't seem to be any problem in the auth .js files, the useEmulator is used just once on the respective function.

`signInWithCredential` and `signOut` won't deal with emulator on .js and on ReactNativeFirebaseAuthModule.java.

On the .java, there is just the
```
  @ReactMethod
  public void useEmulator(String appName, String host, int port) {
    Log.d(TAG, "useEmulator");
    FirebaseApp firebaseApp = FirebaseApp.getInstance(appName);
    FirebaseAuth firebaseAuth = FirebaseAuth.getInstance(firebaseApp);
    firebaseAuth.useEmulator(host, port);
  }
```

and the FirebaseAuth is imported with 
` import com.google.firebase.auth.FirebaseAuth; `

I don't know almost nothing about Java. Where is the source of this import? The issue must be there. I can investigate further studying this source.

The minimal reproduction may be just having on the login a database.once() to a place that have uid Rule, and see if it throws an error, and keep signing out and in. Maybe it's necessary to also have an active prod env.

**Comment by mikehardy** [comment]
You might like to check the PR where I implemented, each of the commits has (I hope!) a clear title and they are separate. There is a large amount of testing in there so we're pretty sure we *can* get the emulator used all the time, however our test harness does signOut / sign in all the time

https://github.com/invertase/react-native-firebase/pull/4552/commits

Should that (signOut / sign in) be necessary? No, in fact I'm not entirely sure you can un-set useEmulator, I think it's set forever. So, very weird that the setting isn't sticking for you

Specifically in the commit series these are most interesting:

- javascript implementation, jest tests: https://github.com/invertase/react-native-firebase/pull/4552/commits/532adb569413e8a5e5077d5f47582a0a300b3045
- java/objective-c native implementation - really not much to it! https://github.com/invertase/react-native-firebase/pull/4552/commits/81369a089e3ffc5be53d7651fa5a9dacf5bfa7b6
- the e2e (on-device) tests so you can see how I tested it. https://github.com/invertase/react-native-firebase/pull/4552/commits/4c688413cb6516ecfdbd4ea325103d0d8d8d84a8

**Comment by SrBrahma** [comment]
I have set useEmulator before the signins. Seems to have increased the success rate (maybe throws problems 1/10~20 of signins against 1/5 before).

More strangely, it now seems to always use a valid previous uid in emulator instead of using a prod one, but the DB operation will throw permission-denied anyway. 

This previous problem seems to be solved by using onAuthStateChanged instead of onUserChanged (I was using it because it seemed to throw less errors before setting useEmulator on every signin). Rarely, the Functions will say the `.user` isn't valid, even if its UID exists in emulator.

Sometimes, the auth provider process will throw `[auth/unknown] An internal error has occurred. [ unexpected end of stream on com.android.okhttp.Address@d22e60 ]` (have seen other addresses).

Sorry for the uncertainties. It really look like it's somewhat random, or maybe time-based (for those valid uid on DB and CF, maybe they are being used too quickly).

Those problems could even be fault of the firebase-tools.

I took a look on the commits code, but I don't know how to track it down...

I hope someone with similar issues can add more info here. Feel free to close this.

**Comment by mikehardy** [comment]
I will close if it does not progress, however, an App.js we can drop in to an example app from https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh that reproduces it (even if it has to do a loop for 100 times, it could reproduce right?) is the key.

I don't reproduce this and have no reproduction to do so, so I can't offer more

**Comment by shablenko-sednor** [comment]
@mikehardy I have set network type to UMTS in android emulator and now getting this error constantly each time I try to load session
