### ISSUE TITLE
iOS: Firestore gRPC conflict with pod 'Firebase/Firestore'

### ISSUE THREAD

**Issue by brianhiss** [invertase/react-native-firebase#476]
### Issue

When I add in the `pod 'Firebase/Firestore'` into my working `react-native-firebase 3.0.1` fresh install, I get compile errors: `./ios/Pods/gRPC-Core/include/grpc/impl/codegen/gpr_types.h:43:3: Unsupported: typedef changes linkage of anonymous type, but linkage was already computed`

It seems that adding `pod 'Firebase/Firestore'` brings with it several additional dependencies like `gRPC` and `BoringSSL`.

It appears to conflict with the Stripe library [`tipsi-stripe`](https://github.com/tipsi/tipsi-stripe), confirming that `react-native unlink tipsi-stripe` will allow me to compile with `pod 'Firebase/Firestore'`.

Is anyone else having these issues with `gRPC` and `pod 'Firebase/Firestore'`? Does anyone else use [`tipsi-stripe`](https://github.com/tipsi/tipsi-stripe)?

Can anyone replicate this issue by installing [`tipsi-stripe`](https://github.com/tipsi/tipsi-stripe)?
- `yarn add tipsi-stripe && react-native link tipsi-stripe`
- Add into Podfile: `pod 'Stripe', '~> 10.1.0'`
- `pod update`

<img width="1115" alt="screen shot 2017-10-07 at 7 07 17 am" src="https://user-images.githubusercontent.com/1640257/31305869-3a4cb074-ab4c-11e7-9d25-837d806e0263.png">

<img width="695" alt="screen shot 2017-10-07 at 7 00 05 am" src="https://user-images.githubusercontent.com/1640257/31305883-7c96ad68-ab4c-11e7-8b11-01d32e8c7284.png">

### Environment

1. Application Target Platform: iOS 11
2. Development Operating System: macOS Sierra 10.12.6 (16G29)
3. Build Tools: Xcode 9.0
4. React Native version: 0.49.1
5. RNFirebase Version: 3.0.1
6. Firebase Module: Firestore

**Comment by Salakar** [comment]
@brianhiss sorry for the slow reply, been a hectic release. Have you tried following the manual install steps for `tipsi-stripe` - they seem run a couple of link shell scripts against the xcode project - might be breaking something a long the way.

Short of that not much else I can suggest other than maybe make an issue on the official firebase/firestore google group (googlers are on there responding): https://groups.google.com/forum/#!forum/google-cloud-firestore-discuss

**Comment by brianhiss** [comment]
@Salakar @chrisbianca You guys have been amazing! It's been a hectic release, but you two have been on top of it. Many thanks.

Spent all morning on it, seems like it was header conflicts. Submitted a pull request to the other library (https://github.com/tipsi/tipsi-stripe/issues/131), but maybe others here experience it with another library.

I've noticed a lot of these conflicts between libraries more recently.

**Comment by doc-phily** [comment]
I'm getting the same error after adding Firestore and running `pod install`. Project was building and running before I added `pod 'Firebase/Firestore'` and `pod 'Firebase/Storage'`. I'm not using the tipsi-stripe library. 
Here's my Podfile 

```source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'myApp' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/1.20.5",
    :subspecs => [
      "Core",
      "CPP"
    ]

  pod 'React',
    :path => "../node_modules/react-native",
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
  pod 'Yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'GLog',
    :podspec => "../node_modules/react-native/third-party-podspecs/GLog.podspec",
    :inhibit_warnings => true


  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|

    if target.pod_name == 'ExpoKit'
      target.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end


    # Build React Native with RCT_DEV enabled
    next unless target.pod_name == 'React'
    target.native_target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
    end

    end
  end

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
end
```

**Comment by chrisbianca** [comment]
@doc-phily If you take a look at your Podfile.lock you should be able to see which other libraries are using gRPC

**Comment by doc-phily** [comment]
@chrisbianca Thank you for your response. As far as I can see from my Podfile.lock the only library I have that has a gRPC as dependency is FirebaseFirestore other than gRPC itself. 
Here's the result I get from running `grep gRPC -rna -B 4 Podfile.lock` 

```
Podfile.lock-95-  - FirebaseFirestore (0.9.0):
Podfile.lock-96-    - FirebaseAnalytics (~> 4.0)
Podfile.lock-97-    - FirebaseAuth (~> 4.3)
Podfile.lock-98-    - FirebaseCore (~> 4.0)
Podfile.lock:99:    - gRPC-ProtoRPC (~> 1.0)
--
Podfile.lock-136-  - GoogleToolboxForMac/NSString+URLArguments (2.1.3)
Podfile.lock-137-  - GoogleUtilities (1.3.2):
Podfile.lock-138-    - GoogleSymbolUtilities (~> 1.1)
Podfile.lock-139-  - GPUImage (0.1.7)
Podfile.lock:140:  - gRPC (1.6.5):
Podfile.lock:141:    - gRPC-Core (= 1.6.5)
Podfile.lock:142:    - gRPC-RxLibrary (= 1.6.5)
Podfile.lock:143:  - gRPC-Core (1.6.5):
Podfile.lock:144:    - gRPC-Core/Implementation (= 1.6.5)
Podfile.lock:145:    - gRPC-Core/Interface (= 1.6.5)
Podfile.lock:146:  - gRPC-Core/Implementation (1.6.5):
--
Podfile.lock-147-    - BoringSSL (~> 9.0)
Podfile.lock:148:    - gRPC-Core/Interface (= 1.6.5)
--
Podfile.lock-149-    - nanopb (~> 0.3)
Podfile.lock:150:  - gRPC-Core/Interface (1.6.5)
Podfile.lock:151:  - gRPC-ProtoRPC (1.6.5):
Podfile.lock:152:    - gRPC (= 1.6.5)
Podfile.lock:153:    - gRPC-RxLibrary (= 1.6.5)
--
Podfile.lock-154-    - Protobuf (~> 3.0)
Podfile.lock:155:  - gRPC-RxLibrary (1.6.5)
--
Podfile.lock-283-  GoogleSymbolUtilities: 631ee17048aa5e9ab133470d768ea997a5ef9b96
Podfile.lock-284-  GoogleToolboxForMac: 2501e2ad72a52eb3dfe7bd9aee7dad11b858bd20
Podfile.lock-285-  GoogleUtilities: 8bbc733218aad26306f9d4a253823986110e3358
Podfile.lock-286-  GPUImage: 733a5f0fab92df9de1c37ba9df520a833ccb406d
Podfile.lock:287:  gRPC: 42f915ce322b1abc5241621acc776f2fdb0a2039
Podfile.lock:288:  gRPC-Core: 54211a073d238ec8569be06e1a939a72f081a3e9
Podfile.lock:289:  gRPC-ProtoRPC: 4299db62f86df58c88844ccb50f5c48993e704f6
Podfile.lock:290:  gRPC-RxLibrary: 1b1c9c9cf666709ad7714cb0e0f3c44dc0cbfb0b
```

**Comment by chrisbianca** [comment]
Have you tried running:

`pod outdated` - refreshed the pod cache and checks for libraries with updates available
`pod update` - update to the latest version of all pods

**Comment by doc-phily** [comment]
I just tried `pod outdated`, `pod cache clean --all` and `pod update` cleaned my project in xcode (CMD SHIFT K) and attempted to build. Still getting _Unsupported: typedef changes linkage of anonymous type, but linkage was already computed_ 

![image](https://user-images.githubusercontent.com/15890505/31766707-a7f6cbc0-b4c8-11e7-9c7f-4bbcab05099d.png)

**Comment by MArkusmight** [comment]
I find the way how to fix this issue:

- Clean build
- Remove pod 'Firebase/Firestore' from your Podfile
- Make `pod install`
- Restart xCode and build project via xCode (important! wait for app is installing on your device)
- Stop project
- Add pod 'Firebase/Firestore' from your Podfile
- Make `pod install`
- Restart xCode and build  build project

Maybe you will need do this twice, but it works. I face with this issue again when add new device to my provisioning profile.
