### ISSUE TITLE
linkWithCredential throws 'auth/unknown' User has already been linked to the given provider

### ISSUE THREAD

**Issue by aadityapaliwal94** [invertase/react-native-firebase#4762]
Hi!

I have an issue with the handling of the linkWithCredential failure code. I expect to get the error 'auth/provider-already-linked' that is described in a doc (@error auth/provider-already-linked Thrown if the provider has already been linked to the user. This error is thrown even if this is not the same provider's account that is currently linked to the user.) but instead of that, I got the code 'auth/unknown'. 

In iOS, it correctly returns the error code (auth/provider-already-linked).

Environment - 
Platform - Android,
Android SDK: 29,
react-native-firebase/auth: "^8.2.0",
react-native: 0.63.3,

**Comment by mikehardy** [comment]
Waste not another second testing on old versions. Update react-native-firebase then see if you can reproduce.
Additionally, do not ignore the template or your issue will be summarily closed.
