### ISSUE TITLE
[messaging/unknown] The operation couldn’t be completed. Too many server requests.  

### ISSUE THREAD

**Issue by sidsingh760** [invertase/react-native-firebase#4763]
## Issue
**Error message - [messaging/unknown] The operation couldn’t be completed. Too many server requests.**  

I have get error message when i try to get token in firebase method messaging().getToken().
In simulator get token but in real device I have get **Too many server error message.**

**Code**
requestNotifications(['sound', 'badge']).then(
      async ({status, settings}) => {
        if (status === RESULTS.GRANTED) {
          const authorizationStatus = await messaging().requestPermission();
          if (authorizationStatus) {
            messaging()
              .getToken()
              .then(async (token) => {
                alert(token);
                console.log('Permission status:', authorizationStatus);
              })
              .catch((err) => {
                console.log(err);
                debugger;
              });
          }
          // Get the token
        }
      },
    );

**Comment by mikehardy** [comment]
Hi there!

You ignored the template, so this issue will be summarily closed.

The error message is explicit, look for ways to reduce your messaging API request throughput.
Never test messaging on simulator or emulator, use real devices as the simulator and emulator both may perform differently then real devices and the simulator (which is a specific word and implies iOS) does not support messaging and tokens at all
While using real devices connected to your computer watch debug logs (Xcode console or adb logcat)

**Comment by codoffer** [comment]
I have solved this issue by configuring Google CloudAPIs.
1. Login with Google Cloud
2. Choose Project
3. Choose APIs keys (Added by firebase) and configure
4. Add application restriction and set restrict key (Firebase Installation and other APIs, if you want - By Dropdown)

**Comment by PeterGreshnov** [comment]
> I have solved this issue by configuring Google CloudAPIs.
> 
> 1. Login with Google Cloud
> 2. Choose Project
> 3. Choose APIs keys (Added by firebase) and configure
> 4. Add application restriction and set restrict key (Firebase Installation and other APIs, if you want - By Dropdown)

Cause and fix have been confirmed in my case as well: the API key "iOS key (auto created by Firebase)" was misconfigured. Fixing key configuration in Google Cloud Console fixed the issue in my case.

**Comment by SoftDev728** [comment]
@PeterGreshnov, can you help me how to configure it in the google cloud, my auto generated keys are also wrong in there

**Comment by k-saparia** [comment]
@SoftDev728 Here's the exact steps, if you are still blocked.

Step 1 — Find the API key

1. Go to GCP Console → [console.cloud.google.com](https://console.cloud.google.com/)
2. Select your production Firebase project
3. Left sidebar → APIs & Services → Credentials
4. Under "API Keys" section, look for a key named "iOS key (auto created by Firebase)" Or any other API Key that is for iOS

Step 2 — Open the key settings

1. Click on that key (or click the key name)

Step 3 — Check Application Restrictions

Under "Application restrictions" you'll see one of:

- None
- IP addresses
- HTTP referrers
- iOS apps ← this is the one Firebase sets

If it's set to "iOS apps", make sure your bundle ID is listed there. If it's missing or wrong, add it:

`com.your.bundleid`

Step 4 — Check API Restrictions

Under "API restrictions" you'll see:

- "Don't restrict key"
- "Restrict key" ← if this is selected, APIs must be explicitly listed

If "Restrict key" is selected, make sure these APIs are in the allowed list:

- Firebase Installations API
- Firebase Cloud Messaging API
- Token Service API
- Firebase Messaging
- etc.

If any are missing, click "Add an API" and add them.

Step 5 — Save

- Click Save and wait ~5 minutes for the changes to propagate.
