### ISSUE TITLE
[🐛] 🔥 Fatal error with auth().SignInWithPhoneNumber()

### ISSUE THREAD

**Issue by steniobarroso** [invertase/react-native-firebase#4769]
I'm using these libraries
"@ react-native-firebase / app": "^ 10.4.0",
"@ react-native-firebase / auth": "^ 10.4.1",
"@ react-native-firebase / messaging": "^ 10.4.1"

Make the Import
import auth from '@ react-native-firebase / auth';
I call by:
const confirmation = await auth (). signInWithPhoneNumber (phone);
Before sending the SMS it gives a fatal error => auth / no-current-user no user currently signed in
react native version
react-native-cli: 2.0.1
react-native: 0.62.2

**Comment by mikehardy** [comment]
There is something wrong with your use of the APIs.
It works, triple check everything on rnfirebase.io docs site related
If you continue to reproduce, then open a new issue following the template (so we don't just close the issue) and provide an App.js that is self-contained and reproduces the problem when dropped into a clean project (like that created from https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh)

Thanks
