### ISSUE TITLE
v.3.x throws error with RN48

### ISSUE THREAD

**Issue by turtec** [invertase/react-native-firebase#477]
Hi there, 

i'm getting the following error:

Unable to resolve module `react-native/Libraries/Core/ReactNativeVersion` from `..../node_modules/react-native-firebase/lib/modules/utils/index.js`: Module does not exist in the module map

I figured out, that ReactNativeVersion is part of RN 49, it not exits in RN 48.

Your documentation says v.3.x is compatible with RN48+.

**Comment by adyscorpius** [comment]
Faced the same issue as you did. Same config, and I was thinking I did something wrong.

**Comment by Salakar** [comment]
Pushed up v3.0.2 to fix this, should be fine now. Thanks for the report.
