### ISSUE TITLE
[🐛] 🔥 I don't receive sms in release mode, user creation only works in test mode

### ISSUE THREAD

**Issue by steniobarroso** [invertase/react-native-firebase#4771]
The problem persists with a fatal error in v10.4.0, I created a test project and the error continues. I created a repository with the test. Excludes the google-services.json files and the key.keystore that I use for firebase.
Follow the repository link
https://github.com/steniobarroso/auth-react-native-firebase.git

![WhatsApp Image 2021-01-13 at 13 13 58](https://user-images.githubusercontent.com/50188691/104478668-57703880-55a1-11eb-970d-aacd9d19f9f3.jpeg)

**Comment by mikehardy** [comment]
I marked up your repository, it looked like it had numerous javascript coding errors, an iOS integration error, and was not a clean reproduction

**Comment by steniobarroso** [comment]
But I'm only testing on Android

**Comment by steniobarroso** [comment]
I just created the project and installed the dependencies

**Comment by steniobarroso** [comment]
I did the test as requested in this link it only worked with this link https://github.com/mikehardy/rnfbdemo/blob/62e8013a5b707c78d986eb3e9cee23f62dc994a0/make-demo.sh#L26-L30
When I try with a new project it fails

**Comment by steniobarroso** [comment]
The project was created with the make-demo.sh executable, I can create a user in the firebase test mode. I created an apk in realese mode and removed the test mode from firebase, but it doesn't work. follow the link to the repository https://github.com/steniobarroso/auth-react-native-firebase/tree/main

**Comment by mikehardy** [comment]
Could you post whatever the actual error is? From console output and/or `adb logcat`. Being able to reproduce it is great - that's step one - but when asking for help we also need to know exactly what we're talking about. The title just says "The Fatal Error" - okay, what fatal error?

**Comment by steniobarroso** [comment]
There is no error just does not call the sms, I managed to make it work on android once in version 10.4.1. I was redirected to an automatic recaptcha check after receiving the sms. Apparently he is unable to redirect to recaptcha automatic scanning.

**Comment by steniobarroso** [comment]
I think I should create another problem because the app now doesn't close, it just doesn't send sms.

**Comment by steniobarroso** [comment]
The solution is to activate Android Device Verification api on the link https://cloud.google.com and go to your terminal in the cd android folder -> type ./gradlew signingReport and copy the SHA-256 key and insert it into the firebase together with SHA1. Remembering that you have the debug key and realese use the one your project is needing
