### ISSUE TITLE
[📚] Documentation Issue - JEST SETUP

### ISSUE THREAD

**Issue by JiboStore** [invertase/react-native-firebase#4773]
## Documentation Feedback

https://rnfirebase.io/ does not provide any setup or mock functions for jest at all, furthermore, the internal code of the project made it difficult to write mock functions for jest

In one specific instance where I still have no solution for:

```
import messaging from '@react-native-firebase/messaging';

const authStatus = await messaging().requestPermission();
```

we have to use `messaging()` because internally it is written this way:
```
  export type FirebaseModuleWithStatics<M, S = {}> = {
    (): M;
```

This substandard code makes it unnecessarily complex and causes us to unable to mock the `()`
```
jest.mock('@react-native-firebase/messaging', () => ({
  default: jest.fn(),
  (): jest.fn(), // parsing error: unexpected token
}));
```

Why wouldn't you follow the conventional coding practice with something like `getInstance()`?

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Welcome to react-native-firebase!

I look forward to your PRs to bring things up to your standards

You may like https://github.com/invertase/react-native-firebase/blob/master/jest.setup.ts

**Comment by mikehardy** [comment]
We'd be happy to take PRs about things like this and do have a jest setup file as I linked, but in the absence of any actual activity, closing
