### ISSUE TITLE
[firestore] RuntimeException "Cannot convert object of type" when trying to parse Map

### ISSUE THREAD

**Issue by DavidKuennen** [invertase/react-native-firebase#478]
I'm getting a RuntimeException when trying to query by users in firestore.

**Setup:**
```
// room
{
    name: "Test",
    users: {
        test: true
    }
}
```

**Query:**
```
firebase.firestore()
    .collection('rooms')
    .where('users.test', '==', true)
    .get()
    .then((doc) => console.log(doc.data()));
```

**Possible cause:** 
I debugged my app and it seems like you're checking for Map.class in your `putValue`-function, but `users` is a HashMap:
![image](https://user-images.githubusercontent.com/7766565/31306907-02e643e4-ab5a-11e7-85cc-2384c09b2012.png)

After changing the condition to `valueClass == Map.class || valueClass == HashMap.class` it was working for me.

Development Operating System: Windows 10
Build Tools: Android Studio 2.3.3
React Native version: 0.48.4
RNFirebase Version:  3.0.0
Firebase Module: Firestore

**Comment by Salakar** [comment]
Upgrade to 3.0.1 please, published a fix for this yesterday, should work then.

**Comment by DavidKuennen** [comment]
I updated to 3.0.2 and it indeed seems to work now. Thanks 👍

**Comment by Salakar** [comment]
Cool, good to hear. Let us know how you get on with Firestore in general, be good to get some feedback on it =]
