### ISSUE TITLE
[🔥🐛] Occasionally getting "You must be registered for remote messages ..." error

### ISSUE THREAD

**Issue by gilbertl** [invertase/react-native-firebase#4782]
## Issue

We 're getting occasional exception reports from our users (~1-5%) with the following messages:

```You must be registered for remote messages before calling getToken, see messaging().registerDeviceForRemoteMessages().```

We have auto initialization enabled, and our getToken works 95+% of the time. 

#### `package.json`:

```json
{
    "@react-native-firebase/app": "8.4.7",
    "@react-native-firebase/auth": "9.3.2",
    "@react-native-firebase/dynamic-links": "^7.5.11",
    "@react-native-firebase/in-app-messaging": "7.5.8",
    "@react-native-firebase/messaging": "7.9.2",
    "@react-native-firebase/storage": "7.4.11"
}
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:
- [ ] 
  pod 'Firebase/CoreOnly', '~> 6.34.0'
  pod 'Firebase/Analytics', '~> 6.34.0'
  pod 'Firebase/Storage', '~> 6.34.0'
  pod 'Firebase/Auth', '~> 6.34.0'

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 151.45 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /var/folders/45/g30y1xtj3xvd8k4lw2k3s0f80000gn/T/yarn--1610793767260-0.9262399996755493/node
    Yarn: 1.18.0 - /var/folders/45/g30y1xtj3xvd8k4lw2k3s0f80000gn/T/yarn--1610793767260-0.9262399996755493/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0-rc.2 => 0.64.0-rc.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
    "@react-native-firebase/messaging": "7.9.2",

- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
YES : 4.0.2

</p>
</details>

**Comment by mikehardy** [comment]
Upgrade to current versions, no support is provided for old versions, sorry. If you can still reproduce we can reopen

**Comment by PaperMonster** [comment]
I also faced this issue. Only ~10 out of 15K users were affected. Apparently some iOS devices fail to auto register for remote notifications at launch for some reason. My workaround was requesting notification permission, followed by manually register for remote notifications.

```javascript
 async function getCurrentToken() {
    let token, retry;
    try {
        token = await firebaseApp.messaging().getToken();
    } catch (error) {
        // Some iOS devices fail to auto register remote notifications at launch, thus "You must be registered for remote messages before calling getToken" error. 
        // Handle this by request notification permission and manually register for remote notifications
        if(error.code !== 'messaging/unregistered') throw error;
        retry = true;
    }
    if(retry) {
        try {
            await firebaseApp.messaging().requestPermission();    // IMPORTANT!
            await firebaseApp.messaging().registerDeviceForRemoteMessages();    // IMPORTANT!
            token = await firebaseApp.messaging().getToken();
        } catch (error) {
            throw error;
        }
    }
    return token;
}
```

The essential part is BOTH  `requestPermission()` and `registerDeviceForRemoteMessages()` are required.
`registerDeviceForRemoteMessages()` alone doesn't work until notification permission is either granted or denied. (Yes, denied permission works too!).

My environment:
```
"@react-native-firebase/app": "^8.4.7",
"@react-native-firebase/auth": "^9.3.2",
"@react-native-firebase/database": "^7.5.13",
"@react-native-firebase/functions": "^7.4.10",
"@react-native-firebase/messaging": "^7.9.2",
```
