### ISSUE TITLE
[🐛] Dynamic links on resolve link crash

### ISSUE THREAD

**Issue by Jalson1982** [invertase/react-native-firebase#4783]
## Issue

After upgrading  to version 10.4.1 I have error when trying to resolve dynamic link:

<img width="460" alt="Screenshot 2021-01-17 at 11 39 39" src="https://user-images.githubusercontent.com/35011526/104838037-b04d1300-58b8-11eb-99c1-549c6e132d5f.png">

```
  const handleLink = async ({ url }) => {
      const linkObject = await DynamicLinks().resolveLink(url).catch(() => undefined);
      if (!linkObject) { return false; }
      handleUrl({ url: linkObject.url });
      return true;
    };
```

Describe your issue here
The problem started after I update all firebase packages to the latest version. Now, when I want to resolve a link I get error all the time.  I am using 0.63.3 version of RN.
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ + ] iOS
  - [ ] Android
  - [+ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - "@react-native-firebase/app": "^10.4.0",
    "@react-native-firebase/auth": "^10.4.1",
    "@react-native-firebase/crashlytics": "^10.4.1",
    "@react-native-firebase/database": "^10.4.1",
    "@react-native-firebase/dynamic-links": "^10.4.1",
    "@react-native-firebase/messaging": "^10.4.1",- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
So strange, you request help but ignore the template? :thinking: 

Not nearly enough info to go on. Post an App.js that is *fully self-contained* and can be dropped in to the result of a *clean* project created by https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh and actually include the template information at *least* for one platform you have a problem with so we can reproduce, and we can look.

Please note that I use resolveLink in my app, and it works, so I'm 99% this is a project-specific error of some sort that will be detected as you simplify your use-case down to the single-purpose / self-contained demo
