### ISSUE TITLE
[🐛] Analytics not reporting on Android

### ISSUE THREAD

**Issue by WadhahEssam** [invertase/react-native-firebase#4784]
## Issue

Describe your issue here
- Logging analytics events are not reported after the addition of the new `analytics_auto_collection_enabled` feature in 10.4.1.
- This happens when you don't set a value for `analytics_auto_collection_enabled` in the firebase.json, which is not labeled as a mandatory field in the docs, so I  was led to believe it wasn't.
---

## what is the problem: 
- in file `analytics/android/build.gradle` the check for `analytics_auto_collection_enabled` checks if the value is true, else it will just set it to false.
<img width="617" alt="Screen Shot 2021-01-18 at 9 10 01 AM" src="https://user-images.githubusercontent.com/24798045/104878588-4c385680-596d-11eb-813b-50c11afb74fa.png">

## suggested solution:
- add a function in `app/android/firebase-json.gradle` to check if the value exists or not, without checking its value.
<img width="477" alt="Screen Shot 2021-01-18 at 9 11 28 AM" src="https://user-images.githubusercontent.com/24798045/104878638-607c5380-596d-11eb-8606-5e18a1af45ce.png">

- add a checking for the value existence in `analytics/android/build.gradle` before checking its value
<img width="617" alt="Screen Shot 2021-01-18 at 9 10 08 AM" src="https://user-images.githubusercontent.com/24798045/104878692-725df680-596d-11eb-8d9e-2ec5c315064f.png">

**Comment by WadhahEssam** [comment]
For those who are looking for an immediate solution:


- set `analytics_auto_collection_enabled` in the firebase.json to true
<img width="433" alt="Screen Shot 2021-01-18 at 9 16 11 AM" src="https://user-images.githubusercontent.com/24798045/104878883-d4b6f700-596d-11eb-9c7e-b84e161f1f96.png">


- OR call setAnalyticsCollectionEnabled();
```
import { firebase } from '@react-native-firebase/analytics';
// ...
await firebase.analytics().setAnalyticsCollectionEnabled(true);
```

**Comment by WadhahEssam** [comment]
For those who are looking for an immediate solution:


- set `analytics_auto_collection_enabled` in the firebase.json to true

- OR call setAnalyticsCollectionEnabled();
```
import { firebase } from '@react-native-firebase/analytics';
// ...
await firebase.analytics().setAnalyticsCollectionEnabled(true);
```

**Comment by mikehardy** [comment]
Oh no! Thanks for reporting this. It wasn't intended that this defaulted to a different value, that's a regression I'll take a look at it this morning and release a 10.4.2 before it catches anyone else out
