### ISSUE TITLE
ANDROID: fetch from firestore crash the APP

### ISSUE THREAD

**Issue by psycura** [invertase/react-native-firebase#479]
### Issue
Hello guys, and thank you for this awesome library.
I have an issue with fetching data from firestore.
i have this function:
   ```
 async fetchUser () {
        const user = firebase.auth().currentUser;
        if ( user ) {  
            firebase.firestore ()
                .doc ( `reporters/${user.uid}` )
                .get ( ( snapshot ) => {
                    console.log ( 'snapshot', snapshot.data () );
                } )
        }
    }
```
so when i launch an app, the app is crashed , with no any message logged to console.
in the logcat of Android studio i found this error message:

> 10-08 18:18:52.072 7977-7977/com.ceci E/UncaughtException: java.lang.RuntimeException: Cannot convert object of type class java.lang.Long
>                                                                at io.invertase.firebase.firestore.FirestoreSerialize.putValue(FirestoreSerialize.java:200)
>                                                                at io.invertase.firebase.firestore.FirestoreSerialize.objectMapToWritable(FirestoreSerialize.java:124)
>                                                                at io.invertase.firebase.firestore.FirestoreSerialize.snapshotToWritableMap(FirestoreSerialize.java:35)
>                                                                at io.invertase.firebase.firestore.RNFirebaseFirestoreDocumentReference$2.onComplete(RNFirebaseFirestoreDocumentReference.java:72)
>                                                                at com.google.android.gms.tasks.zzf.run(Unknown Source)
>                                                                at android.os.Handler.handleCallback(Handler.java:751)
>                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                at android.os.Looper.loop(Looper.java:154)
>                                                                at android.app.ActivityThread.main(ActivityThread.java:6334)
>                                                                at java.lang.reflect.Method.invoke(Native Method)
>                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
> 10-08 18:18:52.366 7977-7977/com.ceci E/AndroidRuntime: FATAL EXCEPTION: main
>                                                         Process: com.ceci, PID: 7977
>                                                         java.lang.RuntimeException: Cannot convert object of type class java.lang.Long
>                                                             at io.invertase.firebase.firestore.FirestoreSerialize.putValue(FirestoreSerialize.java:200)
>                                                             at io.invertase.firebase.firestore.FirestoreSerialize.objectMapToWritable(FirestoreSerialize.java:124)
>                                                             at io.invertase.firebase.firestore.FirestoreSerialize.snapshotToWritableMap(FirestoreSerialize.java:35)
>                                                             at io.invertase.firebase.firestore.RNFirebaseFirestoreDocumentReference$2.onComplete(RNFirebaseFirestoreDocumentReference.java:72)
>                                                             at com.google.android.gms.tasks.zzf.run(Unknown Source)
>                                                             at android.os.Handler.handleCallback(Handler.java:751)
>                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                             at android.os.Looper.loop(Looper.java:154)
>                                                             at android.app.ActivityThread.main(ActivityThread.java:6334)
>                                                             at java.lang.reflect.Method.invoke(Native Method)
>                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

and if i trying to fetch similar data through firebase.database(), everything work ok

why is this happen?

### Environment

1. Application Target Platform: Android

2. Development Operating System: Windows 10

3. Build Tools: Android Studio 2.3.3

4. React Native version: 0.48.4

5. RNFirebase Version: 3.0.2

6. Firebase Module: firestore

**Comment by Salakar** [comment]
@psycura Pushed up a fix for this now, 

Could you try installing the latest version of the repo by running:

npm install --save https://github.com/invertase/react-native-firebase.git

and confirm it's working now?

Thanks

**Comment by psycura** [comment]
i did
 npm install --save https://github.com/invertase/react-native-firebase.git

also gradle complete build an app
but error still exist , now slightly different 

> 10-08 19:09:34.732 15014-15014/com.ceci E/UncaughtException: java.lang.RuntimeException: Cannot convert object of type class com.google.android.gms.internal.zzegf
>                                                                  at io.invertase.firebase.firestore.FirestoreSerialize.objectArrayToWritable(FirestoreSerialize.java:165)
>                                                                  at io.invertase.firebase.firestore.FirestoreSerialize.putValue(FirestoreSerialize.java:202)
>                                                                  at io.invertase.firebase.firestore.FirestoreSerialize.objectMapToWritable(FirestoreSerialize.java:124)
>                                                                  at io.invertase.firebase.firestore.FirestoreSerialize.snapshotToWritableMap(FirestoreSerialize.java:35)
>                                                                  at io.invertase.firebase.firestore.RNFirebaseFirestoreDocumentReference$2.onComplete(RNFirebaseFirestoreDocumentReference.java:72)
>                                                                  at com.google.android.gms.tasks.zzf.run(Unknown Source)
>                                                                  at android.os.Handler.handleCallback(Handler.java:751)
>                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                  at android.os.Looper.loop(Looper.java:154)
>                                                                  at android.app.ActivityThread.main(ActivityThread.java:6334)
>                                                                  at java.lang.reflect.Method.invoke(Native Method)
>                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
> 10-08 19:09:35.003 15014-15014/com.ceci E/AndroidRuntime: FATAL EXCEPTION: main
>                                                           Process: com.ceci, PID: 15014
>                                                           java.lang.RuntimeException: Cannot convert object of type class com.google.android.gms.internal.zzegf
>                                                               at io.invertase.firebase.firestore.FirestoreSerialize.objectArrayToWritable(FirestoreSerialize.java:165)
>                                                               at io.invertase.firebase.firestore.FirestoreSerialize.putValue(FirestoreSerialize.java:202)
>                                                               at io.invertase.firebase.firestore.FirestoreSerialize.objectMapToWritable(FirestoreSerialize.java:124)
>                                                               at io.invertase.firebase.firestore.FirestoreSerialize.snapshotToWritableMap(FirestoreSerialize.java:35)
>                                                               at io.invertase.firebase.firestore.RNFirebaseFirestoreDocumentReference$2.onComplete(RNFirebaseFirestoreDocumentReference.java:72)
>                                                               at com.google.android.gms.tasks.zzf.run(Unknown Source)
>                                                               at android.os.Handler.handleCallback(Handler.java:751)
>                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                               at android.os.Looper.loop(Looper.java:154)
>                                                               at android.app.ActivityThread.main(ActivityThread.java:6334)
>                                                               at java.lang.reflect.Method.invoke(Native Method)
>                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by Salakar** [comment]
@psycura hmm looks like another data type, do you have a sample of your data we could use?

**Comment by psycura** [comment]
Structure is very simple:
3 root collections:

- decisions

- quizzes

- reporters
reporters include DOC`s:

{
    "reporters": {
        "GT1iukjZefZFbLmJvwXJ5fkB8mF2": {
            "address": "dfdsfsdf",
            "email": "test@gmail.com",
            "firstName": "Eugene",
            "id": "GT1iukjZefZFbLmJvwXJ5fkB8mF2",
            "lastName": "Asdfsdf",
            "manager": "",
            "message": "תודה שהצטרפת לצוות שעושה עבודה חשובה במעקב אחר ביצוע החלטות",
            "phone": "9654545434",
            "placeOfReport": "krayot",
            "quizzes": ["flddffe"],
            "quizzesRef": ["quizzes/vBWjuY6vbVJXnkqoRGxz"], 
            "status": "active"
        }
    }
}

pay attention to the quizzesRef field - this is array with elements type REF

Its look like this:
![screenshot-console firebase google com-2017-10-08-19-28-45-352](https://user-images.githubusercontent.com/22491732/31318698-089332f6-ac5f-11e7-906e-25832d4cda0d.png)

**Comment by Salakar** [comment]
Ah I guess then the type it's having trouble with is the refs, @chrisbianca is working on adding support for refs, see https://github.com/invertase/react-native-firebase/issues/468 

I'll close this issue as the `Long` data type issue has been fixed, lets move the ref problem over to the other issue. 

Thanks,

**Comment by psycura** [comment]
Thank you, now another issue - i`ve deleted the fields with REF`s array, and now application don`t crash anymore, but, now she`s stuck on the .get() request.
And as you see in my code example i have this part:

```
.get ( ( snapshot ) => {
                 console.log ( 'snapshot', snapshot.data () );
             } )
     }
```

so issue is, that app doesn`t display the console.log message - so i feel , like the .get method is not fired at all

**Comment by Salakar** [comment]
No worries, we've all done that before :) keep an eye on the ref issue and we'll get it sorted as soon as possible

**Comment by chrisbianca** [comment]
@psycura As an FYI, the issue you saw with arrays of references is actually an issue with the Firestore SDK itself and how it is deserializing DocumentReference.

I have logged this with Google here: https://groups.google.com/forum/#!topic/google-cloud-firestore-discuss/bk3oX1RIleU
