### ISSUE TITLE
[🐛] Crashlytics - sending crashes in debug mode

### ISSUE THREAD

**Issue by waqas19921** [invertase/react-native-firebase#4793]
I have used crashlytics library and it is sending crashes in debug mode.

According to documentation in debug crashes should not be sent.
https://rnfirebase.io/crashlytics/usage#enable-debug-crash-logs

i have set flag `crashlytics_debug_enabled` to false and not working.

I have seen that in this commit 
https://github.com/invertase/react-native-firebase/commit/cad58e178b43dea461e17fa4a0a3fecd507ba68a
the debug flag code is completely removed and this has broken the functionality.

**Comment by mikehardy** [comment]
Strange - I thought this was a duplicate but I can't find another issue to reference.
This does look like a problem
There are a couple recent PRs that show how to add (re-add!?) plist/android manifest keys if you want to make a PR? 

It is actually a pretty small change but the fastest way to fix it is to post a PR for testing

example https://github.com/invertase/react-native-firebase/pull/4730/files

but using a default value in the gradle change, I just added in case firebase.json is there but the key is missing https://github.com/invertase/react-native-firebase/pull/4791/files

10-20 lines of code no more, I'm thinking
