### ISSUE TITLE
[📚][Auth] Google sign in guide problems

### ISSUE THREAD

**Issue by BjoernRave** [invertase/react-native-firebase#4797]
## Documentation Feedback

In the docs it says
```
Before triggering a sign-in request, you must initialize the Google SDK using your any required scopes
and the webClientId, which can be found in the android/app/google-services.json file as the
client/oauth_client/client_id property (the id ends with .apps.googleusercontent.com).
```

However the key found there is an `androidKey` not a `webKey`.

When using the key found in `google-services.json` I get a `DEVELOPER_ERROR` in the `react-native-google-signin/google-signin` lib.

The https://github.com/react-native-google-signin/google-signin docs say it needs to be a `webKey`. However when I copy the `webKey` I have in my credentials I get:

```
error NativeFirebaseError: [auth/invalid-credential] The supplied auth credential is malformed or has
expired. [ Invalid Idp Response: the Google id_token is not allowed to be used with this application.
Its audience (OAuth 2.0 client ID) is xxxxx.apps.googleusercontent.com, which is not authorized to be
used in the project with project_number: yyyyyyy. ]
```

**Comment by BjoernRave** [comment]
I also just realized, that the `project_number` in the error message does not match with the project number of my firebase project and I have no idea where it's taking that `project_number` from

**Comment by mikehardy** [comment]
This sounds like some sort of project-specific error @BjoernRave if you are still experiencing this and have some proposed change you can perhaps make a PR to the docs? I have no problem using google sign in with my app though and I believe I Just followed the guide
