### ISSUE TITLE
Dynamic Link not recognising iOS app at all

### ISSUE THREAD

**Issue by b8ne** [invertase/react-native-firebase#4801]
## Issue

I have implemented Dynamic Links on both iOS and Android.  Android is working perfectly, however iOS is not working at all.  In debug mode links go to the app store, and asked to download the app (i.e. not registering that the app is installed), when running release mode or from the store, links go to the app store and asked to Open the app.  When opened, the app opens without registering a dynamic link.

Javascript implementation is also as per docs, and considering links work on Android I can't see any issues there.

I have tried with links generated in the FB console, and those generated via REST API.

I am using a custom domain and have followed all steps mentioned in the [docs](https://rnfirebase.io/dynamic-links/usage#installation)

- [x] 'https://xxxxxx.swiss8.org/apple-app-site-association' displays correctly
- [x] Provisioning profile has 'Associated Domains' enabled 
![Screen Shot 2021-01-20 at 8 27 19 pm](https://user-images.githubusercontent.com/19263633/105154721-ee1e9580-5b5d-11eb-939e-e3b1c05da400.png)
- [x] Info tab has URL Type added
![Screen Shot 2021-01-20 at 8 23 29 pm](https://user-images.githubusercontent.com/19263633/105154195-689ae580-5b5d-11eb-988e-f7a541861fa1.png)
- [x] FirebaseDynamicLinksCustomDomains added to info.plist
![Screen Shot 2021-01-20 at 8 27 49 pm](https://user-images.githubusercontent.com/19263633/105154782-fd054800-5b5d-11eb-9433-5faf2c9f42ca.png)

I have searched the issue and found a few older threads around AppDelegate.m changes, however it appears the v10.1.0 version I am using implements automatic/linked listeners? Am I missing something that isn't in the docs or is there a bug in this version?

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "Swiss8",
  "version": "4.1.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "node ./FixNodeModulesForXCode12.js"
  },
  "dependencies": {
    "@invertase/react-native-apple-authentication": "^1.1.2",
    "@monterosa/react-native-parallax-scroll": "^1.8.0",
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/datetimepicker": "^3.0.6",
    "@react-native-community/push-notification-ios": "^1.4.0",
    "@react-native-firebase/analytics": "^10.1.0",
    "@react-native-firebase/app": "^10.1.0",
    "@react-native-firebase/dynamic-links": "^10.1.0",
    "@react-native-firebase/in-app-messaging": "^10.1.0",
    "@react-native-firebase/messaging": "^10.1.0",
    "country-codes-list": "^1.6.7",
    "lodash": "^4.17.20",
    "moment": "^2.27.0",
    "moment-timezone": "^0.5.31",
    "normalizr": "^3.6.0",
    "prop-types": "^15.7.2",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-action-button": "^2.8.5",
    "react-native-animated-circular-progress": "^1.0.6",
    "react-native-animated-numbers": "^0.2.0",
    "react-native-code-push": "^6.3.0",
    "react-native-device-info": "^5.6.3",
    "react-native-elements": "^2.0.4",
    "react-native-fast-image": "^8.3.2",
    "react-native-fbsdk": "^2.0.0",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-keyboard-aware-scrollview": "^2.1.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localize": "^1.4.0",
    "react-native-markdown-display": "^6.1.6",
    "react-native-navigation": "^6.10.1",
    "react-native-reanimated": "^1.13.2",
    "react-native-responsive-fontsize": "^0.5.0",
    "react-native-restart": "0.0.17",
    "react-native-rewards": "^1.0.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-sound-player": "^0.10.4",
    "react-native-svg": "^12.1.0",
    "react-native-svg-charts": "^5.4.0",
    "react-native-swipeable-row": "^0.8.1",
    "react-native-timeago": "^0.5.0",
    "react-native-vector-icons": "^7.0.0",
    "react-native-video": "^4.4.5",
    "react-native-video-controls": "^2.6.0",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "seamless-immutable": "^7.1.4",
    "semver": "^7.3.2",
    "validate.js": "^0.13.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1",
    "reactotron-react-native": "^5.0.0",
    "reactotron-redux": "^3.1.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

```
</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Swiss8' do
  # Pods for Swiss8
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])




  target 'Swiss8Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Swiss8-tvOS' do
  # Pods for Swiss8-tvOS

  target 'Swiss8-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"
#import <ReactNativeNavigation/ReactNativeNavigation.h>

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTLinkingManager.h>

#import <Firebase.h>
#import <CodePush/CodePush.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  [ReactNativeNavigation bootstrapWithDelegate:self launchOptions:launchOptions];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [CodePush bundleURL];
#endif
}

@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `10.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Dynamic Links v10.1.0`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by AbdulmalickDimnang** [comment]
I was able to make it work on v10.4.1 and I added another URL Type (Identifier: anything, URL scheme: your custom domain)
Also, I added the follow code to AppDelegate.m

`- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  BOOL handled = NO;
  FIRDynamicLink *dynamicLink = [[FIRDynamicLinks dynamicLinks]
       dynamicLinkFromCustomSchemeURL:url];
    if (dynamicLink) {
      if (dynamicLink.url) {
        handled = [RCTLinkingManager application:application
          openURL:dynamicLink.url options:options];
        }
    }
    if(!handled) {
      handled = [RCTLinkingManager application:application openURL:url
          options:options];
    }
    return handled;
//return [RCTLinkingManager application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application
continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)
   (NSArray<id<UIUserActivityRestoring>> *
   _Nullable))restorationHandler
{
  // I am passing the resolved url to both RCTLinking Manager and
  // Firebase Dynamic Link handler here....
  BOOL handled = [[FIRDynamicLinks dynamicLinks]
      handleUniversalLink:userActivity.webpageURL
      completion:^(FIRDynamicLink * _Nullable dynamicLink,
      NSError * _Nullable error) {
    if (!error) {
      [RCTLinkingManager application:application
            openURL:dynamicLink.url options:nil];
     }
  }];
  if(!handled) {
  handled = [RCTLinkingManager application:application
       continueUserActivity:userActivity
       restorationHandler:restorationHandler];
  }
  return handled;
}`

However, my project doesn't accept any other custom domain for some reason, meaning I can't changing my current working custom domain to another even though, the custom domain is created on the same project

**Comment by mikehardy** [comment]
Use triple-backticks on separate lines to enclose code, specifying the language if possible to make them easy to read. I edited your comment to do so
This sounds like a project-specific problem likely something missing in plist or apple developer site config or perhaps just that it takes time sometimes for the url handling configurations that are apparently cloud based to distribute to the application (indicating an uninstall / reinstall / wait for ...a while? might work)

**Comment by AbdulmalickDimnang** [comment]
@mikehardy but I tested on a fresh project where I created a new firebase project with the first dynamic link prefix domain using .page.link
and everything went well. However, when i create another prefix domain using .page.link as well and try to use the new prefix domain, it just simply doesn't work. It only redirect the user to App Store but not the app even the app is installed. And when i rollback my configuration to the first prefix domain, everything goes smooth.
P.S. I checked both urls with /apple-app-site-association and both have the same values which are correct.

**Comment by luisfuertes** [comment]
I have a similar problem, have this versions
```
    "@react-native-firebase/analytics": "^10.6.4",
    "@react-native-firebase/app": "^10.3.0",
    "@react-native-firebase/dynamic-links": "^10.5.1",
    "@react-native-firebase/messaging": "^10.3.1",
    "react": "16.13.1",
    "react-native": "0.63.3",
```

On android all work fine but on iOS link only open app and in Xcode show this error:
```
[Firebase/Analytics][I-ACS023001] Deep Link does not contain valid required params. URL params: {
    apn = "{myAppBundleId}";
    link = "{myRedirectUrl}/forgot-password?code=YXHIpok3furOkbv5sAcX";
}
```

But cant get dynamic link data. Any idea?

**Comment by mikehardy** [comment]
@luis - do not mix and match versions 10.3 + 10.5 is not the way it works now, we are all on one version, should be 10.6.4 now for all packages - second, check the link via debugging https://firebase.google.com/docs/dynamic-links/debug

**Comment by luisfuertes** [comment]
@mikehardy thx for answer.

I update my versions:
```
    "@react-native-firebase/analytics": "^10.6.4",
    "@react-native-firebase/app": "^10.6.4",
    "@react-native-firebase/dynamic-links": "^10.6.4",
    "@react-native-firebase/messaging": "^10.6.4",
``` 

And my link debugging seems ok
<img width="301" alt="Captura de pantalla 2021-02-09 a las 12 41 03" src="https://user-images.githubusercontent.com/18212615/107358791-2158a280-6ad4-11eb-805d-ec4386acbaab.png">

App keeps opening with the link but it gives the same error in the xcode console:
```
7.5.0 - [Firebase/Analytics][I-ACS023001] Deep Link does not contain valid required params. URL params: {
    apn = "{myAppBundleId}";
    link = "{myRedirectUrl}/forgot-password?code=YXHIpok3furOkbv5sAcX";
}
```

Any idea to fix? I have to add some function to AppDelegate? I only configured associated domains:
<img width="1072" alt="Captura de pantalla 2021-02-09 a las 12 44 40" src="https://user-images.githubusercontent.com/18212615/107359185-ad6aca00-6ad4-11eb-9eeb-c561194fefde.png">

and url types:
<img width="1017" alt="Captura de pantalla 2021-02-09 a las 12 44 19" src="https://user-images.githubusercontent.com/18212615/107359194-b196e780-6ad4-11eb-96b0-9f4b088035d2.png">

**Comment by mikehardy** [comment]
Honestly I'm unsure. I followed the  documentation thoroughly when I implemented deep links in my app, including upstream iOS firebase google docs, and they work. There is a *lot* to configure, rely on their docs and test each little bit as you go, not on me scanning what you say you did or did not configure.

**Comment by luisfuertes** [comment]
Ok i fixed it.

The problem was my API KEY dont have permissions. I have to enabled **firebasedynamiclinks.googleapis.com** for my firebase API KEY

Other posible solution i found: 
```
1. Access the project on the [Cloud console](https://console.cloud.google.com/)
2. Go to APIs and Services > Credentials
3. Identify the client ID with the conflicting package name/bundle ID in the name (ex: [Android/iOS] client for (auto created by Google Service)
4. Edit the package name/bundle ID and save changes or delete the OAuth client ID
```

**Comment by mikehardy** [comment]
Fantastic!
