### ISSUE TITLE
[🐛] 🔥 Github Dependabot flags multiple security issues in yarn.lock

### ISSUE THREAD

**Issue by brandonJY** [invertase/react-native-firebase#4806]
## Issue

Github Dependabot flags multiple security issue in yarn.lock

![image](https://user-images.githubusercontent.com/20021316/105275668-d3d6cd00-5bda-11eb-9c77-cf28690f447a.png)
![image](https://user-images.githubusercontent.com/20021316/105275688-d9341780-5bda-11eb-9833-6f209cc81a67.png)

---

**Comment by mikehardy** [comment]
Hi there! Do you have an indication of what the root dependencies are that bring in the problematic dependencies and/or a PR to update them?

**Comment by brandonJY** [comment]
> Hi there! Do you have an indication of what the root dependencies are that bring in the problematic dependencies and/or a PR to update them?

Hi @mikehardy , sorry. I don't have it yet.  I am new to this repo and still try to exploring here. :)
