### ISSUE TITLE
[🐛] [auth/internal-error] An internal error has occurred, please try again

### ISSUE THREAD

**Issue by tranduy1401384** [invertase/react-native-firebase#4807]
I have got an issue [auth/internal-error] An internal error has occurred, please try again 
when i use function signInWithPhoneNumber firebase.
Although i have enabled Sign-in method with Phone in Fibase console
![image](https://user-images.githubusercontent.com/34645003/105314912-21f6cb00-5bf1-11eb-8926-5da96c98a279.png)

this only happens with some device on ios.
someone tell me the solution. please!

version firebase i'm using 

"@react-native-firebase/app": "^7.2.1", 
"@react-native-firebase/auth": "^8.0.5",
-----
"react": "16.9.0",
"react-native": "0.61.5",

**Comment by mikehardy** [comment]
Hi there! There is no support provided for old versions, please update to current

You have skipped the issue template, we close issues like that as the required information to troubleshoot is not present

You may need to re-download the plist file for your project after upgrading. "auth issues only on some phones" means those phones might be going into the "captcha" flow, make sure you have followed all the documentation regarding iOS from the upstream firebase docs and on rnfirebase.io
