### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by ksielyov** [invertase/react-native-firebase#4816]
I was followed all the steps https://rnfirebase.io/

My App.js 

`import React, {useEffect} from 'react';

import NavigationApp from './NavigationApp';
import {NavigationContainer} from '@react-navigation/native';

import {Voximplant} from 'react-native-voximplant';

import auth from '@react-native-firebase/app';
import messaging, {firebase} from '@react-native-firebase/messaging';

const App: () => React$Node = () => {
    let clientConfig = {};
    clientConfig.enableVideo = true; // Android only option
    clientConfig.saveLogsToFile = true; // iOS only option
    let client = Voximplant.getInstance(clientConfig);

    messaging().setBackgroundMessageHandler(async remoteMessage => {
        console.log('Message handled in the background!', remoteMessage);
    });
    let requestUserPermission = async () => {
        const authStatus = await messaging().requestPermission();
        const enabled =
            authStatus === messaging.AuthorizationStatus.AUTHORIZED ||
            authStatus === messaging.AuthorizationStatus.PROVISIONAL;

        if (enabled) {
            console.log('Authorization status:', authStatus);
            getFcmToken();

            messaging().onMessage(async remoteMessage => {
                console.log('A new FCM message arrived!', JSON.stringify(remoteMessage));
            });

        }
    };

    let getFcmToken = async () => {
        const fcmToken = await messaging().getToken();

        if (fcmToken) {
            console.log(fcmToken);
            console.log('Your Firebase Token is:', fcmToken);
        } else {
            console.log('Failed', 'No token received');
        }
    };

    useEffect(() => {
        requestUserPermission();
    }, []);

    return (
        <NavigationContainer>
            <NavigationApp/>
        </NavigationContainer>
    );
};

export default App;`

**Comment by mikehardy** [comment]
If you don't follow the template, we close the issue with little extra comment.
Create a fully working demonstration project using this script https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

Compare the output with whatever you have done in your project

The difference / reason your project is not working will be in the difference
