### ISSUE TITLE
phone auth AUTO_VERIFIED issue on Android

### ISSUE THREAD

**Issue by jcharbo** [invertase/react-native-firebase#482]
Hi, I'm using the latest react-native-firebase in rn 48 on a real android device.  

The first time I log in using verifyPhoneNumber everything works great.  The subsequent login attempts return firebase.auth.PhoneAuthState.AUTO_VERIFIED.  The contents of the return are null so my understanding of the docs is that I should ignore it and proceed normally.  

Wouldn't proceeding normally mean waiting for the text message with the code?  If so, I'm never receiving a code.  Please advise.

thanks
Jeremey

**Comment by Salakar** [comment]
Closing in favour of #464
