### ISSUE TITLE
[🐛] setUserProperty not working on some devices

### ISSUE THREAD

**Issue by vishwas247** [invertase/react-native-firebase#4828]
## Issue

Hi,
 
There is some strange issue. I am checking firebase analytics with user property it is working on most of the devices but somehow it is not working on Samsung J5 prime phone.  It is not showing when checking stream view and snapshot. I am continuously monitoring data on stream view and it is working fine until the device is Samsung and same is happening on most of the devices of live app. 
 
Firebase Project ID - buyers-28eee
Firebase SDK version - "@react-native-firebase/analytics": "^10.2.0"
MCVE that I can run locally -  analytics().setUserProperty('email',userEmail)
Screenshot/s of DebugView - 
Debug logs. Enable verbose logging (Android/iOS) to retrieve these

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

    "@react-native-firebase/analytics": "^10.2.0",

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

Not working on Samsung device J5 prime

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 60.93 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0. - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found```

<!-- change `[ ]` to `[x]` to select an option(s) -->

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
  "@react-native-firebase/analytics": "^10.2.0",
    "@react-native-firebase/app": "^10.4.0",
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
Firebase Project ID - buyers-28eee

</p>
</details>

<!-- Thanks for reading this far down ❤️  -->
<!-- High quality, detailed issues are much easier to triage for maintainers -->

<!-- For bonus points, if you put a 🔥 (:fire:) emojii at the start of the issue title we'll know -->
<!-- that you took the time to fill this out correctly, or, at least read this far -->

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Please update to current stable - 10.5.x (and make sure you are using the associated firebase-android-sdk 26.3.0) and reproduce

There are analytics debugging flags you can and should turn on to help diagnose, have you tried them? https://firebase.google.com/docs/analytics/debugview#android

Have you looked at the related issues? https://github.com/invertase/react-native-firebase/issues/4010 - sometimes there are inconsistencies in debug view

If it persists, try to reproduce directly with the firebase-android-sdk using their quickstart, as this will likely be an upstream issues in firebase-android-sdk, meaning nothing we do here will likely help, and you'll likely need to file an issue there assuming a minimal reproduction from their quickstart also shows the problem https://github.com/firebase/quickstart-android/tree/master/analytics
