### ISSUE TITLE
ANDROID: Cannot convert object of type class java.util.Date

### ISSUE THREAD

**Issue by psycura** [invertase/react-native-firebase#483]
Hello, guys and thank you for support.

I have another issue: Trying to query list of documents from collection:
 
```
firebase.firestore().where(`reporters.${this.user.id}`, '==', true)
            .get()
            .then((snapshot) => {
                console.log('snap querys', snapshot);
            })

```

and it crash my app, with error in logcat:

> 10-10 13:59:17.003 6202-6202/com.ceci E/UncaughtException: java.lang.RuntimeException: Cannot convert object of type class java.util.Date
>                                                                at io.invertase.firebase.firestore.FirestoreSerialize.putValue(FirestoreSerialize.java:204)
>                                                                at io.invertase.firebase.firestore.FirestoreSerialize.objectMapToWritable(FirestoreSerialize.java:124)
>                                                                at io.invertase.firebase.firestore.FirestoreSerialize.snapshotToWritableMap(FirestoreSerialize.java:35)
>                                                                at io.invertase.firebase.firestore.FirestoreSerialize.documentChangeToWritableMap(FirestoreSerialize.java:108)
>                                                                at io.invertase.firebase.firestore.FirestoreSerialize.documentChangesToWritableArray(FirestoreSerialize.java:82)
>                                                                at io.invertase.firebase.firestore.FirestoreSerialize.snapshotToWritableMap(FirestoreSerialize.java:52)
>                                                                at io.invertase.firebase.firestore.RNFirebaseFirestoreCollectionReference$1.onComplete(RNFirebaseFirestoreCollectionReference.java:59)
>                                                                at com.google.android.gms.tasks.zzf.run(Unknown Source)
>                                                                at android.os.Handler.handleCallback(Handler.java:751)
>                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                at android.os.Looper.loop(Looper.java:154)
>                                                                at android.app.ActivityThread.main(ActivityThread.java:6334)
>                                                                at java.lang.reflect.Method.invoke(Native Method)
>                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
> 10-10 13:59:17.292 6202-6202/com.ceci E/AndroidRuntime: FATAL EXCEPTION: main
>                                                         Process: com.ceci, PID: 6202
>                                                         java.lang.RuntimeException: Cannot convert object of type class java.util.Date
>                                                             at io.invertase.firebase.firestore.FirestoreSerialize.putValue(FirestoreSerialize.java:204)
>                                                             at io.invertase.firebase.firestore.FirestoreSerialize.objectMapToWritable(FirestoreSerialize.java:124)
>                                                             at io.invertase.firebase.firestore.FirestoreSerialize.snapshotToWritableMap(FirestoreSerialize.java:35)
>                                                             at io.invertase.firebase.firestore.FirestoreSerialize.documentChangeToWritableMap(FirestoreSerialize.java:108)
>                                                             at io.invertase.firebase.firestore.FirestoreSerialize.documentChangesToWritableArray(FirestoreSerialize.java:82)
>                                                             at io.invertase.firebase.firestore.FirestoreSerialize.snapshotToWritableMap(FirestoreSerialize.java:52)
>                                                             at io.invertase.firebase.firestore.RNFirebaseFirestoreCollectionReference$1.onComplete(RNFirebaseFirestoreCollectionReference.java:59)
>                                                             at com.google.android.gms.tasks.zzf.run(Unknown Source)
>                                                             at android.os.Handler.handleCallback(Handler.java:751)
>                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                             at android.os.Looper.loop(Looper.java:154)
>                                                             at android.app.ActivityThread.main(ActivityThread.java:6334)
>                                                             at java.lang.reflect.Method.invoke(Native Method)
>                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
> 
> 

i have 2 fields of type TIMESTAMP in the document, and they cause to crash, when i delete them, everything work

### Environment

1. Application Target Platform: Android

2. Development Operating System: Windows 10

3. Build Tools: Android Studio 2.3.3

4. React Native version: 0.48.4

5. RNFirebase Version: 3.0.2

6. Firebase Module:

**Comment by chrisbianca** [comment]
@psycura I am working on this as we speak - will hopefully have something up and running in the next day or so

**Comment by chrisbianca** [comment]
@psycura I've just pushed up support for Dates, DocumentReference, GeoPoints. It would be great if you could test with the latest version of the code and let me know if there are any issues before we release over the next few days.

You can install by doing the following:

`npm install --save https://github.com/invertase/react-native-firebase.git`

Please re-open if there are still issues with Dates, or you find something else isn't working.

**Comment by psycura** [comment]
Thank you , chrisbianca, for so operative work.
I`ve added 2 test fields to my document - timestamp and reference, 
the good news is that app not crashing anymore,
the not so good news, is that fetched data not include this fields... strange

**Comment by chrisbianca** [comment]
Have you created the Document in JS or in the console?
Can you show me how how your Document is structured and the JS code that you're using to retrieve it?

**Comment by psycura** [comment]
UPD: Sorry my fault, made a changes in a wrong place - everything work like a charm )))

**Comment by chrisbianca** [comment]
Excellent! :D

**Comment by chrisbianca** [comment]
This is now live as part of the v3.0.3 release
