### ISSUE TITLE
[🐛] Bug with FieldPath, where & update behavior

### ISSUE THREAD

**Issue by RohovDmytro** [invertase/react-native-firebase#4836]
1. When creating a path using `FieldPath` class and `where` it works just fine.

2. When creating a path using `FieldPath` class and update query it does not work as intended.
![image](https://user-images.githubusercontent.com/1548235/106266384-06af3f80-6231-11eb-9c2c-219d0f11dfde.png)

What is wrong is that it creates a deeply nested object in my database.

Note that my variable `email` contains dots. That is why I am using `FieldPath` class. It somehow escapes special characters. But not in case of an update call.

Meanwhile `where` query works fine.

![image](https://user-images.githubusercontent.com/1548235/106266553-3cecbf00-6231-11eb-861c-5adfbba6884d.png)

Thanks!

**Comment by mikehardy** [comment]
Hi there! First let me say this looks a real issue. I'm not disputing that.
But, you have really chopped up our issue template, not including what we ask for, and for things you did include you used graphics. These actions make it very difficult to help.

Here's the best way to move this forward I think. Either:

1) Create an App.js that be dropped into a completely clean project (like https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh and reproduce the issue (including creating the data that will trigger it, then demonstrates the error by printing it out in console.log or similar)

2) in your project where we already reproduce this, reach into node_modules and follow the API calls from javascript down to native (android and ios? just one? you deleted that template part...) logging out the arguments that come in, the arguments of the firebase-android-sdk/firebase-ios-sdk API calls, and logging the results and you might be able to fix it right there and submit a PR. Believe it or not, this could be like a 5 minute process so you might give it a shot?
