### ISSUE TITLE
[🐛] Interference / inconsistent behavior with other services issuing push notifications

### ISSUE THREAD

**Issue by maxkomarychev** [invertase/react-native-firebase#4839]
## Issue

I am working on a project which uses firebase as a primary way of delivering push notifications to the app. 

At the same time there is a number of other services (including but not limited to https://www.braze.com/) which issue pushes and we want them to be handled. In addition to react-native-firebase we are using react-native-push-notification in order to handle other pushes.

The problem we experience is that in different scenarios different methods of `@react-native-firebase/messaging` are called and also in certain scenarios swizzling of `react-native-firebase` prevents pushes to be propagated to react-native-push-notification`.

Please find a table below showing experienced difference. I compared 2 scenarios of how test pushes are handled by the app on both platforms when application is in foreground and background respectively:

legend:

☝️ - tap on banner
🖼️ - banner visible
🛑 - no banner
🎙️ - callbacks invoked

### ios

|state of the app|firebase	|braze|
|-|-|-|
|foreground	| 🛑 no banner shown, 🎙️ `firebase.messaging().onMessage` is called|🖼️banner is shown, ☝️ TAP on banner invokes `react-native-push-notification::onNotification` |
|background|🖼️banner is shown, ☝️ TAP on banner invokes 🎙️`firebase.messaging().onNotificationOpenedApp` followed by 🎙️`react-native-push-notification::onNotification`|🖼️banner is shown, ☝️ TAP on banner invokes 🎙️ `react-native-push-notification::onNotification`|

### android

|state of the app|firebase	|braze|
|-|-|-|
|foreground|🛑no banner, 🎙️`firebase.messaging().onMessage`, followed by 🎙️`react-native-push-notification::onNotification`|🖼️ banner visible, 🎙️`firebase.messaging().onMessage` is called immediately, ☝️ **TAP does not trigger any other callbacks** ❗ ❗ ❗ 
|background|🖼️ banner is visible simultaneously with 🎙️ `firebase.messaging().setBackgroundMessageHandler` is invoked immediately,  ☝️ TAP triggers 🎙️`react-native-push-notification::onNotification` followed by 🎙️`firebase.messaging().onNotificationOpenedApp`|🖼️  banner is shown, 🎙️ `firebase.messaging().setBackgroundMessageHandler` is called immediately, ☝️**TAP does not trigger any other callbacks** ❗ ❗ ❗ |

**expected behavior:** 
1. I would like to retain control on whether a notification should be shown or no (swizzling issue of appdelegate)
2. I would like to have regular notification handler consistently regardless of where notification came from (currently a problem on android with non-fcm notifications)

### initial research

after digging around a bit I found at least one spot which breaks expected behavior on ios - imo swizzling is in incorrect - by forcing a callback `willPresentNotification` to `UNNotificationPresentationOptionNone` it makes notification never appear in notification center on ios and preventing it to be later forwarded to `react-native-push-notification`

#### ios, firebase, foreground

I tried to dig into codebase to find places where it might be broken, one suspicious place I found in https://github.com/invertase/react-native-firebase/blob/62ee961d6ebffe529bdfa938443e1f25a0201e0e/packages/messaging/ios/RNFBMessaging/RNFBMessaging+UNUserNotificationCenter.m#L66-L85:

in this block a completion handler is (potentially) called twice:
1. first https://github.com/invertase/react-native-firebase/blob/62ee961d6ebffe529bdfa938443e1f25a0201e0e/packages/messaging/ios/RNFBMessaging/RNFBMessaging+UNUserNotificationCenter.m#L77
2. then in https://github.com/invertase/react-native-firebase/blob/62ee961d6ebffe529bdfa938443e1f25a0201e0e/packages/messaging/ios/RNFBMessaging/RNFBMessaging+UNUserNotificationCenter.m#L81 or https://github.com/invertase/react-native-firebase/blob/62ee961d6ebffe529bdfa938443e1f25a0201e0e/packages/messaging/ios/RNFBMessaging/RNFBMessaging+UNUserNotificationCenter.m#L83

what is the reasoning to suppress visual notification and force it to `UNNotificationPresentationOptionNone` in case if notification arrived from FCM?

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
        "@react-native-community/push-notification-ios": "^1",
        "@react-native-community/viewpager": "^3.3.0",
        "@react-native-firebase/analytics": "^10.5.1",
        "@react-native-firebase/app": "^10.5.0",
        "@react-native-firebase/iid": "^10.5.0",
        "@react-native-firebase/messaging": "^10.5.1",
        "react-native-push-notification": "^7",
```
#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
  // Required for the register event.
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
  {
    
    const unsigned *tokenBytes = [deviceToken bytes];
    NSString *hexToken = [NSString stringWithFormat:@"%08x%08x%08x%08x%08x%08x%08x%08x",
                         ntohl(tokenBytes[0]), ntohl(tokenBytes[1]), ntohl(tokenBytes[2]),
                         ntohl(tokenBytes[3]), ntohl(tokenBytes[4]), ntohl(tokenBytes[5]),
                         ntohl(tokenBytes[6]), ntohl(tokenBytes[7])];

    NSLog(@"### apns token %@", [deviceToken base64EncodedStringWithOptions:NSDataBase64Encoding76CharacterLineLength]);
    NSLog(@"### hex token %@", hexToken);
    [RNCPushNotificationIOS didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
    [FIRMessaging messaging].APNSToken = deviceToken;
  }

  // Required for the notification event. You must call the completion handler after handling the remote notification.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
  {
    [RNCPushNotificationIOS didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
  }

  // Required for the registrationError event.
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
  {
    [RNCPushNotificationIOS didFailToRegisterForRemoteNotificationsWithError:error];
  }

//Called when a notification is delivered to a foreground app.
-(void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
  NSLog(@"%@", notification.request.content.userInfo);
  completionHandler(UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge);
}

// IOS 10+ Required for localNotification event
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)(void))completionHandler
{
  [RNCPushNotificationIOS didReceiveNotificationResponse:response];
  completionHandler();
}
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 316.17 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /Users/max/.rvm/gems/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 3.6.6 - /Users/max/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^10.5.0`
- **`Firebase` module(s) you're using that has the issue:**
  - messaging
- **Are you using `TypeScript`?**
  - `Y` & `4.0.5`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
@Ehesp or @Salakar one very specific question you could help with here: "what is the reasoning to suppress visual notification and force it to UNNotificationPresentationOptionNone in case if notification arrived from FCM?"

@maxkomarychev thanks for the very detailed testing report, I need to take some time to give it the thought it deserves. Let me say that I am in general strongly in favor of correct interoperation (of course!) so if there is some/any error in how we do things, I will happily merge any PR to correct once we figure out best course of action. So if you want to speculatively try things it's reasonable to assume that if they actually fix problems they will be merged here

**Comment by maxkomarychev** [comment]
meanwhile I tested my hypothesis: removing this line https://github.com/invertase/react-native-firebase/blob/62ee961d6ebffe529bdfa938443e1f25a0201e0e/packages/messaging/ios/RNFBMessaging/RNFBMessaging+UNUserNotificationCenter.m#L77 does fix the problem: I am getting my banner back as well as I can receive callback from ios and forward it into `react-native-push-notification` with this code in AppDelegate.m:

```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)(void))completionHandler
{
  [RNCPushNotificationIOS didReceiveNotificationResponse:response];
  completionHandler();
}
```

**Comment by Ehesp** [comment]
I need to read this properly, however I can answer this:

> one very specific question you could help with here: "what is the reasoning to suppress visual notification and force it to UNNotificationPresentationOptionNone in case if notification arrived from FCM?

Android doesn't support displaying a notification (visibly) if the current app is in the foreground. We did this because we wanted iOS to be consistent - there is a huge history with notifications and it's a massive pain to debug/test etc, so it was an attempt to keep the experience the same on both platforms.

On FlutterFire, we expose a way to [set these options on iOS dynamically](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart#L318). I'd be inclined to also add this into RNFB, it should be a fairly "simple" task?

**Comment by mikehardy** [comment]
I'll appreciate any deeper thought of course but I think you've already hit the heart of it - disabled for consistency, but already with some prior art in similar project (FlutterFire) addressing this exact problem. Which lends me to suggest to @maxkomarychev to think if you'd be willing to submit a PR that exposed the "consistency-by-default vs ability-to-specify" tradeoff by implementing that FlutterFire feature here?

**Comment by maxkomarychev** [comment]
> Which lends me to suggest to @maxkomarychev to think if you'd be willing to submit a PR that exposed the "consistency-by-default vs ability-to-specify" tradeoff by implementing that FlutterFire feature here?

I'll try. Could you please suggest a place where I can introduce such flag to be available in messaging module?

**Comment by mikehardy** [comment]
Sure, I'll do my best to help + collaborate @maxkomarychev 

I think the place to start is with a new method like the one in FlutterFire, dropped in here:

https://github.com/invertase/react-native-firebase/blob/a41cf3a8b271a5d1eb5574fd896cbf54add29533/packages/messaging/lib/index.js#L124

with a corresponding entry (for documentation purposes, noting it is iOS only) in the index.d.ts file

For platform android just throw saying "we don't support it"

For ios something like the FlutterFire implementation https://github.com/FirebaseExtended/flutterfire/blob/5fddc966a12d98cbe958ac03cddc93d4c99e5afe/packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m#L145 dropped in I think (maybe?) in here https://github.com/invertase/react-native-firebase/blob/a41cf3a8b271a5d1eb5574fd896cbf54add29533/packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m#L277

Then once the options are set so you can access them, I think you can use them to do what you need in the line you quoted above https://github.com/invertase/react-native-firebase/blob/62ee961d6ebffe529bdfa938443e1f25a0201e0e/packages/messaging/ios/RNFBMessaging/RNFBMessaging+UNUserNotificationCenter.m#L77

? This is kind of "thinking out loud" level of concreteness. I *think* that would work and seems okay at a first glance but as the person driving the change, if you feel differently or discover something please feel free to sketch something different out

**Comment by mikehardy** [comment]
I will note for completeness than when I'm just doing something simple, doing it in node_modules and posting a PR is most efficient. But for a real feature the development cycle using the test app is *way* more efficient for me.

I would strongly suggest to get that set up and use it so you have a lightning quick, test-first, code+retry loop locally - start by just adding a stub test here: https://github.com/invertase/react-native-firebase/blob/master/packages/messaging/e2e/messaging.e2e.js where you check the basic arguments to the function for type safety / platform support (throws android, tries to go native for ios) with that test set to ".only" and just keep re-running the tests app while you build the feature https://github.com/invertase/react-native-firebase/blob/master/tests/README.md

Probably a 15 minute investment to set up but in the end the feature will be rock solid. Every time I do it this way I discover two or three little edge cases my code did not handle that I would not have spotted in review, and they save me from getting bug reports after, while taking less total time to actually implement since the code/test/debug loop is so quick thus the strong recommendation

**Comment by mikehardy** [comment]
I'm going to close this for lack of progress but please understand 1) I'm happy to reopen and/or take a PR as discussed here! and 2) I totally understand that there are always 100 things to do and time to do 10 things, I'm not intending to make anyone feel bad by the close
