### ISSUE TITLE
[firestore] Differences between official realtime updates and implementation

### ISSUE THREAD

**Issue by DavidKuennen** [invertase/react-native-firebase#484]
I noticed some differences / complications for the implementation of realtime updates between react-native-firebase and the official docs.

Example Code: 

```javascript
firebase
    .firestore()
    .collection('rooms')
    .where(`users.${userId}`, '==', true)
    .onSnapshot((docs) => {
        docs.docChanges.forEach((change) => {
            // this is where it's different.. see below
        });
    });
```

I noticed the following differences when using `docs.docChanges`:

Official | react-native-firebase | 
--- | --- 
`change.doc.data()` | `change.doc.data` 
`change.doc.id` | `change.doc.path.split('/')[1]` 😅 

1. Application Target Platform: only tested on android
2. Development Operating System: Windows 10
3. Build Tools: Android Studio
4. React Native version: 0.48.4
5. RNFirebase Version: 3.0.2
6. Firebase Module: Firestore

**Comment by chrisbianca** [comment]
@DavidKuennen Good spot!  I've just resolved this and pushed up a change which will be released in our next patch release.  In the meantime, you can try it out by doing the following:

`npm install --save https://github.com/invertase/react-native-firebase.git`

**Comment by DavidKuennen** [comment]
Great, thanks @chrisbianca. 
I can use it like I do right now, so I'll wait for the next release and then just switch out a few lines of code. 😉

**Comment by chrisbianca** [comment]
This is now live as part of the v3.0.3 release
