### ISSUE TITLE
pod install --repo-update not working

### ISSUE THREAD

**Issue by LeonardoDrici** [invertase/react-native-firebase#4844]
Hello I am writing this because apparently when I run `pod install --repo-update` i get this error.

<img width="957" alt="Screenshot 2021-02-01 at 09 46 07" src="https://user-images.githubusercontent.com/53435344/106441751-57fa4180-6472-11eb-86d5-e6cb65987f84.png">

 I don't think it is a problem with my internet as my connection seems to work fine. Any feedback?

**Comment by mikehardy** [comment]
Cocoapods problems are for Cocoapods not RNFB, sorry. Does look like a network issue. Might be their mirror server
