### ISSUE TITLE
[🐛] Bug [Error: [auth/session-expired]

### ISSUE THREAD

**Issue by steniobarroso** [invertase/react-native-firebase#4846]
I'm having trouble authenticating by phone. this error is getting back to me [Error: [auth / session-expired] The sms code has expired. Please re-send the verification code to try again.]
I tried to check if the user is logged in that way but it returns me null.
Test authentication by firebase works

 `async function signInWithPhoneNumber(phoneNumber) {
    try {
        const confirmation = await auth().signInWithPhoneNumber(
          `+55${phoneNumber}`,
        );
    } catch (error) {
      console.log(error);
    }
  }`

async function confirmCode(phone) {
   
    try {
      confirm.confirm(code).then(async res => {
      await AsyncStorage.setItem('cellPhone', phone);
      navigation.navigate('NewPassword');
      }).catch(error =>{
        Alert.alert('Atenção','Message')
        console.log(error);
      });
      // 
    } catch (error) {
      auth().onAuthStateChanged(user => {
        if (user) { 
          navigation.navigate('NewPassword');
        }
      });
    }
  }

**Comment by mikehardy** [comment]
You deleted the template. One of the things you attest to in the template with a check mark is that you have searched the issues prior to posting. This is covered many times in the issues database I believe
