### ISSUE TITLE
[🐛][ 🔥] Cannot build in Android Studio after upgrading firebase/app past 9.0.0

### ISSUE THREAD

**Issue by jbienia** [invertase/react-native-firebase#4847]
## Issue

Describe your issue here

--- I'm unable to build in Android Studio after upgrading past "@react-native-firebase/app": "^8.4.7". When I do I receive the error below. I do not receive this error and am able to build fine on any earlier versions of react-native-firebase/app. It was not clear to me that I was missing anything when going through the release notes and looking at the breaking changes.

Error
Execution failed for task ':app:processDebugResources'.
> Problems reading data from Binary store in /private/var/folders/7w/ybpt01bn47j5q2xg5vrqn75r0000gn/T/gradle5226835182018207497.bin offset 0 exists? true
<img width="1228" alt="Screen Shot 2021-02-01 at 10 21 15 AM" src="https://user-images.githubusercontent.com/15094461/106500909-3a7ba680-6477-11eb-81ae-5b31cdbbcadf.png">

Corrupt serialized resolution result. Cannot find selected module (284) for constraint platform-runtime -> com.google.firebase:firebase-iid:21.0.0

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

{
  "name": "",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.6",
    "@react-native-firebase/app": "^9.0.0",
    "@react-native-firebase/auth": "^9.3.5",
    "@react-native-firebase/database": "^7.5.15",
    "@react-native-firebase/storage": "^7.4.14",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-gesture-handler": "^1.5.6",
    "react-native-media-controls": "^1.1.1",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.2",
    "react-native-screens": "^2.0.0-beta.2",
    "react-native-slider": "^0.11.0",
    "react-native-vector-icons": "^7.0.0",
    "react-native-video": "^4.4.5"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "6.8.0",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "metro-react-native-babel-preset": "^0.58.0",
  "react-test-renderer": "16.11.0"
}

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.1.2')
        classpath 'com.google.gms:google-services:4.3.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

```groovy
// N/A
```

#### `android/app/build.gradle`:
apply plugin: "com.android.application"
apply plugin: 'com.google.gms.google-services'

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation. If none specified and
 *   // "index.android.js" exists, it will be used. Otherwise "index.js" is
 *   // default. Can be overridden with ENTRY_FILE environment variable.
 *   entryFile: "index.android.js",
 *
 *   // https://reactnative.dev/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.tinysoultunes"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        multiDexEnabled true
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }
    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.tinysoultunes">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 4.27 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.4.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 10.0.1 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - "@react-native-firebase/app": "^9.0.0",
- **`Firebase` module(s) you're using that has the issue:**
  - `app`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
`npx react-native-clean-project` I think. This is a local environment issue, we run continuous integration which compiles everything on every change, and there are no build failures

You're development tools (Android Studio + Xcode) are out of date, perhaps updating Android Studio would help as well. Definitely take react-native-firebase to 10.5.x though, it's current.

**Comment by jbieniaFreshGrade** [comment]
Thanks for your response and all your work. I'll address the issues you've noted.

**Comment by sta-vanger** [comment]
I encountered this issue. I'm using the latest firebase/app - 10.5.0. Basically my android app is working (can compile, build and run in real device). After integrating the latest firebase/app by following this guide https://rnfirebase.io/ , I could no longer build the app and see this issue: Problems reading data from Binary store in /private/var/folders/7w/ybpt01bn47j5q2xg5vrqn75r0000gn/T/gradle5226835182018207497.bin

**Comment by sta-vanger** [comment]
@jbienia Were you able to resolve this?

**Comment by mikehardy** [comment]
@sta-vanger `npx react-native-clean-project`

**Comment by sta-vanger** [comment]
Hi @mikehardy , I already did this but still I encountered the same issue.

**Comment by sta-vanger** [comment]
This only happends on Android. Works fine on iOS.

**Comment by jbienia** [comment]
@sta-vanger I haven't been able to fix it. I've run 'npx react-native-clean-project' and am messing around with updating Gradle. It doesn't look to me like my developer tools are out of date. But I perhaps I'm missing something.  Everything works fine before 9.0.0 and everything after somehow breaks something with, I'm assuming, Gradle?

**Comment by jbienia** [comment]
@sta-vanger and @mikehardy it seems from firebase/app 9.0.0 and on there is a dependency on Firebase instance ID. If you add 'implementation "com.google.firebase:firebase-iid:21.0.0' to app/build.gradle in 'dependencies' you should be good to go.

**Comment by mikehardy** [comment]
Instance Is transitive dependency should be handled by the firebase bom but there was a bug with Auth module not bringing in browser dependency even though it was necessary. Are you confirming adding iid dependency explicitly fixes it?

**Comment by jbienia** [comment]
Yes. Adding the iid dependency explicitly fixed it. The dependency is needed for firebase/app 9.0.0 or greater. I'm now currently up to date with '10.5.*' and everything works fine.

**Comment by mikehardy** [comment]
Fascinating.

```
"@react-native-firebase/app": "^9.0.0",
"@react-native-firebase/auth": "^9.3.5",
"@react-native-firebase/database": "^7.5.15",
"@react-native-firebase/storage": "^7.4.14",
```

The way we discovered that firebase/auth needed androidx.browser was through a little-used combination of packages, where the more commonly used combination(s) meant that it was brought in so few people noticed it.

I think firebase/messaging (and likely firebase/analytics, maybe others) bring in iid and those are more-used combinations, your combination of packages above must (?) need iid but unexpectedly not have it.

I'll re-open this for investigation, it is likely an upstream issue but also may be worked around here. The iid dependency has had issues in the past, it appears to be a problem child https://github.com/firebase/firebase-android-sdk/issues/1077

**Comment by sta-vanger** [comment]
> @sta-vanger and @mikehardy it seems from firebase/app 9.0.0 and on there is a dependency on Firebase instance ID. If you add 'implementation "com.google.firebase:firebase-iid:21.0.0' to app/build.gradle in 'dependencies' you should be good to go.

I tried this workaround and it works in my end as well. I can now build & run my app in Android (real device). Thanks @jbienia & @mikehardy !

**Comment by mikehardy** [comment]
@sta-vanger may I ask what `@react-native-firebase` modules you are including? Trying to figure out exactly which module(s) need the iid dependency for a workaround / upstream logging

**Comment by mikehardy** [comment]
I just attempted and failed to reproduce this.
You can see the fully self-contained attempt on this branch of my rnfbdemo project: https://github.com/mikehardy/rnfbdemo/tree/iid-dependency-triage

If anyone can reproduce this, let me know, otherwise I'm going to consider this some kind of stale dependency somewhere, but it does not appear with a clean install on current versions using the app/auth/database/storage modules as indicated.

**Comment by sta-vanger** [comment]
Hi @mikehardy, I'm using this:
    "@react-native-firebase/app": "^10.6.3",
    "@react-native-firebase/messaging": "^10.6.3",

**Comment by mikehardy** [comment]
@sta-vanger you should be able to strip my repro demo down even smaller to show the reproduction then. If it doesn't reproduce then it's a local project problem of some sort but without reproduction I'm unable to fix it

**Comment by jbienia** [comment]
It seems to me that the issue appears when updating the firebase package(s). A clean install of the latest firebase modules appears to work fine, but updating '@react-native-firebase/app' from pre 9.0.0 to post 9.0.0 may surface the "bug"?

**Comment by mikehardy** [comment]
...which is the use case for `npx react-native-clean-project` - if something about the caching infrastructure of the 3-4 layers of build tools (metro, yarn/npm, gradle, javac, etc) under react-native-firebase has a coherency issue, but clean install works, I can't consider that a react-native-firebase problem - clean the project and move on is my stance on issues like that

**Comment by mikehardy** [comment]
still open for a clean reproduction, if there *is* something wrong I'll fix it again - can't reproduce + can't fix

**Comment by Streeterxs** [comment]
`npx react-native-clean-project` worked for me. Using the same modules as @sta-vanger 
```
    "@react-native-firebase/app": "^10.8.0",
    "@react-native-firebase/messaging": "^10.8.0",
```

**Comment by JoaoMosmann** [comment]
I was having the same issue.

The cause was a `implementation 'com.google.firebase:firebase-analytics:17.2.0'` at `android/app/build.gradle`

**Comment by MorenoJoshua** [comment]
Ran into this issue with the `Problems reading data from Binary store ...` message
Adding `implementation 'com.google.firebase:firebase-iid:21.1.0'` to `app/build.gradle` fixed it.

Using just `/app` and `/crashlytics` on latest versions

**Comment by mikehardy** [comment]
> 'com.google.firebase:firebase-iid:21.1.0' 

That's a deprecated dependency, nothing you do should be using it. Here's a demonstration script, with comments, showing how to integrate the current version with current version of react-native https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh - if you stray from that path, results are undefined

**Comment by code-by** [comment]
have same issue
can't build after installing current version of firebase/app core
yarn add @react-native-firebase/app
`npx react-native-clean-project` trying run `brew` which not exists on ubuntu (

**Comment by mikehardy** [comment]
@code-by why are you posting on old closed issues? Just curious.
react-native-clean-project assumes you are a typical react-native developer, meaning you target iOS as well, and thus are running on macOS, so it expects you will have brew installed.

How did it go when you researched your problem? Did you see the upstream bug I filed on the same? https://github.com/pmadruga/react-native-clean-project/issues/92 If you had searched you may have seen that.

How does it go when you integrate the patch I put in that issue, via patch-package? That should work.

It doesn't appear to me as if you are giving it much effort before you ask for help from others. You need to *really* try to move past these issues, they are not serious issues that you are having, they are the very first stumbling blocks people have. I mention that because if you allow yourself to get stuck on these sorts of things and wait for help, you will have very low productivity before you even hit serious problems, and that's no good.

**Comment by code-by** [comment]
I have found this issue by searching `Binary store`
Currently I'm try to build Android project, cause machine with MacOS is working much slower than my PC so I writing/debug for Android, than for iOS
`npx react-native-clean-project@4.0.0` not helped for me, even it do the job (I'm response 'no' to all macOS related questions)
after 'yarn remove @react-native-firebase/app` it do successfully build android project

**Comment by code-by** [comment]
turned out that problem was with 
```
dependencies {
    ...
    implementation 'com.google.firebase:firebase-analytics:17.3.0'
```
in `app/buid.gradle`
after comment this line project build successfully

**Comment by mikehardy** [comment]
Indeed, there should be no `com.google.firebase` lines in `android/app/build.gradle` this module is in full control of those and you will only compile successfully out of luck, temporarily, if your project specifies them vs letting reat-native-firebase handle them

Glad you found the root cause! That's a really important one to clear out of your project
