### ISSUE TITLE
Unable to setup in react native 42

### ISSUE THREAD

**Issue by contata-mobile** [invertase/react-native-firebase#485]
Hey , 
I tried to setup react-native-firebase for RN 0.42 in ios and followed all the steps mentioned in docs
But everytime i try to build it fails with link error of 
 _OBJC_CLASS_$_RNFirebaseDatabase  and alike error message for all the pods  i added .
i tried removing the xcode cache and pods install again and again but same kept on coming 
steps i followed:
1. npm  install react-native-firebase
2.react native link
3.  Pods Install 
4.Appdelegate.m changes
5. run from code 

Is there something i am missing that is preventing build for the same .
Please help 
RN version :0.42
Pods : Latest versions 
RN-firebase: latest

**Comment by DavidKuennen** [comment]
You need at least RN version 0.48 for the latest react-native-firebase version.

See: https://invertase.io/react-native-firebase/#/?id=supported-versions-react-native-firebase

**Comment by contata-mobile** [comment]
Thanks for the reply .
If i wanted to integrate with 0.42 or 0.43 is there some limitations or specific version on pods and react-native-firebase component that i can use ?

**Comment by chrisbianca** [comment]
@contata-mobile Checkout the table here for supported versions: https://github.com/invertase/react-native-firebase#supported-versions---react-native--firebase

**Comment by contata-mobile** [comment]
@chrisbianca  Thanks for the details i tried v2.0.3 but the issue i am getting is ad follows

<img width="563" alt="screen shot 2017-10-11 at 10 52 45 am" src="https://user-images.githubusercontent.com/28640087/31423545-163cdcb6-ae73-11e7-9026-0ada3ec4dfdb.png">

the added only firebase/core pod 
and even crosschecked my pod with demo provided for the same version 
If i add other pod same error come for them as well 

Please help!

**Comment by chrisbianca** [comment]
@contata-mobile what versions of the pods do you have installed?  You can see this in your `Podfile.lock` file

You might want to try updating them by running:

`pod outdated` - shows which pods have updates available
`pod update` - updates to the available pods

**Comment by contata-mobile** [comment]
Thanks alot @chrisbianca  
I  re-setup cocoa in my project and everything started working fine using 
gem install cocoapods
I revisited #321 for the same
