### ISSUE TITLE
🔥 [🐛] Click not work on iOS (CTA to open web page) !

### ISSUE THREAD

**Issue by badredaha** [invertase/react-native-firebase#4852]
issue:

When the modal/card is shown, the CTA (click to action) not work on iOS (but works in Android, the browser is opened with the specific URL setup in Firebase console)?

i use web url (https://www.google.com) 🔢 

Any suggested 🤔

**Comment by mikehardy** [comment]
> Any suggested thinking

Please do not ignore the issue template when opening issues in open source repositories, or there is no help offered
