### ISSUE TITLE
[🐛] RTDB same ref .once() is called before .on(), even if set after.

### ISSUE THREAD

**Issue by SrBrahma** [invertase/react-native-firebase#4865]
## Issue

I have a small lib (https://github.com/SrBrahma/Firebase-Database-Listeners-Manager) which one of it functionalities it to call a callback when all the given refs are first loaded. It attaches a .once() to each given ref, and they are meant to be listened before this additional listener.

One use of it, it to know when everything of a system is loaded, without adding a check to every listener callback manually / changing the callback.

It works almost fine, with the exception that the "allLoadedCallback" is synchronously called before one of the main listeners.

In short and in a more understandable way,
```ts
ref('A').on(() => console.log(1))
ref('A').once(() => console.log(2))
```
Will print 2 and then 1, but

```ts
ref('A').on(() => console.log(1))
ref('A').on(() => console.log(2))
```

Will print 1 and then 2.

As a workaround, I will just use .on() and deactivate it after its first cb to keep the proper order. But, the order's behaviour when using once, as I believe, should keep the order of the listener add.

Edit: Did this workaround and it is working as predicted.
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You skipped the template, so I'm closing this.
There's no indication of which platform.
Is the ordering a guarantee that the underlying SDK provides? If it is, then this could be an issue, if it is not then this is not something we would support. A quickstart or documentation dive on upstream SDKs could answer that quesiton
