### ISSUE TITLE
[🐛] Notification trigger to identify which notification has opened App, is not happening. 

### ISSUE THREAD

**Issue by varora1406** [invertase/react-native-firebase#4866]
## Issue

Two problems - 
* App is getting opened on second click of Notification.
* Which notification has triggered to open the App is not getting detected.

Versions used - 
* "@react-native-firebase/app": "^10.5.0"
* "@react-native-firebase/messaging": "^10.5.1"

```
messaging()
  .getInitialNotification()
  .then(remoteMessage => {
    console.log('getInitialNotification', remoteMessage);
  });

messaging().onNotificationOpenedApp(listener => {
  console.log('onNotificationOpenedApp', listener);
});

messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('setBackgroundMessageHandler', remoteMessage);
});
```

BackgroundMessageHandler triggers and logs data when device receives notification.
But onNotificationOpenedApp is not triggered.
And initialNotification gives null data

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Sounds interesting but if you skip the template, we close the issue

**Comment by varora1406** [comment]
oh man, how many things needs to be filled?

**Comment by mikehardy** [comment]
@varora1406 all the things that you would need if you were developer and a colleague came to you with a problem, in other words, the things we indicate. You want free help? You provide the information we request
