### ISSUE TITLE
🔥  setBackgroundMessageHandler fired only with mixed payload

### ISSUE THREAD

**Issue by Hurobaki** [invertase/react-native-firebase#4872]
## Issue

I had some difficulties setting up notifications on a larger project using Firebase. I started a project from scratch in order to have as few dependencies as possible.

The principle is simple, I use a Cloud Function with the `admin sdk` to send a notification according to a condition. I would like to send data-only notification and manage it in the three states of my application (eg: foreground, background, killed)

As you can see in the Javascript files section, I have set up the `setBackgroundMessageHandler` listener to handle notification from background and quit state. According to the documentation, I thought that `data-only` payload would trigger this listener. But I had to had `notification` key inside my payload in addition to the `data` key to be able to trigger the listener.

Payload that does not trigger : 

```js
const message: Message = {
        data: {
            title: 'Title',
            body: 'body',
        },
        apns: {
            payload: {
                aps: {
                    contentAvailable: true,
                },
            },
            headers: {
                'apns-push-type': 'background',
                'apns-priority': '5',
                'apns-topic': 'com.rn.sandbox',
            },
        },
        android: {
            priority: 'high',
        },
        condition: "'foo' in topics",
    };
```

Payload that does trigger : 

```js
const message: Message = {
        notification: {
            title: 'Title',
            body: 'body',
        },
        data: {
            title: 'Title',
            body: 'body',
        },
        apns: {
            payload: {
                aps: {
                    contentAvailable: true,
                },
            },
            headers: {
                'apns-push-type': 'background',
                'apns-priority': '5',
                'apns-topic': 'com.rn.sandbox',
            },
        },
        android: {
            priority: 'high',
        },
        condition: "'foo' in topics",
    };
```

I have spent a lot of time trying to make data-only notifications works until I have tried to add `notification` key. 
Maybe I misunderstood or it's a problem in my code? I know there are a lot of threads about this, I have read all of them but none is talking about adding notification key inside payload and so can't making data-only notifications.

Some help would be really appreciated ! 

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
    "@react-native-firebase/app": "10.5.0",
    "@react-native-firebase/messaging": "10.5.1",
    "react": "16.13.1",
    "react-native": "0.63.4"
  },
  "devDependencies": {
    "@babel/core": "7.12.13",
    "@babel/runtime": "7.12.13",
    "@react-native-community/eslint-config": "2.0.0",
    "babel-jest": "26.6.3",
    "eslint": "7.19.0",
    "jest": "26.6.3",
    "metro-react-native-babel-preset": "0.65.0",
    "react-test-renderer": "16.13.1"
  }
```

#### `Cloud Function`

```js
import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';
import { Request, Response } from 'express';
import { messaging } from 'firebase-admin/lib/messaging';
import Message = messaging.Message;

admin.initializeApp();

export const helloWorld = functions.https.onRequest(async (request: Request, response: Response) => {
    const message: Message = {
        notification: {
            title: 'Title',
            body: 'body',
        },
        data: {
            title: 'Title',
            body: 'body',
        },
        apns: {
            payload: {
                aps: {
                    contentAvailable: true,
                },
            },
            headers: {
                'apns-push-type': 'background',
                'apns-priority': '5',
                'apns-topic': 'com.rn.sandbox',
            },
        },
        android: {
            priority: 'high',
        },
        condition: "'foo' in topics",
    };

    try {
        await admin.messaging().send(message);
    } catch (e) {
        functions.logger.log('ERROR SEND MESSAGE', e);
    }

    response.send('Hello from Firebase !');
});
```

#### `index.js`:

```js
import React from 'react';
import { AppRegistry } from 'react-native';
import App from './App';
import { name as appName } from './app.json';
import messaging from '@react-native-firebase/messaging';

// Register background handler
messaging().setBackgroundMessageHandler(async (remoteMessage) => {
    console.log('Message handled in the background!', remoteMessage);
});

function HeadlessCheck({ isHeadless }) {
    if (isHeadless) {
        // App has been launched in the background by iOS, ignore
        return null;
    }

    return <App />;
}

AppRegistry.registerComponent(appName, () => HeadlessCheck);
```

#### `App.js`:

```js
import React, { useEffect } from 'react';
import { SafeAreaView, Text, StatusBar, Alert } from 'react-native';
import messaging from '@react-native-firebase/messaging';

const App: () => React$Node = () => {
    const init = async () => {
        const authStatus = await messaging().requestPermission();
        const enabled =
            authStatus === messaging.AuthorizationStatus.AUTHORIZED ||
            authStatus === messaging.AuthorizationStatus.PROVISIONAL;

        if (enabled) {
            console.log('Authorization status:', authStatus);
            messaging()
                .subscribeToTopic('foo')
                .then(() => console.log('Subscribed to topic!'));

            console.log(await messaging().getToken());
        }
    };

    useEffect(() => {
        init()
            .then()
            .catch((e) => console.log('Error while init', e));

        const unsubscribe = messaging().onMessage(async (remoteMessage) => {
            Alert.alert('A new FCM message arrived!', JSON.stringify(remoteMessage));
        });

        return unsubscribe;
    }, []);

    return (
        <>
            <StatusBar barStyle="dark-content" />
            <SafeAreaView>
                <Text>Sandbox</Text>
            </SafeAreaView>
        </>
    );
};

export default App;

```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `Capabilities`

<img width="457" alt="image" src="https://user-images.githubusercontent.com/10489555/107042727-5c03c780-67c2-11eb-9e54-4fa2f2d8df34.png">

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RNSandbox' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'RNSandboxTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RNSandbox-tvOS' do
  # Pods for RNSandbox-tvOS

  target 'RNSandbox-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

#### `AppDelegate.swift`:

```swift
import Foundation
import UIKit
import Firebase


@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate, RCTBridgeDelegate {
  var window: UIWindow?
  
  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    
    FirebaseApp.configure()
    
    let bridge = RCTBridge(delegate: self, launchOptions: launchOptions)
    
    if let reactBridge = bridge {
      let properties = RNFBMessagingModule.addCustomProps(toUserProps: nil, withLaunchOptions: launchOptions)
      
      let rootView = RCTRootView(bridge: reactBridge, moduleName: "RNSandbox", initialProperties: properties)
      rootView.backgroundColor = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
      
      self.window = UIWindow(frame: UIScreen.main.bounds)
      
      let rootViewController = UIViewController()
      rootViewController.view = rootView
      self.window?.rootViewController = rootViewController
      self.window?.makeKeyAndVisible()
    }
    
    return true
  }
  
  func sourceURL(for bridge: RCTBridge!) -> URL! {
    #if DEBUG
    return RCTBundleURLProvider.sharedSettings()?.jsBundleURL(forBundleRoot: "index", fallbackResource: nil)
    #else
    return Bundle.main.url(forResource: "main", withExtension: "jsbundle")
    #endif
  }
}
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 612.27 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /Users/the3796/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `10.5.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Messaging`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
data-only notifications are tagged with "contentAvailable" which is an indicator of how Apple views them.

- they are not guaranteed delivery
  -  you read all the threads, did you see the ones about throttling and debugging flags and how to see if you are thottled?
  - did you see the ones where if you force quit, apple believes you, and refuses to start the app?
  - have you read the apple docs on what they require when you push content-available, which is that the app function fine if not delivered because it is just supposed to trigger content caching, which by definition can be done when app starts up and notices content is stale?


So - the principle is simple, in that it's clear what you want. But what you want is not possible by design on the platform.

If you want guaranteed delivery you must use a notification block, with all the limitations that implies (i.e., that you won't get control until the user clicks it to start your app, and if you attempt to post your own local notification you'll get two notifications)

**Comment by Hurobaki** [comment]
Thank you for your answer

I turned on the `-FIRDebugEnabled` flag but I don't see anything about throttling. Anyway you are right, Apple prevents too many notifications to be delivered. Only 2-3 per hour that's right ? 

I thought that by adding the headers it could force the application to open even if it was force quit.

I will use the notification block to guaranty my delivery and as you said I will not create local notification on background and quit event but let the system display the notification. If I plan to keep mixed payload, do I still need the `contentAvailable` key ?

**Comment by mikehardy** [comment]
> If I plan to keep mixed payload, do I still need the `contentAvailable` key ?

I do not believe so, but with all things related to FCM: test
