### ISSUE TITLE
Cloud Firestore get document API docs are incorrect

### ISSUE THREAD

**Issue by andersryanc** [invertase/react-native-firebase#488]
### Issue

I've been testing out the Cloud Firestore (beta) today and noticed that your documentation around the documents get method doesn't appear to be correct. On this page: https://invertase.io/react-native-firebase/#/modules/firestore the code snippet directly under the Documents headline seems to return a promise and does not use the callback.

**Current Docs**
```js
import firebase from 'react-native-firebase';

firebase.firestore()
  .doc('posts/posts1')
  .get((documentSnapshot) => {
    const value = documentSnapshot.data();
  });

firebase.firestore()
  .collection('posts')
  .doc('posts1')
  .get((documentSnapshot) => {
    const value = documentSnapshot.data();
  });
```

**Should be changed to**
```js
import firebase from 'react-native-firebase';

firebase.firestore()
  .doc('posts/posts1')
  .get()
  .then((documentSnapshot) => {
    const value = documentSnapshot.data();
  });

firebase.firestore()
  .collection('posts')
  .doc('posts1')
  .get()
  .then((documentSnapshot) => {
    const value = documentSnapshot.data();
  });
```

That being said, the way you have it in the docs seems like a nicer API.

### Environment

1. Application Target Platform: **Both**
2. Development Operating System: **macOS Sierra**
3. Build Tools: 
4. React Native version: **0.48.2**
5. RNFirebase Version: **3.0.2**
6. Firebase Module: **Cloud Firestore**

**Comment by Salakar** [comment]
@andersryanc thanks for that, we'll sort. 

https://rnfirebase.io/docs/v3.0.*/firestore/reference/DocumentReference is the new WIP documents site - has a much more complete API reference, if it helps feel free to use this site instead of the current docs. We'll be switching over soon.
