### ISSUE TITLE
[🐛] NullPointerException - Attempt to invoke virtual method waitForPendingWrites() on Android

### ISSUE THREAD

**Issue by luco** [invertase/react-native-firebase#4887]
## Issue

Getting an error while trying to execute `waitForPendingWrites()`.

---

### Javascript

<details><summary>Click To Expand</summary>

```
firestore().waitForPendingWrites().then(() => {

});
```

#### `package.json`:

```
    "@react-native-firebase/app": "^10.5.0",
    "@react-native-firebase/auth": "^10.6.4",
    "@react-native-firebase/firestore": "^10.5.1",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.firestore.core.FirestoreClient.waitForPendingWrites()' on a null object reference
    at com.google.firebase.firestore.FirebaseFirestore.waitForPendingWrites(FirebaseFirestore.java:444)
    at io.invertase.firebase.firestore.UniversalFirebaseFirestoreModule.waitForPendingWrites(UniversalFirebaseFirestoreModule.java:87)
    at io.invertase.firebase.firestore.ReactNativeFirebaseFirestoreModule.waitForPendingWrites(ReactNativeFirebaseFirestoreModule.java:61)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:241)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:919)
```

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```
 implementation platform('com.google.firebase:firebase-bom:26.4.0')
implementation 'com.google.firebase:firebase-analytics'
implementation 'com.google.firebase:firebase-firestore'
```

#### `android/settings.gradle`:

```
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `v6`
- **`Firebase` module(s) you're using that has the issue:**
  - `firestore`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
```
 "@react-native-firebase/app": "^10.5.0",
    "@react-native-firebase/auth": "^10.6.4",
    "@react-native-firebase/firestore": "^10.5.1",
```

Do **NOT** mix and match versions. All should be same version now, all 10.6.4.

You skipped the template which may have had more interesting information but +1 for an actual stack trace, I'll mark this for review

**Comment by luco** [comment]
@mikehardy Even matching all versions I still get the error.

**Comment by mikehardy** [comment]
Okay - not completely surprised there, but your project is in better shape now ;-)

**Comment by luco** [comment]
@mikehardy It seems something related to firestore initialization. Not sure.

**Comment by mikehardy** [comment]
Use my script to attempt to reproduce cleanly then. https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by luco** [comment]
@mikehardy I don't  think this script will fix. Have you seen the temp fix? It's something related on how firebase inits on Android.

**Comment by mikehardy** [comment]
The results should be interesting then
