### ISSUE TITLE
[🐛] FIRESTORE INTERNAL ASSERTION FAILED - invoking documentOnSnapshot on target RNFBFirestoreDocumentModule

### ISSUE THREAD

**Issue by betteryou-ai** [invertase/react-native-firebase#4889]
## Issue

I'm running into an issue where my iOS code will build properly but will throw a FIRESTORE INTERNAL ASSERTION FAILED error with the following stack:
![Screen Shot 2021-02-09 at 10 09 48 AM](https://user-images.githubusercontent.com/44238164/107398466-4265c700-6ac5-11eb-8240-996c9275f5ce.png)

```
2021-02-09 10:09:20.015 [fatal][tid:io.invertase.firebase.firestore] Exception 'FIRESTORE INTERNAL ASSERTION FAILED: Firestore instance has already been started and its settings can no longer be changed. You can only set settings before calling any other methods on a Firestore instance.' was thrown while invoking documentOnSnapshot on target RNFBFirestoreDocumentModule with params (
    "[DEFAULT]",
    "users/4QLyGZlJLZQjLkHvCNSClC4fIao2",
    0,
        {
    }
)
callstack: (
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2042191f +[NSException raise:format:] + 0
	3   Foundation                          0x00007fff20771633 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
	4   BetterYou                           0x00000001007c9bd7 _ZN8firebase9firestore4util16ObjcThrowHandlerENS1_13ExceptionTypeEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 343
	5   BetterYou                           0x00000001007c9055 _ZN8firebase9firestore4util5ThrowENS1_13ExceptionTypeEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 53
	6   BetterYou                           0x0000000100931f1d _ZN8firebase9firestore4util8internal13FailAssertionEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 45
	7   BetterYou                           0x000000010082f203 _ZN8firebase9firestore3api9Firestore12set_settingsERKNS1_8SettingsE + 131
	8   BetterYou                           0x000000010089a6df -[FIRFirestore setSettings:] + 239
	9   BetterYou                           0x0000000100ee0a7d +[RNFBFirestoreCommon setFirestoreSettings:appName:] + 1325
	10  BetterYou                           0x0000000100ee03b1 +[RNFBFirestoreCommon getFirestoreForApp:] + 401
	11  BetterYou                           0x0000000100ee1b0e -[RNFBFirestoreDocumentModule documentOnSnapshot::::] + 270
	12  CoreFoundation                      0x00007fff204282fc __invoking___ + 140
	13  CoreFoundation                      0x00007fff204257b6 -[NSInvocation invoke] + 303
	14  CoreFoundation                      0x00007fff20425a47 -[NSInvocation invokeWithTarget:] + 70
	15  BetterYou                           0x0000000101008ed4 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2660
	16  BetterYou                           0x000000010100d07e _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 814
	17  BetterYou                           0x000000010100cb46 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 134
	18  BetterYou                           0x000000010100caac ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28
	19  libdispatch.dylib                   0x00000001076587ec _dispatch_call_block_and_release + 12
	20  libdispatch.dylib                   0x00000001076599c8 _dispatch_client_callout + 8
	21  libdispatch.dylib                   0x0000000107660296 _dispatch_lane_serial_drain + 796
	22  libdispatch.dylib                   0x0000000107660f67 _dispatch_lane_invoke + 439
	23  libdispatch.dylib                   0x000000010766cde2 _dispatch_workloop_worker_thread + 882
	24  libsystem_pthread.dylib             0x00007fff61167499 _pthread_wqthread + 314
	25  libsystem_pthread.dylib             0x00007fff61166467 start_wqthread + 15
)
```

Describe your issue here

The issue started when I updated the firebase npm packages from 6.2.0 to the latest 10.6.4, I figured there would be some issues as its a large jump, my goal was to get the new version of crashlytics working, since I was having dependency issues with 6.2.0 I upgraded. Everything builds just fine and it launches but then it immediately throws the firestore error. 
I do use firestore both natively in iOS lifecycle methods as well as in react native. What I can't figure out is that it claims i'm setting firestore settings after making snapshot calls but no where in either code am I setting up firestore settings. 

I've so far tried in various orders:
- pod deintegrate
- pod install --repo-update
- uninstall & reinstall node modules
- revert back to 6.2.0 - still same issue
- delete derived data
- cleared watchman and metro bundler caches
- clean build
- followed install guide
- reset emulators

Nothing has seemed to work except if I comment out all of my firestore functions in react native, but then I obviously don't get any use out of it. The other weird behavior is if I reload the emulator it works fine after that. The big issue is that it is crashing our production builds as it just gets hung up on what I would assume is this firestore error. I've not had this issue before while using firebase both native and in react native so i'm assuming there is probably something going wrong in set up as it broke after I tried updating? 

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "BetterYou",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest --watch-all",
    "android": "react-native run-android",
    "ios": "react-native run-ios"
  },
  "dependencies": {
    "@babel/core": "^7.12.10",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/plugin-transform-flow-strip-types": "^7.12.10",
    "@babel/runtime": "^7.12.5",
    "@fortawesome/fontawesome-pro": "^5.15.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.32",
    "@fortawesome/pro-duotone-svg-icons": "^5.15.1",
    "@fortawesome/react-native-fontawesome": "^0.2.6",
    "@miblanchard/react-native-slider": "^1.5.0",
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/datetimepicker": "^2.3.2",
    "@react-native-firebase/app": "^10.6.4",
    "@react-native-firebase/auth": "^10.6.4",
    "@react-native-firebase/crashlytics": "^10.6.4",
    "@react-native-firebase/firestore": "^10.6.4",
    "@react-native-firebase/functions": "^10.6.4",
    "bad-words": "^3.0.4",
    "buffer": "^5.4.3",
    "dayjs": "^1.9.3",
    "husky": "^3.0.0",
    "jest-serializer-enzyme": "^1.0.0",
    "lodash": "latest",
    "moment": "^2.29.1",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-addons-test-utils": "^15.6.2",
    "react-dom": "^16.12.0",
    "react-native": "^0.61.5",
    "react-native-app-auth": "^4.4.0",
    "react-native-branch": "^5.0.0",
    "react-native-contacts": "^5.0.4",
    "react-native-device-info": "^2.3.2",
    "react-native-dropdownalert": "^4.2.0",
    "react-native-fix-image": "^2.0.0",
    "react-native-gesture-handler": "^1.5.3",
    "react-native-google-places": "^3.1.2",
    "react-native-ignore-warnings": "^0.1.1",
    "react-native-image-slider-show": "^1.0.3",
    "react-native-intercom": "^13.1.0",
    "react-native-linear-gradient": "^2.4.2",
    "react-native-modal": "^11.1.0",
    "react-native-permissions": "^1.1.1",
    "react-native-share": "^3.3.2",
    "react-native-snap-carousel": "^3.8.4",
    "react-native-svg": "^9.4.0",
    "react-native-svg-charts": "^5.2.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-video": "^5.0.2",
    "react-native-walkthrough-tooltip": "^1.0.0",
    "react-native-webview": "^10.3.2",
    "react-navigation": "^3.11.1",
    "react-redux": "^7.1.0",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0",
    "rn-apple-healthkit": "^0.8.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.3",
    "babel-jest": "^24.9.0",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "enzyme-to-json": "^3.4.3",
    "eslint": "^6.8.0",
    "eslint-config-defaults": "^9.0.0",
    "eslint-plugin-react": "^7.17.0",
    "eslint-plugin-react-native": "^3.8.1",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-plugin-import": "^2.19.1",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react-hooks": "^2.3.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.57.0",
    "react-test-renderer": "^16.12.0",
    "schedule": "^0.5.0"
  },
  "jest": {
    "preset": "react-native",
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ]
  }
}

```

#### `firebase.json` for react-native-firebase v6:
```json
{
  "react-native": {
    "crashlytics_debug_enabled": true
  }
}

```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:
```# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
pod 'GooglePlaces'
pod 'GoogleMaps'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'
pod 'Firebase/Analytics'
pod 'Firebase/MLVision'
pod 'Firebase/Performance'
pod 'SwiftLog', '~> 1.0.0'
pod 'AppAuth'
pod 'Intercom'
pod 'ReachabilitySwift'
pod 'SwiftLint'
pod 'Branch'

target 'BetterYou' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Pods for BetterYou
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    
    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
    
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    
    pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

    pod 'RNSVG', :path => '../node_modules/react-native-svg'
    
    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

    pod 'react-native-intercom', :path => '../node_modules/react-native-intercom'

    pod 'react-native-google-places', :path => '../node_modules/react-native-google-places'
    
    pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'

    pod 'RNAppAuth', :path => '../node_modules/react-native-app-auth/ios/RNAppAuth.podspec'

    pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

    pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

    pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'

    pod 'RNFBFunctions', :path => '../node_modules/@react-native-firebase/functions'

    pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'

    pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker/RNDateTimePicker.podspec'

    pod 'RCTAppleHealthKit', :path => '../node_modules/rn-apple-healthkit'
    
    pod 'react-native-branch', path: '../node_modules/react-native-branch'
    
    # React-Native-Share pod
     pod 'RNShare', :path => '../node_modules/react-native-share'

    pod 'react-native-webview', :path => '../node_modules/react-native-webview'

    target 'BetterYouTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    
end



target 'BetterYou-tvOS' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for BetterYou-tvOS
    
    target 'BetterYou-tvOSTests' do
        inherit! :search_paths
        # Pods for testing
    end

end
```
- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE

System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 594.59 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.12.0 => 16.12.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

```

- **Platform that you're experiencing the issue on**:
  - [ X] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `10.6.4`
- **`Firebase` module(s) you're using that has the issue:**
  - `Firestore`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there!
If you have a mixed app (using firebase-ios-sdk directly and react-native-firebase) then I must set expectations that you will need to fix this on your own, as it will be project-specific. I can only offer some guesses and some guidance.

What you are running in to is fairy apparent from the stack (good posting it! that helped)

https://github.com/invertase/react-native-firebase/blob/85d6801ecbe9b3922225c55ca3628675ad848764/packages/firestore/ios/RNFBFirestore/RNFBFirestoreCommon.m#L30-L48

Specifically, react-native-firebase expects to be in control of your firestore settings. The first time you access a firestore instance for an app, it will set configuration, as you can see in that code snippet.

Firestore itself may only be configured before use though (regardless of who is using it).

So in your mixed app you need to somehow meet both of those constraints.

I suggest you access your firestore from react-native-firebase immediately on startup so that react-native-firebase knows it is configured and does not attempt to do so after whatever native use you have

There is nothing actionable for this module I think - I also use it in mixed mode personally but I meet the constraints by initializing it immediately via react-native-firebase as mentioned

**Comment by betteryou-ai** [comment]
> Hi there!
> If you have a mixed app (using firebase-ios-sdk directly and react-native-firebase) then I must set expectations that you will need to fix this on your own, as it will be project-specific. I can only offer some guesses and some guidance.
> 
> What you are running in to is fairy apparent from the stack (good posting it! that helped)
> 
> https://github.com/invertase/react-native-firebase/blob/85d6801ecbe9b3922225c55ca3628675ad848764/packages/firestore/ios/RNFBFirestore/RNFBFirestoreCommon.m#L30-L48
> 
> Specifically, react-native-firebase expects to be in control of your firestore settings. The first time you access a firestore instance for an app, it will set configuration, as you can see in that code snippet.
> 
> Firestore itself may only be configured before use though (regardless of who is using it).
> 
> So in your mixed app you need to somehow meet both of those constraints.
> 
> I suggest you access your firestore from react-native-firebase immediately on startup so that react-native-firebase knows it is configured and does not attempt to do so after whatever native use you have
> 
> There is nothing actionable for this module I think - I also use it in mixed mode personally but I meet the constraints by initializing it immediately via react-native-firebase as mentioned

do you initialize using the javascript configuration vs what the docs say which is to do this: 
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  // Add me --- \/
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  // Add me --- /\
  // ...
} 
```

Because i've been doing it this way and it hasn't ever been an issue until I tried updating the packages and pods. Also why wouldn't have this been an issue before if none of my firestore calls have changed since trying to update? 

Is it possible that this is just a weird caching issue and I just need to continue uninstalling and reinstalling?

**Comment by mikehardy** [comment]
You still want to follow the docs, e.g. https://github.com/mikehardy/rnfbdemo/blob/3b1095089e898c7629b8d530e1ad07b7998415d6/make-demo.sh#L31

Do not conflate different initializations/configurations though. You are quoting FIRApp to me, but your problem is FirebaseFirestore configuration.

Immediately on startup you need to do something (anything) at the react-native level with `@react-native-firebase/firestore` in order to go through the code snippet I included for you. You need to do that prior to anything you are doing directly to firebase-ios-sdk

**Comment by betteryou-ai** [comment]
So I think I might have figured it out. 

I had a few functions that fired from the iOS native side on initial app load, upon removing those functions it started to build again without crashing. It seems like it still works natively as well when I test those functions in a simulated background fetch.

I want to assume this issue is resolved but i'm still a bit confused as to why it never caused an issue before. Fortunately none of the native firestore functions were detrimental to the app's initial load. I did also add a firestore function to my app.js file (which was already there) so I'm assuming that is now being called first which should hopefully resolve the issue. I'll just make note to be careful running anything natively on the initial setup.

**Comment by betteryou-ai** [comment]
Unfortunately this bug is reaching beyond initial app load and is now occurring seemingly randomly in the background. I still have background fetch and a few lifecycle methods writing to Firestore but I've also added a Firestore function to the index.js file on the react native side. I'm not sure of ways to call RNFirestore any sooner than I already am. Is there a surefire way to make sure that they aren't conflicting with each other?

**Comment by mikehardy** [comment]
Perhaps, in your native code, pretend you are react-native JS, initializing react-native-firebase/firestore.
That is, in your native code, import react-native-firebase/firestore native code, and access the app so that it is initialized.

**Comment by betteryou-ai** [comment]
I'm not sure I understand what you mean by importing react-native-firebase/firestore code into the native iOS code?

`  if ([FIRApp defaultApp] == nil) {
      [FIRApp configure];
    }`
    
Is there something more than this line that I need in the AppDelegate.m file? 

To give more context about what exactly I'm doing that might be causing this to happen is we use a few of the iOS lifecycle methods to detect lock and unlock events on your device to count overall screen time (we're a digital health app). We also use background fetch and lifecycle methods (on app open/ enter foreground) to send other health data. 

We've primarily noticed that when you update the Test Flight version OR power off and on your device it will crash in the background. I understand that turning off and on your device and expecting things to behave normally is probably part of the issue. 

Originally I removed a bunch of functions that called on the initial start up of the app (didFinishLaunching function) and that seemed to stop the endless crashing but could also running these functions in the lifecycle and background methods be contributing to the issue?

Our long term solution is to migrate these native iOS systems to use callable cloud functions and realtime database to send data.

**Comment by mikehardy** [comment]
I mean, find the objective-c code that implements react-native-firebase/firestore's init. It is pasted in above even

Import that into your objective-c code that touches firestore APIs natively, where ever that is, however the import works for you

call those objective-c APIs so that you init the react-native-firebase/firestore objective-C data structures etc as if you were the react-native-firebase/firestore javascript layer

then later when you go to touch react-native-firebase/firestore it won't have internal assertion errors?

**Comment by betteryou-ai** [comment]
I've been continuing to try a variety of things to narrow down what is happening.

I started by adding 
` [FIRFirestore firestoreForApp:FIRApp.defaultApp];`
(I'm not the best with obj-c so I tried to adapt the code from the module in its most basic form)
I added this to didFinishLaunching, as well as my background fetch call

This seemed to help a little bit, the app doesn't crash on app open like it used to sometimes. I've also reduced the firestore calls into just iOS background fetch, however it still seems to be crashing, and they consistently line up with the background fetch calls. I noticed from my crashlogs mention 

`
RNFBFirestoreDocumentModule.m - Line 118
-[RNFBFirestoreDocumentModule documentGet:::::] `

and I do do a .get when I refresh the users geofences. This is the only document that I'm using .getDocument() on so I converted it to a snapshotListener (which I believe is the recommended approach). 

I've also updated and reinstalled the RNFirebase suite and checked any breaking changes. Everything thing seems to check out there. 

For the most part, crashes occur when updating the app to a new version (mostly through Test Flight). We've been intentionally NOT opening the app right away which successfully reproduces this crash. After opening the app it seems to chill out a bit but it does come back a few hours to a day later. 

I find it difficult to believe that there is something I'm doing wrong, and it doesn't seem practical to have to copy code from the RN package just to get Firestore to work in a mixed project. I've even created native modules to call native firestore functions through the react native layer. I'm hoping it was just the getDocument call I was doing and switching to snapshotListener does the trick.

Mostly just want to provide an update as to what I've tried, but if I fix it I'll leave another update with what I did that helped.

**Comment by mikehardy** [comment]
why not use react-native-background-fetch to implement the background fetch, then it gives you a JS hook and you don't have a brown-field app with part-native / part-javascript firestore use (and thus with firestore state inconsistency)? Could that work?

**Comment by betteryou-ai** [comment]
We've used it in the past, but moved away from it since it was a fairly simple thing to implement natively, and would relieve us of one more dependency. I'll give it another shot, however we still use Significant Location Change through which still touches Firestore in the background, so I don't know that it will completely resolve the issue.

**Comment by mikehardy** [comment]
....and that's react-native-background-geolocation-android ;-)

I use them both. I do not have your error

**Comment by betteryou-ai** [comment]
We've also used that in the past... again I didn't like the idea of adding more dependencies for something that is simple to implement on the native end. I'm not opposed to switching back, despite having to rebuild a number of location systems that so far haven't caused issues in the past. Just seems like a LOT of work around just for a mixed project. I do appreciate the responses though, I hope by making that switch this whole thing gets resolved.

**Comment by mikehardy** [comment]
You could do what they do though and call into JS instead of doing the firestore things that seem touch-y, make your native obj-c code into a react-native native module that emits events, and register listeners for same, then handle in javascript, background fetch's react-native adapter is a reasonable guide for a thing like that

https://github.com/transistorsoft/react-native-background-fetch/blob/master/ios/RNBackgroundFetch/RNBackgroundFetch.m
