### ISSUE TITLE
Realtime Database returns int instead of long

### ISSUE THREAD

**Issue by adamonkey** [invertase/react-native-firebase#489]
### Issue
This happens with iOS only. The large numbers (timestamps) I store in realtime database get returned as int, so they become mod 2,147,483,647, and sometimes become negative. Is this an issue with the library? Strangely, the problems gets fixed if I Reload the javascript, but reloading doesn't happen in production so the problem is always there. 

Edit: the database node reference is kept in sync, if this helps identify the problem. 
Edit2: toggling sync doesn't work I think. It randomly started to work on the simulator. But on a real device, it still will only work if I reload the JS bundle and if I change .once to .on. But it will not work without reloading the JS bundle. Help. 

1. Application Target Platform: iOS only
2. Development Operating System: macOS Sierra
3. Build Tools: Xcode 8.3.3
4. React Native version: 0.49.2
5. RNFirebase Version: I am using the github library. Happens also with the latest npm. 
6. Firebase Module: Realtime Database

**Comment by chrisbianca** [comment]
@adamonkey I've just added some tests to reproduce this, but I'm struggling.  I've tried reading long numbers from the database, and writing a long number to the database before reading it again.  Both times, the numbers come out correctly.

I've tested on an iPhone 8 simulator and an iPhone 4s simulator.

Is this only happening on a specific device?  Just to point out, 32 bit is no longer supported by Apple... so this issue will go away on its own longer term.

**Comment by chrisbianca** [comment]
If you're interested, the tests are here: https://github.com/invertase/react-native-firebase/commit/b12d9b29d04b078b659f8f7a23d9ceecdb203a0a

**Comment by adamonkey** [comment]
@chrisbianca Thank you so much. It is pretty hard to reproduce, it only happens the first time you load the app (not after you hot reload). And only on 32-bit devices.

I released the version without support for 32-bit devices, with a message saying that those phones are no longer supported. I will close this. Thank you again.

**Comment by tsuijten** [comment]
Hi, I also have this issue. I have pinned it down to being a Firebase SDK bug when persistence is enabled. It occurs when running on a 32bit device (in my case a iPhone 5C).

When I retrieve a timestamp from the database in native (Swift) code I also get a negative number instead of the correct timestamp. So it's not a `react-native-firebase` bug, but a bug in the Firebase iOs SDK.

When I turn persitence off the issue is gone.
