### ISSUE TITLE
 CocoaPods could not find compatible versions for pod "Firebase/CoreOnly"

### ISSUE THREAD

**Issue by nwpnkmngm** [invertase/react-native-firebase#4892]
I have new installed @react-native-firebase 3 libraries [app,auth,crashlytics] version 10.7.0

my step is
- delete node_modules , yarn.locks , Podfile.lock 
- yarn install 
- react-native link
- cd ios && pod install --repo-update

and I got error
![messageImage_1612931608849](https://user-images.githubusercontent.com/48342930/107464933-d7cf8c80-6b93-11eb-92dd-91b025a39c16.jpg)

someone can resolve this issues? or facing this like me

**Comment by mikehardy** [comment]
This will be something between you and cocoapods, they exist https://github.com/CocoaPods/Specs/blob/master/Specs/0/3/5/Firebase/7.6.0/Firebase.podspec.json

**Comment by daywong1119** [comment]
Just note down in case someone needed:
I specify `Firebase/Messaging` in Podfile for `image service`.
Remember to change the version during upgrade.

<img width="496" alt="Screenshot 2021-06-25 at 12 25 02 PM" src="https://user-images.githubusercontent.com/3933762/123369694-c7530800-d5b0-11eb-82a8-3434b1b2e03e.png">

**Comment by mikehardy** [comment]
It's very easy to forget to update one if you have to use them in multiple places (for instance if you're tracking tags on the firestore-ios-sdk-frameworks repo to get pre-compiled FirebaseFirestore to save half the build time for ios...)

I can only keep track if I define it as a variable in one spot then just reference it:

https://github.com/invertase/react-native-firebase/blob/bf0baeea3da650909bd617dd0c9c615b9fbc0417/tests/ios/Podfile#L5
