### ISSUE TITLE
dynamic links not working just on iOS 14?

### ISSUE THREAD

**Issue by nimrodbens** [invertase/react-native-firebase#4897]
everything works fine with iOS 13. standard setup according to this manual:

https://rnfirebase.io/dynamic-links/usage

on a device with iOS 14 i get this page after tapping the dynamic link:

https://imgur.com/a/Mt0TTJf

**Comment by mikehardy** [comment]
If it is an iOS version difference, it will be an underlying SDK issue - you should reproduce with their quickstart and pursue this with the firebase-ios-sdk team https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks

I will say that if you ignore whatever template they have for issue reporting, they will similarly not be able to help, resulting in likely issue closure for not providing information, same reason I will close this
