### ISSUE TITLE
messaging onMessage - iOS vs Android

### ISSUE THREAD

**Issue by Ehesp** [invertase/react-native-firebase#49]
Currently it would seem iOS only accepts the following to receive a remote message:

```js
    firebase.messaging().onMessage((notification) => {

    });
```

Currently, Android also has `on` available, which doesn't work in iOS I think:

```js
    firebase.messaging().on(firebase.messaging.EVENT_TYPE.Notification, (notification) => {

    });
```

Whats the correct way we should handle this cross platform?

**Comment by Salakar** [comment]
@Ehesp I need to look into this, i think they should both be the same method, must've missed something during the implementation

**Comment by chrisbianca** [comment]
`onMessage` works across both platforms and is the documented method as per: http://invertase.io/react-native-firebase/#/modules/cloud-messaging?id=onmessagelistener-functionltobjectgt so I'm going to close this
