### ISSUE TITLE
Warning: Module RNFirebaseAuth requires main queue setup

### ISSUE THREAD

**Issue by JSafaiyeh** [invertase/react-native-firebase#490]
`Module RNFirebaseAuth requires main queue setup since it overrides init but doesnt implement requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.`

How can I resolve this warning? It occurs on app startup.

**Comment by Salakar** [comment]
Lets move this into #491 - we'll sort there.
