### ISSUE TITLE
[🐛] Use of undeclared identifier 'kFIRParameterItems'; did you mean 'kFIRParameterItemID'?

### ISSUE THREAD

**Issue by R8Manzo** [invertase/react-native-firebase#4907]
## Issue

Im having trouble updating to 10.7.0, initially, i only had installed /app, /auth and /analytics modules.
Today i wanted to install /firestore module, but i noticed my versions were too old, when i update, this error happens:
Use of undeclared identifier 'kFIRParameterItems'; did you mean 'kFIRParameterItemID'?

![image](https://user-images.githubusercontent.com/19478245/107784588-41c17080-6d11-11eb-9887-e494e2f0bcaf.png)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
old lines:
  "@react-native-firebase/analytics": "7.1.4",
  "@react-native-firebase/app": "7.2.1",
  "@react-native-firebase/auth": "8.0.5",
new lines:
  "@react-native-firebase/analytics": "10.7.0",
  "@react-native-firebase/app": "10.7.0",
  "@react-native-firebase/auth": "10.7.0",
  "@react-native-firebase/firestore": "10.7.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 11.2.1
    CPU: (8) x64 Apple M1
    Memory: 42.12 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.4.3 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `10.7.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Analytics`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
- skipped template, that's inconsiderate of maintainer time in the open source world - we have issue templates for a reason
- images vs text, very hard to actually tell what's going on, if there's an error, post the actual text of the error please
- compile failures imply some sort of incorrect version of firebase-ios-sdk if you are overriding it (at which point it's project-specific and your responsibility to maintain version compatibility when overriding) or a caching issue (try `npx react-native-clean-project`) or something else (try https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh and compare with your project)

In the end this will be project specific 99.9999% of the time if you can reproduce with a clean minimal reproduction please post it (try starting with that make-demo script) and we can reopen
