### ISSUE TITLE
[📚] Documentation Issue Low Accessibility on paragraph text

### ISSUE THREAD

**Issue by lkatartn** [invertase/react-native-firebase#4908]
## Low text visibility on documentation paragraphs

There are two issues with text there:
 - Low contrast (Lighthouse shows hint on that)
 - Text is too thin on windows device

_Browser_: Brave 1.20
_OS_: Windows 10
_Device_: Surface pro 7

![image](https://user-images.githubusercontent.com/2746150/107807187-71ec2c00-6d70-11eb-9704-622aceefd2e1.png)

Pay attention on the readability between paragraph and code text.

Docs to help https://web.dev/color-and-contrast-accessibility/

**Comment by mikehardy** [comment]
Hi there! I'll happily merge PRs to the docs site if you care to propose any. Thanks!

**Comment by lkatartn** [comment]
Hi @mikehardy ! Thanks for response!
I've created a PR for this issue. Tested on win10 and macbook 👍 Much easier to read
