### ISSUE TITLE
[RN 0.49+] `requiresMainQueueSetup` needed for main queue setup, with constantsToExport

### ISSUE THREAD

**Issue by fungilation** [invertase/react-native-firebase#491]
OS:
- [x]  MacOS

_Platform:_
- [x]  iOS

### Console warning:
Module RNFirebase requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

Same for several other Firebase modules.

<img width="1170" alt="screenshot 2017-10-10 22 18 15" src="https://user-images.githubusercontent.com/3803466/31423478-f194d706-ae09-11e7-9274-7595cac91728.png">

`react-native info`:
```
Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.6.0
  Yarn:  1.2.0
  npm:  5.3.0
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3
```

### Reference PR for fix
https://github.com/wix/react-native-navigation/pull/1983/files#diff-b8c48202d12fa78c4c377e5a3225c298

**Comment by Salakar** [comment]
Thanks for flagging and with a PR to use as reference 👍 we'll sort for next patch release.

**Comment by chrisbianca** [comment]
I've just fixed this, pending a release later today
