### ISSUE TITLE
Unable to open app when notification received in closed app

### ISSUE THREAD

**Issue by Sandeep145XamRN** [invertase/react-native-firebase#4915]
I'm trying to bring app to foreground state when received notification of a video call at closed/kill  state.
tried many solution like HeadlessJS, open app by URL and react-native-invoke-app.
but fail to achieve this job. Any help will be appreciated

firebase latest version
React-Native 0.63.2

**Comment by andersonaddo** [comment]
Didn't follow template, closing

**Comment by mikehardy** [comment]
worth noting if it's android you have an application mode issue. launchMode should be singleTask https://github.com/invertase/react-native-firebase-docs/pull/35
