### ISSUE TITLE
🔥  [🐛] Bug Report Title - iOS Build Error Undefined symbols for architecture x86_64 - _OBJC_CLASS_$_FIRAnalytics

### ISSUE THREAD

**Issue by SaraChicaD** [invertase/react-native-firebase#4917]
## Issue

I have successfully installed `@react-native-firebase/analytics` & `@react-native-firebase/app` in my app for **Android only**, I cannot get the iOS app to build in order to see if it works. I have combed the Internet looking for why this may be, but ultimately am unable to fix it. I tried manually linking, adding to the Podfile, different versions of the library. 

I created a new project (sans the `GoogleService-Info.plist`) with the same `package.json` and `Podfile` and found the same error. [Here](https://github.com/SaraChicaD/FBAnalyticsTest) is the repo.

Here is the error:

```
▸ Touching RNFBApp.framework (in target 'RNFBApp' from project 'Pods')
▸ Processing RNFBAnalytics-Info.plist
▸ Linking RNFBAnalytics

❌  Undefined symbols for architecture x86_64
> Symbol: _OBJC_CLASS_$_FIRAnalytics
> Referenced from: objc-class-ref in RNFBAnalyticsModule.o



❌  ld: symbol(s) not found for architecture x86_64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "FBAnalyticsTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/masked-view": "^0.1.6",
    "@react-native-firebase/analytics": "^10.8.0",
    "@react-native-firebase/app": "^10.8.0",
    "@react-navigation/compat": "^5.2.7",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",
    "@reduxjs/toolkit": "^1.4.0",
    "axios": "^0.19.2",
    "es6-promise": "^4.2.8",
    "instabug-reactnative": "^9.1.10",
    "isomorphic-fetch": "^2.2.1",
    "link": "^0.1.5",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.31",
    "npm": "^6.13.7",
    "react": "16.13.1",
    "react-moment": "^0.9.7",
    "react-native": "0.63.2",
    "react-native-actionsheet": "^2.4.2",
    "react-native-adjust": "^4.22.0",
    "react-native-animatable": "^1.3.3",
    "react-native-animated-linear-gradient": "^1.2.0",
    "react-native-awesome-card-io": "^0.8.2",
    "react-native-camera": "^3.17.0",
    "react-native-confetti": "^0.1.0",
    "react-native-contacts": "^5.0.7",
    "react-native-datepicker": "^1.7.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-google-pay": "^2.1.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-masked-text": "^1.13.0",
    "react-native-onesignal": "^3.7.3",
    "react-native-orientation": "^3.1.3",
    "react-native-permissions": "^2.0.9",
    "react-native-picker-select": "^6.4.0",
    "react-native-plaid-link-sdk": "^6.0.4",
    "react-native-popup-dialog": "^0.18.3",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.0.0-alpha.29",
    "react-native-share": "^4.1.0",
    "react-native-snap-carousel": "^3.8.4",
    "react-native-store-review": "^0.1.5",
    "react-native-swipeable": "^0.6.0",
    "react-native-swiper": "^1.5.14",
    "react-native-swiper-flatlist": "^2.0.3",
    "react-native-touch-id": "^4.4.1",
    "react-native-user-agent": "^2.1.0",
    "react-native-video": "^5.0.2",
    "react-native-webview": "^9.4.0",
    "react-phone-input": "^1.2.1",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "stripe": "^8.14.0",
    "tipsi-stripe": "^7.5.3"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/runtime": "^7.9.0",
    "babel-jest": "^25.1.0",
    "eslint-config-rallycoding": "^3.2.0",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-native-clean-project": "^3.4.0",
    "react-test-renderer": "16.13.1",
    "redux-devtools": "^3.6.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'


target 'FBAnalyticsTest' do
  config = use_native_modules!
  config = use_frameworks!

  use_react_native!(:path => config["reactNativePath"])

  # Convert all permission pods into static libraries
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
        def pod.build_type;
          # Uncomment one line depending on your CocoaPods version
          Pod::BuildType.static_library # >= 1.9
          # Pod::Target::BuildType.static_library # < 1.9
        end
      end
    end
  end

  # Pods for Qoins
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"
  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Motion', :path => "#{permissions_path}/Motion.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders.podspec"
  pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition.podspec"
  pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit.podspec"
  
  pod 'Plaid', '~> 2.0.8'

  target 'FBAnalyticsTestTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

end


```

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>
#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"FBAnalyticsTest"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 411.09 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.12.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/saraines/.rvm/gems/ruby-2.4.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `10.8.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Analytics`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Interesting, and a little disappointing because I think this is going to boil down to a static frameworks issue so I'm going to be out of my depth immediately. First though - I'm an ex-Austinite and if I understand the situation correctly from my Austin family I hope you actually maintain power and stay warm this week!

So - to the static frameworks hypothesis, I think the permissions pods and the other stuff are just going to complicate the troubleshooting process

I bet if we just posted a repo from https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh raw, but altered the Podfile with an extra sed after this block https://github.com/mikehardy/rnfbdemo/blob/3b1095089e898c7629b8d530e1ad07b7998415d6/make-demo.sh#L42-L43 that toggled on `use_frameworks!` it would likely throw the same error?

We're in carnaval week in EC right now so I don't have a lot of time to help but if I were investigating my next step would be to completely hack out all of non-analytics react-native-firebase modules from the make-demo script (by just deleting the irrelevant lines in the shell script *and* in App.js, and prove it builds (it should build!). Then I'd manually edit the Podfile to turn on static frameworks and it *should* show the error you see. If both of those are correct then we've isolated to static frameworks and it at least focuses the research and allows us to perhaps go directly to https://github.com/firebase/quickstart-ios/tree/master/analytics for a direct repro against the upstream SDK?

**Comment by SaraChicaD** [comment]
thank you @mikehardy so here's what i did:
- made a new repo with your script and added `use_frameworks` in the Podfile
- got a successful build with that ^^
- i added these lines to the script, plus the `use_frameworks` in the Podfile:
```
echo "Adding react-native-firebase analytics app package"
yarn add "@react-native-firebase/analytics"
```
Then it broke and I got this error:
```
▸ Linking RNFBApp
▸ Copying RNFBAnalytics-umbrella.h
▸ Copying RNFBAnalyticsModule.h
▸ Processing RNFBAnalytics-Info.plist
▸ Compiling RNFBAnalyticsModule.m
▸ Compiling RNFBAnalytics-dummy.m
▸ Compiling RNFBAnalytics_vers.c
▸ Linking RNFBAnalytics

❌  Undefined symbols for architecture x86_64
> Symbol: _OBJC_CLASS_$_FIRAnalytics
> Referenced from: objc-class-ref in RNFBAnalyticsModule.o



❌  ld: symbol(s) not found for architecture x86_64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
- i commented out the `use_frameworks` line in the Podfile (with analytics) and it built successfully

i can put these up in github if that is helpful, let me know. 

> Interesting, and a little disappointing because I think this is going to boil down to a static frameworks issue so I'm going to be out of my depth immediately. First though - I'm an ex-Austinite and if I understand the situation correctly from my Austin family I hope you actually maintain power and stay warm this week!
> 
> So - to the static frameworks hypothesis, I think the permissions pods and the other stuff are just going to complicate the troubleshooting process
> 
> I bet if we just posted a repo from https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh raw, but altered the Podfile with an extra sed after this block https://github.com/mikehardy/rnfbdemo/blob/3b1095089e898c7629b8d530e1ad07b7998415d6/make-demo.sh#L42-L43 that toggled on `use_frameworks!` it would likely throw the same error?
> 
> We're in carnaval week in EC right now so I don't have a lot of time to help but if I were investigating my next step would be to completely hack out all of non-analytics react-native-firebase modules from the make-demo script (by just deleting the irrelevant lines in the shell script _and_ in App.js, and prove it builds (it should build!). Then I'd manually edit the Podfile to turn on static frameworks and it _should_ show the error you see. If both of those are correct then we've isolated to static frameworks and it at least focuses the research and allows us to perhaps go directly to https://github.com/firebase/quickstart-ios/tree/master/analytics for a direct repro against the upstream SDK?

**Comment by mikehardy** [comment]
Interesting, we are in the area then yes, combo of analytics and use frameworks is the reproducible failure if I understand correctly? But just core module (app) and use frameworks builds? This seems like it's going to be an upstream issue if I am correct with that understanding so I'm not sure if posting it would be useful. I would definitely peel a layer off and try the firebase-ios-sdk analytics Quickstart with use frameworks and it should fail, resulting in a reproduction case for the firebase team (which would actually be more useful as well - they have the skills on team to handle that where we don't get these scenarios hardly at all and I personally would be learning from scratch, slowly, to try to assist more)

**Comment by SaraChicaD** [comment]
ok, yes to both your questions. 

just to make sure i understand, you're saying this is an iOS issue, and you want me to make an iOS app and install the ios firebase sdk in it and then see if it fails in the same way? 

i can try to do that, but i'm not a native developer so not sure really even where to start. 

> Interesting, we are in the area then yes, combo of analytics and use frameworks is the reproducible failure if I understand correctly? But just core module (app) and use frameworks builds? This seems like it's going to be an upstream issue if I am correct with that understanding so I'm not sure if posting it would be useful. I would definitely peel a layer off and try the firebase-ios-sdk analytics Quickstart with use frameworks and it should fail, resulting in a reproduction case for the firebase team (which would actually be more useful as well - they have the skills on team to handle that where we don't get these scenarios hardly at all and I personally would be learning from scratch, slowly, to try to assist more)

**Comment by mikehardy** [comment]
That is what I'm saying, and I get the startup hurdle there - I'm Java/Android as a dev originally and very weak on the Objective-C / iOS side, however, the quickstart links I threw in above *should* (I really hope) take most of the pain out of the process. You should be able to basically clone that quickstart directory, make a test firebase project to get a firebase plist file, open it in Xcode and run it. There is not supposed to be much more to it - they are supposed to run as close to out of the box as possible. That should prove that things work when using the firebase-ios-sdk raw (instead of wrapped by react-native-firebase - which is a style google will not offer support for). Then a (hopefully) quick change to the Podfile to use_frameworks and it should duplicate the issue again, but this time with raw firebase-ios-sdk so google firebase team will take a look

If it does *not* reproduce the problem then it's something about our react-native-firebase layer here and I'll do my best to dig in to get it resolved

**Comment by SaraChicaD** [comment]
Ok, thank you, got an error, added the image in the `README` [here](https://github.com/SaraChicaD/FirebaseAnalyticsiOSTest/tree/master).

Let me know next steps or how else I can help, thank you. 

> That is what I'm saying, and I get the startup hurdle there - I'm Java/Android as a dev originally and very weak on the Objective-C / iOS side, however, the quickstart links I threw in above _should_ (I really hope) take most of the pain out of the process. You should be able to basically clone that quickstart directory, make a test firebase project to get a firebase plist file, open it in Xcode and run it. There is not supposed to be much more to it - they are supposed to run as close to out of the box as possible. That should prove that things work when using the firebase-ios-sdk raw (instead of wrapped by react-native-firebase - which is a style google will not offer support for). Then a (hopefully) quick change to the Podfile to use_frameworks and it should duplicate the issue again, but this time with raw firebase-ios-sdk so google firebase team will take a look
> 
> If it does _not_ reproduce the problem then it's something about our react-native-firebase layer here and I'll do my best to dig in to get it resolved

**Comment by mikehardy** [comment]
@SaraChicaD at this point it's time to take it to the firebase-ios-sdk team from google using their official template https://github.com/firebase/firebase-ios-sdk/issues/new?assignees=&labels=&template=bug_report.md - since you have a repo they can clone and investigate based off their official quickstart, this should be fruitful for you + them. I don't believe there is more I/we can do here as the react-native-firebase module but you can and should refer to this issue here so github can cross-link the issues between repos and I will listen in case there is something we need to. We collaborate with the firebase-ios-sdk a lot so I will do my best to pay attention in case it is on us to change something

**Comment by SaraChicaD** [comment]
thank you so much sir for your help and guidance! it was much appreciated!!

> @SaraChicaD at this point it's time to take it to the firebase-ios-sdk team from google using their official template https://github.com/firebase/firebase-ios-sdk/issues/new?assignees=&labels=&template=bug_report.md - since you have a repo they can clone and investigate based off their official quickstart, this should be fruitful for you + them. I don't believe there is more I/we can do here as the react-native-firebase module but you can and should refer to this issue here so github can cross-link the issues between repos and I will listen in case there is something we need to. We collaborate with the firebase-ios-sdk a lot so I will do my best to pay attention in case it is on us to change something

**Comment by mikehardy** [comment]
Happy to help. As mentioned a few times I'm weak on the Obj-C side personally and have very little experience with using these Pods (firebase-ios-sdk or react-native-firebase) with use_frameworks toggle in, so I'm interested in learning more myself. Hopefully the firebase-ios-sdk team is responsive (they usually are very responsive!) and you come away with a solution while I'm able to support this style of use better. Cheers

**Comment by SaraChicaD** [comment]
@mikehardy this is where that issue ended up, not sure it's very helpful -- are you getting anything from [this](https://github.com/firebase/firebase-ios-sdk/issues/7566#issuecomment-786963323)?

**Comment by mikehardy** [comment]
Thanks for linking that in - sorry there is not a clean resolution yet - I posted over there, but to say the same here: looks like I need try this personally (I haven't had time yet, apologies).

**Comment by mikehardy** [comment]
I'm still having difficulty building your specific project but I'm certain this is necessary to build react-native-frameworks in use_frameworks mode:

https://rnfirebase.io/#allow-ios-static-frameworks

Sorry I did not know that immediately - use_frameworks is not something I have any prior experience with, and I only just today had time to try these things out myself

The failures are see now are related to other modules, e.g.:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTViewManager", referenced from:
      _OBJC_CLASS_$_RNCSafeAreaViewManager in RNCSafeAreaViewManager.o
  "_OBJC_METACLASS_$_RCTViewManager", referenced from:
      _OBJC_METACLASS_$_RNCSafeAreaViewManager in RNCSafeAreaViewManager.o
  "_RCTRegisterModule", referenced from:
      +[RNCSafeAreaViewManager load] in RNCSafeAreaViewManager.o
  "_OBJC_METACLASS_$_RCTView", referenced from:
      _OBJC_METACLASS_$_RNCSafeAreaView in RNCSafeAreaView.o
  "_OBJC_CLASS_$_RCTView", referenced from:
      _OBJC_CLASS_$_RNCSafeAreaView in RNCSafeAreaView.o
  "_RCTScreenScale", referenced from:
      -[RNCSafeAreaView invalidateSafeAreaInsets] in RNCSafeAreaView.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The things I see about errors like this is that the Xcode project may have build settings that are not great (you might try to reproduce with a clean react-native project from template (`npx react-native init`) then re-adding the modules you want and your JS code

But I can definitely confirm a successful use_frameworks build with all react-native-firebase modules now via the make-demo.sh script after adding in the special Podfile variable, so I don't think this is actionable any more here

**Comment by SaraChicaD** [comment]
Hi @mikehardy thank you so much for looking into all of this and for the tip about static frameworks, I updated it on my end but had no luck.

So the project I created [here](https://github.com/SaraChicaD/FBAnalyticsTest) was a brand new React Native project created via `react-native init` 9 days ago. I added the frameworks info you suggested to the `Podfile` and a `GoogleService-Info.plist` file and am not getting it to build. 

What I am understanding you saying is that it works for you, so it must be a project setting on my end, is that correct?

**Comment by mikehardy** [comment]
Hmm - yes that is what I am saying. If you run the most current version of my make-demo script - with the static frameworks addition - as part of that execution (it will take a while...) the second iOS pod install / build it does is with static frameworks configured, and it passes reproducibly (since it's a script...) for me

I do not see static frameworks failures related to firebase anymore

As mentioned on the firebase-ios-sdk issue cross-linked here, I was also not able to successfully build your project. There is something about either the Xcode project or the large-ish list of other dependencies that is not compatible with use_frameworks. Not sure what unfortunately - the task I set myself was to prove react-native init + add react-native-firebase packages + configure for use_frameworks works, and I achieved that here:

https://github.com/mikehardy/rnfbdemo/commit/8f7a33921e77c882398fb1c607c0a6eee4501e70

**Comment by SaraChicaD** [comment]
@mikehardy -- thank you so much for all your help and the time you put into this, appreciate your help!

**Comment by mikehardy** [comment]
Sorry we couldn't get it all the way working, but happy to help and I learned a lot about static frameworks, that's for sure. If I were trying to move forward with static frameworks I'd bisect through dependencies now to find the other offenders, maybe they have some toggles to turn on support as well? Ideally you can get away without static_frameworks though, it seems to be a rare case and (clearly) not handled well. Good luck with your project

**Comment by grafosecondo** [comment]
Hi @SaraChicaD , did you manage to solve this. I'm stuck in the exact same problem.

- Added this to my podfile https://rnfirebase.io/#allow-ios-static-frameworks
- Cleaned the Framework Search Paths under Build Settings
- Cleaned my project

But nothing seems to work. Thank you for any help.

Cheers.

P.s.: This is my Podfile right now 

`
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

$RNFirebaseAnalyticsWithoutAdIdSupport = true
$RNFirebaseAsStaticFramework = true

target 'Project' do
  #config = use_native_modules!
  config = use_frameworks!
  use_react_native!(:path => config["reactNativePath"])

  pod 'Firebase/Crashlytics'
  pod 'FirebaseAnalytics'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'GoogleSignIn'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  target 'ProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end

target 'Project-tvOS' do
  # Pods for Project-tvOS

  target 'Project-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
`

**Comment by mikehardy** [comment]
This was resolved and worked in the end as far as I know, and during the investigation I added a mode to the demo script I maintain that proves the static lib compile style works:

https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh (does an `npx react-native run-ios` once normal, then reconfigures for static compile and does it again)

https://github.com/mikehardy/rnfbdemo/blob/e61e600a71a9d14e620c9c37e74bd7feee455fa4/make-demo.sh#L128-L136

```bash
  # This is how you configure for static frameworks:
  sed -i -e $'s/config = use_native_modules!/config = use_native_modules!\\\n  config = use_frameworks!\\\n  $RNFirebaseAsStaticFramework = true/' ios/Podfile


  # Workaround needed for static framework build only, regular build is fine.
  # https://github.com/facebook/react-native/issues/31149#issuecomment-800841668
  sed -i -e $'s/react_native_post_install(installer)/react_native_post_install(installer)\\\n    installer.pods_project.targets.each do |target|\\\n      if (target.name.eql?(\'FBReactNativeSpec\'))\\\n        target.build_phases.each do |build_phase|\\\n          if (build_phase.respond_to?(:name) \&\& build_phase.name.eql?(\'[CP-User] Generate Specs\'))\\\n            target.build_phases.move(build_phase, 0)\\\n          end\\\n        end\\\n      end\\\n    end/' ios/Podfile
  rm -f ios/Podfile.??
  cd ios && pod install && cd ..
  npx react-native run-ios
```

**Comment by SaraChicaD** [comment]
@grafosecondo it was solved, I think I deleted all `node_modules` and the `Pods` directory and started all over again with installing things, I'd also suggest closing your Metro bundler before restarting. Ultimately I added this, did what I just suggested, and that seemed to fix this error. Here's the start of that Podfile:

```
$RNFirebaseAsStaticFramework = true

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'


target 'App' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
```

**Comment by grafosecondo** [comment]
@mikehardy thank you for your quick reply, I tried what you suggeste during the weekend but had no luck yet.

@SaraChicaD thank you for the additional details, I'll try the whole thing again later tonight. Btw, do I need hermes to be enabled?

**Comment by SaraChicaD** [comment]
@grafosecondo i don't believe we were messing with Hermes, i don't think that played into what we were doing at the time.

**Comment by grafosecondo** [comment]
Dear @SaraChicaD and @mikehardy , thank you for your help, and for any further help you may provide. Unfortunately I am still stuck on this error

```ld: warning: ignoring file Pods/FirebaseAnalytics/Frameworks/FirebaseAnalytics.xcframework/ios-arm64_armv7/FirebaseAnalytics.framework/FirebaseAnalytics, missing required architecture x86_64 in file Pods/FirebaseAnalytics/Frameworks/FirebaseAnalytics.xcframework/ios-arm64_armv7/FirebaseAnalytics.framework/FirebaseAnalytics (2 slices)
ld: warning: ignoring file Pods/GoogleAppMeasurement/Frameworks/GoogleAppMeasurement.xcframework/ios-arm64_armv7/GoogleAppMeasurement.framework/GoogleAppMeasurement, missing required architecture x86_64 in file Pods/GoogleAppMeasurement/Frameworks/GoogleAppMeasurement.xcframework/ios-arm64_armv7/GoogleAppMeasurement.framework/GoogleAppMeasurement (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRAnalytics", referenced from:
      objc-class-ref in libRNFBAnalytics.a(RNFBAnalyticsModule.o)
     (maybe you meant: _OBJC_CLASS_$_FIRAnalyticsConfiguration)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

I changed my Podfile according to what Sara suggested, and I tried to compile with both my Framework search paths clean or with $(PROJECT_DIR)

The Podfile now being

```
$RNFirebaseAsStaticFramework = true

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Project' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'GoogleSignIn'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  target 'ProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end

target 'Project-tvOS' do
  # Pods for Project-tvOS

  target 'Project-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

**Comment by mikehardy** [comment]
This isn't a great idea however app measurement is not brought in I think, if you use the analytics pod without idfa. Check out the podfile variable you can define to switch analytics modes in analytics usage on rnfirebase.io. I consider this an experiment only to see if it compiles, I don't have other ideas sorry

**Comment by SaraChicaD** [comment]
@grafosecondo sorry i am also out of ideas, i get all crazy with clearing caches and restarting the computer when this stuff happens because it's saved me before, but outside of that i wouldn't know. we only implemented analytics, was there another library you were using that's related to firebase?

**Comment by grafosecondo** [comment]
@mikehardy thanks anyway! (yep I had the Analytics without IDFA variable set to true just on the first line, missed it when copied the Pod file)

@SaraChicaD yes, I am right in that situation, cleaning and rebuilding and hoping for the good. In case something else comes up to your mind, these are the firebase libraries I am importing in my package.json

``
    "@react-native-firebase/analytics": "12.0.0",
    "@react-native-firebase/app": "12.0.0",
    "@react-native-firebase/auth": "12.0.0",
    "@react-native-firebase/crashlytics": "12.0.0",
    "@react-native-firebase/messaging": "12.0.0",
``

I'll keep you guys posted, thanks!

**Comment by dooleyb1** [comment]
@grafosecondo & @SaraChicaD - Did you guys manage to come to a direct resolution for this issue?

**Comment by grafosecondo** [comment]
@dooleyb1 as far as I can remember the only thing that worked for me was to clear the whole project and start it over again from git clone into a new directory.

**Comment by dooleyb1** [comment]
> @dooleyb1 as far as I can remember the only thing that worked for me was to clear the whole project and start it over again from git clone into a new directory.

Not what I was hoping to hear 😆 Isn't an option for me unfortunately. Will keep digging.

**Comment by dooleyb1** [comment]
`$RNFirebaseAsStaticFramework = true` seemed to solve the issue for me
