### ISSUE TITLE
[🐛] Functions SDK Inconsistency

### ISSUE THREAD

**Issue by mbleigh** [invertase/react-native-firebase#4919]
## Issue

The iOS, Android, and JS SDKs for Firebase now support custom domain endpoints. In JS it looks like this:

```js
const someFunc = firebase.functions("https://my.custom.url").httpsCallable("someFunc");
await someFunc({data: 'here'}); // calls https://my.custom.url/someFunc instead of cloudfunctions.net URL
```

This was a fairly recent addition since previously only a region could be passed to the factory method. It would be nice for the React Native library to catch up to the change in the other SDKs. Thanks!

**Comment by mikehardy** [comment]
This likely won't happen without a community contribution - there is not a lot of general time available for me / Invertase to implement new features here just now. I agree with you it would be great though, and I'd be more than happy to collaborate with you or anyone to get a PR merged. The E2E tests app here serves as a great scaffold / harness to efficiently develop features in a nice tight code/test loop if you wanted to give it a try

c.f. https://github.com/invertase/react-native-firebase/blob/master/tests/README.md
and an example of a feature that starts with types, includes a javascript test, the javascript implementatio and then the two native parts https://github.com/invertase/react-native-firebase/pull/3814/files

**Comment by Salakar** [comment]
Thanks @mbleigh we'll get this looked at.

@dackers86 or @russellwheatley - would you mind taking a look at this this week, I've added added an internal ticket on the new board to track (RNFB-1).
