### ISSUE TITLE
[🐛] dynamicLinks - getInitialLink() is stack on Android

### ISSUE THREAD

**Issue by zvs001** [invertase/react-native-firebase#4922]
## Issue

Package works good for me in total. 
I experienced issue when tried run app on Android Emulator (SDK 24)

JS example:
```typescript
const link = await firebase.dynamicLinks().getInitialLink()
```

This promise is never resolved.

In logcat I found only:
```log
W GooglePlayServicesUtil: Google Play services out of date.  Requires 12451000 but found 11743470
```

Is it possible to resolve with null or throw some exception?

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/app": "^10.8.0",
    "@react-native-firebase/auth": "^10.8.0",
    "@react-native-firebase/dynamic-links": "^10.8.0",
    "@react-native-firebase/messaging": "^10.8.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

**Comment by mikehardy** [comment]
I think that's perhaps the wrong fix. If that's true (play services out of date) then you'll just have a problem somewhere else.

You want this instead I think https://rnfirebase.io/app/utils#android---checking-play-services

**Comment by zvs001** [comment]
It's true, checking can help.
I use it for some other places like auth, etc.

I'll add it like workaround.
But I don't believe to leave problem is good idea. Promises should be always resolved/rejected. Throwing exception can be the solution.
We had it on initial app start and it was bad surprise. Probably some developers will get same problem.

**Comment by mikehardy** [comment]
@zvs001 I will happily merge a PR resolving the issue, I don't like leaving problems either but we must prioritize yes? And if your play services are out of date it is hard to say anything else is worth doing. If you see this problem (promise not resolving) while the play services are up to date that would increase the priority.
