### ISSUE TITLE
phone auth android error

### ISSUE THREAD

**Issue by jcharbo** [invertase/react-native-firebase#493]
Hi everyone, I'm using the latest react-native-firebase with rn 48 on a real android device.  The first time I call signInWithPhoneNumber everything works great.  If I then signout and call it again I get the error "JSON.stringify cannot serialize cyclic structures." but then everything proceeds and works successfully.  Does anyone have any insight?

**Comment by chrisbianca** [comment]
@jcharbo can you attach a code snippet showing how you are using `signInWithPhoneNumber`?

**Comment by jcharbo** [comment]
Hi @chrisbianca , I can give you more code if necessary but this is where the error occurs:


  ```
  firebase.auth().signInWithPhoneNumber('+' + number)
      .then(confirmResult => {
        this.codeSent(confirmResult)
      })
      .catch(error => {
        console.log(error.message)
        //prints ﻿JSON.stringify cannot serialize cyclic structures.
      });
```

**Comment by chrisbianca** [comment]
@jcharbo There is nothing in our code base for `signInWithPhoneNumber` which should call JSON.stringify, so I'm fairly sure this is a problem in your code.

What is your `this.codeSent()` method doing?

**Comment by jcharbo** [comment]
Thanks @chrisbianca , you were right, it's on my end.  Sorry for the bother.
