### ISSUE TITLE
[🐛] TypeError: this._firestore.native.documentGet is not a function. (In 'this._firestore.native.documentGet(this.path, options)

### ISSUE THREAD

**Issue by ReijiTBK** [invertase/react-native-firebase#4930]
## Issue
Apologise for the last issue, Tried to put it in the template. do let me know if u need extra info :)
I've been trying to get firestore collection and document using @react-native-firebase/firestore however I keep getting a promise rejection
version inside package.json
"@react-native-firebase/firestore": "^10.8.0",

> TypeError: this._firestore.native.documentGet is not a function. (In 'this._firestore.native.documentGet(this.path, options)', 'this._firestore.native.documentGet' is undefined)

The code that i used is this

```javascript
import firestore from '@react-native-firebase/firestore';

let fireBaseVersionRecord = await firestore().collection(collection).doc(doc).get();
```

both collection name and doc name are valid 

This is only occurring on iOS, it works well on my android build.
i've verified, during pod install, Firestore has been included.

Really hope to get some help here.
Thank you

---

## Project Files

package.json
```
        "@react-native-firebase/analytics": "^7.6.4",
        "@react-native-firebase/app": "^8.4.5",
        "@react-native-firebase/firestore": "^10.8.0",
        "@react-native-firebase/messaging": "^7.9.0",
        "@react-navigation/bottom-tabs": "^5.8.0",
        "@react-navigation/material-bottom-tabs": "^5.2.16",
        "@react-navigation/native": "^5.7.3",
        "@react-navigation/stack": "^5.9.0",
```

### Javascript
```javascript
import firestore from '@react-native-firebase/firestore';
class ForceUpdateUtil {

    async checkForUpdate(){

        let collection = "collection"
        let doc = "version"        
        
        let fireBaseVersionRecord = await firestore().collection(collection).doc(doc).get();
        let versions = fireBaseVersionRecord.data();
    }

}

export const forceUpdateUtil = new ForceUpdateUtil();
```
<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:
Core Firebase modules
```ruby
 pod 'FirebaseCore'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/Firestore'
  pod 'Firebase/Crashlytics'
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  -       "@react-native-firebase/firestore": "^10.8.0",
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  -N

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
First thing I would do is get all on the same version - when we crossed from < version10 to >= version 10 we went to "one single version" - no more version numbers all over the place to remember, now every single react-native-firebase package should have the same version.

I bet when you upgrade them all to 10.8.0 (and maybe run `npx react-native-clean-project` then pod install and rebuild again) it will work

Do note that some of the major version bumps you cross will have breaking changes - there were not many serious breaking changes so it should be easy to handle all of them - but look in the release notes for each package you use in order to see if there is something to do, and get those versions aligned for a re-test

**Comment by ReijiTBK** [comment]
Hmmmm... tried cleaning cache and reinstalling everything with updated version.. it is still the same

**Comment by ReijiTBK** [comment]
I foudn the issue, i have to add this into the pod file for it to wor
  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'

**Comment by mikehardy** [comment]
You should not have to do that. That is an autolinking failure and shows an incorrect react-native installation or upgrade from react-native 0.59. You should fix your project as that should never be necessary. You can examine the Podfile from my demo script to see a working example with autolinking

**Comment by conor909** [comment]
I had this issue with expo, it was a case of rebuilding with `eas build`, that will sort the pods out, especially if you're in a managed expo project and don't want to access native code
