### ISSUE TITLE
Dev Tools crash

### ISSUE THREAD

**Issue by mackenziemance** [invertase/react-native-firebase#494]
### Issue

on iOS app builds but crashes when opening remote debugger, this only happens when library is installed.

<img width="571" alt="screen shot 2017-10-11 at 2 42 42 pm" src="https://user-images.githubusercontent.com/24738013/31459895-9e2be986-ae92-11e7-8beb-3d4ace39429c.png">

throws this error

<img width="681" alt="screen shot 2017-10-11 at 2 21 45 pm" src="https://user-images.githubusercontent.com/24738013/31458982-b85ab268-ae8f-11e7-868b-03af175ccf35.png">

### Environment

- macOS: High Sierra
- Xcode: 9.0 
- react-native: 0.48.4 
-  react-native-firebase: 3.0.2

**Comment by chrisbianca** [comment]
@mackenziemance If you check out the updated iOS installation instructions, you no longer need to set up React, Yoga and RNFirebase as pods.  Give that a go and hopefully this issue will go away.

**Comment by mackenziemance** [comment]
Ahhh perfect, thanks a bunch @chrisbianca
