### ISSUE TITLE
[🐛] Notification object is missing from remoteMessage when getInitialNotification triggered

### ISSUE THREAD

**Issue by alison-unmind** [invertase/react-native-firebase#4943]
## Issue

Upgrading to 7.8.10 to make use of the bug fix for[ issue 4052](https://github.com/invertase/react-native-firebase/issues/4052). We find that under the specific scenario described in that issue, the notification part of our message does not get included in the remoteMessage. 

Steps to replicate:
1. Send two push notifications with the following message payload:

```
{ 
  notification: {
    title: "Test title",
    body: "Test body",
  },
  data: {
    label: "Test label",
  }
}
```
2. Open one of them, then quit the app
3. Open the second one

Expected behaviour: For both notifications, when they are opened `getInitialNotification` gets called with a `remoteMessage` containing both data and notification
Actual behaviour: For the first notification opened, as expected `getInitialNotification` gets called with a `remoteMessage` containing both data and notification. For the second however, the `remoteMessage` only contains the data portion of the original message

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `7.8.10`, also replicated in `10.8.0`

- **Are you using `TypeScript`?**
  - `Y`, VERSION 4.1.3

**Comment by mikehardy** [comment]
Hi there!
We have seen this on android emulators, please confirm you are using a real device
You have ignored most of the template, please open a new issue and do not ignore the template

**Comment by alison-unmind** [comment]
Sorry, do you mean you have seen this working as expected (sending the notification as well as data through), on emulators?

I am seeing this issue occurring on both a physical device and on an emulator.

I'll have another go writing this up with more of the template 👍

**Comment by mikehardy** [comment]
> Sorry, do you mean you have seen this working as expected (sending the notification as well as data through), on emulators?

I never test messaging-related things with the expectation they will work, on emulators. Even though Android does deliver FCM to emulators (iOS does not even do that - simulators do not get a token, and do not receive FCM) there have been errors in the past so FCM testing for me is "device-only"

> I am seeing this issue occurring on both a physical device and on an emulator.

If it is reproducible on a device, then this could be a valid issue!

> I'll have another go writing this up with more of the template +1

Thank you - the template contains all sorts of things that we look for and can cause subtle errors, it really is important. Even better is the full JSON payload you send via the FCM REST API (minus any identifiers of course) plus an App.js that by itself - dropped in to a clean project like from https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh - reproduces the problem
