### ISSUE TITLE
[🐛] Uncaught exception GADInvalidInitializationException on IOS

### ISSUE THREAD

**Issue by RafilAlArsApps** [invertase/react-native-firebase#4944]
Hi
Sometimes I got Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without an application ID. Google AdMob publishers on IOS. firebase.json is presented and configured correctly in the project any body could help with this issue please.

**Comment by mikehardy** [comment]
First report of this. If this is a problem for you please open a new issue without ignoring the details in the template that we need to provide support
