### ISSUE TITLE
[🐛] FCM payload becomes empty on android devices when tapped after 15 minutes

### ISSUE THREAD

**Issue by sarathzerone** [invertase/react-native-firebase#4954]
We have used the @react-native-firebase/messaging package (7.7.1) for our React native hybrid app (Both ANdroid and iOS versions). But we have faced an issue with the package on the app quit state and background state with **messaging().getInitialNotification().then(async remoteMessage => { });** and **messaging().onNotificationOpenedApp(remoteMessage => {});** functions.

The remoteMessage on the mentioned function becomes null when tap on it hardly after **15 minutes** of it received in an android device. But we found no issues with its iOS version and on the Android studio emulator. The mentioned issue on the android real devices only with most android versions.

The received FCM payload is:
{
	"registration_ids": ["FCM_TOKEN"],
	"notification": {
		"body": "BODY_TEXT",
		"title": "TITLE_TEXT"
	},
	"priority": "high",
	"apns": {
		"headers": {
			"apns-priority": "5"
		}
	},
	"data": {
		"templates": "TEMPLATE_IDS_IN_COMMA_SEPERATE_FORMAT",
		"date": "DATE_VALUE",
		"additionalData": {
			"Type": "TYPE_VALUE"
		}
	}
}

We have written the messaging functions inside useEffect() hook and used the messaging().setBackgroundMessageHandler() on the index.js file for proper listening. 

Kindly help me to fix the issue.

**Comment by mikehardy** [comment]
Please open a new issue but include the details in the template so we can help - the FCM payload contents are very useful though! Please include those as well.
