### ISSUE TITLE
Banner Ad is not showing on Android

### ISSUE THREAD

**Issue by MadeinFrance** [invertase/react-native-firebase#4959]
Hi, I'm trying to display a `BANNER` in my Android App. It works on iOS but not on Android.

AdMob production dashboard:

* iOS: 3K requests/impressions, match rate 99%
* Android, ~5K active users over the last 28days, 100 requests, **30** impressions 🤔

## Issue 1:

From the logs on a **production** build on a real Android device I see that the onAdLoaded() event is triggered. No errors but no banners are showing.
In Android the simulator: `AdFailedToLoad: [Error: [admob/error-code-no-fill] The ad request was successful, but no ad was returned due to lack of ad inventory.]`. However I should see the banner in test mode.

## Issue 2:

I try to implement an interstitial and it seems that the interstitial `AdEventType.LOADED` is never triggered.

AdUnit is old enough, banner + interstitial are working in DEV mode. So I'm out of ideas. 

Can someone look into the [repository that I've created](https://github.com/MadeinFrance/rn-admob-integration-demo/) in order to help me to troubleshoot this?

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

```javascript

  const AdBanner = useMemo(
    () =>
      adMobConfigurationLoaded && (
        <BannerAd
          unitId={adUnitId}
          size={BannerAdSize.BANNER}
          requestOptions={{
            requestNonPersonalizedAdsOnly: false,
          }}
          onAdLoaded={async () => {
            console.log('banner loaded');
          }}
          onAdFailedToLoad={async (error) => {
            console.log('AdFailedToLoad for adUnitId ', adUnitId, error);
            setAdBannerHeight(0);
          }}
        />
      ),
    [adMobConfigurationLoaded],
  );
```

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 123.05 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.7.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.4.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_261 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

- **Platform that you're experiencing the issue on**:
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `latest`
- **`Firebase` module(s) you're using that has the issue:**
  - `AdMob`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

**Comment by MadeinFrance** [comment]
Need to provide new Ad unit IDs for the review process.

**Comment by McDreamy** [comment]
I have tried with test id and actual banner id. It always return AdFailedToLoad: [Error: [admob/error-code-no-fill] The ad request was successful, but no ad was returned due to lack of ad inventory.]

**Comment by MadeinFrance** [comment]
I was using a wrong Ad Unit ID. Please close this issue.

**Comment by mikehardy** [comment]
@MadeinFrance it's already closed but we do typically leave issues open (vs locking them) in case others find further discussion useful. Usually further discussion has low value but occasionally there are real gems so it seems like a valid tradeoff? Do feel free to unsubscribe from updates if you like though - there's a button on the right side of the github web ui on each issue for that. Cheers @MadeinFrance

**Comment by faizantariq1** [comment]
with the test ids. It always return AdFailedToLoad: [Error: [admob/error-code-no-fill] The ad request was successful, but no ad was returned due to lack of ad inventory.] any one?

**Comment by mikehardy** [comment]
@faizantariq1 admob is no longer in firebase at all ---> https://github.com/invertase/react-native-google-ads
