### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "RNFBApp":   In Podfile:     RNFBApp (from `../node_modules/@react-native-firebase/app`)

### ISSUE THREAD

**Issue by Total-Drive** [invertase/react-native-firebase#4967]
Worked for me,

Pod.file
Change **platform :ios, '9.0'** to **platform :ios, '10.0'**

_Originally posted by @bharatbrovitech in https://github.com/invertase/react-native-firebase/issues/2427#issuecomment-771624960_

**Comment by andersonaddo** [comment]
This isn't an issue
as stated [here](https://github.com/invertase/react-native-firebase/issues/2427#issuecomment-771648313), its mentioned in the changelogs.
