### ISSUE TITLE
ARC Semantic issue: No known class method for selector 'componentsWithLink:domain:'

### ISSUE THREAD

**Issue by lavinagandhi** [invertase/react-native-firebase#4975]
I am stuck with an issue since past 5+ hours, I am working on a react native project of version 0.59.0, it is a 1.5 years old project and it is working fine on android, but when building it for iOS, I was facing many issues one of which was:

ld: library not found for -lFirebaseCore

So to make it work, I included arm64 in excluded architecture and my build started working on simulator but my IPA was not working on a real device, again after removing arm64 and resolving multiple issues, I am stuck with the following issue which is coming in RNFirebaseLinks.m file as :

ARC Semantic Issue Group: No known class method for selector 'componentsWithLink:domain:'

Also sharing my device specifications:

macos: Macbook pro(11.0.1), chip: Apple M1, Xcode version: 12.4

PodFile content:

```ruby
**# Uncomment the next line to define a global platform for your project**
platform :ios, '10.0'
target 'PropertiesPublisherNew' do
**# Uncomment the next line if you're using Swift or would like to use dynamic frameworks**
#use_frameworks!
**# Pods for PropertiesPublisherNew**
pod 'Firebase/Core', '6.3.0'
pod 'Firebase/Messaging'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Database'
**# pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'**
**# pod 'RNScreens', :path => '../node_modules/react-native-screens'**
**# pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'**
#pod 'react-native-webview', :path => '../node_modules/react-native-webview'
target 'PropertiesPublisherNewTests' do
inherit! :search_paths
**# Pods for testing**
end
end
post_install do |installer|
installer.pods_project.build_configurations.each do |config|
config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
end
end
target 'PropertiesPublisherNew-tvOS' do
**# Uncomment the next line if you're using Swift or would like to use dynamic frameworks**
**# use_frameworks!**
**# Pods for PropertiesPublisherNew-tvOS**
target 'PropertiesPublisherNew-tvOSTests' do
inherit! :search_paths
**# Pods for testing**
end
end
```

Can anyone please help me out with this?

**Comment by mikehardy** [comment]
I do not believe there is any valid help for this other than updating things.
You are attempting to use a computing architecture that was released *after* your software is released.
You *can* hack around this in a fragile way that involves lots of tradeoffs (as you mentioned excluding archs etc) but that is not supported and spending time on it is not something we can do here

What we can do here is work to support the new architecture and then release software that does so, which we have done.

The primary change is to switch iOS packaging from '.framework' packaging, which only contain one binary for a given library, and that library *must not* contain more than one "slice" per architecture (so you can't have two arm64 slices, so you can't support arm64 simulator and arm64 real device) to '.xcframework' packaging that allows multiple binaries for a library, so all the slices you need are available.

The entire mobile software development ecosystem has done this work to support Apple Silicon over the last few months, and it's all working now as far as I know - in current stable versions

You should upgrade to current stable - you may examine what a clean current-stable project looks like by running this: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

Additionally, if you haven't seen it https://react-native-community.github.io/upgrade-helper/ is a great tool for getting through the upgrade steps on react-native, it works especially well if you step through the diffs one stable version increment at a time

I noticed you posted on stackoverflow as well - for workarounds etc you may receive traffic there, however as with here you did not post the actual full trace of the error. There is no indication of the compilation command that failed, and that would help anyone trying to diagnose the problem
