### ISSUE TITLE
[🐛] 🔥 Firebase sign in link not working from Gmail app on iOS when using a custom domain for dynamic links

### ISSUE THREAD

**Issue by rkbhochalya** [invertase/react-native-firebase#4976]
## Issue

Firebase sign-in link generated using custom dynamic link domain doesn't work when opened from Gmail app on iOS. `dynamicLinks().getInitialLink()` doesn't catch the link but `Linking.getInitialURL()` does in this case. Any other dynamic link except the sign-in links is surprisingly caught by `Linking.getInitialURL()` even when opened from the Gmail app. The sign-in link works when without any issue opened from the default Mail app.

I have created a minimal, reproducible example [here](https://github.com/rkbhochalya/Firebase-Login-Demo). Please let me know if you still need me to provide the contents of the project files. I'll be happy to update the issue.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 11.2.2
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 60.97 MB / 16.00 GB
    Shell: 5.0.17 - /usr/local/bin/bash
  Binaries:
    Node: 12.16.0 - /var/folders/ln/1y37d76j4fn9dcprvy5vn4j40000gn/T/yarn--1614696597989-0.04101918789238557/node
    Yarn: 1.22.10 - /var/folders/ln/1y37d76j4fn9dcprvy5vn4j40000gn/T/yarn--1614696597989-0.04101918789238557/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/rkb/.rvm/rubies/ruby-2.4.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-16 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `10.8.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `Auth, Dynamic Links`
- **Are you using `TypeScript`?**
  - `Y` & `3.9.9`

</p>
</details>

**Comment by mikehardy** [comment]
Hmm - I checked the repro repo quickly and it looks very clean and very up to date (big +1!)
My first take on this is that this smells like an upstream issue in firebase-ios-sdk, have you searched their repo https://github.com/firebase/firebase-ios-sdk ?
I don't know how react-native-firebase could be in between the AppDelegate and the link detection here and I think it might be in how their code handles it

As a workaround in the meantime, have you seen resolveLink? That was implemented specifically for cases where a dynamic link is not coming pre-resolved from the native SDKs (like in this case, where Linking gets it but firebase does not) so that you can at least force resolution and then proceed. I imagine you've seen it but just in case

**Comment by rkbhochalya** [comment]
> have you searched their repo https://github.com/firebase/firebase-ios-sdk ?

Thanks for the tip, @mikehardy. I just did and looks like it's already been reported there: https://github.com/firebase/firebase-ios-sdk/issues/7087.

> As a workaround in the meantime, have you seen resolveLink?

I did but `resolveLink` was throwing `NativeFirebaseError: [dynamicLinks/not-found] Dynamic link not found` error so I ended up using Google-provided domain as a workaround.

**Comment by mikehardy** [comment]
"glad" that you found an upstream issue that seems to fit (in quotes because it's still open, which I understand isn't great)

I'm most confused by your final comment that the link was not found error. If it is a valid dynamic link, how is that possible? :thinking:

**Comment by rkbhochalya** [comment]
I guess it gives the not found error because of the same upstream issue. A sign-in link looks like `https://link.customdomain.com?link=...` doesn't have a trailing `/` after removing the query and hence is not recognized as a valid dynamic link due to the bug.

**Comment by mikehardy** [comment]
Ah - perhaps yes. Note that you are in control of the link at that point though and could perhaps work around the missing-slash logic bomb by appending a slash to domain prior to sending it in - a hack sure, but I assume you did the custom domain work for a clean branding experience, and this might allow you to use all that work

**Comment by rkbhochalya** [comment]
Hmm, I do not think I can do something like this if that's what you meant:

```javascript
auth().sendSignInLinkToEmail(email, {
    handleCodeInApp: true,
    url: 'https://example.app/home',
    dynamicLinkDomain: 'link.example.app/',
});
```

Anyway, we are using a custom domain for sharable links from the app which aren't affected by this bug. Sign-in URLs aren't visible to the end-user and using a Google-provided domain would make no difference.

**Comment by mikehardy** [comment]
This appears to be moot based on your comment about non-visibility of sign in domains (which is good!)

I was thinking prior to resolveLink in the app you could break the URL apart and add a slash then re-assemble then resolve, but I'm making a lot of assumptions about flow there (that you are in app control flow, that you have the link from Linking, that you can reliably break it out and add slash and reassemble and that resolve link would work then etc). Not sure I'm correct in my assumptions - but as you say, moot point :-). Hopefully the upstream bug resolves either way - good luck with your project!

**Comment by rkbhochalya** [comment]
Ah, got it :)

Thanks @mikehardy!
