### ISSUE TITLE
[📚] Investigate Firebase / VPN network failures and document them

### ISSUE THREAD

**Issue by msmfsd** [invertase/react-native-firebase#4978]
## Documentation Feedback

Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:

- RNF Cloud Messaging - suggest you mention that `messaging.getToken()` can fail with `[messaging/unknown] - cannot connect to the network` if you are using a VPN. All other RNF calls including messaging work over VPN but get token gave me this error until I turned off VPN. There is no official documentation on Firebase docs though Google services do have VPN restrictions.

**Comment by mikehardy** [comment]
Indeed - I have actually noticed that I get firestore/unknown on VPN as well and have it logged to examine in my work project soon.

You mention "all other RNF calls including messaging work over VPN" but have you tried firestore?

VPN I was using is Private Internet Access, can you name the one you were using?

**Comment by msmfsd** [comment]
@mikehardy yes every other messaging call was working except get token. I tested this extensively on device too.

**Comment by msmfsd** [comment]
I should mention I only tested on iOS devices and Simulators on Mac.

**Comment by mikehardy** [comment]
this was on android for me, but I asked different questions :-)

- did you try firestore?
- what VPN provider

**Comment by msmfsd** [comment]
@mikehardy yes Firestore works fine, one of the most popular VPNs too. Note that I got this error on:
- iOS 13/14 (iPhone6s, iPhone 10/11 Simulators)
- React Native `0.63.3`
- "@react-native-firebase/app": "10.5.0",
- "@react-native-firebase/messaging": "10.5.1",
