### ISSUE TITLE
messaging.getInitialNotification gets react-native-navigation event instead of notification payload

### ISSUE THREAD

**Issue by alfonsodev** [invertase/react-native-firebase#498]
### Issue
- With the application closed, I send a push notification to my device.
- I press on the notification and the app opens
- on `componentDidMount` of the first component, I do call
```
      messaging.getInitialNotification().then((notification) => {
     })
```
unexpectedly the variable `notification` contains `react-native-navigation` data instead of the expected, notification payload
```
{
   ACTIVITY_PARAMS_BUNDLE: {
    // react-native-navigation data 
   },
  opened_from_tray: true
}
```
☝️  This is `react-native-navigation` data, is it posible that this module and react-native-navigation share the same event name in the Java code  ? 

### Environment

1. Application Target Platform: Android

2. Development Operating System: macOS

4. React Native version: 0.45.1

5. RNFirebase Version:  ^2.1.1

6. Firebase Module: 
firebase-messaging:11.0.1

**Comment by Ehesp** [comment]
Well this is a strange one! Will check it out. Could you also show us your android manifest please?

**Comment by alfonsodev** [comment]
@Ehesp sorry for the delay here is [my AndroidManifest.xml file](https://raw.githubusercontent.com/ghinwallc/mouj/3952cf200526fce92c86ada74fd8f3cc7e1cd1e1/mobile/android/app/src/main/AndroidManifest.xml?token=ACCE-uuR5QGFhTJKNa_HqAJ8rmNLleD_ks5Z-FRNwA%3D%3D) 
Somebody else reported #523 that perhaps is a duplicated of this issue.
thanks.

**Comment by Salakar** [comment]
Closing in favour of #523
