### ISSUE TITLE
Storage E2E tests have possible unhandled promise rejection

### ISSUE THREAD

**Issue by mikehardy** [invertase/react-native-firebase#4982]
Current code as of 20210303 mishandles promise rejects in storage e2e tests

Unsure if this is library code doing something unexpected, or just the test code with a problem.

Any recent CI E2E android run (and maybe iOS? unsure) will show it in the storage tests

Looks like this stack - I think all the same, about 5 or so per E2E run:

```
detox[4935] INFO:  at node_modules/jet/lib/node/console.js:20:15 
 Possible Unhandled Promise Rejection (id: 0):
Error: [storage/cancelled] User cancelled the operation.
NativeFirebaseError: [storage/cancelled] User cancelled the operation.
    at StorageDownloadTask._beginTask (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&sourceMapURL=true:233897:41)
    at StorageDownloadTask.on (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&sourceMapURL=true:236896:32)
    at Context.<anonymous> (/Users/mike/work/Invertase/react-native-firebase/packages/storage/e2e/StorageTask.e2e.js:799:18)
```

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by ha3** [comment]
Hey @mikehardy. I came across with, what I believe, the same issue. A cancellation triggers this condition in the following setups:

```
task.on("state_changed", snapshot => console.log(snapshot));
task.catch(err => console.log(err));
```

```
task.then(() => console.log("done"));
task.catch(err => console.log(err));
```

But if only the catch method is used, it doesn't:

```
task.catch(err => console.log(err));
```

Thank you!

**Comment by mikehardy** [comment]
Note the storage task pause/resume tests are commented out now that storage emulator is in there as the task is done before any pause can happen given the storage emulator is so much faster than working against the live / remove storage APIs, but this was not resolved.
