### ISSUE TITLE
(:fire:)[🐛] You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.auth().

### ISSUE THREAD

**Issue by sperardt** [invertase/react-native-firebase#4994]
## Issue

I have being using firebase/database for a while (woking super!) and now have added firebase/auth. I am implementing authentication using the following methods _createUserWithEmailAndPassword_ and _signInWithEmailAndPassword_. They work as expected in android, but in ios I always get the error: `Error: You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.auth().

Ensure you have either linked the module or added it to your projects Podfile.

See http://invertase.link/ios for full setup instructions.`

The link for full setup instruction is broken. Have tried all the recommendations found in 

1.  [https://github.com/invertase/react-native-firebase/issues/2959](url)
2.  [https://github.com/invertase/react-native-firebase/issues/2697](url)
3. [https://github.com/invertase/react-native-firebase/issues/4488](url)
4. and others 

nothing changes.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

`"@react-native-firebase/app": "^10.8.1",
    "@react-native-firebase/auth": "^10.8.1",
    "@react-native-firebase/database": "^10.8.1",`

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:
`require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

pod 'Firebase/Auth'

target 'myApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  
  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  target 'myAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
     end
  end
 
end

target 'myApp-tvOS' do
  # Pods for myApp-tvOS

  target 'myApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
`
```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 11.2.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 400.84 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `11.0.0 and 10.8.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Unsure what's going on, perhaps `npx react-native-clean-project` would help, perhaps you have forgotten `pod install` after adding the module? This definitely works though

If you can reproduce with https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh (which uses auth, and demonstrates ios working) then we can reopen, but otherwise this will be a local environment problem

**Comment by sperardt** [comment]
@mikehardy I have done all of what you are suggesting. How are you executing you script? I have ran it here and followed what it says to do for example, run the project on XCode and it **fails**!

**Comment by mikehardy** [comment]
I am doing the equivalent of git clone, then I run `./make-demo.sh` ? It works as recently as 2 days ago for me when I added the proof that iOS static frameworks also work. I'm also involved in two other very large codebases that use auth and they're both compiling and running just fine all day today, including one that I installed on a machine clean. Unfortunately, that which cannot be reproduced cannot be fixed.

You indicate you open it in Xcode and it **fails**. But you provide no information? Did you open the .xcworkspace file after running pod install? Then if it fails, what's the text of the command that fails, and the error messages associated with the failure?

**Comment by sperardt** [comment]
Funny, this is the third day I am trying to make it work on my machine. And Yes, I did all that. 

Are you running it on macOS? Which version? What is the version of your XCode? 
![Screen Shot 2021-03-05 at 1 11 09 PM](https://user-images.githubusercontent.com/25747543/110174076-6959a500-7db4-11eb-92e7-4fe934a9da59.png)

**Comment by mikehardy** [comment]
Every single thing current stable.
Latest stable version of every thing you can think of, including the thing you just thought of (but seriously!) with the only possible exception of react-native 0.64 in case that just came out

Your problem is from some Flipper thing. Note that I comment Flipper out completely in make-demo.sh because it causes build errors all the time.

If you search on the react-native or flipper repos you'll see evidence of it, especially in the react-native-releases issue tracking 0.64 as they worked on it 

https://duckduckgo.com/?t=canonical&q=event2%2Fevent-config.h+file+not+found+react-native

With no offense for those working on it and those that need it, from a maintainer perspective Flipper is a mess. If you remove it you might be building and running?

**Comment by sperardt** [comment]
I am confused. Have ran `npx react-native-clean-project` and `pod install` again and could build successfull. However, the app loaded is the one on path `rnfbdemo/rnfbdemo/App.js` I never got to see the code that load the firebase/auth.

I copied and pasted the code from `rnfbdemo/App.js` (the one with firebase imports) to  `rnfbdemo/rnfbdemo/App.js` and it got the same error I am reporting. See before/after pasting code attached.

My question now is: Is it loading the right file when you say it works?
![Screen Shot 2021-03-05 at 1 39 16 PM](https://user-images.githubusercontent.com/25747543/110176520-47622180-7db8-11eb-82a9-d43c71bb5c9c.png)
![Screen Shot 2021-03-05 at 1 39 46 PM](https://user-images.githubusercontent.com/25747543/110176522-48934e80-7db8-11eb-8b8e-1d9c6f951c80.png)

**Comment by mikehardy** [comment]
When I say it works, I mean it actually works. That of course includes that it loads the App.js that I coded up special to demonstrate it works by exercising each module just enough to show their native module was included and running. I won't have time to respond more, I'm sorry. I cannot reproduce any problem like this - if the auth module was not working we would be deluged with user reports and I (as a module user) would also know from about 3 clients plus my own company within the day. It's all working.
