### ISSUE TITLE
Calls to setPersistenceEnabled() must be made before any other usage of FirebaseDatabase instance

### ISSUE THREAD

**Issue by Ehesp** [invertase/react-native-firebase#5]
On Android logs, this error is appearing although the app does not crash.

![image](https://cloud.githubusercontent.com/assets/842078/23994943/1c7d1e98-0a3f-11e7-90b1-e26cb0e353e0.png)

**Comment by Ehesp** [comment]
Closed in favour of https://github.com/invertase/react-native-firebase/issues/97

**Comment by nateshmbhat** [comment]
See this site : https://stackoverflow.com/questions/507602/how-can-i-initialise-a-static-map
