### ISSUE TITLE
Uploading file on Android

### ISSUE THREAD

**Issue by Panda313** [invertase/react-native-firebase#50]
Hi guys,

The file upload works fine on iOS but on android, storage() send me the error "An unknown error has occurred" with no more informations

Any ideas ?

Best

Romain

**Comment by Ehesp** [comment]
Hey can you show some code please?

**Comment by Panda313** [comment]
ahah yes, sorry, I thought you were a magician ;)

Here you are : 
```
                        firebase.storage()
                        .ref(remotePath)
                        .putFile(localPath)
                        .then(uploadedFile => {
                            firebase.database()
                                .ref(linkPath)
                                .set({
                                    url: uploadedFile.downloadUrl
                                })
                                .then(() => {
                                    this.setState({
                                        loading:false,
                                        progression:1
                                    });
                                })
                        })
                        .catch(err => {
                            console.log("KAYO : " +err);
                        });
```

Cheers

**Comment by Ehesp** [comment]
@Salakar @chrisbianca this seems to throw the error that `promise` is not defined. 

```
export default class StorageTask {
  constructor(type: string, promise, storageRef) {
    this.type = type;
    this.ref = storageRef;
    this.promise = promise;
    this.storage = storageRef.storage;
    this.path = storageRef.path;

    // 'proxy' original promise
    this.then = promise.then.bind(promise);
    this.catch = promise.catch.bind(promise);
  }
```

Error on: `this.then = promise.then.bind(promise);`. Also just doing an `on` seems to throw an error as well?

**Comment by Panda313** [comment]
You want me to try something ?

**Comment by Ehesp** [comment]
@Panda313 Try downgrading to alpha10, and trying the following:

```
firestack.storage().ref(ref).putFile(uri)
            .on('state_changed', (snapshot) => {

            }, (err) => {

            }, (uploadedAsset) => {

            })
```

I mentioned to @Salakar that then then/catch wasn't working, and after checking out the web SDK further there's loads of ways to do the same thing (callbacks, promises, listeners etc). Salakar started some work on it, but I'm not sure what the current state of it is/whats broke.

**Comment by Panda313** [comment]
I tried, here is the result :  
```
Possible Unhandled Promise
Rejection (id: 0):
An unknown error has occurred.
Error: An unknown error has occurred.
    at createErrorFromErrorData 
```

and my code : 

```
firebase.storage().ref(remotePath).putFile(photoPath)
.on('state_changed', (snapshot) => {
    console.log("SNAPSHOT = ");
    console.log(snapshot);
}, (err) => {
    console.log("KAYO :( " +err);
}, (uploadedAsset) => {
    console.log("UPLOAD ASSETS ");
});
```
I logged SNAPSHOT 2 times (one with state "running" and one with state "success")

**Comment by Salakar** [comment]
I fixed this issue 9 days ago, just needs a new release - haven't been able to test it fully hence no release, could you try install the npm module direct from github and let me know if it fixes yours issue - if so I'll do a release.

**Comment by Panda313** [comment]
I took your code from github but still got the same error (running on simulator)

**Comment by Panda313** [comment]
I got the last version and I have this error now on iOS : 

"_firebase2.default.storage(...).ref(...).putFile(...).then is not a function"

Thanks

**Comment by Panda313** [comment]
Fixed it on iOS using : 

`const unsubscribe = firebase.storage()
                        .ref('/files/1234')
                        .putFile('/path/to/file/1234')
                        .on('state_changed', snapshot => {
                            //Current upload state
                        }, err => {
                            //Error
                            unsubscribe();
                        }, uploadedFile => {
                            //Success
                            unsubscribe();
                        });`

Still not working on android

**Comment by Panda313** [comment]
The error is now : 

> Possible Unhandled Promise Rejection (id: 0):
An unknown error has occurred.
Error: An unknown error has occurred.
    at createErrorFromErrorData (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:5312:15)
    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:5270:25
    at MessageQueue.__invokeCallback (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:5592:16)
    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:5453:16
    at guard (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:5392:5)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:5452:7)
    at addEventListener (file:///Applications/React%20Native%20Debugger.app/Contents/Resources/app.asar/js/RNDebuggerWorker.js:1:21894)

**Comment by Panda313** [comment]
FOUND IT !

My local file path start with "file:/", wich is not a probleme on iOS but on Android, you're still adding "file:/". Wich make it crash.

I juste remove "file:/" from the local path and it works.

Cheers

**Comment by MssMaster** [comment]
Getting the same issue 

**In case of Android it's throwing unhandle promise exception.**
**Android uri**:-content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F290/ORIGINAL/NONE/1167943080

**In case of iOS it's working absolutely fine**

**iOS uri** :- 
file:///Users/mss/Library/Developer/CoreSimulator/Devices/4B0AD1AA-B6D9-4D22-95A3-58462E23D48A/data/Containers/Data/Application/6A932F67-858A-4878-B595-4E0D41B60F8A/Documents/images/9AAA4502-527A-4727-A3FD-E26A976C818A.jpg

My code for uploading image to firebase storage is as folows:

```
let name = imageUri.substring(
      imageUri.lastIndexOf("/") + 1,
      imageUri.length
    );
    console.log(name);
    const ext = file.type.split("/").pop(); // Extract image extension
    console.log(ext);
    const filename;
    if (Platform.OS === 'ios') {
       filename = {name};
    }else{
       filename = `${name}.${ext}`;
    }
     // Generate unique name
    console.log(filename);
    // displayConsole(name,' ', ext, ' ', filename,' ', imageUri);

 
    firebase
      .storage()
      .ref(`Kliit/${filename}`)
      .putFile(imageUri)
      .on(
        firebase.storage.TaskEvent.STATE_CHANGED,
        snapshot => {
          let state = {};
          // state = {
          //   ...state,
          //   progress: (snapshot.bytesTransferred / snapshot.totalBytes) * 100 // Calculate progress percentage
          // };
          if (snapshot.state === firebase.storage.TaskState.SUCCESS) {
              const userData = {
                params: {
                  firstName : firstName.trim(),
                  lastName : lastName.trim(),
                  dob,
                  pronounsArr,
                  profileImageUrl : snapshot.downloadURL
                },
                navigation,
              }
              uploadUserData(userData)
          }
        },
        error => {
          unsubscribe();
          alert('Sorry, Try again.');
        }
      );
```

**Comment by Piyush132000** [comment]
Possible Unhandled Promise Rejection (id: 17):
Error: [storage/file-not-found] The local file specified does not exist on the device.
NativeFirebaseError: [storage/file-not-found] The local file specified does not exist on the device.


i am getting this every time on uploading image .

**Comment by mikehardy** [comment]
Can you please open a fresh issue?

**Comment by Piyush132000** [comment]
please if anyone know my problem please reply
