### ISSUE TITLE
[Android][messaging] No notification heads up

### ISSUE THREAD

**Issue by theohdv** [invertase/react-native-firebase#500]
### Issue

This is for **Android** only.
**Android notification heads up** are never displayed (app killed or in background).
My notifications are directly displayed in the notification tray.
I tried by setting "priority" (normal & high) but nothing changed.

Here the format of my notifications:
```php
"registration_ids" => [],
"notification" => [
        "sound" => "default",
	"title" => "hello",
        "body" => "world"
],
"data" => [
	"key" => "foobar",
	"key2" => "foobar",
]
```

I would like something like that:

![image](https://user-images.githubusercontent.com/26060802/31508376-bcff71aa-af75-11e7-97f7-6faabab13b0e.png)

### Environment

1. Application Target Platform:  Android

2. Development Operating System: macOS Sierra

4. React Native version: 0.48.4

5. RNFirebase Version: 3.0.3

**Comment by Ehesp** [comment]
Could you try to add the `show_in_foreground` prop, like our tests here: https://github.com/invertase/react-native-firebase/blob/ceedf9b85aed2f66954a3ccdcdf7e23e8715ee0e/tests/src/tests/messaging/messagingTests.js#L138

**Comment by theohdv** [comment]
I tried but it did not change anything. But I think this property is only for localeNotification not for remote one. 
And I want the heads up to display when the app is in background or and it has been killed not when the app is in foreground (Remote notification behavior).

**Comment by theohdv** [comment]
I just noticed that this is a duplicate of #357 but i would like to not use the "custom_notification" approach, is there a proper solution now to do that? (if not, can close the issue)

**Comment by samueljseay** [comment]
@theohdv as far as I can tell from the code in `MessagingService` a notification needs to meet 2 conditions to send in foreground. One is from the firebase spec `show_in_foreground`. The other is that it requires a `custom_notification` property to be set on the data attribute.

@chrisbianca this seems non-standard, I was wondering, why do we need to provide that attribute? I guess at this point I may as well write my own `FirebaseMessagingService`?

**Comment by chrisbianca** [comment]
Thanks for reporting.  We're aware of lots of issues with notifications and will be addressing them all as part of the v3.2.0 release stream.  Please see https://github.com/invertase/react-native-firebase/issues/595 for updates.

**Comment by bm-software** [comment]
@chrisbianca I'm experiencing this issue too. If I delete the `notification` property completely I'm able to get notification but only if the app is running in foreground or in background. To get the notification when the app is killed the `notification` property is required but it won't display as an heads up notification. So here there is a loop :) When do you plan to fix that behaviour?

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)

**Comment by tpucci** [comment]
Hi ! Congrats releasing RNFirebase v4!
Still, I experience the same issue as describe here. How do we create a notification show up on Android ?

**Comment by maggialejandro** [comment]
I'm facing the same issue.
react-native-firebase 4.2.0
react-native 0.53.3

The notification arrives but it is show on the tray bar only.

**Comment by kevinEsherick** [comment]
@maggialejandro @tpucci any luck? This is killing me right now

**Comment by maggialejandro** [comment]
@kevinEsherick not yet.
We were using react-native-fcm so it never worked to us so far

This is our FCM payload

```php
$post = [
  'to' => $to,
  'priority' => 'high',
  'content_available' => true,
  'show_in_foreground' => true,
  
  'notification' => array(
    'time_to_live' => 172800,
    "sound" => "default",
    "lights" => true,
    'color' => '#3f78c3',

    'title' => $notification['title'],
    'body'  => $notification['body'],
    
    'priority' => 'high',
    'tag'   => $notification['id'],

    'icon'      => 'ic_notif',
    'image'     => 'ic_launcher',
    'largeIcon' => 'ic_launcher',
    'smallIcon' => 'ic_launcher'
  ),

  'data' => [
    'notificationId' => $notification['notificationId'],
    'title' => $notification['title'],
    'body'  => $notification['body'],
    'iso' => $notification['iso'],
  ],
];
```

**Comment by avinashwigroup** [comment]
Please open this issue.  It is still not working.

**Comment by whitefox920** [comment]
Guys, in my case the issue was notification settings in phone settings -> installed apps -> Custom notification. When I've added `android:showOnLockScreen="true"` to the root `application` node in AndroidManifest - notifications started showing up. 

-> on iOS notifications are received only on release build. Don't know if Android debug build of app can receive them.

-> Android Studio's Logcat is worth checking - here: https://stackoverflow.com/questions/25610936/enable-logcat-on-release-build-in-android-studio you can see how to access device' logs on release build. Even if nothing shows up - there are some logs worth to check.

-> I have a different problem - notifications showing up only on locked screen. Showing on unlocked screen is indicated by 'floating notifications' setting which have to be turned on by the user. I don't know how to set it up automatically on app install. Anyone knows something about it? 😃

**Comment by eladglobalbit** [comment]
Someone can share the json that he send? @theohdv @edwardrowens  

I send this and this does not work for me
`{
 "to" : "phone-token",
 "content_available": true,
 "notification" : {
     "body" : "Body of Your Notification",
     "title": "Title of Your Notification",
     "content_available" : true,
     "priority" : 10,
     "sound": "default"
 },
 "data" : {
     "body" : "Body of Your Notification in Data",
     "title": "Title of Your Notification in Title",
     "key_1" : "Value for key_1",
     "key_2" : "Value for key_2",
     "android_channel_id": "Hip-chanelId",
      "sound": "default"
 },
 	"priority" : 10
 
}`

**Comment by eladglobalbit** [comment]
@theohdv If u can tell how u fixed that issue this will be great!

**Comment by akuch-dindinn** [comment]
The problem still not solved :( What to do?

**Comment by avianezbq** [comment]
Hi!
Why is this closed, the problem still happens... (version 5.2.x)

**Comment by mi-mazouz** [comment]
I still have the same issue! Why you closed issues not resolved!?

**Comment by mikehardy** [comment]
@mi-mazouz using your same words:

You have not opened a new issue following the issue template! Why don't you open a new issue and supply us with the necessary information to help!?

But more nicely, this issue was closed almost 2 years ago. So much has changed. And it requires lots of information about your environment to troubleshoot. Please open a new issue.

**Comment by Salakar** [comment]
The docs are clear on this also in a big yellow warning:

![image](https://user-images.githubusercontent.com/5347038/58746062-c000b500-8451-11e9-8720-e710c062a3d9.png)

Most if not all of the heads-up notification issues I've come across have been related to that, so I'd start there.

Locking this issue.
