### ISSUE TITLE
🔥 DynamicLinks iOS: dynamic link doesn't survive App Store installation

### ISSUE THREAD

**Issue by drencewicz** [invertase/react-native-firebase#5011]
## Issue

Describe your issue here

Firebase Dynamic Link doesn't survive installation from App Store.  The link opens the App Store to the correct listing, but the url always shows null on dynamicLink.getInitialUrl().  This works perfectly fine on Android.  Please see the snippet below.
---

### Javascript

<details><summary>Click To Expand</summary>
<p>
import dynamicLinks, {
  FirebaseDynamicLinksTypes,
} from '@react-native-firebase/dynamic-links';
import {isNil} from 'lodash';

useEffect(() => {
    try {
      dynamicLinks()
        .getInitialLink()
        .then((link: FirebaseDynamicLinksTypes.DynamicLink | null) => {
          if (isNil(link) || isNil(link.url)) {
            return;
          }
          initialRouteName = 'MainTab';
          processLink(link.url);
        });
    } catch (e) {}
    const unsubscribe = dynamicLinks().onLink(handleDynamicLink);
    return () => unsubscribe();
  }, []);

const handleDynamicLink = useCallback(
    (link: FirebaseDynamicLinksTypes.DynamicLink) => {
      if (isNil(link.url)) {
        return;
      }
      processLink(link.url);
    },
    [processLink],
  );

const processLink = useCallback(
    (url: String) => { .....}

#### `package.json`:

{
  "name": "MyApp",
  "version": "2.2.2",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "postinstall": "react-native-schemes-manager all",
    "env:staging": "node scripts/set-environment.js staging",
    "env:dev": "node scripts/set-environment.js development",
    "env:prod": "node scripts/set-environment.js production",
    "ios:dev:debug": "yarn env:dev && npx react-native run-ios --configuration DevDebug --scheme MyApp-Dev",
    "ios:dev:release": "yarn env:dev && npx react-native run-ios --configuration DevRelease --scheme MyApp-Dev",
    "ios:stage:debug": "yarn env:staging && npx react-native run-ios --configuration StageDebug --scheme MyApp-Stage",
    "ios:stage:release": "yarn env:staging && npx react-native run-ios --configuration StageRelease --scheme MyApp-Stage",
    "ios:prod": "yarn env:prod && npx react-native run-ios --configuration Production --scheme MyApp-Production",
    "android:dev:debug": "yarn env:dev && npx react-native run-android --variant=devDebug --appIdSuffix=dev",
    "android:dev:release": "yarn env:dev && npx react-native run-android --variant=devRelease --appIdSuffix=dev",
    "android:stage:debug": "yarn env:staging && npx react-native run-android --variant=stageDebug --appIdSuffix=stage",
    "android:stage:release": "yarn env:staging && npx react-native run-android --variant=stageRelease --appIdSuffix=stage",
    "android:prod:debug": "yarn env:prod && npx react-native run-android --variant=prodDebug",
    "android:prod:release": "yarn env:prod && npx react-native run-android --variant=prodRelease"
  },
  "xcodeSchemes": {
    "Debug": [
      "DevDebug",
      "StageDebug"
    ],
    "Release": [
      "DevRelease",
      "StageRelease",
      "Production"
    ],
    "projectDirectory": "ios",
    "settings": {}
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.31",
    "@fortawesome/free-brands-svg-icons": "^5.15.1",
    "@fortawesome/free-solid-svg-icons": "^5.15.1",
    "@fortawesome/pro-light-svg-icons": "^5.15.0",
    "@fortawesome/pro-regular-svg-icons": "^5.15.0",
    "@fortawesome/pro-solid-svg-icons": "^5.15.0",
    "@fortawesome/react-native-fontawesome": "^0.2.6",
    "@react-native-async-storage/async-storage": "^1.13.2",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/datetimepicker": "^3.0.9",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-firebase/analytics": "^11.0.0",
    "@react-native-firebase/app": "^11.0.0",
    "@react-native-firebase/dynamic-links": "^11.0.0",
    "@react-native-firebase/messaging": "^11.0.0",
    "@react-native-picker/picker": "^1.9.2",
    "@react-navigation/bottom-tabs": "^5.9.1",
    "@react-navigation/material-top-tabs": "^5.2.19",
    "@react-navigation/native": "^5.7.5",
    "@react-navigation/stack": "^5.9.2",
    "@sentry/react-native": "^2.2.0",
    "algoliasearch": "^4.5.1",
    "axios": "^0.21.1",
    "core-js": "^3",
    "express": "^4.17.1",
    "intl": "^1.2.5",
    "joi": "^17.3.0",
    "lodash": "^4.17.20",
    "luhn": "^2.4.1",
    "moment": "^2.29.0",
    "plaid": "^8.0.0",
    "react": "17.0.1",
    "react-native": "~0.63.4",
    "react-native-appsflyer": "^6.0.50",
    "react-native-branch": "^5.0.1",
    "react-native-contacts": "^6.0.0",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-get-random-values": "^1.5.0",
    "react-native-image-crop-picker": "^0.35.3",
    "react-native-inappbrowser-reborn": "^3.5.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.2",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-paper": "^4.2.0",
    "react-native-permissions": "^3.0.0",
    "react-native-plaid-link-sdk": "^5.0.2",
    "react-native-reanimated": "^1.13.1",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.11.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.0",
    "react-native-swiper": "^1.6.0",
    "react-native-tab-view": "^2.15.2",
    "react-native-vector-icons": "^8.0.0",
    "react-native-video": "^5.1.0-alpha8",
    "react-native-video-controls": "^2.7.1",
    "react-native-view-shot": "3.1.2",
    "react-native-webview": "^11.2.1",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "redux-actions": "^2.6.5",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3",
    "reselect": "^4.0.0",
    "rn-fetch-blob": "^0.12.0",
    "typescript-fsa": "^3.0.0",
    "uuid": "^8.3.2",
    "validate": "^5.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.20",
    "@types/lodash": "^4.14.161",
    "@types/react-native": "^0.63.2",
    "@types/react-redux": "^7.1.9",
    "@types/react-test-renderer": "^17.0.0",
    "@types/redux-logger": "^3.0.8",
    "@types/uuid": "^8.3.0",
    "@typescript-eslint/eslint-plugin": "^4.14.2",
    "@typescript-eslint/parser": "^4.14.2",
    "babel-jest": "^26.6.3",
    "babel-plugin-module-resolver": "^4.0.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "^7.19.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "jest": "^26.6.3",
    "jest-extended": "^0.11.5",
    "metro-react-native-babel-preset": "^0.65.0",
    "react-native-schemes-manager": "^2.0.0",
    "react-navigation-hooks": "^1.1.0",
    "react-test-renderer": "17.0.1",
    "redux-saga-test-plan": "^4.0.1",
    "typescript": "^4.1.3"
  }
}

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
project 'MyApp',
    'DevDebug' => :debug,
    'StageDebug' => :debug,
    'Debug' => :debug,
    'DevRelease' => :release,
    'StageRelease' => :release,
    'Production' => :release,
    'Release' => :release

platform :ios, '11.0'

target 'MyApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  pod 'Plaid', '~> 1.1.34'

  target 'MyApp' do
    inherit! :complete
    # Pods for testing
  end

```ruby
# N/A
```

#### `AppDelegate.m`:

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>
#import "RNSplashScreen.h"
#import "KDataCollector.h"

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {

  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  [FIRAnalytics setAnalyticsCollectionEnabled:YES];

  // Setup Kount Data Collector
  [[KDataCollector sharedCollector] setMerchantID:101201];
  [[KDataCollector sharedCollector] setLocationCollectorConfig:KLocationCollectorConfigPassive];
//   [[KDataCollector sharedCollector] setEnvironment:KEnvironmentTest];
  [[KDataCollector sharedCollector] setEnvironment:KEnvironmentProduction];

#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"GiftYa"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [RNSplashScreen show];
  return YES;
}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {

// notify AppsFlyerLib
 [[AppsFlyerLib shared] registerUninstall:deviceToken];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.2.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 177.64 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5/12E5244e - /usr/bin/xcodebuild
  Languages:
    Java: 10.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: ~0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y` & `3.0.0`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Did you see this? #2660 

I think this is a duplicate
