### ISSUE TITLE
How to avoid opening Safari for phone auth reCAPTCHA?

### ISSUE THREAD

**Issue by steventilator** [invertase/react-native-firebase#5013]
My app got rejected by Apple because of:

> We noticed that the user is taken to Safari to sign in or register for an account, which provides a poor user experience.

The problem is that Safari is opened for the phone auth reCAPTCHA. They recommend using a WebView (I believe) instead of switching to Safari:

> We recommend implementing the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page.

I saw [this in the Firebase docs](https://firebase.google.com/docs/auth/ios/phone-auth#set-up-recaptcha-verification), but honestly I don't have a clue about how that would work:

> Optional: If you want to customize the way your app presents the SFSafariViewController or UIWebView when displaying the reCAPTCHA to the user, create a custom class that conforms to the FIRAuthUIDelegate protocol, and pass it to verifyPhoneNumber:UIDelegate:completion:. 

Could anybody help me out? How can I achieve this?

**Comment by mikehardy** [comment]
I think this is best asked on stackoverflow (with firebase tags! the official team does respond there) or firebase-ios-sdk - we don't do anything special here, it is all firebase-ios-sdk

**Comment by steventilator** [comment]
Okay, thanks. I did: https://stackoverflow.com/questions/66585902/how-to-avoid-opening-safari-for-firebase-phone-auth-recaptcha-on-ios
