### ISSUE TITLE
[firestore][v3.0.3] Setting with property-value "undefined" results in error

### ISSUE THREAD

**Issue by DavidKuennen** [invertase/react-native-firebase#502]
It's because this is being send (notice `isNewDay` is empty): 
![image](https://user-images.githubusercontent.com/7766565/31513446-b0cccc16-af8e-11e7-9359-51301ca95d16.png)

And [here](https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/firestore/FirestoreSerialize.java#L250) you're trying to `.getString("type")` of `isNewDay`, which results in 

![image](https://user-images.githubusercontent.com/7766565/31513610-26bf0e70-af8f-11e7-8b11-0500376f54ec.png)

For me to have it work again I just checked for key type in that method first and returning null if it doesn't exist. So I can still work with it. 

Application Target Platform: only tested on android
Development Operating System: Windows 10
Build Tools: Android Studio
React Native version: 0.48.4
RNFirebase Version: 3.0.3
Firebase Module: Firestore

**Comment by chrisbianca** [comment]
@DavidKuennen Undefined is an interesting one to deal with.  Would you expect this to act as if the field was `null`?  The alternative would be for it for it to act as if you'd specified `firebase.firestore.FieldValue.delete()` and remove the field completely.

I'm leaning towards the first approach, given that the `delete()` functionality is so specific.

**Comment by chrisbianca** [comment]
Ok, for the time-being I've set `undefined` to act as `null`.  If anybody thinks this is the wrong approach please let me know and we can look at changing.

@DavidKuennen I've pushed this up - we'll probably do a release later today with it in.

**Comment by DavidKuennen** [comment]
Hmm interesting question. In the previous versions of RNFirebase it wasn't setting the value at all in firestore when I send undefined. But that was only upon creation of a document. I don't really know what happend when I changed an existing value to undefined, since I don't remember ever doing that. 
If it'd be necessarry to use `firebase.firestore.FieldValue.delete()` to remove that field, it is indeed too much and a simple null would be sufficient.

However, are you sure you'd need to use the `delete()` function? Would't it be sufficient to change [this](https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/firestore/FirestoreSerialize.java#L233) to something like this: 

```java
while (iterator.hasNextKey()) {
    String key = iterator.nextKey();
    if(readableMap.getMap(key).hasKey("type")) {
        map.put(key, parseTypeMap(firestore, readableMap.getMap(key)));
    }
}
```

.. since firestore replaces the whole document with that new map (unless "merge" is being used)? 

Does anyone know how the official web-sdk of firestore handles undefined values?

**Comment by chrisbianca** [comment]
I think we need to be explicit with it's behaviour rather than just omitting the field. Otherwise, as you mention, when `merge` is specified, there could be some ambiguity with how the field is handled.  The user could set the field as `undefined` on the JS, do a merge and the field would retain it's previous value.

I haven't got anything set up with the official Web SDK to see how it's handled there.  If you happen to, it would be great to let us know how it behaves.  If not, I feel the `null` approach works for now and it's a fairly straightforward change to explicitly remove the field if we find that's how it should work.

**Comment by DavidKuennen** [comment]
Alright, I'll let you know when I find out or have new information regarding this case. 

And thanks for fixing the bug @chrisbianca. :+1:
