### ISSUE TITLE
[🐛] iOS randomly stops receiving notifications after restarting the app

### ISSUE THREAD

**Issue by IngyuTae** [invertase/react-native-firebase#5021]
## Issue

Basically, this is very similar to https://github.com/invertase/react-native-firebase/issues/3476#issuecomment-646942888 as it works fine at first but, after restarting(close/open) app several times it suddenly stops working with error codes `messaging/invalid-argument` and `messaging/registration-token-not-registered` in order.

I know this kind of issues are very hard to debug due to external dependencies and privacy but I'm pretty sure that this is **NOT** about

- installation/setup
- not working
- wrong package version
- messaging priority
- partially working in foreground/background
- notification token inconsistency
- running in the simulator 
- platform issues (app id, key, certification, provisioning, ...)
- react-native-splash-screen

In my case, ~~it's working perfectly on Android and~~ normally working well on iOS until the issue has been triggered. I could not provide reproducible code though I want to share what I tried and a temporary fix I found.

### Reproduce

1. start the app /w console.log(token)
2. send notification - it works
3. close/open the app (always get the same token)
4. send notification - normally it works but randomly it fails
5. repeat 3-4
6. once it fails, any following requests are denied
7. close/open the app (multiple times)
8. it starts working again (the token has been changed)

### What I tried,

- upgrade firebase packages and pods to the latest version
- check the official docs and configs twice
- read most of the similar issues in the repo
- remove suspicious packages one by one

### And I got

- it's totally random
- when it failed, the notification token was treated as invalid
- it seems like the token console.logged was already expired
- after removing `firebase-analytics` package, it works! 🤔
- **OR** method swizzling disabled and mapping the APNs token manually, it works!
  - `FirebaseAppDelegateProxyEnabled` = `NO`
  - https://firebase.google.com/docs/cloud-messaging/ios/client

``` objective-c
// With "FirebaseAppDelegateProxyEnabled": NO
- (void)application:(UIApplication *)application
    didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    [FIRMessaging messaging].APNSToken = deviceToken;
}
```

However, disabling method swizzling affects other firebase packages. In my case, dynamic links don't work so I had to roll back. Installing firebase-analytics is recommended and `FirebaseAppDelegateProxyEnabled` is `YES` by default, so chances are you will be going through the same issue.

If you have been run into a similar situation give this a try and please share the result. 🙏

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "react": "16.13.1",
    "react-native": "0.63.3",
    "@react-native-firebase/analytics": "^11.0.0",
    "@react-native-firebase/app": "^11.0.0",
    "@react-native-firebase/dynamic-links": "^11.0.0",
    "@react-native-firebase/firestore": "^11.0.0",
    "@react-native-firebase/functions": "^11.0.0",
    "@react-native-firebase/messaging": "^11.0.0",
```

#### `app`:

```ts
useEffect(() => {
    messaging()
      .getInitialNotification()
      .then((remoteMessage) => {
        console.log('messaging().getInitialNotification', { remoteMessage });
        remoteMessage && onPress(remoteMessage);
      });
  }, [onPress]);

  useEffect(() => {
    const unsubscribe = messaging().onNotificationOpenedApp((remoteMessage) => {
      console.log('messaging().onNotificationOpenedApp', { remoteMessage });
      fetchData(remoteMessage);
      onPress(remoteMessage);
    });
    return unsubscribe;
  }, [fetchData, onPress]);

  useEffect(() => {
    const unsubscribe = messaging().onMessage((remoteMessage) => {
      console.log('messaging().onMessage', { remoteMessage });
      fetchData(remoteMessage);
      handleMessage(remoteMessage);
    });
    return unsubscribe;
  }, [fetchData, handleMessage]);
```

#### `tester`:

```js
let admin = require('firebase-admin');
let app = admin.initializeApp();

const test = (token) => {
  msg = { notification: { body: 'test' }, token };
  admin.messaging().send(msg).then((response) => {
    console.log('Successfully sent message:', response);
  }).catch((error) => {
    console.log('Error sending message:', error);
  });
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import "RNBootSplash.h"

#import <Firebase.h>
#import <AppCenterReactNative.h>
#import <AppCenterReactNativeCrashes.h>
#import <CodePush/CodePush.h>
#import <FBSDKCoreKit/FBSDKCoreKit.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  [FIRApp configure];
  [AppCenterReactNative register];
  [AppCenterReactNativeCrashes registerWithAutomaticProcessing];
  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"test"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];

  return YES;
}

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(nonnull NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options
{
  if ([[FBSDKApplicationDelegate sharedInstance] application:application openURL:url options:options]) {
    return YES;
  }
  return NO;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [CodePush bundleURL];
#endif
}

@end
```

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by andersonaddo** [comment]
@Ehesp @mikehardy (sorry for the pings but I think this is a bit important)
I might want to investigate this a bit. Any idea where I should start looking? I'd imagine Ehesp might have a good idea.

The only useful information from #3476 is https://github.com/invertase/react-native-firebase/issues/3476#issuecomment-630965264, though I think this is a different problem than what analytics is causing (and I don't think this problem exists anymore).

**Comment by mikehardy** [comment]
A minimum reproducible example is where I'd start, otherwise... 🤔🤔

**Comment by mikehardy** [comment]
Some other thoughts, since the issue has some great info with regard to not one but two possible workarounds:

- if removing analytics is a workaround, and we know analytics is optional for messaging, then looking at any of the areas of messaging initialization where it interacts with analytics is maybe useful?
- if removing app delegate proxy is interesting, then looking for this header https://github.com/firebase/firebase-ios-sdk/blob/b752c4a730120e214554d29d91629f18ee59ccae/FirebaseMessaging/Sources/FIRMessaging.m#L22 import and seeing where exactly the swizzling (which *is* app delegate proxying's implementation I believe) is potentially interesting

Trying to figure out *exactly* what happens internally when it switches between the failure case and the working case might be interesting. What exact state is the token in, internally, when sending notifications fails? Like, what does the firebase-ios-sdk think about the token, does it think it is still valid? What does firebase functions using the firebase-admin-sdk have to say about the token? Just that sending to that token fails? When and when does the token *change* afterwards to go back to the working state? Is there some code that detects the token is not working, or did it just hit a refresh timeout and when it went to refresh it was determined to be faulty and thus cycled?

So to expand on my previous comment:
- a clear path to reproduction, so we can start filling in the mental model of internal state
- an understanding of how messaging initializes, with it's app delegate proxying and analytics interaction understood
- an understanding of what the actual token state is at any given moment

Honestly, this might be a time to make a minimal reproducible examples based off the firebase-ios-sdk quickstarts to see if it can be shown using the native SDK alone, then the firebase team could dedicate resource to it

**Comment by andersonaddo** [comment]
@IngyuTae Just shooting into the dark at the moment, but have you seen this? 
https://github.com/invertase/react-native-firebase/issues/3476#issuecomment-652342956
You think this could apply to you too?
Of course it's not a fix but it gives insight into the problem if it changes anything

**Comment by IngyuTae** [comment]
> @IngyuTae Just shooting into the dark at the moment, but have you seen this?
> [#3476 (comment)](https://github.com/invertase/react-native-firebase/issues/3476#issuecomment-652342956)
> You think this could apply to you too?

@andersonaddo Oh, I forgot to mention it. In my project, I'm using 3 build configs for dev, qa, production. I have confirmed that dev is working well, but not qa. The certificates and provisioning profiles are like below.

- dev : development (certs), development (profile)
- qa : distribute (certs), adhoc (profile)
- production: distribute (certs), appstore (profile)

I've not tested it in production yet. I would make time for it soon.

@mikehardy I will try to make a reproducible repo.

**Comment by andersonaddo** [comment]
Great!
So that means this is a pretty subtle bug.
We'll have to look into the differences in these certificates and how data (ie messages and GA) is treated by apps signed  differently

https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh may be helpful in making your demo

**Comment by mikehardy** [comment]
I think it's going to be very subtle, if qa is a release build (optimized / shrunk native code and JS bundle) it might eventually come down to races during init somewhere so that the google AppDelegate swizzling isn't working, but only when things go just perfectly wrong. That's a hunch anyway

**Comment by flutterfrank** [comment]
I had the problems with a Flutter app. But I am sure it was on Android devices too.
Before problems started, I changed/tested a few things with firebase analytics first time. I deleted the package and now I receive all notifications again.

**Comment by andersonaddo** [comment]
@IngyuTae status on the repro?

**Comment by IngyuTae** [comment]
@andersonaddo I'm sorry for the late reply. I have checked the script make-demo.sh but it seems not to be suitable for this issue as it was intended to test not only messaging module but also other RNFB modules. As I wrote the problem might be a race condition issue between the modules in the initialization process.

I have tried to create a repo only for this issue but I realized that it's more complicated than it looks. Because I believe that the issue only happens in the release build, in order to debug the repo you have to use a real iOS device and Adhoc provisioning profile.

1. Add tester's device UUID to the provisining profile and share it.
2. Share the credentials including certificates (iOS developer, APNS) and keys (Firebase).

Is there any good idea avoids the security stuff?

**Comment by andersonaddo** [comment]
I think you're overthinking this a bit.
Yes, its a good idea to maybe not go for the script if you want to isolate the problem; just making a new RN project and installing just analytics and fcm should would be better.

In terms of adding the tester's uuid to your provisioning profile and sharing the apns certificates and everything, I don't think that's super necessary. Just focus on making the actual RN repo itself that cleanly reproduces the problem - if any person (either here or in the upstream ios Firebase team) wants to clone and test and has to add their own apns certificate and add in their own provisioning profiles to build it, they will.

After all, I think this is a pretty important bug to squash.
