### ISSUE TITLE
LevelStart - level type string or number?

### ISSUE THREAD

**Issue by christopherfraser** [invertase/react-native-firebase#5025]
I'm looking at the Google Firebase Analytics documentation and in all of the event documentation level is defined as a string: 

https://firebase.google.com/docs/reference/cpp/group/event-names

kParameterLevelName (string)

https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event

String | LEVEL_START | Level Start event.

But in the react-native-firebase code and documentation it's described as a number, e.g,:

@react-native-firebase/analytics/lib/structs.js

export const LevelStart = struct({
  level: 'number',
});

**Comment by christopherfraser** [comment]
OK, maybe I'm confused. At other points level in defined as a number:

https://firebase.google.com/docs/reference/cpp/group/parameter-names

**Comment by mikehardy** [comment]
CPP is the wrong reference, we attempt to mirror the JS SDK as a stated goal 
I believe it defers the the gtag.js reference, but I can't find anything on firebase-js-sdk docs about level_start / level_end - can you?

gtag says string https://developers.google.com/gtagjs/reference/ga4-events#level_start while they do have numbers for certain types (like "level_up")

Could be that string is correct, I think the gtag reference is the most important baseline expectation but I'm not 100%
