### ISSUE TITLE
[🐛] Bug Report Title - [iOS] Sometimes cant get dynamic link in iOS because  function  application:openURL:options too late

### ISSUE THREAD

**Issue by hamam99** [invertase/react-native-firebase#5032]
## Issue

Sometimes cant get  dynamic link. I am using React Native Firebase V5. Cant update to V6 because I am still using React Native 0.59.10. 

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "react-native-firebase": "5.5.7",
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
  pod 'Firebase/Core', '6.9.0'
  pod 'Firebase/DynamicLinks', '6.9.0'
  pod 'Firebase/RemoteConfig', '6.9.0'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
```

#### `AppDelegate.m`:

```objc
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
...
  [FIROptions defaultOptions].deepLinkURLScheme = @"jajakpendapat.page.link";
  [FIRApp configure];
...
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
 [FBSDKAppEvents activateApp];
}

- (BOOL)application:(UIApplication *)application
           openURL:(NSURL *)url
 sourceApplication:(NSString *)sourceApplication
        annotation:(id)annotation {
 return [[FBSDKApplicationDelegate sharedInstance] application:application
                                                       openURL:url
                                             sourceApplication:sourceApplication                                                     annotation:annotation];
}


- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
 BOOL handled = [[FBSDKApplicationDelegate sharedInstance] application:application openURL:url sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey] annotation:options[UIApplicationOpenURLOptionsAnnotationKey]];

 if (!handled) {
   handled = [[RNFirebaseLinks instance] application:application openURL:url options:options];
 }
  
  BOOL handled = [[RNFirebaseLinks instance] application:application openURL:url options:options];
  return handled;
}


- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray *))restorationHandler {
  return [[RNFirebaseLinks instance] application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
}



```

</p>
</details>

---

## Environment

React Native : 0.59.10
<details><summary>Click To Expand</summary>
<p>

Sometimes when function application:openURL:options, called too late. It means, app finish rendered and function application:openURL:options not yet called

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [] **iOS** but have not tested behavior on Android
  - [] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `5.5.7`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Unsupported version sorry
