### ISSUE TITLE
[🐛] Error in functionsForApp:firebaseApp customDomain

### ISSUE THREAD

**Issue by mm-webx** [invertase/react-native-firebase#5036]
## Issue

Problem with build application.

`node_modules/@react-native-firebase/functions/ios/RNFBFunctions/RNFBFunctionsModule.m:53:79: No known class method for selector 'functionsForApp:customDomain:'`

after update firebase to 11.1:
```
    "@react-native-firebase/analytics": "^11.1.0",
    "@react-native-firebase/app": "^11.1.0",
    "@react-native-firebase/auth": "^11.1.0",
    "@react-native-firebase/firestore": "^11.1.0",
    "@react-native-firebase/functions": "^11.1.0",
    "@react-native-firebase/messaging": "^11.1.0",
    "@react-native-firebase/storage": "^11.1.0",
```

```
FIRFunctions *functions = (url && url.scheme && url.host) ? [FIRFunctions functionsForApp:firebaseApp customDomain:customUrlOrRegion] : [FIRFunctions functionsForApp:firebaseApp region:customUrlOrRegion];
```
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there!

You skipped very important parts of the template which would have provided the information I needed to help. So I will close this after this comment.

However, I suspect what you've done is upgraded from v10 to v11 without checking the breaking changes you needed to handle

Specifically I wrote an entire article that uses this breaking change as an example: https://invertase.io/blog/react-native-firebase-versioning

The image in the article shows what is going on, and the entire article should be useful to you in the future.

If you think you have already done that but the build still is not working you might need to `npx react-native-clean-project` then rebuild
