### ISSUE TITLE
[🐛] NativeFirebaseError: [auth/internal-error] An internal error has occurred, please try again.

### ISSUE THREAD

**Issue by Balaji-Thella** [invertase/react-native-firebase#5037]
I have got an issue [auth/internal-error] An internal error has occurred, please try again
when I used to sign in with firebase.
Although I have enabled the Sign-in method with Phone in Firebase console

![image](https://user-images.githubusercontent.com/42729660/111304492-cfc7a880-867b-11eb-863d-0ae05c5c4b5d.png)

## Issue

This only happens with on ios.
I have also grabbed a fresh set of your config files (Google-Services.plist / google-services.json) from the firebase console
someone tells me the solution. please!

version firebase I'm using 

"@react-native-firebase/app": "^10.8.1",
"@react-native-firebase/auth": "^10.8.1",

**Comment by mikehardy** [comment]
What did the Xcode console say as you ran it on a real device plugged into your development machine? "internal error" usually means "hey, check the logs during execution, there's interesting stuff in there".

In general though, I need to close this. You deleted huge parts of the template and provided no way to reproduce it, sorry
