### ISSUE TITLE
Android installation issue

### ISSUE THREAD

**Issue by shameemz** [invertase/react-native-firebase#504]
### Environment

1. Application Target Platform: Android
2. Development Operating System:  macOS Sierra
3. Build Tools: 
Android Studio version:2.3.3 
4. React Native version: 0.49.0
5. RNFirebase Version: 3.0.1
6. Firebase Module:  All modules.

/rnapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java:640: error: getCurrentActivity() is not public in ReactContext; cannot be accessed from outside package
      mReactContext.getCurrentActivity(), new PhoneAuthProvider.OnVerificationStateChangedCallbacks() {
                   ^
/rnapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java:737: error: getCurrentActivity() is not public in ReactContext; cannot be accessed from outside package
    final Activity activity = mReactContext.getCurrentActivity();
                                           ^
/rnapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuthPackage.java:15: error: RNFirebaseAuthPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNFirebaseAuthPackage implements ReactPackage {
       ^
/rnapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/config/RNFirebaseRemoteConfigPackage.java:15: error: RNFirebaseRemoteConfigPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNFirebaseRemoteConfigPackage implements ReactPackage {
       ^
/rnapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/crash/RNFirebaseCrashPackage.java:15: error: RNFirebaseCrashPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNFirebaseCrashPackage implements ReactPackage {
       ^
/rnapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabasePackage.java:15: error: RNFirebaseDatabasePackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNFirebaseDatabasePackage implements ReactPackage {
       ^
/rnapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestorePackage.java:15: error: RNFirebaseFirestorePackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNFirebaseFirestorePackage implements ReactPackage {
       ^
/rnapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/messaging/RNFirebaseMessaging.java:35: error: RNFirebaseMessaging is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class RNFirebaseMessaging extends ReactContextBaseJavaModule implements LifecycleEventListener, ActivityEventListener {
       ^
/rnapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/messaging/RNFirebaseMessaging.java:275: error: method does not override or implement a method from a supertype
  @Override
  ^
/rnapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/messaging/RNFirebaseMessaging.java:280: error: method does not override or implement a method from a supertype
  @Override
  ^
/rnapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/messaging/RNFirebaseMessagingPackage.java:15: error: RNFirebaseMessagingPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNFirebaseMessagingPackage implements ReactPackage {
       ^
/rnapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/perf/RNFirebasePerformancePackage.java:15: error: RNFirebasePerformancePackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNFirebasePerformancePackage implements ReactPackage {
       ^
/rnapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/RNFirebasePackage.java:17: error: RNFirebasePackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNFirebasePackage implements ReactPackage {
       ^
/rnapp/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/storage/RNFirebaseStoragePackage.java:17: error: RNFirebaseStoragePackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNFirebaseStoragePackage implements ReactPackage {
       ^
       ^

**Comment by chrisbianca** [comment]
@shameemz See: https://github.com/invertase/react-native-firebase/issues/460#issuecomment-334255092
