### ISSUE TITLE
getInitialNotification() is not working

### ISSUE THREAD

**Issue by Haseeba393** [invertase/react-native-firebase#5049]
## getInitialNotification() is not working

**Explanation**
I'm following documentation of the latest React Native Firebase [(React Native Firebase)](https://rnfirebase.io/). I have implemented Firebase Cloud messaging according to the documentation and everything is working fine except getInitialNotification().
I want when the user will receive a notification on mobile then clicking on it will open the application-specific screen for which notification is. For that, I need a handler to work so that I can save payload information somewhere in-app and then navigate the user to that screen with that Payload. I did everything according to the documentation but my getInitialNotification() is not working. I'm doing simple console.log() but it is not invoking even I changed its position as well.
This is my code
`useEffect(()=>{
    messaging().getInitialNotification((remoteMessage)=>{
      console.log('GET INITIAL NOTIFICATION', remoteMessage);
    });
  },[])`

#### `package.json`:
{
  "name": "pr",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@gorhom/animated-tabbar": "^2.1.0",
    "@react-native-async-storage/async-storage": "^1.13.4",
    "@react-native-community/checkbox": "^0.5.7",
    "@react-native-community/datetimepicker": "^3.0.9",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/progress-bar-android": "^1.0.4",
    "@react-native-community/progress-view": "^1.2.4",
    "@react-native-community/push-notification-ios": "^1.8.0",
    "@react-native-firebase/app": "^11.1.0",
    "@react-native-firebase/messaging": "^11.1.0",
    "@react-navigation/bottom-tabs": "^5.11.2",
    "@react-navigation/drawer": "^5.12.3",
    "@react-navigation/material-top-tabs": "^5.3.13",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "axios": "^0.21.1",
    "jwt-decode": "^3.1.2",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-action-button": "^2.8.5",
    "react-native-axios": "^0.17.1",
    "react-native-camera": "^3.40.0",
    "react-native-chart-kit": "^6.8.1",
    "react-native-countdown-circle-timer": "^2.5.0",
    "react-native-device-info": "^8.0.5",
    "react-native-document-picker": "^4.2.0",
    "react-native-file-viewer": "^2.1.4",
    "react-native-fs": "^2.13.2",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-image-base64": "^0.1.4",
    "react-native-image-picker": "^3.1.4",
    "react-native-material-dropdown": "github:noway/react-native-material-dropdown",
    "react-native-modal": "^11.6.1",
    "react-native-modal-datetime-picker": "^9.1.0",
    "react-native-otp-inputs": "^6.0.0",
    "react-native-pdf": "^6.2.2",
    "react-native-popup-menu": "^0.15.10",
    "react-native-push-notification": "^7.2.2",
    "react-native-reanimated": "^1.13.2",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.16.1",
    "react-native-share": "^5.1.1",
    "react-native-step-indicator": "^1.0.3",
    "react-native-svg": "^12.1.0",
    "react-native-swipeable": "^0.6.0",
    "react-native-tab-view": "^2.15.2",
    "react-native-vector-icons": "^7.1.0",
    "react-native-webview": "^11.2.3",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.12.0",
    "rn-swipe-button": "^1.3.3"
  },
  "devDependencies": {
    "@babel/core": "7.12.10",
    "@babel/runtime": "7.12.5",
    "@react-native-community/eslint-config": "1.1.0",
    "babel-jest": "25.5.1",
    "eslint": "6.8.0",
    "jest": "25.5.4",
    "metro-react-native-babel-preset": "0.59.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

#### `ios/Podfile`:

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'pr' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'prTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'pr-tvOS' do
  # Pods for pr-tvOS

  target 'pr-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

**Comment by mikehardy** [comment]
Please post a minimum reproducible example, this is likely either some other package influencing data passing. Also try setting up handling in index.js (before appregistry).

Please post a new issue with those things and without deleting parts from the issue template, we close issues that skip important template parts
