### ISSUE TITLE
[🐛] How to create splash add (== "App Open ad" in admob wesite)

### ISSUE THREAD

**Issue by easonccc1** [invertase/react-native-firebase#5056]
<img width="266" alt="Screen Shot 2021-03-18 at 11 50 43 AM" src="https://user-images.githubusercontent.com/29586734/111862534-df533400-8990-11eb-93a2-283813b2e9e8.png">

In Admob website, you can create "App Open" ad unit, which is displayed in splash screen. However, I cannot find any documentation explaining how to create such splash ad using react-native-firebase.

Any thought?

**Comment by mikehardy** [comment]
Hi there! Consulting the Firebase documentation, are there any APIs upstream that are associated with this? react-native-firebase simply wraps the existing native APIs in firebase-ios-sdk and firebase-android-sdk - if they do not provide APIs for something, then we have nothing to offer here. I don't think there is anything related as an API upstream but if you examine the docs and find something please post back and we can reopen this

**Comment by easonccc1** [comment]
> Hi there! Consulting the Firebase documentation, are there any APIs upstream that are associated with this? react-native-firebase simply wraps the existing native APIs in firebase-ios-sdk and firebase-android-sdk - if they do not provide APIs for something, then we have nothing to offer here. I don't think there is anything related as an API upstream but if you examine the docs and find something please post back and we can reopen this

@mikehardy Thanks for your reply. 

Here is firebase-android-sdk doc for app open ad: https://developers.google.com/admob/android/app-open-ads;

firebase-ios-sdk doc for app open ad: https://developers.google.com/admob/ios/app-open-ads

One thing to mention is that the links are labelled as "open beta". Could that be a reason why rn-firebase doesn't include such function?

**Comment by mikehardy** [comment]
Those are admob links, not firebase links if I'm not mistaken. Those are different sdks
