### ISSUE TITLE
[📚] HttpsCallable Typescript fix 

### ISSUE THREAD

**Issue by luisgurmendez** [invertase/react-native-firebase#5074]
## Documentation Feedback

Right now the types for an HttpsCallable are:
```
export interface HttpsCallable {
    (data?: any): Promise<HttpsCallableResult>;
  }
```
I think that it would make much more sense if we had 2 generics like:
 ```
export interface HttpsCallable<D = any, R = any> {
    (data?: D): Promise<HttpsCallableResult<R>>;
}
```

This would imply having to also change the signautre of httpsCallable function like so:
```
    httpsCallable<D,R>(name: string, options?: HttpsCallableOptions): HttpsCallable<D,R>;
```

**Comment by mikehardy** [comment]
Hi there!

The types will match firebase-js-sdk or they should anyway, which are:

https://github.com/firebase/firebase-js-sdk/blob/7b585e8e7bc6bdc36200681865ec11e91ca7c4a1/packages/functions-types/index.d.ts#L29-L31

```typescript
export interface HttpsCallable {
  (data?: {} | null): Promise<HttpsCallableResult>;
}
```

...so I'd take a PR that made them conform perfectly, but I suggest you petition for the generics upstream with firebase-js-sdk first? They can ingest a change like that and then we can mirror here - but type-wise they are our "upstream" and we try to match them as exactly as possible

Does that make sense?

**Comment by luisgurmendez** [comment]
Totally makes sense! thanks for pointing me to the right direction! Cheers

**Comment by clytras** [comment]
I looked at this, and I can see that actually there is support of the official Firebase SDK for `httpsCallable` generics.

Here is a discussion about it https://github.com/firebase/firebase-js-sdk/discussions/4415#discussioncomment-5795440.
The documentation: https://firebase.google.com/docs/reference/js/functions.md#httpscallable
And the `httpsCallable` API typings declaration https://github.com/firebase/firebase-js-sdk/blob/master/packages/functions/src/api.ts.

I think this should be implemented to the `react-native-firebase` functions package as well.
