### ISSUE TITLE
[🐛] Test suite failed to run      Invariant Violation: Native module cannot be null.

### ISSUE THREAD

**Issue by TiavinaRakotobe** [invertase/react-native-firebase#5076]
react-native-firebase/app: "~8.2.0",
react-native-firebase/auth: "8.2.0",
react-native-firebase/dynamic-links: "7.3.2",
react-native-firebase/messaging": "~7.5.0",
react-native: "0.62.2",
react-native-testing-library: "^2.1.0"
jest": "^24.9.0"

JEST CONFIG
"jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "moduleDirectories": [
      "node_modules",
      "components"
    ],
    "transformIgnorePatterns": [
      "/node_modules/(?!native-base)/",
      "node_modules/(?!(jest-)?react-native|@react-native-firebase/app)",
      "node_modules/(?!(@react-native-community|react-native))",
      "node_modules/(?!(@react-native-community/async-storage/lib))"
    ],
    "setupFiles": [
      "./jestSetup.ts"
    ],
    "setupFilesAfterEnv": [
      "@testing-library/jest-native/extend-expect"
    ]
  }

JEST SETUP
import * as ReactNative from 'react-native';
jest.doMock('react-native', () => {
  return Object.setPrototypeOf(
    {
      Platform: {
        OS: 'android',
        select: () => {},
      },
      NativeModules: {
        ...ReactNative.NativeModules,
        RNFBAdMobModule: {},
        RNFBAdMobInterstitialModule: {},
        RNFBAdMobRewardedModule: {},
        RNFBAdsConsentModule: {},
        RNFBAppModule: {
          NATIVE_FIREBASE_APPS: [
            {
              appConfig: {
                name: '[DEFAULT]',
              },
              options: {},
            },

            {
              appConfig: {
                name: 'secondaryFromNative',
              },
              options: {},
            },
          ],
          addListener: jest.fn(),
          eventsAddListener: jest.fn(),
          eventsNotifyReady: jest.fn(),
        },
        RNFBAuthModule: {
          APP_LANGUAGE: {
            '[DEFAULT]': 'en-US',
          },
          APP_USER: {
            '[DEFAULT]': 'jestUser',
          },
          addAuthStateListener: jest.fn(),
          addIdTokenListener: jest.fn(),
          useEmulator: jest.fn(),
        },
        RNFBCrashlyticsModule: {},
        RNFBPerfModule: {},
      },
    },
    ReactNative,
  );
});

jest.mock('@react-navigation/native', () => {
  const actualNav = jest.requireActual('@react-navigation/native');
  return {
    ...actualNav,
    useNavigation: () => ({
      navigate: jest.fn(),
      dispatch: jest.fn(),
    }),
  };
});

COMPLETE ERROR LOG 
Test suite failed to run

    Invariant Violation: Native module cannot be null.

      at invariant (node_modules/invariant/invariant.js:40:15)
      at new NativeEventEmitter (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:37:27)
      at RNFBNativeEventEmitter._createSuperInternal (node_modules/@react-native-firebase/app/lib/internal/RNFBNativeEventEmitter.js:18:2127)
      at new RNFBNativeEventEmitter (node_modules/@react-native-firebase/app/lib/internal/RNFBNativeEventEmitter.js:24:20)
      at Object.<anonymous> (node_modules/@react-native-firebase/app/lib/internal/RNFBNativeEventEmitter.js:48:1)
      at Object.<anonymous> (node_modules/@react-native-firebase/app/lib/internal/registry/nativeModule.js:21:54)

**Comment by mikehardy** [comment]
Please update to current stable and see if you can reproduce

**Comment by mikehardy** [comment]
Also, you can see our jest setup, it does run for the parts of the package we use but it is not complete. You may need to extend it and add things. It's a good start in other words but not more than that

**Comment by Prernabudh** [comment]
I am still facing this issue. Any solution @mikehardy @TiavinaRakotobe. react-native-firebase/app version -> ^11.5.0

**Comment by mikehardy** [comment]
@Prernabudh This isn't an issue we will prioritize - we need the community to help. This is something you will need to extend for your use case. If you have extensions you think everyone would benefit from please post a PR to the jest mocks we currently supply, that's how they will become more complete

> Also, you can see our jest setup, it does run for the parts of the package we use but it is not complete. You may need to extend it and add things. It's a good start in other words but not more than that
