### ISSUE TITLE
🔥 Cloud Firestore Transactions .then is not a function

### ISSUE THREAD

**Issue by TPXP** [invertase/react-native-firebase#5087]
## Issue
Hello there, thanks again for this great project <3

I'm using a cloud firestore transaction in my app to handle a write requiring document data to match the one of another document in the database. For this purpose, we're using a transaction.

According to the [example usage shown in RNFirebase's documentation](https://rnfirebase.io/firestore/usage#transactions), this should work:
```
    await transaction.update(postReference, {
      likes: postSnapshot.data().likes + 1,
    });
```

Which matches with the [official documentation for the web SDK](https://firebase.google.com/docs/firestore/manage-data/transactions), all good so far!

Except, when trying to run this snippet, the JS engine gets confused and tries to do something with `.then()`, which leads to an error.

```
 [TypeError: transaction.update(postReference, {Data}).then is not a function.
``` 

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
(relevant part only)
```json
{
  "dependencies": {
    "@react-native-firebase/analytics": "^10.2.0",
    "@react-native-firebase/app": "^10.2.0",
    "@react-native-firebase/auth": "^10.2.0",
    "@react-native-firebase/crashlytics": "^10.2.0",
    "@react-native-firebase/firestore": "^10.2.0",
    "@react-native-firebase/functions": "^10.2.0",
    "@react-native-firebase/messaging": "^10.2.0",
    "@react-native-firebase/remote-config": "^10.2.0",
    "@react-native-firebase/storage": "^10.2.0"
  }
}
```

Outdated, I know. Still, I looked at the changelog and I believe the relevant code has not changed.

#### `firebase.json` for react-native-firebase v6:

```json
{ "react-native": {
  "crashlytics_debug_enabled": true
} }
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '10.0'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods'
require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'MyApp' do
  config = use_native_modules!
  use_unimodules!

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper - not for CI builds as it takes some build time
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  unless ENV['CI']
    use_flipper!({'Flipper' => '0.69.0'})

    post_install do |installer|
      flipper_post_install(installer)
    end
  end
end

target 'ImageNotification' do
  pod 'Firebase/Messaging'
end
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.70 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.12.0 - /var/folders/pg/1z2xwlhd0kz2wyv6g_62frdwsw7wbq/T/yarn--1616783497357-0.30801735957811016/node
    Yarn: 1.22.10 - /var/folders/pg/1z2xwlhd0kz2wyv6g_62frdwsw7wbq/T/yarn--1616783497357-0.30801735957811016/yarn
    npm: 7.6.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/lib/ruby/gems/2.5.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ^0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
:thinking:  how is that documentation (which...seems fine?) different from our e2e tests which [seem to exercise a very similar case, and work](https://github.com/invertase/react-native-firebase/runs/2204492938?check_suite_focus=true#step:21:2382)?

https://github.com/invertase/react-native-firebase/blob/a61d0cdebb6c2c7c9c3966f0a7a0af6a0ef3ae05/packages/firestore/e2e/Transaction.e2e.js#L170-L208

**Comment by TPXP** [comment]
Hum, interesting indeed! I'm actually facing the issue with `set`, could that be specific to that function? :thinking:

**Comment by mikehardy** [comment]
I think set is exercised in transaction just below it in that same e2e file?

**Comment by TPXP** [comment]
Indeed, both are tested. ^^

The issue occured when putting `await` or `return` along `transaction.set` or `transaction.update`. In this case, the JS engine tried to interpret a `Transaction` as a promise and the `.then( is not a function` error is emitted.

I'm confused, I tried to test it and everything looks okay, re-building my app also fixed it. I guess the issue was on my side, sorry for the inconvenience 😓 

For the record, maybe `await` should be put in tests, or update the documentation to remove the `await` ?

**Comment by mikehardy** [comment]
🤔 I'm definitely happy you seem to be moving forward, but I'm lost on what exactly the suggestion is for documentation or tests - if you made a speculative PR (can probably just use the GitHub Web UI's edit button to do it quickly) I could see more easily what exactly you would change and to what, in order to understand better

**Comment by TPXP** [comment]
Hello, sorry for the delay.
I believe the `await` in the `transaction.set` example is confusing since, usually, `await` is followed by a promise object, which is not the case here since `transaction.set` returns an Transaction object.

I suggest to remove the `await` keyword in front of this call in the documentation, as shown here https://github.com/invertase/react-native-firebase/commit/886e75dd79b8a73ba8a2611351d1cdde0244a243

**Comment by mikehardy** [comment]
@TPXP you are :100: on that, I agree, I like that commit you reference but it's in your repo, care to post a PR for it? I can merge it and your effort will hopefully remove confusion for future people

**Comment by TPXP** [comment]
Good idea, opened #5273 to fix this :)
