### ISSUE TITLE
 RNFBMessagingSerializer.m:35:58: Property 'appData' not found on object of type '__strong id'

### ISSUE THREAD

**Issue by ezekel** [invertase/react-native-firebase#5090]
## Issue
when I build my IOS project it shows these errors

Property 'appData' not found on object of type '__strong id'

![Screen Shot 2021-03-28 at 11 26 56 PM](https://user-images.githubusercontent.com/6830057/112757647-3dc98380-901d-11eb-97a4-dcdad026f4ff.png)

![Screen Shot 2021-03-28 at 11 21 13 PM](https://user-images.githubusercontent.com/6830057/112757451-63a25880-901c-11eb-8e77-82a925b6d0e3.png)

---

#### `package.json`:
 "react-native": "0.64.0",
"@react-native-firebase/app": "^11.2.0",
    "@react-native-firebase/in-app-messaging": "^11.2.0",
    "@react-native-firebase/messaging": "^7.8.6",

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

platform :ios, '10.0'
$FirebaseSDKVersion = '7.7.0'



target 'projumbrella' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  target 'projumbrellaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
    # flipper_post_install(installer)
  # end
end

target 'projumbrella-tvOS' do
  # Pods for projumbrella-tvOS

  target 'projumbrella-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end```

**Comment by mikehardy** [comment]
Hi there!

**DO NOT DO THIS**

```
"@react-native-firebase/app": "^11.2.0",
"@react-native-firebase/in-app-messaging": "^11.2.0",
"@react-native-firebase/messaging": "^7.8.6",
```

The version numbers must go together

https://invertase.io/blog/react-native-firebase-versioning
