### ISSUE TITLE
[🐛] libc.so unknown crashes 

### ISSUE THREAD

**Issue by Maharshi01** [invertase/react-native-firebase#5095]
Hi @mikehardy 
I have integrated firebase crashlytics version in the app ("@react-native-firebase/crashlytics": "^8.4.9"), after the app was launched i started noticing minimum 10-20 of these crashes.bt suddenly on 23 March out of the blue these crashes spiked to 10k and affected the end users. I was unable to find any description regarding the crash because firebase was unable to extract crash information. Can you please help to tell whats the issue is regarding and how to prevent this from happening?
I have attached the crashlytics screenshot for reference. Thanks @mikehardy 
![Screenshot 2021-03-29 at 10 33 24 AM](https://user-images.githubusercontent.com/48430425/112789397-9da24780-907a-11eb-8bc5-c9acf77f9cc9.png)
![Screenshot 2021-03-29 at 10 33 51 AM](https://user-images.githubusercontent.com/48430425/112789400-a09d3800-907a-11eb-91f4-572680436a6e.png)

**Comment by mikehardy** [comment]
That's an old version but more more important for that date Google Android webview crash Engadget, it's in the news

Crashlytics can't really handle native crashes like that, so deeply at the native level. Play console would have them though

**Comment by mikehardy** [comment]
I'm going to close this one as there is not much we can do here, the app in this specific event was crashing so early in startup that crashlytics couldn't even handle it - this was so rare and serious it made the news (also blew up all my apps, and made Monday last week very ...exciting)

**Comment by Maharshi01** [comment]
Thanks @mikehardy. bt if i update the package will they be resolved?

**Comment by mikehardy** [comment]
No, they won't resolve until your application's users update their Android System WebView. Did you google "android webview crash engadget"? It appears you did not

**Comment by Maharshi01** [comment]
Did @mikehardy.....got the news https://www.bbc.com/news/technology-56496783. Understood the issue now.

**Comment by mikehardy** [comment]
Exactly :-), now you understand. It was a massive google blunder, it affected everyone, and there was nothing we could do about it. Monday was quite exciting ;-)

**Comment by Maharshi01** [comment]
Thanks @mikehardy
