### ISSUE TITLE
Upgraded from 2.2 to 3.0 database_sync_event

### ISSUE THREAD

**Issue by JSafaiyeh** [invertase/react-native-firebase#510]
I am getting the error upon application initialization.

`database_sync_event is not a supported event type for RNFirebaseDatabase. Supported events are: database_event, database_error, database_transaction_event`

How can I resolve this?

**Comment by chrisbianca** [comment]
@JSafaiyeh Please fill out the issue template, it's there to help us help you.  Otherwise we have no way of knowing which platform you're seeing errors on, etc.

**Comment by chrisbianca** [comment]
Closing this. Please re-open the issue with the issue template details if you're still having problems.
