### ISSUE TITLE
[🐛] The ad request was invalid; for instance, the ad unit ID was incorrect.

### ISSUE THREAD

**Issue by easonccc1** [invertase/react-native-firebase#5100]
My code was working a couple of weeks ago. But when I tested today, I cannot request admob ads (both testIds and live adUnit).

The error is:

> 2021-03-30 11:08:54.716 6673-6710/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class io.invertase.firebase.admob.ReactNativeFirebaseAdMobBannerAdViewManager

> 2021-03-30 11:09:48.833 6673-6709/? D/ReactNativeJS: 'admob ad failed to load:', { [Error: [admob/error-code-invalid-request] The ad request was invalid; for instance, the ad unit ID was incorrect.] line: 66, column: 340, sourceURL: 'index.android.bundle' }

I followed the setup page in rnfirebase/admob:
1. added firebase.json
2. added my device in Test Devices page

```
<BannerAd
    unitId={TestIds.BANNER}
    size={BannerAdSize.MEDIUM_RECTANGLE}
    requestOptions={{
       requestNonPersonalizedAdsOnly: true,
    }}
    onAdLoaded={() => {console.debug('admob ad loaded')}}
    onAdFailedToLoad={(result) => {console.debug('admob ad failed to load:', result)}}
 />
```

package version:
 "@react-native-firebase/admob": "^11.2.0",
"@react-native-firebase/analytics": "^11.2.0",
"@react-native-firebase/app": "^11.2.0",
"react": "^17.0.1",
"react-native": "^0.64.0",

**Comment by easonccc1** [comment]
Any thought?

**Comment by mikehardy** [comment]
Sorry - I saw this but I've never personally worked with admob other than the E2E tests here, and they're working with the test ids. So I'm not sure what's going on.
There was another issue just a couple days ago where the rewarded ad wouldn't load with the test ids but the production ids worked.

I think most of this boils down to googles servers profiling the activity of specific ids and behaving in unexplained ways on the back-end but that's just a hunch.

We haven't changed anything that I know of in the area other than the native SDKs. You mention your code was working a couple weeks ago, 11.2.0 isn't that old, you might try rolling back to whatever version here was working then and see if that makes a difference?
