### ISSUE TITLE
timestampsInSnapshotsEnabled not found

### ISSUE THREAD

**Issue by kea0811** [invertase/react-native-firebase#5101]
Hello, I follow the getting started tutorial, but received the following error while compiling.

Error:
Property 'timestampsInSnapshotsEnabled' not found on object of type 'FIRFirestoreSettings *'

I am running on 
"@react-native-firebase/analytics": "^11.2.0",
"@react-native-firebase/app": "^11.2.0",
"@react-native-firebase/auth": "^11.2.0",
"@react-native-firebase/firestore": "^11.1.0",

Did anyone met the same issue?

**Comment by mikehardy** [comment]
You skipped the template, we can't help

**Comment by mikehardy** [comment]
as a guess - https://firebase.google.com/support/release-notes/ios#cloud-firestore_7 - `npx react-native-clean-project` or something else terribly wrong with the project where the native firebase-ios-sdk version is not the expected one somehow for some chunk of code.

**Comment by mikehardy** [comment]
https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh - clone that and run it maybe as a first attempt at using firebase in react-native to prove it works to yourself and see what a functioning project looks like

**Comment by mikehardy** [comment]
interesting - it's the right place to log problems and ask questions but your issue vs your last comment do not go together.

You logged it saying

```
 "@react-native-firebase/app": "^11.2.0",
```

was in your package.json

but now you say it works with this:

> My project had no issue after adding @react-native-firebase/app. Error happen after I import @react-native-firebase/firestore

So, which was it? Was it in your package.json before or does it work now that you've added it?

But most importantly, if you log an issue in an open source repository and they have an issue template which shows up in the text box to create an issue and which you had to specifically delete, in contradiction to this statement:

> I  didn't know there is a template to follow

...I can say as a maintainer that you are not respecting maintainer's time. The template has vital details usually. But then if you do fill parts out - like the package.json snippet you filled in - you need to make absolutely sure they are correct, to contradict your initial information in later comments is odd, and also not an inefficient use of time.

All that said! I'm very happy your project is moving forward, good luck with it :-)

**Comment by kea0811** [comment]
@mikehardy I certainly will look up for template for any open source next time. Appreciate your time to try to help me resolve this issue. 

Initially I included the firestore library in my package.json that’s why it failed during build. On my second statement, I point out the finding that the error only happen AFTER I added the firestore library which is different from the first one. 

I really appreciate your time helping me here. I’m trying to waste your time. I’m trying to see if others met the same problem I had, which we could help each other to save time. I look up every where else and do not see anyone else is having the same issue. That’s why I’m filing an issue here. 

The script you provided is helpful and certainly run well. But when I imported the firestore library that gave me the same problem too. 

I’m not sure if this is a bug or my mistake. All I am trying to do here is to help people who had the same issue/problem as me.

Cheers man!

**Comment by mikehardy** [comment]
I don't understand, my script imports the firestore library: https://github.com/mikehardy/rnfbdemo/blob/8f7a33921e77c882398fb1c607c0a6eee4501e70/make-demo.sh#L95

It runs?

**Comment by kea0811** [comment]
<img width="590" alt="Screenshot 2021-03-31 at 1 01 45 AM" src="https://user-images.githubusercontent.com/8357167/113027495-bc105c00-91bc-11eb-97c5-fbab0d2b2ac4.png">

Here is what i get after running your script. It doesn't install by itself. So I went to add it manually and it still gave me the same timestamp error.

**Comment by mikehardy** [comment]
(note that if you used the make-demo script the regular compile for iOS that everyone uses with dynamic frameworks builds correctly but there was a workaround necessary for the `use_frameworks` way that no one should use, nevertheless I just fixed that even - builds clean https://github.com/mikehardy/rnfbdemo/commit/f84ad523b37f19db46ac0710396c4769ea024808)
