### ISSUE TITLE
[🐛] Remote config - Cannot read property '[DEFAULT]' of undefined

### ISSUE THREAD

**Issue by Praveena0989** [invertase/react-native-firebase#5108]
## Issue
<p>
Using remote config is throwing Cannot read property '[DEFAULT]' of undefined error only on ios running fine on Android.
I tried clearing pods and reinstalling them. Also, tried deleting derived data.

```
import remoteConfig from '@react-native-firebase/remote-config';
const App: React.FC = () => {
 useEffect(() => {
    remoteConfig()
      .setConfigSettings({
        minimumFetchIntervalMillis: 300000,
      })
      .then(() => remoteConfig().fetchAndActivate())
      .then(fetchedRemotely => {
        console.log(`remote config fetched and activated ${fetchedRemotely}`);
      })
      .catch(err => {
        console.log(err);
      });
  }, []);
}
```

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/app": "^11.2.0",
    "@react-native-firebase/crashlytics": "^11.2.0",
    "@react-native-firebase/messaging": "^11.2.0",
    "@react-native-firebase/remote-config": "^11.2.0",
    "react": "17.0.1",
    "react-native": "0.64.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'nova' do
  # Pods for nova
  permissions_path = '../node_modules/react-native-permissions/ios'
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"], :hermes_enabled => true)
  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  
  target 'novaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'nova-tvOS' do
  # Pods for nova-tvOS

  target 'nova-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
use_flipper!({ 'Flipper' => '0.74.0' })
post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
end
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 666.07 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.1 - ~/.nvm/versions/node/v12.8.1/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v12.8.1/bin/yarn
    npm: 6.14.5 - ~/clearone/packages/nova/node_modules/.bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-27 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `11.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y` & `3.9.5`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Praveena0989** [comment]
![Uploading Simulator Screen Shot - iPhone 12 - 2021-03-31 at 23.22.38.png…]()

**Comment by mikehardy** [comment]
Please just post the text of the error

**Comment by mikehardy** [comment]
very odd that your Podfile says iOS should be 10+ but then you clamp all the underlying libraries to 12+ ? Which should it be?

**Comment by mikehardy** [comment]
Final thought - `npx react-native-clean-project` and or try https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh - I was just building a demo as a build test yesterday using that, if you can make an App.js that I can drop in there and reproduce the issue we see what's wrong - but this will probably be project-specific, I use remote-config in my project on iOS and it works

**Comment by Praveena0989** [comment]
@mikehardy  Thank you so much. It worked after changing the platform version to 12 in podfile then clearing the pod cache.
