### ISSUE TITLE
[🐛] sendPasswordResetEmail via Code

### ISSUE THREAD

**Issue by ardenercelik** [invertase/react-native-firebase#5119]
## Issue

Cannot reset password with code. 
I would like to send a code via email from the app, but with the current state of the sendPasswordResetEmail function I can not achive this feature. The confirmPasswordReset function is provided, but I was not able get code from the sendPasswordResetEmail function.

Also while using sendPasswordResetEmail if I use it like below I get null object reference on java.lang.Object.getClass().
```
try {
    await auth().sendPasswordResetEmail(email, {
      handleCodeInApp: true,
    });
  } catch (e) {
    console.log(e);
  }
};
```

I found generatePasswordResetLink method inside firebase sdk but not in the rnf libraries.

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 8.01 GB / 15.94 GB
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: 16.9.31105.61 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_275
    Python: 3.8.5
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  -     "@react-native-firebase/app": "^10.4.0",
         "@react-native-firebase/auth": "^10.4.1",

- **Are you using `TypeScript`?**
  - N

</p>
</details>

**Comment by mikehardy** [comment]
You should use current versions, please make sure you can reproduce this on current versions, reporting issues against old versions is inefficient and I personally don't spend time on them

Is your case not covered here? These are the tests that run against every commit in this repository, and they're passing

https://github.com/invertase/react-native-firebase/blob/c94546d8127606dca5bfd09ef92ec32eec333f19/packages/auth/e2e/auth.e2e.js#L924-L1002

**Comment by ardenercelik** [comment]
Thank you for your response.
We upgraded our code base to the latest and we still could not achive the result we wanted.
When tried to reset password with this function it send a firebase link to the user and the process is handled reset within browser.
Wanted behavior is when we call sendPasswordResetEmail it sends user a password reset code. Then the process could be handled within the app with our password policies.

**Comment by mikehardy** [comment]
I think - I am not sure - that this has to do with how you set up the action code settings, to handle it in app? https://firebase.google.com/docs/auth/ios/passing-state-in-email-actions - and then you would configure the password reset email template to be a deep link in to the app:

https://firebase.google.com/docs/auth/custom-email-handler

Using a similar style (but not a deep link, or as a fall back in the deep link construction just in case deep link fails), you may customize the actual web handlers using firebase services (cloud functions to handle the resets, hosting to host the small javascript app - or even the whole app in cloud functions
