### ISSUE TITLE
firestore query startAfter throws exception

### ISSUE THREAD

**Issue by atlanteh** [invertase/react-native-firebase#512]
This is actually sort of two issues:

1) When running the following code it fails:
```
  fetchNextBatch = () => {
    let query = firebase.firestore().collection('jobs').orderBy('startTime', 'desc').limit(7);
    if (this.state.last) {
      query = query.startAfter(this.state.last);
    }
    query.get()
    .then(querySnap => {
      let last = querySnap.docs[querySnap.docs.length - 1];
      const newData = querySnap.docs.map(docSnap => ({...docSnap.data(), id: docSnap.id}))
      this.setState((state) => {
        const nonExistingData = newData.filter(newItem => !state.data.find(curItem => curItem.id === newItem.id));
        return {data: state.data.concat(nonExistingData), last};
      });
    });
  }
```
![screenshot_20171015-182330](https://user-images.githubusercontent.com/3952700/31586294-a16741f2-b1d7-11e7-9e41-f88947b42ff6.png)

2) When I try to only take ```query = query.startAfter(last.data().startTime)``` I keep getting the same data.

### Environment

1. Application Target Platform: Tested only on Android
2. Development Operating System: Windows 10
4. React Native version: 0.47.2
5. RNFirebase Version: 3.0.3
6. Firebase Module: firestore

**Comment by chrisbianca** [comment]
@atlanteh thanks for logging this.  I'll respond to your two point separately:

1) We definitely don't currently support using the 'DocumentSnapshot' in `startAt`, `startAfter`, etc, at the moment - we need to figure out a way of doing this across the native bridge
2) We should support this format, so this looks does like a bug.  We'll investigate.

**Comment by chris-divvito** [comment]
Just a note that we are seeing these same issues. Also just to clarify on point 1 - the docs currently suggest that the snapshot format IS supported, do these need to be updated? (https://rnfirebase.io/docs/v3.0.*/firestore/reference/CollectionReference#endAt - parameters: snapshotOrVarArgs)

**Comment by chrisbianca** [comment]
@atlanteh I have just pushed up a set of fixes for the issues that you were seeing based on the work that @peterdivvito did in his PR.

@chris-divvito This also includes support for DocumentSnapshot

We'll get a release out later today or tomorrow, but in the meantime if you'd like to try the latest code please use the following:

`npm install --save https://github.com/invertase/react-native-firebase#v3.0.x`

Please shout if there's anything amiss with the fixes.

**Comment by vanishree1** [comment]
We are using "react-native-firebase": "^3.2.0", still startAfter includes the boundary value, however using firestore queries directly returns correct data, has this been fixed as of yet, or is there a way to make firestore queries work in android(as this is why we used rn-firebase)
