### ISSUE TITLE
Link to the `template` project is broken in a blog

### ISSUE THREAD

**Issue by ajaykumar97** [invertase/react-native-firebase#5120]
Hey guys!
I was studying about the usage of the `Cloud Firestore` in the React-Native on the [blog](https://invertase.io/blog/getting-started-with-cloud-firestore-on-react-native), navigated from the `Building a "TODO" app` [section](https://github.com/invertase/react-native-firebase/blob/c2615970ae5fd3ffb4c29e3f735f82f140fe7882/docs/sidebar.yaml#L49) from the [website](https://rnfirebase.io/). This blog post suggests to use a [template](https://invertase.io/oss/react-native-firebase/quick-start/new-project) project for getting started. But this link is broken and is opening a 404 page. Can you please suggest me where to look for the template project for getting started with the Cloud Firestore?

**Comment by mikehardy** [comment]
Hi there! There is no template project any more. It used to be very difficult to integrate react-native-firebase so a template was needed, but now it works pretty much out of the box, and for that blog post at least (just using firestore) is should definitely work out of the box based on `npx react-native init <project name>`

@Ehesp - looks like the post needs another update to reflect that the template no longer exists? :-)

**Comment by ajaykumar97** [comment]
Got it 👍🏼 . Thanks for the quick response 🙂.
