### ISSUE TITLE
[🐛] Bug Report Title - Custom Action Extension Stopped working after adding a admob to My RN project.

### ISSUE THREAD

**Issue by kp72-dev** [invertase/react-native-firebase#5124]
I have used firebase ad mob to show interstitial ads in app
But after adding Ad mob unfortunately my custom action extension stopped responding.
 I tried to figure out how and why this stopped working i didn't get anything that is indicate about this issue.
i am using RN 0.63 latest version of ad mob.
Help me to trouble shoot this issue.

**Comment by mikehardy** [comment]
We do not help troubleshoot any issues when the issue template was ignored, sorry.
