### ISSUE TITLE
[🐛] Facebook auth with "Gaming" App Type

### ISSUE THREAD

**Issue by kg-currenxie** [invertase/react-native-firebase#5125]
## Issue

Creating an app as an "Gaming App" (https://developers.facebook.com/docs/development/create-an-app/app-dashboard/app-types/) breaks FB Auth. 
The Facebook response will replace `public_profile` with `gaming_profile`

(https://developers.facebook.com/docs/games/gaming-services/login/)
> User's player name and avatar. This replaces public_profile to be the default permission for gaming graph domain.
--

When using a gaming app, I'd get the following error

```
[Mon Apr 05 2021 16:32:44.359]  WARN     Possible Unhandled Promise Rejection (id: 0):
Error: [auth/invalid-credential] The supplied auth credential is malformed or has expired.
NativeFirebaseError: [auth/invalid-credential] The supplied auth credential is malformed or has expired.
```

After deleting the gaming app, and creating a normal app over at Facebook's developer pages, it works

Not sure if there's anything you can do over at your side to allow a gaming app, or if its a limitation. (If so, maybe it should be added to the docs)

**Comment by mikehardy** [comment]
This would be a limitation with native Firebase SDKs and the firebase service itself, I would pursue this with one of https://github.com/firebase/firebase-android-sdk/ or https://github.com/firebase/firebase-ios-sdk/, as this is not something we handle at the react-native level

**Comment by kg-currenxie** [comment]
Ok thx :)
