### ISSUE TITLE
[🔥🐛] [ADMOB] - Loading interstitial crashes the app (with possible fix)

### ISSUE THREAD

**Issue by juanamd** [invertase/react-native-firebase#5127]
## Issue

When calling `InterstitialAd.load()` on Android the app automatically crashes.
After checking adb logcat, it shows the following error:
`
AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/InterstitialAd;
04-06 15:06:00.950 13536 13536 E AndroidRuntime:        at io.invertase.firebase.admob.ReactNativeFirebaseAdMobInterstitialModule.lambda$interstitialLoad$0$ReactNativeFirebaseAdMobInterstitialModule(ReactNativeFirebaseAdMobInterstitialModule.java:76)
`

Which, after further investigaton, led me to believe it is caused by a recent update to [play-services-ads](https://developers.google.com/admob/android/rel-notes#20.0.0) (version 20).
(Notice the line that says: `Removed legacy Interstitial API`)

**FIX/WORKAROUND:**
Got it fixed by including the following line in the dependencies section of the app/build.gradle file:
`implementation("com.google.android.gms:play-services-ads:19.8.0") { force = true; }`

So from what I can tell, Firebase Admob relies on play-services-ads but it's not pinned to a specific version. So when version 20 was released, Admob automatically used it and broke some things.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
    Memory: 3.93 GB / 15.87 GB
  Binaries:
    Node: 15.4.0 - ~\AppData\Local\Temp\yarn--1617738690948-0.059075578473437584\node.CMD
    Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1617738690948-0.059075578473437584\yarn.CMD
    npm: 7.0.15 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.2, 29.0.3
      System Images: android-16 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.0.28803.352 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_181
    Python: 2.7.18
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `11.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Admob`
- **Are you using `TypeScript`?**
  - `Y` & `4.2.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Oh that's not good, sorry that caused a crash issue for you

Long-term it's important to note that we prune deprecated APIs so this of course implies that the correct solution is to get rid of InterstitialAd usage ASAP, however of course we should not crash.

For the crash issue the dependency chain looks like

1. Firebase BoM 26.8.0 right now
 https://github.com/invertase/react-native-firebase/blob/3c90c5931e9777eda1614ae1f443c6de79540f01/packages/app/package.json#L72

2. Dependency on "com.google.firebase:firebase-ads" which should then pin the version based on BoM 26.8.0 above
https://github.com/invertase/react-native-firebase/blob/3c90c5931e9777eda1614ae1f443c6de79540f01/packages/admob/android/build.gradle#L110

3. So the BoM contents are here https://firebase.google.com/support/release-notes/android#2021-03-25

and confusingly it indicates that the 26.8.0 BoM is not supposed to have crossed that breaking change barrier to the 20.0.0 ads artifacts (ugly paste below, apologies):

```
Artifact name | Version mappedto previous BoM v26.7.0 | Version mappedto this BoM v26.8.0
-- | -- | --
com.google.firebase:firebase-ads-lite | 19.7.0 | 19.8.0
com.google.firebase:firebase-ads | 19.7.0 | 19.8.0
```

So v20 of firebase-ads should not have leaked in.

Verified by downloading the actual bom artifact: https://maven.google.com/web/index.html#com.google.firebase:firebase-bom:26.8.0

which contains
```xml
            <dependency>
                <groupId>com.google.firebase</groupId>
                <artifactId>firebase-ads</artifactId>
                <version>19.8.0</version>
            </dependency>
```

...so I'm really confused! The BoM *should* have pinned that 

Are we not defining the dependency correctly here in some way such that the BoM versions are not being used :thinking: ?

Your workaround is definitely correct for now, but I'm lost as to why this is happening.

Would be curious to see the output of a `./gradlew :app:dependencies` run both with and without your coercion of the version

**Comment by juanamd** [comment]
> Would be curious to see the output of a ./gradlew :app:dependencies run both with and without your coercion of the version

[dependencies.zip](https://github.com/invertase/react-native-firebase/files/6267493/dependencies.zip)
There you go

**Comment by juanamd** [comment]
Oh, I think I might know what is going on:
My project is using another admob related package which has the following dependency:
`com.google.firebase:firebase-ads:+`

I'll test pinning that one to see if it solves it.

**Comment by mikehardy** [comment]
Ah - I'm going to close this then as it's from another package but I was unaware we had a breaking change coming and that's important for us shortly, so this has been useful all around no matter what.

Yeah the gradle dependencies target is super verbose but also the exact solution for these situations.

I think the workaround you did is the only way to pin it - it is the right way at a gradle level in your build.gradle, but that other package should have known better, you can't use a `+` for exactly this reason, it's too dangerous.

From a react-native perspective you also have the ability to use https://github.com/ds300/patch-package though - it's a fantastic tool. Until the package fixes their dependency by adding a compatible range upstream, you can reach into node_modules and pin the range in their build.gradle, then use patch-package to make it persistent in your source tree (plus it helps you make a PR nowadays, which is a nice feedback loop)

**Comment by mikehardy** [comment]
I have a PR up that will pin the dependency directly in our module (#5189) and I'll issue a v12.0.0 release here that will forward port to the new library soon
