### ISSUE TITLE
[🐛] com.facebook.react.ImageLoaderURLRequestQueue

### ISSUE THREAD

**Issue by alicancelik** [invertase/react-native-firebase#5129]
Hey everyone. I can not repro this bug but firebase show more than i expected. Actually i have no idea what caused this error. This is why i need your help. It happens only IOS

Description
Crashed: com.facebook.react.ImageLoaderURLRequestQueue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

React Native version:
0.61.5

Steps To Reproduce
I can not reproduce

Expected Results
There should be no mistake

![image](https://user-images.githubusercontent.com/26031105/113824850-ed72c400-9788-11eb-82c2-818cb9bb6c1f.png)

**Comment by mikehardy** [comment]
There is nothing to indicate this has anything to do with react-native-firebase.
