### ISSUE TITLE
Unable to resolve module ./internals

### ISSUE THREAD

**Issue by neverlan** [invertase/react-native-firebase#513]
### Issue

<img width="335" alt="capture d ecran 2017-10-15 a 19 28 45" src="https://user-images.githubusercontent.com/5860671/31587289-7d96e7e8-b1df-11e7-9faf-205f7944aecd.png">

### Environment

1. Application Target Platform: iOS
2. Development Operating System: macOS Sierra
3. Build Tools:  Xcode 9.0
4. React Native version: 0.49.3
5. RNFirebase Version: 3.0.3

**Comment by Ehesp** [comment]
Is the file there in your node modules directory?

**Comment by neverlan** [comment]
Yes the file is there :)

**Comment by Ehesp** [comment]
@neverlan do you have a sample project we could check? Seems as though it's a packager issue. 

Could you do `npm start -- --reset-cache` and see if it works?

**Comment by chrisbianca** [comment]
Closing this as it seems to be an isolated issue and we've heard no more.  Please re-open if you're still having problems.

**Comment by mikeumus** [comment]
It's happening to me now. :(
