### ISSUE TITLE
[🐛] 🔥 Firebase* Swift imports not working on integrating framework depending upon Firebase itself

### ISSUE THREAD

**Issue by mohsinulhaq** [invertase/react-native-firebase#5130]
## Issue

Describe your issue here
I have a Cocoapods Swift framework that depends on Firebase (Core, Database, Storage, and a few others). I'm trying to add that framework to my app that also depends on Firebase via `react-native-firebase`. After I added the framework to my app and tried to build the app, I get the following error for all `Firebase*` imports in the Framework's Swift code:

```
No such module 'FirebaseCore'
No such module 'FirebaseAuth'
...
```
I tried cleaning everything, from node_modules to build folder to derived data.
I also tried using `$RNFirebaseAsStaticFramework = true`.
But nothing worked for me.

Please point me in the right direction.
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
    "@react-native-firebase/app": "10.1.0",
    "@react-native-firebase/auth": "10.1.1",
    "@react-native-firebase/crashlytics": "10.1.1",
    "@react-native-firebase/database": "10.1.1",
    "@react-native-firebase/dynamic-links": "10.1.1",
    "@react-native-firebase/firestore": "10.1.1",
    "@react-native-firebase/messaging": "10.1.1",
    "@react-native-firebase/perf": "10.1.1",
    "@react-native-firebase/remote-config": "10.1.1",
}
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "messaging_android_notification_channel_id": "xxx_notification_id",
    "messaging_ios_auto_register_for_remote_messages": false
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
$FirebaseSDKVersion = '7.2.0'
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 111.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.1 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/opt/node@12/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 10.1.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y` & `3.9.5`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Sorry I'm not sure anyone that regular answers questions here (myself included) has ever seen a situation or error like this, I'm not sure you will receive any pointers in the right direction

I can say that we (react-native-firebase) depend on firebase-ios-sdk via cocoapods and you can see all our podspecs etc. You should be able to make a native quickstart of one of the modules (https://github.com/firebase/quickstart-ios/tree/master/firestore maybe, I just randomly picked firestore, no particular reason) then reproduce it natively and maybe get help from the firebase-ios-sdk folks, or perhaps from stackoverflow

I don't believe this will be a react-native-firebase problem in the end, unless there is some incompatibility between SPM and Cocoapods maybe, at which point I have no idea we would untangle that as all of react-native is built on cocoapods

**Comment by mohsinulhaq** [comment]
https://github.com/mohsinulhaq/Swift-Firebase-Framework-error
@mikehardy here's a repro for the issue, for easy development, I have put the Framework in the `ios/TestFramework` folder instead of another GitHub repo.

Run `yarn`. post-install hook handles the pod installation.
Once installation completes, building the app will produce the above error of it not able to compile the Swift files in the framework.

**Comment by mikehardy** [comment]
Hey @mohsinulhaq - to help me with this - can you tell me *exactly* the steps you took to create that repro?

As an example I usually construct repros automatically like so: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh (or https://github.com/react-native-device-info/react-native-device-info/blob/master/refresh-example.sh) because for structural issues like this - which I frequently have to solve - I need to know exactly how things were put together in order to change the one thing (like a header import style or similar) that causes it to not work when it is all put together

I'm not asking you to make a script just emphasizing that knowing exactly how things were constructed could help a lot if you can remember the steps you took

**Comment by mohsinulhaq** [comment]
@mikehardy 
Ok, so I created a new Typescript React Native project using `create-react-app`. Then, I created a new Swift Framework from Xcode, putting it inside ios folder.
To both projects' Podfile I add some Firebase pods as dependencies. Also adding those to the Framework podspec.
Then I add the new local Framework to the app Podfile.
And I finally ran pod install.

Then I run the app via Xcode. And voila, you get that dreadful error.

**Comment by mikehardy** [comment]
Great thank you! Have you done this to allow references across languages, the bridging headers? https://support.swiftify.com/hc/en-us/articles/360032764371-Using-Objective-C-and-Swift-Bridging-Headers

**Comment by mikehardy** [comment]
:sweat_smile: okay, I was just checking prior to pulling it and trying it - you have to realize my support spans about 7 busy repositories now and pulling a reproduction locally and building it is *incredibly* time consuming vs the typical issue so I have to make really really sure it's worth the time first or there might be 50 other issues (with real people behind them also) that could be helped in the meantime.

But for real issues of course, I give them a shot. I'll put it on the queue - thank you very much for confirming

**Comment by mohsinulhaq** [comment]
@mikehardy yes, I can imagine :) Thanks!
BTW I just tried replacing that import with the `#import <FirebaseCore/FirebaseCore.h>`
But on clean building I still got, `No such module FirebaseCore`.

**Comment by mikehardy** [comment]
I don't mind at all, higher chance of resolution there because they have much deeper ios skills but only if based off their Quickstarts, they typically reject react-native items as our layer can really complicate their efforts to diagnose

**Comment by mohsinulhaq** [comment]
Oh is that so 😅. I was thinking the same but then I saw they have a react-native label, and they applied that to the issue. So that gave me some hope. :D

**Comment by mikehardy** [comment]
With deep respect for that crew - they are very responsive and super helpful - I think that usually means "low priority" or "will not investigate" (and I do say that with deep respect - I can hardly blame them, we do have bugs here sometimes and the troubleshooting is really really hard with react-native / react-native-firebase layered on top). They provide fantastic quickstarts https://github.com/firebase/quickstart-ios/tree/master/authentication

**Comment by shamilovtim** [comment]
We are also hitting this issue via `react-native-firebase`. We get the "no such module FirebaseCore"

**Comment by mikehardy** [comment]
Have you tried following up here? https://github.com/firebase/firebase-ios-sdk/issues/7856

**Comment by shamilovtim** [comment]
Resolved. To fix:

-Delete node_modules
- `yarn install`
- Delete /ios/Pods
- `pod install --repo-update`

**Comment by mikehardy** [comment]
@shamilovtim also known as `npx react-native-clean-project` (does much more than what you mentioned, includes cleaning for about 5 problems you haven't had before but will waste your time like you would not believe if you have them...)

**Comment by shamilovtim** [comment]
Awesome I'll check out that project

**Comment by shamilovtim** [comment]
How often do you run that, out of curiosity?

**Comment by mikehardy** [comment]
I'm a library maintainer so always dealing with bleeding edge / broken stuff, so...semi-frequently while coding but that is not normal.

Most people should not need it unless they have unexplained compile errors or very strange runtime behaviors

I run it as part of my release process in order to know I have reproducible builds.
