### ISSUE TITLE
[🐛] Screen name (not set)

### ISSUE THREAD

**Issue by jorge-o-murillo** [invertase/react-native-firebase#5131]
## Issue

Hello. I have a working setup, but under "Events" -> "User engagement" -> "Screen name" there's a property populated as (not set):
![Screen Shot 2021-04-07 at 5 40 56 PM](https://user-images.githubusercontent.com/75639668/113952777-38153000-97cb-11eb-9daa-3504b4282949.png)

I've made sure that all calls to the `logScreenView` method include strings or numbers in its parameters.
The `DebugView` also doesn't show any property being set as such, and I'm not sure what exactly triggers this.
Any help is very much appreciated. Thanks.

---

### Javascript
```
import firebase from '@react-native-firebase/app';
import analytics from '@react-native-firebase/analytics';

class Analytics {
  ...
  async trackScreen(screenName, screenTag) {
    analytics().logScreenView({
      screen_class: screenTag,
      screen_name: screenName
    });
  }
```
<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
    "@react-native-firebase/analytics": "^8.0.1",
    "@react-native-firebase/app": "^9.0.0",
    "@react-native-firebase/crashlytics": "^8.5.2",
    "@react-native-firebase/messaging": "^8.0.1",
```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I would update to current stable versions (v11.2.0) and see if you can reproduce - let us know and we can re-check

**Comment by artemkhalygov** [comment]
@mikehardy Hello, I have the same issue on v11.2.0

**Comment by artemkhalygov** [comment]
@mikehardy Sorry for that, today all screen names are visible on the dashboard. Thank you!

**Comment by artemkhalygov** [comment]
@mikehardy Sorry for that, today all screen names are visible on the dashboard. Thank you!

**Comment by mikehardy** [comment]
ok - thanks for the report - back to needing user response then as this does not seem generally reproducible

**Comment by ShaneMckenna23** [comment]
@jorge-o-murillo 
I just encountered this issue. Updating to the latest stable version and updating my pods solved it.

**Comment by se09deluca** [comment]
Hi, i can provide some info about my experience with this bug.
i'm experimenting this issue with these dependencies:

    "react-native": "0.66.3",
    "@react-native-firebase/analytics": "14.0.0",
    "@react-native-firebase/app": "14.0.0",
    "@react-navigation/bottom-tabs": "^5.11.7",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "react-native-screens": "^3.10.1",
    
I was experimenting duplicated screens tracking, a first with screen_name and screen_class set by me, and others anonymous firebase_screen_name (not set) and firebase_screen_class  'RNSScreen', leading to events related to (not set) screen :/ (i also noticed that firebase_event_origin is 'auto', instead of 'app')

I've figured out that this is addressable to **react-native-screens**, when i remove it (so using createStackNavigator instead of createNativeStackNavigator), the bug goes away, no more (not set) screen name.

I've tried also with lower version of react-native-firebase (10.5.x) and higher of react-navigation (v6).

**Comment by mikehardy** [comment]
It appears this may be disabled @se09deluca - I believe that is the "automatic screen tracking" you are seeing https://firebase.google.com/docs/analytics/screenviews#disable_screenview_tracking

We don't currently expose this toggle in firebase.json meaning you have to dive into your AndroidManifest.xml itself and set it off there, if you want to use react-native-screens and native stack navigator. If that works (turning it off in your AndroidManifest.xml + using native stack) let us know. Maybe we could expose the config element as an item in firebase.json? A PR for that isn't so bad, looks like this: https://github.com/invertase/react-native-firebase/pull/5600/commits/802ab6ea940116ffb585f23d8e0bfb82ee0a3287

**Comment by se09deluca** [comment]
Oh yes, thank you! 🙏🏻
I turned it off on AndroidManifest.xml and Info.plist and now it works as expected (even with native stacks).

I think during this weekend i can work on the PR, in order to expose this config in firebase.json. 😁

**Comment by mikehardy** [comment]
Great! Glad that worked, and happy to merge something, Looks like it's called `FirebaseAutomaticScreenReportingEnabled` on iOS btw - so those are the two key names needed inside the config machinery
