### ISSUE TITLE
[🐛] Firestore emulator - Error: [firestore/unavailable] The service is currently unavailable

### ISSUE THREAD

**Issue by francesco-clementi-92** [invertase/react-native-firebase#5132]
## Issue

Hello and really thanks for your work.
I'm trying to connect my app with firestore emulator, but the auth service is pointing to the remote service and firestore is giving me this error:
[Error: [firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.]

I read all the issues about it and tryed almost everything that was written like in this issue:
https://github.com/invertase/react-native-firebase/issues/2953

Any help where should I look for debugging is really appreciated.

I'm using windows with an android app running on real device plugged with a cable to my computer.

I can access the emulator from the ui without problems and the functions emulator such like triggers are working fine with the firestore emulator

### Javascript

I configured the following code:
```
export const db = firebase.firestore();
db.settings({
  host: '10.0.2.2:8080',
  ssl:false,
  persistence:false
})
```
in almost every relevant part of my code such as index.js, app.js and directly into the query, but I keep getting the service unavailable error.

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/app": "^11.2.0",
"@react-native-firebase/auth": "^11.2.0",
"@react-native-firebase/firestore": "^11.2.0",
"@react-native-firebase/messaging": "^11.2.0",
"@react-native-firebase/storage": "^11.2.0",
"react": "17.0.1",
"react-native": "0.64.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! There is not sufficient info in your issue to say.

But you did say:

> I'm using windows with an android app running on real device plugged with a cable to my computer.

My guess is you need the actual network interface IP address of your computer, and you need to use that as the address to connect to, and you need to make sure in your AndroidManifest (or network security config) that unencrypted connections are allowed from your Android app to that IP address (or subnet) e.g. https://github.com/facebook/react-native/blob/eb13baf2a687b53dde04b9a336f18629d94f4b79/template/android/app/src/debug/AndroidManifest.xml#L8

In the end there will be no action to take on the part of this repository, this will be a local project issue, so I'm going to close this, but of course I hope you are able to get it working

If for some reason there is an actual problem with the module we can reopen
