### ISSUE TITLE
New firebase-ads / google-mobile-ads-sdk incompatible with v11

### ISSUE THREAD

**Issue by mikehardy** [invertase/react-native-firebase#5150]
**If you are using `@react-native-firebase/admob`, you must not update to firebase-android-sdk v27.x.x with react-native-firebase v11.x.x**

## Issue

The upcoming 27.0.0 firebase-android-sdk will contain an updated firebase-ads reference (v20 there, previous v19) https://firebase.google.com/support/release-notes/android

That references an updated v20 of google-mobile-ads-sdk - https://developers.google.com/admob/android/migration

react-native-firebase v11.x.x is not compatible with this breaking change (yet), specifically:

-  #5127 / InterstitialAd API usage to be removed
- then a list of too many other things to mention, it's a big change!

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I have a PR up that will pin the dependency directly in our module (#5189) and I'll issue a v12.0.0 release here that will forward port to the new library soon

**Comment by mikehardy** [comment]
When the forward port is done and v27 is the BoM we should also be able to remove the browser dependency workaround #4490 - https://github.com/invertase/react-native-firebase/pull/4873/commits/56c653e62d163430042db6b1ca1a760c0c258ba4

**Comment by mikehardy** [comment]
With apologies Admob no longer present in v12 as it was removed in upstream SDKs so there are no APIs to wrap any longer - please stay with v11.5 until migration to another project (either from this same code in a new repo - planned, or a different project)

**Comment by birdofpreyru** [comment]
To prevent the bot from closing this issue, I'll wonder: any news on AdMob support by RN-Firebase, or a well-tested advice on an easy migration from RNF-Admob@11.5.0 to a different library? Also, the last time I checked, I understood that Ads were gone from Firebase and this library for good, but checking-in now, and finding this ticket, it reads like a new ads implementation is in-place in Firebase, and potentially will be supported by RN-Firebase library? Can somebody clarify what is going on, and what is the recommended course of action for folks who still depend on RNF-Admob@11.5.0?

**Comment by mikehardy** [comment]
Hey there! Good catch waking the stale bot up. Status (or, announcements) will be here - #5329 as that has the most traffic.
I don't have updates, but 

- admob is no longer a part of firebase at all, throughout firebase ecosystem - that's an upstream change. It's done, we're just following
- the plan is: lift-and-shift admob code from `@react-native-firebase/admob` v11.5 to the new-not-public-yet `react-native-admob` that will be under Invertase namespace (I think), then open it up to the community for forward ports etc with similar level of quality / docs / support that react-native-firebase has enjoyed over the years

The holdup is mostly on invertase / my end as I was just personally unavailable for nearly a month and it's been quite a struggle to get back to the leading edge of all my work efforts and really move them forward - apologies for that

This comment really sums up the state and we have a discussion open so I'm going to close the issue but hopefully the explanation make it clear what the thinking / plan is
