### ISSUE TITLE
Install app via dynamic link is not receiving the link(and params) after opening the app

### ISSUE THREAD

**Issue by gayathrithedev** [invertase/react-native-firebase#5157]
## Issue

Describe your issue here
---
When user click on the dynamic link... it is taking the user to play store to install the app. After successful installation when opening the app the incoming link is not received to read the params over the url. Again I need to click on the link to receive the params over the url.
### Javascript
Attached the code snippet how I am trying to read the params over the incoming url
```
React.useEffect(() => {
    dynamicLinks()
      .getInitialLink()
      .then((link) => {
        const url_string = link?.url;
        var regex = /[?&]([^=#]+)=([^&#]*)/g,
          params = {},
          match;
        while ((match = regex.exec(url_string))) {
          params[match[1]] = match[2];
        }
        const sid = params?.sid;
        if (sid) {
            navigate('ViewVideo', {
              sid: sid,
            });
        }
      });
  }, []);
  ```

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Maybe #4548, maybe #2660 but you skipped the template, so we have nothing to reason on
Issues with no template are closed.
