### ISSUE TITLE
V5->V6 migration guide missing change that firebase.messaging().subscribeToTopic(*) 'topic' must not include "/" (was allowed before?)

### ISSUE THREAD

**Issue by Stas-Buzunko** [invertase/react-native-firebase#5158]
## Issue

FIrebase docs (https://firebase.google.com/docs/cloud-messaging/send-message) say 
// The topic name can be optionally prefixed with "/topics/".

And we have been using prefixed strings for many years and after upgrade to v6 app shows this error which is weird when official firebase docs mention prefixing.

why is that?

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You skipped the template, so I can't say. I have no information with which to reason.
I will say that you linked an SDK doc that is for admin SDK or FCM app server, we reference the firebase-js-sdk and wrap the firebase-android-sdk / firebase-ios-sdk which are slightly different products with different capabilities, and in particular sending messages is not allowed, so I don't believe this error originates here?

**Comment by Stas-Buzunko** [comment]
@mikehardy here is a link to android docs
https://firebase.google.com/docs/cloud-messaging/android/topic-messaging#build_send_requests

**Comment by Stas-Buzunko** [comment]
rn-firebase v5 worked fine with firebase.messaging().subscribeToTopic('/topics/whatever/')
rn-firebase v6 breaks with error specified above and docs kinda recommend prefixing (why would they mention it otherwise?), so yes, i believe it's rn-firebase layer where error appears

**Comment by mikehardy** [comment]
Ah, I see what you mean.
For API purposes, we use firebase-js-sdk as our API of reference where possible. 
https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging

They don't offer this API, so we have no cross-compatibility concerns. Our API can appear however "we" (react-native-firebase) wants effectively, and apparently during switch from v5 to v6 some decision was made to not allow slashes prepending. Why? Not sure

Does it work without the slash? Are the *react-native-firebase* docs clear on the subject?

**Comment by Stas-Buzunko** [comment]
"and apparently during switch from v5 to v6 some decision was made to not allow slashes prepending." - would be great to add this to migration guide and/or messaging guide.

no more questions, have a nice day

**Comment by mikehardy** [comment]
Adding to the migration guide is a great point if that changed - I'll re-open and tag for that - do note if you want to beat me to it all the docs have a little edit button at top right and the github web UI makes docs PRs effectively just a couple clicks. We certainly don't have perfect docs but we're always trying to make them better and the majority of docs tweaks like that come from users :raised_hands:

**Comment by Stas-Buzunko** [comment]
https://github.com/invertase/react-native-firebase/pull/5160

**Comment by Stas-Buzunko** [comment]
https://github.com/invertase/react-native-firebase/pull/5161
