### ISSUE TITLE
[🐛] BannerAd doesn't send any request during the first screen mount on Android

### ISSUE THREAD

**Issue by s-belous** [invertase/react-native-firebase#5179]
## Issue

I'm using BannerAd and seeing that the component doesn't show the ad when the screen was mounted for the first time after the app was launched. If I navigate to another screen and then go back, all works fine. Also, in my first case, no onAdLoaded or onAdFailedToLoad was called, it seems like the app doesn't send any request at all.

I did some investigation and found that `requestAd` function works only if `unitId`, `request` and `size` properties are not null:

https://github.com/invertase/react-native-firebase/blob/9189f3d801b6b09efacec5b1fae5db0a1216fd45/packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobBannerAdViewManager.java#L186

But the setters of properties `unitId` and `request` don't call `requestAd` function, like their implementation for ios or like `size` setter.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 205.07 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: Not Found
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^11.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - "@react-native-firebase/admob": "^11.2.0"
- **Are you using `TypeScript`?**
  - `Y` & `^4.2.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there - as with your issue, thanks for your patience. I'm not super familiar with admob as I don't use it myself which also implies that I don't have a good test rig for this whereas I'm certain you do and it appears you've found the code with the problem.

My best advice is to directly manipulate the java code inside node_modules until it works for you, use patch-package (it's fantastic, if you haven't already incorporated it https://github.com/ds300/patch-package) to persist your work and post the resulting PR (or paste the patch in here) - I'd be happy to work with you to get it merged and released quickly

**Comment by mikehardy** [comment]
With apologies Admob no longer present in v12 as it was removed in upstream SDKs so there are no APIs to wrap any longer - please stay with v11.5 until migration to another project (either from this same code in a new repo - planned, or a different project)

**Comment by minhchienwikipedia** [comment]
@s-belous Did you find the solution to fix this issue? 
@mikehardy With your experience do you have a solution to fix this issue? I can change it by myself (I know it's not update anymore)

**Comment by minhchienwikipedia** [comment]
I found it, seems they call `requestAd` function in `setSize` void, and the `setSize` void has called the first, I just change `requestAd` to the `setRequest` void. And it's works for me!
Just run this patch
```
filePath =
    'node_modules/@react-native-firebase/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobBannerAdViewManager.java';
fs.writeFileSync(
    filePath,
    fs
        .readFileSync(filePath)
        .toString()
        .replace(`requestAd(reactViewGroup);`, ``)
        .replace(
            `request = ReactNativeFirebaseAdMobCommon.buildAdRequest(value);`,
            `request = ReactNativeFirebaseAdMobCommon.buildAdRequest(value);
    requestAd(reactViewGroup);`,
        ),
);
```

**Comment by mikehardy** [comment]
You should try 'patch-package' it's marvelous for little fixes like this

**Comment by minhchienwikipedia** [comment]
@mikehardy :D yeah, I have never tried it before but I'll

**Comment by s-belous** [comment]
> @s-belous Did you find the solution to fix this issue?

My solution is to call `requestAd` function explicitly from the JS side. So I removed `requestAd` calls from properties setters, exported that method from native modules (both for iOS and Android), and called it on `BannerAd` mount.

I attached the patch that can be used with `patch-package`, might be helpful:
[@react-native-firebase+admob+11.5.0.patch.zip](https://github.com/invertase/react-native-firebase/files/7575384/%40react-native-firebase%2Badmob%2B11.5.0.patch.zip)
