### ISSUE TITLE
[messaging] Background notification behavior

### ISSUE THREAD

**Issue by theohdv** [invertase/react-native-firebase#518]
### Issue

When I received Remote Notification and my app is in background, the notification is displaied in the notification tray (normal behavior).

If I click on the notification, it opens the application and `onMessage()` is called and the notification object has all the data properties I sent.

But if i open the application not by clicking on the notification but by clicking in the application's icon. `onMessage()` is called but the notification object has nothing except:

```javascript
{
  "opened_from_tray" : true // Which is false
  "fcm": {
    "action": "foobar"
  }
}
```

**EDIT:** This happened **each time** my application changes **from background state to foreground state**, so OnMessage() is called each time I open the application.

My data are not there and so it is difficult to know what need to be done.

### Environment

Tested on Android but not on iOS

2. Development Operating System: 
macOS Sierra

4. React Native version: 
0.48.4

5. RNFirebase Version: 
3.0.3

6. Firebase Module: 
messaging

**Comment by chrisbianca** [comment]
Thanks for reporting.  We're aware of lots of issues with notifications and will be addressing them all as part of the v3.2.0 release stream.  Please see https://github.com/invertase/react-native-firebase/issues/595 for updates.

**Comment by togusa2017** [comment]
@theohdv I am using 3.2.1 and i still see the issue. Do you see it resolved.

**Comment by Ehesp** [comment]
@togusa2017 it's been pushed back to 3.3.0 - see the issue linked above

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)
