### ISSUE TITLE
[🐛] BannerAd has incorrect types

### ISSUE THREAD

**Issue by s-belous** [invertase/react-native-firebase#5180]
## Issue

Callbacks properties of BannerAd are optional but required in TypeScript interface:

https://github.com/invertase/react-native-firebase/blob/c94546d8127606dca5bfd09ef92ec32eec333f19/packages/admob/lib/index.d.ts#L1135

https://github.com/invertase/react-native-firebase/blob/c94546d8127606dca5bfd09ef92ec32eec333f19/packages/admob/lib/index.d.ts#L1140

https://github.com/invertase/react-native-firebase/blob/c94546d8127606dca5bfd09ef92ec32eec333f19/packages/admob/lib/index.d.ts#L1145

https://github.com/invertase/react-native-firebase/blob/c94546d8127606dca5bfd09ef92ec32eec333f19/packages/admob/lib/index.d.ts#L1150

https://github.com/invertase/react-native-firebase/blob/c94546d8127606dca5bfd09ef92ec32eec333f19/packages/admob/lib/index.d.ts#L1155

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 205.07 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: Not Found
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^11.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - "@react-native-firebase/admob": "^11.2.0"
- **Are you using `TypeScript`?**
  - `Y` & `^4.2.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi @s-belous sorry for the delay - normally we defer to firebase-js-sdk for types but admob is not present in the firebase-js-sdk so we have our own control here. 

You appear to be mostly correct, as the events when they bubble up from native are checked against the passed arguments to see if the event type has a function name that matches, meaning not providing the method would pass:

https://github.com/invertase/react-native-firebase/blob/1f7d03609aaa4abb56a34d162f0fc6a7b21b9d2d/packages/admob/lib/ads/BannerAd.js#L65

However, if they were all marked as optional and zero of them were passed in, would the rest arg `props` be undefined here, resulting in an exception?  https://github.com/invertase/react-native-firebase/blob/1f7d03609aaa4abb56a34d162f0fc6a7b21b9d2d/packages/admob/lib/ads/BannerAd.js#L29

I'm not super familiar with javascript rest args but having just researched them it appears this would work fine

If you post a PR to make the types all optional I could merge it

**Comment by DoctorJohn** [comment]
@mikehardy a little tests confirms the rest `props` would not be undefined:

```sh
Welcome to Node.js v14.16.0.
Type ".help" for more information.
> function fun({arg1, ...props}){console.log(arg1, props);}
undefined
> 
> fun({arg1: "ARG1", arg2: "ARG"})
ARG1 { arg2: 'ARG' }
undefined
> 
> fun({arg1: "ARG1"})
ARG1 {}
undefined
> 

```

I will create a PR correcting the types in a moment.
