### ISSUE TITLE
[auth/internal-error] an internal error has occurred, please try again. (IOS Problem but Android worked)

### ISSUE THREAD

**Issue by tyhour** [invertase/react-native-firebase#5183]
For this I use  "@react-native-firebase/auth": "^11.2.0" / "react-native": "0.63.4"

I just to meet this issue with my current project right now. Android pretty work but IOS always error with this.
I can get data from firestore but I can use auth with it.
I try to clear some cache with XCode and my project also, but It still not working. Thanks for help!!!

**Comment by mikehardy** [comment]
With apologies, no help is provided when the template is skipped.

**Comment by tyhour** [comment]
> With apologies, no help is provided when the template is skipped.

I don't understand about your explain, can you detail for me ?  Thanks for help

**Comment by mikehardy** [comment]
@tyhour what I mean is that you came to this repository

Which is like walking up to a colleague's desk) to ask for help

This repository, when you click the button to make a new issue pre-populates the text area with the information we need to troubleshoot

Which is like your colleague saying "oh, interesting, can you give me the details of your setup?"

But you deleted that. You did not provide the details we asked. So I closed the issue

Which is like you ignoring your colleague's request and your colleague saying "sorry without details I can't help".

Open a new issue, do not ignore the template, provide the details.

**Comment by tyhour** [comment]
> @tyhour what I mean is that you came to this repository
> 
> Which is like walking up to a colleague's desk) to ask for help
> 
> This repository, when you click the button to make a new issue pre-populates the text area with the information we need to troubleshoot
> 
> Which is like your colleague saying "oh, interesting, can you give me the details of your setup?"
> 
> But you deleted that. You did not provide the details we asked. So I closed the issue
> 
> Which is like you ignoring your colleague's request and your colleague saying "sorry without details I can't help".
> 
> Open a new issue, do not ignore the template, provide the details.



> @tyhour what I mean is that you came to this repository
> 
> Which is like walking up to a colleague's desk) to ask for help
> 
> This repository, when you click the button to make a new issue pre-populates the text area with the information we need to troubleshoot
> 
> Which is like your colleague saying "oh, interesting, can you give me the details of your setup?"
> 
> But you deleted that. You did not provide the details we asked. So I closed the issue
> 
> Which is like you ignoring your colleague's request and your colleague saying "sorry without details I can't help".
> 
> Open a new issue, do not ignore the template, provide the details.

Oh Ok, now I already fixed it. thanks

**Comment by mksglu** [comment]
@tyhour how can fix that? why you don't explain questions and solving?

**Comment by tyhour** [comment]
Just change bundle identifier in xCode and then re-config with firebase
again. I thinks this problem with cache of firebase's server only.
