### ISSUE TITLE
Dynamic Links - Can't add fallback url for other platforms

### ISSUE THREAD

**Issue by Sheleya** [invertase/react-native-firebase#5184]
https://firebase.google.com/docs/dynamic-links/create-manually supports adding **ofl** parameter which supports fallback url for other platforms i.e. opening dynamic link via computer.

I need next scenario:
 - opening link with installed app opens app (+)
 - opening link with no app opens PlayMarket/AppStore (+)
 - opening link via computer redirects to fallback url (-)

I have implemented this Manually constructing url, but I need this with buildShortLink() method 

RN - 0.63.3
Version - 10.1.1

**Comment by mikehardy** [comment]
We do not provide support when people skip the template (or in general for out of date versions), and for this one I would definitely need to see the code you use to generate the link.

I'm curious why this is not working? https://rnfirebase.io/reference/dynamic-links/dynamiclinkiosparameters#fallbackUrl - perhaps it is not url encoded correctly - it works in my app

Without a [minimal reproducible example App.js](https://stackoverflow.com/help/minimal-reproducible-example), I can't say.

**Comment by Sheleya** [comment]
> We do not provide support when people skip the template (or in general for out of date versions), and for this one I would definitely need to see the code you use to generate the link.
> 
> I'm curious why this is not working? https://rnfirebase.io/reference/dynamic-links/dynamiclinkiosparameters#fallbackUrl - perhaps it is not url encoded correctly - it works in my app
> 
> Without a [minimal reproducible example App.js](https://stackoverflow.com/help/minimal-reproducible-example), I can't say.

```
const link = await dynamicLinks().buildShortLink(
      {
        link: ,
        domainUriPrefix: ,
        ios: {
          fallbackUrl: ,
          bundleId: ,
        },
        android: {
          fallbackUrl: ,
          packageName: ,
          minimumVersion: '18',
        },
      },
      dynamicLinks.ShortLinkType.DEFAULT,
    );
```
In the Firebase console I have created free Google-provided domain. 
When I'm creating dynamicLink manually everything works as expected.
I'm implementing dynamicLink in this way, every object field is filled. And when I try to open this link using phone it works, as expected, but when I try to open using computer I got:
<img width="656" alt="Screenshot 2021-04-16 at 18 25 51" src="https://user-images.githubusercontent.com/42179511/115047989-c2ebde00-9ee1-11eb-95ee-11b1fb3e4be6.png">

**Comment by mikehardy** [comment]
In the code you pasted the object parameters appear empty, not sure what happened there but if that's how the code actually is, that's the problem

Additionally have you tried pasting the link in for debugging https://firebase.google.com/docs/dynamic-links/debug

**Comment by Sheleya** [comment]
> In the code you pasted the object parameters appear empty, not sure what happened there but if that's how the code actually is, that's the problem
> 
> Additionally have you tried pasting the link in for debugging https://firebase.google.com/docs/dynamic-links/debug

No, I mentioned that
 > every object field is filled
So, I pass everything correctly to the object

**Comment by mikehardy** [comment]
What you have done is nothing like a minimal reproducible example, sorry

https://stackoverflow.com/help/minimal-reproducible-example

Post an App.js that is complete and runs and demonstrates the problem or this will not move forward, sorry.

If you have problems with proprietary information you may put literally any values in there that work and demonstrate the failure. Note you may create a sample firebase project for free on their free plans at any time if that is a constraint

**Comment by skam22** [comment]
@Sheleya PR submitted that fixes your issue,  the parameter will have to be provided using this format:

```
buildShortLink({
  // … other params,
  otherPlatform: {
    fallbackUrl: ‘https://urlToOpenOnDesktop.com/‘
})
```

**Comment by adamsythe** [comment]
@skam22  I am on version ^17.4.3 and fallback doesn't work on otherplatforms.  Any idea if this is still stable?

My code looks like this (everything else is working)

link = await dynamicLinks().buildShortLink({
            link: `MyLink`,
            // domainUriPrefix is created in your Firebase console
            domainUriPrefix: domainUriPrefix,
            ios: {
              bundleId: bundleId,
              appStoreId: appStoreId,
            },
            android: {
              packageName: packageName,
            },
            social: {
              descriptionText: 'text',
              title: shop?.title,
              imageUrl: shop?.new_feature_image.small,
            },
            otherPlatform: {
              fallbackUrl: 'www.google.com'
            }
          });

**Comment by skam22** [comment]
Try putting the full url including https:// in there. 

If that doesn’t work view dynamic link debug in browser to see what was actually generated as the fallback.

**Comment by adamsythe** [comment]
Thanks for getting back to me apologies for not noticing, we tried everything on this but in the end it was easier to just generate these server side and pass them into the app.
