### ISSUE TITLE
[Android]: DuplicateFileException:  Duplicate files copied in APK META-INF/maven/com.squareup.okio/okio/pom.xml

### ISSUE THREAD

**Issue by shubhangi-asgola** [invertase/react-native-firebase#520]
I am trying to integrate react-native-firebase to my project. I followed all the setup instructions.  Initially I got some errors. On searching I found it required google play services to be updated. Errors were gone after update.
Then I face duplicate dependency issues for which I excluded play-services from specific modules using them and included them in dependencies. Part of my build.gradle dependencies looks as below after that:
dependencies {

  // RNFirebase required dependencies
  compile(project(':react-native-firebase')) {
    transitive = false
    exclude group: 'com.google.android.gms'
  }
  compile "com.google.firebase:firebase-core:11.0.0"
  compile "com.google.firebase:firebase-database:11.0.0"
    compile project(':react-native-fbsdk')
    compile project(':react-native-pdf')
    compile project(':react-native-maps')
    compile project(':react-native-image-resizer')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-contacts')
    compile project(':react-native-code-push')
    compile project(':RCTTwilioChat')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-exif')
    compile project(':react-native-share')
    compile(project(':react-native-maps')){
       exclude group: 'com.google.android.gms'
   }
    compile project(':react-native-geocoder')
    compile project(':react-native-splash-screen')
    compile project(':react-native-permissions')
    compile project(':react-native-photo-view')
    compile(project(':react-native-device-info')){
      exclude group: 'com.google.android.gms'
    }
    compile project(':realm')
    compile project(':react-native-vector-icons')
    compile project(':react-native-mail')
    compile project(':react-native-image-picker')
    compile project(':react-native-network-info')
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-html-to-pdf')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules

    compile ("com.google.android.gms:play-services-base:11.0.0") {
       force = true;
   }
   compile ("com.google.android.gms:play-services-maps:11.0.0") {
       force = true;
   }
   compile ("com.google.android.gms:play-services-gcm:11.0.0") {
       force = true;
   }
    compile 'com.facebook.android:facebook-android-sdk:[4.22.1)'
}

Now I am getting the following error:-
![image](https://user-images.githubusercontent.com/10372934/31620127-1443e8ce-b2b4-11e7-9781-5cde92cfea55.png)

If I change versions of com.google.android.gms:play-services-base,
com.google.android.gms:play-services-maps and
com.google.android.gms:play-services-gcm to 10.0.1 then I get the following error:
![image](https://user-images.githubusercontent.com/10372934/31620637-67517d00-b2b5-11e7-8cc5-5de835b65cd9.png)

I have also updated google services to the latest version from android studio.

**Comment by chrisbianca** [comment]
@shubhangi-asgola I know there were some issues with the initial 11.0.0 release.  Have you tried 11.0.4?  You'll need to make sure all versions specified for the google / firebase libraries match.

Out of interest, is there a reason you're not using the latest version of the Play Services? i.e. 11.4.2

**Comment by chrisbianca** [comment]
Closing this as there hasn't been any further response.  Please re-open with further details if this is still an issue
