### ISSUE TITLE
[Android] Notification popup is not displayed 

### ISSUE THREAD

**Issue by momirkostic** [invertase/react-native-firebase#5200]
Notifications work fine on Android, but can't see pop up at the top of the screen, only small icon at the status bar.

This is the JSON object that I sent throughout the server: 

admin.messaging().sendMulticast({
  tokens: ["some token",
],
  data: {
    hello: "world",
  },
  notification: {
    body: "Body",
    title: "Title",
  },
  // Set Android priority to "high"
  android: {
    priority: "high",
    data: {
      hello: "world",
    },
    notification: {
      body: "Body",
      title: "Title",
      sound: 'default',
      channelId: "default",
      visibility: "public",
      priority: "max"
    }
  },
  // Add APNS (Apple) config
  apns: {
    payload: {
      aps: {
        contentAvailable: true,
        sound: 'default',
      },
    },
    headers: {
      "apns-push-type": "alert",
      "apns-priority": "5", // Must be `5` when `contentAvailable` is set to true.
      "apns-topic": "...", // bundle identifier
    },
  },
});

Any suggestions?

**Comment by jerearaujo03** [comment]
Same here

**Comment by telmen** [comment]
@momirkostic Did you resolve this?

**Comment by 77TecShaeer** [comment]
????

**Comment by mikehardy** [comment]
Probably notification channel settings

**Comment by pravinsphinx** [comment]
still facing same isssue.

**Comment by eramudeep** [comment]
still facing same issue in 2023 :(
