### ISSUE TITLE
firebase semantic issue

### ISSUE THREAD

**Issue by ArjunKarki** [invertase/react-native-firebase#5216]
![Screen Shot 2021-04-27 at 10 29 08 AM](https://user-images.githubusercontent.com/33275086/116199469-2933f480-a75d-11eb-9bf1-5c133286a3b4.png)

I am struggling with this error when i install react-native firebase.
RN=>0.61.5
rnf=>5.6.0
xcode=>12.4

**Comment by mikehardy** [comment]
Please reproduce with current versions and don't ignore the issue template if you need to open a new issue
