### ISSUE TITLE
Firebase.database().push does not return key

### ISSUE THREAD

**Issue by maitham1** [invertase/react-native-firebase#522]
### Issue

I'm currently using redux saga and react native firebase however after pushing an object nothing is returned in v2.2 it would return a result where I could get a query back however it seems its broken in this case unless im doing something wrong? 
   const result = yield call([dbRef, dbRef.push], () => eventObj);

### Environment

1. Application Target Platform: 
Both

2. Development Operating System: 
macos

3. Build Tools: 
xcode

4. React Native version: 
0.49.3

5. RNFirebase Version: 
v3.0.3

6. Firebase Module: 
database

**Comment by Ehesp** [comment]
Hello, not sure how saga works but are you expecting it to return a promise here?

**Comment by Salakar** [comment]
@maitham1 push promise no longer resolves with the reference, you need to change your code to something like the following:

```javascript
const thenableRef = dbRef.push(pushSomeDataMaybe);

// new ref is an instance of DatabaseReference with .then() support, just like the web sdk
console.log(newRef.key)
console.log(newRef.path)

const pushResult = await thenableRef;
```

See the official web sdk reference guide: https://firebase.google.com/docs/reference/js/firebase.database.ThenableReference#push
