### ISSUE TITLE
getInitialNotification and onMessage are receiving react-native-navigation events

### ISSUE THREAD

**Issue by mendieta** [invertase/react-native-firebase#523]
### Issue

Hi, 

When using FCM with react-native-navigation the getInitialNotification and onMessage are receiving the navigation events.

The push notifications are working as expected, most of the time. But the onMessage handler is being triggered on every screen pop/push/change. There are cases where the notification data ius override by the navigation event data.

Here is a screenshot of the data the onMessage is receiving.
![screen shot 2017-10-16 at 8 03 18 pm](https://user-images.githubusercontent.com/245195/31641857-319b8352-b2ad-11e7-8797-ebe09134bc35.png)

Is there a way to prevent this? 

On another hand, it appears the token is being "deleted" or invalid form FCM, after a while of app usage the notifications will stop being received, and i have to manually call getToken() and after that it works again. Is this intended?

Thank you

### Environment

1. Application Target Platform:  Android

2. Development Operating System: macOS Sierra 10.12.6

3. Build Tools: Android Studio 2.3.3

4. React Native version:  0.48.4

5. RNFirebase Version: 3.0.3

6. Firebase Module: messaging

**Comment by chrisbianca** [comment]
@mendieta Thanks for flagging this - it seems like there might be some overlap in the names of events that `react-native-navigation` and `react-native-firebase` are using.  We'll investigate and if that's the case, look at changing our event names so there is no clash.

**Comment by chrisbianca** [comment]
Re: your second question.  The token can be invalidated by FCM at any time.  You should listen to the `onTokenRefresh` to get notified if this happens.

**Comment by mendieta** [comment]
thank you @chrisbianca that would be awesome .

about the second question, what happens if the token is invalidated when the app is closed "killed" on app start the token will be sent to the app?

**Comment by alfonsodev** [comment]
@mendieta I had the same problem with `getInitialNotification`, 
 you can avoid it if you call `getInitialNotification` before starting the navigation app.

**Comment by mendieta** [comment]
@alfonsodev thank you, I will try that approach for getInitialNotification

**Comment by mendieta** [comment]
@alfonsodev You were totally right, calling `getInitialNotification` before starting the navigation works just right. Just to take note, it does work on initial app start, but on "reload" from dev settings it will trigger the event with the navigation data. Which is fine on release that case wouldn't even exist. But it may be a got idea to handle that in your code just to avoid errors. Thanks

**Comment by Reiji87** [comment]
calling getInitialNotification before starting navigation app doesnt work for me.

**Comment by mendieta** [comment]
@Reiji87 can you paste here your code?

**Comment by Reiji87** [comment]
this is inside my index.ios.js

`firebase.messaging().requestPermissions();
    firebase.messaging().getToken()
      .then(response => console.log(response));

    firebase.messaging().getInitialNotification()
      .then((payload) => {
        alert('getInitialNotification');
        console.log(payload);
      });

    firebase.messaging().onMessage(() => {
      alert('OnMessage');
    });
    app.startApp();`

just this... where my app.startApp() will call startSingleScreenApp() of react-native-navigation

**Comment by chrisbianca** [comment]
We're aware of lots of issues with notifications and will be addressing them all as part of the v3.2.0 release stream.  Please see https://github.com/invertase/react-native-firebase/issues/595 for updates.

**Comment by Nitroman605** [comment]
is it really fixed in v3.2.0 ? I do not see it in the change log  or in the commits for the release ? 

Thank you guys for the amazing work .

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)
