### ISSUE TITLE
[🐛] Property 'User' does not exist on type 'typeof FirebaseAuthTypes'

### ISSUE THREAD

**Issue by maccman** [invertase/react-native-firebase#5238]
Looks like some missing Typescript definitions?

<img width="661" alt="CleanShot 2021-04-29 at 19 50 18@2x" src="https://user-images.githubusercontent.com/2142/116642664-3e0eb480-a924-11eb-8a49-dba8f3dbe39e.png">

This is in a completely new repo generated with:

`npx react-native init MyApp --template react-native-template-typescript`

## Issue

Describe your issue here

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Not sure - that works in my project, I import like so and use like so ?

```typescript

import { FirebaseAuthTypes } from '@react-native-firebase/auth';

  private userChangedHandler = async (
    user: FirebaseAuthTypes.User | null,
    additionalUserInfo?: FirebaseAuthTypes.AdditionalUserInfo
  ) => {

// etc etc
};
 
```

**Comment by maccman** [comment]
Huh interesting! Maybe an issue with visual studio code.

**Comment by maccman** [comment]
What version of react-native-firebase are you on? 

Also can you share your `tsconfig.json`. Thank you!

**Comment by mikehardy** [comment]
I'm always on most current react-native-firebase and frequently with pre-release patches, since I maintain it :sweat_smile:  - but this hasn't changed in *forever*, like pre-v10 here at least. But I'm on v11.4.1 right now for what it's worth

My react-native app is a package in a monorepo, root tsconfig is

```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "declaration": false,
    "noResolve": false,
    "incremental": true,
    "module": "commonjs",
    "target": "es5",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "./dist/",
    "strict": true
  },
  "exclude": ["node_modules"],
  "include": ["./src/**/*"]
}
```

packages/public-app/tsconfig.json is

```json
{
  "compilerOptions": {
    "composite": true,
    "noEmitHelpers": true,
    "importHelpers": true,
    "declaration": true,
    "noResolve": false,
    "jsx": "react",
    "reactNamespace": "RX",
    "module": "commonjs",
    "target": "es6",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "outDir": "./public/js/",
    "baseUrl": ".",
    "paths": {
      "modules/*": ["./src/modules/*/index.web", "./src/modules/*/index"]
    },
    "typeRoots": ["./node_modules/@types"]
  },
  "exclude": ["node_modules", "temp", ".vscode"],
  "include": ["./src/**/*"]
}

```

They are likely crappy in various ways but they work!

**Comment by maccman** [comment]
I've been banging my head against this for a few days.

Do you mind trying out a new project from scratch with:

`npx react-native init MyApp --template react-native-template-typescript`

And seeing if you're seeing the same issue (once you've added `react-native-firebase/auth`).

**Comment by DoctorJohn** [comment]
@maccman This might be vscode related. I was confused by this myself. But it turned out when types are used in the "right context" vscode intellisense works. For example:

If you type the following, vscode will complain `Property 'User' does not exist on type 'typeof FirebaseAuthTypes'`. Here for some reason the only property vscode can "see" is `FirebaseAuthTypes.Module`.

```js
import { FirebaseAuthTypes } from "@react-native-firebase/auth";

FirebaseAuthTypes.User;
```

But if you use the type in the "right context" (eg. when defining an interface), everything will be fine. Here vscode "sees" all `FirebaseAuthTypes` properties.

```js
import { FirebaseAuthTypes } from "@react-native-firebase/auth";

interface SomeProps {
  user: FirebaseAuthTypes.User,
}
```

**Comment by maccman** [comment]
Ahhh interesting. Thank you.

**Comment by mikehardy** [comment]
That might be why I can't reproduce, I'm only putting that type into app-specific interfaces then from an intellisense perspective dot-chaining off them as I code and it's always worked for me :thinking:

**Comment by Nehal-Sanklecha** [comment]
@DoctorJohn  @maccman  how did you resolve it? I'm also facing the same.

**Comment by angelxmoreno** [comment]
@Nehal-Sanklecha I had a similar issue using WebStorm. My app won't load while my WebStorm IDE sees nothing wrong:
```
 ERROR  TypeError: Cannot read property 'UserCredential' of undefined, js engine: hermes
```
The change I made was the following:
```ts
import auth, {FirebaseAuthTypes} from '@react-native-firebase/auth';
import firestore, {FirebaseFirestoreTypes} from '@react-native-firebase/firestore';
import UserCredential = FirebaseAuthTypes.UserCredential;
import DocumentReference = FirebaseFirestoreTypes.DocumentReference;

// changed to 
import auth, {FirebaseAuthTypes} from '@react-native-firebase/auth';
import firestore, {FirebaseFirestoreTypes} from '@react-native-firebase/firestore';
type UserCredential = FirebaseAuthTypes.UserCredential;
type DocumentReference = FirebaseFirestoreTypes.DocumentReference;
```
IDK why WebStorm decided to construct the types with import, but the change made the error go away.
