### ISSUE TITLE
TypeError: Attempted to assign to readonly property

### ISSUE THREAD

**Issue by CarbonC** [invertase/react-native-firebase#524]
### Issue

I get a ```TypeError: Attempted to assign to readonly property``` triggered by this code (last ligne is the one which fails):
(when remote debugger is enabled, I got this one instead ```TypeError: TypeError: Cannot set property log of [object Object] which has only a getter```)
```
import RNFirebase from 'react-native-firebase';

const firebaseInstance = () => {
  const configurationOptions = {
    debug: true,
  };
  return RNFirebase.initializeApp(configurationOptions);
};

const firebase = firebaseInstance();
const ref = firebase.database().ref('string');
```

### Environment

1. Application Target Platform: 
IOS

2. Development Operating System: 
Mac OSX

3. Build Tools: 
IOS 11, XCode 9.0

4. React Native version: 
0.49.3

5. RNFirebase Version: 
3.0.3

6. Firebase Module: 
database

**Comment by chrisbianca** [comment]
@CarbonC this is a strange one - are you using TypeScript?
Also, with v3.0.3, you no longer need to call `initializeApp` for the default app, you can simply do:

`import firebase from 'react-native-firebase'` and use this instance

**Comment by CarbonC** [comment]
I've delete the initializeApp, no problem. But the problem remains, seems to be linked to strict-mode somehow. I'm not using typescript at all but ccompile with babel...

**Comment by chrisbianca** [comment]
Can you include the full contents of the file?

**Comment by CarbonC** [comment]
But according to the stack trace the problem in react-native-firebase's code is line 78 inside the reference.js file of the database module:

```
export default class Reference extends ReferenceBase {

  _refListeners: { [listenerId: number]: DatabaseListener };
  _database: Object;
  _query: Query;

  constructor(database: Object, path: string, existingModifiers?: Array<DatabaseModifier>) {
    super(path, database);
    this._promise = null;
    this._refListeners = {};
    this._database = database;
    this._query = new Query(this, path, existingModifiers);
    this.log = this._database.log;
    this.log.debug('Created new Reference', this._getRefKey());
  }
```

**Comment by chrisbianca** [comment]
@CarbonC What do you mean by `strict-mode`? How have you enable that?

**Comment by CarbonC** [comment]
Javascript strict mode is enabled by babel, and the error message seems to be triggered due to that, without it would probably quietly fail.

**Comment by CarbonC** [comment]
I found a fix XD Deleted this line from the module:

```
this.log = this._database.log;
```
And it works 👍 But maybe this was useful somehow, helping logging... Tell me if it wasn't and you want a PR.

**Comment by chrisbianca** [comment]
@CarbonC I think you're right - the statement is unnecessary as there is a `get log()` method already. I'll update the code for the next release.

Thanks for helping track this down.

As an aside - using strict mode in RN is brave as there's no guarantee that modules will adhere to it...
