### ISSUE TITLE
[🐛] Multiple commands produce GoogleAppMeasurement in 11.4.1

### ISSUE THREAD

**Issue by mars-lan** [invertase/react-native-firebase#5248]
## Issue

After upgrading `react-native-firebase` from 11.3.3 to 11.4.1, I started getting the following build error in XCode (both 12.4 & 12.5)

```
error: Multiple commands produce '<path>/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleAppMeasurement':
1) That command depends on command in Target 'GoogleAppMeasurement' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
2) That command depends on command in Target 'GoogleAppMeasurement-AdIdSupport' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
```

### Javascript

N/A

#### `package.json`:

```json
    "@react-native-firebase/admob": "11.4.1",
    "@react-native-firebase/analytics": "11.4.1",
    "@react-native-firebase/app": "11.4.1",
    "@react-native-firebase/auth": "11.4.1",
    "@react-native-firebase/crashlytics": "11.4.1",
    "@react-native-firebase/perf": "11.4.1",
    "@react-native-firebase/storage": "11.4.1",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

Use RN auto link

#### `AppDelegate.m`:

N/A

</p>
</details>

---

### Android

N/A

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 486.53 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /var/folders/mj/nctx1fsn2cg7rdssx505z4pr0000gn/T/yarn--1619907559863-0.7526749377860467/node
    Yarn: 1.22.0 - /var/folders/mj/nctx1fsn2cg7rdssx505z4pr0000gn/T/yarn--1619907559863-0.7526749377860467/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 31.0.0
      System Images: android-22 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_271 - /usr/bin/javac
    Python: 3.7.10 - /Users/marslan/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: 4.14.0 => 4.14.0 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 11.4.1
- **`Firebase` module(s) you're using that has the issue:**
  - Analytics (I assume)
- **Are you using `TypeScript`?**
  - Y (but irrelevant)

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I really need to see your Podfile if possible - can you provide it? Also the Podfile.lock if possible to see what Pods are requiring what.

Note: #5224 *just* touched this area, and the firebase-ios-sdk 7.11.0 itself is new. It worked in testing but given it's new there may be some interaction I'm not aware of.

You can examine the test app Podfile + Podfile.lock here to see what's going on but I *think* what might be happening is that you have some other AdMob related or GoogleAppMesasurement-related pod that hasn't updated to the new names

https://github.com/invertase/react-native-firebase/tree/master/tests/ios

**Comment by mikehardy** [comment]
Also, more vague and voodoo-like, but *perhaps* a `npx react-native-clean-project` but that comes at the cost of massive network and CPU usage to repopulate caches after, and may fix nothing.

**Comment by mars-lan** [comment]
Looks like this is an issue with 7.11.0 that's resolved in 8.0: https://github.com/firebase/firebase-ios-sdk/issues/7958. Will wait till RNFB update to 8.0 to try it out again.

**Comment by mikehardy** [comment]
Interesting - or you can pin AdMobs to 7.69, it's compatible.
There is a forward port of this module that I'm hoping to merge tonight in #5309 but it's maybe not what people interested in admob will hope for, as admob is purged from the Firebase SDKs and needs to be depended on independently, but we don't have an admob solution yet (similar to the mlkit issue - where it's purged out in the last breaking change but we haven't had time to set up the infrastructure for a standalone project that wraps the separate library yet)

It will certainly fix the build issue though...

**Comment by mars-lan** [comment]
Wow that's some big breaking changes from the Firebase side. Thanks for maintaining this project. The infra work does sound quite hairy especially for Android.

**Comment by mikehardy** [comment]
Yep, IID also (finally) went away and we need to wrap the new goodies - Installations, and AppCheck, and there's a new storage emulator and firebase bundle downloads, and eventually wrap up the more coherent ML custom model downloader and pair it with the MLKit stuff. Lots of forward progress too but in general yes it's a lot! Luckily the truly core bits of db/auth/analytics/deep-links/messaging are stable

**Comment by mikehardy** [comment]
This can no longer happen in v12, but as mentioned it is because AdMob is no longer integrated. Closing this out for this repo. AdMob users staying on v11.5.0 and using compatible AdMob pods won't see this, and with the level of breaking change that just went out across firebase and AdMob it will just take time for AdMob packages to update unfortunately

**Comment by datnhemployee** [comment]
> Interesting - or you can pin AdMobs to 7.69, it's compatible. There is a forward port of this module that I'm hoping to merge tonight in #5309 but it's maybe not what people interested in admob will hope for, as admob is purged from the Firebase SDKs and needs to be depended on independently, but we don't have an admob solution yet (similar to the mlkit issue - where it's purged out in the last breaking change but we haven't had time to set up the infrastructure for a standalone project that wraps the separate library yet)
> 
> It will certainly fix the build issue though...

Thank you very much @mikehardy, you save my day, literally. I spent 8 hours yesterday to figure how to cope with this. I just follow your comment and then, it's worked.

For those who just miss the comment, please add this to your **Podfile**
`pod 'Google-Mobile-Ads-SDK', '7.69.0'`

And here is my environment:
"react-native": "0.63.4"
"@react-native-firebase/admob": "^11.5.0"
"@react-native-firebase/app": "11.5.0"

**Comment by ridvanuyn** [comment]
> > Interesting - or you can pin AdMobs to 7.69, it's compatible. There is a forward port of this module that I'm hoping to merge tonight in #5309 but it's maybe not what people interested in admob will hope for, as admob is purged from the Firebase SDKs and needs to be depended on independently, but we don't have an admob solution yet (similar to the mlkit issue - where it's purged out in the last breaking change but we haven't had time to set up the infrastructure for a standalone project that wraps the separate library yet)
> > It will certainly fix the build issue though...
> 
> Thank you very much @mikehardy, you save my day, literally. I spent 8 hours yesterday to figure how to cope with this. I just follow your comment and then, it's worked.
> 
> For those who just miss the comment, please:
> 
> 1. Add this to your **Podfile**
>    `pod 'Google-Mobile-Ads-SDK', '7.69.0'`
> 2. run **pod install**
> 
> And here is my environment: "react-native": "0.63.4" "@react-native-firebase/admob": "^11.5.0" "@react-native-firebase/app": "11.5.0"

You save my day. I've been 3 days waste on it. thanks for the code blocks 💯

**Comment by mikehardy** [comment]
React-native-google-mobile-ads oackag exists now though, is in use in production for a few, same apis but updates SDKs, rewritten in typescript etc. You might try it, we actively support it
