### ISSUE TITLE
[📚] Docs claim that an app cannot receive push notifications while quit

### ISSUE THREAD

**Issue by shamilovtim** [invertase/react-native-firebase#5256]
## Documentation Feedback

Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:

On https://rnfirebase.io/messaging/usage#receiving-messages docs say:
"If the user force quits the app from the device settings, it must be re-opened again before receiving messages."

I'm not sure how this can be true. Part of the whole reason for the existence of push notifications is to send messages to users while an app is not open. FCM docs for the SDK don't say anything about needing to have the app open to receive a push.

**Comment by mikehardy** [comment]
There are more states than "open" and "quit", and they must not be confused.

On Android, there are:
- force quit (user force stopped from settings) - your app is likely dead. Won't receive an FCM data-only, notification probably not either
- flicked away from launcher (an FCM may not start it again, but motion or GPS might)
- background - FCM data-only away! but mind how many you send, there are power constraints. Notifications probably fine
- background and doze mode, may not receive FCM data-only, be very careful of how many and what priority. Notification block probably okay
- background vendor-specific - no FCM https://dontkillmyapp.com 
- foreground - FCM away, no problems

FCM upstream docs just gloss over all of it. But you'll encounter all of it. 

Your statement "I'm not sure how this can be true" sounds like what I thought before I started working on the project a lot and testing things and hearing user reports. It's a mess, and you need to test everything, and you need to learn a lot about android and ios power management and message throttling and app states, and then you will be sure of nothing but *almost* sure about when messages or notifications will actually go through or not.

**Comment by mikehardy** [comment]
Oh, and be very very clear on the types of messages and how to send them, i.e. notification, data-only ("silent push"), mixed (has notification and data block) and how those work. The firebase web console only sends notification or mixed, it can't do data-only. For that you need to get a shell script going that uses the FCM REST API and then you can play with the different app states. etc.

This is not a mistake in the documentation I don't think, so I'm going to close it

**Comment by shamilovtim** [comment]
Appreciate you elucidating what was meant by the docs! This was alarming to read and knowing that this is what the docs were referring to clarifies what was meant by it. As a matter of principle we all know the Chinese OEMs (+Samsung) are violating Google's Android guidelines. We should probably as third party developers be protesting this and raising a call to action, rather than enshrining it as the norm in our OSS or upstream docs. The Android operating system as designed and intended fully intends you to receive push notifications if an app is closed. OnePlus's custom version of Android which violates those guidelines shouldn't be misconstrued as the norm. It would be nice if the docs called this out, and identified this as a 50/50 issue rather than acquiescing / normalizing the OEMs abusing us third party developers.

**Comment by mikehardy** [comment]
The AOSP team is already on record (via a reddit A2A) as taking the violation of power management APIs and guarantees seriously and they assert they have added compatibility testing in these areas to the Compatibility Test Suite, effective (I think?) with Android 12
