### ISSUE TITLE
[🐛] crashlytics().recordError doesn't seem to work in iOS

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#5258]
## Issue
I implemented crashlytics into my ios app and tested everything by calling `crashlytics().crash()` method. I latter saw that report in my firebase dashboard correctly. I then proceeded to implement `crashlytics().reportError()` method in my error handling methods (example below)

```ts
try {
 // Some code that can throw and error
} catch (error) {
    if (error instanceof Error) {
      crashlytics().recordError(error, 'api error');
    } else if (error instanceof Object) {
      crashlytics().recordError(new Error(JSON.stringify(error)), 'api error');
    }
}
```

However, even after a full day, I am not seeing these error reports in crashlytics dashboard. To my understanding they should be there? Is this a possible bug in iOS perhaps?

---

#### `package.json`:

```json
    "@react-native-firebase/analytics": "11.4.1",
    "@react-native-firebase/app": "11.4.1",
    "@react-native-firebase/crashlytics": "11.4.1",
    "@react-native-firebase/dynamic-links": "11.4.1",
    "@react-native-firebase/messaging": "11.4.1"
```

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# Everything handled through auto linking
```

#### `AppDelegate.m`:

```objc
// N/A
```
---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 295.78 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 30
      Build Tools: 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `11.4.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `crashlytics`
- **Are you using `TypeScript`?**
  - `Y` & `4.2.4`

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hey @IljaDaderko ! :wave: 

I was just all over this area in #5047 so it's possible I've broken something and this would be the prompt to fix it.
However, as part of that PR I also added a bunch of positive-confirmation and informational logging related to crashlytics

Have you examined the output of either logcat or Xcode console during app boot and when you call recordError ? It could be informative - especially in combo with the related keys from firebase.json which wasn't included in the report

**Comment by IljaDaderko** [comment]
I'm not using `firebase.json` anywhere, so probably not related. Will have a look at xcode logs tomorrow to see if anything is logged there or not and add output here 👍

**Comment by mikehardy** [comment]
it might be related, check this for context https://invertase.io/blog/react-native-firebase-crashlytics-configuration - no logging in debug by default so it could have been shunted off as a report ?

**Comment by mikehardy** [comment]
but also of course I may have just broken something :sweat_smile:

**Comment by IljaDaderko** [comment]
Ok, without that firebase.json config crashlytics were disabled. When I added it in everything worked 👍 Perhaps it should be specified / made required in documentation?

My issue is solved, so I'll close it, but feel free to reopen if needed.

**Comment by mikehardy** [comment]
Well, it is optional to have a firebase.json, and crashes in debug are disabled by default (which is documented) and crashlytics is now quite explicit in the logs...but this is clearly the most important part of crashlytics integration - the testing etc, which is why I went to the trouble of making a whole boring blog post :laughing: 

I'll re-open this and put something, somewhere, in the docs - maybe just a link to the blog post with a comment to check the native logs while integrating and that all control is in firebase.json with a link to the schema...

Glad it's working for you! Was a bit worried there, the new javascript-level fatal feature introduced risk of breakage
