### ISSUE TITLE
Android React-native ERROR: No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()

### ISSUE THREAD

**Issue by ravi123saxena** [invertase/react-native-firebase#5259]
Hi All,

I am using below library for firebase:

    "@react-native-firebase/app": "^11.4.1",
    "@react-native-firebase/messaging": "^11.4.1",
    "react": "17.0.1",
    "react-native": "0.64.0",

I am keep getting error "No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()"

Note: Android not working while iOS doesn't have the same issue.

Please anybody provide the solution asap. 

Thank you.

**Comment by mikehardy** [comment]
There are many issues related in the repo that may help, but you ignored the issue template which asks for important troubleshooting information so this won't receive attention.

You may like https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh to creates a react-native-firebase app that works out of the box, with comments on all integration steps.
