### ISSUE TITLE
[🐛] isHeadless is undefined - iOS

### ISSUE THREAD

**Issue by er1cAk** [invertase/react-native-firebase#5260]
## Issue

I implemented messaging module and I facing with issue about headless run. Property isHeadless is always undefined in [index.js
](https://gist.github.com/er1cAk/afac3e6e306909cdadf4c37d23c0655e) (HeadlesCheck). I changed launchOptions in the AppDelegate. I followed your documentation but I think she is not updated for RN autolinking/newer versions?

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

[Podfile](https://gist.github.com/er1cAk/2adf52d93e0300ea200c3dc43154730e) 

#### `AppDelegate.m`:

[AppDelegate](https://gist.github.com/er1cAk/884dd115f5bb2b6e111e299cdca3acc7#file-appdelegate-m-L54)

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `11.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `messaging`
- **Are you using `TypeScript`?**
  - `Y` & `4.0.0`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Empty issue template, sorry, we close those immediately.
