### ISSUE TITLE
🔥 [🐛] firestore/unavailable error - root cause: token issue, needs docs

### ISSUE THREAD

**Issue by cookt** [invertase/react-native-firebase#5264]
## Issue

For context, I am using the EmailAuthProvider to signIn users and cloud messaging for push notifications using the modules from this repo. However, when I attempt to connect to my firestore, I get errors like the ones seen in #4736, #2887, and #3867. 

Specifically, `.onSnapshot` always returns undefined data and `.get` throws the firebase unavailable error.  This occurs while running on a real device as well as on an emulator. This was not behind any firewall or VPN.

After looking in to adb logs, I did find this entry:
`Firestore: (22.1.2) [WatchStream]: (fe51fe0) Stream closed with status: Status{code=UNAUTHENTICATED, description=Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project., cause=null}` 

Interestingly or not, when I switch the firestore module for the one provided by the JS SDK (leaving the auth module from this repo in place), firestore connects without issue.

#
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/app": "^11.3.3",
    "@react-native-firebase/auth": "^11.3.3",
    "@react-native-firebase/firestore": "^11.3.3",
    "@react-native-firebase/messaging": "^11.3.3",
```

#### `firebase.json` for react-native-firebase v6:

```json
   I have not created a firebase.json to override any defaults
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 54.13 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.0.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.10.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/local/opt/openjdk/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [] iOS
  - [] Android
  - [] **iOS** but have not tested behavior on Android
  - [] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 6 ?
- **`Firebase` module(s) you're using that has the issue:**
  - Firestore
- **Are you using `TypeScript`?**
  - Y 4.0.0

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
This rhymes with something vague but important - I *think* what has happened is automatic auth token refresh has failed, and firestore is attempting to re-use the auth token, and it percolates up in this inscrutable way.

And the issue I'm vaguely remembering traced it to the exact (some google API not enabled - maybe the devicecheck one but I think it was different) and once they went on GCP console and enabled the API, auth token auto-refresh worked and firestore worked.

Found it! https://github.com/invertase/react-native-firebase/issues/4923

https://github.com/invertase/react-native-firebase/issues/4923#issuecomment-814237644

> Token Service API has not been used in project xxxyyyzzz before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/securetoken.googleapis.com/overview?project=xxxyyyzzz then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.


Give that a try and please report back

**Comment by cookt** [comment]
Thanks you for the response. I did end up ruling out the Token Service API issue.  It turned out that our backend was adding a custom claim to the token named `scope`. This apparently interfered with that auth token refresh mechanism somewhere.  Changing `scope` -> `scopes` ended up fixing it. Hopefully this helps someone else.

**Comment by mikehardy** [comment]
Very interesting - really happy you nailed that, it is subtle! I'm going to keep this open and think about how to add some documentation around it. This is semi-frequent, and way too subtle to expect someone would relate firestore/unavailable with "my token refresh is broken somehow". Thanks for reporting back

**Comment by codal-mpawar** [comment]
Hey guys.
I am facing issue with **let fcmToken = await messaging().getToken();** Don't know what is wrong in that or what's other issue please help me.....

**Comment by mikehardy** [comment]
@codal-mpawar I'm guessing your issue is completely unrelated. You were probably bitten by the react-native-push-notifications-did-not-pin-their-dependency issue and need react-native-push-notifications 7.3.1

**Comment by mushtaque87** [comment]
@mikehardy Can you explain what do you mean .. I am also getting a crash in line let fcmToken = await messaging().getToken() our android app.. Can you tell me what needs to be done. i have started seeing this from a day or two.. Its urgent..

**Comment by mikehardy** [comment]
I have explained as much as I can in comments here and in linked issues

**Comment by mikehardy** [comment]
@mushtaque87 your issue is unrelated, and responded to thoroughly in closed issues, including the one you just opened and I responded to. Please search issues lists prior to creating notifications for everyone with comments, thank you

**Comment by gauthampait** [comment]
I am using the latest version of the library and the Disabling/Enabling Token Service API doesn't fix the issue all together. 
The error popup again. 

My main concern is, this is happening on the production apps :(

**Comment by mushtaque87** [comment]
We also have to add this line 

    implementation 'com.google.firebase:firebase-analytics:17.3.0'
    
    in app/build.gradle

**Comment by mikehardy** [comment]
@mushtaque87 not recommended at all. Do not do that.

If you need analytics you should install `@react-native-firebase/analytics` package, why? Because those versions are dependent / move with the rest of firebase and the only way you know you get a well-tested matched set is if you use our package where we, depend on the firebase bill-of-materials as a unit to get a matched set. If you don't do that everything will seem fine now then later you'll get something like #5293 

For iOS if you want analytics but do not want the IDFA symbols used (triggering need for Application Tracking Transparency) use the special toggle documented in analytics docs in your Podfile that switches to a non-IDFA library

Cheers

**Comment by AndrewMorsillo** [comment]
Oddly this seems to happen (firestore/unavailable) immediately after the user signs up with Google on my app. I've never seen it with a Facebook or email signup. They sign up successfully but when I go to create their initial data firestore fails with `firestore/unavailable`. I'm trying to reproduce locally now to see if it is this token issue. If so maybe there's some interaction between `@react-native-google-signin/google-signin` and `@react-native-firebase/firestore`?

**Comment by mikehardy** [comment]
Hmm - I use both of those in conjunction as well @AndrewMorsillo and have not noticed it myself but my sample size is small. I'll be on the lookout but I'm 99% that if it is that interaction you'll beat me to the diagnosis. Very curious though and happy to help if there is something we're doing here but this will likely turn into an underlying problem and need a quickstart example from either firebase-android-sdk or firebase-ios-sdk
