### ISSUE TITLE
How to use setBadge and getBadge with new firebase API ('@react-native-firebase/messaging' && '@react-native-firebase/app')[🐛] Bug Report Title - CHANGE ME 

### ISSUE THREAD

**Issue by ravi123saxena** [invertase/react-native-firebase#5268]
Hi ,

I am stuck on updating badge in new firebase API . Please Provide the code to set and get badge.

"@react-native-firebase/app": "^11.4.1",
"@react-native-firebase/messaging": "^11.4.1",

**Comment by mikehardy** [comment]
Badging is not supported and will not be supported, sorry. As a design feature it is discouraged completely in Android at the platform level, and fighting that is a losing proposition. All the Android badging is done via vendor-specific APIs which is unmaintainable and unsupportable - you can see the underlying library react-native-firebase was using gave up and is unmaintained now https://github.com/leolin310148/ShortcutBadger

on iOS it is possible but you must integrate a separate full-featured notification library https://duckduckgo.com/?q=badging+ios+app+react-native
