### ISSUE TITLE
[🐛] After upgrade library & react-native. LogEvent not working properly.

### ISSUE THREAD

**Issue by maoryadin** [invertase/react-native-firebase#5283]
## Issue

I have issue after upgrade to:
` @react-native-firebase/analytics": "^11.3.3" .
`
i am using the logEvent to send events of completed action:
`await analytics().logEvent('userCompletedServiceCall');`

``

Describe your issue here

After the event is execute, i am not getting it in my google ad campaign.
There is some issue with the LogEvent?
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```

  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.4",
    "@react-native-community/datetimepicker": "^3.4.7",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-firebase/analytics": "^11.3.3",
    "@react-native-firebase/app": "^11.3.3",
    "@react-native-firebase/auth": "^11.3.3",
    "@react-native-firebase/firestore": "^11.3.3",
    "axios": "^0.21.1",
    "geolocator": "^2.1.5",
    "i18next": "^20.2.1",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.28",
    "patch-package": "^6.3.1",
    "prop-types": "^15.7.2",
    "react": "17.0.2",
    "react-i18next": "^11.8.12",
    "react-native": "0.64.0",
    "react-native-animatable": "^1.3.3",
    "react-native-appsflyer": "^6.0.30",
    "react-native-aws3": "^0.0.9",
    "react-native-collapsible": "^1.5.1",
    "react-native-confirmation-code-field": "^6.5.1",
    "react-native-datepicker": "^1.7.2",
    "react-native-dotenv": "^2.4.3",
    "react-native-drawer": "^2.5.1",
    "react-native-fbsdk-next": "^4.1.0",
    "react-native-gesture-handler": "^1.5.6",
    "react-native-image-picker": "^3.2.1",
    "react-native-locale-detector": "^1.0.1",
    "react-native-localize": "^2.0.2",
    "react-native-material-textfield": "^0.16.1",
    "react-native-modal": "^11.5.3",
    "react-native-modalbox": "^2.0.0",
    "react-native-phone-input": "^0.2.4",
    "react-native-reanimated": "^1.7.0",
    "react-native-router-flux": "^4.3.1",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^2.0.0-alpha.33",
    "react-native-share": "^3.0.0",
    "react-native-swiper": "^1.6.0-nightly.5",
    "react-native-webview": "^11.4.3",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.9",
    "redux-thunk": "^2.3.0",
    "remote-redux-devtools": "^0.5.16"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-devtools": "^4.12.4",
    "react-test-renderer": "17.0.1"
  },
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
  package="com.sinapis.gpage">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.SET_DEBUG_APP" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:usesCleartextTraffic="true" tools:targetApi="28"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <meta-data android:name="com.facebook.sdk.ApplicationId"
                 android:value="@string/facebook_app_id"/>

    </application>

</manifest>

```
```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```
```
System:
    OS: Windows 10 10.0.21359
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
    Memory: 18.70 GB / 31.79 GB
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: 21.3.6528147
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: 16.7.30517.126 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_262
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.64.0 => 0.64.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
` 11.3.3
`- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  N

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Just curious, why stop at 11.3.x? Why not 11.4.1? 

You skipped big parts of the template and don't indicate what platform you have issues on, so I will close this as it's not complete, and I can only guess.

You'll want to follow the upstream documentation that shows how to turn on analytics debugging and I recommend using android as your test system, then watch `adb logcat` to see analytics is working - https://firebase.google.com/docs/analytics/debugview

There's no problem with the module we're aware of, this will likely be project specific

**Comment by maoryadin** [comment]
> Just curious, why stop at 11.3.x? Why not 11.4.1?
> 
> You skipped big parts of the template and don't indicate what platform you have issues on, so I will close this as it's not complete, and I can only guess.
> 
> You'll want to follow the upstream documentation that shows how to turn on analytics debugging and I recommend using android as your test system, then watch `adb logcat` to see analytics is working - https://firebase.google.com/docs/analytics/debugview
> 
> There's no problem with the module we're aware of, this will likely be project specific

When my app has been release to play store there was only 11.3.3 version.
my platform is android.

i will check on new version and will update :)

**Comment by mikehardy** [comment]
That makes sense - just want to make sure you get all the latest bug fixes - for the avoidance of doubt I do not think the upgrade will fix your particular issue, but I *do* think the android `adb logcat` while set for analytics debugging will be very informative

**Comment by maoryadin** [comment]
> That makes sense - just want to make sure you get all the latest bug fixes - for the avoidance of doubt I do not think the upgrade will fix your particular issue, but I _do_ think the android `adb logcat` while set for analytics debugging will be very informative

btw i am just logging some info and i am getting:

`05-09 18:19:35.760 E/FA      (11194): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI`

I may think its related to that does it make sense? even that my google_app_id is not changed or removed.
where this attribute should be init?

**Comment by mikehardy** [comment]
You have not mentioned what version you upgraded from, but what I suspect is you upgraded from one of the older v7 or v8 react-native-firebase versions, this will likely be resolved if you fetch a new set of project configuration files from the firebase web console for your app(s) - google-services.json / GoogleService-Info.plist

**Comment by maoryadin** [comment]
i was missing this line on build.gradle:
`apply plugin: 'com.google.gms.google-services'
`
i think it solved the problem .

**Comment by mikehardy** [comment]
Great to hear your problem is solved - that file is definitely needed in order for the system to have your app id
