### ISSUE TITLE
🤷‍♂️  How to open the browser with a link when tapping on a notification?

### ISSUE THREAD

**Issue by fabyeah** [invertase/react-native-firebase#5285]
When the user taps on the notification, I want to open the browser with a specific link, instead of opening the app. I think FCM has `onNotificationOpened` for this. But `@react-native-firebase/messaging` only offers `onNotificationOpenedApp` which triggers when the app is opened as response to tapping on the notification. So this isn't possible with this package, is that correct? So I need to use a different package, like Notifee?

**Comment by mikehardy** [comment]
If you want to do anything with notifications other than have a basic hook to your application, you should integrate a full-featured on-device notification API handler, like notifee yes. At the same time, for this use case I imagine you could implement react-native Linking to then open a browser ? This is an API usage question vs something with this module though - it will not result in a change to the module so I'm going to close this - at the same time, hopefully this helps. Cheers

**Comment by mikehardy** [comment]
I'm not sure how to handle this use case either but if you ask on the notifee repo you might get a good answer and we can all learn something :nerd_face:
