### ISSUE TITLE
[🐛] admob_delay_app_measurement_init wrongly typed in json schema

### ISSUE THREAD

**Issue by DoctorJohn** [invertase/react-native-firebase#5295]
## Issue

I used `"$schema":"./node_modules/@react-native-firebase/app/firebase-schema.json"` in my `firebase.json` file to use the editor Intellisense. Doing so I noticed that `admob_delay_app_measurement_init` is [expected to be a string](https://github.com/invertase/react-native-firebase/blob/50a384f2a2ba61d078521e89594f4e576f1e1f46/packages/app/firebase-schema.json#L18). However docs and code tell [a different story](https://github.com/invertase/react-native-firebase/blob/50a384f2a2ba61d078521e89594f4e576f1e1f46/tests/firebase.json#L5). Am I missing something?

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "$schema":"./node_modules/@react-native-firebase/app/firebase-schema.json",
  "react-native": {
    "admob_delay_app_measurement_init": true
  }
}

```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `11.4.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `admob, app`
- **Are you using `TypeScript`?**
  - `Y` & `4.2.4`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Looks like it should be a boolean - yes - does that work for you locally? Seems it should

#5297 to resolve - thanks for noticing this and reporting it, much appreciated

**Comment by DoctorJohn** [comment]
It appears to be working for me with a boolean.

**Comment by mikehardy** [comment]
Major ecosystem earthquakes rumbling through firebase-land at the moment with breaking changes in the underlying native SDKs so I can't promise when this will be released - it might be in an hour or it might be a few days, so safest bet might be to use patch-package to resolve this locally just for now - it's quick and painless if you've never used it before, I use it everywhere for items like this

**Comment by DoctorJohn** [comment]
Thanks for the tip, I did not know about patch-package before!

**Comment by mikehardy** [comment]
I hold patch-package in such high regard I made a workflow just to generate patches in it's format in our CI for PRs :-) - helps close the loop for submitters / interested testers since otherwise it's hard for interested parties to check results for a monorepo setup like react-native-firebase, and will only get worse as a typescript conversion is in the future meaning there will be a compile step as well - for instance check the artifact here on the linked PR

 https://github.com/invertase/react-native-firebase/actions/runs/835852849

It accrues all the unreleased changes on main branch + plus the PR since last release.

**Comment by DoctorJohn** [comment]
This is pretty awesome! I already was concerned that sooner or later I would have to build custom versions locally and make them available via a private registry. Thanks again for letting me know

**Comment by mikehardy** [comment]
Yeah - I hadn't thought of it, but I suppose even if you proposed something that was critical for you but not for us you could post a PR and get a patch set :laughing: - you can see we'll merge just about anything sensible though. If you ever want to do development on the native stuff here to bend it to your will, the tests app in the repo (and it's README) will get you going pretty quickly. It's surprisingly less painful than I thought it would be, when I started.
