### ISSUE TITLE
A bunch of documentation is not formatted with prettier

### ISSUE THREAD

**Issue by DoctorJohn** [invertase/react-native-firebase#5301]
While authoring #5298 I noticed that a bunch of `docs/*` files were not formatted using `yarn format:markdown`. To prevent this in the future we might want to add a `lint:markdown` script and run it in the `docs` workflow. Note that this would require the docs workflow to setup yarn and install prettier which makes that workflow more complex.

I'll propose a PR in a moment. Feel free to close it if this appears unnecessary.

**Comment by mikehardy** [comment]
a PR with the actual formatting changes here plus turning on a check in CI would be nice yes!

**Comment by DoctorJohn** [comment]
I somehow misread your comment and ended up creating two PRs instead of one.
