### ISSUE TITLE
Android onAuthStateChanged behavior does not match iOS and web

### ISSUE THREAD

**Issue by esamelson** [invertase/react-native-firebase#531]
### Issue

I'm trying to use `firebase.auth().onAuthStateChanged()` to determine when a user's authentication has expired in the middle of using my app. The correct behavior according to Firebase's own JS SDK (which is replicated correctly for iOS in RNFirebase) is that as soon as authentication is no longer valid, the callback passed to `onAuthStateChanged` is called with `null` as its only parameter. On Android, however, the callback is simply never called. The user must close and restart the app to get the callback called with `null`.

Steps to replicate:
1. Sign in on Android using `signInWithEmailAndPassword`
2. Change Firebase password for that account
3. Wait 60 mins for token to expire and auth to become invalid

Expected behavior (correct on iOS):
Callback previously passed to `onAuthStateChanged` is called with `null`

Actual behavior on Android:
`onAuthStateChanged` callback is not called. Instead, all database connections that require auth simply stop returning snapshots.

### Environment

1. Application Target Platform: Android

2. Development Operating System: macOS Sierra

3. Build Tools: Android Studio 2.3.3, Firebase Android SDK 11.4.2

4. React Native version: 0.48.2

5. RNFirebase Version: 3.0.4

6. Firebase Module: auth

**Comment by chrisbianca** [comment]
@esamelson Interesting scenario. Are you able to help us out by putting a break point in `RNFirebaseAuth.java` on line 88, i.e. inside the `onAuthStateChanged` listener:

```
FirebaseAuth.AuthStateListener newAuthListener = new FirebaseAuth.AuthStateListener() {
        @Override
        public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
          FirebaseUser user = firebaseAuth.getCurrentUser(); // ADD BREAKPOINT HERE
          WritableMap msgMap = Arguments.createMap();
          if (user != null) {
            msgMap.putBoolean("authenticated", true);
            msgMap.putString("appName", appName); // for js side distribution
            msgMap.putMap("user", firebaseUserToMap(user));
            Utils.sendEvent(mReactContext, "auth_state_changed", msgMap);
          } else {
            msgMap.putString("appName", appName); // for js side distribution
            msgMap.putBoolean("authenticated", false);
            Utils.sendEvent(mReactContext, "auth_state_changed", msgMap);
          }
        }
      };
```

This will tell us whether it's a Firebase SDK issue or something wrong with RNFirebase.

**Comment by esamelson** [comment]
I may be able to do this in a little while

**Comment by esamelson** [comment]
I can't do this right now, but I should be able to get to it sometime in the next few days.

**Comment by chrisbianca** [comment]
Great, no rush!

**Comment by Ehesp** [comment]
@esamelson did you manage to check this out?

**Comment by chrisbianca** [comment]
@esamelson I tried this out on Friday by doing the following:

1) Logging the user in
2) Changing their password through the console
3) Waiting for `onAuthStateChanged` to fire on both iOS and Android by adding breakpoints in the native code.

Several hours later and it still hadn't fired.

I then repeated by deleting the user from the console rather than changing their password, and the same happened - no update by `onAuthStateChanged` at all.

This does seem like it's a Firebase issue, though I'm interested in the fact that you saw iOS update.  How did you change the user's password?

**Comment by esamelson** [comment]
@chrisbianca - sorry I wasn't able to get to this as quickly as I'd hoped. Interesting to hear that you weren't able to reproduce the behavior I saw on iOS. I consistently saw `onAuthStateChanged` fire with a null value after about an hour, on both iOS and web (JS SDK). I was changing the password programmatically by using the web SDK's `user.updatePassword` method on my own webpage (separate from the app I was testing).

**Comment by cjpete** [comment]
I'm seeing this on iOS, whilst using `react-native-firebase` version `5.5.4`.
