### ISSUE TITLE
[🐛] messaging().getToken() crashes in Android. Works fine in IOS. 

### ISSUE THREAD

**Issue by mushtaque87** [invertase/react-native-firebase#5311]
## Issue

 I am also getting a crash in line let fcmToken = await messaging().getToken() our android app.. Can you tell me what needs to be done. I have started seeing this from a day or two.. Its urgent.. 
 
 I upgraded firebase to 11.5.0 from 11.0 and still it exist. 

import messaging from "@react-native-firebase/messaging";

 private static async getToken() {
    let fcmToken = await PushNotification.storage.getFMCToken();
    console.log('getFMCToken',fcmToken);

    if (!fcmToken) {
      try {
        fcmToken = await messaging().getToken();
        console.log('fcmToken getToken',fcmToken);
        if (fcmToken) {
          PushNotification.storage.saveFMCToken(fcmToken);
          return fcmToken;
        } else {
          console.log(`fcmToken error ${fcmToken}`);
          log.error(
              "getToken",
              new Error(`messaging().getToken(): ${fcmToken}`)
          );
        }
      } catch (e) {
        log.error(
            "getToken",
            new Error(`messaging().getToken(): ${fcmToken}`));
      }
    }

    return fcmToken;
  }

Describe your issue here
The app crashes when messaging.getToken() is called.
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

   "@react-native-firebase/analytics": "^11.4.1",
    "@react-native-firebase/app": "^11.4.1",
    "@react-native-firebase/app-types": "^6.7.2",
    "@react-native-firebase/messaging": "^11.4.1",
    "@react-native-firebase/perf": "^11.4.1",

### Android

- [x] my application is an AndroidX application : YES
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

android.useAndroidX=true
android.enableJetifier=true
# Allocating more memory
org.gradle.jvmargs=-Xmx1536m

#### `android/build.gradle`:
android.useAndroidX=true
android.enableJetifier=true
# Allocating more memory
org.gradle.jvmargs=-Xmx1536m

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="XYZ">
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"  />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"  />
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"  />
    <uses-permission android:name="android.permission.READ_PROFILE" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />
    <uses-permission android:name="android.permission.USE_FINGERPRINT" />
    <uses-permission android:name="com.precisebiometrics.android.mtk.manager.permission.BIOMETRIC_DATA" />
    <application
      tools:replace="android:label, android:allowBackup"
      android:name=".MainApplication"
      android:label="@string/${appNameKey}"
      android:icon="${appIcon}"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
      android:supportsRtl="true"
      tools:targetApi="p"
      android:usesCleartextTraffic="true">
      <meta-data
        android:name="com.google.android.geo.API_KEY"
        android:value="${googleMapApiKey}"/>
      <meta-data
        android:name="com.google.firebase.messaging.default_notification_icon"
        android:resource="${icon}" />
      <meta-data
        android:name="com.google.firebase.messaging.default_notification_color"
        tools:replace="android:resource"
        android:resource="@color/petrol" />
      
      <meta-data android:name="io.branch.sdk.BranchKey" android:value="@string/branch_io_live_key" />
      <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="@string/branch_io_test_key" />
      <meta-data android:name="io.branch.sdk.TestMode" android:value="${isBranchTest}" /> 
      <activity
        android:name=".MainActivity"
        android:launchMode="singleTask"
        android:label="@string/${appNameKey}"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|smallestScreenSize|screenLayout"
        android:windowSoftInputMode="adjustPan"
        android:resizeableActivity="true"
        android:supportsPictureInPicture="true"
        android:screenOrientation="portrait">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <intent-filter android:autoVerify="true">
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" android:host="pyypl.com" android:pathPrefix="/accept-tos" />
        </intent-filter>
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="pyypl${applicationIdSuffix}" android:host="transactions" />
        </intent-filter>
        
        <intent-filter>
            <data android:scheme="pyypl${applicationIdSuffix}" />
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
        </intent-filter>
        
        <intent-filter android:autoVerify="true">
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" android:host="pyypl.test-app.link" />
            <data android:scheme="https" android:host="pyypl-alternate.test-app.link" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <provider
        tools:replace="android:authorities"
        android:name="androidx.core.content.FileProvider"
        android:authorities="${applicationId}.provider"
        android:exported="false"
        android:grantUriPermissions="true">
        <meta-data
            tools:replace="android:resource"
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/freshchat_file_provider_paths" />
      </provider>
      
      <receiver android:name="io.branch.referral.InstallListener" android:exported="true">
          <intent-filter>
              <action android:name="com.android.vending.INSTALL_REFERRER" />
          </intent-filter>
      </receiver>
    </application>
</manifest>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  -  11.0 , 11.4.1 and 11.5.0
- **`Firebase` module(s) you're using that has the issue:**
  - 
- **Are you using `TypeScript`?**
  - YES

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Copied from another issue

----

does no one search issues lists before posting ? :thinking:  :sweat_smile: 

There are **7** of you here! That's a lot of people performing no cursory search. Fascinating, and very expensive in terms of your time here and my time.

Duplicate list: #5300, #5299 #5296 #5293

Root cause is in react-native-push-notifications. Update to 7.3.1 over there https://github.com/zo0r/react-native-push-notification/issues/1992#issuecomment-839995036

Technical explanation here https://github.com/invertase/react-native-firebase/issues/5293#issuecomment-839918527

**Comment by efstathiosntonas** [comment]
@mikehardy looks like everyone works on same company and get in here guns blazing to get an immediate fix!! Haha

j/k ofcourse

**Comment by HerickRaposo** [comment]
Thee yers after and i have same issue here
