### ISSUE TITLE
[🐛] Firebase Auth - Sign in with phone number slow

### ISSUE THREAD

**Issue by zhahaoyu** [invertase/react-native-firebase#5316]
## Issue

I was trying to sign in with phone number using 

```auth().signInWithPhoneNumber(phoneNumber, forceResend)```

On average, this method takes 7-10 seconds to resolve on ios. (Similar amount of time to receive the sms)

My guess is that Firebase needs to send a Silent APNs notification to the device first before sending the actual sms message. Is there a way to call this method separately ahead of time, so the actual SMS waiting time becomes shorter.

**Comment by mikehardy** [comment]
Hi there! This will be an upstream issue I think - I would check either on stackoverflow (where the firebase team participates) or on firebase-ios-sdk, there is nothing special react-native-firebase is doing on top of the native APIs there, and those will be the authoritative places for information. If they ask for a reproduction (sometimes they do), they're quickstarts are very easy to set up https://github.com/firebase/quickstart-ios/tree/master/authentication

**Comment by dqii** [comment]
@zhahaoyu I'm having the same issue --- did you ever figure out the cause or a solution?

**Comment by aashish-jumbohomes** [comment]
Still experiencing the same issue.
