### ISSUE TITLE
Remove listener in reverse order on the same path does not work properly

### ISSUE THREAD

**Issue by omer88** [invertase/react-native-firebase#532]
### Issue
When trying to remove listeners of the same path in the opposite order to their creation - the second listener won't be remove, but only after the first one will be.
I experienced it with child events, but it's probably not limited to them.

**Steps to reproduce:**
firebase .database().ref('refX').on('child_added', callback1)
firebase .database().ref('refX').on('child_added', callback2)
firebase .database().ref('refX').off('child_added', callback2)

**Expected behavior**
callback2 reference was removed and callback1 reference is till alive.

**Current behavior:**
both references are alive - callback2 reference was not removed.

**Note**
If you'll remove callback1 and then callback2 - everything should work fine.

**In addition:**  I've added 2 tests to the test project to demonstrate the issue - one passes and one fails. see my branch: 
https://github.com/rmrs/react-native-firebase/tree/multiple_listeners_issue

### Environment

1. Application Target Platform: Android

2. Development Operating System: Ubuntu 16.04

3. Build Tools: Android Studio 2.3.3, Firebase Android SDK 11.4.2

4. React Native version: 48.0 and also test project version

5. RNFirebase Version: latest master

6. Firebase Module: database

**Comment by Salakar** [comment]
@omer88 thanks for the issue report + tests, super helpful. Will debug this and get back to you.

**Comment by Salakar** [comment]
@omer88 thanks for this, have pushed up a fix, both your tests are passing now:

![image](https://user-images.githubusercontent.com/5347038/32139627-890e8d08-bc46-11e7-9e44-16f9397971fe.png)

**Comment by omer88** [comment]
Thank you, @Salakar ! :)
