### ISSUE TITLE
[🐛] Firebase not recognized price in items 

### ISSUE THREAD

**Issue by rukmanary** [invertase/react-native-firebase#5347]
## Issue

I already read this https://github.com/invertase/react-native-firebase/issues/5227 and see this #5232 so I upgraded my analytics to version 11.4.1. But, every time I send price, it gets an error:

`Error: firebase.analytics().logAddToCart(*): unknown property 'items'.`

I tested with this simple code:
```
firebase.analytics().logAddToCart(
{
        items: [
          {
            price: 2000,
          },
        ],
}
)
```

I checked struct.js, index.d.ts, and everything else, I confirm that price is defined. I also do rm -rf node modules, reinstall it, reset-cache, and clean gradle... But I still get this error. Why?

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```
 "react": "16.9.0",
 "react-native": "0.61.1",
 "@react-native-firebase/analytics": "^11.4.1",
 "@react-native-firebase/app": "^11.4.1",
 "@react-native-firebase/messaging": "^11.4.1",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `firebase v6`
- **`Firebase` module(s) you're using that has the issue:**
  - `analytics`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
We're on v12 now or at least v12.5
You skipped all the other parts of the template which results in immediate close, apologies.

Others had success with quirks here https://github.com/invertase/react-native-firebase/issues/4578

This must be something project specific, sorry

**Comment by rukmanary** [comment]
Sorry, but I don't understand... The price item is already defined here in node_modules/@react-native-firebase/analytics/lib/structs.js also in here node_modules/@react-native-firebase/analytics/lib/index.d.ts
![Screen Shot 2021-05-22 at 06 51 52](https://user-images.githubusercontent.com/36146615/119207941-565c9400-baca-11eb-9b02-cf1896790f3a.png)

but somehow I get this error:
![Screen Shot 2021-05-22 at 06 56 27](https://user-images.githubusercontent.com/36146615/119208085-d682f980-baca-11eb-87dd-99fb26dee20a.png)

I'm running the app with breakpoints now to debug it. I put breakpoints at node_modules/@react-native-firebase/app/lib/common/struct.js on `validateStruct` function. And in the `try` block `return struct(value);` this is what I got:
![Screen Shot 2021-05-22 at 07 37 24](https://user-images.githubusercontent.com/36146615/119209534-5744f400-bad1-11eb-807f-f7fb0a7407a2.png)

why there is no `price` in it? As I mention in the first screenshot, the price is right there.

Then I tried to run again from the start (refresh app) and debug it at `struct` function in node_modules/superstruct/lib/index.js and I got this:
![Screen Shot 2021-05-22 at 08 03 53](https://user-images.githubusercontent.com/36146615/119210313-c15f9800-bad5-11eb-87fc-934307d7814d.png)

At least can you help me explain why there's no price key in here? As you mention in https://github.com/invertase/react-native-firebase/pull/5232#issuecomment-829625323 this fix is already in version `11.4.1`. I confirm that price is defined at index.d.ts and node_modules/@react-native-firebase/analytics/lib/structs.js as I show in the screenshot above but why I didn't get the price key in schema? Please help 🙏

**Comment by mikehardy** [comment]
I can only assume the code executing is somehow not the code you are inspecting. That's intentionally vague because I don't know how that could happen but it's a hypothesis that fits the data.
`npx react-native-clean-project` perhaps.

**Comment by rukmanary** [comment]
Yes, It was cached in my machine. I start new project and it works well. Then I run this project again and everything is fine. I am sorry for creating this issue and thank you so much

**Comment by mikehardy** [comment]
If I had a dollar for every time I've had the same thing happen ;-). It's how I knew to suggest it, and I've personally contributed to `react-native-clean-project` because now it saves me every time, spread the news and help your fellow devlopers. Good luck with your project!
