### ISSUE TITLE
[📚] Unclear sentence on avoiding IDFA usage in analytics

### ISSUE THREAD

**Issue by draperunner** [invertase/react-native-firebase#5354]
## Documentation Feedback

The (incorrect) grammar of this sentence about disabling Ad Id usage makes it confusing:

> If avoiding the usage of IDFA is a requirement for your app, you must use firebase-ios-sdk 7.11.0 or greater, then you may define a variable in your Podfile like this:

I'm not sure what I _must_ do and what I _may_, or if there's a difference. Do I have to use at least v7.11.0 to be able to avoid IDFA usage? Or do I only have to set the variable IF I am using version >= 7.11.0 of firebase-ios-sdk? 🤔

Link to docs:
https://rnfirebase.io/analytics/usage#disable-ad-id-usage-on-ios

**Comment by mikehardy** [comment]
My grammar is overly complicated, sorry, my wife complains about it frequently when reading my written output ;-)

As a logical statement: 

**if** you need to avoid IDFA while still using analytics
**then** you need firebase-ios-sdk 7.11.0 or greater **and** to define the variable in your Podfile

Any clearer wording suggestions happily accepted - just hit that edit button on the top right of the page and propose it :pray:

**Comment by draperunner** [comment]
Ah, logical statements <3. Thanks for helping me understand. I have submitted a PR with a proposed change based on your answer. #5355
