### ISSUE TITLE
notification not arrive

### ISSUE THREAD

**Issue by davidg327** [invertase/react-native-firebase#5361]
Hi, for a few days I have problems receiving notification on ios, on android it works perfectly for me. I have the GoogleService-info.plist which is and if it is returning the token using the getToken () function, so I have the component where I make the call

async function requestUserPermission() {
    const authorizationStatus = await messaging().requestPermission();

    return (
        authorizationStatus === messaging.AuthorizationStatus.AUTHORIZED ||
        authorizationStatus === messaging.AuthorizationStatus.PROVISIONAL
    );
}

const FirebaseMessage = () => {

    const dispatch = useDispatch();

    useEffect(() => {
        const unsubscribe = messaging().onMessage(async remoteMessage => {
            Alert.alert('A new FCM message arrived!', JSON.stringify(remoteMessage));
        });

        return unsubscribe;
    }, []);

    const handleGetToken = () => {
        messaging()
            .getToken()
            .then(firebase => {
                console.log(firebase, 'firebase');
                dispatch(getTokenDevice(firebase));
            });
    };

    useEffect(() => {
        requestUserPermission().then(response => {
            if (response) {
                handleGetToken();
            }
        });

        messaging().onMessage(async remoteMessage => {
            console.log(remoteMessage, 'mensaje');
        });
    }, []);

    useEffect(() => {
        messaging().onNotificationOpenedApp(remoteMessage => {
            console.log(remoteMessage, 'mensaje');
        });
        messaging()
            .getInitialNotification()
            .then(remoteMessage => {
                if (remoteMessage) {
                    console.log(remoteMessage, 'mensaje');
                }
            });
    }, []);

    useEffect(() => {
        return messaging().onTokenRefresh(firebase => {
            console.log(firebase, 'firebase');
            dispatch(getTokenDevice(firebase));
        });
    }, []);

    return null;

}

the versions I have are the following

"react": "16.13.1",
"react-native": "0.63.4",
"@react-native-firebase/app": "^8.4.2",
 "@react-native-firebase/messaging": "^7.8.6",

I go back and repeat it is something that began to happen to me until recently, since this project takes a long time and when I integrated it the first time it was serving, I am testing it directly on an iPhone.

**Comment by mikehardy** [comment]
Update to current stable, we will not troubleshoot old versions
If you can still reproduce on current stable, open a new issue but next time please respect the issue template
