### ISSUE TITLE
Getting RNFBMessagingModule.getToken got 4 arguments, expected 2 error

### ISSUE THREAD

**Issue by akshaykatale99** [invertase/react-native-firebase#5379]
Getting RNFBMessagingModule.getToken got 4 arguments, expected 2 error while calling getToken method.

Here is my code:

    import messaging from '@react-native-firebase/messaging';
    .
    .
    .
    useEffect(() => {
            
            messaging()
            .getToken()
            .then(token => {
                console.log(token);
                setfcmToken(token);
            });
        }, []);

I am using follwing verions: 

"react-native": "~0.63.3"
"@react-native-firebase/app": "^12.0.0"
"@react-native-firebase/database": "^12.0.0"
"@react-native-firebase/messaging": "^12.0.0"

**Comment by mikehardy** [comment]
Please read the breaking changes list for the v12 release https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md

Those APIs are just a little bit different now

Here is how to follow this module so you can safely move along with us as we bump versions: https://invertase.io/blog/react-native-firebase-versioning

**Comment by rdtf1230** [comment]
@akshaykatale99 i was same with u 
but when i clean metro cache ( ex npm start -- --reset cache )
it works
I hope this helps

**Comment by mikehardy** [comment]
Even better! `npx react-native-clean-project` - when you run into really bizarre / unexpected problems that one will clean you right out, down to fixing corrupted cocoapods downloads even.

**Comment by linaia** [comment]
Please reopen : also got this with the following configuration

```
"react-native": "0.63.4"
"@react-native-firebase/analytics": "11.5.0",
"@react-native-firebase/app": "11.5.0",
"@react-native-firebase/messaging": "11.5.0",
```

I had to downgrade to 11.5 due to incompatibility with 12.x

**Comment by mikehardy** [comment]
@linaia there's no incompatibility with ios vs android - it works, it appears `npx react-native-clean-project` would probably help you, either way you may see in our e2e test suite that everything is up to date and working

**Comment by linaia** [comment]
@mikehardy I'll detailled you what was the problem with pod install in ios and why I had to rollback to 11.5.

**Comment by SaeedZhiany** [comment]
@akshaykatale99

did you manage to resolve the problem? I just upgrade fro `v11.5.0` to `12.9.3` and I got the error message. I read the changelog and it says that 

> Messaging.getToken/deleteToken: scoped token APIs removed from upstream APIs. Remove scopes from API calls. deleteToken() should work on iOS now.

what does it mean?

shouldn't we use the `getToken` on `messaging` anymore like below? how we should access it from this new version?

cc @mikehardy 

```
messaging()
        .getToken()
        .then(token => {
            console.log(token);
            setfcmToken(token);
        });
```

thanks

**Comment by mikehardy** [comment]
Hi @SaeedZhiany it means what it says :-) but I can elaborate a little - you may still use getToken and deleteToken (the APIs exist, and they work fine), you just cannot used *scoped* tokens. In the little snippet you include, you are not using a scoped token so that's fine, your usage appears fine. If you have an argument mis-match perhaps you just need to clear out your project build caching so that javascript and native code are in sync, I typically recommend `npx react-native-clean-project` for that. I would not go to 12.9.3 though, we're on 14.2.1 now I think? Good luck!

**Comment by SaeedZhiany** [comment]
> Hi @SaeedZhiany it means what it says :-) but I can elaborate a little - you may still use getToken and deleteToken (the APIs exist, and they work fine), you just cannot used *scoped* tokens. In the little snippet you include, you are not using a scoped token so that's fine, your usage appears fine. If you have an argument mis-match perhaps you just need to clear out your project build caching so that javascript and native code are in sync, I typically recommend `npx react-native-clean-project` for that. I would not go to 12.9.3 though, we're on 14.2.1 now I think? Good luck!

Ah, I didn't know what scoped tokens are. Thanks for clarifying. I need to support pre lolipop Android version so I have to stike with 12.x.x version. Thanks BTW

**Comment by mikehardy** [comment]
@SaeedZhiany  Note that the minSdkVersion should be 19 which is actually down to KitKat https://developer.android.com/reference/android/os/Build.VERSION_CODES#KITKAT I think I made a mistake and you can still go pre-lollipop if needed.

https://github.com/invertase/react-native-firebase/commit/f60afe158b2dc823bd7169e36c3e428470576c7e - documented as 19 but I put 21 in package.json. You might try changing `node_modules/@react-native-firebase/app/package.json` and setting minSdk to 19 (using patch-package to make it persistent) and it should build? The release notes indicate it *should* build https://firebase.google.com/support/release-notes/android#analytics_v20-0-0

If you test it and it works I can move it from 21 to 19, you can post a PR here and I can get that released really quickly

I do completely understand sometimes there are real reasons but even with a developing world userbase target, there were fewer than 1% active devices for me with SDK < 19

**Comment by SaeedZhiany** [comment]
>  Note that the minSdkVersion should be 19 which is actually down to KitKat https://developer.android.com/reference/android/os/Build.VERSION_CODES#KITKAT I think I made a mistake and you can still go pre-lollipop if needed.

Yeah I know that. but my project minSdk is 16 😄

> I do completely understand sometimes there are real reasons but even with a developing world userbase target, there were fewer than 1% active devices for me with SDK < 19

I completely agree, but my managers don't wanna upgrade yet and drop support for the old Android versions!

However I'll try what you said and will inform you if it's ok to downgrade minSdk to 19 to make RNFB compatible with more Android versions.

**Comment by SaeedZhiany** [comment]
@mikehardy 

here is my exact usage. I just realize that `getToken` didn't work at all. when I call my `getFCMTokenAndSendToServer` function only the `log 1` has been shown in the console. none of the other logs are shown. am I missing something in the v12.9.3? at least in v11.5.0 the `catch` method had been called. it seems `messaging().getToken()` does not do anything in this version. have you any idea what is not correct?

```tsx
private getFCMTokenAndSendToServer = () => {
  console.log('getFCMTokenAndSendToServer'); // log 1
  messaging().getToken()
    .then((fcmToken: string) => {
        if (fcmToken) {
          console.log('fcmToken', fcmToken); // log 2
          this.sendPushToken(fcmToken);
        } else {
          console.log('there is not fcmToken'); // log 3
          this.debouncedGetFCMTokenAndSendToServer();
        }
      },
    )
    .catch(console.log); // log 4
};
```

**Comment by SaeedZhiany** [comment]
@mikehardy 
I created the PR. please review it

https://github.com/invertase/react-native-firebase/pull/5984

**Comment by capsandoval01** [comment]
<img width="984" alt="Captura de Pantalla 2022-08-16 a la(s) 12 54 47 a m" src="https://user-images.githubusercontent.com/2879797/184807903-60261a15-f290-4a0c-9677-333bcd896823.png">


Hola, 

Me sucedió lo mismo por 2 días busque la **solución** hasta que la conseguí. después de actualizar a la versión 0.6.0,  tendrás problemas de cache , realiza la siguiente operación

1.
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

2.
sudo react-native run-android 


<img width="416" alt="Captura de Pantalla 2022-08-16 a la(s) 12 53 47 a m" src="https://user-images.githubusercontent.com/2879797/184807708-537893c0-dc41-4bc0-aeb9-4b9a185d3a6b.png">
