### ISSUE TITLE
iOS not working Admod Rewarded

### ISSUE THREAD

**Issue by GH974** [invertase/react-native-firebase#538]
### Issue

Hi, I use admod rewarded function and, try launch rewardedVideo, Xcode return error

Warning: Attempt to present <GADInterstitialViewController: 0x1588e3000>  on <UIViewController: 0x157d16080> which is already presenting <RCTModalHostViewController: 0x15c115630>

### Environment

1. Application Target Platform:  iOS

2. Development Operating System:  macOS Sierra

3. Build Tools: Xcode 9.0.1

4. React Native version: 0.48.3

5. RNFirebase Version: 3.0.3

6. Firebase Module: admob

**Comment by Ehesp** [comment]
Hello

Could you try pulling the branch https://github.com/invertase/react-native-firebase/tree/fix-497 and see if this resolves the issue?

**Comment by GH974** [comment]
OK, I test and come back later thanks

**Comment by GH974** [comment]
I tested this, and this bug is still present.
(I have a question, after npm install .....#fix-497, what else do I have to do)

**Comment by Ehesp** [comment]
I'll spin up the simulator and take a look.

**Comment by GH974** [comment]
After debug, I found new error

> Google Cannot find an ad network adapter with the name(s): com.google.ads.mediation.admob.AdMobAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.

**Comment by Ehesp** [comment]
Maybe related https://github.com/invertase/react-native-firebase/pull/615

**Comment by nielsmadan** [comment]
I have the same problem and the workaround is not pretty (close modal, show ad, re-open modal).

A real fix would be great.
