### ISSUE TITLE
[🐛] Bug Report Title - CHANGE ME 

### ISSUE THREAD

**Issue by harensarma** [invertase/react-native-firebase#5387]
Getting this error when generating a signed apk using android studio:

/Users/mypc/Apps/Reyna/node_modules/@react-native-firebase/app/android/build/intermediates/aar_metadata/release/aar-metadata.properties (No such file or directory)

**Comment by Ehesp** [comment]
Hello, please fill out the issue template (& title) so we can help you. Otherwise we have no idea what versions you're on.
