### ISSUE TITLE
🔥 [🐛] isHeadless flag on iOS unreliable

### ISSUE THREAD

**Issue by helenaford** [invertase/react-native-firebase#5388]
The issue is that the `isHeadless` flag included in `@react-native-firebase/messaging` is unreliable and causes the app to render `null` when the app is opened.  The flag can be true initially when the app is launching but does not update to false when the app is in the foreground.

Please see this code snippet which is taken from the [docs](https://rnfirebase.io/messaging/usage#background-application-state):
```
// index.js
import { AppRegistry } from 'react-native';
import messaging from '@react-native-firebase/messaging';

messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('Message handled in the background!', remoteMessage);
});

function HeadlessCheck({ isHeadless }) {
  if (isHeadless) {
    // App has been launched in the background by iOS, ignore
    return null;
  }

  return <App />;
}

function App() {
  // Your application
}

AppRegistry.registerComponent('app', () => HeadlessCheck);
```

There have been previous discussions around the usage of this flag:
https://github.com/invertase/react-native-firebase/issues/4163
https://github.com/invertase/react-native-firebase/pull/4304

Some suggestions to listen to `AppState` rather than use the `isHeadless` flag but it's unclear what the best solution is to prevent the app from rendering when it's in a headless state.

From reading the discussions, it's clear the `isHeadless` flag causes unpredictable results, is there anything that can be done in the library to fix the flag?

Or, can the docs be updated to show a recommended solution?

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    ...
    if ([FIRApp defaultApp] == nil) {
        [FIRApp configure];
    }
    ...

    NSDictionary *appProperties = [RNFBMessagingModule addCustomPropsToUserProps:nil withLaunchOptions:launchOptions];

    RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                     moduleName:@"xxx"
                                              initialProperties:appProperties];

    ...

    [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];

    return YES;
}
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID` Messaging
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION` Y

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by miallo** [comment]
Is there a place where I can look into this thing and see if I can find the problem? This bug is causing us quite some troubles...

**Comment by mikehardy** [comment]
This is an area of some pain that I've looked into a bit yes. We use detox as our testing solution in the e2e app and unfortunately it does not allow for running on-device on iOS devices, so near as I can tell there is no way to make an automated test for it.

So I think the best path is actually to carefully (that is, take care not to npm/yarn install as it will potentially blow away your changes) reach right into node_modules and then roll up the sleeves and get dirty with the .m and .js files directly in the messaging module

It *appears* based on my understanding of the problem that there are a couple of things:

This may actually fail if used on android? There is no android implementation - but this is a tangent:

 https://github.com/invertase/react-native-firebase/blob/503975909383582d8850470455eeef8f18194ba8/packages/messaging/lib/index.js#L128-L130

This implementation which is checking for foreground or background:

**Comment by mikehardy** [comment]
(hit enter too soon, updated comment above - https://github.com/ds300/patch-package may be used to test your changes more reliably, and then the same work can be proposed as a PR here?)

**Comment by miallo** [comment]
A bit of debugging later...
Here we successfully register the listener for getting into foreground
https://github.com/invertase/react-native-firebase/blob/c94546d8127606dca5bfd09ef92ec32eec333f19/packages/messaging/ios/RNFBMessaging/RNFBMessaging%2BNSNotificationCenter.m#L52
The [docs](https://developer.apple.com/documentation/foundation/nsnotificationcenter/1415360-addobserver) say that the selector function
> must have one and only one argument

but even if we add that, it does not change that this function is never called
https://github.com/invertase/react-native-firebase/blob/c94546d8127606dca5bfd09ef92ec32eec333f19/packages/messaging/ios/RNFBMessaging/RNFBMessaging%2BNSNotificationCenter.m#L133
So here we never set the `isHeadless` to false
https://github.com/invertase/react-native-firebase/blob/c94546d8127606dca5bfd09ef92ec32eec333f19/packages/messaging/ios/RNFBMessaging/RNFBMessaging%2BNSNotificationCenter.m#L147

The default YES value is also never called and the only reference we could find for the `addCustomPropsToUserProps` function is in the respective .h file. 
https://github.com/invertase/react-native-firebase/blob/d97587b33aa4c092a0d34291e24491ca66f9bcaa/packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m#L48

I have to say my knowledge about how RN works is even less than how ObjC is working but maybe this is a first hint?

**Comment by miallo** [comment]
Right... If I only followed [the instructions](https://github.com/invertase/react-native-firebase/blob/master/docs/messaging/usage/index.md#background--quit-state-messages) to update the AppDelegate.m I would have called the `addCustomPropsToUserProps` myself... Sorry for my stupidity...

**Comment by maystrenkoYurii** [comment]
This code fixed bug
<img width="659" alt="Снимок экрана 2021-09-18 в 17 20 25" src="https://user-images.githubusercontent.com/23016311/133891954-6c1e4a7b-aa3d-4bc0-aa28-bdadea953313.png">

**Comment by mym0404** [comment]
In iOS quit state, when I tapped a push notification, the app opened and render null because of `isHeadless`.

**Comment by mym0404** [comment]
if i send message with `content-available` in quit state, `isHeadless` is true during next app open time

**Comment by patissier-boulanger** [comment]
> if i send message with `content-available` in quit state, `isHeadless` is true during next app open time

Same here. If i remove content-available in json, isHeadless works fine.

**Comment by yuvraj-scalex** [comment]
This issue is surfacing in our production app and redirects users to the blank screen as isHeadless is true when the app is launched from the quit state. Even though we return `<App />` component when isHeadless is true, it is completely messing up with the navigation of the App.
Is there any way we can fix this?
RN version: 0.68.5
react-native-firebase: 17.4.1
react: 17.0.2

**Comment by yuvraj-scalex** [comment]
Hello @mikehardy, can you pl suggest something to get rid of this issue?
We've upgraded the react-native-firebase packages but still have no luck with this issue, should we upgrade the react-native version as well?

**Comment by miladdev85** [comment]
Is there any progress here? This issue should not be closed.
isHeadless does not change or get updated.

**Comment by humaidk2** [comment]
Hi, 

I spent some time investigating this issue and found the solution.

The problem comes from updating app properties while the bridge has not been loaded.

It's an issue that comes from react native, https://github.com/facebook/react-native/issues/20115


but react-native suggested that they won't be solving it,

![Screenshot 2023-11-29 at 7 58 27 AM](https://github.com/invertase/react-native-firebase/assets/12982026/c68c94e4-45be-49e9-af4c-c590708f98e9)



There's 2 suggested solutions:

1 is to wait for js to load then set the props, but this didn't work for us
```
[[NSNotificationCenter defaultCenter] addObserverForName:RCTJavaScriptDidLoadNotification object:nil queue:nil usingBlock:^(NSNotification * _Nonnull note) {
 
}];
```
2 is to patch react native,

https://github.com/facebook/react-native/pull/20116/files

**Comment by mikehardy** [comment]
@humaidk2 react-native-firebase definitely has some things that only load after the javascript environment comes up and to my knowledge it has been working reliably. Patching react-native in those files implies a local fork / build of react-native is *very* painful from a maintenance perspective making a javascript observer a strong preference

This notification is used internally in react-native I'm surprised it's not working, they appear to be specifying the bridge as the object to observe though, I wonder if you follow their addObserver pattern it might work better? Examples:

https://github.com/search?q=repo%3Afacebook%2Freact-native+RCTJavaScriptDidLoadNotification&type=code
