### ISSUE TITLE
[🐛] 🔥 Use of undeclared identifier 'FIRAnalytics'

### ISSUE THREAD

**Issue by kesha-antonov** [invertase/react-native-firebase#5389]
## Issue

Hi, I'm tring to build app for `My Mac`. For iPhone simulator it builds fine. 
For mac target it gives errors:

<img width="908" alt="Screenshot 2021-06-03 at 22 24 33" src="https://user-images.githubusercontent.com/11584712/120700768-ba179180-c4ba-11eb-9387-d45916d5bb2a.png">
<img width="922" alt="Screenshot 2021-06-03 at 22 26 10" src="https://user-images.githubusercontent.com/11584712/120700770-bbe15500-c4ba-11eb-8968-0dd63538e813.png">

I had googled everything but couldn't find solution.

This maybe related https://github.com/firebase/firebase-ios-sdk/issues/7521

How to solve this?

## Project Files

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/analytics": "^12.0.0",
"@react-native-firebase/app": "^12.0.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "analytics_auto_collection_enabled": "true"
}
```

</p>
</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods'
IOS_VERSION = '11.0'
platform :ios, IOS_VERSION
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
ENV['SWIFT_VERSION'] = '5.0'

target 'app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  # use_modular_headers!

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  $RNFirebaseAsStaticFramework = true
  pod 'GoogleTagManager'
  pod 'YandexMobileMetrica/Dynamic'

  use_unimodules!(exclude: %w(
    expo-face-detector
    expo-asset
    expo-constants
    expo-file-system
    expo-image-loader
    expo-permissions
    unimodules-app-loader
    unimodules-barcode-scanner-interface
    unimodules-camera-interface
    unimodules-constants-interface
    unimodules-face-detector-interface
    unimodules-file-system-interface
    unimodules-image-loader-interface
    unimodules-permissions-interface
    unimodules-sensors-interface
    unimodules-task-manager-interface
  ))

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  # pre_install do |installer|
  #   installer.pod_targets.each do |pod|
  #     if pod.name.eql?('RNScreens')
  #       def pod.build_type
  #         Pod::BuildType.static_library
  #       end
  #     end
  #   end
  # end

  post_install do |installer|
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      case target.name
      when 'EXInAppPurchases'
        target.build_configurations.each do |config|
          config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= ['$(inherited)']
          config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '"${PODS_CONFIGURATION_BUILD_DIR}/UMCore"'
          config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '"${PODS_CONFIGURATION_BUILD_DIR}/Sentry"'
        end

        file_ref = installer.pods_project.new_file('Sentry.framework')
        target.frameworks_build_phase.add_file_reference(file_ref)
      when 'FBSDKCoreKit-FacebookSDKStrings', 'GoogleTagManager-TagManagerResources', 'React-Core-AccessibilityResources', 'VK-ios-sdk-VKSdkResources'
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGN_IDENTITY[sdk=macosx*]'] = '-'
          config.build_settings['CODE_SIGN_IDENTITY[sdk=iphoneos*]'] = '-'
          config.build_settings['DEVELOPMENT_TEAM'] = 'MCL785384X'
          config.build_settings['CODE_SIGN_STYLE'] = 'Manual'
          # "CODE_SIGN_IDENTITY[sdk=*]" = "iPhone Developer"
        end
      when 'FBReactNativeSpec'
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end
end
```

#### `AppDelegate.m`:

```objc
@import Firebase;

[FIRApp configure];
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 112.61 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/kesha/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.3, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `12.0.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Analytics`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

**Comment by mikehardy** [comment]
react-native-firebase does not currently support the mac target as far as I know or at least I have not tried it, so it may "just work" or there may be other problems - just a warning - I'd like to see it work and it should work, but you may be blazing trail

Separately, you appear to be using static frameworks but your static frameworks setup appears to be incomplete?

https://rnfirebase.io/#allow-ios-static-frameworks

https://github.com/mikehardy/rnfbdemo/blob/e61e600a71a9d14e620c9c37e74bd7feee455fa4/make-demo.sh#L128-L129

```
  # This is how you configure for static frameworks:
  sed -i -e $'s/config = use_native_modules!/config = use_native_modules!\\\n  config = use_frameworks!\\\n  $RNFirebaseAsStaticFramework = true/' ios/Podfile
```

**Comment by kesha-antonov** [comment]
Hi!

I have
```
use_frameworks!
config = use_native_modules!
$RNFirebaseAsStaticFramework = true
```

Is it incomplete?

**Comment by mikehardy** [comment]
@kesha-antonov you can see how when I read the information you actually posted here and re-read just now I would think it is.

**Comment by mikehardy** [comment]
A note that if you have *added* that after you posted your information (and not updated the Podfile contents here as it does not seem to be there?) you will need to do a pod install again.
Also, my make-demo script explicitly tests the static frameworks case and it works, so I'm not sure exactly what is going on, whether it's specifically associated with catalyst builds and a problem here or if it's your project's integration.

In order to progress we will likely need a real example so we can reproduce your results https://stackoverflow.com/help/minimal-reproducible-example

**Comment by kesha-antonov** [comment]
I'm not sure if I understood you. I have the same in my Podfile. And it builds fine for iOS.![image](https://user-images.githubusercontent.com/11584712/120895952-e866af80-c627-11eb-8719-e06cd0cf15d3.jpeg)

**Comment by mikehardy** [comment]
Ah. I see it now. I missed that variable declaration at first, sorry

Then I suppose this may just be an issue with us not supporting catalyst builds. I don't believe we've ever tried it, it's not a use case we support (yet). If you can determine what the root cause is and post a PR we'd happily merge it, I'd like to understand why we don't support Catalyst in this instance (so we understand it) and support catalyst in general.

It would still help to have a https://stackoverflow.com/help/minimal-reproducible-example with the command specified we need to run to see the failure after cloning the repo
