### ISSUE TITLE
library not found for -lGoogleToolboxForMac

### ISSUE THREAD

**Issue by simpleblack** [invertase/react-native-firebase#539]
Issue

Hi~ 
I added In my source used `podfile` for `react-native-firebase-starter`
But I had build error
```
ld: library not found for -lGoogleToolboxForMac
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I can flow 3.0.* iOS Installation and open myproject.xcworkspace
I can build clear and pod update.
but keep error.

I need help

`podfile`
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNFirebaseStarter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFirebaseStarter

  # Required by RNFirebase
  pod 'Firebase/Core'
end
```

Environment

Application Target Platform: iOS
Development Operating System: macOS Sierra
Build Tools: Xcode 9.0
React Native version: 0.48.4
RNFirebase Version: 3.0.4
Firebase Module: core

**Comment by doctorwebbrasil** [comment]
hello @simpleblack what did you to fix it? tsk advance

**Comment by rochapablo** [comment]
+1

**Comment by ggobea** [comment]
@simpleblack We need your help.

**Comment by simpleblack** [comment]
@ggobea 

I solved it.
added this code

```
LIBRARY_SEARCH_PATHS
"$PODS_CONFIGURATION_BUILD_DIR/GoogleToolboxForMac"
"$PODS_CONFIGURATION_BUILD_DIR/nanopb"
```

**Comment by aVillarejo** [comment]
where man??

**Comment by Salakar** [comment]
![image](https://user-images.githubusercontent.com/5347038/37246787-e7d9cbee-24a7-11e8-8d60-4f25759037f6.png)


@aVillarejo I'm guessing he added `$(inherited)` to the search paths list as above
