### ISSUE TITLE
[🐛] iOS Notification Images

### ISSUE THREAD

**Issue by SLSofiane26** [invertase/react-native-firebase#5394]
I have followed the documentation to display image in the IOS notification from the firebase console but it doesn't work ....

https://rnfirebase.io/messaging/ios-notification-images

Thanks you

**Comment by SLSofiane26** [comment]
Someone could help me ?

**Comment by SLSofiane26** [comment]
<img width="692" alt="Capture d’écran 2021-06-06 à 19 53 36" src="https://user-images.githubusercontent.com/63287439/120934995-0c49f400-c701-11eb-882b-e6159b8f43f2.png">

**Comment by SLSofiane26** [comment]
<img width="605" alt="Capture d’écran 2021-06-06 à 19 53 53" src="https://user-images.githubusercontent.com/63287439/120935016-1bc93d00-c701-11eb-8bd6-fb2773cbaaee.png">

**Comment by SLSofiane26** [comment]
<img width="542" alt="Capture d’écran 2021-06-06 à 19 54 28" src="https://user-images.githubusercontent.com/63287439/120935022-21268780-c701-11eb-910b-5872d525ca71.png">

**Comment by SLSofiane26** [comment]
<img width="562" alt="Capture d’écran 2021-06-06 à 19 55 44" src="https://user-images.githubusercontent.com/63287439/120935038-33a0c100-c701-11eb-96d2-24a1fd3b8540.png">

**Comment by SLSofiane26** [comment]
![Uploading Capture d’écran 2021-06-06 à 19.53.58.png…]()

**Comment by SLSofiane26** [comment]
![Uploading Capture d’écran 2021-06-06 à 19.53.58.png…]()

**Comment by SLSofiane26** [comment]
<img width="779" alt="Capture d’écran 2021-06-06 à 19 53 58" src="https://user-images.githubusercontent.com/63287439/120935178-c3df0600-c701-11eb-9a50-7514ce5c5e3a.png">

**Comment by Vitalik7** [comment]
@SLSofiane26 what notification format do you send from the server?

**Comment by SLSofiane26** [comment]
@Vitalik7 Hello, now the problem is to display the image when the app is on foreground. I i succeeded display the image only when the app is on background ......

Thanks

**Comment by SLSofiane26** [comment]
Any solutions ?
