### ISSUE TITLE
Expo imagepicker & Storage

### ISSUE THREAD

**Issue by andfk** [invertase/react-native-firebase#54]
Hi,

I switched from `react-native-image-picker` (that worked good initially with storage of this library) to the ImagePicker of `expo` SDK and when the image is selected it returns the param `origURL` with the format of `assets-library://` but the optimal is to use the `uri` that comes in the format of `file://`.

```javascript
{
  "cancelled":false,
  "height":1611,
  "width":2148,
  "uri":"file:///data/user/0/host.exp.exponent/cache/cropped1814158652.jpg"
}
```

Checking the source code, other format different than `assets-library://` is not recognised. ContentType was automatically detected using `react-native-image-picker` with `1.0.0-alpha11` or at least I didn't have to specify it before and it was set in storage correctly but right now is not. Im using the `assets-library://` from `origURL ` and specifying manually the contentType, it works perfect. 

Many thanks

**Comment by Salakar** [comment]
@andfk not sure of the issue here, file:// paths should be supported, it's implemented [here](https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/storage/RNFirebaseStorage.java#L332-L338)

Unless maybe [this line](https://github.com/invertase/react-native-firebase/blob/master/lib/modules/storage/reference.js#L94) is causing an issue? Could you comment out that line etc in your local copy, restart packager and rebuild - then see if it works?

**Comment by andfk** [comment]
@Salakar thanks for quick answer.

Well, i commented the line and replaced the param from _filePath to filePath.
```javascript
// const _filePath = filePath.replace('file://', '');
    return new StorageTask(UPLOAD_TASK, FirebaseStorage.putFile(this.path, filePath, metadata), this);
```

The error still happens and noticed that in Xcode it shows the following:
```
Body file is unreachable: /Users/{$USER}/Library/Developer/CoreSimulator/Devices/F5A86517-C58A-4529-8289-91F0057AC873/data/Containers/Data/Application/0DF942A9-F53A-4B0F-AC6A-9754F4211942/Library/Caches/ExponentExperienceData/xpouser/ImagePicker/9125580B-9EF3-4AE7-B266-252BC550C65E.jpg
  Error Domain=NSCocoaErrorDomain Code=260 "The file “9125580B-9EF3-4AE7-B266-252BC550C65E.jpg” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/{$USER}/Library/Developer/CoreSimulator/Devices/F5A86517-C58A-4529-8289-91E0057AC573/data/Containers/Data/Application/0DF942A9-F53A-4B0F-AC6A-9754F4211942/Library/Caches/ExponentExperienceData/xpouser/ImagePicker/9125580B-9EF3-4AE7-B266-252BC550C65E.jpg, NSFilePath=/Users/${USER}/Library/Developer/CoreSimulator/Devices/F5A86517-C58A-4529-8289-91F0057AC873/data/Containers/Data/Application/0DF942A9-F53A-4B0F-AC6A-9754F4211942/Library/Caches/ExponentExperienceData/xpouser/ImagePicker/9125580B-9EF3-4AE7-B266-252BC550C65E.jpg, NSUnderlyingError=0x610000851df0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}
```
Is this helpful? i would like to help with this issue as much as i can. Is important to say that using `origURL` param where the file in the format of `assets-library://` does the job, but i have to specify content type manually.

In use: `^1.0.0-alpha12` only tested on IOS for now.

Many thanks

**Comment by andfk** [comment]
Hi again. Did some checks but never did the most basic and simple test. Checking if the file really exists with the path provided. Seems some naming in the setup was causing the file to be unreachable, like error trace says. Tested again the storage module and it works perfect!

Many thanks for the great effort on this library.
