### ISSUE TITLE
Previous and Next reversed

### ISSUE THREAD

**Issue by joshkleyman** [invertase/react-native-firebase#5409]
On the releases page (https://rnfirebase.io/releases) the "previous" and "next" have switched places. "Migrating to v6" is on the left side with the double arrow pointing left [which is supposed to be previous, but actually leads to the next part of the documentation) and vice versa on the right side.

![image](https://user-images.githubusercontent.com/63674231/121611608-7f0ee400-ca0d-11eb-97e6-8dc89ac1e066.png)

**Comment by mikehardy** [comment]
Great catch, thanks - got a PR in progress and will fix this in it
