### ISSUE TITLE
[🐛] Bug Report Title - Messaging.onMessage() is called when app first opened

### ISSUE THREAD

**Issue by babyrusa** [invertase/react-native-firebase#5410]
## Issue

Whenever I get 1 or a few notifications from the background (on IOS), when I open the app either immediately or hours later, Messaging.onMessage() was always fired the last push notification that was handled by the background. I don't notice this in Android. (Android has different issues however I have not done enough testing) .Is this a familiar behavior?

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x ] iOS
  - [ ] Android
  - [ x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 11.5.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. app, messaging`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I am not familiar with this, no. The template is skipped and there is no reproduction, we close those issues, sorry

**Comment by alphadev2018** [comment]
Did you fix this issue? @babyrusa
