### ISSUE TITLE
Unable to set database persistence

### ISSUE THREAD

**Issue by Shank209** [invertase/react-native-firebase#542]
First of all, thanks for this library. It saved me a lot of trouble. My issue is, I'm trying to set persistence for the realtime database and I tried doing it through the config when firebase is first initialized like:

```
firebase.initializeApp({
    ...
    persistence: true
})
```

Apparently this doesn't work yet. See [this issue](https://github.com/invertase/react-native-firebase/issues/529) for more details.

So I tried using `firebase.app().database()._native.setPersistence(true)` which was recommended as a workaround in the above issue and it gives me an error saying **"calls to setPersistenceEnabled() must be made before any other usage if FirebaseDatabase instance"**.

I understand what that error means and in my code, I'm calling `setPersistence()` in the root level App component's `componentWillMount()` before the database instance is used anywhere. What's the right way to implement this?

I'm on android and this is my code:
```
class App extends Component {
	componentWillMount() { 
		if (!firebase.apps.length) {
			firebase.initializeApp({
				apiKey: 'xxx',
				authDomain: 'xxx',
				databaseURL: 'xxx',
				projectId: 'xxx',
				storageBucket: 'xxx',
				messagingSenderId: 'xxx'
			});
		}
		firebase.app().database()._native.setPersistence(true);
	}
        ....
}
```

**Comment by Ehesp** [comment]
Please can you provide the environment information requested in the template.

**Comment by Shank209** [comment]
Sorry, here it is:

1. Application Target Platform: Android

2. Development Operating System: Windows 10

3. Build Tools: Android Studio 2.2.3

4. React Native version: 0.49.3

5. RNFirebase Version: 3.0.4

6. Firebase Module: database

**Comment by chrisbianca** [comment]
@Shank209 The fix for this will be included in the next release, which should be at some point today.

Unfortunately, due to the way that React Native JS integrates with the native side, it's hard to ensure that the `setPersistence()` call is made before anything else happens on the native side, which is why you're seeing this issue when invoking it manually.
