### ISSUE TITLE
🔥 [🐛] signInWithPhoneNumber hangs when called with the same number twice

### ISSUE THREAD

**Issue by helenaford** [invertase/react-native-firebase#5426]
## Issue

When calling `auth().signInWithPhoneNumber()` twice with the same phone number, it hangs and causes an infinite loading state on Android.  If `forceResend` is set to true, a result is returned but this causes the text message to be sent multiple times. 

On iOS, if  `auth().signInWithPhoneNumber()` is called twice, it does not hang but it will resend a code, which mimics the behaviour if `forceResend` is set to true.

Not sure if this is a bug with RNFB, the native SDK, or something the developer should prevent themselves.

Reference docs: https://rnfirebase.io/reference/auth#signInWithPhoneNumber

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
(node:86027) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.49 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 19, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 24.0.1, 24.0.3, 26.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2
      System Images: android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 12.1.0
- **`Firebase` module(s) you're using that has the issue:**
  - Auth
- **Are you using `TypeScript`?**
  - Y

</p>
</details>

---

**Comment by mikehardy** [comment]
Just a note I've collaborated with @helenaford and I know this project is using react-native-firebase v12.1.0 with up to date references to firebase-android-sdk / firebase-ios-sdk and is in general "clean" with regard to it's use of this module so this issue will be valid for current code, it needs inspection

It may actually be visible in the test harness already, I've long puzzled over why the authentication e2e tests on android wait for full 60s timeouts while iOS sails along and this may be the test case / initial investigation that roots it out.

Specifically note the suspiciously 60s-times-taken here for the phone verify e2e tests:

https://github.com/invertase/react-native-firebase/runs/2806971082?check_suite_focus=true#step:22:276

**Comment by mikehardy** [comment]
I'm starting to catch up on RNFB items, and would like to keep this open for now

**Comment by vlsimctco** [comment]
We have recently updated all react-native-firebase dependencies to version 14.8.0 and are now seeing this behaviour. We have previously used react-native-auth 9.2.3 where this was working as expected. As a workaround we will use forceResend as mentioned in the original issue, but this issue still exists.

**Comment by mikehardy** [comment]
I appreciate the repro note on current versions @vlsimctco - I'm glad it's got a workaround but it'll stay alive in the review queue

**Comment by mikehardy** [comment]
one more pause for review if possible

**Comment by helenaford** [comment]
would be good to try and get to the bottom of this
