### ISSUE TITLE
Persistence for the default initialized app is not working

### ISSUE THREAD

**Issue by Shank209** [invertase/react-native-firebase#543]
According to the [docs](https://rnfirebase.io/docs/v3.0.*/core/default-app), in order to enable persistence for the DEFAULT initialized app, I need to add the line `FirebaseDatabase.getInstance().setPersistenceEnabled(true);` to my **MainActivity.java** file which I did. But persistence is still not working. This is the code for my MainActivity.java file:
```
package com.myapp;

import com.facebook.react.ReactActivity;
import com.google.firebase.database.FirebaseDatabase;
import android.os.Bundle;

public class MainActivity extends ReactActivity {
    @Override
	protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
		FirebaseDatabase.getInstance().setPersistenceEnabled(true);
	}

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "myapp";
    }
}

```

Application Target Platform: Android

Development Operating System: Windows 10

Build Tools: Android Studio 2.2.3

React Native version: 0.49.3

RNFirebase Version: 3.0.4

Firebase Module: database

**Comment by chrisbianca** [comment]
What do you mean by persistence isn't working?  How do you know this is the case?

**Comment by Shank209** [comment]
When I go offline, perform some write actions, close the app, restart it and then go online, none of those actions are getting pushed.

**Comment by chrisbianca** [comment]
@Shank209 I'd suggest putting a break point on the line `FirebaseDatabase.getInstance().setPersistenceEnabled(true);` and check that it's being called?

**Comment by Shank209** [comment]
@chrisbianca  I set a break point and check like you said. It is indeed getting called.

**Comment by Shank209** [comment]
Also, if it matters, auth() and every other part of database() and working just fine. It's just the persistence which is the issue. I tested on both an emulator and physical devices.

**Comment by Salakar** [comment]
@Shank209 can you try move the setPersistence call to your MainApplication rather than MainActivity, the docs have been updated to reflect. Thanks

**Comment by chrisbianca** [comment]
Closing due to lack of response. Please re-open if you're still experiencing issues and let us know the answers to the above questions.

**Comment by TitanKing** [comment]
According to the docs it should be added in MainApplication.java under inside the onCreate method; 
Like so: 

  @Override
  public void onCreate() {
    super.onCreate();
    FirebaseDatabase.getInstance().setPersistenceEnabled(true);
    SoLoader.init(this, /* native exopackage */ false);
  }

This causes an exception as such;

  
  
  
  
  /Volumes/nvme/Users/jason/projects/acmtrackmobile/android/app/src/main/java/com/acmtrack/a
    pp/futurity/MainApplication.java:79: error: cannot find symbol
      FirebaseDatabase.getInstance().setPersistenceEnabled(true);
      ^
    symbol:   variable FirebaseDatabase
    location: class MainApplication
  1 error
  :app:compileDebugJavaWithJavac FAILED

**Comment by TitanKing** [comment]
Update: For those struggling with the same issue, I had to add this line to the same file near the top:

import com.google.firebase.database.FirebaseDatabase;

**Comment by chrisbianca** [comment]
@TitanKing Thanks for highlighting this, I've just added the additional details to the documentation.

**Comment by TitanKing** [comment]
@chrisbianca You guys are just amazing, truly.

**Comment by nikolal** [comment]
Hi,

Is there an example for "createUserWithEmailAndPassword" and other auth features when user is offline?

For example I am setting:

```
var firebase2 = RNFirebase.initializeApp({ persistence: true });

```

and then:

```
    firebase2.auth().createUserWithEmailAndPassword(this.state.signupEmail, this.state.signupPassword)
      .catch(function(error) {
        // Handle Errors here.
        var errorCode = error.code;
        var errorMessage = error.message;
        if (errorCode == 'auth/weak-password') {
          alert('The password is too weak.');
        } else {
          alert(errorMessage);
        }
        console.log(error);
      })
      .then(function(User) {
        console.log(User)
      });
```

But I am not getting User...
After I turn on internet I am getting:

```
Error: A network error has occurred, please try again.
```
and User is undefined.

Is there something else I need to do?

**Comment by Ehesp** [comment]
@nikolal only database is going to work offline for such actions. If you're offline you need the server to validate that say the email address is not already in use (for example).

**Comment by nikolal** [comment]
@Ehesp 

OK thanks. 

What about keeping users authenticated? Can I login user in offline mode? I need to access database based on logged in user.

**Comment by chrisbianca** [comment]
@nikolal If the user was logged in before going offline, they will remain logged in when offline, but will obviously only be able to access anything that had previously been accessed on the device.  If the user was not logged in when the device went offline, then they will not be able to login until the device is back online.

Also note that database security rules are server side, so can not be enforced when offline.

**Comment by nikolal** [comment]
OK. So this means if I log in user once and keep him logged in for a longer time, next time he opens the app offline he will stay logged in and will be able to access database ( if rules are allowing it ).

Am I correct?

**Comment by chrisbianca** [comment]
Yes, the user will be able to access anything that has been persisted / cached in the database.

**Comment by nikolal** [comment]
OK, great. Thank you very much.

**Comment by weerakkodylr** [comment]
I have tried persistence storage and the issue is that user doesn't show logged in when I open the app offline mode 
(previously opened in online mode and logged in with the user successfully).

Data looks to be persisting except for **authentication**. 
is there a separate settings for that? is this the expected behavior  ?

**Comment by fungilation** [comment]
I have a new problem after I added `FirebaseDatabase.getInstance().setPersistenceEnabled(true);`

On running `react-native run-android`:

```
MainApplication.java:35: error: package com.google.firebase.database does not exist
import com.google.firebase.database.FirebaseDatabase;
                                   ^
MainApplication.java:88: error: cannot find symbol
    FirebaseDatabase.getInstance().setPersistenceEnabled(true);
    ^
  symbol:   variable FirebaseDatabase
  location: class MainApplication
2 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

I'm new to native Android development. Any idea on how to solve `com.google.firebase.database` being missing?

**Comment by chrisbianca** [comment]
@fungilation sounds like you haven't added the `firebase-database` dependency to your `app/build.gradle`

**Comment by fungilation** [comment]
@chrisbianca thanks so much! I feel dumb now, pods spoiled me on iOS side and I forgot pods is iOS only when I set that up.

Now I'm running into this: https://github.com/invertase/react-native-firebase/issues/17#issuecomment-386009595 (unrelated)
