### ISSUE TITLE
[🐛] IOS - error subscribing: Error: [messaging/unknown] The operation couldn’t be completed. Device ID and checkin info is not found. Will not proceed with subscription/unsubscription.

### ISSUE THREAD

**Issue by kristinadarroch** [invertase/react-native-firebase#5436]
## Issue

Getting errors on iOS only subscribing and unsubscribing to topics in react-native-firebase/messaging

---

## Project Files

`await messaging().subscribeToTopic(topicName).catch(error => GETTING ERROR HERE ON IOS ONLY)`

**subscribe error:**

```
error subscribing: Error: [messaging/unknown] The operation couldn’t be completed. Device ID and checkin info is not found. Will not proceed with subscription/unsubscription. +2m [object Object]
```

`await messaging().unsubscribeFromTopic(topicName).catch(error => GETTING ERROR HERE IN IOS ONLY)`

**unsubscribe error:**

```
error unsubscribing: Error: [messaging/unknown] The operation couldn’t be completed. Device ID and checkin info is not found. Will not proceed with subscription/unsubscription.
```

****

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/messaging": "^8.0.1",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! The version of react-native-firebase you are using is quite old, and in general we can only support things we reproduce on current versions. Can you update to v12.1.0 and attempt to reproduce again? If you can reproduce, please open a new ticket with all the information requested (the snippets provided here aren't enough to really have us know what the execution environment is, apologies) and we can take a look

**Comment by kristinadarroch** [comment]
@mikehardy thanks, will do. If there's no network connectivity will this cause an error like this? i couldn't find ample documentation on this topic

**Comment by mikehardy** [comment]
Totally unsure sorry, that's a reasonable hypothesis but it might just be older versions too. Will definitely examine if you reproduce it while current

**Comment by jefflewis** [comment]
@mikehardy Following up for @kristinadarroch  -> After upgrading to `8.7.0`, we now get a more direct error message when attempting to subscribe to a topic while offline: `[messaging/unknown] A data connection is not currently allowed.`. While this does make sense, our same application code works on the prior version of `Firebase/Messaging`. The new version receives this error appears to never attempt the connection.

Did something change about some kind of retry behavior where prior to upgrading, a retry was being handled by firebase, but now our application is responsible for the retry?
