### ISSUE TITLE
🔥[🐛] iOS unable to signInWithCredential using Facebook Limited Login

### ISSUE THREAD

**Issue by craig1123** [invertase/react-native-firebase#5441]
## Issue
Upgrading to `react-native-fbsdk-next` for iOS has been a pain. First off, the docs are wrong for Facebook https://rnfirebase.io/auth/social-auth#facebook. I know I can make a PR, but I need to get it working first on my own machine before documenting it. 

`react-native-fbsdk-next` now requires `getAuthenticationTokenIOS` instead of `getCurrentAccessToken` if on iOS and using limited login. When using the authenticationToken to get the facebook credential and `signInWithCredential`, firebase throws an error: "[auth/invalid-credential] The supplied auth credential is malformed or has expired."

Here's how I'm implementing it
```
  try {
    const result = await LoginManager.logInWithPermissions(
      ['public_profile', 'email'],
      'limited',
    );

    if (result.isCancelled) {
      return false;
    }

    if (Platform.OS === 'ios') {
      const data = await AuthenticationToken.getAuthenticationTokenIOS();
      return data;
    } else {
      const data = await AccessToken.getCurrentAccessToken();
      return data;
    }

  } catch (error) {
    console.log(error.message)
  }
```

and here is where I consume the authenticationToken
```
    const { accessToken, authenticationToken } = data;
    const token = ios ? authenticationToken : accessToken;
    const credential = auth.FacebookAuthProvider.credential(token);
     // breaks on the next line 
     const userCredential = await auth().signInWithCredential(credential);
```
I believe that the authenticationToken does not have all the properties that is needed for signInWithCredential(), but that's just my vague opinion

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
    "@invertase/react-native-apple-authentication": "^2.1.2",
    "@react-native-firebase/analytics": "^12.1.0",
    "@react-native-firebase/app": "^12.1.0",
    "@react-native-firebase/auth": "^12.1.0",
    "@react-native-firebase/crashlytics": "^12.1.0",
    "@react-native-firebase/firestore": "^12.1.0",
    "@react-native-firebase/perf": "^12.1.0",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-fbsdk-next": "^4.3.0",
     ...
  },
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
$RNFirebaseAsStaticFramework = true
$RNFirebaseAnalyticsWithoutAdIdSupport = true

platform :ios, '11.4'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target [name-of-app] do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  pod 'GoogleSignIn', '~> 5.0.2'
end
```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <Firebase.h>
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <RNSplashScreen.h>
#import <RNGoogleSignin/RNGoogleSignin.h>
#import <FBSDKCoreKit/FBSDKCoreKit.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"app name"
                                            initialProperties:nil];
  
  // Define UNUserNotificationCenter
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [RNSplashScreen show];

  return YES;
}

- (BOOL)application:(UIApplication *)application 
  openURL:(nonnull NSURL *)url 
  options:(nonnull NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options
{
  return [[FBSDKApplicationDelegate sharedInstance] application:application openURL:url options:options] || [RNGoogleSignin application:application openURL:url options:options];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge

{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 1.27 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 12.1.0
- **`Firebase` module(s) you're using that has the issue:**
  - auth
- **Are you using `TypeScript`?**
  - N

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You may notice I help maintain both repos ;-). I haven't had any problems, there was nothing I needed to change when I updated to fbsdk-next that I remember, on the react-native-firebase side. On the fbsdk-next side I had to update the init sequence to initialize sdk on iOS, but that was it. I am not, however, using "limited login" - I haven't tried that out at all and must admit I'm unfamiliar. Have you tried it with non-limited login? If that works then you'll be reproducing my experience at least, and we'll know we need to start investigating what limited means w.r.t. the login and why the tokens aren't acceptable

**Comment by craig1123** [comment]
Thanks for the reply @mikehardy. I have seen that you help maintain both and I'm very grateful for it.

Yes, the AccessToken and fbsdk-next work when not using limited login. However, I don't want to have to ask the customer to accept tracking, so I'd rather not go that route.

The fbsdk-next docs say "When loginTrackingIOS is limited - AccessToken will be unavailable. Use AuthenticationToken instead." AccessToken is `null` (or undefined I forgot) when limited. https://github.com/thebergamo/react-native-fbsdk-next#limited-login-ios. However, the AccessToken is needed for Firebase's `signInWithCredential` to work. I wonder if this is even possible at all without IDFA tracking

**Comment by mikehardy** [comment]
I was afraid of that - that the difference was only evident with limited tracking. To be honest I'd prefer a limited login in my main work app as well so I'm interested here but I have no special knowledge. I don't have time at the moment a fruitful path is probably going to involve upstream firebase-ios-sdk, so any attempt in node_modules here to log out tokens of each type and/or do a native reproduction using their Auth Quickstart is the thorough way to go about it, with a parallel track of scouring their issue list, fbsdk upstream issue list and stackoverflow.com (firebase staff answer there periodically)

**Comment by mikehardy** [comment]
https://github.com/firebase/firebase-ios-sdk/issues/8048 is tracking this upstream
I was unable to find anything else out about it.
I can only imagine very difficult workarounds in the meantime, involving self-validation of the Facebook Limited Login AuthenticationToken https://developers.facebook.com/docs/facebook-login/limited-login/token/validating followed by minting your own Firebase Auth Token https://firebase.google.com/docs/auth/android/custom-auth

I think the flow would be:
- app implements Limited Login on iOS via FBSDK
- app sends that JWT to custom firebase cloud function
- custom firebase cloud function validates JWT and if valid mints custom Auth token using admin sdk and returns it
- app uses this custom auth token for firebase access

All sorts of implementation details - nonce-handling while performing auth and minting tokens, token refresh how?, user resolution / de-duplication from "firebase+facebook native" existing users to this new limited login regime, etc

**Comment by MegaMaddin** [comment]
@mikehardy Openend PR https://github.com/invertase/react-native-firebase/pull/6073 for that.
