### ISSUE TITLE
[🐛] How to retrieve client identifier by React code in React Native project.

### ISSUE THREAD

**Issue by GuoYongming** [invertase/react-native-firebase#5445]
## Issue

There is a new requirement in our project that retrieve client identifier, our project is a React Native project, we checked some documents, such as https://firebase.google.com/docs/projects/manage-installations#retrieve_client_identifer and https://rnfirebase.io/, but they do not mention any methods how to retrieve client identifier with React code.
---
#### `package.json`:

```json
    "@react-native-firebase/analytics": "12.0.0",
    "@react-native-firebase/app": "12.0.0",
    "@react-native-firebase/crashlytics": "12.0.0",
    "@react-native-firebase/dynamic-links": "12.0.0",
    "@react-native-firebase/messaging": "12.0.0",
    "@react-native-firebase/perf": "12.0.0",
```

#### `firebase.json` for react-native-firebase v8:

```json
"react-native": {
    "crashlytics_auto_collection_enabled": true,
    "crashlytics_debug_enabled": true
  }
```

**Comment by mikehardy** [comment]
Firebase Installations APIs, including the one you linked, are not implemented here, yet. It's on the roadmap but isn't complete.

If this is an urgent need for you, and seeing that you already use messaging (which depends on installations, so it should be available during compilation), you might be able to roughly hack it in to the code directly via altering the contents of the lib / android / ios folders in `node_modules/@react-native-firebase/messaging` to add the API according to the very doc link you reference above

If you use [patch-package](https://github.com/ds300/patch-package) the patch itself will be easy to maintain

If it weren't for patch-package I'd never suggest it, but given it's only one API you need and to add it here involves creating and publishing an entirely new module (not an easy task at all) I think it's the least-bad option and could work out well
