### ISSUE TITLE
[🐛]  - setBackgroundMessageHandler only fired with "contentAvailable": true

### ISSUE THREAD

**Issue by jeremykanso** [invertase/react-native-firebase#5449]
## Documentation Feedback

We spent a lot of time trying to figure out why setBackgroundMessageHandler wasn't fired when the app was in the background or terminated.

We discovered it was only working when the option contentAvailable was set to true in the payload of the notification, using a curl command with https://firebase.google.com/docs/cloud-messaging/send-message:

```
curl -X POST --header "Content-Type:application/json" --header "Authorization: Bearer ..." -d '{"message":{"data":{"test": "12345"}, "topic": "ProductionallUsers", "notification": {"title": "Test tech", "body": ""}, "apns": {"payload": {"aps":{"content-available": 1}} }}}' https://fcm.googleapis.com/v1/projects/project-id/messages:send
```

setBackgroundMessageHandler is at least fired with those 2 cases:
- content-available is set in the payload
- notification is not set

setBackgroundMessageHandler is not fired with this case:
- content-available is not set in the payload and notification is set

Maybe it is intentional but it is unclear in the documentation and we spent a long time understanding the impact of content-available.

I would be happy to discuss about this issue.

**Comment by mikehardy** [comment]
Please hit the edit button if it is unclear, we merge docs PRs quickly, however this is all explained here I believe, on the usage page for the module: https://rnfirebase.io/messaging/usage#data-only-messages

**Comment by jeremykanso** [comment]
> Please hit the edit button if it is unclear, we merge docs PRs quickly, however this is all explained here I believe, on the usage page for the module: https://rnfirebase.io/messaging/usage#data-only-messages

Well I wasn't talking about 'data-only messages' but also about mixed notification: what was weird is to have content-available defined to true (bu default) for data-only messages but not for mixed notification. I am not sure that it is intentional so I don't want to edit the documentation before knowing the design behind it.

**Comment by mikehardy** [comment]
without any specifics on the platform you are targeting, this is speculative, but I'll assume iOS? As content-available should not matter for Android, but if it does then that's confusing of course.

For me, on iOS, content-available is a strict requirement to have any chance of a background message being delivered and calling your handler, but is only useful in a data-only FCM context. Mixed payloads will never call your background handler, they call the notification handler and deliver the data payload in the FCM JSON the notification handler receives, if I recall correctly.

On Android, content-available should not matter

Worth mentioning that on iOS data-only message deliver is never guaranteed, they are by design not reliable, delivery of data-only messages should only be used in "nice to have" use cases like "it would be nice if the app updated it's content before the user went to look, but it's okay if it does not"

**Comment by jeremykanso** [comment]
> without any specifics on the platform you are targeting, this is speculative, but I'll assume iOS? As content-available should not matter for Android, but if it does then that's confusing of course.

Sorry, yes it is on iOS.

> on iOS, content-available is a strict requirement to have any chance of a background message being delivered and calling your handler

This is right.

> Mixed payloads will never call your background handler, they call the notification handler and deliver the data payload in the FCM JSON the notification handler receives, if I recall correctly.

Actually, this is wrong. If content-available is set to true in the payload, it will be delivered in the handler.
_NB: moreover, content-available seems to be set to true by default for data-only messages._

> Worth mentioning that on iOS data-only message deliver is never guaranteed, they are by design not reliable, delivery of data-only messages should only be used in "nice to have" use cases like "it would be nice if the app updated it's content before the user went to look, but it's okay if it does not"

Yes I know.

**Comment by mikehardy** [comment]
Very interesting result:

> Actually, this is wrong. If content-available is set to true for a mixed payload, it will be delivered in the handler.
NB: moreover, content-available seems to be set to true by default for data-only messages but not for mixed ones.

When is it delivered? On user interaction with the notification generated from the mixed payload, or immediately on FCM landing on device? Very curious

with regard to unreliability: 
>  Yes I know.

good :relieved: - some people have unrealistic expectations and build a whole business model around it, I try hard to make sure everyone understands

**Comment by jeremykanso** [comment]
> When is it delivered? On user interaction with the notification generated from the mixed payload, or immediately on FCM landing on device? Very curious

No need for interaction. The notification is delivered, a few seconds later you'll receive the data in the setBackgroundMessageHandler.

> [mixed payloads] call the notification handler and deliver the data payload in the FCM JSON the notification handler receives, if I recall correctly.

When you say "the notification handler", you mean onMessage, right ?

**Comment by mikehardy** [comment]
> No need for interaction. The notification is delivered, a few seconds later you'll receive the data in setBackgroundMessageHandler.

That does not match with my understanding but I don't used mixed payloads and there is nothing like experimental results to clear up an incorrect understanding. This does seem like a finding worthy of documentaiton

> When you say "the notification handler", you mean onMessage, right?

Yes - I was thinking of the pure-notification payload handler that is normally called when you send an FCM with notification only in JSON, and the user taps on the resulting real notification on the device - I  believe that is onMessage

**Comment by jeremykanso** [comment]
> This does seem like a finding worthy of documentaiton

Ok I will test in production that everything is ok and still working as my tests suggested, then I'll edit the documentation.
