### ISSUE TITLE
[firestore] Invalid Date on some Android devices

### ISSUE THREAD

**Issue by chrisbianca** [invertase/react-native-firebase#545]
Following on from: https://github.com/invertase/react-native-firebase/issues/533#issuecomment-338772354 courtesy of @urajat:

Just got around to testing this. 3.0.5 works on the emulator (tested on Android 7.1.1). But on the device with 7.1.1, this doesn't work - I get an Invalid Date value for the dates which are being read even though they work perfectly on the emulator and are correct on Firestore too. I added debugging statements in buildTypeMap to compare the values on device vs emulator - there is no change and the parsing is working as expected. I even tried going back to 3.0.4 and manually making the 'X' to 'Z' change to see if that helps, but nope - same Invalid Date issue on device. In the morning, I was testing with a 6.0.1 device where the Z option worked. Not sure if there's some other place where there is some date interpretation happening.

**Comment by chrisbianca** [comment]
@urajat Can I start by saying that I hate working with Dates, in any programming language, let alone when you've got to convert between 3 different ones!  You'd think that after 40 years of software development (give or take) that somebody would have got them working properly...

This sounds like a Javascript parsing issue.  A quick search on RN shows that there are a few historical issues which indicate that apparently, if debug mode is enabled then date handling is done differently?!

https://github.com/facebook/react-native/issues/13195

Do you have debug mode enabled?

**Comment by chrisbianca** [comment]
@urajat Just to confirm - with debug mode enabled, everything works fine.  With debug mode disabled, it doesn't work.  I'm going to look at using `ms` rather than the ISO string and see if that works any better

**Comment by urajat** [comment]
@chrisbianca +1 on the dates bit. I remember putting in a fix in Django 10 years ago for a timezone-related issue :-( 

I tried out the debug mode enabling/disabling part and can see that the issue is indeed there. With both emulator and device, with debug mode disabled, I get the `Invalid Date` error.

**Comment by chrisbianca** [comment]
@urajat Ok, I've just pushed up a fix - hopefully the last one!  Are you able to test with the latest code?  You can install using:

`npm install --save https://github.com/invertase/react-native-firebase#v3.0.x`

**Comment by urajat** [comment]
@chrisbianca Yes, this seems to work on both device and emulator in debug/non-debug modes on Android :-)

**Comment by chrisbianca** [comment]
Whoop, we got their eventually! Thanks for all your help - I'll get a release out either today or tomorrow with this change in

**Comment by urajat** [comment]
Great! Thanks for the quick turnaround on this.
