### ISSUE TITLE
[📚] Documentation Issue Title - Send/SendToDevice/SendToTopic/SendMessage/SendToDeviceGroup/SendToCondition ?

### ISSUE THREAD

**Issue by X-Titouan** [invertase/react-native-firebase#5453]
## Documentation Feedback

I search on API documentation the difference between all this methods :

![image](https://user-images.githubusercontent.com/85634633/123441889-a1d7f580-d5d4-11eb-9e9e-c02f9c7cd286.png)

and I have only found :

![image](https://user-images.githubusercontent.com/85634633/123442154-e2d00a00-d5d4-11eb-9fa1-73a22d6bf9ad.png)

I experienced a LOT of difficulties to be able to receive push notification on iOS Quit mode. It could be great to give more hints than just these two piece of code:

https://rnfirebase.io/messaging/usage#data-only-messages

Thanks

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
> I experienced a LOT of difficulties to be able to receive push notification on iOS Quit mode

If you use a notification block in your FCM JSON, you should enjoy reliable delivery

If you use data-only messages you should not expect reliable delivery, the iOS platform only delivers data-only messages on a "low effort" basis (that is, there is a large chance they won't be delivered depending on device power status, frequency of messages, other settings)

**Comment by X-Titouan** [comment]
Alright 😊

 I think I will display a visible notification to ping the app, If iOS
force us to disturb user instead of being silent and respectful, no problem
for me...

Focusing on the question title, is there any difference between all theses
method ?

Thank you for your reactivity

Le ven. 25 juin 2021 à 16:50, Mike Hardy ***@***.***> a
écrit :

**Comment by mikehardy** [comment]
In general, the firebase-js-sdk is our reference for API signature and behavior, if our docs are not clear in some way on what the differences are, you may try those. Failing that (and for messaging sometimes firebase-js-sdk is simply missing APIs, that's the whole reason to have a "native" react-native-firebase that wraps firebase-android-sdk / firebase-ios-sdk) you should consult their documentation. For general usage questions the upstream documentation in those SDKs and stackoverflow for questions/answers is the best path I think
