### ISSUE TITLE
when do we need to initializeApp for cross platform

### ISSUE THREAD

**Issue by YasirPanjsheri** [invertase/react-native-firebase#546]
Im sorry for posting this here, but I didn't know where else to ask.
I am confused regarding `Default App`and `Initializing Apps` https://rnfirebase.io/docs/v3.0.*/core/initialize-apps

Im not sure when do we need to do `Initializing Apps` steps. I am building for both the platforms , `Android and IOS` , so if I use the firebase the way it's mentioned in `Default App`, is it enough? or do I need to follow `Initializing Apps` to make it work for both platforms.

**Comment by chrisbianca** [comment]
@YasirPanjsheri You only need to worry about `Initializing Apps` if you need to connect your iOS and Android applications to multiple Firebase projects at once.

In your case, the `Default App` will be just fine.
