### ISSUE TITLE
[🐛] Crashlytics Logs are not sufficiently informative

### ISSUE THREAD

**Issue by JohnEmadNashed** [invertase/react-native-firebase#5461]
## Issue

My Application has a problem of flashing with some users and this is the report coming.
This is a react native application and the crash itself is in the react-native module so I cannot know where the crash is coming from in my application.

<img width="1186" alt="Screen Shot 2021-06-28 at 9 57 27 PM" src="https://user-images.githubusercontent.com/27110712/123696311-e75a2400-d85b-11eb-8e78-6abd93b071fa.png">

---
## App.js 

import crashlytics from "@react-native-firebase/crashlytics";
crashlytics().sendUnsentReports(); in useeffect lifecycle.

## I want Help in

* I want to understand how to get full report of a crash.. where is it coming from in my react-native application ?.. my stack trace..? 
* I want to know where is this log coming from unknown error object Object.
* How to access this object in order to know the details of the crash.

**Comment by mikehardy** [comment]
Hi there, this is not an issue in the project and you have ignored most of the template where we request vital troubleshooting information, so I will close it. Your resolution will come from understanding things, not from a change here.

In an attempt to be helpful and move towards understanding though, I will say that a javascript project goes through multiple possible stages before it executes on a device right?

Let's say perhaps it starts as typescript, tsc processes it to javascript, then babel transforms it, then hermes byte compiles it to an intermediate representation, and it is minified and obfuscated, before it finally executes on the HermesVM in native code.

A crash occurs on the device, and what exactly do you expect to see? A stack trace exactly like the above.

You are tagging your code and saving the sourcemaps from all stages in your compilation prior to release right? So what you do is for each step in your compilation/transpilation chain find the sourcemap for the tagged version of code, and use stack trace de-obfuscators to resolve back to the actual line of code.

Further reading #3760

**Comment by mikehardy** [comment]
Oh - and if it's just logging of information you want, that's addition of API calls to crashlytics to log information prior to a crash - that is project-specific code, you are the best judge of what information to log and when such that if a crash occurs after it helps you solve your problem
