### ISSUE TITLE
Firebase setBackgroundMessageHandler not working in iOS when app is closed

### ISSUE THREAD

**Issue by cheturavi3** [invertase/react-native-firebase#5475]
Firebase setBackgroundMessageHandler not working in iOS when app is closed. It works when the application is in background. Its working in Android when application is closed but not in iOS. 

Below code I'm writing on index.js: 

messaging().setBackgroundMessageHandler(async remoteMessage => {
console.log('Message received', remoteMessage);
});

Please help me as I'm stuck here.

**Comment by mikehardy** [comment]
There are a ton ton ton ton of issues related to the same in our issues list - and you have ignored our entire issue template so I will close this

However I want to be super clear: data-only messages for iOS are not guaranteed by Apple to be delivered and start your app, and if it is force quit (swiped away) the will definitely not be delivered, if the app has just closed it in the background it *might* be delivered by definitely no guarantee.
