### ISSUE TITLE
[🐛] Bug Report Title - CHANGE ME 

### ISSUE THREAD

**Issue by jaswantmandloi** [invertase/react-native-firebase#5479]
const admob =  getFirebaseRoot().admob();
return new InterstitialAd('interstitial', admob, requestId, adUnitId, options);

I have installled the latest version of this module  "@react-native-firebase/admob": "^11.5.0" 
But when i am trying to call "InterstitialAd.createForAdRequest(interstitialId);"

There is some internal error "undefined is not a function "   this is being shown to me. When i tried to identify the issue, I got to know it is above issue "getFirebaseRoot().admob()" admob function is not available there.

Please let me know some fixes if anybody knows.

**Comment by mikehardy** [comment]
Hi there! You have deleted our issue template, where we request all the information we need to offer help
Consequently, we can't offer help.
"null is not an object" in react-native terms almost always means you have not integrated the project correctly though, missing pod install or did install `@react-native-firebase/app` or similar.
