### ISSUE TITLE
.once() behaviour with persistence? What about .keepSynced()?

### ISSUE THREAD

**Issue by DavideValdo** [invertase/react-native-firebase#550]
Will ref.once('value') still try to read from the disk with persistence enabled?
Thanks in advance.

**Comment by chrisbianca** [comment]
@DavideValdo I think you're best off deferring to the native SDK documentation to get a better understanding of how this works:

Android: https://firebase.google.com/docs/database/android/offline-capabilities
iOS: https://firebase.google.com/docs/database/ios/offline-capabilities
