### ISSUE TITLE
[🐛] Social auth signin doesn't trigger onathstatechanged on build release

### ISSUE THREAD

**Issue by Onibenjo** [invertase/react-native-firebase#5508]
## Issue

Describe your issue here

In debug mode, during development, after signing with google, onauhtstatechanged gets triggered and the user gets to have access to the main app but after building for release with `gradlew assembleRelease`, clicking the login button shows the google-select-account popup and after selecting an account, the popup closes and nothing happens.
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 12.0.0
- **`Firebase` module(s) you're using that has the issue:**
  - auth
- **Are you using `TypeScript`?**
  - `Y` & `3.8.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Issues between debug and release are always and forever project-specific problems. The module works in release fine.

I suspect this is a google signin module usage issue even, nothing to do with react-native-firebase. That said, the react-native google sign in module also works fine in release. That module does not have a release mode issue.

You have also largely ignored the template where we request necessary information for troubleshooting.
Strongly suggest watching `adb logcat` unfiltered as you attempt this, but there will be no change in this project as a result of your project's problem, combined with ignoring the issue template, so I will close this
