### ISSUE TITLE
Could Not Invoke RNFirebaseFirestore.documentSet

### ISSUE THREAD

**Issue by phantoxe** [invertase/react-native-firebase#551]
Hi folks... i have a litle problem to do a simple sample to register a document in Firebase...

### Environment

1. Application Target Platform: Android

2. Development Operating System: Windows 10

3. Build Tools: Android SDK

4. React Native version: 0.49

5. RNFirebase Version: Last

6. Firebase Module: RnFirestore

![whatsapp image 2017-10-26 at 16 49 26](https://user-images.githubusercontent.com/29681268/32071338-c0f2f09a-ba6d-11e7-8dcc-8ee3a7790285.jpeg)

**Comment by chrisbianca** [comment]
@phantoxe What does Last version of RNFirebase version mean? Can you give the actual version you're using otherwise we can't help you

**Comment by phantoxe** [comment]
@chrisbianca thanks my friend! "version": "3.0.4" 

Thanks again... i am waiting ASAP...

**Comment by chrisbianca** [comment]
Upgrade to version 3.0.5 - this issue has been fixed there.
