### ISSUE TITLE
Can't navigate when setBackgroundMessageHandler is triggered

### ISSUE THREAD

**Issue by youssefhaitham-callvita** [invertase/react-native-firebase#5510]
### Discussed in https://github.com/invertase/react-native-firebase/discussions/5509

<div type='discussions-op-text'>

<sup>Originally posted by **youssefhaitham-callvita** July 12, 2021</sup>
Hello,

I am trying to navigate to a specific page when a user opens a notification and boots the application. In the React native firebase documentation it used setBackgroundMessageHandler to handle the notification sent but it handles it outside the whole app in the index.js file. 

```
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import messaging from '@react-native-firebase/messaging';
import React from 'react';

messaging().setBackgroundMessageHandler(async remoteMessage => {
 console.log('Message handled in the background!', remoteMessage);
});

function HeadlessCheck({ isHeadless }) {
    if (isHeadless) {
      // App has been launched in the background by iOS, ignore
      return null;
    }
  
    return <App />;
  }

AppRegistry.registerComponent(appName, () => HeadlessCheck);
```

So my question is, how can I navigate to a certain module if the app throw the setBackgroundMessageHandler isn't registered yet?</div>

**Comment by mikehardy** [comment]
Please don't duplicate
Answered: https://github.com/invertase/react-native-firebase/discussions/5509#discussioncomment-994584
