### ISSUE TITLE
Issue with limiting Firestore results

### ISSUE THREAD

**Issue by ryanlanglois** [invertase/react-native-firebase#552]
### Issue

Hi there, bit of a newbie here but I'm trying to figure out why `limit`ing a Firestore collection doesn't seem to work for me. I have a collection of about ~1500 users and I only want to show the first 20 by default. The code shown below is displaying all 1500 results.

Any help would be greatly appreciated! I feel like I must be missing something simple...

#### index.js
```
export default class App extends React.Component {
  constructor() {
    super();
    this.ref = firebase.firestore().collection('users').orderBy('name').limit(20);
    this.unsubscribe = null;
    this.state = {
        textInput: '',
        loading: true,
        users: [],
    };
  }

  componentDidMount() {
    this.unsubscribe = this.ref.onSnapshot(this.onCollectionUpdate)
  }

  componentWillUnmount() {
    this.unsubscribe();
  }

  onCollectionUpdate = (querySnapshot) => {
    const users = [];
    querySnapshot.forEach((doc) => {
      const { name, team } = doc.data();
      users.push({
        key: doc.id,
        doc, // DocumentSnapshot
        name,
        team,
      });
    });
    this.setState({
      users,
      loading: false,
   });
  }

render() {
    if (this.state.loading) {
      return (
        <Text>Loading...</Text>
      );
    }
    return (
        <FlatList
          data={this.state.users}
          renderItem={({item}) => <Text>{item.name}</Text>}
        />
    );
  }
```

#### Podfile
```
target 'RNFirebaseStarter' do
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
end
```

### Environment

1. Application Target Platform:  iOS

2. Development Operating System: macOS Sierra 10.12.6

3. Build Tools: 

4. React Native version: 0.49.3

5. RNFirebase Version:  3.0.4

6. Firebase Module: Firestore

**Comment by chrisbianca** [comment]
@ryanlanglois Thanks for this, we'll do a bit of digging and check it's not an underlying issue our end.  Have you tried Android at all?

**Comment by ryanlanglois** [comment]
@chrisbianca just iOS so far, but I'll give Android a shot.

**Comment by melvinxie** [comment]
I got the same problem. limit doesn't work on iOS at all. It still returns all results.

**Comment by nimerfarahty** [comment]
i got also same issue on IOS  RN 0.49.3 
i have test it on android and its works fine

**Comment by chris-divvito** [comment]
Same issue for us, just on iOS, android works fine. In applyOptions method in RNFirebaseFirestoreCollectionReference the limit option is not handled

**Comment by chrisbianca** [comment]
@chris-divvito Good spot.  I've just added this in and will get a release out later today.

**Comment by peterdivvito** [comment]
Hi @chrisbianca, I've just created a pull request to fix this as well as some other issues I've been having. I tried out the change you made for limit and it threw an error.

**Comment by chrisbianca** [comment]
@peterdivvito Thanks for the PR - I'll take a look through it later today and see what can be brought over
