### ISSUE TITLE
[IOS] First time generated FCM token not working on iPad

### ISSUE THREAD

**Issue by binitgurzu** [invertase/react-native-firebase#5533]
**Issue only persist on iPad, it's work fine on iPhone and Android devices** 

When the user installs the app and after that app starts and a user logins the first time, I get a new fcm token with messaging().getToken() and send the token to my server, and after that if I send a notification from the admin panel notification not triggering.  but if I log-out from the app and again re-login to the same user notification starts triggering every time.

However, the issue only persists on the iPad. it's working fine on iPhone and Android devices. In iPhone and Android devices notification starts triggering on the first login.

Inside Main **App.js** (which is for handling first time app loads)

```
  useEffect(() => {
    const { setPushToken } = AUTH_ACTIONS;

    async function getAndStorePushToken() {
      const enabled = await messaging().hasPermission();
      let finalStatus = enabled > 0;

      if (!finalStatus) {
        const status = await reqPermissionForPN();
        finalStatus = status;
      }

      if (!finalStatus) {
        return;
      }

      const fcmToken = await messaging().getToken();
  
      dispatch({ type: setPushToken, payload: fcmToken });
    }

    if (!pushToken) {
      getAndStorePushToken();
    }
  }, [dispatch, reqPermissionForPN, pushToken]);

```

```
useEffect(() => {
    const { setPushToken } = AUTH_ACTIONS;

    let unsubscribeRefreshToken;

    unsubscribeRefreshToken = messaging().onTokenRefresh(async (fcmToken) => {
      // TODO: Update user push token with api call
      dispatch({ type: setPushToken, payload: fcmToken });
    });

    return unsubscribeRefreshToken;
  }, [dispatch]);
```

**At the time user logout** inside handleLogout function

```
const handleLogOut = async () => {
    const { logOut } = AUTH_ACTIONS;
  
    api('DELETE', `/logout?token=${user?.pushToken}`);

  
    await messaging().deleteToken(undefined, '*');

    dispatch({ type: logOut });
  };

```

**My working environment:- **

```
"@react-native-firebase/app": "^8.4.5",
"@react-native-firebase/messaging": "^7.9.0",
"react": "16.13.1",
"react-native": "0.63.2",
```

**Comment by mikehardy** [comment]
There is very little point in spending any time at all on older versions. Please update to current stable versions of all the software involved and let me know if it still reproduces. We are on 12.2.0 here at this point, the changelog has details on the breaking changes for each major version so forward-porting should not be too much of a chore
