### ISSUE TITLE
firebase.auth().signInWithCredentials(obj) does not return User

### ISSUE THREAD

**Issue by evgeni-tsn** [invertase/react-native-firebase#555]
### Issue
I have this code. I am trying to sign in with google account using signInWithCredentials method that suppose to return me the logged User but the **u** object in the then of the method is empty every time. The same logic works well in v2 of the library. I look up at all breaking changes but I did not find anything related to my issue. Can someone assist me please? 👍 
```js
GoogleSignin.signIn()
    .then((user) => {
      let credential = {
        token: user.idToken,
        secret: user.serverAuthCode,
        provider: 'google',
        providerId: 'google'
      }
      console.log('creds', credential)
      return firebase.auth().signInWithCredential(credential)
          .then(u => { console.log(u); return u })
          .catch(error => error)
    })
    .catch((error) => {
      console.warn('WRONG SIGNIN', error)
      return error
    })
```

### Environment
4. React Native version: 0.49.3
5. RNFirebase Version: 3.0.5
6. Firebase Module: auth

**Comment by Salakar** [comment]
@evgeni-tsn your `provider` value is incorrect, would recommend switching to using the built in credential generators:

```javascript
const { idToken, serverAuthCode } = user;
const credential = firebase.auth.GoogleAuthProvider.credential(idToken, serverAuthCode);

// ...
firebase.auth().signInWithCredential(credential)
// ...

``
