### ISSUE TITLE
[🐛] Possible invalid dependency of iid

### ISSUE THREAD

**Issue by ssuchanowski** [invertase/react-native-firebase#5550]
## Issue

There is a possible issue with dependencies. When I install all current versions (12.3.0 for all besides iid - 11.5.0) I get in pods an old lib version.

<img width="370" alt="Screenshot 2021-07-27 at 19 54 56" src="https://user-images.githubusercontent.com/1038270/127204732-dd56e0c5-910c-4fe2-a287-5c65a6414154.png">

#### `package.json`:

```json
    "@react-native-firebase/analytics": "^12.3.0",
    "@react-native-firebase/app": "^12.3.0",
    "@react-native-firebase/iid": "^11.5.0",
    "@react-native-firebase/messaging": "^12.3.0",
    "@react-native-firebase/perf": "^12.3.0",
    "@react-native-firebase/remote-config": "^12.3.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "perf_auto_collection_enabled": true
  }
}
```

### iOS

<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

plugin 'cocoapods-acknowledgements', :settings_bundle => true, :targets => ['APP_TARGET']

$RNFirebaseAsStaticFramework = true
$RNFirebaseAnalyticsWithoutAdIdSupport = true

target 'APP_TARGET' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
```

**Comment by mikehardy** [comment]
IID is no longer a valid dependency - please read the changelog carefully to make sure you've got all the migration items handled - I did my best to include the actual changes needed here - https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md#breaking-changes (note this URL may move but it's valid at the moment, it's the breaking section for the v12 upgrade where IID went away)
