### ISSUE TITLE
[🐛] Bug Report Title - Banner overflow

### ISSUE THREAD

**Issue by rochapablo** [invertase/react-native-firebase#5567]
## Issue

Sometimes the banner overflow the container element (https://youtu.be/gNrEpp4r7PA).

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/admob": "^11.5.0",
"@react-native-firebase/app": "^12.4.0",
"react": "16.9.0",
"react-native": "0.64.1",
```

#### `code`:

```js
const style = { alignItems: 'center', justifyContent: 'center', width: position.pixels.w + 18, height: position.pixels.h + 18, overflow: 'hidden', padding: 18 };
<View style={{...props.style, ...style }}>
        <BannerAd
          // unitId={__DEV__ ? TestIds.BANNER : `/75894840/${position.unit}`}
          unitId={`/75894840/${position.unit}`}
          size={position.size || 'BANNER'}
          onAdFailedToLoad={error => onAdFailedToLoad(props, position, error)}
          requestOptions={{
            contentUrl: 'https://tudoradio.com'
          }}
        />
      </View>
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Admob is no longer supported here - #5329
