### ISSUE TITLE
Crash when signInWithPhoneNumber

### ISSUE THREAD

**Issue by ararog** [invertase/react-native-firebase#557]
I'm trying to use signinWithPhoneNumber, but it is always crashing with the following message:

Please register custom URL scheme 'com.googleusercontent.apps.711281515158-jccuuigsa4851bub2f1dfo5qcfihd469' in the app's Info.plist file.' was thrown while invoking signInWithPhoneNumber on target RNFirebaseAuth with params (
    "__FIRAPP_DEFAULT",
    2392159312,
    2538,
    2539
)

I followed all steps to configure RNFirebase on the project, from npm package to XCode stuff. What I'm doing wrong?

### Environment

1. Application Target Platform: 
iOS

2. Development Operating System: 
Mac OS High Sierra

3. Build Tools: 
XCode 9

4. React Native version: 
0.49.3

5. RNFirebase Version: 
3.0.5

6. Firebase Module: 
auth

**Comment by Salakar** [comment]
@ararog you need to follow steps 1 & 2 from the official firebase ios docs to add the url schema.

Link: https://firebase.google.com/docs/auth/ios/phone-auth

**Comment by ararog** [comment]
@Salakar I would like to find what are you saying, but after take a look on firebase ios docs I see NO reference to url schema on Info.plist, no reference to url schemas at all, I'm assuming for just signin I don't need setup APNs or push notifications. An for simulator I'm assuming it shouldn't crash, right? Just do nothing, but not crash.

**Comment by gusgard** [comment]
If it helps, when enabling Auth, is required to download the GoogleService-info again.

**Comment by jmhuret** [comment]
Thank you @gusgard, that's not an obvious thing to do and it was just what I needed.

**Comment by lucasfernandes** [comment]
Hey guys, sorry reopening this thread, but I've made the steps 1 and 2 to enable silent notifications, but my react native app is crashing asking for configure the URL link is need for recaptcha mode. when I configure this url, everything runs fine, but in the middle of the process, firebase still opening the Verifying If you're not a robot.

I definitely need help with that...

**Comment by joshbedo** [comment]
Kind of stuck on this, just tried to setup the phone auth and getting 'Please register custom url scheme'. What should i do?

**Comment by mypark** [comment]
I fixed it by following the steps in #2 to enable recaptcha verification, specifically:

```
Add custom URL schemes to your Xcode project:
Open your project configuration: double-click the project name in the left tree view. Select your app from the TARGETS section, then select the Info tab, and expand the URL Types section.
Click the + button, and add a URL scheme for your reversed client ID. To find this value, open the GoogleService-Info.plist configuration file, and look for the REVERSED_CLIENT_ID key. Copy the value of that key, and paste it into the URL Schemes box on the configuration page. Leave the other fields blank.
When completed, your config should look something similar to the following (but with your application-specific values):
```

**Comment by tevatahiti** [comment]
@lucasfernandes I was also surprise there is no guide for that! I just spent the whole afternoon on this silent notifications not working and reCaptcha always showing when authenticating with phone number... I think that should be part of a guide on Medium.com lol

There is more stuff that needs to be done actually and you get it from reading that blog: https://firebase.googleblog.com/2017/01/debugging-firebase-cloud-messaging-on.html

![capture d ecran 2018-04-12 a 18 12 20](https://user-images.githubusercontent.com/10006390/38716619-8a8de67e-3e7d-11e8-902c-be8148e3b266.png)


The additional part that I have missed that helped me to solved this: 
1) Install Cloud Messaging Module from RNFirebase
https://rnfirebase.io/docs/v4.0.x/messaging/ios
2) Install Notifications Module in RNFirebase
https://rnfirebase.io/docs/v4.0.x/notifications/ios

Hope it will help someone else

**Comment by mypark** [comment]
@tevatahiti just tried your suggestion and tried 2. install notifications module and I get the error on #import "RNFirebaseNotifications.h", file not found.  I was able to get FCM working, but didn't see an additional pod install for notifications specifically.  Am I missing something?

**Comment by tevatahiti** [comment]
@mypark do you have a version of your app already working with ReCaptcha?
If yes then once you installed Cloud Messaging module and Notifications module:
- xcode : clean derivated data
- xcode : clean project
- in pod folder : pod update
- sometimes it also helps to clean everything and reboot your mac
Hope it can help

**Comment by berpcor** [comment]
Besides, no need to have a real iOS device for testing phone authentication. You just need to set test phone numbers and code in firebase settings.

**Comment by LBroy** [comment]
@mypark save my day

**Comment by Bilal-Abdeen** [comment]
If you are not familiar with Xcode (like me) and struggled to find where to type the URL of the package...
1> Double-click on the project's file `<proj_name>/ios/<proj_name>.xcworkspace` This should open the project in Xcode
2>  `Xcode` > `File` > `Add Packages...` 
3> On the top-right corner, there is a `search field`, type the URL: `https://github.com/firebase/firebase-ios-sdk.git`
4> Select `Firebase-ios-sdk`
5> Select `Firebase Auth`
