### ISSUE TITLE
[🐛] FCM token does not refresh after deleting token via `deleteToken()` on iOS

### ISSUE THREAD

**Issue by helenaford** [invertase/react-native-firebase#5570]
Prior to the Firebase Messaging version before Installations, the FCM token would delete and refresh on iOS. Since installations, `deleteToken` has no effect. Same in FlutterFire. 

## Issue

From debugging, after calling `[FIRInstallations installations] deleteWithCompletion` once, `deleteToken` will start to refresh the token

```
  [[FIRInstallations installations] deleteWithCompletion:^(NSError * _Nullable error) {
    if (error) {
      [RNFBSharedUtils rejectPromiseWithNSError:reject error:error];
    } else {
      resolve([NSNull null]);
    }
  }];
```

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Very interesting! Installations is one of the new-ish modules (in the same cohort as App Distribution I think) without a lot of APIs that we are neither implementing directly nor exposing.

If I understand your diagnose correctly, it appears that in our Messaging module (where we do expose `deleteToken` we should actually be calling the installations native API - either in addition to the Messaging API or simply in place of it?

It appears you already have a test bench for this already set up based on your comment - if you PR this I can merge+release ASAP

**Comment by helenaford** [comment]
@mikehardy p/r pushed up. Thanks for responding so quickly to this issue, as you know it causes a lot of problems in apps.

I've opened up an issue on the native iOS sdk repo to see if we can have some clarity on why this fix is needed. I don't know if it's due to the wrong properties sent to the native `deleteToken` method or some other issue deeper in the sdk

**Comment by henriquedamota** [comment]
Hi guys! Is there an expectation to merge this bugfix?

**Comment by mikehardy** [comment]
@henriquedamota we are waiting on feedback upstream. However, there is never anything stopping you from using patch-package to integrate pull requests easily in your app - we auto-generate a set of patch-packages on every PR, you may see it in the related checks on the related PR in the artifacts section of the patches CI task: https://github.com/invertase/react-native-firebase/pull/5571/checks?check_run_id=3243266945

**Comment by mikehardy** [comment]
react-native-firebase 12.7.0 incorporates firebase-ios-sdk 8.6.0, where `messaging.deleteToken()` *should* just work.

**I would love to hear how this new release works, on real iOS devices** ! Please report!

Alternatively, react-native-firebase 12.7.0 also includes the new `@react-native-firebase/installations` package which directly exposes the API @helenaford was testing with here, `installations.delete()` - it has side effects in that it performs a full backend delete of the app installation so you want to get a token quickly after for things to continue working, but now you can call it directly if `messaging.deleteToken` continues to behave poorly

We will likely close this PR but we really want to hear feedback from someone that tries the new release
