### ISSUE TITLE
Crash Report: RCTFatalException: Unhandled JS Exception: TypeError: undefined is not an object (evaluating 'l.replace')

### ISSUE THREAD

**Issue by chohra-m** [invertase/react-native-firebase#5573]
Hello everyone,

I am getting this error at Firebase Crashlytics, which doesn't show much about the detail of the error and it is crashing the app. I search in the whole codebase for "l.replace" line but didn't found any.

You will find attached a screenshot of the error, it is happening for both Android and IOS

using these packages:

    "react-native": "0.64.0",
    "react-native-branch": "^5.0.3",
    "react": "17.0.1",
    "@react-navigation/bottom-tabs": "^5.11.8",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "@react-native-firebase/analytics": "^11.5.0",
    "@react-native-firebase/app": "^11.5.0",
    "@react-native-firebase/crashlytics": "^11.5.0",
    "react-native-gesture-handler": "^1.10.3",

<img width="1126" alt="Screenshot 2021-08-05 at 23 49 09" src="https://user-images.githubusercontent.com/79843303/128425722-7b3f82ec-1529-4829-b0fc-250c7d714c0a.png">
<img width="1107" alt="Screenshot 2021-08-05 at 23 49 23" src="https://user-images.githubusercontent.com/79843303/128425743-573035ad-c2ab-4c51-8781-a212fe4812d0.png">

**Comment by mikehardy** [comment]
Hi there!
This is a crashlytics report, but it has nothing to do with firebase or react-native-firebase.
It says in the message "unhandled JS exception" then goes on to describe the problem with a javascript stack trace.
If you take the same commit that generated the build corresponding to this release, and work your way through symbolicating this stack to your code from the build, you'll find your project error
