### ISSUE TITLE
'auth_state_changed' is not a supported event type for RNFirebaseAuth

### ISSUE THREAD

**Issue by calclavia** [invertase/react-native-firebase#558]
![simulator screen shot - iphone 6 - 2017-10-28 at 00 11 10](https://user-images.githubusercontent.com/1828968/32132204-88fc9ad0-bb74-11e7-8791-6dd8c28de287.png)

### Issue

Upon app launch, I receive this error. I've previously had React Native Firebase working in v2 with React Native 0.43. After the React Native and RNFirebase upgrade I've been receiving this error.

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode

4. React Native version: 0.49.5

5. RNFirebase Version: git+https://github.com/invertase/react-native-firebase.git#v3.0.x
Using this version because of https://github.com/invertase/react-native-firebase/issues/549

6. Firebase Module: N/A

**Comment by Salakar** [comment]
@calclavia you need to rebuild the native part of your app after updating otherwise it will be out of sync with the new JS code.
