### ISSUE TITLE
MESSAGING: getInitialNotification() promise yielding undefined 

### ISSUE THREAD

**Issue by ashour** [invertase/react-native-firebase#559]
Hello, hope this finds you well. Love this project, and I appreciate the work going into it :)

I'm getting `undefined` in the promise resolution of `getInitialNotification()`.

1. Target Platform : iOS & Android
1. Development Operating System: macOS High Sierra 10.13
1. Build tools: Xcode 9.0.1, Android Studio 2.3.3
1. React Native version 0.49.3
1. RNFirebase Version 3.0.5
1. Firebase Module: Cloud Messaging

> Remote notifications have been configured and both iOS and Android devices are
> receiving notifications triggered from the Firebase console after my app has 
> been installed.

## Scenarios

There are four scenarios that I'm targetting and have tested against. When a remote notification is received and...

1. iOS - app was in background
2. iOS - app was not running (dead)
3. Android - app was in background
4. Android - app was not running (dead)

Here's my root component code:

```
import React, { Component } from 'react'
import {
  // ...
  AppState,
} from 'react-native'
import firebase from 'react-native-firebase'

const messaging = firebase.messaging()

export default class App extends Component<{}> {
    state = {
        appState: AppState.currentState,
    }

    componentDidMount() {
        AppState.addEventListener('change', this._handleAppStateChange)

        messaging.requestPermissions()

        this._logNextNotification('componentDidMount')
    }

    _handleAppStateChange = (nextAppState) => {
        if (this.state.appState.match(/inactive|background/) && nextAppState === 'active') {
          this._logNextNotification('_handleAppStateChange (coming to foreground)')
        }
        this.setState({appState: nextAppState})
     }

    _logNextNotification(tag = 'NO_TAG') {
        messaging
            .getInitialNotification()
            .then(payload => console.log(tag, payload))
    }

```

### iOS

I was getting a console log of `undefined` for both background and dead app scenarios.
I did some digging and managed to get the background scenario working when I simply added a class variable called `lastNotificationInfo` to `RNFirebaseMessaging` and set it to the notification's info `NSDictionary` (often named `data` in the code) in the following `RNFirebaseMessaging` methods:

- `+ (void)didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo`
- `+ (void)didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo fetchCompletionHandler:(nonnull RCTRemoteNotificationCallback)completionHandler`
- `- (void)handleNotificationReceived:(NSNotification *)notification`

I then updated the exported `getInitialNotification:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject` to look like this:

```
RCT_EXPORT_METHOD(getInitialNotification:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject){
    UILocalNotification *localUserInfo = [self bridge].launchOptions[UIApplicationLaunchOptionsLocalNotificationKey];
    if (localUserInfo) {
        resolve([[localUserInfo userInfo] copy]);
    } else {
        resolve(RNFirebaseMessaging.lastNotificationInfo);
        
//        resolve([[self bridge].launchOptions[UIApplicationLaunchOptionsRemoteNotificationKey] copy]);
    }
}
``` 

Notice that I just used the new static variable, `lastNotificationInfo`, instead of
calling the bridge.

This got `getInitialNotification()` working in the JavaScript when the iOS app came to the
foreground from the background. 

As for when the iOS app was dead and came to the foreground, I still keep getting `undefined` from the `getInitialNotification()` promise resolution at this point.

### Android

Android is exhibiting some bizarre behaviour.

On a fresh app install, _whether a remote notification has been sent or not_, the
`getInitialNotification()` promise will yield an object that effectively looks like this:

```
{
	fcm: {
		action: "android.intent.action.MAIN"
	},
	opened_from_tray: true
}
```

Notice that whether a notification has been sent or not, there is no payload in the object.

Sometimes, after sending a few notifications (contiaining the same data), I did see the 
payload in the yielded object. However, once that happened, if I sent notifications with 
_new data_, I still kept seeing the old data in the new logs. It's almost like there's
some kind of caching here.

I admit I haven't looked at the Android / Java code at all at this point. I've been
working on this for a few hours and just wanted to log my findings before taking a break.

> This issue may be a duplicate of [#281](https://github.com/invertase/react-native-firebase/issues/281). However, I'm tackling both Android and iOS here, whereas the older issue only tackled iOS. Also, that issue looks a bit dead at this point, so I thought it would be a good idea to log a new one.

Happy to continue working on this. Thought it would be good to get more heads thinking on it.

**Comment by chrisbianca** [comment]
We're aware of lots of issues with notifications and will be addressing them all as part of the v3.2.0 release stream.  Please see https://github.com/invertase/react-native-firebase/issues/595 for updates.

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)

**Comment by appli-intramuros** [comment]
Hello,

This issue still occurs with the v4 release.

Here is my scenario:
I am trying to listen for a remote notification being opened/clicked when the app is in the background (iOS or Android).

- I'm using Firebase Notification Console to send a test notification. 
- react native version 0.54.2
- RNFirebase Version v4.0.0-rc.2 
- Target Platform : iOS & Android 
 

I followed the documentation https://rnfirebase.io/docs/v4.0.x/notifications/receiving-notifications by adding:

```
componentDidMount() {
    this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen: NotificationOpen) => {
        // Get the action triggered by the notification being opened
        const action = notificationOpen.action;
        // Get information about the notification that was opened
        const notification: Notification = notificationOpen.notification;
        console.log(notificationOpen);
    });
}
```

But when I click the notification, the result of the console.log(notificationOpen); is (**title and body are undefined**):

```
{action: 'android.intent.action.MAIN',
 notification: 
  { _android: 
     { _notification: [Circular],
       _actions: [],
       _people: [],
       _smallIcon: { icon: 'ic_launcher' } },
    _ios: { _notification: [Circular], _attachments: [] },
    _body: undefined,
    _data: {},
    _notificationId: '0:1521836727179578%ff23221dff23221d',
    _sound: undefined,
    _subtitle: undefined,
    _title: undefined },
 results: undefined }
```

On the other side, when the app is in the foreground, the notification is correctly handled by the following code, and the notification contains the correct data:

```
this.notificationListener = firebase.notifications().onNotification((notification: Notification) => {
    // Process your notification as required
    console.log(notification);
});
```

console.log(notification) returns :

```
{ _android: 
    { _notification: [Circular],
      _actions: [],
      _people: [],
      _smallIcon: { icon: 'ic_launcher' } },
   _ios: { _notification: [Circular], _attachments: [] },
   _body: '**My body test**',
   _data: {},
   _notificationId: '0:1521910860494002%ff23221dff23221d',
   _sound: undefined,
   _subtitle: undefined,
   _title: '**My title test**' }
```

Can you help me ? 

thank you very much.

**Comment by chrisbianca** [comment]
I've just been looking at the onNotificationOpened issue and it seems that this is unfortunately a restriction of the Android operating system. When the notification is opened, the only information supplied in `onNewIntent` is:
```
{
  google.sent_time=1522149084674,
  google.ttl=3600,
  from=305229645282, 
  key1=data1,
  key2=data2, 
  google.message_id=0:1522149084678578%81c98c5381c98c53,
  collapse_key=com.reactnativefirebasedemo
}
```
where key1 and key2 are the data parts of my notification.

Unfortunately, there's nothing we can do.  You'll have to use the data part of the notification for this information in this instance.

**Comment by eredinbg** [comment]
Hello.
This is a great project and everything works well except one thing.
I'm getting null in the promise resolution of getInitialNotification() if my app is opened by clicking on push notification. It happens on iOS only.

1. Target Platform: iOS
2. Development Operating System: macOS High Sierra 10.13
3. Build tools: Xcode 9.3
4. React Native version: expo fork of 0.52.0
5. RNFirebase Version: 4.0.0
6. Firebase Module: Notifications

**Comment by rayj10** [comment]
@chrisbianca Hi, I'm facing this particular problem and I'm pretty new to the whole remote notification stuff, would you mind elaborating more on the usage of this 'data' property mentioned on the docs and how do you get that `onNewIntent` object?

I tried making an object like so from the server side to be sent:

{
title: 'blah',
body: 'foo',
data: {
  test: 'data1',
  test2: 'data2'
}
}

But everything just becomes undefined when I tried accessing it from `getInitialNotification()`.
accessing it from `onNotification()` gives me the desired data.

Thanks in advance! :)

**Comment by appli-intramuros** [comment]
Hi @Johncy1997 
It is a limitation of Android (as explained by @chrisbianca ).
The doc says :
`On Android, unfortunately there is no way to access the title and body of an opened remote notification. You can use the data part of the remote notification to supply this information if it's required.`

So I manually set title and body in the data payload param when I create the notification.

https://rnfirebase.io/docs/v5.x.x/notifications/receiving-notifications#4)-Listen-for-a-Notification-being-opened

**Comment by Johncy1997** [comment]
@appli-intramuros i had never accessed body/title part.
```
static async handleNotification(notification)
    {       
        var notificationData;
        notificationData = notification.data;
        //Order_details data
        /**
         * "data":{
            "order_status":4,
            "Order_id":100009
            }
         */
        if(notificationData.order_status==="1"){
            NotificationHandler.getInstance().routeName = routeNames.OrdersStack.orderConfirmation;
            NotificationHandler.getInstance().stackName = routeNames.MainTab.orders;
        }
        else if(notificationData.order_status==="2"){
            NotificationHandler.getInstance().routeName = routeNames.OrdersStack.orderPaymentPreview;
            NotificationHandler.getInstance().stackName = routeNames.MainTab.orders;
        }
        else{
            NotificationHandler.getInstance().routeName = routeNames.OrdersStack.orderDetail;
            NotificationHandler.getInstance().stackName = routeNames.MainTab.orders;
        }
        NotificationHandler.getInstance().isFromPushNotification=true
        NotificationHandler.getInstance().notificationData={item:notificationData};
    }```
Still it navigating to home page

**Comment by appli-intramuros** [comment]
@Johncy1997  how do you send the fcm message ? How do you send message from FCM ? Are you sure the message sent by FCM contains your data param ?

**Comment by appli-intramuros** [comment]
Here is my own code:
```
firebase.notifications().getInitialNotification().then((notificationOpen: NotificationOpened) => {
      if (notificationOpen) {
        // Get information about the notification that was opened
        const notification: Notification = notificationOpen.notification;
        if (notification._notificationId) {
          console.log('notificationID=' + notification._notificationId);
          firebase.notifications().removeDeliveredNotification(notification._notificationId);
        }
        this._processNotification(notification)
      }
    });
```
I can reach data payload from 'notification' object.

Try to remove the 'async' keyword ?!

**Comment by phonganhhung9xtb** [comment]
Hi @appli-intramuros , when iOS app killed, if i tap on notification app crash immediate and getInitialNotification not fire. Can you tell my mistake? my code below:
            firebase.notifications().getInitialNotification()
              .then(notificationOpen => {
                if (notificationOpen) {
                  Logger.log(`onNotificationOpened FCM: ${notificationOpen ? JSON.stringify(notificationOpen) : notificationOpen}`)
                  let link = findLink(notificationOpen);
                  link && showDetail(Navigation, { link }, true)
                }
              });
