### ISSUE TITLE
[🐛] Bug Report Title - Native module cannot be null

### ISSUE THREAD

**Issue by vinhtran6921** [invertase/react-native-firebase#5602]
I already did all steps install as document but when I `import messaging from '@react-native-firebase/messaging';` 
It got error Native module cannot be null.
Pls give me some advices for this

```
    "react-native": "0.59.1"
    "@react-native-firebase/app": "11.5.0",
    "@react-native-firebase/crashlytics": "11.5.0",
    "@react-native-firebase/messaging": "11.5.0",
```
**My podfile**
```
  use_frameworks!
    pod 'FacebookCore'
    pod 'FBSDKCoreKit','5.11.1'
    pod 'FacebookLogin'
    pod 'FBSDKLoginKit','5.11.1'
    pod 'Bolts', '1.9'
    pod 'Fabric','1.9.0'
    pod 'Crashlytics','3.12.0'
    pod 'AWSSNS','2.9.3'
    pod 'GoogleMaps','3.0.3'
    pod 'GoogleAnalytics','3.17.0'
    pod 'GoogleIDFASupport','3.14.0'
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/InAppMessaging'
    pod 'Firebase/Messaging'
    pod 'TrustKit'
end

```
![image](https://user-images.githubusercontent.com/53859772/129603025-c9f83e37-cc22-4d09-ba35-a564b8e4ef82.png)
![IMG_2714](https://user-images.githubusercontent.com/53859772/129602716-966dc3dc-7ae7-4548-a72f-de911931c309.PNG)

**Comment by mikehardy** [comment]
> "react-native": "0.59.1"

This will not be supported any longer - you are on your own if you are using react-native versions this old, without auto-linking.
I used to have a demonstration of it but I stopped even trying 2 years ago https://github.com/mikehardy/rnfbdemo/commits/cf1cdeddf82b78d3589d00a75f12be85f0841263/make-demo-rn59.sh

Please use react-native 0.64.2 (current stable)   as the basis for any new projects

If you simply cannot, for some reason, then the only way to possibly get help is to put a complete reproduction of your problem up as a github repo and ask on stackoverflow for general help https://stackoverflow.com/help/minimal-reproducible-example

Here is how you would you integrate it using current react native https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh
