### ISSUE TITLE
Apple rejection on usage of UIWebview due to react-native-twitter-signin 

### ISSUE THREAD

**Issue by Stas-Buzunko** [invertase/react-native-firebase#5623]
## Documentation Feedback

Using https://github.com/GoldenOwlAsia/react-native-twitter-signin for twitter auth results in app being rejected due to https://developer.apple.com/documentation/uikit/uiwebview

https://github.com/GoldenOwlAsia/react-native-twitter-signin/issues/151
https://github.com/GoldenOwlAsia/react-native-twitter-signin/issues/158
https://github.com/GoldenOwlAsia/react-native-twitter-signin/pull/159

And the only workaround is to manually edit podspec in node_modules which is quite crazy.

So i think docs should at least mention issue with react-native-twitter-signin or better suggest another library that is maintained

**Comment by mikehardy** [comment]
Hi there!
That's an external library, so there's really not much we can do.

Here's what I can concretely recommend, that's in our control:

1) changes in node_modules is not quite crazy, it's actually quite normal. What you need are better tools, this is the one: https://github.com/ds300/patch-package - makes it trivial, and safe to do node_modules work when needed, like when you are dealing with urgent issues on abandon-ware
2) a PR here that points to a twitter library that's maintained - if you can find a library that's maintained, or fork that one and maintain it, then post a PR to the docs here that would help the community

Beyond that, I'm not sure what's actionable here. It's unfortunate, but maintainership in open source ebbs and flows, and it is the opposite of control...
