### ISSUE TITLE
How we add a custom sound in react-native ios

### ISSUE THREAD

**Issue by arjundalal** [invertase/react-native-firebase#5624]
Hello Team,
i want to play custom sound when we got notification in IOS.
can any one help me to do that?

**This is my code in React Native ios**
<img width="645" alt="Screenshot 2021-08-20 at 10 53 59 AM" src="https://user-images.githubusercontent.com/54262572/130183707-548b3619-67f2-44ef-86ce-36d311183a39.png">

**This is an Xcode setting**
<img width="278" alt="Screenshot 2021-08-20 at 10 55 15 AM" src="https://user-images.githubusercontent.com/54262572/130183841-02dec7e6-6906-400b-b7d0-8204018a4fec.png">

please help me to sort this issue
Thanks in advance.

**Comment by mikehardy** [comment]
It's documented I believe, https://rnfirebase.io/messaging/notifications#android-features

**Comment by mikehardy** [comment]
Note iOS features are right next to it
