### ISSUE TITLE
Error with @react-native-firebase/auth and Expo: "does not contain a valid config plugin"

### ISSUE THREAD

**Issue by Madhav-Malhotra** [invertase/react-native-firebase#5629]
I'm trying to add `@react-native-firebase/auth` to a standard Expo template. I have followed all instructions in the documentation [here](https://rnfirebase.io/#installation-1). But I get this error: 
```
Package "@react-native-firebase/auth" does not contain a valid config plugin.
Learn more: https://docs.expo.io/guides/config-plugins/#creating-a-plugin

Cannot use import statement outside a module
```

### Steps to Reproduce
1. Install Expo CLI and initialise a template project. When it asks for the type of template, just hit Enter to select the default Javascript app with one screen.
```
npm i -g expo
expo init my-project
cd ./my-project
```

2. Install @react-native-firebase/app and @react-native-firebase/auth
`npm i @react-native-firebase/app @react-native-firebase/auth`

3. Create a Firebase project and add an Android app and an IOS app. Download config files for both (`google-services.json` and `GoogleService-Info.plist`). Place these files in the root folder (`./my-project`)

4. Add the specified app.json configuration from the [documentation](https://rnfirebase.io/#installation-1).
```
{
  "expo": {
    "android": {
      "googleServicesFile": "./google-services.json"
    },
    "ios": {
      "googleServicesFile": "./GoogleService-Info.plist"
    },
    "plugins": [
      "@react-native-firebase/app",
      "@react-native-firebase/auth"
    ]
  }
}
```

5. Prebuild the app, starting with Android. 
`expo run:android`

You should see the error pop up. 
```
Package "@react-native-firebase/auth" does not contain a valid config plugin.
Learn more: https://docs.expo.io/guides/config-plugins/#creating-a-plugin

Cannot use import statement outside a module
```

-----------------------------------------
# Here are my package versions
Package.json
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-firebase/app": "^12.7.1",
    "@react-native-firebase/auth": "^12.7.1",
    "expo": "~42.0.1",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0"
  },
  "private": true
}
```
app.json
```
{
  "expo": {
    "name": "sprint-tracker",
    "slug": "sprint-tracker",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "googleServicesFile": "./GoogleService-Info.plist"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "googleServicesFile": "./google-services.json"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      "@react-native-firebase/app",
      "@react-native-firebase/auth"
    ]
  }
}
```
I have `node v14.17.4`
# What I've tried to debug
- I've tried downgrading `@react-native-firebase/app` and `@react-native-firebase/app` to `^12.6.1`
- I've tried deleting the entire `./my-project` folder and initialising a new app
- I also saw the same error message in a [forum](https://gitmemory.com/issue/mrousavy/react-native-vision-camera/269/886833408) about `react-native-vision-camera`. Someone commented how there was an issue with Expo 41 and 42. It said to modify the 'user podfile'. I'm just trying react-native-firebase for the first time, so I don't understand what they mean :/

**Comment by mikehardy** [comment]
Hi there, Expo support has been contributed by the community, if auth needs a config plugin and doesn't have one, then you will either need to make one (like so #5480), wait until someone does, or use a different workflow.

I wasn't under the impression that auth needed a config plugin though? Does it @barthap ?

**Comment by barthap** [comment]
As far as I know, the Auth module does not need any custom installation steps. It implies that it doesn't need config plugin to work with Expo.

According to the [docs](https://rnfirebase.io/#expo):

> Config plugins are only required for React Native Firebase modules, which require custom native installation steps - e.g. modifying the Xcode project, Podfile, build.gradle, AndroidManifest.xml etc. Packages without native steps required will work out of the box.

Just remove the `auth` from plugins list in `app.json` and you should be OK.

**Comment by Madhav-Malhotra** [comment]
@mikehardy This works, thank you! Quick question: which of the react-native-firebase modules do we need to add to plugins in `app.json`? I saw these ones in the [documentation](https://rnfirebase.io/#installation-1)
- `@react-native-firebase/app`
- `@react-native-firebase/perf`
- `@react-native-firebase/crashlytics`

**Comment by mikehardy** [comment]
Just those one for normal usage. Basically, if you read in the instructions that you need to add something in AppDelegate.m or build.gradle, it needs a plugin. I *just* added the App Check module here, and for debug/CI only you may wish to add something in AppDelegate but as it's new and Expo has been very helpfully contributed by @barthap before App Check existed, it does not have a plugin yet.

**Comment by danieldanielecki** [comment]
> As far as I know, the Auth module does not need any custom installation steps. It implies that it doesn't need config plugin to work with Expo.
> 
> According to the [docs](https://rnfirebase.io/#expo):
> 
> > Config plugins are only required for React Native Firebase modules, which require custom native installation steps - e.g. modifying the Xcode project, Podfile, build.gradle, AndroidManifest.xml etc. Packages without native steps required will work out of the box.
> 
> Just remove the `auth` from plugins list in `app.json` and you should be OK.

Same applies to `@react-native-firebase/analytics` :)

**Comment by wyeo** [comment]
Hi @barthap @mikehardy ! Importing `FirebaseAuthTypes` from @react-native-firebase/auth (``import { FirebaseAuthTypes } from '@react-native-firebase/auth'``) causes 

Error: You attempted to use 'firebase.auth' but this module could not be found.
Ensure you have installed and imported the '@react-native-firebase/auth' package.

Any idea ?

**Comment by ramikhoualdi** [comment]
> As far as I know, the Auth module does not need any custom installation steps. It implies that it doesn't need config plugin to work with Expo.
> 
> According to the [docs](https://rnfirebase.io/#expo):
> 
> > Config plugins are only required for React Native Firebase modules, which require custom native installation steps - e.g. modifying the Xcode project, Podfile, build.gradle, AndroidManifest.xml etc. Packages without native steps required will work out of the box.
> 
> Just remove the `auth` from plugins list in `app.json` and you should be OK.

it worked for me. Thanks
