### ISSUE TITLE
"RNFirebase core module was not found natively on iOS" (Expo issue?)

### ISSUE THREAD

**Issue by NordlingArt** [invertase/react-native-firebase#563]
### Issue

Error given:

![image](https://user-images.githubusercontent.com/2098838/32172826-42500648-bd7d-11e7-9e3b-cf9fb368cad7.png)

I have followed the whole iOS setup guide at https://rnfirebase.io/docs/v3.0.*/installation/ios successfully (until no errors or warnings were shown). Later when importing `react-native-firebase` in a module, I get the error shown above. I figured this might have to do with me using Expo via `create-react-native-app`.

This is my Podfile:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'testapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testapp

  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'

  target 'testapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS Sierra

3. Build Tools: n/a

4. React Native version: 0.48.4

5. RNFirebase Version: 3.0.5

6. Firebase Module: Core, Auth, Storage, Firestore

**Comment by chrisbianca** [comment]
@NordlingArt - Expo does not support native modules. In order to use RNFirebase you will need to `eject` your Expo app.

**Comment by smititelu** [comment]
Hi @chrisbianca! I am having this same issue on android: "RNFirebase core module was not found natively on Android".

My question is, how will I be able to write react-native code and debug/test it after I eject the expo app... ? Because the QR code will no longer be available.

**Comment by chrisbianca** [comment]
@smititelu This is a limitation of Expo and the libraries it can work with. You will need to use Android Studio / XCode in order to debug and test once you have ejected.
