### ISSUE TITLE
React Native Firebase - AdMob implement interstitial ads and Reward Ad showing error

### ISSUE THREAD

**Issue by CodeWithYd** [invertase/react-native-firebase#5635]
please help me this error

 ERROR  TypeError: (0, _$$_REQUIRE(_dependencyMap[10], "@react-native-firebase/app/lib/internal/registry/namespace").getFirebaseRoot)().admob is not a function. (In '(0, _$$_REQUIRE(_dependencyMap[10], "@react-native-firebase/app/lib/internal/registry/namespace").getFirebaseRoot)().admob()', '(0, _$$_REQUIRE(_dependencyMap[10], "@react-native-firebase/app/lib/internal/registry/namespace").getFirebaseRoot)().admob' is undefined)

**Comment by Milutin-P** [comment]
What version of `react-native-firebase` are you using?
The 11.5 version is the last one that supports admob.

Check out this Issue for more info and updates about it: #5329

**Comment by tronghieu60s** [comment]
I'm using 11.5 and have same errors.
```js
"@react-native-firebase/admob": "^11.5.0",
"@react-native-firebase/app": "^12.7.4",
```

**Comment by mikehardy** [comment]
@tronghieu60s - you must use all the same version, mixing and matching doesn't work in current react-native-firebase releases - https://invertase.io/blog/react-native-firebase-versioning

**Comment by tronghieu60s** [comment]
> @tronghieu60s - you must use all the same version, mixing and matching doesn't work in current react-native-firebase releases - https://invertase.io/blog/react-native-firebase-versioning

It's worked. Thank you.
