### ISSUE TITLE
[iOS] "React/RCTEventEmitter.j" file not found

### ISSUE THREAD

**Issue by NordlingArt** [invertase/react-native-firebase#564]
### Issue

As per the [suggestion](https://github.com/invertase/react-native-firebase/issues/563#issuecomment-340473858) by @chrisbianca, I realized I had to eject my Expo app. After doing so, I now cannot run build in Xcode due to the following error:

`'React/RCTEventEmitter.h' file not found` at line 9 in *"testapp/Libraries/RNFirebase.xcodeproj/firestore/RNFirebaseFirestoreDocumentReference.h"*:

```
...
 8 #import <FirebaseFirestore/FirebaseFirestore.h>
 9 #import <React/RCTEventEmitter.h>     <--- 'React/RCTEventEmitter.h' file not found
10 #import "RNFirebaseEvents.j"
11 #import "RNFirebaseFirestore.h"
...
```

I have even tried setting up a completely new project with XDE and then detaching it. Inspecting further I started to look inside the "Pods" folder and I could not find any React folder in there. Is that the problem maybe? The React pod is there in the Podfile and the `pod install` command runs successfully.

My Podfile looks like this:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'tradit' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.0.4",
    :subspecs => [
      "Core",
      "CPP"
    ]

  pod 'React',
    :path => "../node_modules/react-native",
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'GLog',
    :podspec => "../node_modules/react-native/third-party-podspecs/GLog.podspec",
    :inhibit_warnings => true

  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'

  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|

    if target.pod_name == 'AppAuth'
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
    if target.pod_name == 'ExpoKit'
      target.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end


    # Build React Native with RCT_DEV enabled
    next unless target.pod_name == 'React'
    target.native_target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
    end

    end
  end
end
```

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode 9.0.1

4. React Native version: 0.48.4

5. RNFirebase Version: 3.0.5

6. Firebase Module: Core, Auth, Storage, Firestore

**Comment by Ehesp** [comment]
Have you tried adding RCTEventEmitter to your subspec?

**Comment by NordlingArt** [comment]
@Ehesp - Yes, and this is the error I get when doing a `pod update` or `pod install`:

```
[!] Unable to satisfy the following requirements:

- `React/RCTEventEmitter (from `../node_modules/react-native`)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `React/RCTEventEmitter (from `../node_modules/react-native`)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by chrisbianca** [comment]
@NordlingArt See the iOS instructions here on the Expo website: https://docs.expo.io/versions/v18.0.0/guides/expokit.html#ios

**Comment by NordlingArt** [comment]
@chrisbianca - `Pods/Headers/Public` is already in my **Header Search Paths** configuration:

![image](https://user-images.githubusercontent.com/2098838/32189613-91042228-bdab-11e7-8d02-a6673f809f86.png)

Even `Pods/Headers/Public/React` is. Should I put them as "recursive" maybe?

**Comment by chrisbianca** [comment]
@NordlingArt I'm not really sure what to suggest here.  For obvious reasons, none of us as project maintainers use Expo, but we do know that people have managed to get ExpoKit working alongside RNFirebase but with a bit of a struggle.

On our Discord channel somebody got it working by making the following change

![screen_shot_2017-10-16_at_12 47 13_pm](https://user-images.githubusercontent.com/10723021/32213248-6223da86-be12-11e7-9615-0e78ffeb603e.png)

**Comment by chrisbianca** [comment]
Closing due to lack of response. Please re-open if you're still experiencing issues.

**Comment by NordlingArt** [comment]
I juust tried initiating a new React Native project with `react-native init` only, and now it works. Thank you!

**Comment by chrisbianca** [comment]
Great, glad to hear it!
