### ISSUE TITLE
[🐛] react-native@0.65.1 & @react-native-firebase/dynamic-links@12.7.2: DynamicLinks.API is not available on this device

### ISSUE THREAD

**Issue by aforty** [invertase/react-native-firebase#5648]
## Issue

I upgraded to `react-native@0.65.1` and `@react-native-firebase/dynamic-links@12.7.2` but now I get the following error when initializing my application, specifically when I call `firebase.dynamicLinks().getInitialLink()`. This only happens on Android so I will be providing only Android related files and info below. This worked fine before the upgrade.

```
[Error: [dynamicLinks/initial-link-error] 17: API: DynamicLinks.API is not available on this device. Connection failed with: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}]
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
```

#### `android/app/build.gradle`:

```groovy
```

#### `android/settings.gradle`:

```groovy
```

#### `MainApplication.java`:

```java
```

#### `AndroidManifest.xml`:

```xml
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `12.7.2`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/dynamic-links`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by hermanho** [comment]
I faced the same error. It may be related to specific android model / device. Refer to the error code, it means "The version of the Google Play services installed on this device is not authentic."
https://developers.google.com/android/reference/com/google/android/gms/common/ConnectionResult

Based on the issue from our sentry side, the phone model is HONORELZ-AN10 and the installerStore is com.aurora.store. I think the device does not have Google Play services or somethings wrong with Google library

**Comment by mikehardy** [comment]
Exactly that @hermanho - if you use features that require play services you *must* either guard the usage with checks for valid play services using our APIs to do the same - or just wrap the whole app in a check and exclude users without play services.
