### ISSUE TITLE
[🐛] Firebase Analytics Bug - logging event with number param value showing as (not set)

### ISSUE THREAD

**Issue by antpuleo2586** [invertase/react-native-firebase#5666]
## Issue

When we log an event with a param that has a numeric value it shows correctly in the Realtime view but when viewed on the event dashboard, it is shown as `(not set)`.

If I stringify the value, it appears correctly.

i.e.

```
analytics().logEvent('test_event', {some_param: 1}); // not working
analytics().logEvent('test_event', {some_param: '2'}); // working

```
Realtime view:

<img width="706" alt="Screenshot 2021-08-27 at 11 00 19" src="https://user-images.githubusercontent.com/10067589/131110192-09f06eda-5669-470a-9568-2378300f5b87.png">

Event Dashboard view:

<img width="505" alt="Screenshot 2021-08-31 at 09 20 32" src="https://user-images.githubusercontent.com/10067589/131468286-e5937413-f36c-422d-a70a-dd401aae8f41.png">

Custom dimension defined as follows:

<img width="635" alt="Screenshot 2021-08-27 at 11 06 30" src="https://user-images.githubusercontent.com/10067589/131110914-fbf0e641-687b-4b87-b5c0-13bc72676409.png">

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/app": "^10.8.1",
"@react-native-firebase/auth": "^10.8.1",
"@react-native-firebase/dynamic-links": "^10.8.1",
"@react-native-firebase/messaging": "^10.8.1",
"@react-native-firebase/perf": "^10.8.1",
"@react-native-firebase/remote-config": "^10.8.1",
"react-native": "0.64.2",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Foo' do
  config = use_native_modules!

  pod 'GoogleIDFASupport', '~> 3.14.0'
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  IS_CI = ENV['APPCENTER_BUILD_ID'] || ENV['IS_CI']

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  if not IS_CI
    use_flipper!({'Flipper' => '0.91.1', 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3'})
  end

  post_install do |installer|
      if not IS_CI
        react_native_post_install(installer)
      end
  end
end

```

#### `AppDelegate.m`:

```swift
FirebaseApp.configure()
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [x ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
(node:66152) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 196.98 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.2 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2.1 4.2.1
    Xcode: 13.0/13A5212g - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `10.8.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `analytics`
- **Are you using `TypeScript`?**
  - `Y` & `3.7`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Can you update to latest stable (making sure you have the latest underlying firebase-android-sdk / firebase-ios-sdk - that is, you have not overridden them) and reproduce? These are quite old:

```
"@react-native-firebase/app": "^10.8.1",
"@react-native-firebase/auth": "^10.8.1",
"@react-native-firebase/dynamic-links": "^10.8.1",
"@react-native-firebase/messaging": "^10.8.1",
"@react-native-firebase/perf": "^10.8.1",
"@react-native-firebase/remote-config": "^10.8.1",
```

**Comment by antpuleo2586** [comment]
I upgraded as follows:

```
"@react-native-firebase/analytics": "^12.7.3",
"@react-native-firebase/app": "^12.7.3",
"@react-native-firebase/auth": "^12.7.3",
"@react-native-firebase/dynamic-links": "^12.7.3",
"@react-native-firebase/messaging": "^12.7.3",
"@react-native-firebase/perf": "^12.7.3",
"@react-native-firebase/remote-config": "^12.7.3",
```

but still seeing the same issue (new events from yesterday):

<img width="511" alt="Screenshot 2021-09-01 at 09 12 31" src="https://user-images.githubusercontent.com/10067589/131636588-8e9712ea-93df-43e4-ad81-f6980205a358.png">



Thanks!

**Comment by mikehardy** [comment]
Hmm :thinking: this is a tough one. Here's my research:

- firebase-js-sdk specifies the index type of EventParams as `[key: string]: any` so they are advertising they'll take any type
- firebase-js-sdk is actually just a thin wrapper on gtag.js which is not open source, and I cannot see what is happening to different types to transform them if you were to use google analytics via javascript

Stated differently: I'm not sure exactly how google is doing this in their javascript implementation, and I've not tested it, so I'm not sure if they handle this either? 

It would be useful if you could test that so we could compare implementations and try to behave the same. Can you test a raw firebase-js-sdk analytics hit of the same type?

- firebase-ios-sdk and firebase-android-sdk are both closed source for the analytics logic, so I can't see what they are doing either.

We have some experience with problems passing numbers before, please examine: https://github.com/invertase/react-native-firebase/pull/4536#issuecomment-725526959

So it seems like there are two technical options:

1- you can just pass the number as a string right now, if that works for you - are they behaving as numbers in the console? and just document that using numbers won't work well in our API
2- we can add a documentation restriction that if you pass a number it must be a positive integer (as documented here https://developers.google.com/analytics/devguides/collection/gtagjs/events#send_events `<value> | number |   | A non-negative integer that will appear as the event value`) and then we can coerce the double precision floating point number that javascript comes through as since javascript numbers are all doubles to an int in native code before sending it through

If you have to use a number, and firebase-js-sdk testing shows that they behave like 2 above (restricting to set of positive integers, correctly registering them as numbers) then that works

**Comment by antpuleo2586** [comment]
I tested this with a web project that uses the firebase-js-sdk

`
"firebase": "^8.2.9"
`

And it works correctly!

<img width="503" alt="Screenshot 2021-09-03 at 09 52 57" src="https://user-images.githubusercontent.com/10067589/131978570-30f7cefb-bbae-4c1f-a247-f5da14533f7f.png">

You see the number 1 is now coming through as a number param.

I'm not sure what to make of that.

We have no issue in mapping each param value to a string before we log events, but I don't understand why this works in the js library.

**Comment by mikehardy** [comment]
They must be coercing the number a bit as it goes through the system to handle javascript's inherit "double-ness" in numbers and make sure analytics sees them as integers, thank you very much for testing this and reporting the results.

**Comment by mikehardy** [comment]
I was working on an unrelated analytics issue today and tested this. In our e2e test on android a number param goes through as a number, and on ios a number param goes through as a number in Debug View - how long does it take for you to show up in the dashboard? I waited a bit but did not see it yet.

That said, now that I see it working in DebugView, if it then does not work in some other location this seems like it will be an upstream issue with the SDK (firebase-ios-sdk / firebase-android-sdk --> cloud analytics processing) and out of our control. If I'd seen DebugView show `1.00000123` then it's a classic floating point issue related to our javascript/native translation, but seeing an integer there...I'm not sure what we can do.

Have you raised this upstream at all?

**Comment by antpuleo2586** [comment]
I haven't raised upstream no, can you point me in the right direction there?

I will take a look via debug view and see what I'm getting.

It takes about 24 hours to show up on dashboard.

Cheers

**Comment by mikehardy** [comment]
https://github.com/firebase/firebase-android-sdk/
https://github.com/firebase/firebase-ios-sdk/

it usually helps to post a github repo based off their quickstart showing the exact issue (for example clone this https://github.com/firebase/quickstart-android/tree/master/analytics put a google-services.json in there and do something like adding an analytics hit here https://github.com/firebase/quickstart-android/blob/14b5e47b8af5e7019bdba94c2e6969a2c58c0165/analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java#L182 by calling LogEvent https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#public-void-logevent-string-name,-bundle-params with params as `testBundle` made from  `Bundle testBundle = new android.os.Bundle(); testBundle.putFloat("testFloat", 1.0);` or similar ? May compile 🙏 hard to code in a web textarea
