### ISSUE TITLE
[🐛] [iOS] Custom dimension to Google analytics is missing 

### ISSUE THREAD

**Issue by Musadhikh** [invertase/react-native-firebase#5684]
## Issue

I have my Google Analytics has couple of Custom Dimensions defined.
eg: UserID, Active User (User Properties)
Video ID, Video Name (Event Properties)

When I send these values using firebase analytics, Google Analytics dashboard is not capturing these data. I can see the same values in Firebase debug view

I have checked Charles log and can't see any cd1, cd2 etc values. Other non custom dimension values are being sent just fine (eg: App version, Event name etc)

When I used the Google Analytics SDK, I am able to send every dimension as expected.

It seems like, Firebase Analytics is missing the custom dimension mapping to Google analytics. 

Please help to fix this issue

Thanks in Advance

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/analytics": "^11.0.0",
"@react-native-firebase/app": "^11.0.0",
"@react-native-firebase/crashlytics": "^11.0.0",
"@react-native-firebase/messaging": "^11.0.0",
"@react-native-firebase/perf": "^11.0.0",
```

#### `analytics.js` for react-native-firebase v6:

```json
import firebase from '@react-native-firebase/app';
import analytics from '@react-native-firebase/analytics';

export const userProperties = {
  USER_ID: 'user_id',
  ACTIVE_USER: 'active_user',
};

export const setUserProperties = (params) => {
  analytics().setUserProperties(params);
};

export const setUserIdentifier = (userId) => {
  analytics().setUserId(userId);
  setUserProperties({ [USER_ID]: userId });
};

export const setActiveUserAsUserProperty = (userProfile) => {
  setUserProperties({
    [ACTIVE_USER]: getActiveUser(userProfile),
  });
};

export const trackEvent = ({ event, params }) => {
  analytics().logEvent(event, params);
};
```
</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
$RNFirebaseAsStaticFramework = true

def firebasePods
    pod 'GoogleTagManager'
end
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 21.70 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: Not Found
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! I see you are not running the current version of this module, can you update to the current version then confirm you still reproduce?

**Comment by Musadhikh** [comment]
@mikehardy I have updated the package to latest version 12.7.5

`"@react-native-firebase/analytics": "^12.7.5",
    "@react-native-firebase/app": "^12.7.5",
    "@react-native-firebase/crashlytics": "^12.7.5",
    "@react-native-firebase/messaging": "^12.7.5",
    "@react-native-firebase/perf": "^12.7.5",`
    
    I still don't see the custom dimension under scope User.
    
    the custom dimension with scope User being use once in the app using method 
    `analytics().setUserProperties(params);`
    
    but when track an event later using `analytics().logEvent(event, params);` , these user properties not included in the event.
    
    if I am not wrong, what ever set in the user property will be includes with event tracking batch request right.?

**Comment by mikehardy** [comment]
@Musadhikh that's to  be expected, no changes were made to the analytics package, there should have been no change in your results (or we are going crazy! seeing changes when code did not change...)

My linked commend was this, it's worth a read as are the following comments on that thread:

> That said, now that I see it working in DebugView, if it then does not work in some other location this seems like it will be an upstream issue with the SDK (firebase-ios-sdk / firebase-android-sdk --> cloud analytics processing) and out of our control. If I'd seen DebugView show 1.00000123 then it's a classic floating point issue related to our javascript/native translation, but seeing an integer there...I'm not sure what we can do.
> 
> Have you raised this upstream at all?
