### ISSUE TITLE
BUG admod banner ios 10.3.3

### ISSUE THREAD

**Issue by GH974** [invertase/react-native-firebase#569]
### Issue

quizz was compiled with optimization - stepping may behave oddly; variables may not be available.
(lldb) 
<img width="1440" alt="capture d ecran 2017-11-01 a 11 07 28" src="https://user-images.githubusercontent.com/11731125/32263860-2856a1ec-bef5-11e7-9cd4-93618b0a4e08.png">

### Environment

1. Application Target Platform: iOS iPhone 5 v10.3.3

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode 9.1

4. React Native version:  React native 0.49

5. RNFirebase Version: 3.0.6

6. Firebase Module: admob

**Comment by chrisbianca** [comment]
@GH974 We need the stack trace relating to the `EXC_BAD_ACCESS` error, not the warning that you have supplied.

**Comment by GH974** [comment]
Where is this?

**Comment by chrisbianca** [comment]
You will need to look at the logs in Xcode

**Comment by GH974** [comment]
<img width="1679" alt="capture d ecran 2017-11-01 a 11 28 42" src="https://user-images.githubusercontent.com/11731125/32264375-dbf24434-bef7-11e7-9532-f791c35ea3ed.png">

**Comment by chrisbianca** [comment]
No, not the threads. Click the last tab on the right hand side of the left panel to show the actual logs

**Comment by GH974** [comment]
<img width="1674" alt="capture d ecran 2017-11-01 a 11 35 15" src="https://user-images.githubusercontent.com/11731125/32264574-c7b60edc-bef8-11e7-8df1-75ae9d8f146a.png">

**Comment by GH974** [comment]
Im checked this and not error generating after bug

**Comment by Ehesp** [comment]
Can we see your JS code please where you're using it?

**Comment by GH974** [comment]
`import React from "react";
import { Image, Dimensions, StatusBar, View} from "react-native";

import ConfigAdmob from '../config/admob';
import firebase from 'react-native-firebase';

const bannerUnitID = ConfigAdmob.AD_UNIT_ID_BANNER;

const Banner    = firebase.admob.Banner;
const AdRequest = firebase.admob.AdRequest;
const request   = new AdRequest();
request.addKeyword('footer');

export default class BannerClass extends React.Component {
    constructor(props){
        super(props);
    }

    render(){

        return (
            <Banner
                size="SMART_BANNER"
                unitId={bannerUnitID}
                request={request.build()}
            />
        );
    }

}
`

**Comment by GH974** [comment]
Bug only on iphone 5 on my iphone 7 is ok

**Comment by Ehesp** [comment]
What ios version is the iPhone 5 running?

**Comment by GH974** [comment]
ios 10.3.3

**Comment by chrisbianca** [comment]
This will be another 32 bit issue

**Comment by chrisbianca** [comment]
@GH974 This seems to be the same issue as: https://github.com/invertase/react-native-firebase/issues/437

Closing in favour of that one as there's a bit more detail to go on
