### ISSUE TITLE
onDisconnect().set() on iOS

### ISSUE THREAD

**Issue by alexkuttig** [invertase/react-native-firebase#57]
Hi,

first of all, great job with react-native-firebase. I move here from the WebSDK and it works like a charm. 

Except one Issue. 

onDisconnect().set() is not working on iOS. It results in an missing function for promisify error.

I think the problem is, that in lib/modules/database/disconnect.js line 30 the function to call is onDisconnectSet, but in ios/RNFirebase/RNFirebaseDatabase.m line 617 the function is named onDisconenctSetObject or line 628 onDisconnectSetString. The function onDisconnectSet is missing.

**Comment by alexkuttig** [comment]
I made my own fork an fixed it (at least for my needs). I tested it with Strings, Booleans, Objects and null. 

I opened a pull request here. Since I'm no iOS dev, any suggested changes are welcome:
https://github.com/invertase/react-native-firebase/pull/58

**Comment by Salakar** [comment]
@alexkuttig awesome, thanks for the fix - I refactored android https://github.com/invertase/react-native-firebase/blob/d8693f5e39106e62dccdcd883728629ef0e6c6aa/android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabase.java#L341 to do this a while back, ios was on the todo.

**Comment by Salakar** [comment]
Will close and merge, again, thanks.

**Comment by alexkuttig** [comment]
Perfect. you're welcome. Thanks for the fast reply and the great job.
