### ISSUE TITLE
[🐛] [iOS] Dynamics Links handle links correctly but doesn't return YES from delegation

### ISSUE THREAD

**Issue by leolusoli** [invertase/react-native-firebase#5702]
**What I'm doing:**

Installed and test dynamic links with firebase. In my app, I need t handle FB SDK App events and other custom urls. My `AppDelegate.m openUrl` method look like this:

```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  // try handling url with FB SDK
  BOOL handled = [[FBSDKApplicationDelegate sharedInstance] application:application openURL:url options:options];
  
  if (!handled) {
    // try handling url with our custom scheme
    handled = [RCTLinkingManager application:application openURL:url options:options];
  }
  
  return handled;
}
```

**What do I expect to happen**

When a user opens an URL created by the firebase dynamic link console, only the firebase resolved data is handled by the application, using the SDK listener (i.e. `onLink` method)

**What happening**

In addition of firebase resolved data, the application receive also the not resolved firebase url (example: `https://domain.page.link/XXX`) through the react native classical `Linking.addEventListener('url', this.handleLinking);`.

**Motivation**

The dynamic links work correctly with the google swizzling method. By the way, in my application, I need to handle the Facebook app links (and custom universal and deep link URLs) so I need to reimplement the app delegate OpenUrl method. **Returning NO inside SDK OpenUrl method causes the application to open a broken not resolved link from firebase, in addition to the correct data resolved by dynamic link library.** 

In general, the question is:

```
  if (!dynamicLink) {
    return NO;
  }

  if (dynamicLink.url) {
    if (_initialLinkUrl == nil) {
      _initialLinkUrl = dynamicLink.url.absoluteString;
      _initialLinkMinimumAppVersion = dynamicLink.minimumAppVersion;
      _initialLinkUtmParametersDictionary = dynamicLink.utmParametersDictionary;
    }
    [[RNFBRCTEventEmitter shared]
        sendEventWithName:LINK_RECEIVED_EVENT
                     body:@{
                       @"url" : dynamicLink.url.absoluteString,
                       @"minimumAppVersion" : dynamicLink.minimumAppVersion == nil
                           ? [NSNull null]
                           : dynamicLink.minimumAppVersion,
                       @"utmParameters" : dynamicLink.utmParametersDictionary == nil
                           ? @{}
                           : dynamicLink.utmParametersDictionary,
                     }];
       /// MARKER
  }

  // results of this are ORed and NO doesn't affect other delegate interceptors' result
  return NO;

```
file: **RNFBDynamicLinksAppDelegateInterceptor.m**

Why instead of the MARKER comment the SDK doesn't `return YES` to the delegate?

### Javascript

Using firebase dynamics link listener and also Facebook + react-native linking listener.

#### `package.json`:

```json
{
  "dependencies": {
    "@notifee/react-native": "1.11.0",
    "@react-native-firebase/analytics": "12.7.4",
    "@react-native-firebase/app": "12.7.4",
    "@react-native-firebase/dynamic-links": "12.7.4",
    "@react-native-firebase/messaging": "12.7.4",
    "react": "17.0.2",
    "react-native": "0.65.1",
  }
}
```

## Environment

**`react-native info` output:**

```
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 488.40 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7621141
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_144 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `12.7.4`
- **`Firebase` module(s) you're using that has the issue:**
  - `messaging`
- **Are you using `TypeScript`?**
  - `N`

**Comment by mikehardy** [comment]
Hi there! I'm not understanding you, sorry.

Can you please clearly state your problem? More like: I do exactly this thing. I need and expect exactly this thing to happen. This happens instead?

**Comment by leolusoli** [comment]
Hi @mikehardy,
I'm trying to explain this more clearly. Sorry.

**Comment by mikehardy** [comment]
For reference + comparison, this is in my work project's `AppDelegate.m`

```objective-c

- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
    return YES;
  }

  if ([RNGoogleSignin application:app openURL:url options:options]) {
    return YES;
  }

  if ([RCTLinkingManager application:app openURL:url options:options]) {
    return YES;
  }

  return NO;
}
```

I believe if you also subscribe to Linking events, it will also be triggered, I do not think it is even desirable to disable that? In other words, not a bug I think, but a valid expectation? Additionally, it would be a breaking change if we suddenly changed to stopping control flow there.

In my work project I consume both (just in case) and disambiguate them.

```typescript
import { autoSubscribe, AutoSubscribeStore, StoreBase } from 'resub';
import * as SyncTasks from 'synctasks';
import firebase from '@react-native-firebase/app';
import * as url from 'url';
import { FirebaseDynamicLinksTypes } from '@react-native-firebase/dynamic-links';
import { Linking } from 'react-native';

import { Service } from '../services/ServiceManager';
import { User } from '../models/IdentityModels';
import AppConfig from '../app/AppConfig';
import I18NService from '../services/I18NService';
import UserStore from './UserStore';
import NavigationService from '../services/NavigationService';
import SecondaryUserStore from './SecondaryUserStore';

@AutoSubscribeStore
export class DynamicLinkStore extends StoreBase implements Service {
  private static inboundLinkProfileOwner?: string;

  private static currentUserProfileLink?: string;

  private static profileLinkLoading = false;

  private static initialLink?: FirebaseDynamicLinksTypes.DynamicLink;

  private static lastLinkProcessed?: FirebaseDynamicLinksTypes.DynamicLink;

  private static _instance: DynamicLinkStore = new DynamicLinkStore();

  constructor() {
    super();
    // This is a singleton no one else gets to instantiate or the hooks
    // and listeners won't work as the references won't be correct
    if (DynamicLinkStore._instance) {
      throw new Error('DynamicLinkStore is a singleton. Call .getInstance() instead');
    }
    DynamicLinkStore._instance = this;
  }

  public static getInstance(): DynamicLinkStore {
    return DynamicLinkStore._instance;
  }

  // eslint-disable-next-line class-methods-use-this
  startup(): SyncTasks.Thenable<void> {
    console.log('DynamicLinkStore::startup called');
    firebase
      .dynamicLinks()
      .getInitialLink()
      .then((link) => {
        if (link !== undefined && link !== null) {
          console.log(
            `DynamicLinkStore::startup - got initial link: ${JSON.stringify(link, null, 2)}`
          );
          DynamicLinkStore.initialLink = link;
          this.trigger();
        }
      })
      .catch((err) => console.log('DynamicLinkStore::startup - getInitialLink error', err))
      .finally(() => console.log('DynamicLinkStore::startup async link fetch finished.'));

    Linking.getInitialURL()
      .then((link) => {
        if (link !== undefined && link !== null) {
          console.log(
            `DynamicLinkStore::startup - Linking.getInitialUrl: ${JSON.stringify(link, null, 2)}`
          );
          if (!this.linkIsDynamicLink(link) && this.linkIsProfileLink(link)) {
            console.log(
              'DynamicLinkStore::startup::Linking::getInitialURL - handling non-dynamic profile link'
            );
            DynamicLinkStore.initialLink = {
              url: link,
              minimumAppVersion: null,
              utmParameters: {},
            };
            this.trigger();
          }
        }
      })
      .catch((err) => console.log('DynamicLinkStore::startup - Linking.getInitialURL error', err))
      .finally(() =>
        console.log('DyanmicLinkStore::startup async Linking.getInitialURL fetch finished.')
      );

    return SyncTasks.Resolved<void>();
  }

  // eslint-disable-next-line class-methods-use-this
  linkIsDynamicLink(link: string): boolean {
    const linkPrefixes = AppConfig.getDynamicLinkPrefixes();
    for (let i = 0; i < linkPrefixes.length; i++) {
      if (link.startsWith(`${AppConfig.getWebAppURIRoot()}/${linkPrefixes[i]}/`)) {
        console.log(`DynamicLinkStore::linkIsDynamicLink ${link} is a dynamic link`);
        return true;
      }
    }
    console.log(`DynamicLinkStore::linkIsDynamicLink ${link} is not a dynamic link`);
    return false;
  }

  // eslint-disable-next-line class-methods-use-this
  linkIsProfileLink(link: string): boolean {
    // Anything over 8 characters (9 if you include `/`) is a profile link by our convention.
    // This is enforced in screens/ProfileDetails.tsx
    return link.length > AppConfig.getWebAppURIRoot().length + 9;
  }

  @autoSubscribe
  // eslint-disable-next-line class-methods-use-this
  getInitialLink(): FirebaseDynamicLinksTypes.DynamicLink | undefined {
    console.log(`DynamicLinkStore::getInitialLink - ${DynamicLinkStore.initialLink?.url}`);
    return DynamicLinkStore.initialLink;
  }

  // eslint-disable-next-line class-methods-use-this
  clearInitialLink(): void {
    console.log('DynamicLinkStore::clearInitialLink');
    DynamicLinkStore.initialLink = undefined;
  }

  // eslint-disable-next-line class-methods-use-this
  public getProfileFromLink(link: FirebaseDynamicLinksTypes.DynamicLink): string | undefined {
    DynamicLinkStore.lastLinkProcessed = link;
    const urlParts = url.parse(link.url);
    let profileName;
    if (urlParts.path) {
      profileName = urlParts.path.substring(1);
      console.log(
        `DynamicLinkStore::getProfileFromLink got a link (${link.url})! profile name: ${profileName}`
      );
    }
    return profileName;
  }

  @autoSubscribe
  // eslint-disable-next-line class-methods-use-this
  public dequeueLastLinkProcessed(): FirebaseDynamicLinksTypes.DynamicLink | undefined {
    const link = DynamicLinkStore.lastLinkProcessed;
    DynamicLinkStore.lastLinkProcessed = undefined;
    return link;
  }

  // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
  public setInboundLinkProfileOwner(user?: string) {
    DynamicLinkStore.inboundLinkProfileOwner = user;
    this.trigger();
  }

  @autoSubscribe
  // eslint-disable-next-line class-methods-use-this
  public getInboundLinkProfileOwner(): string | undefined {
    return DynamicLinkStore.inboundLinkProfileOwner;
  }

  @autoSubscribe
  public getProfileLink(user: User | undefined): string | undefined {
    if (!user || !user.profileName) {
      console.log('DynamicLinkStore::getProfileLink - user or user.profileName not defined');
      return undefined;
    }

    if (!DynamicLinkStore.currentUserProfileLink && !DynamicLinkStore.profileLinkLoading) {
      DynamicLinkStore.profileLinkLoading = true;
      console.log('DynamicLinkStore::getProfileLink - building link');
      firebase
        .dynamicLinks()
        .buildShortLink(
          {
            link: `${AppConfig.getWebAppURIRoot()}/${user.profileName}`,
            domainUriPrefix: AppConfig.getDynamicLinkProfileRoot(),
            android: {
              packageName: AppConfig.getAndroidPackage(),
            },
            ios: {
              bundleId: AppConfig.getIOSBundle(),
              appStoreId: AppConfig.getIOSAppId(),
            },
            social: {
              title: `${user.profileName} ${I18NService.translate(
                'ProfileShareSocialYour'
              )} Komp.ai`,
              descriptionText: I18NService.translate('ProfileShareSocialDescription'),
              imageUrl: `${AppConfig.getWebAppURIRoot()}/ms-icon-310x310.png`,
            },
          },
          firebase.dynamicLinks.ShortLinkType.SHORT
        )
        .then((link) => {
          console.log(`DynamicLinkStore::getProfileLink - got link: ${link}`);
          DynamicLinkStore.currentUserProfileLink = link;
          this.trigger();
        })
        .catch((err) => {
          console.log('DynamicLinkStore::getProfileLink - unable to build link?', err);
          DynamicLinkStore.profileLinkLoading = false;
        });
    }

    return DynamicLinkStore.currentUserProfileLink;
  }

  @autoSubscribe
  async handleLink(link: FirebaseDynamicLinksTypes.DynamicLink): Promise<boolean> {
    console.log('DynamicLinkStore::handleLink - ', JSON.stringify(link, null, 2));
    this.clearInitialLink();
    this.trigger();
    const profileName = this.getProfileFromLink(link);
    if (profileName) {
      const profileNameOwner = await UserStore.resolveProfileName(profileName);
      this.setInboundLinkProfileOwner(profileNameOwner?.kullkiId);
      SecondaryUserStore.setUser(profileNameOwner);
      NavigationService.navigate('Profile', 'ProfilePublic');
      this.dequeueLastLinkProcessed();
      return true;
    }
    return false;
  }

  async handleDeepLinkDirectly(deepLink: string): Promise<boolean> {
    console.log(`DynamicLinkStore::handleDeepLinkDirectly ${deepLink}`);
    try {
      const link = await firebase.dynamicLinks().resolveLink(deepLink);
      console.log(`DynamicLinkStore::handleDeepLinkDirectly got: ${JSON.stringify(link, null, 2)}`);
      return this.handleLink(link);
    } catch (e) {
      console.log('DynamicLinkStore::handleDeepLinkDirectly - did not work ', e);
    }
    return false;
  }
}

export default DynamicLinkStore.getInstance();

```

That's the full code, I don't think I've have time to fully dissect your work project and assist.

**Comment by leolusoli** [comment]
@mikehardy Thanks for sharing your code.
So there's no real motivation to return TRUE from the swizzled OpenURL method inside the module when the dynamic link is recognized?
I'm talking about it because I don't know if it's a decision related to something that I don't know or something else?

Thank you, appreciate your patience.

**Comment by mikehardy** [comment]
In general I'm not motivated to issue  breaking changes for features that have behaved one way forever, but as I carefully reconsider this (playing devil's advocate in my mine, arguing it is a bug) - I think it might be a reasonable stance to say "if react-native-firebase recognizes it as a dynamic link, react-native-firebase should return the expected value (TRUE) indicating it did recognize it.

It does seem like the return value should be TRUE - https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl

@Salakar or @Ehesp I feel like I need a second set of eyes to make sure, before I contemplate issuing a breaking change

**Comment by mikehardy** [comment]
Yeah - this is still in the review queue but it did go stale - sorry about that, will attempt to pursue it internally to get the second review I want

**Comment by mikehardy** [comment]
Still haven't gotten a set of eyes on this, need to

**Comment by Willham12** [comment]
> For reference + comparison, this is in my work project's `AppDelegate.m`
> 
> ```objc
> - (BOOL)application:(UIApplication *)app
>             openURL:(NSURL *)url
>             options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
> {
>   if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
>     return YES;
>   }
> 
>   if ([RNGoogleSignin application:app openURL:url options:options]) {
>     return YES;
>   }
> 
>   if ([RCTLinkingManager application:app openURL:url options:options]) {
>     return YES;
>   }
> 
>   return NO;
> }
> ```
> 
> I believe if you also subscribe to Linking events, it will also be triggered, I do not think it is even desirable to disable that? In other words, not a bug I think, but a valid expectation? Additionally, it would be a breaking change if we suddenly changed to stopping control flow there.
> 
> In my work project I consume both (just in case) and disambiguate them.
> 
> ```ts
> import { autoSubscribe, AutoSubscribeStore, StoreBase } from 'resub';
> import * as SyncTasks from 'synctasks';
> import firebase from '@react-native-firebase/app';
> import * as url from 'url';
> import { FirebaseDynamicLinksTypes } from '@react-native-firebase/dynamic-links';
> import { Linking } from 'react-native';
> 
> import { Service } from '../services/ServiceManager';
> import { User } from '../models/IdentityModels';
> import AppConfig from '../app/AppConfig';
> import I18NService from '../services/I18NService';
> import UserStore from './UserStore';
> import NavigationService from '../services/NavigationService';
> import SecondaryUserStore from './SecondaryUserStore';
> 
> @AutoSubscribeStore
> export class DynamicLinkStore extends StoreBase implements Service {
>   private static inboundLinkProfileOwner?: string;
> 
>   private static currentUserProfileLink?: string;
> 
>   private static profileLinkLoading = false;
> 
>   private static initialLink?: FirebaseDynamicLinksTypes.DynamicLink;
> 
>   private static lastLinkProcessed?: FirebaseDynamicLinksTypes.DynamicLink;
> 
>   private static _instance: DynamicLinkStore = new DynamicLinkStore();
> 
>   constructor() {
>     super();
>     // This is a singleton no one else gets to instantiate or the hooks
>     // and listeners won't work as the references won't be correct
>     if (DynamicLinkStore._instance) {
>       throw new Error('DynamicLinkStore is a singleton. Call .getInstance() instead');
>     }
>     DynamicLinkStore._instance = this;
>   }
> 
>   public static getInstance(): DynamicLinkStore {
>     return DynamicLinkStore._instance;
>   }
> 
>   // eslint-disable-next-line class-methods-use-this
>   startup(): SyncTasks.Thenable<void> {
>     console.log('DynamicLinkStore::startup called');
>     firebase
>       .dynamicLinks()
>       .getInitialLink()
>       .then((link) => {
>         if (link !== undefined && link !== null) {
>           console.log(
>             `DynamicLinkStore::startup - got initial link: ${JSON.stringify(link, null, 2)}`
>           );
>           DynamicLinkStore.initialLink = link;
>           this.trigger();
>         }
>       })
>       .catch((err) => console.log('DynamicLinkStore::startup - getInitialLink error', err))
>       .finally(() => console.log('DynamicLinkStore::startup async link fetch finished.'));
> 
>     Linking.getInitialURL()
>       .then((link) => {
>         if (link !== undefined && link !== null) {
>           console.log(
>             `DynamicLinkStore::startup - Linking.getInitialUrl: ${JSON.stringify(link, null, 2)}`
>           );
>           if (!this.linkIsDynamicLink(link) && this.linkIsProfileLink(link)) {
>             console.log(
>               'DynamicLinkStore::startup::Linking::getInitialURL - handling non-dynamic profile link'
>             );
>             DynamicLinkStore.initialLink = {
>               url: link,
>               minimumAppVersion: null,
>               utmParameters: {},
>             };
>             this.trigger();
>           }
>         }
>       })
>       .catch((err) => console.log('DynamicLinkStore::startup - Linking.getInitialURL error', err))
>       .finally(() =>
>         console.log('DyanmicLinkStore::startup async Linking.getInitialURL fetch finished.')
>       );
> 
>     return SyncTasks.Resolved<void>();
>   }
> 
>   // eslint-disable-next-line class-methods-use-this
>   linkIsDynamicLink(link: string): boolean {
>     const linkPrefixes = AppConfig.getDynamicLinkPrefixes();
>     for (let i = 0; i < linkPrefixes.length; i++) {
>       if (link.startsWith(`${AppConfig.getWebAppURIRoot()}/${linkPrefixes[i]}/`)) {
>         console.log(`DynamicLinkStore::linkIsDynamicLink ${link} is a dynamic link`);
>         return true;
>       }
>     }
>     console.log(`DynamicLinkStore::linkIsDynamicLink ${link} is not a dynamic link`);
>     return false;
>   }
> 
>   // eslint-disable-next-line class-methods-use-this
>   linkIsProfileLink(link: string): boolean {
>     // Anything over 8 characters (9 if you include `/`) is a profile link by our convention.
>     // This is enforced in screens/ProfileDetails.tsx
>     return link.length > AppConfig.getWebAppURIRoot().length + 9;
>   }
> 
>   @autoSubscribe
>   // eslint-disable-next-line class-methods-use-this
>   getInitialLink(): FirebaseDynamicLinksTypes.DynamicLink | undefined {
>     console.log(`DynamicLinkStore::getInitialLink - ${DynamicLinkStore.initialLink?.url}`);
>     return DynamicLinkStore.initialLink;
>   }
> 
>   // eslint-disable-next-line class-methods-use-this
>   clearInitialLink(): void {
>     console.log('DynamicLinkStore::clearInitialLink');
>     DynamicLinkStore.initialLink = undefined;
>   }
> 
>   // eslint-disable-next-line class-methods-use-this
>   public getProfileFromLink(link: FirebaseDynamicLinksTypes.DynamicLink): string | undefined {
>     DynamicLinkStore.lastLinkProcessed = link;
>     const urlParts = url.parse(link.url);
>     let profileName;
>     if (urlParts.path) {
>       profileName = urlParts.path.substring(1);
>       console.log(
>         `DynamicLinkStore::getProfileFromLink got a link (${link.url})! profile name: ${profileName}`
>       );
>     }
>     return profileName;
>   }
> 
>   @autoSubscribe
>   // eslint-disable-next-line class-methods-use-this
>   public dequeueLastLinkProcessed(): FirebaseDynamicLinksTypes.DynamicLink | undefined {
>     const link = DynamicLinkStore.lastLinkProcessed;
>     DynamicLinkStore.lastLinkProcessed = undefined;
>     return link;
>   }
> 
>   // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
>   public setInboundLinkProfileOwner(user?: string) {
>     DynamicLinkStore.inboundLinkProfileOwner = user;
>     this.trigger();
>   }
> 
>   @autoSubscribe
>   // eslint-disable-next-line class-methods-use-this
>   public getInboundLinkProfileOwner(): string | undefined {
>     return DynamicLinkStore.inboundLinkProfileOwner;
>   }
> 
>   @autoSubscribe
>   public getProfileLink(user: User | undefined): string | undefined {
>     if (!user || !user.profileName) {
>       console.log('DynamicLinkStore::getProfileLink - user or user.profileName not defined');
>       return undefined;
>     }
> 
>     if (!DynamicLinkStore.currentUserProfileLink && !DynamicLinkStore.profileLinkLoading) {
>       DynamicLinkStore.profileLinkLoading = true;
>       console.log('DynamicLinkStore::getProfileLink - building link');
>       firebase
>         .dynamicLinks()
>         .buildShortLink(
>           {
>             link: `${AppConfig.getWebAppURIRoot()}/${user.profileName}`,
>             domainUriPrefix: AppConfig.getDynamicLinkProfileRoot(),
>             android: {
>               packageName: AppConfig.getAndroidPackage(),
>             },
>             ios: {
>               bundleId: AppConfig.getIOSBundle(),
>               appStoreId: AppConfig.getIOSAppId(),
>             },
>             social: {
>               title: `${user.profileName} ${I18NService.translate(
>                 'ProfileShareSocialYour'
>               )} Komp.ai`,
>               descriptionText: I18NService.translate('ProfileShareSocialDescription'),
>               imageUrl: `${AppConfig.getWebAppURIRoot()}/ms-icon-310x310.png`,
>             },
>           },
>           firebase.dynamicLinks.ShortLinkType.SHORT
>         )
>         .then((link) => {
>           console.log(`DynamicLinkStore::getProfileLink - got link: ${link}`);
>           DynamicLinkStore.currentUserProfileLink = link;
>           this.trigger();
>         })
>         .catch((err) => {
>           console.log('DynamicLinkStore::getProfileLink - unable to build link?', err);
>           DynamicLinkStore.profileLinkLoading = false;
>         });
>     }
> 
>     return DynamicLinkStore.currentUserProfileLink;
>   }
> 
>   @autoSubscribe
>   async handleLink(link: FirebaseDynamicLinksTypes.DynamicLink): Promise<boolean> {
>     console.log('DynamicLinkStore::handleLink - ', JSON.stringify(link, null, 2));
>     this.clearInitialLink();
>     this.trigger();
>     const profileName = this.getProfileFromLink(link);
>     if (profileName) {
>       const profileNameOwner = await UserStore.resolveProfileName(profileName);
>       this.setInboundLinkProfileOwner(profileNameOwner?.kullkiId);
>       SecondaryUserStore.setUser(profileNameOwner);
>       NavigationService.navigate('Profile', 'ProfilePublic');
>       this.dequeueLastLinkProcessed();
>       return true;
>     }
>     return false;
>   }
> 
>   async handleDeepLinkDirectly(deepLink: string): Promise<boolean> {
>     console.log(`DynamicLinkStore::handleDeepLinkDirectly ${deepLink}`);
>     try {
>       const link = await firebase.dynamicLinks().resolveLink(deepLink);
>       console.log(`DynamicLinkStore::handleDeepLinkDirectly got: ${JSON.stringify(link, null, 2)}`);
>       return this.handleLink(link);
>     } catch (e) {
>       console.log('DynamicLinkStore::handleDeepLinkDirectly - did not work ', e);
>     }
>     return false;
>   }
> }
> 
> export default DynamicLinkStore.getInstance();
> ```
> 
> That's the full code, I don't think I've have time to fully dissect your work project and assist.

Hi, is this still your current setup? For me it's not really clear if we need to add this steps https://firebase.google.com/docs/dynamic-links/ios/receive to have working dynmic/deep links
