### ISSUE TITLE
[🐛] Method onNotificationOpenedApp not call if user tap on ranker_group of notifications on Android

### ISSUE THREAD

**Issue by ustkirill** [invertase/react-native-firebase#5706]
## Issue

Hi guys!

On Android devices notifications grouped automatically if it's count more than 3, if I tap on group title - list expanded and taps on each notification worked perfectly, but if tap on body of group - app open, but onNotificationOpenedApp method not called.

I researched info about grouping from server on FCM, but not found any information about this.

I think tap on group notifications should call method onNotificationOpenedApp with all notifications in this group and cancel the group of notifications.

The problem is reproducible on Android 11.

Help me please, I totally discouraged :(

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 12.7.5
- **`Firebase` module(s) you're using that has the issue:**
  - @react-native-firebase/messaging 12.7.5
- **Are you using `TypeScript`?**
  - 3.9.7

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Skipped template == closed issue, sorry.
https://stackoverflow.com/help/minimal-reproducible-example would also help (for example, an App.js with everything in there to reproduce the behavior you see)

Definitely work through platform documentation as well, this is a platform feature:

https://developer.android.com/guide/topics/ui/notifiers/notifications#bundle

> Note: If the same app sends four or more notifications and does not specify a grouping, the system automatically groups them together.
