### ISSUE TITLE
library not found for -lBoringSSL-GRPC

### ISSUE THREAD

**Issue by stakkdev** [invertase/react-native-firebase#5707]
i have install @react-native-firebase/firestore
and after it Run pod install,
But after that when i run the build, this issue getting 
can anyone help me, how to get rid of this issue.

**Comment by mikehardy** [comment]
That's a cocoapods issue, this module uses, but does not provide or provide support for the BoringSSL--GRPC library. It is a transitive dependency of the firestore direct dependency, and that is provided by firebase-ios-sdk.
Errors this are almost always "cocoapods specs are out of date" (`pod repo update`) or "my network failed" (examine and fix your local network)

There will not be anything at all we can do to help, sorry
