### ISSUE TITLE
Missing support for Firestore `createTime` and `updateTime` properties on `DocumentSnapshot` objects

### ISSUE THREAD

**Issue by toblerpwn** [invertase/react-native-firebase#571]
### Issue

I'm not sure if this is a feature request or a bug, but in Firestore the `createTime` and `updateTime` properties provided by Google are not available on `DoumentSnapshot` objects.

For API details, see: https://cloud.google.com/nodejs/docs/reference/firestore/0.8.x/DocumentSnapshot

In case you view this as a feature request and not an "issue" per se, I made one here: https://react-native-firebase.canny.io/feature-requests/p/support-firestore-documentsnapshot-properties-createtime-and-updatetime

### Environment

1. Application Target Platform: Both

2. Development Operating System: macOS High Sierra

3. Build Tools: Atom Nuclide

4. React Native version: 0.49.1

5. RNFirebase Version: 3.0.6

6. Firebase Module: Firestore

**Comment by chrisbianca** [comment]
@toblerpwn Unfortunately, although these fields are present on Node, they're not present on either the web SDK (https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentSnapshot) or more importantly on the Android and iOS native SDKs.

We've spoken with Firestore directly about this, and apparently it tends to be that Node is easier to work with so gets features sooner than the other SDKs.  As soon as these are added to both iOS and Android we will incorporate it into RNFirebase.

I'll close this issue, but leave your feature request open as a reminder to keep a look out for them in future versions of the native SDKs
