### ISSUE TITLE
[🐛] Bug RNFBMessagingModule.getToken was called with 0 arguments but expects 2 arguments 

### ISSUE THREAD

**Issue by caolong0204** [invertase/react-native-firebase#5719]
## Issue

Hello, i've got an error when call Function messaging().getToken() 
on IOS:
![image](https://user-images.githubusercontent.com/66582805/133223064-30e54ee8-3b9d-421c-8ff6-93d4662a2e91.png)
on Android:
![image](https://user-images.githubusercontent.com/66582805/133226664-c3cdd5c4-4104-4504-bee0-7ae8f627a245.png)

This is my Code:
  

> `const token = await messaging().getToken();`

It worked with me before but now it doesn't
 I haven't yet upgraded to new version.so i don't know why i got the error .
I read more information of this function 
![image](https://user-images.githubusercontent.com/66582805/133224600-631fd518-3e7e-4fa5-8661-8206e57c7d1d.png)
i find that This function need 2 arguments but both is nullable argument.So my code isn't wrong.

Please help me!
---

## Environment
       "react-native": "0.64.0",
       "@react-native-firebase/app": "^11.1.2",
       "@react-native-firebase/messaging": "^11.1.2",

**Comment by mikehardy** [comment]
Hi there! This is always the result of a mismatch between the compiled javascript bundle and the native code. First goal (before logging an issue in fact) is to update to whatever current stable release is so we are not chasing phantoms that are already fixed, that's 12.7.5 right now, soon to be 12.8.0.

Second step is to make sure your environment is clean: `npx react-native-clean-project`. That should get your javascript and your native code all cleared out so this works for you
