### ISSUE TITLE
Sending file straight from camera failing

### ISSUE THREAD

**Issue by peterdivvito** [invertase/react-native-firebase#572]
### Issue

I integrated with https://github.com/react-community/react-native-image-picker to add image upload to my app. When trying to upload a file to from a newly taken photo it failed with:

`ReactNativeJS: 'error uploading image', { [Error: An unknown error has occurred.] framesToPop: 1, code: 'storage/unknown' }`

When I changed the image picker options to store the image (added 'storageOptions' option) the upload worked.

I noted that he differences from failing to working was that the URI passed to RNFireBase was:

FAILS:
content://XXX/app_images/Android/data/XXX/files/Pictures/image-a8721787-9b0b-44d5-a11c-9850c6db7ca8.jpg

WORKS:
file:///storage/emulated/0/DCIM/image-fe3b561f-db6d-43df-b847-458414a40f29.jpg

I debugged the code and found it failing in RNFirebaseStorage.getRealPathFromURI() with an error along the lines of 'column _data not found'.

I made some changes to use putStream instead of putFile and this fixed it. Pull request to follow.

### Environment

1. Application Target Platform: Android 7.0 API 24

2. Development Operating System: macOS Sierra

3. Build Tools: Android Studio 3

4. React Native version: 0.48.4

5. RNFirebase Version: Git v3.0.x 270279551aaf8061f64a3d7c47cbc4c10de03458

6. Firebase Module: Storage

**Comment by chrisbianca** [comment]
This is now resolved on the 3.0.x branch and ready for our 3.1.0 release
