### ISSUE TITLE
Android App Force Close

### ISSUE THREAD

**Issue by rachmanzz** [invertase/react-native-firebase#5725]
Hay there, I Wanna Ask my problem in react-native-firebase

I have follow the documentation configuration, but when I try to run application in android device. My app auto force close.
I dont know what the problem. I need Some Help

this is the detail my configuration:

### android build.gradle

`
     // Top-level build file where you can add configuration options common to all sub-projects/modules.
    
    buildscript {
        ext {
            buildToolsVersion = "30.0.2"
            minSdkVersion = 21
            compileSdkVersion = 30
            targetSdkVersion = 30
            ndkVersion = "20.1.5948944"
        }
        repositories {
            google()
            mavenCentral()
        }
        dependencies {
            classpath("com.android.tools.build:gradle:4.2.1")
            classpath("com.google.gms:google-services:4.3.10")
            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
        }
    }
    
    allprojects {
        repositories {
            mavenCentral()
            mavenLocal()
            maven {
                // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
                url("$rootDir/../node_modules/react-native/android")
            }
            maven {
                // Android JSC is installed from npm
                url("$rootDir/../node_modules/jsc-android/dist")
            }
    
            google()
            maven { url 'https://www.jitpack.io' }
        }
    }

`

### android/app build.gradle

`
      apply plugin: "com.android.application"
      apply plugin: 'com.google.gms.google-services' // <- Add this line
    
    import com.android.build.OutputFile
    
    
    project.ext.react = [
        enableHermes: false,  // clean and rebuild if changing
    ]
    
    apply from: "../../node_modules/react-native/react.gradle"
    
    
    def enableSeparateBuildPerCPUArchitecture = false
    
    
    def enableProguardInReleaseBuilds = false
    
    
    def jscFlavor = 'org.webkit:android-jsc:+'
    def enableHermes = project.ext.react.get("enableHermes", false);
    
    android {
        ndkVersion rootProject.ext.ndkVersion
    
        compileSdkVersion rootProject.ext.compileSdkVersion
    
        defaultConfig {
            applicationId "com.myappname.app"
            minSdkVersion rootProject.ext.minSdkVersion
            targetSdkVersion rootProject.ext.targetSdkVersion
            versionCode 1
            versionName "1.0"
        }
        splits {
            abi {
                reset()
                enable enableSeparateBuildPerCPUArchitecture
                universalApk false  // If true, also generate a universal APK
                include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
            }
        }
        signingConfigs {
            debug {
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }
        buildTypes {
            debug {
                signingConfig signingConfigs.debug
            }
            release {
                // Caution! In production, you need to generate your own keystore file.
                // see https://reactnative.dev/docs/signed-apk-android.
                signingConfig signingConfigs.debug
                minifyEnabled enableProguardInReleaseBuilds
                proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            }
        }
    
        // applicationVariants are e.g. debug, release
        applicationVariants.all { variant ->
            variant.outputs.each { output ->
                // For each separate APK per architecture, set a unique version code as described here:
                // https://developer.android.com/studio/build/configure-apk-splits.html
                // Example: versionCode 1 will generate 1001 for armeabi-v7a, 1002 for x86, etc.
                def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
                def abi = output.getFilter(OutputFile.ABI)
                if (abi != null) {  // null for the universal-debug, universal-release variants
                    output.versionCodeOverride =
                            defaultConfig.versionCode * 1000 + versionCodes.get(abi)
                }
    
            }
        }
    }
    
    dependencies {
        implementation fileTree(dir: "libs", include: ["*.jar"])
        //noinspection GradleDynamicVersion
        implementation "com.facebook.react:react-native:+"  // From node_modules
    
        implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    
        debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
          exclude group:'com.facebook.fbjni'
        }
    
        debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
            exclude group:'com.facebook.flipper'
            exclude group:'com.squareup.okhttp3', module:'okhttp'
        }
    
        debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
            exclude group:'com.facebook.flipper'
        }
    
        if (enableHermes) {
            def hermesPath = "../../node_modules/hermes-engine/android/";
            debugImplementation files(hermesPath + "hermes-debug.aar")
            releaseImplementation files(hermesPath + "hermes-release.aar")
        } else {
            implementation jscFlavor
        }
    }
    
    task copyDownloadableDepsToLibs(type: Copy) {
        from configurations.implementation
        into 'libs'
    }
    
    apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

`

and google-services.json has been add in android/app folder.

Force close just in android device, in ios my application is run well. I think problem come from in android configuration

RN Version : 0.65

**Comment by mikehardy** [comment]
Hi there. You did not follow our bug template, package.json is missing for instance, so I will close this 

You should watch adb logcat and get the stack trace of the crash, it'll lead you to the problem
