### ISSUE TITLE
Fallback link on desktop

### ISSUE THREAD

**Issue by phillipcmittmann** [invertase/react-native-firebase#5738]
So, I'm trying to figure out how to configure a fallback link, when I manually create a dynamic link, that redirects in desktops. When using fallbackUrl in the builder, the Promise returned contains both AFL and IFL parameters not encoded.

```
const link = await dynamicLinks().buildLink({
                link: `https://myapp.example.com/todayEdition/${Moment().format('YYYYMMDD')}`,
                domainUriPrefix: 'https://myapp.example.com',
                android: {
                    packageName: 'com.myapp.example,
                    fallbackUrl: 'www.google.com.br'
                },
                ios: {
                    bundleId: 'com.myapp.example',
                    fallbackUrl: 'www.google.com.br'
                },
            });
```

The snipped above results in:

```
https://myapp.example.com?afl=www.google.com.br&apn=com.myapp.example&ibi=com.myapp.example&ifl=www.google.com.br&link=https%3A%2F%2Fmyapp.example.com%2FtodayEdition%2F20210923
```

When opening in mobile, the links redirects/open the application like it should. On desktop, it says: "Dynamic Link Not Found
Failed to resolve uri domain prefix: https://myapp.example.com/todayEdition", instead of redirecting to Google as expected.

The domain prefix is already registered in the console. 

React-Native - 0.64.2
Dynamic Links - 12.1.0

**Comment by mikehardy** [comment]
Opening a discussion and issue at the same time just splits the conversation, I've already responded in the discussion you opened - closing this one
