### ISSUE TITLE
Loop inifine when createLocalNotification call on firebase.messaging().onMessage

### ISSUE THREAD

**Issue by sirstevensu** [invertase/react-native-firebase#574]
### Environment

1. Application Target Platform: Android

2. Development Operating System: Windows 7

3. Build Tools: Android SDK 23.0.1

4. React Native version: 0.48.1

5. RNFirebase Version: 3.0.5

6. Firebase Module: Cloud Messaging

```
firebase.messaging().onMessage((message) => {
	//console.log(message);

	if(message.isTrip === '1'){
		Alert.alert( message.title ? message.title : 'Boss Attendance System', 
		 message.body ? message.body: 'Start trip', 
		[	
		    {
		    	text: 'Ignore', 
		    	onPress: () => console.log('Cancel Pressed'), style: 'cancel'}, 
		    {
		    	text: 'Show', 
		    	onPress: () => this.props.navigation.navigate("Trip")}, 
		], { cancelable: false } )	
	}
	else{
		firebase.messaging().createLocalNotification({
		   title: 'My app',     
		   body: 'Hello world',
		   icon: 'ic_launcher',
		   priority: 'high',
		   click_action: 'ACTION',
		   show_in_foreground: true,
		   sound: 'default',
		   opened_from_tray: true,
		   big_text: 'i am large, i am large'
		})
		//console.log(message);
		//this.showMessagging();
		
		// /global.commonAlert(message.body ? message.body: 'Start trip', message.title ? message.title : 'Boss Attendance System');
	}		  	
});
```

Android debug logging [log.txt](https://github.com/invertase/react-native-firebase/files/1437438/log.txt)

**Comment by chrisbianca** [comment]
@sirstevensu Your `createLocalNotification()` call will trigger `onMessage` which will in turn trigger another `createLocalNotification()` call, hence the infinite loop.

This is code that you need to fix - you have to protect against this by looking at the content of the message and detecting whether it should trigger a local notification

**Comment by grifotv** [comment]
@chrisbianca is `createLocalNotification` part of the v3.1?

I'm not sure as it's not listed in the [documentation](https://rnfirebase.io/docs/v3.1.*/messaging/reference/messaging#Methods) and I'm aware you are considering [moving this out](https://github.com/invertase/react-native-firebase/issues/140#issuecomment-305751852) of the main `react-native-firebase` library.

**Comment by chrisbianca** [comment]
@grifotv We haven't made any changes to messaging in v3.0 or v3.1 so anything that worked on v2 will still do so.

This is going to be our primary focus for v3.2.  We haven't decided exactly how we're going to proceed with this, but we'll make sure it's fully documented once we've decided!

**Comment by grifotv** [comment]
@chrisbianca thanks for the quick response!

**Comment by hegelstad** [comment]
I am experiencing the samme issue, however, I am not creating new notifications within onMessage() callback.

What I am doing is opening a uri with react-native Linking API. `Linking.openURL('marketplace://marketplace/tabs/messages/id')`

This link is then handled by the apps uri scheme and handed over to React-Navigation which handles the url.

**Comment by numez** [comment]
@sirstevensu to prevent infinite loop just add a property to message


 
    firebase.messaging().onMessage((message)=>{
      if(message.local_notification) return;
      
      firebase.messaging().createLocalNotification({
        ...message.fcm,
        local_notification: true, // prevent loop
        show_in_foreground: true,
        priority: "high",
      });
    });

**Comment by frangeris** [comment]
@numez if app is in `background` it will show double notification, use this way: 

```javascript
      if (AppState.currentState === 'active') {
        firebase.messaging().createLocalNotification({
          ...notif,
          local_notification: true,
          show_in_foreground: true
        })
      }
```

**Comment by guillermodoghel** [comment]
Same issue here.
`
let FCM = firebase.messaging();

FCM.onMessage((message=>{
    console.log('new message',message);
    if(AppState.currentState=='active'){
    	firebase.messaging().createLocalNotification({
		  title: "My Notification Title",
		  body: "My Notification Message",
		  sound: "default",
		  priority: "high",
		  click_action: "ACTION",
		  icon: "ic_launcher",
		  local_notification: true,
          show_in_foreground: true
		});
    }

}));
`

But Im still having the  looping issues
