### ISSUE TITLE
Always throwing some link 

### ISSUE THREAD

**Issue by aneena-thomas** [invertase/react-native-firebase#5742]
Dynamic-link always throwing some link even I log out and come back to the app. It should throw URL only if is from dynamic link.

@Salakar

**Comment by mikehardy** [comment]
Hi there!
You actively erased the issue template, that would have contained the information we need to troubleshoot.
There is no example that shows us how to reproduce https://stackoverflow.com/help/minimal-reproducible-example

**Comment by aneena-thomas** [comment]
Issue:
Dynamic-link always throwing some link even I log out and come back to the app. It should throw URL only if is from dynamic link.

**Reproducible Example:**

1. Click a dynamic link from safari or any app, then it will redirected to my app and gave some redirection some other pages. Its works fine
2. Then I logout from the app, then again login to my app, it again go the link pages. Means link always there.
3. If once I open my app from dynamic link it always throw some url.
4. In android its working fine

I cant able to share my project here, its a client project.

**Code used for getting the link is,**

 useEffect(() => {
    dynamicLinks()
      .getInitialLink()
      .then((link) => {
        handleDynamicLink(link);
      });
    const linkingListener = dynamicLinks().onLink(handleDynamicLink);
    return () => {
      linkingListener();
    };
  }, []);
  

Package version:  "@react-native-firebase/dynamic-links": "^11.3.3",
React native version: "0.63.4"

cc: @mikehardy

**Comment by mikehardy** [comment]
Please use current stable user versions (12.8.0 here at the moment) and attempt to reproduce.

You mention "logout" and "again login" I don't see the code for that, I do not know what "logout" and "again login" mean, do you mean you close the app completely? Or just logout in the app but the app is open?

If you "open my app from dynamic link" it should trigger the link every time. You click a link, you should have API methods related to it (either initialLink or onLink) give you the link.

Please understand that the issue quality here is very low - it started with no information, and now you're posting an incomplete example using outdated software. With apologies, it's very difficult to help you.

**Comment by aneena-thomas** [comment]
Ok will try in new version,

Yes, I log out from the app.

Iam using the below code for getting the link,


useEffect(() => {
dynamicLinks()
.getInitialLink()
.then((link) => {
handleDynamicLink(link);
});
const linkingListener = dynamicLinks().onLink(handleDynamicLink);
return () => {
linkingListener();
};
}, []);


I got the dynamic link from the above code. But after logout from the app and log in again, it again throws the old link. 

Dynamic-link removed only after quitting the app.

**Comment by mikehardy** [comment]
That's correct behavior I think - the initial link is not "consumed" it is always there if you get it again.
I use app-wide state storage (like redux) to store the initial link and to store whether I have handled it or not, and I do it once on app startup in bootstrap code (not in login code), then after login I check to see if I have already handled it or not

That's the usage pattern that should work here
