### ISSUE TITLE
App crash on startup - (Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: bundleIdentifier != nil')

### ISSUE THREAD

**Issue by farajshuaib** [invertase/react-native-firebase#5744]
After installing react native firebase messaging package, the app crash on startup
xcode shows the following error:

<img width="896" alt="Screen Shot 2021-09-24 at 8 59 36 PM" src="https://user-images.githubusercontent.com/46637985/134727363-f67ba920-57c6-41e2-b123-4e9e9fe753a9.png">

**my pod file is ass follows:**

`require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path

target 'taqeem' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
  )

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"

  target 'taqeemTests' do
    inherit! :complete
  end

  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end`

**Environment**

1. iOS 14.5
2. macOS Big Sur
3. Xcode
4. React Native version: 0.64):
5. react native firebase messages Version : 11.5
6. react native firebase app Version : 11.5

**Comment by mikehardy** [comment]
Please respect the issue template, you deleted huge useful chunks of it, so I will close this issue.
Also please note that troubleshooting on old versions is inefficient, please try again with 12.8.0, and examine this script which shows every single step necessary to integrate correctly https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh
If you can still reproduce after upgrading please open a new issue *with the information requested in the template* and including the **text** of the error stack trace so we may troubleshoot
