### ISSUE TITLE
Firestore - "delete()" after "where()" apparently is not deleting but pass a promise

### ISSUE THREAD

**Issue by maueli** [invertase/react-native-firebase#5745]
Basically, firestore find the document with condition "nombre", "==",props.infoitem.nombre but not delete it. The strange thing is 
the promise is working... in the console appear "Deleted". It this a bug?

`            firestore().collection("collection1").doc(uid).collection("subcollection1")
            .where("nombre", "==",props.infoitem.nombre).get()
            .then(snapshots=>{
                snapshots.docs.forEach(e=>{
                    e.ref.delete().then( () => console.log("Deleted") );
                })                
            })
`

**Comment by mikehardy** [comment]
This sounds like a usage question, have you tried on stackoverflow?

We're looking for definite issues here, with our issue template filled in (so we can reproduce etc) - basically an issue is something that will result in a change to the module, whereas questions are best asked on stackoverflow
