### ISSUE TITLE
Could not locate configuration file: 'GoogleService-info.plist'

### ISSUE THREAD

**Issue by DavideValdo** [invertase/react-native-firebase#576]
When I start the application from my .xcworkspace it crashes after splash screen and this gets logged:

```
2017-11-02 14:53:07.429164+0100 myapp[921:13765] [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
2017-11-02 14:53:07.429768+0100 myapp[921:13765] [Firebase/Core][I-COR000005] No app has been configured yet.
2017-11-02 14:53:07.870175+0100 myapp[921:13087] *** Terminating app due to uncaught exception 'com.firebase.core', reason: '`[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.'
```

1. The file is correctly placed in `ios/myapp/`
2. I also drag-and-drop the file in XCode here:
![screen shot 2017-11-02 at 14 58 35](https://user-images.githubusercontent.com/26572302/32329799-61dcd348-bfde-11e7-98a3-a4721f8e8551.png)

react-native 0.49.3
RNFirebase 3.0.3
yarn 1.2.1

**Comment by DavideValdo** [comment]
After struggling with this for a while and right after opening this issue, I managed to solve this by:

1. Selected the .plist file inside XCode
2. On the rightmost part of the screen I could see under "Target Membership" that my project's name was not flagged
3. Flagging it starts the application correctly

Really don't know what happened because project used to start fine until yesterday.

**Comment by rochefort8** [comment]
Same problem happened to me, and following information gave me a way to fix for me,

https://github.com/firebase/quickstart-ios/issues/5

Hope this help

**Comment by olkunmustafa** [comment]
Tat solution saves my day.

https://github.com/firebase/quickstart-ios/issues/5#issuecomment-424437087

**Comment by ipolx** [comment]
> After struggling with this for a while and right after opening this issue, I managed to solve this by:
> 
> 1. Selected the .plist file inside XCode
> 2. On the rightmost part of the screen I could see under "Target Membership" that my project's name was not flagged
> 3. Flagging it starts the application correctly
> 
> Really don't know what happened because project used to start fine until yesterday.
Best answer on the internet ! Thanks !

**Comment by RowanG1** [comment]
The above alone did not help me. This was needed in info.plist:
```
<!-- Info.plist -->
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleURLName</key><string>GoogleSignIn</string>
    <key>CFBundleURLSchemes</key>
    <array>
      <!-- paste the literal REVERSED_CLIENT_ID value -->
      <string>com.googleusercontent.apps.XXXXXXXXXXXX-XXXXXXXXXXXX</string>
    </array>
  </dict>
</array>
```
