### ISSUE TITLE
@react-native-firebase\dynamic-links cannot find symbol

### ISSUE THREAD

**Issue by shivam0831** [invertase/react-native-firebase#5762]
I am getting the following error after using npm install @react-native-firebase/dynamic-links. I am not able to solve this issue, any solutions?
```
D:\myapp\node_modules\@react-native-firebase\dynamic-links\android\src\main\java\io\invertase\firebase\dynamiclinks\ReactNativeFirebaseDynamicLinksModule.java:227: error: cannot find symbol
                    Bundle linkUtmParameters = linkData.getUtmParameters();
                                                       ^
  symbol:   method getUtmParameters()
  location: variable linkData of type PendingDynamicLinkData
D:\myapp\node_modules\@react-native-firebase\dynamic-links\android\src\main\java\io\invertase\firebase\dynamiclinks\ReactNativeFirebaseDynamicLinksModule.java:458: error: cannot find symbol
                                      pendingDynamicLinkData.getUtmParameters()))));
                                                            ^
  symbol:   method getUtmParameters()
  location: variable pendingDynamicLinkData of type PendingDynamicLinkData
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-firebase_dynamic-links:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by mikehardy** [comment]
Hi there! You've ignored our issue template (you actively deleted it), and it provides the information that would help us troubleshoot, so I will close this issue.

I'm guessing you have an outdated version of the react-native firebase-android-sdk, as current versions provide this method https://firebase.google.com/docs/reference/android/com/google/firebase/dynamiclinks/PendingDynamicLinkData#getUtmParameters() and are referenced correctly from `@react-native-firebase\app`

It could be that you have a stale override for the android sdk if for some reason you are overriding them https://rnfirebase.io/#android

It could be that the versioning of react-native-firebase is incorrect https://invertase.io/blog/react-native-firebase-versioning or that your project is unclean and needs a really fresh clean+build `npx react-native-clean-project`
