### ISSUE TITLE
App / Expo plugin - iOS might break with Expo SDK 43

### ISSUE THREAD

**Issue by barthap** [invertase/react-native-firebase#5788]
> Not sure where to post it, it's not a problem yet, feel free to move/edit this issue.

Because of [this commit in expo](https://github.com/expo/expo/commit/9781212eb3ec89a0b184da712ec7ca4e5ecc725b#diff-bff087577a5c9701fc698b349742e47dd252ee849307704985df6799de62f405) (scroll to `AppDelegate.m`),
The `@rnfb/app` plugin will likely stop working, because of [this regex](https://github.com/invertase/react-native-firebase/blob/master/packages/app/plugin/src/ios/appDelegate.ts#L19-L23)

We need to find a way to make that regex work more flexible - to support both old and new `AppDelegate` template.

**Comment by mikehardy** [comment]
Interesting - the link for `this regex` wasn't coming out to a useful spot for me, so I couldn't put 1+1 together to make the 2 you were intending :-). Could you check?

**Comment by barthap** [comment]
A bunch of updates _(if any link posted here fails, just lmk - sometimes I have this issue with github too)_:

- There is a more universal regex in one of unofficial plugins: [link to line 122 in withIosGoogleCast.ts](https://github.com/expo/config-plugins/blob/f0d957456eaf134b7301e4bb4d42d80f5cef2c4b/packages/react-native-google-cast/src/withIosGoogleCast.ts#L122)
   
   It looks terrible but it seems to work: [regex101.com example](https://regex101.com/r/MeYGTo/1)
- If you scroll down the code above, there's a `mergeContents()` ([source here - line 35](https://github.com/expo/expo-cli/blob/fef6cc3adf7b9d45f46e42e79dfd88a6a8b704a0/packages/config-plugins/src/utils/generateCode.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L35)) method available, which tries to add/replace code in a more controlled manner + adds comments about auto-generated places & some hashes. I haven't tried this functionality yet, but looks promising.

- The same issue happens to [some built-in expo plugins](https://github.com/expo/expo/blob/sdk-43/packages/expo-firebase-core/plugin/src/withFirebaseCore.ts#L26-L30) 🤷 - Evan Bacon declared to follow up this - we can just wait, then do the same here 😉 but having the tools above we could act early too.

**Comment by EvanBacon** [comment]
For `expo-firebase-core`, we'll be utilizing the `expo-modules-core` AppDelegate proxy system ([PR](https://github.com/expo/expo/pull/14750)) which is the long term replacement for config plugin regular expressions. 
We'll investigate some non-intrusive options for other packages to support the proxy as well but in the meantime, our new default [`AppDelegate.m`](https://github.com/expo/expo/blob/master/templates/expo-template-bare-minimum/ios/HelloWorld/AppDelegate.m) template is nearly identical (if not completely identical) to the default React Native `AppDelegate.m` template (of the matching version), this means that Expo config plugins which were accounting for both will continue working, example [react-native-maps](https://github.com/expo/expo-cli/blob/4477bdde3c768e4ab822fb43224e94f85453683b/packages/config-plugins/src/ios/Maps.ts#L12).

I'd recommend updating the RNFirebase plugin to account for both (like maps) to avoid needing any versioning.
