### ISSUE TITLE
Typescript: Property 'auth' does not exist on type 'typeof FireBase'

### ISSUE THREAD

**Issue by mlandauer** [invertase/react-native-firebase#579]
### Issue

The typescript type definition seems be slightly out of sync with the code. I have some simple working code that uses react-native-firebase. It runs without any issue.

However, the typescript compiler throws the following error:
```
error TS2339: Property 'auth' does not exist on type 'typeof FireBase'.
```

The code looks something like this:
```
import * as React from 'react'
import {
  View,
  TextInput,
  Button,
} from 'react-native'
import firebase from 'react-native-firebase'

interface LoginState {
  email: string;
  password: string;
}

export default class Login extends React.Component<{}, LoginState> {
  ...

  onLogin() {
    firebase.auth().signInWithEmailAndPassword(this.state.email, this.state.password)
  }

  ...
}

```

The line that typescript (with the current type definitions) doesn't like is:
```
firebase.auth().signInWithEmailAndPassword(this.state.email, this.state.password)
```

It appears that the typescript definition is saying that `firebase` is a class while in the actual code `firebase` is an object instantiated from that class.

I think, from my somewhat limited experience of react-native-firebase, that the library used to return a class but this was changed in https://github.com/invertase/react-native-firebase/commit/80ae8425ce07e108156000294684da694d3fe1dc

So it looks like the typescript definition needs updating to match the actual code.

### Environment

1. Application Target Platform: 
iOS

2. Development Operating System: 
macOS Sierra

3. Build Tools: 
Xcode

4. React Native version: 
0.49.5

5. RNFirebase Version: 
3.0.6

6. Firebase Module: 
auth

**Comment by jorgutdev** [comment]
Hello, this also happened to me, I resolved the issue calling `firebase.app().auth()` instead of `firebase.auth()`.

Hope it helps!

**Comment by fieryorc** [comment]
The type definition is out of date. Needs to be updated. +1

**Comment by Salakar** [comment]
@taljacobson made the original typings and we're not users of typescript ourselves, so it's not something we're overly familiar with or keep updated for that reason, having said that, 'I think' i've pushed up a correct update for `auth` typings.

However, ideally they need a full rewrite, they're 2 major versions out of date and I think this same issue will happen on other modules except for auth and database. So if someone would like to champion this and send in a PR to fully update them that'd be awesome! 👍

**Comment by danielw93** [comment]
Hey! 
We're using this project in a typescript setup and I am currently slowly going through the definitions file and updating it piece by piece to the reflect the current master. 
I am pretty new to TypeScript myself so it could take a while but I will keep you updated on the progress.

For now I have forked the project and I am working on a new branch `update-typings`

**Comment by chrisbianca** [comment]
@danielw93 If you're happy that the type changes you've made are working then please feel free to submit a PR request of where you've got to. We'd prefer incremental updates as they're easier to look over!!  I've just had a look at your branch and in particular, your auth ones would be a great addition.

**Comment by danielw93** [comment]
Right! Didn't think about that. 
I've isolated my changes for the `auth` module and submitted pull request #764

**Comment by quead** [comment]
I still got this problem and I've solved by importing in component:
`import { auth } from 'firebase';
`
and replaced
`new firebase.auth.GoogleAuthProvider();` with `new auth.GoogleAuthProvider();`

**Comment by Gideon14th** [comment]
> Hello, this also happened to me, I resolved the issue calling `firebase.app().auth()` instead of `firebase.auth()`.
> 
> Hope it helps!

**Comment by sanket9006** [comment]
https://stackoverflow.com/questions/69139443/property-auth-does-not-exist-on-type-typeof-import-firebase-auth/69899138#69899138

https://firebase.google.com/docs/web/modular-upgrade

**Comment by sanket9006** [comment]
> I have tried the following
> 
> 
> import * as firebase from 'firebase/app' (top) .. firebase.app().auth() (inside function)
> 
> 
> import { Firebase } from '@ionic-native/firebase';
> 
> it does not get rid of the error ..is keeps on saying "Property 'app' does not exist on type 'typeof ' "

**Comment by Hilati-Ashref** [comment]
For firebase v10 (it can work for other versions) use the following code: (worked for me)

    `import firebase from 'firebase/compat/app';
    import 'firebase/compat/auth';
    import 'firebase/compat/firestore';
    
    firebase.initializeApp(firebaseConfig);
    
    const auth = firebase.default.auth();
    const database = firebase.default.database();`
