### ISSUE TITLE
[🐛] Firebase-messaging don't receive notification when first install app on production build

### ISSUE THREAD

**Issue by trantrongkim98** [invertase/react-native-firebase#5792]
##Version
- 12.9.0
- IOS
## Device
- on all devices of my team
## Description
- App don't receive notification before second startup on production build
- **This is critical bug**
- I see this [issue](https://github.com/invertase/react-native-firebase/issues/4299) closed but it don't resolved problem 

Steps:
 Install app from AppStore -> SignIn to get token ==> don't receive notification
-> quick app -> open app again ==> received notification

**Comment by mikehardy** [comment]
I don't think there is anything our module here (react-native-firebase) is doing, I think this will be at the firebase-ios-sdk level.

Have you checked their issue list? https://github.com/firebase/firebase-ios-sdk/issues
Have you tried to reproduce it directly via their quickstart? https://github.com/firebase/quickstart-ios/tree/master/messaging

I'm guessing if it is a problem it will show up in their native quickstart, and they will accept a reproduction based on that for issue creation in their repo

The previous issue had reported success from people, so this is unexpected. Sorry it is happening in your project

**Comment by trantrongkim98** [comment]
> I don't think there is anything our module here (react-native-firebase) is doing, I think this will be at the firebase-ios-sdk level.
> 
> Have you checked their issue list? https://github.com/firebase/firebase-ios-sdk/issues Have you tried to reproduce it directly via their quickstart? https://github.com/firebase/quickstart-ios/tree/master/messaging
> 
> I'm guessing if it is a problem it will show up in their native quickstart, and they will accept a reproduction based on that for issue creation in their repo
> 
> The previous issue had reported success from people, so this is unexpected. Sorry it is happening in your project

Thank you. My used react-native-notification-badge conflicted with firebase-messaging and i used notifee to instead it, after it worked for me
