### ISSUE TITLE
Firebase.auth().authenticated not supported in 3.X.X?

### ISSUE THREAD

**Issue by wbattel4607** [invertase/react-native-firebase#580]
### Issue

I just upgraded from 2.1.3 to 3.0.6. I used `Firebase.auth().authenticated` in my Login component to figure out if the Facebook authentication was completed or cancelled. This worked fine in 2.1.3 but doesn't in 3.0.6. Looking at the new docs (website docs look nice by the way, good job) I don't see that property listed- but I do see it when I switch to the 2.X.X docs. Was this removed and/or is there an alternative? Thanks.

### Environment

1. Application Target Platform: Tested on iOS 10.3.1

2. Development Operating System: Tested on macOS Sierra

3. Build Tools: Tested on Xcode 9

4. React Native version: 0.50.1

5. RNFirebase Version: 3.0.6

6. Firebase Module: Authentication (auth)

**Comment by chrisbianca** [comment]
@wbattel4607 Although `authenticated` worked on v2.X it was unreliable in its approach and was inconsistent with the web SDK which we're trying to adhere to as closely as possible.

Your best approach is to make use of the `firebase.auth().onAuthStateChanged()` listener documented here: https://rnfirebase.io/docs/v3.0.*/auth/reference/auth#onAuthStateChanged

This will be fired as soon as the auth state has been resolved by Firebase.  You can find out some more here: https://firebase.google.com/docs/auth/web/start#set_an_authentication_state_observer_and_get_user_data
