### ISSUE TITLE
authentication is not persistent

### ISSUE THREAD

**Issue by kriss1897** [invertase/react-native-firebase#582]
### Issue
authentication is not persistent. What should I do to make it persistent? Please Help.

### Environment
1. React Native version: 0.49.3
2. RNFirebase Version: 3.0.5
3. Firebase Module: Auth

**Comment by chrisbianca** [comment]
@kriss1897 Authentication is most definitely persistent, however when the app starts there is a delay before the authentication state is available.

You need to make use of the `firebase.auth().onAuthStateChanged()` listener as documented here: https://rnfirebase.io/docs/v3.0.*/auth/reference/auth#onAuthStateChanged

There is some more information in the official Firebase guide: https://firebase.google.com/docs/auth/web/start#set_an_authentication_state_observer_and_get_user_data

**Comment by kriss1897** [comment]
@chrisbianca Thanks.
I have developed few react-native apps now. Now I am thinking of doing some open source work. 
What should I do to contribute to this library.

cheers,
shashank
