### ISSUE TITLE
[🐛] :fire: Expo run:android fails with app.json changes but succeeds with manual build.gradle changes

### ISSUE THREAD

**Issue by CMadden8** [invertase/react-native-firebase#5822]
## Issue

The issue is identical to issue described below for android - ie 'No Firebase App [DEFAULT] has been created' error when running expo run:android:

https://github.com/invertase/react-native-firebase/issues/4880

Expo is being used and I've followed all instructions from @react-native-firebase 'Get Started' with Expo as well as https://bartlomiej-klocek.medium.com/how-to-integrate-react-native-firebase-into-expo-d34712eaf64d

I managed to 'fix' the problem by modifying the build.gradle and app/build.gradle files to contain the modifications suggested by firebase for these files (ie add classpath 'com.google.gms:google-services:4.3.10' etc)

I then manually added google-services.json to the android/app folder.

Running expo run:android now correctly connected to firebase and firestore and returned some test docs from a test collection.

But will there be side effects to this approach? 

It seems as though the suggested app.json modifications aren't being picked up.

` "android": {
      "googleServicesFile": "./google-services.json",
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "com.test"
    },`

I've also added the plugin.

`"plugins": [
      "@react-native-firebase/app"
    ]`

The google-services.json file was on the same level as app.json - ie ./google-services.json.

I'm not sure what automation is going on with the suggested app.json changes, but it looks like it doesn't work. 

FYI - the project is completely fresh. No modifications to anything - the only thing that has been added is @react-native-firebase.

I'm concerned that changing the build.gradle files directly and moving the google-services.json is the wrong approach. Obviously they'll be overwritten anytime the android folder is deleted. So I assume that's the purpose of the app.json changes - to prevent the need to keep modifying these files.

**Comment by CMadden8** [comment]
It looks like I've discovered the problem. When using expo plugins, it seems it's necessary to run `expo prebuild --clean` before running `expo run:android`, as per the documentation on expo [here](https://docs.expo.dev/workflow/customizing/).

The issue seems to be in relation to documentation rather than the code.

I believe the [above article](https://bartlomiej-klocek.medium.com/how-to-integrate-react-native-firebase-into-expo-d34712eaf64d) does a good job going into the detail of the set up with expo.

The prebuild command is mentioned, but it's not explicitly stated that you must run it after adding the plugin to app.json.

Closing the issue.

**Comment by mikehardy** [comment]
Hey @CMadden8 - if there is any location in our documentation that could be improved (and it sounds like it...) please hit the edit button on any of the relevant pages and GitHub will walk you through a quick docs PR to help all future folks. Thanks!
