### ISSUE TITLE
[🐛] Not receiving FCM messages after deleteToken() on IOS, getAPNSToken() is null

### ISSUE THREAD

**Issue by EStrehlau** [invertase/react-native-firebase#5823]
## Issue

messaging().getAPNSToken() returns null after, FCM messages do not get delivered:
await messaging().deleteToken();
await messaging().registerDeviceForRemoteMessages();

I think this regression was introduced by 491436fe31cc4c0b8fafc3af91a62d581bc495a0.

APNS gets reset to NULL after calling deleteToken, but since we return early setAPNS never gets called again remaining NULL.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
"dependencies": {
    "@react-native-firebase/app": "^12.9.3",
    "@react-native-firebase/auth": "^12.9.3",
    "@react-native-firebase/messaging": "^12.9.3",
    }
 }

```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "messaging_ios_auto_register_for_remote_messages": false
  }
}

```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 290.56 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: ^0.63.3 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `12.9.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `Messaging`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by EStrehlau** [comment]
Apparently there is more to this issue, reverting the return is not enough.

We need to properly wait for setAPNS being called before calling getToken. Otherwise the FCM token does not work.

I tried to work around this by calling unregisterDeviceForRemoteMessages and waiting on it before calling registerDeviceForRemoteMessages. But it appears that isDeviceRegisteredForRemoteMessages does not get set straight after awaiting the unregisterDeviceForRemoteMessages call.

To work around this issue I have:
removed the condition for doing the early resolve entirely, always running the callbacks and resolving the promise even if isDeviceRegisteredForRemoteMessages is true.
I call unregisterDeviceForRemoteMessages after deleteToken to force a new APNS token, it appears that even if isDeviceRegisteredForRemoteMessages is true a new token is generated.
I await registerDeviceForRemoteMessages and then call getToken.

There is an additional issue:
There can only be one registerDeviceForRemoteMessages inflight at the time, it overrides the resolution callbacks of the earlier invocation when running, causing its promise to never resolve.

**Comment by mikehardy** [comment]
@EStrehlau I'd be happy to merge anything reasonable here if you can propose a PR where the changes are commented as you have above with an explanation for any particular bit is needed. I don't doubt at all this is a touchy area, possibly not working, and needs careful repair but it's unfortunately a very difficult part of the codebase since our chosen testing harness unfortunately does not run on real iOS devices, so we haven't had good luck conclusively/automatically probing it with tests and making it perfect

**Comment by mikehardy** [comment]
Please feel free to reopen this or propose a PR - but at the moment this is not actionable for us as I haven't been able to reproduce
