### ISSUE TITLE
[RTDB] How to cleanup .off() of listener .on complex ( listener .on in listener .on('child_add...) 

### ISSUE THREAD

**Issue by paddypure** [invertase/react-native-firebase#5824]
useEffect(() => {
      
        const ChannelRef = database().ref(`/user/${uid}/channel`);
        ChannelRef.keepSynced(true);
        ChannelRef.on('child_added', channel_id => {
              var startTime = ....
              const threadRef = database().ref(`/cNl/${xx.key}/TD/${f}`).orderByKey().startAt(startTime);
              threadRef.keepSynced(true);
              threadRef.on('value', thread => {.     <--------------------------------   How to cleanup this listenner ?
                dispatch({
                   type: 'AddThread',
                   payload: thread.val()
                });
        })

        return () => {
              // CleanUp listenner
               ChannelRef.off();
              threadRef.keepSynced(false); 
             
              // How to cleanup threadRef = database().ref(`/cNl/${xx.key}/TD/${f}`).orderByKey().startAt(startTime) ?
       }
      
    }, []);

**Comment by mikehardy** [comment]
Hi there, for general project coding support I think stackoverflow is the place to go, this is not actually an issue that will result in a change to the library, and ignores the issue template completely so I'm going to close this
