### ISSUE TITLE
[🐛]arrayUnion works like arrayRemove in 12.9.0

### ISSUE THREAD

**Issue by Innokentiy213** [invertase/react-native-firebase#5826]
Sometimes arrayUnion works like arrayRemove.
promise catches nothing.

my Code:
`
await firestore()
    .collection('users')
    .doc(uid)
    .update({
      measures: firestore.FieldValue.arrayUnion(last? 
        {
          date: firestore.Timestamp.fromMillis(last.dateMs + 1000),
          buttocks: measure.buttocks,
          hips: measure.hips,
          hands: measure.hands,
          stomach: measure.stomach,
        }
        : 
        {
          date: firestore.Timestamp.fromMillis(measure.dateMs + 1000),
          buttocks: measure.buttocks,
          hips: measure.hips,
          hands: measure.hands,
          stomach: measure.stomach,
        }
      ),
    })    
    .catch(err => Alert.alert('Error', err))
    .then(() => {
      if (last) {
        dispatch(addMeasureSuccess({
          ...measure,
          dateMs: last.dateMs+1000
        }));
      } else {
        dispatch(addMeasureSuccess(measure))
      }
    });
`
last - is null or last measure in this day

**Comment by mikehardy** [comment]
Hi there! You have ignored our template, so we do not have enough information to work with. Please do not ignore issue templates in repositories when logging issues
