### ISSUE TITLE
[Firestore] onSnapshot is not fired if the query is empty

### ISSUE THREAD

**Issue by thevishnupradeep** [invertase/react-native-firebase#583]
How do we check if the query data set is empty or not from onSnapshot listener?

**Comment by thevishnupradeep** [comment]
It was an issue with the query indexing. For anyone with the same issue, just follow these instructions from the [docs](https://firebase.google.com/docs/firestore/query-data/indexing).

**Comment by jeremyfrancis** [comment]
> It was an issue with the query indexing. For anyone with the same issue, just follow these instructions from the [docs](https://firebase.google.com/docs/firestore/query-data/indexing).

Not sure how this is suppose to fix it? Could you provide more instruction please. Thank you!

**Comment by acrdlph** [comment]
Also had the same problem caused by a missing index.

@jeremyfrancis Try doing a regular `get()` instead of a snapshot listener - then you will get an error in your console with a link to create the missing database index.
