### ISSUE TITLE
Slow response on first firestore.document.get() and Storage.getDownloadUrl()

### ISSUE THREAD

**Issue by kkusanagi** [invertase/react-native-firebase#584]
I'm not sure this issue count as react-native-firebase or just Firebase. so I add here.

I'm using emulator Nexus 5X and real phone Huawei P8 android 6.0.

After signing in using firebase.auth(), I would like to update firestore data with current signing in user and get image download url. 

In Emulator, 
debug version: smooth
release version: smooth

In Phone Huawei P8,
debug version: almost smooth (just a bit delay)
release version: delay response for over 60 seconds for first request of document.get() and over 60 seconds of storage.getdownloadURL()

Of course, both of them, I use same account to sign in. 
Anyone meet this problem, please state what had I'm missing to fix this problem.

for coding, as below

         firebase.auth().onAuthStateChanged((user) => {
      
           //state.isLoading = false;
           if (user) {
          var displayName = user.displayName;
          var email = user.email;
          //var emailVerified = user.emailVerified;
          var photoURL = user.photoURL;
          //var isAnonymous = user.isAnonymous;
          var userid = user.uid;
          //var providerData = user.providerData;
          this.setState({progress:'c...'});
         
          //**starting to delay response from here**          
          dbFireStore.collection('user').where('email','==',email).get().then((querySnapshot)=>{
          
          this.setState({progress:'ccc...'});

          if (querySnapshot.empty){
            this.setState({progress:'0...'});
            var arrUser = {
              authentication_id: userid,
              name: displayName,
              search_name: displayName.trim().toLowerCase(),
              email: email,
              ispublic: true,
              created: firebase.firestore.FieldValue.serverTimestamp(),
              last_update: firebase.firestore.FieldValue.serverTimestamp()
            };
            dbFireStore.collection('user').doc(userid).set(arrUser).then((docRef)=>{
              global.obj_user = {
                  user_id: docRef.id,
                  name: displayName,
                  email: email
              };
              this.props.navigation.dispatch(resetMainAction);
            });
          }else{
            this.setState({progress:'d...'});
            let document = querySnapshot.docs[0];
            global.obj_user = {
                user_id: document.id,
                name: document.data().name,
                email: email
            };

            dbFireStore.collection('user').doc(document.id).update({
              last_update: firebase.firestore.FieldValue.serverTimestamp()
            });
            this.setState({progress:'e...'});
            if (document.data().image_path !== undefined){
              this.setState({progress:'f...'});
              
              //**starting to delay response from here**
              firebase.storage().ref(document.data().image_path).getDownloadURL().then((url)=>{
                this.setState({progress:'g...'});
                global.obj_user.image_path = document.data().image_path;
                global.obj_user.image_url = url;

                this.props.navigation.dispatch(resetMainAction);
              });
            }else{
              this.props.navigation.dispatch(resetMainAction);
            }
          }
        });
      } else {
       ...
      }
    });

 

### Environment

1. Application Target Platform: Android

2. Development Operating System: Mac OS Sierra

3. Build Tools: 25.0.3

4. React Native version: 0.48.3

5. RNFirebase Version: react-native-firebase@3.0.6

6. Firebase Module: Firestore, Storage

**Comment by chrisbianca** [comment]
@kkusanagi Not sure how best to help with this.  If it's working fine with your debug version then it's not likely to be an RNFirebase issue.

I'm going to close, but please reopen if you manage to prove that it's something in RNFirebase causing the problem.
