### ISSUE TITLE
(0 admob.default) is not a function. (in, '(0, _admob is undefined)

### ISSUE THREAD

**Issue by saeedsagacious** [invertase/react-native-firebase#5842]
in my site banner add is working but interstitial add is not working and then throw error

**Comment by mikehardy** [comment]
Hi there - admob has been removed upstream from firebase by google, so we have removed it here with version 11.5 - current versions have no admob
I've been working on extracting the code and bringing it up as a separate repo and unfortunately it's a bit slow but it will live here https://github.com/invertase/react-native-google-ads

You should log this over there so it will receive attention *when* the repo is up and running, but it won't receive attention here, sorry

#5329
