### ISSUE TITLE
remoteConfig().getAll() return undefined is not an object (evaluating 'Object.keys(this._values)')

### ISSUE THREAD

**Issue by AghaShayan123** [invertase/react-native-firebase#5854]
useEffect(() => {
      getConfig()
      .then(res => console.log(res)
      .catch(err => console.log(err.message))
   }, [])

   const getConfig = async () => {
     const firebase = await remoteConfig().getAll();
     return firebase
  }

It return undefined is not an object (evaluating 'Object.keys(this._values)')

**Comment by mikehardy** [comment]
We can reopen if you include version information as requested in the template you actively deleted

**Comment by mikehardy** [comment]
Also if reproducible on current versions please include full stack trace thrown, these are all things you would need if someone brought the problem to you I believe

**Comment by AghaShayan123** [comment]
> Also if reproducible on current versions please include full stack trace thrown, these are all things you would need if someone brought the problem to you I believe

These are my current versions list

    "react": "17.0.2",
    "react-native": "0.66.0",
    "@react-native-firebase/analytics": "^13.0.1",
    "@react-native-firebase/app": "^13.0.1",
    "@react-native-firebase/auth": "^13.0.1",
    "@react-native-firebase/firestore": "^13.0.1",
    "@react-native-firebase/in-app-messaging": "^13.0.1",
    "@react-native-firebase/messaging": "^13.0.1",
    "@react-native-firebase/remote-config": "^13.0.1",

**Comment by mikehardy** [comment]
Okay, I can see the problem. I'm going to increase validation in the effected area, but this is at heart a usage issue. It should not crash, but you are not using it correctly.

Prior to calling getAll or getValue, you must set defaults, and fetchAndActivate, until then you may not assume there is anything useful in the config's internal state, and in fact it is uninitialized at the moment

From our docs - https://rnfirebase.io/remote-config/usage#default-values

> Before fetching the parameters from Firebase, it is first important to set some default values

And then again a very prescriptive statement in the next chunk https://rnfirebase.io/remote-config/usage#fetch--activate

> Before reading the values from Firebase, we first need to pull them from Firebase (fetching) & then enable them on the device (activating). The fetchAndActivate API combines both tasks into a single flow

I am certain that will resolve  your issue, and result in useful results so it will actually resolve the issue for you
