### ISSUE TITLE
remoteConfig().getAll() return undefined is not an object (evaluating 'Object.keys(this._values)')

### ISSUE THREAD

**Issue by AghaShayan123** [invertase/react-native-firebase#5855]
Hello there you awesome person;

Please note that the issue list of this repo is exclusively for bug reports;
## Issue

remoteConfig().getAll() return undefined is not an object (evaluating 'Object.keys(this._values)')

import remoteConfig from '@react-native-firebase/remote-config';

useEffect(() => {
getConfig()
.then(res => console.log(res)
.catch(err => console.log(err.message))
}, [])

const getConfig = async () => {
const firebase = await remoteConfig().getAll();
return firebase
}

**It return undefined is not an object (evaluating 'Object.keys(this._values)')**

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

"react": "17.0.2",
"react-native": "0.66.0",
"@react-native-firebase/analytics": "^13.0.1",
"@react-native-firebase/app": "^13.0.1",
"@react-native-firebase/auth": "^13.0.1",
"@react-native-firebase/firestore": "^13.0.1",
"@react-native-firebase/in-app-messaging": "^13.0.1",
"@react-native-firebase/messaging": "^13.0.1",
"@react-native-firebase/remote-config": "^13.0.1",

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Farsh' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'GoogleSignIn', '~> 6.0.2'

  target 'FarshTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
#5859 fixed this almost the same day
