### ISSUE TITLE
[🐛] Not able to manually crash the App. - Crashlytics

### ISSUE THREAD

**Issue by anujraghuvanshi** [invertase/react-native-firebase#5861]
## Issue

Platform - iOS.
I am using `"@react-native-firebase/crashlytics": "^13.0.1"`. When I create a release build I am able to crash the build using -
```js
crashlytics().crash()
```

but while I am doing development, I am not able to make any crashes. Nor any events are being logged into Firebase Crashalytics section.

---

## Project Files
`firebase.json`

```
{
    "react-native": {
      "crashlytics_disable_auto_disabler": false,
      "crashlytics_debug_enabled": true,
      "crashlytics_auto_collection_enabled": true
    }
}
```

### Javascript
```js
crashlytics().crash()
```

#### `package.json`:

```json
"@react-native-firebase/app": "^12.1.0",
"@react-native-firebase/auth": "^12.1.0",
"@react-native-firebase/crashlytics": "^13.0.1",
```

I tried keeping the version the same but the issue was there, So I updated  `crashlytics` to the latest to check if it's fixed.

#### `firebase.json` for react-native-firebase v6:

```json
{
    "react-native": {
      "crashlytics_disable_auto_disabler": false,
      "crashlytics_debug_enabled": true,
      "crashlytics_auto_collection_enabled": true
    }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

 OUTPUT GOES HERE

- **Platform that you're experiencing the issue on**:
  - [x] iOS
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 12.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  -  crashlytics
- **Are you using `TypeScript`?**
  - No

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
This is known working. It is tricky though. Please read this thoroughly https://invertase.io/blog/react-native-firebase-crashlytics-configuration
Please examine the log thoroughly while starting the app and trying to crash it
Hypothesis: you are running under a debugger (like, you started it from Xcode)

**Comment by anujraghuvanshi** [comment]
@mikehardy - When I check whether crashlytics is enabled or not, It comes true indicating enabled.
But when I try to crash, It shows me crashlytics is not enabled in console- 

```js
RCTLog.js:47 Crashlytics - INFO: crashlytics collection is not enabled, not crashing
```

Checking by - 
```js
crashlytics().isCrashlyticsCollectionEnabled
```

As I have updated the configuration/changes I made it to work. Can you please confirm me where I am doing wrong from above?  I hope I have done all the required changes to make it work in debug mode also.

**Comment by anujraghuvanshi** [comment]
One more question I want to ask along with is - If I am running my app with Xcode and not enabled debugging. Then it should work according to documentation. Just terminal is running with metro. then It should work, Right?

I have followed the same documentation which you have shared and I am running my app on the device.

**Comment by mikehardy** [comment]
Do not run it under xcode, try it from command line. Use console.app to watch log. I believe the blog I posted is clear on that 🤔

**Comment by mikehardy** [comment]
Also that log message is explicit. It's not enabled. Carefully examine firebase.json, then do a pod install to install the new json and rebuild
