### ISSUE TITLE
Updating Firebase ios/android SDK library

### ISSUE THREAD

**Issue by amitbravo** [invertase/react-native-firebase#587]
### Issue
I am updating react-native-firebase  from 3.0.5 to 3.0.6 but,
as there is new Firebase ios SDK 4.5.0 released at October 30, 2017 , How can I update it ? should I simply run "pod install" inside ios directory ? 

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode 9

4. React Native version: 0.49.3

5. RNFirebase Version: 3.0.5

6. Firebase Module: N/A

**Comment by chrisbianca** [comment]
@amitbravo To update pods you need to run:

`pod outdated` - this will refresh the pod cache, and check which of your pods our out of date

Then either:
`pod update` - this will update all out of date pods
`pod update {podName}` - this will update a specific pod
