### ISSUE TITLE
[🐛] Phone Auth TypeError: (0, _app.default) is not a function

### ISSUE THREAD

**Issue by rohit267** [invertase/react-native-firebase#5871]
import  auth from '@react-native-firebase/app';
try {
      const confirm = await auth().signInWithPhoneNumber(mobile);
      setAuthConfirm(confirm);
      setOtpBoxDisplay(true);
      setIsLoading(false);
      successToast.show(SuccessToast('OTP sent successfully'));
    }
    catch (error) {
      console.log(error);
      errorToast.show(ErrorToast("Oops, something went wrong."));
      setIsLoading(false);
    }

Minimal code here, console gave: 
[TypeError: (0, _app.default) is not a function. (In '(0, _app.default)()', '(0, _app.default)' is an instance of Object)]

**Comment by mikehardy** [comment]
You have ignored our template, we are unable to help without the information requested, sorry.
I suspect you have not correctly integrated things. I also don't understand how you can import auth from app ?
I think the example code will be helpful https://rnfirebase.io/auth/phone-auth#sign-in

**Comment by rohit267** [comment]
Sorry I was in hurry. Thanks for the help, I think there was /app not /auth, maybe I just missed it.

Anyway thanks again.

**Comment by narayanchoudhary** [comment]
was doing same mistake
