### ISSUE TITLE
Unable to generate FCM Token in iOS device.(The operation couldn’t be completed. Too many server requests.)

### ISSUE THREAD

**Issue by mmdHussain** [invertase/react-native-firebase#5873]
Firebase messaging NPM Module - "@react-native-firebase/messaging": "^13.0.1"
iOS Version - Not working on any iOS version
Xcode version - 13.1
Macos - Big Sur (11.6)
VS Code - 1.62.3

```
 async function requestUserPermission() {
    const authStatus = await messaging().requestPermission();
    const enabled =
      authStatus === messaging.AuthorizationStatus.AUTHORIZED ||
      authStatus === messaging.AuthorizationStatus.PROVISIONAL;

    if (enabled) {
      console.log('Authorization status:', authStatus);
      registerAppWithFCM();
    }
  }

  async function registerAppWithFCM() {
    const registerFCM = await messaging().registerDeviceForRemoteMessages();
    console.log('Register status:', registerFCM);
    if (registerFCM) {
      console.log('Register Fcm  status:', registerFCM);
      FcmToken();
    }
  }

  function FcmToken() {
    try {
        const token = await messaging().getToken();
        console.debug('fcm Token', token);
    } catch (error) {
      console.log('ERROR TOKEN ', error);
    }
    // alert(token);
  }
```

But I'm getting error - **The operation couldn’t be completed. Too many server requests.** also getting some additional error while compiling in xcode like.
1.APNS device token not set before retrieving FCM Token for Sender ID '168403391934'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.

If these cannot be fixed please suggest any alternate way to get FCM token.

**Comment by mikehardy** [comment]
There's a lot of duplicate traffic on this one
https://github.com/invertase/react-native-firebase/issues?q=Too+many+server+requests

Fundamentally it does not look like a problem with this module - I'm going to resolve it as duplicate
I recognize that does not directly provide help
If you read through some of those other issues (I just did), it looks like maybe uninstalling analytics, maybe trying TestFlight with a production cert, maybe being more careful with how you are invalidating tokens... but at heart it is either an upstream bug or a usage issue. Our APIs here are using the underlying APIs correctly and there's nothing we can do in this module to mitigate I think

**Comment by codoffer** [comment]
I have solved this issue by configuring Google CloudAPIs.
1. Login with Google Cloud
2. Choose Project
3. Choose APIs keys (Added by firebase) and configure
4. Add application restriction and set restrict key (Firebase Installation and other APIs, if you want - By Dropdown)

**Comment by jadsy2107** [comment]
> I have solved this issue by configuring Google CloudAPIs.
> 
>     1. Login with Google Cloud
> 
>     2. Choose Project
> 
>     3. Choose APIs keys (Added by firebase) and configure
> 
>     4. Add application restriction and set restrict key (Firebase Installation and other APIs, if you want - By Dropdown)

You are the man, Thank you - the API keys were restricted and removing the restriction solved this.

**Comment by saadkhalil01** [comment]
https://medium.com/@saadkhalil773/react-native-push-notification-0381af2252d2

**Comment by akansha1907** [comment]
> > I have solved this issue by configuring Google CloudAPIs.
> > ```
> > 1. Login with Google Cloud
> > 
> > 2. Choose Project
> > 
> > 3. Choose APIs keys (Added by firebase) and configure
> > 
> > 4. Add application restriction and set restrict key (Firebase Installation and other APIs, if you want - By Dropdown)
> > ```
> 
> You are the man, Thank you - the API keys were restricted and removing the restriction solved this.

I am facing the same issue, Can you explain this process, I am unable to understand points 3 and  4 
@codoffer

**Comment by jdarshan5** [comment]
+1
