### ISSUE TITLE
Cannot contact reCAPTCHA, Check your connection and try again

### ISSUE THREAD

**Issue by ControlAndC** [invertase/react-native-firebase#5882]
Hi,

I am using firebase version  "react-native-firebase": "5.6.0" with react native verson "react-native": "0.61.5" On our side build is working but iTunes is continuously rejecting the build saying  'Cannot contact reCAPTCHA, Check your connection and try again'.

Please see the attached screenshot and provide some solution.

Thanks

![image](https://user-images.githubusercontent.com/5564601/143529285-c3633326-6a98-4b30-96bb-570493123b84.png)

**Comment by mikehardy** [comment]
Sorry, these are versions that receive no support, as clearly mentioned in the documentation. please upgrade to current versions and see if it still reproduces.

If it does, please provide the requested issue template information so there is some ability to diagnose

**Comment by AmmarArnt** [comment]
Hi,

I am using the following versions in my project, and I am getting the exact same issue on the Apple review process. Cannot get the app approved due to this issue.

    "@react-native-firebase/app": "14.8.0",
    "@react-native-firebase/auth": "14.8.0",

**Comment by mikehardy** [comment]
Best guess here is intermittent network connection issue on the reviewers side. It was resolved by another affected party by essentially re-reviewing until they had a device that worked:

https://github.com/firebase/firebase-ios-sdk/issues?q=cannot+contact+recaptcha+check+your+connection+and+try+again

Unfortunately, this isn't actionable here as it doesn't reproduce for me and does not happen normally. But! Networks do have intermittent failures all the time, it appears that it is just really unfortunate this happened to the reviewer during the review process :weary:
