### ISSUE TITLE
🔥[🐛] Messaging: willPresentNotification delegate has no effect on iOS

### ISSUE THREAD

**Issue by cheungpat** [invertase/react-native-firebase#5884]
## Issue

On iOS, notification sent to foreground app is not shown to the user. However, this behavior can be changed by implementing `UNUserNotificationCenterDelegate`’s `-userNotificationCenter:willPresentNotification:withCompletionHandler:`. Calling the completion handler with `UNNotificationPresentationOptionBanner` will trigger the notification be shown, even when the app is in foreground.

This is how I implemented the delegate method in my app delegate:

```
// This line is added in `-application:didFinishLaunchingWithOptions:`:
// UNUserNotificationCenter.currentNotificationCenter.delegate = self;

- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler
{
  // Show a received notification when the app is in foreground.
  if (@available(iOS 14.0, *)) {
    completionHandler(UNNotificationPresentationOptionBanner | UNNotificationPresentationOptionList);
  } else {
    completionHandler(UNNotificationPresentationOptionAlert);
  }
}
```

Currently, implementing this delegate method has no effect

It appears that the `completionHandler` is already called in:

https://github.com/invertase/react-native-firebase/blob/514e6bd51e7624a6403dda706f4e5b65cee63422/packages/messaging/ios/RNFBMessaging/RNFBMessaging%2BUNUserNotificationCenter.m#L86

Therefore calling the same completion handler in `willPresentNotification` has no effect. If I remove this line, the notification is presented foreground with no problem.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 529.83 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - ~/.asdf/installs/nodejs/14.17.3/bin/node
    Yarn: 1.22.11 - ~/.asdf/installs/nodejs/14.17.3/.npm/bin/yarn
    npm: 6.14.13 - ~/.asdf/installs/nodejs/14.17.3/bin/npm
    Watchman: 2021.08.30.00 - /Users/user/.brew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/user/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.5 - /Users/user/.asdf/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e12.8.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y` & `4.4.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there!
You have not filled any of the issue template, so I'm unclear what versions or other packages you have in play, all of them could be old (with different behavior now, in current versions) and / or any of them could be swizzling in AppDelegate methods just as we do, interfering with the call chain.

You have not included any sort of code that would demonstrate what you were trying to do, if you could post a complete App.js that would demonstrate the problem you are having if dropped in a clean app, we could reason more about this

https://stackoverflow.com/help/minimal-reproducible-example
https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

Without more information I can just as easily say "this module is handling my use cases well and has no problems". That's apparently not correct in your case or you wouldn't have taken the time to post an issue but without more info - either of our statements are potentially true.
