### ISSUE TITLE
[🔥🐛] setPersistenceEnabled should return a promise, but it does not in IOS

### ISSUE THREAD

**Issue by stopachka** [invertase/react-native-firebase#5886]
## Issue

It's noted that [`database().setPersistenceEnabled`](https://github.com/invertase/react-native-firebase/blob/514e6bd51e7624a6403dda706f4e5b65cee63422/docs/database/offline-support.md?plain=1#L24) should return a Promise 

However, the [IOS bridge](https://github.com/invertase/react-native-firebase/blob/514e6bd51e7624a6403dda706f4e5b65cee63422/packages/database/ios/RNFBDatabase/RNFBDatabaseModule.m#L69) returns void.

Hence, the part in the doc that is written: 

```
database()
  .setPersistenceEnabled(true)
  .then(() => console.log('Realtime Database persistence enabled'));
```

will throw, saying that `then` is not defined

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 12.8.0
- **`Firebase` module(s) you're using that has the issue:**
  - database
- **Are you using `TypeScript`?**
  - N

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I think that's a documentation error vs implementation.
The implementation of setPersistenceEnabled, setPersistenceCacheSizeBytes, and setLoggingEnabled are all sync / no-return in both Android and iOS implementations, and the documentation should be changed to just have return of void and examples that don't do .then()

Could I implore you :pray: :pray:  to hit the edit button on that doc page and post up a PR that corrects the docs?
