### ISSUE TITLE
TOO_MANY_REGISTRATIONS error with firebase/messaging

### ISSUE THREAD

**Issue by samleurs247** [invertase/react-native-firebase#5889]
When trying to fetch the token (with ``messaging().getToken()``), I get the following error in the console for my physical device:
````
Error: [messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: TOO_MANY_REGISTRATIONS
NativeFirebaseError: [messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: TOO_MANY_REGISTRATIONS
````

I found [this SO question](https://stackoverflow.com/questions/47529977/firebase-token-error-too-many-registrations) but I does not provide me with an adequate solution. Does anyone know how to fix this? Should I delete some apps from my phone?

**Comment by mikehardy** [comment]
Hi there! Your post completely ignores our template, so I can  only provide limited guesses.
The SO question you link says to reset your phone, and there was a report of success for that. How did it work?

**Comment by samleurs247** [comment]
Hi @mikehardy, sorry for the inconvience, you're right, I'v should have asked this on SO.

Anyway, resetting my phone worked. So it's not an issue with this project.

Thanks!

**Comment by Yandamuri** [comment]
> Hi @mikehardy, sorry for the inconvience, you're right, I'v should have asked this on SO.
> 
> Anyway, resetting my phone worked. So it's not an issue with this project.
> 
> Thanks!

Resetting means, Did you do factory reset?

**Comment by mikehardy** [comment]
@Yandamuri the SO question is clear, with the answer from firebase support:

> If this is a real device, the best way to solve it is to factory reset to the real system image of the device.

**Comment by Yandamuri** [comment]
@mikehardy This is was reported by one of my customers. SO I cannot my customer to reset his device so easily without proper reason. At least may i know how resetting the device will resolve the issue?

**Comment by Yandamuri** [comment]
@mikehardy Thank you for your response. Anyway I will proceed for factory reset as it is the only option left.

**Comment by mikehardy** [comment]
For what it's worth, I recognize that's painful, and for a customer as well. I hope it resolves the issue.
