### ISSUE TITLE
Not receiving notifications sent from firebase console 

### ISSUE THREAD

**Issue by priyankinfinnov** [invertase/react-native-firebase#589]
### Issue
Not receiving notifications sent from firebase console using send to single device option

I used 
`Firebase.messaging().getToken().then((token) => {});`
to get the token.

And then 

`firebase.messaging().getInitialNotification((message) => {
      console.log("Got getInitialNotification "+JSON.stringify(message));
    });`
`firebase.messaging().onMessage((message) => {
      console.log("Got onMessage "+JSON.stringify(message));
    });`
to receive.

But log doesn't appear.

### Environment

1. Application Target Platform: Tried on Android (don't know about iOS)

2. Development Operating System: Windows 10

3. Build Tools: Android Studio 2.2

4. React Native version: 0.49.x

5. RNFirebase Version: "^3.0.3"

6. Firebase Module: Messaging

**Comment by chrisbianca** [comment]
We're aware of lots of issues with notifications and will be addressing them all as part of the v3.2.0 release stream.  Please see https://github.com/invertase/react-native-firebase/issues/595 for updates.

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)
