### ISSUE TITLE
App crashing when enabling Hermes and using react-native-firebase

### ISSUE THREAD

**Issue by Dassine** [invertase/react-native-firebase#5890]
Hi guys!

Last week, I had to enable the hermes-engine in my podfile since the TF build was crashing at launch. Once done, the build worked fine. This week, Im trying to react-native-firebase/app and /messaging to add Push Notification and the app is again crashing at launch. I read somewhere that react-native-firebase is not compatible with hermes but React-Native mentioned that they added Proxy support to hermes jn RN 0.64

Im using RN 0.66 since last week and the added react-native-firebase packages are 13.0.1. I believe since 2020 both were upgraded to support PN, isn’t it?

**Comment by mikehardy** [comment]
Hi there! This report doesn't have a reproduction, but I do :-), and it works.

https://github.com/mikehardy/rnfbdemo/blob/44a612684a5d9b7b96af430a68c239c11f580af5/make-demo.sh#L133-L137

Also I use it in my work projects. It's fine using up to date versions, and attempting to troubleshoot non-up-to-date versions is inefficient, so I'll just say "it works"

If you can tweak the demo somehow to reproducibly crash and produce a trace, we can try to fix it but the only incompatibility was "Proxy" support, needed for the database package here. Everything else is and was fine

**Comment by Dassine** [comment]
@mikehardy  Thank you for your feedback.  I end up finding a small issue in the setup of react-native-firebase.
