### ISSUE TITLE
Analytics setUserProperties, logEvent key/value setting guideline / validation issue

### ISSUE THREAD

**Issue by Hemistone** [invertase/react-native-firebase#5894]
During using the analytics library, we got stuck on setting _user behavior data pipeline_ since several events were not triggering and user properties are not setting well.

After some research(checking device logs, [reading official firebase docs](https://firebase.google.com/docs/analytics/user-properties?platform=ios#set_user_properties_2), ...etc), I found that firebase's user property does not support `key` names of upper 24 letters and `value` string length over 100 letters. Also, some of long params in `analtyics().logEvent()` are also failed to be called. Those error logs are visible in adb device log, but it does not show any try/catch errors by js scripts.

In order not to let others do the same thing as me, I suggest to add additional guidelines to _Restrictions on naming key, and inserting string values_ in events and user properties.

Additional guideline on setting key/value pairs for analtyics' `setUserProperties` and `logEvent` is needed as example as below.

> - User Properties' key should be under 24 letters
> - User Properties' value should be under 100 letters
> - `logEvent` param's inner string values should be under 100 letters

```javascript
analytics().setUserProperty('color_preference', 'blue') 
// OK

analytics().setUserProperty('color_preference_a_long_key_name_haha','red') 
// FAIL - user property does not set since the key string overed 24 letters

analytics().logEvent('good',{color: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'}) 
// FAIL - params on event overed 100 letters
```
The official firebase documents managed by Google also did not specify exactly how many letters are allowed, which was questionable.
I'm pretty curious about has anyone had same experience like me. 

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Hemistone** [comment]
I think this also can be _Bug Report Issue_, since the `analytics().setUserProperties()` and `analytics().logEvent()` function did not bring error correctly, as device log showed. There are no errors captured even `logEvent()` and `setUserProperty()` did not run successfully since of loooong key/values for now.

**Comment by mikehardy** [comment]
The index.js file in packages/analytics could be modified to test and throw, I thought it already did 🤔, would be a great PR as would an addition to the docs. Post a PR and we can merge, it'll help a lot of people I'm sure

**Comment by mikehardy** [comment]
Yep - testing event name but not value:
https://github.com/invertase/react-native-firebase/blob/bb1bf4c8563cf48b5280138a59e12ec0cb24cd47/packages/analytics/__tests__/analytics.test.ts#L127-L131

testing setUserProperties but not probing boundaries:
https://github.com/invertase/react-native-firebase/blob/bb1bf4c8563cf48b5280138a59e12ec0cb24cd47/packages/analytics/__tests__/analytics.test.ts#L61

Area of documentation to edit if you hit the edit button:
https://github.com/invertase/react-native-firebase/blob/bb1bf4c8563cf48b5280138a59e12ec0cb24cd47/packages/analytics/lib/index.d.ts#L730-L742

...and
https://github.com/invertase/react-native-firebase/blob/bb1bf4c8563cf48b5280138a59e12ec0cb24cd47/packages/analytics/lib/index.d.ts#L666-L669

...extract validation here and here:
https://github.com/invertase/react-native-firebase/blob/bb1bf4c8563cf48b5280138a59e12ec0cb24cd47/packages/analytics/lib/index.js#L150-L153
https://github.com/invertase/react-native-firebase/blob/bb1bf4c8563cf48b5280138a59e12ec0cb24cd47/packages/analytics/lib/index.js#L169-L173

...and add stricter check for user properties

Add check similar to name format validation to validate param as well on logEvent here
https://github.com/invertase/react-native-firebase/blob/bb1bf4c8563cf48b5280138a59e12ec0cb24cd47/packages/analytics/lib/index.js#L97-L102
