### ISSUE TITLE
Add examples to upload and download to firebase storage in documentation

### ISSUE THREAD

**Issue by varungupta85** [invertase/react-native-firebase#590]
### Issue

Currently, there are no examples of how to upload and download a file to firebase storage in the documentation. There API reference for storage API is also empty due to which I am not able to use the storage API. Some examples and documentation around the storage API will really help.

**Comment by priyankinfinnov** [comment]
+1 Will require this soon. 

Although @varungupta85 i think you can try https://firebase.google.com/docs/storage/web/upload-files and https://firebase.google.com/docs/storage/web/download-files 

Since most of the code in react-native-firebase is kept similar to the web SDK of firebase as mentioned at [https://rnfirebase.io/](url) "Our implementation replicates the official Web SDK where possible and supports both Android and iOS."

**Comment by Salakar** [comment]
Hi both, looks like we've not moved this over yet from the old docs, you can find them here: https://github.com/invertase/react-native-firebase/blob/docs_old/docs/modules/storage.md

We'll get them moved over also and refreshed.

**Comment by malikhzr** [comment]
Hi @Salakar. Is it possible to upload media files(image,video,audio) to firebase storage in offline mode and sync them to redux store once Internet Connection is back with React Native ?

**Comment by xaphod** [comment]
@Salakar Please reopen this issue:
- the link you posted is 404 / invalid
- the existing 5.x.x documentation still has zero examples
- the existing alpha 6.x.x documentation has zero examples, no guide
I am stuck and will have to start grokking random projects online that use this module somehow, frustrating

**Comment by Salakar** [comment]
> the existing 5.x.x documentation still has zero examples - @xaphod 

- https://rnfirebase.io/docs/v5.x.x/storage/reference/Reference#putFile x2 examples
- https://rnfirebase.io/docs/v5.x.x/storage/reference/Reference#downloadFile x2 examples

> the existing alpha 6.x.x documentation has zero examples - @xaphod 

- https://invertase.io/oss/react-native-firebase/v6/storage/reference/reference#putFile
- https://invertase.io/oss/react-native-firebase/v6/storage/reference/reference#getFile
- https://invertase.io/oss/react-native-firebase/v6/storage/reference/task#on
