### ISSUE TITLE
Google sign in replaces other auth providers when linked

### ISSUE THREAD

**Issue by mikehardy** [invertase/react-native-firebase#5900]
### Discussed in https://github.com/invertase/react-native-firebase/discussions/5897

<div type='discussions-op-text'>

<sup>Originally posted by **MarioUnlam** December  1, 2021</sup>
I'm working on an app that allows the user to sign in with Google, Facebook and Twitter. I noticed that if the user signs in with one auth provider, and then tries to use another, signInWithCredential() will return an 'account-exists-with-different-credential' exception. I already managed to handle this exception for the three auth providers, so the user has to authenticate using the previous provider to link the new one.

However, this only happens if the new auth provider is NOT google. If the user authenticates with Facebook or Twitter first, and then uses Google, it won't throw an exception, and instead it unlinks the previous providers, leaving that account with Google as the only provider. Is this a bug? because it looks quite inconsistent, the other providers work differently. Is there any way to disable this behavior?</div>

**Comment by mikehardy** [comment]
reproducible with react-native-firebase-authentication-example

**Comment by mikehardy** [comment]
From the other issue:

> In the meantime, a possible workaround would be to run fetchSignInMethodsForEmail(...) every time a user tries to sign in with Google, and if it returns more than one provider, run the same logic used to handle "account-exists-with-different-credential" exceptions. I'm pretty sure this is a very unlikely scenario (a user signing in to the same app, using the same email, but a different provider, and in this specific order).

**Comment by duke-darius** [comment]
This is still an issue, do we not have any way to link accounts together?

**Comment by bobbytestrowy2** [comment]
This is still an issue.

**Comment by bofeiw** [comment]
This is still an issue.

**Comment by marcoturi** [comment]
@mikehardy can you re-open this issue? Or maybe it's better to open a new one, as this is quite old?

**Comment by antoine-waag** [comment]
I've got the same problem, I do not have a solution to link multiple accounts with Google and an Email/Password sign in. 

If I create an account with an email/password first and then sign in with Google, it will remove the email/password provider.

**Comment by MrSharpp** [comment]
same issue, it keeps replacing my account which is signed up using email/password
