### ISSUE TITLE
[🐛] Firebase android not installing correctly

### ISSUE THREAD

**Issue by ViggoGaming** [invertase/react-native-firebase#5903]
Hey everyone.
I am trying to use the react-native-firebase module, but I keep getting the same error:
```
Android Bundling complete 14791ms
Android Running app on Android SDK built for x86

Error: You attempted to use a firebase module that's not installed on your Android project by calling firebase.app().

Ensure you have:

1) imported the 'io.invertase.firebase.app.ReactNativeFirebaseAppPackage' module in your 'MainApplication.java' file.

2) Added the 'new ReactNativeFirebaseAppPackage()' line inside of the RN 'getPackages()' method list.

See http://invertase.link/android for full setup instructions.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-dev-launcher/build/DevLauncherErrorManager.js:44:19 in errorHandler
at node_modules/expo-dev-launcher/build/DevLauncherErrorManager.js:49:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://192.168.1.69:19000/index.bundle?platform=android&dev=true&hot=false&minify=false:122558:3 in global code

```

I have tried for multiple hours now to install it in different ways, such as using expo modules, following the official installation guide, manual linking. I have installed the npm modules react-native-firebase/app and /database, and I have tried the fixes it tells in the error message, with no luck.
I have read online that other people have encountered the same error, and it does not look like there is a fix for it:
https://stackoverflow.com/questions/70154548/react-native-expo-you-attempted-to-use-a-firebase-module-thats-not-installed-o
https://stackoverflow.com/questions/69810211/you-attempted-to-use-firebase-module-thats-not-installed-on-your-android
https://stackoverflow.com/questions/69752638/while-react-native-app-implement-in-webpack-error-in-firebase

As you can see it seems to be a wide problem.
My npm version is 8.1.3
Here is my package.json:
```
{
  "scripts": {
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "start": "expo start --dev-client"
  },
  "dependencies": {
    "@react-native-firebase/app": "^13.1.0",
    "@react-native-firebase/database": "^13.1.0",
    "expo": "^43.0.0",
    "expo-dev-client": "~0.6.3",
    "expo-splash-screen": "~0.13.4",
    "expo-status-bar": "~1.1.0",
    "expo-updates": "~0.10.13",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true,
  "version": "1.0.0",
  "name": "with-dev-client"
}

```

Many thanks in advance for the help! I really hope it gets solved, because I want to use this great module.

**Comment by mikehardy** [comment]
Hi there! This isn't going to cause any change in the module, it's an install problem, so I'm going to close this.
However, you can read and follow along with this script and it'll get a working project going from scratch:
https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

Or this one 
https://github.com/invertase/react-native-firebase-authentication-example

Both should be enough to compare with your project to hopefully find out where the install went wrong - I do hope they help

**Comment by ShunsukeAraki-IPG** [comment]
@mikehardy 
Sorry but I installed follow with the instruction but when I run dynamic links on android I have faced same issue. Can you help me?

**Comment by ducbinh1995** [comment]
@mikehardy 
Sorry but I installed follow with the instruction but when I run dynamic links on android I have faced same issue. Can you help me?

**Comment by mikehardy** [comment]
No, my comment above is the complete answer including a reproducible demonstration.
