### ISSUE TITLE
[🐛] Bug Report Title - Analytics v13.1.0 throw error when use logScreenView

### ISSUE THREAD

**Issue by j2teamlbh** [invertase/react-native-firebase#5905]
## Issue

When i move between screens and logScreenView, my app throw "Cannot convert undefined value to object". I saw this error and try update **struct.interface** to **struct** like v12.x.x and it work normally. I think you need check this again. Thanks

---
![Screen Shot 2021-12-03 at 11 07 39](https://user-images.githubusercontent.com/45052513/144543674-146b3d07-eca2-43dd-b54d-375123f95459.png)
![Screen Shot 2021-12-03 at 11 09 54](https://user-images.githubusercontent.com/45052513/144543855-9e079bcc-41c1-423c-907f-a4e1acdde043.png)
![Screen Shot 2021-12-03 at 11 08 12](https://user-images.githubusercontent.com/45052513/144543724-e1e3b210-e21c-46ee-9aa2-4e2408e99435.png)
![Screen Shot 2021-12-03 at 11 12 19](https://user-images.githubusercontent.com/45052513/144544067-41896391-9cf0-4f79-ae3b-becd8a4dd221.png)

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I can't really understand what's going on between the missing issue template and mash of images (I review issues on mobile a lot, like now). It sounds like you have something figured out though, could you propose a PR with the fix? If it looks good we can integrate it and release

**Comment by j2teamlbh** [comment]
> I can't really understand what's going on between the missing issue template and mash of images (I review issues on mobile a lot, like now). It sounds like you have something figured out though, could you propose a PR with the fix? If it looks good we can integrate it and release

I'm busy right now so I'll try again later and find out a solution for this issue
https://github.com/invertase/react-native-firebase/pull/5811/files#diff-7e5696b3f3b07b650301888d0e2095a3e2e80a6109b3c759ee970675198063e7
