### ISSUE TITLE
Maximum call stack size error when trying to use firestore with auth call

### ISSUE THREAD

**Issue by DavidKarasek** [invertase/react-native-firebase#591]
### Issue

I am trying to save user data into a user collection after a successful auth login. However, when I try to nest the two calls, I get a maximum call stack size error. If I do the calls independently, they work.

   ```
 try {
      var u = await firebase.auth().signInWithEmailAndPassword(login,password)
      this.loggingIn = false
      console.log("User: ", u)
    } catch (e) {
      this.loggingIn = false
      console.log(e)
      setTimeout(()=>Alert.alert('BS Error',e.message),10)
      return e;
    }

    try {
      var dbU = await firebase.firestore().collection('users').doc(u.uid).set({
        user: u,
        test: true
      }, {merge: true})
    } catch (e) {
      console.log("Saving error: ", e)
    }
```
I have tried chaining them as promises and also the async await method above. It catches on the second try block with the error. For some reason, having the firestore call in the callback of the first promise is causing the problem. 

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS Sierra 10.12.6

3. Build Tools: Xcode Version 9.0 (9A235), iOS Simulator 8.0

4. React Native version: 0.47.2

5. RNFirebase Version: 3.0.5 & 3.1.0

6. Firebase Module: auth, firestore

**Comment by chrisbianca** [comment]
@DavidKarasek the issue is that you're trying to serialize the `User` class which includes methods and other nested structures.

Try with the `User` objects `toJSON()` method:

```
var dbU = await firebase.firestore().collection('users').doc(u.uid).set({
     user: u.toJSON(),
     test: true
   }, {merge: true})
```

**Comment by DavidKarasek** [comment]
Ah, of course. That was it. Thanks!
