### ISSUE TITLE
Can't create .apk

### ISSUE THREAD

**Issue by mdehghani65** [invertase/react-native-firebase#5913]
## Issue

I'm trying to export an .apk release for my RN project using cd android && ./gradlew assembleRelease.
although I **can** successfully **"npx react-native run-android"** in debug mode , create .abb bundles and also **"run-android --variant=release"**, but assembleRelease command fails with the following logs in my console : 
 
> Configure project :@react-native-firebase_messaging
:@react-native-firebase_messaging package.json found at /Users/mdbaniani/Documents/viitabs/node_modules/@react-native-firebase/messaging/package.json
:react-native-firebase_app package.json found at /Users/mdbaniani/Documents/viitabs/node_modules/@react-native-firebase/app/package.json
:@react-native-firebase_messaging:firebase.bom using default value: 29.0.1
:@react-native-firebase_messaging package.json found at /Users/mdbaniani/Documents/viitabs/node_modules/@react-native-firebase/messaging/package.json
:@react-native-firebase_messaging:version set from package.json: 13.1.0 (13,1,0 - 13001000)
:@react-native-firebase_messaging:android.compileSdk using custom value: 30
:@react-native-firebase_messaging:android.targetSdk using custom value: 30
:@react-native-firebase_messaging:android.minSdk using custom value: 21
:@react-native-firebase_messaging:reactNativeAndroidDir /Users/mdbaniani/Documents/viitabs/node_modules/react-native/android

> Configure project :react-native-firebase_analytics
:react-native-firebase_analytics package.json found at /Users/mdbaniani/Documents/viitabs/node_modules/@react-native-firebase/analytics/package.json
:react-native-firebase_app package.json found at /Users/mdbaniani/Documents/viitabs/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_analytics:firebase.bom using default value: 29.0.1
:react-native-firebase_analytics package.json found at /Users/mdbaniani/Documents/viitabs/node_modules/@react-native-firebase/analytics/package.json
:react-native-firebase_analytics:version set from package.json: 13.1.0 (13,1,0 - 13001000)
:react-native-firebase_analytics:android.compileSdk using custom value: 30
:react-native-firebase_analytics:android.targetSdk using custom value: 30
:react-native-firebase_analytics:android.minSdk using custom value: 21
:react-native-firebase_analytics:reactNativeAndroidDir /Users/mdbaniani/Documents/viitabs/node_modules/react-native/android

> Configure project :react-native-firebase_app
:react-native-firebase_app package.json found at /Users/mdbaniani/Documents/viitabs/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:firebase.bom using default value: 29.0.1
:react-native-firebase_app:play.play-services-auth using default value: 19.2.0
:react-native-firebase_app package.json found at /Users/mdbaniani/Documents/viitabs/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:version set from package.json: 13.1.0 (13,1,0 - 13001000)
:react-native-firebase_app:android.compileSdk using custom value: 30
:react-native-firebase_app:android.targetSdk using custom value: 30
:react-native-firebase_app:android.minSdk using custom value: 21
:react-native-firebase_app:reactNativeAndroidDir /Users/mdbaniani/Documents/viitabs/node_modules/react-native/android

> Configure project :react-native-firebase_crashlytics
:react-native-firebase_crashlytics package.json found at /Users/mdbaniani/Documents/viitabs/node_modules/@react-native-firebase/crashlytics/package.json
:react-native-firebase_app package.json found at /Users/mdbaniani/Documents/viitabs/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_crashlytics:firebase.bom using default value: 29.0.1
:react-native-firebase_crashlytics package.json found at /Users/mdbaniani/Documents/viitabs/node_modules/@react-native-firebase/crashlytics/package.json
:react-native-firebase_crashlytics:version set from package.json: 13.1.0 (13,1,0 - 13001000)
:react-native-firebase_crashlytics:android.compileSdk using custom value: 30
:react-native-firebase_crashlytics:android.targetSdk using custom value: 30
:react-native-firebase_crashlytics:android.minSdk using custom value: 21
:react-native-firebase_crashlytics:reactNativeAndroidDir /Users/mdbaniani/Documents/viitabs/node_modules/react-native/android

> Configure project :react-native-firebase_messaging
:react-native-firebase_messaging package.json found at /Users/mdbaniani/Documents/viitabs/node_modules/@react-native-firebase/messaging/package.json
:react-native-firebase_app package.json found at /Users/mdbaniani/Documents/viitabs/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_messaging:firebase.bom using default value: 29.0.1
:react-native-firebase_messaging package.json found at /Users/mdbaniani/Documents/viitabs/node_modules/@react-native-firebase/messaging/package.json
:react-native-firebase_messaging:version set from package.json: 13.1.0 (13,1,0 - 13001000)
:react-native-firebase_messaging:android.compileSdk using custom value: 30
:react-native-firebase_messaging:android.targetSdk using custom value: 30
:react-native-firebase_messaging:android.minSdk using custom value: 21
:react-native-firebase_messaging:reactNativeAndroidDir /Users/mdbaniani/Documents/viitabs/node_modules/react-native/android
WARNING:: The specified Android SDK Build Tools version (29.0.2) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.2.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '29.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :react-native-firebase_app:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :@react-native-firebase_messaging:compileReleaseJavaWithJavac
Note: /Users/mdbaniani/Documents/viitabs/node_modules/@react-native-firebase/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :@react-native-firebase_messaging:extractReleaseAnnotations FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@react-native-firebase_messaging:extractReleaseAnnotations'.
> Could not resolve all files for configuration ':@react-native-firebase_messaging:lintClassPath'.
   > Could not find lint-gradle-27.2.2.jar (com.android.tools.lint:lint-gradle:27.2.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.2.2/lint-gradle-27.2.2.jar
   > Could not find lint-27.2.2.jar (com.android.tools.lint:lint:27.2.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint/27.2.2/lint-27.2.2.jar
   > Could not find lint-checks-27.2.2.jar (com.android.tools.lint:lint-checks:27.2.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-checks/27.2.2/lint-checks-27.2.2.jar
   > Could not find lint-api-27.2.2.jar (com.android.tools.lint:lint-api:27.2.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-api/27.2.2/lint-api-27.2.2.jar
   > Could not find intellij-core-27.2.2.jar (com.android.tools.external.com-intellij:intellij-core:27.2.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/27.2.2/intellij-core-27.2.2.jar
   > Could not find kotlin-compiler-27.2.2.jar (com.android.tools.external.com-intellij:kotlin-compiler:27.2.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/kotlin-compiler/27.2.2/kotlin-compiler-27.2.2.jar
   > Could not find uast-27.2.2.jar (com.android.tools.external.org-jetbrains:uast:27.2.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/external/org-jetbrains/uast/27.2.2/uast-27.2.2.jar
   > Could not find aapt2-proto-4.1.0-alpha01-6193524.jar (com.android.tools.build:aapt2-proto:4.1.0-alpha01-6193524).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2-proto/4.1.0-alpha01-6193524/aapt2-proto-4.1.0-alpha01-6193524.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 28s
37 actionable tasks: 34 executed, 3 up-to-date

Describe your issue here

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

{
  "name": "viitabs",
  "version": "1.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.36",
    "@fortawesome/free-brands-svg-icons": "^5.15.4",
    "@fortawesome/free-regular-svg-icons": "^5.15.4",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@fortawesome/react-native-fontawesome": "^0.2.7",
    "@react-native-async-storage/async-storage": "^1.15.9",
    "@react-native-community/slider": "^4.1.8",
    "@react-native-firebase/analytics": "^13.1.0",
    "@react-native-firebase/app": "^13.1.0",
    "@react-native-firebase/crashlytics": "^13.1.0",
    "@react-native-firebase/messaging": "^13.1.0",
    "@react-navigation/bottom-tabs": "^6.0.7",
    "@react-navigation/native": "^6.0.4",
    "@react-navigation/native-stack": "^6.2.2",
    "axios": "^0.22.0",
    "fast-xml-parser": "^3.20.3",
    "react": "17.0.2",
    "react-native": "0.66.0",
    "react-native-document-picker": "^7.1.0",
    "react-native-fs": "^2.18.0",
    "react-native-input-spinner": "^1.7.11",
    "react-native-mime-types": "^2.3.0",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.8.0",
    "react-native-sound": "^0.11.1",
    "react-native-svg": "^12.1.1",
    "react-native-zip-archive": "^6.0.3",
    "sp-react-native-in-app-updates": "^1.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.15.8",
    "@babel/runtime": "^7.15.4",
    "@react-native-community/eslint-config": "^3.0.1",
    "babel-jest": "^27.2.5",
    "eslint": "^7.32.0",
    "jest": "^27.2.5",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
#### `firebase.json` for react-native-firebase v6:

N/A

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application? I didn't change anything regarding this
- [X ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
    Memory: 631.77 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 10.0/10A255 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.0 => 0.66.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [X ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
This is a network problem in local network somewhere, either blocking in the browser or a DNS failure or something, but, the error clearly states the failure was because:


> Could not resolve all files for configuration ':@react-native-firebase_messaging:lintClassPath'.
> Could not find lint-gradle-27.2.2.jar (com.android.tools.lint:lint-gradle:27.2.2).
> Searched in the following locations:
> https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.2.2/lint-gradle-27.2.2.jar
> Could not find lint-27.2.2.jar (com.android.tools.lint:lint:27.2.2).

I try that URL and download the jar. So it works on my network and thus gradle will resolve it and it will work.

If you can restore access to the network resources gradle needs, it will work for you

**Comment by mdehghani65** [comment]
> This is a network problem in local network somewhere, either blocking in the browser or a DNS failure or something, but, the error clearly states the failure was because:
> 
> > Could not resolve all files for configuration ':@react-native-firebase_messaging:lintClassPath'.
> > Could not find lint-gradle-27.2.2.jar (com.android.tools.lint:lint-gradle:27.2.2).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.2.2/lint-gradle-27.2.2.jar
> > Could not find lint-27.2.2.jar (com.android.tools.lint:lint:27.2.2).
> 
> I try that URL and download the jar. So it works on my network and thus gradle will resolve it and it will work.
> 
> If you can restore access to the network resources gradle needs, it will work for you

You're right. It's something related to network. I successfully built the apk using codemagic.io. otherwise I couldn't have.
