### ISSUE TITLE
🔥[🐛] Bug Report Title - CHANGE ME 

### ISSUE THREAD

**Issue by TaylorDale** [invertase/react-native-firebase#5918]
## Issue
Can't compile for Android:

node_modules\@react-native-firebase\analytics\android\src\main\java\io\invertase\firebase\analytics\UniversalFirebaseAnalyticsModule.java:71: error: cannot find symbol
      FirebaseAnalytics.getInstance(getContext()).setMinimumSessionDuration(milliseconds);
                                                 ^
  symbol:   method setMinimumSessionDuration(long)
  location: class FirebaseAnalytics

I don't use this function in my app so I've just commented it out for now, but intellisense in Android studio doesn't seem to show any logical replacement for this function call.

---

#### `package.json`:

```json

    "@react-native-firebase/app": "^13.1.0",
    "@react-native-firebase/auth": "^13.1.0",
    "@react-native-firebase/firestore": "^13.1.0",
    "@react-native-firebase/functions": "^13.1.0",
    "@react-native-firebase/remote-config": "^13.1.0",
```
</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [x ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```
        classpath("com.android.tools.build:gradle:4.2.2")
        classpath 'com.google.gms:google-services:4.3.10'
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - v6

</p>
</details>

---

**Comment by mikehardy** [comment]
Re-scanned this. Relevant breaking change note: https://github.com/invertase/react-native-firebase/blob/main/packages/analytics/CHANGELOG.md#800-2020-11-10

Definitely out of date local SDKs. `npx react-native-clean-project` and verify you have current firebase-android-sdk or rely on `react-native-firebase/app` to bring it in for you (in an up to date version)

**Comment by TaylorDale** [comment]
Thanks mate - appreciate you investigating it. I did have a feeling my
dependencies might be some weird cached version, I'll try that out
tomorrow. Thanks as always.

**Comment by TaylorDale** [comment]
I just hadn't updated the analytics package, it was still on 6. I must have only looked at the entries that I copied out of the package.json here, it was directly above it. D'oh!.

Thanks.
