### ISSUE TITLE
Firebase Performance error log on IOS

### ISSUE THREAD

**Issue by peterdivvito** [invertase/react-native-firebase#593]
### Issue
When using firebase-perf  to create/start/stop a trace the error log entry keeps being output on IOS.

`Failed to start trace checkTone because it has already been started and stopped`

I tracked the problem down to RNFirebasePerformance.m

```Objectivec
- (FIRTrace *)getOrCreateTrace:(NSString *)identifier {
    if (_traces[identifier]) {
        return _traces[identifier];
    }
    FIRTrace *trace = [FIRPerformance startTraceWithName:identifier];
    _traces[identifier] = trace;
    return trace;
}
```

which is calling **startTraceWithName** instead of just **traceWithName**

### Environment

1. Application Target Platform: IOS

2. Development Operating System: macOS Sierra

3. Build Tools: XCode 9.1

4. React Native version: 0.50.1

5. RNFirebase Version: 3.1.0

6. Firebase Module: FirebasePerformance (1.0.6)

**Comment by Salakar** [comment]
@peterdivvito thanks for flagging, have just pushed up a fix for this, will get this in the next patch release - most likely later today.
