### ISSUE TITLE
[🐛] "name" can not be Korean on "logEvent"

### ISSUE THREAD

**Issue by keiches** [invertase/react-native-firebase#5953]
## Issue

I want to use like below,

### JavaScript
```javscript
firebase.analytics().logEvent('비티에스_is_BTS', params);
```

But, it throws,

```javascript
firebase.analytics().logEvent(*) 'name' the event name '비티에스_is_BTS' is reserved and can not be used.
```

I think, "isAlphaNumericUnderscore" does not allow Korean.

#### [packages/analytics/lib/index.js](https://github.com/invertase/react-native-firebase/blob/8efda506474b1757f6a0537495a1de581d372299/packages/analytics/lib/index.js)

```js
 97    // name format validation
 98    if (!isAlphaNumericUnderscore(name) || name.length > 40) {
 99      throw new Error(
100        `firebase.analytics().logEvent(*) 'name' invalid event name '${name}'. Names should contain 1 to 40 alphanumeric characters or underscores.`,
101      );
102    }
```

I know it means only Alphbet, Numeric and Underscore.
but, Firebase console can Korean as the event name.
Is there any solution for this. or have any plan?

If not, I have to change that line to below,

```js
 97    // name format validation
 98    if (/* !isAlphaNumericUnderscore(name) || */ name.length > 40) {
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/analytics": "^12.1.0",
    "@react-native-firebase/app": "^12.1.0",
    "@react-native-firebase/crashlytics": "^12.1.0",
    "@react-native-firebase/messaging": "^12.1.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
  "react-native": {
    "analytics_auto_collection_enabled": false,
    "android_task_executor_maximum_pool_size": 10,
    "android_task_executor_keep_alive_seconds": 3,
    "crashlytics_auto_collection_enabled": false,
    "crashlytics_debug_enabled": false,
    "crashlytics_ndk_enabled": true,
    "crashlytics_is_error_generation_on_js_crash_enabled": false,
    "crashlytics_javascript_exception_handler_chaining_enabled": true
  }
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 9.40 GB / 31.73 GB
  Binaries:
    Node: 14.15.4 - C:\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Yarn\bin\yarn.CMD
    npm: 6.14.10 - C:\nodejs\npm.CMD
    Watchman: 20200802.200524.0 - C:\opt\bin\watchman.EXE      
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3      
      System Images: android-22 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Disabled
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.64.2 => 0.64.2
    react-native-windows: ^0.64.11 => 0.64.18
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `12.9.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
🤔 Hmmm - I think this would necessarily expand the idea of alphanumeric to UTF-8 (or UTF-16?) - are you aware of the real "alphanumeric" constraint that firebase puts on / what character sets they allow?

Once we know that as a fundamental fact, then we may cross-reference it with what the javascript engines react-native runs on supports. I'm afraid Hermes doesn't have full intl support and in fact the JSC has intl support as optional, so we may be limited in our options here, I'm unsure
