### ISSUE TITLE
App crashing on using 

### ISSUE THREAD

**Issue by puneetkansal04** [invertase/react-native-firebase#5956]
App is hang in the ios and android working fine. This is happening in debug mode IOS only. Production works fine.

I am using this module "@react-native-firebase/perf": "^14.1.0", app is going to hang and crash after 2-3 seconds and give me this error

Thread 1: "-[fir_BEE71E0E-B676-4996-A97B-D120B6GF165B_GULNetworkURLSession _flex_swizzle_a0c22ca7_URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:]: unrecognized selector sent to instance 0x600001d98000"

and crashing my app. In the xcode automatically open this file name main as below. Tried with multiple version but not resolved.

#import <UIKit/UIKit.h>

#import "AppDelegate.h"

int main(int argc, char * argv[]) {
  @autoreleasepool {
    return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
  }
}

**Comment by mikehardy** [comment]
Please open a new issue providing the info in the template, thanks
