### ISSUE TITLE
onSnapshot hangs indefinitely

### ISSUE THREAD

**Issue by connercms** [invertase/react-native-firebase#596]
### Issue
When setting up subscription to firestore collection update, sometimes it causes my application to just hang indefinitely.

I have a 'controller' component in which I set up a listener to receive collection updates from the firestore. When the user starts the application, this controller sets up the listener and takes the initial snapshot and loads it into the redux store. The application then uses the redux store to pull data from. The controller sits in the background listening for updates while the application is open and updates the redux store if any changes come through. This way, I only have to set up a listener to collection updates in the controller, and can use the data in the redux store throughout my application. During the time when the user starts the application and the controller is setting up the listener and gathering the initial snapshot data, I am displaying a splash screen (I have noticed that the application lags and is generally unusable during this time, so I did this as a workaround). It is working well, but sometimes the application gets 'stuck' on setting up the listener, or onCollectionUpdate never gets called initially, which I thought it always did when initially called. I believe this is the case anyway because my splash screen never goes away, which indicates my loading variable in my state (shown below) never gets set to false

```
class DispatchController extends Component {
  constructor(props) {
    super(props)
    this.unsubscribe = null
    this.ref = firebase.firestore().collection('dispatches')

    this.state = {
      loading: true
    }
  }

  componentDidMount() {
    this.unsubscribe = this.ref.onSnapshot(this.onCollectionUpdate)
  }

  componentWillUnmount() {
    this.unsubscribe()
  }

  onCollectionUpdate = querySnapshot => {
    const dispatches = []
    querySnapshot.forEach(document => {
      dispatches.push(document.data())
    })
    this.props.handleDispatchUpdate(dispatches)
    this.setState({ loading: false })
  }

  render() {
    if (this.state.loading) {
      return (
        <View style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, justifyContent: 'center' }}>
          <SplashScreen />
        </View>
      )
    }
    return null
  }
}

DispatchController.propTypes = {
  handleDispatchUpdate: PropTypes.func.isRequired
}

export default connect(null, dispatchActions)(DispatchController) 
```

### Environment

1. Application Target Platform:  Android

2. Development Operating System: MacOS Sierra

3. Build Tools: 23.0.1

4. React Native version: ^0.49.3

5. RNFirebase Version: ^3.1.0

6. Firebase Module: Firestore

**Comment by Ehesp** [comment]
Hey, the only really thing we're able to suggest is getting up logcat and checking the logs when it hangs - there maybe something being thrown which isn't being handled?

**Comment by chrisbianca** [comment]
@connercms when your app is hanging can you try doing a write to Firestore from the web console? There is apparently a known Firestore issue which causes this to happen in unexplained cases until a write has happened.

I’ll link the issue in the morning when I’m on my PC.

**Comment by connercms** [comment]
I will check logs and try a write to store from console in the morning and get back to you both

**Comment by connercms** [comment]
I opened a support ticket with Firebase and after speaking with them I think it has to do with how we were using security rules and may be a bug with that instead, as I haven't been able to reproduce it when not using security rules.

**Comment by chrisbianca** [comment]
@connercms Great, thanks for the update. Are you happy for me to close this issue down as sounds like it is on the Firebase / security rules side of things rather than anything RNFirebase related?

**Comment by connercms** [comment]
Yep. Thanks again

**Comment by jemise111** [comment]
@chrisbianca Would you be able to post a link to the issue you mentioned about? I think I may be experiencing a similar issue, thanks!

**Comment by chrisbianca** [comment]
@jemise111 Unfortunately, the link is on a private Firebase group so I can't link to it

**Comment by JimTeva** [comment]
@connercms I just had the same issue with latest RNF 6.3.2. It was happening only on iOS emulator and not on device...

I realized setting the listener in componentDidMount was happening a bit too fast.
It was like Firebase hasn't finished initialized but the onSnapshot query was running.

Then I set a timer with 200ms:
 setTimeout(() => {
      this.props.myActionToFetchFirebase();
    }, 200); and it worked.

You can try different duration to fit your needs.

**Comment by tomchify** [comment]
I was getting an issue loading data from my /users collection as described above. Ultimately, I solved my own hang up by adding the following code before my /users data listener (.onSnapshot call). Note I use mobx. Hope it's helpful to someone:

```
await when(() => {
      return (firebase.auth().currentUser && firebase.auth().currentUser.uid);
});
```

**Comment by Joshandrews43** [comment]
This is still an issue for me with the latest version. Restarting my react native server fixes it, but it happens randomly in development and not in production as far as I know.
