### ISSUE TITLE
[🐛] 🔥  [iOS] In-App Messaging: Top Banner hides behind Notch

### ISSUE THREAD

**Issue by CYBERKING40** [invertase/react-native-firebase#5961]
## Issue

Describe your issue here
In iOS Devices Which has Notch In-App Messaging Top Banner hides behind Notch

![Screen Shot 2021-12-24 at 10 01 30 AM](https://user-images.githubusercontent.com/95463997/147316929-36326402-ad25-4a8a-bee5-9b0f9cd65860.png)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
    "@invertase/react-native-apple-authentication": "^2.1.5",
    "@react-native-async-storage/async-storage": "^1.15.13",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-cookies/cookies": "^6.0.11",
    "@react-native-firebase/analytics": "^13.0.1",
    "@react-native-firebase/app": "^13.0.1",
    "@react-native-firebase/auth": "^13.0.1",
    "@react-native-firebase/crashlytics": "^13.0.1",
    "@react-native-firebase/database": "^13.0.1",
    "@react-native-firebase/dynamic-links": "^13.0.1",
    "@react-native-firebase/in-app-messaging": "^13.0.1",
    "@react-native-firebase/messaging": "^13.0.1",
    "@react-native-firebase/perf": "^13.0.1",
    "@react-native-firebase/remote-config": "^13.0.1",
    "@react-native-google-signin/google-signin": "^7.0.1",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "@stream-io/flat-list-mvcp": "^0.10.1",
    "d3-shape": "^2.1.0",
    "expo-barcode-scanner": "^10.2.2",
    "expo-camera": "^11.1.2",
    "expo-local-authentication": "11.1.1",
    "i18n-js": "^3.8.0",
    "lottie-ios": "3.2.3",
    "lottie-react-native": "^4.1.3",
    "mobx": "^6.3.6",
    "mobx-react": "^7.2.1",
    "moment": "^2.29.1",
    "numeral": "^2.0.6",
    "react": "17.0.2",
    "react-native": "0.66.3",
    "react-native-bidirectional-infinite-scroll": "^0.3.3",
    "react-native-countdown-component": "^2.7.1",
    "react-native-country-picker-modal": "^2.0.0",
    "react-native-device-info": "^8.4.5",
    "react-native-dropdown-picker": "^5.2.3",
    "react-native-fast-image": "^8.5.11",
    "react-native-fbsdk-next": "^4.6.0",
    "react-native-gesture-handler": "^2.1.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localize": "^2.1.5",
    "react-native-logs": "^3.0.4",
    "react-native-looped-carousel": "^0.1.13",
    "react-native-modal": "^13.0.0",
    "react-native-nfc-manager": "^3.11.0",
    "react-native-orientation-locker": "^1.4.0",
    "react-native-qrcode-svg": "^6.1.1",
    "react-native-reanimated": "^2.2.4",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.10.1",
    "react-native-size-matters": "^0.4.0",
    "react-native-snap-carousel": "^4.0.0-beta.6",
    "react-native-svg": "^12.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-swiper": "^1.6.0",
    "react-native-unimodules": "^0.14.10",
    "react-native-vector-icons": "^8.1.0",
    "react-native-walkthrough-tooltip": "^1.3.0",
    "react-native-webview": "11.14.4",
    "throttle-debounce": "^3.0.1",
    "use-count-up": "^3.0.1"
  },
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS (Devices with Notch or SafeArea)
- **`react-native-firebase` version you're using that has this issue:**
  - `13.0.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `In-App Messaging`
- **Are you using `TypeScript`?**
  - `No`

</p>
</details>

---

**Comment by andersonaddo** [comment]
gonna have to fill the template since we need a App.js file to show how to reproduce this.

Looks project specific? Like, using a SafeAreaView is meant to prevent this.

**Comment by CYBERKING40** [comment]
> gonna have to fill the template since we need a App.js file to show how to reproduce this.
> 
> Looks project specific? Like, using a SafeAreaView is meant to prevent this.

There is no other configuration in In-App Messaging
https://rnfirebase.io/in-app-messaging/usage

**Comment by mikehardy** [comment]
Yeah, it may be at the native level. Out of curiosity, does the same thing happen in firebase-ios-sdk? https://github.com/firebase/quickstart-ios/tree/master/inappmessaging - may be we need to calculate insets ourselves in our native code (or reuse the native calculation capabilities of react-native-safe-area or something)
