### ISSUE TITLE
Is the Firebase Admin SDK supported?

### ISSUE THREAD

**Issue by callagga** [invertase/react-native-firebase#598]
Is the Firebase Admin SDK supported?  I basically ask this to understand whether either of these two security approach would be possible from an app?  (I think not as they might need a service account)

https://firebase.google.com/docs/auth/admin/create-custom-tokens
https://firebase.google.com/docs/auth/admin/custom-claims

Background: Trying to understand options for how you could "share" access to a "todo" list stored in Clound Firestore to others in a secure fashion.

**Comment by chrisbianca** [comment]
@callagga No, the Firebase Admin SDK is only supported on servers as it requires a service account which can not be kept secure within an app.

To share access to a todo list, you need to take a look at security rules.  It's most definitely possible to use these in a way that would allow shared access to a particular `todo` document or collection.

**Comment by munkhorgil** [comment]
@chrisbianca There is no API for delete authenticated user in Firebase SDK, after removing a user from database you cannot register again with existing email. That is why Firebase Admin SDK needed to delete user completely.

**Comment by Ehesp** [comment]
@munkhorgil that is not something the app should be handling. You need to setup some Cloud Functions to handle triggers and do this on a server.
