### ISSUE TITLE
[🐛] 🔥 App Check drastically slowing down Firestore transactions

### ISSUE THREAD

**Issue by okcompewter** [invertase/react-native-firebase#5983]
## Issue

I've just added App Check to my Android RN app, and I immediately noticed a several second performance hit when performing a Firestore transaction that gets 1 document, and update 3 documents.

In my app.tsx:

when adding
`await firebase.appCheck().activate('ignored', true)`
a transaction takes about 2 seconds

when commenting this back out
`//await firebase.appCheck().activate('ignored', true)`
a transaction is back to taking only a tenth of a second

I've tried this against a production Firestore, on emulated devices and physical devices, as debug and release builds, and it occurs every time.

I didn't realize there would be such a performance hit to Firestore transaction updates by enabling App Check...?

AFAIK, this slow down is only on the client side, since I have not even enabled/enforced App Check within Firebase yet.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 17.88 GB / 31.94 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 24, 25, 26, 27, 28, 29, 30, 31
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_221 - C:\Program Files\Java\jdk1.8.0_221\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.66.1 => 0.66.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `14.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/app-check`
  - `@react-native-firebase/firestore`
- **Are you using `TypeScript`?**
  - `Y` & `3.7.2`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I cannot spend any time on this if you ignore the issue template @okcompewter - in the related discussion you mentioned windows and JDK8 and android emulators and all of that gives me pause.
It would be useful to see an App.js that was minimal and self-contained in order to reproduce this in a clean app, ideally while running on a real device

**Comment by okcompewter** [comment]
I switched to latest JDK 17.
Then had to remove `-XX:MaxPermSize=2048m` from `\tests\android\gradle.properties` to get the test app to build without error.
But the e2e tests always fail for me here:
```
  auth()
    1) "before all" hook in "auth()"

detox[46260] INFO:  at e2e\init.js:55:11
  ✨ Tests Complete ✨
The syntax of the command is incorrect.
detox[46260] INFO:  at e2e\init.js:79:15
 Unable to download coverage data from device:  {"status":1,"signal":null,"output":[null,{"type":"Buffer","data":[]},{"type":"Buffer","data":[84,104,101,32,115,121,110,116,97,120,32,111,102,32,116,104,101,32,99,111,109,109,97,110,100,32,105,115,32,105,110,99,111,114,114,101,99,116,46,13,10]}],"pid":47628,"stdout":{"type":"Buffer","data":[]},"stderr":{"type":"Buffer","data":[84,104,101,32,115,121,110,116,97,120,32,111,102,32,116,104,101,32,99,111,109,109,97,110,100,32,105,115,32,105,110,99,111,114,114,101,99,116,46,13,10]}}

  84 passing (3m)
  6 pending
  1 failing

  1) auth()
       "before all" hook in "auth()":
     NativeFirebaseError: [auth/network-request-failed] A network error (such as timeout, interrupted connection or unreachable host) has occurred.
      at FirebaseAuthModule.createUserWithEmailAndPassword (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.invertase.testing&modulesOnly=false&runModule=true&sourceMapURL=true:114482:28)
      at Context.<anonymous> (C:\Users\surfa\code\github\invertase\react-native-firebase\packages\auth\e2e\auth.e2e.js:29:27)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
Would be great to hear from anyone in the community, whether they could repro within their own app that uses AppCheck alongside a Firestore transaction.

Seeing as AppCheck just recently added to support for Firestore on Nov 10, 2021 (https://firebase.googleblog.com/2021/11/whats-new-at-Firebase-Summit-2021.html#Strengthening)... I'm inclined to say it may be something on their end that needs ironed out, but I've been unsuccessful in finding anything on it.

**Comment by mikehardy** [comment]
Not sure I'd go all the way to JDK17 :sweat_smile: - sticking with the defaults (JDK11 right now) in the underlying tool chains is usually the smoothest path. 

Are you sure you are running the emulator? Most likely you are not since it's a bash script, though if you run it via WSL it should work https://github.com/invertase/react-native-firebase/blob/main/.github/workflows/scripts/start-firebase-emulator.sh

The alternative to get the e2e tests to run is to execute against the real cloud services (not the local firebase emulator) which you can do by commenting out all the emulator stuff in https://github.com/invertase/react-native-firebase/blob/8015779035835e03746754a1f28b16bd83407376/tests/app.js#L46-L54

Since react-native-firebase has to support apple devices we're pretty unix-y for dev work, it doesn't make much sense to make .bat files to run this stuff unfortunately so it's a bit of a rough go on windows as a development platform, apologies

**Comment by okcompewter** [comment]
Sure, I just went with the latest LTS version (17). Switched to 11 now.

When I run `yarn tests:emulator:start`, a Git Bash window opens, says Starting Firebase Emulator Suite, then eventually prints some things too fast for me to see and the window closes... so I'm guessing the emulator is not online.

So, I went with the non-emulator approach by commenting out all those lines you said, but now there is an error for auth() about the email address is already in use:
```
  1) auth()
       "before all" hook in "auth()":
     NativeFirebaseError: [auth/email-already-in-use] The email address is already in use by another account.
      at FirebaseAuthModule.createUserWithEmailAndPassword (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.invertase.testing&modulesOnly=false&runModule=true&sourceMapURL=true:114474:28)
      at Context.<anonymous> (C:\Users\surfa\code\github\invertase\react-native-firebase\packages\auth\e2e\auth.e2e.js:29:27)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
I think I'll wait to hear back from Firebase support at this point, I just filed a support ticket with them re: AppCheck and Firestore transactions in general... thanks for the help @mikehardy!

**Comment by mikehardy** [comment]
The local emulator is remarkably easy to run actually if you see the actual commands in use, and it is a much faster and cheaper way to develop, that is you may find it's worth the trouble to run. At any rate I just have a windows develo environment running and I'll check this in parallel but it may be a few days still

**Comment by okcompewter** [comment]
No problem. FWIW - Firebase support says they didn’t find any similar ticket/bug that has been reported at all by other developers at the Firebase SDK level.

**Comment by mikehardy** [comment]
This matches my experience at least, I've seen no delay in my testing during implementation of AppCheck. But it's pretty new, and I don't have a specific test targeted at your scenario (yet), so we may all learn something. I will tell you that my default stance on this at the moment, or stated better, my hypothesis is that you have something local / project-specific going on. What? No idea. Should be documented here even if it's project-specific? Maybe? But even with that bias, scientifically, there's always: Hypothesis could be wrong and we're about to learn there's a bug in here? Definitely a possibility, need to run the experiment to see....

**Comment by okcompewter** [comment]
Well, I'm not sure what I did differently, but the problem seems to no longer repro on my end...

But now I'm finding AppCheck isn't verifying my requests like I thought, they're all being denied when I enforce AppCheck on Firestore... I posted some questions to the Discord community on more detailed integration steps.

I think we can close this for now, thanks again @mikehardy.

**Comment by mikehardy** [comment]
Okay, I'll close then, glad thus at least is not a problem!
