### ISSUE TITLE
Notification with image implementation issue in iOS

### ISSUE THREAD

**Issue by vipu-sa** [invertase/react-native-firebase#5985]
https://rnfirebase.io/messaging/ios-notification-images

I am following the above link for the notification with the image in iPhone, but the image is not getting with notification.

I am sharing the details of current versions which are used in my project.
"react-native": "0.62.2",
"@react-native-firebase/app": "^8.4.0",
"@react-native-firebase/messaging": "^7.8.1",
Firebase/Messaging (6.34.0) in Podfile.lock
In project, Deployment Info, iOS version is 14.4
In my iPhone device version is 14.7.1

Getting build fail issue when inserting the below line in NotificationService file.
#import "FirebaseMessaging.h"
[[FIRMessaging extensionHelper] populateNotificationContent:self.bestAttemptContent withContentHandler:contentHandler];

Please help to solve this issue.

**Comment by mikehardy** [comment]
Hi there! Please upgrade to current stable versions and log a new issue with an App.js snippet that will reproduce when included in a clean app (e.g. from https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh) https://stackoverflow.com/help/minimal-reproducible-example / https://stackoverflow.com/help/how-to-ask

Current versions are 14.2.1 - https://invertase.io/blog/react-native-firebase-versioning
