### ISSUE TITLE
Error: No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()

### ISSUE THREAD

**Issue by zoobibackups** [invertase/react-native-firebase#5993]
Google signIn working correctly but **auth().signInWithCredential(googleCredential)** causes this error.

```
try {
      await GoogleSignin.hasPlayServices();
      const userInfo = await GoogleSignin.signIn(); // working
      const googleCredential = auth.GoogleAuthProvider.credential(userInfo?.idToken); // working
      auth().signInWithCredential(googleCredential).then((data) => {     // this generate error
           console.log(data)
      })
  } catch (error) {
      window.alert(error) 
  }
```
The error log:

`Error: No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()`

I don't know what i am missing here. Do I need any configuration for it??
Thanks in advance!

**Comment by mikehardy** [comment]
Hi there! We have an issue template, which you have removed (you actually have to remove it, it is a conscious act) so I'm going to close this as there is not sufficient information to make any informed statements

https://stackoverflow.com/help/how-to-ask

I'm going to guess that you have not followed the integration guides for `@react-native-firebase/app` as you integrated react-native-firebase.
I provide a couple demonstrations that you can compare to your project to see where things went wrong
https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh
https://github.com/invertase/react-native-firebase-authentication-example

**Comment by zoobibackups** [comment]
> Hi there! We have an issue template, which you have removed (you actually have to remove it, it is a conscious act) so I'm going to close this as there is not sufficient information to make any informed statements
> 
> https://stackoverflow.com/help/how-to-ask
> 
> I'm going to guess that you have not followed the integration guides for `@react-native-firebase/app` as you integrated react-native-firebase. I provide a couple demonstrations that you can compare to your project to see where things went wrong https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh https://github.com/invertase/react-native-firebase-authentication-example

You made a guess and close the issue wow.

**Comment by mikehardy** [comment]
No, @zoobibackups - you ignore the template and I close the issue.

The guess was for your benefit. The template ignoring resulted in the close.

**Comment by iChristosK** [comment]
Having the same issue. Please open this.

**Comment by mikehardy** [comment]
@iChristosK I will not - but you may feel free to open a new issue if you have not already. Please mind the template, we can't help when there's no information provided.
These are great guides:
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

And you can generate a quick skeleton to see how to integrate everything so this problem doesn't happen, using this script https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

If you can use that script and reproduce the problem, we'll have a real issue to fix

**Comment by mohammedelnady** [comment]
re-open it

**Comment by mikehardy** [comment]
No.

Please open a new issue *following the template* (that is, providing the necessary information to help https://stackoverflow.com/help/how-to-ask)

Simply stating, with no evidence provided "re-open it" is doing open source wrong, please consider https://medium.com/hackernoon/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b

Open source means you're the developer of the open source package, not the user. Bring information and help, not demands please

**Comment by adamsadiq7** [comment]
At the end of the day, the package names for my android app and my google-services.json were different. Changing it from the firebase end was fine, but if not maybe try changing it from the project end: https://stackoverflow.com/questions/37389905/change-package-name-for-android-in-react-native

**Comment by talaikis** [comment]
Go through "Getting started": https://rnfirebase.io/
