### ISSUE TITLE
[📚] Possible incorrect build.gradle path 

### ISSUE THREAD

**Issue by joaoramalho** [invertase/react-native-firebase#5997]
Hello,

I'm following the documentation to install the Firebase framework to my React Native app and I'm a bit confused with the following part:

> Configure Firebase with Android credentials
To allow Firebase on Android to use the credentials, the google-services plugin must be enabled on the project. This requires modification to two files in the Android directory.
First, add the google-services plugin as a dependency inside of your /android/build.gradle file:

`buildscript {
  dependencies {
    // ... other dependencies
    classpath 'com.google.gms:google-services:4.3.10'
    // Add me --- /\
  }
}
`

When I open /android/build.gradle file, under dependecies I have this note:

`// NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files`

So, from what I understand, I should not be placing the google services classpath on this build.gradle file but instead on the build.gradle that is inside the app folder, which is /android/app/build.gradle.

Am I missing something?

Thanks in advance.

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there!
Read this script (to understand what to do) then run it also if you like and check the output, it will show you exactly what must be done to integrate:
https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by mikehardy** [comment]
You'll notice the things related to the *build* of the whole system (that is, the google services plugin, perhaps the firebase performance and/or crashlytics plugins) all go in the top level android file. This is because they affect gradle itself, and how it compiles things, not just your specific module. That might help explain things?

**Comment by joaoramalho** [comment]
Hello,

Ah! I got it now. Sorry, my experience with gradle or Android Dev is very limited.

I can see on your shell script that you are adding the google services plugin on the top level file (line 29).

I'll follow the instructions accordingly and check your script. 


Thank you very much for your quick explanation.

In this case, I consider this issue as Closed.
