### ISSUE TITLE
Updating to newer versions

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#6]
Whats the correct way to update `react-native-firebase` ? I usually `yarn add react-native-firebase` and then `react-native link` is this correct way to approach this?

**Comment by Salakar** [comment]
Update as in switching versions​, say alpha5 to alpha6? If so, you o!ly need to update the npm module, no need to re link every time.

**Comment by Ehesp** [comment]
If you've already installed the module, simply follow the following:

1. Update package.json to new version.
2. Re-run the start command (`node node_modules/react-native/local-cli/cli.js start`).
3. Re-install/run your build for the platform (`react-native run-android/run-ios`).

**Comment by IljaDaderko** [comment]
@Ehesp @Salakar thanks guys. So native side of the code isn't updated at all, just curious now, as I saw libraries like https://github.com/yutin1987/react-native-bridge-firebase where it has quiet a lot of native side implementation. In the future if you change something there, will simple re-linking solve the issue?
