### ISSUE TITLE
Firebase Invites

### ISSUE THREAD

**Issue by jeveloper** [invertase/react-native-firebase#60]
Just curious what you think of this library and if you thought of adding that part of this?

Thanks !

**Comment by Ehesp** [comment]
Its something we'd like to implement, however internally we've not used
them so hasn't been a priority.

**Comment by jeveloper** [comment]
Thanks for your response.

I personally haven't used it either. It seems that they are simplifying what normally would happen via push notifications with a payload. Also google used to have app invites.

**Comment by chrisbianca** [comment]
At a quick look, it shouldn't be too difficult to add to the library.  Most of the complexity on iOS comes from the setup to handle incoming invitations, triggering them is fairly trivial.

I may have some time next week to have a proper look, I'm a bit snowed under at the moment!

**Comment by jeveloper** [comment]
Thanks Chris , hopefully i can allocate time and help out

**Comment by Salakar** [comment]
Closing - should be moved to the project board for now =]

**Comment by brunolemos** [comment]
+1 for this

**Comment by brunolemos** [comment]
@Salakar How do we track its roadmap?
