### ISSUE TITLE
[Android] Not receive message when apps terminate from task 

### ISSUE THREAD

**Issue by sirstevensu** [invertase/react-native-firebase#600]
### Issue

Data from server : 
 ```
$custom_notif = array(
 	'custom_notification' => array(
 		'title'=> "Hello World",
 		'body'=> "Lorem ipsum dolor sit amet",
 		'sound'=> "default",
 		'priority'=> 'high'
 		'click_action'=> "OPEN_MAIN_ACTIVITY",
 		'auto_cancel'=> true,
 		'large_icon'=> "ic_launcher",
 		'show_in_foreground'=> true,
 		'opened_from_tray'=> true,
 		'content_available'=> true,
 	),
 	'data' => 'consectetur adipisicing elit'
 )

 $message = arrat(
 	'title'=> "Hello World",
	'body'=> "Lorem ipsum dolor sit amet",
 )

 $fields = array(
 'registration_ids' => $reg_id, 
 'data' => $custom_notif, 
 'priority'=> "high", 
 'notification'=>$message
 );
```

on IOS its work fully. but on Android that's problem
when apps on foreground  and background its work. but when apps terminate/kill from task it's not work (cannot receive message)

### Environment

1. Application Target Platform: Android

2. Development Operating System: Windows 7

3. Build Tools: Android SDK 23.0.1

4. React Native version: 0.48.1

5. RNFirebase Version: 3.0.5

6. Firebase Module: Cloud Messaging

**Comment by chrisbianca** [comment]
We're aware of lots of issues with messaging and will be resolving as part of the 3.2.0 release. Please see: https://github.com/invertase/react-native-firebase/issues/595

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)
