### ISSUE TITLE
How to fix Error: [messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE

### ISSUE THREAD

**Issue by NongKaittong** [invertase/react-native-firebase#6000]
Error: [messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE

System:
    OS: macOS 12.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 118.79 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.5 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    @react-native-firebase/app": "^14.2.1",
    @react-native-firebase/messaging": "^14.2.1"

**Comment by mikehardy** [comment]
Hi there! You've skipped our issue template and not really asked a great question here, I'm not really going to be able to help and with no template we typically close the issue, which I will do here

For future:
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

These should help, the top results look like they are on target for you https://duckduckgo.com/?q=%5Bmessaging%2Funknown%5D+java.io.IOException%3A+java.util.concurrent.ExecutionException%3A+java.io.IOException%3A+SERVICE_NOT_AVAILABLE&t=newext&atb=v278-1&ia=web
