### ISSUE TITLE
How can i pause to receiving the push notification in the client app

### ISSUE THREAD

**Issue by tikkichan4** [invertase/react-native-firebase#601]
### Issue

In my use cases, the user can subscribe other user's feed. I want to add a feature that the user can stop receiving all the notification by disabling from the global app setting.

How i can implement this function for IOS and ANDROID platform ? I am confused with this issue around 5 days. Please help ! Thanks a lot ....

### Environment

1. Application Target Platform:  Both

2. Development Operating System: N/A

3. Build Tools: N/A

4. React Native version: 0.49.2

5. RNFirebase Version: 3.1.0

6. Firebase Module: messaging

**Comment by Salakar** [comment]
Thanks for reporting. We're aware of lots of issues with notifications/messaging and will be addressing them all as part of the v3.2.0 release stream. Please see #595 for updates.

**Comment by Ehesp** [comment]
To add; I'd suggest handling this in your database and only send to users who want the data. For example when a user adds a new post then query the database to get subscribed users. Cloud Functions should make this pretty trivial!
