### ISSUE TITLE
[🐛] Firebase performance monitoring crash ios app after start

### ISSUE THREAD

**Issue by NetPumi2** [invertase/react-native-firebase#6019]
## Issue
I am using firebase on our project for some time now. And we decide to implement performance monitoring. I updated all FB packages to the latest version and all works fine. After the update, I added "@react-native-firebase/perf": "^14.2.2" install pods and set up android. Android works fine but ios have some issues after adding this package.

When I open the ios app it loads and runs fine for 30 seconds and then freeze and I can catch this error in the Xcode log:

```
2022-01-20 12:32:31.885175+0100 APPNAME[473:51878] -[fir_7891ABC3-3A54-4945-8F53-592D0CAF4D03_GULNetworkURLSession _flex_swizzle_8d46847a_URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:]: unrecognized selector sent to instance 0x28003a2e0

2022-01-20 12:32:31.886164+0100 APPNAME[473:51878] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[fir_7891ABC3-3A54-4945-8F53-592D0CAF4D03_GULNetworkURLSession _flex_swizzle_8d46847a_URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:]: unrecognized selector sent to instance 0x28003a2e0'
*** First throw call stack:
(0x1818a50fc 0x19a0ead64 0x1819820c4 0x18183a524 0x181839660 0x102ed4b74 0x102ecb254 0x102ed49d4 0x1820afe1c 0x105c446d4 0x105c463b4 0x105c56898 0x18185dd84 0x181817f5c 0x18182b468 0x19d3c338c 0x1841ce5cc 0x183f4cf70 0x102a11bec 0x105b11aa4)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[fir_7891ABC3-3A54-4945-8F53-592D0CAF4D03_GULNetworkURLSession _flex_swizzle_8d46847a_URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:]: unrecognized selector sent to instance 0x28003a2e0'
terminating with uncaught exception of type NSException
```

#### `package.json`:

```json
  "react-native": "0.64.1",

    "@react-native-firebase/analytics": "^14.2.2",
    "@react-native-firebase/app": "^14.2.2",
    "@react-native-firebase/crashlytics": "^14.2.2",
    "@react-native-firebase/perf": "^14.2.2",
```
NOTE: I tried downgrade firebase to the originally used version 13.1.0 and after then i added `perf` with this version and the error is still present

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "crashlytics_debug_enabled": false,
    "analytics_auto_collection_enabled": true
  }
}
```

- **Platform that you're experiencing the issue on**:
  - [x ] iOS

- **`react-native-firebase` version you're using that has this issue:**
  - `14.2.2`
- **`Firebase` module(s) you're using that has the issue:**
  - `Firebase performance monitoring`

**Comment by mikehardy** [comment]
Smells like #4935 - please check that one - you have very carefully omitted parts of the issue template that are important for troubleshooting. Not sure why people do that, but it means I'm unable to help

I would very carefully examine if you can get your react-native (and flipper) versions etc current, and also make sure you've done `npx react-native-clean-project` so there are no mismatched objects from any of the build cache layers.

If you can reproduce with https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh (or some light modification of it, to show a problem) we can reopen.

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by NetPumi2** [comment]
thx 
in this case i was able to fix this with  `use_flipper!({ 'Flipper' => '0.78'})`
