### ISSUE TITLE
[🐛]  Duplicate class com.google.android.gms.ads.identifier.AdvertisingIdClient with remote-config or analytics

### ISSUE THREAD

**Issue by SimonErich** [invertase/react-native-firebase#6030]
## Issue

After running yarn install today, I cannot build my application anymore.
I have not made any changes to any packages or the code, but it started failing with the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.google.android.gms.ads.identifier.AdvertisingIdClient found in modules jetified-play-services-ads-identifier-18.0.0-runtime.jar (com.google.android.gms:play-services-ads-identifier:18.0.0) and jetified-play-services-analytics-7.8.0-runtime.jar (com.google.android.gms:play-services-analytics:7.8.0)
  Duplicate class com.google.android.gms.ads.identifier.AdvertisingIdClient$Info found in modules jetified-play-services-ads-identifier-18.0.0-runtime.jar (com.google.android.gms:play-services-ads-identifier:18.0.0) and jetified-play-services-analytics-7.8.0-runtime.jar (com.google.android.gms:play-services-analytics:7.8.0)
  
  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
```

I realize that this issue has been asked quite a bit, but all of the tipps (hardcoding bom or the class) did not work.
I also upgraded to the latest version of react-native-firebase packages (14.2.4), but it still appears.

Also tried ./gradlew clean multiple times, ...

I use the following 5 react-native packages:
```
    "@react-native-firebase/analytics": "^14.2.4",
    "@react-native-firebase/app": "^14.2.4",
    "@react-native-firebase/crashlytics": "^14.2.4",
    "@react-native-firebase/dynamic-links": "^14.2.4",
    "@react-native-firebase/remote-config": "^14.2.4",
```

I realized, that if I remove analytics and remote-config, the error goes away and I can build normally.
I can reproduce it. Everytime I add one of these two packages, the error appears again.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/analytics": "^14.2.4",
    "@react-native-firebase/app": "^14.2.4",
    "@react-native-firebase/crashlytics": "^14.2.4",
    "@react-native-firebase/dynamic-links": "^14.2.4",
    "@react-native-firebase/remote-config": "^14.2.4",
    "react": "16.13.1",
    "react-native": "0.63.4",

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [X] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [X] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
    Memory: 481.39 MB / 31.04 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.asdf/installs/nodejs/14.18.1/bin/node
    Yarn: 1.22.17 - ~/.asdf/installs/nodejs/14.18.1/.npm/bin/yarn
    npm: 6.14.15 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 27, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0, 32.0.0, 32.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ X ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `all`
- **`Firebase` module(s) you're using that has the issue:**
  - `analytics/remote config`
- **Are you using `TypeScript`?**
  - `yes`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hmmm
What's the full set of dependencies in package.json? That might point the way
`npx react-native-clean-project` maybe
otherwise, that's a stumper

I just ran https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh to double-check locally, and it seems that android built fine, debug and release mode.

**Comment by SimonErich** [comment]
@mikehardy thanks for taking a look.
By removing package by package, I found the problematic package.
It seems to be: https://www.npmjs.com/package/react-native-onetrust-cmp

Unfortunately I cannot find a way to them work together.
Is there a way to align the firebase version with the version used there?

**Comment by mikehardy** [comment]
Can't say sorry, I have no experience with that package. You can override our SDK version though sure. Documented on rnfirebase.io in the install area

**Comment by mikehardy** [comment]
Here it is as a direct link now that I'm in front of a computer: https://rnfirebase.io/#overriding-native-sdk-versions

Since we do allow override, or you can use gradle `build.gradle` tricks in order to pin the dependency as needed, but it's for a separate module, I'm not sure that there is anything actionable here, so I'm going to close it, but I do hope the info provided is a real help. Cheers

**Comment by ferasabufares** [comment]
can you please help me with this i am stuck here 
 app BUILD FAILED after installing  @react-native-firebase/app

for more info 
https://stackoverflow.com/questions/76443737/react-native-app-build-failed-after-installing-react-native-firebase-app
```

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.gms.internal.measurement.zzdu found in modules jetified-firebase-analytics-impl-16.1.1-runtime (com.google.firebase:firebase-analytics-impl:16.1.1) and jetified-play-services-measurement-sdk-api-21.3.0-runtime (com.google.android.gms:play-services-measurement-sdk-api:21.3.0)
     Duplicate class com.google.android.gms.internal.measurement.zzdv found in modules jetified-firebase-analytics-impl-16.1.1-runtime (com.google.firebase:firebase-analytics-impl:16.1.1) and jetified-play-services-measurement-sdk-api-21.3.0-runtime (com.google.android.gms:play-services-measurement-sdk-api:21.3.0)
     Duplicate class com.google.android.gms.internal.measurement.zzdw found in modules jetified-firebase-analytics-impl-16.1.1-runtime (com.google.firebase:firebase-analytics-impl:16.1.1) and jetified-play-services-measurement-sdk-api-21.3.0-runtime (com.google.android.gms:play-services-measurement-sdk-api:21.3.0)
     Duplicate class com.google.android.gms.internal.measurement.zzdx found in modules jetified-firebase-analytics-impl-16.1.1-runtime (com.google.firebase:firebase-analytics-impl:16.1.1) and jetified-play-services-measurement-sdk-api-21.3.0-runtime (com.google.android.gms:play-services-measurement-sdk-api:21.3.0)
     Duplicate class com.google.android.gms.internal.measurement.zzdy found in modules jetified-firebase-analytics-impl-16.1.1-runtime (com.google.firebase:firebase-analytics-impl:16.1.1) and jetified-play-services-measurement-sdk-api-21.3.0-runtime (com.google.android.gms:play-services-measurement-sdk-api:21.3.0)
     Duplicate class com.google.android.gms.internal.measurement.zzdz found in modules jetified-firebase-analytics-impl-16.1.1-runtime (com.google.firebase:firebase-analytics-impl:16.1.1) and jetified-play-services-measurement-sdk-api-21.3.0-runtime (com.google.android.gms:play-services-measurement-sdk-api:21.3.0)
     Duplicate class com.google.android.gms.internal.measurement.zzea found in modules jetified-firebase-analytics-impl-16.1.1-runtime (com.google.firebase:firebase-analytics-impl:16.1.1) and jetified-play-services-measurement-sdk-api-21.3.0-runtime (com.google.android.gms:play-services-measurement-sdk-api:21.3.0)
     Duplicate class com.google.android.gms.internal.measurement.zzeb found in modules jetified-firebase-analytics-impl-16.1.1-runtime (com.google.firebase:firebase-analytics-impl:16.1.1) and jetified-play-services-measurement-sdk-api-21.3.0-runtime (com.google.android.gms:play-services-measurement-sdk-api:21.3.0)
     Duplicate class com.google.android.gms.internal.measurement.zzec found in modules jetified-firebase-analytics-impl-16.1.1-runtime (com.google.firebase:firebase-analytics-impl:16.1.1) and jetified-play-services-measurement-sdk-api-21.3.0-runtime (com.google.android.gms:play-services-measurement-sdk-api:21.3.0)
```
