### ISSUE TITLE
Error: [storage/unknown] java.lang.Double cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by Saalim95** [invertase/react-native-firebase#6035]
## Issue

Storage upload working fine in iOS but not in Android. I am using `putFile()` method.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "ShelfWatch",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "reset": "watchman watch-del-all && rm -rf node_modules && npm install && npm start --reset-cache && rm -rf /tmp/metro-*",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/netinfo": "^5.2.0",
    "@react-native-firebase/app": "^14.2.2",
    "@react-native-firebase/crashlytics": "^14.2.2",
    "@react-native-firebase/storage": "^14.2.2",
    "@sentry/react-native": "^3.2.3",
    "@tensorflow/tfjs": "^1.5.1",
    "@tensorflow/tfjs-react-native": "0.1.0-alpha.2",
    "buffer": "^5.4.3",
    "expo-gl": "^8.0.0",
    "expo-gl-cpp": "^8.0.0",
    "lodash": "^4.17.15",
    "patch-package": "^6.2.2",
    "promise-reflect": "^1.1.0",
    "pusher-js": "^7.0.3",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-actionsheet": "^2.4.2",
    "react-native-background-job": "^2.3.1",
    "react-native-camera": "3.31.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-device-info": "^5.5.8",
    "react-native-fast-image": "^8.3.4",
    "react-native-fs": "^2.16.2",
    "react-native-geolocation-service": "^3.1.0",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-gesture-responder": "^0.1.1",
    "react-native-i18n": "^2.0.15",
    "react-native-image-pan-zoom": "^2.1.11",
    "react-native-image-picker": "^2.3.1",
    "react-native-image-resizer": "^1.1.0",
    "react-native-image-zoom-viewer": "^2.2.27",
    "react-native-mixpanel": "^1.2.0",
    "react-native-onesignal": "^3.6.1",
    "react-native-permissions": "^2.0.8",
    "react-native-picker-select": "^6.5.1",
    "react-native-popup-menu": "^0.15.10",
    "react-native-progress-circle": "^2.1.0",
    "react-native-queue": "^1.2.1",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area": "^0.5.1",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^2.0.0-alpha.22",
    "react-native-simple-picker": "^3.1.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^11.0.1",
    "react-native-svg-charts": "^5.3.0",
    "react-native-unimodules": "^0.7.0",
    "react-native-url-polyfill": "^1.2.0",
    "react-native-uuid": "^1.4.9",
    "react-native-vector-icons": "^8.1.0",
    "react-native-zip-archive": "^5.0.0",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.3.3",
    "react-navigation-stack": "^1.10.3",
    "react-redux": "^7.1.3",
    "realm": "^3.6.0",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "socket.io-client": "^2.3.0",
    "throttle-debounce": "^2.1.0",
    "ulid": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.7.7",
    "@babel/runtime": "^7.7.7",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "^6.8.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.57.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by mikehardy** [comment]
Hey @Saalim95 :wave: 

Can you post the code snippet that triggers it, and the exception stack pulled from `adb logcat`? We test putFile in e2e on android and don't see this, so it's either project-specific or our test cases need some improvement (in tandem with repair in the module), but more information would help.

Also - not sure about react-native 0.61.5 - I'm surprised that even works on Android 10, must less 12 - it's on 0.67.1 now, I'd get busy with https://react-native-community.github.io/upgrade-helper/ if there was any time available

Thanks

**Comment by Saalim95** [comment]
Hi Mike, thanks for your prompt response. Here's my code snippet:


> 
      const StorageBucket = firebase.app().storage(gcpBucket);
      const reference = StorageBucket.ref(gcpPath);  // gcpPath is a file reference on gcp bucket (string)
      reference
        .putFile(filePath, {customMetadata: metaData})
        .then(res => {
          resolve(res);
        })
        .catch(err => {
          console.log('reject gcp 1**', err);
          reject(err);
        });

**Comment by mikehardy** [comment]
Hey @Saalim95 - I asked multiple things at once.

> and the exception stack pulled from adb logcat?

**Comment by Saalim95** [comment]
> 01-30 19:35:34.757 28707 28752 I ReactNativeJS: { [Error: [storage/unknown] java.lang.Double cannot be cast to java.lang.String]
01-30 19:35:34.757 28707 28752 I ReactNativeJS:   line: 25310,
01-30 19:35:34.757 28707 28752 I ReactNativeJS:   column: 28,
01-30 19:35:34.757 28707 28752 I ReactNativeJS:   sourceURL: 'http://localhost:8081/index.bundle?platform=android&dev=true&minify=false' }

**Comment by mikehardy** [comment]
Please don't constrain the logcat, it loses the information I want. I want the actual java code lines that cause the problem, e.g. 

https://stackoverflow.com/questions/64254157/java-lang-classcastexception-java-lang-string-cannot-be-cast-to-java-lang-doubl

```
 Process: com.example.ketomate, PID: 13156
    java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double
        at com.example.ketomate.BillDetailsForPaymentAndDelivery$2.onDataChange(BillDetailsForPaymentAndDelivery.java:121)
        at com.google.firebase.database.Query$1.onDataChange(Query.java:179)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:75)
        at com.google.firebase.database.core.view.DataEvent.fire(DataEvent.java:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(EventRaiser.java:55)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

That points the error - the heavily filtered logcat you produced does not to point to anything actionable.

Can you try again and post the java stack trace please?

**Comment by Saalim95** [comment]
@mikehardy I think i've found the solution. I was passing customMetadata while uploading the image. There were few keys in the customMetadata whose values were not string but integer/float (coordinates). I explicitly changes all the value to string with `.toString()` and it finally uploaded. Though i still don't know why it was working fine iOS without any data type conversion. Anyways, thank you so much for your time and your contribution. I really appreciate it 🙂.
