### ISSUE TITLE
[🐛] On Android Redmi's phones notification's badge and sound's permissions are not enable by default.

### ISSUE THREAD

**Issue by usamaabutt** [invertase/react-native-firebase#6036]
I have integrated firebase push notifications into a react native app and it's working perfectly fine for the iOS side. But on some Android devices notification's sound and badge permissions are not enabled by default nor I could able to find any solution to enable them programmatically. 

Anyone has faced this issue? and is there any solution for it?

**Testing devices having this issue**
Redmi note 8, Redmi note 9.

Thanks!

**Comment by mikehardy** [comment]
Hi there, you will want either a) react-native-permissions or b) to complain to Xioami if they have made some other non-standard change to AOSP in the MIUI devices - they do this frequently and it's nearly impossible to support Xioami devices because of this

**Comment by usamaabutt** [comment]
Hi @mikehardy thanks for the suggestion to use react-native-permissions but seriously there is no workaround for Android to get notification's badge and sound permissions in it. but yes for iOS it is (but in iOS everything is already working fine).

**Comment by usamaabutt** [comment]
Yes, that makes sense we to complain to Xioami for this but that couldn't fix my issue until this package has made itself compatible with those changes of AOSP. Do you think @mikehardy is there any temporary and quick fix for this issue?

**Comment by mikehardy** [comment]
> Do you think @mikehardy is there any temporary and quick fix for this issue?

No.

If Xioami corrupts the AOSP APIs, what exactly can we do?

I suggest you make a PR to react-native-permissions and/or fork it for react-native-permissions-xioami or something to handle it. It's unreasonable to expect all modules to conform to non-standard behavior
