### ISSUE TITLE
🔥[🐛] TOO_MANY_REGISTRATIONS error with firebase/messaging 

### ISSUE THREAD

**Issue by johnf** [invertase/react-native-firebase#6044]
## Issue

When I push my app to the android store and google run their internal testing I get the following error pushed to Sentry.

> [messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: TOO_MANY_REGISTRATIONS

I believe this is because Google is probably installing lots of apps on their test devices and therefore they legitimately hit the 100 app registration limit.

My code looks like

``` jsx
try {
  defaultAppMessaging.getToken().then(saveToken);
} catch (e) {
  // TODO: Seeing if we can make this more specific so we can cath only the TOO MANY REGISTRATIONS error
  Sentry.captureMessage(`Get Token Error ${e.code} msg: ${e.message}`, {
    level: Sentry.Severity.Error,
    extra: {
      error: e,
    },
  });
}
```
The catch doesn't seem to work, I'm guessing because it's a java error and not a javascript error?

Could this error be caught in the java code and thrown as a javascript error?

I'm happy to help out with a pull request here if that's the right solution.

---

## Project Files

NB: I haven't added most of the project files as I don't think they'll be relevant to this issue, but I can easily provide them if needed.

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

I've summarised this to the relevant packages for respective versions
```json
{
"dependencies": {
    "@notifee/react-native": "^4.0.0",
    "@react-native-async-storage/async-storage": "^1.15.11",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^7.1.2",
    "@react-native-firebase/app": "^14.0.0",
    "@react-native-firebase/messaging": "^14.0.0",
    "@sentry/react-native": "^3.1.1",
    "react": "17.0.2",
    "react-native": "0.67.2",
}
}
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 246.56 MB / 31.00 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v14.18.0/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: AI-203.7717.56.2031.7678000
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
  npmGlobalPackages:
    *react-native*: Not Found

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `14.3.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `messaging`
- **Are you using `TypeScript`?**
  - `Y` & `4.5.5`

</p>
</details>

**Comment by mikehardy** [comment]
Have you searched the issues list for prior issues?
This seems to be one completely out of our control here as a react-native module
Yours looks exactly the same as the previous one unfortunately - https://github.com/invertase/react-native-firebase/issues?q=TOO_MANY_REGISTRATIONS

**Comment by johnf** [comment]
I did see the prior issue, I was looking for a way to catch the exception.
My bad I was using try catch as I didn't notice it returns a promise.
For anyone else trying to ignore this here is what I'm now ising.

```javascript
defaultAppMessaging.getToken()
  .then(saveToken)
  .catch((err) => {
    if (err.message.includes('TOO_MANY_REGISTRATIONS')) {
      console.debug('Too many registrations, clearing token');
      defaultAppMessaging.deleteToken();

      return;
    }

    console.debug('Error getting token', err);
    Sentry.captureMessage(`Get Token Error code: ${err.code} msg: ${err.message}`, {
      level: Sentry.Severity.Error,
      extra: {
        error: err,
      },
    });
  });
```
