### ISSUE TITLE
Internal error on cloud function call with emulators and anonymous users, auth related INVALID_REFERSH_TOKEN, iOS

### ISSUE THREAD

**Issue by hitsthings** [invertase/react-native-firebase#6045]
## Environment and context

I'm using version 12.7.5 at the moment on an old iPhone 6.

I expose firebase in a module after setting up emulators like so:

```ts
import auth from '@react-native-firebase/auth'
import functions from '@react-native-firebase/functions'
import DeviceInfo from 'react-native-device-info'

if (__DEV__) {
    const host = DeviceInfo.isEmulatorSync() ? 'localhost' : '192.168.20.22'
    auth().useEmulator(`http://${host}:9099`)
    functions().useFunctionsEmulator(`http://${host}:5001`)
}

export const firebase = {
    auth,
    functions
}
```

I later create an anonymous user for everyone with `firebase.auth().signInAnonymously()`

I also set up a cloud function call:

```ts
const _syncReceipt = firebase.functions().httpsCallable('user-syncReceipt')
```

The problem is when I attempt to call that function:

```ts
    try {
        const receipt = '...a string'
        if (receipt) {
            await _syncReceipt({ receipt })
            console.log('Receipt synced')
        }
    } catch (e: any) {
        logError(e)
    }
```

## Expected behavior

The functions emulator is called and "Receipt synced" is logged.

## Actual behavior

`_syncReceipt` throws and this error is logged in Xcode:

```
2022-02-02 11:43:01.446235+1100 In8[466:35781] [javascript] [Error: An internal error has occurred, print and inspect the error details for more information.], '\n', 'Error: An internal error has occurred, print and inspect the error details for more information.\nsyncReceipt$@/private/var/containers/Bundle/Application/B92C1D07-F2D5-4970-BE27-73E294E5F9A7/In8.app/main.jsbundle:211011:59\ntryCatch@/private/var/containers/Bundle/Application/B92C1D07-F2D5-4970-BE27-73E294E5F9A7/In8.app/main.jsbundle:23254:23\n(lots more useless stuff here)\n
```

## Debugging

Since that error is so unhelpful, I modified the FirebaseAuth pod a little to add an `NSLog` in `FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.m` on line 972 in `errorWithCode`:

```objc
   } else {
     // This is an internal error. Wrap it in an internal error.
     NSError *error = [NSError errorWithDomain:FIRAuthInternalErrorDomain
                                          code:code
                                      userInfo:userInfo];
       error = nil;
+      NSLog(@"Blammo %ld %@", (long)code, userInfo);
     return [self errorWithCode:FIRAuthInternalErrorCodeInternalError underlyingError:error];
  }
```
Now before the internal error is logged, this is in the logs:

```
2022-02-02 11:43:01.423181+1100 In8[466:38950] Blammo 3 {
    FIRAuthErrorUserInfoDeserializedResponseKey =     {
        code = 400;
        errors =         (
                        {
                domain = global;
                message = "INVALID_REFRESH_TOKEN";
                reason = invalid;
            }
        );
        message = "INVALID_REFRESH_TOKEN";
    };
}
```

I have tried deleting the app entirely (so a new anonymous user is created fresh), but it doesn't seem to fix anything. Nothing is logged by the firebase emulator at all.

If I manually go into the Auth emulator UI and create a user with email/password, then I log in as that user in iOS, I can call the function just fine. It's only anonymous users that throw.

**Comment by mikehardy** [comment]
I cannot offer help for old versions, it defeats the purpose of integrating bug fixes and new versions of the firebase-ios-sdk, please let me know if you can reproduce with current stable version here (and the current stable version of firebase-ios-sdk if you've overridden it, or the default if you have not)

If you can still reproduce, you may want to crank up debug output on the functions emulator itself and see what it's doing, as well as making sure that firebase-tools is fully up to date (you skipped your package.json here - which we explicitly ask for - so I can't really provide guidance, sorry)

**Comment by hitsthings** [comment]
Thanks, I'll look into reproducing with latest version.

Tangent: Just realized there are already issue templates on this repo. I was going to offer to create one. Somehow I was never prompted for the template and got the blank issue form. But I can't reproduce it. Might be that I wasn't logged in when I clicked New issue the first time? Anyway, sorry for not using the template.

**Comment by Genchou** [comment]
@mikehardy I am on 14.5.0 and I'm encountering the exact same issue, my situation is very similar to histhings : I call a function before authenticating the user and an the same error occurs (I modified `FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.m` the same way). It seems to only happen on physical iOS devices, both in release and debug builds.

**Comment by mikehardy** [comment]
Does this only happen on physical iOS devices, *against the auth emulator*, or does this happen on functions against real firebase backend as well? You might try latest version of firebase-tools (contains the emulator) if it reproduces against emulator.

Is there anything else going on with functions - app check integration maybe? :thinking: 

Seems like improving the error message is the only actionable thing I can pick out of here at the moment, the information provided does not yet quite rise to a https://stackoverflow.com/help/minimal-reproducible-example

**Comment by mikehardy** [comment]
If you want to make a skeleton project, this one does a reasonably good job https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh or this template https://github.com/invertase/react-native-firebase-authentication-example/ (which has emulator support for functions even in the scripts directory, but no shim for functions at the moment, though following the same shims pattern for functions should work - https://github.com/invertase/react-native-firebase-authentication-example/blob/main/template/src/shims/firebase-app-web.ts - or of course it should just work natively on android / ios with no shim since the shims are just for web)
