### ISSUE TITLE
[🐛] AppCheck's .activate() does not return a Promise on iOS

### ISSUE THREAD

**Issue by birdofpreyru** [invertase/react-native-firebase#6052]
## Issue

According to [the docs](https://rnfirebase.io/reference/app-check#activate) `.activate()` returns a Promise. It does so on Android, however it seems to return nothing on iOS. At least, I ended up with such code block in my app:
```js
import getFbAppCheck from '@react-native-firebase/app-check';

// Irrelevant code skipped here

  if (!initPromise) {
    initPromise = getFbAppCheck()
      .activate('', true)
      .catch((error) => {
        initPromise = null;
        throw error;
      });
  }

// Irrelevant code skipped here
```
which works fine on Android, but on iOS it crashes with the error:
> _Cannot read property 'catch' of undefined_

Sure, not a big trouble to workaround, as per docs it is not needed to call it on iOS at all, but still a bug, I believe.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hey @birdofpreyru :wave: - nice to see you over here. Sorry about this, I believe you are exactly right - I need to add the resolve/reject parameters to the ios native module method signature here and resolve it at the end so that the ios platform is consistent with android like it should be

https://github.com/invertase/react-native-firebase/blob/471b4be4035e0a9e02f22286492672a651bcaa6c/packages/app-check/ios/RNFBAppCheck/RNFBAppCheckModule.m#L39-L52

**Comment by mikehardy** [comment]
Ok - I've altered the e2e test to more thoroughly probe the return value there and now I've got the e2e test failing as it should be vs the current false positive for the ios platform. I'll have a fix shortly
