### ISSUE TITLE
[📚] Installing and Configuring React Native Firebase Crashlytics

### ISSUE THREAD

**Issue by FakhruddinAbdi** [invertase/react-native-firebase#6057]
## Documentation Feedback

I was struggling with crashlytic activation on my project for days, and after double-checking all the steps mentioned in the doc and especially in [this blog](https://invertase.io/blog/react-native-firebase-crashlytics-configuration) post by @mikehardy, I found out that the code for firebase.json, has missed `react-native` key

Instead of 

```
{
  "react-native": {
    "crashlytics_debug_enabled": true,
    "crashlytics_disable_auto_disabler": true,
    "crashlytics_auto_collection_enabled": true,
    "crashlytics_is_error_generation_on_js_crash_enabled": true,
    "crashlytics_javascript_exception_handler_chaining_enabled": true
  }
}
```
Its 
```
{
    "crashlytics_debug_enabled": true,
    "crashlytics_disable_auto_disabler": true,
    "crashlytics_auto_collection_enabled": true,
    "crashlytics_is_error_generation_on_js_crash_enabled": true,
    "crashlytics_javascript_exception_handler_chaining_enabled": true
}
```

As this blog post mentioned in the threads, it may misleads other developers.

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
oh my! Nice catch. Sorry about that. Hopefully with the notes in the log that show you how to at least *see* the keys that it considered it was not too bad but I can imagine that is pretty confusing.

I'll see about fixing the blog post shortly

**Comment by mikehardy** [comment]
Should be fixed now: https://github.com/invertase/invertase/commit/59ae828f369045c02a090c175f5d5186d279ca85
