### ISSUE TITLE
Isn't it possible to save date type object to firestore doc's field?

### ISSUE THREAD

**Issue by ruci06** [invertase/react-native-firebase#606]
Sorry for my lacked English.

### Issue

I tried to save object which has date type object for field.
for example
let data = {
    key1:'string',
    key2:new Date()
}
but when set handler is called, key2 saved as null on firestore.
Isn't it possible to save date type object to firestore doc's field?
Or is there anything I could check?

### Environment

1. Application Target Platform: 
Android

2. Development Operating System: 
macOS sierra

3. Build Tools: 
android studio 2

4. React Native version: 
0.48.3

5. RNFirebase Version: 
3.0.3

6. Firebase Module: 
firestore

**Comment by Salakar** [comment]
@ruci06 yes it is possible, you need to upgrade your RNFirebase version to the latest version: https://github.com/invertase/react-native-firebase/releases/tag/v3.1.0

There was an issue with dates that has been fixed in the newer versions.
