### ISSUE TITLE
[🐛] React Native Firebase onAuthStateChanged returns user after signOut

### ISSUE THREAD

**Issue by kvbalib** [invertase/react-native-firebase#6060]
## Issue

I'm struggling with signing out in my app. I'm using freshly installed managed Expo app with dev-client and @react-native-firebase/auth, all in their current versions. For the shared state i'm using Recoil. Sign in and persisting user session works just fine, the problem occurs when signing out. Here is my **AuthProvider.ts**

```
import React, { FC, Fragment, useEffect } from 'react';

import auth, { FirebaseAuthTypes } from '@react-native-firebase/auth';
import { useSetRecoilState } from 'recoil';

import { firebaseUser } from '../../../state/user/atoms/firebaseUser';

export const AuthProvider: FC = ({ children }) => {
  const setUser = useSetRecoilState(firebaseUser);
  const onAuthStateChanged = (user: FirebaseAuthTypes.User | null) => setUser(user);

  useEffect(() => {
    const subscriber = auth().onAuthStateChanged(onAuthStateChanged);

    return subscriber;
  }, []);

  return <Fragment children={children} />;
};
```

And the function I use to sign out:

```
const logout = () => async () => await auth().signOut()

<MainButton action={logout()} label={'Logout'} />
```

After sign in the **onAuthStateChanged** listener returns **user object**, but after hitting 'Logout' button it returns the user object again instead of **null** and the interface doesn't update. After hitting it again, console returns an error:

`[Unhandled promise rejection: Error: [auth/no-current-user] No user currently signed in.]`

**onAuthStateChanged** is not called second time, user state persists and the interface doesn't update.

The user state is cleared after restarting the app and the sign in works just fine again. The behaviour is similar when switching users (eg. from anonymous to signed in).

## Project Files

I'm using managed flow with expo-dev-client, so I've added firebase trough the app.json plugins.

`{
  ...
    "ios": {
      "bundleIdentifier": "<name>",
      "buildNumber": "900000",
      "googleServicesFile": "./GoogleService-Info.plist",
      "supportsTablet": true
    },
    "android": {
      "googleServicesFile": "./google-services.json",
      "versionCode": 900000,
      "package": "<name>",
    },
    ...
    "plugins": [
      "@react-native-firebase/app"
    ]
  }
}
`

The content of GoogleService-Info.plist and google-services.json is autogenerated by the Firebase console.

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `14.3.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y` & `4.3.5`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! 
You have omitted large portions of the issue template, which is unfortunate. It limits our ability to help. I'm not sure what platform even, or if it is both. Or if it is real devices or emulator/simulator.

https://stackoverflow.com/help/how-to-ask

> I'm struggling with signing out in my app. I'm using freshly installed managed Expo app with dev-client and @react-native-firebase/auth, all in their current versions. For the shared state i'm using Recoil

This makes things difficult as well - can you reduce the issue to a single App.js we can drop in a clean skeleton to eliminate other dependencies as sources of error?

https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by kvbalib** [comment]
Hi @mikehardy , thanks for the reply.

This is freshly initialized app with Expo, nothing really special to it yet, as login functionality was the first thing I've worked on. All dependencies are installed using expo install, so they're current versions. Here's my package.json dependency list:

```
"dependencies": {
    "@expo/vector-icons": "^12.0.0",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-firebase/analytics": "^14.3.1",
    "@react-native-firebase/app": "^14.3.1",
    "@react-native-firebase/auth": "^14.3.1",
    "@react-native-firebase/crashlytics": "^14.3.1",
    "@react-native-firebase/database": "^14.3.1",
    "@react-native-firebase/in-app-messaging": "^14.3.1",
    "@react-native-firebase/installations": "^14.3.1",
    "@react-native-firebase/messaging": "^14.3.1",
    "@react-native-firebase/remote-config": "^14.3.1",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "axios": "^0.25.0",
    "expo": "~44.0.0",
    "expo-asset": "~8.4.4",
    "expo-constants": "~13.0.0",
    "expo-dev-client": "~0.8.4",
    "expo-font": "~10.0.4",
    "expo-linking": "~3.0.0",
    "expo-splash-screen": "~0.14.0",
    "expo-status-bar": "~1.2.0",
    "expo-web-browser": "~10.1.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-hook-form": "^7.26.1",
    "react-native": "0.64.3",
    "react-native-paper": "^4.11.2",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-web": "0.17.1",
    "recoil": "^0.6.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.64.12",
    "jest": "^26.6.3",
    "jest-expo": "~44.0.1",
    "react-test-renderer": "17.0.1",
    "typescript": "~4.3.5"
  },
```

Here's my App.tsx. As you can see the AuthProvider that I've posted in my initial report is high in the component tree. Along the way is a simple login form, which works just fine. Outside the form, I've added really simple Logout button (also in my initial report) to test if it works and it does not. The rest of the code seems irrelevant as I did not change much in the app initialized by expo init - it's just login form, and logout button. Signing in with password makes the onAuthStateChanged listener return user object properly - user object gets saved to the Recoil state and updates UI - showing user display name. On the other hand, clicking Logout button makes the onAuthStateChanged listener return the same user object again, instead of null.

```
import 'expo-dev-client';
import { StatusBar } from 'expo-status-bar';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { RecoilRoot } from 'recoil';

import useCachedResources from './src/hooks/useCachedResources';
import useColorScheme from './src/hooks/useColorScheme';
import Navigation from './src/navigation';
import { PaperTheme } from './src/ui/_functional/PaperTheme';
import { AuthProvider } from './src/ui/_functional/AuthProvider';
import { ErrorBoundary } from './src/ui/_functional/ErrorBoundary';

export default function App() {
  const isLoadingComplete = useCachedResources();
  const colorScheme = useColorScheme();

  if (!isLoadingComplete) return null;

  return (
    <RecoilRoot>
      <ErrorBoundary>
        <AuthProvider>
          <PaperTheme>
            <SafeAreaProvider>
              <Navigation colorScheme={colorScheme} />
              <StatusBar />
            </SafeAreaProvider>
          </PaperTheme>
        </AuthProvider>
      </ErrorBoundary>
    </RecoilRoot>
  );
}
```

I've tested it on iOS simulator iPhone 13 and a device - iPhone 12 Pro Max.

**Comment by mikehardy** [comment]
I have seen problems related to persistence libraries before, I was asking for a minimal App.js on purpose. The word "minimal" is prescriptive - I really need to know this happens in a minimal reproduction. I do not have the desire to repeat the discovery made, for example, that incorrect use of redux outside of this module's control can affect how listeners are working.

**Comment by kvbalib** [comment]
Ok, I will try to simplify the app to one file later.

**Comment by kvbalib** [comment]
Ok. I've managed to fix the issue, the problem was Recoil, apparently the two libraries don't work well together. I've rewritten it using context and it works just fine.

**Comment by mikehardy** [comment]
What a pain in the ___ ! I'm sorry that happened, you can understand now my insistence on stripping the dependencies down. I'll add "recoil" to the list (which includes "redux" also) of libraries that have bizarre interactions. Glad you have it sorted out!

**Comment by johncblandii** [comment]
@kvbalib what was your issue?

**Comment by kvbalib** [comment]
@johncblandii the issue was caused by Recoil. Instead of syncing the user with local state (useState), I was using global (useSetRecoilState) state and apparently those 2 libraries don’t work well together. This was causing onUserStateChanged to return user object even after signing out.

**Comment by Raller** [comment]
Are there any news regarding this error? I am using recoil to store the user when logging in and I experience the same problem with the user not being null after signout.
