### ISSUE TITLE
[🐛] 🔥Expo Managed Config Plugin for Crashlytics iOS 

### ISSUE THREAD

**Issue by adamwlev** [invertase/react-native-firebase#6063]
## Issue
I have a managed Expo App and am trying to setup Crashlytics for it using the config plugin. I am testing the setup on iOS. What seems to be happening is that firebase is saying it is not getting the info that it needs to process the crashes. It saying this:

Upload missing required dSYMs
<img width="1016" alt="Screen Shot 2022-02-10 at 3 42 26 PM" src="https://user-images.githubusercontent.com/6889910/153515635-f1764af2-5dbf-4113-9aba-31151f90f030.png">

Since I am using the Managed setup with EAS Build, I can't follow the instructions they give to resolve it by uploading since I do not have the files they say to look for on my machine. [These](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios&authuser=2) are the steps that they say to do to resolve the issue.
 

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/app": "^14.3.1",
"@react-native-firebase/crashlytics": "^14.3.1",
"@react-native-firebase/perf": "^14.3.1",
```

#### `firebase.json` for react-native-firebase v6:

```json
{
    "crashlytics_debug_enabled": true,
    "crashlytics_disable_auto_disabler": true,
    "crashlytics_auto_collection_enabled": true,
    "crashlytics_is_error_generation_on_js_crash_enabled": true,
    "crashlytics_javascript_exception_handler_chaining_enabled": true
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x ] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
zsh: command not found: react-native
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `14.3.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `crashlytics`
- **Are you using `TypeScript`?**
  - `No` & `N/A`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I'm not sure this is a tractable problem for this module, inside this repository.

But more importantly, those symbols will have no value for you anyway. They won't be the correct symbols and won't map to anything.

Why? Bitcode.

For details: here's an answer I wrote on stackoverflow that uses fastlane to download dSYMS and upload them, you can then use the dSYM uploader for firebase to upload them

https://stackoverflow.com/questions/54577202/how-to-run-upload-symbols-to-upload-dsyms-as-a-part-of-xcode-build-process/55796619#55796619
