### ISSUE TITLE
auth().signOut failed for non-default firebase app in IOS

### ISSUE THREAD

**Issue by weiqgu** [invertase/react-native-firebase#607]
### Issue

My app connects to a non-default firebase app, after signin successfully, when I tried to do call signOut() in auth module, I am getting the error : "No user currently signed in.".

I looked at the source code of the /ios/RNFirebase/auth/RNFirebaseAuth.m, I think there is a bug in signOut method at line 107:

105    FIRApp *firApp = [FIRApp appNamed:appName];
106
_107   FIRUser *user = [FIRAuth auth].currentUser;_

It doesn't get the auth for the specific app but the default one.  I think it should be:

FIRUser *user = [FIRAuth authWithApp:firApp].currentUser;

### Environment

1. Application Target Platform:  IOS

2. Development Operating System: 

3. Build Tools: 

4. React Native version: 0.48

5. RNFirebase Version: 3.0.6

6. Firebase Module: Auth

**Comment by Salakar** [comment]
Thanks for the report, you're correct, have pushed a fix for this, will land in next version.

**Comment by adirzoari** [comment]
@Salakar  @weiqgu  I still get this issue when I sign in with phone auth and then sign out and then again try to login with phone.

**Comment by ramon90** [comment]
I get this when i sign in with custom token
