### ISSUE TITLE
[🐛] Push message alerts not showing on Android 12

### ISSUE THREAD

**Issue by sadikyalcin** [invertase/react-native-firebase#6075]
## Issue

Current prod application stopped receiving messages on devices running Android 12. `onMessage` handler still works but no notifications alerts popping up. I believe messages are received but banners not showing. So I'm not really sure if it's a device specific issue or a firebase issue.

I plugged a phone in and I did actually receive the notification but no alerts. 

```
@setBackgroundMessageHandler()  {"collapseKey": "...", "data": {}, "from": "440390820819", "messageId": "0:1644947798470536%67fbdd7a67fbdd7a", "notification": {"android": {}, "body": "This is the body text", "title": "Notification title"}, "sentTime": 1644947798450, "ttl": 2419200}
```

The notifications aren't blocked on the device it self and all banners from other applications do appear.

I've tried 2 apps using rn/firebase and same issue on both apps. Unfortunately, I don't have another Android 12 phone to test at the moment but just writing it up here just incase someone has an idea / or the same issue.

```
"@react-native-firebase/analytics": "^7.6.8",
"@react-native-firebase/app": "^8.4.6",
"@react-native-firebase/messaging": "^7.9.1",
```

Are there any new params / config needed for Android 12+? Android 11 and below work perfectly fine. I don't feel the need to add any project files as it looks like a generic issue but will do if required.

**Comment by mikehardy** [comment]
Hi there!
No effort spent on these versions:

```
"@react-native-firebase/analytics": "^7.6.8",
"@react-native-firebase/app": "^8.4.6",
"@react-native-firebase/messaging": "^7.9.1",
```

...is worthwhile. Those were released in 2020 prior to the release of Android 11, much less 12

You should update to the current stable version (which will pull in the current stable version of firebase-android-sdk, which should work with Android 12), )then if it continues happening, we can reopen

This may help, as it describes how to handle the breaking changes etc, philosophically: https://invertase.io/blog/react-native-firebase-versioning
