### ISSUE TITLE
[🐛] onSnapshot callback is incorrectly typed

### ISSUE THREAD

**Issue by Shywim** [invertase/react-native-firebase#6077]
## Issue

`onSnapshot` callback is incorrectly typed: it can receive `null` as it first argument and a second argument [if an error happens](https://github.com/invertase/react-native-firebase/blob/d9cf9c3ea364001d12de0e26693bc9e4e3e2c859/packages/firestore/lib/FirestoreDocumentReference.js#L145), but currently it is typed only to be able to [receive an existing `DocumentSnapshot`](https://github.com/invertase/react-native-firebase/blob/d9cf9c3ea364001d12de0e26693bc9e4e3e2c859/packages/firestore/lib/index.d.ts#L292-L409).

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/analytics": "^12.9.0",
    "@react-native-firebase/app": "^12.9.3",
    "@react-native-firebase/auth": "^12.7.3",
    "@react-native-firebase/crashlytics": "^13.0.1",
    "@react-native-firebase/firestore": "^12.9.3",
    "@react-native-firebase/remote-config": "^13.0.1",
```

#### `firebase.json` for react-native-firebase v6:

```json
{
    "react-native": {
        "crashlytics_debug_enabled": true
    }
  }
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `12.9.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `Firestore`
- **Are you using `TypeScript`?**
  - `Y` & `4.3.5`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there!

Please do not open issues on out of date software:

```
    "@react-native-firebase/analytics": "^12.9.0",
    "@react-native-firebase/app": "^12.9.3",
    "@react-native-firebase/auth": "^12.7.3",
    "@react-native-firebase/crashlytics": "^13.0.1",
    "@react-native-firebase/firestore": "^12.9.3",
    "@react-native-firebase/remote-config": "^13.0.1",
```

Update to current stable, then re-verify it's happening, as we do fix types on occasion and may have already fixed this.

If it continues to be an incorrect type, the path forward is to compare the v8 version of firebase-js-sdk APIs here to see how they handle it, and to the extent possible alter our index.d.ts file here in a PR to have correct types that match the firebase-js-sdk API so we maintain compatibility

**Comment by Ronald3217** [comment]
update to version 14.5.0, just implemented firebase and the real-time database function (onSnapshot) works perfectly

using the latest version of the packages

"@react-native-firebase/app": "14.5.0",
"@react-native-firebase/firestore": "14.5.0",

**Comment by mikehardy** [comment]
@Ronald3217 are you sure that is what @Shywim's issue was about? The issue seems to be about typescript typing, not functionality - although I'm always glad to hear things are working!

**Comment by Ronald3217** [comment]
> @Ronald3217 are you sure that is what @Shywim's issue was about? The issue seems to be about typescript typing, not functionality - although I'm always glad to hear things are working!

Sorry, I didn't understand Shywim's question.
