### ISSUE TITLE
[📚] Performance monitoring docs should have info banner about automatic monitoring

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [invertase/react-native-firebase#6082]
## Documentation Feedback
I think it would be nice if following pages had a notice about **automatic** http monitoring that's performed by firebase:

https://rnfirebase.io/perf/axios-integration
https://rnfirebase.io/perf/ky-integration

As soon as I installed the firebase, it started picking up without even applying middlewares. I spent some time applying axios middleware, and at the end it turned out to be unnecessary.

**Comment by mikehardy** [comment]
Hi there - perhaps on the two pages you link, there could be a notice that Firebase Performance will log HTTP requests by default but you may integrate more deeply with request/response interceptors, emphasizing this point from the pages linked: **"exposing metadata which can be hooked"**

That is, the point of those integrations is that you include much more detailed information from Axios (or KY) than the default logs, if you like. But it is not necessary.

Does that sound right? Either way - feel free to propose a PR, if it looks good, we can merge it

**Comment by OrkhanAlikhanov** [comment]
Hey @mikehardy while firebase performance http metric works for iOS out of the box, for android it does not work out of the box because firebase will auto track okhttp v3.x.x and RN uses v4

From [firebase docs](https://firebase.google.com/docs/perf-mon/network-traces?platform=android#:~:text=Performance%20Monitoring%20automatically%20collects%20metrics,specifically%20HTTP%20client%20v3.x.x):
>Performance Monitoring automatically collects metrics for network requests that use the following networking libraries:
>
>[OkHttp3](https://square.github.io/okhttp/), specifically HTTP client v3.x.x

From [react native blog for v0.65](https://reactnative.dev/blog/2021/08/17/version-065)
>Upgraded OkHttp from v3 to v4.9.1

**Comment by mikehardy** [comment]
logged enhancement request https://github.com/firebase/firebase-android-sdk/issues/3465 - perhaps they already support it somehow and their docs just need an update, or perhaps they have some development effort to do before it works. Can you confirm you tested it on android with a react-native that uses OkHTTP v4+ and it did not auto trace?

**Comment by OrkhanAlikhanov** [comment]
I confirm from production code that it does not auto-trace. In fact I checked out the docs because of that. iOS on the other hand traces as expected

**Comment by OrkhanAlikhanov** [comment]
Hello @mikehardy. It seems we had forgotten one step for android to make automatic network tracking work, and that was "applying gradle plugin". After fixing that, it started to collect http requests. Probably okhttp4 under the hood uses something that firebase already auto-traces. I'm sorry for misreporting

Also android does not trace requests made by `<Image src={url} />` tag, but iOS does trace them.

**Comment by mikehardy** [comment]
@OrkhanAlikhanov - interesting findings! Could you post the same on the related firebase-android-sdk ticket if you were not already in the process of doing so?
