### ISSUE TITLE
Notification not displaying when app is in quit state (swiped away from recents) in android

### ISSUE THREAD

**Issue by RejoV** [invertase/react-native-firebase#6085]
Following are the dependencies used in my project:
    "@react-native-firebase/app": "14.5.0",
    "@react-native-firebase/messaging": "14.5.0",
    "react": "17.0.2",
    "react-native": "0.67.2",
I've used the following code as mentioned in documentation in index.js
messaging().setBackgroundMessageHandler(async remoteMessage => {
    console.log('Message handled in the background!', remoteMessage);
});

When app is in foreground and background it works fine. Issue arises when app is swiped away from recent apps. I've even removed battery optimisation and gave permission to run in background from settings. 
Thanks in advance

**Comment by mikehardy** [comment]
Hi there - I think this is the case where you have told the operating system "stop running this app", and basically it believed you.
You haven't mentioned anything about the device in question or the JSON you are sending (remove the device token of course but please post the raw JSON you are sending to the FCM REST API end point so no one has to make assumptions...) or what you see in `adb logcat` (unfiltered) when the device receives the FCM  (https://stackoverflow.com/help/how-to-ask)

**Comment by RejoV** [comment]
Hi,
 I've sent fcm notification via firebase console.
{"displayName":"Test","state":"RUNNING","onStart":{},"notificationOptions":{"messageText":"Testing","messageTitle":"Test","hasSound":false,"imageUrl":"","expiryTime":"2419200s","registrationIds":["xxxx"]},"dataBundle":{}} 
while running `adb logcat` notification logs are not coming when app is in swiped away state, but notification logs are being shown when the app is in foreground or background. 
Thanks you in advance.

**Comment by jinshin1013** [comment]
I can also reproduce this issue. After the app is completely closed and wait for few minutes `.setBackgroundMessageHandler` is not triggered when the notification is received. This only happens on Android 11 and 12. I've tested on Android 7 device and worked just fine.

**Comment by mikehardy** [comment]
https://github.com/invertase/react-native-firebase/issues/6085#issuecomment-1044468577

`adb logcat` results would be quite interesting. Also note this could be device-specific: https://dontkillmyapp.com/ - so any details from your testing should be as precise as you can be about controlling the experiment / explaining experimental conditions

**Comment by ederwan** [comment]
Hello, there is no news on this topic, but I have the same problem.
I previously use https://github.com/zo0r/react-native-push-notification and i didn't have any issues but this lib is no longer maintain. 

Do you have any solution ?

**Comment by mikehardy** [comment]
notifee.app
