### ISSUE TITLE
Error: firebase.auth().linkWithCredential(credential) is not a function

### ISSUE THREAD

**Issue by wbattel4607** [invertase/react-native-firebase#609]
### Issue

I am migrating my phone auth setup from v2.1.3 (we used one of the temporary solutions before v3 rolled out) to v3.1.0. I am able to use firebase.auth().signInWithCredential(credential) perfectly fine but now I'm trying to setup account linking with our other auth provider, Facebook.

I've got both Phone and Facebook authentication working great- but for some reason I keep getting `_Firebase2.default.auth(...).linkWithCredential is not a function` when I try to link.

I've been following the [guide](https://rnfirebase.io/docs/v3.1.*/auth/phone-auth#Example) which confirms that linkWithCredential is something I can do... so I'm not sure what's up.

This is what I'm specifically trying. I know the setup works because I'm able to do everything else except linking.
`firebase.auth().linkWithCredential(firebase.auth.PhoneAuthProvider.credential(this.state.verificationId, this.state.code))`

Any ideas? Thanks :)

### Environment

1. Application Target Platform: Both (only testing on iOS right now)

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode 9, iOS 11.1

4. React Native version: 0.50.3

5. RNFirebase Version: 3.1.0

6. Firebase Module: Authentication

**Comment by wbattel4607** [comment]
Looks like it was just a typo in the docs. The correct way to link is `user.linkWithCredential` not `firebase.auth().linkWithCredential`

**Comment by Salakar** [comment]
Re-opened so we can address docs issue.

**Comment by wbattel4607** [comment]
Okay. I also have an existing PR for another small docs issue

https://github.com/invertase/react-native-firebase-docs/pull/12

**Comment by chrisbianca** [comment]
I've just updated the documentation with the correct usage
