### ISSUE TITLE
[🐛] NPM package '@react-native-firebase/admob' depends on '@react-native-firebase/app' v11.5.0 but found v14.3.0, this might cause build issues or runtime crashes.

### ISSUE THREAD

**Issue by pushpender-singh-ap** [invertase/react-native-firebase#6098]
NPM LINK:- [CLICK ON ME](https://www.npmjs.com/package/@react-native-firebase/admob)

<img width="744" alt="image" src="https://user-images.githubusercontent.com/73298854/155845204-137a8900-3180-41ac-93ff-744c962730f3.png">

Please update @react-native-firebase/admob version not available on NPM v14.3.0

**Comment by mikehardy** [comment]
Hi there! Google removed admob completely from firebase, so it is no longer a firebase-related project and will receive no further updates here. We have split it out to a separate project, and you should convert to using it: https://github.com/invertase/react-native-google-mobile-ads
