### ISSUE TITLE
[🐛] OTP Verification failure issue in both iOS and Android

### ISSUE THREAD

**Issue by chandrahasan1** [invertase/react-native-firebase#6109]
## Issue

`[auth/invalid-verification-code] The sms verification code used to create the phone auth credential is invalid. Please resend the verification code sms and be sure use the verification code provided by the user.
`
We are getting the above error for a handful of devices, in both iOS and Android. The OTP entered is correct and without any delay, but OTP is being rejected with the same error always. 

It is only happening for a few users and not all of them. Please advice.

Thank you.
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
“@react-native-firebase/app”: “^14.1.0",
“@react-native-firebase/auth”: “^14.1.0",
“react”: “17.0.2",
“react-native”: “0.66.3"
```
</details>

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 14.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Auth`
- **Are you using `TypeScript`?**
  - `No`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Without isolating the actual devices it is happening on and reproducing it with some information from the logs on device, I'm not sure what help I can offer.

**Comment by chandrahasan1** [comment]
Hi, @mikehardy thanks for the response. The issue is happening in a multitude of devices ranging from iOS to Android and this is been there for the last 10 months or more. I wonder why nobody has complained about this yet.

Please let me know what information I can log and share with you. Thank you.

**Comment by mikehardy** [comment]
Log any information you can, if you have a reproduction and it's on Android, do adb logcat unfiltered and read it really really closely , share what you find. It is suspicious that this is so reproducible but no one else notices, that argues for some project specific thing, from a change maybe 10 months ago in your project?

**Comment by chandrahasan1** [comment]
Hi Mike, we believe this issue is from our side. We have released a patch with fix and one customer has already confirmed to be working.

Please tell me if there is a way to undo a `flagged user` of suspicious activity due to consuming many OTPs in small time period in Firebase Console.

Appreciate your time and support.

Thank you.

Thanks,
Chandu.

**Comment by mikehardy** [comment]
I don't believe there is anything you actively do, I believe there is a cooldown period on the server side in firebase's closed cloud anti-fraud business logic and that will expire with no more action - either possible or necessary - on anyone's part. So I think all you can do is wait, but you shouldn't have to wait much longer, I think it is on the order of .5-2 hours ?
