### ISSUE TITLE
Passing state to email actions?

### ISSUE THREAD

**Issue by Stas-Buzunko** [invertase/react-native-firebase#611]
https://firebase.google.com/docs/auth/ios/passing-state-in-email-actions
https://firebase.google.com/docs/auth/android/passing-state-in-email-actions

Is it possible in react-native-firebase?

**Comment by Salakar** [comment]
@Stas-Buzunko thanks for flagging this, currently it's not supported but it may be something we can potentially support, we'll investigate and get back to you.

**Comment by Stas-Buzunko** [comment]
@Salakar thanks for a quick response! when will you know whether you will support it and if you decide to support it, how long do you think it will take to implement?

I just want to know whether I should count on this feature in my current project :)

**Comment by Salakar** [comment]
@Stas-Buzunko have replied to you on discord, but for reference here: We'll get this in as part of v3.2, potentially an earlier patch release if time permits.

**Comment by chrisbianca** [comment]
I've just added this functionality which will be released as part of v3.2.0: https://github.com/invertase/react-native-firebase/commit/a03c445e0c4a5391fd203dd3cca6b40f94d05c68
