### ISSUE TITLE
[react-native-firebase/messaging] Remote notifications on iOS do not trigger setBackgroundMessageHandler or onBackgroundEvent

### ISSUE THREAD

**Issue by thehellmaker** [invertase/react-native-firebase#6123]
Remote notification sent to ios via APNS [not FCM] which is registered using var apnsToken: string | null = await messaging().getAPNSToken() is not triggering any firebase events

Steps to reproduce
1. register using var apnsToken: string | null = await messaging().getAPNSToken()
2. Exit / Close the app
3. send a notification using apnsToken
4. Notification is recieved on the ios device
5. Tap on the notification and none of the life cycle methods are triggered
notifee.onBackgroundEvent not called
messaging().setBackgroundMessageHandler not called
messaging().getInitialNotification( has remote message as null
messaging().onNotificationOpenedApp( not called

Usecase when the notification is tapped we want to take them to a call screen where the user can pick up the call from a video door bell

**Comment by mikehardy** [comment]
I don't believe that Firebase will respond to non-Firebase messages
Firebase includes some special notification / JSON content keys that let it know it should process things.
You should consult the upstream documentation (firebase-ios-sdk / general firebase messaging docs) to see if your use case is actually expected to work per official docs, I assert it is not, but the docs will be the authoritative verification there
