### ISSUE TITLE
[🐛] getInitialNotification returns old notification data on Android

### ISSUE THREAD

**Issue by soutua** [invertase/react-native-firebase#6130]
## Issue

On Android the `getInitialNotification` can return previously opened notification's data, instead of the one that the user opened most recently.

Steps to reproduce:

1. Kill the app if it's currently in the background
2. Send a notification containing data A
3. Open the notification and check that it contains data A
4. Press home to leave the app (note: important to leave with the home button, not with the back button)
5. Send a notification with data B
6. Open the notification and check that it contains data B
7. Press back to leave the app (note: important to leave with the back button, not with the home button)
8. Send a third notification with data C
9. Open the notification

Expected result is that you would get the third notification's data C when calling `getInitialNotification`, but instead you get the second notification's data B.

I was reading the library's code and I think the issue is in this functionality where the notification data is stored in the `onNewIntent` handler and then returned in the `getInitialNotification`: https://github.com/invertase/react-native-firebase/blob/514e6bd51e7624a6403dda706f4e5b65cee63422/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java#L61

The data gets set to `null` after it's returned but the problem is that in that above reproduction sequence in the step 6 the app returns from the background in which case the `onNotificationOpenedApp` callback gets triggered in which case we don't call the `getInitialNotification` since we get the correct notification data already in the callback parameters so in that case the data is left in place.

Note that it is possible to workaround this issue by doing an "unnecessary" `getInitialNotification` call inside that `onNotificationOpenedApp` callback, which will then set the stored notification value to `null` and the stale data doesn't exist anymore in the step 9. 

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `14.5.0`
- **`Firebase` module(s) you're using that has the issue:**
  - ``
- **Are you using `TypeScript`?**
  - ``

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by LA-Johan** [comment]
@soutua I think I'm facing the same issue. Can you expand on what your workaround is? Would you call `getInitialNotification()` after `log("onNotificationOpenedApp")` in my code here?

```
const useRegisterNotificationActionHandlers = (): void => {
  const linkTo = useLinkTo()
  useEffect(() => {
    messaging()
      .getInitialNotification()
      .then(
        message => {
          if (message == null) return
          log("getInitialNotification")
          handleRemoteMessage(message, linkTo)
        },
        e => logError("Error loading initial notification", e)
      )
    return messaging().onNotificationOpenedApp(remoteMessage => {
      log("onNotificationOpenedApp")
      handleRemoteMessage(remoteMessage, linkTo)
    })
  }, [linkTo])
}
```
