### ISSUE TITLE
[🐛] rn-firebase crashes in a monorepo

### ISSUE THREAD

**Issue by kickbk** [invertase/react-native-firebase#6133]
When running any calls with `auth()` in a expo custom dev client monorepo, the app responds by showing the splash screen and is stuck. So it's not really a crash, but a strange behavior.

I tried to debug this, and I cannot figure this one out really so I created a simple monorepo with the least amount of dependencies to demonstrate.

Instructions for installation in the repo: https://github.com/kickbk/rn-firebase-monorepo

This is what I am seeing:

https://user-images.githubusercontent.com/31323376/158886564-c1988cd2-85d4-4c47-9ae1-54dc3212a2b5.mp4

**Comment by mikehardy** [comment]
before I look, what's `adb logcat` say? What do log statements say, as you reach into node_modules and add them while you trace control flow to native?

**Comment by mikehardy** [comment]
Also, the monorepo is useful, but execution environment is important: version of host OS, node, what version of android, what device (or emulator) you're using. All the stuff you would want if you were a busy colleague and someone came to you with a problem:

https://stackoverflow.com/help/how-to-ask

**Comment by mikehardy** [comment]
Last thought - would be curious to see all those deps but not the expo case. For instance something like https://github.com/invertase/react-native-firebase-authentication-example (works out of the box, can be in a monorepo just fine)

**Comment by kickbk** [comment]
I was testing on ios simulator (although I also tested with a real device and got the same behavior)
The simulator logs show nothing, which is something I believe I mentioned somewhere. I don't think there's an actual crash or an error. It just switches to the splash screen and gets stuck.
I tried to debug by placing console logs before and after the call to `auth().verifyPhoneNumber`. It shows the log before the call but never the log after.
As for my env:
MacOS BigSur 11.6.5
ios simulator (iPhone 13)
Also same with real device iPhone 6s plus with os v. 14.6
If you need any other data, please let me know.

After you mentioned Android, I built it on android and it actually sort of worked. It did not switch to the splash screen. Notice I have this function:
```js
<Button
  title="AUTH"
  onPress={() => {
    auth()
      .verifyPhoneNumber('+15555555555')
      .on('state_changed', (phoneAuthSnapshot) => {
        console.log('Snapshot state: ', phoneAuthSnapshot.state);
      })
      .catch((error) => console.log('error', error));
  }}
/>
```
With android I see the logs! It shows
Snapshot state:  sent
Snapshot state:  timeout

I'll try to see if I can test with your example by adding those deps.

**Comment by mikehardy** [comment]
make sure to test my example *before* adding those deps.
Surprising the Xcode logs of the app running showed nothing, there should have been at least a little bit of firebase-related chatter in there.
On both platforms native you can add logging code in to our module's code before it calls down to firebase-ios-sdk/firebase-android-sdk (and logging on callbacks etc) to see where it hangs as well, could be enlightening or a dead end

> Have I missed something in my setup perhaps?

Well, for phone auth there's quite a bit of back-end stuff I think for app verification and recaptcha etc and you may have missed something in GCP control panel, an entitlement or something. The possibilities for missing something / misconfiguring are nearly endless in a system as sprawling as this unfortunately.

**Comment by kickbk** [comment]
I was able to get xcode logs by building the app with xcode vs eas and found the issue on ios:
```js
2022-03-18 09:45:35.426592-0700 easmonorepoappwithdevclient[22958:1492563] [native] Exception 'Please register custom URL scheme 'app-1-506433008776-ios-xxxxxx' in the app's Info.plist file.' was thrown while invoking verifyPhoneNumber on target RNFBAuthModule with params (
...
```
Sam as https://github.com/invertase/react-native-firebase/issues/2346

I'm gonna try to find out how to set this up with expo config and if I do, I'll post my findings. It may be useful to mention it somewhere in the [Expo setup](https://rnfirebase.io/#expo)

**Comment by mikehardy** [comment]
> It may be useful to mention it somewhere in the [Expo setup](https://rnfirebase.io/#expo)

Hit that pencil button on the top of the page :-), I don't use Expo personally so we rely 100% on Expo folks to help each other get it working + avoid landmines since I can't fix or teach about what I don't use. Happy to collaborate + merge PRs tho

**Comment by kickbk** [comment]
I was finally able to make things work with Expo, authentication, and dynamic links, using a managed expo custom client. There's really quite a lot going on, so instead of suggesting edits to your original document, I wrote a two part post about it: https://kickbk.medium.com/expo-react-native-firebase-f99651b7d09

**Comment by mikehardy** [comment]
I like the idea of a medium post, but if there is something specific missing in the *actual* module documentation it really would be great to have it fixed...
