### ISSUE TITLE
[🐛] setUserProperties does not display on Debug View only Android

### ISSUE THREAD

**Issue by tranhuuthinhit** [invertase/react-native-firebase#6142]
A pretty simple one, I have a call to use the **setUserProperties** method, but I don't see the user property show and update on Debug View, only on Android. But all events still display on Debug view.

The user property only updates when I kill and restart the app again.

![[Tux, the Linux mascot](https://i.ibb.co/cb1Xkyr/Screen-Shot-2022-03-21-at-17-00-05.png)](https://i.ibb.co/cb1Xkyr/Screen-Shot-2022-03-21-at-17-00-05.png)

#### `JS Handle`
```
async setUserProperties(isReset = false) {
    const { language } = store.getState().app
    const { account } = store.getState().account

    const params = {
      ui_language: language,
      membership: `${CONFIGS.TENANT_ID}-anonymous`,
      build_type: CONFIGS.BUILD_TYPE
    }

    if (account && account.profile !== undefined) {
      const subscriptionPlanInfo = account.profile.subscription_plan_info
      params.membership = `${CONFIGS.TENANT_ID}-free`

      if (subscriptionPlanInfo && subscriptionPlanInfo.slug) {
        params.membership = `${CONFIGS.TENANT_ID}-${subscriptionPlanInfo.slug}`
      }
    }

    try {
      console.log('setUserProperties', params)
      firebase.analytics().setUserProperties(params)

      if (isReset) {
        firebase.analytics().resetAnalyticsData()
        firebase.analytics().setUserProperties(params)
      }
    } catch (error) {
      console.log('setUserProperties error', error)
    }
  }
```

#### `package.json`:

```json
  "@react-native-firebase/admob": "11.5.0",
  "@react-native-firebase/analytics": "11.5.0",
  "@react-native-firebase/app": "11.5.0",
  "@react-native-firebase/crashlytics": "11.5.0",
  "@react-native-firebase/perf": "11.5.0",
  "react": "17.0.1",
  "react-native": "0.64.2",
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "analytics_auto_collection_enabled": false
  }
}
```

I'm using autolinking on Android.

**Comment by mikehardy** [comment]
Hi there! These versions are incredibly old, we can't spend time working on them for troubleshooting:

```
 "@react-native-firebase/admob": "11.5.0",
  "@react-native-firebase/analytics": "11.5.0",
  "@react-native-firebase/app": "11.5.0",
  "@react-native-firebase/crashlytics": "11.5.0",
  "@react-native-firebase/perf": "11.5.0",
```

I understand you are likely on those versions because it was the last version with admob. Have no fear! We have a valid + living admob replacement package now, so you should switch to https://github.com/invertase/react-native-google-mobile-ads, then you can get everything here up to date, and if you can still reproduce, please let us know

**Comment by mikehardy** [comment]
For the changes needed here while updating across major versions (they should be small?) you can read how we handle versioning and how to upgrade here https://invertase.io/blog/react-native-firebase-versioning

**Comment by tranhuuthinhit** [comment]
> For the changes needed here while updating across major versions (they should be small?) you can read how we handle versioning and how to upgrade here https://invertase.io/blog/react-native-firebase-versioning

Thank you!

**Comment by tranhuuthinhit** [comment]
Hi @mikehardy,
I'm trying to update the latest version and this issue is still reproduced. The event is still displayed, but I don't see the user property display on debug view (only on android)

I have added an event after set the user property, and then this event is displayed on debug view.

I using this command to enable debug view on Android

```
adb shell setprop debug.firebase.analytics.app <package>
```

![https://i.ibb.co/hCSGNQD/Screen-Shot-2022-03-21-at-23-56-04.png](https://i.ibb.co/hCSGNQD/Screen-Shot-2022-03-21-at-23-56-04.png)

#### JS Code

```js
setUserProperties() {
    const { language } = store.getState().app
    const { account } = store.getState().account

    const params = {
      ui_language: language,
      membership: `${CONFIGS.TENANT_ID}-anonymous`,
      build_type: CONFIGS.BUILD_TYPE
    }

    if (account && account.profile !== undefined) {
      const subscriptionPlanInfo = account.profile.subscription_plan_info
      params.membership = `${CONFIGS.TENANT_ID}-free`

      if (subscriptionPlanInfo && subscriptionPlanInfo.slug) {
        params.membership = `${CONFIGS.TENANT_ID}-${subscriptionPlanInfo.slug}`
      }
    }

    try {
      analytics().resetAnalyticsData()

      console.log('setUserProperties', params)

      analytics().setUserProperty('ui_language', params.ui_language)
      analytics().setUserProperty('membership', params.membership)
      analytics().setUserProperty('build_type', params.build_type)

      this.logEvent('setUserProperties')
    } catch (error) {
      console.log('setUserProperties error', error)
    }
  }
```

####
```json
    "@react-native-firebase/analytics": "14.5.1",
    "@react-native-firebase/app": "14.5.1",
    "@react-native-firebase/crashlytics": "14.5.1",
    "@react-native-firebase/perf": "14.5.1",
```

**Comment by tranhuuthinhit** [comment]
Hi Mikehardy, 

I have the same thoughts as you about debug view, but when I try to integrate firebase with android native (JAVA) and then test update the user property and event, it works perfectly and updates on the User Property table at the right bottom.

And for React Native (iOS) with this lib, it still works perfectly.

![https://i.ibb.co/KFvFmDx/Screen-Shot-2022-03-22-at-10-24-30.png](https://i.ibb.co/KFvFmDx/Screen-Shot-2022-03-22-at-10-24-30.png)

![https://i.ibb.co/C2K2P5n/Screen-Shot-2022-03-22-at-10-26-50.png](https://i.ibb.co/C2K2P5n/Screen-Shot-2022-03-22-at-10-26-50.png)

But on React Native (Android), just the event had been updated realtime, and I need to kill the app and re-open the app again, and then the user property had been updated.

I think there may be a difference between iOS and Android implemented.

Can you help me re-produce it on Android?
Thank you

**Comment by mydesweb** [comment]
@mikehardy Any updates? I also use **setUserProperties** / **setUserProperty** and I don't see any of these properties in firebase console Debug View . Tested on Android with the latest version of analytics and react native. 

I also enabled debug mode running `adb shell setprop debug.firebase.analytics.app my.app.package`

**Comment by mikehardy** [comment]
There are no secret updates, what is in this thread is what exists

**Comment by sleekLancelot** [comment]
Hi guys,

I'm in a similar spot. I am setting some user properties in my application code with the hope of using them in remote config. However, I cannot find the properties anywhere on the analytics dashboard, not even in the debug view. It's been over an hour now, does it take longer than that to reflect?
