### ISSUE TITLE
[🐛] Bug Report Title - Property 'utmParametersDictionary' not found on object of type 'FIRDynamicLink

### ISSUE THREAD

**Issue by nwpnkmngm** [invertase/react-native-firebase#6153]
![image](https://user-images.githubusercontent.com/48342930/159862820-19c161f8-e183-4060-936c-73d372e8ec33.png)

**Comment by mikehardy** [comment]
When logging issues, you must search the issues list first - this is a duplicate of a couple exact same messages and has solutions (e.g., upgrade correctly to current version) https://github.com/invertase/react-native-firebase/issues?q=is%3Aissue+utmparametersdictionary+FIRDynamiclink
