### ISSUE TITLE
Android firestore:24.0.1 has bug preventing reconnection to firestore after being backgrounded (workaround: use bom 29.2.1)

### ISSUE THREAD

**Issue by evelant** [invertase/react-native-firebase#6158]
Per the title the Android firebase-firestore SDK v24.0.1 has a bug that will cause it to fail to reconnect to firestore after an app has been backgrounded and come back to the foreground. 

This is actually a bug in grpc-java that was fixed in v1.44.1 https://github.com/grpc/grpc-java/releases/tag/v1.44.1

firebase-firestore did not upgrade to grpc-java 1.44.1 until version firebase-firestore:24.0.2 but the current version of react-native-firebase uses firebase-firestore:24.0.1 which still has the bug

https://github.com/firebase/firebase-android-sdk/issues/3302

I resolved this locally by overriding the firebase sdk version on Android so that 24.0.2 is used like so in `build.gradle`

```
ext {
    set('react-native', [
                versions: [
                  // Overriding Library SDK Versions
                  firebase: [
                    // Override Firebase SDK Version
                    bom           : "29.2.1"
                  ]
                ],
              ])
}
```

**Comment by mikehardy** [comment]
Sure - working to unblock this via #6122 but it's stuck on an issue with auth emulator. We do allow overrides though luckily
I'll leave this open but alter the title a bit in case others need it

**Comment by mikehardy** [comment]
The firebase-android-sdk did not do a v29 release that includes the fix for the emulator I needed, it will be included in v30 firebase-android-sdk and I have the work for that port started. In the meantime affected users will need to specify the bom version as indicated here.

**Comment by evelant** [comment]
@mikehardy reading over the issues with upgrading firebase SDKs, particularly https://github.com/firebase/firebase-android-sdk/issues/3557 I've realized that using bom 29.2.1 is working in production to prevent this issue but is plaguing me in development where any given reload of the app seems to have a random chance of losing connection to the auth emulator. Based on that issue it looks like the firebase sdks still don't have a fix for the auth emulator issue so I'm not sure that recommending specifying 29.2.1 is so much a fix for this issue as it is a tradeoff that resolves the reconnect issue but introduces the auth emulator issue. Are there any firebase sdk versions that currently have neither problem that you might recommend trying?

**Comment by mikehardy** [comment]
Re-opening as I was sure based on interaction with firebase-android-sdk team this would be fixed and I'd do a release today with new SDKs, but that was not to be and this issue may be actionable based on test results from the above

**Comment by mikehardy** [comment]
I've got PR #6238 up that does what I mentioned and I'm going to release that to relieve the pressure on the auth emulator situation by getting at least a newer firestore out. There appears to be progress on the auth emulator issue but I really don't like cross-issue dependencies :-). 14.9.3 here (when it is out, a bit later today) will have the up to date firestore while still having an auth from bom 29.2.0 so it works locally
