### ISSUE TITLE
createLocalNotification with sound: false still plays a sound

### ISSUE THREAD

**Issue by Kerrick** [invertase/react-native-firebase#616]
### Issue

In a RNFirebase app I've set up from the [RNFirebase Starter](https://github.com/invertase/react-native-firebase-starter), I've created a local notification as such:

```js
import firebase from 'react-native-firebase';
// ...
firebase.messaging().createLocalNotification({
  title: 'Example Title',
  body: 'Example notification body with longer text',
  show_in_foreground: true,
  sound: false,
});
```

The local notification does show up in the Android notification center with the proper title and body, including when the app is open -- so everything except `sound: false` seems to be working as intended. However, I still hear the default Android notification sound whenever the local notification displays. I've also tried `sound: null` and `sound: undefined` and `sound: ''`.

### Environment

1. Application Target Platform: Android

2. Development Operating System: elementaryOS Luna

3. Build Tools: `react-native`, Android 7.X, WebStorm

4. React Native version: `^0.49.3`

5. RNFirebase Version: `^3.0.4`

6. Firebase Module: `messaging`

**Comment by Kerrick** [comment]
Update: After digging through the source code, it appears this may not be a supported feature. Is that actually the case? (I'm not super familiar with Java or Obj-C.)

https://github.com/invertase/react-native-firebase/blob/6f9cfd6ba1af680a143246cd7c3183f2fb2228ad/android/src/main/java/io/invertase/firebase/messaging/RNFirebaseLocalMessagingHelper.java#L75

https://github.com/invertase/react-native-firebase/blob/5e12700c3592e8209e955d096444023207a0388a/ios/RNFirebase/messaging/RNFirebaseMessaging.m#L38-L43

**Comment by Kerrick** [comment]
Well after digging further through the source code, I found a workaround!

https://github.com/invertase/react-native-firebase/blob/6f9cfd6ba1af680a143246cd7c3183f2fb2228ad/android/src/main/java/io/invertase/firebase/messaging/RNFirebaseLocalMessagingHelper.java#L121-L130

You can just include [a silent audio file](https://github.com/anars/blank-audio) in your build and then reference it by name. 

![image](https://user-images.githubusercontent.com/552093/32710586-1af7a88a-c7ff-11e7-89c9-dda47f807cc1.png)


```js
import firebase from 'react-native-firebase';
// ...
firebase.messaging().createLocalNotification({
  title: 'Example Title',
  body: 'Example notification body with longer text',
  show_in_foreground: true,
  sound: 'silence',
});
```

I'm still curious if this is/could be a built-in feature, but I can work with this!

**Comment by Ehesp** [comment]
Hello - please take a look at https://github.com/invertase/react-native-firebase/issues/595

We'll add it to the feature list on there. Cheers.

**Comment by chrisbianca** [comment]
Closing in favour of #595

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)
