### ISSUE TITLE
Prototype Pollution in simple-plist package - dependency of @react-native-firebase/app 

### ISSUE THREAD

**Issue by nick-casadei** [invertase/react-native-firebase#6172]
## Issue

Critical Vulnerability in package simple-plist which is a depedency of @react-native-firebase/app.

Using: "@react-native-firebase/app": "13.0.1",

When will this patch be available? And are there other ways to go about updating the subpackage simple-plist as I believe the issue has been resolved.

**Comment by mikehardy** [comment]
Hi there - I've got some trouble understanding this issue

Why are you filing a bug about updating packages without being on the current package?

> Using: "@react-native-firebase/app": "13.0.1",

We are on 14.7.0

Why are you filing an issue about some critical vulnerability without including any reference to the vulnerability? https://stackoverflow.com/help/how-to-ask

Why are you waiting on an update from here when updating transitive dependencies in your package-lock.json or yarn.lock is a trivial matter and may be done with directives in your package.json? 

https://stackoverflow.com/questions/56634474/npm-how-to-update-upgrade-transitive-dependencies

If on our current versions we are still pinned somehow to out of date versions, what is the transitive dependency chain?

**Comment by mikehardy** [comment]
To anyone else reading this, please examine carefully the link @srithar21 posts, it contains this:

> There is no fixed version for simple-plist.

So there is nothing we can do, and it's not in our control. Go work with simple-plist to patch their code.

Then use package.json as linked above in stackoverflow link to set the resolution to that simple-plist version that is patched.

I repeat: This is not actionable here. There is nothing we can do. Go to simple-plist repo.

**Comment by mikehardy** [comment]
Appears fixed https://github.com/wollardj/simple-plist/pull/62 - released as 1.3.1
So, how did it go when you deleted your yarn.lock or package-lock.json and re-installed?

**Comment by srithar21** [comment]
After removing the yarn.lock and package-lock - Reinstalled and simple-plist updated into 1.3.1.

But still issue exist in the Snyk side and pointing the same firebase app.

@react-native-firebase/app@14.7.0, @react-native-firebase/crashlytics@14.7.0.

**Comment by srithar21** [comment]
Because It will scan against the package.json not lock files.

Can you please update crashlytics library with simple-plist@1.3.1.

**Comment by mikehardy** [comment]
@srithar21 you are misunderstanding how dependencies work, and attributing a problem to this module that is *not* our problem. There is nothing I can do for you.
We do not use that package in our dependencies, please check for yourself: https://github.com/invertase/react-native-firebase/blob/main/packages/crashlytics/package.json

There is nothing actionable here for us.

**Comment by mikehardy** [comment]
Since the dependency is not actually referenced by our packages, and the version is not specified, standard dependency version management solutions may be used, with success as indicated by the report that re-installing packages got the updated version.

As such, this is not actionable, meaning the issue is closed here as there is nothing to do.

**Comment by srithar21** [comment]
@mikehardy  I posted this issue in simple-list repo. Thank you for your time.

https://github.com/wollardj/simple-plist/issues/60
