### ISSUE TITLE
🔥 [🐛] `messaging().getToken()` no longer supports `messageSenderId`, breaks notifications

### ISSUE THREAD

**Issue by ecexplorer** [invertase/react-native-firebase#6173]
## Issue
When Firebase updated to use `getInstance()` instead of InstanceId to get a FCM token, this project dropped support for passing `messagingSenderId` into `getToken()`. This meant that apps which initialized the project using options in `initializeApp` would inadvertently get a token for the default project rather than the expected project.  Base on the current implementation in this library, I don't see a similar workaround as worked before for passing `messagingSenderId`.  
In trying to verify this issue, I stumbled upon: https://stackoverflow.com/questions/62253691/firebasemessaging-getinstancefirebaseapp-for-secondary-app-supposed-to-be-publ.  
I can report that after having locally changed `FirebaseMessaging.getInstance()` in `getToken()` in **ReactNativeFirebaseMessagingModule** to `FirebaseApp.getInstance(<project_name>).get(FirebaseMessaging.class)`, notifications again work on the expected project.  
Although this is tested on Android, I would _hope_ a similar fix is available for iOS (both platforms exhibit the issue).

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `14.7.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Cloud Messaging`
- **Are you using `TypeScript`?**
  - `N/A`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
This was noticed in https://github.com/invertase/react-native-firebase/discussions/6145 as well, I just tagged that discussion so the other interested party could participate.

@ecexplorer are you interested in posting a PR for this? We could get it merged + released really quickly though for something like this we need to figure out iOS as well

@paulb777 I am really bending your ear today, apologies for randomly tagging twice. We've got users looking for app-specific device tokens to target messages, where previously they used Instance ID's scoped tokens, but those are gone now with Installations (and there is just one getToken API, no scope). Here (and with more details and firebase-android-sdk code ref link here https://github.com/invertase/react-native-firebase/discussions/6145) it appears we may get app-specific tokens in a ... kind of rude way on Android, is there *anything* like that in firebase-ios-sdk?

**Comment by ecexplorer** [comment]
@mikehardy let me poke around the iOS side (less knowledgable) and see. If I can find a similar fix there, happy to work on a PR.

**Comment by ecexplorer** [comment]
I opened a firebase support case for iOS specifically. There is not an obvious way that I can see to make a similar call on iOS.

**Comment by chliangGoogle** [comment]
@ecexplorer I believe Firebase Messaging still keeps the multi-senderID token api: https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessaging.h#L307

Does this fit your need?

**Comment by ecexplorer** [comment]
@chliangGoogle This is perfect! Thank you!

I'll test this method, similar to how I tested Android and report back; create a PR if it all comes together!
🍻

**Comment by mikehardy** [comment]
Very nice - that certainly looks on target, thank you so much @chliangGoogle 

@ecexplorer not sure exactly how to set up a platform-independent getToken API that does the right thing on both platforms but something must be workable

We generally try our hardest to mirror the JS SDK API (v8 still, but with an eye towards v9) but I'm not sure how much guidance that provides here
https://firebase.google.com/docs/reference/js/v8/firebase.messaging.Messaging#gettoken
https://firebase.google.com/docs/reference/js/messaging_#gettoken

They both provide for an "options" parameter, which does not contain a parameter for "scope" or "app" https://firebase.google.com/docs/reference/js/messaging_.gettokenoptions.md#gettokenoptions_interface

Perhaps we could add "scope" back in to the getToken call by taking a TokenOptions argument that supports a scope key/value pair and ties into these underlying android/ios APIs ?

I'm thinking out loud here a little bit. Anything with this rough solution shape seems like it would be okay

**Comment by ecexplorer** [comment]
☝️ @mikehardy - threw that together quickly. I don't have RNFB fully setup locally, so testing, etc is slim.
I'll target our NPM to this branch while reviews are ongoing.
Did my best to follow your options suggestion, and I think it fits well here.

**Comment by FranciscoPDNeto** [comment]
Hello all, any updates about this issue? I was seeing this issue https://github.com/firebase/firebase-android-sdk/issues/2778 on android sdk and it seems that really there is no other way but creating another firebaseApp for the custom senderId, it seems possible just for iOS https://firebase.google.com/docs/reference/swift/firebasemessaging/api/reference/Classes/Messaging#retrievefcmtokenforsenderid:.
