### ISSUE TITLE
React Native Firebase App Check In ios: Error: [firestore/permission-denied] The caller does not have permission to execute the specified operation.

### ISSUE THREAD

**Issue by RajanDevstree** [invertase/react-native-firebase#6181]
When i try to access the firestore database when firstore enforce in appcheck active get a permission-denied error

**Comment by mikehardy** [comment]
Hi there! You have not followed our template, and there is no attempt to demonstrate how to reproduce this, so it's not actionable and I'll close it.
It is very important to say that we have not heard of any module errors (or SDK errors, for that matter) with firestore in enforcing mode, but there are many reasons your error could happen *if your project is not configured correctly*. So I'd use all available troubleshooting tools on your local project and attempt to verify configuration is good.
