### ISSUE TITLE
[🐛] Spelling Mistake in Documentation

### ISSUE THREAD

**Issue by Jagroop2000** [invertase/react-native-firebase#6186]
In the React-Native Firebase Documentation is the a spelling mistake of **principals** . Instead of **principals** there will be **principles**. Below i add screen for your reference :
![Screenshot from 2022-04-07 20-37-47](https://user-images.githubusercontent.com/99062463/162232459-c627b043-14f2-4ff0-9498-d3cd15bbeea3.png)

I would like to work on this bug. Can i work ??

Here is the documentation link : https://github.com/invertase/react-native-firebase

**Comment by mikehardy** [comment]
No need to ask or even post an issue on a small item - just hit the edit button at the top right of the page and post a PR. 
Since you've opened an issue, when open the PR put `Fixes #6186` in there and this will be cross-linked by github automatically and auto-closed when PR is merged
Thanks!
