### ISSUE TITLE
Storage :An unknown error has occurred. 

### ISSUE THREAD

**Issue by dev-hamid** [invertase/react-native-firebase#621]
### Issue

getting an error with message 
> An unknown error has occurred. 
here is my code
```
async onFinish() {
                try {
                        const uid =this.state.uid
                        this.setState({loading:true})
                        let avatar = await firebase.storage().ref('Avatars/'+uid+'.jpg').putFile(this.state.imgBase64Avatar);
                        console.log(avatar);
                        if(avatar) this.setState({loading:false})
                }
}
 ```

### Environment

1. Application Target Platform: Both

2. Development Operating System: ubuntu 16.04

4. React Native version: 0.49.3

5. RNFirebase Version: ^3.0.5

6. Firebase Module: storage

**Comment by chrisbianca** [comment]
@dev-hamid we're going to need more to go on than this. Have you checked the native logs to see if there are any errors there? Is this definitely giving the same error on iOS and Android?

**Comment by dev-hamid** [comment]
it was fixed after passing the image path instead of blob 
now it works perfect
and the docs says nothing

**Comment by chrisbianca** [comment]
@dev-hamid Glad you got it working. Updating the storage documentation is on our list of things to do.  Please feel free to submit a PR with some documentation in the meantime.
