### ISSUE TITLE
🔥 [🐛]@react-native-firebase/perf build fails on Expo/Android using managed workflow

### ISSUE THREAD

**Issue by lucas-figueiredo-m** [invertase/react-native-firebase#6210]
## Issue

I'm working on a project that is supposed to use the @react-native-firebase/perf module. We are using Expo on a managed workflow. When we try to build the Android package using eas, the following error happens:

`[stderr] > java.lang.UnsupportedClassVersionError: com/google/firebase/perf/plugin/FirebasePerfPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

But after ejecting the project, it has built successfully when built locally. We would like not to eject for now, and keep the project in the managed workflow. But first, we need to understand why is it failing on expo builds.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "N/A",
  "version": "N/A",
  "scripts": {
    "preinstall": "npx npm-force-resolutions",
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "npx jest --coverage --reporters=jest-junit --reporters=default",
    "lint": "npx eslint ./app",
    "eas-cli": "npx eas-cli"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-firebase/analytics": "^14.8.0",
    "@react-native-firebase/app": "^14.8.0",
    "@react-native-firebase/auth": "^14.8.0",
    "@react-native-firebase/crashlytics": "^14.8.0",
    "@react-native-firebase/perf": "^14.8.0",
    "@react-native-google-signin/google-signin": "7.0.4",
    "@react-navigation/bottom-tabs": "^6.2.0",
    "@react-navigation/drawer": "^6.3.1",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "@react-navigation/stack": "^6.1.1",
    "@reduxjs/toolkit": "^1.8.0",
    "ajv": "^8.11.0",
    "apisauce": "^2.1.2",
    "dayjs": "^1.10.7",
    "expo": "^43.0.2",
    "expo-apple-authentication": "~4.0.3",
    "expo-dev-client": "^0.6.3",
    "expo-device": "~4.0.3",
    "expo-facebook": "~12.0.3",
    "expo-image-picker": "~11.0.3",
    "expo-notifications": "~0.13.3",
    "expo-permissions": "~13.0.3",
    "expo-splash-screen": "~0.13.5",
    "expo-status-bar": "~1.1.0",
    "expo-updates": "~0.10.13",
    "i18next": "^21.6.14",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-i18next": "^11.15.6",
    "react-native": "0.64.3",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-logs": "^4.0.1",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.13.0",
    "react-redux": "^7.2.6",
    "redux-persist": "^6.0.0",
    "underscore": "^1.13.1",
    "validator": "^13.7.0"
  },
  "devDependencies": {
    "@babel/core": "^7.17.8",
    "@babel/plugin-transform-runtime": "^7.17.0",
    "@types/validator": "^13.7.1",
    "babel-eslint": "^10.1.0",
    "babel-plugin-inline-import": "^3.0.0",
    "babel-plugin-module-resolver": "^4.1.0",
    "babel-preset-expo": "8.5.1",
    "eslint": "^7.32.0",
    "eslint-import-resolver-babel-module": "^5.3.1",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-module-resolver": "^1.4.0",
    "eslint-plugin-react": "^7.26.1",
    "eslint-plugin-react-hooks": "^4.3.0",
    "jest": "^26.6.3",
    "jest-expo": "~43.0.1",
    "jest-junit": "^13.0.0",
    "prettier": "^2.6.0",
    "prettier-eslint": "^13.0.0",
    "react-test-renderer": "^17.0.2",
    "sucrase": "^3.20.3"
  },
  "resolutions": {},
  "jest": {
    "preset": "jest-expo",
    "setupFiles": [
      "./jest.setup.js"
    ],
    "collectCoverage": true,
    "collectCoverageFrom": [
      "**/*.{js,jsx}",
      "!**/coverage/**",
      "!**/node_modules/**",
      "!**/babel.config.js",
      "!**/jest.setup.js"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
    ]
  },
  "private": true
}
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**
PS: this output was generated after ejecting.

```
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 86.50 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.4.1 - /opt/homebrew/bin/npm
    Watchman: 2022.02.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 32.0.0, 32.1.0, 33.0.0
      System Images: android-32 | Google APIs ARM 64 v8a, android-Tiramisu | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 14.8.0
- **`Firebase` module(s) you're using that has the issue:**
  - @react-native-firebase/perf
- **Are you using `TypeScript`?**
  - No

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
https://search.brave.com/search?q=java.lang.UnsupportedClassVersionError%3A+com%2Fgoogle%2Ffirebase%2Fperf%2Fplugin%2FFirebasePerfPlugin+has+been+compiled+by+a+more+recent+version+of+the+Java+Runtime+(class+file+version+55.0)%2C+this+version+of+the+Java+Runtime+only+recognizes+class+file+versions+up+to+52.0&source=desktop

https://www.baeldung.com/java-lang-unsupportedclassversion

```
52 = Java 8
53 = Java 9
54 = Java 10
55 = Java 11
```

EAS infrastructure is perhaps on JDK8, you need JDK11

We have had to handle similar things for people on Notifee, as more libraries (including Notifee) require Android API31 as the compile target, which requires JDK11 to build, leading to these problems sometimes.

https://notifee.app/react-native/docs/installation#expo-support

If that doesn't get you going, pursue "how to use JDK11 in EAS builds" with Expo support, they should be able to get you going

Hope this helps
