### ISSUE TITLE
[📚] iOS Messaging Setup would be easier to find as a sub-section of "Cloud Messaging"

### ISSUE THREAD

**Issue by taylorkline** [invertase/react-native-firebase#6214]
## Documentation Feedback

Currently, [iOS Messaging Setup](https://rnfirebase.io/messaging/usage/ios-setup) is a bit difficult to find since it does not show up in the right-hand navigation bar, as you can see here:

![Screen Shot 2022-04-25 at 3 31 39 PM](https://user-images.githubusercontent.com/2641739/165170003-3be87129-ce19-465e-b302-0e71f770a10a.png)

The easiest thing would probably be to make it a sub-section of "Cloud Messaging" the same as "iOS Notifications," "Server Integration," and the rest. Or, perhaps it could continue to be nested under "Usage," but with a drop-down chevron indicator appearing so that you can see that iOS Messaging Setup is a subsection of Usage.

**Comment by mikehardy** [comment]
Oh wow! It doesn't really show up anywhere at all does it? Thanks for pointing that out, let me see what I can do

**Comment by mikehardy** [comment]
The vercel deploy of the PR for #6215 should have this fixed, hopefully looks good

**Comment by taylorkline** [comment]
Awesome, ty!
