### ISSUE TITLE
RNFirebase core module was not found..

### ISSUE THREAD

**Issue by koansang** [invertase/react-native-firebase#622]
### Issue
I have error when run-ios with RNFirebase.

- my `Podfile`
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'enertalk_kr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for enertalk_kr
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  
  target 'enertalk_krTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'enertalk_kr-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for enertalk_kr-tvOS

  target 'enertalk_kr-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
- ScreenShot
![image](https://user-images.githubusercontent.com/12390185/32769358-f1641d12-c95e-11e7-938c-bb6cc3f90592.png)

- Terminal log
```
/Volumes/Data/Project/enertalk_kr/node_modules/react-native/React/../third-party/glog-0.3.4/src/base/mutex.h:105:10: fatal error: 'config.h' file not found
#include "config.h"           // to figure out pthreads support
         ^~~~~~~~~~
1 error generated.
```

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode 9.1

4. React Native version: 0.49.3

5. RNFirebase Version: 3.1.0

6. Firebase Module: core, analytics

**Comment by Vilitsa** [comment]
+

**Comment by chrisbianca** [comment]
@koansang 
1) Have you run `react-native link`?
2) Firebase doesn't work well as a dynamic framework, comment out the `use_frameworks!` line in your Podfile

**Comment by Vilitsa** [comment]
1. yep
2. I don't use use_frameworks!

**Comment by Ehesp** [comment]
@Vilitsa Its there though:

![image](https://user-images.githubusercontent.com/842078/32779422-a80bce86-c935-11e7-967c-fc977c401512.png)

**Comment by whitebird** [comment]
@chrisbianca Since I use Swift in my project, is it possible to make it work while still using use_frameworks? The solution proposed here didn't work. https://github.com/invertase/react-native-firebase/issues/252

**Comment by c0d3blooded** [comment]
+1

I'm also running into this issue with no 'use_frameworks!' lines in my Podfile. 

Pods have been added and installed (and re-installed/updated), GoogleService-Info.plist file has been added, and project has been already linked.

Why would this error come up if the RNFirebase pod has been deprecated?

**Environment**

Application Target Platform: iOS
Development Operating System: macOS Sierra
Build Tools: Xcode 9.1
React Native version: 0.50.3
RNFirebase Version: 3.1.1

**Comment by jwrubel** [comment]
For anyone still having this issue - I fixed it following the instructions [here](https://github.com/invertase/react-native-firebase/issues/519#issuecomment-336871738). A brand new `pod init` `pod install` will not get the latest pods. To get the latest, run `pod outdated` - for reference my output was:
```
The following pod updates are available:
- Firebase 4.0.0 -> (unused) (latest version 4.7.0)
- FirebaseAnalytics 4.0.0 -> 4.0.5 (latest version 4.0.5)
- FirebaseAuth 4.0.0 -> 4.4.0 (latest version 4.4.0)
- FirebaseCore 4.0.0 -> 4.0.12 (latest version 4.0.12)
- FirebaseInstanceID 2.0.0 -> 2.0.7 (latest version 2.0.7)
- GoogleToolboxForMac 2.1.1 -> (unused) (latest version 2.1.3)
- GTMSessionFetcher 1.1.10 -> (unused) (latest version 1.1.12)
```
then `pod update`.

One that completed, my app launched with no errors.

**Comment by Salakar** [comment]
These are also now in the troubleshooting ios installation docs now thanks to @jwrubel 

@Vilitsa and @koansang is this still an issue for you?

**Comment by heckchuckman** [comment]
Hi @jwrubel could you post your Podfile? I've been beating my head against the wall on this issue for hours with no result. Either React gets added which obviously breaks things or RNFirebase is missing and throws a red screen.

Many thanks!

**Comment by heckchuckman** [comment]
Also, the `pod update` fix, as covered in the documentation, did not work for me. I still have the red screen error message referencing that the module was not found persists.

Thanks all!

**Comment by jwrubel** [comment]
Here's my Podfile - there's nothing much here really:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'BeerGoggles' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # required for RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
end
```
@heckchuckman what do you get when you run `pod outdated` ? After running `pod update` I now get the message `No pod updates are available.` but before I updated I got that list of updatable pods I posted above. If you run `pod outdated` and it says everything is up to date, I am afraid I'm at a loss to help beyond that.

**Comment by heckchuckman** [comment]
After a bit of tooling around this pod file (snippet) worked for me after I deleted/cleaned all pods ... While this works, I'm a bit concerned I'll run into issues down the road because it looks like the React pod is being deprecated ...

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native' , :subspecs => [
    'BatchedBridge',
    'Core',
    'DevSupport'
  ]
...
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
...
  

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

**Comment by c0d3blooded** [comment]
I was able to get my app up and running with the recommended Podfile specs (just the Firebase pods) with the latest RN version (0.51.0).

It looks like there have been some changes to help RN work better with CocoaPods:
https://github.com/facebook/react-native/releases/tag/v0.51.0
https://github.com/facebook/react-native/commit/74146cb3158273921b768c97f229695e680ea82d

**Comment by bobmulder** [comment]
@c0d3blooded Can you show me what you've done and how your config looks like to help me and others? :) Getting crazy on RN 0.51.0 and RN Firebase 3.1.*

**Comment by c0d3blooded** [comment]
@bobmulder Sure. My Podfile isn't much different than what's already been mentioned.
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'fitkit' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Required by RNFirebase
    pod 'Firebase/Core'

    # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Messaging'
    pod 'Firebase/Storage'
end
```
I'm also on react-native-firebase version 3.1.1.

You may also want to try deleting your Pods folder and Podfile ( and .lock), and re-initializing pods for your project:

pod init
*configure your Podfile*
pod install
pod update

Also try running react-native link after updating to RN 0.51.

**Comment by bobmulder** [comment]
@c0d3blooded thank's! I managed to fix it before by removing the `ios` folder and start again initializing iOS, and adding RN Firebase again. It was sort of the same like you documented so I hope this will help people!

**So if you're stuck, remove the `ios` folder, run `react-native upgrade` and start all over again :)**

**Comment by chrisbianca** [comment]
Closing this as `use_frameworks!` is now supported as part of v3.2.0

**Comment by noumanDev** [comment]
i have added this line in my pod file 
``  pod 'RNFirebase', :path => '../node_modules/react-native-firebase' ``

and it gives error  `` [!] No podspec found for `RNFirebase` in `../node_modules/react-native-firebase`

**Comment by noumanDev** [comment]
@chrisbianca thanks for your quick response, i had not much time to fix this issue, so i used the firebase starter project and it works.

**Comment by ankitsehgal94** [comment]
> After a bit of tooling around this pod file (snippet) worked for me after I deleted/cleaned all pods ... While this works, I'm a bit concerned I'll run into issues down the road because it looks like the React pod is being deprecated ...
> 
> ```
>   pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
>   pod 'React', :path => '../node_modules/react-native' , :subspecs => [
>     'BatchedBridge',
>     'Core',
>     'DevSupport'
>   ]
> ...
>   pod 'Firebase/Core'
>   pod 'Firebase/Auth'
>   pod 'Firebase/Firestore'
> ...
>   
> 
>   pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
> ```

How did you fix the issue React depreciated?

**Comment by leotm** [comment]
> ... We really don't recommend using RNFirebase as a pod, it's much safer to import using `react-native link`

@chrisbianca Sorry late to the party here, since the Xcode 11 update.

Who is _we_? And why not recommend it as a pod?

The documentation states

> 1.3. Install Firebase Library
> Option 1: Cocoapods (Recommended)
> Firebase recommends using Cocoapods to install the Firebase SDK.

Source: https://rnfirebase.io/docs/v5.x.x/installation/ios#Option-1:-Cocoapods-(Recommended)

Am I missing something here, or have times changed?

**Comment by Salakar** [comment]
> Am I missing something here, or have times changed?

Times have most definitely changed, Pods are now the recommended approach especially in RN 0.60+

**Comment by mikehardy** [comment]
well @Salakar and @leotm I would be careful - times have most definitely changed and pods are recommend for 0.60+ (I can't imagine it working otherwise?) but that's just barely slightly different then saying "especially for 0.60+", for react-native 0.59 you actually *must* link react-native-firebase, then just add the underlying google firebase ios sdks as pods. 

And when you ask "who is we", it's people that sit on the github issues lists and the discord forums and actively troubleshoot problems until we get to reliable solutions. And right now the reliable solution for installation is:

react-native 0.59? move Podfile out of the way, react-native link react-native firebase, move Podfile back and add the google firebase iOS SDKs as pods

react-native 0.60+? everything via Pods and auto-linking
