### ISSUE TITLE
[🐛] Expo SDK 45 error - Can't compile AppDelegate.mm

### ISSUE THREAD

**Issue by cdedreuille** [invertase/react-native-firebase#6221]
## Issue

We have an app using SDK 44 and our set up worked just fine. We are building the app using EAS. This morning we tried to upgrade to Expo SDK 45 and React Native 0.68 and while building we had this error in fastlane:

![CleanShot_2022-04-28_at_07 55 012x](https://user-images.githubusercontent.com/1540635/165696009-0ca303cd-c923-4cea-8ead-e9e293d9049a.png)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/app": "^14.9.0",
"@react-native-firebase/dynamic-links": "^14.9.0",
"@react-native-firebase/messaging": "^14.9.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
I don't have a firebase.json file
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods per say as I use EAS to compile our app.

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
I don't have access to this file
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] We are mostly focus on iOS
- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both - We are using EAS to build the app and this is where it crashes.
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - Yes & version 4.3.5

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by cdedreuille** [comment]
It seems this PR might fix this bug.
https://github.com/invertase/react-native-firebase/pull/6223

**Comment by mikehardy** [comment]
@cdedreuille yep! @kbrandwijk and @barthap get to split my daily ration of Internet Points for working through a PR that fixes this :-) - as soon as CI finishes chewing on it I'll issue a patch release that supports Expo 45's new RN68/objective-c++-based builds
