### ISSUE TITLE
'@react-native-firebase/iid' depends on '@react-native-firebase/app' v11.5.0 but found v14.3.0, this might cause build issues or runtime crashes.

### ISSUE THREAD

**Issue by ashishHp1** [invertase/react-native-firebase#6228]
I am experiencing issue regarding PendingIntent on Android version 12 so i was updating all Firebase libraries to the the latest version but '@react-native-firebase/iid' library is having 11.5.0 version so again there is a dependency issue. 
I am getting this issue like this:
ReactNativeFirebase WARNING: NPM package '@react-native-firebase/iid' depends on '@react-native-firebase/app' v14.9.1 but found v11.5.0, this might cause build issues or runtime crashes.

Need help regarding this issue

**Comment by mikehardy** [comment]
Hi there! The IID package no longer exists, I published a document that explains exactly *how* we version, and then runs through how to handle major version changes (where we introduce breaking changes) here https://invertase.io/blog/react-native-firebase-versioning

Once you switch from IID to Installations (or simply remove IID and use newer APIs if you're just getting messaging tokens) you'll be set
