### ISSUE TITLE
Different UID for Facebook users

### ISSUE THREAD

**Issue by nikolal** [invertase/react-native-firebase#625]
Hi,

We used web SDK before, and now we are migrating to react-native-firebase.

We used this function to log in facebook users:

```
    LoginManager.logInWithReadPermissions(['public_profile', "email","user_friends"])
      .then((result) => {
        if (result.isCancelled) {
          console.log('Login cancelled');
        } else {
          AccessToken.getCurrentAccessToken()
            .then((data) => {
              var accessToken = data.accessToken.toString()
              firebase.authWithOAuthToken('facebook', accessToken, (error, authData) => {
                if (error) {
                  console.log(error)
                } else {
                  this.handleAuthLogin(authData, accessToken)
                }
              });
            })
        }
      }, (error) => {
        console.log('Login fail with error: ' + error);
      }
    );
```

Now we are using:

```
    LoginManager
      .logInWithReadPermissions(['public_profile', 'email', "user_friends"])
      .then((result) => {
        if (result.isCancelled) {
          console.log('Login cancelled');
        }
        // get the access token
        return AccessToken.getCurrentAccessToken();
      })
      .then(data => {
        // create a new firebase credential with the token
        const credential = firebase2.auth.FacebookAuthProvider.credential(data.accessToken);
        // login with credential
        return firebase2.auth().signInWithCredential(credential);

      })
      .then((currentUser) => {
        console.log(currentUser); // TODO: handle current user
      })
      .catch((error) => {
        console.log(`Login fail with error: ${error}`);
      });
```

The issue is that Firebase returns different UID for old and new Facebook user, so this means that old users will loose their progress if they login using new SDK.

What could cause this, is this normal behavior?
Is there any workaround for this issue?

Thanks in advanced.

**Comment by chrisbianca** [comment]
@nikolal It looks like you're using the original web Firebase SDK from before Google bought them out, and not the updated Google Firebase Web SDK, by the looks of things here: https://firebase.google.com/support/guides/firebase-android#sign_a_user_in_with_a_social_provider_numbered

We have no control over the Firebase IDs that are being returned, we just pass the credentials through to the iOS and Android SDKs and they handle this for us.

I'd suggest perhaps updating to Google's Firebase Web SDK first (the above code should work perfectly) and see if you have the same problem before subsequently updating to react-native-firebase.

I'm going to close this issue as it's not really anything RNFirebase can help with, but please re-open if you find that it is our problem.
