### ISSUE TITLE
Firestore getting Message undefined

### ISSUE THREAD

**Issue by billnbell** [invertase/react-native-firebase#6250]
"@react-native-firebase/firestore": "^14.9.4",

  const v1 = await firestore().collection(table).doc(username).get();

I always get "Undefined Message"

**Comment by mikehardy** [comment]
Hmm :thinking: may I infer that with 14.9.4 this does not happen?  Or maybe 14.9.2?

The only difference between 14.9.4 here and 14.9.3 is a firestore patch version from 24.1.1 to 24.1.2 https://firebase.google.com/support/release-notes/android#firestore_v24-1-2

v14.9.1 here had a much older firestore so it may have different behavior as well

Pretty strange - our e2e tests definitely exercise getting docs from collections and they went through fine but maybe the newly adopted firebase-android-sdk has something going on that we're not detecting. Any information you can provide to reproduce would be helpful, like details of the execution environment you see this, the stack trace if any, etc

https://stackoverflow.com/help/how-to-ask

**Comment by mikehardy** [comment]
also perhaps `npx react-native-clean-project` but I will quickly acknowledge that's a pretty vague "solution" along the same lines as "reboot", at the same time it's surprising how often that works.

And very important to note that there haven't been iOS changes in the last release so if you're seeing this on iOS then we have something very strange happening.

**Comment by billnbell** [comment]
OK I think this was a local issue. Since I rebooted and it worked.

Let's close this one. Weird on my side. Sorry!
