### ISSUE TITLE
Property 'delegate' not found on object of type 'FIRMessaging *'

### ISSUE THREAD

**Issue by RaniaAAH** [invertase/react-native-firebase#626]
Using Firebase (3.17.0)
Using FirebaseAnalytics (3.9.0)
Using FirebaseCore (3.6.0)
Using FirebaseInstanceID (1.0.10)
Using FirebaseMessaging (1.2.3)

[FIRMessaging messaging].delegate = self;
// error Property 'delegate' not found on object of type 'FIRMessaging *'
how to solve error please ?!

iOS objective-c

**Comment by chrisbianca** [comment]
@RaniaAAH You need to be using Firebase v4.X. Run the following in your `ios` directory:

`pod outdated` - Check which pod files have updates available
`pod update` - Update all pods

**Comment by RaniaAAH** [comment]
@chrisbianca  i tried your solution but issue not solved. 

pod outdated
    WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    
Updating spec repo `master`
  $ /usr/bin/git -C /Users/rm/.cocoapods/repos/master fetch origin --progress
  remote: Counting objects: 18, done.        
  remote: Compressing objects: 100% (17/17), done.        
  remote: Total 18 (delta 11), reused 0 (delta 0), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     c2ad28e..81f9266  master     -> origin/master
  $ /usr/bin/git -C /Users/rm/.cocoapods/repos/master rev-parse --abbrev-ref
  HEAD
  master
  $ /usr/bin/git -C /Users/rm/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 81f9266 [Add] Heyzap 9.15.3
Analyzing dependencies
The following pod updates are available:
- Firebase 3.17.0 -> (unused) (latest version 4.6.0)
- FirebaseAnalytics 3.9.0 -> 3.9.0 (latest version 4.0.5)
- FirebaseCore 3.6.0 -> 3.6.0 (latest version 4.0.11)
- FirebaseInstanceID 1.0.10 -> 1.0.10 (latest version 2.0.6)
- FirebaseMessaging 1.2.3 -> 1.2.3 (latest version 2.0.6)
- TwitterCore 2.8.0 -> 2.8.0 (latest version 3.0.2)
- TwitterKit 2.8.1 -> 2.8.1 (latest version 3.2.1)
The following pods are deprecated:
- Google
rms-macbook-pro:MozaicMe rm$ pod update
    WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    
Update all pods
Updating local specs repositories
  $ /usr/bin/git -C /Users/rm/.cocoapods/repos/master fetch origin --progress
  $ /usr/bin/git -C /Users/rm/.cocoapods/repos/master rev-parse --abbrev-ref
  HEAD
  master
  $ /usr/bin/git -C /Users/rm/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 81f9266 [Add] Heyzap 9.15.3
Analyzing dependencies
Downloading dependencies
Using ActionSheetPicker-3.0 (2.2.0)
Using Crashlytics (3.9.3)
Using Fabric (1.7.2)
Using Firebase (3.17.0)
Using FirebaseAnalytics (3.9.0)
Using FirebaseCore (3.6.0)
Using FirebaseInstanceID (1.0.10)
Using FirebaseMessaging (1.2.3)
Using GTMOAuth2 (1.1.5)
Using GTMSessionFetcher (1.1.12)
Using Google (3.1.0)
Using GoogleAnalytics (3.17.0)
Using GoogleSignIn (4.1.1)
Using GoogleToolboxForMac (2.1.3)
Using Protobuf (3.5.0)
Using TwitterCore (2.8.0)
Using TwitterKit (2.8.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 8 dependencies from the Podfile and 17 total pods installed.

**Comment by chrisbianca** [comment]
@RaniaAAH Looks like one of your other dependencies is making use of an explicit earlier version. Can you show me the contents of your `Podfile.lock`?

**Comment by RaniaAAH** [comment]
@chrisbianca  


platform :ios, '8.0'
use_frameworks!

target 'MozaicMe' do
use_frameworks!

pod 'Fabric'
pod 'Crashlytics'
pod 'TwitterKit'
pod 'Google/SignIn'
pod 'ActionSheetPicker-3.0'
pod 'Google/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
end

**Comment by RaniaAAH** [comment]
@chrisbianca can you help me please ?!

**Comment by chrisbianca** [comment]
@RaniaAAH I asked for your `Podfile.lock` file, otherwise I can't help you

**Comment by RaniaAAH** [comment]
@chrisbianca  sorry it is my mistake i attached it now
[Podfile.lock.zip](https://github.com/invertase/react-native-firebase/files/1487148/Podfile.lock.zip)

**Comment by chrisbianca** [comment]
Try changing your target platform to iOS 9.0?

**Comment by RaniaAAH** [comment]
@chrisbianca  i tried but issue still exist 
[Podfile.lock.zip](https://github.com/invertase/react-native-firebase/files/1487192/Podfile.lock.zip)

**Comment by chrisbianca** [comment]
Did you run `pod outdated` and `pod update` again?

**Comment by RaniaAAH** [comment]
yes

**Comment by chrisbianca** [comment]
Can you try commenting out the use_frameworks line?

**Comment by RaniaAAH** [comment]
tried but issue still exist !

platform :ios, '9.0'

target 'MozaicMe' do

pod 'Fabric'
pod 'Crashlytics'
pod 'TwitterKit'
pod 'Google/SignIn'
pod 'ActionSheetPicker-3.0'
pod 'Google/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
end

[Podfile.lock.zip](https://github.com/invertase/react-native-firebase/files/1487213/Podfile.lock.zip)

**Comment by chrisbianca** [comment]
@RaniaAAH The issue is that Google/Analytics is using the Google/Core pod which in turn requests an old 3.x version of Firebase/Core

**Comment by haseebnaseem** [comment]
facing the same issue. Any fix for this ?
