### ISSUE TITLE
[🐛] @react-native-firebase/messaging {"line":108,"column":352,"sourceURL":"index.android.bundle"}

### ISSUE THREAD

**Issue by phanvungoc96** [invertase/react-native-firebase#6265]
## Issue

Describe your issue here
I get an error when i get getToken FCM from firebase.
I have checked all the installations on the project and also the Firebase console, SHA1 keys, and nothing is out of the ordinary.
Everything works normally in debug mode, but when I release the apk file and install it on the real phone, I get an error like this.
Please help me.
![IMG_1128](https://user-images.githubusercontent.com/73456278/170180550-f4aa165e-e5fa-483e-947c-12554bbb18f7.jpg)

---

## Project Files

<img width="751" alt="Screen Shot 2022-05-25 at 11 35 36" src="https://user-images.githubusercontent.com/73456278/170180628-cd7dadbd-4fe9-478e-8599-4e06fb4bc604.png">

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
    "@react-native-firebase/analytics": "12.8.0",
    "@react-native-firebase/app": "12.8.0",
    "@react-native-firebase/crashlytics": "12.8.0",
    "@react-native-firebase/messaging": "12.8.0",
```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:
{
  "react-native": {
    "crashlytics_debug_enabled": true,
    "crashlytics_disable_auto_disabler": true,
    "crashlytics_auto_collection_enabled": true,
    "crashlytics_is_error_generation_on_js_crash_enabled": true,
    "crashlytics_javascript_exception_handler_chaining_enabled": true
  }
}

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Please make sure you log issues while using current versions of the software, these are getting pretty old:

```
"@react-native-firebase/analytics": "12.8.0",
"@react-native-firebase/app": "12.8.0",
"@react-native-firebase/crashlytics": "12.8.0",
"@react-native-firebase/messaging": "12.8.0",
```

Can help you upgrade - the changes are not that big I don't think - https://invertase.io/blog/react-native-firebase-versioning

Other than that, a photo of an error is not nearly as useful as a full stack trace from adb logcat after you plug the device into a machine. It's quite possible that this error message has nothing to do with firebase, it could just be an unhandled promise rejection from some part of your code, but it's impossible to say from the information provided, and it is hard to say with older software as it may be some bug that's already fixed

So - upgrade to current version of react-native-firebase, build it for release, run it on your real device while plugged into a machine and run `adb logcat` on it, then see if you can reproduce and capture the full error message, then we can see
