### ISSUE TITLE
[🐛] Bug Report Duplicate fcm push notification in react native android backgroundhandler

### ISSUE THREAD

**Issue by Cazs03** [invertase/react-native-firebase#6267]
Related to [https://stackoverflow.com/questions/71507734/duplicate-fcm-push-notification-in-react-native-android-backgroundhandler](https://stackoverflow.com/questions/71507734/duplicate-fcm-push-notification-in-react-native-android-backgroundhandler)

I getting duplicate notification in background

    "@react-native-firebase/app": "^14.9.4",
    "@react-native-firebase/messaging": "^14.9.4",

**JS React Native**
```
    messaging().onMessage(async remoteMessage => {
      console.log('onMessage: ' + JSON.stringify(remoteMessage));
    });
    messaging().setBackgroundMessageHandler(async remoteMessage => {
      console.log(
        'Message handled in the background!',
        JSON.stringify(remoteMessage),
      );
    });
```

**NodeJS banckend**
```
messaging
    .send({
      notification: { title: 'Price drop', body: 'ioioioio' },
      topic: 'club'
    })
    .then((response) => {
      // Response is a message ID string.
      console.log('Successfully sent message:', response);
    })
```
Error: 
![image](https://user-images.githubusercontent.com/6555389/170264236-06bd271f-62eb-44f9-9ec7-c19fa7c82739.png)

**Comment by mikehardy** [comment]
Hi there!
Please strip the code repro snippets down to just an index.js and App.js that do *nothing* but show exactly how you reproduce this problem.

Please note that if you include a notification block in the FCM you send, the firebase-android-sdk *will* display a notification. Period. Every time. Outside of your control. You will not be able to disable it.

So then if you *also* pop a notification using some other code that you are not showing, you'll get two.

Every time these have been investigated it has been a combination of that fact not being fully understand and then - with the new understanding - detecting API mis-use and altering project code.

It never results in changes in this library and is not actionable here - to set expectations

**Comment by Cazs03** [comment]
Hello, but I did not understand you with the answer.
Do you want me to reduce the code to the most basic?
Or expand information with more code?
