### ISSUE TITLE
RNFirebase.m:2:9: 'FirebaseCore/FirebaseCore.h' file not found

### ISSUE THREAD

**Issue by adamfisher** [invertase/react-native-firebase#627]
### Issue

I have followed the installation guide exactly. I got Android configured but iOS is being more temperamental. When I attempt to build it in XCode I get the following error inside the `RNFirebase` Xcode project. 

```
<RN project root>/node_modules/react-native-firebase/ios/RNFirebase/RNFirebase.m:2:9: 
'FirebaseCore/FirebaseCore.h' file not found
```

![screen shot 2017-11-16 at 10 55 17 am](https://user-images.githubusercontent.com/1834711/32900980-b283eb54-cabc-11e7-92f6-e11af06d7629.png)

The one deviation I made was to use the [Integrate without CocoaPods](https://firebase.google.com/docs/ios/setup) procedure which involves manually linking the Frameworks to your XCode project so I followed the Firebase readme to link the proper framework packages. That solved my initial error of the Firebase.h header file not being found by my AppDelegate file but now I just need to get past this error of the actual RNFirebase XCode project not seeing the framework.

![screen shot 2017-11-16 at 11 00 47 am](https://user-images.githubusercontent.com/1834711/32901268-71ac765e-cabd-11e7-9c9b-835d0f3bf32e.png)

I tried rerunning the `react-native link command` but that yielded no fruit and it seems like it would be bad for me to manually go in and link it. 

![screen shot 2017-11-16 at 11 03 39 am](https://user-images.githubusercontent.com/1834711/32901480-e51fea58-cabd-11e7-92ed-50f26dc29166.png)

So how do I get the RNFirebase project to see the framework files? The `#import <FirebaseCore/FirebaseCore.h>` statement is causing the issue.

### Environment

- **OS:**  macOS Sierra 10.12.6
- **Node:**  7.9.0
- **Yarn:**  1.0.2
- **npm:**  5.5.1
- **Watchman:**  4.7.0
- **Xcode:**  Xcode 9.1 Build version 9B55
- **react:** 16.0.0-beta.5
- **react-native:** 0.49.5
- **RNFirebase Version:** 3.1.0
- **Firebase Module:** N/A

**Comment by chrisbianca** [comment]
@adamfisher This might be an oversight on our part - the support for standalone frameworks has been merged but not released, even though the docs have been updated.

Could you try installing from the latest version and seeing if that works:

`npm install --save https://github.com/invertase/react-native-firebase`

**Comment by adamfisher** [comment]
I ran the following commands but I still get the same error during build in XCode. I made sure to do a clean and then complete rebuild.

```
6000760mac:MobileApp user1$ yarn add https://github.com/invertase/react-native-firebase

yarn add v1.0.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native-firebase@3.1.0" has incorrect peer dependency "fbjs@*".
warning "babel-jest@21.2.0" has incorrect peer dependency "babel-core@^6.0.0 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0".
[4/4] 📃  Building fresh packages...
success Saved 1 new dependency.
└─ react-native-firebase@3.1.0
✨  Done in 4.75s.


6000760mac:MobileApp user1$ react-native link react-native-firebase

Scanning folders for symlinks in <RN Project Root>/node_modules (7ms)
rnpm-install info Android module react-native-firebase is already linked
rnpm-install info iOS module react-native-firebase is already linked
rnpm-install info Linking assets to ios project
rnpm-install info Linking assets to android project
rnpm-install info Assets have been successfully linked to your project
```

**Comment by chrisbianca** [comment]
Which directory have you added your frameworks to?

**Comment by adamfisher** [comment]
They are in the root of the ios folder that React Native creates.

**Comment by chrisbianca** [comment]
Try popping them in a Firebase folder as explained in the docs: https://rnfirebase.io/docs/v3.1.*/installation/ios#4.-Setup-Firebase-Pods

**Comment by adamfisher** [comment]
🤦‍♂️ Oh man that was easy. Thank you so much! creating a `Firebase` folder at the root of the ios folder and adding them into there did the trick! Thank you.

**Comment by chrisbianca** [comment]
No problem, glad it worked!!

**Comment by BricePissard** [comment]
Still getting this error.

By placing the frameworks within a Firebase folder at the root of the ios folder you mean this conf?
![screen shot 2017-11-22 at 8 57 39 am](https://user-images.githubusercontent.com/4115874/33116059-9053d4d0-cf63-11e7-9445-1fb03f8cb6a9.png)

**Comment by mtx62** [comment]
I'm having the same issue.

**Comment by tirrorex** [comment]
@chrisbianca your fix is not possible for people with npm 5 since npm 5 break post_install script making the install from source not possible.
When do you guys plan on releasing the new build?

**Comment by chrisbianca** [comment]
@tirrorex which fix?

**Comment by tirrorex** [comment]
@chrisbianca building the library from the source.

Anyway, could you guys describe in detail what we should do if we cannot use cocoapods.
Is the folder Firebase at the root of the project enough, should we have a subfolder in it, do we drop all the libraries in the ios project or the folder, do we have to set a custom header search path either for the ios project target or the pods target etc...

Currently stuck with this and unfortunatly i don't think i am the only one.

**Comment by uc-asa** [comment]
I have the same issue what should I do please suggest.

![image](https://user-images.githubusercontent.com/16412197/34704272-15bb5da2-f51e-11e7-995e-d8fbceb0d7fe.png)

**Comment by pilot4u** [comment]
we are experiencing the same issue
tried integrating using:
pod "Firebase/Core"
as described here: https://rnfirebase.io/docs/v3.1.*/installation/ios#4.-Setup-Firebase-Pods
but the problem wasn't solved
anybody managed to solve this issue?

**Comment by esutton** [comment]
+1 Same issue on iOS. FirebaseCore/FirebaseCore.h not found

Install from latest did not help:
````
npm install --save https://github.com/invertase/react-native-firebase
````

**Comment by esutton** [comment]
Solved.  

- Make sure your pods are updated and installed.
- Fix any pods errors.  I had a missing target target 'MyAppTests'.  Once I removed, all was  good.

Using:
````
		"react": "^16.2.0",
		"react-native": "^0.51.0",
		"react-native-firebase": "^3.2.2",
````

My podfile is using:
````
platform :ios, '9.3'
````
One of these commands help fix the 'FirebaseCore.h' not found.
````
cd ios
pod outdated
pod  update
pod install
````

**Comment by policz** [comment]
i have configured firebase for my react-native app "only for android part" it works really cool, But when i run my project to get the new build the Xcode throws some issues while building the app "though i haven't configured firebase for ios part"

please find the attachments 
<img width="1413" alt="issue2" src="https://user-images.githubusercontent.com/6464037/38750517-30324138-3f23-11e8-83dc-488c309ce28e.png">
<img width="1393" alt="issue1" src="https://user-images.githubusercontent.com/6464037/38750518-303d1220-3f23-11e8-99c2-b6efd9cf61da.png">

**Comment by GoNishant** [comment]
@policz 
Hello, I am facing the same issue. Do you get any solution?

Inside RNFirebaseUtil.h file , 'Firebase.h' file not found error occur.

![screen shot 2018-05-22 at 12 46 51 pm](https://user-images.githubusercontent.com/39513891/40347531-449fd4f0-5dbe-11e8-9d53-3ebb36e3948b.png)

**Comment by somsin** [comment]
i am also facing same issue

**Comment by r00li** [comment]
In my experience deleting the Pods directory and Porfile.lock, then running 'pod install' again will fix this issue. But I don't know why it appears in the first place and how to permanently resolve it.

**Comment by oferRounds** [comment]
Did anyone find solution? Facing the same issue

**Comment by r00li** [comment]
I eventually did. I gave up on Cocoapods installation after the problem kept coming back, and just included Firebase manually (look at the Firebase installation guide). After that no more issues.

**Comment by oferRounds** [comment]
Thanks @r00li!
Actually I was just able to solve it (finally) by removing the `use_frameworks` from the pod file, while using a 1.5+ version of cocoa pods, and adding the `, :modular_headers => true` for specific pods which depends on Obj-C code.

More info can be found here:
http://blog.cocoapods.org/CocoaPods-1.5.0/

**Comment by bhavneet0812** [comment]
**Solved**

Install  **pod 'FirebaseCore'** instead of **pod 'Firebase/Core'**

**Comment by manjuy124** [comment]
@bhavneet0812 
I think your solution is not working. RNFirebase Version v5.x.x

**Comment by anniewey** [comment]
I'm getting the same error **only in CI** no matter what pod version I used. Tried: 4.11/4.13/latest ver still same.

```
pod 'Firebase/Core'
pod 'Firebase/Messaging'
```

`/Users/vagrant/git/node_modules/react-native-firebase/ios/RNFirebase/RNFirebaseUtil.h:6:9: 'Firebase.h' file not found`

**Comment by alexxsanchezm** [comment]
> I eventually did. I gave up on Cocoapods installation after the problem kept coming back, and just included Firebase manually (look at the Firebase installation guide). After that no more issues.

I did the same, but the issue is still there. I've read the installation guide(many times).
I had a pod configuration for other dependencies, but I removed the Pod settings. Maybe Im missing something.

Any place to look at? or configuration I might be doing wrong?

**Comment by tenchoklang** [comment]
Having the same problem while installing it manually.
<img width="1440" alt="screen shot 2019-01-24 at 4 13 14 pm" src="https://user-images.githubusercontent.com/26011251/51709033-5f6cf180-1ff3-11e9-8553-0950cc6a4f2d.png">
<img width="1440" alt="screen shot 2019-01-24 at 4 14 37 pm" src="https://user-images.githubusercontent.com/26011251/51709041-64ca3c00-1ff3-11e9-97b2-f1255806876d.png">

**Comment by alexxsanchezm** [comment]
@tenchoklang You don't need to add the header file "Firebase.h" to Link Binary With Libraries, you should even remove it from there. But if your followed the manual installation steps you had been thru this steps:

1. yarn add react-native-firebase
2. Download the fat Firebase SDK
3. Drag all the frameworks in Analytics, select copy if needed, select the target too
4. Drag the header file Firebase.h to your project.
4. run `react-native link react-native-firebase`
5. Add the initialization code to your app delegate.

I don't know the reason you choose to do it manually, personally I'm not fan of use cocoapods, but I admit it has lots of benefits, so if you don't want to get a headache as me 3 days ago, you should use pods.

**Comment by tenchoklang** [comment]
I was told not to use cocoapods at work. I was able to SOLVE the issue by following the steps here [](https://github.com/invertase/react-native-firebase/issues/1016)
