### ISSUE TITLE
[🔥] onDisconnect not doing anything

### ISSUE THREAD

**Issue by pierroo** [invertase/react-native-firebase#6285]
## Issue

I am trying to build a presence system following the docs.
very simply I have the following:

```
const amOnline = database().ref(`.info/connected`)
    const presenceRef = database().ref(`users/${user.uid}/watchers`)
    amOnline.on('value', (snapshot) => {
      if (snapshot.val()) {
        console.log('connected val: ', snapshot.val())
        presenceRef.onDisconnect().update({ isOnline: false })
      } else {
        console.log('COMING OFFLINE')
      }
    });
```

I can clearly see the "connected val: true" in my console.log; but the onDisconnect() update is NEVER called (trying to force close the app, close properly, close internet, etc)
Also, the else "coming offline" log is also never triggered.

I am using firebase for years, everything else is working fine, so it's really just the onDisconnect that seems void.
I'm trying on an emulator (again, every other firebase implementation, database accesses / updates / etc work fine)

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 14.9.1
- **`Firebase` module(s) you're using that has the issue:**
  - firebase database
- **Are you using `TypeScript`?**
  - No

**Comment by mikehardy** [comment]
Your code differs from our docs. It might be valid or it might not.

Please make an app.js that uses our example code exactly as a minimal viable reproduction. Make a button that goes offline and online and a text in a view that prints status.

**Comment by pierroo** [comment]
Sorry I should have mentioned I did try the code from your doc as follow:

const reference = database().ref(`/users/${user.uid}/watchers/isOnline`);
    reference.set(true).then(() => console.log('Online presence set'));

    // Remove the node whenever the client disconnects
    reference
      .onDisconnect()
      .remove()
      .then(() => console.log('On disconnect function configured.'));

set(true) gets triggered as expected;
but the onDisconnect() never does; it litterally does nothing and never gets triggered, even with a button and goOffline()

it should be working on an emulator as well, right?

**Comment by mikehardy** [comment]
Our e2e test harness runs on emulators, you can see our harness setup in .github/workflows here, it's all open, every single line of source and infrastructure for the whole project

You keep showing snippets - https://stackoverflow.com/help/mcve 

>  Please make an app.js that uses our example code exactly as a minimal viable reproduction. Make a button that goes offline and online and a text in a view that prints status.

Also you hacked up our issue template and did not provide all the info we ask for, perhaps forgivable but it decreases quality of support. https://stackoverflow.com/help/how-to-ask

If there were an app.js I could perhaps drop it in our test project and examine. But I can't really help when just tossing snippets around with assertions of not working and no full spec of test environment or versions etc.
