### ISSUE TITLE
ref.update() only works when trying to update existing data

### ISSUE THREAD

**Issue by wbattel4607** [invertase/react-native-firebase#630]
### Issue

If this is my database structure...
```
└─ users
   └─ foobar
      └─ existingProperty: 'hello, world!'
```

This works:
```
Firebase.database().ref('users/' + uid).update({
    existingProperty: 'lalalalalala'
}).then(() => {
    console.log('Updated user');
});
```
This does not work! :(
```
Firebase.database().ref('users/' + uid).update({
    existingProperty: 'lalalalalala',
    newProperty: 'hahahahaha'
}).then(() => {
    console.log('Updated user');
});
```

I'm referencing the [update function on the Database documentation](https://rnfirebase.io/docs/v3.1.*/database/reference/Reference#update), which doesn't say that it won't work for new properties (at least I don't see anywhere it says that).
### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS High Sierra

3. Build Tools: Xcode 9.1, iOS 11.1

4. React Native version: 0.50.3

5. RNFirebase Version: 3.1.0

6. Firebase Module: Database

**Comment by wbattel4607** [comment]
Nevermind, it was an oversight on my part. Apologies for any inconvenience.

**Comment by arminsal1** [comment]
@wbattel4607 What was your oversight? I'm having the same issue
