### ISSUE TITLE
ad_impression event needs to be removed from reserved events list

### ISSUE THREAD

**Issue by alexpovkolas** [invertase/react-native-firebase#6307]
## Issue

Currently ad_impression event is [reserved](https://rnfirebase.io/analytics/usage#reserved-events) so when an app tries to log it RNFirebase throws an exception.

But according to [Google docs](https://firebase.google.com/docs/analytics/measure-ad-revenue#unity_1) it is possible to track impression level manually for non-google monetization platforms

The following [line](https://github.com/invertase/react-native-firebase/blob/ee740f80501fdd2ea5184515c4840340fca55e63/packages/analytics/lib/index.js#L43) needs to be removed 

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Interesting! We have a couple other carve-outs (items from the reserved list https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event) that we pass and despite being reserved, they do work for various reasons.

Can you verify for me that when you reach into node_modules and comment that line out, you are able to log things as you need according to the link you included? https://firebase.google.com/docs/analytics/measure-ad-revenue#unity_1

**Comment by alexpovkolas** [comment]
Yip It works. I have ad_impression events in a firebase console and "Publisher ad impressions	
  by Ad unit" report. It looks the same as automatically tracked events from AdMob

**Comment by mikehardy** [comment]
Fantastic - thanks for verifying - looks like we have another carve-out then :-)

I have quite a few react-native-firebase environments but each of them has a separate sizable chunk of work unpacked in them and in progress so it might be a little bit before I get to this.

If you want to cut that time down and get this changed+released now, you could do a PR that comments that out with a comment next to it saying "manual tracking on this reserved word is allowed #6307" as a helper for any curious future code explorers.

Otherwise I'll make the change it just might take a bit. Thanks!
