### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by ericmager** [invertase/react-native-firebase#6309]
I can't figure this out for the life of me. I've been trying for a few days now. Auth seems to work (I can add a new user), but when I try to hit the database I get the below error(I simplified the query):

```
[Unhandled promise rejection: TypeError: undefined is not a function (near '...this._firestore.native.collectionGet...')]
at node_modules/@react-native-firebase/firestore/lib/FirestoreQuery.js:194:24 in _firestore.native.collectionGet.then$argument_0
```

```bash
expo prebuild --clean -p ios
expo run:ios    
```

package.json:

```json
  "dependencies": {
    "@gorhom/bottom-sheet": "^4",
    "@react-native-firebase/app": "^14.11.0",
    "@react-native-firebase/auth": "^14.11.0",
    "@react-native-firebase/firestore": "^14.11.0",
    "@react-native-firebase/storage": "^14.11.0",
    "@react-native-google-signin/google-signin": "^7.2.2",
...

app.json:

...json
    "plugins": [
      "@react-native-firebase/app"
    ]
```

js file:

```javascript
import firestore from "@react-native-firebase/firestore";

export const getVideos = async (
) => {

  const documents = await firestore().collection("videos").get();

  console.log(documents)
...

**Comment by mikehardy** [comment]
Sorry, I wish I could help but I don't use Expo - it has historically had lots of problems with native modules, like you are having now, so I have always avoided it. I understand with EAS and prebuild and such it is supposed to be better now, but here you are with a mis-integration where the firestore module javascript is installed but the native code is not. Why? I wish I knew

**Comment by ericmager** [comment]
Thanks for taking a look Mike. I'll close this out
