### ISSUE TITLE
Should we remove database key logging on android ?

### ISSUE THREAD

**Issue by peteroid** [invertase/react-native-firebase#631]
### Issue

The keys of the database are logged when using ref.once('value') in the app. The corresponding line should be [here](https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabaseReference.java#L146).

As the keys may contain the user id or other sensitive data, should we remove the key logging at least in release build of the app?

The example of the `adb logcat` output is like below.
<img width="783" alt="screen shot 2017-11-20 at 3 14 37 pm" src="https://user-images.githubusercontent.com/12689188/33006548-b191ce86-ce05-11e7-876d-4237cfbbac3f.png">

### Environment

1. Application Target Platform: 
Android

2. Development Operating System: 
macOS High Sierra

3. Build Tools: 
Android SDK v26

4. React Native version: 
0.49.5

5. RNFirebase Version: 
3.1.0

6. Firebase Module: 
database

**Comment by Ehesp** [comment]
Hey, this is just a [debug](https://developer.android.com/reference/android/util/Log.html#d(java.lang.String, java.lang.String)) Log which won't show in production builds :)

**Comment by peteroid** [comment]
Oh, my bad. I think I was messing around the debug and release build. Thanks for the information anyway.
