### ISSUE TITLE
[🐛] The Android platform was not approved for the app market because get ANDROID_ID (resolution: firebase-android-sdk issue)

### ISSUE THREAD

**Issue by huangnan78100** [invertase/react-native-firebase#6327]
"stackTrace":["com.google.firebase.crashlytics.internal.common.CommonUtils.isEmulator(CommonUtils.java:404)","com.google.firebase.crashlytics.internal.common.CommonUtils.getDeviceState(CommonUtils.java:456)","com.google.firebase.crashlytics.internal.common.CrashlyticsController.createDeviceData(CrashlyticsController.java:690)","com.google.firebase.crashlytics.internal.common.CrashlyticsController.doOpenSession(CrashlyticsController.java:548)","com.google.firebase.crashlytics.internal.common.CrashlyticsController.access$600(CrashlyticsController.java:55)","com.google.firebase.crashlytics.internal.common.CrashlyticsController$7.call(CrashlyticsController.java:486)","com.google.firebase.crashlytics.internal.common.CrashlyticsController$7.call(CrashlyticsController.java:483)","com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(CrashlyticsBackgroundWorker.java:105)","[com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.1:3)](mailto:com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.1:3))","java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)",

**Comment by mikehardy** [comment]
I'm sorry, this is outside our control. You will want to follow along on this bug https://github.com/firebase/firebase-android-sdk/issues/3826

...and as soon as there is resolution there, you may use the new version of crashlytics by overriding the BoM as described here: https://rnfirebase.io/#android

**Comment by huangnan78100** [comment]
Thanks for your reply

**Comment by mikehardy** [comment]
This must be the Huawei market yes? I think they are the ones enforcing this right now, I just did a build to Play Store and it worked. Regardless - I can share that google is aware of the issue and they're trying to get a fix out as quickly as possible. That is still not a committed deadline or anything - apologies, in the meantime I suppose all you can do if you *must* do a release is temporarily remove crashlytics. That seems drastic but if you must make a release you must make one.

As soon as google releases a new firebase-android-sdk release (watch here: https://firebase.google.com/support/release-notes/android) that mentions this change, you can use that override link https://rnfirebase.io/#android I posted above to adopt it

**Comment by huangnan78100** [comment]
> This must be the Huawei market yes? I think they are the ones enforcing this right now, I just did a build to Play Store and it worked. Regardless - I can share that google is aware of the issue and they're trying to get a fix out as quickly as possible - it is already committed and just not in a tagged release yet - [firebase/firebase-android-sdk@e17dcac](https://github.com/firebase/firebase-android-sdk/commit/e17dcac60a3abc3d056d0878f60022af6d89ffd1).
> 
> That is still not a committed deadline or anything for the release - apologies, in the meantime I suppose all you can do if you _must_ do a release is temporarily remove crashlytics. That seems drastic but if you must make a release you must make one.
> 
> As soon as google releases a new firebase-android-sdk release (watch here: https://firebase.google.com/support/release-notes/android) that mentions this change, you can use that override link https://rnfirebase.io/#android I posted above to adopt it

yes huawei, What about the way you're talking about（ https://rnfirebase.io/#android ） in my file

my android/build.gradle:


// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 23
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
        kotlin_version = "1.6.0"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.2")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'

    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url(new File(["node", "--print", "require.resolve('react-native/package.json')"].execute().text.trim(), "../android"))
        }
        maven {
            // Android JSC is installed from npm
            url(new File(["node", "--print", "require.resolve('jsc-android/package.json')"].execute().text.trim(), "../dist"))
        }

        google()
        maven { url 'https://www.jitpack.io' }
        jcenter()
    }
}

**Comment by huangnan78100** [comment]
> I'm not sure I fully understand your questino and it is hard to read with the formatting missing?
> 
> If you are asking "how exactly do I override the version", you would do something like this:
> 
> https://github.com/mikehardy/rnfbdemo/blob/ce416bfaa462e012fa4b4a7fdeab727c34fd7392/make-demo.sh#L87
> 
> But with whatever they call the version that releases the fix. **They have not released the fix yet though, so we have to wait for the release**.

ok👌

**Comment by mikehardy** [comment]
Official word on linked issue is the release is scheduled for July 14th, until then the only workaround I can think of that will enable a successful review+release on Huawei app store would be temporary de-integration of crashlytics. This is a project-specific business decision to make - wait + update-with-BoM-override and release on or after July 14th, or temporariliy-de-integrate + release now

**Comment by huangnan78100** [comment]
> Official word on linked issue is the release is scheduled for July 14th, until then the only workaround I can think of that will enable a successful review+release on Huawei app store would be temporary de-integration of crashlytics. This is a project-specific business decision to make - wait + update-with-BoM-override and release on or after July 14th, or temporariliy-de-integrate + release now

谢谢，我明白了你的意思，🙏

**Comment by huangnan78100** [comment]
> Official word on linked issue is the release is scheduled for July 14th, until then the only workaround I can think of that will enable a successful review+release on Huawei app store would be temporary de-integration of crashlytics. This is a project-specific business decision to make - wait + update-with-BoM-override and release on or after July 14th, or temporariliy-de-integrate + release now

可以升级30.2.0了吗？

**Comment by mikehardy** [comment]
It looks like 30.2.0 does not have it, and neither does 30.3.0 - hopefully it will be very soon

**Comment by huangnan78100** [comment]
> It looks like 30.2.0 does not have it, and neither does 30.3.0 - hopefully it will be very soon

👌，希望快点，我们已经发两个版本了。

**Comment by huangnan78100** [comment]
> It looks like 30.2.0 does not have it, and neither does 30.3.0 - hopefully it will be very soon

我是不是可以更新到30.3.1版本了

**Comment by mikehardy** [comment]
PR #6433 is going through CI now and I intend to release it the first chance I get after CI is green, should be a half hour or so if everything goes through first time, will be version v15.3.0 when it releases

**Comment by huangnan78100** [comment]
> PR #6433 is going through CI now and I intend to release it the first chance I get after CI is green, should be a half hour or so if everything goes through first time, will be version v15.3.0 when it releases

👌👌
