### ISSUE TITLE
Add support for the new 'multi-database' firebase feature

### ISSUE THREAD

**Issue by Salakar** [invertase/react-native-firebase#634]
We've been tracking this for a while, this issue is purely for 'todo' purposes.

Reference: http://firebase.googleblog.com/2017/11/easier-scaling-with-multi-database.html

**Web SDK**: https://firebase.google.com/docs/reference/js/firebase.database
```
firebase.database() can be called with no arguments to access the default app's 
Database service or as firebase.database(app) or firebase.database(URL) to access
the Database service associated with a specific app or database URL.
```
```javascript
firebase.database(url);
```

**Android SDK**: https://firebase.google.com/docs/reference/android/com/google/firebase/database/FirebaseDatabase.html#getInstance(java.lang.String)
```java
public static FirebaseDatabase getInstance (String url)
// Gets a FirebaseDatabase instance for the specified URL.
// ..
FirebaseDatabase.getInstance(url);
```

**iOS SDK**: https://firebase.google.com/docs/reference/ios/firebasedatabase/api/reference/Classes/FIRDatabase#databasewithurl
```obj-c
+ (nonnull FIRDatabase *)databaseWithURL:(nonnull NSString *)url;
// ...
[FIRDatabase databaseWithURL:url]
```

**Comment by akshetpandey** [comment]
@chenjh1992 : ^

**Comment by Salakar** [comment]
@akshetpandey @Chenjh1992 - contributions welcome 👍

**Comment by Chenjh1992** [comment]
@Salakar The implementation is: passing a dbURL associated with appName so it can support multiple apps or multiple shard databases. 
Will create the PR later.

**Comment by Salakar** [comment]
See PR #649
