### ISSUE TITLE
remote config not work in android with version 5.6.0

### ISSUE THREAD

**Issue by Doomshell2022** [invertase/react-native-firebase#6343]
app crashes when app runs in android but its run in iOS perfectly 

In android it shows firebase.config().enableDeveloperMode() null and app crashes 

 i m using these dependancies 

  //    Firebase
    implementation platform('com.google.firebase:firebase-bom:30.2.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation("com.google.firebase:firebase-iid")
    implementation project(':react-native-firebase')
    implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation "com.google.firebase:firebase-core:16.0.9"
    implementation "com.google.firebase:firebase-messaging:18.0.0"
    implementation "com.google.firebase:firebase-config:17.0.0"
    implementation 'me.leolin:ShortcutBadger:1.1.21@aar'
    implementation('com.crashlytics.sdk.android:crashlytics:17.2.2@aar') {
        transitive = true
    }
![Screenshot 2022-06-27 at 1 08 33 PM](https://user-images.githubusercontent.com/103122824/175885921-446cbbd4-c216-4016-85c6-b4ef22cfe1aa.png)

please help me to resolve this issue

**Comment by mikehardy** [comment]
There is no support offered for v5.6.0, it's incredibly old and there is zero chance it will work with modern underlying SDKs.

https://invertase.io/blog/react-native-firebase-versioning

We are on version 15+ now, please update
