### ISSUE TITLE
[📚] Documentation Issue Title - Missing step for firebase appcheck

### ISSUE THREAD

**Issue by pierroo** [invertase/react-native-firebase#6344]
## Documentation Feedback

The rnfirebase documentation for appcheck only mentions yarn install and that's it;
but unfortunately when I try to run my app afterwards it clearly states missing dependencies from the app/build.gradle for android for example, for both:

- implementation 'com.google.firebase:firebase-appcheck-safetynet:16.0.0'
 - implementation 'com.google.firebase:firebase-appcheck-debug:16.0.0'

Which I found mentioned in the official firebase appcheck documentation, but was wondering if rnfirebase should have added those automatically like it did for other firebase installs? (firebase, auth, etc)

**Comment by soundaraj** [comment]
`* What went wrong:
Could not determine the dependencies of task ':react-native-firebase_app-check:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-firebase_app-check:debugCompileClasspath'.
   > Could not find com.google.firebase:firebase-appcheck-safetynet:.
     Required by:
         project :react-native-firebase_app-check
   > Could not find com.google.firebase:firebase-appcheck-debug:.
     Required by:
         project :react-native-firebase_app-check`

**Comment by soundaraj** [comment]
> `* What went wrong: Could not determine the dependencies of task ':react-native-firebase_app-check:compileDebugAidl'.
> 
> > Could not resolve all task dependencies for configuration ':react-native-firebase_app-check:debugCompileClasspath'.
> > Could not find com.google.firebase:firebase-appcheck-safetynet:.
> > Required by:
> > project :react-native-firebase_app-check
> > Could not find com.google.firebase:firebase-appcheck-debug:.
> > Required by:
> > project :react-native-firebase_app-check`

I don't have idea why it was happen....

**Comment by pierroo** [comment]
> 

That is literally the issue I faced.
As explained above, make sure that all your other react-native-firebase/app & auth & etc are up to date (15.0.0)

**Comment by soundaraj** [comment]
@pierroo all of them was updated, but still i have this issue

**Comment by pierroo** [comment]
@soundaraj can you share your package.json?
did you clean/rebuilt the project?
Did you try uninstalling/reinstalling appcheck?

it could be that a dependency was missed during the installation?

**Comment by soundaraj** [comment]
@pierroo I find out the problem,  "\node_modules\@react-native-firebase\app-check\android\build.gradle" in this file they missing to mention the version of the dependencies. anyway thanks man.

**Comment by pierroo** [comment]
that's indeed exactly what I meant about the missing dependency upon missed installation; often the uninstall / reinstall fix this kind of issue.
Glad you found it :)

**Comment by mikehardy** [comment]
> @soundaraj  "\node_modules@react-native-firebase\app-check\android\build.gradle" in this file they missing to mention the version of the dependencies. anyway thanks man.


We no longer need the versions since AppCheck is out of beta and the versions are now specified in the dependencies.

Git blame is a neat trick:

https://github.com/invertase/react-native-firebase/blame/main/packages/app-check/android/build.gradle

https://github.com/invertase/react-native-firebase/commit/c5e6b41eaec0d7238665495caf3e0f9572427e1e

> AppCheck no longer beta, app distribution available, but it is beta, adjust deps

If you are not overriding your BoM to something < firebase-android-sdk BoM 30, you don't need the deps anymore. If you are overriding it then you are responsible for handling compatibility issues as that is a supported method of overriding just in case people need it for emergency patches etc but opens you up to your own compatibility issues which you have to support yourself.
