### ISSUE TITLE
module 'FirebaseCore' not found @import FirebaseCore;

### ISSUE THREAD

**Issue by longjiecn** [invertase/react-native-firebase#6354]
CompileC /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/Objects-normal/x86_64/FIRInstallationsStoredAuthToken.o /Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredAuthToken.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'FirebaseInstallations' from project 'Pods')
    cd /Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods
    export LANG\=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios11.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=c99 -fobjc-arc -fobjc-weak -fmodules -fmodules-cache-path\=/Users/tuitui/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/tuitui/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version\=2 -fobjc-legacy-dispatch -index-store-path /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Index/DataStore -iquote /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/FirebaseInstallations-generated-files.hmap -I/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/FirebaseInstallations-own-target-headers.hmap -I/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/FirebaseInstallations-all-non-framework-target-headers.hmap -ivfsoverlay /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/all-product-headers.yaml -iquote /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/FirebaseInstallations-project-headers.hmap -I/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Products/Debug-iphonesimulator/FirebaseInstallations/include -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Private -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Private/FirebaseInstallations -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/FirebaseCore -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/FirebaseCoreDiagnostics -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/FirebaseInstallations -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/GoogleDataTransport -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/GoogleUtilities -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/PromisesObjC -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/nanopb -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/FirebaseInstallations -I/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/DerivedSources-normal/x86_64 -I/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/DerivedSources/x86_64 -I/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/DerivedSources -F/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Products/Debug-iphonesimulator/FirebaseInstallations -fmodule-map-file\=/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Products/Debug-iphonesimulator/FirebaseCoreInternal/FirebaseCoreInternal.modulemap -fmodule-map-file\=/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/FBLPromises/PromisesObjC.modulemap -fmodule-map-file\=/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/GoogleUtilities/GoogleUtilities.modulemap -MMD -MT dependencies -MF /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/Objects-normal/x86_64/FIRInstallationsStoredAuthToken.d --serialize-diagnostics /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/Objects-normal/x86_64/FIRInstallationsStoredAuthToken.dia -c /Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredAuthToken.m -o /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/Objects-normal/x86_64/FIRInstallationsStoredAuthToken.o -index-unit-output-path /Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/Objects-normal/x86_64/FIRInstallationsStoredAuthToken.o
In file included from /Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredAuthToken.m:19:
In file included from /Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/FIRInstallationsLogger.h:19:
/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/FirebaseInstallations/FirebaseCore/Extension/FirebaseCoreInternal.h:15:9: fatal error: module 'FirebaseCore' not found
@import FirebaseCore;
 ~~~~~~~^~~~~~~~~~~~
/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/Objects-normal/x86_64/FIRInstallationsStoredAuthToken.dia:1:1: warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'FirebaseInstallations' from project 'Pods')

CompileC /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/Objects-normal/x86_64/FIRInstallationsStore.o /Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStore.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'FirebaseInstallations' from project 'Pods')
    cd /Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods
    export LANG\=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios11.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=c99 -fobjc-arc -fobjc-weak -fmodules -fmodules-cache-path\=/Users/tuitui/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/tuitui/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version\=2 -fobjc-legacy-dispatch -index-store-path /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Index/DataStore -iquote /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/FirebaseInstallations-generated-files.hmap -I/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/FirebaseInstallations-own-target-headers.hmap -I/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/FirebaseInstallations-all-non-framework-target-headers.hmap -ivfsoverlay /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/all-product-headers.yaml -iquote /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/FirebaseInstallations-project-headers.hmap -I/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Products/Debug-iphonesimulator/FirebaseInstallations/include -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Private -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Private/FirebaseInstallations -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/FirebaseCore -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/FirebaseCoreDiagnostics -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/FirebaseInstallations -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/GoogleDataTransport -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/GoogleUtilities -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/PromisesObjC -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/nanopb -I/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/FirebaseInstallations -I/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/DerivedSources-normal/x86_64 -I/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/DerivedSources/x86_64 -I/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/DerivedSources -F/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Products/Debug-iphonesimulator/FirebaseInstallations -fmodule-map-file\=/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Products/Debug-iphonesimulator/FirebaseCoreInternal/FirebaseCoreInternal.modulemap -fmodule-map-file\=/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/FBLPromises/PromisesObjC.modulemap -fmodule-map-file\=/Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/Headers/Public/GoogleUtilities/GoogleUtilities.modulemap -MMD -MT dependencies -MF /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/Objects-normal/x86_64/FIRInstallationsStore.d --serialize-diagnostics /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/Objects-normal/x86_64/FIRInstallationsStore.dia -c /Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStore.m -o /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/Objects-normal/x86_64/FIRInstallationsStore.o -index-unit-output-path /Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/Objects-normal/x86_64/FIRInstallationsStore.o
/Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/Objects-normal/x86_64/FIRInstallationsStore.dia:1:1: warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'FirebaseInstallations' from project 'Pods')


2022-06-30 17:52:13.984 xcodebuild[17875:1457977] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-06-30 17:52:13.984 xcodebuild[17875:1457977] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
** BUILD FAILED **


The following build commands failed:
        CompileC /Users/tuitui/Library/Developer/Xcode/DerivedData/VirgoCXApp-ahobtzpqcaeqoibwdvqwdxiwzhfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/Objects-normal/x86_64/FIRInstallationsStoredItem.o /Users/tuitui/Desktop/code/VirgoCXApp/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredItem.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'FirebaseInstallations' from project 'Pods')
(1 failure)

info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by longjiecn** [comment]
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
$RNFirebaseAsStaticFramework = true

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'VirgoCXApp' do
  config = use_native_modules!

    # Flags change depending on the env values.
    flags = get_default_flags()

    # use_frameworks!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,
    :fabric_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  permissions_path  =  '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"

  pod 'GoogleUtilities', :modular_headers => true


  target 'VirgoCXAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  
  # use_flipper!({ 'Flipper' => '0.95.0', 'Flipper-Folly' => '2.6.7', 'Flipper-DoubleConversion' => '3.1.7' })
  use_flipper!()
  # post_install do |installer|
  #   installer.pods_project.build_configurations.each do |config|
  #     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  #     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.2'
  #   end
  #   react_native_post_install(installer)
  # end
  post_install do |installer|
    react_native_post_install(installer)
    # installer.pods_project.build_configurations.each do |config|
    #       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    #       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
    #     end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
  
end

**Comment by longjiecn** [comment]
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 111.44 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.19.1 - /opt/homebrew/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by longjiecn** [comment]
`require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
$RNFirebaseAsStaticFramework = true

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'VirgoCXApp' do
  config = use_native_modules!

    # Flags change depending on the env values.
    flags = get_default_flags()

    # use_frameworks!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,
    :fabric_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  permissions_path  =  '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"

  pod 'GoogleUtilities', :modular_headers => true


  target 'VirgoCXAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  
  # use_flipper!({ 'Flipper' => '0.95.0', 'Flipper-Folly' => '2.6.7', 'Flipper-DoubleConversion' => '3.1.7' })
  use_flipper!()
  # post_install do |installer|
  #   installer.pods_project.build_configurations.each do |config|
  #     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  #     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.2'
  #   end
  #   react_native_post_install(installer)
  # end
  post_install do |installer|
    react_native_post_install(installer)
    # installer.pods_project.build_configurations.each do |config|
    #       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    #       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
    #     end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
  
end`

**Comment by longjiecn** [comment]
`
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
$RNFirebaseAsStaticFramework = true

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'VirgoCXApp' do
  config = use_native_modules!

    # Flags change depending on the env values.
    flags = get_default_flags()

    # use_frameworks!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,
    :fabric_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  permissions_path  =  '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"

  pod 'GoogleUtilities', :modular_headers => true


  target 'VirgoCXAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  
  # use_flipper!({ 'Flipper' => '0.95.0', 'Flipper-Folly' => '2.6.7', 'Flipper-DoubleConversion' => '3.1.7' })
  use_flipper!()
  # post_install do |installer|
  #   installer.pods_project.build_configurations.each do |config|
  #     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  #     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.2'
  #   end
  #   react_native_post_install(installer)
  # end
  post_install do |installer|
    react_native_post_install(installer)
    # installer.pods_project.build_configurations.each do |config|
    #       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    #       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
    #     end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
  
end
`

**Comment by mikehardy** [comment]
Use JDK11
Follow this demonstration: https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
Please follow our template
https://stackoverflow.com/help/how-to-ask

**Comment by matextrem** [comment]
@mikehardy I'm having the same issue but for iOS

**Comment by mikehardy** [comment]
That sounds like "I'm having a different issue" the way I read these things

**Comment by mikehardy** [comment]
Hey thumbs down people please note this was resolved mostly for no template. We can't troubleshoot well without good information. So just metoo-ing it doesn't help. Please open a real iss with details and I will try to help. This issue is closed though

**Comment by LozytskyiA** [comment]
Same issue

I've installed these commands 

<img width="783" alt="image" src="https://user-images.githubusercontent.com/16165863/179551752-2d757a29-be86-4b25-8b4b-b45ae3432abc.png">

After that, I put code into Podfile, because of that error:

## Error 
<img width="953" alt="image" src="https://user-images.githubusercontent.com/16165863/179552629-bfdfe111-4ce4-499f-98cb-b2e142751f45.png">


## Code

<img width="693" alt="image" src="https://user-images.githubusercontent.com/16165863/179551635-99b9f25a-9f67-4886-bb6a-2365f135d251.png">

**Comment by mikehardy** [comment]
@LozytskyiA please open a new issue, please do not post screenshots of code (they don't work well at all on mobile devices, I can't read them well, and even on non-mobile devices I can't refer to them and propose slight changes without re-typing)

Bottom line - please, everyone, open a new issue with full details from our issue template.
