### ISSUE TITLE
[🐛] device uniqueId(user_pseudo_id) corresponds to several different devices

### ISSUE THREAD

**Issue by buynao** [invertase/react-native-firebase#6357]
## Issue

I'm using firebase to import data into bigquery and I'm finding some unusual data.

I set the unique value when reporting the data.

`firebaseAnalytics.setUserId(NativeModules.RNDeviceInfo.uniqueId)`

Then I also learned that firebase internally generates a unique value `user_pseudo_id` based on different devices as well.

My understanding is that either the `user_id` I set or the `user_pseudo_id` set by firebase should be unique to the device and this value is not cross-device, but the current situation is that these two unique values, both correspond to different devices.

![image](https://user-images.githubusercontent.com/11701966/176813578-84520204-a83e-4917-9966-21563da28108.png)

Obviously something is wrong somewhere. Please help me to analyze what is wrong with this issue，thanks

firebase version：

```
    "@react-native-firebase/analytics": "^14.1.0",
    "@react-native-firebase/app": "^14.1.0",
    "@react-native-firebase/crashlytics": "^14.1.0",
    "@react-native-firebase/messaging": "^14.1.0",
    "@react-native-firebase/perf": "^14.1.0",
```

`Android` and `iOS` have a similar problem.

I'm not sure if this is the right place to ask this question.
But this issue has been bothering me for a longer time, and I have sent emails to the FA team to inquire about it, but I have not gotten any feedback.I hope I can get some help here.

**Comment by mikehardy** [comment]
That is very odd - are you certain your bigquery export is okay? Maybe there is a join or something that is over-eager and is filling in values incorrectly

I have not seen anything like you describe when I store uniqueID in firestore personally, but I have *not* exported it to bigquery. Perhaps if you looked in firestore with that uniqueId you could see if firestore data was bad also, to either eliminate or focus on the firestore->bigquery step.

I'm pretty sure the uniqueId value that we get here is actually unique though

**Comment by buynao** [comment]
> 



> That is very odd - are you certain your bigquery export is okay? Maybe there is a join or something that is over-eager and is filling in values incorrectly
> 
> I have not seen anything like you describe when I store uniqueID in firestore personally, but I have _not_ exported it to bigquery. Perhaps if you looked in firestore with that uniqueId you could see if firestore data was bad also, to either eliminate or focus on the firestore->bigquery step.
> 
> I'm pretty sure the uniqueId value that we get here is actually unique though

Thank you for your answer，
By `uniqueId`, do you mean `user_pseudo_id`?
