### ISSUE TITLE
[📚] Problem with Performance Monitoring

### ISSUE THREAD

**Issue by marclpez** [invertase/react-native-firebase#6363]
## Documentation Feedback

Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:

I'm trying to add Performance Monitoring into my project. My project has been developed in React Native with Android Studio to run my application in a device, and when I try to add "const perf = getPerformance(app)" in my file configuration about firebase, I get this error:

Performance: Firebase Performance cannot start if the browser does not support "Fetch" and "Promise", or cookies are disabled.

I've been looking for this error, but I can't find a solution to solve it.

Thanks.

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I'm not sure exactly what you've done or how to reproduce this (https://stackoverflow.com/help/how-to-ask) so I can't say exactly.

I can say that this scripted demonstrator will go from `npx react-native init ...` of a fresh app to a running integration of all react-native-firebase modules including perf, you can see it in action:

https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
