### ISSUE TITLE
after installing npm i @react-native-firebase/app in project it works fine in android but during cd ios and pod install then it give me error and add  $RNFirebaseAsStaticFramework = true, use_modular_headers!  , then pod installed but when i run npx react-native run-ios it gives error 

### ISSUE THREAD

**Issue by ardhendu12345** [invertase/react-native-firebase#6370]
## Issue

Describe your issue here

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by ardhendu12345** [comment]
the too long error produced in log console is Command CompileSwiftSources failed with a nonzero exit code

2022-07-05 16:47:46.163 xcodebuild[11109:198292] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-07-05 16:47:46.163 xcodebuild[11109:198292] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/arindam/Library/Developer/Xcode/DerivedData/DemoChat-cttmfseavejzhadnawolzvwrzelz/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsi.build/Objects-normal/x86_64/JSIDynamic.o /Users/arindam/Documents/test_projects/DemoChat/node_modules/react-native/ReactCommon/jsi/jsi/JSIDynamic.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-jsi' from project 'Pods')
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'YogaKit' from project 'Pods')
(2 failures)

**Comment by mikehardy** [comment]
Hmm, maybe this https://github.com/facebook/react-native/issues/34063

And perhaps a workaround / solution https://apple.stackexchange.com/questions/438785/xcode-error-when-launching-terminal

This does not look related to react-native-firebase, and won't be actionable here, so I sincerely hope those two links work but I'm going to close this as not actionable

If you try those workarounds and they do not work, and you can modify this specific script to reproduce the error so we have a reproduction, then we can reopen https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh - that one starts from scratch and works on android and ios
