### ISSUE TITLE
[🐛]  When using Analytics logEvent, the custom parameter with name 'error_value' not appearing in the Firebase console

### ISSUE THREAD

**Issue by AleCatSS** [invertase/react-native-firebase#6376]
## Issue

Hello there,

we are logging firebase events using some custom parameters. One of this parameter name is 'error_value'. The event is logged correctly in Firebase but 'error_value' parameter doesn't show up and no error/warning is logged (checked in Javascript and XCode console). If I change the error name for example error_value -> error_value_test the parameter is correctly logged.

Is this parameter reserved  at some level? 

Here is a snippet to reproduce the issue:

```
import Analytics from '@react-native-firebase/analytics';

const analytics = Analytics();

analytics.logEvent('my_event',{error_value: 'something bad occurred, try again later'});

```
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

`    "@react-native-firebase/analytics": "14.11.0",
`
#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

From the podfile lock

`  - "RNFBAnalytics (from `../node_modules/@react-native-firebase/analytics`)"
`

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [X] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [X] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>
---

**Comment by mikehardy** [comment]
Hi there! Unfortunately I'm not sure - you might ask on the corresponding upstream SDK for one of the platforms you use (either firebase-android-sdk or firebase-ios-sdk)

**Comment by AleCatSS** [comment]
@mikehardy thanks for your answer. If this can help I experience the same issue on both platforms (I updated the description) so the problem is likely to be before the specific platform SDKs or directly in Firebase.
 I will also try with the upstream SDKs as you suggested.

**Comment by BogdanRad** [comment]
I have the same problem.. @AleCatSS did you find a solution?

**Comment by henryglendening-hh** [comment]
FWIW I'm setting up some new custom dimensions (that I haven't started logging yet), and when picking a parameter that I want to map my dimension to, I'm seeing `error_value` show up in the "Event Parameter" dropdown list. I've never logged that before, soo it may be an undocumented, yet reserved, parameter name.

**Comment by scottbouma** [comment]
Same as @henryglendening-hh .  I'm seeing "error_value" show up in our list of event_params, with the value equal to the name of a different custom parameter.  I am taking this to mean that the Firebase SDK had trouble serializing our custom parameter, and is reporting that to us via the built-in "error_value" param.  So it's probably a reserved name.

**Comment by marouane-tradelab** [comment]
"error_value" is a reserved param. It was previously called firebase_error_value and it's documented here : https://firebase.google.com/docs/analytics/errors?hl=en
