### ISSUE TITLE
linker command.. exist code 1

### ISSUE THREAD

**Issue by MarshMelon** [invertase/react-native-firebase#638]
Help me please, when I archive project, get: 
clang: error: linker command failed with exit code 1 (use -v to see invocation ...

Showing Recent Messages
ld: warning: directory not found for option '-F/Users/devx/care-driver-redesign/care-driver-app/ios/../../../ios/Pods/FirebaseCore'

pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

pod 'Firebase/Core'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Messaging'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'Core',
    'ART',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'GoogleMaps'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

end

**Comment by Salakar** [comment]
@MarshMelon did you cd into your ios directory and run `pod install` ?

**Comment by MarshMelon** [comment]
@Salakar yes.. :(

**Comment by chrisbianca** [comment]
@MarshMelon what version of RNFirebase are you running?

**Comment by MarshMelon** [comment]
@chrisbianca I have latest version.

**Comment by chrisbianca** [comment]
I think the issue is that this:

`/Users/devx/care-driver-redesign/care-driver-app/ios/../../../ios/Pods/FirebaseCore` 

doesn't resolve to the right directory, it will be looking in:

`/Users/devx/ios/Pods/FirebaseCore`

Rather than the correct:

`/Users/devx/care-driver-redesign/care-driver-app/ios/Pods/FirebaseCore` 

You'll need to check your header and framework search paths to see why this is the case

**Comment by MarshMelon** [comment]
I have $(PROJECT_DIR)/../../../ios/Pods/FirebaseCore in Framework search paths non-recursive and nothing in header.

**Comment by MarshMelon** [comment]
Okey , directory for option found , but 
Showing Recent Messages
ld: 515 duplicate symbols for architecture arm64

Showing Recent Messages
ld: 515 duplicate symbols for architecture arm64
