### ISSUE TITLE
[🐛] Notification issue on android 12

### ISSUE THREAD

**Issue by Minhuun** [invertase/react-native-firebase#6380]
Hi all, my app work well on SDK target 30 & below but when i was updated target 31 so app's notification & message did not display in notification center of device.

My library version: "react-native-firebase": "git+https://github.com/smartpayvn/react-native-firebase.git#v5.5.6.2"

Please help me to give some solution for this. 

Thanks you so much!

**Comment by jeveloper** [comment]
Hi there

use the version "^15" and upgrade the setup.

**Comment by mikehardy** [comment]
Yep, no support is available or even possible for v5 react-native-firebase
