### ISSUE TITLE
[🐛] AppCheck can not activate DebugAppCheckProviderFactory in Android 6 API

### ISSUE THREAD

**Issue by manakuro** [invertase/react-native-firebase#6384]
## Issue
The AppCheck activate throws an error when enabling DebugAppCheckProviderFactory in Android 6 API like so.

```
java.lang.IllegalAccessException: Class java.lang.Class<io.invertase.firebase.appcheck.ReactNativeFirebaseAppCheckModule> cannot access  method void com.google.firebase.appcheck.debug.DebugAppCheckProviderFactory.<init>(java.lang.String) of class java.lang.Class<com.google.firebase.appcheck.debug.DebugAppCheckProviderFactory>
```

https://github.com/invertase/react-native-firebase/blob/main/packages/app-check/android/src/main/java/io/invertase/firebase/appcheck/ReactNativeFirebaseAppCheckModule.java#L59-L74

Android 12 is working fine, but Android 7 and Android 8 do not seem to be working as well.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 275.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.8.0 - ~/.nodenv/versions/16.8.0/bin/node
    Yarn: 1.22.11 - ~/.nodenv/versions/16.8.0/bin/yarn
    npm: 7.21.0 - ~/.nodenv/versions/16.8.0/bin/npm
    Watchman: 2022.05.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Chipmunk 2021.2.1 Patch 1 Chipmunk 2021.2.1 Patch 1
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `14.11.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

**Comment by tabitta** [comment]
I have the same issue on Android 8 and 9. On Android 11 it is working fine. I have not tested other versions.

**Comment by mikehardy** [comment]
This seems like something you could log in firebase-android-sdk - they may not be aware and may not be testing all the way down to their minSdkVersion supported

**Comment by mikehardy** [comment]
@tabitta have you pursued this with firebase-android-sdk? I would love it if you could mention this issue as a URL in a comment on the issue you log in firebase-android-sdk to cross link them so I could follow and learn what happened. Thanks

**Comment by manakuro** [comment]
I've created an issue in firebase-android-sdk so we can follow what's going on.

https://github.com/firebase/firebase-android-sdk/issues/3916

**Comment by mikehardy** [comment]
Fantastic - I see they reproduced over there, and they *are* the place that controls this part, so that's a great result. Thanks for doing that

**Comment by mikehardy** [comment]
Sorry for the delay here, I'm just catching up now.

I think we may resolve this temporarily, if they don't want to open up access to that method (which is their absolute right, of course, and may be the right decision really)

If we alter access during the reflective access here:

https://github.com/invertase/react-native-firebase/blob/dc7464325a315091a74027e150de1ba77190e0dd/packages/app-check/android/src/main/java/io/invertase/firebase/appcheck/ReactNativeFirebaseAppCheckModule.java#L64

by changing the constructor accessibility (examples of doing so in this thread https://stackoverflow.com/questions/5629706/java-accessing-private-constructor-with-type-parameters/5629983)

**Comment by mikehardy** [comment]
Just wanted to update that over there they have decided to keep this private.
If this is a use case that people need to support, then the code change proposed in the comment above is the path forward

PRs happily merged
