### ISSUE TITLE
The react-native-firebase/app v15+ installation steps are not clear ..

### ISSUE THREAD

**Issue by ardhendu12345** [invertase/react-native-firebase#6385]
react-native-firebase/app v15+ installation procedure is not clear
Altering CocoaPods to use frameworks
Beginning with firebase-ios-sdk v9+ (react-native-firebase v15+) you must tell CocoaPods to use frameworks.

Open the file ./ios/Podfile and add this line inside your targets:

use_frameworks!
To use Static Frameworks on iOS, you also need to manually enable this for the project with the following global to the top of your /ios/Podfile file:

$RNFirebaseAsStaticFramework = true
 as a result pod installation error and npx react-native run-ios build will failed .. please provide a clear guide  that it will easily install ...the documentaion is not clear ..please help , i am new to react-native..

**Comment by nonuabi** [comment]
Is there a solution without using use_Frameworks!

**Comment by ardhendu12345** [comment]
@nonuabi how you can solve it using use_Frameworks! ..please help..i am new to react-native

**Comment by BaloccoDev** [comment]
Even with react-native 0.69.1 I get The 'Pods-XXXX' target has transitive dependencies that include statically linked binaries: (Flipper-Boost-iOSX and Flipper-RSocket)

**Comment by nonuabi** [comment]
For me, I just add test pods lib into the pod file

>   pod 'Firebase', :modular_headers => true
     pod 'FirebaseCoreInternal', :modular_headers => true
     pod 'GoogleUtilities', :modular_headers => true
     $RNFirebaseAsStaticFramework = true

**Podfile Preview**

<img width="1440" alt="Screenshot 2022-07-14 at 7 07 59 PM" src="https://user-images.githubusercontent.com/63551058/178995657-3b59c47d-c040-49b6-a4a2-44408882e00e.png">

then,  in /ios/{projectName}/AppDelegate.m file,
At the top of the file, import the Firebase SDK:

>  #import <Firebase.h>

Within your existing didFinishLaunchingWithOptions method, add the following to the top of the method:

> 
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
>   // Add me --- \/
>   [FIRApp configure];
>   // Add me --- /\
>   // ...
> }


After adding all these codes, Then I ran 

> pod install --repo-update

Pod installed successfully.
Then I just ran `yarn ios` to build the application for ios
and I came across this errors. 

> 
> In file included from /Users/abhishekverma/planetspark-native/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/FIRInstallationsLogger.h:19:
> /Users/abhishekverma/planetspark-native/ios/Pods/FirebaseInstallations/FirebaseCore/Extension/FirebaseCoreInternal.h:15:9: fatal error: module 'FirebaseCore' not found
> @import FirebaseCore;
>  ~~~~~~~^~~~~~~~~~~~
> 1 error generated.


> The following build commands failed:
> 	CompileC /Users/abhishekverma/Library/Developer/Xcode/DerivedData/GalaxyNativeApp-alzzqmsfruzgslewqslktbywmbbf/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseInstallations.build/Objects-normal/x86_64/FIRInstallationsStoredItem.o /Users/abhishekverma/planetspark-native/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredItem.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'FirebaseInstallations' from project 'Pods')
> (1 failure)



To resolve this error 
copy the path for that file error is occurring 
for me the path is -> /ios/Pods/FirebaseInstallations/FirebaseCore/Extension/FirebaseCoreInternal.h

for there I just remove 
-> @import FirebaseCore; 
this statement and replace with 
-> #import "FirebaseCore/FirebaseCore.h
and over write the change.

then, for me build ran successfully without any error.


🤞🏻
Best of Luck!

**Comment by mikehardy** [comment]
How would you like a script that showed exactly what you need to do - every single thing - with a comment explaining what and why?

https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

That along with our documentation has worked well for me showing people how to do the integration the last couple years, hopefully it helps you move forward.

Right now the only officially supported way to do this is with `use_frameworks!` in your Podfile, though a second style of solution is being investigated here - #6332
