### ISSUE TITLE
Show Android normal notification in system tray when app is in foreground

### ISSUE THREAD

**Issue by kevindavee** [invertase/react-native-firebase#639]
Hi everyone !

I would like to ask if there is a way to show up notification in system tray while the app is in foreground, inside the onMessage() listener
Thanks !

1. Application Target Platform: Android
2. Development Operating System: macOS High Sierra
3. Build Tools: Android Studio
4. React Native version: 0.47.2
5. RNFirebase Version: 3.1.0
6. Firebase Module: messaging

**Comment by Yoruba** [comment]
You can create a local message when app is in foreground. 
This show (pass) the message to the system tray.

```
 firebase.messaging().onMessage((message) => {
      if (message.opened_from_tray) {
        firebase.messaging().createLocalNotification({
          title: message.title,
          body: message.body
      // ... more properties
        })
      }
    })
```

**Comment by kevindavee** [comment]
@Yoruba where can I check the local notification properties ? If I'm not mistaken, I didn't see any reference about local notification in react-native-firebase documentation ?

**Comment by Yoruba** [comment]
You can see it in the [docs of version 2.x](https://rnfirebase.io/docs/v2.2.*/messaging).
It is still working with version 3.x.

**Comment by chrisbianca** [comment]
@kevindavee closing this as @Yoruba's solution should be what you're looking for.
Please also keep an eye on https://github.com/invertase/react-native-firebase/issues/595 which is going to be a big overhaul of messaging and it's docs

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)
