### ISSUE TITLE
[🐛] Unable to upload ios live photo to firebase storage

### ISSUE THREAD

**Issue by cozyqueen** [invertase/react-native-firebase#6390]
## Issue

Currently seeing an issue with uploading live photos to storage. Attempting to do so triggers a storage/unknown error. Upgraded our app to use the latest 15.1.1 release and the underlying reason is 'Can not finalize upload. Current size is 728. Expected final size is 725'. I was able to, in the past, upload live photos with no issue. We are uploading them as a .jpg from the devices which also used to work in the past.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by cozyqueen** [comment]
Just in case anyone has run into this issue, or in general the storage/unknown issues when trying to upload multiple images, it seems to be the size of the images causing this. Compressing the images with react-native-image-resizer seems to have fixed this issue for me.

**Comment by efstathiosntonas** [comment]
In my case nothing works (resizing the image), it just doesn't like live photos and some times photos from iCloud.

**Comment by mikehardy** [comment]
If someone could provide a sample photo that works, and one that does not work, for comparison, that would help advance this

(https://stackoverflow.com/help/mcve / https://stackoverflow.com/help/how-to-ask)

Currently this issue report is really light on details anyone would need for a definitive reproduction

**Comment by mlecoq** [comment]
@mikehardy here you can find 2 pictures (one which works, the other fails) 

https://drive.google.com/drive/folders/1ZTUkZ1DYZ4AEeYvlCzcIvcIDZz9PC_e5?usp=sharing

**Comment by efstathiosntonas** [comment]
@mikehardy I also had this issue on `14.11.1` but with any photo, doesn't matter if live or not. 

This is my upload function:

```ts
const uploadImage = async (
  image: { url: string; width: number; height: number },
  // eslint-disable-next-line @typescript-eslint/default-param-last
  contentType = "image/png",
  path: string
) => {
  const filename = new URI(image.url).filename(); // urijs -> https://www.npmjs.com/package/urijs
  const id = nanoid(12);

  await storage()
    .ref(`users/${currentUser().uid}/${path}/${id}_${filename}`)
    .putFile(image.url, {
      cacheControl: "max-age=31536000",
      contentType
    });

  const url = await storage()
    .ref(`users/${currentUser().uid}/${path}/${id}_${filename}`)
    .getDownloadURL();

  if (!url) {
    notify(
      "Unable to get download link for image file",
      "error",
      "Error while getting image download link for image file"
    );
    throw new Error("Unable to get download link");
  }
  return { url: url.replace(":443", ""), width: image.width, height: image.height };
};
```

The error was something between the lines of: "cannot find storage file ref", when I go back to 14 (I'm working on 2 different versions of my app, one with 15.x and one with 14.x) I'll come back here and paste the proper error message.
