### ISSUE TITLE
[Error: [auth/invalid-app-credential] Invalid token.]

### ISSUE THREAD

**Issue by Aris-ngoy** [invertase/react-native-firebase#6395]
`    "@react-native-firebase/auth": "^15.1.1",
`
the ios simulator is working fine one run on the real device I am getting this error

I have also uploaded the APNs file to firebase console still same issue

**Comment by mikehardy** [comment]
Invalid template, so closing, sorry
You might search issues list, there are others with various misconfigured projects that have seen this. I don't reproduce it myself so please make sure you can reproduce it from https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh before logging a new issue and post a diff to that if needed that exposes the problem
