### ISSUE TITLE
Auto login not working

### ISSUE THREAD

**Issue by santiagofm** [invertase/react-native-firebase#640]
### Issue

I can't get the auto login(that you work by default) to work.
I can login successfully using email & password but then if I close the app and open it back again, `firebase.auth().currentUser` is `undefined`.

I've followed the installation instructions for both the core & auth modules and to use the lib I am just:
```js
import firebase from 'react-native-firebase';

firebase.auth().currentUser
```

I noticed that if I put a breakpoint on the `AppDelegate` -after Firebase is initialized- and inspect `[[FIRAuth auth] currentUser]`, this var is actually set but then accessing from react native yields undefined.
So I guess there's an issue when retrieving the defaultApps' currentUser ?

### Environment
1. Application Target Platform: iOS
2. Development Operating System: macOS Sierra
3. Build Tools: Xcode 9.1, iOS 10.0
4. React Native version: 0.50.3
5. RNFirebase Version: 3.1.0
6. Firebase Module: auth

**Comment by Ehesp** [comment]
Documentation is your friend! https://rnfirebase.io/docs/v3.1.*/auth/reference/auth#onAuthStateChanged

You need to watch for this, as firebase needs to connect to the service first.

Common usage is something like:

```
class App extends React.Component {
  constructor() {
    super();
    this.state = { loading: true, user: null };
  }

  componentDidMount() {
    firebase.auth().onAuthStateChanged((user) => {
      this.setState({ loading: false, user });
    });
 }

  render() {
    if (this.state.loading) return null;

    // handle logic here
  }
}
```

**Comment by Vuinfang** [comment]
Even this is an old question, as a new user to react-native-firebase, I have went through with it today, so just put the solution here in case someone needs help. To keep user auto login, we can use onAuthStateChanged like following:

`import React, { useState, useEffect } from 'react';
import { View, Text } from 'react-native';
import auth from '@react-native-firebase/auth';

function App() {
  // Set an initializing state whilst Firebase connects
  const [initializing, setInitializing] = useState(true);
  const [user, setUser] = useState();

  // Handle user state changes
  function onAuthStateChanged(user) {
    setUser(user);
    if (initializing) setInitializing(false);
  }

  useEffect(() => {
    const subscriber = auth().onAuthStateChanged(onAuthStateChanged);
    return subscriber; // unsubscribe on unmount
  }, []);

  if (initializing) return null;

  if (!user) {
    return (
      <View>
        <Text>Login</Text>
      </View>
    );
  }

  return (
    <View>
      <Text>Welcome {user.email}</Text>
    </View>
  );
}`
