### ISSUE TITLE
module 'FirebaseCore' not found

### ISSUE THREAD

**Issue by LozytskyiA** [invertase/react-native-firebase#6403]
"@react-native-firebase/app": "^15.1.1",
"@react-native-firebase/messaging": "^15.1.1",
"react-native": "^0.68"

<img width="792" alt="image" src="https://user-images.githubusercontent.com/16165863/179554868-e3702552-f54a-4bf0-9d88-c46a27e5863d.png">

I've installed these commands 

<img width="783" alt="image" src="https://user-images.githubusercontent.com/16165863/179551752-2d757a29-be86-4b25-8b4b-b45ae3432abc.png">

After that, I put code into Podfile, because of that error:

## Error 
<img width="953" alt="image" src="https://user-images.githubusercontent.com/16165863/179552629-bfdfe111-4ce4-499f-98cb-b2e142751f45.png">

## Code

<img width="693" alt="image" src="https://user-images.githubusercontent.com/16165863/179551635-99b9f25a-9f67-4886-bb6a-2365f135d251.png">

**Comment by mikehardy** [comment]
Hey @LozytskyiA - thanks for filing a new issue. The images are very difficult to deal with though, in the future unless you are showing an actual graphical difference to some sort of user-visible layout, strongly prefer text, pasted in between triple backticks like

```
this is some text I would like you to look at
```

That said:

Interesting - this smells like: https://github.com/invertase/react-native-firebase/pull/6352

Could you reach in to `node_modules/@react-native-firebase/messaging` and alter `RNFBMessaging.podspec` to include this same line I added in that PR, but to the messaging podspec?

https://github.com/invertase/react-native-firebase/pull/6352/files?diff=unified&w=0#diff-456bfaf2e363b356db0e68d83d3f9cd9c54ffb0cc693ec0e07727f3c1ecdbc99R39

```ruby
  s.dependency          'FirebaseCoreExtension', firebase_sdk_version
```

If you do a `pod install` (or however you install pods) after that and rebuild iOS it should build.

If it builds then you may use https://github.com/ds300/patch-package/ to make the change work for you locally, and propose a PR here to https://github.com/invertase/react-native-firebase/blob/main/packages/messaging/RNFBMessaging.podspec and we can merge and release this fix

**Comment by LozytskyiA** [comment]
@mikehardy Thank You,
Sorry

**Comment by LozytskyiA** [comment]
@mikehardy Hello, I've tried the patch, but this doesn't work for me, I was still getting this error until I made a couple of changes on `Podfile`.

## Before

```
use_flipper!

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
      case target.name
      when 'RCT-Folly'
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
    end
  end
end
```


## After 
```
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

Sorry that I bother you, it works fine now.

**Comment by AyoubAbdellaoui** [comment]
update CocoaPods:

1. run `brew cleanup -d -v `
2. run `brew install cocoapods `
3. run `brew link --overwrite cocoapods`

then add `use_modular_headers!` to your `appname/ios/Podfile`

hope work for you
