### ISSUE TITLE
No known class method for selector 'initiateOnDeviceConversionMeasurementWithEmailAddress:'

### ISSUE THREAD

**Issue by phanindrareddyv** [invertase/react-native-firebase#6424]
I am facing an issue with  React Native FirebaseAnalytics in iOS build. I am trying to run the app on iOS Simulator. I am using $FirebaseSDKVersion = '8.15.0'. "@react-native-firebase/analytics": "^15.2.0", "@react-native-firebase/app": "^15.2.0". Any solution?

RCT_EXPORT_METHOD(initiateOnDeviceConversionMeasurementWithEmailAddress
                  : (NSString *)emailAddress resolver
                  : (RCTPromiseResolveBlock)resolve rejecter
                  : (RCTPromiseRejectBlock)reject) {
  @try {
    [FIRAnalytics initiateOnDeviceConversionMeasurementWithEmailAddress:emailAddress];
  } @catch (NSException *exception) {
    return [RNFBSharedUtils rejectPromiseWithExceptionDict:reject exception:exception];
  }

  return resolve([NSNull null]);
}

**Comment by mikehardy** [comment]
> FirebaseSDKVersion = '8.15.0'.

That's your problem, that's incompatible. You cannot use react-native-firebase v15+ with firebase-ios-sdk < v9, and this symbol appears in v9+

There was a major version bump in react-native-firebase (v14 to v15) on purpose, and it was for this reason (you have to bump firebase-ios-sdk and do some other changes) and that was mentioned in the release notes / CHANGELOG I think

If you line those things up compatibly (either v14 here and firebase-ios-sdk v8, or v15 here and firebase-ios-sdk v9+), you should be fine

**Comment by ildaneta** [comment]
I'm running into the same problem @mikehardy , the `firebase-ios-sdk` installed is `v9.5` and `RNFBAnalytics 18.5.0`
![Screenshot 2023-09-27 at 10 27 16](https://github.com/invertase/react-native-firebase/assets/21963291/9b9c3764-0603-42f5-bc04-3c39cbc080aa)
![Screenshot 2023-09-27 at 10 27 38](https://github.com/invertase/react-native-firebase/assets/21963291/f706ef62-3afd-4db9-a612-ed92521906f7)

Could you help me please?

**Comment by mikehardy** [comment]
Hi there! You have mixed and matched the react-native-firebase versions, which is not supported and will lead to issues like this.

All react-native-firebase modules should be the exact same version at all times -- https://invertase.io/blog/react-native-firebase-versioning

**Comment by ildaneta** [comment]
You say about analytics being in 18.5.0 and the other packages like firebase/app being at 18.3.0?

I created this issue with all the information:
https://github.com/invertase/react-native-firebase/issues/7375

Thank you for your time @mikehardy
