### ISSUE TITLE
[🐛] Error Compile

### ISSUE THREAD

**Issue by huoengineer** [invertase/react-native-firebase#6426]
** BUILD FAILED **

The following build commands failed:
	CompileC /Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNFirebase.build/Objects-normal/x86_64/RNFirebaseAnalytics.o /node_modules/react-native-firebase/ios/RNFirebase/analytics/RNFirebaseAnalytics.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNFirebase' from project 'Pods')
(1 failure)

**Comment by mikehardy** [comment]
This issue is invalid, it contains no useful information to help people help you
https://stackoverflow.com/help/how-to-ask
