### ISSUE TITLE
React native firebase admob interstitial error

### ISSUE THREAD

**Issue by minhtamwebmaster** [invertase/react-native-firebase#643]
![screen shot 2017-11-23 at 11 19 52 pm](https://user-images.githubusercontent.com/8031837/33182078-15d4f110-d0a5-11e7-8c41-7cd7451b434a.png)

Android working, but ios error
My code here

import React, { Component } from 'react';
import {
    View, Text, Dimensions, Image, 
    StyleSheet, Button, TextInput, TouchableOpacity
} from 'react-native';
import { connect } from 'react-redux';
import Carousel from 'react-native-snap-carousel';
import firebase from 'react-native-firebase';

const {width, height} = Dimensions.get('window');
const advert = firebase.admob().interstitial('ca-app-pub-3940256099942544/1033173712');

const AdRequest = firebase.admob.AdRequest;
const request = new AdRequest();
request.addKeyword('foo').addKeyword('bar');

// Load the advert with our AdRequest
advert.loadAd(request.build());

advert.on('onAdLoaded', () => {
  console.log('Advert ready to show.');
});

// Simulate the interstitial being shown "sometime" later during the apps lifecycle
setTimeout(() => {
  if (advert.isLoaded()) {
    advert.show();
  } else {
    // Unable to show interstitial - not loaded yet.
  }
}, 1000);

class Detail extends Component {

**Comment by Ehesp** [comment]
Please follow the issue template and format your code.
