### ISSUE TITLE
signInWithPhoneNumber ignoring promise rejection

### ISSUE THREAD

**Issue by sfratini** [invertase/react-native-firebase#644]
### Issue

I am configuring the phone auth verification but I am finding one particular issue and I believe it could be a bug. 

I was having this issue:

`11-24 00:15:24.143 23148 11203 I AuthChimeraService: Error description received from server: INVALID_APP_CREDENTIAL : App validation failed`

Which I found is because of the missing SHA1 fingerprint in my firebase console. I added that and I got this:

```
11-24 00:05:52.662 23148  6216 W Conscrypt:    com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@11746448:13)
11-24 00:05:52.895 23148  6216 E Volley  : [39708] BasicNetwork.performRequest: Unexpected response code 400 for https://www.googleapis.com/identitytoolkit/v3/relyingparty/sendVerificationCode?alt=proto&key=XXXXXXXXXXXXXXX
11-24 00:05:52.897 23148   780 I AuthChimeraService: Error description received from server: INVALID_PHONE_NUMBER : Invalid format.
11-24 00:05:52.901 23148 13280 W FirebaseAuth: [PhoneVerificationSession] onFailure
11-24 00:05:53.013 23148 11203 W FirebaseAuth: [PhoneNumberAuthPostProcessor] postProcess ends
```

The second one was expected since I was testing sending a wrong number like 123. In both cases, the promise is not being rejected nor accepted. This is my code and in both cases, the resolve code is not being executed:

```
 if (this.state.phone == null || this.state.phone.length == 0){
                alert(this.getString('login_sms_send_invalid'));                
            } else {

                firebase.auth().signInWithPhoneNumber(this.state.phone)
                .then(function (confirmationResult) {
                    this._confirmationResult = confirmationResult; 
                    alert(this.getString('login_sms_send_confirmation'));       //Never executed                     
                }).catch(function (error) {
                    if (error.code == "auth/invalid-phone-number"){
                        alert(this.getString('login_sms_send_invalid'));
                    } else {
                        alert(this.getString('login_sms_send_error'));
                    }
                });

            }
```

### Environment

1. Application Target Platform:  Android

2. Development Operating System:  Windows 10

3. Build Tools: Android 7.0

4. React Native version: 0.48.1

5. RNFirebase Version: 3.0.5

6. Firebase Module:  auth

**Comment by chrisbianca** [comment]
@sfratini Are you able to test the latest version of `react-native-firebase`? We've recently released a auth starter kit which covers off the scenario you describe and didn't come across this issue. It might be that we've now fixed it...

**Comment by Ehesp** [comment]
Closing as we've heard nothing back. Please try the latest version and let us know if the problem still exists.
