### ISSUE TITLE
[📚] Confused how to get working for Bare Workflow Expo and crashlytics

### ISSUE THREAD

**Issue by joshua-revolutions** [invertase/react-native-firebase#6443]
## Documentation Feedback

I'm very confused how to get crashlytics working with Expo bareworkflow.
For [getting started](https://rnfirebase.io/#expo) it says:

> If you're using [Bare Workflow](https://docs.expo.io/introduction/managed-vs-bare/#bare-workflow), please follow the above installation steps instead.

What does it mean by "above installation steps"? Does mean just do the steps as if it is a non-expo react native project?

Then for [crashlytics](https://rnfirebase.io/crashlytics/android-setup) setup:

> If you're using Expo, make sure to add the @react-native-firebase/crashlytics config plugin to your app.json or app.config.js. It handles the below installation steps for you. For instructions on how to do that, view the [Expo](https://rnfirebase.io/#expo) installation section.

Is this for bare/managed or both workflows?

**Comment by ShaneZhengNZ** [comment]
I kind of agree with you. That part is a little confusing. I will create a PR to clarify the process.

Since I have just done the integration using Expo and RN Firebase, I know exactly what to do

**Comment by mikehardy** [comment]
I just want to give a specific + big thanks to @ShaneZhengNZ for posting the PR he mentioned, I just merged it and that should help all Expo users going forward. If anyone from the future reads this: I'm always happy to merge reasonable PRs and the GitHub web UI makes a docs PR like this really easy if you want to give it a go. Cheers

**Comment by ShaneZhengNZ** [comment]
@mikehardy haha. all good. I am actively using this package with my Expo project, so, trying my best to contribute as I go through various modules.

**Comment by mikehardy** [comment]
Not sure you will want phone authentication, but the only Expo thing we have hanging out without closure is a PR for an expo plugin that does auth+phone auth that nobody seems to be able to sign correctly :laughing: so it can't get past the CI checks. #6472 / #6167 - no obligation whatsoever of course, but that one needs almost no work I think? And if you want that feature you might be interested. I think there are config plugins for all the other high-use items
