### ISSUE TITLE
Signinwithphonenumber Getting Invalid token error on device only, simulator works perfectly

### ISSUE THREAD

**Issue by brooklyntronic** [invertase/react-native-firebase#645]
Steps to reproduce: login works on first attempt after app is installed on device.  After logging out and trying to log back in I get this error. On the ios simulator it works perfectly but is failing on device.
Debug log from device:
{ [Error: Invalid token.]
  line: 7484,
  column: 24,
  sourceURL: 'http://192.168.0.11.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false',
  framesToPop: 1,
  code: 'auth/unknown',
  nativeStackIOS: 
   [ '0   MUM_5                               0x00000001049e42b0 RCTJSErrorFromCodeMessageAndNSError + 152',
     '1   MUM_5                               0x0000000104997268 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.218 + 176',
     '2   MUM_5                               0x0000000104c1f44c -[RNFirebaseAuth promiseRejectAuthException:error:] + 288',
     '3   MUM_5                               0x0000000104c1c668 __70-[RNFirebaseAuth signInWithPhoneNumber:phoneNumber:resolver:rejecter:]_block_invoke + 156',
     '4   libdispatch.dylib                   0x00000001071a549c _dispatch_call_block_and_release + 24',
     '5   libdispatch.dylib                   0x00000001071a545c _dispatch_client_callout + 16',
     '6   libdispatch.dylib                   0x00000001071aa050 _dispatch_main_queue_callback_4CF + 1192',
     '7   CoreFoundation                      0x000000018175deb0 <redacted> + 12',
     '8   CoreFoundation                      0x000000018175ba8c <redacted> + 2012',
     '9   CoreFoundation                      0x000000018167bfb8 CFRunLoopRunSpecific + 436',
     '10  GraphicsServices                    0x0000000183513f84 GSEventRunModal + 100',
     '11  UIKit                               0x000000018ac502e8 UIApplicationMain + 208',
     '12  MUM_5                               0x000000010467fad0 main + 124',
     '13  libdyld.dylib                       0x000000018119e56c <redacted> + 4' ],
  userInfo: 
   { error_name: 'INVALID_APP_CREDENTIAL',
     NSLocalizedDescription: 'Invalid token.' },
  domain: 'FIRAuthErrorDomain' }

firebase.auth().signInWithPhoneNumber(phoneNumber)
  .then(confirmResult => {this.setState({ confirmResult, fetching: false}); })
  .catch(error => {window.alert('Network Error, please make sure you are connected');console.log(error);this.setState({ message: `Sign In With Phone Number Error: ${error.message}`, fetching: false })});

1. Application Target Platform: 
iOS
2. Development Operating System: 
macOS Sierra
3. Build Tools: 
Xcode
4. React Native version: 
0.49.3
5. RNFirebase Version: 
3.1.0
6. Firebase Module: 
Firebase/Auth

**Comment by brooklyntronic** [comment]
Re installed and uploaded new apn's etc, everything works now.

**Comment by alorr10** [comment]
@brooklyntronic can you explain in a little more detail how you fixed this?? Im having the exact same problem right now. Thanks!

**Comment by gabrielvcbessa** [comment]
I am also getting this error

**Comment by brooklyntronic** [comment]
Reinstall the module.  Look up the process in the firebase docs on setting up phone-auth.  From there you will be instructed to create various items within the apple developer console.  As well as that you must reset all of the variables and the JSON you receive from firebase.  To make a long story short, I reset the module and all of it's associated data.

**Comment by naytun** [comment]
First, you need to update Project settings in Firebase:
https://firebase.google.com/docs/auth/ios/phone-auth

Second: create Auth. Key in Apple developer console:
https://firebase.google.com/docs/cloud-messaging/ios/certs

Third: follow/copy the sample shown on this page:
https://rnfirebase.io/docs/v3.2.x/auth/phone-auth
