### ISSUE TITLE
Non Fatal event reported in firebase crashlytics while using messaging.getToken()

### ISSUE THREAD

**Issue by saikirannani123** [invertase/react-native-firebase#6462]
Hi,

   On the production build recently a non-fatal event is getting reported on the firebase crashlytics. While trying to get the more insights on the event, Observed the event is happening on the messging.getToken() method. 

Below is the screenshot reported in the firebase Crashlytics

<img width="1149" alt="Screenshot 2022-08-09 at 11 06 50 PM" src="https://user-images.githubusercontent.com/27265601/183722107-a560a38c-2ec1-4742-af55-832830b2cca7.png">

<img width="1174" alt="Screenshot 2022-08-09 at 11 06 56 PM" src="https://user-images.githubusercontent.com/27265601/183722130-ec158f67-0357-496d-aad4-10010e905957.png">

using source map with the bundle we figured out  where exactly the event is happening. Attached the screenshot for the reference.

![image](https://user-images.githubusercontent.com/27265601/183721400-0a0d6e4f-d6b3-47a3-9b41-effdec8422a5.png)

Appreciate any help on the above to get it resolved . 

Thank you!!

**Edit:** 

There is also a Non fatal exception reported couple of days back in the firebase related to the messaging. Snapshot attached below

<img width="834" alt="image" src="https://user-images.githubusercontent.com/27265601/183730719-be832066-527d-489c-904f-f51be242208d.png">

**Comment by saikirannani123** [comment]
Any Reason Why it is closed without any comment or solution being provided @mikehardy

**Comment by mikehardy** [comment]
Web search stackoverflow 'how to ask'
Web search javascript unhandled promise rejection 

Action items for a new issue afterwards

- use try/catch in your code
- include details required to access help if you need help
