### ISSUE TITLE
[firestore/unavailable] The service is currently unavailable

### ISSUE THREAD

**Issue by Ggayane** [invertase/react-native-firebase#6474]
[firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff, this error appears, although there is a network connection, this happens a lot on Android devices, and a few times on iOS.
Does anyone know what can be the problem?
I've found similar reports in issues section, but they don't seem to have any solution.

I'm using "@react-native-firebase/firestore": "^14.2.2"

**Comment by Ggayane** [comment]
I've tested on the same network both iOS and Android, iOS works fine, on Android sometimes I see this error, and whenever this happens right after it when I try another request (like `firestore().doc(`smoething`).get();`) it works as expected, without any errors. And I also check user token while this error appears, token is fine and not expired.

**Comment by mikehardy** [comment]
That's odd - I wonder if the android device is somehow putting the network to sleep aggressively, for instance for power-saving.

It appears to be this case from the error message:

> This is a most likely a transient condition and may be corrected by retrying with a backoff

**Comment by Ggayane** [comment]
that's possible I guess, the solution can be to catch this error and retying to do the same call again.

**Comment by AdnanIqbalKhan** [comment]
I am getting the same issue
using @react-native-firebase/firestore": "^14.7.0"

**Comment by AdnanIqbalKhan** [comment]
@mikehardy I don't know what causes the issue
in a physical device, it works fine
but in the emulator firebase/auth is working but firebase/firestore and firebase/database not responding 
This is the error I get. 
"[Error: [firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.]"

**Comment by AdnanIqbalKhan** [comment]
The problem is with Android Emulator v 31.3.10 
I added 
`<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>`
and turn off wifi in the emulator and turn on its data connection
works for me
https://stackoverflow.com/questions/50195049/firebase-android-works-on-the-emulator-but-not-on-the-device
https://stackoverflow.com/questions/73370728/firebase-doesnt-work-on-android-studio-emulator/73395525#73395525

**Comment by raulgordejev** [comment]
I've had the same problem for years with react-native-firebase. What happens (I think) is that OS battery saver/optimisation settings kill the firestore connection while the app is backgrounded for some time (a few minutes). After opening the app again, firestore takes quite a long time to reconnect - around 30 seconds up to 1 minute. Get queries return the [firestore/unavailable] error, but subscriptions just silently wait until firestore is reconnected.

It's been a really annoying issue to deal with and I haven't seen any proper solutions for that yet. As a workaround I'm currently using firestore REST API to fetch data in addition to subscriptions in the more critical places in the app.

From crashlytics logs it seems to be happening slightly more on iOS, but I've found it to be easier to reproduce on Android. Specifically Androids 10 to 12.

To reproduce this issue:

1. Subscribe to a collection/document in the app
2. Put the app in the background state
3. Settings->Battery->Battery saver [on] OR Select your app -> App info -> Battery -> Manage battery usage [restricted]
4. Open the app after around 5 minutes
5. Firestore subscription should not return anything for around 30 seconds and get queries will return [firestore/unavailable].

**Comment by becabytess** [comment]
In my case , the problem was that i was trying to use offline persistence without caching the data first .  So , make sure you have fetched first before trying to make use of offline-persistence .

**Comment by becabytess** [comment]
In my case , the problem was that i was trying to use offline persistence without caching the data first .  So , make sure you have fetched first before trying to make use of offline-persistence .

**Comment by jomgapuz** [comment]
This is still happening with the latest version "20.30.0" with iPhone SE (3rd generation) simulator and using Firebase emulators with auth and firestore. Do you have an official guide or solution for this?

**Comment by ftaibi** [comment]
still happening

**Comment by alikrodrigues** [comment]
Still happening it a lot of times, most of the times in android OnePlus8

**Comment by jd-alexander** [comment]
For me the error was taking place due to some WiFi issues. When I switched to another network it disappeared.

**Comment by Daniel-W1** [comment]
has anyone fixed this issue, it happened to me too, and I couldn't find any fix.

**Comment by francesco-clementi-92** [comment]
> I've had the same problem for years with react-native-firebase. What happens (I think) is that OS battery saver/optimisation settings kill the firestore connection while the app is backgrounded for some time (a few minutes). After opening the app again, firestore takes quite a long time to reconnect - around 30 seconds up to 1 minute. Get queries return the [firestore/unavailable] error, but subscriptions just silently wait until firestore is reconnected.
> 
> It's been a really annoying issue to deal with and I haven't seen any proper solutions for that yet. As a workaround I'm currently using firestore REST API to fetch data in addition to subscriptions in the more critical places in the app.
> 
> From crashlytics logs it seems to be happening slightly more on iOS, but I've found it to be easier to reproduce on Android. Specifically Androids 10 to 12.
> 
> To reproduce this issue:
> 
> 1. Subscribe to a collection/document in the app
> 2. Put the app in the background state
> 3. Settings->Battery->Battery saver [on] OR Select your app -> App info -> Battery -> Manage battery usage [restricted]
> 4. Open the app after around 5 minutes
> 5. Firestore subscription should not return anything for around 30 seconds and get queries will return [firestore/unavailable].

Hello, I'm experiencing the same error. Is there a way to check if the connection has been restored or not?

**Comment by mikehardy** [comment]
perhaps 

https://reactnative.dev/docs/appstate#addeventlistener


listen for transition to foreground, do a test get to firestore and if it is unavailble try a pair of calls to toggle the network down then up

https://rnfirebase.io/reference/firestore#disableNetwork / https://rnfirebase.io/reference/firestore#enableNetwork

I have not tried this but something like this might work

If there is no way to force the network to reinit and you must wait, then in the app could also maintain a global "firestore network is available" status flag somewhere, and in the AppState listener on transition to foreground you could try a firestore doc get and update the availability flag based on the result, testing it in a loop until it is available. Use the availability flag in other areas to do what makes sense for your app's use cases...

**Comment by amarinsam** [comment]
For me, I had named my Firestore database to something other than (default).  Deleting the database, and creating a new one named (default) fixed the error.

**Comment by sarnakov** [comment]
> For me, I had named my Firestore database to something other than (default). Deleting the database, and creating a new one named (default) fixed the error.

At first I thought it was a joke, but apparently it's a solution...

**Comment by Sneidon** [comment]
> For me, I had named my Firestore database to something other than (default). Deleting the database, and creating a new one named (default) fixed the error.

This fixed the issue for me.

**Comment by kaleb-dev** [comment]
Im getting this error with the new modular api in the emulators, everything runs correctly but the firestore is causing me issue on mount. 

```
import { getApp } from "@react-native-firebase/app";
import { getAuth, connectAuthEmulator } from "@react-native-firebase/auth";
import {
  getFirestore,
  connectFirestoreEmulator,
} from "@react-native-firebase/firestore";
import {
  connectStorageEmulator,
  getStorage,
} from "@react-native-firebase/storage";
import {
  getFunctions,
  connectFunctionsEmulator,
} from "@react-native-firebase/functions";
import { environmentUtil } from "@/utils/environment";
const environment = environmentUtil();

const host = "192.168.2.216";

export const app = getApp();
export const auth = getAuth(app);
export const db = getFirestore(app);
export const storage = getStorage(app);
export const functions = getFunctions(app, "us-central1");
export const firestore = getFirestore(app);

if (environment === "localhost") {
  connectAuthEmulator(auth, `http://${host}:9099`, {
    disableWarnings: true,
  });
  connectFunctionsEmulator(functions, host, 5001);
  connectFirestoreEmulator(firestore, host, 8080);
  connectStorageEmulator(storage, host, 9199);
}
```

**Comment by ErangaD** [comment]
> For me, I had named my Firestore database to something other than (default). Deleting the database, and creating a new one named (default) fixed the error.

this works lol

**Comment by hungtooc** [comment]
> For me, I had named my Firestore database to something other than (default). Deleting the database, and creating a new one named (default) fixed the error.

Fixed for me!

**Comment by dogankablan** [comment]
It's really weird, but it worked.Firebase definitely needs to find a proper solution for this.

**Comment by jerryphm** [comment]
I encountered the same issue when reading from firestore, both in a Cloud Function and in mobile app. Specifying the database name when calling `getFirestore` fixed the error for me:

```js
import { getFirestore, doc, getDoc } from '@react-native-firebase/firestore';
import { getApp } from '@react-native-firebase/app';

const db = getFirestore(getApp(), 'my-database-name');
```

**Comment by ngothanhtai** [comment]
for my case, I haven't clicked Create database in Firebase console.

**Comment by andrewde** [comment]
Thank you @Ggayane for creating this thread and @amarinsam for posting a fix! I have been stuck on this for WEEKS for a side project, I was getting "[[firestore/unavailable] The service is currently unavailable]" CONSTANTLY for iOS (simulator or physical device), and never got a successful read/write. 

I deleted my custom db, and recreated one with the default name (being "(default)"), it worked!!!!

Next step is to try with a custom DB name, and then try to pass that custom name like indicated in other comments. No luck so far. 

But I can live with my db named "(default)" for now.

**Comment by Saad962404** [comment]
firebase is shit to be used as backend

**Comment by st0w** [comment]
> I encountered the same issue when reading from firestore, both in a Cloud Function and in mobile app. Specifying the database name when calling `getFirestore` fixed the error for me:
> 
> import { getFirestore, doc, getDoc } from '@react-native-firebase/firestore';
> import { getApp } from '@react-native-firebase/app';
> 
> const db = getFirestore(getApp(), 'my-database-name');

Thank you!! I just spent a couple hours banging my head against the wall and this was the fix I needed. It would be nice if this was mentioned somewhere in the documentation for this module, or even in the native Firestore documentation. Nowhere did I see a single reference to the database name.

**Comment by faustoct1** [comment]
> For me, I had named my Firestore database to something other than (default). Deleting the database, and creating a new one named (default) fixed the error.

it worked for me, thanks.
