### ISSUE TITLE
Expo app plugin adds Firebase import multiple times [Expo 45]

### ISSUE THREAD

**Issue by pehagg** [invertase/react-native-firebase#6477]
## Issue

On Expo 45, Firebase import gets added every time `expo prebuild` is run on an Expo project that uses dev client and the Firebase app plugin. Most likely caused by the import check in `appDelegate.ts` which only checks for `@import Firebase`, not `#import <Firebase/Firebase.h>`. 

Had a stab at a local fix/patch, but wasn't able to figure out how to update the plugin code so that my changes would apply. 

Not a huge issue, but somewhat annoying because I need to remove the added lines every time I want to check in my changes to version control.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `15.3.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `App`
- **Are you using `TypeScript`?**
  - `N/A`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
That does sound irritating. Expo isn't a use case of mine (apologies) so this will need a patch from someone else but I can merge+release anything that comes in related

**Comment by DoctorJohn** [comment]
@pehagg I think your right, looks like the following check is not correct:

https://github.com/invertase/react-native-firebase/blob/630142ff49ca269d1b55d0898767228d0cf5f808/packages/app/plugin/src/ios/appDelegate.ts#L18

You should give [patch-package](https://www.npmjs.com/package/patch-package) a try. If your patch works you can open a pull request in this repo.

**Comment by pehagg** [comment]
> You should give [patch-package](https://www.npmjs.com/package/patch-package) a try. Our do you mean by `but wasn't able to figure out how to update the plugin code so that my changes would apply.` something else 👀 ?

@DoctorJohn , Sorry, didn't see this before now. I tried with patch-package, but my changes didn't have any effect when I built the app, regardless what I tried. Might've been missing some step or something 🤷🏻 .

**Comment by mikehardy** [comment]
That sounds like a mis-integration of patch-package somehow. Yarn will obliterate patch-package changes if you re-run yarn *and* patch-package is not in a postinstall (or maybe even postinstall-postinstall - check patch-package docs) step

**Comment by pehagg** [comment]
@mikehardy nope, that's not it. I verified several times that the postinstall task ran successfully. Most likely some other issue, but let's not rule out PEBCAK completely 😁

**Comment by pehagg** [comment]
Can confirm that the fix is working. Thanks for fixing this @DoctorJohn.
