### ISSUE TITLE
[🐛] Crashlytics (iOS) - Reports are sent only after restarting the application

### ISSUE THREAD

**Issue by dylanalizon** [invertase/react-native-firebase#6479]
## Issue

Reports (fatal and non-fatal) are only sent when the application has restarted. This is not a problem for fatal errors because the application crashes and so to use it you have to reopen it so the report is sent. But for non-fatal errors, it is more problematic, because I use `crashlytics().recordError(new Error('test'));` in try catches and I cannot force the user to restart his application.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "dependencies": {
    "@react-native-community/datetimepicker": "^6.3.1",
    "@react-native-community/push-notification-ios": "^1.10.1",
    "@react-native-firebase/analytics": "^15.3.0",
    "@react-native-firebase/app": "^15.3.0",
    "@react-native-firebase/crashlytics": "^15.3.0",
    "@react-native-firebase/messaging": "^15.3.0",
    "react-native": "^0.69.4",
  },
}

```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "crashlytics_debug_enabled": true
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false
production = ENV["PRODUCTION"] == "1"

target 'App' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => true,
    :hermes_enabled => true,
    :fabric_enabled => false,
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  $RNFirebaseAsStaticFramework = true

  target 'AppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] =  "arm64"
      end
    end
  end
end

```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <React/RCTAppSetupUtils.h>
// Enable Splash Screen
#import "RNBootSplash.h"
// Firebase
#import <Firebase.h>

#if RCT_NEW_ARCH_ENABLED
#import <React/CoreModulesPlugins.h>
#import <React/RCTCxxBridgeDelegate.h>
#import <React/RCTFabricSurfaceHostingProxyRootView.h>
#import <React/RCTSurfacePresenter.h>
#import <React/RCTSurfacePresenterBridgeAdapter.h>
#import <ReactCommon/RCTTurboModuleManager.h>

#import <react/config/ReactNativeConfig.h>

static NSString *const kRNConcurrentRoot = @"concurrentRoot";

@interface AppDelegate () <RCTCxxBridgeDelegate, RCTTurboModuleManagerDelegate> {
  RCTTurboModuleManager *_turboModuleManager;
  RCTSurfacePresenterBridgeAdapter *_bridgeAdapter;
  std::shared_ptr<const facebook::react::ReactNativeConfig> _reactNativeConfig;
  facebook::react::ContextContainer::Shared _contextContainer;
}
@end
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // Firebase init
  [FIRApp configure];

  RCTAppSetupPrepareApp(application);

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];

#if RCT_NEW_ARCH_ENABLED
  _contextContainer = std::make_shared<facebook::react::ContextContainer const>();
  _reactNativeConfig = std::make_shared<facebook::react::EmptyReactNativeConfig const>();
  _contextContainer->insert("ReactNativeConfig", _reactNativeConfig);
  _bridgeAdapter = [[RCTSurfacePresenterBridgeAdapter alloc] initWithBridge:bridge contextContainer:_contextContainer];
  bridge.surfacePresenter = _bridgeAdapter.surfacePresenter;
#endif

  NSDictionary *initProps = [self prepareInitialProps];
  UIView *rootView = RCTAppSetupDefaultRootView(bridge, @"App", initProps);

  if (@available(iOS 13.0, *)) {
    rootView.backgroundColor = [UIColor systemBackgroundColor];
  } else {
    rootView.backgroundColor = [UIColor whiteColor];
  }

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  // Init splash screen
  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];

  return YES;
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feture is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  // Switch this bool to turn on and off the concurrent root
  return true;
}

- (NSDictionary *)prepareInitialProps
{
  NSMutableDictionary *initProps = [NSMutableDictionary new];

#ifdef RCT_NEW_ARCH_ENABLED
  initProps[kRNConcurrentRoot] = @([self concurrentRootEnabled]);
#endif

  return initProps;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

#if RCT_NEW_ARCH_ENABLED

#pragma mark - RCTCxxBridgeDelegate

- (std::unique_ptr<facebook::react::JSExecutorFactory>)jsExecutorFactoryForBridge:(RCTBridge *)bridge
{
  _turboModuleManager = [[RCTTurboModuleManager alloc] initWithBridge:bridge
                                                             delegate:self
                                                            jsInvoker:bridge.jsCallInvoker];
  return RCTAppSetupDefaultJsExecutorFactory(bridge, _turboModuleManager);
}

#pragma mark RCTTurboModuleManagerDelegate

- (Class)getModuleClassFromName:(const char *)name
{
  return RCTCoreModulesClassProvider(name);
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:(const std::string &)name
                                                      jsInvoker:(std::shared_ptr<facebook::react::CallInvoker>)jsInvoker
{
  return nullptr;
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:(const std::string &)name
                                                     initParams:
                                                         (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return nullptr;
}

- (id<RCTTurboModule>)getModuleInstanceFromClass:(Class)moduleClass
{
  return RCTAppSetupDefaultModuleFromClass(moduleClass);
}

#endif

@end

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 87.13 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /var/folders/54/myt1c22x7sl99ppljfw62gzw0000gp/T/yarn--1660836547360-0.14618622090343036/node
    Yarn: 1.22.18 - /var/folders/54/myt1c22x7sl99ppljfw62gzw0000gp/T/yarn--1660836547360-0.14618622090343036/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Bumblebee 2021.1.1 Bumblebee 2021.1.1
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /opt/homebrew/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.0.0 => 18.2.0 
    react-native: ^0.69.4 => 0.69.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

- **Platform that you're experiencing the issue on**:
  - [] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `15.3.0`
- **`Firebase` module(s) you're using that has the issue:**
  - see package.json above
- **Are you using `TypeScript`?**
  - `Y` & `4.7.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I wonder if this would help? https://rnfirebase.io/reference/crashlytics#sendUnsentReports (along with the related check method)

It was my understanding that non-fatal errors would go immediately, so I'm a little surprised here

**Comment by dylanalizon** [comment]
> I wonder if this would help? https://rnfirebase.io/reference/crashlytics#sendUnsentReports (along with the related check method)
> 
> It was my understanding that non-fatal errors would go immediately, so I'm a little surprised here

I've already tried this. But it doesn't send anything either. For information the variable `isCrashlyticsCollectionEnabled` is `true`.

**Comment by mikehardy** [comment]
Still want to look into this, but have not had available time. Anyeone else free to look into it of course...

**Comment by swrobel** [comment]
FWIW, this seems to be something new in RNFirebase 15.x. I wasn't seeing this issue when I was on 14.12.0 but it started happening when I upgraded.

**Comment by mikehardy** [comment]
> Still want to look into this, but have not had available time. Anyone else free to look into it of course...


Same same, different month...

**Comment by toscalivia83** [comment]
I have the same problem

this is what I have in my firebase.json file:
`"react-native": {
    "crashlytics_debug_enabled": true,
    "crashlytics_ndk_enabled": false,
    "crashlytics_auto_collection_enabled": true,
    "crashlytics_disable_auto_disabler": true
  }`

and these are the versions I'm using @react-native-firebase/crashlytics version 14.11.0

**Comment by developeromI89** [comment]
I am experience different error.
@mikehardy 
After crash happens in release on ios simultor 
I am tracking events with below command 
xcrun simctl spawn booted log stream --level debug --style compact | grep -i crash
which is mentioned on [here](https://invertase.io/blog/react-native-firebase-crashlytics-configuration) .

So crash happens , then I restart app and I am getting below logs in terminal 
- [FirebaseCrashlytics][I-CLS000000] [Firebase/Crashlytics] Packaged report with id '2xxxxxxxxxxxxxxd' for submission
- [FirebaseCrashlytics][I-CLS000000] Submitting report async
- [FirebaseCrashlytics][I-CLS000000] [Crashlytics:Crash:Reports:Event] Sending app_exception event to Firebase Analytics for crash-free statistics
- [FirebaseCrashlytics][I-CLS000000] Completed report submission with id: 2xxxxxxxxxxxxxxd.  but crashes not reporting on Firebase console. in crashlytics

**Comment by mikehardy** [comment]
> I am experience different error.

Then as an etiquette thing, you should open a different issue versus hijacking an existing issue, in the future please do so. I will minimize your comment and this one as off-topic after posting this.

> Completed report submission with id: 2xxxxxxxxxxxxxxd

This indicates that react-native-firebase, and firebase-ios-sdk underneath it have done their job. The web console is a different group and you can pursue it there (or on stackoverflow where the firebase team responds to issues) but make absolutely sure that you have selected the correct app on the console for crash viewing, and you have not hidden / filtered anything. Both of those are things I have made the mistake of before and had trouble finding my crash reports.
