### ISSUE TITLE
React-native-firebase/app installed but build failed with react-native-razorpay 

### ISSUE THREAD

**Issue by ardhendu12345** [invertase/react-native-firebase#6480]
React-native-firebase/app installed and then using use_frameworks! and disbled flipper in the pod file and pod installed and build will succeed but if we use react-native-razorpay (v2.2.9)  it will build failed and throwing an error **The following build commands failed:
	Ld /Users/username/Library/Developer/Xcode/DerivedData/<projectname>-adalexogpyankxeyidumipsdmbar/Build/Products/Debug-iphonesimulator/react-native-razorpay/react_native_razorpay.framework/react_native_razorpay normal (in target 'react-native-razorpay' from project 'Pods')
(1 failure)
** please help what to do for build succeded, too much worried about it please help.

**Comment by mikehardy** [comment]
Unfortunately, if razorpay is not ready, you need to log an issue with them to enable use_frameworks support

Until then, if that module is required in your system you will need to stay on react-native-firebase v14 (which does not require use_frameworks)

I can't think of any other action we can take here
