### ISSUE TITLE
xCode: RNFBMessagging: Modules Issue: Definition of UNNotification must be imported from module 'UserNotifications.UNNotification

### ISSUE THREAD

**Issue by ShumGG** [invertase/react-native-firebase#6483]
Building the app in xCode but always getting this error: 
<img width="334" alt="Screenshot 2022-08-23 at 3 52 11 PM" src="https://user-images.githubusercontent.com/64358196/186117978-ded7516e-edba-4073-8fc9-f60c75ee43da.png">

im using react-native-firebase/app and react-native-messagging latest versions, cant downgrade because messagging requires latest version of react native and also cant find anything related to this error

**Comment by mikehardy** [comment]
With apologies, you have *specifically* deleted our template, so no help may be offered as there are no details

https://stackoverflow.com/help/how-to-ask
