### ISSUE TITLE
[🐛] MainActivity Screen page and screen class log too much views

### ISSUE THREAD

**Issue by aswemake** [invertase/react-native-firebase#6493]
## Issue
I use @react-native-firebase/analytics for collect screen views and screen class
But after upgrade firebase version, i face too much screen views to MainActivity
How to fix it
<img width="378" alt="image" src="https://user-images.githubusercontent.com/83565375/186822209-ba2fe722-6f3d-4926-ac04-53c1e5a467f4.png">

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/analytics": "^15.3.0"
    "@react-native-firebase/app": "^15.3.0"
    "@react-native-firebase/crashlytics": "^15.3.0"
    "@react-native-firebase/dynamic-links": "^15.3.0"
    "@react-native-firebase/messaging": "^15.3.0"
```

#### `firebase.json` for react-native-firebase v6:

```json
{
    "react-native": {
        "google_analytics_automatic_screen_reporting_enabled": false,
        "analytics_auto_collection_enabled": false,
        "messaging_auto_init_enabled": false
    }
}
```

</details>

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ o] my application is an AndroidX application?
- [ o] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ o] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 24
        compileSdkVersion = 31
        targetSdkVersion = 31
        kotlinVersion = '1.6.0'
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.2.2')
        classpath 'com.google.gms:google-services:4.3.13'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven {
            url 'https://naver.jfrog.io/artifactory/maven/'
        }
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven { url 'https://devrepo.kakao.com/nexus/content/groups/public/' }
    }
}

subprojects {
    repositories {
        mavenCentral()
        maven { url 'http://devrepo.kakao.com:8088/nexus/content/groups/public/' }
    }
}
```

**`react-native info` output:**

```
System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 46.82 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.69.4 => 0.69.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mikehardy** [comment]
Hi there!

> But after upgrade firebase version

Upgrade from what version to what version? Looking at the changelog in https://firebase.google.com/support/release-notes/android and https://github.com/invertase/react-native-firebase/blob/main/CHANGELOG.md do you see anything that could cause it?

Your list of dependencies from package.json has been trimmed to not show anything else (so interactions with other systems cannot be determined, like navigation, or react-native itself) and there is no reproduction code here or detailed set of expectations based on prior experience except just "Too much" with regard to views. What specific amount do you expect as you follow a defined path in your app? What amount do you see now

This will be difficult to even think about without more information, and in the end it may be an upstream issue https://github.com/firebase/firebase-android-sdk/ - especially if this happens on Android but not iOS

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/mcve

**Comment by clin211** [comment]
I'm having the same problem, any updates?

**Comment by shhivam** [comment]
Same problem!
