### ISSUE TITLE
'FBDefines/FBDefines.h' file not found  - RN 69.4

### ISSUE THREAD

**Issue by alex-mironov** [invertase/react-native-firebase#6494]
## Issue

After upgrading to NR 69.4 I've attempted to integrate a react-native/firebase into the app following this document: https://rnfirebase.io/.

I saw this note

> use_frameworks [is not compatible with Flipper](https://github.com/reactwg/react-native-releases/discussions/21#discussioncomment-2924919). A fix was put in place in [react-native release 0.69.1](https://github.com/facebook/react-native/releases/tag/v0.69.1) that makes it work with and without Hermes. To use it with Hermes make sure you have set static linkage with use_frameworks! :linkage => :static. To use without Flipper, comment out the :flipper_configuration line in your Podfile.

So I added exactly this to my Podfile
```
target 'myApp' do
  use_frameworks! :linkage => :static
...
```

Eventually I've got an error saying `'FBDefines/FBDefines.h' file not found`
![SCR-20220826-kt5](https://user-images.githubusercontent.com/2544767/186898729-708080c5-24a3-424e-89a7-d925d05e26e1.png)

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

project 'myApp',
        'Dev.Debug' => :debug,
        'Debug' => :debug,

target 'myApp' do
  use_frameworks! :linkage => :static
  config = use_native_modules!
  
  # Flags change depending on the env values.
  flags = get_default_flags()
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Pods for myApp
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'GoogleTagManager', '~> 7.1'
  pod 'OpenSSL-Universal', '~>1.1.1100'

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

end
```
```

#### `AppDelegate.m`:

```objc
#import <Firebase.h>
#import "AppDelegate.h"

...

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  RCTAppSetupPrepareApp(application);

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];

...
}
```
---

**package.json**
```
    "react-native": "0.69.4",

    "@react-native-firebase/app": "^15.3.0",
    "@react-native-firebase/crashlytics": "^15.3.0",
    "@react-native-firebase/messaging": "^15.3.0",
    "@react-native-firebase/remote-config": "^15.3.0",
```

**Comment by mikehardy** [comment]
>     :flipper_configuration => FlipperConfiguration.enabled,

`:flipper_configuration => FlipperConfiguration.disabled` should do it

https://github.com/mikehardy/rnfbdemo/blob/058dc304ca739f40698225753c12164875af1907/make-demo.sh#L210-L211

```
# Static frameworks does not work with flipper (yet) - toggle it off
sed -i -e $'s/FlipperConfiguration.enabled/FlipperConfiguration.disabled/' ios/Podfile
```

Flipper not working is a known incompatibility, we have ongoing effort to fix it but we are not there yet

https://github.com/invertase/react-native-firebase/blob/630142ff49ca269d1b55d0898767228d0cf5f808/docs/index.md?plain=1#L151

"not compatible with Flipper" from the line you quote :-)
