### ISSUE TITLE
RNFirebase is not working on android

### ISSUE THREAD

**Issue by arunxampr** [invertase/react-native-firebase#650]
![whatsapp image 2017-11-28 at 8 03 15 pm](https://user-images.githubusercontent.com/30466426/33325047-412ac256-d477-11e7-800a-70766b0983ee.jpeg)

I add this to android/app/build.gradle

```
dependencies {
    compile project(':react-native-config')
    compile(project(':react-native-firebase')) {
        transitive = false
    }
   
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules

    // Firebase dependencies
    compile "com.google.android.gms:play-services-base:11.6.0"
    compile "com.google.firebase:firebase-core:11.6.0"
    compile "com.google.firebase:firebase-auth:11.6.0"
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
apply plugin: 'com.google.gms.google-services'`

and in _project level_ build.gradle

`buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.google.gms:google-services:3.1.1'
        classpath 'com.android.tools.build:gradle:2.2.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com'
        }

    }
}`
```

but it's  not working... please help

**Comment by chrisbianca** [comment]
Can I see the contents of `MainApplication.java`?

**Comment by arunxampr** [comment]
@chrisbianca 
Sure 

`package com.xampr_native;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;
import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.auth.RNFirebaseAuthPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ReactNativeConfigPackage(),
            new RNFirebasePackage(),
             new RNFirebaseAuthPackage() 
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
`

**Comment by Ehesp** [comment]
@arunxampr you have re-built the app right?

**Comment by arunxampr** [comment]
I tried to run it multiple times @Ehesp

**Comment by chrisbianca** [comment]
@arunxampr If I'm honest, I'm not sure why this isn't working - have you considered trying to starter kit? https://github.com/invertase/react-native-firebase-starter

**Comment by harisvsulaiman** [comment]
@arunxampr what about our settings.gradle file? it should have something similar 
```
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
include ':react-native-vector-icons'
```

**Comment by chrisbianca** [comment]
@arunxampr Also, check out my new blog post on getting started with Authentication: https://blog.invertase.io/getting-started-with-firebase-authentication-on-react-native-a1ed3d2d6d91

Or, alternatively, we have a new premium starter kit which has authentication all set up and ready to go... https://rnfirebase.io/kits/auth-starter

**Comment by chrisbianca** [comment]
Not heard anything further on this so hopefully the guide has helped - please re-open if you're still having problems.

**Comment by liorbraginsky92** [comment]
I've got error when run react native project using firebase.
gradle build error in android studio
