### ISSUE TITLE
ViewManagerAd apter_ExpoAdAdMobBannerView was not found in UIManager

### ISSUE THREAD

**Issue by MariaLogic5** [invertase/react-native-firebase#6508]
![bug](https://user-images.githubusercontent.com/112341756/188282288-d148c173-b518-4cd6-b4e2-988c895760c3.jpeg)

plz, suggest a solution I have successfully installed the AdMob library.Still getting this error.

**Comment by mikehardy** [comment]
Hi there! There is nothing in this library's supported versions that have anything to do with admob anymore

You may be thinking of expo-ads-admob, which is migrating now to react-native-google-mobile-ads ?

https://stackoverflow.com/questions/72426902/how-to-use-react-native-google-mobile-ads-with-expo may help, but I'm going to close this as unactionable for this repo
