### ISSUE TITLE
React native firebase IOS Admob interstitial show only once

### ISSUE THREAD

**Issue by minhtamwebmaster** [invertase/react-native-firebase#651]
React native firebase  IOS Admob interstitial show only once but android show very normal. 39/5000
IOS off the new app get re-advertised

**Comment by Ehesp** [comment]
Version? Code? Examples?

**Comment by minhtamwebmaster** [comment]
react-native-cli: 2.0.1
react-native: 0.50.3


[Detail copy.txt](https://github.com/invertase/react-native-firebase/files/1510429/Detail.copy.txt)

**Comment by Ehesp** [comment]
Lol what version of this lib?

**Comment by minhtamwebmaster** [comment]
"react-native-firebase": "^3.1.0",

**Comment by Ehesp** [comment]
Will have to look later, but your usage isn't great to be honest, calling loadAd in the render method is asking for trouble.

**Comment by minhtamwebmaster** [comment]
95/5000
I used to check out admob's activity, but it did not work as well on android

**Comment by Ehesp** [comment]
I have no idea what you mean. The docs need updating for usage in a component it seems.

**Comment by minhtamwebmaster** [comment]
Please show admob like on android

**Comment by minhtamwebmaster** [comment]
"A single interstitial instance can only be shown once. If you want to display another, create a new one."

Please guide me to initialize a new audience and show my ad more than once.

**Comment by Ehesp** [comment]
You just create a new instance of it, like so:

```
const advert = firebase.admob().interstitial('ca-app-pub-3940256099942544/1033173712');
```

**Comment by minhtamwebmaster** [comment]
That means I have to create multiple ad units. Is that justified?

2017-12-06 21:47 GMT+07:00 Elliot Hesp <notifications@github.com>:

**Comment by Ehesp** [comment]
Just call it with the same ID? It's an iOS limitation of admob, just has to be re-created each time.

**Comment by minhtamwebmaster** [comment]
When I can not throw the ball into the hole, I'm advertising. Android works
very well, but ios only shows once. Please guide me.

Source code:
https://drive.google.com/file/d/1RqRUd13jnKu0dCg72JniVfNRoLfsbs5w/view?usp=sharing

2017-12-06 22:02 GMT+07:00 Elliot Hesp <notifications@github.com>:

**Comment by Ehesp** [comment]
I'm not downloading your app sorry. I'll take a look at the iOS problem when I can, quite busy at the moment. Feel free to create a PR to fix it.

**Comment by minhtamwebmaster** [comment]
Thank you. Check me out when I have time

2017-12-06 22:14 GMT+07:00 Elliot Hesp <notifications@github.com>:

**Comment by csumrell** [comment]
I also am having this issue on IOS. I have three instances where a redux state counter will trigger the interstitial from my root container. On android the code works fine as is, but on IOS the interstitial will only show up the first time, even though it is loaded for the next calls.

I have this at the very top of my file, outside of the actual react class
```
const advert = firebase.admob().interstitial(interId);
const AdRequest = firebase.admob.AdRequest;
const request = new AdRequest();
advert.loadAd(request.build());
advert.on("onAdClosed", () => {
	advert.loadAd(request.build());
});
```

and then in the same file of the RootComponent Class

```
componentWillUpdate(nextProps) {
			if (nextProps.count === 2) {
				if (advert.isLoaded()) {
					advert.show();
					console.log("2 Show")	
				}
			} else if (nextProps.count === 7) {
				if (advert.isLoaded()) {
					advert.show();
					console.log("7 Show")	
				}
			} else if (nextProps.count === 4) {
				if (advert.isLoaded()) {
					advert.show();
					console.log("4 Entry Show")
				}
			}
}
```

From my understanding of reading the commentd above, I  need to create a new instance of
```
const advert = firebase.admob().interstitial(interId);
```
every time to display another interstital on IOS?

**Comment by Salakar** [comment]
Thanks for reporting this issue. We're aware that AdMob has fallen behind on React Native Firebase and would like to bring it up to speed again. I will close this issue for now and track it as well as other issues collectively over on the `AdMob overhaul proposal` to be addressed in a future release. See #1259
