### ISSUE TITLE
Firestore Snapshot not working with startAt function

### ISSUE THREAD

**Issue by ahmadzraiq** [invertase/react-native-firebase#6512]
Hey,
I'm using Firestore to manage user messages and I want to listen to new user conversations,
For that I used startAt function and I put the listener with "ASC" order, but the listener doesn't work

And here my code:-
<img width="706" alt="Screen Shot 2022-09-07 at 1 30 52 PM" src="https://user-images.githubusercontent.com/43582061/188858206-3826614b-350a-4635-b610-ad86d330f7bb.png">

But if I used the code in that way it will work, but here I don't want to listen to whole user conversions  
<img width="658" alt="Screen Shot 2022-09-07 at 1 38 34 PM" src="https://user-images.githubusercontent.com/43582061/188858298-7d605c3c-0572-4f9a-b4fc-7b0726d55458.png">

I've tried to listen to just updated or created conversations but it's not working 
<img width="617" alt="Screen Shot 2022-09-07 at 2 39 41 PM" src="https://user-images.githubusercontent.com/43582061/188870140-f5c73b8c-c379-4ed2-8865-fed48be06743.png">

**Comment by mikehardy** [comment]
Hi there! You actively deleted our template where we request information required to provide help, and you've provided screenshots not text of code, this is not helpful when it comes to analyzing a problem

**Comment by ahmadzraiq** [comment]
@mikehardy Sorry about that, I've created a new issue [here](https://github.com/invertase/react-native-firebase/issues/6513)
