### ISSUE TITLE
[🐛] App crashes on Android after clicking on notification (quit state)

### ISSUE THREAD

**Issue by koaladlt** [invertase/react-native-firebase#6516]
## Issue

Hi everyone!

I'm having this issue, whenever I have my app in a "Quit State" and I open the app clicking on the push notification, this popup! 

![photo1662583543](https://user-images.githubusercontent.com/64273203/188975249-5a743684-9e15-4753-a7a2-e891c575ba95.jpeg)

I'm not sure how to handle this, maybe I'm missing something.

Thanks a lot!

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `15.4.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there!

- you have deleted our troubleshooting template - that's a big :cry: when it comes to providing help, because we can't
- you'll have to find where those implementation files and open an issue with where ever there are, because they do not exist in this repo

```
mike@bistromath:~/work/Invertase/react-native-firebase (main) % find . | grep PushNotification | grep java
mike@bistromath:~/work/Invertase/react-native-firebase (main) % 
```

**Comment by ajlee4** [comment]
![image](https://user-images.githubusercontent.com/41113213/197222842-e31e0caf-3ce1-4c0e-8ac8-e081dbdea8c0.png)
is there a solution to this problem?
