### ISSUE TITLE
After save or update app automatically restart

### ISSUE THREAD

**Issue by munkhorgil** [invertase/react-native-firebase#652]
When I do something like this 
```
saveFirstDay = () => {
  const { uid } = this.props;
  firebase.database().ref(`/users/${uid}`)
  .update({ 
    'anniversary/firstDay': this.state.firstDay
  });
```

It always restarts the app automatically. Why is that?

**Comment by Ehesp** [comment]
Please use the issue template so we can help.

Look at your native app logs, they'll show you what the problem is.
