### ISSUE TITLE
[📚] Document .setUserProperties 

### ISSUE THREAD

**Issue by benedikt-buchert** [invertase/react-native-firebase#6520]
## Documentation Feedback

For sake of completeness, sending of user properties via .setUserProperties should be added to the documentation.

https://firebase.google.com/docs/analytics/user-properties

**Comment by benedikt-buchert** [comment]
Maybe duplicate: https://github.com/invertase/react-native-firebase/issues/5894

**Comment by mikehardy** [comment]
Sure - could use a PR (or completing that PR as sketched out) to drive it forward
