### ISSUE TITLE
Save mp3 from Firebase storage to res/raw folder in Android

### ISSUE THREAD

**Issue by popo63301** [invertase/react-native-firebase#653]
Hi! I'm using react-native sound to use sound clip on my Android app and I would like to download and fetch sound from my firebase storage. Is it possible using rn-firebase? if so, could you give me more details about how I can achieve that, please?  

Thanks!

**Comment by Salakar** [comment]
@popo63301 please ask this on our discord chat or on StackOverflow with the `react-native-firebase` tag. 

Thanks
