### ISSUE TITLE
[🐛] Bug Report- Error after installing library with building app

### ISSUE THREAD

**Issue by ceyanesb** [invertase/react-native-firebase#6531]
After installing latest version of react-native-firebase several libraries like Auth0 and react-native-geolocation-service stopped working. When trying to build the app after installing rnfirebase i get this error
```
Undefined symbols for architecture x86_64:
  "_OBJC_METACLASS_$_RCTEventEmitter", referenced from:
      _OBJC_METACLASS_$_RNFusedLocation in RNFusedLocation.o
  "_OBJC_CLASS_$_RCTEventEmitter", referenced from:
      type metadata for react_native_geolocation_service.RNFusedLocation in RNFusedLocation.o
  "_RCTMakeAndLogError", referenced from:
      react_native_geolocation_service.checkPlistKeys(Swift.String) -> () in LocationUtils.o
  "_RCTRegisterModule", referenced from:
      _initialize_RNFusedLocation in RNFusedLocationBridge.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I don't understand why, do I need to delete pod lock and install it? Clean pods? What should I do... If I remove the react-native-firebase library it works great

Maybe there is a compatibility issue, any version that doesn't break this?

**Comment by mikehardy** [comment]
You have deleted the template, which is a shame. There is not enough information to go on, so this is not actionable, so I will close

Here's a fully reproducible + scripted from scratch working build for react-native-firebase though, perhaps starting from that then attempting to add other libraries to determine the problem would help https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

I encourage you to read the comments in the script, each thing the script does is vital for a build, as this script is as far as I know a minimal reproduction of a build that works every time in all conditions I'm aware of
