### ISSUE TITLE
[🐛] Unable to retrieve Firebase app check debug token in Android using React native 

### ISSUE THREAD

**Issue by yogitaV-dev** [invertase/react-native-firebase#6538]
I have integrated firebase app check feature in android in react native followed the  document link 
https://rnfirebase.io/reference/app-check.

I have configured the android project in firebase base console and enabled app check. 
I am trying to get token in Debug mode in android.
React native Prpject:

android app/build gradle file for debug 
dependencies {
    implementation 'com.google.firebase:firebase-appcheck-debug:16.0.1'
}

```
import {firebase} from '@react-native-firebase/app-check';
   firebase
        .appCheck()
        .activate('ignored_param', true)
        .then(() => {
          firebase
            .appCheck()
            .getToken()
            .then(token => {
              console.log('token: ', token.token);
            })
            .catch(error => {
              console.log('token error', error);
            });
        });
```

Error: Error returned from the api 403, **App Attestation Failed**.

**Comment by mikehardy** [comment]
I'm not sure what is going on, to be sure I would need to know the exact execution environment. Is this on an emulator? Or a real device?

If it is on an emulator the only way I know is to configure a known debug token in your configuration of app check in the firebase console and inject that token to the app directly as a "shared secret".

Here is what I mean: 

https://github.com/invertase/react-native-firebase/blob/3371727dd23976ce769696c71865460740502d80/packages/app-check/android/src/main/java/io/invertase/firebase/appcheck/ReactNativeFirebaseAppCheckModule.java#L55-L57

From #6026

Described here https://rnfirebase.io/app-check/usage#on-android

This is something you will need to configure and will work if configured correctly

I don't think this is actionable here so I'm going to close this, but the idea is the links above get you moving of course :-). Cheers

**Comment by mo-nizar** [comment]
The same error on the release build, working perfectly on debug build.

Environment: production/ release
Platform: Android
Code:
    if (Platform.OS === 'android') {
      await appCheck().activate('ignoredParam', true);

      appcheck = await appCheck().getToken();
    } else {
      appcheck = await appCheck().getToken(true);
    }

Error: [appCheck/token-error] com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed
