### ISSUE TITLE
React-native-firebase supports only one language in the email template

### ISSUE THREAD

**Issue by StepanNaryshkov** [invertase/react-native-firebase#654]
I use **react-native-firebase** for my project and I can not set a language in the email template. For example, I use [`sendPasswordResetEmail`](https://firebase.google.com/docs/auth/web/manage-users#send_a_password_reset_email) function to send an email, but I can not set language from my device (only in my [firebase console](https://console.firebase.google.com)). In the web, I can set it [`firebase.auth().languageCode = 'fr';`](https://firebase.google.com/docs/auth/web/manage-users#send_a_password_reset_email). Does somebody have any ideas?

**Comment by Ehesp** [comment]
WIP PR created: https://github.com/invertase/react-native-firebase/pull/655

**Comment by chrisbianca** [comment]
This will be released in our next version, either v3.2.3 or v3.3.0

**Comment by scaralfred** [comment]
Was did fixed? What is the exact fucntion to get this working?
I tried auth().useDeviceLanguage().  and auth().setLanguage(appLanguage)
but they did not work

**Comment by mikehardy** [comment]
I just tested this in my app @scaralfred and I'm glad you made me do so! I had an error and was *not* calling `auth().setLanguageCode('my code')` correctly after a re-factoring.

Now, before I send the verification email I call `auth().setLanguage` with either `en` or `es` (my two codes) as the language argument and I get an email template in either English or Spanish as I would expect.

It works for me?
