### ISSUE TITLE
Remote Config does not work...

### ISSUE THREAD

**Issue by nica0012** [invertase/react-native-firebase#6541]
No matter what I try, it seems like it is not possible to fetch values from the console with firebase remote config.

I am, "connected" but no values are being fetched besides the default values I have set.

```
//Package JSON
"react-native": "0.66.0",
"@react-native-firebase/app": "^14.11.1",
"@react-native-firebase/remote-config": "^14.11.1",
```
Here is my code which is executed on app load:

 ```
 async componentDidMount() {
    const appVersion = DeviceInfo.getVersion();

    await remoteConfig().setConfigSettings({
      minimumFetchIntervalMillis: 30000,
    });

    await remoteConfig()
      .setDefaults({
        is_application_on: true,
        min_app_version: appVersion
      })
      .then(() => remoteConfig().fetchAndActivate())
      .then((fetchedRemotely) => {});

      let isAppOn = remoteConfig().getBoolean('is_application_on');
      let appMinVersion = remoteConfig().getNumber('min_app_version');

      this.setState({
        isAppOn: isAppOn ? true : false
      }, () => {
        alert(this.state.isAppOn)
        alert(appMinVersion)
      })
}
```
My firebase is connected but remote config is the only module I cannot seem to connect to...

**Comment by pehagg** [comment]
On a quick glance, the example code looks OK. 

Apologies for the somewhat stupid question, but have you published your configs in Remote Config console? Asking because the process has two steps, edit _and_ publish.

**Comment by pehagg** [comment]
Now that I look at the code again, you're mixing async/await with Promise API, might want to stick with one or the other. Not sure if this is the culprit, but on a general level you're doing all the right things when it comes to initializing the API.

**Comment by enzzoperez** [comment]
same here, the firebase console shows me that there are many reads of my vars, but I cannot get the values remotely. My packages versions

```
    "react-native": "0.70.0",
    "@react-native-firebase/analytics": "^15.6.0",
    "@react-native-firebase/app": "^15.6.0",
    "@react-native-firebase/remote-config": "^15.6.0",
```

**Comment by pehagg** [comment]
I cannot reproduce the issue with my codebase using RNFB 15.6.0 and RN 0.69.5. I published two new parameters remotely, one string and one boolean, both without default values, and both synced just fine. Can't verify with 0.70.x currently as the codebase is Expo based. 

Can you @enzzoperez provide a code snippet that demonstrates how you activate and fetch value from Remote Config?

**Comment by enzzoperez** [comment]
Thanks for the response @pehagg , 
I tested my code again, deleting and creating a new var in firebase and the code worked 🤷‍♂️ , I could get the correct values

**Comment by pehagg** [comment]
> I tested my code again, deleting and creating a new var in firebase and the code worked 🤷‍♂️ , I could get the correct values

Sounds to me that you might've experienced the effect of Remote Config's local caching. 

I recall that in the past there's been some minimum value for `minimumFetchIntervalMillis` you can't go under, but I can't find any documentation that corroborates this, so maybe it has changed. The default setting for this is 12 hours [according to the docs](https://firebase.google.com/docs/remote-config/get-started?platform=web#throttling).

**Comment by kolaade271** [comment]
you close the issue and you are asking question, i dont know what usally wrong with big developer
