### ISSUE TITLE
where clause not working

### ISSUE THREAD

**Issue by lakhwinderdebut** [invertase/react-native-firebase#6549]
Hi there

I am trying to get products from a collection on the basis of some ids, but it returns me empty response

```
const products = await firestore()
        .collection(PRODUCT_COLLECTION)
        .where('id', 'in',[20,2,4,3])
        .get();
```

 but without where, it is working absolutely fine.

`const products = await firestore().collection(PRODUCT_COLLECTION).get();
`
NOTE: I have checked, like 'id' is present in object and single value instead of multiple ids, but same response

**Comment by mikehardy** [comment]
Hi there, in order to post this issue as you have, you have specifically deleted the issue template, which has all sorts of information useful to reproduce this.
Please post a new issue without deleting the template /  with the details we require to help, and we can take a look
