### ISSUE TITLE
Two notifications receiving(one without data and another local notification) When App is in Background Or Kill State 

### ISSUE THREAD

**Issue by ZaidQ797** [invertase/react-native-firebase#6568]
Hi folks I'm using notifee with Firebase Messaging in react native project.When I send notification from FMC I receive only one notification that is good but When notification is sent from my server and app is in background or Killed state I receive Two notifications the first one contains nothing just empty notification and another notification is that I'm displaying with notifee as notifee.displayNotification({title:'Title',body:'Body'}).
  ```
useEffect(() => {
    const unsubscribe = messaging().onMessage(async remoteMessage => {
      const { data } = remoteMessage;
      let payload = eval('({' + data?.payload + '})');
      await notifee.displayNotification({
        title: data?.title,
        body: data?.body,
      });
 });
    return unsubscribe;
  }, []);
```
And I'm setting background Handler in index.js like this
`messaging().setBackgroundMessageHandler(async remoteMessage => {})`
I tried to add display notification code in Background Handler as well but if I left empty or add displayNotification code both cases receiving two notifications.

**Comment by mikehardy** [comment]
Why are you double-posting? Don't do that please. 
Closing as duplicate https://github.com/invertase/notifee/issues/524
