### ISSUE TITLE
[🐛] [Expo][IOS] Build failed 're2/re2.h' file not found Pods/gRPC-Core

### ISSUE THREAD

**Issue by ballza95** [invertase/react-native-firebase#6575]
## Issue

Im use eas build by expo build failed with ios

<img width="776" alt="Screen Shot 2565-09-26 at 10 29 28" src="https://user-images.githubusercontent.com/32051406/192189057-ca4c0604-8126-4ff9-9c7d-fc7ce732c9e0.png">

Thank you.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
    "@react-native-firebase/app": "^14.10.0",
    "@react-native-firebase/auth": "^14.10.0",
    "@react-native-firebase/crashlytics": "14.11.0",
    "@react-native-firebase/firestore": "^14.10.0",
    "@react-native-firebase/messaging": "14.11.0",
    "@react-native-firebase/storage": "^14.10.0",
    "expo": "^44.0.0",
    "react-native": "0.64.3", 
}
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by nbonatsakis** [comment]
I am also running into this. Any help would be appreciated.

**Comment by mikehardy** [comment]
Hi there!

Do not mix and match versions please:

```

    "@react-native-firebase/app": "^14.10.0",
    "@react-native-firebase/auth": "^14.10.0",
    "@react-native-firebase/crashlytics": "14.11.0",
    "@react-native-firebase/firestore": "^14.10.0",
    "@react-native-firebase/messaging": "14.11.0",
    "@react-native-firebase/storage": "^14.10.0",
```

Use most recent version, and use all one version --> https://invertase.io/blog/react-native-firebase-versioning

This version of react-native is in general not supportable:

>     "react-native": "0.64.3", 

I'm not aware of how it even compiles with Xcode 13.3+ and in general the latest version of Xcode is required to develop firebase-ios-sdk, but as of this typing I think it is strictly required - https://github.com/invertase/react-native-firebase/blob/main/CHANGELOG.md#breaking-changes

That said, there's no reason the re2 library should be having compile failures, especially not just now - it's last release was in May apparently? https://github.com/google/re2/releases - months ago, then no changes.

**I have a build script that I use to build test everything, all the time, and I just ran it, it completed fine:**
https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

I don't see any thing on stackoverflow like this, I do not see anything logged in firebase-ios-sdk repository upstream like this. I'm not sure what it is

If you can provide a minimal, complete, reproducible example of this build failure on current versions we can reopen this and revisit 
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by evelant** [comment]
FWIW @mikehardy this just cropped up for me without any changes to my build process. I'm still on 14.12.0 as I can't get my app to build with use_frameworks! yet. Perhaps this is an upstream cocoapods issue? I know very little about cocoapods but is it possible that a minor version of grpc pod got published with a breaking change causing these sudden failures?

**Comment by mikehardy** [comment]
https://github.com/google/re2/releases - nope
https://github.com/grpc/grpc/releases - maybe - this one released 8 days ago, 

According to this https://guides.cocoapods.org/syntax/podspec.html if you use `~>` in a version spec with `1.44.0` it might update to 1.44.x but should not go to 1.45 etc.

firebase says `~> 1.44.0` for gRPC-Core so I think that transitive dep should not have slipped
https://github.com/firebase/firebase-ios-sdk/blob/dc34af68f90452ad56da4615c524c707a45900a0/FirebaseFirestore.podspec#L103 

You can always check your Podfile.lock before and after it began failing to see if the dep really did move?

All I can say is that I have a reproducible example of success, as linked above, and it is my main build repro rig so I can't reproduce failure, it just works for me. I just rebuilt my main work app today for release and it was fine too.

Without a repro, I'm just guessing, it's pretty inefficient and hasn't led to an answer unfortunately

**Comment by evelant** [comment]
Yeah I just checked and it's using 1.44.0. Time to do some more digging. There's no Podfile.lock in an app's repo when using expo managed builds, it gets generated by the EAS build service at build time (not sure exactly how they manage pod versioning with that...)

**Comment by mikehardy** [comment]
If there is no lock file, then they don't :thinking: ? I did a quick search "Expo EAS reproducible builds" and turned up nothing. Perhaps you can dig on that in their forums to see if that's a possible or not. If it was on 1.44.0 though then, nothing slipped. `npx react-native-clean-project` perhaps :fire: :fire_extinguisher:

**Comment by evelant** [comment]
@bondPiyapan I think this is simply a bug with EAS caching. Go to `eas.json` in your project and under whatever build profile you're using set the cache key to some arbitrary string like so `"cache": { "key": "cache_1234" },`

**Comment by nbonatsakis** [comment]
Yes, this works for me now, and I believe it is because I changed the cache key for something else, not realizing that it would likely fix this.
