### ISSUE TITLE
[🐛] [Firebase | Messaging ]firebase.messaging().getToken() returns {"_1": 0, "_2": 0, "_3": null, "_4": null} in android emulator

### ISSUE THREAD

**Issue by Imane-Ragi** [invertase/react-native-firebase#6577]
Hello, 
when I try to retrieve  the token in async mode from an Android device, I got {"_1": 0, "_2": 0, "_3": null, "_4": null}

**Comment by mikehardy** [comment]
That's what a promise looks like when you print it directly. It's an async function, you must wait for it to resolve via async/await or Promise.then()

**Comment by mikehardy** [comment]
@Imane-Ragi Without full details (https://stackoverflow.com/help/how-to-ask / https://stackoverflow.com/help/minimal-reproducible-example) I can't really say.

I can say that this is a standard javascript problem, this is not a react-native-specific thing.

You may think you are awaiting but if what you put in the issue title is what you see, that's a classic "raw Promise" console.log, and it means that regardless of what you think, the Promise is not resolved, that is simply a factual statement based on the evidence you presented. So keep investigating

**Comment by Imane-Ragi** [comment]
@mikehardy Thank you for your support :) .
