### ISSUE TITLE
[🐛][Firestore][iOS] useEmulator doesn't work with a real URL (ngrok specifically)

### ISSUE THREAD

**Issue by pyramid-scheme-ceo** [invertase/react-native-firebase#6596]
## Issue

I am developing an Expo app using the React Native Firebase lirbrary with the auth and firestore sub-libraries (side note: it's super helpful!!). I'm developing for iOS and want my real phone -- running the expo dev client -- to connect to the Firestore emulator which I have running on my local machine. I'm accomplishing this by using ngrok to provide an accessible URL straight to the Firestore emulator on my machine.

i.e. expo dev client (running on real iPhone 11) -> ngrok -> Firestore emulator (running on 2013 MBP).

Unfortunately, it's just plain not working. I load up the app and no logs appear in the ngrok tunnel, i.e. no requests are made. It's interesting because there's no errors either. But it doesn't appear to be connecting to the _real_ Firebase instance either, if I insert some test data into the live firestore, nothing gets returned.

**Firebase/Firestore emulator (running on port 8800):**

<img width="566" alt="FirestoreEmulator" src="https://user-images.githubusercontent.com/22147620/194703143-b7de1b97-9b72-41a1-82cd-dba660d2b0aa.png">

**Ngrok pointing to port 8800, but no connection/request logs appearing:**

<img width="738" alt="NgrokTunnel" src="https://user-images.githubusercontent.com/22147620/194703151-c96458df-d3ac-4dde-9bb0-252560d50585.png">

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `App.tsx`:

```javascript
import React, { useEffect, useState } from 'react';
import { Text, View } from 'react-native';
import firestore from '@react-native-firebase/firestore';

const emulatorHost = 'bc54-125-168-143-94.ngrok.io'; // Or whatever host ngrok gives
const emulatorPort = 80;

firestore().useEmulator(emulatorHost, emulatorPort);

export default function App() {
  const [name, setName] = useState('');

  useEffect(() => {
    firestore().collection('users').doc('user123').onSnapshot((res) => {
      setName(res.data()?.firstName || 'No user found');
    });
  }, []);

  return (
    <View style={{ alignContent: 'center', justifyContent: 'center', flex: 1 }}>
      <Text>{name}</Text>
    </View>
  );
}
```

#### `package.json`:

```json
{
  "name": "firestore-test",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start --dev-client",
    "ios": "expo start --ios",
    "build:ios": "eas build --profile development --platform ios"
  },
  "dependencies": {
    "@react-native-firebase/app": "15.7.0",
    "@react-native-firebase/auth": "15.7.0",
    "@react-native-firebase/firestore": "15.7.0",
    "expo": "46.0.13",
    "expo-build-properties": "~0.3.0",
    "expo-dev-client": "1.3.0",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~18.0.14",
    "@types/react-native": "~0.69.1",
    "typescript": "~4.3.5"
  },
  "private": true
}
```

#### app.json

```json
{
  "expo": {
    "name": "firestore-access-test",
    "slug": "firestore-access-test",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.namespace-matt.firestore-access-test",
      "googleServicesFile": "./configuration/GoogleService-Info.plist"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }
      ],
      "@react-native-firebase/app"
    ]
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 166.35 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /var/folders/jt/cryfj42d443cbq51n4gg5vl00000gn/T/yarn--1665224976949-0.3720505318354064/node
    Yarn: 1.22.19 - /var/folders/jt/cryfj42d443cbq51n4gg5vl00000gn/T/yarn--1665224976949-0.3720505318354064/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.4.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `15.7.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `firestore`
- **Are you using `TypeScript`?**
  - `Y` & `4.3.5`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You've been here before #6140 

I've never used ngrok so can't support it, sorry, no idea what it's doing to the connections or the setup, if it requires a PR to the docs or the code is in error somehow, I'd be happy to collaborate on a PR but you'll have to dig in and figure it out, I won't be installing ngrok to troubleshoot.

How does it work when you use the IP address and port of the MBP?

**Comment by pyramid-scheme-ceo** [comment]
Hey mate, yes indeed I have (and pleased to report that the auth module is working as expected haha, just that firestore isn't).

No worries, I'm happy to help out with the fix - could just use some pointers once I get around to that part 🙂

**Disclaimer:** None of what I'm about to explain below really relates to this library so I don't expect your help on it, but just an update on my progress.

I'm actually using ngrok becuase connecting to another local IP/port from my iOS device wasn't working for me and I couldn't work out why. When I have the firestore emulator running on port 8800 on my macbook and I make a get request to its index (which should return a basic "OK" page):
* I can connect locally by going to http://localhost:8800
* I can connect by forwarding a ngrok adress to port 8800 and then visiting that URL on a different machine (PC)
* Unfortunately I cannot connect using a different machine on the same network by navigating to `http://{macbook local IP}:8800` -- even when I turn my firewall entirely off.

However using the IP/port _does_ work if instead of running the emulator, I just run a basic express JS 'hello world' app, so I don't think it's my security which is the issue anymore as the requests seem to make it through just fine, provided it's connecting to anything other than the firebase emulators...

**Comment by pyramid-scheme-ceo** [comment]
...and of course after a few days of no success and deciding to write the above comment, I found the solution! By default, the emulators only open the port you've chosen for requests coming from _localhost_ specifically. If you want to open the port for everyone else on the network you have to change the config to have a defined host like so:
```
// firebase.json
{
  ...
  "emulators": {
    "firestore": {
      "port": 8800,
      "host": "0.0.0.0"
    }
  }
}
```

Now after doing that, I can connect to both the auth and firestore emulators using an IP address and port, which frankly is good enough for me - sorry for the bother 😂

I'm still more than happy to look into why using a domain rather than an IP doesn't work if it's something you'd like to see solved, but if you're happy to close this thread then I am too.

**Comment by mikehardy** [comment]
Yes! That has bitten me before as well, and now typically I do set the host to quad-0 in my firebase.json for emulator - subtle one that, glad you figured it out.

If you're unblocked, I'll close this - I've got more than enough other items to work through vs chasing the hostname issue. Good luck with your project

**Comment by ethanbonin** [comment]
@pyramid-scheme-ceo 

> ...and of course after a few days of no success and deciding to write the above comment, I found the solution! By default, the emulators only open the port you've chosen for requests coming from _localhost_ specifically. If you want to open the port for everyone else on the network you have to change the config to have a defined host like so:
> 
> ```
> // firebase.json
> {
>   ...
>   "emulators": {
>     "firestore": {
>       "port": 8800,
>       "host": "0.0.0.0"
>     }
>   }
> }
> ```
> 
> Now after doing that, I can connect to both the auth and firestore emulators using an IP address and port, which frankly is good enough for me - sorry for the bother 😂
> 
> I'm still more than happy to look into why using a domain rather than an IP doesn't work if it's something you'd like to see solved, but if you're happy to close this thread then I am too.

Hey, were you able to get the emulator working with `ngrok` by doing this setup? 

```json
{
  "emulators": {
    "firestore": {
      "port": 8800,
      "host": "0.0.0.0"
    }
}
```

```javascript
connectFirestoreEmulator(firestore, 'firebase-firestore.ngrok.io', 443);
```
Am I missing something??
I keep getting this error: 
```bash
 @firebase/firestore: Firestore (9.15.0): Connection WebChannel transport errored:
```

Thanks!

**Comment by djabif** [comment]
Thanks, but I need the firestore emulator to be served over https 😭

**Comment by djabif** [comment]
I finally got it working by setting ssl true in a hackish way. It's not ideal, but it's just for testing, so it's okay.

```
connectFirestoreEmulator(db, 'my-firestore.ngrok.io', 443);
// @ts-ignore
db['_settings']['ssl'] = true;
```

**Comment by ethanbonin** [comment]
> I finally got it working by setting ssl true in a hackish way. It's not ideal, but it's just for testing, so it's okay.
> 
> 
> 
> ```
> 
> connectFirestoreEmulator(db, 'my-firestore.ngrok.io', 443);
> 
> // @ts-ignore
> 
> db['_settings']['ssl'] = true;
> 
> ```

Awesome!!

**Comment by AlexRobinson66** [comment]
> // @ts-ignore
> db['_settings']['ssl'] = true;

Amazing! You have saved me - thank you! 🙏
