### ISSUE TITLE
[🐛] Bug -> _SharedEventEmitter.default.once is not a function

### ISSUE THREAD

**Issue by muzzamil76** [invertase/react-native-firebase#6599]
These are the package versions

    "@react-native-firebase/analytics": "15.7.0",
    "@react-native-firebase/app": "15.7.0",
    "@react-native-firebase/crashlytics": "15.7.0",
    "@react-native-firebase/messaging": "15.7.0",
    "@react-native-firebase/database": "14.11.2",

 "react-native": "0.68.2",
 
 Constantly I am having this issue and not able to test me firebase database 
any help please.

TypeError: _SharedEventEmitter.default.once is not a function. 
(In '_SharedEventEmitter.default.once(eventRegistrationKey, this._onOnceRemoveRegistration(eventRegistrationKey, listener))',
 '_SharedEventEmitter.default.once' is undefined)

**Comment by efstathiosntonas** [comment]
Don’t mix different package versions, the patch was introduced on `14.11.2`.
