### ISSUE TITLE
onAuthStateChanged returns a user after deleting and reinstalling app 

### ISSUE THREAD

**Issue by yasir-netlinks** [invertase/react-native-firebase#660]
As the title states , when I delete an app from simulator or iphone device and reinstall again, `onAuthStateChanged` still returns a user (already logged in). This is not happening on Android where it requires re-authentication when app reinstalled.

### Environment

1. Application Target Platform: iOS

3. Build Tools: xcode 9.1

4. React Native version: 0.50.3

5. RNFirebase Version: 3.0.6

6. Firebase Module: Auth

**Comment by Salakar** [comment]
Not sure what we can do about this, might need a solution like whats posted on this stackoverflow post: https://stackoverflow.com/questions/27893418/firebase-deleting-and-reinstalling-app-does-not-un-authenticate-a-user

But then that's not something this library could control, may just be a case of documentation.

**Comment by chrisbianca** [comment]
Closing in favour of https://github.com/invertase/react-native-firebase/issues/694 which has a workaround.
