### ISSUE TITLE
getCountFromServer not supported

### ISSUE THREAD

**Issue by goleary** [invertase/react-native-firebase#6654]
This was released in 9.11.0 on Oct 6th:
> Added getCountFromServer() (getCount() in the Lite SDK), which fetches the number of documents in the result set without actually downloading the documents.

https://firebase.google.com/support/release-notes/js#cloud-firestore_1

I'd love to be able to use this in React Native Firebase

**Comment by mikehardy** [comment]
getCount was added I think in v16.1 here, it is up and running

**Comment by goleary** [comment]
Got it. I searched through the docs and found nothing, and also searched the repo and found nothing for `getCountFromServer`.

Digging through the code I've found [the PR](https://github.com/invertase/react-native-firebase/commit/bd52301ad4ef35eeb4dbdab1bc4926db72d40949) where it was added.

Curious why `collectionRef.count()` was the chosen syntax? The firebase-js sdk uses `getCountFromServer()` which makes it clear why one would want to use this method (docs are not needlessly transmitted to the client).

Does `.count()` behave the same?

**Comment by mikehardy** [comment]
count() behaves the same, In this case I chose to mirror the work done on FlutterFire (also done by Invertase...) I didn't realize we deviated from the JS API. Something to look in to - I'll reopen it just for naming resolution, perhaps we answer to both APIs...
