### ISSUE TITLE
react-native-firebase Typescript support for Multi-factor Auth

### ISSUE THREAD

**Issue by SO2OS1EN45QGF81** [invertase/react-native-firebase#6661]
### Discussed in https://github.com/invertase/react-native-firebase/discussions/6656

<div type='discussions-op-text'>

<sup>Originally posted by **SO2OS1EN45QGF81** November  3, 2022</sup>
In the documentation it is mentioned to use
```
import auth from '@react-native-firebase/auth';
const multiFactorUser = await auth.multiFactor(auth());

...

const session = await multiFactorUser.getSession();
 and 
const verificationId = await auth().verifyPhoneNumberForMultiFactor(phoneOptions);
```
But it seems at least some of these functions are not available in Typescript ( verifyPhoneNumberForMultiFactor for example )
I am using v16.4.1
</div>

**Comment by mikehardy** [comment]
Thanks for reporting this, I think #6664 will fix it, could you take a look and see if it meets your expectatiosn?

**Comment by SO2OS1EN45QGF81** [comment]
I think something is missing in index.d.ts around line 317
Something like :
```
    /**
     * A multiFactor interface.
     */
    multiFactor(auth: FirebaseAuthTypes.Module): MultiFactorUser;
```

**Comment by mikehardy** [comment]
@SO2OS1EN45QGF81 can you post a PR for the same 🙏 ? I can do another release with a further modification
