### ISSUE TITLE
[📚]React Native Firebase - ML - CHANGE ME 

### ISSUE THREAD

**Issue by DamonGuzman** [invertase/react-native-firebase#6666]
## Documentation Feedback

The documentation references a package which no longer exists on NPM and I can't find it on GitHub either. This is in the following passage: 

"If you're looking for pre-trained models that run on the device, check out [the new standalone ML Kit](https://developers.google.com/ml-kit). Use the new [react-native-mlkit modules](https://www.npmjs.com/org/react-native-mlkit)) for most on-device use cases:

Text recognition
Image labeling
Object detection and tracking
Face detection and contour tracing
Barcode scanning
Language identification
Translation
Smart Reply"
---

![image](https://user-images.githubusercontent.com/106456287/200129473-80c1c018-e978-4d27-b805-045a75f8b927.png)
![image](https://user-images.githubusercontent.com/106456287/200129542-96584eab-9134-4baf-a6ac-1ca2edf803cf.png)

**Comment by mikehardy** [comment]
Hi there! Unfortunately that repo is private still since firebase upstream removed the APIs and we pulled the package here

To date, there has not been enough interest to result in development. In fact this is the first interest anyone has expressed in it in months and months! 

I believe this is the most functionality I've seen in the ecosystem at the moment, though it does not appear very active at the moment: https://github.com/agoldis/react-native-mlkit-ocr

We should update the related documentation to have current status

**Comment by AlkanV** [comment]
hello @mikehardy , i am also interested in this, i have take a look at but i saw same results, is there any update on this?

**Comment by mikehardy** [comment]
Hey there - no there is no update, you two are the first to mention any interest in machine language features in maybe a year :laughing: - they *are* firebase APIs and I would like to support them but with the exceedingly low interest I have not made them a priority at all, apologies.

There were two huge "firebase removed the APIs / extract to another package if possible" changes made around the same time, and admob had lots and lots of interest so we pursued it (https://github.com/invertase/react-native-google-mobile-ads/pulse/monthly) but the MLKit stuff just did not seem to justify the investment even though I am curious about the whole SDK. For me to work on it would require me personally needing it (I don't, apologies) or some funding I think. That is something that could perhaps be pursued with Invertase, who typically sponsor my work on Google SDKs in the react-native ecosystem

**Comment by CodingWithNobody** [comment]
Try this https://www.youtube.com/watch?v=mv4c2uTxR4U
