### ISSUE TITLE
Unable to build project with use_frameworks!

### ISSUE THREAD

**Issue by tirrorex** [invertase/react-native-firebase#667]
### Issue

Been following the documentation to install this in a swift project.
According to the documentation i should put the firebase librairies inside a folder named firebase at the /ios folder.
Digging a bit it seems the documentation is talking about the ios folder inside nodes_modules/RnFirebase, or is it the one created by react-native ? if someone could confirm that would be great.
Anyway, i did copy everything twice but no luck.

Doing so, the rnfirebase librairie cannot find firebaseCore headers.
Manually changing the search path for the header in the .m file gives me another error : 

> Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIROptions", referenced from:
      objc-class-ref in RNFirebase.o
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in RNFirebase.o
ld: symbol(s) not found for architecture arm64

So i am currently stuck on this (would like to know why the librairy doesn't find the headers in the first place though).

Setting -ObjC to Other Linker Flags in Build Settings of the RNFirebase target didn't work, arm64 is in the valid architecture list and setting Build Active Architecture Only to No in both targets (ios project and RNFirebase)  didn't work either.

### Environment

1. Application Target Platform: 

iOS

2. Development Operating System: 

OSX high sierra

3. Build Tools: 

xcode 9.2 beta (building on . real device running ios 11.2)

4. React Native version: 

RN 0.50.3

5. RNFirebase Version: 

version 3.1.1, i confirmed looking at the code that indeed there is a commit with added header search paths.
Related to this commit : https://github.com/invertase/react-native-firebase/commit/1fdb9074967f5c5438c4d657fce09d83cfcbe2bc

6. Firebase Module: 

Just firebase core and analytics.

ps : did anyone manage to make this work with a swift project ?

**Comment by tirrorex** [comment]
Also installing the module via yarn fails : 

> yarn add https://github.com/invertase/react-native-firebase
yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning react-native > connect@2.30.2: connect 2.x series is deprecated
error Error parsing JSON at "https://github.com/invertase/react-native-firebase/package.json", "Unexpected token w in JSON at position 0".

**Comment by tirrorex** [comment]
For people that have troubles to build this on swift, the solution of @kyle-ssg works(https://github.com/invertase/react-native-firebase/issues/332), just add firebase through your podfile and add ${BUILT_PRODUCTS_DIR} recursive to RNFirebase target framework search paths.
It's a workaround but it works so...

**Comment by tirrorex** [comment]
Well, workaround works for building but project fails to archive, false hope.

**Comment by kyle-ssg** [comment]
@tirrorex  Do you get the same error on archive? I've published a couple apps with this since finding this issues

**Comment by tirrorex** [comment]
@kyle-ssg the only thing react-native link does is adding the path for react-native-firebase in the podfile.
(by thre way i did tried that, and it fails because the framework cannot find firebaseCore headers)
My project is in swift which seems to be the root cause for all my issues ?
Don't know if anybody manage to build this properly with a swift project.

I spent too much time on this already, if i don't manage to find a proper fix for tomorrow morning i will just copy paste all the sources inside my project.

**Comment by tirrorex** [comment]
Dirty solution that works even for archive is to import all needed sources (.h and .m files, NOT the folders) inside my project.
Will do for now but i am open to any working suggestion :)

**Comment by chrisbianca** [comment]
`react-native link` now supports `use_frameworks!` as part of v3.2.0

**Comment by tirrorex** [comment]
@chrisbianca you should wait for people to test that everything is working before closing issues mate

**Comment by chrisbianca** [comment]
@tirrorex We choose to run the project by closing down issues as we release fixes.  This keeps our issues list as clean as possible rather than having to wait, sometimes weeks for confirmation of a fix.  By all means, feel free to re-open the issue if the new release isn't working for you, mate.

**Comment by tirrorex** [comment]
@chrisbianca it doesn't work.
Did you guys test your release on a swift project ?
I tried your method before (the one you are using in the 3.2 release) and the problem is the order of compilation, react-native must be compiled before react-native-firebase in order for this method to work.
I also had other issues and the only way i found to have something reliable is to NOT import react-native-firebase xcodeproj but to import the sources instead.
You don't want to import the lib.a in your project, just the sources for the extern module.

**Comment by Naoto-Ida** [comment]
Any solutions for this? We also have a Swift-based project.

**Comment by tirrorex** [comment]
@Naoto-Ida best solution i found so far was to copy paste the objective-c sources in my project

**Comment by chrisbianca** [comment]
@tirrorex Take a look at the release notes for: https://github.com/invertase/react-native-firebase/releases/tag/v3.2.2

This made some header changes and talks through how to ensure that RN gets compiled before RNFirebase.  Let me know if it works for you and I'll update the documentation to add a section on how to get this working.

**Comment by tirrorex** [comment]
We are switching to a full react-native project (with react-native init so objective-c project) so i won't be able to try this for a while.
