### ISSUE TITLE
Firebase iOS SDK "pod 'undefined'" for notification

### ISSUE THREAD

**Issue by kishanevery** [invertase/react-native-firebase#6675]
<img width="374" alt="Screenshot 2022-11-08 at 2 17 24 PM" src="https://user-images.githubusercontent.com/95119878/200517752-96e4bfc9-2495-449f-9b78-5acb320bf6e6.png">

i am getting this error when i run application.

**Comment by mikehardy** [comment]
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

Those are both good guides as well
