### ISSUE TITLE
☂️ Bring Modular V9 to React Native Firebase 

### ISSUE THREAD

**Issue by Lyokone** [invertase/react-native-firebase#6705]
This issue will track the progress and gather feedback for bringing the V9 API of Firebase to React Native Firebase.

The objective is to have a compatible API so people may adopt the V9 API if they wish, or if they were already using firebase-js-sdk v9 and find they need some native features provided by react-native-firebase, they may adopt react-native-firebase with zero code changes.

## Modules
- [x]  App: #6694
- [x] app-check https://github.com/invertase/react-native-firebase/pull/6912       
- [x] app-distribution https://github.com/invertase/react-native-firebase/pull/7307
- [x] analytics https://github.com/invertase/react-native-firebase/pull/6816      
- [x] auth  https://github.com/invertase/react-native-firebase/pull/7015            
- [x] crashlytics https://github.com/invertase/react-native-firebase/pull/7283
- [x] database https://github.com/invertase/react-native-firebase/pull/7136
- [x] dynamic-links https://github.com/invertase/react-native-firebase/pull/7296
- [x] firestore https://github.com/invertase/react-native-firebase/pull/7235
- [x] functions    https://github.com/invertase/react-native-firebase/pull/6764    
- [x] in-app-messaging https://github.com/invertase/react-native-firebase/pull/7306
- [x] installations   https://github.com/invertase/react-native-firebase/pull/7095 
- [x] messaging  https://github.com/invertase/react-native-firebase/pull/6806      
- [x] ml https://github.com/invertase/react-native-firebase/pull/7390
- [x] perf https://github.com/invertase/react-native-firebase/pull/6771    
- [x] remote-config #6868 
- [x] storage  #6958

**Comment by jeveloper** [comment]
Github bot doesn't respect humans needing to enjoy some of that down time and self care. Tsk tsk.
Enjoy the holidays all and thank you for all the wonderful work over many years!

**Comment by mikehardy** [comment]
The bot doesn't sleep no

**Comment by adrianotadao** [comment]
hey @Lyokone @mikehardy, thank you for your hard work on it! #heroes

I'm quite interested in the **firestore** item, is this progress list up to date?

Thank you

**Comment by Lyokone** [comment]
Hello @adrianotadao, Firestore hasn't yet been brought to modular v9 APIs. It will probably be dealt with in the coming weeks.

**Comment by Slapbox** [comment]
If I'm not mistaken, at least one of these items and possibly several are released and need to be checked off in this issue.

`storage` appears to be exposed but is unchecked: https://github.com/invertase/react-native-firebase/pull/6958 

I guess `auth` and `database` are a ways off since they don't show any relevant PRs on the list? Or do those maybe need updating too?

@Lyokone

**Comment by mikehardy** [comment]
@Slapbox only storage status was out of date, we just merged+released that one

If there is no relevant PR then the work is not in progress yet, we don't provide ETAs but they are all "next on the list" basically. Slowly but surely...

**Comment by Slapbox** [comment]
Not stale.

**Comment by jeveloper** [comment]
Github bot doesn't seem to care for work-life balance. Let's not be pushed into a rat race :) 
Thanks for the great work.

**Comment by Slapbox** [comment]
Not stale. Thanks to the team and the community for the ongoing great work!

**Comment by Slapbox** [comment]
Not stale.

**Comment by RobertSasak** [comment]
I am unable to see any exposed modular functions. Is it possible to try, for instance, modular storage functions in the latest 18.2.0 release? If yes, could you please provide an example?

**Comment by apetta** [comment]
Would be great to try this!

**Comment by Slapbox** [comment]
Database work is done and can be checked off!

https://github.com/invertase/react-native-firebase/pull/7136

Thanks @exaby73 and others who worked on it!

**Comment by exaby73** [comment]
Just a couple more items to be checked off :)

**Comment by Slapbox** [comment]
Are there any known changes in Firebase 10 which these changes might not be compatible with?

**Comment by exaby73** [comment]
We'd have to compare the release notes I guess, starting [with the initial release of v10](https://firebase.google.com/support/release-notes/js#version_1000_-_july_6_2023). We can worry about that once we catch up to V9 first :)

**Comment by exaby73** [comment]
All modules have been migrated to the modular APIs, with the merge of https://github.com/invertase/react-native-firebase/pull/7390. This has been a long running effort but we've finally gotten there 🎉

**Comment by AbenezerBayeh** [comment]
Having trouble converting Firebase modular v9 code to the modular React Native Firebase equivalent. Can you please assist by providing the steps to do the following commands:

`
import {
  doc,
  updateDoc,
  getDoc,
  onSnapshot,
  arrayUnion,
  arrayRemove,
  writeBatch
} from 'firebase/firestore';

const batch = writeBatch(db);
const userRef = doc(db, 'users', userID);

**batch.update(userRef,{
   [`user.books`]: arrayUnion(bookName),
   [`user.visits`]: increment(1)
})**

Or

**await updateDoc(userRef, {
    [`user.books`]: arrayRemove(bookName),
 });**


AND

**const userSnap = await getDoc(userRef); 
var documentData = userSnap.data();**

Or 

**const unsubscribe = onSnapshot(doc(db, 'users', userID), snap => {
	const documentData = snap.data();
	…
});**
`

Thank you!

**Comment by RobertSasak** [comment]
Simply import from '@react-native-firebase/auth' as you woule normally do.
```ts
import {
  getAuth,
  onAuthStateChanged,
  signInAnonymously,
} from '@react-native-firebase/auth'
```
However currently there seems to be only few Typescript definition files. So not TS support yet. 

I openned a discussion about using modular syntax at https://github.com/invertase/react-native-firebase/discussions/7597

**Comment by younes0** [comment]
@RobertSasak we could open an issue about the missing TS definitions.
