### ISSUE TITLE
:fire: [🐛] [iOS] Messaging - Background notifications are received but not displayed

### ISSUE THREAD

**Issue by AlixH** [invertase/react-native-firebase#6706]
## :fire: Issue

Describe your issue here

On iOS, when sending remote push notifications from my server via Firebase Admin SDK, the notifications are received by the iPhone (the callback inside setBackgroundMessageHandler is getting called), but not notification is displayed on the screen !
Server-side, I have put 'ContentAvailable: true'. Without that, the background handler was not being called, despite the doc stating that it's only required for data-only messages. See https://rnfirebase.io/messaging/usage#data-only-messages and screenshot below
<img width="774" alt="Screenshot 2022-11-17 at 11 19 20" src="https://user-images.githubusercontent.com/32574035/202420781-0251f589-f3f7-4304-ab63-a4975dadfb0d.png">

Here is an snippet of my server-code:
```js
// Build the notification
const message =  {
    notification: {
          title,
          body,
          icon: '@drawable/ic_stat_ic_notification',
          sound: 'default',
          badge: '0',
          color: severity ? severity : NotificationSeverity.INFO,
          android_channel_id: 'e-Mobility'
    },
    data: {
          tenantID: tenant.id,
          tenantSubdomain: tenant.subdomain,
          notificationType,
          ...data
    }
}

// Send the notification
const response = await admin.messaging(app). sendToDevice(
            user.mobileData.mobileToken,
            message,
            { priority: 'high', contentAvailable: true, timeToLive: 60 * 60 * 24 }
          );
```

Mobile code:

index.js
```tsx
// Callback called when notification received by device in background state
messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('Message handled in the background!', remoteMessage);  //<--- this is getting called !
});

function HeadlessCheck({ isHeadless }) {
  if (isHeadless) {
    // App has been launched in the background by iOS, ignore
    return null;
  }

  return <App  navigation={null}/>;
}

AppRegistry.registerComponent(appName, () => HeadlessCheck);
```

NotificationManager.tsx

```tsx
    const initialNotification = await messaging().getInitialNotification();
    if (initialNotification) {
      this.handleNotification(initialNotification);
    }
    // Listen for notifications when the app is in background state
    messaging().onNotificationOpenedApp((remoteMessage: FirebaseMessagingTypes.RemoteMessage) => {
      this.handleNotification(remoteMessage);
    });
    messaging().onMessage((message: FirebaseMessagingTypes.RemoteMessage) => {
      console.log(message);  //<---- this is getting called !
    });
```

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
    "@react-native-firebase/app": "^16.2.0",
    "@react-native-firebase/messaging": "^16.2.0",
    "@react-navigation/drawer": "^6.4.3",
    "@react-navigation/material-bottom-tabs": "^6.2.2",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/stack": "^6.2.2",
    "@stripe/stripe-react-native": "^0.19.0",
    "axios": "^0.22.0",
    "base-64": "^1.0.0",
    "buffer": "^6.0.3",
    "color": "^3.2.1",
    "deepmerge": "^4.2.2",
    "http-status-codes": "^2.1.4",
    "i18n-js": "^3.8.0",
    "intl": "^1.2.5",
    "intl-messageformat": "^9.11.4",
    "intl-unofficial-duration-unit-format": "^3.1.0",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.3",
    "native-base": "^3.4.13",
    "react": "17.0.2",
    "react-native": "0.67.4",
  }
```

#### `firebase.json` for react-native-firebase v6:

I have not created a firebase.json but I am using v6

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

You can see that I have not put use_frameworks! but the lib still compiles on both platforms, could the problem be here ?
```ruby
platform :ios, '12.0'

target 'app' do
  project 'app.xcodeproj'
  config = use_native_modules!
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config["../node_modules/react-native"],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Required for Firebase
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  # Camera Permission
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  target 'tests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "RNBootSplash.h"
#import "Orientation.h"
#import <React/RCTLinkingManager.h>
#import <GoogleMaps/GoogleMaps.h>
#import <Firebase.h>
#import "RNFBMessagingModule.h"

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
   #ifdef FB_SONARKIT_ENABLED
     InitializeFlipper(application);
   #endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  NSDictionary *appProperties = [RNFBMessagingModule addCustomPropsToUserProps:nil withLaunchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"app" initialProperties:appProperties];

  if (@available(iOS 13.0, *)) {
    rootView.backgroundColor = [UIColor systemBackgroundColor];
  } else {
    rootView.backgroundColor = [UIColor whiteColor];
  }

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window
{
  return [Orientation getOrientation];
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
  return [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
}
@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 139.53 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: Not Found
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [X] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `16.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/messaging`
- **Are you using `TypeScript`?**
  - `Y` & `4.3.4`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
:thinking: I find this strange in a couple ways -

1- for "mixed" FCM JSON (that is, "data" and "notification" block) the receiving device should behave similar to the notification-content only case. That is, your background handler should not be called, and the firebase-ios-sdk should display a visible notification without booting the app. Then when/if the user interacts with the notification in a way that should open the app, you should see the data contents in getInitialNotification. So, the handler should not be called and I don't understand why it is...

2- most people that want to post a visible notification on iOS in response to FCM JSON receipt on device integrate Notifee.app module instead. Why? the firebase-ios-sdk does not offer much visual control over the notification so you cannot do any branding, whereas with the Notifee module (and optionally the notification service extension) you have the opportunity to intercept the visual notification post and skin it prior to the user seeing it.


In my case, I just send a notification block only (no data block) in my FCM JSON, and firebase-ios-sdk correctly posts the notification in a plain but functional way. Have you tried that?

**Comment by mikehardy** [comment]
> You are saying that the normal behavior of the background handler for mixed JSON is to not be called ? In the doc I see that it should not be called only when the payload is data-only thinking

That's my understanding, but software never fails to surprise. It is/was my understanding that if FCM JSON contains notification, you get a visible notification immediately (assuming you are not in DND - a "fun" gotcha) with no handlers called

https://firebase.google.com/docs/cloud-messaging/concept-options#notification-messages-with-optional-data-payload

**Comment by AlixH** [comment]
> > You are saying that the normal behavior of the background handler for mixed JSON is to not be called ? In the doc I see that it should not be called only when the payload is data-only thinking
> 
> That's my understanding, but software never fails to surprise. It is/was my understanding that if FCM JSON contains notification, you get a visible notification immediately (assuming you are not in DND - a "fun" gotcha) with no handlers called
> 
> https://firebase.google.com/docs/cloud-messaging/concept-options#notification-messages-with-optional-data-payload

My understanding of the sentence "When in the background, apps receive the notification payload in the notification tray, and only handle the data payload when the user taps on the notification", is that, indeed notifications are displayed. But the last part about payload handling means (I think) that only when the user taps the notification, either the getInitialNotification method or the onNotificationOpenedApp callback is called. It does not mean that the callback of setBackgroundMessageHandler is called when the user tap the notification.

**Comment by upngo** [comment]
In order for the setBackgroundMessageHandler() to be called I need the top level
` "content_available" => true `
for both notification, mixed and data only messages.

**Comment by Varofon** [comment]
Can confirm that for mixed (notification + data) remote messages `contentAvailabe: true` is required to trigger background handler. 
Having that in documentation would be helpful for the future
