### ISSUE TITLE
React Native Expo FireBase Dependency not able to connect 

### ISSUE THREAD

**Issue by WhoAbhigyan** [invertase/react-native-firebase#6708]
{
  "dependencies": {
    "dayjs": "*",
    "firebase": "*",
    "prop-types": "*",
    "expo-constants": "~13.2.4",
    "react-navigation": "4.1.1",
    "recat-navigation": "*",
    "@expo/vector-icons": "^13.0.0",
    "react-native-paper": "4.9.2",
    "react-native-screens": "~3.15.0",
    "react-native-lightbox": "*",
    "react-navigation-stack": "*",
    "@react-navigation/native": "^3.6.5",
    "react-native-gifted-chat": "*",
    "react-native-parsed-text": "*",
    "react-native-communications": "*",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-typing-animation": "*",
    "react-native-safe-area-context": "4.3.1",
    "@expo/react-native-action-sheet": "*",
    "@react-native-community/masked-view": "^0.1.0"
  }
}

**Comment by mikehardy** [comment]
Looks like you may have hit the create button before you were ready but on a preliminary scan of your dependencies: you are not using any `@react-native-firebase` modules, so this is not the correct repo.

**Comment by mikehardy** [comment]
Going to close this as there was no update, can always open a new issue as needed
