### ISSUE TITLE
[🔥] [🐛] [iOS] - Notification handlers getting called multiple times 

### ISSUE THREAD

**Issue by AlixH** [invertase/react-native-firebase#6709]
## :fire: Issue

Describe your issue here

On iOS, when sending remote push notifications from my server via Firebase Admin SDK, the notifications are received by the iPhone. When the app is in the background and I tap a notification, the app is foregrounded but the onNotificationOpenedApp callback is getting called multiples times (more than 10 times sometimes)
Also, the same behavior occurs with foregoround notifications: the onMessage callback is getting called multiple times

Here is an snippet of my server-code:
```js
// Build the notification
const message =  {
    notification: {
          title,
          body,
          icon: '@drawable/ic_stat_ic_notification',
          sound: 'default',
          badge: '0',
          color: severity ? severity : NotificationSeverity.INFO,
          android_channel_id: 'e-Mobility'
    },
    data: {
          tenantID: tenant.id,
          tenantSubdomain: tenant.subdomain,
          notificationType,
          ...data
    }
}

// Send the notification
const response = await admin.messaging(app). sendToDevice(
            user.mobileData.mobileToken,
            message,
            { priority: 'high', contentAvailable: true, timeToLive: 60 * 60 * 24 }
          );
```

Mobile code:

index.js
```tsx
// Callback called when notification received by device in background state
messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('Message handled in the background!', remoteMessage);  //<--- this is getting called !
});

function HeadlessCheck({ isHeadless }) {
  if (isHeadless) {
    // App has been launched in the background by iOS, ignore
    return null;
  }

  return <App  navigation={null}/>;
}

AppRegistry.registerComponent(appName, () => HeadlessCheck);
```

NotificationManager.tsx

```tsx
    const initialNotification = await messaging().getInitialNotification();
    if (initialNotification) {
      this.handleNotification(initialNotification);
    }
    // Listen for notifications when the app is in background state
    messaging().onNotificationOpenedApp((remoteMessage: FirebaseMessagingTypes.RemoteMessage) => {
      this.handleNotification(remoteMessage);
    });
    messaging().onMessage((message: FirebaseMessagingTypes.RemoteMessage) => {
      console.log(message);  //<---- this is getting called !
    });
```

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
    "@react-native-firebase/app": "^16.2.0",
    "@react-native-firebase/messaging": "^16.2.0",
    "@react-navigation/drawer": "^6.4.3",
    "@react-navigation/material-bottom-tabs": "^6.2.2",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/stack": "^6.2.2",
    "@stripe/stripe-react-native": "^0.19.0",
    "axios": "^0.22.0",
    "base-64": "^1.0.0",
    "buffer": "^6.0.3",
    "color": "^3.2.1",
    "deepmerge": "^4.2.2",
    "http-status-codes": "^2.1.4",
    "i18n-js": "^3.8.0",
    "intl": "^1.2.5",
    "intl-messageformat": "^9.11.4",
    "intl-unofficial-duration-unit-format": "^3.1.0",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.3",
    "native-base": "^3.4.13",
    "react": "17.0.2",
    "react-native": "0.67.4",
  }
```

#### `firebase.json` for react-native-firebase v6:

I have not created a firebase.json but I am using v6

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

You can see that I have not put use_frameworks! but the lib still compiles on both platforms, could the problem be here ?
```ruby
platform :ios, '12.0'

target 'app' do
  project 'app.xcodeproj'
  config = use_native_modules!
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config["../node_modules/react-native"],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Required for Firebase
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  # Camera Permission
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  target 'tests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "RNBootSplash.h"
#import "Orientation.h"
#import <React/RCTLinkingManager.h>
#import <GoogleMaps/GoogleMaps.h>
#import <Firebase.h>
#import "RNFBMessagingModule.h"

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
   #ifdef FB_SONARKIT_ENABLED
     InitializeFlipper(application);
   #endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  NSDictionary *appProperties = [RNFBMessagingModule addCustomPropsToUserProps:nil withLaunchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"app" initialProperties:appProperties];

  if (@available(iOS 13.0, *)) {
    rootView.backgroundColor = [UIColor systemBackgroundColor];
  } else {
    rootView.backgroundColor = [UIColor whiteColor];
  }

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window
{
  return [Orientation getOrientation];
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
  return [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
}
@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 139.53 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: Not Found
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [X] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `16.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/messaging`
- **Are you using `TypeScript`?**
  - `Y` & `4.3.4`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Are you perhaps registering handlers multiple times somehow, perhaps via hot-refresh or incorrect useEffect dependency or similar?

Curious if this works correctly on clean launch and then builds up or if it's something else.

I can say, I've never seen this behavior in my own apps, so I suspect something project-specific.

Not likely to be the root cause here, but these are out of date, with react-native actually being out of support at this point I think:

```
    "@react-native-firebase/app": "^16.2.0",
    "@react-native-firebase/messaging": "^16.2.0",
    "react-native": "0.67.4",
```

**Comment by mikehardy** [comment]
This will be project-specific, something about your code is registering listeners without unregistering them somehow.

*or* it could be the version, and this:

> I did not want to upgrade react-native because their own doc sates that the new architecture is not stable yet

...just means "don't use new architecture". It's a specific mode that you have to enable to use. And you don't have to enable it, you don't have to use it. In fact, react-native-firebase requires `use_frameworks` for iOS, and new architecture mode is specifically incompatible with use_frameworks at the moment so you cannot use it anyway.

But that is no reason not to update react-native. It works just fine in 0.70.6 *without* new architecture mode enabled. I test it frequently and base my work projects on current stable (0.70.6 right now...) in order to make sure it works for everyone.

**Comment by AlixH** [comment]
> This will be project-specific, something about your code is registering listeners without unregistering them somehow.

Ok, I will try to look into this
> 
> _or_ it could be the version, and this:
> 
> > I did not want to upgrade react-native because their own doc sates that the new architecture is not stable yet
> 
> ...just means "don't use new architecture". It's a specific mode that you have to enable to use. And you don't have to enable it, you don't have to use it. In fact, react-native-firebase requires `use_frameworks` for iOS, and new architecture mode is specifically incompatible with use_frameworks at the moment so you cannot use it anyway.
> 
> But that is no reason not to update react-native. It works just fine in 0.70.6 _without_ new architecture mode enabled. I test it frequently and base my work projects on current stable (0.70.6 right now...) in order to make sure it works for everyone.

I see, but precisely about use_frameworks!, when I remove it from my Podfile, the project builds and runs, so I don't understand the purpose of it. Tbh there are still several things I don't get about the Podfile, like why did I have to add the following lines inside it
```
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
```

**Comment by mikehardy** [comment]
This is getting far afield from your initial problem but these lines, do not add them:

```
pod 'GoogleUtilities', :modular_headers => true
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
```

Those are workarounds for people attempting to avoid the use of `use_frameworks`. I do not support configurations like that, and I want to state in clear terms

1- firebase-ios-sdk requires use_frameworks
2- so we require `use_frameworks`


If you add the required `use_frameworks` to your Podfile, you then should remove the workaround-modular_headers stuff (I am tempted to say "junk") and then you'll find that it will not build without use_frameworks.

The only reason it builds with or without use_frameworks now is because you have those workaround lines in place, but you'll find that if you use the storage or functions modules now the build still won't work, and as more upstream modules convert to swift and require use_frameworks *strictly* (with no workarounds, as far as I know) those modules will fail too.

remove the workaround modular header lines, add `use_frameworks! :linkage => :static`, update react-native, continue forward...

**Comment by AlixH** [comment]
So, I have searched for an issue about the subscribtion/unsubscribtion. This is what I have found out so far:
- From quit state, the registration of the onMessage handler is done only one time
- For every other app foregrouding, the registration is done exactly two times

This is how I am performing the subscribe/unsubscribe:

App.tsx
```tsx
public async componentDidMount() {
    ...
    this.notificationManager = NotificationManager.getInstance();
    this.notificationManager.setCentralServerProvider(this.centralServerProvider);
    await this.notificationManager.start();  // <--- Listen for notifications
    ...
  }

  public componentWillUnmount() {
   ...
   // Stop Notifications
   this.notificationManager?.stop(); // <--- Stop listening
   ...
  }
```
NotificationManager.tsx

```tsx
  public async start(): Promise<void> {
    // Check initial notification when app was closed
    const initialNotification = await messaging().getInitialNotification();
    if (initialNotification) {
      this.handleNotification(initialNotification);
    }
    // Listen for notifications when the app is in background state
    messaging().onNotificationOpenedApp((remoteMessage: FirebaseMessagingTypes.RemoteMessage) => {
      this.handleNotification(remoteMessage);
    });
    // Listen for notifications when app is in foreground state
    this.removeForegroundNotificationListener = messaging().onMessage((remoteMessage: FirebaseMessagingTypes.RemoteMessage) => {
      Alert.alert(remoteMessage.notification.title, remoteMessage.notification.body);
    });  // <--- Register, this is called one time from quit state, two times then
  }

  public stop() {
    this.removeForegroundNotificationListener();  //<---- Unregister
  }
```

**Comment by mikehardy** [comment]
You should refactor those listener registrations out of component mount to whatever app startup bootstrap logic you have, I think.

**Comment by AlixH** [comment]
I don't really understand. In the doc, it's done inside the useEffect hook

**Comment by mikehardy** [comment]
I don't know what to tell you other than these two things that I know:
- no one else is reporting this (read as: you have a project-specific problem, if it was a problem with the module emitting events incorrectly, there would be lots and lots of reports - there are not - so it is a problem in your project)
- accumulating subscribers is a classic register/deregister imbalance (why is it happening in your project? I don't know, there are lots of ways to do it, no one way is "the way", but if you are imbalanced whatever way you are doing it is not correct)

As far as I can tell based on those things this is not really actionable in this repo, it is not going to result in a change here as far as I can tell, though clearly something in your project will need to change to bring register/deregister calls back into balance on lifecycle.

I still recommend pulling these register / de-register calls out of any component lifecycle and doing them on app lifecycle but that's me.

If you can show me how this module is double-emitting events *to the same listener* then we have an issue here, but it will need a minimal reproducible example.

If this module is only emitting one event to each listener, it's project-specific and this issue is headed to close

**Comment by AlixH** [comment]
It appears that my App root component is mounted twice, so the call to start the listeners are called twice as well.
Very surprisingly, this only happens in iOS. In Android, the root component is not event unmounted when the ap in backgrounded

**Comment by AlixH** [comment]
Ok so here is what I have founs out about my app lifecycle (still on iOS):
When launching the app:
- App root componentDidMount is called
- Notification listener starts

When backgrounding the app:
- App root componentWillUnmount is called
- Notification listener stops
- App root component ComponentDidMount is called
- App root component ComponentWillUnmount is called
- App root component ComponentDidMount is called

When opening the app again:
- Notification listener start **twice**

I am totally clueless

**Comment by yushanwebdev** [comment]
This solves the problem very nicely. It will be really helpful for the developers if this answer added to the documentation @mikehardy 

> the problem is because the notification listener is not getting cleared/removed when the component is unmounted, here's the solution:
> 
> ```
> useEffect(() => {
>   // assign the listener to a variable
>   const listener = messaging().onNotificationOpenedApp(async remoteMessage => {
>     .........
>   })
> 
>   // and remove it when your component gets unmounted
>   return () => listener()
> }, []);
> ```
