### ISSUE TITLE
[🐛] IOS crashlytics error

### ISSUE THREAD

**Issue by Quintis1212** [invertase/react-native-firebase#6712]
Hi , i have a crashlitic on my react-native project:
```
    "@react-native-firebase/app": "^10.5.0",
    "@react-native-firebase/crashlytics": "^10.5.1",
    "react-native": "0.68.0",
```
In android all is okey , but on ios I have an issue. When I paste 
```
import crashlytics from '@react-native-firebase/crashlytics';
```
 I have an error: 
```
Error: No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()
```
Does anyone knows how to solve the issue ?

**Comment by mikehardy** [comment]
```
 "@react-native-firebase/app": "^10.5.0",
    "@react-native-firebase/crashlytics": "^10.5.1",
```

This is not even worth looking into, on versions that old - they are way out of support. Here's knowledge on how to upgrade: https://invertase.io/blog/react-native-firebase-versioning

In general though, looks like a failure to follow the basic integration steps in AppDelegate implementation, where you import Firebase then call `[FIRApp configure]`, https://rnfirebase.io/#configure-firebase-with-ios-credentials

This is *definitely* not a problem with react-native-firebase, it is a project-specific integration problem. It will not result in any change in this module (not even in the documentation), so I'm going to close this as it is not an error
