### ISSUE TITLE
[🐛] IOS import crashlytics  cause error 

### ISSUE THREAD

**Issue by Quintis1212** [invertase/react-native-firebase#6717]
import crashlytics  cause error  : 
```
Error: No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()
```

Config: 
```
    "@react-native-firebase/app": "^16.4.5",
    "@react-native-firebase/crashlytics": "^16.4.5",
     "react-native": "0.68.0",
```
AppDelegate: 
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];
  [FIRApp configure];
  return YES;
}
```
 I was updating crashlytics from 10-th version. I used  https://rnfirebase.io/#configure-firebase-with-ios-credentials and  https://rnfirebase.io/crashlytics/usage .Please , any help

**Comment by mikehardy** [comment]
Hi there!
There are quite a few ways things can go wrong, and it's not possible to work through each one (certainly not with the minimal details you've included here, contrary to our template)

Here's a script that goes from start to finish and works correctly, with crashlytics - you should read it to make sure you have done the integration correctly and/or run it to verify that your project looks like the result of the script https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

I can verify with my own project, which I have been running all weekend long that crashlytics works, so this is definitely project-specific + will not result in a change in this module and is thus not an actionable issue so I'll close it

**Comment by Quintis1212** [comment]
@mikehardy thank you for help, but how I can run [make-demo.sh](https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh) script ? I have a windows

**Comment by mikehardy** [comment]
@Quintis1212 development on windows is not supported well, because it does not allow for iOS development and thus is not really a valid react-native development environment. It may work on WSL via ubuntu, I run it on linux sometimes but it has been a while. You may like https://github.com/kholia/OSX-KVM which I use to create OSX virtual machines, seems to work well with monterey (but not ventura yet)

**Comment by Quintis1212** [comment]
@mikehardy  I have also a macbook. Torun your script I must type: 
```
$ bash ./make-demo.sh

```
? 
And where I must put this script ? In the ios folder ?

**Comment by mikehardy** [comment]
@Quintis1212 the script is unsupported, it is just a demonstrator + learning tool. I count on you to read the script and learn from it. If you do that you'll see it does an `npx react-native init ...` that is, it creates an *entirely new project*, from scratch. You will want to do that somewhere in a temporary folder most likely.

**Comment by Quintis1212** [comment]
@mikehardy so this script create a react-native project with stable firebase ?

**Comment by mikehardy** [comment]
> I count on you to read the script and learn from it
