### ISSUE TITLE
Typo in the Auth Starter Kit page, the price need to be corrected

### ISSUE THREAD

**Issue by assurancetourix** [invertase/react-native-firebase#672]
Hello,

Many thanks for the good job with react native firebase.

I have just seen the Auth Starter Kit is sold 75$
https://rnfirebase.io/kits/auth-starter

It is an issue as it should probably be 7.5$

Taken seriously, if it is really that price of 75 $, it is way too much in my humble opinion. Or I hope the price will include other kits.

**Comment by chrisbianca** [comment]
@assurancetourix how long do you think it would take to build the same functionality yourself?

**Comment by assurancetourix** [comment]
Hi chrisbianca, probably several days or weeks alone, but if everyone can contribute it is not the same model. I was just hoping this kind of samples would be free so that the community could also make it evolve. Or at least with a more reasonnable cost, 

Not my will to start a vain discussion, but I really think 75 is too much, but maybe that's because I am an independant.

Good luck!

**Comment by chrisbianca** [comment]
You're right, it is a couple of weeks work and whilst we'd love to give the starter kit away for free, we need some way of funding and justifying the vast amount of time that the three of us spend building, maintaining and supporting the underlying **free** `react-native-firebase` library.  The starter kit is one way of doing this and will allow us to continue making the library better for everybody.

$75 to save yourself a couple of weeks work seems like a pretty good deal to me whether you're independent or not, but we'll take the feedback on pricing under consideration.

**Comment by assurancetourix** [comment]
Said like this that's convincing:-) 
By the way this kind of starter kit for Cloud Messaging could reach its audience.
All the best!
