### ISSUE TITLE
Getting building error "property with 'retain (or strong)' attribute must be of object type"

### ISSUE THREAD

**Issue by kjp151087** [invertase/react-native-firebase#6724]
Hello, 

We are getting error in react native project, 
We are adding firebase analytics using below package "@react-native-firebase/analytics": "^16.4.6" 

but for ios we are getting below while making build 

<img width="990" alt="Screenshot 2022-11-25 at 3 10 22 PM" src="https://user-images.githubusercontent.com/71250508/203949157-63b24a7f-89f0-4c61-b422-63252d4eb3c1.png">

Please can anyone help me for fixing this error. 

Thanks

**Comment by mikehardy** [comment]
You've ignored the issue template and not provided enough details to help, so I will close this.

My guess is that you are compiling on a non-supported version of Xcode? In general you need to use Xcode current to be sure things will work, as a general rule, for iOS development.

In this particular case starting with react-native-firebase v15.0.0 Xcode 13.3+ is required https://github.com/invertase/react-native-firebase/blob/main/CHANGELOG.md#1500-2022-06-20

**Comment by BabuStack** [comment]
Even I faced the same issue, but later got to know that the module's(dynamic-links) version was incompatible with the other firebase modules. So kindly verify that all your firebase modules are of same version.
