### ISSUE TITLE
App automatically restarted after update in Firebase

### ISSUE THREAD

**Issue by munkhorgil** [invertase/react-native-firebase#673]
### Issue
In my firebase I have 3 json objects such as **user**, **userInfo**, **structure**. When I update or set data in **user** json every device using my app automatically restarts itself but structure and userInfo are fine. Log as follows I am using router-flux

```
Key is already defined
```

```
componentDidMount() {
    this.userRef = firebase.database().ref(`users/${this.props.uid}`);
    this.userRef.on('value', this.handleUser);
}

savePhone = () => {
    this.userRef.update({
      phone: this.state.phone,
    });
  };
```

### Environment

1. Application Target Platform: Both

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode 9

4. React Native version: 0.45.1

5. RNFirebase Version: 3.1.1

6. Firebase Module: Auth, Database

**Comment by Ehesp** [comment]
Can you show us the logs on XCode at the point it crashes please?

**Comment by munkhorgil** [comment]
@Ehesp There is no error. But in debug I got this
```
Key ContactList is already defined!
Actions.js:178 Key contactList is already defined!
Actions.js:178 Key Anniversary is already defined!
Actions.js:178 Key anniversary is already defined!
Actions.js:178 Key tabbar is already defined!
``` 
And app starts in root scene.

**Comment by munkhorgil** [comment]
@Ehesp I send user state to editcontact as props and then I updated the user objects propperties. Can it be the reason?

**Comment by Ehesp** [comment]
Looks like an issue with your code. Never used `router-flux` but it sounds like you're re-rendering a component and then it's also trying to re-render the routes which have already been declared.
