### ISSUE TITLE
No virtual method getProjectId()Ljava/lang/String; in class Lcom/google/firebase/FirebaseOptions;

### ISSUE THREAD

**Issue by kukko** [invertase/react-native-firebase#674]
I completed the installation steps which was listen on this site:
`https://rnfirebase.io/docs/v3.1.x/installation/android`

But when I run the following command:
`react-native link && react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && react-native run-android`

It's successfully build the app and install it on my physical device, but on the phone, i got the following error.

![screenshot_20171207-140205 1](https://user-images.githubusercontent.com/5628838/33716719-805c4c92-db57-11e7-9e00-8219d836424c.png)

1. Application Target Platform: `Android`

2. Development Operating System: `Windows 7 SP1 x64`

3. Build Tools: `BuildToolVersion: 23.0.1`

4. React Native version: `0.50.4`

5. RNFirebase Version: `3.1.1`

6. Firebase Module: `N/A`

**Comment by rafikn** [comment]
I ran into this same stacktrace before, I was missing 
```
  compile "com.google.android.gms:play-services-base:11.6.0"
  compile "com.google.firebase:firebase-core:11.6.0"
```
inside my `android/app/build.gradle`.

Also check if you have enabled Google's maven repo in your `android/build.gradle`.

**Comment by chrisbianca** [comment]
Closing as @rafikn is correct in his solution.  @kukko Please let us know if this is still causing you problems after making the suggested change.

**Comment by Kishanjvaghela** [comment]
Still getting same error
Below is my App Gradle
```

dependencies {
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:25.3.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile "com.google.android.gms:play-services-base:10.2.1"
    compile "com.google.firebase:firebase-core:10.2.1"
    compile 'com.google.firebase:firebase-ads:10.2.1'
}

```
Main Gradle
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:3.0.0'
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

**Comment by muganwas** [comment]
I had the same error which was being cause by conflict in google play services
`compile "com.google.android.gms:play-services-base:11.6.0"`
`compile "com.google.android.gms:play-services-auth:10.6.1"`<--//had to change this to 11.6.0

**Comment by ethanyuwang** [comment]
Having the same issue here:

My app graddle:

`dependencies {
    compile(project(':react-native-firebase')) {
        transitive = false
    }
  compile fileTree(dir: 'libs', include: ['*.jar'])

  // RNFirebase
  compile "com.google.android.gms:play-services-base:9.8.0"
  compile "com.google.firebase:firebase-core:9.8.0"
  compile "com.google.firebase:firebase-analytics:9.8.0"

  compile 'com.android.support:multidex:1.0.1'

  // Our dependencies
  compile 'com.android.support:appcompat-v7:26.0.1'

  // Our dependencies from ExpoView
  // DON'T ADD ANYTHING HERE THAT ISN'T IN EXPOVIEW. ONLY COPY THINGS FROM EXPOVIEW TO HERE.
  compile 'com.android.support:appcompat-v7:26.0.1'
  compile 'com.facebook.android:facebook-android-sdk:4.7.0'
  compile('com.facebook.android:audience-network-sdk:4.22.1') {
    exclude module: 'play-services-ads'
  }
  provided 'org.glassfish:javax.annotation:3.1.1'
  compile 'com.jakewharton:butterknife:7.0.1'
  compile 'de.greenrobot:eventbus:2.4.0'
  compile 'com.amplitude:android-sdk:2.9.2' // Be careful when upgrading! Upgrading might break experience scoping. Check with Jesse. See Analytics.resetAmplitudeDatabaseHelper
  compile 'com.squareup.picasso:picasso:2.5.2'
  compile 'com.google.android.gms:play-services-gcm:9.8.0'
  compile 'com.google.android.gms:play-services-analytics:9.8.0'
  compile 'com.google.android.gms:play-services-maps:9.8.0'
  compile 'com.google.android.gms:play-services-auth:9.8.0'
  compile 'com.google.android.gms:play-services-location:9.8.0'
  compile 'com.google.android.gms:play-services-ads:9.8.0'
  apt 'com.raizlabs.android:DBFlow-Compiler:2.2.1'
  compile "com.raizlabs.android:DBFlow-Core:2.2.1"
  compile "com.raizlabs.android:DBFlow:2.2.1"
  compile "com.madgag.spongycastle:core:1.53.0.0"
  compile "com.madgag.spongycastle:prov:1.53.0.0"
  debugCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.4-beta1'
  // debugCompile 'com.squareup.leakcanary:leakcanary-android:1.4-beta1'
  releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.4-beta1'
  compile 'com.facebook.device.yearclass:yearclass:1.0.1'
  compile 'commons-io:commons-io:1.3.2'
  compile 'me.leolin:ShortcutBadger:1.1.4@aar'
  compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
  compile 'com.theartofdev.edmodo:android-image-cropper:2.4.7'
  compile 'com.yqritc:android-scalablevideoview:1.0.1'
  compile 'commons-codec:commons-codec:1.10'
  compile 'com.segment.analytics.android:analytics:4.3.0'
  compile 'com.google.zxing:core:3.2.1'
  compile 'net.openid:appauth:0.4.1'
  compile 'com.airbnb.android:lottie:2.2.0'
  compile 'io.branch.sdk.android:library:2.6.1'
  compile('io.nlopez.smartlocation:library:3.2.11') {
    transitive = false
  }
  compile 'com.android.support:exifinterface:26.0.1'
  compile 'com.squareup.okhttp3:okhttp:3.4.1'
  compile 'com.squareup.okhttp3:okhttp-urlconnection:3.4.1'
  compile 'com.squareup.okhttp3:okhttp-ws:3.4.1'
  compile 'com.squareup.okio:okio:1.9.0'

  // Testing
  androidTestCompile 'com.android.support.test.espresso:espresso-core:3.0.1'
  // We use a modified build of com.android.support.test:runner:1.0.1. Explanation in maven-test/README
  androidTestCompile 'com.android.support.test:runner:1.0.1'
  androidTestCompile 'com.android.support:support-annotations:26.0.1'
  androidTestCompile 'com.google.code.findbugs:jsr305:3.0.0'
  androidTestCompile 'com.android.support.test.uiautomator:uiautomator-v18:2.1.1'
  androidTestCompile 'com.azimolabs.conditionwatcher:conditionwatcher:0.2'


  
  compile('host.exp.exponent:expoview:25.0.0@aar') {
    transitive = true
  }
  
  
}`

main gradle:

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:2.3.3'
    classpath 'com.google.gms:google-services:3.0.0'
    classpath 'de.undercouch:gradle-download-task:2.0.0'
    classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
  }
}

allprojects {
  repositories {
    maven {
      url "$rootDir/maven"
    }
    maven {
      // We use a modified build of com.android.support.test:runner:1.0.1. Explanation in maven-test/README
      url "$rootDir/maven-test"
    }
    jcenter()
    maven {
      // Local Maven repo containing AARs with JSC built for Android
      url "$rootDir/../js/node_modules/jsc-android/android"
    }
    flatDir {
      dirs 'libs'
      // dirs project(':expoview').file('libs')
    }
    maven { url "https://jitpack.io" }
    maven {
      url 'https://maven.google.com'
    }

    // Want this last so that we never end up with a stale cache
    mavenLocal()
  }
}

task clean(type: Delete) {
  delete rootProject.buildDir
}
`

**Comment by chrisbianca** [comment]
@ethanyuwang see my comment here: https://github.com/invertase/react-native-firebase/issues/818#issuecomment-364031850
