### ISSUE TITLE
[🐛] Dynamic link gets detected but has missing utm parameters.

### ISSUE THREAD

**Issue by Advait1306** [invertase/react-native-firebase#6746]
## Issue
Sometimes when a dynamic link is detected, the UTM parameters are unavailable, as shown in the log image below. I'm sure that the dynamic link itself will have utm parameters. Even in my analytics data I can see that a lot of users aren't getting marked correctly as the dynamic link isn't containing utm parameters.

I know all my setups are correct & it is also working for some of the users, but there a considerable chunk that isn't getting their dynamic links detected.

![Screenshot 2022-11-30 at 11 54 27 AM](https://user-images.githubusercontent.com/42912342/204741071-9180d250-85b5-4f59-997a-31a68270e38f.jpg)

```
const useDynamicLinkDetector = () => {
    const getInitialLink = async () => {
        try {
            const link = await dynamicLinks().getInitialLink()
            if (link) {
                console.log(link)
                const {url, utmParameters} = link || {}
                const {
                    utm_source: utmSource,
                    utm_campaign: utmCampaign,
                    utm_medium: utmMedium,
                    utm_content: utmContent
                } = utmParameters || {}
              
                EventTracker.trackTriggerEvent(
                    EventNames.DETECTED_DYNAMIC_LINK,
                    {
                        [EventProperty.UTM_SOURCE]: utmSource,
                        [EventProperty.UTM_CAMPAIGN]: utmCampaign,
                        [EventProperty.UTM_MEDIUM]: utmMedium,
                        [EventProperty.UTM_CONTENT]: utmContent
                    }
                )
            }
        } catch (error) {
            console.log('error is ::', error)
        }
    }

    useEffect(() => {
        /**
         * Using timeout just to be on safer side,
         * related to this issue: https://github.com/invertase/react-native-firebase/issues/4548
         * Already using the workaround that's suggested
         */
        setTimeout(() => {
            getInitialLink()
        }, 1000)
    }, [])
}

```
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 228.69 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.10.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: * => 7.0.3 
    react: * => 17.0.2 
    react-native: * => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^14.11.4`
- **`Firebase` module(s) you're using that has the issue:**
  - `^14.11.4` & `dynamic-links`
- **Are you using `TypeScript`?**
  - `Y` & `4.7.4`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by tylerrhinehart** [comment]
@Advait1306 Did you find a solution to this? I am running into the same issue.

**Comment by Gopinath-dartexon** [comment]
same

**Comment by Advait1306** [comment]
@tylerrhinehart haven't found anything yet, it seems like a firebase issue. We noticed that it only happens when there's a swarm or 1000 users coming each day. So we decided to move to appsflyer's onelink.

**Comment by n0uki** [comment]
same here. urlParameters are empty

**Comment by AdriaRios** [comment]
We are experimenting the same issue, any update here?

**Comment by abhishek-goel1** [comment]
Any update on this? we are also facing same issue on android

**Comment by AdriaRios** [comment]
Hey, this is still happening. Should we reopen it?

**Comment by kr-yeon** [comment]
+1

**Comment by cleversonffaria** [comment]
Sei que essa abordagem seria a melhor, mas como dica eu falaria para puxar o que vem na URL criar uma desestruturação dos parâmetros manualmente.  
Um exemplo: 
`
 import { EmitterSubscription } from 'react-native';
 import * as Linking from 'expo-linking';

 let subscription: EmitterSubscription | null = null;

const handleLinking = (link: string) => {
      const queryString = link.split('?link=')[1];
      const parsedUrl = URL.parse(String(queryString), true).query;

      console.log(parsedUrl); // Parâmetros transformados em objeto. 
 
      listener(link);
    };

    const onReceiveURL = ({ url }: { url: string }) => {
      handleLinking(url);
    };

    subscription = Linking.addEventListener('url', onReceiveURL);
     
`

Espero ter ajudado de alguma forma para aqueles que não encontraram a solução ideal.
