### ISSUE TITLE
[🐛] Some error on IOS simulator

### ISSUE THREAD

**Issue by Sergey-lang** [invertase/react-native-firebase#6748]
https://rnfirebase.io/ 
did all steeps for ios
1. 
<img width="986" alt="Снимок экрана 2022-11-30 в 16 01 14" src="https://user-images.githubusercontent.com/63201050/204802971-5c7c08d5-bc88-4ba0-91ef-b9ca31304e6a.png">
2.
<img width="712" alt="Снимок экрана 2022-11-30 в 16 02 11" src="https://user-images.githubusercontent.com/63201050/204803226-d9ac917f-0ab6-40ed-91bb-ef30fe745159.png">

and get this when i'm trying to run ios
<img width="1592" alt="Снимок экрана 2022-11-30 в 16 03 07" src="https://user-images.githubusercontent.com/63201050/204803496-a6bca508-44cf-4c9b-95af-4cd724f43b25.png">

**Comment by mikehardy** [comment]
> i don't understand what it is https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

It is exactly as I described:

> a demonstrator that shows all the steps you need (you can just read the comments...) to successfully integrate react-native and react-native-firebase. It proves it all works and builds

That is, I've provided you a fully automated minimal reproducible example of react-native and react-native-firebase integrating and building, from scratch. So if there is an error, it will be in your project somewhere and you'll have to find it
