### ISSUE TITLE
[📚] Managed workflow docs

### ISSUE THREAD

**Issue by conor909** [invertase/react-native-firebase#6750]
In the [Managed Workflow Expo docs](https://rnfirebase.io/#managed-workflow), at the end it's mentioned to run `expo prebuild --clean`, this ejects from managed to a bare project.  It may be very undesirable for people.

**Comment by mikehardy** [comment]
If there is some PR that would clean the language up to, I'm open to merge it. I don't use Expo myself so I'm not sensitive to these sorts of things though I understand ejecting is a big deal

**Comment by conor909** [comment]
Well the thing is, does rnb work for managed flows at all, if in the end you need to eject to the bare workflow?   Maybe there's a command that does the same thing without ejecting, I'm not sure

**Comment by mikehardy** [comment]
It works fine with EAS build and the config plugins we host in-repo here, for the main "app" module, auth (only need plugin if you do phone auth), crashlytics, and performance monitoring. No eject needed, but you have to do EAS style

Expo changes the names for things frequently enough I don't try to track it too closely. I know EAS + config plugins is good though

**Comment by conor909** [comment]
But only in bare workflow?  After installing the plugins and running `expo prebuild --clean`?

**Comment by mikehardy** [comment]
I don't use Expo myself, I can't really help

**Comment by silencie** [comment]
Can we use firestore/storage/auth with expo? 

Collect me if I'm wrong. For what I understand we can create development build with EAS build and this does not need to eject to the bare workflow.
ref :  [https://docs.expo.dev/development/create-development-builds/#create-and-install-eas-build](url)

**Comment by conor909** [comment]
@silencie thats correct

**Comment by mikehardy** [comment]
> I’m new to rnfb but I’ll try note these things down as suggestions to update the docs

That would be fantastic - I want to be clear that I am not antagonistic to Expo in any way, just that I do not personally use it nor do I have time to start playing with it, so I am simply not a reliable source of advice for it.

So any help to improve expo-related sections of the docs are highly appreciated. I try to handle PRs like that basically immediately so they're published and help new folks with no delay

Cheers

**Comment by silencie** [comment]
Firebase JS SDK has a problem when uploading image to cloud storage even firebase team couldn't figure it out and they suggested using react native firebase. I think many expo users are going to find the docs about how to use rnfb with expo for sure. 

ref : https://github.com/firebase/firebase-js-sdk/issues/5848#issuecomment-1279292900
