### ISSUE TITLE
App Check - Too many attempts

### ISSUE THREAD

**Issue by chenop** [invertase/react-native-firebase#6753]
## Issue

Trying to use AppCheck with "Play Integrity" android
Did the following:
1. install react-native-firebase/app-check
2. In Firebase Console --> App Check --> Apps --> Registered Successfully Play Integrity - inserting the SHA-256 generated from the app keystore file
keytool -list -v -alias [alias] -keystore [keystore file path] -keypass [key password]
3. invoking:
```
export const getAppCheckToken = async () => {
	try {
		const { token } = await firebase.appCheck().getToken();
		return token;
	} catch (err) {
		console.error(err);
		return err.toString();
	}
};
```

Actual:
[appCheck/token-error] com.google.firebase.FirebaseException: Too many attempts

Expected: 
Real token

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/analytics": "14.12.0",
    "@react-native-firebase/app": "14.12.0",
    "@react-native-firebase/app-check": "14.12.0",
    "@react-native-firebase/crashlytics": "14.12.0",
    "@react-native-firebase/dynamic-links": "14.12.0",
    "@react-native-firebase/perf": "14.12.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
```
    "@react-native-firebase/analytics": "14.12.0",
    "@react-native-firebase/app": "14.12.0",
    "@react-native-firebase/app-check": "14.12.0",
    "@react-native-firebase/crashlytics": "14.12.0",
    "@react-native-firebase/dynamic-links": "14.12.0",
    "@react-native-firebase/perf": "14.12.0",
```

Please only log issues against current stable versions. Update to current stable then report if you still reproduce

> [appCheck/token-error] com.google.firebase.FirebaseException: Too many attempts

How many attempts were there :thinking: ? We test it in our CI all the time and it definitely works - I suspect something about your project config and/or timing of requests etc. You should watch `adb logcat` while testing.

**Comment by chenop** [comment]
Thank you @mikehardy for the quick response - will try to upgrade those packages

**Comment by chenop** [comment]
Hi @mikehardy - Updated to latest version:
```
    "@react-native-firebase/analytics": "16.4.6",
    "@react-native-firebase/app": "^16.4.6",
    "@react-native-firebase/app-check": "^16.4.6",
    "@react-native-firebase/crashlytics": "^16.4.6",
    "@react-native-firebase/dynamic-links": "^16.4.6",
    "@react-native-firebase/perf": "^16.4.6",
    "react-native": "0.66.4",
```
Still got "too many attempts"

adb logcat:
```
2022-12-04 16:14:49.433 27255-27438/? E/AppCheck: RNFB: Unknown error while fetching AppCheck token com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.
2022-12-04 16:14:49.433 27255-27438/? E/AppCheck: RNFB: Unknown error while fetching AppCheck token com.google.firebase.FirebaseException: Too many attempts.
2022-12-04 16:14:49.433 27255-27438/? E/AppCheck: RNFB: Unknown error while fetching AppCheck token com.google.firebase.FirebaseException: Too many attempts.
2022-12-04 16:14:49.435 27255-27363/? I/ReactNativeJS: { token: 'Error: [appCheck/token-error] com.google.firebase.FirebaseException: Too many attempts.' }
2022-12-04 16:14:49.448 27255-27363/? E/ReactNativeJS: [Error: [appCheck/token-error] com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.]
2022-12-04 16:14:49.450 27255-27363/? E/ReactNativeJS: [Error: [appCheck/token-error] com.google.firebase.FirebaseException: Too many attempts.]
2022-12-04 16:14:49.450 27255-27363/? E/ReactNativeJS: [Error: [appCheck/token-error] com.google.firebase.FirebaseException: Too many attempts.]
2022-12-04 16:14:49.452 27255-27365/? E/unknown:ReactNative: Error: [appCheck/token-error] com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed., js engine: hermes, stack:
    getToken@1:1846223
    _callee$@1:1844795
    tryCatch@1:203176
    invoke@1:204180
    anonymous@1:203324
    tryCatch@1:203176
    invoke@1:203409
    anonymous@1:203848
    tryCallTwo@61:8
2022-12-04 16:14:49.452 27255-27365/? E/unknown:ReactNative: Error: [appCheck/token-error] com.google.firebase.FirebaseException: Too many attempts., js engine: hermes, stack:
    getToken@1:1846223
    _callee$@1:1844795
    tryCatch@1:203176
    invoke@1:204180
    anonymous@1:203324
    tryCatch@1:203176
    invoke@1:203409
    anonymous@1:203848
    tryCallTwo@61:8
2022-12-04 16:14:49.453 27255-27365/? E/unknown:ReactNative: Error: [appCheck/token-error] com.google.firebase.FirebaseException: Too many attempts., js engine: hermes, stack:
    getToken@1:1846223
    _callee$@1:1844795
    tryCatch@1:203176
    invoke@1:204180
    anonymous@1:203324
    tryCatch@1:203176
    invoke@1:203409
    anonymous@1:203848
    tryCallTwo@61:8
```

**Comment by chenop** [comment]
App Check on Android looks ok
![image](https://user-images.githubusercontent.com/446575/205506068-5b4e9cd3-ce71-40a9-add4-3a66e74a2ccb.png)

Took the SAH-256 from here:
![image](https://user-images.githubusercontent.com/446575/205506123-1073218e-4cdf-4646-bd1f-ef5a14a426e7.png)

@mikehardy  Is that ok?

**Comment by mikehardy** [comment]
> Trying to use AppCheck with "Play Integrity" android

We don't support Play Integrity yet.

So I think this is essentially duplicate #6434

**Comment by mptorz** [comment]
Hey, I'm having exactly the same issues with latest react-native-firebase.

**Comment by bwerere** [comment]
I also have similar issue: I have followed all steps, put the debug tokens where necessary. I want to use firebase emulator with real device. This works perfect with web but with mobile app on real device hitting the firebase emulator, has error: 
D/com.google.firebase.appcheck.debug.internal.DebugAppCheckProvider(25557): Enter this debug secret into the allow list in the Firebase Console for your project: 36c2eb3f-ed60-4d36-b2a8-137d45******
W/LocalRequestInterceptor(25557): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.

Note that the debug secret is already in the firebase as required. 

Is there a clear step by step procedure for setting up firebase emulator with App check, I have failed to get this straight...

**Comment by barath-dev** [comment]
I am developing a flutter application and facing the exact same issue
Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.
I wish someone to help me resolve this error

**Comment by VidojeMuric** [comment]
I am developping Android application and having same issues. Could someone give his experience, how to resolve these issues?

Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.

Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.

**Comment by barath-dev** [comment]
Hey VidojeMuric,
I haven't resolved this issue but, i de enforced in the Firebase app
check.I dont think
there is a exact solution for this, I have tried every way possible to
completely
resolve this issue. So ignoring this issue would be the best solution.

Thank you for contacting me

Yours Sincerely
Barathwaj.K

**Comment by barath-dev** [comment]
Hey VidojeMuric,
I haven't resolved this issue but, i de enforced in the Firebase app
check.I dont think
there is a exact solution for this, I have tried every way possible to
completely
resolve this issue. So ignoring this issue would be the best solution.

**Comment by Krishi1702** [comment]
Hey @VidojeMuric 
I am getting the same error. Did you find any solution to it?

**Comment by Abdelsattar** [comment]
i face the same issue, any solution found?

**Comment by ottob** [comment]
We also see this issue in production on android devices.

**Comment by gongshoudao** [comment]
Same issue~~~~

**Comment by pcevikogullari** [comment]
Same issue

**Comment by gimi-anders** [comment]
Same issue for us - why is this closed?

**Comment by HumedMohammed** [comment]
Facing the same issue of too many attempts in 2025 too, In release android app... debug works fine

**Comment by mikehardy** [comment]
Leaving this comment for any future people with this problem:

We are not able to control, influence, or have any insight into the Firebase API rate limits imposed by Firebase cloud services. Our job here is just to wrap the native SDKs APIs and expose them to react-native applications at the javascript level.

If we have done that - expose the APIs, which we have done - then the problem is an application-specific concern or an issue to take up directly with Firebase via their support.

This is not actionable here and unfortunately there is no insight we can provide
