### ISSUE TITLE
[📚] The iid library guide is still showing

### ISSUE THREAD

**Issue by Sun-Woo-Kim** [invertase/react-native-firebase#6756]
## Documentation Feedback

Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:

The iid library guide is still showing
https://rnfb-docs.netlify.app/iid/usage 

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! That's not a valid URL. Where did you encounter it? It should not be linked anywhere.

You want: https://rnfirebase.io/

IId is not present there

**Comment by Sun-Woo-Kim** [comment]
Thank you @mikehardy 
This link was at the top when I searched for "react native firebase instance id".
I'm worried that other users will also enter this link.

![Screenshot 2022-12-04 at 5 49 13 PM](https://user-images.githubusercontent.com/13533884/205481980-99bd0ddd-532f-4893-baa7-92d2ba7133fe.png)

**Comment by mikehardy** [comment]
Not much we can do about that. It's an invalid link though still, rnfirebase.io is the official one
