### ISSUE TITLE
targeting s+ (version 31 and above) requires that one of flag_immutable or flag_mutable

### ISSUE THREAD

**Issue by ViniciusMargotti** [invertase/react-native-firebase#6759]
### **targeting s+ (version 31 and above) requires that one of flag_immutable or flag_mutable**

Hello, I'm facing the same problem with "react-native/messaging", I've already updated the libraries to the latest versions but the error continues

"@react-native-firebase/app": "16.4.6", 
"@react-native-firebase/crashlytics": "16.4.6",
"@react-native-firebase/messaging": "16.4.6",
 "react-native": "0.64.1",

![image](https://user-images.githubusercontent.com/26387908/205451400-8940ac52-1a3c-45c7-bb2a-9d93856ada91.png)

I made some changes to build.gradlew, according to some correction reports, but I couldn't identify a solution to the problem

![image](https://user-images.githubusercontent.com/26387908/205451438-2e8ba120-ea0f-4039-8e36-529676a812da.png)

Could you indicate any known solution or version to update?

_Originally posted by @ViniciusMargotti in https://github.com/invertase/react-native-firebase/issues/6147#issuecomment-1336194868_

**Comment by mikehardy** [comment]
> "react-native": "0.64.1",

This is terribly out of date. I wouldn't consider using it, personally --> https://react-native-community.github.io/upgrade-helper/

IID is deprecated and out of use. It has been removed from the BoM and you should no longer use it. Installations replaced it about 2 years ago. you should remove that and any other firebase items from your gradle scripts as react-native-firebase should be allowed to manage the versions.

The BoM should be on 31.1.0 (but managed by react-native-firebase) - https://github.com/invertase/react-native-firebase/blob/367620571afba215653315600689d49866cdf3db/packages/app/package.json#L76 and messaging is simply whatever version is included in the BoM. You shouldn't specify a messaging version even if you must have a specific dependency in your gradle, but ideally you have no firebase items in your build.gradle.

This *will* resolve if you are actually on all current stable versions (I know: I have a work project targeting 31+, it's fine) so it is not actionable here, I'll close it

**Comment by ViniciusMargotti** [comment]
We had this issue when updating to Android API 31, we thought the error was in "@react-native-firebase/messaging" but it was only in the "react-native-notifications" library

We update

**"react-native-notifications": "^3.3.0"**

to

**"react-native-notifications": "4.2.0"**
