### ISSUE TITLE
First onSnapShot makes application temporarily freeze

### ISSUE THREAD

**Issue by connercms** [invertase/react-native-firebase#676]
### Issue

I am using the react-native-firebase ^3.1.1 and react-native ^0.49.5. A user of my application has variable permissions to territories. For example, User A may have permission to just territory 1, while User B may have permission to territory 1, 2 and 3. When the application starts, I set up snapshot listeners to listen for changes to the documents that correspond to the territories the user has access to. Since there is no logical OR, I have to loop for each territory and set up a snapshot listener like below

```
componentDidMount() {
let { territories } = this.props
territories.forEach(territory => {
  this.unsubscribe.push(
    firebase
      .firestore()
      .collection('dispatches')
      .where('territory_id', '==', territory)
      .onSnapshot(querySnapshot => {
        const dispatches = []
        querySnapshot.forEach(document => {
          dispatches.push(document.data())
        })
        this.props.handleDispatchUpdate(territory, dispatches)
      })
  )
})
}
```

This seems to work but my application 'freezes' when the listeners are being set up. For example, if the user tries to open the side drawer menu or interact with the application in any way, nothing happens for on average about 8 seconds or sometimes up to over a minute, then all the actions seem to happen at once.

![gif-171207_120400](https://user-images.githubusercontent.com/12799522/33733984-130fffd6-db51-11e7-8e79-02ce7b3e31ad.gif)

I have added console log statements to check if it was due to networking time between the app and firebase like below

```
  componentDidMount() {
let { territories } = this.props
territories.forEach(territory => {
  console.log(`Starting read for territory item ${territories.indexOf(territory)}`, moment().format('hh:mm:ss'))
  this.unsubscribe.push(
    firebase
      .firestore()
      .collection('dispatches')
      .where('territory_id', '==', territory)
      .onSnapshot(querySnapshot => {
        console.log(`Finished read for territory item ${territories.indexOf(territory)}`, moment().format('hh:mm:ss'))
        const dispatches = []
        querySnapshot.forEach(document => {
          dispatches.push(document.data())
        })
        console.log(
          `Storing documents in redux store for territory item ${territories.indexOf(territory)}`,
          moment().format('hh:mm:ss')
        )
        this.props.handleDispatchUpdate(territory, dispatches)
      })
  )
})
}
```
With the results below recorded as hh:mm:ss. The user in question had permission to 3 territories

<img width="535" alt="screen shot 2017-12-07 at 12 07 07 pm" src="https://user-images.githubusercontent.com/12799522/33733928-e8b98a7c-db50-11e7-8b33-021b289ed4b5.png">

I am unsure if this is an issue with the react-native-firebase package, firebase firestore itself or the way I am setting up the snapshot listeners.

### Environment

1. Application Target Platform: Android 

2. Development Operating System: macOS High Sierra 10.13.1

3. Build Tools: 

4. React Native version: ^0.49.5

5. RNFirebase Version: ^3.1.1

6. Firebase Module: Firestore

**Comment by darioielardi** [comment]
I'm experiencing this too.

**Comment by Salakar** [comment]
@connercms might be worth splitting up your logic there asynchronously using a library such as `async` - sounds like you have a lot of traffic going through the RN bridge all at once and locking up your JS thread.

Be worth updating to the latest version of RNFirebase as well - just in case there's an underlying firebase sdk issue that has since been fixed.

**Comment by ccoeder** [comment]
Did you solve it?

**Comment by Zeusmist** [comment]
@connercms How did you solve the issue?
