### ISSUE TITLE
No type or protocol named 'FIRLibrary'

### ISSUE THREAD

**Issue by faizanbutt** [invertase/react-native-firebase#6763]
Hi All,
I am facing this issue when I try to run my app on Xcode
I came to this error after trying to resolve my original error that was: firebase crashlytics, analytics and messaging were depending on different versions of react-native-firebase/app.
Please guide me on this!
![Screenshot 2022-12-06 at 4 10 50 PM](https://user-images.githubusercontent.com/28476857/205896201-e91438a6-0e46-4fbb-a1ce-8d8f5e31efe8.png)
This is my package.json
![Screenshot 2022-12-06 at 4 12 05 PM](https://user-images.githubusercontent.com/28476857/205896483-3cea41b1-0b0d-4af1-89d1-0e9ebff878e8.png)

**Comment by mikehardy** [comment]
Hi there! You are most likely not opening the .xcworkspace file (opening the .xcproject file is non-functional in a cocoapods app, you have to open the .xcworkspace)

if you open it correctly after doing a `pod install` it should all work

**Comment by faizanbutt** [comment]
Hi @mikehardy , I am already opening .xcworkspace file..

**Comment by mikehardy** [comment]
Okay, that's good. Here's the thing though - in general when asking for help in open source repositories you are expected to do a fair bit of work setting up the problem with the idea you are asking others to take valuable time to work on your problem, usually for no benefit to them. There are some guides that help you set up problems that way:

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

In particular the minimal reproducible example guide leads me to create this script, which is a reproducible example of a successful react-native-firebase integration that builds and works and which you may open: https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

So what that means is, you have some project-specific problem, that you have not specified fully enough for me (or anyone else) to really help you with, and you haven't provided an example of how to reproduce the issue. But I have (with that script) provided an example of it actually working, so I conclude there's no problem in this module so it's not actionable here - which keeps the issue closed.

If you run that script and compare the project it builds with your project, you may find the source of integration error and hopefully it helps straighten things out in your project
