### ISSUE TITLE
AdMob Rewarded Video not loaded on iOS released app on Device

### ISSUE THREAD

**Issue by mustivar** [invertase/react-native-firebase#677]
### Issue

Hi I've developed a react-native app and took the advantage of admob module of this library while showing ads.

AdMob Rewarded Video Ads not loaded when app is released and installed on device(even app is now available on app store)

Because of this problem we also defined another network (AdColony) to AdMob Mediation and device can successfully receive AdColony rewarded video ads.

I thought that I was doing something wrong and tried different strategies during loading ad but I can successfuly receive Admob Rewarded Video when running on emulator.

Lately I've found an issue on github/googleads which is mentioning that AdMob has ad serving problem when test device is added to request. And What I understand from your source is it is added by default in react-native-firebase.

Link: https://github.com/googleads/googleads-mobile-unity/issues/360#issuecomment-284914249

May it be the problem that I'm facing? Is it an option to remove that default definition?

Thanks.

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS

3. Build Tools: Xcode 9

4. React Native version: 0.51.0

5. RNFirebase Version: 3.1.1

6. Firebase Module: admob

**Comment by Ehesp** [comment]
Heya, can I see your code to display the video?

**Comment by mustivar** [comment]
Hi @Ehesp thanks for you reply.
I've tried to simplify my code by removing unrelated part.
Thanks.

```
import React from 'react'
import { Button, View, ScrollView, TouchableOpacity,
  Text, ActivityIndicator  } from 'react-native'
import Config from '../Config/DebugConfig'

import { alertMessage } from '../Data/Messages'

import { connect } from 'react-redux'
import AccountActions from '../Redux/AccountRedux'

import firebase from 'react-native-firebase'

import AdConfig from '../Config/AdConfig'
import AdBanner from '../Components/AdBanner'

class RewardedVideoScreen extends React.Component {

  state = {
    adLoaded: false,
    adLoading: true
  };

  advert = firebase.admob().rewarded(AdConfig.rewardedVideoAdId);
  AdRequest = firebase.admob.AdRequest;
  rewardAdRequest = new this.AdRequest();

  constructor(props) {
    super(props);
  }

  componentDidMount() {
    this.loadAd();
    this.advert.on('onAdLoaded', () => {
      if (Config.useReactotron) {console.tron.log('Advert ready to show.');}
      if (this.advert) this.setState({adLoaded: true, adLoading: false});
    });

    this.advert.on('onAdFailedToLoad', (error) => {
      if (Config.useReactotron) {console.tron.log('Ad failed to load');console.tron.log(error)}
      if (this.advert) this.setState({adLoaded: false, adLoading: false});
    });

    this.advert.on('onAdClosed', () => {
      if (Config.useReactotron) {console.tron.log('Ad closed.');}
      if (this.advert) {
        this.setState({adLoaded: false, adLoading: true});
        this.loadAd()
      }
    });

    this.advert.on('onRewardedVideoStarted', () => {
      if (Config.useReactotron) {console.tron.log('Video started.');}
    });

    this.advert.on('onRewarded', (event) => {
      if (Config.useReactotron) {console.tron.log(event);}
      if (this.advert) {
        this.props.rewardUser();
        this.setState({adLoaded: false});
      }
    });

  }

  componentWillUnmount() {
    this.advert = undefined;
  }

  componentWillReceiveProps(nextProps) {
    if (this.state.adLoaded && nextProps.showAdVideo) {
      this.advert.show();
    }
  }

  loadAd() {
    this.advert.loadAd(this.rewardAdRequest.build());
  }

  showAdvert() {
    if (this.state.adLoaded) {
      this.props.startRewarding();
    } else {
      alertMessage('Warning!','reward.error.failed.adload');
      this.loadAd();
    }
  }

  renderAdLoading() {
    if (this.state.adLoading) {
      return (
        <View style={{width: 30}}>
          <ActivityIndicator color={Colors.green} />
        </View>
      )
    }
    return null
  }

  render() {
    return (
      <View style={{flex: 1, backgroundColor: Colors.white, paddingTop: 10}}>
       <ScrollView>
          <TouchableOpacity onPress={() => this.showAdvert()} disabled={this.state.adLoading}>
            <View>
              <Text>Reward me</Text>
              {this.renderAdLoading()}
            </View>
          </TouchableOpacity>
       </ScrollView>
       <AdBanner unitId={AdConfig.bottomBannerAdId} size='LARGE_BANNER' />
     </View>
    )
  }
}

const mapStateToProps = (state) => {
  return {
    showAdVideo: state.ads.showAdVideo
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    rewardUser: () => dispatch(AccountActions.accountRewardUser()),
    startRewarding: () => dispatch(AccountActions.accountRewardingStart())
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(RewardedVideoScreen)
```

**Comment by mustivar** [comment]
Hi @Ehesp any chance to check?
I've tried by removing default test device definition but still no luck.
I've also tried react-native-admob library and it seems same problem also occurs there
https://github.com/sbugert/react-native-admob/issues/214

it is still interesting that mediation ads can be served with same ad unit and release also works great on emulator

**Comment by ovaris** [comment]
Yeah, we have exactly this issue too, Rewarded video used work but now loading has suddenly stopped, using same version than @mustivar . `onAdLoaded` nor `onAdFailedToLoad` is fired.

**Comment by Ehesp** [comment]
If you run the production app on the simulator does it show?

**Comment by mustivar** [comment]
@Ehesp for me yes Production app on the simulator works ok. 
What is interesting that previous day I received an Admob rewarded video ad on device. it was a short Quicktime ad but thats all, nothing anymore. 
I thought maybe it is something to related device settings but checked this on multiple devices. 
Also I tried different mediation adapters and I'm able to get rewarded video ads from Chartboost and Unity Ads on ios (could not receive mediation ads on Android, maybe I need to create another issue for that too)

**Comment by ovaris** [comment]
I digged deeper and verified with Charles proxy and running release build in real device that calls to google ad networks works just fine (https calls to https://googleads.g.doubleclick.net & https://statitic.doubleclick.net), I saw ads raw binary data etc, and no http error codes there.

So the question now remains, why callback is not called?

Using RN 0.51.0, RNFirebase 3.1.1, Firebase SDK 4.5.0, Google-Mobile-Ads-SDK 7.25.0

**Comment by mustivar** [comment]
@Ehesp I've tested release with Admob test ad unit id 'ca-app-pub-3940256099942544/1712485313' and I added my device id with addTestDevice and as a result I could see test ads on device so it seems device is able to show admob rewarded video without changing any implementation. 
With test unit id I also see some logs in console

> <Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.

I also created a new Admob application with a different admob account to see if there is a problem with my account but it again behaves similar.
I think I will also write to Admob support team to confirm if everything ok with my account.

**Comment by mustivar** [comment]
Hi @ovaris did you check your production app on emulator as @Ehesp asked?
In my case it works on emulator.

**Comment by ovaris** [comment]
@Ehesp @mustivar Yes, indeed it works on emulator running with release build! But not on dev emu, nor running on real device.

**Comment by mustivar** [comment]
Hi @ovaris @Ehesp I wanted to inform you about something. 
I also had an issue after created this, my app stopped receiving ads. I've seen that I start to receive ads again after removing and reinstalling the app(or after erasing cleaning data in emulator)
I found a recent post on Google Mobile Ads SDK Developers group https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/ios/FPW3d4LKYmQ

It says Firebase Performance module update causes the problem and when I removed Performance module from ios app I started to receive ads again. @ovaris this may be related to your problem.

For this one about my Rewarded Video my problem still exists.
I tried with sample app provided by Google using my adunit Id and same problem also occurs with that. 
 I created a post in related group. So I close this one. Thank you.

**Comment by ovaris** [comment]
Thank you @mustivar! That was it, after commenting out `pod 'Firebase/Performance'` in Podfile, videos started to show again 💯 💯

**Comment by delorenj** [comment]
I am having this exact same issue, but I am not linking `Firebase/Performance`. I am running out of ideas on how to fix this issue!  Super frustrating.  I can load ads through multiple mediation adapters, but using the iOS ad uit test id gives me an "internal SDK error" after loadAd().

**Comment by Ehesp** [comment]
@delorenj have you checked the native iOS logs for anything more telling? The errors back from the SDK are less than helpful in a lot of cases, but sometimes the native libs throw out "console logs" with more handy messages.

**Comment by tusharmutreja** [comment]
Hey guys, I am not able to load rewarded adds on ios platform (react-native). 
Even I have tried test adds, also added test devices .
When i tried to load it shows:"

admob/error-code-no-fill
--
 "

Any Help ???
