### ISSUE TITLE
[🐛] Crashlytic iOS - Logs not sent to firebase console

### ISSUE THREAD

**Issue by kukuandroid** [invertase/react-native-firebase#6779]
## Issue

I am migrating from fabric to firebase crashlytic. The issue is logs are not recorded in firebase console only on iOS. For android, it is working fine. I did perform pod install after changing firebase.json. I tested using both debug & release mode, simulator and device. But neither was working. Please help

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
   "@react-native-firebase/analytics": "^14.9.4",
        "@react-native-firebase/app": "^14.9.4",
        "@react-native-firebase/crashlytics": "^14.9.4",
        "@react-native-firebase/dynamic-links": "^14.9.4",
        "@react-native-firebase/messaging": "^14.9.4",
        "@react-native-firebase/perf": "^14.9.4",
        "@react-navigation/bottom-tabs": "^5.9.1",
        "@react-navigation/native": "^5.7.5",
        "@react-navigation/stack": "^5.9.2",
        "@reduxjs/toolkit": "^1.8.3",
        "accordion-collapse-react-native": "^1.1.0",
        "axios": "^0.21.1",
        "cachee": "https://github.com/irfanrosly/react-native-fast-image#next",
        "compare-versions": "^3.6.0",
        "d3-shape": "^2.0.0",
        "jail-monkey": "^2.3.3",
        "lodash": "^4.17.20",
        "lottie-react-native": "^4.0.2",
        "moment": "^2.29.0",
        "numeral": "^2.0.6",
        "prop-types": "^15.7.2",
        "react": "16.13.1",
        "react-native": "0.63.3",
```

#### `firebase.json` for react-native-firebase v6:

```json
  "react-native": {
    "crashlytics_disable_auto_disabler": true,
    "crashlytics_debug_enabled": true,
    "crashlytics_auto_collection_enabled": true,
    "perf_auto_collection_enabled": true,
    "analytics_auto_collection_enabled": true
  }
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm using Pods and my Podfile looks like:

```ruby
# $FirebaseSDKVersion = '8.11.0'

platform :ios, '12.0'
# Override Firebase SDK Version

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

  pod 'GoogleMLKit/TextRecognition'
  pod 'GoogleMLKit/BarcodeScanning'
  pod 'GoogleMLKit/FaceDetection'
def shared_pods
  permissions_path = '../node_modules/react-native-permissions/ios'
  
  # pod 'Fabric', '~> 1.7.7'
  # pod 'Crashlytics', '~> 3.10.2'
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  # pod 'Firebase/MLVision', '~> 6.28.0'
  # pod 'Firebase/MLVisionTextModel'
  # pod 'Firebase/MLVisionFaceModel','~> 6.28.0'
  pod 'TensorFlowLiteObjC', '~> 2.0.0'
  pod 'GoogleDataTransport', '~> 9.1'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
end

```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
With apologies, I can't support the old versions (react-native 63 is out of support, and you're two major versions back here)

I encourage you to play with crashlytics in a standalone testbed app first, following along with this https://invertase.io/blog/react-native-firebase-crashlytics-configuration and maybe scaffolded for the test via https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
