### ISSUE TITLE
Android 8 - No notification shown for data-only messages and delay in firebaseMessaging.onMessage being called.

### ISSUE THREAD

**Issue by accordionpeas** [invertase/react-native-firebase#678]
### Issue

Hi,

Since upgrading to Android 8 I am experiencing incorrect behaviour when sending data messages. 

When sending a message with no "notification" key and a "custom_notification" key then two incorrect behaviours occur:

1) No notification is ever shown regardless of what state the app is in - foreground, background, killed.
2) There is a ~25 second delay between receiving a read-receipt from the Firebase server and when `firebaseMessaging.onMessage` is invoked.

Here is the format of the messages I am sending:

```
{
	messageId: '5a2acaeebf454a8f0cce3cd9',
	priority: 'high',
	data:{
		custom_notification:{
			id: '1511347791000',
			lights: true,
			title: 'Title',
			body: 'Body',
			group: 'appName',
			data: {},
			icon: 'icon',
			sub_text: 'sub_text',
			number: 17,
			large_icon: 'http://localhost:3000/some/url',
			big_text: 'Big text'
		}
	}
}
```

When I send a message **with** a "notification" key then the notification is shown and there is no delay in `firebaseMessaging.onMessage` being called.

Before upgrading to Android 8 these issues did not exist.

Thanks

### Environment

1. Application Target Platform: Android

2. Development Operating System: Windows 10

3. Build Tools: Android SDK 26

4. React Native version: 0.51.0

5. RNFirebase Version: 3.1.1

6. Firebase Module: messaging

**Comment by chrisbianca** [comment]
@accordionpeas You'll be pleased to know that I've just tested that our rewrite of FCM (#595) works correctly in Android 8.0.  We're hoping to get this rolled out over the next couple of weeks.

I'll close this - please follow the progress on the linked issue for updated.

**Comment by accordionpeas** [comment]
Excellent. Thanks for the update.

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)
