### ISSUE TITLE
Firebase In App Messaging not working

### ISSUE THREAD

**Issue by ibrahimaykutbas** [invertase/react-native-firebase#6783]
I have completed all the steps in the document. But notification is not coming. I tested it on different RN versions but it doesn't work. Even previously installed and running applications do not receive notifications.

Note: Push notification is working.

**Comment by zeynepfahriye** [comment]
same issue.I can't display the message on real device I was using 14.00 version of firabase I updated it with the latest version ^16.4.6 but the problem persists my react native version is 0.64.4

**Comment by mikehardy** [comment]
This issue provides no information required to help --> https://stackoverflow.com/help/how-to-ask / https://stackoverflow.com/help/minimal-reproducible-example so I will close it.

Please note that react-native 0.64 is out of support in general in the react-native ecosystem --> https://github.com/reactwg/react-native-releases#releases-support-policy

**Comment by mahan-sepehri** [comment]
@ibrahimaykutbas @zeynepfahriye Did you manage to make it work?

No in-app-message is coming through for me. analytics and push notifications works fine.

    "@react-native-firebase/analytics": "^17.3.1",
    "@react-native-firebase/app": "^17.3.1",
    "@react-native-firebase/in-app-messaging": "^17.3.1",
    "@react-native-firebase/messaging": "^17.3.1",

    "react": "18.2.0",
    "react-native": "0.71.4"
