### ISSUE TITLE
[🐛🔥] @react-native-firebase/auth config plugin for phone auth + iOS does not recognize googleServicesFile if it is in Expo secrets vs filesystem

### ISSUE THREAD

**Issue by TrevPennington** [invertase/react-native-firebase#6785]
## Issue

Hello, I am trying to implement phone auth using Expo managed. I follow the instructions and add `@react-native-firebase/auth` to `app.json` plugins array. Running `eas build` for a custom dev client will work on Android but not iOS.

iOS output:
`Error: [ios.infoPlist]: withIosInfoPlistBaseMod: [@react-native-firebase/auth] Your app.json file is missing ios.googleServicesFile. Please add this field.`

I have created the secret and uploaded the google plist file to expo secrets. Everything works fine on Android. iOS does not recognize the file.

expo: 47.0.8
@react-native-firebase/auth: 16.4.6

app.config.js

```
export default ({ config }) => {
  return {
    ...config,

    ios: {
      ...config.ios,
      googleServicesFile: process.env.FIREBASE_IOS,
    },

    android: {
      ...config.android,
      googleServicesFile: process.env.FIREBASE_ANDROID,
    },
    plugins: [...config.plugins, "@react-native-firebase/auth"],
  };
};
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ X] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.59 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /var/folders/vm/13433b4s03d0rtytfw1s97l40000gn/T/yarn--1671067936712-0.6134243581400707/node
    Yarn: 1.22.19 - /var/folders/vm/13433b4s03d0rtytfw1s97l40000gn/T/yarn--1671067936712-0.6134243581400707/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ X] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `16.4.6`
- **`Firebase` module(s) you're using that has the issue:**
  - `react-native-firebase/auth`
- **Are you using `TypeScript`?**
  - `Y` & `4.6.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
> Error: [ios.infoPlist]: withIosInfoPlistBaseMod: [@react-native-firebase/auth] Your app.json file is missing ios.googleServicesFile. Please add this field.

Okay

> I have created the secret and uploaded the google plist file to expo secrets

Sorry, I have no idea what this means, I do not use expo.

I must assume though, that you need an *actual file* somewhere, and to specify it here: https://docs.expo.dev/versions/latest/config/app/#googleservicesfile

**Comment by TrevPennington** [comment]
That's correct @mikehardy the actual file is on expo secrets, with reference to it in `app.config.js`
I updated the post to show that code.

**Comment by mikehardy** [comment]
Then I'm not sure what's happening, sorry. Others use this successfully though, so *something* is going wrong with regard to that file and the config plugin's ability to access it.

**Comment by zunkelty** [comment]
Hey @TrevPennington, I just encountered the same problem as you did. I store the firebase config files in Expo secrets as well. I have looked through the code of `@react-native-firebase/auth` and found the cause of our problem.

When using the package in an expo app, you have to add the config plugin to your `app.json` / `app.config.js` file which allows more complex customization of the underlying native code. Unfortunately, when including the Expo Config Plugins for `@react-native-firebase/auth`, the plugin is trying to automatically [enable phone number sign in](https://firebase.google.com/docs/auth/ios/phone-auth#enable-phone-number-sign-in-for-your-firebase-project). For this, it needs to use the `GoogleService-Info.plist` file which is not available locally.

@mikehardy With our Expo setup, the React Native / Expo App is built via the Expo Application Service (EAS) in the cloud. To store sensitive data such as the `GoogleService-Info.plist` file securely, we have uploaded the file to EAS. Somehow, the [Expo Config Plugin code](https://github.com/invertase/react-native-firebase/blob/54f60128502e25e1026a2e093ef42ae46977cbe6/packages/auth/plugin/src/ios/urlTypes.ts) is run locally before the code is uploaded to EAS which results in the error.

**Comment by mikehardy** [comment]
That can certainly work (just removing the auth config plugin), the issue then is that you will not be able to use phone number auth.

This sounds like an "in between" problem, where Expo and react-native-firebase will have to resolve - somehow - this interoperation need where in order to enable phone auth we need those google services plist information bits. If an Expo EAS user + phone auth user was sufficiently motivated, they could take it up with Expo and ask them how to access secret files values in config plugins during build, and alter (via a PR here) the auth config plugin to either detect if that was possible and do it in whatever way was needed in that circumstance, or if there was a way that was different but compatible with EAS secrets builds and non-secrets builds, do it that way

**Comment by zdp12** [comment]
@mikehardy  So does this mean there is no way to use phone number auth with firebase and Expo?

**Comment by mikehardy** [comment]
@zdp12 I believe it is more subtle then that. I believe it means no Expo user has yet figured out how to do phone auth with the current react-native-firebase auth config plugin *and* Expo secrets.

If you don't use the expo secrets thing, then it works fine. If you do use the Expo secrets thing, someone needs to figure out how to get the right information from secrets in to the config plugin at build time.

**Comment by javelwilson** [comment]
Hi @TrevPennington, I’ve been following the discussion and I’ve encountered the same issue that you did.

Following @zunkelty's point about the Expo config plugin code, I wanted to suggest a solution that worked me. Instead of removing @react-native-firebase/auth from the Expo config plugin, you can create a local environment variable for the GoogleService-Info.plist file path. To do this, you can use the command `export FIREBASE_IOS="./GoogleService-Info.plist"`.

@zdp12 If you are using the react-native-firebase auth config plugin along with Expo secrets and experienced the same issue, you can use the solution above before running `eas build`

I would be interested to hear if anyone else has encountered this issue or has found alternative solutions.

**Comment by VictorioMolina** [comment]
This problem sucks

**Comment by ildaneta** [comment]
You need to add into your `app.config.ts` or `app.json` file the following config:

```
ios: {
   googleServicesFile: './GoogleService-Info.plist',
},
android: {
   googleServicesFile: './google-services.json',
},
```
    
  And then, run `npx expo prebuild` whit that expo will set the firebase values within the native `android` and `ios` folders.
