### ISSUE TITLE
Wrong path returned from snapshot reference

### ISSUE THREAD

**Issue by brunolemos** [invertase/react-native-firebase#679]
### Issue

Running:
```js
const ref = firebase.database().ref('users/G2t491yrinOu7XUARHPTtXLUvZ93/')
console.log(`${ref}`)
``` 

have different results between `javascript sdk` and `react-native-firebase`.

#### Javascript

`https://myappid.firebaseio.com/users/G2t491yrinOu7XUARHPTtXLUvZ93`

#### react-native-firebase

`users/G2t491yrinOu7XUARHPTtXLUvZ93/`

Until now, fine by be. But the critical part is when I get the path from a snapshot reference:

```js
ref.on('value', snapshot => { console.log(`${snapshot.ref}`) })
```

#### Javascript

`https://myappid.firebaseio.com/users/G2t491yrinOu7XUARHPTtXLUvZ93` (same value)

#### react-native-firebase

`users/G2t491yrinOu7XUARHPTtXLUvZ93//G2t491yrinOu7XUARHPTtXLUvZ93`

Note that besides not showing the full url, it duplicated the id at the end.

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS High Sierra

3. Build Tools: Xcode 9.1

4. React Native version: 0.50.4

5. RNFirebase Version: ^3.1.1

6. Firebase Module: N/A

**Comment by brunolemos** [comment]
Fortunately I just found a workaround.

If I remove the last `/` from my database path, it shows the correct snapshot path:

```diff
-const ref = firebase.database().ref('users/G2t491yrinOu7XUARHPTtXLUvZ93/')
+const ref = firebase.database().ref('users/G2t491yrinOu7XUARHPTtXLUvZ93')
```

```diff
-users/G2t491yrinOu7XUARHPTtXLUvZ93//G2t491yrinOu7XUARHPTtXLUvZ93
+users/G2t491yrinOu7XUARHPTtXLUvZ93
```

That is indeed a bug :)

**Comment by chrisbianca** [comment]
@brunolemos Both these issues are now fixed and will be part of our next release. Either v3.2.3 or v3.3.0.

**Comment by brunolemos** [comment]
Awesome, thank you :)
