### ISSUE TITLE
[🐛] [Firestore] different data on android

### ISSUE THREAD

**Issue by BiskremMuhammad** [invertase/react-native-firebase#6795]
## firestore is showing different data on Adndroid

hey there,
I'm having really weird issue it's going to drive me craaazy..
i just installed the core module and added the plugin in `expo.config.ts` as i'm working in managed workflow using expo dev client.
and also installed the firestore module `@react-native-firebase/firestore` and i'm just doing a simple read, nothing more.
the app is working with no errors both on android and ios simulators. 
the iOS app is showing same data as i see on firebase console > firestore,
Although for the android it doesn't show same data from same collection, it started as showing `0` in size, so i tried to add a doc programmatically and run again on the android, the add was successful but it's shown only on android, so the data is only exclusive on android, it doesn't appear on my firestore console. and the ios is showing right data as the console.

i'm placing the google services files at the root of the project and used them in `app.config.ts` 
```
...
    ios: {
      bundleIdentifier: "com.example.app",
      googleServicesFile: "./GoogleService-Info.plist",
    },
    android: {
      package: "com.example.app",
      googleServicesFile: "./google-services.json",
    },
...
```

i didn't do `firebase.initializeApp()` step as it's done by default
i first ran the command `npx expo prebuild --clean` and then `npx expo run:android`

---

**Comment by BiskremMuhammad** [comment]
So, it seems that the android emulator can not connect to internet, although the host device internet is working!!,. but the data was offline data as the firebase is performing offline capabilities by default. so i used `firestore().settings({ persistence: false });` the app wasn't showing fake data anymore always empty results, this how i figured the network issue..

**Comment by mikehardy** [comment]
I believe you can also check the source of the results, but yes, cache consistency can be difficult to figure out when results skew between device + cloud
