### ISSUE TITLE
limitToLast not working how it should, WebSDK comparison included.

### ISSUE THREAD

**Issue by ChristianTucker** [invertase/react-native-firebase#68]
When using `ref.limitToLast(...)` anything over the number 10 is causing problems, and returning a maximum of 10 values. This shouldn't be the case, for example, `limitToLast(25)` should return the most recent 25 items (when used with `orderByKey()`) However, instead it only returns 10 values.

To run this test please do the following

```npm install --save react-native-firebase firebase```

You can then run this test by doing the following, with a ref that already has children in it.

```javascript
import firebase from 'app/react-native-firebase-instance';
import * as websdk from 'firebase';

websdk.initializeApp(...);

firebase.database()
  .ref('path/to/ref')
  .orderByKey()
  .limitToLast(25)
  .once('value')
  .then((snapshot) => {
  console.log('react-native-firebase:', Object.keys(snapshot.val()).length);
});

websdk.database()
  .ref('path/to/ref')
  .orderByKey()
  .limitToLast(25)
  .once('value')
  .then((snapshot) => {
  console.log('web sdk:', Object.keys(snapshot.val()).length);
});
```

You'll get the following output in console:

```
react-native-firebase: 10
web sdk: 25
```

This has caused several hours of headache for myself, as I was testing my code over and over again and try to post on stackoverflow using Codepen and the likes and it always worked fine. But when I copy and pasted the same firebase query to my app, it gave me incorrect results. I finally installed the websdk in my app and ran the same query side by side and it turns out that `react-native-firebase` is returning the wrong results for `limitToLast` and I was also having problems with `limitToStart` but I haven't tested them in-depth.

**Comment by ChristianTucker** [comment]
@Ehesp

**Comment by Salakar** [comment]
@ChristianTucker also, what platform was this on, Android, iOS or both? Thanks

**Comment by ChristianTucker** [comment]
@Salakar  We've only tested on Android, submitting another bug report in a moment.

**Comment by chrisbianca** [comment]
@ChristianTucker Are you able to test with 1.0.0-alpha13, there have been some changes to the way that database modifiers are sent to the native side which may have resolved this.

**Comment by Ehesp** [comment]
Just tested this against our own dataset. I can confirm it now works, albeit with a bug which has been fixed via https://github.com/invertase/react-native-firebase/commit/b4622006bfe99f69125540b73ae81ae0e570956e.

**Comment by dorw123** [comment]
Hello. 
I`m having some sort of similar situation. 
I`m using orderBy and limit together. When limitToLast is below value 10 everything is working as expected, but when above value 10, ordering is not working anymore.

**Comment by Ehesp** [comment]
@dorw123 please create a new issue as this one is super dated.
