### ISSUE TITLE
[🐛]  Fatal Exception: java.lang.IllegalArgumentException: com.halkhata: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE

### ISSUE THREAD

**Issue by SohelKabir** [invertase/react-native-firebase#6802]
## Issue

My app is crashing on start on android 12 devices i found this on crashlytics dashboard looks like something in wrong in react-native-firebase apps
```
Fatal Exception: java.lang.IllegalArgumentException: com.halkhata: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
       at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
       at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
       at android.app.PendingIntent.getActivity(PendingIntent.java:451)
       at android.app.PendingIntent.getActivity(PendingIntent.java:415)
       at com.google.firebase.messaging.CommonNotificationBuilder.createContentIntent(CommonNotificationBuilder.java:26)
       at com.google.firebase.messaging.CommonNotificationBuilder.createNotificationInfo(CommonNotificationBuilder.java:69)
       at com.google.firebase.messaging.CommonNotificationBuilder.createNotificationInfo(CommonNotificationBuilder.java:34)
       at com.google.firebase.messaging.DisplayNotification.handleNotification(DisplayNotification.java:28)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(FirebaseMessagingService.java:36)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(FirebaseMessagingService.java:130)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:12)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:89)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(EnhancedIntentService.java:1)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(EnhancedIntentService.java:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
       at java.lang.Thread.run(Thread.java:1012)
```

---

## Project Files

```
buildscript {
    ext {
         buildToolsVersion = "30.0.2"
         minSdkVersion = 21
         compileSdkVersion = 30
         targetSdkVersion = 31
         ndkVersion = "21.4.7075529"
         googlePlayServicesAuthVersion = "19.2.0" 
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.2.2')
        classpath('com.google.gms:google-services:4.3.10')
        classpath('com.google.firebase:firebase-crashlytics-gradle:2.5.2')
        

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
"dependencies": {
    "@amplitude/react-native": "2.0.11",
    "@react-native-async-storage/async-storage": "^1.13.2",
    "@react-native-community/cli-debugger-ui": "^4.9.0",
    "@react-native-community/datetimepicker": "^3.0.1",
    "@react-native-community/hooks": "^2.8.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.9",
    "@react-native-firebase/analytics": "^11.2.0",
    "@react-native-firebase/app": "11.2.0",
    "@react-native-firebase/crashlytics": "^11.2.0",
    "@react-native-firebase/messaging": "11.2.0",
    "@react-native-firebase/remote-config": "11.2.0",
    "@react-native-google-signin/google-signin": "^8.0.0",
    "@react-navigation/drawer": "^5.8.4",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2",
    "@reduxjs/toolkit": "1.6.0",
    "appcenter": "^4.4.3",
    "appcenter-analytics": "^4.4.3",
    "appcenter-crashes": "^4.4.3",
    "axios": "^0.19.2",
    "bcrypt-react-native": "^1.1.1",
    "dayjs": "^1.8.30",
    "husky": "^4.2.5",
    "i18next": "^19.5.4",
    "jsc-android": "^250230.2.1",
    "lodash": "^4.17.15",
    "lottie-react-native": "^3.5.0",
    "mathjs": "^10.0.2",
    "phone": "^2.4.17",
    "prettier": "^2.0.5",
    "react": "16.13.1",
    "react-i18next": "^11.7.0",
    "react-native": "0.63.3",
    "react-native-animatable": "^1.3.3",
    "react-native-animated-loader": "^0.0.9",
    "react-native-applovin-max": "^4.0.0",
    "react-native-background-timer": "^2.4.1",
    "react-native-bootsplash": "^3.0.1",
    "react-native-code-push": "^7.0.4",
    "react-native-contacts": "^5.2.3",
    "react-native-device-info": "^7.2.1",
    "react-native-fbsdk-next": "^4.0.0",
    "react-native-file-access": "1.7.1",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-get-random-values": "^1.5.0",
    "react-native-html-to-pdf-lite": "^0.10.0",
    "react-native-image-picker": "^3.0.1",
    "react-native-image-resizer": "^1.4.5",
    "react-native-image-viewing": "^0.2.1",
    "react-native-in-app-review": "^3.3.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-month-year-picker": "^1.3.4",
    "react-native-otp-autocomplete": "^1.0.7",
    "react-native-pager-view": "^5.2.1",
    "react-native-paper": "^3.10.1",
    "react-native-permissions": "^3.1.0",
    "react-native-reanimated": "^1.9.0",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^3.0.6",
    "react-native-scoped-storage": "^1.9.2",
    "react-native-screens": "^2.9.0",
    "react-native-sms": "^1.11.0",
    "react-native-svg": "^12.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-tab-view": "^2.14.4",
    "react-native-toast-message": "^2.1.1",
    "react-native-vector-icons": "^7.0.0",
    "react-native-version-check": "^3.4.2",
    "react-native-version-info": "^1.1.1",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3",
    "rn-fetch-blob": "^0.12.0",
    "styled-components": "^5.1.1",
    "uuid": "^8.3.1",
    "yup": "^0.29.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "eslint": "^6.5.1",
    "eslint-config-airbnb": "18.2.0",
    "eslint-import-resolver-babel-module": "^5.1.2",
    "eslint-plugin-import": "2.21.2",
    "eslint-plugin-jsx-a11y": "6.3.0",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "7.20.0",
    "eslint-plugin-react-hooks": "4.0.0",
    "eslint-plugin-simple-import-sort": "^6.0.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },
```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml

<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.halkhata">

  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.READ_CONTACTS" />
  <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
  <uses-permission android:name="android.permission.CAMERA"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />

  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_PHONE_STATE" />
  <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
  <uses-permission android:name="android.permission.READ_PROFILE" />

  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" android:requestLegacyExternalStorage="true" android:theme="@style/AppTheme">
    <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
    <meta-data android:name="com.google.firebase.messaging.default_notification_icon"  android:resource="@mipmap/ic_stat_ic_notification" />
    <activity android:name=".MainActivity"
      android:label="@string/app_name"
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" 
      android:exported="true" 
      android:launchMode="singleTask" 
      android:windowSoftInputMode="stateVisible|adjustResize"
      android:screenOrientation="portrait" 
      android:requestLegacyExternalStorage="true"
    
    >
      <!-- <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
            <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
        </intent-filter> -->
    </activity>
     
    <activity android:name="com.zoontek.rnbootsplash.RNBootSplashActivity" android:theme="@style/BootTheme" android:launchMode="singleTask"  android:exported="true" >
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
      </intent-filter>
    </activity>
    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
  </application>
  <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:mimeType="*/*" />
        </intent>
   </queries>


</manifest>

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by joanraza1991** [comment]
same problem facing +1

**Comment by joanraza1991** [comment]
Any solution?

**Comment by mikehardy** [comment]
Hi there! @joanraza1991 please do not "metoo" or spam comment sections, they do not add to the discussion or create progress.

@SohelKabir you are using versions so old they are not open for support. Please reproduce this on current versions of react-native-firebase, where these things are solved. In general opening any issue in any open source repository on old versions is counter-productive as new releases are issued to fix problems, and in particular problems with compatibility on "future" versions of Android and iOS, like this one.

Additionally, searching first is useful: https://github.com/invertase/react-native-firebase/issues?q=is%3Aissue+FLAG_IMMUTABLE

...so you don't spend even an extra second of your time waiting on a solution that is already found, and you don't spend any of the repository maintainers time answering already answered issues

Cheers

**Comment by SohelKabir** [comment]
Sorry forgot to comment, the problem was solved by updating all react-native-firebase library to latest 16.5.0 versions. Thanks.

**Comment by Najeeb-Idrees** [comment]
After spending a lot of time on this. Finally, only this solution works.
