### ISSUE TITLE
[📚] Documentation Issue: console links are outdated

### ISSUE THREAD

**Issue by david-potgieter** [invertase/react-native-firebase#6803]
## Documentation Feedback

The redirects from both [iOS](https://github.com/invertase/react-native-firebase/blob/514e6bd51e7624a6403dda706f4e5b65cee63422/packages/app/lib/internal/registry/nativeModule.js#L181) and [Android](https://github.com/invertase/react-native-firebase/blob/514e6bd51e7624a6403dda706f4e5b65cee63422/packages/app/lib/internal/registry/nativeModule.js#L192) links, are pointing to a version 5.x.x and throws a 404.

 - http://invertase.link/ios
 - http://invertase.link/android

would be happy to submit a PR, but it seems the links are managed outside of the repo.

![Screenshot 2022-12-26 at 12 30 58](https://user-images.githubusercontent.com/2729962/209506933-e4113486-a3c1-41ba-a06f-142a3689fa98.png)

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Indeed! Good catch thank you. This is I think out of my ability to configure things as well, and I believe it will need a fix from either @Ehesp or @Salakar ...

**Comment by david-potgieter** [comment]
@mikehardy - think we need to reopen here, as it's still an issue?

**Comment by mikehardy** [comment]
I think you're right, I'm not quite keeping up with notifications at the moment unfortunately...

**Comment by david-potgieter** [comment]
Noted, thanks @mikehardy - should I prepare a PR with the links corrected, and roll back once they are fixed upstream?

**Comment by Salakar** [comment]
I've just updated the links, sorry for the delay 😅
