### ISSUE TITLE
[firestore/unavailable] The service is currently unavailable

### ISSUE THREAD

**Issue by raulgordejev** [invertase/react-native-firebase#6805]
## Issue

I've had this problem for quite some time now (since v6.4.0). What happens (I think) is that OS battery saver/optimisation settings kill the firestore connection while the app is backgrounded for some time (a few minutes). After opening the app again, firestore takes quite a long time to reconnect - around 30 seconds up to 1 minute. Get queries return the [firestore/unavailable] error, but subscriptions just silently wait until firestore is reconnected.

It's been a really difficult issue to debug and I haven't seen any proper solutions for that yet. As a workaround I'm currently using firestore REST API to fetch data in addition to subscriptions in the more critical places in the app.
From crashlytics logs it seems to be happening slightly more on iOS, but I've found it to be easier to reproduce on Android. Specifically Androids 10 to 12.

To reproduce this issue on Android:
1. Subscribe to a collection/document in the app (onSnapshot)
2. Put the app in the background state
3. Settings->Battery->Battery saver [on] OR Select your app -> App info -> Battery -> Manage battery usage [restricted]
4. Open the app after around 5 minutes
5. Firestore subscription should not return anything for around 30 seconds and get queries will return [firestore/unavailable].

---

#### `package.json`:

```json
"react-native": "0.70.5",
"react": "18.1.0",
"@react-native-firebase/app": "14.11.1",
"@react-native-firebase/firestore": "14.11.1",
```

</details>

- **Platform that you're experiencing the issue on**:
  - [x ] iOS
  - [x ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.4.0 - 14.11.1`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Can you please try on current versions? Yours are pretty outdated, and this is an area they work on in the underlying native SDKs, you can see references to it from time to time in the upstream SDK release notes.

You may also be interested in https://dontkillmyapp.com (with associated detection of power savings setting via some react-native API - a few modules provide it I think? notifee does, not sure about react-native-device-info...) - a manual offline/online firestore settings toggle (something that can be done programmatically perhaps based on an AppState listener?)

**Comment by raulgordejev** [comment]
@mikehardy So far I've been staying on 14.x.x because starting from 15.0.0 use_frameworks! is required and it was not compatible with hermes. However it looks like this has been solved meanwhile, so I'll upgrade and test it again with new versions.

Will also look into the options for detecting the power saver setting.

**Comment by raulgordejev** [comment]
Opening up this issue again, since after upgrading and using the version 17.4.2 for a while, the [firestore/unavailable] errors still persist for both iOS and Android.

Workarounds like manually toggling the firestore offline/online on appstate changes doesn't have much effect. As @mikehardy suggested, I have looked into power saving settings detection APIs like Notifee, but it doesn't seem to be the best user experience to ask them to manually disable battery optimisation. As well as these API's are only available for Android.

I understand this issue comes from the underlying native SDK's, but perhaps bringing this up again might bring up some new ideas/workarounds.

**Comment by nicolaosm** [comment]
Having this issue as well!

**Comment by raulgordejev** [comment]
The problem still persists for me as well on react-native-firebase@19.0.0. This issue was closed automatically and I'm not able to reopen it unfortunately.

**Comment by mikehardy** [comment]
My best guess is some underlying network issue, I have noticed firestore in particular is not friendly with VPNs much of the time and google will block you on a network level.

I have also noticed that people reporting "same issue" and "me too!" are very very rarely actually experiencing the same issue, and are much better served opening a fresh issue with full details provided. For instance, this issue was opened with old firebase versions which would not even be accepted in the App Store now, and are reports from newer versions actually the same? Hard to say

Best to open a new issue with details and minimal reproduction we can see in a single App.tsx

**Comment by KaviduAloka** [comment]
Hi @mikehardy, I still face this issue. I am on;

```
"react-native": "0.72.14",
"@react-native-firebase/app": "^21.0.0",
"@react-native-firebase/auth": "^21.0.0",
"@react-native-firebase/firestore": "^21.0.0",
"@react-native-firebase/storage": "^21.0.0",
```

Everytime this `firestore/unavailable` error occurs, all the data from collections return empty arrays in `data` and `undefined` when I use `doc(ID).get()`. Doesn't matter passing `source` as "server" or "cache"

The only solution is relogin using `firestore/auth`. Then the data fetching works fine. After few hours of not using the application, same error occurs.

Is this related to auth package or firestore?

**Comment by mikehardy** [comment]
When I have seen firestore stop working after a few hours, but reauth fixes it, I think what is happening is that the supposed-to-be-automated token refresh is not working for you. And when I have heard of *that* happening it was (if I remember correctly...) some google cloud console API that was supposed to be enabled for the firebase app's service account but was not enabled, causing the token refresh to fail. That's pretty vague, apologies, but *that* is what I'd look for. "A freshly authed token is working but token refresh seems to be broken, why?"

**Comment by KaviduAloka** [comment]
Thank you @mikehardy for the response. I solved the issue by removing all the packages completely and installed freshly. Now the issue is gone 🙌🏻

**Comment by KaviduAloka** [comment]
> My best guess is some underlying network issue, I have noticed firestore in particular is not friendly with VPNs much of the time and google will block you on a network level.
> 
> I have also noticed that people reporting "same issue" and "me too!" are very very rarely actually experiencing the same issue, and are much better served opening a fresh issue with full details provided. For instance, this issue was opened with old firebase versions which would not even be accepted in the App Store now, and are reports from newer versions actually the same? Hard to say
> 
> Best to open a new issue with details and minimal reproduction we can see in a single App.tsx

Is there a way to handle token refresh in `rnfirebase auth` ?

**Comment by KaviduAloka** [comment]
Found the solution, make sure to enable correct APIs in Google Cloud Console 😁

**Comment by mikehardy** [comment]
@KaviduAloka found "a" solution, there are multiple reasons this can happen. API key restrictions are certainly one

**Comment by KaviduAloka** [comment]
@mikehardy yeah, that's the best explanation. Thanks 🙏
