### ISSUE TITLE
iOS : Cancel repeating notifications

### ISSUE THREAD

**Issue by Kernael** [invertase/react-native-firebase#681]
### Issue

On iOS only, I have trouble cancelling scheduled repeating local notifications.

I want to schedule a notification at, say, **today at 10:00am**, that will repeat itself every minutes, and when the notification is clicked, cancel every scheduled notifications, then schedule a new one at **tomorrow at 10:00am**.

If I cancel  with`.cancelLocalNotification('*')` and do nothing afterwards, the notification will be cancelled and will stop repeating.

But whenever I try to schedule a new notification with a new time and a new ID, right after cancelLocalNotifications, my "old" notification will keep repeating anyway, with no way to stop it.

My code is :

```
firebase.messaging().cancelLocalNotification('*');
firebase.messaging().removeDeliveredNotification('*');
firebase.messaging().getScheduledLocalNotifications().then((notifications) => {
    console.log(notifications) // empty, as intented
})

const now = moment();
const date = moment().hours(10).minutes(0).seconds(0);

let time;
 if (now > date) {
  time = date.add(1, 'day').valueOf();
 } else {
  time = date.valueOf();
}

firebase.messaging().scheduleLocalNotification({
  title: 'Title',
  body: 'Test',
  sound: 'test.mp3',
  priority: 'high',
  icon: 'ic_launcher',
  large_icon: 'ic_launcher',
  vibrate: 2000,
  lights: true,
  show_in_foreground: true,
  repeat_interval: 'minute',
  fire_date: time
  id: uuid(), // setting a random id
});

firebase.messaging().getScheduledLocalNotifications().then((notifications) => {
  console.log(notifications) // one notification, as intended -- `fire_date` timestamps are also correct, and IDs are different every time
})
```

Everything seems to be working as intented on Android.

Thank you for your help.

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS Sierra

3. Build Tools: 

4. React Native version: 0.46.1

5. RNFirebase Version: 2.1.3

6. Firebase Module: Messaging

**Comment by chrisbianca** [comment]
@Kernael This sounds like a timing issue.  What happens if you were to put a `setTimeout()` with a delay in before rescheduling the notification?

**Comment by chrisbianca** [comment]
Closing due to lack of response. Please re-open with more details if required.
