### ISSUE TITLE
[📚] Legacy documentation (v5) urgently required

### ISSUE THREAD

**Issue by zenjedi** [invertase/react-native-firebase#6811]
## Documentation Feedback

Our apps are on v5 of react-native-firebase and which is facing a high priority issue which needs urgent resolution. But it seems all of v5 (and perhaps older versions) reference documentation has been archived. While the intention of pushing users to the supported v6 is noted and is understood, to not show legacy documentation is really handcuffing. I'm hoping it is not intentional.

Please reopen <=v5 legacy documentation (with of course all the caveats that it is not supported)

![image](https://user-images.githubusercontent.com/64598065/210128371-d97b5da2-0ff9-4d0d-a8b0-ab513d316361.png)

**Comment by mikehardy** [comment]
No support for react-native-firebase v5 is provided at all and **it is not supportable**. You must understand that at this point if it runs it does so by chance. The docs are removed on purpose.

You may use github to go back in time to the old docs if you need to perform some archeology but no other path is available https://github.com/invertase/react-native-firebase-docs/tree/v5.x.x

It should be clear based on that limited access and this comment that no project should be using v5 at this point and you should update at the earliest possible moment, but hopefully you find what you need via github
