### ISSUE TITLE
[2023-01-02t20:51:957Z] @firebase/firestore: Firestore (9.15.0): Connection WebChannel transport errored:

### ISSUE THREAD

**Issue by shoaiby31** [invertase/react-native-firebase#6812]
![Screenshot from 2023-01-03 01-58-23](https://user-images.githubusercontent.com/121829567/210277583-3c8319d6-c09d-48b8-88d6-a04b96240cba.png)

## Issue

I am trying to write data in firestore database, But stuck on this error.
My code is
import { collection, addDoc } from "firebase/firestore"; 
import { auth, db } from '../firebase/config'

 Register = async () => {
        const docRef = await addDoc(collection(db, "users"), {
            Name: "ABC",
            State: "Kp",
            Country: "Xyz"
        })
        console.log("Document written with ID: ", docRef.id);
    }
Describe your issue here

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

##React Native

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
![Screenshot from 2023-01-03 01-58-23](https://user-images.githubusercontent.com/121829567/210278025-d5d0537f-c126-4502-81a3-573e820d9d6f.png)

```

- **Platform that you're experiencing the issue on**:
  - [ ] **Android** but have not tested behavior on iOS
- **`react-native-firebase` version you're using that has this issue:**
  - `9.15.6`
- **`Firebase` module(s) you're using that has the issue:**
  - `Firestore`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by SohelIslamImran** [comment]
Same issue

**Comment by santipapo98** [comment]
Same here, I tried using experimentalForceLongPolling option (which for people on 8 version has worked) but I couldn't find it for 9.15.0

**Comment by mikehardy** [comment]
> import { collection, addDoc } from "firebase/firestore";

That's not an import that implies use of react-native-firebase, that looks like firebase-js-sdk, so is not relevant in this repo, you should look at firebase-js-sdk repo I think

The parts of the template that are important to perhaps provide counter-evidence to my assertion there are ignored, so I will close this as not actionable.

Others posting "me too" are likely looking at something unrelated or are also having a problem with firebase-js-sdk, please open new issues *if they involve react-native-firebase* and include requested template information so the people you are requesting help from can help you (https://stackoverflow.com/help/how-to-ask)

**Comment by shoaiby31** [comment]
Thanks for your guidance, I found the reason behind this problem. And it was due to version conflict in Firebase and Firestore. @mikehardy @santipapo98

**Comment by shoaiby31** [comment]
> Same issue

I think this is due to version conflicts in firebase and firestore. remove firebase, firebase/app, firebase/firestore from project. and then reinstall them with same version. e.g, npm install firebase@9.11.6

**Comment by santipapo98** [comment]
> Thanks for your guidance, I found the reason behind this problem. And it was due to version conflict in Firebase and Firestore. @mikehardy @santipapo98

Thanks for the update !

**Comment by mikehardy** [comment]
That is still firebase-js-sdk, it has nothing to do with react-native-firebase - to be clear for anyone that stumbles on this.
