### ISSUE TITLE
Google Play Store warn to update firebase-crashlytics in react-native mobile app

### ISSUE THREAD

**Issue by RioAU** [invertase/react-native-firebase#6813]
I have developed my mobile application in react-native, where I have used @react-native-firebase/crashlytics to track crashes in my application. Everything is working fine.

In my last upload .aab to PlayStore, google warn me to update firebase Crashlytics and they will not support after march. Here is the message I got from them.

```We detected an issue in this version of the Crashlytics Android SDK. We strongly recommend either using v18.2.13 or earlier or upgrading to v18.3.1+. For more info see: https://github.com/firebase/firebase-android-sdk/issues/4223
Starting from March 18, 2023 00:00 (UTC) you won't be able to release new versions which contain this SDK version.```

I have used latest @react-native-firebase/crashlytics npm in my project, but still it showing the same sdk(18.3.0) in my android project.

Check this link to understand more in deep. 

https://stackoverflow.com/questions/75003899/google-play-store-warn-to-update-firebase-crashlytics-in-react-native-mobile-app

**Comment by mikehardy** [comment]
Hi there! You've opened an issue but oddly you have requested help but ignored our issue template so I cannot provide detailed help (https://stackoverflow.com/help/how-to-ask)

I can only infer that you are on an outdated version of react-native-firebase which includes an outdated version of firebase-android-sdk (which transitively includes an outdated version of crashlytics) or you have specifically overridden the firebase-android-sdk dependency such that it is outdated.

I can only guess based on incomplete information that the likely solution is to make sure you are on current version of react-native-firebase and that you remove any firebase-android-sdk version overrides in your build.gradle files if you have overridden it.
