### ISSUE TITLE
[🐛] [auth/internal-error] an internal error has occurred, please try again. (IOS Problem but Android worked). When use func verifyPhoneNumber

### ISSUE THREAD

**Issue by trungdh-itealteam** [invertase/react-native-firebase#6822]
## Issue
Our dependencies are :
 ```
"@react-native-firebase/app": "^16.5.0",
 "@react-native-firebase/auth": "^16.5.0",
```
Output ios :
`[Error: [auth/internal-error] An internal error has occurred, please try again.]`

Below Js Code: 
`     const otherApp = firebase.app(env.APP_USER_NAME);
        firebase.auth(otherApp).verifyPhoneNumber(phone).then((response) => {}).catch(e => console.log(e))`

**Comment by mathysFor** [comment]
> @trungdh-itealteam hey guys, stuck with this issue and all my iOS users are blocked. Have you guys been able to find any solution for this? This broke when we transferred the app to another App Store account. Please let us know. Thank you.

Hello,Same problem. Did you find a solution ?

**Comment by chandrahasan1** [comment]
Hey @mathysFor, Yes. We found the solution. The APNS not properly configured in the app and that is root cause. Here in this case for real devices the Firebase SDK users Silent Push notifications. In case of failure of push notification, it was NOT properly handled in the RN SDK.

Thanks,
Chandu.
