### ISSUE TITLE
Appcheck error in react native android

### ISSUE THREAD

**Issue by mo-nizar** [invertase/react-native-firebase#6831]
Implemented app check for React Native. it is working perfectly in ios but returns an error in android.

hereby attached the code and error.

environment: Production / Release

Code:
    if (Platform.OS === 'android') {
      await appCheck().activate('ignoredParam', true);
      appcheck = await appCheck().getToken();
    } else {
      appcheck = await appCheck().getToken(true);
    }

Error:
  [appCheck/token-error] com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.

**Comment by vivekcubet** [comment]
is there any update on this?

encountered the same error.

**Comment by mikehardy** [comment]
The template has been ignored, this issue is not valid and will be closed.
I would check configuration though and make sure safetynet for android has been turned on.
Shortly you will be able to use Play Integrity but it's not ready yet - working on it here #6847
