### ISSUE TITLE
how can I attach image in push notification in IOS app

### ISSUE THREAD

**Issue by rbsl-rimjhim** [invertase/react-native-firebase#684]
I created a react native app for IOS and sending push notification successfully. 
But now I want to send image as well. Can someone guide me how to achieve this?

**Comment by chrisbianca** [comment]
@rbsl-rimjhim other than the icon, this isn't supported at the moment. We plan on overhauling FCM in our next version and will try to add this going forward. In the meantime, please follow: https://github.com/invertase/react-native-firebase/issues/595
