### ISSUE TITLE
[🐛] Error: [messaging/unknown] The operation couldn’t be completed. (com.firebase.iid error 1001.)

### ISSUE THREAD

**Issue by miteshdb** [invertase/react-native-firebase#6842]
There is no change in code, issue suddenly started to appear ..

When I call the await messaging().getToken() it is always returning above error. when I request for permission it returns 1 so it is working perfectly.

My concern is there is no change in podfile.lock or any other versions, following are the versions I'm using right now.
```

@react-native-firebase/analytics": "^11.3.2",
    "@react-native-firebase/app": "^11.3.2",
    "@react-native-firebase/crashlytics": "^11.3.2",
    "@react-native-firebase/messaging": "^11.3.2",
    "@react-native-firebase/perf": "^15.7.0",
    "react": "17.0.1",
    "react-native": "0.64.4",

```

Need to get bottom of the issue asap, help would be appreciated, thanks

**Comment by rrasconc** [comment]
Same issue here with iOS 

``
"@react-native-firebase/app": "16.4.6",
"@react-native-firebase/messaging": "16.4.6",
``

**Comment by mikehardy** [comment]
Hi there - with apologies @miteshdb - v11 is not current and is too old to support. IID no longer exists as a package (it was replaced by Installations) and we cannot support it.

@rrasconc As mentioned IID is no longer a package, so it is curious this is happening, please open a new / separate issue with information requested in the template and following the general spirit of https://stackoverflow.com/help/how-to-ask and https://stackoverflow.com/help/minimal-reproducible-example with relevant logs from device and versions of software in use for us to help better, thanks
