### ISSUE TITLE
onSnapshot does not fire for server event in Android. Works fine in IOS

### ISSUE THREAD

**Issue by pavanmehta91** [invertase/react-native-firebase#685]
### Issue
```
.onSnapshot(querySnapShot=>{
      let newMessages = [];
      let source = '';
      querySnapShot.forEach((chatDoc)=>{
        let chatData = chatDoc.data();
        source = chatDoc.metadata.hasPendingWrites ? 'local' : 'server';
        newMessages.push(chatData);
        console.log(chatData);
      });
```
Here to avoid multiple rewrites to my array I've differentiated the onSnapshot callback's call by local and server updates. In IOS the behavior is as expected. But in android the callback is only called once i.e for local event only.

### Environment

1. Application Target Platform:  Android

2. Development Operating System:  MacOS High Sierra

3. Build Tools: React-native run-android

4. React Native version: 0.47

5. RNFirebase Version: 3.1.1

6. Firebase Module: fire store

**Comment by chrisbianca** [comment]
@pavanmehta91 This sounds like it is likely to be an issue with the underlying Android SDK. Are you able to add break points in the Android code to prove that you're not receiving the notification from the underlying SDK?

**Comment by pavanmehta91** [comment]
I'll try and do that and let you know. Thanks.

**Comment by Ehesp** [comment]
Please let us know if you've managed to debug and we'll reopen.
