### ISSUE TITLE
firestore().collection(collectionName) throws "undefined is not a function" error

### ISSUE THREAD

**Issue by ryan-schwarz** [invertase/react-native-firebase#6855]
Hi!

I have my firebase setup what I believe to be correct, all are on version **16.5.1**. All works well with the **auth** library, to log in and out, sign up, etc. 

I wanted to fetch my "Users" collection in my Cloud Firestore, but for some reason it keeps throwing this error. I completely uninstalled everything and rebuilt my app, pods, and npm packages. The app itself builds successfully, but again, when it comes time to get my "Users" collection is can't be done. Any help is greatly appreciated!

Here is how I send my firestore request:

```javascript
import firestore from '@react-native-firebase/firestore';

  const getData = () => {
    const db = firestore()
      .collection('Users')
      .doc('ryan')
      .then(docSnapshot => {
        if (docSnapshot.exists) {
          const userData = docSnapshot.data();
          console.log(userData);
        }
      });
};

 console.log(db);

  useEffect(() => {
    getData();
  }, []);
```

**Comment by mikehardy** [comment]
This seems like it will be some basic javascript thing, not really a firebase/firestore thing but I'm not 100% sure.

We have a lot of example usage in our e2e test suite, for instance this:

https://github.com/invertase/react-native-firebase/blob/97a5523bac4570ba7b47fbfdbb22348f38246d11/packages/firestore/e2e/DocumentReference/get.e2e.js#L55-L63

That uses async/await style so if you want to stick with the .then/.catch style you'll have to mentally convert

Things I notice:
- we use path addressing to just specify a doc, you could do the same, that is don't get collection/doc, just get the doc by path, that is `firestore().doc('Users/ryan');` to make your `CollectionReference`
- I don't see a '.get()` here? I am expecting `firestore().doc('Users/ryan').get().then(docSnap => console.log(JSON.stringify(docSnap.data()))` or similar

**Comment by ryan-schwarz** [comment]
Yup! It's always the smallest things that I can't catch. Thanks for saving me here, it works now!

**Comment by mikehardy** [comment]
Sweet - glad to hear. Going to close this - good luck on your project!

**Comment by danielkv** [comment]
I'm having a similar issue:

```tsx
export async function getDataUseCase() {
    const fs = firebase.firestore()
    
    const snapshot = await fs.collection('myCollection').get()

    return snapshot.docs.map((doc) =>doc.data())
}
```

The `const fs` has the expected value, but the `get` method does not exist
