### ISSUE TITLE
[🐛] I don't receive SMS message (status code: 17093)

### ISSUE THREAD

**Issue by TsplayerT** [invertase/react-native-firebase#6859]
## Issue

I'm developing an Android application using Expo. 🔥

Using a physical device (_SM-A705MN, Android 11 - API 30_) connected via USB (_Win 10 Home 21H2_) when typing my phone number, a popup appears with the error message:

`Error: [auth/missing-client-identifier] This request is missing a valid app identifier, meaning that neither Safety checks nor reCAPTCHA checks succeeded. Please try again, or check the logcat for more details.`

Further in the command line tool (logcat) dumped this log:

`E/FirebaseAuth(32314): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17093 null`

- I have already configured the Firebase SDK by placing the fingerprints of the SHA-1 and SHA-256 certificates of the development (_debug_) security certificates (_Keystore_) through the official website, on the project Configuration page.
- I have already added the configuration file (_JSON_) that contains the app keys and identifiers in the project code.
- I already enabled the Android Device Verification (_DEPRECATED_) API on the Google Cloud Console website.

**Note:** when I put the phone number for testing on the login providers settings page (_authentication_) I receive the API information normally even without receiving a text message by SMS

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json

  "dependencies": {
    "@react-native-firebase/app": "16.5.2",
    "@react-native-firebase/app-check": "16.5.2",
    "@react-native-firebase/auth": "16.5.2",
    "@react-native-firebase/firestore": "16.5.2",
    "expo": "47.0.13",
    "react": "18.2.0",
    "react-native": "0.71.1"
  }

```

</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `16.5.2`
- **Are you using `TypeScript`?**
  - `4.9.4`

</p>
</details>

## Attachments
<details><summary>Click To Expand</summary>
<p>

[SMS-verification-code-request-failed.log](https://github.com/invertase/react-native-firebase/files/10492791/SMS-verification-code-request-failed.log)

![680039c8-3503-4a7e-b11f-7ef719850644](https://user-images.githubusercontent.com/6465230/214372642-87dbe183-cef0-4117-b537-43f325cfd300.png)

</p>
</details>

---

**Comment by mikehardy** [comment]
Hi there! This is a project-specific configuration issue, it will not result in a change to this module so I will close this issue after submitting this comment

There is prior knowledge in our issues list that discusses how to get the SHA-1 and SHA-256 of your app, I assume with a new app you are using the ABB bundle style so you'll need to go to the google play dashboard for your app and get the SHA-1/SHA-256 for the key that google play uses to re-sign the app with, and put that in the firebase console. Most likely anyway...

https://github.com/invertase/react-native-firebase/issues?q=is%3Aissue+auth%2Fmissing-client-identifier

https://search.brave.com/search?q=firebase+auth%2Fmissing-client-identifier

**Comment by TsplayerT** [comment]
Firebase is already configured with the SHA-1 and SHA-256 fingerprints of the development security certificates (_debug.keystore_)

I also already added the SHA-1 and SHA-256 fingerprints of the app signing key certificate found in the Google Play Console, but I don't think it should interfere with anything at this point.

I'm sorry, but I don't understand what I need to do to receive SMS text messages normally.

**Comment by mikehardy** [comment]
Perhaps through the vagaries of the Expo build process, the `google-services.json` for your firebase app from the firebase console is not being included in your build

I'm not sure exactly *what* is going on but this error means your project is not configured. Firebase does not recognize the app talking to it. Either because it is not identified at all (the JSON file) or because it is not signed in a way it recognizes (the SHAs). I'm not sure what you need to do either but it will be something in your configuration

**Comment by TsplayerT** [comment]
I deleted the `android` folder and ran `npx expo prebuild --clean` command
Made it regenerate this folder and again included the configuration file `google-services.json`

This led to a new error:

`SMS verification code request failed: unknown status code: 17028 A safety_net_token was passed, but no matching SHA-256 was registered in the Firebase console. Please make sure that this application's packageName/SHA256 pair is registered in the Firebase Console.`

That last part of the error message, can help me understand what it would be: `application's packageName/SHA256 pair` ?

**Comment by mikehardy** [comment]
With apologies, we use this issue tracker to track and fix errors in the package, it is not a general help desk. Stackoverflow is a general helpdesk and appears to have related information:

https://search.brave.com/search?q=A+safety_net_token+was+passed%2C+but+no+matching+SHA-256+was+registered+in+the+Firebase+console.+Make+sure+this+app%27s+packageName%2FSHA-256+pair+is+registered+in+the+Firebase+console&source=desktop

**Comment by longb1997** [comment]
+1, did you resolve this? @TsplayerT

**Comment by TsplayerT** [comment]
@longb1997 I deleted the android folder and after automatically recreating it, I added the **JSON** file in the `android/app/google-services.json` directory

**Comment by Cleversou1983** [comment]
I'm using expo prebuild and facing the same issue...
