### ISSUE TITLE
Remote Config Condition ( Segmented User From Custom User Property Analytic )

### ISSUE THREAD

**Issue by pramahaditamaputra** [invertase/react-native-firebase#6871]
Hi Guys,

I have a plan to do an A/B test with targeting segmented user with data from Custom User Property Analytics

in custom User Property it just support value string or number with limit 36 char, so i can't put object or array on it

let say i set the value with string 12,121,1212

how to achieve condition only true for user 12 and the 121,1212 will not true ?

i tried with this

![Screen Shot 2023-01-27 at 17 23 12](https://user-images.githubusercontent.com/30662967/215063725-5ca99ec6-4494-44b5-9c55-3626e92ec265.png)

but the condition will also true for 121 and 1212 too

any suggestion for achieve this ?

**Comment by mikehardy** [comment]
I think this might be better on stackoverflow, tagged up appropriately the core firebase team should give it a look. I don't think we have experience with this directly here at react-native-firebase
