### ISSUE TITLE
🔥 [🐛] Crashlytics - Android doesn't show stack traces for JS crashes / warnings

### ISSUE THREAD

**Issue by Avishayy** [invertase/react-native-firebase#6878]
## Issue

I'm using react-native-firebase-crashlytics to report errors / diagnose crashes. 
One example from my code is
```typescript
    const response = await fetch(...); // API call here is done here

    if (response.status !== 200) {
      const err = new Error(`Unexpected status ${response.status}`);
      crashlytics().recordError(err);
      console.log(err);
      return;
    }
```

and (un?)fortunately, I can see the relevant issue on crashlytics with a valid stack trace on iOS:
(the obfuscated paths are later resolved with the sourcemap locally)
![image](https://user-images.githubusercontent.com/5567310/216120122-41923f01-2d3a-418b-8f8f-63979c3d211c.png)
(iOS has the error string in the non copy-able title)
```
Non-fatal Exception: JavaScriptError
0  ???                            0x0 ?anon_0_ + 2372 (main.jsbundle:2372:661:2372)
1  ???                            0x0 next ((native):0:0)
2  ???                            0x0 n + 277 (main.jsbundle:277:69:277)
3  ???                            0x0 v + 277 (main.jsbundle:277:280:277)
4  ???                            0x0 tryCallOne + 53 (InternalBytecode.js:53:16:53)
5  ???                            0x0 anonymous + 139 (InternalBytecode.js:139:27:139)
6  ???                            0x0 apply ((native):0:0)
7  ???                            0x0 anonymous + 74 (main.jsbundle:74:1495:74)
8  ???                            0x0 w + 74 (main.jsbundle:74:448:74)
9  ???                            0x0 N + 74 (main.jsbundle:74:721:74)
10 ???                            0x0 callReactNativeMicrotasks + 74 (main.jsbundle:74:2882:74)
11 ???                            0x0 value + 57 (main.jsbundle:57:2936:57)
12 ???                            0x0 anonymous + 57 (main.jsbundle:57:1046:57)
13 ???                            0x0 value + 57 (main.jsbundle:57:2584:57)
14 ???                            0x0 value + 57 (main.jsbundle:57:1005:57)
15 ???                            0x0 value + 57 (main.jsbundle:57:940:57)
```
---

However, on Android, the crash on the exact same place (I know it has to be the same one because there's only one occurrence of that error), looks like this on crashlytics:
(Note that the error string exists `Unexpected status 403`)
```
Non-fatal Exception: io.invertase.firebase.crashlytics.JavaScriptError: Unexpected status 403
       at .?anon_0_(.java)
       at .next(.java)
       at .asyncGeneratorStep(.java)
       at ._next(.java)
       at .tryCallOne(.java)
       at .anonymous(.java)
       at .apply(.java)
       at .anonymous(.java)
       at ._callTimer(.java)
       at ._callReactNativeMicrotasksPass(.java)
       at .callReactNativeMicrotasks(.java)
       at .__callReactNativeMicrotasks(.java)
       at .anonymous(.java)
       at .__guard(.java)
       at .flushedQueue(.java)
       at .invokeCallbackAndReturnFlushedQueue(.java)
```

I know for a fact that this doesn't only happen with `recordError()`, I'm having a JS crash that happens on Android only and I can't pinpoint the cause as the stack trace is unhelpful.

Moreover, native Android crashes do show java stack traces, so it leads me to believe that this is an issue with react-native-firebase rather than firebase-android-sdk

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
{
    "react-native": {
        "crashlytics_debug_enabled": false,
        "crashlytics_disable_auto_disabler": true,
        "crashlytics_auto_collection_enabled": true,
        "crashlytics_is_error_generation_on_js_crash_enabled": true,
        "crashlytics_javascript_exception_handler_chaining_enabled": false
    }
}

```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 30.29 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.2.0 - ~/Projects/user/project/node_modules/.bin/npm
    Watchman: 2023.01.09.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 21.4.7075529
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `16.4.6`
- **`Firebase` module(s) you're using that has the issue:**
  - `react-native-firebase`
- **Are you using `TypeScript`?**
  - `Y` & `4.9.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Have you searched the issues lists for duplicates? I believe this is discussed a few times

https://github.com/invertase/react-native-firebase/issues?q=is%3Aissue+crashlytics+stacktrace+sort%3Acomments-desc+

This is probably the most discussed one #3760

You are correct that it is not firebase-android-sdk because they know nothing of javascript, we have to feed them a simulated stack trace reconstructed from the javascript stack.

We have to do that despite not having any way to reconstruct it from a minimized + obfuscated bundle though. How would you propose de-obfuscating the stack, given no symbol maps that go from javascript source to bundle? (or worse: from typescript, to javascript, to bundle?)

I'm not sure the problem is tractable.

I'm not sure why on iOS you at least get bundle line numbers while on android it is just a .java filename with no number though - would be great if you (or someone interested, with time) could investigate and figure out how to make the firebase crashlytics console show the bundle line number. I believe we're generating the javascript stacks the same way on both platforms so we should have knowledge of the line number...

**Comment by Avishayy** [comment]
I'll clarify, I'm not asking react-native-firebase to deobfuscate the stack traces. I have a local script that handles parsing the stack trace and uses the locally saved sourcemaps to do so. (Which is why the linked issue or any other issue I found is irrelevant)

The real issue I want to adderss here is the variance between iOS and Android (like you mentioned on the last paragraph), iOS includes the bundle paths, while Android doesn't.

I will spend some time figuring out why the JS stack generation doesn't work on Android and hopefully update with a solution soon.

**Comment by mikehardy** [comment]
I would definitely appreciate any insight if you perform testing and discover something

Will be some sort of incompatibility between one of three items I think -

a) the error transform we do here https://github.com/invertase/react-native-firebase/blob/1b8df4c8e55d474c09e301f9c7b58b6128ae6485/packages/crashlytics/lib/handlers.js#L25

b) and the repackaging here ... https://github.com/invertase/react-native-firebase/blob/1b8df4c8e55d474c09e301f9c7b58b6128ae6485/packages/crashlytics/android/src/main/java/io/invertase/firebase/crashlytics/ReactNativeFirebaseCrashlyticsModule.java#L195-L202

c) prior to forwarding to crashlytics where it may be interpreted correctly or incorrectly

**Comment by Avishayy** [comment]
Unfortunately I couldn't reproduce this :(

At first I stepped through the native code, it was fine on debug. I ran the flows to reach the error recording paths, the stack traces on my own devices – Pixel 6 Pro Android 13 and Pixel 8 Pro Android 11, for both debug and release are looking as expected, the bundle paths are there.

What I can say is that almost all devices I saw with the `.java` paths (around 11 devices) were a Samsung Galaxy variant with Android 12 or Android 13, except for one that was OnePlus 6 Android 11.

Since I don't have any of those devices, I can't confirm whether this issue is real, perhaps it's Samsung only (mostly?) or maybe it got magically fixed, I guess I'll wait for more crashes.

**Comment by Avishayy** [comment]
I did manage to get my hands on a Samsung device and test it, but crashing on release from my local build still creates stack traces with valid bundle paths, I wonder if uploading the app to Play Store somehow strips that information.. (Maybe they don't expect non .java files as part of stack traces? I really don't know)

**Comment by Avishayy** [comment]
I can confirm what I said before, it's somehow due to the Play Store.. I created a crash on my device with the Play Store install, and sure enough, the stack traces are pathless. I then took the exact same build that was done locally and the paths were back.

As an additional sanity I went to the release in the play console
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/5567310/216714366-49faed5a-443e-4cd2-8c2b-ae2fff28804e.png">
The original file (.aab) creates a crash with bundle paths, the signed universal APK creates the missing paths (.java).

I'm re-opening this because it seems somewhat actionable now, @mikehardy do you have any suggestions on how to tackle this?

**Comment by mikehardy** [comment]
I see what you are saying but I do not see how that is actionable 🤔 - we have no control over the play store aab -> apk conversion and there's no insight into possible workarounds to mitigate whatever that conversion is messing up

**Comment by mikehardy** [comment]
This is still on my "stretch goals..." list. Obviously happy for any motivated person to take it up, but I'll keep it open a bit longer

**Comment by douglasjunior** [comment]
Just to bring more information to the table, here we have cases that the Crashlytics was reporting errors with wrong line/columns in stack trace.

For some reason, recently the Crashlytics logs are point always for line `1`:

![image](https://github.com/invertase/react-native-firebase/assets/1512341/e882b2fa-f306-4ed8-88b7-f575ae0f4ae3)

But, when we look at the transpiled bundle generated by `react-native`, our code is not entire compressed in line `1`:

![image](https://github.com/invertase/react-native-firebase/assets/1512341/27575eb2-c617-4e4f-8779-9cf0d98320fc)


So this makes us to understand that the Play Store is changing something during the .aab -> .apk conversion too.

**Comment by douglasjunior** [comment]
> Hi @douglasjunior, have you been able to symbolicate the stacktrace? I got the same issue and don't know how to fix it
> 

Unfortunately not.

**Comment by rajeshias** [comment]
> Unfortunately not, today the Crashlytcis on React Native is almost useless to help with JavaScript crashes.

So what is the solution?. I am a Developer from a large bank sector. And our banking App uses crashlytics. The majority of crashes ~4 Million are plain JavaScriptException. It is totally useless if we cannot find exactly which part the App crashes with this report.

**Comment by Avishayy** [comment]
@rajeshias Currently there's no solution, and this is a free open source project. Either invest the resources needed into fixing it, find an alternative, or develop your own.

**Comment by kukuandroid** [comment]
@Avishayy can you share the script u used to track the js error ?
