### ISSUE TITLE
[📚] Dependency table for legacy build systems (XCode, and Android Studio if relevant)

### ISSUE THREAD

**Issue by evangrim** [invertase/react-native-firebase#6879]
## Documentation Feedback

_Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:_

If possible, please document which version of React Native Firebase is appropriate for recent versions of XCode. If relevant, please include similar/relevant information for Android Studio and/or Gradle.

I'd suggest putting a dependency table for iOS in the [Prerequisites section](https://rnfirebase.io/#prerequisites):
> Additionally, current versions of firebase-ios-sdk have a minimum Xcode requirement of 13.3, which implies a minimum macOS version of 12 (macOS Monterey).

**Context:**
I'm unable to update past MacOS 11 for now, because I need to support some legacy software awhile longer. Speaking for myself, I've also had trouble finding information browsing through the repo, looking for release info, and examining the Firebase SDK docs, so at my skill level the answer will be trial and error, which is quite painful while updating an app. Documenting this will help more people like me get back on the "happy path". 

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
We require Xcode 13.3,1+ which requires macOS 12.5+, it comes from the firebase-ios-sdk repo's requirements:
https://github.com/firebase/firebase-ios-sdk#development

It is already listed in our prerequisites? https://rnfirebase.io/#prerequisites

**Comment by mikehardy** [comment]
You had a secondary question which is I think guessing at backwards compatibility, I'm not sure exactly what the matrix would look like with regard to what versions are compatible with what. I think you might be stuck on v14 or lower, but honestly the thing about the new versions is that they are typically handling compatibility issues with newer versions of mobile devices, or fixing issues, or both, so to be frank: we don't support the old versions or think about them too much - we have limited resources and look forward almost exclusively.

You might try isolating your macOS11 stuff in a VM (like perhaps https://github.com/kholia/OSX-KVM/ which works well for me, especially on the older macOS versions) or if it's a hardware think you can get old macs running new macOS with https://dortania.github.io/OpenCore-Legacy-Patcher/ (which I also use and works well).

In general though, we expect folks to stay up to date and don't support old versions

**Comment by evangrim** [comment]
That's already listed on prerequisites. My question is, how far back do I have to go (in terms of react-native-firebase versions) to build on an older version of Xcode?

Currently "my" app is running version 7, but it no longer builds for Android. My assumption (and hope) is that there's a viable version between 7 and current. Here's what I need to update from, from package.json:

`"@react-native-firebase/app": "^7.1.0",
    "@react-native-firebase/messaging": "^7.1.0",`

**Comment by evangrim** [comment]
OK, I totally understand where you're coming from: it gets increasingly difficult to support older versions, especially as time progresses.

I will try version 14 (and otherwise try a VM, either locally or on EC2), and please feel free to close this issue. I appreciate your response.

**Comment by mikehardy** [comment]
I'd go back step-wise on the majors, v15 first, then v14, then v13 etc. Note that if you go to v14 you may avoid some pain because it doesn't require `use_frameworks! :linkage => :static` in the Podfile, and since that directive is potentially troublesome avoiding it is at least one positive in the experience

I will close those, but I do wish you luck with your project. Cheers

**Comment by evangrim** [comment]
For posterity:

1. It looks like I will be able to work with @react-native-firebase/app 14.11.1 using [Xcode 13.2.1 ](https://developer.apple.com/download/all/?q=xcode) (link requires sign in with Apple dev account) -- will try to update if this doesn't pan out
2. I think this is the general thing mikehardy is referencing in [his previous comment](https://github.com/invertase/react-native-firebase/issues/6879#issuecomment-1412765237):

ios/Podfile
```
  # The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which does not define modules.
  # To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), 
  # you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
  # (BUT use_modular_headers! conflicts with Flipper, so set modular headers only on Firebase dependencies)
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Firebase/Messaging', :modular_headers => true

```

**Comment by mikehardy** [comment]
Hmm modular_headers is an unsupported workaround for people attempting to avoid the use_frameworks requirements, to be honest I don't even like seeing it mentioned as it gets people's hopes up. Use_frameworks is the strict requirement and is the only compilation style we support
