### ISSUE TITLE
Typescript definitions not found (v 3.1.1)

### ISSUE THREAD

**Issue by pheromonez** [invertase/react-native-firebase#688]
### Issue

Typescript definition file not found (with default Typescript settings) when using `react-native-firebase 3.1.1`. This is because the definition file is now located at `./lib/index.d.ts` rather than simply `./index.d.ts`, which is where Typescript expects to find it.

For anyone that needs it, the location of the definition file can be forced by including this in any file where `react-native-firebase` is needed: `/// <reference path="../node_modules/react-native-firebase/lib/index.d.ts" />`. Ideally though, it would be nice to have the definition file at `./index.d.ts` so that everything 'just works' out of the box, exactly the way it did in `react-native-firebase 3.1.0`

### Environment

(Not really relevant)

**Comment by chrisbianca** [comment]
@pheromonez Thanks for raising this - a fix is ready to be deployed with the next release

**Comment by IljaDaderko** [comment]
@chrisbianca just ran into same issue, since this was posted a month ago wanted to ask if you guys have and eta for next release that fixes this?

**Comment by Ehesp** [comment]
@IljaDaderko It's already live, from 3.2.0

**Comment by IljaDaderko** [comment]
@Ehesp I'm still seeing errors like this `auth doesn't exist on firebase` and by looking at the master branch, index.d.ts is still located in `./lib/index.d.ts` as author mentioned.

**Comment by pheromonez** [comment]
@IljaDaderko My original post was about the `Could not find a declaration file for module 'react-native-firebase'` error.
In your case, the typings are being brought in correctly however you may not be using the interface in the intended way. For instance, we use the `messaging` module in our application, and our code looks like this:
```typescript
import firebase from 'react-native-firebase'
const messaging = firebase.app().messaging()
messaging.onMessage((message) => console.log(`Message received!`))
```

Change `messaging` to `auth` to access the `auth` module.

**Comment by IljaDaderko** [comment]
@pheromonez you are right, that resolves it.
