### ISSUE TITLE
CocoaPods could not find compatible versions for pod "FirebaseCore"

### ISSUE THREAD

**Issue by uboltabaev** [invertase/react-native-firebase#6882]
Hi, I am getting an error when I try to install Firebase Storage into my project.

`[!] CocoaPods could not find compatible versions for pod "FirebaseCore":
  In snapshot (Podfile.lock):
    FirebaseCore (= 10.4.0, ~> 10.0)

  In Podfile:
    Firebase was resolved to 10.4.0, which depends on
      Firebase/Core (= 10.4.0) was resolved to 10.4.0, which depends on
        FirebaseAnalytics (~> 10.4.0) was resolved to 10.4.0, which depends on
          FirebaseCore (~> 10.0)

    FirebaseCore

    FirebaseStorageInternal was resolved to 9.6.0, which depends on
      FirebaseCore (~> 9.0)

    RNFBApp (from `../node_modules/@react-native-firebase/app`) was resolved to 16.7.0, which depends on
      Firebase/CoreOnly (= 10.4.0) was resolved to 10.4.0, which depends on
        FirebaseCore (= 10.4.0)

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `FirebaseCore` inside your development pod `RNFBApp`.
   You should run `pod update FirebaseCore` to apply changes you've made.`

Here is my Pod file:

`# Override Firebase SDK Version
$FirebaseSDKVersion = '10.4.0'
$RNFirebaseAsStaticFramework = true
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'edukonim' do
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseStorageInternal', :modular_headers => true
  pod 'GTMSessionFetcher', :modular_headers => true
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true

  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'edukonimTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
`

**Comment by mikehardy** [comment]
```

pod 'Firebase', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseAppCheckInterop', :modular_headers => true
pod 'FirebaseAuthInterop', :modular_headers => true
pod 'FirebaseCoreExtension', :modular_headers => true
pod 'FirebaseStorageInternal', :modular_headers => true
pod 'GTMSessionFetcher', :modular_headers => true
pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true
```

This Podfile configuration is not supported, I will close this issue.

`use_frameworks! :linkage => :static` is *strictly* required, as a transitive requirement from firebase-ios-sdk

**Comment by aurangs7** [comment]
@mikehardy I am reading your comments and trying to resolve my exact issue, but not able to solve it. Need your help and guidance

my versions are:
**React-Native: 0.61.5
"@react-native-firebase/app": "^17.5.0"**

I am simply following the official react-native-firebase [documentation](https://rnfirebase.io/) for the iOS setup but getting this error while installing the pods.

What I tried:

1. pod install --repo-update   
2. npx pod-install
3. download old version of the lib and try 
4. delete podfile.lock and clean pod cache and all.

There are some links I've followed but no luck yet. 

Is there anything specific I've to do in this react-native version(0.61.5)? 

Attached the screenshot of the error and pod file:

<img width="977" alt="Screenshot 2023-05-30 at 16 38 22" src="https://github.com/invertase/react-native-firebase/assets/110371514/50fe02fe-c941-4cf6-b7e8-712783956cfb">
<img width="1067" alt="Screenshot 2023-05-30 at 16 32 30" src="https://github.com/invertase/react-native-firebase/assets/110371514/1be85d4c-05e9-44c1-aecc-80921a7e5067">

**Comment by aurangs7** [comment]
OK... Updating the react-native-camera version fixed the issue for me.

https://github.com/react-native-camera/react-native-camera/issues/3166

**Comment by Siliconvelly** [comment]
how can react-native-camera updating can be work although i didn't installed that library i am facing issue in my react-native-firebase having same issue 

[!] CocoaPods could not find compatible versions for pod "FirebaseCoreExtension":
  In Podfile:
    RNFBMessaging (from `../node_modules/@react-native-firebase/messaging`) was resolved to 18.1.0, which depends on
      FirebaseCoreExtension (= 10.11.0)

None of your spec sources contain a spec satisfying the dependency: `FirebaseCoreExtension (= 10.11.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

i tried pod install --repo-update but it also gives error like

LoadError - incompatible library version - /Users/adadminmin/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.15.5/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

**Comment by masteread** [comment]
![Screenshot 2023-12-05 at 11 09 39 p m](https://github.com/invertase/react-native-firebase/assets/64763962/ec331463-38c0-4c59-859f-c5d01394fbea)

I had this issue. Removing the version number after the: pod 'Firebase/CoreOnly' seems to be the solution

**Comment by chiragthummar** [comment]
I have resolved by opening terminal at your project directory

1.` cd ios` 
2. `run pod repo update`

The issue was Firebase Dependency was not updated to latest.

**Comment by pierroo** [comment]
> @masteread there is no reason to have those pods directly referenced in your Podfile. react-native-firebase expects to have control over which Firebase pods are referenced and at which versions since...this is the react-native-firebase module and those are the Firebase pods. Kind of follows
> 
> This all happens in this module's podspecs
> 
> I suspect you have some "modular_headers" stuff in your Podfile which is the only reason you have those specific references and the only reason I'm replying - there is _no_ reason to have those and they are specifically unsupported. It is likely you will have other build problems.
> 
> Note that Flipper historically has been a reason people do this as it does not support static frameworks, but Flipper is deprecated in the react-native ecosystem so is not a future-looking solution at any rate. I'd make sure you're using static_frameworks, remove modular headers workarounds, and remove any Firebase references

But that is precisely the problem for me as well;
If I dont add those modular headers in pod file for the firebase stuff, I get the error:

```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

The Swift pod `FirebaseDatabase` depends upon `leveldb-library`, `FirebaseCore`, and `FirebaseAppCheckInterop`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

The Swift pod `FirebaseFirestore` depends upon `FirebaseCore`, `FirebaseCoreExtension`, and `FirebaseFirestoreInternal`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

The Swift pod `FirebaseStorage` depends upon `FirebaseAppCheckInterop`, `FirebaseAuthInterop`, `FirebaseCore`, `FirebaseCoreExtension`, and `GTMSessionFetcher`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

And when I do add the modular headers, then I get "could not find compatible versions" of this GitHub issue..

I am stuck in between with no solution @mikehardy

**Comment by mikehardy** [comment]
> however it is disgusting the amount of issues it brings when using use_frameworks; it breaks so many other packages upon trying to build.

Work with those packages to get them building well with use_frameworks, other than Flipper (which is now deprecated, so, no use spending time on it) I was able to push through changes or work with maintainers to do so in all the packages I use. It's the harder path but also the correct one

**Comment by jyotiprakash111** [comment]
![pod issue](https://github.com/invertase/react-native-firebase/assets/45302047/a35682f2-e29f-496b-818a-75fb6b468c3a)
 Facing the same, please anyone help me here..

**Comment by wolfxpertlab** [comment]
just delete podfile.lock and  pod folder

after that pod install issue solved!

**Comment by Shonu72** [comment]
pod install --repo-update


this fixed my issue for flutter

**Comment by eeshankeni** [comment]
was trying this on expo, the plugins data was missing in app json as specified in the documentation

**Comment by lijing89** [comment]
Check the pods folder and verify the iOS versions supported by the plugins. The iOS version at the top of the podfile must be the same as the highest version required by the plugin.
