### ISSUE TITLE
AppCheck follow up issues

### ISSUE THREAD

**Issue by mikehardy** [invertase/react-native-firebase#6886]
This is an umbrella issue to collect known problems with the recent AppCheck overhaul released as v17 here from PR #6847 

- [x] iOS debugToken not applied from config - still requires environment variable setup
- [x] Android debugToken style [changed internally in firebase-android-sdk 31.2.0](https://github.com/firebase/firebase-android-sdk/pull/4436/commits/c339aa03dd2ff9f0105d32d06c214f1b922605e9) and needs re-work here before we can bump the firebase-android-sdk to current 
- [x] how to use debug provider is confusing in the docs - need to clarify perhaps with a debug/release build switch example
- [x] argument validation in config block could be improved
- [x] missing index.d.ts definition for `newReactNativeFirebaseAppCheckProvider` method (which exists in index.js...)
- [ ] no modular API

**Comment by felipecamposfabel** [comment]
I can't get `firebase.appCheck().getToken()` to work on Android on debug environments (android device and emulator). My project needs to use AppCheck only for external resources. I always end up getting the following error when calling getToken():

`[Error: [appCheck/token-error] com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.]`

Tested the 3 alternatives presented on rn-firebase docs. Tried passing a debug token to the provider configuration during runtime. Tried using `FIREBASE_APP_CHECK_DEBUG_TOKEN` parameter during build. And the `adb logcat | grep DebugAppCheckProvider` command doesn't return anything, so I couldn't try using the token.

For iOS I'm getting an "App not registered" error. I think it's because firebase needs both DeviceCheck and App Attest for it to work. So I need to do more tests on iOS.

Any help with that? And thanks for putting the effort on improving AppCheck!

**Comment by mikehardy** [comment]
@felipecamposfabel apologies - this is incomplete information. Knowing your version, and knowing how you are configuring your provider is required to know how to respond. You might see the example here, and note that with debug provider it works, with appAttest it fails (because it's not configured and doesn't work on an emulator anyway) then with debug provider it works again:

https://github.com/invertase/react-native-firebase/blob/4e170ead24035cd0154b153dcf1e8d69d6ab7ac9/packages/app-check/e2e/appcheck.e2e.js#L82-L156

I suspect your config is incorrect and you are expecting the debug provider behavior but you are configuring some non-debug provider.

If that's the case you'll be the second person to expect debug provider behavior without specifying the debug provider, indicating we need to drop a note in the docs to help people avoid it

**Comment by felipecamposfabel** [comment]
@mikehardy That must be it. I was not aware of the 'debug' provider. I think it would be great to clarify it on docs or on API Reference. Right now I'm getting a "too many attempts" but I'll try again later, and let you know if I still get any issues. Thanks for the quick help!

**Comment by mikehardy** [comment]
I'll try to clarify (and will add this to the list above, then collapse these comments) but it is documented, just that it is obviously confusing. Will try to remedy https://rnfirebase.io/app-check/usage#on-android

**Comment by bimix** [comment]
> I'll try to clarify (and will add this to the list above, then collapse these comments) but it is documented, just that it is obviously confusing. Will try to remedy https://rnfirebase.io/app-check/usage#on-android

newReactNativeFirebaseAppCheckProvider() function is not found, how are you even using it? It fails on build for me.

**Comment by mikehardy** [comment]
@bimix As an oversight on my part it is not in index.d.ts but it *IS* in index.js and exists. Notice empty / not completed yet fifth checkbox here

**Comment by mikehardy** [comment]
I will tag #6906 as closing this and we'll continue to track app-check with modular API in #6705

**Comment by bimix** [comment]
> @bimix As an oversight on my part it is not in index.d.ts but it _IS_ in index.js and exists. Notice empty / not completed yet fifth checkbox here

I am not following you, I have tested this and it fails because it cannot find that function:
firebase.appCheck().newReactNativeFirebaseAppCheckProvider();  // newReactNativeFirebaseAppCheckProvider cant be found

**Comment by mikehardy** [comment]
The latest version of the module has the function defined correctly in our typescript types.

**Comment by bimix** [comment]
> The latest version of the module has the function defined correctly in our typescript types.

you were right, only the newest version has that function. Guys, can you please please spend some more time in the documentation? We need to know how to actually use the appCheck in general, it's almost impossible to know how to use it from the current documentation. For example there are 2 different functions to initialize the app check and I have no idea which one to use it:
```
initializeAppCheck()
activate()
```
Also, should I use the following functions as below:
```
const rnfbProvider = firebase.appCheck().newReactNativeFirebaseAppCheckProvider();
rnfbProvider.configure({
   android: {
      provider: __DEV__ ? 'debug' : 'playIntegrity',
      debugToken: 'a07b3e55-4cc3-414f-a498-ffb6eerertda6c',
   }
});
firebase.appCheck().initializeAppCheck({
   provider: "ReactNativeAppCheckCustomProvider",
})
```
what's the difference between those two, because I am configuring the app check providers in both?

**Comment by mikehardy** [comment]
I'm only aware of one on the documentation I spent some time on quite recently, have you seen it? https://rnfirebase.io/app-check/usage#initialize

The `activate` method is the old deprecated API, which I left in so I didn't create an irritating breaking change for everyone.

`initializeAppCheck` is the new API that takes our new custom provider and supports all the new underlying providers

Your proposed initialization looks great, if you are android only. You'll want a similar iOS block per the documentation (and I recommend `appAttestWithDeviceCheckFallback` as provider for maximum iOS device range compatibility but your project may have different needs).

What exactly would you propose I change in the docs since I have marked activate as deprecated, and only documented initializeAppCheck along with how to use it 🤔

**Comment by bimix** [comment]
> I'm only aware of one on the documentation I spent some time on quite recently, have you seen it? https://rnfirebase.io/app-check/usage#initialize
> 
> The `activate` method is the old [deprecated ](https://github.com/invertase/react-native-firebase/blob/a54d765728a856ac04b06b8898658cc4270d4802/packages/app-check/lib/index.d.ts#L220)API, which I left in so I didn't create an irritating breaking change for everyone.
> 
> `initializeAppCheck` is the new API that takes our new custom provider and supports all the new underlying providers
> 
> Your proposed initialization looks great, if you are android only. You'll want a similar iOS block per the documentation (and I recommend `appAttestWithDeviceCheckFallback` as provider for maximum iOS device range compatibility but your project may have different needs).
> 
> What exactly would you propose I change in the docs since I have [marked activate as deprecated,](https://github.com/invertase/react-native-firebase/blob/a54d765728a856ac04b06b8898658cc4270d4802/packages/app-check/lib/index.d.ts#L220) and only documented initializeAppCheck along with how to use it 🤔

usually having a simple example shown in the documentation is the easiest way for everyone to understand how to use it. I would suggest this for all modules not just app check.

**Comment by mikehardy** [comment]
> usually having a simple example shown in the documentation is the easiest way for everyone to understand how to use it. I would suggest this for all modules not just app check.

Right, I have a simple example in there. How did it go when you tried it? If your code is failing, perhaps the example code I have in the documentation will work for you. I took it right from our e2e tests, which work, so it should be functional.

**Comment by bimix** [comment]
> If your code is failing, perhaps the example code I have in the documentation will work for you

ok so I have tried like this and it fails initializing app check:

```
         const rnfbProvider = await firebaseAppCheck.newReactNativeFirebaseAppCheckProvider();
         rnfbProvider.configure({
            android: {
               provider: __DEV__ ? 'debug' : 'playIntegrity',
               debugToken: 'a07b3e55-4cc3-414f-a498-dfgdfgddf',
            },
         });

         firebaseAppCheck.initializeAppCheck(rnfbProvider); // it fails here
```
 
I have also tried like this:
`firebaseAppCheck.initializeAppCheck({ provider: rnfbProvider }); ` // rnfbProvider  is the instance of newReactNativeFirebaseAppCheckProvider

**Comment by bimix** [comment]
> > usually having a simple example shown in the documentation is the easiest way for everyone to understand how to use it. I would suggest this for all modules not just app check.
> 
> Right, I have a simple example in there. How did it go when you tried it? If your code is failing, perhaps the example code I have in the documentation will work for you. I took it right from our e2e tests, which work, so it should be functional.

I managed to get it working by adding the refresh token flag inside the object. 
Btw there are plenty of broken links to documentation in the rnfirebase.io such as this one [](https://firebase.google.com/docs/emulator-suite)
I was trying to read how to set security rules for localhost firestore and I clicked on the link shown here [](https://firebase.google.com/docs/emulator-suite) but it's broken. I have noticed in many cases it is like that.
Also, why there aren't more emulators but only Functions and Firestore? What about Storage and Authentication? At least you haven't mentioned them there.

**Comment by wortkotze** [comment]
> > > usually having a simple example shown in the documentation is the easiest way for everyone to understand how to use it. I would suggest this for all modules not just app check.
> > 
> > 
> > Right, I have a simple example in there. How did it go when you tried it? If your code is failing, perhaps the example code I have in the documentation will work for you. I took it right from our e2e tests, which work, so it should be functional.
> 
> I managed to get it working by adding the refresh token flag inside the object. Btw there are plenty of broken links to documentation in the rnfirebase.io such as this one I was trying to read how to set security rules for localhost firestore and I clicked on the link shown here but it's broken. I have noticed in many cases it is like that. Also, why there aren't more emulators but only Functions and Firestore? What about Storage and Authentication? At least you haven't mentioned them there.

Can you please share your complete working example ? Thx for the help

**Comment by bimix** [comment]
> > > > usually having a simple example shown in the documentation is the easiest way for everyone to understand how to use it. I would suggest this for all modules not just app check.
> > > 
> > > 
> > > Right, I have a simple example in there. How did it go when you tried it? If your code is failing, perhaps the example code I have in the documentation will work for you. I took it right from our e2e tests, which work, so it should be functional.
> > 
> > 
> > I managed to get it working by adding the refresh token flag inside the object. Btw there are plenty of broken links to documentation in the rnfirebase.io such as this one I was trying to read how to set security rules for localhost firestore and I clicked on the link shown here but it's broken. I have noticed in many cases it is like that. Also, why there aren't more emulators but only Functions and Firestore? What about Storage and Authentication? At least you haven't mentioned them there.
> 
> Can you please share your complete working example ? Thx for the help

```
         const rnfbProvider = await firebase.appCheck().newReactNativeFirebaseAppCheckProvider();
         rnfbProvider.configure({
            android: {
               provider: __DEV__ ? 'debug' : 'playIntegrity',
               debugToken: 'a07b3e55-4cc3-23423f-a498-3453sdfdsf',
            },
            apple: {
               provider: __DEV__ ? 'debug' : 'appAttestWithDeviceCheckFallback',
               debugToken: 'some token you have configured for your project firebase web console',
            },
         });

         firebase.appCheck().initializeAppCheck({ provider: rnfbProvider, isTokenAutoRefreshEnabled: true })
            .then((res) => {
               // do something
            }).catch((error) => {
              console.error("app check failed: " + error);
            });
```

**Comment by mikehardy** [comment]
@bimix with respect, our comments here between each other have not been very collaborative. This is an *open source project*. You are not just the user, you are the developer. That's the essence of open source. If you see problems, help - then it gets better for everyone. Provide *specifics*, possibly post PRs, that's how open source works. We're not just a help desk staffed with faceless folks across the internet. We are your fellow developers. You are one of us, making the package better.

> I was trying to read how to set security rules for localhost firestore and I clicked on the link shown here but it's broken. I have noticed in many cases it is like that.

Okay, we can fix those - post the exact URLs here with some info on how to find the links. Or post a PR to the docs (github web UI makes it easy to make a docs PR, give it a shot)

> Also, why there aren't more emulators but only Functions and Firestore? What about Storage and Authentication? At least you haven't mentioned them there.

https://rnfirebase.io/reference/auth#useEmulator
https://rnfirebase.io/reference/storage#useEmulator

Our reference documentation mentions them

You mention, with regard to app check:

> I managed to get it working by adding the refresh token flag inside the object.

What error did you receive without the refresh token flag? It is supposed to be optional, there may be an issue with the code *but I can't know without seeing exactly what you tried and what happened* (https://stackoverflow.com/help/how-to-ask)

For anyone else reading, as mentioned a few times above, our e2e tests contain a full usage example:

https://github.com/invertase/react-native-firebase/blob/a54d765728a856ac04b06b8898658cc4270d4802/packages/app-check/e2e/appcheck.e2e.js#L22-L42

It is basically duplicated verbatim in the documentation - the two code snippets here will work together and are functional as a complete example:

https://rnfirebase.io/app-check/usage#configure-a-custom-provider

**Comment by felipecamposfabel** [comment]
I upgraded Appcheck to version 17.3.0, but after that, I'm unable to use the method `getToken` on iOS Simulator and physical device in debug mode (it was working on prior versions without the debugToken, using -FIRDebugEnabled). Here are the configurations and changes I made after upgrading:

On didFinishLaunchingWithOptions I tried **with and without** the following:

```
#if DEBUG
    FIRAppCheckDebugProviderFactory *providerFactory =
          [[FIRAppCheckDebugProviderFactory alloc] init];
    [FIRAppCheck setAppCheckProviderFactory:providerFactory];
  #endif
```

I removed the `-FIRDebugEnabled` flag from my scheme.

I generated a Debug Token on my firebase web console and started using it here:

```
rnfbProvider.configure({
      android: {
        provider: __DEV__ ? 'debug' : 'playIntegrity',
        debugToken: 'ANDROID_FB_TOKEN'
      },
      apple: {
        provider: __DEV__ ? 'debug' : 'appAttestWithDeviceCheckFallback',
        debugToken: 'IOS_FB_TOKEN',
      },
    });

await firebase.appCheck().initializeAppCheck({ provider: rnfbProvider, isTokenAutoRefreshEnabled: true });
```

I'm getting this error on iOS Simulator:

`-[RNFBAppCheckModule getToken::::]_block_invoke [Line 113] RNFBAppCheck - getToken - Unable to retrieve App Check token: Error`

Also, I noticed on your tests that for the `getToken` test you are not setting the `debugToken` on the provider, but you do when testing the `appCheck()`:

https://github.com/invertase/react-native-firebase/blob/a54d765728a856ac04b06b8898658cc4270d4802/packages/app-check/e2e/appcheck.e2e.js#L134-L151

It is working alright in Release mode. Don't know what I'm missing.

**Comment by bimix** [comment]
@mikehardy  I have been able to follow your examples to set up the app-check in debug mode but for some reason, it fails in production. I am using play integrity for it and I have followed all steps. The only part where I am unsure if it's the correct way to pull the sha256 is by using this command: `gradlew signingReport`. I have then added that sha256 to the firebase console.

**Comment by nixolas1** [comment]
Solved the issue of Play Integrity not working in "production".
It didn't work when creating a production build and installing the apk locally, and neither when uploading bundle to internal app sharing in play store.

It did however work when uploaded to a real Play Store internal testing track, WITH protection enabled.

1:
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/3536134/231447714-6ee2f229-0672-4562-b1d2-2a9602168bed.png">

2:
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/3536134/231447749-4d65155c-9b53-46f4-9f67-04e5ee4f289d.png">

**Comment by bimix** [comment]
> Solved the issue of Play Integrity not working in "production". It didn't work when creating a production build and installing the apk locally, and neither when uploading bundle to internal app sharing in play store.
> 
> It did however work when uploaded to a real Play Store internal testing track, WITH protection enabled.
> 
> 1: <img alt="image" width="1476" src="https://user-images.githubusercontent.com/3536134/231447714-6ee2f229-0672-4562-b1d2-2a9602168bed.png">
> 
> 2: <img alt="image" width="1338" src="https://user-images.githubusercontent.com/3536134/231447749-4d65155c-9b53-46f4-9f67-04e5ee4f289d.png">

thanks for this! However, how do you test the production app before releasing it if the app-check is not working? If I generate an apk to test it, appcheck fails. I dont want to release it without testing locally first.

**Comment by talaikis** [comment]
@bimix Thank your for the working example. Documentation is really insane.

**Comment by mikehardy** [comment]
Happy to integrate any docs PR if someone proposes one to clarify anything - there's an edit button on top right of all pages on rnfirebase.io and the github web UI for text PRs is really quick to go through and add a note
