### ISSUE TITLE
[🐛] App crash on android in react-native 0.71.2 

### ISSUE THREAD

**Issue by tahaAlgoace** [invertase/react-native-firebase#6888]
## Issue

I create a new project when I place the apply plugin: 'com.google.gms.google-services'  in android/app/build.gradle my app is automatically crash and when I remove this the new error is shown No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()

**Comment by tahaAlgoace** [comment]
when I place the apply plugin: 'com.google.gms.google-services' in android/app/build.gradle my app is crash on android and I follow every step that mentioned in your documentation

**Comment by mikehardy** [comment]
> when I place the apply plugin: 'com.google.gms.google-services' in android/app/build.gradle my app is crash on android and I follow every step that mentioned in your documentation

That is an *assertion*, not backed by any evidence in your information-lite issue, and your assertion is contradicted by the scripted minimal reproduction I have provided you.

Continuing to comment without evidence is not productive. I strongly suggest you look at the script, open up rnfirebase.io's install guide, and restart

**Comment by mikehardy** [comment]
(by the way, my guess? https://rnfirebase.io/#generating-android-credentials --> "Download the google-services.json file and place it inside of your project....")

**Comment by tahaAlgoace** [comment]
I'm doing the same thing what is mentioned in documentation and also I have google-services.json My app is running on ios but on android the app is crashed when I place the apply plugin: 'com.google.gms.google-services' in android/app/build.gradle

**Comment by mikehardy** [comment]
If you assert there is an app crash, the required minimum piece of information to provide as evidence of your assertion is the stack trace from `adb logcat`. A secondary required piece of evidence is the version information that specifies the software in use, along with the execution environment.

I will reiterate: you provide no evidence or information that would normally be needed to access help.

I propose you open this issue in your browser, and you pretend that you are me and I am you. I am asking you the question here about my crash, and providing you no information. How do you respond? How can you provide help? :thinking:

**Comment by chirag773** [comment]
> when I place the apply plugin: 'com.google.gms.google-services' in android/app/build.gradle my app is crash on android and I follow every step that mentioned in your documentation

how you solved this? i am getting the same

**Comment by mikehardy** [comment]
@chirag773 "My app crashes" but no actual native crash trace is not a valid request for help.
If your app is crashing you *must* examine the native logs and find the crash trace. Include that in your request for help and people have the information they need to actually help

**Comment by kundanthe** [comment]
I am also facing same issue ?

**Comment by mikehardy** [comment]
I have no reproduction locally https://stackoverflow.com/help/minimal-reproducible-example / https://stackoverflow.com/help/how-to-ask

I can only investigate and fix things that are reproducible, sorry

**Comment by sfase3** [comment]
@kundanthe , @chirag773 , @tahaAlgoace , @andymatuschak hello, has anyone found a solution? Facing the same issue with crashing app without any errors after applying google service plugin. On IOS everything works fine.

**Comment by kundanthe** [comment]
Hi @sfase3 

I was getting this error because Firebase was not initializing automatically, open-tok libraries were restricting it.
Please check may be other libraries creating problem for you.
