### ISSUE TITLE
Installing Database module causes build failure

### ISSUE THREAD

**Issue by Benjamin-Dewey** [invertase/react-native-firebase#689]
### Issue

I have my iOS build working with `'Firebase/Core'`, `'Firebase/Auth'`, and `'Google/SignIn'` modules. No issues. However when I add `pod 'Firebase/Database'` to my podfile and `pod update` just like what the install docs say things go wrong. Running `react-native run-ios` finishes with

```
** BUILD FAILED **



The following build commands failed:
	CompileC /Users/benjamindewey/Desktop/Development/temp/Trackdown/ios/build/Build/Intermediates.noindex/RNFirebase.build/Debug-iphonesimulator/RNFirebase.build/Objects-normal/x86_64/RNFirebase.o RNFirebase/RNFirebase.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

Although the app still gets up and running on the simulator, trying to call `firebase.database()` logs out an error saying that the database module is not installed. Also if I remove `pod 'Firebase/Database'` and run `pod update` again and `react-native run-ios` I get the same build failure as before. It seems that trying to install the database module has contaminated things.

**Podfile**
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Trackdown' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Trackdown
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Google/SignIn'

  target 'TrackdownTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Trackdown-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Trackdown-tvOS

  target 'Trackdown-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

**Podfile.lock**
```
PODS:
  - Firebase/Auth (3.17.0):
    - Firebase/Core
    - FirebaseAuth (= 3.1.1)
  - Firebase/Core (3.17.0):
    - FirebaseAnalytics (= 3.9.0)
    - FirebaseCore (= 3.6.0)
  - Firebase/Database (3.17.0):
    - Firebase/Core
    - FirebaseDatabase (= 3.1.2)
  - FirebaseAnalytics (3.9.0):
    - FirebaseCore (~> 3.6)
    - FirebaseInstanceID (~> 1.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseAuth (3.1.1):
    - FirebaseAnalytics (~> 3.7)
    - GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseCore (3.6.0):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseDatabase (3.1.2):
    - FirebaseAnalytics (~> 3.7)
  - FirebaseInstanceID (1.0.10):
    - FirebaseCore (~> 3.6)
  - Google/Core (3.1.0):
    - FirebaseAnalytics (~> 3.2)
  - Google/SignIn (3.1.0):
    - Google/Core
    - GoogleSignIn (~> 4.0)
  - GoogleSignIn (4.1.1):
    - GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)
    - GoogleToolboxForMac/NSString+URLArguments (~> 2.1)
    - GTMOAuth2 (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleToolboxForMac/DebugUtils (2.1.3):
    - GoogleToolboxForMac/Defines (= 2.1.3)
  - GoogleToolboxForMac/Defines (2.1.3)
  - GoogleToolboxForMac/NSData+zlib (2.1.3):
    - GoogleToolboxForMac/Defines (= 2.1.3)
  - GoogleToolboxForMac/NSDictionary+URLArguments (2.1.3):
    - GoogleToolboxForMac/DebugUtils (= 2.1.3)
    - GoogleToolboxForMac/Defines (= 2.1.3)
    - GoogleToolboxForMac/NSString+URLArguments (= 2.1.3)
  - GoogleToolboxForMac/NSString+URLArguments (2.1.3)
  - GTMOAuth2 (1.1.6):
    - GTMSessionFetcher (~> 1.1)
  - GTMSessionFetcher (1.1.12):
    - GTMSessionFetcher/Full (= 1.1.12)
  - GTMSessionFetcher/Core (1.1.12)
  - GTMSessionFetcher/Full (1.1.12):
    - GTMSessionFetcher/Core (= 1.1.12)

DEPENDENCIES:
  - Firebase/Auth
  - Firebase/Core
  - Firebase/Database
  - Google/SignIn

SPEC CHECKSUMS:
  Firebase: 4b66b5b59c43edac745b87f0c87e42cdd0279c13
  FirebaseAnalytics: e5fe8486efc01bec33f6bf82e2fa9fce4b124052
  FirebaseAuth: cc8a1824170adbd351edb7f994490a3fb5c18be6
  FirebaseCore: 9691ee2ade70c098d7cf92440f4303f16d83ca75
  FirebaseDatabase: 05c96d7b43a7368dc91c07791adb49683e1738d1
  FirebaseInstanceID: b9eedd6846fb5e1f0f7279e1deaa7a7e4cf8392e
  Google: 98da4b1a60ed0beb80a290387a28333406a1eb90
  GoogleSignIn: 3fdaa34a2ba04dbd7a25d7db39aecb0da98d5bdc
  GoogleToolboxForMac: 2501e2ad72a52eb3dfe7bd9aee7dad11b858bd20
  GTMOAuth2: c77fe325e4acd453837e72d91e3b5f13116857b2
  GTMSessionFetcher: ebaa1f79a5366922c1735f1566901f50beba23b7

PODFILE CHECKSUM: 0f45f287213131c236fbc400114cd3a4a735af6b

COCOAPODS: 1.3.1

```

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS High Sierra

4. React Native version: 0.51.0

5. RNFirebase Version: 3.1.1

6. Firebase Module: core, auth, database

**Comment by Ehesp** [comment]
Some of those Pods look quite out of date, the Firebase/Database one is 4.3.0 I believe - does your `pod outdated` not flag this?

**Comment by Benjamin-Dewey** [comment]
Running `pod outdated` gives me this

```
Analyzing dependencies
The following pod updates are available:
- Firebase 3.17.0 -> (unused) (latest version 4.7.0)
- FirebaseAnalytics 3.9.0 -> 3.9.0 (latest version 4.0.5)
- FirebaseAuth 3.1.1 -> 3.1.1 (latest version 4.4.0)
- FirebaseCore 3.6.0 -> 3.6.0 (latest version 4.0.12)
- FirebaseDatabase 3.1.2 -> 3.1.2 (latest version 4.1.2)
- FirebaseInstanceID 1.0.10 -> 1.0.10 (latest version 2.0.7)
The following pods are deprecated:
- Google
```

Running `pod update` updates nothing. Reinstalling cocoapods according to the instructions [here](https://stackoverflow.com/questions/34509310/cocoapods-pod-update-installs-old-pods) and trying again still does not get me the latest versions of the pods.

**Comment by chrisbianca** [comment]
@Benjamin-Dewey You need to change your `Google/SignIn` pod to just `GoogleSignIn` - this is a newer pod which doesn't force older versions of Firebase to be downloaded.

**Comment by akobylianskyi** [comment]
I have the same problem with integrating react-native-google-signin and react-native-firebase in my project. Everything was ok before I add cocoapods with firebase dependencies. react-native-google-signin module was added manually before and after adding firebase with pods iOS project started failing. After that I tried to add google-signin module using pods but the problem were not solved. I have noticed that react-native-google-signin uses old versions of the Firebase. Adding GoogleSignIn pod instead of Google/SignIn should solve that but google-signin module is not working after such replacement. I understand that the problem is more related to google-signin module but in the react-native-firebase documentation we have recommendation to use it. Maybe someone could help me to solve this problem.

**Comment by akobylianskyi** [comment]
@Benjamin-Dewey Any news about your progress with that issue?

**Comment by Benjamin-Dewey** [comment]
@akobylianskyi I was able to get things to work by doing the following:
1. Installation of `react-native-firebase` on iOS and Android following the instructions in the docs just like normal.
2. Installation of `react-native-google-signin` on Android described [here](https://github.com/devfd/react-native-google-signin/blob/master/android-guide.md).
2. **Manual** installation of `react-native-google-signin` on iOS described [here](https://github.com/devfd/react-native-google-signin/blob/master/ios-guide.md#manual). If the instructions are not so clear you can follow along with this [video](https://www.youtube.com/watch?v=sT3hcMsRF68). I also used the 4.0.0 version of the Google SignIn SDK because  of this issue [here](https://github.com/devfd/react-native-google-signin/issues/305).
