### ISSUE TITLE
Ios Background Message Handler doesn't work with firebase console message

### ISSUE THREAD

**Issue by ahmedelsayed11** [invertase/react-native-firebase#6896]
### What i am facing?
I need to save the incoming notifications locally in an offline database and notification will be send from firebase console not from the sdk or postman. 
The issue is the `setBackgroundMessageHandler` doesn't work when the app in the background or killed.
Note, i managed to make it work when sending a message from postman and here is my body:
`{
  "message": {
    "apns": {
      "payload": {
        "aps": {
          "content-available": 1
        },
        "acme1": "bar",
        "acme2": "42"
      },
      "headers": {
        "apns-priority": "5"
      }
    },
    "token":"<your-token>",
    "notification": {
      "title": "Mumbai vs Pune finals",
      "body": "Watch the match online now"
    },
    "data":{
      "notificationType":"offer"
    }
  }
}`

**Comment by mikehardy** [comment]
Your goals are not achievable, you won't be able to accomplish this with the console I don't think.
Plan on using firebase functions and the firebase-admin-sdk in combination with device tokens.

**Comment by mingyeom1** [comment]
me too. please save me!!!
