### ISSUE TITLE
Create user with instagram tokens

### ISSUE THREAD

**Issue by QQizi** [invertase/react-native-firebase#690]
### Issue

I'm building an app which involve Instagram authentification.
I tried to follow this tutorial : [link](https://firebase.googleblog.com/2016/10/authenticate-your-firebase-users-with.html)
But the method createCustomToken() is not available in react-native-firebase.
How could i manage to create an account in Firebase based on the user Instagram's token or id ?

### Environment

1. Application Target Platform: IOS

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode 9.1

4. React Native version:  0.50.3

5. RNFirebase Version: 3.1.1

6. Firebase Module: auth

**Comment by chrisbianca** [comment]
@QQizi `createCustomToken` is only available in the admin SDKs (https://firebase.google.com/docs/reference/node/firebase.auth.Auth#createCustomToken) - you'll need to send the details to a server (or a firebase cloud function) and create the token there.
