### ISSUE TITLE
[🐛] Auth fails silently, no stack trace from `signInWithEmailAndPassword` 

### ISSUE THREAD

**Issue by MorenoMdz** [invertase/react-native-firebase#6900]
## Issue

Our app is having problems authenticating in our production environment, it worked fine with the same credentials when using FB web SDK and it works fine in our dev environment. The sign call throws but no error is returned, making it very hard to diagnose what the problem actually is.

---

### Javascript

```js
 const handleLogin = async (email: string, password: string) => {
   // this is a test call to confirm Firestore calls from rn-firebase work and this does successfully run
    try {
      const ref = await firebase
        .firestore()
        .collection('system')
        .doc('settings')
        .get()
      const settings = ref.data()
      alert(`DATA ${JSON.stringify(settings, null, 2)}`)

      const { user } = await auth.signInWithEmailAndPassword(email, password)

    } catch (error) {
      // these both return undefined
      alert(JSON.stringify(error, null, 2)) 
      alert(error)
    }
    dispatchSignUpProfile({ type: 'CLEAR' }) // Clear any previous sign up information upon successful login
  }
```
</details>

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `17.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Auth`
- **Are you using `TypeScript`?**
  - `Y 4.6.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
🤔 missing large parts of the issue template here.
No mention of what platform and execution environment you see it
No mention of what `adb logcat` or iOS (depending) logs show
No evidence of the actual error message or anything

Based on information provided I could jokingly say "it's sunspots" and be as near correct as I can guess

**Comment by MorenoMdz** [comment]
> Based on information provided I could jokingly say "it's sunspots" and be as near correct as I can guess

Basically, that method call from the Auth package throws an empty error, we identified that the problem causing it to not work in prod was that the API key didn't have Identity toolkit access and could reproduce it reliably now, and fix it ofc, the point of this bug issue is that we assumed the auth package would properly return an error but all we have is `Error: [auth/internal-error] An internal error has occurred, please try again.` .

As for the template yes it definitely is missing data as we simply do not have more to share.

Going to close this issue with a small TLDR that might be helpful for others in the future, if your Auth is failing with no obvious reasons and the other Firebase packages seem to work, double check your API key has the correct permissions at 
https://console.cloud.google.com/apis/credentials/key 👍

**Comment by MorenoMdz** [comment]
Btw thanks for the quicky response @mikehardy , it is impressive how you can respond fast considering so many repositories you work on haha
