### ISSUE TITLE
[🐛] Dynamic link opening Play Store instead of Installed app

### ISSUE THREAD

**Issue by ajaykumar97** [invertase/react-native-firebase#6901]
## Issue

Dynamic link is not opening the installed mobile app. It opens the Play Store instead. I have a button on my website on click of which, I want to open my app. For this, I am opening a dynamic link on click of that button on my website. When I click on the button, in some web browsers, the dynamic link is redirecting to Google Play store app(with my app on the Play Store) and in some browsers, opening Play Store website(with my app on the Play Store) inside the browser. However, when I send that dynamic link in the chat apps like Whatsapp and click on that link from the chat, then its opening my installed application.

I have gone through several issues and stackoverflow questions, but could not find any solution for it.

---

### Javascript

<details><summary>Click To Expand</summary>
<p> On mobile side, I only have dynamic link listeners setup as we are generating the dynamic link on the backend side.</p>

##### Mobile
```
useEffect(() => {
    getInitialDynamicLink();
    const unsubscribe = dynamicLinks().onLink(handleDynamicLink);
    return () => unsubscribe();
  }, []);

const handleDynamicLink = link => {
  if (link?.url) {
    console.log('shared url is: ', link?.url);
  }
};

const getInitialDynamicLink = () => {
    dynamicLinks()
      .getInitialLink()
      .then(link => {
        handleDynamicLink(link);
      });
  };
```

##### Backend
On the backend, I am using https://www.npmjs.com/package/firebase-dynamic-links/v/1.0.0 to generate dynamic links.

![image](https://user-images.githubusercontent.com/38132295/218018097-262006ea-a203-4253-b03d-71c61ee123b7.png)

#### `package.json`:

```json
"@react-native-firebase/app": "^16.4.0",
"@react-native-firebase/dynamic-links": "^16.4.0",
"react-native": "0.67.4",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby

```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        ndkVersion = "21.4.7075529"
        kotlin_version = "1.4.0"
        googlePlayServicesAuthVersion = "19.2.0"
    }
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<intent-filter android:autoVerify="true">
            <action android:name="android.intent.action.VIEW"/>
            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <data android:host="appname.page.link" android:scheme="https"/>
</intent-filter>
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `16.4.0`
- **`Firebase` module(s) you're using that has the issue:**
  - @react-native-firebase/app
  - @react-native-firebase/auth
  - @react-native-firebase/crashlytics
  - @react-native-firebase/dynamic-links
  - @react-native-firebase/messaging
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I don't believe this is within the control of react-native-firebase, I believe it is at a lower level and involves an interaction between firebase-android-sdk, Android devices in general (with https://developer.android.com/training/app-links) and the firebase backend, I suggest re-doubling efforts on stackoverflow to find resolution with the firebase team (who does - or should - respond there if an issue is tagged up correctly)
