### ISSUE TITLE
[🐛] Android and iOS .getInitialNotification() method not called when app is killed and opened again.

### ISSUE THREAD

**Issue by rajesh57** [invertase/react-native-firebase#6902]
## Issue

Android and iOS .getInitialNotification() method not called when app is killed and opened again.

Describe your issue here

I'm using FCM to get the push notificaion and I want to do the deeplink based on the notification payload. Followed the below documentation.

https://rnfirebase.io/messaging/notifications

When app is killed/ quite  state and click on the notificaiton getInitialNotification() not called. **I'm not using any splash screen library.**

package version:
    "@react-native-firebase/messaging": "^16.5.0",

```
 messaging()
        .getInitialNotification()
        .then((remoteMessage) => {
          if (remoteMessage) {
            console.log(remoteMessage.notification);
          }
        });

```

Please assist me to resolve this issue.

Thanks in Advance. 

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
        <activity
          android:name=".MainActivity"
          android:launchMode="singleTask"
          android:label="@string/app_name"
          android:configChanges="keyboard|keyboardHidden|orientation|screenSize|layoutDirection|locale"
          android:windowSoftInputMode="adjustResize"
          android:exported="true">
          <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
          </intent-filter>
         <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
          </intent-filter>
        </activity>
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [X] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by codal-mpawar** [comment]
@mikehardy Getting the same issue can you please help me with this?

**Comment by codal-mpawar** [comment]
```javascript
{
    "react-native": {
        "crashlytics_debug_enabled": false,
        "crashlytics_disable_auto_disabler": true,
        "crashlytics_auto_collection_enabled": true,
        "crashlytics_is_error_generation_on_js_crash_enabled": true,
        "crashlytics_javascript_exception_handler_chaining_enabled": true,
        "analytics_auto_collection_enabled": true
    }
}

```

**Comment by mikehardy** [comment]
Have you tried it with up to date software? This version of react-native is out of support in general:

>  "react-native": "0.64.2"

https://github.com/reactwg/react-native-releases#releases-support-policy

It is old enough, it could be the source of the problem.
