### ISSUE TITLE
[🐛] Dynamic Link with minimumVersion not working 

### ISSUE THREAD

**Issue by byyoungjin** [invertase/react-native-firebase#6904]
## Issue
---
I'm using `dynamicLinks().buildShortLink`. The minimumVersion parameter seems not working.
It just redirect to the lower version app. not the app store, both IOS & Android

### Javascript

<details><summary>Click To Expand</summary>
<p>

here is my buildShortLink code 
current version is '22' for android, and '1.1.0' for ios ( buildnumber 23 for ios, and buildnumber also not work on ios ) 

```js
export const buildShortLink = async ({ path }) => {
  const bundleIdentifier = VersionInfo.bundleIdentifier;

  console.log("minimum: 1.1.1");
  const shortLink = await dynamicLinks().buildShortLink(
    {
      link: `https://pclip.app/${path}`,
      domainUriPrefix: domainUriPrefixMap[bundleIdentifier],
      android: {
        packageName: bundleIdentifier,
        fallbackUrl: storeUrls.android,
        // minimumVersion: "22",
        minimumVersion: "23",
      },
      ios: {
        appStoreId: "6443961036",
        bundleId: bundleIdentifier,
        fallbackUrl: storeUrls.ios,
        // minimumVersion: "1.1.0",
        minimumVersion: "1.1.1",
      },
    },
    firebase.dynamicLinks.ShortLinkType.SHORT
  );

  return shortLink;
};
```

#### `package.json`:

```json
 "@react-native-firebase/app": "^15.4.0",
    "@react-native-firebase/auth": "^15.4.0",
    "@react-native-firebase/dynamic-links": "^15.4.0",
    "@react-native-firebase/firestore": "^15.4.0",
    "@react-native-firebase/functions": "^15.4.0",
    "@react-native-firebase/messaging": "^15.4.0",
    "@react-native-firebase/storage": "^15.4.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
$RNFirebaseAsStaticFramework = true

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

require 'json'

podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}
platform :ios, podfile_properties['ios.deploymentTarget'] || '12.4'
install! 'cocoapods',
  :deterministic_uuids => false

def shared_pods 
  podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}
  use_expo_modules!
  config = use_native_modules!
  use_frameworks!
  # use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled] || podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Dir.pwd}/.."
  )

  # Uncomment to opt-in to using Flipper
  # Note that if you have use_frameworks! enabled, Flipper will not work
  #
  # if !ENV['CI']
  #   use_flipper!()
  # end

 
end 

target 'bok' do
  shared_pods
end
target 'bok-staged' do
  shared_pods
end
target 'bok-development' do
  shared_pods
end


post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

post_integrate do |installer|
  begin
    expo_patch_react_imports!(installer)
  rescue => e
    Pod::UI.warn e
  end
end
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! Can you verify this continues to happen on current versions? You've logged an issue on old versions:

```
 "@react-native-firebase/app": "^15.4.0",
    "@react-native-firebase/auth": "^15.4.0",
    "@react-native-firebase/dynamic-links": "^15.4.0",
    "@react-native-firebase/firestore": "^15.4.0",
    "@react-native-firebase/functions": "^15.4.0",
    "@react-native-firebase/messaging": "^15.4.0",
    "@react-native-firebase/storage": "^15.4.0",
```

Can you check the flowchart produced when you paste the dynamic link into a browser with `?d=1` on it (https://firebase.google.com/docs/dynamic-links/debug)

Can you explain *exactly*, in technical terms what this means?

> It just redirect to the lower version app. not the app store, both IOS & Android
