### ISSUE TITLE
[🐛] [IOS] onNotificationOpenedApp and getInitialNotification not working, But onMessage is work fine 

### ISSUE THREAD

**Issue by Poovit-B** [invertase/react-native-firebase#6915]
## Issue
 I'm having an issue with receiving replies for onNotificationOpenedApp, getInitialNotification, and getInitialNotification. I am able to receive the normal badge and onMessage, but these other notifications seem to be missing. Interestingly, everything seems to be working properly on Android.

Any ideas on how to fix this issue?

```
 const subscribeNotificationMessage = () => {
    // 2. Action when got FCM while user is using application
    messaging().onMessage(async (remoteMessage) => {
      console.log('New FCM message arrived!', JSON.stringify(remoteMessage, null, 2));

    });

    // 3. Action when click from OS Notification, while App was OPENED
    messaging().onNotificationOpenedApp(remoteMessage => {
      console.log('Notification Open from background state:', JSON.stringify(remoteMessage, null, 2));
      handleOpenNotification(remoteMessage);
    });


  }

  const handleCheckNotification = async () => {
    messaging()
      .getInitialNotification()
      .then((remoteMessage) => {
        if (remoteMessage) {
          handleOpenNotification(remoteMessage)
        } else {
          Linking.getInitialURL()
            .then((initialURL) => {
              if (initialURL) {
                handleOpenDeepLink(initialURL)
              }
            })
            .catch(console.error)
        }
      })
      .catch((e) => console.log('err', e))
  }


messaging().setBackgroundMessageHandler(async remoteMessage => {
    console.log('Message handled in the background!', JSON.stringify(remoteMessage, null, 2));
});

```
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "react-native": "0.70.6",
    "@react-native-firebase/analytics": "^16.7.0",
    "@react-native-firebase/app": "^16.7.0",
    "@react-native-firebase/messaging": "^16.7.0",
    "@react-navigation/native": "^6.1.3",
    "@react-navigation/stack": "^6.3.5",
    "react-native-screens": "^3.19.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^16.7.0`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by alex-dosa92** [comment]
Are you using the Notifee package? If yes that is the reason.

**Comment by ttdatt** [comment]
> 

I'm having this problem too. Is there any way to use notifee with react-native-firebase?

**Comment by mikehardy** [comment]
The simple answer to your questino @ttdatt is, yes there is. My project does for instance. I expect you need more specific information though. The example above is not complete (is that from index.js? It should be if it is setting the background handler. Or is from app.js? It is also doing some App-type work... 🤔 ) so I can't puzzle out what could be wrong.

**Comment by emzet93** [comment]
That's interesting. I'm facing exactly the same issue. I'm using both firebase messaging and notifee. Main purpose of using notifee was to show notification buble in `messaging().onMessage()` listener when the app is in foreground and handle buble press.
Everything was working ok, besides `getInitialNotification` always returning null and `onNotificationOpenedApp` never being called. When I removed notifee it started to work as expected.

Any ideas why those to libs have conflict and how to workaround it?

Initially I was calling `getInitialNotification` and `onNotificationOpenedApp` in linking config from react-navigation:
https://reactnavigation.org/docs/deep-linking/#third-party-integrations

However I was also trying to call them in other places and none was working when `notifee` was installed

**Comment by Bardiamist** [comment]
I don't use notifee. I noticed that in my app `getInitialNotification` and `onNotificationOpenedApp` doesn't work on Android. Not sure how long. It works on iOS. Tested on react-native-firebase 16.5.0, 17.3.2 and 17.4.2

**Comment by uguraktas** [comment]
> Are you using the Notifee package? If yes that is the reason.


What exactly is the reason for this method not working with Notifee? Give more details please

**Comment by nic-rod** [comment]
The fact that this is undocumented anywhere besides this issue and buried patch notes seems pretty unreasonable. Notifee  is recommended for usage by the ReactNativeFirebase library, and vice versa, and nowhere does it state that the handlers in ReactNativeFirebase will no longer work when used with Notifee. Feels like I just wasted hours debugging this extremely frustrating issue.

**Comment by vergsparda** [comment]
> The fact that this is undocumented anywhere besides this issue and buried patch notes seems pretty unreasonable. Notifee is recommended for usage by the ReactNativeFirebase library, and vice versa, and nowhere does it state that the handlers in ReactNativeFirebase will no longer work when used with Notifee. Feels like I just wasted hours debugging this extremely frustrating issue.

same problem, i tried to fix this for a week

**Comment by faker007** [comment]
> Are you using the Notifee package? If yes that is the reason.

Oh... Thats the correct way to fix the problem.

Confirmed under
```
iOS 17.0
react-native": "0.72.3
@react-native-firebase/messaging": "18.5.0"
react-native-push-notification": "8.1.1",
```

**Comment by BLOCKMATERIAL** [comment]
oohhh srsly
if you install notifee listeners for handling background notification does'nt work
relesolved issue uninstall notifee

**Comment by NenadoPL1Z** [comment]
I managed to get it to work like this:

```
  //? SERVICES
  const {
    handleOpenInitialNotification,
    listenMessageEvent,
    listenForegroundEvent,
  } = useNotificationEventServices();

  useEffect(() => {
    notifee.getInitialNotification().then(handleOpenInitialNotification);

    const onMessage = messaging().onMessage(listenMessageEvent);

    const onForegroundEvent = notifee.onForegroundEvent(listenForegroundEvent);

    //? unsubscribe
    return () => {
      onMessage();
      onForegroundEvent();
    };
  }, []);
```

**Comment by NenadoPL1Z** [comment]
```
import { Linking } from "react-native";
import type { InitialNotification } from "@notifee/react-native";
import notifee from "@notifee/react-native";
import type {
  Event,
  EventDetail,
} from "@notifee/react-native/src/types/Notification";
import { EventType } from "@notifee/react-native/src/types/Notification";
import type { FirebaseMessagingTypes } from "@react-native-firebase/messaging";

import { IS_IOS, SCHEME_URL_APP } from "@app/lib/constants/constants";
import type { Nullable } from "@app/types/types";

type Initial = Nullable<InitialNotification>;
type MessageEvent = FirebaseMessagingTypes.RemoteMessage;
type ForegroundEvent = Event;
type NotificationCustomData = Nullable<{ click_action: string }>;

export const useNotificationEventServices = () => {
  const handleOpenInitialNotification = (notification: Initial) => {
    return notification;
  };

  const listenMessageEvent = async (message: MessageEvent) => {
    if (IS_IOS) {
      return;
    }

    const channelId = await notifee.createChannel({
      id: "default",
      name: "Default Channel",
    });

    // Display a notification
    await notifee.displayNotification({
      title: message.notification?.title,
      body: message.notification?.body,
      android: {
        channelId,
      },
    });
  };

  const listenForegroundEvent = async (event: ForegroundEvent) => {
    const { type, detail } = event;

    switch (type) {
      case EventType.PRESS:
        notificationOpen(detail);
    }
  };

  return {
    handleOpenInitialNotification,
    listenMessageEvent,
    listenForegroundEvent,
  };
};

const notificationOpen = (remoteMessage: EventDetail) => {
  const notificationData = remoteMessage.notification?.data;
  if (!notificationData) return;

  const customData = notificationData?.custom_data as NotificationCustomData;
  if (!customData) return;

  const clickAction = (customData || {})?.click_action;
  if (!clickAction) return;

  Linking.openURL(`${SCHEME_URL_APP}${clickAction}`).finally();
};

```

**Comment by armenasatryan9603** [comment]
> Are you using the Notifee package? If yes that is the reason.

you saved my life too :D

**Comment by usman965** [comment]
was facing same issue. i was using @react-native-firebase/messaging and notifee library. this notifee latest version causing issue on causing issue on ios on calling getInitialNotification and onNotificationOpenedApp as these events are handled by it as in docs https://rnfirebase.io/messaging/usage. just downgrade notifee version to ^5.7.0 or remove it if not necessary. just solve problem

**Comment by CostasCF** [comment]
This is a serious issue as I have spent hours debugging the reason why the background handlers from Firebase weren't working. Downgrading to notifee@6.0.0 as someone else mentioned seems to have fixed the above issue, however, it may have created other side effects (are triggers still functioning as expected?) that we need to investigate.

**Comment by erenkulaksiz** [comment]
Hello, i removed react-native-push-notification library and now onNotificationOpenedApp works but i cant make getInitialNotification work. I also use expo-splash-screen.
