### ISSUE TITLE
Snyk Security vulnerability issues on  @xmldom/xmldom

### ISSUE THREAD

**Issue by mahesh7325** [invertase/react-native-firebase#6918]
Snyk has identified as a critical security vulnerability on @xmldom/xmldom which is using in this project and they are suggesting to upgrade it for to fix it.

Introduced through
@react-native-firebase/app@14.3.0 and @react-native-firebase/crashlytics@14.3.0
Fixed in
@xmldom/xmldom@0.7.7, @0.8.4, @0.9.0-beta.4

**Comment by mikehardy** [comment]
Please do not log issues against old software, v14 is not current.
