### ISSUE TITLE
Snyk Vulnerability issue on @xmldom/xmldom

### ISSUE THREAD

**Issue by mahesh7325** [invertase/react-native-firebase#6919]
Snyk has identified as a critical security vulnerability on @xmldom/xmldom which is using in this project and they are suggesting to upgrade it for to fix it.

Introduced through
@react-native-firebase/app@14.3.0 and @react-native-firebase/crashlytics@14.3.0
Fixed in
@xmldom/xmldom@0.7.7, @0.8.4, @0.9.0-beta.4

**Comment by mikehardy** [comment]
Please do not log duplicate issues, #6918, it is an inefficient use of time.

In any case, please show in the package.json for the modules you cite where we depend on xmldom:

https://github.com/invertase/react-native-firebase/blob/main/packages/app/package.json
https://github.com/invertase/react-native-firebase/blob/main/packages/crashlytics/package.json

You'll notice they are not there.

Automated tools are interesting, but it is the responsibility of the user to validate results + filter false positives

**Comment by mahesh7325** [comment]
Yes you are correct. Sorry for the confusion
