### ISSUE TITLE
[🐛]Firebase Crashlytics not working on ios

### ISSUE THREAD

**Issue by hllibrhm01** [invertase/react-native-firebase#6922]
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 96.17 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/his/.rvm/gems/ruby-3.1.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.3 => 0.71.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Error text : 
/Users/his/Desktop/react-native/Trial/ios/Pods/Headers/Public/glog/glog/logging.h:512:1 Import of module 'glog.glog.log_severity' appears within namespace 'google'

This error is coming in XCode while running smoothly on android side.

**Comment by mikehardy** [comment]
Hi there! Unfortunately you've deleted our template, so I can't deduce what went wrong or where.

Here's a build of crashlytics working on iOS though, if you read the script you can see how I integrate everything as it is fully automated starting from `npx react-native init` - https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
