### ISSUE TITLE
[🐛] How to get FirebaseInAppMessagingClickListener for React Native

### ISSUE THREAD

**Issue by mayank-paryani** [invertase/react-native-firebase#6946]
Hello All,

I am using React Native Firebase In App Messaging library and it is working fine.
The issue is I need a callback when user clicks on the In app message pop up.

In Android native there is an interface available "FirebaseInAppMessagingClickListener" which gives callback, I need a way to get this in React Native.

Can someone please help regarding this.

- **Platform that you're experiencing the issue on**:
  - [ ] Both (iOS & Android)
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 17.3.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g.In App Messaging (17.3.1)`
- **Are you using `TypeScript`?**
  - `N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Spxc** [comment]
Look at their docs...

**Comment by scaralfred** [comment]
Has anyone found a solution to this?
I'd like to catch and save the in-app-message content in the mobile-app.

**Comment by Spxc** [comment]
> Has anyone found a solution to this? I'd like to catch and save the in-app-message content in the mobile-app.
> 
> @mayank-paryani

Highly recommend you to read their docs...
For the lazy ones, you do something like this ex:

```
messaging().onMessage(onMessageReceived);
messaging().onNotificationOpenedApp((notification) => {
})
```

Where `notification` is your FCM object

**Comment by scaralfred** [comment]
> > Has anyone found a solution to this? I'd like to catch and save the in-app-message content in the mobile-app.
> > 
> > @mayank-paryani
> 
> Highly recommend you to read their docs...
> For the lazy ones, you do something like this ex:
> 
> ```
> messaging().onMessage(onMessageReceived);
> messaging().onNotificationOpenedApp((notification) => {
> })
> ```
> 
> Where `notification` is your FCM object

I think the methods you shared refer to "messaging" (push notifications) and not in-app-messaging which is a different firebase tool.

**Comment by buraks** [comment]
@mikehardy I hope you don't mind the mention.

Is in-app-messaging feature used in the wild? I am trying to integrate with it today and it doesn't seem to work, and its further customizations (https://firebase.google.com/docs/in-app-messaging/modify-message-behavior) don't seem to be supported by rnfirebase which made me question whether I should integrate with it or not :)

Thanks in advance!
