### ISSUE TITLE
how can remove notification still receive message

### ISSUE THREAD

**Issue by JayricMok** [invertase/react-native-firebase#695]
I get notification from sender, if I click the notification I will receive the message data when `componentDidMount()`, if I swipe out the notification (remove). I reopen the app, message not receive. 

    componentDidMount(){
      firebase.messaging().getInitialNotification().then((payload) => {
        console.log("Initial Message: ", payload); 
      });
      firebase.messaging().onMessage((payload) =>{
        console.log("Message received. ", payload);
        // ...
      });
    }

**Comment by chrisbianca** [comment]
If I understand you, then you're removing the notification in the iOS or Android display but still expecting that you'll receive the notification when you next open the app?

This just isn't possible as the OS won't tell the app about the notification unless it is tapped to open it.  If you want to still show this in your app, you'll need to implement a store of outstanding notifications in your database and display this in the app.

**Comment by JayricMok** [comment]
@chrisbianca what i want is when sender send the message (app in background), notification does received, but without clicking the notification and just open the app to getting the message from `getInitialNotification` or `onMessage`.

**Comment by chrisbianca** [comment]
@JayricMok I'm afraid that's just not possible and out of our control. The notification is only available in `getInitialNotification` or `onMessage` if the notification was clicked or it was received whilst in the foreground

**Comment by JayricMok** [comment]
@chrisbianca ok, forget the notification. For example, my app go offline, but sender still sending the message. how to receive message when app go online again without clicking the notification
