### ISSUE TITLE
[🐛] Play Intergrity Error - Can't not get token from Play Intergrity android

### ISSUE THREAD

**Issue by ledinhthi** [invertase/react-native-firebase#6951]
Hi @mikehardy ,
I'm facing the problem when i get token from Play intergrity:
I already turn on app Play integrity on CHplay with release product.
I added SHA-256 to firebase.
But get 403 attestation failed. on both debug, and release.
I'm using  "@react-native-firebase/app-check": "^17.3.1",
I saw on google api project. which was tell us that, we had a request for play integrity. But exchange 100% error.
Here is the screen shot about it.
<img width="1120" alt="Screen Shot 2023-02-28 at 11 12 03" src="https://user-images.githubusercontent.com/25853138/221751894-ca883ba9-37f5-4aa0-98d7-ba52827a2847.png">

Could you help me to took a look on it?

Thank you so much

**Comment by mikehardy** [comment]
Unfortunately I'm not sure what causes this for your project, my guess is some sort of misconfiguration of Play Integrity though. Perhaps the SHA-256 is from your local APK and not the signing key from google play dashboard they use to turn ABBs into APKs

**Comment by ledinhthi** [comment]
Your mean is apk maybe not correct with sha from google play site

Vào Th 3, 28 thg 2, 2023 lúc 11:32 Mike Hardy ***@***.***> đã
viết:
