### ISSUE TITLE
push() no longer returns anything

### ISSUE THREAD

**Issue by ergunyasar** [invertase/react-native-firebase#696]
Hello,
.push() method of 2.x version of react-native-firebase was returning a promise and when its resolved, I was getting an object inside then function. This object had a "path" prop which gave me the full path of inserted object.

However, currently I'm using 3.1.0 and then function returns null to me. Object is still inserting to database I dont think there is a problem with that. I can observe it.

`firebase.database().ref('path/' + id).push({
                key: 'value'
            }).then((result) => {
                console.log('result',result); //this wasn't null until the 3.1.0 version
                console.log(result.path);
            })`

### Environment

1. Application Target Platform: IOS

2. Development Operating System: macOS Sierra 10.12.6

3. Build Tools: XCode 9.1

4. React Native version: 0.51

5. RNFirebase Version: 3.1.0

6. Firebase Module: database

**Comment by Ehesp** [comment]
I *think* the functionality was incorrect, so we fixed it to match the web SDK. `push` shouldn't be a promise, as it's just generating a new key.

```js
const key = firebase.database().ref('path/' + id).push({ key: 'value' });
```

**Comment by chrisbianca** [comment]
@ergunyasar This was changed as part of v3.0.0 to match the web SDK.  See the conversation here: https://github.com/invertase/react-native-firebase/issues/147
