### ISSUE TITLE
[🐛] [remoteconfig/failure] fetch() operation cannot be completed successfully.

### ISSUE THREAD

**Issue by SohelIslamImran** [invertase/react-native-firebase#6962]
## Issue

 `"@react-native-firebase/remote-config"` throws this error :
```sh
Error: [remoteconfig/failure] fetch() operation cannot be completed successfully.
``` 

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/analytics": "^17.3.1",
    "@react-native-firebase/app": "^17.3.1",
    "@react-native-firebase/crashlytics": "^17.3.1",
    "@react-native-firebase/dynamic-links": "^17.3.1",
    "@react-native-firebase/remote-config": "^17.3.1",
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
$ npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
    Memory: 4.52 GB / 13.90 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-221.6008.13.2211.9514443
    Visual Studio: Not Found
  Languages:
    Java: 17.0.6 - /c/Program Files/Common Files/Oracle/Java/javapath/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.71.3 is now available (your project is running on v0.70.5).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.71.3
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.70.5
info For more info, check out "https://reactnative.dev/docs/upgrading".
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `v17.3.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `"@react-native-firebase/remote-config": "^17.3.0",`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by priyankdixit** [comment]
Hi,I can solve this one....please assign me

**Comment by mikehardy** [comment]
@priyankdixit that's not how it works here? Sorry - if you have conclusive information on the solution please just post it.

@SohelIslamImran I'm not aware of any difference in 17.3.0-17.3.1 diff that would affect this https://github.com/invertase/react-native-firebase/compare/v17.3.0...v17.3.1

It was just a bump to firebase-android-sdk and nothing else, and their release notes contain no mention of changes to remote config https://firebase.google.com/support/release-notes/android#2023-02-15

We'll need a better issue report + reproduction https://stackoverflow.com/help/how-to-ask / https://stackoverflow.com/help/minimal-reproducible-example

**Comment by SohelIslamImran** [comment]
@mikehardy Sorry, Actually even 17.3.0 has the same issue. It sometimes throw and sometimes not

**Comment by SohelIslamImran** [comment]
```js
  useEffect(() => {
    (async () => {
      await remoteConfig().setConfigSettings({
        minimumFetchIntervalMillis: 21600000, // 6 hours
      });
      await remoteConfig().setDefaults(defaultRemoteConfig);
      await remoteConfig().fetchAndActivate();
      const configValues = remoteConfig().getAll();
      const config = {};
      for (const [key, entry] of Object.entries(configValues)) {
        let value = entry.asString();
        if (numberRegex.test(value)) value = entry.asNumber();
        if (booleanRegex.test(value)) value = entry.asBoolean();
        config[key] = value;
      }
      setFeatures(config);
    })();
  }, []);
  ```

**Comment by SohelIslamImran** [comment]
@mikehardy Is anything wrong with the above code?
