### ISSUE TITLE
[🐛] Installation RemoteConfig - Your JavaScript code tried to access a native module that doesn't exist

### ISSUE THREAD

**Issue by lutluthfi** [invertase/react-native-firebase#6967]
## Issue

Hi, I'm in the middle of personal project. I create React Native project with Expo. When I try to install the Firebase Remote Config and I follow step-by-step in this link https://rnfirebase.io/remote-config/usage then try to run, the apps show this Uncaught Error
<img src="https://user-images.githubusercontent.com/16360926/223177001-024fb06b-054c-4a86-984f-66a61e01e39f.jpeg" width="200" />

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "haloustadz-rn",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-community/masked-view": "*",
    "@react-native-firebase/analytics": "^17.3.1",
    "@react-native-firebase/app": "^17.3.2",
    "@react-native-firebase/remote-config": "^17.3.1",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/drawer": "6.4.1",
    "@react-navigation/elements": "1.3.3",
    "@react-navigation/material-bottom-tabs": "6.2.1",
    "@react-navigation/material-top-tabs": "6.2.1",
    "@react-navigation/native": "6.0.10",
    "@react-navigation/native-stack": "6.6.1",
    "@react-navigation/stack": "6.2.1",
    "@reduxjs/toolkit": "^1.9.3",
    "@types/react-native-snap-carousel": "^3.8.5",
    "axios": "^1.3.4",
    "deprecated-react-native-prop-types": "^4.0.0",
    "dotenv": "^16.0.3",
    "expo": "^48.0.4",
    "expo-application": "~5.1.1",
    "expo-build-properties": "~0.5.1",
    "expo-constants": "~14.2.1",
    "expo-dev-client": "~2.1.5",
    "expo-device": "~5.2.1",
    "expo-haptics": "~12.2.1",
    "expo-image": "~1.0.0",
    "expo-linear-gradient": "^12.1.1",
    "expo-status-bar": "~1.4.4",
    "mobx": "^6.8.0",
    "react": "18.2.0",
    "react-native": "0.71.3",
    "react-native-asset": "^2.1.0",
    "react-native-fast-image": "^8.6.3",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-pager-view": "6.1.2",
    "react-native-paper": "^4.7.2",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-tab-view": "^3.0.0",
    "react-native-ui-lib": "^7.1.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-voximplant": "^1.36.0",
    "react-redux": "^8.0.5",
    "redux": "^4.2.1",
    "typescript": "^4.9.5"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@redux-devtools/core": "^3.13.1",
    "@types/react-native-vector-icons": "^6.4.13",
    "babel-plugin-module-resolver": "^5.0.0",
    "patch-package": "^6.5.1"
  },
  "private": true
}
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.25 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `17.3.2`

- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Your error message states in fairly clear terms what the problem is, please examine it carefully and do the necessary things for using non-expo modules in an expo project

**Comment by lutluthfi** [comment]
@mikehardy I see, this is only for RemoteConfig or others too?
