### ISSUE TITLE
Does react-native-firebase use app instance id?

### ISSUE THREAD

**Issue by lindsaymacvean** [invertase/react-native-firebase#6975]
Apologies if this is obvious or a Google search away. I have been at this question for a few hours to satisfy a Data Protection Officer at a client. 

Google Firebase suggests the following things could be considered PII and can be transmitted from Firebase Analytics 
[Mobile ad IDs](https://support.google.com/adxseller/answer/6274238?hl=en)
[IDFVs](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor)/[Android IDs](https://developer.android.com/reference/android/provider/Settings.Secure.html#ANDROID_ID)
[Firebase installation IDs](https://firebase.google.com/docs/projects/manage-installations)
[Analytics App Instance IDs](https://support.google.com/firebase/answer/6317486?hl=en)

Reference
[https://firebase.google.com/support/privacy](https://firebase.google.com/support/privacy)

I believe I can turn off the first two in firebase.json. The third one is not generally considered PII (at least according to Google)
But the last one I am not sure whether we need to add something to the generated AndroidManifest.xml in our pipeline. But having looked through the react-native-firebase code I am wondering if it even reports the App Instance ID or relies entirely on the firebaseID?

Reference
[https://github.com/invertase/react-native-firebase/blob/main/packages/app/lib/common/id.js](https://github.com/invertase/react-native-firebase/blob/main/packages/app/lib/common/id.js)

**Comment by mikehardy** [comment]
Hey there - interesting

We do have the APIs to get / reset the analytics app instance id:
https://rnfirebase.io/reference/analytics#resetAnalyticsData
https://rnfirebase.io/reference/analytics#getAppInstanceId

I don't believe it is PII though it is a semi-persistent identifier (that is: it is persistent as long as the same app installation exists / is not uninstalled and you do not call resetAnalyticsData)

From a GDPR perspective, this would correlate to the "right to be forgotten" I think, if the user does allows tracking but then later revokes tracking permission you would want to reset the app instance ID just to be sure and then disable automatic data collection.

All of this happens at the firebase-android-sdk / firebase-ios-sdk level though, we don't have anything specific at the react-native-firebase level other than the ability to get + reset the analytics app instance ID and enable/disable collection.

If you must have more detailed answers I would take it up on stackoverflow with the appropriate firebase tags and you will probably be able to get firebase staff to respond, they use that channel - or on their github repos of course

Hope this helps!
