### ISSUE TITLE
[🐛] React Native Android and iOS logs and recordError is not working in firebase console

### ISSUE THREAD

**Issue by harshal111** [invertase/react-native-firebase#6979]
I am integrating firebase crashlytics in my react native application and below is my firebase version for that 

package.json 

    "@react-native-firebase/app": "^17.3.1",
    "@react-native-firebase/crashlytics": "^17.3.1",
    "@react-native-firebase/messaging": "^17.3.1",

Android set up 

build.gradle 

classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.4'

app/build.gradle 
at top level below apply plugin: 'com.google.gms.google-services' i added below line 

apply plugin: 'com.google.firebase.crashlytics'

inside dependencies block i added below plugins 
 implementation 'com.google.firebase:firebase-analytics-ktx'
 implementation platform('com.google.firebase:firebase-bom:31.2.0')

Now In my react native ts file i called as below 

import crashlytics from '@react-native-firebase/crashlytics';

for record log and crash i added line as below 

 ```
 catch (error) {
        console.log('useAddTicket error -->', error);
        crashlytics().log(`Add ticket ${url} ${error}`);
         crashlytics().recordError(error);
      }
```

When I try above in Android and iOS my logs as well as recordError is not display in my firebase console any idea how I can solve this ?

**Comment by mikehardy** [comment]
You'll want this: https://invertase.io/blog/react-native-firebase-crashlytics-configuration

**Comment by wency-yang** [comment]
@harshalkalavadiya-star Is the issue fixed? Can you log the error caught on firebase?
