### ISSUE TITLE
.babelrc is being published

### ISSUE THREAD

**Issue by peterdivvito** [invertase/react-native-firebase#698]
### Issue

After upgrading to 3.2.0 my jest tests started failing with an error around invalid syntax 

export default ....
^^^^^^

After pulling my hair out for a couple of hours I tracked the issue down to the .babelrc file deployed with your package. This babelrc file was being used instead of the one in the root of my project causing things to break.

I don't believe this should be a part of any package so can you please remove it.

Thanks

### Environment

1. Application Target Platform: 

2. Development Operating System: 

3. Build Tools: 

4. React Native version: 

5. RNFirebase Version: 

6. Firebase Module:

**Comment by chrisbianca** [comment]
@peterdivvito Sorry about this - we introduced babel to allow flow typings to work properly and forgot to ignore the configuration as part of the npm build.  I've updated this now so it will be fixed in the next release.
