### ISSUE TITLE
[🐛] [ANDROID] :app:injectCrashlyticsBuildIdsRelease FAILED - unstrippedNativeLibsDir

### ISSUE THREAD

**Issue by yepMad** [invertase/react-native-firebase#6983]
## Issue

"./gradlew assembleRelease" error:

```
> Task :app:injectCrashlyticsBuildIdsRelease FAILED
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:injectCrashlyticsBuildIdsRelease'.
> java.io.IOException: Unstripped native library path does not exist: C:\Users\---\Documents\Git\---\android\app\build\intermediates\merged_native_libs\release\out\lib. Either specify the correct unstrippedNativeLibsDir or disable Crashlytics symbol uploading.
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "expo": "^48.0.4",
    "react": "^18.2.0",
    "react-native": "^0.71.3",
    "@react-native-firebase/analytics": "^17.3.2",
    "@react-native-firebase/app": "^17.3.2",
    "@react-native-firebase/crashlytics": "^17.3.2",
    "@react-native-firebase/messaging": "^17.3.2",
    "@react-native-firebase/perf": "^17.3.2",
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "messaging_android_notification_channel_id": "high-priority",
    "messaging_android_notification_color": "@color/white"
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [X] my application is an AndroidX application?
- [X] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
release {
        signingConfig signingConfigs.release
        minifyEnabled enableProguardInReleaseBuilds
        proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"

        firebaseCrashlytics {
                nativeSymbolUploadEnabled true
                unstrippedNativeLibsDir 'build/intermediates/merged_native_libs/release/out/lib'
        }
}
```

#### `android/settings.gradle`:

```groovy
rootProject.name = '------'

apply from: new File(["node", "--print", "require.resolve('expo/package.json')"].execute(null, rootDir).text.trim(), "../scripts/autolinking.gradle");
useExpoModules()

apply from: new File(["node", "--print", "require.resolve('@react-native-community/cli-platform-android/package.json')"].execute(null, rootDir).text.trim(), "../native_modules.gradle");
applyNativeModulesSettingsGradle(settings)

include ':app'
includeBuild(new File(["node", "--print", "require.resolve('react-native-gradle-plugin/package.json')"].execute(null, rootDir).text.trim()).getParentFile())

include ':app', ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 15.29 GB / 31.92 GB
  Binaries:
    Node: 16.19.0 - ~\AppData\Local\Temp\yarn--1678500777997-0.07019674832839518\node.CMD
    Yarn: 1.22.19 - ~\AppData\Local\Temp\yarn--1678500777997-0.07019674832839518\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: 15.9.28307.2019 (Visual Studio Community 2017), 16.11.32802.440 (Visual Studio Community 2019)
  Languages:
    Java: 11.0.15
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.71.3 => 0.71.3 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [X] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `17.3.2`
- **`Firebase` module(s) you're using that has the issue:**
  - `crashlytics`
- **Are you using `TypeScript`?**
  - `Y` & `v4.9.5`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by yepMad** [comment]
Probably related: https://github.com/firebase/firebase-android-sdk/issues/4682

**Comment by mikehardy** [comment]
I was unable to successfully generate an android release build with crashlytics android plugin v2.9.4 whereas v2.9.2 worked in make-demo - so hopefully the upstream issue is resolved soon. Until then I have to recommend v2.9.2 of the android crashlytics plugin

**Comment by mikehardy** [comment]
I've got a PR open that will update the expo plugin to use 2.9.2 instead of 2.9.4 plus alters docs to recommend 2.9.2 with a note that 2.9.4 is problematic, linking back to here. I'm going to resolve this here since we have a workaround *but* I urge everyone to subscribe to the upstream issue and stay subscribed to this one. If there is anything important, I'll post updates but in general I think we can hope a 2.9.5 version-to-come of the plugin will fix things

**Comment by billnbell** [comment]
it does not build on React Native - non-expo. So we still need a solution.

**Comment by mikehardy** [comment]
The solution is to use 2.9.2, until some version greater than 2.9.4 is released @billnbell

**Comment by amit-nayar** [comment]
> I am using 2.9.5 and I am getting the following error:
> 
> ```
> * What went wrong:
> Could not determine the dependencies of task ':app:lintVitalReportRelease'.
> > Could not create task ':app:injectCrashlyticsBuildIdsRelease'.
>    > Cannot invoke method map() on null object
> ```
> 
> 2.9.2 works ✅

Same for me. Can't use the latest. Using 2.9.2 for now.
