### ISSUE TITLE
[🐛] Auth token not getting refreshed after expired - React Native 

### ISSUE THREAD

**Issue by MDmubarak786** [invertase/react-native-firebase#6989]
## Issue

Describe your issue here
Am using all the updated library versions like React, React Native and Firebase
currently facing issue like token expire time is 1 hr after expired token not getting refresh 
so While doing the API call. API returning the error like "Firebase token invalid" due to Firebase not renewed the auth token  
after expired time 

used the updated firebase version but I thought i would be latest version issue.
even though still replicating the issue.

using this method onAuthStateChanged is it correct one ?

please help me on this 

---

### Javascript

<details><summary>
  const onAuthStateChanged = async (userDetails) => {
    setUser(userDetails)
    if (initializing) setInitializing(false)
  }

  useEffect(() => {
    const subscriber = auth().onAuthStateChanged(onAuthStateChanged)

    return subscriber
  }, [user, appState, initializing])
</summary>
<p>

#### `package.json`:

```json
    "react": "18.2.0",
    "@react-native-firebase/analytics": "14.12.0",
    "@react-native-firebase/app": "14.12.0",
    "@react-native-firebase/auth": "14.12.0",
    "@react-native-firebase/messaging": "14.12.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
> Am using all the updated library versions like React, React Native and Firebase

Specifying the actual version numbers is important

> currently facing issue like token expire time is 1 hr after expired token not getting refresh

What evidence do you have to support this assertion? Do you have sample code that reproduces it? Device information about the environment where it reproduces (model / android version / timezone+locale information)?

> using this method onAuthStateChanged is it correct one ?

No idea based on information provided, sorry

In general, you've deleted the template, which means we can't help and that leads to us closing issues.

In specific, when this (tokens not being renewed) has happened before it has been a variety of issues related to a few things - API calls with restrictions in the google cloud configuration, SSL certificate pinning in the app, network issues, device time issues. Each issue requires specific careful investigation which is out of scope for this repository

If you created a sample app (perhaps starting with https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh ) you would likely find that it works just fine. So the goal would be to figure out what is different between your project and a clean / default project and go from there
