### ISSUE TITLE
Can't setBadgeNumber

### ISSUE THREAD

**Issue by nighttiger1990** [invertase/react-native-firebase#699]
**Issue**
How can i fix this?
Calling setBadgeNumber(1) get error
![25555316_2229767237049173_1775928528_n](https://user-images.githubusercontent.com/21042933/34193562-f4e4de9c-e586-11e7-81ec-05a9a47a55c5.png)
-My devices worked well with ShortcutBagder 
**Environment**
Application Target Platform:
android 4.4.2
Development Operating System:
Windows 10 Fall Creator
Build Tools version:
25.0.1
React Native version:
"react-native": "0.48.4"
RNFirebase Version:
"react-native-firebase": "^3.1.1"
Firebase Module:
Cloud Messaging

**Comment by nighttiger1990** [comment]
i resolved this by add: to ./app/build.gradle
`compile 'me.leolin:ShortcutBadger:1.1.18@aar'`

**Comment by evanjmg** [comment]
This should be in the docs!!!!

**Comment by Ehesp** [comment]
@evanjmg you should submit a PR!!!!

**Comment by evanjmg** [comment]
done https://github.com/invertase/react-native-firebase-docs/pull/32

**Comment by HueNguyenFramgia** [comment]
@kkusanagi I use code but it is work in ios not work android.Please help me!

**Comment by kkusanagi** [comment]
@HueNguyenFramgia about that, I'm sorry, I'm only tried it on Android.

For firebase IOS, please read through here.
[https://rnfirebase.io/docs/v5.x.x/notifications/reference/IOSNotification](https://rnfirebase.io/docs/v5.x.x/notifications/reference/IOSNotification)

Seems like android and iOS are separated.

Or use the original feature in react native as shown here
[https://facebook.github.io/react-native/docs/pushnotificationios.html](https://facebook.github.io/react-native/docs/pushnotificationios.html)

**Comment by udarts** [comment]
I also try to use the setBadge on Android and it is not showing the badge.

Using the following code:
```javascript
if (Platform.OS === 'ios') {
      ShortcutBadge.setCount(JSON.parse(amount));
}else{
      firebase.notifications().setBadge(JSON.parse(amount));
}
```

It works on iOS, but on Android it doesn't show the badge. Does anybody got this working?

**Comment by JB-CHAUVIN** [comment]
I have the same problem @udarts.
Have you fixed the issue ?

**Comment by kkusanagi** [comment]
Try it on real mobile phone. It won't work on emulator.

**Comment by saikiranoptisol** [comment]
@udarts  @JB-CHAUVIN  did you get any solution on this

**Comment by hammerstrike331** [comment]
> i resolved this by add: to ./app/build.gradle
> `compile 'me.leolin:ShortcutBadger:1.1.18@aar'`


dependencies {
    implementation "com.google.firebase:firebase-core:17.0.1"
    implementation "com.google.firebase:firebase-messaging:19.0.1"
    implementation 'me.leolin:ShortcutBadger:1.1.21@aar'   **<---- add this**

}

**Comment by mikehardy** [comment]
That library is not maintained and badging on android is basically not supported and thus not a good idea to agree to deliver as a developer. Read up on how it is supported (only some launchers, launcher-specific implementations, specifically not supported in AOSP or on pixels) and best practice on Android is to not do it.
