### ISSUE TITLE
[📚] Add react-native-firebase in an expo managed project.

### ISSUE THREAD

**Issue by Saad-Bashar** [invertase/react-native-firebase#6990]
## Documentation Feedback

Right now there is a section on adding this package to an expo-managed project. That is already good. But I have faced few troubles following the docs. So I have added a few more details. Hope this is useful,

**Summary of installing react-native-firebase package successfully in an expo project.**

### 1. **Install expo-dev-client**

Since React Native Firebase requires custom native code, you need to install the `expo-dev-client` library in your project. It also allows configuring any native code required by React Native Firebase using Config plugins without writing native code yourself.

To install `[expo-dev-client](https://docs.expo.dev/development/getting-started#installing--expo-dev-client--in-your-project)`, run the following command in your project:

```jsx
npx expo install expo-dev-client
```

### 2. **Install React Native Firebase**

To use React Native Firebase, it is necessary to install the `@react-native-firebase/app` module. This module provides the core functionality for all other modules. It also adds custom native code to your project using a config plugin. You can install it using the following command:

```jsx
npx expo install @react-native-firebase/app
```

### 3. Add plugin

Go to `app.json` and add the following at the end,

```jsx
"plugins": [
      "@react-native-firebase/app",
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }
      ]
    ]
```

<aside>
💡 You do not need to add `“@react-native-firebase/firestore"`, `"@react-native-firebase/authentication"`,

</aside>

### 4. Install expo build properties

Install `expo-build-properties` by running,

```
npx expo install expo-build-properties
```

### 5. Expo prebuild

Then run expo prebuild,

```jsx
expo prebuild --clean
```

### 6. Run the app,

```jsx
npx expo run:android or npx expo run:ios
```

Try first using an android device.

but if you need to run on an emulator or simulator, then 

- You need both Android Studio and Xcode installed and configured on your computer.
- Then, you can run the project using `npx expo run:android` or `npx expo run:ios` command.

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there - this would work best as a PR to the docs - you can propose a PR to docs by just clicking the edit button on the top right of every documentation change

I do not personally use Expo so I cannot verify those and do not propose PRs to Expo docs, but our Expo users (like yourself!) are more than welcome to and I merge those regularly

Thanks!

**Comment by mikehardy** [comment]
No need to reopen the issue, we can still communicate, and you may open a PR any time

**Comment by guidani** [comment]
But, where the `google-service.json` file go using a Managed Flow?
