### ISSUE TITLE
🔥  messaging().SetBackgroundmessagehandler() not working in iOS on real device but messaging().onMessage()  is working fine 

### ISSUE THREAD

**Issue by KumailAhmedWellwink** [invertase/react-native-firebase#7006]
i am using the latest
 @react-native-firebase/app :17.4.0 ,
@react-native-firebase/messaging :17.4.0

my podfile file  
pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

my  React Native version is react-native": "^0.65.0"
 calling messaging().SetBackgroundmessagehandler() in index.js 

also enable in background Modes complete follow the documentation and doing all the steps but still no luck

**Comment by Akilramki** [comment]
i am also facing this issue

**Comment by mikehardy** [comment]
```
pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
```

This should not be necessary, it's contrary to our documentation and means your auto-linking is not working

> my React Native version is react-native": "^0.65.0"

I'm not sure this is supported anymore, I wouldn't trust a version that old.

In general we follow these guidelines: https://github.com/reactwg/react-native-releases#releases-support-policy

> calling messaging().SetBackgroundmessagehandler() in index.js

This description of your reproduction is imprecise + incomplete: https://stackoverflow.com/help/minimal-reproducible-example - showing a minimal/complete `index.js` that reproduces it would be helpful

Additionally you do not specify the JSON you are using. Typically when people have this problem they:

- have not included `content-available: 1` in the JSON that FCM sends
- have not requested + received notification permissions on iOS
- have background refresh disabled or are in low power mode
- have some other issue which causes iOS not to deliver the message (you have to look at native logs to see why the OS did not deliver it...)

In general, background messages on iOS **are not reliable, by Apple design** - you should expect that some or all will not be delivered. If guaranteed delivery is important, you must include a notification block in your FCM

**Comment by KumailAhmedWellwink** [comment]
/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import React from 'react';
import {name as appName} from './app.json';
import messaging from '@react-native-firebase/messaging';


messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('Message handled in the background!', remoteMessage);
});
function HeadlessCheck({ isHeadless }) {
  if (isHeadless) {
    console.log("Headless");
    // App has been launched in the background by iOS, ignore
    return null;
  }

  return <App />;
}
AppRegistry.registerComponent(appName, () => HeadlessCheck);


my Index.js file above
1: background refresh is enabled 
2: requested + received notification permissions on iOS
3: content-available: 1 is also mention

and please describe the notification block 
 my JSOn is 
data = {}
          data[:msg] = 'call canceled'
          data[:patient_user_id]= user_id
          data[:caller_id] = current_user.id
          data[:notification_type]= 'Video call'
          fcm = FCM.new( key)

          options = {
            data: data,
            mutableContent: true,
            contentAvailable:1
            notification: { body: "Event ", title: "Moniter Vital Sign" } }

          Rails.logger.info("sending ------------------------------------------canceled-------------")
          response = fcm.send(token, options)

please check

**Comment by mikehardy** [comment]
> you have to look at native logs to see why the OS did not deliver it...

Everything seems sensible. What happened in the logs when the FCM was sent?

**Comment by talhashafique12** [comment]
@KumailAhmedWellwink were you able to fix this? if yes then how?

**Comment by hp120** [comment]
@KumailAhmedWellwink  I faced the same issue. Please share a solution if you found.

**Comment by RubenPM-dev** [comment]
> ```js
> /**
>  * @format
>  */
> 
> import {AppRegistry} from 'react-native';
> import App from './App';
> import React from 'react';
> import {name as appName} from './app.json';
> import messaging from '@react-native-firebase/messaging';
> 
> 
> messaging().setBackgroundMessageHandler(async remoteMessage => {
>   console.log('Message handled in the background!', remoteMessage);
> });
> function HeadlessCheck({ isHeadless }) {
>   if (isHeadless) {
>     console.log("Headless");
>     // App has been launched in the background by iOS, ignore
>     return null;
>   }
> 
>   return <App />;
> }
> AppRegistry.registerComponent(appName, () => HeadlessCheck);
> ```
> 
> my Index.js file above 1: background refresh is enabled 2: requested + received notification permissions on iOS 3: content-available: 1 is also mention
> 
> and please describe the notification block my JSOn is
> 
> ```python
> data = {}
>           data[:msg] = 'call canceled'
>           data[:patient_user_id]= user_id
>           data[:caller_id] = current_user.id
>           data[:notification_type]= 'Video call'
>           fcm = FCM.new( key)
> 
>           options = {
>             data: data,
>             mutableContent: true,
>             contentAvailable:1
>             notification: { body: "Event ", title: "Moniter Vital Sign" } }
> 
>           Rails.logger.info("sending ------------------------------------------canceled-------------")
>           response = fcm.send(token, options)
> ```
> 
> please check

For contentAvailable should not be a boolean so in this case 'true'?

`contentAvailable: true`
