### ISSUE TITLE
Migrating problem from  2.2.1 to 3.1.1

### ISSUE THREAD

**Issue by dennisbejencev-an** [invertase/react-native-firebase#701]
before migrating all worked good, when I made `npm install react-native-firebase@3.1.1`
I got http://prntscr.com/hq2i2k
my current versions
```
    "react-native-firebase": "^3.1.1",
    "react-native": "0.48.3",
    Firebase/Core (4.8.0).
    Iphone 6 - IOS 10.3
    Mac OS Sierra 10.12.5
```
problem is here: http://prntscr.com/hq2okc
my Podfile.lock https://pastebin.com/xpNbxDa5

**Comment by chrisbianca** [comment]
@dennisbejencev-an sounds like your native and JS code may be out of sync - have you correctly rebuilt the application and followed all the migration steps?

**Comment by dennisbejencev-an** [comment]
yes, sorry, I had not completely updated Firebase sdk
