### ISSUE TITLE
'new' is unavailable build failure after XCode 14.3 update

### ISSUE THREAD

**Issue by my-name-is-nheo** [invertase/react-native-firebase#7014]
## Issue

Describe your issue here

After updating to Xcode 14.3, I am encountering a build error while attempting to build my app. Specifically, the error message states that "'init' has been explicitly marked available here."
 
### Javascript

```typescript
  const initializeAppCheckHandler = async () => {
    const provider = firebase.appCheck().newReactNativeFirebaseAppCheckProvider();

    provider.configure({
      android: {
        provider: process.env.NODE_ENV === 'development' ? 'debug' : 'playIntegrity',
        debugToken: config.APP_CHECK_DEBUG_ANDROID_TOKEN,
      },
      apple: {
        provider:
          process.env.NODE_ENV === 'development' ? 'debug' : 'appAttestWithDeviceCheckFallback',
        debugToken: config.iOS_APP_CHECK_DEBUG_TOKEN,
      },
    });

    firebase.appCheck().initializeAppCheck({ provider, isTokenAutoRefreshEnabled: true });
  };
```
#### `package.json`:

```json
    "@react-native-firebase/app": "^17.4.0",
    "@react-native-firebase/app-check": "^17.4.0",
    "@react-native-firebase/auth": "^17.4.0",
    "@react-native-firebase/messaging": "^17.4.0",  
    "react-native": "^0.67.5",
```
I'm trying not to release too much information as this is for a company project. Please let me know if there is anything more you need. I uploaded as much as I could

## Bug Photos

![image](https://user-images.githubusercontent.com/58013260/229004817-5a39cbf7-9ab9-4b3e-91c0-ae92b375a18d.png)

![image](https://user-images.githubusercontent.com/58013260/229004896-4fddb7d7-96ae-4750-866d-28fe7caaf4b9.png)

![image](https://user-images.githubusercontent.com/58013260/229004918-ceb0622d-466f-44c2-ae46-e793096f171e.png)

![image](https://user-images.githubusercontent.com/58013260/229004973-9a63555e-5971-4d20-bd1e-5a9e36544b07.png)

Amazing how there are only 34 pending issues in this project. Thank you to all contributers

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '16.0'
target 'Test - Dev' do
  use_modular_headers!
  $RNFirebaseAsStaticFramework = true

  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
end
target 'Test - Demo' do
  use_modular_headers!
  $RNFirebaseAsStaticFramework = true

  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
end
target 'Test - Prod' do
  use_modular_headers!
  $RNFirebaseAsStaticFramework = true

  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
end

use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })

post_install do |installer|
  react_native_post_install(installer)
end
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `17.4.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID` <- apologies but where can i find this?
- **Are you using `TypeScript`?**
  - `Y` & `^4.9.4`

</p>
</details>

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 13.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 17.79 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2023.01.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/hello/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.67.5 => 0.67.5 
    react-native-macos: Not Found
  npmGlobalPackages: < -- using PNPM
    *react-native*: Not Found
```

</p>

**Comment by mikehardy** [comment]
Wow, that took forever! Xcode updates are a bear. Also a requirement, though, so it's done now.

It's a silly coding error on my part. Those three `new`s that are causing problems should all be `alloc`s

Patch + release landing in a moment, if you're following along you'll see the PR linked here on the issue, and in that PR if you need a patch immediately vs updating theh packages, our CI generates a set of patch-package compatible patches you may apply.
