### ISSUE TITLE
[🐛] XCode 14.3 Build Error - 'value' is unavailable: Introduced in iOS 12.0

### ISSUE THREAD

**Issue by AlixH** [invertase/react-native-firebase#7018]
## Issue

I have just updated my Mac to Ventura 13.3 and XCode got updated to 14.3 Since, my app is not building anymore and outputs build error when building Firebase pods:
![Screenshot 2023-04-03 at 15 01 40](https://user-images.githubusercontent.com/32574035/229518364-deaf8833-b4b6-4a64-8fa1-970165574798.png)

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 13.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 352.23 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 9.1.2 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.1.0 => 18.1.0 
    react-native: ^0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

- **Platform that you're experiencing the issue on**:
  - [X] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `16.4.5`
- **`Firebase` module(s) you're using that has the issue:**
  - `App and Messaging`
- **Are you using `TypeScript`?**
  - `Y` & `4.9.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by AlixH** [comment]
> @AlixH how did you solve this issue?

I did not, but it's not related to this lib. The issue is on React-Codegen
I will downgrade XCode version, you can also look at this to  patch your podfile until they patch React Native: https://github.com/facebook/react-native/issues/36635#issuecomment-1483266211

**Comment by dimaischenko** [comment]
Thanks! I updated both react-native (to 0.71.6) and react-native-firebase (to 17.4.1) to the latest versions with their patches and got a new error, already definitely related to the firebase package with building...

```
Undefined symbols for architecture arm64:
  "_swift_stdlib_isStackAllocationSafe", referenced from:
      _$ss17_NativeDictionaryV6filteryAByxq_GSbx3key_q_5valuet_tKXEKF20FirebaseCoreInternal10TimePeriodO_10Foundation4DateVTg504$s20fg10Internal10ij14O10Foundation4L41VSbs5Error_pIgyndzo_AcFSbsAG_pIegnndzo_TRAiLSbs0R0_pIgyndzo_Tf1cn_n in libFirebaseCoreInternal.a(HeartbeatController.o
```

I'll try to figure it out, or maybe really just roll back to xcode 14.2

**Comment by AlixH** [comment]
> Thanks! I updated both react-native (to 0.71.6) and react-native-firebase (to 17.4.1) to the latest versions with their patches and got a new error, already definitely related to the firebase package with building...
> 
> ```
> Undefined symbols for architecture arm64:
>   "_swift_stdlib_isStackAllocationSafe", referenced from:
>       _$ss17_NativeDictionaryV6filteryAByxq_GSbx3key_q_5valuet_tKXEKF20FirebaseCoreInternal10TimePeriodO_10Foundation4DateVTg504$s20fg10Internal10ij14O10Foundation4L41VSbs5Error_pIgyndzo_AcFSbsAG_pIegnndzo_TRAiLSbs0R0_pIgyndzo_Tf1cn_n in libFirebaseCoreInternal.a(HeartbeatController.o
> ```
> 
> I'll try to figure it out, or maybe really just roll back to xcode 14.2

The patch on React Native is not out yet... You need to patch your Podfile as shown in my link

**Comment by mikehardy** [comment]
Just to note that I issued the latest release (with Xcode 14.3 compatibility) *only* after actually testing it on Xcode 14.3 including our e2e app (of course :-) ) which exercises all of firebase-ios-sdk. And It all worked for me at least.

I did not test it on an apple silicon machine though and I notice the last error here posted by @dimaischenko is an arm64 (apple silicon) machine. Is that still happening + reproducible? I have one M1 machine in the house and I can check with it if needed

**Comment by dimaischenko** [comment]
> I did not test it on an apple silicon machine though and I notice the last error here posted by @dimaischenko is an arm64 (apple silicon) machine. Is that still happening + reproducible? I have one M1 machine in the house and I can check with it if needed

Yes, I have not yet been able to resolve the error and rolled back to XCode 14.2. If you have the possibility to look at the M1 would be very grateful!

**Comment by mikehardy** [comment]
This was opened as a separate issue #7021 - and as commented there, I just tested on an M1 machine this evening after updating everything, and I am unable to reproduce the error. Everything worked for me. Please comment further on 7021 if you still reproduce this and you are using supported build methods (that is: `use_frameworks! :linkage => :static` in your Podfile)
