### ISSUE TITLE
[🐛] XCode 14.3 iOS Build Error - Undefined _swift_stdlib_isStackAllocationSafe

### ISSUE THREAD

**Issue by dimaischenko** [invertase/react-native-firebase#7021]
## Issue

I have just updated my Mac to Ventura 13.3 and XCode got updated to 14.3. And now my app is not archived (but works in debug on simulator) anymore and outputs build error when building Firebase pods:

```
Undefined symbols for architecture arm64:
  "_swift_stdlib_isStackAllocationSafe", referenced from:
      _$ss17_NativeDictionaryV6filteryAByxq_GSbx3key_q_5valuet_tKXEKF20FirebaseCoreInternal10TimePeriodO_10Foundation4DateVTg504$s20fg10Internal10ij14O10Foundation4L41VSbs5Error_pIgyndzo_AcFSbsAG_pIegnndzo_TRAiLSbs0R0_pIgyndzo_Tf1cn_n in libFirebaseCoreInternal.a(HeartbeatController.o
```
---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M1
    Memory: 125.84 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - /opt/homebrew/bin/npm
    Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0
    react-native: ^0.71.6 => 0.71.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 17.4.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `app`, `Analytics`, `Crashlytics`, `Messaging`, `remote-config`, `installations`
- **Are you using `TypeScript`?**
  - `Y` & `5.0.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by dimaischenko** [comment]
> I have the exact same issue, can build but can't archive, it's throws the same error described above. All updated to the latest version, clean build folder, deleted node_modules and pods, restarted Xcode and Mac but the error won't go away.

Yep, the same. I downgraded back to XCode 14.2 for now, and it all worked

**Comment by mikehardy** [comment]
Sorry this is happening! I checked 14.3 with an intel machine when I issued the Xcode 14.3 compatibility release a few days back but I did not check arm64 and I did not check archive either.

This goes on the list first priority. Hopefully it's something quick but I didn't see anything in an initial scan of firebase-ios-sdk so I do not want to set expectations, it might take a bit of time - apologies in advance if so

**Comment by mikehardy** [comment]
I'm sorry, but I can't reproduce this with my work project (where I have provisioning profiles etc, so I can archive it).
I just updated to react-native 0.70.8 (I'm a bit behind in my work project, unfortunately, but not too far back)
I updated to react-native-firebase 17.4.1 and used firebase-ios-sdk 10.7.0

> [18:35:35]: ▸ Archive Succeeded

That was the happy message from fastlane after the build + archive process, and it is uploading successfully now.

**Comment by mikehardy** [comment]
I'll note that you removed / did not include most of the information in our issue template.
Perhaps you are not using `use_frameworks` and are avoiding it via some unsupported workarounds?
That could cause an objective-c / swift interop failure like this build failure.
That is just a guess though, lacking information I cannot be sure of much except that it works for me, and I am using `use_frameworks! :linkage => :static` per our documentation here

**Comment by dimaischenko** [comment]
> I'll note that you removed / did not include most of the information in our issue template. Perhaps you are not using `use_frameworks` and are avoiding it via some unsupported workarounds? That could cause an objective-c / swift interop failure like this build failure. That is just a guess though, lacking information I cannot be sure of much except that it works for me, and I am using `use_frameworks! :linkage => :static` per our documentation here

I'll look into it, I have react native `0.71.6` but I don't think that's the problem. And instead of `use_frameworks! :linkage => :static` I'm using these settings in the Podfile

```
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
...
```

That seems to be the point

**Comment by RobertSasak** [comment]
I managed to build project following this tutorial https://mrdevgeek.com/xcode-14-3-simulator-16-4-build-failure-how-to-fix-value-is-unavailable-introduced-in-ios-12-0-error-with-react-native-0-71-5/

Steps:
- copy ___apply_Xcode_14_3_RC_post_install_workaround_ function
- replace _min_ios_version_supported_ with '13.0'
```rb
# Force pods to match minimum iOS version for React Native
# Fixes build issue on Xcode Cloud where some pods
# Use iOS 12 calls despite being set as iOS 11
def __apply_Xcode_14_3_RC_post_install_workaround(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      current_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      minimum_target = '13.0'
      if current_target.to_f < minimum_target.to_f
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
```
- call ___apply_Xcode_14_3_RC_post_install_workaround(installer)_ in post_install

<details>

<summary>Final Podfile looks like this</summary>

```rb
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

platform :ios, podfile_properties['ios.deploymentTarget'] || '13.0'
install! 'cocoapods',
  :deterministic_uuids => false

# Force pods to match minimum iOS version for React Native
# Fixes build issue on Xcode Cloud where some pods
# Use iOS 12 calls despite being set as iOS 11
def __apply_Xcode_14_3_RC_post_install_workaround(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      current_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      minimum_target = '13.0'
      if current_target.to_f < minimum_target.to_f
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end

target 'Checkito' do
  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    #
    # Uncomment to opt-in to using Flipper
    # Note that if you have use_frameworks! enabled, Flipper will not work
    # :flipper_configuration => !ENV['CI'] ? FlipperConfiguration.enabled : FlipperConfiguration.disabled,
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    __apply_Xcode_14_3_RC_post_install_workaround(installer)

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end
```

</details>

**Comment by dimaischenko** [comment]
> ```ruby
> 
>       current_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
>       minimum_target = '13.0'
>       if current_target.to_f < minimum_target.to_f
>         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
>       end
>     end
>   end
> end
> ```

It seems react-native team fixed this problem in the react-native `0.71.6` update and the patch is unnecessary. But I have a different error, and I think it could really be related to `use_frameworks! :linkage => :static`

You seem to have it right here:

```
use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
```

I'll do some more experiments one day and write, or maybe someone else will write

**Comment by mikehardy** [comment]
1- I reproduce the error requiring IOS minimum deployment moved to 13 in Podfile post install **but only if I do not have the latest react-native** because you are correct, that is fixed now upstream. Latest react-native works

2- I do not reproduce any problems with react-native-firebase when using `use_frameworks! :linkage => :static` as mentioned - I was able to build+archive the latest without problems

So as of current at least - I do not have a reproduction using latest react-native + latest react-native-firebase + use_frameworks as described/required

**Comment by mikehardy** [comment]
@dimaischenko I must say: that style is *explicitly unsupported*. Do not post about build errors here again until/unless you reproduce them with `use_frameworks! :linkage => :static`

**Comment by pke** [comment]
btw @mikehardy the "hack" had to be used for flipper to work (at some point in the past). That's why we also have it in our code base. 
Just merely upgrading to Xcode 14.3 broke the whole setup. That is **insane**. 
The state of this whole ecosystem of weird config values and dependencies will hopefully get some AI help in the future.

**Comment by vishuk570** [comment]
> > I have the exact same issue, can build but can't archive, it's throws the same error described above. All updated to the latest version, clean build folder, deleted node_modules and pods, restarted Xcode and Mac but the error won't go away.
> 
> Yep, the same. I downgraded back to XCode 14.2 for now, and it all worked

How to downgrade in 4.2 ?

**Comment by dimaischenko** [comment]
> How to downgrade in 4.2 ?

https://developer.apple.com/download/all/

Download the required version from here and replace yours in macOS. If there is enough space, then you can keep two in parallel. Then do not replace the current one in Applications, but launch a new one from a separate folder

**Comment by toscalivia83** [comment]
Having the same issue with "react-native": "0.71.7" and XCode 14.3
And I'm using use_frameworks! :linkage => :static

I can run in debug mode on any emulator and on real device but can't Archive
Any idea? @mikehardy

**Comment by minhnguyenit14** [comment]
@toscalivia83 Yeah! that's correct.

I provide the old answer which has more instructions to apply to the Pod file.
https://github.com/adaptyteam/AdaptySDK-React-Native/issues/20#issuecomment-1086816651

and my result also:

![Screenshot at May 25 16-03-27](https://github.com/invertase/react-native-firebase/assets/38130019/0ead4dd4-2159-4fa2-ade1-c77e0db65054)

**Comment by NilsBaumgartner1994** [comment]
Facing the same problem. Can build but not archive.

**Comment by snairsumith** [comment]
Any updates regarding this issue ?

**Comment by snairsumith** [comment]
I have updated the same. But still not resolved . 
this is my pod file 
`require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'mobile' do
  config = use_native_modules!
  use_frameworks! :linkage => :static

  # If you use `use_frameworks!` in your Podfile,
  # uncomment the below $static_framework array and also
  # the pre_install section.  This will cause Flipper and
  # it's dependencies to be built as a static library and all other pods to
  # be dynamic.
  #
  # NOTE Doing this may lead to a broken build if any of these are also
  #      transitive dependencies of other dependencies and are expected
  #      to be built as frameworks.
  #
  $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
    'CocoaAsyncSocket', 'ComponentKit', 'Flipper-DoubleConversion',
    'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
    'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
  
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
        if $static_framework.include?(pod.name)
          def pod.build_type;
            Pod::BuildType.static_library
          end
        end
      end
  end

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'


  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'


  target 'mobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
#   use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  
  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end
  
  
end



`

**Comment by snairsumith** [comment]
I have updated the same. But still not resolved . 
this is my pod file 
`require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'mobile' do
  config = use_native_modules!
  use_frameworks! :linkage => :static

  $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
    'CocoaAsyncSocket', 'ComponentKit', 'Flipper-DoubleConversion',
    'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
    'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
  
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
        if $static_framework.include?(pod.name)
          def pod.build_type;
            Pod::BuildType.static_library
          end
        end
      end
  end

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'


  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'


  target 'mobileTests' do
    inherit! :complete
    # Pods for testing
  end

  
  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end
  
  
end



`

**Comment by dimaischenko** [comment]
@snairsumith 

At first glance it looks like you have a lot of outdated code, which is unnecessary in newer versions of react and swift (maybe I'm wrong). Here is mine for react-native 0.72 and xcode 15:

```
#import <Firebase.h>
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "RNSplashScreen.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  
  self.moduleName = @"aitales";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  bool didFinish = [super application:application didFinishLaunchingWithOptions:launchOptions];
  
  if (didFinish) {
    RCTRootView *rootView = (RCTRootView *)self.window.rootViewController.view;
    rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
  }
  
  // Set the splash screen to show by default.
  [RNSplashScreen show];
  
  return didFinish;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```

Try restarting the project completely after the changes.

```
pod deintegrate
pod install
```

**Comment by dimaischenko** [comment]
@snairsumith I have updated previous comment. And it's for react-native 0.72, they made some changes to it, for example the `require` at the beginning is a bit different now.

**Comment by snairsumith** [comment]
This resolved my issue. 
https://github.com/adaptyteam/AdaptySDK-React-Native/issues/20#issuecomment-1086816651

@dimaischenko Thanks a million for your help :)

**Comment by RaguRam1991** [comment]
xcode 14.2 worked for me. tried and failed with xcode 14.3

https://stackoverflow.com/a/77435861/10317833

**Comment by mikehardy** [comment]
Xcode 15 works just fine with current react-native-firebase and current react-native. Just tested it this morning https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
