### ISSUE TITLE
[🐛] Firebase functions get [Error: NOT FOUND]

### ISSUE THREAD

**Issue by qaws5503** [invertase/react-native-firebase#7026]
## Issue

When I tried to fetch a deployed function, I get an output `[Error: NOT FOUND]` in the console. 
But when I change the function to use local function emulator it works. Can't figure out where's the problem.
My code:
```
// frontend react-native
import functions from '@react-native-firebase/functions';

functions()
      .httpsCallable('example')()
      .then(response => {
        console.log(response);
      }).catch(e => {
        console.log(e); // will log [Error: NOT FOUND]
      });

// backend firebase-functions
exports.example = functions.https.onCall(() => {
  return {data:"data"};
});
```

When I change to this it works
```
// frontend react-native
import functions, { firebase } from '@react-native-firebase/functions';

firebase.functions().useEmulator('localhost', 5001); // this is my local emulator port

functions()
      .httpsCallable('example')()
      .then(response => {
        console.log(response); // will log {data:"data"}
      }).catch(e => {
        console.log(e);
      });

// backend firebase-functions
// run `npm run serve` on the console to start local emulator
exports.example = functions.https.onCall(() => {
  return {data:"data"};
});
```

I'm using Expo and using dev-client to use this package.
I have tested on `@react-native-firebase/firestore`, and it works. So I think it isn't a problem with the setup.

```
version:
"@react-native-firebase/functions": "^17.4.1",
"expo": "~48.0.9",
"react": "18.2.0",
"react-native": "0.71.6",
```
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I suspect some problem with the deployment of the function.
You'll want to check the execution logs for the function in the firebase web console / google cloud console

react-native-firebase functions is working fine (my work project *depends* on it) and this will not result in any change to this repository, this is a project-specific problem and you'll find the solution with more inspection of your project
