### ISSUE TITLE
[📚] Documentation Issue: GoogleIDFASupport is obsolete

### ISSUE THREAD

**Issue by kesha-antonov** [invertase/react-native-firebase#7027]
## Documentation Feedback

Hi,

here https://rnfirebase.io/analytics/usage/installation/ios#device-identification `GoogleIDFASupport` is mentioned that it should be linked. But link on the same page follow to this page https://support.google.com/firebase/answer/6318039 where this pod is not mentioned. And really, I can't find info on firebase website that this pod should be linked. Only `AdSupport.framework`. Seems like we should remove instruction that `GoogleIDFASupport` should be linked. What do you think?

**Comment by mikehardy** [comment]
The documentation as is, is correct. No change is needed.
If you want IDFA support for more detailed analytics, you link that pod.
If you do not want more detailed analytics, you do not link that pod.

**Comment by RohovDmytro** [comment]
@mikehardy as far as I understand, firebase-analytics included idfa collectiong by default AND if you want to avoid that you can use firebase-analytics without ad id support build. So the docs are indeed obselete, isn't it?

**Comment by mikehardy** [comment]
@RohovDmytro this one is pretty subtle, if I understand it correctly. I will link to the relevant discussions I'm aware of and if you think I'm wrong in my analysis please link to the exact things that point it out

Here is my understanding:

- By default, firebase analytics *includes some ATT symbols* but does not directly gather IDFA
  - as described by firebase-ios-sdk staff: https://github.com/firebase/firebase-ios-sdk/issues/7736#issuecomment-805990944
- Firebase analytics will collect and use IDFA *if and only if you link GoogleIDFASupport*
  - as linked in our doc https://support.google.com/firebase/answer/6318039
  - as documented https://firebase.google.com/support/guides/analytics-adsupport?sjid=1429605320174210781-NA
- Apple was requiring ATT disclosure for IDFA use for symbol existence only, even if unused
  - Discussion: https://github.com/invertase/react-native-firebase/discussions/5223
  - PR: https://github.com/invertase/react-native-firebase/pull/5224
- Firebase analytics released a sub-spec that does not even include the symbols, to avoid ATT IDFA disclosure (which is a strict requirement for kid's apps)

So, that means:
- if you want to have extended analytics metrics that use IDFA, you still must link it in as currently documented
- If you have a kids app or want to avoid Apple ATT disclosure requirements for IDFA, you must not link IDFA support in and you need the analytics-no-idfa subspec

Thus I believe our docs are still correct.

The insight is that symbols alone were triggering apple to require ATT disclosure, but symbols aren't enough to actually get IDFA analytics. You still need to link GoogleIDFASupport to get the IDFA analytics.

**Comment by Bardiamist** [comment]
@mikehardy 

>Firebase analytics will collect and use IDFA if and only if you link GoogleIDFASupport
as linked in our doc https://support.google.com/firebase/answer/6318039
as documented https://firebase.google.com/support/guides/analytics-adsupport?sjid=1429605320174210781-NA

But in these docs nothing about `GoogleIDFASupport`. In docs mentioned only `AdSupport.framework`.

Based on [legacy docs](https://developers.google.com/analytics/devguides/collection/ios/v3/optional-features). `GoogleIDFASupport` created for link `AdSupport.framework` and `libAdIdAccess.a`.

So now maybe only `AdSupport.framework` will be enough?

I'd happy to link `GoogleIDFASupport` as documented but I have the build fail when to build for the sumulator.

```
Building for 'iOS-simulator', but linking in object file (/Users/bardiamist/Documents/proj/proj-mobile/ios/Pods/GoogleIDFASupport/Libraries/libAdIdAccessLibrary.a[arm64][2](TAGActualAdIdAccess.o)) built for 'iOS'
```

**Comment by mikehardy** [comment]
Ask upstream I think, happy to take a PR to update the docs. I analyzed it as well as I could.

**Comment by lossen** [comment]
Hello. I got the same error
Mac M1 xcode 15
I followed guide by the link https://rnfirebase.io/analytics/usage/installation/ios#device-identification
But build failed with this line **pod 'GoogleIDFASupport', '~> 3.14.0'**
I see this error 
```
Search path '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.2.sdk/usr/lib/swift/Users/user/Library/Developer/Xcode/DerivedData/projectname-bcrmcqowlnpsjlfrgauidifzyylw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleIDFASupport' not found
Library 'AdIdAccessLibrary' not found
```

When I tried to add **libAdIdAccess.a** manually to **Frameworks, libraries and embedded content**
I got this error 
```
Building for 'iOS-simulator', but linking in object file (/Users/anna/projects/projectname/ios/Pods/GoogleIDFASupport/Libraries/libAdIdAccessLibrary.a[arm64][2](TAGActualAdIdAccess.o)) built for 'iOS'
Linker command failed with exit code 1 (use -v to see invocation)
```

Withoout **pod 'GoogleIDFASupport', '~> 3.14.0'** build works, but I'm not sure if it will work without it.
So what I'm doing wrong? How to solve these build errors?

**Comment by mikehardy** [comment]
I confirm this GoogleIDFASupport pod works on real devices and on x86 emulators, but that it fails to link on Apple Silicon machines when building for Simulator because it apparently has not been updated forever and does not have an arm64 simulator slice

Apparently the "state of the art" has moved on and this pod is abandoned.

Current docs, as you all are referencing above (thank you) -

https://firebase.google.com/docs/analytics/get-started?platform=ios#before_you_begin_2

> (Recommended). [Add the AdSupport framework to your project](https://firebase.google.com/support/guides/analytics-adsupport) to enable additional features such as audiences and campaign attribution.

--> https://firebase.google.com/support/guides/analytics-adsupport which points to

--> https://firebase.google.com/support/guides/analytics-adsupport

It appears that just linking in AdSupport as described in that final link there from the chain of links may be all that is required now.

I've got a PR up in #7637 where you may define 

You can try it by:

- using these patches https://github.com/invertase/react-native-firebase/actions/runs/7993216134?pr=7637
- adding `$RNFirebaseAnalyticsEnableAdSupport = true` to your Podfile

If I get confirmation it works then the final step pre-merge is to update the documentation

**Comment by mikehardy** [comment]
#7637 is merged and released now, documents are updated, new process is documented here:
https://rnfirebase.io/analytics/usage#device-identification
