### ISSUE TITLE
Use getInitialNotification on local notifications created by another SDK

### ISSUE THREAD

**Issue by VincentCATILLON** [invertase/react-native-firebase#703]
### Issue

We are using your package for a while now, and we want to implement custom redirection on notification tap depending on the notification data.

When we got notifications from FCM API, it's working like a charm to retrieve data attached to a notifications using the `getInitialNotification()` method. But on a native local notification created by another SDK/Library (our case), we got data in our main Android activity (`MainActivity` for us), but the `getInitialNotification()` method returns an object without the data given to the main activity.

FYI, this way is working on iOS.

### Environment

1. Application Target Platform: Android

2. Development Operating System: macOS high Sierra

3. Build Tools: Android SDK version 26

4. React Native version: 0.44

5. RNFirebase Version: 2.x

6. Firebase Module: Analytics and Messaging for the moment

### To reproduce

1. Create a local notification natively (or with another library / SDK).
2. Add `System.out.println(getIntent().getExtras());` in your main activity `onCreate()` method
3. Add somewhere (feel free to use a breakpoint instead of the console.log):
```
    messaging()
      .getInitialNotification()
      .then(notification => console.log(notification));
```
3. Then, tap on the notification
4. You should be redirected to your app, but there is a difference between data in the Java logs (step 2) and data in the notification object (step 3)

**Comment by chrisbianca** [comment]
@VincentCATILLON I don't think this is something that we can (or would) realistically support - we have no control over how a third party library might structure their notification data which could in turn break something internally to our library.

@Ehesp @Salakar I'm inclined to close this as won't fix. Thoughts?

**Comment by VincentCATILLON** [comment]
Hi @chrisbianca, firstly, thanks for your answer.

It's not related to the notification structure, the data logged in Android activity has the same structure than the data triggered by Firebase. 

The issue is that the data given in activity are not retrieved in the `getInitialNotification()` as it's done with Firebase notifications.

I'll try to do it with another RN package, but it seems to be a bug (limit ?) or your sdk and should be explicit or fixed IMO. Feel free to contradict me if it's not related to your package perimeter.

Btw, if you have any proposal of why it's not working, it would be appreciated 👍 

Rgds

**Comment by chrisbianca** [comment]
I won't lie, FCM and local notifications is a bit of a mess in `react-native-firebase` - it's something we're aware of and are planning to address here: https://github.com/invertase/react-native-firebase/issues/595

There is some debate over how or even if we should support local notifications, as really we're only aiming to bring the full suite of Firebase functionality to React Native, and whilst Firebase messaging obviously falls within this remit, local notifications don't.  However, we do appreciate that making use of the same system to handle all notifications, whether FCM or local does to some extent make sense.

I'll bear what you've said in mind as we spec everything out...

**Comment by chrisbianca** [comment]
I'm going to close this as the work we're currently doing on #595 should resolve this issue.  Please monitor that for progress.

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)

**Comment by VincentCATILLON** [comment]
Glad to ear it @chrisbianca ! Thx for the improvement 👍
