### ISSUE TITLE
NativeFirebaseError: [auth/unknown] an internal error has occurred. [ internal error encountered.] 

### ISSUE THREAD

**Issue by asim1048** [invertase/react-native-firebase#7033]
I integrated the React Native firebase phone number authentication before 2 days. It was sending the OTP messages to all the numbers. Now after 2 days, it is giving an error

NativeFirebaseError: [auth/unknown] an internal error has occurred. [ internal error encountered.] 

When try to send send OTP. 

Sometimes it sends an OTP, but most of time, it gives that error for Android.

**Comment by mikehardy** [comment]
Hi there! You have removed the template and any indication of how to reproduce the error, so I will close this as there is no good way to answer a largely unspecified question/problem.

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

You may find more information if you use `adb logcat` to watch the logs

**Comment by asim1048** [comment]
async function signInWithPhoneNumber(phoneNumber) {
    const confirmation = await auth().signInWithPhoneNumber(phoneNumber);
    setConfirm(confirmation);
  }
This works fine sometimes, and sometimes gives error 
nativefirebaseerror: [auth/unknown] an internal error has occurred. [ internal error encountered.] 

Hybrid behavior. My Integration is fully according to firebase documentation.

**Comment by WidgetPMT** [comment]
@asim1048 Please check my comment if you not yet found it.
