### ISSUE TITLE
[🐛] Dynamic Links Safari cannot open the page because the address is invalid.

### ISSUE THREAD

**Issue by elmcapp** [invertase/react-native-firebase#7036]
## Issue

I am experiencing an issue with `@react-native-firebase` library. Specifically, I am using the `dynamic-links` module and it doesn't seem to be working as expected.

### Expected Behavior
When I create a dynamic link and tap on it, it should redirect me to the app and navigate to the specified screen.

### Actual Behavior
However, when I tap on the dynamic link, it doesn't redirect me to the app. Instead, I see the following error message:
Safari cannot open the page because the address is invalid.

### Steps to Reproduce
Here are the steps to reproduce the issue:
1. Create a dynamic link using the instructions provided on your website.
2. Copy the link and open it on the iOS simulator.
3. The simulator shows the error message mentioned above and the app doesn't open.

#### `package.json`:

```json
{
  "@react-native-firebase/app": "^17.4.1",
  "@react-native-firebase/dynamic-links": "^17.4.2",
  "@react-native-firebase/analytics": "^17.4.1",
  "react": "18.2.0",
  "react-native": "0.71.5"
}
```

### My question
Do dynamic links work on iOS simulator or only on real device? I only have 1 real device to test on so I can't confirm if the issue is only with simulator or with all devices or if I am only having luck with my real device.

**Comment by fobos531** [comment]
PLease see https://rnfirebase.io/dynamic-links/usage#application-is-not-installed-on-device

**Comment by mikehardy** [comment]
I recognize the `^` means you are likely getting a matching set, but do not mix and match versions, this is incorrect:

```

  "@react-native-firebase/app": "^17.4.1",
  "@react-native-firebase/dynamic-links": "^17.4.2",
  "@react-native-firebase/analytics": "^17.4.1",
```

https://invertase.io/blog/react-native-firebase-versioning

Should all be the same, in this case 17.4.2

@fobos531 thank you! - the note in that link is exactly on target, this is not an issue
