### ISSUE TITLE
[🐛] Off not really unsubscribing from realtime updates

### ISSUE THREAD

**Issue by moxen-dev** [invertase/react-native-firebase#7042]
## Issue

The issue is happening in a app with multiple realtime streams. Once subscribed in one realtime database to listen to changes, even calling the `off` function does not prevent from listen to new changes.

https://user-images.githubusercontent.com/93292309/231828333-88f23977-7bfa-47dc-a19c-38cda5145ea0.mov

---

## Project Files

_I am leaving console logs on the code blocks to match with the video._

### Typescript

<details><summary>Click To Expand</summary>
<p>

#### `listenOffers.ts`:

```typescript
export default function listenCurrentOffer({ liveId, onValueChange }: IListenAuction): IListenerUnsubscriber {
  const reference = `lives/${liveId}/currentOffer`;
  const listener = database().ref(reference).on('value', onValueChange);
  return () => database().ref(reference).off('value', listener);
}
```

#### `setupLive.ts`:

I am using zustand, and for those unfamiliar, it is represented here by the `set` function that save states to my global store. What I doing in the code below is turning on a listener, saving their unsubscribe function and returning a bigger unsubscribe function with calls for this and other unsubscribers and clean the store. I am not pasting the full code to focus on what really matters.

```typescript
async function setupLive({ liveId, role, ownerId }) {
    const unsubscribeFromOffers = listenCurrentOffer({ liveId, onValueChange });

    return function unsubscribe() {
      const offerUnsubscribe = unsubscribeFromOffers();
      console.log('🐛  offerUnsubscribe', offerUnsubscribe);

      set({
        currentOffer: {} as IAuction,
      });
    };

    async function onValueChange(snapshot: any): Promise<void> {
      console.log("🐛  onValueChange", liveId, snapshot.val());
      const data: IAuction = snapshot.val();
      set({ currentOffer: data });
    }
  },
```

#### `Live.tsx`:

This is part of the react component. It calls the setup on first effect and on unmount, calls the unsubscribe function.

```tsx
  useEffect(() => {
    let unsubscribe = new Function();
    async function setup() {
      unsubscribe = await setupLive({ liveId, ownerId, role });
    }

    setup().then(() => {
      setLoading(false);
    });

    return () => {
      unsubscribe();
    };
  }, []);
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 58.50 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.volta/tools/image/node/18.15.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.5.0 - ~/.volta/tools/image/node/18.15.0/bin/npm
    Watchman: 2023.03.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.6 => 0.71.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `17.4`
- **`Firebase` module(s) you're using that has the issue:**
  - `Realtime`
- **Are you using `TypeScript`?**
  - `Y 4.9.5`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hmm, this one may prove difficult.

> I am leaving console logs on the code blocks to match with the video.

I don't see them? 🤔 And unfortunately videos are not a valid way to demonstrate + reproduce a problem

I have in the past had difficulty with the ordering of events firing which is why this test is `xit` (meaning "do not run") vs `it` which would run it, but I had no problem with the subscriptions and the unsubscriptions:

https://github.com/invertase/react-native-firebase/blob/4eb336b4bd27d1f3beafbcdd4ab1e8bbab234321/packages/database/e2e/query/on.e2e.js#L95-L108

If you can produce a code snippet that demonstrates the failure and is a *minimal* and *complete* example, we can investigate: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by moxen-dev** [comment]
Thanks for answering, I will switch to mode "the problem is on my side" and understand how can I iterate over the order. I am firing multiple "offs" in sequence. If I do not find success I will provide a minimal example (I still need to get used to this).

In the video, I highlight the return of the off function. At the end of the path returned, there are some weird characters. Can you confirm this is what is expected?

It is the one ending with `/firebasepath$[DEFAULT]${}$27$value`.
