### ISSUE TITLE
Problem with integration of react-native-firebase and react-native-google-signin

### ISSUE THREAD

**Issue by akobylianskyi** [invertase/react-native-firebase#705]
I have the problem with integration _react-native-google-signin_ and _react-native-firebase_ in my project. Everything was ok before I add cocoapods with firebase dependencies. _react-native-google-signin_ module was added manually before and after adding _firebase_ with pods iOS project started failing. 
- After that I tried to add _google-signin_ module using pods but the problem was not solved. I have noticed that _react-native-google-signin_ uses old versions of the Firebase. 
- Adding 'GoogleSignIn' pod instead of' Google/SignIn' should solve version conflict but _google-signin_ module still not working after such replacement. 

I understand that the problem is more related to _google-signin_ module but in the react-native-firebase documentation we have recommendation to use it. Any ideas?

**Podfile**

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LibraryTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LibraryTest
  pod 'GoogleSignIn'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'LibraryTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LibraryTest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LibraryTest-tvOS

  target 'LibraryTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```
**Environment**

Application Target Platform: iOS
Development Operating System: macOS Sierra
React Native version: 0.51.0
RNFirebase Version: 3.2.0
Firebase Module: database

**Comment by Benjamin-Dewey** [comment]
@akobylianskyi  see my [reply](https://github.com/invertase/react-native-firebase/issues/689#issuecomment-353742631).
