### ISSUE TITLE
React-native Firebase Push Notifications not works in iOS on development and release modes

### ISSUE THREAD

**Issue by DeepakSharma04** [invertase/react-native-firebase#7074]
React-native firebase push notifications works fine in debug mode on iOS physical devices. But when i check on development or release modes **(means when i created Archive for development or app store connect)** it's not working.please help, why it's not working and i used APNs Authentication Key not APNs Certificates for notifications.

And also Certificates, Identifiers & Profiles of apple developer accounts which things or setup need to be verify and check.

`"@react-native-firebase/app": "^17.3.2",

"@react-native-firebase/messaging": "^17.3.2",`

**Comment by brunofrigeri-lc** [comment]
Hey @DeepakSharma04 can you share your `iOS` configuration? I'm having the opposite issue, while my Push Notifications are working for Release mode but not in debug mode, I'm trying to understand why.

**Comment by DeepakSharma04** [comment]
> 

Hi @brunofrigeri-lc  Please check .

[`"react": "17.0.2",
  "react-dom": "^18.0.0",
  "react-native": "0.68.2",`](url)

[` "@react-native-firebase/app": "^17.3.2",
    "@react-native-firebase/messaging": "^17.3.2",`](url)


App.js file

```
React.useEffect(() => {
    // Fetching firebase token & Request permissions (required for iOS & Android API Level above 12)
    async function fetchFirebaseToken() {
      await notifee.requestPermission();
      const FirebaseFcmToken = await messaging().getToken();
      console.log('FirebaseFcmToken--', FirebaseFcmToken)
      if (FirebaseFcmToken != null) {
        await AsyncStorage.setItem("fcmToken", FirebaseFcmToken);
      }
      const fireBasePayloadData = messaging().onMessage(async remoteMessage => {
        displayFirebaseNotifications(remoteMessage);
        return remoteMessage
      });
    }
    // Fetching initial notifications of notifee for closed/killed state
    async function fetchInitialNotifications() {
      const initialNotification = await notifee.getInitialNotification();
      if (initialNotification != null) {
        let validateJson = JSON.stringify(initialNotification)
        let validateObject = JSON.parse(validateJson);
        await notifee.cancelNotification(validateObject.notification.id);
        await notifee.cancelDisplayedNotification(validateObject.notification.id);
      }
    }

    fetchFirebaseToken();
    fetchInitialNotifications();
  }, []);
```


  /*---Display foreground firebase push notification---*/
 ```
 const displayFirebaseNotifications = async (remoteMessage) => {
    //  console.log('remoteMessage--on message--', remoteMessage)
    const channelId = await notifee.createChannel({
      id: 'default',
      name: 'Default Channel',
      badge: false,
    });
    try {
      await notifee.displayNotification({
        title: remoteMessage.notification.title,
        body: remoteMessage.data.notify_message,
        android: {
          channelId,
          color: "#3DA6D7",
          smallIcon: 'faveo_notification_icon',
          importance: AndroidImportance.HIGH,
          pressAction: {
            id: 'default',
          },
        },
        data: {
          'scenario': remoteMessage.data.module,
          'scenarioId': remoteMessage.data.mobile_scenario_id,
          'notificationId': remoteMessage.data.id
        }
      })
    } catch (e) {
      console.log(e);
    }
  }
```

AppDelegate.m file 
`#import <Firebase.h>`
` [FIRApp configure];   `. // added in application didFinishLaunchingWithOptions method

**Comment by 2sem** [comment]
17.4.2
I can see token.
however onMessage never fired.
Android works
this is weird...

**Comment by DeepakSharma04** [comment]
> Hey @DeepakSharma04 can you share your `iOS` configuration? I'm having the opposite issue, while my Push Notifications are working for Release mode but not in debug mode, I'm trying to understand why.

Hi @brunofrigeri-lc , can you explain how your notifications is works on release mode.

**Comment by 2sem** [comment]
Oh I used the wrong key.
It was a key to connect to appstoreconnect.
I replaced the key and it works well.

**Comment by DeepakSharma04** [comment]
> Oh I used the wrong key. It was a key to connect to appstoreconnect. I replaced the key and it works well.

Hi @2sem , which modes your notifications is working - debug, development and release.

**Comment by brunofrigeri-lc** [comment]
hey @DeepakSharma04 . I don't know what is the discrepancy between debug and release in my app. But currently I cannot test receiving push notifications on `debug` and in `release` it works just fine. The settings are done exactly how the documentation tell us to do, so ... hard to know what is happening.

**Comment by DeepakSharma04** [comment]
> hey @DeepakSharma04 . I don't know what is the discrepancy between debug and release in my app. But currently I cannot test receiving push notifications on `debug` and in `release` it works just fine. The settings are done exactly how the documentation tell us to do, so ... hard to know what is happening.

Ok , let me check it again on release mode may be works.

**Comment by ProgramadorLeandroSantos** [comment]
> hey @DeepakSharma04 . I don't know what is the discrepancy between debug and release in my app. But currently I cannot test receiving push notifications on `debug` and in `release` it works just fine. The settings are done exactly how the documentation tell us to do, so ... hard to know what is happening.

Hello Bruno, how are you?  can you Share with us more details about your project settings?

**Comment by DeepakSharma04** [comment]
Hi Everyone , I checked the debug , development and release modes of notification in iOS (real device). Finally , all modes are working fine .

**Comment by ProgramadorLeandroSantos** [comment]
> Hi Everyone , I checked the debug , development and release modes of notification in iOS (real device). Finally , all modes are working fine .

nice!! how do you fixed it?

**Comment by DeepakSharma04** [comment]
> > Hi Everyone , I checked the debug , development and release modes of notification in iOS (real device). Finally , all modes are working fine .
> 
> nice!! how do you fixed it?

I grow through the all steps again and check the config of iOS mentioned on ReactNative Firebase Documentation.
But in my case i added wrong jsmain bundler file and for release mode i used test flight .

**Comment by ProgramadorLeandroSantos** [comment]
> > > Hi Everyone , I checked the debug , development and release modes of notification in iOS (real device). Finally , all modes are working fine .
> > 
> > 
> > nice!! how do you fixed it?
> 
> I go through the all steps again and check the config of iOS mentioned on ReactNative Firebase Documentation. But in my case i added wrong jsmain bundler file and for release mode i used test flight .

Thanks for sahe the news, but I would like to know where is jsmain bundler and the line of code that was wrong :)

**Comment by DeepakSharma04** [comment]
> > > > Hi Everyone , I checked the debug , development and release modes of notification in iOS (real device). Finally , all modes are working fine .
> > > 
> > > 
> > > nice!! how do you fixed it?
> > 
> > 
> > I go through the all steps again and check the config of iOS mentioned on ReactNative Firebase Documentation. But in my case i added wrong jsmain bundler file and for release mode i used test flight .
> 
> Thanks for share the news, but I would like to know where is jsmain bundler and the line of code that was wrong :)

I'm facing this issue in my project, so i added it.- https://stackoverflow.com/questions/71825697/main-jsbundle-does-not-exist-this-must-be-a-bug-with.

**Comment by ProgramadorLeandroSantos** [comment]
> > > > > Hi Everyone , I checked the debug , development and release modes of notification in iOS (real device). Finally , all modes are working fine .
> > > > 
> > > > 
> > > > nice!! how do you fixed it?
> > > 
> > > 
> > > I go through the all steps again and check the config of iOS mentioned on ReactNative Firebase Documentation. But in my case i added wrong jsmain bundler file and for release mode i used test flight .
> > 
> > 
> > Thanks for share the news, but I would like to know where is jsmain bundler and the line of code that was wrong :)
> 
> I'm facing this issue in my project, so i added it.- https://stackoverflow.com/questions/71825697/main-jsbundle-does-not-exist-this-must-be-a-bug-with.

Thanks for your help and time.

**Comment by ProgramadorLeandroSantos** [comment]
@DeepakSharma04  I am facing this error => `Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0xa160f6d4b9c1e7fa'`

I'm trying to build in development environment (physical device). My App is crashing when i try to open it by touching the notification

**Comment by brunofrigeri-lc** [comment]
@ProgramadorLeandroSantos I opened an issue, you can check [here](https://github.com/invertase/react-native-firebase/issues/7061)

**Comment by DeepakSharma04** [comment]
This Issue is closed as I checked , Notifications in development and release modes are working fine.

**Comment by harishMankar** [comment]
i have make all the configuration for ios push notification but it is not working, im getting the token but while testing, the notification not get received and 


useEffect(() => {
   notificationListener();
});

export async function notificationListener() {

  messaging().onNotificationOpenedApp(remoteMessage => {
    console.log(
      'Notification caused app to open from background state',
      remoteMessage.notification,
    );
    console.log("background state", remoteMessage.notification);
  });


  messaging()
    .getInitialNotification()
    .then(remoteMessage => {
      if(remoteMessage) {
        console.log(
          'Notification caused app to open from quit state',
          remoteMessage.notification,
        );
        console.log("remote message", remoteMessage.notification);
      }
    }).catch(error => {
      console.log("error got",error);
    })
}

this function is not invoking after sending the notification please guide me, Thank you.

**Comment by josue-rocha0809** [comment]
I change key "developemt" to "production" and it works in release
files: ios/app/app.entitlements

<dict>
	<key>aps-environment</key>
	<string>production</string>
</dict>

**Comment by mikehardy** [comment]
@josue-rocha0809 I believe Xcode is supposed to handle that for you automatically?

https://developer.apple.com/documentation/bundleresources/entitlements/aps-environment

> Xcode sets the value of the entitlement based on your app’s current provisioning profile. For example, if you’re using a development provisioning profile, Xcode sets the value to development. Production provisioning profile and [Prerelease Versions and Beta Testers](https://developer.apple.com/documentation/AppStoreConnectAPI/prerelease-versions-and-beta-testers) use production. These default settings can be modified. The development environment is also referred to as the sandbox environment.

If you have some build processes outside of Xcode, then I suppose yes, you may need to change it manually - I don't believe this is a common thing people need to do though

**Comment by ahmetilhn** [comment]
IOS push notification not working on simulator and REAL DEVICE(with development). Publish on testflight then test it.
