### ISSUE TITLE
🔥 [🐛] Storage unaffected by "android_bypass_emulator_url_remap"

### ISSUE THREAD

**Issue by bcye** [invertase/react-native-firebase#7076]
## Issue

The storage module is not affected by the "android_bypass_emulator_url_remap" flag. I'm using the emulator using the appropriate functions for 4 services.

In my metro log the following message appears, but just for storage, not for any other services:
`Mapping storage host to "10.0.2.2" for android emulators. Use real IP on real devices.`

The firestore and auth emulator are working fine. I configure the emulator as following:
```js
firestore().useEmulator("localhost", 8080);
auth().useEmulator("http://localhost:9099");
storage().useEmulator("localhost", 9199);
```

My firebase.json
```json
{
  "react-native": {
    "android_bypass_emulator_url_remap": true
  }
}
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "android_bypass_emulator_url_remap": true
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 740.97 MB / 15.02 GB
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.10.31.00 - /home/linuxbrew/.linuxbrew/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: ^0.70.5 => 0.70.5 
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^16.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `storage`
- **Are you using `TypeScript`?**
  - `Y` & `4.8.4`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by danielkv** [comment]
These issues are never getting solved. it's kinda annoying I'm also having this problem, but the support to this lib is too bad

**Comment by mikehardy** [comment]
> These issues are never getting solved. it's kinda annoying I'm also having this problem, but the support to this lib is too bad

@danielkv I'll note that you have not contributed anything to this open source repository

You may thank @PedroDuarte536 for PR #7326 who has graciously contributed his time to fix this issue for you
