### ISSUE TITLE
[🐛] 🔥 iOS app crashes in simulator when handleCodeInApp is false or not set in actionCodeSettings

### ISSUE THREAD

**Issue by skulljuice** [invertase/react-native-firebase#7078]
## Issue

Describe your issue here

When using auth().sendSignInLinkToEmail() in a React Native Firebase project on iOS, the app crashes in the simulator when handleCodeInApp is set to false or not included in the actionCodeSettings object. The error occurs when sendSignInLinkToEmail() is called and the app tries to open the authentication link in the browser instead of handling it in the app.

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/app": "^17.4.0",
 "@react-native-firebase/auth": "^17.4.0",
 "expo": "~48.0.11",
 "react-native": "0.71.6",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  -  ^17.4.0
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - N

</p>
</details>

---

Steps to reproduce:

- Create a new React Native Firebase project in expo and set up Firebase Authentication.
- Add code to send a sign-in link to the user's email with sendSignInLinkToEmail().
- Set handleCodeInApp to false or do not include it in the actionCodeSettings object.
- Run the app in the iOS simulator and trigger the sign-in flow.

Expected result:
The user should be able to receive and click the sign-in link in the email, which should open the app and complete the sign-in flow successfully.

Actual result:
The app crashes in the simulator when the sign-in link is clicked in the email. The error occurs when the app tries to open the authentication link in the browser instead of handling it in the app.

Sample code to reproduce the issue:

```
const actionCodeSettings = {
  url: url,
  handleCodeInApp: false
};

await auth().sendSignInLinkToEmail(email, actionCodeSettings);

```
Additional information:

- React Native Firebase version: ^17.4.0
- iOS version: 16.4
- Simulator version: 14.3 (994)

**Comment by aureliopetrone** [comment]
This may be related somehow to #7080
