### ISSUE TITLE
Not able to build IOS after FCM setup

### ISSUE THREAD

**Issue by NitinSinghElegant** [invertase/react-native-firebase#7079]
I am using react native 0.71.3 version. I set up FCM in android first that is working fine. When I set up the same in IOS. It is giving me the following error `RCTAp. I am also including SS for you to look over.

<img width="1440" alt="Screenshot 2023-04-27 at 4 45 39 PM" src="https://user-images.githubusercontent.com/130339696/234846506-57785af4-14e5-46af-9f3c-0efabde0eb67.png">

<img width="1440" alt="Screenshot 2023-04-26 at 2 56 33 PM" src="https://user-images.githubusercontent.com/130339696/234760430-c5d1419b-7885-4d23-b315-4e2b1dfbaf24.png">

**Comment by HCSharma** [comment]
Facing the same issue

**Comment by andreaSimonePorceddu** [comment]
Same issue with version 0.70.8
