### ISSUE TITLE
Docs & code inconsistency?

### ISSUE THREAD

**Issue by atlanteh** [invertase/react-native-firebase#708]
The docs say to add:
```compile "com.google.firebase:firebase-core:11.6.0"```

However in code I see that the firebase version is [11.4.2](https://github.com/invertase/react-native-firebase/blob/master/android/build.gradle#L2).

Is this a mistake? Which one should I use?

**Comment by Ehesp** [comment]
Both are technically "supported", we are trying to keep up with releases across web/android/ios where we can.

Basically if you use a newer version (such as the new 11.8.0) which has a new feature or change, we may not have implemented this so you'll get an error. 

You can check the change log here: https://firebase.google.com/support/release-notes/android
