### ISSUE TITLE
[🐛]Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication().  A frequent cause of the error is that the application entry file path is incorrect.

### ISSUE THREAD

**Issue by developeromI89** [invertase/react-native-firebase#7089]
## Issue
Getting below issue in my project iOs when trying to call crashlytics().log('test log')

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happe

 crashlytics().log('asdasdas')

import crashlytics from '@react-native-firebase/crashlytics';

React-native version : 0.70.6

no issue in import but as soon as I try to use any functions from crashlytics() package I am getting invariant violation issue.

Getting below issue in my project iOs when trying to call crashlytics().log('test log')

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect.

Running from Xcode on Real Device 

What I tried so far.

1.Delete node modules and install everything
2.delete pods , podfile.lock and tried
3.close metro bundler and delete pod delete node module 

Also tried solution  mentioned here but still its not working 
[https://github.com/invertase/react-native-firebase/issues/6929](https://github.com/invertase/react-native-firebase/issues/6929)

---

## Project Files

ios pdofile 
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target ‘MyProjectName’ do
//other pods
  pod 'nRFMeshProvision'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  pod 'Firebase/Analytics'
  config = use_native_modules!
  flags = get_default_flags()
  use_frameworks! :linkage => :static
  use_modular_headers!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'
  target 'MyProjectNameTests' do
    inherit! :search_paths
    # Pods for testing
  end

 
end

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

react: 18.1.0 => 18.1.0 
 react-native: 0.70.6 => 0.70.6 

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
 
- ** - @react-native-firebase/crashlytics": "^17.4.3",

 
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y'

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by developeromI89** [comment]
Fixed .
So issue is we have 2 AppDelegte.m files in our project dont know why .
The configuration I have added in one file but Xcode taking reference from another file due to which it gives Invariant  Violation.

after adding configuration to second file methods and functions worked properly.

**Comment by mock2019** [comment]
@developeromI89 I am facing the same issue for react native upgrade from 0.68 to 0.70..

 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes

Would you please suggest the fix..
