### ISSUE TITLE
cannot read property 'addListener' of undefined

### ISSUE THREAD

**Issue by neverlan** [invertase/react-native-firebase#709]
### Issue

After upgrading from 2.x to 3.x, I get "cannot read property 'addListener' of undefined" from this line in the onTokenRefresh func:

 onTokenRefresh(listener) {
    const rnListener = this._eventEmitter.addListener(EVENT_TYPE.RefreshToken, listener);
    return () => rnListener.remove();
  }

Worked as expected before.

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode 9.1

4. React Native version: 0.50

5. RNFirebase Version: 3.2.0

6. Firebase Module: Messaging

**Comment by Ehesp** [comment]
Can we see your code usage?

**Comment by chrisbianca** [comment]
Closing due to lack of response.
