### ISSUE TITLE
Error: [messaging/unknown] The operation couldn’t be completed. No APNS token specified before fetching FCM Token

### ISSUE THREAD

**Issue by markjoseultra** [invertase/react-native-firebase#7108]
Hi Team 

const token = await messaging().getToken();
This function is not returning the FCM token on javascript side

<img width="564" alt="image" src="https://user-images.githubusercontent.com/49055288/236999905-d5fa1355-1211-40f5-b0bb-9325e5ffb5a4.png">

I tried running directly on xcode and it generates the FCM token

<img width="450" alt="image" src="https://user-images.githubusercontent.com/49055288/237000006-4018164a-87c9-4d70-9524-61927ccde88c.png">

**Comment by snowdigital** [comment]
Check changelog

**Comment by markjoseultra** [comment]
I already added APNS key on Firebase
