### ISSUE TITLE
Batch init error _firebase2.default.firestore.batch is not a function

### ISSUE THREAD

**Issue by 3210jr** [invertase/react-native-firebase#711]
### Issue

Hey guys,
I am trying to run a batch update using the line `const batch = firebase.firestore.batch();` but I am getting the following error:

```
_firebase2.default.firestore.batch is not a function
acceptTransportJobQuote
    require.js:68:3
Object.onPress
    error-guard.js:61:6
<unknown>
    Alert.js:145:53
MessageQueue.__invokeCallback
    MessageQueue.js:354:13
<unknown>
    MessageQueue.js:129:11
MessageQueue.__guard
    MessageQueue.js:269:6
MessageQueue.invokeCallbackAndReturnFlushedQueue
    MessageQueue.js:128:9
<unknown>
    debuggerWorker.js:72:58

```

Thanks!

### Environment

1. Application Target Platform: Android

2. Development Operating System: macOS Sierra

3. Build Tools: 

4. React Native version: 0.49.5

5. RNFirebase Version: 

6. Firebase Module: 3.2.0

**Comment by Ehesp** [comment]
Transactions are not yet supported in RNFirebase. They're quite complex as they need custom implementation on both Android & iOS. It's one of the top on our priority list though, we'll keep you updated.

**Comment by Ehesp** [comment]
Woops, I was wrong. `batch` is supported, but you're calling it incorrectly:

```js
firebase.firestore.batch() // wrong
firebase.firestore().batch() // correct
```

**Comment by 3210jr** [comment]
Thanks a lot. Also really good to know about transactions coming soon!
