### ISSUE TITLE
[📚] configuration guide of Notification Image for Expo Prebuild

### ISSUE THREAD

**Issue by chhornponleu** [invertase/react-native-firebase#7113]
## Documentation Feedback

Need guide to configure Notification with Image working with Expo Configs (Prebuild). 

Related links: https://rnfirebase.io/messaging/ios-notification-images

**Comment by chhornponleu** [comment]
found the way. just manual add notification scheme (same as RN) as mentioned in the doc

**Comment by chhornponleu** [comment]
No, I still need it for was build

**Comment by whentao** [comment]
Is there any steps I can do this for expo managed flow? Or I have to change to bare flow to include notification image?

**Comment by mikehardy** [comment]
perhaps notifee.app would work?
