### ISSUE TITLE
Do I need the whole Firebase SDK even if I'm using only some modules?

### ISSUE THREAD

**Issue by JCMais** [invertase/react-native-firebase#712]
I've correctly configured this package in the app I'm working on, without cocoapods, but from what I can see, it's necessary to have almost the whole Firebase SDK installed, is that really necessary?

The only module I could remove was the Invites one.

**Comment by chrisbianca** [comment]
@JCMais It certainly isn't with Cocoapods - you just need to add the pods that you require.  Unfortunately, we don't recommend the manual download approach (and neither do Google/Firebase) so haven't explored what this might mean.

Please create a feature request at https://react-native-firebase.canny.io/feature-requests if you'd like us to consider adding support for this, or alternatively consider investigating this yourself and submit a PR - it certainly should be possible, but I'd imagine it will need some fiddling with header and framework search paths.
