### ISSUE TITLE
[🐛] react native fails with 'react/bridging/CallbackWrapper.h' file not found after following getting started guide

### ISSUE THREAD

**Issue by victororlyk** [invertase/react-native-firebase#7128]
## Issue

I am trying to setup react native and firebase push notifications, I am following this guide. https://rnfirebase.io/messaging/usage
after `pod install` I am always getting failing build. 

It fails most often with 
```
'react/bridging/CallbackWrapper.h' file not found
```
If i will remove everything from this guide getting started(https://rnfirebase.io/) , the build will work 

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest",
    "start::clearCache": "yarn start --reset-cache"
  },
  "dependencies": {
    "@hookform/resolvers": "^3.0.0",
    "@react-native-async-storage/async-storage": "^1.17.12",
    "@react-native-firebase/app": "^17.4.2",
    "@react-native-firebase/messaging": "^17.4.2",
    "@react-native-picker/picker": "^2.4.9",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@shopify/react-native-skia": "^0.1.185",
    "@tanstack/react-query": "^4.28.0",
    "axios": "^1.3.4",
    "classnames": "^2.3.2",
    "d3": "^7.8.4",
    "date-fns": "^2.29.3",
    "jotai": "^2.0.3",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-hook-form": "^7.43.9",
    "react-native": "^0.71.0",
    "react-native-biometrics": "^3.0.1",
    "react-native-email-link": "^1.14.5",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-haptic-feedback": "^2.0.2",
    "react-native-localize": "^2.2.6",
    "react-native-plaid-link-sdk": "^10.1.0",
    "react-native-reanimated": "^3.1.0",
    "react-native-restart": "^0.0.27",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-splash-screen": "^3.3.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-webview": "^12.0.2",
    "zod": "^3.21.4"
  },
  "devDependencies": {
    "@babel/core": "^7.21.4",
    "@babel/preset-env": "^7.21.4",
    "@babel/runtime": "^7.21.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@total-typescript/ts-reset": "^0.4.2",
    "@tsconfig/react-native": "^2.0.2",
    "@types/d3": "^7.4.0",
    "@types/jest": "^29.5.0",
    "@types/react": "^18.0.24",
    "@types/react-native-vector-icons": "^6.4.13",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.5.0",
    "babel-plugin-module-resolver": "^5.0.0",
    "eslint": "^8.37.0",
    "eslint-plugin-ft-flow": "^2.0.3",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "jest": "^29.5.0",
    "metro-react-native-babel-preset": "0.73.8",
    "prettier": "^2.8.7",
    "prettier-plugin-tailwindcss": "^0.2.7",
    "react-native-dotenv": "^3.4.8",
    "react-test-renderer": "18.2.0",
    "tailwindcss": "^3.3.1",
    "typescript": "^5.0.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'subsidio' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
#    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Firebase
#  use_frameworks! :linkage => :dynamic # Change from static to dynamic
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  # Add the Firebase pods you need below this line
  pod 'Firebase/Core'
  # Add other Firebase pods if required

  target 'subsidioTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

```

#### `AppDelegate.mm`:

```objc
#import "AppDelegate.h"
#import <Firebase.h> //firebase

/// Deep linking
#import <React/RCTLinkingManager.h>
#import <React/RCTBundleURLProvider.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure]; //firebase
  self.moduleName = @"subsidio";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feature is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  return true;
}

/// Deep linking
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}

@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `17.4.2`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/app`
  - `@react-native-firebase/messaging`
- **Are you using `TypeScript`?**
  - `Yes` & `5.0.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

here is error file
[Build app_2023-05-22T13-36-15.txt](https://github.com/invertase/react-native-firebase/files/11530035/Build.app_2023-05-22T13-36-15.txt)

**Comment by atuldhakaSB** [comment]
Hi, facing the same issue when upgrading rn version from 70.6 to 76.5, using the latest version of firebase 21.7.1, also using expo, expo-module-core for some expo libraries in bare react native project

**Comment by mikehardy** [comment]
This hints at some fundamental build problem that no one else is experiencing, so the question is why @atuldhakaSB ? 

Given: since no one else is experiencing this, it must be project-specific.

More context: here's an example of a project that does work, if you run this script it generates the appropriate AppDelegate and Podfile edits needed for react-native-firebase to build, you may read the script (all things it does are commented!) to see what the basic edits are for installing react-native-firebase: https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

My best guess is that you've sliced in the AppDelegate edit in the wrong spot so it's messing up the ifdefs in there and blowing up the compile completely. 

you mentioned you are on react-native 0.76 so here's the deep link to those specific required edits for AppDelegate.mm (react-native 0.77 has ported AppDelegate to Swift so it looks just a little different...)

https://github.com/mikehardy/rnfbdemo/blob/04b101e880c4c79943d6ec12cebbc7f04c70c72e/make-demo.sh#L93-L96

**Comment by atuldhakaSB** [comment]
initially i was using the modular_headers => true for the firebase dependency in my pod file but as i have gone through your threads i have removed them and now getting this error, i have cross checked all the documentation from firebase docs, 

the error is : - [!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `FirebaseAuth` depends upon `FirebaseAuthInterop`, `FirebaseAppCheckInterop`, `FirebaseCore`, `FirebaseCoreExtension`, `GoogleUtilities`, and `RecaptchaInterop`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

The Swift pod `FirebaseCrashlytics` depends upon `FirebaseCore`, `FirebaseInstallations`, `GoogleDataTransport`, `GoogleUtilities`, and `nanopb`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

The Swift pod `FirebaseFirestore` depends upon `FirebaseCore`, `FirebaseCoreExtension`, and `FirebaseFirestoreInternal`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

The Swift pod `FirebaseRemoteConfig` depends upon `FirebaseABTesting`, `FirebaseCore`, `FirebaseInstallations`, and `GoogleUtilities`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

The Swift pod `FirebaseSessions` depends upon `FirebaseCore`, `FirebaseCoreExtension`, `FirebaseInstallations`, `GoogleDataTransport`, `GoogleUtilities`, and `nanopb`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.



here is my podfile : - Apologies for some commented code 

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
# Resolve react_native_pods.rb with node to allow for hoisting
 def node_require(script)
   # Resolve script with node to allow for hoisting
   require Pod::Executable.execute_command('node', ['-p',
     "require.resolve(
       '#{script}',
       {paths: [process.argv[1]]},
     )", __dir__]).strip
 end

# Use it to require both react-native's and this package's scripts:
 node_require('react-native/scripts/react_native_pods.rb')
 node_require('react-native-permissions/scripts/setup.rb')

#  podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}
#  ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
 
 setup_permissions([
    "AppTrackingTransparency",
    "Camera",
    "LocationAccuracy",
    "LocationAlways",
    "LocationWhenInUse",
    "MediaLibrary",
    "Notifications",
    "PhotoLibrary",
    "PhotoLibraryAddOnly",
    "StoreKit"
])

  platform :ios, min_ios_version_supported
  prepare_react_native_project!
   
  linkage = ENV['USE_FRAMEWORKS']
  if linkage != nil
    Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
    use_frameworks! :linkage => linkage.to_sym
  end

# use_frameworks! :linkage => :static
# $RNFirebaseAsStaticFramework = true
# $FirebaseSDKVersion = '10.6.0'

project 'ballebaazi', {
  'devDebug' => :debug,
  'qaDebug' => :debug,
  'preDebug' => :debug,
  'Debug' => :debug,
  'Release' => :release,
  'devRelease' => :release,
  'qaRelease'=> :release,
  'preRelease'=> :release,
}

target 'ballebaazi' do

  use_expo_modules!(exclude: ['expo-splash-screen'])
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

  target 'ballebaaziTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    ) 

    installer.pods_project.targets.each do |target|
      # if target.name == 'BoringSSL-GRPC'
      #   target.source_build_phase.files.each do |file|
      #     if file.settings && file.settings['COMPILER_FLAGS']
      #       flags = file.settings['COMPILER_FLAGS'].split
      #       flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
      #       file.settings['COMPILER_FLAGS'] = flags.join(' ')
      #     end
      #   end
      # end
      # if target.name == 'HPWebKit'
      #   `xcrun -sdk iphoneos bitcode_strip -r Pods/HPWebKit/Frameworks/HaptikWebKit/HPWebKit.xcframework/ios-arm64/HPWebKit.framework/HPWebKit -o Pods/HPWebKit/Frameworks/HaptikWebKit/HPWebKit.xcframework/ios-arm64/HPWebKit.framework/HPWebKit`
      # end

      target.build_configurations.each do |config|
        # config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
        # config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Private/React-bridging/react/bridging" '
        # config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_CONFIGURATION_BUILD_DIR)/React-bridging/react_bridging.framework/Headers" '
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
        if target.name == 'Sentry'
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
        end
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] < '12.4'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
        end
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
      end
    end

    # installer.pods_project.build_configurations.each do |config|
    #   config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    # end

    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings["DEVELOPMENT_TEAM"] = "RWGLSYDNDS"
        end
      end
    end
    fuse_path = "./Pods/HyperSDK/Fuse.rb"
     clean_assets = false # Pass true to re-download all the assets
     if File.exist?(fuse_path)
       if system("ruby", fuse_path.to_s, clean_assets.to_s)
       end
     end
  end

 # react-native-permissions
  # permissions_path = '../node_modules/react-native-permissions/ios'
  # pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  # pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"

  # Add the correct ReactCommon dependency:
  # pod 'ReactCommon', :path => '../node_modules/react-native/ReactCommon', :modular_headers => false

  # pod 'Firebase', :modular_headers => true
  # pod 'FirebaseCore', :modular_headers => true
  # pod 'FirebaseCoreInternal', :modular_headers => true
  # pod 'GoogleUtilities', :modular_headers => true
  # pod 'FirebaseCoreExtension', :modular_headers => true
  # pod 'FirebaseInstallations', :modular_headers => true
  # pod 'FirebaseABTesting', :modular_headers => true
  # pod 'GoogleDataTransport', :modular_headers => true
  # pod 'nanopb', :modular_headers => true
  # pod 'FirebaseAuth', :modular_headers => true
  # pod 'FirebaseFirestore', :modular_headers => true
  # pod 'FirebaseAuthInterop', :modular_headers => true
  # pod 'FirebaseAppCheckInterop', :modular_headers => true
  # pod 'RecaptchaInterop', :modular_headers => true
  # pod 'FirebaseFirestoreInternal', :modular_headers => true

  dynamic_frameworks = ['HyperKYC', 'HyperSnapSDK', 'MaterialComponents', 'MDFInternationalization'] # <- swift libraries names

  # Make all the other frameworks into static frameworks by overriding the static_framework? function to return true
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if dynamic_frameworks.include?(pod.name)
        # puts "Overriding the linkage & packaging method for #{pod.name}"
        def pod.build_type;
          Pod::BuildType.new(:linkage => :dynamic, :packaging => :framework)
        end
      end
      if !dynamic_frameworks.include?(pod.name)
        # puts "Overriding the static_framework? method for #{pod.name}"
        def pod.static_framework?;
          true
        end
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end

end



package.json firebase version: -

    "@react-native-firebase/app": "21.7.1",
    "@react-native-firebase/analytics": "21.7.1",
    "@react-native-firebase/auth": "21.7.1",
    "@react-native-firebase/crashlytics": "21.7.1",
    "@react-native-firebase/firestore": "21.7.1",
    "@react-native-firebase/messaging": "21.7.1",
    "@react-native-firebase/perf": "21.7.1", 
     "react-native": "0.76.5",
     "expo": "latest",  -->> for some expo libraries
      "expo-modules-core": "2.0.3", -->> for some expo libraries

the project is in react native cli

i am stuck can yoy please guide through

**Comment by atuldhakaSB** [comment]
initially i was using the modular_headers => true for the firebase dependency in my pod file but as i have gone through your threads i have removed them and now getting this error, i have cross checked all the documentation from firebase docs,

the error is : - [!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod FirebaseAuth depends upon FirebaseAuthInterop, FirebaseAppCheckInterop, FirebaseCore, FirebaseCoreExtension, GoogleUtilities, and RecaptchaInterop, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set use_modular_headers! globally in your Podfile, or specify :modular_headers => true for particular dependencies.

The Swift pod FirebaseCoreInternal depends upon GoogleUtilities, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set use_modular_headers! globally in your Podfile, or specify :modular_headers => true for particular dependencies.

The Swift pod FirebaseCrashlytics depends upon FirebaseCore, FirebaseInstallations, GoogleDataTransport, GoogleUtilities, and nanopb, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set use_modular_headers! globally in your Podfile, or specify :modular_headers => true for particular dependencies.

The Swift pod FirebaseFirestore depends upon FirebaseCore, FirebaseCoreExtension, and FirebaseFirestoreInternal, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set use_modular_headers! globally in your Podfile, or specify :modular_headers => true for particular dependencies.

The Swift pod FirebaseRemoteConfig depends upon FirebaseABTesting, FirebaseCore, FirebaseInstallations, and GoogleUtilities, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set use_modular_headers! globally in your Podfile, or specify :modular_headers => true for particular dependencies.

The Swift pod FirebaseSessions depends upon FirebaseCore, FirebaseCoreExtension, FirebaseInstallations, GoogleDataTransport, GoogleUtilities, and nanopb, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set use_modular_headers! globally in your Podfile, or specify :modular_headers => true for particular dependencies.

here is my podfile : - Apologies for some commented code

`
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
# Resolve react_native_pods.rb with node to allow for hoisting
 def node_require(script)
   # Resolve script with node to allow for hoisting
   require Pod::Executable.execute_command('node', ['-p',
     "require.resolve(
       '#{script}',
       {paths: [process.argv[1]]},
     )", __dir__]).strip
 end

# Use it to require both react-native's and this package's scripts:
 node_require('react-native/scripts/react_native_pods.rb')
 node_require('react-native-permissions/scripts/setup.rb')

#  podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}
#  ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
 
 setup_permissions([
    "AppTrackingTransparency",
    "Camera",
    "LocationAccuracy",
    "LocationAlways",
    "LocationWhenInUse",
    "MediaLibrary",
    "Notifications",
    "PhotoLibrary",
    "PhotoLibraryAddOnly",
    "StoreKit"
])

  platform :ios, min_ios_version_supported
  prepare_react_native_project!
   
  linkage = ENV['USE_FRAMEWORKS']
  if linkage != nil
    Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
    use_frameworks! :linkage => linkage.to_sym
  end

# use_frameworks! :linkage => :static
# $RNFirebaseAsStaticFramework = true
# $FirebaseSDKVersion = '10.6.0'

project 'ballebaazi', {
  'devDebug' => :debug,
  'qaDebug' => :debug,
  'preDebug' => :debug,
  'Debug' => :debug,
  'Release' => :release,
  'devRelease' => :release,
  'qaRelease'=> :release,
  'preRelease'=> :release,
}

target 'ballebaazi' do

  use_expo_modules!(exclude: ['expo-splash-screen'])
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

  target 'ballebaaziTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    ) 

    installer.pods_project.targets.each do |target|
      # if target.name == 'BoringSSL-GRPC'
      #   target.source_build_phase.files.each do |file|
      #     if file.settings && file.settings['COMPILER_FLAGS']
      #       flags = file.settings['COMPILER_FLAGS'].split
      #       flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
      #       file.settings['COMPILER_FLAGS'] = flags.join(' ')
      #     end
      #   end
      # end
      # if target.name == 'HPWebKit'
      #   `xcrun -sdk iphoneos bitcode_strip -r Pods/HPWebKit/Frameworks/HaptikWebKit/HPWebKit.xcframework/ios-arm64/HPWebKit.framework/HPWebKit -o Pods/HPWebKit/Frameworks/HaptikWebKit/HPWebKit.xcframework/ios-arm64/HPWebKit.framework/HPWebKit`
      # end

      target.build_configurations.each do |config|
        # config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
        # config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Private/React-bridging/react/bridging" '
        # config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_CONFIGURATION_BUILD_DIR)/React-bridging/react_bridging.framework/Headers" '
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
        if target.name == 'Sentry'
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
        end
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] < '12.4'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
        end
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
      end
    end

    # installer.pods_project.build_configurations.each do |config|
    #   config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    # end

    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings["DEVELOPMENT_TEAM"] = "RWGLSYDNDS"
        end
      end
    end
    fuse_path = "./Pods/HyperSDK/Fuse.rb"
     clean_assets = false # Pass true to re-download all the assets
     if File.exist?(fuse_path)
       if system("ruby", fuse_path.to_s, clean_assets.to_s)
       end
     end
  end

 # react-native-permissions
  # permissions_path = '../node_modules/react-native-permissions/ios'
  # pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  # pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"

  # Add the correct ReactCommon dependency:
  # pod 'ReactCommon', :path => '../node_modules/react-native/ReactCommon', :modular_headers => false

  # pod 'Firebase', :modular_headers => true
  # pod 'FirebaseCore', :modular_headers => true
  # pod 'FirebaseCoreInternal', :modular_headers => true
  # pod 'GoogleUtilities', :modular_headers => true
  # pod 'FirebaseCoreExtension', :modular_headers => true
  # pod 'FirebaseInstallations', :modular_headers => true
  # pod 'FirebaseABTesting', :modular_headers => true
  # pod 'GoogleDataTransport', :modular_headers => true
  # pod 'nanopb', :modular_headers => true
  # pod 'FirebaseAuth', :modular_headers => true
  # pod 'FirebaseFirestore', :modular_headers => true
  # pod 'FirebaseAuthInterop', :modular_headers => true
  # pod 'FirebaseAppCheckInterop', :modular_headers => true
  # pod 'RecaptchaInterop', :modular_headers => true
  # pod 'FirebaseFirestoreInternal', :modular_headers => true

  dynamic_frameworks = ['HyperKYC', 'HyperSnapSDK', 'MaterialComponents', 'MDFInternationalization'] # <- swift libraries names

  # Make all the other frameworks into static frameworks by overriding the static_framework? function to return true
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if dynamic_frameworks.include?(pod.name)
        # puts "Overriding the linkage & packaging method for #{pod.name}"
        def pod.build_type;
          Pod::BuildType.new(:linkage => :dynamic, :packaging => :framework)
        end
      end
      if !dynamic_frameworks.include?(pod.name)
        # puts "Overriding the static_framework? method for #{pod.name}"
        def pod.static_framework?;
          true
        end
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end

end
`


package.json firebase version: -
`"@react-native-firebase/app": "21.7.1",
"@react-native-firebase/analytics": "21.7.1",
"@react-native-firebase/auth": "21.7.1",
"@react-native-firebase/crashlytics": "21.7.1",
"@react-native-firebase/firestore": "21.7.1",
"@react-native-firebase/messaging": "21.7.1",
"@react-native-firebase/perf": "21.7.1", 
 "react-native": "0.76.5",
 "expo": "latest",  -->> for some expo libraries
  "expo-modules-core": "2.0.3", -->> for some expo libraries`

the project is in react native cli

i am stuck can yoy please guide through

**Comment by mikehardy** [comment]
There are a million ways a project may be integrated incorrectly, and each one cannot consume support time or nothing else would get done

So as a support strategy I instead show one way that works every time, and I trust other developers to be able to reflect on that and fix their projects using their own time

That's what https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh is. It works every time. You can run it and then try to make your project look like it, and it should work.

as a guess though, you might move these lines up to near where they would be configured dynamically in the Podfile, and put them in there. Perhaps they are being configured too late, I don't know

```
use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true
```

**Comment by mikehardy** [comment]
(to be clear: the errors you are receiving indicate that for some reason, somehow in some spot, `use_frameworks! :linkage => :static` does not seem to be taking effect. Why? No idea)
