### ISSUE TITLE
[🐛] Dynamic Linking Not Working on IOS Real Device: Redirects to App Store Instead of App

### ISSUE THREAD

**Issue by moeezahmad77** [invertase/react-native-firebase#7129]
## Issue

I have implemented Firebase Dynamic Links in my React Native app, following all the configuration steps provided in the official Firebase documentation. The dynamic links are functioning correctly on the Android simulator, Android real device, and iOS simulator. However, when testing on an iOS real device, the dynamic links consistently redirect to the App Store, even when the app is already installed on the device.

To further investigate the issue, I also tried using the Branch.io SDK as an alternative solution. I set up the Branch.io SDK in my React Native app, following the necessary configurations and integration steps. However, I encountered the same problem as mentioned above - dynamic links on iOS real devices always redirect to the App Store, regardless of the app being installed on the device.

I have tested this issue on three iOS devices running OS versions 16.1.1 and 16.0.3. Despite researching the problem, double-checking my configurations, and attempting to use the Branch.io SDK as an alternative, the dynamic links continue to redirect to the App Store on real iOS devices.

## Steps to Reproduce:

Set up Firebase Dynamic Links or Branch.io SDK in a React Native app following the respective documentation.
Generate a dynamic link using the chosen solution (Firebase or Branch.io).
Share the dynamic link with an iOS device having the app installed.
Click on the dynamic link from a messaging app or any other platform.
Observe that instead of opening the app, the iOS device redirects to the App Store.

## Expected Behavior:
When the app is already installed on an iOS device, clicking on a dynamic link should open the app directly, without redirecting to the App Store.

## Additional Information:

Tested on three iOS devices running OS versions 16.1.1 and 16.0.3.
Dynamic links work correctly on Android simulator, Android real device, and iOS simulator.
Verified the apple-app-site-association details.
Set up a separate React Native project following all the configurations from the official documentation for both Firebase Dynamic Links and Branch.io SDK, encountering the same issue.
I would appreciate any assistance in resolving this issue and ensuring that dynamic links on iOS real devices properly redirect to the app when it is already installed, regardless of whether Firebase Dynamic Links or Branch.io SDK is used.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
    "@react-native-firebase/analytics": "^16.4.0",
    "@react-native-firebase/app": "^16.4.0",
    "@react-native-firebase/dynamic-links": "^16.4.0",
    "react": "18.0.0",
    "react-native": "0.69.3"
  }
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

target 'APP_NAME' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # :flipper_configuration => FlipperConfiguration.enabled,
    #  :flipper_configuration => FlipperConfiguration.enabled(["Debug"], { 'Flipper' => '0.159.0' }),
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

    # If you're using autolinking, this line might not be needed
  pod 'WatermelonDB', :path => '../node_modules/@nozbe/watermelondb'

  # NOTE: Do not remove, needed to keep WatermelonDB compiling:
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => true

  # NOTE: This is required as of v0.23
  pod 'simdjson', path: '../node_modules/@nozbe/simdjson'

    #   pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  $RNFirebaseAsStaticFramework = true

  pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'
  
  target 'APP_NAME' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

#### `AppDelegate.m`:

```objc
#import <Firebase.h>
#import "AppDelegate.h"

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // some default code...
  [FIRApp configure];
  // rest of the code...
  
  return YES;
}

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Working fine no issues with the dynamic link behaviour

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 16.4.0`
- **Are you using `TypeScript`?**
  - `No`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Mubashirkhan** [comment]
Having the same issue but the more interesting part is that i have a white label app with multiple build flavours and it works for all the build flavours except one.
