### ISSUE TITLE
Upload to Firebase Storage: ref.putString is not a function

### ISSUE THREAD

**Issue by mdebo** [invertase/react-native-firebase#713]
Hi, I meet an error when trying to upload a base64 formatted string to firebase storage
Error: ref.putString is not a function
Here is my code:
        let storageRef = firebaseApp.storage().ref('pictures').child('test.jpg')
        storageRef.putString(data.data, 'base64').then(function(snapshot) {
        })
Maybe I'm doing something wrong?
Thank you.

 Environment
1. Application Target Platform: 
ios
2. Development Operating System: 
macOS Sierra
3. Build Tools: 
Xcode
4. React Native version: 
0.51
5. RNFirebase Version: 
3.2.0
6. Firebase Module: 
Storage

**Comment by yasir-netlinks** [comment]
Hi, I am having the same issue on Android , trying to upload a base64 format to storage, any updates on this! thanx

**Comment by chrisbianca** [comment]
Currently `putString` and `putData` aren't supported by `react-native-firebase` as it's a little complicated with the RN bridge. 

We have an open feature request for the latter here: https://react-native-firebase.canny.io/admin/board/feature-requests/p/firebase-storage-putdata-download-urls-without-touching-fs

Feel free to add another for `putString` or comment with a request for `putString` and we'll look to add them both at the same time.

**Comment by brunogonncalves** [comment]
WHAT ??? OMG !!! I can't upload file to storage o_O

**Comment by modawoud** [comment]
@brunogonncalves I see that it is already there, and it is really easy to upload to firebase, check this link for documentation
https://github.com/invertase/react-native-firebase/blob/docs_old/docs/modules/storage.md

**Comment by Salakar** [comment]
I'll add support for both `putString` and `putData` in a later release - though they'll both come with a performance warning in dev as you really should be using the file system in most cases.

@brunogonncalves @modawoud there's actually 2 up to date examples here: https://rnfirebase.io/docs/v5.x.x/storage/reference/Reference#putFile

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
