### ISSUE TITLE
Phone Auth Opening External Verification Link

### ISSUE THREAD

**Issue by sunnyysetia** [invertase/react-native-firebase#7140]
## Issue

I'm Using Expo managed workflow with EAS Build.

I am using react-native-firebase and followed this guide to get it working: https://rnfirebase.io/auth/phone-auth

I'm encountering an issue that when someone enters their phone number, it opens an external link which adds delay & friction to the sign up process. This link asks user to verify they are not a robot.

There is also a significant delay of ~6 seconds between hitting the next button and this link being opened. 

This is extremely bad UX and I have not noticed having to do this with any of the apps that use phone auth on the app store. Is there a way around this? 

Screen recording of issue:
https://drive.google.com/file/d/1U94YSi8I08o8xWfuKZcEHvWcr3YTkEWm/view?usp=sharing

I am using the following code for my implementation:
![Screenshot 2023-05-28 at 2 25 25 PM](https://github.com/invertase/react-native-firebase/assets/89380644/f13e4451-3c35-47e0-8ee0-676f70ae6032)

Thanks

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by SectionTN** [comment]
same problem

**Comment by balloman** [comment]
Did you ever find a solution?
