### ISSUE TITLE
Compatibility Issue Between @react-native-firebase/app and @react-native-firebase/admob

### ISSUE THREAD

**Issue by hinevi** [invertase/react-native-firebase#7145]
I am writing to inform you about a compatibility issue I've encountered while working with the @react-native-firebase/app and @react-native-firebase/admob packages.

I have installed the @react-native-firebase/app package, version 17.5.0. However, I've noticed an issue arising from a peer dependency conflict between this package and the @react-native-firebase/admob package, version 11.5.0.

The error message I received is as follows:

peer @react-native-firebase/app@"11.5.0" from @react-native-firebase/admob@11.5.0

This error suggests that the @react-native-firebase/admob package expects a version of @react-native-firebase/app that is "11.5.0", which is incompatible with the current version I have installed ("17.5.0").

**Comment by SandipJawaleRN** [comment]
> I am writing to inform you about a compatibility issue I've encountered while working with the @react-native-firebase/app and @react-native-firebase/admob packages.
> 
> I have installed the @react-native-firebase/app package, version 17.5.0. However, I've noticed an issue arising from a peer dependency conflict between this package and the @react-native-firebase/admob package, version 11.5.0.
> 
> The error message I received is as follows:
> 
> peer @react-native-firebase/app@"11.5.0" from @react-native-firebase/admob@11.5.0
> 
> This error suggests that the @react-native-firebase/admob package expects a version of @react-native-firebase/app that is "11.5.0", which is incompatible with the current version I have installed ("17.5.0").

`com.google.android.gms:play-services-ads:19.8.0
This SDK version has a note from the SDK developer. Here's what the SDK developer told us:

This version is scheduled to sunset on June 30th 2023. See https://developers.google.com/admob/android/deprecation for more information.

Starting from November 20, 2023 00:00 (UTC) you won't be able to release new versions which contain this SDK version.`

How to upgrade?
