### ISSUE TITLE
[🐛] 🔥Firestore collection orderBy string type is incorrect when using interface

### ISSUE THREAD

**Issue by ChromeQ** [invertase/react-native-firebase#7147]
## Issue

I am getting typescript errors with the following snippet:
```
const snaps = await firestore().collection<TestInterface>('test').orderBy('test-obj.sort-num').get();
const docs = snaps.docs.map((doc) => doc.data());
console.log(JSON.stringify(docs, null, 2));
```
Error is: `Argument of type '"test-obj.sort-num"' is not assignable to parameter of type 'FieldPath | "test-obj"'` which is because the expected type for `orderBy` is `orderBy(fieldPath: keyof T | FieldPath, directionStr?: 'asc' | 'desc'): Query<T>;`

Seems correct, but actually we can pass a dot notation string to order by object maps in the document, no official documentation on https://firebase.google.com/docs/firestore/query-data/order-limit-data, but a SO with a similar setup got confirmation of the behaviour: https://stackoverflow.com/questions/46840622/firestore-orderby-on-subproperty-subcollection#comment80651114_46841561

I have used this in a web project previously, and I have tested it here in RN - it seems to work, just the TS not allowing me to pass a string when I provide a type to the collection generic (TestInterface in my example).

Here is the output with correct order of the sort-num:
![image](https://github.com/invertase/react-native-firebase/assets/625203/88377c70-91dc-4380-b7b1-5a6a388e1581)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
    "@react-native-firebase/app": "17.5.0",
    "@react-native-firebase/firestore": "17.5.0",
}
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
❯ npx react-native info
info Fetching system and libraries information...
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1270P
    Memory: 16.37 GB / 30.80 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 25.2.9519653
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `17.5.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `firestore`
- **Are you using `TypeScript`?**
  - `Y` & `4.9.5`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by ChromeQ** [comment]
Still requires investigation

**Comment by ChromeQ** [comment]
Not stale

**Comment by ChromeQ** [comment]
Not stale

**Comment by ChromeQ** [comment]
Not stale

**Comment by ChromeQ** [comment]
Still not stale

**Comment by ChromeQ** [comment]
Still not stale, annoying this is taking so long to be triaged or any comments from a firebase employee.

**Comment by mikehardy** [comment]
Sorry for the delay, we haven't had time to triage this - no - however, our types are in general supposed to match firebase-js-sdk. The goal is that at least from an API shape / typing perspective it's a drop-in replacement for firebase-js-sdk with the added extra of native device integration where that's important.

What that means specifically is that if you check the reference part of the http://rnfirebase.io docs site for any module where there is some typing error and hit the "edit" button at the top right, you can propose a quick fix to the typing via the github web PR UI, and if you drop a link in to the firebase-js-sdk reference docs for the same API for comparison so we can see it lines up we can merge it and publish a release with very little delay

**Comment by ChromeQ** [comment]
Not stale, but I forgot to action the suggestion so I will look into doing this soon

**Comment by ChromeQ** [comment]
Still not stale, will once again try to remember to fix this myself

**Comment by ChromeQ** [comment]
@mikehardy Thanks for the tips on how to update this, I have submitted a PR so it would be great to get somebody to review and approve to merge asap. Thanks again
