### ISSUE TITLE
iOS crash on release build after upgrading to react-native 0.71.8 ([FIRApp configure] and any import creates a crash)

### ISSUE THREAD

**Issue by saladestomateoignon** [invertase/react-native-firebase#7153]
Hello guys,
I had a react-native app with the below configs:
- react-native@0.70.6,
- expo@^47.0.0,
- @react-native-firebase/app@16.4.6
- @react-native-firebase/crashlytics@16.4.6
- @react-native-firebase/analytics@16.4.6
- @react-native-firebase/dynamic-links@16.4.6

Everything worked very well on it.

After upgrading to react-native to 0.71.8 and expo to 48.0.17, app now crashes on iOS when booting on release mode only with AdHoc or testflight builds. (on debug, with react-native-run-ios, everything works well).

I remarked that if I remove the [FIRApp configure] of my AppDelegate.mm + any import related to @react-native-firebase packages, app does not crash.
I also tried to upgrade @react-native-firebase packages to latest (17.5.0), but result is still the same.

Here is the "didFinishLaunchingWithOptions" function of my AppDelegate.mm file:
```
#import "AppDelegate.h"
#import <React/RCTBundleURLProvider.h>

#import <React/RCTLinkingManager.h>
#import <Firebase.h>
// other imports

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  //... other module setup
  [FIRApp configure];

  self.moduleName = @"myApp";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
```

Here are the dependencies of my current project after all the upgrades:
```
{
  "name": "myApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ./src --ext .js,.jsx,.ts,.tsx",
    "lint:fix": "eslint ./src --ext .js,.jsx,.ts,.tsx --fix",
    "format": "prettier --check ./src",
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "~1.17.11",
    "@react-native-clipboard/clipboard": "^1.11.0",
    "@react-native-community/hooks": "^2.8.1",
    "@react-native-cookies/cookies": "^6.2.1",
    "@react-native-firebase/analytics": "^17.5.0",
    "@react-native-firebase/app": "^17.5.0",
    "@react-native-firebase/crashlytics": "^17.5.0",
    "@react-native-firebase/dynamic-links": "^17.5.0",
    "@react-native-picker/picker": "^2.4.9",
    "@react-navigation/bottom-tabs": "6.4.3",
    "@react-navigation/native": "6.0.16",
    "@react-navigation/native-stack": "6.9.4",
    "@reduxjs/toolkit": "^1.9.1",
    "@sentry/react-native": "^5.5.0",
    "axios": "^1.2.0",
    "country-emoji": "^1.5.6",
    "currency.js": "^2.0.4",
    "dayjs": "^1.11.6",
    "expo": "^48.0.0",
    "expo-application": "~5.1.1",
    "expo-checkbox": "~2.3.1",
    "expo-device": "~5.2.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-local-authentication": "~13.3.0",
    "expo-localization": "~14.1.1",
    "expo-location": "~15.1.1",
    "expo-secure-store": "~12.1.1",
    "expo-splash-screen": "~0.18.2",
    "formik": "^2.2.9",
    "i18n-js": "^3.9.2",
    "js-base64": "^3.7.5",
    "lodash": "^4.17.21",
    "lottie-react-native": "^5.1.4",
    "newrelic-react-native-agent": "^1.2.0",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-config": "^1.5.0",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-paper": "^4.12.5",
    "react-native-reanimated": "^3.2.0",
    "react-native-reanimated-carousel": "^3.1.5",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "3.18.2",
    "react-native-size-matters": "^0.4.0",
    "react-native-svg": "13.4.0",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-webview": "11.23.1",
    "react-redux": "^8.0.5",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/i18n-js": "^3.8.2",
    "@types/jest": "^29.2.1",
    "@types/lodash": "^4.14.191",
    "@types/react": "^18.0.24",
    "@types/react-native": "^0.70.6",
    "@types/react-native-vector-icons": "^6.4.12",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.37.0",
    "@typescript-eslint/parser": "^5.37.0",
    "babel-jest": "^29.2.1",
    "babel-plugin-module-resolver": "^4.1.0",
    "eslint": "^8.19.0",
    "eslint-plugin-no-inline-styles": "^1.0.5",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.31.11",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.9",
    "patch-package": "^6.5.0",
    "prettier": "^2.8.1",
    "react-native-flipper": "0.163.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-version": "^4.0.0",
    "react-test-renderer": "18.2.0",
    "redux-flipper": "^2.0.2",
    "typescript": "^4.8.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  },
  "expo": {
    "autolinking": {
      "exclude": [
        "expo-asset",
        "expo-constants",
        "expo-file-system",
        "expo-font",
        "expo-keep-awake"
      ]
    }
  }
}
```

I am stuck with this issue for two days now. Any idea bout what might be the issue?

Thanks.

**Comment by danielkv** [comment]
I'm also having problems on IOS, it's the same symptoms though. But it may be related behind the scenes: https://github.com/invertase/react-native-firebase/issues/7152

I can open and authenticate in the app, but the firestore doesn't work. It does on android!

**Comment by danielkv** [comment]
I'm trying another approach here, if it works I'll post it here

**Comment by danielkv** [comment]
well, you may call me studid, but I was missing one little thing: **build the project again**.

I'm using `managed workflow` on **expo** so I just build the project when it's really necessary, I had built it when I installed the `@react-native-firebase/app`, but I haven't realized that I installed `@react-native-firebase/firestore` and `@react-native-firebase/function` after I've done the build. So the native modules were not setup.

I Just needed to rebuild the `development build again` and it worked like a charm! This should be more explicit in the docs, something like: "For each module installed you must rebuild the project"

I'm not sure if this could fix you problem though.

**Comment by danielkv** [comment]
Can't you upgrade to v17.5.0?

**Comment by danielkv** [comment]
Oh, that's tough! Well, have luck in your journey 😅I hope you find it soon. If I step in a possible solution for you I'll let you know!

**Comment by mikehardy** [comment]
This is not using expo, but my install-from-scratch + configure firebase + build demonstrator does a release build for iOS and it works fine for me?

https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

It is using latest react-native-firebase (v18 just now) and react-native 0.71.8 seemingly without issue

Please note that any report of a crash should be accompanied with the stack trace from the crash. I don't see that here. You can get that by running it from Xcode and looking at the console, or you may plug your device into the laptop and open Console.app, select the phone, and watch the log when you start the app to capture the trace

**Comment by kkaplinski** [comment]
I don't know if this will help someone but for me, solution was very simple: I added `GoogleService-Info.plist` file via Xcode. My first approach was very lazy. I skipped this important step and manually copied the file to the iOS folder. 😅

**Comment by kholiqcode** [comment]
same with me, IOS crash

any suggestion?

```
"dependencies": {
    "@hookform/error-message": "^2.0.1",
    "@hookform/resolvers": "^3.1.1",
    "@react-native-firebase/app": "^18.0.0",
    "@react-native-masked-view/masked-view": "^0.2.9",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@shopify/flash-list": "^1.4.3",
    "@tamagui/babel-plugin": "^1.31.2",
    "@tamagui/react-native-media-driver": "^1.31.2",
    "@tamagui/shorthands": "^1.31.2",
    "@tamagui/themes": "^1.31.2",
    "@tanstack/react-query": "^4.29.13",
    "axios": "^1.4.0",
    "i18next": "^22.5.1",
    "react": "18.2.0",
    "react-hook-form": "^7.44.3",
    "react-i18next": "^12.3.1",
    "react-native": "0.71.8",
    "react-native-code-push": "^8.0.2",
    "react-native-config": "^1.5.1",
    "react-native-device-info": "^10.6.0",
    "react-native-gesture-handler": "^2.11.0",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-mmkv": "^2.8.0",
    "react-native-reanimated": "^3.4.0-nightly-20230613-d6c178870",
    "react-native-safe-area-context": "^4.5.3",
    "react-native-screens": "^3.20.0",
    "react-native-skeleton-placeholder": "^5.2.4",
    "react-native-svg": "^13.9.0",
    "react-native-toast-message": "^2.1.6",
    "tamagui": "^1.31.2",
    "zod": "^3.21.4",
    "zod-i18n-map": "^2.13.1",
    "zustand": "^4.3.8"
  }
```

**Comment by mikehardy** [comment]
Glad you appear to have found the culprit @saladestomateoignon but for future reference

> Doing this reproduces the crash.

There is no crash trace provided, no help is possible. If reporting a native crash, the crash trace is essential + required information

@kholiqcode - likewise,

> same with me, IOS crash

This statement does not advance a crash issue ever. The crash trace is required information.

**Comment by kholiqcode** [comment]
For now it's working fine, thank you all

**Comment by kholiqcode** [comment]
For now rn-firebase is running fine in my project, but for some reason it runs with flipper enable and I can use flipper fully with this library.

```
"react-native": "0.71.11",
"@react-native-firebase/app": "^18.1.0",
"@react-native-firebase/messaging": "^18.1.0",
```

my Podfile
```
  config = use_native_modules!

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
```

isn't flipper not supported when using this library? @mikehardy

**Comment by mikehardy** [comment]
Flipper is not supported because it does not support `use_frameworks`, and using `modular_headers` as a workaround to avoid `use_frameworks` is not supported. So you have it working because of an unsupported workaround, but I wouldn't expect react-native-firebase in general to work well this way. You just happen to be using some parts of firebase-ios-sdk that are not currently using Swift in a way that links correctly using the unsupported workaround. It could change with any firebase-ios-sdk release
