### ISSUE TITLE
NoClassDefFoundError -> Cannot resolve

### ISSUE THREAD

**Issue by ianataffinity** [invertase/react-native-firebase#716]
### Issue

Have installed firebase and react native firebase and running into this red screen on startup. 
![image](https://user-images.githubusercontent.com/29443467/34472286-8e21593e-efb2-11e7-9eb1-518119046646.png)

Here is the dependencies in my build.gradle file:

    compile "com.google.android.gms:play-services-base:11.8.0"
    compile "com.google.firebase:firebase-core:11.8.0"
    compile "com.google.firebase:firebase-analytics:11.8.0"
    compile "com.google.firebase:firebase-auth:11.8.0"
    compile "com.google.firebase:firebase-messaging:11.8.0"
    compile "com.google.firebase:firebase-database:11.8.0"

Im running React Native Firebase 3.2.0

    "react-native-firebase": "^3.2.0",

Have installed google play services dependencies:

    classpath 'com.android.tools.build:gradle:3.0.1'
    classpath 'com.google.gms:google-services:3.1.2'

And running SDK version 26

    compileSdkVersion 26
    buildToolsVersion '26.0.2'

I have hit a wall and not sure how to get this working. Any help / advice would be much appreciated.

### Environment

1. Application Target Platform: ANDROID
2. Development Operating System: WINDOWS 10
3. Build Tools: Android Studio
4. React Native version: 0.51.0
5. RNFirebase Version:  3.2.0

6. Firebase Module: 
* compile "com.google.firebase:firebase-core:11.8.0"
* compile "com.google.firebase:firebase-analytics:11.8.0"
* compile "com.google.firebase:firebase-auth:11.8.0"
* compile "com.google.firebase:firebase-messaging:11.8.0"
* compile "com.google.firebase:firebase-database:11.8.0"

**Comment by Ehesp** [comment]
Can we see your code usage please?

**Comment by ianataffinity** [comment]
Found out the directory it was building into was wrong. A good project clean and restart fixed the issue.
