### ISSUE TITLE
[🐛] 🔥 DynamicLinks iOS: dynamic link doesn't survive when user installs app from App Store and press open button

### ISSUE THREAD

**Issue by JaiminTechholding** [invertase/react-native-firebase#7160]
Dynamic Links don't survive App Store installation on any device, Although it's working when a user installs from TestFlight (not added public link).

I have followed the steps to test that scenario for the AppStore installation process.

- If the application is not installed, Click on the dynamic link, It will redirect you to the Browser from that you will be redirected to the AppStore.
- Now install the app and once it's installed click on the Open button. The application is launched but you'll not be able to see that dynamic link.
- I have checked via bugsnag.

Contrary to the previous issue, getInitialLink() doesn't work for any devices I've tested when the app is installed through App Store.

I've got the correct Team ID and App Store ID in the Firebase console. When clicking through Preview Page, I get redirected to my app's right App Store page. I do have `GoogleService-Info.plist` inside my ios project.

Android is working flawlessly. Install through Play Store all work correctly. The only issue is iOS.

Code I'm using:
In `AppDelegate.m` added this code in `didFinishLaunchingWithOptions`

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [RNFBDynamicLinksAppDelegateInterceptor sharedInstance]; // add this line
 // other code
  [FIROptions defaultOptions].deepLinkURLScheme = @"appSchema";
  
[FIRApp configure];
}
```

The following code was added for the Restoration handler for `continuUserActivity` and `openURL` scenario.

```
-(BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  BOOL handled = NO;
  FIRDynamicLink *dynamicLink = [[FIRDynamicLinks dynamicLinks]
                                 dynamicLinkFromCustomSchemeURL:url];
  if (dynamicLink) {
    if (dynamicLink.url) {
      handled = [RCTLinkingManager application:application openURL:dynamicLink.url options:options];
      //         || [[RNFirebaseLinks instance] application:application
      //                          openURL:dynamicLink.url options:options];
    }
  }
  if(!handled) {
    handled = [RCTLinkingManager application:application openURL:url
                                     options:options];
  }
  return handled;
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  BOOL handled = [[FIRDynamicLinks dynamicLinks] handleUniversalLink:userActivity.webpageURL
                                                          completion:^(FIRDynamicLink * _Nullable dynamicLink, NSError * _Nullable error) {
    // Handle the dynamic link or error as needed.
    // For example, you can parse the URL and navigate to a specific screen.
    // You may also need to handle other user activities if your app supports them.
    
    // Call the restorationHandler to indicate that the user activity was handled.
    restorationHandler(@[self]);
  }];
  
  // Return whether the dynamic link was handled successfully.
  return handled;
}
```

I have followed some of the threads like

- https://github.com/invertase/react-native-firebase/issues/2661
- https://github.com/invertase/react-native-firebase/issues/2660
- https://github.com/invertase/react-native-firebase/issues/2660#issuecomment-1338229842
- https://github.com/invertase/react-native-firebase/issues/4548#issuecomment-1453547781
- https://github.com/invertase/react-native-firebase/issues/4548#issuecomment-762881871

Also followed medium links but still not working, For this testing I am continuously uploading the build on AppStore but none of them is working.

- https://medium.com/@ramakrishnan_89356/firebase-dynamic-links-for-your-react-native-app-ios-setup-only-c6e1f5a7944e
- https://medium.com/@mouryaakhilesh26/react-native-firebase-dynamic-links-88953d295a2d

**Comment by quyen0122bee** [comment]
I also have the same problem ((=

**Comment by JaiminTechholding** [comment]
@quyen0122bee I have resolved this code by adding the same code multiple times like previously I was calling it to App.js and then I have also added the same code in the Signup screen (or whichever screen you required that thing.)

**Comment by DaniyalShaikh-0** [comment]
@JaiminTechholding , this code is for Appdelegate.m , how did you add that code to JS. 

I am asking because i am experiencing the exact Same issue that you described above.

my openURL function Looks like this:

```
- (BOOL)application:(UIApplication *)application
              openURL:(NSURL *)url
    sourceApplication:(NSString *)sourceApplication
           annotation:(id)annotation {
  return [RCTLinkingManager application:application
                                openURL:url
                      sourceApplication:sourceApplication
                             annotation:annotation];
}
- (BOOL)application:(UIApplication *)application
    continueUserActivity:(nonnull NSUserActivity *)userActivity
      restorationHandler:
#if defined(__IPHONE_12_0) && (__IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_12_0)
          (nonnull void (^)(NSArray<id<UIUserActivityRestoring>> *_Nullable))
              restorationHandler {
#else
          (nonnull void (^)(NSArray *_Nullable))restorationHandler {
#endif // __IPHONE_12_0
  BOOL handled = [[FIRDynamicLinks dynamicLinks]
      handleUniversalLink:userActivity.webpageURL
               completion:^(FIRDynamicLink *_Nullable dynamicLink,
                            NSError *_Nullable error){
                   // ...
               }];
  return handled;
}
```


BUT still, on install it doesn’t work, and getInitialLink doesn’t work.

Other things that you mentioned do work.

**Comment by DaniyalShaikh-0** [comment]
Now my onLink is not working as well.

I don’t understand why it is so Unstable on IOS.

**Comment by artvichi** [comment]
same problem on our side - all works except for when user installs the app from app store - it doesn't show that there is any kind of initial Link in this case.

**Comment by dhaval97micro1** [comment]
I am also facing the same issue
