### ISSUE TITLE
🔥 iOS 12.5 is deprecated in v18 / FirebaseCoreExtension 10.10.0?

### ISSUE THREAD

**Issue by mstrokin** [invertase/react-native-firebase#7167]
Upgrading @react-native-firebase to 18.0.0 broke the pod install for me; 
Works fine if I change the platform :ios, '12.4' to platform :ios, '13.0' in the Podfile

FYI: This iOS version is used by iPhone 5S and 6 (2013/2014 models)

**Comment by mikehardy** [comment]
Ah they have moved the minimum supported version as well - will check - thanks for opening this

**Comment by mikehardy** [comment]
I don't seem to be able to reproduce this.. Here is the evidence I have with an iOS deploy target of 12.4:

- https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh (fully scripted build, is set to 12.4 in the Xcode settings with *no* setting in the Podfile and it works?
- our e2e tests app, which specifies it in the Podfile:
https://github.com/invertase/react-native-firebase/blob/db49dfeab62fa0c52530ccf2bfdfe9e27947bdbd/tests/ios/Podfile#L18-L20

Plus, the documentation indicates iOS 11+ should work: https://firebase.google.com/docs/ios/setup#prerequisites

🤔

**Comment by mstrokin** [comment]
Sorry for taking your time, "pod update" solved the issue; I guess there was an outdated podspec somewhere
