### ISSUE TITLE
 🔥Urgent: Expo-Eas-build Sdk45 iOS (simulator) @react-native-firebase/auth throws [internal-server-error ]  

### ISSUE THREAD

**Issue by zain148** [invertase/react-native-firebase#7170]
## Issue

 <b>Expo sdk45 iOS simulator development build I'm  facing this error [auth/internal-error] An internal error has occurred, please try again.</b>

Describe your issue here

Hello, I'm facing critical issues on my iOS side  Note: Android works perfectly with development build and on release build.
This is the error I'm able to catch <b> [auth/internal-error] An internal error has occurred, please try again.</b>

Somehow I switched to latest version @18.0.0 but it's still throwing same error on expo iOS simulator with development build. 

I was using <b>  @react-native-firebase version @16.4.6 and switched to latest @18.0.0 version  </b> but no luck

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "eas:build:ios": "sudo eas build --profile dev --platform ios",
    "eas:build:android": "eas build --profile dev --platform android",
    "eas:build:all": "sudo eas build --profile dev --platform all"
  },
  "dependencies": {
    "@babel/helper-string-parser": "^7.19.4",
    "@expo/config-plugins": "^4.1.0",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/datetimepicker": "6.1.2",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-firebase/app": "^18.0.0",
    "@react-native-firebase/auth": "^18.0.0",
    "@react-native-firebase/firestore": "^18.0.0",
    "@react-native-firebase/storage": "^18.0.0",
    "@react-native-google-signin/google-signin": "8.0.0",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "expo": "^45.0.0",
    "expo-app-auth": "~11.1.0",
    "expo-apple-authentication": "~4.2.1",
    "expo-application": "~4.1.0",
    "expo-asset": "~8.5.0",
    "expo-av": "~11.2.3",
    "expo-background-fetch": "~10.2.0",
    "expo-build-properties": "~0.2.0",
    "expo-camera": "~12.2.0",
    "expo-constants": "~13.1.1",
    "expo-dev-client": "~1.0.1",
    "expo-device": "~4.2.0",
    "expo-font": "~10.1.0",
    "expo-image-manipulator": "~10.3.1",
    "expo-image-picker": "~13.1.1",
    "expo-intent-launcher": "~10.2.0",
    "expo-linear-gradient": "~11.3.0",
    "expo-linking": "~3.1.0",
    "expo-location": "~14.2.2",
    "expo-notifications": "~0.15.4",
    "expo-permissions": "~13.2.0",
    "expo-screen-capture": "~4.2.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-system-ui": "~1.2.0",
    "expo-task-manager": "~10.2.1",
    "expo-updates": "~0.13.4",
    "expo-web-browser": "~10.2.1",
    "firebase": "8.2.3",
    "geolib": "^3.3.3",
    "js-sha256": "^0.9.0",
    "lottie-ios": "3.2.3",
    "lottie-react-native": "5.0.1",
    "moment": "^2.29.1",
    "react": "17.0.2",
    "react-content-loader": "^6.2.0",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-animated-loader": "^0.0.9",
    "react-native-confirmation-code-field": "^7.1.0",
    "react-native-country-picker-modal": "^2.0.0",
    "react-native-draggable-flatlist": "^3.1.2",
    "react-native-elements": "^3.4.2",
    "react-native-fbsdk-next": "10.1.0",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-image-slider-box": "^1.0.12",
    "react-native-image-viewing": "^0.2.0",
    "react-native-maps": "0.30.2",
    "react-native-modal-datetime-picker": "^10.0.0",
    "react-native-modalbox": "^2.0.2",
    "react-native-reanimated": "~2.8.0",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-svg": "12.3.0",
    "react-native-uuid": "^2.0.1",
    "react-native-web": "0.17.7",
    "react-native-webview": "11.18.1",
    "yarn": "^1.22.18"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}

```json
# N/A
```

#### `app.json`:

app.config.js or app.json

{
  "name": "Hookd",
  "slug": "Hookd",
  "version": "1.0.0",
  "scheme": "hookd",
  "orientation": "portrait",
  "icon": "./src/assets/images/iphone1024.png",
  "splash": {
    "image": "./src/assets/images/splashScreen.png",
    "resizeMode": "contain",
    "backgroundColor": "#ffffff"
  },
  "updates": {
    "enabled": true,
    "fallbackToCacheTimeout": 5000,
    "url": "https://u.expo.dev/29b92582-89fb-4921-80dd-e04afe45d61c"
  },
  "runtimeVersion": {
    "policy": "sdkVersion"
  },
  "assetBundlePatterns": [
    "**/*"
  ],
  "notification": {
    "iosDisplayInForeground": true,
    "androidMode": "default",
    "color": "#ffffff"
  },
  "jsEngine": "hermes",
  "ios": {
    "jsEngine": "jsc",
    "bitcode": "Debug",
    "userInterfaceStyle": "light",
    "usesAppleSignIn": true,
    "supportsTablet": false,
    "icon": "./src/assets/images/iphone1024.png",
    "bundleIdentifier": "com.zaincompany.hookd",
    "buildNumber": "1.0.49",
    "infoPlist": {
      "NSPhotoLibraryUsageDescription": "To select media for your profile and chats, Hookd needs permission to access your photos.",
      "NSLocationWhenInUseUsageDescription": "To find nearby users, Hookd needs permission to access your foreground location permission. Your exact location will not be shown.",
      "NSLocationAlwaysAndWhenInUseUsageDescription": "Hookd needs to know your position even when the app is turned off so you can always hook new people.",
      "NSCameraUsageDescription": "To take photos and videos for your profile and chats, Hookd needs permission to access your camera.",
      "NSMicrophoneUsageDescription": "To record sound for your profile video and chats, Hookd needs permission to access your microphone.",
      "UIBackgroundModes": [
        "location"
      ],
      "SKAdNetworkItems": [
        {
          "SKAdNetworkIdentifier": "v9wttpbfk9.skadnetwork"
        },
        {
          "SKAdNetworkIdentifier": "n38lu8286q.skadnetwork"
        }
      ]
    },
    "googleServicesFile": "./GoogleService-Info.plist"
  },
  "android": {
    "userInterfaceStyle": "automatic",
    "icon": "./src/assets/images/hookd1500.png",
    "package": "com.zaincompany.hookd",
    "versionCode": 9,
    "permissions": [
      "ACCESS_FINE_LOCATION",
      "ACCESS_COARSE_LOCATION",
      "FOREGROUND_SERVICE",
      "ACCESS_BACKGROUND_LOCATION",
      "CAMERA",
      "CAMERA_ROLL",
      "READ_EXTERNAL_STORAGE",
      "RECORD_AUDIO",
      "android.permission.INTERNET"
    ],
    "googleServicesFile": "./google-services.json"
  },
  "web": {
    "favicon": "./src/assets/images/favicon.png"
  },
  "description": "Hookd App",
  "extra": {
    "eas": {
      "projectId": "29b92582-89fb-4921-80dd-e04afe45d61c"
    }
  },
  "sdkVersion": "45.0.0",
  "platforms": [
    "ios",
    "android",
    "web"
  ],
  "plugins": [
    [
      "expo-build-properties",
      {
        "ios": {
          "useFrameworks": "static"
        }
      }
    ],
    "./src/plugins/react-native-maps.js",
    "@react-native-google-signin/google-signin",
    "@react-native-firebase/app",
    "@react-native-firebase/auth",
    [
      "react-native-fbsdk-next",
      {
        "appID": "1006363050323471",
        "clientToken": "0f2ae188c32bc97a7e5bc553971573fa",
        "displayName": "Hookd",
        "autoLogAppEventsEnabled": true,
        "scheme": "fb1006363050323471"
      }
    ]
  ],
  "currentFullName": "@hookd123/Hookd",
  "originalFullName": "@hookd123/Hookd"
}

🍏 Build profile "dev"

{
  "credentialsSource": "remote",
  "distribution": "internal",
  "developmentClient": true,
  "channel": "dev",
  "simulator": true,
  "autoIncrement": "buildNumber"
}

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 EAS CLI 3.13.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    Utilities:
      Git: 2.32.1 - /usr/bin/git
    npmPackages:
      expo: ^45.0.0 => 45.0.8 
      expo-dev-client: ~1.0.1 => 1.0.1 
      expo-updates: ~0.13.4 => 0.13.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 3.13.3
      expo-cli: 6.2.1
    Project workflow: managed
```

- **Platform that you're experiencing the issue on**:
  - [x ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 18.0.0 @react-native-firebase/auth`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there @zain148 👋  please note that while I provide support, this is an open source project. That is, I understand it is urgent for you, and critical for you, but there is no paid support here and I cannot commit to any sort of responsiveness. Stated differently: you are going to need to maintain the mental perspective that you must discover the root cause and determine an appropriate solution for your problem.

I can only help guide, in time I have available.

That said, you mention this:

>  this error [auth/internal-error] An internal error has occurred, please try again.

But you do not dig in to the internal error. Native troubleshooting will necessarily involve you looking at the native logs, by plugging the device in and using Console.app to select the device and figure out what the firebase-ios-sdk is printing out at the native level or using Xcode to build the app to your device or simulator and watching the Xcode logs.

Further, you do not include any reproduction that would help in anyone else reproduce the error, so it will be difficult for anyone to help you.  This is some good guidance on what it means to make a minimal reproducible example and what others will expect of you with regard to specifying it: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by benoitzohar** [comment]
For what it's worth I'm running into the same issue, on a fresh project (tried re-creating that project multiple time without any luck).

My setup is:
- Bare `react-native@0.71.6`
- `@react-native-firebase/app@18.0.0`
- `@react-native-firebase/auth@18.0.0`
```
use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true
```  
in Podfile

- Tried disabling Flipper, Fabric, and Hermes, with no luck.


Worth noting that when the app runs, and before the JS bundle is generated, I get this error: 
```
Thread Performance Checker: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions
PID: 28145, TID: 85624
Backtrace
=================================================================
3   RecipeProdigy                       0x000000010235c150 -[_RCTSRRunLoopThread runLoop] + 44
4   RecipeProdigy                       0x000000010235be74 __49+[NSRunLoop(RCTSRWebSocket) RCTSR_networkRunLoop]_block_invoke + 116
5   libdispatch.dylib                   0x000000010a8a9d50 _dispatch_client_callout + 16
6   libdispatch.dylib                   0x000000010a8ab7f8 _dispatch_once_callout + 84
7   RecipeProdigy                       0x000000010235bdd8 +[NSRunLoop(RCTSRWebSocket) RCTSR_networkRunLoop] + 88
8   RecipeProdigy                       0x0000000102355a70 -[RCTSRWebSocket _connect] + 76
9   RecipeProdigy                       0x0000000102354788 -[RCTSRWebSocket open] + 320
10  RecipeProdigy                       0x00000001023366f0 -[RCTReconnectingWebSocket start] + 148
11  RecipeProdigy                       0x0000000102324fcc -[RCTPackagerConnection init] + 416
12  RecipeProdigy                       0x0000000102324e0c __49+[RCTPackagerConnection sharedPackagerConnection]_block_invoke + 36
13  libdispatch.dylib                   0x000000010a8a9d50 _dispatch_client_callout + 16
14  libdispatch.dylib                   0x000000010a8ab7f8 _dispatch_once_callout + 84
15  RecipeProdigy                       0x0000000102324dc0 +[RCTPackagerConnection sharedPackagerConnection] + 88
16  RecipeProdigy                       0x00000001020d9008 -[RCTDevSettings initialize] + 164
17  RecipeProdigy                       0x0000000102310a70 -[RCTModuleData _initializeModule] + 96
18  RecipeProdigy                       0x0000000102310420 -[RCTModuleData setUpInstanceAndBridge:] + 2168
19  RecipeProdigy                       0x0000000102311ed8 -[RCTModuleData instance] + 1168
20  RecipeProdigy                       0x00000001022b9938 -[RCTCxxBridge moduleForName:lazilyLoadIfNecessary:] + 712
21  RecipeProdigy                       0x000000010231ab30 -[RCTModuleRegistry moduleForName:lazilyLoadIfNecessary:] + 140
22  RecipeProdigy                       0x000000010231aa98 -[RCTModuleRegistry moduleForName:] + 48
23  RecipeProdigy                       0x00000001020ea514 -[RCTPerfMonitor devMenuItem] + 92
24  RecipeProdigy                       0x00000001020ea3e0 -[RCTPerfMonitor initialize] + 88
25  RecipeProdigy                       0x0000000102310a70 -[RCTModuleData _initializeModule] + 96
26  RecipeProdigy                       0x0000000102310420 -[RCTModuleData setUpInstanceAndBridge:] + 2168
27  RecipeProdigy                       0x0000000102312110 __25-[RCTModuleData instance]_block_invoke + 44
28  RecipeProdigy                       0x000000010237a390 RCTUnsafeExecuteOnMainQueueSync + 52
29  RecipeProdigy                       0x0000000102311d78 -[RCTModuleData instance] + 816
30  RecipeProdigy                       0x00000001022be1ec __49-[RCTCxxBridge _prepareModulesWithDispatchGroup:]_block_invoke + 156
31  libdispatch.dylib                   0x000000010a8a8528 _dispatch_call_block_and_release + 24
32  libdispatch.dylib                   0x000000010a8a9d50 _dispatch_client_callout + 16
33  libdispatch.dylib                   0x000000010a8ba978 _dispatch_main_queue_drain + 1684
34  libdispatch.dylib                   0x000000010a8ba2d4 _dispatch_main_queue_callback_4CF + 40
35  CoreFoundation                      0x0000000109831784 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
36  CoreFoundation                      0x000000010982bde4 __CFRunLoopRun + 1912
37  CoreFoundation                      0x000000010982b254 CFRunLoopRunSpecific + 584
38  GraphicsServices                    0x000000010b7dbc9c GSEventRunModal + 160
39  UIKitCore                           0x000000012ad6eff0 -[UIApplication _run] + 868
40  UIKitCore                           0x000000012ad72f3c UIApplicationMain + 124
41  RecipeProdigy                       0x00000001020b6180 main + 100
```
