### ISSUE TITLE
Error using CollectionReference onSnapshot when trying to pass options (with includeMetadataChanges) as first parameter 

### ISSUE THREAD

**Issue by callagga** [invertase/react-native-firebase#719]
I am getting a "Query.onSnapshot failed: First argument must be a function, observer or options" error when I modify my working code to include an options parameter for onSnapshot.  

Q1 - Is there something I am doing wrong here or is this a Firebase issue as per https://github.com/invertase/react-native-firebase/issues/613?   

Q2 - Note I am using includeMetadataChanges as mentioned in teh documentation at https://rnfirebase.io/docs/v3.1.*/firestore/reference/CollectionReference#onSnapshot.  However is this correct or should the documentation read "includeDocumentMetaDataChanges"?  In any case I get the same error.  

Q3 - If it is a know error is there a work around if I am striving to be able to highlight my list in the UI to indicate a different color for rows that have already saved to firebase, versus rows that are yet to be saved (e.g. may have been out of network range for a period).

Code:

```
function createListChannel() {
  return eventChannel((emit) => {
    // 1st Argument - subscriber function
    console.log('List Updates being Requested');
    firebase.firestore().collection('todos').onSnapshot(
      { includeMetadataChanges: false },   // ** ERROR when I add this **
      (querySnapshot) => {
        const items = querySnapshot.docs.map(doc => ({ 
          id: doc.id,
          fromCache: doc.metadata.fromCache,
          hasPendingWrites: doc.metadata.hasPendingWrites,
          title: doc.data().title,
        }));
        emit({ items, error: undefined });
      },
      (error) => {
        emit(null, error);
      },
    );
    // 2nd Argument - unsubscribe function
    const unsubscribe = () => {
      console.log('TBC - Unsubscribe for listSagas.js');
    };
    return unsubscribe;
  });
}
```

Error:

```
 ExceptionsManager.js:73
 at rootSaga 
 Error: Query.onSnapshot failed: First argument must be a function, observer or options.
    at Query.onSnapshot (/Users/Greg/Dropbox/source_reactnative/gcTodo/node_modules/react-native-firebase/dist/modules/firestore/Query.js:120:15)
    at CollectionReference.onSnapshot (/Users/Greg/Dropbox/source_reactnative/gcTodo/node_modules/react-native-firebase/dist/modules/firestore/CollectionReference.js:67:24)
    at /Users/Greg/Dropbox/source_reactnative/gcTodo/app/sagas/listSagas.js:64:46
    at eventChannel (/Users/Greg/Dropbox/source_reactnative/gcTodo/node_modules/redux-saga/lib/internal/channel.js:165:21)
    at createListChannel (/Users/Greg/Dropbox/source_reactnative/gcTodo/app/sagas/listSagas.js:61:23)
    at updatedListsSaga$ (/Users/Greg/Dropbox/source_reactnative/gcTodo/app/sagas/listSagas.js:101:25)
    at tryCatch (/Users/Greg/Dropbox/source_reactnative/gcTodo/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/Greg/Dropbox/source_reactnative/gcTodo/node_modules/regenerator-runtime/runtime.js:337:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/Greg/Dropbox/source_reactnative/gcTodo/node_modules/regenerator-runtime/runtime.js:96:21)
    at next (/Users/Greg/Dropbox/source_reactnative/gcTodo/node_modules/redux-saga/lib/internal/proc.js:322:27)

```

**Comment by chrisbianca** [comment]
@calclavia Try `includeDocumentMetadataChanges` - note that the `d` in `Metadata` is lowercase. If that works, I'll update the documentation

**Comment by callagga** [comment]
still seem to get the same error with this

ie using:
```
function createListChannel() {
  return eventChannel((emit) => {
    // 1st Argument - subscriber function
    console.log('List Updates being Requested');
    firebase.firestore().collection('todos').onSnapshot(
      { includeDocumentMetadataChanges: false },
      // { includeMetadataChanges: false },
      (querySnapshot) => {
        const items = querySnapshot.docs.map(doc => ({ 
          id: doc.id,
          fromCache: doc.metadata.fromCache,
          hasPendingWrites: doc.metadata.hasPendingWrites,
          title: doc.data().title,
        }));
        emit({ items, error: undefined });
      },
      (error) => {
        emit(null, error);
      },
    );
    // 2nd Argument - unsubscribe function
    const unsubscribe = () => {
      console.log('TBC - Unsubscribe for listSagas.js');
    };
    return unsubscribe;
  });
}
```

getting
```
    at Query.onSnapshot (/Users/Greg/Dropbox/source_reactnative/gcTodo/node_modules/react-native-firebase/dist/modules/firestore/Query.js:120:15)
    at CollectionReference.onSnapshot (/Users/Greg/Dropbox/source_reactnative/gcTodo/node_modules/react-native-firebase/dist/modules/firestore/CollectionReference.js:67:24)
    at /Users/Greg/Dropbox/source_reactnative/gcTodo/app/sagas/listSagas.js:64:46
    at eventChannel (/Users/Greg/Dropbox/source_reactnative/gcTodo/node_modules/redux-saga/lib/internal/channel.js:165:21)
    at createListChannel (/Users/Greg/Dropbox/source_reactnative/gcTodo/app/sagas/listSagas.js:61:23)
    at updatedListsSaga$ (/Users/Greg/Dropbox/source_reactnative/gcTodo/app/sagas/listSagas.js:101:25)
    at tryCatch (/Users/Greg/Dropbox/source_reactnative/gcTodo/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/Greg/Dropbox/source_reactnative/gcTodo/node_modules/regenerator-runtime/runtime.js:337:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/Greg/Dropbox/source_reactnative/gcTodo/node_modules/regenerator-runtime/runtime.js:96:21)
    at next (/Users/Greg/Dropbox/source_reactnative/gcTodo/node_modules/redux-saga/lib/internal/proc.js:322:27)
```

**Comment by chrisbianca** [comment]
@callagga If you change `includeDocumentMetadataChanges` to be `true` does that work?  I think there might be a minor issue with how we're checking for presence of the flags

**Comment by callagga** [comment]
if I put "true" in instead it does NOT throw the error any more, however it also doesn't seem to give me the subsequent 2nd update when the backend does update things (if this makes sense).   i.e. for the new row I add it shows it as "pending" however I don't see it change to "Not Pending" after a short secord (or after I reenable my network connection, in the case I create a new record whilst not connected) - does this make sense?

**Comment by callagga** [comment]
This is a bug (not just documentation) I think.  Ie no way to get all the firestore updates available...

**Comment by callagga** [comment]
@chrisbianca - what do you think? Is this a bug in terms of not being able to get all the firestore updates available?

**Comment by Ehesp** [comment]
@callagga please hold on, we'll look at it when we can

**Comment by callagga** [comment]
ok thanks - got a response on the Google Firebase forum that confirms that firebase does pass back subsequent updates like I'm after, so getting "includeQueryMetadataChanges" is required, so it does seem to be a bug.  Response I got:

Questions

> a) when Offline the listener function would fire to confirm the update (even though offline), although the doc's may be marked "hasPendingUpdates"
> 
> b) when the device then comes back online, should the same listener fire again?  So you effectively get the data back a 2nd time to the client code BUT this time the documents would be not marked with "hasPendingUpdates" (** this is what I'm trying to get working **)
> 
> c) if the answer for b) above is YES, then is there only one (1) firing for the listener even though there may have been multiple document updates whilst the device is offline?
> 
> d) when ONLINE should there be two listener firing events (one immediately, then another when backend is updated) or does the library check if online first such that there is only one (1) triggering of the listener? 

Responses

> In order to rely on hasPendingWrites, you need to set the includeQueryMetadataChanges option when you attach your onSnapshot() handler. I'm going to assume you're doing that.  Then the answers to your questions are:
> 
> a) yes, it should fire with the data you wrote and with hasPendingWrites = true
> b) yes, it should fire again with hasPendingWrites = false
> c) it should only fire if something actually changed (data or metadata) and so you shouldn't get repetitive events with the exact same snapshot contents.
> d) yes, there will be 2 events when online as well (once with hasPendingWrites = true, once with = false).
>

**Comment by chrisbianca** [comment]
Have you tried with `includeQueryMetadataChanges` as suggested by Firebase's response?
In your examples above, you have only spoken about using `includeDocumentMetadataChanges`.

**Comment by callagga** [comment]
setting includeQueryMetadataChanges to true does NOT help (should have mentioned I'd tried that) unfortunately.  So it does seem there is way to get all the firestore updates available...

**Comment by chrisbianca** [comment]
Have you confirmed that the incorrect behaviour is consistent across iOS and Android?
This certainly does look like a bug, but, it would be good to understand if it's one or both platforms. Regardless of that though, the likelihood is that this is an underlying bug in the Firebase SDK...

**Comment by callagga** [comment]
I'll have to get back to you re Android, as it was on IOS I have been testing.  I should point out this is on the IOS simulator too.

**Comment by callagga** [comment]
(still haven't had a chance to setup/reproduce on Android)

All - anyone actually ever seen the 2nd expected response come back from firestore?

**Comment by chrisbianca** [comment]
FYI - I've updated the docs with the correct option names

**Comment by callagga** [comment]
FYI - was able to confirm the expected 2nd event operation directly here:

```
<html>
<script src="https://www.gstatic.com/firebasejs/4.9.0/firebase.js"></script>
<script src="https://www.gstatic.com/firebasejs/4.9.0/firebase-firestore.js"></script>
<script>
  // Initialize Firebase
  // Copy / paste web snippet from: https://console.firebase.google.com/
  var config = {
    //...I deleted my details, but copy paste it in here...
  };
  firebase.initializeApp(config);
  const db = firebase.firestore();
  console.log('----------- Start Up ----------');
  db.collection('foo').onSnapshot({ includeQueryMetadataChanges: true }, querySnapshot => {
    console.log('----------- Update Received ----------');
    const numCached = querySnapshot.docs.reduce((acc, curr) => acc + (curr.metadata.fromCache ? 1 : 0), 0);
    const numPending = querySnapshot.docs.reduce((acc, curr) => acc + (curr.metadata.hasPendingWrites ? 1 : 0), 0);
    const numChanged = querySnapshot.docChanges.length;
    console.log(`updatedListsSaga Callback: #Docs=${querySnapshot.size}, #Changes=${numChanged}, #Cached=${numCached}  #Pending=${numPending} `);
    // console.log('docs', querySnapshot.docs.map(doc => doc.data()));
    // console.log('metadata', querySnapshot.metadata);
  });

  setTimeout(() => {
    console.log('----------- Add New Item ----------');
    db.collection('foo').add({time: new Date().getTime() });
  }, 5000);
</script>
</html>
```

with console output:

```
index.html:18 ----------- Start Up ----------
index.html:20 ----------- Update Received ----------
index.html:24 updatedListsSaga Callback: #Docs=2, #Changes=2, #Cached=0  #Pending=0 
index.html:30 ----------- Add New Item ----------
index.html:20 ----------- Update Received ----------
index.html:24 updatedListsSaga Callback: #Docs=3, #Changes=1, #Cached=0  #Pending=1 
index.html:20 ----------- Update Received ----------
index.html:24 updatedListsSaga Callback: #Docs=3, #Changes=0, #Cached=0  #Pending=0 
```

**Comment by callagga** [comment]
FYI - I swapped out "react-native-firebase" with just "firebase" in my react test app, and now the two events are coming through fine (only tried on IOS so far).  So when coming back online after changes offline you get the automatic synch under the bonnet happening which you can see (as it's the 2nd event that gives this)

**Comment by callagga** [comment]
Note whilst there is an issue in general re "react-native-firebase" once this is resolved currently there seems to be another specific issue for android as mentioned in comments https://github.com/invertase/react-native-firebase/issues/765, in the Firebase JS SDK.

**Comment by chrisbianca** [comment]
@callagga Are you able to try the latest version of the Firebase pods (v4.8.1)?

There was a note in their release notes (https://firebase.google.com/support/release-notes/ios#4.8.1):

```
Snapshot listeners (with the includeMetadataChanges option enabled) now receive an event with snapshot.metadata.isFromCache set to true if the SDK loses its connection to the backend. A new event with snapshot.metadata.isFromCache set to false will be raised once the connection is restored and the query is in sync with the backend again.
```

**Comment by callagga** [comment]
haven't had a chance to test yet - I did migrate my project (hobbyist) to be based on firebase/firebase-js-sdk as I mentioned so will have to swap back...  

Mind if I ask, in fact, what are the pros/cons of using firebase/firebase-js-sdk versus react-native-firebase, i.e. noting it seems the former doesn't require the extended setup with pods etc?  I'm just doing some basic firestore currently but probably want to incorporate authentication after.

**Comment by chrisbianca** [comment]
@callagga It's predominately performance and feature set. You can find some more information in the introduction section and a side by side comparison on features here: https://github.com/invertase/react-native-firebase

**Comment by chrisbianca** [comment]
I'm going to close this as the issue has gone quiet and we've not had any further reports.
Please re-open with more information if it's still an issue.
