### ISSUE TITLE
firebase.analytics is not a function

### ISSUE THREAD

**Issue by louiszawadzki** [invertase/react-native-firebase#72]
Hi,

I'm trying to add Firebase analytics on my Android app.
I've followed the documentation to install react-native-firebase, but I get a `firebase.analytics is not a function` error when I call `firebase.analytics().logEvent('app_started');`.

Here's my code:

`config/firebase.js`
```
import RNFirebase from 'react-native-firebase';

const configurationOptions = {
  debug: true,
};

const firebase = RNFirebase.initializeApp(configurationOptions);

console.log(firebase);

export default firebase;
```

in `App.js`:
```
const firebase = require('./config/firebase');
firebase.analytics().logEvent('app_started');
```

When I console.log `firebase` just before call here's what comes up:

![screenshot from 2017-04-28 14-14-56](https://cloud.githubusercontent.com/assets/8973379/25530157/2ab1c194-2c1d-11e7-9f42-be83fe3f3be2.png)

**Comment by Salakar** [comment]
@louiszawadzki can you go into the RNFirebase module inside node_modules folder and tell me what version is state on the package.json - looks like you're using a dated version. If you're using yarn remove the yarn.lock file in the root of your project and install the latest alpha again.

**Comment by louiszawadzki** [comment]
@Salakar I'm using version 1.0.0-alpha13

**Comment by Salakar** [comment]
@louiszawadzki believe I may have fixed possible issues with this on master branch, any chance you can install from master and try?

**Comment by louiszawadzki** [comment]
hi @Salakar, I'm using version 1.0.2 and it's not fixed.

However, I managed to fix it by renaming `firebase` to something else like `firebaseInstance` in my `config/firebase.js`.

I've also tried it on a fresh app (using `react-native init`) and I see the exact same result.

**Comment by Ehesp** [comment]
@louiszawadzki could you try with the latest version? Tests are all passing with it our end, so I can't really see what the issue is to be honest!

**Comment by Ehesp** [comment]
Please let us know if you are still having this issue.
