### ISSUE TITLE
[🐛]  firebase.messaging() , firebase module that's not installed natively

### ISSUE THREAD

**Issue by thidasapankaja** [invertase/react-native-firebase#7204]
## Issue

```
Possible Unhandled Promise Rejection (id: 0): 
Error: You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.messaging()

Ensure you have either linked the module or added it to your projects Podfile
```

---

We already have firebase configured and been using firebase analytics.

I'm just using firebase/messaging to access the push notifications which send via Salesforce Marketing Cloud.

I followed this https://rnfirebase.io/messaging/usage and currently using the below function to request the permission on app initialize

```
const requestPushPermission = async () => {
  const authStatus = await messaging().requestPermission();
  const enabled =
    authStatus === messaging.AuthorizationStatus.AUTHORIZED || authStatus === messaging.AuthorizationStatus.PROVISIONAL;

  if (enabled) {
    console.log('Authorization status:', authStatus);
  }
};
```

But I'm getting an error here

**Comment by mikehardy** [comment]
The error is pretty prescriptive.
You *think* you have installed the module, but in fact, the module's code has not been built + installed into the app that is running on the actual device.

You'll need to determine why (make sure you add the reat-native-firebase/messaging package, `pod install` then a rebuild perhaps?) and that will resolve it.

It is a project-specific issue though and will not result in a code change here, so it is not really actionable. I will close this
