### ISSUE TITLE
[📚] Documentation Issue google_analytics_adid_collection_enabled undocumented

### ISSUE THREAD

**Issue by ruipaulo** [invertase/react-native-firebase#7213]
## Documentation Feedback

I think it is not documented how to disable ad id collection in android. Probably that has changed recently. It took me quite a while to figure it out and I had to read the source code to understand what was happening, but in the end it is trivial. 
There is a parameter `google_analytics_adid_collection_enabled` in the firebase.json. 

I think there should be a paragraph added to https://rnfirebase.io/analytics/usage#firebasejson or https://rnfirebase.io/analytics/usage#firebasejson

If you agree that documentation is needed, I would be willing to write it. 

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Oh! Sorry about that, I did add that one recently. I made my best attempt to make sure that if you wanted a zero collection app that I implemented all the various toggles and switches (there are a ton of them!) and I'm sorry that the documentation didn't make it easy to see they were available

If you're willing to give a try to improving the documentation I'd love the help, happy to merge a PR! Cheers

**Comment by ruipaulo** [comment]
Hey @mikehardy thanks for answering (and implementing it! 😀). I will write a documentation paragraph and post it later here. Unfortunately the flag did not change the outcome, google play store was still complaining that the app id was used. Did it work for you? We decided, that we simply declare the usage of the ad id.

**Comment by mikehardy** [comment]
Have you included the correct pod? https://rnfirebase.io/analytics/usage#disable-ad-id-usage-on-ios

**Comment by ruipaulo** [comment]
This is Android, so I am not sure how the pod istallation on ios is related?

**Comment by mikehardy** [comment]
> This is Android, so I am not sure how the pod istallation on ios is related?

🤦 sorry - should have picked that up from context of google complaining, I did not read closely enough and was all excited that I thought I had an on-target idea. Clearly was not on-target, apologies 😆 


> google play store was still complaining that the app id was used

I think you mean "ad id"? Not "app id"?

This is the related issue upstream: https://github.com/firebase/firebase-android-sdk/issues/2582

The solution is to use firebase.json to disable things (as you are doing), *and* declare in the play console that 3rd part libraries are using it for analytics, and that should satisfy google play console but without declaring that your app shows ads.

Some others on that issue tried more involved things (like, excluding transitive dependencies and stuff...) but I would not recommend that personally as it sounds like a maintenance nightmare

**Comment by ruipaulo** [comment]
I am closing this, as we did not solve it, but declared the needed permission instead. I think having this feature working would be useful for many apps.

**Comment by paul-rinaldi** [comment]
Seeing this again with `"@react-native-firebase/analytics": "^18.7.3"`. 
When building with expo, you'll see the error:
```
Google Api Error: Invalid request - This release includes the com.google.android.gms.permission.AD_ID permission but your declaration on Play Console says your app doesn't use advertising ID. You must update your advertising ID declaration.
```

Since we don't actually have ads, as others are saying, we would not like to add the declaration.

So, I tried the [suggested solution from the Google Play Console Team](https://support.google.com/googleplay/android-developer/thread/236755877?hl=en&msgid=236860799) of adding this line  `<uses-permission android:name="com.google.android.gms.permission.AD_ID" tools:node="remove"/>` to the permissions list in the `android/app/src/main/AndroidManifest.xml` (with expo plugin successfully) and when build, gradle errors out:
```
> Task :app:processDebugGoogleServices
Parsing json file: /Users/paulrinaldi/Documents/.../projectname/android/app/google-services.json

> Task :app:processDebugMainManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing /Users/paulrinaldi/Documents/.../projectname/android/app/src/main/AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 18s
157 actionable tasks: 40 executed, 112 from cache, 5 up-to-date
Error: /Users/paulrinaldi/Documents/.../projectname/android/gradlew exited with non-zero code: 1
Error: /Users/paulrinaldi/Documents/.../projectname/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/paulrinaldi/Documents/.../projectname/node_modules/@expo/cli/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at Object.spawnAsync [as default] (/Users/paulrinaldi/Documents/.../projectname/node_modules/@expo/cli/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnGradleAsync (/Users/paulrinaldi/Documents/.../projectname/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:72:46)
    at Object.assembleAsync (/Users/paulrinaldi/Documents/.../projectname/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:52:18)
    at runAndroidAsync (/Users/paulrinaldi/Documents/.../projectname/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:36:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Removing that line and trying to build android (with expo) builds and runs correctly (though I then still can't submit to google play unless I changed the declaration).

Should I declare something in my `google-services.json` (firebase)? Anyone else seeing this? What am I missing?

**Comment by mikehardy** [comment]
Something about the removal is wrong, unsure what. Perhaps Expo does not by default includes the "tools" XML namespace required to use the `tools:remove` line?

https://developer.android.com/build/manage-manifests#merge_rule_markers

> All markers belong to the Android tools namespace, so you must first declare this namespace in the <manifest> element, as shown here:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.myapp"
    xmlns:tools="http://schemas.android.com/tools">
```

This mentions it, in a bare react-native context at least https://docs.expo.dev/guides/permissions/#are-you-using-this-library-in-a

**Comment by paul-rinaldi** [comment]
Ah this is making sense. When I open the android folder correctly in android studio and open the manifest I see red highlights on `node:tools` with the error window stating "Namespace 'tools' is not bound."

My debug manifest does have:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
```

When I do what the error recommends "Create namespace declaration", it adds that attribute (`xmlns:tools="http://schemas.android.com/tools"`) to the manifest (which I wrote about initially, `android/app/src/main/AndroidManifest.xml`). Then when I run `yarn run android` it works. So I suppose I need the tools attribute adding in expo as well along with this change. Thank you @mikehardy good recommendation.

**Comment by liveakshay** [comment]
The [RNfirebase](https://rnfirebase.io/analytics/usage) documentation hasn't caught up to this, as far as I can tell.  Is this true, please reply, I am happy to contribute if needed.

**Comment by mikehardy** [comment]
@liveakshay I believe you are correct, the ability to toggle that to false in AndroidManifest.xml via firebase.json is built:

https://github.com/search?q=repo%3Ainvertase%2Freact-native-firebase%20google_analytics_adid_collection_enabled&type=code

But there's no documentation surrounding it other than the schema reference page, and there's no mention of people that want to get rid of it completely altering their app-level AndroidManifest to include the tools namespace and using tools:remove to remove the AD_ID uses-permission entry

A docs addition that did all/any of that would be most welcome!

**Comment by mikehardy** [comment]
I'll reiterate:

> A docs addition that did all/any of that would be most welcome!

And I had an additional though, if people are using this in a react-native context, then an extension to the analytics plugin that added this ability to add the xmlns tools namespace (if it was missing) and did a tools:remove on that item if the plugin was requested to do so would be a great PR

**Comment by aravi365** [comment]
Getting the same error in android react native cli project as well. Confused which is the correct solution after going through many different issues reported. @mikehardy  please guide what to be done. WIll it be resolved if i add  `"google_analytics_adid_collection_enabled": true,` in the firebase.json?

context:
`"This release includes the com.google.android.gms.permission.AD_ID permission but your declaration on Play Console says your app doesn't use advertising ID. You must update your advertising ID declaration"`
