### ISSUE TITLE
Crashlytics dashboard is not open

### ISSUE THREAD

**Issue by siyarammalav-cnel** [invertase/react-native-firebase#7223]
I'm adding Firebase Crashlytics to my React-Native app. And then I follow the docs to add it. 
After adding depenmdc and plugin to my project and then I build the app and then check in firebase the crashlytics dashboard is not opening.
I don't know why this happens, why the dashboard doesn't open. It is still showing add sdk.

Documenction Link : https://rnfirebase.io/crashlytics/usage

Can you please help me to resole this issue.

**Comment by RaviKumar-msys** [comment]
With in root folder create firebase.json and add {
  "react-native": {
    "crashlytics_ndk_enabled": false
  }
}

**Comment by siyarammalav-cnel** [comment]
not working.

**Comment by siyarammalav-cnel** [comment]
{
    "react-native": {
      "crashlytics_debug_enabled": true
    }
  } 

I have added this code in firebase.json and now crashlytics dashboard is opened
