### ISSUE TITLE
[🐛] HTTPs Callable Functions Serialization - Undefined arguments not converted to null

### ISSUE THREAD

**Issue by VictorioMolina** [invertase/react-native-firebase#7227]
Today, I have decided to migrate to this library. Everything goes nice but there is something I have noticed with HTTPs Callable Functions.

In the official Firebase JS SDK, when you call a Firebase Cloud Function using functions.httpsCallable, the parameters you pass are converted into an HTTP request to the function on the Firebase server. During this process, the parameter values are __serialized__ and sent over the network.

When you use { id: undefined } on the client-side, the Firebase JS SDK serializes this value as `null` before sending it to the cloud. Imo, this is an established convention to maintain consistency in how data is handled across different languages and platforms. On the Firebase server-side, when the Cloud Function receives the request, the `null` value is interpreted as `null` and not as `undefined`.

Is there any config we have to pass to this package in order to automatically serialize and convert those `undefined` and other special values when invoking a function? When I do:

```
functions().httpsCallable("someFunction")({ someField: undefined });
```

I get `undefined` on the server, and not `null`, something which breaks some of the logic behind my data validations.

**Comment by Gsiete** [comment]
I'm having the opposite issue I think. My undefined values are getting wrongly transformed to null.
Null is not undefined. See for instance firestore, where with the right config undefined is ignored.
