### ISSUE TITLE
Local notification not displaying in React Native Android App

### ISSUE THREAD

**Issue by jbienia** [invertase/react-native-firebase#723]
My local notifications are not displaying in the Android emulator. I'm able to send local notifications through the firebase console and they display properly. But when I use the code firebase.messaging().createLocalNotification({
            body: "body",
            icon: "ic_launcher",
            show_in_foreground: true,
            title: "title",
            local_notification: true,
            priority: "high",
            click_action:"ACTION"
        }); ...nothing displays

If I use the onMessage() function I can see that I'm receiving the notification, but I'm not seeing the notification in the Android notification tray. Does anyone have experience with notifications and the react-native-firebase invertase library?

### Environment

1. Android

2. Mac

3. Build Tools: 
Android - '23.0.3'

4. React Native version: 
"react-native": "0.48.3",

5. RNFirebase Version: 
"react-native-firebase": "^3.0.2",

6. Firebase Module: 
FCM

**Comment by reznik789** [comment]
I don't know why this functionality not described in documentation, maybe this functionality are in develop progress, but I also get this issue. I find solution using Android Monitor in Android Studio.

> Key show_in_foreground expected Boolean but value was a java.lang.String.  The default value false was returned.

All what you need is change 
`show_in_foreground: "true"`
to
`show_in_foreground: true`

**Comment by Ehesp** [comment]
@reznik789 PR welcome :D

**Comment by jbienia** [comment]
@reznik789 Yeah I've tried that already. I don't get any result. I can see the data in the console, so the app is receiving the local notification, but it just won't display. Did you have to do anything specific to the emulator?
![screen shot 2018-01-05 at 8 24 04 am](https://user-images.githubusercontent.com/15094461/34617968-0d8f7138-f1f2-11e7-86c4-f6ec7d80b3ee.png)

**Comment by jbienia** [comment]
It was the lack of an icon. You must have the icon set. Using the Android Device Monitor is really helpful and gives more information about notification errors. Local notifications are displaying properly. Love the library!!
