### ISSUE TITLE
[🐛] Allow disabling usage of PhotoKit API on iOS

### ISSUE THREAD

**Issue by nicodeory-homa** [invertase/react-native-firebase#7230]
## Issue

The following file `@react-native-firebase/app/ios/RNFBApp/RNFBUtilsModule.m` contains the method `fetchAssetForPath` which handles fetching files from the user's photo directory. 

This is not used in my app since the only place this method is called is inside `packages/storage/ios/RNFBStorage/RNFBStorageCommon.m`. I don't have `@react-native-firebase/storage` installed so this should never be called.

However, when publishing the built binary to App Store Connect, the automatic analyzer raises the following issue:

> ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “XXX.app” bundle should contain a NSPhotoLibraryUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.

The clear workaround is to add an usage description, but I have tracked down this problem to `react-native-firebase` which is the only package that uses an iOS library that can raise this issue.

There should be a compile-time option to disable this code so that this permission issue is not raised.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Sorry this went stale. I think this is a valid request - photo access is something privacy-oriented people are concerned about - there shouldn't be a need in the common package for what is effectively a storage-package-specific item.

**Comment by munjalpatel** [comment]
I am also having the same problem. I only use Firebase Device Check / App Attest. But it depends on Firebase Core. Hence, my app is not getting published until I specify `NSPhotoLibraryUsageDescription` in Info.plist. However, my app is not using Photo Library and user's shouldn't be forced to grant this permission.
