### ISSUE TITLE
[🐛] Unexpected crash on React Native 0.72.1

### ISSUE THREAD

**Issue by LeleDallas** [invertase/react-native-firebase#7237]
## Issue

I followed the official guide at [rnfirebase.io](https://rnfirebase.io/) to install Firebase in my React Native CLI application. However, after completing the installation steps, my application started crashing.

Here's a small part of the report generated:
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 05C07174-0433-493D-AA0B-78FA09A399D4
CrashReporter Key:   912D355E-67D3-CFE2-84B7-0F18FCA9F884
Hardware Model:      MacBookAir10,1
Process:             MyApp [23698]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/E5E13BEA-BE83-4802-B8FF-7FFB7C118444/data/Containers/Bundle/Application/78758700-F420-42CF-840D-384173BBD908/MyApp.app/MyApp
Identifier:          com.myapp.myapp
Version:             1.0 (1)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      Exited process [23769]
Coalition:           com.apple.CoreSimulator.SimDevice.E5E13BEA-BE83-4802-B8FF-7FFB7C118444 [3713]
Responsible Process: SimulatorTrampoline [3234]

Date/Time:           2023-07-14 16:56:19.0775 +0200
Launch Time:         2023-07-14 16:55:46.1299 +0200
OS Version:          macOS 13.4.1 (22F82)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0

```
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@gorhom/bottom-sheet": "^4.4.7",
    "@react-native-async-storage/async-storage": "^1.19.0",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-firebase/app": "^18.2.0",
    "@react-native-picker/picker": "^2.4.10",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/stack": "^6.3.17",
    "@reduxjs/toolkit": "^1.9.5",
    "@rnmapbox/maps": "^10.0.9-rc.1",
    "@shopify/react-native-skia": "^0.1.197",
    "axios": "^1.4.0",
    "d3": "^7.8.5",
    "d3-scale": "^4.0.2",
    "jwt-decode": "^3.1.2",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-native": "0.72.1",
    "react-native-calendars": "^1.1299.0",
    "react-native-config": "^1.5.1",
    "react-native-device-info": "^10.7.0",
    "react-native-elements": "^3.4.3",
    "react-native-gesture-handler": "^2.12.0",
    "react-native-graph": "^1.0.2",
    "react-native-linear-gradient": "^2.7.3",
    "react-native-reanimated": "^3.3.0",
    "react-native-safe-area-context": "^4.6.4",
    "react-native-screens": "^3.22.1",
    "react-native-skeleton-placeholder": "^5.2.4",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "^13.10.0",
    "react-native-vector-icons": "^9.2.0",
    "react-redux": "^8.1.1",
    "styled-components": "^6.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.7",
    "@tsconfig/react-native": "^3.0.0",
    "@types/d3": "^7.4.0",
    "@types/metro-config": "^0.76.3",
    "@types/react": "^18.0.24",
    "@types/react-native-snap-carousel": "^3.8.5",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.5",
    "prettier": "^2.4.1",
    "react-native-iconfont-cli": "^2.2.4",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
Not required in the guide
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
$RNMapboxMapsImpl = 'mapbox'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!


# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
target 'MyApp' do
  config = use_native_modules!
  use_frameworks! :linkage => :static # for Firebase
  $RNFirebaseAsStaticFramework = true # for Firebase
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MyAppTests' do
    inherit! :complete
    # Pods for testing
  end
  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end

  post_install do |installer|
    $RNMapboxMaps.post_install(installer)
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

```

#### `AppDelegate.mm`:

```objc
#import "AppDelegate.h"
#import <Firebase.h>
#import <React/RCTBundleURLProvider.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  self.moduleName = @"MyApp";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 05C07174-0433-493D-AA0B-78FA09A399D4
CrashReporter Key:   912D355E-67D3-CFE2-84B7-0F18FCA9F884
Hardware Model:      MacBookAir10,1
Process:             MyApp [23698]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/E5E13BEA-BE83-4802-B8FF-7FFB7C118444/data/Containers/Bundle/Application/78758700-F420-42CF-840D-384173BBD908/MyApp.app/MyApp
Identifier:          com.myapp.myapp
Version:             1.0 (1)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      Exited process [23769]
Coalition:           com.apple.CoreSimulator.SimDevice.E5E13BEA-BE83-4802-B8FF-7FFB7C118444 [3713]
Responsible Process: SimulatorTrampoline [3234]

Date/Time:           2023-07-14 16:56:19.0775 +0200
Launch Time:         2023-07-14 16:55:46.1299 +0200
OS Version:          macOS 13.4.1 (22F82)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0

```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `react-native-firebase/app ^18.2.0`
- **Are you using `TypeScript`?**
  - `Y` & `4.8.4`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by neeteshraj** [comment]
is it fixed yet?

**Comment by LeleDallas** [comment]
> is it fixed yet?

No I'm still waiting a PR that could solve that

**Comment by ajlee4** [comment]
any update?

**Comment by LeleDallas** [comment]
> any update?

Maybe #7250 could help

**Comment by lmahoudeau** [comment]
Hello,

This doesn't fix the problem for me. I still have the same issue with android application.
I have to downgrade React-Native to 0.71.12 to make it work, which is not an acceptable work around to maintain all my librairies up-to-date.

Could you please make a move on with this issue, cause react-native is already at the 0.72.4 revision and still nothing for months ... 

It's unbelievable that a google librairie is in such a state ... I will have to consider finding another way of doing analytics with my applications soon. It's a shame :o( ...

Please help.

**Comment by mikehardy** [comment]
Hi there!
I don't see a stack trace here that points to the  react-native-firebase code.
I do have an example here that compiles fine (and has always compiled fine as new versions come out...) with current react-native - https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

It is currently updated to react-native 0.72.3 and appears to work for me.

If someone can post a stack trace showing exactly how this relates to react-native-firebase, or can post an example repository  that demonstrates the problem, or can run make-demo.sh as linked above to maybe isolate it to a problem in their environment, we can make some progress

**Comment by lmahoudeau** [comment]
Hi Mike,

here is the error running gradlew :app:assembleRelease with the stacktrace:

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':react-native-firebase_app:extractDeepLinksForAarRelease' (type 'ExtractDeepLinksTask').
  - Gradle detected a problem with the following location: 'E:\git_sources\bus-on-time-app\node_modules\@react-native-firebase\app\android\build\generated\res\rs\release\navigation'.

    Reason: Task ':react-native-firebase_app:extractDeepLinksForAarRelease' uses this output of task ':@react-native-firebase_app:compileReleaseRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':@react-native-firebase_app:compileReleaseRenderscript' as an input of ':react-native-firebase_app:extractDeepLinksForAarRelease'.
      2. Declare an explicit dependency on ':@react-native-firebase_app:compileReleaseRenderscript' from ':react-native-firebase_app:extractDeepLinksForAarRelease' using Task#dependsOn.
      3. Declare an explicit dependency on ':@react-native-firebase_app:compileReleaseRenderscript' from ':react-native-firebase_app:extractDeepLinksForAarRelease' using Task#mustRunAfter.

    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'E:\git_sources\bus-on-time-app\node_modules\@react-native-firebase\app\android\build\generated\res\resValues\release\navigation'.

    Reason: Task ':react-native-firebase_app:extractDeepLinksForAarRelease' uses this output of task ':@react-native-firebase_app:generateReleaseResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':@react-native-firebase_app:generateReleaseResValues' as an input of ':react-native-firebase_app:extractDeepLinksForAarRelease'.
      2. Declare an explicit dependency on ':@react-native-firebase_app:generateReleaseResValues' from ':react-native-firebase_app:extractDeepLinksForAarRelease' using Task#dependsOn.
      3. Declare an explicit dependency on ':@react-native-firebase_app:generateReleaseResValues' from ':react-native-firebase_app:extractDeepLinksForAarRelease' using Task#mustRunAfter.

    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.internal.execution.WorkValidationException: Some problems were found with the configuration of task ':react-native-firebase_app:extractDeepLinksForAarRelease' (type 'ExtractDeepLinksTask').
  - Gradle detected a problem with the following location: 'E:\git_sources\bus-on-time-app\node_modules\@react-native-firebase\app\android\build\generated\res\rs\release\navigation'.

    Reason: Task ':react-native-firebase_app:extractDeepLinksForAarRelease' uses this output of task ':@react-native-firebase_app:compileReleaseRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':@react-native-firebase_app:compileReleaseRenderscript' as an input of ':react-native-firebase_app:extractDeepLinksForAarRelease'.
      2. Declare an explicit dependency on ':@react-native-firebase_app:compileReleaseRenderscript' from ':react-native-firebase_app:extractDeepLinksForAarRelease' using Task#dependsOn.
      3. Declare an explicit dependency on ':@react-native-firebase_app:compileReleaseRenderscript' from ':react-native-firebase_app:extractDeepLinksForAarRelease' using Task#mustRunAfter.

    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'E:\git_sources\bus-on-time-app\node_modules\@react-native-firebase\app\android\build\generated\res\resValues\release\navigation'.

    Reason: Task ':react-native-firebase_app:extractDeepLinksForAarRelease' uses this output of task ':@react-native-firebase_app:generateReleaseResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':@react-native-firebase_app:generateReleaseResValues' as an input of ':react-native-firebase_app:extractDeepLinksForAarRelease'.
      2. Declare an explicit dependency on ':@react-native-firebase_app:generateReleaseResValues' from ':react-native-firebase_app:extractDeepLinksForAarRelease' using Task#dependsOn.
      3. Declare an explicit dependency on ':@react-native-firebase_app:generateReleaseResValues' from ':react-native-firebase_app:extractDeepLinksForAarRelease' using Task#mustRunAfter.

    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
        at org.gradle.internal.execution.WorkValidationException$BuilderWithSummary.build(WorkValidationException.java:133)
        at org.gradle.internal.execution.WorkValidationException$BuilderWithSummary.get(WorkValidationException.java:115)
        at org.gradle.internal.execution.steps.ValidateStep.throwValidationException(ValidateStep.java:162)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:86)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:71)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:45)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNonEmptySources(SkipEmptyWorkStep.java:177)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:81)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:53)
        at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
        at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
        at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:75)
        at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:41)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:32)
        at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:287)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:21)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:42)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:31)
        at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:64)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:135)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)

Could you help with that ?

Many thanks.

**Comment by LeleDallas** [comment]
> Hi there!
> I don't see a stack trace here that points to the  react-native-firebase code.
> I do have an example here that compiles fine (and has always compiled fine as new versions come out...) with current react-native - https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
> 
> It is currently updated to react-native 0.72.3 and appears to work for me.
> 
> If someone can post a stack trace showing exactly how this relates to react-native-firebase, or can post an example repository  that demonstrates the problem, or can run make-demo.sh as linked above to maybe isolate it to a problem in their environment, we can make some progress

Ok, I'll try with that version

**Comment by ajlee4** [comment]
@mikehardy the same error occurs on your demo project

`-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 5A92704E-1BF4-44B8-BEC8-1EB0FFCE8AB2
CrashReporter Key:   3004270F-3CFD-71B1-E462-466BBF1FEE3E
Hardware Model:      MacBookPro16,1
Process:             rnfbdemo [73438]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/38E8FE5F-F83F-4FAA-A54A-654A64625EF0/data/Containers/Bundle/Application/D97C6B12-139B-4672-A6EA-7097DA4303F9/rnfbdemo.app/rnfbdemo
Identifier:          org.reactjs.native.example.rnfbdemo
Version:             1.0 (1)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [4741]
Coalition:           com.apple.CoreSimulator.SimDevice.38E8FE5F-F83F-4FAA-A54A-654A64625EF0 [50857]
Responsible Process: SimulatorTrampoline [1325]

Date/Time:           2023-08-24 11:09:51.6675 +0300
Launch Time:         2023-08-24 11:09:50.8406 +0300
OS Version:          macOS 13.2.1 (22D68)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0`

**Comment by mikehardy** [comment]
Interesting. There is still no stack trace, it is hard to see what's causing the problem without a stack trace

**Comment by LeleDallas** [comment]
> @mikehardy the same error occurs on your demo project
> 
> `
> -------------------------------------
> Translated Report (Full Report Below)
> -------------------------------------
> 
> Incident Identifier: 5A92704E-1BF4-44B8-BEC8-1EB0FFCE8AB2
> CrashReporter Key:   3004270F-3CFD-71B1-E462-466BBF1FEE3E
> Hardware Model:      MacBookPro16,1
> Process:             rnfbdemo [73438]
> Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/38E8FE5F-F83F-4FAA-A54A-654A64625EF0/data/Containers/Bundle/Application/D97C6B12-139B-4672-A6EA-7097DA4303F9/rnfbdemo.app/rnfbdemo
> **Identifier:          org.reactjs.native.example.rnfbdemo**
> Version:             1.0 (1)
> Code Type:           X86-64 (Native)
> Role:                Foreground
> Parent Process:      launchd_sim [4741]
> Coalition:           com.apple.CoreSimulator.SimDevice.38E8FE5F-F83F-4FAA-A54A-654A64625EF0 [50857]
> Responsible Process: SimulatorTrampoline [1325]
> 
> Date/Time:           2023-08-24 11:09:51.6675 +0300
> Launch Time:         2023-08-24 11:09:50.8406 +0300
> OS Version:          macOS 13.2.1 (22D68)
> Release Type:        User
> Report Version:      104
> 
> Exception Type:  EXC_CRASH (SIGABRT)
> Exception Codes: 0x0000000000000000, 0x0000000000000000
> Triggered by Thread:  0
> 
> `
> **UPD: we tried it on two different devices, but the error is the same**

Are you using an Apple M1 laptop?

**Comment by ajlee4** [comment]
@LeleDallas 
does the demo version work for you without errors?

<img width="287" alt="mac" src="https://github.com/invertase/react-native-firebase/assets/41113213/832b180f-ac7b-4e6a-bacf-d27ee34e71ce">

**Comment by LeleDallas** [comment]
> @LeleDallas 
> does the demo version work for you without errors?
> 
> <img width="287" alt="mac" src="https://github.com/invertase/react-native-firebase/assets/41113213/832b180f-ac7b-4e6a-bacf-d27ee34e71ce">
> 

No I'm still stucked

**Comment by ajlee4** [comment]
@LeleDallas 
maybe this is still a problem in the emulator, I'll try to run it on a real device today

**Comment by LeleDallas** [comment]
> @LeleDallas 
> maybe this is still a problem in the emulator, I'll try to run it on a real device today

Ok, let us know! 

But I think this issue is coming from flipper as we disable it as written in the documentation

**Comment by mikehardy** [comment]
@lmahoudeau I'm hiding your comments as they are not related in any way I can see to the original issue. The original reporter is having difficulty with crashes in Apple environments. You are posting android build errors. They are not related

**Comment by mikehardy** [comment]
Just to note I do not reproduce this on Intel or M1 macs, I run my make-demo.sh script on those all the time - both platforms, to make sure they are working since each platform has it's own issues from time to time.

So I still do not reproduce this, and most importantly from the perspective of troubleshooting: I have noted a couple times there is no stack trace. A "problem report" is *not* a stack trace. A stack trace shows the code that was executing at the time of the problem. It is required in order to help locate the issue.

In Apple lingo they use the word "backtrace" for this chunk of information we are looking for. Here is some background information that may help you recognize what the information is, what it means, and why we need it: https://developer.apple.com/documentation/xcode/analyzing-a-crash-report#Read-the-backtraces

**Comment by ajlee4** [comment]
@LeleDallas after a few days of torment, this comment helped me, check if you have a similar problem https://github.com/invertase/react-native-firebase/issues/472#issuecomment-334826731
