### ISSUE TITLE
[🐛] setBackgroundMessageHandler is called twice on Android

### ISSUE THREAD

**Issue by garciaaentrust** [invertase/react-native-firebase#7262]
## Issue

Hi there,

In my React Native Project, I have implemented the setBackgroundMessageHandler to handle incoming background messages. However, I have encountered an intermittent issue where the setBackgroundMessageHandler function seems to be called twice, resulting in 2 notifications displayed to the user. I have ensured that I register the setBackgroundMessageHandler only once in the codebase, and I have carefully reviewed the documentation multiple times to identify any mistakes, but I cannot pinpoint the source of the error.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

```typescript
export class NotificationManager {
  private static instance: NotificationManager;

  public static get = () => {
    if (!this.instance) this.instance = new NotificationManager();
    return this.instance;
  };

  constructor() {
    this.setUpPushNotifications();
  }

  private setUpPushNotifications = async () => {
    this.setUpFirebase();
    this.registerNotificationInteractionListeners();
  };

  private setUpFirebase = async () => {
    this.registerFirebaseMessageListeners();
    await firebase().registerDeviceForRemoteMessages();
    await this.updateFirebaseToken();
  };

  private registerNotificationInteractionListeners = () => {
    notifee.onForegroundEvent(this.onForegroundEvent);
    notifee.onBackgroundEvent(this.onBackgroundEvent);
  };

  private registerFirebaseMessageListeners = () => {
    firebase().onMessage(this.onNotification);
    firebase().setBackgroundMessageHandler(this.onNotification);
  };

  private updateFirebaseToken = async () => {
    const token = await firebase().getToken();
    await this.onTokenGenerated(token);
    firebase().onTokenRefresh(this.onTokenGenerated);
  };

```

#### `package.json`:

```json
"dependencies": {
    "@gorhom/bottom-sheet": "4.4.6",
    "@notifee/react-native": "7.4.0",
    "@react-native-async-storage/async-storage": "1.17.12",
    "@react-native-community/clipboard": "1.5.1",
    "@react-native-community/netinfo": "9.3.10",
    "@react-native-community/push-notification-ios": "1.11.0",
    "@react-native-firebase/analytics": "14.12.0",
    "@react-native-firebase/app": "14.12.0",
    "@react-native-firebase/messaging": "14.12.0",
    "dayjs": "1.11.7",
    "i18next": "22.4.13",
    "lodash.debounce": "4.0.8",
    "lottie-ios": "3.4.1",
    "lottie-react-native": "5.1.5",
    "mobx": "6.9.0",
    "mobx-persist": "0.4.1",
    "mobx-react": "7.6.0",
    "mobx-state-tree": "5.1.8",
    "nanoid": "4.0.1",
    "react": "18.2.0",
    "react-i18next": "12.2.0",
    "react-native": "0.71.8",
    "react-native-autolink": "4.0.0",
    "react-native-background-timer": "2.4.1",
    "react-native-camera-kit": "13.0.0",
    "react-native-device-info": "8.7.1",
    "react-native-elements": "3.4.2",
    "react-native-gesture-handler": "2.9.0",
    "react-native-haptic-feedback": "2.0.3",
    "react-native-linear-gradient": "2.6.2",
    "react-native-localize": "2.2.6",
    "react-native-navigation": "7.33.4",
    "react-native-permissions": "3.8.0",
    "react-native-prompt-android": "1.1.0",
    "react-native-reanimated": "3.1.0",
    "react-native-safe-area-context": "4.5.3",
    "react-native-simple-toast": "1.1.4",
    "react-native-svg": "13.6.0",
    "react-native-url-polyfill": "1.3.0",
    "react-native-vector-icons": "9.2.0",
    "tinycolor2": "1.6.0",
    "validate.js": "0.13.1"
  }
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `14.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `messaging`
- **Are you using `TypeScript`?**
  - `Yes v4.8.4`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by superyarik** [comment]
@garciaaentrust did you solve it?

**Comment by agestaun** [comment]
> @garciaaentrust did you solve it?

Still facing it, I just apllied a patch keeping the notifications history in memory to avoid displaying the incoming one twice if duplicated.
