### ISSUE TITLE
[🐛] Cannot use Firebase Authentication with Phone number - Missing Valid app identifier

### ISSUE THREAD

**Issue by ntrphongse** [invertase/react-native-firebase#7265]
## Issue

Hi there,
I recently implemented my Android app using React Native and this package React Native Firebase. I want to provide authentication via Firebase using Phone number. I follow the steps described at https://rnfirebase.io/auth/phone-auth. But after I trigger the function to send OTP code, Firebase returns to me this error:

![image](https://github.com/invertase/react-native-firebase/assets/57389575/5e6a8c04-385b-4c48-8c0e-abcc1f4aec6c)

No reCaptcha verification was prompted for me to solve. I ran this application on an Android simulator. What do I need to do to fix this?
Thank you so much!

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `18.3.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Auth`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
This is a project setup issue - there is good information available online (for instance https://stackoverflow.com/questions/64952016/firebase-phone-authentication-is-not-working-on-android-real-device) and carefully following the android firebase docs for phone authentication should help
