### ISSUE TITLE
Is react native firebase auth supported on react native TVOS ?

### ISSUE THREAD

**Issue by YoucefBen47** [invertase/react-native-firebase#7268]
After adding   use_frameworks! :linkage => :static and  $RNFirebaseAsStaticFramework = true we are getting duplicate commands produce on our tv os project as seen in the screenshot attached. Is react native firebase supported on react native tvos ? If yes how can we solve this issue ? 
We tried adding a pod for RNFBAuth and it resulted in an error saying that it is not supported on tvos !!
<img width="1407" alt="Screenshot 2023-07-28 at 5 27 57 AM" src="https://github.com/invertase/react-native-firebase/assets/70854871/93fc8ccc-5472-4639-9445-b9e26446a515">

**Comment by mikehardy** [comment]
I believe react-native-firebase was supported on tvOS last time I checked, but as you mention - not all modules are supported on all platforms.

You can check specific modules in the firebase-ios-sdk repository - https://firebase.google.com/docs/ios/learn-more#firebase_library_support_by_platform

It appears that auth is supported.

**Comment by mikehardy** [comment]
The rest of the issue template is missing and there are no reproduction details here so I'm going to close this as a question answered
