### ISSUE TITLE
Exception not being caught for FireStore

### ISSUE THREAD

**Issue by callagga** [invertase/react-native-firebase#727]
I was testing attempts to make an update when the security rules for FireStore to see how much error information is available in the return error, however I can not seem to successfully catch the error.  

That is the error does get printing out to the console BUT it seems it's from the underlying library and my code does get a chance to "catch" it itself.   Also the line "console.log('After Add');" is reached which shouldn't have been the case

Console Output (short):
```
About to Add
After Add
Possible Unhandled Promise Rejection (id: 0):
Error: Firestore: The caller does not have permission to execute the specified operation. (firestore/permission-denied).Code:
```
Code:
```
const mapDispatchToProps = dispatch => ({
  addAddButtonPress: (inputText) => {
    const item = { title: '123412341234' };
    try {
      console.log('About to Add');
      firebase.firestore().collection('todos').add(item);
      console.log('After Add');   // <== Reached
    } catch (error) {
      console.log('Error Received');  // <== NOT Reached
      console.log(pf(error));
    }
  },
});
```

Full Error:
```
About to Add
GcListContainer.js:27
After Add
GcListContainer.js:29
Possible Unhandled Promise Rejection (id: 0):
YellowBox.js:82
Error: Firestore: The caller does not have permission to execute the specified operation. (firestore/permission-denied).
Error: Firestore: The caller does not have permission to execute the specified operation. (firestore/permission-denied).
    at createErrorFromErrorData (/Users/Greg/Dropbox/source_reactnative/gcTodo/.vscode/.react/index.bundle:1822:15)
    at /Users/Greg/Dropbox/source_reactnative/gcTodo/.vscode/.react/index.bundle:1775:25
    at MessageQueue.__invokeCallback (/Users/Greg/Dropbox/source_reactnative/gcTodo/.vscode/.react/index.bundle:2133:16)
    at /Users/Greg/Dropbox/source_reactnative/gcTodo/.vscode/.react/index.bundle:1950:16
    at MessageQueue.__guard (/Users/Greg/Dropbox/source_reactnative/gcTodo/.vscode/.react/index.bundle:2068:9)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (/Users/Greg/Dropbox/source_reactnative/gcTodo/.vscode/.react/index.bundle:1949:12)
    at /Users/Greg/Dropbox/source_reactnative/gcTodo/.vscode/.react/debuggerWorker.js:126:58
    at process.<anonymous> (/Users/Greg/Dropbox/source_reactnative/gcTodo/.vscode/.react/debuggerWorker.js:35:9)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)

```

**Comment by Ehesp** [comment]
Try the following code. You can't catch a promise rejection inside a try catch block 

```js
const mapDispatchToProps = dispatch => ({
  addAddButtonPress: async (inputText) => {
    const item = { title: '123412341234' };
    try {
      console.log('About to Add');
      await firebase.firestore().collection('todos').add(item);
      console.log('After Add');   // <== Reached
    } catch (error) {
      console.log('Error Received');  // <== NOT Reached
      console.log(pf(error));
    }
  },
});
```

> You cannot use try-catch statements to handle exceptions thrown asynchronously, as the function has "returned" before any exception is thrown. You should instead use the promise.then and promise.catch methods, which represent the asynchronous equivalent of the try-catch statement [ref](https://stackoverflow.com/a/24977580)

**Comment by callagga** [comment]
@Ehesp - thanks very much for pointing this out.  I've actually started using redux-saga and had this problem too - I don't suppose you know offhand the way to "fix" with the saga approach (i.e. want to be able to catch this same exception, but ideally via a redux-saga approach?)

Code:

```
function createItem(item) {
  firebase.firestore().collection('todos').add(item);
}

export function* createItemSaga() {
  while (true) {
    const action = yield take(ActionTypes.AddListItem_UIRequest);
    const { item } = action;
    yield put({ type: ActionTypes.AddListItemRequested });
    try {
      yield fork(createItem, item);  // Fork used after I noted subsequent updates offline after the first were not going through locally
    } catch (e) {
      yield put({ type: ActionTypes.AddListItemRejected });
    }
  }
}
```

Issue is the same, can't seem to catch the firebase "add" (from createItem) exception that comes back within the try/catch (within createItemSaga).

**Comment by callagga** [comment]
this seems to work:


```
export function* createItemSaga() {
  while (true) {
    const action = yield take(ActionTypes.AddListItem_UIRequest);
    const { item } = action;
    yield put({ type: ActionTypes.AddListItemRequested });
    try {
      const ref = firebase.firestore().collection('todos');
      yield call([ref, ref.add], item);
      yield put({ type: ActionTypes.AddListItemFulfilled });
    } catch (e) {
      console.log('createItemSaga: error caught. Error='); 
      console.log(pf(e));
      yield put({ type: ActionTypes.AddListItemRejected });
    }
  }
}
```

**Comment by Afsarunnisa** [comment]
I'm also facing the same issue, here is the code

async addTodo() {
   
    const item = { title: '123412341234' };
    try {
      console.log('About to Add');
      await firebase.firestore().collection('todos').add(item);
      console.log('After Add');   // <== Reached
    } catch (error) {
      console.log('Error Received');  // <== NOT Reached
      console.log(pf(error));
    }



Possible Unhandled Promise Rejection (id: 0):
ReferenceError: pf is not defined
ReferenceError: pf is not defined
    at Todos.addTodo$ (http://10.9.9.61.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:108336:23)
    at tryCatch (http://10.9.9.61.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:11331:40)
    at Generator.invoke [as _invoke] (http://10.9.9.61.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:11490:22)
    at Generator.prototype.(anonymous function) [as throw] (http://10.9.9.61.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:11367:21)
    at tryCatch (http://10.9.9.61.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:11331:40)
    at invoke (http://10.9.9.61.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:11396:20)
    at http://10.9.9.61.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:11406:13
    at tryCallOne (http://10.9.9.61.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:10685:12)
    at http://10.9.9.61.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:10771:15
    at http://10.9.9.61.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:12047:19

**Comment by Ehesp** [comment]
@Afsarunnisa thats seems an issue with your code somewhere, whatever "pf" is?

I've never used redux-saga personally, it just makes things overly complicated especially when you're trying to use another state store like Firebase.

**Comment by callagga** [comment]
Oh the pf was just for debugging:

import pf from 'pretty-format'
