### ISSUE TITLE
[🐛] ANDORID - DynamicLinks().onLink(this.handleDynamicLink()); - Not returning any response in prod environment 

### ISSUE THREAD

**Issue by avishek-dev** [invertase/react-native-firebase#7276]
### Issue:
**DynamicLinks().onLink(this.handleDynamicLink())  not returning any response in prod environment, but in debug APK the response is coming alright.** 

**The response object is:** ` {"minimumAppVersion": null, "url": "https://letssin.app/invite", "utmParameters": {"utm_campaign": "Invite For Checklist & qrcode", "utm_medium": "dynamic_link", "utm_source": "firebase"}`

*Package:*
```
@react-native-firebase/dynamic-links": "^16.5.0"
@react-native-firebase/app": "^14.3.2"
"react-native": "0.66.4"
```
**Reproduction code snippet:**
`this.unsubscribeListeningToDeepLinks = dynamicLinks().onLink(this.handleDynamicLink());
      dynamicLinks()
        .getInitialLink()
        .then(url => {
          dynamic_link_data(firebaseData);
          if (url) {
            saveUTMSource(url);
            this.deapLink(url);
          }
        })`

**Comment by killian2k** [comment]
I am having the same with this code snippet:
`void dynamicLinks()
      .getInitialLink()
      .then(link => {
        safeLogEvent('dyn_link_will_be_handled', {});
        if (link?.url === undefined || handledInvitationIds.has(link.url)) {
          if (link?.url !== undefined) {
            safeLogEvent('Link_already_handled', {url: link.url});
          }
          return;
        }
        handleDynamicLink(link);
      });`
the event 'dyn_link_will_be_handled' is getting called many times but the url is null in prod on Android as well.
I tried to update the firebase packages to 18.3.0 and I am using react native v '0.71.7'

**Comment by avishek-dev** [comment]
Hey @killian2k thanks for sharing your case. I just wanted to know that are you using the Firebase Dynamic link in your project.

**Comment by nakapon9517** [comment]
I'm experiencing the same phenomenon.
@react-native-firebase/dynamic-links: 18.3.0
