### ISSUE TITLE
🔥 Type Issue in Messaging  - Not a bug just a type fix

### ISSUE THREAD

**Issue by ccorneliusHsv** [invertase/react-native-firebase#7279]
## Issue

Describe your issue here
Discovered a type issue through trial and error. Specifically FirebaseMessagingTypes.RemoteMessage.data has a type of { [key: string]: string }. When I accessed data I got back the following: 

  "data": {
    "link": "https://example.com",
    "fcm_options": {
      "image": "https://example.png"
    }

fcm_options returns an object not a string. My suggestion is to change the type on data to { [key: string]: string | object }.

This is just a type fix, so I'm not sure it's relevant to include the information below. If you do think it's relevant I would be glad to add more 
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 17.5.0
- **`Firebase` module(s) you're using that has the issue:**
  - Messaging
- **Are you using `TypeScript`?**
  - YES 4.8.4

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Sorry for the delay! What you propose as a type change does make sense, if you raised a PR for the same we could merge+release. Thanks!
