### ISSUE TITLE
firestore callbacks to onSnapshot note coming through when device back on line

### ISSUE THREAD

**Issue by callagga** [invertase/react-native-firebase#728]
I note that when subscribed in firestore via onSnapshot one does not get a callback (to fire the listener allocated in onSnapshot) for the cases:

a) when a device comes back on line, when updates were made whilst offline [note the firestore backend does seem to get the updates, but nothing bubbles up to the code to indicate this]

b) in general after an update (e.g. add) - so you get the initial callback locally but the document is marked as "hasPendingUpdates".  One doesn't get a subsequent callback to confirm the backend actually has been updated with the document data indicating hasPendingUpdates=false.

Not sure to what extent this is related to the "includeMetadataChanges" issue at https://github.com/invertase/react-native-firebase/issues/719.

**Comment by Salakar** [comment]
@callagga are you still facing this issue, which platform, what versions etc? Please fill out the issue template if you are still facing this issue - we're not mind readers =]

**Comment by callagga** [comment]
actually perhaps close this one and reference:  https://github.com/invertase/react-native-firebase/issues/719#issuecomment-357191318

**Comment by chrisbianca** [comment]
Closing in favour of #719

**Comment by NULL-SWEAT** [comment]
I was having this same issue on android when using `4.0.7`, upgrading to `4.1.0` and `firebase-firestore 15.0.0`(the release note says 16 but that doesn't work, check [this link](https://github.com/invertase/react-native-firebase-starter/issues/30) ) got it working, persists to db as soon as device goes online.

**Comment by kkusanagi** [comment]
<img width="272" alt="screen shot 2018-05-18 at 6 37 24 pm" src="https://user-images.githubusercontent.com/1698343/40230573-928da012-5aca-11e8-89fb-7783a14bcf90.png">

Any help for this? this is from v4.2.0. Any stable version advise?
