### ISSUE TITLE
[🐛] DynamicLinks.API is not available on this device.

### ISSUE THREAD

**Issue by vladimir-vasilev** [invertase/react-native-firebase#7287]
This error from Crashlytics report

Non-fatal Exception: io.invertase.firebase.crashlytics.UnhandledPromiseRejection
[dynamicLinks/initial-link-error] 17: API: DynamicLinks.API is not available on this device. Connection failed with: b{statusCode=SERVICE_INVALID, resolution=null, message=null}

It reproduces on many android devices (mostly Huawei, android v. 6, 10 ,12)

env:
"react": "18.2.0",
"react-native": "0.72.2",
"@react-native-firebase/dynamic-links": "16.5.0",

**Comment by mikehardy** [comment]
Huawei does not support many google services. Dynamic links is one of them - https://firebase.google.com/docs/android/android-play-services

**Comment by ziga-hvalec** [comment]
How can we check if dynamic links are supported?

**Comment by mikehardy** [comment]
Hey @ziga-hvalec - two things:

1- dynamic links are barely supported anywhere, you are aware they are deprecated and going away quite soon? August I believe - you may look at docs upstream to see
2- a good indicator is if google play services is installed or not. That is the discriminating information between lots of firebase services working or not. There is a Utils static off the react-native-firebase core/app module that you may interrogate for this information https://rnfirebase.io/app/utils#android---checking-play-services

**Comment by ziga-hvalec** [comment]
Thanks for a quick reply. 
I know. But we are still  using them for a little while. We'll remove then soon.
Might try that playServicesAvailability just to avoid sentry errors. 
Thanks
