### ISSUE TITLE
React Native Firebase Phone Number auth/invalid-app-credential invalid

### ISSUE THREAD

**Issue by younisabuzayed** [invertase/react-native-firebase#7289]
I have a problem with the Phone number Auth is not working on Real devices just on IOS. The error response is [auth/invalid-app-credential] invalid token.
The Android app is working 
IOS Simulator is working 
IOS real device is not working I do everything to make it work but I can't.

System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 431.19 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2023.05.22.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/opt/ruby/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 22, 24, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-29 | Intel x86 Atom, android-29 | Intel x86_64 Atom, android-30 | Intel x86_64 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs ATD ARM 64 v8a, android-33 | Google APIs Intel x86_64 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by nanokoko89** [comment]
same

**Comment by younisabuzayed** [comment]
I found the problem the APNs certificate is expired

**Comment by hassanharoon321** [comment]
Please give any solution
