### ISSUE TITLE
[🐛] phone auth Session ID key didn't get

### ISSUE THREAD

**Issue by KuldipReactNative** [invertase/react-native-firebase#7304]
I am trying to send OTP to a phone, but the Application crashes. please provide solution

**Library version:

```json
@react-native-firebase/analytics": "18.0.0",
    "@react-native-firebase/app": "18.0.0",
    "@react-native-firebase/auth": "18.0.0",
    "@react-native-firebase/messaging": "18.0.0",
    react-native: "0.61.3"`
```

path of code: 

`node_modules/@react-native-firebase/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java`

Code:

```java
private void promiseRejectAuthException(Promise promise, Exception exception) {
    WritableMap error = getJSError(exception);
    final String sessionId = error.getString("sessionId");
    final MultiFactorResolver multiFactorResolver = mCachedResolvers.get(sessionId);
    WritableMap resolverAsMap = Arguments.createMap();
    if (multiFactorResolver != null) {
      resolverAsMap = resolverToMap(sessionId, multiFactorResolver);
    }
    rejectPromiseWithCodeAndMessage(
        promise, error.getString("code"), error.getString("message"), resolverAsMap);
  }
```

--------------------------------------------------------------------------------------------------------------------------------

Error logs:- 

```
com.facebook.react.bridge.NoSuchKeyException: sessionId
    at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:122)
    at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:126)
    at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:161)
    at io.invertase.firebase.auth.ReactNativeFirebaseAuthModule.promiseRejectAuthException(ReactNativeFirebaseAuthModule.java:1932)
    at io.invertase.firebase.auth.ReactNativeFirebaseAuthModule.access$000(ReactNativeFirebaseAuthModule.java:87)
    at io.invertase.firebase.auth.ReactNativeFirebaseAuthModule$1.onVerificationFailed(ReactNativeFirebaseAuthModule.java:945)
    at com.google.android.gms.internal.firebase-auth-api.zzacb.onVerificationFailed(com.google.firebase:firebase-auth@@22.1.0:2)
    at com.google.android.gms.internal.firebase-auth-api.zzabk.zza(com.google.firebase:firebase-auth@@22.1.0:2)
    at com.google.android.gms.internal.firebase-auth-api.zzabl.run(com.google.firebase:firebase-auth@@22.1.0:3)
    at android.os.Handler.handleCallback(Handler.java:942)
```
--------------------------------------------------------------------------------------------------------------------------------

```
System:
    OS: macOS 13.4.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 102.21 MB / 20.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.14.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.7.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/mypc/.rvm/rubies/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.4 is now available (your project is running on v0.61.3)
```

**Comment by mikehardy** [comment]
Can you please forma the stack trace so it is readable? It is unreadable on my phone. I suggest wrapping it in triple backticks in the markdown

**Comment by KuldipReactNative** [comment]
> Can you please forma the stack trace so it is readable? It is unreadable on my phone. I suggest wrapping it in triple backticks in the markdown

Hello @mikehardy ,
Please check

**Comment by mikehardy** [comment]
Thank you! That stack trace does seem to point right into the library and I think this is an area with some recent work. That leaves us with a high probability that you've discovered a real issue in the library, thanks for posting this

I'll look into it

**Comment by mikehardy** [comment]
Just looked into this -

I have reformatted your description so it is readable

This is a difficult scenario to test in our automated tests, but I can see how this would happen

Referring back to react-native 0.61 (you really should upgrade!!) I see where a `hasKey` == false will throw the exception that crashes the app:

https://github.com/facebook/react-native/blob/86cad7d69099baaaeae10ac7c0912a023101f257/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeMap.java#L118-L123

This behavior changed with react-native 0.63, so if you upgraded you would never see a crash like this as that will just return null now:

https://github.com/facebook/react-native/blob/86cad7d69099baaaeae10ac7c0912a023101f257/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeMap.java#L118-L123

...and it explains why it wasn't seen in development or by anyone else - since most have upgraded now

I can alter the code in the area to be more compatible with the ancient react-native though, by calling `hasKey` prior to asking for the value, and using a null value if there is no key by the name `sessionId`, which is what newer react-native versions would return.

The defensive method looks like this, you can alter it locally if you like and use patch-package to make it persistent until I get a PR in and release it. Hopefully will have a release with the fix in today or tomorrow tho

```java

  private void promiseRejectAuthException(Promise promise, Exception exception) {
    WritableMap error = getJSError(exception);
    String sessionId = null;
    if (error.hasKey("sessionId")) {
      final String sessionId = error.getString("sessionId");
    }
    final MultiFactorResolver multiFactorResolver = mCachedResolvers.get(sessionId);
    WritableMap resolverAsMap = Arguments.createMap();
    if (multiFactorResolver != null) {
      resolverAsMap = resolverToMap(sessionId, multiFactorResolver);
    }
    rejectPromiseWithCodeAndMessage(
        promise, error.getString("code"), error.getString("message"), resolverAsMap);
  }
```

**Comment by mikehardy** [comment]
Patch set from PR here if that's useful: https://github.com/invertase/react-native-firebase/actions/runs/5955250636?pr=7310

**Comment by mikehardy** [comment]
Here's the patch set from the PR if that's useful: https://github.com/invertase/react-native-firebase/actions/runs/5955548239?pr=7310

(fixed one tiny issue in PR - deleted previous comment to old patch set, replaced with this one)

**Comment by KuldipReactNative** [comment]
> Here's the patch set from the PR if that's useful: https://github.com/invertase/react-native-firebase/actions/runs/5955548239?pr=7310
> 
> (fixed one tiny issue in PR - deleted previous comment to old patch set, replaced with this one)

@mikehardy  Thank you so much
