### ISSUE TITLE
Or query operators are limited to 10 comparisons by SDK 

### ISSUE THREAD

**Issue by varem611** [invertase/react-native-firebase#7312]
## Issue
As per the documentation
Cloud Firestore provides support for logical OR queries through the or, in, and array-contains-any operators. These queries are limited to [30 disjunctions based on the query's disjunctive normal form](https://firebase.google.com/docs/firestore/query-data/queries#limits_on_or_queries).

As such I believe the client side validation on the “Filter” function and “in” operator need to be tweaked from their max of 10 comparisons to 30 disjunctions based on the query's disjunctive normal form or remove the client side validation for this all together.

https://firebase.google.com/docs/firestore/query-data/queries#query_limitations

 

Describe your issue here

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Seems reasonable, a PR to do the same would likely be merged+released.
When you make the change locally (recommended to do so via patch-package) does it work for you up to 30?

**Comment by mikehardy** [comment]
Did you pursue this @varem611 ? What did you find when you altered it to 30 locally and tested it?
