### ISSUE TITLE
How to get params from createDynamicLink for navigate

### ISSUE THREAD

**Issue by pisangGoreng** [invertase/react-native-firebase#732]
at first, im generate link from createDynamicLink method
```
    firebase.links()
    .createDynamicLink({
      dynamicLinkDomain: "https://nk897.app.goo.gl",
      link: "kucing/jacky",
      androidInfo: {
        androidPackageName: "com.yumboxapp"
      },
      iosInfo: {
        iosBundleId: "com.example.ios"
      }
    })
    .then((url) => {
      console.tron.log(url)
    });
```

whem im, try the result link from createDynamicLink, my device open my apps.
But how to get params from dynamic link?

im try this, but no result
```
    // Check if the app was opened from a link
    firebase.links().getInitialURL()
      .then(url => console.tron.log(url))
      .catch(err => console.tron.log('An error occurred getting the initial page'))
```

and 
```
    firebase.links()
    .getInitialLink()
    .then((url) => {
        console.tron.log(url)
    });
```

any idea to solve this?

Thanks

**Comment by omer88** [comment]
Hi @pisangGoreng ,
Could you please supply more details about the environment?
Is that the link you try to supply?
In addition, if it's android, what launchMode do you use?

**Comment by pisangGoreng** [comment]
Hi @omer88 

i try generate dynamic 
```
firebase.links()
    .createDynamicLink({
      dynamicLinkDomain: "https://example.app.goo.gl",
      link: "name/age",
      androidInfo: {
        androidPackageName: "com.example"
      },
      iosInfo: {
        iosBundleId: "com.example.ios"
      }
    })
    .then((url) => {
      console.tron.log(url)
    });
```

from then result, i try to open from terminal
``
adb shell 'am start -W -a android.intent.action.VIEW -d "https://https*******.app.goo.gl?apn=com.******&ibi=com.example.ios&link=kucing%2Fjacky" com.*****'
``

after that, my apps will open.
Because i need parameter from that dynamic link, im try with firebase.links().getInitialLink().

but i cant get the result. When first time app open, result from getInitialLink is null & when im try to running adb shell to test dynamic link, the getInitialLink not execute again.

maybe my method is wrong, any idea how to my App can take params from dynamic url ?

thanks

**Comment by omer88** [comment]
I think that you should use a full link (e.g http://yourdomain/kucing/Fjacky) rather just kucing/Fjacky.
How did you configure the intent-filter at the manifest file to open such link?

**Comment by pisangGoreng** [comment]
hi @omer88 i think, im hav missunderstanding.. before, im think if we want take parameter from dynamic link, we use method from firebase too. 

right now, im use Linking from react native & can take parameter from dynamic link firebase.
this my reference: https://github.com/invertase/react-native-firebase/issues/304

in manifest, im use link from firebase console
```
<!-- CONFIG FOR DEEP LINKING ANDROID -->
        <intent-filter>
            <action android:name="android.intent.action.VIEW"/>
            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <data android:host="http://example.app.goo.gl" android:scheme="http"/>
            <data android:host="https://example.app.goo.gl" android:scheme="https"/>
        </intent-filter>
```

Thanks

**Comment by omer88** [comment]
Can you please try to change the host to your own domain?
For example, if your domain is example.com, try to configure:
`            <data android:host="example.com" android:scheme="http"/>
            <data android:host="example.com" android:scheme="https"/>`
The dynamic link is parsed so the app should have a filter for this link.
see: https://firebase.google.com/docs/dynamic-links/android/receive

**Comment by afilp** [comment]
@omer88 The instructions here at the end show that we should enter google's link:

`` android:host="your.dynamic.links.domain.example.com``

https://rnfirebase.io/docs/v3.2.x/links/android

**Comment by omer88** [comment]
Hi @afilp ,
What should actually be there is *your* domain (the one you have specified at link field on createDynamicLink / createShortDynamicLink)
The instructions are not so clear regarding this.

**Comment by afilp** [comment]
@omer88 Thanks! This was indeed confusing on the instructions.

**Comment by afilp** [comment]
@omer88 It is also confusing what to put for ``CUSTOM_URL_SCHEME`` on iOS. There is different wording on the Android compared to iOS, so if we want to use the same url for both it is kind of confusing.

In Android it mentions this:  ``your.dynamic.links.domain.example.com``
In iOS it mentions this: ``URL scheme field to either your **bundle identifier** or a unique value.``

So, if I want to use this dynamic link:   
``dl1 = 'https://cp342.app.goo.gl/?link=http://mobilelink.ourwebsite.com/app/123&apn=com.ourcompany.ourapp&amv=32&ibi=com.ourcompany.ourapp&isi=1156392612&imv=32';``

What do I put there?   ``mobilelink.ourwebsite.com`` in both cases?

**Comment by omer88** [comment]
Hi @afilp ,
Did you mean `iosCustomScheme` ?
If so, it's an optional parameter which you have to provide in case of custom URL scheme, was defined to be something other than your app's bundle ID.
see: https://firebase.google.com/docs/reference/dynamic-links/link-shortener

**Comment by chrisbianca** [comment]
Closing this as the conversation has gone stale. Please re-open if there are still issues.

**Comment by Johncy1997** [comment]
I am facing issue on getting link parameters.

1. Created dynamic link using:
```
const link = new firebase.links.DynamicLink('https://taxijo.com?param1=' + this.props.user.referral_code + '&param2=' + this.props.user.type, 'taxijo.page.link')
            .android.setPackageName('com.taxijo')
            .ios.setBundleId('org.reactjs.native.example.TaxiJo').ios.setAppStoreId(APP_STORE_ID);
        firebase.links()
            .createDynamicLink(link)
            .then((url) => {
                if (url) {
                    console.log("dynamicLink=" + url);
                    this.setState({ dynamicLink: url })
                }

            });
```

2. I am trying to get the parameters from _componentDidMount_ of _App.js_ file.

```
firebase
      .links()
      .getInitialLink()
      .then(url => {
        if (url) {
          // app opened from a url
    //       var link = "https://preview.page.link/taxijo.page.link?link=https://taxijo.com?param1%3DH9ZTUIPS%26param2%3DOWNER&apn=com.taxijo&isi=1445430478&ibi=org.reactjs.native.example.TaxiJo";
    // console.log("My Decoded url",decodeURIComponent(link));
    // var chromeLinkFormat = "https://taxijo.com?param1=H9ZTUIPS&param2=OWNER";
    // console.log("My Decoded chromeLinkFormat",decodeURIComponent(chromeLinkFormat));

          let params,paramType;
          if(url.startsWith("https://preview")){
            var decodedURL = decodeURIComponent(url);
            var link = decodedURL.substring(decodedURL.indexOf("=")+1,decodedURL.lastIndexOf("&apn"));
            params = link.substring(
              link.indexOf("=") + 1,
              link.lastIndexOf("&")
            );
            paramType = link.split("param2=")[1];
          }else{
            params = url.substring(
              url.indexOf("=") + 1,
              url.lastIndexOf("&")
            );
            paramType = url.split("param2=")[1];
          }
          setItem("registerData", { register: { refferal_code: params, refferal_type: paramType } });
          console.log("Referral code=" + params);
          console.log("Referral type=" + paramType);
        } else {
          // app NOT opened from a url
        }
      });
```

Everything works fine on Android as expected.But in IOS, while opening the link from Chrome its opening the app and exactly i am getting the url as **https://taxijo.com?param1=H9ZTUIPS&param2=OWNER** then i can get the parameters from the link. 
The exact issue is i am getting **https://preview.page.link/taxijo.page.link?link=https://taxijo.com?param1%3DH9ZTUIPS%26param2%3DOWNER&apn=com.taxijo&isi=<appstoreid>&ibi=<iosbundleid>** this format when its opened from**Safari**.

**Comment by mikehardy** [comment]
@Johncy1997  there may be something there, but please open a new issue following the template so we have the information needed to help. Also for something touchy between browsers you might want to hunt through the internet very carefully, as it's the first thing we'd do anyway. Finally, I believe apply may register links differently, but I'm not an expert in the area - just make sure you've definitely registered the custom link correctly via apple and in your app etc.

**Comment by Johncy1997** [comment]
@mikehardy Thanks for your quick reply. I spent 2days in the same issue(searched a lot through internet). Not able to find an exact cause or solution. I am under pressure to close this.Thats why i asked here.
