### ISSUE TITLE
[🐛] Error resolving module in @react-native-firebase/messaging module

### ISSUE THREAD

**Issue by bshubham80** [invertase/react-native-firebase#7320]
**Description:**
I encountered an error while using the @react-native-firebase/messaging module in my project. The error message suggests that a module cannot be resolved, and I'm seeking assistance in resolving this issue. Please refer to the screenshot for more details.

**Environment:**
React Native version: 0.71.12
@react-native-firebase/messaging version: 18.3.1
Operating system: macOS Ventura 13.0.1

**Possible Solution:**
I have made some changes in the import statement from  `import { firebase } from '..';` to `import { firebase } from '../lib/';` and started working fine. But not sure why is it needed.

<img width="1541" alt="image" src="https://github.com/invertase/react-native-firebase/assets/24887663/9fafe61f-de54-4dc6-b498-3c32c4ca62fd">

**Comment by katiahr** [comment]
Hi, I have the same error in version 20.4.0. Was there any solution?

**Comment by bshubham80** [comment]
@katiahr, Can you please try 

**Possible Solution:**
I have made some changes in the import statement from import { firebase } from '..'; to import { firebase } from '../lib/'; and started working fine. But not sure why is it needed.
