### ISSUE TITLE
FirebaseInAppMessaging V9 (and other packages) modular APIs not exercised in CI?

### ISSUE THREAD

**Issue by mikehardy** [invertase/react-native-firebase#7328]
FirebaseInAppMessaging V9 modular APIs not exercised in CI

Not sure exactly why coverage is showing up as not hitting these APIs when the tests seem to cover them
Don't want to block the PR though so this is a separate issue

_Originally posted by @mikehardy in https://github.com/invertase/react-native-firebase/issues/7306#issuecomment-1705734524_

**Comment by exaby73** [comment]
Not stale
