### ISSUE TITLE
Device is getting blocked for life when user attempts multiple times and unable to block in both Debug and Release versions

### ISSUE THREAD

**Issue by gani419** [invertase/react-native-firebase#7331]
**Using firebase in react native for both release and debug versions.**

When the user tries to hit otp call many times getting app not authorized error.
Since that device is blocked for otp call for lifetime.
Unable to revoke the block issue.
Can use with test phone numbers, But cant do for release apk.
I'm getting the following error from firebase.
auth/app-not-authorized

AppCheck is registered for app verification.

**Comment by chinmay4github1987** [comment]
Even the same happening to me as well . Please give solutions for above bug as already many users are live in google playstore.
Unable to make recpatha invisible.

**Comment by mikehardy** [comment]
Solving this is not within the capability of this repo. I believe your issue may be restated as:

"OTPs have costs in terms of server and real-life cellular carrier resources, all of which are guarded zealously by anti-abuse policies at multiple layers on the server side. When a device behaves in a way that looks like abuse via multiple requests, it is denied further use of OTP resources".

The general solutions are I believe "don't behave in ways that appear abusive", "have backups for OTP auth flows as OTP flows must always be considered 'lossy' and require backups", and/or "pursue with google support if necessary". I'm not aware of any other strategies that can affect the experience, but I know that app behavior that appears OTP-abusive will be blocked, likely without  support recourse
