### ISSUE TITLE
:fire: Android App Check Play Integrity ctsProfileMatch

### ISSUE THREAD

**Issue by JupitersLB** [invertase/react-native-firebase#7333]
## Issue

Hey thanks for any help in advance.

We have implemented and have AppCheck working on both production and staging which is great. However, some devices fail the integrity test. We used [this app](https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck&hl=en&gl=US) to confirm the reason why on the device(s) in question and it seems to fail the `ctsProfileMatch`.

The "solution" to this according to docs is around this [`MEETS_BASIC_INTEGRITY `](https://developer.android.com/google/play/integrity/setup#configure-api) which requires further setup within the play console. Unfortunately, even though we can confirm app check is integrated, it appears that the play console hasn't or does not recognize this and we can't figure out why this is the case.

<img width="1478" alt="Screenshot 2023-09-06 at 17 49 46" src="https://github.com/invertase/react-native-firebase/assets/46614913/f7803a2c-dec6-4f84-a7c4-4d1b835f9e70">

Is this something that is expected? Is there any way we can manage this `MEETS_BASIC_INTEGRITY` with the current implementation?

---

## Project Files

N/A

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Sorry this went stale - I have seen other API integration areas where the server side console parts were (for various reasons...) unaware that the integration was completed and actually working (crashlytics and analytics come to mind). That's not directly related, but is context - I think it will pay to pursue this in firebase-android-sdk (and possibly try a minimum reproduction with their quickstart - though they do not seem to publish one for app-check 🤔  https://github.com/firebase/quickstart-android - so may require some setup) so they don't simply bounce the issue as "we don't do react-native")

I can say that on a scan of the firebaes appcheck docs and their repo I do not see any issues or related information concerning the string MEETS_BASIC_INTEGRITY nor do I see any related code (https://github.com/search?q=repo%3Afirebase%2Ffirebase-android-sdk%20MEETS_BASIC_INTEGRITY&type=code)

In this related code it appears the PlayIntegrity provider simply exchange the play integrity response for an AppCheck token (with whatever extra API responses you may have configured to get "MEETS_BASIC_INTEGRITY" as a possible inclusion in the response...)  https://github.com/firebase/firebase-android-sdk/blob/470153683091c7ec59dc29916193863182e16a43/appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/internal/PlayIntegrityAppCheckProvider.java#L24

That's a network call (to exchange the tokens) so I *assume* (maybe wrong) that the ability to handle and perhaps allow AppCheck tokens for lower integrity devices is something that needs support on the Firebase server side. I do not see any indication that is possible now.

I believe that is the sort of thing that would need coordination between a few teams at Firebase and would need to be pursued initially in the firebase-android-sdk repo

I do not believe we'll be able to do much here though - even if firebase-android-sdk implements support for lower integrity devices on the server side, it will likely be in the form of allowing that as a firebase console configuration, then AppCheck tokens will simply start showing up for the lower integrity devices
