### ISSUE TITLE
I am trying to use Filter.or in react native firebase but it gives an error 'or' undifined

### ISSUE THREAD

**Issue by gorkemunluyurt** [invertase/react-native-firebase#7346]
I import the firestore library as in the documentation.

`import firestore, {Filter} from '@react-native-firebase/firestore';`
It already works properly in everything else, but when I want to use Filter.or, it gives an error that 'or' is not defined.

Example use:

```
const bigCities = await citiesRef
.where(
Filter.or(
Filter.where('capital', '==', true),
Filter.where('population', '\>=', 1000000)
)
)
.get();
```

**Comment by mahesh-agrawal-313** [comment]
same here

**Comment by alikrodrigues** [comment]
same here to and property  

`"@react-native-firebase/firestore": "^18.5.0",`

```
 firestore()
      .collection('eventProduct')
      .where(
        Filter.and(
          Filter(
            'eventId',
            '==',
            firestore().doc(`Events/${eventId}`),
            Filter('type', '==', itemType),
            Filter('available', '==', true),
          ),
        ),
      )
      .get()
```

![image](https://github.com/invertase/react-native-firebase/assets/29580644/7434e0bd-fc92-4635-837e-cc3d0c014de4)

**Comment by oskar117** [comment]
I'm expecting the same problem, but with Filter.and. Workaround above worked

**Comment by mikehardy** [comment]
With apologies - there is not a complete + executable reproduction here, it would be more useful to have a full example .js so I could try this. Note that our e2e test app exercises these APIs, so I'm a bit 🤔 

Example: https://github.com/invertase/react-native-firebase/blob/2d8ac144a14e79ce1846ecab077f8d7b69d11f05/packages/firestore/e2e/Query/where.and.filter.e2e.js#L42-L66

**Comment by wasupalonely** [comment]
I have the same problem, was anyone able to solve it?

**Comment by ZakirBangash** [comment]
has running with same issue, using latest firebase 18.8 react native 71.14

**Comment by antoine-waag** [comment]
@gorkemunluyurt do not import `Filter` from `@react-native-firebase/firestore`

You can simply do :
```
import firestore from '@react-native-firebase/firestore';

const bigCities = await citiesRef
    .where(
        firestore.Filter.or(
            firestore.Filter.where('capital', '==', true),
            firestore.Filter.where('population', '\>=', 1000000)
        )
    )
    .get();
```

**Comment by Felipe-OT** [comment]
> @gorkemunluyurt do not import `Filter` from `@react-native-firebase/firestore`
> 
> You can simply do :
> 
> ```
> import firestore from '@react-native-firebase/firestore';
> 
> const bigCities = await citiesRef
>     .where(
>         firestore.Filter.or(
>             firestore.Filter.where('capital', '==', true),
>             firestore.Filter.where('population', '\>=', 1000000)
>         )
>     )
>     .get();
> ```

I get the error: _firestore.default.Filter.where is not a function (it is undefined).
Property 'where' does not exist on type 'FilterFunction'.
