### ISSUE TITLE
Is ReactNativeFirebaseMessagingHeadlessTask unnecessary for current messaging version?

### ISSUE THREAD

**Issue by pavelustenko** [invertase/react-native-firebase#7348]
### Discussed in https://github.com/invertase/react-native-firebase/discussions/7347

<div type='discussions-op-text'>

<sup>Originally posted by **pavelustenko** September 12, 2023</sup>
I'm updating my project to the latest versions of the libraries and I'm discouraged that neither the documentation nor the changelog mentions the need to register a headless task to receive remote messages. Apparently, now when receiving a remote message, the application is launched entirely in invisible mode, which leads to unforeseen consequences, since it contradicts the logic of the code of my project (Android). Is it possible to monitor that the application is running in invisible mode, or the ability to work with your own headless task, as was the case in previous versions?</div>

**Comment by JanzenJohn** [comment]
Did you find another solution?
