### ISSUE TITLE
[🐛] documentation not updated to function logEvent of analitycs 

### ISSUE THREAD

**Issue by mateusfranco** [invertase/react-native-firebase#7351]
## Issue

The documentation of RN firebase analitycs is wrong
if you try to dispatch a customEvent like the example in this link [RN analitycs custom events](https://rnfirebase.io/analytics/usage#custom-events) you will receive a error 21 in debug view of firebase analitycs 

this happen because the doc show a false example 

```
<Button
        title="Add To Basket"
        onPress={async () =>
          await analytics().logEvent('basket', {
            id: 3745092,
            item: 'mens grey t-shirt',
            description: ['round neck', 'long sleeved'], ---- will occur the problem because of this
            size: 'L',
          })
        }
      />
```

in example it show is possible to use array of primitives but, searching in other places i discovered  that you only can pass string or number to this funcion.

[sameproblem](https://github.com/firebase/flutterfire/issues/8861)
[explanation of the resolution](https://github.com/firebase/flutterfire/pull/9520/files)

**Comment by mpadel78** [comment]
@mateusfranco having same issue here.

**Comment by mikehardy** [comment]
Hi there 👋 - if you look on the top right of every documentation page you will see "Edit Page" and that will take you to the github web UI that should walk you through the easy process of proposing a text edit to the page, where you can suggest any improvements that would clarify things. If you do so, with supporting links (as you've posted here) that support the technical details of your proposed changes, we can get your PR merged and help future users
