### ISSUE TITLE
🔥 Missing support for initiateOnDeviceConversionMeasurementWithPhoneNumber

### ISSUE THREAD

**Issue by htcgh** [invertase/react-native-firebase#7355]
## Issue

React Native Firebase is missing support for the Analytics (iOS-only) API `initiateOnDeviceConversionMeasurementWithPhoneNumber` ([reference](https://firebase.google.com/docs/reference/ios/firebaseanalytics/api/reference/Classes/FIRAnalytics#+initiateondeviceconversionmeasurementwithphonenumber:)), which was added in [Firebase iOS SDK 10.13.0](https://firebase.google.com/support/release-notes/ios#version_10130_-_august_1_2023).

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Versioning note: this could be considered a breaking change to add, as firebase-ios-sdk 10.10.0 was the minimum firebase-ios-sdk last required in a breaking change (https://github.com/invertase/react-native-firebase/blob/main/CHANGELOG.md#1810-2023-06-22)

On the other hand, the ability to override the firebase-ios-sdk version explicitly comes with a warning that it may cause problems, and you have to manage versions yourself so I'm leaning towards considering requirement of new minimum firebase-ios-sdk version to be a non-breaking change so we are free to add support for new APIs without friction (though with a good changelog comment from commit message...)

I feel this warning, present in the documentation about overrides, supports the stance that simply using new symbols is non-breaking change:

> Using your own SDK versions is generally not recommended as it can lead to breaking changes in your application. Proceed with caution.

So, that settled (for me at least, though open to opinion...) this should be pretty trivial to add
