### ISSUE TITLE
[🐛] [firebase_storage] getDownloadURL() returning inconsistent URLs in Android/web vs iOS

### ISSUE THREAD

**Issue by Jeffreyoboe1** [invertase/react-native-firebase#7363]
When calling getDownloadURL() on a storage reference, the returned URL format is different depending on Android/web or iOS platform. The iOS platform returns a URL with the port number, i.e. 443 appended to domain, and Android and web omit the port.

ios: [https://firebasestorage.googleapis.com:443/v0/b/](https://firebasestorage.googleapis.com/v0/b/)...'
vs
android or web: https://firebasestorage.googleapis.com/v0/b/...'

Steps to reproduce
call getDownloadURL() on a storage reference object for both Android and iOS and compare results.

The inconsistency creates inconsistent data when storing URLs in DB, and causes issues when whitelisting url paths, i.e. applying rules to firebase db field values to ensure field being set is for a specific url base path.  Or when trying to compare download urls set in firestore database on iOS vs  what firebase functions will return when calling .getDownloadUrl() on a storage file.  

Additional Context: 

This bug was noted in flutter repository and resolved.  See: 

Issue: https://github.com/firebase/flutterfire/issues/7036

and

PR: https://github.com/firebase/flutterfire/pull/7097

**Comment by mikehardy** [comment]
Fascinating! Thanks so much for linking the related items from flutterfire, that's a huge help

Looks like the solution is to stop the port if it exists

```objective-c

      NSString *url = URL.absoluteString;

      if ([url rangeOfString:@":443"].location != NSNotFound) {
        NSRange replaceRange = [url rangeOfString:@":443"];
        url = [url stringByReplacingCharactersInRange:replaceRange withString:@""];
      }
```

**Comment by mikehardy** [comment]
If you look on the patch-package CI job's summary tab here you should see a patch-package set generate which contains the fix, I'll merge it and release it but that will get you going in the meantime. Thanks again for reporting this

https://github.com/invertase/react-native-firebase/actions/runs/6277542009?pr=7367

**Comment by mikehardy** [comment]
Finished the merge work for the week and will do a release shortly as well, so if you just want to wait for 18.5.0 it will have this fix in it

**Comment by Jeffreyoboe1** [comment]
Great, thanks Mike!
