### ISSUE TITLE
[🔥🐛] Realtime Database Connection Fails Randomly on iOS with App Check Enforced

### ISSUE THREAD

**Issue by mrsasuu** [invertase/react-native-firebase#7364]
## Issue

I've recently added App Check to my Firebase project to protect various services, including the SMS authentication service and the Realtime Database. After enforcing App Check, the requests seemed to work as expected.

However, I've noticed that on iOS, the Realtime Database connection fails randomly when users start the app after a period with the app in the background or even if the app was killed. This issue is intermittent and doesn't happen every time, but it's frequent enough to cause concern. 

Additionally, I'm uncertain about the exact error returned by the Realtime Database during these failures, as I haven't been able to capture it.

I installed App Check following the steps listed in the [official documentation](https://rnfirebase.io/app-check/usage). I set up deviceCheck, app attest, Play integrity, and reCAPTCHA enterprise for web.

In my root JS file (where I initialize my app), I added the following function:

```javascript
export const firebaseAppCheckInitialize = async () => {
  const isDebug = getEnvironment() === 'debug'
  const debugTokens = getDebugToken()
  try {
    const rnfbProvider = firebase
      .appCheck()
      .newReactNativeFirebaseAppCheckProvider()
    rnfbProvider.configure({
      android: {
        provider: isDebug ? 'debug' : 'playIntegrity',
        debugToken: debugTokens.android,
      },
      apple: {
        provider: isDebug ? 'debug' : 'appAttestWithDeviceCheckFallback',
        debugToken: debugTokens.ios,
      },
    })

    await firebase.appCheck().initializeAppCheck({
      provider: rnfbProvider,
      isTokenAutoRefreshEnabled: true,
    })

    const { token } = await firebase.appCheck().getToken(true)
    if (token.length > 0) {
      console.log('AppCheck verification passed')
    }
  } catch (error) {
    // This should never happen
    console.error('AppCheck initialization or verification error', error)
    Sentry.captureException(error, {
      extra: {
        platform: Platform.OS,
      },
    })
  }
}
```

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "@react-native-firebase/analytics": "18.4.0",
  "@react-native-firebase/app": "18.4.0",
  "@react-native-firebase/app-check": "18.4.0",
  "@react-native-firebase/auth": "18.4.0",
  "@react-native-firebase/crashlytics": "18.4.0",
  "@react-native-firebase/database": "18.4.0",
  "@react-native-firebase/messaging": "18.4.0",
  "@react-native-firebase/perf": "18.4.0",
  "@react-native-firebase/remote-config": "18.4.0",
  "@react-native-firebase/storage": "18.4.0"
}

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
...
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

  [RNFBAppCheckModule sharedInstance];

  // Firebase
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
...
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 333.94 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/user/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.13 => 0.70.13 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

- **Platform that you're experiencing the issue on**:
  - [x] iOS, not found in Android yet.
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `18.4.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Analytics, App, App Check, Auth, Crashlytics, Database, Messaging, Perf, Remote Config, Storage`
- **Are you using `TypeScript`?**
  - `Y` & `5.2.2`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hmm - that is concerning, not to punt this to another repo however have you looked into firebase-ios-sdk repo at all to see if they have related issues? This sounds like it will be a low level issue, perhaps with persistent connection handling / network drops on sleep / connection re-establishment and maybe a race condition between appcheck and database

Do you have any associated logging indicating anything at all? Or any local reproductions? Without reproducing this one it is going to be very, very difficult to troubleshoot

**Comment by Slapbox** [comment]
You could also try forcing websockets instead of long-polling. I've had nothing but trouble with long-polling but I forget how exactly to force websockets.

**Comment by mrsasuu** [comment]
I'm curious if the issue arises from a race condition, as the `firebaseAppCheckInitialize` might still be in progress while the app is loading. We've set up a watcher that connects to the realtime database during app startup. I'm uncertain about the behavior of the realtime database and other Firebase services if they encounter failures due to enforced App Check. Are you aware if the realtime database automatically attempts to reconnect if the connection fails for this reason?

> Hmm - that is concerning, not to punt this to another repo however have you looked into firebase-ios-sdk repo at all to see if they have related issues? This sounds like it will be a low level issue, perhaps with persistent connection handling / network drops on sleep / connection re-establishment and maybe a race condition between appcheck and database
> 
> Do you have any associated logging indicating anything at all? Or any local reproductions? Without reproducing this one it is going to be very, very difficult to troubleshoot

I am going to try to gather more data to have a better understanding.

> You could also try forcing websockets instead of long-polling. I've had nothing but trouble with long-polling but I forget how exactly to force websockets. Please do share if it helps!

I am going to try as well. 

Thx a lot =D

**Comment by Slapbox** [comment]
@mrsasuu please do report back! Also a note I should have mentioned - we're still using the JS SDK here and that workaround works for us. I don't know if it might not work as nicely with RN-Firebase for some reason, but I imagine it should.

**Comment by mbaker3** [comment]
I'm seeing similar behaviour except with Firestore's [`onSnapshot`](https://firebase.google.com/docs/firestore/query-data/listen). Periodically, on iOS when resuming the app from the background after some time (> 1 hour), the snapshot listeners will fail to respond to changes and I will see `unverified: invalid requests` in the Firebase console.

After a few minutes or a force quit the app functions as expected making verified requests.

Our app isn't live so the usage of our Firebase instances is very controlled at the moment. I can be certain the exact user/device that experienced this was the only one interacting with our instance when this occurred.

It really seems like something to do with requesting a new token for listening connections on app resume.

My initialization of App Check is similar to @mrsasuu except I have my app wait for the initialization to finish before allowing the loading of my app to progress.
``` js
// pseudo init
await appCheck().initializeAppCheck({
    provider: provider,
    isTokenAutoRefreshEnabled: true,
  });
 
await firstFirestoreCall();

showAppUI();
```

I haven't been able to pin down an exact error message yet but am still in the early stages of trying to get to the bottom of this.

One strange observation, once I disabled App Check enforcement my `Unverified: invalid requests` dropped to 0%. This is almost certainly is just a coincidence but is worth sharing in case someone else experiences the same and it helps track down the source of the issue.

Watching this thread. I'll share any more info I find.

**Comment by mbaker3** [comment]
Possibly relevant finds from the Firebase iOS repo:
 - https://github.com/firebase/firebase-ios-sdk/issues/11264
 - https://github.com/firebase/firebase-ios-sdk/issues/11579
    - Although the react-native-firebase docs seem to indicate that the custom provider logic is provided by the firebase-js-sdk. I hope Google's SDK is appropriately locking!

 - https://github.com/firebase/firebase-js-sdk/issues/6708
    - Seems very ReCAPTCHA related but maybe some of the back out/retry logic is in the core implementation and not provider specific?

There are a number of other issues related to App Check failing on apps installed via cloud recovery or new hardware transfer. That doesn't seem to be the situation we're encountering though.

**Comment by newbstudent** [comment]
We posted about our issues with AppCheck before and have basically given up on it, have never had it enabled for production because it goes from a small % of users impacted to 100% of users.  Just can't take the risk of users being unable to use our paid app, would immediately kill the app for sure if we enabled it.  Meanwhile we're just taking the risk that abuse could happen at any moment in terms of bills racking up for unauthorized use.

**Comment by mikehardy** [comment]
I'm not sure this is actionable in this repo, but I am watching

One quick note re this comment:

> Although the react-native-firebase docs seem to indicate that the custom provider logic is provided by the firebase-js-sdk. I hope Google's SDK is appropriately locking!

Our custom provider logic is nothing more than what I would call a "shim". My goals in implementing it were/are:

1- provide an API here that has the same "shape" as the firebase-js-sdk AppCheck API. Unfortunately the firebase-js-sdk / firebase-android-sdk / firebase-ios-sdk teams all implemented AppCheck with slightly different API shapes which makes this difficult and makes it hard to live up to our goal of being a drop-in replacement for firebase-js-sdk. The custom provider is my best attempt at "fixing" that by using the one API available on firebase-js-sdk where I can hide the differences, that is, a custom provider that you can then configure 

2- allow for dynamic provider loading, which is otherwise not supported on firebase-ios-sdk. Javascript (that is, react-native...) doesn't even have configuration available until the iOS native code is loaded and firebase-ios-sdk expects it's AppCheck system to be configured already, which is a mis-match for us. The custom provider allows us to swap providers at the native level, once we have javascript-level configuration available in the runtime.

Those are the only goals. I would say that the comment I quote is incorrect then, in the sense that the logic is not provided by firebase-js-sdk for our custom provider here, only the API shape. And as a shim our custom provider is doing nothing more than delegating to the native providers from the relevant SDKs (firebase-ios-sdk / firebase-android-sdk) so theoretically (warning!) if they handle locking correctly, we should as well, as the shim is effectively just a provider-swapper that then passes through to current provider

**Comment by kurtspirited** [comment]
@mbaker3 https://lnkr.fun/da2d7fe

**Comment by mikehardy** [comment]
@kurtspirited your comment is completely off topic, and poses a question but on some off-site space that has no guarantee of being available in the future for people. Questionable behavior, discouraged.. What you want is delivery reports though, I believe. https://firebase.google.com/docs/cloud-messaging/understand-delivery?platform=ios#message-delivery-reports
