### ISSUE TITLE
Analytics - Issue with User-Specific Data not Appearing in Google Analytics Console

### ISSUE THREAD

**Issue by InvescoTeam** [invertase/react-native-firebase#7373]
I've encountered an issue with Google Analytics in my React Native app, specifically related to user-specific data not appearing in the Google Analytics console. I have implemented **custom dimensions** to track specific data points, but I am facing difficulties with few particular user's data not showing up. Here are some details about the user's mobile device:

Operating System: Android
OS Version: Android 12 
Model Name: Samsung Galaxy M51

Code:
`const response = await analytics().logEvent(eventname, params);`

> "@react-native-firebase/analytics" :"14.11.1."
> "react-native": "0.66.0"

Could someone please assist in understanding the root cause of this problem and provide guidance on how to resolve it? Any insights or suggestions would be greatly appreciated.

**Comment by mpadel78** [comment]
Same issue here. My event count per user is too high and does not show the params at analytics.

**Comment by mpadel78** [comment]
Maybe this helps in your case. https://medium.com/lost-but-coding/setting-up-firebase-analytics-event-custom-parameters-dimensions-and-metrics-219cc3f3c356

**Comment by mikehardy** [comment]
Unfortunately, I do not believe this is actionable in any way in this repository.
I would pursue on stackoverflow or with upstream google analytics support.
This repository just provides react-native bindings without any logic as it passes through the method calls for the underlying firebase-android-sdk / firebase-ios-sdk implementations and they may have further information as well.
