### ISSUE TITLE
[🐛] 🔥 fetchSignInMethodsForEmail returning empty array

### ISSUE THREAD

**Issue by andrebeolchi** [invertase/react-native-firebase#7377]
## Issue

I work with several firebase projects, in a whitelabel **expo** app, as of September 22nd (maybe earlier), all the projects I created (with the exact same settings) the ***fetchSignInMethodsForEmail*** function always returns empty array. I tested using the endpoint "www....identitytoolkit.googleapis.com/v1/accounts:createAuthUri....." and it returns the list of login methods for that email correctly

## Steps to reproduce:
1. Create an account with email and password
2. Log out and use the fetch function.

```
import auth from "@react-native-firebase/auth";

const checkEmail = async () => {
  const { data, statusText } = await axios.post(
    "https://identitytoolkit.googleapis.com/v1/accounts:createAuthUri?key=[API_KEY]",
    {
      identifier: email,
      continueUri: "https://www.example.com.br"
    }
  );

  console.log("axios", data);
  //axios {"allProviders": ["password"], "kind": "identitytoolkit#CreateAuthUriResponse", "registered": true, "sessionId": "xxxx", "signinMethods": ["password"]}

  auth()
    .fetchSignInMethodsForEmail(email)
    .then((result) => {
      
      console.log("result", result); 
      //result []
      }
    });
};

```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/analytics": "^16.5.1",
    "@react-native-firebase/app": "^16.5.1",
    "@react-native-firebase/auth": "^16.5.1",
    "@react-native-firebase/database": "^16.5.1",
    "@react-native-firebase/firestore": "^16.5.1",
    "@react-native-firebase/messaging": "^16.5.1",
    "@react-native-firebase/storage": "^16.5.1",
    ...
    "expo": "~47.0.14",
    ...
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.8"
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 483.56 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 20.0.1 - /opt/homebrew/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.8 => 0.70.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [X] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `"@react-native-firebase/app": "^16.5.1",`
- **`Firebase` module(s) you're using that has the issue:**
  - `Authentication`
- **Are you using `TypeScript`?**
  - `Yes` & `"typescript": "^4.6.3"`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Is this reproducible in current versions?

> "@react-native-firebase/app": "^16.5.1",

This is quite old and I'm surprised it continues to function at all...

**Comment by Gouldy-C** [comment]
I am getting the same issue as the original issuer. I am running 18.7.3. 

```
const testFunc = async () => {
    if (user) {
      const methods = await auth().fetchSignInMethodsForEmail(user?.email!)
      console.log(methods)
      methods.forEach((method) => {
        console.log(method);
      });
    }
  }
```
The user email is an already authenticated email. This should be returning providers but it returns an empty array.

Using: 
"react-native": "0.72.6",
"expo": "~49.0.15",
"@react-native-firebase/app": "^18.7.3",
"@react-native-firebase/auth": "^18.7.3",


[package.json](https://github.com/invertase/react-native-firebase/files/13999448/package.json)


Would you like me you start a new issue or would you want to reopen this one?

**Comment by mikehardy** [comment]
email enumeration is disabled in new projects, that could be the problem, if this is still an issue for you

https://cloud.google.com/identity-platform/docs/admin/email-enumeration-protection

It is documented to return empty list when enabled
