### ISSUE TITLE
[🐛] ABSL_CONST_INIT iOS 17

### ISSUE THREAD

**Issue by mishkeTz** [invertase/react-native-firebase#7378]
## Issue

There's an issue when building the RN project for iOS 17.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "react-native": "0.63.4",
    "@react-native-firebase/analytics": "^14.11.0",
    "@react-native-firebase/app": "^14.11.0",
    "@react-native-firebase/auth": "^14.11.0",
    "@react-native-firebase/crashlytics": "^14.11.0",
    "@react-native-firebase/firestore": "^14.11.0",
    "@react-native-firebase/messaging": "^14.11.0",
    "@react-native-firebase/perf": "^14.11.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
  - RNFBApp (14.11.1):
    - Firebase/CoreOnly (= 8.15.0)
    - React-Core
  - RNFBAuth (14.11.1):
    - Firebase/Auth (= 8.15.0)
    - React-Core
    - RNFBApp
  - RNFBCrashlytics (14.11.1):
    - Firebase/Crashlytics (= 8.15.0)
    - React-Core
    - RNFBApp
  - RNFBFirestore (14.11.1):
    - Firebase/Firestore (= 8.15.0)
    - React-Core
    - RNFBApp
  - RNFBMessaging (14.11.1):
    - Firebase/Messaging (= 8.15.0)
    - React-Core
    - RNFBApp
  - RNFBPerf (14.11.1):
    - Firebase/Performance (= 8.15.0)
    - React-Core
    - RNFBApp
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `14.11.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Yes`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

<img width="1084" alt="Screenshot 2023-09-27 at 21 16 39" src="https://github.com/invertase/react-native-firebase/assets/15350199/63588557-3c95-443c-a319-0006fda805f7">
<img width="513" alt="Screenshot 2023-09-27 at 21 17 01" src="https://github.com/invertase/react-native-firebase/assets/15350199/247b5234-09f5-4ff7-a410-5951403adf42">

**Comment by aslamanver** [comment]
Facing issue

**Comment by alexkev** [comment]
Replace:
`ABSL_CONST_INIT extern "C" const int64_t kFIRFirestoreCacheSizeUnlimited =
    Settings::CacheSizeUnlimited;`
With
`extern "C" ABSL_CONST_INIT  const int64_t kFIRFirestoreCacheSizeUnlimited =
    Settings::CacheSizeUnlimited;`
