### ISSUE TITLE
[🐛] Receiving notifications has been delayed since sending

### ISSUE THREAD

**Issue by yedi97** [invertase/react-native-firebase#7382]
## Issue

My notification is delayed after pushing fcm for the case of quitting the app or the app is in the background. It seems like this delay error is happening on iOS 17, is anyone experiencing the same situation as me? and is there a solution to this problem?

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
target 'ImageNotification' do
  use_frameworks! :linkage => :static
  pod 'Firebase/Messaging', '~> 10.15.0' # eg 6.31.0
end
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ x] iOS
  - [ ] Android
  - [x ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`@react-native-firebase/app` version you're using that has this issue:**
  - `e.g. 18.5.0`
- **`@react-native-firebase/messaging` version you're using that has this issue:**
  - `e.g. 18.5.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `The device receives notifications with a delay`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by yenpn** [comment]
Does anyone else have the same problem as me?

**Comment by mikehardy** [comment]
I haven't heard it reported. For FCM issues it helps to publish the JSON that reproduces the issue when you send that JSON to the FCM REST APIs to trigger the FCM send to the device (just remove the device token as that's personal info of course)

If you are relying on data-only messages I can only reiterate here as I've mentioned in many related issue threads in this repo that data-only messages have zero guarantee of delivery and certainly no guarantee of timeliness.

If this is a notification (not data only...) and iOS17 is delaying it, then perhaps iOS 17 has implemented some new power-saving / wakeup-batching "feature" that preserves battery while making developers lives difficult as it will violate our (and our users') expectations of timely delivery in a new way. That would be a general issue though and likely have better results for you on stackoverflow (though I'd be interested in a cross-link here if you find anything...)
