### ISSUE TITLE
[🐛] Bug Report : [Expo][crashlytics] Error: undefined Unable to resolve module fs

### ISSUE THREAD

**Issue by mrkpatchaa** [invertase/react-native-firebase#7385]
## Issue

Hi Team, I am getting the following error on iOS when trying to use crashlytics. 
**Expo SDK 49**
```
The package at "../node_modules/source-map/lib/read-wasm.js" attempted to import the Node standard library module "fs".
It failed because the native React runtime does not include the Node standard library.
[Error: undefined Unable to resolve module fs from
node_modules/source-map/lib/read-wasm.js: fs could not be found within the project or in these directories:
../node_modules
```
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"expo": "~49.0.8",
"@react-native-firebase/crashlytics": "^18.5.0",
"react-native": "0.72.5",
```

#### `firebase.json` for react-native-firebase v6:

```json
{
    "react-native": {
        "crashlytics_debug_enabled": true,
        "crashlytics_javascript_exception_handler_chaining_enabled": true,
        "crashlytics_is_error_generation_on_js_crash_enabled": true,
        "crashlytics_ndk_enabled": true,
        "crashlytics_auto_collection_enabled": true
    }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
  OS: macOS 13.5.2
  CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  Memory: 2.39 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.16.0/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman:
    version: 2023.08.28.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `18.5.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `analytics`
  - `crashlytics`
- **Are you using `TypeScript`?**
  - `Y` & `5`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I do not see the `@react-native-firebase/app` module in your package.json snippet thus I do not believe this is a valid react-native-firebase integration

I suggest a very careful read of the install documentation and a second attempt to integrate react-native-firebase may clear things up, but this won't be actionable here
