### ISSUE TITLE
Notification shown as silent on Android (no popup)

### ISSUE THREAD

**Issue by slavko-lukic** [invertase/react-native-firebase#7393]
As title says, notification comes as silent always on android, works perfectly on iOS.
Did anybody have similar issue?

"react-native": "0.71.7",
"@react-native-firebase/app": "^18.5.0",
"@react-native-firebase/messaging": "^18.5.0",

**Comment by slavko-lukic** [comment]
I found out what is the problem.
So Firebase creates Miscellaneous channel for android app which has popups disabled by default.
Right now I cannot find a way to edit settings of that channel since `Creating and managing Channels is outside of the scope of the React Native Firebase library`.

Since Firebase creates this channel automatically, at least it should give possibility to edit the options for the channel in my opinion.

**Comment by mikehardy** [comment]
I believe you want a tighter notification integration + more control over notifications etc, which is a very difficult space to work in and resulted in a completely separate repository: notifee.app

We had to remove most of the notification stuff here as it is too burdensome to track given the velocity of change in the platform APIs vs the goals of react-native-firebase
