### ISSUE TITLE
App Check - iOS Debug Token not working with Expo Dev Client

### ISSUE THREAD

**Issue by apetta** [invertase/react-native-firebase#7396]
Getting the error:
```
AppCheck verification failed [Error: [appCheck/token-error] The operation couldn’t be completed. The attestation provider DeviceCheckProvider is not supported on current platform and OS version.]
```
Have completed the pre-requisite Apple/Firebase setup. Android is working well. Have set the debug token in firebase console and provided the debug token via the eas.json file, as well as via the `apple.debugToken` in `newReactNativeFirebaseAppCheckProvider`, but not working unfortunately.

Expo 49
RN 0.72.5
@react-native-firebase/app-check 18.5.0

**Comment by apetta** [comment]
Is the `ios/ProjectName/AppDelegate.mm` edit needed with expo dev-client? If so, how would we do that without ejecting?

**Comment by apetta** [comment]
Solved by [this issue](https://github.com/invertase/react-native-firebase/discussions/6184#discussioncomment-2562694)

A formal plugin or a note in the docs would be great!

**Comment by mikehardy** [comment]
Hi there! As an open source repo we depend on user contributions, especially for Expo which is community supported. All docs have an edit button at top right which walks you through an easy web-based PR flow for text edits, and plugins have been developed by the community for Expo - if there is one that would help, you could post a PR. Cheers
