### ISSUE TITLE
[🐛] Can't upgrade to latest @react-native-firebase 18.5.0

### ISSUE THREAD

**Issue by putuoka** [invertase/react-native-firebase#7402]
## Issue

I tried to upgrade the @react-native-firebase package from version 14.5.0 to the latest version 18.5.0 but it failed. Here are the steps I took to upgrade:

Initially, my package.json file looked like this. 

![image](https://github.com/invertase/react-native-firebase/assets/20880839/57215baf-414d-40bd-981c-64f250fd0dce)

Then I ran npm uninstall on @react-native-firebase/app, @react-native-firebase/messaging, and @react-native-firebase/perf to remove them. After they were uninstalled, I reinstalled the latest versions by running 

`npm install @react-native-firebase/app @react-native-firebase/messaging @react-native-firebase/perf`

The next step was to run ./gradlew clean to clean the Android build files. Then I ran yarn android to build the Android project. However, I received the following error:

```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-firebase_app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 48s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Note: D:\app\node_modules\@react-native-async-storage\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
> > Compilation failed; see the compiler error output for details.

🤔 but you have not included that compiler error output. So there is not enough information to work with here and provide any suggestions

>  OUTPUT GOES HERE

That is in the `react-native info` section of the template as well, meaning you have not provided enough information to provide any suggestions.

My only hunch is that you are on outdated versions of various toolchains (Java SDK perhaps? try 11+. Gradle? Make sure your react-native is up to date so you are on modern + supported versions of gradle)

I provide a reproducible demo here showing compilation with current versions works, so I'm not sure what we can do here, thus I will close this: https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
