### ISSUE TITLE
[🐛]  Could not find any version that matches com.google.firebase:firebase-session

### ISSUE THREAD

**Issue by ajiehatajie** [invertase/react-native-firebase#7406]
"@react-native-firebase/app": "^18.5.0",
    "@react-native-firebase/crashlytics": "^18.5.0",
    "@react-native-firebase/messaging": "^18.5.0",
    "@react-native-firebase/perf": "^18.5.0",
     "react-native": "0.71.14",
 

Could not determine the dependencies of task ':app:lintVitalReportDevRelease'.
> Could not resolve all task dependencies for configuration ':app:devReleaseRuntimeClasspath'.
   > Could not find any version that matches com.google.firebase:firebase-sessions:[15.0.0, 16.0.0).
     Versions that do not match:
       - 1.0.2
       - 1.0.1
       - 1.0.0
     Searched in the following locations:
       - https://zendesk.jfrog.io/artifactory/repo/com/google/firebase/firebase-sessions/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/com/google/firebase/firebase-sessions/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/google/firebase/firebase-sessions/maven-metadata.xml

**Comment by mikehardy** [comment]
No template, not only cannot reproduce but I reproduce successful builds, demonstration: https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

**Comment by bharamalhusen** [comment]
@mikehardy We have got the similar issue with version 18.9.0.


@ajiehatajie could you find any solution then please me on this.
My react-native version is 0.68.7

**Comment by mikehardy** [comment]
> 0.68.7

In general only 2 versions of react-native are supported in the react-native ecosystem. 0.74 is out, which implies that 0.72.0 is the oldest version that will work.

I suspect that if you update react-native and all the toolchains associated (gradle, android gradle plugin) it will work

Note that there is no reproduction here so "metoo" comments are not useful.

I have posted a reproduction that works, on the other hand: https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
