### ISSUE TITLE
[📚] Not clear which name to mention for Firebase configurations

### ISSUE THREAD

**Issue by ashutosh887** [invertase/react-native-firebase#7407]
## Documentation Feedback

The description here is not clear:

```
On the Firebase console, add a new Android application and enter your projects details. 
The "Android package name" must match your local projects package name which can 
be found inside of the manifest tag within the /android/app/src/main/AndroidManifest.xml 
file within your project.
```
I can't understand which name to use for the firebase project

My `AndroidManifest.xml` looks like this and I'm not sure which key to configure it with.

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
    </application>
</manifest>
```

The docs. I'm referring to can be found here:

https://github.com/invertase/react-native-firebase/blob/2d8ac144a14e79ce1846ecab077f8d7b69d11f05/docs/index.md?plain=1#L47

**Comment by exaby73** [comment]
Hello @ashutosh887. The documentation clear specifies the Android package name. The package name is the reverse domain you can find in your `app/buuld.gradle` or your `Android.Manifest.xml`. For example, it may look like `com.example.myReactNativeApp`.

Looking at your manifest file, could you tell me how you have set up your app? Are you using the React Native CLI, or Expo to  scaffold your app?

**Comment by ashutosh887** [comment]
It's a React Native CLI Project @exaby73 

Now I'm stuck here:

Not able to understand how to add this 
```
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services' // <- Add this line
```

in this file:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("com.google.gms:google-services:4.3.15")
    }
}
```

There are a lot of things I believe that needs to be fixed @exaby73 I believe!

**Comment by mikehardy** [comment]
@ashutosh887 this is an open source projects, and we welcome + happily merge PRs

> There are a lot of things I believe that needs to be fixed @exaby73 I believe!

Every documentation page has an "Edit Page" link at the top right, and proposing improvements to the docs is an easy process using the Github Web UI that the edit page link takes you too.

@exaby73 The way you specific an android application package just recently changed in gradle from being in AndroidManifest.xml to being in build.gradle, so this likely requires a documentation update as that's a new thing

@ashutosh887 for your current problem, I believe you are looking in the top-level file `android/build.gradle` not the module-level `android/app/build.gradle` (note that *app*). Here's the line from the react-native template, seems to match our docs just fine at the moment in this case? https://github.com/facebook/react-native/blob/c47bef6ae0767937cad4a75254be088118fc3dd1/packages/react-native/template/android/app/build.gradle#L2

**Comment by mikehardy** [comment]
@ashutosh887 I was updating quite a few android-gradle-plugin v8+ related items today and picked off the necessary update to the docs in a commit https://github.com/invertase/react-native-firebase/pull/7412/commits/c42f76622329d0cb83c75b731c9c72486586c173 on PR #7412 so that one shouldn't catch any future people unaware
