### ISSUE TITLE
[🐛] Cannot log custom parameters inside custom events

### ISSUE THREAD

**Issue by sumapietrogrm** [invertase/react-native-firebase#7415]
### **Cannot log custom parameter inside a custom events**

I have this code:

```js
await analytics().logEvent('event_name_custom', {objectToLog})

objectToLog= {
    "item_id": "string",
    "item_brand": "string",
    "item_name": "string",
    "item_category": "string",
    "item_category2": "string",
    "item_category3": "string",
    "item_category4":"string",
    "item_category5": "string",
    "item_list_id": "string",
    "item_list_name": "string",
    "price": 0.99,
    "quantity": 2,
    "description": "string",
    "choice": "string"
}
```

my custom definition inside ga4 dashboard:
![image](https://github.com/invertase/react-native-firebase/assets/127997258/4f45c37f-5271-437e-93e2-cbca4d6c3ddd)
![image](https://github.com/invertase/react-native-firebase/assets/127997258/9ae72021-37f3-40a2-8174-2c918b64bc26)

but, in my report i can check the count_events of "event_name_custom" but all custom definition are populated as "(not set)"

**Comment by Maja-Codetribe** [comment]
Hello, my team has encountered the same issue. Is there any solution for this issue?
Also to note, in the debug view, all the data is being logged as expected. Only in production we se all the values as (not set).

**Comment by sumapietrogrm** [comment]
> Hello, my team has encountered the same issue. Is there any solution for this issue? Also to note, in the debug view, all the data is being logged as expected. Only in production we se all the values as (not set).

Hello Maja, it was an easy (and lazy) problem in my case, i innested an object inside an object

Wrong version:
```js
await analytics().logEvent('event_name_custom', {objectToLog})

objectToLog= {
    "item_id": "string",
    "item_brand": "string",
    "item_name": "string",
    "item_category": "string",
    "item_category2": "string",
    "item_category3": "string",
    "item_category4":"string",
    "item_category5": "string",
    "item_list_id": "string",
    "item_list_name": "string",
    "price": 0.99,
    "quantity": 2,
    "description": "string",
    "choice": "string"
}
```

Correct version:
```js
await analytics().logEvent('event_name_custom', objectToLog)

objectToLog= {
    "item_id": "string",
    "item_brand": "string",
    "item_name": "string",
    "item_category": "string",
    "item_category2": "string",
    "item_category3": "string",
    "item_category4":"string",
    "item_category5": "string",
    "item_list_id": "string",
    "item_list_name": "string",
    "price": 0.99,
    "quantity": 2,
    "description": "string",
    "choice": "string"
}
```

**Comment by Maja-Codetribe** [comment]
Hello,
Many thanks for the quick reply! Really appreciate you helping us pinpoint the earlier issue.
However, our application's problem remains, since we are sending an object as payload to logEvent function, with all the values being strings. 
<img width="522" alt="image" src="https://github.com/invertase/react-native-firebase/assets/141336686/5fb6ee12-5179-47d2-a4a6-13c8876e2d28">
Thank you again for finding time to reply. 
Best regards!

**Comment by sumapietrogrm** [comment]
> Hello, Many thanks for the quick reply! Really appreciate you helping us pinpoint the earlier issue. However, our application's problem remains, since we are sending an object as payload to logEvent function, with all the values being strings. <img alt="image" width="522" src="https://private-user-images.githubusercontent.com/141336686/321643005-5fb6ee12-5179-47d2-a4a6-13c8876e2d28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDI0NzksIm5iZiI6MTcxMjg0MjE3OSwicGF0aCI6Ii8xNDEzMzY2ODYvMzIxNjQzMDA1LTVmYjZlZTEyLTUxNzktNDdkMi1hNGE2LTEzYzg4NzZlMmQyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxMzI5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjE3YzM5N2FkZGRhMDljZTkxMmI4NjIyNDMzNjIwODk1YzY1MDU0ZDBiOGU3ODBjNDhkZTk3MTlmMjAzMDEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K4p8C5zs8mEAEoITvVhFq01-4vMGVZmSwi0Es2Ir_us"> Thank you again for finding time to reply. Best regards!

Can you give us more code? when and how you assign a valorization to the parameters?
If you console log those variable are they correctly populated when you click on the banner?

**Comment by Maja-Codetribe** [comment]
Hi,
> Can you give us more code? when and how you assign a valorization to the parameters? If you console log those variable are they correctly populated when you click on the banner?
We have checked the logs and even in the debug view - all the values are being set and populated as expected. Only in production we see those values as (not set).
>
The logic in the code is pretty straight forward, when the event occurs, we just pass the above mentioned values as payload for custom Analytics event. All the values are accessible, because they are required elsewhere earlier (we have double checked for undefined values).
Thank you for taking interest in this issue :)
