### ISSUE TITLE
SafetyNet 17.0.0 critical issue releasing to Google Play Store

### ISSUE THREAD

**Issue by Jeffreyoboe1** [invertase/react-native-firebase#7417]
When releaseing android app to playstore, I see this warning about : 

<img width="721" alt="Screen Shot 2023-10-23 at 12 42 11 PM" src="https://github.com/invertase/react-native-firebase/assets/30086374/5703c107-0556-4f38-9a3c-eeeff005d89c">

Also, please see this issue in Android sdk: 

https://github.com/firebase/firebase-android-sdk/issues/3890

Looks like they have a version out that handles the issue with safetynet.

**Comment by mikehardy** [comment]
Interesting thanks for pointing this out. I have firebase-android-sdk 32.4.0 integrated and ready for release but the release itself failed for unrelated reasons. You may try a temporary local sdk override of the sdk version for Android to see if it resolves it for you while waiting on release

**Comment by mikehardy** [comment]
There is no action to take here - the SafetyNet API is still used as a fallback for those that have not yet converted to the PlayIntegrity API.

The PlayIntegrity API is fully supported in firebase-android-sdk and in react-native-firebase in current versions though - so there is no further action to take in the repo and if you are already using the PlayIntegrity API there is no further action for you to take.

The warning will continue to show up until the SafetyNet API fallback has finished it's deprecation cycle in the underlying firebase-android-sdk but will not affect your releases, per https://github.com/firebase/firebase-android-sdk/issues/3890#issuecomment-1488368740
