### ISSUE TITLE
Use new method to determine if app is in foreground

### ISSUE THREAD

**Issue by estampscvt** [invertase/react-native-firebase#7418]
Per android developer guide this function should only be used for debugging and apps in the past have been rejected from the google play store when included.

https://github.com/invertase/react-native-firebase/blob/63f1893849578bfab85241bf4458eb845a4d857f/packages/app/android/src/reactnative/java/io/invertase/firebase/common/SharedUtils.java#L127

**Comment by mikehardy** [comment]
I just finished reading up all the available android developer docs.
The warning you cite has been in place forever yet the implementation does continue to function and I'm not aware of a competing implementation that could take over so I am going to close this as I do not think it is feasible.

However! I could of course be wrong. I still would be happy to accept a PR that swaps the current implementation for one of the modern lifecycle style APIs but it would need to handle the constraints of being implemented in a non-Application extending / non-Activity-owning react-native context, and would need to implement ignore of a list of activities + work across multiple app processes as I think that's current behavior

**Comment by estampscvt** [comment]
Hey @mikehardy I saw this fix in another library that is trying to determine if the app is in foreground as well. Would this type of fix be possible?  https://github.com/invertase/notifee/blob/f78a56518b1fe0dab060e96c2a1f145e41b7363a/packages/react-native/android/src/main/java/io/invertase/notifee/NotifeeReactUtils.java#L201

**Comment by estampscvt** [comment]
@mikehardy Just wanted to circle back and see what you think of that suggestion/if it would work here

**Comment by mikehardy** [comment]
Very interesting - I'm involved in that repo as well but haven't been active there for a while. Generally the stuff in there does work though...I may have misunderstood something about how ProcessLifecycleOwner worked, and whether we can use it effectively. It appears it is possible, I'll investigate but - with apologies - it won't be super high priority. In that sense if this is something you are interested in I'd be more than happy to take any reasonable PR
