### ISSUE TITLE
[🐛] task.cancel() never ends

### ISSUE THREAD

**Issue by Idelya** [invertase/react-native-firebase#7425]
## Issue

I am trying to implement the cancellation of the file transfer when the cancel button is pressed. According to the documentation, task.cancel() should return Promise - but Promise never completes.

I run the task in useEffect:
```javascript
  const task = storage().ref(filepath).putFile(uri);
    uploadTaskRef.current = task;
    task.catch(error => console.error(error));
    await task;
```

Where `uploadTaskRef.current` is a reference from `useRef`.

User run cancel method with this code:

```javascript
          <Pressable
            onPress={() =>
              uploadTaskRef.current
                ?.cancel()
                .then(() => console.log('success'))
                .catch(err => console.log('error'))
                .finally(() => console.log('finally'))
            }
          >
            <Text>Cancel</Text>
         </Pressable>
```

'Success', 'error' as well as 'finally' will not be logged in the console, instead the `task.catch` will return an error:

`[Error: [storage/unknown] An unknown error has occurred.]`
### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/app": "^18.6.0",
    "@react-native-firebase/auth": "^18.6.0",
    "@react-native-firebase/firestore": "^18.6.0",
    "@react-native-firebase/storage": "^18.6.0",
    "firebase": "^10.5.2"
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `5.6.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Storage`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! If it never ends, how does it end up in the catch block? It sounds like it ends, but it ends with an error. Do I understand that correctly?

`storage/unknown-error` may have more information in the device logs. What do you see in the device console output when you launch the app from Xcode? There will likely be more information about the underlying error / status from firebase-ios-sdk in the device log before the error makes it to the react-native-firebase code and is transformed to an unknown-error as it bubbles up to the javascript code.

**Comment by Idelya** [comment]
> Hi there! If it never ends, how does it end up in the catch block? It sounds like it ends, but it ends with an error. Do I understand that correctly?
> 
> `storage/unknown-error` may have more information in the device logs. What do you see in the device console output when you launch the app from Xcode? There will likely be more information about the underlying error / status from firebase-ios-sdk in the device log before the error makes it to the react-native-firebase code and is transformed to an unknown-error as it bubbles up to the javascript code.

The error is catched by this
```javascript
    task.catch(error => console.error(error));
```

And this never ends:
```javascript
    uploadTaskRef.current
                ?.cancel()
                .then(() => console.log('success'))
                .catch(err => console.log('error'))
```
