### ISSUE TITLE
App crashes for ios

### ISSUE THREAD

**Issue by akataa916** [invertase/react-native-firebase#7426]
App crashes after initial ios setup.
As sooon as i add
`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  // Add me --- \/
  [FIRApp configure];
  // Add me --- /\
  // ...
}`

in AppDelegate.mm and run with npm run ios app crashes on simulator without any errors.

<img width="1512" alt="Screenshot 2023-10-28 at 5 09 10 PM" src="https://github.com/invertase/react-native-firebase/assets/149242561/fc2b1877-bd9f-4b15-9906-e8c0ecd59613">

**Comment by mikehardy** [comment]
Hi there! A correctly integrated app will not crash. You have ignored the template so there is not enough information to help, but I suspect you have not added the google services plist file to your application.

Please triple-check the installation information, and consult this script (it has descriptive comments! please read them!) to understand the minimal steps necessary for a successful integration https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
