### ISSUE TITLE
[🐛] AppCheck ain't working in release mode

### ISSUE THREAD

**Issue by realabbas** [invertase/react-native-firebase#7427]
## Issue

Describe your issue here

AppCheck ain't working in release mode, throwing the following error. Although working fine in debug mode using debug token

```
AppCheck verification failed [Error: [appCheck/token-error] com.google.android.play.core.integrity.IntegrityServiceException: -9: Integrity API error (-9): Binding to the service in the Play Store has failed. This can be due to having an old Play Store version installed on the device.
Ask the user to update Play Store.
(https://developer.android.com/reference/com/google/android/play/core/integrity/model/IntegrityErrorCode.html#CANNOT_BIND_TO_SERVICE).]

```
 ---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `16.7.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `App Check`
- **Are you using `TypeScript`?**
  - `Y`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! You have ignored the template, so there is not quite enough information to help

That said, this is a native SDK error, and appears pretty desriptive: 

> AppCheck verification failed [Error: [appCheck/token-error] com.google.android.play.core.integrity.IntegrityServiceException: -9: Integrity API error (-9): Binding to the service in the Play Store has failed. This can be due to having an old Play Store version installed on the device.
> Ask the user to update Play Store.
(https://developer.android.com/reference/com/google/android/play/core/integrity/model/IntegrityErrorCode.html#CANNOT_BIND_TO_SERVICE).]

You should do that. You can use the API here perhaps to detect whether the user has play services or not and then you can behave accordingly by either restricting access if they have no play services (e.g., Huawei devices...) or asking them to update if it is just out of date https://rnfirebase.io/app/utils#android---checking-play-services

Further advice may be obtained by searching + posting on stackoverflow with the correct firebase-related tags to attract support answers

This is not something we can affect here so I will close this as it is unactionable in this repo
