### ISSUE TITLE
[🐛] React Native iOS Xcode Compile Issue - clang error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by Sage-Rishi** [invertase/react-native-firebase#7430]
Hey guys,
I've been having an issue with my React Native firebase project as it fails to build at the very last step and simply shows 2 errors.

1. 771 duplicate symbols found
2. clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have a number of dependencies which caused a lot of issues while compiling for iOS although there were fixes by editing the Podfile of the application.

- **React Native Version: 0.72.4
- XCode Version: 15.0.1
- MacOS Sonoma 14.0
- Ruby Version: 3.1.4
- Cocoapods Version: 1.14.2**

Here's the output of my react-native doctor.

```
✓ Node.js - Required to execute JavaScript code
 ✓ yarn - Required to install NPM dependencies
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✖ Adb - No devices and/or emulators connected. Please create emulator with Android Studio or connect Android device.
 ✓ JDK - Required to compile Java code
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 33.0.0, 34.0.0
   - Version supported: Not Found
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ Ruby
 ✓ CocoaPods - Required for installing iOS dependencies
 ● ios-deploy - Required for installing your app on a physical device with the CLI
 ✖ .xcode.env - File to customize Xcode environment

Errors:   3
Warnings: 1

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.
```

Steps to reproduce:

1. Edit your Podfile and package.json with the files above.
2. Run yarn install or npm install
3. cd ios && **RCT_NEW_ARCH_ENABLED=0** pod install
4. **In XCode set Compile Sources As to Objective-C++**
5. Launch Xcode and build the app (or) run npx react-native run-ios

Here is my Podfile

```
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '14.0'
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  # use_frameworks! :linkage => linkage.to_sym
end

use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

target 'problembolo_mobile' do
  config = use_native_modules!
  
  # Flags change depending on the env values.
  flags = get_default_flags()
  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    # :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
    )
    
    target 'problembolo_mobileTests' do
      inherit! :complete
      # Pods for testing
    end

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = true
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
        config.build_settings['HEADER_SEARCH_PATHS'] << '"${PODS_ROOT}/../../node_modules/react-native/ReactCommon" '
      end
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      end
    end
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

And here is my package.json

```
{
  "name": "problembolo_mobile",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/blur": "^4.3.2",
    "@react-native-community/geolocation": "^3.1.0",
    "@react-native-firebase/app": "^18.3.2",
    "@react-native-firebase/auth": "^18.4.0",
    "@react-navigation/bottom-tabs": "6.5.8",
    "@react-navigation/native": "6.1.7",
    "@react-navigation/native-stack": "6.9.13",
    "@react-navigation/stack": "^6.3.17",
    "@reduxjs/toolkit": "^1.9.6",
    "axios": "1.5.1",
    "expo": "^49.0.13",
    "moment-timezone": "^0.5.43",
    "react": "18.2.0",
    "react-devtools": "^4.28.4",
    "react-native": "0.72.4",
    "react-native-charts-wrapper": "^0.6.0",
    "react-native-fast-image": "^8.6.3",
    "react-native-gesture-handler": "2.13.1",
    "react-native-image-picker": "^7.0.1",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-maps": "1.7.1",
    "react-native-mmkv": "^2.10.2",
    "react-native-paper": "5.10.4",
    "react-native-pressable-opacity": "^1.0.10",
    "react-native-reanimated": "^3.5.4",
    "react-native-safe-area-context": "3.4.1",
    "react-native-screens": "3.25.0",
    "react-native-shared-element": "^0.8.8",
    "react-native-static-safe-area-insets": "^2.2.0",
    "react-native-svg": "^13.14.0",
    "react-native-svg-transformer": "^1.1.0",
    "react-native-tab-view": "3.5.2",
    "react-native-vector-icons": "^10.0.0",
    "react-native-video": "^5.2.1",
    "react-native-vision-camera": "3.4.0",
    "react-native-worklets-core": "^0.2.1",
    "react-navigation-shared-element": "^3.1.3",
    "react-redux": "^8.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  }
}
```

The error log is attached here as well

[xcodeerrors.log](https://github.com/invertase/react-native-firebase/files/13231128/xcodeerrors.log)

Would really appreciate any help that resolves this issue, I've been at it for a couple of days and I haven't reached any resolution yet.

**Comment by mikehardy** [comment]
Hey there - you might try react-native 0.72.6 (out for just a bit) and react-native-firebase 18.6.1 (just released)
I know there have been lots of little fixes for Xcode 15, and I think those may help

Also be very careful to keep your react-native-firebase versions aligned --> version philosophy: https://invertase.io/blog/react-native-firebase-versioning

If that fails, you may try a demo build that creates a correctly integrated + correctly compiling react-native-firebase integration from scratch with nothing but a shell script - you may look at the resulting project to see what things *should* look like: https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

**Comment by Sage-Rishi** [comment]
Hey @mikehardy I tried using the script to initialise a fresh react native project with firebase integration but it didn't work. Although a manual addition to a fresh project worked by default. I seemed to have recognised the issue is being caused by a plugin react-antive-vision-camera and that it doesn't compile with static linkages with use_framework!.

Is there any temporary workaround this and also is changing the "Compile Source FIles" to Objective-C++ in XCode Build Settings the right thing to do. I have no idea on how to resolve this as I've primarily worked with Flutter before.

Output when I keep the Compile Source Files option as default:
<img width="719" alt="Screenshot 2023-11-02 at 11 04 26 PM" src="https://github.com/invertase/react-native-firebase/assets/31234123/1d861b65-9935-4644-b0cb-0fe2ebdb58d6">

**Comment by mikehardy** [comment]
> I tried using the script to initialise a fresh react native project with firebase integration but it didn't work

Interesting - works for me every time, that's the whole point of the script - I use it to validate that things work. Curious why it did not, by which I mean specific error messages etc

With regard to react-native-vision-camera that is obviously out of our control, it's a separate repository.

firebase-ios-sdk strictly requires `use_frameworks!`, and react-native requires `:linkage => :static` *if* you use `use_frameworks!`, thus we strictly require `use_frameworks! :linkage => :static`

There is no workaround for this requirement that we support.

**Comment by mikehardy** [comment]
for what it's worth react-native-camera works, I use that one, never tried react-native-vision-camera

**Comment by rocket13011** [comment]
Good evening, I have the same problem.

No problem when installing app but problem when installing firestore.

here is package.json

`"dependencies": {
    "@react-native-firebase/app": "18.6.1",
    "@react-native-firebase/firestore": "^18.6.1",
    "@react-navigation/native": "6.1.9",
    "@react-navigation/native-stack": "6.9.17",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-asset": "2.1.1",
    "react-native-linear-gradient": "3.0.0-alpha.1",
    "react-native-mmkv": "2.10.2",
    "react-native-permissions": "3.10.1",
    "react-native-reanimated": "3.5.4",
    "react-native-safe-area-context": "4.7.4",
    "react-native-screens": "3.27.0",
    "react-native-svg": "13.14.0",
    "zustand": "4.4.6"
  },`

here is podfile

`linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

  #use_frameworks! :linkage => :static
  #FIREBASE
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseFirestoreInternal', :modular_headers => true
  $RNFirebaseAsStaticFramework = true`

with use_frameworks! :linkage => :static I immediately have a problem with flipper

and the error in xcode :

<img width="262" alt="Capture d’écran 2023-11-06 à 23 45 59" src="https://github.com/invertase/react-native-firebase/assets/1051575/fe3350a0-50ca-4843-b123-8accec37fbf4">


Thanks a vous.

**Comment by Sage-Rishi** [comment]
@mikehardy the specific error logs when I runt he script is this: 
```

Running on ARM





**********************************



You must set XCODE_DEVELOPMENT_TEAM environment variable to your team id to test macCatalystTry running it like: XCODE_DEVELOPMENT_TEAM=2W4T2B656C ./make-demo.sh (but with your id)Skipping macCatalyst test




**********************************



Testing react-native 0.72.6 + react-native-firebase 18.5.0 + firebase-ios-sdk 10.15.0 + firebase-android-sdk 32.3.1
                                                          
               ######                ######               
             ###     ####        ####     ###             
            ##          ###    ###          ##            
            ##             ####             ##            
            ##             ####             ##            
            ##           ##    ##           ##            
            ##         ###      ###         ##            
             ##  ########################  ##             
          ######    ###            ###    ######          
      ###     ##    ##              ##    ##     ###      
   ###         ## ###      ####      ### ##         ###   
  ##           ####      ########      ####           ##  
 ##             ###     ##########     ###             ## 
  ##           ####      ########      ####           ##  
   ###         ## ###      ####      ### ##         ###   
      ###     ##    ##              ##    ##     ###      
          ######    ###            ###    ######          
             ##  ########################  ##             
            ##         ###      ###         ##            
            ##           ##    ##           ##            
            ##             ####             ##            
            ##             ####             ##            
            ##          ###    ###          ##            
             ###     ####        ####     ###             
               ######                ######               
                                                          

                  Welcome to React Native!                
                 Learn once, write anywhere               


  
  Run instructions for Android:
    • Have an Android emulator running (quickest way to get started), or a device connected.
    • cd "/Users/bitsage/PersonalProjects/rnfbdemo" && npx react-native run-android
  
  Run instructions for iOS:
    • cd "/Users/bitsage/PersonalProjects/rnfbdemo" && npx react-native run-ios
    - or -
    • Open rnfbdemo/ios/rnfbdemo.xcodeproj in Xcode or run "xed -b ios"
    • Hit the Run button
    
  Run instructions for macOS:
    • See https://aka.ms/ReactNativeGuideMacOS for the latest up-to-date instructions.
    
  
yarn install v1.22.19
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
Done in 17.17s.
Scanning for pods...
1.14.2
> pod install
[31m
[!] Invalid `Podfile` file: unexpected token at 'Config Validation Error: "project.ios.automaticPodsInstallation" is not allowed

    at readConfigFromDisk (/Users/bitsage/PersonalProjects/rnfbdemo/node_modules/@react-native-community/cli-config/build/readConfigFromDisk.js:52:11)

    at loadConfig (/Users/bitsage/PersonalProjects/rnfbdemo/node_modules/@react-native-community/cli-config/build/loadConfig.js:65:65)

    at setupAndRun (/Users/bitsage/PersonalProjects/rnfbdemo/node_modules/@react-native-community/cli/build/index.js:159:39)

    at run (/Users/bitsage/PersonalProjects/rnfbdemo/node_modules/@react-native-community/cli/build/index.js:129:11)

    at Object.<anonymous> (/Users/bitsage/PersonalProjects/rnfbdemo/node_modules/@react-native-community/cli/build/bin.js:31:3)

    at Module._compile (node:internal/modules/cjs/loader:1120:14)

    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)

    at Module.load (node:internal/modules/cjs/loader:998:32)

    at Module._load (node:internal/modules/cjs/loader:839:12)

    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
'.
[0m
 #  from /Users/bitsage/PersonalProjects/rnfbdemo/ios/Podfile:29
 #  -------------------------------------------
 #  target 'rnfbdemo' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
> pod install --repo-update
[31m
[!] Invalid `Podfile` file: unexpected token at 'Config Validation Error: "project.ios.automaticPodsInstallation" is not allowed

    at readConfigFromDisk (/Users/bitsage/PersonalProjects/rnfbdemo/node_modules/@react-native-community/cli-config/build/readConfigFromDisk.js:52:11)

    at loadConfig (/Users/bitsage/PersonalProjects/rnfbdemo/node_modules/@react-native-community/cli-config/build/loadConfig.js:65:65)

    at setupAndRun (/Users/bitsage/PersonalProjects/rnfbdemo/node_modules/@react-native-community/cli/build/index.js:159:39)

    at run (/Users/bitsage/PersonalProjects/rnfbdemo/node_modules/@react-native-community/cli/build/index.js:129:11)

    at Object.<anonymous> (/Users/bitsage/PersonalProjects/rnfbdemo/node_modules/@react-native-community/cli/build/bin.js:31:3)

    at Module._compile (node:internal/modules/cjs/loader:1120:14)

    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)

    at Module.load (node:internal/modules/cjs/loader:998:32)

    at Module._load (node:internal/modules/cjs/loader:839:12)

    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
'.
[0m
 #  from /Users/bitsage/PersonalProjects/rnfbdemo/ios/Podfile:29
 #  -------------------------------------------
 #  target 'rnfbdemo' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
```

**Comment by mikehardy** [comment]
@Sage-Rishi fascinating! I reproduce this locally.

> [!] Invalid `Podfile` file: unexpected token at 'Config Validation Error: "project.ios.automaticPodsInstallation" is not allowed

Root cause: There is an interdependency between `@react-native-community/cli` and `react-native` template, the template is now generating a `react-native.config.js` that contains this "project.ios.automaticPodsInstallation" key (it's a new feature in react-native 0.73 if I understand correctly) but the version of the `@react-native-community/cli` that ships with the template does not yet understand the key! That's an upstream bug.

Why didn't I see that? I'm mostly testing the upcoming react-native 0.73 release candidates now so I did not notice this problem with the current 0.72 version and I really appreciate the info.

Fix: I just updated the `make-demo.sh` script to `rm -f react-native.config.js` before it attempts the `pod install` and that fixes it for now. Will push that up to the repo in a moment when it's done validating locally

**Comment by Sage-Rishi** [comment]
@mikehardy Thanks the script for iOS works and compiles as well as installs an application on the iOS simulator. Interestingly I installed all the packages one by one onto a new project and kept building for iOS as I added one of each package and the app compiled without a hitch in this scenario. Although compiling the app on Xcode instead of using yarn still throws the same errors as above and the app doesn't install, although this is an issue on Xcode only.
<img width="719" alt="Screenshot 2023-11-02 at 11 04 26 PM" src="https://github.com/invertase/react-native-firebase/assets/31234123/94eeeb87-54aa-474d-bc6b-82319a85b882">

**Comment by mikehardy** [comment]
I wonder if you opened the `.xcworkspace` or the project? For cocopaods apps you have to open the xcworkspace. Just a guess though

**Comment by Sage-Rishi** [comment]
@mikehardy I opened .`xcworkspace` and not the project file as I have faced challenges with this while working on Flutter builds previously.

**Comment by Santosh12081998** [comment]
Xcode 15
React Native: 0.69.3
Add `use_frameworks! :linkage => :static` 
`$RNFirebaseAsStaticFramework = true` these two line before `use_react_native` and comment out `# use_flipper!()`
  
Now everything is working fine.
