### ISSUE TITLE
[🐛] [auth/internal-error] Errors not to be handled properly for signInWithEmailAndPassword

### ISSUE THREAD

**Issue by maximownrock** [invertase/react-native-firebase#7433]
## Issue

I'm experiencing an issue. When I call `signInWithEmailAndPassword` with valid credentials, everything works fine, and the user is successfully authenticated. However, if I input incorrect credentials, instead of getting error codes like `'auth/user-not-found'` or `'auth/wrong-password'` or something similar, I receive `'auth/internal-error'` with the message `[Error: [auth/internal-error] An internal error has occurred, please try again.]`

The most interesting part is that for the `createUserWithEmailAndPassword` function, everything works perfectly. Errors are handled correctly, and the user is created. I can't figure out what's causing the errors not to be handled properly for `signInWithEmailAndPassword`. Has anyone else encountered this issue?

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "Project",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint --ext .js,.ts,.tsx src",
    "lint-fix": "eslint --ext .js,.ts,.tsx src --fix",
    "start": "react-native start",
    "test": "jest"
  },
  "pre-commit": [
    "lint"
  ],
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.19.3",
    "@react-native-firebase/analytics": "^18.6.1",
    "@react-native-firebase/app": "^18.6.1",
    "@react-native-firebase/auth": "^18.6.1",
    "@react-native-firebase/crashlytics": "^18.6.1",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/stack": "^6.3.20",
    "@reduxjs/toolkit": "^1.9.7",
    "axios": "^1.5.1",
    "axios-case-converter": "^1.1.0",
    "formik": "^2.4.5",
    "i18next": "^23.6.0",
    "react": "18.2.0",
    "react-i18next": "^13.3.1",
    "react-native": "0.72.6",
    "react-native-gesture-handler": "^2.13.4",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-rate": "^1.2.12",
    "react-native-safe-area-context": "^4.7.4",
    "react-native-screens": "^3.27.0",
    "react-native-svg": "^13.14.0",
    "react-redux": "^8.1.3",
    "redux-persist": "^6.0.0",
    "redux-persist-transform-filter": "^0.0.22",
    "redux-saga": "^1.2.3",
    "yup": "^1.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/plugin-proposal-class-properties": "^7.18.6",
    "@babel/plugin-proposal-private-methods": "^7.18.6",
    "@babel/plugin-transform-flow-strip-types": "^7.22.5",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "@types/redux-persist": "^4.3.1",
    "@typescript-eslint/eslint-plugin": "^6.8.0",
    "@typescript-eslint/parser": "^6.8.0",
    "babel-jest": "^29.2.1",
    "babel-plugin-module-resolver": "^5.0.0",
    "eslint": "^8.19.0",
    "eslint-plugin-jest": "^27.4.3",
    "eslint-plugin-prettier": "^5.0.1",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-native": "^4.1.0",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "pre-commit": "^1.2.2",
    "prettier": "^3.0.3",
    "react-native-svg-transformer": "^1.1.0",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  }
}
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "crashlytics_debug_enabled": false,
    "crashlytics_disable_auto_disabler": true,
    "crashlytics_auto_collection_enabled": true,
    "crashlytics_is_error_generation_on_js_crash_enabled": true,
    "crashlytics_javascript_exception_handler_chaining_enabled": false,
    "google_analytics_automatic_screen_reporting_enabled": false
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

$RNFirebaseAsStaticFramework = true

target 'Artnership' do
  use_frameworks! :linkage => :static
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ArtnershipTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <Firebase.h>
#import <React/RCTBundleURLProvider.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  self.moduleName = @"Artnership";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

</p>
</details>

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^18.6.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/auth`
- **Are you using `TypeScript`?**
  - `YES` & `4.8.4`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Interesting - you should run this from Xcode on a real device and watch the console output, an internal error usually indicates that the firebase-ios-sdk will spit out some information that can be helpful in troubleshooting, before it is mostly discarded and just bubbles up as "internal error"

**Comment by maximownrock** [comment]
Thanks I'll do it and come back here with the answers

**Comment by ZaharenkoNickInterexy** [comment]
Similar problem. tell me, did you manage to solve it?

**Comment by crasneanucristian** [comment]
I have the same problem as @maximownrock when I run the app on simulator or a real device. 
react-native-firebase: ^18.6.1

**Comment by maximownrock** [comment]
Hello everyone, I haven't found a solution

**Comment by Slapbox** [comment]
I just started up our app with React Native Firebase for the first time but when I attempt to sign in nothing happens. No error, no indication anything is occurring. This in on 18.5.0.

I'm currently upgrading to 18.6.2 but based on the changelog and this issue being open I don't expect it will help.

Can anyone comment on what might be going wrong here?

**Comment by mikehardy** [comment]
@Slapbox please don't thread hijack, and for the second time in a couple seconds --> https://stackoverflow.com/help/how-to-ask

@ZaharenkoNickInterexy my comment above is where I've left this, haven't seen any information provided that addresses it:

>  Interesting - you should run this from Xcode on a real device and watch the console output, an internal error usually indicates that the firebase-ios-sdk will spit out some information that can be helpful in troubleshooting, before it is mostly discarded and just bubbles up as "internal error"

**Comment by Slapbox** [comment]
Sorry - I commented here because I believe it's related. Is there a reason you think it's definitely not?

If OP had had those symptoms on Android I would assume my issue was separate, but since they're having them on iOS I suspected it could be a difference in how (and if) the error is shown.

**Comment by Slapbox** [comment]
Sorry - I commented here because I believe it was related.

If OP had had those symptoms on Android I would assume my issue was separate, but since they're having them on iOS I suspected it could be a difference in how (and if) the error is shown.

----

> Perhaps you have a catch block somewhere where the authentication error is flying away, so you don't see it

Maybe, but why would it only occur when we move to `react-native-firebase`? Our auth errors were always properly thrown and caught when using the JS SDK.

**Comment by mikehardy** [comment]
@Slapbox you may have a real thing here - I would lean towards you having discovered some fidelity error between our behavior and the behavior in firebase-js-sdk - if you open a fresh issue we can explore it

**Comment by Slapbox** [comment]
I apologize for the issue noise. As I was filing a new issue, I found I overlooked a tiny error much higher up in the console: `forceWebSockets() is not implemented`. Removing our call to that unimplemented function allows login to proceed as expected.

Always fun when the proper debugger won't load and you're left skimming the CLI.

-----

So next I tried to reproduce the issue OP reported on Android, but I get the expected `'auth/user-not-found'` - so this problem may be iOS-specific. 

Unfortunately I'm a while from being able to test it on iOS on our end.

**Comment by mikehardy** [comment]
@Slapbox is that this API? https://firebase.google.com/docs/reference/js/database#forcewebsockets ? If we're missing APIs please feel free to open a "missing firebase-js-sdk API" issue and post them all up there. They may not have more than stub implementations here but we *do* have the goal of being a drop-in API-for-API replacement for firebase-js-sdk and I haven't done an audit yet on the modular / v9 API of firebase-js-sdk yet. An issue with a list of already-known ones would get us started

**Comment by ZaharenkoNickInterexy** [comment]
@mikehardy 
I'm getting this error. The error is reproduced on a real device, the application is built from xcode 
`[Error: [auth/internal-error] An internal error has occurred, please try again.]`

**Comment by mikehardy** [comment]
@ZaharenkoNickInterexy please note this part of my comment especially:

> watch the console output, an internal error usually indicates that the firebase-ios-sdk will spit out some information that can be helpful in troubleshooting

Was there nothing else in Console.log as this happened? No other information at all? I was really hoping for more 🤔

**Comment by AkhmetovAitzhan** [comment]
@maximownrock 
"if I input incorrect credentials, instead of getting error codes like `'auth/user-not-found'` or `'auth/wrong-password'` or something similar, I receive `'auth/internal-error'`"
this happens because of enabled "Email enumeration protection" in your firebase project>Authentication>Settings>User Actions. Source: [https://cloud.google.com/identity-platform/docs/admin/email-enumeration-protection](url).

**Comment by ZaharenkoNickInterexy** [comment]
@AkhmetovAitzhan @mikehardy 
Indeed, disabling this helped, but is it the right thing to do. Judging by firebase documentation, this option should not affect error statuses during authorisation. Is it correct, or have I misunderstood something?

**Comment by Slapbox** [comment]
> Invalid sign-in cases return an INVALID_LOGIN_CREDENTIALS error response. Invalid sign-up cases continue to return EMAIL_EXISTS errors

I think `INVALID_LOGIN_CREDENTIALS` is different than the default incorrect/non-existent email message. I wonder if React Native Firebase fails to handle it under the hood? 

----

> Judging by firebase documentation, this option should not affect error statuses during authorisation.

It sounds to me like that's actually exactly what it should do. It's obfuscating the existence of user accounts to prevent brute force attacks.

**Comment by mikehardy** [comment]
@Slapbox - `I think INVALID_LOGIN_CREDENTIALS is different than the default incorrect/non-existent email message. I wonder if React Native Firebase fails to handle it under the hood?` - perhaps, you can see the error code mappings in the respective native files (locating those quickly with a repo search on github web UI)

@AkhmetovAitzhan that's a great find! It would probably help quite a few people if you could hit the edit button at the top right of any of the web pages where it seemed important (perhaps the reference page for the APIs in question?) and add this as a note

**Comment by Slapbox** [comment]
It seems likely this is the mapping, and if so it seems correct: https://github.com/invertase/react-native-firebase/blob/f8b7794db23185c8a934a3e3623e996ce282c1f7/packages/auth/ios/RNFBAuth/RNFBAuthModule.h#L29

But maybe I'm misinterpreting.

**Comment by mikehardy** [comment]
Those are the iOS mappings, and they *do* look correct :thinking: - and there are separate ones for invalid email / wrong password - I suppose for those that haven't restricted the error to be just "invalid credentials"

https://github.com/invertase/react-native-firebase/blob/f8b7794db23185c8a934a3e3623e996ce282c1f7/packages/auth/ios/RNFBAuth/RNFBAuthModule.h#L29-L34

**Comment by Peetee06** [comment]
I just ran into the same issue where I used the following snippet:

```dart
final credential = EmailAuthProvider.credential(
  email: email,
  password: password,
);
await currentUser.reauthenticateWithCredential(credential);
```

I used an invalid password to test this. On android I get the expected error code of `invalid_credential`. On iOS I get `internal-error`. This is the Xcode console output:

```
Task <FBC18053-21A6-4984-BAEB-DEEC09E87D52>.<1> resuming, timeouts(60.0, 604800.0) QOS(0x19) Voucher (null)
[Telemetry]: Activity <nw_activity 12:2[9C93AC45-D0EC-42A5-8908-078ABFFBC6D3] (reporting strategy default)> on Task <FBC18053-21A6-4984-BAEB-DEEC09E87D52>.<1> was not selected for reporting
Connection 0: creating secure tcp or quic connection
Connection 61: enabling TLS
Connection 61: starting, TC(0x0)
Task <FBC18053-21A6-4984-BAEB-DEEC09E87D52>.<1> setting up Connection 61
Connection 61: asked to evaluate TLS Trust
[TLSCBQ] Need to invoke to satisfy trust callback
Task <FBC18053-21A6-4984-BAEB-DEEC09E87D52>.<1> auth completion disp=0 cred=0x2894eaeb0
System Trust Evaluation yielded status(0)
Connection 61: TLS Trust result 0
Connection 61: connected successfully
Connection 61: TLS handshake complete
Connection 61: ready C(N) E(N)
Task <FBC18053-21A6-4984-BAEB-DEEC09E87D52>.<1> done setting up Connection 61
Connection 61: set is idle false
Task <FBC18053-21A6-4984-BAEB-DEEC09E87D52>.<1> now using Connection 61
Connection 61: received viability advisory(Y)
Task <FBC18053-21A6-4984-BAEB-DEEC09E87D52>.<1> sent request, body S 145
Task <FBC18053-21A6-4984-BAEB-DEEC09E87D52>.<1> received response, status 400 content K
Task <FBC18053-21A6-4984-BAEB-DEEC09E87D52>.<1> done using Connection 61
Task <FBC18053-21A6-4984-BAEB-DEEC09E87D52>.<1> response ended
Connection 61: set is idle true
HTTP/2 Connection 61 Stream 1 ended successfully true
Task <FBC18053-21A6-4984-BAEB-DEEC09E87D52>.<1> finished successfully
Connection 61: cleaning up
Connection 61: done
Garbage collection for alternative services
flutter: \^[[38;5;199m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;199m│ [firebase_auth/internal-error] An internal error has occurred, print and inspect the error details for more information.<…>
[stack trace of the error in my app]
```

Is there any other information that I can supply which would help resolve this issue?

**Comment by mikehardy** [comment]
@Peetee06 

> flutter: 

You are in the react-native-firebase repository 🤔 

Regardless, nothing in the provided log snippet looks conclusively related to the error message either being actually internal with some SDK issue from firebase-ios-sdk (or flutter's firebase auth code) or just mapped incorrectly. So I'm not sure what to say there

**Comment by Peetee06** [comment]
@mikehardy you are right, I just realized that when looking at the notification I got for your answer. 😅

Will also post this in the correct repo, but nevertheless it seemed like the same issue. 

Thank you for your response!

**Comment by Slapbox** [comment]
@maximownrock @ZaharenkoNickInterexy @crasneanucristian did any of you have success resolving this? I'd like to enable the [enumeration feature](https://cloud.google.com/identity-platform/docs/admin/email-enumeration-protection) that I believe causes this in our project but I haven't had a chance to test yet.

The correct error this should return should be akin to `INVALID_LOGIN_CREDENTIALS` according to the Firebase docs.

Furthermore I never did find the Android mappings to see if they appear correct. Is it in this file, but just organized differently? But the messages are different too so I don't know: https://github.com/invertase/react-native-firebase/blob/f8b7794db23185c8a934a3e3623e996ce282c1f7/packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java

**Comment by amcoolkid** [comment]
This continue to be an issue, why cannot the lib pass down the right exception/error (on iOS, which is what I tested and observed) Everything seems goes into a `internal-error` Error.
Please help.

**Comment by mikehardy** [comment]
I can reopen this as it appears to still be an issue, but please note that "please help" could be rewritten in an open source context as "I will investigate this further and post a PR when I can" - we all need to help each other and ourselves in other words.

There may be some error code mapping issues internally - any fixes would be most welcome

**Comment by usman-whizpool** [comment]
I am also facing same issue. same app code works fine for android, while for iOS case it fails with this error.
double checked googleservice plist file. bundle id .

**Comment by usman-whizpool** [comment]
for me it was permission issue on google console. Firebase auto created api key was somehow edited and required permissions for firebase auth, token and other were missing. reseting it to default has resolve this issue

**Comment by EmanuilM** [comment]
> for me it was permission issue on google console. Firebase auto created api key was somehow edited and required permissions for firebase auth, token and other were missing. reseting it to default has resolve this issue

Where exactly in the console can I find these permissions, and which one have you changed?

**Comment by minhchienwikipedia** [comment]
Any solution? I just got this issue recently

**Comment by tux2nicolae** [comment]
I get the same error when calling `verifyPhoneNumber()`

**Comment by kevtechi** [comment]
> for me it was permission issue on google console. Firebase auto created api key was somehow edited and required permissions for firebase auth, token and other were missing. reseting it to default has resolve this issue

Same issue with our project as well `auth/internal-error` with no indication as to what the real problem was.

We deleted the iOS app configuration on Firebase and re-created it with the same bundle id. After that, re-downloaded the GoogleService-Info.plist file and it worked!

**Comment by odina101** [comment]
I have the same problem. I tried using signInWithPhoneNumber on react-native-firebase but got an internal error. After searching for the bug in my Xcode and pod files, I tried with web Firebase and got the same error. I think Firebase has a bug. :(

**Comment by kevtechi** [comment]
> I have the same problem. I tried using signInWithPhoneNumber on react-native-firebase but got an internal error. After searching for the bug in my Xcode and pod files, I tried with web Firebase and got the same error. I think Firebase has a bug. :(

The real error message is hidden. Try deleting and re-creating the Firebase App Configuration, then downloading the GoogleService-Info.plist file again.

**Comment by odina101** [comment]
> > I have the same problem. I tried using signInWithPhoneNumber on react-native-firebase but got an internal error. After searching for the bug in my Xcode and pod files, I tried with web Firebase and got the same error. I think Firebase has a bug. :(
> 
> The real error message is hidden. Try deleting and re-creating the Firebase App Configuration, then downloading the GoogleService-Info.plist file again.

thats why I tried first, even created other email with other firebase project, problem is with firebase not with us :)

**Comment by kevtechi** [comment]
It's unavoidable for Android push notifications as of a few years ago, so it's not going anywhere soon :) 

For anyone who sees this, try deleting/re-creating app configurations or disabling/enabling login options. 

If that doesn't work, try re-creating oauth client tokens in GCP.

If that doesn't work, make a fresh Firebase project 🤷‍♂️ .


I wonder if there would be a solution for this library to inform users a bit better about the issue.

**Comment by russellwheatley** [comment]
as @kevtechi has mentioned, for the vast majority of users with this issue, it can be fixed by redownloading the Firebase configuration file for the relevant platform from the Firebase console. This is a documentation issue.

**Comment by 1guzzy** [comment]
If you don't have your Firebase billing setup, that might be your problem. Firebase only allows 10 sms verifications a day if you don't have a payment method setup! Once I added a payment method, it started working!

**Comment by harshithvemulas** [comment]
I got an email from firebase to update to their blaze plan. once updated I am not getting this issue

**Comment by mikehardy** [comment]
Perhaps a docs PR in the tips-and-tricks section (or an auth troubleshooting section) that mentioned:
- make sure your API keys in the google cloud project have the correct permission
- make sure your code is correctly handling the current email enumeration protection settings for your project
- make sure you have a billing plan set up if you are relying on SMS
- make sure your project's GoogleServices plist file is correct, re-download if necessary

**Comment by zcmgyu** [comment]
I uncovered the issue when I ran the following command:

```bash
curl -X POST "https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=PASTE_YOUR_API_KEY" \
  -H "Content-Type: application/json" -d '{}'
```

That’s when I realized AppCheck had been enabled - something I hadn’t been informed of. 
The API_KEY I used came from GoogleService-Info.plist or google-services.json.
