### ISSUE TITLE
[🐛] No task registered for key ReactNativeFirebaseMessagingHeadlessTask

### ISSUE THREAD

**Issue by klejdisjorgji** [invertase/react-native-firebase#7435]
## Issue

I have expo managed RN app,

in index.js i have 
`AppRegistry.registerHeadlessTask('ReactNativeFirebaseMessagingHeadlessTask', () => FirebaseListenerHealth);`

and FirebaseListenerHealth is 
```
export default async (message) => {
    // handle your message

    console.log('event', message);
    
    return Promise.resolve();
}
```

i send the message with high-priority 
`curl --location 'https://fcm.googleapis.com/v1/projects/hearts-app-70b9a/messages:send' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer 123' \
--header 'Content-Type: application/json' \
--data '{
    "message": {
        "token": "token-here",
        "data": {
            "test": "test"
        },
        "android": {
            "priority": "high"
        }
    }
}'`

and then on the logs i see 
` WARN  No task registered for key ReactNativeFirebaseMessagingHeadlessTask`

The other type on notifications foreground/background are working okay, but i am interested on data only messages.

I have tested on android emulator and physical device
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@config-plugins/react-native-webrtc": "^7.0.0",
    "@react-native-firebase/app": "^18.6.0",
    "@react-native-firebase/firestore": "^18.6.0",
    "@react-native-firebase/messaging": "^18.6.0",
    "expo": "~49.0.15",
    "expo-dev-client": "~2.4.11",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-webrtc": "^111.0.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
```

</details>

**Comment by mikehardy** [comment]
could do with completeness --> https://stackoverflow.com/help/minimal-reproducible-example
