### ISSUE TITLE
this.native.onConfigUpdated is undefined

### ISSUE THREAD

**Issue by jamieGardyn** [invertase/react-native-firebase#7436]
## Issue

Describe your issue here
Just trying to get the real time listener working. I have the following code in my onComponentDidMount function i a class component... 

const remoteConfig1 = remoteConfig();

remoteConfig1.fetchAndActivate().then(() => {
      const remoteConfigValue = remoteConfig1.getValue('remoteConfigValue');
    });

    // Add a listener for real-time updates to the Remote Config values
   remoteConfig1.onConfigUpdated((configUpdate) => {
      const remoteConfigValue = configUpdate.getValue('remoteConfigValue');
    });

Getting this error on app load...
TypeError: this.native.onConfigUpdated is not a function. (In 'this.native.onConfigUpdated()', 'this.native.onConfigUpdated' is undefined)
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Template ignored, no version information provided, likely old version
Assuming a correct integration (which does not seem to be achieved yet, and is the responsibility of the developer...) you may look here for inspiration on usage https://github.com/invertase/react-native-firebase/blob/3d73352fb7434251fe661b426115339cf6d30bc1/packages/remote-config/e2e/config.e2e.js#L756

**Comment by jamieGardyn** [comment]
> Template ignored, no version information provided, likely old version Assuming a correct integration (which does not seem to be achieved yet, and is the responsibility of the developer...) you may look here for inspiration on usage
> 
> https://github.com/invertase/react-native-firebase/blob/3d73352fb7434251fe661b426115339cf6d30bc1/packages/remote-config/e2e/config.e2e.js#L756

I updated with react-native info - can you tell me if it is not compatible? I can't find anything I am doing wrong

**Comment by mikehardy** [comment]
There is an entire issue template. You have now completed one chunk of it.
The package.json part is important. You should examine our changelog, it will tell you when onConfigUpdated was implemented

**Comment by jamieGardyn** [comment]
> There is an entire issue template. You have now completed one chunk of it. The package.json part is important. You should examine our changelog, it will tell you when onConfigUpdated was implemented

I had examined and saw when it was added. I had used your example code and it told me 'await' can't be used b/c it is not a an async function so I tried the code I added above.

I was using version 10.5.1 of your libraries. I had deleted them, removed pod folder, removed podlock file, then reinstalled fresh and ran cd ios ... pod install

This is what is installed in packages.json
...
"@react-native-firebase/app": "^18.6.1",
    "@react-native-firebase/crashlytics": "^18.6.1",
    "@react-native-firebase/messaging": "^18.6.1",
    "@react-native-firebase/remote-config": "^18.6.1",
...
