### ISSUE TITLE
[Android] PhoneAuth in Genymotion Emulator with Play Services

### ISSUE THREAD

**Issue by Naveen-ICARUS** [invertase/react-native-firebase#744]
### Issue

Hey. I knew that firebase phoneAuth require google play services to work. Recently Genymotion support Play Services by installing OpenGApps. So I successfully installed Google play services on my Genymotion emulator but still its not working. It says "This app is not authorized to use Firebase Authentication. Please verify that the correct package name and SHA-1 are configured in the Firebase Console." stackoverflow also didn't help me. Please suggest how to use PhoneAuth in Genymotion Emulator.

### Environment

1. Application Target Platform: **Android** 

2. Development Operating System: **Ubuntu 17.04**

4. React Native version: **0.47.1**

5. RNFirebase Version: **^3.1.0**

6. Firebase Module: **auth().signInWithPhoneNumber()**

![2018-01-11 17-34-11](https://user-images.githubusercontent.com/31643287/34824765-d26e04e4-f6f5-11e7-863f-92f76464b119.png)

**Comment by chrisbianca** [comment]
As per: https://firebase.google.com/docs/auth/android/phone-auth#before-you-begin

`Also, note that phone number sign-in requires a physical device and won't work on an emulator.`
