### ISSUE TITLE
[🐛] Bug Android Deep Link Inconsistent Behavior Across Apps

### ISSUE THREAD

**Issue by ghost** [invertase/react-native-firebase#7444]
## Issue

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android

- **Firebase module(s) involved**:
  - [x] Deep Linking (Dynamic Links)

- **Versions**:
  - **React Native Firebase**: **^17.5.0**
  - **React Native**: "0.72.3"

## Description

Hi React Native Firebase Team,

We are facing a problem with the Firebase deep link behavior on Android. The deep link does not pass payload data when the app is opened from apps like WhatsApp or other third-party apps. The link opens and functions as expected when the same URL is opened in an incognito tab or directly in a Chrome browser.

Additionally, the deep link is not passing the payload when opened normally on Android devices, but it does in incognito mode. iOS does not exhibit this issue and works correctly in all scenarios.

## Steps to Reproduce

1. Send a Firebase deep link to an Android device through WhatsApp or another app.
2. Attempt to open the app through the deep link.
3. Observe that the payload is not passed to the app, and the link may not open correctly.

## Expected Behavior

The payload should be consistently passed to the app when opened from a deep link, regardless of the app from which it is opened, and whether it is in normal or incognito mode.

## Observed Behavior

On Android:
- The payload is not passed when the app is opened from within WhatsApp or other apps.
- The deep link does not open the app correctly when clicked from within WhatsApp or other apps.
- The deep link functions as expected when opened in incognito mode or directly when we paste url in the Chrome browser.

## Troubleshooting Steps

- Verified the issue on multiple Android devices.
- Ensured deep links work correctly when accessed through incognito mode or directly in the Chrome browser.
- Checked that this issue is not observed on iOS devices.

Thank you for looking into this matter.

**Comment by mikehardy** [comment]
Hi there! You have removed large sections of our template, which is a shame as that helps us troubleshoot.

I'll assume you mean "firebase dynamic links" as there is no firebase product called "deep links"

With apologies, and also with sadness as I use firebase dynamic links, they are shutting the service down and will only issue security-related fixes going forward, so there is unlikely to be a solution there.

One of the reasons is the inconsistent nature and near impossibility of getting it to work all the time, as you see. I don't think this will be resolvable, and in my apps at least I have fallback behavior for links such that if the payload is not passed there is the user ability to obtain the information again or input the missing information again as rapidly as possible. Not ideal but the links do not always work and the payloads do not always come through unfortunately

**Comment by mikehardy** [comment]
Also, your version is out of date, you might try 18.6.1 version here, with updated native SDKs underneath it, despite dynamic links being discontinued, there are newer versions and opening issues on older versions is typically unproductive as the first thing we'll do is ask you to update, like now

**Comment by Mubashirkhan** [comment]
i have updated the version to 18.7.2 and can still reproduce the issue mentioned. One thing is that for this issue is only reproducible on 1+ devices. On other android devices for-example samsung etc everything works fine

**Comment by mikehardy** [comment]
I have a OnePlus 6T and a 5 and both of them have worked for me. There could be skew within the device+android-version matrix though, perhaps these are just too old to get an updated Android version where it shows up on OnePlus, I don't know

Most unfortunately, this is still the critical comment:

> With apologies, and also with sadness as I use firebase dynamic links, they are shutting the service down and will only issue security-related fixes going forward, so there is unlikely to be a solution there.

Perhaps working directly with deep links (and/or react-native Linking API) is best
