### ISSUE TITLE
 In-App Messaging Popup and Campaign Deletion Problem

### ISSUE THREAD

**Issue by virenradadiya** [invertase/react-native-firebase#7446]
## Issue

Incorrect In-Message Popup Display:

When using in-app messaging, I expect to see a popup message within the application. However, the popup is not displaying as expected or not displaying at all. This affects the user experience and functionality of the feature.
Delayed or Persistent Popups After Deleting Campaigns:

Even after I have deleted campaigns, I still encounter in-app popups related to those campaigns. This behavior is unexpected and can be confusing for users.

Note: I have also enable the in-app messaging API  from the google cloud console.

---

### Javascript

![Screenshot 2023-11-08 at 6 54 54 PM](https://github.com/invertase/react-native-firebase/assets/30589064/a7781c39-2716-44bb-87fa-3a5dedfa5357)

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! You have ignored our issue template, so there is not much information to help with and I will close this issue.

It is important to note that react-native-firebase is a wrapper for the native firebase-ios-sdk and firebase-android-sdk libraries, and in the specific case of in-app-messaging it is a *very* thin wrapper. All the behavior you mention will be controlled by the native libraries with no control in this repository, so it is not really actionable here and I would pursue upstream

Also important to note that the firebase team offers support on stackoverflow of you post there with the correct tags - I submit that will be the most effective way to discuss what your goals are, and what you see vs your goals. Please be sure to include sufficient information to troubleshoot the issues, for instance, I will assume you updated to current versions here prior to posting an issue to make sure it hasn't been solved already - that's react-native-firebase v18.6.1, and I will further assume that you have not overridden the native SDK versions, thus you will be using firebase-ios-sdk 10.17.0 and firebase-android-sdk 32.5.0 when you ask for help
