### ISSUE TITLE
[🐛] Not Protected Android Activities  

### ISSUE THREAD

**Issue by MateuszMatyska** [invertase/react-native-firebase#7447]
## Issue

Activities **com.google.firebase.auth.internal.RecaptchaActivity** and **com.google.firebase.auth.internal.GenericIdpActivit**y are not protected. 
_[android:exported=true] An Activity is found to be shared with other apps on the device therefore leaving it accessible to any other application on the device._

I found that issue after security audit in one of application which use react-native-firebase library. 
Issue was found with MobSF static analyser. 
https://mobsf.github.io/docs/#/ 

If I made a mistake and add this issue to wrong section please move it to the right section.  
_I'm sorry I can not provide more information because of NDA._

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `18.6.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `Auth`
- **Are you using `TypeScript`?**
  - `Y` & `5.2.2`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
No template information, not actionable --> closing

> I'm sorry I can not provide more information because of NDA.

You'll have to provide information about versions etc
