### ISSUE TITLE
[Bug] FirebaseFirestoreInternal framework not found. i think there's something wrong with the Other Link Flags on ios that tries to link a framework on Firestore despite none existing.

### ISSUE THREAD

**Issue by joekabogo** [invertase/react-native-firebase#7454]
Good evening, I have the same problem.

No problem when installing app but problem when installing firestore.

here is package.json

```
"dependencies": {
    "@react-native-firebase/app": "18.6.1",
    "@react-native-firebase/firestore": "^18.6.1",
    "@react-navigation/native": "6.1.9",
    "@react-navigation/native-stack": "6.9.17",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-asset": "2.1.1",
    "react-native-linear-gradient": "3.0.0-alpha.1",
    "react-native-mmkv": "2.10.2",
    "react-native-permissions": "3.10.1",
    "react-native-reanimated": "3.5.4",
    "react-native-safe-area-context": "4.7.4",
    "react-native-screens": "3.27.0",
    "react-native-svg": "13.14.0",
    "zustand": "4.4.6"
  },
```

here is podfile

```
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
  #use_frameworks! :linkage => :static
  #FIREBASE
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseFirestoreInternal', :modular_headers => true
  $RNFirebaseAsStaticFramework = true
```

with `use_frameworks! :linkage => :static` I immediately have a problem with flipper

and the error in xcode :

<img width="262" alt="Capture d’écran 2023-11-06 à 23 45 59" src="https://github.com/invertase/react-native-firebase/assets/1051575/fe3350a0-50ca-4843-b123-8accec37fbf4">

Thanks a vous.

_Originally posted by @rocket13011 in https://github.com/invertase/react-native-firebase/issues/7430#issuecomment-1796987255_

**Comment by rocket13011** [comment]
Hello,

Here's how I got my app working with firebase. using the React-native procedure and this one from react-native-firebase.

all the useFramework has to be static, (I still don't understand why you can't say that only the react-native-firebase part requires this but hey.

and since flipper isn't compatible with it, you need to disable it.

so you have to set : 

`$RNFirebaseAsStaticFramework = true`

and delete the all modular_headers

in podfile

and above all do this for the pod install :

```USE_FRAMEWORKS=static NO_FLIPPER=1 arch -x86_64 pod install```  (silicon Chip)
or 
```bundle install && USE_FRAMEWORKS=static NO_FLIPPER=1 RCT_NEW_ARCH_ENABLED=1 bundle exec pod install``` (new build)

**Comment by helferleinsoftware** [comment]
I have got the same problem, also with Firebase versions 18.6.1.

Pod install fails with

```
The Swift pod `FirebaseFirestore` depends upon `FirebaseFirestoreInternal`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

When adding `pod 'FirebaseFirestoreInternal', :modular_headers => true`, Pod Install succeeds, but in the end, the iOS build fails with

`❌  ld: framework not found FirebaseFirestoreInternal`

**Comment by mikehardy** [comment]
```ruby

  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseFirestoreInternal', :modular_headers => true
```

No Podfile containing these statements or modular_headers statements like this will receive support here.

They are unsupported workarounds intended to avoid `use_frameworks! :linkage => :static` and they will result in problems like this. That use_frameworks configuration is a requirement of the underlying firebase-ios-sdk.

Remove them and use a supported configuration in your Podfile per our documents then your build will work.

**Comment by afzal-gsoftconsulting** [comment]
> ```ruby
>   pod 'FirebaseCore', :modular_headers => true
>   pod 'FirebaseCoreInternal', :modular_headers => true
>   pod 'GoogleUtilities', :modular_headers => true
>   pod 'FirebaseCoreExtension', :modular_headers => true
>   pod 'FirebaseFirestoreInternal', :modular_headers => true
> ```
> 
> No Podfile containing these statements or modular_headers statements like this will receive support here.
> 
> They are unsupported workarounds intended to avoid `use_frameworks! :linkage => :static` and they will result in problems like this. That use_frameworks configuration is a requirement of the underlying firebase-ios-sdk.
> 
> Remove them and use a supported configuration in your Podfile per our documents then your build will work.

Still not resolved. Please provide a link to resolve this issue.

**Comment by mikehardy** [comment]
> Still not resolved. Please provide a link to resolve this issue.

https://rnfirebase.io/#altering-cocoapods-to-use-frameworks

**Comment by FazilMuhammed** [comment]
please help, anyone works I am facing this issue @joekabogo @mikehardy @rocket13011

**Comment by mikehardy** [comment]
@FazilMuhammed please do not tag people randomly - the resolution is provided. You must remove all unsupported / build-failing `modular_headers` items from your Podfile and configure cocoapods for `use_frameworks! :linkage => :static` instead.
