### ISSUE TITLE
No DOCs references for Database

### ISSUE THREAD

**Issue by FacuAcosta** [invertase/react-native-firebase#746]
There's no documentation on the DOCs for the Database module, as you can see in here:

[https://rnfirebase.io/docs/v3.2.x/database/reference/Database](url)

**Comment by chrisbianca** [comment]
You can see them here: https://rnfirebase.io/docs/v3.2.x/database/reference/database

We've had a bit of an issue with the capitalisation on some of our docs that we are aware needs fixing.
