### ISSUE TITLE
[🐛] Analytics sends exact same event data

### ISSUE THREAD

**Issue by januswel** [invertase/react-native-firebase#7460]
## Issue

Describe your issue here

Events that has the same data with following columns are recorded in Firebase Analytics

- `event_timestamp`
- `event_name`
- `user_pseudo_id`

Here is summarized table with Big Query

<img width="240" alt="dups" src="https://github.com/invertase/react-native-firebase/assets/43239/b249b218-1ab0-4476-9100-dc03a523979c">

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "dependencies": {
    "@react-native-firebase/analytics": "18.6.1",
    "@react-native-firebase/app": "18.6.1",
    "@react-native-firebase/auth": "18.6.1",
    "@react-native-firebase/messaging": "18.6.1",
    "@react-native-firebase/remote-config": "18.6.1",
    "react-native": "0.72.6",
  }
}
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# = Lines that have a comment that starts with an equal (like this one) have been added to the base template for this
# = project. Please respect this convention to make it easier to distinguish boilerplate code from our own code.

# = Use statically linked frameworks
ENV['USE_FRAMEWORKS'] = "static"
# = Enable new architecture
ENV['RCT_NEW_ARCH_ENABLED'] = "0"
# = Enable Hermes
ENV['USE_HERMES'] = "1"
# = Disable Flipper
ENV['NO_FLIPPER'] = "1"

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'mybest' do

  # = https://rnfirebase.io/#altering-cocoapods-to-use-frameworks
  $RNFirebaseAsStaticFramework = true

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # =
  pod 'GoogleUtilities', '~> 7.11.1'
  pod 'LineSDKSwift/ObjC', '~> 5.0'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # = Required due to known issue in react-native-image-picker
    # = This setting has also been configured inside the project's Build Settings in Xcode (ios/mybest.xcodeproj/project.pbxproj)
    # = (Project > Build Settings > Apple Clang - Language - Modules > Allow Non-modular includes in Framework Modules)
    # = See: https://github.com/react-native-image-picker/react-native-image-picker/issues/2158
    # = TODO: Once the library is updated, this should be removed
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = true
    end
  end
end

# =
target 'ImageNotification' do
  pod 'KarteNotificationServiceExtension'
end
```

#### `AppDelegate.m`:

```objc
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by januswel** [comment]
Is this related to https://github.com/invertase/react-native-firebase/issues/7245 ?

**Comment by mikehardy** [comment]
🤔 hmm - we haven't run in to this before, so I haven't seen anything like and it don't have any special insight, sorry.

I did notice with a little concern that you are specifying the version for pod `GoogleUtilities` since that's a transitive dependency of the Firebase pod (and `FirebaseAnalytics` which is of specific concern...)

You might want to either remove the version specifier from your Podfile so Firebase podspecs can control the version, or carefully/periodically compare the versions and make sure they are compatible and then leave a comment/note in your Podfile to do the same

They use `~> '7.11'` as their spec, letting the patch version slide:

https://github.com/firebase/firebase-ios-sdk/blob/7605a1842cd247eb894498bb7fa0329d609b608d/FirebaseAnalytics.podspec#L31-L34

...in this case though a quick check on GoogleUtilities CHANGELOG indicates that should not affect anything https://github.com/google/GoogleUtilities/blob/main/CHANGELOG.md - it's just a note of caution

So that's likely not the problem, which sadly leaves me back at the "haven't seen this before..." point. You might try posting on stackoverflow with appropriate firebase tags to see if anyone else has seen this - official firebase support folks drop by on appropriately tagged questions as well so someone from firebase-ios-sdk team or with ability to contact them quickly may be able to offer support

**Comment by januswel** [comment]
@mikehardy 
Thank you for your advice!!
I'll ask this issue in stackoverflow 💪🏼

**Comment by kadiraydinli** [comment]
We are experiencing a similar issue. When we check from BigQuery, we can see that multiple events, including default events, are being sent more than once. Is there any progress related this issue?

Some of our events that we noticed repeated more than once:
- screen_view,
- first_open,
- app_open,
- app_remove,
- app_update,
- first_visit,
- os_update,
- session_start,
- user_engagement
- add_to_cart
- view_cart
- purchase
- remove_cart


**Versions:**

"@react-native-firebase/analytics": "^16.5.0",
"@react-native-firebase/app": "^16.5.0",
"@react-native-firebase/auth": "^16.5.0",
"react-native": "0.63.2",


Thanks in advance.

**Comment by mikehardy** [comment]
@kadiraydinli no time will spent analyzing a report on outdated versions, as a standard comment
