### ISSUE TITLE
[🐛] ld: framework now found FirebaseFirestoreInternal

### ISSUE THREAD

**Issue by NjegosP** [invertase/react-native-firebase#7464]
After updating React Native to v0.72, the app is not building and I get this error message:

❌  ld: framework not found FirebaseFirestoreInternal

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

NOTE: I can't use use_frameworks! because I'm using Flipper

### _Description_

After updating react-native-firebase modules to their latest versions, I've had to add these lines to the Podfile in order to make it work:

pod 'Firebase', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true

Then, after the RN update to v0.72, I was receiving this error message on `pod install`:

`The Swift pod FirebaseFirestore depends upon FirebaseCoreExtension and FirebaseFirestoreInternal, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set use_modular_headers! globally in your Podfile, or specify :modular_headers => true for particular dependencies.`

In order to make the error message go away, I had to add two more lines to the Podfile (and it worked!):

pod 'FirebaseCoreExtension', :modular_headers => true
pod 'FirebaseFirestoreInternal', :modular_headers => true

And then I encountered the error from this issue (framework not found). These are the Firebase modules I use in my app:

    "@react-native-firebase/analytics": "^18.6.0",
    "@react-native-firebase/app": "^18.6.0",
    "@react-native-firebase/auth": "^18.6.0",
    "@react-native-firebase/dynamic-links": "^18.6.0",
    "@react-native-firebase/firestore": "^18.6.0",
    "@react-native-firebase/messaging": "18.6.0",

NOTE:
- npm version: 9.6.7
- node version: v18.17.1
- output of gem which cocoapods: ruby-2.7.5/gems/cocoapods-1.14.3

### _Things I've tried and it didn't help_

- use_modular_headers! to enable modular headers globally (although even if it did work, I would like to avoid this solution)
- Adding `$RNFirebaseAsStaticFramework = true`
- Any combination of `pod install`, `pod deintegrate`, etc.
- Adding the FirebaseFirestoreInternal framework explicitly through XCode
- Trying to build the app on two different devices in order to avoid any possible caching issues

**Comment by mikehardy** [comment]
Hi there, you're using an unsupported build configuration that attempts to work around the stated + documented requirement to use `use_frameworks! :linkage => :static` in your Podfile:

```
 I've had to add these lines to the Podfile in order to make it work:

pod 'Firebase', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
```

You did not have to add those lines, and you will have to remove them for your build to work

**Comment by HemangiVekaria** [comment]
Hello
I am facing same issue.
in my package.json  "@react-native-firebase/firestore": "^18.6.2",

Here's screenshot of my podfile.
![Screenshot 2023-11-28 at 7 56 43 PM](https://github.com/invertase/react-native-firebase/assets/17717369/82dab915-eca1-4dbb-87ad-d7bea43e2ccb)
![Screenshot 2023-11-28 at 7 56 55 PM](https://github.com/invertase/react-native-firebase/assets/17717369/688526ad-0c51-4452-922e-4837e43b6022)


Can anyone please help? I am new to ios podfile

**Comment by mikehardy** [comment]
@HemangiVekaria I was very clear above: modular_headers is not supported.

No one should post for help in this repo for iOS build errors if they are using modular_headers in their Podfile. We cannot help you with those unsupported workarounds.

**Comment by HemangiVekaria** [comment]
Hello @mikehardy i already tried that before posting question here. But it was not working for me.

**Comment by mikehardy** [comment]
Firebase has no problem with installation as documented on rnfirebase.io, something is wrong with your integration but there's insufficient details in your comment to say. Do a small test on a throwaway example app to prove it, using my make-demo.sh script surely linked above somewhere

**Comment by HemangiVekaria** [comment]
> Hey @mikehardy, how do you fix erros like this if you delete the :modular_headers => true lines in the Podfile? Any help appreciated.
> 
> ![image](https://private-user-images.githubusercontent.com/43939710/287559474-2538b449-339b-435a-9eb7-813112708ea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NjI3MTQsIm5iZiI6MTcwMTY2MjQxNCwicGF0aCI6Ii80MzkzOTcxMC8yODc1NTk0NzQtMjUzOGI0NDktMzM5Yi00MzVhLTllYjctODEzMTEyNzA4ZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA0MDAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3OTdhNzY2MTQxMDFiYjc1NTIzMmRkOGM5MzZkZWVmZDU2ODRkMzAzNzU4MjFjMmRhYjYzZjRkNjk2ODMyMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3CW1O1E32rBkA5sDSK8asDuzIrWrmX5CwXS3jRSDtPE)

![image](https://github.com/invertase/react-native-firebase/assets/17717369/c19fb613-61d4-4968-9255-93db99b80cb8)
this is my pod file. I did change in marked areas and it's working ok for me now. Previously i was using use_frameworks! :linkage => :static  to the top commented area but now i changed position for that and it's working without any issue.

**Comment by SmartDev0910** [comment]
Perfect!
It worked well on my side.
Thanks. @HemangiVekaria

**Comment by dionator** [comment]
@HemangiVekaria 
Thanks a million! Spent days trying to get my app to work and your solution worked flawlessly!

**Comment by osama-ameer** [comment]
This is my pod file still stucked! 
@HemangiVekaria 


#pod 'Firebase', :modular_headers => true
#pod 'FirebaseCoreInternal', :modular_headers => true
#pod 'GoogleUtilities', :modular_headers => true
#pod 'FirebaseCore', :modular_headers => true
#pod 'FirebaseCoreExtension', :modular_headers => true
#pod 'FirebaseFirestoreInternal', :modular_headers => true


# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
#if linkage != nil
#  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#  use_frameworks! :linkage => linkage.to_sym
#end

target 'chat_app' do
  
  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
 
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    #:flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'chat_appTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
  
  
end

**Comment by osama-ameer** [comment]
@HemangiVekaria 
This is my pod file and I am still stucked!

![image](https://github.com/invertase/react-native-firebase/assets/51041844/3a9c990b-f50f-41f0-a833-08eb9f717d79)

**Comment by dionator** [comment]
> @HemangiVekaria This is my pod file and I am still stucked!
> 
> ![image](https://private-user-images.githubusercontent.com/51041844/323515964-3a9c990b-f50f-41f0-a833-08eb9f717d79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0Mjg0MDQsIm5iZiI6MTcxMzQyODEwNCwicGF0aCI6Ii81MTA0MTg0NC8zMjM1MTU5NjQtM2E5Yzk5MGItZjUwZi00MWYwLWE4MzMtMDhlYjlmNzE3ZDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA4MTUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMGRkNzk4Njg5Yzc2NTRmYjVkZWIyODRhN2E5MzRjYTQzZTAwZWEwMzhjYWVlOTIzYmZkYzgxYzQzOGY3OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oRqt7ZF-ptp9nxdnFGaMF6KqC6dOC0DEngDSbBCFfFY)


Looks like you haven't added the "pod 'FirebaseCore'" and others at the very end of your pod file.

**Comment by mikehardy** [comment]
Strange that is required. That has never been required in my build demonstrator, it always builds fine without ever specifying FirebaseCore or FirebaseCoreInternal pods

https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
