### ISSUE TITLE
[🐛]The following Swift pods cannot yet be integrated as static libraries:

### ISSUE THREAD

**Issue by HemangiVekaria** [invertase/react-native-firebase#7477]
I am getting this error when run pod install in my react native app.

**[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod FirebaseFirestore depends upon FirebaseCoreExtension and FirebaseFirestoreInternal, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set use_modular_headers! globally in your Podfile, or specify :modular_headers => true for particular dependencies.**

My package.json contain this 
![image](https://github.com/invertase/react-native-firebase/assets/17717369/1fccac8e-1365-4276-819a-6b3b801c0e8a)

![image](https://github.com/invertase/react-native-firebase/assets/17717369/d9659e4c-fc16-4423-b3bc-8f7b7d1fb937)

This is my podfile. 

![image](https://github.com/invertase/react-native-firebase/assets/17717369/c435bcbc-a1ca-4ea0-abde-731a7543aa20)

My XCode version is 15.0.1

Can anyone please help. I am trying to find solution for this from last 2 day. Previously my Xcode version was 14 and with that this works ok. Now I updated XCode to 15 and this stopped working. I already tried to reinstall Xcode 14 but now with that also pod install throws same error

**Comment by mikehardy** [comment]
You will receive zero support here for modular headers workarounds, if you  have been trying for two days and not encountered any of my comments saying the same that is a shame, as they are all over.

Our install documentation is clear:
- use_frameworks! :linkage -> :static is required. Use it. DO NOT USE modular_headers workarounds
- that implies you must disable flipper

Do these things.

**Comment by HemangiVekaria** [comment]
Hello @mikehardy i already tried that. I removed modular_headers but still get same error. I tried that before posting question here.

**Comment by mikehardy** [comment]
Try reading this script carefully (the comments are important) and running it. It works every time: https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

**Comment by cbdeveloper** [comment]
Had a similar issue. This is what I was missing:

https://rnfirebase.io/#altering-cocoapods-to-use-frameworks

**Comment by Nagibaba** [comment]
Don't use modular_headers. Just move this to top
```
use_frameworks! :linkage => :static

**Comment by francis19-bit** [comment]
Hi there, have been trying to extract aab file at expo but when ever I run eas build --platform ios...
I get this error sayin "install pods" 
The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
[!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `9D49179BBF8E48AF9B4D0CB0` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.

Can anyone please help me with this ?  Thank you.

**Comment by Djotchuang** [comment]
I added these two lines to my pod file directly before the `use_react_native` line.

`use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true`
  
  Read through Firebase's documentation for more details:
  https://rnfirebase.io/#altering-cocoapods-to-use-frameworks

**Comment by maximekahn** [comment]
> Don't use modular_headers. Just move this to top
> 
> ```
> use_frameworks! :linkage => :static
> ```

worked for me

**Comment by AksAman** [comment]
With the latest expo version, this line is not there in the Podfile

> Don't use modular_headers. Just move this to top
> 
> ```
> use_frameworks! :linkage => :static
> ```


Instead, i added a custom plugin/mod to the config file and it worked.
> Note: I am using typescript and using app.config.ts instead of app.json

Inside app.config.ts file
```typescript
// add this to your imports
import { ConfigPlugin, withDangerousMod } from "expo/config-plugins";
import { resolve } from "path";
import { readFileSync, writeFileSync } from "fs";


const withModularHeaders: ConfigPlugin = (config) => {
  return withDangerousMod(config, [
    "ios",
    async (config) => {
      const podfilePath = resolve(
        config.modRequest.platformProjectRoot,
        "Podfile"
      );
      let podfileContent = readFileSync(podfilePath, "utf-8");
      // // Only add if it's not already there
      if (!podfileContent.includes("use_modular_headers!")) {
        podfileContent = `use_modular_headers!\n${podfileContent}`;
        writeFileSync(podfilePath, podfileContent);
      }

      return config;
    },
  ]);
};
```

then you can add this to your config plugins as:
```typescript
 plugins: [
      // ...
      withModularHeaders,
     //...
]
```

**Comment by AksAman** [comment]
@mikehardy Oh got it! adding this to the plugins is cleaner and works. Realized this was in the [documentation](https://rnfirebase.io/#configure-react-native-firebase-modules) too.

```typescript
plugins: [
      // ...
      [
        "expo-build-properties",
        {
          ios: {
            useFrameworks: "static",
          },
        },
      ],
      //...
]
```
