### ISSUE TITLE
Can't build for Android probably due to a conflict of Google Play Services

### ISSUE THREAD

**Issue by victorsferreira** [invertase/react-native-firebase#748]
I setup my app with 'react-native-firebase' to receive the notifications. The problem now is that I have to find a way to show the notifications in the UI

I installed 'react-native-push-notifications' and now I cant build the project anymore. I get the error at 96%

" UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define"

It seems to be a conflict with the version of Google Play Services these two libraries use. 

How can i fix it? Are they incompatible? So how do I show the notifications?

**Comment by Ehesp** [comment]
FAQ has been done on this: https://rnfirebase.io/docs/v3.2.x/faqs#[Android]-Duplicate-Dex-Files-error-(build-time-error)
