### ISSUE TITLE
Podfile doesn't recognize "always_out_of_date" option

### ISSUE THREAD

**Issue by raminious** [invertase/react-native-firebase#7482]
[!] Invalid `Podfile` file: Unrecognized options `[:always_out_of_date]` in shell script `[RNFB] Core Configuration` within `MyApp` target. Available options are `[:name, :script, :shell_path, :input_files, :output_files, :input_file_lists, :output_file_lists, :show_env_vars_in_log, :execution_position, :dependency_file]`..

https://github.com/invertase/react-native-firebase/blob/02f1a2e1f32032b187b94316584e5b70abb47477/packages/app/react-native.config.js#L14

```
pod --version
1.12.1

react-native version
0.72.7

@react-native-firebase/app
18.7.0
```

**Comment by mikehardy** [comment]
Hmm - this was *just* released, you are a very early adopter, may I ask you to update your cocoapods as they are on 1.14.2 now? https://github.com/CocoaPods/CocoaPods/releases

I think it will work for you and that would help me figure this out

I may need to revert that change as I did not intend to issue a breaking change

**Comment by raminious** [comment]
appreciate it @mikehardy.
