### ISSUE TITLE
is it posibble to do whitelisting

### ISSUE THREAD

**Issue by pisacode** [invertase/react-native-firebase#749]
Hi 
For security, can we add whitelisting as if we were developing with native ios or android app?

**Comment by Ehesp** [comment]
Please give some context - not sure what you mean?

**Comment by pisacode** [comment]
Hi,

I am sorry to be very brief. I was looking for a solution to not expose API Keys, or even if I expose the keys I would like to protect the firebase account with whitelisting domains or adding a access restiriction with Bundle Ids or SHA like it is mentioned on this [link](https://firebase.google.com/support/guides/launch-checklist). However I then realize this plugin does not require initiliazing so I think my concern will go away with that.

**Comment by Ehesp** [comment]
Thanks I see what you mean. The Web point there doesn't apply to native apps. The android and ios points aren't really rnfirebase related, it's something you'd do before releasing to production within Android Studio or Xcode. Cheers
