### ISSUE TITLE
Execution failed for task ':react-native-firebase_app:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by sheggietyn** [invertase/react-native-firebase#7490]
* What went wrong:
Execution failed for task ':react-native-firebase_app:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-firebase_app:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /Users/Emmanuel/Library/Android/sdk/platforms/android-33/core-for-system-modules.jar.
         > Error while executing process /Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home/bin/jlink with arguments {--module-path /Users/Emmanuel/.gradle/caches/transforms-3/5f21d2de10aaaaa965a00fcb3b1f9e0d/transformed/output/temp/jmod --add-modules java.base --output /Users/Emmanuel/.gradle/caches/transforms-3/5f21d2de10aaaaa965a00fcb3b1f9e0d/transformed/output/jdkImage --disable-plugin system-modules}
         
         React native info:
         
         System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 457.32 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.5.0 - ~/.nvm/versions/node/v19.5.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.5.0/bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v19.5.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.11005911
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 21.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    
    
    my build.gradle
    
    import org.apache.tools.ant.taskdefs.condition.Os
def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
            googlePlayServicesVersion = "+" // default: "+"
            //firebaseMessagingVersion = "14.9.4" // default: "21.1.0"
            //firebaseMessagingVersion = "+"

        buildToolsVersion = "33.0.0" // 31.0.0
        minSdkVersion = 21  //21
        compileSdkVersion = 33 //31
        targetSdkVersion = 33 //31
        androidXCore = "1.7.0"
        kotlin_version = '1.6.10' //1.6.10
        kotlinVersion = '1.6.10' //**to remove */
        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else if (Os.isFamily(Os.FAMILY_WINDOWS)) {
            // For Android Users, we need to use NDK 23, otherwise the build will
            // fail due to paths longer than the OS limit
            ndkVersion = "23.1.7779620"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        //classpath("com.android.tools.build:gradle:7.0.4")
        classpath('com.android.tools.build:gradle:7.0.4')
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:4.1.2")
        //classpath 'com.google.gms:google-services:4.3.14' 
        classpath 'com.google.gms:google-services:4.4.0'    

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
    
    }  

     configurations.all {
        resolutionStrategy {
            // Remove this override in 0.65+, as a proper fix is included in react-native itself.
            force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
        }
    }
    
    
}

**Comment by mikehardy** [comment]
You are bold trying JDK21, most of the react-native ecosystem just moved from JDK11 to JDK17 (with some still on JDK11 and slightly out of date AndroidX libraries)

>  Execution failed for JdkImageTransform: /Users/Emmanuel/Library/Android/sdk/platforms/android-33/core-for-system-modules.jar

This is an upstream issue in the android gradle plugin and should be fixed in android-gradle-plugin 8.2.1 whenever that is released, follow here: https://issuetracker.google.com/issues/294137077

Until then, you must use JDK17 for anything android related, or use the android-gradle-plugin 8.3.x alpha series if you must though I wouldn't recommend it

**Comment by mkmule** [comment]
Had same issue as described here on Mac (M1 Pro): https://github.com/invertase/react-native-firebase/issues/7387
Fixed with installation of JDK17 as mentioned by @mikehardy!

```
brew install openjdk@17
```

I had some other issues before so ended-up with extra variables in my _.zshrc_:
```
export JAVA_HOME="/opt/homebrew/Cellar/openjdk@17/17.0.9/libexec/openjdk.jdk/Contents/Home"
export ANDROID_HOME="$HOME/Library/Android/sdk"
```

**Comment by kaxi1993** [comment]
> Had same issue as described here on Mac (M1 Pro): #7387 Fixed with installation of JDK17 as mentioned by @mikehardy!
> 
> ```
> brew install openjdk@17
> ```
> 
> I had some other issues before so ended-up with extra variables in my _.zshrc_:
> 
> ```
> export JAVA_HOME="/opt/homebrew/Cellar/openjdk@17/17.0.9/libexec/openjdk.jdk/Contents/Home"
> export ANDROID_HOME="$HOME/Library/Android/sdk"
> ```

Works fine, thanks

**Comment by kiplrohit** [comment]
Switching to JDK 11 from JDK17 Solved it for me. Gonna stay on this for much longer now. I don't want to, but we got no choice.

**Comment by Fewknowme** [comment]
Switching to JDK 11 from JDK17 Solved it for me. Gonna stay on this for much longer now. I don't want to, but we got no choice.
