### ISSUE TITLE
data-only notification not displayed at on android

### ISSUE THREAD

**Issue by Dyachenko022** [invertase/react-native-firebase#7491]
the structure of my notification looks like this: 
{
    "message": {
        "data": {
            "sdUuid": "${guidMessage}",
            "title": "${titleApp}",
            "body": "${textMessage}"
        },
        "android": {
            "priority": "High"
        },
        "token": "${token}"
    }
}

the IOS works fine, however on android it doesn't want to be displayed no matter what I do. 
i have onMessage and backgroundMessageHandler set up within my project.

If my notification has the following structure, everything works fine:
{
    message:
    {
        token: ${token},
        notification:
        {
            title = title,
            body = "Test Body",
        }
    }
};

is there any workaround?

**Comment by mikehardy** [comment]
A data-only notification will never generate anything visible for users.
Working as expected
