### ISSUE TITLE
500 Internal Error: Google Device provisioning API

### ISSUE THREAD

**Issue by sangamiv** [invertase/react-native-firebase#7497]
## Issue

**Error: API 500 Error | https://device-provisioning.googleapis.com/checkin**

 **"@react-native-firebase/app": "14.12.0",**

Describe your issue here

Encountering a 500 Internal Server Error on the Google Device Provisioning API call (https://device-provisioning.googleapis.com/checkin).
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

    "@react-native-firebase/analytics": "14.12.0",
    "@react-native-firebase/app": "14.12.0",
    "@react-native-firebase/crashlytics": "14.12.0",
    "@react-native-firebase/database": "14.12.0",
    "@react-native-firebase/firestore": "14.12.0",
    "@react-native-firebase/messaging": "14.12.0",
    "@react-native-firebase/remote-config": "14.12.0",
```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby

<key>firebasestorage.googleapis.com</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.5.2' 
```

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Versions not recent - please update to current and if you can reproduce we can reopen:

```
"@react-native-firebase/analytics": "14.12.0",
"@react-native-firebase/app": "14.12.0",
"@react-native-firebase/crashlytics": "14.12.0",
"@react-native-firebase/database": "14.12.0",
"@react-native-firebase/firestore": "14.12.0",
"@react-native-firebase/messaging": "14.12.0",
"@react-native-firebase/remote-config": "14.12.0",
```

accessing support on old versions is non-productive in general, new versions are issued to fix issues, so troubleshooting issues on old versions is not a smart use of time for reporter or maintainer...
