### ISSUE TITLE
Exception calling signInWithPhoneNumber

### ISSUE THREAD

**Issue by hmolotsi** [invertase/react-native-firebase#751]
[phone-auth-source-file.txt](https://github.com/invertase/react-native-firebase/files/1628865/phone-auth-source-file.txt)

### Issue

Exception calling signInWithPhoneNumber (see attached file). This was working until recently and now causes a crash in our Android app.

Exception java.lang.IllegalArgumentException: Cannot create PhoneAuthCredential without either verificationProof, sessionInfo, ortemprary proof.
com.google.android.gms.common.internal.zzbq.checkArgument ()
com.google.firebase.auth.PhoneAuthCredential.<init> ()
com.google.firebase.auth.PhoneAuthProvider.getCredential ()
io.invertase.firebase.auth.RNFirebaseAuth._confirmVerificationCode (RNFirebaseAuth.java:708)
java.lang.reflect.Method.invoke (Method.java)
com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:363)
com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:162)
com.facebook.react.bridge.queue.NativeRunnable.run (NativeRunnable.java)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:31)
android.os.Looper.loop (Looper.java:158)

### Environment

1. Application Target Platform: Only happens on Android (iOS works)

2. Development Operating System: macOS High Sierra 10.13.2

3. Build Tools: Android Studio 3.0.1

4. React Native version: 0.48.4

5. RNFirebase Version: 3.1.1

6. Firebase Module:

**Comment by chrisbianca** [comment]
@hmolotsi It doesn't look like you're listening for the `onAuthStateChanged` event to detect Android auto-verified numbers as per: https://rnfirebase.io/docs/v3.2.*/auth/phone-auth#3.-[Android]-Handle-Auto-Verification

**Comment by hmolotsi** [comment]
Thanks @chrisbianca

**Comment by gvillenave** [comment]
@chrisbianca Is listening to onAuthStateChanged the only way to implement this flow on Android? I was under the impression that calling confirm manually should work as well. It's especially an issue for devices like tablets that don't necessarily have a phone number and people use a separate device to authenticate.

Thanks!

**Comment by JanErikFoss** [comment]
I'm definitely listening to onAuthStateChanged but still having this problem.
Only on android, iOS works fine.

React Native 0.55.4
React Native Firebase 4.3.7

**Comment by Salakar** [comment]
@gvillenave `verifyPhoneNumber` is the one you want for full control over the flow without reliance on `onAuthStateChanged`. 👍 

See: https://rnfirebase.io/docs/v4.3.x/auth/phone-auth#verifyPhoneNumber

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by nomi9995** [comment]
i have also same problem

**Comment by JanErikFoss** [comment]
I've still got this problem on 5.0.0-rc.1, with react-native 0.57.0-rc.3

I'm listening to onAuthStateChanged in the parent component and calling signInWithPhoneNumber in the child component.

I'm aware that verifyPhoneNumber exists, but I don't really want or need full control over the flow.

**Comment by JanErikFoss** [comment]
So it turns out it works fine if I use the android device's own phone number. I was sending the code to my iPhone.

That means android users of my app can't log in with codes from phone numers other than their own. It works fine on iOS.

**Comment by AakashKB** [comment]
I am still experiencing this issue. Has anyone found a solution yet? I am definitely listening to onAuthStateChanged. When I reload the app, it logs me in so I am definitely getting logged in as well. However, the app still crashes when I enter the verification code.

**Comment by franzwarning** [comment]
Experiencing this issue on the `.confirm` call (android only). `.signInWithPhoneNumber` works fine. react-native: 0.59.3, react-native-firebase: 5.3.1

**Comment by Asalem1** [comment]
@franzwarning - experiencing the same issue with the same dependencies. Any chance you found some sort of resolution? SHA-1 is up, everything seems to be working besides this

**Comment by SABRYX** [comment]
any update on this issue

**Comment by zachrnolan** [comment]
I'm experiencing this issue as well, any chance we can get this reopened? Seems like it could be a problem with Android Firebase: https://github.com/firebase/FirebaseUI-Android/issues/1392

**Comment by franzwarning** [comment]
If you get on the latest version this is all resolved. I'm currently on 
```
"@react-native-firebase/app": "^6.0.2"
"@react-native-firebase/auth": "^6.0.2"
```

**Comment by jojonarte** [comment]
can anyone else confirm this getting fixed by upgrading to 6.0.2??

**Comment by mikehardy** [comment]
6.0.4 is out now, not sure if it is fixed though

**Comment by zachrnolan** [comment]
I upgraded to 6.0.3 and I haven't seen this crash yet.

**Comment by luisfuertes** [comment]
I have this issue with. 

Only in release mode, i dont receive phone code, but it continue to sms code step. If i submit wrong code, app crash.

Versions:
```
    "react": "16.9.0",
    "react-native": "0.61.5",
    "@react-native-firebase/app": "^6.3.4",
    "@react-native-firebase/auth": "^6.3.4",
    "@react-native-firebase/messaging": "^6.3.4",
```

Android google services
```
classpath 'com.google.gms:google-services:4.2.0'
```

Logcat:
```
FATAL EXCEPTION: mqt_native_modules
Process: com.my_app, PID: 10856
java.lang.IllegalArgumentException: Cannot create PhoneAuthCredential without either verificationProof, sessionInfo, temporary proof, or enrollment ID.
	at com.google.android.gms.common.internal.Preconditions.checkArgument(Unknown Source:35)
	at com.google.firebase.auth.PhoneAuthCredential.<init>(com.google.firebase:firebase-auth@@19.1.0:7)
	at com.google.firebase.auth.PhoneAuthProvider.getCredential(com.google.firebase:firebase-auth@@19.1.0:33)
	at io.invertase.firebase.auth.ReactNativeFirebaseAuthModule.confirmationResultConfirm(ReactNativeFirebaseAuthModule.java:945)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
	at android.os.Looper.loop(Looper.java:207)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
	at java.lang.Thread.run(Thread.java:764)
```

Javascript auth code:
```
_onSubmitPhone = async (phone, country) => {
    this.setState({ isFetching: true, phone, country }, async () => {
      try {
        const confirmResult = await auth().signInWithPhoneNumber(phone)
        console.log('_onSubmitPhone confirmResult: ', confirmResult)
        this.setState({ step: STEPS.CODE, confirmResult, isFetching: false })
      } catch (e) {
        console.log('_onSubmitPhone error: ', e)
        Alert.alert('Error', _.get(e, 'message', 'Ha ocurrido un error'))
        this.setState({ isFetching: false })
      }
    })
  }

  _onSubmitCode = async code => {
    const { confirmResult } = this.state
    if (confirmResult && code) {
      //console.log('_onSubmitCode confirmResult: ', confirmResult)
      this.setState({ isFetching: true, code }, async () => {
        try {
          const user = await confirmResult.confirm(code)
          console.log('_onSubmitCode user: ', user)
          this.setState({ step: STEPS.PASSWORD, user, isFetching: false })
        } catch (e) {
          console.log('_onSubmitCode error: ', e)
          Alert.alert('Error', _.get(e, 'message', 'Ha ocurrido un error'))
          this.setState({ isFetching: false })
        }
      })
    }
  }
```
