### ISSUE TITLE
[🐛] 18.7.3 - Build Error - incompatible CocoaPods versions

### ISSUE THREAD

**Issue by apetta** [invertase/react-native-firebase#7513]
## Issue

Getting a build error on iOS when working with Expo 49 dev client build (EAS). I'm currently trying to upgrade from 18.5.0 to ^18.7.3.

```
[!] CocoaPods could not find compatible versions for pod "Firebase/Functions":
[INSTALL_PODS]   In Podfile:
[INSTALL_PODS]     RNFBFunctions (from `../../../node_modules/@react-native-firebase/functions`) was resolved to 18.7.3, which depends on
[INSTALL_PODS]       Firebase/Functions (= 10.19.0)
[INSTALL_PODS] None of your spec sources contain a spec satisfying the dependency: `Firebase/Functions (= 10.19.0)`.
[INSTALL_PODS] You have either:
[INSTALL_PODS]  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
[INSTALL_PODS]  * mistyped the name or version.
[INSTALL_PODS]  * not added the source repo that hosts the Podspec to your Podfile.
```

---

## Project Files

package.json
```
    "@react-native-firebase/app": "18.7.3",
    "@react-native-firebase/app-check": "18.7.3",
    "@react-native-firebase/auth": "18.7.3",
    "@react-native-firebase/functions": "18.7.3",
```

**Comment by mikehardy** [comment]
> [INSTALL_PODS] None of your spec sources contain a spec satisfying the dependency: `Firebase/Functions (= 10.19.0)`.

The error is reasonably clear, but it does require familiarity with `pod` or a quick look here:

https://search.brave.com/search?q=%5BINSTALL_PODS%5D+None+of+your+spec+sources+contain+a+spec+satisfying+the+dependency%3A+%60Firebase%2FFunctions+(%3D+10.19.0)%60.&source=desktop

With a stackoverflow https://stackoverflow.com/questions/64037496/none-of-your-spec-sources-contain-a-spec-satisfying-the-dependencies-firebase

And you should know that Paul Beusterien is one of the developers on firebase-ios-sdk (and cocoapods) so if you see an answer from him, trust it!

https://stackoverflow.com/a/64048939/9910298

`pod install --repo-update` (or maybe just `pod repo update`)

**Comment by apetta** [comment]
Thank you 🙏

**Comment by nakapon9517** [comment]
I am experiencing the same problem here.
expo managed workflow cannot do `pod install`.
Is there a solution for that case yet?

```
"@react-native-firebase/analytics":"^18.7.3",.
"@react-native-firebase/app": "^18.7.3", "@react-native-firebase/app".
"@react-native-firebase/auth":"^18.7.3", "@react-native-firebase/analytics".
"@react-native-firebase/firestore":"^18.7.3", "@react-native-firebase/firestore".
"@react-native-firebase/functions": "^18.7.3", "@react-native-firebase/functions".
"expo":"^50.0.0",.
```

**Comment by mikehardy** [comment]
This is not expo specific this is specific to your local environment most likely.
There will be no changes in this repository with regard to this error, you will need to look carefully at the error message you receive, and follow the relevant suggestions from stackoverflow etc
