### ISSUE TITLE
Unable to log in via facebook sdk + signInWithCrdential

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#753]
### Issue

I'm not 100% positive on this, but I think that credential created via `auth.FacebookAuthProvider.credential(facebookToken);` might be wrong or missing something, alternatively something might be wrong with `auth().signInWithCredential`

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS High Sierra

3. Build Tools: XCode Version 9.2, iOS 11

4. React Native version: 0.52.0

5. RNFirebase Version: 3.2.1

6. Firebase Module: auth

Hey guys, was trying to follow tutorial here: https://rnfirebase.io/docs/v3.2.x/auth/social-auth#Facebook got more or less done with it, but am stuck at last step i.e. `firebase.auth().signInWithCredential(credential)`

Here is my sign in flow:

```
import { AccessToken, LoginManager } from "react-native-fbsdk";
import { firebase } from "react-native-firebase";

const auth = firebase.app().auth;

export async function facebookLogin() {
  try {
    const login = await LoginManager.logInWithReadPermissions(["public_profile", "email"]);
    if (!login.isCancelled) {
      const token = await AccessToken.getCurrentAccessToken();
      const credential = auth.FacebookAuthProvider.credential(token.accessToken);
      await auth().signInWithCredential(credential);
    }
  } catch (e) {
    console.error(e);
  }
}
```
It gets to the point where it generates credential like this

```
{
  token: "myTokenString", 
  secret: "", 
  providerId: "facebook.com"
}
```

but errors when I use this credential with `auth().signInWithCredential`. Error doesn't give much feedback, but this is it

> Error: An internal error has occurred, please try again.
>     at createErrorFromErrorData (NativeModules.js:123)
>     at NativeModules.js:80
>     at MessageQueue.__invokeCallback (MessageQueue.js:400)
>     at MessageQueue.js:139
>     at MessageQueue.__guardSafe (MessageQueue.js:316)
>     at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:138)
>     at debuggerWorker.js:72

**Comment by chrisbianca** [comment]
@IljaDaderko Have you enabled and configured Facebook login on the Firebase Auth dashboard? Can you check the native iOS logs - there should be a corresponding error which may have more information...

**Comment by IljaDaderko** [comment]
Yep, all is configured in firebase and facebook's developer console. As soon as I get my hands on my laptop I'll drop some native logs here 👍

**Comment by IljaDaderko** [comment]
@chrisbianca alright just got it running. No error pops up at an actual "login" bit, but this shows up on application start:

```
2018-01-15 16:59:38.305801+0200 skimitar[23358:1700859] -canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
2018-01-15 16:59:38.306144+0200 myProjectName[23358:1700859] Falling back to storing access token in NSUserDefaults because of simulator bug
```

**Comment by FacuAcosta** [comment]
I'm facing the same issue right now, what have you done to fix it?

**Comment by IljaDaderko** [comment]
@FacuAcosta nothing at the moment, we are trying to find a cause.

**Comment by IljaDaderko** [comment]
hmm, might be related but typescript gives this error for credential, looks like fbsdk doesn't generate `provider` property that firebase expects? At least according to their typings.

```
[ts]
Argument of type 'object' is not assignable to parameter of type 'Credential'.
  Property 'provider' is missing in type '{}'.
```

**Comment by chrisbianca** [comment]
@IljaDaderko as per the other thread, I'd take it you're using Typescript? This looks like a typings error, rather than anything with the library itself...

**Comment by IljaDaderko** [comment]
@chrisbianca my last comment, yep, but this issue as a whole looks like something wrong with `signInWithCredential` to me. I checked fbsdk setup, firebase has enabled facebook login, I get token from facebook correctly, but my app errors at firebase login.

**Comment by IljaDaderko** [comment]
Oh my days I am such a noob, resolved my issue. Somehow a merge conflict occurred and firebase setup files were not updated and used old ones. Testing this in android gave error with more context, it failed because old app is in pending deletion process.

@FacuAcosta it is probably something else for you, but double check you have correct google plis tand json files for firebase. Make sure Facebook auth is enabled and that everything is set up correctly in facebook's developer console.

**Comment by dashracer** [comment]
I'm having the same problem but with RN Firebase 4.0.

I've setup facebook app and firebase but still got that error

**Comment by IljaDaderko** [comment]
@dashracer I assume you are referring to facebook login using sdk when you say facebook app? In that case it works fine for me on v4.0.6, make sure you are getting correct data returned to construct firebase's credentials. If you can drop your implementation here I could take a look and see if anything looks odd :)

**Comment by rostyys** [comment]
Getting the same issue - facebook login and firebase are set up.

The error is received after getting the credential, when retrieving user.

My implementation (basically what react-native-firebase docs say to do)

<img width="699" alt="screen shot 2018-07-05 at 4 30 25 pm" src="https://user-images.githubusercontent.com/6425523/42352710-0899cfbc-8071-11e8-875d-e99f7f3bf063.png">
<img width="614" alt="screen shot 2018-07-05 at 4 30 41 pm" src="https://user-images.githubusercontent.com/6425523/42352720-1f8944fa-8071-11e8-9686-d37263279530.png">
