### ISSUE TITLE
:fire: Multiple apps setup in firebase project for firebase cloud messaging. (React-native-firebase android)

### ISSUE THREAD

**Issue by SMPinCode** [invertase/react-native-firebase#7531]
## Issue

I have an app with 5 different product markets and each of them has 8 different builds. So i have 40 various package names for example: `com.companyName.appName.marketName.dev`.

As mentioned in [https://developers.google.com/android/guides/google-services-plugin#adding_the_json_file](https://developers.google.com/android/guides/google-services-plugin#adding_the_json_file): When processing the JSON file for your Android app, the plugin only uses the client object that matches your package name (for the current build type)

Problems arising from adding more than 40 apps (+ iOS apps) to a firebase project:

1. Complication on adding more than 30 apps in firebase project as that is a limit. To raise the limit seems complicated. [https://firebase.google.com/support/faq#apps-per-project](https://firebase.google.com/support/faq#apps-per-project)
2. Maintenance (I would need to add additional apps if a new market would be introduced)

There is no need for me to have that many apps as i only need 1. ( I have omitted anything related to production app as it would reside in another firebase project)

I have added one apple app with an apple bundle id com.companyName.appName and it works for all suffixes. I have tried doing the same with android, but i get an error:

`What went wrong: Execution failed for task ':app:processCompanyNameMarketNameDevelopmentDebugGoogleServices'.  No matching client found for package name com.companyName.appName.marketName.dev`

Is there a way to have a package name as a wildcard as in `com.companyName.appName.*` or at least with marketName `com.companyName.appName.marketName.*` to work with all build types? I have added one apple app with an apple bundle id `com.companyName.appName` and it works for all suffixes. All ideas are welcome.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
classpath('com.google.gms:google-services:4.3.15')
```

#### `android/app/build.gradle`:

```groovy
apply plugin: 'com.google.gms.google-services'
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I think you'll need to take this up with firebase support, and I can say that they respond to stackoverflow questions if you tag them up well

Alternatively you could pursue it in the firebase-ios-sdk and/or firebase-android-sdk repos

I don't have any information to add at the react-native-firebase level though - we wrap and expose the functionality from the native SDKs so if they support it we likely support it. If they don't, we do not
