### ISSUE TITLE
Error: No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()

### ISSUE THREAD

**Issue by philipheinser** [invertase/react-native-firebase#7532]
updating to the latest version of rn firebase results in `Error: No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()` on android.

**Comment by mikehardy** [comment]
If you delete the template I have nothing to go on
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

Note that we have an app used for e2e that works, and I have this https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh which works

So the barrier to proving there is a problem is reasonably high, we need details to troubleshoot and this doesn't qualify.

**Comment by philipheinser** [comment]
@mikehardy does the e2e only check non concurrent react?

**Comment by mikehardy** [comment]
It is not new architecture nor is it concurrent. Only recently has that stuff been compatible with use_frameworks

**Comment by kbqdev** [comment]
+1
