### ISSUE TITLE
Firestore offline persistence, fromCache is always false

### ISSUE THREAD

**Issue by eugenecp** [invertase/react-native-firebase#754]
### Issue

I already set my internet access to Airplane Mode, however the metada fromCache is always false.

 ref.onSnapshot((qrySnapshot) => {
                console.log(qrySnapshot.metadata);
});

android log
01-15 11:26:09.518 15260  6986 I ReactNativeJS: { hasPendingWrites: false, fromCache: false }

### Environment

1. Application Target Platform: 
Android

2. Development Operating System: 
Windows 10

3. Build Tools: 
React-native run-android

4. React Native version: 
react-native-cli: 2.0.1
react-native: 0.51.0

5. RNFirebase Version: 
react-native-firebase@3.2.2

6. Firebase Module: 
Firestore

**Comment by eugenecp** [comment]
(Update)
Forget it... All is good after I reinstall the react-native-firebase module.

**Comment by sfratini** [comment]
@eugenecp I am reading that the module does not support enablePersistence. So, it does support offline caching for firestore?

**Comment by rspenc29** [comment]
Offline persistence doesn't seem to be working for firestore. If I turn off wifi, my data stops loading and I get `Network Request Failed` error. If I call `firebase.firestore().enablePersistence()` then I get `Persistence is enabled by default on the Firestore SDKs`

Offline persistence is working for authentication though. I just can't load any data from firestore that should already be cached.

**Comment by rikur** [comment]
+1

**Comment by imspikey** [comment]
Same fore me offline caching is not working.
has this issue been resolved?
