### ISSUE TITLE
 HostObject::get for prop 'RNFBUtilsModule

### ISSUE THREAD

**Issue by kundanthe** [invertase/react-native-firebase#7545]
Hello there ;

I updated react native from 0.67.5 to 0.72.7 in my project but its started giving firebase is not initialize error. After that I uninstall the firebase npm and installed again. Now I am getting this issue Which I had given below.

I am using these configuration.

  "@react-native-firebase/app": "^18.7.3",
   "react-native": "0.72.7",
   classpath 'com.google.gms:google-services:4.3.15'

-->

## Issue

Error: Exception in HostObject::get for prop 'RNFBUtilsModule': com.google.android.gms.common.GooglePlayServicesMissingManifestValueException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />, js engine: hermes

**Comment by mikehardy** [comment]
This must be an integration issue. We'll need a reproducible clean example in order to reopen this, as I regularly install everything from scratch and test it in order to prove out issues like this. You can run it yourself to see: https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
