### ISSUE TITLE
[🐛] 'FirebaseCore/FirebaseCore.h' file not found

### ISSUE THREAD

**Issue by keene2** [invertase/react-native-firebase#7553]
I've tried every solution to clean the cache and reinstall it, but nothing works.
<img width="324" alt="image" src="https://github.com/invertase/react-native-firebase/assets/108206051/3ed8b7b2-64ca-41fb-abcc-a092e671cea9">

System:
    OS: macOS 13.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 428.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.8.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
    Watchman: 2023.08.28.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 15.1/15C65 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: ^11.3.3 => 11.3.9 
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.10 => 0.71.10 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by mikehardy** [comment]
Hi there!

You must use `use_frameworks` - if you attempt unsupported workarounds you'll get this error.

It may be something different but you have not posted the required items from the issue template so I will close the issue.
