### ISSUE TITLE
Failed to initialize app. FirebaseOptions missing or invalid 'databaseURL' property.

### ISSUE THREAD

**Issue by Taimoormk** [invertase/react-native-firebase#756]
Failed to initialize app. FirebaseOptions missing or invalid 'databaseURL' property.

Firebase is hooked up fine on iOS but on Android it throws up above mentioned error also attached as a screenshot. Following code I am using in various Android grade and MainApplication files;

**build.gradle**

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.google.gms:google-services:3.1.2' // google-services plugin

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url "https://maven.google.com" // Google's Maven repository
        }
    }
}

**app/build.gradle**

apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.aqarchers"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile project(':react-native-fetch-blob')
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules

    // RNFirebase required dependencies
    compile "com.google.firebase:firebase-core:11.8.0"
    compile "com.google.android.gms:play-services-base:11.8.0"

    // RNFirebase optional dependencies
//    compile "com.google.firebase:firebase-ads:11.8.0"
//    compile "com.google.firebase:firebase-auth:11.8.0"
    // compile "com.google.firebase:firebase-config:11.8.0"
    // compile "com.google.firebase:firebase-crash:11.8.0"
    compile "com.google.firebase:firebase-database:11.8.0"
//    compile "com.google.firebase:firebase-firestore:11.8.0"
    // compile "com.google.firebase:firebase-messaging:11.8.0"
    // compile "com.google.firebase:firebase-perf:11.8.0"
    // compile "com.google.firebase:firebase-storage:11.8.0"
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'

**MainApplication.java**

package com.aqarchers;

import android.app.Application;

import com.facebook.react.ReactApplication;
import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.database.RNFirebaseDatabasePackage; // <-- Add this line
import com.RNFetchBlob.RNFetchBlobPackage;
import com.oblador.vectoricons.VectorIconsPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new RNFirebasePackage(),
            new RNFirebaseDatabasePackage(), // <-- Add this line
            new RNFetchBlobPackage(),
            new VectorIconsPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

### Environment

1. Application Target Platform: Android only (iOS is working fine)

2. Development Operating System: macOS Sierra

3. Build Tools: Android Studio

4. React Native version: 0.52.0

5. RNFirebase Version: 3.2.2

6. Firebase Module: Core and Database

![screenshot_1516095248](https://user-images.githubusercontent.com/27800340/34984446-d3dd3f44-fad2-11e7-8e6a-f78b8602b0c4.png)

**Comment by Ehesp** [comment]
Is your json file from Firebase in the correct place?

**Comment by Taimoormk** [comment]
Yes it is, to be on safe side, I copied it in android and android/app folders to make it work, but still no luck!

**Comment by chrisbianca** [comment]
Can I see how you're using initializeApp on the JS side?

**Comment by Taimoormk** [comment]
Yes you may, following is the code I am using for android configuration;

//pluck values from your 'google-services.json' you created on the firebase console
const androidConfig = {
  clientId: '<clientID>',
  appId: '<appID>',
  apiKey: '<apiKey>',
  databseURL: '<databaseURL>',
  storageBucket: '<storageBucket>',
  messagingSenderId: '<messagingSenderID>',
  projectId: '<projectID>',
  persistence: true,
}

const aqarchers = firebase.initializeApp(
  // use platform specific firebase config
  Platform.OS === 'ios' ? iosConfig : androidConfig,
  // name of this app
  'aqarchers'
);

const rootRef = firebase.database().ref();
export const chatRef = rootRef.child('chats');

**Comment by chrisbianca** [comment]
I assume you are supplying a databaseURL and not sending it through as an empty string?

**Comment by Taimoormk** [comment]
Yes you are correct, I actually placed placeholders within every string but for some reason it didn't come up in my last post, I am using all the configuration details from the google-services.json file supplied by Firebase console.

On the other note, same values are working fine with the iOS platform.

**Comment by chrisbianca** [comment]
`databseURL` is spelt incorrectly, it should be `databaseURL`

**Comment by Taimoormk** [comment]
Woopsy! good catch, cheers mate.

**Comment by anilkumar2273702** [comment]
I'm also getting the same error -

 WARN  Possible Unhandled Promise Rejection (id: 1):
Error: Missing or invalid FirebaseOptions property 'apiKey'.

**Comment by mikehardy** [comment]
So, how did it go when you added the apiKey to the configuration @anilkumar2273702 ? Seems like a perfect + complete error message that will lead you right to the fix

**Comment by decent1** [comment]
I'm also getting the same error -

 Possible Unhandled Promise Rejection (id: 1):
Error: Missing or invalid FirebaseOptions property 'apiKey'. 
urgent help

**Comment by decent1** [comment]
![image](https://user-images.githubusercontent.com/58625735/123772423-47e17380-d8e5-11eb-900d-c23a980495f5.png)

**Comment by mikehardy** [comment]
This is an issue from 3 years ago, there will not be any updates on it

Sorry you're experiencing problems but it looks like you have a fundamental module integration issue. Possible just downloading fresh copies of Google services json and plist from your firebase web console will fix.

**Comment by altafhussain786** [comment]
the best to solve this Problem is add databaseUrl in your firbaseconfig object I attached snapshot  

![codecodecode](https://user-images.githubusercontent.com/87299642/202919571-9e66c605-ece7-460f-ac74-70e71af0e5af.png)

**Comment by altafhussain786** [comment]
the best to solution of this problem is to add a database URL in your firbaseconfig object I attached snapshot
![Screenshot from 2022-11-20 23-36-59](https://user-images.githubusercontent.com/87299642/202919739-25a12e89-882c-4b06-9665-59a3509ffa04.png)

**Comment by mikehardy** [comment]
In general the best way is to download + use fresh json / plist config files from the firebase console on the web

**Comment by altafhussain786** [comment]
> In general the best way is to download + use fresh json / plist config files from the firebase console on the web

but it has not the databaseURL link
