### ISSUE TITLE
🔥[🐛] [expo][plugin] Does not add the Background Modes capabilities

### ISSUE THREAD

**Issue by AntoineThibi** [invertase/react-native-firebase#7577]
## Issue

The current documentation of react-native-firebase/messaging suggests enabling Background Modes capabilities for iOS as part of the setup process (see [iOS Setup](https://rnfirebase.io/messaging/usage/ios-setup#enable-background-modes)). However, when integrating the @react-native-firebase/messaging plugin via Expo, the Background Modes are not automatically added.

### Expected Behavior:
The documentation or the config plugin should align with the actual behavior of the package when used with Expo. If the Expo plugin @react-native-firebase/messaging does not automatically handle the addition of Background Modes, this discrepancy should be clearly mentioned in the documentation, along with guidance on how to manually set up Background Modes for iOS when using Expo.

### Steps to Reproduce:
Follow the instructions for setting up react-native-firebase/messaging on iOS as per the [official documentation](https://rnfirebase.io/messaging/usage/ios-setup#enable-background-modes).
Add the @react-native-firebase/messaging plugin via Expo.
Observe that backgroundModes are not added automatically as part of this process.

### Suggested Solution:
**Best solution** : updating the expo plugin to add those Background modes (if you agree with the issue, I can make a PR to add it)

Quick fix : changing the documentation, to also tell the user to add these capabilities : 
```
// app.json
{
  "expo": {
    "ios": {
      "infoPlist": {
        "UIBackgroundModes": ["fetch", "remote-notification"]
      }
    }
  }
}
```

---

## Project Files

```
// app.json

{
  "expo": {
    "android": {
      "googleServicesFile": "./google-services.json"
    },
    "ios": {
      "googleServicesFile": "./GoogleService-Info.plist"
    },
    "plugins": [
      "@react-native-firebase/app",
      "@react-native-firebase/messaging",
    ]
  }
}
```

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/app": "^18.7.3",
"@react-native-firebase/messaging": "^18.7.3",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**Expo SDK**: 49

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there - with apologies - we do have Expo support in the repo but it is community-provided. I do not personally use Expo so I will not be able to help here.

Hopefully someone that uses this library + Expo can step in to offer a solution

**Comment by zholmes1** [comment]
I think the solution that you posted (adding the background modes to `ios.infoPlist`) is a better solution than having it be part of the messaging package's plugin. It should be added to the documentation for the package. Expo already has first-class support for adding to the Info.plist, and there's no need to re-invent the wheel in a plugin.

**Comment by youssdevx** [comment]
Why confusing people when we can do it the right way and add it to the config plugin?
<img width="804" alt="image" src="https://github.com/user-attachments/assets/030c233b-98ee-4ac9-80de-41e2b86a58d0">

**Comment by mikehardy** [comment]
@youssdevx I don't think there is any intention to confuse anyone, however, from above:

> Hi there - with apologies - we do have Expo support in the repo but it is community-provided. I do not personally use Expo so I will not be able to help here.
> 
> Hopefully someone that uses this library + Expo can step in to offer a solution

It appears an Expo user needs to document how to add background modes using existing Expo tooling, or needs to post a PR to the config plugin to add this functionality

**Comment by michalvadak** [comment]
Is it still needed to add those Background modes? I can no longer see that option in iOS Capabilites and all seems to work without explicitly allowing it.

**Comment by samducker** [comment]
I can't comment if it is needed or not, but I believe this is the way to add the capabilities according to [https://docs.expo.dev/versions/latest/sdk/task-manager/](https://docs.expo.dev/versions/latest/sdk/task-manager/)

```
{
  "expo": {
    "ios": {
      "infoPlist": {
        "UIBackgroundModes": ["fetch", "remote-notification"]
      }
    }
  }
}
```

To your config

**Comment by zholmes1** [comment]
@samducker Yes, that's the original "Suggested Solution" that was posted at the top of this thread.

**Comment by mikehardy** [comment]
I believe if a knowledgable Expo user was to hit the "edit this page" button on the top right of this page and propose a PR, that might help all future Expo users? https://rnfirebase.io/messaging/usage#ios---notifications-entitlement
