### ISSUE TITLE
remote config - always config/failure

### ISSUE THREAD

**Issue by butchmarshall** [invertase/react-native-firebase#759]
Admob, cloud messaging and analytics packages are all working nicely for me.

I'm now trying to use the remote config.

The example always throws to the error condition for me?  Is there something additional I need to set up in the firebase console?

I'm running react-native 0.51.0 & react-native-firebase 3.2.0.

```
firebase.config().fetch()
  .then(() => firebase.config().activateFetched())
  .then(() => {
    // Chain additional firebase config methods if needed
  })
  .catch((error) => console.log(`Error processing config: ${error}`))
```

**Comment by chrisbianca** [comment]
@butchmarshall What's the error?

**Comment by Ehesp** [comment]
Please let us know if you're still having issues.

**Comment by tamarinda** [comment]
Commenting here in case somebody else like me pops by with the same issue. I am using only Remote Config from Firebase and I was calling fetch on `componentWillMount` and I was getting this same error, moving it to `componentDidMount` solved my issue.

Debugging with Android Studio, the promise rejection on `fetchInternal` was called with this message
`E/ReactNativeJS: { [Error: null] framesToPop: 1, code: 'config/failure' }`

And on the client the Exception screen with: `null <unknown> NativeModules.js 80:57`

**Comment by SeunLanLege** [comment]
Didn't work

**Comment by TheBlackHacker** [comment]
This solved my problem.
https://github.com/invertase/react-native-firebase/issues/844
