### ISSUE TITLE
[🐛]  ERROR  TypeError: _this.native.configureAuthDomain is not a function (it is undefined) 

### ISSUE THREAD

**Issue by roellongcop** [invertase/react-native-firebase#7599]
I get this error when i tried to run my mobile app in expo.

this is my package:
"@react-native-firebase/app": "^18.0.0",
"@react-native-firebase/auth": "^18.0.0",
"@react-native-firebase/database": "^18.5.0",
"@react-native-firebase/firestore": "^18.0.0",
 "@react-native-firebase/storage": "^18.0.0",
 
 
 
![image](https://github.com/invertase/react-native-firebase/assets/30338518/7e02a6cf-04b3-40cb-bc40-8222bde56784)

**Comment by mikehardy** [comment]
https://stackoverflow.com/help/minimal-reproducible-example
https://stackoverflow.com/help/how-to-ask

You have not provided much info to go on, and you have *actively* deleted our issue template where we request information to help.

Looks like it exists to me 🤔 

https://github.com/search?q=repo%3Ainvertase%2Freact-native-firebase%20configureAuthDomain&type=code

You likely need to rebuild your native code to contain it, as it is relatively new - released only in 18.8.0

Given lack of information, and likely solution of native rebuild, going to close.

Can reopen if you rebuild all your native stuff and it's still not there

**Comment by flipflopapp** [comment]
Hi @mikehardy 

I am also getting the same error.

I am using the following lib versions.

    "@react-native-firebase/app": "^20.4.0",
    "@react-native-firebase/auth": "^20.4.0",
    "@react-native-firebase/database": "^20.4.0",
    "@react-native-firebase/functions": "^20.4.0",
    "react-native": "0.72.15",
    "react": "18.2.0",
    
    I just upgraded from 18.x versions to 20.x . This was working in 18.x version .
    
    The error comes on iSimulator on my M1 machine with xcode 15.
