### ISSUE TITLE
Use with existing Swift project

### ISSUE THREAD

**Issue by erikaxel** [invertase/react-native-firebase#76]
Hi,

I have tried to use react-native-firebase with an existing swift project. It failed with 
```
/Users/erikaxel/Documents/Projects/lucalabs/luca_expenses_mobile/ios/Pods/Firebase/Core/Sources/Firebase.h:1:9: 'FirebaseAnalytics/FirebaseAnalytics.h' file not found
```

I did the following steps:

1. Created a project with react-native-cli `react-native init MyProject`
2. Replaced everything in ios with my existing code
At this point, everything was working and I checked that I managed to switch between views from React Native and Native. Firebase via cocoapods is also working at this point.
3. Added inn react-native-firebase with yarn. Im using 1.0.0-alpha13.
4. Used cocoapods to install RNFirebase. I was already using Firebase in my project, so everything related to that should be ok. 

However, I get the above mentioned error when trying to compile&run my project.

I have tried several steps to make it work, including adding a swift-objective-c bridge. One thing that almost worked was manually adding headers to the RNFirebase Framework project, but then the linker failed. And it would anyway get overwritten on next update of the framework, so it was in any case just a stopgap measure.

Have anyone any tips for solving this? I will be happy to provide PRs to either the doc or setup for future projects like this.

**Comment by tirrorex** [comment]
@erikaxel Did you manage to make it work by any chance?
