### ISSUE TITLE
Cannot get any response in signInWithPhoneNumber

### ISSUE THREAD

**Issue by llvc** [invertase/react-native-firebase#760]
I am going to sign in with phone number. So I used signInWithPhoneNumber in firebase phone authentication. It works on iphone but not work on android.
In detail of problem, I cannot get any promise response of 'then' as well as 'catch'.
I waited for 30 mins but didn't get any response.
I run the app on Nox. but I got same error in real device.
And I followed all steps in doc
The code is 

```
         console.log( 'Sending code ...' );
    
         firebase.auth().signInWithPhoneNumber(this.props.phoneNumber)
         .then(confirmResult => {
               console.log('code sent', confirmResult)
               this.setState({ confirmResult })
         })
         .catch(error => {
               console.log('Sign In With Phone Number Error', error)
         });
```

I got ` Sending code... ` but I couldn't get any subsequent message like 'code sent' or 'sign in with phone number error' although I wait for along time.

**Environment**
"react-native-firebase": "^3.1.1",
"react-native": "0.50.0",
Application Target Platform: Android
Build Tools: Android Studio 2.3.3, Android SDK 27
Android version tested: 4.2.2

Let me know what's wrong
Thanks.

**Comment by Ehesp** [comment]
Hello - could you check in Android logs for any errors / messages? Sounds like something native isn't returning which the logs will let us know about.

**Comment by llvc** [comment]
I got `Sending code ...` on logcat. And I didn't get anything else.
I didn't use browser debug mode.
Informing one thing missed, I didn't specify  `apply plugin: 'com.google.gms.google-services'` in app/android/build.gradle

```
dependencies {
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile "com.android.support:support-v4:26.1.0"
    compile "com.android.support:design:26.1.0"
    // Firebase dependencies
    compile "com.google.android.gms:play-services-base:11.6.0"
    compile "com.google.firebase:firebase-core:11.6.0"
    compile "com.google.firebase:firebase-auth:11.6.0"

    compile 'com.google.android.gms:play-services:11.+'
    compile 'com.google.android.gms:play-services-auth:11.+'
    compile 'com.google.android.gms:play-services-wallet:11.+'
}
 ....

// apply plugin: 'com.google.gms.google-services'
```

**Comment by llvc** [comment]
I could solve this by revising android/app/build.gradle as following.

dependencies {
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile "com.android.support:support-v4:26.1.0"
    compile "com.android.support:design:26.1.0"
    // Firebase dependencies
    compile "com.google.android.gms:play-services-base:11.6.0"
    compile "com.google.firebase:firebase-core:11.6.0"
    compile "com.google.firebase:firebase-auth:11.6.0"

    compile 'com.google.android.gms:play-services:11.6.0'
    compile 'com.google.android.gms:play-services-auth:11.6.0'
    compile 'com.google.android.gms:play-services-wallet:11.6.0'
}
 ....

 apply plugin: 'com.google.gms.google-services'

**Comment by llvc** [comment]
I could solve this by updating android/app/build.gradle as following.

```
dependencies {
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile "com.android.support:support-v4:26.1.0"
    compile "com.android.support:design:26.1.0"
    // Firebase dependencies
    compile "com.google.android.gms:play-services-base:11.6.0"
    compile "com.google.firebase:firebase-core:11.6.0"
    compile "com.google.firebase:firebase-auth:11.6.0"

    compile 'com.google.android.gms:play-services:11.6.0'
    compile 'com.google.android.gms:play-services-auth:11.6.0'
    compile 'com.google.android.gms:play-services-wallet:11.6.0'
}
 ....

 apply plugin: 'com.google.gms.google-services'
```
