### ISSUE TITLE
Something went wrong running `pod install` in the `ios` directory.

### ISSUE THREAD

**Issue by nicolofranceschi** [invertase/react-native-firebase#7601]
hi,

when i install @react-native-firebase/firestore with

npx expo add @react-native-firebase/firestore

pods installation faild, 

is there a different way to use this library with expo ?

**Comment by mikehardy** [comment]
https://stackoverflow.com/help/how-to-ask

There is not enough information here to help. You have deleted the template, which is required an actual action on your part, to not provide information
