### ISSUE TITLE
🔥[🐛] Unnecessary latency when fetching from firestore

### ISSUE THREAD

**Issue by joaqo** [invertase/react-native-firebase#7610]
## Issue
Hi, I found what I think is an issue with the way firestore handles its cache, which results in unnecessary latency, and makes view transitions in iOS look choppy.

In summary, I am making very simple firestore queries (one of which I post below), for a db that contains only a handful of small documents, which is taking about 180ms. This is a problem for two reasons. First, I already have this data cached locally, so the query should be almost instant. Second, it's affecting the view transitions. Midway through the transition the firebase document is fetched and the view renders, creating this weird effect that goes against the smooth iOS transition.

In my search for a solution I came about [this comment](https://github.com/invertase/react-native-firebase/issues/3491) on an issue here, I tried disabling the network by placing `firestore().disableNetwork()` in my code, and the latency went down to about 30ms. Much better but not really useful as I have disabled my network and also the transition was still not perfect. After that, I tried using `npx expo run:ios --configuration Release` and the latency basically disappeared, giving me perfect transitions.

What I wanted to understand in this issue is why is react-native-firebase seemingly waiting for a network response before returning cached data? I've used firestore extensively in native iOS (SwiftUI) and it immediately returns the cached data, with a possible subsequent update to it if the network response returns any changes to the cached data. This latency reduction created by caching is one of the features the firebase team most boasts about, so I think this is the way it's meant to work.

I suspect this may be a generalized issue as I am just using a barely modified expo `tabs@50` template and tried it on several iOS devices and simulators.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `query`:

```typescript
  // onSuccess is just a react hook updating a very simple data structure, nothing special
  let start = Date.now()
  firestore()
    .collection("sellers")
    .doc(id)
    .get()
    .then((snap) => {
      if (snap.exists) {
        onSuccess({ id: snap.id, ...snap.data() } as Seller);
        console.log("Time", Date.now() - start)
      } else {
        handleError(Error(`Document doesn't exist: ${id}`));
      }
    })
    .catch((error) => handleError(error));
```

</details>

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M2
  Memory: 89.16 MB / 16.00 GB
  Shell:
    version: 5.2.2
    path: /opt/homebrew/bin/bash
Binaries:
  Node:
    version: 20.11.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.4
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: javac 21
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.3
    wanted: ^0.73.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `18.8.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `firestore`
- **Are you using `TypeScript`?**
  - `Y` & `Version 4.9.5`

</p>
</details>

**Comment by mikehardy** [comment]
So there is a performance problem, but in release mode it works?

> After that, I tried using npx expo run:ios --configuration Release and the latency basically disappeared, giving me perfect transitions.

That's encouraging. I'm not sure exactly what is different between your debug and release mode configurations, but if the transitions are - at least in release mode - smooth then it seems like searching for what those differences are and if they are tolerable for development / with tests in release mode prior to release may be the path forward

**Comment by joaqo** [comment]
In release mode it worked only if I used `firestore().disableNetwork()`, which was not really a solution as I was left without the ability to sync to the remote firestore server.

We have successfully fixed the issue though, turns out we were using `get` and `then`, instead of `onSnapshot` on our queries. This caused firestore to make the request instead of looking at the cache.

**Comment by mikehardy** [comment]
Oh! I misunderstood the scenario then, I did not realize disableNetwork was required to remove the latency in release mode, I thought release mode was sufficient. So that would not have been okay

It sounds like through using a different API this may be closable though (something you can do, if correct)? I've already misunderstood once though, don't want to close without knowing I actually understand correctly this time...

**Comment by joaqo** [comment]
You're absolutely right, I'll go ahead and close it. Thanks!
