### ISSUE TITLE
[🐛] Messaging onclick event handle

### ISSUE THREAD

**Issue by SitaMelark** [invertase/react-native-firebase#7612]
I almost finished my app but im missing a onclick event when clicking a firebase notifications launched from a java server, tried with some of the messaging() methods but seems to not work for android, still didnt try in ios because have not yet the developer licence. Would like to have it to work in ios and android. This is the notifications class:

```
import messaging from '@react-native-firebase/messaging';
import { MMKV } from 'react-native-mmkv';
//import PushNotification from 'react-native-push-notification';
import { updateFirebaseToken } from './Posts';
import PushNotification from 'react-native-push-notification';
import { useEffect } from 'react';

const storage = new MMKV();

export function Notification() {
  PushNotification.createChannel(
    {
      channelId: "canal1",
      channelName: "Canal1",
    },
    created => { }
  );

  messaging().setBackgroundMessageHandler(async remoteMessage => {
  });

  messaging().onMessage(async remoteMessage => {

    if (remoteMessage.notification !== undefined) {
      let messageTitle = remoteMessage.notification.title;
      let messageBody = remoteMessage.notification.body;

      if (messageTitle !== undefined && messageBody !== undefined) {
        // Crea una notificación local con los datos
        PushNotification.localNotification({
          channelId: "canal1",
          title: messageTitle,
          message: messageBody,
        });
      } else {
        console.log("El título o el mensaje de la notifcación no está definido");
      }
    } else {
      console.log("La notificación no está definida");
    }
  });

  messaging().onTokenRefresh((newToken) => {
    let oldToken = storage.getString("firebaseToken");
    const cre = storage.getString("credentials");
    if (cre !== undefined && oldToken !== undefined) {
      updateFirebaseToken(oldToken, newToken);
      storage.set("firebaseToken", newToken);
    }
  });
  

}
```
And this is the main app:

```
import { NavigationContainer } from '@react-navigation/native';
import { createDrawerNavigator } from '@react-navigation/drawer';
import { Notification } from "../data/Notification";
import Redirect from '../navigation/Redirect';
import Login from '../screens/Login';
import Balance from '../screens/Balance';
import Impuestos from '../screens/Impuestos';
import SubirFactura from '../screens/SubirFactura';
import NotsElectronicas from "../screens/NotsElectronicas";
import LaboralResumen from '../screens/Laboral/LaboralResumen';
import LaboralNominas from '../screens/Laboral/LaboralNominas';
import { useEffect, useState } from 'react';
import { MMKV } from 'react-native-mmkv';
import { Alert, Platform, StatusBar, View } from 'react-native';
import DeviceInfo from 'react-native-device-info';
//import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';


//const Tab = createBottomTabNavigator();
const Drawer = createDrawerNavigator();
Notification();

const storage = new MMKV();

function App(): JSX.Element {
  const storedData = storage.getString("credentials");


  const deviceModel = DeviceInfo.getDeviceId();

  const iPhoneModels = [
    'iPhone1,1', // iPhone (1st generation)
    'iPhone1,2', // iPhone 3G
    'iPhone2,1', // iPhone 3GS
    'iPhone3,1', 'iPhone3,2', 'iPhone3,3', // iPhone 4
    'iPhone4,1', // iPhone 4S
    'iPhone5,1', 'iPhone5,2', // iPhone 5
    'iPhone5,3', 'iPhone5,4', // iPhone 5C
    'iPhone6,1', 'iPhone6,2', // iPhone 5S
    'iPhone7,2', // iPhone 6
    'iPhone7,1', // iPhone 6 Plus
    'iPhone8,1', // iPhone 6S
    'iPhone8,2', // iPhone 6S Plus
    'iPhone8,4', // iPhone SE (1st generation)
    'iPhone9,1', 'iPhone9,3', // iPhone 7
    'iPhone9,2', 'iPhone9,4', // iPhone 7 Plus
    'iPhone10,1', 'iPhone10,4', // iPhone 8
    'iPhone10,2', 'iPhone10,5' // iPhone 8 Plus
  ];

  return (
    <>
      {Platform.OS === "ios" && <View style={[{ width: '100%' }, iPhoneModels.includes(deviceModel) ? { height: 20 } : { height: 44 }]}></View>}
      <NavigationContainer>
        <Drawer.Navigator
          initialRouteName={storedData === undefined ? "Login" : "Balance"}
          screenOptions={{ swipeEnabled: false }}>
          <Drawer.Screen
            name="Login"
            component={Login}
            options={{
              headerLeft: () => null,
              headerShown: false,
            }} />
          <Drawer.Screen
            name="Balance"
            component={Balance}
            options={{
              headerLeft: () => null,
              headerShown: false,
              unmountOnBlur: true,
            }} />
          <Drawer.Screen
            name="Impuestos"
            component={Impuestos}
            options={{
              headerLeft: () => null,
              headerShown: false,
              unmountOnBlur: true,
            }} />
```

**Comment by mikehardy** [comment]
Hi there, this is a project-specific problem with API usage and we don't have the resources to code up project features for people's projects.

If you run into a situation where you are using a react-native-firebase API, and the API itself is not failing, please post the smallest possible App.js that reproduces the specific problem with all details (including if it is a notification issue, the JSON you send to the FCM REST API to trigger the notification...) and nothing else

https://stackoverflow.com/help/minimal-reproducible-example

Otherwise I have to assume this is just a project-specific issue with no change required in react-native-firebase

In addition, if you delete the issue template, we'll close the issue as we won't have the required information to help

**Comment by SitaMelark** [comment]
> Hi there, this is a project-specific problem with API usage and we don't have the resources to code up project features for people's projects.
> 
> If you run into a situation where you are using a react-native-firebase API, and the API itself is not failing, please post the smallest possible App.js that reproduces the specific problem with all details (including if it is a notification issue, the JSON you send to the FCM REST API to trigger the notification...) and nothing else
> 
> https://stackoverflow.com/help/minimal-reproducible-example
> 
> Otherwise I have to assume this is just a project-specific issue with no change required in react-native-firebase
> 
> In addition, if you delete the issue template, we'll close the issue as we won't have the required information to help

I made the change in the App.js right now, may i get help now?

**Comment by mikehardy** [comment]
With apologies, the current issue description does not seem to be made with an understanding of https://stackoverflow.com/help/minimal-reproducible-example

A minimal example would not include some "Posts" page, nor would it include MMKV or onTokenRefresh handling or anything like that.

Create a notification and post it while logging the attempt and the result of the post
Create one handler function to handle a remote message, make sure the handler logs everything that happens
Install that handler function as the handler for your various possible events

Just do that *all* in App.js. One file.

Make all the log messages very clear and easy to understand.

Paste that App.js in here. Paste the contents of the log when you run this new minimal "app"
