### ISSUE TITLE
reauthenticateWithCredential makes app crashes [iOS + Android]

### ISSUE THREAD

**Issue by marcoizzo** [invertase/react-native-firebase#762]
When reauthenticateWithCredential method is called, app crashes on iOS and Android.

I would like to change user password. This is my code:

```
...
firebase.auth().currentUser.reauthenticateWithCredential(email, password).then(() => {
     return user.updatePassword(newPassword)
}).then(() => {
...
```

Xcode log says:
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Either IDToken or accessToken must be supplied.'`

On Android:
<img width="344" alt="schermata 2018-01-17 alle 17 53 36" src="https://user-images.githubusercontent.com/13518657/35055386-6338c6cc-fbaf-11e7-9c54-50d46b3c8e33.png">

My environment:
"react": "16.2.0",
"react-native": "0.52.0",
"react-native-firebase": "^3.1.1",

**Comment by chrisbianca** [comment]
`reauthenticateWithCredential` needs a credential, not the email and password:
```
const credential = firebase.auth.EmailAuthProvider.credential(email, password);
firebase.auth().currentUser.reauthenticateWithCredential(credential).then(() => {

});
```

**Comment by pietroleggero** [comment]
- (void)authorizationController:(ASAuthorizationController *)controller didCompleteWithAuthorization:(ASAuthorization *)authorization API_AVAILABLE(ios(13.0)) {
  ASAuthorizationAppleIDCredential* appleIDCredential = authorization.credential;
  NSString *idToken = [NSString stringWithUTF8String:[appleIDCredential.identityToken bytes]];
   
        FIROAuthCredential *credential = [FIROAuthProvider credentialWithProviderID:@"apple.com"
                                                                            IDToken:idToken
                                                                        accessToken:nil];
        _providerSignInCompletion(credential, nil, nil, nil);
}
When idToken is null you have the crash
