### ISSUE TITLE
[📚] Issues while seting up iOS notification images - iOS Notification Images

### ISSUE THREAD

**Issue by darlanhms** [invertase/react-native-firebase#7632]
Summary: I followed every step on [iOS Notification Images section](https://rnfirebase.io/messaging/ios-notification-images) and I still had some issues building my application, I managed to solve em' but I don't know if it is worth documenting. (It is a expo bare workflow BTW). It wasn't an error with this library itself and it is probably some annoying ios configuration, I just think it is helpful to share if someone is having the same issues.

- ### Unable to integrate the following embedded targets with their respective host targets (a host target is a "parent" target which embeds a "child" target like a framework or extension)
This issue always occurs when I put `target 'ImageNotification' do ...` at the end of the file.
I solved it by putting it before the last `end` tag.

- ### Cycle inside ...; building could produce unreliable results. Cycle details: → Target '...': ExtractAppIntentsMetadata
I solved it by clicking on xcode project, **Targets** -> **Build Phases** and dragging "Embed Frameworks" above "Compile Sources"

- ### 'sharedApplication' is unavailable: not available on iOS
I solved it by pasting the following code to `Podfile`. It disables that option on every pod.
```
  post_install do |installer|
    ...
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
   ...

```

- ### [Sandbox: bash(72986) deny(1) file-write-data /Users/XXX/ios/Pods/resources-to-copy-XXXShareExtension.txt
I solved it by going to xcode project **Build Settings** and setting `User Script Sandboxing` to 'No'

---- 

I'm not experienced at writing issues, if the issue is bad written or not related just close it.

**Comment by controtie** [comment]
Super helpful finding this post today. Thanks for sharing your findings!

**Comment by themtaysw** [comment]
hi @darlanhms so i followed your guide and its great and worked before but since i needed clean build i prebuild with expo and now this step fix: 

**'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.**

doesnt work, any suggestion?

my Podfile:

`
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '13.4'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...), which will be excluded. To fix this,
# you can also exclude `react-native-flipper` in `react-native.config.js`
#
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
#   }
# }
# ```
flipper_config = FlipperConfiguration.disabled
if ENV['NO_FLIPPER'] == '1' then
  # Explicitly disabled through environment variables
  flipper_config = FlipperConfiguration.disabled
elsif podfile_properties.key?('ios.flipper') then
  # Configure Flipper in Podfile.properties.json
  if podfile_properties['ios.flipper'] == 'true' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"])
  elsif podfile_properties['ios.flipper'] != 'false' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"], { 'Flipper' => podfile_properties['ios.flipper'] })
  end
end

target 'matysw' do
  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Note that if you have use_frameworks! enabled, Flipper will not work if enabled
    :flipper_configuration => flipper_config
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  
  target 'ImageNotification' do
    pod 'Firebase/Messaging', '~> 10.23.1'
  end
end
`

**Comment by FadiAboMsalam** [comment]
@darlanhms You are lifesaver Thank you so much for this documentation it was super helpful.
God bless you

**Comment by JamesZhao2022** [comment]
Thank you so much for help, I did everything to fix the issue. Build and run all works, but the image didn't show, did you do anything to make the image show in app notifcation?

**Comment by darlanhms** [comment]
@JamesZhao2022 another thing that I had to do was unbind this framework and bind again (click on it and `-` and add the same one again (it should create another build phases there you should check if it is correctly ordered again)
<img width="806" alt="ex" src="https://github.com/invertase/react-native-firebase/assets/50335402/90e3221e-d151-4393-a6be-4bd9b3c574e7">

**Comment by Jahanzeb009** [comment]
by following these instructions, the build error fixed but only notifications with images still not showing

**Comment by sntg-p** [comment]
I also had these problems (except the sharedApplication one) and still can't make images appear on the notification. Even though the Notification Service extension is running (I'm modifying the title and it appears in my device).

Maybe it is a problem of firebase-ios-sdk?

**Comment by mayur-bhandari** [comment]
> I also had these problems (except the sharedApplication one) and still can't make images appear on the notification. Even though the Notification Service extension is running (I'm modifying the title and it appears in my device).
> 
> Maybe it is a problem of firebase-ios-sdk?

I tried to update the title but it is not appearing on my device. Can you please share your Notification Service file?

**Comment by sntg-p** [comment]
It's just the autogenerated one with the `populateNotificationContent` from Firebase.

```objc
#import "NotificationService.h"
#import "FirebaseMessaging.h"

@interface NotificationService ()

@property (nonatomic, strong) void (^contentHandler)(UNNotificationContent *contentToDeliver);
@property (nonatomic, strong) UNMutableNotificationContent *bestAttemptContent;

@end

@implementation NotificationService

- (void)didReceiveNotificationRequest:(UNNotificationRequest *)request withContentHandler:(void (^)(UNNotificationContent * _Nonnull))contentHandler {
    self.contentHandler = contentHandler;
    self.bestAttemptContent = [request.content mutableCopy];

    // Modify the notification content here...
    // self.bestAttemptContent.title = [NSString stringWithFormat:@"%@ [modified]", self.bestAttemptContent.title];

    // self.contentHandler(self.bestAttemptContent);
    [[FIRMessaging extensionHelper] populateNotificationContent:self.bestAttemptContent withContentHandler:contentHandler];

}

- (void)serviceExtensionTimeWillExpire {
    // Called just before the extension will be terminated by the system.
    // Use this as an opportunity to deliver your "best attempt" at modified content, otherwise the original push payload will be used.
    self.contentHandler(self.bestAttemptContent);
}

@end
```

In my case, I noticed it is working but it seems like URL has to specify the image extension. As in:
- https://myhost.com/image won't work
- https://googledimage.com/image.jpg will work

Not really sure if this is the same problem other people are having, but it is indeed a different behavior from Android where both URLs would work.

**Comment by krisnapy** [comment]
> Summary: I followed every step on [iOS Notification Images section](https://rnfirebase.io/messaging/ios-notification-images) and I still had some issues building my application, I managed to solve em' but I don't know if it is worth documenting. (It is a expo bare workflow BTW). It wasn't an error with this library itself and it is probably some annoying ios configuration, I just think it is helpful to share if someone is having the same issues.
> 
> * ### Unable to integrate the following embedded targets with their respective host targets (a host target is a "parent" target which embeds a "child" target like a framework or extension)
> 
> This issue always occurs when I put `target 'ImageNotification' do ...` at the end of the file. I solved it by putting it before the last `end` tag.
> 
> * ### Cycle inside ...; building could produce unreliable results. Cycle details: → Target '...': ExtractAppIntentsMetadata
> 
> I solved it by clicking on xcode project, **Targets** -> **Build Phases** and dragging "Embed Frameworks" above "Compile Sources"
> 
> * ### 'sharedApplication' is unavailable: not available on iOS
> 
> I solved it by pasting the following code to `Podfile`. It disables that option on every pod.
> 
> ```
>   post_install do |installer|
>     ...
>     installer.pods_project.targets.each do |target|
>       target.build_configurations.each do |config|
>         config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
>       end
>     end
>    ...
> ```
> 
> * ### [Sandbox: bash(72986) deny(1) file-write-data /Users/XXX/ios/Pods/resources-to-copy-XXXShareExtension.txt
> 
> I solved it by going to xcode project **Build Settings** and setting `User Script Sandboxing` to 'No'
> 
> I'm not experienced at writing issues, if the issue is bad written or not related just close it.

`  post_install do |installer|
    ...
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
   ...`
   
I followed the guide provided by @darlanhms to add the `APPLICATION_EXTENSION_API_ONLY` configuration in my `Podfile`. However, after adding this code, I encountered the following warning for several pod libraries on github action deployment:
   `warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.2.99.` for some pods library

**Comment by krisnapy** [comment]
I've tried setting the IPHONEOS_DEPLOYMENT_TARGET directly in the Podfile using the following code:
`config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'`

<img width="403" alt="Screenshot 2024-06-08 at 4 24 13 AM" src="https://github.com/invertase/react-native-firebase/assets/96037957/1b5e330c-7526-4f5a-bfdc-61aa129b3059">

**Comment by binle** [comment]
I got the same

> hi @darlanhms so i followed your guide and its great and worked before but since i needed clean build i prebuild with expo and now this step fix:
> 
> **'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.**
> 
> doesnt work, any suggestion?
> 
> my Podfile:
> 
> ```
> require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
> require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
> 
> require 'json'
> podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}
> 
> ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
> ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
> 
> platform :ios, podfile_properties['ios.deploymentTarget'] || '13.4'
> install! 'cocoapods',
>   :deterministic_uuids => false
> 
> prepare_react_native_project!
> 
> # If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
> # because `react-native-flipper` depends on (FlipperKit,...), which will be excluded. To fix this,
> # you can also exclude `react-native-flipper` in `react-native.config.js`
> #
> # ```js
> # module.exports = {
> #   dependencies: {
> #     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
> #   }
> # }
> # ```
> flipper_config = FlipperConfiguration.disabled
> if ENV['NO_FLIPPER'] == '1' then
>   # Explicitly disabled through environment variables
>   flipper_config = FlipperConfiguration.disabled
> elsif podfile_properties.key?('ios.flipper') then
>   # Configure Flipper in Podfile.properties.json
>   if podfile_properties['ios.flipper'] == 'true' then
>     flipper_config = FlipperConfiguration.enabled(["Debug", "Release"])
>   elsif podfile_properties['ios.flipper'] != 'false' then
>     flipper_config = FlipperConfiguration.enabled(["Debug", "Release"], { 'Flipper' => podfile_properties['ios.flipper'] })
>   end
> end
> 
> target 'matysw' do
>   use_expo_modules!
>   config = use_native_modules!
> 
>   use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
>   use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']
> 
>   use_react_native!(
>     :path => config[:reactNativePath],
>     :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
>     # An absolute path to your application root.
>     :app_path => "#{Pod::Config.instance.installation_root}/..",
>     # Note that if you have use_frameworks! enabled, Flipper will not work if enabled
>     :flipper_configuration => flipper_config
>   )
> 
>   post_install do |installer|
>     react_native_post_install(
>       installer,
>       config[:reactNativePath],
>       :mac_catalyst_enabled => false
>     )
> 
>     # This is necessary for Xcode 14, because it signs resource bundles by default
>     # when building for devices.
>     installer.target_installation_results.pod_target_installation_results
>       .each do |pod_name, target_installation_result|
>       target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
>         resource_bundle_target.build_configurations.each do |config|
>           config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
>         end
>       end
>     end
>     installer.pods_project.targets.each do |target|
>       target.build_configurations.each do |config|
>         config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
>       end
>     end
>   end
> 
>   post_integrate do |installer|
>     begin
>       expo_patch_react_imports!(installer)
>     rescue => e
>       Pod::UI.warn e
>     end
>   end
>   
>   target 'ImageNotification' do
>     pod 'Firebase/Messaging', '~> 10.23.1'
>   end
> end
> ```

I got the same error. I moved the target ImageNotification to the end of file and it worked.
![image](https://github.com/invertase/react-native-firebase/assets/13077778/9956657e-8bd9-4176-81b0-d73e3f515756)

**Comment by tommyDoroGit** [comment]
I too cannot get an Image to appear on a IOS push notification. I'm running the following;

package.json
```
    "react-native": "0.69.12",
    "@react-native-firebase/app": "17.5.0",
    "@react-native-firebase/messaging": "17.5.0",
``` 

Podfile 

```
    target 'ImageNotification' do
      use_frameworks! :linkage => :static
      pod 'Firebase/Messaging'
    end
``` 

Curiously, I get this error in Xcode where the `FirebaseMessaging.h` import is failing despite the pod being located in the project. See below

<img width="1239" alt="image" src="https://github.com/invertase/react-native-firebase/assets/40597861/4574bb50-014d-4c38-bad2-627862ea2b81">

Can anyone confirm that the IOS image support actually works?

**Comment by binle** [comment]
> I too cannot get an Image to appear on a IOS push notification. I'm running the following;
> 
> package.json
> 
> ```
>     "react-native": "0.69.12",
>     "@react-native-firebase/app": "17.5.0",
>     "@react-native-firebase/messaging": "17.5.0",
> ```
> 
> Podfile
> 
> ```
>     target 'ImageNotification' do
>       use_frameworks! :linkage => :static
>       pod 'Firebase/Messaging'
>     end
> ```
> 
> Curiously, I get this error in Xcode where the `FirebaseMessaging.h` import is failing despite the pod being located in the project. See below
> 
> <img alt="image" width="1239" src="https://private-user-images.githubusercontent.com/40597861/343070814-4574bb50-014d-4c38-bad2-627862ea2b81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTExMTAsIm5iZiI6MTcxOTM5MDgxMCwicGF0aCI6Ii80MDU5Nzg2MS8zNDMwNzA4MTQtNDU3NGJiNTAtMDE0ZC00YzM4LWJhZDItNjI3ODYyZWEyYjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA4MzMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMTM3YzQyY2UyMTVkOGJjNDA4MjRlMzdmMDE1YWUxYmJlM2ZlM2FjOTg2YTdhNTEwNDU5YzhjM2Q1YTAwMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d0Q2DqeMaqkAEZy-TG1R45bxf54wYwht7kyd7kwRNX4">
> Can anyone confirm that the IOS image support actually works?

It still worked for me. In your case, I think you missed `pod install`
my client's app:

![image](https://github.com/invertase/react-native-firebase/assets/13077778/8efc6c97-68f8-46fc-9140-d3aabc30f046)

**Comment by tommyDoroGit** [comment]
Thanks for sending through @binle. 

The pod is in my Podfile.lock so it appears the pod installed correctly

<img width="676" alt="image" src="https://github.com/invertase/react-native-firebase/assets/40597861/f4e1b688-2587-4718-bc02-7f66f90fca2e">

**Comment by tommyDoroGit** [comment]
A further update, I managed to get the Podfile's to properly install, resulting in the below config in Xcode. After a successful build, I'm still unable to see the notification images.

<img width="967" alt="Screenshot 2024-06-27 at 5 26 28 pm" src="https://github.com/invertase/react-native-firebase/assets/40597861/38b1524d-2161-4af4-ad60-4be46e76529a">
<img width="971" alt="Screenshot 2024-06-27 at 5 26 50 pm" src="https://github.com/invertase/react-native-firebase/assets/40597861/6aace247-438e-4eac-9e37-4b85236eaa2f">
<img width="1126" alt="Screenshot 2024-06-27 at 5 25 42 pm" src="https://github.com/invertase/react-native-firebase/assets/40597861/750d1aab-16ea-427c-b11b-3d02425df9cb">

**Comment by abhisheksoni27** [comment]
@Salakar @mikehardy @Lyokone Do we have any update on this?

**Comment by irvinsingGitHub** [comment]
Encountered the same error. Then realised that I misunderstood the instructions regarding the pod file.

Instructions say to paste the following code "at the end of the pod file". 

target 'ImageNotification' do
      use_frameworks! :linkage => :static
      pod 'Firebase/Messaging'
 end

But what it actually means is that you have to paste it outside of the main target block in the pod file:

target 'yourMainApp' do
  use_expo_modules!
  config = use_native_modules!

... rest of code...

end

target 'ImageNotification' do
      use_frameworks! :linkage => :static
      pod 'Firebase/Messaging'
 end


If you paste the the above target 'ImageNotification' block of code within the main target block (which is what i did initially), you will encounter build error in Xcode 'sharedApplication' is unavailable: not available on iOS.

So the solution is to ensure your pod file is configured as above. The new target block must be OUTSIDE of the main target block (i.e. 'at the end of the pod file').


Then quit Xcode. Then in the terminal, go to project folder --> cd iOS --> pod deintegrate --> then pod install.

Then open Xcode, wait for it re-index files, clean folder, clear issues, then rebuild the app.

**Comment by Santhosh-Umapathi** [comment]
The missing information was to create new Bundle Id and Provisioning profiles

Steps
1. Create Notification Image Service
2. Provide New Bundle Id and Provisioning Profiles
3. Update Podfile same as the docs, put it at the end of the file, not inside the main target
4. Clear pods and deintegrate and pod install.

**Comment by skizzo** [comment]
> The missing information was to create new Bundle Id and Provisioning profiles
> 
> Steps
> 
> 1. Create Notification Image Service
> 2. Provide New Bundle Id and Provisioning Profiles
> 3. Update Podfile same as the docs, put it at the end of the file, not inside the main target
> 4. Clear pods and deintegrate and pod install.

@Santhosh-Umapathi could you be a bit more specific what you mean by "Provide New Bundle Id and Provisioning Profiles"? Thank you!

**Comment by skizzo** [comment]
> Encountered the same error. Then realised that I misunderstood the instructions regarding the pod file.
> 
> Instructions say to paste the following code "at the end of the pod file".
> 
> target 'ImageNotification' do use_frameworks! :linkage => :static pod 'Firebase/Messaging' end
> 
> But what it actually means is that you have to paste it outside of the main target block in the pod file:
> 
> target 'yourMainApp' do use_expo_modules! config = use_native_modules!
> 
> ... rest of code...
> 
> end
> 
> target 'ImageNotification' do use_frameworks! :linkage => :static pod 'Firebase/Messaging' end
> 
> If you paste the the above target 'ImageNotification' block of code within the main target block (which is what i did initially), you will encounter build error in Xcode 'sharedApplication' is unavailable: not available on iOS.
> 
> So the solution is to ensure your pod file is configured as above. The new target block must be OUTSIDE of the main target block (i.e. 'at the end of the pod file').
> 
> Then quit Xcode. Then in the terminal, go to project folder --> cd iOS --> pod deintegrate --> then pod install.
> 
> Then open Xcode, wait for it re-index files, clean folder, clear issues, then rebuild the app.

@irvinsingGitHub  When following your advice, I get the error that "FirebaseMessaging.h" can't be found. How did you manage to resolve this? Thanks :)

**Comment by darlanhms** [comment]
> > Encountered the same error. Then realised that I misunderstood the instructions regarding the pod file.
> > Instructions say to paste the following code "at the end of the pod file".
> > target 'ImageNotification' do use_frameworks! :linkage => :static pod 'Firebase/Messaging' end
> > But what it actually means is that you have to paste it outside of the main target block in the pod file:
> > target 'yourMainApp' do use_expo_modules! config = use_native_modules!
> > ... rest of code...
> > end
> > target 'ImageNotification' do use_frameworks! :linkage => :static pod 'Firebase/Messaging' end
> > If you paste the the above target 'ImageNotification' block of code within the main target block (which is what i did initially), you will encounter build error in Xcode 'sharedApplication' is unavailable: not available on iOS.
> > So the solution is to ensure your pod file is configured as above. The new target block must be OUTSIDE of the main target block (i.e. 'at the end of the pod file').
> > Then quit Xcode. Then in the terminal, go to project folder --> cd iOS --> pod deintegrate --> then pod install.
> > Then open Xcode, wait for it re-index files, clean folder, clear issues, then rebuild the app.
> 
> @irvinsingGitHub When following your advice, I get the error that "FirebaseMessaging.h" can't be found. How did you manage to resolve this? Thanks :)

You forgot to follow [Step 2](https://rnfirebase.io/messaging/ios-notification-images#step-2---add-target-to-the-podfile) (Mainly the third line of code) and run pod-install after it

**Comment by tommyDoroGit** [comment]
I can confirm the I've ran `pod install`.  The ImageNotification.framework is attached to the Notification service extension correctly. 

<img width="560" alt="image" src="https://github.com/user-attachments/assets/0ff1c361-0bf4-4ce0-b451-d63c6af3bf8b">

All the steps outlined in the docs for IOS images has been followed and Android images are working fine when testing in Firebase.

Is there further configuration required? Maybe something missing in Signing & Capability? This is a bare React Native project  and I'm running React Native 0.74.1 & @react-native-firebase/messaging 20.4.0.

**Comment by Sotiris-Bekiaris** [comment]
Anyone made it work with Xcode version 16.0 ? My build fails after I add the target...

**Comment by sen46Sko** [comment]
@Sotiris-Bekiaris Hi, man! I have the same issue. Did you find the solution?

**Comment by Sotiris-Bekiaris** [comment]
> @Sotiris-Bekiaris Hi, man! I have the same issue. Did you find the solution?

I am focusing on other parts of my application right now, because thankfully I currently have that option, in the hopes of someone fixing this. I am planning to give another try in a few days but I am not sure if I will manage to solve it.

**Comment by sen46Sko** [comment]
@Sotiris-Bekiaris I found it! 
In my case, the problem was next
![image](https://github.com/user-attachments/assets/701162c0-9949-480b-a73a-09be40dd9551)

If you have the same, after target installation just change objectVersion in your project.pbxproj  to 60 (or to the value, that you had before target installation).
Source: https://github.com/CocoaPods/CocoaPods/issues/12671#issuecomment-2445304215

**Comment by Brightbong92** [comment]
```
// Podfile
...
  use_frameworks! :linkage => :static
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end

target 'ImageNotification' do
  use_frameworks! :linkage => :static
  pod 'Firebase/Messaging'
end
```


you should add last line

about Xcode > Sandbox : deny(1) file-write-create Error
출처: https://judekim.tistory.com/139 [MoreLean:티스토리]

**Comment by surkanfuren** [comment]
I was able to run this successfully in the simulator. However, I get this build fail when I'm trying to archive my build.

> Multiple commands produce '/Users/furkansuren/Library/Developer/Xcode/DerivedData/[project-name]-aacmaoocrgbydwexmjbvzsyqiucv/Build/Intermediates.noindex/ArchiveIntermediates/[project-name]/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities_Privacy.bundle'


![Image](https://github.com/user-attachments/assets/5906b264-aff3-4dc9-83e3-2dcf1b2a6ac0)

I've tried removing the duplicates by addin **`Run Script`** at the end of the **`Build Phases`** like this:
`# Remove duplicates in frameworks
find "${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/" -name '*.framework' -type d -exec rm -rf "{}" \;
`

And it didn't work.

Cannot archive my build right now. Please help!

**Comment by angelos3lex** [comment]
@surkanfuren 
Same problem for me, solved by: https://github.com/orgs/codemagic-ci-cd/discussions/2416

**Comment by rajesh-launchventures** [comment]
> Summary: I followed every step on [iOS Notification Images section](https://rnfirebase.io/messaging/ios-notification-images) and I still had some issues building my application, I managed to solve em' but I don't know if it is worth documenting. (It is a expo bare workflow BTW). It wasn't an error with this library itself and it is probably some annoying ios configuration, I just think it is helpful to share if someone is having the same issues.
> 
> * ### Unable to integrate the following embedded targets with their respective host targets (a host target is a "parent" target which embeds a "child" target like a framework or extension)
> 
> This issue always occurs when I put `target 'ImageNotification' do ...` at the end of the file. I solved it by putting it before the last `end` tag.
> 
> * ### Cycle inside ...; building could produce unreliable results. Cycle details: → Target '...': ExtractAppIntentsMetadata
> 
> I solved it by clicking on xcode project, **Targets** -> **Build Phases** and dragging "Embed Frameworks" above "Compile Sources"
> 
> * ### 'sharedApplication' is unavailable: not available on iOS
> 
> I solved it by pasting the following code to `Podfile`. It disables that option on every pod.
> 
> ```
>   post_install do |installer|
>     ...
>     installer.pods_project.targets.each do |target|
>       target.build_configurations.each do |config|
>         config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
>       end
>     end
>    ...
> ```
> 
> * ### [Sandbox: bash(72986) deny(1) file-write-data /Users/XXX/ios/Pods/resources-to-copy-XXXShareExtension.txt
> 
> I solved it by going to xcode project **Build Settings** and setting `User Script Sandboxing` to 'No'
> 
> I'm not experienced at writing issues, if the issue is bad written or not related just close it.

You just saved my day. <3 ❤

**Comment by re2005** [comment]
> I was able to run this successfully in the simulator. However, I get this build fail when I'm trying to archive my build.
> 
> > Multiple commands produce '/Users/furkansuren/Library/Developer/Xcode/DerivedData/[project-name]-aacmaoocrgbydwexmjbvzsyqiucv/Build/Intermediates.noindex/ArchiveIntermediates/[project-name]/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities_Privacy.bundle'
> 
> ![Image](https://github.com/user-attachments/assets/5906b264-aff3-4dc9-83e3-2dcf1b2a6ac0)
> 
> I've tried removing the duplicates by adding **`Run Script`** at the end of the **`Build Phases`** like this: `# Remove duplicates in frameworks find` `"${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/" -name '*.framework' -type d -exec rm -rf "{}" \; `
> 
> And it didn't work.
> 
> Cannot archive my build right now. Please help!

Hi @surkanfuren 

Were you able to fix this issue ?

**Comment by hungtd97** [comment]
Has anyone got this error when archiving? I fixed all of the above issues, but got this one at last.

"Build input file cannot be found: '/Users/xxx/Library/Developer/Xcode/DerivedData/ssp-gtcbiatbjntvxzewtbdaedxbnrbr/Build/Products/Debug-UAT-iphoneos/ImageNotificationUAT.appex/ImageNotificationUAT'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?"

My environment:
Xcode: 16.2
    "react-native": "0.77.3",
    "@react-native-firebase/analytics": "23.4.1",
    "@react-native-firebase/app": "23.4.1",
    "@react-native-firebase/messaging": "23.4.1",

<img width="1316" height="139" alt="Image" src="https://github.com/user-attachments/assets/60b01bb8-c235-467e-8fa0-1db429fa9f9b" />

**Comment by chanphillip** [comment]
> > I was able to run this successfully in the simulator. However, I get this build fail when I'm trying to archive my build.
> > > Multiple commands produce '/Users/furkansuren/Library/Developer/Xcode/DerivedData/[project-name]-aacmaoocrgbydwexmjbvzsyqiucv/Build/Intermediates.noindex/ArchiveIntermediates/[project-name]/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities_Privacy.bundle'
> > 
> > 
> > ![Image](https://github.com/user-attachments/assets/5906b264-aff3-4dc9-83e3-2dcf1b2a6ac0)
> > I've tried removing the duplicates by adding **`Run Script`** at the end of the **`Build Phases`** like this: `# Remove duplicates in frameworks find` `"${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/" -name '*.framework' -type d -exec rm -rf "{}" \; `
> > And it didn't work.
> > Cannot archive my build right now. Please help!
> 
> Hi [@surkanfuren](https://github.com/surkanfuren)
> 
> Were you able to fix this issue ?

Found https://github.com/invertase/react-native-firebase/issues/6268#issuecomment-1168848622 which leads to https://github.com/CocoaPods/CocoaPods/issues/8206#issuecomment-696754566

Just add `pod 'GoogleUtilities'` to all targets in `Podfile`, and I'm able to archive the build now!
