### ISSUE TITLE
[🐛] iOS devices don't receive push notification

### ISSUE THREAD

**Issue by dessorry** [invertase/react-native-firebase#7639]
## Issue
Android devices correctly receive notification. iOS devices no
![Screenshot 2024-02-21 220106](https://github.com/invertase/react-native-firebase/assets/14030210/47f69f80-c5b2-41ea-bb6c-25c549dfc84d)
I followed steps in:
https://rnfirebase.io/messaging/usage
to configure iOS notification.

![Screenshot 2024-02-21 212200](https://github.com/invertase/react-native-firebase/assets/14030210/180842df-0716-4c27-b166-97081883af20)

![Screenshot 2024-02-21 212447](https://github.com/invertase/react-native-firebase/assets/14030210/1c367716-903c-4b20-9f0c-3a8b8d2dbb3a)
![Screenshot 2024-02-21 212432](https://github.com/invertase/react-native-firebase/assets/14030210/c9b86e13-5de3-4271-83ee-715a8e9a18e9)
![Screenshot 2024-02-21 212557](https://github.com/invertase/react-native-firebase/assets/14030210/3b8be86a-1cdd-4dd7-8101-c918a2670ff2)
<img width="930" alt="Screenshot 2024-02-21 alle 21 41 29" src="https://github.com/invertase/react-native-firebase/assets/14030210/623b3901-9525-4947-9b81-a319a32470a6">
<img width="817" alt="Screenshot 2024-02-21 alle 21 42 39" src="https://github.com/invertase/react-native-firebase/assets/14030210/5ec4514e-8724-48b6-be64-caa47f1ed849">

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'LoStrego' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'
  pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'

  target 'LoStregoTests' do
    inherit! :complete
  end

  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end

target 'LoStrego-tvOS' do
  target 'LoStrego-tvOSTests' do
    inherit! :search_paths
  end
end
```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"
#import <Firebase.h>

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"LoStrego"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 1.22 GB / 7.84 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_312 - C:\Program Files\OpenJDK\openjdk-8u312-b07\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: ^6.1.0 => 6.4.0
    react: 17.0.2 => 17.0.2
    react-native: 0.66.5 => 0.66.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
    "@react-native-firebase/analytics": "^14.12.0",
    "@react-native-firebase/app": "^14.12.0",
    "@react-native-firebase/crashlytics": "^14.12.0",
    "@react-native-firebase/messaging": "^14.12.0",

- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
Y
</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
for ios to reliably receive a firebase cloud message it must contain a notification block

do your messages contain a notification block?

**Comment by dessorry** [comment]
Yes I have always chosen notification instead of in-app messages. Do you mean this?

**Comment by enesozturk** [comment]
@mikehardy I'm curious about if we really need a `notification` block in the parameters. 

In my team, we have examples in different platforms: Kotlin, Swift, and React Native. We don't have any issues receiving background messages on the `quit/background/foreground` states with the Kotlin and Swift samples. On the iOS side, my team built a [Notification Service Extension](https://github.com/WalletConnect/WalletConnectSwiftV2/blob/develop/Example/PNDecryptionService/NotificationService.swift#L7) to receive messages in the background and it's working without issues. 

Maybe some would be applied to RNF?

**Comment by mikehardy** [comment]
Hi @enesozturk - yes you really need the notification block. Apple has made a specific design decision that data-only messages (which in Apple terms are *literally* "content-available" messages, meaning "new content is available *if you want to pre-fetch it*") are simply not a priority. Specifically, developers have historically abused these messages to remotely wake up apps on user's devices which spends user device power, and Apple always takes the side of users in those situations.

So - *most* of the time - they will not wake up your app when the device receives a data-only / content-available message, in order to preserve user device power. The cases where it will wake up the app are a small combination of things involving an algorithm they do not publish but which looks at things like is the device at a low temperature? does the user interact with the app a lot? has the user interacted with the app recently? is the device plugged in or at a very high battery level? is background refresh on? is low power mode off? etc.

You may satisfy those conditions and get a delivery while testing. *but it will never be reliable - it is unreliable by design as it is meant for content pre-fetching and not considered important by Apple*

So that's that.

react-native, Swift, Kotlin, it doesn't matter what your implementation language is. This is whether the system decides to wake up your app at all, and call the message handling entry point regardless of how you implemented it.

@dessorry what I mean is, you should do messaging testing by using a script to send a request to the FCM REST API where you send specific JSON that you control to a specific device token that is for the device under test. When you do that, the JSON you send to the FCM REST API should have a notification block.

**Comment by mikehardy** [comment]
From what I understand (as maintainer on notifee.app) a notification service extension gives you a very small energy budget / timeslice where your code (the Notification Service Extension...) will execute and is able to alter the device-local notification that before it is posted. That device-local notification is generated for you by the system when you ask Firebase Cloud Messaging to send an FCM with JSON that includes a notification block.

If you do not have a notification service extension and you send an FCM with JSON that includes a notification block, the firebase-ios-sdk will not do anything special and your app will not do anything special, and any FCM that is sent with a notification block will simply post a default / unskinned device-local notification on the device. The app will not wake up and your code will not have any control flow unless and until the user interacts with the notification.

If you do have a Notification Service Extension then *however* a notification is going to be posted, your extension will get a moment to alter it before posting. Could be a notification block, could be a data-only message where you have miraculously had delivery to your app despite Apple not doing so reliably, and posted a notification in your handler, and then your Notification Service Extension runs

That's the difference between having a Notification Service Extension or not. Your focus on the "how" (implementation framework, language, whatever) is not important. You have a notification service extension or not, and it alters how your app behaves when an FCM comes in with notification in it's JSON.

If you do not send an FCM JSON with notification in it, it is data-only, and it simply may not be delivered at all. If it is, great, all the other stuff becomes more important. If it is not delivered, that's how Apple wants it.

I'm not going to speculate on framework differences and I'm not interested in diving in to other repos or collaborating.

I'm interested in people understanding that if you do not include a notification block you will have unreliable delivery on Apple period. You must internalize that or release an app and expect disappointment later as you experience unreliable delivery.

If you include a notificaiton block and you want a chance to alter them before posting, that's the Notification Service Extension pathway (possible perhaps with notifee.app)

**Comment by dessorry** [comment]
So @mikehardy you are saying that I have to use API?
The problema that I'ìm talking about is in production and is generated sending notification from here:

![Screenshot 2024-02-22 210825](https://github.com/invertase/react-native-firebase/assets/14030210/f1884a9c-ff6f-4fd2-b768-c8fc0b4b3853)

Do you suggest me to use API in order to do some test notification or because for iOS to send notification from firebase web console?
Thank you

**Comment by mikehardy** [comment]
The best way to reproducibly test FCM reception, is to use the FCM REST APIs and send JSON that you specifically craft. Otherwise, what exactly is in that JSON? Do you actually know and if so how do you know?

**Comment by dessorry** [comment]
I don't know what's in the JSON but I know that the Firebase console is how I will push notifications into production.
Do you have a guide that recommends how to use the Rest API? 
Thank you

**Comment by mikehardy** [comment]
@dessorry it's a REST API, I don't have anything special about it other than available documentation. General searches describe how to use REST APIs if needed https://search.brave.com/search?q=firebase+cloud+messaging+rest+api - I personally just have a bash shell script that uses the `curl` utility to POST a JSON to it when I do testing.

**Comment by dessorry** [comment]
I know what is a REST API, I usually use Postman to interact with them.
I meant something like:
- a json message good to be used to test iOS notification (in order to be sure that is not the message the problem)
- how (and if it is possibile) send push notification to my iOS simulator running my App
Thank you!

**Comment by mikehardy** [comment]
@dessorry you'll need the device token for your device (you can get that using react-native-firebase APIs) and you'll need to construct an FCM JSON following their docs

Here's an example I have, you *will* want to alter parts of it I'm sure but it shows basic structure - the docs are online upstream for firebase messaging


```bash
#!/bin/bash

SERVER_KEY="An API key that is authorized for your project for firebase"

curl -X POST \
--header "Authorization: key=$SERVER_KEY"  \
--Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"token\":\"YOUR DEVICE TOKEN HERE\",\"collapse_key\": \"AppInfo\",\"content_available\": true, \"priority\": \"high\", \"data\":{\"IconCheck\":\"Testing Icon\"}}"

```

I haven't actually tested this in forever personally and that's for the old REST API but it's a rough idea - just needs reshaping to match current endpoint https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send
