### ISSUE TITLE
🔥 [🐛] setConsent() not working

### ISSUE THREAD

**Issue by maurispalletti** [invertase/react-native-firebase#7645]
## Issue

analytics().setConsent(params); is throwing the following error:
```
TypeError: this.native.setConsent is not a function (it is undefined)
```

The import and usage of setConsent() were made following the documentation. It is:
I'm using @react-native-firebase/analytics v18.9.0.

```
import analytics from '@react-native-firebase/analytics';
...
let params = {
    analytics_storage: true,
    ad_storage: true,
    ad_user_data: true,
    ad_personalization: true,
};
...
await analytics().setConsent(params);
```

Going further and logging what this.native includes ([in this line](https://github.com/invertase/react-native-firebase/blob/3c0dc54854aaf0bb7194ec7073f84dcc11345a1b/packages/analytics/lib/index.js#L282)), I get:
```
 LOG  {"getAppInstanceId": [Function anonymous], "getConstants": [Function anonymous], "initiateOnDeviceConversionMeasurementWithEmailAddress": [Function anonymous], "logEvent": [Function anonymous], "resetAnalyticsData": [Function anonymous], "setAnalyticsCollectionEnabled": [Function anonymous], "setDefaultEventParameters": [Function anonymous], "setSessionTimeoutDuration": [Function anonymous], "setUserId": [Function anonymous], "setUserProperties": [Function anonymous], "setUserProperty": [Function anonymous]}
```
Where "setConsent" is not included.

---

## Project Files
https://github.com/invertase/react-native-firebase/blob/3c0dc54854aaf0bb7194ec7073f84dcc11345a1b/packages/analytics/lib/index.js#L282

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1 Pro
  Memory: 137.45 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn:
    version: 3.2.0
    path: ~/.nvm/versions/node/v18.19.0/bin/yarn
  npm:
    version: 10.4.0
    path: ~/.nvm/versions/node/v18.19.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.2
    path: /Users/mauriciospalletti/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.21
    path: /usr/bin/javac
  Ruby:
    version: 2.7.4
    path: /Users/mauriciospalletti/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `18.9.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `analytics`
- **Are you using `TypeScript`?**
  - `Y` & `Version 5.1.5`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by pehagg** [comment]
@maurispalletti , I had the same issue, but was able to resolve it by doing a clean build from Xcode.

**Comment by mikehardy** [comment]
This is a project-local build issue as pehagg says, you have up to date javascript and out of date native code
If you install a new version of react-native-firebase and you do not correctly build the new native code that matches the new javascript code this will happen but unfortunately there is nothing we (in this repo) can do, you have to sort out your local build system
