### ISSUE TITLE
[🐛] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":

### ISSUE THREAD

**Issue by dr-zr** [invertase/react-native-firebase#7658]
## Issue

After upgrading to the latest version of `react-native-firebase` (`v19`) I'm unable to create local expo `ios`. The error I receive is:

```sh
CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
```

I'm using a managed Expo workflow and have the latest Expo version installed (`50.0.8`). 
I've installed cocoapods via brew and done `brew update cocoapods` after the 1st time I received this error, but that didn't solve the issue. 
I'm using version `1.15.2` of cocoapods on my Macbook

**Comment by mikehardy** [comment]
Hi there! You have deleted the issue template, so I don't have any solid information to go on

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

As a brief guess, you might try `pod repo update`

**Comment by mikehardy** [comment]
I've been doing this for a while now, and this one still gets me from time to time. If software development were easy, everyone would do it. Good luck with your project
