### ISSUE TITLE
[🐛] setBackgroundMessageHandler not working in iOS 17.3.1?

### ISSUE THREAD

**Issue by frankA10019** [invertase/react-native-firebase#7659]
## Issue

My iOS app work well when receive the notification in foreground and background before. But recently my iOS setBackgroundMessageHandler didn't trigger when I receive the notification in background(notification show well only handler doesn't trigger). I am not sure is this the issue only in iOS 17.3.1, because my iPhone update iOS automatically. I checked the payload in notification, there has 
apns: { payload: { aps: { "content-available": true, }, } } }). 
Is "content-available" right ?  I saw "content_available", "contentAvailable" in some forum article. and some say set value to 1. "content-available": true works for me before so I kept this setting.

Any solution for this issue ? Any suggestion is appreciated.

By the way, Android app works well in foreground and background when receive notification.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 18.3.0
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - Y 5.3.2

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by frankA10019** [comment]
For those who facing the same issue.  Please reboot your iPhone. After reboot my device, notification works perfect.

**Comment by mikehardy** [comment]
Your notifications will never be delivered reliably if you use data-only notifications.

This is an Apple design decision to save user battery power from app developers they consider as recklessly spending user's phone battery by waking up their apps all the time in the background.

So this will probably happen to you again - where it looks like it's not working.

The only way to achieve reliable delivery on the iOS platform is to include a notification block in your messages.

**Comment by akshay-engage** [comment]
@mikehardy 

below is the payload i am using, Where I am sending notification which should render the notification and trigger the setBackgroundMessageHandler.

But, In my case it is only rendering notification in background and killed state, issue is only with iOS (background and killed)

I see many other open issues arround github and stackoverflow. I could not get any satisfactory response so far
```{
  "to": "TOKEN,

  "notification": {
    "title": "Notification Title",
    "body": "Notification Body"
  }
}
```

**Comment by frankA10019** [comment]
@mikehardy I used the notification block already, this issue(setBackgroundMessageHandler doesn't trigger) happen again. Could you please open this issue and help again? Thanks.

@akshay-engage  any update?
