### ISSUE TITLE
[🐛⚠️] iOS Build Fails - Value of optional type '?' must be unwrapped to refer to member 'storage' of wrapped base type 'any StorageProvider' (Optional Chaining)

### ISSUE THREAD

**Issue by VictorioMolina** [invertase/react-native-firebase#7666]
## Scenario

Last week I was able to compile my project (Expo EAS Build) without errors.

Today, without modifying anything (didn't upgrade any dependency), I have started getting this error on my iOS AdHoc compilation:

## Run Fastlane Errors

```
Copying   @react-native-firebase/storage ../../../Users/expo/Library/Developer/Xcode/DerivedData/Advice-dzlzwedukqkcvxgkbpzvxdpjkyli/Build/Intermediates.noindex/ArchiveIntermediates/Advice/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/FirebaseStorage.framework/Headers/FirebaseStorage-umbrella.h ➜ ios/Pods/Target/ Support/ Files/FirebaseStorage/FirebaseStorage-umbrella.h

› Copying   @react-native-firebase/storage ../../../Users/expo/Library/Developer/Xcode/DerivedData/Advice-dzlzwedukqkcvxgkbpzvxdpjkyli/Build/Intermediates.noindex/ArchiveIntermediates/Advice/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/FirebaseStorage.framework/Headers/FIRStorageTypedefs.h ➜ ios/Pods/FirebaseStorage/FirebaseStorage/Typedefs/FIRStorageTypedefs.h

❌  (/Users/expo/workingdir/build/packages/app/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:73:12)

  71 |     let provider = ComponentType<StorageProvider>.instance(for: StorageProvider.self,
  72 |                                                            in: app.container)
> 73 |     return provider.storage(for: Storage.bucket(for: app))
     |            ^ value of optional type '?' must be unwrapped to refer to member 'storage' of wrapped base type 'any StorageProvider'
  74 |   }
  75 | 
  76 |   /**

❌  (/Users/expo/workingdir/build/packages/app/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:88:12)

  86 |     let provider = ComponentType<StorageProvider>.instance(for: StorageProvider.self,
  87 |                                                            in: app.container)
> 88 |     return provider.storage(for: Storage.bucket(for: app, urlString: url))
     |            ^ value of optional type '?' must be unwrapped to refer to member 'storage' of wrapped base type 'any StorageProvider'
  89 |   }
  90 | 
  91 |   /**

❌  (/Users/expo/workingdir/build/packages/app/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:291:39)

  289 |   init(app: FirebaseApp, bucket: String) {
  290 |     self.app = app
> 291 |     auth = ComponentType<AuthInterop>.instance(for: AuthInterop.self,
      |                                       ^ cannot assign value of type '?' to type 'any AuthInterop'
  292 |                                                in: app.container)
  293 |     appCheck = ComponentType<AppCheckInterop>.instance(for: AppCheckInterop.self,
  294 |                                                        in: app.container)

❌  (/Users/expo/workingdir/build/packages/app/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:293:47)

  291 |     auth = ComponentType<AuthInterop>.instance(for: AuthInterop.self,
  292 |                                                in: app.container)
> 293 |     appCheck = ComponentType<AppCheckInterop>.instance(for: AppCheckInterop.self,
      |                                               ^ cannot assign value of type '?' to type 'any AppCheckInterop'
  294 |                                                        in: app.container)
  295 |     storageBucket = bucket
  296 |     host = "firebasestorage.googleapis.com"
```

## Package Versions

Since I was using the following dependencies

```
    "@react-native-firebase/analytics": "^18.7.3",
    "@react-native-firebase/app": "^18.7.3",
    "@react-native-firebase/auth": "^18.7.3",
    "@react-native-firebase/firestore": "^18.7.3",
    "@react-native-firebase/functions": "^18.7.3",
    "@react-native-firebase/storage": "^18.7.3",
```

I decided to upgrade to the latest one `@^19.0.0`.

```
    "@react-native-firebase/analytics": "^19.0.0",
    "@react-native-firebase/app": "^19.0.0",
    "@react-native-firebase/auth": "^19.0.0",
    "@react-native-firebase/firestore": "^19.0.0",
    "@react-native-firebase/functions": "^19.0.0",
    "@react-native-firebase/storage": "^19.0.0",
```

I have also tried upgrading EAS with Expo 48, 49 and the latest release and images, with CocoaPods v1.15.2, and the error still persists.

Is anyone experiencing the same issue?

**Comment by geoffcfchen** [comment]
Yes. I just got the same issue here. I am using expo 49 SDK. The following is a part of my package.json.

  "dependencies": {
    "@react-native-firebase/app": "^18.4.0",
    "@react-native-firebase/auth": "^18.4.0",
    "@react-native-firebase/firestore": "^18.4.0",
    "@react-native-firebase/storage": "^18.4.0",
    "expo": "~49.0.10",
    "react": "18.2.0",
    "react-native": "^0.72.6",
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

**Comment by VictorioMolina** [comment]
Yep, it’s a minimal issue with nils handling. Hope it’s fixed soon 🥺 I downgraded the package to but nothing. Did you try @17.5.0? @geoffcfchen 

Starting to think the issue itself is in the latest Google Firebase package and not directly in this wrapper for React Native (?).

**Comment by VictorioMolina** [comment]
Yep, seems an issue in Firebase iOS sdk https://github.com/firebase/firebase-ios-sdk/pull/12391

**Comment by geoffcfchen** [comment]
@VictorioMolina could you share how you solve this issue? Thanks!

**Comment by geoffcfchen** [comment]
> 17.5.0

No I did not try 17.5.0...

**Comment by VictorioMolina** [comment]
@geoffcfchen I am trying to implement an expo config plugin to update this field in @react-native-firebase/app's package.json:

```json
"sdkVersions": {
    "ios": {
      "firebase": "10.21.0", <----- https://github.com/firebase/firebase-ios-sdk/commit/2e7ff6a892f868c46665febb8708e5b4708c347b
      "iosTarget": "11.0",
      "macosTarget": "10.13"
    },
    "android": {
      "minSdk": 19,
      "targetSdk": 33,
      "compileSdk": 33,
      "firebase": "32.7.2",
      "firebaseCrashlyticsGradle": "2.9.9",
      "firebasePerfGradle": "1.4.2",
      "gmsGoogleServicesGradle": "4.4.1",
      "playServicesAuth": "20.7.0"
    }
  },
```

I am not an expert with expo plugins, and not really sure if this approach will work with EAS. Have a try.

```
const fs = require("fs");
const path = require("path");
const { withDangerousMod } = require("expo/config-plugins");

/**
 * Modifier plugin to update the sdkVersions.ios.firebase field in
 * `@react-native-firebase/app package`.
 *
 * @param {import("expo/config").ExpoConfig} expoConfig - Current Expo config.
 * @returns {import("expo/config").ExpoConfig} Modified Expo config.
 */
const withFirebaseSdkVersionUpdate = (expoConfig) => {
  return withDangerousMod(expoConfig, [
    "ios",
    (modConfig) => {
      const filePath = path.resolve(
        modConfig.modRequest.projectRoot,
        "node_modules/@react-native-firebase/app/package.json"
      );

      const packageJson = JSON.parse(fs.readFileSync(filePath, "utf-8"));

      if (packageJson.sdkVersions?.ios) {
        packageJson.sdkVersions.ios.firebase = "10.23.0";

        const newContent = JSON.stringify(packageJson, null, 2);

        fs.writeFileSync(filePath, newContent);

        console.log("Updated sdkVersions.ios.firebase to 10.23.0");
      }

      return modConfig;
    },
  ]);
};

module.exports = withFirebaseSdkVersionUpdate;

```

In the EAS prebuild, I am getting the error:

Error: [ios.dangerous]: withIosDangerousBaseMod: ENOENT: no such file or directory, open '/Users/expo/workingdir/build/packages/app/node_modules/@react-native-firebase/app/package.json'

**Comment by geoffcfchen** [comment]
Thanks for sharing the information. It seems to me that this problem is still not resolved. It was fine last week but now it can't work, so I think that there are some changes under the hood. I hope some one can point us in a direction...

**Comment by VictorioMolina** [comment]
@geoffcfchen take a look at this commit https://github.com/firebase/firebase-ios-sdk/pull/12391/commits/72449ec4506d8f966fd840f551906e3ea231d59b

**Comment by geoffcfchen** [comment]
I see. 

Since I am working on the expo project, I only have 

    "@react-native-firebase/app": "18.9.0",
    "@react-native-firebase/auth": "18.9.0",
    "@react-native-firebase/firestore": "18.9.0",
    "@react-native-firebase/storage": "18.9.0",
    
    in my package.json
    
    and the following plugins
    
        "plugins": [
      "expo-apple-authentication",
      "@react-native-firebase/app",
      "@react-native-firebase/auth",
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }
      ],

in app.json.

But I think that we encountered the same issue. I don't think that we are the only one. Who use the EAS build recently should also encountered the same issue...

**Comment by VictorioMolina** [comment]
@geoffcfchen It’s correct, it seems impossible to build with expo in the current state. Ignore the custom config plug-in I was implementing, it’s not working and looks like a hack which could lead to extra problems… definitively, not a good solution, I am deleting it.

We will need to wait for the package maintainers.

**Comment by geoffcfchen** [comment]
Someone mentioned a solution

https://stackoverflow.com/questions/78027770/upgrading-to-expo-50-can%C2%B4t-build-ios

But it requires ejecting from Expo...

**Comment by geoffcfchen** [comment]
Maybe a related post

https://github.com/firebase/flutterfire/issues/12429

**Comment by aslihanturkdonmez** [comment]
I don't  using expo, i use cli and the error occurs there too

**Comment by VictorioMolina** [comment]
@geoffcfchen yep, it’s the same issue. Also, the solution is just to upgrade the firebase iOS sdk version, but, as I mentioned before, I feel it’s not the best approach to touch the Podfile with an expo plugin. It’s better to wait for the maintainers of react-native-firebase.

**Comment by AleshkovDenis** [comment]
any updates?

**Comment by vladi-klmv** [comment]
any updates?

**Comment by VictorioMolina** [comment]
@AleshkovDenis @vladi-klmv I submitted a pull request to fix the issue. Pls, check it out and if you think something is missing, update it :) or create a patch package. This issue is strongly retaining us.

**Comment by AleshkovDenis** [comment]
@VictorioMolina
Did you try build your app with patched package changes?

**Comment by VictorioMolina** [comment]
@AleshkovDenis Nop, I didn't, just prefer to wait for any updates on this repo. But if you do, let us know if the sdk version upgrade fixes the issue.

**Comment by cwackerfuss** [comment]
@VictorioMolina and @AleshkovDenis - the sdk version upgrade does fix the issue with a patched package. If anyone would like to use this solution in the meantime, it's very straightforward with a tool like [patch-package](https://www.npmjs.com/package/patch-package), or if you use yarn v2+ or pnpm, those have built-in support for package patching.

Here's how I did it on Yarn v2+ (I use 4.0.2):
- Run `yarn patch @react-native-firebase/app`
- Navigate to the folder location output by the yarn patch command
- Update package.json L76 to `"firebase": "10.22.0",` and save
- Apply the patch using the command output by the yarn patch command
- Rebuild

**Comment by AleshkovDenis** [comment]
@cwackerfuss
Can you write the path to the file that needs to be changed?
Or show a successful diff?

**Comment by VictorioMolina** [comment]
@AleshkovDenis check the changed files in the pull request. https://github.com/invertase/react-native-firebase/pull/7668

**Comment by geoffcfchen** [comment]
> @cwackerfuss Can you write the path to the file that needs to be changed? Or show a successful diff?

node_modules/@react-native-firebase/app/package.json

**Comment by ishikaj12** [comment]
Hi, I'm running into the same Fastlane issues with Firebase Storage. I tried to do the patch-package command (yarn patch-package @react-native-firebase/app) but got this message:

patch-package 8.0.0
• Creating temporary folder
• Installing @react-native-firebase/app@18.7.3 with yarn
• Diffing your files with clean files
⁉️  Not creating patch file for package '@react-native-firebase/app'
⁉️  There don't appear to be any changes.
error Command failed with exit code 1.

Does anyone know what to do in this case? Thank you!

**Comment by geoffcfchen** [comment]
> Hi, I'm running into the same Fastlane issues with Firebase Storage. I tried to do the patch-package command (yarn patch-package @react-native-firebase/app) but got this message:
> 
> patch-package 8.0.0 • Creating temporary folder • Installing @react-native-firebase/app@18.7.3 with yarn • Diffing your files with clean files ⁉️ Not creating patch file for package '@react-native-firebase/app' ⁉️ There don't appear to be any changes. error Command failed with exit code 1.
> 
> Does anyone know what to do in this case? Thank you!

yarn patch-package @react-native-firebase/app --exclude

**Comment by geoffcfchen** [comment]
For those who need to fix it right now before the official updates, you can do 

1. **Install patch-package and postinstall-postinstall if you haven't already**
npm install patch-package postinstall-postinstall --save-dev

2. **Edit the node_modules/@react-native-firebase/app/package.json to change the Firebase version to 10.22.0.**
"sdkVersions": {
    "ios": {
      "firebase": "10.22.0",
3. **Include --exclude when creating a patch file in a patches/ directory** 
npx patch-package  @react-native-firebase/app --exclude
4. **Modify your package.json to include the postinstall script** 
"scripts": {
  "postinstall": "patch-package"
}
5. **Rebuild your project** 
such as eas build --profile development --platform ios

**Comment by GibbyBox** [comment]
A workaround I'm using it to pin the related pods via a config plugin. It does require knowing what pods to pin and at what versions

```

[ "expo-build-properties", { 
	"ios": {
		"useFrameworks": "static",
		"extraPods": [
			{ "name": "FirebaseAppCheckInterop", "version": "= 10.21.0" },
			{ "name": "FirebaseAuthInterop", "version": "= 10.21.0" },
			{ "name": "FirebaseCoreExtension", "version": "= 10.21.0" },
			{ "name": "FirebaseCoreInternal", "version": "= 10.21.0" },
			{ "name": "FirebaseFirestoreInternal", "version": "= 10.21.0" },
			{ "name": "FirebaseInstallations", "version": "= 10.21.0" },
			{ "name": "FirebaseMessagingInterop", "version": "= 10.21.0" },
			{ "name": "FirebaseSharedSwift", "version": "= 10.21.0" },
			{ "name": "GoogleUtilities", "version": "= 7.12.0" },
			{ "name": "PromisesObjC", "version": "= 2.3.1" },
			{ "name": "leveldb-library", "version": "= 1.22.3" }
		]
	}
}]
```

**Comment by GibbyBox** [comment]
With what I encountered it was 10.22.0 giving me these issues.

**Comment by VictorioMolina** [comment]
@GibbyBox  The issue got solved here: https://github.com/firebase/firebase-ios-sdk/commit/1ed6d66b2010539bf21abf66b942dcf89384bd75

Currently, react-native-firebase wraps firebase-ios-sdk v10.21.0 https://github.com/invertase/react-native-firebase/blob/main/packages/app/package.json

Could you please re-check? Is it compiling correctly with the extra pods solution? No crashes while testing the app?

**Comment by GibbyBox** [comment]
@VictorioMolina I'm positive. The pods I rolled back to are what's being used in my production app currently.

**Comment by GibbyBox** [comment]
In that flutterfire issue you linked, there is this https://github.com/firebase/flutterfire/issues/12429#issuecomment-1978209797
> After investigation, it seems that some internal libraries in the native iOS SDK are not strongly linked to a version. When the iOS team released 10.22.0 yesterday some dependencies got upgraded without the main package.

@VictorioMolina Can you double check what version of the pods are installed in your failing builds, specifically if there is a mismatch in FirebaseCoreExtension, FirebaseCore, and FirebaseStorage?

What's likely happening on EAS for us is that FirebaseCoreExtension is on the 10.22.0. The interface defined in it indicate that the provider is nullable, but then the implementations in FirebaseCore and FirebaseStorage are on the 10.21.0 where it's missing the change to handle it being nullable.

Having all of them on the same version is the solution. Your PR should do that.

**Comment by VictorioMolina** [comment]
@GibbyBox Thank you for your workaround!! Could you please share the final state of the extra pods? AFAIK, the problem with nils is in the storage package.

**Comment by womj** [comment]
```
target 'sociablesui' do
  config = use_native_modules!

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  pod 'RNFBStorage', :path => '../node_modules/@react-native-firebase/storage'
  $FirebaseSDKVersion = '10.22.0'
```
  In your podfile works
  
  Specify the new version of firebase sdk 10.22.0

**Comment by mikehardy** [comment]
Hi there! 👋  Sorry for the delayed response here. I'm qualifying the firebase-ios-sdk 10.22.0 right now for release, but I was under the impression you can easily override the firebase-ios-sdk version as documented here:

https://rnfirebase.io/#ios

...and as mentioned @womj here https://github.com/invertase/react-native-firebase/issues/7666#issuecomment-1980083859 ?

Is there some reason that doesn't work for expo folks to get people moving?

Someone else mentioned that there is a mix of 10.21.0 and 10.22.0 pods coming down when you specify "10.21.0" as the Firebase version, that's because some of the pods are brought in as transitive dependencies and their semver requirement for the transitive dependency allows cocoapods to resolve higher minor version numbers. This is normal, and should not cause problems.

**Comment by geoffcfchen** [comment]
> Hi there! 👋 Sorry for the delayed response here. I'm qualifying the firebase-ios-sdk 10.22.0 right now for release, but I was under the impression you can easily override the firebase-ios-sdk version as documented here:
> 
> https://rnfirebase.io/#ios
> 
> ...and as mentioned @womj here [#7666 (comment)](https://github.com/invertase/react-native-firebase/issues/7666#issuecomment-1980083859) ?
> 
> Is there some reason that doesn't work for expo folks to get people moving?
> 
> Someone else mentioned that there is a mix of 10.21.0 and 10.22.0 pods coming down when you specify "10.21.0" as the Firebase version, that's because some of the pods are brought in as transitive dependencies and their semver requirement for the transitive dependency allows cocoapods to resolve higher minor version numbers. This is normal, and should not cause problems.

I think that for those who use Expo's managed workflow, direct access to iOS and Android native project files is abstracted away, meaning they don't modify the Podfile or any native code directly. This limits the ability to specify or override the Firebase iOS SDK version. In any case, thank you @mikehardy @VictorioMolina for solving this issue.

**Comment by mikehardy** [comment]
@geoffcfchen I see - I do understand that, I guess I assumed (incorrectly) there would be some sort of Expo plugin somewhere that was fairly standard where you could express the idea "Hey, just add this one raw line to the Podfile at the top" 🤷 

Either way, yes, react-native-firebase 19.0.1 is out with @VictorioMolina's PR bumping us to firebase-ios-sdk 10.22.0 in place and it handles the new Xcode's "we issue breaking changes in minor version all the time, enjoy" version update

**Comment by artem-alek** [comment]
I am still having this issue in April. Just ran into it. Has there been any updates or movement on this? I am about to try the patch package but I dont want to do that...

 "@react-native-firebase/app": "^18.9.0",
  "@react-native-firebase/auth": "^18.9.0",
  "@react-native-firebase/firestore": "^18.9.0",
  "@react-native-firebase/storage": "^18.9.0",
  "expo": "~50.0.17",

**Comment by artem-alek** [comment]
> I am still having this issue in April. Just ran into it. Has there been any updates or movement on this? I am about to try the patch package but I dont want to do that...
> 
> "@react-native-firebase/app": "^18.9.0", "@react-native-firebase/auth": "^18.9.0", "@react-native-firebase/firestore": "^18.9.0", "@react-native-firebase/storage": "^18.9.0", "expo": "~50.0.17",

Looks like I resolved this with getting the latest version of react-native-firebase version 19.2.2

**Comment by vedjuno236** [comment]
Swift Compiler Error (Xcode): Value of optional type '(any StorageProvider)?' must be unwrapped to refer to member
'storage' of wrapped base type 'any StorageProvider'
/Users/kouved/Booking/User/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:72:11


Swift Compiler Error (Xcode): Value of optional type '(any StorageProvider)?' must be unwrapped to refer to member
'storage' of wrapped base type 'any StorageProvider'
/Users/kouved/Booking/User/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:87:11


Swift Compiler Error (Xcode): Cannot assign value of type '(any AuthInterop)?' to type 'any AuthInterop'
/Users/kouved/Booking/User/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:290:38


Swift Compiler Error (Xcode): Cannot assign value of type '(any AppCheckInterop)?' to type 'any AppCheckInterop'
/Users/kouved/Booking/User/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:292:46


Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code


Could not build the application for the simulator.
Error launching application on iPhone 15.

**Comment by james-zedd4** [comment]
I ran into the same issue -- [Value of optional type '?' must be unwrapped to refer to member 'storage' of wrapped base type 'any StorageProvider' ...

I can confirm that updating my version of the firestore apps (18.3.0 -> 20.4.0) fixed the build issue.

Also I am updating my Expo SDK version from 49 -> 51.
