### ISSUE TITLE
FCM getToken always returning null and no notifications are received on Android

### ISSUE THREAD

**Issue by victorsferreira** [invertase/react-native-firebase#767]
"react": "16.2.0",
"react-native": "^0.52.0",
"react-native-firebase": "^3.2.2",
Platform: Android

I'm developing this app that will receive notifications from Firebase. After one week of development I stoped receiving new notifications. So I started debugging and I realized that the token it gets is always null now. Notifications are not received anymore.

The anonymous signin is alright, I get an UID but no token and no messages from Firebase.

Anyone knows what could be happening?

    firebase.auth().signInAnonymously()
    .then((signin) => {
        //signin is alright
        fcm.getToken()
        .then(token => {
            //token is null. Nothings happens after that
        });
    });

**Comment by Salakar** [comment]
`fcm.getToken()` -> what is this and where is it coming from? Could you provide full example of code, thanks.

**Comment by AmirTahani** [comment]
i have exactly the same problem

**Comment by chrisbianca** [comment]
We need more information to be able to help with this further.  Please re-open with the information requested.

**Comment by Heru6664** [comment]
is there any solution? i have same problem here

**Comment by Johny8811** [comment]
Some news? I have a same problem, *firebase.messaging().getToken()* still return null if I have permissions or not
