### ISSUE TITLE
🔥 [🐛] Sudden IOS build failures on expo that previously had worked

### ISSUE THREAD

**Issue by GibbyBox** [invertase/react-native-firebase#7670]
## Issue

I've been using firebase in a production app with expo. I've encountered build issues. In my attempts to determine which of my changes caused the build issue, I built the last known snapshot of the codebase that built successfully and encountered the same issue.

Examining the logs, the only change I can find were minor upgrades to related firebase pods. Using expo-build-properties, I pinned these pods to the version that was in the last successful build and it worked fine.

### The exact fastlane error

<details><summary>Click To Expand</summary>
<p>

```
❌  (ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:73:12)

  71 |     let provider = ComponentType<StorageProvider>.instance(for: StorageProvider.self,
  72 |                                                            in: app.container)
> 73 |     return provider.storage(for: Storage.bucket(for: app))
     |            ^ value of optional type '?' must be unwrapped to refer to member 'storage' of wrapped base type 'any StorageProvider'
  74 |   }
  75 | 
  76 |   /**

❌  (ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:88:12)

  86 |     let provider = ComponentType<StorageProvider>.instance(for: StorageProvider.self,
  87 |                                                            in: app.container)
> 88 |     return provider.storage(for: Storage.bucket(for: app, urlString: url))
     |            ^ value of optional type '?' must be unwrapped to refer to member 'storage' of wrapped base type 'any StorageProvider'
  89 |   }
  90 | 
  91 |   /**

❌  (ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:291:39)

  289 |   init(app: FirebaseApp, bucket: String) {
  290 |     self.app = app
> 291 |     auth = ComponentType<AuthInterop>.instance(for: AuthInterop.self,
      |                                       ^ cannot assign value of type '?' to type 'any AuthInterop'
  292 |                                                in: app.container)
  293 |     appCheck = ComponentType<AppCheckInterop>.instance(for: AppCheckInterop.self,
  294 |                                                        in: app.container)

❌  (ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:293:47)

  291 |     auth = ComponentType<AuthInterop>.instance(for: AuthInterop.self,
  292 |                                                in: app.container)
> 293 |     appCheck = ComponentType<AppCheckInterop>.instance(for: AppCheckInterop.self,
      |                                               ^ cannot assign value of type '?' to type 'any AppCheckInterop'
  294 |                                                        in: app.container)
  295 |     storageBucket = bucket
  296 |     host = "firebasestorage.googleapis.com"
```

</p>
</details>

### Pods version changes detected

|Pod|Working|Failed|
|--|--|--|
|FirebaseAppCheckInterop|10.21.0|10.22.0|
|FirebaseAuthInterop|10.21.0|10.22.0|
|FirebaseCoreExtension|10.21.0|10.22.0|
|FirebaseCoreInternal|10.21.0|10.22.0|
|FirebaseFirestoreInternal|10.21.0|10.22.0|
|FirebaseInstallations|10.21.0|10.22.0|
|FirebaseMessagingInterop|10.21.0|10.22.0|
|FirebaseSharedSwift|10.21.0|10.22.0|
|GoogleUtilities|7.12.0|7.13.0|
|PromisesObjC|2.3.1|2.4.0|
|leveldb-library|1.22.3|1.22.4|

### My Workaround

I decided to pin these pods to the working versions in the podfile that expo produces.
The config plugin looks like this. **There might need to be more depending on what other firebase modules are being used.**

```
[ "expo-build-properties", { 
	"ios": {
		"useFrameworks": "static",
		"extraPods": [
			{ "name": "FirebaseAppCheckInterop", "version": "= 10.21.0" },
			{ "name": "FirebaseAuthInterop", "version": "= 10.21.0" },
			{ "name": "FirebaseCoreExtension", "version": "= 10.21.0" },
			{ "name": "FirebaseCoreInternal", "version": "= 10.21.0" },
			{ "name": "FirebaseFirestoreInternal", "version": "= 10.21.0" },
			{ "name": "FirebaseInstallations", "version": "= 10.21.0" },
			{ "name": "FirebaseMessagingInterop", "version": "= 10.21.0" },
			{ "name": "FirebaseSharedSwift", "version": "= 10.21.0" },
			{ "name": "GoogleUtilities", "version": "= 7.12.0" },
			{ "name": "PromisesObjC", "version": "= 2.3.1" },
			{ "name": "leveldb-library", "version": "= 1.22.3" }
		]
	}
}]
```

---

## Project Files

Would you take a repro instead?
https://github.com/GibbyBox/repro-firebase-pods-issue-3-5-2024

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

Since this is the EAS CI, I don't have this output available. I do have what's reported to be installed on the box though (logged in the "Spin up build environment" step).

```
Creating new worker instance
M1, 2 cores, 8 GB RAM

Using VM template "macos-ventura-13.6-xcode-15.2" running macOS Ventura 13.6

Installed software:
- Xcode 15.2 (15C500b)
- Node.js 18.18.0
- Bun 1.0.23
- Yarn 1.22.21
- pnpm 8.14.1
- npm 9.8.1
- fastlane 2.219.0
- CocoaPods 1.14.3
- Ruby 2.7
- node-gyp 10.0.1
No `image` was explicitly specified. Resolved builder image to 'macos-ventura-13.6-xcode-15.2'.
- Expo CLI 6.3.10
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 19.0.0
- **`Firebase` module(s) you're using that has the issue:**
  - app
  - app-check
  - database
  - firestore
  - functions
  - storage
- **Are you using `TypeScript`?**
  - Yes for my production app. No for the provided repro.

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by geoffcfchen** [comment]
Maybe this is the same issue 

https://github.com/invertase/react-native-firebase/issues/7666

**Comment by GibbyBox** [comment]
I missed this entire discussion. Yes this is the same issue

**Comment by GibbyBox** [comment]
Closing in favor of that ticket
