### ISSUE TITLE
big Image in Remote notification

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [invertase/react-native-firebase#768]
**#**How can I display notifications with an image sent from console side?****

![pushnotifyresult3](https://user-images.githubusercontent.com/6310631/35181042-97e728cc-fde0-11e7-8160-0176df73d571.gif)

1. Application Target Platform: 26
2. Development Operating System: windows 
3. React Native version: 0.50
4. RNFirebase Version: 3.2.2
6. Firebase Module: messeging

**Comment by Ehesp** [comment]
This isn't currently possible - https://github.com/invertase/react-native-firebase/issues/595
