### ISSUE TITLE
[🐛] receive notification but setBackgroundMessageHandler not working

### ISSUE THREAD

**Issue by frankA10019** [invertase/react-native-firebase#7681]
My iOS app work well when receive the notification in foreground and background before. But recently my iOS setBackgroundMessageHandler didn't trigger when I receive the notification in background(notification show well only handler doesn't trigger). I am not sure is this the issue only in iOS 17.3.1, because my iPhone update iOS automatically. I checked the payload in notification, there has
apns: { payload: { aps: { "content-available": true, }, } } }).
Is "content-available" right ? I saw "content_available", "contentAvailable" in some forum article. and some say set value to 1. "content-available": true works for me before so I kept this setting.

Already use notification block, still nothing change
Any solution for this issue ? Any suggestion is appreciated.

## Issue

Describe your issue here

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ahmad-AbdElKader** [comment]
How did you solve this, I'm facing the same issue

**Comment by sajin1010** [comment]
@frankA10019  Facing the same issue: it was working fine in iOS 16.7, but in iOS 17.5.1, the background event handler is not triggering. How did you solve this?

**Comment by sajin1010** [comment]
@frankA10019 facing same issue , can you plz share the fix you have done.
