### ISSUE TITLE
not showing notifications on ios device but in backend onmessaging function returning the notification message

### ISSUE THREAD

**Issue by sukumardv3101** [invertase/react-native-firebase#769]
here is the code snippet.

import firebase from 'react-native-firebase';

const notif = firebase.messaging();

componentDidMount () {
    notif.requestPermissions();

     notif.getToken()
        .then(res => {
           console.log(res); // returing device token
        })
        .catch( err => {
          console.log(err)
        })

    if(!firebase.database().app._initialized){
           const App = firebase.initializeApp(iosConfig,'App');
           firebase.app('App').auth().signInAnonymously().then((user) => {
               console.log(user);
           }).catch(err=>console.log(err)); 
    }
}

**Comment by Ehesp** [comment]
Please follow the issue template.
