### ISSUE TITLE
[🐛] auth().signInWithEmailAndPassword(email, password) returns auth/invalid-login instead of auth/wrong-password

### ISSUE THREAD

**Issue by DavideViolante** [invertase/react-native-firebase#7696]
## Issue

```ts
auth().signInWithEmailAndPassword(email, password)
  .catch((error) => {
    if (error.code === "auth/wrong-password") {...}
    // error.code was "auth/wrong-password", now it's "auth/invalid-login".
```
I noticed this error because it was not going into the if anymore.
I can't find anywhere this breaking change or auth/invalid-login error in particular.
Ref: https://firebase.google.com/docs/auth/admin/errors

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
    "@react-native-firebase/app": "^18.6.1",
    "@react-native-firebase/auth": "^18.6.1",
    "@react-native-firebase/crashlytics": "^18.6.1",
    "@react-native-firebase/firestore": "^18.6.1",
    "@react-native-firebase/functions": "^18.6.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-intl": "^6.6.1",
    "react-native": "0.72.0",
    
```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 24
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "25.1.8937393"
        androidXCore = "1.8.0"
        googlePlayServicesVersion = "17.0.0"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        // Firebase
        classpath('com.google.gms:google-services:4.4.0')
        classpath('com.google.firebase:firebase-crashlytics-gradle:2.9.9')
    }
}

```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
  OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
  Memory: 5.68 GB / 15.22 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 20.11.1
    path: /usr/bin/node
  Yarn: Not Found
  npm:
    version: 9.6.6
    path: ~/.npmglobal/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Hiipivahalko** [comment]
I think this expected error nowadays, check this https://cloud.google.com/identity-platform/docs/admin/email-enumeration-protection.

**Comment by DavideViolante** [comment]
I think @Hiipivahalko is right, after enabling email enumeration protection the error changes. Good to know.
