### ISSUE TITLE
FCM Notification Banner is not shown in IOS device

### ISSUE THREAD

**Issue by SandeshBG** [invertase/react-native-firebase#770]
### Issue
I have been trying to implement fcm in one of the project I am working. In android the notification is shown correctly. But In IOS the banner is not shown. I am getting the message in the background. But notification banner is not displayed.

This is my code:

import firebase from 'react-native-firebase';

const notif = firebase.messaging();

componentDidMount () {
notif.requestPermissions();

 notif.getToken()
    .then(res => {
       console.log(res); // returing device token
    })
    .catch( err => {
      console.log(err)
    })

if(!firebase.database().app._initialized){
       const App = firebase.initializeApp(iosConfig,'App');
       firebase.app('App').auth().signInAnonymously().then((user) => {
           console.log(user);
       }).catch(err=>console.log(err)); 
}
}

Platform: IOS 
Development OS: MacOS 10.13.2

Build Tools: X-Code 9

RN version:0.51.0
RNFirebase Version: 3.2.2

Firebase Module: firebase  cloud messaging

**Comment by Salakar** [comment]
@SandeshBG not entirely sure where you've got half of this code from? `if(!firebase.database().app._initialized){` for example doesn't exist

Also please see https://github.com/invertase/react-native-firebase/issues/595
