### ISSUE TITLE
I'm updated my react native version to 0.73.6 'FirebaseCrashlytics/FirebaseCrashlytics-Swift.h' file not found 

### ISSUE THREAD

**Issue by Mohamed-Ziyad** [invertase/react-native-firebase#7710]
this is my podfile 
![Screenshot 1445-09-17 at 15 11 41](https://github.com/invertase/react-native-firebase/assets/48976332/c00787b0-65be-46bc-af30-abd09fc9ecf0)

this is the issue from xcode 15.3 
<img width="1215" alt="Screenshot 1445-09-17 at 15 13 59" src="https://github.com/invertase/react-native-firebase/assets/48976332/2ceb2407-06dd-407e-81a9-d9b1071e3ef9">

I have followed the setup according to your official website, how to fix it?

**Comment by estmau** [comment]
Same problem with react native 0.72.12 and firebase 1.9.1

**Comment by Mohamed-Ziyad** [comment]
in your podfile add these lines   
$RNFirebaseAsStaticFramework = true
  config = use_native_modules!
  use_frameworks! :linkage => :static

<img width="546" alt="Screenshot 1445-09-19 at 12 48 19" src="https://github.com/invertase/react-native-firebase/assets/48976332/7437c105-926a-434d-86d0-94d1325b9965">

**Comment by DeepakSharma04** [comment]
Hye @Mohamed-Ziyad , can you check this 
I'm updated my react native version to 0.73.4 and getInitialNotification() and onNotificationOpenedApp() does not work in iOS #7715

**Comment by Mohamed-Ziyad** [comment]
in your index file.
import messaging from '@react-native-firebase/messaging';

add this line. 
messaging().setBackgroundMessageHandler(async remoteMessage => {
});

**Comment by alex-mironov** [comment]
Same problem

**Comment by mikehardy** [comment]
use_frameworks is a strict requirement, and you dodge it at your peril - it appears that you are using unsupported workarounds so this issue will be closed

It appears that you may find firebase-ios-sdk 10.24.0 will work - for now - as they have attempted to help people that struggle with use_frameworks by softening the Swift migration of Crashlytics which landed in 10.23.0, but adopting use_frameworks is the actual fix

In the meantime you can override the firebase-ios-sdk version as we document in our install docs *for temporary / unsupported use* to 10.22.0 or use react-native-firebase v18.x.x

https://github.com/firebase/firebase-ios-sdk/issues/12611#issuecomment-2028821390
