### ISSUE TITLE
Error: [messaging/unknown] The operation couldn’t be completed. No APNS token specified before fetching FCM Token

### ISSUE THREAD

**Issue by puneetkansal04** [invertase/react-native-firebase#7712]
Code is working fine till yesterday. And today I just started getting this error

Error: [messaging/unknown] The operation couldn’t be completed. No APNS token specified before fetching FCM Token

made changes as per questions like info.plist changes, AppDelegate.mm but still getting the same error.

What is changed today so I started getting error while generating firebase token

**Comment by built-by-as** [comment]
also seeing this

**Comment by wailin0** [comment]
same here

**Comment by kepman** [comment]
Same here

**Comment by mikehardy** [comment]
Unfortunately, when the template is ignored there is no ability to offer help
