### ISSUE TITLE
No known instance method for selector 'getLimitedUseTokenWithCompletion:'

### ISSUE THREAD

**Issue by Bob-JZhao** [invertase/react-native-firebase#7714]
## Issue

I am try to use firebase app check, but after install the @react-native-firebase/app-check and start app from xCode, I always get this error. I was following the documentation.  
<img width="1217" alt="image" src="https://github.com/invertase/react-native-firebase/assets/6147980/b937a877-d280-45f6-8896-578f129d4aaf">

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
  "@react-native-firebase/app": "^18.6.1",
    "@react-native-firebase/app-check": "^18.6.1",
    "@react-native-firebase/auth": "^18.6.1",
    "@react-native-firebase/functions": "^18.6.1",
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
 rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'FirebaseAppCheck'
  config = use_native_modules!

  # Required by RNFirebase, see https://rnfirebase.io/#altering-cocoapods-to-use-frameworks.
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  
```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"
#import <Firebase.h>
#import "RNFBAppCheckModule.h"  
#import <React/RCTBundleURLProvider.h>
#import <React/RCTLinkingManager.h>

#import <GoogleMaps/GoogleMaps.h>
#import "ADURLProtocol.h"
#import "RSSwizzle.h"

#import <CoreLocation/CoreLocation.h>

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
   [GMSServices provideAPIKey:KeyGoogle];
  self.moduleName = @"xxx";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};
 
  
 [RNFBAppCheckModule sharedInstance];
 [FIRApp configure];
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. ^18.6.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! You are overriding the firebase-ios-sdk version which implies that you are responsible for checking compatibility, and it appears you have not done so - adopting a newer version of react-native-firebase that depends on a newer API in firebase-ios-sdk but you have not moved your overridden SDK dependency.

If you remove your firebase-ios-sdk version pin from your Podfile, or update it to a supported version, your build will work.

https://github.com/invertase/react-native-firebase/blob/main/CHANGELOG.md#1870-2023-11-28
https://github.com/invertase/react-native-firebase/pull/7424

Wow, looks like it was added all the way back in firebase-ios-sdk 10.9.0 https://firebase.google.com/support/release-notes/ios#app_check_4

Your firebase-ios-sdk is likely quite out of date
