### ISSUE TITLE
[🐛] Bug Report Title - Missing Privacy Manifest for GoogleUtilities

### ISSUE THREAD

**Issue by jordan-rp-cb** [invertase/react-native-firebase#7716]
## Issue

Describe your issue here
I noticed Firebase is still using 7.11, but GoogleUtilities has a new [minor version](https://github.com/google/GoogleUtilities/releases/tag/7.13.0) increase which includes their new privacy manifest. Is that missing by accident or are there any plans to include this? 
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You've deleted the template, so I don't know what versions you are on, so I cannot help.

The latest react-native-firebase uses the latest firebase-ios-sdk though (well, 10.23.0, 10.23.1 will be an update we'll adopt here in the next couple hours though)

These should include privacy manifests.

**Comment by jordan-rp-cb** [comment]
@mikehardy given the privacy manifest isn't included in any version, I didn't think the version i'm using is relevant as it doesn't provide any value. Since there's nothing to debug here. 

>10.23.1 will be an update we'll adopt here in the next couple hours though 

This is what I was hoping to understand, thank you!

**Comment by mikehardy** [comment]
Versions are always relevant, hopefully the new version has what you need. If not underlying 10.24.0 I believe is targeted for April 9 release

**Comment by kevin-kp** [comment]
We have seen that `RNBPreferences.m` (https://github.com/invertase/react-native-firebase/blob/2c1f48eacba95904c89073dcb391d89d0f966165/packages/app/ios/RNFBApp/RNFBPreferences.m#L38) uses NSUserDefaults. Doesn't this mean that the podspec of react-native-firebase (packages/app) also need a PrivacyManifest?

**Comment by mikehardy** [comment]
@kevin-kp it appears we are touching UserDefaults here but react-native-firebase is distributed *as source*, so it can be thought of as a direct part of your app. You will need to include a privacy manifest in your app I believe and that would solve it?

Note that firebase-ios-sdk 10.25.0 appears to have taken some pains to remove the usage of user defaults (and I will publish an update here that includes it shortly: #7774 )

It may be that we can avoid it as well if that makes things easier for people but I looked into it and both firestore and database use user preferences (i.e. User defaults APIs) to store offline settings with regard to cache size and persistence preferences etc. I'm not sure how you would implement that functionality without an app-specific / user-specific persistent data storage area which is exactly what user defaults / preferences is for?
