### ISSUE TITLE
Daily Spike in Remote Config Fetches at 12:05 AM IST

### ISSUE THREAD

**Issue by sourcefbs** [invertase/react-native-firebase#7722]
### Discussed in https://github.com/invertase/react-native-firebase/discussions/7685

<div type='discussions-op-text'>

<sup>Originally posted by **sourcefbs** March 18, 2024</sup>
We're observing a daily spike in Remote Config fetches at 12:05 AM IST. Any insights or suggestions to address this issue would be greatly appreciated. 
![Screenshot 2024-03-18 at 15 21 30](https://github.com/invertase/react-native-firebase/assets/163841117/37e1a428-689c-42b5-963c-6517d87d0d03)
</div>

**Comment by mikehardy** [comment]
There is no information here that would help me help you as you have ignored our template.
Some idea of versions, configuration, code that reproduces it etc

https://stackoverflow.com/help/how-to-ask
