### ISSUE TITLE
Build error with use_frameworks! in version 3.2.2

### ISSUE THREAD

**Issue by KimAM** [invertase/react-native-firebase#773]
Hi,

When adding `use_frameworks!` to our Podfile we get the following error when building:

```
▸ Compiling RNFirebaseAdMobRewardedVideo.m

❌  /<myproject>/native/node_modules/react-native-firebase/ios/RNFirebase/admob/RNFirebaseAdMobRewardedVideo.h:4:9: 'React/RCTBridgeModule.h' file not found

#import <React/RCTBridgeModule.h>
                            ^
▸ Compiling RNFirebaseAdMob.m
▸ Compiling RNFirebaseLinks.m
▸ Compiling RNFirebaseFirestore.m
▸ Compiling RNFirebaseFirestoreCollectionReference.m
▸ Compiling RNFirebaseAuth.m
▸ Compiling RNFirebaseAdMobNativeExpressManager.m

❌  /<myproject>/native/node_modules/react-native-firebase/ios/RNFirebase/admob/RNFirebaseAdMobNativeExpressManager.h:1:9: 'React/RCTViewManager.h' file not found

#import <React/RCTViewManager.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~

▸ Compiling RNFirebaseFirestoreDocumentReference.m
** ARCHIVE FAILED **
```
I've followed all the steps in the release guide for version 3.2.0 and 3.2.2. Firebase is added as a dependency in the Podfile and we added react-native-firebase with `react-native link react-native-firebase`. We've also added our Pods_{projectName}.framework to Link Binary with Libraries inside RNFirebase.xcodeproj

We build the project with `npm run ios` and the funny thing is that this error occurs only the first build. The second time, the build is ok and the app starts. So everytime I delete the `ios/build` folder, the build fails the first time.

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS

3. Build Tools: XCode

4. React Native version: 0.51

5. RNFirebase Version: 3.2.2

6. Firebase Module: N/A

**Comment by Salakar** [comment]
@KimAM that's a weird one, certainly sounds like xcode derrived data issue where it's not being cleared, if you try the below straight after nuking your build dir does it still occur?

![image](https://user-images.githubusercontent.com/5347038/35244535-57d3743c-ffb8-11e7-8886-2910d55f4d73.png)

**Comment by KimAM** [comment]
Thanks for your reply! I took the step to manually link react-native (instead of using cocoapods) due to a problem with another library as well. Everything is working fine now.
