### ISSUE TITLE
feature request: support index manager APIs for firestore

### ISSUE THREAD

**Issue by joaqo** [invertase/react-native-firebase#7737]
Hi, I was just wondering if there is documentation for the Index Manager introduced around September 2023 in the official SDK?

@mikehardy I saw you commenting on their [original PR](https://github.com/firebase/firebase-ios-sdk/pull/11596#issuecomment-1721557664), so I am assuming it got implemented here as well?

Thanks!

**Comment by mikehardy** [comment]
Hey @joaqo - I investigated that one but never got a reply on that query, so I did not complete any implementation work here - it has sat idle sense then

Documented above now - just not with the capital `P` - https://firebase.google.com/docs/reference/ios/firebasefirestore/api/reference/Classes/FIRFirestore#persistentcacheindexmanager

So, nothing blocking implementation here as it exists on web (for API shape) and android+ios (for underlying implementation)

Does not exist here as an implementation yet though - I'll leave this open with a slightly altered title, and would happily collaborate on getting a PR in that implemented it
