### ISSUE TITLE
in target 'FirebaseStorage' from project 'Pods'

### ISSUE THREAD

**Issue by Thivakar-N** [invertase/react-native-firebase#7738]
## Issue

Describe your issue here

I am having React Native 0.73.6 version with firebase sdk 19.0.0.

I configured everything according to the rnfirebase.io in my mac m2. I am getting build error when I use firebase storage. I tried uninstalling the firebase-storage and build was successful. I did everything as as in the docs.

I got this build error,

The following build commands failed:
        SwiftCompile normal arm64 Compiling\ AsyncAwait.swift,\ Result.swift,\ Storage.swift /Users/accronrevolutions/Downloads/MyLaptopMain/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/AsyncAwait.swift /Users/accronrevolutions/Downloads/MyLaptopMain/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Result.swift /Users/accronrevolutions/Downloads/MyLaptopMain/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift (in target 'FirebaseStorage' from project 'Pods')
        SwiftCompile normal arm64 /Users/accronrevolutions/Downloads/MyLaptopMain/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift (in target 'FirebaseStorage' from project 'Pods')
(2 failures)
---

## Project Files

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MyLaptop' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
 

  $RNFirebaseAsStaticFramework = true
  use_react_native!(

    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
   :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MyLaptopTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:
#import "AppDelegate.h"
#import <Firebase.h>
#import <React/RCTBundleURLProvider.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions

{

  self.moduleName = @"MyLaptop";
  [FIRApp configure];
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
  return [self getBundleURL];
}

- (NSURL *)getBundleURL
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Nantris** [comment]
@Thivakar-N thanks for sharing. Could you clarify what you upgraded? All the `@react-native-firebase/*` packages? Could you let me know to what version? I'm facing this issue and haven't been able to work around it thus far.

**Comment by mikehardy** [comment]
@Nantris 

1- flipper has been completely removed from react-native in current versions, so I encourage you to similarly remove it (ideally by upgrading to latest react-native 0.74.2)
2- once that is done you should have no problem using `use_frameworks! :linkage => :static` as is documented here since it is a hard requirement for having a supported, working build
3- you'll want the most up to date react-native-firebase versions in general as the recent changes to support framework signing and privacy manifests only just recently stabilized and you will likely have publishing problems with Apple App Store if you are not current
