### ISSUE TITLE
Bump iOS SDK to 10.24.0 to comply with Apple requirements

### ISSUE THREAD

**Issue by gabrielguilhoto** [invertase/react-native-firebase#7743]
## Issue

Starting May 1, Apple [will require](https://developer.apple.com/support/third-party-SDK-requirements/) certain SDKs, including Firebase, to be signed. According to https://github.com/firebase/firebase-ios-sdk/issues/12238, signing was added to the 10.24.0 iOS SDK. Could you bump the iOS SDK to comply with Apple requirements?

I didn't fill in the template below because it looks like the environment is not relevant to this issue.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Yeah, been hitting refresh on the iOS release page to see when 10.24.0 would drop https://firebase.google.com/support/release-notes/ios

Happy to see it out. I'll run through the process of updating the native SDKs and get it shipped

**Comment by ucheNkadiCode** [comment]
Hey @mikehardy, thanks for bumping this version. Currently I'm on 14.12.0 of react native firebase due to the issues surrounding use_frameworks and flipper support. With this new news, does this mean that 14.12.0 will no longer work/no longer send data? Any thoughts would be super helpful.

<img width="1113" alt="image" src="https://github.com/invertase/react-native-firebase/assets/20650058/150f1fcf-aae8-42b9-b614-d8f3471060b1">

**Comment by mikehardy** [comment]
Your app will likely be removed from the app store or at minimum you will not be able to publish updates if you don't comply with Apple policy
