### ISSUE TITLE
 [🐛] getInitialNotification returns old notification data on Android

### ISSUE THREAD

**Issue by klaevv** [invertase/react-native-firebase#7749]
## Issue

Noticed that this (#6130)  bug is still repeatable with "@react-native-firebase/messaging": "19.0.1":

On Android the getInitialNotification can return previously opened notification's data, instead of the one that the user opened most recently.

Steps to reproduce:

1. Kill the app if it's currently in the background
2. Send a notification containing data A
3. Open the notification and check that it contains data A
4. Press home to leave the app (note: important to leave with the home button, not with the back button)
5. Send a notification with data B
6. Open the notification and check that it contains data B
7. Press back to leave the app (note: important to leave with the back button, not with the home button)
8. Send a third notification with data C
9. Open the notification

Expected result is that you would get the third notification's data C when calling getInitialNotification, but instead you get the second notification's data B.

I was reading the library's code and I think the issue is in this functionality where the notification data is stored in the onNewIntent handler and then returned in the getInitialNotification:

https://github.com/invertase/react-native-firebase/blob/514e6bd51e7624a6403dda706f4e5b65cee63422/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java#L61

The data gets set to null after it's returned but the problem is that in that above reproduction sequence in the step 6 the app returns from the background in which case the onNotificationOpenedApp callback gets triggered in which case we don't call the getInitialNotification since we get the correct notification data already in the callback parameters so in that case the data is left in place.

Note that it is possible to workaround this issue by doing an "unnecessary" getInitialNotification call inside that onNotificationOpenedApp callback, which will then set the stored notification value to null and the stale data doesn't exist anymore in the step 9.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by LA-Johan** [comment]
@klaevv I think I'm facing the same issue. Can you expand on what your workaround is? Would you call `getInitialNotification()` after `log("onNotificationOpenedApp")` in my code here?
```
const useRegisterNotificationActionHandlers = (): void => {
  const linkTo = useLinkTo()
  useEffect(() => {
    messaging()
      .getInitialNotification()
      .then(
        message => {
          if (message == null) return
          log("getInitialNotification")
          handleRemoteMessage(message, linkTo)
        },
        e => logError("Error loading initial notification", e)
      )
    return messaging().onNotificationOpenedApp(remoteMessage => {
      log("onNotificationOpenedApp")
      handleRemoteMessage(remoteMessage, linkTo)
    })
  }, [linkTo])
}
```

**Comment by LA-Johan** [comment]
@klaevv thank you for responding!

I'm a little confused, in your example you don't change the notification you're passing to `navigateFromNotification`, why would just calling `messaging.getInitialNotification()` help?

**Comment by klaevv** [comment]
This workaound with seemingly unnecessary `getInitialNotification` call to get the initial notification is a fix for an issue in the react-native-firebase library where they are storing notification data as a result of the Android's onNewIntent() call, and the getInitialNotification() clears the stored data. We don't need the stored data since we have our own implementation of the onNewIntent() in our MainActivity where we update the current intent.

**Comment by LA-Johan** [comment]
@klaevv I see, that makes sense. Would you mind sharing your MainActivity code?

**Comment by klaevv** [comment]
Here:

```
@Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
    }
```

**Comment by mikehardy** [comment]
Huh...perhaps adding a `@CallSuper` to our 

This looks like it is not actionable here - we expect onNewIntent to be called, but this is definitely a developer trap, as our onNewIntent will only be called if people correctly call the super ReactActivity method when they override

Java (and Kotlin I suppose) have a way to avoid this trap though, I wonder if adding a `@CallSuper` annotation here would be the correct thing:

https://github.com/facebook/react-native/blob/b38f80aeb6ad986c64fd03f53b2e01a7990e1533/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactActivity.java#L110

...probably on the other methods as well, as they all can potentially have side-effects that module developers expect to happen, but the call chain can be broken if someone overrides the methods in MainActivity without calling the correct super methods in ReactActivity above them in the inheritance chain...

Not something we can handle here but if you open an issue / propose a PR in react-native, putting a link to this issue would be interesting as it would allow for followup knowledge

**Comment by LA-Johan** [comment]
@klaevv thank you so much for sharing

@mikehardy Can you expand on what the trap here is? Prior to me trying to work around this I had not overridden  onNewIntent

**Comment by mikehardy** [comment]
> @klaevv thank you so much for sharing
> 
> @mikehardy Can you expand on what the trap here is? Prior to me trying to work around this I had not overridden  onNewIntent 

That's the trap. That people don't know a super call exists and they need to override it in order for objects you inherit from to meet their contracts.

A CallSuper annotated method will fail lint checks at least, notifying the developer they are missing the call to super, avoiding the broken contract trap

**Comment by LA-Johan** [comment]
I'm still not following. Let me play it back and you can tell me where I'm wrong:

Option 1: There's a bug in this library that can be work around by overriding onNewIntent. If so, then this issue should not be closed. 

Option 2: There's a bug in the react-native implementation of the ReactActivity. If so, I think the workaround should at least be documented in this library and this issue should remain open. 

Option 3: The bug is somewhere in my code of how I use this library.

**Comment by LA-Johan** [comment]
@mikehardy wanted to follow up on this!

**Comment by LA-Johan** [comment]
@mikehardy but I had this issue without overriding anything. There was no super call I was not calling.

**Comment by mikehardy** [comment]
@LA-Johan as you are posting a lot on someone else's issue, it's possible that we are talking at cross-purposes.

All of my discussion of calling a super class is based on this from the original issue author https://github.com/invertase/react-native-firebase/issues/7749#issuecomment-2075169937

It appears you can just do this and have things working https://github.com/invertase/react-native-firebase/issues/7749#issuecomment-2075084174

The original poster explained in the difference that this is because we store the notification contents of initial notifications (when app is not running) but not notifications when app is running but in background. And if that storage isn't cleared out with a getInitialNotification call then you can get stale data. So they are doing an otherwise-unnecessary getInitialNotification call.

Note that this is all determined from the original poster's description. I believe it answers all your questions and in that followup comment I linked offers you a workaround. 

I have not personally had time to investigate, but would welcome a PR if there was some way to handle the notification storage clearance issue when notifications are posted but the app is already running

**Comment by LA-Johan** [comment]
@mikehardy I think you're right. I've been getting user reports of notifications leading to the wrong URL on Android. I have not been able to reproduce personally. 

After implementing the workarounds suggested by @klaevv the user now reports that they no longer end up at the wrong URL. I had not previously overridden `onNewIntent` so I do believe that there is a bug in this library, but the workaround works for me.

**Comment by jamalud-lab** [comment]
Reopen this issue
