### ISSUE TITLE
Unable to upload to multiple buckets

### ISSUE THREAD

**Issue by FacuAcosta** [invertase/react-native-firebase#775]
Hi, we are using multiple buckets on our app. Since there is no documentation for the Storage on the Docs we are using the official one provided by Google. They say in there that for using a different bucket and not the default one, we need to use this function:

`var storage = firebase.app().storage("gs://my-custom-bucket");`
[](https://firebase.google.com/docs/storage/web/start)

While doing this, I get a red screen saying that `Invalid FirebaseApp instance passed to firebase.storage(app <--).` Looking at the source code, It seems that this option is not available right now on RNFirebase and It's a needed one.

I tried to use other app instance changing the bucket and sending it into the storage() function, but since the user is logged into the other app instance, we are not able to upload files to that bucket.

Is there a workaround for doing this?

**Comment by Ehesp** [comment]
Hello, currently the string version of the URL doesn't work in RNFirebase. You can however pass the [App](https://rnfirebase.io/docs/v3.2.x/core/reference/App) instance you want.

**Comment by K0ff33** [comment]
What is the best way to extend the current `App` instance with the new storage url without recreating the object?

Creating a completely new `App` instance resulted in having a user logged in to one (with default bucket) and not to the other one.

**Comment by Salakar** [comment]
@K0ff33 https://github.com/invertase/react-native-firebase/pull/675 might be a good reference for you - this is how the multi-db by url support was implemented for database - technically the storage bucket url support should be very similar to this - if it helps.

**Comment by K0ff33** [comment]
Unfortunately I'm not a mobile app developer but I'm doing my best in trying to debug the issue.

Some of my thoughts:
`firebase.storage().refFromURL("gs://my-custom-bucket/path-to.file")` can't be used to retrieve files from different bucket as the implementation in the Firebase SDK does not allow to pass a different bucket than the one in the current instance: [link to iOS SDK source code](https://github.com/firebase/firebase-ios-sdk/blob/7226b4adf38e4732dfb9a840d25f86d3e5533bdb/Firebase/Storage/FIRStorage.m#L200).
That is why the app crashes as described in #776. 
<img width="1291" alt="screen shot 2018-01-26 at 14 19 33" src="https://user-images.githubusercontent.com/8126512/35444680-2cd42eb0-02a7-11e8-9d13-295ab15d7fde.png">

I believe that the only way to support multiple buckets is by implementing the option to pass bucket name in the storage constructor: `var storage = firebase.app().storage("gs://my-custom-bucket");`.

**Comment by olegwn** [comment]
Any news on this?

Would be really cool to do something like:
>var storage = firebase.app().storage("gs://my-custom-bucket");

**Comment by Salakar** [comment]
Thanks for reporting this issue. This is something we're going to add support for.

We're aware that Storage has fallen behind slightly on React Native Firebase and would like to bring it up to speed again. I will close this issue for now and track it as well as other issues collectively over on the Storage improvements proposal to be addressed in a future release. See #1260

**Comment by Salakar** [comment]
Hey @FacuAcosta @k0ff33 @olegwn  - just thought you'd like to know the v6 storage re-write PR is up and well into dev, which includes many improvements including multi-bucket support 🎉 

**PR & Changelog**: https://github.com/invertase/react-native-firebase/pull/2043

**Comment by williamgoodhew** [comment]
I am getting this same error. I am on react-native-firebase v 5.6.0. Have tried to upgrade to @latest but this seems to be the latest. 

In my podfile I have:

pod 'Firebase/Storage', '~> 6.13.0'

React-native version 0.61.5.

I've tried this
`const storage = firebase.app().storage("gs://athalens-51eb0-us-rekognition");

    const storageRef = storage.ref(uid)

    storageRef.put(uri)
      .then(() => {
        dispatch({ type: SET_SELFIE });
      })
      .catch(error => {
        console.log(error);
      });`

and this

`const storageRef = firebase.storage('gs://athalens-51eb0-us-rekognition').ref(uid)

    storageRef.put(uri)
      .then(() => {
        dispatch({ type: SET_SELFIE });
      })
      .catch(error => {
        console.log(error);
      });`

I know it says upgrade to v6 but not sure why npm install @latest is only doing v5.6.0

**Comment by mikehardy** [comment]
Ah - that is because when RNFB moved from v5 to v6 it also changed packaging style, so `@latest` of the package `react-native-firebase` **is** 5.6.0, but if you want v6 you install different packages - now they look like `@react-native-firebase/app` + `@react-native-app/storage` etc (modules all split out)

**Comment by williamgoodhew** [comment]
Ok. Thanks. So do I run npm install --save react-native-firebase/storage@6?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mikehardy** [comment]
I believe you'd want this doc: https://invertase.io/oss/react-native-firebase/migrating-to-v6

**Comment by amitiwary999** [comment]
setting bucket in storage is not working. I already migrated to v6. I tried storage('gs://bucket_name') but it's not working.

**Comment by Mavenic** [comment]
Same for me.
Getting the following error:

Error: "firebase.storage(app)" arg expects a FirebaseApp instance or undefined.
Ensure the arg provided is a Firebase app instance; or no args to use the default Firebase app.

```
firebaseModuleWithApp
    namespace.js:138:10
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:221989:43
loadModuleImplementation
    require.js:321:4

```

**Comment by BrianL3** [comment]
Still getting this error, using
`"@react-native-firebase/storage": "16.7.0"`

How are you supposed to use non-default buckets?

**Comment by zeevl** [comment]
I finally got this to work by doing 
```
storage().refFromURL('gs://other-bucket/path')
```
