### ISSUE TITLE
Firebase Push Notification Data Inconsistency and Open Rate Issues

### ISSUE THREAD

**Issue by inveon-ozantuna** [invertase/react-native-firebase#7753]
## Issue

Hello,

We are currently using Firebase push notifications to send notifications in our application. However, we have noticed that the notification content appears to be incomplete and the notification open rates are inconsistent. These issues are negatively impacting user experience and compromising data accuracy.

In our development environment, we are using React Native version 0.62.2 and Firebase version 12.7.0. Upon reviewing, we have found that there seems to be an issue with the Firebase SDK in transmitting data. Even after adding labels for events like 'notification_open', there are inconsistencies observed in the notification data.

Could you provide us with suggestions or guidance on how to address these issues, perhaps by using the latest versions of Firebase SDK and React Native Firebase package? Additionally, if anyone has experienced or resolved similar issues before, sharing their insights would be greatly appreciated.

We are looking forward to your assistance. Thank you.
![screenshotfirebase](https://github.com/invertase/react-native-firebase/assets/135812452/09b8695b-fcfc-43fc-b62e-b0dc2d68e5ae)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
> React Native version 0.62.2 and Firebase version 12.7.0

These are far, far too old to support at all, and in general when asking for support in an open source context make sure you are 100% updated to the current stable release of all packages in question, you still reproduce, *then* ask for support

Asking for support on old versions is inefficient as it means you may be discovering problems that are already fixed, and even if not fixed the reproduction is difficult because the versions aren't current

Additionally, when you ask for support and the support request includes requests for information. Provide the information
