### ISSUE TITLE
[🐛] Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

### ISSUE THREAD

**Issue by pratikdonda** [invertase/react-native-firebase#7767]
<img width="509" alt="Screenshot 2024-04-26 at 18 44 59" src="https://github.com/invertase/react-native-firebase/assets/25050821/159242a2-6dd6-4e95-add8-3db1bd45e4fc">

Getting error while run jest test cases.

**Comment by mikehardy** [comment]
insufficient information to help
template deleted
no sample code
no indication of what jest mocks you are using

Not able to help
