### ISSUE TITLE
Problems with pagination(startAfter() in specific)

### ISSUE THREAD

**Issue by Dezainer** [invertase/react-native-firebase#779]
Hello there guys,

I'm having a problem when attempting to do some pagination...
Variations happen and sometimes i get a warning and some times an error, but they are kind of the same

![screenshot_20180124-154909](https://user-images.githubusercontent.com/19918284/35348281-c493e536-011e-11e8-898d-bc83a2bd1495.png)

Anyways, it seems to be related to the **startAfter()** function of my query... 
Here's a simple test function i created to test the pagination (Based on -> https://firebase.google.com/docs/firestore/query-data/query-cursors):
`
paginateProducts() {
		let first, second, last

		//First Page Query
		this.collection('products/1/1')
			.orderBy('title')
			.limit(3)
			.get()
			.then(products => {
				//A function i use to get the data the way i need it
				first = this.formatCollection(products)

				//Getting the last element
				last = products.docs[products.docs.length - 1]

				//Second Page Query
				this.collection('products/1/1')
					.orderBy('title')
					.startAfter(last) //This is where it all happens
					.limit(3)
					.get()
					.then(moreProducts => {
						second = this.formatCollection(moreProducts)
						all = [...first, ...second]

						console.error(all)
					})
			})
	}
`

I don't really know why this happens, i have a similar code working on the web SDK of Firebase but can't seem to make it work here on react-native....

Here is some extra info from my **package.json**:
`
"dependencies": {
    "react": "16.0.0",
    "react-native": "^0.48.0",
    "react-native-firebase": "^3.0.5",
    "react-native-svg": "^5.4.1",
    "react-navigation": "^1.0.0-beta.11"
  },
"devDependencies": {
    "babel-preset-react-native-stage-0": "^1.0.1",
    "jest-expo": "~22.0.1",
    "react-test-renderer": "16.0.0"
  }
`

Hope we can figure it out ;)
Thanks

**Comment by Ehesp** [comment]
Is there any reason you've not upgraded this lib? We're on 3.2.2 now and there's been quite a lot of bug fixes in Firestore in later versions.

**Comment by Dezainer** [comment]
Omg, i feel so silly haha. Thank you for your time, after an upgrade and a rebuild it's working perfectly! Again, thank you so much!
