### ISSUE TITLE
[📚] Documentation Issue Title - Migrating to v6

### ISSUE THREAD

**Issue by twocs** [invertase/react-native-firebase#7803]
## Documentation Feedback

When I visit the rnfirebase website, the fourth article in the sidebar is called "Migrating to v6". When I look at react-native-firebase, it doesn't refer to a recent versions as v19, instead the modules have versions like 19.

Thus, I would suggest that this article https://rnfirebase.io/migrating-to-v6 is also legacy documentation. It is really confusing for someone who's trying to fix a bug and make sure that they are on the latest version, when the first thing they see on rnfirebase after Getting Started and Release Notes is "Migrating to v6". 

Can we also have the current version number on the home page of https://rnfirebase.io? Would be great to use a dynamic github badge that just shows the current version number without requiring editing. Would also be nice to see this number on the github readme as well, because currently it's not really easy to see the current version number via https://github.com/invertase/react-native-firebase (version is not set in the root package.json file, only the modules, which takes a bit of digging). 

[Edit: noticed that there's a badge:
![image](https://github.com/invertase/react-native-firebase/assets/72763/26c28fbe-cfa2-417f-bcb1-a7c54bfe9df1)
To a naive document reader, "npm: v20.0.0" does not convey to me that react-native-firebase is now up to version 20.0.0. Although it implies version 20.0.0 is available via npm, it doesn't actually say this in https://github.com/invertase/react-native-firebase/blob/main/README.md... Personally I think since npm is the main way the project is released, it could be improved a sentence saying so, which would give more context to the npm: v20.0.0 badge.]

Even better would be to have documentations locked to different versions, so that e.g. if someone's still on v6 they can simply select the v6 version of the documentation.

**Comment by twocs** [comment]
For context, this is how important "Migrating to v6" looks on the home page:
![image](https://github.com/invertase/react-native-firebase/assets/72763/495e0be2-d0b7-40f6-a580-6aeab1ea34ce)

Nothing in the v6 page looks like it's years out of date:
![image](https://github.com/invertase/react-native-firebase/assets/72763/7a8a7e0a-0e9a-45dc-bd06-8ff513854f39)

**Comment by mikehardy** [comment]
These are all great points, have you thought about tapping the edit button at top right and taking a quick swipe at it via the github web UI? I'm likely to merge anything reasonable, and simply moving the v6 stuff (which is really old! as you mention) to somewhere marked clearly as legacy, and adding the npm version badge with an explanation might be quick+easy
