### ISSUE TITLE
/ios/Pods/Headers/Private/grpc/gRPC-Core.modulemap' not found

### ISSUE THREAD

**Issue by Harshit-Unicsol** [invertase/react-native-firebase#7805]
I am using the React native version 0.73.6 in my existing application with firebase 

 "@react-native-firebase/app": "^19.2.2",
    "@react-native-firebase/database": "^19.2.2",
    "@react-native-firebase/firestore": "^19.2.2",
    "@react-native-firebase/messaging": "^19.2.2"
    
I am getting an error while building the Application on Xcode 

Showing All Messages
module map file '/ios/Pods/Headers/Private/grpc/gRPC-Core.modulemap' not found

**Comment by mikehardy** [comment]
Deleted issue template, so closing issue 

You might search issues list for rnfbdemo - it's a demonstration of correct integration that will build correctly

**Comment by ketanuengage** [comment]
> I am using the React native version 0.73.6 in my existing application with firebase
> 
> "@react-native-firebase/app": "^19.2.2", "@react-native-firebase/database": "^19.2.2", "@react-native-firebase/firestore": "^19.2.2", "@react-native-firebase/messaging": "^19.2.2"
> 
> I am getting an error while building the Application on Xcode
> 
> Showing All Messages module map file '/ios/Pods/Headers/Private/grpc/gRPC-Core.modulemap' not found

@Harshit-Unicsol Did you find any solution to this? I am also getting same error with latest package versions.

**Comment by ketanuengage** [comment]
> Deleted issue template, so closing issue
> 
> You might search issues list for rnfbdemo - it's a demonstration of correct integration that will build correctly

This did not help.

**Comment by Harshit-Unicsol** [comment]
Yes I found the solution @ketanuengage

**Comment by ketanuengage** [comment]
> Yes I found the solution @ketanuengage

@Harshit-Unicsol 
Can you share the same as I am also struggling with this error?

**Comment by Harshit-Unicsol** [comment]
@ketanuengage 

Update the React native version 0.73.6 to 0.73.8 and delete the node modules and Pods and clear the cache, then install node modules and pods and run the project

**Comment by ketanuengage** [comment]
> @ketanuengage 
> 
> Update the React native version 0.73.6 to 0.73.8 and delete the node modules and Pods and clear the cache, then install node modules and pods and run the project

I am using react native version 0.68.3.
All other firebase packages works fine but when I added firestore then started getting this error.

**Comment by Harshit-Unicsol** [comment]
@ketanuengage, you should downgrade the firebase package versions with firestore

**Comment by mikehardy** [comment]
I don't think it is reasonable to expect react-native versions that old to continue functioning, mobile development implies moving pretty quickly with software upgrades as the underlying platforms and build toolchains change pretty quickly

I would investigate and pursue getting your underlying react-native version updated to current as a high priority item

**Comment by farhan-pathan-us** [comment]
@mikehardy Did you get any another solution?

**Comment by mikehardy** [comment]
@farhan-pathan-us nothing related to this issue has been an issue forever. I suspect something is awfully wrong in your Podfile. Perhaps you are attempting to use completely-unsupported-you-must-remove-them-now `modular_headers` workarounds instead of the strictly-required-you-must-use-it `use_frameworks! :linkage => :static`

I can say for certain that this issue has none of the required information in order to help though.

**Comment by farhan-pathan-us** [comment]
Yes, thanku it works with this line
`use_frameworks! :linkage => :static`

**Comment by farhan-pathan-us** [comment]
@vithika **$RNFirebaseAsStaticFramework = true** 
have you added this line at top?

#Podfile

target 'NewProject' do
  config = use_native_modules!

  **# ✅ Required for Firebase to work as static frameworks. Add Here👇
  use_frameworks! :linkage => :static**. 

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end

**Comment by vithika** [comment]
> [@vithika](https://github.com/vithika) **$RNFirebaseAsStaticFramework = true** have you added this line at top?
> 
> #Podfile
> 
> target 'NewProject' do config = use_native_modules!
> 
> **# ✅ Required for Firebase to work as static frameworks. Add Here👇 use_frameworks! :linkage => :static**.
> 
> use_react_native!( :path => config[:reactNativePath], # An absolute path to your application root. :app_path => "#{Pod::Config.instance.installation_root}/.." )
> 
> post_install do |installer| # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202 react_native_post_install( installer, config[:reactNativePath], :mac_catalyst_enabled => false, # :ccache_enabled => true ) end end



Yes I have added..but still same error.

**Comment by farhan-pathan-us** [comment]
@vithika Can you paste your pod file?

**Comment by vithika** [comment]
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
use_modular_headers!
platform :ios, '13.0'
prepare_react_native_project!
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  # use_frameworks! :linkage => linkage.to_sym
  use_frameworks! :linkage => :static
end
$RNFirebaseAsStaticFramework = true

target 'ProjectName' do
 
 

  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    
   
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # post_install do |installer|
  #   # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  #   react_native_post_install(
  #     installer,
  #     config[:reactNativePath],
  #     :mac_catalyst_enabled => false, 
  #      # :ccache_enabled => true
  #   )
  # end
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'BoringSSL-GRPC'
        target.source_build_phase.files.each do |file|
          if file.settings && file.settings['COMPILER_FLAGS']
            flags = file.settings['COMPILER_FLAGS'].split
            flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
            file.settings['COMPILER_FLAGS'] = flags.join(' ')
          end
        end
      end
     
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
    react_native_post_install(
      installer,
      config[:reactNativePath],
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    # __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

  $RNFirebaseAnalyticsWithoutAdIdSupport = true

 
end

@farhan-pathan-us  - added my pod file

**Comment by farhan-pathan-us** [comment]
@vithika 

#Add this at top of file 
$RNFirebaseAsStaticFramework = true 

#Replace this code 
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

#Replace this code in target
target 'ProjectName' do
 config = use_native_modules!

  # ✅ Add this line here It is required for Firebase to work as static frameworks
  use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
        # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


Try this steps if not working, feel free to reach
