### ISSUE TITLE
[🐛] Icon notification not display in xiaomi devices - CHANGE ME 

### ISSUE THREAD

**Issue by anubisdark** [invertase/react-native-firebase#7807]
hi there, i have this bug. Chen i use firebase messages in my react native project. When display notifications in xiaomi devices, i can't view the icon of my app, but when i use other device example, samnsung i can view the icon in the notification. How can solve this issue?

![1](https://github.com/invertase/react-native-firebase/assets/49248371/81245543-eb2c-4a81-88a4-2f699bec91f8)

## Issue

Describe your issue here

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
If it is manufacturer specific I'm not sure there is much we can do here so I'm going to close this as not actionable
If it *were* actionable it would be in a different repo regardless as it is native functionality so that would be firebase-android-sdk

That said, it may just be a matter of rebooting your device according to the internet: https://stackoverflow.com/questions/40093616/android-miui-setting-small-icon-in-notification-bar-not-working-default-icon-di

**Comment by anubisdark** [comment]
Hi @mikehardy , finally resolve when send in the parameter of sdk pyton the name of icon. But this sdk not have upgrade, you know when this sdk will be upgrade?
