### ISSUE TITLE
_reactNativeFirebase2.default.auth(...).useDeviceLanguage is not a function

### ISSUE THREAD

**Issue by goleador0322** [invertase/react-native-firebase#781]
I tried to use useDeviceLanguage function (like firebase.auth().userDeviceLanguage)

but, I got this error.
```
ExceptionsManager.js:65 _reactNativeFirebase2.default.auth(...).useDeviceLanguage is not a function
```

how can i fix this :( ?

Podfile.lock
```
- Firebase/Auth (4.8.1):
    - Firebase/Core
    - FirebaseAuth (= 4.4.2)
  - Firebase/Core (4.8.1):
    - FirebaseAnalytics (= 4.0.7)
    - FirebaseCore (= 4.0.14)
  - FirebaseAnalytics (4.0.7):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - nanopb (~> 0.3)
  - FirebaseAuth (4.4.2):
    - FirebaseAnalytics (~> 4.0)
    - GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseCore (4.0.14):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseInstanceID (2.0.8):
    - FirebaseCore (~> 4.0)
```

yarn.lock
```
react-native-firebase@^3.2.2:
  version "3.2.2"
  resolved "https://registry.yarnpkg.com/react-native-firebase/-/react-native-firebase-3.2.2.tgz#768d0384de489ffcee106f53c9fbb41cee7eebb0"
  dependencies:
    bows "^1.6.0"
    opencollective "^1.0.3"
    postinstall-build "^5.0.1"
    prop-types "^15.6.0"
```

**Comment by Ehesp** [comment]
Hello, `useDeviceLanguage` is unsupported as there's a bug with the iOS SDK. (Docs need updating!).

For now, I'd recommend using [languageCode](https://rnfirebase.io/docs/v3.2.x/auth/reference/auth#languageCode) and grabbing the language via another lib (e.g https://github.com/rebeccahughes/react-native-device-info)

**Comment by Ehesp** [comment]
https://github.com/invertase/react-native-firebase-docs/commit/268aff770877c17bd5d815fae9fe541616e2d550

**Comment by goleador0322** [comment]
@Ehesp 
omg, what a fast response !!
Thanks you, I will try to use languageCode

**Comment by chrisbianca** [comment]
@goleador0322 Also, note that this hasn't yet been released - you'd need to install from the master branch for it to work. We're planning a release sometime in the next week.

**Comment by goleador0322** [comment]
@chrisbianca 
ok, I understand! For now, I'm using languageCode function 💪 
But, I am really looking forward to being able to use useDeviceLanguage 👏

**Comment by Ehesp** [comment]
`languageCode` is on master (pending release), `useDeviceLanguage` won't be available until Firebase fix an issue with iOS.

**Comment by goleador0322** [comment]
sorry for my poor English.... 😢 
I could understand completely. I will use languageCode 🥇

**Comment by scaralfred** [comment]
Hello guys. I tried to use => auth().languageCode(appLanguage)

But it does not work. It throws an error => .languageCode() is not a function...

**Comment by mikehardy** [comment]
@scaralfred it's a property not a function, you do `const currentLanguage = auth().languageCode`
