### ISSUE TITLE
[📚] Update Google Analytics for Firebase (GA4F) iOS SDK to Version 10.24.0 or Later

### ISSUE THREAD

**Issue by sajid-foodhub** [invertase/react-native-firebase#7812]
Action Recommended:
Update the Google Analytics for Firebase (GA4F) iOS SDK to version 10.24.0 or later to comply with upcoming privacy manifest policies effective after May 1, 2024.

Issue Details:
The current version of the GA4F iOS SDK in our project needs to be updated to version 10.24.0 or later. Failure to update may result in potential impacts due to new privacy manifest policies that come into effect after May 1, 2024.

Can you suggest which React Native Firebase Analytics version I should migrate to resolve this privacy policy issue?

Also, my React Native version in the project is 0.67.5. Should I also migrate to the latest React Native version?

**Comment by CaptainJeff** [comment]
Same question as to which of these dependency versions are 10.24.0 and later

**Comment by ThalesBMC** [comment]
Version 19.0.0 already uses version 10.24.0. 
It works fine on iOS, but it's causing build errors on Android.

**Comment by sajid-foodhub** [comment]
> Same question as to which of these dependency versions are 10.24.0 and later

Hi @CaptainJeff, Hope this helps you  😊

While checking this document [,](https://github.com/invertase/react-native-firebase/blob/main/CHANGELOG.md#1920-2024-04-10) I found out that the iOS SDK 10.24.0 is available starting from version 19.2.0 of @react-native-firebase/analytics. However, I need confirmation on this. My project's React Native version is 0.67.5, and when upgrading the Firebase Analytics version to 19.2.0, I face some build issues.

I need to check whether I should upgrade my project's React Native version, or if it is possible to upgrade to Firebase Analytics 19.2.0 with the existing React Native version Any idea about this.

**Comment by ThalesBMC** [comment]
@sajid-foodhub I also have this problem, and my project is also on 0.67.5. 
I was able to run the project on iOS, but I encountered some build problems on Android that I was not able to fix.
Please, if you are able to update the version share your solution :)

**Comment by sajid-foodhub** [comment]
> @sajid-foodhub I also have this problem, and my project is also on 0.67.5. I was able to run the project on iOS, but I encountered some build problems on Android that I was not able to fix. Please, if you are able to update the version share your solution :)

Hi @ThalesBMC ,

I have resolved the Android build issues and am now able to generate a build. However, I haven't thoroughly checked whether all Firebase Analytics functionalities are working fine.

Changes made:

 --> Upgraded Kotlin version from 1.7.20 to 1.9.20.
 -->   Upgraded project-level build.gradle from classpath("com.android.tools.build:gradle:4.2.2") to classpath("com.android.tools.build:gradle:7.0.0-rc01").

**Comment by ThalesBMC** [comment]
@sajid-foodhub Thank you for your help!

The only problem on my side with iOS was the pod incompatibilities.
I had to add these two lines to the Podfile to make it work on iOS:
`pod 'FirebaseCore', :modular_headers => true`
`pod 'GoogleUtilities', :modular_headers => true`

**Comment by ThalesBMC** [comment]
@sajid-foodhub I have tested the events of firebase analytics and it's working

**Comment by rizki-tabist** [comment]
is it required to update the  `@react-native-firebase/app` to `19.x.x` as well? mine is still `17.x.x`

**Comment by sajid-foodhub** [comment]
> @sajid-foodhub Thank you for your help!
> 
> The only problem on my side with iOS was the pod incompatibilities. I had to add these two lines to the Podfile to make it work on iOS: `pod 'FirebaseCore', :modular_headers => true` `pod 'GoogleUtilities', :modular_headers => true`

Hi @ThalesBMC Still i face issue while running IOS
Can you share your ruby and node version that you used ?

**Comment by ThalesBMC** [comment]
> is it required to update the `@react-native-firebase/app` to `19.x.x` as well? mine is still `17.x.x`

I have updated mine. 
I'm not sure if it's required, but I would recommend it.

**Comment by ThalesBMC** [comment]
> > @sajid-foodhub Thank you for your help!
> > The only problem on my side with iOS was the pod incompatibilities. I had to add these two lines to the Podfile to make it work on iOS: `pod 'FirebaseCore', :modular_headers => true` `pod 'GoogleUtilities', :modular_headers => true`
> 
> Hi @ThalesBMC Still i face issue while running IOS Can you share your ruby and node version that you used ?

Node: v16
Ruby: 2.7.4
Cocoapods: 1.11.2

**Comment by mikehardy** [comment]
Hi there - current versions support things, so I'm going to close this as it will not result in a change in this repository so it is not actionable, that shouldn't stop anyone from helping anyone though, comments are open!

I will say that:
- current versions of react-native-firebase are going to be strictly required because you'll need the privacy manifest work done for iOS or you simply won't be able to upload a build - 10.25.0 of firebase-ios-sdk was the first version I think everyone was comfortable with, which implies v20.0.0+ here
- modular_headers workarounds **are not supported and will never be supported** - I cannot recommend this path to anyone. I know it is a hot topic and lots of people do it but it is also a frequent cause of sleeper build problems that show up later after you've forgotten you were using a supported workaround
