### ISSUE TITLE
[🐛] import { firebase } from '..';  |  Returns a Messaging instance for the given app. (messaging/analytics)

### ISSUE THREAD

**Issue by kathrynowy** [invertase/react-native-firebase#7813]
node_modules/@react-native-firebase/messaging/modular/index.js
Unable to resolve module ../../../../.. from XXXX/node_modules/@react-native-firebase/messaging/modular/index.js: 

XXXX/node_modules/@react-native-firebase/messaging/modular/index.js: None of these files exist: * ..
> 1 | import { firebase } from '..';  |  * Returns a Messaging instance for the given app.

    "react-native": "0.73.6",
    "@react-native-firebase/app": "19.1.2",
    "@react-native-firebase/messaging": "19.1.2"
    
    Error is in this file:
    node_modules/@react-native-firebase/messaging/modular/index.js
    1st line import { firebase } from '..';
    
    
    **Fixed like this:**
    import { firebase } from '../lib';
   
   
   
   
   UPD:
   
   same for analytics
    [Error: undefined Unable to resolve module ../../../../../.. from XXXX/node_modules/@react-native-firebase/analytics/lib/modular/index.js:

**Comment by mikehardy** [comment]
I'm sorry, I don't understand the problem.
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

If you are still having an issue, you can open a new issue here and please include the information we request in the template vs deleting it, keeping in mind the information in the two links above

**Comment by judeProground** [comment]
Hello, I am experiencing the same issue and am currently using a patch-package to address it. 
Do you know the cause of this problem?
