### ISSUE TITLE
[🐛] Firebase Performance Monitoring Dashboard Doesn't Display CPU and Memory Usage for User Sessions

### ISSUE THREAD

**Issue by ydatech** [invertase/react-native-firebase#7818]
## Issue

Hi everyone,
I recently started using @react-native-firebase/perf@20.0.0 for performance monitoring in an application built with Expo SDK 50. However, on the Firebase dashboard, user session details such as CPU and Memory usage for a custom trace are not showing up. Instead, there's a message indicating that I need to upgrade the SDK (Firebase SDK).

I'm uncertain if this is an issue that requires me to upgrade or if I simply need to wait for 24 hours or more for the data to appear. Has anyone else experienced the same problem? Any assistance would be greatly appreciated.

Please see the attached screenshot for reference.
<img width="1144" alt="Screenshot 2024-06-01 at 01 12 34" src="https://github.com/invertase/react-native-firebase/assets/5019283/5d4210c1-ad74-4e8b-b74e-aaaf708e00c8">

Thank you.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/app": "^20.0.0",
    "@react-native-firebase/crashlytics": "^20.0.0",
    "@react-native-firebase/perf": "^20.0.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Did the data show up after a delay or is this still an issue for you? 

> I'm uncertain if this is an issue that requires me to upgrade or if I simply need to wait for 24 hours or more for the data to appear. Has anyone else experienced the same problem? Any assistance would be greatly appreciated.

**Comment by ydatech** [comment]
This is no longer an issue. The data has now appeared in the Firebase console (I might need to wait for some days to have enough data to display). Thank you. I will close this issue.
