### ISSUE TITLE
No timeout in Firestore persist whitout internet.

### ISSUE THREAD

**Issue by lucasmathioni** [invertase/react-native-firebase#782]
When trying to update a doc in the firestore, when the device is without internet, there is no timeout or return, but in auth there is an exception (auth / unknown).
How do I get the firestore to return something like this?

Application Target Platform: Ios/Android
Development Operating System: Windows 10
React Native version: 0.50.3
RNFirebase Version: 3.1.0
Firebase Module: Firestore

**Comment by petermiles** [comment]
Are you enabling offline persistence? 

More info here: https://firebase.google.com/docs/firestore/manage-data/enable-offline

**Comment by chrisbianca** [comment]
@lucasmathioni Firestore has persistence enabled by default, so it will work offline. You should still get a response in the `.then()` part of the update? Are you saying this isn't the case?

**Comment by chrisbianca** [comment]
Closing due to lack of response - please re-open with further details if this is still an issue.
