### ISSUE TITLE
[📚] Push notification iOS entitlements

### ISSUE THREAD

**Issue by christopherPiero** [invertase/react-native-firebase#7825]
## Documentation Feedback

Since the SDK51 expo update, the changelog mentions the following:

> Notifications entitlement is no longer always added to iOS projects during prebuild: No changes are required if you use expo-notifications. If your project uses push notifications but does not use the expo-notifications package, you may need to add the aps-environment entitlement to your app config

So, to use react-native-firebase/messaging, we need to add the following code to the iOS configuration :

in app.config.ts :
```
“ios”: {
      “entitlements”: {
        “aps-environment” : “production”.
      },
 },
```

see :
- https://github.com/expo/expo/issues/27668
- https://expo.dev/changelog/2024/05-07-sdk-51#deprecations-renamings-and-removals

It would be good to have this detail in the documentation.

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! If you click the edit link at the top right of any documentation page you can propose what you think is needed, it's a quick process with the github web UI and I'd be happy to merge something. I don't use Expo myself though so I'm not really qualified other than QA to make sure it fits with the project here, it really needs an Expo user that proposes something they know works to do it

**Comment by christopherPiero** [comment]
https://github.com/invertase/react-native-firebase/pull/7842
