### ISSUE TITLE
In Android, Firebase mobile number authentication is validating apart from sending wrong credential(OTP).

### ISSUE THREAD

**Issue by MynkPaliwal** [invertase/react-native-firebase#7827]
Description of the issue here

```
firebase.auth().signInWithCredential(credential: AuthCredential)

export interface AuthCredential {
    providerId: string;
    token: string;
    secret: string;
}
```

Sending wrong secret value(OTP) in credential of firebase.auth().signInWithCredential(). But then also it was authenticating the user and not giving any error.

**Comment by mikehardy** [comment]
Hi there, I'm going to close this - but if it is still happening with current versions can you open a new issue while respecting the issue template and including an example of code that will reproduce the problem?
