### ISSUE TITLE
In Android, sending the wrong secret value(OTP) for firebase mobile number authentication is validating the user.

### ISSUE THREAD

**Issue by MynkPaliwal** [invertase/react-native-firebase#7831]
## Issue

User is getting authenticate apart from sending wrong secret value in firebase auth signInWithCredential().

Case: It will only happen when the user enters the wrong OTP on the same device from which it is sent.

```
firebase.auth().signInWithCredential(credential: AuthCredential)

export interface AuthCredential {
    providerId: string;
    token: string;
    secret: string;
}
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"react": "18.2.0",
"react-native": "0.71.0",
 "@react-native-firebase/auth": "^14.11.0",
"@react-native-firebase/app": "^14.11.0",
"@react-native-firebase/analytics": "^14.11.0"
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
buildscript {
    ext {
        buildToolsVersion = "33.0.1"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        supportLibVersion = "30.0.3"
        kotlinVersion = "1.6.21"

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"        
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:5.0.1")
        classpath 'com.google.gms:google-services:4.3.14'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.0'
        classpath 'com.google.firebase:perf-plugin:1.4.2'
    }
}
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by snowluminum** [comment]
Maybe it is related to automatic android auth?

![image](https://github.com/invertase/react-native-firebase/assets/45245153/d023b691-ece6-4a6a-8b81-724d85ba8e08)

**Comment by mikehardy** [comment]
very well could be, I imagine there would be some evidence of this in logcat (`adb logcat` to watch on device while things are happening...)
