### ISSUE TITLE
[🐛] 🔥`Filter.and` and `Filter.or` should be able to accept `Filter.and` or `Filter.or` as their argument

### ISSUE THREAD

**Issue by thisisgit** [invertase/react-native-firebase#7850]
## Issue

According to the [document](https://rnfirebase.io/firestore/usage#filtering) `Filter.or` and `Filter.and` should be able to accept themselves as arg:
```typescript
const snapshot = await firestore()
  .collection('Users')
  .where(
    firestore.Filter.or(
      firestore.Filter.and(firestore.Filter('user', '==', 'Tim'), firestore.Filter('email', '==', 'tim@example.com')),
      firestore.Filter.and(firestore.Filter('user', '==', 'Dave'), firestore.Filter('email', '==', 'dave@example.com')),
    ),
  )
  .get();
```
(Note that I've updated `Filter` to `firestore.Filter` due to [this issue](https://github.com/invertase/react-native-firebase/issues/7134))

However this throws type error:
<img width="749" alt="스크린샷 2024-06-19 오후 4 09 52" src="https://github.com/invertase/react-native-firebase/assets/13231564/0c1f0d4b-a61b-42ef-9ade-5b7411d9ff32">

This is happening because type of `Filter.or` and `Filter.and` only accepts type of `QueryFilterConstraint` while what they're returning is type of `QueryCompositeFilterConstraint`:
https://github.com/invertase/react-native-firebase/blob/ca07cadd592487102b035a24b55f593f065ef4a5/packages/firestore/lib/index.d.ts#L71-L87

So to address this issue, their type needs to be adjusted to accept either `QueryFilterConstraint` or `QueryCompositeFilterConstraint`:
```typescript
export interface FilterFunction {
    /**
     * The Filter function used to generate an instance of Filter.
     * e.g. Filter('name', '==', 'Ada')
     */
    (fieldPath: keyof T | FieldPath, operator: WhereFilterOp, value: any): QueryFilterConstraint;
    /**
     * The Filter.or() static function used to generate a logical OR query using multiple Filter instances.
     * e.g. Filter.or(Filter('name', '==', 'Ada'), Filter('name', '==', 'Bob'))
     */
    or(...queries: (QueryFilterConstraint | QueryCompositeFilterConstraint)[]): QueryCompositeFilterConstraint;
    /**
     * The Filter.and() static function used to generate a logical AND query using multiple Filter instances.
     * e.g. Filter.and(Filter('name', '==', 'Ada'), Filter('name', '==', 'Bob'))
     */
    and(...queries: (QueryFilterConstraint | QueryCompositeFilterConstraint)[]): QueryCompositeFilterConstraint;
  }
```

This works as I tested by updating the file in `node_modules`. 
But will the change introduce any other issues that I'm not aware of?

---

## Project Files

Managed expo

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/analytics": "20.0.0",
"@react-native-firebase/app": "20.0.0",
"@react-native-firebase/app-check": "20.0.0",
"@react-native-firebase/auth": "20.0.0",
"@react-native-firebase/crashlytics": "20.0.0",
"@react-native-firebase/firestore": "20.0.0",
"@react-native-firebase/functions": "20.0.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `20.0.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Firestore`
- **Are you using `TypeScript`?**
  - `Y` & `5.3.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there 👋  our types had a slight divergence from the firebase-js-sdk types and the fix was to appropriately compose QueryFilterConstraint as being either QueryFieldFilterConstraint or QueryCompositeFilterConstraint so that the and/or (a Composite) was correctly known as a QueryFilterConstraint and thus allowed as the constraint inside and/or again if needed

It should "just work" as the underlying SDKs should support it, I believe it was just a type divergence

It'll be out in the next release or you can try the patch-package set off the related PR here - feedback is always welcome from early testing https://github.com/invertase/react-native-firebase/actions/runs/9955468340
