### ISSUE TITLE
[📚] Documentation Issue Title - Keep facing  No Firebase App when using realtime database

### ISSUE THREAD

**Issue by DevTeamJML** [invertase/react-native-firebase#7855]
## Documentation Feedback

import firebase from "@react-native-firebase/database";

const reference = firebase
  .app()
  .database('https://<databaseName>.<region>.firebasedatabase.app/')

I have follow as above the guide but keep getting 

: No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()
---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Lyokone** [comment]
I'm not reproducing on my end this issue, could you provide a full sample to help debug?

**Comment by younes0** [comment]
I reproduced this error when I still had firebase-js RTDB calls.
Obviously, error disappeared after replacing all these calls by RNFB.
This issue could be closed.

**Comment by Lyokone** [comment]
Closing since this one is stale
