### ISSUE TITLE
goes to  first page after uploading image 

### ISSUE THREAD

**Issue by atchuthsai468** [invertase/react-native-firebase#787]
If i upload an image from gallery it
picking photos from gallery or taking a photo from camera  Redirecting to Homepage(without showing any error)

i'm using react-native-image-picker module
i tried to store image in firebase database

React Native version: 0.46.4
Platform: both
Development Operating System: MacOS,
Dev tools:Android Studio navigation crash for Android

**Comment by chrisbianca** [comment]
@atchuthsai468 This doesn't seem to be react-native-firebase specific. If you can identify an error from your native logs which shows that this is being caused by this library then please re-open with details.
