### ISSUE TITLE
error: package android.support.annotation does not exist import android.support.annotation.Keep;                

### ISSUE THREAD

**Issue by yernandus** [invertase/react-native-firebase#7870]
getting the error above when trying to build expo app with react native firebase. Plugins are configured. libraries that I use: 
  "@expo/metro-runtime": "~3.2.1",
    "@expo/react-native-action-sheet": "^4.1.0",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-firebase/app": "^20.1.0",
    "@react-native-firebase/auth": "^20.1.0",
    "@react-native-firebase/crashlytics": "^20.1.0",
    "@react-native-firebase/firestore": "^20.1.0",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "@reduxjs/toolkit": "^2.2.5",
    "expo": "~51.0.17",
    "expo-build-properties": "~0.12.3",
    "expo-camera": "~15.0.12",
    "expo-dev-client": "~4.0.19",
    "expo-image-picker": "~15.0.6",
    "expo-location": "~17.0.1",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.6",
    "geolib": "^3.3.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.2",
    "react-native-firebase": "^5.6.0",
    "react-native-gesture-handler": "^2.16.2",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-maps": "1.14.0",
    "react-native-paper": "^5.12.3",
    "react-native-reanimated": "~3.10.1",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-safe-area-context": "^4.10.1",
    "react-native-screens": "^3.31.1",
    "react-native-web": "~0.19.10",
    "react-redux": "^9.1.2",
    "redux": "^5.0.1",
    "redux-persist": "^6.0.0"

**Comment by Lyokone** [comment]
Hello, I see that you have both
```
react-native-firebase
@react-native-firebase/app
```

Could you remove the former and try again?

**Comment by Lyokone** [comment]
Closing since stale
