### ISSUE TITLE
Crashed: com.google.firebase.crashlytics.ios.exception

### ISSUE THREAD

**Issue by Saalim95** [invertase/react-native-firebase#7871]
## Issue
We are getting this crash on Crashlytics Dashboard.
We are unable to reproduce it on our side. But in the stack trace seems like it came from Firebase Crashlytics SDK.

I am getting the following crash log from the Firebase crash analytics.
---

[io.shelfwatch.paralleldots_issue_beec17a892773a571365d17b9b61e09e_crash_session_24c4864895f940e39b9a1adbc8ae66db_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/16093042/io.shelfwatch.paralleldots_issue_beec17a892773a571365d17b9b61e09e_crash_session_24c4864895f940e39b9a1adbc8ae66db_DNE_0_v2_stacktrace.txt)

#### `package.json`:

```json
    "react-native": "0.61.5",
    "@react-native-firebase/app": "^14.2.2",
    "@react-native-firebase/crashlytics": "^14.2.2"
```

**Comment by danieltgfischer** [comment]
+1

**Comment by Salakar** [comment]
👋 hey, the crash indicates that it's originating from the Firebase iOS SDK, could you raise this issue there; https://github.com/firebase/firebase-ios-sdk - React Native Firebase is a wrapper around these native SDKs.
