### ISSUE TITLE
Unexpected (not set) pages in (firebase) analytics

### ISSUE THREAD

**Issue by aaroncornelissen** [invertase/react-native-firebase#7877]
## Issue

We're experience a lot of (not set) pages in our analytics reports and we don't know why. I've used debugView for both android and iOS to debug if some events are logged without screen name. During the debugging nothing without screen name where logged. 

In my code it is impossible to fire a logScreenView event without a title because the function has an early return if the title is empty. 

Automatic screenView is logging is already disabled. So I don't know how I can solve this. 

![Screenshot 2024-07-05 at 10 04 25](https://github.com/invertase/react-native-firebase/assets/57479235/538de686-02b9-413b-b86c-b92e6ab95875)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

NavigationContainer

```
  const onNavigationStateChange = async () => {
    const previousRouteName = routeNameRef.current;
    const currentRouteName = navigationRef?.getCurrentRoute()?.name;
    if (currentRouteName && previousRouteName !== currentRouteName) {
      logScreenView(
        currentRouteName as PageNames | StartupPageNames,
      );
      routeNameRef.current = currentRouteName;
    }
  };

  return (
    <NavigationContainer
      ref={navigationRef}
      onReady={onNavigationContainerReady}
      onStateChange={onNavigationStateChange}>
      {children}
    </NavigationContainer>
  );
```

Custom Analytics hook
```
  const logScreenView = (
    pageName: PageNames | keyof typeof StartupPageNames,
  ) => {
    const {title, contentType} = getPageDetails(
      pageName,
      isStartupFlowCompleted,
    );

    if (!title) {
      return;
    }

    dispatch(setPageDetails({title, contentType}));
    analytics()
      .logScreenView({
        screen_name: title,
        content_group: contentType,
      })
      .catch((error: any) => {
        logWarning('Screen view could not be logged to analytics', error);
      });
  };

```
#### `package.json`:

```json
    "@react-native-firebase/analytics": "^19.2.2",
    "@react-native-firebase/app": "^19.2.2",
    "@react-native-firebase/messaging": "^19.2.2",
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "google_analytics_automatic_screen_reporting_enabled": false,
    "analytics_auto_collection_enabled": false
  }
}

```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
  OS: macOS 14.5
  CPU: (12) arm64 Apple M2 Pro
  Memory: 55.33 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.0/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 33.0.1
      - 34.0.0
    System Images:
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.8
    wanted: 0.73.8
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

- **Platform that you're experiencing the issue on**:
  - [X ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [X ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Lyokone** [comment]
Hello @aaroncornelissen, I'm not reproducing this issue. Could you provide a full reproduction example showing this bug? Thanks

**Comment by Lyokone** [comment]
Closing since stale

**Comment by aaroncornelissen** [comment]
Thank you for your response. I was not able to respond shortly on your message because of the summer holiday. 

A colleague of my investigated the issue in our project and made some adjustments to my code. It looks like the adjustments solved the problem. He did two things: 

- He transformed all log functions to async functions and awaited the promise to log the data to firebase.
- He changed the parameter name 'screen_name' at click events to 'click_screen_name'.
