### ISSUE TITLE
[Question] making email verification / password-reset links a dynamic links

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#789]
Hey guys, this is more of a question rather than an issue, I hope this doesn't pollute the issue list, but thought it would be good for future searches.

You have this section in your documentation: https://rnfirebase.io/docs/v3.2.x/auth/reference/ActionCodeSettings

This was mentioned in
https://rnfirebase.io/docs/v3.2.x/auth/reference/User#sendEmailVerification

Am I correct assuming that assuming that passing `ActionCodeSettings` to `sendEmailVerification` will make link user receives in an email a dynamic link and open it in the app? This is something I was trying to achieve for a while now and would like to understand if this is the best way to do it. If you have time could you please walk me through proper process to handle this?

If I am mistaken, is the best way to do this connected to following flow:

1) Create custom dynamic link in firebase
2) Add that dynamic link to email template in firebase
3) When user navigates to an app from email, get verification token and perform manual api validation?

**Comment by IljaDaderko** [comment]
Closing as I was able to find: https://firebase.google.com/docs/auth/web/passing-state-in-email-actions which outlines exactly what I was asking here.

**Comment by IljaDaderko** [comment]
@firemuzzy I only tested with ios ones, but yeh. firebase guide I mention above was pretty much all I was missing (assumigh you have set up dynamic links successfully prior.)

**Comment by firemuzzy** [comment]
Thanks @IljaDaderko figure out the dynamic link stuff, google's docs are confusing as usual. Also thank you for your your tip in #826 to use the react native's build in Linking (https://facebook.github.io/react-native/docs/linking.html), I was also having issues with the url open action not getting picked up consistently
