### ISSUE TITLE
[📚] Documentation Issue Title - Links within the npm site need to be modified.

### ISSUE THREAD

**Issue by hanseulhee** [invertase/react-native-firebase#7890]
## Documentation Feedback

hello! I am using the package well.
I saw the package on [the npm site](https://www.npmjs.com/package/react-native-firebase), but when I go to the GitHub link, 404 appears.

<img width="70%" alt="스크린샷 2024-07-10 오후 8 13 35" src="https://github.com/invertase/react-native-firebase/assets/63100352/bfa33ee2-0b4f-4831-a52c-8f5193cd4e85" />

Accordingly, it seems that the existing link should be changed from https://github.com/invertase/react-native-firebase/tree/main/packages/mlkit to https://github.com/invertase/react-native-firebase.

thank you 🚀

**Comment by Lyokone** [comment]
<img width="1209" alt="Screenshot 2024-07-16 at 09 39 35" src="https://github.com/user-attachments/assets/1bc8c8d7-1544-42b1-bc04-a96612212203">

Hello, as stated by the red banner, you are referring to a deprecated package. We will not be updating this.
