### ISSUE TITLE
RNFirebase seems to only work from inside firebase initialization file

### ISSUE THREAD

**Issue by akshetpandey** [invertase/react-native-firebase#79]
I am not sure what is causing this and since I am not able to narrow it any further I am asking here for help. For some reason I cannot get firebase to work in any of my Components...

`App/Services/Firebase.js`
```javascript
import RNFirebase from 'react-native-firebase'

const firebase = RNFirebase.initializeApp({
  debug: __DEV__ ? '*' : false,
  errorOnMissingPlayServices: false,
  persistence: false
})

firebase.database()
  .ref('stories')
  .on('value', (snapshot) => {
    console.log('got value in firebase.js')
  });

export default firebase
```

`App/Containers/App.js`
```javascript
import React from 'react'
import { Provider, StatusBar } from 'react-redux'
import RootContainer from './RootContainer'
import createStore from '../Redux'
import firebase from '../Services/Firebase'

class App extends React.Component {
  constructor(props) {
    super(props)

    console.log('constructor')
    firebase.database()
      .ref('stories')
      .on('value', (snapshot) => {
        console.log('got value in app.js constructor')
      });
  }

  componentWillLoad() {
    console.log('componentWillLoad')
    firebase.database()
      .ref('stories')
      .on('value', (snapshot) => {
        console.log('got value in app.js componentWillLoad')
      });
  }

  render () {
    return (
      <Provider store={store}>
        <RootContainer />
      </Provider>
    )
  }
}

export default App

```

I only see the log from firebase.js. The logs I get are:
got value in firebase.js
constructor
componentWillLoad

The on events inside app.js are never triggered. But the on event inside firebase.js works fine. Any help would be very much appreciated.
I am running ` "react-native-firebase": "^1.0.0-alpha13"` and `Firebase/Core (3.17.0)`

**Comment by chrisbianca** [comment]
@akshetpandey I think your method should be `componentWillMount` not `componentWillLoad`

**Comment by akshetpandey** [comment]
Oops, but changing that didn't help either... That was a typo in the minimum repro case I created, the full app was using the right function name.

**Comment by chrisbianca** [comment]
If you remove the `.on()` call from firebase.js does it work in your component?

There was a known issue prior to `1.0.0-alpha13` which meant that a listener would only fire once on a database ref, and I just want to rule out that for some reason you're not running the latest code.

**Comment by akshetpandey** [comment]
Didn't fix app.js calls. I also tried removing the method from the app.js constructor and only calling from `componentWillMount` and that didn't work either

**Comment by chrisbianca** [comment]
What happens if you change the `.on()` calls to `.once()`:

```
firebase.database()
      .ref('stories')
      .once('value').then(() => {
            console.log('Log statement');
      })
      .catch((err) => {
        console.error(err);
      });
```

**Comment by akshetpandey** [comment]
Inside `firebase.js`
![screen shot 2017-05-02 at 2 10 02 am](https://cloud.githubusercontent.com/assets/1213060/25611654/bb687d9c-2edc-11e7-97de-cacdee7fa6b7.png)

Inside `app.js`
![screen shot 2017-05-02 at 2 10 31 am](https://cloud.githubusercontent.com/assets/1213060/25611655/bb6bca92-2edc-11e7-87a5-e2d4f6987c58.png)

I noticed a difference when the function was called from inside firebase.js and from inside app.js.
In the first one I get logs about `adding reference.on 2 value` and `on() : 2 1 value` which is missing from the second test.

**Comment by chrisbianca** [comment]
I am completely lost as to why it would behave differently!

There's nothing I can see to explain why it wouldn't be called or show the logging statement you mentioned, so are you 100% sure that the `.on()` call in app.js is identical to the one in firebase.js?

You could try debugging and putting some breakpoints in the react-native-firebase js code to try and trace where it's not working properly?  `.on()` in `database/reference.js` would be a good start.

**Comment by Ehesp** [comment]
Inside of your `App/Services/Firebase.js` try removing the database call. Maybe since these are bundled up there's some weird race condition going on when the app loads.

**Comment by akshetpandey** [comment]
I have already tried that and that doesn't help. I have isolated the issue to a ListView, where commenting/uncommenting the ListView make the database call work/break. I am trying to create a minimum repro version of the app which will probably isolate the issue further. It's really perplexing.  I will post an update with min repo code included.

**Comment by Salakar** [comment]
@akshetpandey If that's the case then i'd imagine your ListView has maybe been implemented incorrectly and is blocking the React Native Bridge

**Comment by akshetpandey** [comment]
@Salakar  It looks like I cannot reproduce the issue when using react native 0.44.0. Earlier I was on 0.42.0 and I do see a commit in their changelog that mentions a native bridge deadlock fix. Closing the ticket because of this.
