### ISSUE TITLE
[Firebase Storage]: ref.getMetadata doesn't return property downloadURLs on iOS. returns relative url on Android

### ISSUE THREAD

**Issue by escobar5** [invertase/react-native-firebase#791]
### Issue

On iOS the getMetadata() object doesn't have the property downloadURLs

[Firebase docs](https://firebase.google.com/docs/reference/ios/firebasestorage/api/reference/Classes/FIRStorageMetadata#/c:objc(cs)FIRStorageMetadata(py)downloadURLs)

On Android it does return the property, but the url is relative (eg. /images/img.png)

I've tried getting the metadata using firebase's web sdk and it does returns the property and the url is absolute.

### Environment

1. Application Target Platform: Both

2. Development Operating System: macOS High Sierra

3. Build Tools: (not relevant)

4. React Native version: 0.51.0

5. RNFirebase Version: 3.2.2

6. Firebase Module: Storage

**Comment by chrisbianca** [comment]
@escobar5 have you tried using the ref's `getDownloadUrl()` method?

**Comment by escobar5** [comment]
@chrisbianca yes, but I need the updated metadata also, so it would be better to do just one request

**Comment by chrisbianca** [comment]
Ok, thanks for confirming - I've flagged it as a bug that we'll look at once we've got our messaging rewrite out of the way.

**Comment by Salakar** [comment]
Thanks for reporting this issue. We're aware that Storage has fallen behind slightly on React Native Firebase and would like to bring it up to speed again. I will close this issue for now and track it as well as other issues collectively over on the Storage improvements proposal to be addressed in a future release. See #1260

**Comment by Salakar** [comment]
@escobar5 confused as to where you're reading that `getMetadata()` has a `downloadURLs` property, none of the firebase docs for js, ios or android show that as existing:

https://firebase.google.com/docs/reference/ios/firebasestorage/api/reference/Classes/FIRStorageMetadata#file
https://firebase.google.com/docs/reference/js/firebase.storage.FullMetadata
https://firebase.google.com/docs/reference/android/com/google/firebase/storage/StorageMetadata

**Comment by escobar5** [comment]
I can't find it, maybe it was removed in some version, I looked into my code and I'm not using that property anymore. I'm constructing the URL like this:

```js
var uri = `https://firebasestorage.googleapis.com/v0/b/${metadata.bucket}/o/${encodeURIComponent(metadata.fullPath||metadata.name)}?alt=media`;
```

**Comment by Salakar** [comment]
@escobar5 ok I'll close this issue for now then. Thanks for your responses
