### ISSUE TITLE
[🐛] Bug Report Title - CHANGE ME 

### ISSUE THREAD

**Issue by RohovDmytro** [invertase/react-native-firebase#7915]
## Issue

The app check token update yield an error on Amazing Fire tablet.

````
instanceForAppCheck
      .getToken(false)
      .then((res) => {
        if (res.token.length > 0) {
          setIsVerified(true);
        }
      })
      .catch((err: any) => {
        console.log(err);
        setIsVerified(false);
      });
````

Part of the problem might be that Amazon tablet does not have pre-installed Google Play Store. So my user manually installed Google Play Store, then he installed my app, then the app fails to download the token.

I am not sure if that is an expected behaviour. In that case I'm not sure how to handle that. Should I just handler the error not avoid supporting this device or is it expected to work none of the less?

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/analytics": "20.2.1",
    "@react-native-firebase/app": "20.2.1",
    "@react-native-firebase/app-check": "20.2.1",
    "@react-native-firebase/auth": "20.2.1",
    "@react-native-firebase/crashlytics": "20.2.1",
    "@react-native-firebase/dynamic-links": "20.2.1",
    "@react-native-firebase/firestore": "20.2.1",
    "@react-native-firebase/functions": "20.2.1",
    "@react-native-firebase/perf": "20.2.1",
    "@react-native-firebase/remote-config": "20.2.1",
    "@react-native-firebase/storage": "20.2.1",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Lyokone** [comment]
It's probably due to the version of Google Play Services installed by your customer. I guess it's expected that App Check wouldn't work properly in such an environment. Unfortunately it's not something we will fix since directly, but you can open an issue on the Android Firebase Repository: https://github.com/firebase/firebase-android-sdk
