### ISSUE TITLE
[🐛] Error installing BoringSSL-GRPC (0.0.32) | after yarn add @react-native-firebase/firestore -> pod install

### ISSUE THREAD

**Issue by IamMasterWayne** [invertase/react-native-firebase#7942]
_[!] Error installing BoringSSL-GRPC
[!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/6v/jrlm3nwx7hvf4yyj1ytv7f580000gn/T/d20240726-17764-kj76h3 --template=

Cloning into '/var/folders/6v/jrlm3nwx7hvf4yyj1ytv7f580000gn/T/d20240726-17764-kj76h3'...
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 2915 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output_

 ```
    "react-native": "0.66.3",
    "@react-native-firebase/analytics": "^20.3.0",
    "@react-native-firebase/app": "^20.3.0",
    "@react-native-firebase/auth": "^20.3.0",
    "@react-native-firebase/crashlytics": "^20.3.0",
    "@react-native-firebase/firestore": "^20.3.0",
    "@react-native-firebase/functions": "^20.3.0",
    "@react-native-firebase/messaging": "^20.3.0",
    "@react-native-firebase/storage": "^20.3.0",

```

**Comment by Lyokone** [comment]
Hello @IamMasterWayne, it looks like a network related issue. Not much we can do on our end.

**Comment by Jerry8135** [comment]
i also face this problem still can not solve

**Comment by ZeeshanSatti798** [comment]
**1. Add BoringSSL-GRPC in pods:**
`pod 'BoringSSL-GRPC', :modular_headers => true`

**2. After Test target add the following:**
`post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'BoringSSL-GRPC'
          target.source_build_phase.files.each do |file|
            if file.settings && file.settings['COMPILER_FLAGS']
              flags = file.settings['COMPILER_FLAGS'].split
              flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
              file.settings['COMPILER_FLAGS'] = flags.join(' ')
            end
          end
        end
      end`

**Comment by mikehardy** [comment]
@ZeeshanSatti798 do not recommend anyone uses modular_headers here, that is an unsupported workaround and should never be recommended.
This is fixed by just updating to current gRPC so your comment will just lead people astray, I am hiding it.
