### ISSUE TITLE
[🐛] Bug Report SignInWithPhoneNumber Not working for Expo Dev Client

### ISSUE THREAD

**Issue by leeroyanesu** [invertase/react-native-firebase#7944]
## Issue

My current signinwithphonenumber is not returning an sms for the verfication code in Expo Dev Client (React Native)

<code>
{"errorCode": "auth/operation-not-allowed", "msg": "[auth/operation-not-allowed] This operation is not allowed. This may be because the given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.", "success": false}
</code>

I have enabled the phone signin provider and also have verified the SHA-1 & SHA-256 but still nothing seems to work, any suggestion what it might be. I have tried with the foreRecaptcha... and without but still returns the same Error.

RN Firebase Auth & App Version: 20.3.0
React Native: 0.74.2
Expo: 51.0.14

```
auth().settings.forceRecaptchaFlowForTesting = true;
    return auth().signInWithPhoneNumber(phoneNum).then((result) => {
        return { verificationID: result.verificationId, success: true }
    }).catch((error) => {
        console.log(error)
        const errorCode = error.code;
        return { errorCode: error.code, msg: error.message, success: false };
    })
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by russellwheatley** [comment]
Try redownloading you `google-services.json` and replace the old one.
