### ISSUE TITLE
Unable to Determine if Two FCM Tokens Belong to the Same Device

### ISSUE THREAD

**Issue by AmirDoreh** [invertase/react-native-firebase#7946]
### Description:

We are facing an issue where we need to determine if two FCM tokens are associated with the same device. Currently, we do not store device IDs or any other metadata that can directly link tokens to a single device.

### Problem:

We have an array of FCM tokens and need to ascertain whether any of these tokens are related to the same device. Directly from the FCM tokens, there is no inherent way to determine if they are from the same device, as tokens do not carry identifiable information about the device or user.

### Request

Even after ensuring that each FCM token is unique, some devices receive more than one notification. We need a solution to understand if two different tokens are related to one single device

**Comment by russellwheatley** [comment]
Hey @AmirDoreh - As far as I'm aware, this isn't possible. You could reach out to Firebase support and see if there is a solution. But I'd recommend devising a solution where you can associate a token with a user in your backend setup.
