### ISSUE TITLE
[🐛] Expo + Authentication - `No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()`

### ISSUE THREAD

**Issue by loyddaniels** [invertase/react-native-firebase#7947]
## Issue

When following the documentation for authentication I get the error `No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()`
<img width="318" alt="image" src="https://github.com/user-attachments/assets/2ca243a8-4bbe-43cb-a338-70bd09b2c3d0">

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### App.tsx
import * as React from 'react';
import { Text } from 'react-native';
import auth from '@react-native-firebase/auth';

export default function App() {
    const user = auth().currentUser;

    if (!user) {
        return <Text>Please login</Text>;
    }

    return <Text>Welcome {user.email}</Text>;
}

#### `package.json`:

```json
{
  "name": "auth",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-firebase/app": "^20.3.0",
    "@react-native-firebase/auth": "^20.3.0",
    "expo": "~51.0.22",
    "expo-build-properties": "~0.12.3",
    "expo-dev-client": "~4.0.20",
    "expo-status-bar": "~1.12.1",
    "firebase": "^10.12.4",
    "react": "18.2.0",
    "react-native": "0.74.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "typescript": "^5.1.3"
  },
  "private": true
}
```

#### `firebase.json` for react-native-firebase v6:

```json

```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

I'm using expo

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 ERROR  Error: No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()
```

- **Platform that you're experiencing the issue on**:
  - [x] expo
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `20.3.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `auth`
- **Are you using `TypeScript`?**
  - Yes, 5.5.4

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by russellwheatley** [comment]
Seems unlikely something so fundamental to React Native Firebase is broken. Please provide a repo with [minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example) to illustrate this behaviour. i.e app + auth Firebase dependencies.

**Comment by Bohooslav** [comment]
Any progress? I also have this issue.

**Comment by anthlasserre** [comment]
Can you share your `app.json` ? You have probably forgotten to add the Firebase libraries within the Expo plugins.

```json
{
  ...
  "plugins": [
    "@react-native-firebase/app",
    "@react-native-firebase/analytics"
  ],
  ...
}
```

**Comment by Bohooslav** [comment]
Some of the reasons may be unmatching `aplicationId` package name of the app. Also in my case, am building replacement for an old xamarine app, I have to add new SHA1 keys of my new keystore to Firebase project but for some reason Firebase doesn't refresh the `google-service.json` file and it just wont work with new keystore, while I have no access to the old one.  These are reasons I faced.
