### ISSUE TITLE
Firebase not working on Oneplus 5t Android 8.0

### ISSUE THREAD

**Issue by hkxicor** [invertase/react-native-firebase#795]
### Issue
Firebase database not fetching data on Oneplus 5t Android 8.0
### Environment

1. Application Target Platform: Android 8.0

2. Development Operating System: Mac OS

3. Build Tools: buildToolVersion 26.0.1

4. React Native version:  0.49.5

5. RNFirebase Version: 3.1.0

6. Firebase Module: database

**Comment by Salakar** [comment]
@hkxicor this is most likely down to an out of date Google Play Services installation, try update it

**Comment by hkxicor** [comment]
@Salakar will update hare after updating **GooglePlayService** version

**Comment by chrisbianca** [comment]
Closing due to lack of response - please re-open if the above solution doesn't fix it.

**Comment by skfaisal93** [comment]
My play service is updated and I am facing the same issue with firebase notification.

When I swipe app to close it, I stopped getting notification.

**Comment by hkxicor** [comment]
@chrisbianca @Salakar I am still getting the same problem in **One Plus 5t** and some other Chinese devices even if play services are updated

**Comment by skfaisal93** [comment]
I found that with Chinese devices, FCM does not work according to their behaviour.

They said that in new version of FCM, they will fix the issue but they have not specified date.

Looking for alternative of FCM

**Comment by amrita019** [comment]
Any solutions to this?

**Comment by devanshAppiness** [comment]
Even i am facing this issue ! any solutions ?

**Comment by mikehardy** [comment]
https://dontkillmyapp.com/ - OnePlus is a bad vendor. They break Android APIs. Nothing the library can do. Direct your users to the settings pages (there's code on the net for this) and have them turn off battery saving, maybe pin your app if it's that important to them.

**Comment by mikehardy** [comment]
(I will admit to being a happy OnePlus 5 user though, I like their policy on rooting and custom ROMs, but when I use OxygenOS I have to be careful with settings so the apps I care about continue to run)

**Comment by devanshAppiness** [comment]
@mikehardy  moreover they have dissabled wireless debugging and it really sucks

**Comment by mikehardy** [comment]
But you can put LineageOS on there and maintain your warranty :-). Pluses and minuses, but yeah, not awesome.
