### ISSUE TITLE
White Screen Of death in release build at the time of crash and no logs in firebase crashlytics

### ISSUE THREAD

**Issue by pkpardeep482** [invertase/react-native-firebase#7966]
**Problem**
In release app. i pressed "click me to crash button" and instead of crashing the app, it was a blank white screen. Also crashlytics didnt received any logs for same. 

**Info**
- OS: Android 
-  "react": "18.2.0",
-  "react-native": "0.74.5"
-    newArchitectureEnabled : true

**Additional Info**
- Everything works fine when i disable new architecture.

**Code**
 ```
let name = undefined
  const setName = () => {
    name.dfscxjcmkwdljfckl =1
  }
  return (
    <SafeAreaView style={backgroundStyle}>
     <TouchableOpacity onPress={setName}>
       <Text>Click me to crash</Text>
     </TouchableOpacity>
    </SafeAreaView>
  );
```
  
  
**dependencies** 

"@react-native-firebase/app": "20.3.0",
"@react-native-firebase/crashlytics": "20.3.0",

**Comment by russellwheatley** [comment]
Hey @pkpardeep482 - is the screen white before pressing the crash button? or does it render as white before any user interaction?
