### ISSUE TITLE
[🐛] Crash in iOS 17 when a push notification is received

### ISSUE THREAD

**Issue by mykel-unwritten** [invertase/react-native-firebase#7981]
## Issue

No crash when launching the app, the issue only happens when receiving one

`react-native`: 0.73.7
`react-native-firebase/messaging`: 12.9.3 (also tried upgrading to the latest)
other firebase libs: app, crashlytics, analytics, dynamic-links

firebase crash log:
          Crashed: com.google.firebase.messaging.database.rmq
0  CoreFoundation                 0x6bac __CFStringChangeSizeMultiple + 224
1  CoreFoundation                 0x6920 __CFStringAppendBytes + 548
2  CoreFoundation                 0x37114 __CFStringAppendFormatCore + 9172
3  CoreFoundation                 0x348e0 _CFStringCreateWithFormatAndArgumentsReturningMetadata + 184
4  CoreFoundation                 0x3481c _CFStringCreateWithFormatAndArgumentsAux2 + 44
5  Foundation                     0x242e4 +[NSString stringWithFormat:] + 68
6  Project                        0x5dee0 __52-[FIRMessagingRmqManager querySyncMessageWithRmqID:]_block_invoke + 282 (FIRMessagingRmqManager.m:282)
7  libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
8  libdispatch.dylib              0x136f8 _dispatch_sync_invoke_and_complete_recurse + 64
9  libdispatch.dylib              0x13178 _dispatch_sync_f_slow + 176
10 Project                        0x5de28 -[FIRMessagingRmqManager querySyncMessageWithRmqID:] + 322 (FIRMessagingRmqManager.m:322)
11 Project                        0x5f69c -[FIRMessagingSyncMessageManager didReceiveAPNSSyncMessage:] + 63 (FIRMessagingSyncMessageManager.m:63)
12 Project                        0x4e308 -[FIRMessaging appDidReceiveMessage:] + 360 (FIRMessaging.m:360)
13 Project                        0x5c45c FCMSwizzleWillPresentNotificationWithHandler + 479 (FIRMessagingRemoteNotificationsProxy.m:479)
14 Project                        0x102f0c -[NotifeeCoreUNUserNotificationCenter userNotificationCenter:willPresentNotification:withCompletionHandler:] + 164 (NotifeeCore+UNUserNotificationCenter.m:164)
15 Shake                          0xbf6ec -[SHKNotificationProxy userNotificationCenter:willPresentNotification:withCompletionHandler:] + 308
16 Project                        0x5c478 FCMSwizzleWillPresentNotificationWithHandler + 482 (FIRMessagingRemoteNotificationsProxy.m:482)
17 UIKitCore                      0x4c4ba0 -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:completion:] + 397740
18 UIKitCore                      0x237f98 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 308
19 UIKitCore                      0x302e7c -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 4309402744
20 UIKitCore                      0x302a5c -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 397740
21 FrontBoardServices             0x66e4 -[FBSScene updater:didUpdateSettings:withDiff:transitionContext:completion:] + 308
22 FrontBoardServices             0x16844 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke_2 + 4309402744
23 FrontBoardServices             0x166cc -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 397740
24 FrontBoardServices             0x1b7fc __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke + 308
25 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 4309402744
26 libdispatch.dylib              0x786c _dispatch_block_invoke_direct + 397740
27 FrontBoardServices             0x17d58 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 308
28 FrontBoardServices             0x17cd8 -[FBSMainRunLoopSerialQueue _targetQueue_performNextIfPossible] + 4309402744
29 FrontBoardServices             0x17bb0 -[FBSMainRunLoopSerialQueue _performNextFromRunLoopSource] + 397740
30 CoreFoundation                 0x56834 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 308
31 CoreFoundation                 0x567c8 __CFRunLoopDoSource0 + 4309402744
32 CoreFoundation                 0x54298 __CFRunLoopDoSources0 + 397740
33 CoreFoundation                 0x53484 __CFRunLoopRun + 308
34 CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 4309402744
35 GraphicsServices               0x11a8 GSEventRunModal + 397740
36 UIKitCore                      0x40a90c -[UIApplication _run] + 308
37 UIKitCore                      0x4be9d0 UIApplicationMain + 4309402744
38 Project                        0x43a4 main + 15 (main.m:15)
39 ???                            0x1caabde4c -[SHKNotificationProxy userNotificationCenter:willPresentNotification:withCompletionHandler:] + 308
        

Describe your issue here

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by russellwheatley** [comment]
In foreground, background and terminated (opening app with notification), I did not experience this issue. Need an [mcve](https://stackoverflow.com/help/minimal-reproducible-example) before I look at this issue again. It is almost always a configuration issue.

**Comment by mykel-unwritten** [comment]
hi @russellwheatley thanks for your response, at the moment i can't provide an mcve, but what's concerning for us is it seems it doesn't even reach the JS side, we have removed any JS code related to event listeners but we haven't removed the messaging library, and still it crashes when it receives a push notification, even coming from firebase messaging console

**Comment by mykel-unwritten** [comment]
hi @russellwheatley no worries, totally understand. Yea it is very odd, and it seems to only happen on ios 17 (based on crashlytics). Does certificates and profiles cause this?

**Comment by russellwheatley** [comment]
I just noticed this in the logs:
```
14 Project 0x102f0c -[NotifeeCoreUNUserNotificationCenter userNotificationCenter:willPresentNotification:withCompletionHandler:] + 164 (NotifeeCore+UNUserNotificationCenter.m:164)
```

There is actually no logs in that crash report that indicates it is from RNFB messaging. I think you ought to open an issue or have a look at any similar issues on that repository: https://github.com/invertase/notifee

Hope that helps 🙏
