### ISSUE TITLE
[🐛] @react-native-firebase/firestore@20.4.0 - Is Breaking Change

### ISSUE THREAD

**Issue by ChromeQ** [invertase/react-native-firebase#7986]
## Issue
Upgrading to `@react-native-firebase/firestore@latest` (currently v20.4.0) breaks expo development client app. This seems like a breaking change and not a minor release.

Describe your issue here
I recently updated all `@react-native-firebase` dependencies and my app broke 😿
Narrowed down update change to `@react-native-firebase/firestore@20.4.0`

After some restarts I got some error message saying something about expecting 9 inputs but got 10 or vice versa. (unfortunately I cannot recreate with all my debug efforts) with the `GetCollection` method, which sounds very firestore-y to me.

<p>The expo development build was initially build when react-native-firebase was v20.1.0
With this latest update it is broken and requires a new full build (I use expo)<br>
imo a minor release should not be breaking the existing expo builds (native code "embedded" into the app as far as I understand it)
This minor release has resulted in me requiring a new development build (which is fine except I don't expect it with a minor update)
</p>
---

## Project Files
No ios/android project files as I am using expo

**Comment by ChromeQ** [comment]
Downgrading to `v20.3.0` means everything works and no crash. If I upgrade all firebase packages to latest (v20.4.0) and leave firestore at the previous version then it works ok. This is how I determined that firestore is the issue.

**Comment by russellwheatley** [comment]
Hi @ChromeQ - I don't agree that this is a breaking change. You did not have to update your source code, just complete a rebuild of your app.

**Comment by ChromeQ** [comment]
Yes I guess it isn't technically a breaking change. But as I utilise over the air updates I tend to avoid having to rebuild the app and release a new version to the app store. For this reason I call it a "breaking change" when I can't use OTA to update it. 

I guess this is more of a question of what the versioning strategy is with RNFB and what constitutes a breaking change vs a feature release?

**Comment by russellwheatley** [comment]
If you have to manually update your source code, we consider that. a breaking change. e.g. API removed, API has changed or package version (not RNFB) has to be bumped to make your app work. Things off that nature.

Rebuilding your app is not a breaking change. If you don't rebuild your app, you're essentially using cached code of the previous version.
