### ISSUE TITLE
putFile to Storage: Keep getting 'filePath replace is not a function

### ISSUE THREAD

**Issue by thedc89** [invertase/react-native-firebase#799]
I try baisc putFile with image taken with camera:

```
const filePath = { uri: response.uri };

const storage = firebase.storage();

const storageRef = storage.ref();

const imageRef = storageRef.child('images/space.jpg');

imageRef.putFile(filePath)
```

I keep getting the following message in simulator

> filePath.replace is not a function. (In filePath replace('file://:' ''), 'filePath.replace' is undefined

I failed to find any similar issue here. 
I'm quite new to react native as well, so maybe the problem lies elsewhere?

### Environment

1. Application Target Platform: 
iOS

2. Development Operating System: 
Mac OS High Sierra

3. Build Tools: 
command line
XCode

4. React Native version: 
react-native-cli: 2.0.1
react-native: 0.52.2

5. RNFirebase Version: 
"react-native-firebase": "^3.2.3",

6. Firebase Module: 
Storage

**Comment by Salakar** [comment]
@thedc89 putFile expects a string of the full filePath as the first argument - you're sending it an object.

**Comment by thedc89** [comment]
Thank you, in fact adding uri to filePath solved the issue
`imageRef.putFile(filePath.uri)`
