### ISSUE TITLE
[🐛] Error on Mac Catalyst - FirebaseFirestore has a minimum deployment target

### ISSUE THREAD

**Issue by tommycarpi** [invertase/react-native-firebase#7994]
I'm struggling with an error I seem not to be able to solve.

Context:
- React Native app that uses Firebase Auth and Firestore
- Firebase versione 20.4
- on iOS (both simulator and device) it works perfectly
- on mac Catalyst it does not compile

this is the error:
`Compiling for iOS 13.1, but module 'FirebaseFirestore' has a minimum deployment target of iOS 13.4: <...> /Build/Products/Debug-maccatalyst/FirebaseFirestore/FirebaseFirestore.framework/Modules/FirebaseFirestore.swiftmodule/arm64-apple-ios-macabi.swiftmodule`

I've tried everything, from changing the XCode version to 13.4, to specify it in the Podfile as specified here:

```
min_ios_versions_supported = ['13.4', min_ios_version_supported]
index_of_max = min_ios_versions_supported.each_with_index.max_by { |number, _| number.to_f }[1]
platform :ios, min_ios_versions_supported[index_of_max]

....

deployment_target = '13.4'

post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => true
    )
    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
          end
      end
      project.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
      end
    end
end
```

I've also tried to downgrade to v19.3, still the same issue.

Any help?

**Comment by russellwheatley** [comment]
Try this at top of file:
```ruby
platform :ios, '13.4'
```

**Comment by tommycarpi** [comment]
@russellwheatley unfortunately didn't work.
I tried to put it on top commenting my line:
`platform :ios, min_ios_versions_supported[index_of_max]
`
and then executing `pod install`

still same error when compiling Catalyst 🥲

**Comment by russellwheatley** [comment]
Have you cleaned Pods out? Try:

```bash
cd ios/
rm -rf Pods && rm Podfile.lock
pod install
```

**Comment by tommycarpi** [comment]
Tried but still.

But I think is a bug for Catalyst, I mean the version is correct here.

<img width="778" alt="Screenshot 2024-08-29 at 16 43 35" src="https://github.com/user-attachments/assets/c4888218-551a-48c2-b762-ccc5990aa7d5">

On iOS it works, on Catalyst throws this ...

<img width="539" alt="Screenshot 2024-08-29 at 16 44 56" src="https://github.com/user-attachments/assets/b669808c-646b-45a1-bffd-c48b3d880243">

**Comment by tommycarpi** [comment]
The issue was with the XCode Beta. Using XCode v15.4 does not cause the issue.

This one does instead, for unknown reasons.
 
<img width="518" alt="Screenshot 2024-08-30 at 00 44 50" src="https://github.com/user-attachments/assets/4dd36aad-c189-46cf-9a4f-ac6ad62b31e1">
