### ISSUE TITLE
Linking problem

### ISSUE THREAD

**Issue by lobo922** [invertase/react-native-firebase#8]
Hi,
I'm trying to do like the installation instructions says.
First i did:
npm i react-native-firebase --save
then:
react-native link react-native-firebase

and i get the following message:

`'yarn' is not recognized as an internal or external command,
operable program or batch file.
Scanning 557 folders for symlinks in D:\fbcounter\node_modules (19ms)
rnpm-install ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
Please file an issue here: https://github.com/facebook/react-native/issues

spawn UNKNOWN`

**Comment by rborn** [comment]
Do you have `yarn` installed on your system?

**Comment by lobo922** [comment]
I installed yarn, then i reinstalled the package again and when i try to link it i get the following message:
'Scanning 589 folders for symlinks in D:\xxx\node_modules (21ms)
rnpm-install ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
Please file an issue here: https://github.com/facebook/react-native/issues

spawn UNKNOWN'

**Comment by rborn** [comment]
mmm, no idea 😢

**Comment by Ehesp** [comment]
Try deleting your project fully and starting over. RN installs with yarn so might be an issue with the initial setup.

**Comment by lobo922** [comment]
I already tried to do that with no luck

**Comment by IljaDaderko** [comment]
This is not the issue with the project @lobo922 there is something wrong with yarn and it's npm installation, I had same issue today, you can solve it by following installation instructions for home brew they have on the website: https://github.com/yutin1987/react-native-bridge-firebase

Here are the steps to take for clean yarn re-install
1) `sudo npm uninstall -g yarn`
2) `brew update`
3) `brew install yarn`

Hope this help. If you don't use homebrew there are alternate methods mentioned in yarns install guide

**Comment by lobo922** [comment]
I managed to fix the issue with a different  way:
I went to my_project\node_modules\react-native-firebase\package.json and deleted the following lines:
"prelink": "node_modules/react-native-firestack/bin/prepare.sh",
"postlink": "node_modules/react-native-firestack/bin/cocoapods.sh"

**Comment by sandeep0607** [comment]
I got this error while running command for lining


rnpm-install ERR! Something went wrong while linking. Error: Expected "=" but "/" found.
Please file an issue here: https://github.com/facebook/react-native/issues

Expected "=" but "/" found.
help me
