### ISSUE TITLE
[🐛] Bug Report Title - Issues Related to Headless Mode

### ISSUE THREAD

**Issue by ccn-choi-sanghoon** [invertase/react-native-firebase#8004]
I am currently using React Native Firebase from "https://rnfirebase.io/". I have registered a foreground handler, and I confirmed that messages are received correctly while the app is in the foreground. However, after the app goes into the background and receives one message, the previously registered foreground handler gets disconnected and no longer functions.

As a temporary solution, I re-register the foreground handler within the background handler, and this allows it to work again when the app returns to the foreground. However, when calling UI-related APIs (such as alert), I receive a warning message saying "Tried to show an alert while not attached to an Activity." I suspect this happens because the app is running in headless mode when the handler is registered in the background, and thus UI processing is not possible.

I am wondering if there is a standard or recommended way to handle this issue, particularly with managing handlers in this scenario. Any guidance would be greatly appreciated.

**Comment by russellwheatley** [comment]
As [documentation describes](https://rnfirebase.io/messaging/usage#background--quit-state-messages), you need to register your background message handler as early as possible in app start up. The foreground handler does not get called when your app is in the background.
