### ISSUE TITLE
Anonymous login method error on Android

### ISSUE THREAD

**Issue by JxianMa** [invertase/react-native-firebase#801]
### Issue

Anonymous login method:
```javascript
import firebase from 'react-native-firebase';
// ...
firebase.auth().signInAnonymously()
      .then(() => {
        this.setState({
          isAuthenticated: true,
        });
      });
// ...
``` 
on Android is returning an error `No async scheduler available`, working fine on iOS. 

### Environment

1. Application Target Platform: 
Android

2. Development Operating System: 
macOS Sierra

3. Build Tools: 
Android Studio v3.0.1, Android SDK 23.0.1

4. React Native version: 
0.52.1

5. RNFirebase Version: 
3.2.2

6. Firebase Module: 
auth

**Comment by Salakar** [comment]
@JxianMa This error sounds like it's coming from bluebird, which I guess it means signInAnonymously is throwing some error - you need to add a .catch() otherwise it's an uncaught exception - and then handle the exception - if it's a new firebase project then i'm guessing it's most likely anonymous auth has not been enabled on the firebase console.

**Comment by JxianMa** [comment]
@Salakar Anonymous auth was enabled, I was actually following the documentation here: https://rnfirebase.io/docs/v3.2.x/auth/getting-started, but still get the same error after catch the error after signInAnonymously function

**Comment by JxianMa** [comment]
Turns out to be related to React Native debugger. If I leave the debugger open, this error will gone.

**Comment by Salakar** [comment]
Are you using bluebird or some other promise library in your browser project? If something only works in debugger then generally means there's a lib being used somewhere that's not compatible with RN js environment, e.g. window/document usages will only work in a browser, in this case the debugger
