### ISSUE TITLE
Error: [auth/billing-not] an internal error has occured. [billing_not_enabled] in firebase authentication in react native

### ISSUE THREAD

**Issue by Avik-Bera-scorpion23** [invertase/react-native-firebase#8012]
A warning shown
Error: [auth/billing-not] an internal error has o
![Selected photo](https://github.com/user-attachments/assets/521ca0f4-89fe-4b54-863d-9cbe204e5f56)
ccured. [billing_not_enabled] in firebase authentication in react native
#6469 #React Native 0.75.2 # react native firebase authentication #4972

**Comment by mikehardy** [comment]
Have you tried enabling billing in your firebase account?
It is required for phone authentication

https://firebase.google.com/pricing

**Comment by ameen06** [comment]
My billing is enabled and I am using BLAZE(pay as you go) plan. But in my app it is still showing this error.

**Comment by saicherry93479** [comment]
@ameen06 you found any soution for the above ?

**Comment by dk-a-dev** [comment]
I am also facing same issue @ameen06 @Avik-Bera-scorpion23 , any updates on this?
