### ISSUE TITLE
🐛 @react-native-firebase/firestore Need Sum in aggregation method

### ISSUE THREAD

**Issue by Ganeshguru5** [invertase/react-native-firebase#8027]
## Sum in aggregation of @react-native-firebase/firestore

In the firebase documentation. They detailed that they have the aggregation feature to sum a particular attribute of a document. But i cant found this method in @react-native-firebase/firestore. Instead everyone reccommends to fetch all data and **sum** the value using array-reduce method. I dont want to get 10 or 100 documents to obtain a single value. Those reads are unwanted.

**Comment by mikehardy** [comment]
This was one of the major feature enhancements of firestore in the last long while, I think it's still a valid request as an API gap
