### ISSUE TITLE
[🐛] messaging().getToken() returns old token for ANDROID device after executing messaging().deleteToken()

### ISSUE THREAD

**Issue by poojalivin** [invertase/react-native-firebase#8030]
In my react native app I'm executing

        await messaging().deleteToken();

to delete token and then on log in runs 

        await messaging().getToken() 

But even after deleting the previous token I'm getting the same old token from getToken().
I have seen many issues reported for IOS and have implemented some suggestions mentions in their comments like using

      await messaging().deleteToken(undefined,'*');

But it didn't work.
I'm using 
     "@react-native-firebase/app": "^20.5.0",
    "@react-native-firebase/messaging": "^20.5.0",

Thanks.

**Comment by russellwheatley** [comment]
Hi @poojalivin - not sure if this is on android or iOS as you mention both. Could you specify which platform you're referring to?
