### ISSUE TITLE
[🐛] Error on phone auth - Expo + RN Firebase

### ISSUE THREAD

**Issue by WellingtonSouzaAbreu** [invertase/react-native-firebase#8037]
The method called is:
firebaseAuth.signInWithPhoneNumber(completeNumber)

I’m using the react-native-firebase library in my project (https://rnfirebase.io/).

Context:
When I generate a build or .app and install it on a device, it works normally, but when I submit it to TestFlight, I get the error:
“NSInvalidArgumentException: -[__NSFrozenDictionaryM length]: unrecognized selector sent to instance 0x600003dad320”

I use the same environment variables to generate the .app builds and the production build, but the error only occurs in production and TestFlight

I recently migrated from Expo SDK 49 to SDK 51.

Does anyone have any idea what this could be?

**Comment by mikehardy** [comment]
Hi there! You've deleted all the information from the issue template, so it will. not be possible to help
In general "unrecognized selector sent to instance" means the native code for react-native-firebase is trying to speak with the native code from firebase-ios-sdk but the two versions are incompatible.
If you have overridden the firebase-ios-sdk in your Podfile to a specific version, you should remove that, and make sure that you have the most up to date react-native-firebase, then retry
If you have some sort of dynamic codebundle OTA updating going on like expo-ota you might make sure that you didn't OTA an outdated codebundle

**Comment by WellingtonSouzaAbreu** [comment]
I create a correctly report here now. I will remove this issue

New issue => https://github.com/invertase/react-native-firebase/issues/8039

Call me if required another infos

**Comment by WellingtonSouzaAbreu** [comment]
Closed because the issue report is malformed. Sorry guys

**Comment by WellingtonSouzaAbreu** [comment]
Closed because the issue report is malformed. Sorry guys
