### ISSUE TITLE
[🐛] The Swift pod FirebaseCoreInternal depends upon GoogleUtilities

### ISSUE THREAD

**Issue by PandaDouxYT** [invertase/react-native-firebase#8051]
Hi, when I do pod install in my ios folder I get this error:

The Swift pod FirebaseCoreInternal depends upon GoogleUtilities, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set use_modular_headers! globally in your Podfile, or specify :modular_headers => true for particular dependencies.

![image](https://github.com/user-attachments/assets/bea3d914-f0fb-41b9-b70b-277fa1dc1819)

**It appears when I do:**
cd ios
pod install

Does anyone have an idea how to set this? I've read that you need to add use_modular_headers! or change the version of platform :ios, ‘13.4’ or whatever.

```
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

use_autolinking_method_symbol = ('use' + '_native' + '_modules!').to_sym
origin_autolinking_method = self.method(use_autolinking_method_symbol)
self.define_singleton_method(use_autolinking_method_symbol) do |*args|
  if ENV['EXPO_UNSTABLE_CORE_AUTOLINKING'] == '1'
    Pod::UI.puts('Using expo-modules-autolinking as core autolinking source'.green)
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
    origin_autolinking_method.call(config_command)
  else
    origin_autolinking_method.call()
  end
end

platform :ios, podfile_properties['ios.deploymentTarget'] || '13.4'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'StarLegends' do
  use_expo_modules!
  config = use_native_modules!
  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end
```

there is my podfile

(I had already tried quite a few things but I deleted my ios folder to start again from 0 with your advice, on mac I can't manage to emulate the app)

**Comment by mikehardy** [comment]
> Does anyone have an idea how to set this? I've read that you need to add use_modular_headers! or change the version of platform :ios, ‘13.4’ or whatever.

You may read that you should use `use_modular_headers!` in some places but I strongly advise against it, you will be in an unsupported configuration and any related issues will be closed here.

firebase-ios-sdk, which is our underlying SDK, strictly request `use_frameworks! :linkage => :static`

You need to configure that and re-install pods and rebuild. It should work. I can see in the Podfile that it's trying to configure that based on ENV or whatever, but since you are using firebase-ios-sdk and it strictly requires it, you can just hard-code it to true

**Comment by PandaDouxYT** [comment]
> > Does anyone have an idea how to set this? I've read that you need to add use_modular_headers! or change the version of platform :ios, ‘13.4’ or whatever.
> 
> You may read that you should use `use_modular_headers!` in some places but I strongly advise against it, you will be in an unsupported configuration and any related issues will be closed here.
> 
> firebase-ios-sdk, which is our underlying SDK, strictly requires `use_frameworks! :linkage => :static`
> 
> You need to configure that and re-install pods and rebuild. It should work. I can see in the Podfile that it's trying to configure that based on ENV or whatever, but since you are using firebase-ios-sdk and it strictly requires it, you can just hard-code it to true

Thank you so much for your reply 🙏! Frankly, I've been struggling for weeks with this problem, I searched in every direction and I couldn't find any solution. As a last hope, I turned to GitHub and in just two minutes you came up with exactly what I needed. I just applied your suggestion and it worked perfectly! 😍

**Comment by ecorengia-joann** [comment]
> > Does anyone have an idea how to set this? I've read that you need to add use_modular_headers! or change the version of platform :ios, ‘13.4’ or whatever.
> 
> You may read that you should use `use_modular_headers!` in some places but I strongly advise against it, you will be in an unsupported configuration and any related issues will be closed here.
> 
> firebase-ios-sdk, which is our underlying SDK, strictly requires `use_frameworks! :linkage => :static`
> 
> You need to configure that and re-install pods and rebuild. It should work. I can see in the Podfile that it's trying to configure that based on ENV or whatever, but since you are using firebase-ios-sdk and it strictly requires it, you can just hard-code it to true

Any reference for Expo powered projects? I'm facing the same issue.

**Comment by mikehardy** [comment]
@ecorengia-joann 

https://duckduckgo.com/?q=how+to+set+use_frameworks+static+expo
https://docs.expo.dev/versions/latest/sdk/build-properties/
https://docs.expo.dev/versions/latest/sdk/build-properties/#pluginconfigtypeios

**Comment by ecorengia-joann** [comment]
> @ecorengia-joann
> 
> https://duckduckgo.com/?q=how+to+set+use_frameworks+static+expo https://docs.expo.dev/versions/latest/sdk/build-properties/ https://docs.expo.dev/versions/latest/sdk/build-properties/#pluginconfigtypeios

Oh I was missing the whole build properties from Expo. There I was able to set `useFrameworks: 'static'`, and it did the trick. Thanks @mikehardy!!

**Comment by lancaluis** [comment]
> > Does anyone have an idea how to set this? I've read that you need to add use_modular_headers! or change the version of platform :ios, ‘13.4’ or whatever.
> 
> You may read that you should use `use_modular_headers!` in some places but I strongly advise against it, you will be in an unsupported configuration and any related issues will be closed here.
> 
> firebase-ios-sdk, which is our underlying SDK, strictly requires `use_frameworks! :linkage => :static`
> 
> You need to configure that and re-install pods and rebuild. It should work. I can see in the Podfile that it's trying to configure that based on ENV or whatever, but since you are using firebase-ios-sdk and it strictly requires it, you can just hard-code it to true

I'm using RN with CLI (v0.76.6) and i'm with the same error. I've already changed from to `linkage.to_sym` to ` :static`
and the error didn't change: 

```
The following Swift pods cannot yet be integrated as static libraries:
The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which does not define modules.
```

Any oder suggestion?

**Comment by lancaluis** [comment]
I had the same issue and I figured out it was missing some configs inside my Podfile:

```
use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  // Those lines below fixed my problem
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
```

**Comment by mikehardy** [comment]
@lancaluis 

No, these lines:

```
  // Those lines below fixed my problem
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
```

... have just created a new problem for you that you don't know about. Specifically that firebase-ios-sdk is partially written in Objective-C and partially written in Swift.

And those lines will break your build whenever one of the modules you use converts to swift.

You must remove them.

you must use `use_frameworks! :linkage => :static`

Or you will not be able to get any support for react-native-firebase or firebase-ios-sdk

This is documented in our installation reference on rnfirebase.io

**Comment by DreamEmulator** [comment]
`use_frameworks! :linkage => :static`

![Image](https://github.com/user-attachments/assets/28e43e2c-98b3-4940-b258-083e9607bb44)

@mikehardy just came here to say I love you 🫶

**Comment by haikulabs-ai** [comment]
> > @ecorengia-joann
> > https://duckduckgo.com/?q=how+to+set+use_frameworks+static+expo https://docs.expo.dev/versions/latest/sdk/build-properties/ https://docs.expo.dev/versions/latest/sdk/build-properties/#pluginconfigtypeios
> 
> Oh I was missing the whole build properties from Expo. There I was able to set `useFrameworks: 'static'`, and it did the trick. Thanks [@mikehardy](https://github.com/mikehardy)!!

Just to clarify for anyone else looking, you have to install the expo-build-properties plugin and add this plugin to your app.config.js (or app.json) -> plugins and set 

`['expo-build-properties', iOS: { useFramworks: 'static' }]`

**Comment by CodeByStella** [comment]
Hi, @mikehardy 
I was getting stress with same issue for 4 days and I just solved the issue using your method. Really thank you!! I follow you.  ❤

**Comment by ssthil** [comment]
> `use_frameworks! :linkage => :static`
> 
> ![Image](https://github.com/user-attachments/assets/28e43e2c-98b3-4940-b258-083e9607bb44)
> 
> [@mikehardy](https://github.com/mikehardy) just came here to say I love you 🫶

It worked for me. Thanks @DreamEmulator

**Comment by GSFZamai** [comment]
Hi there, hope you're fine.
This line `use_frameworks! :linkage => :static` resolved the Pods installation problem but now I'm getting this error on build:

<img width="1353" height="305" alt="Image" src="https://github.com/user-attachments/assets/ea0ac544-5992-47a4-a72e-
f45c41999930" />

Anyone with the same problem? I'm struggling  with it for about 3 days without a solution... It seems to be related to `use_frameworks! :linkage => :static`.
I'm upgrading from RN `0.75.4` to `0.80.2` on the previous version It was working fine. Now on `0.80.2` works on Android but the build fails on iOS

**Comment by jonnathanc765** [comment]
@fgagneten answers works for me 🚀

**Comment by FidFenix** [comment]
Just came to say, the code below did the trick expo 54. However, ```use_frameworks! :linkage => :static``` did not worked for me, or I set it wrongly.

```
plugins: [
      "@react-native-firebase/app",
      "@react-native-firebase/auth",
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }
      ],
]
```

**Comment by mzain512** [comment]
For me this removed firebase build issues but I am getting the following now.

`'react/debug/react_native_assert.h' file not found`

**Comment by keidakira** [comment]
If anyone faces a build failure in iOS due to this change, try this change as suggested [here](https://github.com/expo/expo/issues/39607#issuecomment-3287742018)
```
["expo-build-properties", {
  "ios": {
    "useFrameworks": "static",
    "buildReactNativeFromSource": true
  }
}]
```

Then run `npx expo prebuild --clean` and `npx expo run:ios`

**Comment by zahid502** [comment]
@mikehardy answer worked for me 
`use_frameworks! :linkage => :static`

I'm using
 "react-native": "0.81.1",
 "@react-native-firebase/app": "^23.4.0",
 "@react-native-firebase/messaging": "^23.4.0",

**Comment by anandsharmaautovyn** [comment]
the firebase analytics SDK is not supported in RN 0.80+ that's why it's happening, so even after adding use_frameworks! :linkage => :static
it's giving 'react/debug/react_native_assert.h' file not found
@mikehardy I think that's true
so the issue is still open

**Comment by dBrogle** [comment]
Came to say thanks @mikehardy and everyone else in this thread

Fix in app.json:
```
plugins: [
...
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static",
            "buildReactNativeFromSource": true
          }
        }
      ]
]
```
(as an fyi, without the "buildReactNativeFromSource": true, the prebuild works, but when built using expo, it failed at a later step)

On expo 54.0.20, pod 1.16.2, and node 25.2.0

Thanks for the fix! The LLMs couldn't get it

**Comment by mikehardy** [comment]
In case anyone else sees this, I've got an expo integration demo script that I'll keep generally up to date and it shows how to integrate:

https://github.com/mikehardy/rnfbdemo/blob/main/make-expo-demo.sh
