### ISSUE TITLE
'dynamic_link_received' with no listeners registered

### ISSUE THREAD

**Issue by IsracardTeam** [invertase/react-native-firebase#806]
I am Testing out Dynamic links .
Sometime i get this warning that says "Sending `dynamic_link_receivedz with no listeners registered` 

This logs the message object correctly:

Firebase is initialized in my Root container. (this problem happens almost every time on the first install.

 ```
           firebase.links()
                .getInitialLink()
                .then((url) => {
                    if (url) {
                        deepLinkGoTo = url;
                        // app opened from a url
                    } else {
                        // app NOT opened from a url
                    }
                });
            firebase.links().onLink((url) => {
                deepLinkHandle(url);
            });
```
looks like firebase is initialized late.

any ideas ?

react-native: 0.51.0
yarn: v1.2.1
react-native-firebase: 3.2.4
XCode: 9.2
iOS 11.2

**Comment by chrisbianca** [comment]
@IsracardTeam thanks for the report, I'm currently looking at something similar in messaging at the moment. Once I've resolved there, I'll apply the fix to Links as well.

**Comment by IsracardTeam** [comment]
@chrisbianca Thanks

**Comment by IsracardTeam** [comment]
@chrisbianca did you handle this issue on v.3.30 that was released today ?

**Comment by IljaDaderko** [comment]
@chrisbianca I'm getting same warning with dynamic links in iOS, let me know if there is any further feedback I can give 👍 this is in RNFirebase v3.3.1 still

**Comment by SamMatthewsIsACommonName** [comment]
Same here on 3.3.1, 
I'm wondering if I have the url scheme entered correctly? I assume I was supposed to make it a string?

<img width="535" alt="screen shot 2018-03-17 at 8 01 31 am" src="https://user-images.githubusercontent.com/21329063/37550037-9185abb6-29b9-11e8-9a81-c368d899166f.png">
<img width="853" alt="screen shot 2018-03-17 at 8 01 46 am" src="https://user-images.githubusercontent.com/21329063/37550038-91bae088-29b9-11e8-93b8-06742f2d1f84.png">

Also I'm not getting any 'onLink' events. I've instead had to put 

````
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
  
  return [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}
````

Back in and use the linking library

**Comment by chrisbianca** [comment]
This should be resolved in the latest v4 release candidate.

**Comment by SamMatthewsIsACommonName** [comment]
Hi @chrisbianca  just tried with new release candidate, but now has changed to:

````
Sending `links_link_received` with no listeners registered

````
The onLink is now working btw, thanks!
