### ISSUE TITLE
Execution failed for task ':react-native-firebase_auth:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by musabgulfam** [invertase/react-native-firebase#8064]
Hi there,
So just today, I started facing this weird error, which says

Execution failed for task ':react-native-firebase_auth:compileDebugJavaWithJavac`

Here is a detailed error description

node_modules/@react-native-firebase/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java:1620: error: pattern matching in instanceof is not supported in -source 11
                    if (exception instanceof FirebaseAuthUserCollisionException collEx) {
                                                                                ^
  (use -source 16 or higher to enable pattern matching in instanceof)
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-firebase_auth:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

These are my Java configurations

openjdk 17.0.13 2024-10-15 LTS
OpenJDK Runtime Environment Zulu17.54+21-CA (build 17.0.13+11-LTS)
OpenJDK 64-Bit Server VM Zulu17.54+21-CA (build 17.0.13+11-LTS, mixed mode, sharing)

My dependencies
"dependencies": {
    "@invertase/react-native-apple-authentication": "^2.2.2",
    "@notifee/react-native": "^5.6.0",
    "@react-native-async-storage/async-storage": "^1.17.0",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/datetimepicker": "^6.1.2",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/push-notification-ios": "^1.10.1",
    "@react-native-community/slider": "^4.2.1",
    "@react-native-firebase/app": "^19.2.2",
    "@react-native-firebase/auth": "^19.2.2",
    "@react-native-firebase/dynamic-links": "^19.2.2",
    "@react-native-firebase/messaging": "^19.2.2",
    "@react-native-firebase/storage": "^19.2.2",
    "@react-native-google-signin/google-signin": "^9.1.0",
    "@react-native-picker/picker": "^2.4.0",
    "@react-navigation/bottom-tabs": "^6.2.0",
    "@react-navigation/drawer": "^6.6.6",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.2",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "apisauce": "^2.1.2",
    "axios": "^0.26.1",
    "deprecated-react-native-prop-types": "^5.0.0",
    "easy-peasy": "^5.0.4",
    "geolib": "^3.3.3",
    "joi": "^17.4.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.2",
    "query-string": "^8.1.0",
    "react": "18.2.0",
    "react-native": "0.72.7",
    "react-native-branch": "^6.2.2",
    "react-native-calendars": "^1.1305.0",
    "react-native-camera": "^4.2.1",
    "react-native-config": "^1.5.1",
    "react-native-countdown-component": "^2.7.1",
    "react-native-countdown-fixed": "^2.7.1",
    "react-native-date-picker": "^5.0.4",
    "react-native-device-info": "^10.6.0",
    "react-native-exit-app": "^2.0.0",
    "react-native-fbsdk-next": "^12.1.1",
    "react-native-gesture-handler": "^2.14.1",
    "react-native-get-random-values": "^1.11.0",
    "react-native-gifted-chat": "^2.4.0",
    "react-native-google-places-autocomplete": "^2.5.6",
    "react-native-image-crop-picker": "^0.40.2",
    "react-native-image-picker": "^4.7.3",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-maps": "^1.8.0",
    "react-native-maps-directions": "^1.9.0",
    "react-native-modal": "^13.0.0",
    "react-native-modal-datetime-picker": "^14.0.0",
    "react-native-modal-selector": "^2.1.2",
    "react-native-network-info": "^5.2.1",
    "react-native-paper": "^4.9.2",
    "react-native-permissions": "^3.10.1",
    "react-native-public-ip": "^1.0.2",
    "react-native-qrcode-scanner": "^1.5.5",
    "react-native-radial-gradient": "^1.1.2",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^3.6.1",
    "react-native-render-html": "^6.3.4",
    "react-native-restart": "0.0.22",
    "react-native-safe-area-context": "^4.2.4",
    "react-native-screens": "^3.13.1",
    "react-native-share": "^10.2.0",
    "react-native-simple-toast": "^1.1.3",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^12.1.1",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-toast-message": "^2.1.3",
    "react-native-vector-icons": "^10.0.2",
    "react-native-version-info": "^1.1.1",
    "react-native-webview": "^11.18.2",
    "socket.io-client": "^4.5.2"
  }

**Comment by musabgulfam** [comment]
Thanks, @mikehardy
Is there any documentation outlining how to install those?

**Comment by musabgulfam** [comment]
Surprisingly, when issuing a `npm run android` instead of using yarn, there's no such errors. Is there any reason for that?

**Comment by mikehardy** [comment]
Helping developers install the jdk is out of scope for this repository.

**Comment by musabgulfam** [comment]
Unfortunately, I am still getting the errors.

```
node_modules/@react-native-firebase/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java:1620: error: pattern matching in instanceof is not supported in -source 11
                    if (exception instanceof FirebaseAuthUserCollisionException collEx) {
                                                                                ^
  (use -source 16 or higher to enable pattern matching in instanceof)
```

Upon issuing the command `java --version`
```
openjdk version "17.0.13" 2024-10-15 LTS
OpenJDK Runtime Environment Zulu17.54+21-CA (build 17.0.13+11-LTS)
OpenJDK 64-Bit Server VM Zulu17.54+21-CA (build 17.0.13+11-LTS, mixed mode, sharing)
```
The JDK version seems fine here, its not outdated though...

**Comment by musabgulfam** [comment]
Upon trying to install a later version of gradle also results in incompatibility issues...

**Comment by mikehardy** [comment]
> Unfortunately, I am still getting the errors

Then you are still running with an unsupported version of the JDK. You must make sure that you build and run react-native-firebase only with supported versions of the JDK.

That's JDK17+

**Comment by mikehardy** [comment]
Additionally:

```
    "@react-native-firebase/app": "^19.2.2",
    "@react-native-firebase/auth": "^19.2.2",
    "@react-native-firebase/dynamic-links": "^19.2.2",
    "@react-native-firebase/messaging": "^19.2.2",
    "@react-native-firebase/storage": "^19.2.2",
```

These are outdated.

```
    "react-native": "0.72.7",
```

So is this, by default most repositories only support the current and two prior releases so that would be react-native 0.76, 0.75 and 0.74.

You appear to have a lot of deferred maintenance between need to update JDK, react-native and react-native-firebase

Once you perform that deferred maintenance and are on current versions, you will not see this problem.

**Comment by musabgulfam** [comment]
The JDK I downloaded is directly from the documentation outlined here

[https://reactnative.dev/docs/set-up-your-environment?platform=android](url)

**Comment by musabgulfam** [comment]
> Additionally:
> 
> ```
>     "@react-native-firebase/app": "^19.2.2",
>     "@react-native-firebase/auth": "^19.2.2",
>     "@react-native-firebase/dynamic-links": "^19.2.2",
>     "@react-native-firebase/messaging": "^19.2.2",
>     "@react-native-firebase/storage": "^19.2.2",
> ```
> 
> These are outdated.
> 
> ```
>     "react-native": "0.72.7",
> ```
> 
> So is this, by default most repositories only support the current and two prior releases so that would be react-native 0.76, 0.75 and 0.74.
> 
> You appear to have a lot of deferred maintenance between need to update JDK, react-native and react-native-firebase
> 
> Once you perform that deferred maintenance and are on current versions, you will not see this problem.

Thanks for the guidance, updating to react native version `0.75.0`

**Comment by mikehardy** [comment]
> The JDK I downloaded is directly from the documentation outlined in react native environment setup page. Still not sure whats wrong, or how to troubleshoot whats going wrong in here 😕
> 
> https://reactnative.dev/docs/set-up-your-environment?platform=android

You think you are using that JDK. And you are able to see it on the command line

But something about how react-native is building and running android **is not using that JDK**

Or you would not see the error. So you are not, in practice, using the JDK you think you are using. The evidence is showing you this, you should believe it and figure out why your system has multiple JDKs and react-native is using the wrong one

**Comment by musabgulfam** [comment]
Sorry to ask, but is there a way to find which JDK is being utilised currently by react-native?

**Comment by mikehardy** [comment]
I won't be able to help with that, apologies

**Comment by musabgulfam** [comment]
This is my local.properties
```
## This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
#Mon Nov 18 13:28:25 PKT 2024
sdk.dir=/Users/musabgulfam/Library/Android/sdk
java.home=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
```

I just added the `java.home` line

**Comment by musabgulfam** [comment]
> This is my local.properties
> ```
> ## This file must *NOT* be checked into Version Control Systems,
> # as it contains information specific to your local configuration.
> #
> # Location of the SDK. This is only used by Gradle.
> # For customization when using a Version Control System, please read the
> # header note.
> #Mon Nov 18 13:28:25 PKT 2024
> sdk.dir=/Users/musabgulfam/Library/Android/sdk
> java.home=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
> ```
> 
> I just added the `java.home` line

This didn't help either. I did everything outlined in the docs, but I'm still stuck with this error 😫
