### ISSUE TITLE
[🐛] Bug Report Title - No known class method for selector 'componentWithProtocol:instantiationTiming:creationBlock:'

### ISSUE THREAD

**Issue by Tarun24RN** [invertase/react-native-firebase#8065]

**Comment by mikehardy** [comment]
You have updated to a new version of our module while maintaining a version pin to firebase-ios-sdk in your podfile so you have the kind of compatibility issues we mention are possible if you out a version pin for the sdk in your podfile. Remove the firebase-ios-sdk version pin

**Comment by Tarun24RN** [comment]
> You have updated to a new version of our module while maintaining a version pin to firebase-ios-sdk in your podfile so you have the kind of compatibility issues we mention are possible if you out a version pin for the sdk in your podfile. Remove the firebase-ios-sdk version pin

After removing the pin version pod installs successfully but new issue occur  'FirebaseAuth/FirebaseAuth-Swift.h' file not found.
But before installing pods i added pod 'FirebaseAuth', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true in podfile

**Comment by mikehardy** [comment]
modular_headers is not supported in any way here, it is an unsupported workaround for people not choosing to comply with the strict requirement we list that you set `use_frameworks! :linkage => :static``

You must use `use_frameworks! :linkage => :static` and remove modular_headers directives to be on a supported build configuration

**Comment by vivkikkk** [comment]
same howto fix ?

**Comment by mikehardy** [comment]
@vivkikkk 

> You have updated to a new version of our module while maintaining a version pin to firebase-ios-sdk in your podfile so you have the kind of compatibility issues we mention are possible if you out a version pin for the sdk in your podfile. Remove the firebase-ios-sdk version pin

Make sure you are using the correct version of firebase-ios-sdk, by removing any version pins you have on it so that we control the version from within firebase-ios-sdk and you see in Podfile.lock the version we get, which is currently 11.4.0:

https://github.com/invertase/react-native-firebase/blob/3780d671b65333cebee0887f7cd30faa0055945b/packages/app/package.json#L77

**Comment by vivkikkk** [comment]
@mikehardy Thanks for replying to me. I'm not sure if you meant the firebase in dependencies or not the firebase sdk Versions or right.

**Comment by vivkikkk** [comment]
@mikehardy Thanks for replying me. Yes, it is "firebase" version: "11.4.0" but I am not sure why Podfile.lock is like this. 
<img width="298" alt="Screenshot 2567-10-31 at 09 51 40" src="https://github.com/user-attachments/assets/c2254c96-09c5-4b53-91a3-c17ad15f9d6f">

**Comment by j-elmer123** [comment]
> @mikehardy Thanks for replying me. Yes, it is "firebase" version: "11.4.0" but I am not sure why Podfile.lock is like this. <img alt="Screenshot 2567-10-31 at 09 51 40" width="298" src="https://private-user-images.githubusercontent.com/40588602/381805834-c2254c96-09c5-4b53-91a3-c17ad15f9d6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDQ3MzUsIm5iZiI6MTczMDM0NDQzNSwicGF0aCI6Ii80MDU4ODYwMi8zODE4MDU4MzQtYzIyNTRjOTYtMDljNS00YjUzLTkxYTMtYzE3YWQxNWY5ZDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAzMTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZWJjNDE2ZWJhYTU0OWE5NjQxNjMwM2IxNDVhZDExMDI2ZWZhZTQxNzg2MDhjZTI5MTU3MDc3NTA4NGVkMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6g501RYBnop-j9Or9ZZThh2QBya8xyHig6WFlNRKfak">

I am also having the similar issue

**Comment by mikehardy** [comment]
I can't answer the why, but now the issue in your project is clear. The lock file usually says what causes what dependency to be what version, you'll have to decode and fix

**Comment by vivkikkk** [comment]
@mikehardy Thanks, I'll try it.
