### ISSUE TITLE
[🐛] React Native not track in_app_purchase event for Android

### ISSUE THREAD

**Issue by CVHOANG-coder** [invertase/react-native-firebase#8068]
Issue
Describe your issue here

Hello everyone i have problem with firebase analytics tracking for Android.My application is React Native.On Android i dont receive in_app_purchase event.

Javascript:

>   "dependencies": {
    "@hookform/resolvers": "^3.9.0",
    "@notifee/react-native": "^9.0.2",
    "@react-native-clipboard/clipboard": "^1.14.1",
    "@react-native-community/slider": "^4.5.2",
    "@react-native-firebase/analytics": "^21.0.0",
    "@react-native-firebase/app": "^21.0.0",
    "@react-native-firebase/crashlytics": "^21.0.0",
    "@react-native-firebase/messaging": "^21.0.0",
    "@react-native-firebase/remote-config": "^21.0.0",
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "@react-navigation/stack": "^6.4.1",
    "@tanstack/react-query": "^5.52.2",
    "axios": "^1.7.5",
    "lottie-ios": "^4.5.0",
    "lottie-react-native": "^7.0.0",
    "moment": "^2.30.1",
    "react": "18.2.0",
    "react-hook-form": "^7.53.0",
    "react-native": "0.72.15",
    "react-native-blob-util": "^0.19.11",
    "react-native-device-info": "^11.1.0",
    "react-native-dotenv": "^3.4.11",
    "react-native-gesture-handler": "^2.18.1",
    "react-native-iap": "^12.15.2",
    "react-native-in-app-review": "^4.3.3",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-mmkv": "^2.12.2",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "^6.3.4",
    "react-native-permissions": "^4.1.5",
    "react-native-reanimated": "^3.15.0",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-safe-area-context": "^4.10.9",
    "react-native-screens": "^3.34.0",
    "react-native-share": "^11.0.3",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "15.1.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-track-player": "^4.1.1",
    "react-native-vector-icons": "^10.1.0",
    "react-native-webview": "^13.12.3",
    "yup": "^1.4.0",
    "zustand": "^4.5.5"
  }

Android:

>  // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 24
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "23.1.7779620"
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'com.google.gms:google-services:4.4.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
    }
}

**Comment by russellwheatley** [comment]
hi @CVHOANG-coder - we're going to need more information than that. What API are you calling? Is the event not appearing in debug view?

**Comment by ouarrtaha** [comment]
Same here, 
it works fine with ios iap events, but not android

**Comment by mikehardy** [comment]
@ouarrtaha 

> we're going to need more information than that. What API are you calling? Is the event not appearing in debug view?
