### ISSUE TITLE
Can't build release iOS version - error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by thedc89** [invertase/react-native-firebase#807]
I'm struggling really hard with building the app under release schema in Xcode. Finally, the last error that occurs looks as follows:

http://i65.tinypic.com/35cisn9.png

```
ld: warning: directory not found for option '-L/Users/DC/Library/Developer/Xcode/DerivedData/pagarony-gttspckltgehqjbmapfbkdfpuwlb/Build/Products/Release-iphoneos/GTMSessionFetcher'
ld: warning: directory not found for option '-L/Users/DC/Library/Developer/Xcode/DerivedData/pagarony-gttspckltgehqjbmapfbkdfpuwlb/Build/Products/Release-iphoneos/GoogleToolboxForMac'
ld: warning: directory not found for option '-L/Users/DC/Library/Developer/Xcode/DerivedData/pagarony-gttspckltgehqjbmapfbkdfpuwlb/Build/Products/Release-iphoneos/leveldb-library'
ld: warning: directory not found for option '-L/Users/DC/Library/Developer/Xcode/DerivedData/pagarony-gttspckltgehqjbmapfbkdfpuwlb/Build/Products/Release-iphoneos/nanopb'
ld: library not found for -lGTMSessionFetcher
clang: error: linker command failed with exit code 1 (use -v to see invocation) 
```

I suspect this issue might come from Firebase. Has anyone here encountered such issue? 

Note that it does not occur when in debug mode.

### Environment

Application Target Platform:
iOS

Development Operating System:
Mac OS High Sierra

Build Tools:
command line
XCode 9.2

React Native version:
react-native-cli: 2.0.1
react-native: 0.52.2

RNFirebase Version:
"react-native-firebase": "^3.2.3",

Firebase Module:
Storage

**Comment by chrisbianca** [comment]
@thedc89 which error are you getting? This issue, or this https://github.com/invertase/react-native-firebase/issues/808 other one you opened?

**Comment by thedc89** [comment]
@chrisbianca this one was the first I got, after a couple of cleans and other tricks found in other issues I managed to silent this error for a while, but afterwards it showed up again. Not sure which error is called first though, this or #808  so I decided not to close this issue until it's fully resolved

**Comment by thedc89** [comment]
For now, I managed to solve it by running `pod deintegrate` and `pod install1`

Closing the issue

**Comment by thedc89** [comment]
The issue occurs again, `pod deintegrate` and `pod install` do not solve it anymore

**Comment by yezarela** [comment]
@thedc89 have you found a solution?

**Comment by thedc89** [comment]
@yezarela Unfortunately not. Are you facing the same issue?

**Comment by evanjmg** [comment]
pod 'React', :path => '../node_modules/react-native', :subspecs => ['DevSupport'] work?

**Comment by thedc89** [comment]
@evanjmg  When I run pod install I get `[!] Unable to find a specification for `yoga (= 0.53.3.React)` depended upon by `React/Core``

**Comment by evanjmg** [comment]
sorry forgot to add yoga in pod   pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

**Comment by yezarela** [comment]
in my case, I use fastlane/gym to package a release of the app and found that I need to update gymfile to use `workspace` instead of `project` to include pod files.

**Comment by thedc89** [comment]
@evanjmg Now I get 

> ld: library not found for -lPods-pagarony
clang: error: linker command failed with exit code 1 (use -v to see invocation)

pagarony is the name of project.

**Comment by LorandP** [comment]
What worked for me was to add this https://github.com/invertase/react-native-firebase/issues/294#issuecomment-370669509 into my pod file along with 'Firebase/Core' and 'FirebaseMessaging'.

After you do that first apply these commands:
1.	rm -rf ios/Pods.
	2.	rm Podfile.lock.
	3.	pod install

You can also try unlink and re-link the library.

**Comment by chrisbianca** [comment]
We've not heard much on this for a while, so I'm going to assume it's been resolved as part of the header changes in v4. Please let us know if this is not the case after updating to v4.

**Comment by andrewkslv** [comment]
Don't forget to close xcode before running `pod install`. After that open your project with `.xcworkspace`.

**Comment by thedc89** [comment]
The problem occurs only when node modules for some other libraries are linked in Podfile. After I added all other libraries manually and do not run `react-native link`, it's all fine

**Comment by Dimon70007** [comment]
after i removed all pods from project and manually linked all dependencies project has built successfully.
