### ISSUE TITLE
[🐛] Bug - 'headerValue()' is unavailable in Swift: Use `asyncHeaderValue() async -> String?` instead.

### ISSUE THREAD

**Issue by VadymBezsmertnyi** [invertase/react-native-firebase#8073]
Good day, I have an error after the last pod update, specifically:
'headerValue()' is unavailable in Swift: Use 'asyncHeaderValue() async -> String?' instead.
This occurs in the file AuthBackend.swift.
I am attaching screenshots:
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/f96c7bf5-2fb1-4972-a3a3-f754e2ea0c0e">
<img width="603" alt="image" src="https://github.com/user-attachments/assets/fdb44623-7163-40a8-b6bb-9ee945874538">

Also, here is my package.json:

> {
  "name": "***name**",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest",
    "repods": "cd ios && pod install",
    "reinstall": "rm -rf node_modules/ && yarn cache clean && yarn install && cd ios && rm -rf Podfile.lock && rm -rf Pods && arch -x86_64 pod install",
    "icons": "svgr -d assets/icons-auto/components assets/icons-auto/svg --template assets/icons-auto/icon-template.js --typescript --native --no-dimensions",
    "android-release-bundle": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release/ && rm -rf android/app/src/main/res/drawable-* && rm -rf android/app/src/main/res/raw/* && cd android && ./gradlew bundleRelease && cd ..",
    "android-release-build": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release/ && rm -rf android/app/src/main/res/drawable-* && rm -rf android/app/src/main/res/raw/* && cd android && ./gradlew assembleRelease && cd .."
  },
  "dependencies": {
    "@gorhom/bottom-sheet": "^5.0.4",
    "@invertase/react-native-apple-authentication": "^2.4.0",
    "@react-native-async-storage/async-storage": "^2.0.0",
    "@react-native-community/datetimepicker": "^8.2.0",
    "@react-native-community/push-notification-ios": "^1.11.0",
    "@react-native-firebase/app": "^21.1.0",
    "@react-native-firebase/auth": "^21.1.0",
    "@react-native-firebase/database": "^21.1.0",
    "@react-native-firebase/messaging": "^21.1.0",
    "@react-native-firebase/storage": "^21.1.0",
    "@react-native-google-signin/google-signin": "^13.1.0",
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "@svgr/cli": "^8.1.0",
    "axios": "^1.7.7",
    "dayjs": "^1.11.13",
    "react": "18.3.1",
    "react-native": "0.75.4",
    "react-native-contacts": "^7.0.8",
    "react-native-fbsdk-next": "^13.1.3",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.20.0",
    "react-native-get-random-values": "^1.11.0",
    "react-native-global-props": "^1.1.5",
    "react-native-image-picker": "^7.1.2",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-permissions": "^5.0.1",
    "react-native-purchases": "^8.2.4",
    "react-native-push-notification": "^8.1.1",
    "react-native-reanimated": "^3.16.1",
    "react-native-safe-area-context": "^4.11.1",
    "react-native-screens": "^3.34.0",
    "react-native-section-alphabet-list": "^3.0.0",
    "react-native-shadow-2": "^7.1.0",
    "react-native-share": "^11.0.4",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^15.8.0",
    "react-native-text-input-mask": "^3.2.0",
    "react-native-vision-camera": "^4.5.3",
    "uuid": "^10.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.25.8",
    "@babel/preset-env": "^7.25.8",
    "@babel/runtime": "^7.25.7",
    "@react-native-community/cli": "^14.1.1",
    "@react-native/babel-preset": "0.75.4",
    "@react-native/eslint-config": "0.75.4",
    "@react-native/metro-config": "0.75.4",
    "@react-native/typescript-config": "0.75.4",
    "@types/react": "^18.3.11",
    "@types/react-native-global-props": "^1.1.6",
    "@types/react-native-push-notification": "^8.1.4",
    "@types/react-test-renderer": "^18.3.0",
    "@types/uuid": "^10.0.0",
    "babel-jest": "^29.7.0",
    "eslint": "^9.13.0",
    "jest": "^29.7.0",
    "prettier": "3.3.3",
    "react-native-dotenv": "^3.4.11",
    "react-test-renderer": "18.3.1",
    "typescript": "5.6.3"
  },
  "engines": {
    "node": ">=18"
  },
  "packageManager": "yarn@3.6.4"
}

**Comment by DiazIgnacio** [comment]
Same issue here, happening when building in EAS server's but not locally

**Comment by mikehardy** [comment]
Are you able to reproduce the bug with my build issue reproducer here? https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

just need to plop a google services json/plist file in there and bump the RNFB version to 21.1.0 (though, I've been using firebase-ios-sdk 11.3.0 forever already and it worked...)

I suspect something going on with caching or something, or perhaps the firebase-ios-sdk version is overriden in the Podfile or something?

Because I haven't had any build problems like this either here in the e2e test suite app or my build reproducer 🤔

**Comment by PavelShev** [comment]
Same erros here in class AuthBackend
'headerValue()' has been explicitly marked unavailable here (FirebaseCoreExtension.FIRHeartbeatLoggerProtocol)
Installing Firebase (11.3.0)
Installing FirebaseAppCheckInterop (11.4.0)
Installing FirebaseAuth (11.3.0)
Installing FirebaseAuthInterop (11.4.0)
Installing FirebaseCore (11.3.0)
Installing FirebaseCoreExtension (11.4.0)
Installing FirebaseCoreInternal (11.4.0)
Installing FirebaseDatabase (11.3.0)
Installing FirebaseInstallations (11.4.0)
Installing FirebaseMessaging (11.3.0)
Installing FirebaseSharedSwift (11.4.0)
Installing FirebaseStorage (11.3.0)

**Comment by VadymBezsmertnyi** [comment]
@mikehardy 
Hey)
Here are the changes I updated and couldn't revert:
![Screenshot 2024-10-22 at 00 11 00](https://github.com/user-attachments/assets/f423a769-5502-4202-a2ad-86f47d5cb46b)

**Comment by mikehardy** [comment]
I think it's because 11.4.0 came out and we're getting a mix of dependencies - thanks @PavelShev for posting that - very instructive

**workaround** - ping firebase-ios-sdk in Podfile to 11.4.0 like so: https://rnfirebase.io/#ios

I'm not sure if you can do that in Expo. Looks like we need a release here that can either pin the versions to "same or lower than" firebase-ios-sdk instead of letting them drift since it appears they aren't semantic versioning-safe, or to update to 11.4.0

**Comment by DiazIgnacio** [comment]
For a managed Expo app I made a temp plugin to solve this:

/* eslint-disable no-undef */
/* eslint-disable quotes */
/* eslint-disable @typescript-eslint/no-var-requires */
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const withTempFirebaseFix = (config) => {
    return withDangerousMod(config, [
        'ios',
        (config) => {
            const podfilePath = path.join(config.modRequest.platformProjectRoot, 'Podfile');
            let podfileContents = fs.readFileSync(podfilePath, 'utf-8');

            //  Fix for the Podfile
            const fix = `
    # Fix 'headerValue()' is unavailable in Swift: Use asyncHeaderValue() async -> String? 
    # https://github.com/invertase/react-native-firebase/issues/8073
    $FirebaseSDKVersion = '11.4.0'

`;
            if (!podfileContents.includes("$FirebaseSDKVersion = '11.4.0'")) {
                podfileContents = fix + podfileContents;
                fs.writeFileSync(podfilePath, podfileContents);
            }

            return config;
        },
    ]);
};

module.exports = withTempFirebaseFix;

**Comment by mikehardy** [comment]
I've got a PR in CI right now that contrains the transitive dependencies a lot more tightly
Some of them are still slipping out to 11.4.0 but the build passes for me now?

I will also be pursuing the actual firebase-ios-sdk update as a separate item but this should get people building again assuming CI here goes green and I can hit the merge + publish buttons

**Comment by mikehardy** [comment]
@DiazIgnacio this is actually a pretty useful plugin in general, as there is no other way I'm aware of to set the Firebase SDK version in Expo since it is direct in the Podfile - thanks for posting that

**Comment by maximmai** [comment]
also experiencing this with flutter version `3.24.3` and FirebaseAuth version 
```
#  firebase_analytics: ^10.5.1
#  firebase_auth: ^4.10.1
#  firebase_messaging: ^14.6.9
#  firebase_crashlytics: ^3.3.7
#  firebase_dynamic_links: ^5.3.7
#  firebase_in_app_messaging: ^0.7.3+7
```
![image](https://github.com/user-attachments/assets/cc1b8fb2-628d-4977-9f92-08baf0c2dab3)

**Comment by alexsyeo** [comment]
Not sure if this is related, but I'm using Expo and also had to manually add `use_modular_headers!` toward the top of my ios/Podfile to get it to work, even after pulling v21.1.1

**Comment by VadymBezsmertnyi** [comment]
@mikehardy 
Thank you for the quick fix. I updated everything, and it works well)

**Comment by mikehardy** [comment]
react-native-firebase with firebase-ios-sdk 11.4.0 is out as well so this should go away for everyone for two reasons:
- better transitive dependency management so it shouldn't happen again
- current firebase-ios-sdk so it doesn't matter in this specific instance either

**Comment by ncooke3** [comment]
Thanks, @mikehardy! FYI, FirebaseCoreExtension 11.4.1 was published this morning to revert the problematic change. Folks on older Firebase versions that run `pod update` should get the patched pod.

**Comment by jpdriver** [comment]
@mikehardy fwiw we were seeing this in our managed Expo app (using `"@react-native-firebase/app": "^21.2.0"`) but only when building with Xcode 15.4.

updating to Xcode 16 (with no other code / project changes) solved it for us.

sorry i know that's anecdotal, just wanted to flag that it may be related..
