### ISSUE TITLE
[🐛] [firebase_auth] The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.

### ISSUE THREAD

**Issue by rezaultf** [invertase/react-native-firebase#8075]
## Issue

We are using firebase phone number authentication in our application, but for some country (Lebanon +961) OTP doesn't delivering and log shows this error `[firebase_auth] The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.` where everything working in Malaysian number, Indian number, Bangladeshi number etc.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there - this won't be something we can solve here unfortunately, we just wrap those APIs so if it works for any country code, that means the code in this repository is working. You might want to look carefully in the documentation to see if the country code that is failing has restrictions of some sort, with regard to Firebase billing plan or something specific to the country etc, and if further assistance is needed I'd approach firebase support directly from the firebase docs help / contact sections

**Comment by russellwheatley** [comment]
Appears Lebanon is a supported region, but worth asking Firebase support if that has changed for whatever reason: https://firebase.google.com/support/faq/#phone-auth-regions

As Mike has said, this isn't something we can fix, perhaps not even at the level of the Firebase SDKs (likely Firebase servers), so worth raising an issue with Firebase support.
