### ISSUE TITLE
RNFirebase - Argument list too long

### ISSUE THREAD

**Issue by thedc89** [invertase/react-native-firebase#808]
Building for release and keep getting this error:

> Argument list too long: recursive header expansion failed at /Users/DC/Development/pagarony/node_modules/react-native-firebase/ios/../../../ios/Pods/React/node_modules/fsevents/node_modules/isarray.

It occurs under RNFirebase target.
I have gone through some similar issues here, but none did the trick. Any ideas how to silent this error?
Podfile:
```
platform :ios, '11.0'
target "MyProject" do
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
end
```
Thanks in advance

### Environment

Application Target Platform:
iOS

Development Operating System:
Mac OS High Sierra

Build Tools:
command line
XCode 9.2

React Native version:
react-native-cli: 2.0.1
react-native: 0.52.2

RNFirebase Version:
"react-native-firebase": "^3.2.3",

Firebase Module:
Storage

**Comment by neeboo** [comment]
Same problem came to me last night

Something happened using cocoapods with RN 0.52

 I've tried work around with "firebase frameworks" downloaded from firebase, and import the dependencies directly. Build Successfully, but crashed on app start.

**Comment by chrisbianca** [comment]
@thedc89 @neeboo Can we see your `Podfile` please?

**Comment by thedc89** [comment]
Sure, I edited my question above

**Comment by neeboo** [comment]
@chrisbianca Here's mine

platform :ios, '9.3'
target "MyAwesomeProject" do
  pod 'Firebase/Core'
  pod 'Firebase/Auth
end

**Comment by khsily** [comment]
In my case,
Deleting "React" folder in "Pods" solved the problem.

**Comment by khsily** [comment]
In my case,
Deleting "React" folder in "Pods" solved the problem

**Comment by khsily** [comment]
In my case,
Deleting "React" folder in "Pods" solved the problem

**Comment by chrisbianca** [comment]
I'm unclear why you're having these errors if you're not specifying React as a pod.
Have you in the past?  I'd suggest completely deleting your Pods folder (leave your podfile) and re-running pod install.

**Comment by chrisbianca** [comment]
Closing due to lack of response. Please re-open if this is still an issue and include the details requested above.

**Comment by yoonsy** [comment]
I faced same issue and after deleting my Pods folder and re-running pod install, it works! Thanks @chrisbianca

**Comment by phil-andrews** [comment]
Same problem, no solution posed her has worked. Why would this happen suddenly without touching RNFB?

**Comment by thedc89** [comment]
Same again, recently I solved it by running `pod deintegrate` and `pod install` but does not work anymore
<img width="974" alt="zrzut ekranu 2018-02-25 o 19 30 05" src="https://user-images.githubusercontent.com/4841004/36644992-9f5dba5a-1a62-11e8-872d-25b642772519.png">

**Comment by ethanyuwang** [comment]
Having the same problem here. Have tried every solution none of them worked.

my Podfile:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'myproject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myproject
  pod 'Firebase/Core'
```

**Comment by neeboo** [comment]
I’m not quite sure but i think it is related to cocoapods when i came into another [problem](https://github.com/firebase/firebase-ios-sdk/issues/750).

see also [here](https://github.com/CocoaPods/Xcodeproj/issues/544)

After I tried these:
sudo gem update
sudo gem install cocoapods
sudo gem install xcodeproj


Then 
pod update, clean project and reboot

Then
build


Both problems seem solved

**Comment by thedc89** [comment]
@neeboo unfortunately this did not work for me ;(

**Comment by mattop1709** [comment]
@neeboo that didn't work with me either...done updating the pods..

**Comment by evanjmg** [comment]
deleting React pod seems to work for me

**Comment by evanjmg** [comment]
Still having issues, definitely need to remove the React pod dependency from this library and use the node modules version.

**Comment by thedc89** [comment]
@evanjmg Have you managed to get rid of this issue?

**Comment by thedc89** [comment]
@evanjmg Could you describe step by step what you have done and your final Podfile looks like? This might be very helpful. 
When I deleted my React pod from the folder, it started to show the issue described here #807

**Comment by evanjmg** [comment]
I didn't have that issue, but try adding subspecs? 
 pod 'React', :path => '../node_modules/react-native', :subspecs => ['DevSupport'] 

# Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'

**Comment by benevbright** [comment]
I had the same issue and following resolved my issue.

remove ios/Pods by `rm -rf ios/Pods`.
remove `Podfile.lock`.
remove lines in Podfile that you didn't add but there is.
`pod install`

The problem is gone.

**Comment by phil-andrews** [comment]
@benevbright This is ultimately what I did as well. There are bunch of unnecessary pods that got added somewhere in here, and I'm pretty sure it's RNFB. Delete them, delete your pods, clean project, reinstall pods.

**Comment by thedc89** [comment]
@benevbright does not work for me, still getting the issue. To get rid of the error, I use @evanjmg solution, but it eventually ends up with #807

**Comment by alexandrzavalii** [comment]
Removing RNFirebase and adding it again from "Link Binaries With Libraries" works for me.

**Comment by srameshr** [comment]
Same here :(

**Comment by thedc89** [comment]
The problem occurs only when node modules for some other libraries are linked in Podfile. After I added all other libraries manually and do not run react-native link, it's all fine
