### ISSUE TITLE
[🐛] Bug Report Title - Facebook [Error: [auth/invalid-credential] The supplied auth credential is malformed or has expired.]

### ISSUE THREAD

**Issue by VadymBezsmertnyi** [invertase/react-native-firebase#8086]
Good afternoon! 
I've been trying to fix an error when logging in with Facebook for 2 days:
[Error: [auth/invalid-credential] The supplied auth credential is malformed or has expired.]
It works fine with Apple and Google, but not with Facebook.
My function:

> const facebookSignIn = async () => {
>     setIsLoading(true);
>     try {
>       const dataPrev = await AccessToken.getCurrentAccessToken();
>       const result = dataPrev
>         ? {
>             isCancelled: false,
>           }
>         : await LoginManager.logInWithPermissions(['public_profile', 'email']);
>       if (result.isCancelled) {
>         Alert.alert('Error', 'User cancelled the login process');
>         return false;
>       }
>       const data = await AccessToken.getCurrentAccessToken();
>       if (!data) {
>         Alert.alert('Error', 'Something went wrong obtaining access token');
>         return false;
>       }
>       const facebookCredential = auth.FacebookAuthProvider.credential(
>         data.accessToken,
>       );
>       const resultAuth = await auth().signInWithCredential(facebookCredential);
>       if (resultAuth.user) {
>         await createUser(
>           resultAuth.user.displayName || '',
>           resultAuth.user.email || '',
>         );
>       }
>       setUser(resultAuth.user);
>       createPasswordWithSocial();
>       return true;
>     } catch (error: any) {
>       sendCustomError(error, 'Error on create user with Facebook');
>       if (userUUID)
>         track({
>           uuid: userUUID,
>           event: 'Error on create user with Facebook',
>           properties: {
>             UID: userUUID,
>             Reason: error instanceof Error ? error.message : (error as string),
>             function: 'facebookSignIn',
>           },
>         });
>       return false;
>     } finally {
>       setIsLoading(false);
>     }
>   };

  
The error occurs specifically on the line **const facebookCredential = auth.FacebookAuthProvider.credential(data.accessToken);**

_I also tried using Facebook Limited Login (iOS only), but that didn't help either._

![image](https://github.com/user-attachments/assets/6cae37b3-87f9-49b5-9c9d-794ac92c8e37)

- The project is old, about 3 years old. Before this, it was written in Swift, but the Facebook authentication also doesn't work on it.

**Comment by mikehardy** [comment]
This is the error I personally saw that happens when you do not implement limited login correctly
I would triple check, then check again, the limited login implementation. I might even just redo it completely following the limited login documentation on rnfirebase.io

That's what I did anyway, and I started getting correct logins

**Comment by VadymBezsmertnyi** [comment]
@mikehardy 
Thank you for the response.
I’ve checked and compared everything on developers.facebook.com and Firebase, and everything is set up correctly. How can I remove restricted login or configure it to work properly?

**Comment by VadymBezsmertnyi** [comment]
@mikehardy 
I managed to get Limited Login working with the following code:

> const facebookSignIn = async () => {
>     setIsLoading(true);
>     try {
>       const nonce = uuidv4();
>       console.log('nonce', nonce);
>       const nonceSha256 = await sha256(nonce);
>       console.log('nonceSha256', nonceSha256);
>       const test = await auth()
>         .signOut()
>         .then(() => true)
>         .catch(() => false);
>       console.log('test', test);
>       const dataPrev = await AuthenticationToken.getAuthenticationTokenIOS();
>       console.log('dataPrev', dataPrev);
>       const result = dataPrev
>         ? { isCancelled: false }
>         : await LoginManager.logInWithPermissions(
>             ['public_profile', 'email'],
>             'limited',
>             nonceSha256
>           );
>       console.log('result', result);
>       if (result.isCancelled) {
>         Alert.alert('Error', 'User cancelled the login process');
>         return false;
>       }
>       const data = await AuthenticationToken.getAuthenticationTokenIOS();
>       console.log('data', data);
>       if (!data) {
>         Alert.alert('Error', 'Something went wrong obtaining access token');
>         return false;
>       }
>       const facebookCredential = auth.FacebookAuthProvider.credential(
>         data.authenticationToken,
>         nonce
>       );
>       console.log('facebookCredential', facebookCredential);
>       const resultAuth = await auth().signInWithCredential(facebookCredential);
>       console.log('resultAuth', resultAuth);
>       if (resultAuth.user) {
>         await createUser(
>           resultAuth.user.displayName || '',
>           resultAuth.user.email || ''
>         );
>       }
>       setUser(resultAuth.user);
>       createPasswordWithSocial();
>       return true;
>     } catch (error) {
>       sendCustomError(error, 'Error on create user with Facebook');
>       if (userUUID) {
>         track({
>           uuid: userUUID,
>           event: 'Error on create user with Facebook',
>           properties: {
>             UID: userUUID,
>             Reason: error instanceof Error ? error.message : String(error),
>             function: 'facebookSignIn'
>           }
>         });
>       }
>       return false;
>     } finally {
>       setIsLoading(false);
>     }
>   };

However, this approach doesn’t merge accounts in Firebase, resulting in the error: _[Error: [auth/account-exists-with-different-credential] An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address.]_

Is there a way to either merge accounts or disable Limited Login entirely?

**Comment by mikehardy** [comment]
I don't believe accounts are ever merged automatically? That's something you have to handle, and unfortunately it's made a bit more difficult with email enumeration restrictions on firebase side - you have to handle that exception and get the user to login using their existing method then link. There are guides for thus on the internet or you could ask on stackoverlow 

Facebook - as far as I know - requires limited login for nearly everyone now, but in either case you would ask Facebook or stackoverlow, not here in a firebase repository 

Your original issue was token issues, and that was an implementation problem in your project. The code in this repository is working fine and allowing logins as you have mentioned so there is no issue here in the repository

**Comment by VadymBezsmertnyi** [comment]
@mikehardy 
Thank you for the clarification.
