### ISSUE TITLE
🚀 [firebase_crashlytics] Add methods to NativeHelper 

### ISSUE THREAD

**Issue by 15matias15** [invertase/react-native-firebase#8093]
## What feature would you like to see?

Currently android package `ReactNativeFirebaseCrashlyticsNativeHelper` expose this 3 methods:

<img width="727" alt="Screenshot 2024-10-28 at 12 00 07" src="https://github.com/user-attachments/assets/574aec9f-a967-4532-9b9d-2e40f048d339">

while on iOS, the same package `RNFBCrashlyticsNativeHelper` expose only 1 method:
<img width="462" alt="Screenshot 2024-10-28 at 12 01 10" src="https://github.com/user-attachments/assets/1e239c10-0737-4c75-ac9b-fb6ac58238af">

We have a RN cross platform that currently is making use of the log & setCustomKey on android side, it will be nice to have it alos exposed on iOS side.

**Comment by mikehardy** [comment]
Sure, almost as easy to add it as to verify the assertion that it exists on android but not iOS, did it while I was looking

You can grab the patch-set here for local integration until it is merged+released https://github.com/invertase/react-native-firebase/actions/runs/11596186764?pr=8104
