### ISSUE TITLE
Is a way to run it with Expo?

### ISSUE THREAD

**Issue by tranotheron** [invertase/react-native-firebase#81]
My question is like in topic.

Is there a way to run it with Expo.io?

**Comment by Ehesp** [comment]
Hi, not actually got any experience with expo. I can take a look tomorrow, not sure how it works with native modules.

**Comment by Salakar** [comment]
Afaik you have to eject out of expo which creates the files that you'd see in a standard RN app, then you can add native modules. Think there was a cmd on the cli to do this,  just remember you can't revert back.

**Comment by Salakar** [comment]
Yep as above, see: https://docs.expo.io/versions/v14.0.0/guides/exponentkit.html - the detaching section.

**Comment by tranotheron** [comment]
Thanks guys! :-)
