### ISSUE TITLE
workaround below - Undefined symbols "absl::lts_20240116::CHexEscape(absl::lts_20240116::string_view)"

### ISSUE THREAD

**Issue by mikehardy** [invertase/react-native-firebase#8103]
If you experience an iOS build failure during the link step with a bunch of errors that look like this:

> Undefined symbols for architecture arm64
❌ "absl::lts_20240116::CHexEscape(absl::lts_20240116::string_view)", referenced from:

It is not coming from this library, it is upstream issue https://github.com/firebase/firebase-ios-sdk/issues/13996

It is related to an interaction between cocoapods 1.16+ and the abseil library from firebase-ios-sdk.

You can either: 

1- downgrade your ruby gems to cocoapods 1.15.2 and xcodeproj 1.25.0 or
2- use a post_install workaround in your Podfile that changes one build setting back to what it was prior to cocoapods 1.16+ and allows the build to work

Here is the workaround if you are interested, note you may already have a post_install section, so you would just use the inner part(s):

[note: this was edited to be `gnu++14` not `c++14`]

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'abseil'
      Pod::UI.puts "Workaround: Configuring abseil to use gnu++14 language standard for cocoapods 1.16+ compatibility".yellow
      Pod::UI.puts "            Remove workaround when upstream issue fixed https://github.com/firebase/firebase-ios-sdk/issues/13996".yellow
      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++14'
      end
    end
  end
end
```

You will need to run `pod install` again after adding this, so that it executes and updates the build setting

**Comment by stephentuso** [comment]
For anyone using expo managed workflow - I added it in a plugin:

**fix-rn-firebase.plugin.js**
```js
const { withDangerousMod, withPlugins } = require("@expo/config-plugins");
const {
  mergeContents,
} = require("@expo/config-plugins/build/utils/generateCode");
const fs = require("fs");
const path = require("path");

async function readFileAsync(path) {
  return fs.promises.readFile(path, "utf8");
}

async function saveFileAsync(path, content) {
  return fs.promises.writeFile(path, content, "utf8");
}

const withFixBuildSettings = (c) => {
  return withDangerousMod(c, [
    "ios",
    async (config) => {
      const file = path.join(config.modRequest.platformProjectRoot, "Podfile");
      const contents = await readFileAsync(file);
      await saveFileAsync(file, fixBuildSettings(contents));
      return config;
    },
  ]);
};

const fixSrc = `
    installer.pods_project.targets.each do |target|
      if target.name == 'abseil'
        Pod::UI.puts "Workaround: Configuring abseil to use gnu++14 language standard for cocoapods 1.16+ compatibility".yellow
        Pod::UI.puts "            Remove workaround when upstream issue fixed https://github.com/firebase/firebase-ios-sdk/issues/13996".yellow
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++14'
        end
      end
    end
`;

function fixBuildSettings(src) {
  return mergeContents({
    tag: `rn-firebase-fix-build`,
    src,
    newSrc: fixSrc,
    anchor: /post_install do \|installer\|/,
    offset: 1,
    comment: "#",
  }).contents;
}

module.exports = (config) => withPlugins(config, [withFixBuildSettings]);
```

`npm i --save-dev @expo/config-plugins` if you haven't already and add that file to your expo plugins list

**Comment by mikehardy** [comment]
@stephentuso with the just-released cocoapods 1.16.2 and xcodeproj 1.27 no workarounds are necessary for this issue - they reverted the breaking change

I'm going to close it, as current versions are now working fine

**Comment by ics-vandit** [comment]
> ```ruby
> CLANG_CXX_LANGUAGE_STANDARD
> ```

this is not working for me

**Comment by mikehardy** [comment]
@ics-vandit the issue is closed. Current versions of cocoapods / xcodeproj require no fix
Thus no one should require a fix nor a workaround nor anything other than: update your cocoapods + xcodeproj gems / installation to current
