### ISSUE TITLE
Performance Monitoring not working

### ISSUE THREAD

**Issue by EyreGe** [invertase/react-native-firebase#812]
my project add Analytics、Crashlytics、Performance Monitoring, I can see result with Analytics and Crashlytics in console. Performance Monitoring not result and 'install SDK' visible.

react-native run android.

React Native version (e.g. 0.45.1): 0.51.0
RNFirebase Version (e.g. 2.0.2): ^3.2.4

**Comment by Ehesp** [comment]
How long did you wait? Results are not realtime.

**Comment by EyreGe** [comment]
@Ehesp I 'am waiting two days. It's not working and not error.

**Comment by EyreGe** [comment]
@Ehesp It's working today. I don't know why! But Thanks!
