### ISSUE TITLE
[🐛] Build Failure After Installing React Native Firebase : React Native 0.74.5

### ISSUE THREAD

**Issue by mohamedziadjabbad** [invertase/react-native-firebase#8129]
After installing react-native-firebase/app and setting up Firebase in the React Native project, the following errors occur during the build process:

  - Library not found for -lReact-hermes
  - Linker command failed with exit code 1 (use -v to see invocation)
 

Steps to Reproduce:

  - Install react-native-firebase/app following the setup documentation.
  - Configure Firebase in AppDelegate.mm as required.
  - Attempt to build the project in Xcode.

Result: The build fails with the error "Library not found for -lReact-hermes" and "Linker command failed with exit code 1."

<img width="1399" alt="Screenshot 2024-11-13 at 09 43 05" src="https://github.com/user-attachments/assets/94244509-0310-49c1-b2d8-4324eda60910">

**Comment by mikehardy** [comment]
Hi there!

The build works fine - steps to reproduce:

1- download build demonstrator that starts from `npx react-native init` https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
2- drop your apple and android plist/json google services files in there
3- run it

There's no problem with the library, but there are frequently problems with the integration of native modules that are project-specific

The comments in that script document every step it performs so it will hopefully be helpful in determining where the integration went wrong in your project

**Comment by mikehardy** [comment]
side note: deleted that image it appeared to contain information in it you likely do not want to provide to the world
