### ISSUE TITLE
storage putFile() ignores custom metadata

### ISSUE THREAD

**Issue by jonaseck2** [invertase/react-native-firebase#814]
### Issue

storage putFile() ignores custom metadata. Standard metadata such as contentType works.

```
import firebase from 'react-native-firebase';

firebase.storage()
      .ref().child(storageName)
      .putFile(data.path, { contentType: 'video', uid: this.props.user.uid, "okok": "okok"})
```

Expected: metadata "contentType", "uid", and "okok" listed in firebase storage ui for the uploaded file

Actual: contentType is correctly set, but no other custom metadata is present

### Environment

Android

1. Application Target Platform: macOS Sierra

2. Development Operating System: react-native run-android, Nexus P6 API 26.

3. Build Tools: ?

4. React Native version: ^0.52.1

5. RNFirebase Version: ^3.2.2

6. Firebase Module: storage

**Comment by chrisbianca** [comment]
@jonaseck2 Can you try putting the custom data into a `customMetadata` object:

```
firebase.storage()
      .ref().child(storageName)
      .putFile(data.path, { contentType: 'video', customMetadata: { uid: this.props.user.uid, "okok": "okok"}})
```

Storage is another area that we need to take a look at after FCM as it's not had much attention, but I'm fairly sure this may be an undocumented `feature`

**Comment by chrisbianca** [comment]
Closing due to lack of response - Please let us know if this doesn't work.

**Comment by jonaseck2** [comment]
Yeah, it works. Good to know is the key is omitted if the value is null

**Comment by anhnch** [comment]
```javascript
ref.putFile('path/to/file.jpg', {
    customMetadata: {
        uid: 'abc', // this works
        firebaseStorageDownloadTokens: token // => [storage/unknown] An unknown error has occurred
    }
})
```

**Comment by mikehardy** [comment]
@anhnch you are commenting on issue from more than 4 years ago, there cannot really be a valid response any longer.
If you've detected something you think is a problem, please open a new issue, ideally with these in mind 
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example
