### ISSUE TITLE
The following build commands failed: 	CompileC RNFBCrashlytics.build/Objects-normal/arm64/RNFBCrashlyticsInitProvider.o node_modules/@react-native-firebase/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsInitProvider.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNFBCrashlytics' from project 'Pods') 	Building workspace Thrive with scheme Thrive and configuration Debug (2 failures)

### ISSUE THREAD

**Issue by kyle-belle** [invertase/react-native-firebase#8142]
Im using expo ("~50.0.13")
When trying to run on the ios simulator the build fails with the following error
```cmd
The following build commands failed:
	CompileC /Users/kylebelle/Library/Developer/Xcode/DerivedData/Thrive-coshjuovgibntngmykkuqctwjwjr/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNFBCrashlytics.build/Objects-normal/arm64/RNFBCrashlyticsInitProvider.o /Users/kylebelle/Documents/GitHub/thrive/node_modules/@react-native-firebase/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsInitProvider.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNFBCrashlytics' from project 'Pods')
	Building workspace Thrive with scheme Thrive and configuration Debug
(2 failures)
```

i included the plugin in app.json ("@react-native-firebase/crashlytics").
this is with the latest xcode version (16.1 [16B40])

im using `"@react-native-firebase/crashlytics": "^21.2.0",`

**Comment by mikehardy** [comment]
Hi there, you haven't included the necessary information to troubleshoot this, which is clearly requested in the template, so this will be closed.

However, if crashlytics is failing to build, it is most likely this duplicated issue

- #8127

You will want to make absolutely sure that you have not pinned the firebase-ios-sdk version anywhere, and that it is resolving to the correct version.

You indicate v21.2.0 of react-native-firebase, I encourage you to use the version 21.5.0 just released today, or at least 21.4.1 as it likely would fix your issue 

https://github.com/invertase/react-native-firebase/blob/main/CHANGELOG.md#2141-2024-11-13
