### ISSUE TITLE
[🐛] Incompatibility of superstruct versions when using @react-native-firebase/app and @solana/web3.js.

### ISSUE THREAD

**Issue by exzos28** [invertase/react-native-firebase#8152]
**Problem Description**

The project uses two dependencies:
	•	@react-native-firebase/app, which relies on superstruct@^0.6.2.
	•	@solana/web3.js, which relies on superstruct@^2.0.2

When integrating both libraries, there is a version conflict because each library expects a different, incompatible version of superstruct: 
Once I import `import analytics from '@react-native-firebase/analytics';`
I get an error `_index.default is not a function (it is undefined)`
<img src="https://github.com/user-attachments/assets/c545dfa2-dc83-4255-ae81-c7b0afbd47c9" width="150px" />

Yes, I know that different versions should be handled by the package manager - yarn, npm and so on, but I really don't know why it doesn't happen.

**Suggested Fix**

Upgrade the superstruct version in `@react-native-firebase/app` to be compatible with `@solana/web3.js` (e.g., ^2.0.2).

**Comment by exzos28** [comment]
Didn't write the main things:
The project where this error occurs uses a monorepository based on yarn workspaces and yarn 3.6.4 (which is used with react-native 0.75 projects). All dependencies are in the root node_modules (with no separation into submodules).

When clicking on import `import superstruct from 'superstruct/lib/index';` it sends me to the root (where `superstruct 2.0.0` from solana is). For some reason the import does not lead to the subtree inside `@react-native-firebase/app/node_modules`;

**Comment by mikehardy** [comment]
...and then I see your PR - if CI likes that, I like that. It should work?
You'll be able to get a patch set for testing via patch-package here once run is done:

https://github.com/invertase/react-native-firebase/actions/runs/11940133200?pr=8153

**Comment by exzos28** [comment]
- I can't override the global version of the superstruct - it has a completely different API, and it won't work in react-native-firebase.
- Other than that, it looks right. But why it is not resolved by imports I don't know.
```
  ├─┬ @react-native-firebase/app@21.5.0
  │ └── superstruct@0.6.2
  ├─┬ @solana/spl-token@0.3.11
   └─┬ @solana/buffer-layout-utils@0.2.0
     └─┬ @solana/web3.js@1.95.3
       └── superstruct@2.0.2
```

It seemed to me that the most effective thing to do here would be to try to update superstruct -- especially since it is already necessary.

And then deal with imports in the project... or not 😁

> If there is any way you can put a resolution pinned for the specific version in your subtree package.json perhaps that would work around it?

**Comment by exzos28** [comment]
And yes, I've checked the patch and can confirm that it helped to get rid of the error.

**Comment by mikehardy** [comment]
really appreciated that PR, just kicked off a publish with it merged, should be a new version up for you in just a few minutes
Cheers
