### ISSUE TITLE
is this a typo on doc?

### ISSUE THREAD

**Issue by sibelius** [invertase/react-native-firebase#816]
![image](https://user-images.githubusercontent.com/2005841/35929851-9bcc9bc6-0c17-11e8-9701-a656535d514f.png)

is this a typo?

`classpath` should be `compile`?

**Comment by aMarCruz** [comment]
I think the documentation is correct. The plugin's perf module is applied in android/app/build.gradle

**Comment by chrisbianca** [comment]
Yep, this documentation is definitely correct.
