### ISSUE TITLE
[🐛] Bug Report onMessage triggers twice on notification ios - CHANGE ME 

### ISSUE THREAD

**Issue by shandurrani428** [invertase/react-native-firebase#8166]
useEffect(() => {
    requestUserPermission();
  
    const unsubscribe = messaging().onMessage(async remoteMessage => {
      console.log('Hit twice:', remoteMessage)});
    return unsubscribe;
  }, []);
  
  having this issue hitting twice remoteMessage in ios and android

**Comment by mikehardy** [comment]
Have you searched the issues list? I believe this is duplicate
But most importantly, you deleted every bit of information from the issue template, so I will close this issue as we have no information useful to troubleshoot with
