### ISSUE TITLE
jest tests fail with [RNFirebase core module was not found...]

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#817]
### Environment

1. Application Target Platform: iOS / Android / nodejs

2. Development Operating System: macOS High Sierra

3. Build Tools: XCode 9.2, Android Studio 3

4. React Native version: 0.53

5. RNFirebase Version: 3.2.4

6. Firebase Module: Native iOS

---

I was working on implementing basic jest test and got error like this after running it:

>    RNFirebase core module was not found natively on iOS, ensure you have correctly included the RNFirebase pod in your projects `Podfile` and have run `pod install`.
>     
>    See http://invertase.link/ios for the ios setup guide.

This does not pop up when I run iOS app, works perfectly there. Is there something specific to test env jest uses that I need to alter / add in order to fix this? This is running default jest test by the way, one that renders full app

```
import "react-native";
import React from "react";
import App from "../";

import renderer from "react-test-renderer";

it("App renders correctly", () => {
  const tree = renderer.create(<App />);
});
```

**Comment by chrisbianca** [comment]
@IljaDaderko Please see the issue here: https://github.com/invertase/react-native-firebase/issues/162

You'll have to mock out RNFirebase for this to work as Jest doesn't have access to the native environment at all.
