### ISSUE TITLE
[📚] Documentation Issue Title - CHANGE ME      all pic is GG

### ISSUE THREAD

**Issue by hanwenbo** [invertase/react-native-firebase#8172]
## Documentation Feedback

Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:
<img width="1111" alt="image" src="https://github.com/user-attachments/assets/d5d0d062-c7de-4250-a35f-7ccf977c1b27">

![Uploading image.png…]()
https://images.prismic.io/invertase/01fefe19-132f-4b88-8c17-9dc40357e4ce_apple-key.png?auto=format

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Does not appear to describe an issue, closing

**Comment by hanwenbo** [comment]
Because you restored it
