### ISSUE TITLE
Mismatched GoogleDataTransportCCTSupport version in Podfile with Expo 52.0.9 and React Native 0.76.2

### ISSUE THREAD

**Issue by Ajay12234567898765432** [invertase/react-native-firebase#8173]
I am experiencing an issue with GoogleDataTransportCCTSupport in the Podfile when integrating react-native-firebase in my iOS project. Despite upgrading and downgrading the library versions, the problem persists. Below are the relevant details of my project and the error I am encountering.

Project Details:

Expo Version: 52.0.9
React Native Version: 0.76.2
react-native-firebase Version: 14.12.0
Xcode Version: Version 16.1 (16B40)
iOS Version: 15.1

Problem:
After installing react-native-firebase and resolving all dependencies, I am facing an issue with mismatched versions of GoogleDataTransportCCTSupport in the Podfile. This results in build failures when trying to run the app on iOS. I have tried both upgrading and downgrading the react-native-firebase package, but the issue persists.

The specific error message is:

[ERROR] Mismatched version of GoogleDataTransportCCTSupport in the Podfile.

What I've Tried:

Upgrading and downgrading react-native-firebase to different versions.
Running pod repo update and pod install after clearing derived data.
Ensuring that the correct versions of dependencies are specified in the Podfile.
Manually modifying the Podfile to try and resolve the version conflict, but without success.

**Comment by mikehardy** [comment]
>  After installing react-native-firebase and resolving all dependencies, I am facing an issue with mismatched versions of GoogleDataTransportCCTSupport in the Podfile.

Can you provide evidence of the alleged mismatch? error message text, build log output, Podfile.lock etc? I can't do anything with the information provided unfortunately

**Comment by Ajay12234567898765432** [comment]
//ios.podfile
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

$RNFirebaseAsStaticFramework = true

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

platform :ios, podfile_properties['ios.deploymentTarget'] || '13.0'
install! 'cocoapods', :deterministic_uuids => false
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

# If Flipper is not needed, you can comment out the next block:
# if !ENV['CI']
#   use_flipper!({ 'Flipper' => '0.75.1' })
# end

target 'Idaho Lottery' do
  use_expo_modules!
  config = use_native_modules!

  flags = get_default_flags() # Proper initialization of flags

  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps'
  # pod 'GoogleMaps'
  # pod 'Google-Maps-iOS-Utils'
  pod 'GoogleMaps', '8.4.0'
  pod 'Google-Maps-iOS-Utils', '5.0.0'
  pod 'GoogleDataTransport', '~> 10.0'

  pod 'react-native-passkit-wallet', path: '../node_modules/react-native-passkit-wallet'
  
  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"]
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']

  # If Flipper is needed for debugging, you can uncomment this block:
  # if !ENV['CI']
  #   use_flipper!({ 'Flipper' => '0.75.1' })
  # end

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled] || podfile_properties['expo.jsEngine'] == 'hermes',
    :app_path => "#{Dir.pwd}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false'
  )

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        config.build_settings['mac_catalyst_enabled'] = false
        config.build_settings['ccache_enabled'] = podfile_properties['apple.ccacheEnabled'] == 'true'

        # Ensure iOS deployment target is set to a minimum of 13.0
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] < '13.0'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
      end
    end

    react_native_post_install(installer)
    if !ENV['CI']
      flipper_post_install(installer) # Uncomment this if using Flipper
    end
  end
end
![image](https://github.com/user-attachments/assets/3d7651eb-c1ae-47e1-9a3b-6a0124fa2a08)

**Comment by Ajay12234567898765432** [comment]
![image](https://github.com/user-attachments/assets/d22dca86-51e6-4fa6-b0d6-512b9e8e865e)

**Comment by Ajay12234567898765432** [comment]
@mikehardy Can you please check the above reference

**Comment by mikehardy** [comment]
I see.

I have edited your comment to provide syntax highlighting to the Podfile code, so that it is readable. It was impossible to read before - for future reference in github markdown you can place code in triple-backticks with a language specifier to format things so they are readable, for instance:

```ruby
  # this could be some ruby code
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled] || podfile_properties['expo.jsEngine'] == 'hermes',
    :app_path => "#{Dir.pwd}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false'
  )
```

The error you are seeing is not something this repository is responsible for however, I suggest you have a project-specific problem.

The error is quite specific.

It may have something to do with this line

> platform :ios, podfile_properties['ios.deploymentTarget'] || '13.0'

But as mentioned, this is not something that is an error in this repository and won't result in a change in this repository, so it is not actionable here, thus I will close the issue
