### ISSUE TITLE
Firestore get() at launch fails in release

### ISSUE THREAD

**Issue by kevboh** [invertase/react-native-firebase#819]
### Issue

In bundled release versions of my app, making a firestore `get()` request immediately on launch fails.

In my app entrypoint I make a collection `get()` request to check a version flag and, if necessary, kick off another, much larger `get()`. That first request seems to fail with a `Firestore: The service is currently unavailable. (firestore/unavailable)` error, but only in release versions of my app. Running in debug mode or connected to the react native debugger seems to not trigger this error.

I have not yet tried to reproduce in a test project, but plan to do so tomorrow—I've been trying to nail down this issue for a few hours now 😓 .

### Environment

1. Application Target Platform: Both

2. Development Operating System: macOS High Sierra

3. React Native version: 0.47.2

4. RNFirebase Version: 3.2.1

5. Firebase Module: firestore

**Comment by kevboh** [comment]
Digging through the iOS SDK, it seems like the underlying `FIRFirestoreErrorCodeUnavailable` is only thrown when offline: https://github.com/firebase/firebase-ios-sdk/blob/729b8d176c75ecc0cbbd137cc6811116a64e310a/Firestore/Source/API/FIRDocumentReference.mm#L239

And it seems like that error is just passed through in react-native: https://github.com/invertase/react-native-firebase/blob/40125d8eb6e8d7ee09fd3464a1497bbdd05353a9/ios/RNFirebase/firestore/RNFirebaseFirestore.m#L240

Not sure if I'm following the source properly, but it seems like firestore may think it's offline immediately after launch.

**Comment by chrisbianca** [comment]
@kevboh Are you using a different firebase project for your release and debug versions? It could be that your projects are set up differently if so?

**Comment by kevboh** [comment]
@chrisbianca I am not—same project for both.

**Comment by chrisbianca** [comment]
Ok, just wanted to check as that's a common mistake where the projects are set up differently.

Have you tried delaying your initial `get` request to see whether that resolves the problem?  I'm not saying this is a long term workaround, I'm just keen to identify exactly where the issue lies.

**Comment by kevboh** [comment]
I have, and delaying seems to work. I thought `firebase.firestore().app.onReady()` looked promising, but I still get the error when wrapping my request in it.

**Comment by kevboh** [comment]
I'm trying to think of ways in which my firebase setup might be special, but I can't think of any. I've reproduced this a bunch of times in my project, but have yet to make a test project—I'm on a pretty tight deadline at the moment.

**Comment by chrisbianca** [comment]
Yes, this is quite a strange one, and a bit of a nightmare to debug!

I've just taken a look at the `onReady` and with natively initialized apps, i.e. the one from your .plist (iOS)/.json (Android) file, we do assume they are ready at the point the JS initialises so in this instance `onReady` will always just return.

@Salakar do you think it's possible for us to tweak this to make sure the native app is ready?

**Comment by Salakar** [comment]
@chrisbianca aye it's possible to modify it to always check native for ready status but i'm not sure if there's any way on native side to check it is actually ready for the default app - the event it listens for:

https://github.com/invertase/react-native-firebase/blob/master/lib/modules/core/firebase-app.js#L164

and is only based on when the native initialise app promise resolves from here: https://github.com/invertase/react-native-firebase/blob/master/lib/modules/core/firebase-app.js#L68 - there is no checks on native side to say it's ready or not as it's meant to be immediately available on calling initialise natively - not sure where we can check to make sure that it actually is - seems to be a firestore specific thing this hmm

**Comment by chrisbianca** [comment]
It looks like they're in the process of adding explicit online/offline controls - they've added them to JS and iOS but not Android yet.

@kevboh It might be worth flagging this with Firebase directly as well?

**Comment by corysimmons** [comment]
@chrisbianca Is this the feature you're talking about? https://firebase.google.com/docs/firestore/manage-data/enable-offline

Seems to be supported now?

If not, could you link to me where I can track this?

**Comment by corysimmons** [comment]
That's fair. Do you happen to know if there's an active issue for this where we can thumbs up them to death? :D

**Comment by chrisbianca** [comment]
Not that I'm aware of, sorry

**Comment by aMarCruz** [comment]
Could this be an RN issue?
In the native code for `PermissionsAndroid`, I'm seeing this:
![image](https://user-images.githubusercontent.com/6636980/37278202-943b3e9a-25ac-11e8-83d0-9758e4c55f61.png)

And really the exception is being generated with a UI already fully loaded at the start of my App, so I had to use a workaround calling to `InteractionManager.runAfterInteractions` in a recursive fassion if the error is generated. Seems solves my issue.

After 4 months of development, I'm very dissapointed with RN ...too many important issues. Right now RN 0.53.3 has problems with Animation, Promises and setTimeout, fortunately, most in development mode.

I think RN is not ready for producction. Will it ever be? I hope so, but 0.54.0 is using a very young alpha of React instead the more mature 16.2... mmm :(

**Comment by chrisbianca** [comment]
Firebase have now made the enableNetwork and disableNetwork functions available on Android and iOS.  We've added these to the upcoming v4 release which should help address this issue.
