### ISSUE TITLE
[🐛] App crashing when tried to integrate Crashlytics library into React Native Firebase

### ISSUE THREAD

**Issue by ChandrakalaHM** [invertase/react-native-firebase#8195]
> Currently using React native version 0.64, but Crashlytics library is not supported by this version.  Crashlytics library is very much needed for the project, there is problem with the following line of code  _**use_frameworks! :linkage => :static**_
Is there any way we can integrate Crashlytics library for React native version 0.64.

**Comment by mikehardy** [comment]
react-native 0.64 is not supported nor is it supportable that I'm aware of.
The general policy in react-native is for modules to support the current react-native version and the 2 most recent version after that.

So right now that would be 0.76, 0.75, and 0.74

Deferring updates just makes them more painful unfortunately
