### ISSUE TITLE
Error: Failed to call into JavaScript module method AppRegistry.startHeadlessTask()

### ISSUE THREAD

**Issue by alized559** [invertase/react-native-firebase#8199]
I am getting this error when sending notification and app is in background. Note that I am receiving the noc correctly while the app is opened.

I added the google-services.json and edited AndroidManifest and build.gradle but still facing the issue.

The error:
 (NOBRIDGE) ERROR  Error: Failed to call into JavaScript module method AppRegistry.startHeadlessTask(). Module has not been registered as callable. Registered callable JavaScript modules (n = 9): GlobalPerformanceLogger, RCTNativeAppEventEmitter, RCTEventEmitter, SamplingProfiler, RCTDeviceEventEmitter, HMRClient, RCTLog, HeapCapture, Systrace. Did you forget to call `registerCallableModule`?

index.js:
/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import messaging from '@react-native-firebase/messaging';

messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('Message handled in the background!', remoteMessage);
});

AppRegistry.registerComponent(appName, () => App);

packages:
 "react-native": "0.76.0",
"@react-native-firebase/app": "^21.6.1",
"@react-native-firebase/messaging": "^21.6.1",

**Comment by mikehardy** [comment]
Please try again with a new issue where you do not delete the issue template, rather, you fill in the template with the requested information

**Comment by mikehardy** [comment]
Also headlessJS had issues until the most recent release, plus upgrade to react-native 0.76.5

> "react-native": "0.76.0",

**Comment by Abhimanyuydv** [comment]
I am getting this error when sending notification and app is in background. Note that I am receiving the noc correctly while the app is opened.

I added the google-services.json and edited AndroidManifest and build.gradle but still facing the issue.

The error:
(NOBRIDGE) ERROR Error: Failed to call into JavaScript module method AppRegistry.startHeadlessTask(). Module has not been registered as callable. Registered callable JavaScript modules (n = 9): GlobalPerformanceLogger, RCTNativeAppEventEmitter, RCTEventEmitter, SamplingProfiler, RCTDeviceEventEmitter, HMRClient, RCTLog, HeapCapture, Systrace. Did you forget to call registerCallableModule?    "react-native": "0.76.0",
