### ISSUE TITLE
error RNFirebaseDatabase.on got 6 arguments, expected 5

### ISSUE THREAD

**Issue by xabree** [invertase/react-native-firebase#82]
error RN Firebase Database.on got 6 arguments expected 5 when upgrade version 1.0.1

error when initialize firebase.database().ref("posts")

```
import {Platform} from 'react-native';
import RNFirebase from 'react-native-firebase';

const configurationOptions = {
  debug: true,
  persistence: Platform == 'ios' ? false : true,
};
const firebase = new RNFirebase(configurationOptions); 
let ref = firebase.database().ref("posts");
```

**Comment by SteffeyDev** [comment]
Start by deleting node_modules and re-installing (using `npm install` or `yarn install`).  If that doesn't fix it, unlink and remove react-native-firebase and then install from github (`yarn add invertase/react-native-firebase`) and then link it again with `react-native link react-native-firebase`.  I know I had this issue and I think one of those fixed it.

**Comment by Salakar** [comment]
@xabree @SteffeyDev this issue happens because of the versioning of alpha, i.e alpha9 always installs - switch to 1.0.1^, drop your yarn.lock file and re-install - should be no need to re-link.

**Comment by xabree** [comment]
Thanks all, remove yarn.lock then re-install package solve this issue.
