### ISSUE TITLE
Phone Authentication on a device that has no SIM Card

### ISSUE THREAD

**Issue by williamliangwl** [invertase/react-native-firebase#820]
### Issue

I am trying to do phone authentication on a device that has **no** SIM Card, with the phone number inputted is active in **another** device. The result I get from this test in Android is that I get **auth/unknown** error in catch function.

More interestingly, the result vary from device to device. I tested 4 devices, 2 of them successfully "requested" code using phone number in another device and the SMS is sent successfully ( and the code in the SMS works ), while another 2 showing the error above.

The devices that are successful:
- Xiaomi A1 - Android Oreo
- Samsung Galaxy Note 2 - Android Kitkat

The devices that show the error:
- Xiaomi Redmi 5s - Android Oreo
- Oneplus 3 - Android Oreo

### Environment

1. Application Target Platform: Android, iOS ( not tested in iOS yet )

2. Development Operating System: Windows 10

3. Build Tools: VS Code

4. React Native version: 0.50.4

5. RNFirebase Version: 3.2.1

**Comment by chrisbianca** [comment]
@williamliangwl I'm afraid this is something that you'll have to report to Firebase directly and follow up with them. We're merely reporting the errors that the underlying native SDKs pass to us and can't influence this behaviour.
