### ISSUE TITLE
ios opened_from_tray is 0 when locking the device

### ISSUE THREAD

**Issue by yuoppp** [invertase/react-native-firebase#821]
### Issue
Using cloud messaging.

Lock the device when the app is in foreground.
Get a remote notification.
Click on it.

onMessage handles the notification, but `opened_from_tray` is `0`. I think it should be 1.

### Environment

iOS

1. Application Target Platform:

macOS ElCapitan

2. Development Operating System:

XCode: 8.2
IOS: 11.2.5

3. Build Tools:

react: 16.2.0

4. React Native version:

react-native: 0.52.2

5. RNFirebase Version:

react-native-firebase: 3.2.2
cloud messaging

6. Firebase Module:

Cloud Messaging

**Comment by chrisbianca** [comment]
@yuoppp We're aware of this issue - it will be fixed as part of #595

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)
