### ISSUE TITLE
improve flow types

### ISSUE THREAD

**Issue by sibelius** [invertase/react-native-firebase#822]
Are you accepting a PR to improve flow types

like this one https://github.com/invertase/react-native-firebase/blob/master/lib/modules/messaging/index.js#L154?

**Comment by chrisbianca** [comment]
@sibelius yes, we are always willing to accept PRs!

On the messaging front, we are in the process of completely rewriting this from the ground up and will be improving the flow types as part of this: #595 so you may wish to take a look at another area if you'd like to contribute.
