### ISSUE TITLE
No Virtual method getLanguageCode()Ljava/lang/String in class LCom/google/firebase/auth/FireBaseAuth

### ISSUE THREAD

**Issue by kalandher** [invertase/react-native-firebase#828]
### Environment

1. Application Target Platform: Android

2. Development Operating System: Android Studio 3.01

3. Build Tools: 2.2.3

4. React Native version: 0.53.0

5. RNFirebase Version: 3.2.4

6. Firebase Module:

had posted with code here in  [stackoverflow](https://stackoverflow.com/questions/48739568/error-while-integrating-firebase-in-react-native-no-virtual-method-getlanguagec). Please check.

**Comment by chrisbianca** [comment]
You need to update your google play service dependencies to a newer version. I'd suggest at least 11.6.2, but probably even better to go with the latest version 11.8.0.
