### ISSUE TITLE
Auth persistence on 3.2.x?

### ISSUE THREAD

**Issue by DavideValdo** [invertase/react-native-firebase#831]
I see that auth().setPersistence() is not supported as stated in https://rnfirebase.io/docs/v3.2.x/auth/reference/auth#setPersistence

I thought setting persistence on the native side was the solution, but in the docs there is no corresponding setPersistence() method as in the official JS SDK ( e. g. https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth for Android)

Is there no way to achieve offline persistence of auth state?

**Comment by chrisbianca** [comment]
@DavideValdo Auth persistence is enabled by default on the native SDKs, there's no way of turning it off.  The state is persisted across application refreshes and whilst offline (obviously until the current token expires)

**Comment by CAMOBAP** [comment]
@chrisbianca is this something that may be implemented in the future?

Let me share a bit more context, I would like to add the user's biometrics check before allowing to login (with this library https://github.com/hieuvp/react-native-fingerprint-scanner). 

My idea was to store `idToken` in secure storage which will be protected by biometrics check.

Per https://rnfirebase.io/auth/usage#listening-to-authentication-state documentation, looks like there is no way to prevent/pause `@react-native-firebase/auth` from connecting Firebase to get user auth information.

**Comment by mikehardy** [comment]
There is no way to prevent auth from maintaining a valid token, and that keeps an auth session alive, even across app restarts

There is nothing requiring you to then use the token or the session.

You can intervene in token refresh by setting different times and/or listening to token changes, you can invalidate the token at will perhaps in response to AppState transition to foreground, or app start, you can ignore the auth session until an external requirement is met. All with native
