### ISSUE TITLE
Could not invoke RNFirebaseMessaging.subscribeToTopic

### ISSUE THREAD

**Issue by SoldierCorp** [invertase/react-native-firebase#837]
### Issue

I've been using the same code for subscribing to a topic using firebase messaging but since I decided to update my packages I have the following error

![image](https://user-images.githubusercontent.com/1775881/36353039-c761a2fa-1486-11e8-80e0-99183b88107b.png)

Using this configuration in `android/build.grad;le`

     classpath 'com.android.tools.build:gradle:2.2.3'
     classpath 'com.google.gms:google-services:3.2.0'
     classpath 'io.fabric.tools:gradle:1.24.4'

And this one in `android/app/build.grandle`

    compile "com.google.android.gms:play-services-base:11.6.2"
    compile 'com.google.firebase:firebase-core:11.8.0'
    compile "com.google.firebase:firebase-crash:11.6.2"
    compile "com.google.firebase:firebase-analytics:11.6.2"
    compile "com.google.firebase:firebase-messaging:11.6.2"

The line I am using to subscribe to a topic:
    
    import firebase from 'react-native-firebase';
    
    ....
    firebase.messaging().subscribeToTopic('DEMO_ANDROID');

    

### Environment

Android

1. Application Target Platform:

macOS Sierra

2. Development Operating System:

3. Build Tools:

23.0.2

4. React Native version:

0.53.0

5. RNFirebase Version:

3.2.5

6. Firebase Module:
Firebase messaging

**Comment by chrisbianca** [comment]
@SoldierCorp All the play services dependencies should be the same version - 11.8.0

**Comment by adesst** [comment]
i got the same problem, and i did change this
implementation "com.google.firebase:firebase-core:16.0.1"
implementation "com.google.android.gms:play-services-base:15.0.1"

to
implementation "com.google.firebase:firebase-core:15.0.2"
implementation "com.google.android.gms:play-services-base:15.0.2"

and to add '/topics/...' before the topic name
firebase.messaging().subscribeToTopic('DEMO_ANDROID');
to
firebase.messaging().subscribeToTopic('/topics/DEMO_ANDROID');}

tq
