### ISSUE TITLE
Firestore: Caller does not have permission to execute on iOS but not Android with same codebase

### ISSUE THREAD

**Issue by ntomallen** [invertase/react-native-firebase#839]
I'm having a nifty bug where I get this error: `"Firestore: The caller does not have permission to execute the specified operation. (firestore/permission-denied)."` in iOS only, but not in Android using identical versions of the codebase. In fact, I have both iOS and Android emulators going to the same node server and I'm going back and forth between them and setting breakpoints to see where it's happening. I don't have any native code that would make the difference other than the config stuff required to set up the packges I have installed for the project. Here's a snippet of the query:

```js
let query = momentsRef.where('uid', '==', uid)
query.get().then((snapshot) => { /*etc*/ }).catch((e) => /*fails here on iOS with the error above*/)
```
The security rules in Firestore for momentsRef (which points to 'user_activity') are:
```
    match /user_activity/{activityId} {
    	allow write: if request.auth.uid != null;
	allow read: if request.auth.uid != null;
    }
```
This code is called after the user has successfully logged in with the same method on both iOS and Android. I have also double checked that `uid` is defined on iOS when the `where` query is generated. 
### Environment
Only on iOS, not on Android. Tested using an iPhone 6 emulator on iOS 11.2 and a Nexus 5X emulator on Nougat.

1. Application Target Platform: ?

2. Development Operating System: This was built and tested on macOS 10.13.2 using node v9.3.0

3. Build Tools: Android build tools 

4. React Native version: `"react-native": "0.51.0"`

5. RNFirebase Version: `"react-native-firebase": "3.2.2"`
The gradle configuration. Note that we add `com.google.android.gms` elsewhere and exclude it here so that the same version is used across the app.
```
    implementation(project(':react-native-firebase')) {
        transitive = false
        exclude group: "com.google.android.gms"
    }
    compile "com.google.firebase:firebase-core:11.8.0"
    compile "com.google.firebase:firebase-auth:11.8.0"
    compile "com.google.firebase:firebase-analytics:11.8.0"
    compile "com.google.firebase:firebase-firestore:11.8.0"
```

The pod configuration for iOS:
```
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/iOS'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth' , '~> 4.8.1'
  pod 'Firebase/Firestore'
```
6. Firebase Module: Firestore

**Comment by chrisbianca** [comment]
What’s the reasoning for fixing the version of Auth to 4.8.1?

This version was actually dropped from release by Firebase due to issues - I’d suggest removing the version restriction, updating your pods and seeing whether this is the cause of the problem.

**Comment by ntomallen** [comment]
Nice! One of our developers had added that to try to fix a different bug, but it seems that it was not needed. I removed that line, ran `pod install`, and then deleted the app from the emulator. I also deleted and cleaned the npm cache. Then after running `react-native run-ios` again, it seems to be working perfectly. Thanks!

**Comment by chrisbianca** [comment]
Awesome, glad it's resolved!

**Comment by aliamjad2** [comment]
I am facing the same issue my podfile looks like this. Can anyone suggest a solution please?
```
# Resolve react_native_pods.rb with node to allow for hoisting
$RNFirebaseAsStaticFramework = true
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.0'
prepare_react_native_project!


flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']


target 'Haatif' do
  use_frameworks!
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  # pod 'Google-Maps-iOS-Utils'
  
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'leveldb-library', :modular_headers => true
  
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'HaatifTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

```

**Comment by aliamjad2** [comment]
> I am facing the same issue my podfile looks like this. Can anyone suggest a solution please?
> 
> ```
> # Resolve react_native_pods.rb with node to allow for hoisting
> $RNFirebaseAsStaticFramework = true
> require Pod::Executable.execute_command('node', ['-p',
>   'require.resolve(
>     "react-native/scripts/react_native_pods.rb",
>     {paths: [process.argv[1]]},
>   )', __dir__]).strip
> 
> platform :ios, '13.0'
> prepare_react_native_project!
> 
> 
> flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
> 
> linkage = ENV['USE_FRAMEWORKS']
> 
> 
> target 'Haatif' do
>   use_frameworks!
>   rn_maps_path = '../node_modules/react-native-maps'
>   pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'
>   pod 'react-native-google-maps', :path => rn_maps_path
>   pod 'GoogleMaps'
>   # pod 'Google-Maps-iOS-Utils'
>   
>   pod 'Firebase', :modular_headers => true
>   pod 'FirebaseCore', :modular_headers => true
>   pod 'GoogleUtilities', :modular_headers => true
>   pod 'FirebaseAppCheckInterop', :modular_headers => true
>   pod 'leveldb-library', :modular_headers => true
>   
>   config = use_native_modules!
> 
>   # Flags change depending on the env values.
>   flags = get_default_flags()
>   use_frameworks! :linkage => :static
>   $RNFirebaseAsStaticFramework = true
> 
>   use_react_native!(
>     :path => config[:reactNativePath],
>     # Hermes is now enabled by default. Disable by setting this flag to false.
>     :hermes_enabled => flags[:hermes_enabled],
>     :fabric_enabled => flags[:fabric_enabled],
>     # Enables Flipper.
>     #
>     # Note that if you have use_frameworks! enabled, Flipper will not work and
>     # you should disable the next line.
>     # :flipper_configuration => flipper_config,
>     # An absolute path to your application root.
>     :app_path => "#{Pod::Config.instance.installation_root}/.."
>   )
> 
>   target 'HaatifTests' do
>     inherit! :complete
>     # Pods for testing
>   end
> 
>   post_install do |installer|
>     # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
>     react_native_post_install(
>       installer,
>       config[:reactNativePath],
>       :mac_catalyst_enabled => false
>     )
>     __apply_Xcode_12_5_M1_post_install_workaround(installer)
>   end
> end
> ```

My issue was I did not enable permission to read from firebase console. It is resolved now.
