### ISSUE TITLE
[ANDROID] Crash on launch

### ISSUE THREAD

**Issue by misuna1997** [invertase/react-native-firebase#843]
Application Target Platform: Android
Development Operating System: macOS High Sierra
Build Tools: Android Studio, SDK v.23
React Native version: 0.50.3
react-native-firebase version: 3.2.5

After installing react-native-firebase my application immediately crashing on launching
Here I provide my debug log.

Crash only on real devices. On Emulator everything works properly.

`02-21 12:43:50.879 28908 28908 E AndroidRuntime: FATAL EXCEPTION: main
02-21 12:43:50.879 28908 28908 E AndroidRuntime: Process: com.vodafonekids, PID: 28908
02-21 12:43:50.879 28908 28908 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzh(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String; in class Lcom/google/android/gms/common/internal/zzab; or its super classes (declar
ation of 'com.google.android.gms.common.internal.zzab' appears in /data/app/com.vodafonekids-1/base.apk)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at com.google.android.gms.cast.internal.zzm.<init>(Unknown Source)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at com.google.android.gms.cast.internal.zzm.<init>(Unknown Source)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at com.google.android.gms.cast.framework.CastContext.<clinit>(Unknown Source)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at guichaguri.trackplayer.cast.GoogleCast.initialize(GoogleCast.java:25)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at guichaguri.trackplayer.logic.MediaManager.<init>(MediaManager.java:45)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at guichaguri.trackplayer.logic.services.PlayerService.onCreate(PlayerService.java:66)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3232)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at android.app.ActivityThread.-wrap5(ActivityThread.java)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1606)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:163)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6205)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
02-21 12:43:50.879 28908 28908 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
02-21 12:43:50.886  1582  4076 W ActivityManager:   Force finishing activity com.vodafonekids/.MainActivity
02-21 12:43:50.888  4242  4434 I WtProcessController: Receive am_crash event for pid: 28908 pkg = com.vodafonekids`

**Comment by chrisbianca** [comment]
See https://rnfirebase.io/docs/v3.2.x/troubleshooting/android#NoSuchMethodError:-No-static-method-(run-time-error)
