### ISSUE TITLE
remote config no fetch data

### ISSUE THREAD

**Issue by wellyshen** [invertase/react-native-firebase#844]
Thank you for this great library. I use this library with FireStore it works great. But when I use it with RemoteConfig I can't fetch my parameter which setup on my Firebase. I am pretty sure I have setup the RemoteConfig SDK and my config parameter on my Firebase. Does anyone encounter this problem?

Here's my parameter on my Firebase:
<img width="1018" alt="2018-02-21 8 15 41" src="https://user-images.githubusercontent.com/21308003/36479696-8da8edaa-1744-11e8-8d43-2bc6eb58e015.png">

Here's my code:
```javascript
if (__DEV__) {
  firebase.config().enableDeveloperMode();
}

// Set default values
firebase.config().setDefaults({
  test_key: 'No value!'
});

firebase
  .config()
  .fetch()
  .then(() => firebase.config().activateFetched())
  .then(activated => {
    if (!activated) console.log('Fetched data not activated');
    return firebase.config().getValue('test_key');
  })
  .then(snapshot => {
    console.log('LOG ==> ', snapshot.val()); // <== It always return my default value "No value!"
  })
  .catch(console.error);
```

* Application Target Platform: iOS
* Development Operating System: macOS High Sierra
* Build Tools: xCode 9.2
* React Native version: 0.53.3
* RNFirebase Version: 3.2.5
* Firebase Module: remote config

**Comment by Ehesp** [comment]
Try doing the following:

```js
firebase
  .config()
  .fetch(0)
```

Remote config is cached for 12 hours by default, and `enableDeveloperMode` doesn't bypass cache, it just allows for more frequent refreshes of it.

**Comment by wellyshen** [comment]
@Ehesp Thank you it works 👍
