### ISSUE TITLE
problem with null values on logEvent only on Android

### ISSUE THREAD

**Issue by sibelius** [invertase/react-native-firebase#846]
When I pass a null value, it breaks analytics on Android, but it works fine on iOS.

How can we improve this?

![image](https://user-images.githubusercontent.com/2005841/36591846-0f804afc-1872-11e8-8573-0af88482fb0b.png)

**Comment by Ehesp** [comment]
I guess you shouldn't be able to pass a null value in, since it should be an event name. Needs to be handled more gracefully though.
