### ISSUE TITLE
Multi-App Setup seems to fall back to the default app regardless of app entry point.

### ISSUE THREAD

**Issue by Ayiga** [invertase/react-native-firebase#848]
### Environment

1. Application Target Platform: Both

2. Development Operating System: macOS High Sierra 10.13.3 (17D47)

3. Build Tools: N/A

4. React Native version: 0.53.3

5. RNFirebase Version: 3.2.5

6. Firebase Module: auth (likely affects all modules)

Greetings,

  I'm attempting to use multiple Apps using the [initializeApp](https://github.com/invertase/react-native-firebase/blob/c57c6a7/lib/utils/apps.js#L91) method as outlined in the documentation on [rnfirebase.io](https://rnfirebase.io/docs/v3.2.x/core/initialize-apps), but I'm getting stuck on Authentication.  It seems as though, regardless of which `App` I am using it still falls back to the `[DEFAULT]` app.

![screen shot 2018-02-23 at 4 26 08 pm](https://user-images.githubusercontent.com/3937524/36621644-4e5eb684-18b6-11e8-8a6e-db80c5840120.png)

<img width="976" alt="screen shot 2018-02-23 at 4 20 52 pm" src="https://user-images.githubusercontent.com/3937524/36621653-568c1dce-18b6-11e8-969f-5b9cd24bac76.png">

<img width="979" alt="screen shot 2018-02-23 at 4 24 45 pm" src="https://user-images.githubusercontent.com/3937524/36621658-5b4ecd98-18b6-11e8-990e-8cc1a84d46b1.png">

I've looked through the source to try and pin-point why this is occurring, and [I believe the issue is caused by attempting to index the `APP_MODULES` by the `App` object itself](https://github.com/invertase/react-native-firebase/blob/c57c6a7/lib/utils/apps.js#L21).  Since Javascript object's are only able to have `string` or `Symbol`s as their keys, this forces the `App` to be converted to a string.  With no implementation of the `toString` method this falls back to the default `Object` `toString` method, of `'[object Object]'`.  Because of this, all created App Modules will be referencing the same app.

<img width="980" alt="screen shot 2018-02-23 at 4 22 09 pm" src="https://user-images.githubusercontent.com/3937524/36621678-78700086-18b6-11e8-8266-7c246a0e0549.png">

The easiest way to detect this is to create a project with `react-native-firebase`, have a native app setup, and sign in to it.  Now create a new app using `initializeApp`, and then call the `onAuthStateChanged`.  You should get a result that returns the user for the `'[DEFAULT_APP]'` instead of `null` or a user for the second app.

It seems that the simplest solution to this issue is to add a `toString` method to the [`App`](https://github.com/invertase/react-native-firebase/blob/c57c6a7/lib/modules/core/app.js) class so that it returns the app's name.
```javascript
  /**
   * toString returns the name of the app.
   *
   * @return {string}
   */
  toString() {
    return this._name;
  }
```

This is what I've done currently to fix the issue.  Another possible solution would be to [switch out the Javascript Object Literal](https://github.com/invertase/react-native-firebase/blob/c57c6a7/lib/utils/apps.js#L21) for a `Map`.  Although that may cause issues with the javascript Environment, and could require the runtime to have a polyfill.  I'm not sure if it has this polyfill by default.
```javascript
const APP_MODULES: Map<App, FirebaseModule> = new Map();
```

The last option that would work would be to [modify the Javascript Object Literal](https://github.com/invertase/react-native-firebase/blob/c57c6a7/lib/utils/apps.js#L21) so that it uses a string as a key, and modify the modules so that they use the app's name.
[Lines to Modify 1](https://github.com/invertase/react-native-firebase/blob/c57c6a7/lib/utils/apps.js#L52-L53)

[Lines to Modify 1](https://github.com/invertase/react-native-firebase/blob/c57c6a7/lib/utils/apps.js#L52-L53)

[Lines to Modify 2](https://github.com/invertase/react-native-firebase/blob/c57c6a7/lib/utils/apps.js#L65-L69)

```javascript
  /**
   *
   * @param statics
   * @param InstanceClass
   * @return {function()}
   * @private
   */
  appModule<M: FirebaseModule>(
    app: App,
    namespace: FirebaseNamespace,
    InstanceClass: Class<M>
  ): () => FirebaseModule {
    return (): M => {
      if (!APP_MODULES[app.name]) {
        APP_MODULES[app.name] = {};
      }

      if (
        isAndroid &&
        namespace !== 'utils' &&
        !INTERNALS.FLAGS.checkedPlayServices
      ) {
        INTERNALS.FLAGS.checkedPlayServices = true;
        app.utils().checkPlayServicesAvailability();
      }

      if (!APP_MODULES[app.name][namespace]) {
        APP_MODULES[app.name][namespace] = new InstanceClass(app, app.options);
      }

      return APP_MODULES[app.name][namespace];
    };
  },
```

There may be more ways to address this issue as well, but these seem like fairly simple changes.

As I said, I used the first method, but it's all personal preference.  I can open a Pull Request with the method that best suits your style.

Please let me know,

Thanks,

~ Ayiga

**Comment by Salakar** [comment]
Thanks for this well written issue report 💯  

Have just pushed a fix for this, went with the toString() approach - thanks for all the suggested fixes.
