### ISSUE TITLE
Adding dynamic links integration to AppDelegate.m when \ application:(UIApplication *)application \ already exists for fbsdk?

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#849]
This is likely ios related question, but its regarding RNFirebase docs (step `iv`) in dynamics links integration: https://rnfirebase.io/docs/v3.2.x/links/ios

When configuring Facebook SDK, they asked to add following line to `AppDelegate.m`
```
- (BOOL)application:(UIApplication *)application
  openURL:(NSURL *)url
  options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    BOOL handled = [[FBSDKApplicationDelegate sharedInstance] application:application
      openURL:url
      sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
      annotation:options[UIApplicationOpenURLOptionsAnnotationKey]
  ];
  return handled;
}
```

RNFirebase asks to add this one
```
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<NSString *, id> *)options {
    return [RNFirebaseLinks application:application
                                openURL:url
                                options:options];
}
```

Both of these clash, I tried to resolve them so I can use both, but failed, due to lack of Objective C knowledge, hence am asking here. Additionally, I could submit a pr to the docs explaining what to do if users are in a similar situation.

**Comment by chrisbianca** [comment]
Essentially you need to chain the checks, then if that doesn't `handle` the link, check the other, so something like:
```
- (BOOL)application:(UIApplication *)application
  openURL:(NSURL *)url
  options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    BOOL handled = [[FBSDKApplicationDelegate sharedInstance] application:application
      openURL:url
      sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
      annotation:options[UIApplicationOpenURLOptionsAnnotationKey]
  ];
  if (!handled) {
    handled = [RNFirebaseLinks application:application openURL:url options:options];
  } 
  return handled;
}
```
If you're able to confirm that's working, and submit a PR to the docs that would be fantastic!

**Comment by IljaDaderko** [comment]
@chrisbianca Awesome, I'll jump on this right away! Need to fix provisioning profiles after adding associated domain, might take a while, but if it works, will add that PR 👍

**Comment by IljaDaderko** [comment]
@chrisbianca yep all cool, thank you. I'm having trouble locating repo for docs / website to put this in, could you please point me to it, I will draft up a pr mentioning this caveat.

**Comment by chrisbianca** [comment]
https://github.com/invertase/react-native-firebase-docs

You'll want to submit the PR to the 3.2.x branch. Thanks again!

**Comment by JayricMok** [comment]
@chrisbianca just facing the issue, and your code save me, Thanks !
