### ISSUE TITLE
firebase.auth.EmailAuthProvider is undefined

### ISSUE THREAD

**Issue by adamonkey** [invertase/react-native-firebase#850]
### Issue

When I try to link the user's anonymous account to an email or Facebook account by calling:

var credential = firebase.auth.EmailAuthProvider.credential(email, password) 
or 
var credential = firebase.auth.FacebookAuthProvider.credential(token)

It crashes my app by throwing the following error:
undefined is not an object (evaluating '_firebase2.default.auth.EmailAuthProvider.credential')

I tried both auth and auth() - no difference. firebase.auth is defined. firebase.auth.EmailAuthProvider is undefined. It doesn't get to .credential. 

This is happening in iOS and Android, in simulator and in production.
Other Firebase utilities (sign-in, database) work for me - it's just sign-up. It worked fine before, but after I upgraded RN, Firebase, and RNFirebase simultaneously recently, it no longer worked. 

### Environment

1. Application Target Platform: Both
2. Development Operating System: macOS
3. Build Tools: Xcode and Android Studio. 
4. React Native version: 0.53.0
5. RNFirebase Version: 3.2.5
6. Firebase Module: Authentication

Thanks!!!

**Comment by chrisbianca** [comment]
@adamonkey How is your firebase defined?

Is it simply: 

`import firebase from 'react-native-firebase';`

or is it a particular initialised app instance?

`EmailAuthProvider` and `FacebookAuthProvider` are only available on the former, and this did change fairly recently to bring it inline with the official Firebase web SDK.

**Comment by adamonkey** [comment]
I initialized an app instance, so that sounds like the problem. Will try it, thanks!

**Comment by chrisbianca** [comment]
Great, I'll close this, but please re-open if you find that isn't the issue

**Comment by khanka0511** [comment]
i am new to programing and where do i place the imports ?
