### ISSUE TITLE
Firebase Remote Config doesn't install natively in iOS project

### ISSUE THREAD

**Issue by tadalavigne** [invertase/react-native-firebase#851]
1. Application Target Platform: iOS
2. Development Operating System: macOS High Sierra
3. Build Tools: XCode  9.3 beta 
4. React Native version: react-native-cli: 2.0.1 , react-native: 0.52.2
5. RNFirebase Version: 3.2.4
6. Firebase Module: Remote Config

The error occurred by the following detail below.

> Error: You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.config().

> Ensure you have the required Firebase iOS SDK pod for this module included in your Podfile, in this instance confirm you've added "pod 'Firebase/RemoteConfig'" to your Podfile

In my podfile already add 

> pod 'Firebase/RemoteConfig'

**Comment by Ehesp** [comment]
Can we see your Podfile.lock?

**Comment by tadalavigne** [comment]
> PODS:
>   - Firebase/Core (4.9.0):
>     - FirebaseAnalytics (= 4.0.9)
>     - FirebaseCore (= 4.0.15)
>   - Firebase/RemoteConfig (4.9.0):
>     - Firebase/Core
>     - FirebaseRemoteConfig (= 2.1.2)
>   - Firebase/Storage (4.9.0):
>     - Firebase/Core
>     - FirebaseStorage (= 2.1.2)
>   - FirebaseABTesting (1.0.0):
>     - FirebaseCore (~> 4.0)
>     - Protobuf (~> 3.1)
>   - FirebaseAnalytics (4.0.9):
>     - FirebaseCore (~> 4.0)
>     - FirebaseInstanceID (~> 2.0)
>     - GoogleToolboxForMac/NSData+zlib (~> 2.1)
>     - nanopb (~> 0.3)
>   - FirebaseCore (4.0.15):
>     - GoogleToolboxForMac/NSData+zlib (~> 2.1)
>   - FirebaseInstanceID (2.0.9):
>     - FirebaseCore (~> 4.0)
>   - FirebaseRemoteConfig (2.1.2):
>     - FirebaseABTesting (~> 1.0)
>     - FirebaseAnalytics (~> 4.0)
>     - FirebaseCore (~> 4.0)
>     - FirebaseInstanceID (~> 2.0)
>     - GoogleToolboxForMac/NSData+zlib (~> 2.1)
>     - Protobuf (~> 3.1)
>   - FirebaseStorage (2.1.2):
>     - FirebaseAnalytics (~> 4.0)
>     - FirebaseCore (~> 4.0)
>     - GTMSessionFetcher/Core (~> 1.1)
>   - GoogleToolboxForMac/Defines (2.1.3)
>   - GoogleToolboxForMac/NSData+zlib (2.1.3):
>     - GoogleToolboxForMac/Defines (= 2.1.3)
>   - GTMSessionFetcher/Core (1.1.14)
>   - nanopb (0.3.8):
>     - nanopb/decode (= 0.3.8)
>     - nanopb/encode (= 0.3.8)
>   - nanopb/decode (0.3.8)
>   - nanopb/encode (0.3.8)
>   - Protobuf (3.5.0)
>   - React (0.52.2):
>     - React/Core (= 0.52.2)
>   - React/BatchedBridge (0.52.2):
>     - React/Core
>     - React/cxxreact_legacy
>   - React/Core (0.52.2):
>     - yoga (= 0.52.2.React)
>   - React/cxxreact_legacy (0.52.2):
>     - React/jschelpers_legacy
>     - React/jsinspector_legacy
>   - React/fishhook (0.52.2)
>   - React/jschelpers_legacy (0.52.2)
>   - React/jsinspector_legacy (0.52.2)
>   - React/RCTActionSheet (0.52.2):
>     - React/Core
>   - React/RCTAnimation (0.52.2):
>     - React/Core
>   - React/RCTBlob (0.52.2):
>     - React/Core
>   - React/RCTGeolocation (0.52.2):
>     - React/Core
>   - React/RCTImage (0.52.2):
>     - React/Core
>     - React/RCTNetwork
>   - React/RCTLinkingIOS (0.52.2):
>     - React/Core
>   - React/RCTNetwork (0.52.2):
>     - React/Core
>   - React/RCTSettings (0.52.2):
>     - React/Core
>   - React/RCTText (0.52.2):
>     - React/Core
>   - React/RCTVibration (0.52.2):
>     - React/Core
>   - React/RCTWebSocket (0.52.2):
>     - React/Core
>     - React/fishhook
>     - React/RCTBlob
>   - ReactNativePermissions (1.1.1):
>     - React
>   - yoga (0.52.2.React)
> 
> DEPENDENCIES:
>   - Firebase/Core
>   - Firebase/RemoteConfig
>   - Firebase/Storage
>   - React/BatchedBridge (from `../node_modules/react-native`)
>   - React/Core (from `../node_modules/react-native`)
>   - React/RCTActionSheet (from `../node_modules/react-native`)
>   - React/RCTAnimation (from `../node_modules/react-native`)
>   - React/RCTGeolocation (from `../node_modules/react-native`)
>   - React/RCTImage (from `../node_modules/react-native`)
>   - React/RCTLinkingIOS (from `../node_modules/react-native`)
>   - React/RCTNetwork (from `../node_modules/react-native`)
>   - React/RCTSettings (from `../node_modules/react-native`)
>   - React/RCTText (from `../node_modules/react-native`)
>   - React/RCTVibration (from `../node_modules/react-native`)
>   - React/RCTWebSocket (from `../node_modules/react-native`)
>   - ReactNativePermissions (from `../node_modules/react-native-permissions`)
>   - yoga (from `../node_modules/react-native/ReactCommon/yoga`)
> 
> EXTERNAL SOURCES:
>   React:
>     :path: ../node_modules/react-native
>   ReactNativePermissions:
>     :path: ../node_modules/react-native-permissions
>   yoga:
>     :path: ../node_modules/react-native/ReactCommon/yoga
> 
> SPEC CHECKSUMS:
>   Firebase: 632216af3ed7f31e3be34776947fdc7546cfb572
>   FirebaseABTesting: d07d0ee833b842d5153549e4c7e2e2cb1c23a3f9
>   FirebaseAnalytics: 388b630c15713f5dbf364071f5f3d6077fb52f4e
>   FirebaseCore: 3bd047463058fa6b5d312c97502c52e45401cdfb
>   FirebaseInstanceID: d2058a35e9bebda1b6dd42486b84917bde552a9d
>   FirebaseRemoteConfig: df64ce784a45e9b9d4988030a59da6baede8bdb0
>   FirebaseStorage: 181bb543d39ee3c53e0558de7ba86b1286a0427f
>   GoogleToolboxForMac: 2501e2ad72a52eb3dfe7bd9aee7dad11b858bd20
>   GTMSessionFetcher: 390ea358e5a0d0133153806f744662dad933d06b
>   nanopb: 5601e6bca2dbf1ed831b519092ec110f66982ca3
>   Protobuf: 8a9838fba8dae3389230e1b7f8c104aa32389c03
>   React: 001655c2b9dfc2f55e8271c60098d4f4227fb1b3
>   ReactNativePermissions: 2e324bb3baf12702e3ec27f76c8ae1158fa69fc6
>   yoga: 18f5bf8fba4b4a31ca4b42ac931fce5537e1923c
> 
> PODFILE CHECKSUM: c2ef9efcb8aab2fd66dd2e05048df248b88195d1
> 
> COCOAPODS: 1.3.1

**Comment by Ehesp** [comment]
@tadalavigne Strange - before anything else, make sure you delete the `Podfile.lock` and the `Pods` directory. Make sure cocoapods is up-to-date and run `pod outdated` to check for any outdated pods. 

Run `pod install` again and rebuild your app.

**Comment by chrisbianca** [comment]
Closing this due to lack of response. Please re-open if you're still having issues.

**Comment by ericlathrop** [comment]
I was having this same error, and I fixed it by removing the `node_modules` folder and re-installing them.

**Comment by tarun29061990** [comment]
I fixed this by doing clean and then building the project. But now firebase.config().getValue("....") returning me 0

**Comment by SteFF1997** [comment]
> I fixed this by doing clean and then building the project. But now firebase.config().getValue("....") returning me 0
 
this helps me with your problem

```
firebase
    .config()
    .fetch()
    .then(() => firebase.config().activateFetched())
    .then(() => firebase.config().getValue('your_key_in_firebase_console'))
    .then((data) => {
      console.warn('data', data.val());
    })
    .catch(error => console.log(Error processing config: ${error}));
```

**Comment by SteFF1997** [comment]
@tarun29061990  read https://rnfirebase.io/docs/v5.x.x/config/reference/config
you must fetch with native module after update config at the firebase console
