### ISSUE TITLE
Native Ads Advanced to replace Express?

### ISSUE THREAD

**Issue by csumrell** [invertase/react-native-firebase#853]
I see in the documentation that v3 allows for Native Express, but that has since been discontinued. Does the plugin support Native Ads Advanced instead now? I could not find anything in the documentation about it?

**Comment by Ehesp** [comment]
Right now it's not supported - we've got a canny board with the request, feel free to upvote!

https://react-native-firebase.canny.io/feature-requests/p/new-native-ad-format

**Comment by haotangio** [comment]
Looks like implementation for this one is time consuming. Did someone figure out any workaround to show `Native Ads Advances`?

**Comment by perrosnk** [comment]
Any updates on this?

**Comment by flyinghawker** [comment]
looking for update...
