### ISSUE TITLE
Installation docs are possibly incoherent with state of the art

### ISSUE THREAD

**Issue by christianversloot** [invertase/react-native-firebase#854]
### Issue

I followed the installation process as described in your docs: https://rnfirebase.io/docs/v3.2.x/installation/android

The `:app:transformClassesWithDexForDebug` part of the process then throws the following error:

```
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzbfq;
    UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzbfq;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
```

A quick Google leads to the observation that as this means that there are multiple copies of different versions of the Google Play services in the project. I believe that this is caused by a discrepancy between the docs and the current state of the art, because the docs state to add:

```
 compile "com.google.android.gms:play-services-base:11.6.0"
 compile "com.google.firebase:firebase-core:11.6.0"
```

While the current master HEAD of your build.gradle file (https://github.com/invertase/react-native-firebase/blob/master/android/build.gradle) signals that your latest version uses a different version: 

`ext.firebaseVersion = '11.8.0'`

As a consequence, I experienced the dex error after freshly installing `react-native-firebase`. Handling this by replacing 11.6.0 with 11.+ (required by some other libraries I use) resolved the error. I think replacing 11.6.0 with 11.8.0 also works.

Please let me know whether I'm thinking in the proper direction and if relevant, please update the docs.

### Environment

Android

1. Application Target Platform:

Android, but not relevant

2. Development Operating System:

Not relevant

3. Build Tools:

Not relevant

4. React Native version:

Not relevant

5. RNFirebase Version:

latest

6. Firebase Module:

Core + modules

**Comment by Ehesp** [comment]
Yeah the docs are static so can be out-dated on new releases. The following is where it's defined in the docs:

https://github.com/invertase/react-native-firebase-docs/blob/v3.3.x/docs/_config.yaml

**Comment by baona95** [comment]
@Ehesp Do we really need to add particular dependencies like 
`compile "com.google.firebase:firebase-ads:11.8.0"` into our project build.gradle despite it is already in https://github.com/invertase/react-native-firebase/blob/master/android/build.gradle ?

**Comment by chrisbianca** [comment]
@baona95 Yes you do, as otherwise every app would include every firebase dependency regardless of whether they needed it or not.

**Comment by chrisbianca** [comment]
I've just updated the docs to 11.8.0
