### ISSUE TITLE
Phone Auth Auto Verification does not work on RELEASE version!

### ISSUE THREAD

**Issue by mdmush** [invertase/react-native-firebase#855]
### Issue

I am using phone authentication with auto verification. The app works fine when it is running in debugging mode but when i create a release app of it, it stopped verifying. Please let me know what to do.

### Code for handling Verification

    firebase.auth()
    .verifyPhoneNumber(this.state.number)
    .on('state_changed', (phoneAuthSnapshot) => {

      switch (phoneAuthSnapshot.state) {

        case firebase.auth.PhoneAuthState.CODE_SENT: // or 'sent'
          console.log('code sent');
          break;

        case firebase.auth.PhoneAuthState.ERROR: // or 'error'
          console.log('verification error');
          console.log(phoneAuthSnapshot.error);
          break;

        case firebase.auth.PhoneAuthState.AUTO_VERIFY_TIMEOUT: // or 'timeout'
          console.log('auto verify on android timed out');
          break;

        case firebase.auth.PhoneAuthState.AUTO_VERIFIED: // or 'verified'
          console.log('auto verified on android');
          console.log(phoneAuthSnapshot);
          AsyncStorage.setItem('loggedin', 'true');
          this.getCurrentUser(); // Checking if the user is logged-in and it have the user as current user.
          break;
      }
    }, (error) => {
      console.log(error);
      console.log(error.verificationId);
    }, (phoneAuthSnapshot) => {
      console.log(phoneAuthSnapshot);
    });

    async getCurrentUser(){
      var userId;
      try {
        firebase.auth().onAuthStateChanged(function(user){
          userId = user.uid;
       });

       AsyncStorage.setItem('uid', userId);

       Database.checkFirstLogin(userId, (firstLogin) => {
          this.setState({
            firstLogin: firstLogin
        });
          if (this.state.firstLogin == null) {
              Actions.userDetails({uid: userId});
          }  else {
              Actions.dashboard({uid: userId});
            }
        });
      } catch (error) {
        console.log(error);
      }
    }

### Environment

1. Application Target Platform: Windows 10

2. Development Operating System: Android

3. React Native version: 0.52.0

4. RNFirebase Version: 3.2.5

5. Firebase Module: Auth

**Comment by Ehesp** [comment]
Maybe some errors would help us? We can't help with a block of code sorry.

**Comment by chrisbianca** [comment]
Closing due to lack of response. Please re-open with some error messages if this is still a problem.

**Comment by adirzoari** [comment]
@mdmush  I have same issue,  phone auth AUTO verification not works.  phoneAuthSnapshot includes code null. how did you solve it?

**Comment by mdmush** [comment]
@adirzoari 

try adding correct release **SHA-1 certificate fingerprints** in your firebase project settings. 

And if you have created your app project in Google Play store as well, Go to _Release Management -> App signing_. Then add the given SHA-1 certificate fingerprints in your firebase project too.

**Comment by adirzoari** [comment]
I added. the phone auth works fine. but I read in firebase docs in android should be firebase AUTO codeInput

**Comment by mdmush** [comment]
@adirzoari 

try adding correct release **SHA-1 certificate fingerprints** in your firebase project settings. 

And if you have created your app project in Google Play store as well, Go to _Release Management -> App signing_. Then add the given SHA-1 certificate fingerprints in your firebase project too.

**Comment by mdmush** [comment]
Oh! Okay.

Then you can use this code to make it as Auto fetching code input from OTP messages.


      firebase.auth()
      .verifyPhoneNumber(this.state.number)
      .on('state_changed', (phoneAuthSnapshot) => {

    switch (phoneAuthSnapshot.state) {

    case firebase.auth.PhoneAuthState.CODE_SENT: // or 'sent'
      console.log('code sent');
      break;

    case firebase.auth.PhoneAuthState.ERROR: // or 'error'
      console.log('verification error');
      console.log(phoneAuthSnapshot.error);
      break;

    case firebase.auth.PhoneAuthState.AUTO_VERIFY_TIMEOUT: // or 'timeout'
      console.log('auto verify on android timed out');
      break;

    case firebase.auth.PhoneAuthState.AUTO_VERIFIED: // or 'verified'
      console.log('auto verified on android');
      console.log(phoneAuthSnapshot);
      AsyncStorage.setItem('loggedin', 'true');
      this.getCurrentUser(); // Checking if the user is logged-in and it have the user as current user.
      break;
     }
     }, (error) => {
     console.log(error);
    console.log(error.verificationId);
    }, (phoneAuthSnapshot) => {
     console.log(phoneAuthSnapshot);
     });

**Comment by adirzoari** [comment]
Yes I did it you can see.
`        confirmPhone = async (phoneNumber) => {
            console.log('phoneNumber',phoneNumber)
            return new Promise((res, rej) => {
                firebase.auth().verifyPhoneNumber(phoneNumber)
                    .on('state_changed', async (phoneAuthSnapshot) => {
                        switch (phoneAuthSnapshot.state) {
                            case firebase.auth.PhoneAuthState.AUTO_VERIFIED:
                                this.confirmCode(phoneAuthSnapshot.verificationId, phoneAuthSnapshot.code)
                                break

                            case firebase.auth.PhoneAuthState.CODE_SENT:
                                console.log('codeSend',phoneAuthSnapshot)
                                // await userSettings.set(AUTH_KEYS.VERIFICATION_ID, phoneAuthSnapshot.verificationId)
                                UserStore.setVerificationId(phoneAuthSnapshot.verificationId)
                                res(phoneAuthSnapshot)
                                break

                            case firebase.auth.PhoneAuthState.AUTO_VERIFY_TIMEOUT: // or 'timeout'
                                UserStore.setVerificationId(phoneAuthSnapshot.verificationId)
                                res(phoneAuthSnapshot)
                           

                            case firebase.auth.PhoneAuthState.ERROR:
                                rej(phoneAuthSnapshot)
                                break;
                                
                        }
                    })
            })
        }

        confirmCode = async (verificationId, code) => {
            console.log('verificationCONFIRM',code) // it show me code is null
            UserStore.setCodeInput(codecode);
            const credential = await firebase.auth.PhoneAuthProvider.credential(UserStore.verificationId, code)
            UserStore.setUserCredentials(credential.token)
            this.authenticate(credential)
            return credential
        }

        authenticate = (credential)=> {
            console.log('new',credential)
            firebase.auth().signInAndRetrieveDataWithCredential(credential)
        }
`

**Comment by adirzoari** [comment]
this state_changed:

> case firebase.auth.PhoneAuthState.AUTO_VERIFIED:

is called but it not save me automatic the user in firebase Authentication Users in firebase console

**Comment by mdmush** [comment]
You don't need to confirm code or authenticate after **AUTO_VERIFIED** state. When it is **AUTO_VERIFIED**, it automatically authenticate the app as the user.

You need to add this code in your componentWillMount() to navigate if the app is authenticated/verified successfully with the user.


```
firebase.auth().onAuthStateChanged(function(user){
      //set the user accrodingly
});
```

**Comment by adirzoari** [comment]
look on it what I get

![print](https://user-images.githubusercontent.com/20258998/39753609-1bd1cc28-52c8-11e8-8a3e-7f38f400e07a.JPG)


`  console.log('phoneAuthSnapshot', phoneAuthSnapshot)

            console.log('code ->',code) // it show me code is null`
```

**Comment by adirzoari** [comment]
> You don't need to confirm code or authenticate after AUTO_VERIFIED state. When it is AUTO_VERIFIED, it automatically authenticate the app as the user.

> 
> You need to add this code in your componentWillMount() to navigate if the app is authenticated/verified successfully with the user.
> 
> firebase.auth().onAuthStateChanged(function(user){
>       //set the user accrodingly
> });
> 


I agree with you, but to be authneticate user, it mean to write him in FIREBASE authnetication users table. and it not write him.

**Comment by adirzoari** [comment]
Do you have any full code I can look on it please?

**Comment by mdmush** [comment]
> `  console.log('phoneAuthSnapshot', phoneAuthSnapshot)
> 
>             console.log('code ->',code) // it show me code is null`

Snapshot Object with null values and Verified state only comes if all the **SHA-1** fingerprints are not in the firebase project settings. Happened with me too but after adding **SHA-1**, everything is working perfectly.

**This is one working code. Check if it helps.**

```
firebase.auth()
    .verifyPhoneNumber(this.state.number)
    .on('state_changed', (phoneAuthSnapshot) => {
      switch (phoneAuthSnapshot.state) {

        case firebase.auth.PhoneAuthState.CODE_SENT: // or 'sent'
          console.log('code sent');
          break;

        case firebase.auth.PhoneAuthState.ERROR: // or 'error'
          ToastAndroid.show(
            'Check your internet connection. There is something wrong with that! :)',
            ToastAndroid.LONG
          );
          break;

        case firebase.auth.PhoneAuthState.AUTO_VERIFY_TIMEOUT: // or 'timeout'
          ToastAndroid.showWithGravity(
            'Check your internet connection. There is something wrong with that! :)',
            ToastAndroid.SHORT,
            ToastAndroid.BOTTOM
          );
          break;

        case firebase.auth.PhoneAuthState.AUTO_VERIFIED: // or 'verified'
          const { verificationId, code } = phoneAuthSnapshot;
          const credential = firebase.auth.PhoneAuthProvider.credential(verificationId, code);
          firebase.auth().signInAndRetrieveDataWithCredential(credential);
          break;
      }
  }, (error) => {
      console.log(error);
  }, (phoneAuthSnapshot) => {
      console.log(phoneAuthSnapshot);
 });
```

**Comment by adirzoari** [comment]
Hey,
I take your code and I found something:

1. in android version under 8.0, the phone auth it not send sms to phone, but it run the AUTH_VERIFIED and  but after that is shows user undefined BUT it add the user to firebase authentication table in firebase console
```
`  firebase.auth().onAuthStateChanged((user) => {
            if (user) {
                console.log('user--->',user)`
```
the photoAuthSnapshot code shows null again.

2. in android version up to 8.0 the phone auth send sms (it not call to AUTH_VERIFIED) to phone and code information works code but again the user is undefined,
 
Do I do something wrong maybe?

**Comment by adirzoari** [comment]
in addition, I generate again SHA1 when I run the project in android studio and get the right SHA1, then I copy to firebase console and download again the googld-service.json and add to the project

**Comment by adirzoari** [comment]
@mdmush I generate apk sign (for testing- without to upload to playstore) in react native app and test my app and I get the error 

> Error: this app is not authorized to use firebase authentication. please verifythat the correct package name and sha-1 are configured in the firebase console.

But when i test on my app by 'react-native run-android' all works good. what to do?

**Comment by thegreate** [comment]
![screenshot_1532523617](https://user-images.githubusercontent.com/6082909/43202314-cddf610c-9038-11e8-9854-392f7dbe6de7.png)
 I am facing this issue . Don't know how this happend.

**Comment by nomi9995** [comment]
i have same issue
Error: this app is not authorized to use firebase authentication. please verifythat the correct package name and sha-1 are configured in the firebase console.

i have already added SHA-1 package name to firebase but could not resolve this error

**Comment by maheshmnj** [comment]
can someone help me  whitelist phone numbers in firebase console it says error while adding a phone number

**Comment by mdmush** [comment]
> can someone help me whitelist phone numbers in firebase console it says error while adding a phone number

Maybe some errors or logs would help us?

**Comment by mdmush** [comment]
> I am facing this issue . Don't know how this happend.

Firebase is not properly integrated into your app. Take a look at it and do Step by Step: 
1. [Initial Setup](https://rnfirebase.io/docs/v4.3.x/installation/initial-setup)
**Must**: 
**Android**: Don't forgot to add **google-services.json** to **android/app/** 
**iOS**: Don't forgot to add **GoogleService-Info.plist** to **ios/[YOUR APP NAME]/**
2. a. [iOS Installation](https://rnfirebase.io/docs/v4.3.x/installation/ios)
    b. [Android Installation](https://rnfirebase.io/docs/v4.3.x/installation/android)
3. [Usage](https://rnfirebase.io/docs/v4.3.x/installation/javascript)

**Comment by mdmush** [comment]
> @mdmush I generate apk sign (for testing- without to upload to playstore) in react native app and test my app and I get the error
> 
> > Error: this app is not authorized to use firebase authentication. please verifythat the correct package name and sha-1 are configured in the firebase console.
> 
> But when i test on my app by 'react-native run-android' all works good. what to do?

Try adding release SHA-1 also.

**Comment by Yingi** [comment]
I have added the the SHA-1 to the firebase console. I have also included SMS permission in my AndroidManifest.xml file. Yet i am unable to recieve sms even if `case firebase.auth.PhoneAuthState.CODE_SENT: // or 'sent'
            console.log('code sent');
            console.log(firebase.auth.PhoneAuthState.CODE_SENT)
            break;
`
gets called.

I dont know why i am unable to recieve sms from firebase. Do i need to upgrade to a premium version on firebase. I am not recieving sms code from firebase. I really dont know what the problem is

@adirzoari I am using Android 5.1, Do you think that is the cause of it.

@mdmush Please help

**Comment by maheshmnj** [comment]
try sending otp on another phone or try after some time

**Comment by 3210jr** [comment]
I've had the same problem for a while, this answer on stackoverflow helped me => https://stackoverflow.com/a/53513327/3765706 

Good Luck!

**Comment by Fardeen15** [comment]
> i have same issue
> Error: this app is not authorized to use firebase authentication. please verifythat the correct package name and sha-1 are configured in the firebase console. 
> i have already added SHA-1 package name to firebase but could not resolve this error


I think you can use emulator
 emulator can not resolve SHA-1 Package Name

**Comment by subhadeepquantiantech** [comment]
same issue
