### ISSUE TITLE
Firebase Dynamic Link doesn't redirect to the app when open through Safari

### ISSUE THREAD

**Issue by Luckygirlllll** [invertase/react-native-firebase#857]
### Issue

I have added Firebase Dynamic Link in my app, when I open in iPhone link through Google Chrome, it redirects me to the app, but when I'm trying to open app through Safari (I'm opening links through the Notes, not directly from the Safari), it doesn't open the app.

I'm testing on real device, not in simulator.

What can be wrong and how is possible to fix that?

### Environment
IOS

1. Application Target Platform:

macOS Sierra

2. Development Operating System:

Latest Xcode

3. Build Tools:

4. React Native version:

 0.47.2

5. RNFirebase Version:

latest RNFirebase Version

6. Firebase Module:

Firebase Dynamic Links

**Comment by Salakar** [comment]
Resolved issue on discord. Incorrect universal link domain in Xcode + invalid url scheme set.

**Comment by FakhruddinAbdi** [comment]
@Salakar how did you resolve it ?

Could you please add the detailed instruction here too

**Comment by Luckygirlllll** [comment]
@FakhruddinAbdi The solution of my problem is here https://stackoverflow.com/questions/49030395/firebase-dynamic-link-doesnt-redirect-to-the-app-when-open-through-safari

**Comment by FakhruddinAbdi** [comment]
@LuckGirlllll i commented your answer on stof but no reply there.
this is my comment `according to firebase official doc, we should set the value in associated domains like this applinks:your_subdomain.page.link Could you please let me know what app_id and app as an example `

**Comment by Luckygirlllll** [comment]
Well, app_id is something like k4pd5, so it should be like this  applinks: k4pd5.app.goo.gl

**Comment by FakhruddinAbdi** [comment]
`[TEMPORARY - PERSONAL DATA]`
This is my App id on firebase console -> project setting -> ios -> App id : `VPH4QRQT5D`
And this is my app name : `harzaan`
And my ios bundle name : `com.bawersystem.harzaan`
And dynamic link domain in firebase console -> dynamic link -> upper right section: `harzaan.page.link`

So what should be my `applinks` eventually? 

Sorry for bothering you, but i really tried many ways and failed, and just want to get it working asap

**Comment by FakhruddinAbdi** [comment]
Ok .. You are using old dynamic link scheme, Im not sure if firebase console still support it
The current scheme is something like this : `app.page.link/random_key`

https://firebase.googleblog.com/2018/06/3-ways-to-customize-your-firebase.html

**Comment by anniewey** [comment]
@Luckygirlllll Did you release the app in AppStore for it to work? 
I'm having the same situation. Weirdly, when I clicked the link from Notes/Whatsapp it did launch the app. But when I clicked in Slack, it will open in Safari and keep prompt message to open in AppStore.

**Comment by Vanclief** [comment]
I am having exactly the same problem, but the scheme has changed as @FakhruddinAbdi said. Anyone has been able to solve this situation with new scheme?
