### ISSUE TITLE
Import firebase from react-native-firebase break other dependencies that uses localStorage

### ISSUE THREAD

**Issue by adoankim** [invertase/react-native-firebase#858]
### Issue

On our project we're using some dependency that uses the global localStorage API. After making an `import firebase from react-native-firebase` we got a stack trace complaining that some property doesn't exist on the localStorage object. 

Note: I found that the global localStorage is replaced by an empty object in [here](https://github.com/invertase/react-native-firebase/blob/24d16e4853151f92590fb24aebbc3b69927ecf96/lib/utils/log.js#L11).

### Environment

1. Application Target Platform: Both

2. Development Operating System: macOS Sierra 10.13.1

3. Build Tools: not relevant

4. React Native version:  0.51.0

5. RNFirebase Version: 3.2.7

6. Firebase Module: RemoteConfig

Thanks for the support!

**Comment by Salakar** [comment]
Thanks for the report @adoankim - we're removing this as part of v3.3.0 this week. Was added a while back in the legacy codebase to support `bows` logger.

**Comment by Salakar** [comment]
Fixed pending [next release](https://github.com/invertase/react-native-firebase/releases) (v3.3.0)
