### ISSUE TITLE
Gradle wrapper 4.4 transitive = false no longer works

### ISSUE THREAD

**Issue by sgong-pdftron** [invertase/react-native-firebase#861]
### Issue
Gradle wrapper 4.4 "transitive = false" no longer works.
All modules that are not referenced in the main application will not compile. Have to manually comment out all modules not in use.

### Environment

Android

1. Application Target Platform: 
Windows 10

2. Development Operating System: 
Android Studio v3.0.1

3. Build Tools: 
27.0.3

4. React Native version: 
0.49.+

5. RNFirebase Version: 
3.2.7

6. Firebase Module:
any

After migrated to Android Plugin for Gradle 3.0.0 (https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html), using gradle wrapper version 4.4, transitive project dependency no longer works.

Before forced to update to gradle wrapper 4.4, it was working fine, however, after being forced to update to gradle wrapper 4.4 by Android Studio, I have to manually comment out all the modules that I am not using in the main project, or set transitive to true, i.e.

Does not work:
```
implementation(project(':react-native-firebase')) {
        transitive = false
}
```

Works (however I am only using a few modules and may not want to pull in all modules):
```
implementation(project(':react-native-firebase')) {
        transitive = true
}
```

Any help is highly appreciated! Thanks.

**Comment by Salakar** [comment]
@sgong-pdftron looking at the Gradle 4.4 api docs I can't see why this would no longer work - it still has transitive support. Can you try `api` instead of `implementation`

**Comment by sgong-pdftron** [comment]
@Salakar thanks for the reply! Unfortunately `api` does not work as well... 

Not sure if it helps, but this is the error I get. I am not using `ads` module.

![image](https://user-images.githubusercontent.com/20527369/37364230-2c0ee720-26b7-11e8-8e94-b46584044977.png)

**Comment by chrisbianca** [comment]
Closing in favour of https://github.com/invertase/react-native-firebase/issues/915
