### ISSUE TITLE
flow type issues in createUserAndRetrieveDataWithEmailAndPassword

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#862]
### Issue

I'm login user in via
```
const {
        user,
        additionalUserInfo
      } = await auth().createUserAndRetrieveDataWithEmailAndPassword(email, password);
```

Everything works fine, but there is a flow error:

> [flow] Promise (This type is incompatible with the expected param type of union: `Promise` | `T` Member 1: Promise Error: property `additionalUserInfo` Property not found in User Member 2: T Error: property `additionalUserInfo` Property not found in Promise)
> (method) RNFirebase.auth.Auth.createUserAndRetrieveDataWithEmailAndPassword(email: string, password: string): Promise<RNFirebase.UserCredential>
> [Flow]
> createUserAndRetrieveDataWithEmailAndPassword: Promise < User >
> 

As far as I understand `additionalUserInfo` is optional, yet it should still not throw that error correct? even if I just destructure `{ user }`, I get

> [flow] Promise (This type is incompatible with the expected param type of union: `Promise` | `T` Member 1: Promise Error: property `user` Property not found in User Member 2: T Error: property `user` Property not found in Promise)
> (method) RNFirebase.auth.Auth.createUserAndRetrieveDataWithEmailAndPassword(email: string, password: string): Promise<RNFirebase.UserCredential>
> [Flow]
> createUserAndRetrieveDataWithEmailAndPassword: Promise < User >
> 

### Environment

1. Application Target Platform: Both

2. Development Operating System: macOS High siearra

3. Build Tools: VSCode, flow

4. React Native version: ^0.53.3

5. RNFirebase Version: ^3.2.7

6. Firebase Module: Types

**Comment by chrisbianca** [comment]
@IljaDaderko Does the destructuring approach work properly with other Promises?  I can't help but think this might be a Flow limitation rather than anything with our Flow typings.

**Comment by IljaDaderko** [comment]
@chrisbianca I believe so, here is very similar method that works
```
const { user, additionalUserInfo } = await auth().signInAndRetrieveDataWithCredential(credential);
```

and without additionalUserInfo
```
const { user } = await auth().signInAndRetrieveDataWithCredential(credential);
```

Both don't throw errors above and look very simmilar

**Comment by chrisbianca** [comment]
Looks like we were returning the incorrect flow type.  I've just pushed up a fix which will land in the next release: https://github.com/invertase/react-native-firebase/commit/a6734fa4397271726219d8ebf22bed90b31d380c
