### ISSUE TITLE
analytics api parity with fully native offerings

### ISSUE THREAD

**Issue by elwhitman** [invertase/react-native-firebase#863]
I've noticed some differences in the google analytics api offerings based on another native module, namely https://github.com/idehub/react-native-google-analytics-bridge. Is there anything important that is missing or is it condensed? some clarity here would be helpful; because at the end of the day they are the same product, right?

**Comment by Ehesp** [comment]
The Firebase API reference for analytics only exposes the main/basic methods for analytics. The library you linked above provides a larger API surface with the core of GA, such as `trackMultiProductsPurchaseEvent`.

Firebase Analytics is more of a plug'in'play solution, however it may not provide everything your app needs.
