### ISSUE TITLE
admob is commented-out in v3.2.7

### ISSUE THREAD

**Issue by taiale** [invertase/react-native-firebase#865]
### Issue

I have just installed this module. However the admob mobulde is commented-out. Please help I'd to display admob in the iOS & Android app.
### Environment

iOS, Android

1. Application Target Platform:

macOS Sierra

2. Development Operating System:

Xcode 9.2

3. Build Tools:

4. React Native version:

react-native-cli: 2.0.1
react-native: 0.48.4

5. RNFirebase Version:

3.2.7

6. Firebase Module:

admob is commented-out as this:
// Modules commented-out do not currently have type definitions
  export class Firebase {
    private constructor();
    // admob: FirebaseModuleAndStatics<RNFirebase.admob.AdMob>;
...

**Comment by Ehesp** [comment]
https://github.com/invertase/react-native-firebase/pull/792

This PR is related - if you could help review it would be handy here as we're not big TS users.

**Comment by Salakar** [comment]
Thanks for reporting this issue. We're aware that AdMob has fallen behind on React Native Firebase and would like to bring it up to speed again. I will close this issue for now and track it as well as other issues collectively over on the `AdMob overhaul proposal` to be addressed in a future release. See #1259
