### ISSUE TITLE
[feature suggestion] expose ActionCodeSettings helper functions

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#870]
I am not sure if I understood this correctly, but while browsing the web to figure out if it is possible to somehow get bundle id / package name inside react-native javascript I found this documentation for firebase:

https://firebase.google.com/docs/reference/android/com/google/firebase/auth/ActionCodeSettings

At first glance it looks like a method exposed by android sdk that sits on `auth`? Interesting bits here are functions like `getIOSBundle` and `getAndroidPackageName`.

I think this can be useful addition? Particularly in cases like mine where I have 2 iOS targets and 2 Android flavours with different bundle id's and package names for dev and release which are both built in Release mode (i.e. can't target DEV global to set correct url / bundleID etc... in javascript based on target)

Would be cool if something like this (https://rnfirebase.io/docs/v3.3.x/auth/reference/ActionCodeSettings)

```
{
  android: { 
    packageName: "com.example.app", 
    installApp: true, 
    minimumVersion: 19
  },
  handleCodeInApp: true,
  iOS: { 
    bundleId: "com.example.app" 
  },
  url: "example.com",
}
```

could be change to

```
{
  android: { 
    packageName: firebase.auth().ActionCodeSettings.getAndroidPackageName(), 
    installApp: true, 
    minimumVersion: firebase.auth().ActionCodeSettings.getAndroidMinimumVersion()
  },
  handleCodeInApp: true,
  iOS: { 
    bundleId: firebase.auth().ActionCodeSettings.getIOSBundle()
  },
  url: "example.com",
}
```

**Comment by chrisbianca** [comment]
@IljaDaderko I'm afraid that's not how ActionCodeSettings works. It is a builder to allow you to pass information into auth methods, not to retrieve information about the current application.

Will close as what you're looking for just isn't achievable, sorry.

**Comment by IljaDaderko** [comment]
Got it, my bad for miss-understanding 👍

**Comment by Salakar** [comment]
@IljaDaderko if it helps you can also get this from `react-native-device-info`: https://github.com/rebeccahughes/react-native-device-info#getbundleid
