### ISSUE TITLE
How can i measure the campaigns?

### ISSUE THREAD

**Issue by Mamdouh-Symbyo** [invertase/react-native-firebase#873]
### Issue

is the library supported to tracking and measure campaigns like this in Google Analytics : 
[https://developers.google.com/analytics/devguides/collection/android/v4/campaigns](url)

### Environment

1. Application Target Platform: iOS & Android

2. Development Operating System: macOS High Sierra

3. Build Tools: VS Code

4. React Native version: 0.49

5. RNFirebase Version: V3.1.1

6. Firebase Module: analytics

**Comment by Salakar** [comment]
This library is for Firebase Analytics not GA sorry, see what we support [here](https://rnfirebase.io/docs/v3.3.x/analytics/reference/analytics).

**Comment by gianpaj** [comment]
For others coming up here, see this:
https://github.com/idehub/react-native-google-analytics-bridge/issues/30

**Comment by michaelshengy** [comment]
> ### Issue
> is the library supported to tracking and measure campaigns like this in Google Analytics :
> [https://developers.google.com/analytics/devguides/collection/android/v4/campaigns](url)
> 
> ### Environment
> 1. Application Target Platform: iOS & Android
> 
> 1. Development Operating System: macOS High Sierra
> 
> 1. Build Tools: VS Code
> 
> 1. React Native version: 0.49
> 
> 1. RNFirebase Version: V3.1.1
> 
> 1. Firebase Module: analytics

Hi,  I have the same issue same as yours.  Finally you solved it or have another solution?
