### ISSUE TITLE
Stuck at Loading Dependancy Graph

### ISSUE THREAD

**Issue by vishnuchalla** [invertase/react-native-firebase#874]
Getting Stuck at Loading Dependancy Graph when the project is started

![issue](https://user-images.githubusercontent.com/28471457/37270094-617f42e8-25f3-11e8-9fef-ec0f290e3585.png)

**Comment by chrisbianca** [comment]
@vishnuchalla Sorry to say that this is a react-native issue, nothing to do with react-native-firebase
