### ISSUE TITLE
react-native-firebase/node_modules/.bin/postinstall-build'. Couldn't follow symbolic link

### ISSUE THREAD

**Issue by BonnieMilian** [invertase/react-native-firebase#877]
react-native-firebase/node_modules/.bin/postinstall-build'. Couldn't follow symbolic link
"version": "3.0.6"
React 16.0.0 RN 0.50.0

Android (don't know if ios too)
Only Release, on the building

**Comment by Ehesp** [comment]
Can you try updating, the RNFB version is quite a bit behind what we're on now.

**Comment by Ehesp** [comment]
Please let us know if you're still having issues.
