### ISSUE TITLE
Notification triggers twice when app killed

### ISSUE THREAD

**Issue by poptocrack** [invertase/react-native-firebase#879]
### Issue

Since I've update rnf from the version 3.2.1 to 3.3.1, I have a problem with cloud messaging:
When my app is in the foreground, everything works fine, notifications are received and displayed normally.

When my app is inactive, killed or in the background, the notification is received but displayed twice.

The problem isn't coming from the firebase console or my backend.
 
### Environment

1. Application Target Platform:

Android and iOS, the bug is only present with Android devices

2. Development Operating System:
Mac osX Sierra

3. Build Tools:
Android studio, and xCode

4. React Native version:

0.52, expo sdk 25, detached app

5. RNFirebase Version:

3.3.1

6. Firebase Module:

Cloud messaging (also using crashlytics)

**Comment by chrisbianca** [comment]
@poptocrack we are about to release an alpha of our new notifications and messaging rewrite which will resolve this issue. See #595

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)

**Comment by poptocrack** [comment]
If anyone is coming into this issue again, it's probably because you have a detached Expo app.

In that case you should try to delete this from your `AndroidManifest.xml`
```
    <service
      android:name=".gcm.ExponentGcmListenerService"
      android:exported="false">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
      </intent-filter>
    </service>
```
