### ISSUE TITLE
error java.lang.Double cant be cast to java.lang.integer when using parameter .limitToLast(10) 

### ISSUE THREAD

**Issue by xabree** [invertase/react-native-firebase#88]
error java.lang.Double cant be cast to java.lang.integer when using parameter .limitToLast(10) 

version : "react-native-firebase": "^1.0.1",

```
import {Platform} from 'react-native';
import RNFirebase from 'react-native-firebase';

const configurationOptions = {
  debug: true,
  persistence: Platform == 'ios' ? false : true,
};
const firebase = new RNFirebase(configurationOptions); 
let ref = firebase.database().ref("posts");

ref.orderByChild('startTime').limitToLast(10).once('value', snap => {
      console.log(snap.val())
 });
```

![whatsapp image 2017-05-05 at 2 05 50 pm](https://cloud.githubusercontent.com/assets/24905186/25736719/e75fb122-319d-11e7-80ba-673baa624825.jpeg)

**Comment by Ehesp** [comment]
Hey this has been fixed via https://github.com/invertase/react-native-firebase/commit/b4622006bfe99f69125540b73ae81ae0e570956e Not released it in a new version yet, but will be coming in soon. Only a one liner so could just update the code in your node_modules if needed.

**Comment by Salakar** [comment]
@xabree v1.0.2 is now up on NPM with this fix in. Feel free to update.
