### ISSUE TITLE
How to use logEvent(event, params) returns void;?

### ISSUE THREAD

**Issue by soniczsonic** [invertase/react-native-firebase#883]
I love this plugin.
However, there is no example.

Is there any example for Analytics?

**Comment by Ehesp** [comment]
`firebase.analytics().logEvent('Clicked Button', { foo: 'bar' });`

Simple as that :)

**Comment by bemazo** [comment]
@Ehesp how we can fetch errors? Is there a .catch() property?

**Comment by chrisbianca** [comment]
@bemazo not at the moment, but we plan on making all methods that go across the bridge return promises at some point in the future.

**Comment by madeeha96** [comment]
firebase
      .analytics()
      .logEvent("HomeScreen", {
        ec: "Screen Event",
        ea: "madeeha" + "is on Home Screen",
        el: "Home Screen",
        ev: null
      });

Here is my function and its not working

**Comment by ovy9086** [comment]
apparently the params do not reach Firebase ?
