### ISSUE TITLE
UILocalNotification is deprecated

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#887]
### Issue
As per firebase messaging docs, one of the functions that needs to be added to AppDelegate.m file is

```
-(void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [RNFirebaseMessaging didReceiveLocalNotification:notification];
}
```

This throws warning

> 'UILocalNotification' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationRequest

Nothing major, but figured worth mentioning

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS High Sierra

3. Build Tools: Xcode 9.2

4. React Native version: 0.54

5. RNFirebase Version: 3.3.1

6. Firebase Module: messaging

**Comment by Salakar** [comment]
@IljaDaderko thanks for the heads up. If you're feeling daring you're welcome to give the new messaging and notifications implementation a go, it's on master, the docs are on the docs website by selecting master in the version select drop down.

**Comment by IljaDaderko** [comment]
@Salakar closing this as I didn't realise it was present on master. Any breaking changes? If not might give it a try on a side branch 👍

**Comment by chrisbianca** [comment]
There's definitely a few breaking changes, but the docs on master should give you much better instruction than the docs for the previous version!!

As an aside, we need to keep the presence of the above UILocalNotification reference in order to support iOS 9 and 10.
