### ISSUE TITLE
Android app crashes / stops upon receiving notification

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#888]
### Issue
I've set up notifications for iOS and Android, but for some reason when android app receives notification it stops / crashes. Upon inspecting my manifest file RN class seems to be undefined there

<img width="759" alt="screen shot 2018-03-17 at 16 45 36" src="https://user-images.githubusercontent.com/3154053/37556747-da18c9dc-2a02-11e8-87ce-6fd4b9e76925.png">

I also have another change I made which is 

```
android:launchMode="singleTask"
```

in documentation it is

```
android:launchMode="singleTop"
```

but this doesn't work for me in terms of universal links.

### Environment

1. Application Target Platform: Android

2. Development Operating System: macOS high sierra

3. Build Tools: Android studio 3.0, emulator running Nexus 5X with api lvl 26 and play store

4. React Native version: 0.54..2

5. RNFirebase Version: 3.3.1

6. Firebase Module: Messaging

**Comment by chrisbianca** [comment]
@IljaDaderko looks like you're using the docs for master (i.e. the latest version of messaging and notifications), but might not have installed the code from master?

**Comment by IljaDaderko** [comment]
![picardfacepalm](https://user-images.githubusercontent.com/3154053/37565064-ccdad41a-2aaa-11e8-89fa-b8b8c9f1af02.jpg)
