### ISSUE TITLE
How can I do pagination on Android?

### ISSUE THREAD

**Issue by maestrolsj** [invertase/react-native-firebase#89]
`  var itemsRef = firebaseApp.database().ref().limitToFirst(10);

          itemsRef.once('value', function(snapshot) {
              console.log('Snap: ', snapshot.val());
          });
`

IOS works well 
...but came out Error on Android.

Error msg is  : 
<img width="963" alt="2017-05-06 4 12 05" src="https://cloud.githubusercontent.com/assets/16445243/25770681/ebc4979e-3276-11e7-8dc2-cb38576e6d95.png">

**Comment by Salakar** [comment]
@maestrolsj this was fixed in version 1.0.2 - please upgrade your version (remove yarn.lock file and upgrade as it does weird things sometimes)

**Comment by maestrolsj** [comment]
Thank you so much. it works
