### ISSUE TITLE
[iOS] crash when setting user property as number and not string

### ISSUE THREAD

**Issue by jgfidelis** [invertase/react-native-firebase#892]
### Issue

On the line:
`analytics.setUserProperty(name, value);`

If `value` is a number and not a string, our app will crash.

We are fixing it by calling `toString()` on our number, but I think this would be a simple fix for the rnfirebase library to handle this.
<img width="559" alt="screen shot 2018-03-19 at 14 22 19" src="https://user-images.githubusercontent.com/4925068/37611435-19f3e4cc-2b81-11e8-9d8f-35fe6b2d24bc.png">

### Environment

ios 11.1

4. React Native version:

RN: 0.53

5. RNFirebase Version:

RNFirebase: 3.3.1
Error on RNFirebase analytics

**Comment by chrisbianca** [comment]
I've resolved this as part of: https://github.com/invertase/react-native-firebase/commit/e3ea0d3fc7660a5cea7f8d3e048476468573227b

The iOS and Android SDKs explicitly expect a string parameter, so we are also now enforcing this requirement in our SDKs and will throw an error if a non-string value is received.
