### ISSUE TITLE
[WEB SDK COMPAT] await .push() returns null, but works on web sdk

### ISSUE THREAD

**Issue by brunolemos** [invertase/react-native-firebase#893]
### Issue

Given the code:

```js
const messageRef = await firebase.database().ref('xxx/123/messages').push(message)
// messageRef = null
```

If I use `await` it returns null. But on web sdk it works just fine.
Just converted from firebase to react-native-firebase and faced this compatibility problem.
If I don't use `await` it works fine, but it should match the web.

Related but closed: #147, #696 

### Environment

iOS (not tested on Android)

1. Application Target Platform: macOS High Sierra

2. Development Operating System: iOS 11

3. Build Tools: ?

4. React Native version: 0.54

5. RNFirebase Version: 3.3.1

6. Firebase Module: Database

**Comment by Friis1978** [comment]
Anything new on this issue, still does not work for me.

`const ref = firebase.database().ref(`/users/${uid}/points`).push({
                  name: propValues.name,
                  address: propValues.address,
                  number: propValues.number,
                })
                .then(() => {
                  const key = ref.key;
                  console.log(key);
                })
                .catch((error) => {
                  console.log(error);
                });`

This should give me the key value, but is empty.

**Comment by Friis1978** [comment]
Hmmm It actually worked without the then, so the problem is solved in my case. 

Just thought that the reference key was based on what the promise returned, so I was using the 'then' to wait for that promise. 

This is the answer:
`const ref = firebase.database().ref(dbref).push({
            name: propValues.name,
            address: propValues.address,
          });
          console.log(ref.key);`

**Comment by Salakar** [comment]
@Friis1978 without the await is also correct as creating a new reference + id path via `push()` is synchronous/client sided, though I believe the web SDK supports await as well like you mentioned above so we still need to add support for that our end.

Are you able to test the following 3 scenarios on the Web SDK if you still have it handy and report back with the logs if possible, would be super helpful:

```js
// 1
const ref1 = firebase.database().ref(dbref).push();
console.log('1a', ref1.key); // should be key ?
const result = await ref1.set({ name: propValues.name, address: propValues.address });
console.log('1b', result); // should be null ?

// 2
const ref2 = await firebase.database().ref(dbref).push({ name: propValues.name, address: propValues.address });
console.log('2a', ref2.key); // should be key ?

// 3
const ref3 = await firebase.database().ref(dbref).push();
console.log('3a', ref3.key); // should be key ?
const result = await ref3.set({ name: propValues.name, address: propValues.address });
console.log('3b', result); // should be null ?
```


---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by simonbengtsson** [comment]
Results with firebase `5.4.2`:

```
1a -LLuT3yPEkWQYq7JinLP
1b undefined
2a -LLuT4A5DPPpDSjEaGg-
3a -LLuT4CbmLlncywg1l3e
3b undefined
```

**Comment by Salakar** [comment]
@simonbengtsson awesome, thanks for that - looks like `await` support on `push()` is missing then on RNFB - will get it fixed.

**Comment by Salakar** [comment]
Have just pushed a re-write of the `push()` logic to match the Web SDK. 

Have added test cases from this issue and others which can be seen working here: https://github.com/invertase/react-native-firebase/blob/database-fixes/tests/e2e/database/ref/push.js#L73

This will land in v5.1.0, apologies for the delay on this one.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
