### ISSUE TITLE
[WEB SDK COMPAT] .info/connected returns 1 instead of true like web sdk

### ISSUE THREAD

**Issue by brunolemos** [invertase/react-native-firebase#894]
### Issue

```js
firebase.database().ref('.info/connected').on('value', snapshot => {
  console.log(snapshot.val()) // 1 on react-native-firebase, true on web sdk
})
```

### Environment

iOS (not tested on Android)

1. Application Target Platform: macOS High Sierra

2. Development Operating System: iOS 11

3. Build Tools: ?

4. React Native version: 0.54

5. RNFirebase Version: 3.3.1

6. Firebase Module: Database

**Comment by Ehesp** [comment]
I believe this one was brought up quite a long time ago, which at the time we identified as an iOS SDK issue - but we could handle it JS side to return a truthy value.

**Comment by Salakar** [comment]
Hey 👋 	

This is now fixed on v6 and we have a test up as well for this; https://github.com/invertase/react-native-firebase/blob/master/packages/database/e2e/internal/connected.e2e.js#L59

[[v6 Database Changelog]](https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md#realtime-database-database)

Will go-ahead and close this issue pending a v6 release. Thanks
