### ISSUE TITLE
Warning on createLocalNotification

### ISSUE THREAD

**Issue by kriptonhaz** [invertase/react-native-firebase#896]
### Issue

I got a warning when tried to createLocalNotification 

> Possible Unhandled Promise Rejection (id: 0): TypeError: Requested keys of a value that is not an object. 

The notification is showed but still got warning like above, this is my code:

```
firebase.messaging().createLocalNotification({
      title: 'Test App',     
      body: 'body',
      id: '1521522002037',
      show_in_foreground:true,
      priority:"high",
      sound: 'default',
      opened_from_tray: false 
    });
```

There's no documentation about this in latest doc. I hope someone will update it alongside with schedule notification.

### Environment

1. Application Target Platform: Android
2. Development Operating System: Windows 10
3. Build Tools: vscode SDK version 26.0.1
4. React Native version: 0.48.4
5. RNFirebase Version: 3.3.1
6. Firebase Module: Messaging

**Comment by chrisbianca** [comment]
@kriptonhaz we are about to release an alpha of our messaging rewrite which has proper documentation and better functionality. Please track #595 for updates.

**Comment by chrisbianca** [comment]
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)
