### ISSUE TITLE
undefined is not a function _reactNativeFirebase2.default.messaging.getToken()

### ISSUE THREAD

**Issue by judemanutd** [invertase/react-native-firebase#897]
### Issue

The app crashes with the following error.

    undefined is not a function (evaluating '_reactNativeFirebase2.default.messaging.getToken()'

### Environment

1. Application Target Platform: Android

2. Development Operating System: Windows 10

3. Build Tools: Android Studio 27.0.3

4. React Native version: 0.54.0

5. RNFirebase Version: 3.3.1

6. Firebase Module: messaging

my app/build.gradle file looks like this 

    dependencies {

    implementation "com.google.android.gms:play-services-base:11.8.0"
    implementation(project(':react-native-firebase')) {
        transitive = false
    }

    implementation 'com.google.firebase:firebase-core:11.8.0'
    implementation 'com.google.firebase:firebase-messaging:11.8.0'

    implementation project(':react-native-orientation')
    implementation project(':react-native-youtube')
    implementation project(':react-native-vector-icons')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:27.1.0"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    }

project build gradle file 

    buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.google.gms:google-services:3.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

        allprojects {
          repositories {

             google()
             mavenCentral()
             maven { url 'https://jitpack.io' }

              mavenLocal()
              jcenter()
             maven {
               // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
                url "$rootDir/../node_modules/react-native/android"
            }
          }
        }

The file where i have used the command 

    import firebase from 'react-native-firebase';
     .......

     componentDidMount() {
        console.debug("LIFECYCLE componentDidMount");
        firebase.messaging.getToken().then(value => {
            console.debug("FCM is " + value);
        }).catch(reason => {
            console.error(reason);
        }).finally(() => {
            console.debug("FCM finally ");
        })
    }

**Comment by chrisbianca** [comment]
Use: `firebase.messaging().getToken()` not `firebase.messaging.getToken()`

**Comment by judemanutd** [comment]
@chrisbianca that worked thank you, I had a few follow up questions that i had hoped you could answer.

 1. When i worked on a native android project I didn't have to import `com.google.android.gms:play-services-base:11.8.0` into my project, I only plan on using cloud messaging, analytics and crashlytics in my current react native project, can I exclude the import?

 2.  The documentation does not specify any particular lifecycle component that i need to write the code in, for example I have written the current implementation of cloud messaging in the `componentDidMount` of a particular component like so

    componentDidMount() {
        console.debug("LIFECYCLE componentDidMount");
        firebase.messaging().getToken().then(value => {
            console.debug("FCM is " + value);
        }).catch(reason => {
            console.error(reason);
        }).finally(() => {
            console.debug("FCM finally ");
        });

        firebase.messaging().subscribeToTopic('testing');

        firebase.messaging().onMessage(message => {
            console.debug("FCM got message " + message);
        });
    }

Is this the correct way to do it ? Or is there a preferred way?

 3. The documents do not mention anything about creating notifications manually, is it possible to do so?

**Comment by chrisbianca** [comment]
@judemanutd No problem at all.

1) I believe that play-services-base is required by all play service libraries, so even if you exclude it, it will be imported by other libs.

2) `componentDidMount` is a good place to do this

3) Documentation for v3 is sparse. This morning we released an alpha of v4 which has a complete rewrite of messaging and notifications with extensive documentation.  If you're just getting started, you might be better to look at this version: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

**Comment by judemanutd** [comment]
Building of notifications and most importantly notification channels, just what I needed, thank you so much, the documentation looks much richer and informative now.

**Comment by chrisbianca** [comment]
Awesome. Do let us know if you come across any issues!
