### ISSUE TITLE
Firestore performance?

### ISSUE THREAD

**Issue by savvopoulos** [invertase/react-native-firebase#899]
### Issue
Hi there, I'm trying to understand how Firestore on rnfirebase would perform with medium/large datasets (2-10k documents). It seems to me that every time there is an update to a collection, the only option to get that update is to re-read the entire collection via onSnapshot / forEach - I haven't seen a way to receive incremental updates.

Am I overthinking this? Does the library do something in the background to alleviate this (e.g. at least re-using unchanged references)?

Thanks!

**Comment by Ehesp** [comment]
Keeping such a large dataset in memory, especially on a React Native app is generally a bad idea anyway and you'll most likely hit performance issues somewhere.

Generally you need to combine the FlatList/SectionList component and using Firestore together - only querying an initial dataset of say 50 records, and as the user scrolls down append the next 50 records into the dataStore.

When it comes to the realtime aspect of things, it does indeed get trickier. Your best solution would be to query say 0-50 records, 0-100 records, 0-150 records and so on. This won't effect performance too much as long as you properly render a component on each row which only re-renders when critical data has updated (using shouldComponentUpdate or a PureComponent).

Also downloading 10k documents at once is bad for user experience, they'll have long waiting times and be downloading data they may not even use. Not to mention the Firestore costs this will incur along with high bandwidth usage.

**Comment by savvopoulos** [comment]
How would querying work with offline persistence?

10k records is a pretty small dataset - let's say a 500KB JSON file. Of course it needs to be rendered smartly, but it feels like something that a phone from the last 3-5 years should be able to handle.

**Comment by Salakar** [comment]
@savvopoulos lets move this discussion over to the [community on discord](https://discord.gg/C9aK28N) - would be much easier to discuss non bug related questions and get input from other devs in the community who've dealt with the same things :)
