### ISSUE TITLE
Transaction failure: Error: Firestore: Operation was rejected because the system is not in a state required for the operation`s execution. (firestore/failed-precondition).

### ISSUE THREAD

**Issue by israelidanny** [invertase/react-native-firebase#904]
I'm trying to run this seemingly simple transaction on iOS, and it returns the above error. I can't figure out for the life of me what could be causing it, it's a simple one read one write transaction and there's nothing blocking the writes (database isn't a production app).

`Transaction failure: Error: Firestore: Operation was rejected because the system is not in a state required for the operations execution. (firestore/failed-precondition).`

Here is the code:
```javascript
function follow(userId, showId) {
  const firestore = firebase.firestore();
  const followRef = firestore.collection('follows').doc(`${showId}-${userId}`);

  return firestore.runTransaction(transaction => {
    return transaction.get(followRef)
      .then(followDoc => {
        if (!followDoc.exists) {
          transaction.set(followRef, { userId, showId });
        }
      });
  }).then(result => {
    console.log('Transaction success', result);
  }).catch(err => {
    console.log('Transaction failure:', err);
  });
}
```

**Comment by Salakar** [comment]
@israelidanny a `failed pre-condition` generally means you're missing an index, which is weird as you're not doing a query. It might also possibly mean the `follows` collection isn't created - can you check it's created on the Firebase Console?

**Comment by israelidanny** [comment]
@Salakar Yup, I tried to create the collection and fill it with some random document, and then run it. Same result.

**Comment by Salakar** [comment]
@israelidanny ok thanks for confirming - could you provide me as much detail as possible on your environment so I can investigate:

- xcode version
- react-native-firebase version
- pod file + lock file contents
- firestore rules
- any sample data
- does it work on android?

**Comment by israelidanny** [comment]
🤦‍♂️ ... Alright, my issue was bad Firestore rules. It was basically refusing write based on insufficient rule permissions... 
However, the error message isn't helpful, and if it could be somehow adjusted to reflect the actual error/issue it would be amazing for people in the future!

**Comment by Salakar** [comment]
@israelidanny glad you sorted it. The error message comes direct from the Firebase Native SDK's unfortunately - agree though, that message wasn't very helpful lol
