### ISSUE TITLE
 Not allowed to start service Intent RNFirebaseBackgroundMessagingService

### ISSUE THREAD

**Issue by mleonard87** [invertase/react-native-firebase#906]
### Issue

I'm getting the following stack trace when sending a message when the app is closed.

```
03-25 17:19:36.890 28088-28114/com.my.app E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
  Process: com.my.app, PID: 28088
  java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.my.app/io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService (has extras) }: app is in background uid UidRecord{cd2b739 u0a383 RCVR idle change:idle|uncached procs:1 seq(0,0,0)}
      at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
      at android.app.ContextImpl.startService(ContextImpl.java:1477)
      at android.content.ContextWrapper.startService(ContextWrapper.java:650)
      at io.invertase.firebase.messaging.RNFirebaseMessagingService.onMessageReceived(RNFirebaseMessagingService.java:41)
      at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source:320)
      at com.google.firebase.iid.zzg.run(Unknown Source:26)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
      at java.lang.Thread.run(Thread.java:764)
```

I've added the following to AndroidManifest.xml
```
<service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />
```

And I'm registering the task like this:
```
AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => handleBackgroundMessage);
```

### Environment

1. Application Target Platform: Android

2. Development Operating System: macOS

3. Build Tools: 26.0.2

4. React Native version: 0.54

5. RNFirebase Version: 4.0.0-alpha.1

6. Firebase Module: messaging, notifications

**Comment by chrisbianca** [comment]
@mleonard87 can I ask what version of the Android SDK you're targeting in your build.gradle?

**Comment by mleonard87** [comment]
compileSdkVersion 26
buildToolsVersion "26.0.2"
minSdkVersion 16
targetSdkVersion 26

**Comment by mleonard87** [comment]
I've managed to progress past this error but now I get `03-25 13:09:50.919 21632-21672/? E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling startHeadlessTask)`

**Comment by chrisbianca** [comment]
How did you progress past the original error?

Can I see all the code relating to `startHeadlessTask`?

**Comment by mleonard87** [comment]
I thought I added `android.permission.WAKE_LOCK` but I've removed that again now and I still get the second error. My apologies, I've been doing a bunch a hacking around to try and get it to work.

I don't have any app specific code relating to `startHeadlessTask` - I assumed this was in React or react-native-firebase.

I register the headless task with:
```javascript
AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => handleBackgroundMessage);

const handleBackgroundMessage = async (message) => {
  const notification = new firebase.notifications.Notification()
    .setNotificationId('mike001')
    .setTitle(message.data.title)
    .setBody(message.data.body);

  if (Platform.OS === 'android') {
    notification.android.setChannelId('mikeDefault');
    notification.android.setSmallIcon('ic_notification');
    notification.android.setColor('red');  // Reposit blue
    notification.android.setAutoCancel(true);
  }

  firebase.notifications().displayNotification(notification);

  return Promise.resolve();
};
  
```

My MAIN app activity is a pure Java splash screen screen which then starts MainActivity - possibly this is the issue? I've had to launch the new Intent with the following code to copy forwards the intent extras so that `getInitialNotification` will work.

```java
Intent thisIntent = this.getIntent();
nextIntent.putExtras(thisIntent);
```

**Comment by chrisbianca** [comment]
I trust you have added:

`import { AppRegistry } from 'react-native';`?

**Comment by mleonard87** [comment]
Yes, I have.

I get the AppRegistry error if I close the app and send a notification. I get no errors when the registerHeadlessTask code is called to actually register the task.

**Comment by mleonard87** [comment]
I've done so digging to better reproduce the issue and help with this thread.

I reproduced the original error in my first comment - `Not allowed to start service Intent { cmp=com.my.app/io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService (has extras) }: app is in background` - by by removing the default pure-java splash screen (this was the LAUNCHER activity and marked up with `android:launchMode="singleTop"`).

Looking at the Android documentation [Android documentation](https://developer.android.com/about/versions/oreo/background.html) it appears that the way background execution works is different starting in API26.

Notably, `The startService() method now throws an IllegalStateException if an app targeting Android 8.0 tries to use that method in a situation when it isn't permitted to create background services.`

`startService()` is called in [RNFirebaseMessagingService.java#L41](https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/messaging/RNFirebaseMessagingService.java#L41) so this may be the issue.

This would make sense as my targetSdkVersion is 26. What SDK versions does react-native-firebase support? I can't find anything in the documentation?

I have locally patched `RNFirebaseMessagingService.onMessageReceived` with the following to handle API > 26 and < 26. I am happy to send a pull request if this is the right approach but I am not familiar with Android background services.

```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
  this.getApplicationContext().startForegroundService(headlessIntent);
} else {
  this.getApplicationContext().startService(headlessIntent);
}
```

This now appears to work for API 26 and above but I now get the `Module AppRegistry is not a registered callable module (calling startHeadlessTask` error.

It's worth noting that this is a data-only message. If I do all of this with a notification + data message everything works fine, although this these firebase takes care of the notifications so I do need need the `AppRegistry.registerHeadlessTask(...)` code.

**Comment by mleonard87** [comment]
I've resolved the `Module AppRegistry is not a registered callable module (calling startHeadlessTask)` issue by putting my `AppRegistry.registerHeadlessTask(...)` code in index.js - I was not aware that it had to be here, doing this makes it work.

My above suggested fix to use `startForegroundService` does not work as I originally reported. The Android documentation states that the service started with `startForegroundService` "will call startForeground(int, android.app.Notification) once it begins running". Note that the second argument to this is a Notification. I've gotten around this by override `onStartCommand` of `RNFirebaseBackgroundMessagingService` with the following. But at this point its very much feeling like a hack as I deliberately pass a notification that does not have a channel so it won't display.

```java
  @Override
  public int onStartCommand(Intent intent, int flags, int startId) {
    HeadlessJsTaskConfig taskConfig = getTaskConfig(intent);
    if (taskConfig != null) {

      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        Notification notification = new Notification();
        startForeground(1, notification);
        startTask(taskConfig);
      } else {
        startTask(taskConfig);
      }

      return START_REDELIVER_INTENT;
    }
    return START_NOT_STICKY;
  }
```

**Comment by chrisbianca** [comment]
@mleonard87 Thanks for the continued information.  I'm glad you've resolved the `Module AppRegistry is not a registered callable module` part of the issue.  I'll add something to the docs to stress that this call needs to be made from the entry point to your application.

With regards to the background service issue - this is what I'd concluded too.  It's odd that it didn't come up in my testing as I was purposefully targeting SDK 26 to ensure it was compatible with the latest version of Android.  Are you testing on a real device or on a simulator?

I'll do some investigation myself over the next couple of days to see if I can figure out a suitable approach that works for both Oreo and earlier versions.  We'll make sure we address it properly before a full 4.0 release.

**Comment by mleonard87** [comment]
I've been using a real device with API 27 and a simulator with API 26. Both presented the same symptoms. 

Here's a branch based on the 4.0.0-alpha.1 release that I've put my hacks on https://github.com/mleonard87/react-native-firebase/tree/mleonard87-v40.0.0-alpha.1-api26

**Comment by chrisbianca** [comment]
@mleonard87 I'm really sorry, but I just haven't been able to reproduce this problem.  I've just set up a new simulator running API 27 to double check as my API 26 simulator was already running without any issues.

Both when the app is in the background and when it's closed, my background remote message is triggering the background messaging intent and subsequent React Native code.

Are you able to send over your complete AndroidManifest.xml so I can take a look?

**Comment by arash8m** [comment]
I'm having the same issue as well when the app is closed and is receiving data only message. I'm using react-native-navigations and not sure if that's what mleonard87 and I have in common and  could be causing the "Not allowed to start service Intent" error. 

API 26
compileSdkVersion 26
targetSdkVersion 26
RNFirebase: 4.0.0-rc.2
React native: 0.53.3

**index.android.js**

`import { AppRegistry } from 'react-native';
import bgMessaging from './src/bgMessage';

AppRegistry.registerHeadlessTask(
  'RNFirebaseBackgroundMessage',
  () => bgMessaging
); 
import App from './src/app';`

**AndroidManifest.xml**

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.app"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />                                               
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="26" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <meta-data android:name="com.facebook.sdk.ApplicationId" 
        android:value="@string/facebook_app_id"/>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
        <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
      </service>
      <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
        <intent-filter>
          <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
        </intent-filter>
      </service>
      <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />
    </application>
</manifest>`

**Comment by mleonard87** [comment]
Its worth noting that this is with data-only messages, notifications work fine. And that this only occurs when the app is closed rather than just backgrounded.

Also, I am using react-native-firebase@4.0.0-alpha.1 as I haven't had a chance to overcome #900 yet.

Heres my manifest.xml
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.my.app">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:allowBackup="true"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">

        <meta-data
                android:name="com.google.firebase.messaging.default_notification_icon"
                android:resource="@drawable/ic_notification" />
        <!-- Set color used with incoming notification messages. This is used when no color is set for the incoming
             notification message. See README(https://goo.gl/6BKBk7) for more. -->
        <meta-data
                android:name="com.google.firebase.messaging.default_notification_color"
                android:resource="@color/primary_blue" />

        <service
            android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        <service
            android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>

        <!-- This allows background messages -->
        <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />

        <activity
            android:launchMode="singleTop"
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:windowSoftInputMode="adjustResize"
            android:theme="@style/SplashScreen"
            android:screenOrientation="portrait"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

    </application>

</manifest>
```

**Comment by chrisbianca** [comment]
@mleonard87 @arash8m what versions of the Android firebase libs are you importing in your `build.gradle`?

**Comment by chrisbianca** [comment]
@mleonard87 @arash8m Figured it out!

The message priority has to be set to `high` to allow the app to launch the background service intent :D

**Comment by chrisbianca** [comment]
I have added a note to the documentation: https://rnfirebase.io/docs/v4.0.x/messaging/receiving-messages#4)-(Optional)(Android-only)-Listen-for-FCM-messages-in-the-background

**Comment by mleonard87** [comment]
How is this done in practice? I thought I was already doing this. I POST to fcm with the following.

```
POST https://fcm.googleapis.com/fcm/send
{
	"android": {
		"priority": "high"
	},
	"data": {
		"title": "Message from Postman", 
		"body": "This is a message from postman!"
	},
	"registration_ids":[...]
}
```

**Comment by chrisbianca** [comment]
For the /fcm/send endpoint, priority lives at the top level:

```
{
    "registration_ids":[...]
    "data": {
    	"title": "Message from Postman", 
    	"body": "This is a message from postman!"
    },
    "priority": "high"
}
```
You're mixing up the structure between the legacy endpoint above and the new v1 endpoint which allows more bespoke customisation for android and ios

**Comment by mleonard87** [comment]
This still isn't working for me. I appear to get the same error.

**Comment by chrisbianca** [comment]
Very strange. It's definitely the priority field that's the issue. When I remove the priority field I get the same error that you're seeing.  Add it back in and the message handler works just fine.

**Comment by mleonard87** [comment]
Is this with alpha.1? Or rc.2? Should make a difference?

I can try upgrading to rc.2 but I might not be able to get around to it until after Easter.

**Comment by chrisbianca** [comment]
It's rc.2, but I'm fairly sure nothing changed around this between the alpha and release candidates

**Comment by arash8m** [comment]
I can confirm adding the priority fixes the issue. I'm using Android firebase 12.0.0.
It also fixes a crash when you receive data-only message with the following conditions:
- App is in background (not killed)
- firebase.messaging().onMessage() listener is registered

@chrisbianca I noticed you updated the doc in section 4 only, but the fix applies to section 3 as well if anyone else is experiencing a crash.

**Comment by chrisbianca** [comment]
@arash8m Glad that this fixes the issue for you.

What sort of crash are you seeing in the second scenario?  I've not come across this before, but then I've also not tested it with anything other than `high` priority.

Do you have a stack trace you could send over?

**Comment by arash8m** [comment]
I believe it might have been because I wasn't registering the callback right either for headlessjs or onMessage. Below is the stack trace, but I cannot reproduce it anymore.

`
03-25 01:07:20.477 23874-24046/com.appE/ReactNativeJS: undefined is not a function (evaluating 'taskProvider()(data)')
03-25 01:07:20.486 23874-24047/com.app E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                           Process: com.app, PID: 23874
                                                           com.facebook.react.common.JavascriptException: undefined is not a function (evaluating 'taskProvider()(data)'), stack:
                                                           startHeadlessTask@57518:21
                                                           __callFunction@4416:49
                                                           <unknown>@4186:31
                                                           __guardSafe@4378:13
                                                           callFunctionReturnFlushedQueue@4185:21
                                                           
                                                               at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
                                                               at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
                                                               at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                               at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                               at android.os.Handler.handleCallback(Handler.java:789)
                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                               at android.os.Looper.loop(Looper.java:164)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                               at java.lang.Thread.run(Thread.java:764)
`

**Comment by dbyilmaz** [comment]
@arash8m  did you solve it?

**Comment by arash8m** [comment]
@dbyilmaz yes, just make sure registerHeadlessTask is in your index.js file. 
https://rnfirebase.io/docs/v4.0.x/messaging/receiving-messages  (bottom of the page)

**Comment by aminosman** [comment]
My issue was I had not created a channel for my messages. This is required on android. Make sure you have created the channel prior to trying to send messages though one. 

[https://rnfirebase.io/docs/v4.0.x/notifications/android-channels](Docs)

**Comment by devpascoe** [comment]
Having these issues on data only messages to android. Tried all the configs, same result as original error.

**Comment by redexp** [comment]
Also, don't forget to return promise from your `registerHeadlessTask` callback

**Comment by Viswa-Vinod** [comment]
none of the suggestions in this thread worked for me -
getting the IllegalStateException when app is killed for data only messages. I am getting these same messages on my Android 5.1
Even the notification + data message fails for me. I have ensured that
(i) registerration of headlessjs is done correctly in index.js
(ii) bgMessage returns a promise
(iii) onMessage is defined in my component
(iv) an android channel is defined. 
(v) message  priority is set to high when sending it. 

None of them worked. 

I have not tried tinkering with the code in RNFirebaseMessagingService.java. 
Please help.

**Comment by sam9010** [comment]
plz check my error
https://stackoverflow.com/questions/58097745/how-to-fix-error-no-task-registered-for-key-rnfirebasebackgroundmessage-when-app

**Comment by prasanthsd** [comment]
The problem here is the push notification not being high on priority as said previously.

In our case we are using Twilio programmable chat and want to receive new chat messages when the app is in background. Twilio generates push messages for us and its not set to high priority. Thus we run into this issue and we cant change the priority either.

There may be others who run into the same issue. So maybe its worth fixing this lib with something like this posted above:

```
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        Notification notification = new Notification();
        startForeground(1, notification);
        startTask(taskConfig);
      } else {
        startTask(taskConfig);
      }
```

**Comment by mikehardy** [comment]
@prasanthsd I'm not sure how that will help the message launch the app if it isn't set to high priority before it hits the device. This seems like something that should be followed up with Twilio

**Comment by prasanthsd** [comment]
https://github.com/invertase/react-native-firebase/blob/d2a61f5e7f8c85d31c7af77d3132ece91ab7d6bb/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingReceiver.java#L50

@mikehardy When the app is not killed the above startService call works. If its killed and the incoming notification is not high priority then we will need to do something similar to this:

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
  context.startForegroundService(backgroundIntent);
} else {
  context.startService(backgroundIntent);
}
```

This actually worked in our test. Not sure if I'm missing something or if its considered a hack.

**Comment by mikehardy** [comment]
Oh! I see - you should turn on strict mode or watch the logs, I'm not sure startForegroundService is the recommended way but it might be a really good hack

https://developer.android.com/about/versions/oreo/background#services

you have 5 seconds to get things done basically, and if you do, then it should work?

The API keeps moving as the API increases, you need a permission in Android 9 https://developer.android.com/about/versions/pie/android-9.0-changes-28#fg-svc

**Comment by patrick-samy** [comment]
@prasanthsd Were you ever able to address this issue?

We're exactly in the same situation with Twilio not setting high priority for notifications:
```
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: Background messages only work if the message priority is set to 'high'
```

We're also getting a similar exception after:
```
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.span.app/io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService (has extras) }: app is in background uid UidRecord{1402daf u0a473 RCVR idle change:idle|uncached procs:1 seq(0,0,0)}
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1715)
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: 	at android.app.ContextImpl.startService(ContextImpl.java:1670)
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: 	at android.content.ContextWrapper.startService(ContextWrapper.java:720)
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: 	at android.content.ContextWrapper.startService(ContextWrapper.java:720)
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: 	at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingReceiver.onReceive(ReactNativeFirebaseMessagingReceiver.java:54)
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4032)
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: 	at android.app.ActivityThread.access$1400(ActivityThread.java:237)
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: 	at android.os.Looper.loop(Looper.java:223)
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: 	at java.lang.reflect.Method.invoke(Native Method)
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-06 17:43:54.561 22370 22370 E RNFirebaseMsgReceiver: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by prasanthsd** [comment]
I believe twilio has hooks. If my memory serves me right we wrote a back-end service which gets the push from twilio and we generate our own high priority notifications.

**Comment by AliGoherShabir** [comment]
> I've resolved the `Module AppRegistry is not a registered callable module (calling startHeadlessTask)` issue by putting my `AppRegistry.registerHeadlessTask(...)` code in index.js - I was not aware that it had to be here, doing this makes it work.
> 
> My above suggested fix to use `startForegroundService` does not work as I originally reported. The Android documentation states that the service started with `startForegroundService` "will call startForeground(int, android.app.Notification) once it begins running". Note that the second argument to this is a Notification. I've gotten around this by override `onStartCommand` of `RNFirebaseBackgroundMessagingService` with the following. But at this point its very much feeling like a hack as I deliberately pass a notification that does not have a channel so it won't display.
> 
> ```java
>   @Override
>   public int onStartCommand(Intent intent, int flags, int startId) {
>     HeadlessJsTaskConfig taskConfig = getTaskConfig(intent);
>     if (taskConfig != null) {
> 
>       if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
>         Notification notification = new Notification();
>         startForeground(1, notification);
>         startTask(taskConfig);
>       } else {
>         startTask(taskConfig);
>       }
> 
>       return START_REDELIVER_INTENT;
>     }
>     return START_NOT_STICKY;
>   }
> ```

Huge Thanks, I fixed my issue with a little tweak and here is my code:
`@Override
  public int onStartCommand(Intent intent, int flags, int startId) {
    HeadlessJsTaskConfig taskConfig = getTaskConfig(intent);
    if (taskConfig != null) {

      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {

        NotificationCompat.Builder builder = new NotificationCompat.Builder(this, createNotificationChannel("123", "notify_channel"));
        builder.setPriority(NotificationCompat.PRIORITY_MIN);

        startForeground(1, builder.build());
      }
      startTask(taskConfig);

      return START_REDELIVER_INTENT;
    }
    return START_NOT_STICKY;
  }

  @RequiresApi(Build.VERSION_CODES.O)
  private String createNotificationChannel(String channelId, String channelName){
    NotificationChannel chan = new NotificationChannel(channelId, channelName, NotificationManager.IMPORTANCE_NONE);
    chan.setLightColor(Color.BLUE);
    chan.setLockscreenVisibility(Notification.VISIBILITY_PRIVATE);
    NotificationManager service = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
    service.createNotificationChannel(chan);
    return channelId;
  }`
