### ISSUE TITLE
getServerTime returns an object with an invalid date

### ISSUE THREAD

**Issue by idlework** [invertase/react-native-firebase#910]
### Issue

For iOS when I request a server time with `getServerTime` it return an object with an `Invalid Date`. When I call `getServerTime` a second time it returns a correct date. The following code shows it: ```
console.log(typeof firebase.database().getServerTime() // shows: Invalid Date)
console.log(typeof firebase.database().getServerTime()) // shows: Mon Mar 26 2018 18:01:53 GMT+0200 (CEST)```

This is how it shows when tested on a iOS device, with an Android device it always return the `Invalid Date` object.

The `Invalid Date` object is probably generated by the Chrome console because it can't handle the object.

### Environment

Both

1. Application Target Platform:

macOS Sierra: 10.12.6 (16G1212)

2. Development Operating System:

iOS build has a minimum requirement of iOS 10

*Android build settings*
```
android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "2.0"
    }
}
```

3. Build Tools:

react-native command line

4. React Native version:

`"react-native": "0.51"`

5. RNFirebase Version:

`"react-native-firebase": "^3.3.1"`

6. Firebase Module:

*iOS libraries*
```
pod "FirebaseCore", "~> 4.0.15"
  pod "Firebase/Auth"
  pod "Firebase/Database"
  pod "Firebase/DynamicLinks"
  pod "Firebase/Firestore"
  pod "Firebase/Messaging"
  pod "Firebase/Storage"

  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'
```
*Android libraries*
```
compile "com.android.support:appcompat-v7:26.0.2"
    compile "com.facebook.react:react-native:+"
    compile "com.google.android.gms:play-services-base:11.8.0"
    compile "com.google.android.gms:play-services-auth:11.8.0"
    compile "com.google.android.gms:play-services-maps:11.8.0"
    compile "com.google.android.gms:play-services-gcm:11.8.0"
    compile "com.google.firebase:firebase-core:11.8.0"
    compile "com.google.firebase:firebase-analytics:11.8.0"
    compile "com.google.firebase:firebase-auth:11.8.0"
    compile "com.google.firebase:firebase-database:11.8.0"
    compile "com.google.firebase:firebase-firestore:11.8.0"
    compile "com.google.firebase:firebase-invites:11.8.0"
    compile "com.google.firebase:firebase-messaging:11.8.0"
```

**Comment by chrisbianca** [comment]
This has been fixed and will be included in the next v4 release
