### ISSUE TITLE
BUG: Firebase.auth.User.updateProfile cash with null values

### ISSUE THREAD

**Issue by aMarCruz** [invertase/react-native-firebase#911]
### Issue

From the Google [updateProfile](https://firebase.google.com/docs/reference/js/firebase.User#updateProfile) sample:

> // Passing a null value will delete the current attribute's value, but not
// passing a property won't change the current attribute's value:
// Let's say we're using the same user than before, after the update.

react-native-firebase will crash with this:
```js
const user = firebase.auth().currentUser
if (user && user.photoURL) {
    user.updateProfile({ photoURL: null })
}
```
This is in RNFirebaseAuth.java when trying Uri.parse:

![image](https://user-images.githubusercontent.com/6636980/37922239-44caf1aa-30e9-11e8-81e0-b2be46804176.png)

### Environment

1. Application Target Platform:

Device: Android 7.0 (Samsung S7 Edge)
targetSdk 26

2. Development Operating System:

Linux Mint 18.3
VS Code v1.21.1

3. Build Tools: 27.0.3

4. React Native version: 0.53.3

5. RNFirebase Version: 3.3.1

6. Firebase Module: Auth

Thanks in advance!

BTW: I :heart: RNF

**Comment by chrisbianca** [comment]
This has been fixed in https://github.com/invertase/react-native-firebase/commit/9f9a3da5af82eecf2af8ac18b97694f3cc080f26 which will be incorporated into the next v4 release.
