### ISSUE TITLE
Error:Execution failed for task ':app:processDebugGoogleServices'. > File google-services.json is missing. The Google Services Plugin cannot function without it.    

### ISSUE THREAD

**Issue by harikrishnanssomdev** [invertase/react-native-firebase#918]
im on a problem now which shows the google-services.json is missing in android/app folder, but i downloaded it from my firebase console and placed the file in app folder of my project still it didn't work, it searches the location but didn't recognise the file google-services.json that i have put in

**Comment by chrisbianca** [comment]
Closing this as I assume it's fixed based on the fact you're opening other issues.
Please make sure you close issues once you've resolved them.
