### ISSUE TITLE
error ios on 4.0.0-rc.3

### ISSUE THREAD

**Issue by sibelius** [invertase/react-native-firebase#921]
node_modules/react-native-firebase/ios/RNFirebase/firestore/RNFirebaseFirestore.m:209:16: no visible @interface for 'FIRFirestore' declares the selector 'enableNetworkWithCompletion:'

**Comment by chrisbianca** [comment]
@sibelius Run `pod update`, you need to be on iOS pods v4.11.0+

**Comment by sibelius** [comment]
not using `pod`, gonna upgrade native sdk

tks

**Comment by chrisbianca** [comment]
Here-in lies the benefits of pods ;)

**Comment by sibelius** [comment]
am I missing anything here 

> #import "RNFirebaseMessaging.h"

> AppDelegate.m:74:24: no known class method for selector 'didReceiveLocalNotification:'

>   [RNFirebaseMessaging didReceiveLocalNotification:notification];

**Comment by sibelius** [comment]
found it https://rnfirebase.io/docs/master/notifications/ios, tks
