### ISSUE TITLE
displayNotification is not available

### ISSUE THREAD

**Issue by giladno** [invertase/react-native-firebase#925]
```
import Firebase from 'react-native-firebase';

Firebase.messaging().displayNotification(...);
Firebase.notifications().displayNotification(...);
```

`Firebase.notifications` is not available and there is no `displayNotification` available under `Firebase.messaging()`. What is the proper way to display a notification from within the app?

**Comment by chrisbianca** [comment]
@giladno which version of the library have you installed?  Sounds like you've installed v3, but are following the v4 docs.

v4 messaging / notifications is much more stable.  You can install using the following:

`npm install --save react-native-firebase@next`

**Comment by giladno** [comment]
@chrisbianca thanks. I have the latest official one (3.3.1), I was under the impression v4 is still in beta. Is it stable enough to use?

**Comment by chrisbianca** [comment]
v4 has had more testing done on it than any release we've done previously, particularly with regards to messaging and notifications.  I'd highly recommend going with v4, and if all goes well, we'll be doing a final release some time next week...

**Comment by giladno** [comment]
Is there any migration guide available? I couldn't find any. Or should it work as-is out of the box? (hopefully :) )

**Comment by chrisbianca** [comment]
Check out the release notes: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-rc.3
