### ISSUE TITLE
ANDROID Build Fail 4.0.0-rc3

### ISSUE THREAD

**Issue by GroupXTech** [invertase/react-native-firebase#926]
Changing to com.android.tools.build:gradle:3.1.0 completely disrupts the rest of my project packages because they aren't updated using the latest android changes. 
I understand we are at the mercy of android here. 
Is there some kind of work around to use this lastest update without updating to tools.build:gradle:3.1.0?
If no, let me know and feel free to close the issue.

Thanks

**Comment by chrisbianca** [comment]
Do you mind me asking what sort of issues you’re having with other packages as a result of the upgrade to 3.1.0?

From our point of view, we’ll obviously do our best to support what we can, but it’s tricky to do that when things around us change which make it hard to maintain forwards and backwards compatibility.

**Comment by chrisbianca** [comment]
Without any further information, it's hard to know how to help.  We've addressed some Android issues which will be noted as part of the v4 release later today.

Please re-open with more information if you're still having issues with the full release.

**Comment by GroupXTech** [comment]
Hey there,
Just an update, I went back and installed 4.0.1 and got it to build successfully. I think my problem was that I clicked in to each Warning to update each node package and this time I ignored the warnings.

Thanks again for your commitment to this package.

Cheers,
Jim
