### ISSUE TITLE
admob not work !! 

### ISSUE THREAD

**Issue by bhram** [invertase/react-native-firebase#927]
### Issue

hi , why admob model not work ? 
and it's commit out in 
![screenshot_1](https://user-images.githubusercontent.com/6893953/38164862-9e7226b4-3513-11e8-8645-cb2fb226d054.png)

### Environment
Android

1. Application Target Platform:

windows 10

2. Development Operating System:

Android Studio 3.0

3. Build Tools:

0.45.1

4. React Native version:

0.54.2

5. RNFirebase Version:

3.3.0

6. Firebase Module:

Admob

**Comment by chrisbianca** [comment]
Please see: https://github.com/invertase/react-native-firebase/issues/865
