### ISSUE TITLE
local notification with 3.2.0

### ISSUE THREAD

**Issue by amitbravo** [invertase/react-native-firebase#928]
Just wondering if local notification working perfectly with 3.2.0 or 3.3.0 , I do not want to go with 4.xx right now , as I am having lot of android build problem with 4.0.0xxx.

**Comment by chrisbianca** [comment]
@amitbravo local notifications certainly do work on 3.2.0 and 3.3.0 but don't offer the same feature set, or stability that is offered in 4.0.0.

Do you mind me asking what sort of build problems you're having with 4.0.0?

**Comment by chrisbianca** [comment]
Btw, I'm closing this as it's not really an issue.
