### ISSUE TITLE
firestore crashing query big file

### ISSUE THREAD

**Issue by vinipachecov** [invertase/react-native-firebase#929]
### Issue
Hi there, I recently changed my database from real time database to Firestore and also changed web sdk to react-native-firebase. My app needs to save some huge entries, something I'm still thinking the best approach. Since I need to store 2k ~40k entries (each sale in my app will be stored as an entry in the db), I tried first to save the sales as a separated document.
Then when I tried to fetch the app crashed. Now I was trying the opposite and it lags and sooner or later it crashes because of this error when I try to fetch the big document( between 2k ~40k { objects }):

![image](https://user-images.githubusercontent.com/2838834/38209368-87e8fc42-368a-11e8-86a8-c04dae1ee65c.png)

### Environment

1. Application Target Platform:
Android 5.x+
2. Development Operating System:
Deepin Linux 15.5 (debian based)
3. Build Tools:

4. React Native version:

0.52

5. RNFirebase Version:
3.3.1

6. Firebase Module:
    compile "com.google.android.gms:play-services-base:11.8.0"
    compile "com.google.firebase:firebase-firestore:11.8.0"
    compile "com.google.firebase:firebase-auth:11.8.0"
    compile "com.google.firebase:firebase-database:11.8.0"

![code](https://user-images.githubusercontent.com/2838834/38210306-6d7cfde2-368d-11e8-9d29-00b91a27aeee.png)

All I'm doing is testing how much Firestore handles when the test include a big document. I've searched the error that java is throwing and It looks like that the cursor cannot handle such a big query.
By the way, the code sample is been tested by first inserting the document and in a second run the reading of it. 
The wierd part is that it works once or twice, lagging the whole app, and after that even if I try to get a simple small document the app throws the same error and crashes.

**Comment by chrisbianca** [comment]
@vinipachecov Sorry to say that this is something you're going to have to take up with Firebase directly as the error is being reported inside the native SDK and not our library.

One thing to bear in mind - your data structure does not suit Firestore, you should look at sub-collections to store the attendees, sales and products, rather than trying to have this within a single document.
