### ISSUE TITLE
Catch Network Error when read in Real Time Database

### ISSUE THREAD

**Issue by AlexandreMaistret** [invertase/react-native-firebase#930]
### Issue

I have made a function to read some data in my realtime database in firebase. It works perfectly, but when I disconnect the network on the device, I don't catch any error, the firebase function just stay stuck.

```
try {
        const value = await firebase.database().ref('/users/usernames/'+username+'/').once('value');
        if (value.val()) {
                  return value.val();
         }
} catch (err) {
        console.log(err)
}
```

### Environment

react-native : 0.51.0
react-native-firebase: 3.2.4

**Comment by chrisbianca** [comment]
You can listen to the state of the connection by following the instructions here: https://firebase.google.com/docs/database/web/offline-capabilities#section-connection-state

I've made a note that we need to add some docs to RNFirebase itself.
