### ISSUE TITLE
RNFirebaseMessaging in AppDelegate.o Symbol not found

### ISSUE THREAD

**Issue by hajjiTarik** [invertase/react-native-firebase#931]
Hey,

Environment:

Target Platform:
iOS (iOS 11.3 - iPhone 8)
Development Operating System:
macOS Sierra
Build tools: Xcode
 "react-native": "0.53.3",
 "react-native-firebase": "^3.3.1",

I already done and redone react-native link react-native-firebase and unlink.
I deleted the derived data folder several times.
clean, and restart xcode several times.
I also uninstall react-native-firebase.

Note :

when I import
#import "RNFirebaseMessaging.h"
I have no problem.
it is when I use the following functions that build failed :

> -(void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
>   [RNFirebaseMessaging didReceiveLocalNotification:notification];
> }
> 
> - (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo {
>   [RNFirebaseMessaging didReceiveRemoteNotification:userInfo];
> }
> 
> ...

<img width="926" alt="sans titre" src="https://user-images.githubusercontent.com/16863562/38223253-e12e4224-36e1-11e8-9f8e-fcfd4a7bf271.png">

**Comment by andr3a88** [comment]
Reported the same issue

**Comment by chrisbianca** [comment]
A couple of things:

1) I'd suggest updating to v4 for all notifications functionality
2) It sounds like your Xcode workspace is getting itself in a mess. Follow the instructions here: https://rnfirebase.io/docs/v4.0.x/troubleshooting/ios#Duplicate-Symbols-/-Undefined-Symbols-(build-time-error)

**Comment by andr3a88** [comment]
I've already update to RNFirebase v4 and clean the project but the problem still remaining

**Comment by chrisbianca** [comment]
@andr3a88 It's not just a clean - you need to follow all the steps in the linked issue.
