### ISSUE TITLE
Offline mode: signInWithEmailAndPassword throws 'auth/unknown' error code instead of 'auth/network-request-failed'

### ISSUE THREAD

**Issue by vasyl-kovalchuk** [invertase/react-native-firebase#934]
Hi!
I have an issue with handling of auth failure code. I expect to get error 'auth/network-request-failed' that is described in a docs([Common Error Codes](https://rnfirebase.io/docs/v3.3.x/auth/reference/Error#Common-Error-Codes)) but instead of that I got code 'auth/unknown'. 

### Environment
Android SDK: 25
react-native-firebase: 3.3.1
RNFirebase 11.0.8( (database, auth)

**Comment by chrisbianca** [comment]
Thanks for the report, we'll investigate

**Comment by juanpaternina** [comment]
+1

**Comment by Salakar** [comment]
@vasyl-kovalchuk @juanpaternina just pushed up something that should hopefully handle this - the Android SDK seems to now returning grpc errors in some cases as well as AuthExceptions. So the code extracting regex needed a tweak.

**Comment by rikur** [comment]
I'm still getting auth/unknown for some Android auth errors. I'm expecting a 'auth/credential-already-in-use' error, but receive this instead:

```
code: auth/unknown
message: User has already been linked to the given provider.
```

**Comment by EhsanSarshar** [comment]
I also have same problem. auth/unknow
but when I extract the .catch() function and convert it to a "await try catch block". and after I log the error in catch block it says. API key not valid. even I tried to redownload google-service.json but still the same error

**Comment by denisk20** [comment]
Still getting this on a physical device (*not* on emulator) with 5.5.6.

**Comment by mikehardy** [comment]
@denisk20 Hmm - can you open a fresh issue following the issue template? In particular the code doing the auth? This bug is old enough from inception that I'm not sure on versions of anything
