### ISSUE TITLE
[proposal] firebase.functions() 

### ISSUE THREAD

**Issue by Salakar** [invertase/react-native-firebase#935]
This issue is to discuss the newly released functions API, possible API implementation spec for RNFirebase and track interest.

Announcement: https://firebase.googleblog.com/2018/04/launching-cloud-functions-for-firebase-1-0.html?m=1

 SDK Guide: https://firebase.google.com/docs/functions/callable?utm_source=blog&utm_medium=blog&utm_campaign=cloud_functions_v1.0

**Comment by jeveloper** [comment]
This is a nice feature to utilize. 
I thought it was already possible by just using Google Cloud Functions by heading Header with auth.

Curious if you're planning on implementing using native SDK (http client with java and swift/objective c) or just high level Fetch

**Comment by Salakar** [comment]
@jeveloper we did briefly internally discus the possibility of using fetch in JS but we're gonna stick with using the native SDK's rather than rolling our own.

Re the headers, you're correct, that is how it works pretty much, requires the authentication token and the instance id token to work, see: https://github.com/firebase/firebase-js-sdk/blob/master/packages/functions/src/context.ts#L70

**Comment by jeveloper** [comment]
Thanks for using native code, should be more performant :)

**Comment by asadighi** [comment]
@Salakar is it possible to have a hack-around to be able to call functions in rnfirebase until the support is added?

**Comment by chrisbianca** [comment]
@asadighi if you want a hack-around, then it's something you'll have to implement yourself I'm afraid. We'll release a proper implementation in due course.

**Comment by Salakar** [comment]
All - have started implementing this on the `functions` branch: https://github.com/invertase/react-native-firebase/tree/functions

**Comment by Salakar** [comment]
@jeveloper @asadighi and others, I have just submitted the PR for this 🎉  https://github.com/invertase/react-native-firebase/pull/1056

Closing this issue. Hoping to land the PR as part of v4.1. Testers are welcome to try out the functions branch or the above PR.
