### ISSUE TITLE
RCTEventDispatcher.h file not found on React Native 0.44

### ISSUE THREAD

**Issue by arminsal1** [invertase/react-native-firebase#94]
I upgraded to React Native 0.44 today and now I'm getting this error for the RNFirebase Pod.

Here's a screenshot:
<img width="1158" alt="screen shot 2017-05-07 at 12 21 21 pm" src="https://cloud.githubusercontent.com/assets/8769537/25782838/c51e12ec-331f-11e7-90da-3f75e8eea43b.png">

I'm guessing the React team made some change that's causing this but idk what to do about it

UPDATE: I just ran "pod update --verbose" and the error went away. I'm dealing with other library errors at the moment so I'll reopen the issue if it comes back

UPDATE 2: After messing around and reinstalling, the issue is now with `#import "RCTBridgeModule.h"`

**Comment by arminsal1** [comment]
Yeah it's showing up again

**Comment by arminsal1** [comment]
Added the RNFirebase Framework to "Link Binary with Libraries" in Build Phases, and I think the issue will be gone for good

**Comment by arminsal1** [comment]
Aaaand it's back. I'm just gonna leave this open.

**Comment by metalmalte** [comment]
Still facing the same issue, even when adding RNFirebase to the app's Libraries

**Comment by metalmalte** [comment]
Any idea on how to solve it?

**Comment by arminsal1** [comment]
@metalmalte We're currently trying to figure it out over at this new issue I opened #95

**Comment by hchen1202** [comment]
Still facing the same issue, after tried  "pod update --verbose"  and  adding libRNFirebase.a to the app's Libraries, still get it.

**Comment by parkerproject** [comment]
Same issue here.
