### ISSUE TITLE
After configure, It is not showing push notification settings or anything ? 

### ISSUE THREAD

**Issue by isurugajasinghe** [invertase/react-native-firebase#941]
only can see this two only. no any push notification active row .

<img width="349" alt="screen shot 2018-04-06 at 10 53 39 pm" src="https://user-images.githubusercontent.com/23732707/38434814-606ea462-39ed-11e8-9c66-c5d2e5d10c9b.png">

#import "RNFIRMessaging.h"
// add before return YES;
  [FIRApp configure];
  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
  
// add before @end
- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler
{
  [RNFIRMessaging willPresentNotification:notification withCompletionHandler:completionHandler];
 }

- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler
{
     [RNFIRMessaging didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
   [RNFIRMessaging didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

**Comment by IljaDaderko** [comment]
@isurugajasinghe did you prompt user to enable push notifications from your app?

https://rnfirebase.io/docs/v4.0.x/notifications/receiving-notifications

After user grants access (iOS) you will see notification option in that menu like with any other apps.
You also need to ensure you enabled this feature in XCode, just in case you forgot, as placing that code snippet in AppDelegte is not enough.

I'd also suggest watching firebase's videos on this, they go in depth about all details associated to notifications

1) Generating notification certificates in developer portal and adding them to firebase
2) Setting everything up in XCode (notifications)

etc...

**Comment by chrisbianca** [comment]
Thanks @IljaDaderko for explaining this, closing.
