### ISSUE TITLE
Cannot display a notification while in background (iOS)

### ISSUE THREAD

**Issue by giladno** [invertase/react-native-firebase#942]
I'm sending a data only push message with `content-available`. This works great on Android, but not on iOS. My client does receive the message while in the background (I can see the `onMessage` callback in my traces), but when I try to display an alert (while my app is still in the background) - it shows nothing.

```
import Firebase from 'react-native-firebase';

export default data=>{
    const notification = new Firebase.notifications.Notification();
    notification.setTitle(data.author);
    notification.setBody(data.title);
    notification.setNotificationId(`id_${Date.now()}`);
    notification.setData(data);
    notification.android.setChannelId('inbox');
    notification.android.setSmallIcon('ic_launcher');
    notification.android.setAutoCancel(true);
    notification.android.setPriority(Firebase.notifications.Android.Priority.Max);
    Firebase.notifications().displayNotification(notification);
};
```

**Comment by chrisbianca** [comment]
@giladno I'm afraid that with iOS, whilst `content-available` will open the app in the background, it doesn't always allow data to pass over the bridge.  This is an iOS restriction and there are 2 ways to work around it:

1) For iOS, use the `notification` part of FCM to display the notification whilst the app is in the background (the new FCM sending API is much more flexible)
2) Write some native code to intercept the message and display it in the background (not recommended)
