### ISSUE TITLE
firebase.auth().onAuthStateChanged error handling

### ISSUE THREAD

**Issue by darrenchiu** [invertase/react-native-firebase#944]
Hi, not sure if i missed something, but it seems that the `firebase.auth().onAuthStateChanged` api is missing out the error handling api parameter for passing in an error handling function. Is that on the roadmap?

Thanks a lot.

**Comment by chrisbianca** [comment]
@darrenchiu you're right, this is an oversight on our part. We'll get this added in a future version, thanks for the report.

**Comment by Salakar** [comment]
@darrenchiu hey, not forgotten about this - I took a stab at it earlier this week and going through it all I'd like to move this to the v6 release as there's a few internal changes that need doing for this to be supported - so would prefer to semver major it just incase.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
Closing as tracking on https://github.com/invertase/react-native-firebase/pull/2107 - thanks.
