### ISSUE TITLE
RNFirebase - Argument list too long recursive header expansion failed

### ISSUE THREAD

**Issue by juniorneo2** [invertase/react-native-firebase#947]
Hi, I am not able to build my project in the IOS version, this error occurs and I do not know what to do, I configured it according to the manual. In the Android version is working the notification push already in IOS does not go up. This error occurs:

`Argument list too long: recursive header expansion failed at /Users/myfolder/Documents/work/reactnative/myproject/node_modules/react-native-firebase/ios/../../../ios/Pods/React/node_modules/react-tools/src/renderers/dom/client/__tests__.
`
PodFile:
```
platform :ios, '9.0'

use_frameworks!
target 'Siclope' do
  target 'Siclope-tvOSTests' do
    inherit! :search_paths
    pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker'
    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  end

  target 'SiclopeTests' do
    inherit! :search_paths
  end

  pod 'SwiftyJSON', '3.1.4'
  pod 'Charts', '3.0.3'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
end
post_install do |installer|
	installer.pods_project.targets.each do |target|
	  target.build_configurations.each do |config|
	    config.build_settings['SWIFT_VERSION'] = '3.0'
	  end
	end
end
```

Environment
Application Target Platform:
iOS

Development Operating System:
Mac OS High Sierra

Build Tools:
command line
XCode 9.2

React Native version:
react-native-cli: 2.0.1

RNFirebase Version:
"react-native-firebase": "^3.3.1",

Does anyone know what can it be?

Thank you!

**Comment by chrisbianca** [comment]
@juniorneo2 This has been fixed in v4.0.0
