### ISSUE TITLE
Clear existing notifications

### ISSUE THREAD

**Issue by judemanutd** [invertase/react-native-firebase#948]
### Issue
No way to clear any existing notifications.

### Environment 
Both

1. Application Target Platform:
Windows 10

2. Development Operating System:
iOS and Android

3. Build Tools:
27.0.3

4. React Native version:
0.54.3

5. RNFirebase Version:
4.0.0

6. Firebase Module:
Firebase notifications

**Comment by chrisbianca** [comment]
Assuming this is a delivered notification, you can use `firebase.notifications().removeDeliveredNotification(notificationId)` or `firebase.notifications().removeAllDeliveredNotifications()`.  If it's a scheduled notification, you can use `firebase.notifications().cancelNotification(notificationId)` or `firebase.notifications().cancelAllNotifications()`.

All this is documented at: https://rnfirebase.io/docs/v4.0.x/notifications/reference/Notifications

**Comment by judemanutd** [comment]
@chrisbianca Thank you, I seem to have missed that

**Comment by LorandP** [comment]
> Assuming this is a delivered notification, you can use `firebase.notifications().removeDeliveredNotification(notificationId)` or `firebase.notifications().removeAllDeliveredNotifications()`. If it's a scheduled notification, you can use `firebase.notifications().cancelNotification(notificationId)` or `firebase.notifications().cancelAllNotifications()`.
> 
> All this is documented at: https://rnfirebase.io/docs/v4.0.x/notifications/reference/Notifications

`firebase.notifications().removeDeliveredNotification(notificationId)` is not working for me on react-native: 0.57.7 and firebase 4.3.8

**Comment by agmcleod** [comment]
Also seem to be having this issue.

react-native: 0.57.7
react-native-firebase: 5.2.2

I don't see any particular notes about this feature in the changelog since 5.2.2. Is this something known to be fixed?

**Comment by Aashir1** [comment]
> Also seem to be having this issue.
> 
> react-native: 0.57.7
> react-native-firebase: 5.2.2
> 
> I don't see any particular notes about this feature in the changelog since 5.2.2. Is this something known to be fixed?

Hi @agmcleod I was also facing the same issue I solved this issue by adding this line 
`firebase.notifications().cancelNotification(notifcationPayload.notification._notificationId)`.

react-native : 0.60.5
react-native-firebase: 5.5.6

**Comment by aravi365** [comment]
Any way to clear remote notifications in react native firebase v6???

**Comment by mikehardy** [comment]
@aravi365 I was clear in my answer on #3563 I think.
Integrate a package that handles local device notification APIs
