### ISSUE TITLE
Illegal callback invocation from native module.

### ISSUE THREAD

**Issue by huybq95** [invertase/react-native-firebase#951]
[https://drive.google.com/file/d/104F0LT4dbVRkuA0CvHOKVvWdg6pX2pgl/view](url)

package.json:
"react-native-firebase": "2.2.3",
"react-native-fcm": "10.0.3",
"react-native": "0.47.2"

**Comment by Ehesp** [comment]
Link doesn't work, please put your code/screenshot on here.

**Comment by Salakar** [comment]
Please re-file this issue with the issue template filled out.

**Comment by huybq95** [comment]
Sorry for my bad, here my screenshot
![img_0604](https://user-images.githubusercontent.com/26105254/38532166-ba45b496-3c9d-11e8-8096-7ba45bc88e48.PNG)

**Comment by chrisbianca** [comment]
@huybq95 this looks like an issue that we resolved as part of the v3 release.  I'd strongly recommend updating to the latest version, which is now v4.  We no longer actively support v2.x
