### ISSUE TITLE
App crashes when notifications are received in background mode on iOS9

### ISSUE THREAD

**Issue by todorone** [invertase/react-native-firebase#952]
### Issue

On iOS, when app receives push notifications in foreground mode, everything is ok. When app receives push notifications in background mode, it crashes. Screenshot is attached, probably it's due to iOS9 issue?

![screen shot 2018-04-09 at 12 29 02 pm](https://user-images.githubusercontent.com/423701/38490644-4ebc812e-3bf2-11e8-99d9-4fbfb53ae6a0.png)

### Environment

1. Application Target Platform: iOS 9

2. Development Operating System: MacOS

3. Build Tools: XCode 9

4. React Native version: 0.54.4

5. RNFirebase Version: 4.0.0

6. Firebase Module:

**Comment by chrisbianca** [comment]
@todorone Thanks for flagging this, I've pushed up a fix which will be released as part of v4.0.1 later today.

**Comment by chrisbianca** [comment]
v4.0.1 is out now: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.1
