### ISSUE TITLE
Ads causing app instability and crashes in production

### ISSUE THREAD

**Issue by lwansbrough** [invertase/react-native-firebase#953]
### Environment

1. Application Target Platform:
- iOS, all versions, all phone models, sporadic (impacting ~10% of users)

2. Development Operating System:
macOS High Sierra

3. Build Tools:
XCode

4. React Native version:

React Native 0.55

5. RNFirebase Version:

3.3.1

6. Firebase Module:

Admob

Screenshots from our crash log:

<img width="787" alt="screen shot 2018-04-09 at 12 07 53 pm" src="https://user-images.githubusercontent.com/186674/38517542-2b7bb3f4-3bef-11e8-9509-5a58ae7cb2c3.png">
<img width="849" alt="screen shot 2018-04-09 at 12 07 10 pm" src="https://user-images.githubusercontent.com/186674/38517543-2b92d37c-3bef-11e8-999d-d21c4c70c8ac.png">

**Comment by batical** [comment]
#437

**Comment by lwansbrough** [comment]
@batical Thanks. A notice would be good to have somewhere I suppose.

**Comment by Salakar** [comment]
Thanks for reporting this issue. We're aware that AdMob has fallen behind on React Native Firebase and would like to bring it up to speed again. I will close this issue for now and track it as well as other issues collectively over on the `AdMob overhaul proposal` to be addressed in a future release. See #1259
