### ISSUE TITLE
Receive intent extras on notification open

### ISSUE THREAD

**Issue by judemanutd** [invertase/react-native-firebase#954]
### Issue

I want to be able to set some data for the notification so that when the notification is clicked to open an activity, I can get this data and process it. I am not sure how to receive this data once it has been set.
This is the code I am currently using.

```
 let notification = new firebase.notifications.Notification()
        .setNotificationId(JSON.stringify(NOTIFICATION_ID))
        .setTitle(notifTitle)
        .setBody(`You have ${notifCount} new alerts`)
        .setData({
            key1: 'value1',
            key2: 'value2',
        });
```
I have tried receiving the notification open using `getInitialNotification` but that doesn't seem to be triggered.

```
firebase.notifications()
            .getInitialNotification()
            .then((val) => {
                console.log("getInitialNotification  =" + JSON.stringify(val));
            }).catch((err) => {
            console.log("Error getInitialNotification  =" + JSON.stringify(err));
        }).finally(() => {
            console.log("finally getInitialNotification");
        });
```

### Environment

1. Application Target Platform: Android

2. Development Operating System: Windows 10

3. Build Tools: Android SDK 27.0.3

4. React Native version: 0.54.3

5. RNFirebase Version: 4.0.0

6. Firebase Module: Firebase Notification, Firebase Cloud Messaging

**Comment by judemanutd** [comment]
Issue resolved using 

```
firebase.notifications().onNotificationOpened((notificationOpen) => {
            console.log(notificationOpen.notification.data);
        });
```

Is there any other code that needs to be added along with this? An unsubscribe?

**Comment by judemanutd** [comment]
Issue resolved using 

```
firebase.notifications().onNotificationOpened((notificationOpen) => {
            console.log(notificationOpen.notification.data);
        });
```

Is there any other code that needs to be added along with this? An unsubscribe?

**Comment by chrisbianca** [comment]
`onNotificationOpened` returns a function which can be used to unsubscribe. I'd recommend adding this to `componentWillUnmount()`
