### ISSUE TITLE
How to link user to twitter in react-native-firebase? getting error "new TwitterAuthProvider() is not supported on the native Firebase SDKs"

### ISSUE THREAD

**Issue by juanlet** [invertase/react-native-firebase#958]
Hey, I did a web version and I could link a user to twitter with the press of a button using the method firebase.auth().currentUser.linkWithPopup(new firebase.auth.TwitterAuthProvider()), getting warning "new TwitterAuthProvider() is not supported on the native Firebase SDKs" ....how do I do that with react-native-firebase??. I can't find it anywhere...maybe I can install raw firebase at the side of this library and do it with the raw library???

**Comment by chrisbianca** [comment]
@juanlet I'm afraid this just isn't how React Native works.  The Native SDKs don't offer anything like this functionality, so you'll have to make use of a third party library to do the Twitter login and then manually link using the RNFirebase library.  Examples for this exist for Facebook and Google here: https://rnfirebase.io/docs/v4.0.x/auth/social-auth

**Comment by juanlet** [comment]
ok, but you think that if I use the twitter sdk for react native and then firebase.auth.TwitterAuthProvider.credential method will work like it works on facebook or that property doesnt exist?

**Comment by chrisbianca** [comment]
firebase.auth.TwitterAuthProvider does exist

**Comment by juanlet** [comment]
@chrisbianca  do you know any npm package that has the flow to the detect if twitter is installed and fallback to web like the one on the link your provided for facebook? It would be very helpful

**Comment by juanlet** [comment]
If it's good for anyone...I found this one that seems to be the most popular....  https://github.com/GoldenOwlAsia/react-native-twitter-signin

**Comment by juanlet** [comment]
@chrisbianca  excuse me that I'm insisting on this. I did as you said. I got the user's tokens with reac-native-twitter-signin...Which method should I use for TwitterAuthProvider to turn the two user's tokens(auth token and auth token secret) https://github.com/GoldenOwlAsia/react-native-twitter-signin/blob/master/Example/TwitterButton.js    into a credential that I can send to the method credential on TwitterAuthProvider?? the facebook example takes only one parameter since facebook only has 1 value, accessToken, how do I do when I have two values like in the case of twitter?

**Comment by juanlet** [comment]
I could do it with the mentioned package.....I will leave the code for those who come after me using the react-native-twitter-signin.....

```
import firebase from 'react-native-firebase';
//twitter login
import {
  NativeModules
} from 'react-native';
const { RNTwitterSignIn } = NativeModules;
const config = {
        consumer_key: "pHYkfW3tVK7rPNkfWx64J4quH",
        consumer_secret: "kuB9srCrGzjTf41BJFuMDDCkwotePjKUTL0eUIOBGJsruWuSS1"
    };

export const linkTwitterAccount = async ()=> {


RNTwitterSignIn.init(config.consumer_key, config.consumer_secret);

 let linkToTwitterResult;
 let twitterTokensObject;
 let loginData;
 //get credentials
 
 try{
  loginData = await RNTwitterSignIn.logIn();
  console.log("Twitter login data", loginData);
 }catch(err){
   console.log("Error with twitter login result",error);
 }

 //link to react native firebase

 try{

  const { authToken, authTokenSecret } = loginData;
  const user = firebase.auth().currentUser;
  // create a new firebase credential with the token
  const twitterCredential = firebase.auth.TwitterAuthProvider.credential(authToken,authTokenSecret);
 console.log(twitterCredential);

  // link to this account with credential
  const linkingResult = await user.linkAndRetrieveDataWithCredential(twitterCredential);
  console.log("Success Linking twitter",linkingResult);
}catch(err){
  console.log("Error linking account",err);
}

}
```

**Comment by chrisbianca** [comment]
@juanlet thanks for this, feel free to submit a PR to the main docs to add this example if you'd like?

I've removed your secret from the example...

**Comment by juanlet** [comment]
I will, thanks for your help

**Comment by quantumcept** [comment]
@juanlet any idea why I get an error saying

'Error linking account', { [TypeError: null is not an object (evaluating 'user.linkAndRetrieveDataWithCredential')]

**Comment by aj-4699** [comment]
> I could do it with the mentioned package.....I will leave the code for those who come after me. My solution is using the react-native-twitter-signin.....
> 
> ```
> import firebase from 'react-native-firebase';
> //twitter login
> import {
>   NativeModules
> } from 'react-native';
> const { RNTwitterSignIn } = NativeModules;
> const config = {
>         consumer_key: "YYYYYYYY",
>         consumer_secret: "ZZZZZZZ"
>     };
> 
> export const linkTwitterAccount = async ()=> {
> 
> 
> RNTwitterSignIn.init(config.consumer_key, config.consumer_secret);
> 
>  let linkToTwitterResult;
>  let twitterTokensObject;
>  let loginData;
>  //get credentials
>  
>  try{
>   loginData = await RNTwitterSignIn.logIn();
>   console.log("Twitter login data", loginData);
>  }catch(err){
>    console.log("Error with twitter login result",error);
>  }
> 
>  //link to react native firebase
> 
>  try{
> 
>   const { authToken, authTokenSecret } = loginData;
>   const user = firebase.auth().currentUser;
>   // create a new firebase credential with the token
>   const twitterCredential = firebase.auth.TwitterAuthProvider.credential(authToken,authTokenSecret);
>  console.log(twitterCredential);
> 
>   // link to this account with credential
>   const linkingResult = await user.linkAndRetrieveDataWithCredential(twitterCredential);
>   console.log("Success Linking twitter",linkingResult);
> }catch(err){
>   console.log("Error linking account",err);
> }
> 
> }
> ```

Could please guide on [Could not find com.twitter.sdk.android:twitter-core:3.3.0] error
