### ISSUE TITLE
Merge react-native-fcm?

### ISSUE THREAD

**Issue by chrisbianca** [invertase/react-native-firebase#959]
Hi @evollu, you commented a while back about merging react-native-fcm and react-native-firebase's messaging and notifications functionality.

I'm not sure if you've seen, but [we recently released v4.0.0](https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0) which overhauled messaging and notifications to address a large number of the issues that existed in our previous implementation.

This release covers the complete iOS and Android messaging / notifications API, has full documentation and is well tested.

I was wondering how you'd feel about starting to point people over to `react-native-firebase` to start consolidating the two libraries and save us all from duplicating work?

**Comment by evollu** [comment]
Hi @chrisbianca 

I'm willing to merge two libraries and I like your rich documentation.

I started react-native-fcm just like what you guys did: bridging the callbacks. However Firebase SDK has very limited features especially for Android. So people start needing banner, sound, large pictures, action buttons, recurring notification, and etc. So react-native-fcm now is a combination of Firebase SDK bridge and a local notification library. But I don't see any extra notification features in your documentation. 
Is it on your road map? 
Shall we migrate both? 
Or shall we find a way that let `react-native-firebase` handle everything Firebase and `react-native-fcm` becoming a local notification library?

**Comment by chrisbianca** [comment]
That's great @evollu 

As you found, it's very hard to separate FCM and notifications, so we have implemented support for local notifications as part of v4 as well.  What we have done though, is make a clean divide between data-only FCM messages and notification messages, as explained here: https://rnfirebase.io/docs/v4.0.x/messaging/introduction

You can find the documentation for notifications here:

Intro: https://rnfirebase.io/docs/v4.0.x/notifications/introduction
Receiving notifications: https://rnfirebase.io/docs/v4.0.x/notifications/receiving-notifications
Displaying notifications: https://rnfirebase.io/docs/v4.0.x/notifications/displaying-notifications
Scheduling notifications: https://rnfirebase.io/docs/v4.0.x/notifications/scheduling-notifications
Android notification channels: https://rnfirebase.io/docs/v4.0.x/notifications/android-channels

Complete reference docs: https://rnfirebase.io/docs/v4.0.x/notifications/reference/Notifications

We've tried to cover as much of the iOS and Android Notifications API as possible.  The only outstanding area is iOS categories, which is coded but still needs testing to confirm it's working correctly.

Let me know what you think of the above.

**Comment by evollu** [comment]
Looks great. I think we can merge.
It is missing recurring notification but I can contribute to it.
Let me try it out over the week.

Just curious, are you guys a company backing this repo?

**Comment by chrisbianca** [comment]
We do support recurring notifications, but looks like we forgot to add the documentation here: https://rnfirebase.io/docs/v4.0.x/notifications/reference/Schedule - I'll get that added tomorrow.

We started out building the library to support apps we were working on individually, but as the library usage has grown, we've set up a company to help back the ongoing development and accept Open Collective donations.  You can find out a bit more here: https://blog.invertase.io/keeping-react-native-firebase-awesome-8723470d2d26

**Comment by evollu** [comment]
I will try during weekend.

**Comment by evollu** [comment]
I tried local notification
questions: 
1. android actions: how do I know which action did you tap? Do you plan to support text action?
2. ios actions seem to be missing

**Comment by chrisbianca** [comment]
@evollu Sorry for the delay, I've been away the last week.

1. Android actions are already supported. The selected action is part of the `NotificationOpen` class: https://rnfirebase.io/docs/v4.0.x/notifications/reference/NotificationOpen along with text from any remote inputs
2. iOS actions is work in progress. They are coded, but weren't working when testing and need investigating: https://github.com/invertase/react-native-firebase/tree/ios-notification-categories
3. The headless task definitely works when the android app is killed - it might be that you have implemented it incorrectly.  You need to make sure that the headless task is registered at the top level of your app, alongside where you register your main component.
4. iOS doesn't support headless mode, so it's the standard JS callback you establish in `componentDidMount`

**Comment by evollu** [comment]
question on answer 4: componentDidMount doesn't get called when app is not running at all (say after system reboot).

**Comment by chrisbianca** [comment]
This may be related to: https://github.com/invertase/react-native-firebase/issues/971 which I'm looking at this week

**Comment by evollu** [comment]
I'm having https://github.com/evollu/react-native-fcm/tree/firebase/Examples/firebase-migration to test all functions I'm interested in. but I can't get my headless listener working. Can you take a look and see what's wrong?

**Comment by aminosman** [comment]
I am getting same error as @evollu. Notifications work fine when app is in foreground or background. When app is closed I get the same log message along with a notification saying my app has crashed. This was working a few days ago, not sure what changed in my app.

**Comment by aminosman** [comment]
Yes this is an older project (running latest RN) and it looks like thats what happened. I see others in the same boat. You are awesome! Thanks.

**Comment by chrisbianca** [comment]
Thanks for confirming!  I'm glad it's that and not a bug with a later version of React Native (which wouldn't be unheard of!!!)

I'll get a note added to the docs...

**Comment by chrisbianca** [comment]
Update: Added a note to the docs: https://rnfirebase.io/docs/v4.0.x/messaging/receiving-messages#4)-Check-%3Ccode%3EMainApplication.java%3C/code%3E

@evollu has that resolved your issue?

**Comment by evollu** [comment]
@chrisbianca yes problem solved. I'm using RN 0.48 btw

**Comment by chrisbianca** [comment]
@evollu great, glad that’s now resolved.

Is there anything else that concerns you about messaging and notifications is react-native-firebase?

If not, what’s the best way to move this forward? I notice you’ve already put a note on your repo which is great!

**Comment by evollu** [comment]
iOS actions and iOS handler when app is not running?

I will keep maintain the repo for existing users (bug fixes etc). But I will update the note to ask new users to check out your repo.
Does that sound good?

**Comment by chrisbianca** [comment]
Yep, both WIP and should be done in the next week or so.

That sounds like a good plan to me, thank you!

FYI - I noticed you have a note/PR about Android 26 Channel support on your repo. This is already supported in `react-native-firebase`.

**Comment by luizaugustocs** [comment]
@chrisbianca 
Any news on iOS actions?
