### ISSUE TITLE
Show Notification at foreground

### ISSUE THREAD

**Issue by KrisanuWeavers** [invertase/react-native-firebase#961]
How to Show Notification at foreground ? Please help

**Comment by Salakar** [comment]
You can call displayNotification on the notification received in your listeners if you want to display whilst the app is running:

https://rnfirebase.io/docs/v4.0.x/notifications/displaying-notifications#Display-the-notification

**Comment by ElangoPrince** [comment]
@Salakar , this **displayNotification**  listeners show's notification in foreground when the app is opened. else notification can't be show in foreground , shows only background. 
 how to fix this problem? any idea about this.
