### ISSUE TITLE
App crash when receive notification

### ISSUE THREAD

**Issue by ming436534** [invertase/react-native-firebase#963]
Issue

<img width="601" alt="screen shot 2018-04-11 at 2 11 59 pm" src="https://user-images.githubusercontent.com/15244626/38599268-5aa46672-3d92-11e8-9f90-14c887a2ae58.png">

My app crashed after receiving a notification. After some investigations, I found out that the alert variable in line 679 may not be NSDictionary, in may case, it is a string which is the title. And that will cause the for-in loop in line 680 to crash.  The notification is a simple one which only consist title and a key-value pair and was sent from the firebase notification console. For workaround I add a line of code to check if it is NSDictionary or not, but I don't know if it is a good solution.

**Environment**

1. Application Target Platform: iOS 8

2. Development Operating System: MacOS

3. Build Tools: XCode 9

4. React Native version: 0.54.2

5. RNFirebase Version: 4.0.1

6. Firebase Module:

**Comment by chrisbianca** [comment]
@ming436534 thanks for the report. We don't officially support iOS 8 any more as it makes up less than 0.2% of devices out in the wild.

However, this looks like something we might be able to address fairly easily.  Are you able to submit a PR with your dictionary check, or paste the code you're using here and I can look at getting it added to the next release?

**Comment by ming436534** [comment]
I opened a merge request for this issue, thank you!
