### ISSUE TITLE
is onAuthStateChanged()  supossed to be triggered after linking a social network to existing account?

### ISSUE THREAD

**Issue by juanlet** [invertase/react-native-firebase#965]
I linked twitter to an existing email/password account like I mention in this other issue  https://github.com/invertase/react-native-firebase/issues/958  .... The thing is that when the link is successful onAuthState doesn't execute. The listener works fine since it triggers when you login or logout, but not with linking accounts. I checked this using breakpoints with react-native-debugger. Should I perfomr the actions I want manually after linking success or  onAuthStateChanged is supossed to be triggered in those situations? Thank you very much.

**Comment by chrisbianca** [comment]
`onAuthStateChanged` does just that, fires when the auth state changes, i.e. login / logout
You'll need to take a look at https://rnfirebase.io/docs/v4.0.x/auth/reference/auth#onUserChanged.

In the future, these sorts of questions should be asked on StackOverflow or our Discord chat as they're not issues.
