### ISSUE TITLE
Notification title should be optional

### ISSUE THREAD

**Issue by jochem725** [invertase/react-native-firebase#967]
### Issue

Sending notifications without a title results in an error. I'm not sure if title should be a required parameter here since, if I'm correct, both iOS and Android do not display a title if it is not given.

Previous versions of react-native-firebase worked fine without a title set.

https://github.com/invertase/react-native-firebase/blob/master/lib/modules/notifications/Notification.js#L145

### Environment

1. Application Target Platform: Both

2. Development Operating System: macOS High Sierra

3. Build Tools: -

4. React Native version: 0.54.2

5. RNFirebase Version: 4.0.0

6. Firebase Module: Notifications

**Comment by chrisbianca** [comment]
@jochem725 Thanks for flagging this - I've checked and it looks like title and body are both optional fields on Android and iOS. I've just pushed up a fix that will land in v4.0.2.

**Comment by jochem725** [comment]
@chrisbianca Thanks 😄
