### ISSUE TITLE
Getting an abstract error on RNFirebaseAdMobRewardedVideo.java

### ISSUE THREAD

**Issue by udarts** [invertase/react-native-firebase#973]
Hi there,

I getting an error, which I hadn't before.

`main/java/io/invertase/firebase/admob/RNFirebaseAdMobRewardedVideo.java:17: error: RNFirebaseAdMobRewardedVideo is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener`

Any idea why this error is showing, it doesn't show up when syncing. It prevents me from building the apk.

**Comment by chrisbianca** [comment]
@udarts Please fill out the issue template next time.

My assumption is that you're on v3.3.x and you've updated your android dependencies to 12.0.x.

You'll need to update to RNFirebase v4.0.x to fix this issue.

**Comment by udarts** [comment]
Thanks, that was indeed the fix for this issue.
