### ISSUE TITLE
Attempted to use firebase module that's not installed on your android project- firebase.storage()

### ISSUE THREAD

**Issue by phuzarski** [invertase/react-native-firebase#977]
I have an error why I try call `**firebase.storage()**` anywhere in the app. What is more `firebase.auth()`, `firebase.database() `working fine.

I did gradlew clean, reinstalled all from package.json. Nothing help.

This bellow should be fine because auth and database work fine, but I paste it.

My build.gradle file
```
dependencies {
    compile project(':react-native-image-crop-picker')
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile project(':react-native-fetch-blob')
    compile project(':react-native-fbsdk')
    implementation project(':react-native-image-crop-picker')
    implementation project(':react-native-fbsdk')
    implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
    implementation project(':react-native-firebase')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:27.1.1"
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation(project(':react-native-firebase')) {
        transitive = false
    }

    implementation('com.crashlytics.sdk.android:crashlytics:2.9.1@aar') {
        transitive = true
    }

    implementation "com.google.android.gms:play-services-base:12.0.1"
    implementation "com.google.firebase:firebase-core:12.0.1"
    implementation "com.google.firebase:firebase-auth:12.0.1"
    implementation "com.google.firebase:firebase-database:12.0.1"

}
```
### Environment

ANDROID
1. Application Target Platform:
MacOS android studio emulator

2. Development Operating System:
Nexus 6 API 27

3. Build Tools:

4. React Native version:
"react-native": "0.54.1",

5. RNFirebase Version:
"react-native-firebase": "4.0.0",

**Comment by chrisbianca** [comment]
Please follow the installation instructions: https://rnfirebase.io/docs/v4.0.x/storage/android

You need to include the firebase-storage dependency in your build.gradle.

**Comment by phuzarski** [comment]
I added it as in instruction. Another error occured:

Java exception in 'NativeModules'
`
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/storage/StorageMetadata;`

**Comment by noumantahir** [comment]
I am having similar issue with messaging, I am not using pods with linked the framework manually

**Comment by meyonn** [comment]
I need you guys to help me solve this error please. I got stuck with this error in couple of week. can you guys help me please. my error is **Error: you attempted to use a firebase module that's not installed on your android project by calling firebase.auth()**. Is the above error same with this error?
Thank you.
![Screenshot_1553074894](https://user-images.githubusercontent.com/47807472/54674506-851c0000-4b37-11e9-8fa9-c6efba0fe9a2.png)

**Comment by alainib** [comment]
> 
> 
> I need you guys to help me solve this error please. I got stuck with this error in couple of week. can you guys help me please. my error is **Error: you attempted to use a firebase module that's not installed on your android project by calling firebase.auth()**. Is the above error same with this error?
> Thank you.
> ![Screenshot_1553074894](https://user-images.githubusercontent.com/47807472/54674506-851c0000-4b37-11e9-8fa9-c6efba0fe9a2.png)

stuck her too
i triple check the installation doc

**Comment by mikehardy** [comment]
I saw this once when I did not follow the installation doc.
In your android application java did you actually include/initialize things?

https://github.com/invertase/react-native-firebase-docs/blob/v5.x.x/docs/auth/android.md#install-the-rnfirebase-authentication-package

**Comment by fgagneten** [comment]
I solved the issue using:

    new RNFirebaseNotificationsPackage()

into my MainApplication.java

**Comment by Anuskhan** [comment]
app/build.gradle 
implementation "com.google.firebase:firebase-storage:15.0.2"

MainApplication.java

import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.auth.RNFirebaseAuthPackage; // <-- Add this line

public class MainApplication extends Application implements ReactApplication {
    // ...

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new RNFirebasePackage(),
          new RNFirebaseAuthPackage() // <-- Add this line
      );
    }
  };
  // ...
}

**Comment by Jahanzai6** [comment]
i am having an issue in reactnative auth and i tried everything above but didn't work for me

**Comment by Jahanzai6** [comment]
![Screenshot_1563990196](https://user-images.githubusercontent.com/45278880/61815831-ab530300-ae7d-11e9-81a3-ad7c03438279.png)


![Capture 2](https://user-images.githubusercontent.com/45278880/61816103-3f24cf00-ae7e-11e9-9d5a-b3a0d6db629e.PNG)
![Capture 1](https://user-images.githubusercontent.com/45278880/61816112-43e98300-ae7e-11e9-8cde-d4b8afd62871.PNG)


I am stuck on this error and unable to solve it for 2 weeks, Please help me. I even installed react-native-firebase-auth

**Comment by BilalS10** [comment]
Im facing the same issue as @Jahanzai6 .
Tried everything given on this thread.
Included the dependencies in build.gradle as well as the main.application.java.
But still showing the same error.
Can someone please help here

**Comment by Jahanzai6** [comment]
haven't find the solution yet

**Comment by snake-eye77** [comment]
i  have same issue

**Comment by Jahanzai6** [comment]
> i have same issue

I have found the solution,
if u r using react native version 0.60 then u have to add package in the MainApplication.java in following way.
packages.add( new RNFirebaseAuthPackage());

After adding this package if ur app is still not working then uninstall ur app from emulator and reinstall .....Then everything will work

**Comment by Jahanzai6** [comment]
> Im facing the same issue as @Jahanzai6 .
> Tried everything given on this thread.
> Included the dependencies in build.gradle as well as the main.application.java.
> But still showing the same error.
> Can someone please help here

I Found the solution, read my above comment.

**Comment by snake-eye77** [comment]
my react-native version is 0.59.8 and I have the same issue

**Comment by snake-eye77** [comment]
my react-native version 0.59.8 and I have sam issue

**Comment by snake-eye77** [comment]
> > Im facing the same issue as @Jahanzai6 .
> > Tried everything given on this thread.
> > Included the dependencies in build.gradle as well as the main.application.java.
> > But still showing the same error.
> > Can someone please help here
> 
> I Found the solution, read my above comment.

my react-native version is 0.59.8 and I have the same issue

**Comment by snake-eye77** [comment]
> > i have same issue
> 
> I have found the solution,
> if u r using react native version 0.60 then u have to add package in the MainApplication.java in following way.
> packages.add( new RNFirebaseAuthPackage());
> 
> After adding this package if ur app is still not working then uninstall ur app from emulator and reinstall .....Then everything will work

my react-native version is 0.59.8 and I have the same issue

**Comment by snake-eye77** [comment]
> > i have same issue
> 
> I have found the solution,
> if u r using react native version 0.60 then u have to add package in the MainApplication.java in following way.
> packages.add( new RNFirebaseAuthPackage());
> 
> After adding this package if ur app is still not working then uninstall ur app from emulator and reinstall .....Then everything will work

thanks it's very helpful for me @Jahanzai6

**Comment by mikehardy** [comment]
For react-native-firebase modules on RN59 follow the pattern here https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh

You can see what you have to do for each one in that script. You also have to add the pod in the Podfile for iOS of course

**Comment by bimix** [comment]
> > i have same issue
> 
> I have found the solution,
> if u r using react native version 0.60 then u have to add package in the MainApplication.java in following way.
> packages.add( new RNFirebaseAuthPackage());
> 
> After adding this package if ur app is still not working then uninstall ur app from emulator and reinstall .....Then everything will work

this is the right solution for whoever is using react-native 0.60+

**Comment by creativemind1** [comment]
> > i have same issue
> 
> I have found the solution,
> if u r using react native version 0.60 then u have to add package in the MainApplication.java in following way.
> packages.add( new RNFirebaseAuthPackage());
> 
> After adding this package if ur app is still not working then uninstall ur app from emulator and reinstall .....Then everything will work

After adding the above code, I got error as 

 packages.add( new RNFirebaseAuthPackage()),
```
            ^
  symbol:   variable packages
  location: class MainApplication
```

**Comment by mikehardy** [comment]
@creativemind1 - an infinite number of ways to go wrong, maybe try generating a throwaway example by cloning this repo and running this script (assuming you are trying react-native-firebase v5 + react-native 0.60+?): https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by creativemind1** [comment]
I'm using `"react-native-firebase": "~5.6.0", "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",`. I'm using `Expokit` and in iOS all is fine but just have trouble with android. I wanted to clone your repo but again I thought as I'm using Expokit there might be some glitch somewhere..

**Comment by SofticKabir** [comment]
> > i have same issue
> 
> I have found the solution, if u r using react native version 0.60 then u have to add package in the MainApplication.java in following way. packages.add( new RNFirebaseAuthPackage());
> 
> After adding this package if ur app is still not working then uninstall ur app from emulator and reinstall .....Then everything will work

I tried this but I am still getting the initial error...

**Comment by mikehardy** [comment]
There is no reason to add anything to anywhere anymore on android in react-native 0.60+ with auto-linking. Disregard any advice to manually link.

Please see this script (read it, read the comments) along with the rnfirebase.io install instructions for step by step walk through on how to integrate this properly from scratch: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by vikas6377297826** [comment]
i found a sam issue
solution: uninstall you app in emulator and rebuild.

**Comment by impaaras** [comment]
@Jahanzai6 

> > i have same issue
> 
> I have found the solution, if u r using react native version 0.60 then u have to add package in the MainApplication.java in following way. packages.add( new RNFirebaseAuthPackage());
> 
> After adding this package if ur app is still not working then uninstall ur app from emulator and reinstall .....Then everything will work
@Jahanzai6  I working using Expo go app so what i should do, as I am not on Emulator. please help me to solve this error

**Comment by codexjoshy** [comment]
@Jahanzai6 i'm having same issue with expo, found any solution to it yet ?

**Comment by Jahanzai6** [comment]
Try to run command
npm i

then delete the app and reinstall it .

**Comment by Jahanzai6** [comment]
add package in the MainApplication.java in following way.
packages.add( new RNFirebaseAuthPackage());

**Comment by Jahanzaib320** [comment]
@impaaras @codexjoshy
I would suggest you not to use expo.  Expo comes with limitations. 

Try to add package in the MainApplication.java in following way.
packages.add( new RNFirebaseAuthPackage());

2) npm I

3) Uninstall the app and reinstall it

**Comment by WilliamSilveiraF** [comment]
I got this error because i had "@react-native-async-storage/async-storage" and "@react-native-community/async-storage"(deprecated) installed at my packages

**Comment by ceconcarlsen** [comment]
This is how i solved my issue: 

RN 0.6+ (autolinking)

android/app build.gradle

`dependencies {
   implementation project(path: ":@react-native-firebase_auth")
}
`

settings.gradle

`include ':@react-native-firebase_auth'
project(':@react-native-firebase_auth').projectDir = new File(rootProject.projectDir, './../node_modules/@react-native-firebase/auth/android')`

**Comment by mikehardy** [comment]
@ceconcarlsen that defeats auto-linking in react-native and is a sub-standard solution. No one should follow that suggestion, and you should determine why auto-linking is not working for you so your project is fixed in general

**Comment by omivrex** [comment]
@codexjoshy I am using expo-dev-client I fixed this by uninstalling the dev-client app and re-building it.

**Comment by gosunman** [comment]
yeah instead of `expo start --dev-client`

run `expo run:android` and `expo run:ios` each
then it will rebuild and run correctly.
