### ISSUE TITLE
Any plan to support FirebaseUI?

### ISSUE THREAD

**Issue by vincent0225** [invertase/react-native-firebase#98]
Hello, 
Thanks for the awesome library.
Is there any plan to support FirebasUI to display image in image view?

https://firebase.google.com/docs/storage/android/download-files#downloading_images_with_firebaseui

https://firebase.google.com/docs/storage/ios/download-files#downloading_images_with_firebaseui

**Comment by Ehesp** [comment]
Hey, we've not really looked at this before. Generally I'm not sure what benefit it would provide? With RN it makes it simple to pull in and display an image?

Are you looking for something like the below to be possible?

```js
import { Image } from 'react-native-firebase';

...

render() {
  return <Image ref="some/storage/ref" />
}
```

**Comment by Colmea** [comment]
^  Would be awesome !

**Comment by Ehesp** [comment]
I'm really not sure there's any point in using a native module for this. RNFirebase exposes the methods needed to handle this, you could quickly make a custom image component:

```js
import React from 'react';
import { Image } from 'react-native';

export default class extends React.Component {
  static propTypes = {
    ref: React.PropTypes.string.isRequired,
  }

  constructor() {
    super();
    this.state = {
      downloadUrl: '',
    };
  }

  componentDidMount() {
    firebase.storage().ref(this.props.ref)
      .getDownloadURL()
      .then((downloadUrl) => this.setState({ downloadUrl });
  }

  render() {
    if (!this.state.downloadUrl) return null; // or placeholder

    return (
      <Image
        source={{ uri: this.props.downloadUrl }}
        {...this.props}
      />
    );
  }
}
```

**Comment by Colmea** [comment]
You're right, I don't see this component as part of RNFirebase, but it's a good idea for a separate plugin !

**Comment by Ehesp** [comment]
Out of the scope of this project I think. Maybe something to look into in the future once the core API is stable.

**Comment by erezrokah** [comment]
Hello, we wrote a small wrapper (only supports images for now) on top of FirebaseUI:
https://github.com/rmrs/react-native-firebaseui

This is our first attempt of writing React Native UI components (the library is still consider alpha), but we've been running with it for two weeks and it made our application(s) much faster.

**Comment by paramaggarwal** [comment]
I am interested in `FirebaseUI` so that I can use Phone Auth without writing logic to detect current country code and providing a picker for it, and writing validation logic and UI for the verification code. Kindly consider this use case.

**Comment by jundelikwo** [comment]
It would be great if we could use `FirebaseUI` for auth

**Comment by maxime-aubry** [comment]
Indeed, provide an interface would be great !
