### ISSUE TITLE
Authentication not consistently persisting between sessions

### ISSUE THREAD

**Issue by wbattel4607** [invertase/react-native-firebase#980]
### Issue

Some of our users (about 20% at this point) are losing their authentication between sessions. This includes terminating the app, or simply leaving it in the background for a while. The effected users have to re-login every session. For those 20% it is happening very frequently. 

We offer both Facebook and Phone authentication. The problem is not discriminating between providers- both are experiencing this.

This is the onAuthStateChanged subscription code in our root component.
```
componentDidMount() {
    this.unsubscribeFromAuth = Firebase.auth().onAuthStateChanged((user) => {
        if (user && user.uid) {
            Firebase.auth().currentUser.getIdToken(true).then((token) => {
                if (!token) {
                    Helpers.logout(false);
                }
                else {
                    // init rest of app, send user to primary navigation component, etc...
                }
            })
            .catch(() => {
                Helpers.logout(false);
            });
        }
        else
            // send user to login screen
    });
}

componentWillUnmount() {
    if (this.unsubscribeFromAuth) {
        this.unsubscribeFromAuth();
        this.unsubscribeFromAuth = null;
    }
}
```

This is the logout method. If the parameter passed is `false`, an error message appears. The users getting logged out are not getting the error message. We have confirmed that the error message is functioning properly for other cases. This means that the logout() function isn't being called.
```
logout(intentional) {

    const logoutMessage = (intentional) ? 'You have been logged out.' : 'Sorry! Something went wrong and you were signed out.';
    // show logoutMessage

    Firebase.auth().signOut().then(() => {
        console.log('signed out');
        LoginManager.logOut();
        Firebase.analytics().logEvent('logout', { error: (intentional) ? 0 : 1 });
        return Storage.delete('credential');
    })
    .then(() => {
        console.log('deleted credential');
        // go to login screen
    })
    .catch((error) => {
        Log.error(error);
        // go to login screen
    });
}
```

It is possible that this is related to #962. There seems to be a correlation between the users affected by both issues, but it is not a 100% match by any means.

### Environment

1. Application Target Platform: iOS (we target both but do not have enough Android users to know if it is affecting Android)

2. Development Operating System: macOS High Sierra

3. Build Tools: Xcode 9.2, iOS 10.0 through 11.3

4. React Native version: 0.54.4

5. RNFirebase Version: 3.3.1

6. Firebase Module: Authentication

Any ideas? Thanks!

**Comment by wbattel4607** [comment]
Actually, this seems to be affecting closer to 40% of our users, who have to re-login every time. This is a very UX-breaking issue that we're not sure how to deal with.

**Comment by wbattel4607** [comment]
> Can I ask why you're doing this part?

We call `Firebase.auth().currentUser.getIdToken(true).then((token) => { ... }` because after the user is logged in we immediately need the token to attach to our location service HTTP POST URL so that its requests are authenticated.

> When you say an error appears - how are you presenting this to your user?

If there is ever an explicit error with authentication, we log the user out, send them to the login screen, and display an error message. This mostly applies to edge cases where the authentication may expire or be otherwise invalidated mid-session. However, in this case the user is sent to the login screen without any error message after having authenticated in a recent session.

When the app boots, we subscribe to `onAuthStateChanged` and then wait for the callback. If the callback indicates they are authenticated, then they get sent into the app. If they're not authenticated, they start on the login screen. The latter is happening for these users. They get no error message, they just get sent to the login screen. This suggests that the `user` parameter could be coming back as undefined.

> I'm assuming you haven't been able to reproduce locally at all?

I have not been able to reproduce this myself yet. I'm only going off of reports from our users. It seems to consistently affect a select number of users. In other words, only X% of **devices/users** are affected, rather than X% of **sessions**.

**Comment by chrisbianca** [comment]
I'll have a chat with @Salakar and talk through this change to confirm it won't affect anything else then try and get a release out.

Is there any pattern to the type of devices that are experiencing this issue?  Are they newer, faster devices? Or older, slower devices? Or is it just random?  Seems odd that it's the same users/devices that are seeing the issue rather than just a percentage of sessions unless there is some correlation in the performance of the devices...

**Comment by chrisbianca** [comment]
I've just published v4.0.6 which has this possible fix in - it would be great if you're able to roll this out and see whether it addresses your issues?

**Comment by wbattel4607** [comment]
Sounds good. We're shipping a new version in the next 36 hours, we'll update to 4.0.6 and see what happens.

**Comment by chrisbianca** [comment]
@wbattel4607 Have you had a chance to get this released and tested?

**Comment by wbattel4607** [comment]
We've released it and are monitoring for any changes in behavior. I'll let you know what we find.

**Comment by chrisbianca** [comment]
Perfect, thanks. Fingers crossed!

**Comment by chrisbianca** [comment]
@wbattel4607 How's this looking?

**Comment by wbattel4607** [comment]
We've been getting fewer reports, although I am hesitant to say it's resolved yet. If you would like to close the issue, go ahead. If we should discover the problem persists we can create a new issue and reference this one.

**Comment by chrisbianca** [comment]
Will do, thanks.

**Comment by Vindexus** [comment]
@chrisbianca can I ask what was the issue here? I'm encountering a similar issue with Firebase Auth in an Angular project and am having trouble narrowing it down.

**Comment by delavago** [comment]
currently have the same issue in my application. i use firestore listeners to stream data into the application but after being left in the background for lets say 2 hours or more and going back to the application the app no longer recieves data from firestore. User has to log out and login back with firebase auth to get it working again. which indicates to me that its an auth issue

**Comment by ankitbishtapollo** [comment]
Any updates on this?

**Comment by mikehardy** [comment]
@ankitbishtapollo this issue was opened in 2018, and closed in 2018. Why would there be any updates on a 2 year stale issue? If you have problems with current stable versions please open a new issue and respect the template, then people can try to help

**Comment by ankitbishtapollo** [comment]
Ok @mikehardy will raise a new ticket. You can close this
