### ISSUE TITLE
Firebase crashlytics do not show the dashboard and redirect to Fabric

### ISSUE THREAD

**Issue by assurancetourix** [invertase/react-native-firebase#981]
Hello,

I have struggled a bit about this issue, and I am not really sure what brought about this behaviour.
After installation of rnfirebase crashlytics, I was presented in firebase console a link to manage crashlytics via the fabric website (details are in this blog post https://firebase.googleblog.com/2018/03/firebase-crashlytics-graduates-from-beta.html)

Once I have updated google services (from 3.1.2 to 3.2.0) in the project gradle.build, I finally manage to get the dashboard, but honestly I cannot be sure that this was the cause.

```
buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.fabric.io/public'
        }
        google()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'

        classpath 'com.google.gms:google-services:3.2.0'
        //classpath 'com.google.gms:google-services:3.1.2'
```
Does someone experienced this behaviour ?
Should this be updated in the documentation?
https://rnfirebase.io/docs/v4.0.x/crashlytics/android

Many thanks.

**Comment by chrisbianca** [comment]
@assurancetourix I'm not quite sure what you'd like from us here? My assumption is it took a while for the dashboard to update with the fact you're using Crashlytics.

Please re-open if you'd like something specific from us
