### ISSUE TITLE
Firebase Dashboard no data

### ISSUE THREAD

**Issue by serbol** [invertase/react-native-firebase#989]
In Firebase Dashboard is no data, but app was installed on several devices. Also on emulators. Data are seen only in StreamView. What could be the reason of this problem?

**Comment by nkov** [comment]
It takes time for the changes to propagate to the rest of the Firebase dashboard.

**Comment by Salakar** [comment]
As @nkov correctly pointed out - it does takes several hours for analytics events to show in the dashboard. Use the debug view and stream view to view them closer to real-time.
