### ISSUE TITLE
Website is down 522!

### ISSUE THREAD

**Issue by koloff** [invertase/react-native-firebase#990]
Hi! Your website seems to return error 522: connection timed out!

**Comment by Salakar** [comment]
@koloff hmm can't see any down websites - which website was it?

**Comment by koloff** [comment]
https://rnfirebase.io/ returns Error 522 Ray ID: 40d135b05daf4038 • 2018-04-17 19:14:05 UTC.
My friends confirmed and I even tried opening it through European and US proxies.

**Comment by judemanutd** [comment]
Working fine here, logging in from India

**Comment by Salakar** [comment]
Working here in the UK as well, where are you requesting from @koloff?

**Comment by koloff** [comment]
I am in Bulgaria.

**Comment by Salakar** [comment]
Weird, definitely showing as working around the world on the console. 

It's hosted with firebase hosting so nothing fancy either, might just be a IP restriction on firebase hosting for your region/IP range - out of our control unfortunately, sorry. 

If it helps, the docs are also sourced from GitHub: https://github.com/invertase/react-native-firebase-docs - there's a branch per version.
