### ISSUE TITLE
android sdk version

### ISSUE THREAD

**Issue by rendomnet** [invertase/react-native-firebase#995]
### Issue

In the installation docs https://rnfirebase.io/docs/v4.0.x/installation/android written that we need to use gradle version v4.4
And gradle v4.4 needs android sdk version 27.0.3
But react native suggest using sdk version 23
What should we use documentation says nothing about sdk version change.

### Environment

Application Target Platform: Android
Development Operating System: Mac os
React Native version: 54.4
RNFirebase Version: 4.0.3

**Comment by judemanutd** [comment]
I'm currently using the library with the latest version that is 27.0.3, everything works fine, react native suggests that mainly because they have tried and tested everything on that version and can safely guarantee that all apis work on it

**Comment by aMarCruz** [comment]
@judemanutd are you also using support libraries 27.1.1?

**Comment by judemanutd** [comment]
Yes correct

**Comment by jeanregisser** [comment]
@judemanutd did you test Android release builds?
Aren't you affected by https://github.com/facebook/react-native/issues/16906#issuecomment-382605516 ?

**Comment by judemanutd** [comment]
@jeanregisser working fine, just built a release build on my app and it built with no errors.

**Comment by judemanutd** [comment]
@aMarCruz I built a release apk and tested all the functionality built into my app and it worked without any errors, my app consists of infinite scrolls, tabs, image displays, notification support, html rendering and Web views. Is there any functionality in particular that is known to crash with the latest build? I could check it out.

**Comment by aMarCruz** [comment]
@judemanutd , I just checked my App with v27.1.1 and everything looks fine, thanks!

**Comment by jeanregisser** [comment]
Tried again this morning following @judemanutd config.
The release build did work without complaining (`./gradlew assembleRelease`).

However, bundle assets (images used like this `<Image source={require("./my_image.jpg")} />` were not part of the final APK.
Though the build process did mention assets being copied:

```
> Task :app:bundleReleaseJsAndAssets
Scanning folders for symlinks in /Users/jean/xxx/node_modules (12ms)
Scanning folders for symlinks in /Users/jean/xxx/node_modules (10ms)
Loading dependency graph, done.
warning: the transform cache was reset.
bundle: Writing bundle output to: /Users/jean/xxx/android/app/build/intermediates/assets/release/index.android.bundle
bundle: Done writing bundle output
bundle: Copying 1 asset files
bundle: Done copying assets
```

**Comment by judemanutd** [comment]
@jeanregisser instead of using `require` I have imported the image into the component.

`import example_image` from '../assets/example.png'

**Comment by jeanregisser** [comment]
Ok, tried it, same effect.
require and import should be equivalent.
Unless you have a custom babel step that turns that import into embedded base64 data.
Is this what you're doing?

**Comment by judemanutd** [comment]
@jeanregisser No extra step just a simple import and it works. Are you using the latest react and react-native versions?

**Comment by jeanregisser** [comment]
yep latest published, started the project from scratch yesterday:

```json
"dependencies": {
  "react": "16.3.1",
  "react-native": "0.55.3",
  "react-native-firebase": "^4.0.5"
},
```

**Comment by chrisbianca** [comment]
I believe this has been resolved now, so I'm going to close.
Please let me know if you feel there's anything we need to do our end...
