### ISSUE TITLE
Local Notification not working in background

### ISSUE THREAD

**Issue by kishanj918** [invertase/react-native-firebase#996]
Hello there,

I integrated cloud messaging as well as notification new concept of version 4.0.x

### Issue

local notification working well when my app is in foreground, but after i setup repeatInterval as mention [here](https://rnfirebase.io/docs/v4.0.x/notifications/reference/Schedule#repeatInterval), i try it in background and it's not showing up.

in my case, i have many articles in my realm database & i have to show notification to user on every morning 8AM & every evening 8PM.
but if Application will Closed, then it will not show up.

here is my sample code 
`    const date = new Date();
    date.setMinutes(5, 0, 0);

    const notification = new firebase.notifications.Notification()
    .setNotificationId(Date.now()+'')
    .setSound('default')
    .setTitle("test title")
    .setBody("test body");

    notification
    .android.setChannelId('channelId')
    .android.setBigPicture(
        "https://image.winudf.com/v2/image/Y29tLmFsZmFwaXhlbC5tYWhhZGV2aGR3YWxscGFwZXJfc2NyZWVuXzFfbGtzbzJwZGc/screen-1.jpg?h=355&fakeurl=1&type=.jpg",
        'https://www.google.co.in/images/branding/product/ico/googleg_lodp.ico', 
        "test title 1", 
        "test title 2");

    firebase.notifications().scheduleNotification(notification, {
        fireDate: date.getTime(),
        repeatInterval : "minute"
    });`

### Issue update
if i remove,
`.android.setBigPicture()`
portion, it's working fine.

### Environment

1. Application Target Platform: Both

2. Development Operating System: macOS sierra

3. Build Tools: 27

4. React Native version: 0.53.0

5. RNFirebase Version: react-native-firebase@4.0.3

6. Firebase Module: FCM & Notification

**Comment by chrisbianca** [comment]
Sorry for the delay, and thanks for the detailed error report and reproduction steps.
This has now been fixed and will be released as part of v4.0.7 later today
