### ISSUE TITLE
firebase auth().getIdToken() crash on ios when a facebook user is authenticated on firebase

### ISSUE THREAD

**Issue by mowbell** [invertase/react-native-firebase#997]
### Issue
It is really a firebase sdk issue, but is related here =
When is called method **getIdToken** of Auth module with an authenticated user using facebook credentials, app crashes on ios
It doesn't happen with password/email authenticated user

The issue is fixed downgrading Pod dependency (on Podfile.lock) installed when run `pod install` version of **Firebase/Auth** from 4.13.0  to 4.11.0 and all works again

I suggest update docs like firebase ios sdk does,
`pod 'FirebaseAuth', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '4.11.0'`
and so
Look it at:
[https://github.com/firebase/firebase-ios-sdk#installation](firebase ios sdk installation)

### Environment 
iOS

1. Application Target Platform: macOS Sierra
2. Development Operating System: Xcode
3. Build Tools:
4. React Native version: 0.54.4
5. RNFirebase Version: 4.0.3
6. Firebase Module: Auth

**Comment by wbattel4607** [comment]
This seems to be an iOS SDK issue. They have an issue open on that repo, here: https://github.com/firebase/firebase-ios-sdk/issues/1140

**Comment by Salakar** [comment]
Thanks for flagging, will close this as it's a Firebase SDK issue - looks like they have a fix on master already as well.

**Comment by wbattel4607** [comment]
I can't get my project to build, regardless of what version I use, including the suggested fix from @mowbell. I mentioned it on the native iOS SDK issue ([here](https://github.com/firebase/firebase-ios-sdk/issues/1140#issuecomment-385124344)) but the build error is coming from `react-native-firebase`. This particular build error does not seem to come from the native iOS SDK but I may be wrong.

This is what Xcode is throwing me.
<img width="852" alt="screen shot 2018-04-27 at 7 16 57 pm" src="https://user-images.githubusercontent.com/13490339/39391140-7b3a7e42-4a64-11e8-8532-f515c63167d9.png">

I cannot get either of these to work. They both throw the same error above.
```
  pod 'Firebase'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios/RNFirebase.podspec'
  pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'staging-4.13.1'
  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'FirebaseAuth', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'staging-4.13.1'
  pod 'Firebase/Database'
  #pod 'Firebase/DynamicLinks'
  #pod 'Firebase/Firestore'
  #pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'
```
```
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios/RNFirebase.podspec'
  pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '4.11.0'
  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'FirebaseAuth', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '4.11.0'
  pod 'Firebase/Database'
  #pod 'Firebase/DynamicLinks'
  #pod 'Firebase/Firestore'
  #pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'
```

If we forgo the manual version on the pods, we get the getIdToken crash, so we can't do that either.
```
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios/RNFirebase.podspec'
  pod 'FirebaseCore'
  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  #pod 'Firebase/DynamicLinks'
  #pod 'Firebase/Firestore'
  #pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'
```

I'm using version `4.0.6` of `react-native-firebase` and `0.55.3` of `react-native`.

Any ideas? The native SDK won't be getting a release with the fix until mid-May and we cannot afford to wait that long.

**Comment by wbattel4607** [comment]
@Salakar do you have any ideas on how I can get around this until 5.0.0 of the native SDK is released? We can't build our project at all.

**Comment by chrisbianca** [comment]
@wbattel4607 can you try the fix that's been suggested here? https://github.com/invertase/react-native-firebase/pull/1017

**Comment by Soren-Knudsen** [comment]
@wbattel4607 : Did you find temp solution?
