### ISSUE TITLE
Notification Logo white square

### ISSUE THREAD

**Issue by poptocrack** [invertase/react-native-firebase#999]
### Issue

On android only, when I display the raw notification there is the top notification, and if I use `.android.setLargeIcon('ic_launcher')`, I have the normal notification logo but on some devices (Samsung S7 with android 6.0.1) a grey round with a white square is displayed for no reason.

The issue seems to depend on the phone model and not of the android version.

Tested on my side:
Galaxy S7 edge, Android 6.0.1 => behavior is present
Huawei Y6, Android 6.0 => not present

Tested by discord users:
Nexus 7 tablet, Android 6.0.1 => present
Galaxy note8 Android 8.0.0 => not present

Redmi Note 3 => not present
(Not device precised) 8.1.1 emulator => present

![](https://cdn.discordapp.com/attachments/431316367447293952/436184009106522113/unknown.png)

By the way, in the top notification, default behavior should be a "full screen" logo

### Environment

Android only

1. Application Target Platform:

macOS Sierra

2. Development Operating System:

Android studio

3. Build Tools:

4. React Native version:

0.54 (Expo detached sdk 26)

5. RNFirebase Version:

v4.0.3

6. Firebase Module:

Notifications

**Comment by Salakar** [comment]
@poptocrack the white square is correct - this is android behaviour - to show something better there you should create a mipmap version of your logo in white+transparent.

[![image](https://user-images.githubusercontent.com/5347038/39084291-4658ee32-456b-11e8-8393-9a2917f5c35f.png)](https://stackoverflow.com/questions/30795431/icon-not-displaying-in-notification-white-square-shown-instead)


You could get the android version from RN import and adjust your small icon accordingly when you create your notification based on the platform - as in the code example in the above SO post (but not in java 😛 ).
